[msg SYS_039_0_0]
[s][vp 1 0 0 0 0 0]The battle took ○○ turns...[n][f 1 3 65535][w][e]

[msg MSG_063_0_0 [Caroline]]
[s][bup 0 102 3 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Pitiful.[n][f 1 3 65535][w][e]

[msg MSG_064_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Allow me to disclose the results of our[n]examination.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]If I had to describe your current state...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]I would say you are: One Who Has Yet[n]to Learn His Place in the World.[n][f 1 3 65535][w][e]

[msg MSG_065_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]You were probably feeling all confident[n]in yourself when you challenged us, right?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]There's nothing you can say after a[n]miserable defeat like that though.[n][f 1 3 65535][w][e]

[msg MSG_066_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]However, it would not be interesting if[n]you quit here.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Accept this. Think of it as... a participation[n]award.[n][f 1 3 65535][w][e]

[msg MSG_067_0_0 [Justine]]
[s][bup 0 101 2 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Prepare well if you wish to hold a true[n]battle. Ordinary effort alone cannot[n]overturn this result.[n][f 1 3 65535][w][e]

