[msg MSG_000_0_0 [Caroline]]
[s][bup 0 102 5 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]We... lost?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]To a human?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 1 301 1][vp 8 0 0 3 65535 0]Hahaha! I can't believe this actually[n]happened to us! It's a little strange...[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Even though I should feel humiliated,[n]I feel... refreshed. Like I finally was[n]able to leave something behind.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [(SE)カロリーヌ]]
[s][vp 8 0 0 5 65535 0](朗らかな笑い)[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Hah... Our sisters are gonna get[n]mad at us.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]It turns out even the rulers of power[n]can't measure everything![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Justine]]
[s][bup 0 101 4 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Sisters? Rulers of power?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Caroline, what did you just...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Hm? Did I say something weird?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Justine]]
[s][bup 0 101 0 0 0][vp 1 0 0 11 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Justine]]
[s][bup 0 101 2 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Inmate. It seems the time has come for us[n]to fulfill our promise.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]I will now tell you our embarrassing secret.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 7 301 1][vp 8 0 0 14 65535 0]What!? We still have to do that!?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Justine]]
[s][bup 0 101 2 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]To be perfectly honest...[n][f 1 3 65535][w][e]
[s][bup 0 101 3 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]From time to time, a strange feeling[n]of unease falls over us.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]It is almost as though we are not[n]ourselves, or that our true selves[n]are in a place far, far away.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Huh?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Justine]]
[s][bup 0 101 3 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]We are meant to be leading inmates[n]through rehabilitation, yet we have[n]doubts about our own validity.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Could there be anything more[n]humorous than that?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Oh, so that's what you meant...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Justine]]
[s][bup 0 101 2 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Are you not ashamed, Caroline?[n]What did you think I was going[n]to talk about?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Perhaps the time you nearly wept[n]from fear when you first witnessed[n]a Persona fusion?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 7 301 1][vp 8 0 0 24 65535 0]Wha—!?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Justine]]
[s][bup 0 101 2 0 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Or about those intimidating poses[n]you had practiced, that you're too[n]embarrassed to use on the inmate?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Caroline]]
[s][bup 0 102 4 0 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]S-Stop! My heart can't take this![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [(SE)ジュスティーヌ]]
[s][vp 8 0 0 27 65535 0](呆れた溜め息)[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Justine]]
[s][bup 0 101 2 0 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]After I lost to you... albeit for a brief[n]moment... I saw something.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]It was then that I knew for certain...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Just as you have your goal of[n]rehabilitation, we too have an[n]objective we must achieve.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]We're supposed to act as wardens for[n]our master, right?[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Justine]]
[s][bup 0 101 2 0 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Then how do you explain this? It is[n]completely unrelated to that task.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Caroline]]
[s][bup 0 102 3 0 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Well, um...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]...Inmate. I will now disclose the results[n]of our examination.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]If I had to describe your current state...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]I would say you are: He Who Will Save[n]the Souls of Humanity.[n][f 1 3 65535][w][e]

[msg MSG_022_5_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]To commemorate your victory,[n]I entrust this bookmark to you.[n][f 1 3 65535][w][e]

[sel SEL_023_0_0 top]
[s]Thanks.[e]
[s]You don't mind?[e]

[msg MSG_024_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]I require no thanks... After all, I am the[n]one forcing my own issues upon you.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]If you continue to hold ties with us,[n]we will surely arrive at the truth.[n][f 1 3 65535][w][e]
[s][bup 0 101 1 0 0][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]That is how I feel.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Caroline]]
[s][bup 0 102 5 0 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]Ugh. I stay quiet and you just gotta[n]go saddling him with more work.[n][f 1 3 65535][w][e]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Well, I won't tell our master about this.[n]It'll just be one of our secrets.[n][f 1 3 65535][w][e]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]Wait—speaking of secrets, you only told[n]him mine! This isn't fair![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Justine]]
[s][bup 0 101 3 0 0][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]You would like one from me?[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Justine]]
[s][bup 0 101 3 0 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Recently, whenever the inmate takes[n]prolonged absences from our chamber...[n][f 1 3 65535][w][e]
[s][bup 0 101 6 0 0][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]...I miss him.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Justine]]
[s][bup 0 101 6 0 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]According to human standards, directly[n]conveying this emotion may be somewhat[n]uncomfortable...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]But that is how I feel...[n][f 1 3 65535][w][e]

[msg MSG_029_5_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]Caroline is probably the same way.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Caroline]]
[s][bup 0 102 7 0 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]I...![n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Justine]]
[s][bup 0 101 6 0 0][f 4 10 65535 0 0][vp 8 0 0 119 65535 0]I simply... wanted you to know.[n][f 1 3 65535][w][e]
[s][bup 0 101 2 0 0][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]Oh, you understand this is a secret to be[n]kept between us, yes?[n][f 1 3 65535][w][e]

[sel SEL_032_0_0 top]
[s]Thanks.[e]
[s]I can't choose between you.[e]

[msg MSG_033_0_0 [Caroline]]
[s][bup 0 102 6 0 0][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]Sh-Shut up! She just said it's a secret![n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]Choose? I mean, if you did,[n]the other would feel bad.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]How should I say this...? I would not[n]resist you choosing the both of us.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 55 65535 0]Is that strange?[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 56 65535 0]O-Okay, that's enough of that.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 57 65535 0]...Yes. Any further discussion may[n]interfere with our work.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 58 65535 0]Things are gonna go back to how they[n]were before. This special inspection was[n]a one-time deal.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 59 65535 0]Though... I think we might feel a little[n]differently when we're watching over[n]you from now on...[n][f 1 3 65535][w][e]

[msg MSG_038_5_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 15 301 1][vp 8 0 0 60 65535 0]That means we're gonna be stricter than[n]ever! Y-You got that, Inmate!?[n][f 1 3 65535][w][e]

