[msg MSG_000_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 7 301 1][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]What the...!?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sumire]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]This is...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]This appears to be quite the paradise.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]I assume Maruki's trying to convey that[n]the world will turn into something like[n]this if we allow him to abuse his research.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]A paradise...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Wait, but this is a dead end, right? And[n]we still haven't found the Treasure...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Look again.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]The shimmery thing?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]No doubt about it—that's our Treasure![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]That also means we've secured our[n]route.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]All right! All we got left is sendin'[n]the calling card—[n][f 1 3 65535][w][e]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 4 100][vp 8 0 0 12 65535 0]Oh, wait. How are we suppose'ta do that[n]this time?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]That's right, Dr. Maruki's been here in[n]the Palace this entire time, hasn't he?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]I'm sure Maruki's well aware that the[n]Phantom Thieves send out their calling[n]cards the day before their heists.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Considering his actions up until now,[n]I highly suspect he'll attempt to directly[n]intervene in some way that day...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]My money's on him trying it with Joker.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Good point. In that case, I'll leave the[n]calling card in your hands, Joker.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][bup 0 9 811 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]We could just set up an ambush and[n]destroy him once he steps in our trap,[n]too.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]No way are we doin' that![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Our goal in coming here is to return[n]reality to its original state, not to beat up[n]Dr. Maruki.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Akechi]]
[s][bup 0 9 813 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]It was merely a joke.[n][f 1 3 65535][w][e]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]After all, you're all well-aware that[n]Maruki's influence on reality goes well[n]beyond this Palace...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]If we make the wrong move in here, we[n]could get eliminated outside the Palace, since[n]we lack our Personas there.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Akechi]]
[s][bup 0 9 811 0 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]It'd be a safer strategy to change Maruki's[n]heart, just as you all wish.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]We're finally changing his heart...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]If we steal Dr. Maruki's Treasure,[n]everything'll go back to the way[n]it was, right?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]I don't know for sure, but most likely.[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]Are you okay with that?[e]
[s]Can you do this?[e]

[msg MSG_021_0_0 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Yeah! Of course.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]We've all come so far... We can't just[n]give up now.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]We gotta stick to our own reality.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]About the time limit—Dr. Maruki told[n]you it was [clr 2]February 3rd[clr 27], correct?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Yeah.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]He isn't like anything we've faced[n]before... We should get as strong[n]as we can before that fight.[n][f 1 3 65535][w][e]

