[msg MSG_000_0_0 [Maruki]]
[s][bup 0 216 163 0 0][f 4 10 65535 0 0][vp 8 0 0 1 5 0]Sorry to cut your flight short like that.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Maruki]]
[s][bup 0 216 163 0 0][f 4 10 65535 0 0][vp 8 0 0 2 5 0]...This place is done for.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 5 0]Along with the entire reality[n]I dreamed of...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Maruki]]
[s][bup 0 216 163 0 0][f 4 10 65535 0 0][vp 8 0 0 4 5 0]I... have lost.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 5 0]Even if I were to try that fight over,[n]I'm sure I'd only lose again.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Maruki]]
[s][bup 0 216 163 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 5 0]So I know... this is going to sound[n]pretty stupid.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 5 0]I've been holding this all in for so long,[n]just hiding it from myself...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 5 0]So, please...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Maruki]]
[s][bup 0 216 162 0 0][f 4 10 65535 0 0][vp 8 0 0 9 5 0]Help me kill every last one of my[n]regrets.[n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [Maruki]]
[s][bup 0 216 162 0 0][f 4 10 65535 0 0][vp 8 0 0 10 5 0]You're the only one I can ask to help me[n]with this, [f 4 1]-kun.[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Very well.[e]
[s]I'm here for you.[e]

[msg MSG_006_0_0 [Maruki]]
[s][bup 0 216 603 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]The disappearance of my Palace—of the[n]entire Metaverse—is drawing near.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Seems like neither of us can summon[n]our Personas anymore.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Maruki]]
[s][bup 0 216 602 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Let's begin.[n][f 1 3 65535][w][e]

