[msg MSG_000_0_0 [Maruki]]
[s][bup 0 216 145 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Why...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]I gave up everything else... I dedicated[n]all that I have to this... But I still... Why?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]You're running from the past.[e]
[s]You're denying reality.[e]

[msg MSG_002_0_0 [Maruki]]
[s][bup 0 216 144 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]I'm... running from...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Maruki]]
[s][bup 0 216 144 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]You mean... I'm running away from it all?[n][f 1 3 65535][w][e]
[s][bup 0 216 143 0 0][vp 1 0 0 5 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Maruki]]
[s][bup 0 216 141 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]...Heheh.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]You nailed it.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Maruki]]
[s][bup 0 216 143 0 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 115 3 300 65535][vp 8 0 0 8 65535 0]It's true that I turned my back on the[n]original reality...[n][f 1 3 65535][w][e]

[msg MSG_005_5_0 [Maruki]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 115 3 300 1][vp 8 0 0 9 65535 0]But where's the harm in that!?[n][f 1 3 65535][w][e]
[s][bup 0 216 143 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]When it grows to be too much, too[n]painful... Every person deserves to[n]escape that![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sumire]]
[s][bup 0 10 103 0 0][vp 1 0 0 11 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Maruki]]
[s][bup 0 216 142 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]In all honesty, it's best for a person's[n]growth when they tackle their own[n]hardships...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]But reality doesn't always make that[n]so feasible![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]No matter how much you try, or work[n]for so long, the smallest injustice can[n]wipe it all out, leave you with nothing...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Maruki]]
[s][bup 0 216 142 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Don't you, of all people, understand[n]that!?[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]You have to look to the future.[e]
[s]Even then, you keep going.[e]

[msg MSG_009_3_0 [Maruki]]
[s][bup 0 216 143 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Ngh...[n][f 1 3 65535][w][e]

[msg MSG_009_5_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]We're not saying you're wrong there.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Living with this guy's made me realize[n]that life in the actual reality can be[n]way too cruel sometimes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Still! Did he run away from his life[n]because of that? No, he gained more[n]friends, and more Personas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Now he's such an incredible phantom[n]thief, even you and all your godlike[n]powers respect him![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Maruki]]
[s][bup 0 216 144 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]......![n][f 1 3 65535][w][e]

[msg MSG_010_2_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]You know, there probably are plenty of[n]people who'd ultimately benefit from[n]your "reality."[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]But what about the people who want to[n]take on the world themselves? How's it[n]right to rob them of their opportunities?[n][f 1 3 65535][w][e]

[msg MSG_010_4_0 [Haru]]
[s][bup 0 7 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Oh, Mona-chan...[n][f 1 3 65535][w][e]

[msg MSG_010_6_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]There's something I've learned, after[n]all we've been through...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Even if humans can't stand on their[n]own, they can still do it with the help[n]of their friends.[n][f 1 3 65535][w][e]

[msg MSG_010_8_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Don't steal the potential away from[n]humanity![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]You act like this is going to help[n]everyone when it's really just you[n]giving up on them![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Maruki]]
[s][bup 0 216 143 0 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]I've given up on everyone, huh...[n][f 1 3 65535][w][e]
[s][bup 0 216 141 0 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Looks like I'm totally finished.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Maruki]]
[s][bup 0 216 144 0 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]......![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]You know, there probably are plenty of[n]people who'd ultimately benefit from[n]your "reality."[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]But what about the people who want to[n]take on the world themselves? How's it[n]right to rob them of their opportunities?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sumire]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]I don't think what you're saying[n]is wrong either, Dr. Maruki...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Some people want to run from their[n]pain and cling to some other version[n]of reality... Like I used to.[n][f 1 3 65535][w][e]
[s][bup 0 10 102 0 0][f 4 10 65535 0 0][f 4 24 0 12 6 37 3 100][vp 8 0 0 36 65535 0]But the knowledge I gained through[n]that pain, and my desire to move on...[n]Those are even more precious to me![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]And I won't let anyone take them[n]from me again![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Maruki]]
[s][bup 0 216 144 0 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Yoshizawa-san...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Maruki]]
[s][bup 0 216 141 0 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]So you truly don't want it... Huh...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Looks like I'm totally finished.[n][f 1 3 65535][w][e]

