[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Parece otimo ter[n]Todo mundo fala sobre nos, hein?[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]Madarame e o unico topico de[n]conversa na minha escola.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]E como sou o aluno dele, a maioria dos meus[n]Os colegas optaram por me ignorar.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Serio? Isso e treta.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Voce vai ficar bem?[n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]Nao ha necessidade de se preocupar.[n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]Eles ja haviam sido[n]me tratando de maneira diferente[n]de outros como estava.[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Isso nao e novidade para mim.[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]OK entao...[n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Mais importante, temos algum[n]Lidera em nossa proxima missao?[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Esta brincando? Nao ha como nos[n]Encontre um alvo tao rapido![n][w][e]

[sel SEL_011_0_0 top]
[s][f 5 14]Precisamos esperar e ver.[e]
[s]Para lembrancas, vamos![e]

[msg MSG_012_0_0 [Yusuke]]
[s][f 5 14]Entendido.[n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]Oooh, sempre poderiamos ir[n]Em vez disso, lembrar![n][w][e]

[msg MSG_014_0_0 [Ann]]
[s][f 5 14]Boa ideia![n][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Vou me manter livre. Por favor[n]Diga-me se alguma coisa surgir.[n][w][e]

