[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Então, o que acabou acontecendo[n]com o cartão de visita?[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Makoto levou Ryuji com ela.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Ela mencionou especificamente que[n]Ele ficaria bem e nós temos[n]Nada com que se preocupar.[n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]HM? Eu me pergunto o que ela planeja[n]Ao fazer com ele...[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Alguém já ouviu alguma coisa[n]de qualquer um deles?[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]Nada mesmo.[e]
[s]Vamos deixar isso para eles.[e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]Eu vejo...[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Tenho certeza que vai ficar bem se[n]Makoto está lá com ele.[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]Eu definitivamente ficaria preocupado se[n]Ryuji estava indo sozinho.[n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Você tem um ponto.[n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14]Suponho que vamos descobrir[n]amanhã de qualquer maneira. Por enquanto,[n]Devemos descansar um pouco.[n][w][e]

[msg MSG_011_0_0 [Ann]]
[s][f 5 14][f 5 15]Sim, Cya![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1098 65535 0]Finalmente atacamos amanhã. Certificar-se de que[n]you get your prep done—we need to be[n]em melhor forma para isso![n][f 1 3 65535][w][e]

