[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Eu tentei mudar[n]o ícone de bate-papo.[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Parece o mesmo para mim.[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Talvez seja só para o grupo[n]e não aparece aqui...[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Bem, você deve levar[n]um olhar mais tarde.[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]É aquele logotipo Phantom Thieves[n]Eu tinha Yusuke desenhando para nós.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]O cartão de visita acabou[n]Ótima causa dele também.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]De qualquer forma, este é o primeiro emprego[n]Para os ladrões fantasmas. Nós[n]Realmente não consigo estragar tudo, k?[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Eu não estou subestimando[n]Qualquer coisa, eu garanto a você.[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]E verifique se Yusuke recebe[n]Muito descanso hoje, ok?[n][w][e]

[msg MSG_009_0_0 [Ann]]
[s][f 5 14]Sim.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Bem, veja vocês amanhã![n][w][e]

[sel SEL_011_0_0 top]
[s][f 5 14]Entendi.[e]
[s]Noite.[e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14][f 5 15]Vejo você amanhã![n][w][e]

