[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Tudo o que temos a fazer agora e enviar[n]O cartao de visita para Madarame.[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Tudo bem, finalmente chegou a hora![n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Agora tudo o que precisamos fazer e decidir[n]Quando vamos fazer isso.[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Nao devemos falar com Yusuke[n]sobre isso primeiro?[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Uhhh, por que?[n][w][e]

[msg MSG_005_0_0 [Ann]]
[s][f 5 14]Quero dizer, Madarame era seu professor.[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Nao e o nosso lugar para estar[n]decidindo algo assim.[n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]Oh sim...[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]Vamos falar com Yusuke.[e]
[s]Eh, vai ficar bem.[e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]Sim, esse problema e maior do que[n]So nos tres.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Cara, muito egoista?[n][w][e]

[msg MSG_011_0_0 [Ann]]
[s][f 5 14]Enfim, que tal todos nos[n]Encontrar-se no esconderijo?[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]Sim, parece bom.[n][w][e]

[msg MSG_013_0_0 [Ann]]
[s][f 5 14][f 5 15]OK. Deixe-me saber quando voce quer[n]Para me encontrar e eu vou contar a Yusuke.[n][w][e]

