[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Makoto, você está bem? Tem kaneshiro[n]ameaçou você ou qualquer coisa?[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Ele está exigindo dinheiro, mas eu[n]Escolha ignorar essas mensagens.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Tudo bem? Tem algum homem assustador[n]apareceu em sua casa?[n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Não.[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Kaneshiro ainda tem as fotografias[n]Em sua posse, lembra?[n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]Talvez essa vantagem seja por que ele[n]não sente urgência para agir.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Então você acha que somos[n]seguro por enquanto então?[n][w][e]

[sel SEL_007_0_0 top]
[s][f 5 14]Sim.[e]
[s]Estou meio preocupado.[e]
[s]Tudo o que podemos fazer é esperar...[e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]Você está errado.[n][w][e]

[msg MSG_009_0_0 [Ann]]
[s][f 5 14]Como você deveria estar.[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Sim, eu sei como você se sente.[n][w][e]

[msg MSG_011_0_0 [Ann]]
[s][f 5 14]Assim como Yusuke disse, aqueles[n]As fotos são más notícias para nós.[n][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][f 5 14]Precisamos mudar de Kaneshiro[n]coração o mais rápido possível.[n][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][f 5 14][f 5 15]Concordou. eu farei[n]tudo o que posso para ajudar.[n][w][e]

