[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Os ladrões fantasmas, hein...[n]Estou gostando do som disso![n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Espero que possamos realmente ajudar as pessoas.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Estou curioso sobre aquele fantasma[n]Site aficionado também.[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Eu me pergunto quem fez isso...[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Sem pista.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Mais importante, você vê[n]a pesquisa aí?[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14]Não sei como me sinto sobre isso.[n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14]Sim, houve essa aprovação[n]coisa de classificação, mas foi apenas[n]a seis por cento...[n][w][e]

[sel SEL_012_0_0 top]
[s][f 5 14]Isso é baixo.[e]
[s]Isso é melhor do que eu esperava.[e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]Sim.[n][w][e]

[msg MSG_014_0_0 [Ann]]
[s][f 5 14]Eu acho que não é tão ruim se[n]Você coloca assim...[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14]Mas você não quer ficar[n]É mais alto que isso?[n][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][f 5 14]Aposto que vai subir toneladas se nós[n]Continue derrubando grandes alvos.[n][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][f 5 14]É muito emocionante se você[n]Tente pensar sobre isso assim.[n][w][e]

[msg MSG_018_0_0 [Ann]]
[s][f 5 14]Você sabe, você está realmente certo.[n][w][e]

[msg MSG_019_0_0 [Ann]]
[s][f 5 14][f 5 15]Bem então, vamos continuar trabalhando[n]Hard a partir deste ponto![n][w][e]

