[msg MSG_000_0_0 [Haru]]
[s][f 5 14]Finalmente fomos capazes de conseguir[n]no salão de montagem principal.[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Isso significa que estamos prontos para[n]Envie o cartão de visita também.[n]Quando devemos fazer isso?[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Devemos considerar o método por[n]que enviaremos também.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Todos aqueles caras torcendo por[n]É melhor Shido estar pronto.[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Vamos surpreender o[n]merda fora deles![n][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][f 5 14]Eu não posso esperar por isto.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]BTW, onde está Makoto? Ela é[n]Neste bate-papo, certo?[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]Sim, não se preocupe. Eu tenho[n]tenho lido isso.[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]Algo está errado?[e]
[s]Você parece ansioso.[e]
[s]O que está em sua mente?[e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]Nós iremos...[n][w][e]

[msg MSG_010_0_0 [Haru]]
[s][f 5 14]É sobre Akechi-kun, é[n]não? Isso foi realmente triste o que[n]aconteceu com ele...[n][w][e]

[msg MSG_011_0_0 [Haru]]
[s][f 5 14]Honestamente, tenho sentimentos confusos...[n]Mas acho que ele também foi uma vítima.[n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14]Uma vítima que não podíamos salvar...[n][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][f 5 14]Se eu não tivesse conhecido todos vocês, posso[n]também se tornaram como ele...[n][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14]Pessoalmente falando, eu[n]Não pode perdoar o cara.[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14]Mas o mais importante, eu não posso[n]perdoe Shido por deformar seu[n]Mente tão maldita![n][w][e]

[msg MSG_016_0_0 [Makoto]]
[s][f 5 14]Devo concordar. O que Shido[n]Fiz é repreensível.[n][w][e]

[msg MSG_017_0_0 [Haru]]
[s][f 5 14]Nós devemos fazer isso. tenho certeza[n]Seremos capazes de fazer isso.[n][w][e]

[sel SEL_018_0_0 top]
[s][f 5 14]Vamos fazer isso.[e]
[s]Tenho certeza também.[e]
[s]Será como sempre.[e]

[msg MSG_019_0_0 [Futaba]]
[s][f 5 14][f 5 15]Você pode contar conosco. A decisão[n]sobre quando nos ligar para[n]Este plano está em você,[f 4 2].[n][w][e]

[msg MSG_020_0_0 [Ann]]
[s][f 5 14][f 5 15]Sim, definitivamente. Você está dentro[n]acusação de escolher o tempo[n]Para nós fazer isso,[f 4 2]![n][w][e]

[msg MSG_021_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Sim, é melhor não ficar também[n]trabalhou sobre isso. Quanto ao[n]Tempo, isso é sobre você,[f 4 2].[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Akechi nos salvou no final. Eu penso[n]em seu coração, ele pode não ter sido[n]tão ruim...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 2 0 0]......[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 3 0 0]Ei,[f 4 2]. Vamos ter sucesso nisso[n]Missão, não importa o quê.[n][f 1 3 65535][w][e]

