[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Ja e uma semana[n]ate dezembro.[n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]As coisas sao pessimas online.[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]As pessoas na cidade sao apenas[n]Falando sobre Shido tambem.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Sim, todo o zumbido sobre[n]Akechi se foi completamente.[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Shido pode ter pressionado para[n]silencio da midia sobre o assunto.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Por que as pessoas nao ficam bravas sobre[n]essa merda!? Nao faz sentido![n][w][e]

[sel SEL_006_0_0 top]
[s][f 5 14]As eleicoes sao mais importantes.[e]
[s]Eles so se preocupam com Shido.[e]
[s]Eles nao estao interessados.[e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Isso pode ser verdade, mas ainda assim...[n][w][e]

[msg MSG_008_0_0 [Futaba]]
[s][f 5 14]Nem e isso! Todo mundo justo[n]trava na historia mais recente![n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]E irritante pensar,[n]Mas voce provavelmente esta certo.[n][w][e]

[msg MSG_010_0_0 [Haru]]
[s][f 5 14]Eu pensei algo semelhante[n]Quando o pai entrou em colapso.[n][w][e]

[msg MSG_011_0_0 [Haru]]
[s][f 5 14]Contanto que nao envolva[n]voce, as noticias nao sao nada alem de[n]Outra forma de entretenimento.[n][w][e]

[msg MSG_012_0_0 [Haru]]
[s][f 5 14]Para o publico em geral, cada[n]A historia de passagem e simplesmente uma nova[n]meios de matar tempo.[n][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][f 5 14]Eles consomem cada topico, entao[n]Descarte-o antes de seguir em frente[n]para a proxima grande novidade...[n][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14]Mas aposto que tudo vai[n]Mudar quando eles veem Shido[n]tenha uma mudanca de coracao![n][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Espero que sim. Nos apenas teremos que[n]Espere com a crenca em nossos coracoes.[n][w][e]

