[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]O cartão de chamada está pronto![n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Isso foi rápido![n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Quero dizer, eu já escrevi três[n]De antes disso, lembra?[n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Mas eu inventei quase[n]Todas as frases...[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Você não tem que mencionar isso![n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]Suave, ryuji...[n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]A verdadeira questão aqui é quando[n]Devemos ir para o quarto de Futaba...[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]Bem, hum...[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]Eu acho que nosso líder deve decidir.[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]Olha quem é o suave agora...[n][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][f 5 14]Realmente deveria estar de acordo[n]Ele, porém, você não acha?[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]Absolutamente. Nós não temos escolha[n]mas para realizar isso.[n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14][f 5 15]É tudo em você,[f 4 2]![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]...Aí está. Parece um lindo[n]Tarefa importante foi pressionada por você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Não há sentido em pensar sobre isso agora[n]no entanto. Temos que fazer isso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 3 0 0]Depois de decidir, apenas[n]Dê o pedido como de costume no esconderijo.[n][f 1 3 65535][w][e]

