[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Entao eu vi Kamoshida no[n]Portao da escola esta manha.[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Ele so estava ali de pe[n]Olhando para mim com isso[n]sorriso de merda no rosto.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Ugh, isso e irritante...[n]Ele provavelmente estava zombando de voce.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Honestamente, vendo isso me pegou[n]Ainda mais emitido com isso.[n][w][e]

[msg MSG_003_0_1 [Ryuji]]
[s][f 5 14]Definitivamente vamos puxar[n]isso fora.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Sim. Estou preocupado com Shiho,[n]Mas eu quero me concentrar em[n]nossa operacao tambem.[n][w][e]

[msg MSG_005_0_0 [Ann]]
[s][f 5 14]E eu nao vou me deixar conseguir[n]exausto como a ultima vez.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]A reuniao do conselho[n]2 de maio, certo?[n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]Nos apenas temos cuidado[n]ele antes disso.[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]Estou pronto para isso.[e]
[s]Ja me decidi.[e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]O mesmo vale para mim.[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Eu tambem![n][w][e]

[msg MSG_011_0_0 [Ann]]
[s][f 5 14]Vou fazer o meu melhor.[n]Nao entrando sem mim, ok?[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Sim, e melhor voce nos informar se[n]Voce esta indo para o palacio.[n][w][e]

