[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Entao voce conhece aquela loja eu[n]mencionado, com as armas modelo?[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Esta em Shibuya. Eu posso ir com voce[n]Se voce quiser.[n][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Voce nao pode fazer isso sozinho?[e]
[s]Soa bem.[e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Oh certo, voce so[n]transferido aqui, hein?[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Vamos juntos, cara.[n]Eu vou te mostrar.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Doce.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Welp, vamos descobrir[n]Onde encontrar.[n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]Voce pelo menos sabe como conseguir[n]para a estacao Shibuya, sim?[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]Ei, eu nao posso fazer isso. Eu posso[n]confie em voces para verificar o[n]colocar para mim?[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]Voce nao pode vir?[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Amanha nao.[n][w][e]

[msg MSG_011_0_0 [Ann]]
[s][f 5 14]Eu fiz planos de ir ver[n]Shiho no hospital.[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]Ah, petcha.[n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]Nao se preocupe, conseguimos isso.[n][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Bem, Seeya em Shibuya,[f 4 2]![n]Eu estarei em frente a estacao![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Podemos ser capazes de colocar nossas maos[n]algumas coisas decentes se esta loja realmente tiver[n]Modelo de armas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Bem, podemos deixar isso para amanha.[n]Vamos para casa![n][f 1 3 65535][w][e]

