[msg TEST_MINE]
[s]Parece que consegui aumentar[n]minha[f 4 11 0][clr 26][f 4 12 0][clr 27]...[n][w][e]

[msg TEST_MINE2]
[s]Eu acho que posso enfrentar maior[n]Desafios agora![n][w][e]

[msg MSG_029_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Eu nao disse que estava suspeitando de voce.[n][f 1 3 65535][w][e]

[sel SEL_030_0_0 top]
[s]Bom de se ouvir.[e]
[s]Voce e o suspeito.[e]
[s]Ryuji e um ladrao fantasma.[e]

[msg MSG_NOT_SELECT_PARA_YUUK]
[s]......[n][w][e]
[s]Nao meu[f 4 11 3][clr 26][f 4 12 3][clr 27]precisa[n]ser pelo menos[clr 26][f 4 13 3 2][clr 27]para dizer aquilo...[n][w][e]

[msg MSG_NOT_SELECT_PARA_TISH]
[s]......[n][w][e]
[s]Nao meu[f 4 11 0][clr 26][f 4 12 0][clr 27]precisa[n]ser pelo menos[clr 26][f 4 13 0 2][clr 27]para dizer aquilo...[n][w][e]

[msg MSG_NOT_SELECT_PARA_BOTH]
[s]Eu nao posso dizer isso agora...[n][w][e]
[s]Meu[f 4 11 3][clr 26][f 4 12 3][clr 27]precisa ser pelo menos[n][clr 26][f 4 13 3 2][clr 27]e meu[f 4 11 0][clr 26][f 4 12 0][clr 27]precisa estar em[n]ao menos[clr 26][f 4 13 0 2][clr 27]para dizer aquilo...[n][w][e]

