[msg MSG_C15_PRECOOP_00_00 [Ohya]]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16001 65535 0]Hey, where's my glass...? Didn't I[n]order a refill?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]How much did I drink today?[n]What time is it? Ah, who cares.[n]...Wait, I care.[n][w][e]

[msg MSG_C15_PRECOOP_00_01 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]She's so drunk that she hasn't[n]even noticed you're here.[n][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]If we have her write articles,[n]it'll have an effect on the[n]Metaverse.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]We might be able to use her[n]if we do it right.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Should we try forming a deal[n]with Ohya?[n][w][e]

[sel SEL_C15_PRECOOP_00_02 top]
[s]Form a deal with her[e]
[s]Don't form a deal with her[e]

[msg MSG_C15_PRECOOP_00_03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]Keep in mind that she's drunk.[n]Now, do a good job negotiating,[n]okay?[n][w][e]

[msg MSG_C15_PRECOOP_00_04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1059 65535 0]You're not gonna do it? We could[n]really use her articles, though.[n][w][e]

[msg MSG_C15_PRECOOP_00_05 [Ohya]]
[s][bup 0 107 2 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16043 65535 0]Gimme 'nother... Mmmnn, put it[n]on my tab.[n][w][e]

[msg MSG_C15_BEGIN_RANK_10 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16003 65535 0]Yo! There you are![n][w][e]

[msg MSG_C15_BEGIN_QUEST_00 [Ohya]]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16028 65535 0]I'm exhausted from working five times[n]my usual work load...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]'S no way I could face any of this sober.[n][w][e]

[msg MSG_C15_BEGIN_QUEST_01 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16002 65535 0]Oh, there you are.[n][w][e]

[msg MSG_OOYA_SASOI_THROUGH_1 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16018 65535 0]What happened the other day?[n]Didn't you have any info for me?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I'm counting on you, as my own[n]private source.[n][w][e]

[msg MSG_OOYA_SASOI_THROUGH_2 [Ohya]]
[s][bup 0 107 2 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16101 65535 0]Is the Phantom Thieves boom over[n]already? If you're a serious fan, you[n]gotta show up! Just kidding.[n][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I mean, do what you want. You kids[n]nowadays really enjoy your freedom.[n][w][e]

[msg MSG_C15_BEGIN_WEATHER_00 [Ohya]]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16009 65535 0]I can't write when it's raining. I just can't[n]get into the mood...[n][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]So, inevitably, I wind up drinking here[n]instead.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Inevitably, okay? Inevitably![n][w][e]

[msg MSG_C15_BEGIN_WEATHER_01 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16011 65535 0]The press office goes crazy when it[n]snows in the city. Even when it's just[n]one or two centimeters.[n][w][e]

[msg MSG_C15_BEGIN_WEATHER_02 [Ohya]]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16012 65535 0]Sheesh, I hate how it's always raining[n]this time of year.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]When the weather's crappy, not even[n]my writing skills can improve the dull[n]photos.[n][w][e]

[msg MSG_C15_BEGIN_WEATHER_03 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16013 65535 0]I heard the Kanto region was directly hit[n]by the typhoon. It's all over the news.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]But I'm doing what I want here by[n]covering the bar.[n][w][e]

[msg MSG_C15_BEGIN_WEATHER_04 [Ohya]]
[s][bup 0 107 5 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16014 65535 0]Ah-choo![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hmmm... suppose someone's talking[n]about me behind my back, huh?[n][w][e]

[msg MSG_C15_BEGIN_WEATHER_05 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16015 65535 0]It's really coming down out there.[n]Did you get wet?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Why don't you sit and wait it out?[n]I'm sure you brought me some[n]good info, right?[n][w][e]

[msg MSG_C15_BEGIN_WEATHER_06 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16016 65535 0]It's another hot summer this year.[n]I bet we're gonna break some[n]record temperatures.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Although I'd be pretty happy to let[n]those records stay unbroken.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Still, this time of year is the best[n]for a nice, refreshing cold one.[n][w][e]

[msg MSG_C15_BEGIN_WEATHER_07 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16017 65535 0]I hear the flu's going around.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]You should wear a mask... Places like[n]a crowded train can be dangerous.[n][w][e]

[msg MSG_C15_BEGIN_WEATHER_08 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16017 65535 0]Holy crap, it's cold... I can't hold my[n]camera steady when I'm shivering[n]my ass off![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]The best thing for a day like today is[n]to coop up somewhere warm with[n]a nice, frosty beer.[n][w][e]
[s]You wanna go get a drink? It'd help[n]you feel all fuzzy and warm... Well,[n]not like you actually can.[n][w][e]

[msg MSG_C15_BEGIN_TIME_01 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 23 1 215 14 10 13 10]A runaway-train incident, huh? Is it[n]related to the psychotic breakdowns?[n][w][e]

[msg MSG_C15_BEGIN_TIME_02 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 23 1 215 14 10 13 10]Kamoshida, the perverted teacher.[n]Hm, that might make a good story.[n][w][e]

[msg MSG_C15_BEGIN_TIME_03 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16006 65535 0]The authorities are really working the[n]Kaneshiro case. It's best to stay away[n]from him.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]But I guess that doesn't have[n]anything to do with you...[n][w][e]

[msg MSG_C15_BEGIN_TIME_04 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16002 65535 0]Oh, there you are. I was wondering[n]where my informant had gone to.[n]Isn't it warm out?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Speaking of which, the public's[n]starting to warm up to the Phantom[n]Thieves. Your favorites![n][w][e]

[msg MSG_C15_BEGIN_TIME_05 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16002 65535 0]So you came, Phantom Thieves[n]believer. I wonder what's next,[n]now that the Medjed case is over.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]But how the heck would you[n]know, right? Riiiiiight?[n][w][e]

[msg MSG_C15_BEGIN_TIME_06 [Ohya]]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16021 65535 0]Okumura Foods... that was unexpected,[n]huh? And then your principal commits[n]suicide...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]The public blames the Phantom Thieves[n]for both incidents, but something doesn't[n]add up...[n][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Maybe you're rubbing off on me. But[n]I guess a journalist's gotta question[n]everything.[n][w][e]

[msg MSG_C15_BEGIN_TIME_07 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16021 65535 0]I wonder if the Phantom Thieves[n]leader really died. There hasn't[n]been any comment from the police.[n][w][e]
[s][bup 0 107 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I don't like that detective, the Akechi[n]guy... He's so cocky.[n][w][e]

[msg MSG_C15_BEGIN_TIME_08 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16002 65535 0]Oh, there you are. Wow, you look[n]really serious.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]You want a drink to loosen up?[n]...Just kidding.[n][w][e]

[msg MSG_C15_BEGIN_TIME_09 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16002 65535 0]Oh, there you are... but judging from[n]that look, you've got your own problems[n]on your mind.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Things aren't great for me either. I keep[n]looking for something newsworthy, but[n]everyone and everything's doing fine.[n][w][e]
[s]The heck's going on here?[n][w][e]

[msg MSG_C15_BEGIN_SECOMD_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16001 65535 0]You still need something from me?[n][w][e]

[msg MSG_C15_BEGIN_NOTCOOP_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16001 65535 0]I have to go back to work at the office, so[n]Lala-chan said she'll keep you company.[n][w][e]

[msg MSG_C15_COOP_00_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]Do you have a lot of info on the[n]Phantom Thieves?[n][w][e]

[msg MSG_C15_COOP_10_00 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]You want me to write something?[n]Sure, I'll see what I can do.[n][w][e]

[msg MSG_C15_COOP_10_01 [Ohya]]
[s][bup 0 107 6 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]Obviously you're here to see me, right?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]And info on the Phantom Thieves is on[n]the way?[n][w][e]

[msg MSG_C15_SPOT_01_00 [Ohya]]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16028 65535 0]*sigh* I can't gather any news because[n]of the chief. He doubts that I'm dating[n]a younger guy...[n][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, should we try going on an actual[n]date? Any beaches around here or[n]something?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]...Just kidding. You have some Phantom[n]Thieves info for me again today, right?[n][w][e]

[msg MSG_C15_SPOT_02_00 [Ohya]]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16028 65535 0]I've been stuck at work lately, so I[n]haven't had any decent food...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I wish I could go eat sushi, now that[n]I got my bonus...[n][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, did you bring me some Phantom[n]Thieves info?[n][w][e]

[msg MSG_C15_SPOT_03_00 [Ohya]]
[s][bup 0 107 6 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16084 65535 0]Hey... why don't we do something that[n]an actual couple might do?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Maybe go to Odaiba...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]A-Anyway, you brought me some info on the[n]Phantom Thieves, right?[n][w][e]

[msg MSG_C15_SPOT_04_00 [Ohya]]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16021 65535 0]I wish I could chug some sake and forget[n]everything. Maybe somewhere with...[n]teppanyaki...[n][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, well, I probably shouldn't be talking[n]like that to a kid.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Do you have some Phantom[n]Thieves info for me?[n][w][e]

[msg MSG_C15_SPOT_05_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]I haven't been home lately, so my[n]place is like a trash can... Have you[n]been keeping your room clean?[n][w][e]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 16099 65535 0]I can check for you if you want![n]...Just kidding.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]So, did you bring me some Phantom[n]Thieves info?[n][w][e]

[msg MSG_C15_COOP_01_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]Have you heard any good gossip?[n]My deadline's coming up, and[n]I'm all out of material.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sit down. I'll treat ya.[n][w][e]

[msg MSG_C15_COOP_02_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]Take a seat. Any new info?[n][w][e]

[msg MSG_C15_COOP_03_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]You brought me some news, right?[n][w][e]

[msg MSG_C15_COOP_04_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]The higher-ups are starting to get[n]tired of one-off articles.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]You have anything good to share?[n][w][e]

[msg MSG_C15_COOP_05_00 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]Hey... you have some info to share,[n]riiight?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Need s'more info on the Phantom[n]Thievesssss. So sit your pretty lil[n]butt down...[n][w][e]

[msg MSG_C15_COOP_06_00 [Ohya]]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]*sigh* ...God, my head is splitting.[n]Work's been tough... I need a break...[n][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]You have any good stories? I'm takin'[n]a little break, so I'm all ears.[n][w][e]

[msg MSG_C15_COOP_07_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]Can I talk to you about Kayo for a bit?[n][w][e]

[msg MND_C15_COOP_07_02]
[s]Ohya seems awfully tired...[n][w][e]
[s]I acquired the chief's name.[n]Let's go to Mementos[n]and change his heart...[n][w][e]

[msg MSG_C15_COOP_07_03 [Ohya]]
[s][bup 0 107 4 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]So you won't believe how weird the[n]chief's been acting![n][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sit down so I can give you the details![n][w][e]

[msg MSG_C15_COOP_08_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]I gotta talk to you about Kayo's case...[n]It's important.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Do you have a minute...?[n][w][e]

[msg MSG_C15_COOP_09_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]I have to tell you something.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Could you join me?[n][w][e]

[msg MSG_C15_COOP_09_01 [Ohya]]
[s][bup 0 107 6 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]There's a place I wanna go today.[n]You'll come with me, riiight?[n][w][e]

[msg MND_COOP_DOUZOKUSEI]
[s]I feel I can become closer with[n]Ohya thanks to the [var 2][n]Persona [clr 1][var 5][clr 27]...[n][w][e]

[msg MND_COOP_RANKUP_OK]
[s]I feel like my bond with Ohya[n]will grow stronger soon...[n][w][e]

[msg MND_COOP_RANKUP_NG]
[s]I don't think my bond with[n]Ohya will deepen just yet...[n][w][e]

[msg MND_COOP_RANK_MAX_00]
[s]I have a strong bond[n]with Ohya...[n][w][e]

[msg MND_COOP_RANK_MAX_01]
[s]I have a special bond[n]with Ohya...[n][w][e]

[msg MSG_COOP_CHECK_NIGHT [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]What are you gonna do? Are you[n]gonna hang out with Ohya?[n][w][e]

[msg MSG_COOP_CHECK_SHIDOU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nobody thinks you're alive at this point,[n]so it should be okay as long as you're[n]careful.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]What are you gonna do? Are you[n]gonna hang out with Ohya?[n][w][e]

[sel SEL_COOP_CHECK top]
[s]Hang out with her[e]
[s]Check bond with Ohya[e]
[s]Decline[e]

[msg MSG_C15_YES_01_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16002 65535 0]For real? From the look of it, you must[n]have good info, huh?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Give me the details about the Kamoshida[n]incident.[n][w][e]

[msg MSG_C15_YES_02_00 [Ohya]]
[s][bup 0 107 4 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16066 65535 0]Seriously, where do you get this stuff[n]from? True believers are scary...[n][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, you want a drink?[n][w][e]

[msg MSG_C15_YES_03_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16053 65535 0]Sorry, but let's go somewhere else.[n]You can give me the info later.[n][w][e]
[s][bup 0 107 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]We gotta get outta here quickly.[n]Someone problematic might've[n]found out about us...[n][w][e]

[msg MSG_C15_YES_04_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16053 65535 0]All right, let's hear it.[n][w][e]

[msg MSG_C15_YES_05_00 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16099 65535 0]I'm expecting a lot from you...[n]Okay, take a seat![n][w][e]

[msg MSG_C15_YES_06_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16053 65535 0]Lala-chan, two drinks please...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Here, take a seat.[n][w][e]

[msg MSG_C15_YES_07_01 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16061 65535 0]Okay... Sit down.[n][w][e]

[msg MSG_C15_YES_07_00 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16055 65535 0]Now, take a seat![n][w][e]

[msg MSG_C15_YES_08_00 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16031 65535 0]Thanks. Stop standing and sit down.[n][w][e]

[msg MSG_C15_YES_09_00 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]Well then, let's go to Skytree today.[n]I wanna see that view.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Okay, let's head out.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 16152 65535 0]Lala-chan, put it on my tab.[n][w][e]

[msg MSG_C15_YES_09_01 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]Take a seat.[n][w][e]

[msg MSG_C15_YES_09_02 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16067 65535 0]Sorry, I have to take this. Just a minute.[n][w][e]

[msg MSG_MORGANA_COOP_ESCAPE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Well, I'm gonna walk around. Let me[n]know when you're ready to leave.[n][w][e]

[msg MSG_C15_YES_00_00 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16060 65535 0]Oh, I look forward to it![n][w][e]

[msg MSG_C15_YES_10_00 [Ohya]]
[s][bup 0 107 6 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16088 65535 0]Sit next to me...[n][w][e]

[msg MSG_C15_YES_10_01 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16060 65535 0]Sit down. So, what type of article[n]do you want me to write?[n][w][e]

[msg MND_C15_SPOT_01_01]
[s]Maybe I should invite[n]her to Seaside Park...[n][w][e]

[sel SEL_C15_SPOT_01_02 top]
[s]Invite her[e]
[s]Don't invite her[e]

[msg MSG_C15_SPOT_01_03 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]Oh, not bad. It's a bit far, but we[n]can make it if we leave now.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 16052 65535 0]All right! Operation Secret Lovers,[n]commence![n][w][e]

[msg MND_C15_SPOT_02_01]
[s]Maybe I should invite her[n]out for expensive sushi...[n][w][e]

[sel SEL_C15_SPOT_02_02 top]
[s]Invite her[e]
[s]Don't invite her[e]

[msg MSG_C15_SPOT_02_03 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]I see... a sushi shop in Ginza, huh?[n][w][e]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 16069 65535 0]Sounds good. Let's go! I'll treat you,[n]of course.[n][w][e]

[msg MND_C15_SPOT_03_01]
[s]Maybe I should invite her to ride[n]the Odaiba Ferris wheel with me...[n][w][e]

[sel SEL_C15_SPOT_03_02 top]
[s]Invite her[e]
[s]Don't invite her[e]

[msg MSG_C15_SPOT_03_03 [Ohya]]
[s][bup 0 107 7 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]What!? A Ferris wheel!?[n][w][e]
[s][bup 0 107 6 65535 0][f 4 10 65535 0 0][vp 8 2 1 16099 65535 0]Wow, that's usually just for kids,[n]but... whatever! Let's go before[n]I change my mind![n][w][e]

[msg MND_C15_SPOT_04_01]
[s]Maybe I should invite her to[n]go get monjayaki with me...[n][w][e]

[sel SEL_C15_SPOT_04_02 top]
[s]Invite her[e]
[s]Don't invite her[e]

[msg MSG_C15_SPOT_04_03 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16059 65535 0]Ooh, good idea. I'm surprised you[n]know about that place... Pretty[n]well-informed, I see.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]You can't drink alcohol, so you're[n]in charge of making the monja.[n][w][e]

[msg MND_C15_SPOT_05_01]
[s]Should I invite her to my room?[n][w][e]

[sel SEL_C15_SPOT_05_02 top]
[s]Invite her[e]
[s]Don't invite her[e]

[msg MSG_C15_SPOT_05_03 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 0 65535 0]Whoa, is that okay!?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 16052 65535 0]Let's go, then! I'm super excited![n][w][e]

[msg MSG_C15_COOP_CANCEL_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 14 10 13 10][vp 8 2 1 16063 65535 0]Booo...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Lala-chaaan, give me a refill![n][w][e]

[msg MSG_SPOT_OPEN_KANDA]
[s]You can now go to [clr 1]Kanda[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_SHINJUKU]
[s]You can now go to [clr 2]Shinjuku[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_AKIHABARA]
[s]You can now go to [clr 2]Akihabara[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]

[msg MSG_SPOT_OPEN_INOKASHIRA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Inokashira Park[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]

[msg MSG_SPOT_OPEN_OGIKUBO]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Ogikubo Ramen[clr 27].[n][w][e]
[s]You can also invite people[n]who may enjoy eating ramen[n]to hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_ODAIBA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Odaiba Seaside Park[clr 27].[n][w][e]
[s]You can also invite people[n]who may like such parks to[n]hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_UENO]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Ueno Museum[clr 27].[n][w][e]
[s]You can also invite people[n]who may enjoy art museums[n]to hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_TSUKISHIMA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Tsukishima Monja[clr 27].[n][w][e]
[s]You can also invite people[n]who may enjoy eating monjayaki[n]to hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_HARAJUKU]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Harajuku Takenoko Street[clr 27].[n][w][e]
[s]You can also invite people[n]who may enjoy Takenoko Street[n]to hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_TYUKAGAI]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Motomachi Chinatown[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]

[msg MSG_SPOT_OPEN_MAIHAMA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Maihama Destinyland[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Asakusa[clr 27].[n][w][e]
[s]You can also invite people who may[n]enjoy the Skytree or Nakamise Street[n]to hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_IKEBUKURO]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Ikebukuro Planetarium[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]

[msg MSG_SPOT_OPEN_MEIJIJINGU]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Meiji Shrine[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]
[s]Furthermore, you can go by[n]yourself to pay homage to[n]the shrine if you wish.[n][w][e]

[msg MSG_SPOT_OPEN_SUIDOUBASH]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Suidobashi Dome Town[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]

[msg MSG_SPOT_OPEN_SHIBUYA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Shibuya Wilton Hotel[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]

[msg MSG_SPOT_OPEN_GINZA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Ginza Sushi Bar[clr 27].[n][w][e]
[s]You can also invite people who[n]may enjoy eating expensive sushi[n]to hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_JINBOCHO]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Jinbocho Book Town[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]
[s]Furthermore, you can go by[n]yourself for some shopping[n]if you so desire.[n][w][e]

[msg MSG_SPOT_OPEN_ICHIGAYA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Ichigaya Fishing Pond[clr 27].[n][w][e]
[s]You can also invite people[n]who may enjoy fishing to[n]hang out with you there.[n][w][e]
[s]Furthermore, you can go by[n]yourself and try your hand at[n]fishing if you so choose.[n][w][e]

[msg MSG_SPOT_OPEN_SHINAGAWA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Shinagawa Aquarium[clr 27].[n][w][e]
[s]You can also invite people[n]who may enjoy the aquarium[n]to hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_NAKANO]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Nakano Commerce Building District[clr 27].[n][w][e]
[s]You can also invite people[n]who may enjoy that location[n]to hang out with you there.[n][w][e]

[msg MSG_C15_BYEGREET_00_00 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 1 65535 0]I've been waiting for you![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]Isn't it kinda refreshing to see each[n]other like this in broad daylight?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]Okay, let's start off this celebratory[n]moment with something to drink![n][w][e]

[sel SEL_C15_BYEGREET_00_01 top]
[s]I don't want any alcohol...[e]
[s]Wait until I'm of age.[e]
[s]Well, maybe just one.[e]

[msg MSG_C15_BYEGREET_00_02 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 4 65535 0]Sorry! Mostly joking about the booze.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]But you'll join me once you're old[n]enough, riiight?[n][w][e]

[msg MSG_C15_BYEGREET_00_03 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 6 65535 0]Oho, I'll hold you to that, 'kay?[n][w][e]

[msg MSG_C15_BYEGREET_00_04 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 7 65535 0]That's the spirit! Oh, no, sorry—[n]I was just kidding.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]You can join in on the booze once[n]you're of age.[n][w][e]

[msg MSG_C15_BYEGREET_00_05 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 9 65535 0]...So, I'm thinking it's time for me to[n]write an article about Kayo's case.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 10 65535 0]Ever since all that stuff happened[n]with Shido, the stories haven't[n]stopped rolling in.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]...But it looks like I can finally avenge her.[n]And it's all thanks to your hard work.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]Here. It's a record of all the struggles[n]we shared.[n][w][e]

[msg MSG_C15_BYEGREET_00_06 [Ohya]]
[s][bup 0 107 6 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 13 65535 0]...Thank you so much. You better keep[n]it up when you're back home too.[n][w][e]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 660][vp 8 0 1 14 65535 0]...Whoa! Wait... What the hell?[n]No, I'm okay. I just have something[n]in my eye, is all![n][w][e]

[msg MSG_C15_BYEGREET_00_07 [Ohya]]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 660][f 4 23 1 215 14 10 13 10][vp 8 0 1 15 65535 0]...Whoa! Wait... What the hell?[n]No, I'm okay. I just have something[n]in my eye, is all![n][w][e]

[msg MSG_C15_BYEGREET_01_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 16 65535 0]Do you have ESP?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 17 65535 0]I'm surprised you knew where I was...[n]Are you here to say goodbye?[n][w][e]

[sel SEL_C15_BYEGREET_01_01 top]
[s]Yep.[e]
[s]I wanted to thank you.[e]
[s]Are you busy?[e]

[msg MSG_C15_BYEGREET_01_02 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 18 65535 0]Ahaha... Thanks. I wanted to speak with[n]you about something too...[n][w][e]

[msg MSG_C15_BYEGREET_01_03 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 19 65535 0]...That's my line.[n][w][e]

[msg MSG_C15_BYEGREET_01_04 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 20 65535 0]As you can see, it's my day off![n][w][e]

[msg MSG_C15_BYEGREET_01_05 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 21 65535 0]So... I'm close to being able to report on[n]Kayo's case.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 22 65535 0]Ever since all that stuff happened[n]with Shido, the stories haven't[n]stopped rolling in.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 23 65535 0]...But it looks like I can finally avenge her.[n]And it's all thanks to your hard work.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 24 65535 0]Here. It's a record of all the struggles[n]we shared.[n][w][e]

[msg MSG_C15_BYEGREET_01_06 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 25 65535 0]...Take care of yourself over there. I'll[n]call you, so you can keep me updated[n]on things.[n][w][e]
[s][f 4 10 65535 0 530][vp 8 0 1 26 65535 0]In a way, we're accomplices, you know?[n]So I won't let you ignore my calls, got it?[n][w][e]

[msg MSG_C15_BYEGREET_01_07 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 530][f 4 23 1 215 14 10 13 10][vp 8 0 1 27 65535 0]In a way, we're accomplices, you know?[n]So I won't let you ignore my calls, got it?[n][w][e]

[msg MSG_C15_BYEGREET_00_00_5 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 28 65535 0]I've been waiting for you![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 29 65535 0]Isn't it kinda refreshing to see each[n]other like this in broad daylight?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 30 65535 0]Okay, let's start off this celebratory[n]moment with something to drink![n][w][e]

[sel SEL_C15_BYEGREET_00_01_5 top]
[s]I don't want any alcohol...[e]
[s]Wait until I'm of age.[e]
[s]Well, maybe just one.[e]

[msg MSG_C15_BYEGREET_00_02_5 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 31 65535 0]Sorry! Mostly joking about the booze.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 32 65535 0]But you'll join me once you're old[n]enough, riiight?[n][w][e]

[msg MSG_C15_BYEGREET_00_03_5 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 33 65535 0]Fiiine... I'll be waiting![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 34 65535 0]One of these days, we gotta have an[n]all-night bender, okay?[n][w][e]

[msg MSG_C15_BYEGREET_00_04_5 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 35 65535 0]That's the spirit! Oh, sorry, I was just[n]kidding.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 36 65535 0]You can join in on the booze once[n]you're of age.[n][w][e]

[msg MSG_C15_BYEGREET_00_05_5 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 37 65535 0]...So, I'm thinking it's time for me to[n]write an article about Kayo's case.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 38 65535 0]Ever since all that stuff happened[n]with Shido, the stories haven't[n]stopped rolling in.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 39 65535 0]...But it looks like I can finally avenge her.[n]And it's all thanks to your hard work.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 40 65535 0]You know, you and I are partners now.[n]In a lot of ways.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 41 65535 0]Here. It's a record of all the struggles[n]we shared.[n][w][e]

[msg MSG_C15_BYEGREET_00_06_5 [Ohya]]
[s][bup 0 107 6 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 42 65535 0]*sigh* So this is it, huh? You go your[n]way, and I go mine? It's gonna get[n]so boring around here...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 43 65535 0]Though something tells me going[n]home isn't gonna keep you from[n]stirring up some trouble.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 44 65535 0]Call it a reporter's hunch, I guess.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 45 65535 0]I suppose you're just a permanent[n]person of interest. So no dropping[n]off the map, okay?[n][w][e]

[msg MSG_C15_BYEGREET_00_07_5 [Ohya]]
[s][bup 0 107 6 65535 0][f 4 10 65535 0 660][f 4 23 1 215 14 10 13 10][vp 8 0 1 46 65535 0]I suppose you're just a permanent[n]person of interest. So no dropping[n]off the map, okay?[n][w][e]

[msg MSG_C15_BYEGREET_01_00_5 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 47 65535 0]Do you have ESP?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 48 65535 0]I'm surprised you knew where I was...[n]Are you here to say goodbye?[n][w][e]

[sel SEL_C15_BYEGREET_01_01_5 top]
[s]Yep.[e]
[s]I wanted to thank you.[e]
[s]Are you busy?[e]

[msg MSG_C15_BYEGREET_01_02_5 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 49 65535 0]Ahaha... Thanks. I wanted to speak with[n]you about something too...[n][w][e]

[msg MSG_C15_BYEGREET_01_03_5 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 50 65535 0]...That's my line.[n][w][e]

[msg MSG_C15_BYEGREET_01_04_5 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 51 65535 0]As you can see, it's my day off![n][w][e]

[msg MSG_C15_BYEGREET_01_05_5 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 52 65535 0]So... I'm close to being able to report on[n]Kayo's case.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 53 65535 0]Ever since all that stuff happened[n]with Shido, the stories haven't[n]stopped rolling in.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 54 65535 0]...But it looks like I can finally avenge her.[n]And it's all thanks to your hard work.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 55 65535 0]Here. It's a record of the struggles[n]we shared.[n][w][e]

[msg MSG_C15_BYEGREET_01_06_5 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 23 1 215 3 10 0 10][vp 8 0 1 56 65535 0]By the way, I heard the Phantom[n]Thieves are disbanding? It's gonna be[n]so boring around here...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 57 65535 0]It's not every day you get to chase[n]after a bunch of young revolutionaries[n]like them.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 58 65535 0]Hold on, though... I bet you got more[n]tricks up your sleeve. You're going[n]home, not turning over a new leaf![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 59 65535 0]I'll be keeping an ear out for your next[n]adventure, okay? I promise, I'll tell[n]your story to the world![n][w][e]

[msg MSG_C15_BYEGREET_01_07_5 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 530][f 4 23 1 215 14 10 13 10][vp 8 0 1 60 65535 0]I'll be keeping an ear out for your next[n]adventure, okay? I promise, I'll tell[n]your story to the world![n][w][e]

