[msg COUNTER_ANNOUNCE_GREETIN]
[s]ダミー[n][w][e]

[msg D153_MOB_VOICE_TV_mes01 [Voice]]
[s][vp 8 1 65535 5000 0 0]Thank you for visiting.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes02 [Voice]]
[s][vp 8 1 65535 5001 0 0]Currently, we are holding an exhibition of[n]the works of the great artist Madarame.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes03 [Voice]]
[s][vp 8 1 65535 5002 0 0]Madarame can always be found on the[n]cutting edge of the Japanese art world.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes04 [Voice]]
[s][vp 8 1 65535 5003 0 0]This exhibit attempts to express and[n]share the appeal of Madarame's works.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes05 [Voice]]
[s][vp 8 1 65535 5004 0 0]His unique ideas, unrestrained by[n]preconceived notions...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes06 [Voice]]
[s][vp 8 1 65535 5005 0 0]...give rise to new possibilities in the[n]Nihonga art form.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes07 [Voice]]
[s][vp 8 1 65535 5006 0 0]Not only has he helped pioneer new[n]developments in the art world...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes08 [Voice]]
[s][vp 8 1 65535 5007 0 0]...but he has also dedicated himself to[n]training the next generation of artists.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes09 [Voice]]
[s][vp 8 1 65535 5008 0 0]He is an irreplaceable figure in the[n]modern world of Japanese art.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes10 [Voice]]
[s][vp 8 1 65535 5009 0 0]The eyes of the world are on Madarame.[n]How will his next move change the art[n]world?[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes [Announcement]]
[s][vp 8 1 65535 5100 0 0]This work, attentively painted with[n]delicate strokes...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_2 [Announcement]]
[s][vp 8 1 65535 5101 0 0]...is noted for its use of deep, intricate[n]colors.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_3 [Announcement]]
[s][vp 8 1 65535 5102 0 0]The features of the model are captured[n]masterfully.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_4 [Announcement]]
[s][vp 8 1 65535 5103 0 0]It's almost as if they were right there[n]in front of you.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_5 [Announcement]]
[s][vp 8 1 65535 5104 0 0]Not only does it exude an imposing[n]presence...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_6 [Announcement]]
[s][vp 8 1 65535 5105 0 0]...but it has a mysterious, unique allure...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_7 [Announcement]]
[s][vp 8 1 65535 5106 0 0]...that draws in and captivates all who[n]look at it.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_8 [Announcement]]
[s][vp 8 1 65535 5107 0 0]It has an everlasting appeal...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_9 [Announcement]]
[s][vp 8 1 65535 5108 0 0]...that makes you feel like you could[n]gaze upon it forever.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_10 [Announcement]]
[s][vp 8 1 65535 5109 0 0]It would not be an overstatement to[n]call this painting "perfect."[n][f 1 6 65534][e]

