[msg MSG_MORGANA_C0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]People in the city are all pretty terrible,[n]but it's hard finding someone with a[n]Palace...[n][w][e]

[msg MSG_REQ_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]So you want to make some infiltration[n]tools, right?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Just gather the [clr 2]materials[clr 27] in the Metaverse,[n]then I'll help you[n]make them![n][w][e]

[msg MSG_KAWAKAMI_00 [Kawakami]]
[s][bup 0 109 600 0 0][f 4 10 65535 0 0][vp 8 2 1 0 10 0]Don't talk to me while I'm working.[n]You don't want me to mess up, do you?[n][w][e]

[msg MSG_YUUSUKE_0611_001_00 [Yusuke]]
[s][f 4 23 1 65535 14 0 13 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4003 65535 0]Aren't you going to sleep yet?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I will be fine here. I sleep in my studio[n]on occasion, so this is luxurious in[n]comparison.[n][w][e]

[msg MSG_YUUSUKE_0611_002_00 [Yusuke]]
[s][f 4 23 1 65535 14 0 13 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4129 65535 0]I enjoy going to a bathhouse every[n]once in a while. The hot water is[n]quite relaxing.[n][w][e]

[msg MSG_FUTABA_1026_000_00 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9193 65535 0]It's my fault...[n][w][e]
[s][f 4 23 1 65535 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]All this happened because I kept the[n]calling card...[n][w][e]
[s][f 4 10 65535 0 0]......[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9178 65535 0]It's so late already...[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10_2 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9176 65535 0]Is Sojiro still awake?[n][w][e]
[s][f 4 10 65535 0 0]This is kind of awkward...[n][w][e]

[sel SEL_BED_MORGANA_NIGHT_10 top]
[s]Go home or he'll worry.[e]
[s]You can sleep on the sofa.[e]

[msg MSG_BED_MORGANA_NIGHT_10_3 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1029 65535 0]Wait, shouldn't you sleep on the sofa,[n]so that Futaba can go ahead and sleep[n]on the bed?[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10_4 [Futaba]]
[s][bup 0 8 3 65535 0]......[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10_5 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9195 65535 0][f 4 23 1 65535 4 10 0 0]...I'm gonna go home.[n][w][e]
[s][f 4 10 65535 0 0]Night.[n][w][e]

[msg MSG_FUTABA_1121_000_00 [Futaba]]
[s][f 4 23 1 65535 3 0 0 0][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 1 65535 0]Remember how I hijacked your phone[n]during the school trip? That kinda came[n]in handy![n][w][e]

[sel SEL_FUTABA_1121_001_00 top]
[s]How so?[e]
[s]I'm not interested.[e]

[msg MSG_FUTABA_1121_000_01 [Futaba]]
[s][f 4 23 1 65535 3 0 0 0][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]Oh, you wanna hear it again?[n][w][e]

[sel SEL_FUTABA_1121_001_01 top]
[s]Definitely.[e]
[s]Not now.[e]

[msg MSG_FUTABA_1121_002_00 [Futaba]]
[s][f 4 23 1 65535 4 0 0 0][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]Well, remember how I put that wiretap[n]app in Akechi's phone?[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]Basically that let me see GPS info for[n]two phones: yours and his.[n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 0 0 0][vp 8 0 1 5 65535 0]I'd be able to tell the precise moment[n]Sae Niijima, who had your phone,[n]ran into Akechi![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]That's when I saw my chance and beep—[n]sent the signal to activate the Metaverse[n]Navigator.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 7 65535 0]But there was the chance they'd just[n]pass each other without saying a[n]single word.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]That's why we needed you to tell Sae[n]Niijima to show the phone to Akechi![n][w][e]

[msg MSG_FUTABA_1121_003_00 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 1 9 65535 0]This plan still surprises me no matter[n]how many times I hear it...[n][w][e]

[msg MSG_FUTABA_1121_004_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 10 65535 0]Still, I couldn't just directly hack into[n]the Metaverse Nav. It's a mysterious[n]app, after all.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]But you know how it has that bookmark[n]function? All you have to do is push the[n]button.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]Making the phone think he was pushing[n]that button was totally doable.[n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Mwehehehe... Pretty good, huh!?[n][w][e]

[msg MSG_FUTABA_1121_002_01 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 14 65535 0]Whattt? That's no fun.[n][w][e]

[msg MSG_FUTABA_1121_003_01 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 1 15 65535 0][f 4 2] is tired. You can tell[n]him some other time, okay?[n][w][e]

[msg MSG_FUTABA_1121_100_00 [Futaba]]
[s][f 4 23 1 65535 4 0 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 16 65535 0]It may not have looked like it, but[n]everyone else was risking their lives too.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 17 65535 0]Though there's no doubt you were the[n]most at risk. I mean, you actually got[n]arrested.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 18 65535 0]...But it seems like all the drugs and stuff[n]made you forget the details of the plan.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 19 65535 0]Want me to explain how it all went[n]down? It might take a bit.[n][w][e]

[sel SEL_FUTABA_1121_101_00 top]
[s]Definitely.[e]
[s]Not now.[e]

[msg MSG_FUTABA_1121_102_00 [Futaba]]
[s][f 4 23 1 65535 3 0 0 0][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 20 65535 0]Well, since the rest of us didn't get[n]captured, we had to act.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 21 65535 0]We had to pretend we never wanted[n]you to get arrested... Pretend the[n]suicide news was a real shock...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 22 65535 0]Basically, we had to act like we didn't[n]know anything, 24/7.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 23 65535 0]The enemy knows who we are, so we[n]couldn't let our guard down even once[n]while you were gone.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 24 65535 0]If they had people watching us and[n]realized what our plan was, they[n]would have killed you immediately.[n][w][e]

[msg MSG_FUTABA_1121_103_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 25 65535 0]...Wanna hear more?[n][w][e]

[sel SEL_FUTABA_1121_104_00 top]
[s]I do.[e]
[s]That's enough for now.[e]

[msg MSG_FUTABA_1121_105_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 26 65535 0]Another tough part was figuring out[n]how to get Sae Niijima and Akechi[n]back from the Metaverse.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 27 65535 0]In order to return to reality, you have to[n]go back to the point where you came[n]into the Metaverse.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 28 65535 0]So, Sae and Akechi had to go through[n]where the Nav was activated, as in...[n]the hall where they met.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 29 65535 0]Akechi would just come back the same[n]way after the assassination. The real[n]issue was Sae Niijima.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 30 65535 0]We needed to stop her for a moment[n]before she headed back toward the[n]interrogation room.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 31 65535 0]But nothing can be sent to a phone[n]inside a Palace. So... I had to program[n]the messages in beforehand.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 32 65535 0]In doing so, I made it seem like the[n]messages were coming at that exact[n]moment in time.[n][w][e]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 33 65535 0]That part was kinda last minute, so I[n]had to pull an all-nighter trying to[n]get it set up...[n][w][e]

[msg MSG_FUTABA_1121_106_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 34 65535 0]...I'm really on a roll here! Wanna hear[n]some more?[n][w][e]

[sel SEL_FUTABA_1121_107_00 top]
[s]Yes, please.[e]
[s]That's enough, I think.[e]

[msg MSG_FUTABA_1121_108_00 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 35 65535 0]Lemme see, another problematic[n]thing was...[n][w][e]
[s][f 4 23 1 65535 3 0 0 0][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 0 1 36 65535 0]Oh yeah! Tying Akechi up! That was[n]really tough...[n][w][e]

[msg MSG_FUTABA_1121_109_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 37 65535 0]Uhhh, I obviously don't mean the[n]real Akechi. Even if we could do that,[n]it would ruin our plan.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 38 65535 0]The one we had to tie up was Sae[n]Niijima's cognitive Akechi.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 39 65535 0]...This part's really complicated. I know[n]you're tired. You sure you wanna hear[n]all of this now?[n][w][e]

[sel SEL_FUTABA_1121_110_00 top]
[s]Definitely.[e]
[s]Actually, maybe not.[e]

[msg MSG_FUTABA_1121_111_00 [Futaba]]
[s][f 4 23 1 65535 3 0 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 40 65535 0]Well, we needed to lure Akechi into[n]Sae Niijima's Palace and have him kill[n]the cognitive [f 4 2].[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 41 65535 0]But Akechi would have entered the[n]Palace immediately after meeting[n]Sae Niijima in the hallway, right?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 42 65535 0]Because of that, there was a pretty[n]decent chance he'd run into the[n]cognitive Akechi.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 43 65535 0]And if that happened, Akechi would've[n]totally realized we'd lured him into[n]the Palace.[n][w][e]

[msg MSG_FUTABA_1121_112_00 [Futaba]]
[s][f 4 23 1 65535 3 0 0 0][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 44 65535 0]Nobody actually even thought of this[n]possibility until the night before the[n]assassination...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 45 65535 0]Makoto realized in the middle of the[n]night, then it was a huge mess trying[n]to figure out what to do.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 46 65535 0]In the end, we chose to sneak into[n]the Metaverse while the plan was[n]happening to tie up the cognition.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 47 65535 0]Because you told Sae to show him[n]the phone, we expected her to chat[n]with him for at least a bit...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 48 65535 0]So, we had a few minutes to strike after[n]the cognitive Akechi showed up, but[n]before the Nav activated.[n][w][e]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 49 65535 0]It was Operation: Tie Him Up! Though[n]it wasn't really much of an operation[n]in the end...[n][w][e]

[msg MSG_FUTABA_1121_113_00 [Futaba]]
[s][f 4 23 1 65535 3 0 0 0][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 50 65535 0]Thankfully, Sae Niijima didn't know[n]his true nature, so the one that[n]appeared was an ordinary kid.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 51 65535 0]It was pretty simple surrounding him,[n]knocking him out, and tossing him on[n]another floor.[n][w][e]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 0 1 52 65535 0]But man, watching Makoto's skill was[n]super amazing... I guess she does use[n]knuckles as her weapon...[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 53 65535 0]Basically what I'm trying to say is,[n]appreciate what everyone else did.[n][w][e]

[msg MSG_FUTABA_1121_114_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 54 65535 0]...Phew. I just can't help but rant when[n]I'm talking about stuff that interests me.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 55 65535 0]Sorry 'bout that. Just focus on resting[n]up. You don't have to worry about[n]anything else.[n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 56 65535 0]And seriously... well done,[n][f 4 2].[n][w][e]

[msg MSG_FUTABA_1121_102_01 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 57 65535 0]I guess that's understandable.[n]You must be pretty exhausted.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 58 65535 0]Just focus on resting up. You don't[n]have to worry about anything else.[n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 59 65535 0]And seriously...[n]well done, [f 4 2].[n][w][e]

[msg MSG_MASTER_1121_000_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5111 65535 0]Oh, by the way...[n][w][e]
[s][f 4 10 65535 0 0]The police report on your death isn't[n]gonna show up at your school. No[n]need to worry.[n][w][e]
[s][f 4 10 65535 0 0]Seems Prosecutor Niijima worked out[n]some kinda deal with the higher-ups[n]or something.[n][w][e]
[s][f 4 10 65535 0 0]I mean, they haven't even said anything[n]to me even. As long as you stay quiet,[n]you'll be fine.[n][w][e]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 2 1 5135 65535 0]And I guess if they reported your death[n]now, they'd basically be saying you[n]were a phantom thief.[n][w][e]
[s][f 4 10 65535 0 0]They can't really go announcing what[n]the Phantom Thieves are, so I'm sure[n]they'll avoid that.[n][w][e]

[msg MSG_MORUGANA_1121_100_00 [Morgana]]
[s][f 4 23 1 65535 6 0 5 0][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]At any rate... I'm glad you're back safe[n]and sound.[n][w][e]
[s][f 4 10 65535 0 0]But even that's putting it too lightly.[n]You had it rough in there, didn't you?[n][w][e]

[sel SEL_MORUGANA_1121_101_00 top]
[s]Don't worry about it.[e]
[s]Only a little.[e]

[msg MSG_MORUGANA_1121_102_00 [Morgana]]
[s][f 4 23 1 65535 6 0 5 0][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1032 65535 0]Akechi was after you all along. I knew[n]it was risky, but we had no choice but[n]to depend on him.[n][w][e]
[s][f 4 10 65535 0 0]But thanks to your tenacity, you were[n]able to fool him.[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]It's payback time. Let's make him regret[n]underestimating the Phantom Thieves![n][w][e]

