[msg TEST_MES]
[s]Test[n][w][e]

[sel YESNO_SEL top]
[s]Yes[e]
[s]No[e]

[msg SAFETY_MES_RYUJI_01_01 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7024 65535 0]So she wants to do this "fair and square,"[n]huh? Works for me![n][w][e]

[msg SAFETY_MES_RYUJI_02_01 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]It'd be awesome if we could just get[n]a Shadow to drop a card for us... but[n]I guess things ain't gonna go that easy.[n][w][e]

[msg SAFETY_MES_RYUJI_03_01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]I think we're done with this floor.[n]Let's head upstairs.[n][w][e]

[msg SAFETY_MES_RYUJI_04_01 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 7025 65535 0]I guess I'm kinda interested in gamblin',[n]but my poker face is real pathetic...[n]I'd prolly just end up gettin' wiped out.[n][w][e]

[msg SAFETY_MES_RYUJI_05_01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7115 65535 0]It's gonna take friggin' forever to get[n]50,000 coins. Let's speed up the[n]process with a little sleight of hand![n][w][e]

[msg SAFETY_MES_RYUJI_06_01 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7103 65535 0]We got a little held up back there, but[n]let's get to the upper floor ASAP![n][w][e]

[msg SAFETY_MES_RYUJI_06_02 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7162 65535 0]Nooo waaay, you got this many coins[n]on your own!? I can't believe it![n][w][e]

[msg SAFETY_MES_RYUJI_06_03 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7039 65535 0]Joker... You got a little too caught up[n]in the shopping, didn't you? How're[n]we supposed to go up now?[n][w][e]

[msg SAFETY_MES_RYUJI_06_04 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7103 65535 0]Whew, you really had me goin' there[n]for a sec. Let's get back to the progress![n][w][e]

[msg SAFETY_MES_RYUJI_07_01 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][vp 8 2 1 7044 65535 0]A prosecutor does whatever it takes[n]to win, huh? Ain't no way that's right,[n]I don't care who says it.[n][w][e]

[msg SAFETY_MES_RYUJI_08_01 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7025 65535 0]Ugh, now we gotta get 100,000 coins?[n]We busted our asses gettin' HALF that![n][w][e]

[msg SAFETY_MES_RYUJI_09_01 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7028 65535 0]Owww... I think I banged my foot on[n]something in that pitch-black room.[n][w][e]

[msg SAFETY_MES_RYUJI_10_01 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7024 65535 0]Welp, looks like we got what we needed![n]Serves 'em right for cheatin' us so much.[n][w][e]

[msg SAFETY_MES_RYUJI_10_02 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][vp 8 2 1 7025 65535 0]Damn, we ain't done gettin' coins now![n]Let's go back for another round.[n][w][e]

[msg SAFETY_MES_RYUJI_11_01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7158 65535 0]Nice work in here! The rest is just[n]business as usual for us Phantom[n]Thieves![n][w][e]

[msg SAFETY_MES_MONA_01_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]She must be awfully confident if she's[n]fine with flat-out telling us where her[n]Treasure is...[n][w][e]

[msg SAFETY_MES_MONA_02_01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Since we're in a casino right now, that[n]means they have to be keeping some[n]pretty good stuff in the back room![n][w][e]

[msg SAFETY_MES_MONA_03_01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]That member's card was a cinch for you![n]I knew you were something special![n][w][e]

[msg SAFETY_MES_MONA_04_01 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]We're not getting anywhere until[n]we get our hands on one of those[n]cards... Let's work on that first.[n][w][e]

[msg SAFETY_MES_MONA_05_01 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Gambling's not really our thing...[n]Let's just get those coins so we can[n]get back to the phantom thievery.[n][w][e]

[msg SAFETY_MES_MONA_06_01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Y'know, when we struck it big on that[n]slot machine, I think I finally understood[n]what gambling's all about![n][w][e]

[msg SAFETY_MES_MONA_06_02 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1048 65535 0]Look at all those coins! Nice, Joker—[n]you really are special![n][w][e]

[msg SAFETY_MES_MONA_06_03 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1029 65535 0]Rein in the spending, Joker! We[n]would've had a member's card by now[n]if you could control yourself![n][w][e]

[msg SAFETY_MES_MONA_06_04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Geez, you gave me a heart attack back[n]there... Good thing you've got that[n]special something.[n][w][e]

[msg SAFETY_MES_MONA_07_01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]That was my first time in a courthouse.[n]I've gotta say, I have no idea how a stuffy[n]place like that could be seen as a casino.[n][w][e]

[msg SAFETY_MES_MONA_08_01 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]A scale-shaped bridge... That's going[n]to be a real hassle. Looks like the[n]tough times aren't through yet.[n][w][e]

[msg SAFETY_MES_MONA_09_01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1048 65535 0]Heh, some underhanded move like[n]hers isn't going to stop us![n][w][e]

[msg SAFETY_MES_MONA_10_01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Finally, we can cross the bridge.[n]Let's go, Joker![n][w][e]

[msg SAFETY_MES_MONA_10_02 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1029 65535 0]We were just one step away...[n]Why did you use the coins on[n]something else?[n][w][e]

[msg SAFETY_MES_MONA_11_01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1158 65535 0]Be careful, Joker—this is where things[n]get real serious.[n][w][e]

[msg SAFETY_MES_ANN_01_01 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6019 65535 0]Now that I think about it, this is actually[n]a courthouse in our world, right?[n][w][e]
[s][f 4 10 65535 0 0]The Phantom Thieves, sneaking into[n]a courthouse... Hoo boy, now I'm a little[n]nervous![n][w][e]

[msg SAFETY_MES_ANN_02_01 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6155 65535 0]Looks like we have to become members[n]first. Let's get our hands on a member's[n]card.[n][w][e]

[msg SAFETY_MES_ANN_03_01 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 6019 65535 0]We've got a card and a map now.[n]Things are looking up![n][w][e]

[msg SAFETY_MES_ANN_04_01 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6128 65535 0]So, she forced us to get a card so we'd[n]have no choice but to gamble...[n][w][e]

[msg SAFETY_MES_ANN_05_01 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 6155 65535 0]I think I'm getting hooked on all the[n]gambling! Let's keep working towards[n]50,000![n][w][e]

[msg SAFETY_MES_ANN_06_01 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 6022 65535 0]Ahhh, I'm so nervous! That fear of[n]losing it all... Gambling is too scary![n][w][e]

[msg SAFETY_MES_ANN_06_02 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 6162 65535 0]You went for it and got us all the coins[n]we need... What a dependable leader.[n][w][e]

[msg SAFETY_MES_ANN_06_03 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 6029 65535 0]We had just what we needed... How are[n]we supposed to get the card now?[n][w][e]
[s][f 4 10 65535 0 0]Well, knowing you, Joker, you'll probably[n]just make it all right back, but still...[n][w][e]

[msg SAFETY_MES_ANN_06_04 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 6155 65535 0]Joker, if you ever get married, um...[n]It may be a good idea to let your wife[n]take care of the money stuff for you.[n][w][e]

[msg SAFETY_MES_ANN_07_01 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6027 65535 0]That was my first time at a trial...[n][w][e]
[s][f 4 10 65535 0 0]If we get busted, we'll be on the way[n]scarier side of the courtroom... This[n]change of heart better go well.[n][w][e]

[msg SAFETY_MES_ANN_08_01 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 6028 65535 0]We can practically see the manager's[n]floor! If only we could clear the gap...[n][w][e]

[msg SAFETY_MES_ANN_09_01 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 6028 65535 0]Gah, my eyes are killing me. Please,[n]no more dark rooms...[n][w][e]

[msg SAFETY_MES_ANN_10_01 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 6117 65535 0]We can finally get to the manager's[n]floor now, right? Let's hurry and get[n]that Treasure.[n][w][e]

[msg SAFETY_MES_ANN_10_02 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 6029 65535 0]Jokerrrr! Now we don't have enough[n]coins![n][w][e]

[msg SAFETY_MES_ANN_11_01 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 6158 65535 0]Now all we have to do is send the[n]calling card. Let's do this right![n][w][e]

[msg SAFETY_MES_YUUSUKE_01_01 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4117 65535 0]A casino... If a Palace is the manifestation[n]of a person's desires, this seems to be[n]the most blatant reinterpretation yet.[n][w][e]

[msg SAFETY_MES_YUUSUKE_02_01 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4127 65535 0]The back area of a casino... What might[n]we find while sneaking about?[n][w][e]

[msg SAFETY_MES_YUUSUKE_03_01 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4088 65535 0]An air duct in the surveillance room...[n]What a classic approach to infiltration.[n][w][e]

[msg SAFETY_MES_YUUSUKE_04_01 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 4087 65535 0]So much gambling... If I win, I'll treat[n]myself to an extra-large beef bowl.[n][w][e]

[msg SAFETY_MES_YUUSUKE_05_01 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 4129 65535 0]To think she would attempt to cheat us.[n]I suppose this is what was meant by[n]winning at any cost...[n][w][e]

[msg SAFETY_MES_YUUSUKE_06_01 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 4158 65535 0]Excellent—we've hit our goal. I believe[n]we're done with this floor now.[n][w][e]

[msg SAFETY_MES_YUUSUKE_06_02 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 4158 65535 0]Excellent—we've hit our goal. I believe[n]we're done with this floor now.[n][w][e]

[msg SAFETY_MES_YUUSUKE_06_03 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 4040 65535 0]Ah— Joker! We had the requisite 50,000[n]coins. What are we supposed to do now?[n][w][e]

[msg SAFETY_MES_YUUSUKE_06_04 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4087 65535 0]It looks like you've recouped our losses.[n]It's about time to dispense with all the[n]unnecessary meandering.[n][w][e]

[msg SAFETY_MES_YUUSUKE_07_01 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4087 65535 0]The tension one feels in a courtroom...[n]I can see how it is very similar to all the[n]tension in a casino.[n][w][e]

[msg SAFETY_MES_YUUSUKE_08_01 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 4107 65535 0]Hmm, so we must be successful in[n]the games in order to proceed...[n][w][e]

[msg SAFETY_MES_YUUSUKE_09_01 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4129 65535 0]This business can hardly be called[n]gambling—it's rather tragic, actually.[n]You can tell she doesn't want us to win.[n][w][e]

[msg SAFETY_MES_YUUSUKE_10_01 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 4189 65535 0]No matter what underhanded trick[n]she may employ, it won't work on us.[n][w][e]

[msg SAFETY_MES_YUUSUKE_10_02 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 4158 65535 0]Joker, we no longer have enough coins.[n]I doubt you planned for this to happen,[n]but...[n][w][e]

[msg SAFETY_MES_YUUSUKE_11_01 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4158 65535 0]Well, we've finally reached the end.[n]We shall soon prevail![n][w][e]

[msg SAFETY_MES_MAKOTO_01_01 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 2048 65535 0]Well, at least Sis is seeing people as[n]actual humans here. That's somewhat[n]of a relief...[n][w][e]

[msg SAFETY_MES_MAKOTO_02_01 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2158 65535 0]If we want to reach the next level,[n]we'll need to gain access to the[n]elevator somehow.[n][w][e]

[msg SAFETY_MES_MAKOTO_03_01 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2047 65535 0]Just you wait, Sis... We're coming.[n][w][e]

[msg SAFETY_MES_MAKOTO_04_01 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2199 65535 0]So she's number one, huh? We really[n]need to open Sis's eyes.[n][w][e]

[msg SAFETY_MES_MAKOTO_05_01 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2197 65535 0]If we played fair here, we'd never get[n]all the coins we need.[n][w][e]

[msg SAFETY_MES_MAKOTO_06_01 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2028 65535 0]Sis rigged both the dice and the slots.[n]The amount of effort she's putting into[n]us failing is almost inhuman...[n][w][e]
[s][f 4 10 65535 0 0]We absolutely have to change her heart.[n]Let's head on up—Sis is waiting.[n][w][e]

[msg SAFETY_MES_MAKOTO_06_02 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 2162 65535 0]You collected 50,000 coins, all without[n]cheating!? Only you would be able to[n]pull something like that off, Joker.[n][w][e]

[msg SAFETY_MES_MAKOTO_06_03 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 2120 65535 0]We don't have enough coins anymore...[n]I'm sure you'll be able to fix this, though.[n][w][e]

[msg SAFETY_MES_MAKOTO_06_04 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 2156 65535 0]Okay, no more wasting time here—[n]we need to go after Sis.[n][w][e]

[msg SAFETY_MES_MAKOTO_07_01 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2028 65535 0]I wonder what I should tell Sis about[n]us being at the courthouse when I get[n]back...[n][w][e]

[msg SAFETY_MES_MAKOTO_08_01 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2108 65535 0]Fine then, we'll just keep on winning[n]until Sis feels like she has to face us![n][w][e]

[msg SAFETY_MES_MAKOTO_09_01 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2129 65535 0]She's not even trying to hide her[n]cheating anymore... At least it's[n]easier to spot now.[n][w][e]

[msg SAFETY_MES_MAKOTO_10_01 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2035 65535 0]Now we can get to the manager's floor...[n]No more looking down on us.[n][w][e]

[msg SAFETY_MES_MAKOTO_10_02 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2158 65535 0]Joker, we don't have enough to meet[n]the 100,000 coin requirement now.[n]What are we going to do?[n][w][e]

[msg SAFETY_MES_MAKOTO_11_01 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2158 65535 0]It's finally time to change Sis's heart![n]Let's get this done, Joker![n][w][e]

[msg SAFETY_MES_HARU_01_01 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 3082 65535 0]This place is so vibrant... but it's still[n]a Palace. There's no doubt that we[n]need to be careful.[n][w][e]
[s][f 4 10 65535 0 0]Anything could happen here...[n][w][e]

[msg SAFETY_MES_HARU_02_01 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 3133 65535 0]I'd hoped we could make a beeline[n]for the Treasure, but it doesn't look[n]like we'll be so lucky.[n][w][e]

[msg SAFETY_MES_HARU_03_01 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 3057 65535 0]Is there anything else we need to do on[n]this floor? If not, we should head up.[n][w][e]

[msg SAFETY_MES_HARU_04_01 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 3195 65535 0]Is being number one really so important?[n][w][e]

[msg SAFETY_MES_HARU_05_01 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 3178 65535 0]Is being number one really so important?[n][w][e]

[msg SAFETY_MES_HARU_06_01 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 3179 65535 0]I'm glad we're doing so well! ...I have a[n]feeling it's not over yet, though.[n][w][e]

[msg SAFETY_MES_HARU_06_02 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 3104 65535 0]You got all those without cheating!?[n]Do you have some sort of knack for[n]gambling, Joker?[n][w][e]

[msg SAFETY_MES_HARU_06_03 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 3019 65535 0]We've fallen below 50,000 coins...[n]I assume you have some sort of plan?[n][w][e]

[msg SAFETY_MES_HARU_06_04 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 3179 65535 0]We finally have the 50,000 coins we[n]need again—should we head on up?[n][w][e]

[msg SAFETY_MES_HARU_07_01 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 3023 65535 0]We have to make sure Queen's sister[n]has a change of heart![n][w][e]

[msg SAFETY_MES_HARU_08_01 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 3192 65535 0]Now we need twice as many coins as[n]before... Do you think it's possible,[n]Joker?[n][w][e]

[msg SAFETY_MES_HARU_09_01 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 3046 65535 0]Almost everything that attendant told us[n]was a lie! How rude.[n][w][e]

[msg SAFETY_MES_HARU_10_01 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 3181 65535 0]They might still try to pull something[n]on us... We should be careful.[n][w][e]

[msg SAFETY_MES_HARU_10_02 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 3178 65535 0]We've fallen below 100,000 coins...[n]Um, are we going to be okay?[n][w][e]

[msg SAFETY_MES_HARU_11_01 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 3158 65535 0]Let's make sure we're fully prepared...[n]for everyone's sakes.[n][w][e]

[msg SAFETY_MES_HUTABA_01_01 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 9089 65535 0]No worries on the navigation front[n]here—all systems are go![n][w][e]

[msg SAFETY_MES_HUTABA_02_01 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Leave the terminal work to me![n]I can't wait to get crackin'![n][w][e]

[msg SAFETY_MES_HUTABA_03_01 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9076 65535 0]I sure did a good job coming up with[n]a fake name for that card, didn't I?[n][w][e]

[msg SAFETY_MES_HUTABA_04_01 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 9133 65535 0]If only we could overwrite the card,[n]we'd be at the Treasure already. Hmph,[n]guess they're smarter than I thought...[n][w][e]

[msg SAFETY_MES_HUTABA_05_01 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 9089 65535 0]Just find me another terminal and[n]I'll take it from there. Two can play[n]the "cheating at games" game![n][w][e]

[msg SAFETY_MES_HUTABA_06_01 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9098 65535 0]I guess things turned out all right, but[n]I still wish I could've worked over that[n]giant slot machine more effectively...[n][w][e]

[msg SAFETY_MES_HUTABA_06_02 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9019 65535 0]C'mon, Joker, when do I get to show[n]off my stuff? I'm gettin' bored![n][w][e]

[msg SAFETY_MES_HUTABA_06_03 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9040 65535 0]Waaaugh! Joker, what have you done!?[n]We were at 50,000 coins![n][w][e]

[msg SAFETY_MES_HUTABA_06_04 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9158 65535 0]You've got luck all right, Joker—but[n]do me a favor... don't scare me like[n]that again.[n][w][e]

[msg SAFETY_MES_HUTABA_07_01 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9021 65535 0]Casino security is surprisingly easy[n]to crack. I want a real challenge![n][w][e]

[msg SAFETY_MES_HUTABA_08_01 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9160 65535 0]Whatever game she throws at us next,[n]you better believe she's cheating at it![n][w][e]

[msg SAFETY_MES_HUTABA_09_01 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 9043 65535 0]She really has no intention of letting us[n]win here... I suppose we figured that[n]out on the lower floors already, though.[n][w][e]

[msg SAFETY_MES_HUTABA_10_01 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 9048 65535 0]Sorry I couldn't do anything about the[n]cheating this time around—I'm glad[n]you're all right though![n][w][e]

[msg SAFETY_MES_HUTABA_10_02 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9192 65535 0]Jokerrrr! We're short on coins now![n]Y'know we can't cheat anymore,[n]right!?[n][w][e]

[msg SAFETY_MES_HUTABA_11_01 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 9158 65535 0]Don't worry, I've got my eye out for[n]you all! We've got this locked down![n][w][e]

[msg SAFETY_MES_AKECHI_01_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 8018 65535 0]Don't concern yourself with me—[n]just focus on infiltrating the Palace.[n][w][e]

[msg SAFETY_MES_AKECHI_02_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 8156 65535 0]If the public knew I was working[n]alongside the Phantom Thieves,[n]they'd be absolutely gobsmacked.[n][w][e]

[sel AKECHI_SEL_02_01 top]
[s]Will you stick with us?[e]
[s]They'd probably cry.[e]

[msg SAFETY_MES_AKECHI_02_02 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0]After this mission? I think not. This is[n]the only time I'm going to be a part[n]of the Phantom Thieves.[n][w][e]

[msg SAFETY_MES_AKECHI_02_03 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0]Yes, I suppose my fans could very well[n]do that.[n][w][e]

[msg SAFETY_MES_AKECHI_03_01 [Akechi]]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 8038 65535 0]Dear me... The Phantom Thieves[n]sure are tough on newcomers.[n][w][e]

[msg SAFETY_MES_AKECHI_04_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 8155 65535 0]Don't worry, I've deduced a way for us[n]to "win." I'll share the details later.[n][w][e]

[msg SAFETY_MES_AKECHI_05_01 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 8048 65535 0]I bet you could even get 50,000 coins[n]without resorting to cheating.[n][w][e]

[msg SAFETY_MES_AKECHI_06_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 8158 65535 0]Now that we have the requisite coins,[n]we have no further business here.[n]Let's go, Joker.[n][w][e]

[msg SAFETY_MES_AKECHI_06_02 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 8158 65535 0]Now that we have the requisite coins,[n]we have no further business here.[n]Let's go, Joker.[n][w][e]

[msg SAFETY_MES_AKECHI_06_03 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 54412 65535 0]Our collection's fallen below 50,000[n]coins. What do you plan to do about[n]that?[n][w][e]

[msg SAFETY_MES_AKECHI_06_04 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 54417 65535 0]I suspected you'd make it all back.[n]Now, let's make our way to Sae-san.[n][w][e]

[msg SAFETY_MES_AKECHI_07_01 [Akechi]]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 8038 65535 0]I wonder what Sae-san's cognitive[n]versions of us would look like.[n][w][e]

[msg SAFETY_MES_AKECHI_08_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 8155 65535 0]We managed 50,000 coins before—[n]I'm sure we're more than capable[n]of netting double the amount.[n][w][e]

[msg SAFETY_MES_AKECHI_09_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 8127 65535 0]So far, so good... I doubt Sae-san is[n]going to sit idly by at this rate, though.[n][w][e]

[msg SAFETY_MES_AKECHI_10_01 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 8158 65535 0]I knew you could pull off such a victory,[n]Joker.[n][w][e]

[msg SAFETY_MES_AKECHI_10_02 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 54412 65535 0]We no longer have the amount of coins[n]we need. I trust you have a contingency[n]plan for this?[n][w][e]

[msg SAFETY_MES_AKECHI_11_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 8023 65535 0]We must put an end to this. Let's go[n]change Sae-san's heart.[n][w][e]

[msg TEST_VELVET_GIRL_QUIET01 [Justine]]
[s]Sinner who is tied to the chains of fate...[n][w][e]
[s]You must not dawdle in the real world.[n]Return to your cell and find the strength[n]to resist.[n][w][e]

[msg TEST_VELVET_GIRL_QUIET02 [Justine]]
[s]Your must continue to resist in order[n]to change your fate...[n][w][e]

[msg TEST_VELVET_GIRL_LOUD01 [Caroline]]
[s]Heehee! Do you really have the time[n]to fool around?[n][w][e]
[s]Get back in the pokey and challenge[n]your fate![n][w][e]

[msg TEST_VELVET_GIRL_LOUD02 [Caroline]]
[s]Give it all you got! Your future depends[n]on it![n][w][e]

