[msg D150_03_ENEMY_GREE_A_mes [Agent]]
[s][vp 8 1 65535 3015 0 0]The intruder simply can't be found.[n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_A_mes_2 [Agent]]
[s][vp 8 1 65535 3007 0 0]Where'd they go!? Scum...[n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_A_mes_3 [Agent]]
[s][vp 8 1 65535 3003 0 0]Heh, thieves. I'll find[n]you no matter what.[n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_A_mes_4 [Agent]]
[s][vp 8 1 65535 3008 0 0]They should still be in the area![n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_A_mes_5 [Agent]]
[s][vp 8 1 65535 3001 0 0]Damn, where did you go!?[n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_B_mes [Agent]]
[s][vp 8 1 65535 3014 0 0]No problems on my end.[n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_B_mes_2 [Agent]]
[s][vp 8 1 65535 3000 0 0]You're quick![n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_B_mes_3 [Agent]]
[s][vp 8 1 65535 3010 0 0]Where are you...?[n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_B_mes_4 [Agent]]
[s][vp 8 1 65535 3009 0 0]Where did you hide?[n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_B_mes_5 [Agent]]
[s][vp 8 1 65535 3011 0 0]Where are they?[n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_C_mes [Agent]]
[s][vp 8 1 65535 3004 0 0]Just making life hard for me, aren't you?[n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_C_mes_2 [Agent]]
[s][vp 8 1 65535 3005 0 0]Dammit! Where did he go?[n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_C_mes_3 [Agent]]
[s][vp 8 1 65535 3017 0 0]Tch! Where is he hiding!?[n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_C_mes_4 [Agent]]
[s][vp 8 1 65535 3006 0 0]Where is he, dammit!?[n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_C_mes_5 [Agent]]
[s][vp 8 1 65535 3002 0 0]Damn, where is he...?[n][f 1 6 65534][e]

[msg D150_03_ENEMY_GREE_C_mes_6 [Agent]]
[s][vp 8 1 65535 3012 0 0]Where did he go!?[n][f 1 6 65534][e]

