[sel YESNO_SEL top]
[s]はい[e]
[s]いいえ[e]

[msg NPC_GREETING_MSG]
[s]Š拶[n][w][e]

[msg NPC_01]
[s]会話[n][w][e]

[msg MSG_GARAKEIJYOSI_001_0_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]You still use a flip phone!? Get a[n]smartphone already.[n][w][e]

[msg MSG_GARAKEIJYOSI_001_1_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Meh, this is enough for me. Smartphones[n]are complicated and seem really[n]expensive...[n][w][e]

[msg MSG_GARAKEIJYOSI_001_2_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]You'll be left behind in the world like that.[n]By the way, didn't Shujin get some horrible[n]transfer student?[n][w][e]

[msg MSG_GARAKEIJYOSI_001_3_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Yeah, I heard he's violent, with a criminal[n]record... I'm surprised you know so much[n]about my school.[n][w][e]

[msg MSG_GARAKEIJYOSI_002_0_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]I got a text about the Phantom Thieves.[n]Is this for real?[n][w][e]

[msg MSG_GARAKEIJYOSI_002_1_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]You mean the calling card? Apparently it[n]was posted on the school bulletin board...[n][w][e]

[msg MSG_GARAKEIJYOSI_002_2_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Did you take a picture? Even flip phones[n]can do that much, right?[n][w][e]

[msg MSG_GARAKEIJYOSI_002_3_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]It's old, so the camera's kinda wonky... but[n]I don't really care. As long as I can still text.[n][w][e]

[msg MSG_GARAKEIJYOSI_003_0_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]I heard that pervo teacher at your school[n]got arrested. I saw a pic of the calling card[n]online, too.[n][w][e]

[msg MSG_GARAKEIJYOSI_003_1_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Huh... I didn't know you could find out[n]about that kind of stuff on the internet.[n][w][e]

[msg MSG_GARAKEIJYOSI_003_2_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]What era are you from!?[n][w][e]
[s][vp 8 2 1 0 1 0]I bet Shujin students are posting about[n]it too. That Kamoshida story is really[n]trending right now.[n][w][e]

[msg MSG_GARAKEIJYOSI_004_0_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Have you heard of Ichiryusai Madarame?[n]I've been curious since I saw him on TV.[n][w][e]

[msg MSG_GARAKEIJYOSI_004_1_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Of course. An apprentice of his goes to[n]my school.[n][w][e]

[msg MSG_GARAKEIJYOSI_004_2_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Whaaat, really!? Wow! What kind of[n]person are they?[n][w][e]

[msg MSG_GARAKEIJYOSI_004_3_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Who knows? He's an art student. I heard[n]he's pretty eccentric.[n][w][e]

[msg MSG_GARAKEIJYOSI_005_0_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Did you know a calling card was posted[n]at the exhibit the same day we went?[n][w][e]

[msg MSG_GARAKEIJYOSI_005_1_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]What!? Really!?[n][w][e]

[msg MSG_GARAKEIJYOSI_005_2_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]People are talking about it all over the[n]internet. Seems Madarame's been[n]stealing other people's work.[n][w][e]

[msg MSG_GARAKEIJYOSI_005_3_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]You found out all that? The internet is[n]amazing...[n][w][e]

[msg MSG_GARAKEIJYOSI_006_0_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]So that art theft thing was true! Where[n]do you go to find info on that stuff?[n][w][e]

[msg MSG_GARAKEIJYOSI_006_1_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]A message board called the "Phan-Site."[n]Its viewership is insane right now.[n][w][e]

[msg MSG_GARAKEIJYOSI_006_2_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Is that site safe to look at? I won't get a[n]bunch of ads trying to scam me?[n][w][e]

[msg MSG_GARAKEIJYOSI_006_3_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]You're worrying too much! Just ignore[n]that stuff.[n][w][e]

[msg MSG_GARAKEIJYOSI_007_0_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Hey, do you believe in the Phantom[n]Thieves?[n][w][e]

[msg MSG_GARAKEIJYOSI_007_1_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Hmm, I think so. Akechi-san was talking[n]about them on TV, after all.[n][w][e]

[msg MSG_GARAKEIJYOSI_007_2_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]It's like what happened with Kamoshida.[n]I think the calling card is the key.[n][w][e]
[s][vp 8 2 1 0 1 0]Do you have any idea who put it there?[n][w][e]

[msg MSG_GARAKEIJYOSI_007_3_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Oh yeah, the culprits are still a real[n]mystery... I wonder if they really are[n]from my school.[n][w][e]

[msg MSG_GARAKEIJYOSI_008_0_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Hey, big news. Apparently a calling card[n]was sent to Junya Kaneshiro.[n][w][e]

[msg MSG_GARAKEIJYOSI_008_1_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]What!? Are the Phantom Thieves at it[n]again?[n][w][e]
[s][vp 8 2 1 0 0 0]...By the way, who's Kaneshiro?[n][w][e]

[msg MSG_GARAKEIJYOSI_008_2_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]He's the mafia boss running Shibuya.[n]It's all over the internet![n][w][e]

[msg MSG_GARAKEIJYOSI_009_0_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Did the Phantom Thieves really do it?[n]The police are denying it, aren't they?[n][w][e]

[msg MSG_GARAKEIJYOSI_009_1_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Don't trust the cops. The real calling[n]card was posted online![n][w][e]

[msg MSG_GARAKEIJYOSI_009_2_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]I guess it doesn't really matter who did[n]it, as long as they're getting rid of the[n]bad guys.[n][w][e]

[msg MSG_GARAKEIJYOSI_009_3_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]You're so nonchalant, as usual...[n][w][e]

[msg MSG_GARAKEIJYOSI_010_0_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]A fight between the Phantom Thieves[n]and Medjed, huh... This is worth[n]paying attention to.[n][w][e]

[msg MSG_GARAKEIJYOSI_010_1_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Huh? The Phantom Thieves are gonna[n]fight hackers?[n][w][e]

[msg MSG_GARAKEIJYOSI_010_2_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Of course! Medjed is a bunch of[n]scumbags. No way the Phantom[n]Thieves would ignore that.[n][w][e]
[s][vp 8 2 1 0 1 0]And technically, they're "cracking."[n]People online will get on your case[n]if you say they're hackers.[n][w][e]

[msg MSG_GARAKEIJYOSI_011_0_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]This school trip's gonna be a drag. Why[n]can't we just look at maps online if we[n]wanna sightsee?[n][w][e]

[msg MSG_GARAKEIJYOSI_011_1_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]I'm excited. It'll be my first time overseas.[n][w][e]
[s][vp 8 2 1 0 0 0]I heard Big Bang Burger has an exclusive[n]menu in Hawaii![n][w][e]

[msg MSG_GARAKEIJYOSI_011_2_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Don't fall for marketing hype so easily.[n]It makes you seem information illiterate.[n][w][e]

[msg MSG_GARAKEIJYOSI_012_0_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]The principal at your school died,[n]right? What was that like?[n][w][e]

[msg MSG_GARAKEIJYOSI_012_1_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Umm... It's shocking, but I'm not[n]devastated or anything.[n][w][e]
[s][vp 8 2 1 0 0 0]I'd never even spoken to him, so...[n]it's like the death of a celebrity.[n][w][e]

[msg MSG_GARAKEIJYOSI_012_2_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]I see... Your school's really been[n]through a lot this year.[n][w][e]

[msg MSG_GARAKEIJYOSI_013_0_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]I didn't know the calling card was for[n]Okumura-senpai's dad... She must be[n]having a hard time.[n][w][e]

[msg MSG_GARAKEIJYOSI_013_1_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]You just now found that out? It's all[n]over the internet. He's getting bashed[n]left and right.[n][w][e]
[s][vp 8 2 1 0 1 0]Corrupt companies are the worst! The[n]Phantom Thieves will do something[n]about it![n][w][e]

[msg MSG_GARAKEIJYOSI_014_0_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Aren't the Phantom Thieves supposed[n]to be superheroes? That was too cruel...[n][w][e]

[msg MSG_GARAKEIJYOSI_014_1_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]You think so? There were people who[n]committed suicide because of that guy.[n][w][e]
[s][vp 8 2 1 0 1 0]Don't they deserve your pity? Talk about[n]double standards.[n][w][e]

[msg MSG_GARAKEIJYOSI_014_2_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]...Even so, there has to have been a better[n]way...[n][w][e]

[msg MSG_GARAKEIJYOSI_015_0_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]We're in the middle of exams, but[n]they're still making such a big deal[n]about the Phantom Thieves...[n][w][e]

[msg MSG_GARAKEIJYOSI_015_1_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Police at Shujin, huh...[n][w][e]
[s][vp 8 2 1 0 1 0]They must have their eyes on your[n]school since that's where the first[n]calling card appeared.[n][w][e]
[s][vp 8 2 1 0 1 0]But that's old news if you keep up[n]with the internet... and the Phantom[n]Thieves did murder someone.[n][w][e]

[msg MSG_GARAKEIJYOSI_016_0_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]The internet's on fire searching for[n]the Phantom Thieves. I haven't slept[n]because of it.[n][w][e]
[s][vp 8 2 1 0 1 0]There's a ton of theories that they're[n]connected to Shujin somehow. Do[n]you know anything?[n][w][e]

[msg MSG_GARAKEIJYOSI_016_1_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]I don't... I don't want to believe they're[n]at my school...[n][w][e]

[msg MSG_GARAKEIJYOSI_016_2_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Hey, try to look into it while you can.[n]It'll be too late if you have a psychotic[n]breakdown...[n][w][e]

[msg MSG_GARAKEIJYOSI_017_0_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Are the Phantom Thieves going to[n]be arrested? Is there any information[n]online?[n][w][e]

[msg MSG_GARAKEIJYOSI_017_1_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Just a lot of fake stuff. Any mention[n]of the Phantom Thieves always brings[n]in the trolls.[n][w][e]

[msg MSG_GARAKEIJYOSI_017_2_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]They used to be so popular...[n][w][e]

[msg MSG_GARAKEIJYOSI_017_3_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]That's old news. Of course people[n]were upset after finding out they[n]were murderers.[n][w][e]

[msg MSG_GARAKEIJYOSI_018_0_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Akechi's a real genius, huh? I can't believe[n]he's just a high schooler like me.[n][w][e]

[msg MSG_GARAKEIJYOSI_018_1_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]The most shocking thing to me is that[n]the Phantom Thieves are minors...[n][w][e]
[s][vp 8 2 1 0 0 0]They're around our age, right? High[n]school...?[n][w][e]

[msg MSG_GARAKEIJYOSI_018_2_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Usually this stuff gets posted on the[n]internet. I can't seem to find anything,[n]though...[n][w][e]

[msg MSG_GARAKEIJYOSI_019_0_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]My TV went haywire all of a sudden...[n]I was so surprised...[n][w][e]
[s][vp 8 2 1 0 0 0]So that Shido person was the bad guy?[n]The Phantom Thieves were right all along?[n][w][e]

[msg MSG_GARAKEIJYOSI_019_1_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Well, it may not be that simple.[n][w][e]
[s][vp 8 2 1 0 1 0]On the internet, people are speculating[n]it's a hoax by Shido's political rivals.[n][w][e]

[msg MSG_GARAKEIJYOSI_020_0_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]The Phantom Thieves never existed...?[n]Were we just dreaming this whole time?[n][w][e]

[msg MSG_GARAKEIJYOSI_020_1_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]From what I saw on the internet... it looks[n]that way. There's no actual proof.[n][w][e]
[s][vp 8 2 1 0 1 0]Anyone who really believed in that was[n]an idiot. How could a heart be stolen,[n]anyway?[n][w][e]

[msg MSG_GARAKEIJYOSI_020_2_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]I might be an idiot... but it would be nice[n]if they were real...[n][w][e]

[msg MSG_GARAKEIJYOSI_020_3_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Ah, uh... yeah, I guess.[n][w][e]

[msg MSG_GARAKEIJYOSI_021_0_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Haven't things felt kinda weird ever[n]since the new year started? Everyone[n]seems so giddy...[n][w][e]
[s][vp 8 2 1 0 1 0]How're you though? Anything good[n]happen lately?[n][w][e]

[msg MSG_GARAKEIJYOSI_021_1_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Mmm, I'm not sure. I don't really[n]have a specific wish anyways...[n][w][e]

[msg MSG_GARAKEIJYOSI_021_2_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]I guess it's no surprise coming from[n]someone who's still happy using a[n]flip phone.[n][w][e]

[msg MSG_GARAKEIJYOSI_022_0_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]I wonder if the Phantom Thieves were all[n]a dream.[n][w][e]

[msg MSG_GARAKEIJYOSI_022_1_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]You're still talking about them? They're[n]yesterday's news.[n][w][e]

[msg MSG_GARAKEIJYOSI_022_2_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]I still think about them... I feel like they're[n]still around, somewhere not far from us...[n][w][e]

[msg MSG_GARAKEIJYOSI_022_3_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]More importantly, why don't you just get[n]a smartphone already? You're lagging[n]behind because of your flip phone.[n][w][e]

[msg MSG_GARAKEIJYOSI_023_0_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]I can't believe we'll be done with[n]high school in just one more year...[n][w][e]
[s][vp 8 2 1 0 1 0]We talked here a lot last year...[n]So much happened.[n][w][e]

[msg MSG_GARAKEIJYOSI_023_1_0 [Easygoing Shujin Girl]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Remember the Phantom Thieves?[n]I'm going to try to steal a heart this[n]year, too.[n][w][e]

[msg MSG_GARAKEIJYOSI_023_2_0 [Stylish Male Student]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]...What!?[n][w][e]
[s][vp 8 2 1 0 1 0]D-Do you mean... mine...?[n][w][e]

[msg MSG_BIKOU01_001_0_0 [Makoto]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2018 65535 0]Try to refrain from stopping on your way[n]home. I hear security in here is quite poor.[n][w][e]

[msg MSG_BIKOU01_002_0_0 [Female Shujin Student]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Huh? Are you... Niijima-san? The student[n]council president?[n][w][e]
[s][vp 8 2 1 0 22 0]Can't I at least go shopping? I mean, you're[n]here too. It can't be that dangerous, right?[n][w][e]

[msg MSG_BIKOU01_003_0_0 [Makoto]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I-I have business here. I had no other[n]choice...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2028 65535 0]*sigh* I can't believe I followed him all[n]the way outside of school. Why am I[n]doing this...?[n][w][e]

[msg MSG_BIKOU01_004_0_0 [Makoto]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 2029 65535 0]A-Anyway... be careful. I'll be heading[n]home now as well.[n][w][e]

[msg MSG_BIKOU01_005_0_0 [Female Shujin Student]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Yeah, yeah, I'll go home. After all, I don't[n]want you tattling on me, Miss President.[n][w][e]

[msg MSG_BIKOU02_001_0_0 [Makoto]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 2129 65535 0]M-My, what a coincidence.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Were you perhaps... going back to the[n]scene of the crime...?[n][w][e]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 2087 65535 0]U-Ummm, this book is so good. I just[n]can't stop reading it. I hope the next[n]volume comes out soon...[n][w][e]

[msg MSG_BIKOU02_002_0_0 [Makoto]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2028 65535 0]There are certainly a lot of people in[n]Shibuya... I need to make sure I don't[n]lose sight of—[n][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh... Don't mind me. I was simply talking[n]to myself.[n][w][e]

[msg MSG_0103_0108_SHIHO_000_ [Shiho]]
[s][bup 0 212 600 0 0][f 4 10 65535 0 0][vp 8 2 1 37309 65535 0]Hmm, what else do I need...?[n][w][e]

[sel SEL_0103_0108_SHIHO_001_ top]
[s]Problem?[e]
[s]Looking for something?[e]
[s]Hello again.[e]

[msg MSG_0103_0108_SHIHO_002_ [Shiho]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 212 601 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, hi, [f 4 1]-kun! Fancy[n]running into you here.[n][w][e]

[msg MSG_0103_0108_SHIHO_002__2 [Shiho]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 212 600 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, [f 4 1]-kun! Good to see[n]you again.[n][w][e]
[s][bup 0 212 601 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I'm surprised to run into you here,[n]though.[n][w][e]

[msg MSG_0103_0108_SHIHO_003_ [Shiho]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 212 600 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I'm just picking up some things I'll[n]need for volleyball club.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I'm going back to Shujin next year,[n]so I figure I should get everything[n]ready now.[n][w][e]

[sel SEL_0103_0108_SHIHO_004_ top]
[s]Sounds like a lot of work.[e]
[s]Sounds like fun.[e]

[msg MSG_0103_0108_SHIHO_005_ [Shiho]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 212 601 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ahaha, not at all.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I mean, I'm just happy that I get to[n]spend time with Ann again.[n][w][e]

[msg MSG_0103_0108_SHIHO_006_ [Shiho]]
[s][bup 0 212 600 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I feel like I can barely wait for April[n]to come.[n][w][e]
[s][f 4 23 1 65535 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, and I look forward to seeing you[n]more too, [f 4 1]-kun—I hope[n]we can be good friends.[n][w][e]

[msg MSG_0103_0108_SHIHO_005__2 [Shiho]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 212 601 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ahaha, can you tell?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 37309 65535 0]I mean, I'm just happy that I get to[n]spend time with Ann again.[n][w][e]

[msg MSG_0103_0108_SHIHO_END_ [Shiho]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 212 601 0 0][f 4 10 65535 0 0][vp 8 2 1 37309 65535 0]Going to the same school as Ann is[n]like a dream of mine.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, and I look forward to seeing you[n]more too, [f 4 1]-kun—I hope[n]we can be good friends.[n][w][e]

[msg MSG_GRT_main_All_001_01_ [Shiho]]
[s][vp 9 2 65535 37609 0 0]Every day is so boring... Isn't[n]there anything fun to do?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_02_ [Shiho]]
[s][vp 9 2 65535 41805 0 0]I wish I could make some[n]easy money. Are there any[n]good opportunities out there?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_09_ [Shiho]]
[s][vp 9 2 65535 40905 0 0]The sun's still out and I'm[n]already out of things to do...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_10_ [Shiho]]
[s][vp 9 2 65535 40951 0 0]Is there anything fun[n]going on? I'm so bored![n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_03_ [Shiho]]
[s][vp 9 2 65535 40355 0 0]I can just half-ass it.[n]Things'll work out,[n]one way or another...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_04_ [Shiho]]
[s][vp 9 2 65535 42459 0 0]I really don't feel like[n]going to work today. Maybe[n]I'll just skip going today...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_11_ [Shiho]]
[s][vp 9 2 65535 41052 0 0]I'm just doing the same[n]things every single day...[n]It's exhausting...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_12_ [Shiho]]
[s][vp 9 2 65535 41152 0 0]I'm so sick of working... I don't[n]even get holidays off...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_05_ [Shiho]]
[s][vp 9 2 65535 43155 0 0]Every day is so boring... Isn't[n]there anything fun to do?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_06_ [Shiho]]
[s][vp 9 2 65535 43360 0 0]I wish I could make some[n]easy money. Are there any[n]good opportunities out there?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_13_ [Shiho]]
[s][vp 9 2 65535 40905 0 0]The sun's still out and I'm[n]already out of things to do...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_14_ [Shiho]]
[s][vp 9 2 65535 40951 0 0]Is there anything fun[n]going on? I'm so bored![n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_07_ [Shiho]]
[s][vp 9 2 65535 38752 0 0]Nothing good ever[n]happens... Someone should[n]do something about that.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_08_ [Shiho]]
[s][vp 9 2 65535 44755 0 0]Nothing's ever going to[n]change... So I refuse to[n]take things seriously.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_15_ [Shiho]]
[s][vp 9 2 65535 41052 0 0]I'm just doing the same[n]things every single day...[n]It's exhausting...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_16_ [Shiho]]
[s][vp 9 2 65535 41152 0 0]I'm so sick of working... I don't[n]even get holidays off...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_01_ [Shiho]]
[s][vp 9 2 65535 38704 0 0]They say they went crazy,[n]and they don't remember[n]a thing afterward...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_02_ [Shiho]]
[s][vp 9 2 65535 45752 0 0]They say some of them[n]just go brain dead...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_09_ [Shiho]]
[s][vp 9 2 65535 38159 0 0]Politicians are useless.[n]Why aren't they doing[n]anything about this...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_10_ [Shiho]]
[s][vp 9 2 65535 46202 0 0]So many strange things[n]have been happening lately.[n]I feel so uneasy...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_03_ [Shiho]]
[s][vp 9 2 65535 37859 0 0]I didn't get that raise...[n]Working hard just doesn't[n]seem like it's worth it...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_04_ [Shiho]]
[s][vp 9 2 65535 37760 0 0]I wish there were an easier[n]way to make money. Know[n]any way I could get rich quick?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_11_ [Shiho]]
[s][vp 9 2 65535 41051 0 0]What the heck are these[n]politicians even doing!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_12_ [Shiho]]
[s][vp 9 2 65535 39360 0 0]This world is terrible...[n]Who's to blame for that?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_05_ [Shiho]]
[s][vp 9 2 65535 38159 0 0]Politicians are useless.[n]Why aren't they doing[n]anything about this...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_06_ [Shiho]]
[s][vp 9 2 65535 46202 0 0]So many strange things[n]have been happening lately.[n]I feel so uneasy...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_13_ [Shiho]]
[s][vp 9 2 65535 38704 0 0]They say they went crazy,[n]and they don't remember[n]a thing afterward...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_14_ [Shiho]]
[s][vp 9 2 65535 45752 0 0]They say some of them[n]just go brain dead...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_07_ [Shiho]]
[s][vp 9 2 65535 39102 0 0]I didn't get that raise...[n]Working hard just doesn't[n]seem like it's worth it...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_08_ [Shiho]]
[s][vp 9 2 65535 39360 0 0]This world is terrible...[n]Who's to blame for that?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_15_ [Shiho]]
[s][vp 9 2 65535 41051 0 0]What the heck are these[n]politicians even doing!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_16_ [Shiho]]
[s][vp 9 2 65535 37760 0 0]I wish there were an easier[n]way to make money. Know[n]any way I could get rich quick?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_01_ [Shiho]]
[s][vp 9 2 65535 42705 0 0]He admitted it...? Geez, if he[n]was gonna confess anyway,[n]he never should've done it...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_02_ [Shiho]]
[s][vp 9 2 65535 46355 0 0]Why'd he confess all of[n]a sudden? I don't get it...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_09_ [Shiho]]
[s][vp 9 2 65535 38405 0 0]Why did he confess all[n]of a sudden like that?[n]Has he gone crazy?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_10_ [Shiho]]
[s][vp 9 2 65535 44860 0 0]I can't believe he sexually[n]harassed those girls. Tch,[n]abusing his power like that...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_03_ [Shiho]]
[s][vp 9 2 65535 40905 0 0]He admitted it...? Geez, if he[n]was gonna confess anyway,[n]he never should've done it...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_04_ [Shiho]]
[s][vp 9 2 65535 38559 0 0]That pig just manhandled[n]those poor girls however he[n]wanted. That's so disgusting...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_11_ [Shiho]]
[s][vp 9 2 65535 42703 0 0]Why did he confess all[n]of a sudden like that?[n]Has he gone crazy?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_12_ [Shiho]]
[s][vp 9 2 65535 42401 0 0]I can't believe he sexually[n]harassed those girls. Tch,[n]abusing his power like that...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_05_ [Shiho]]
[s][vp 9 2 65535 38405 0 0]Why did he confess all[n]of a sudden like that?[n]Has he gone crazy?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_06_ [Shiho]]
[s][vp 9 2 65535 44860 0 0]I can't believe he sexually[n]harassed those girls. Tch,[n]abusing his power like that...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_13_ [Shiho]]
[s][vp 9 2 65535 46355 0 0]Why'd he confess all of[n]a sudden? I don't get it...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_14_ [Shiho]]
[s][vp 9 2 65535 38405 0 0]Why did he confess all[n]of a sudden like that?[n]Has he gone crazy?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_07_ [Shiho]]
[s][vp 9 2 65535 42703 0 0]Why did he confess all[n]of a sudden like that?[n]Has he gone crazy?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_08_ [Shiho]]
[s][vp 9 2 65535 42401 0 0]I can't believe he sexually[n]harassed those girls. Tch,[n]abusing his power like that...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_15_ [Shiho]]
[s][vp 9 2 65535 40905 0 0]He admitted it...? Geez, if he[n]was gonna confess anyway,[n]he never should've done it...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_16_ [Shiho]]
[s][vp 9 2 65535 38559 0 0]That pig just manhandled[n]those poor girls however he[n]wanted. That's so disgusting...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_01_ [Shiho]]
[s][vp 9 2 65535 46305 0 0]I'm not really into art,[n]but it sounds like he's[n]a famous painter.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_02_ [Shiho]]
[s][vp 9 2 65535 41653 0 0]His works have gotten rave[n]reviews all around the world.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_03_ [Shiho]]
[s][vp 9 2 65535 41750 0 0]I saw him on TV.[n]His art's pretty good.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_04_ [Shiho]]
[s][vp 9 2 65535 44454 0 0]Have you heard of Madarame?[n]He's this famous painter[n]everyone's talking about.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_05_ [Shiho]]
[s][vp 9 2 65535 40904 0 0]I'm not really into art,[n]but it sounds like he's[n]a famous painter.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_06_ [Shiho]]
[s][vp 9 2 65535 45453 0 0]His works have gotten rave[n]reviews all around the world.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_07_ [Shiho]]
[s][vp 9 2 65535 38753 0 0]I saw him on TV.[n]His art's pretty good.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_08_ [Shiho]]
[s][vp 9 2 65535 46354 0 0]I heard he's known[n]around the world![n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_01_ [Shiho]]
[s][vp 9 2 65535 37854 0 0]Extortion and scams... And[n]I hear they sell drugs, too...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_02_ [Shiho]]
[s][vp 9 2 65535 43359 0 0]What are the police doing!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_03_ [Shiho]]
[s][vp 9 2 65535 38402 0 0]Are the stories about those[n]scams and extortion true?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_04_ [Shiho]]
[s][vp 9 2 65535 38054 0 0]Wait, are they really[n]victimizing students?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_05_ [Shiho]]
[s][vp 9 2 65535 42704 0 0]Things have been getting[n]pretty dangerous around[n]here these days.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_06_ [Shiho]]
[s][vp 9 2 65535 37952 0 0]Organized crime? Just[n]thinking about it is scary...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_07_ [Shiho]]
[s][vp 9 2 65535 38205 0 0]Are the stories about those[n]scams and extortion true?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_08_ [Shiho]]
[s][vp 9 2 65535 43852 0 0]What are the police doing!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_01_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_02_ [Shiho]]
[s][vp 9 2 65535 44550 0 0]You know, all those strange[n]incidents just sort of[n]stopped all of a sudden.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_03_ [Shiho]]
[s][vp 9 2 65535 40302 0 0]I feel like they'll start[n]happening again if we[n]let our guard down.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_04_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_05_ [Shiho]]
[s][vp 9 2 65535 38754 0 0]Doesn't it feel like another[n]crazy accident's gonna[n]happen again soon?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_06_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_07_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_08_ [Shiho]]
[s][vp 9 2 65535 42454 0 0]I can't help but feel scared.[n]I mean, they could happen at[n]any time, without warning...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_01_ [Shiho]]
[s][vp 9 2 65535 39104 0 0]That painter's been[n]famous for a while, right?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_02_ [Shiho]]
[s][vp 9 2 65535 42953 0 0]I'm really glad I went.[n]All the paintings there[n]were so beautiful.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_03_ [Shiho]]
[s][vp 9 2 65535 37900 0 0]People really like that painter.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_04_ [Shiho]]
[s][vp 9 2 65535 45050 0 0]I heard he lives a pretty[n]modest lifestyle, even[n]though he's so famous.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_05_ [Shiho]]
[s][vp 9 2 65535 40304 0 0]Oh, that painter's[n]exhibition is in Shibuya?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_06_ [Shiho]]
[s][vp 9 2 65535 41650 0 0]The paintings were all[n]so wonderful... I want[n]to go again![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_07_ [Shiho]]
[s][vp 9 2 65535 44354 0 0]He seems like a good[n]teacher. His students[n]must be very happy.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_08_ [Shiho]]
[s][vp 9 2 65535 43353 0 0]I'm so jealous of everyone[n]that got to see Madarame's[n]exhibition...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_01_ [Shiho]]
[s][vp 9 2 65535 40103 0 0]That old man's a real disgrace.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_02_ [Shiho]]
[s][vp 9 2 65535 41251 0 0]It's the media's fault too, for[n]giving him so much attention![n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_03_ [Shiho]]
[s][vp 9 2 65535 41505 0 0]I'm sure there are a[n]lot more people out[n]there like him, too...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_04_ [Shiho]]
[s][vp 9 2 65535 46405 0 0]All of them were forgeries? He[n]really conned us into thinking[n]he was this magnificent man...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_05_ [Shiho]]
[s][vp 9 2 65535 43004 0 0]Has there been any news[n]since that calling card[n]thing happened?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_06_ [Shiho]]
[s][vp 9 2 65535 43804 0 0]"Phantom thieves"?[n]Please, stop joking...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_07_ [Shiho]]
[s][vp 9 2 65535 43753 0 0]What a pitiful sight.[n]A grown man, crying[n]and screaming like that...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_08_ [Shiho]]
[s][vp 9 2 65535 40951 0 0]Just because he apologized[n]doesn't mean people will[n]forgive what he'd done...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_09_ [Shiho]]
[s][vp 9 2 65535 39352 0 0]I went to his exhibition[n]too... I'm shocked...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_10_ [Shiho]]
[s][vp 9 2 65535 38152 0 0]Plagiarizing is so wack.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_11_ [Shiho]]
[s][vp 9 2 65535 41052 0 0]Only talentless people resort[n]to this kind of despicable crap...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_12_ [Shiho]]
[s][vp 9 2 65535 39302 0 0]Look at how much he's[n]crying. What a disgrace...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_01_ [Shiho]]
[s][vp 9 2 65535 37552 0 0]Are the stories about those[n]scams and extortion true?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_02_ [Shiho]]
[s][vp 9 2 65535 42409 0 0]What are the police doing!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_03_ [Shiho]]
[s][vp 9 2 65535 41604 0 0]Are the stories about those[n]scams and extortion true?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_04_ [Shiho]]
[s][vp 9 2 65535 42604 0 0]Wait, are they really[n]victimizing students?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_05_ [Shiho]]
[s][vp 9 2 65535 45652 0 0]Are the stories about those[n]scams and extortion true?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_06_ [Shiho]]
[s][vp 9 2 65535 43602 0 0]What's going to[n]happen to this city...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_07_ [Shiho]]
[s][vp 9 2 65535 44604 0 0]Are the stories about those[n]scams and extortion true?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_08_ [Shiho]]
[s][vp 9 2 65535 44502 0 0]What are the police doing!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_01_ [Shiho]]
[s][vp 9 2 65535 42255 0 0]There's no way that the[n]Phantom Thieves really exist...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_02_ [Shiho]]
[s][vp 9 2 65535 41404 0 0]I heard there were some weird[n]posters put up around town...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_09_ [Shiho]]
[s][vp 9 2 65535 40905 0 0]All this talk about[n]phantom thieves is so stupid...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_10_ [Shiho]]
[s][vp 9 2 65535 40004 0 0]Phantom thieves[n]in Shibuya again?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_03_ [Shiho]]
[s][vp 9 2 65535 38105 0 0]There's no way that the[n]Phantom Thieves really exist...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_04_ [Shiho]]
[s][vp 9 2 65535 40454 0 0]You know, it'd be kind[n]of exciting if those[n]calling cards were real.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_11_ [Shiho]]
[s][vp 9 2 65535 37604 0 0]Wait, wasn't someone also[n]talking about the Phantom[n]Thieves earlier?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_12_ [Shiho]]
[s][vp 9 2 65535 45753 0 0]I heard people are seeing some[n]strange posters in Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_05_ [Shiho]]
[s][vp 9 2 65535 37905 0 0]There's no way that the[n]Phantom Thieves really exist...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_06_ [Shiho]]
[s][vp 9 2 65535 40004 0 0]Phantom thieves[n]in Shibuya again?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_13_ [Shiho]]
[s][vp 9 2 65535 37604 0 0]Wait, wasn't someone also[n]talking about the Phantom[n]Thieves earlier?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_14_ [Shiho]]
[s][vp 9 2 65535 45753 0 0]I heard people are seeing some[n]strange posters in Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_07_ [Shiho]]
[s][vp 9 2 65535 37604 0 0]Wait, wasn't someone also[n]talking about the Phantom[n]Thieves earlier?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_08_ [Shiho]]
[s][vp 9 2 65535 45753 0 0]I heard people are seeing some[n]strange posters in Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_15_ [Shiho]]
[s][vp 9 2 65535 37905 0 0]There's no way that the[n]Phantom Thieves really exist...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_16_ [Shiho]]
[s][vp 9 2 65535 40004 0 0]Phantom thieves[n]in Shibuya again?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_01_ [Shiho]]
[s][vp 9 2 65535 37904 0 0]I heard the person behind[n]those scams got arrested.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_02_ [Shiho]]
[s][vp 9 2 65535 45150 0 0]Hopefully, all these terrible[n]crimes will stop happening now.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_03_ [Shiho]]
[s][vp 9 2 65535 38703 0 0]I heard the person behind[n]those scams got arrested.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_04_ [Shiho]]
[s][vp 9 2 65535 46203 0 0]Let's go hang out in Shibuya![n]It's finally safe to go now.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_05_ [Shiho]]
[s][vp 9 2 65535 42550 0 0]Kaneshiro's arrest is the best[n]news I've heard in a while.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_06_ [Shiho]]
[s][vp 9 2 65535 42154 0 0]I saw on the news that they[n]caught a major criminal.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_07_ [Shiho]]
[s][vp 9 2 65535 46304 0 0]I heard the person behind[n]those scams got arrested.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_08_ [Shiho]]
[s][vp 9 2 65535 45454 0 0]I saw on the news that they[n]caught a major criminal.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_01_ [Shiho]]
[s][vp 9 2 65535 42204 0 0]I heard the Phantom[n]Thieves were involved![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_02_ [Shiho]]
[s][vp 9 2 65535 41256 0 0]Did you see the news?[n]That calling card was real![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_03_ [Shiho]]
[s][vp 9 2 65535 38204 0 0]I heard the Phantom[n]Thieves were involved![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_04_ [Shiho]]
[s][vp 9 2 65535 42006 0 0]They're way better[n]than the police![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_05_ [Shiho]]
[s][vp 9 2 65535 39754 0 0]I heard the Phantom[n]Thieves were involved![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_06_ [Shiho]]
[s][vp 9 2 65535 40454 0 0]Did you see the news?[n]That calling card was real![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_07_ [Shiho]]
[s][vp 9 2 65535 40354 0 0]I heard the Phantom[n]Thieves were involved![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_08_ [Shiho]]
[s][vp 9 2 65535 43454 0 0]Did you see the news?[n]That calling card was real![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_01_ [Shiho]]
[s][vp 9 2 65535 42206 0 0]What are those Phantom[n]Thieves going to do?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_02_ [Shiho]]
[s][vp 9 2 65535 46204 0 0]It'd be so cool if they[n]had a showdown![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_09_ [Shiho]]
[s][vp 9 2 65535 45654 0 0]What's this about the Phantom[n]Thieves dispensing false justice?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_10_ [Shiho]]
[s][vp 9 2 65535 41556 0 0]They really threw down the[n]gauntlet. I wonder what the[n]Phantom Thieves will do.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_03_ [Shiho]]
[s][vp 9 2 65535 44704 0 0]What are those Phantom[n]Thieves going to do?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_04_ [Shiho]]
[s][vp 9 2 65535 40454 0 0]Is there going to be another[n]huge commotion about this?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_11_ [Shiho]]
[s][vp 9 2 65535 45654 0 0]What's this about the Phantom[n]Thieves dispensing false justice?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_12_ [Shiho]]
[s][vp 9 2 65535 41556 0 0]They really threw down the[n]gauntlet. I wonder what the[n]Phantom Thieves will do.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_05_ [Shiho]]
[s][vp 9 2 65535 42655 0 0]What are those Phantom[n]Thieves going to do?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_06_ [Shiho]]
[s][vp 9 2 65535 38954 0 0]I wonder if people[n]are going to get in an[n]uproar over this too...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_13_ [Shiho]]
[s][vp 9 2 65535 45654 0 0]What's this about the Phantom[n]Thieves dispensing false justice?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_14_ [Shiho]]
[s][vp 9 2 65535 41556 0 0]They really threw down the[n]gauntlet. I wonder what the[n]Phantom Thieves will do.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_07_ [Shiho]]
[s][vp 9 2 65535 45654 0 0]What's this about the Phantom[n]Thieves dispensing false justice?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_08_ [Shiho]]
[s][vp 9 2 65535 41556 0 0]They really threw down the[n]gauntlet. I wonder what the[n]Phantom Thieves will do.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_15_ [Shiho]]
[s][vp 9 2 65535 42655 0 0]What are those Phantom[n]Thieves going to do?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_16_ [Shiho]]
[s][vp 9 2 65535 38954 0 0]I wonder if people[n]are going to get in an[n]uproar over this too...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_01_ [Shiho]]
[s][vp 9 2 65535 41953 0 0]I wonder how the[n]Phantom Thieves[n]will handle this one.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_02_ [Shiho]]
[s][vp 9 2 65535 38955 0 0]The Phantom Thieves[n]have been keeping quiet.[n]What's going to happen...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_09_ [Shiho]]
[s][vp 9 2 65535 40156 0 0]What can the Phantom[n]Thieves do against hackers...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_10_ [Shiho]]
[s][vp 9 2 65535 40256 0 0]Japan's being targeted.[n]I really hope they do[n]something about it.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_03_ [Shiho]]
[s][vp 9 2 65535 40156 0 0]What can the Phantom[n]Thieves do against hackers...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_04_ [Shiho]]
[s][vp 9 2 65535 40256 0 0]Japan's being targeted.[n]I really hope they do[n]something about it.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_11_ [Shiho]]
[s][vp 9 2 65535 41953 0 0]I wonder how the Phantom[n]Thieves will handle this one.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_12_ [Shiho]]
[s][vp 9 2 65535 38955 0 0]The Phantom Thieves[n]have been keeping quiet.[n]What's going to happen...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_05_ [Shiho]]
[s][vp 9 2 65535 38206 0 0]What can the Phantom[n]Thieves do against hackers...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_06_ [Shiho]]
[s][vp 9 2 65535 44451 0 0]What are the Phantom[n]Thieves thinking? Hurry[n]up and do something![n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_13_ [Shiho]]
[s][vp 9 2 65535 40156 0 0]Wonder what the Phantom[n]Thieves' next move is going[n]to be.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_14_ [Shiho]]
[s][vp 9 2 65535 40256 0 0]Japan's being targeted.[n]I really hope they do[n]something about it.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_07_ [Shiho]]
[s][vp 9 2 65535 38405 0 0]What can the Phantom[n]Thieves do against hackers...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_08_ [Shiho]]
[s][vp 9 2 65535 45452 0 0]The Phantom Thieves[n]have been keeping quiet.[n]What's going to happen...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_15_ [Shiho]]
[s][vp 9 2 65535 40156 0 0]Wonder what the Phantom[n]Thieves' next move is going[n]to be.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_16_ [Shiho]]
[s][vp 9 2 65535 40256 0 0]Japan's being targeted.[n]I really hope they do[n]something about it.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_01_ [Shiho]]
[s][vp 9 2 65535 40304 0 0]Medjed's site was shut[n]down? Did those[n]Phantom Thieves do it?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_02_ [Shiho]]
[s][vp 9 2 65535 46200 0 0]Does this mean the Phantom[n]Thieves beat those hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_03_ [Shiho]]
[s][vp 9 2 65535 40754 0 0]Does this mean the[n]Phantom Thieves won[n]against the hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_04_ [Shiho]]
[s][vp 9 2 65535 45156 0 0]Wait, the hackers' site[n]was really shut down!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_05_ [Shiho]]
[s][vp 9 2 65535 38804 0 0]Medjed's site was shut[n]down? Did those[n]Phantom Thieves do it?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_06_ [Shiho]]
[s][vp 9 2 65535 43803 0 0]If the hackers shut down[n]their site, does that mean[n]the Phantom Thieves won?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_07_ [Shiho]]
[s][vp 9 2 65535 40503 0 0]Medjed's site was shut[n]down? Did those[n]Phantom Thieves do it?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_08_ [Shiho]]
[s][vp 9 2 65535 44456 0 0]Does this mean the Phantom[n]Thieves beat those hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_01_ [Shiho]]
[s][vp 9 2 65535 42706 0 0]It was the Phantom Thieves[n]who saved us, right?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_02_ [Shiho]]
[s][vp 9 2 65535 39006 0 0]The Phantom Thieves[n]protected us from[n]the hackers![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_03_ [Shiho]]
[s][vp 9 2 65535 43400 0 0]It was the Phantom Thieves[n]who saved us, right?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_04_ [Shiho]]
[s][vp 9 2 65535 37756 0 0]The Phantom Thieves[n]even took down Medjed![n]Aren't they awesome!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_05_ [Shiho]]
[s][vp 9 2 65535 37506 0 0]It was the Phantom Thieves[n]who saved us, right?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_06_ [Shiho]]
[s][vp 9 2 65535 38300 0 0]They did a great job![n]The Phantom Thieves[n]are awesome![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_07_ [Shiho]]
[s][vp 9 2 65535 38806 0 0]The Phantom Thieves rule![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_08_ [Shiho]]
[s][vp 9 2 65535 39350 0 0]The Phantom Thieves[n]really are amazing people![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_01_ [Shiho]]
[s][vp 9 2 65535 39406 0 0]Steal all the evil[n]hearts in the world![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_02_ [Shiho]]
[s][vp 9 2 65535 37703 0 0]They've been talking a[n]lot about the Phantom[n]Thieves on TV, too.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_09_ [Shiho]]
[s][vp 9 2 65535 46306 0 0]I'm thankful for those Phantom[n]Thieves. It's no surprise that[n]they're so popular.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_10_ [Shiho]]
[s][vp 9 2 65535 37753 0 0]Those Phantom Thieves[n]are really amazing![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_03_ [Shiho]]
[s][vp 9 2 65535 46306 0 0]I'm thankful for those Phantom[n]Thieves. It's no surprise that[n]they're so popular.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_04_ [Shiho]]
[s][vp 9 2 65535 37753 0 0]Those Phantom Thieves[n]are really amazing![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_11_ [Shiho]]
[s][vp 9 2 65535 39406 0 0]Steal all the evil[n]hearts in the world![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_12_ [Shiho]]
[s][vp 9 2 65535 37703 0 0]They've been talking a[n]lot about the Phantom[n]Thieves on TV, too.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_05_ [Shiho]]
[s][vp 9 2 65535 40506 0 0]The Phantom Thieves'[n]popularity is only natural,[n]right? I mean, they deserve it.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_06_ [Shiho]]
[s][vp 9 2 65535 39653 0 0]The Phantom Thieves are[n]going to change the world![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_13_ [Shiho]]
[s][vp 9 2 65535 38150 0 0]I admit it. I wish I were[n]cool and fabulous enough to[n]send a calling card like that![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_14_ [Shiho]]
[s][vp 9 2 65535 43306 0 0]Talk about phantom thieves[n]is nonstop on TV these days.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_07_ [Shiho]]
[s][vp 9 2 65535 38150 0 0]I admit it. I wish I were[n]cool and fabulous enough to[n]send a calling card like that![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_08_ [Shiho]]
[s][vp 9 2 65535 43306 0 0]Talk about phantom thieves[n]is nonstop on TV these days.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_15_ [Shiho]]
[s][vp 9 2 65535 40506 0 0]The Phantom Thieves'[n]popularity is only natural,[n]right? I mean, they deserve it.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_16_ [Shiho]]
[s][vp 9 2 65535 39653 0 0]The Phantom Thieves are[n]going to change the world![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_01_ [Shiho]]
[s][vp 9 2 65535 42203 0 0]I never thought Okumura[n]Foods would be such a[n]corrupt company...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_02_ [Shiho]]
[s][vp 9 2 65535 43204 0 0]It sounds like they did[n]some pretty shady things[n]behind the scenes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_09_ [Shiho]]
[s][vp 9 2 65535 42704 0 0]I didn't expect Okumura[n]Foods to be such a[n]corrupt corporation...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_10_ [Shiho]]
[s][vp 9 2 65535 43451 0 0]They treat their employees[n]like slaves? That's terrible![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_03_ [Shiho]]
[s][vp 9 2 65535 42704 0 0]I didn't expect Okumura[n]Foods to be such a[n]corrupt corporation...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_04_ [Shiho]]
[s][vp 9 2 65535 43451 0 0]They treat their employees[n]like slaves? That's terrible![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_11_ [Shiho]]
[s][vp 9 2 65535 42203 0 0]I never thought Okumura[n]Foods would be such a[n]corrupt company...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_12_ [Shiho]]
[s][vp 9 2 65535 43204 0 0]It sounds like they did[n]some pretty shady things[n]behind the scenes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_05_ [Shiho]]
[s][vp 9 2 65535 43754 0 0]I'm surprised this matter[n]wasn't made public until now...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_06_ [Shiho]]
[s][vp 9 2 65535 43604 0 0]Did you see the news[n]about Okumura Foods?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_13_ [Shiho]]
[s][vp 9 2 65535 42704 0 0]I didn't expect Okumura[n]Foods to be such a[n]corrupt corporation...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_14_ [Shiho]]
[s][vp 9 2 65535 43451 0 0]They treat their employees[n]like slaves? That's terrible![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_07_ [Shiho]]
[s][vp 9 2 65535 46304 0 0]I'm surprised this matter[n]wasn't made public until now...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_08_ [Shiho]]
[s][vp 9 2 65535 38601 0 0]I was so shocked[n]when I saw the news...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_15_ [Shiho]]
[s][vp 9 2 65535 42203 0 0]I never thought Okumura[n]Foods would be such a[n]corrupt company...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_16_ [Shiho]]
[s][vp 9 2 65535 43204 0 0]It sounds like they did[n]some pretty shady things[n]behind the scenes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_01_ [Shiho]]
[s][vp 9 2 65535 37906 0 0]I hope the Phantom Thieves[n]keep working to reform society.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_02_ [Shiho]]
[s][vp 9 2 65535 38004 0 0]How about Okumura? His[n]business practices are[n]questionable, I hear.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_09_ [Shiho]]
[s][vp 9 2 65535 45654 0 0]I'm interested to see what the[n]Phantom Thieves will do next.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_10_ [Shiho]]
[s][vp 9 2 65535 39306 0 0]Isn't it about time for the[n]Phantom Thieves to take action?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_03_ [Shiho]]
[s][vp 9 2 65535 45654 0 0]I'm interested to see what the[n]Phantom Thieves will do next.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_04_ [Shiho]]
[s][vp 9 2 65535 39306 0 0]Isn't it about time for the[n]Phantom Thieves to take action?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_11_ [Shiho]]
[s][vp 9 2 65535 37906 0 0]I hope the Phantom Thieves[n]keep working to reform society.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_12_ [Shiho]]
[s][vp 9 2 65535 38004 0 0]How about Okumura? His[n]business practices are[n]questionable, I hear.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_05_ [Shiho]]
[s][vp 9 2 65535 41750 0 0]I hope the Phantom Thieves[n]keep working to reform society.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_06_ [Shiho]]
[s][vp 9 2 65535 40654 0 0]A lot of people are talking[n]about the president of[n]Okumura Foods...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_13_ [Shiho]]
[s][vp 9 2 65535 44706 0 0]I'm interested to see what the[n]Phantom Thieves will do next.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_14_ [Shiho]]
[s][vp 9 2 65535 39303 0 0]Who are they gonna target[n]next? I'm kind of excited[n]to see who it will be.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_07_ [Shiho]]
[s][vp 9 2 65535 44706 0 0]I'm interested to see what the[n]Phantom Thieves will do next.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_08_ [Shiho]]
[s][vp 9 2 65535 39303 0 0]Who are they gonna target[n]next? I'm kind of excited[n]to see who it will be.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_15_ [Shiho]]
[s][vp 9 2 65535 41750 0 0]I hope the Phantom Thieves[n]keep working to reform society.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_16_ [Shiho]]
[s][vp 9 2 65535 40654 0 0]A lot of people are talking[n]about the president of[n]Okumura Foods...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_01_ [Shiho]]
[s][vp 9 2 65535 44601 0 0]Don't let him get away![n]We're counting on you,[n]Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_02_ [Shiho]]
[s][vp 9 2 65535 41550 0 0]Just take out that[n]awful CEO already![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_09_ [Shiho]]
[s][vp 9 2 65535 38206 0 0]So the Phantom Thieves[n]are going for President[n]Okumura after all![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_10_ [Shiho]]
[s][vp 9 2 65535 41303 0 0]Take down that crooked CEO![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_03_ [Shiho]]
[s][vp 9 2 65535 38206 0 0]So the Phantom Thieves[n]are going for President[n]Okumura after all![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_04_ [Shiho]]
[s][vp 9 2 65535 41303 0 0]Take down that crooked CEO![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_11_ [Shiho]]
[s][vp 9 2 65535 44601 0 0]Don't let him get away![n]We're counting on you,[n]Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_12_ [Shiho]]
[s][vp 9 2 65535 41550 0 0]Just take out that[n]awful CEO already![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_05_ [Shiho]]
[s][vp 9 2 65535 39451 0 0]Don't let him get[n]away, Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_06_ [Shiho]]
[s][vp 9 2 65535 43106 0 0]Just take out that[n]awful CEO already![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_13_ [Shiho]]
[s][vp 9 2 65535 40750 0 0]So the Phantom Thieves[n]are going for President[n]Okumura after all![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_14_ [Shiho]]
[s][vp 9 2 65535 42956 0 0]Yeah, Phantom Thieves![n]Kick their asses![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_07_ [Shiho]]
[s][vp 9 2 65535 40750 0 0]So the Phantom Thieves[n]are going for President[n]Okumura after all![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_08_ [Shiho]]
[s][vp 9 2 65535 42956 0 0]Yeah, Phantom Thieves![n]Kick their asses![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_15_ [Shiho]]
[s][vp 9 2 65535 39451 0 0]Don't let him get[n]away, Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_16_ [Shiho]]
[s][vp 9 2 65535 43106 0 0]Just take out that[n]awful CEO already![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_01_ [Shiho]]
[s][vp 9 2 65535 37607 0 0]Was that supposed to[n]be a change of heart?[n]That was just murder![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_02_ [Shiho]]
[s][vp 9 2 65535 38252 0 0]They change a person's heart[n]by killing them? They're crazy![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_09_ [Shiho]]
[s][vp 9 2 65535 37857 0 0]You can't be serious![n]Is that what they call[n]a change of heart!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_10_ [Shiho]]
[s][vp 9 2 65535 45107 0 0]All that stuff about changing[n]hearts was a lie! They're[n]just murderers![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_03_ [Shiho]]
[s][vp 9 2 65535 38502 0 0]Was that supposed to[n]be a change of heart?[n]That was just murder![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_04_ [Shiho]]
[s][vp 9 2 65535 38302 0 0]Did they really have to kill him!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_11_ [Shiho]]
[s][vp 9 2 65535 37857 0 0]You can't be serious![n]Is that what they call[n]a change of heart!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_12_ [Shiho]]
[s][vp 9 2 65535 45107 0 0]All that stuff about changing[n]hearts was a lie! They're[n]just murderers![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_05_ [Shiho]]
[s][vp 9 2 65535 37857 0 0]You can't be serious![n]Is that what they call[n]a change of heart!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_06_ [Shiho]]
[s][vp 9 2 65535 45107 0 0]All that stuff about changing[n]hearts was a lie! They're[n]just murderers![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_13_ [Shiho]]
[s][vp 9 2 65535 38701 0 0]Was that supposed to[n]be a change of heart?[n]That was just murder![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_14_ [Shiho]]
[s][vp 9 2 65535 46207 0 0]They change a person's heart[n]by killing them? They're crazy![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_07_ [Shiho]]
[s][vp 9 2 65535 38701 0 0]Was that supposed to[n]be a change of heart?[n]That was just murder![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_08_ [Shiho]]
[s][vp 9 2 65535 46207 0 0]They change a person's heart[n]by killing them? They're crazy![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_15_ [Shiho]]
[s][vp 9 2 65535 37857 0 0]You can't be serious![n]Is that what they call[n]a change of heart!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_16_ [Shiho]]
[s][vp 9 2 65535 45107 0 0]All that stuff about changing[n]hearts was a lie! They're[n]just murderers![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_01_ [Shiho]]
[s][vp 9 2 65535 39402 0 0]Those Phantom Thieves are[n]monsters. They need to be[n]locked up in prison...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_02_ [Shiho]]
[s][vp 9 2 65535 46201 0 0]Why isn't the government[n]doing anything? Where's[n]the police!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_09_ [Shiho]]
[s][vp 9 2 65535 40907 0 0]Someone capture those[n]goddamn Phantom[n]Thieves already![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_10_ [Shiho]]
[s][vp 9 2 65535 41559 0 0]What are the police doing!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_03_ [Shiho]]
[s][vp 9 2 65535 38507 0 0]Those Phantom Thieves are[n]monsters. They need to be[n]locked up in prison...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_04_ [Shiho]]
[s][vp 9 2 65535 45452 0 0]It doesn't matter who does[n]it, somebody has to stop[n]the Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_11_ [Shiho]]
[s][vp 9 2 65535 40907 0 0]Someone capture those[n]goddamn Phantom[n]Thieves already![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_12_ [Shiho]]
[s][vp 9 2 65535 41559 0 0]What are the police doing!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_05_ [Shiho]]
[s][vp 9 2 65535 41051 0 0]Those Phantom Thieves are[n]monsters. They need to be[n]locked up in prison...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_06_ [Shiho]]
[s][vp 9 2 65535 41559 0 0]What are the police doing!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_13_ [Shiho]]
[s][vp 9 2 65535 40907 0 0]Someone capture those[n]goddamn Phantom[n]Thieves already![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_14_ [Shiho]]
[s][vp 9 2 65535 41559 0 0]What are the police doing!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_07_ [Shiho]]
[s][vp 9 2 65535 42207 0 0]Those Phantom Thieves are[n]monsters. They need to be[n]locked up in prison...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_08_ [Shiho]]
[s][vp 9 2 65535 38551 0 0]Why isn't the government[n]doing anything? Where's[n]the police!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_15_ [Shiho]]
[s][vp 9 2 65535 40907 0 0]Someone capture those[n]goddamn Phantom[n]Thieves already![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_16_ [Shiho]]
[s][vp 9 2 65535 41559 0 0]What are the police doing!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_01_ [Shiho]]
[s][vp 9 2 65535 43157 0 0]If they're offering 30 million[n]yen as a reward, then it must[n]be pretty bad...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_02_ [Shiho]]
[s][vp 9 2 65535 39351 0 0]Just arrest them already![n]I don't care how you do it![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_09_ [Shiho]]
[s][vp 9 2 65535 43702 0 0]NOW they're putting[n]out a reward!? What have[n]the police been doing?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_10_ [Shiho]]
[s][vp 9 2 65535 39705 0 0]That's a pretty hefty[n]reward... I just hope[n]it gets them arrested.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_03_ [Shiho]]
[s][vp 9 2 65535 43702 0 0]NOW they're putting[n]out a reward!? What have[n]the police been doing?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_04_ [Shiho]]
[s][vp 9 2 65535 39705 0 0]That's a pretty hefty[n]reward... I just hope[n]it gets them arrested.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_11_ [Shiho]]
[s][vp 9 2 65535 43157 0 0]If they're offering 30 million[n]yen as a reward, then it must[n]be pretty bad...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_12_ [Shiho]]
[s][vp 9 2 65535 39351 0 0]Just arrest them already![n]I don't care how you do it![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_05_ [Shiho]]
[s][vp 9 2 65535 42851 0 0]How long are they going to[n]let those murderers run free!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_06_ [Shiho]]
[s][vp 9 2 65535 43354 0 0]Oh, so the police finally[n]feel like taking action now?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_13_ [Shiho]]
[s][vp 9 2 65535 43702 0 0]NOW they're putting[n]out a reward!? What have[n]the police been doing?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_14_ [Shiho]]
[s][vp 9 2 65535 39705 0 0]That's a pretty hefty[n]reward... I just hope[n]it gets them arrested.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_07_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_08_ [Shiho]]
[s][vp 9 2 65535 42003 0 0]Did you see the news? The[n]amount of money they're[n]offering is ridiculously huge...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_521_14_ [Shiho]]
[s][vp 9 2 65535 45501 0 0]They need to hurry up with[n]a plan that'll work. Our[n]lives are at stake here...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_15_ [Shiho]]
[s][vp 9 2 65535 42851 0 0]How long are they going to[n]let those murderers run free!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_16_ [Shiho]]
[s][vp 9 2 65535 43354 0 0]Oh, so the police finally[n]feel like taking action now?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_01_ [Shiho]]
[s][vp 9 2 65535 46004 0 0]They just formed a new[n]political party recently, right?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_02_ [Shiho]]
[s][vp 9 2 65535 40654 0 0]What's it called again? That new[n]party that they just formed.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_03_ [Shiho]]
[s][vp 9 2 65535 40355 0 0]The next administration had[n]better be more competent![n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_04_ [Shiho]]
[s][vp 9 2 65535 39654 0 0]Aren't there any politicians who[n]actually think about our future?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_05_ [Shiho]]
[s][vp 9 2 65535 38405 0 0]Isn't there anybody who[n]can start up a revolution[n]in our society?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_06_ [Shiho]]
[s][vp 9 2 65535 42355 0 0]I just hope this new[n]party can actually change[n]things for the better...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_07_ [Shiho]]
[s][vp 9 2 65535 41359 0 0]Politicians are all the same.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_08_ [Shiho]]
[s][vp 9 2 65535 43254 0 0]The election for the House[n]of Reps is at the end of the[n]year? I wonder who'll win...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_01_ [Shiho]]
[s][vp 9 2 65535 39104 0 0]It feels like the culprits[n]might be from the school[n]where the rumors started.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_02_ [Shiho]]
[s][vp 9 2 65535 40001 0 0]If you have a profile of[n]the criminals, then go out[n]and catch them already![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_03_ [Shiho]]
[s][vp 9 2 65535 40507 0 0]How long are they going[n]to let such dangerous[n]people run free?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_04_ [Shiho]]
[s][vp 9 2 65535 38951 0 0]I don't care who does it, just[n]arrest the culprits already...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_05_ [Shiho]]
[s][vp 9 2 65535 41201 0 0]When are we going to hear[n]news that the Phantom Thieves[n]have been arrested?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_06_ [Shiho]]
[s][vp 9 2 65535 40651 0 0]What are the police[n]doing? Hurry up and[n]arrest them already![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_07_ [Shiho]]
[s][vp 9 2 65535 41351 0 0]Just how long are you[n]going to let the Phantom[n]Thieves run amok![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_08_ [Shiho]]
[s][vp 9 2 65535 39702 0 0]How long are they going to let[n]that gang of killers run free?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_01_ [Shiho]]
[s][vp 9 2 65535 38803 0 0]Did you hear Mr. Shido's[n]speech? He's quite respected,[n]considering how young he is.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_02_ [Shiho]]
[s][vp 9 2 65535 39650 0 0]Shido-san's amazing.[n]He's so dignified, even[n]though he's so young...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_03_ [Shiho]]
[s][vp 9 2 65535 41503 0 0]In this election, maybe I'll[n]vote for Representative Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_04_ [Shiho]]
[s][vp 9 2 65535 45253 0 0]Did you hear Shido-san's[n]speech? I was really surprised![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_05_ [Shiho]]
[s][vp 9 2 65535 37603 0 0]I think Shido has a really[n]good attitude for a leader.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_06_ [Shiho]]
[s][vp 9 2 65535 45053 0 0]From what I heard,[n]Representative Shido[n]is pretty capable![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_07_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_08_ [Shiho]]
[s][vp 9 2 65535 46053 0 0]I might vote for Shido-san[n]in the election at the[n]end of the year.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_01_ [Shiho]]
[s][vp 9 2 65535 38704 0 0]If that phantom thief died, then[n]that means we're safe, right?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_02_ [Shiho]]
[s][vp 9 2 65535 46400 0 0]With that phantom thief[n]gone, we can finally relax...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_03_ [Shiho]]
[s][vp 9 2 65535 39451 0 0]He must be insane to[n]just kill himself after[n]getting arrested...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_04_ [Shiho]]
[s][vp 9 2 65535 39652 0 0]I never imagined that[n]phantom thief would[n]just commit suicide...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_05_ [Shiho]]
[s][vp 9 2 65535 38404 0 0]To think, that phantom thief[n]was a minor. I had no idea...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_06_ [Shiho]]
[s][vp 9 2 65535 39705 0 0]That phantom thief died, right?[n]We should be okay now...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_07_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_08_ [Shiho]]
[s][vp 9 2 65535 40802 0 0]He killed himself in jail?[n]On the day he was arrested?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_01_ [Shiho]]
[s][vp 9 2 65535 41953 0 0]Representative Shido[n]was right! Everything's[n]going to be fine now![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_02_ [Shiho]]
[s][vp 9 2 65535 38354 0 0]Shido-san is going to make[n]this country great again![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_03_ [Shiho]]
[s][vp 9 2 65535 46003 0 0]Shido's going to[n]change the world![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_04_ [Shiho]]
[s][vp 9 2 65535 43103 0 0]The future that[n]Representative Shido[n]envisions must be great...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_05_ [Shiho]]
[s][vp 9 2 65535 41700 0 0]Shido's the only one who[n]can change this world now.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_06_ [Shiho]]
[s][vp 9 2 65535 43353 0 0]Representative Shido[n]all the way![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_07_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_08_ [Shiho]]
[s][vp 9 2 65535 45758 0 0]We'll be fine with things[n]in Shido-san's hands![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_01_ [Shiho]]
[s][vp 9 2 65535 42500 0 0]Representative Shido is[n]going to change this country.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_02_ [Shiho]]
[s][vp 9 2 65535 45453 0 0]Japan needs a man[n]like Shido-san![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_09_ [Shiho]]
[s][vp 9 2 65535 41950 0 0]This country will be[n]safe if we have Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_10_ [Shiho]]
[s][vp 9 2 65535 43200 0 0]We don't have to be scared[n]of anything if we follow[n]Representative Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_03_ [Shiho]]
[s][vp 9 2 65535 41950 0 0]This country will be[n]safe if we have Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_04_ [Shiho]]
[s][vp 9 2 65535 43200 0 0]We don't have to be scared[n]of anything if we follow[n]Representative Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_11_ [Shiho]]
[s][vp 9 2 65535 42500 0 0]Representative Shido is[n]going to change this country.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_12_ [Shiho]]
[s][vp 9 2 65535 45453 0 0]Japan needs a man[n]like Shido-san![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_05_ [Shiho]]
[s][vp 9 2 65535 45650 0 0]Shido has a persuasive[n]way of wording things.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_06_ [Shiho]]
[s][vp 9 2 65535 43300 0 0]Shido-san's way different[n]from other politicians![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_13_ [Shiho]]
[s][vp 9 2 65535 42500 0 0]Representative Shido is[n]going to change this country.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_14_ [Shiho]]
[s][vp 9 2 65535 44200 0 0]We'll be fine since[n]we have Shido-san![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_07_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_08_ [Shiho]]
[s][vp 9 2 65535 44200 0 0]We'll be fine since[n]we have Shido-san![n][f 1 2 180][e]

[msg MSG_GRT_main_All_527_14_ [Shiho]]
[s][vp 9 2 65535 45511 0 0]Shido-san just has this[n]different air about him.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_15_ [Shiho]]
[s][vp 9 2 65535 45650 0 0]Shido has a persuasive[n]way of wording things.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_16_ [Shiho]]
[s][vp 9 2 65535 43300 0 0]Shido-san's way different[n]from other politicians![n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_01_ [Shiho]]
[s][vp 9 2 65535 40105 0 0]That phantom thief died,[n]right? What's going on...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_02_ [Shiho]]
[s][vp 9 2 65535 45452 0 0]Is it true what those Phantom[n]Thieves are saying...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_09_ [Shiho]]
[s][vp 9 2 65535 39455 0 0]Why are the Phantom Thieves[n]targeting Shido? I don't get it...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_10_ [Shiho]]
[s][vp 9 2 65535 45102 0 0]Shido-san is in the right...[n]That's why I'm supporting him.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_03_ [Shiho]]
[s][vp 9 2 65535 39455 0 0]Why are the Phantom Thieves[n]targeting Shido? I don't get it...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_04_ [Shiho]]
[s][vp 9 2 65535 45102 0 0]Shido-san is in the right...[n]That's why I'm supporting him.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_11_ [Shiho]]
[s][vp 9 2 65535 40105 0 0]That phantom thief died,[n]right? What's going on...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_12_ [Shiho]]
[s][vp 9 2 65535 45452 0 0]Is it true what those Phantom[n]Thieves are saying...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_05_ [Shiho]]
[s][vp 9 2 65535 38402 0 0]Do those Phantom Thieves really[n]expect us to believe their[n]accusations that Shido is evil?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_06_ [Shiho]]
[s][vp 9 2 65535 44855 0 0]I don't really care[n]which of them is right...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_13_ [Shiho]]
[s][vp 9 2 65535 39455 0 0]Why are the Phantom Thieves[n]targeting Shido? I don't get it...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_14_ [Shiho]]
[s][vp 9 2 65535 45102 0 0]Shido-san is in the right...[n]That's why I'm supporting him.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_07_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_08_ [Shiho]]
[s][vp 9 2 65535 38957 0 0]What's going on? I thought[n]that phantom thief died...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_528_14_ [Shiho]]
[s][vp 9 2 65535 39155 0 0]Those Phantom Thieves[n]have to be lying, right...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_15_ [Shiho]]
[s][vp 9 2 65535 38402 0 0]Do those Phantom Thieves really[n]expect us to believe their[n]accusations that Shido is evil?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_16_ [Shiho]]
[s][vp 9 2 65535 44855 0 0]I don't really care[n]which of them is right...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_01_ [Shiho]]
[s][vp 9 2 65535 39402 0 0]He's taking time off[n]because he doesn't feel[n]well? I hope he'll be okay.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_02_ [Shiho]]
[s][vp 9 2 65535 37652 0 0]No way... This whole time, I've[n]been supporting Shido-san...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_09_ [Shiho]]
[s][vp 9 2 65535 41202 0 0]But Representative Shido[n]just won the election...[n]Why's this happening now?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_10_ [Shiho]]
[s][vp 9 2 65535 38552 0 0]I thought Shido-san was going[n]to change this country...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_03_ [Shiho]]
[s][vp 9 2 65535 41202 0 0]But Representative Shido[n]just won the election...[n]Why's this happening now?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_04_ [Shiho]]
[s][vp 9 2 65535 38552 0 0]I thought Shido-san was going[n]to change this country...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_11_ [Shiho]]
[s][vp 9 2 65535 39402 0 0]He's taking time off because[n]he doesn't feel well? I hope[n]he'll be okay.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_12_ [Shiho]]
[s][vp 9 2 65535 37652 0 0]No way... This whole time, I've[n]been supporting Shido-san...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_05_ [Shiho]]
[s][vp 9 2 65535 45652 0 0]How are they going to make[n]up for it if Shido disappears...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_06_ [Shiho]]
[s][vp 9 2 65535 39002 0 0]No! Shido-san can't stop now...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_13_ [Shiho]]
[s][vp 9 2 65535 41202 0 0]But Representative Shido[n]just won the election...[n]Why's this happening now?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_14_ [Shiho]]
[s][vp 9 2 65535 41252 0 0]Who's going to change[n]this country now...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_07_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_08_ [Shiho]]
[s][vp 9 2 65535 41252 0 0]Who's going to change[n]this country now...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_529_14_ [Shiho]]
[s][vp 9 2 65535 45302 0 0]No... Come back,[n]Representative Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_15_ [Shiho]]
[s][vp 9 2 65535 45652 0 0]How are they going to make[n]up for it if Shido disappears...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_16_ [Shiho]]
[s][vp 9 2 65535 39002 0 0]No! Shido-san can't stop now...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_01_ [Shiho]]
[s][vp 9 2 65535 40902 0 0]I don't know who to believe[n]in, or who to follow...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_02_ [Shiho]]
[s][vp 9 2 65535 43352 0 0]Why is this happening?[n]Someone help us, I don't[n]care who it is anymore...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_09_ [Shiho]]
[s][vp 9 2 65535 38502 0 0]What are we supposed[n]to do now...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_10_ [Shiho]]
[s][vp 9 2 65535 44002 0 0]How did this happen...?[n]Someone do something...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_03_ [Shiho]]
[s][vp 9 2 65535 38502 0 0]What are we supposed[n]to do now...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_04_ [Shiho]]
[s][vp 9 2 65535 44002 0 0]How did this happen...?[n]Someone do something...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_11_ [Shiho]]
[s][vp 9 2 65535 40902 0 0]I don't know who to believe[n]in, or who to follow...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_12_ [Shiho]]
[s][vp 9 2 65535 43352 0 0]Why is this happening?[n]Someone help us, I don't[n]care who it is anymore...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_05_ [Shiho]]
[s][vp 9 2 65535 42560 0 0]I can't keep living[n]in a world like this...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_06_ [Shiho]]
[s][vp 9 2 65535 44252 0 0]It's all over...[n]Somebody save us...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_13_ [Shiho]]
[s][vp 9 2 65535 40902 0 0]I don't know who to believe[n]in, or who to follow...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_14_ [Shiho]]
[s][vp 9 2 65535 43352 0 0]Why is this happening?[n]Someone help us, I don't[n]care who it is anymore...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_07_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_08_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_01_ [Shiho]]
[s][vp 9 2 65535 40908 0 0]Ooh, that looks good on you...[n]but this one's nice too![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_02_ [Shiho]]
[s][vp 9 2 65535 41005 0 0]I'm not going to do that.[n]I'm married, you know?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_03_ [Shiho]]
[s][vp 9 2 65535 59054 0 0]If I don't do this, my[n]subordinate will never[n]get a break.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_04_ [Shiho]]
[s][vp 9 2 65535 41553 0 0]Oh, this is where you[n]worked? That doesn't[n]really matter to me.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_05_ [Shiho]]
[s][vp 9 2 65535 38804 0 0]My mother and wife[n]left for a trip yesterday.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_06_ [Shiho]]
[s][vp 9 2 65535 59070 0 0]Uhh, I don't think I'll have time.[n]My relatives are coming over.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_07_ [Shiho]]
[s][vp 9 2 65535 59030 0 0]I don't consider myself[n]a pro, no. It's always just[n]been a hobby for me...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_08_ [Shiho]]
[s][vp 9 2 65535 40400 0 0]You should just wear[n]whatever you want.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_09_ [Shiho]]
[s][vp 9 2 65535 40154 0 0]Sleeping in all day[n]is a waste of time.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_10_ [Shiho]]
[s][vp 9 2 65535 58840 0 0]She doesn't get shy at all.[n]See, she's already getting[n]along with them.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_11_ [Shiho]]
[s][vp 9 2 65535 59050 0 0]Yeah, she's the one![n]I'm supposed to meet[n]her soon.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_12_ [Shiho]]
[s][vp 9 2 65535 46054 0 0]You've always been a[n]hard worker...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_13_ [Shiho]]
[s][vp 9 2 65535 58880 0 0]Whoa, so many cats... You[n]have a great sense of style.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_14_ [Shiho]]
[s][vp 9 2 65535 39603 0 0]Waiting is part of the[n]fun, don't you think?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_15_ [Shiho]]
[s][vp 9 2 65535 37550 0 0]Oh, it's okay! Please[n]don't worry about it.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_16_ [Shiho]]
[s][vp 9 2 65535 39252 0 0]Hey, did something happen?[n]...Wait, never mind.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_01_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_02_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_03_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_04_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_05_ [Shiho]]
[s][vp 9 2 65535 41705 0 0]March is already ending...[n]Where did the time go?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_06_ [Shiho]]
[s][vp 9 2 65535 40652 0 0]It's the start of[n]a new season, huh?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_07_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_08_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_01_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_02_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_03_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_04_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_05_ [Shiho]]
[s][vp 9 2 65535 42105 0 0]Society is so stupid...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_06_ [Shiho]]
[s][vp 9 2 65535 40655 0 0]If you just let it be, someone[n]will take care of it...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_07_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_08_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_01_ [Shiho]]
[s][vp 9 2 65535 41751 0 0]The train's been stopped for so[n]long. What the hell's going on?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_02_ [Shiho]]
[s][vp 9 2 65535 38602 0 0]There's been so many[n]accidents lately. One[n]could happen at any time...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_03_ [Shiho]]
[s][vp 9 2 65535 42551 0 0]The train's been stopped for so[n]long. What the hell's going on?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_04_ [Shiho]]
[s][vp 9 2 65535 38952 0 0]Safety here is a joke. I'm really[n]scared of taking the train...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_05_ [Shiho]]
[s][vp 9 2 65535 41201 0 0]Isn't it your job to make sure[n]the trains run on time!?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_06_ [Shiho]]
[s][vp 9 2 65535 41301 0 0]Now I can't get on the train[n]without feeling worried![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_07_ [Shiho]]
[s][vp 9 2 65535 41352 0 0]Am I going to make[n]it home safely...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_08_ [Shiho]]
[s][vp 9 2 65535 41402 0 0]Honestly, I'm too scared[n]to take the train now...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_01_ [Shiho]]
[s][vp 9 2 65535 43154 0 0]He was on Good Morning[n]Japan! He must be[n]a famous artist.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_02_ [Shiho]]
[s][vp 9 2 65535 38654 0 0]They were announcing that[n]there's going to be an[n]exhibition of Madarame's work.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_03_ [Shiho]]
[s][vp 9 2 65535 44904 0 0]They say he's preeminent[n]in the world of Japanese art.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_04_ [Shiho]]
[s][vp 9 2 65535 45753 0 0]Did you watch Good Morning[n]Japan? Madarame was on it![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_05_ [Shiho]]
[s][vp 9 2 65535 38803 0 0]He was on Good Morning[n]Japan! He must be[n]a famous artist.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_06_ [Shiho]]
[s][vp 9 2 65535 40654 0 0]They were announcing that[n]there's going to be an[n]exhibition of Madarame's work.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_07_ [Shiho]]
[s][vp 9 2 65535 40904 0 0]They say he's preeminent[n]in the world of Japanese art.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_08_ [Shiho]]
[s][vp 9 2 65535 42153 0 0]Madarame the artist was[n]on Good Morning Japan![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_01_ [Shiho]]
[s][vp 9 2 65535 40302 0 0]They're supposed to[n]be a pretty dangerous[n]group of criminals...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_02_ [Shiho]]
[s][vp 9 2 65535 40602 0 0]I've heard they actually[n]force you into prostitution...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_003 [Shiho]]
[s][vp 9 2 65535 39802 0 0]Daaang... They're pretty[n]much yakuza then...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_004 [Shiho]]
[s][vp 9 2 65535 39602 0 0]Some weirdo came up[n]and talked to meee...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_03_ [Shiho]]
[s][vp 9 2 65535 40554 0 0]They're supposed to[n]be a pretty dangerous[n]group of criminals...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_04_ [Shiho]]
[s][vp 9 2 65535 40004 0 0]I've heard more people are[n]becoming victims of crime...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_005 [Shiho]]
[s][vp 9 2 65535 40004 0 0]There was a victim[n]at my school too...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_006 [Shiho]]
[s][vp 9 2 65535 41352 0 0]Let's go home already![n]It's dangerous out here...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_05_ [Shiho]]
[s][vp 9 2 65535 38752 0 0]They're supposed to[n]be a pretty dangerous[n]group of criminals...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_06_ [Shiho]]
[s][vp 9 2 65535 38902 0 0]I've heard they actually[n]force you into prostitution...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_007 [Shiho]]
[s][vp 9 2 65535 38902 0 0]So the police aren't[n]doing anything about[n]it? What the heck![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_07_ [Shiho]]
[s][vp 9 2 65535 42655 0 0]They're supposed to[n]be a pretty dangerous[n]group of criminals...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_08_ [Shiho]]
[s][vp 9 2 65535 39652 0 0]I've heard they actually[n]force you into prostitution...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_009 [Shiho]]
[s][vp 9 2 65535 41902 0 0]Can we avoid going to[n]Central Street? Sounds[n]scary over there.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_01_ [Shiho]]
[s][vp 9 2 65535 46255 0 0]I haven't seen[n]fireworks in years...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_02_ [Shiho]]
[s][vp 9 2 65535 41455 0 0]It's already the season[n]for fireworks, huh?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_03_ [Shiho]]
[s][vp 9 2 65535 41504 0 0]I haven't seen[n]fireworks in years...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_04_ [Shiho]]
[s][vp 9 2 65535 38254 0 0]Wanna head to the[n]fireworks festival soon?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_104_05_ [Shiho]]
[s][vp 9 2 65535 41300 0 0]I ended up wearing the[n]yukata! What do you[n]think of this pattern?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_104_06_ [Shiho]]
[s][vp 9 2 65535 41202 0 0]The fireworks festival[n]is great, but I just can't[n]deal with this crowd...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_104_07_ [Shiho]]
[s][vp 9 2 65535 41453 0 0]There's tons of girls in yukatas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_104_08_ [Shiho]]
[s][vp 9 2 65535 41350 0 0]Yukatas are so stunning...[n]Gotta love 'em![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_01_ [Shiho]]
[s][vp 9 2 65535 43051 0 0]They really went too far...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_02_ [Shiho]]
[s][vp 9 2 65535 39252 0 0]What they did to Mr. Okumura[n]was just too much. How could[n]they resort to such cruelty?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_03_ [Shiho]]
[s][vp 9 2 65535 42252 0 0]They really went too far...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_04_ [Shiho]]
[s][vp 9 2 65535 38351 0 0]Killing him is going way too far![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_05_ [Shiho]]
[s][vp 9 2 65535 40352 0 0]They really went too far...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_06_ [Shiho]]
[s][vp 9 2 65535 39652 0 0]Did you see President[n]Okumura's press conference?[n]They didn't need to go that far...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_07_ [Shiho]]
[s][vp 9 2 65535 38502 0 0]They really went too far...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_08_ [Shiho]]
[s][vp 9 2 65535 41252 0 0]What they did to Mr. Okumura[n]was just too much. How could[n]they resort to such cruelty?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_01_ [Shiho]]
[s][vp 9 2 65535 37903 0 0]Even though he's still just[n]a student, that detective[n]is pretty amazing.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_02_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_03_ [Shiho]]
[s][vp 9 2 65535 41054 0 0]Akechi-kun's still in[n]high school, right?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_04_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_05_ [Shiho]]
[s][vp 9 2 65535 41204 0 0]Akechi-kun is the greatest[n]detective of our generation![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_06_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_07_ [Shiho]]
[s][vp 9 2 65535 39104 0 0]Have you heard of that[n]detective, Akechi?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_08_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_01_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_02_ [Shiho]]
[s][vp 9 2 65535 41005 0 0]If I had to choose,[n]I'm not really sure...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_03_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_04_ [Shiho]]
[s][vp 9 2 65535 41105 0 0]It's a little hard for[n]me to understand...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_05_ [Shiho]]
[s][vp 9 2 65535 38704 0 0]Yeah, manipulating someone's[n]heart isn't normal...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_06_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_07_ [Shiho]]
[s][vp 9 2 65535 41352 0 0]Manipulate the heart, huh...[n]Is that even possible?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_08_ [Shiho]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_655_01_ [Shiho]]
[s][vp 9 2 65535 41352 0 0]Why are we guys 'sposed to[n]give something three times[n]better than what we got?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_655_02_ [Shiho]]
[s][vp 9 2 65535 39351 0 0]Where are you going[n]to take us today? [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_655_03_ [Shiho]]
[s][vp 9 2 65535 42252 0 0]I wonder what to get[n]her to reciprocate for Valentines...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_655_04_ [Shiho]]
[s][vp 9 2 65535 45253 0 0]I've gotta post this online![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_01_ [Shiho]]
[s][vp 9 2 65535 37552 0 0]I don't want to work...[n]I wanna stay home...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_02_ [Shiho]]
[s][vp 9 2 65535 38052 0 0]People have no[n]drive nowadays...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_03_ [Shiho]]
[s][vp 9 2 65535 37603 0 0]That person on TV showed a[n]lot of promise for someone[n]so young.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_04_ [Shiho]]
[s][vp 9 2 65535 41152 0 0]It must be tough getting[n]recommendations[n]through sports...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_05_ [Shiho]]
[s][vp 9 2 65535 40302 0 0]It would suck to die in[n]one of those accidents...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_06_ [Shiho]]
[s][vp 9 2 65535 40952 0 0]No place is safe...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_07_ [Shiho]]
[s][vp 9 2 65535 41352 0 0]Man, I don't have the[n]energy I used to... I[n]guess I'm getting old...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_08_ [Shiho]]
[s][vp 9 2 65535 41652 0 0]I have to attend another[n]match this weekend! I'm[n]so ready to quit...[n][f 1 2 180][e]

[msg quest11_hint_talk_00 [Angry Young Man]]
[s]Goddamn him! I'll have him arrested[n]for this![n][w][e]

[msg quest11_hint_talk_01 [Teary-Eyed Woman]]
[s]No, Sho-chan... It's all my fault.[n][w][e]

[msg quest11_hint_talk_02 [Angry Young Man]]
[s]Are you kidding? You didn't do anything[n]wrong, Mom![n][w][e]
[s]That goddamn drunk excuse for a father.[n]The same one who got fired and just sits[n]around drinking all day![n][w][e]
[s]All you try to do is help, and what's he do[n]in return? Hits you and bails![n][w][e]
[s]We can't keep living like this! At some[n]point you just have to give up on him...[n][w][e]

[msg quest11_hint_talk_03 [Teary-Eyed Woman]]
[s]You have to understand, deep down he's—[n][w][e]

[msg quest11_hint_talk_04 [Angry Young Man]]
[s]Never gonna change! You'll just get[n]knocked around more and more if you[n]keep waiting around for it to happen![n][w][e]
[s]I bet he's at a Central Street bar. I'm gonna[n]find that asshole and see how he likes[n]getting punched![n][w][e]

[msg quest11_hint_sinjyo]
[s]What a lousy father...[n][w][e]

[msg MSG_quest11_morgana_00 [Morgana]]
[s]I don't know who he is, but we can't let[n]someone like that go unpunished.[n][w][e]
[s]Let's try to find this drunk.[n][w][e]

[msg Quest17_target_00_00 [Hitoe Takeishi]]
[s]Keisuke, what're we gonna do? We can't[n]have this baby—we're broke.[n][w][e]
[s]I don't want money from my parents. Our[n]only option is to give it up for adoption.[n][w][e]

[msg Quest17_target_00_01 [Keisuke]]
[s]I'm sorry, this is all my fault. If I had my[n]shit together, you wouldn't be in such a[n]tough spot.[n][w][e]
[s]I'm so sorry for being so pathetic...[n][w][e]

[msg Quest17_target_00_02 [Hitoe Takeishi]]
[s]What should we do? We don't have jobs,[n]and I don't want to be a parent. I just want[n]to party.[n][w][e]
[s]If we're giving it up, we need to find the[n]cheapest solution.[n][w][e]

[msg Quest17_target_00_03 [Keisuke]]
[s]I'm so, so sorry![n][w][e]
[s]I won't make you go through something[n]like this ever again.[n][w][e]

[msg Quest17_target_00_04 [Hitoe Takeishi]]
[s]I know. It's just... Ugh, this is so annoying.[n][w][e]

[msg Quest17_target_sinjyo_00]
[s]How irresponsible...[n][w][e]

[msg MSG_quest17_morgana_00 [Morgana]]
[s]I won't let them throw a life away! We'll[n]settle this at the hideout.[n][w][e]

[msg Quest17_target_01_00 [Hitoe Takeishi]]
[s]Hey, there was something weird in my[n]bag. Though, I'm sure it's just a prank.[n][w][e]

[msg Quest17_target_01_01 [Keisuke]]
[s]Be careful, okay? We don't want anything[n]jeopardizing your body right now...[n][w][e]

[msg Quest17_target_01_02 [Hitoe Takeishi]]
[s]The government is going to give me[n]money if I have this kid, right? Maybe[n]I should cash in...[n][w][e]

[msg Quest17_target_01_03 [Keisuke]]
[s]You can't apply for that money, idiot.[n]If our parents find out, we won't be able[n]to get rid of it...[n][w][e]

[msg Quest17_target_01_04 [Hitoe Takeishi]]
[s]What, really!? If we're going to help with[n]the declining birth rate, I better get my[n]money's worth.[n][w][e]

[msg Quest17_target_sinjyo_01]
[s]The calling card has been sent...[n]Let's settle this...[n][w][e]

[msg Quest17_target_02_00 [Hitoe Takeishi]]
[s]I gave it some thought, and I'm going to[n]raise this child. I want to be a responsible[n]parent.[n][w][e]

[msg Quest17_target_02_01 [Keisuke]]
[s]H-Hey, what's this all of a sudden? We[n]can't afford a baby. I thought we were[n]going to adopt it out...[n][w][e]

[msg Quest17_target_02_02 [Hitoe Takeishi]]
[s]But this baby did nothing wrong. I can't[n]do that because we're being selfish.[n][w][e]
[s]We'll make the money, somehow. It'll be[n]hard, but we can ask our parents for help...[n][w][e]

[msg Quest17_target_02_03 [Keisuke]]
[s]......[n][w][e]
[s]You've got to be kidding me. If you do[n]that, you'll create a lot of trouble for me.[n][w][e]
[s]Dammit... I was gonna cut contact with[n]you. How could you get pregnant?[n][w][e]

[msg Quest17_target_02_04 [Hitoe Takeishi]]
[s]Wh-What are you saying!?[n][w][e]
[s]Are you cheating on me...?[n][w][e]

[msg Quest17_target_02_05 [Keisuke]]
[s]Cheating? You were the one I was[n]cheating with! Idiot. Did you really take[n]this seriously?[n][w][e]
[s]I have no intent in getting married, and[n]I won't acknowledge that the kid's mine.[n][w][e]

[msg Quest17_target_02_06 [Keisuke]]
[s]No... So you were tricking me this whole[n]time!? You bastard![n][w][e]
[s]I was an idiot, but you're a scumbag...[n]I won't let you run away from this by[n]yourself![n][w][e]

[msg Quest17_target_sinjyo_02]
[s]Man... he's an awful person too...[n][w][e]

[msg MSG_quest17_morgana_01 [Morgana]]
[s]I guess we'll beat him down, too! Let's[n]discuss it at the hideout![n][w][e]

[msg Quest18_target_00_00 [Keisuke]]
[s]You bitch! Putting a weird letter in my bag![n][w][e]

[msg Quest18_target_00_01 [Hitoe Takeishi]]
[s]What? I did no such thing! Besides, isn't[n]that a calling card!?[n][w][e]
[s]I was able to change because of the calling[n]card... I hope the Phantom Thieves kick[n]your ass too![n][w][e]

[msg Quest18_target_sinjyo_00]
[s]It seems the calling card has reached its[n]destination...[n][w][e]

[msg Quest18_target_01_00 [Keisuke]]
[s]I'm sorry, Hitoe...[n][w][e]
[s]I don't know if you can forgive me after[n]all that, but I want to take whatever[n]responsibility I can.[n][w][e]

[msg Quest18_target_01_01 [Hitoe Takeishi]]
[s]It's fine. I can't really fault you anyway.[n][w][e]
[s]This child is both of our responsibilities,[n]yet we were only thinking of ourselves.[n]We're awful.[n][w][e]

[msg Quest18_target_01_02 [Keisuke]]
[s]I don't know what I can do... But from now[n]on, I'll have a change of heart and work...![n][w][e]

[msg Quest18_target_01_03 [Hitoe Takeishi]]
[s]About that... I thought about it a lot, and[n]I decided to raise this baby on my own.[n][w][e]
[s]I talked to my parents already. I'm ready[n]to be a single mother.[n][w][e]

[msg Quest18_target_01_04 [Keisuke]]
[s]H-Hey, wait. Why are you saying this!?[n][w][e]

[msg Quest18_target_01_05 [Hitoe Takeishi]]
[s]On my end, I was in a serious relationship[n]with you. But you... you were just fooling[n]around with me.[n][w][e]
[s]It's enough that you felt some[n]responsibility. I won't ask you for[n]anything more. Goodbye.[n][w][e]

[msg Quest18_target_01_06 [Keisuke]]
[s]I was such an idiot... I'm sorry. I'm so[n]sorry...[n][w][e]

[msg Quest18_target_sinjyo_01]
[s]Now it's up to them...[n][w][e]

[msg Quest37_target_00_00 [ターゲット37]]
[s]クエスト37のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗は受注可能状態です。[n][w][e]

[msg Quest37_target_sinjyo_00]
[s]クエスト37のテスト心情メッセージです。[n][w][e]

[msg MSG_quest37_morgana_00 [Morgana]]
[s]クエスト37のモルガナメッセージです。[n]ターゲット用です。[n][w][e]

[msg Quest37_target_01_00 [ターゲット37]]
[s]クエスト37のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗はメメントス突入可能状態です。[n][w][e]

[msg Quest37_target_sinjyo_01]
[s]クエスト37のテスト心情メッセージです。[n][w][e]

[msg Quest37_target_02_00 [ターゲット37]]
[s]クエスト37のテストメッセージです。[n]表示後、キャンプでの状態を確認して下さい。[n][w][e]
[s]Quest progression:[n]Mission cleared. Please check that[n]the next quest can be accepted.[n][w][e]

[msg Quest37_target_sinjyo_02]
[s]クエスト37のテスト心情メッセージです。[n][w][e]

[msg MSG_quest37_morgana_01 [Morgana]]
[s]クエスト37のモルガナメッセージです。[n]37から38への繋ぎメッセージとなります。[n][w][e]

[msg Quest38_target_00_00 [ターゲット38]]
[s]クエスト38のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]Quest progression:[n]You can enter Mementos.[n][w][e]

[msg Quest38_target_sinjyo_00]
[s]クエスト38のテスト心情メッセージです。[n][w][e]

[msg Quest38_target_01_00 [ターゲット38]]
[s]クエスト38のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗はミッションクリア状態です。[n][w][e]

[msg Quest38_target_sinjyo_01]
[s]クエスト38のテスト心情メッセージです。[n][w][e]

[msg quest44_hint_talk_00 [ヒント44]]
[s]クエスト44のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest44_hint_sinjyo]
[s]クエスト44のテスト心情メッセージです。[n][w][e]

[msg MSG_quest44_morgana_00 [Morgana]]
[s]クエスト44のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

[msg quest46_hint_talk_00 [ヒント46]]
[s]クエスト46のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest46_hint_sinjyo]
[s]クエスト46のテスト心情メッセージです。[n][w][e]

[msg MSG_quest46_morgana_00 [Morgana]]
[s]クエスト46のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

