[msg CMM_EVENT_OPEN]
[s][vp 1 0 0 0 0 0]You've unlocked the[n]Councillor Confidant![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Fusing Personas of the Councillor[n]arcana will now grant you EXP[n]due to Arcana Burst![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_2]
[s][vp 1 0 0 0 0 0]Your Councillor Confidant has[n]increased to [clr 2]Rank 2[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]You will now earn more EXP from[n]Arcana Burst when fusing Personas[n]of the Councillor arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Maruki taught you [clr 1]Detox X[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_3]
[s][vp 1 0 0 0 0 0]Your Councillor Confidant has[n]increased to [clr 2]Rank 3[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]You will now earn more EXP from[n]Arcana Burst when fusing Personas[n]of the Councillor arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Maruki taught you how to achieve [clr 1]Flow[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_4]
[s][vp 1 0 0 0 0 0]Your Councillor Confidant has[n]increased to [clr 2]Rank 4[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]You will now earn more EXP from[n]Arcana Burst when fusing Personas[n]of the Councillor arcana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_5]
[s][vp 1 0 0 0 0 0]Your Councillor Confidant has[n]increased to [clr 2]Rank 5[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]You will now earn more EXP from[n]Arcana Burst when fusing Personas[n]of the Councillor arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Maruki taught you how to[n]practice [clr 1]Mindfulness[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_6]
[s][vp 1 0 0 0 0 0]Your Councillor Confidant has[n]increased to [clr 2]Rank 6[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]You will now earn more EXP from[n]Arcana Burst when fusing Personas[n]of the Councillor arcana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_7]
[s][vp 1 0 0 0 0 0]Your Councillor Confidant has[n]increased to [clr 2]Rank 7[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]You will now earn more EXP from[n]Arcana Burst when fusing Personas[n]of the Councillor arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Maruki taught you [clr 1]Flow Boost[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_8]
[s][vp 1 0 0 0 0 0]Your Councillor Confidant has[n]increased to [clr 2]Rank 8[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]You will now earn more EXP from[n]Arcana Burst when fusing Personas[n]of the Councillor arcana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_9]
[s][vp 1 0 0 0 0 0]Your Councillor Confidant has[n]increased to [clr 2]Rank 9[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]You will now earn more EXP from[n]Arcana Burst when fusing Personas[n]of the Councillor arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Maruki taught you [clr 1]Detox DX[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKMAX]
[s][vp 1 0 0 0 0 0]Your Councillor Confidant has[n]increased to [clr 2]MAX Rank[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]You will now earn more EXP from[n]Arcana Burst when fusing Personas[n]of the Councillor arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Maruki taught you how to[n]practice [clr 1]Wakefulness[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_UNLOCK]
[s][vp 1 0 0 0 0 0]You can now fuse [clr 1]Vohu Manah[clr 27],[n]the most powerful Persona[n]of the Councillor arcana.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_REVERSE]
[s][vp 1 0 0 0 0 0]If you see this, it's a bug![n]Your Councillor Confidant is in a state[n]of Doubt. You will not receive its[n]benefits until you clear your name.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_UPRIGHT]
[s][vp 1 0 0 0 0 0]You have lifted the state of Doubt[n]on your Councillor Confidant.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_BROKEN]
[s][vp 1 0 0 0 0 0]If you see this, it's a bug![n]Your Councillor Confidant is now broken.[n]The deal is off, and you will not[n]receive its benefits in this state.[n][f 1 3 65535][w][e]

