[msg mini_ev_mes_02_01_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]Caramba, mas é enorme![n]Um jogo custa... 5.000?!?[n][w][e]

[msg mini_ev_mes_02_01_mes02 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espere, cerejas ganham[n]5.000 moedas, BARs ganham 10.000,[n]enquanto um 777 [clr 2]50.000[clr 27]?!?[n][w][e]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uau! Aqui podemos ganhar todas as moedas que[n]precisamos de uma só vez![n][w][e]

[msg mini_ev_mes_02_01_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Supondo que você possa vencer.[n]Com uma recompensa semelhante, os[n]riscos serão igualmente altos.[n][w][e]

[msg mini_ev_mes_02_01_mes04 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8155 65535 0]No entanto, nosso objetivo é[n]obter o cartão de membro para[n]o plano de apostas altas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Gostaríamos de poder[n]usar esta[n]caça-níqueis de alguma forma. No entanto...[n][w][e]

[msg mini_ev_mes_02_01_mes05 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Deixe-me adivinhar, "primeiro temos que[n]impedi-lo de trapacear"?[n]Isso também é manipulado, com certeza.[n][w][e]

[msg mini_ev_mes_02_01_mes06 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Haha, que bom que você entendeu.[n]Então, vamos explorar a área.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esperamos encontrar algo[n]para aprender mais[n]sobre este slot.[n][w][e]

[msg mini_ev_mes_02_01_mes07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Provavelmente há[n]um terminal de informações lá atrás.[n]Tente pesquisar, Joker.[n][w][e]

[msg mini_ev_mes_02_01_mes08 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu entendo como você se sente, mas[n]por enquanto precisamos neutralizar[n]o sistema que comanda as jogadas.[n][w][e]

[msg mini_ev_mes_02_01_mes09 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu acredito que[n]existe um terminal de informações lá atrás.[n]Tente pesquisar, Joker.[n][w][e]

