[msg D05_01_e328_025_mes01 [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9040 65535 0]Segure um segundo, Joker![n][w][e]

[msg D05_01_e328_025_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A porta fechou. Existe alguma maneira pela[n]qual possamos abri-lo?[n][w][e]

[msg D05_01_e328_025_mes03 [System Voice]]
[s]Realizando autenticação biométrica.[n][w][e]

[msg D05_01_e328_025_mes04 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]O que isso significa com isso?[n][w][e]

[msg D05_01_e328_025_mes05 [System Voice]]
[s]Erro de autorização.[n][w][e]
[s]Somente pessoal registrado pode prosseguir[n]com esse ponto.[n][w][e]

[msg D05_01_e328_025_mes06 [Futaba]]
[s][bup 0 8 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9159 65535 0]Este sistema de segurança pode ser um[n]problema...[n][w][e]

