[msg e259_141_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6021 65535 0]Parece que até aqui tem[n]andares inferiores...[n][w][e]

[msg e259_141_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hum, mas o elevador não tem um painel de controle.[n][w][e]

[msg e259_141_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1021 65535 0]Eles irão monitorá-lo de uma sala de segurança.[n]É um método de proteção simples, mas eficaz.[n][w][e]

[msg e259_141_mes04 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Evidentemente, eles querem ter certeza[n]de que ninguém desce lá...[n][w][e]

[msg e259_141_mes05 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2164 65535 0]Uhm, se for controlado[n]remotamente, não poderemos[n]usá-lo...[n][w][e]

