[msg D153_003_LOCK_EV01_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6184 65535 0]Huh...? É isto...[n][w][e]

[msg D153_003_LOCK_EV01_mes02 [???]]
[s]Intrudadores na segunda sala de exposições![n]Aprendê-los de uma só vez![n][w][e]

[msg D153_003_LOCK_EV01_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]Merda, vamos sair daqui, rápido![n]Qual é a saída!?[n][w][e]

