[msg D157_006_miniEV_02_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Aqui está a explicação das[n]regras do jogo de dados.[n][w][e]

[msg D157_006_miniEV_02_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"Aproveite este jogo simples[n]onde você pode adivinhar o total[n]que vai sair quando você jogar três dados."[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"Com um palpite correto, você[n]dobra sua aposta, enquanto com[n]três dados idênticos, você a triplica".[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"Com três 6s, a aposta inicial[n]é multiplicada por cinco."[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"Exceto em casos especiais, o jogo é inserido[n]com 25 moedas de cassino".[n][w][e]

[msg D157_006_miniEV_02_mes03 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]O que diabos são[n]"casos especiais"?!?[n][w][e]

[msg D157_006_miniEV_02_mes04 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Como nós sabemos disso?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No entanto, mesmo que vencêssemos[n]todas as vezes, teríamos que jogar 1.960[n]jogos diferentes deste jogo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]50.000 é um número enorme...[n][w][e]

[msg D157_006_miniEV_02_mes05 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8020 65535 0]Dito isso, é apenas um meio de ganhar moedas.[n]Isso nos ajudará a nos adaptar ao jogo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu sugiro que você tente, Joker.[n][w][e]

