[msg D07_BRIEFING_180_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Nós garantimos nossa rota para o tesouro![n]Tudo o que precisamos fazer agora é enviar o[n]cartão de visita![n][w][e]

[msg D07_BRIEFING_180_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Então, finalmente concluímos a primeira[n]etapa... isso não significa que podemos[n]estar à vontade...[n][w][e]

[msg D07_BRIEFING_180_mes03 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Heh, não há muito fora agora. Vamos dar uma[n]corrida para esse dinheiro para o seu[n]dinheiro![n][w][e]

