[msg D06_BOSS_CHASE_EV_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Existe uma maneira de subir ainda mais alto?[n][w][e]

[msg D06_BOSS_CHASE_EV_mes04 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Há um elevador no próximo andar.[n]Para as escadas, rapidamente.[n][w][e]

[msg D06_BOSS_CHASE_EV_mes05 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você é sempre confiável.[n]Vamos nos apressar![n][w][e]

