[msg MSG_COFFEE_NG_mes01]
[s]Um monte de [clr 2]ferramentas de fabricação de café com[n]aparência profissional [n][clr 27]foram colocados aqui no balcão...[n][w][e]
[s]Eu me pergunto se o café realmente teria um[n]sabor diferente se eu usasse isso para[n]fazer alguns...[n][w][e]

[msg MSG_COFFEE_NG_0410_mes01]
[s]Eu deveria atender o telefone primeiro.[n][w][e]

[msg MSG_COFFEE_NG_0410_mes02]
[s]Prefiro comer um pouco de comida do que[n]tomar café agora. Vamos olhar para dentro[n]do  [clr 2]frigorífico [clr 27]...[n][w][e]

