[msg D10_BRIEFING_080_mes01 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9176 65535 0]Esse vídeo... estou sem palavras...[n][w][e]

[msg D10_BRIEFING_080_mes02 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sua namorada perdeu todas as suas[n]memórias e... aquele poder nele[n]... despertou?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu... nem sei por onde começar com essas coisas.[n][w][e]

[msg D10_BRIEFING_080_mes03 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Bem, nós temos as informações que[n]precisamos para a porta de segurança.[n]Vamos lá.[n][w][e]

