[msg D07_BRIEFING_060_mes01 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7175 65535 0]Merda, eu não dou a mínima[n]se isso foi um nobre.[n]Ele está fodendo com a gente![n][w][e]

[msg D07_BRIEFING_060_mes02 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não parecia que ele ia nos ouvir.[n][w][e]

[msg D07_BRIEFING_060_mes03 [Haru]]
[s][bup 0 7 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas temos que fazer alguma coisa,[n]não? Venha, vamos![n][w][e]

