[msg D01_BRIEFING_030_mes01 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6058 65535 0]Uh, crânio... o que você está sorrindo por[n]lá?[n][w][e]

[msg D01_BRIEFING_030_mes02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, desculpe, sobre isso. Eu estava pensando[n]em como atravessávamos esses lustres mais[n]cedo.[n][w][e]

[msg D01_BRIEFING_030_mes03 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7024 65535 0]Quero dizer, tudo isso não faz você sentir[n]que somos ladrões de verdade?[n][w][e]

[msg D01_BRIEFING_030_mes04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6022 65535 0]* suspiro* Você sabe que ainda temos um[n]longo caminho a percorrer, certo?[n][w][e]

[msg D01_BRIEFING_030_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ela tem um ponto. Mesmo olhando para isso[n]otimista, ainda há muitos pela frente.[n][w][e]

[msg D01_BRIEFING_030_mes06 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu sei, eu sei... não se preocupe, eu vou[n]continuar dando essa merda tudo o que tenho![n][w][e]

