[msg D07_02_e409_011_mes01 [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Oh. Espere um minuto.[n][w][e]

[msg D07_02_e409_011_mes02 [Ryuji]]
[s][vp 1 0 0 2 0 0]Espere, que porra é essa?[n]S-Nós nos tornamos... ratos?[n][w][e]

[msg D07_02_e409_011_mes03 [Yusuke]]
[s][vp 1 0 0 3 0 0]Estou com muita raiva![n]Ou algo assim...[n][w][e]

[msg D07_02_e409_011_mes04 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]Ugh, pare com isso, Inari.[n]Você poderia voltar aqui?[n][w][e]

[msg D07_02_e409_011_mes05 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Que alívio, somos humanos de novo![n][w][e]

[msg D07_02_e409_011_mes06 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]Aparentemente, voltamos ao que éramos[n]quando saímos da área de efeito.[n]Não é grande coisa.[n][w][e]

[msg D07_02_e409_011_mes07 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 7 0 0]Em vez disso, é um grande problema![n]Conte-nos o que aconteceu conosco![n][w][e]

[msg D07_02_e409_011_mes08 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 8 0 0]Parece que as pessoas que Shido[n]considera "intrusos" se transformam[n]em ratos perto de suas estátuas.[n][w][e]

[msg D07_02_e409_011_mes09 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 9 0 0]Então, para ele, somos apenas[n]roedores, hein? Irritante.[n][w][e]

[msg D07_02_e409_011_mes10 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 10 0 0]Concordo, mas temos que[n]ter muito mais cuidado[n]quando somos ratos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 11 0 0]Não poderemos abrir portas e, se[n]tentarmos lutar, qualquer[n]inimigo nos separará.[n][w][e]

[msg D07_02_e409_011_mes11 [Makoto]]
[s][bup 0 6 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 12 0 0]Então, podemos apenas nos esconder?[n]Teremos que ficar totalmente[n]defensivos...[n][w][e]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 13 0 0]Esperamos encontrar uma[n]passagem secreta pela área...[n][w][e]

[msg D07_02_e409_012_mes01 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6119 65535 0]Hã? Um beco sem saída? Haveria outra maneira...?[n][w][e]

[msg D07_02_e409_012_mes02 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Isso não está certo... Temos que encontrar[n]a [clr 2]passagem secreta[clr 27][n]em algum lugar.[n][w][e]

[msg D07_02_e409_013_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Mmm, algo se moveu... Para que serve esse botão?[n][w][e]

[msg D07_02_e409_013_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]É impossível dizer daqui.[n]Vamos dar uma olhada.[n][w][e]

[msg D07_02_e409_014_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7174 65535 0]Uuuh, sou eu ou parece que algo mudou?[n][w][e]

[msg D07_02_e409_014_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bem, nós não viramos mais ratos quando[n]chegamos perto daquela estátua...[n][w][e]

[msg D07_02_e409_014_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que aquela estátua está[n]conectada ao botão que[n]pressionamos anteriormente.[n][w][e]

[msg D07_02_e409_014_mes04 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Interessante. Não poderemos mais usar[n]a passagem secreta, mas podemos[n]prosseguir com mais facilidade.[n][w][e]

[msg D07_02_e409_014_AF_mes01 [Futaba]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9021 65535 0]Parece que pressionar aquele botão[n]desativou o poder das[n]estátuas de nos transformar em ratos.[n][w][e]

[msg D07_02_e411_010_mes01 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6194 65535 0]Huh? Há uma estátua aqui, mas não nos[n]transformamos em ratos.[n][w][e]

[msg D07_02_e411_010_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que já está desativado.[n][w][e]

[msg D07_02_e411_010_mes03 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]FIGO. Então passar por aqui[n]deve ser bastante fácil.[n][w][e]

[msg D07_02_e411_010_AF_mes01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9155 65535 0]Quando ativa, esta estátua[n]nos transforma em ratos[n]quando nos aproximamos dela.[n][w][e]

