[msg dummy_mes]
[s]......[n][w][e]

[msg D10_03_start_mes01 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]É enorme...[n][w][e]
[s]Mas acho que ficaremos bem[n]se continuarmos em frente.[n]Vamos nos apressar![n][w][e]

[msg D10_03_start_mes02 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este lugar não é tão seguro quanto[n]nossa realidade. Fique atento.[n][w][e]

[msg D10_10_Door_Lock_Clear_S [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57161 65535 0]Que abriu! Você conseguiu,[n]Oracle-senpai![n][w][e]

[msg D10_10_Door_Lock_Clear_E [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9076 65535 0]Oracle-senpai... Mueheheh,[n]eu gosto do jeito que soa![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]De agora em diante, estaremos[n]em um lugar desconhecido.[n]Fiquem atentos, pessoal![n][w][e]

[msg D10_10_ID_Get_Start [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nós temos o cartão![n]Agora é só...[n][w][e]

[msg D10_10_ID_Get_End [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que estamos nos aproximando do Tesouro.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Podemos tentar o[n]ID naquela porta agora.[n][w][e]

[msg D10_cardLeader_suggestio [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9199 65535 0]Então as Sombras estavam se comportando de[n]maneiras incomuns por causa da emboscada...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bem, passamos por momentos difíceis, mas[n]temos uma missão a cumprir![n]Vamos dar uma olhada naquela porta.[n][w][e]

[msg D10_cardLeader_suggestio_2 [[f 4 31 10 0]]]
[s][bup 0 10 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, sim, você está certo...[n]Eu esqueci completamente disso.[n][w][e]

