[msg D08_01_e437_101_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]O que diabos é esse lugar...?[n][w][e]

[msg D08_01_e437_101_mes02 [Ann]]
[s][bup 0 4 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]É tão assustador...[n][w][e]

[msg D08_01_e437_101_mes03 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Então, aqueles tubos estranhos que o túnel[n]através de lembranças eram originários[n]daqui, afinal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sabe, eu tenho pensado isso há algum[n]tempo... eles me lembram um pouco de veias.[n][w][e]

[msg D08_01_e437_101_mes04 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6198 65535 0]Mais importante, o que há com esse cenário?[n]Que tipo de distorção é essa?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quero dizer, o que todo mundo pensa que este[n]mundo é...!?[n][w][e]

[msg D08_01_e437_101_mes05 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Acalme-se, Lady Ann. O tesouro está[n]definitivamente aqui, e é isso que é[n]importante agora.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E eu posso sentir outra coisa.[n]Uma presença tremenda que vem de muito mais[n]profunda...[n][w][e]

[msg D08_01_e437_101_mes06 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2193 65535 0]Não sei se quero descobrir o que isso pode[n]ser, mas devemos endurecer nossas[n]resoluções.[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]É hora de ir para as profundezas![n][w][e]

