[msg D07_01_e407_201_A_mes01 [Male Guest]]
[s]... Oh, você tem a elegância e o refinamento[n]tão ausentes na cidadania comum![n][w][e]

[msg D07_01_e407_201_A_mes02 [Female Guest]]
[s]Meu, tal lisonja! Uma aura de alta classe[n]emana de você também![n][w][e]

[msg D07_01_e407_201_A_mes03 [Male Guest]]
[s]Então você notou! Hahahaha![n][w][e]

[msg D07_01_e407_201_A_mes04 [Female Guest]]
[s]Certamente! Ahahaha![n][w][e]

[msg D07_01_e407_201_A_mes05 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7085 65535 0]Ei, esses caras me ignoram totalmente quando[n]eu tento falar com eles...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu pareço muito com eu não tenho dinheiro? É[n]'causa da máscara do crânio ou algo assim?[n][w][e]

[msg D07_01_e407_201_B_mes01 [Female Guest]]
[s]HM...? Um dos VIPs costumavam pertencer à[n]nobreza?[n][w][e]

[msg D07_01_e407_201_B_mes02 [Male Guest]]
[s]Sim, deve ser por isso que ele pode entrar[n]no lugar sagrado. Ouvi dizer que ele também[n]não é visto facilmente...[n][w][e]

[msg D07_01_e407_201_B_mes03 [Female Guest]]
[s]Mas por que alguém de sua estatura sempre[n]estaria à beira da piscina?[n][w][e]

[msg D07_01_e407_201_B_mes04 [Male Guest]]
[s]Bem, ele deve gostar lá por algum motivo...[n]mas não acho que seja a natação. Hahahaha![n][w][e]

[msg D07_01_e407_201_B_mes05 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Além dessa porta está a "área VIP" e o[n]principal salão de montagem é um "lugar[n]sagrado".[n][w][e]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que não podemos entrar, a menos que[n]Shido nos aceite.[n][w][e]

[msg D07_01_e407_201_C_mes01 [Male Guest]]
[s]HM... Então esse é o presidente de uma[n]estação de TV?[n][w][e]

[msg D07_01_e407_201_C_mes02 [Female Guest]]
[s]De fato. O Sr. Shido tem um grande círculo[n]de conhecidos.[n][w][e]

[msg D07_01_e407_201_C_mes03 [Male Guest]]
[s]Parece que você tem que ser pelo menos tão[n]importante para ser considerado um VIP...[n][w][e]
[s]Estou realmente com inveja...[n][w][e]

[msg D07_01_e407_201_C_mes04 [Female Guest]]
[s]Por que você não vai jogar os slots com ele?[n]Isso pode chamar sua atenção...[n][w][e]

[msg D07_01_e407_201_C_mes05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Parece que todas essas pessoas querem ser[n]aceitas como um dos clientes especiais da[n]Shido.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A propósito, ganhei algumas informações[n]sobre os VIPs. Devemos discutir mais tarde.[n][w][e]

[msg D07_01_e407_201_D_mes01 [Female Guest]]
[s]Meu... até o Sr. Ooe é um VIP?[n][w][e]

[msg D07_01_e407_201_D_mes02 [Male Guest]]
[s]Acabei de ver ele no restaurante... pensar[n]que um político importante como ele foi[n]convidado aqui...[n][w][e]
[s]Bem, o apoio do mundo político deve[n]significar que os desligamentos mentais são[n]tão viáveis como sempre![n][w][e]

[msg D07_01_e407_201_D_mes03 [Female Guest]]
[s]Ahaha, estou com muita inveja... eu me[n]pergunto se há uma maneira de conhecê-lo[n]melhor...[n][w][e]

[msg D07_01_e407_201_D_mes04 [Male Guest]]
[s]Hahaha, se desejar...[n][w][e]

[msg D07_01_e407_201_D_mes05 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Ouvir as pessoas falarem tão casualmente[n]sobre o negócio de desligamento mental faz[n]minha cabeça girar...[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]... Mas parece que precisamos de[n]certificação de cinco VIPs para nos[n]tornarmos um "cliente especial".[n][w][e]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Essas pessoas estão dispostas a compartilhar[n]qualquer coisa. Talvez seja porque os[n]rostos deles estão escondidos?[n][w][e]

[msg D07_01_e407_201_E_mes03 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]Hum, não tenho muita certeza de como falar[n]com as pessoas aqui...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu permaneci em silêncio ou falei em[n]gentilezas simples durante as relações[n]comerciais do pai...[n][w][e]

[msg D07_01_e407_201_F_mes01 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9027 65535 0]Você é um pouco sadista por me fazer obter[n]informações de estranhos completos, Joker![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas eu vou fazer isso! Vou vingar minha mãe.[n][w][e]

[msg D07_01_e407_201_A_AF_mes [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7085 65535 0]Ei, esses caras me ignoram totalmente quando[n]eu tento falar com eles...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu pareço muito com eu não tenho dinheiro? É[n]'causa da máscara do crânio ou algo assim?[n][w][e]

[msg D07_01_e407_201_B_AF_mes [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Além dessa porta está a "área VIP" e o[n]principal salão de montagem é um "lugar[n]sagrado".[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que não podemos entrar, a menos que[n]Shido nos aceite.[n][w][e]

[msg D07_01_e407_201_C_AF_mes [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Parece que todas essas pessoas querem ser[n]aceitas como um dos clientes especiais da[n]Shido.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A propósito, ganhei algumas informações[n]sobre os VIPs. Devemos discutir mais tarde.[n][w][e]

[msg D07_01_e407_201_D_AF_mes [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Ouvir as pessoas falarem tão casualmente[n]sobre o negócio de desligamento mental faz[n]minha cabeça girar...[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]... Mas parece que precisamos de[n]certificação de cinco VIPs para nos[n]tornarmos um "cliente especial".[n][w][e]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Essas pessoas estão dispostas a compartilhar[n]qualquer coisa. Talvez seja porque os[n]rostos deles estão escondidos?[n][w][e]

[msg D07_01_e407_201_E_AF_mes [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]Hum, não tenho muita certeza de como falar[n]com as pessoas aqui...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu permaneci em silêncio ou falei em[n]gentilezas simples durante as relações[n]comerciais do pai...[n][w][e]

[msg D07_01_e407_201_F_AF_mes [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9027 65535 0]Você é um pouco sadista por me fazer obter[n]informações de estranhos completos, Joker![n][w][e]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas eu vou fazer isso! Vou vingar minha mãe.[n][w][e]

