[msg ALL_PICTURE_CHECK_EVENT_ [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Aqui está o nome completo...[n][w][e]

[msg ALL_PICTURE_CHECK_EVENT__2 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6028 65535 0]Outra vítima de[n]Madarame, certo?[n][w][e]

[msg ALL_PICTURE_CHECK_EVENT__3 [Yusuke]]
[s][bup 0 5 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4170 65535 0]Jamais esquecerei essa[n]expressão... O olhar de[n]quem saindo do ateliê...[n][w][e]

