[msg D159_01_L_01_mes01 [Navegador do Metaverso]]
[s]Este é o ponto de retorno[n]do Palácio Shido.[n][w][e]

[msg D159_01_L_01_mes02 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]É muito cedo para voltar! Vamos lá, vamos[n]explorar um pouco por dentro primeiro.[n][w][e]

[msg D159_01_L_01_N_mes02 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]É muito cedo para voltar! Vamos lá, vamos[n]explorar um pouco por dentro primeiro.[n][w][e]

[msg D159_01_L_02_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]Espere, Joker.[n]É melhor irmos por hoje.[n][w][e]

