[msg D01_04_e160_086_mes01 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7047 65535 0]*anf* Eu não pensei que essas coisas[n]poderiam ser tão fodas...[n][w][e]

[msg D01_04_e160_086_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sim... Ele parece estar fazendo o possível para[n]nos impedir.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, eu te ensinei várias coisas até agora, mas[n]o tempo para lições acabou.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vou compilar informações[n]úteis para a batalha. Lembre-se de[n]verificá-lo mais tarde.[n][w][e]

[msg D01_04_e160_086_mes05 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]Merda... Tem outros...[n][w][e]

[msg D01_04_e160_086_mes06 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O que nós fazemos? Vamos voltar?[n][w][e]

[msg D01_04_e160_086_mes07 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não, o Tesouro está sem dúvida[n]à frente e em algum lugar[n]deve haver um caminho.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você vê alguma coisa que pode nos ajudar a passar[n]por isso? Mantenha os olhos abertos![n][w][e]

[msg D01_04_e160_086_af_mes02]
[s]Afinidade, Alterações Negativas,[n]Assistência de Habilidade e Corrida[n]adicionadas ao Tutorial de Batalha.[n][w][e]
[s]Você pode visualizar os tutoriais anteriores[n]no item Tutorial[n]no menu [f 1 10 25].[n][w][e]

[msg D01_04_e160_091_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Há algo lá embaixo que me cheira mal.[n]Também há trepadeiras[n]na porta.[n][w][e]

[msg D01_04_e160_091_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Já. Aparentemente, já faz um tempo que ninguém[n]entra lá.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se ao menos houvesse uma maneira[n]de ir mais longe…[n][w][e]

[msg D01_04_e160_091_mes03 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não vejo nada que sirva para[n]ossa... Pena que não[n]podemos chegar lá com um simples salto.[n][w][e]

[msg D01_04_e160_091_mes04]
[s]......?[n][w][e]

[msg D01_04_e160_091_mes05]
[s]Mas isso é...?[n][w][e]

[msg D01_04_e160_091_mes06 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O que é, Joker?[n][w][e]

[sel D01_04_e160_091_selA top]
[s]É hora de usar seu dom.[e]
[s]é o momento perfeito[e]
[s]para tirá-lo.[e]

[msg D01_04_e160_091_mes07 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh? O que você está... Oh, ótimo![n]É hora do gancho![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se você usá-lo corretamente,[n]nos levará para o outro lado com certeza,[n]mas onde você vai mirar?[n][w][e]

[msg D01_04_e160_092_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vaca sagrada! Você viu?!?[n]Nós fizemos WHOOOSH![n][w][e]

[msg D01_04_e160_092_mes02 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sim, nem tive tempo[n]para me recuperar da surpresa![n]É super útil.[n][w][e]

[msg D01_04_e160_092_mes03 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Boa jogada, Joker! Eu sabia,[n]você tem um talento natural![n][w][e]
[s][bup 0 3 8 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se você vir uma área que não pode[n]alcançar a pé,[n]o gancho pode ser útil![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mantenha os olhos abertos e procure apoios para[n]as mãos. É um aspecto fundamental para um bom[n]Phantom Thief, viu?[n][w][e]

[msg D01_04_e160_092_mes04 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aqui vamos nós novamente...[n][w][e]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos dar uma olhada naquela porta.[n][w][e]

[msg D01_04_e160_093_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1109 65535 0]...Fiuuu, foi perto. Ótimo[n]trabalho, Joker! Você é bom[n]com esse gancho.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Agora podemos explorar a área![n]Vamos nos mover.[n][w][e]

