[msg D04_03_e296_251_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]O mural deve ser exibido na parede da frente[n]agora, certo?[n][w][e]

[msg D04_03_e296_251_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Eu esperaria assim. Joker, se você quiser.[n][w][e]

[msg D04_03_e296_351_AF01_mes [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 31 0 0]Nós apenas temos que resolver esse[n]quebra-cabeça.[n]Você pode fazer isso, Joker![n][w][e]

[msg D04_03_e296_351_AF02_mes [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Este é o dispositivo que abre a porta,[n]certo? A luz está refletindo na direção[n]certa agora.[n][w][e]

[msg D04_03_e296_351_AF02_mes_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tenho certeza de que a porta será aberta[n]agora.[n]Vamos confirmar isso.[n][w][e]

[msg D04_03_e296_301_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6023 65535 0]Sim! Terminamos![n][w][e]

[msg D04_03_e296_301_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]Uma criança puxando as roupas da mãe?[n][w][e]

[msg D04_03_e296_301_mes03 [Girl's Voice]]
[s][vp 1 0 0 7 0 0]...Mãe...[n][w][e]

[msg D04_03_e296_301_mes04 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 8 0 0]Mais vozes...[n][w][e]

[msg D04_03_e296_301_mes05 [Girl's Voice]]
[s][vp 1 0 0 9 0 0]Estou... estou cansado de jantar sozinho o[n]tempo todo.[n][w][e]
[s][vp 1 0 0 10 0 0]É sempre apenas bento da loja de[n]conveniência...[n][w][e]
[s][vp 1 0 0 11 0 0]Eu quero ir a algum lugar.[n]Leve-me em uma viagem![n][w][e]

[msg D04_03_e296_301_mes06 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 12 0 0]O que se apega à mãe seria Futaba-chan,[n]certo?[n][w][e]

[msg D04_03_e296_301_mes07 [Young Woman's Voice]]
[s][vp 1 0 0 13 0 0]Não seja tão egoísta![n][w][e]
[s][vp 1 0 0 14 0 0]Você sabe que estou trabalhando duro para[n]apoiá-lo, certo!?[n][w][e]
[s][vp 1 0 0 15 0 0]Eca![n][w][e]

[msg D04_03_e296_301_mes08 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 16 0 0]Ela parecia muito brava...[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 17 0 0]Essa é a neurose da maternidade que a voz[n]mencionou anterior?[n][w][e]

[msg D04_03_e296_301_mes09 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 18 0 0]Eu pensei que era bastante normal para uma[n]criança querer passar tempo com os pais, no[n]entanto...[n][w][e]

[msg D04_03_e296_301_mes10 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 19 0 0]Sim. Parece que Futaba era um garoto muito[n]solitário crescendo...[n][w][e]

[msg D04_03_e296_301_mes11 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 20 0 0]Então, esses incidentes agravam, forçando[n]sua mãe a se suicidar?[n][w][e]

[msg D04_03_e296_301_mes12 [Shadow Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 21 0 0]... eu devo morrer.[n][w][e]

[msg D04_03_e296_301_mes13 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 22 0 0]Huh?[n][w][e]

[msg D04_03_e296_301_mes14 [Shadow Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 23 0 0]Eu a matei... é por isso que estou aqui[n]nesta tumba...[n][w][e]

[msg D04_03_e296_301_mes15 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 24 0 0]Não diga isso![n][w][e]

[msg D04_03_e296_301_mes16 [Shadow Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 25 0 0]Eu vou morrer...[n][w][e]

[msg D04_03_e296_301_mes17 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 26 0 0]Futaba-chan![n][w][e]

[msg D04_03_e296_301_mes18 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 27 0 0]Por que ela ficou tão quieta de repente?[n]O que aconteceu com essa personalidade[n]sarcástica?[n][w][e]

[msg D04_03_e296_301_mes19 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 28 0 0]Seu coração poderia estar ficando mais fraco?[n][w][e]

[msg D04_03_e296_301_mes20 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 29 0 0]Temos que nos apressar e salvá-la![n][w][e]

[msg dummy_mes01]
[s](仮)反射板が動く[n][w][e]

[msg dummy_mes02]
[s](仮)光が反射される[n][w][e]

[msg dummy_mes03]
[s](仮)壁画が消える[n][w][e]

[msg dummy_mes04]
[s](仮)扉がひらく[n][w][e]

[msg D04_PUZZLE_dummy1_mes01]
[s](仮)パズルギミック調整中のため飛ばします[n][w][e]

