[msg GOTO_MEME_DUMMY [Morgana]]
[s][bup 0 3 0 0 0]......[n][w][e]

[sel GOTO_MEMENTOS_SEL top]
[s]Vamos.[e]
[s]Deixe-me repensar isso.[e]

[sel GOTO_MEMENTOS_NO_TARGET_ top]
[s]Vamos.[e]
[s]Deixe-me repensar isso.[e]

[msg GOTO_MEME_NG_0713_01 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2111 65535 0]Os exames começam o dia depois de amanhã.[n]Provavelmente devemos gastar nosso tempo[n]estudando.[n][w][e]

[msg GOTO_MEME_NG_0713_02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7111 65535 0]Vamos lá, não seja tão tenso sobre isso.[n]Vamos apenas![n][w][e]

[msg GOTO_MEME_NG_0713_03 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6140 65535 0]Eu tenho que concordar com Makoto. Prefiro[n]estudar...[n][w][e]

[msg GOTO_MEME_NG_0713_04 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7063 65535 0]Tudo bem... acho que estou fazendo o mesmo[n]então.[n][w][e]

[msg GOTO_MEME_NG_0713_05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4023 65535 0]Hm, espero ver porcos subindo pelo céu[n]amanhã...[n][w][e]

[msg GOTO_MEME_NG_0713_06 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7043 65535 0]Ei, eu estudo às vezes, você sabe![n][w][e]

[msg GOTO_MEME_NG_0714_01 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2112 65535 0]Você está falando sério? Temos exames amanhã.[n][w][e]

[msg GOTO_MEME_NG_0714_02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7111 65535 0]Mas estudamos tudo ontem à noite! Não[n]podemos demitir os livros por um dia?[n][w][e]

[msg GOTO_MEME_NG_0714_03 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0]Não.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2043 65535 0]Se você continuar reclamando, terei que[n]cancelar a festa de celebração também.[n][w][e]

[msg GOTO_MEME_NG_0714_04 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7017 65535 0]Você é um maldito tirano...[n][w][e]

[msg GOTO_MEME_NG_0714_05 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0]Tudo bem para mim.[n][w][e]

[msg GOTO_MEME_NG_0714_06 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7063 65535 0]O que quer que... acho que não estamos indo[n]hoje...[n][w][e]

[msg GOTO_MEME_NG_1008_01 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2112 65535 0]Seria perigoso fazer qualquer coisa agora.[n]Devemos abster-se de qualquer atividade até[n]que os exames terminem.[n][w][e]

[msg GOTO_MEME_NG_1008_02 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0]Além disso, Haru também não está conosco...[n][w][e]

[msg GOTO_MEME_NG_1008_03 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0]Também estou fazendo um monte de pesquisas[n]agora. Basta ficar baixo e preparar-se para[n]o meu relatório.[n][w][e]

[msg GOTO_MEME_NG_1008_04 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0]HM? O que você está pesquisando?[n][w][e]

[msg GOTO_MEME_NG_1008_05 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 9086 65535 0]Isso é o topo segredo![n][w][e]

[msg GOTO_MEME_NG_1118_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 8112 65535 0]Agora não é a hora de tais coisas. Em vez[n]disso, enviamos o cartão de visita para[n]SAE-san.[n][w][e]

[msg GOTO_MEME_NO_TARGET_mes0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]Nosso alvo não está aqui. Vamos continuar[n]explorando.[n][w][e]

[msg GOTO_MEME_NO_TARGET_mes0_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Nosso alvo não está aqui. Vamos continuar[n]explorando normalmente.[n][w][e]

[msg GOTO_MEME_NO_TARGET_mes0_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0]Parece que nosso alvo não está aqui. Devemos[n]explorar?[n][w][e]

[msg GOTO_MEME_NO_TARGET_mes0_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0]Parece que nosso alvo não está aqui. Vamos[n]explorar normalmente.[n][w][e]

[msg GOTO_MEME_NO_TARGET_mes0_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0]Parece que nosso alvo não está aqui. Vamos[n]nos concentrar em explorar.[n][w][e]

[msg GOTO_MEME_NO_TARGET_mes0_6 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0]Nosso alvo não está aqui, mas vamos explorar.[n][w][e]

[msg GOTO_MEME_NO_TARGET_mes0_7 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0]Parece que nosso alvo não está aqui. Então[n]vamos explorar como sempre.[n][w][e]

[msg GOTO_MEME_NO_TARGET_mes0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0]Nosso alvo não parece estar aqui.[n]Vamos explorar?[n][w][e]

[msg GOTO_MEME_NO_TARGET_mes0_9 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0]Nosso alvo não parece estar aqui.[n]Você gostaria de explorar?[n][w][e]

[msg GOTO_MEME_NO_TARGET_mes0_10 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0]Nosso alvo não parece estar aqui.[n]Vamos explorar?[n][w][e]

[msg GOTO_MEME_EXIST_TARGET_m [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]Ei quantos alvos obtivemos?[n][var 0]Dei, sim? Vamos fazer isso.[n][w][e]

[msg GOTO_MEME_EXIST_TARGET_m_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]No momento, nossa contagem de alvos em[n]lembranças é [n][var 0]. Bem, vamos.[n][w][e]

[msg GOTO_MEME_EXIST_TARGET_m_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0]Vamos ver, quantos alvos temos...?[n][var 0]deles? Devemos começar?[n][w][e]

[msg GOTO_MEME_EXIST_TARGET_m_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0]O número de alvos residentes em lembranças é [var 0]Atualmente. Agora então, devemos entrar?[n][w][e]

[msg GOTO_MEME_EXIST_TARGET_m_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0]HM, vamos considerar nosso total alvo.[n]Nós conhecemos [var 0]Atualmente em lembranças, sim? Vamos.[n][w][e]

[msg GOTO_MEME_EXIST_TARGET_m_6 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0]Alvos? Há prolly [var 0]lá agora. Vamos lá, vamos derrubá-los.[n][w][e]

[msg GOTO_MEME_EXIST_TARGET_m_7 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0]Oh, sobre nossos alvos... parece que temos [n][var 0]para buscar agora. Nós devemos ir.[n][w][e]

[msg GOTO_MEME_EXIST_TARGET_m_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0]HM, vamos considerar nosso total alvo.[n]Nós conhecemos [var 0]Atualmente em lembranças, sim? Vamos.[n][w][e]

[msg GOTO_MEME_EXIST_TARGET_m_9 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0]Verificação de destino!...[var 0]deles deixados na área. Devemos ir?[n][w][e]

[msg GOTO_MEME_EXIST_TARGET_m_10 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0]HM, vamos considerar nosso total alvo.[n]Nós conhecemos [var 0]Atualmente em lembranças, sim? Vamos.[n][w][e]

[msg GOTO_MEME_YOKOKU_NG_mes0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7156 65535 0]Cara, precisamos estar prontos para amanhã.[n]Vamos fazer com calma hoje.[n][w][e]

[msg GOTO_MEME_YOKOKU_NG_mes0_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1139 65535 0]O assalto é amanhã. Devemos adiar o trabalho[n]por hoje.[n][w][e]

[msg GOTO_MEME_YOKOKU_NG_mes0_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6140 65535 0]Não vamos entrar hoje, então temos tempo[n]para nos preparar para amanhã.[n][w][e]

[msg GOTO_MEME_YOKOKU_NG_mes0_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4114 65535 0]Vamos nos abster de tais atividades hoje e,[n]em vez disso, nos concentrar em preparar[n]para amanhã.[n][w][e]

[msg GOTO_MEME_YOKOKU_NG_mes0_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2139 65535 0]Devemos nos concentrar em nos preparar para[n]amanhã, em vez de entrar hoje.[n][w][e]

[msg GOTO_MEME_YOKOKU_NG_mes0_6 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9141 65535 0]Não está acontecendo hoje! Temos que[n]preparar para amanhã![n][w][e]

[msg GOTO_MEME_YOKOKU_NG_mes0_7 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9139 65535 0]Devemos nos concentrar em nos preparar para[n]amanhã, em vez de entrar hoje.[n][w][e]

[msg GOTO_MEME_YOKOKU_NG_mes0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 8113 65535 0]Vamos nos abster de tais atividades hoje e,[n]em vez disso, nos concentrar em preparar[n]para amanhã.[n][w][e]

[msg GOTO_LAST_DUNGEON_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1139 65535 0](仮)ラスダン専用メッセージ。[n][w][e]

[msg QUEST_TALK_D7_PLAYABLE1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Huh? Você está curioso sobre lembranças?[n][w][e]
[s]É verdade que acho que não há sentido em[n]deixar o tempo desperdiçar enquanto[n]esperamos o dia do assalto.[n][w][e]

[msg QUEST_TALK_D7_PLAYABLE2 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Claro que sim. Vamos entrar lá e fazer o que[n]pudermos antes do nosso último emprego.[n][w][e]

