[msg D159_13_L_01_mes01 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4083 65535 0]O que você está fazendo!? Precisamos[n]priorizar o alvo escapado![n][w][e]

[msg D159_13_c_01_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Nosso alvo parece estar dentro desta sala.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nós o encurralamos até agora, então vamos[n]procurar um caminho para dentro.[n][w][e]

[msg D159_13_L_02_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7175 65535 0]Agh, caramba! Ele trancou a porta![n][w][e]

[msg D159_13_L_02_mes02 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Isso não vai servir. Também não podemos[n]desistir exatamente da carta... existe[n]alguma maneira de...?[n][w][e]

