[msg D01_BRIEFING_060_mes01 [Ann]]
[s][bup 0 4 103 0 0][vp 8 2 1 6183 65535 0]......[n][w][e]

[msg D01_BRIEFING_060_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ainda pensando naquele[n]quarto de antes?[n][w][e]

[msg D01_BRIEFING_060_mes03 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu continuo pensando no que Shiho deve ter[n]passado...[n][w][e]

[msg D01_BRIEFING_060_mes04 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Yo, Mona, onde estamos agora?[n][w][e]

[msg D01_BRIEFING_060_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh? B-Bem, eu diria que cerca de[n]no meio do caminho...[n][w][e]

[msg D01_BRIEFING_060_mes06 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ouvi? Nós só precisamos[n]da outra metade, então[n]podemos vingar Suzui![n][w][e]

[msg D01_BRIEFING_060_mes07 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6186 65535 0]Sim você está certo.[n][w][e]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Desculpe pela atitude deprimente.[n]A partir de agora vou dar tudo de mim![n][w][e]

