[msg MSG_DUMMY]
[s]......[n][w][e]

[sel YESNO_SEL top]
[s]Sim[e]
[s]Não[e]

[msg MND_JuiceShop_NotOpen]
[s]Aqui eles vendem suco espremido na hora.[n][w][e]
[s]Quando tiver tempo, devo experimentar...[n][w][e]

[msg MSG_1stInfo_Aojiru_01 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Uma barraca de bebidas, hein? É um pouco mais[n]caro do que em outros lugares.[n][w][e]
[s][f 4 10 65535 0 0]Se eles tiverem alguma bebida especial,[n]não faria mal experimentá-los ...[n][w][e]

[msg MSG_1stInfo_Aojiru_02 [Vendedora de quiosque de bebidas]]
[s][f 4 23 1 2 3 5 65534 0][vp 8 2 1 0 2 0]Bem-vindo! Temos suco fresco![n][w][e]
[s][vp 8 2 1 0 2 0]Gosta? Bebidas especiais?[n]Sim, temos hoje![n][w][e]

[msg MSG_1stInfo_Aojiru_03 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Oooh, quem sabe o que são.[n][w][e]

[msg MSG_1stInfo_Aojiru_NotSe [Vendedora de quiosque de bebidas]]
[s][f 4 23 1 2 3 5 65534 0][vp 8 2 1 0 2 0]Bem-vindo! Como?[n]Bebidas especiais?[n][w][e]
[s][vp 8 2 1 0 2 0]Bom, no [clr 2]domingo[clr 27] temos um[n]suco especial de vegetais...[n][w][e]

[msg MSG_1stInfo_Aojiru_NotSe_2 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0]Então hoje nada, né? Que pena.[n]Vamos tentar voltar no domingo?[n][w][e]

[msg MSG_1stInfo_Aojiru_04 [Vendedora de quiosque de bebidas]]
[s][f 4 23 1 2 3 5 65534 0][vp 8 2 1 0 2 0]É muito amargo, mas[n]fortalece o corpo.[n][w][e]
[s][vp 8 2 1 0 2 0]O nome dele é Aojiru![n][w][e]
[s][vp 8 2 1 0 2 0]Temos um tipo diferente de aojiru[n]toda semana.[n][w][e]

[msg MSG_NotSale_Aojiru_01 [Vendedora de quiosque de bebidas]]
[s][f 4 23 1 2 3 5 65534 0][vp 8 2 1 0 2 0]Me desculpe, mas hoje não temos aojiru...[n][w][e]
[s][vp 8 2 1 0 2 0]Vendemos apenas aos [clr 2]domingos[clr 27].[n][w][e]

[msg MSG_NotSale_Aojiru_02 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Que pena. Vamos voltar[n]outra vez![n][w][e]

[msg MSG_Sale_Aojiru_01 [Vendedora de quiosque de bebidas]]
[s][f 4 23 1 2 3 5 65534 0][vp 8 2 1 0 2 0]Bem-vindo! Quer um pouco de suco espremido na[n]hora?[n][w][e]
[s][vp 8 2 1 0 2 0]Hoje é [clr 2]domingo[clr 27], então[n]também temos aojiru![n][w][e]

[msg MSG_Sale_Aojiru_02 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Oh, eles têm![n]Eles têm aojiru![n][w][e]

[msg MSG_Aojiru_Notbuy [Morgana]]
[s][bup 0 3 11 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Você não bebe?[n]Tão assustado?[n][w][e]

[msg MSG_Aojiru_Today_Drink [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Tente se limitar a um por dia. Mesmo as coisas[n]saudáveis são ruins se você exagerar.[n][w][e]

[msg MND_Aojiru_ParamEndInfo_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Aparentemente, com o aojiru de hoje, você terá[n]mais[f 4 11 0][clr 26][f 4 12 0][clr 27]. Mas[n]talvez você não precise agora.[n][w][e]

[msg MND_Aojiru_ParamEndInfo__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Aparentemente, com o aojiru de hoje, você terá[n]mais[f 4 11 1][clr 26][f 4 12 1][clr 27]. Mas[n]talvez você não precise agora.[n][w][e]

[msg MND_Aojiru_ParamEndInfo__3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Aparentemente, com o aojiru de hoje, você terá[n]mais[f 4 11 2][clr 26][f 4 12 2][clr 27]. Mas[n]talvez você não precise agora.[n][w][e]

[msg MND_Aojiru_ParamEndInfo__4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Aparentemente, com o aojiru de hoje, você terá[n]mais[f 4 11 3][clr 26][f 4 12 3][clr 27]. Mas[n]talvez você não precise agora.[n][w][e]

[msg MND_Aojiru_ParamEndInfo__5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Aparentemente, com o aojiru de hoje, você terá[n]mais[f 4 11 4][clr 26][f 4 12 4][clr 27]. Mas[n]talvez você não precise agora.[n][w][e]

[msg MSG_Aojiru_Start_RND01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Bom! Vamos, engula![n][w][e]

[msg MSG_Aojiru_Start_RND02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Q-Que tipo de cor...[n]Eu certamente NÃO beberia isso.[n][w][e]

[msg MSG_Aojiru_Start_RND03 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Você tem que ter coragem e[n]lembrar que[n]é para a sua saúde.[n][w][e]

[msg MSG_Aojiru_NowDrink [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Tudo de uma vez![n]É assim que se faz![n][w][e]

[msg MSG_Aojiru_End [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1045 65535 0]Bom menino! Eu vi que[n]você tentou muito.[n][w][e]

[msg MSG_Aojiru_HumanParamGet [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Uau, você parece uma pessoa totalmente diferente![n][w][e]

[msg TEST_MONA2 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 47 0 0]Você subiu na hierarquia, hein?[n][w][e]

[msg MSG_Aojiru_Finish [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]OK, depois dessa cheia de saúde[n]vamos para outro lugar![n][w][e]

