[msg D01_04_e165_001_mes01 [Guard Captain]]
[s]Meu LIEGE! Eu trago notícias terríveis![n][w][e]

[msg D01_04_e165_001_mes02 [Kamoshida]]
[s][bup 0 202 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O que é isso?[n][w][e]

[msg D01_04_e165_001_mes03 [Guard Captain]]
[s]Perdoe-nos, rei Kamoshida. Os intrusos[n]levaram a chave para a sala do tesouro.[n][w][e]

[msg D01_04_e165_001_mes04 [Kamoshida]]
[s][bup 0 202 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O que!? Isso é impossível! Eu pensei que lhe[n]disse para lidar com esses imbecis![n][w][e]

[msg D01_04_e165_001_mes05 [Guard Captain]]
[s]Parece que falhamos em acabar com eles...[n][w][e]

[msg D01_04_e165_001_mes06 [Kamoshida]]
[s][bup 0 202 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Como eles me desafiam assim...[n][w][e]

[msg D01_04_e165_001_mes07 [Kamoshida]]
[s][bup 0 202 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hmph... não importa. Não é como se eles[n]pudessem chegar a esta torre.[n][w][e]

[msg D01_04_e165_001_mes08 [Kamoshida]]
[s][bup 0 202 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sele todos os corredores que conectam o[n]castelo a esta torre. Não os deixe perto de[n]mim![n][w][e]

[msg D01_04_e165_001_mes09 [Guard Captain]]
[s]Entendido![n][w][e]

