[msg D07_BRIEFING_020_mes01 [Haru]]
[s][bup 0 7 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3199 65535 0]Precisamos recuperar cinco cartas de[n]recomendação, certo? Eu ajudarei da maneira que[n]puder![n][w][e]

[msg D07_BRIEFING_020_mes02 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Um político, um ex-nobre, um[n]presidente de uma rede de TV, um de[n]uma empresa de TI e um gari![n][w][e]

[msg D07_BRIEFING_020_mes03 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos nos preparar para os obstáculos que nos[n]esperam. Afinal, é o Palácio do homem por trás[n]dessa história.[n][w][e]

