[msg D04_02_e295_025_mes01 [Shadow Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Você está saindo?[n][w][e]

[msg D04_02_e295_025_mes02 [Shadow Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Volte aqui. Vamos falar por um momento.[n][w][e]

[msg MSG_e295_025_AF_000 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Espere, Futaba-chan pediu que você voltasse![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Devemos ir falar com ela.[n][w][e]

[msg D04_02_e295_026_mes01 [Shadow Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Bem vindo de volta. Eu pensei que nunca mais[n]te veria.[n][w][e]

[msg D04_02_e295_026_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]Sim, eu me pergunto por que- não posso[n]acreditar que você tentou nos esmagar com[n]uma pedra de Effing![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Você quer que roubamos seu maldito tesouro[n]ou não?[n][w][e]

[msg D04_02_e295_026_mes03 [Shadow Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]HM, por que não fazemos um acordo? Você[n]deseja prosseguir, sim?[n][w][e]

[msg D04_02_e295_026_mes04 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 7 0 0]Um acordo, você diz?[n][w][e]

[msg D04_02_e295_026_mes05 [Shadow Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 8 0 0]Há uma cidade próxima. Eu gostaria que você[n]retomasse o que o bandit roubou de mim.[n][w][e]

[msg D04_02_e295_026_mes06 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 9 0 0]Ah, sim, acho que me lembro de ver uma[n]cidade no caminho aqui.[n][w][e]

[msg D04_02_e295_026_mes07 [Shadow Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 10 0 0]Se você trazer o que foi roubado de volta[n]para mim, eu lhe darei uma recompensa. Vou[n]até te dizer como proceder.[n][w][e]

[msg D04_02_e295_026_mes08 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 11 0 0]Você não pode nos dizer mais detalhes?[n]Algo sobre esse bandido, ou o que foi[n]roubado?[n][w][e]

[msg D04_02_e295_026_mes9 [Shadow Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 12 0 0]Você aprenderá todas as informações que você[n]precisa saber quando chegar.[n][w][e]

[msg D04_02_e295_026_mes10 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 13 0 0]Precisamos sair se quisermos ir para a[n]cidade. Podemos ir quando você estiver[n]pronto, Joker.[n][w][e]

[msg D04_02_e295_027_mes01 [Shadow Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Retire o que esse bandido roubou de mim.[n]Ele deveria estar na cidade vizinha.[n][w][e]

[msg D04_03_e295_041_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Estamos de volta. É isso que você disse que[n]eles roubaram, certo?[n][w][e]

[msg D04_03_e295_041_mes02 [Shadow Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Bom trabalho. É seu agora.[n][w][e]

[msg D04_03_e295_041_mes03 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Espere o que? Você não queria que[n]recuperássemos porque é importante?[n][w][e]

[msg D04_03_e295_041_mes04 [Shadow Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]Esse é um mapa da tumba, roubado pelo[n]bandido para ajudar em seu saqueado deste[n]lugar.[n][w][e]

[msg D04_03_e295_041_mes05 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Por que você está deixando que eles apenas[n]façam o que quiserem? Este é o seu palácio,[n]não é?[n][w][e]

[msg D04_03_e295_041_mes06 [Shadow Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]Tudo o que importa é que o mapa agora é seu.[n]Apenas entre mais adiante e... Oh.[n][w][e]

[msg D04_03_e295_041_mes07 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 7 0 0]O que no—?[n][w][e]

[msg D04_03_e295_041_mes08 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 8 0 0]Huh? Futaba-chan Disa— [n][w][e]

[msg D04_03_e295_041_mes09 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 9 0 0]Goddammiiiiiiiiiiii![n][w][e]

