[msg D07_06_e380_130_mes01 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos revisar nossa situação. Então, o que[n]exatamente precisamos fazer?[n][w][e]

[msg D07_06_e380_130_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Deve ser bem claro. Devemos jogar no cassino[n]e vencer.[n][w][e]

[sel D07_06_e380_130_selA top]
[s]Os clientes são divididos nos diferentes[n]pisos com base na classificação de sua peça.[n][f 2 7 0 0 106 1][e]
[s]Se desejarmos entrar em um piso mais alto,[n]precisaremos aumentar nossa classificação.[n][f 2 7 0 0 106 1][e]

[msg D07_06_e380_130_selA_0_m [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Então isso significa que temos que ganhar e [n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ganhe o direito de liderar [n][w][e]

[msg D07_06_e380_130_selA_1_m [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E, como mencionei anteriormente, um cartão[n]de um membro diferente é usado dependendo[n]da sua classificação.[n][w][e]

[msg D07_06_e380_130_selA_2_m [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg D07_06_e380_130_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Teremos que obter um cartão para o [n][w][e]

[msg D07_06_e380_130_mes04 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]piso limite alto [n][w][e]

[msg D07_06_e380_130_mes05 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]em algum lugar por aqui.[n][w][e]

