[msg mini_EV_e210_143_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]HM, parece que esta é a sala de controle de[n]segurança...[n][w][e]

[msg mini_EV_e210_143_mes02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, sim, é hora de desligar essa merda![n][w][e]

[msg mini_EV_e210_143_mes03 [Terminal]]
[s]Insira a senha.[n][w][e]

[msg mini_EV_e210_143_mes04 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7021 65535 0]Ugh, outro...?[n][w][e]

[msg mini_EV_e210_143_mes05 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos apenas procurar alguém que possa[n]saber...[n][w][e]

[msg mini_EV_e210_143_mes06 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Não há nada que possamos fazer com isso, a[n]menos que descobramos a senha, certo?[n][w][e]

[msg mini_EV_e210_143_mes07 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]Não há nada que possamos fazer com isso, a[n]menos que descobramos a senha, certo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aquele guarda disse algo sobre os "pés de[n]Madarame", certo? O que isso poderia[n]significar...?[n][w][e]

[msg mini_EV_e210_143_mes08 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Tudo bem, vamos tentar essa senha que[n]encontramos![n][w][e]

[msg mini_EV_e210_143_mes09 [Terminal]]
[s]Senha aceita...[n]Desengajando o Protocolo de Segurança...[n][w][e]

[msg mini_EV_e210_143_mes10 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uau... que abriu todo tipo de coisa...[n][w][e]

[msg mini_EV_e210_143_mes11 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Definitivamente, poderemos ir a mais lugares[n]agora! Vamos lá, vamos nos mudar![n][w][e]

