[msg MSG_DESK_CLEAN_THINK [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Aparentemente vai demorar um[n]dia inteiro para limpar tudo...[n][w][e]
[s][f 4 10 65535 0 0]No entanto, devemos, se quisermos[n]criar ferramentas[n]de infiltração. Contando com você.[n][w][e]

[sel MSG_DESK_CLEAN_THINK_SEL top]
[s]Vamos limpar.[e]
[s]É muito cansativo.[e]

[msg MSG_DESK_CLEAN_START [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]OK! Vamos polir[n]esta mesa![n][w][e]

[msg MSG_DESK_CLEAN_CANCEL [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ei, o que há de errado com você? Não podemos[n]criar ferramentas se não[n]limparmos essa bagunça primeiro.[n][w][e]

[msg BENCH_CLEAN_END [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Tudo bem, chega de limpeza![n]Agora devemos poder[n]usar a escrivaninha.[n][w][e]
[s][f 4 10 65535 0 0]Vamos fazer ferramentas, agora![n][w][e]

