[msg D04_BRIEFING_040_mes01 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4189 65535 0]Este palácio é um lugar intrigante.[n]Até esses murais são fascinantes.[n][w][e]

[msg D04_BRIEFING_040_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você sempre entra nesses palácios com uma[n]sensação de admiração, Fox. Na verdade,[n]estou um pouco impressionado.[n][w][e]

[msg D04_BRIEFING_040_mes03 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Obrigada. Eu provavelmente não deveria estar[n]dizendo essas coisas... mas estou ansioso[n]pelo que está por vir.[n][w][e]

