[msg D06_157_11_ex_chk_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]A vontade de Sis semeada está apenas à[n]frente...[n][w][e]

[msg D06_157_11_ex_chk_mes02 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Desculpe, mas você estará nos deixando[n]passar![n][w][e]

[msg D06_157_11_ex_chk_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espere, a rainha- estou sentindo que este[n]será uma dor de cabeça.[n][w][e]

[msg D06_157_11_ex_chk_mes04 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Provavelmente queremos estar o mais pronto[n]para essa luta. Somos, Joker?[n][w][e]

[sel D06_157_11_ex_chk_selA top]
[s]Nós com certeza somos.[e]
[s]Espere um segundo.[e]

[msg D06_157_11_ex_chk_selA_1 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1136 65535 0]Soa bem. Certifique-se de que estamos legais[n]e prontos.[n][w][e]

[msg D06_157_11_ex_chk_re_mes [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1099 65535 0]Então vamos. Prepare-se, Joker![n][w][e]

[msg D06_157_11_ex_btl_mes01 [Shadow]]
[s]Oh querido... convidados? Aqui? Com licença,[n]senhoras e senhores...[n][w][e]
[s]Peço desculpas, mas essa área está fora dos[n]limites para os hóspedes. Por favor, tire[n]sua licença.[n][w][e]

[msg D06_157_11_ex_btl_mes02 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2108 65535 0]Oh, no entanto, não é problema para a irmã[n]do gerente- você é aquele que está fora[n]daqui![n][w][e]

[msg D06_157_11_ex_btl_af_mes [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2165 65535 0]E isso cuida disso! Vamos nos mover.[n][w][e]

[msg D06_157_11_ex_btl_af_mes_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tudo bem, Joker! Pegue e tire-nos para fora[n]aqui![n][w][e]

