[msg D07_02_e408_031_mes01 [Waiter]]
[s]Senhor, se você deseja jantar em nosso[n]restaurante, apresente seu [n][clr 2]Cartão de membro [clr 27] agora.[n][w][e]

[msg D07_02_e408_031_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Ah, sim, ouvimos falar dessa coisa antes...[n]que dor.[n][w][e]

[msg D07_02_e408_031_mes03 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7182 65535 0]Huh? Temos que colocar nossas mãos em algo[n]assim?[n][w][e]

[msg D07_02_e408_031_mes04 [Waiter]]
[s]Eu acredito que nossa equipe deveria ter[n]explicado quando você embarcou neste[n]navio...[n][w][e]
[s]Desculpas pelo inconveniente, mas posso[n]verificar seu passe de embarque, senhor?[n][w][e]

[msg D07_02_e408_031_mes05 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2164 65535 0]Isso é ruim... devemos recuar.[n][w][e]

[msg D07_02_e408_031_mes06 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que não poderemos entrar em paz até[n]que possamos obter isso [n][clr 2]Cartão de membro [clr 27]...[n][w][e]

[msg D07_02_e408_031_AF_mes01 [Waiter]]
[s]Senhor, se você deseja jantar em nosso[n]restaurante, apresente seu [n][clr 2]Cartão de membro [clr 27] agora.[n][w][e]

[msg D07_02_e408_031_AF_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]Parece que não poderemos entrar em paz até[n]que possamos obter isso [n][clr 2]Cartão de membro [clr 27]...[n][w][e]

