[msg MSG_e296_229_000 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]Maldito! Fale sobre uma bagunça![n][w][e]

[msg MSG_e296_229_001 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Está quebrado... bem, acho que seria um[n]pouco mais preciso dizer que quebramos.[n][w][e]

[msg MSG_e296_229_002 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Não podemos passar assim![n]O que vamos fazer!?[n][w][e]

[msg MSG_e296_229_003 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Talvez pudéssemos caminhar sobre os[n]pedregulhos gigantes? Vamos tentar.[n][w][e]

[msg MSG_D155_03_c_04_000 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ugh, você está brincando? Os pedregulhos[n]estão presos, então não podemos sair...[n][w][e]

[msg MSG_D155_03_c_04_001 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Será impossível passar por essa maneira.[n]Teremos que encontrar outro caminho.[n][w][e]

