[msg D03_BRIEFING_080_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6162 65535 0]Absurdo que exista tal lugar aqui. Os palácios[n]escondem tudo.[n][w][e]

[msg D03_BRIEFING_080_mes02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, a realidade foi para o inferno quando[n]encontramos essa coisa flutuante.[n][w][e]

[msg D03_BRIEFING_080_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Isso prova que o coração[n]das pessoas é estranhamente[n]complexo. Os outros eram semelhantes.[n][w][e]

[msg D03_BRIEFING_080_mes04 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, certo. Lembro-me de ouvir[n]que seu primeiro assalto[n]aconteceu em um velho castelo.[n][w][e]

[msg D03_BRIEFING_080_mes05 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O que era isso, uma fantasia medieval?[n][w][e]

[msg D03_BRIEFING_080_mes06 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7114 65535 0]Você faz com que pareça muito melhor do que era.[n]Quero dizer, foram os desejos daquele bastardo[n]do Kamoshida...[n][w][e]

[msg D03_BRIEFING_080_mes07 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ei, devemos nos mexer. Passando[n]esta zona devemos chegar[n]à parte mais profunda do Palácio.[n][w][e]

