[msg D08_01_twins_cure_start_ [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 11027 65535 0]V-Você ainda quer sair[n]dessa situação depois de tudo[n]que aconteceu com você, Prisioneiro?!?[n][w][e]

[sel D08_01_twins_cure_start__2 top]
[s]É claro.[e]
[s]Eu não vou desistir.[e]
[s]Por favor me ajude.[e]

[msg D08_01_twins_cure_start__3 [Caroline]]
[s][bup 0 102 5 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 11055 65535 0]Como você quer provar...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Certo... Não é nenhuma surpresa que[n]você queira fazer isso...[n][w][e]

[msg D08_01_twins_cure_start__4 [Caroline]]
[s][bup 0 102 5 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 11055 65535 0]Vocês...[n][w][e]
[s]Umpf.[n][w][e]

[msg D08_01_twins_cure_start__5 [Caroline]]
[s][bup 0 102 5 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 11064 65535 0]Ajuda...?[n][w][e]
[s]......[n][w][e]

[msg D08_01_twins_cure_start__6 [Caroline]]
[s][bup 0 102 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Ajudar os presos em[n]reabilitação é nosso dever...[n][w][e]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK. Vou te dar uma ajudinha.[n][w][e]

[msg D08_01_twins_cure_start__7]
[s]Sinto que recuperei parcialmente o espírito e a[n]saúde...[n][w][e]

[msg D08_01_twins_cure_start__8 [Caroline]]
[s][bup 0 102 6 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 11022 65535 0]Surpreso? Tal coisa[n]é um absurdo para nós![n][w][e]
[s]Volte se você se machucar[n]novamente, Prisioneiro![n][w][e]

[msg D08_01_twins_cure_mes01 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 11064 65535 0]Ajuda para a sua[n]reabilitação... Não deve haver problema...[n][w][e]

[msg D08_01_twins_cure_mes02]
[s]Sinto que recuperei parcialmente o espírito e a[n]saúde...[n][w][e]

