[msg D01_02_BF_01_new_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nós realmente precisamos fazer isso? Eu só[n]quero descobrir para onde foram esses caras[n]das células.[n][w][e]

[msg D01_02_BF_01_new_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu entendo como você se sente...[n][w][e]

[msg D01_02_BF_01_new_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas ainda há muito que você quer saber sobre[n]este mundo, certo?[n][w][e]

[msg D01_02_BF_01_new_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos falar sobre isso agora que temos tempo.[n][w][e]

[msg D01_02_BF_01_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cara, havia totalmente pessoas que eu[n]conhecia nessas células...[n][w][e]
[s]Você também não viu? Eles estavam realmente[n]lá, certo!?[n][w][e]

[sel D01_02_BF_01_selA top]
[s]Eles foram.[e]
[s]Se acalme.[e]
[s]Eu não me lembro.[e]

[msg D01_02_BF_01_selA_0_mes0 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Isso foi o que eu pensei![n][w][e]
[s]Mas por que as células estão vazias agora!?[n][w][e]

[msg D01_02_BF_01_selA_0_mes0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Acalme-se, vocês dois. Vamos pensar sobre[n]isso com cuidado.[n][w][e]

[msg D01_02_BF_01_selA_1_mes0 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dizendo que não vai resolver nada.[n][w][e]
[s]Eu tenho que saber por que essas células[n]estão vazias agora![n][w][e]

[msg D01_02_BF_01_selA_1_mes0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos pensar sobre isso um pouco mais com[n]cuidado, ok?[n][w][e]

[msg D01_02_BF_01_selA_2_mes0 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu os vi, cara! Eles estavam definitivamente[n]lá![n][w][e]
[s]Mas por que as células estão vazias agora!?[n][w][e]

[msg D01_02_BF_01_selA_2_mes0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Acalme-se, vocês dois. Vamos pensar sobre[n]isso com cuidado.[n][w][e]

[msg D01_02_BF_01_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não há dúvida de que é aqui que vocês[n]queriam vir, mas algo está errado.[n][w][e]
[s]Eu me pergunto por que as células estão[n]abertas...[n][w][e]

[msg D01_02_BF_01_mes03 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Talvez eles escapassem como nós?[n][w][e]

[msg D01_02_BF_01_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não, isso seria impensável.[n][w][e]

[msg D01_02_BF_01_mes05 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por que isso?[n][w][e]

[msg D01_02_BF_01_mes06 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ao contrário de você, eles vêm da cognição[n]do governante deste mundo.[n][w][e]
[s]Esses caras nas células são pessoas que[n]Kamoshida pensa que não vai se voltar[n]contra ele, não importa o quê.[n][w][e]

[msg D01_02_BF_01_mes7 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Então eles são apenas seus escravos.[n][w][e]

[msg D01_02_BF_01_mes8 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sim. Há uma boa chance que eles foram[n]levados para algum lugar.[n][w][e]

[msg D01_02_BF_01_mes9 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas o que ele vai fazer com esses escravos?[n][w][e]

[sel D01_02_BF_01_selB top]
[s]Tortura?[e]
[s]Execução?[e]
[s]Trabalho forçado?[e]

[msg D01_02_BF_01_selB_0_mes0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sim... isso parece muito provável.[n][w][e]

[msg D01_02_BF_01_selB_1_mes0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Talvez, mas acho que a tortura é a[n]possibilidade mais provável.[n][w][e]

[msg D01_02_BF_01_selB_2_mes0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você, como quando eles fazem caras girarem[n]uma roda gigante enquanto um cara de uma[n]máscara os chicoteou?[n][w][e]

[msg D01_02_BF_01_selB_2_mes0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Talvez, mas acho que a tortura é a[n]possibilidade mais provável.[n][w][e]

[msg D01_02_BF_01_mes10 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esse é exatamente o tipo de coisa que o[n]governante deste mundo gosta.[n][w][e]

[msg D01_02_BF_01_mes11 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ugh, Kamoshida é um pau.[n][w][e]
[s]De qualquer forma, isso significa que haverá[n]uma sala de tortura ou algo assim por aqui?[n][w][e]

[msg D01_02_BF_01_mes12 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Provavelmente.[n][w][e]
[s]Chegar lá pode ser perigoso... vocês não[n]querem desistir agora, certo?[n][w][e]

[msg D01_02_BF_01_mes13 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Claro que não![n][w][e]

[msg D01_02_BF_01_mes14 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Excelente. Bem, nós chegamos até aqui, então[n]continuarei com você até que tudo acabe.[n][w][e]

[msg D01_02_BF_01_mes15 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Então está decidido. Vamos procurar a sala[n]de tortura.[n][w][e]

[msg D01_02_BF_01_mes16 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Deixe-me enfatizar novamente o quão perigoso[n]será. Você deve estar preparado para[n]qualquer coisa.[n][w][e]

