[msg D07_BRIEFING_140_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]Sabemos onde está o presidente da empresa de TI.[n]Está em uma sala acima do convés lateral.[n][w][e]

[msg D07_BRIEFING_140_mes02 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sabemos onde está, mas isso não significa[n]que nos deixará entrar...[n][w][e]

[msg D07_BRIEFING_140_mes03 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7038 65535 0]Você não precisa nos abrir, apenas[n]encontre uma maneira de entrar.[n][w][e]

