[msg D05_02_e341_072_mes03 [Voz guia]]
[s]LOUVADO AO NOSSO PRESIDENTE[n]OKUMURA, E SOMENTE A ELE![n]NÓS SOMOS NOSSOS MELHORES ESFORÇOS PARA ELE![n][w][e]

[sel D05_02_e341_072_selA top]
[s]Selecione "Pausar"[e]
[s]Selecione "Almoço"[e]
[s]Selecione "Horas extras"[e]
[s]Não mude nada[e]

[msg D05_02_e341_072_selA_0_m [Voz guia]]
[s]É HORA DO INTERVALO![n][w][e]

[msg D05_02_e341_072_selA_0_m_2 [Voz guia]]
[s]DESCANSAREMOS PARA RECARREGAR O ESPÍRITO CANSADO![n][w][e]

[msg D05_02_e341_072_selA_0_m_3 [Voz guia]]
[s]A PAUSA SERÁ DE[n]APROXIMADAMENTE [clr 2]CINCO SEGUNDOS[clr 27]![n][w][e]

[msg D05_02_e341_072_selA_1_m [Voz guia]]
[s]É HORA DO ALMOÇO![n][w][e]

[msg D05_02_e341_072_selA_1_m_2 [Voz guia]]
[s]VAMOS CONSUMIR NOSSA SAFRA[n]E RECHEAR DE ALEGRIA![n][w][e]

[msg D05_02_e341_072_selA_1_m_3 [Voz guia]]
[s]SEU ALMOÇO SERÁ DE[n]APROXIMADAMENTE [clr 2]TRINTA SEGUNDOS[clr 27]![n][w][e]

[msg D05_02_e341_072_selA_2_m [Voz guia]]
[s]ESTAMOS EM UM ESTADO CONSTANTE DE[n]HORAS EXTRAS NÃO PAGADAS![n][w][e]

[msg D05_02_e341_072_selA_2_m_2 [Voz guia]]
[s]PELO BEM DA EMPRESA![n]LOUVO SEJA NOSSO PRESIDENTE[n]OKUMURA, E SOMENTE A ELE![n][w][e]

[msg D05_02_e341_072_mes04 [Voz guia]]
[s]A PAUSA ACABOU![n][w][e]

[msg D05_02_e341_072_mes05 [Voz guia]]
[s]VAMOS TRABALHAR AINDA MAIS[n]PARA RECUPERAR O TEMPO PERDIDO![n][w][e]

[msg D05_02_e341_072_mes06 [Voz guia]]
[s]ESTAMOS PARADOS![n][w][e]
[s]VAMOS APROVEITAR A OPORTUNIDADE PARA[n]DESCANSAR O CORPO CANSADO![n][w][e]

[msg D05_02_e341_072_rest_mes [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7046 65535 0]Besteiras! O que[n]podemos fazer em cinco[n]malditos segundos?!?[n][w][e]

[msg D05_02_e341_072_rest_mes_2 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Talvez uma respiração profunda...?[n][w][e]

[msg D05_02_e341_072_rest_mes_3 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Cinco segundos não[n]nos ajudam em nada. Eu diria para[n]ignorar essa opção.[n][w][e]

[msg D05_02_e341_072_service_ [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]Ei, ei, ei. Espere um minuto![n]O que você quis dizer com "constante"?!?[n][w][e]

[msg D05_02_e341_072_service__2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Horas extras não pagas[n]é uma constante aqui.[n]A configuração não muda nada...[n][w][e]

[msg D05_02_e341_072_service__3 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]É um pesadelo...[n][w][e]

[msg D05_02_e341_072_service__4 [Haru]]
[s][bup 0 7 103 0 0]......[n][w][e]

[msg D05_02_e341_072_service__5 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4025 65535 0]Se for esse o caso,[n]não é útil para nós. Eu diria que[n]ignore essa opção.[n][w][e]

[msg D05_02_e341_072_reset_me [Voz guia]]
[s]AH! VOCÊ ESTÁ IMPACIENTE PARA VOLTAR[n]AO SEU AMOROSO TRABALHO?[n][w][e]

[sel D05_02_e341_072_reset_se top]
[s]Está bem.[e]
[s]Não.[e]

[msg D05_02_e341_072_reset_se_2 [Voz guia]]
[s]ENTÃO APROVEITE O QUANTO QUISER[n]O PRAZER DO TRABALHO árduo![n][w][e]

[msg D05_02_e341_072_reset_se_3 [Voz guia]]
[s]...NO ENTANTO, ENQUANTO ISSO[n]A PAUSA ACABOU. VOLTE[n]todos ao trabalho![n][w][e]

[msg D05_02_e341_072_reset_se_4 [Morgana]]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]......[n][w][e]

