[msg D08_02_e457_050_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu vejo o que parece ser uma espécie de entrada.[n][w][e]

[msg D08_02_e457_050_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Ah, cuidado. Lá em cima,[n]alguém muito grande está esperando por nós.[n][w][e]

[msg D08_02_e457_050_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ele não vai nos derrotar.[n]Vamos, vamos lá![n][w][e]

[msg D08_e455_004_mes01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Estou detectando uma força significativa...[n]Parece muito perigoso.[n]O que fazemos, Joker?[n][w][e]

[sel D08_e455_004_selA top]
[s]Poder.[e]
[s]Devemos nos preparar primeiro.[e]

[msg D08_e455_004_selA_0_mes0 [Futaba]]
[s][bup 0 8 0 65535 0]Neste caso, LOADAA![n][w][e]

[msg D08_e455_004_selA_1_mes0 [Futaba]]
[s][bup 0 8 0 65535 0]Você tem razão. É melhor[n]proceder com cautela.[n][w][e]

