[msg D157_009_miniEV_03_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Ei, isso não é um [clr 2]terminal[clr 27]?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você pode nos hackear para descobrir[n]como eles trapaceiam, Oracle?[n][w][e]

[msg D157_009_miniEV_03_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bem... está em espera.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uh, basicamente eu tenho que ativá-lo[n]remotamente, de um terminal principal[n]localizado em outro lugar.[n][w][e]

[msg D157_009_miniEV_03_mes03 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8134 65535 0]Portanto, sem fazer login no hub principal, é[n]totalmente inútil.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah bem. Vamos memorizar[n]este lugar por enquanto.[n][w][e]

[msg D157_009_miniEV_07_mes01 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3114 65535 0]Tem um painel de controle aqui![n]Ah, mas é [clr 2]amarelo[clr 27].[n][w][e]

[msg D157_009_miniEV_07_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Estamos procurando o painel vermelho[n]e verde.[n]Vamos procurar em outro lugar.[n][w][e]

[msg D157_009_miniEV_07_mes03 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, vamos continuar procurando![n]Não se preocupe, vamos encontrá-los[n]num piscar de olhos![n][w][e]

