[msg D01_04_e165_061_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Huh...?[n][w][e]

[msg D01_04_e165_061_mes02 [Voice From Behind]]
[s]Hmph. Você está gravemente enganado se achar[n]que as escadas aparecerão para você sempre[n]que quiser.[n][w][e]

[msg D01_04_e165_061_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Então esse cara os está impedindo...[n][w][e]

[msg D01_04_e165_061_ng_mes01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Porcaria, as escadas não estão aparecendo...[n][w][e]

[msg D01_04_e165_061_ng_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esse capitão de guarda provavelmente está[n]impedindo-os de aparecer. Precisamos fazer[n]algo sobre ele...[n][w][e]

