[msg MSG_PER_CHK_00_000 [Igor]]
[s][bup 0 201 0 0 0][f 4 23 1 0 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 22008 65535 0]Vejo que sua reabilitação[n]está indo bem.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Aposto que você já está bastante[n]usado com a infiltração de[n]Palácios, não é?[n][w][e]

[sel SEL_PER_CHK_00_001 top]
[s]Mais ou menos.[e]
[s]Isso me causa algum estresse.[e]
[s]......[e]

[msg MSG_PER_CHK_00_002 [Igor]]
[s][bup 0 201 0 0 0][f 4 23 1 0 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No entanto, você ainda precisa[n]obter uma quantidade aceitável[n]de Personas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Você ainda não explorou totalmente todo o[n]potencial do curinga.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hum, esta pode ser[n]uma oportunidade perfeita para impulsionar[n]sua reabilitação.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Não se preocupe... Esta tarefa[n]não é obrigatória. Veja isso[n]antes como um confronto final.[n][w][e]

[sel SEL_PER_CHK_00_003 top]
[s]Sobre o que é isso?[e]
[s]Bem, como você gosta.[e]

[msg MSG_PER_CHK_00_004 [Justine]]
[s][bup 0 101 0 0 0][f 4 23 1 211 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 12055 65535 0]Você precisará nos trazer uma máscara específica.[n][w][e]

[msg MSG_PER_CHK_00_005 [Caroline]]
[s][bup 0 102 0 0 0][f 4 23 1 200 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 11001 65535 0]Você só precisa nos mostrar a Person[n]que mostraremos a você![n][w][e]

[msg MSG_PER_CHK_00_006 [Justine]]
[s][bup 0 101 0 0 0][f 4 23 1 211 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Em primeiro lugar... gostaríamos que você[n]nos trouxesse um [clr 1]Jack Frost[clr 27].[n][w][e]

[msg MSG_PER_CHK_00_007 [Caroline]]
[s][bup 0 102 0 0 0][f 4 23 1 200 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 11028 65535 0]Muito fácil, Justine![n]Deve ser um desafio.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mmm... Eu quero que ele tenha[n][clr 1]Mabufu[clr 27] também![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 11071 65535 0]Entendeu, Prisioneiro? Traga-nos [clr 1]Jack[n]Frost[clr 27] com [clr 1]Mabufu[clr 27].[n][w][e]

[msg MSG_PER_CHK_00_008 [Justine]]
[s][bup 0 101 0 0 0][f 4 23 1 211 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 12053 65535 0]E seja. Traga-nos[n][clr 1]Jack Frost[clr 27] com [clr 1]Mabufu[clr 27].[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Volte para nós[n]quando você conseguir.[n][w][e]

[msg MSG_PER_CHK_00_009 [Igor]]
[s][bup 0 201 0 0 0][f 4 23 1 0 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Não será obrigatório para sua[n]reabilitação, mas você será[n]recompensado... generosamente.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 22008 65535 0]Eu aconselho você a dar[n]pelo menos uma tentativa.[n][w][e]

