[msg D07_BRIEFING_210_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]O dia finalmente chegou... vamos resolver as[n]coisas com Shido de uma vez por todas![n][w][e]

[msg D07_BRIEFING_210_mes02 [Haru]]
[s][bup 0 7 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sim. Chegamos até aqui, então tenho certeza[n]de que podemos fazer isso![n][w][e]

[msg D07_BRIEFING_210_mes03 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Obviamente! Nós vamos vencê-lo em uma polpa![n][w][e]

