[sel DUNGEON_EXIT_SEL top]
[s]※特殊[e]
[s][clr 6]パレスから帰還する[clr 27][e]
[s]モルガナカー内で作戦会議[e]
[s]潜入を続ける[e]

[sel DUNGEON_EXIT_151_SEL top]
[s]※特殊[e]
[s][clr 6]パレスから帰還する[clr 27][e]
[s]仲間と相談する[e]
[s]潜入を続ける[e]

[sel DUNGEON_EXIT_155_SEL top]
[s]カイロの街へ行く[e]
[s][clr 6]パレスから帰還する[clr 27][e]
[s]モルガナカー内で作戦会議[e]
[s]潜入を続ける[e]

[msg D01_EXIT_MES [Metaverse Navigator]]
[s]Isto é o [clr 2]ponto de retorno [clr 27]ao mundo real da posição atual no palácio de[n]Kamoshida.[n][w][e]

[msg D02_EXIT_MES [Metaverse Navigator]]
[s]Isto é o [clr 2]ponto de retorno [clr 27]ao mundo real da posição atual no palácio de[n]Madarame.[n][w][e]

[msg D03_EXIT_MES [Metaverse Navigator]]
[s]Isto é o [clr 2]ponto de retorno [clr 27]ao mundo real da posição atual no palácio de[n]Kaneshiro.[n][w][e]

[msg D04_EXIT_MES [Metaverse Navigator]]
[s]Isto é o [clr 2]ponto de retorno [clr 27]ao mundo real da posição atual no palácio de[n]Futaba.[n][w][e]

[msg D05_EXIT_MES [Metaverse Navigator]]
[s]Isto é o [clr 2]ponto de retorno [clr 27]ao mundo real da posição atual no palácio de[n]Okumura.[n][w][e]

[msg D06_EXIT_MES [Metaverse Navigator]]
[s]Isto é o [clr 2]ponto de retorno [clr 27]ao mundo real da posição atual no palácio de[n]Niijima.[n][w][e]

[msg D07_EXIT_MES [Metaverse Navigator]]
[s]Isto é o [clr 2]ponto de retorno [clr 27]ao mundo real da posição atual no palácio de[n]Shido.[n][w][e]

[msg D08_EXIT_MES [Metaverse Navigator]]
[s]Isto é o [clr 2]ponto de retorno [clr 27]ao mundo real da posição atual em lembranças.[n][w][e]

[msg DUNGEON_EXIT_01_PC02_mes [Ryuji]]
[s][bup 0 2 0 65535 0]E aí? Você quer voltar e se reagrupar?[n][w][e]

[msg DUNGEON_EXIT_01_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0]HM? Você quer recuar, Joker?[n][w][e]

[msg DUNGEON_EXIT_01_PC04_mes [Ann]]
[s][bup 0 4 0 65535 0]O que está errado? Você quer sair daqui?[n][w][e]

[msg DUNGEON_EXIT_01_PC05_mes [Yusuke]]
[s][bup 0 5 0 65535 0]Deseja reconvender-se, Joker?[n][w][e]

[msg DUNGEON_EXIT_01_PC06_mes [Makoto]]
[s][bup 0 6 0 65535 0]Oh? Você quer se reagrupar?[n][w][e]

[msg DUNGEON_EXIT_01_PC07_mes [Futaba]]
[s]Pode ser uma boa ideia ir para casa e se[n]reagrupar.[n][w][e]

[msg DUNGEON_EXIT_01_PC08_mes [Haru]]
[s]É hora de nos retirarmos?[n][w][e]

[msg DUNGEON_EXIT_01_PC09_mes [Akechi]]
[s]Oh? Você gostaria de se reagrupar?[n][w][e]

[msg D_EXIT_OK_01_PC02_mes [Ryuji]]
[s][bup 0 2 0 65535 0]Mkay, vamos dar uma volta.[n][w][e]

[msg D_EXIT_OK_01_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0]MM, devemos sair para hoje.[n][w][e]

[msg D_EXIT_OK_01_PC04_mes [Ann]]
[s][bup 0 4 0 65535 0]Tudo bem, vamos voltar.[n][w][e]

[msg D_EXIT_OK_01_PC05_mes [Yusuke]]
[s][bup 0 5 0 65535 0]HM, muito bem. Vamos voltar.[n][w][e]

[msg D_EXIT_OK_01_PC06_mes [Makoto]]
[s][bup 0 6 0 65535 0]......[n][w][e]

[msg D_EXIT_OK_01_PC07_mes [Futaba]]
[s]......[n][w][e]

[msg D_EXIT_OK_01_PC08_mes [Haru]]
[s]......[n][w][e]

[msg D_EXIT_OK_01_PC09_mes [Akechi]]
[s]......[n][w][e]

[msg D_EXIT_OK_02_PC02_mes [Ryuji]]
[s][bup 0 2 0 65535 0]Mkay, vamos voltar.[n][w][e]

[msg D_EXIT_OK_02_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0]Hmm, acho que é um bom momento para sair.[n][w][e]

[msg D_EXIT_OK_02_PC04_mes [Ann]]
[s][bup 0 4 0 65535 0]Bem, então, vamos para casa.[n][w][e]

[msg D_EXIT_OK_02_PC05_mes [Yusuke]]
[s][bup 0 5 0 65535 0]Vamos voltar para hoje.[n][w][e]

[msg D_EXIT_OK_02_PC06_mes [Makoto]]
[s][bup 0 6 0 65535 0]......[n][w][e]

[msg D_EXIT_OK_02_PC07_mes [Futaba]]
[s]......[n][w][e]

[msg D_EXIT_OK_02_PC08_mes [Haru]]
[s]......[n][w][e]

[msg D_EXIT_OK_02_PC09_mes [Akechi]]
[s]......[n][w][e]

[msg D_EXIT_OK_03_PC02_mes [Ryuji]]
[s][bup 0 2 0 65535 0]Ufa, terminamos hoje![n][w][e]

[msg D_EXIT_OK_03_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0]É importante saber quando sair.[n]Bem, vamos para casa.[n][w][e]

[msg D_EXIT_OK_03_PC04_mes [Ann]]
[s][bup 0 4 0 65535 0]Isso é tudo por hoje.[n][w][e]

[msg D_EXIT_OK_03_PC05_mes [Yusuke]]
[s][bup 0 5 0 65535 0]HM. Essa deve ser a conclusão da atividade[n]de hoje.[n][w][e]

[msg D_EXIT_OK_03_PC06_mes [Makoto]]
[s][bup 0 6 0 65535 0]......[n][w][e]

[msg D_EXIT_OK_03_PC07_mes [Futaba]]
[s]......[n][w][e]

[msg D_EXIT_OK_03_PC08_mes [Haru]]
[s]......[n][w][e]

[msg D_EXIT_OK_03_PC09_mes [Akechi]]
[s]......[n][w][e]

[msg D_EXIT_GOTO_SAFE_PC02_me [Ryuji]]
[s][bup 0 2 0 65535 0]Sim, deveríamos falar prolicamente[n]estratégia, hein.[n][w][e]

[msg D_EXIT_GOTO_SAFE_PC03_me [Morgana]]
[s][bup 0 3 0 65535 0]OK. Me dê um segundo.[n][w][e]

[msg D_EXIT_GOTO_SAFE_PC04_me [Ann]]
[s][bup 0 4 0 65535 0]OK. Devemos ter uma reunião de estratégia.[n][w][e]

[msg D_EXIT_GOTO_SAFE_PC05_me [Yusuke]]
[s][bup 0 5 0 65535 0]Sim, vamos revisar nossas opções primeiro.[n][w][e]

[msg D_EXIT_GOTO_SAFE_PC06_me [Makoto]]
[s][bup 0 6 0 65535 0]É verdade que seria uma boa ideia examinar[n]nosso plano. Mona, se você quiser.[n][w][e]

[msg D_EXIT_GOTO_SAFE_PC07_me [Futaba]]
[s]Sim, você está certo. Está em você, Mona.[n][w][e]

[msg D_EXIT_GOTO_SAFE_PC08_me [Haru]]
[s]É verdade que devemos nos acalmar.[n][w][e]

[msg D_EXIT_GOTO_SAFE_PC09_me [Akechi]]
[s]Isso muito bem pode ser uma boa decisão.[n]Vá em frente.[n][w][e]

[msg D_EXIT_CANCEL_PC02_mes [Ryuji]]
[s][bup 0 2 0 65535 0]Mkay. Eu posso continuar indo para isso é[n]isso que você quer.[n][w][e]

[msg D_EXIT_CANCEL_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0]Sim, acho que podemos ganhar mais dinheiro[n]aqui.[n][w][e]

[msg D_EXIT_CANCEL_PC04_mes [Ann]]
[s][bup 0 4 0 65535 0]Ok, vamos olhar em volta aqui um pouco mais[n]do que.[n][w][e]

[msg D_EXIT_CANCEL_PC05_mes [Yusuke]]
[s][bup 0 5 0 65535 0]Concordo. Espero que ainda haja lugares[n]ainda não vistos.[n][w][e]

[msg D_EXIT_CANCEL_PC06_mes [Makoto]]
[s][bup 0 6 0 65535 0]HM, sim. Acho que ainda podemos continuar[n]por enquanto.[n][w][e]

[msg D_EXIT_CANCEL_PC07_mes [Futaba]]
[s]......[n][w][e]

[msg D_EXIT_CANCEL_PC08_mes [Haru]]
[s]......[n][w][e]

[msg D_EXIT_CANCEL_PC09_mes [Akechi]]
[s]......[n][w][e]

