[msg D10_BRIEFING_120_mes01 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3111 65535 0]O "tratamento" que a sombra nos contou...[n]alguém poderia realmente ficar feliz assim?[n][w][e]

[msg D10_BRIEFING_120_mes02 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Testemunhar em ação foi mais do que um pouco[n]perturbador...[n][w][e]

[msg D10_BRIEFING_120_mes03 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não importa a nossa opinião, isso não mudará[n]a maneira de pensar de Maruki.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8155 65535 0]A única coisa que podemos fazer é roubar seu[n]tesouro e induzir uma mudança de coração.[n][w][e]

