[msg D159_07_npc_01_mes01 [Masked Guest]]
[s]*risada* Olhando para esse cenário me faz[n]sentir realmente que sou um dos escolhidos.[n][w][e]

[msg D159_07_npc_02_mes01 [Masked Guest]]
[s]Oh querido, fiquei muito empolgado no salão[n]de entretenimento. Eu deveria esfriar aqui[n]por um tempo.[n][w][e]

[msg D159_07_npc_03_mes01 [Masked Guest]]
[s]Aquele homem tinha tantas tatuagens...[n]E seus maneirismos também eram bastante[n]absurdos...[n][w][e]
[s]Mas suponho que se ele estiver neste navio,[n]o Sr. Shido deve aceitá-lo...[n][w][e]

[msg D159_07_npc_04_mes01 [Bartender]]
[s]Bem vindo senhor. O convés traseiro é assim.[n][w][e]
[s]Atualmente, estamos em alerta especial, mas[n]não nos importamos. Por favor sinta-se em[n]casa.[n][w][e]

[msg D159_07_npc_05_mes01 [Bartender]]
[s]A sala de entretenimento está perto daqui.[n][w][e]
[s]Temos vários jogos lá, incluindo máquinas[n]caça-níqueis. Eu sugiro que você vá para lá[n]se estiver entediado.[n][w][e]

