[msg JULY_AZITO_TALK_01_mes01 [Ann]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Finalmente os exames acabaram...[n]estou exausto...[n][w][e]

[msg JULY_AZITO_TALK_01_mes02 [Ryuji]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Agora posso voltar a dormir em paz...[n][w][e]

[msg JULY_AZITO_TALK_01_mes03 [Makoto]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 3 0 0]Uh. Se você passou a noite acordado, deve ter[n]estudado muito.[n][w][e]

[msg JULY_AZITO_TALK_01_mes04 [Ryuji]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 1 0 0 4 0 0]Não, eu tenho jogado videogame.[n]Fazer preguiça é muito divertido...[n][w][e]

[msg JULY_AZITO_TALK_01_mes05 [Ann]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 1 0 0 5 0 0]Verdadeiro? Tudo o que fiz foi limpar[n]meu quarto em vez de estudar![n]Talvez agora esteja muito limpo...[n][w][e]

[msg JULY_AZITO_TALK_01_mes06 [Yusuke]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 6 0 0]Vocês dois são um exemplo perfeito[n]de escapismo.[n][w][e]

[msg JULY_AZITO_TALK_01_mes07 [Makoto]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 7 0 0]*suspiro* Só posso imaginar[n]qual será o resultado final.[n][w][e]

[msg JULY_AZITO_TALK_01_mes08 [Ryuji]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 8 0 0]Vabbeh, agora se foi.[n]Quem se importa agora?!?[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 9 0 0]Mais importante é a enorme[n]popularidade dos Phantom Thieves![n]Isso não é ótimo?!?[n][w][e]

[msg JULY_AZITO_TALK_01_mes09 [Ann]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 1 0 0 10 0 0]Parece que[n]é nossa hora![n][w][e]

[msg JULY_AZITO_TALK_01_mes10 [Yusuke]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 11 0 0]Eu ouvi transeuntes discutindo[n]animadamente sobre nosso próximo[n]alvo. Temos que escolher bem.[n][w][e]

[msg JULY_AZITO_TALK_01_mes11 [Makoto]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 12 0 0]Não há pressa.[n]Devemos levar algum[n]tempo para pensar sobre isso.[n][w][e]

[msg JULY_AZITO_TALK_01_mes12 [Ryuji]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 13 0 0]Espera, agora o mais[n]importante é a nossa festa![n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 14 0 0]Espero que você não[n]tenha esquecido. É o[n]festival de fogos de artifício no dia 18.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 15 0 0]Vejo você diretamente em[n]Shibuya, ok? Vamos fazer[n]às... 17h![n][w][e]

[msg JULY_AZITO_TALK_01_mes13 [Morgana]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 16 0 0]Claro que você está muito bem informado sobre[n]essas coisas...[n][w][e]

