[msg SHORTCUT_TEST_mes01]
[s]Teste [n][w][e]

[msg f_menu_txt]
[s]Para onde devo ir...?[n][e]

[msg train_txt]
[s]Para onde devo pegar o trem...?[n][e]

[sel TRAIN_mes top]
[s]Dirigir o trem [e]
[s]Cancelar [e]

[sel TRAIN_AOYAMA_mes top]
[s]Shibuya [e]
[s]Cancelar [e]

[sel TRAIN_SHIBUYA_DENEN_mes top]
[s]Yongen-Jaya [e]
[s]Cancelar [e]

[sel TRAIN_SHIBUYA_GINZA_mes top]
[s]Aoyama-Titchome [e]
[s]Cancelar [e]

[sel TRAIN_YONCHA_mes top]
[s]Shibuya [e]
[s]Cancelar [e]

[sel SCHOOL_MY_CLASS_mes top]
[s]Deixe a sala de aula [e]
[s]Deixe a escola [e]
[s]Telhado [e]
[s]Pátio [e]
[s]Praticar construção [e]

[sel SCHOOL_COURT_mes top]
[s]Edifício da sala de aula [e]
[s]Praticar construção [e]
[s]Cancelar [e]

[sel SCHOOL_ROOTTOP_mes top]
[s]Retornar ao campus [e]
[s]Cancelar [e]

[sel SCHOOL_OUTGATE_mes top]
[s]Entre na escola [e]
[s]Vá para a estação [e]
[s]Cancelar [e]

[sel SCHOOL_OUTGATE_OFF_mes top]
[s]Vá para a estação [e]
[s]Cancelar [e]

[sel SCHOOL_PASSAGE_KYOUSITU_ top]
[s]Deixe a escola [e]
[s]Minha sala de aula [e]
[s]Telhado [e]
[s]Pátio [e]
[s]Praticar construção [e]
[s]Cancelar [e]

[sel SCHOOL_PASSAGE_JISSYUU_m top]
[s]Deixe a escola [e]
[s]Edifício da sala de aula [e]
[s]Pátio [e]
[s]Cancelar [e]

[sel SIBUYA_OUT_FIELD_METRO_m top]
[s]Portão de ingressos de linha denen-toshi [e]
[s]Quadrado no nível do solo [e]
[s]Edifício da estação 2F [e]
[s]Edifício da estação 3F [e]
[s]Cancelar [e]

[sel SIBUYA_OUT_FIELD_GROUND_ top]
[s]Edifício da estação 3F [e]
[s]Edifício da estação 2F [e]
[s]Passagem subterrânea [e]
[s]Cancelar [e]

[sel SIBUYA_BLDG_FIELD_2F_mes top]
[s]Edifício da estação 3F [e]
[s]Quadrado no nível do solo [e]
[s]Passagem subterrânea [e]
[s]Cancelar [e]

[sel SIBUYA_BLDG_FIELD_3F_mes top]
[s]Ginza Line Ticket Gate [e]
[s]Edifício da estação 2F [e]
[s]Quadrado no nível do solo [e]
[s]Passagem subterrânea [e]
[s]Cancelar [e]

[sel YONCHA_ARCADE_mes top]
[s]Vá para a estação [e]
[s]Voltas de volta [e]
[s]Cancelar [e]

[sel YONCHA_ROJIURA_mes top]
[s]Arcade de compras [e]
[s]LeBlanc [e]
[s]Cancelar [e]

[sel MY_HOUSE_CAFE_mes top]
[s]Sair [e]
[s]Voltar para o próprio quarto [e]
[s]Cancelar [e]

[sel MY_HOUSE_ROOM_mes top]
[s]Para LeBlanc [e]
[s]Cancelar [e]

