[msg GMC_PASSCODE_EXIT_CHECK_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1057 65535 0]O que está acontecendo, Joker? Você tem que[n]pensar sobre isso um pouco?[n][w][e]

[sel YESNO_SEL top]
[s]Pensar[e]
[s]não reflita[e]

[msg e259_501_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vá com calma. No diário[n]está escrito: "[clr 2]R=C=0 I=1 H=2[clr 27]".[n][w][e]

[msg e259_501_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos tentar inserir os números[n]que formam R-I-C-H.[n][w][e]

