[msg Msg_NotOpen_moru [Morgana]]
[s][bup 0 3 1 0 0]É uma loja de Beef Bowl.[n]Cheira bem...[n][w][e]

[msg MSG_BAITO_NOTOPEN]
[s]Parece uma loja de uma[n]grande rede Beef Bowl Shop...[n][w][e]

[msg MSG_Beef_NoShift [Morgana]]
[s][bup 0 3 0 0 0]Huh? Você não tem[n]trabalho hoje, não é?[n][w][e]

[msg MSG_Beef_OKShift_1st [Morgana]]
[s][bup 0 3 0 0 0]Este é o Beef Bowl Shop[n]você ligou sobre um[n]trabalho de meio período, certo?[n][w][e]

[sel SEL_Beef1st_Q top]
[s]Já...[e]
[s]Isso não importa.[e]

[msg MSG_Beef_Start_1st [Morgana]]
[s][bup 0 3 1 0 0]Bom! Envolva-se com tudo, [f 4 2]![n][w][e]

[msg MSG_Beef_OKShift [Morgana]]
[s][bup 0 3 0 0 0]Você pode ir trabalhar hoje.[n]O que você está fazendo, você está indo?[n][w][e]

[sel SEL_Beef_Q top]
[s]Nós vamos trabalhar.[e]
[s]Trabalhamos outro dia.[e]

