[msg D05_BRIEFING_010_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu me pergunto como será o tesouro desse[n]lugar gigante.[n][w][e]

[msg D05_BRIEFING_010_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu esperaria que estivesse relacionado a[n]esses edifícios de alguma forma...[n][w][e]
[s]Mas não consigo imaginar o que isso poderia[n]acabar com o significado.[n][w][e]

[msg D05_BRIEFING_010_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Falando disso, o que é esses Buildin para de[n]qualquer maneira?[n][w][e]

[msg D05_BRIEFING_010_mes04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não tenho certeza. Isso é apenas outra coisa[n]que precisamos investigar.[n][w][e]

