[msg mini_EV_DOOR_LOCK03_mes0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]E o cartão de acesso anterior?[n]Pode funcionar.[n][w][e]

[msg mini_EV_DOOR_LOCK03_mes0_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perfeito, está aberto![n][w][e]

[msg mini_EV_DOOR_LOCK03_mes0_3 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Talvez também possamos usá-lo[n]em outros lugares.[n][w][e]

