[msg e380_300_mes01 [Voce meccanica]]
[s]Autenticação concluída.[n][w][e]
[s]Você pode acessar os[n]seguintes planos:[n][w][e]
[s]O plano padrão.[n]O plano exclusivo para membros.[n]O plano High Stakes.[n][w][e]

[msg e380_300_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6144 65535 0]Uh, a Gerência[n]continua fugindo...[n][w][e]

[msg e380_300_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas está tão perto que quase consigo sentir o[n]cheiro. Provavelmente ext será o último andar.[n][w][e]

[msg e380_300_mes04 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7186 65535 0]OK, vamos subir para o[n]piso de apostas altas![n][w][e]

