[msg D156_09_miniEV01_mes01 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espere, não é...[n][w][e]

[msg D156_09_miniEV01_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Um sensor infravermelho... encontramos a[n]mesma coisa no museu de Madarame.[n][w][e]

[msg D156_09_miniEV01_mes03 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O que diabos é algo assim nesta fábrica!?[n][w][e]

[msg D156_09_miniEV01_mes04 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hum... realmente existe na realidade também.[n]Disseram-me que é para manter o pessoal não[n]autorizado...[n][w][e]

[msg D156_09_miniEV01_mes05 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bem, acho que você não gostaria que as[n]pessoas vejam esse lugar... de qualquer[n]maneira, acho que podemos ignorá-lo por[n]enquanto.[n][w][e]

[msg D05_02_e341_081_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6019 65535 0]Ei, Joker...[n][w][e]

[msg D05_02_e341_081_mes02 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Há um elevador ali.[n]Você acha que poderíamos ir assim?[n][w][e]

[msg D05_02_e341_081_mes03 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]HM, é assim que aparece no mapa também...[n][w][e]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4180 65535 0]No entanto, com o sensor infravermelho, não[n]podemos prosseguir.[n][w][e]

[msg D05_02_e341_081_mes04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que podemos continuar assim que[n]pararmos a imprensa.[n][w][e]

[msg D05_02_e341_081_mes05 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espere um momento.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você não acha que esses robôs ali estão[n]agindo um pouco estranhos?[n][w][e]

[msg D05_02_e341_081_mes06 [???]]
[s]PELA EMPRESA! Para o nosso maravilhoso[n]presidente Okumura![n][w][e]
[s]Eu faço isso com alegria![n]Eu faço isso com alegria![n][w][e]

[msg D05_02_e341_081_mes07 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Eles ainda o respeitam, apesar de ver os[n]colegas de trabalho entrarem em colapso da[n]obtenção de sobrecarregados...[n][w][e]

[msg D05_02_e341_081_mes08 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]É controle da mente... Eles foram[n]propositadamente levados a um estado de[n]adaptação.[n][w][e]

[msg D05_02_e341_081_mes09 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sobre o que?[n][w][e]

[msg D05_02_e341_081_mes10 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4020 65535 0]Quando uma pessoa é continuamente[n]confrontada com a opressão, ela vêm para[n]dar as boas-vindas à sua presença.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esse truque psicológico está sendo usado[n]aqui. Eu... experimentei isso em primeira[n]mão por muitos anos.[n][w][e]

[msg D05_02_e341_081_mes11 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Raposa...[n][w][e]

[msg D05_02_e341_081_mes12 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3198 65535 0]Portanto, esses robôs existem porque o pai[n]está ciente de que está explorando seus[n]funcionários...[n][w][e]

[msg D05_02_e341_081_mes13 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sim. Deveríamos ter cuidado, no entanto.[n]Duvido que possamos nos comunicar com esses.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Provavelmente vamos direto para a batalha[n]quando nos aproximarmos deles. Eu sugiro[n]que você se prepare de antemão![n][w][e]

[msg D156_09_miniEV02_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Então esse é o nosso objetivo lá![n][w][e]

[msg D156_09_miniEV02_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2020 65535 0]Direita...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas sem parar a imprensa, acho que não[n]poderemos chegar lá.[n][w][e]

