[msg MND_PUB_TELEPHONE_YET]
[s]Aí está o telefone público.[n][w][e]
[s]Você não vê muitos desses telefones de[n]estilo rotativo.[n][w][e]

[msg MSG_PUB_TELEPHONE_YET [Morgana]]
[s][bup 0 3 0 0 0]Oh, um telefone rotativo? Bem, você não vê[n]algo assim com muita frequência hoje em dia.[n][w][e]

[msg MND_PUB_TELEPHONE]
[s]Aí está o telefone público.[n][w][e]
[s]Devo ligar para o serviço de entrega de[n]empregada?[n][w][e]

[msg MSG_PUB_TELEPHONE [Morgana]]
[s][bup 0 3 0 0 0]Se você ligar para o serviço de entrega de[n]empregada a partir daqui, não haverá[n]nenhuma evidência rastreando para você.[n][w][e]
[s]Então você iria ligar para o serviço de[n]entrega de empregada?[n][w][e]

[sel SEL_PUB_TELEPHONE top]
[s]Vamos chamar o serviço.[e]
[s]Não, não importa.[e]

[msg MND_PUB_TELEPHONE_NG]
[s]Aí está o telefone público.[n][w][e]
[s]Estou cansado hoje, então vou usar isso em[n]outra hora.[n][w][e]

[msg MSG_PUB_TELEPHONE_NG [Morgana]]
[s][bup 0 3 0 0 0]Você está cansado, certo? Você sempre pode[n]fazer telefonemas mais tarde. Vamos bater[n]no saco.[n][w][e]

[msg MSG_PHONE_DAY_TIME_NOT [Kawakami's Voice]]
[s]Hiii, isso é Becky![n][w][e]
[s]Sinto muito, mestre, mas estou de folga[n]agora.[n][w][e]
[s]Só posso servi-lo como sua empregada à noite.[n][w][e]
[s]Além disso, mais empregadas estão[n]disponíveis em [n][clr 2]Sexta e Sábado [clr 27], então tente ligar de volta em uma noite de[n]fim de semana.[n][w][e]

[msg MSG_PHONE_NIGHT_NOT [Kawakami's Voice]]
[s]Hiii, isso é Becky![n][w][e]
[s]Sinto muito, mestre, mas já estou[n]trabalhando duro agora.[n][w][e]
[s]Mais empregadas estão disponíveis em [clr 2]Sexta e Sábado [clr 27], então tente ligar de volta em uma noite de[n]fim de semana.[n][w][e]

[msg MSG_PHONE_NIGHT [Kawakami]]
[s][bup 0 109 0 65535 1]Hiii, isso é Becky![n][w][e]
[s]Oh... você realmente ligou. Obrigado.[n][w][e]
[s]Estou no trabalho agora, então custará 5.000[n]ienes. Você gostaria de me pedir para vir?[n][w][e]

[sel SEL_PHONE_NIGHT_CHECK top]
[s]É claro.[e]
[s]Talvez na próxima vez.[e]

[msg MSG_PHONE_NIGHT_OK [Kawakami]]
[s][bup 0 109 0 65535 1]Hehe, obrigado.[n][w][e]
[s]Eu estarei certo, Mestre.[n][w][e]

[msg MSG_PHONE_NIGHT_CANCEL [Kawakami]]
[s][bup 0 109 0 65535 1]Oh... bem, ligue novamente se precisar de[n]mim.[n][w][e]

[msg MND_PUB_TELEPHONE_OPEN]
[s]Aí está o telefone público.[n][w][e]
[s]Eu deveria tentar ligar para o número da[n]célula de trabalho de Kawakami...[n][w][e]

[msg MSG_PUB_TELEPHONE_OPEN [Morgana]]
[s][bup 0 3 0 0 0]É seguro ligar para o serviço de entrega de[n]empregada a partir daqui, pois não deixará[n]um recorde.[n][w][e]
[s]Você vai ligar para Kawakami?[n][w][e]

[msg MSG_COOP_NG [Kawakami's Voice]]
[s]Hiii, isso é Becky![n][w][e]
[s]Sinto muito, mestre, mas já estou[n]trabalhando duro agora.[n][w][e]
[s]Mais empregadas estão disponíveis em [clr 2]Sexta e Sábado [clr 27], então tente ligar de volta na noite da[n]aweekend.[n][w][e]

[msg MSG_COOP_NG_RANK_8 [Kawakami's Voice]]
[s]Hiii, isso é Becky! Estou de folga por um[n]whiiile.[n][w][e]
[s]Espero que você ligue de volta em breve![n][w][e]

[msg MSG_KAWAKAMI_CORP_C00_00 [Kawakami]]
[s][bup 0 109 0 65535 1]Hiii, mestre! Isso é Becky.[n][w][e]
[s]......[n][w][e]
[s]Oh, espere, é você...[n][w][e]
[s]... Sim, como você deve ter adivinhado, não[n]tenho clientes hoje à noite.[n][w][e]
[s]Você se importaria de me ligar?[n]Vou lhe dar a taxa de desconto de estudante[n]de 5.000 ienes.[n][w][e]

[msg MSG_KAWAKAMI_CORP_C01_00 [Kawakami]]
[s][bup 0 109 0 65535 1]Hiii, mestre! Obrigado por ligar.[n]Isso é Becky![n][w][e]
[s]Oh, espere, é você. Na verdade, estou muito[n]entediado hoje.[n][w][e]
[s]Será apenas 5.000 ienes se você quiser me[n]contratar. Você me ligaria?[n][w][e]

[msg MSG_KAWAKAMI_CORP_C02_00 [Kawakami]]
[s][bup 0 109 0 65535 1]Hiii, isso é Becky! Você está com fome,[n]mestre?[n][w][e]
[s]No momento, estamos oferecendo as opções[n]"Maid Cooking" e "junto com uma empregada"[n]de graça![n][w][e]
[s]São apenas 5.000 ienes por tudo isso e mais,[n]incluídos impostos incluídos. O que você[n]diz?[n][w][e]

[msg MSG_KAWAKAMI_CORP_C03_00 [Kawakami]]
[s][bup 0 109 0 65535 1]Hiii, isso é Becky![n][w][e]
[s]Oh, ei...[n][w][e]
[s]É o habitual 5.000 ienes, mas o menu[n]secreto...[n][w][e]
[s]Hum, posso lhe contar os preços do menu[n]secreto quando chegar lá.[n][w][e]

[msg MSG_KAWAKAMI_CORP_C04_00 [Kawakami]]
[s][bup 0 109 0 65535 1]Hiii, isso é Becky! Boa noite, mestre.[n][w][e]
[s]HM? Ah é você...[n][w][e]
[s]Então, o que você precisa?[n][w][e]

[msg MSG_KAWAKAMI_CORP_C05_00 [Kawakami]]
[s][bup 0 109 0 65535 1]Hiii, isso é Becky! É você, mestre?[n][w][e]
[s]Adivinha? Hoje, eu tenho um acordo especial[n]apenas para você![n][w][e]
[s]É apenas 5.000 ienes me solicitar, e tudo[n]está incluído. Então, o que você acha?[n][w][e]

[msg MSG_KAWAKAMI_CORP_C06_00 [Nurse]]
[s]Olá, este é o Hospital Aoyama.[n]Estou falando com [f 4 1]-san?[n][w][e]
[s]Kawakami-san entrou em colapso e ela foi[n]admitida em nosso hospital.[n][w][e]
[s]Ela é delirante, mas está chamando seu nome.[n]Você pode vir vê-la?[n][w][e]

[msg MSG_KAWAKAMI_CORP_C07_00 [Kawakami]]
[s][bup 0 109 0 65535 1]Hiii, isso é Becky! Eu estarei certo.[n]Tudo bem, Mestre?[n][w][e]
[s]Hum, eu vou jogar um monte de serviços de[n]bônus, então 5.000 ienes estão bem?[n][w][e]

[msg MSG_KAWAKAMI_CORP_C08_00 [Kawakami's Voice]]
[s]Hiii, isso é Becky! Estou de folga por um[n]whiiile.[n][w][e]
[s]Espero que você ligue de volta em breve![n][w][e]

[msg MSG_KAWAKAMI_CORP_C08_01 [Morgana]]
[s][bup 0 3 0 0 0]Temos um nome, então vamos para as[n]lembranças.[n][w][e]

[msg MSG_KAWAKAMI_CORP_C08_03 [Kawakami]]
[s][bup 0 109 0 65535 1]Hiii, isso é Becky![n][w][e]
[s]Espere, o que está acontecendo?[n][w][e]
[s]Há algumas coisas que eu quero perguntar,[n]então você vai me ligar, certo?[n][w][e]

[msg MSG_KAWAKAMI_CORP_C09_00 [Kawakami]]
[s][bup 0 109 0 65535 1]Oi! Ah é você.[n][w][e]
[s]No momento ideal. Eu tenho algo que eu[n]queria te dizer, então espere no seu quarto.[n][w][e]

[msg MSG_COOP_CHECK_NIGHT [Morgana]]
[s][bup 0 3 0 0 0]Vai custar 5.000 ienes. Você quer ligar para[n]Kawakami esta noite?[n][w][e]

[msg MSG_COOP_CHECK_RANK_6 [Morgana]]
[s][bup 0 3 0 0 0]Kawakami está no hospital!? Você vai[n]visitá-la?[n][w][e]

[sel SEL_COOP_CHK top]
[s]Vamos pedir uma massagem.[e]
[s]Vamos ligar para Kawakami.[e]
[s]Arcana de Kawakami...[e]
[s]Não, não importa.[e]

[sel SEL_COOP_CHK_RANK_6 top]
[s]Vamos pedir uma massagem.[e]
[s]Vamos visitar o hospital.[e]
[s]Arcana de Kawakami...[e]
[s]Não, não importa.[e]

[msg MSG_KAWAKAMI_COOP_CANCEL [Kawakami]]
[s][bup 0 109 0 65535 1]*suspiro*... tudo bem, acho que vou ter que[n]ligar para as pessoas e ver se alguém está[n]interessado.[n][w][e]
[s]Ah, e é melhor você levar seus estudos a[n]sério, ok?[n][w][e]

[msg MSG_KAWAKAMI_COOP_CANCEL_2 [Nurse]]
[s]Você é um membro da família, certo?[n]Por favor, venha aqui assim que puder.[n][w][e]
[s]Tudo bem, estaremos esperando por você.[n][w][e]

[msg MSG_KAWAKAMI_K_YES [Kawakami]]
[s][bup 0 109 0 65535 1]Vou pegar uma carona até lá agora, então[n]limpe seu quarto e espere por mim.[n][w][e]

[msg MSG_KAWAKAMI_K_YES_RANK1 [Kawakami]]
[s][bup 0 109 0 65535 1]Oh, você realmente vai me pedir?[n][w][e]
[s]Vou pegar uma carona até lá agora, então[n]limpe seu quarto e espere por mim.[n][w][e]

[msg MSG_KAWAKAMI_K_YES_RANK2 [Kawakami]]
[s][bup 0 109 0 65535 1]Ok! Obrigado por me solicitar.[n][w][e]
[s]Espero que você esteja com fome, mestre![n][w][e]

[msg MSG_KAWAKAMI_K_YES_RANK3 [Kawakami]]
[s][bup 0 109 0 65535 1]Eu estarei certo... espere por mim, ok?[n][w][e]

[msg MSG_KAWAKAMI_K_YES_RANK4 [Kawakami]]
[s][bup 0 109 0 65535 1]A sério!? Eu acho que você deve realmente[n]precisar de ajuda...[n][w][e]

[msg MSG_KAWAKAMI_K_YES_RANK5 [Kawakami]]
[s][bup 0 109 0 65535 1]Ok! Obrigado por me solicitar.[n][w][e]
[s]Vou pegar uma carona lá agora, então limpe[n]sua mesa e espere por mim.[n][w][e]

[msg MSG_KAWAKAMI_K_YES_RANK6 [Nurse]]
[s]OK. Você sabe onde está o hospital?[n]O número da sala é...[n][w][e]

[msg MSG_KAWAKAMI_K_YES_RANK7 [Kawakami]]
[s][bup 0 109 0 65535 1]Ok! Obrigado por me solicitar.[n][w][e]
[s]Vou pegar uma carona para lá, então prepare[n]um pouco de caneta e papel e espere por mim.[n][w][e]

[msg MSG_KAWAKAMI_K_YES_RANK8 [Kawakami]]
[s][bup 0 109 0 65535 1]Obrigado.[n][w][e]
[s]Eu estarei certo, então espere.[n][w][e]

[msg MSG_KAWAKAMI_K_YES_NEXTM [Kawakami]]
[s][bup 0 109 0 65535 1]Eu vou estar aí...[n][w][e]
[s]Vejo você em breve.[n][w][e]

[msg MSG_KAWAKAMI_F_YES_NEXTM [Kawakami]]
[s][bup 0 109 0 65535 1]Eu vou estar aí...[n][w][e]
[s]Vejo você em breve.[n][w][e]

[msg MSG_KAWAKAMI_SPOT_NAKANO [Kawakami]]
[s][bup 0 109 0 65535 1]Você conhece algum lugar que eu possa[n]aprender sobre a cultura Otaku?[n][w][e]
[s]Eu fui a Akihabara outro dia, então quero[n]conferir um novo lugar.[n][w][e]

[sel SEL_KAWAKAMI_SPOT_NAKANO top]
[s]Vamos para Nakano Broadway.[e]
[s]Apenas faça seu trabalho.[e]
[s]Eu não saberia.[e]

[msg MSG_KAWAKAMI_SPOT_NAKANO_2 [Kawakami]]
[s][bup 0 109 0 65535 1]Oh! Nakano! Eu ouvi falar dessa área.[n][w][e]
[s]my guide, Master~[n][w][e]

[msg MSG_KAWAKAMI_SPOT_NAKANO_3 [Kawakami]]
[s][bup 0 109 0 65535 1]Vamos dar uma olhada agora! Você pode ser[n]aw, não seja tão tenso...[n][w][e]

[msg MSG_KAWAKAMI_SPOT_NAKANO_4 [Kawakami]]
[s][bup 0 109 0 65535 1]Eu acho que isso faz sentido- você se mudou[n]para cá e tudo.[n][w][e]
[s]Ah bem. Acho que vou limpar hoje.[n][w][e]

[msg MSG_KAWAKAMI_SPOT_TUKISI [Kawakami]]
[s][bup 0 109 0 65535 1]Eu meio que quero sair e comer algo para[n]comemorar sair do hospital.[n][w][e]
[s]Alimentos de chapa ou algo parece bom.[n]Você tem alguma sugestão?[n][w][e]

[sel SEL_KAWAKAMI_SPOT_TUKISI top]
[s]Vamos pegar Monjayaki.[e]
[s]Apenas faça seu trabalho.[e]
[s]Não conheço bons lugares.[e]

[msg MSG_KAWAKAMI_SPOT_TUKISI_2 [Kawakami]]
[s][bup 0 109 0 65535 1]Oh, boa ideia! Tsukishima tem o melhor Monja.[n][w][e]
[s]É tão gentil da sua parte me tratar.[n]Vamos, mestre![n][w][e]

[msg MSG_KAWAKAMI_SPOT_TUKISI_3 [Kawakami]]
[s][bup 0 109 0 65535 1]Ah, não seja tão tenso...[n][w][e]

[msg MSG_KAWAKAMI_SPOT_TUKISI_4 [Kawakami]]
[s][bup 0 109 0 65535 1]Eu acho que isso faz sentido- você se mudou[n]para cá e tudo.[n][w][e]
[s]Ah bem. Acho que vou limpar hoje.[n][w][e]

[msg MSG_KAWAKAMI_SPOT_UENO_0 [Kawakami]]
[s][bup 0 109 0 65535 1]Por que não fazemos algumas lições[n]extracurriculares? Vamos testar seu sentido[n]artístico.[n][w][e]
[s]Leve-me a algum lugar agora.[n][w][e]

[sel SEL_KAWAKAMI_SPOT_UENO_0 top]
[s]Vamos para o Museu de Arte.[e]
[s]Volta para o trabalho.[e]
[s]Não conheço bons lugares.[e]

[msg MSG_KAWAKAMI_SPOT_UENO_0_2 [Kawakami]]
[s][bup 0 109 0 65535 1]O Museu de Arte em Ueno, hein?[n]Soa interessante.[n][w][e]
[s]Let's go, Master! ☆[n][w][e]

[msg MSG_KAWAKAMI_SPOT_UENO_0_3 [Kawakami]]
[s][bup 0 109 0 65535 1]Ah, não seja tão tenso...[n][w][e]

[msg MSG_KAWAKAMI_SPOT_UENO_0_4 [Kawakami]]
[s][bup 0 109 0 65535 1]Eu acho que isso faz sentido- você se mudou[n]para cá e tudo.[n][w][e]
[s]Ah bem. Acho que vou limpar hoje.[n][w][e]

[msg MSG_KAWAKAMI_SPOT_ODAIBA [Kawakami]]
[s][bup 0 109 0 65535 1]Ei, por que não saímos em algum lugar juntos?[n][w][e]
[s]Você deve pelo menos conhecer alguns bons[n]pontos de data, certo?[n][w][e]

[sel SEL_KAWAKAMI_SPOT_ODAIBA top]
[s]Vamos para Odaiba.[e]
[s]Eu prefiro você limpar.[e]
[s]Não conheço bons lugares.[e]

[msg MSG_KAWAKAMI_SPOT_ODAIBA_2 [Kawakami]]
[s][bup 0 109 0 65535 1]Ok, mastro- espere.[n][w][e]
[s]Vamos, [f 4 2].[n][w][e]

[msg MSG_KAWAKAMI_SPOT_ODAIBA_3 [Kawakami]]
[s][bup 0 109 0 65535 1]Ah, não seja tão tenso...[n][w][e]

[msg MSG_KAWAKAMI_SPOT_ODAIBA_4 [Kawakami]]
[s][bup 0 109 0 65535 1]Eu acho que isso faz sentido- você se mudou[n]para cá e tudo.[n][w][e]
[s]Ah bem. Acho que vou limpar hoje.[n][w][e]

[msg MND_COOP_DOUZOKUSEI]
[s]Eu deveria ser capaz de aprofundar nosso[n]vínculo, já que tenho [n][clr 1][var 5][clr 27][n]do [var 2]Arcana...[n][w][e]

[msg MSG_COOP_ABI_MORGANA [Morgana]]
[s][bup 0 3 0 0 0][vp 8 2 1 1084 65535 0]Se você aprofundar seu vínculo com Kawakami,[n]poderá usar seu tempo na escola e em casa[n]com mais eficiência.[n][w][e]

[msg MSG_COOP_RANKUP_OK [Morgana]]
[s][bup 0 3 0 0 0]Parece que algo especial pode acontecer hoje.[n][w][e]

[msg HELP_COOP_BONUS]
[s]Aumente o ranking confidente de Kawakami[n]para receber um bônus ao criar personas do[n]arcaana da temperança.[n][w][e]

[msg MSG_MONEY_NG_MORGANA [Morgana]]
[s][bup 0 3 0 0 0]Ei... você só tem [var 1]Yen.[n][w][e]
[s]Você não pode solicitar Kawakami com esse[n]valor.[n][w][e]

[msg MSG_MONEY_NG [Kawakami]]
[s][bup 0 109 0 65535 1]... Espere, você está amarrado por dinheiro!?[n][w][e]
[s]Bem, me ligue novamente depois de economizar[n]um pouco mais de dinheiro. Tchau.[n][w][e]

[msg MND_TELEPHONE_MASSAGE]
[s]Aí está o telefone público.[n][w][e]
[s]Como estou tão exausto, devo solicitar que[n]Kawakami me faça uma massagem...[n][w][e]

[msg MSG_TELEPHONE_MASSAGE [Morgana]]
[s][bup 0 3 0 0 0]É seguro ligar para o serviço de entrega de[n]empregada a partir daqui, pois não deixará[n]um recorde.[n][w][e]
[s]Se você está cansado, por que não pedir uma[n]massagem a Kawakami?[n][w][e]

[sel SEL_TELEPHONE_MASSAGE top]
[s]Eu quero uma massagem.[e]
[s]Não, não importa.[e]

[msg MSG_KAWAKAMI_MASSAGE [Kawakami]]
[s][bup 0 109 0 65535 1]Oh, você está solicitando seriamente uma[n]massagem...?[n][w][e]
[s]Ok, vou ir agora, então espere por mim.[n][w][e]

[msg MND_NOT_MASSAGE]
[s]Vou passar por enquanto.[n][w][e]

[msg MSG_NOT_MASSAGE [Morgana]]
[s][bup 0 3 0 0 0]Você não vai ligar para ela? Se você pode[n]massagear a fadiga, pode sair, sabe?[n][w][e]

[msg MSG_KAWAKAMI_SASOI_THROU [Kawakami]]
[s][bup 0 109 0 65535 1]Eu preciso trabalhar, sabe? Eu gostaria que[n]você me pedisse quando estiver livre.[n][w][e]

[msg MSG_KAWAKAMI_SASOI_THROU_2 [Kawakami]]
[s][bup 0 109 0 65535 1]Você faz o que quiser quando estiver na[n]aula, mas nunca ouve quando eu tenho um[n]pedido...[n][w][e]
[s]Quero dizer, você até me ignora quando falo[n]com você. Isso não é meio que significa?[n][w][e]

[msg MSG_KAWAKAMI_DOUBT_EVENT [Kawakami]]
[s][bup 0 109 0 65535 1]Isso pode demorar um pouco, mas podemos[n]conversar?[n][w][e]

[msg MSG_OOYA_DOUBT_HELLO [Kawakami]]
[s][bup 0 109 0 65535 1]Desculpe, estou ocupado agora.[n][w][e]
[s]E, enquanto sou grato a você... não posso ir[n]mais longe do que isso.[n][w][e]

[msg MSG_DOUBT_RELEASE_01 [Kawakami]]
[s][bup 0 109 0 65535 1]É minha culpa por ser enganada e deixá-lo[n]relaxar, já que não se encaixava, mas...[n]*suspiro * [n][w][e]

[msg MSG_DOUBT_RELEASE_02 [Morgana]]
[s][bup 0 3 0 0 0][vp 1 0 0 0 0 0]Uau, não é bom para os ladrões fantasmas se[n]você perder esse tempo livre na aula.[n][w][e]
[s]Espere, talvez ela suspeite que você esteja[n]brincando com outras garotas.[n]Deve ser isso...[n][w][e]
[s]Agora é a hora de jogar o fato de que você[n]está sozinho. Faça parecer que tudo o que[n]você faz é ler.[n][w][e]

[msg MSG_DOUBT_RELEASE_04 [Kawakami]]
[s][bup 0 109 0 65535 1]... Você tem certeza de que não misturou meu[n]número com uma de suas namoradas ou algo[n]assim?[n][w][e]

[msg MSG_DOUBT_RELEASE_05 [Morgana]]
[s][bup 0 3 0 0 0][vp 1 0 0 0 0 0]É hora de provar que você está sozinho.[n]Comece a falar sobre o que você tem lido nos[n]livros![n][w][e]

[msg MND_DOUBT_RELEASE_06]
[s]Vou provar que estou sozinho, trazendo à[n]tona o que tenho lido ultimamente.[n][w][e]

[msg MSG_DOUBT_RELEASE_07 [Kawakami]]
[s][bup 0 109 0 65535 1]W-Wait! Você está dizendo demais.[n]Estou ficando confuso.[n][w][e]
[s]Você leu seriamente o livro inteiro?[n]Quão entediado você está...?[n][w][e]
[s]Oh... é porque você geralmente está[n]sozinho...[n][w][e]
[s]R-right... Acho que eu entendi mal você...[n][w][e]

[msg MND_DOUBT_RELEASE_08]
[s]Parece que ela acreditava na minha mentira.[n][w][e]

[msg MSG_DOUBT_RELEASE_09 [Morgana]]
[s][bup 0 3 0 0 0][vp 1 0 0 0 0 0]Legal! Você conseguiu sair![n][w][e]

[msg MSG_DOUBT_RELEASE_10 [Kawakami]]
[s][bup 0 109 0 65535 1]Hum, então... você ia me pedir, certo?[n][w][e]

[msg MSG_BROKEN_01 [Kawakami]]
[s][bup 0 109 0 65535 1][vp 1 0 0 0 0 0]Não é um pouco tarde para tentar se[n]explicar, mestre?[n][w][e]
[s]... Você ainda vai tentar dizer que não tem[n]um lugar para pertencer?[n][w][e]

[msg MSG_BROKEN_02]
[s]Kawakami viu através da minha mentira...![n][w][e]

[msg MSG_BROKEN_03 [Kawakami]]
[s][bup 0 109 0 65535 1][vp 1 0 0 0 0 0]Você sabe... eu tentei esperar que você faça[n]uma desculpa. Mas você não fez nada.[n][w][e]
[s]Isso deve ter sido sobre o quanto você se[n]importava com o seu tempo livre.[n]Honestamente, é difícil para mim.[n][w][e]
[s]Então, isso significa que nosso acordo está[n]desligado.[n]E isso é final![n][w][e]

[msg MSG_BROKEN_04 [Kawakami]]
[s][bup 0 109 0 65535 1][vp 1 0 0 0 0 0]Então... adeus, mestre![n][w][e]

[msg MSG_BROKEN_05]
[s]Parece que é impossível reiniciar meu acordo[n]com Kawakami...[n][w][e]

[msg MSG_BROKEN_06 [Morgana]]
[s][bup 0 3 0 0 0]Isso é sem esperança. Você não será capaz de[n]reiniciar seu acordo com Kawakami.[n][w][e]
[s]É sua culpa por não tentar consertar as[n]coisas quando ela começou a duvidar de você.[n][w][e]
[s]Apenas desista já.[n][w][e]

[msg MSG_BROKEN_HELLOW [Kawakami]]
[s][bup 0 109 0 65535 1][vp 1 0 0 0 0 0]Oh, uh...[n][w][e]
[s]Oh, certo! Já estou totalmente reservado, na[n]verdade.[n][w][e]
[s]Espero vê-lo novamente em breve, mestre![n][w][e]

