[msg D08_01_e446_010_mes01 [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9114 65535 0]Huh? A luz sobre o chão é diferente daqueles[n]que vimos até agora...[n][w][e]

[msg D08_01_e446_017_mes01 [Futaba]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9105 65535 0]Ooh, ele se abriu! Esse é o nosso Joker![n][w][e]

[msg D08_01_e446_017_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas o que esses padrões no chão poderiam[n]significar...?[n][w][e]

[msg D08_01_e446_017_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tenho certeza de que descobri enquanto[n]estava assistindo... há uma limitação nessa[n]área.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você só pode alterar as cores até dez vezes.[n]Mais do que isso, e teremos que começar de[n]novo.[n][w][e]

[msg D08_01_e446_017_mes04 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6011 65535 0]Você resolveu um quebra-cabeça como esse em[n]sua primeira tentativa, Joker? Isso é[n]seriamente incrível![n][w][e]

