[msg D01_03_e161_020_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7024 65535 0]Somos dragões agora, para fugir daqui, hein?[n][w][e]

[msg D01_03_e161_021_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Ei, olhe! Isso não é...[n][w][e]

[msg D01_03_e161_021_mes02 [Ombra di Kamoshida]]
[s][bup 0 202 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Os intrusos do outro dia foram um entretenimento[n]aceitável.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]Mas eu não posso deixar[n]lixo saquear meu[n]castelo![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Reforce a segurança![n]Mate-os! Eu recompensarei quem[n]trouxer suas cabeças para mim.[n][w][e]

[msg D01_03_e161_021_mes03 [Soldado com Armadura]]
[s][vp 1 0 0 6 0 0]Louvado seja o Rei Kamoshida![n][w][e]

[msg D01_03_e161_021_mes04 [Soldado com Armadura]]
[s][vp 1 0 0 7 0 0]Morte aos intrusos![n][w][e]

[msg D01_03_e161_021_mes05 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 8 0 0]Oi Mona. Não poderíamos[n]simplesmente pisar nele bem[n]e acabar com isso?[n][w][e]

[msg D01_03_e161_021_mes06 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 9 0 0]Olha quantos soldados, idiota![n]Isso seria suicídio. Eu não acho que você[n]quer acabar como da última vez.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 10 0 0]Além disso, você não quer que ele confesse seus[n]pecados?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 11 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não adianta bater nele. Devemos[n]roubar a forma material[n]de seus desejos... O [clr 2]Tesouro[clr 27].[n][w][e]

[msg D01_03_e161_021_mes7 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 12 0 0]Bem. E onde?[n][w][e]

[msg D01_03_e161_021_mes8 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 13 0 0]Deve estar em algum lugar nas profundezas do[n]castelo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 14 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos mais fundo,[n]enquanto ele está por aí![n][w][e]

[msg D01_03_e161_312_AF_mes01 [Ombra di Kamoshida]]
[s][bup 0 202 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mate-os à primeira vista! Você entendeu!?![n][w][e]

[msg D01_03_e161_312_AF_mes02 [Soldado com Armadura]]
[s][vp 1 0 0 2 0 0]Louvado seja o Rei Kamoshida![n]Morte aos intrusos![n][w][e]

[msg D01_03_e161_312_AF_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1080 65535 0]Por enquanto não podemos entrar nesta sala.[n]Procuramos em outro lugar.[n][w][e]

[msg D01_03_LOCK_151_02_A_mes [Voce di soldato in armatura]]
[s][vp 1 0 0 2 0 0]Louvado seja o Rei Kamoshida![n]Morte aos intrusos![n][w][e]

[msg D01_03_LOCK_151_02_A_mes_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]Q-Que diabos!?![n][w][e]

