[msg D151_04_miniEV01_mes01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7021 65535 0]Vamos ver...[n]"A história de Kamoshida"...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"Nos passos de Kamoshida"...[n]"Heroic Kamoshida"...[n]"Lei de Kamoshida"...?[n][w][e]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Que diabos?!? Eles são todos[n]livros sobre Kamoshida![n][w][e]

[msg D151_04_miniEV01_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Agora que penso nisso, nós[n]encontramos um livro primeiro, certo?[n][w][e]

[sel D151_04_miniEV01_selA top]
[s]Você acha que tem algo a ver com isso?[e]
[s]Vamos tentar colocar aqui.[e]

[msg D151_04_miniEV01_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1157 65535 0]Sim, talvez colocando aqui[n]alguma coisa aconteça...[n][w][e]

[sel D151_04_miniEV01_selB top]
[s]O "Livro do Rei"[e]
[s]O "Livro da Rainha"[e]
[s]O "Livro do Escravo"[e]
[s]O "Livro do Ginásio"[e]
[s]Deixar[e]

[msg D151_04_miniEV01_ng_book [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1001 65535 0]Ah... Esse livro parece meio[n]pequeno... não cabe[n]como os outros.[n][w][e]

[msg D151_04_miniEV01_re_mes0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1133 65535 0]Esta estante está cheia[n]de livros sobre Kamoshida...[n][w][e]

[msg D151_04_miniEV01_recover [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Hum? Você quer pegá-lo de volta?[n][w][e]

[sel D151_04_miniEV01_selC top]
[s]Sim.[e]
[s]Melhor não.[e]

[msg D151_04_miniEV01_recover_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1035 65535 0]Sim, tentar os livros em[n]ordem diferente é uma boa ideia.[n]Então, qual é a próxima vez?[n][w][e]

[msg D151_04_miniEV01_none_me [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Oh...Ei, aqui está espaço[n]para outro livro.[n][w][e]

[msg D151_04_miniEV02_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6165 65535 0]Existem livros de todos os tipos aqui... Os[n]títulos não têm links específicos.[n][w][e]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hã? No título deste livro...[n]é o nome de Shiho...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espere um momento... Não só isso![n]Todos os livros nesta estante[n]são sobre alunas...![n][w][e]

[msg D151_04_miniEV02_mes02 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"Ann Takamaki: A[n]Boneca Charmosa". Vaca sagrada...[n][w][e]

[msg D151_04_miniEV02_mes03 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6190 65535 0]E que diabos é isso...?!?[n][w][e]

[msg D151_04_miniEV02_mes04 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]Ei, primeiro encontramos um livro, certo? Não[n]poderíamos usá-lo aqui?[n][w][e]

[sel D151_04_miniEV02_selA top]
[s]Usamos...?[e]
[s]Vamos colocar aqui.[e]

[msg D151_04_miniEV02_mes05 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7080 65535 0]Isso mesmo, colocando um[n]livro nessa estante,[n]algo pode acontecer...[n][w][e]

[sel D151_04_miniEV02_selB top]
[s]O "Livro do Rei"[e]
[s]O "Livro da Rainha"[e]
[s]O "Livro do Escravo"[e]
[s]O "Livro do Ginásio"[e]
[s]Deixar[e]

[msg D151_04_miniEV02_ng_book [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7192 65535 0]Ei, isso não é um pouco pequeno demais, não é?[n]Não se encaixa perfeitamente, vê?[n][w][e]

[msg D151_04_miniEV02_re_mes0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7038 65535 0]Há apenas[n]livros sobre alunas nesta estante...[n][w][e]

[msg D151_04_miniEV02_recover [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7088 65535 0]Hum? Você quer retirá-lo?[n][w][e]

[sel D151_04_miniEV02_selC top]
[s]Sim.[e]
[s]Melhor não.[e]

[msg D151_04_miniEV02_recover_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7186 65535 0]Sim, ok. Vamos tentar[n]outra maneira.[n][w][e]

[msg D151_04_miniEV02_none_me [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1159 65535 0]Uhm... Parece que entre esses[n]livros ainda tem um que[n]encaixa...[n][w][e]

[msg D151_04_miniEV03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1171 65535 0]Hum... Um momento. Os livros nesta estante[n]parecem familiares.[n][w][e]

[msg D151_04_miniEV03_mes02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]São os nomes dos membros[n]do time de vôlei![n][w][e]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espera, que diabos?!? Nos[n]títulos só tem meninos[n]da escola![n][w][e]

[msg D151_04_miniEV03_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"Ryuji Sakamoto: O Macaco[n]vulgar" . Isso é no Skull.[n][w][e]

[msg D151_04_miniEV03_mes04 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7047 65535 0]Que bastardo! Quem diabos ele[n]pensa que é?!?[n][w][e]

[msg D151_04_miniEV03_mes05 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6157 65535 0]Espere, não achamos um livro agora? E se...[n][w][e]

[sel D151_04_miniEV03_selA top]
[s]E se... o que?[e]
[s]Vamos colocá-lo na prateleira.[e]

[msg D151_04_miniEV03_mes06 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6035 65535 0]Sim, talvez colocando na prateleira algo aconteça.[n][w][e]

[sel D151_04_miniEV03_selB top]
[s]O "Livro do Rei"[e]
[s]O "Livro da Rainha"[e]
[s]O "Livro do Escravo"[e]
[s]O "Livro do Ginásio"[e]
[s]Deixar[e]

[msg D151_04_miniEV03_ng_book [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6118 65535 0]Esse livro não parece um pouco pequeno demais[n]para você? Deixe espaço.[n][w][e]

[msg D151_04_miniEV03_re_mes0 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6127 65535 0]Nesta estante há apenas[n]livros sobre os alunos do sexo masculino[n]da escola...[n][w][e]

[msg D151_04_miniEV03_recover [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6001 65535 0]Você quer pegar aquele[n]livro de novo?[n][w][e]

[sel D151_04_miniEV03_selC top]
[s]Sim.[e]
[s]Melhor não.[e]

[msg D151_04_miniEV03_recover_2 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6108 65535 0]Concordar! Vamos tentar[n]outro pedido.[n][w][e]

[msg D151_04_miniEV03_none_me [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Que diabos? Parece que[n]um livro está faltando aqui.[n][w][e]

[msg D151_04_miniEV06_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]...Hã? Encontrei algo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"Glory in the Muscles"...[n]"Muscleland"...[n][w][e]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7119 65535 0]Deus, parece que estou na têmpora do bíceps.[n]'Esse cara é obcecado por seus músculos...[n][w][e]

[msg D151_04_miniEV06_mes02 [Ann]]
[s][bup 0 4 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6197 65535 0]...Nojento.[n][w][e]

[sel D151_04_miniEV06_selB top]
[s]O "Livro do Rei"[e]
[s]O "Livro da Rainha"[e]
[s]O "Livro do Escravo"[e]
[s]O "Livro do Ginásio"[e]
[s]Deixar[e]

[msg D151_04_miniEV06_choice_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7088 65535 0]Você quer colocar o livro lá?[n][w][e]

[msg D151_04_miniEV06_choice__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1171 65535 0]Então você quer tentar deslizar[n]o livro lá?[n][w][e]

[msg D151_04_miniEV06_choice__3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmh... Eu me pergunto se seremos capazes de[n]encontrar um livro que corresponda[n]por aqui.[n][w][e]

[msg D151_04_miniEV06_re_mes0 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7106 65535 0]Oh, a prateleira de músculos...[n][w][e]

[msg D151_04_miniEV06_none_me [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1171 65535 0]Parece que falta[n]um livro aqui também.[n][w][e]

[msg D151_04_miniEV07_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7174 65535 0]Hã? Tudo bem?[n][w][e]

[msg D151_04_miniEV07_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6166 65535 0]Talvez haja algo preso lá[n]dentro. Por que você não tenta[n]enfiar a mão, Skull?[n][w][e]

[msg D151_04_miniEV07_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ei! Tem alguma coisa aqui![n]...Aqui estamos.[n][w][e]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh fixe. Aqui, todo seu.[n][w][e]

[msg D151_04_miniEV07_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1175 65535 0]Sem botões secretos, mas[n]conseguimos algo de qualquer maneira ...[n]Ainda é uma vitória![n][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E um agradecimento extra ao[n]Joker, que vasculhou esta sala de cima a baixo![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Continue assim enquanto avançamos pelo[n]Palácio, ok? Vamos,[n]vamos continuar com a infiltração![n][w][e]

[msg D151_04_miniEV08_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6139 65535 0]Duvido que esse livro seja bom.[n][w][e]

[msg D151_04_miniEV08_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Deve ser um pouco[n]menor, certo? Não temos[n]um livro desse tamanho?[n][w][e]

[msg D151_04_miniEV08_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6127 65535 0]Então vamos precisar de um livro[n]menor que todos[n]que temos aqui, hein?[n][w][e]

[msg D151_04_miniEV10_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]Vamos ignorar esse livro por enquanto...[n]Não é o tamanho certo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se ao menos tivéssemos outro livro[n]do tamanho certo...[n][w][e]

