[msg D06_12_e382_250_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O balcão não está ali? Ainda não conseguimos[n]nossas moedas![n][w][e]

[msg D06_12_e382_250_mes02 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Onde você está indo? Ainda temos que receber[n]nossas moedas.[n][w][e]

[msg D06_12_e382_250_mes03 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ainda não obtivemos nossas moedas![n]Venha, vamos falar com o atendente no balcão.[n][w][e]

