[msg MES_GROUP0_01 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 54701 65535 0]Honestamente, eu não sabia se conseguiríamos,[n]mas... estou feliz por termos aguentado.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Se tivéssemos perdido... o mundo[n]teria acabado.[n][w][e]

[msg MES_GROUP0_02 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 2035 65535 0]Estou convencido de que nosso[n]líder foi o elemento[n]chave para o sucesso.[n][w][e]

[msg MES_GROUP0_03 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 36 10 0 10][vp 8 2 1 9191 65535 0]E Mona também! Esses dois[n]são os verdadeiros MVPs![n][w][e]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ou é chamado de MVP... e MVC?[n][w][e]

[msg MES_GROUP1_01 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 40 10 0 10][vp 8 2 1 2193 65535 0]Não pensei que iríamos derrotar[n]um deus... nascido dos desejos distorcidos[n]das massas, afinal.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vamos torcer para que as pessoas deste mundo[n]não queiram mais ser comandadas[n]uma varinha.[n][w][e]

[msg MES_GROUP1_02 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 3194 65535 0]Não vamos deixar ninguém[n]pensar que é certo[n]destruir o mundo.[n][w][e]

[msg MES_GROUP2_01 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 4088 65535 0]Mesmo o público mais impassível decidiu apoiar os[n]Phantom Thieves...[n][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Esse é um momento que não será esquecido tão cedo.[n][w][e]

[msg MES_GROUP2_02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 42 10 0 10][vp 8 2 1 7024 65535 0]Absolutamente.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu odeio o fato de que a opinião de[n]pessoas sobre nós[n]sempre foi incerta...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas tenho que admitir que é bom saber que eles[n]estão do nosso lado.[n][w][e]

[msg MES_GROUP4_01 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 23 1 65535 32 10 0 10][vp 8 2 1 11001 65535 0]Esses humanos[n]geraram um deus maligno,[n]e então viraram as costas para ele...[n][w][e]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Que elementos problemáticos. Não foi[n]fácil mantê-los na linha reta.[n][w][e]

[msg MES_GROUP4_02 [Justine]]
[s][bup 0 101 1 0 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 12020 65535 0]Mas, estranhamente, não me importo.[n]Talvez seja essa luta constante[n]que torna os humanos fascinantes.[n][w][e]

[msg MES_GROUP4_03 [Caroline]]
[s][bup 0 102 3 0 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 11101 65535 0]Entendo...[n][w][e]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Esse deve ser o famoso "amor[n]esforço" de que falam os humanos.[n][w][e]

[msg MES_GROUP4_04 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 55205 65535 0]Sim... Talvez os esforços feitos pelo[n]Prisioneiro tenham nos feito[n]gostar dele.[n][w][e]

[msg MES_GROUP4_05 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 11064 65535 0]Talvez você esteja certo...[n][w][e]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Isso nos causou alguns[n]problemas, mas no geral...[n]não foi ruim.[n][w][e]

[msg MES_GROUP5_01 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 55477 65535 0]Morgana... Derrotar o Deus do Controle e eliminar[n]os Mementos poderia ter feito você desaparecer.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Você estava ciente disso desde o início?[n][w][e]

[msg MES_GROUP5_02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 65535 3 10 0 10]Bem... Sim, era uma possibilidade.[n][w][e]

[msg MES_GROUP5_03 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 55475 65535 0]Eu suspeitei. Então, por que você decidiu[n]continuar? O que lhe deu a força para lutar?[n][w][e]

[msg MES_GROUP5_04 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 1112 65535 0]Difícil dizer. Eu não tinha pensado muito sobre[n]isso.[n][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Fiz o que pude para salvar a humanidade. Para[n]salvá-los. No final, isso era tudo que eu queria.[n][w][e]

[msg MES_GROUP5_05 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 65535 3 10 0 10]Então, ao invés de agir[n]calculado, você preferiu[n]ouvir o coração...[n][w][e]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 2 1 55458 65535 0]Essa é uma ótima resposta, Morgana.[n][w][e]

[msg MES_GROUP6_01 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 6019 65535 0]Eu sei que treinamos os Phantom Thieves com um[n]objetivo bastante ambicioso ...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas eu não tinha ideia de que teríamos que lutar[n]contra um deus.[n][w][e]

[msg MES_GROUP6_02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 7079 65535 0]É verdade. Se alguém[n]tivesse me contado, eu teria respondido que[n]ele havia comido seu cérebro.[n][w][e]

[msg MES_GROUP6_03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 65535 3 10 0 10]No entanto, foi assim que aconteceu.[n][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]E nós também ganhamos![n][w][e]

[msg MES_GROUP6_04 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 36 10 0 10][vp 8 2 1 7048 65535 0]Oh sim![n][w][e]

[msg MES_GROUP7_01 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 40 10 0 10][vp 8 2 1 54202 65535 0]Sabe... eu também estava me perguntando isso...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quando aquele sujeito assustador[n]se transformou no Santo Graal,[n]ele abriu os braços rindo.[n][w][e]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ele... bem... ainda está lá?[n]De pé em uma grande taça,[n]com os braços levantados?[n][w][e]

[msg MES_GROUP7_02 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 23 1 65535 41 10 0 10][vp 8 2 1 4129 65535 0]......[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Agora que você mencionou, é uma ideia bem bizarra.[n][w][e]

[msg MES_GROUP7_03 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 2199 65535 0]Vou fingir que não ouvi.[n][w][e]

