[msg MSG_INFO_AWARD]
[s]You've obtained a new award.[n][w][e]

[msg MSG_INFO_TRANSFORM]
[s]A new type of Transformation Tile[n]was added.[n][w][e]

[msg MSG_INFO_GET_MEDAL]
[s]You received a P Medal.[n]Please enjoy Thieves Den.[n][w][e]

[msg MSG_INFO_UPDATE1 [An item was added to the content below.]]
[s] [var 0] [n][w][e]

[msg MSG_INFO_UPDATE2 [An item was added to the contents below.]]
[s] [var 0] [n] [var 1] [n][w][e]

[msg MSG_INFO_UPDATE3 [An item was added to the contents below.]]
[s] [var 0] [n] [var 1] [n] [var 2] [n][w][e]

[msg MSG_INFO_UPDATE4 [An item was added to the contents below.]]
[s] [var 0] [n] [var 1] [n] [var 2] [n] [var 3] [n][w][e]

