[msg MSG_BUY]
[s]Comprar este filme?[n][e]

[msg MSG_000]
[s]Introdução Vídeo para Persona 5.[n][e]

[msg MSG_001]
[s]Introdução Vídeo para Persona 5 Royal.[n][e]

[msg MSG_002]
[s]O protagonista choca a multidão correndo[n]pelo cassino, zombando do caos abaixo.[n][e]

[msg MSG_003]
[s]Depois de arrancar a máscara da guarda de[n]segurança que virou sombra, ela mostra seu[n]verdadeiro eu e ataca![n][e]

[msg MSG_004]
[s]Como o protagonista é cercado por sombras,[n]uma jovem em uma máscara aparece diante[n]dele...[n][e]

[msg MSG_005]
[s]Enquanto o protagonista tenta fazer sua[n]grande fuga, ele é emboscado e preso.[n][e]

[msg MSG_006]
[s]Após sua prisão, o protagonista é informado[n]das acusações contra ele com uma surra[n]brutal.[n][e]

[msg MSG_007]
[s]O protagonista lembra seu passado no trem[n]para Shibuya, onde ele experimenta algo[n]bizarro.[n][e]

[msg MSG_008]
[s]O protagonista acorda para se encontrar em[n]uma cela e conhece Igor, um velho[n]assustador.[n][e]

[msg MSG_009]
[s]Igor prevê a ruína do protagonista e[n]questiona sua determinação em assumir as[n]distorções do mundo.[n][e]

[msg MSG_010]
[s]Um promotor discute a cadeia de incidentes[n]inexplicáveis e é visitado por um certo[n]jovem.[n][e]

[msg MSG_011]
[s]Por uma loja, o protagonista encontra uma[n]beleza de olhos azuis abrigo da chuva.[n][e]

[msg MSG_012]
[s]No caminho para a escola, Ryuji e o[n]protagonista acabam em um lugar que parece[n]um castelo.[n][e]

[msg MSG_013]
[s]Enquanto o protagonista se sente impotente[n]para ajudar Ryuji, uma borboleta azul[n]aparece com uma voz enigmática...[n][e]

[msg MSG_014]
[s]contract and summoning Arsène.[n][e]

[msg MSG_015]
[s]O protagonista encontra suas convicções,[n]formando assim um partido que foge de[n]Kamoshida, mas à medida que mais sombras[n]atacam, Morgana convoca sua própria persona.[n][e]

[msg MSG_016]
[s]A festa usa o navegador Metaverse para se[n]aventurar de volta ao antigo castelo.[n][e]

[msg MSG_017]
[s]Com seu amigo é perigo, Ryuji forma um[n]contrato com sua voz interior e convoca o[n]capitão Kidd.[n][e]

[msg MSG_018]
[s]Uma manifestação de vôlei entre estudantes e[n]professores dá errado.[n][e]

[msg MSG_019]
[s]Ann confessa ser abusada por Kamoshida em[n]troca da posição de sua amiga na equipe.[n][e]

[msg MSG_020]
[s]Tendo atingido seu limite, Ann forma um[n]contrato com sua voz interior e convoca[n]Carmen.[n][e]

[msg MSG_021]
[s]Como Kamoshida admite a derrota, Ann chega a[n]uma decisão importante.[n][e]

[msg MSG_022]
[s]Os ladrões Phantom se esforçam para escapar[n]do antigo castelo quando ele começa a[n]desmoronar.[n][e]

[msg MSG_023]
[s]Ann diz que sente que está sendo vigiada. Os[n]três eclodiram um plano para pegar o[n]agressor.[n][e]

[msg MSG_024]
[s]Yusuke percebe a verdade sobre Madarame. Com[n]olhos afiados, ele forma um contrato com[n]Goemon.[n][e]

[msg MSG_025]
[s]Com sua verdadeira natureza exposta,[n]Madarame atacou os ladrões fantasmas.[n][e]

[msg MSG_026]
[s]Decidindo participar de seu falso eu, Makoto[n]forma um contrato com sua voz interior e[n]convoca Johanna.[n][e]

[msg MSG_027]
[s]Com sua verdadeira natureza exposta,[n]Kaneshiro ataca contra os ladrões fantasmas.[n][e]

[msg MSG_028]
[s]A festa está a caminho do festival de fogos[n]de artifício quando o evento é[n]repentinamente cancelado devido à chuva.[n][e]

[msg MSG_029]
[s]Enquanto os ladrões fantasmas atravessam o[n]deserto no carro Morgana, eles vêem algo...[n][e]

[msg MSG_030]
[s]O partido é atacado pela semelhança da mãe[n]de Futaba, nascida de sua cognição[n]distorcida.[n][e]

[msg MSG_031]
[s]Depois de encontrar a verdade em suas[n]ilusões, Futaba forma um contrato com[n]Necronomicon.[n][e]

[msg MSG_032]
[s]O pensamento rápido de Ann salva o dia à[n]medida que os ladrões fantasmas escapam do[n]palácio implodente.[n][e]

[msg MSG_033]
[s]À medida que o fim das férias de verão se[n]aproxima, a festa decide chegar à praia.[n][e]

[msg MSG_034]
[s]O protagonista e os amigos estão animados[n]por estar no Havaí para a viagem escolar.[n][e]

[msg MSG_035]
[s]O diretor decide ir para a delegacia, mas as[n]coisas dão uma virada estranha no caminho[n]para lá...[n][e]

[msg MSG_036]
[s]O partido entra em um palácio misterioso que[n]parece ter aparecido do nada.[n][e]

[msg MSG_037]
[s]Irritado pelas palavras da sombra, Kasumi[n]forma um contrato e convoca Cendrillon.[n][e]

[msg MSG_038]
[s]Enquanto Haru decide se separar de seu pai,[n]seu verdadeiro despertar revela poderes[n]invisíveis.[n][e]

[msg MSG_039]
[s]Okumura é encurralado pelos ladrões Phantom.[n]O confronto começa...[n][e]

[msg MSG_040]
[s]Okumura muda de coração, mas algo dá errado[n]durante sua conferência de imprensa...[n][e]

[msg MSG_041]
[s]Kasumi Awes, espectadores com sua dança na[n]festa pós-festival.[n][e]

[msg MSG_042]
[s]Os ladrões Phantom invadem o palácio de[n]Niijima para encontrar um cassino chamativo.[n][e]

[msg MSG_043]
[s]Makoto, perturbada pela próxima batalha,[n]convoca a coragem de enfrentar sua irmã.[n][e]

[msg MSG_044]
[s]Tendo já matado um policial de plantão,[n]Akechi aponta sua arma para o[n]protagonista...[n][e]

[msg MSG_045]
[s]Akechi faz a morte do protagonista parecer[n]um suicídio antes de fugir da cena.[n][e]

[msg MSG_046]
[s]As notícias do suicídio do protagonista[n]lança uma nuvem negra sobre a festa.[n]Mas então...[n][e]

[msg MSG_047]
[s]O protagonista parecia estar morto... mas[n]esse engano era o plano o tempo todo.[n][e]

[msg MSG_048]
[s]Os ladrões Phantom ficam sem palavras ao ver[n]o palácio de Shido.[n][e]

[msg MSG_049]
[s]Akechi revela seu verdadeiro eu e fica[n]furioso contra os ladrões fantasmas.[n][e]

[msg MSG_050]
[s]Os ladrões Phantom retiram seu maior golpe[n]ainda entregando um cartão de visita a[n]Shido.[n][e]

[msg MSG_051]
[s]A fatídica batalha entre Shido e os ladrões[n]fantasmas está prestes a começar...[n][e]

[msg MSG_052]
[s]À medida que o navio de cruzeiro afunda,[n]Ryuji arrisca sua vida garantindo um barco[n]salva-vidas para a equipe.[n][e]

[msg MSG_053]
[s]Através do poder do Santo Graal, as[n]lembranças começam a se fundir no mundo[n]real...[n][e]

[msg MSG_054]
[s]À medida que o mundo real e as lembranças se[n]fundem, os ladrões fantasmas desaparecem da[n]cognição do público.[n][e]

[msg MSG_055]
[s]Os guardas gêmeos, superando a vontade[n]malévola que os dividem, são fundidos[n]novamente...[n][e]

[msg MSG_056]
[s]O Santo Graal, espancado pelos ladrões[n]fantasmas, se liberta para revelar sua[n]verdadeira forma...[n][e]

[msg MSG_057]
[s]Quando Mishima aplaude os ladrões Phantom,[n]todos ao seu redor começam a se juntar.[n][e]

[msg MSG_058]
[s]O apoio aos ladrões Phantom continua a se[n]espalhar...[n][e]

[msg MSG_059]
[s]As vozes daqueles que acreditam nos ladrões[n]fantasmas se tornam uma força própria.[n][e]

[msg MSG_060]
[s]Arsène evolves into Satanael.[n][e]

[msg MSG_061]
[s]Com as orações das massas, Satanael dispara[n]sua concha pecaminosa, penetrando[n]Yaldabaoth.[n][e]

[msg MSG_062]
[s]As distorções na realidade desaparecem, e o[n]mundo começa a retornar à maneira como era[n]uma vez.[n][e]

[msg MSG_063]
[s]Sobre a multidão de shibuya, a equipe[n]resolve resgatar o protagonista.[n][e]

[msg MSG_064]
[s]O protagonista é encontrado inocente e[n]liberado do Juvenile Hall, onde Sojiro vem[n]buscá-lo.[n][e]

[msg MSG_065]
[s]O protagonista retorna, para o alívio de[n]seus companheiros de equipe.[n][e]

[msg MSG_066]
[s]Os ladrões Phantom partiram para novos[n]horizontes.[n][e]

[msg MSG_067]
[s]あいうえお[n]かきくけこ[n][e]

[msg MSG_068]
[s]067 Enquanto caminhava por Shibuya, o[n]protagonista encontra algo incomum.[n][e]

[msg MSG_069]
[s]Enquanto visitava o santuário com Kasumi[n]para o ano novo, o protagonista encontra[n]seus amigos.[n][e]

[msg MSG_070]
[s]A verdade é revelada quando a tragédia de[n]Kasumi e Sumire vem à luz.[n][e]

[msg MSG_071]
[s]O protagonista rejeita a proposta de Maruki[n]para uma realidade impecável.[n][e]

[msg MSG_072]
[s]Sumire, cego por seu desejo de uma realidade[n]melhor, é capacitado por Maruki.[n][e]

[msg MSG_073]
[s]Partindo com sua própria fraqueza, Sumire[n]tem um verdadeiro despertar e convoca[n]Cendrillon mais uma vez.[n][e]

[msg MSG_074]
[s]Os ladrões fantasmas fogem do palácio em[n]colapso de Maruki no carro Morgana.[n][e]

[msg MSG_075]
[s]Para satisfazer seu próprio conceito de[n]felicidade, Maruki evolui sua própria[n]persona.[n][e]

[msg MSG_076]
[s]Encurdado pelos ladrões fantasmas, Maruki se[n]funde com sua persona e fica ainda mais[n]forte.[n][e]

[msg MSG_077]
[s]Enquanto seus aliados separam o ataque de[n]Maruki, o protagonista dispara o tiro final.[n][e]

[msg MSG_078]
[s]Morgana se torna um helicóptero e a equipe[n]pega uma carona enquanto tentam escapar...[n][e]

[msg MSG_079]
[s]Enquanto Maruki aceita sua própria morte, o[n]protagonista estende a mão.[n][e]

[msg MSG_080]
[s]Com seus próprios caminhos escolhidos, o[n]protagonista e seus amigos dão seus[n]próximos passos no futuro.[n][e]

[msg MSG_081]
[s]Quando ele parte, o protagonista reflete[n]sobre sua vida.[n][e]

[msg MSG_082]
[s]Com uma promessa em seu coração, o[n]protagonista parte em um novo caminho.[n][e]

[msg MSG_083]
[s]Persona 5 A animação The Day Breakers[n]abrindo filme [n][e]

[msg MSG_084]
[s]Persona 5 A Animação O Trailer do Day[n]Breakers [n][e]

[msg MSG_085]
[s]Persona 5 Trailer No. 1 [n][e]

[msg MSG_086]
[s]Persona 5 Trailer No. 2 [n][e]

[msg MSG_087]
[s]Persona 5 Trailer No. 3 [n][e]

[msg MSG_088]
[s]Persona Music FES 2013 em Nippon Budokan [n][e]

[msg MSG_089]
[s]Persona Music FES 2013 em Nippon Budokan [n][e]

[msg MSG_090]
[s]Persona Music FES 2013 em Nippon Budokan [n][e]

[msg MSG_091]
[s]Persona Super Live 2015 em Nippon Budokan-[n]Night of the Phantom- [n][e]

[msg MSG_092]
[s]Persona Super Live 2015 em Nippon Budokan-[n]Night of the Phantom- [n][e]

[msg MSG_093]
[s]Persona Super Live 2015 em Nippon Budokan-[n]Night of the Phantom- [n][e]

[msg MSG_094]
[s]Persona Super Live 2017 [n][e]

[msg MSG_095]
[s]Persona Super Live 2017 [n][e]

[msg MSG_096]
[s]Persona Super Live 2017 [n][e]

[msg MSG_097]
[s]O protagonista optou por permanecer na[n]realidade projetada por Maruki.[n][e]

[msg MSG_098]
[s]Showtime: Panther e Mona [n][e]

[msg MSG_099]
[s]Showtime: Queen and Skull [n][e]

[msg MSG_180]
[s]Showtime: Skull e Fox [n][e]

[msg MSG_101]
[s]Showtime: Fox e Pantera [n][e]

[msg MSG_102]
[s]Showtime: Mona e Noir [n][e]

[msg MSG_103]
[s]Showtime: noir e rainha [n][e]

[msg MSG_104]
[s]Showtime: Crow and Joker [n][e]

[msg MSG_105]
[s]Showtime: Violet e Joker [n][e]

[msg MSG_106]
[s]あいうえお[n]かきくけこ[n][e]

[msg MSG_107]
[s]あいうえお[n]かきくけこ[n][e]

[msg MSG_108]
[s]あいうえお[n]かきくけこ[n][e]

[msg MSG_109]
[s]あいうえお[n]かきくけこ[n][e]

