[sel charaorder_se top]
[s]Sim [e]
[s]Não [e]

[msg charaorder_Hero_00]
[s]Precisamos expor seus truques.[n]Devo enviar alguém para fazer isso...?[n][w][e]

[msg charaorder_Hero_01]
[s]Fictício [n][w][e]

[msg charaorder_Hero_02]
[s]Fictício [n][w][e]

[msg charaorder_Reiji_00 [Ryuji]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1030 0 2]Não queremos deixá-la continuar nos[n]enganando, certo?[n][w][e]

[msg charaorder_Reiji_01 [Ryuji]]
[s][vp 8 0 2 1037 0 2]Eu posso ir sempre que.[n][w][e]

[msg charaorder_Reiji_02 [Ryuji]]
[s][vp 8 0 2 1044 0 2]Deixe para mim![n][w][e]

[msg charaorder_Morgana_00 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1031 0 3]Joker, escolha alguém para enviar![n][w][e]

[msg charaorder_Morgana_01 [Morgana]]
[s][vp 8 0 2 1038 0 3]Vou mostrar minha precisão perfeita![n][w][e]

[msg charaorder_Morgana_02 [Morgana]]
[s][vp 8 0 2 1045 0 3]Estou desligado![n][w][e]

[msg charaorder_Ann_00 [Ann]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1032 0 4]Temos que parar isso.[n][w][e]

[msg charaorder_Ann_01 [Ann]]
[s][vp 8 0 2 1039 0 4]Você quer que eu faça isso...? Ok, eu vou[n]dar tudo de mim.[n][w][e]

[msg charaorder_Ann_02 [Ann]]
[s][vp 8 0 2 1046 0 4]Ok, Joker![n][w][e]

[msg charaorder_Yugo_00 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 5]Como ela se atreve a fazer tão tolos de[n]nós...[n][w][e]

[msg charaorder_Yugo_01 [Yusuke]]
[s][vp 8 0 2 1040 0 5]Eu vou? Bem, vou tentar o meu melhor.[n][w][e]

[msg charaorder_Yugo_02 [Yusuke]]
[s][vp 8 0 2 1047 0 5]Muito bem. Mantenha-se firme.[n][w][e]

[msg charaorder_Makoto_00 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1034 0 6]Devemos parar minha irmã...[n][w][e]

[msg charaorder_Makoto_01 [Makoto]]
[s][vp 8 0 2 1041 0 6]Enquanto eu chegar perto, até essa arma deve[n]funcionar...[n][w][e]

[msg charaorder_Makoto_02 [Makoto]]
[s][vp 8 0 2 1048 0 6]Ok... vou tentar![n][w][e]

[msg charaorder_Ranko_00 [Haru]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1035 0 7]Não podemos permitir que essa trapaça[n]continue...[n][w][e]

[msg charaorder_Ranko_01 [Haru]]
[s][vp 8 0 2 1042 0 7]Estou pronto quando.[n][w][e]

[msg charaorder_Ranko_02 [Haru]]
[s][vp 8 0 2 1049 0 7]Ok, eu vou![n][w][e]

[msg charaorder_Hutaba_00 [Futaba]]
[s]Datcharaorder dummy [n][w][e]

[msg charaorder_Hutaba_01 [Futaba]]
[s]Datcharaorder dummy [n][w][e]

[msg charaorder_Hutaba_02 [Futaba]]
[s]Datcharaorder dummy [n][w][e]

[msg charaorder_Akechi_00 [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1036 0 9]Vamos expor sua traição![n][w][e]

[msg charaorder_Akechi_01 [Akechi]]
[s][vp 8 0 2 1043 0 9]Deixe para mim! Eu não vou sentir falta da[n]marca![n][w][e]

[msg charaorder_Akechi_02 [Akechi]]
[s][vp 8 0 2 1050 0 9]Sim. Vou fazer isso sem problemas![n][w][e]

