[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Huh? O que e este lugar?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]E o castelo de Kamoshida.[e]
[s]A cor...[e]
[s]Uma estacao de TV?[e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Nao, voce pode dizer claramente que nao e...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu acho que este e um estudio de gravacao para uma estacao de TV. Mas por que tudo e colorido assim...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Sim. Este lugar parece um estudio de gravacao dentro de uma estacao de TV.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu penso que sim. Mas por que todo mundo e colorido assim...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Esses caras fazem parte da cognicao de Kamoshida?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Diga, quem diabos voces sao?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ei! Nao me ignore 悪[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Uau![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ei! Olhe para isso![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Espere, e isso... Kamoshida!?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Veteran AD]]
[s][vp 8 2 0 0 65535 0]Cortando do comercial![n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Sete, seis, cinco segundos ate o inicio, quatro,[n]tres...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Bright Announcer]]
[s][vp 8 2 0 0 9 0]E agora, em nosso segmento "mais quente e greet". Este ano marca o quarto ano desde o torneio mundial...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 9 0]Juntando-se a nos hoje, esta o capitao do time de volei para meninos que venceu o ultimo torneio mundial, Suguru Kamoshida.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ola, eu sou Kamoshida... Estou honrado em estar aqui.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]E ele! Mas... ele nao parece muito jovem!?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu nao tenho ideia do que esta acontecendo... vamos continuar assistindo por enquanto.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Talkative MC]]
[s][vp 8 2 0 0 8 0]Meu, isso e alguma popularidade! E isso com certeza nao mudou desde que voce se tornou profissional![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]N-NOT. Eu realmente nao sou tao especial.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Talkative MC]]
[s][vp 8 2 0 0 8 0]Voce realmente nao pode dizer isso agora, pode?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Bright Announcer]]
[s][vp 8 2 0 0 9 0]Absolutamente. Voce esta aparecendo atualmente em varios comerciais, entre outras coisas...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 9 0]E depois de assinar seu contrato profissional, voce doou metade de seus ganhos para a sua escola em casa.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Talkative MC]]
[s][vp 8 2 0 0 8 0]Isso mesmo! Nenhuma pessoa normal poderia ter passado por isso![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Talkative MC]]
[s][vp 8 2 0 0 8 0]Agora, por hoje, gostariamos de perguntar a um favor especial de voce, atleta Kamoshida...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ah com certeza![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Talkative MC]]
[s][vp 8 2 0 0 8 0]Ooh, e tao brilhante![n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 8 0]Ainda me lembro daquele pico final que voce pousou! Voce pode nos dizer como se sentiu no momento que venceu?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hum, bem... eu estava pensando comigo mesmo: "Eu fiz!"... Eu me senti muito feliz na epoca.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Talkative MC]]
[s][vp 8 2 0 0 8 0]Voce sentiu que estava sob pressao, sendo o capitao e tudo?[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Isso e verdade. Eu tinha minha propria pratica e tive que cuidar dos meus colegas de equipe tambem...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Acompanhar todas as responsabilidades de um capitao foi a parte mais dificil.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tome agora, por exemplo. Nao estou tao confortavel indo na frente das pessoas, entao...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Talkative MC]]
[s][vp 8 2 0 0 8 0]O que realmente? Voce poderia ter me enganado.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Haha... eu pareco realmente capaz para outras pessoas?[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Bright Announcer]]
[s][vp 8 2 0 0 9 0]Ainda assim, eu entendo esse sentimento.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Bright Announcer]]
[s][vp 8 2 0 0 9 0]Qualquer trabalho que envolva ir na frente das pessoas e muito trabalho, voce nao diria?[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 9 0]Sempre que as cameras estao rolando, nao posso deixar de colocar um "ato".[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 9 0]Eu acho que voce poderia dizer que e dificil ser eu mesmo...?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]......![n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Bright Announcer]]
[s][vp 8 2 0 0 9 0]Voce e realmente incrivel, Kamoshida-san![n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 9 0]Voce parecia tao legal durante a entrevista quando ganhou sua medalha de ouro![n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Talkative MC]]
[s][vp 8 2 0 0 8 0]Kamoshida-san, quando estava na escola, costumava estar no clube de volei. Ela era uma grande fa![n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Huh!?[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Bright Announcer]]
[s][vp 8 2 0 0 9 0]Sim! Eu adoraria falar mais com voce depois disso, se voce nao se importa![n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Talkative MC]]
[s][vp 8 2 0 0 8 0]Whoa whoa! Voce esta tentando marcar em um programa de TV ao vivo!?[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Talkative MC]]
[s][vp 8 2 0 0 8 0]Bem, voce a ouviu, Kamoshida-san. Como voce responde!?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Huh!? Hum, bem...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Talkative MC]]
[s][vp 8 2 0 0 8 0]Espere, voce esta seriamente corando, Kamoshida-san?[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Isso... parou? Ei, o que era tudo isso?[n][f 1 3 65535][w][e]

[sel SEL_041_0_0 top]
[s]Kamoshida era jovem.[e]
[s]Deveriamos estar no palacio.[e]

[msg MSG_042_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Sim, ele era.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Alem disso, ouvi algo sobre ele ganhar uma medalha de ouro no ultimo torneio. Nao era para isso ha muito tempo...?[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Nao me lembro de deixar o palacio... e Kamoshida nao parecia muito jovem la?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Alem disso, ouvi algo sobre ele ganhar uma medalha de ouro no ultimo torneio. Nao era para isso ha muito tempo...?[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]HM? Um jovem kamoshida...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Entao isso significa... esse era o passado de Kamoshida...?[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]O passado de Kamoshida!?[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Sim, ja que um palacio e o interior do coracao de uma pessoa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Nao seria estranho vermos manifestacoes de memorias aqui que sao significativas para a pessoa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Coisas que eles nao podem esquecer, ou mesmo, coisas que eles querem esquecer, mas nao podem...[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu nao dou a minima para o passado do idiota![n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Kamoshida provavelmente tambem nao quer que saibamos. Ele pode desligar se irmos cavar por conta propria.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Por outro lado, se entendermos melhor o coracao do governante do palacio, poderemos navegar melhor neste lugar.[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]"Conheca teu inimigo"... como eles dizem?[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Exatamente. Devemos manter nossos olhos para portas semelhantes daqui para frente.[n][f 1 3 65535][w][e]

[msg SYS_051_0_0]
[s]Existem portas escondidas em todo o palacio que contem memorias do passado do governante do palacio.[n][f 1 3 65535][w][e]
[s]A abertura de todas essas portas pode permitir que voce progrida pelo palacio com mais facilidade.[n][f 1 3 65535][w][e]

