[msg SNUFF_PS_GET_NG]
[s]Você já tem essa máscara...[n][e]

[msg SNUFF_PS_MAX]
[s]Você não pode segurar mais máscaras...[n][e]

[msg COMBINE_WARNING_MSG]
[s]Estou sentindo inquieto...[n][w][e]

[msg SYS_HumanParam_ItemUse]
[s]Graças ao "nome do item", suas estatísticas[n]sociais aumentarão mais do que o normal[n]para esse período.[n][w][e]
[s]O efeito continuará enquanto o tempo não[n]avançar. Faça um bom uso disso enquanto[n]puder.[n][w][e]

