[msg MSG_ITEM_SHOP_OPEN_00 [Languid Doctor]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14030 65535 0]...E a sua primeira visita?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]HM? Eu sinto que te vi em algum lugar[n]antes da...[n][w][e]

[msg MSG_ITEM_SHOP_OPEN_01 [Languid Doctor]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14028 65535 0]Voce precisa de cuidados de emergencia tao tarde?[n]O horario de consulta acabou...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]HM? Eu sinto que te vi em algum lugar[n]antes da...[n][w][e]

[sel SEL_ITEM_SHOP_OPEN_CHK_0 top]
[s]Em LeBlanc.[e]
[s]Acabei de me mudar para ca.[e]
[s]Prazer em conhece-la.[e]

[msg MSG_ITEM_SHOP_OPEN_02 [Languid Doctor]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hmmm... bem, o que quer que seja...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entao, o que voce esta aqui para hoje?[n][w][e]

[sel SEL_ITEM_SHOP_OPEN_CHK_0_2 top]
[s]Meu corpo parece letargico.[e]
[s]Eu tenho tido pesadelos.[e]
[s]Eu tenho uma doenca cronica...[e]

[msg MSG_ITEM_SHOP_OPEN_03 [Languid Doctor]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0]......[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]...Multar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 14059 65535 0]Por favor, va para a sala de exames.[n][w][e]

[msg MSG_C13_BEGIN_UNOPEN_00 [Languid Doctor]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14059 65535 0]Voce precisa de remedio, certo? Va em frente[n]na sala de exame.[n][w][e]

[msg MND_C13_PRECOOP_00_00]
[s]Eu deveria perguntar sobre o "medicamento para melhorar"[n]Eu a ouvi mencionar outro dia...[n][w][e]

[msg MSG_C13_PRECOOP_00_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14030 65535 0]O que voce esta aqui para hoje?[n][w][e]

[msg MND_C13_PRECOOP_00_01]
[s]Eu deveria perguntar a ela sobre[n]aquele "medicamento para melhorar"...[n][w][e]

[msg MSG_C13_PRECOOP_00_01 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14002 65535 0]Voce ainda precisa de algo?[n][w][e]

[sel SEL_C13_PRECOOP_01_00 top]
[s]Tem algum remedio "especial"?[e]
[s]Eu preciso de remedios regulares.[e]
[s]Oh, nao e nada.[e]

[msg MSG_C13_PRECOOP_02_00 [Takemi]]
[s][bup 0 108 2 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14089 65535 0]Huh?[n][w][e]
[s]......[n][w][e]

[msg MSG_C13_PRECOOP_02_02 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce e o garoto que estava em LeBlanc.[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]... remedio regular nao fara o truque?[n][w][e]

[msg MSG_C13_PRECOOP_02_02_5R [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Agora eu lembro. Voce e o garoto que[n]estava em LeBlanc.[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]... remedio regular nao fara o truque?[n][w][e]

[sel SEL_C13_PRECOOP_03_00 top]
[s]Tenho meus motivos...[e]
[s]Por favor, eu te imploro.[e]

[msg MSG_C13_PRECOOP_04_00 [Takemi]]
[s][bup 0 108 0 0 0]......[n][w][e]

[msg MSG_C13_PRECOOP_04_01 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14027 65535 0]Muito bem...[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Apenas va para a sala de exame[n]por enquanto.[n][w][e]

[msg MSG_C13_PRECOOP_30_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14059 65535 0]Bem, entao, por favor, va para o[n]sala de exame.[n][w][e]

[msg MSG_C13_PRECOOP_40_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14115 65535 0]...Cuidar.[n][w][e]

[msg MSG_C13_BEGIN_QUEST_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14027 65535 0]... ha algo que voce quer?[n][w][e]

[msg MSG_TAKEMI_SHOP_SASOI_TH [Takemi]]
[s][bup 0 108 2 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, apenas verificando, voce precisa de remedios[n]Para ajudar a estudar para seus exames, certo?[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Eu tenho preparativos para fazer,[n]Entao chegue aqui mais cedo da proxima vez.[n][w][e]

[msg MSG_TAKEMI_SHOP_SASOI_TH_2 [Takemi]]
[s][bup 0 108 2 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce ate tem resistencia para[n]Continuar com os ensaios clinicos?[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Eu entrei em contato com voce, mas voce parecia[n]bastante ocupado. Outra pessoa pode ser[n]A cobaia, voce sabe.[n][w][e]

[msg MSG_C13_BEGIN_WEATHER_00 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14011 65535 0]Parece um dia de folga porque eu nao[n]tem muitos pacientes hoje...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas esta chovendo... para que eu possa receber um influxo[n]de pessoas com resfriados.[n][w][e]

[msg MSG_C13_BEGIN_WEATHER_01 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14026 65535 0]Dias de neve sao irritantes porque muito[n]de pessoas escorregam e se machucam...[n][w][e]

[msg MSG_C13_BEGIN_WEATHER_02 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14048 65535 0]Eu faco progresso quando a umidade e alta[n]Porque estimula a propagacao[n]de bacterias.[n][w][e]

[msg MSG_C13_BEGIN_WEATHER_03 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14013 65535 0]Eu tenho muitos pacientes hoje com[n]dores de cabeca... provavelmente devido a baixa[n]pressao atmosferica.[n][w][e]

[msg MSG_C13_BEGIN_WEATHER_04 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14014 65535 0]Como estao suas alergias?[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Eu tenho um bom remedio para eles.[n]Apenas uma dose deve cuidar de[n]eles, em teoria.[n][w][e]

[msg MSG_C13_BEGIN_WEATHER_05 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14015 65535 0]A chuva esta horrivel la fora... embora seja[n]bom porque nao vou conseguir muitos[n]pacientes.[n][w][e]

[msg MSG_C13_BEGIN_WEATHER_06 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14016 65535 0]Para evitar insultos de calor,[n]Voce tem que se manter hidratado...[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]... mas voce nao parece muito preocupado[n]sobre isso.[n][w][e]

[msg MSG_C13_BEGIN_WEATHER_07 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14017 65535 0]Voce tem uma contramedida para[n]a gripe?[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]A vacina para a tensao deste ano nao foi[n]eficaz, entao aposto que vou ter muito[n]pacientes...[n][w][e]

[msg MSG_C13_BEGIN_WEATHER_08 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14017 65535 0]Realmente esta congelando hoje, hein?[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Nao pegue um resfriado la fora.[n][w][e]
[s]Eu tenho pacientes suficientes como sao.[n][w][e]

[msg MSG_C13_BEGIN_TIME_01 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14027 65535 0]Na primavera, um "dorme um sono que sabe[n]sem amanhecer, "hein...? * bocejo * Deus, eu preciso[n]um cochilo...[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Ou pelo menos uma boa moda antiga[n]cafeina no meu sistema...[n][w][e]

[msg MSG_C13_BEGIN_TIME_02 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14026 65535 0]Quanto mais quente fica, o pessoal estranho[n]aja... como aquele ensino medio pervertido[n]professora.[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Alguem ja estudou a correlacao[n]entre o aumento da temperatura e[n]Um aumento de esquisitos...?[n][w][e]

[msg MSG_C13_BEGIN_TIME_03 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14026 65535 0]Um paciente me perguntou se eu tinha um[n]Recomendacao para um par[n]de leitura de oculos...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas eu nao sou um optometrista... oh, e isso[n]Porque eu tenho um grafico de testes de olho no[n]muro...?[n][w][e]

[msg MSG_C13_BEGIN_TIME_04 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14016 65535 0]Esta ficando mais quente, hein? Como esta o seu[n]saude? Nao se esqueca de permanecer hidratado.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu nao quero voce desmoronar quando voce[n]Tome meu remedio.[n][w][e]

[msg MSG_C13_BEGIN_TIME_05 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14018 65535 0]As noites estao ficando mais legais.[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]E facil ficar doente naquele meio[n]periodo a medida que as estacoes mudam, entao seja[n]cuidadoso.[n][w][e]

[msg MSG_C13_BEGIN_TIME_06 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14026 65535 0]Hematomas, entorses, ossos quebrados...[n]Eu nao sou um cirurgiao...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu nao sei se o outono e a estacao[n]para esportes, mas considere sua idade e[n]Nao se superexert.[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Bem, acho que uma crianca como voce nao tem[n]muito com que se preocupar la...[n][w][e]

[msg MSG_C13_BEGIN_TIME_07 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14026 65535 0]Uma eleicao em um momento como este? Bleh...[n]Estou com preguica de votar...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, acho que ainda nao e o seu problema.[n][w][e]

[msg MSG_C13_BEGIN_TIME_08 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14002 65535 0]... hm? Voce esta nervoso? Eu nao sei, e[n]como se voce estivesse prestes a mergulhar[n]ou alguma coisa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tudo o que posso fazer por voce e lhe dar remedios.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entao, tudo o que voce esta fazendo, apenas faca[n]Claro para nao exagerar.[n][w][e]

[msg MSG_C13_BEGIN_TIME_09 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14021 65535 0]Parece que o ano novo comecou, e[n]Todo mundo esta vindo para mim sem nada[n]Mas boas noticias.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Um dos meus amigos que trabalha no ER[n]de repente passa mais tempo com[n]sua familia apos uma grande reforma no local de trabalho.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas nao e como se eles trouxessem nenhum novo[n]Hires, entao... parece um pouco estranho.[n][w][e]

[msg MSG_C13_CONNECT_NG_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entao, o que voce quer hoje?[n][w][e]

[msg MSG_C13_CONNECT_OK_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entao, o que voce esta aqui para hoje?[n][w][e]

[msg MSG_C13_CONNECT_OK_01 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce veio porque viu minhas mensagens,[n]certo?[n][w][e]

[msg MSG_C13_BEGIN_SECOND_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14002 65535 0]Voce precisa de algo de novo?[n][w][e]

[msg MSG_C13_BEGIN_ABI_00_00 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0]Eu nao recebo muitos pacientes quando o[n]O tempo esta ruim, entao vou manter os precos baixos[n]para voce hoje.[n][w][e]

[sel SEL_C13_BUY_OR_COOP top]
[s]Eu quero fazer um ensaio clinico.[e]
[s]Eu quero comprar algo.[e]
[s]Deixa para la.[e]

[sel SEL_C13_BUY_OR_COOP_7 top]
[s]Eu tenho que falar com voce.[e]
[s]Eu quero comprar algo.[e]
[s]Deixa para la.[e]

[sel SEL_C13_DOUBT top]
[s]Ouca o que tenho a dizer.[e]
[s]Eu quero comprar algo.[e]
[s]Deixa para la.[e]

[msg MSG_C13_SHOP_00_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14059 65535 0]Entao vamos para o exame[n]quarto.[n][w][e]

[msg MSG_C13_SHOP_01_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O que voce gostaria?[n][w][e]

[msg MSG_C13_SHOP_01_01 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O que voce quer?[n][w][e]

[msg MSG_C13_SHOP_02_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cuidar.[n][w][e]

[msg MSG_C13_SHOP_02_01 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]...Bem entao.[n][w][e]

[msg MSG_C13_SHOP_03_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14115 65535 0]Entao boa sorte com isso.[n][w][e]

[msg MSG_C13_COOP_NG_00_NODOK]
[s]Pensando bem,[n]Eu posso entrar em colapso de novo[n]Se eu tomar esse remedio...[n][w][e]
[s]Eu sinto que preciso[clr 26][f 4 13 3 2][clr 27] [f 4 11 3][clr 26][f 4 12 3][clr 27][n]Para tomar esse remedio...[n][w][e]
[s]Eu nao deveria sugerir[n]Um ensaio clinico...[n][w][e]

[msg MSG_C13_COOP_NG_00_NODOK_2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Ensaios clinicos, hein? Isso e praticamente[n]Colocando sua vida nas maos dela... levaria[n]coragem, isso e certo.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tem que haver maneiras de construir[n]sua[f 4 11 3][clr 26][f 4 12 3][clr 27]em sua vida diaria.[n][w][e]
[s][bup 0 3 11 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Talvez voce possa melhorar seu[f 4 11 3][clr 26][f 4 12 3][clr 27][n]estudando as coisas certas no[n]biblioteca da escola.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Acho que vamos apenas tentar o que pudermos.[n][w][e]

[msg MSG_C13_COOP_NG_00_NODOK_3 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Ensaios clinicos, hein? Isso e praticamente[n]Colocando sua vida nas maos dela... levaria[n]coragem, isso e certo.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tem que haver maneiras de construir[n]sua[f 4 11 3][clr 26][f 4 12 3][clr 27]em sua vida diaria.[n][w][e]
[s][bup 0 3 11 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Tente pequenas maneiras de se esforcar. Curti,[n]Nao sei... aceite um desafio alimentar. Este[n]pode construir alguns[f 4 11 3][clr 26][f 4 12 3][clr 27].[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Acho que vamos apenas tentar o que pudermos.[n][w][e]

[msg MSG_C13_COOP_NG_00_OKDOK]
[s]No meu nivel atual de[n][f 4 11 3][clr 26][f 4 12 3][clr 27], Eu deveria ser capaz[n]para lidar com esse remedio.[n][w][e]
[s]Eu deveria sugerir[n]Um ensaio clinico...[n][w][e]

[msg MSG_C13_COOP_NG_00_20 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14032 65535 0]Ainda estou estudando clinica de ontem[n]tentativas. Os resultados foram muito interessantes.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Provavelmente nao faremos outro julgamento[n]Ate o dia depois de amanha...[n][w][e]

[msg MSG_C13_COOP_NG_00_10 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14032 65535 0]Estou no meio da revisao dos resultados[n]do nosso ultimo ensaio clinico.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce pode voltar amanha?[n][w][e]

[msg MSG_C13_COOP_NG_00_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14032 65535 0]...Oh, desculpe. Eu nao terminei de configurar[n]Para o ensaio clinico ainda.[n][w][e]

[msg MSG_C13_COOP_NG_00_01 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14032 65535 0]Eu so posso fazer os ensaios clinicos[n]durante o dia. Volte novamente[n]Quando o sol esta fora.[n][w][e]

[msg MSG_C13_COOP_NG_01_00 [Takemi]]
[s][bup 0 108 6 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14081 65535 0]Eu posso ter um paciente entrando[n]Para um exame, entao venha novamente em[n]noite se voce precisar de algo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]...Ok?[n][w][e]

[msg MSG_C13_COOP_NG_01_01 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14032 65535 0]Me desculpe, ainda tenho muito trabalho[n]Para fazer hoje...[n][w][e]
[s][bup 0 108 6 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Volte outra vez.[n][w][e]

[msg MSG_C13_COOP_NG_QUEST_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0]... um ensaio clinico? Nao ha necessidade de fazer[n]aqueles por mais tempo.[n][w][e]

[msg MND_C13_COOP_NG_QUEST_01]
[s]Embora tenhamos mudado de Oyamada[n]coracao, parece que ele nao[n]contatou Takemi ainda.[n][w][e]
[s]Vamos perguntar a ela em outro momento...[n][w][e]

[msg MSG_C13_COOP_00_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nesse caso, voce poderia me deixar verificar[n]Seu progresso, minha pequena cobaia?[n][w][e]

[msg MSG_C13_COOP_10_00 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nao vamos fazer um ensaio clinico,[n]Mas posso fazer um check-up[n]em sua saude.[n][w][e]

[msg MSG_C13_COOP_10_01 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nao faremos um ensaio clinico, mas...[n]Posso examina-lo?[n][w][e]

[msg MSG_C13_SPOT_01_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu gostaria de poder estudar dados la fora uma vez em[n]um tempo... como em um parque espacoso...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Em algum lugar que nao esta muito lotado[n]Seria melhor... talvez eu olhe[n]por um quando tenho algum tempo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tudo bem, vamos ao ensaio clinico.[n][w][e]

[msg MSG_C13_SPOT_02_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu posso querer tentar um diferente[n]ambiente para que eu possa entender[n]Como a pressao afeta os dados.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Por exemplo, algum lugar que e alto[n]sobre o chao. Vou ter que encontrar um bom[n]localizacao...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ok, vamos fazer o ensaio clinico de hoje.[n][w][e]

[msg MSG_C13_SPOT_03_00 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu gostaria que pudessemos sair a noite[n]Em algum lugar juntos... apenas nos dois.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu nao me importaria de fechar a clinica[n]para hoje...[n][w][e]

[msg MSG_C13_SPOT_04_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu meio que quero comer junk food...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas isso pode afetar os resultados do estudo...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah bem. Vamos para o ensaio clinico.[n][w][e]

[msg MSG_C13_SPOT_05_00 [Takemi]]
[s][bup 0 108 7 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu poderia pegar uma xicara de cafe...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Deixa para la. Agora, vamos para o[n]sala de exames para fazer o ensaio clinico.[n][w][e]

[msg MSG_C13_COOP_01_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu desenvolvi um novo remedio. Voce poderia[n]Venha para as costas?[n][w][e]

[msg MSG_C13_COOP_02_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu refinei o remedio do outro[n]dia um pouco. Voce poderia vir para as costas?[n][w][e]

[msg MSG_C13_COOP_03_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu fiz mais alguns refinamentos para o[n]medicamento. Eu poderia ter voce entrando?[n][w][e]

[msg MSG_C13_COOP_04_00 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nesse caso, minha pequena cobaia, ha[n]Algo que quero testar hoje...[n][w][e]

[msg MSG_C13_COOP_05_00 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu tenho estado muito ocupado ultimamente com todos os meus[n]Novos pacientes, mas... o que diabos?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, tudo ja esta configurado.[n][w][e]

[msg MSG_C13_COOP_06_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Esta quase completo. Ha alguma coisa[n]Eu quero testar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce poderia ir para as costas?[n][w][e]

[msg MSG_C13_COOP_07_00 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, o ensaio clinico...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Desculpe, vou passar hoje.[n][w][e]
[s]......[n][w][e]

[msg MND_C13_COOP_07_01]
[s]Takemi esta deprimido...[n][w][e]

[msg MND_C13_COOP_07_02]
[s]Para que ela dependa de mim,[n]Eu posso ter que polir[n]minha[f 4 11 1][clr 26][f 4 12 1][clr 27]como pessoa...[n][w][e]
[s]Takemi provavelmente faria[n]depende de mim se meu[f 4 11 1][clr 26][f 4 12 1][clr 27][n]nos estamos[clr 26][f 4 13 1 4][clr 27]...[n][w][e]

[msg MND_C13_COOP_07_03]
[s]Meu transbordamento[f 4 11 1][clr 26][f 4 12 1][clr 27][n]O coracao teimoso de Takemi derretido![n][w][e]

[msg MSG_C13_COOP_07_04 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu preciso falar com voce.[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Ja que essa pode ser a ultima vez...[n][w][e]

[msg MSG_C13_COOP_07_11 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14032 65535 0]Nao ha necessidade de fazermos mais[n]testes clinicos.[n][w][e]

[msg MND_C13_COOP_07_12]
[s]Takemi parece afundado em melancolia.[n]A causa provavelmente e seu problema[n]com o chefe de gabinete medico.[n][w][e]
[s]Eu ja conheco o chefe medico[n]do nome da equipe. Vamos ir para[n]Lembrancas e mude seu coracao...[n][w][e]

[msg MSG_C13_COOP_07_03 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nao ha nada para falar...[n][w][e]

[msg MSG_C13_COOP_08_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu fiz progressos com o remedio.[n]Voce poderia acompanhar um pouco?[n][w][e]

[msg MSG_C13_COOP_09_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nao ha necessidade de um ensaio clinico. Voce[n]veio no momento perfeito. Entre.[n][w][e]

[msg MSG_C13_COOP_09_01 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Agora nao ha necessidade de um ensaio clinico.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mais importante, agora seria um[n]Otimo momento para um cafe. Voce mora em um[n]caf, right?[n][w][e]

[msg MND_COOP_DOUZOKUSEI]
[s]Eu sinto que posso me aproximar[n]Takemi gracas ao[var 2][n]Persona[clr 1][var 5][clr 27]...[n][w][e]

[msg MND_COOP_RANKUP_OK]
[s]Eu me sinto como meu vinculo com Takemi[n]Vai ficar mais forte em breve...[n][w][e]

[msg MND_COOP_RANKUP_NG]
[s]Eu nao acho que meu vinculo com[n]Takemi vai se aprofundar ainda...[n][w][e]

[msg MND_COOP_RANK_MAX_00]
[s]Eu tenho um vinculo forte[n]com Takemi...[n][w][e]

[msg MND_COOP_RANK_MAX_01]
[s]Eu tenho um vinculo especial[n]com Takemi...[n][w][e]

[msg MSG_COOP_CHECK_NIGHT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entao o que voce vai fazer?[n]Quer sair com Takemi?[n][w][e]

[msg MSG_COOP_CHECK_SHIDOU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ninguem pensa que voce esta vivo neste momento,[n]Entao deve ficar bem enquanto voce estiver[n]cuidadoso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entao o que voce vai fazer? Quer[n]sair com Takemi?[n][w][e]

[msg MSG_COOP_CHECK_RANK_7 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Por que voce nao diz a Takemi[n]Sobre Oyamada?[n][w][e]

[sel SEL_COOP_CHECK top]
[s]Sair com ela[e]
[s]Verifique o vinculo com Takemi[e]
[s]Declinio[e]

[sel SEL_COOP_CHECK_RANK_7 top]
[s]Fale com ela[e]
[s]Verifique o vinculo com Takemi[e]
[s]Declinio[e]

[msg MSG_C13_YES_01_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14059 65535 0]Nesse caso, vou comecar a se estabelecer,[n]Entao va esperar na sala de exames.[n][w][e]

[msg MSG_C13_YES_02_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14059 65535 0]Vou comecar a configurar entao.[n]Va para a sala de exames.[n][w][e]

[msg MSG_C13_YES_03_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14061 65535 0]Nesse caso, va para o exame  hein?[n][w][e]

[msg MSG_C13_YES_03_01 [Man's Voice]]
[s]Entao esta e a clinica medica de Takemi de[n]Medicina Interna? Estou feliz que ainda esta[n]abrir.[n][w][e]
[s]Desculpe, eu tenho um filho que preciso ter[n]examinado...[n][w][e]

[msg MSG_C13_YES_03_02 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14001 65535 0]... parece que tenho um paciente com um[n]emergencia.[n][w][e]

[msg MSG_C13_YES_04_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14059 65535 0]Bem, entao, por favor, va para o[n]sala de exame.[n][w][e]

[msg MSG_C13_YES_05_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh aquela velha senhora de anteriormente esqueceu[n]algo...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 14021 65535 0]Eu me pergunto se ela ainda esta do lado de fora...[n][w][e]

[msg MSG_C13_YES_06_00 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14048 65535 0]E obrigado a voce que eu era capaz de[n]Progresso ate agora.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Agora voce pode beber essas coisas sem[n]Problema, certo?[n][w][e]

[msg MSG_C13_YES_07_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14059 65535 0]Entre.[n][w][e]

[msg MSG_C13_YES_07_01 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14060 65535 0]Oh, tudo bem... eu vou ate voce, entao espere la.[n][w][e]

[msg MSG_C13_YES_08_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vou conhecer alguem em[n]Parque Inokashira.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 14052 65535 0]Esta perto, certo? Vamos la.[n][w][e]

[msg MSG_C13_YES_09_00 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entao, suponho que vou visitar agora.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 14110 65535 0]* risada* Estou supondo que ninguem esteja em casa[n]a noite?[n][w][e]

[msg MSG_C13_YES_09_01 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14122 65535 0]A garota que tenho tratado e[n]chegando em breve. Eu quero que voce veja[n]Como ela esta.[n][w][e]

[msg MSG_MORGANA_COOP_ESCAPE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bem, eu vou andar por ai. Deixe-me[n]Saiba quando voce esta pronto para sair.[n][w][e]

[msg MSG_TAKEMI_K_YES [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14059 65535 0]Bem, entao, por favor, va para o[n]sala de exame.[n][w][e]

[msg MSG_C13_YES_10_00 [Takemi]]
[s][bup 0 108 6 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14110 65535 0]Sim... eu nao tenho mais pacientes,[n]Entao... entre.[n][w][e]

[msg MSG_C13_YES_10_01 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14136 65535 0]Ok, entao va para o exame[n]quarto.[n][w][e]

[msg MND_C13_SPOT_01_01]
[s]Talvez eu deva convidar[n]ela para o parque Inokashira...[n][w][e]

[sel SEL_C13_SPOT_01_02 top]
[s]Convide-a[e]
[s]Nao a convide[e]

[msg MSG_C13_SPOT_01_03 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Inokashira Park? Hmmm... isso pode[n]Na verdade, seja uma boa ideia.[n][w][e]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E um pouco longe, mas vamos dar uma olhada.[n][w][e]

[msg MND_C13_SPOT_02_01]
[s]Talvez eu deva convidar[n]ela para o Skytree...[n][w][e]

[sel SEL_C13_SPOT_02_02 top]
[s]Convide-a[e]
[s]Nao a convide[e]

[msg MSG_C13_SPOT_02_03 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Skytree, hein? Parece divertido.[n][w][e]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 1 14052 65535 0]Vamos dar uma olhada.[n][w][e]

[msg MND_C13_SPOT_03_01]
[s]Talvez eu deva convida-la a andar[n]A roda de gigante de Odaiba comigo...[n][w][e]

[sel SEL_C13_SPOT_03_02 top]
[s]Convide-a[e]
[s]Nao a convide[e]

[msg MSG_C13_SPOT_03_03 [Takemi]]
[s][bup 0 108 6 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14051 65535 0]Voce realmente me leva? Ok, vamos la entao.[n][w][e]

[msg MND_C13_SPOT_04_01]
[s]Talvez eu deva convida-la para[n]Va buscar Monjayaki comigo...[n][w][e]

[sel SEL_C13_SPOT_04_02 top]
[s]Convide-a[e]
[s]Nao a convide[e]

[msg MSG_C13_SPOT_04_03 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14051 65535 0]OK, vamos la.[n][w][e]

[msg MND_C13_SPOT_05_01]
[s]Devo convida-la para o meu quarto?[n][w][e]

[sel SEL_C13_SPOT_05_02 top]
[s]Convide-a[e]
[s]Nao a convide[e]

[msg MSG_C13_SPOT_05_03 [Takemi]]
[s][bup 0 108 6 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Seu quarto!?[n][w][e]
[s][bup 0 108 6 0 0][f 4 10 65535 0 0][vp 8 2 1 14060 65535 0]...OK, claro. Eu vou me preparar,[n]Entao espere.[n][w][e]

[msg MSG_C13_COOP_CANCEL [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14022 65535 0]...Isso e bom.[n][w][e]

[msg MSG_C13_COOP_CANCEL_07_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu vejo...[n][w][e]

[msg MSG_SPOT_OPEN_KANDA]
[s]Agora voce pode ir para[clr 2]Kanda[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_SHINJUKU]
[s]Agora voce pode ir para[clr 2]Shinjuku[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_AKIHABARA]
[s]Agora voce pode ir para[clr 2]Akihabara[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]

[msg MSG_SPOT_OPEN_INOKASHIRA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Parque Inokashira[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]

[msg MSG_SPOT_OPEN_OGIKUBO]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Ogikubo Ramen[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar de comer ramen[n]Para sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_ODAIBA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Parque Seasa de Odaiba[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar desses parques para[n]sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_UENO]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Museu Ueno[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode desfrutar de museus de arte[n]Para sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_TSUKISHIMA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Tsukishima Monja[clr 27].[n][w][e]
[s]Voce tambem pode convidar pessoas que[n]pode gostar de comer monjayaki para[n]sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_HARAJUKU]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Harajuku Takenoko Street[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode desfrutar da Rua Takeko[n]Para sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_TYUKAGAI]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Motomachi Chinatown[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]

[msg MSG_SPOT_OPEN_MAIHAMA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Maihama Destinyland[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Asakusa[clr 27].[n][w][e]
[s]Voce tambem pode convidar pessoas que podem[n]Aproveite a rua Skytree ou Nakamise[n]Para sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_IKEBUKURO]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Ikebukuro Planetarium[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]

[msg MSG_SPOT_OPEN_MEIJIJINGU]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Santuario Meiji[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]
[s]Alem disso, voce pode passar[n]voce para prestar homenagem a[n]o santuario, se desejar.[n][w][e]

[msg MSG_SPOT_OPEN_SUIDOUBASH]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Cidade de Suidobashi Dome[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]

[msg MSG_SPOT_OPEN_SHIBUYA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Shibuya Wilton Hotel[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]

[msg MSG_SPOT_OPEN_GINZA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Barra de sushi de ginza[clr 27].[n][w][e]
[s]Voce tambem pode convidar pessoas que[n]pode gostar de comer sushi caro[n]Para sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_JINBOCHO]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Cidade do Livro JinboCho[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]
[s]Alem disso, voce pode passar[n]voce mesmo para fazer compras[n]Se voce deseja.[n][w][e]

[msg MSG_SPOT_OPEN_ICHIGAYA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Ichigaya Pisca de pesca[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar de pescar para[n]sair com voce la.[n][w][e]
[s]Alem disso, voce pode passar[n]voce mesmo e tente sua mao em[n]pescar se voce escolher.[n][w][e]

[msg MSG_SPOT_OPEN_SHINAGAWA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Aquario Shinagawa[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode aproveitar o aquario[n]Para sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_NAKANO]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Distrito de construcao de comercio de Nakano[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode aproveitar esse local[n]Para sair com voce la.[n][w][e]

[msg MSG_C13_BYEGREET_00_00 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 1 65535 0]...Voce veio.[n][w][e]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]Eu queria atualiza-lo sobre Miwa-chan.[n]Seus sintomas diminuiram gracas ao[n]Novo medicamento.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]Ela ainda tem um caminho a percorrer, mas...[n]Nao vai demorar muito ate eu chegar a[n]Veja o sorriso dela.[n][w][e]

[sel SEL_C13_BYEGREET_00_01 top]
[s]Fico feliz em ouvir isso.[e]
[s]Mal posso esperar.[e]
[s]E tudo gracas a voce.[e]

[msg MSG_C13_BYEGREET_00_02 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]Sim, estou aliviado tambem.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]... eu nao teria sido capaz de terminar[n]O novo remedio sem a sua ajuda.[n][w][e]

[msg MSG_C13_BYEGREET_00_03 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Sim... tudo o que resta fazer e esperar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 7 65535 0]... eu nao teria sido capaz de terminar[n]O novo remedio sem a sua ajuda.[n][w][e]

[msg MSG_C13_BYEGREET_00_04 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]Nao foi apenas pelos meus esforcos.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 9 65535 0]... eu nao teria sido capaz de terminar[n]O novo remedio sem a sua ajuda.[n][w][e]

[msg MSG_C13_BYEGREET_00_05 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 10 65535 0]Muito obrigado, minha pequena cobaia [n]Oh, acho que nao posso te chamar assim agora[n]que voce me ajudou muito.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]O mesmo vale para a situacao com[n]Oyamada... voce fez tudo[n]Voce poderia me ajudar com isso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]Aqui... pegue isso.[n][w][e]

[msg MSG_C13_BYEGREET_00_06 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Voce nao estara aqui amanha...[n][w][e]
[s][vp 8 0 1 14 65535 0][f 4 10 65535 0 0]Estou preocupado com voce. Voce tem um[n]tendencia a se esforcar...[n][w][e]
[s][bup 0 108 6 0 0][f 4 10 65535 0 390][vp 8 0 1 15 65535 0]Cuide bem do seu corpo, pelo menos,[n]ok...? Vejo voce mais tarde.[n][w][e]

[msg MSG_C13_BYEGREET_00_07 [Takemi]]
[s][bup 0 108 6 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 390][vp 8 0 1 16 65535 0]Cuide bem do seu corpo, pelo menos,[n]ok?...Vejo voce mais tarde.[n][w][e]

[msg MSG_C13_BYEGREET_01_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 17 65535 0]Ah... Ola.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 18 65535 0]Voce esta indo para casa amanha, certo?[n]Entao deixe-me fazer uma atualizacao.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 19 65535 0]Aparentemente, os sintomas de Miwa-chan[n]esta subindo desde que eles[n]administrou o medicamento.[n][w][e]

[sel SEL_C13_BYEGREET_01_01 top]
[s]Fico feliz em ouvir isso.[e]
[s]Ela esta curada?[e]
[s]Voce pode ve-la sorrir agora.[e]

[msg MSG_C13_BYEGREET_01_02 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 20 65535 0]Sim, estou aliviado tambem  e tudo obrigado[n]Para voce, minha pequena cobaia.[n][w][e]

[msg MSG_C13_BYEGREET_01_03 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 21 65535 0]Ela ainda tem alguns caminhos a percorrer, mas...[n]Nao demorara muito para esse ritmo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 22 65535 0]E tudo gracas a voce, meu pequeno[n]porquinho da india.[n][w][e]

[msg MSG_C13_BYEGREET_01_04 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 23 65535 0]Voce esta certo... eu nao posso controlar meu[n]excitacao.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 24 65535 0]E tudo gracas a voce, meu pequeno[n]porquinho da india.[n][w][e]

[msg MSG_C13_BYEGREET_01_05 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 25 65535 0]Obrigado por me ajudar, ate[n]o fim.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 26 65535 0]O mesmo vale para a situacao com[n]Oyamada... voce fez tudo[n]Voce poderia me ajudar com isso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 27 65535 0]Aqui... pegue isso.[n][w][e]

[msg MSG_C13_BYEGREET_01_06 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 28 65535 0]Eu realmente queria que voce conhecesse Miwa-chan,[n]mas...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 29 65535 0]Salvaremos isso para outra hora.[n][w][e]
[s][f 4 10 65535 0 500][vp 8 0 1 30 65535 0]Tenho certeza que nos encontraremos novamente... se voce[n]Nao morra. Bem cuidar.[n][w][e]

[msg MSG_C13_BYEGREET_01_07 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 500][vp 8 0 1 31 65535 0]Tenho certeza que nos encontraremos novamente... se voce[n]Nao morra. Bem cuidar.[n][w][e]

[msg MSG_C13_BYEGREET_00_00_5 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 32 65535 0]...Voce veio.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 33 65535 0]Eu queria atualiza-lo sobre Miwa-chan.[n]Seus sintomas diminuiram gracas ao[n]Novo medicamento.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 34 65535 0]Ela ainda tem um caminho a percorrer, mas...[n]Nao vai demorar muito ate que eu veja[n]o sorriso dela.[n][w][e]

[sel SEL_C13_BYEGREET_00_01_5 top]
[s]Fico feliz em ouvir isso.[e]
[s]Mal posso esperar.[e]
[s]E tudo gracas a voce.[e]

[msg MSG_C13_BYEGREET_00_02_5 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 35 65535 0]Sim, estou aliviado tambem.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 36 65535 0]... eu nao teria sido capaz de terminar[n]O novo remedio sem a sua ajuda.[n][w][e]

[msg MSG_C13_BYEGREET_00_03_5 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 37 65535 0]Sim... tudo o que resta fazer e esperar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 38 65535 0]... eu nao teria sido capaz de terminar[n]O novo remedio sem a sua ajuda.[n][w][e]

[msg MSG_C13_BYEGREET_00_04_5 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 39 65535 0]Nao foi apenas pelos meus esforcos.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 40 65535 0]... eu nao teria sido capaz de terminar[n]O novo remedio sem a sua ajuda.[n][w][e]

[msg MSG_C13_BYEGREET_00_05_5 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 41 65535 0]Muito obrigado, minha pequena cobaia [n]Oh, acho que nao posso te chamar assim agora[n]que voce me ajudou muito.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 42 65535 0]O mesmo vale para a situacao com[n]Oyamada... voce fez tudo[n]Voce poderia me ajudar com isso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 43 65535 0]Eu nao sei onde toda essa devocao[n]vem de. Talvez eu deva levar[n]uma sugestao de voce.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 44 65535 0]Aqui... eu quero que voce tenha isso.[n][w][e]

[msg MSG_C13_BYEGREET_00_06_5 [Takemi]]
[s][bup 0 108 3 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 45 65535 0]Entao... aqui hoje, se foi amanha, hein?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 46 65535 0]Agora sou apenas um medico do bairro.[n]Nao e mais assistente. Me pergunto se e[n]vou ser dificil sem voce.[n][w][e]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 0 1 47 65535 0]Bem... o pensamento passou pela minha mente.[n]Mas de alguma forma eu acho que ficaremos bem.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 48 65535 0]E ei. Se eu quiser, sempre posso[n]Surpreenda voce com uma chamada em casa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 49 65535 0]Cuide de si mesmo la fora, tudo bem?[n]Nao apenas por seu proprio bem.[n][w][e]

[msg MSG_C13_BYEGREET_00_07_5 [Takemi]]
[s][bup 0 108 6 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 390][vp 8 0 1 50 65535 0]Cuide de si mesmo la fora, tudo bem?[n]Nao apenas por seu proprio bem.[n][w][e]

[msg MSG_C13_BYEGREET_01_00_5 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 51 65535 0]Oh, ei. Voce esta indo para casa[n]Amanha, certo?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 52 65535 0]Entao deixe-me fazer uma atualizacao.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 53 65535 0]Entao, sobre Miwa-chan: seus sintomas[n]comecou a desaparecer logo depois[n]administrando o novo medicamento.[n][w][e]

[sel SEL_C13_BYEGREET_01_01_5 top]
[s]Fico feliz em ouvir isso.[e]
[s]Ela esta curada?[e]
[s]Voce pode ve-la sorrir agora.[e]

[msg MSG_C13_BYEGREET_01_02_5 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 54 65535 0]Sim, estou aliviado tambem  e e tudo[n]Gracas a voce.[n][w][e]

[msg MSG_C13_BYEGREET_01_03_5 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 55 65535 0]Ela ainda nao esta totalmente melhor, mas... ela e[n]chegando la. Nao deveria demorar muito agora.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 56 65535 0]E e tudo gracas a voce.[n][w][e]

[msg MSG_C13_BYEGREET_01_04_5 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 57 65535 0]Sim... eu mal posso esperar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 58 65535 0]E tudo gracas a voce.[n][w][e]

[msg MSG_C13_BYEGREET_01_05_5 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 59 65535 0]Obrigado por me apoiar[n]Atraves de tudo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 60 65535 0]O mesmo vale para a situacao com[n]Oyamada... voce fez tudo[n]Voce poderia me ajudar com isso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 61 65535 0]Eu nao sei onde toda essa devocao[n]vem de. Talvez eu deva levar[n]uma sugestao de voce.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 62 65535 0]Aqui... eu quero que voce tenha isso.[n][w][e]

[msg MSG_C13_BYEGREET_01_06_5 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 63 65535 0]Voce salvou Miwa-chan. E justo que[n]Voce a conhece algum dia.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 64 65535 0]Vamos ver... uma vez que Miwa-chan esta melhor,[n]Talvez nos dois pudessemos fazer uma viagem[n]visitar voce.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 65 65535 0]Heh... mantenha sua saude sob controle.[n]Eu quero voce la para nos receber com[n]Um sorriso, ok?[n][w][e]

[msg MSG_C13_BYEGREET_01_07_5 [Takemi]]
[s][bup 0 108 1 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 500][vp 1 0 0 66 65535 0]Heh... mantenha sua saude sob controle.[n]Eu quero voce la para nos receber com[n]Um sorriso, ok?[n][w][e]

[msg MSG_C13_BYEGREET_02_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Desculpe... mas eu tenho um paciente chegando[n]para um exame.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 14032 65535 0]Se voce precisar de algo, volte[n]novamente em outro momento.[n][w][e]

[msg MSG_C13_BYEGREET_02_01 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14032 65535 0]Se voce precisar de algo, volte[n]novamente em outro momento.[n][w][e]

[msg MSG_C13_BYEGREET_03_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ouvi dizer que voce esta se mudando...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 14139 65535 0]Agradeco toda a sua ajuda com o[n]testes clinicos. Bem cuidar.[n][w][e]

[msg MSG_C13_BYEGREET_03_01 [Takemi]]
[s][bup 0 108 0 0 0][f 4 23 1 213 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 14139 65535 0]Agradeco toda a sua ajuda com o[n]testes clinicos. Bem cuidar.[n][w][e]

