[msg MSG_C09_SOJIRO_00_00_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9178 65535 0]Oh,[f 4 2].[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sobre meu tio, hum... eu quero[n]Va para lembrancas agora.[n][w][e]

[msg MND_C09_SOJIRO_00_00_01]
[s]Futaba e eu precisaremos entrar[n]Lembrancas, apenas nos dois...[n][w][e]
[s]Vai demorar muito e[n]perigoso. Nao e uma tarefa facil...[n][w][e]

[msg MSG_C09_SOJIRO_00_00_02 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entao, voce esta livre para ir hoje?[n][w][e]

[sel SEL_C09_SOJIRO_00_01_00 top]
[s]Vamos fazer isso.[e]
[s]Talvez outra hora.[e]

[msg MSG_C09_SOJIRO_00_02_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9031 65535 0]Obrigado.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Esta e uma questao familiar, entao eu[n]quero fazer isso sozinho com voce.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, e eu enviei meu tio um[n]carta anonima, entao o chamado[n]Parte do cartao e cuidada.[n][w][e]

[msg MSG_C09_SOJIRO_00_03_00 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9047 65535 0]Esta e uma questao familiar, entao eu[n]quero fazer isso sozinho com voce.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Podemos cuidar disso sempre que[n]voce tem tempo. Apenas me avise[n]Quando voce esta se sentindo bem.[n][w][e]

[msg MSG_C09_ODA_00_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Voce encontrou o rei? Nao e surpresa la.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entao, ele te disse como[n]derrubar esse trapaceiro?[n][w][e]

[msg MSG_C09_ODA_01_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1037 65535 0]Ele vai, em uma condicao:[n]Ele quer que nos o apresentemos[n]para os ladroes fantasmas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nao podemos simplesmente nos entregar[n]no entanto. E onde voce entra.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Talvez voce possa invadir a arma[n]Sobre servidor e fazer algo?[n][w][e]

[msg MSG_C09_ODA_02_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9114 65535 0]Mas nao poderemos conseguir[n]Em contato com ele dessa maneira...[n][w][e]

[sel SEL_C09_ODA_03_00 top]
[s]Poderiamos enviar a ele um cartao de visita.[e]
[s]Deixe evidencias de seus hackers.[e]

[msg MSG_C09_ODA_04_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Um cartao de visita...? O que sao[n]Nos vamos roubar?[n][w][e]

[msg MSG_C09_ODA_05_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9200 65535 0]Oh, que tal a pagina inicial?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu ja invadi isso,[n]Entao e tao bom quanto roubado![n][w][e]

[msg MSG_C09_ODA_06_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9098 65535 0]Isso seria facil, mas ele e[n]Realmente vai acreditar nisso?[n][w][e]

[msg MSG_C09_ODA_07_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]HM, ok. Vou escrever um cartao de chamada[n]dizendo que vamos roubar[n]A arma sobre a pagina inicial.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Depois disso, voce precisara deixar evidencias[n]que os ladroes fantasmas invadiram.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O rei nao tera escolha senao[n]Acreditar que realmente eramos nos.[n][w][e]

[msg MSG_C09_ODA_08_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9089 65535 0]Oooh, isso parece divertido.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vou colocar nosso logotipo cheirar[n]na parte superior da primeira pagina.[n][w][e]

[msg MSG_C09_ODA_09_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Perfeito. Vamos ver o rei.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, e nos o informaremos antes[n]conversamos com ele, entao espere pelo nosso[n]palavra para iniciar o hacking.[n][w][e]

[msg MSG_C09_ODA_10_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Tudo bem, voce pode contar comigo.[n][w][e]

[msg MSG_C09_ODA_99_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9114 65535 0]Voce ja foi e viu o rei?[n]Estou pronto para ir sempre que voce estiver.[n][w][e]

[msg MSG_C09_ODA_99_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Vamos ver o rei. Ele deveria[n]estar no arcade em Akiba.[n][w][e]

[msg MSG_C09_BEGIN_D00_10_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Yo,[f 4 2].[n][w][e]

[msg MSG_C09_BEGIN_D00_20_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Yo,[f 4 2]. Testes e apenas[n]sobre chegar, hein?[n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hum, esta tudo bem para voce nao ser[n]estudo? Talvez eu pudesse ajudar,[n]Se voce esta se sentindo pronto para isso.[n][w][e]

[sel SEL_C09_ACTION_D00_20_01 top]
[s]Isso soa bem.[e]
[s]Acho que vou passar.[e]

[msg MSG_C09_ACTION_D00_20_02 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Oooh, estou surpreso que voce tenha dito que sim![n]Bem, entao, entre no meu escritorio.[n][w][e]

[msg MSG_C09_ACTION_D00_21_02 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9043 65535 0]Mannn, e aqui eu estava pronto para[n]Obtenha meu estudo sobre.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Apenas deixe-me saber se voce mudar[n]Sua mente, ok?[n][w][e]

[msg MSG_C09_BEGIN_D00_30_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9163 65535 0]Ooh,[f 4 2]. Bem-vindo a casa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O que voce esta fazendo hoje?[n][w][e]

[msg MSG_C09_BEGIN_D00_30_01 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Oh de manha,[f 4 2].[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O que quer fazer hoje?[n][w][e]

[sel SEL_C09_ACTION_D00_31_00 top]
[s]Vamos sair.[e]
[s]Vamos para o metaverso.[e]
[s]Eu ainda nao decidi.[e]

[msg MSG_C09_ACTION_D00_31_10 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce sabe que estamos no meio de[n]uma operacao, certo? Tem certeza[n]Voce nao quer se infiltrar...?[n][w][e]

[sel SEL_C09_ACTION_D00_31_10 top]
[s]Nos ficaremos bem.[e]
[s]Na verdade, deixe-me repensar isso.[e]

[msg MSG_C09_ACTION_D00_31_11 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9045 65535 0]R-Really?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh, acho que nao posso reclamar muito[n]ja que voce vai ficar comigo.[n][w][e]

[msg MSG_C09_ACTION_D00_31_12 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9063 65535 0]Entendido. Deixe-me saber se[n]Alguma coisa muda, ok?[n][w][e]

[msg MSG_C09_BEGIN_D00_40_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Ei[f 4 2], deveriamos ser muito[n]Protegendo nossa rota em breve.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce quer chamar os outros?[n][w][e]

[msg MSG_C09_BEGIN_D00_50_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Doce! Temos uma rota para nos mesmos![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tudo o que temos que fazer e enviar o chamado[n]cartao. Voce quer se encontrar no esconderijo?[n][w][e]

[sel SEL_C09_ACTION_D00_99_00 top]
[s]Vamos fazer isso.[e]
[s]Talvez mais tarde.[e]

[msg MSG_C09_ACTION_D00_99_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ok, vou mandar uma mensagem para todos![n][w][e]

[msg MSG_C09_ACTION_D00_31_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9098 65535 0]Quanto mais cedo protegemos nossa rota,[n]o melhor. Avise-nos quando voce[n]sua programacao esta definida, ok?[n][w][e]

[msg MSG_C09_ACTION_D00_41_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9114 65535 0]Ei, nao se esqueca que estamos no[n]meio de uma operacao agora.[n]Precisamos de um plano de jogo, cara![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quero dizer, voce e o tipo de cara para[n]Procrastina em sua licao de casa[n]Ate o dia anterior ao vencimento?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]De qualquer forma, deixe-nos saber quando voce[n]descobriu um cronograma, ok?[n][w][e]

[msg MSG_C09_ACTION_D00_51_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9098 65535 0]Por que nao enviamos o chamado[n]cartao e terminar isso?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]De qualquer maneira, apenas nos avise quando[n]Voce decide em que dia estamos entrando.[n][w][e]

[msg MSG_C09_BEGIN_D00_60_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9067 65535 0]Fizemos tudo o que podemos... agora, esperamos.[n][w][e]

[msg MSG_C09_BEGIN_D06_50_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Acabamos de esperar pelo nosso[n]dia programado agora.[n][w][e]

[msg MSG_C09_BEGIN_D07_10_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh,[f 4 2].[n][w][e]

[msg MSG_C09_BEGIN_D07_20_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Yo,[f 4 2]. Testes e apenas[n]sobre chegar, hein?[n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hum, esta tudo bem para voce nao ser[n]estudo? Talvez eu pudesse ajudar,[n]Se voce esta se sentindo pronto para isso.[n][w][e]

[sel SEL_C09_ACTION_D07_20_01 top]
[s]Isso soa bem.[e]
[s]Acho que vou passar.[e]

[msg MSG_C09_ACTION_D07_20_02 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Oooh, estou surpreso que voce tenha dito que sim![n]Bem, entao, entre no meu escritorio.[n][w][e]

[msg MSG_C09_ACTION_D07_21_02 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9043 65535 0]Mannn, e aqui eu estava pronto para[n]Obtenha meu estudo sobre.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Apenas deixe-me saber se voce[n]Mude de ideia, ok?[n][w][e]

[msg MSG_C09_BEGIN_D07_30_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9163 65535 0]Yo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O que quero fazer hoje,[f 4 2]?[n][w][e]

[sel SEL_C09_ACTION_D07_31_00 top]
[s]Vamos sair.[e]
[s]Vamos para o metaverso.[e]
[s]Eu ainda nao decidi.[e]

[msg MSG_C09_ACTION_D07_31_10 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9197 65535 0]Espere, nao seria ruim se alguem[n]viu voce? Estamos no meio de[n]Todo o nosso plano de infiltracao, voce sabe.[n][w][e]

[sel SEL_C09_ACTION_D07_31_10 top]
[s]Nos ficaremos bem.[e]
[s]Na verdade, deixe-me repensar isso.[e]

[msg MSG_C09_ACTION_D07_31_11 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]R-Really?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh, acho que nao posso reclamar muito[n]ja que voce vai ficar comigo.[n][w][e]

[msg MSG_C09_ACTION_D07_31_12 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9063 65535 0]Entendido. Deixe-me saber se[n]Alguma coisa muda, ok?[n][w][e]

[msg MSG_C09_BEGIN_D07_40_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Nao sera um problema se nos[n]Nao se mexa logo?[n][w][e]

[msg MSG_C09_BEGIN_D07_50_00 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9189 65535 0]Vamos enviar o chamado[n]cartao,[f 4 2]! Mae... Sojiro...[n]Eu preciso vingar a todos![n][w][e]

[sel SEL_C09_ACTION_D07_99_00 top]
[s]Vamos fazer isso.[e]
[s]Talvez mais tarde.[e]

[msg MSG_C09_ACTION_D07_99_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Ok, vou mandar uma mensagem para todos![n][w][e]

[msg MSG_C09_ACTION_D07_31_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9098 65535 0]Quanto mais cedo protegemos nossa rota,[n]o melhor. Avise-nos quando voce[n]sua programacao esta definida, ok?[n][w][e]

[msg MSG_C09_ACTION_D07_41_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9114 65535 0]Ei, nao se esqueca que estamos no[n]meio de uma operacao agora.[n]Precisamos de um plano de jogo, cara![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quero dizer, voce e o tipo de cara para[n]Procrastina em sua licao de casa[n]Ate o dia anterior ao vencimento?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]De qualquer forma, deixe-nos saber quando voce[n]descobriu um cronograma, ok?[n][w][e]

[msg MSG_C09_ACTION_D07_51_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9098 65535 0]Por que nao enviamos o chamado[n]cartao e terminar isso?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]De qualquer maneira, apenas nos avise quando[n]Voce decide em que dia estamos entrando.[n][w][e]

[msg MSG_C09_BEGIN_D07_60_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Tudo esta terminado, certo? Tudo[n]Temos que fazer agora e esperar como sempre![n][w][e]

[msg MSG_C09_BEGIN_D10_50_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Acabamos de esperar pelo nosso[n]dia programado agora.[n][w][e]

[msg MSG_C09_BEGIN_D10_00_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Yo,[f 4 2].[n][w][e]

[msg MSG_C09_BEGIN_D10_10_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Ei[f 4 2], o que nos fazemos?[n]Quero dizer, sobre o Dr. Maruki...?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nesse ritmo, sua atualizacao vai[n]assumir a realidade. E nao podemos deixar isso[n]acontecer![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce quer ir para o palacio agora?[n]Ou...[n][w][e]

[sel SEL_C09_ACTION_D10_10_01 top]
[s]Vamos sair.[e]
[s]Vamos para o metaverso.[e]
[s]Eu ainda nao decidi.[e]

[msg MSG_C09_BEGIN_D10_10_02 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9038 65535 0]Uau! S-seriamente!?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce nao esta preocupado com o Dr. Maruki[n]Deal, no entanto? Se baguncarmos isso, e[n]para todos.[n][w][e]

[sel SEL_C09_ACTION_D10_10_03 top]
[s]Nos ficaremos bem.[e]
[s]Na verdade, deixe-me repensar isso.[e]

[msg MSG_C09_BEGIN_D10_10_04 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]D-Dang! Nada chega ate voce, hein?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bem, acho que nao queremos[n]Tambem pense nessas coisas. Sim, vamos[n]tire o dia de folga![n][w][e]

[msg MSG_C09_BEGIN_D10_10_05 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9063 65535 0]Entendido. Deixe-me saber se alguma coisa[n]muda, ok?[n][w][e]

[msg MSG_C09_BEGIN_D10_10_06 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Ok, vou mandar uma mensagem para todos![n][w][e]

[msg MSG_C09_BEGIN_D10_20_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Ei, ei, e quase o prazo[n]Dr. Maruki comecou para nos.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce nao acha que devemos comecar[n]muito em breve?[n][w][e]

[sel SEL_C09_ACTION_D10_20_01 top]
[s]Vamos fazer isso.[e]
[s]Talvez mais tarde.[e]

[msg MSG_C09_BEGIN_D10_20_02 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Ok, vou enviar textos para o grupo.[n]Vamos levar a realidade de volta![n][w][e]

[msg MSG_C09_BEGIN_D10_10_07 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9098 65535 0]Ei! Voce esta bem?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ainda temos algum tempo, mas voce tem que[n]Encontre uma maneira de garantir nossa rota![n][w][e]

[msg MSG_C09_BEGIN_D10_20_03 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9098 65535 0]Ei, voce percebe que o prazo esta chegando[n]para cima, certo? Nao podemos nos dar ao luxo de estragar[n]isto...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Apenas nos informe quando voce decidir.[n]Vamos quebrar a porta de Maruki![n][w][e]

[msg MSG_C09_BEGIN_COOPNG_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9114 65535 0]Ei, ha um anime que eu quero assistir[n]Esta noite, entao nao posso sair hoje.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Acho que posso definir meu DVR se voce[n]quero se encontrar com os outros... embora...[n]Apenas deixe-me saber com antecedencia, ok?[n][w][e]

[msg MSG_C09_COOP_00_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 24 1 209 0 16 0 100][f 4 10 65535 0 0][vp 8 2 1 9110 65535 0]Voce esta voltando para LeBlanc?[n]Vamos falar se voce tiver algum tempo.[n][w][e]

[msg MSG_C09_COOP_10_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9110 65535 0]Bem-vindo a casa. Vamos falar se voce[n]tenho tempo.[n][w][e]

[msg MSG_C09_COOP_10_11 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9003 65535 0]Heheh, sonolento! Vamos falar um pouco[n]Se voce tem tempo.[n][w][e]

[msg MSG_C09_COOP_10_01 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9080 65535 0]Ola, namorado.[n]Quer se divertir?[n][w][e]

[msg MSG_C09_COOP_01_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, esta certo.[n][w][e]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hum, bem...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Desculpe pelo que aconteceu em[n]Akihabara. Eu realmente estraguei tudo...[n][w][e]

[msg MSG_C09_COOP_01_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Futaba parece realmente deprimido...[n]Talvez voce deva anima-la.[n][w][e]

[msg MND_C09_COOP_01_10]
[s]Eu posso ser capaz de confortar Futaba[n]se meu[f 4 11 4][clr 26][f 4 12 4][clr 27]nos estamos[clr 26][f 4 13 4 4][clr 27]...[n][w][e]

[msg MSG_C09_COOP_01_11 [Futaba]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Estou bem, eu prometo! Nao se preocupe,[n][f 4 2]! Nao se preocupe, Futaba![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9027 65535 0]......[n][w][e]

[msg MND_C09_COOP_01_20]
[s]Eu deveria ser capaz de encontrar o[n]palavras para confortar Futaba com meu[n]nivel atual de[f 4 11 4][clr 26][f 4 12 4][clr 27]...[n][w][e]
[s]Esta pode ser uma boa oportunidade[n]Para aprofundar meu vinculo com ela...[n][w][e]

[msg MSG_C09_COOP_01_21 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9027 65535 0]Aquele policial... ele era[n]Um nivel muito mais alto que eu...[n][w][e]

[sel SEL_C09_COOP_01_22 top]
[s]Apenas leve as coisas devagar.[e]
[s]Voce se saiu bem, Futaba.[e]

[msg MSG_C09_COOP_01_23 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sim... eu acho que voce esta certo...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quero dizer, eu ainda consegui comprar[n]Algumas coisas depois disso. Mas isso[n]so era porque voce estava la...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]De qualquer forma...[n][w][e]

[msg MSG_C09_COOP_01_30 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9018 65535 0]... podemos ir ate o seu quarto?[n]Eu quero falar com voce um pouco mais.[n][w][e]

[msg MSG_C09_COOP_02_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce tem algum tempo?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu quero ficar rachando nisso[n]Lista de promessas que fiz.[n][w][e]

[msg MSG_C09_COOP_03_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce tem algum tempo? Vamos manter[n]indo nessa lista de promessas.[n][w][e]

[msg MSG_C09_COOP_04_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Se voce e livre, e a lista de promessas[n]Tempo! O que devemos fazer em seguida?[n][w][e]

[msg MSG_C09_COOP_05_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, voce esta livre hoje?[n][w][e]

[msg MSG_C09_COOP_06_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh sim.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu desenterrei todo tipo de sujeira...[n]Sobre Kana-chan, e isso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Esta livre? Eu quero falar com[n]voce sobre isso.[n][w][e]

[msg MSG_C09_COOP_07_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, eu quero ir para lembrancas[n]e salve Kana-chan.[n][w][e]

[msg MND_C09_COOP_07_01]
[s]A resolucao de Futaba e firme. Deveriamos[n]va para lembrancas e mude os coracoes[n]dos pais de Kana-chan...[n][w][e]

[msg MSG_C09_COOP_07_10 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mwehehe! Voce esta livre, certo?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ha algo que eu realmente quero[n]fale com voce sobre. Seria incrivel[n]Se voce pudesse reservar algum tempo para mim.[n][w][e]

[msg MSG_C09_COOP_08_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce tem algum tempo?[n]Eu acho que quero falar...[n][w][e]

[msg MSG_C09_COOP_09_00 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei,[f 4 2]! Estou pronto![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vamos fazer a ultima coisa no[n]Lista de promessas![n][w][e]

[msg MSG_C09_COOP_09_01 [Futaba]]
[s][bup 0 8 6 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]H-hey la, coisas quentes.[n]Voce tem algum tempo?[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]... er, isso soou estranho?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]A-Wayway, terminei a lista de promessas![n]Entao, voce tem tempo...?[n][w][e]

[msg MND_COOP_DOUZOKUSEI]
[s]Eu sinto que posso me aproximar[n]Futaba gracas ao[var 2][n]Persona[clr 1][var 5][clr 27]...[n][w][e]

[msg MND_COOP_RANKUP_OK]
[s]Eu me sinto como meu vinculo com Futaba[n]Vai ficar mais forte em breve...[n][w][e]

[msg MND_COOP_RANKUP_NG]
[s]Eu nao acho que meu vinculo com[n]Futaba vai se aprofundar ainda...[n][w][e]

[msg MND_COOP_RANK_MAX_00]
[s]Eu tenho um vinculo forte[n]Com Futaba...[n][w][e]

[msg MND_COOP_RANK_MAX_01]
[s]Eu tenho um vinculo especial[n]Com Futaba...[n][w][e]

[msg MSG_COOP_SPOT_CHECK [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, voce nao descobriu um novo[n]Hangout Spot outro dia? Voce[n]deve tentar ir la algum dia.[n][w][e]

[msg MSG_COOP_CHECK_DUNGEON [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E bom fazer uma pausa de vez em quando.[n]Voce quer sair com Futaba?[n][w][e]

[msg MSG_COOP_CHECK_DAY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Qual e o plano? Voce vai[n]Para sair com Futaba?[n][w][e]

[msg MSG_COOP_CHECK_SHIDOU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ninguem pensa que voce esta vivo em[n]Este ponto, entao deve ficar bem[n]Contanto que voce seja cuidadoso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Qual e o plano? Voce vai[n]Para sair com Futaba?[n][w][e]

[sel SEL_COOP_CHECK top]
[s]Sair com ela[e]
[s]Verifique o Bond com Futaba[e]
[s]Declinio[e]

[msg MSG_C09_YES_01_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]OK. Vamos la,[f 4 2].[n][w][e]

[msg MSG_C09_YES_02_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9060 65535 0]Entao vamos formar nosso plano de batalha.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entre no meu escritorio,[f 4 2].[n][w][e]

[msg MSG_C09_YES_03_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Ok, entao vamos segurar uma estrategia[n]reuniao em LeBlanc.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nao se preocupe, nao ha nenhum[n]clientes por ai agora.[n][w][e]

[msg MSG_C09_YES_04_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Tudo bem, hora de formular nosso[n]plano de ataque.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entre la! Va, va![n][w][e]

[msg MSG_C09_YES_05_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Apenas uma coisa deixou na lista de promessas...[n]"Ficar bem sem voce por perto."[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas antes disso, ha algo[n]Eu quero te mostrar,[f 4 2].[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9171 65535 0]Venha para o meu quarto.[n][w][e]

[msg MSG_C09_YES_06_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9030 65535 0]...Obrigado.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Venha para o meu quarto entao.[n]Eu vou te contar la.[n][w][e]

[msg MSG_C09_YES_07_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9137 65535 0]Ok![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vamos para o seu quarto entao.[n][w][e]

[msg MSG_C09_YES_08_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Vamos fazer isso no seu quarto.[n][w][e]

[msg MSG_C09_YES_09_00 [Futaba]]
[s][bup 0 8 7 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9027 65535 0]Th--ha muito sobre o qual temos que falar![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]... W-Wanna vinha para o meu quarto?[n][w][e]

[msg MSG_C09_YES_09_01 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]A ultima coisa na lista de promessas...[n]"Estando bem sem voce por perto"...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu acho que quero dar outra chance.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Estou chegando para voce, Akihabara![n][w][e]

[msg MSG_MORGANA_COOP_ESCAPE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bem, eu vou andar por ai.[n]Avise-me quando estiver pronto[n]deixar.[n][w][e]

[msg MSG_C09_SPOT_00_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9114 65535 0]Entao, o que vamos fazer hoje?[n][w][e]

[sel SEL_C09_SPOT_00_01 top]
[s]Vamos em algum lugar divertido.[e]
[s]Vamos para o meu quarto.[e]
[s]Vamos treinar nas proximidades.[e]

[msg MSG_C09_SPOT_00_10 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9022 65535 0]Voce quer dizer la fora...?[n]Onde voce vai me levar?[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Eu acho que vou ficar bem assumindo[n]multidoes se voce quiser tentar... desde que[n]Como voce esta la comigo,[f 4 2].[n][w][e]

[msg MSG_C09_MYROOM_00_00 [Futaba]]
[s][bup 0 8 7 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9087 65535 0]Seu quarto... sim, isso parece bom.[n][w][e]

[msg MSG_C09_YES_00_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9027 65535 0]Hm, deve estar em algum lugar com nao[n]Muitas pessoas... somos prolicamente bons[n]ao redor do bairro.[n][w][e]

[msg MSG_C09_YES_10_00 [Futaba]]
[s][bup 0 8 6 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9080 65535 0]Ola, namorado. Voce quer[n]Va tomar um cha comigo?[n][w][e]

[msg MSG_C09_YES_10_01 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Sim! Hmmm, eu me pergunto o que[n]Devemos falar sobre...[n][w][e]

[msg MSG_C09_COOP_CANCEL_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9063 65535 0]Oh, voce esta ocupado? Eu acho que esta tudo bem...[n][w][e]

[msg MSG_C09_BEGIN_D10_REV [Futaba]]
[s][bup 0 8 3 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9178 65535 0]Oh,[f 4 2]...[n][w][e]

[msg MSG_C09_COOP_10_00_REV [Futaba]]
[s][bup 0 8 3 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 54719 65535 0]Voce tem algum tempo agora?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ha algo que eu quero falar com voce[n]cerca de. E realmente importante...[n][w][e]

[msg MND_COOP_RANK_MAX__REV]
[s]Parece que Futaba tem algo[n]importante me dizer...[n][w][e]

[msg MSG_COOP_CHECK_3RD_REV [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Isso parece serio...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O que voce vai fazer? Voce quer[n]Passar algum tempo com Futaba?[n][w][e]

[sel SEL_COOP_CHECK_REV top]
[s]Sair com ela[e]
[s]Verifique o Bond com Futaba[e]
[s]Declinio[e]

[msg MSG_C09_YES_10_00_REV [Futaba]]
[s][bup 0 8 3 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Obrigado... entao venha para o meu ro [n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Na verdade, espere... voce pode vir um pouco[n]mais tarde,[f 4 2]?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vou deixar minha porta aberta, entao apenas entre.[n][w][e]

[msg MND_C09_YES_10_00_REV_00]
[s]Futaba rapidamente foi para casa.[n][w][e]

[msg MND_C09_YES_10_00_REV_01]
[s]......[n][w][e]
[s]Ela deveria ser boa agora...[n][w][e]

[msg MND_C09_YES_10_00_REV_02]
[s]Eu me pergunto se Futaba esta dentro...[n][w][e]
[s]Eu deveria entrar...[n][w][e]

[msg MSG_C09_YES_10_01_REV [Futaba]]
[s][vp 8 2 1 9174 65535 0][f 4 2]...?[n][w][e]
[s]......[n][w][e]
[s]...Voce pode entrar.[n][w][e]

[msg MSG_MORGANA_COOP_ESCAPE_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ok, entao vou tirar minha despedida... estou[n]deixando Lady Ann para voce.[n][w][e]

[msg MSG_C09_COOP_CANCEL_REV [Futaba]]
[s][bup 0 8 3 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9193 65535 0]OK. Desculpe, isso e tao repentino...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sempre que e bom,[f 4 2].[n]Eu estarei esperando.[n][w][e]

[msg MSG_C09_EVOLUTION_WAIT [Futaba]]
[s][bup 0 8 3 65535 0][f 4 23 1 209 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 9043 65535 0]Desculpe, eu quero pensar nas coisas[n]sozinho...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Se for uma emergencia, me avise.[n]Vou largar minhas outras coisas.[n][w][e]

[msg MSG_SPOT_OPEN_KANDA]
[s]Agora voce pode ir para[clr 2]Kanda[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_SHINJUKU]
[s]Agora voce pode ir para[clr 2]Shinjuku[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_AKIHABARA]
[s]Agora voce pode ir para[clr 2]Akihabara[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]

[msg MSG_SPOT_OPEN_INOKASHIRA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Parque Inokashira[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]

[msg MSG_SPOT_OPEN_OGIKUBO]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Ogikubo Ramen[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar de comer ramen[n]Para sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_ODAIBA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Parque Seasa de Odaiba[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar desses parques para[n]sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_UENO]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Museu Ueno[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode desfrutar de museus de arte[n]Para sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_TSUKISHIMA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Tsukishima Monja[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar de comer monjayaki[n]Para sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_HARAJUKU]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Harajuku Takenoko Street[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode desfrutar da Rua Takeko[n]Para sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_TYUKAGAI]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Motomachi Chinatown[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]

[msg MSG_SPOT_OPEN_MAIHAMA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Maihama Destinyland[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Asakusa[clr 27].[n][w][e]
[s]Voce tambem pode convidar pessoas que podem[n]Aproveite a rua Skytree ou Nakamise[n]Para sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_IKEBUKURO]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Ikebukuro Planetarium[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]

[msg MSG_SPOT_OPEN_MEIJIJINGU]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Santuario Meiji[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]
[s]Alem disso, voce pode passar[n]voce para prestar homenagem a[n]o santuario, se desejar.[n][w][e]

[msg MSG_SPOT_OPEN_SUIDOUBASH]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Cidade de Suidobashi Dome[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]

[msg MSG_SPOT_OPEN_SHIBUYA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Shibuya Wilton Hotel[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]

[msg MSG_SPOT_OPEN_GINZA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Barra de sushi de ginza[clr 27].[n][w][e]
[s]Voce tambem pode convidar pessoas que[n]pode gostar de comer sushi caro[n]Para sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_JINBOCHO]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Cidade do Livro JinboCho[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar la para[n]sair contigo.[n][w][e]
[s]Alem disso, voce pode passar[n]voce mesmo para fazer compras[n]Se voce deseja.[n][w][e]

[msg MSG_SPOT_OPEN_ICHIGAYA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Ichigaya Pisca de pesca[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode gostar de pescar para[n]sair com voce la.[n][w][e]
[s]Alem disso, voce pode passar[n]voce mesmo e tente sua mao em[n]pescar se voce escolher.[n][w][e]

[msg MSG_SPOT_OPEN_SHINAGAWA]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Aquario Shinagawa[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode aproveitar o aquario[n]Para sair com voce la.[n][w][e]

[msg MSG_SPOT_OPEN_NAKANO]
[s]Voce agora tem informacoes[n]Em um novo ponto de encontro:[n][clr 2]Distrito de construcao de comercio de Nakano[clr 27].[n][w][e]
[s]Voce tambem pode convidar as pessoas[n]quem pode aproveitar esse local[n]Para sair com voce la.[n][w][e]

[msg MSG_C09_VISIT_01_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 200 14 10 13 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Ei, eu vou relaxar aqui hoje. eu ate[n]trouxe algumas revistas de PC para matar o tempo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, eu tenho o suficiente para voce, a proposito.[n]Ha algumas coisas seriamente engenhosas[n]nessas coisas.[n][w][e]

[msg MND_C09_VISIT_01_01]
[s]Eu posso melhorar[n]minha[f 4 11 2][clr 26][f 4 12 2][clr 27]Se eu ler o[n]revistas de computador com Futaba...[n][w][e]
[s]Alem disso, isso pode ser um bom[n]chance de aprofundar meu vinculo com ela...[n][w][e]

[msg MSG_C09_VISIT_01_01 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 200 14 10 13 10][f 4 10 65535 0 0][vp 8 2 1 9110 65535 0]Entao, voce quer apenas relaxar e ler se[n]Nao estamos nos encontrando com os outros?[n][w][e]

[sel SEL_C09_VISIT_01_02 top]
[s]Isso soa bem.[e]
[s]Acho que vou passar.[e]

[msg MSG_C09_VISIT_01_03 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 200 14 10 13 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Ok! Hoje e uma leitura![n][w][e]

[msg MSG_C09_VISIT_02_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 200 14 10 13 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Eu vou passar algum tempo aqui[n]hoje, e eu trouxe um DVD comigo[n]para matar algum tempo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E um dos maiores filmes de terror[n]de todos os tempos! Eu nao estou totalmente com medo de[n]Assista sozinho, prometa![n][w][e]

[msg MND_C09_VISIT_02_01]
[s]Eu posso ser capaz de melhorar meu[f 4 11 3][clr 26][f 4 12 3][clr 27]E se[n]Eu assisto a um filme de terror com Futaba...[n][w][e]
[s]Alem disso, isso pode ser um bom[n]chance de aprofundar meu vinculo com ela...[n][w][e]

[msg MSG_C09_VISIT_02_01 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 200 14 10 13 10][f 4 10 65535 0 0][vp 8 2 1 9181 65535 0]Entao, voce quer assistir?[n][w][e]

[sel SEL_C09_VISIT_02_02 top]
[s]Isso soa bem.[e]
[s]Acho que vou passar.[e]

[msg MSG_C09_VISIT_02_03 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 200 14 10 13 10][f 4 10 65535 0 0][vp 8 2 1 9086 65535 0]Mwhehehe... eu tambem tenho lanches![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, e nao se preocupe. eu trouxe[n]muito para voce tambem,[f 4 2].[n][w][e]

[msg MSG_C09_VISIT_03_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 200 14 10 13 10][f 4 10 65535 0 0][vp 8 2 1 9002 65535 0]Ei, eu vou ficar por aqui hoje,[n]Entao eu trouxe um jogo bastante antigo para[n]matar o tempo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E intuicao de poder. Um verdadeiro controlador-[n]BUSLING PHUMP-MUNCHER![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce tem a coragem de me encontrar em[n]um teste de coragem?[n][w][e]

[msg MND_C09_VISIT_03_01]
[s]Eu posso ser capaz de melhorar meu[f 4 11 3][clr 26][f 4 12 3][clr 27][n]Se eu jogar Intuicao de poder com Futaba...[n][w][e]
[s]Alem disso, isso pode ser um bom[n]chance de aprofundar meu vinculo com ela...[n][w][e]

[msg MSG_C09_VISIT_03_01 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 200 14 10 13 10][f 4 10 65535 0 0][vp 8 2 1 9110 65535 0]Vamos, vamos abandonar a infiltracao[n]E volte com alguns jogos hoje![n][w][e]

[sel SEL_C09_VISIT_03_02 top]
[s]Isso soa bem.[e]
[s]Acho que vou passar.[e]

[msg MSG_C09_VISIT_03_03 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 200 14 10 13 10][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Caramba, sim! Vamos la, vamos![n][w][e]

[msg MSG_C09_VISIT_99_00 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 23 1 200 14 10 13 10][vp 8 2 1 9062 65535 0][f 4 10 65535 0 0]Awww, ok...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Acho que nos informe se voce estiver[n]vou se infiltrar...[n][w][e]

[msg MSG_C09_BYEGREET_00_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 1 65535 0][f 4 2], boas noticias![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]Kana-chan passou por ela[n]Exame de entrada da escola! Ela enviou[n]Eu uma mensagem esta manha![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]E a partir de abril, eu vou[n]Seja um ensino medio tambem! Conseguimos![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]Parece que vou poder manter[n]Minha promessa sobre ir para a escola![n][w][e]

[sel SEL_C09_BYEGREET_00_01 top]
[s]Deixe-me saber se voce precisar de ajuda.[e]
[s]Voce fara muito bem, Futaba.[e]
[s]Voce merece uma recompensa.[e]

[msg MSG_C09_BYEGREET_00_02 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]Mhm, vou contar com voce.[n][w][e]

[msg MSG_C09_BYEGREET_00_03 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Obrigado! E bom ouvir[n]isso de voce,[f 4 2].[n][w][e]

[msg MSG_C09_BYEGREET_00_04 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 7 65535 0]Ooh!? Gostaria disso...[n][w][e]

[msg MSG_C09_BYEGREET_00_05 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]Hum... eu gostaria que houvesse uma maneira de eu[n]poderia fazer voce ficar... mas eu vou[n]Mostre alguma autocontrole aqui.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 9 65535 0]Todas as apostas estao desligadas quando eu me formar[n]High School embora.[n][w][e]
[s][bup 0 8 6 65535 0][f 4 10 65535 0 0][vp 8 0 1 10 65535 0]Depois disso acontece, nos vamos[n]Fique juntos para sempre,[f 4 2]![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]... ate entao, aqui.[n][w][e]

[msg MSG_C09_BYEGREET_00_06 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]* Sniff* Ja va...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Meus oculos vao elogiar...[n][w][e]

[msg MSG_C09_BYEGREET_00_07 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 14 65535 0]Meus oculos vao elogiar...[n][w][e]

[msg MSG_C09_BYEGREET_01_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 15 65535 0][f 4 2], hum...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 16 65535 0]Kana-chan passou por ela[n]Exame de entrada da escola! Ela enviou[n]Eu uma mensagem esta manha![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 17 65535 0]E a partir de abril, eu vou[n]Seja um ensino medio tambem! Conseguimos![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 18 65535 0]Parece que vou poder manter[n]Minha promessa sobre ir para a escola![n][w][e]

[sel SEL_C09_BYEGREET_01_01 top]
[s]Parabens.[e]
[s]Tem certeza de que vai ficar bem?[e]
[s]Voce merece uma recompensa.[e]

[msg MSG_C09_BYEGREET_01_02 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 19 65535 0]Obrigado! Mesmo assim, e o que acontece[n]Em seguida, isso realmente conta... certo?[n][w][e]

[msg MSG_C09_BYEGREET_01_03 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 20 65535 0]Sabe, estou realmente super nervoso...[n]Mas e o que acontece a seguir que realmente[n]Conta, certo?[n][w][e]

[msg MSG_C09_BYEGREET_01_04 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 21 65535 0]Seriamente...!? Mesmo assim, e o que[n]acontece a seguir que realmente conta...[n]certo?[n][w][e]

[msg MSG_C09_BYEGREET_01_05 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 22 65535 0]Enfim... eu vou fazer o meu melhor[n]no ensino medio. Vou me certificar de[n]Use tudo o que voce me ensinou.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 23 65535 0]Depois de cumprir minha promessa de ir para[n]ensino medio... eu estarei por vir[n]essa recompensa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 24 65535 0]... ate entao, aqui.[n][w][e]

[msg MSG_C09_BYEGREET_01_06 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 25 65535 0]Cara, eu nao posso acreditar que voce e realmente[n]indo para casa amanha... tenho certeza que vai[n]Seja sozinho, mas voce se saira muito bem![n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 370][vp 8 0 1 26 65535 0]Venha sair comigo algum dia,[n]ok?[n][w][e]

[msg MSG_C09_BYEGREET_01_07 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 370][vp 8 0 1 27 65535 0]Venha sair comigo algum dia,[n]ok?[n][w][e]

[msg MSG_C09_BYEGREET_00_00_5 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 28 65535 0][f 4 2], boas noticias![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 29 65535 0]Kana-chan passou por ela[n]Exame de entrada da escola! Ela enviou[n]Eu uma mensagem esta manha![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 30 65535 0]Eu disse a ela que estava entrando no ensino medio[n]tambem, e ela diz que podemos fazer nosso[n]Os estudantes estream juntos![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 31 65535 0]Entao, eu fiz isso! Certo? Eu cumpri o[n]promete ir para o ensino medio?[n][w][e]

[sel SEL_C09_BYEGREET_00_01_5 top]
[s]E claro.[e]
[s]Excelente trabalho.[e]
[s]Vou pensar em uma recompensa.[e]

[msg MSG_C09_BYEGREET_00_02_5 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 32 65535 0]YESSSS! Missao completa![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 33 65535 0]... bem, a missao comecou, de qualquer maneira. eu ainda[n]Hafta realmente se formou.[n][w][e]

[msg MSG_C09_BYEGREET_00_03_5 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 34 65535 0]G-Good... e meio embaracoso,[n]no entanto...[n][w][e]

[msg MSG_C09_BYEGREET_00_04_5 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 35 65535 0]Oooh! Eu gosto do som disso![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 36 65535 0]Se voce precisar de ideias, sempre ha um ano[n]fornecimento de ramen instantaneo! Bem, eu vou deixar isso[n]voce decide.[n][w][e]

[msg MSG_C09_BYEGREET_00_05_5 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 37 65535 0]Se estou sendo honesto, estou realmente... realmente,[n]realmente nervoso com isso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 38 65535 0]Eu nao sei se posso fazer amigos, e o caminho[n]fora da minha zona de conforto, tudo que eu[n]Pense em me dar ansiedade...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 39 65535 0]Mas eu sei que nao posso ficar no meu quarto[n]para todo sempre. E isso e muito mais importante.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 40 65535 0]E eu quero entrar na faculdade. Formacao em[n]Psiencia cognitiva real. Como minha mae...[n]e Dr. Maruki.[n][w][e]

[msg MSG_C09_BYEGREET_00_06_5 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 41 65535 0]Por enquanto... vou desistir do meu caderno, e[n]essa recompensa. Aquele onde eu nao[n]Tenho que deixar voce, quero dizer.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 42 65535 0]E quando eu faco meu sonho se tornar realidade[n]um dia, quando eu ganhei, eu vou... eu vou[n]Leve os dois de volta.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 43 65535 0]Entao... e melhor voce nao chorar! Eu nao vou, e[n]Voce nao vai, e nos dois seremos[n]bem![n][w][e]

[msg MSG_C09_BYEGREET_00_07_5 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 44 65535 0]Entao... e melhor voce nao chorar! Eu nao vou, e[n]Voce nao vai, e nos dois seremos[n]bem![n][w][e]

[msg MSG_C09_BYEGREET_01_00_5 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 45 65535 0][f 4 2], boas noticias![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 46 65535 0]Kana-chan passou por ela[n]Exame de entrada da escola! Ela enviou[n]Eu uma mensagem esta manha![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 47 65535 0]Eu disse a ela que estava entrando no ensino medio[n]tambem, e ela diz que podemos fazer nosso[n]Os estudantes estream juntos![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 48 65535 0]Entao, voce conhece essa promessa no livro?[n]Aquele sobre ir para a escola? este[n]significa, como... eu fiz isso, certo?[n][w][e]

[sel SEL_C09_BYEGREET_01_01_5 top]
[s]E claro.[e]
[s]Excelente trabalho.[e]
[s]Vou pensar em uma recompensa.[e]

[msg MSG_C09_BYEGREET_01_02_5 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 49 65535 0]YESSSS! Missao completa![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 50 65535 0]Bem, a missao comecou, de qualquer maneira. eu ainda[n]Hafta realmente se formou.[n][w][e]

[msg MSG_C09_BYEGREET_01_03_5 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 51 65535 0]Entao, eu sou incrivel, certo!? Posso pegar isso[n]por escrito?[n][w][e]

[msg MSG_C09_BYEGREET_01_04_5 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 52 65535 0]Ooh, parece bom para mim![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 53 65535 0]Entao eu tenho outra coisa para olhar[n]para a frente. E melhor ser bom! Nao[n]Deixe-me cair,[f 4 2]![n][w][e]

[msg MSG_C09_BYEGREET_01_05_5 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 54 65535 0]Honestamente, embora... a ideia de nao[n]tendo sojiro ou todos os outros por perto[n]e a parte mais assustadora.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 55 65535 0]Mas eu sei que nao posso ficar no meu quarto[n]para todo sempre. E isso e muito mais importante.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 56 65535 0]Eu sinto que... eu tenho recebido mais[n]curioso todos os dias. Eu quero ver e[n]Aprenda muita coisa...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 57 65535 0]Entao, eu quero que voce tenha isso. E prova de que sou[n]se movendo![n][w][e]

[msg MSG_C09_BYEGREET_01_06_5 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 58 65535 0]Porque eu so mudei muito obrigado[n]para o caderno. E voce, e claro.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 59 65535 0]Se voce se sentir sozinho, apenas olhe para isso[n]caderno e lembre-se de que eu tenho[n]suas costas. Ok?[n][w][e]

[msg MSG_C09_BYEGREET_01_07_5 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 370][vp 8 0 1 60 65535 0]Se voce se sentir sozinho, apenas olhe para isso[n]caderno e lembre-se de que eu tenho[n]suas costas. Ok?[n][w][e]

[msg MSG_C09_BYEGREET_02_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cara, eu nao posso acreditar que voce e realmente[n]indo para casa amanha... tenho certeza que vai[n]Seja sozinho, mas voce se saira muito bem![n][w][e]
[s][f 4 10 65535 0 400][vp 8 2 1 37419 65535 0]Mesmo depois de morrer e ir embora, nos vamos[n]Ainda sao os ladroes fantasmas... certo?[n][w][e]

[msg MSG_C09_BYEGREET_02_01 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 23 1 209 14 10 13 10][f 4 10 65535 0 400][vp 8 2 1 37419 65535 0]Mesmo depois de morrer e ir embora, nos vamos[n]Ainda sao os ladroes fantasmas... certo?[n][w][e]

