[msg KARIOKI_NPC_grt00]
[s]......[n][w][e]

[msg KARIOKI_NPC_talk00]
[s]テスト用仮配置NPCです。[n][w][e]

[msg MSG_GREET_TEST_000_00]
[s]Eu ouvi dizer que ele realmente machucou alguem?[n]Ele deve ser perigoso...[n][f 1 7 30][e]

[msg MSG_GREET_TEST_001_00]
[s]Tente nao fazer contato visual. Seria ruim[n]Se voce se envolveu com esse cara.[n][f 1 7 30][e]

[msg MSG_GREET_TEST_002_00]
[s]Nao vamos chegar muito perto dele...[n][f 1 7 30][e]

[msg MSG_GREET_TEST_003_00]
[s]Estou tao feliz que ele nao esta sentado perto de mim.[n][f 1 7 30][e]

[msg MSG_GREET_TEST_004_00]
[s]Prefiro nao me envolver com ele...[n][f 1 7 30][e]

[msg MSG_GREET_TEST_005_00]
[s]Ele parece quieto, mas ouvi ele[n]atacou alguem...[n][f 1 7 30][e]

[msg MSG_GREET_TEST_006_00]
[s]Ele nao tentara falar conosco,[n]ele vai...?[n][f 1 7 30][e]

[msg MSG_GREET_TEST_007_00]
[s]A policia teve que vir e dete-lo?[n]Isso e loucura![n][f 1 7 30][e]

[msg MSG_GRT_SCH_WEATHER_AME_]
[s][vp 8 2 65535 36950 0 0]Eu nao quero andar[n]la fora na chuva...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_AME__2]
[s][vp 8 2 65535 37000 0 0]Esta chovendo muito...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_YUKI]
[s][vp 8 2 65535 36987 0 0]Nao e de admirar que esteja tao frio. Esta nevando...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_YUKI_2]
[s][vp 8 2 65535 37038 0 0]Esta nevando...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_TSUY]
[s][vp 8 2 65535 36956 0 0]A estacao chuvosa e tao irritante...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_TSUY_2]
[s][vp 8 2 65535 37005 0 0]Eu odeio a estacao chuvosa...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_TYPH]
[s][vp 8 2 65535 36964 0 0]Havera um tufao em nosso[n]area?[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_TYPH_2]
[s][vp 8 2 65535 37011 0 0]E melhor eu chegar em casa rapidamente, pois havera[n]Um tufao...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_KAHU]
[s][vp 8 2 65535 36972 0 0]Ha muito polen no ar...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_KAHU_2]
[s][vp 8 2 65535 37023 0 0]Ha muito polen hoje...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_GERI]
[s][vp 8 2 65535 36959 0 0]Uau, esta derramando...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_GERI_2]
[s][vp 8 2 65535 37015 0 0]Eu odeio quando comeca a chover tudo[n]repentino...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_HEAT]
[s][vp 8 2 65535 36980 0 0]Este calor nao e brincadeira...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_HEAT_2]
[s][vp 8 2 65535 37032 0 0]Esta muito quente novamente este ano...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_VIRU]
[s][vp 8 2 65535 36978 0 0]Droga... estou vindo[n]com a gripe?[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_VIRU_2]
[s][vp 8 2 65535 37029 0 0]Eu ouco a gripe que esta acontecendo[n]Este ano e terrivel...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_CLASSMATE_01]
[s][vp 8 2 65535 42702 0 0]As pessoas estao dizendo que ele foi preso por[n]atacando alguem. Ele e um serio[n]Criminoso...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_CLASSMATE_02]
[s][vp 8 2 65535 43002 0 0]Ouvi dizer que ele esta sendo expulso.[n][f 1 2 180][e]

[msg MSG_SEASON_GOODS_001_01 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Existem tantas lojas aqui, as vezes[n]Eu me perdi enquanto estou tentando escolher[n]onde ir...[n][w][e]
[s][vp 8 2 1 0 7 0]Eu me pergunto se posso encontrar em qualquer lugar bom[n]comer...[n][w][e]

[msg MSG_SEASON_GOODS_001_02 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Eu sei tudo sobre como encontrar as melhores coisas[n]comer! Voce deve procurar tempo limitado[n]Especiais![n][w][e]
[s][vp 8 2 1 0 8 0]Especiais de tempo limitado geralmente sao realmente[n]delicioso, e voce pode obte-los por[n]um desconto![n][w][e]
[s][vp 8 2 1 0 8 0]Sempre que quiser, eu vou te dizer se houver[n]quaisquer especiais de tempo limitado que voce possa[n]quero tentar![n][w][e]

[msg MSG_SEASON_GOODS_001_03 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Serio? Legal, mal posso esperar![n][w][e]

[msg MSG_SEASON_GOODS_002_01 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]* Suspiro* As atividades do clube estao me matando.[n]Ha algo que eu posso me aliviar[n]exaustao?[n][w][e]

[msg MSG_SEASON_GOODS_002_02 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Se for esse o caso, por que voce nao tenta[n]oleo corporal chamado[clr 2][var 0][clr 27]?[n][w][e]
[s][vp 8 2 1 0 8 0]Voce pode encontra-lo na loja de cosmeticos em[n]O shopping subterraneo da estacao Shibuya.[n][w][e]

[msg MSG_SEASON_GOODS_002_03 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Oleo corporal? Huh. Acho que vou dar[n]uma tentativa da proxima vez...[n][w][e]

[msg MSG_SEASON_GOODS_002_04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Uau, oleo corporal que pode aliviar[n]exaustao? Isso parece incrivel,[n]Voce nao concordaria?[n][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Esses dois sempre parecem falar[n]sobre alimentos e modismos. Pode pagar[n]sair para ouvi-los com frequencia.[n][w][e]

[msg MSG_SEASON_GOODS_003_01 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Entao, outro dia, eu verifiquei isso[n]A padaria chamada Yon-Germain.[n][w][e]
[s][vp 8 2 1 0 7 0]O sanduiche que eu tinha la... foi[n]Tao delicioso.[n][w][e]

[msg MSG_SEASON_GOODS_003_02 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Esse lugar tambem tem um limitado[n]Item vendido apenas em dias chuvosos.[n]E chamado[clr 2][var 1][clr 27].[n][w][e]
[s][vp 8 2 1 0 8 0]Nao e tao conveniente que[n]Yon-Germain esta localizado[n]Na estacao Shibuya?[n][w][e]

[msg MSG_SEASON_GOODS_003_03 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Wowww, eu nao sabia que eles tinham um[n]Pao de tempo limitado vendido apenas em chuva[n]dias. Eu vou quando chover![n][w][e]

[msg MSG_SEASON_GOODS_004_01 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]* suspiro* o time de volei esta indo[n]Atraves de uma bagunca tao grande agora...[n][w][e]
[s][vp 8 2 1 0 7 0]Eu estava pensando em ir para Shibuya[n]com meus amigos para limpar minha cabeca, mas...[n][w][e]
[s][vp 8 2 1 0 7 0]Voce sabe se ha algum sazonal[n]bens ou promocoes em Shibuya?[n][w][e]

[msg MSG_SEASON_GOODS_004_02 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Vamos ver. Se voce esta saindo[n]Com seus amigos, voce deveria[n]Experimente o Big Bang Burger.[n][w][e]
[s][vp 8 2 1 0 8 0]Seu item de primavera,[clr 2][var 0][clr 27], Assim,[n]e saudavel e delicioso.[n][w][e]
[s][vp 8 2 1 0 8 0]E muito grande, por isso e perfeito para compartilhar.[n]Voce pode encontrar um Big Bang Burger em[n]Rua Central.[n][w][e]

[msg MSG_SEASON_GOODS_004_03 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Big Bang Burger, hein? Soa bem.[n]Obrigado, vou experimentar![n][w][e]

[msg MSG_SEASON_GOODS_005_01 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Eu tenho me sentido ultimamente. Houve[n]o incidente de Kamoshida, e agora tudo isso[n]casos de fraude...[n][w][e]
[s][vp 8 2 1 0 7 0]Estao os lugares que vendem qualquer coisa especial[n]Para a primavera? Algo gostoso[n]vai me animar.[n][w][e]

[msg MSG_SEASON_GOODS_005_02 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Voce conhece um lugar chamado[n]Super Muramasa?[n][w][e]
[s][vp 8 2 1 0 8 0]E um[clr 2]supermercado[clr 27]elas[n]terminou em Yongen-Jaya.[n][w][e]
[s][vp 8 2 1 0 8 0]Seus[clr 2][var 0][clr 27]gostaria[n]Provavelmente faca apenas o truque.[n][w][e]

[msg MSG_SEASON_GOODS_005_03 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Frutas, hein...? Aproveitando algumas frutas[n]Parece bom e relaxante...[n][w][e]

[msg MSG_SEASON_GOODS_006_01 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]E quase a estacao chuvosa... mas o[n]A chuva constante me incomoda, e eu nao[n]quero fazer qualquer coisa...[n][w][e]

[msg MSG_SEASON_GOODS_006_02 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]O que voce esta falando!? O chuvoso[n]A temporada e a hora de comprar chuva limitada[n]Mercadorias diarias![n][w][e]
[s][vp 8 2 1 0 8 0]De fato, ha um tempo limitado[n][clr 2][var 1][clr 27]Isso e vendido em Shibuya[n]Nivel subterraneo da estacao![n][w][e]

[msg MSG_SEASON_GOODS_006_03 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Uau, voce realmente sabe muito sobre[n]Especiais. Ok, entao esta em Shibuya[n]Shopping Underground da estacao...[n][w][e]

[msg MSG_SEASON_GOODS_007_01 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]E quase Sumerrr.[n][w][e]
[s][vp 8 2 1 0 7 0]Falar sobre os ladroes Phantom era[n]sem parar durante a primavera. Vai isso[n]Va ate o verao?[n][w][e]

[msg MSG_SEASON_GOODS_007_02 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Os ladroes Phantom sao legais e tudo,[n]Mas o verao exige[clr 2][var 0][clr 27]![n][w][e]
[s][vp 8 2 1 0 8 0]Nao subestime seu sabor, apenas[n]Porque voce pode compra-lo em conveniencia[n]lojas...[n][w][e]

[msg MSG_SEASON_GOODS_007_03 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]E dificil dizer se eles estao quentes ou frios.[n]Esses macarrao nao sao frios, mas sao...[n]suavizante?[n][w][e]

[msg MSG_SEASON_GOODS_008_01 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Os ladroes Phantom estao pegando fogo[n]agora mesmo! Eles derrubaram isso[n]Grupo criminal tambem, certo?[n][w][e]
[s][vp 8 2 1 0 7 0]Agora e mais seguro ir para Shibuya.[n][w][e]

[msg MSG_SEASON_GOODS_008_02 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Falando nisso, o[clr 2][var 0][clr 27][n]vendido na padaria Yon-Germain[n]esta pegando fogo tambem![n][w][e]
[s][vp 8 2 1 0 8 0]E tao delicioso, o sabor vai trazer voce[n]de volta a vida! Ou pelo menos da beira[n]de morte.[n][w][e]

[msg MSG_SEASON_GOODS_008_03 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Uau, tao bom? E apenas pao, mas[n]Eu acho que nao deveria subestima-lo...[n][w][e]

[msg MSG_SEASON_GOODS_009_01 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Quao surpreendentes sao[n]os ladroes fantasmas?[n][w][e]
[s][vp 8 2 1 0 7 0]Foi aquele incidente com o Sr. Kamoshida[n]Apenas o comeco?[n][w][e]

[msg MSG_SEASON_GOODS_009_02 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Um estande na estacao Shibuya[n]estava vendendo[clr 2][var 0][clr 27].[n][w][e]
[s][vp 8 2 1 0 8 0]Ja estava perto de esgotar.[n]Eu acho que e assim que popular[n]Os ladroes Phantom sao...[n][w][e]

[msg MSG_SEASON_GOODS_009_03 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0][clr 2][var 0][clr 27]!?[n]Eu me pergunto se posso comprar[n]um a caminho de casa...[n][w][e]

[msg MSG_SEASON_GOODS_010_01 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]E tao deprimente, como nosso diretor morreu[n]Enquanto estavamos em uma viagem escolar...[n][w][e]
[s][vp 8 2 1 0 7 0]Em um momento como este, ha alguma coisa[n]Isso pegaria meu humor?[n][w][e]

[msg MSG_SEASON_GOODS_010_02 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Eu diria o[clr 2][var 0][clr 27][n]vendido no subterraneo de Shibuya[n]O shopping deve fazer o truque![n][w][e]
[s][vp 8 2 1 0 8 0]Deve afastar qualquer tipo de negativo[n]humor em um instante![n][w][e]

[msg MSG_SEASON_GOODS_010_03 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Entao e uma especie de terapia de aroma, hein?[n]Isso parece perfeito para mim[n]agora mesmo...[n][w][e]

[msg MSG_SEASON_GOODS_011_01 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Eu me pergunto se o Okumura Foods vai[n]ser alvo dos ladroes fantasmas.[n][w][e]
[s][vp 8 2 1 0 7 0]Se isso acontecer, sera o fim de[n]Os itens sazonais do Big Bang Burger?[n][w][e]

[msg MSG_SEASON_GOODS_011_02 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Voce sabe, Big Bang Burger nao e o unico[n]Local que serve itens sazonais.[n][w][e]
[s][vp 8 2 1 0 8 0]Nossa loja escolar tem um item de outono limitado[n]chamado[clr 2][var 0][clr 27], tambem![n][w][e]
[s][vp 8 2 1 0 8 0]E tao popular que eles sempre se esgotam.[n][w][e]

[msg MSG_SEASON_GOODS_011_03 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Uau, eles sao tao populares? Eu nunca[n]Visitei nossa loja da escola antes. Vou verificar[n]isso fora.[n][w][e]

[msg MSG_SEASON_GOODS_013_01 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Entao, o que esta acontecendo com Okumura[n]Alimentos desde aquele incidente?[n][w][e]
[s][vp 8 2 1 0 7 0]Big Bang Burger ainda esta aberto como de costume,[n]Nao e?[n][w][e]

[msg MSG_SEASON_GOODS_013_02 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Parece que eles ainda estao por perto. o[n]Presidente faleceu, mas que[n]Sozinho nao vai acabar com a empresa.[n][w][e]
[s][vp 8 2 1 0 8 0]Eles estao vendendo itens limitados para o outono[n]temporada, como o[clr 2][var 0][clr 27].[n][w][e]

[msg MSG_SEASON_GOODS_013_03 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]E verdade que os funcionarios nao fizeram nada[n]errado. Eu me sinto mal que o fantasma[n]Ladroes os direcionavam...[n][w][e]

[msg MSG_SEASON_GOODS_014_01 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Ei, eu vi uma maquina de venda automatica em Akihabara[n]vendendo[clr 2][var 0][clr 27]![n][w][e]
[s][vp 8 2 1 0 7 0]Ouvi dizer que e um item sazonal vendido apenas durante[n]O outono e o inverno![n][w][e]

[msg MSG_SEASON_GOODS_014_02 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]O que e aquilo...? Eu nunca ouvi falar de[n]algo assim antes...[n][w][e]
[s][vp 8 2 1 0 8 0]Parece que voce se tornou bem informado[n]sobre especiais de tempo limitado e sazonal,[n]tambem...[n][w][e]
[s][vp 8 2 1 0 8 0]Nao tenho mais nada para te ensinar. Tu es[n]agora um mestre, encarregado de compartilhar seu[n]Sabedoria com os outros...[n][w][e]

[msg MSG_SEASON_GOODS_014_03 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Oh fixe. Obrigado... mas o que isso faz isso[n]ate...?[n][w][e]

[msg MSG_SEASON_GOODS_015_01 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Nao parece que coisas boas foram[n]acontecendo um pouco com muita frequencia ultimamente? Fiz o[n]Inicio do ano novo muda nossa sorte...?[n][w][e]

[msg MSG_SEASON_GOODS_015_02 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Minha sorte certamente tem! Eu nao encontro nada alem de[n]itens limitados agora![n][w][e]

[msg MSG_SEASON_GOODS_015_03 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Mesmo com o inicio de um novo ano, voce ainda[n]Tudo sobre esses itens limitados, hein... entao, o que[n]tipos estao ai?[n][w][e]

[msg MSG_SEASON_GOODS_015_04 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Primeiro, ha o[clr 2][var 0][clr 27], Assim,[n]que e vendido na loja de conveniencia![n][w][e]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]E tao bonito que e quase uma pena comer![n][w][e]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]E o proximo e o[clr 2][var 1][clr 27], qual e[n]Vendido na loja chinesa de pao em Kichijoji![n]Por acaso eu sou regular la.[n][w][e]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Essa suculencia e praticamente viciante...[n][w][e]

[msg MSG_SEASON_GOODS_015_05 [Inquisitive Girl]]
[s][f 4 23 1 7 3 10 0 0][vp 8 2 1 0 7 0]Uau, ambos parecem incriveis![n]Parece que este ano esta comecando bem![n][w][e]

[msg MSG_SEASON_GOODS_015_06 [Foodie Girl]]
[s][f 4 23 1 8 14 0 13 0][vp 8 2 1 0 8 0]Provavelmente ha muito mais se voce tomar[n]a hora de olhar! Ah, sendo cercado por[n]itens alimentares limitados e uma felicidade...[n][w][e]

[msg MSG_KATAOMOI_001_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]O Sr. Kamoshida e mais popular do que nunca.[n]Ha uma multidao inteira que quer[n]Junte-se ao time de volei.[n][w][e]

[msg MSG_KATAOMOI_001_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Bem, ele e basicamente uma celebridade por perto[n]aqui. Alem disso, ele e muito bonito para[n]idade dele.[n][w][e]

[msg MSG_KATAOMOI_001_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Ele ate tem seu proprio crescente fa-clube.[n][w][e]

[msg MSG_KATAOMOI_001_3_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Bem, ele e algo sobre o qual podemos nos gabar[n]para nossos amigos. Voce nao esta feliz por termos decidido[n]ir para Shujin?[n][w][e]

[msg MSG_KATAOMOI_002_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Tentativa de suicidio... isso nao e louco?[n][w][e]
[s][vp 8 2 1 0 1 0]As meninas no fa clube do Sr. Kamoshida[n]estao realmente abalados... eu nao posso culpar[n]eles embora.[n][w][e]

[msg MSG_KATAOMOI_002_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Todas essas coisas assustadoras aconteceram desde[n]O semestre comecou. Entao ha isso[n]terrivel acidente...[n][w][e]

[msg MSG_KATAOMOI_002_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Estamos na mesma classe com isso realmente[n]pessoa assustadora tambem... sera um inferno de[n]um ano.[n][w][e]

[msg MSG_KATAOMOI_002_01_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Ouvi dizer que o Sr. Kamoshida tem sido[n]muito zangado.[n][w][e]
[s][vp 8 2 1 0 1 0]Parece[f 4 1]-kun,[n]Mishima-kun, e aquele delinquente[n]Sakamoto esta sendo expulso.[n][w][e]

[msg MSG_KATAOMOI_002_01_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Primeiro essa tentativa de suicidio, e agora[n]Problema de expulsao... o que diabos[n]indo?[n][w][e]

[msg MSG_KATAOMOI_002_01_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Tudo fica louco desde o[n]O aluno transferido chegou aqui. Por que[n]Ele vai contra o Sr. Kamoshida!?[n][w][e]

[msg MSG_KATAOMOI_003_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Kamoshida esta ausente hoje,[n]aparentemente. As meninas em seu fa[n]O clube parece tao deprimido.[n][w][e]
[s][vp 8 2 1 0 1 0]Eles jogaram sobre aquele chamado[n]cartao tambem. Eu nao pensei que eles sentiriam[n]isso fortemente sobre isso.[n][w][e]

[msg MSG_KATAOMOI_003_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Os jogadores de volei parecem[n]ansioso tambem. Eles ainda estao sendo[n]Realizado em suas salas de aula?[n][w][e]

[msg MSG_KATAOMOI_003_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Esse cartao de visita poderia ser verdadeiro?[n]Voce acha que o Sr. Kamoshida vai[n]confessar para fazer algo horrivel?[n][w][e]

[msg MSG_KATAOMOI_004_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Ele e o pior tipo de professor,[n]cometendo assedio sexual[n]enquanto fingia ser tao nobre.[n][w][e]

[msg MSG_KATAOMOI_004_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Eu sei. As coisas que ele fez provavelmente[n]Marcou aquelas garotas por toda a vida.[n][w][e]

[msg MSG_KATAOMOI_004_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Ele continuou batendo em Takamaki-san,[n]certo? Eu tive a ideia errada sobre[n]sua. Eu deveria me desculpar mais tarde...[n][w][e]

[msg MSG_KATAOMOI_004EX_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Dr. Maruki esta aqui para ajudar o sexual[n]vitimas de assedio, certo?[n][w][e]

[msg MSG_KATAOMOI_004EX_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Mas ele e um cara, certo...? Eu me pergunto se o[n]As meninas vao realmente falar com ele?[n][w][e]
[s][vp 8 2 1 0 0 0]Depois do que aconteceu, eles podem ser[n]medo de caras em geral, nao apenas[n]Sr. Kamoshida...[n][w][e]

[msg MSG_KATAOMOI_004EX_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Com base no que vi na assembleia[n]No entanto, ele parecia um cara serio[n]que voce poderia relaxar por ai...[n][w][e]

[msg MSG_KATAOMOI_005_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][f 4 25 1 2 0 0][vp 8 2 1 0 1 0]Ei, eu esqueci totalmente, mas[f 4 1]-kun[n]Nao foi expulso, nao e?[n][w][e]

[msg MSG_KATAOMOI_005_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Ei, nao tao alto. Ele esta aparecendo[n]com bastante regularidade, entao parece que ele sera[n]Ficar por ai.[n][w][e]

[msg MSG_KATAOMOI_005_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][f 4 25 1 2 0 0][vp 8 2 1 0 1 0]Eu vejo. Entao e a coisa sobre ele ter um[n]registro criminal nao e verdade, entao?[n][w][e]

[msg MSG_KATAOMOI_005_3_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Nao sei, estou com muito medo de perguntar.[n]Enfim, provavelmente e melhor nao conseguir[n]muito envolvido com ele.[n][w][e]

[msg MSG_KATAOMOI_006_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]* suspiro* tem um garoto que estou realmente[n]Interessado agora. Ele e[n]parecendo sonhado, super inteligente...[n][w][e]
[s][vp 8 2 1 0 1 0]Talvez ele seja um ano mais velho que eu,[n]Mas nao posso deixar de me sentir atraido por[n]Quao calmo e distante ele e.[n][w][e]

[msg MSG_KATAOMOI_006_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Oh, ele e um senpai da nossa escola?[n][w][e]

[msg MSG_KATAOMOI_006_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Nao, ele e uma celebridade que vai a isso[n]Escola super prestigiada. tenho uma[n]muita concorrencia.[n][w][e]

[msg MSG_KATAOMOI_006_01_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Ei, voce conhece aquele aluno de honra?[n]Qual era o nome dela... Yoshizawa-san?[n]O que voce pensa sobre ela?[n][w][e]

[msg MSG_KATAOMOI_006_01_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Hmm, ela e a ginastica, certo?[n]Eu nao a conheco tao bem, mas estou[n]Definitivamente torcendo por ela.[n][w][e]
[s][vp 8 2 1 0 0 0]Embora ultimamente... eu nao tenho um problema[n]Com a propria Yoshizawa, mas as pessoas[n]em quem a animar pode ser meio...[n][w][e]

[msg MSG_KATAOMOI_006_01_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Eu te entendo totalmente! Todo mundo a trata como[n]Ela e tao especial que meio que me deixa doente.[n][w][e]
[s][vp 8 2 1 0 1 0]Especialmente os caras...![n][w][e]

[msg MSG_KATAOMOI_007_0_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Eu ouvi dizer que Madarame foi enviado[n]cartao de chamada. E como o que[n]aconteceu com o Sr. Kamoshida.[n][w][e]
[s][vp 8 2 1 0 0 0]Voce acha que talvez o fantasma[n]Ladroes vao para a nossa escola? Isso[n]Seja emocionante, nao e?[n][w][e]

[msg MSG_KATAOMOI_007_1_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Isso e otimo e tudo, mas eu sou mais[n]animado com outra coisa.[n][w][e]
[s][vp 8 2 1 0 1 0]Nossa viagem de campo esta chegando, e[n]Eu quero ir ver a estacao de TV![n][w][e]

[msg MSG_KATAOMOI_007_2_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Akechi-kun e tao arrojado, tao inteligente[n]e garantido, e dificil de acreditar[n]Ele esta no ensino medio como nos.[n][w][e]

[msg MSG_KATAOMOI_007_3_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Certo? E como se ele fosse um principe. Ele e[n]o detetive principe![n][w][e]
[s][vp 8 2 1 0 1 0]Adoro ouvir aquele suave e[n]voz suave dele tambem! Eu desejo[n]Ele falava comigo assim.[n][w][e]

[msg MSG_KATAOMOI_007_4_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Mas voce sabe,[f 4 1]-kun[n]realmente debatido com Akechi-kun,[n]E ele nao fez muito mal.[n][w][e]

[msg MSG_KATAOMOI_008_0_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Ei, voce viu o Phantom[n]Site de ladroes? Voce pode realmente[n]Solicite-os para atingir alguem.[n][w][e]

[msg MSG_KATAOMOI_008_1_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Algo assim soa como[n]Isso pode levar a muitos problemas.[n]Akechi-kun mencionou isso tambem.[n][w][e]

[msg MSG_KATAOMOI_008_2_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Eu acho que parece que eles sao[n]muito perigoso, afinal...[n][w][e]
[s][vp 8 2 1 0 0 0]Houve uma enquete ou algo assim[n]sobre os ladroes Phantom, e[n]Muitas pessoas os apoiam.[n][w][e]

[msg MSG_KATAOMOI_009_0_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Eu ouvi os ladroes fantasmas[n]apareceu em Shibuya! Desta vez,[n]Eles estao mirando aquele chefe da mafia.[n][w][e]

[msg MSG_KATAOMOI_009_1_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Akechi-kun deve lidar com o[n]Mafia em vez do Phantom[n]Ladroes, mas talvez ele esteja muito ocupado.[n][w][e]

[msg MSG_KATAOMOI_009_2_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Quais sao os ladroes fantasmas[n]tentando alcancar? Eles sao apenas[n]Visando bandidos, ate agora.[n][w][e]

[msg MSG_KATAOMOI_009_3_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Talvez eles facam isso pela fama. Eu acho[n]Eles queriam aparecer akechi-kun[n]Depois que ele disse essas coisas na TV.[n][w][e]

[msg MSG_KATAOMOI_010_0_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Eu costumava ter medo de ir para[n]Shibuya, mas esta mais seguro agora,[n]Gracas aos ladroes Phantom.[n][w][e]
[s][vp 8 2 1 0 0 0]Parece que eles me salvaram novamente.[n]Acho que vou me tornar um fa do[n]Afinal, ladroes fantasmas.[n][w][e]

[msg MSG_KATAOMOI_010_1_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Espero que Akechi-kun nao seja tambem[n]Chocado de toda a reacao[n]Ele esta ficando online...[n][w][e]
[s][vp 8 2 1 0 1 0]Ainda vou acreditar em Akechi-kun,[n]no entanto! Quero dizer, ele e tao bonito![n]Tipo, ridiculamente bonito![n][w][e]

[msg MSG_KATAOMOI_011_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Medjed e um grupo perigoso, certo?[n]Lembro-me de ouvir que eles[n]Atos comprometidos de terrorismo.[n][w][e]
[s][vp 8 2 1 0 1 0]Akechi-kun estava dizendo aqueles hackers[n]apareceu novamente por causa do[n]Phantom Thieves.[n][w][e]

[msg MSG_KATAOMOI_011_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Hackers e Phantom Thieves Sound[n]Como algo fora de um manga.[n]E engracado se voce pensar sobre isso.[n][w][e]
[s][vp 8 2 1 0 0 0]Eu me pergunto quem venceria em uma luta. Um monte de[n]As pessoas online estao ficando animadas[n]tudo isso.[n][w][e]

[msg MSG_KATAOMOI_012_0_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 1 0]Eu tenho seguido noticias sobre o Phantom[n]Ladroes durante todo o verao. E dificil nao conseguir[n]varrido por isso.[n][w][e]
[s][vp 8 2 1 0 1 0]Estou surpreso que eles tenham recebido tao[n]famoso. Ninguem nem acreditou que eles[n]foram reais a principio.[n][w][e]

[msg MSG_KATAOMOI_012_1_0 [Energetic Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Estou envergonhado por ser um fa[n]de Akechi-kun...[n][w][e]
[s][vp 8 2 1 0 0 0]Agora e tudo sobre os ladroes fantasmas.[n]Vou anima-los o maximo que puder![n][w][e]

[msg MSG_KATAOMOI_013_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]O diretor realmente se comprometeu[n]suicidio? Eu ouvi alguem pode[n]o matou.[n][w][e]

[msg MSG_KATAOMOI_013_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Toda a loucura que esta acontecendo[n]esta me enlouquecendo. Voce pensa o[n]Phantom Thieves vai nos salvar de novo?[n][w][e]

[msg MSG_KATAOMOI_013_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Hmm, eles provavelmente estao muito ocupados[n]para nos agora. Primeiro, eles tem que[n]Concentre-se em Okumura![n][w][e]

[msg MSG_KATAOMOI_013_01_0_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Ei, eu ouvi Yoshizawa-san indo[n]Obtenha o status de seu aluno de honra revogado...[n][w][e]

[msg MSG_KATAOMOI_013_01_1_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Whoa, o que? Isso e tao cruel. Aposto ela[n]Os fas estao em choque...[n][w][e]
[s][vp 8 2 1 0 1 0]Esses caras costumavam me irritar, mas agora[n]Eu posso simpatizar com eles...[n][w][e]

[msg MSG_KATAOMOI_014_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]O presidente da Okumura Foods tem[n]Uma filha que vai para Shujin!? Fez[n]Voce sabe disso?[n][w][e]

[msg MSG_KATAOMOI_014_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Y-sim... eu sabia, mas... nao diga coisas[n]assim tao alto...[n][w][e]

[msg MSG_KATAOMOI_014_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]E tao chocante embora. Quero dizer, e tudo[n]conectado a nossa escola novamente.[n][w][e]
[s][vp 8 2 1 0 1 0]Agora que o presidente Okumura conseguiu isso[n]cartao de visita, o que voce acha que vai[n]acontecer?[n][w][e]

[msg MSG_KATAOMOI_015_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Os ladroes fantasmas realmente causaram[n]tudo isso? Quao crueis eles sao!?[n][w][e]

[msg MSG_KATAOMOI_015_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Pobre Okumura-San...[n][w][e]

[msg MSG_KATAOMOI_015_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Eles sao assassinos! Alguem precisa[n]Capture-os ja![n][w][e]

[msg MSG_KATAOMOI_015_3_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Nos nunca deveriamos ter virado nossas costas[n]em Akechi-kun. Tudo o que podemos fazer agora e perguntar[n]ele por ajuda...[n][w][e]

[msg MSG_KATAOMOI_016_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]... Entao, se a policia estivesse aqui o outro[n]dia, isso significa os ladroes fantasmas[n]Estavam aqui tambem, certo?[n][w][e]

[msg MSG_KATAOMOI_016_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Ah, nao diga isso. Eu fico com medo so por[n]pensando que eles poderiam estar a espreita por perto...[n][w][e]
[s][vp 8 2 1 0 0 0]Eu tenho escrito em todo o local do Phan,[n]pedindo aos ladroes fantasmas para dar[n]eles mesmos.[n][w][e]

[msg MSG_KATAOMOI_016_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Nao parece que a policia vai pegar[n]em breve. Eu desejo Akechi-kun[n]nos salvaria...[n][w][e]

[msg MSG_KATAOMOI_017_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Eu ouco que a policia pode vir ao nosso[n]escola de novo![n][w][e]

[msg MSG_KATAOMOI_017_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]De jeito nenhum... alguem esta sendo preso?[n][w][e]

[msg MSG_KATAOMOI_017_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Eu nao faco ideia. Se alguem esta ficando[n]preso, porem, espero que a policia leve[n]eles em breve.[n][w][e]

[msg MSG_KATAOMOI_017_3_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Se os ladroes fantasmas ouvem isso, nos[n]pode estar em perigo. Espero que nao entendamos[n]arrastado para essa bagunca.[n][w][e]

[msg MSG_KATAOMOI_018_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Entao, no final, Shido foi ruim[n]cara? Akechi-kun e uma fraude?[n][w][e]

[msg MSG_KATAOMOI_018_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Eu nem sei mais...[n]Aparentemente, os ladroes fantasmas[n]tambem eram apenas um boato na Internet.[n][w][e]

[msg MSG_KATAOMOI_018_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Ah bem. Todas essas coisas bonitas[n]Muito nao tem nada a ver conosco.[n][w][e]

[msg MSG_KATAOMOI_019_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Cara, os ladroes fantasmas e akechi-kun[n]foram o assunto do ano passado...[n][w][e]
[s][vp 8 2 1 0 1 0]O que voce acha que esta reservado para este ano?[n][w][e]

[msg MSG_KATAOMOI_019_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Aposto que vai ser completamente normal e[n]sem intercambio. Ate a noticia e super manso.[n][w][e]

[msg MSG_KATAOMOI_019_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Temos que comecar a tomar a entrada da faculdade[n]exames este ano. Provavelmente e melhor para nos[n]que nao ha drama.[n][w][e]

[msg MSG_KATAOMOI_020_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Eu me pergunto para onde Akechi-kun foi. Ele[n]nao esta na TV desde o inicio[n]Do ano...[n][w][e]

[msg MSG_KATAOMOI_020_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Sim, e preocupante que nao tenha havido[n]qualquer palavra dele. Existem ate[n]teorias circulando online que ele esta morto...[n][w][e]

[msg MSG_KATAOMOI_020_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Voce nao pode acreditar em tudo que ve[n]conectados. Afinal, os ladroes fantasmas[n]Foram apenas um boato na Internet, certo?[n][w][e]
[s][vp 8 2 1 0 1 0]Se Akechi-kun esta bem, espero que ele[n]apareca na TV de novo...[n][w][e]

[msg MSG_KATAOMOI_021_0_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Finalmente estamos em terceiro ano. Pensando sobre[n]Isso meio que me deixa ansioso.[n][w][e]

[msg MSG_KATAOMOI_021_1_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Espero que este ultimo ano letivo esteja cheio de[n]nada alem de bons momentos.[n][w][e]

[msg MSG_KATAOMOI_021_2_0 [Energetic Student]]
[s][f 4 23 1 1 3 10 0 0][vp 8 2 1 0 1 0]Sim, o ano passado foi bastante duro. eu digo[n]Saimos hoje e apenas comemos um monte[n]de sobremesas.[n][w][e]

[msg MSG_KATAOMOI_021_3_0 [Calm Student]]
[s][f 4 23 1 0 3 10 0 0][vp 8 2 1 0 0 0]Sim, vamos fazer isso! Comer doces acucarados[n]me deixa tao feliz![n][w][e]

[msg MSG_ANNNOYOUSHI_001_0_0 [Easygoing Student]]
[s][f 4 23 1 3 3 10 0 0][vp 8 2 1 0 3 0]E raro ver Takamaki na aula.[n]Ela geralmente desaparece imediatamente.[n][w][e]
[s][vp 8 2 1 0 3 0]Mas cara, ela e muito fofa... se ela[n]Era minha namorada, eu me gabaria de[n]o tempo todo.[n][w][e]

[msg MSG_ANNNOYOUSHI_001_1_0 [Lighthearted Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]Esqueca, idiota. Alem disso, namoro[n]ela seria muito problema.[n][w][e]
[s][vp 8 2 1 0 4 0]Ela meio que emite uma vibracao ruim, e[n]Todas as meninas a ignoram. E ela e[n]A garota de Kamoshida, lembra?[n][w][e]

[msg MSG_ANNNOYOUSHI_002_0_0 [Loud Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]Ela e muito bonita, e ela tem tanta coisa[n]muito estilo. Eu gostaria de ter nascido[n]Quarter-americano como ela.[n][w][e]

[msg MSG_ANNNOYOUSHI_002_1_0 [Sharp Student]]
[s][f 4 23 1 6 3 10 0 0][vp 8 2 1 0 6 0]Claro que ela teria todos os caras. Nao e[n]Tudo tao injusto? Ela ate tem o Sr.[n]Kamoshida.[n][w][e]

[msg MSG_ANNNOYOUSHI_002_2_0 [Loud Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]Falando nisso... Sr. Kamoshida[n]nao esta em hoje. Eu me pergunto se ele esta se sentindo doente.[n][w][e]

[msg MSG_ANNNOYOUSHI_002_3_0 [Sharp Student]]
[s][f 4 23 1 6 3 10 0 0][vp 8 2 1 0 6 0]O namorado dela fica doente e o melhor dela[n]Amigo tenta se matar... que pena.[n]Hahaha![n][w][e]

[msg MSG_GRT_main_All_001_01_ [Sharp Student]]
[s][vp 9 2 65535 42463 0 0]Cometendo assalto[n]e muito serio...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_02_ [Sharp Student]]
[s][vp 9 2 65535 42112 0 0]Entao, ele e a transferencia[n]Pessoas estudantis eram[n]Falando sobre online...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_04_ [Sharp Student]]
[s][vp 9 2 65535 42162 0 0]Ouvi dizer que ele foi preso por[n]assalto. Ele e um criminoso de verdade.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_05_ [Sharp Student]]
[s][vp 9 2 65535 42512 0 0]Espere, e isso o cara[n]que agrediu alguem?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_06_ [Sharp Student]]
[s][vp 9 2 65535 42963 0 0]Ei, e ele, nao e[n]isto? Aquele povo era[n]Falando sobre online...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_01_ [Sharp Student]]
[s][vp 9 2 65535 39605 0 0]Nao ha como saber quando[n]Ele pode se encaixar. Deveriamos[n]evite aquele cara...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_02_ [Sharp Student]]
[s][vp 9 2 65535 42862 0 0]Ate os professores[n]desisti dele.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_03_ [Sharp Student]]
[s][vp 9 2 65535 43013 0 0]Os rumores estavam certos...[n]Ele parece realmente perigoso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_04_ [Sharp Student]]
[s][vp 9 2 65535 42913 0 0]Eu nao quero me envolver[n]Com ele... ele e assustador.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_05_ [Sharp Student]]
[s][vp 9 2 65535 42863 0 0]Se ele for expulso,[n]Eu me sentiria tao aliviado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_06_ [Sharp Student]]
[s][vp 9 2 65535 43212 0 0]Ele realmente e[n]perigoso, nao e?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_01_ [Sharp Student]]
[s][vp 9 2 65535 43262 0 0]Sendo expulso[n]nao e algo isso[n]acontece todos os dias...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_02_ [Sharp Student]]
[s][vp 9 2 65535 43063 0 0]Ele ja comecou[n]causando problemas?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_03_ [Sharp Student]]
[s][vp 9 2 65535 42712 0 0]Ele nao vai de repente apenas[n]Comece a atacar pessoas, e?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_04_ [Sharp Student]]
[s][vp 9 2 65535 42363 0 0]Ele esta sendo expulso?[n]Aquele cara nao deve ter nenhum[n]remorso por seus crimes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_05_ [Sharp Student]]
[s][vp 9 2 65535 42562 0 0]Ele esta sendo expulso[n]ja? Isso e gentil[n]de impressionante, de certa forma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_06_ [Sharp Student]]
[s][vp 9 2 65535 43212 0 0]Aquele aluno transferido ja esta[n]sendo expulso da escola![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_01_ [Sharp Student]]
[s][vp 9 2 65535 38652 0 0]Por que alguem tocaria um[n]Prank no Sr. Kamoshida?[n]Isso e realmente muito estupido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_02_ [Sharp Student]]
[s][vp 9 2 65535 42703 0 0]Estou tendo uma boa risada[n]Desse bobagem do ladrao fantasma.[n]Espero que nao pare por aqui.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_04_ [Sharp Student]]
[s][vp 9 2 65535 42951 0 0]Ele brigou com[n]Sr. Kamoshida? Ele e estupido?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_05_ [Sharp Student]]
[s][vp 9 2 65535 40355 0 0]Provavelmente e apenas um[n]brincadeira por alguem que[n]Observa muito anime...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_06_ [Sharp Student]]
[s][vp 9 2 65535 38905 0 0]Um cartao de chamada Phantom Thief?[n]Isso e apenas uma brincadeira, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_01_ [Sharp Student]]
[s][vp 9 2 65535 38054 0 0]Por que Kamoshida de repente[n]decidir se desculpar assim?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_02_ [Sharp Student]]
[s][vp 9 2 65535 41705 0 0]Espere, aquele fantasma[n]A coisa do ladrao era de verdade?[n]Nao, isso e ridiculo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_03_ [Sharp Student]]
[s][vp 9 2 65535 44654 0 0]Por que ele estava agindo de repente[n]dessa maneira? Fez o fantasma[n]Ladroes o ameacam?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_04_ [Sharp Student]]
[s][vp 9 2 65535 42602 0 0]Voce pode acreditar nas coisas[n]Kamoshida disse que fez?[n]Ele e completamente horrivel![n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_05_ [Sharp Student]]
[s][vp 9 2 65535 40105 0 0]Voce nao pode roubar o coracao de alguem...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_06_ [Sharp Student]]
[s][vp 9 2 65535 43105 0 0]Essa brincadeira foi perfeitamente cronometrada...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_01_ [Sharp Student]]
[s][vp 9 2 65535 42362 0 0]Apenas deixe-o em paz...[n]Ele pode nao deixar voce[n]fora desta vez.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_02_ [Sharp Student]]
[s][vp 9 2 65535 42313 0 0]Eu gostaria que ele tivesse desaparecido[n]junto com Kamoshida.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_03_ [Sharp Student]]
[s][vp 9 2 65535 40302 0 0]Espere, ele realmente teve[n]Nada a ver com isso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_04_ [Sharp Student]]
[s][vp 9 2 65535 43362 0 0]Andando aqui como[n]Ele e dono do lugar... ele[n]Deveria ter sido expulso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_05_ [Sharp Student]]
[s][vp 9 2 65535 42513 0 0]Talvez ele nao tenha sido expulso,[n]Mas ele ainda tem isso[n]registro criminal...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_06_ [Sharp Student]]
[s][vp 9 2 65535 42613 0 0]Ouvi dizer que o aluno transferido[n]nao esta mais sendo expulso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_01_ [Sharp Student]]
[s][vp 9 2 65535 44755 0 0]Parece o time de volei[n]esta tendo problemas com tudo isso[n]Coisas de kamoshida acontecendo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_02_ [Sharp Student]]
[s][vp 9 2 65535 40103 0 0]O time de volei e[n]Terminado sem Kamoshida.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_04_ [Sharp Student]]
[s][vp 9 2 65535 38602 0 0]O time de volei vai[n]tem isso de agora em diante.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_05_ [Sharp Student]]
[s][vp 9 2 65535 40505 0 0]Eu nunca gostaria de me tornar[n]Conhecido pelo assedio sexual...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_06_ [Sharp Student]]
[s][vp 9 2 65535 38354 0 0]Eu acho que o time de volei nao vai[n]estar recebendo o tratamento real[n]Da nossa escola mais...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_01_ [Sharp Student]]
[s][vp 9 2 65535 40203 0 0]Se suas pinturas sao famosas,[n]Pode ser muito bom[n]Ideia para conferi-los.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_02_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_04_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_05_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_06_ [Sharp Student]]
[s][vp 9 2 65535 38004 0 0]Se as pessoas estao falando[n]sobre isso muito, faca[n]Voce quer dar uma olhada?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_01_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_02_ [Sharp Student]]
[s][vp 9 2 65535 38755 0 0]Outro e-mail de spam?[n]Qual e o problema com tudo isso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_04_ [Sharp Student]]
[s][vp 9 2 65535 42905 0 0]Alguns esquisitos tentaram comecar[n]Falando comigo em Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_05_ [Sharp Student]]
[s][vp 9 2 65535 38704 0 0]Ouvi dizer que eles sao realmente[n]Visando os alunos do ensino medio...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_06_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_01_ [Sharp Student]]
[s][vp 9 2 65535 39954 0 0]Era aquele ladrao fantasma[n]Cartao de chamada real?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_02_ [Sharp Student]]
[s][vp 9 2 65535 39804 0 0]Mencionou algo sobre o[n]Phantom Thieves. E kamoshida[n]realmente envolvido de alguma forma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_04_ [Sharp Student]]
[s][vp 9 2 65535 38254 0 0]Kamoshida e[n]Madarame... talvez Phantom[n]Ladroes realmente existem...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_05_ [Sharp Student]]
[s][vp 9 2 65535 39103 0 0]E verdade que Madarame[n]Tem um cartao de visita tambem?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_06_ [Sharp Student]]
[s][vp 9 2 65535 42354 0 0]Ouvi dizer que os ladroes fantasmas foram enviados[n]Um cartao de visita para Madarame tambem...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_01_ [Sharp Student]]
[s][vp 9 2 65535 40602 0 0]Eu ouvi Shibuya's[n]perigoso agora...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_02_ [Sharp Student]]
[s][vp 9 2 65535 38201 0 0]O que a policia esta fazendo?[n]Apresse-se e prenda-os...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_03_ [Sharp Student]]
[s][vp 9 2 65535 43013 0 0]Estou ouvindo que algumas pessoas[n]Fiquei arruinado por golpes de phishing...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_04_ [Sharp Student]]
[s][vp 9 2 65535 40652 0 0]Ouvi dizer que algumas pessoas de[n]Nossa escola foi extorquada...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_05_ [Sharp Student]]
[s][vp 9 2 65535 38752 0 0]Alguns de nossos colegas de classe[n]Na verdade, foi enganado, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_06_ [Sharp Student]]
[s][vp 9 2 65535 40802 0 0]E assustador que tantos[n]Mais pessoas estao se apaixonando[n]Famas de phishing hoje em dia...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_01_ [Sharp Student]]
[s][vp 9 2 65535 39654 0 0]Eu ouvi dizer que existem[n]Phantom Thief chamando[n]Cartoes em todo o Shibuya![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_02_ [Sharp Student]]
[s][vp 9 2 65535 42204 0 0]Pessoas tem visto[n]Phantom Thief chamando[n]Cartas em Shibuya![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_04_ [Sharp Student]]
[s][vp 9 2 65535 42754 0 0]Quem eles vao[n]punir em seguida?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_05_ [Sharp Student]]
[s][vp 9 2 65535 40505 0 0]Quem e esse cara de Kaneshiro[n]Eles estao segmentando desta vez?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_06_ [Sharp Student]]
[s][vp 9 2 65535 39255 0 0]E verdade que eles[n]encontrou outro fantasma[n]Cartao de chamada de ladrao?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_01_ [Sharp Student]]
[s][vp 9 2 65535 38906 0 0]Os ladroes fantasmas[n]sao muito mais confiaveis[n]do que a policia![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_02_ [Sharp Student]]
[s][vp 9 2 65535 42256 0 0]Ouvi dizer que o[n]Phantom Thieves levou[n]naquele anel de crime...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_04_ [Sharp Student]]
[s][vp 9 2 65535 43350 0 0]Com esse sindicato de crime desaparecido,[n]Nao precisamos mais ter medo[n]Enquanto passeava pela cidade.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_05_ [Sharp Student]]
[s][vp 9 2 65535 41704 0 0]Os ladroes Phantom sao[n]Finalmente ficando serio![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_06_ [Sharp Student]]
[s][vp 9 2 65535 43308 0 0]Entao foi por causa de[n]Phantom ladroes isso[n]Kaneshiro foi preso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_01_ [Sharp Student]]
[s][vp 9 2 65535 45050 0 0]Eu li um post do forum que dizia[n]nos temos os ladroes fantasmas[n]Agradeco por sua prisao![n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_02_ [Sharp Student]]
[s][vp 9 2 65535 39506 0 0]Parece cada vez mais[n]as pessoas estao postando nisso[n]Forum do Phantom Thief.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_04_ [Sharp Student]]
[s][vp 9 2 65535 42356 0 0]Todos online[n]tenho falado sobre[n]Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_05_ [Sharp Student]]
[s][vp 9 2 65535 40503 0 0]O forum Phantom Thieves[n]esta sendo inundado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_06_ [Sharp Student]]
[s][vp 9 2 65535 44804 0 0]Espere, voce nao[n]ouvi falar do Phantom[n]Site aficionado!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_01_ [Sharp Student]]
[s][vp 9 2 65535 42906 0 0]Se o Phantom ladroes apenas[n]derrubar pessoas que fizeram[n]Coisas terriveis, tudo bem, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_02_ [Sharp Student]]
[s][vp 9 2 65535 38403 0 0]Aqueles ladroes fantasmas[n]esta finalmente comecando a[n]Disponique alguma justica real![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_03_ [Sharp Student]]
[s][vp 9 2 65535 38506 0 0]Estou realmente curioso sobre quem[n]Os ladroes Phantom realmente sao![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_04_ [Sharp Student]]
[s][vp 9 2 65535 43300 0 0]Eu sabia! Eu sabia o[n]Os ladroes fantasmas eram reais![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_05_ [Sharp Student]]
[s][vp 9 2 65535 40304 0 0]Voce acha que Kamoshida[n]eram os ladroes fantasmas '[n]Primeiro trabalho, afinal?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_06_ [Sharp Student]]
[s][vp 9 2 65535 38906 0 0]Ladroes Phantom tambem sao[n]legal. Basta olhar para o caminho[n]Eles derrotam o mal e outras coisas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_01_ [Sharp Student]]
[s][vp 9 2 65535 46353 0 0]Ameacas como Medjed[n]deve ser retirado por[n]Os ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_02_ [Sharp Student]]
[s][vp 9 2 65535 37553 0 0]Mal posso esperar para ver o que vai[n]acontecer em um confronto entre o[n]Phantom ladroes e hackers![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_03_ [Sharp Student]]
[s][vp 9 2 65535 38754 0 0]Quem voce acha que e[n]vai ganhar? O fantasma[n]Ladroes ou medjed?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_04_ [Sharp Student]]
[s][vp 9 2 65535 43253 0 0]Estou meio que ansioso para[n]os proximos ladroes do Phantom[n]Showdown contra os hackers![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_05_ [Sharp Student]]
[s][vp 9 2 65535 42554 0 0]Os ladroes fantasmas versus[n]hackers? Parece coisas[n]estao ficando interessantes![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_06_ [Sharp Student]]
[s][vp 9 2 65535 45054 0 0]Medjed declarou guerra[n]Os ladroes fantasmas...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_01_ [Sharp Student]]
[s][vp 9 2 65535 39606 0 0]Mal posso esperar para ver como o[n]Phantom Thieves estao indo[n]Para lidar com este![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_02_ [Sharp Student]]
[s][vp 9 2 65535 38404 0 0]A menos que os ladroes Phantom se encontrem[n]suas demandas, eles vao[n]causar alguns danos graves...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_04_ [Sharp Student]]
[s][vp 9 2 65535 43601 0 0]Quais sao os ladroes fantasmas[n]fazendo!? Apresse-se e leve-os[n]antes que eles nos atacem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_05_ [Sharp Student]]
[s][vp 9 2 65535 39804 0 0]Como estao os ladroes fantasmas[n]vou responder ao[n]Ameacas dos hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_06_ [Sharp Student]]
[s][vp 9 2 65535 40256 0 0]Aqueles ladroes fantasmas vao[n]Pare esses hackers antes[n]Eles podem fazer alguma coisa, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_01_ [Sharp Student]]
[s][vp 9 2 65535 41403 0 0]Eles sao incriveis! Se[n]So eu poderia conhecer o[n]Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_02_ [Sharp Student]]
[s][vp 9 2 65535 37806 0 0]Os ladroes fantasmas sao o caminho[n]Melhor que a policia![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_03_ [Sharp Student]]
[s][vp 9 2 65535 40556 0 0]Os ladroes fantasmas levaram[n]Down Medjed! Ninguem pode[n]Fique no seu caminho![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_04_ [Sharp Student]]
[s][vp 9 2 65535 43303 0 0]Eu sabia que poderiamos contar com[n]Os ladroes Phantom! Eu vou[n]Mostre a eles mais apoio![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_05_ [Sharp Student]]
[s][vp 9 2 65535 40750 0 0]Por que devemos nos preocupar?[n]Aqueles ladroes fantasmas sao[n]la fora, lutando por nos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_06_ [Sharp Student]]
[s][vp 9 2 65535 42606 0 0]Voce pode acreditar que eles levaram[n]para um hacker internacional[n]organizacao? Que incrivel![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_01_ [Sharp Student]]
[s][vp 9 2 65535 42155 0 0]O principal morreu para levar[n]responsabilidade pelo que aconteceu?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_02_ [Sharp Student]]
[s][vp 9 2 65535 38405 0 0]Ele conseguiu o que merecia, nao[n]ele? Quero dizer, ele deixou Kamoshida fazer[n]todas essas coisas para seus alunos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_04_ [Sharp Student]]
[s][vp 9 2 65535 40454 0 0]Os ladroes fantasmas mudaram seu[n]coracao, e entao ele se matou[n]Para compensar o que ele fez?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_05_ [Sharp Student]]
[s][vp 9 2 65535 41704 0 0]Entao espere, ele se matou[n]de culpa, causada por Phantom[n]Ladroes mudando seu coracao...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_06_ [Sharp Student]]
[s][vp 9 2 65535 38255 0 0]Talvez seja o direito dele se comprometer[n]suicidio, mas eu gostaria que nao[n]Porque tantos problemas para nos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_01_ [Sharp Student]]
[s][vp 9 2 65535 42603 0 0]Quem voce acha que o Phantom[n]O proximo alvo dos ladroes sera!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_02_ [Sharp Student]]
[s][vp 9 2 65535 37556 0 0]A midia realmente tem[n]seus olhos em nossa escola.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_04_ [Sharp Student]]
[s][vp 9 2 65535 38553 0 0]Como voce pode nao saber sobre[n]Os ladroes Phantom!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_05_ [Sharp Student]]
[s][vp 9 2 65535 37503 0 0]Tudo vai ficar bem[n]Se deixarmos para o fantasma[n]Ladroes![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_06_ [Sharp Student]]
[s][vp 9 2 65535 40206 0 0]Espero que aqueles ladroes fantasmas mantenham[n]derrubando o mal e os transgressores.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_01_ [Sharp Student]]
[s][vp 9 2 65535 46354 0 0]Eu tenho um senpai chamado Okumura.[n]Eles estao relacionados?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_02_ [Sharp Student]]
[s][vp 9 2 65535 39404 0 0]Faz o presidente Okumura[n]filha realmente vai para a nossa escola?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_04_ [Sharp Student]]
[s][vp 9 2 65535 41404 0 0]Eu ouvi presidente[n]A filha de Okumura e[n]Um terceiro ano em nossa escola![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_05_ [Sharp Student]]
[s][vp 9 2 65535 46304 0 0]Aparentemente, aquele CEO corrupto[n]Todo mundo esta falando tem um[n]filha que vai para a nossa escola...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_06_ [Sharp Student]]
[s][vp 9 2 65535 43804 0 0]Filho do presidente Okumura[n]vai para a nossa escola!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_01_ [Sharp Student]]
[s][vp 9 2 65535 40404 0 0]Quem voce pensa o[n]Os ladroes fantasmas sao[n]vai para o alvo a seguir!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_02_ [Sharp Student]]
[s][vp 9 2 65535 45804 0 0]Que tipo de vilao voce[n]Pense nos ladroes fantasmas[n]ira depois do proximo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_04_ [Sharp Student]]
[s][vp 9 2 65535 38006 0 0]Nao ha nada a temer,[n]Enquanto o fantasma[n]Ladroes estao aqui![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_05_ [Sharp Student]]
[s][vp 9 2 65535 42506 0 0]Ficaremos bem com[n]os ladroes fantasmas[n]nos protegendo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_06_ [Sharp Student]]
[s][vp 9 2 65535 46353 0 0]Eu nao me importo com quem  alguem[n]precisa excluir todo o mal e[n]Pessoas perversas em nosso mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_01_ [Sharp Student]]
[s][vp 9 2 65535 37653 0 0]Um CEO corrupto como[n]que merece o que e[n]Vindo para ele![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_02_ [Sharp Student]]
[s][vp 9 2 65535 43156 0 0]Aqueles adultos irresponsaveis[n]Precisa ser derrubado[n]pelos ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_03_ [Sharp Student]]
[s][vp 9 2 65535 38206 0 0]Apenas se apresse e leve[n]Ele para baixo, ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_04_ [Sharp Student]]
[s][vp 9 2 65535 42956 0 0]Eu sabia que eles iriam atras[n]Presidente Okumura![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_05_ [Sharp Student]]
[s][vp 9 2 65535 42650 0 0]Faca-o descer[n]Seus joelhos e groveld![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_06_ [Sharp Student]]
[s][vp 9 2 65535 42403 0 0]Eu esperava que eles enviassem[n]um cartao de chamada! Mal posso esperar para[n]Veja o que acontece a seguir![n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_01_ [Sharp Student]]
[s][vp 9 2 65535 44860 0 0]Aquela coisa que aconteceu[n]com o presidente Okumura[n]Definitivamente nao era normal...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_02_ [Sharp Student]]
[s][vp 9 2 65535 43057 0 0]Fiquei muito chocado quando[n]Eu vi o presidente Okumura[n]conferencia de imprensa...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_03_ [Sharp Student]]
[s][vp 9 2 65535 44602 0 0]Eu nunca imaginei que o[n]Phantom Thieves faria[n]algo parecido...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_04_ [Sharp Student]]
[s][vp 9 2 65535 42762 0 0]O que aconteceu com o presidente[n]Okumura nao era CG... certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_05_ [Sharp Student]]
[s][vp 9 2 65535 41902 0 0]Voce viu a conferencia de imprensa[n]Com o Presidente Okumura? Este[n]era completamente louco...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_06_ [Sharp Student]]
[s][vp 9 2 65535 40607 0 0]O que aconteceu durante isso[n]A conferencia foi realmente[n]Real, nao foi...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_01_ [Sharp Student]]
[s][vp 9 2 65535 42351 0 0]Eu me sinto tao traido.[n]Os ladroes fantasmas[n]sao realmente assassinos!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_02_ [Sharp Student]]
[s][vp 9 2 65535 37857 0 0]Mata-lo estava cruzando[n]A linha, Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_04_ [Sharp Student]]
[s][vp 9 2 65535 38357 0 0]Eu nunca pensei no fantasma[n]Ladroes seriam assassinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_05_ [Sharp Student]]
[s][vp 9 2 65535 37557 0 0]Entao eles estao mudando[n]Coracoes das pessoas no comeco,[n]So para nos enganar!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_06_ [Sharp Student]]
[s][vp 9 2 65535 42401 0 0]Eles o mataram!?[n]Isso e nojento![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_01_ [Sharp Student]]
[s][vp 9 2 65535 42913 0 0]Eu ouvi em algum lugar que[n]Os ladroes fantasmas tem[n]Alguns links para Shujin...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_02_ [Sharp Student]]
[s][vp 9 2 65535 42551 0 0]Eles estao ate tentando[n]Pegue os ladroes Phantom!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_04_ [Sharp Student]]
[s][vp 9 2 65535 42601 0 0]Eu ouvi isso tudo[n]Eles fizeram ate agora[n]era apenas eles se aquecendo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_05_ [Sharp Student]]
[s][vp 9 2 65535 39407 0 0]Alguem precisa prender[n]Os ladroes Phantom![n]Nao importa quem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_06_ [Sharp Student]]
[s][vp 9 2 65535 40857 0 0]Quando e a policia[n]Vou agir!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_01_ [Sharp Student]]
[s][vp 9 2 65535 38357 0 0]Ouvi dizer que ha uma recompensa[n]Se voce fornecer informacoes sobre[n]Os ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_02_ [Sharp Student]]
[s][vp 9 2 65535 38109 0 0]Entao, a policia finalmente[n]Levou a serio a prisao[n]os ladroes fantasmas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_03_ [Sharp Student]]
[s][vp 9 2 65535 38407 0 0]Ouvi dizer que voce pode obter recompensa[n]dinheiro para fornecer informacoes[n]Sobre os ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_04_ [Sharp Student]]
[s][vp 9 2 65535 40605 0 0]Ouvi dizer que eles colocaram uma recompensa[n]Os ladroes Phantom! Eles estao[n]Finalmente fazendo a sua mudanca...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_05_ [Sharp Student]]
[s][vp 9 2 65535 39109 0 0]Agora eles estao fazendo[n]algo!? Eles nao sao[n]trabalhando um pouco lento?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_06_ [Sharp Student]]
[s][vp 9 2 65535 42407 0 0]Espero que isso convenca o[n]Phantom Thieves para parar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_01_ [Sharp Student]]
[s][vp 9 2 65535 39359 0 0]Se eles sabem quem causou o[n]Quebras psicoticas entao[n]Apenas prende-los ja...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_02_ [Sharp Student]]
[s][vp 9 2 65535 46251 0 0]Eles estao ate tentando[n]Pegue os ladroes Phantom!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_04_ [Sharp Student]]
[s][vp 9 2 65535 42351 0 0]Eu ouvi isso tudo[n]Eles fizeram ate agora[n]era apenas eles se aquecendo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_05_ [Sharp Student]]
[s][vp 9 2 65535 39757 0 0]Tudo esta baguncado[n]por causa do[n]Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_06_ [Sharp Student]]
[s][vp 9 2 65535 42357 0 0]Alguem pega o[n]Phantom Thieves! Isto[n]Nao importa quem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_01_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_02_ [Sharp Student]]
[s][vp 9 2 65535 40552 0 0]De jeito nenhum... eu pensei que ele era[n]Um shoo-in para o primeiro-ministro...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_04_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_05_ [Sharp Student]]
[s][vp 9 2 65535 40352 0 0]Todas essas coisas representativas[n]Shido disse, eles nao podem ser verdadeiros...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_06_ [Sharp Student]]
[s][vp 9 2 65535 42902 0 0]O que nos vamos fazer[n]sem shido representativo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_01_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_02_ [Sharp Student]]
[s][vp 9 2 65535 42102 0 0]Nao importa o que eu faco.[n]Nao vai mudar nada...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_04_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_05_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_06_ [Sharp Student]]
[s][vp 9 2 65535 44202 0 0]Alguem, por favor, faca[n]algo sobre tudo isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_01_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_02_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_04_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_05_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_06_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_01_ [Sharp Student]]
[s][vp 9 2 65535 42363 0 0]Ele parece calmo e em[n]controle, mas voce nunca[n]Saiba quando ele vai virar...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_02_ [Sharp Student]]
[s][vp 9 2 65535 43062 0 0]Beber, fumar, roubo...[n]Eu ouvi que esse cara fez tudo.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_03_ [Sharp Student]]
[s][vp 9 2 65535 42112 0 0]Entao e ele? Esse e o[n]Cara com o registro criminal?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_04_ [Sharp Student]]
[s][vp 9 2 65535 43313 0 0]Aquele aluno transferido[n]envolvido em todos os tipos[n]De coisas obscuras, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_05_ [Sharp Student]]
[s][vp 9 2 65535 42263 0 0]Ele parece inofensivo, mas ele e[n]fez algumas coisas loucas, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_06_ [Sharp Student]]
[s][vp 9 2 65535 42812 0 0]Aquele aluno transferido realmente[n]Comprometido alguns crimes, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_01_ [Sharp Student]]
[s][vp 9 2 65535 42960 0 0]Eu sinto que, se voce olhar[n]ele nos olhos por muito tempo,[n]Ele so vai dar um soco em voce...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_02_ [Sharp Student]]
[s][vp 9 2 65535 43162 0 0]Ouvi dizer que ele puxa facas[n]em pessoas sem nenhum aviso.[n]Esse cara e um canhao solto.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_04_ [Sharp Student]]
[s][vp 9 2 65535 43312 0 0]Eu ouco que quem faz[n]O contato visual com ele tem que[n]ser enviado para o hospital...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_05_ [Sharp Student]]
[s][vp 9 2 65535 42712 0 0]Nao o olhe nos olhos![n]Ele vai bater em voce em quase morte...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_06_ [Sharp Student]]
[s][vp 9 2 65535 43112 0 0]Todo mundo esta dizendo que ele usa[n]armas para ameacar as pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_01_ [Sharp Student]]
[s][vp 9 2 65535 42163 0 0]Eu ouvi que a policia e[n]Aqui para investigar qualquer[n]Links para o Sr. Kamoshida.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_02_ [Sharp Student]]
[s][vp 9 2 65535 40155 0 0]Ugh, a policia esta aqui?[n]Vamos la, me de um tempo...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_04_ [Sharp Student]]
[s][vp 9 2 65535 40454 0 0]Parece a policia[n]vao investigar[n]coisas sobre a nossa escola.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_05_ [Sharp Student]]
[s][vp 9 2 65535 40355 0 0]A escola tem sido tao barulhenta[n]Com esta comocao...[n]Esta me dando nos nervos.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_06_ [Sharp Student]]
[s][vp 9 2 65535 42605 0 0]A policia esta acontecendo,[n]Questionando as pessoas, aparentemente.[n]Espero que eles saiam em breve.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_01_ [Sharp Student]]
[s][vp 9 2 65535 43202 0 0]Eu vou ficar tao ferrado[n]No meu meio-medio...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_02_ [Sharp Student]]
[s][vp 9 2 65535 42702 0 0]Vou ter que ficar acordado tudo[n]noite para Cram, e depois adivinhe[n]tudo o que eu nao sei...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_03_ [Sharp Student]]
[s][vp 9 2 65535 42560 0 0]Quem se importa com os exames? Eu nao[n]sinto vontade de estudar de qualquer maneira...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_04_ [Sharp Student]]
[s][vp 9 2 65535 40951 0 0]Ja esta na hora do meio do meio!?[n]Tiro, eu preciso comecar a revisar.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_05_ [Sharp Student]]
[s][vp 9 2 65535 42658 0 0]Nao temos nenhum clube[n]atividades, para que eu possa apenas estudar.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_06_ [Sharp Student]]
[s][vp 9 2 65535 41405 0 0]Midterms estao em breve,[n]Ha? Que aborrecimento...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_01_ [Sharp Student]]
[s][vp 9 2 65535 44805 0 0]Nao posso deixar minhas notas cair.[n]Vou precisar trabalhar[n]Muito dificil para minhas finais...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_02_ [Sharp Student]]
[s][vp 9 2 65535 39052 0 0]Esta quase na hora das finais.[n]E melhor eu ter certeza de que[n]Estude o suficiente...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_04_ [Sharp Student]]
[s][vp 9 2 65535 42011 0 0]Eu preciso melhorar[n]pontuacao nas minhas finais do que[n]Eu fiz no meu meio-medio![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_05_ [Sharp Student]]
[s][vp 9 2 65535 39402 0 0]Cara, ja e[n]temporada de finais?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_06_ [Sharp Student]]
[s][vp 9 2 65535 38010 0 0]O que, e hora de[n]Finals ja? Eu acabei de[n]quero ir para meus clubes...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_01_ [Sharp Student]]
[s][vp 9 2 65535 38904 0 0]Aquele detetive Akechi-kun[n]e realmente incrivel![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_02_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_04_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_05_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_06_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_01_ [Sharp Student]]
[s][vp 9 2 65535 42754 0 0]Nao ha garantia de que eles vao[n]so va atras de pessoas mas...[n]Isso e um pouco assustador.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_02_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_03_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_04_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_05_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_06_ [Sharp Student]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_01_ [Sharp Student]]
[s][vp 9 2 65535 38902 0 0]Estou meio surpreso.[n]Eu acho que ele deve estar estudando[n]Quando nenhum de nos esta olhando.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_02_ [Sharp Student]]
[s][vp 9 2 65535 38755 0 0]Essas pontuacoes justas[n]tem que ser um acaso.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_03_ [Sharp Student]]
[s][vp 9 2 65535 39402 0 0]Um delinquente que tambem e inteligente...[n]Isso e meio assustador, nao e?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_04_ [Sharp Student]]
[s][vp 9 2 65535 43201 0 0]Ele roubou o teste[n]respostas ou algo assim?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_05_ [Sharp Student]]
[s][vp 9 2 65535 38751 0 0]Aposto que ele apenas traiu[n]durante o teste.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_06_ [Sharp Student]]
[s][vp 9 2 65535 38905 0 0]Obtendo boas pontuacoes na escola[n]Nao vai apagar o que ele fez.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_01_ [Sharp Student]]
[s][vp 9 2 65535 37651 0 0]Ele nao se parece com o tipo[n]que passaria muito tempo estudando...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_02_ [Sharp Student]]
[s][vp 9 2 65535 38752 0 0]Ele esta no topo do[n]classe? Qual e o negocio dele?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_03_ [Sharp Student]]
[s][vp 9 2 65535 39502 0 0]Eu me sinto totalmente derrotado.[n]Tenho tanta vergonha de mim mesma.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_04_ [Sharp Student]]
[s][vp 9 2 65535 38305 0 0]Ele realmente conseguiu a pontuacao superior?[n]Eles cometeram um erro quando[n]Eles estavam classificando seus testes?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_05_ [Sharp Student]]
[s][vp 9 2 65535 42663 0 0]Eu me pergunto se devo pedir a ele[n]Tutori-me. Ele e tao assustador embora...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_06_ [Sharp Student]]
[s][vp 9 2 65535 42362 0 0]E melhor ele nao deixar isso ir para o dele[n]cabeca. Ele obtendo a pontuacao superior[n]Provavelmente foi um acaso, de qualquer maneira.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_01_ [Sharp Student]]
[s][vp 9 2 65535 41554 0 0]Ele esta entre os dez primeiros, certo?[n]Entao ele e definitivamente inteligente...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_02_ [Sharp Student]]
[s][vp 9 2 65535 37552 0 0]Antes de eu perceber, ele era[n]Recebendo notas melhores do que eu...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_03_ [Sharp Student]]
[s][vp 9 2 65535 41704 0 0]Eu pensei que ele era apenas alguns[n]delinquente, mas ele e[n]realmente muito bom...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_04_ [Sharp Student]]
[s][vp 9 2 65535 37701 0 0]Voce viu as notas dos testes?[n]As pontuacoes principais foram loucas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_05_ [Sharp Student]]
[s][vp 9 2 65535 38704 0 0]Mesmo que ele tenha um criminoso[n]Record, ele ainda tem essas pontuacoes?[n]Ele pode ser grande algum dia...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_06_ [Sharp Student]]
[s][vp 9 2 65535 39652 0 0]Voce nao pode dizer por olhar para[n]ele, mas acho que ele realmente[n]Estudos como um aluno serio...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_01_ [Sharp Student]]
[s][vp 9 2 65535 42154 0 0]Voce tem que entrega-lo a ele.[n]Obter a pontuacao superior e[n]uma realizacao bastante.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_02_ [Sharp Student]]
[s][vp 9 2 65535 40104 0 0]Eu zombei dele, mas recebendo[n]A pontuacao superior e incrivel...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_03_ [Sharp Student]]
[s][vp 9 2 65535 42210 0 0]A maneira como sua mente funciona e[n]Provavelmente apenas completamente[n]Diferente do nosso...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_04_ [Sharp Student]]
[s][vp 9 2 65535 43304 0 0]Eu li isso errado?[n]Ele nao pode ter conseguido[n]a pontuacao superior...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_05_ [Sharp Student]]
[s][vp 9 2 65535 38404 0 0]Just quando ele se tornou[n]o topo da classe?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_06_ [Sharp Student]]
[s][vp 9 2 65535 39605 0 0]Eu acho que ele realmente era[n]estudando todo esse tempo...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_01_ [Sharp Student]]
[s][vp 9 2 65535 42153 0 0]Os professores devem ser todos[n]Surpreso tambem. Eu queria dizer isso[n]Cara, na verdade, estuda para a escola...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_02_ [Sharp Student]]
[s][vp 9 2 65535 38504 0 0]Eu tenho que admitir que ele e realmente[n]isso inteligente. Quero dizer, tudo de[n]Suas pontuacoes sao tao boas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_03_ [Sharp Student]]
[s][vp 9 2 65535 40152 0 0]Eu me sinto burro por ser tao[n]com medo dele. Ele e realmente[n]um aluno muito bom.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_04_ [Sharp Student]]
[s][vp 9 2 65535 40955 0 0]E bom que ele tenha[n]boas notas, mas ele e[n]Ainda meio assustador...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_05_ [Sharp Student]]
[s][vp 9 2 65535 40155 0 0]Mesmo que ele tenha uma boa pontuacao,[n]Como podemos ter certeza de que ele de repente[n]Nao vai causar problemas de novo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_06_ [Sharp Student]]
[s][vp 9 2 65535 40805 0 0]Eu entendo que ele e inteligente, mas eu ainda[n]sinta-se mais confortavel em manter meu[n]Distancia dele, sabe?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_01_ [Sharp Student]]
[s][vp 9 2 65535 42404 0 0]Eu acho que ninguem pode reclamar se[n]Ele esta no topo da aula...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_02_ [Sharp Student]]
[s][vp 9 2 65535 41705 0 0]E realmente meio que[n]assustador quando alguem gosta[n]Isso obtem a pontuacao superior...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_03_ [Sharp Student]]
[s][vp 9 2 65535 44304 0 0]Ele pode ate ser[n]Mais inteligente que Akechi...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_04_ [Sharp Student]]
[s][vp 9 2 65535 42363 0 0]Ele e realmente inteligente, mas ainda estou[n]nao tenho tanta certeza sobre ele. Ele pode[n]acaba se tornando um genio do mal...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_05_ [Sharp Student]]
[s][vp 9 2 65535 44904 0 0]E inacreditavel que[n]Ele obteve a pontuacao superior.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_06_ [Sharp Student]]
[s][vp 9 2 65535 42602 0 0]Bem, ele e o mais inteligente[n]um em nossa escola...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_01__2 [Sharp Student]]
[s][vp 9 2 65535 38906 0 0]Veja isso! eu comprei algum[n]Phantom Thieves Merchandise![n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_02__2 [Sharp Student]]
[s][vp 9 2 65535 40100 0 0]Olha, eu peguei esses chamados[n]Cartas! Uau, agora estou parte[n]dos ladroes fantasmas tambem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_04__2 [Sharp Student]]
[s][vp 9 2 65535 39602 0 0]Todos estavam esgotados de[n]Phantom Thieves Merchandise...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_01_ [Sharp Student]]
[s][vp 9 2 65535 42353 0 0]Meus pais sempre me dizem[n]Para fazer o que eu quero fazer...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_02_ [Sharp Student]]
[s][vp 9 2 65535 42800 0 0]Vamos, vamos celebrar o[n]ano Novo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_03_ [Sharp Student]]
[s][vp 9 2 65535 42559 0 0]Nao ha nenhuma regra dizendo que nos[n]Tem que passar para a faculdade.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_04_ [Sharp Student]]
[s][vp 9 2 65535 42650 0 0]Meu irmao mais velho e o unico[n]assumindo o controle. Entao estou livre para[n]Faca o que quer![n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_05_ [Sharp Student]]
[s][vp 9 2 65535 42853 0 0]Vou lhe emprestar minha raquete...[n]Na verdade, para ser sincero,[n]e o meu irmao mais novo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_06_ [Sharp Student]]
[s][vp 9 2 65535 43002 0 0]Huh? Eu pensei que voce disse[n]voce deixou seu emprego... talvez[n]isso era outra pessoa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_07_ [Sharp Student]]
[s][vp 9 2 65535 42205 0 0]Sua aula sempre foi[n]aqui...? Bem, tanto faz.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_01_ [Sharp Student]]
[s][vp 9 2 65535 43354 0 0]Voce esta indo para o Senpai's[n]Cerimonia de graduacao?[n]Eu acho que posso chorar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_02_ [Sharp Student]]
[s][vp 9 2 65535 43203 0 0]O time de volei e tao[n]Forte. Vamos anima-los[n]no proximo jogo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_03_ [Sharp Student]]
[s][vp 9 2 65535 42503 0 0]Esta aula e tao pacifica.[n]Sem panelinhas ou qualquer coisa...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_04_ [Sharp Student]]
[s][vp 9 2 65535 43053 0 0]Voce estara de volta no proximo ano,[n]certo? Uau, Inglaterra...[n]Isso e tao emocionante...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_05_ [Sharp Student]]
[s][vp 9 2 65535 42255 0 0]Hmm, talvez eu tivesse[n]errado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_503_01_ [Sharp Student]]
[s][vp 9 2 65535 42953 0 0]Eu acho que vou pegar alguns[n]Aconselhamento tambem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_503_02_ [Sharp Student]]
[s][vp 9 2 65535 42753 0 0]Ei, quero visitar a enfermeira[n]escritorio? Ha doces la![n][f 1 2 180][e]

[msg MSG_GRT_main_All_503_03_ [Sharp Student]]
[s][vp 9 2 65535 42554 0 0]Dr. Maruki e tal[n]uma pessoa legal.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_503_04_ [Sharp Student]]
[s][vp 9 2 65535 42854 0 0]Aconselhamento, hein...[n]Talvez eu tente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_601_01_ [Sharp Student]]
[s][vp 9 2 65535 42404 0 0]Voce sabe daquele primeiro ano,[n]Yoshizawa? Ela esta dentro[n]Ginastica, nao e?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_601_02_ [Sharp Student]]
[s][vp 9 2 65535 43100 0 0]Yoshizawa-san[n]performances sao[n]incrivel![n][f 1 2 180][e]

[msg MSG_GRT_main_All_601_03_ [Sharp Student]]
[s][vp 9 2 65535 42104 0 0]Yoshizawa e realmente um[n]Atleta talentoso, nao e?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_601_04_ [Sharp Student]]
[s][vp 9 2 65535 42204 0 0]Voce viu esse primeiro ano?[n]Aquele em ginastica...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_505_01_ [Sharp Student]]
[s][vp 9 2 65535 43101 0 0]E verdade que Yoshizawa-san[n]e amigo da transferencia[n]aluna?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_505_02_ [Sharp Student]]
[s][vp 9 2 65535 42352 0 0]Aquela garota de ginasta era[n]com aquele cara...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_505_03_ [Sharp Student]]
[s][vp 9 2 65535 42655 0 0]Yoshizawa-san e[n]tipo de estranho...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_505_04_ [Sharp Student]]
[s][vp 9 2 65535 38752 0 0]Aposto que ele apenas carrega[n]As coisas de Yoshizawa-san[n]para ela...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_01_ [Sharp Student]]
[s][vp 9 2 65535 42602 0 0]Como ela poderia deixar todo mundo[n]Assim... que piada.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_02_ [Sharp Student]]
[s][vp 9 2 65535 42752 0 0]Ela nao deveria ser[n]um aluno de honra? Ela e[n]Nao e tao impressionante.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_03_ [Sharp Student]]
[s][vp 9 2 65535 43152 0 0]Oh garoto... agora as meninas vao[n]Nunca pare de fazer o mal[n]sua...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_04_ [Sharp Student]]
[s][vp 9 2 65535 42255 0 0]Nao seja tao duro com ela[n]por cometer um erro...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_602_01_ [Sharp Student]]
[s][vp 9 2 65535 42503 0 0]Esse conselheiro e[n]Muito facil de conversar.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_602_02_ [Sharp Student]]
[s][vp 9 2 65535 42953 0 0]Mal posso esperar para voltar[n]Para o escritorio da enfermeira![n][f 1 2 180][e]

[msg MSG_GRT_main_All_602_03_ [Sharp Student]]
[s][vp 9 2 65535 42550 0 0]Esse conselheiro e otimo![n]Voce pode falar com ele sobre[n]nada![n][f 1 2 180][e]

[msg MSG_GRT_main_All_602_04_ [Sharp Student]]
[s][vp 9 2 65535 42353 0 0]Eu me pergunto se posso falar com[n]Dr. Maruki sobre o meu[n]estudos...[n][f 1 2 180][e]

