[sel YESNO_SEL top]
[s]Sim[e]
[s]Nao[e]

[msg NPC_GREETING_MSG]
[s]Saudar[n][w][e]

[msg NPC_01]
[s]Conversa[n][w][e]

[msg MSG_PV_HOSUTO_001_0_0 [Host]]
[s][f 4 23 1 80 3 10 0 10][vp 8 2 1 0 80 0]Posso ajudar?[n][w][e]

[msg MSG_KIGURUMI_001_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Voce ja ouviu as historias assustadoras[n]andando ultimamente?[n][w][e]
[s][vp 8 2 1 0 1 0]Isso mesmo! Ha algo que voce[n]absolutamente deve fazer caso algo[n]Sempre acontece com voce![n][w][e]
[s][vp 8 2 1 0 1 0]Limpe seu disco rigido antes de alguem[n]descobre o que realmente esta la![n]Apresento o seguro de dados![n][w][e]
[s][vp 8 2 1 0 1 0]Pegue agora a um preco especial durante[n]Esta promocao![n][w][e]

[msg MSG_KIGURUMI_002_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Oi pessoal! Voce nao pensa[n]As ruas parecem inseguras ultimamente?[n][w][e]
[s][vp 8 2 1 0 1 0]Bem, eu tenho boas noticias para voce![n]Voce estara protegido com isso totalmente[n]Capa de telefone anti-crime em destaque![n][w][e]
[s][vp 8 2 1 0 1 0]Ficando assaltado? Com o flip[n]de um interruptor, seu telefone vai girar[n]em uma arma de choque![n][w][e]
[s][vp 8 2 1 0 1 0]Compre o seu hoje, como parte de um[n]Pacote irresistivel contrato com[n]Nosso servico de Internet![n][w][e]

[msg MSG_KIGURUMI_003_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Voce nunca sabe quando o perigo[n]vai atacar! Tem certeza que voce[n]E seus entes queridos estao seguros?[n][w][e]
[s][vp 8 2 1 0 1 0]Cabe a voce proteger o que e[n]muito importante. Voce nao pode levar[n]riscos nesses tempos perigosos.[n][w][e]
[s][vp 8 2 1 0 1 0]Mas o que voce pode fazer para proteger[n]voce mesma?[n][w][e]
[s][vp 8 2 1 0 1 0]Nao se preocupe  nossos sistemas de seguranca[n]sao a resposta! Entre em contato com o nosso[n]Empresa para servicos de instalacao![n][w][e]

[msg MSG_KIGURUMI_004_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]O seu computador em casa e realmente[n]Seguro e seguro?[n][w][e]
[s][vp 8 2 1 0 1 0]Vivemos em uma epoca em que temos que[n]Guarde nossos computadores de hackers.[n]Voce poderia sobreviver ao roubo de identidade?[n][w][e]
[s][vp 8 2 1 0 1 0]No momento, estamos tendo uma promocao[n]Venda da melhor deteccao de hackers[n]Software na industria![n][w][e]
[s][vp 8 2 1 0 1 0]Sem ele, voce nunca saberia quem[n]pode estar tentando roubar seu pessoal[n]em formacao![n][w][e]

[msg MSG_KIGURUMI_005_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Se voce acha que os assaltantes so operam[n]Atualmente, voce estaria errado.[n][w][e]
[s][vp 8 2 1 0 1 0]Voce reavaliou sua casa[n]seguranca ultimamente? Se nao, agora e o[n]tempo perfeito![n][w][e]
[s][vp 8 2 1 0 1 0]Estamos tendo uma venda promocional especial[n]do nosso total de sistemas de seguranca. Juntar[n]Agora, para beneficios de bonus![n][w][e]
[s][vp 8 2 1 0 1 0]Nao deixe esta oportunidade passar por voce[n]por! Quando o perigo atingir, voce vai[n]tem a protecao que voce precisa?[n][w][e]

[msg MSG_KIGURUMI_006_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Quando voce esta em perigo, quem vai[n]estar la para protege-lo?[n][w][e]
[s][vp 8 2 1 0 1 0]Seus amigos? Familia? A policia?[n]Mesmo... os ladroes Phantom!?[n][w][e]
[s][vp 8 2 1 0 1 0]Nao ha garantia de que eles chegarao[n]na hora. tu precisas estar preparado[n]Para se proteger![n][w][e]
[s][vp 8 2 1 0 1 0]Proteger contra ameacas antes[n]Eles podem acontecer, anunciamos[n]Nosso novo plano de garantia de seguranca![n][w][e]

[msg MSG_KIGURUMI_007_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Atencao, todos na rua![n][w][e]
[s][vp 8 2 1 0 1 0]Quer-b-alert apresenta nosso novo[n]plano de garantia de seguranca, com base em[n]Nossas cameras de seguranca de ponta![n][w][e]
[s][vp 8 2 1 0 1 0]Nosso sistema de deteccao de invasores e o[n]primeiro de seu tipo, usando o mais recente em[n]Tecnologia de reconhecimento facial![n][w][e]
[s][vp 8 2 1 0 1 0]Voce nunca sabe quem esta te observando.[n]Voce nao se sentiria mais seguro conhecendo voce[n]poderia pega-los em flagrante?[n][w][e]

[msg MSG_KIGURUMI_008_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Voce ja sentiu que sua empresa[n]Pode estar aproveitando voce?[n][w][e]
[s][vp 8 2 1 0 1 0]O perigo poderia atingir sua empresa[n]a qualquer momento. E assim, seu[n]A vida como voce conhece isso desmorona.[n][w][e]
[s][vp 8 2 1 0 1 0]Voce nunca sabe o que pode acontecer,[n]Mas pelo menos voce pode dar sua casa[n]a melhor protecao.[n][w][e]
[s][vp 8 2 1 0 1 0]Quer-b-alert pode ajuda-lo! Para[n]Tempo limitado, inscreva-se com um zero para baixo[n]contrato![n][w][e]

[msg MSG_KIGURUMI_009_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Mesmo no Japao, estamos sendo atingidos[n]por terrorismo. Nao podemos nos dar ao luxo de[n]Ignore os perigos ao nosso redor.[n][w][e]
[s][vp 8 2 1 0 1 0]E a pessoa ao seu lado alguem[n]que voce pode realmente confiar?[n][w][e]
[s][vp 8 2 1 0 1 0]Substitua toda a sua ansiedade por[n]confianca garantida ao se inscrever[n]Para o nosso plano de garantia de seguranca![n][w][e]

[msg MSG_KIGURUMI_010_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Voce ja teve medo disso[n]Alguem pode estar te observando?[n][w][e]
[s][vp 8 2 1 0 1 0]Surpreendentemente, recebemos cinco vezes[n]Mais inscricoes de contrato neste outono[n]do que fizemos no ano passado![n][w][e]
[s][vp 8 2 1 0 1 0]Isso porque as pessoas sabem disso[n]Quer-b-alert vai te proteger[n]Quando o mal atinge de repente![n][w][e]
[s][vp 8 2 1 0 1 0]Para comemorar nosso alto contrato[n]numeros com nossos clientes, estamos[n]Dando bonecas que nao quer-wanna-kun![n][w][e]

[msg MSG_KIGURUMI_011_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Voce esta vivendo com medo por causa de[n]aqueles estranhos e misteriosos[n]Phantom Thieves?[n][w][e]
[s][vp 8 2 1 0 1 0]Ninguem sabe como eles se comprometem[n]seus crimes. Voce esta preocupado[n]Nenhum lugar esta a salvo deles?[n][w][e]
[s][vp 8 2 1 0 1 0]Nao seja vitima de terrorismo ou[n]Seu proprio medo. Tomar as medidas para[n]Seja capaz de dizer: "Minha casa e segura".[n][w][e]
[s][vp 8 2 1 0 1 0]Inscreva-se com o que quer-b-alert agora[n]e obtenha um seguranca em seu[n]Casa tres vezes por mes de graca![n][w][e]

[msg MSG_KIGURUMI_012_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]A sociedade esta cheia com a mudanca[n]dos partidos no poder, mas como[n]Na verdade, afeta nossas vidas?[n][w][e]
[s][vp 8 2 1 0 1 0]Voce nao sabe? Isso mesmo.[n]Nao ha como saber! E[n]E por isso que planejamos com antecedencia.[n][w][e]
[s][vp 8 2 1 0 1 0]Com a seguranca do que quer-b-alert[n]Garantia, voce estara seguro nos tempos[n]de perigo imprevisivel![n][w][e]
[s][vp 8 2 1 0 1 0]Antes do fim do ano, voce nao vai[n]finalmente comece a colocar uma prioridade em[n]Seguranca... antes que seja tarde demais?[n][w][e]

[msg MSG_KIGURUMI_013_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Hoje em dia, nao esta ficando[n]Mais dificil de saber em que acreditar?[n]Em quem voce pode confiar?[n][w][e]
[s][vp 8 2 1 0 1 0]Com o que quer-b-alert, seus medos de[n]o invisivel sera substituido por[n]doce alivio.[n][w][e]
[s][vp 8 2 1 0 1 0]No momento, estamos vendendo pacotes de[n]Cinco cameras de seguranca para o nosso especial[n]Promocao de Natal![n][w][e]
[s][vp 8 2 1 0 1 0]Nem o Papai Noel poderia invadir um[n]casa com esse tipo de protecao![n]Tente querer-b-alert hoje![n][w][e]

[msg MSG_KIGURUMI_014_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Como esta tudo o que voce esta fazendo neste Natal[n]estacao?[n][w][e]
[s][vp 8 2 1 0 1 0]Se voce esteve seguro este ano, por que nao[n]Invista mais em sua seguranca para o proximo ano?[n][w][e]
[s][vp 8 2 1 0 1 0]Quer-b-alert esta operando ate mesmo[n]o ano Novo! Nos trabalhamos o nosso mais duro para[n]De-lhe paz de espirito![n][w][e]
[s][vp 8 2 1 0 1 0]Inscreva-se para o nosso final de ano, ultimo[n]Promocao de contrato minuciosa para um gratis[n]Wanna-Wanna-Kun Kagamimochi![n][w][e]

[msg MSG_KIGURUMI_015_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Feliz Ano Novo! Voce com certeza merece um[n]depois de um tempo tao turbulento. Entao voce e[n]Finalmente respirando um suspiro de alivio, certo?[n][w][e]
[s][vp 8 2 1 0 1 0]Mas sao momentos como esses que voce precisa[n]ser cuidadoso! Voce nunca sabe quando[n]A tragedia pode atacar a seguir![n][w][e]
[s][vp 8 2 1 0 1 0]Por exemplo, voce trancou a porta da frente[n]Quando voce saiu hoje?...De quem[n]O coracao pulou uma batida agora?[n][w][e]
[s][vp 8 2 1 0 1 0]E por isso que quero alerta B esta aqui para[n]Proteja sua vida, este ano e sempre![n][w][e]

[msg MSG_KIGURUMI_016_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Mesmo com nosso governo em perigo de[n]sendo derrubado, o que esta por acontecer[n]Sua seguranca como individuo?[n][w][e]
[s][vp 8 2 1 0 1 0]Wanna B Alert tem a resposta![n][w][e]
[s][vp 8 2 1 0 1 0]Mesmo que o governo fosse fechado[n]para baixo, quero alerta B estara aqui para[n]Mantenha voce seguro![n][w][e]
[s][vp 8 2 1 0 1 0]Considere-nos um forro de luxo inacessivel.[n]Confie em nossos servicos e aproveite o passeio![n][w][e]

[msg MSG_KIGURUMI_017_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Os ladroes Phantom fizeram um pouco de respingo,[n]Mas agora eles se foram. Isso tambem significa[n]o mundo e seguro?[n][w][e]
[s][vp 8 2 1 0 1 0]Nao e uma chance! Pode haver qualquer numero[n]de ladroes e ladroes a espreita no[n]Trevas![n][w][e]
[s][vp 8 2 1 0 1 0]Quero alertas de B MUITO guardas[n]casa desses criminosos.[n][w][e]
[s][vp 8 2 1 0 1 0]Inscreva-se agora e receba um desejo gratuito-[n]Wanna-kun Setsubun Bean! Mantenha seu[n]Bencaos seguras com alertas de Wanna B![n][w][e]

[msg MSG_KIGURUMI_018_0_0 [Woman Pushing Promotion]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Nao e hora de voce considerar que quer-[n]Garantia de seguranca do B-Alert para[n]proteger voce?[n][w][e]
[s][vp 8 2 1 0 1 0]Como parte da nossa primavera "nova vida"[n]Promocao, vamos jogar em alguns[n]Profissional Home Movers![n][w][e]
[s][vp 8 2 1 0 1 0]Vivemos em alguns tempos sombrios, mas um[n]sociedade onde todos podem viver[n]Seguranca e nosso objetivo final.[n][w][e]
[s][vp 8 2 1 0 1 0]E por isso que, no quer-b-alert, estamos[n]fazendo tudo o que pudermos para proteger[n]Seu futuro brilhante![n][w][e]

[msg MSG_OKAMAFUTARI_001_0_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Ultimamente, eu me deparei com isso[n]Garoto muito bom.[n][w][e]

[msg MSG_OKAMAFUTARI_001_1_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Oh, seu encontro caseiro sem vergonha![n][w][e]

[msg MSG_OKAMAFUTARI_001_2_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Nao, nao e bem assim. estou falando sobre[n]Um garoto que vi na TV! Akechi-kun![n][w][e]

[msg MSG_OKAMAFUTARI_001_3_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]De jeito nenhum voce tem os gostos[n]ele tambem!? Pare ja![n][w][e]

[msg MSG_OKAMAFUTARI_002_0_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Voce ja ouviu falar sobre o fantasma[n]Ladroes? Algumas criancas estavam falando sobre[n]eles.[n][w][e]

[msg MSG_OKAMAFUTARI_002_1_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Aqueles que roubam coracoes? Ah, eu desejo[n]Eles roubariam o meu...[n][w][e]

[msg MSG_OKAMAFUTARI_002_2_0 [Julian]]
[s][vp 8 2 1 0 65535 0]Nao! Akechi-kun diz que sao[n]perigoso. E ele sabe o que[n]Ele esta falando![n][w][e]

[msg MSG_OKAMAFUTARI_002_3_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Voce sempre se apaixona pelas pessoas com muita forca tambem[n]velozes. Voce e muito pegajoso! E por isso que voce[n]Continue sendo despejado![n][w][e]

[msg MSG_OKAMAFUTARI_003_0_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Voce ve as noticias? O fantasma[n]Ladroes trabalhavam sua magia, e[n]Peguei aquele cara da mafia para desistir.[n][w][e]

[msg MSG_OKAMAFUTARI_003_1_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Ei, cuidado com o que voce diz[n]coisas! Voce tem uma suja tao suja[n]Lembre-se, voce sabe disso?[n][w][e]

[msg MSG_OKAMAFUTARI_003_2_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Olha quem Esta Falando! Cobicando-se depois de um[n]menino pelo menos vinte anos mais jovem[n]do que voce![n][w][e]

[msg MSG_OKAMAFUTARI_003_3_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Oh, deite-se! Eu nao posso evitar! Alem do mais,[n]Eu nao sou realmente eu se nao estiver apaixonado[n]Com alguem, certo?[n][w][e]

[msg MSG_OKAMAFUTARI_004_0_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Acho que talvez meu computador tenha sido hackeado...[n][w][e]

[msg MSG_OKAMAFUTARI_004_1_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Como isso aconteceu!? Isso tem que[n]fazer com todas essas noticias ultimamente?[n][w][e]

[msg MSG_OKAMAFUTARI_004_2_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Quando estou na internet, esses peculiares[n]As telas continuam aparecendo. E eu entendo estes[n]contas estranhas...[n][w][e]

[msg MSG_OKAMAFUTARI_004_3_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Uau la... voce clicou em alguns sombrios[n]Links em um site porno!?[n][w][e]

[msg MSG_OKAMAFUTARI_005_0_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Eu sei que voce gosta de Akechi, mas o que fazer[n]Voce pensa nos ladroes fantasmas?[n][w][e]

[msg MSG_OKAMAFUTARI_005_1_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Aqueles ladroes fantasmas nunca poderiam[n]roubar meu coracao...[n][w][e]
[s][vp 8 2 1 0 65535 0]Ja foi arrebatado![n]Akechi-kuuuun...[n][w][e]

[msg MSG_OKAMAFUTARI_005_2_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Uau! Nao grite e me assuste como[n]voce, seu manequim![n][w][e]

[msg MSG_OKAMAFUTARI_006_0_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Akechi-kun esta recebendo muito[n]de odiadores. Tantas pessoas sairam[n]ele para os ladroes fantasmas.[n][w][e]

[msg MSG_OKAMAFUTARI_006_1_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Ele deve estar sofrendo muito[n]lado de dentro. Eu gostaria de poder animar[n]Meu querido Akechi-kun...[n][w][e]

[msg MSG_OKAMAFUTARI_006_2_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]"Meu Akechi-kun", minha bunda. Sua[n]Os olhos goo-boo nao sao realmente pares[n]com sua sombra das cinco horas.[n][w][e]

[msg MSG_OKAMAFUTARI_006_3_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]E voce tem alguns cabelos no nariz[n]Voce precisa ser controlado![n][w][e]

[msg MSG_OKAMAFUTARI_007_0_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Apenas desista. A era de Akechi-kun[n]esta acabado.[n][w][e]

[msg MSG_OKAMAFUTARI_007_1_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Cale a boca, voce... robusto, bonitinho... bolo[n]de carne![n][w][e]
[s][vp 8 2 1 0 65535 0]So voce assiste! Vou revelar o fantasma[n]Ladroes como os monstros que realmente sao![n][w][e]

[msg MSG_OKAMAFUTARI_007_2_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]O que voce esta falando? Quando voce[n]Fique com raiva, voce e mais um monstro[n]do que eles sao![n][w][e]

[msg MSG_OKAMAFUTARI_008_0_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Voce ouviu!? Os ladroes fantasmas tem[n]Um novo alvo![n][w][e]

[msg MSG_OKAMAFUTARI_008_1_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Bem, espero que eles explodam! Eu diria o[n]a mesma coisa para eles como eu faria qualquer[n]Se voce cruzar Akechi-kun, terminou![n][w][e]

[msg MSG_OKAMAFUTARI_008_2_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Vamos la, apenas ouca a si mesmo! Eu penso[n]Voce "fez" perdeu a cabeca![n][w][e]
[s][vp 8 2 1 0 65535 0]Eu sei que voce tem a voz de Akechi[n]Defina como alarme do seu telefone![n][w][e]

[msg MSG_OKAMAFUTARI_009_0_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Acontece que os ladroes fantasmas[n]Afinal, eram monstros![n][w][e]
[s][vp 8 2 1 0 65535 0]Assassinando alguem a sangue frio![n]Isso e tao escaloso![n][w][e]

[msg MSG_OKAMAFUTARI_009_1_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Voce esta certo, eles foram longe demais[n]Tempo. Estou traumatizado pelo visual[n]No rosto daquele homem...[n][w][e]

[msg MSG_OKAMAFUTARI_009_2_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Sim, prefiro olhar para o rosto de[n]Um menino lindo. Trazer a era de[n]Akechi-kun![n][w][e]

[msg MSG_OKAMAFUTARI_010_0_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Ei... eu aposto que os ladroes fantasmas sentem[n]Ma em lutar pelo cerebro desse cara.[n][w][e]

[msg MSG_OKAMAFUTARI_010_1_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Ooh, bem, voce nao e o mais legal[n]contrario? Nao empurre sua sorte.[n][w][e]
[s][vp 8 2 1 0 65535 0]"Seja voce mesmo." Nao e isso que voce[n]prometeu fazer quando voce mudou[n]sua imagem e se mudou para ca?[n][w][e]

[msg MSG_OKAMAFUTARI_010_2_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Eu nao mudei nada! Mas talvez[n]Eu realmente perdi contato com quem eu sou,[n]la no fundo...[n][w][e]

[msg MSG_OKAMAFUTARI_011_0_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Aqueles pobres ladroes fantasmas... eles sao[n]Obtendo tanto odio.[n][w][e]

[msg MSG_OKAMAFUTARI_011_1_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Voce sabe quanto danos eles[n]causado as pessoas? Eles sao terroristas,[n]Te digo![n][w][e]
[s][vp 8 2 1 0 65535 0]E voce nao pode contar com a policia.[n]E hora do grande detetive Akechi[n]brilhar![n][w][e]

[msg MSG_OKAMAFUTARI_011_2_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Onde ele esteve, afinal? Eu nao tenho[n]vi-o na TV ultimamente...[n][w][e]

[msg MSG_OKAMAFUTARI_012_0_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Um membro dos ladroes Phantom[n]foi finalmente pego. O tempo deles no[n]Spotlight foi tao breve...[n][w][e]

[msg MSG_OKAMAFUTARI_012_1_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Foi tudo gracas a Akechi-kun.[n][w][e]
[s][vp 8 2 1 0 65535 0]Mas... oh nao! Meu amado se sente tao[n]distante de mim de novo! Onde estao[n]Voce, Akechi-kun!?[n][w][e]

[msg MSG_OKAMAFUTARI_012_2_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]De alguma forma, ele deve saber como voce se sente.[n]Ele fugiu e se escondeu![n][w][e]

[msg MSG_OKAMAFUTARI_013_0_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Incrivel! Ele voltou![n]Eu pensei que ele morreu, mas aqui esta ele.[n]Isso e realmente emocionante![n][w][e]

[msg MSG_OKAMAFUTARI_013_1_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Bem, voce nao vai me ver se juntando[n]Os odiadores de Akechi em breve![n][w][e]

[msg MSG_OKAMAFUTARI_013_2_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]A mesma coisa aconteceu com o[n]Phantom Thieves. So vai mostrar[n]que ninguem pensa por si.[n][w][e]
[s][vp 8 2 1 0 65535 0]Somos os unicos que[n]permaneceu verdadeiro. Seremos dedicados[n]ate que a morte nos separe![n][w][e]

[msg MSG_OKAMAFUTARI_014_0_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Ei, voce nao acha que e suspeito?[n][w][e]

[msg MSG_OKAMAFUTARI_014_1_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Duvidoso? Nao, voce cheira mais a uma fera.[n]Voce realmente precisa tomar banho, mesmo no[n]inverno.[n][w][e]

[msg MSG_OKAMAFUTARI_014_2_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Nao e isso que quero dizer! Nao e estranho[n]que eles estao dizendo o fantasma[n]Ladroes eram apenas uma ilusao?[n][w][e]

[msg MSG_OKAMAFUTARI_014_3_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Sim... eles eram rivais de Akechi-kun,[n]tambem. Eu me pergunto se eles estao tentando cobrir[n]algo para cima...[n][w][e]

[msg MSG_OKAMAFUTARI_015_0_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Entao, do que voce acha que suas chances sao[n]Encontrando aquela alguem especial este ano?[n][w][e]

[msg MSG_OKAMAFUTARI_015_1_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Hmhmhm... bem, verdade seja dita... eu ja[n]Ja encontrei alguem![n][w][e]

[msg MSG_OKAMAFUTARI_015_2_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]O que!? Oh, voce... Entao, como ele e? Dizer[n]eu tudo![n][w][e]

[msg MSG_OKAMAFUTARI_015_3_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Ele e devastadoramente bonito, como[n]Akechi-kun! Vamos jantar[n]data em breve![n][w][e]

[msg MSG_OKAMAFUTARI_015_4_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Por que voce e o unico que consegue ser[n]feliz? E tao injusto! Me leve com voce![n][w][e]

[msg MSG_OKAMAFUTARI_016_0_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Foi legal da sua parte me deixar marcar junto[n]no seu jantar na outra noite.[n][w][e]

[msg MSG_OKAMAFUTARI_016_1_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]E claro. Eu me senti culpado por todos os[n]felicidade para mim mesmo.[n][w][e]

[msg MSG_OKAMAFUTARI_016_2_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Voce e tao doce![n][w][e]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Mas o cara que seu namorado trouxe[n]Ao longo, tambem era muito bonito.[n][w][e]

[msg MSG_OKAMAFUTARI_016_3_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Aquele amigo esta aparentemente dizendo que ele[n]quer sair para jantar com voce...[n][w][e]

[msg MSG_OKAMAFUTARI_016_4_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Cale-se! Serio? Finalmente, na primavera[n]Venha para mim tambem?[n][w][e]

[msg MSG_OKAMAFUTARI_017_0_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Oh, o que eu nao daria para ser jovem[n]novamente...[n][w][e]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Voce sabe a melhor coisa sobre a juventude?[n]Aquela pele flexivel! Eu tomaria banho em uma banheira[n]de hidratante se eu pudesse recuperar essa pele![n][w][e]

[msg MSG_OKAMAFUTARI_017_1_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Eu te escuto! Na verdade, tomei banho em hidratante[n]outro dia e quase se afogou...[n][w][e]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Quando cheguei, minha pele estava tao flexivel,[n]Eu pensei que ainda estava sonhando...[n][w][e]

[msg MSG_OKAMAFUTARI_017_2_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Entao funcionou? Serio? Mesmo para voce!?[n][w][e]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Entao tambem funcionaria para mim! Ou[n]Vou ficar desapontado![n][w][e]

[msg MSG_OKAMAFUTARI_018_0_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]... as coisas com certeza ficaram silenciosas em torno desta cidade,[n]Ha?[n][w][e]

[msg MSG_OKAMAFUTARI_018_1_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Se ha uma coisa que os ladroes fantasmas[n]me ensinaram, e para seguir a batida de[n]Meu proprio tambor![n][w][e]

[msg MSG_OKAMAFUTARI_018_2_0 [Julian]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Isso surgiu do nada. Springtime[n]Venha cedo la fora em sua cabeca?[n][w][e]

[msg MSG_OKAMAFUTARI_018_3_0 [Angel]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Apenas me ouca.[n]Eu tomei uma decisao.[n][w][e]
[s][vp 8 2 1 0 65535 0]E hora de eu comecar realmente[n]sendo real comigo mesmo. Entao olhe[n]fora, mundo! E hora das folhas![n][w][e]

[msg MSG_GYAKUSAGI_001_0_0 [Gentle Old Man]]
[s][vp 8 2 1 0 5 0]Meu filho sofreu um acidente de carro!?[n]Como ele esta agora?[n][w][e]
[s][vp 8 2 1 0 5 0]Operacao de emergencia? Alguem[n]Ele sabe que esta cuidando dele?[n][w][e]
[s][vp 8 2 1 0 5 0]Eu gostaria de poder ir, mas... sinto muito[n]por te incomodar.[n][w][e]
[s][vp 8 2 1 0 5 0]Sim, pagarei as taxas do hospital imediatamente.[n]Vou entrar em contato com o colega dele e... sim...[n][w][e]

[msg MSG_GYAKUSAGI_002_0_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]Entao, como esta meu filho!? Ele esta realmente bem?[n][w][e]
[s][vp 8 2 1 0 5 0]Minha esposa suspeita que isso e uma farsa,[n]que voce esta naquela gangue criminosa[n]Os ladroes fantasmas estao procurando.[n][w][e]

[msg MSG_GYAKUSAGI_002_1_0 [Casual Young Man]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]O que? Nao! Eu so quero salvar meu[n]Amigo! Apenas pergunte a ele sobre mim[n]Quando ele acorda.[n][w][e]
[s][vp 8 2 1 0 7 0]Mas agora nao e hora disso. Ele[n]precisa de outra operacao para sobreviver...[n][w][e]

[msg MSG_GYAKUSAGI_002_2_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]Eu-eu vejo. Sinto muito por duvidar de voce.[n]Sim, eu acredito em voce. Vou pagar o que quer que seja[n]voce precisa. Salve meu filho![n][w][e]

[msg MSG_GYAKUSAGI_003_0_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]Eu trouxe o dinheiro para a operacao,[n]Assim como voce perguntou. Entao eu apenas entrego[n]para voce?[n][w][e]

[msg MSG_GYAKUSAGI_003_1_0 [Casual Young Man]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Seria dificil para voce ter que falar[n]Para toda a equipe medica quando voce estiver[n]Preocupado com seu filho, certo?[n][w][e]
[s][vp 8 2 1 0 7 0]Seu filho esta inconsciente, mas eu vou fazer[n]Claro que a segunda operacao acontece.[n][w][e]

[msg MSG_GYAKUSAGI_003_2_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]Obrigado por tudo. Nao sei[n]O que teria acontecido se nao fosse[n]para voce...[n][w][e]
[s][vp 8 2 1 0 5 0]Ah... eu quero ver meu filho. Avise[n]Assim que voce ouvir algo novo sobre[n]sua condicao.[n][w][e]

[msg MSG_GYAKUSAGI_004_0_0 [Casual Young Man]]
[s][vp 8 2 1 0 7 0]Funcionou como planejamos,[n]parceiro! Eu realmente cambaleei nisso[n]Velhote![n][w][e]
[s][vp 8 2 1 0 7 0]O seu tambem esta indo bem, sim?[n]Os idosos sao faceis demais. E[n]Eles tem dinheiro![n][w][e]
[s][vp 8 2 1 0 7 0]...O que? Tenha cuidado com o fantasma[n]Ladroes? Isso e apenas uma farsa, idiota.[n][w][e]
[s][vp 8 2 1 0 7 0]Vai ficar bem, nada vai dar errado.[n]Vou ordenhar esse velho por tudo o que vale![n][w][e]

[msg MSG_GYAKUSAGI_005_0_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]Voce nao vai me deixar ligar para meu filho?[n]Eu sei que nao e permitido as vezes, as vezes,[n]Mas deve haver uma maneira que eu possa...[n][w][e]

[msg MSG_GYAKUSAGI_005_1_0 [Casual Young Man]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Sinto muito, mas seu filho esta em[n]uma condicao muito precaria, e[n]Ele pode precisar de outra operacao.[n][w][e]

[msg MSG_GYAKUSAGI_005_2_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]H-ele esta ferido tao mal? E o[n]3 milhoes de ienes que eu te dei outro dia[n]o suficiente?[n][w][e]

[msg MSG_GYAKUSAGI_005_3_0 [Casual Young Man]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Na verdade... ja que e uma operacao complexa,[n]Ele vai precisar de mais 5 milhoes...[n][w][e]

[msg MSG_GYAKUSAGI_005_4_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]Tudo bem, eu vou depositar. Eu nao posso colocar um preco[n]em sua vida. Por favor, cuide do meu filho![n][w][e]

[msg MSG_GYAKUSAGI_006_0_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]Muito obrigado por cuidar do meu[n]filho. Nao tenho palavras para agradecer.[n][w][e]
[s][vp 8 2 1 0 5 0]Nao e muito, mas eu gostaria que voce tivesse[n]algum dinheiro como recompensa. Vou depositar[n]em sua conta bancaria.[n][w][e]

[msg MSG_GYAKUSAGI_006_1_0 [Casual Young Man]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Nao, eu me sentiria culpado se voce o fizesse. eu so queria[n]Para garantir que meu amigo esteja bem.[n][w][e]

[msg MSG_GYAKUSAGI_006_2_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]Ele nao entra em contato com seus pais com muita frequencia.[n]Quem sabe o que teria acontecido[n]para ele sem voce?[n][w][e]

[msg MSG_GYAKUSAGI_006_3_0 [Casual Young Man]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Bem, quando ele acordar, eu vou dizer a ele que[n]Ele precisa entrar em contato com seu pai, haha.[n][w][e]

[msg MSG_GYAKUSAGI_007_0_0 [Casual Young Man]]
[s][vp 8 2 1 0 7 0]Aquele velho era facil demais. estou fazendo[n]mais fora dele do que torcer dinheiro[n]de pessoas na rua.[n][w][e]
[s][vp 8 2 1 0 7 0]Sim. Os caras que geralmente fazem[n]o extorquir tem tudo[n]roubado deles. Tivemos sorte.[n][w][e]
[s][vp 8 2 1 0 7 0]Uh huh. Mas sim, aquele nerista nao[n]ate duvido de mim. Ele e ate voluntario[n]Para me dar dinheiro![n][w][e]
[s][vp 8 2 1 0 7 0]Tudo o que faco e deixar o nome do filho dele,[n]E ele e vidraceiro em minhas maos.[n][w][e]
[s][vp 8 2 1 0 7 0]Cara, eu nao posso acreditar como os velhos ricos[n]sao embora. Vou ter que encontrar outro[n]e ordenha-lo seco.[n][w][e]

[msg MSG_GYAKUSAGI_008_0_0 [Agent Suit]]
[s][f 4 23 1 6 5 10 4 20][vp 8 2 1 0 6 0]Ei voce. Eu preciso que voce me pague 10 milhoes[n]Yen, este instante.[n][w][e]

[msg MSG_GYAKUSAGI_008_1_0 [Casual Young Man]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Que diabos, bastardo? Isso e extorsao?[n][w][e]

[msg MSG_GYAKUSAGI_008_2_0 [Agent Suit]]
[s][vp 8 2 1 0 6 0]Os ladroes fantasmas cuidaram daqueles[n]Gente, lembra? Eu so quero que voce pague[n]de volta o que eu emprestei.[n][w][e]

[msg MSG_GYAKUSAGI_008_3_0 [Casual Young Man]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Eu nunca peguei emprestado nenhum dinheiro de voce![n]Por que devo pagar 10 milhoes de ienes?[n][w][e]

[msg MSG_GYAKUSAGI_008_4_0 [Agent Suit]]
[s][f 4 23 1 6 6 10 0 10][vp 8 2 1 0 6 0]Voce nao pode correr. Sente-se e pergunte a si mesmo[n]Se voce realmente nao sabe o que estou falando[n]cerca de.[n][w][e]

[msg MSG_GYAKUSAGI_009_0_0 [Casual Young Man]]
[s][vp 8 2 1 0 7 0]Ouca, outro dia, fiquei ameacado por[n]Este cara estranho...[n][w][e]
[s][vp 8 2 1 0 7 0]O que? Ele veio ate voce tambem? Ele era[n]Vestindo um terno preto serio, certo?[n][w][e]
[s][vp 8 2 1 0 7 0]Talvez ele seja um ladrao fantasma! Mas eu nunca[n]Tenho um cartao de visita... o que esta acontecendo!?[n][w][e]
[s][vp 8 2 1 0 7 0]Mais policia esta por causa de[n]As quebras psicoticas tambem. Pode ser[n]Devemos abandonar esta area...[n][w][e]

[msg MSG_GYAKUSAGI_010_0_0 [Agent Suit]]
[s][f 4 23 1 6 4 10 0 10][vp 8 2 1 0 6 0]Voce esta pronto para pagar o que deve?[n]Enviamos muito dinheiro para voce. Voce nao[n]Lembra agora?[n][w][e]

[msg MSG_GYAKUSAGI_010_1_0 [Casual Young Man]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Huh? O que voce esta fazendo aqui...? E[n]Esse dinheiro era para pagar o seu filho[n]contas do hospital...[n][w][e]

[msg MSG_GYAKUSAGI_010_2_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]Voce pensou que eu realmente se apaixonaria por isso?[n]Eu estava apenas brincando.[n][w][e]
[s][vp 8 2 1 0 5 0]Eu sou apenas um empreendedor, um de muitos,[n]Mas eu sempre me certifico de voltar o que e[n]devia a mim.[n][w][e]

[msg MSG_GYAKUSAGI_010_3_0 [Casual Young Man]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Isso nao pode ser... voce esta dizendo que voce esta[n]Aquele que me enganou!?[n][w][e]

[msg MSG_GYAKUSAGI_011_0_0 [Casual Young Man]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Nao posso pagar 10 milhoes de ienes! O que voce faz[n]caras querem!?[n][w][e]

[msg MSG_GYAKUSAGI_011_1_0 [Agent Suit]]
[s][f 4 23 1 6 4 10 0 10][vp 8 2 1 0 6 0]Como eu expliquei muitas vezes, queremos[n]Purge o mundo dos artistas de fragmentacao[n]como voce.[n][w][e]
[s][vp 8 2 1 0 6 0]Lutamos contra veneno com veneno. Voce e sortudo[n]voce nao conseguiu um daqueles psicoticos[n]separacao.[n][w][e]

[msg MSG_GYAKUSAGI_011_2_0 [Casual Young Man]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Vou me entregar a policia, entao.[n]Voce nao pode me seguir la, pode?[n]Eu nao pensei assim![n][w][e]

[msg MSG_GYAKUSAGI_011_3_0 [Agent Suit]]
[s][f 4 23 1 6 4 10 0 10][vp 8 2 1 0 6 0]Voce ainda pagara quando sair. Poco[n]tambem cobra juros pelo tempo que voce[n]na prisao. Hehehe...[n][w][e]

[msg MSG_GYAKUSAGI_012_0_0 [Casual Young Man]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Eu nao posso mais pagar... eu paguei tanto[n]Mais do que eu enganei voces![n][w][e]

[msg MSG_GYAKUSAGI_012_1_0 [Agent Suit]]
[s][f 4 23 1 6 4 10 0 10][vp 8 2 1 0 6 0]Ha grande recompensa dinheiro para[n]pegando os ladroes fantasmas, mas[n]E impossivel com seu cerebro.[n][w][e]
[s][vp 8 2 1 0 6 0]Tudo bem, vou apresentar a voce um trabalho simples.[n]Trabalhe la, e voce esta livre de dividas.[n][w][e]

[msg MSG_GYAKUSAGI_012_2_0 [Casual Young Man]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]R-Really!? Por favor... me de esse trabalho,[n]E deixe tudo acabar...[n][w][e]

[msg MSG_GYAKUSAGI_013_0_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]Ei, o que aconteceu com aqueles golpes[n]Artistas? O unico bom ponto esses caras[n]tinha sua resistencia.[n][w][e]

[msg MSG_GYAKUSAGI_013_1_0 [Agent Suit]]
[s][f 4 23 1 6 4 10 0 10][vp 8 2 1 0 6 0]Eles estao em um navio de pesca de atum no[n]No meio do Pacifico agora. Foi gentil[n]de voce para envia-los.[n][w][e]
[s][vp 8 2 1 0 6 0]Bem, nao tenho certeza se eles voltarao[n]vivo, entao eu tomei um seguro de vida[n]politicas tambem.[n][w][e]

[msg MSG_GYAKUSAGI_013_2_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]Livre-se do mal sem estar preso[n]por leis estupidas  essa e a nossa maneira de[n]fazendo coisas.[n][w][e]
[s][vp 8 2 1 0 5 0]E por isso que sinto uma camaradagem com[n]os ladroes fantasmas. E uma pena[n]Lider morreu.[n][w][e]

[msg MSG_GYAKUSAGI_014_0_0 [Agent Suit]]
[s][f 4 23 1 6 4 10 0 10][vp 8 2 1 0 6 0]Voce parece estar de bom humor. Fez[n]Algo aconteceu?[n][w][e]

[msg MSG_GYAKUSAGI_014_1_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]Voce viu o chamado dos ladroes do Phantom[n]cartao? Ja faz tanto tempo que estou[n]tao animado.[n][w][e]
[s][vp 8 2 1 0 5 0]Eu nao posso acreditar que eles direcionariam o[n]governo assim. Eles devem ser[n]comprometido em curar o veneno.[n][w][e]

[msg MSG_GYAKUSAGI_014_2_0 [Agent Suit]]
[s][f 4 23 1 6 4 10 0 10][vp 8 2 1 0 6 0]Esta area tem sido bastante pacifica e silenciosa[n]por causa deles tambem.[n][w][e]

[msg MSG_GYAKUSAGI_014_3_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]O mundo nao precisa de veneno como eu[n]nao mais. Eu acho que vou me aposentar de ser[n]Um empreendedor de dinheiro...[n][w][e]

[msg MSG_GYAKUSAGI_015_0_0 [Agent Suit]]
[s][f 4 23 1 6 4 10 0 10][vp 8 2 1 0 6 0]Eu sei que voce disse que deixaria de ser um[n]Moneylender, mas o que voce planeja[n]fazer a seguir?[n][w][e]

[msg MSG_GYAKUSAGI_015_1_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]Hmm, talvez um restaurante de sushi. Eu tenho[n]o navio de pesca de atum, entao conseguir o estoque vai[n]Nao haja problema.[n][w][e]

[msg MSG_GYAKUSAGI_015_2_0 [Agent Suit]]
[s][f 4 23 1 6 4 10 0 10][vp 8 2 1 0 6 0]Ah, isso sera uma mudanca de ritmo.[n][w][e]
[s][vp 8 2 1 0 6 0]Eu me pergunto quando os caras que colocamos no[n]O navio de atum voltara...? Eu acho que vamos[n]tem que ser paciente.[n][w][e]

[msg MSG_GYAKUSAGI_015_3_0 [Gentle Old Man]]
[s][f 4 23 1 5 3 10 0 10][vp 8 2 1 0 5 0]Vou tornar isso um barato, mas muito delicioso[n]Sushi Place. Um lugar para os jovens pode[n]visite casualmente.[n][w][e]
[s][vp 8 2 1 0 5 0]Talvez seja por causa do fantasma[n]Ladroes, mas eu quero fazer algo[n]novo. Estou em uma aposentadoria divertida![n][w][e]

[msg MSG_SUKAUTOMAN_001_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Uau, agora voce e um cara bonito.[n]E voce tem olhos tao bonitos para tras[n]Esses oculos elegantes![n][w][e]
[s][vp 8 2 1 0 8 0]Diga, voce ja pensou em trabalhar em um[n]clube de hospedagem? Um anfitriao como voce poderia fazer[n]Um dinheiro pouco![n][w][e]

[sel SEL_SUKAUTOMAN_001_0_0 top]
[s]Eu sou menor de idade.[e]
[s]......[e]

[msg MSG_SUKAUTOMAN_001_1_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]O que? Menor de idade? Eu pensei que voce era[n]muito mais velho. Voce e tao maduro para o seu[n]era! Ele Ele![n][w][e]

[msg MSG_SUKAUTOMAN_001_2_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]... PSH. Garoto idiota. Ninguem vai descobrir sobre[n]sua idade, a menos que voce diga algo.[n][w][e]

[msg MSG_SUKAUTOMAN_001_3_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Vamos la, voce pode ate tentar para um[n]dia, uma corrida de teste, para ver se voce realmente gosta![n][w][e]

[msg MSG_SUKAUTOMAN_001_4_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]... PSH. Garoto idiota. Me ignorando como se eu nao[n]mesmo la.[n][w][e]

[msg MSG_SUKAUTOMAN_002_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Diga, amigo, voce tem um minuto?[n]Relaxe, nao estou com a mafia ou[n]Phantom Thieves, entao nao se preocupe![n][w][e]

[sel SEL_SUKAUTOMAN_002_0_0 top]
[s]Estou ocupado.[e]
[s]E melhor eu ir. Tchau.[e]

[msg MSG_SUKAUTOMAN_002_1_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Ocupado estudando, nao e? Com estas[n]Incriveis livros de referencia de estudo,[n]Voce passara qualquer exame que quiser![n][w][e]

[sel SEL_SUKAUTOMAN_002_1_0 top]
[s]E melhor eu ir. Tchau.[e]
[s]Eu realmente tenho que sair.[e]

[msg MSG_SUKAUTOMAN_002_2_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Sim! E melhor voce ir comprar... estes[n]Livros de referencia de estudo impressionantes![n]Se voce apenas assinar aqui...[n][w][e]

[msg MSG_SUKAUTOMAN_002_3_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Sim! Voce realmente precisa sair...[n]Sua assinatura neste contrato[n]Para obter esses livros incriveis![n][w][e]
[s][vp 8 2 1 0 8 0]Se voce apenas assinar aqui, estaremos[n]bom para ir...[n][w][e]

[sel SEL_SUKAUTOMAN_002_3_0 top]
[s]Eu nao quero essas coisas.[e]
[s]......[e]

[msg MSG_SUKAUTOMAN_002_4_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]O que!? Voce usa meu tempo como[n]isso, e entao voce diz que nao[n]Quer algum dos meus produtos!?[n][w][e]
[s][vp 8 2 1 0 8 0]Por que voce nao apenas disse isso de[n]o comeco? Va embora, seu idiota[n]garoto, voce esta perdendo meu tempo![n][w][e]

[msg MSG_SUKAUTOMAN_002_5_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Hellloooo? Voce pode me ouvir, certo?[n][w][e]
[s][vp 8 2 1 0 8 0]... PSH. Garoto idiota. Se voce nao quiser[n]Qualquer coisa, entao saia aqui![n][w][e]

[msg MSG_SUKAUTOMAN_003_0_0 [Fishy Hawker]]
[s][vp 8 2 1 0 8 0]Shibuya esta cheio de policia, nao e?[n]Tenho certeza de que estou feliz por ter mudado minhas vendas[n]territorio desde o inicio.[n][w][e]
[s][vp 8 2 1 0 8 0]Sim, eu nao estou fazendo muito surrado.[n]As pessoas realmente se apaixonam por estes[n]Historias "muito boas para serem verdadeiras".[n][w][e]
[s][vp 8 2 1 0 8 0]Apenas manteiga um pouco, e e[n]um coche. Existem tantos ingenuos[n]pessoas em todos os lugares![n][w][e]

[msg MSG_SUKAUTOMAN_003_1_0 [Patrolling Police Officer]]
[s][f 4 23 1 10 3 10 0 10][vp 8 2 1 0 10 0]Pare de incomodar as pessoas e fazer[n]uma vida mais honesta. Tenho certeza[n]Seus pais concordariam comigo.[n][w][e]

[msg MSG_SUKAUTOMAN_003_2_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]De jeito nenhum, meus pais sao scumbag[n]Viciados em jogos de azar! E como deles[n]Filho, eu tambem sou um desprezado natural![n][w][e]
[s][vp 8 2 1 0 8 0]Voce tem outras preocupacoes! Pessoas[n]estao dizendo os ladroes fantasmas[n]Faca melhor trabalho do que a policia![n][w][e]

[msg MSG_SUKAUTOMAN_003_3_0 [Patrolling Police Officer]]
[s][f 4 23 1 10 3 10 0 10][vp 8 2 1 0 10 0]Hrmph, que bastardo podre...[n]Vou te pegar um dia desses.[n][w][e]

[msg MSG_SUKAUTOMAN_004_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Ei voce ai! Voce nao e comum[n]Schmo! Eu posso dizer pela maneira como voce anda![n][w][e]
[s][vp 8 2 1 0 8 0]Voce e um ladrao fantasma, nao e?[n]Eles sao toda a raiva agora! Descobrir[n]Mais... depois dessas mensagens![n][w][e]

[sel SEL_SUKAUTOMAN_004_0_0 top]
[s]Como voce sabia?[e]
[s]Isso e impossivel.[e]
[s]......[e]

[msg MSG_SUKAUTOMAN_004_1_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Haha, uau! Voce realmente gosta disso![n]Voce realmente colocou o "fa" em Phantom[n]Ladrao, nao e?[n][w][e]

[msg MSG_SUKAUTOMAN_004_2_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Huh? Voce nao e? Bem, agora voce[n]tem mais do que um fantasma de chance[n]Para se tornar um verdadeiro ladrao fantasma![n][w][e]

[msg MSG_SUKAUTOMAN_004_3_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Apenas entre voce e eu... voce[n]sabe que os ladroes fantasmas sao[n]Recrutamento agora?[n][w][e]
[s][vp 8 2 1 0 8 0]E isso mesmo, aulas de ladrao fantasma[n]estao 90% de desconto agora! Nos ate oferecemos[n]Planos de pagamento faceis![n][w][e]

[sel SEL_SUKAUTOMAN_004_2_0 top]
[s]Nao, obrigado.[e]
[s]......[e]

[msg MSG_SUKAUTOMAN_004_4_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]O que!? Nao fique tao cheio de[n]voce mesma! Voce me deu falsa[n]Espero um minuto la![n][w][e]
[s][vp 8 2 1 0 8 0]Kid idiota, saia aqui! Como se alguem[n]Como se voce pudesse se tornar um ladrao fantasma![n][w][e]

[msg MSG_SUKAUTOMAN_004_5_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Entao, qual e a sua resposta? Acho que vamos encontrar[n]depois dessas mensagens! Esses...[n]mensagens...[n][w][e]
[s][vp 8 2 1 0 8 0]PSH. Garoto idiota, me ignorando. Saia[n]aqui! Como se alguem como voce pudesse[n]Torne-se um ladrao fantasma![n][w][e]

[msg MSG_SUKAUTOMAN_005_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Uau! Aquele brilho! Eu expliquei[n]talento por um longo tempo, mas eu tenho[n]Nunca vi ninguem brilhar como voce![n][w][e]

[msg MSG_SUKAUTOMAN_005_1_0 [Homely Woman]]
[s][f 4 23 1 10 3 10 0 10][vp 8 2 1 0 10 0]Ah, isso e tao bom! Na verdade, eu tenho[n]Sempre quis ser uma atriz...[n][w][e]

[msg MSG_SUKAUTOMAN_005_2_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Sim! Eu posso dizer que a atuacao esta em seu[n]alma. Eu sei que voce se tornara famoso[n]Se voce fizer nossos cursos de atuacao![n][w][e]

[msg MSG_SUKAUTOMAN_005_3_0 [Homely Woman]]
[s][f 4 23 1 10 3 10 0 10][vp 8 2 1 0 10 0]HM, parece um pouco caro.[n]Eu nao tenho muito dinheiro, entao vou[n]tem que perguntar aos meus pais...[n][w][e]

[msg MSG_SUKAUTOMAN_005_4_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Nao ha problema! Eu posso te pegar[n]um trabalho onde voce pode fazer muito[n]de dinheiro em um pouco de tempo![n][w][e]

[msg MSG_SUKAUTOMAN_005_5_0 [Fishy Hawker]]
[s][vp 8 2 1 0 8 0]Como vai os negocios para voce?[n]... aw, patetico.[n][w][e]
[s][vp 8 2 1 0 8 0]Voce so tem que iscar com eles com[n]Uma atitude alegre e animada.[n]E tudo o que voce precisa para empurra-los.[n][w][e]
[s][vp 8 2 1 0 8 0]Ah, hoje em dia, se voce se levantar[n]coisas sobre os ladroes fantasmas,[n]Esses idiotas vao apenas comer![n][w][e]

[msg MSG_SUKAUTOMAN_006_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Ei, segure ai! Pare voce precisa[n]Para ouvir isso![n][w][e]
[s][vp 8 2 1 0 8 0]Esta e sua chance de conhece-los[n]super-herois misteriosos, o "fantasma[n]Ladroes "! Voce esta interessado?[n][w][e]

[sel SEL_SUKAUTOMAN_006_1_0 top]
[s]Estou com pressa.[e]
[s]......[e]

[msg MSG_SUKAUTOMAN_006_2_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Relaxe, isso levara apenas um segundo. Apenas um[n]poucos segundos, ok?[n][w][e]
[s][vp 8 2 1 0 8 0]Estamos comemorando a queda de Medjed com[n]Um evento de festa: uma conversa noturna com[n]os ladroes fantasmas.[n][w][e]
[s][vp 8 2 1 0 8 0]Claro, os ladroes fantasmas vao[n]apareca tambem! Vai ser um jantar chique[n]a um preco ruim![n][w][e]

[sel SEL_SUKAUTOMAN_006_3_0 top]
[s]Parece suspeito.[e]
[s]......[e]

[msg MSG_SUKAUTOMAN_006_4_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]O que? Voce tem medo do Phantom[n]Ladroes aparecendo? O que voce esta,[n]frango?[n][w][e]

[msg MSG_SUKAUTOMAN_006_5_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Me ignorando, hein? Bem, isso e bom![n][w][e]

[msg MSG_SUKAUTOMAN_006_6_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Bem, nesse caso, ja va para casa, garoto![n]Nossa, estou desperdicando minha respiracao aqui![n][w][e]

[msg MSG_SUKAUTOMAN_007_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Eu tenho minhas vistas para voce! E[n]Estou enviando meu cartao de visita![n][w][e]

[sel SEL_SUKAUTOMAN_007_1_0 top]
[s]Voce e tao chato.[e]
[s]Cartao de chamada para que?[e]

[msg MSG_SUKAUTOMAN_007_2_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Oh, nossa, eu chateei voce? Bem, deixe[n]eu compensando voce mostrando[n]Este produto novo![n][w][e]

[msg MSG_SUKAUTOMAN_007_3_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Oh, voce se interessou, hein? Nos iremos,[n]Se for esse o caso, voce deve ver[n]Nosso novo produto![n][w][e]

[sel SEL_SUKAUTOMAN_007_4_0 top]
[s]Pergunte a outra pessoa.[e]
[s]Quem compraria suas coisas?[e]

[msg MSG_SUKAUTOMAN_007_5_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Nao esteja tao cheio de si mesmo, garoto. Eu estou[n]sem ladrao fantasma, mas eu posso fazer[n]Voce implora por perdao tambem.[n][w][e]

[msg MSG_SUKAUTOMAN_008_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Aw, vamos la! Nao fique com medo so[n]Porque voce tem um cartao de chamada![n][w][e]

[msg MSG_SUKAUTOMAN_008_1_0 [Shabby Middle-Aged Man]]
[s][f 4 23 1 9 3 10 0 10][vp 8 2 1 0 9 0]B-mas o preco dos alimentos okumura[n]Estoque que comprei do meu amigo tem[n]desabou...[n][w][e]

[msg MSG_SUKAUTOMAN_008_2_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Tudo o que voce precisa fazer e compensar isso![n]Na verdade, eu tenho essa informacao secreta...[n][w][e]

[msg MSG_SUKAUTOMAN_008_3_0 [Shabby Middle-Aged Man]]
[s][f 4 23 1 9 3 10 0 10][vp 8 2 1 0 9 0]R-Really!? Por favor, diga-me o que e![n][w][e]

[msg MSG_SUKAUTOMAN_009_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Voce e um fa dos ladroes Phantom?[n]Eles sao toda a raiva agora! Descobrir[n]Mais... depois dessas mensagens![n][w][e]

[msg MSG_SUKAUTOMAN_009_1_0 [Bored-Looking Young Man]]
[s][f 4 23 1 10 3 10 0 10][vp 8 2 1 0 10 0]O que? Phantom Thieves? O que sao[n]Voce falando sobre?[n][w][e]

[msg MSG_SUKAUTOMAN_009_2_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Aqueles populares e glamourosos[n]Os ladroes Phantom estao recrutando![n]Se voce fizer esta aula...[n][w][e]

[msg MSG_SUKAUTOMAN_009_3_0 [Bored Young Man]]
[s][f 4 23 1 10 3 10 0 10][vp 8 2 1 0 10 0]Classe? Voce esta brincando. Esses caras[n]sao criminosos. Eu nao quero nada para fazer[n]com esses arrepios.[n][w][e]

[msg MSG_SUKAUTOMAN_009_4_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Gah, este phantom ladroes desapareceu[n]fora muito rapido! De certa forma, e meio engracado.[n][w][e]

[msg MSG_SUKAUTOMAN_010_0_0 [Fishy Hawker]]
[s][vp 8 2 1 0 8 0]... voce nao quer um psicotico[n]demolir? O que, voce esta com medo?[n][w][e]
[s][vp 8 2 1 0 8 0]Eles so tem como alvo pessoas de alto perfil[n]Como artistas e CEOs.[n][w][e]
[s][vp 8 2 1 0 8 0]E quem poderia acreditar que teriam[n]Uma mudanca de coracao, afinal? Tenho certeza[n]Esta tudo encenado![n][w][e]
[s][vp 8 2 1 0 8 0]Scumbags merecem ser destruidos,[n]nao tem uma mudanca de coracao. o[n]mundial seria melhor dessa maneira.[n][w][e]

[msg MSG_SUKAUTOMAN_011_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Ei, como ganhar 30 milhoes de ienes[n]som para voce?[n][w][e]
[s][vp 8 2 1 0 8 0]Eu descobri onde os ladroes fantasmas '[n]O esconderijo e. Eu posso te vender as informacoes para um[n]preco barato.[n][w][e]

[sel SEL_SUKAUTOMAN_011_1_0 top]
[s]Nao, obrigado.[e]
[s]Eu ja sei.[e]

[msg MSG_SUKAUTOMAN_011_2_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Ah, nao acredite em mim, eu vejo. Eu terei voce[n]Saiba que estou muito bem informado.[n][w][e]
[s][vp 8 2 1 0 8 0]Eles estao muito perto aqui. Mais perto que[n]voce pensaria. Que tal isso? 50.000 ienes?[n][w][e]
[s][vp 8 2 1 0 8 0]Ei, voce esta me ignorando!? Huh!?[n][w][e]

[msg MSG_SUKAUTOMAN_011_3_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Uau! Espere um segundo, voce envolveu com o[n]investigacao ou algo assim!?[n][w][e]
[s][vp 8 2 1 0 8 0]... heh, sim, certo. Uma crianca como voce? Eu nao[n]ate cuidado. Apenas saia aqui.[n][w][e]

[msg MSG_SUKAUTOMAN_012_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Ei, voce parece um inteligente[n]homem jovem. Entao voce entendeu quando[n]Eu digo que seu dinheiro esta em perigo.[n][w][e]
[s][vp 8 2 1 0 8 0]O partido no poder se dissolveu, entao nosso[n]O pais e a economia estao condenados![n]Mas eu posso parar tudo isso. Espero.[n][w][e]

[sel SEL_SUKAUTOMAN_012_0_0 top]
[s]Voce esta mentindo.[e]
[s]E hora de mudar seu coracao.[e]

[msg MSG_SUKAUTOMAN_012_1_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Vamos la, amigo! Nao seja assim.[n]Estou apenas cuidando do seu futuro...[n][w][e]
[s][vp 8 2 1 0 8 0]... PSH. O garoto nao esta comprando. Eu acho[n]Voce teria que ser um verdadeiro idiota para cair[n]Para essa linha.[n][w][e]

[msg MSG_SUKAUTOMAN_012_2_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Naaao! Eu nao quero meu cerebro[n]mexidos! Papai! Papai, ajuda[n]meeeeeeee![n][w][e]
[s][vp 8 2 1 0 8 0]Heh, interpretando ladroes fantasmas em um[n]tempo assim? Eles sao covardes que[n]fugiu da policia.[n][w][e]
[s][vp 8 2 1 0 8 0]Tudo o que faco e economizar dinheiro de idiotas[n]quem o desperdicaria. Sociedade deveria ser[n]grato a mim![n][w][e]

[msg MSG_SUKAUTOMAN_013_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Ola, linda madame! Ter voce[n]ouvi falar de estudos secretos de Goro Akechi[n]tecnica?[n][w][e]
[s][vp 8 2 1 0 8 0]Compre esses maravilhosos guias de estudo e[n]voce tambem pode se tornar um genio como[n]Akechi-kun. S'il Vous Plait?[n][w][e]

[msg MSG_SUKAUTOMAN_013_1_0 [Wealthy-Looking Madame]]
[s][f 4 23 1 10 3 10 0 10][vp 8 2 1 0 10 0]Ah, talvez eu compre isso para meu filho.[n]Akechi-kun e realmente bastante impressionante,[n]afinal.[n][w][e]
[s][vp 8 2 1 0 10 0]E verdade que se voce quiser que seu filho[n]ter sucesso e ingressar na elite, educacao[n]sera muito importante.[n][w][e]

[msg MSG_SUKAUTOMAN_013_2_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Ahh, sim. Entao sua assinatura aqui, entao,[n]S'il Vous Plait...[n][w][e]

[msg MSG_SUKAUTOMAN_014_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Ei. Voce na equipe shido ou equipe[n]Phantom Thieves? Whiiiiich um[n]voce esta!?[n][w][e]

[sel SEL_SUKAUTOMAN_014_0_0 top]
[s]Os ladroes fantasmas, e claro.[e]
[s]Nenhum.[e]

[msg MSG_SUKAUTOMAN_014_1_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Sim. Voce entendeu![n][w][e]
[s][vp 8 2 1 0 8 0]Qualquer novo primeiro-ministro funcionara[n]para "purificar" Shinjuku de caras como eu.[n]De jeito nenhum eu estou caido por isso.[n][w][e]

[msg MSG_SUKAUTOMAN_014_2_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Ahhhh, um desses tipos cautelosos![n]Voce realmente nao tem uma opiniao,[n]voce?[n][w][e]

[msg MSG_SUKAUTOMAN_014_3_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Enfim, voce quer se tornar um fantasma[n]Ladrao com este kit de jacking de onda de radio?[n][w][e]

[msg MSG_SUKAUTOMAN_015_0_0 [Fishy Hawker]]
[s][vp 8 2 1 0 8 0]Shinjuku esta pronto para. A mudanca em[n]Os partidos governantes farao esta area[n]Ainda mais regulamentado.[n][w][e]
[s][vp 8 2 1 0 8 0]Alguem me diga onde eu posso cacar.[n]Vou explorar, estou disposto a fazer qualquer coisa.[n][w][e]
[s][vp 8 2 1 0 8 0]O que? Voce nao precisa de uma ma[n]Artista de fraude? Quem voce acha[n]Voce esta falando t  ei![n][w][e]
[s][vp 8 2 1 0 8 0]... PSH. Droga![n][w][e]

[msg MSG_SUKAUTOMAN_016_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Sim... quem faz aqueles malditos policiais pensam[n]eles sao? Eles nao podem simplesmente nos encarar todos[n]Curtiu isso.[n][w][e]

[sel SEL_SUKAUTOMAN_016_0_0 top]
[s]Voce nao esta trabalhando?[e]
[s]Voce esta relaxando?[e]

[msg MSG_SUKAUTOMAN_016_1_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Heh, eu estaria trabalhando se fizesse a diferenca.[n][w][e]

[msg MSG_SUKAUTOMAN_016_2_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Eu nao estou relaxando. Trabalhar e apenas um desperdicio[n]do meu tempo hoje em dia.[n][w][e]

[msg MSG_SUKAUTOMAN_016_3_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Meu trabalho e sobre a venda de acordos que sao[n]"Bom demais para ser verdade" para as pessoas que sentem[n]nao realizado...[n][w][e]
[s][vp 8 2 1 0 8 0]Entao, quando o mundo inteiro esta cheio de[n]pessoas que estao totalmente satisfeitas com seus[n]Vidas, nao posso vender nada.[n][w][e]
[s][vp 8 2 1 0 8 0]Quero dizer, por que estou preso a um trabalho como este[n]Quando todo mundo esta tao feliz? eu estive[n]Sentindo-se ultimamente...[n][w][e]

[msg MSG_SUKAUTOMAN_017_0_0 [Patrolling Police Officer]]
[s][f 4 23 1 10 3 10 0 10][vp 8 2 1 0 10 0]Voce ainda esta assediando pessoas? Arranje um[n]trabalho real. Tenho certeza que seus pais fariam[n]concorde comigo.[n][w][e]

[msg MSG_SUKAUTOMAN_017_1_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]...Voce tem razao. Meu velho era um[n]Guy de destaque que nunca jogou.[n][w][e]
[s][vp 8 2 1 0 8 0]Do jeito que estou vivendo agora, nao pude[n]Olhe-o nos olhos! eu quero mudar[n]de coracao, oficial![n][w][e]

[msg MSG_SUKAUTOMAN_017_2_0 [Patrolling Police Officer]]
[s][f 4 23 1 10 3 10 0 10][vp 8 2 1 0 10 0]O importante e que voce acredita[n]em voce. Voce consegue! eu tenho fe[n]em voce![n][w][e]

[msg MSG_SUKAUTOMAN_018_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 12 10 3 10][vp 8 2 1 0 8 0]Estou voluntario para limpar as ruas.[n]E bom estar indo bem![n][w][e]
[s][vp 8 2 1 0 8 0]Vou trabalhar minha bunda e pagar de volta[n]Todo mundo que eu enganava.[n][w][e]

[sel SEL_SUKAUTOMAN_018_0_0 top]
[s]Parece dificil.[e]
[s]Voce nao parece bem.[e]

[msg MSG_SUKAUTOMAN_018_1_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]E porque estou trabalhando o dia todo e a noite toda![n]Mas nao importa o que acontece com[n]meu corpo.[n][w][e]
[s][vp 8 2 1 0 8 0]Vou pagar o dinheiro,[n]Peca desculpas... e se torne um decente o suficiente[n]Ser humano para ir ver meu velho![n][w][e]

[msg MSG_SUKAUTOMAN_019_0_0 [Fishy Hawker]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Ah cara... tanto para o shinjuku[n]Estrategia de descriminalizacao. Caramba.[n][w][e]
[s][vp 8 2 1 0 8 0]Acho que ja era hora de sair daqui.[n]Eu me pergunto para onde irei a seguir...[n][w][e]

[msg MSG_GEINOUDON_001_0_0 [Dream-Chasing Girl]]
[s][vp 8 2 1 0 12 0]Como voce esta? Oh sim?[n]Isso e bom  Estou orgulhoso de voce.[n][w][e]
[s][vp 8 2 1 0 12 0]Huh? Estou bem. Sim, eu sei que ha[n]Ultimamente foram alguns incidentes estranhos.[n]Claro, terei cuidado.[n][w][e]
[s][vp 8 2 1 0 12 0]Nao se preocupe com sua grande irma.[n]Eu nao vou me deixar conseguir[n]enganou novamente, eu prometo.[n][w][e]
[s][vp 8 2 1 0 12 0]Uma vez que eu me tornei cantor, vou fazer[n]Esse dinheiro de volta e mais alguns.[n]Nao, nao estarei em casa por um tempo.[n][w][e]

[msg MSG_GEINOUDON_002_0_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Essa audicao foi absolutamente fabulosa![n]Minha empresa, a agencia Asakura, faria[n]Adoro representa-lo![n][w][e]

[msg MSG_GEINOUDON_002_1_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]Isso e otimo, mas... voce ve, eu estava[n]enganado antes, e com tudo o que e[n]Aconteceu, estou um pouco cauteloso.[n][w][e]

[msg MSG_GEINOUDON_002_2_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Olha, apenas deixe-me ser seu produtor.[n]Voce tem um monte de talento, sabe?[n]Eu juro que vou cuidar bem de voce.[n][w][e]

[msg MSG_GEINOUDON_002_3_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]Eu realmente, realmente quero ser um cantor...[n]Mas posso confiar em voce?[n][w][e]

[msg MSG_GEINOUDON_003_0_0 [Show-Biz Veteran]]
[s][vp 8 2 1 0 11 0]As pessoas estao se levantando agora que[n]Kaneshiro esta atras das grades.[n][w][e]
[s][vp 8 2 1 0 11 0]Isso significa apenas que temos que ir atras[n]aqueles pobres caipiras ingênuos do interior![n][w][e]
[s][vp 8 2 1 0 11 0]Traga-os, mesmo que voce precise[n]Faca por forca "entendeu?[n][w][e]

[msg MSG_GEINOUDON_004_1_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]Eu nao quero fazer uma sessao de fotos sexy...[n]Eu so quero cantar.[n][w][e]

[msg MSG_GEINOUDON_004_2_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Olha, entendi, eu realmente faco. Voce e um[n]um pouco nervoso, com certeza, mas voce tem que[n]Faca isso para conquistar o coracao das pessoas.[n][w][e]
[s][vp 8 2 1 0 11 0]Voce sabe, eu queria ser um cantor,[n]tambem, entao quando voce esta seguindo o seu[n]Sonhos, isso me lembra de mim mesmo.[n][w][e]

[msg MSG_GEINOUDON_004_3_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]Voce fez, Sr. Asakura? Voce era[n]apenas como eu? Bem, entao eu acho[n]Eu posso confiar em voce![n][w][e]

[msg MSG_GEINOUDON_005_0_0 [Show-Biz Veteran]]
[s][vp 8 2 1 0 11 0]De a eles qualquer que seja o trabalho disponivel.[n]Eles farao qualquer coisa por uma grande estreia.[n][w][e]
[s][vp 8 2 1 0 11 0]Depois de faze-los se despir, sera[n]Navegacao suave de la.[n][w][e]
[s][vp 8 2 1 0 11 0]Looks sao importantes. Os clientes desejam[n]Uma garota linda. Talvez tenhamos[n]Algum trabalho cosmetico tambem feito.[n][w][e]

[msg MSG_GEINOUDON_006_0_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]Hum, isso realmente deveria ser fantasma[n]Ladroes de cosplay? Parece lingerie...[n][w][e]

[msg MSG_GEINOUDON_006_3_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Fazendo meu sonho  nosso sonho  Venha[n]Verdadeiro e um fardo pesado... eu nao era capaz[n]para assumir isso.[n][w][e]

[msg MSG_GEINOUDON_006_4_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]Sim... voce esta certo, Sr. Asakura.[n]Eu tenho que trabalhar duro para nos dois![n][w][e]
[s][vp 8 2 1 0 12 0]Ok! Eu vou fazer isso![n][w][e]

[msg MSG_GEINOUDON_007_0_0 [Show-Biz Veteran]]
[s][vp 8 2 1 0 11 0]Como o jantar com o Okumura[n]ternos vao? Certifique-se de me enviar[n]fotos do nosso "talento".[n][w][e]
[s][vp 8 2 1 0 11 0]Isso e importante, seu idiota.[n]Como voce acha que estamos passando?[n][w][e]
[s][vp 8 2 1 0 11 0]Eles sao um patrocinador muito importante,[n]um que nao podemos perder, entao nos[n]Tenho que cuidar bem deles![n][w][e]

[msg MSG_GEINOUDON_008_0_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Bem, a coisa da Okumura Foods caiu[n]Atraves dos. Mas eu tenho algo novo[n]Alinhado com um grande produtor de fotos.[n][w][e]
[s][vp 8 2 1 0 11 0]Voce quer fazer sua grande estreia, certo?[n][w][e]

[msg MSG_GEINOUDON_008_1_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]E claro! Vou trabalhar tanto quanto for necessario![n][w][e]

[msg MSG_GEINOUDON_008_2_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]E bom ouvir... nunca perca isso[n]Dirija, tudo bem?[n][w][e]

[msg MSG_GEINOUDON_009_0_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Sua filmagem de lingerie foi um grande sucesso.[n]Todo mundo esta falando sobre como[n]sexy voce e.[n][w][e]

[msg MSG_GEINOUDON_009_1_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]Sobre isso... voce ve, eu acho que realmente[n]preferiria continuar cantando.[n][w][e]

[msg MSG_GEINOUDON_009_2_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Ouca, isso e apenas um negocio como sempre[n]para a industria. Voce quer sobreviver[n]Neste mundo, nao e?[n][w][e]
[s][vp 8 2 1 0 11 0]Entao voce precisa ser uma estrela. Voce precisa[n]ser divertido. Apenas sendo capaz de[n]Cante nao e bom o suficiente  entendeu?[n][w][e]

[msg MSG_GEINOUDON_010_0_0 [Dream-Chasing Girl]]
[s][vp 8 2 1 0 12 0]Ei, como voce esta segurando? Seria um prazer[n]Ouca que  Estou orgulhoso de voce.[n][w][e]
[s][vp 8 2 1 0 12 0]Se este show que eu tenho correr bem, eu vou[n]Seja capaz de fazer minha estreia em breve.[n]MHM, isso mesmo.[n][w][e]
[s][vp 8 2 1 0 12 0]... O que voce quer dizer com eu[n]Nao soa feliz?[n][w][e]
[s][vp 8 2 1 0 12 0]Estou apenas preocupado com todo esse fantasma[n]Ladroes de negocios, isso e tudo. Tenho certeza[n]Vai se acalmar em breve.[n][w][e]
[s][vp 8 2 1 0 12 0]Estou tao perto de realizar meu sonho...[n]Eu preciso continuar trabalhando duro.[n][w][e]

[msg MSG_GEINOUDON_011_0_0 [Show-Biz Veteran]]
[s][vp 8 2 1 0 11 0]Ela correu chorando!?[n][w][e]
[s][vp 8 2 1 0 11 0]Nao, nao e isso que eu tinha em mente.[n]Deve ter sido algo que ela[n]fez por conta propria.[n][w][e]
[s][vp 8 2 1 0 11 0]Como um pedido de desculpas, eu vou te oferecer nosso[n]Melhor garota. Nao, por favor, eu insisto...[n][w][e]
[s][vp 8 2 1 0 11 0]Estou ansioso para sua continuacao[n]patrocinio da Agencia Asakura![n][w][e]
[s][vp 8 2 1 0 11 0]...Ola? Hellooo?[n][w][e]

[msg MSG_GEINOUDON_012_0_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Ei, um de nossos clientes reclamou[n]sobre voce! Ele disse que voce o virou[n]para baixo e reservou![n][w][e]
[s][vp 8 2 1 0 11 0]O que diabos foi isso!?[n]Eu pensei que voce estava disposto a fazer[n]O que for necessario para torna-lo grande![n][w][e]

[msg MSG_GEINOUDON_012_1_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]Nao, isso e... nao e isso que eu quis dizer...[n][w][e]

[msg MSG_GEINOUDON_012_2_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Voce sabe como isso me faz[n]olhar? Leve sua bunda la de volta, implore[n]por perdao e entrete-lo![n][w][e]

[msg MSG_GEINOUDON_012_3_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Voce realmente acha que pode ser um verdadeiro[n]cantor? Ouca, podemos ligar para voce[n]Um "talento", mas isso nao significa merda![n][w][e]
[s][vp 8 2 1 0 11 0]Agora volte ao trabalho antes de nos[n]perder o cara. Da proxima vez que voce[n]Cross Me, eu vou acabar com voce.[n][w][e]

[msg MSG_GEINOUDON_012_4_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]Por que voce esta sendo tao mau?[n]Eu tenho feito o meu melhor para[n]estreia como cantor...[n][w][e]

[msg MSG_GEINOUDON_013_0_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]De onde tudo isso vem?[n]Voce acha que eu posso apenas te perdoar[n]Depois daquelas coisas que voce disse?[n][w][e]

[msg MSG_GEINOUDON_013_1_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Por favor, voce deve! Eu preciso de voce[n]Para ver como estou arrependido! Voce deve[n]eu tanto, pelo menos![n][w][e]

[msg MSG_GEINOUDON_013_2_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]O que voce ainda esta agindo[n]Tao auto-absorvido! Eu nao preciso[n]faca qualquer coisa![n][w][e]

[msg MSG_GEINOUDON_013_3_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]* SOB* por favor! Eu preciso que voce![n]Eu preciso que voce me veja maquiagem[n]Por tudo o que eu fiz![n][w][e]

[msg MSG_GEINOUDON_014_0_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Ola, meu nome e Shiro Asakura.[n]Eu fiz coisas terriveis para[n]Mulheres que aspiram ser idolos.[n][w][e]

[msg MSG_GEINOUDON_014_1_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 21 10 20 10][vp 8 2 1 0 12 0]Tem certeza que quer que eu grave[n]isto? Voce nao precisa fazer upload do seu[n]desculpas online...[n][w][e]

[msg MSG_GEINOUDON_014_2_0 [Show-Biz Veteran]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]...Sim eu tenho certeza. A unica maneira de[n]eu expiar e confessar todos os meus[n]Intelas para a Internet.[n][w][e]
[s][vp 8 2 1 0 11 0]Eu fiz coisas como fazer mulheres[n]Faca cirurgia plastica, tornando-os[n]Durma com clientes... Sinto muito![n][w][e]

[msg MSG_GEINOUDON_015_0_0 [Shiro Asakura]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Quando estou em publico, pessoas[n]aponte e tire fotos minhas...[n][w][e]

[msg MSG_GEINOUDON_015_1_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]Sim, voce esta por toda a midia social[n]agora. Voce sabia que as pessoas ligam[n]Voce "gritando Asakura"?[n][w][e]

[msg MSG_GEINOUDON_015_2_0 [Shiro Asakura]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Eu nao achei que acabasse assim...[n]Nao tenho certeza se e bom ou ruim[n]coisa tambem.[n][w][e]

[msg MSG_GEINOUDON_015_3_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]As pessoas o reconhecem mais do que[n]Eles me fazem, Sr. Asakura. Voce e[n]Como um idolo, de certa forma.[n][w][e]
[s][vp 8 2 1 0 12 0]... hm? Espere, vamos pensar sobre[n]isso por um segundo...[n][w][e]

[msg MSG_GEINOUDON_016_0_0 [Shiro Asakura]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Quando estou em publico, pessoas[n]aponte e tire fotos minhas...[n][w][e]

[msg MSG_GEINOUDON_016_1_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]Sim, voce esta por toda a midia social[n]agora. Voce sabia que as pessoas ligam[n]Voce "gritando Asakura"?[n][w][e]

[msg MSG_GEINOUDON_016_2_0 [Shiro Asakura]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]Eu nao achei que acabasse assim...[n]Nao tenho certeza se e bom ou ruim[n]coisa tambem.[n][w][e]

[msg MSG_GEINOUDON_016_3_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]As pessoas o reconhecem mais do que[n]Eles me fazem, Sr. Asakura. Voce e[n]Como um idolo, de certa forma.[n][w][e]
[s][vp 8 2 1 0 12 0]... hm? Espere, vamos pensar sobre[n]isso por um segundo...[n][w][e]

[msg MSG_GEINOUDON_017_0_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]Ex-CEO e Predator de Idol Teen...[n]sofre uma mudanca de coracao para[n]Uma estreia impressionante de canto![n][w][e]
[s][vp 8 2 1 0 12 0]Ninguem nunca fez isso antes.[n]A Internet com certeza vai[n]Faca de voce um meme![n][w][e]

[msg MSG_GEINOUDON_017_1_0 [Shiro Asakura]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]B-b-but nao e isso levando as coisas um pouco[n]muito longe? Eu tenho uma reputacao, sabe?[n]... ou, pelo menos, acho que ainda faco.[n][w][e]

[msg MSG_GEINOUDON_017_2_0 [Dream-Chasing Girl]]
[s][f 4 23 1 12 3 10 0 10][vp 8 2 1 0 12 0]Sr. Asakura, se voce esta falando serio[n]Arrependo-se, entao voce tem que fazer o que eu disse.[n][w][e]
[s][vp 8 2 1 0 12 0]Ouca, comigo como seu produtor,[n]Tudo vai ficar otimo![n]Voce nunca foi tao popular![n][w][e]

[msg MSG_041_0_0 [Dream-Chasing Girl]]
[s][vp 8 2 1 0 12 0]Nao, nao posso voltar para casa  nao para um[n]enquanto. Nao esta seguro agora.[n][w][e]
[s][vp 8 2 1 0 12 0]Ha algumas pessoas que eu...[n]Eu simplesmente nao consigo me afastar.[n]Por favor entenda.[n][w][e]
[s][vp 8 2 1 0 12 0]Sim, eu sei... me desculpe...[n]Diga a todos que eu disse "Oi", ok?[n][w][e]
[s][vp 8 2 1 0 12 0]Nao... meu sonho, isso... nao[n]materia. Nao mais...[n][w][e]

[msg MSG_GRT_main_All_007_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38504 0 0]Ouvi dizer que ha um crime[n]anel que tem sido[n]Alvejando os alunos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37702 0 0]Se a policia nem consegue[n]Toque-os, entao o que[n]Devemos fazer?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_003 [Dream-Chasing Girl]]
[s][vp 9 2 65535 39452 0 0]Eu estou dizendo a voce,[n]Shibuya e muito mais[n]perigoso agora...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_004 [Dream-Chasing Girl]]
[s][vp 9 2 65535 38652 0 0]Uau... eu acho que voce nao pode[n]realmente diga isso para a policia...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41505 0 0]Eu acho que eles nao podem segmentar voce[n]Se voce nao for para Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44001 0 0]O que a policia esta fazendo!?[n]Nao e em momentos como esses[n]Quando precisamos mais deles?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45355 0 0]A policia e tao inutil...[n]O que eles estao fazendo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_006 [Dream-Chasing Girl]]
[s][vp 9 2 65535 43604 0 0]Omigosh! Nao e isso[n]Apenas o pior?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_007 [Dream-Chasing Girl]]
[s][vp 9 2 65535 43902 0 0]Cara, vamos evitar[n]de Shibuya por enquanto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39804 0 0]Sou so eu, ou sou[n]Eu vendo cada vez mais[n]bandidos em Shibuya?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40901 0 0]O que a policia esta fazendo?[n]Nao e o trabalho deles para[n]lidar com isso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42913 0 0]Eu ouco que eles forcaram um[n]muitas garotas para trabalhar[n]eles como prostitutas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_009 [Dream-Chasing Girl]]
[s][vp 9 2 65535 38052 0 0]Estou com muito medo de sair[n]Em Shibuya. Vamos[n]Em outro lugar.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38754 0 0]Eu acho que eles nao podem segmentar voce[n]Se voce nao for para Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38452 0 0]Se a policia nem consegue[n]Toque-os, entao o que[n]Devemos fazer?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38052 0 0]Voce realmente esperava o[n]Policia para obter algum resultado?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_012 [Dream-Chasing Girl]]
[s][vp 9 2 65535 38401 0 0]Ei, e verdade que[n]ele foi alvo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39405 0 0]Phantom Thief chamando[n]cartao? Isso e algo[n]Isso esta em um novo filme?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37754 0 0]Voce ouviu algo sobre[n]ladroes fantasmas aparecendo em[n]Shibuya? Sobre o que e isso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43505 0 0]Esses cartoes de chamada[n]tem que ser apenas uma brincadeira.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37953 0 0]Eu ouvi dizer que eles eram[n]Postado em todo o Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45354 0 0]Seria interessante se[n]Esse cartao de visita era real...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46255 0 0]Sao esses cartoes de chamada[n]Realmente esse grande negocio?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39104 0 0]Um cartao de chamada?[n]O que voce esta falando?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38554 0 0]Um ladrao fantasma chamando[n]cartao? Por favor, ha[n]De jeito nenhum isso e real.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42104 0 0]Todos em Shibuya's[n]Falando sobre ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39155 0 0]Phantom Thief Calling Calls?[n]Nossa, voce e estupido o suficiente[n]para realmente acreditar nisso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44504 0 0]Phantom Thieves?[n]O que voce esta falando?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38200 0 0]Estou feliz que eles o pegaram.[n]Quero dizer, eu poderia ter acabado[n]tornando-se uma de suas vitimas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46054 0 0]Kaneshiro era o chefe[n]daquele anel de crime, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43554 0 0]Seria muito emocionante[n]Se os ladroes fantasmas existissem[n]Na vida real, embora.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37954 0 0]Eu ouvi aquele anel de crime[n]A base estava em Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43653 0 0]Parece que eles prenderam[n]Um grande criminoso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42550 0 0]Estou feliz que eles presos[n]ele antes de comecarem[n]Visando as pessoas em Shinjuku.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37503 0 0]Foi realmente grande[n]organizacao, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43200 0 0]Eu ouvi aquele anel de fraude[n]Em Shibuya, foi esmagado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43903 0 0]Se os ladroes fantasmas eram[n]Na verdade, eu acho que a vida[n]seria mais interessante.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45300 0 0]Estou feliz que tudo isso tenha[n]resolvido antes que eu pudesse[n]ser afetado por tudo isso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41404 0 0]Aparentemente, esse crime[n]Ring estava baseado em Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41204 0 0]Parece fantasma[n]Ladroes sao toda a raiva[n]entre jovens.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41304 0 0]Entao era fantasma[n]Ladroes que derrotaram[n]Aqueles criminosos em Shibuya?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41954 0 0]E verdade que o fantasma[n]ladroes tirou isso[n]Kaneshiro Guy?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43600 0 0]Eu acho que tudo isso sobre[n]Os ladroes fantasmas eram verdadeiros.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45568 0 0]Parece phantom ladroes[n]sao um topico muito quente entre[n]jovens agora.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44904 0 0]Entao foram os ladroes fantasmas[n]que derrubou os golpistas[n]Em Shibuya?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39103 0 0]Entao, ele foi pego, apenas[n]Como o cartao de visita[n]disse que faria...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37656 0 0]Eles sao muito melhores[n]do que a policia![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37554 0 0]Voce viu as noticias?[n]Parece assim[n]O cartao de visita era real![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40704 0 0]Entao, os ladroes fantasmas...[n]Sao eles enviando tudo[n]Esses cartoes de visita, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39604 0 0]Voce esta me dizendo isso[n]tudo naquele cartao de visita[n]realmente aconteceu? Serio?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38103 0 0]Aquele grupo medjed escolheu[n]Uma briga com ladroes Phantom?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43454 0 0]Eles sao mundialmente famosos[n]hacktivistas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40355 0 0]Quais sao esses hackers[n]tentando fazer, provocando o[n]Phantom Thieves assim?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38254 0 0]Quais sao os fantasmas[n]Ladroes vao fazer?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45569 0 0]Enfim, eu simplesmente nao[n]quer que eles pensem que podem[n]Apenas faca o que quiserem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39504 0 0]Aparentemente, aquele hacker[n]O grupo e conhecido em todo o mundo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39455 0 0]Quais sao esses hackers[n]tentando fazer, provocando o[n]Phantom Thieves assim?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40454 0 0]Eles sairam do seu caminho[n]para insulta-los. Como vai o[n]Phantom Thieves reage?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37504 0 0]Aparentemente, aquele hacker[n]O grupo e conhecido em todo o mundo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40705 0 0]Quais sao esses hackers[n]tentando fazer, provocando o[n]Phantom Thieves assim?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46404 0 0]Eles sairam do seu caminho[n]para insulta-los. Como vai o[n]Phantom Thieves reage?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43804 0 0]Quando o Phantom[n]Ladroes se mostram?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_13_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43156 0 0]Esses caras medjed parecem[n]mas noticias. Espero o fantasma[n]Ladroes saem por cima![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_14_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43703 0 0]Os ladroes fantasmas[n]estao ate sendo cacados[n]por hackers![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_15_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44052 0 0]O que e medjed tentando[n]Para puxar com esse golpe?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46303 0 0]Phantom Thieves versus[n]hackers? Tudo bem, tempo[n]Para fazer minhas apostas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40602 0 0]O que eles podem[n]fazer contra esses hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43555 0 0]A midia esta realmente tocando[n]ate este Phantom Thieves[n]versus hackers.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40654 0 0]Eu me pergunto o que o[n]Phantom Thieves 'Next[n]Move vai ser...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44054 0 0]O que eles podem[n]fazer contra esses hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37505 0 0]A midia esta realmente tocando[n]ate este Phantom Thieves[n]versus hackers.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46003 0 0]Eu me pergunto o que aqueles[n]Os ladroes fantasmas sao[n]vou fazer sobre isso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38254 0 0]Quem sabe o que o[n]Os ladroes Phantom farao![n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43900 0 0]eu realmente quero ver[n]Como os ladroes fantasmas[n]responda a isso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43953 0 0]Como os ladroes fantasmas podem[n]lutar contra hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44853 0 0]O que eles podem[n]fazer contra esses hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37900 0 0]Estou feliz que irritante[n]O grupo de hackers foi fechado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39700 0 0]Parece aqueles[n]Os hackers fecharam o site![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43400 0 0]Os ladroes Phantom sao[n]incrivel! Nem mesmo hackers[n]ter uma chance contra eles![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43504 0 0]Foi fantasma ladroes que[n]Desligue o site de Medjed!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46354 0 0]Aguentar, medjed[n]O site foi assumido!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43650 0 0]Estou feliz que eles pudessem[n]Ponha um fim a isso antes[n]Qualquer coisa ruim poderia acontecer.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44904 0 0]Eu ouvi os hackers[n]fechou o site deles![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42850 0 0]Estou feliz que irritante[n]O grupo de hackers foi fechado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44550 0 0]Parece aqueles[n]Os hackers fecharam o site![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43906 0 0]Eu ouvi que o site deles tinha o[n]Phantom Thieves Logo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45503 0 0]Eu conhecia o fantasma[n]Ladroes ganhariam![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43604 0 0]Eu ouvi que o site de Medjed era[n]Assumido por outra pessoa![n]Esses hackers foram agradados![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37606 0 0]Parece o[n]Os ladroes fantasmas sao[n]Os que nos salvaram![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37756 0 0]Estou tao feliz por termos o[n]Phantom Thieves do nosso lado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43456 0 0]Eles sao como o[n]Construcao da justica![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41600 0 0]Sim, e isso que herois reais[n]devem ser como.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40853 0 0]Estou tao feliz que o fantasma[n]Ladroes estao aqui para nos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45356 0 0]Obrigado, Phantom Thieves![n]Saude para voce![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38206 0 0]Eu conhecia os ladroes fantasmas[n]eram os mocinhos. Eu sabia.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43403 0 0]Estou feliz pelo fantasma[n]Ladroes estao do nosso lado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43203 0 0]Os ladroes fantasmas[n]sao realmente incriveis![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38403 0 0]Parabens, ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39156 0 0]Incrivel, o Phantom[n]Ladroes realmente existem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38306 0 0]Eu amo os ladroes fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44606 0 0]Eu conheco alguem que e louco[n]Para ladroes Phantom e coleta[n]toda a sua mercadoria...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45754 0 0]Eles estao fazendo uma TV especial[n]Sobre os ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43406 0 0]Aqueles ladroes fantasmas sao[n]Super-herois da vida real![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43558 0 0]Voce sabe, eu realmente admiro[n]os ladroes fantasmas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43206 0 0]Tudo o que eles falam sobre[n]A TV e Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43654 0 0]Voce nao sabe sobre[n]os ladroes fantasmas?[n]Voce esta brincando certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41906 0 0]Eles estao montando uma TV[n]Especial sobre ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46306 0 0]Aquele fantasma ladroes[n]A mercadoria e bastante popular.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45250 0 0]Nosso pais como seguro, desde que[n]Como temos os ladroes fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46254 0 0]Os ladroes fantasmas sao tao legais![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41858 0 0]Por favor, faca meu chefe[n]tenha uma mudanca de coracao...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44000 0 0]Ninguem pode vencer[n]Os ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_12__2 [Dream-Chasing Girl]]
[s][vp 9 2 65535 44056 0 0]Os ladroes fantasmas sao[n]muito legal![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_13_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43754 0 0]Eu gosto de como eles usam mascaras[n]para esconder suas identidades![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_14_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43604 0 0]Todos os meus clientes falam[n]Sobre sao os ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_15_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44003 0 0]Eu amo o Japao porque[n]Tem ladroes fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_16_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43752 0 0]Existem tantas pessoas[n]Eu gostaria que eles fossem atras![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43404 0 0]Voce ja ouviu os rumores[n]Sobre Okumura Foods?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38652 0 0]Eu achei estranho[n]quao rapido eles cresceram...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43451 0 0]Onde quer que voce va,[n]sempre havera[n]empresas corruptas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40550 0 0]Eu achei incrivel[n]Como eles expandiram seus[n]armazena tao rapidamente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44001 0 0]Pelo que ouco, as coisas[n]Eles dizem que as noticias sao apenas[n]a ponta do iceberg...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45569 0 0]Parece que eles fizeram muito[n]de coisas obscuras para poder[n]para crescer tao rapido...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40302 0 0]Estou surpreso este assunto[n]nao foi tornado publico ate agora...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39802 0 0]Eu achei incrivel[n]Como eles expandiram seus[n]armazena tao rapidamente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43602 0 0]Eles tratam seus funcionarios[n]Muito mal, nao e?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43902 0 0]A noticia sobre eles e bonita[n]ruim, mas eu ouco que e realmente[n]muito, muito pior do que isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40709 0 0]Eles os tratam como escravos,[n]certo? Que empresa terrivel.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42154 0 0]Voce ja ouviu os rumores[n]Sobre Okumura Foods?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39806 0 0]Os ladroes Phantom estao fazendo[n]O que nao podemos fazer a nos mesmos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39303 0 0]Eu gostaria que eles fossem apenas[n]sair e se livrar de todos[n]o mal no mundo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43400 0 0]Desca, Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43553 0 0]Nao e sobre o tempo de tempo[n]Para os ladroes Phantom[n]Para fazer a mudanca deles?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39356 0 0]Espero que os ladroes fantasmas[n]Continue trabalhando para reformar a sociedade.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43650 0 0]Eu me pergunto se aqueles Phantom[n]Ladroes vao segmentar[n]Okumura Foods a seguir.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39106 0 0]Os ladroes fantasmas[n]vai cuidar disso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41950 0 0]Tudo ficara bem![n]Aqueles ladroes fantasmas sao[n]Vou cuidar disso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40806 0 0]Continue reformando a sociedade[n]e fazer as pessoas se arrependerem por[n]Seus maus, ladroes fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43906 0 0]Os ladroes fantasmas vao[n]Ajude-nos fazendo as coisas[n]que nao podemos fazer por conta propria.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45506 0 0]Tenho certeza que o Phantom[n]Ladroes farao[n]algo sobre isso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41400 0 0]Espero que os ladroes fantasmas[n]Continue trabalhando para reformar a sociedade.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41051 0 0]Ensine a essa licao de Okumura![n]Va busca-lo, ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45903 0 0]Estou ansioso para[n]Okumura implorando[n]Perdao nas noticias![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43403 0 0]Ensine a essa licao de Okumura![n]Va busca-lo, ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43503 0 0]Eu sabia que eles segmentariam Okumura![n]Boa indo, ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37753 0 0]Esse CEO me irrita![n]Apresse-se e derrube-o![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45570 0 0]Punir esse CEO corrupto![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41756 0 0]Eles enviaram um cartao de chamada! Pegue[n]Pronto para cair em seu estupido[n]joelhos e confessar, Okumura![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39450 0 0]Bom, Phantom Thieves![n]Um homem egoista como ele precisa[n]para ser derrubado um entalhe![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40400 0 0]Isso e o que ele recebe para agir[n]Tudo alto e poderoso. Ele totalmente[n]merece o que quer que aconteca![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38701 0 0]Eles encontraram o cartao de visita![n]Tudo bem, faca esse CEO pagar![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42053 0 0]Mal posso esperar para ver o Okumura[n]Conferencia de imprensa de desculpas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37650 0 0]Aquele CEO Shady merece[n]para ser alvo pelo[n]Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41757 0 0]Quem disse que voce poderia[n]Mate ele!? Voce se foi[n]Muito longe, ladroes Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43801 0 0]Isso foi um jogo de poder total...[n]Eu nao consigo nem dormir agora[n]por causa do trauma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43407 0 0]Eu nao posso acreditar[n]os ladroes fantasmas[n]Na verdade, matou alguem...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43502 0 0]Os ladroes fantasmas[n]fez tolos fora de nos[n]Com essa execucao publica![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38557 0 0]Os ladroes Phantom eram[n]O mal o tempo todo, nao era!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45357 0 0]Considerando como isso[n]aconteceu, eles devem ter[n]Matou-o pela diversao![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44957 0 0]Tanto para mudar[n]seu coracao! Eles sao apenas[n]Um monte de criminosos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43751 0 0]Ninguem disse para mata-lo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38601 0 0]Os ladroes fantasmas[n]sao os verdadeiros bandidos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43907 0 0]Aqueles ladroes fantasmas[n]sao puro mal![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39157 0 0]Eu nao posso acreditar que eles fizeram[n]um show de mata-lo como[n]este! Isso foi horrivel![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45751 0 0]Os ladroes Phantom eram[n]O mal o tempo todo, nao era!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41205 0 0]O governo nao fara[n]qualquer coisa e a policia[n]sao totalmente nao confiaveis...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44502 0 0]E alarmante com que frequencia aqueles[n]Avarias psicoticas sao[n]acontecendo. Alguem pare isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43407 0 0]Temos que viver com medo de[n]Aqueles ladroes fantasmas agora...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43555 0 0]Aqueles ladroes fantasmas[n]precisa ser parado.[n]Eu nao quero morrer...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45907 0 0]Quanto tempo o fantasma vai[n]Ladroes estao soltos?[n]Apresse-se e faca algo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43657 0 0]Nao podemos deixar o fantasma[n]Ladroes correm de graca.[n]Alguem tem que dete-los![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40302 0 0]Aquelas quebras psicoticas[n]que estao acontecendo[n]sao todos tao horriveis...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41355 0 0]O governo nao fara[n]qualquer coisa e a policia[n]sao totalmente nao confiaveis...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42357 0 0]Por que a policia esta deixando[n]um grupo tao perigoso[n]correr assim!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39802 0 0]Essas quebras psicoticas sao[n]realmente perigoso. Tem alguem[n]descobriu como dete-los?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42057 0 0]Alguem tem que fazer algo[n]Sobre esses ladroes fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44451 0 0]Por que eles realmente nao fazem[n]Um plano para captura-los!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41954 0 0]Eu ouvi o dinheiro da recompensa[n]Para os ladroes Phantom[n]e bem alto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44551 0 0]Se estou pagando dinheiro a eles,[n]A policia deveria estar recebendo[n]resultados! Eles sao inuteis![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43404 0 0]Eu acho que devo ir...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43504 0 0]Se eu pudesse encontrar algumas informacoes[n]nos ladroes Phantom,[n]Eu seria rico...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43611 0 0]Phantom Thieves, certo? Eu estou[n]dizendo a voce, o esconderijo deles[n]ali em algum lugar![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45571 0 0]Apenas pegue o Phantom[n]Ladroes ja. Eu nao[n]Cuidado com o que e preciso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38159 0 0]Nao apenas divulgue uma recompensa![n]Prende-los ja![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38405 0 0]Eles nao demoraram muito[n]Para agir? Exatamente quando[n]Eles planejam prende-los?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43457 0 0]Entao, a policia tem[n]Finalmente ficou serio...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39404 0 0]Uma recompensa de 30 milhoes de ienes...[n]Esse valor e insano.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40707 0 0]Apresse-se e pegue[n]O assassino ja![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43601 0 0]Quanto tempo voce vai[n]Deixe esses ladroes soltarem!?[n]Eles sao assassinos enlouquecidos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40504 0 0]Uma eleicao de desvio, hein...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39605 0 0]HM, podemos realmente esperar muito[n]De uma nova administracao?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43411 0 0]Eu sei para quem estou votando[n]este ano![n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43553 0 0]Eu nunca votei em um[n]eleicao, mas talvez eu[n]Vai este ano.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43600 0 0]Talvez eu vote nisso[n]Um politico-Indice tambem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44054 0 0]Vou votar este ano![n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40755 0 0]Eu preciso ter certeza de[n]Escolha alguem confiavel[n]Esta eleicao...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43752 0 0]Talvez com a dissolucao de[n]Parlamento, o governo[n]vai agir juntos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38004 0 0]Entao, o partido no poder[n]dividido e depois um novo[n]A festa foi formada, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37504 0 0]Eu ouvi alguem dar um discurso[n]outro dia, e parte do[n]Coisas que ele disse que eu concordei.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39850 0 0]Eu tenho ouvido que as pessoas[n]estao colocando muita esperanca em[n]aquele novo partido politico.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46354 0 0]Ouvi dizer que eles vao ter[n]uma eleicao porque nosso[n]Parlamento se dissolveu.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38501 0 0]A policia e inutil...[n]Por favor, alguem traga aqueles[n]Phantom ladroes para a justica.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43854 0 0]Talvez haja uma conexao[n]entre os ladroes fantasmas[n]E aquele professor...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43402 0 0]Os ladroes Phantom estao em[n]as noticias todos os dias, mas eles[n]Ainda nao foi pego ainda...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38502 0 0]Os ladroes fantasmas[n]sao perigosos! Elas[n]tem que ser preso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43601 0 0]E tudo por causa daqueles[n]Phantom Thieves que eu sou[n]Nao esta recebendo clientes![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45568 0 0]Estou curioso sobre quem aqueles[n]Phantom Thieves realmente sao...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42655 0 0]Quais sao a policia[n]fazendo? Apresse-se e[n]Pegue-os ja...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45652 0 0]O governo nao fara[n]qualquer coisa e a policia[n]sao totalmente nao confiaveis...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45252 0 0]E aterrorizante que psicotico[n]Avarias acontecem com tanta frequencia.[n]Alguem tem que parar com isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43901 0 0]Quando eles estao planejando[n]Prenda esses ladroes fantasmas!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38457 0 0]Alguem tem que fazer algo[n]Sobre esses ladroes fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37952 0 0]E tao assustador como[n]Aquelas quebras psicoticas[n]tem estado em ascensao ultimamente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39803 0 0]Depois de ouvir Masayoshi Shido[n]Fale, eu me senti incrivelmente emocionado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39704 0 0]Eu tenho ouvido muito[n]sobre este representante[n]Nomeado Shido hoje em dia.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38204 0 0]Aquele politico chamado Shido[n]tem uma boa reputacao.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_04_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43650 0 0]Shido-san e tao[n]falante poderoso.[n]Ele e muito persuasivo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39503 0 0]Shido pensou muito[n]coisas. Outros politicos nao podem[n]ate nos de respostas retas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41353 0 0]Aquele shido representativo[n]esta trabalhando duro novamente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43354 0 0]Shido-san fez um[n]Nova festa, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43904 0 0]Muitas pessoas sao[n]falando sobre isso[n]Representante Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39854 0 0]Voce ouviu o discurso de Shido?[n]Eu me senti tao inspirado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44503 0 0]Voce ouviu Shido-san[n]Fala? Isso nao foi incrivel?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45657 0 0]Apresse-se e prenda o outro[n]Phantom Thieves! Eu conheco la[n]sao mais do que aquele que morreu![n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40052 0 0]Ele cometeu suicidio certo[n]Depois que ele foi preso?[n]Que se intensificou rapidamente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38404 0 0]Fez esse ladrao fantasma realmente[n]cometer suicidio no mesmo[n]dia ele foi preso...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_04_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45355 0 0]Ele deve ter sido completamente[n]Insano se ele se matasse...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39404 0 0]E verdade que o[n]ladrao fantasma eles[n]pego foi menor!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45655 0 0]Ele cometeu suicidio antes[n]Descobrimos qual o seu objetivo[n]Parece... parece que tudo acabou.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46352 0 0]Ele nao tinha[n]Para se matar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43907 0 0]Nos nunca vamos imaginar[n]fora como eles fizeram isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45302 0 0]Eu acho que ele sempre foi[n]Pronto para se matar[n]Se ele foi pego.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43604 0 0]Esse ladrao fantasma pensa[n]Matar a si mesmo vai fazer as pazes[n]Por tudo o que ele fez?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41953 0 0]Ninguem mais pode comparar[n]para o representante shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40653 0 0]Nao consigo imaginar ninguem[n]Alem de Shido-San vencer![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41753 0 0]A sociedade e muito ruim,[n]Mas Shido vai[n]Mude tudo isso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_04_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44050 0 0]Precisamos de Shido-san para mudar[n]Este pais, nao importa o que.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42853 0 0]Nos ja sabemos que Shido vai[n]Ganhe, mesmo sem eleicao.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46003 0 0]Nos vamos ficar bem.[n]Agora e a idade de[n]Representante Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41650 0 0]Shido representativo e[n]praticamente garantido[n]para vencer a proxima eleicao.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40750 0 0]Tudo vai acabar[n]Ok  Shido esta do nosso lado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40703 0 0]Nao ha nada para se preocupar[n]sobre se deixarmos tudo[n]para o representante shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44003 0 0]Shido representativo e[n]o unico em que podemos confiar.[n]Nao ha mais ninguem como ele![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38800 0 0]Podemos respirar com facilidade com[n]O Partido de Shido-San no poder.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41153 0 0]Eu nunca ouvi nada ruim[n]Sobre Shido-san. Ele realmente[n]tem uma reputacao de libra.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43403 0 0]Shido parece um bom[n]escolha! Podemos confiar nele![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37604 0 0]Eu nao sei muito[n]sobre ele, mas shido-san[n]Parece um bom candidato![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43604 0 0]Shido, hein?[n]Acho que vou votar nele![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43653 0 0]Shido-san apenas fica[n]acima de outros candidatos. Ele[n]tem isso, como vibe confiante...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41700 0 0]Esse e o comeco[n]da era de Shido-san![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41503 0 0]Masayoshi shido e um virtuoso[n]homem com principio. Ele e o que[n]Todo politico deveria ser.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40954 0 0]Shido-san e realmente[n]um grande representante.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40304 0 0]Shido representativo e[n]diferente. Ele e apenas melhor[n]do que todos os outros, nao e?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39850 0 0]Sempre que Shido fala, seu[n]palavras... eles apenas tem isso[n]gravitas que ninguem mais tem.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40600 0 0]Representante Shido parece um[n]um pouco assustador, mas acho que ele e[n]Muito bonito de perto![n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41957 0 0]Eu pensei aquele ladrao fantasma[n]Era para estar morto...[n]Que diabos esta acontecendo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46405 0 0]Tenho certeza que Shido-san esta certo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43402 0 0]Depois de tudo isso aconteceu,[n]Eu simplesmente nao confio naqueles[n]Phantom Thieves...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39804 0 0]Quem esta certo? E[n]e aqueles ladroes fantasmas[n]ou shido?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43605 0 0]Eu nao confio em shido ou[n]Aqueles ladroes fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44055 0 0]Nossa, que se importa com o[n]Mais ladroes fantasmas?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39755 0 0]Shido disse que nao era verdade, entao[n]Quaisquer que sejam aqueles ladroes fantasmas[n]disse que todos devem ser mentiras...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43705 0 0]Eu nem me importo quem e[n]certo ou errado mais...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44505 0 0]Nao tem jeito[n]Shido-san esta errado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37555 0 0]Eu nao acredito nisso.[n]Aquele ladrao fantasma[n]esta realmente vivo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45505 0 0]Bem, Shido disse que tudo[n]essas coisas nao eram verdadeiras, entao[n]Nao vamos nos preocupar com isso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40455 0 0]Phantom Thieves de novo?[n]As pessoas ja nao estao alem disso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40552 0 0]Como isso pode acontecer...?[n]O que nos vamos fazer?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40802 0 0]Shido-san nao esta se sentindo bem?[n]Oh nao, ele vai ficar bem?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43401 0 0]Eu confiei nele...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43552 0 0]Eu pensei tudo[n]Seria bom se nos[n]Deixou coisas para Shido...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43610 0 0]Eu deveria ter nunca[n]Confiavel Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45352 0 0]Eu nao posso acreditar nisso...[n]Todos os seus discursos eram apenas mentiras?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42851 0 0]Shido venceu a eleicao, entao ele[n]Nao renunciaria agora, seria?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44952 0 0]Por que isso aconteceu?[n]Nos apoiamos e apoiamos[n]muito ele, mas agora...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38552 0 0]O Japao nao pode se tornar[n]forte sem shido-san.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42302 0 0]Isso tem que ser uma piada.[n]O que nos vamos fazer[n]Sem Shido para nos liderar!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39859 0 0]Shido-san... Por que? Voce[n]estavam... voce estava indo[n]mudar a sociedade![n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45452 0 0]E o representante shido[n]vai ficar bem?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46252 0 0]Esta tudo acabado...[n]Alguem tem que[n]faca alguma coisa...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44555 0 0]Nao ha nada que possamos fazer.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43502 0 0]Este pais esta condenado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41910 0 0]Por que isso esta acontecendo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43602 0 0]Nao importa o que[n]nos fazemos mais...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45360 0 0]Eu me sinto sobrecarregado...[n]esmagando o desespero...[n]Ajude-me...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46252 0 0]Esta tudo acabado...[n]Alguem tem que[n]faca alguma coisa...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43055 0 0]Nada vai[n]mudar de qualquer maneira.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45902 0 0]O que eu vou fazer?[n]Alguem me ajude...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40355 0 0]Faca o que fizer, e[n]Tudo inutil, de qualquer maneira...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38460 0 0]Alguem conserta este mundo.[n]Nao importa quem[n]faz isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40202 0 0]Alguem nos ajude...[n]Qualquer pessoa fara, eu nao me importo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38804 0 0]Ei, o que e um bom presente para[n]comemorar alguem recebendo[n]aceito na escola?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42011 0 0]Apenas mais dois contratos,[n]E tudo vai acabar![n]Voce consegue![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43705 0 0]Ela nao esta estudando em um[n]campo diferente? Eu nunca[n]vi-a por ai antes.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39253 0 0]HM? Claro meu[n]O namorado tem um emprego![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42150 0 0]Ooh, a new caf...[n]Espere o que? Isso e[n]sempre esteve la?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41755 0 0]Voce e o responsavel?[n]O que quer que... voce se importa?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43402 0 0]Nao, nao, nao e nada[n]Curtiu isso. Eu sou apenas um[n]funcionario regular...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43202 0 0]Trabalhar em uma anfitria[n]clube? Uh, nao, obrigado.[n]Eu tenho um emprego regular...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44058 0 0]Festa hoje, festa[n]amanha! Manter[n]as bebidas chegando![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42400 0 0]Eu posso nao ser o numero um...[n]Mas todos os meus regulares[n]sao legais, entao estou satisfeito.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40505 0 0]Eu parei de ser um anfitriao.[n]Eu tenho que me concentrar em[n]Faculdade de Graduacao.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40000 0 0]Toquio e um otimo lugar.[n]Estou tao feliz por me mudar para ca![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_13_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40151 0 0]Tenho certeza que este foi o[n]lugar eu a vi... hein?[n]Nao, eu nao estava bebado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_14_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39750 0 0]Vou dirigir voce. Nao se preocupe![n]Eu nao tenho nenhum acidente[n]ou violacoes no meu registro.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_15_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41352 0 0]Se minha filha esta feliz,[n]Eu nao me importo... mas o que[n]tipo de homem e o namorado dela?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_16_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38350 0 0]Isso e tao fofo! E legal[n]que tudo parece[n]bem em voce.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_17_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38202 0 0]Hmm... eu realmente nao gosto[n]A atmosfera em clubes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_18_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42350 0 0]Estou tao feliz por ter nascido[n]Neste mundo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_19_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42151 0 0]Voce seriamente deu o seu[n]novo hamster o mesmo[n]nome como seu ultimo!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_20_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40503 0 0]Voce se importa se eu cair[n]pela pos-festa?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_21_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38802 0 0]Sim, eu tambem tenho musculos[n]dor. Eu festei um pouco[n]Muito dificil para a minha idade.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_22_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43600 0 0]A senhora no bar certa[n]e popular. Estou feliz que ela[n]Nao precisava fechar a loja.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_23_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43905 0 0]Eu nunca teria[n]um caso! Eu entraria entao[n]Muito problema![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_24_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43952 0 0]Huh? Nao estava em algum lugar[n]por aqui...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_25_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40002 0 0]O que devo fazer sobre[n]minha busca de emprego? eu gosto de[n]trabalho de meio periodo que tenho agora.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_01_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_032_02_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_032_03_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_032_04_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_032_05_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_032_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40505 0 0]Voce sabe, reclamando[n]nao vai te levar a lugar nenhum.[n][f 1 2 90][e]

[msg MSG_GRT_main_All_032_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37552 0 0]Ja e primavera...[n][f 1 2 90][e]

[msg MSG_GRT_main_All_032_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40850 0 0]Eu gosto muito dessa epoca do ano.[n][f 1 2 90][e]

[msg MSG_GRT_main_All_032_09_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_032_10_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_032_11_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_033_01_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_033_02_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_033_03_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_033_04_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_033_05_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_033_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43405 0 0]Tudo e tao chato...[n][f 1 2 90][e]

[msg MSG_GRT_main_All_033_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42659 0 0]Por que e sempre eu...?[n][f 1 2 90][e]

[msg MSG_GRT_main_All_033_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 41405 0 0]Entao, nada esta indo[n]Afinal, mudar.[n][f 1 2 90][e]

[msg MSG_GRT_main_All_033_09_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_033_10_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_All_033_11_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 90][e]

[msg MSG_GRT_main_Lim_104_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40905 0 0]Ja e hora[n]Para fogos de artificio, hein...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45450 0 0]Eu ouvi dizer que esta indo[n]ser fogos de artificio.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46300 0 0]Eu nao me importo com fogos de artificio,[n]Mas estou ansioso para[n]Vendo todos em Yukata![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45255 0 0]Eu nao tenho tempo para[n]Assistindo os fogos de artificio...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 45569 0 0]Estou muito velho para estar[n]Vou ver fogos de artificio...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_01_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40902 0 0]Nao importa o quao mau ele[n]eles nao tinham[n]para mata-lo...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46402 0 0]Aquela conferencia de imprensa[n]estava tao traumatizante...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_12_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 43401 0 0]Os ladroes Phantom sao[n]Seguindo-se![n]Eles sao os piores![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_03_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40352 0 0]Eles vao tao longe quanto[n]cometendo assassinato...?[n]Eles sao loucos...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 37701 0 0]Eles sao lunaticos.[n]Eles realmente o mataram durante[n]uma conferencia de desculpas publica...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_05_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44051 0 0]Mata-lo nao foi o seu trabalho![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_06_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 44602 0 0]O que aconteceu com[n]Okumura estava muito doente...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 39802 0 0]Aquelas filmagens de Okumura[n]A conferencia de imprensa nao foi[n]Acabei de editar, foi...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_08_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46202 0 0]Eles o mataram na frente de[n]um publico ao vivo. Eles nao[n]ate mudar seu coracao...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_09_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38502 0 0]Como eles poderiam fazer algo assim[n]brutal e cruel, bem no[n]meio de sua conferencia de desculpas?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_10_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 42051 0 0]Mata-lo nao[n]faz algum sentido![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38602 0 0]Aquela coisa que aconteceu[n]ao presidente Okumura[n]era definitivamente estranho...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_01_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_02_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40804 0 0]O que Akechi tem dito[n]Na verdade, faz sentido.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_03_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_04_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 38604 0 0]Seria muito estranho se[n]Eles poderiam controlar sua mente...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_05_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_06_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_07_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 40302 0 0]Eles so tem como alvo pessoas mas agora,[n]Mas eles nao respondem a ninguem,[n]certo? Eles foram desonestos...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_08_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_09_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_10_ [Dream-Chasing Girl]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_11_ [Dream-Chasing Girl]]
[s][vp 9 2 65535 46204 0 0]Entao espere, quem esta certo?[n]Akechi-kun ou o[n]Phantom Thieves?[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_AME_ [Dream-Chasing Girl]]
[s][vp 8 2 65535 36951 0 0]A chuva ainda nao vai parar...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_AME__2 [Dream-Chasing Girl]]
[s][vp 8 2 65535 37002 0 0]A chuva realmente me derruba.[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_YUKI [Dream-Chasing Girl]]
[s][vp 8 2 65535 36985 0 0]Neve nesta epoca do ano?[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_YUKI_2 [Dream-Chasing Girl]]
[s][vp 8 2 65535 37035 0 0]Esta nevando? Acho[n]E melhor eu usar um casaco.[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_TSUY [Dream-Chasing Girl]]
[s][vp 8 2 65535 36955 0 0]Eu me pergunto quanto tempo isso[n]O tempo vai continuar...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_TSUY_2 [Dream-Chasing Girl]]
[s][vp 8 2 65535 37006 0 0]Ugh, eu nao suporto[n]a estacao chuvosa.[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_TYPH [Dream-Chasing Girl]]
[s][vp 8 2 65535 36971 0 0]Um tufao, hein...[n]Talvez eu chame um taxi.[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_TYPH_2 [Dream-Chasing Girl]]
[s][vp 8 2 65535 37016 0 0]Cara, esse vento e forte.[n]Esta chuva tambem e muito pesada![n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_KAHU [Dream-Chasing Girl]]
[s][vp 8 2 65535 36973 0 0]Sendo alergico a[n]O polen e uma merda...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_KAHU_2 [Dream-Chasing Girl]]
[s][vp 8 2 65535 37022 0 0]Meus olhos estao tao aquosos[n]Por causa de todo esse polen...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_GERI [Dream-Chasing Girl]]
[s][vp 8 2 65535 36961 0 0]Uau, esta realmente descendo![n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_GERI_2 [Dream-Chasing Girl]]
[s][vp 8 2 65535 37013 0 0]Essa chuva realmente[n]veio do nada.[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_HEAT [Dream-Chasing Girl]]
[s][vp 8 2 65535 36981 0 0]Pode ser verao, mas[n]Tem que haver um limite[n]Para este calor...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_HEAT_2 [Dream-Chasing Girl]]
[s][vp 8 2 65535 37034 0 0]Esta tao quente... eu sinto[n]Como se eu fosse colapso...[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_VIRU [Dream-Chasing Girl]]
[s][vp 8 2 65535 36979 0 0]Vai ser tao aborrecido[n]Se eu pegar a gripe.[n][f 1 2 180][e]

[msg MSG_GRT_SCH_WEATHER_VIRU_2 [Dream-Chasing Girl]]
[s][vp 8 2 65535 37027 0 0]Oh cara...[n]E melhor eu nao ter gripe...[n][f 1 2 180][e]

[msg MSG_TAXIUNTENSYU_001_0_0 [Taxi Driver]]
[s][f 4 23 1 17 3 10 0 10][vp 8 2 1 0 17 0]Eu tenho buscado menos e[n]Menos tarifas. Voce sabe de alguma forma[n]Eu poderia ganhar mais dinheiro?[n][w][e]

[msg MSG_TAXIUNTENSYU_001_1_0 [Bespectacled Taxi Driver]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Bem, eu ouco aqueles bandidos em Shibuya[n]ganhar muito dinheiro, e eles[n]festa la como louca.[n][w][e]

[msg MSG_TAXIUNTENSYU_001_2_0 [Taxi Driver]]
[s][f 4 23 1 17 3 10 0 10][vp 8 2 1 0 17 0]Sim, mas Shibuya esta ficando obscura.[n]E tudo por causa de algum novo crime[n]organizacao ou algo assim.[n][w][e]
[s][vp 8 2 1 0 17 0]Talvez o dinheiro deles seja bom, mas eu[n]Nao quero ser pego em[n]Qualquer problema com esses caras.[n][w][e]

[msg MSG_TAXIUNTENSYU_002_0_0 [Bespectacled Taxi Driver]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Eu estava estacionando meu carro em shibuya[n]outro dia, e encontrei um estranho[n]pedaco de papel preso a ele.[n][w][e]
[s][vp 8 2 1 0 18 0]Ele disse que era um "cartao de visita". Voce[n]Acha que e um anuncio para alguma coisa?[n][w][e]

[msg MSG_TAXIUNTENSYU_002_1_0 [Taxi Driver]]
[s][f 4 23 1 17 3 10 0 10][vp 8 2 1 0 17 0]Oh, eu tenho ouvido esses sao[n]uma mensagem para o chefe de honra[n]daqueles bandidos em Shibuya.[n][w][e]
[s][vp 8 2 1 0 17 0]Os caras enviando os cartoes de chamada[n]tem estado ocupados. Talvez eles tenham[n]em uma briga com Yakuza.[n][w][e]

[msg MSG_TAXIUNTENSYU_003_0_0 [Bespectacled Taxi Driver]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Os bandidos em Shibuya se foram, principalmente,[n]Entao talvez eu espere por ai para escolher[n]ate algumas tarifas.[n][w][e]

[msg MSG_TAXIUNTENSYU_003_1_0 [Taxi Driver]]
[s][f 4 23 1 17 3 10 0 10][vp 8 2 1 0 17 0]Aqueles "ladroes fantasmas" se livraram do[n]bandidos, certo? O que eles supoem[n]Para ser, super-herois?[n][w][e]

[msg MSG_TAXIUNTENSYU_003_2_0 [Bespectacled Taxi Driver]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Uma das minhas tarifas, ele era bonito[n]jovem, disse que sao mais[n]confiavel que a policia.[n][w][e]

[msg MSG_TAXIUNTENSYU_003_3_0 [Taxi Driver]]
[s][f 4 23 1 17 3 10 0 10][vp 8 2 1 0 17 0]Hahaha, talvez. E embaracoso para[n]a policia, tendo alguem fazendo seu[n]trabalho para eles.[n][w][e]

[msg MSG_TAXIUNTENSYU_004_0_0 [Taxi Driver]]
[s][f 4 23 1 17 3 10 0 10][vp 8 2 1 0 17 0]Voce ouve sobre mej... alguma coisa? Um[n]das minhas tarifas perguntaram sobre isso, mas eu nao[n]sabe alguma coisa.[n][w][e]

[msg MSG_TAXIUNTENSYU_004_1_0 [Bespectacled Taxi Driver]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Oh, medjed? Eles sao um grupo de hackers[n]conhecido em todo o mundo. Eles causaram[n]problema antes.[n][w][e]
[s][vp 8 2 1 0 18 0]Eles tem como alvo orificios de seguranca em servidores e[n]Extrair informacoes acessando sites[n]ilegalmente...[n][w][e]

[msg MSG_TAXIUNTENSYU_004_2_0 [Taxi Driver]]
[s][f 4 23 1 17 3 10 0 10][vp 8 2 1 0 17 0]Eu realmente nao entendo, mas eles sao basicamente[n]Usoads, certo? "Julgamento da justica".[n]minha bunda.[n][w][e]

[msg MSG_TAXIUNTENSYU_009_0_0 [Taxi Driver]]
[s][f 4 23 1 17 3 10 0 10][vp 8 2 1 0 17 0]Isso foi uma coisa tao terrivel para[n]pessoas para ver. Eu me sinto muito mal[n]Para esse presidente.[n][w][e]

[msg MSG_TAXIUNTENSYU_009_1_0 [Bespectacled Taxi Driver]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Muitas das minhas tarifas eram bonitas[n]zangado hoje. Eles se sentem traidos por[n]os ladroes fantasmas.[n][w][e]

[msg MSG_TAXIUNTENSYU_009_2_0 [Taxi Driver]]
[s][f 4 23 1 17 3 10 0 10][vp 8 2 1 0 17 0]Quais sao a policia e o governo[n]fazendo? Esses caras precisam ser presos,[n]ASSIM QUE POSSIVEL.[n][w][e]

[msg MSG_TAXIUNTENSYU_009_3_0 [Bespectacled Taxi Driver]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Eu ouvi Kasumigaseki esta bastante agitado[n]com os superiores deste pais[n]lutando para lidar com esse problema.[n][w][e]

[msg MSG_TAXIUNTENSYU_010_0_0 [Taxi Driver]]
[s][f 4 23 1 17 3 10 0 10][vp 8 2 1 0 17 0]Uma recompensa de 30 milhoes de ienes, hein?[n]Talvez devessemos deixar nossos empregos[n]Para encontrar os ladroes fantasmas.[n][w][e]

[msg MSG_TAXIUNTENSYU_010_1_0 [Bespectacled Taxi Driver]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]De jeito nenhum, apenas seriamos mortos. o[n]A policia pode lidar com isso, entao vamos sair[n]isso para os profissionais.[n][w][e]

[msg MSG_TAXIUNTENSYU_010_2_0 [Taxi Driver]]
[s][f 4 23 1 17 3 10 0 10][vp 8 2 1 0 17 0]Ei, podemos pegar mais tarifas[n]perto daquelas agencias governamentais[n]Se eles vao ficar ocupados.[n][w][e]
[s][vp 8 2 1 0 17 0]Mas nao tenho certeza se eles podem pegar[n]Aqueles ladroes fantasmas. Eles podem[n]Basta fazer voce ficar com o cerebro, facil.[n][w][e]

[msg MSG_TAXIUNTENSYU_013_0_0 [Bespectacled Taxi Driver]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Eu ouvi dizer que o representante Shido foi[n]hospitalizado. Eu realmente me pergunto quando[n]Escolheremos um novo primeiro-ministro.[n][w][e]

[msg MSG_TAXIUNTENSYU_013_1_0 [Taxi Driver]]
[s][f 4 23 1 17 3 10 0 10][vp 8 2 1 0 17 0]Todas as minhas tarifas estao falando sobre isso.[n]Todos eles dizem que vai acabar com o mesmo[n]Nao importa quem faz o trabalho.[n][w][e]
[s][vp 8 2 1 0 17 0]Eu acho que este ano vai acabar[n]sem muito fechamento. Nada e[n]mudou, se voce pensar sobre isso.[n][w][e]

[msg quest16_hint_talk_00_00 [Worried Office Worker]]
[s][f 4 23 1 603 3 10 0 10][vp 8 2 1 0 603 0]Por favor, meu amigo precisa de ajuda. Nao esta la[n]Algo que voce pode fazer?[n][w][e]
[s][vp 8 2 1 0 603 0]Ele esta ate emprestando dinheiro do mal[n]credores, alegando que seu salario nao e suficiente[n]Para pagar as datas...[n][w][e]

[msg quest16_hint_talk_00_01 [Frustrated Office Worker]]
[s][f 4 23 1 602 3 10 0 10][vp 8 2 1 0 602 0]Olha, nao e tao simples. Ele esta perseguindo[n]Depois de Tomoko Kamata, certo?[n][w][e]
[s][vp 8 2 1 0 602 0]Ela parece agradavel na superficie, mas[n]No fundo, ela e um monstro pegajoso.[n][w][e]
[s][vp 8 2 1 0 602 0]Por que nao perguntar aos ladroes Phantom[n]ajuda? Se eles fizerem isso, nao precisamos[n]Preocupe-se com qualquer blowback.[n][w][e]

[msg quest16_hint_sinjyo_00]
[s][vp 8 2 65535 0 0 0]Parece que eles precisam de ajuda...[n][w][e]

[msg MSG_quest16_morgana_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Se cuidarmos dessa meta, faremos[n]Um nome para nos mesmos![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Vamos encontrar essa mulher![n][w][e]

[msg quest16_hint_talk_01_00 [Worried Office Worker]]
[s][f 4 23 1 603 3 10 0 10][vp 8 2 1 0 603 0]Os ladroes fantasmas fizeram isso! Aparentemente,[n]Kamata-san foi implorando por seu[n]perdao![n][w][e]

[msg quest16_hint_talk_01_01 [Frustrated Office Worker]]
[s][f 4 23 1 602 3 10 0 10][vp 8 2 1 0 602 0]Eu nao posso acreditar que voce realmente perguntou o[n]Phantom Thieves para obter ajuda. Ou aquilo[n]Eles fizeram algo sobre isso![n][w][e]

[msg quest16_hint_talk_01_02 [Worried Office Worker]]
[s][f 4 23 1 603 3 10 0 10][vp 8 2 1 0 603 0]Huh? Eu pensei que voce pediu ajuda a eles.[n][w][e]

[msg quest16_hint_talk_01_03 [Frustrated Office Worker]]
[s][f 4 23 1 602 3 10 0 10][vp 8 2 1 0 602 0]O que? Por que eu faria meu pescoco[n]por cima disto?[n][w][e]
[s][vp 8 2 1 0 602 0]Espere, isso significa... o fantasma[n]Ladroes ajudaram por conta propria?[n][w][e]

[msg quest16_hint_talk_01_04 [Worried Office Worker]]
[s][f 4 23 1 603 3 10 0 10][vp 8 2 1 0 603 0]Eu... acho que sim. Eles sao realmente[n]algo mais.[n][w][e]

[msg quest16_hint_sinjyo_01]
[s][vp 8 2 65535 0 0 0]Parece ladroes fantasmas[n]A aprovacao esta em ascensao.[n][w][e]

[msg Quest16_target_00_00 [Tomoko Kamata]]
[s][f 4 23 1 602 3 10 0 10][vp 8 2 1 0 602 0]Ei, podemos ir para aquele restaurante frances[n]Vimos na TV? Eu quero experimentar.[n][w][e]

[msg Quest16_target_00_01 [Exhausted Boyfriend]]
[s][f 4 23 1 603 3 10 0 10][vp 8 2 1 0 603 0]Desculpe, o dinheiro esta apertado agora ate[n]dia do pagamento. Que tal um restaurante?[n][w][e]

[msg Quest16_target_00_02 [Tomoko Kamata]]
[s][f 4 23 1 602 3 10 0 10][vp 8 2 1 0 602 0]Voce esta seriamente sugerindo me levar[n]Em uma data para um restaurante?[n][w][e]
[s][vp 8 2 1 0 602 0]Eu comprei roupas novas e peguei minhas unhas[n]Feito so para voce, Ma-kun! Voce e um idiota![n][w][e]

[msg Quest16_target_00_03 [Exhausted Boyfriend]]
[s][f 4 23 1 603 3 10 0 10][vp 8 2 1 0 603 0]Bem, ok... que tal irmos holandeses?[n][w][e]

[msg Quest16_target_00_04 [Tomoko Kamata]]
[s][f 4 23 1 602 3 10 0 10][vp 8 2 1 0 602 0]Voce e inacreditavel. Um namorado deveria[n]ser capaz de cobrir o jantar.[n][w][e]
[s][vp 8 2 1 0 602 0]Eu sou uma mulher  voce deveria levar[n]Eu saiu e me trate certo.[n][w][e]

[msg Quest16_target_00_05 [Exhausted Boyfriend]]
[s][vp 8 2 65535 0 0 0]......[n][w][e]

[msg Quest16_target_00_06 [Tomoko Kamata]]
[s][f 4 23 1 602 3 10 0 10][vp 8 2 1 0 602 0]Olha, me desculpe... eu nao queria ser[n]uma dor.[n][w][e]
[s][vp 8 2 1 0 602 0]E que eu realmente gosto de voce. Eu acho[n]Eu sou uma garota ruim, ma, hein?[n][w][e]

[msg Quest16_target_00_07 [Exhausted Boyfriend]]
[s][f 4 23 1 603 3 10 0 10][vp 8 2 1 0 603 0]Oh, nao  Sinto muito. Nao fique chateado.[n]Vou leva-lo para aquele restaurante.[n][w][e]

[msg Quest16_target_00_08 [Tomoko Kamata]]
[s][f 4 23 1 602 3 10 0 10][vp 8 2 1 0 602 0]Serio? Eu estou tao feliz! Voce e um[n]Cara legal, Ma-kun.[n][w][e]

[msg Quest16_target_sinjyo_00]
[s][vp 8 2 65535 0 0 0]Olhe para aquelas lagrimas de crocodilo...[n][w][e]

[msg MSG_quest16_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Uau, aqueles niveis de rainha do drama sao[n]fora dos graficos! Eu acho que temos o nosso[n]proximo alvo.[n][w][e]

[msg Quest16_target_01_00 [Tomoko Kamata]]
[s][f 4 23 1 602 3 10 0 10][vp 8 2 1 0 602 0]Vamos passar por algumas lojas depois do jantar.[n]Ha um colar que eu realmente quero conseguir...[n][w][e]

[msg Quest16_target_01_01 [Exhausted Boyfriend]]
[s][f 4 23 1 603 3 10 0 10][vp 8 2 1 0 603 0]Huh? O jantar nao e suficiente?[n][w][e]

[msg Quest16_target_01_02 [Tomoko Kamata]]
[s][f 4 23 1 602 3 10 0 10][vp 8 2 1 0 602 0]O que posso dizer, meninas querem legal[n]Coisas  E nos obtemos o que queremos.[n][w][e]

[msg Quest16_target_01_03 [Exhausted Boyfriend]]
[s][vp 8 2 65535 0 0 0]......[n][w][e]

[msg Quest16_target_sinjyo_01]
[s][vp 8 2 65535 0 0 0]Em que ano essa mulher[n]acho que e? Esperando o[n]cara para pagar o seu caminho...[n][w][e]

[msg Quest16_target_02_00 [Tomoko Kamata]]
[s][f 4 23 1 602 3 10 0 10][vp 8 2 1 0 602 0]Ma-kun, qual e o problema com isso[n]Carta estranha?[n][w][e]

[msg Quest16_target_02_01 [Exhausted Boyfriend]]
[s][f 4 23 1 603 3 10 0 10][vp 8 2 1 0 603 0]Huh? Que carta estranha? eu estive[n]Com voce todo esse tempo...[n][w][e]

[msg Quest16_target_02_02 [Tomoko Kamata]]
[s][f 4 23 1 602 3 10 0 10][vp 8 2 1 0 602 0]Nao jogue idiota. Eu nao pensei que voce fosse[n]capaz de algo isso significa...[n][w][e]

[msg Quest16_target_02_03 [Exhausted Boyfriend]]
[s][f 4 23 1 603 3 10 0 10][vp 8 2 65535 0 0 0]......[n][w][e]

[msg Quest16_target_sinjyo_02]
[s][vp 8 2 65535 0 0 0]Isso nao esta indo bem. Deveriamos[n]embrulhe o mais rapido possivel.[n][w][e]

[msg Quest40_target_00_00 [Ryota Tennou]]
[s][f 4 23 1 605 3 10 0 10][vp 8 2 1 0 605 0]Ve algo que voce quiser, Miki-chan?[n]Esta em mim.[n][w][e]

[msg Quest40_target_00_01 [Miki-chan]]
[s][f 4 23 1 604 3 10 0 10][vp 8 2 1 0 604 0]Voce tem certeza, Tennou-san? Voce comprou um[n]bolsa para mayu outro dia.[n][w][e]
[s][vp 8 2 1 0 604 0]Voce nao e casado? O que voce faz[n]esposa pensa nisso tudo?[n][w][e]

[msg Quest40_target_00_02 [Ryota Tennou]]
[s][f 4 23 1 605 3 10 0 10][vp 8 2 1 0 605 0]Nao se preocupe com ela. eu sou o escolhido[n]quem ganha todo o dinheiro  ela nao pode[n]Diga-me como gasta-lo.[n][w][e]
[s][vp 8 2 1 0 605 0]Alem disso, se eu tenho o dinheiro, por que nao deveria[n]Gase em uma mulher bonita como voce?[n][w][e]

[msg Quest40_target_00_03 [Miki-chan]]
[s][f 4 23 1 604 3 10 0 10][vp 8 2 1 0 604 0]O que voce faz para viver, Tennou-san?[n][w][e]

[msg Quest40_target_00_04 [Ryota Tennou]]
[s][f 4 23 1 605 3 10 0 10][vp 8 2 1 0 605 0]Eu sou um contador. Em outras palavras, e[n]Minha mao que segura a carteira da empresa.[n][w][e]
[s][vp 8 2 1 0 605 0]Apenas entre nos, as empresas nao pagam[n]quase tanta atencao ao seu dinheiro[n]como eles deveriam.[n][w][e]

[msg Quest40_target_00_05 [Miki-chan]]
[s][f 4 23 1 604 3 10 0 10][vp 8 2 1 0 604 0]Oh? Huh.[n][w][e]

[msg MSG_quest40_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Este deve ser o cara que ouvimos falar.[n]Vamos voltar para o esconderijo e[n]Descubra um plano![n][w][e]

[msg Quest40_target_01_00 [Ryota Tennou]]
[s][f 4 23 1 605 3 10 0 10][vp 8 2 1 0 605 0]Diabos e isso? Um cartao de chamada?[n][w][e]
[s][vp 8 2 1 0 605 0]A empresa descobriu sobre o[n]peculato? Nao, nao  estou sendo[n]paranoico. Isso e apenas uma brincadeira.[n][w][e]

[msg Quest40_target_01_01 [Miki-chan]]
[s][f 4 23 1 604 3 10 0 10][vp 8 2 1 0 604 0]Qual e o problema? Algo errado?[n][w][e]

[msg Quest40_target_01_02 [Ryota Tennou]]
[s][f 4 23 1 605 3 10 0 10][vp 8 2 1 0 605 0]Nao, apenas uma brincadeira. Ha.[n][w][e]
[s][vp 8 2 1 0 605 0]Vamos ter um bom dia.[n][w][e]

[msg Quest40_target_sinjyo_01]
[s][vp 8 2 65535 0 0 0]Parece o cartao de visita[n]foi entregue com seguranca...[n][w][e]

[msg Quest40_target_02_00 [Ryota Tennou]]
[s][f 4 23 1 605 3 10 0 10][vp 8 2 1 0 605 0]Eu sinto muito. Eu o coloquei tanto,[n]Tomei voce como certo...[n][w][e]

[msg Quest40_target_02_01 [Long-Haired Woman]]
[s][f 4 23 1 604 3 10 0 10][vp 8 2 1 0 604 0]Que bom que voce entende.[n][w][e]
[s][vp 8 2 1 0 604 0]Sim, bem... eu deveria ter falado[n]para mim mais cedo.[n][w][e]

[msg Quest40_target_02_02 [Ryota Tennou]]
[s][f 4 23 1 605 3 10 0 10][vp 8 2 1 0 605 0]Nao, nao... isso e tudo culpa minha. Voce nao deveria[n]omitir qualquer culpa.[n][w][e]
[s][vp 8 2 1 0 605 0]Eu me senti tao inutil por tanto tempo, nao pude[n]ajuda, mas use o dinheiro como uma distracao de[n]minha infelicidade.[n][w][e]
[s][vp 8 2 1 0 605 0]Devemos nos divorciar. Voce nao[n]merece ter seu nome manchado[n]sobre meus erros.[n][w][e]

[msg Quest40_target_02_03 [Long-Haired Woman]]
[s][f 4 23 1 604 3 10 0 10][vp 8 2 1 0 604 0]Ryota... sim. Eu entendo.[n][w][e]
[s][vp 8 2 1 0 604 0]Voce nao e todo ruim, voce sabe.[n]Voce tem uma alma gentil  e por que[n]Eu me apaixonei por voce.[n][w][e]

[msg Quest40_target_sinjyo_02]
[s][vp 8 2 65535 0 0 0]Parece que a mudanca de coracao funcionou.[n][w][e]

[msg Quest45_target_00_00 [ターゲット45]]
[s]クエスト45のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗は受注可能状態です。[n][w][e]

[msg Quest45_target_sinjyo_00]
[s]クエスト45のテスト心情メッセージです。[n][w][e]

[msg MSG_quest45_morgana_01 [Morgana]]
[s]クエスト45のモルガナメッセージです。[n]ターゲット用です。[n][w][e]

[msg Quest45_target_01_00 [ターゲット45]]
[s]クエスト45のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗はメメントス突入可能状態です。[n][w][e]

[msg Quest45_target_sinjyo_01]
[s]クエスト45のテスト心情メッセージです。[n][w][e]

[msg Quest45_target_02_00 [ターゲット45]]
[s]クエスト45のテストメッセージです。[n]表示後、キャンプでの状態を確認して下さい。[n][w][e]
[s]クエストの進捗はミッションクリア状態です。[n][w][e]

[msg Quest45_target_sinjyo_02]
[s]クエスト45のテスト心情メッセージです。[n][w][e]

[msg quest52_hint_talk_00_00 [Gossip-Loving Woman]]
[s][vp 8 2 1 0 600 0]Ei, voce viu aquela mulher? Isso e[n]O que eu estava falando sobre voce.[n][w][e]

[msg quest52_hint_talk_00_01 [Enthralled Woman]]
[s][vp 8 2 1 0 601 0]Aquele que sempre tem a fortuna dela[n]ler?[n][w][e]
[s][vp 8 2 1 0 601 0]Esses hematomas parecem novos... eu realmente desejo[n]Ela ja terminaria com esse cara.[n][w][e]

[msg quest52_hint_talk_00_02 [Gossip-Loving Woman]]
[s][vp 8 2 1 0 600 0]Sim, nao ha nada pior do que um[n]namorado abusivo.[n][w][e]

[msg quest52_hint_talk_00_03a [Gossip-Loving Woman]]
[s][vp 8 2 1 0 601 0]Com licenca, voce esta nos escutando?[n][w][e]
[s][vp 8 2 1 0 601 0]Bem, voce e bem fofo. Acho que posso[n]Deixe ir  apenas uma vez.[n][w][e]

[msg quest52_hint_talk_00_03b [Gossip-Loving Woman]]
[s][vp 8 2 1 0 600 0]Com licenca, voce esta nos escutando?[n][w][e]
[s][vp 8 2 1 0 600 0]Eu conheco o seu tipo. Tranquilo. Arrepiante.[n][w][e]
[s][vp 8 2 1 0 600 0]Inacreditavel. E melhor voce nao estar[n]esgueirando fotos de nos.[n][w][e]

[msg quest52_hint_sinjyo_00a]
[s][vp 8 2 65535 0 0 0]Parece todo o[f 4 11 1][clr 26]Charme[clr 27]Eu exalo[n]Me faz parecer mais acessivel![n][w][e]

[msg quest52_hint_sinjyo_00b]
[s][vp 8 2 65535 0 0 0]Ela esta realmente rasgando em mim...[n][w][e]
[s][vp 8 2 65535 0 0 0]Talvez ela seja apenas superficial.[n][w][e]
[s][vp 8 2 65535 0 0 0]Talvez ela me desse[n]a hora do dia se eu tivesse[n]Virando da cabeca[f 4 11 1][clr 26]Charme[clr 27].[n][w][e]

[msg quest52_hint_talk_00_04 [Enthralled Woman]]
[s][vp 8 2 1 0 601 0]Ei, eu vi aquela mulher que voce estava dizendo[n]eu sobre novamente. Ela estava carregando isso[n]rocha estranha.[n][w][e]

[msg quest52_hint_talk_00_05 [Gossip-Loving Woman]]
[s][vp 8 2 1 0 600 0]Oh, voce quer dizer uma rocha de sorte? Eu me pergunto onde[n]Ela consegue isso.[n][w][e]

[msg quest52_hint_talk_00_06 [Enthralled Woman]]
[s][vp 8 2 1 0 601 0]O namorado dela continua jogando-os[n]longe, mas ela continua ficando mais.[n][w][e]

[msg quest52_hint_talk_STONE_ [Gossip-Loving Woman]]
[s][vp 8 2 1 0 600 0]Huh. E como a rocha que voce tem.[n][w][e]

[msg quest52_hint_talk_STONE__2 [Enthralled Woman]]
[s][vp 8 2 1 0 601 0]Sim, o mesmo, eu acho.[n][w][e]

[msg quest52_hint_talk_00_07 [Gossip-Loving Woman]]
[s][vp 8 2 1 0 600 0]Bem, de qualquer maneira, aquele idiota que ela liga[n]um namorado  uh...[n][w][e]
[s][vp 8 2 1 0 600 0]... Qual e o nome dele de novo?[n][w][e]

[msg quest52_hint_talk_00_08 [Enthralled Woman]]
[s][vp 8 2 1 0 601 0]Oh, Deus  Nao me lembro.[n][w][e]

[msg quest52_hint_talk_00_09 [Gossip-Loving Woman]]
[s][vp 8 2 1 0 600 0]Esta bem na ponta da minha lingua...[n]Bem, quem se importa?[n][w][e]

[msg MSG_quest52_morgana_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Alguns chauvinistas masculinos obsoletos[n]atacando sua namorada, hein?[n]Parece um novo alvo para mim![n][w][e]
[s][vp 8 2 65535 0 0 0]......[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]... hm?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Uh, eu preciso do nome do cara ou nao posso[n]Pesquise lembrancas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Tudo o que temos que continuar e aquele namorado[n]da metade melhor do ano mantem um estranho[n]Rock com ela.[n][w][e]

[msg MSG_quest52_morgana_00_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]... hm?[n][w][e]

[msg MSG_quest52_morgana_00_0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Parece que alguem foi ver Mifune.[n]Quer ver o que esta acontecendo?[n][w][e]

[msg MSG_quest52_morgana_STON [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Alguns chauvinistas masculinos obsoletos[n]atacando sua namorada, hein?[n]Parece um novo alvo para mim![n][w][e]
[s][vp 8 2 65535 0 0 0]......[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]... hm?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Uh, eu preciso do nome do cara ou nao posso[n]Pesquise lembrancas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Ei, aquela rocha  O Melhor Namorado[n]O Bonnie Lass de Ever nao era um santo[n]Pedra?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Vamos balancar na loja de Mifune.[n][w][e]

[msg quest52_hint_talk_01_00 [Gossip-Loving Woman]]
[s][vp 8 2 1 0 600 0]Espero que a mulher esteja bem. Ninguem[n]deveria ter que lidar com um violento,[n]namorado abusivo.[n][w][e]

[msg quest52_hint_talk_01_01 [Enthralled Woman]]
[s][vp 8 2 1 0 601 0]Sim, realmente. Ela deveria fazer o que[n]E preciso terminar com esse imbecil.[n][w][e]

[msg quest52_hint_talk_STONE__3 [Gossip-Loving Woman]]
[s][vp 8 2 1 0 600 0]Aquela mulher estava carregando um barato[n]parecendo rock, assim como o seu.[n][w][e]

[msg MSG_quest52_morgana_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Esse cara parece um pesadelo total.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]... mas nao ha nada que possamos fazer[n]Se nao soubermos o nome dele.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Vamos ver se podemos encontrar essa mulher.[n]Talvez ela nos diga o nome de Sleazeball.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Tudo o que temos que continuar e aquele namorado[n]da metade melhor do ano mantem um estranho[n]Rock com ela.[n][w][e]

[msg MSG_quest52_morgana_STON_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Esse cara parece um pesadelo total.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]... mas nao ha nada que possamos fazer[n]Se nao soubermos o nome dele.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Vamos ver se podemos encontrar essa mulher.[n]Talvez ela nos diga o nome de Sleazeball.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Ei, aquela rocha  O Melhor Namorado[n]O Bonnie Lass de Ever nao era um santo[n]Pedra?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Vamos balancar na loja de Mifune.[n][w][e]

[msg MSG_quest52_morgana_MIFU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Esse cara parece um pesadelo total.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]... mas nao ha nada que possamos fazer[n]Se nao soubermos o nome dele.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Parece que Mifune e o unico lider que[n]sairam. Como podemos fazer com que ela conte[n]nos o nome dele...?[n][w][e]

[msg MSG_quest52_morgana_MIFU_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Esse cara parece um pesadelo total.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]... mas nao ha nada que possamos fazer[n]Se nao soubermos o nome dele.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Mifune e a nossa melhor aposta. Sua fortuna[n]dizendo ao local, entao talvez ela[n]Aponte-nos na direcao certa.[n][w][e]

[msg MSG_quest52_morgana_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Esse cara parece um pesadelo total.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Eu acho que o nome dele e Yuya Uchimura.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Vamos para lembrar assim que[n]possivel  Temos que dar a este idiota um[n]Mudanca seria de coracao![n][w][e]

[msg quest52_hint_talk_02_00 [Gossip-Loving Woman]]
[s][vp 8 2 1 0 600 0]Ei, voce ouviu falar dessa mulher?[n]Aquele com o namorado abusivo.[n][w][e]

[msg quest52_hint_talk_02_01 [Enthralled Woman]]
[s][vp 8 2 1 0 601 0]Oh, sim  ela acabou sendo uma[n]perseguidor, certo? O cara nem sequer[n]o namorado dela.[n][w][e]

[msg quest52_hint_talk_02_02 [Gossip-Loving Woman]]
[s][vp 8 2 1 0 600 0]Sim. E o cara, ele foi pressionar[n]cobrancas, mas...[n][w][e]
[s][vp 8 2 1 0 600 0]Quando a policia olhou para isso, eles[n]nao conseguiu encontrar evidencias de que a mulher[n]ate existia.[n][w][e]
[s][vp 8 2 1 0 600 0]Ele confessou que estava atingindo[n]ela, mas...[n][w][e]
[s][vp 8 2 1 0 600 0]Bem, sem vitima, nao ha muito[n]A policia pode fazer.[n][w][e]

[msg quest52_hint_talk_02_03 [Enthralled Woman]]
[s][vp 8 2 1 0 601 0]Voce se lembra do nome dela?[n][w][e]

[msg quest52_hint_talk_02_04 [Gossip-Loving Woman]]
[s][vp 8 2 1 0 600 0]Huh? Uh... Nao. Ah bem.[n][w][e]

[msg MSG_F006_001_00_Q74_HINT [Busy-Looking Young Man]]
[s][vp 8 2 1 0 650 0]HM? "BillionCoin"?[n][w][e]

[msg MSG_F006_001_00_Q74_HINT_2 [Busy-Looking Young Man]]
[s][vp 8 2 1 0 650 0]Um comerciante de Deus nao vai lidar com isso[n]tipo de merda![n][w][e]

[sel SEL_F006_001_00_Q74_HINT top]
[s]Explique mais[e]
[s]Merda?[e]

[msg MSG_F006_001_00_Q74_HINT_3 [Busy-Looking Young Man]]
[s][vp 8 2 1 0 650 0]Voce compra essa merda uma vez, acabou! o[n]O site esta sempre em construcao![n][w][e]
[s][vp 8 2 1 0 650 0]Nao ha utilidade para isso! E inutil![n]Merda! Merda! Merda...[n][w][e]

[msg MSG_CHK_Q74_HINT_QUEST_0]
[s][vp 1 0 0 0 0 0]Missao 74 dica npc[n]Tenho todas as dicas[n][w][e]

[msg MSG_CHK_Q74_HINT_QUEST_0_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Temos informacoes suficientes. Vamos falar isso[n]com todos no esconderijo.[n][w][e]

[msg MSG_BENGOSHI_001_0_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Voce ouviu sobre Madarame e[n]Os ladroes fantasmas dos coracoes?[n][w][e]

[msg MSG_BENGOSHI_001_1_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Phantom Thieves, hein? Eles devem ser[n]bastante primario e adequado se eles estao[n]entregando cartoes de chamada.[n][w][e]
[s][vp 8 2 1 0 22 0]Eles dizem que nao encontraram nenhum outro[n]evidencia sobre eles ainda. Eu me pergunto[n]O que vai acontecer.[n][w][e]

[msg MSG_BENGOSHI_001_2_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]A internet os esta tratando como se eles[n]Robin Hood. Duvido que a policia possa[n]ignore isso por muito tempo.[n][w][e]

[msg MSG_BENGOSHI_002_0_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Outro cartao de visita... eu vou admitir o[n]Phantom Thieves escolheu um bom[n]alvo embora.[n][w][e]

[msg MSG_BENGOSHI_002_1_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Kaneshiro, hein? A policia nao consegue lidar[n]ele, entao eles vao conquistar o publico se[n]Eles o derrubam.[n][w][e]

[msg MSG_BENGOSHI_002_2_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Voce acha que sera tao simples? Eles estao[n]indo atras de uma figura importante no[n]submundo criminal.[n][w][e]

[msg MSG_BENGOSHI_002_3_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]E exatamente por isso que e emocionante ver[n]O que vai acontecer a seguir.[n][w][e]

[msg MSG_BENGOSHI_003_0_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Quem sabia que as coisas seriam resolvidas[n]tao facilmente?[n][w][e]

[msg MSG_BENGOSHI_003_1_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]E gracas a internet, agora[n]Todo mundo sabe que a policia era apenas[n]cheio de conversa.[n][w][e]

[msg MSG_BENGOSHI_003_2_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Agora que a policia perdeu o rosto,[n]a midia de massa vai girar para[n]os ladroes fantasmas.[n][w][e]
[s][vp 8 2 1 0 22 0]Phantom Thieves, hein? Parece[n]As coisas ficarao muito ocupadas por nos em breve.[n][w][e]

[msg MSG_BENGOSHI_004_0_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Como voce esta? Voce deve estar muito ocupado[n]nos dias de hoje.[n][w][e]

[msg MSG_BENGOSHI_004_1_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Sim, eu preciso me preparar para esses casos[n]relacionado a vazamentos de informacoes e[n]acesso nao autorizado.[n][w][e]
[s][vp 8 2 1 0 22 0]Esses superiores corporativos sao[n]em panico. Eles nunca ouviram[n]de Medjed ate agora.[n][w][e]

[msg MSG_BENGOSHI_004_2_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Suponho que eles tenham alguns grandes[n]Segredos que eles gostariam de manter, hahaha![n][w][e]

[msg MSG_BENGOSHI_005_0_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Voce sabe, se hackers atacarem[n]algo em larga escala, o[n]todo o pais pode entrar em colapso.[n][w][e]

[msg MSG_BENGOSHI_005_1_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Sim, tudo acabou se eles podem destruir[n]a infraestrutura. Aqueles hackers entram[n]Medjed sabe disso.[n][w][e]

[msg MSG_BENGOSHI_005_2_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Se a economia tambem sofrer um golpe, o[n]O governo atual tambem nao vai durar.[n][w][e]

[msg MSG_BENGOSHI_005_3_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Os ladroes fantasmas podem ser nossos[n]ultima esperanca. Talvez realmente tenhamos tomado[n]Paz como garantida, sabe?[n][w][e]

[msg MSG_BENGOSHI_006_0_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Entao eles conseguiram derrotar o Medjed tambem.[n]Ouvi dizer que tambem esta no noticiario no exterior.[n][w][e]
[s][vp 8 2 1 0 23 0]Quem sao eles, afinal...? Honestamente,[n]A ideia de que eles existem me assusta[n]um pouco.[n][w][e]

[msg MSG_BENGOSHI_006_1_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]A policia, os promotores, todos[n]No governo esta em armas, tentando encontrar[n]os ladroes fantasmas.[n][w][e]
[s][vp 8 2 1 0 22 0]Pode nao demorar ate aqueles[n]Os ladroes fantasmas sao finalmente pegos.[n][w][e]

[msg MSG_BENGOSHI_007_0_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Voce acha que os ladroes fantasmas[n]Vai atras de Okumura?[n][w][e]

[msg MSG_BENGOSHI_007_1_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Quem sabe? Nao e tao chamativo um alvo[n]como medjed embora.[n][w][e]
[s][vp 8 2 1 0 23 0]Empresas de todo o pais[n]explorar seus trabalhadores. Vai levar[n]Down um deles muda alguma coisa?[n][w][e]

[msg MSG_BENGOSHI_007_2_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Tenho certeza de que isso afetara a opiniao publica.[n]Acho que vamos sentar e assistir o que[n]eles fazem.[n][w][e]

[msg MSG_BENGOSHI_008_0_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Eles enviaram o cartao de visita.[n][w][e]
[s][vp 8 2 1 0 23 0]Gracas a eles, estou recebendo toneladas[n]de consultas relacionadas ao trabalho.[n][w][e]

[msg MSG_BENGOSHI_008_1_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Horas extras nao remuneradas e ilegais, abuso[n]de posicao... eu nao posso acreditar que eles lidaram[n]com isso por tanto tempo.[n][w][e]
[s][vp 8 2 1 0 22 0]As pessoas estao defendendo para seus[n]Direitos apos a coisa de Okumura.[n]Estarei ocupado por um bom tempo.[n][w][e]

[msg MSG_BENGOSHI_009_1_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Agora eu vejo. Entao eles fizeram um exemplo[n]desse presidente.[n][w][e]
[s][vp 8 2 1 0 23 0]Os ladroes Phantom nao querem[n]Para melhorar o mundo. Eles querem[n]tiranize pessoas com medo.[n][w][e]

[msg MSG_BENGOSHI_009_2_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Como voce pode dizer isso como advogado?[n]Voce esta dizendo que eles sao culpados sem[n]tendo alguma prova?[n][w][e]
[s][vp 8 2 1 0 22 0]Mas se houver provas, a policia ira[n]Encontre. Sua equipe de investigacao apenas[n]Adicionou um jogador de estrela.[n][w][e]

[msg MSG_BENGOSHI_010_0_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Eu vi akechi  acho que e dele[n]nome  outro dia no metro[n]Construcao do Departamento de Policia.[n][w][e]

[msg MSG_BENGOSHI_010_1_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Aquele detetive do ensino medio? Ele ainda e[n]Passando por la?[n][w][e]

[msg MSG_BENGOSHI_010_2_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Algumas pessoas de terno estavam seguindo[n]ele por ai. Eles estavam tratando-o[n]muito bem.[n][w][e]
[s][vp 8 2 1 0 23 0]Mantenha isso apenas entre nos, mas...[n]As pessoas em saude publica estao indo[n]Para fazer uma mudanca em breve.[n][w][e]

[msg MSG_BENGOSHI_011_0_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Uau, 30 milhoes de ienes! Esse e o maior[n]recompensa ja colocada para um criminoso[n]no nosso pais![n][w][e]
[s][vp 8 2 1 0 22 0]Tambem parece suspeito. Nao[n]esta situacao meio que parece que era[n]tudo configurado?[n][w][e]

[msg MSG_BENGOSHI_011_1_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Provavelmente e a policia que envia[n]uma mensagem. "Isto e o que acontece[n]Quando voce atravessa as autoridades. "[n][w][e]
[s][vp 8 2 1 0 23 0]Essa coisa toda foi impactada[n]o governo. Eu duvido da policia[n]estao ansiosos pelo Natal.[n][w][e]

[msg MSG_BENGOSHI_012_0_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Vamos supor que os ladroes fantasmas recebam[n]apanhado. O que voce faria se eles perguntassem[n]Voce e o advogado deles?[n][w][e]

[msg MSG_BENGOSHI_012_1_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Eu diria que sim em um piscar de olhos. Eu nao quero[n]Traga minhas emocoes pessoais para o meu[n]trabalho, mas...[n][w][e]
[s][vp 8 2 1 0 22 0]Muitas pessoas surgiram contra[n]sociedade antes, mas desta vez, esta em[n]uma escala diferente.[n][w][e]
[s][vp 8 2 1 0 22 0]Eu realmente quero ver o que o[n]Os ladroes Phantom faria.[n][w][e]

[msg MSG_BENGOSHI_013_0_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Depois de um suicidio atras das grades, o todo[n]coisa acabou. Isso realmente sentiu[n]Anticlimatico de alguma forma.[n][w][e]

[msg MSG_BENGOSHI_013_1_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]E surpreendente que ninguem saiba disso[n]identidade do menino. Eu pensei com certeza[n]A policia vazaria.[n][w][e]

[msg MSG_BENGOSHI_013_2_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Suponho que eles queriam manter isso[n]informacoes para si mesmas depois de salvar[n]sua dignidade com essa prisao.[n][w][e]

[msg MSG_BENGOSHI_013_3_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]E uma pena que ele tenha morrido, no entanto.[n]Eu realmente gostaria de poder ter representado[n]dele.[n][w][e]

[msg MSG_BENGOSHI_014_0_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Eu nao achei o anuncio[n]era uma mentira total. Demitindo todo mundo[n]envolvidos nao impedirao a indignacao.[n][w][e]

[msg MSG_BENGOSHI_014_1_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Shido esta praticamente entrado em[n]se escondendo. Todos eles dizem que ele caiu[n]mal ou algo assim.[n][w][e]

[msg MSG_BENGOSHI_014_2_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]E tudo muito obscuro, incluindo como[n]o lider do especial[n]A equipe de investigacao morreu.[n][w][e]

[msg MSG_BENGOSHI_014_3_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Quem sabe o que esta acontecendo?[n]Algo assim pode ate ser[n]tratado pela lei?[n][w][e]

[msg MSG_BENGOSHI_015_0_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Tantas pessoas morreram. E isto[n]Como termina todo esse fiasco?[n][w][e]

[msg MSG_BENGOSHI_015_1_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]... So Shido sabe. Nos teremos[n]esperar que ele melhore.[n][w][e]

[msg MSG_BENGOSHI_015_2_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Algumas pessoas estao tentando construir[n]um caso contra ele, mas vai[n]Seja impossivel encontra-lo culpado.[n][w][e]

[msg MSG_BENGOSHI_015_3_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Sim, ele e o lider da decisao[n]Festa. A promotoria atual nao pode[n]toque ele.[n][w][e]

[msg MSG_BENGOSHI_016_0_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]O ano passado foi tao agitado, o que com o[n]Ladroes fantasmas e o incidente com[n]Shido.[n][w][e]

[msg MSG_BENGOSHI_016_1_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Gracas a isso, este ano provavelmente sera[n]tedioso.[n][w][e]

[msg MSG_BENGOSHI_016_2_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Ei, nao diga coisas assim. Advogados[n]devem manter a lei e a ordem.[n][w][e]

[msg MSG_BENGOSHI_016_3_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]As pessoas esquecem o valor da lei e da ordem[n]Quando esta muito pacifico. A sociedade precisa um pouco[n]Um pouco de caos aqui e ali.[n][w][e]

[msg MSG_BENGOSHI_017_0_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10]Este ano e estranho... muitos clientes sao[n]retirando seus processos.[n][w][e]

[msg MSG_BENGOSHI_017_1_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]O mesmo aqui, na verdade. Ainda conseguimos empregos que[n]nao sao processos, mas...[n][w][e]

[msg MSG_BENGOSHI_017_2_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Um mundo sem lutar, onde todos[n]esta feliz... acho que isso e um reflexo disso[n]Sociedade de Ano.[n][w][e]

[msg MSG_BENGOSHI_017_3_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]E bom que todos estejam felizes, mas...[n]E um pouco assustador quando isso e difundido.[n][w][e]

[msg MSG_BENGOSHI_018_0_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Eu estive me perguntando. O que voce vai fazer[n]Se voce recebe uma oferta para defender Shido?[n][w][e]

[msg MSG_BENGOSHI_018_1_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Prefiro defender os ladroes fantasmas[n]do que shido.[n][w][e]
[s][vp 8 2 1 0 23 0]Aposto que teria sido um caso fascinante para[n]trabalhar em, com todas as coisas inesperadas que[n]poderia surgir.[n][w][e]

[msg MSG_BENGOSHI_018_2_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]... bem, eles nunca foram capturados, entao[n]Nao ha mais necessidade de defende-los.[n][w][e]

[msg MSG_BENGOSHI_018_3_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]Em retrospectiva, eles eram interessantes[n]monte. Seria uma pena para a sociedade[n]para esquece-los completamente.[n][w][e]

[msg MSG_BENGOSHI_019_0_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]No final, nunca aprendemos quem[n]os ladroes fantasmas eram, ou o que[n]causou toda essa discordia no Japao.[n][w][e]

[msg MSG_BENGOSHI_019_1_0 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Eu nao concordo. Pelo menos,[n]Shido enfrentara julgamento pelo que[n]Ele terminou.[n][w][e]
[s][vp 8 2 1 0 22 0]Agora, a coisa que me incomoda[n]e que me pediram para ser[n]parte da equipe juridica de Shido.[n][w][e]

[msg MSG_BENGOSHI_019_2_0 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]E a sua vez de estar no local,[n]E seja perguntado o que e a verdadeira justica.[n]I know it's clich, but good luck.[n][w][e]

[msg MSG_Q79_HINT_BENGOSHI_00 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Cara, eu nao sei o que fazer com isso[n]deputado...[n][w][e]

[msg MSG_Q79_HINT_BENGOSHI_01 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]... voce esta falando sobre Morozumi-san?[n]Eu acho que voce deveria considerar o backup.[n][w][e]
[s][vp 8 2 1 0 23 0]Isso esta fora do registro, mas ele tem alguns[n]Rumores desagradaveis ao seu redor...[n][w][e]

[msg MSG_Q79_HINT_MORU_00_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Moro...? Ei, nao e sobre o falso[n]acusacao?[n][w][e]
[s]Vamos ficar quietos e ouvir.[n][w][e]

[msg MSG_Q79_HINT_BENGOSHI_02 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]Ele parecia bastante em panico recentemente.[n][w][e]
[s][vp 8 2 1 0 22 0]Ele foi ao local de trabalho do agressor[n]por algum motivo tambem...[n][w][e]
[s][vp 8 2 1 0 22 0]Cara, espero que ele nao faca nada[n]extremo. Embora nao pareca[n]Ele fez qualquer coisa violenta...[n][w][e]
[s][vp 8 2 1 0 22 0]Ainda assim, eu poderia ter perdido minha chance de voltar[n]Fora...[n][w][e]

[msg MSG_Q79_HINT_BENGOSHI_03 [Serious-Looking Lawyer]]
[s][f 4 23 1 23 3 10 0 10][vp 8 2 1 0 23 0]E bom que ele age, mas com certeza e[n]dando-me dor de cabeca.[n][w][e]
[s][vp 8 2 1 0 23 0]Ele era o secretario do ex-primeiro[n]Ministro, mas ele causou um escandalo ao obter[n]envolvido com a filha do primeiro-ministro.[n][w][e]
[s][vp 8 2 1 0 23 0]Todo mundo estava falando sobre ela ser dele[n]amante e tudo. Nao esperava o escandalo para[n]termine com seu suicidio...[n][w][e]
[s][vp 8 2 1 0 23 0]Ele realmente teve sorte. Eu nao me pegava[n]envolvido.[n][w][e]

[msg MSG_Q79_HINT_BENGOSHI_04 [Sharp Lawyer]]
[s][f 4 23 1 22 3 10 0 10][vp 8 2 1 0 22 0]... hm?[n][w][e]

[msg MSG_Q79_HINT_MORU_10_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]... caramba, eles nos notaram!? Vamos esgueirar-se[n]um jeito![n][w][e]

[msg MSG_Q79_HINT_MORU_20_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]* suspiro* Conseguimos evitar ser notado...[n]Vamos examinar as informacoes que reunimos.[n][w][e]
[s][f 4 10 65535 0 0]Qualquer coisa em particular que voce notou?[n][w][e]

[sel SEL_Q79_HINT_00_00 top]
[s]O suicidio daquela mulher.[e]
[s]Pai de Toji.[e]

[msg MSG_Q79_HINT_MORU_30_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1023 65535 0]Sim, isso esta me incomodando tambem.[n][w][e]
[s][f 4 10 65535 0 0]A mae de Toji cometeu suicidio e de[n]O que ouvimos, a pessoa que ele causou[n]escandalo com tambem suicidio.[n][w][e]
[s][f 4 10 65535 0 0]Isso nao pode ser apenas uma coincidencia. Poderia[n]seja o pai...[n][w][e]
[s][f 4 10 65535 0 0]Mas o nome. E Ushiwata, nao Morozumi,[n]certo?[n][w][e]

[msg MSG_Q79_HINT_MORU_30_10 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1023 65535 0]Sim, isso esta me incomodando tambem.[n][w][e]
[s][f 4 10 65535 0 0]E dificil de acreditar, mas poderia ser assim[n]O pai de Toji...?[n][w][e]
[s]A mae de Toji cometeu suicidio e de[n]O que ouvimos, a pessoa que ele causou[n]escandalo com tambem suicidio.[n][w][e]
[s][f 4 10 65535 0 0]Mas o nome. E Ushiwata, nao Morozumi,[n]certo?[n][w][e]

[msg MSG_Q79_HINT_MORU_40_10 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Hmm, eu nao entendo... mas nos nao[n]tem mais leads.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Akechi pode ser feito investigando.[n]Vamos negociar informacoes com ele a noite.[n][w][e]

[msg MSG_YOKOTA_001_0_0 [Yokoda]]
[s][f 4 23 1 32263 3 10 0 10][vp 8 2 1 0 5 0]Oh, voce e o discipulo de Mifune-san...[n]Voce esta a caminho de se encontrar com ela?[n][w][e]
[s][vp 8 2 1 0 5 0]Nos apenas nos encontramos com ela mesmos.[n][w][e]

[msg MSG_YOKOTA_002_0_0 [Genial Woman]]
[s][f 4 23 1 32265 3 10 0 10][vp 8 2 1 0 6 0]Eu costumava culpar tudo no destino,[n]Mas agora eu decidi assumir o controle[n]da minha propria vida.[n][w][e]

[msg MSG_YOKOTA_003_0_0 [Bright-Faced Man]]
[s][f 4 23 1 32268 3 10 0 10][vp 8 2 1 0 7 0]Devemos isso a donzela... quero dizer,[n]Mifune-san, por abrir nossos olhos.[n][w][e]

[msg MSG_YOKOTA_004_0_0 [Yokoda]]
[s][f 4 23 1 32263 3 10 0 10][vp 8 2 1 0 5 0]Ainda ha momentos em que falhamos,[n]e claro.[n][w][e]
[s][vp 8 2 1 0 5 0]Mas agora, posso dizer com confianca[n]Essa vida realmente nao e tudo ruim.[n][w][e]

[msg MSG_YOKOTA_END [Yokoda]]
[s][f 4 23 1 32263 3 10 0 10][vp 8 2 1 0 5 0]Claro, ainda ha momentos em que[n]nos falhamos...[n][w][e]
[s][vp 8 2 1 0 5 0]Mas a vida nao e tudo ruim. E nenhum de nos[n]esta sozinho.[n][w][e]

