[msg D157_005_DOOR_01_mes01 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3112 65535 0]Nao parece que podemos abrir[n]agora mesmo...[n][w][e]

[msg NOT_OPEN_DOOR]
[s]A porta esta bem selada.[n][w][e]

[msg LOCK_DOOR]
[s]A porta esta trancada.[n][w][e]

[msg D157_009_miniEV_09_mes01 [Security Guard]]
[s]Sim... aquele convidado esta jogando lotes[n]de dinheiro.[n][w][e]
[s]Deixe que ele sinta que esta em uma sequencia de vitorias,[n]Em seguida, faca com que ele perca grande na rodada final.[n][w][e]

[msg D157_009_miniEV_09_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]TCH, eles estao dizendo aos revendedores como montar[n]os jogos...[n][w][e]

[msg D157_009_miniEV_09_mes03 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nos antecipamos isso.[n][w][e]

[msg D157_009_miniEV_09_mes04 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8019 65535 0]Independentemente, seria um problema se[n]Esses guardas nos viram. Devemos sair[n]este lugar por enquanto.[n][w][e]

[msg DOOR_Dummy_MES [Akechi]]
[s]ERROR! イベントをセットして下さい。[n][w][e]

