[msg NOT_OPEN_DOOR]
[s]A porta esta bem selada.[n][w][e]

[msg LOCK_DOOR]
[s]A porta esta trancada.[n][w][e]

[msg mini_EV_DOOR_LOCK_01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Uma porta fechada? Deve haver um cartao[n]leitor por aqui...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Ou nao. Talvez esteja do outro lado?[n][w][e]

[msg mini_EV_DOOR_LOCK_02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Eu acho que voce ficara aberto se usar[n]aquela coisa.[n][w][e]

[msg DOOR_Dummy_MES [Ryuji]]
[s]ERROR! イベントをセットして下さい。[n][w][e]

