[msg EnTalkMsg_DUMMY]
[s]......[n][w][e]

[msg DebugMsg_ERROR]
[s](Error)[n][w][e]

[msg TalkMsg_EN_CONTACT_00]
[s]HMHM... parece que seu amigo está em perigo.[n][w][e]
[s]Você sabe sempre que quis [n][f 2 5 3 9999 3]. Pegue minha deriva?[n][w][e]

[msg TalkMsg_EN_CONTACT_01]
[s]... Oh cara, parece que seu amigo está com[n]problemas.[n][w][e]
[s]Você não quer salvá-los? Eu posso estar[n]disposto a ouvir por [n][var 0]Yen.[n][w][e]

[msg TalkMsg_EN_CONTACT_02]
[s]Oh não... seu amigo não está em perigo real[n]aqui?[n][w][e]
[s]Quer fazer algo sobre isso? Então me dê um[n]pouco da sua saúde.[n][w][e]

[msg TalkMsg_EN_CONTACT_03]
[s]Uau, segure lá. O que acontecerá com seu[n]amigo se eu fizer minha mudança?[n][w][e]
[s]Você não quer salvá-los? Então me dê um[n]pouco da sua resistência.[n][w][e]

[sel TalkSel_EN_CONTACT top]
[s]Tudo bem, você ganha.[e]
[s]Não posso atender às suas demandas.[e]
[s]Call Thieves Guild ([var 5] left).[e]
[s][clr 2]Você está acordado, Pantera.[clr 27][e]

[msg TalkMsg_EN_DECLINE_00]
[s]Hmm... isso não é suficiente.[n][w][e]
[s]Me dê [f 2 5 3 9999 3]desta vez.[n]Eu não acho que você está em posição de me[n]recusar...[n][w][e]

[msg TalkMsg_EN_DECLINE_01]
[s]... isso não é suficiente para me satisfazer.[n]Talvez eu deva exigir mais...?[n][w][e]
[s]Desta vez, é melhor você pagar. Eu quero [n][var 0]Yen. É um preço barato pagar pelo seu amigo,[n]certo?[n][w][e]

[msg TalkMsg_EN_DECLINE_02]
[s]... Eu quero viver a boa vida, você sabe.[n][w][e]
[s]Por que você não me dá um pouco da sua[n]saúde? Tenho certeza de que não é problema,[n]pois é para salvar seu amigo.[n][w][e]

[msg TalkMsg_EN_DECLINE_03]
[s]Hmm, isso não parece um pouco apressado?[n][w][e]
[s]Por que você não me dá um pouco de sua[n]resistência? Tenho certeza de que não é[n]problema, pois é para salvar seu amigo.[n][w][e]

[msg TalkMsg_EN_AGREE_00]
[s]Heheh, acho que é o suficiente. Vou liberar[n]seu amigo.[n][w][e]

[msg TalkMsg_EN_AGREE_01]
[s]... ok, isso é o suficiente. Aqui, vou te[n]devolver seu amigo.[n][w][e]

[msg TalkMsg_EN_SLAY_00]
[s]Isso significa que você vai abandonar seu[n]amigo? Tão coração de frio...[n][w][e]

[msg TalkMsg_EN_SLAY_01]
[s]Acho que não tenho motivos para segurar[n]naquela época. Você vai se arrepender do[n]que aconteceu aqui hoje.[n][w][e]

[msg TalkMsg_EN_FORGIVE_00]
[s]Você está muito frio. Você não se importa[n]com seu companheiro de equipe?[n][w][e]
[s]... Ugh, isso não vale o meu tempo.[n]Estou indo embora![n][w][e]

[msg TalkMsg_EN_FORGIVE_01]
[s]Caramba, você está falando sério? Você vai[n]abandonar seu amigo? Mesmo eu não faria[n]nada![n][w][e]
[s]É isso, eu terminei! Estou indo embora![n][w][e]

[msg TalkMsg_EN_FLEE_00]
[s]Bem, estou bem. Eu vou sair daqui. Faça o[n]que você quiser![n][w][e]

[msg TalkMsg_EN_FLEE_01]
[s]Eu posso sair agora, certo?[n][w][e]

[msg TalkMsg_EN_ACCEPT_00]
[s]... Bem, então, vamos voltar aos negócios.[n][w][e]

[msg TalkMsg_EN_ACCEPT_01]
[s]... Ok, então, vamos retomar as coisas.[n][w][e]

[msg TalkMsg_EN_FALTER_00]
[s]Aahh! O que é que foi isso!?[n][w][e]

[msg TalkMsg_EN_FALTER_01]
[s]Huh!? Que nervo![n][w][e]

[msg TalkMsg_EN_FAKE_CRIED00]
[s]H-hey! Você está chorando!?... Tudo bem, eu[n]vou te perdoar! Só me dá [n][f 2 5 3 9999 3].[n][w][e]

[msg TalkMsg_EN_FAKE_CRIED01]
[s]O que...? Essa mulher é muito problema. Só[n]me dá  [var 0]Yen.[n]Vou deixar você sair do gancho.[n][w][e]

[msg TalkMsg_EN_FAKE_CRIED02]
[s]H-hey! Você está chorando!?... Se você me[n]der um pouco da sua saúde, acho que posso[n]te perdoar.[n][w][e]

[msg TalkMsg_EN_FAKE_CRIED03]
[s]O que...? Essa mulher é demais- apenas me dê[n]um pouco de sua resistência. Eu vou te[n]perdoar.[n][w][e]

[msg TalkMsg_EN_FAKE_COUP00]
[s]Huh!? Você é criança? Tudo bem, continue[n]chorando![n][w][e]

[msg TalkMsg_EN_FAKE_COUP01]
[s]Caramba... essa mulher é louca.[n]Tudo bem, eu terminei aqui.[n][w][e]

[msg TalkMsg_NO_REQUIREMENT]
[s]Você não tem!?[n][w][e]

[msg CharmActing [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 5 301 1]Não... como você poderia tirar isso de nós?[n][w][e]

[msg NetEngo]
[s]Outro bando de ladrões respondeu à ligação![n][w][e]

