[msg MSG_BTLTALKSTART01_000_0 [Lavenza]]
[s]Nada mal... Você conseguiu[n]me nocautear...[n][f 1 3 65535][w][e]

[msg MSG_BTLTALKSTART01_000_0_2 [Lavenza]]
[s]Nada mal... Você conseguiu[n]me nocautear...[n][f 1 3 65535][w][e]

[msg MSG_BTLTALKSTART01_000_0_3 [Lavenza]]
[s]Nada mal... Você conseguiu[n]me nocautear...[n][f 1 3 65535][w][e]

[msg MSG_BTLTALKSELECT_000_00 [Lavenza]]
[s]Boneco[n][f 1 3 65535][w][e]

