[msg MSG_000_0_0 [Concerned Girl]]
[s][vp 8 0 0 0 4 0]What's wrong? You don't look so good.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ill-Looking Girl]]
[s][vp 8 0 0 0 5 0]I haven't been feeling well lately.[n]My head's all foggy, and I have[n]no energy...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]I've tried every drug at the pharmacy,[n]but nothing works. Do I have some[n]new virus?[n][f 1 3 65535][w][e]
[s][vp 8 2 0 40602 5 0]...Is this the onset of a psychotic[n]breakdown? Wh-What should I do?[n]Am I going to die!?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Concerned Girl]]
[s][vp 8 0 0 0 4 0]Calm down, calm down![n]Let's go to the clinic. Come on.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]I'm sure the doctor can prescribe[n]something that'll fix you right up![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1133 0 0]Doctors have the best medicine, huh...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Hey, wasn't that one customer back[n]at Leblanc a doctor?[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]So what?[e]
[s]Do you have a cold?[e]
[s]She was wearing punk clothes.[e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1021 0 0]It might be nice to have some strong[n]medicine to use in the Palace...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1036 0 0]No![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I just thought it might be nice[n]to have some strong medicine[n]to use in the Palace...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1036 0 0]That's not what's important here![n]Though she did have an interesting[n]fashion sense...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]It might be nice to have some strong[n]medicine to use in the Palace...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Dull Student]]
[s][vp 8 0 0 0 4 0]I thought I'd get a girlfriend once I was[n]in high school, but I'm not having any[n]luck at all...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 42851 4 0]Is there something wrong with me?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Calm Student]]
[s][vp 8 0 0 0 5 0]Maybe self-improvement is the answer.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Try reading some books.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]You'll get more than just some[n][f 4 11 0][clr 26][f 4 12 0][clr 27] out of them, and[n]it'll make you better in conversation.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]You'll be more desirable if you're more[n]intelligent. It'll take hard work, though—[n]won't happen overnight.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Dull Student]]
[s][vp 8 0 0 0 4 0]Yeah, but books make me sleepy...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Guess I can give it a go, though,[n]if it'll help make me more popular[n]with the ladies![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Uh, is the library where you go[n]to borrow books?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1166 0 0]Reading books is an important way[n]to expand your mind.[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]Books are great![e]
[s]And why should I do that?[e]
[s]I don't like reading though.[e]

[msg MSG_013_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1167 0 0]I totally agree.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]You can apparently read for free[n]at the [clr 2]school library[clr 27], so you should[n]try and take advantage of that.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I think there's also a [clr 2]bookstore[clr 27][n]over on [clr 2]Central Street[clr 27]...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1034 0 0]Diamonds don't start out beautiful.[n]You need to polish them first.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Similarly, you need to polish your[n]intellect in order to really tap into[n]your true talent.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]You can apparently read for free[n]at the [clr 2]school library[clr 27], so you should[n]try and take advantage of that.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I think there's also a [clr 2]bookstore[clr 27][n]over on [clr 2]Central Street[clr 27]...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1168 0 0]That's too bad...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]But you should at least put some[n]effort into it. There's a lot that[n]reading can teach you.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]You can apparently read for free[n]at the [clr 2]school library[clr 27], so you should[n]try and take advantage of that.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I think there's also a [clr 2]bookstore[clr 27][n]over on [clr 2]Central Street[clr 27]...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Athletic Student]]
[s][vp 8 2 0 43002 4 0]...Shogi? That's a grandpa-ass game[n]to get into now.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Hipster Student]]
[s][vp 8 0 0 0 5 0]Nah, it's back in fashion. There's a lot of[n]young shogi pros out there right now.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]I've been following [clr 2]Hifumi Togo[clr 27].[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]She's incredibly skilled for a high school[n]student. Not to mention pretty![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]She hasn't played much lately, though.[n]I heard she practices alone in [clr 2]a church[n]somewhere[clr 27].[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Athletic Student]]
[s][vp 8 0 0 0 4 0]She plays shogi in a church?[n]I don't get it. Seems strange.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1019 0 0]Did you hear that...?[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]I don't care about shogi.[e]
[s]About the pretty girl?[e]
[s]That girl sounds familiar.[e]

[msg MSG_021_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1037 0 0]That's not what I meant... Doesn't that[n]girl sound like the one that Yusuke was[n]talking about earlier?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I didn't realize she was a famous[n]shogi player...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1029 0 0]You would focus on her looks... Anyway,[n]doesn't she sound like the girl Yusuke[n]mentioned earlier?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I didn't realize she was a famous[n]shogi player...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1023 0 0]Yeah, she must be the same one[n]Yusuke mentioned earlier.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I didn't realize she was a famous[n]shogi player...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Serious Student]]
[s][vp 8 2 0 37554 4 0]I heard even the student council's[n]after whoever left the calling card.[n]Crazy, considering exams are soon.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Optimistic Third-Year]]
[s][vp 8 0 0 0 5 0]I forgot all about the exams.[n]I haven't studied at all...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Do you want to form a study group?[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Serious Student]]
[s][vp 8 0 0 0 4 0]...You just want to copy my notes,[n]don't you?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0][f 1 5]Optimistic Third-Year[n]What do you mean?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Real friends compensate for one another's[n]weaknesses![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1163 0 0]A study group with friends, huh...[n][f 1 3 65535][w][e]

[sel SEL_028_0_0 top]
[s]Let's do it![e]
[s]I want to be alone.[e]
[s]I want to go have fun...[e]

[msg MSG_029_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1023 0 0]Yeah, you can help each other with[n]questions you don't understand.[n]It'll be a great bonding experience.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]You should invite someone to study[n]with you sometime.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1025 0 0]Hey now, the leader of the Phantom[n]Thieves can't be a lone wolf.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Besides, you can help each other with[n]questions you don't understand.[n]It'll be a great bonding experience.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]You should invite someone to study[n]with you sometime.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1156 0 0]Not before the exams. Besides, having[n]fun isn't the only way to deepen your[n]friendships.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Helping each other with things you don't[n]understand is a great way to strengthen[n]your intellect and your bond as friends.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]You should invite someone to study[n]with you sometime.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Food-Loving Student]]
[s][vp 8 0 0 0 4 0]The school store's always out[n]of yakisoba pan, no matter[n]what time I go.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]I haven't been able to get any even once.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Well-Informed Student]]
[s][vp 8 0 0 0 5 0]Oh, don't you know?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]It's always sold out on Mondays,[n]but there's usually some left over[n]on Fridays.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Food-Loving Student]]
[s][vp 8 0 0 0 4 0]Are you serious!?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]I'll finally be able to get some[n]yakisoba pan today![n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1192 0 0]Huh, I guess there's a lot in this world[n]you can only get for a limited time or[n]during certain seasons...[n][f 1 3 65535][w][e]

[sel SEL_036_0_0 top]
[s]Now I want some, too.[e]
[s]I wouldn't mind some.[e]
[s]I don't want any.[e]

[msg MSG_037_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1168 0 0]Do you want to try to get some?[n]I'll come with you.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1034 0 0]Right? Do you want to try to find some?[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 65535 1169 0 0]Well aren't you just too cool...[n]Wouldn't hurt to show a little[n]enthusiasm once and a while.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Rumor-Loving Student]]
[s][vp 8 0 0 0 4 0]Hey, there's this article making[n]the rounds online...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]It's called "Confessions of Boy M: A Tell-all[n]on the Kamoshida Abuse Scandal."[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]That's gotta be Mishima, right?[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Rowdy Student]]
[s][vp 8 0 0 0 5 0]I read it![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]It all sounds so horrible... It's no[n]wonder they consider the Phantom[n]Thieves heroes.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Kinda hard to bag on the Phantom[n]Thieves after reading that...[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Rumor-Loving Student]]
[s][vp 8 0 0 0 4 0]You're right. In fact, you might call[n]them superheroes.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1020 0 0]That journalist's articles sure are[n]making a big splash.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]It might be the perfect way to get[n]the Phantom Thieves name out there.[n]We should take advantage of this.[n][f 1 3 65535][w][e]

[sel SEL_044_0_0 top]
[s]Get our name out there?[e]
[s]Why?[e]
[s]I'm not interested.[e]

[msg MSG_045_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1025 0 0]I want the Phantom Thieves to be[n]famous for more than just my own[n]selfish reasons.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]The bigger our name is, the more[n]our targets will hear talk of us.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Remember that reporter? If we give her[n]the right intel, her articles could make[n]a real difference for us in the Metaverse![n][f 1 3 65535][w][e]
[s][vp 8 2 65535 1174 0 0][f 4 10 65535 0 0]Let's go back to that [clr 2]bar in Shinjuku[clr 27] and[n]get her to write more stuff about us![n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1156 0 0]The bigger our name is, the more[n]our targets will hear talk of us.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Plus, the positive buzz will [clr 2]make[n]people less cautious of us[clr 27].[n][f 1 3 65535][w][e]
[s][vp 8 2 65535 1174 0 0][f 4 10 65535 0 0]Let's go back to that [clr 2]bar in Shinjuku[clr 27] and[n]get her to write more stuff about us![n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 65535 1026 0 0]Come on, try to show a little interest.[n]This is great news.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The bigger our name is, the more[n]our targets will hear talk of us.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Plus, the positive buzz will [clr 2]make[n]people less cautious of us[clr 27].[n][f 1 3 65535][w][e]
[s][vp 8 2 65535 1174 0 0][f 4 10 65535 0 0]We should go to that [clr 2]bar in[n]Shinjuku[clr 27] and convince her to[n]write more articles about us![n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Dull Student]]
[s][vp 8 0 0 1 4 0]I got a chance to talk to this girl[n]the other day...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 2 4 0]We had an amazing conversation[n]after I brought up some of the stuff[n]I read about![n][f 1 3 65535][w][e]
[s][vp 8 0 0 3 4 0]We're gonna go out somewhere[n]together soon![n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Calm Student]]
[s][vp 8 0 0 4 5 0]Well, don't get ahead of yourself[n]because it happened to go well.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 5 5 0]Look, [f 4 11 0][clr 26][f 4 12 0][clr 27] isn't enough.[n]You need [f 4 11 2][clr 26][f 4 12 2][clr 27] to adapt[n]on the fly.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 6 5 0]You also need [f 4 11 4][clr 26][f 4 12 4][clr 27] to be[n]accepted and [f 4 11 3][clr 26][f 4 12 3][clr 27] to be honest[n]and direct.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 7 5 0]Plus [f 4 11 1][clr 26][f 4 12 1][clr 27], to draw people[n]to you.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 8 5 0]The quality of your character says a lot[n]about you, so it's important to better[n]yourself every day.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Dull Student]]
[s][vp 8 0 0 9 4 0]Really? But it takes so much work...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 10 4 0]But I'll do it, if it means I'll get a girlfriend![n][f 1 3 65535][w][e]
[s][vp 8 0 0 11 4 0]I guess I'll start by showering every day.[n]I hear girls prefer a dude who's hygienic.[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Hey, this applies to you, too.[n][f 1 3 65535][w][e]

[sel SEL_052_0_0 top]
[s]Of course.[e]
[s]It's a waste of time.[e]
[s]Why?[e]

[msg MSG_053_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]You get it. That's a good attitude to have.[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Your hard work may not always pay off,[n]but that doesn't mean it's a waste of time.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 15 65535 0][f 4 10 65535 0 0]Working hard helps build confidence.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 16 65535 0][f 4 10 65535 0 0]Think you can get by on luck alone?[n]Think again![n][f 1 3 65535][w][e]

[msg MSG_055_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Working hard helps build confidence.[n]It's all about getting experience.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Think you can get by on luck alone?[n]Think again![n][f 1 3 65535][w][e]

[msg MSG_056_0_0 [Bag-Eyed Student]]
[s][vp 8 2 0 38702 4 0]They're seriously holding an emergency[n]meeting right when summer break is[n]starting?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]I guess they need to set some rules[n]when the world's eyes are on us[n]because of the Phantom Thieves.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Stuff like, "Don't do anything that will[n]hurt the school's reputation; spend[n]your summer break quietly."[n][f 1 3 65535][w][e]

[msg MSG_057_0_0 [Worried Student]]
[s][vp 8 2 0 39452 4 0]I can't stay quiet with all this excitement[n]going on. Medjed's statement was insane![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]"People of Japan, you must not worship[n]the Phantom Thieves," they said...[n]It could just be a joke.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]There's talk that this could lead to the[n]biggest leak of private data to date.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]I wonder if they're gonna target[n]another site... I'm curious to see[n]how the Phantom Thieves react.[n][f 1 3 65535][w][e]

[msg MSG_058_0_0 [Bag-Eyed Student]]
[s][vp 8 0 0 0 4 0]It's what I'm looking forward to most[n]this summer. It'll be the perfect escape[n]from exam studies.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]But the Phantom Thieves need to take[n]action. They're the ones Medjed is after.[n][f 1 3 65535][w][e]

[msg MSG_059_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1027 0 0]This is bigger than I thought.[n]We can't leave this be...[n][f 1 3 65535][w][e]

[sel SEL_060_0_0 top]
[s]You're right.[e]
[s]Don't be hasty.[e]
[s]Why?[e]

[msg MSG_061_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1035 0 0]Let's get this assembly out of the way.[n]We have our own business to attend to![n][f 1 3 65535][w][e]

[msg MSG_062_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1170 0 0]I applaud your cool-headedness,[n]but it'll be too late if we wait until[n]after something's happened.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]If Medjed does something drastic,[n]what will people think of us?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Let's get this assembly out of the way.[n]We have our own business to attend to![n][f 1 3 65535][w][e]

[msg MSG_063_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1156 0 0]If Medjed does something drastic,[n]what will people think of us?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Worst case scenario, they blame us[n]for everything...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Let's get this assembly out of the way.[n]We have our own business to attend to![n][f 1 3 65535][w][e]

[msg MSG_064_0_0 [Athletic Student]]
[s][vp 8 2 0 43002 4 0]...Shogi? That's a grandpa-ass game[n]to get into now.[n][f 1 3 65535][w][e]

[msg MSG_0650_0 [Hipster Student]]
[s][vp 8 0 0 0 5 0]Nah, it's back in fashion. There's a lot of[n]young shogi pros out there right now.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]I've been following [clr 2]Hifumi Togo[clr 27].[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]She's incredibly skilled for a high school[n]student. Not to mention pretty![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]She hasn't played much lately,[n]though. I heard she practices[n]alone in [clr 2]a church somewhere[clr 27].[n][f 1 3 65535][w][e]

[msg MSG_066_0_0 [Athletic Student]]
[s][vp 8 0 0 0 4 0]She plays shogi in a church?[n]I don't get it. Seems strange.[n][f 1 3 65535][w][e]

[msg MSG_067_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1019 0 0]Hey, did you hear what those two said?[n][f 1 3 65535][w][e]

[sel SEL_068_0_0 top]
[s]Not interested in shogi.[e]
[s]The pretty shogi player?[e]
[s]It could give us a leg up.[e]

[msg MSG_069_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1037 0 0]Well, maybe you should develop[n]an interest.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Shogi strategies might be useful during[n]battles in the Metaverse.[n][f 1 3 65535][w][e]

[msg MSG_070_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1029 0 0]THAT's what you focused on?[n]Anyway... I think you should[n]consider learning shogi.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Shogi strategies might be useful during[n]battles in the Metaverse.[n][f 1 3 65535][w][e]

[msg MSG_071_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1023 0 0]I had the same thought.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Shogi strategies might be useful during[n]battles in the Metaverse.[n][f 1 3 65535][w][e]

[msg MSG_072_0_0 [Excited Girl]]
[s][vp 8 0 0 0 4 0]Hey, guess what! I'm thinking of going[n]for a career on quiz shows![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]They were showing this movie called[n]Tanktop Millionaire at the theater on[n]Central Street...[n][f 1 3 65535][w][e]

[msg MSG_073_0_0 [Skeptical Girl]]
[s][vp 8 0 0 0 5 0]You mean the one where a boy rises[n]from rags to riches by winning on a[n]quiz show?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Sheesh, you get way too into those[n]stories... How about studying for exams[n]before you think about quiz shows?[n][f 1 3 65535][w][e]

[msg MSG_074_0_0 [Excited Girl]]
[s][vp 8 0 0 0 4 0]Oof... You got me there...[n][f 1 3 65535][w][e]

[msg MSG_075_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1167 0 0]Sounds like that movie can change your[n]worldview... Watching movies in the[n]theater sounds like a special experience.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]What kind of movies do you like?[n][f 1 3 65535][w][e]

[sel SEL_076_0_0 top]
[s]Action.[e]
[s]Comedy.[e]
[s]Not telling.[e]

[msg MSG_077_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1166 0 0]I get you. They're just so cathartic[n]to watch![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]When I turn back into a human, it might[n]not be so bad to make our debut on the[n]silver screen...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Either way, we should check out the[n]theater every now and then, since[n]they're always showing new films.[n][f 1 3 65535][w][e]

[msg MSG_078_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 65535 1021 0 0]...Seriously!? Well, that might actually[n]suit you, surprisingly enough...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]When I turn back into a human, how[n]about you and I make our comedic[n]duo debut on the silver screen?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Either way, we should check out the[n]theater every now and then, since[n]they're always showing new films.[n][f 1 3 65535][w][e]

[msg MSG_079_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1043 0 0]Not the telling type, huh...? You're[n]probably the kind of person who[n]likes spy movies, I'll bet![n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A spy movie featuring a cat and a[n]human... That sounds like it'd sell, no?[n]...I'm not a cat though.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Either way, we should check out the[n]theater every now and then, since[n]they're always showing new films.[n][f 1 3 65535][w][e]

[msg MSG_080_0_0 [Hungry Student]]
[s][vp 8 0 0 0 4 0]I skipped breakfast, so now I'm hungry...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]I want something filling, but with[n]summer coming up I'm worried[n]about having too many calories...[n][f 1 3 65535][w][e]

[msg MSG_081_0_0 [Discerning Student]]
[s][vp 8 0 0 0 5 0]Why don't we get tea? The diner[n]in Shibuya serves Frui-Tea.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]It smells good, it's great for your skin,[n]and it totally increases your charm![n][f 1 3 65535][w][e]

[msg MSG_082_0_0 [Hungry Student]]
[s][vp 8 0 0 0 4 0][clr 2]Frui-Tea[clr 27]? What a cute name![n]Sounds yummy![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Being stylish starts from the inside out,[n]after all. Guess I'll try some.[n][f 1 3 65535][w][e]

[msg MSG_083_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1168 0 0][clr 2]Frui-Tea[clr 27], huh...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Sounds like a hip drink that's[n]real popular with the ladies.[n]You want to try some?[n][f 1 3 65535][w][e]

[sel SEL_084_0_0 top]
[s]Sounds delicious.[e]
[s]I'm too embarrassed...[e]
[s]Water's fine.[e]

[msg MSG_085_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1166 0 0]No rule against dudes drinking it.[n]If it tastes good and makes you more[n]stylish, might as well, right?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It might be a good idea to boost your[n][f 4 11 1][clr 26][f 4 12 1][clr 27] by drinking [clr 2]Frui-Tea[clr 27][n]whenever you're at the diner.[n][f 1 3 65535][w][e]

[msg MSG_086_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1021 0 0]No rule against dudes drinking it.[n]If it tastes good and makes you more[n]stylish, might as well, right?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It might be a good idea to boost your[n][f 4 11 1][clr 26][f 4 12 1][clr 27] by drinking [clr 2]Frui-Tea[clr 27][n]whenever you're at the diner.[n][f 1 3 65535][w][e]

[msg MSG_087_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 65535 1028 0 0]I see...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, you should keep an open mind.[n]If it tastes good and makes you more[n]stylish, might as well, right?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It might be a good idea to boost your[n][f 4 11 1][clr 26][f 4 12 1][clr 27] by drinking [clr 2]Frui-Tea[clr 27][n]whenever you're at the diner.[n][f 1 3 65535][w][e]

[msg MSG_088_0_0 [Hungry Student]]
[s][vp 8 0 0 0 4 0]I skipped breakfast, so now I'm hungry...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Have you seen the [clr 2]Totem Pole[clr 27][n]at the diner in Shibuya yet?[n][f 1 3 65535][w][e]

[msg MSG_089_0_0 [Discerning Student]]
[s][vp 8 0 0 0 5 0]Haha, yeah—it really is a [clr 2]Totem Pole[clr 27].[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]It's so colorful. I just love watching[n]people try to eat it![n][f 1 3 65535][w][e]

[msg MSG_090_0_0 [Hungry Student]]
[s][vp 8 0 0 0 4 0]You know those people who can eat[n]it without it falling over? I'd never be[n]able to do that![n][f 1 3 65535][w][e]

[msg MSG_091_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1170 0 0]Eating a [clr 2]Totem Pole[clr 27]? Without it[n]falling over...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I wonder why they call it the [clr 2]Totem Pole[clr 27]?[n][f 1 3 65535][w][e]

[sel SEL_092_0_0 top]
[s]Probably the way it looks.[e]
[s]Just a coincidence...?[e]
[s]Maybe the smell.[e]

[msg MSG_093_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1025 65535 0]Well what does it look like...? You didn't[n]really think about that, did you.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hmm... Eating without it falling over...[n]You might be able to improve your[n][f 4 11 2][clr 26][f 4 12 2][clr 27] there.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The [clr 2]Totem Pole[clr 27] at the diner, huh...[n]We should go there at least once and[n]see what it's all about.[n][f 1 3 65535][w][e]

[msg MSG_094_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1025 65535 0]Well, it's important to go with a good[n]gut feeling, but maybe not when[n]naming food.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hmm... Eating without it falling over...[n]You might be able to improve your[n][f 4 11 2][clr 26][f 4 12 2][clr 27] there.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The [clr 2]Totem Pole[clr 27] at the diner, huh...[n]We should go there at least once and[n]see what it's all about.[n][f 1 3 65535][w][e]

[msg MSG_095_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 65535 1177 0 0]What does that even mean? Have you[n]smelled a totem pole before?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hmm... Eating without it falling over...[n]You might be able to improve your[n][f 4 11 2][clr 26][f 4 12 2][clr 27] there.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The [clr 2]Totem Pole[clr 27] at the diner, huh...[n]We should go there at least once and[n]see what it's all about.[n][f 1 3 65535][w][e]

[msg MSG_999_0_0 [Rumor-Loving Student]]
[s][vp 8 0 0 0 4 0]The Phantom Thieves are nothing[n]more than criminals. I hope they[n]get caught soon.[n][f 1 3 65535][w][e]

[msg MSG_999_1_0 [Rowdy Student]]
[s][vp 8 0 0 0 5 0]Yeah, those mental shutdowns[n]are horrible.[n][f 1 3 65535][w][e]

[msg MSG_999_2_0 [Rumor-Loving Student]]
[s][vp 8 0 0 0 4 0]I wasted my time supporting them,[n]and now I'll never get that back.[n][f 1 3 65535][w][e]

[msg MSG_999_3_0 [Mishima]]
[s][bup 0 111 0 65535 0][vp 8 2 65535 1020 0 0]......[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I'm rooting for you, [f 4 1]![n][f 1 3 65535][w][e]

[msg MSG_100_0_0 [Crude Girl]]
[s][vp 8 0 0 0 4 0]So I was like, washing some of my[n]favorite western-style clothes, and[n]they like, came out really stiff.[n][f 1 3 65535][w][e]

[msg MSG_101_0_0 [Girl Who Likes Cleanliness]]
[s][vp 8 0 0 0 5 0]Did you read the washing instructions[n]on the label? Some clothes are really[n]delicate, you know.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Even a single stain takes a lot of care[n]to wash. I recommend some good[n]detergent, even if it's expensive.[n][f 1 3 65535][w][e]

[msg MSG_102_0_0 [Crude Girl]]
[s][vp 8 0 0 0 4 0]The detergent is that important...?[n]Maybe I'll like, stop by the drugstore[n]on the way home.[n][f 1 3 65535][w][e]

[msg MSG_103_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1167 0 0]So the detergent really makes that[n]much of a difference, huh?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]What do you look for in a detergent?[n][f 1 3 65535][w][e]

[sel SEL_104_0_0 top]
[s]Scent.[e]
[s]Softness.[e]
[s]Whatever's fine.[e]

[msg MSG_105_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1184 0 0]Wow, that's surprisingly mature of you[n]to consider.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]People don't like it if a smell is too[n]strong. Even I wouldn't wanna be next[n]to you in that case.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We should check out the drugstore[n]sometime and see what kinds of[n]detergent they have![n][f 1 3 65535][w][e]

[msg MSG_106_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1184 0 0]Yeah, you know what's important![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The feeling of a warm, fluffy towel, fresh[n]out of the dryer... That's absolute heaven.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So, we should check out the drugstore[n]sometime and see what kinds of[n]detergent they have![n][f 1 3 65535][w][e]

[msg MSG_107_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1043 0 0]"Whatever's fine"...? Didn't you hear[n]what they just said? What're you gonna[n]do if your uniform gets all stiff?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]All right, let's check out the drugstore[n]sometime and see what kinds of[n]detergent they have![n][f 1 3 65535][w][e]

[msg MSG_108_0_0 [Excited Girl]]
[s][vp 8 0 0 0 4 0]Hey, guess what! I'm thinking of going[n]for a career on quiz shows![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]They were showing this movie called[n]Tanktop Millionaire at the theater on[n]Central Street...[n][f 1 3 65535][w][e]

[msg MSG_109_0_0 [Skeptical Girl]]
[s][vp 8 0 0 0 5 0]You mean the one where a boy rises[n]from rags to riches by winning on a[n]quiz show?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Sheesh, you get way too into those[n]stories... How about studying for exams[n]before you think about quiz shows?[n][f 1 3 65535][w][e]

[msg MSG_110_0_0 [Excited Girl]]
[s][vp 8 0 0 0 4 0]Oof... You got me there...[n][f 1 3 65535][w][e]

[msg MSG_111_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1167 0 0]Sounds like that movie can change your[n]worldview... Watching movies in the[n]theater sounds like a special experience.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]What kind of movies do you like?[n][f 1 3 65535][w][e]

[sel SEL_112_0_0 top]
[s]Action.[e]
[s]Comedy.[e]
[s]Not telling.[e]

[msg MSG_113_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1166 0 0]I get you. They're just so cathartic[n]to watch![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]When I turn back into a human, it might[n]not be so bad to make our debut on the[n]silver screen...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, as much as I want to check out[n]that movie they talked about, we've[n]gotta focus on Kamoshida for now.[n][f 1 3 65535][w][e]

[msg MSG_114_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 65535 1021 0 0]...Seriously!? Well, that might actually[n]suit you, surprisingly enough...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]When I turn back into a human, how[n]about you and I make our comedic[n]duo debut on the silver screen?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, as much as I want to check out[n]that movie they talked about, we've[n]gotta focus on Kamoshida for now.[n][f 1 3 65535][w][e]

[msg MSG_115_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1043 0 0]Not the telling type, huh...? You're[n]probably the kind of person who[n]likes spy movies, I'll bet![n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A spy movie featuring a cat and a[n]human... That sounds like it'd sell, no?[n]...I'm not a cat though.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, as much as I want to check out[n]that movie they talked about, we've[n]gotta focus on Kamoshida for now.[n][f 1 3 65535][w][e]

[msg MSG_116_0_0 [Uneasy Girl]]
[s][vp 8 0 0 0 4 0]...Hey, I heard from one of my[n]upperclassmen, but apparently there's[n]some kind of weirdo in Kichijoji.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Even at a glance, you can supposedly[n]tell right away that he's bad news. You[n]live there, don't you? Are you okay?[n][f 1 3 65535][w][e]

[msg MSG_117_0_0 [Curious Girl]]
[s][vp 8 0 0 0 5 0]Oh, you mean the old man in Harmony[n]Alley? My parents were talking about[n]him too...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Doesn't that just make you wonder!?[n]I'm thinking I might try looking for[n]him today...[n][f 1 3 65535][w][e]

[msg MSG_118_0_0 [Uneasy Girl]]
[s][vp 8 0 0 0 4 0]Wha, don't do that![n]Besides, I heard he hides his face...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Who knows what he'll do to you if[n]he sees you? You're gonna end up in[n]a ditch somewhere, I just know it![n][f 1 3 65535][w][e]

[msg MSG_119_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1021 65535 0]...They're probably talking about[n]that guy.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]They're spreading all these rumors.[n]I kinda feel sorry for him.[n][f 1 3 65535][w][e]

[sel SEL_120_0_0 top]
[s]"That guy"?[e]
[s]You can't blame them.[e]
[s]He's not a bad person.[e]

[msg MSG_121_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1028 65535 0]You met him just yesterday... He made an[n]offer to trade items with you, remember?[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'm not sure if he was serious about it,[n]but it's probably worth looking into[n]at least.[n][f 1 3 65535][w][e]

[msg MSG_122_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1169 65535 0]Yeah, the way he looks is pretty[n]suspicious. And the way he talks...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, his offer to trade items was pretty[n]good. Give it a try if you're feeling up[n]to it.[n][f 1 3 65535][w][e]

[msg MSG_123_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0]I know... But still, first impressions[n]count for a lot.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, his offer to trade items was pretty[n]good. I bet it'll come in handy for the[n]Phantom Thieves...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Let's use it to our advantage.[n][f 1 3 65535][w][e]

[msg MSG_124_0_0 [Uneasy Girl]]
[s][vp 8 0 0 0 4 0]...Hey, I heard from one of my[n]upperclassmen, but apparently there's[n]some kind of weirdo in Kichijoji.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Even at a glance, you can supposedly[n]tell right away that he's bad news. You[n]live there, don't you? Are you okay?[n][f 1 3 65535][w][e]

[msg MSG_125_0_0 [Curious Girl]]
[s][vp 8 0 0 0 5 0]Oh, you mean the old man in Harmony[n]Alley? My parents were talking about[n]him too...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Doesn't that just make you wonder!?[n]I'm thinking I might try looking for[n]him today...[n][f 1 3 65535][w][e]

[msg MSG_126_0_0 [Uneasy Girl]]
[s][vp 8 0 0 0 4 0]Wha, don't do that![n]Besides, I heard he hides his face...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Who knows what he'll do to you if[n]he sees you? You're gonna end up in[n]a ditch somewhere, I just know it![n][f 1 3 65535][w][e]

[msg MSG_127_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1021 65535 0]Did they say Kichijoji...?[n]Did we ever see someone like that?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]It just sounds like a rumor though,[n]so who knows how much of it you[n]can believe...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]What do you think, [f 4 2]?[n][f 1 3 65535][w][e]

[sel SEL_128_0_0 top]
[s]I'm curious.[e]
[s]He might be dangerous.[e]
[s]I don't want to get involved.[e]

[msg MSG_129_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1023 65535 0]Yeah. If on the off chance he really is[n]a bad guy, we should do something[n]about it...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]For now, we can just check it out[n]whenever we have time.[n][f 1 3 65535][w][e]

[msg MSG_130_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 1027 65535 0]I don't think it's good to make[n]assumptions... but yeah, we can't[n]rule out that possibility.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]If it's true though, then we should do[n]something about him...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]For now, we can just check it out[n]whenever we have time.[n][f 1 3 65535][w][e]

[msg MSG_131_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1028 65535 0]Come on, don't be like that...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]What if he's a bad guy? If that's true, then[n]we should do something about him.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]For now, we can just check it out[n]whenever we have time.[n][f 1 3 65535][w][e]

