[msg TOOLWIN_END_MSG_SABORI]
[s]Maybe I should stop...[n][w][e]

[msg TOOLWIN_END_MSG]
[s]Maybe I shouldn't do this today...[n][w][e]

[msg TOOLWIN_END2_MSG_SABORI [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Do you want to stop making tools[n]for today?[n][w][e]

[msg TOOLWIN_END2_MSG [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]What's wrong? Do you want to stop?[n][w][e]

[sel TOOLWIN_SEL top]
[s]Stop[e]
[s]Don't stop[e]

[msg TOOLWIN_CANCELL_STOP_MSG [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]What's wrong? Don't you want to make[n]a [f 6 1 8 0 0 39][clr 3]Lockpick[clr 27]?[n][w][e]

