[msg CMM_EVENT_OPEN]
[s][vp 1 0 0 0 0 0]Voce desbloqueou o[n]Confidente da Roda da Fortuna![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Personas fundindo da roda de[n]Fortune Arcana agora concedera[n]voce expulsa devido a explosao de Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Chihaya agora e capaz de contar[n]sua[clr 1]Sorte lendo[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_2]
[s][vp 1 0 0 0 0 0]Sua roda de confidente da fortuna[n]aumentou para[clr 2]Rank 2[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]da roda da fortuna Arcana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_3]
[s][vp 1 0 0 0 0 0]Sua roda de confidente da fortuna[n]aumentou para[clr 2]Rank 3[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]da roda da fortuna Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Chihaya agora e capaz de contar[n]sua[clr 1]Leitura de dinheiro[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_4]
[s][vp 1 0 0 0 0 0]Sua roda de confidente da fortuna[n]aumentou para[clr 2]Rank 4[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]da roda da fortuna Arcana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_5]
[s][vp 1 0 0 0 0 0]Sua roda de confidente da fortuna[n]aumentou para[clr 2]Rank 5[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]da roda da fortuna Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Chihaya agora e capaz de contar[n]sua[clr 1]Leitura de afinidade[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_6]
[s][vp 1 0 0 0 0 0]Sua roda de confidente da fortuna[n]aumentou para[clr 2]Rank 6[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]da roda da fortuna Arcana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_7]
[s][vp 1 0 0 0 0 0]Sua roda de confidente da fortuna[n]aumentou para[clr 2]Rank 7[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]da roda da fortuna Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Chihaya agora e capaz de contar[n]sua[clr 1]Leitura de destino especial[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_8]
[s][vp 1 0 0 0 0 0]Sua roda de confidente da fortuna[n]aumentou para[clr 2]Rank 8[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]da roda da fortuna Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Chihaya agora e capaz de contar[n]sua[clr 1]Leitura celestial[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_9]
[s][vp 1 0 0 0 0 0]Sua roda de confidente da fortuna[n]aumentou para[clr 2]Rank 9[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]da roda da fortuna Arcana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKMAX]
[s][vp 1 0 0 0 0 0]Sua roda de confidente da fortuna[n]aumentou para[clr 2]MAX RANK[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]da roda da fortuna Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Chihaya agora e capaz de contar[n]sua[clr 1]Leitura de vinculo especial[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_UNLOCK]
[s][vp 1 0 0 0 0 0]Agora voce pode se fundir[clr 1]Lakshmi[clr 27], Assim,[n]a persona mais poderosa de[n]A roda da fortuna Arcana.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_REVERSE]
[s][vp 1 0 0 0 0 0]Sua roda de confidente da fortuna[n]esta em um estado de duvida. Voce ira[n]nao receber seus beneficios ate[n]voce limpa seu nome.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_UPRIGHT]
[s][vp 1 0 0 0 0 0]Voce levantou o estado de duvida[n]na sua roda da fortuna confidente.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_BROKEN]
[s][vp 1 0 0 0 0 0]Sua roda de confidente da fortuna[n]agora esta quebrado. O negocio esta desligado,[n]E voce nao recebera seu[n]beneficios neste estado.[n][f 1 3 65535][w][e]

