[msg CMM_EVENT_OPEN]
[s][vp 1 0 0 0 0 0]Voce desbloqueou o[n]Confidente do homem enforcado![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Personas fusiveis dos enforcados[n]Man Arcana agora vai te dar[n]Exp devido a explosao de Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Iwai lhe deu permissao[n]usar[clr 1]Personalizacao de iniciantes[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_2]
[s][vp 1 0 0 0 0 0]Seu confidente de homem enforcado[n]aumentou para[clr 2]Rank 2[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]do homem enforcado Arcana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_3]
[s][vp 1 0 0 0 0 0]Seu confidente de homem enforcado[n]aumentou para[clr 2]Rank 3[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]do homem enforcado Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Iwai lhe deu permissao[n]usar[clr 1]Personalizacao de camuflagem[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_4]
[s][vp 1 0 0 0 0 0]Seu confidente de homem enforcado[n]aumentou para[clr 2]Rank 4[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]do homem enforcado Arcana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_5]
[s][vp 1 0 0 0 0 0]Seu confidente de homem enforcado[n]aumentou para[clr 2]Rank 5[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]do homem enforcado Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Iwai te deu um[clr 1]Desconto[clr 27][n]na personalizacao em sua loja![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_6]
[s][vp 1 0 0 0 0 0]Seu confidente de homem enforcado[n]aumentou para[clr 2]Rank 6[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]do homem enforcado Arcana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_7]
[s][vp 1 0 0 0 0 0]Seu confidente de homem enforcado[n]aumentou para[clr 2]Rank 7[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]do homem enforcado Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Iwai lhe deu permissao[n]usar[clr 1]Personalizacao de especialistas[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_8]
[s][vp 1 0 0 0 0 0]Seu confidente de homem enforcado[n]aumentou para[clr 2]Rank 8[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]do homem enforcado Arcana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_9]
[s][vp 1 0 0 0 0 0]Seu confidente de homem enforcado[n]aumentou para[clr 2]Rank 9[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]do homem enforcado Arcana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKMAX]
[s][vp 1 0 0 0 0 0]Seu confidente de homem enforcado[n]aumentou para[clr 2]MAX RANK[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Voce agora ganhara mais exp de[n]Arcana explodiu ao fundir personas[n]do homem enforcado Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Personalizacao de armas na loja de Iwai[n]agora sera[clr 1]Na casa[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_UNLOCK]
[s][vp 1 0 0 0 0 0]Agora voce pode se fundir[clr 1]Attis[clr 27], Assim,[n]a persona mais poderosa[n]do homem enforcado Arcana.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_REVERSE]
[s][vp 1 0 0 0 0 0]Seu confidente de homem enforcado esta em[n]um estado de duvida. Voce nao vai[n]receba seus beneficios ate voce[n]Limpe seu nome.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_UPRIGHT]
[s][vp 1 0 0 0 0 0]Voce levantou o estado de duvida[n]em seu confidente de homem enforcado.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_BROKEN]
[s][vp 1 0 0 0 0 0]Seu confidente de homem enforcado e agora[n]quebrado. O negocio esta desligado e voce[n]nao recebera seus beneficios em[n]este estado.[n][f 1 3 65535][w][e]

