[msg MSG_DUMMY]
[s]......[n][w][e]

[sel SPOT_SELECT_COMMON top]
[s]Go with Ryuji[e]
[s]Go with Ann[e]
[s]Go with Yusuke[e]
[s]Go with Makoto[e]
[s]Go by yourself[e]
[s]Cancel[e]

[sel SEL_SPOT_GO top]
[s]Let's go.[e]
[s]Never mind.[e]

[sel SEL_SPOT_GO_ASAKUSA top]
[s]Skytree[e]
[s]Nakamise Street[e]
[s]Cancel[e]

[msg OGIKUBO_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Ogikubo[clr 27], huh? There's a [clr 2]popular[n]ramen shop[clr 27] there. Want to go?[n][w][e]

[msg OGIKUBO_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]ramen[n]shop[clr 27] in [clr 2]Ogikubo[clr 27] with Ryuji.[n]Do you want to go again?[n][w][e]

[msg OGIKUBO_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]ramen[n]shop[clr 27] in [clr 2]Ogikubo[clr 27] with Lady Ann.[n]Do you want to go again?[n][w][e]

[msg OGIKUBO_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]ramen[n]shop[clr 27] in [clr 2]Ogikubo[clr 27] with Yusuke.[n]Do you want to go again?[n][w][e]

[msg OGIKUBO_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]ramen[n]shop[clr 27] in [clr 2]Ogikubo[clr 27] with Makoto.[n]Do you want to go again?[n][w][e]

[msg OGIKUBO_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]ramen[n]shop[clr 27] in [clr 2]Ogikubo[clr 27] with Futaba.[n]Do you want to go again?[n][w][e]

[msg OGIKUBO_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]ramen[n]shop[clr 27] in [clr 2]Ogikubo[clr 27] with Haru.[n]Do you want to go again?[n][w][e]

[msg ITIGAYA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Ichigaya[clr 27], huh? There's a [clr 2]fishing[n]pond[clr 27] there... Want to go?[n][w][e]

[msg ITIGAYA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]fishing[n]pond[clr 27] in [clr 2]Ichigaya[clr 27] with Ryuji.[n]Do you want to go again?[n][w][e]

[msg ITIGAYA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]fishing[n]pond[clr 27] in [clr 2]Ichigaya[clr 27] with Lady Ann.[n]Do you want to go again?[n][w][e]

[msg ITIGAYA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]fishing[n]pond[clr 27] in [clr 2]Ichigaya[clr 27] with Yusuke.[n]Do you want to go again?[n][w][e]

[msg ITIGAYA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]fishing[n]pond[clr 27] in [clr 2]Ichigaya[clr 27] with Makoto.[n]Do you want to go again?[n][w][e]

[msg ITIGAYA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]fishing[n]pond[clr 27] in [clr 2]Ichigaya[clr 27] with Futaba.[n]Do you want to go again?[n][w][e]

[msg ITIGAYA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]fishing[n]pond[clr 27] in [clr 2]Ichigaya[clr 27] with Haru.[n]Do you want to go again?[n][w][e]

[msg SUIDOUBASHI_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Suidobashi[clr 27], huh? That's where[n][clr 2]Dome Town[clr 27] is... Want to go?[n][w][e]

[msg SUIDOUBASHI_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Suidobashi[clr 27], huh? That's where [clr 2]Dome[n]Town[clr 27] is... but the weather's no[n]good today. Let's go elsewhere.[n][w][e]

[msg SUIDOUBASHI_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Dome[n]Town[clr 27] in [clr 2]Suidobashi[clr 27] with Ryuji.[n]Do you want to go again?[n][w][e]

[msg SUIDOUBASHI_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Dome[n]Town[clr 27] in [clr 2]Suidobashi[clr 27] with Lady Ann.[n]Do you want to go again?[n][w][e]

[msg SUIDOUBASHI_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Dome[n]Town[clr 27] in [clr 2]Suidobashi[clr 27] with Yusuke.[n]Do you want to go again?[n][w][e]

[msg SUIDOUBASHI_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Dome[n]Town[clr 27] in [clr 2]Suidobashi[clr 27] with Makoto.[n]Do you want to go again?[n][w][e]

[msg SUIDOUBASHI_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Dome[n]Town[clr 27] in [clr 2]Suidobashi[clr 27] with Futaba.[n]Do you want to go again?[n][w][e]

[msg SUIDOUBASHI_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Dome[n]Town[clr 27] in [clr 2]Suidobashi[clr 27] with Haru.[n]Do you want to go again?[n][w][e]

[msg INOKASIRA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Inokashira Park[clr 27], huh? There's a[n][clr 2]big lake[clr 27] there... Want to go?[n][w][e]

[msg INOKASIRA_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Inokashira Park[clr 27], huh? There's a [clr 2]big[n]lake[clr 27] there... but the weather's no[n]good today. Let's go elsewhere.[n][w][e]

[msg INOKASIRA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]been to the lake[clr 27][n]at [clr 2]Inokashira Park[clr 27] with Ryuji.[n]Do you want to go again?[n][w][e]

[msg INOKASIRA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]been to the lake[clr 27][n]at [clr 2]Inokashira Park[clr 27] with Lady Ann.[n]Do you want to go again?[n][w][e]

[msg INOKASIRA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]been to the lake[clr 27][n]at [clr 2]Inokashira Park[clr 27] with Yusuke.[n]Do you want to go again?[n][w][e]

[msg INOKASIRA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]been to the lake[clr 27][n]at [clr 2]Inokashira Park[clr 27] with Makoto.[n]Do you want to go again?[n][w][e]

[msg INOKASIRA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]been to the lake[clr 27][n]at [clr 2]Inokashira Park[clr 27] with Futaba.[n]Do you want to go again?[n][w][e]

[msg INOKASIRA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]been to the lake[clr 27][n]at [clr 2]Inokashira Park[clr 27] with Haru.[n]Do you want to go again?[n][w][e]

[msg INOKASIRA_COMMON_007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]been to the lake[clr 27][n]at [clr 2]Inokashira Park[clr 27] with Yoshizawa.[n]Do you want to go again?[n][w][e]

[msg INOKASIRA_COMMON_008 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]been to the lake[clr 27][n]at [clr 2]Inokashira Park[clr 27] with Sumire.[n]Do you want to go again?[n][w][e]

[msg TUKISIMA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Tsukishima[clr 27], huh? There's a[n][clr 2]monjayaki shop[clr 27] there. Want to go?[n][w][e]

[msg TUKISIMA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]monjayaki shop[clr 27] in [clr 2]Tsukishima[clr 27] with[n]Ryuji. Do you want to go again?[n][w][e]

[msg TUKISIMA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]monjayaki shop[clr 27] in [clr 2]Tsukishima[clr 27] with[n]Lady Ann. Do you want to go again?[n][w][e]

[msg TUKISIMA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]monjayaki shop[clr 27] in [clr 2]Tsukishima[clr 27] with[n]Yusuke. Do you want to go again?[n][w][e]

[msg TUKISIMA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]monjayaki shop[clr 27] in [clr 2]Tsukishima[clr 27] with[n]Makoto. Do you want to go again?[n][w][e]

[msg TUKISIMA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]monjayaki shop[clr 27] in [clr 2]Tsukishima[clr 27] with[n]Futaba. Do you want to go again?[n][w][e]

[msg TUKISIMA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]monjayaki shop[clr 27] in [clr 2]Tsukishima[clr 27] with[n]Haru. Do you want to go again?[n][w][e]

[msg HARAJUKU_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Harajuku[clr 27], huh? That's where[n][clr 2]Takenoko Street[clr 27] is. Want to go?[n][w][e]

[msg HARAJUKU_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Harajuku[clr 27], huh? That's where[n][clr 2]Takenoko Street[clr 27] is... but the[n]weather's not right for it today.[n][w][e]

[msg HARAJUKU_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Takenoko[n]Street[clr 27] in [clr 2]Harajuku[clr 27] with Ryuji.[n]Do you want to go again?[n][w][e]

[msg HARAJUKU_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Takenoko[n]Street[clr 27] in [clr 2]Harajuku[clr 27] with Lady Ann.[n]Do you want to go again?[n][w][e]

[msg HARAJUKU_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Takenoko[n]Street[clr 27] in [clr 2]Harajuku[clr 27] with Yusuke.[n]Do you want to go again?[n][w][e]

[msg HARAJUKU_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Takenoko[n]Street[clr 27] in [clr 2]Harajuku[clr 27] with Makoto.[n]Do you want to go again?[n][w][e]

[msg HARAJUKU_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Takenoko[n]Street[clr 27] in [clr 2]Harajuku[clr 27] with Futaba.[n]Do you want to go again?[n][w][e]

[msg HARAJUKU_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Takenoko[n]Street[clr 27] in [clr 2]Harajuku[clr 27] with Haru.[n]Do you want to go again?[n][w][e]

[msg IKEBUKURO_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Ikebukuro[clr 27], huh? There's a[n][clr 27]planetarium there... Want to go?[n][w][e]

[msg IKEBUKURO_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]planetarium[clr 27] in [clr 2]Ikebukuro[clr 27] with[n]Ryuji. Do you want to go again?[n][w][e]

[msg IKEBUKURO_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]planetarium[clr 27] in [clr 2]Ikebukuro[clr 27] with[n]Lady Ann. Do you want to go again?[n][w][e]

[msg IKEBUKURO_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]planetarium[clr 27] in [clr 2]Ikebukuro[clr 27] with[n]Yusuke. Do you want to go again?[n][w][e]

[msg IKEBUKURO_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]planetarium[clr 27] in [clr 2]Ikebukuro[clr 27] with[n]Makoto. Do you want to go again?[n][w][e]

[msg IKEBUKURO_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]planetarium[clr 27] in [clr 2]Ikebukuro[clr 27] with[n]Futaba. Do you want to go again?[n][w][e]

[msg IKEBUKURO_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]planetarium[clr 27] in [clr 2]Ikebukuro[clr 27] with[n]Haru. Do you want to go again?[n][w][e]

[msg AKIHABARA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Akihabara[clr 27], huh? There's[n]an [clr 2]electronics store[clr 27] there...[n]Want to go?[n][w][e]

[msg AKIHABARA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]electronics store[clr 27] in [clr 2]Akihabara[clr 27] with[n]Ryuji. Do you want to go again?[n][w][e]

[msg AKIHABARA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]electronics store[clr 27] in [clr 2]Akihabara[clr 27] with[n]Lady Ann. Do you want to go again?[n][w][e]

[msg AKIHABARA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]electronics store[clr 27] in [clr 2]Akihabara[clr 27] with[n]Yusuke. Do you want to go again?[n][w][e]

[msg AKIHABARA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]electronics store[clr 27] in [clr 2]Akihabara[clr 27] with[n]Makoto. Do you want to go again?[n][w][e]

[msg AKIHABARA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]electronics store[clr 27] in [clr 2]Akihabara[clr 27] with[n]Futaba. Do you want to go again?[n][w][e]

[msg AKIHABARA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]electronics store[clr 27] in [clr 2]Akihabara[clr 27] with[n]Haru. Do you want to go again?[n][w][e]

[msg UENO_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Ueno[clr 27], huh? There's an [clr 2]art[n]museum[clr 27] there... Want to go?[n][w][e]

[msg UENO_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]art museum[clr 27] in [clr 2]Ueno[clr 27] with Ryuji.[n]Do you want to go again?[n][w][e]

[msg UENO_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]art museum[clr 27] in [clr 2]Ueno[clr 27] with Lady Ann.[n]Do you want to go again?[n][w][e]

[msg UENO_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]art museum[clr 27] in [clr 2]Ueno[clr 27] with Yusuke.[n]Do you want to go again?[n][w][e]

[msg UENO_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]art museum[clr 27] in [clr 2]Ueno[clr 27] with Makoto.[n]Do you want to go again?[n][w][e]

[msg UENO_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]art museum[clr 27] in [clr 2]Ueno[clr 27] with Futaba.[n]Do you want to go again?[n][w][e]

[msg UENO_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]art museum[clr 27] in [clr 2]Ueno[clr 27] with Haru.[n]Do you want to go again?[n][w][e]

[msg GINZA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Ginza[clr 27], huh? There's a [clr 2]fancy sushi[n]restaurant[clr 27] there... Want to go?[n][w][e]

[msg GINZA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]fancy[n]sushi restaurant[clr 27] in [clr 2]Ginza[clr 27] with[n]Ryuji. Do you want to go again?[n][w][e]

[msg GINZA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]fancy[n]sushi restaurant[clr 27] in [clr 2]Ginza[clr 27] with[n]Lady Ann. Do you want to go again?[n][w][e]

[msg GINZA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]fancy[n]sushi restaurant[clr 27] in [clr 2]Ginza[clr 27] with[n]Yusuke. Do you want to go again?[n][w][e]

[msg GINZA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]fancy[n]sushi restaurant[clr 27] in [clr 2]Ginza[clr 27] with[n]Makoto. Do you want to go again?[n][w][e]

[msg GINZA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]fancy[n]sushi restaurant[clr 27] in [clr 2]Ginza[clr 27] with[n]Futaba. Do you want to go again?[n][w][e]

[msg GINZA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]fancy[n]sushi restaurant[clr 27] in [clr 2]Ginza[clr 27] with[n]Haru. Do you want to go again?[n][w][e]

[msg ASAKUSA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Asakusa[clr 27], huh? [clr 2]Nakamise Street[clr 27][n]and the [clr 2]Skytree[clr 27] are there...[n]Want to go?[n][w][e]

[msg ASAKUSA_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Nakamise Street[clr 27] and the [clr 2]Skytree[clr 27],[n]huh? The weather's looking pretty[n]bad today... Let's go elsewhere.[n][w][e]

[msg ASAKUSA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Nakamise[n]Street[clr 27] in [clr 2]Asakusa[clr 27] with Ryuji.[n]Do you want to go again?[n][w][e]

[msg ASAKUSA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Nakamise[n]Street[clr 27] in [clr 2]Asakusa[clr 27] with Lady Ann.[n]Do you want to go again?[n][w][e]

[msg ASAKUSA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Nakamise[n]Street[clr 27] in [clr 2]Asakusa[clr 27] with Yusuke.[n]Do you want to go again?[n][w][e]

[msg ASAKUSA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Nakamise[n]Street[clr 27] in [clr 2]Asakusa[clr 27] with Makoto.[n]Do you want to go again?[n][w][e]

[msg ASAKUSA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]Skytree[clr 27] in [clr 2]Asakusa[clr 27] with Futaba.[n]Do you want to go again?[n][w][e]

[msg ASAKUSA_COMMON_015 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Nakamise[n]Street[clr 27] in [clr 2]Asakusa[clr 27] with Futaba.[n]Do you want to go again?[n][w][e]

[msg ASAKUSA_COMMON_025 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to both the[n][clr 2]Skytree[clr 27] and [clr 2]Nakamise Street[clr 27] with[n]Futaba. What do you want to do?[n][w][e]

[msg ASAKUSA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Nakamise[n]Street[clr 27] in [clr 2]Asakusa[clr 27] with Haru.[n]Do you want to go again?[n][w][e]

[msg ASAKUSA_COMMON_007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]Skytree[clr 27] in [clr 2]Asakusa[clr 27] with Sumire.[n]Do you want to go again?[n][w][e]

[msg ASAKUSA_COMMON_008 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]Skytree[clr 27] in [clr 2]Asakusa[clr 27] with Sumire.[n]Do you want to go again?[n][w][e]

[msg JINBOUTYOU_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Jinbocho[clr 27], huh? That's where[n][clr 2]Book Town[clr 27] is... Want to go?[n][w][e]

[msg JINBOUTYOU_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Jinbocho[clr 27], huh? That's where[n][clr 2]Book Town[clr 27] is... but the weather's[n]bad today. Let's go elsewhere.[n][w][e]

[msg JINBOUTYOU_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Book[n]Town[clr 27] in [clr 2]Jinbocho[clr 27] with Ryuji.[n]Do you want to go again?[n][w][e]

[msg JINBOUTYOU_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Book[n]Town[clr 27] in [clr 2]Jinbocho[clr 27] with Lady Ann.[n]Do you want to go again?[n][w][e]

[msg JINBOUTYOU_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Book[n]Town[clr 27] in [clr 2]Jinbocho[clr 27] with Yusuke.[n]Do you want to go again?[n][w][e]

[msg JINBOUTYOU_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Book[n]Town[clr 27] in [clr 2]Jinbocho[clr 27] with Makoto.[n]Do you want to go again?[n][w][e]

[msg JINBOUTYOU_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Book[n]Town[clr 27] in [clr 2]Jinbocho[clr 27] with Futaba.[n]Do you want to go again?[n][w][e]

[msg JINBOUTYOU_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Book[n]Town[clr 27] in [clr 2]Jinbocho[clr 27] with Haru.[n]Do you want to go again?[n][w][e]

[msg ODAIBA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Odaiba Seaside Park[clr 27], huh? There's a[n][clr 2]Ferris wheel[clr 27] there... Want to go?[n][w][e]

[msg ODAIBA_COMMON_999 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Odaiba[clr 27], huh? That's where[n][clr 2]Seaside Park[clr 27] is... Want to go?[n][w][e]

[msg ODAIBA_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Odaiba[clr 27], huh? That's where [clr 2]Seaside[n]Park[clr 27] is... but the weather's pretty[n]bad today. Let's go elsewhere.[n][w][e]

[msg ODAIBA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Ferris[n]wheel[clr 27] in [clr 2]Odaiba Seaside Park[clr 27] with[n]Ryuji. Do you want to go again?[n][w][e]

[msg ODAIBA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Ferris[n]wheel[clr 27] in [clr 2]Odaiba Seaside Park[clr 27] with[n]Lady Ann. Do you want to go again?[n][w][e]

[msg ODAIBA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Ferris[n]wheel[clr 27] in [clr 2]Odaiba Seaside Park[clr 27] with[n]Yusuke. Do you want to go again?[n][w][e]

[msg ODAIBA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Ferris[n]wheel[clr 27] in [clr 2]Odaiba Seaside Park[clr 27] with[n]Makoto. Do you want to go again?[n][w][e]

[msg ODAIBA_COMMON_014 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to [clr 2]Seaside[n]Park[clr 27] in [clr 2]Odaiba[clr 27] with Makoto.[n]Do you want to go again?[n][w][e]

[msg ODAIBA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Ferris[n]wheel[clr 27] in [clr 2]Odaiba Seaside Park[clr 27] with[n]Futaba. Do you want to go again?[n][w][e]

[msg ODAIBA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Ferris[n]wheel[clr 27] in [clr 2]Odaiba Seaside Park[clr 27] with[n]Haru. Do you want to go again?[n][w][e]

[msg ODAIBA_COMMON_007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Ferris[n]wheel[clr 27] in [clr 2]Odaiba Seaside Park[clr 27] with[n]Yoshizawa. Do you want to go again?[n][w][e]

[msg YOKOHAMA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Motomachi[clr 27], huh? There's a[n][clr 2]Chinatown[clr 27] there... Want to go?[n][w][e]

[msg YOKOHAMA_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Motomachi[clr 27], huh? There's a[n][clr 2]Chinatown[clr 27] there, but the weather's[n]bad today... Let's go elsewhere.[n][w][e]

[msg YOKOHAMA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]Chinatown[clr 27] in [clr 2]Motomachi[clr 27] with[n]Ryuji. Do you want to go again?[n][w][e]

[msg YOKOHAMA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]Chinatown[clr 27] in [clr 2]Motomachi[clr 27] with[n]Lady Ann. Do you want to go again?[n][w][e]

[msg YOKOHAMA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]Chinatown[clr 27] in [clr 2]Motomachi[clr 27] with[n]Yusuke. Do you want to go again?[n][w][e]

[msg YOKOHAMA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]Chinatown[clr 27] in [clr 2]Motomachi[clr 27] with[n]Makoto. Do you want to go again?[n][w][e]

[msg YOKOHAMA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]Chinatown[clr 27] in [clr 2]Motomachi[clr 27] with[n]Futaba. Do you want to go again?[n][w][e]

[msg YOKOHAMA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]Chinatown[clr 27] in [clr 2]Motomachi[clr 27] with[n]Haru. Do you want to go again?[n][w][e]

[msg MIURAKAIGAN_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Miura[clr 27], huh? There's a[n][clr 2]beach[clr 27] there... Want to go?[n][w][e]

[msg MAIHAMA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Maihama[clr 27], huh? That's where[n][clr 2]Destinyland[clr 27] is... Want to go?[n][w][e]

[msg MAIHAMA_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Maihama[clr 27], huh? That's where[n][clr 2]Destinyland[clr 27] is... but the weather[n]isn't looking good for it today.[n][w][e]

[msg MAIHAMA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to[n][clr 2]Destinyland[clr 27] in [clr 2]Maihama[clr 27] with[n]Ryuji. Do you want to go again?[n][w][e]

[msg MAIHAMA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to[n][clr 2]Destinyland[clr 27] in [clr 2]Maihama[clr 27] with[n]Lady Ann. Do you want to go again?[n][w][e]

[msg MAIHAMA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to[n][clr 2]Destinyland[clr 27] in [clr 2]Maihama[clr 27] with[n]Yusuke. Do you want to go again?[n][w][e]

[msg MAIHAMA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to[n][clr 2]Destinyland[clr 27] in [clr 2]Maihama[clr 27] with[n]Makoto. Do you want to go again?[n][w][e]

[msg MAIHAMA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to[n][clr 2]Destinyland[clr 27] in [clr 2]Maihama[clr 27] with[n]Futaba. Do you want to go again?[n][w][e]

[msg MAIHAMA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to[n][clr 2]Destinyland[clr 27] in [clr 2]Maihama[clr 27] with[n]Haru. Do you want to go again?[n][w][e]

[msg MAIHAMA_COMMON_007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to[n][clr 2]Destinyland[clr 27] in [clr 2]Maihama[clr 27] with[n]Sumire. Do you want to go again?[n][w][e]

[msg MEIJIJINGU_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Meiji Shrine[clr 27], huh? You can[n][clr 2]pray[clr 27] there... Want to go?[n][w][e]

[msg MEIJIJINGU_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Meiji Shrine[clr 27], huh? You can [clr 2]pray[clr 27][n]there... but the weather's pretty[n]bad today. Let's go elsewhere.[n][w][e]

[msg MEIJIJINGU_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]prayed[clr 27] at[n][clr 2]Meiji Shrine[clr 27] with Ryuji.[n]Do you want to go again?[n][w][e]

[msg MEIJIJINGU_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]prayed[clr 27] at[n][clr 2]Meiji Shrine[clr 27] with Lady Ann.[n]Do you want to go again?[n][w][e]

[msg MEIJIJINGU_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]prayed[clr 27] at[n][clr 2]Meiji Shrine[clr 27] with Yusuke.[n]Do you want to go again?[n][w][e]

[msg MEIJIJINGU_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]prayed[clr 27] at[n][clr 2]Meiji Shrine[clr 27] with Makoto.[n]Do you want to go again?[n][w][e]

[msg MEIJIJINGU_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]prayed[clr 27] at[n][clr 2]Meiji Shrine[clr 27] with Futaba.[n]Do you want to go again?[n][w][e]

[msg MEIJIJINGU_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]prayed[clr 27] at[n][clr 2]Meiji Shrine[clr 27] with Haru.[n]Do you want to go again?[n][w][e]

[msg MEIJIJINGU_COMMON_007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]prayed[clr 27] at[n][clr 2]Meiji Shrine[clr 27] with Yoshizawa.[n]Do you want to go again?[n][w][e]

[msg MEIJIJINGU_COMMON_008 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already [clr 2]prayed[clr 27] at[n][clr 2]Meiji Shrine[clr 27] with Sumire.[n]Do you want to go again?[n][w][e]

[msg SHIBUYA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Shibuya[clr 27], huh? That's where the[n][clr 2]Wilton buffet[clr 27] is... Want to go?[n][w][e]

[msg SHIBUYA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Wilton[n]buffet[clr 27] in [clr 2]Shibuya[clr 27] with Ryuji.[n]Do you want to go again?[n][w][e]

[msg SHIBUYA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Wilton[n]buffet[clr 27] in [clr 2]Shibuya[clr 27] with Lady Ann.[n]Do you want to go again?[n][w][e]

[msg SHIBUYA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Wilton[n]buffet[clr 27] in [clr 2]Shibuya[clr 27] with Yusuke.[n]Do you want to go again?[n][w][e]

[msg SHIBUYA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Wilton[n]buffet[clr 27] in [clr 2]Shibuya[clr 27] with Makoto.[n]Do you want to go again?[n][w][e]

[msg SHIBUYA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Wilton[n]buffet[clr 27] in [clr 2]Shibuya[clr 27] with Futaba.[n]Do you want to go again?[n][w][e]

[msg SHIBUYA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Wilton[n]buffet[clr 27] in [clr 2]Shibuya[clr 27] with Haru.[n]Do you want to go again?[n][w][e]

[msg YONCHA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Do you want to go back[n]to [clr 2]your place[clr 27] together?[n][w][e]

[msg SINAGAWA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Shinagawa[clr 27], huh? That's where[n]the [clr 2]aquarium[clr 27] is... Want to go?[n][w][e]

[msg SINAGAWA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]aquarium[clr 27] in [clr 2]Shinagawa[clr 27] with[n]Ryuji. Do you want to go again?[n][w][e]

[msg SINAGAWA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]aquarium[clr 27][n]in [clr 2]Shinagawa[clr 27] with Lady Ann. Do you[n]want to go again?[n][w][e]

[msg SINAGAWA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]aquarium[clr 27][n]in [clr 2]Shinagawa[clr 27] with Yusuke. Do you[n]want to go again?[n][w][e]

[msg SINAGAWA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]aquarium[clr 27][n]in [clr 2]Shinagawa[clr 27] with Makoto. Do you[n]want to go again?[n][w][e]

[msg SINAGAWA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]aquarium[clr 27][n]in [clr 2]Shinagawa[clr 27] with Futaba. Do you[n]want to go again?[n][w][e]

[msg SINAGAWA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the[n][clr 2]aquarium[clr 27] in [clr 2]Shinagawa[clr 27] with[n]Haru. Do you want to go again?[n][w][e]

[msg SINAGAWA_COMMON_007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]aquarium[clr 27][n]in [clr 2]Shinagawa[clr 27] with Yoshizawa. Do you[n]want to go again?[n][w][e]

[msg SINAGAWA_COMMON_008 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]aquarium[clr 27][n]in [clr 2]Shinagawa[clr 27] with Sumire. Do you[n]want to go again?[n][w][e]

[msg NAKANO_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Nakano[clr 27], huh? That's where the[n][clr 2]Commerce Building District[clr 27] is...[n]Want to go?[n][w][e]

[msg NAKANO_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Commerce[n]Building District[clr 27] in [clr 2]Nakano[clr 27] with Ryuji.[n]Do you want to go again?[n][w][e]

[msg NAKANO_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Commerce[n]Building District[clr 27] in [clr 2]Nakano[clr 27] with Lady Ann.[n]Do you want to go again?[n][w][e]

[msg NAKANO_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Commerce[n]Building District[clr 27] in [clr 2]Nakano[clr 27] with Yusuke.[n]Do you want to go again?[n][w][e]

[msg NAKANO_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Commerce[n]Building District[clr 27] in [clr 2]Nakano[clr 27] with Makoto.[n]Do you want to go again?[n][w][e]

[msg NAKANO_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Commerce[n]Building District[clr 27] in [clr 2]Nakano[clr 27] with Futaba.[n]Do you want to go again?[n][w][e]

[msg NAKANO_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Commerce[n]Building District[clr 27] in [clr 2]Nakano[clr 27] with Haru.[n]Do you want to go again?[n][w][e]

[msg NAKANO_COMMON_007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Commerce[n]Building District[clr 27] in [clr 2]Nakano[clr 27] with Yoshizawa.[n]Do you want to go again?[n][w][e]

[msg NAKANO_COMMON_008 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You've already been to the [clr 2]Commerce[n]Building District[clr 27] in [clr 2]Nakano[clr 27] with Sumire.[n]Do you want to go again?[n][w][e]

[msg MSG_SPOT_DUMMY [Morgana]]
[s]Dummy MSG_SPOT_DUMMY[n][w][e]

[msg MSG_RYUJI_SPOT_OGIKUBO [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 0 65535 0]Oh, that ramen place!? Sure,[n]I'm pretty damn hungry.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 7051 65535 0]Mkay, let's get goin'![n][w][e]

[msg MSG_RYUJI_SPOT_OGIKUBO_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 7052 65535 0]You're totally diggin' that[n]ramen, huh? Mkay, let's go![n][w][e]

[msg MSG_RYUJI_SPOT_TUKISHIMA [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10]Oh, you wanna go to that[n]monja shop? Let's make some[n]tasty memories, dude.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 7051 65535 0]Mkay, let's get goin'![n][w][e]

[msg MSG_RYUJI_SPOT_TUKISHIMA_2 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 7052 65535 0]Monja's best when it's[n]burnin' the roof of your[n]mouth. C'mon, let's go![n][w][e]

[msg MSG_RYUJI_SPOT_AKIHABARA [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10]The electronics store? I guess it's[n]pretty fun goin' there. Let's go[n]look at some exercise machines![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 7051 65535 0]Mkay, let's get goin'![n][w][e]

[msg MSG_RYUJI_SPOT_AKIHABARA_2 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 7052 65535 0]Ain't it weird how you wanna look[n]at electronics even though you[n]can't buy 'em? Anyways, let's go![n][w][e]

[msg MSG_RYUJI_SPOT_SUIDOUBAS [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10]Isn't that place all couples?[n]Well, as long as it's fun...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 7051 65535 0]Anyways, let's go. We're gonna[n]conquer that roller coaster![n][w][e]

[msg MSG_RYUJI_SPOT_SUIDOUBAS_2 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 7052 65535 0]Sweet, we're gonna have some[n]fun today! Let's get goin'![n][w][e]

[msg MSG_RYUJI_SPOT_YOKOHAMA [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10]Niiice, I'm game for some[n]all-you-can-eat Chinese food.[n]Let's stuff our faces, dude.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 7051 65535 0]Mkay, let's get goin'![n][w][e]

[msg MSG_RYUJI_SPOT_YOKOHAMA_ [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 7052 65535 0]I'll never get tired of goin'[n]there! C'mon, let's go![n][w][e]

[msg MSG_RYUJI_SPOT_NAKANO [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10]Nakano, huh... I guess we can go check it[n]out.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 7051 65535 0]Alright, let's go![n][w][e]

[msg MSG_RYUJI_SPOT_NAKANO_02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 7052 65535 0]I'll never get tired of goin'[n]there! C'mon, let's go![n][w][e]

[msg MSG_ANNE_SPOT_INOKASIRA [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10]Inokashira Park? Okay.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 6052 65535 0]I like it there too. Let's go![n][w][e]

[msg MSG_ANNE_SPOT_INOKASIRA_ [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10][vp 8 2 1 6023 65535 0]Yeah, Inokashira Park sounds[n]really nice. Let's go![n][w][e]

[msg MSG_ANNE_SPOT_HARAJUKU [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10]Harajuku... How about Takenoko[n]Street? It'd be great if you[n]could come shopping with me.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 6052 65535 0]Even just going for the[n]people watching is interesting.[n]Anyway, let's go![n][w][e]

[msg MSG_ANNE_SPOT_HARAJUKU_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10][vp 8 2 1 6023 65535 0]Okay, Takenoko Street sounds great.[n][w][e]

[msg MSG_ANNE_SPOT_IKEBUKURO [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10]I've been wanting to go to the[n]planetarium for ages! Ikebukuro[n]isn't too far away either.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 6052 65535 0]Let's go![n][w][e]

[msg MSG_ANNE_SPOT_IKEBUKURO_ [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10][vp 8 2 1 6023 65535 0]Yeah, let's do it. That[n]planetarium's great.[n][w][e]

[msg MSG_ANNE_SPOT_BUFFET [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10]That buffet we went to before?[n]I'll need you to make sure I[n]don't eat too much, okay?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 6052 65535 0]Let's go![n][w][e]

[msg MSG_ANNE_SPOT_BUFFET_02 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10][vp 8 2 1 6023 65535 0]Sounds good. Just don't[n]let me eat too much![n][w][e]

[msg MSG_ANNE_SPOT_MAIHAMA [Ann]]
[s][bup 0 4 6 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10]Whoa, really!? I'm so happy you[n]asked! Let's go enjoy ourselves![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 6052 65535 0]Let's go![n][w][e]

[msg MSG_ANNE_SPOT_MAIHAMA_02 [Ann]]
[s][bup 0 4 6 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10][vp 8 2 1 6023 65535 0]Of course I'll go with you![n]I'm gonna savor this trip![n][w][e]

[msg MSG_ANNE_SPOT_KANRANSYA [Ann]]
[s][bup 0 4 6 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10]Yeah, the Ferris wheel sounds[n]lovely. It'll be nice spending[n]some time just the two of us...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 6052 65535 0]Let's go![n][w][e]

[msg MSG_ANNE_SPOT_KANRANSYA_ [Ann]]
[s][bup 0 4 6 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10][vp 8 2 1 6023 65535 0]Yeah, let's go! The view from[n]up there was really pretty.[n]I'd love to see it again.[n][w][e]

[msg MSG_ANNE_SPOT_UENO [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10]The art museum? Sure. I could[n]probably learn a thing or two[n]about modeling while we're there.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 6052 65535 0]Let's go![n][w][e]

[msg MSG_ANNE_SPOT_UENO_02 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10][vp 8 2 1 6023 65535 0]Yeah, it's a great opportunity[n]for me to study. Let's go![n][w][e]

[msg MSG_YUSUKE_SPOT_OGIKUBO [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10]Hm... Ramen in Ogikubo? I was[n]just beginning to feel peckish.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 4059 65535 0]Let us depart at once.[n][w][e]

[msg MSG_YUSUKE_SPOT_OGIKUBO_ [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10][vp 8 2 1 4060 65535 0]Mm... I was just thinking[n]about my desire to have[n]that again. Let us go.[n][w][e]

[msg MSG_YUSUKE_SPOT_UENO [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10]Ah yes, gazing upon the work[n]of the masters... You have such[n]interesting ideas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 4059 65535 0]Well then, let us be off.[n][w][e]

[msg MSG_YUSUKE_SPOT_UENO_02 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10][vp 8 2 1 4060 65535 0]Yes, let us go forth and[n]study the great classics.[n][w][e]

[msg MSG_YUSUKE_SPOT_IKEBUKUR [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 204 3 10 0 10]The planetarium, hm? That[n]may be a good place for me[n]to make new discoveries.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 4059 65535 0]Let's go, [f 4 2].[n][w][e]

[msg MSG_YUSUKE_SPOT_IKEBUKUR_2 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10][vp 8 2 1 4060 65535 0]Very well. The stars provide[n]great inspiration for my[n]art. Now then, let us go.[n][w][e]

[msg MSG_YUSUKE_SPOT_JINBO [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10]Ah, you think we could look[n]for art books there? I hope[n]there are some good ones.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 4059 65535 0]Let us depart at once.[n][w][e]

[msg MSG_YUSUKE_SPOT_JINBO_02 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10][vp 8 2 1 4060 65535 0]You want to look for the hidden[n]gem that is a wonderful art book?[n]Very well, let us depart.[n][w][e]

[msg MSG_YUSUKE_SPOT_MEIJIJIN [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10]A shrine, hm? Experiencing[n]traditional culture may be nice.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 4059 65535 0]Let us go. I'll be counting[n]on you to lead the way.[n][w][e]

[msg MSG_YUSUKE_SPOT_MEIJIJIN_2 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10][vp 8 2 1 4060 65535 0]Another meditation session at the[n]shrine sounds superb. Let us go.[n][w][e]

[msg MSG_YUSUKE_SPOT_SINAGAWA [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10]Hm, an aquarium... Let us go and be awed[n]by the beautiful movements of the fish.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 4059 65535 0]Let us go. I'll be counting[n]on you to lead the way.[n][w][e]

[msg MSG_YUSUKE_SPOT_SINAGAWA_2 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10][vp 8 2 1 4060 65535 0]Perhaps I can create a new painting in[n]my mind by observing. Let us get going.[n][w][e]

[msg MSG_MAKOTO_SPOT_OGIKUBO [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10]Hm, I haven't been to a[n]ramen shop in a long time...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]It would be nice to go again.[n]Can I ask that you show me[n]where it is?[n][w][e]

[msg MSG_MAKOTO_SPOT_OGIKUBO_ [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]Sure. The flavor of that[n]ramen is honestly addicting...[n][w][e]

[msg MSG_MAKOTO_SPOT_TUKISIMA [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10]Monjayaki... I've actually never[n]had it before. I'm interested in[n]giving it a try though.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]Could you take me there, [f 4 2]?[n][w][e]

[msg MSG_MAKOTO_SPOT_TUKISIMA_2 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]Sure. We can think about what[n]we want to get on our way there.[n][w][e]

[msg MSG_MAKOTO_SPOT_HARAJUKU [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10]I've actually never been to[n]Takenoko Street... This is a good[n]opportunity for a new experience.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]Please lead the way.[n][w][e]

[msg MSG_MAKOTO_SPOT_HARAJUKU_2 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]I still haven't quite had[n]enough of that place. Let's go.[n][w][e]

[msg MSG_MAKOTO_SPOT_SUIDOUBA [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 202 3 10 0 10]Dome Town... I've heard of it,[n]but this will actually be my[n]first time going there.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]You can lead the way.[n][w][e]

[msg MSG_MAKOTO_SPOT_SUIDOUBA_2 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]Sure, I could go there as many[n]times as you ask me. Let's go.[n][w][e]

[msg MSG_MAKOTO_SPOT_YOKOHAMA [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10]Good idea. I've truthfully been[n]curious about going there myself.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]Let's depart.[n][w][e]

[msg MSG_MAKOTO_SPOT_YOKOHAMA_2 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]I love the foreign feel of[n]being there. Let's go.[n][w][e]

[msg MSG_MAKOTO_SPOT_MAIHAMA [Makoto]]
[s][bup 0 6 6 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10]Hehe, I'm sure going with you[n]will be quite fun. Let's enjoy[n]a leisurely day out together.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]We should get going.[n][w][e]

[msg MSG_MAKOTO_SPOT_MAIHAMA_ [Makoto]]
[s][bup 0 6 6 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]Sure, I would love relaxing with[n]you in the kingdom of dreams.[n][w][e]

[msg MSG_MAKOTO_SPOT_KANRANSY [Makoto]]
[s][bup 0 6 6 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10]I don't think I've ever ridden a[n]Ferris wheel... I'm a bit nervous.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]Well, shall we go?[n][w][e]

[msg MSG_MAKOTO_SPOT_KANRANSY_2 [Makoto]]
[s][bup 0 6 6 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]That sounds good. I would love[n]another chance to appreciate the[n]view with you, [f 4 2]...[n][w][e]

[msg MSG_MAKOTO_SPOT_ODAIBA [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10]I don't know much about Odaiba,[n]but that sounds like fun.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]Let's go.[n][w][e]

[msg MSG_MAKOTO_SPOT_ODAIBA_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]Yeah, the scenery there[n]was lovely. Let's go.[n][w][e]

[msg MSG_FUTABA_SPOT_ASAKUSA_ [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 209 3 10 0 10]The Skytree? 'Kay![n]High places are fun.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]Can you show me how to[n]get there [f 4 2]?[n][w][e]

[msg MSG_FUTABA_SPOT_ASAKUSA__2 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]The view last time was freaking[n]awesome... I'll go with you.[n][w][e]

[msg MSG_FUTABA_SPOT_ASAKUSA__3 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]That's a famous tourist[n]spot, right? I wonder[n]what it's like there...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]Okay, let's go![n][w][e]

[msg MSG_FUTABA_SPOT_ASAKUSA__4 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]...I'll go! I'm gonna eat[n]all the food there is![n][w][e]

[msg MSG_FUTABA_SPOT_HARAJUKU [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]Takenoko Street...!?[n][w][e]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]N-No, it's fine... Let's go![n][w][e]

[msg MSG_FUTABA_SPOT_HARAJUKU_2 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]Takenoko Street... It'll be[n]Okay, I promise. Let's go.[n][w][e]

[msg MSG_FUTABA_SPOT_AKIHABAR [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]A-A-Akihabaraaa! It's the best![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]I'm so happy! This is gonna[n]be so much fun! Let's go![n][w][e]

[msg MSG_FUTABA_SPOT_AKIHABAR_2 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]Akihabara sounds perfect![n]There's stuff I wanna see there![n][w][e]

[msg MSG_FUTABA_SPOT_INOKASIR [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]It's just a park, right? Quiet[n]places like that should be fine.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]I'm game. Let's go![n][w][e]

[msg MSG_FUTABA_SPOT_INOKASIR_2 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]It's really relaxing there.[n]I'll gladly go with you.[n][w][e]

[msg MSG_FUTABA_SPOT_KANRANSY [Futaba]]
[s][bup 0 8 6 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]Being alone together on the Ferris[n]wheel...? Piece of cake. I think[n]I'd really like that, actually.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]Let's go! I'm gonna be[n]a great girlfriend![n][w][e]

[msg MSG_FUTABA_SPOT_KANRANSY_2 [Futaba]]
[s][bup 0 8 6 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]Sure, I'll go. We can be alone[n]together on the Ferris wheel...[n][w][e]

[msg MSG_FUTABA_SPOT_YOKOHAMA [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]Chinatown!? I-It'll be fine...[n]They speak Japanese, right...?[n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]I-I'll go though. I'm excited![n][w][e]

[msg MSG_FUTABA_SPOT_YOKOHAMA_2 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]I wanna explore Chinatown some[n]more... I'll go with you.[n][w][e]

[msg MSG_FUTABA_SPOT_MAIHAMA [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]Oof... There are lots of[n]people there, right?[n][w][e]
[s][bup 0 8 6 65535 0][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]But... I'll be okay on a date![n][w][e]

[msg MSG_FUTABA_SPOT_MAIHAMA_ [Futaba]]
[s][bup 0 8 6 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]Yeah, I wanna go! Crowds of[n]people are nothing to me when[n]we're together...![n][w][e]

[msg MSG_FUTABA_SPOT_NAKANO [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]Oh, Nakano! That's my holy land![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]I'm so happy! This is gonna[n]be so much fun! Let's go![n][w][e]

[msg MSG_FUTABA_SPOT_NAKANO_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]Nakano sounds great! There's something[n]I wanna check out there![n][w][e]

[msg MSG_HARU_SPOT_OGIKUBO [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]Ogikubo's ramen is famous, yes?[n]I've always wanted to try it.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]All right, let's head over there.[n][w][e]

[msg MSG_HARU_SPOT_OGIKUBO_02 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]Sure, I would love some more of[n]that ramen. Let's go, [f 4 2]-kun.[n][w][e]

[msg MSG_HARU_SPOT_TUKISHIMA [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]Monjayaki? I... don't think[n]I've ever had it.[n][w][e]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]I wonder what it tastes like.[n]Let's go find out![n][w][e]

[msg MSG_HARU_SPOT_TUKISHIMA_ [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]Sure, I want to try cooking[n]it myself again! Let's go.[n][w][e]

[msg MSG_HARU_SPOT_HARAJUKU [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]Takenoko Street? Looking at all[n]the stores there does sound nice.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]All right, let's head over there.[n][w][e]

[msg MSG_HARU_SPOT_HARAJUKU_0 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]Sure, let's head over. There's[n]actually a store there I've[n]been meaning to check out.[n][w][e]

[msg MSG_HARU_SPOT_AKIHABARA [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]An electronics store? I look[n]forward to seeing what kind[n]of things they have there.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]All right, let's head over there.[n][w][e]

[msg MSG_HARU_SPOT_AKIHABARA_ [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]Sure. Just going and looking[n]around is fun, don't you think?[n][w][e]

[msg MSG_HARU_SPOT_GINZA [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]Oh, the place in Ginza?[n]I love the sushi there.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]All right, let's head over there.[n][w][e]

[msg MSG_HARU_SPOT_GINZA_02 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]Yes, the shrimp there is[n]absolutely delectable. Let's go.[n][w][e]

[msg MSG_HARU_SPOT_MAIHAMA [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]Oh, I'm so glad you asked! We[n]have the day off today, so we[n]can take our time and have fun.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]All right, let's head over there.[n][w][e]

[msg MSG_HARU_SPOT_MAIHAMA_02 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]Yay! Let's walk around[n]and see all the sights![n][w][e]

[msg MSG_HARU_SPOT_KANRANSYA [Haru]]
[s][bup 0 7 206 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]I might get a little embarrassed[n]alone on the Ferris wheel with[n]you... Not that I mind.[n][w][e]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]Um... let's go.[n][w][e]

[msg MSG_HARU_SPOT_KANRANSYA_ [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]Sure, I've been hoping we could[n]ride the Ferris wheel together[n]again. Let's go, [f 4 2]-kun.[n][w][e]

[msg MSG_HARU_SPOT_MEIJIJINGU [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]I've always wanted to get a good[n]look at the grounds there. It's[n]such a wonderful shrine.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]All right, let's head over there.[n][w][e]

[msg MSG_HARU_SPOT_MEIJIJINGU_2 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]Can't you just feel the history[n]there? Well, let's go.[n][w][e]

[msg MSG_KASUMI_SPOT_MEIJIJIN [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]That sounds great! It's good[n]to pray every now and then.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57087 65535 0]Shall we get going?[n][w][e]

[msg MSG_SUMIRE_SPOT_MEIJIJIN [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]That's a great idea! I always go and pray[n]when there's something important I need[n]to do.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57087 65535 0]Let's get going![n][w][e]

[msg MSG_KASUMI_SPOT_MEIJIJIN_2 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Okay! I've been feeling so much better[n]since the last time I prayed there![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57087 65535 0]Shall we get going?[n][w][e]

[msg MSG_SUMIRE_SPOT_MEIJIJIN_2 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Sounds great! I'm sure the gods and[n]goddesses will hear our wishes again![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57087 65535 0]Let's go![n][w][e]

[msg MSG_KASUMI_SPOT_SKYTREE [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57086 65535 0]Oh! I'd love to go up there! It may not[n]seem like it, but I really like heights![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Shall we get going?[n][w][e]

[msg MSG_SUMIRE_SPOT_SKYTREE [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57086 65535 0]Oh, that one tall building! Sure, I love[n]heights![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Let's get going![n][w][e]

[msg MSG_KASUMI_SPOT_SKYTREE_ [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]That sounds great! I can't wait to[n]see the view from up there again![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57067 65535 0]Let's head on over![n][w][e]

[msg MSG_SUMIRE_SPOT_SKYTREE_ [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Okay! The view from up there is amazing![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57069 65535 0]Let's get going![n][w][e]

[msg MSG_KASUMI_SPOT_INOKASHI [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57086 65535 0]Great! I love that place![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Let's go![n][w][e]

[msg MSG_SUMIRE_SPOT_INOKASHI [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57086 65535 0]I really like boats. They're[n]great for balance training, too.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Let's get going![n][w][e]

[msg MSG_KASUMI_SPOT_INOKASHI_2 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Sure! Let's go surround ourselves with[n]nature. I could use some of that energy![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57068 65535 0]Let's get going![n][w][e]

[msg MSG_SUMIRE_SPOT_INOKASHI_2 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]We're going on that boat again? I'm so glad[n]you remembered that I like to go there![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57068 65535 0]Now then, let's get going![n][w][e]

[msg MSG_KASUMI_SPOT_YOKOHAMA [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]I've never been there before! Let's see[n]if we can visit every single store![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57068 65535 0]Let's hurry over![n][w][e]

[msg MSG_SUMIRE_SPOT_YOKOHAMA [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Oh, it'll be my first time going there! I[n]wonder if we can go to all the stores![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57068 65535 0]Now then. Let's go![n][w][e]

[msg MSG_KASUMI_SPOT_YOKOHAMA_2 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]I've been craving Chinese food! Let's make[n]sure we go to every store this time![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57067 65535 0]Let's get going![n][w][e]

[msg MSG_SUMIRE_SPOT_YOKOHAMA_2 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]I've been wanting Chinese food all day![n]We'll have to do our best to visit every[n]store this time around![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57067 65535 0]Let's get going![n][w][e]

[msg MSG_KASUMI_SPOT_SHINAGAW [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]I love aquariums! I hope there're penguins...[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57067 65535 0]Let's go![n][w][e]

[msg MSG_SUMIRE_SPOT_SHINAGAW [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Aquariums are the best! I wonder[n]if we'll get to see some penguins.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57067 65535 0]C'mon, Senpai! Let's get going![n][w][e]

[msg MSG_KASUMI_SPOT_SHINAGAW_2 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]I just recently saw giant squid special[n]on TV, and I've been wanting to go[n]there ever since![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57068 65535 0]Let's go![n][w][e]

[msg MSG_SUMIRE_SPOT_SHINAGAW_2 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Oh! I've been wanting to go there ever[n]since I saw a giant squid special on TV a[n]while back![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57068 65535 0]Let's get going![n][w][e]

[msg MSG_SUMIRE_SPOT_MAIHAMA [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]I want to go on the thrill rides! I think[n]I'll be okay if I'm with you, Senpai...[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57093 65535 0]Let's hurry over there![n][w][e]

[msg MSG_SUMIRE_SPOT_MAIHAMA_ [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Spending time with my boyfriend at the[n]land of dreams... This time, let's take our[n]time going around.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57093 65535 0]Let's head over now.[n][w][e]

[msg MSG_SUMIRE_SPOT_ODAIBA [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57058 65535 0]It's been so long since I've been on a[n]Ferris wheel![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]C'mon, Senpai. Let's go![n][w][e]

[msg MSG_SUMIRE_SPOT_ODAIBA_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57076 65535 0]I'm so happy that I get to ride the[n]Ferris wheel with you again.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Let's head over, Senpai.[n][w][e]

[msg MSG_SUMIRE_SPOT_MYROOM [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]As long as I'm with you, even just[n]sitting and talking can be fun.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57093 65535 0]Let's go.[n][w][e]

[msg MSG_SUMIRE_SPOT_MYROOM_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]I love how your room has the scent[n]of coffee...[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57093 65535 0]Let's head over.[n][w][e]

[msg MSG_MONEY_SHORTAGE_FARE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hm, you don't have enough money.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Planning is important if you want[n]to be a good thief, you know.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh well. I'll use my secret[n]savings to cover your return trip.[n][w][e]

[msg MND_MONEY_SHORTAGE_FARE]
[s]I don't have enough for the train fare...[n][w][e]
[s]Oh yeah...[n][w][e]
[s]Morgana gave me some of his savings...[n]I should be careful how I spend it...[n][e]

[msg MSG_NO_MONEY]
[s]I don't have enough money[n]for a round trip fare...[n][w][e]

[msg MSG_ERROR_DISABLE_KF [Morgana]]
[s]There's no reason for me[n]to go there right now...[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT [Morgana]]
[s]I should bring someone[n]here sometime...[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Huh. I dunno, it ain't bad but...[n]maybe we should go somewhere else.[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_A [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6032 65535 0]Um... sorry, but do you think[n]we could go somewhere else?[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_Y [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4111 65535 0]I do not have interest in such[n]a location... My apologies, but[n]could you pick another spot?[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_M [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2128 65535 0]Well... I appreciate the offer,[n]but do you think there's anywhere[n]else we could go instead?[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_F [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9113 65535 0]Can we not? I think I[n]wanna go somewhere else.[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_H [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 3032 65535 0]Um, sorry for saying this but...[n]if I'm going somewhere with you,[n]I'd rather it be a different spot.[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_K [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57037 65535 0]Um... Sorry, but can we go somewhere else?[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_S [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57037 65535 0]Sorry, but would it be okay if we go[n]somewhere else?[n][w][e]

[msg MSG_ERROR_SPOT_SHIBUYA]
[s]This is where we went to[n]that buffet. I should bring[n]someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_YONCHA]
[s]It's still a little early for[n]me to go back to Leblanc...[n][w][e]

[msg MSG_ERROR_SPOT_AOYAMA]
[s]I don't have any reason to be[n]going to school right now...[n][w][e]

[msg MSG_ERROR_SPOT_SHINJUKU]
[s]I don't have any reason to be[n]going to Shinjuku right now...[n][w][e]

[msg MSG_ERROR_SPOT_AKIBA]
[s]There's a large electronics store[n]near this station. I should bring[n]someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_KANDA]
[s]There's nothing for me to[n]do in Kanda right now...[n][w][e]

[msg MSG_ERROR_SPOT_KANDA_NIG]
[s]There's nothing for me to do in[n]Kanda right now... I should comeback during the day...[n][w][e]

[msg MSG_ERROR_SPOT_HARAJYUKU]
[s]Takenoko Street is right near[n]this station. I should bring[n]someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_IKEBUKURO]
[s]I know of a planetarium right[n]near this station. I should[n]bring someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_AKIBA_SPO]
[s]There's a large electronics store[n]near this station. I should bring[n]someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_UENO]
[s]There are lots of art museums near[n]this station. I should take someone[n]to check them out sometime...[n][w][e]

[msg MSG_ERROR_SPOT_OGIKUBO]
[s]This station is near a famous[n]ramen shop. I should go eat[n]with someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_ICHIGAYA]
[s]There's a fishing pond next to[n]this station. I should go fish[n]with someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_INOKASIRA]
[s]This is where Inokashira[n]Park is. I should bring[n]someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_NAGATACHO]
[s]The National Diet Building is[n]by this station. I don't have[n]any reason to go there now...[n][w][e]

[msg MSG_ERROR_SPOT_GINZA]
[s]I know of a fancy sushi[n]restaurant near here. I should[n]bring someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_ASAKUSA]
[s]The Skytree and Nakamise Street[n]are near here. I should bring[n]someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_KORAKUEN]
[s]Dome Town is right by this[n]station. I should bring[n]someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_JINBOCHO]
[s]There's a shopping district full[n]of bookshops nearby. I should[n]bring someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_JINBOCHO_]
[s]There's a shopping district full[n]of bookshops nearby. I should go[n]there with someone during the day...[n][w][e]

[msg MSG_ERROR_SPOT_TUKISIMA]
[s]There's a monjayaki shop close[n]to this station. I should bring[n]someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_KAIHINPAR]
[s]There's a park and Ferris wheel[n]near this station. I should bring[n]someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_KAIHINPAR_2]
[s]There's a park and Ferris wheel[n]near this station. I should bring[n]someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_AKASAKA]
[s]This is near the TV station I went[n]to on my social studies trip. I[n]don't need to go there now...[n][w][e]

[msg MSG_ERROR_SPOT_YOKOHAMA]
[s]Chinatown is close to this station.[n]I should bring someone there for[n]Chinese food on my day off...[n][w][e]

[msg MSG_ERROR_SPOT_BEACH]
[s]This is where we all went to[n]the beach together. Beach[n]season is over now...[n][w][e]

[msg MSG_ERROR_SPOT_ROPPONGI]
[s]This is the station near the[n]Okumura Foods Corporate HQ. I[n]have no business there now...[n][w][e]

[msg MSG_ERROR_SPOT_MAIHAMA]
[s]This is right near Destinyland.[n]I should go there with someone[n]when I have a day off...[n][w][e]

[msg MSG_ERROR_SPOT_MAIHAMA_S]
[s]This is right near[n]Destinyland. I should bring[n]someone there sometime...[n][w][e]

[msg MSG_ERROR_SPOT_MEIJI_JIN]
[s]Meiji Shrine is really close to[n]this station. I should come pray[n]with someone sometime...[n][w][e]

[msg MSG_ERROR_SPOT_MEIJI_JIN_2]
[s]Meiji Shrine is really close to[n]this station. I should come pray[n]with someone during the day...[n][w][e]

[msg MSG_ERROR_SPOT_NAKANO]
[s]This station is filled with unique cultural[n]sites. I should bring someone here[n]sometime.[n][w][e]

[msg MSG_ERROR_SPOT_SINAGAWA]
[s]This station is known for its hotels and[n]aquarium. I should bring someone with[n]me next time.[n][w][e]

[msg MSG_ERROR_SPOT_SHIBUYA_L]
[s]This is where we went to that[n]buffet. I should go eat with[n]someone next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_AKIBA_LAS]
[s]There's a large electronics store[n]near here. I should come with[n]someone next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_HARAJYUKU_2]
[s]Takenoko Street is right near[n]this station. I should come with[n]someone next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_IKEBUKURO_2]
[s]I know of a planetarium right near[n]this station. I should come with[n]someone next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_AKIBA_SPO_2]
[s]There's a large electronics store[n]near here. I should come with[n]someone next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_UENO_LAST]
[s]There are lots of art museums near[n]this station. I should come with[n]someone next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_OGIKUBO_L]
[s]This station is near a famous[n]ramen shop. I should go eat with[n]someone next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_ICHIGAYA_]
[s]There's a fishing pond next to[n]this station. I should go fish with[n]someone next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_INOKASIRA_2]
[s]This is where Inokashira Park[n]is. I should bring someone there[n]next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_GINZA_LAS]
[s]I know of a fancy sushi restaurant[n]near here. I should bring someone[n]next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_ASAKUSA_L]
[s]The Skytree and Nakamise Street[n]are near here. I should bring[n]someone next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_KORAKUEN_]
[s]Dome Town is right by this[n]station. I should bring someone[n]next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_JINBOCHO__2]
[s]There are lots of bookshops near[n]here. I should bring someone[n]next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_TUKISIMA_]
[s]There's a monjayaki shop close[n]to this station. I should bring[n]someone next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_KAIHINPAR_3]
[s]There's a park and Ferris wheel[n]near here. I should bring someone[n]next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_YOKOHAMA_]
[s]Chinatown is close to this station.[n]I should take someone to eat there[n]next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_MAIHAMA_L]
[s]This is right near Destinyland.[n]I should bring someone there[n]next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_MEIJI_JIN_3]
[s]Meiji Shrine is really close to[n]this station. I should go pray with[n]someone next time I'm in Tokyo...[n][w][e]

[msg MSG_ERROR_SPOT_NAKANO_LA]
[s]This station is filled with unique cultural[n]sites. I should bring someone with me[n]next time I'm in Tokyo.[n][w][e]

[msg MSG_ERROR_SPOT_SINAGAWA_]
[s]This station is known for its hotels and[n]aquarium. I should bring someone with[n]me next time I'm in Tokyo.[n][w][e]

[msg MSG_RYUJI_SPOT_CANCEL [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7063 65535 0]Dude, way to be a downer.[n][w][e]

[msg MSG_ANNE_SPOT_CANCEL [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6063 65535 0]Oh, that's too bad.[n][w][e]

[msg MSG_YUSUKE_SPOT_CANCEL [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4026 65535 0]I see. That's disappointing...[n][w][e]

[msg MSG_MAKOTO_SPOT_CANCEL [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2120 65535 0]Oh... Did you change your mind?[n][w][e]

[msg MSG_FUTABA_SPOT_CANCEL [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9062 65535 0]Don't waffle on me![n][w][e]

[msg MSG_HARU_SPOT_CANCEL [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 3063 65535 0]Oh... okay.[n][w][e]

