[msg baton_touch_help_000]
[s]Baton Pass Help Blank[n][e]

[msg baton_touch_help_101]
[s]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_102]
[s]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_103]
[s]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_201]
[s]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_202]
[s]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_203]
[s]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_301]
[s]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_302]
[s]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_303]
[s]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_401]
[s]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_402]
[s]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_403]
[s]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_501]
[s]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_502]
[s]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_503]
[s]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_601]
[s]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_602]
[s]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_603]
[s]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_701]
[s]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_702]
[s]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_703]
[s]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_801]
[s]Dummy data (Futaba's is unused)[n][e]

[msg baton_touch_help_802]
[s]Dummy data (Futaba's is unused)[n][e]

[msg baton_touch_help_803]
[s]Dummy data (Futaba's is unused)[n][e]

[msg baton_touch_help_901]
[s]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_902]
[s]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_903]
[s]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

[msg baton_touch_help_A01]
[s]Slightly increases attack after a[n]Baton Pass.[n][e]

[msg baton_touch_help_A02]
[s]Increases the effect of a Baton Pass[n]and slightly heals HP.[n][e]

[msg baton_touch_help_A03]
[s]Increases effect of Baton Pass and[n]HP recovered. SP will be slightly[n]recovered after 3rd Baton Pass.[n][e]

