[msg MSG_NML08_02_FIND_01_01]
[s]Who is that!?[n][f 1 2 65535][e]

[msg MSG_NML08_02_FIND_01_02]
[s]Huh? Who are you!?[n][f 1 2 65535][e]

[msg MSG_NML08_02_FIND_01_03]
[s]What are you doing here?[n][f 1 2 65535][e]

[msg MSG_NML08_02_FIND_01_04]
[s]Are you a fugitive!?[n][f 1 2 65535][e]

[msg MSG_NML08_02_FIND_01_05]
[s]Hey, you![n][f 1 2 65535][e]

[msg MSG_NML08_02_PURSUE_01_0]
[s]Wait![n][f 1 2 65535][e]

[msg MSG_NML08_02_PURSUE_01_0_2]
[s]You think you[n]can get away!?[n][f 1 2 65535][e]

[msg MSG_NML08_02_PURSUE_01_0_3]
[s]Do as I say![n][f 1 2 65535][e]

[msg MSG_NML08_02_PURSUE_01_0_4]
[s]You must be punished![n][f 1 2 65535][e]

[msg MSG_NML08_02_PURSUE_01_0_5]
[s]Stop right there![n][f 1 2 65535][e]

[msg MSG_NML08_02_LOST_01_01]
[s]They disappeared!?[n][f 1 2 65535][e]

[msg MSG_NML08_02_LOST_01_02]
[s]I guess I lost them...[n][f 1 2 65535][e]

[msg MSG_NML08_02_LOST_01_03]
[s]You're quick![n][f 1 2 65535][e]

[msg MSG_NML08_02_LOST_01_04]
[s]Tch, where did they go!?[n][f 1 2 65535][e]

[msg MSG_NML08_02_LOST_01_05]
[s]Dammit, they got away![n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_NML_01]
[s]All right, nothing[n]wrong here.[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_NML_01_2]
[s]Be vigilant in your[n]surveillance.[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_NML_01_3]
[s]Area check complete![n]All clear![n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_NML_01_4]
[s]No one's stepping[n]out of line, are they?[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_NML_01_5]
[s]What was that sound? Must[n]have been my imagination...[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_NML_01_6]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_NML_01_7]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_NML_01_8]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_NML_01_9]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_NML_01_10]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_ALT_01]
[s]Where did they go?[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_ALT_01_2]
[s]Damn, where are they?[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_ALT_01_3]
[s]If I find them, they'll[n]be dead on sight...[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_ALT_01_4]
[s]They're wasting my time...[n]No matter what they[n]do, it's futile anyway...[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_ALT_01_5]
[s]I'll send them straight[n]to the punishment room...[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_ALT_01_6]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_ALT_01_7]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_ALT_01_8]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_ALT_01_9]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_ALT_01_10]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_REPORT_01_0]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_REPORT_01_0_2]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_REPORT_01_0_3]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_REPORT_01_0_4]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_REPORT_01_0_5]
[s]......[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01_]
[s]......[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__2]
[s]......[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__3]
[s]......[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__4]
[s]......[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__5]
[s]......[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01]
[s]Someone has infiltrated[n]the premises! Be on alert![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_2]
[s]Someone has escaped![n]Everyone, be on alert![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_3]
[s]Someone's there![n]Possible fugitive![n]Be on the lookout![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_4]
[s]Emergency! All personnel[n]must search for the intruder![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_5]
[s]Someone's breaking[n]the rules! Everybody[n]search for them![n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_2]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_3]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_4]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_5]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_6]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_7]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_8]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_9]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_10]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_11]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_12]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_13]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_14]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_15]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_16]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_17]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_18]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_19]
[s]......[n][f 1 2 65535][e]

[msg MSG_NML08_02_MNLG_FREE_0_20]
[s]......[n][f 1 2 65535][e]

