[msg MSG_000_0_0 [Shido]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]The criminals calling themselves the[n]Phantom Thieves are no more.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]However, I believe that this country's[n]citizens are still living their days in[n]anxiety.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]These scandals only increase our distrust[n]of the current government. As a citizen[n]myself, I am enraged![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Look who's talking.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Shido]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]What does it mean to be a politician with[n]responsibility?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Working toward personal gain without[n]consideration of the country is[n]outrageous![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]The election's public notification is[n]tomorrow, but no matter where I go,[n]people are cheering for Shido.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Everyone's being deceived so easily.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Shido]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]In order to save this country that has[n]been tainted by villains, social reform[n]is essential![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Ugh...[n][f 1 3 65535][w][e]

