[msg MSG_001_0_0 [Yaldabaoth]]
[s][vp 8 0 0 1 65535 0]So you have failed to harness the power.[n][f 1 2 100][e]

[msg MSG_002_0_0 [Yaldabaoth]]
[s][vp 8 0 0 2 65535 0]No matter how many prayers of those foolish masses come together...[n][f 1 2 160][e]

[msg MSG_003_0_0 [Yaldabaoth]]
[s][vp 8 0 0 3 65535 0]...Hm!?[n][f 1 2 40][e]

[msg MSG_004_0_0 [Ann]]
[s][vp 1 0 0 4 0 0]What the...[n][f 1 2 40][e]

[msg MSG_005_0_0 [Yaldabaoth]]
[s][vp 1 0 0 5 0 0]......![n][f 1 2 45][e]

