[msg MSG_019_0_0 [Mishima]]
[s][vp 8 0 0 1 65535 0]Take it down, Phantom Thieves![n][f 1 2 50][e]

[msg MSG_020_0_0 [Mishima]]
[s][vp 1 0 0 2 0 0]Come on, why do you think they've risked their lives all this time!?[n][f 1 2 115][e]

[msg MSG_021_0_0 [Mishima]]
[s][vp 1 0 0 3 0 0]Dammit, you guys! Snap out of it![n][f 1 2 65][e]

[msg MSG_022_0_0 [Mishima]]
[s][vp 1 0 0 4 0 0]When will you stop running from the truth!?[n][f 1 2 78][e]

[msg MSG_023_0_0 [Mishima]]
[s][vp 1 0 0 5 0 0]Phantom Thieves, can you hear us!?[n][f 1 2 98][e]

