[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 600 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]It's not moving at all...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Newscaster]]
[s][vp 8 0 0 2 65535 0]Due to the railway incident this morning,[n]widespread delays have impacted the[n]various lines and...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Sojiro]]
[s][bup 0 103 603 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Another accident, huh?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 601 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Heh. Reminds me of that day back in April.[n]Remember when we went to introduce you[n]at the school?[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Oh yeah.[e]
[s]Nope.[e]
[s]I'm trying to forget.[e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 600 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]It's almost been a whole year since then,[n]huh...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][bup 0 103 603 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Liar. It wasn't that far back.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sojiro]]
[s][bup 0 103 603 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]You never change, huh?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 603 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Thinking back, I was pretty awful to you,[n]throwing you in that storage room all by[n]yourself...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Then again, soon you're gonna be...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Sojiro]]
[s][bup 0 103 601 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Made some great friends here.[n]You'd better thank them when[n]we get back, all right?[n][f 1 3 65535][w][e]

