[msg MSG_000_0_0 [Third-Year Group Leader]]
[s][vp 8 0 0 1 9 0]Hey, that guy—yeah, him. Is he...[n]THAT transfer student?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Second-Year Group Member]]
[s][vp 8 0 0 2 13 0]Yeah...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [First-Year Group Member]]
[s][vp 8 0 0 3 12 0]You mean the one in all the crazy rumors?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Third-Year Group Leader]]
[s][vp 8 0 0 4 9 0]Keep it down! What if he hears us!?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Testy First-Year]]
[s][vp 8 0 0 5 10 0]Ugh. Anyone who just dumps a broken[n]umbrella on the ground like this is[n]human garbage.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ann]]
[s][bup 0 4 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Oh, before you trash it, you have to[n]make sure you separate the plastic[n]parts from the metal frame.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Large Second-Year]]
[s][vp 8 0 0 7 11 0]Separate it? How?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ann]]
[s][bup 0 4 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Like this.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Testy First-Year]]
[s][vp 8 0 0 9 10 0]Whoa, awesome![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Brunette Third-Year]]
[s][vp 8 0 0 10 13 0]I had no idea you knew about that[n]kinda stuff, Takamaki-san. I bet[n]you'd make a wonderful wife.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Oh, nah...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Uncouth Third-Year]]
[s][vp 8 0 0 12 9 0]Sweet, a wallet![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Excited Second-Year]]
[s][vp 8 0 0 13 13 0]Anything in it?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Easygoing First-Year]]
[s][vp 8 0 0 14 10 0]Whoa! Yeah, a shit-ton![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Uncouth Third-Year]]
[s][vp 8 0 0 15 9 0]...We goin' splitsies on this?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Wait—shouldn't we take[n]that to a police box?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]What!? How was that weird?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Mishima]]
[s][bup 0 111 202 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Man, this park is trashed... No way this[n]was all done by kids—it's gotta be the[n]work of some no-good adults, too.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Mature Third-Year]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 19 0]If you don't mind, may I have the cap[n]on that bottle?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Mishima]]
[s][bup 0 111 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Huh? Sure...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Mishima]]
[s][bup 0 111 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Oh! Are you a collector?[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Mature Third-Year]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 19 0]Ah... Not exactly.[n][f 1 3 65535][w][e]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 24 0 19 6 36 5 100][vp 8 0 0 23 19 0]Recycling companies collect these and[n]convert them into vials for vaccines.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Mishima]]
[s][bup 0 111 204 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Huh, I didn't know that...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Mishima]]
[s][bup 0 111 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Well, that sounds like an awesome way[n]to bring more justice to the world![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Mature Third-Year]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 19 0]...I'm sorry, but I'm not sure I follow you.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Maruki]]
[s][bup 0 216 700 0 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Before I add taro to the pot, I have[n]to rub them with salt to reduce the[n]sliminess...[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Fawning Female Student]]
[s][vp 8 0 0 28 12 0]Ohhh, you're an amazing chef![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Maruki]]
[s][bup 0 216 701 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]I do cook pretty often at home.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Let me try this little technique here...[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Thin Female Student]]
[s][vp 8 0 0 31 13 0]Huh? What the... Why's the wind salty!?[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Maruki]]
[s][bup 0 216 703 0 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Uh... Sorry.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Makoto]]
[s][bup 0 6 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]The cleanup is officially complete.[n]Thank you for your hard work,[n]everyone.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Would the leader of each group[n]please come and get the soup[n]for their teams?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Third-Year Group Leader]]
[s][vp 8 0 0 35 9 0]So, after the soup's doled out, everyone's[n]free to do whatever they want.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 36 9 0]Including getting the hell outta here.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Second-Year Group Member]]
[s][vp 8 0 0 37 13 0]Oh, okay.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [First-Year Group Member]]
[s][vp 8 0 0 38 12 0]Thank you for everything.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]I don't know the best way to put it...[n]but that sure was a crappy time out[n]there.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Student Called Yoshizawa]]
[s][bup 0 10 204 65535 0][f 4 10 65535 0 0][vp 8 0 0 40 6 0]Oh![n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Student Called Yoshizawa]]
[s][bup 0 10 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 41 6 0]I've finally found you.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 42 6 0]I was trying to find you so I could[n]thank you properly for this morning.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Student Called Yoshizawa]]
[s][bup 0 10 203 65535 0][f 4 10 65535 0 0][vp 8 0 0 43 6 0]So... Where'd the other people in your[n]group go?[n][f 1 3 65535][w][e]

[sel SEL_038_0_0 top]
[s]We've disbanded.[e]
[s]They ditched me.[e]

[msg MSG_039_0_0 [Student Called Yoshizawa]]
[s][bup 0 10 203 65535 0][f 4 10 65535 0 0][vp 8 0 0 44 6 0]Ah... I see.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Student Called Yoshizawa]]
[s][bup 0 10 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 45 6 0]...I'm in pretty much the same[n]situation.[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Student Called Yoshizawa]]
[s][bup 0 10 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 46 6 0]If it's all right with you, why don't[n]we eat our soup together?[n][f 1 3 65535][w][e]

[sel SEL_042_0_0 top]
[s]Sure.[e]
[s]This is soup, though.[e]

[msg MSG_043_0_0 [Student Called Yoshizawa]]
[s][bup 0 10 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 47 6 0]Great![n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Student Called Yoshizawa]]
[s][bup 0 10 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 49 6 0]Then let's drink it together.[n][f 1 3 65535][w][e]

