[msg MSG_000_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Thanks again for letting me join you.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]To be honest, prelims are coming[n]up soon, so I didn't want to take[n]any chances of getting sick.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Prelims?[e]
[s]Is it for gymnastics?[e]

[msg MSG_002_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Oh, the preliminary competition for[n]gymnastics.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Yeah, that's right.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Two huge competitions are coming up—[n]one at the beginning of summer and[n]one near the end.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]If I'm going to participate in the prelims,[n]I have to be selected as my club's[n]representative...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]And there's a qualifier meet to[n]determine who that rep will be.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]It's my dream to compete in gymnastics[n]on the global level.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]So, I plan on maintaining a strict[n]training regimen with my coach.[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]You sure are devoted.[e]
[s]I'll cheer you on.[e]

[msg MSG_008_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]It's nothing extraordinary.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]But it's for my dream, so I'm willing to[n]put in every bit of effort that I have.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]I'd be invincible if I had you cheering[n]me on, Senpai! *giggle*[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Oh, we're already at the station...[n][f 1 3 65535][w][e]

