[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Whew, I'm done...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]As for me... I'm done for.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Talk about a clichéd way to end your[n]summer vacation.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]I can't believe you hadn't even touched[n]your homework until last night.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Well, everyone's free to spend their time[n]as they choose. I guess SOME PEOPLE[n]just can't help themselves.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]I'm sorry...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Come on, I think he's learned his lesson.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]More importantly, why don't you folks[n]take a break?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Boss! You're a lifesaver![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]I'm gonna go pick up some groceries.[n]Mind the shop for a bit.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Newscaster]]
[s][f 4 10 65535 0 0][vp 1 0 0 20 0 0]The sports club has aggressively applied[n]kinesthesiology to their team's practices.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 21 0 0]By incorporating their lab's findings on[n]human efficiency into the training[n]regimen, they've developed a...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]...Oh, that reminds me: isn't there a[n]female athlete from our own school[n]who's made the news?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]An athlete... Do you mean the one in[n]gymnastics?[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Yeah, her! The one everyone's saying[n]is super-cute![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Oh yeah—Yoshizawa, right?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Wasn't she gonna be in the summer[n]meet? Or izzat already over?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Ah, about that...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Makoto?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Well... I just happened to overhear a[n]couple teachers discussing it when I[n]was heading to school the other day.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Yoshizawa-san's results in the meet...[n]They weren't exactly stellar.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]I see...?[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]There seemed to have been a great many[n]people expecting her success there. It's[n]got to be tough for her...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Yeah...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Ain't there one more meet left this year[n]in gymnastics, though?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Shit must be rough right now, but if she[n]can nail that one, who cares what anybody[n]at school says?[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Oh. That also reminds me...[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]So, I just so happened to bump into[n]Mishima-kun before summer vacation[n]started.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]And?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]He seemed really mad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]I asked him what was wrong and[n]he showed me some posts on an[n]underground site about our school.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]It pretty much said the school's planning[n]to abandon any honors student who isn't[n]actively making Shujin look better.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Whoa, wait a sec...[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]There was no name, and it sounded like[n]just another rumor at first...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]But, could this be about Yoshizawa-san?[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Who knows?[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]Still, ever since the case with Kamoshida...[n]The school's been frantically trying to[n]improve its public image, right?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]At the very least, this abandonment of[n]honor students would fall in line with[n]the school's real mission.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]I can't deny the possibility that they[n]would do this to Yoshizawa-san...[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]They dump all their hopes onto their[n]athletes, and if they don't cut the mustard,[n]they're out like the rest of the trash, huh?[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]Regardless of whether it's true or not,[n]such behavior is extremely self-serving.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]Tch... Just like we've thought this whole[n]time... There's still tons of shit wrong[n]with society.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]Yeah...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]We don't know what'll happen to[n]Yoshizawa's spot on the team...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]But at the very least, we can keep up[n]our efforts to prevent the worst-case[n]scenario.[n][f 1 3 65535][w][e]

