[msg MSG_000_0_0 [Shibusawa]]
[s][bup 0 222 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 4 0]Dammit! Just hearing it from you's[n]pissing me off...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 4 0]You've come so far... What problem[n]could they possibly have now!?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Maruki]]
[s][bup 0 216 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]I tried negotiating in person with[n]the professor and the investors,[n]but they simply wouldn't listen...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]"Due to the lack of concrete evidence,[n]all further research and funding in the[n]field of cognitive psience will cease."[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]They told me it's already over and[n]done with.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Maruki]]
[s][bup 0 216 905 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]But, why now of all times?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]When they first saw my paper, they[n]were positively beaming with[n]excitement![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Shibusawa]]
[s][bup 0 222 503 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 4 0]And the research lab in Odaiba...[n]They're not going through with[n]that anymore?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Maruki]]
[s][bup 0 216 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Yep...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Maruki]]
[s][bup 0 216 902 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Dammit... To hell with their "concrete[n]evidence"![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]How are we supposed to get any[n]evidence if we can't perform the[n]research first!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]If we can change the cognition of[n]trauma victims, their suffering can[n]be eliminated...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Who knows how many people could[n]be saved with this research... How much[n]more obvious could its benefits be?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Shibusawa]]
[s][bup 0 222 503 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 4 0]So... Do you really think the lack of [n]evidence is the reason they shut it all[n]down?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Maruki]]
[s][bup 0 216 903 65535 0][vp 1 0 0 15 0 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]It makes absolutely no sense to me.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]After all the time and money spent...[n]To just cut off my research because it[n]wasn't all proven sound immediately...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Maruki]]
[s][bup 0 216 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Even if that was the result of some kind[n]of conspiracy, what could I do about it?[n]It's not like I have any proof.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Shibusawa]]
[s][bup 0 222 503 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 4 0]I see...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Shibusawa]]
[s][bup 0 222 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 4 0]So, what're you gonna do now?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 4 0]The sponsors have backed out, so[n]I doubt the college is gonna let you[n]keep using their labs...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Maruki]]
[s][bup 0 216 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]I'm done with that college. They have[n]nothing for me at this point.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]I'll look for work elsewhere while I keep[n]fleshing out that research paper.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Eventually, I'll prove the existence of[n]the cognitive world... Once I've done[n]that, no one will be able to complain.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Maruki]]
[s][bup 0 216 907 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Rumi...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]I swear I'm going to do it.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]I have the power now... It cost me my life[n]with you...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Maruki]]
[s][bup 0 216 907 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]So I'm going to rescue everyone from[n]their pain...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]I don't care how long it takes me...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]It's going to happen.[n][f 1 3 65535][w][e]

