[msg MSG_000_0_0 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Was that...?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sumire]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Yes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]It was a counseling session I had with[n]Dr. Maruki.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]It was just after Kasumi... after my[n]sister passed away.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]From that moment on, I lived my life[n]really believing I was Kasumi.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]It was all due to the rewriting of your[n]cognition—his "actualization," as we've[n]started calling it?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Okay, but I've been wondering[n]something...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]So it was only Sumire who believed[n]that she was Kasumi, right?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]I assumed someone in your family or one[n]of your friends would've noticed you[n]going by the wrong name right away...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sumire]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Well, I can certainly remember being[n]called "Kasumi" by everyone else, too...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]It might be more accurate to say you[n]misheard or misunderstood the[n]name you were being called.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Like, everyone kept callin' you "Sumire,"[n]but your cognition made you hear it as[n]"Kasumi."[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]So that's why nobody thought it was[n]weird, including her folks and herself...[n]Damn...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]This must be part of the whole[n]"salvation" nonsense Maruki's[n]trying to pull over on us.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]That memory may have been kept here[n]in video form because he truly does[n]wish for Violet to be happy with life.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sumire]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]I admit, I really did feel saved in that[n]moment when I became Kasumi...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]But at the same time, I ran from my life[n]as Sumire...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]I'm genuinely grateful for what Dr. Maruki[n]did for me, but I'm done running.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Sumire]]
[s][bup 0 10 102 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]...Let's get going.[n][f 1 3 65535][w][e]

