[msg TEST_DUMMY]
[s]......[n][w][e]

[msg MSG_MORU_Q80_000_000 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]Certo, que lugar melhor para procurar[n]alunos do que em uma escola! Vamos comecar[n]perguntando sobre Nagata![n][w][e]

[msg MSG_E13710100_000_00 [Ryuji]]
[s][bup 0 2 205 65535 0][f 4 10 65535 0 0][vp 8 0 1 1 65535 0]Aquele idiota esta agindo como um rei aqui[n]tambem...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]Conhecer um ao outro melhor, minha bunda.[n]E apenas um show individual para ele derrotar[n]seu ego.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]E como ele agiu como se estivesse preocupado[n]Sobre Mishima? Que D-BAG abusivo![n][w][e]

[msg MSG_E13710100_000_03 [Ryuji]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7187 65535 0]......[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]... bem, de qualquer maneira.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]Agora e nossa chance de procurar os caras[n]Vimos eram escravos ontem.[n][w][e]

[msg MSG_E13710100_000_05 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Vamos procurar os rostos que vimos no castelo.[n]Todos os membros da equipe devem ser[n]aqui hoje.[n][w][e]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 0 1 7 65535 0]Vou encontrar alguem para se derramar[n]O abuso fisico de Kamoshida. Apenas espere,[n]Idiota.[n][w][e]

[sel SEL_E13710100_001_00 top]
[s]Onde voce esta pesquisando?[e]
[s]Tudo bem, vejo voce mais tarde.[e]
[s]Eu nao me lembro dos rostos deles...[e]

[msg MSG_E13710100_002_00 [Ryuji]]
[s][bup 0 2 204 65535 0][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]Oh, voce esta chegando comigo tambem![n][w][e]

[msg MSG_E13710100_003_00 [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 0 1 9 65535 0]Nao se preocupe, eu me lembro delas claramente.[n][w][e]

[msg MSG_E13710100_004_00 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 0 1 10 65535 0]... o primeiro que saiu foi um cara[n]Da classe D, entao vamos comecar a partir dai.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]Essa e a sua classe.[n][w][e]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]Espero que voce possa fazer com que ele fale sem[n]quaisquer problemas. As pessoas estao me evitando[n]Ultimamente, entao...[n][w][e]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Oh, mas voce esta meio no mesmo barco, hein.[n][w][e]

[msg MSG_E13720100_000_00 [Ryuji]]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cara, eu gostaria que pudessemos pegar Mishima e[n]Faca com que ele fale ja.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ele sempre acaba correndo para longe de mim[n]por algum motivo...[n][w][e]
[s][bup 0 2 200 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Seria mais facil para voce falar com ele desde[n]Voces estao na mesma classe, certo?[n]Posso deixar isso para voce?[n][w][e]
[s][bup 0 2 204 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh! Ele poderia estar no escritorio da enfermeira ou[n]algo '? Ele pegou aquele rosto de pico-[n]primeiro.[n][w][e]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tudo bem, eu vou ir assim.[n]Vou perguntar as pessoas no pratico edificio[n]tambem.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Se eu o pegar, eu vou te bater. Ate mais.[n][w][e]

[msg MSG_E13910100_000_00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Se nao nos apressarmos, Mishima vai lidar[n]casa. Vamos pega-lo na entrada da frente[n]da escola![n][w][e]

