[msg MSG_MAMA_GREETING_01 [Lala Escargot]]
[s][vp 8 2 1 57728 65535 0]Voce esta aqui de novo, garoto?[n][w][e]
[s]Nao me culpe se voce for comido vivo,[n]ok?[n][w][e]

[msg MSG_MAMA_GREETING_02 [Lala Escargot]]
[s][vp 8 2 1 57728 65535 0]Voce com certeza veio muito aqui...[n][w][e]
[s]Eu realmente nao me importo, mas mantenha-se[n]em cheque, ok?[n][w][e]

[msg MSG_MAMA_GREETING_03 [Lala Escargot]]
[s][vp 8 2 1 57728 65535 0]Desculpe garoto. Ichiko-chan nao esta aqui hoje.[n][w][e]
[s]Ou voce esta aqui para me ver em vez disso?[n][w][e]

[msg MSG_MAMA_GREETING_04 [Lala Escargot]]
[s][vp 8 2 1 57728 65535 0]Desculpe, Ichiko-chan nao esta aqui hoje.[n][w][e]

[msg MSG_MAMA_LAST_GREETING [Lala Escargot]]
[s][vp 8 2 1 57728 65535 0]... O que te traz aqui em um momento como este?[n][w][e]

[msg MSG_MAMA_WorkInfo_01 [Lala Escargot]]
[s]HM? O que voce faz 悪 oh![n][w][e]
[s]Voce esta aqui para o trabalho de meio periodo?[n][w][e]

[sel SEL_WorkInfo_01 top]
[s]Isso mesmo.[e]
[s]Sem chance.[e]

[msg MSG_MAMA_WorkInfo_02_01 [Lala Escargot]]
[s]Oh, isso e um alivio! Nos estavamos recebendo[n]desesperado por ajuda.[n][w][e]

[msg MSG_MAMA_WorkInfo_02_02 [Lala Escargot]]
[s]Mentiras. Esta escrito em todo o seu rosto,[n]voce sabe?[n][w][e]

[msg MSG_MAMA_WorkInfo_03 [Lala Escargot]]
[s]Entao, voce aqui hoje para fazer um pouco[n]trabalho de meio periodo?[n][w][e]

[sel SEL_WorkInfo_02 top]
[s]Deixe-me.[e]
[s]Talvez mais tarde.[e]

[msg MSG_MAMA_WorkInfo_04_01 [Lala Escargot]]
[s]Entao vamos comecar voce imediatamente, hmm?[n][w][e]

[msg MSG_MAMA_WorkInfo_04_02 [Lala Escargot]]
[s]Ah, que chatice. Vou te perguntar de novo[n]em alguma outra hora...[n][w][e]

[msg MSG_QuestTarget_Notice [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Temos um alvo que ainda nao identificamos,[n]certo? Talvez voce possa reunir mais um pouco[n]informacao enquanto voce esta trabalhando?[n][w][e]

[msg MSG_E24440100_000_0_0 [Lala Escargot]]
[s][f 4 23 1 850 3 10 0 0][vp 8 0 1 1 65535 0]Bem-vindo bem vindo![n][f 1 3 65535][w][e]

[msg MSG_E24440100_001_0_0 [Lala Escargot]]
[s][vp 8 0 1 2 65535 0]... Quantos anos voce tem, garoto?[n][f 1 3 65535][w][e]

[msg MSG_E24440100_002_0_0 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]Desculpe, Lala-chan. Ele esta comigo.[n][f 1 3 65535][w][e]

[msg MSG_E24440100_003_0_0 [Lala Escargot]]
[s][f 4 23 1 850 3 10 0 0][vp 8 0 1 4 65535 0]Ooh, voce pegou um jovem verdadeiro[n]Desta vez... apenas nao deixe uma bebida menor[n]Alcool, ok?[n][f 1 3 65535][w][e]

