[msg msg_cbs_mode_help_000]
[s]Em branco[n]Em branco[n]Em branco[n][e]

[msg msg_cbs_mode_help_001]
[s]Um modo básico que testa os[n]fundamentos do combate, incluindo[n]fraquezas, ajudas e revezamento.[n][e]

[msg msg_cbs_mode_help_002]
[s]Um modo em que você identifica[n]fraquezas e encadeia o Relay[n]para obter a pontuação mais alta.[n][e]

[msg msg_cbs_mode_help_003]
[s]Um modo avançado onde você inflige[n]doenças negativas e acertos técnicos[n]para obter a pontuação mais alta.[n][e]

[msg msg_cbs_mode_help_004]
[s]Um modo especialista para resistir[n]aos ataques ferozes do inimigo para obter a[n]maior pontuação.[n][e]

[msg msg_cbs_mode_help_005]
[s]Um modo que testa os fundamentos[n]do combate, incluindo[n]ataque, defesa e suporte.[n][e]

[msg msg_cbs_mode_help_006]
[s]Uma batalha especial contra o conhecimento de um[n]invocador que evitou a queda da humanidade.[n][e]

[msg msg_cbs_mode_help_007]
[s]Uma batalha especial contra a[n]cognição de um invocador que[n]dissipou uma mortalha de névoa.[n][e]

[msg msg_cbs_not_open_sys_mes]
[s]Puoi affrontare la sfida[n]acquistandone il contenuto sul[n]PlayStation™Store.[n][w][e]

[msg msg_cbs_confirm_message [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Você começa a batalha?[n][w][e]

[msg msg_cbs_confirm_message_ [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]Você quer começar esta batalha?[n][w][e]

[sel msg_cbs_confirm_select top]
[s]Sim.[e]
[s]Não.[e]

[msg msg_cbs_devil_message_00 [Lavenza]]
[s]Hee-ho![n][w][e]

[msg msg_cbs_devil_message_00_2 [Lavenza]]
[s]Kill-ho![n][w][e]

[msg msg_cbs_devil_message_00_3 [Lavenza]]
[s]...Hee![n][w][e]

[msg msg_cbs_devil_message_00_4 [Lavenza]]
[s]Oh![n][w][e]

[msg msg_cbs_devil_message_00_5 [Lavenza]]
[s]Violência-ho![n][w][e]

[msg msg_cbs_devil_message_00_6 [Lavenza]]
[s]O...[n][w][e]

[msg msg_cbs_devil_message_00_7 [Lavenza]]
[s]EU TE ENGUIO...[n][w][e]

[msg msg_cbs_devil_message_00_8 [Lavenza]]
[s]... EM UMA MORDIDA![n][w][e]

[msg msg_cbs_devil_message_00_9 [Lavenza]]
[s]O...[n][w][e]

[msg msg_cbs_devil_message_00_10 [Lavenza]]
[s]É O MESMO PARA VOCÊ![n][w][e]

[msg msg_cbs_devil_message_00_11 [Lavenza]]
[s]Eu mato...[n][w][e]

[msg msg_cbs_devil_message_00_12 [Lavenza]]
[s]...graça![n][w][e]

[msg msg_cbs_devil_message_00_13 [Lavenza]]
[s]Sonolento...[n][w][e]

[msg msg_cbs_devil_message_00_14 [Lavenza]]
[s]Em breve...[n][w][e]

[msg msg_cbs_devil_message_00_15 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_16 [Lavenza]]
[s]Como quiser...[n][w][e]

[msg msg_cbs_devil_message_00_17 [Lavenza]]
[s]Você vai morrer por mim?[n][w][e]

[msg msg_cbs_devil_message_00_18 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_19 [Lavenza]]
[s]Não tem espaço aqui...[n][w][e]

[msg msg_cbs_devil_message_00_20 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_21 [Lavenza]]
[s]Você se importaria...[n][w][e]

[msg msg_cbs_devil_message_00_22 [Lavenza]]
[s]...morra por mim?!?[n][w][e]

[msg msg_cbs_devil_message_00_23 [Lavenza]]
[s]É tão...[n][w][e]

[msg msg_cbs_devil_message_00_24 [Lavenza]]
[s]...abafado...[n][w][e]

[msg msg_cbs_devil_message_00_25 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_26 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_27 [Lavenza]]
[s]Onde estou...?[n][w][e]

[msg msg_cbs_devil_message_00_28 [Lavenza]]
[s]A próxima lua cheia...[n][w][e]

[msg msg_cbs_devil_message_00_29 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_30 [Lavenza]]
[s]Eu não me importo...[n][w][e]

[msg msg_cbs_devil_message_00_31 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_32 [Lavenza]]
[s]Onde estou...?[n][w][e]

[msg msg_cbs_devil_message_00_33 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_34 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_35 [Lavenza]]
[s]A neblina está chegando...[n][w][e]

[msg msg_cbs_lock_sys_message]
[s]Esta batalha ainda não foi desbloqueada.[n][w][e]

[msg msg_cbs_unlock_trial_2_s]
[s]Um novo nível de dificuldade foi desbloqueado[n]para as Challenge Battles.[n][w][e]

[msg msg_cbs_unlock_trial_3_s]
[s]Um novo nível de dificuldade foi desbloqueado[n]para as Challenge Battles.[n][w][e]

[msg msg_cbs_unlock_trial_4_s]
[s]Um novo nível de dificuldade foi desbloqueado[n]para as Challenge Battles.[n][w][e]

[msg msg_cbs_unlock_trial_5_s]
[s]Um novo nível de dificuldade foi desbloqueado[n]para as Challenge Battles.[n][w][e]

[msg msg_cbs_unlock_chain_sys]
[s]Um novo modo para Challenge Battles foi[n]desbloqueado: Chain.[n][w][e]

[msg msg_cbs_unlock_technical]
[s]Um novo modo para Batalhas de Desafio foi[n]desbloqueado: Técnico.[n][w][e]

[msg msg_cbs_unlock_suvival_s]
[s]Um novo modo para Batalhas de Desafio foi[n]desbloqueado: Sobrevivência.[n][w][e]

[msg msg_cbs_unlock_trickster]
[s]Um novo modo para Challenge Battles foi[n]desbloqueado: Trickster.[n][w][e]

[msg msg_cbs_unlock_p3_sys_me]
[s]Um novo modo para Batalhas de Desafio foi[n]desbloqueado: Lua Cheia.[n][w][e]

[msg msg_cbs_unlock_p4_sys_me]
[s]Um novo modo para Challenge Battles foi[n]desbloqueado: Foggy Day.[n][w][e]

[msg msg_cbs_unlock_p3_hard_s]
[s]Um novo nível[n]dificuldade foi desbloqueado para Full Moon.[n][w][e]

[msg msg_cbs_unlock_p4_hard_s]
[s]Um novo nível de dificuldade[n]foi desbloqueado para Foggy Day.[n][w][e]

[msg msg_cbs_unlock_new_mode_]
[s]Um novo[n]modo para Batalhas de Desafio foi desbloqueado.[n][w][e]

