[sel FCL_MSG_COMBINE_SELECT top]
[s]Vamos prosseguir.[e]
[s]Esqueça.[e]

[msg FCL_MSG_COMBINE_CONFIRM [Igor]]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg FCL_MSG_COMBINE_OVER_LEV [Igor]]
[s]Você não parece ter nível[n]alto o suficiente para[n]criar esta Persona.[n][w][e]

[msg FCL_MSG_COMBINE_SAME [Igor]]
[s]Você parece já ter dado as boas-vindas a essa[n]Pessoa em você...[n][w][e]

[msg FCL_MSG_COMBINE_JAIL [Igor]]
[s][clr 1][var 0][clr 27]está atualmente em[n]Reclusão. Você não pode fundi-lo[n]quando estiver nesta condição.[n][w][e]

[msg FCL_MSG_COMBINE_STOCK_OV [Igor]]
[s]Você não pode acolher outras[n]Personas dentro de você.[n][w][e]

[msg FCL_MSG_COMBINE_STOCK_EM [Igor]]
[s]Parece que você não tem[n]Personas para usar na fusão...[n][w][e]

[msg FCL_MSG_COMBINE_MONEY [Igor]]
[s]Oh? Parece que você não[n]tem o dinheiro solicitado...[n][w][e]

[msg FCL_MSG_COMBINE_MONEY_CO [Igor]]
[s]Levará [var 0] ienes para criar[n]esta pessoa. Você acha aceitável?[n][w][e]

[msg FCL_MSG_COMBINE_SUCCESSI [Justine]]
[s]Escolha quais habilidades herdar.[n][w][e]

[msg FCL_MSG_COMBINE_CONCEPT_ [Igor]]
[s]Oh...?[n][w][e]
[s]Aparentemente, sua Persona nasceu com um poder[n]especial...[n][w][e]

[msg FCL_MSG_COMBINE_COMU_POW [Igor]]
[s]Admirar. O Confidente [var 0][n]está despertando o poder oculto[n]da sua Persona...[n][w][e]

[msg FCL_MSG_COMBINE_GET_EXP]
[s]誕生した[clr 1][var 1][clr 27]は、[n]なんと[var 2]EXPを得た![n][w][e]

[msg FCL_MSG_COMBINE_LVUP]
[s][clr 1][var 0][clr 0]は、レベルが上がりそうだ![n][w][e]

[msg FCL_MSG_COMBINE_COMULV_N]
[s][var 0]コミュの力が、[n][clr 1][var 1][clr 27]に力を与える...[n][w][e]
[s]...だが、[var 0]コープは[n]まだ生まれていなかった...[n][w][e]

[msg FCL_MSG_COMBINE_GET_CARD]
[s]A pessoa [clr 1][var 0][clr 27][n]nasceu![n][w][e]

[msg FCL_MSG_COMBINE_ACCIDENT [Igor]]
[s]Oh? Parece que a fusão não foi conforme o planejado…[n][w][e]

[msg FCL_MSG_COMBINE_ACCIDENT_2 [Igor]]
[s]Alguém está [clr 2]suspeitando[clr 27] de você,[n]desencadeando um violento redemoinho[n]no mar da consciência...[n][w][e]
[s]Isso pode afetar suas[n]fusões de forma inesperada.[n]Você acha que é aceitável...?[n][w][e]

[msg FCL_MSG_COMBINE_SKILL_EV [Igor]]
[s]Hmm... sinto os sintomas[n]da evolução em[n][var 0].[n][w][e]
[s]O que você vai fazer?[n][w][e]

[msg FCL_MSG_COMBINE_SKILL_EV_2]
[s]Pessoa [var 0] evoluiu[n]para [var 1]![n][w][e]

[msg FCL_MSG_COMBINE_SKILL_CH [Igor]]
[s]Hmm... Parece que [var 0] quer[n]se transformar em outra coisa.[n][w][e]
[s]... O que você vai fazer?[n][w][e]

[msg FCL_MSG_COMBINE_SKILL_CH_2]
[s]A pessoa [var 0] se transformou[n]em [var 1]![n][w][e]

[msg FCL_MSG_COMBINE_GALL_SKI]
[s]Sua Persona está herdando[n]o poder do sacrifício...[n][w][e]

[msg FCL_MSG_COMBINE_GALL_ACC [Igor]]
[s]Oh? Aparentemente, sua Persona[n]não ganhou experiência, mas[n]seu poder parece ter aumentado...[n][w][e]

[sel FCL_MSG_COMBINE_SKILL_EV_3 top]
[s]Vamos fazê-lo.[e]
[s]Está bem do jeito que está.[e]

[msg FCL_MSG_COMBINE_BONUS [Igor]]
[s]A nova Persona parece ser[n]mais poderosa que o normal…[n][w][e]

[msg FCL_MSG_COMBINE_BONUS_SK [Igor]]
[s]Algo está prestes a acontecer com[n]uma habilidade...[n]Você quer deixar isso acontecer?[n][w][e]

[sel FCL_MSG_COMBINE_BONUS_SK_2 top]
[s]Apenas faça.[e]
[s]Deixa para lá.[e]
[s]Vamos voltar às habilidades.[e]

[msg FCL_MSG_COMBINE_PUBLIC_S [Igor]]
[s]Parece que ele ganhou uma habilidade especial...[n][w][e]

[sel FCL_MSG_COMBINE_CELL_SEL top]
[s]Apenas faça.[e]
[s]Isso não importa.[e]

[msg FCL_MSG_COMBINE_CELL_CON [Caroline]]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg FCL_MSG_COMBINE_CELL_STO [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Hã? Você só tem uma Pessoa com você.[n][w][e]
[s]Se você colocá-lo em isolamento,[n]você não terá nenhum para invocar.[n][w][e]

[msg FCL_MSG_COMBINE_CELL_IN_ [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Você já tem uma pessoa em isolamento.[n]Recupere essa pessoa primeiro.[n][w][e]

[msg FCL_MSG_COMBINE_CELL_HOU [Caroline]]
[s]Isso é especial. Você não pode[n]melhorá-lo com isolamento.[n][w][e]

[msg FCL_MSG_COMBINE_CELL_LAV [Caroline]]
[s]Lavanza pára[n][w][e]

[msg FCL_MSG_COMBINE_CELL_LV9 [Caroline]]
[s]Esta Persona já tem boost[n]máximo. Escolha outro.[n][w][e]

[msg FCL_MSG_COMBINE_CELL_NOT [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Não seja estúpido.[n]No momento, nenhum de seus[n]Personas está aqui conosco.[n][w][e]

[msg FCL_MSG_COMBINE_CELL_NOT_2 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Você não tem incenso para usar.[n][w][e]

[msg FCL_MSG_COMBINE_CELL_ITE [Caroline]]
[s]Você quer queimar algum incenso?[n][w][e]

[sel FCL_MSG_COMBINE_CELL_ITE_2 top]
[s]Queime um.[e]
[s]Não, vamos deixar para lá.[e]
[s]Vamos mudar Personas .[e]

[msg FCL_MSG_COMBINE_CELL_OVE [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 2 5 3 9999 0]ainda está queimando.[n]Você quer queimar outro incenso?[n][w][e]

[msg FCL_MSG_COMBINE_CELL_ITE_3 [Caroline]]
[s]Você quer queimar [f 2 5 3 9999 0]?[n][w][e]

[sel FCL_MSG_COMBINE_CELL_ITE_4 top]
[s]Apenas faça.[e]
[s]Escolha outro.[e]

[msg FCL_MSG_COMBINE_CELL_GET [Caroline]]
[s]Você quer liberar esta Persona?[n][w][e]

[msg FCL_MSG_COMBINE_CELL_GET_2 [Caroline]]
[s]Aparentemente, seu Persona[n]aprendeu uma habilidade.[n][w][e]
[s]Você quer libertá-la de qualquer maneira?[n][w][e]

[msg FCL_MSG_COMBINE_CELL_GET_3 [Caroline]]
[s]Ainda vai demorar[n]um pouco até que sua Persona[n]aprenda uma habilidade.[n][w][e]
[s]Você quer libertá-la de qualquer maneira?[n][w][e]

[msg FCL_MSG_COMBINE_CELL_GET_4 [Caroline]]
[s]Levará algum tempo para[n]seu Persona aprender uma habilidade.[n][w][e]
[s]Você quer libertá-la de qualquer maneira?[n][w][e]

[msg FCL_MSG_COMBINE_CELL_NON [Caroline]]
[s]Ela ainda não é forte o suficiente.[n]Tem certeza que quer libertá-la?[n][w][e]

[msg FCL_MSG_COMBINE_CELL_ITE_5 [Caroline]]
[s]O item [f 2 5 3 9999 0] ainda não teve efeito.[n]Você quer libertá-la de qualquer maneira?[n][w][e]

[msg FCL_MSG_COMBINE_CELL_GET_5 [Caroline]]
[s]Muito bem, acabou o tempo![n]Confira o resultado dos[n]treinos de Persona![n][w][e]

[msg FCL_MSG_COMBINE_PUB_NET_]
[s]Os recursos de rede estão[n]desativados no momento.[n]Este recurso está desativado.[n][w][e]

[msg FCL_MSG_COMBINE_PUB_DAY_ [Caroline]]
[s]Esta execução é especial, não podemos[n]realizá-la repetidamente.[n]Volte outro dia![n][w][e]

[msg FCL_MSG_COMBINE_PUB_CONF [Caroline]]
[s]Nem mesmo podemos prever a[n]forma final desta Persona.[n]Você está convencido de que deseja continuar?[n][w][e]

[msg FCL_MSG_COMBINE_PUB_RESU [Igor]]
[s]Eheheh... Gostou do resultado?[n][w][e]

[msg FCL_MSG_COMBINE_PUB_TUTO [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Em primeiro lugar, escolha uma de[n]suas Personas para fusão![n][w][e]
[s][f 4 10 65535 0 0]Em seguida, escolha uma das Personas [n]de outro mundo.[n][w][e]
[s][f 4 10 65535 0 0]Nesse ponto, o rest[n]é o mesmo que as outras[n]execuções da guilhotina.[n][w][e]
[s][f 4 10 65535 0 0]NO ENTANTO, existem habilidades raras[n]que você só pode obter com[n]este ritual. Faça bom uso dele![n][w][e]

[msg FCL_MSG_COMBINE_ELECT_KE [Igor]]
[s]Você não parece ter o item[n]para usar na fusão...[n][w][e]

[msg FCL_MSG_COMBINE_ELECT_NU [Caroline]]
[s]Esta execução é especial, não podemos[n]realizá-la repetidamente.[n]Volte outro dia![n][w][e]

[msg FCL_MSG_COMBINE_ELECT_CH [Igor]]
[s]Não parece haver ninguém com você[n]que possa fazer bom uso disso...[n][w][e]

[msg FCL_MSG_COMBINE_ELECT_PO [Igor]]
[s]Você já tem este item.[n]Você não precisa de mais...[n][w][e]

[msg FCL_MSG_COMBINE_ELECT_MA [Igor]]
[s]Duvido que precise de mais...[n][w][e]

[msg FCL_MSG_COMBINE_ELECT_NO [Igor]]
[s]Você perderá a pessoa capaz[n]de usá-lo...[n][w][e]

[msg FCL_MSG_COMBINE_ELECT_LE]
[s]Level too low error (not used)[n][w][e]

[msg FCL_MSG_BOOK_REGIST_HELP [Justine]]
[s]Mmm, essas Personas parecem[n]diferentes das já registradas.[n][w][e]

[msg FCL_MSG_BOOK_ACCEPTANCE [Justine]]
[s]Você quer convocar esta Persona?[n]Vai custar [var 0] ienes.[n][w][e]

[msg FCL_MSG_BOOK_ACCEPTANCE_ [Justine]]
[s]Você deseja convocá-la?[n][w][e]

[msg FCL_MSG_BOOK_NO_MONEY [Justine]]
[s]Você não tem dinheiro suficiente.[n]Uma tentativa bastante descarada...[n][w][e]

[msg FCL_MSG_BOOK_SUMMONS]
[s]Você convocou [clr 1][var 0][clr 27].[n][w][e]

[msg FCL_MSG_BOOK_SAME [Justine]]
[s]Parece que você já tem[n]esta Pessoa... Não entendo[n]o motivo da sua solicitação.[n][w][e]

[msg FCL_MSG_BOOK_LEVEL [Justine]]
[s]Você não pode controlar esta Pessoa[n]em seu nível atual.[n][w][e]

[msg FCL_MSG_BOOK_MAX [Justine]]
[s]Você não pode acolher outras[n]Personas dentro de você.[n][w][e]

[msg FCL_MSG_BOOK_WRITE [Justine]]
[s]Como você solicitou, excluí o registro antigo de[n]sua Persona em favor do novo.[n][w][e]

[msg FCL_MSG_BOOK_WRITE_OK [Justine]]
[s]Deseja que ele registre[n][clr 1][var 0][clr 27]?[n][w][e]

[msg FCL_MSG_BOOK_WRITE_OK_AL [Justine]]
[s]Você quer que eu registre todas as[n]Personas que você[n]possui atualmente, certo?[n][w][e]

[msg FCL_MSG_BOOK_WRITE_OK_MA [Justine]]
[s]Você quer que eu registre todas[n]as Personas que você selecionou,[n]estou certo?[n][w][e]

[msg FCL_MSG_BOOK_ALL_REGISTE [Justine]]
[s]Você não tem outras Personas que precisam[n]ser registradas.[n][w][e]

[msg FCL_MSG_DLC_COMBINE [Igor]]
[s]Esta Pessoa nasceu do coração de uma entidade com[n]um destino diferente daquele narrado por sua[n]revolta.[n][w][e]
[s]No entanto, ainda possui o poder[n]de seu proprietário original.[n]Será de grande ajuda para você.[n][w][e]

[msg FCL_MSG_DLC_BOOK_ACCEPTA [Justine]]
[s]Esta Pessoa nasceu do coração de[n]uma entidade cujo destino difere do seu.[n][w][e]
[s]Ele carrega o poder de seu proprietário original.[n]Não tenho dúvidas de que o ajudará muito.[n][w][e]
[s]Você deseja convocá-la?[n][w][e]

[msg FCL_MSG_GET_ITEM]
[s]Obteve [f 2 5 3 9999 0].[n][w][e]

[msg book_bonus001]
[s]25% registro completo[n][w][e]

[msg book_bonus002]
[s]50% registro completo[n][w][e]

[msg book_bonus003]
[s]75% registro completo[n][w][e]

[msg book_bonus004]
[s]registro 100% completo[n][w][e]

[msg combine_before_comu_none [Igor]]
[s]Parece que você ainda não[n]estabeleceu um vínculo com o[n]Confidente da Arcana: [var 0][n][w][e]
[s]Portanto, esta Persona não ganhará[n]qualquer poder adicional com a fusão.[n]Você ainda deseja criá-la?[n][w][e]

[msg combine_before_comu_none_2 [Igor]]
[s]Parece que você ainda não[n]estabeleceu um vínculo com o[n]Confidente da Arcana: [var 0][n][w][e]
[s]Portanto, esta Persona não ganhará[n]nenhum poder adicional com a fusão.[n]Você ainda deseja criá-la?[n][w][e]

[msg combine_before_comu_none_3 [Igor]]
[s]Parece que você ainda não[n]estabeleceu um vínculo com o[n]Confidente da Arcana: [var 0][n][w][e]
[s]Portanto, esta Persona não ganhará[n]nenhum poder adicional com a fusão.[n]Você ainda deseja criá-la?[n][w][e]

[msg combine_comu_rank_00 [Igor]]
[s]Parece que você ainda não[n]estabeleceu um vínculo com o[n]Confidente da Arcana: [var 0][n][w][e]
[s]Portanto, esta Persona não ganhará[n]nenhum poder adicional com a fusão.[n]Você ainda deseja criá-la?[n][w][e]

[msg combine_comu_rank_01 [Igor]]
[s]Seu vínculo com o Confidant[n]é de nível 1.[n]Ele receberá novos poderes?[n][w][e]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg combine_comu_rank_02 [Igor]]
[s]Seu vínculo com o Confidant[n]é nível 2.[n]Você deve ver os benefícios...[n][w][e]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg combine_comu_rank_03 [Igor]]
[s]Seu vínculo com o Confidant[n]é nível 3.[n]Você deve ver os benefícios...[n][w][e]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg combine_comu_rank_04 [Igor]]
[s]Seu vínculo com o Confidant[n]é Rank 4.[n]Ele ganhará poder substancial...[n][w][e]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg combine_comu_rank_05 [Igor]]
[s]Seu vínculo com o Confidant[n]é Rank 5.[n]Ele ganhará grande poder...[n][w][e]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg combine_comu_rank_06 [Igor]]
[s]Seu vínculo com o Confidant[n]é de nível 6.[n]Ele ganhará um poder considerável...[n][w][e]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg combine_comu_rank_07 [Igor]]
[s]Seu vínculo com o Confidant[n]é nível 7.[n]Ele ganhará um poder enorme...[n][w][e]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg combine_comu_rank_08 [Igor]]
[s]Seu vínculo com o Confidant[n]é de nível 8.[n]Ele acumulará um poder excepcional.[n][w][e]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg combine_comu_rank_09 [Igor]]
[s]Seu vínculo com o Confidant[n]é de nível 9.[n]Ele acumulará um poder incontrolável.[n][w][e]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg combine_comu_rank_10 [Igor]]
[s]Seu vínculo com o Confidant[n]é de nível 10.[n][w][e]
[s]Mmm, não há dúvida sobre isso.[n]Essa fusão liberará[n]poder imensurável.[n][w][e]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg combine_comu_rank_s00 [Igor]]
[s]Parece que você ainda não[n]estabeleceu um vínculo com o[n]Confidente da Arcana: [var 0][n][w][e]
[s]Portanto, esta Persona não ganhará[n]nenhum poder adicional com a fusão.[n]Você ainda deseja criá-la?[n][w][e]

[msg combine_comu_rank_s01 [Igor]]
[s]Atualmente, você não tem acesso a todo o[n]potencial desse vínculo com o Confidente.[n][w][e]
[s]Portanto, esta Persona não ganhará[n]qualquer poder adicional com a fusão.[n]Você ainda deseja criá-la?[n][w][e]

[msg combine_comu_rank_s02 [Igor]]
[s]Atualmente, você não tem acesso a todo o[n]potencial desse vínculo com o Confidente.[n][w][e]
[s]Portanto, esta Persona não ganhará[n]nenhum poder adicional com a fusão.[n]Você ainda deseja criá-la?[n][w][e]

[msg combine_comu_rank_s03 [Igor]]
[s]Atualmente, você não tem acesso a todo o[n]potencial desse vínculo com o Confidente.[n][w][e]
[s]Portanto, esta Persona não ganhará[n]nenhum poder adicional com a fusão.[n]Você ainda deseja criá-la?[n][w][e]

[msg combine_comu_rank_s04 [Igor]]
[s]Atualmente, você não tem acesso a todo o[n]potencial desse vínculo com o Confidente.[n][w][e]
[s]Portanto, esta Persona não ganhará[n]nenhum poder adicional com a fusão.[n]Você ainda deseja criá-la?[n][w][e]

[msg combine_comu_rank_s05 [Igor]]
[s]Atualmente, você não tem acesso a todo o[n]potencial desse vínculo com o Confidente.[n][w][e]
[s]Portanto, esta Persona não ganhará[n]nenhum poder adicional com a fusão.[n]Você ainda deseja criá-la?[n][w][e]

[msg combine_comu_rank_s06 [Igor]]
[s]Atualmente, você não tem acesso a todo o[n]potencial desse vínculo com o Confidente.[n][w][e]
[s]Portanto, esta Persona não ganhará[n]nenhum poder adicional com a fusão.[n]Você ainda deseja criá-la?[n][w][e]

[msg combine_comu_rank_s07 [Igor]]
[s]Atualmente, você não tem acesso a todo o[n]potencial desse vínculo com o Confidente.[n][w][e]
[s]Portanto, esta Persona não ganhará[n]nenhum poder adicional com a fusão.[n]Você ainda deseja criá-la?[n][w][e]

[msg combine_comu_rank_s08 [Igor]]
[s]Atualmente, você não tem acesso a todo o[n]potencial desse vínculo com o Confidente.[n][w][e]
[s]Portanto, esta Persona não ganhará[n]nenhum poder adicional com a fusão.[n]Você ainda deseja criá-la?[n][w][e]

[msg combine_comu_rank_s09 [Igor]]
[s]Atualmente, você não tem acesso a todo o[n]potencial desse vínculo com o Confidente.[n][w][e]
[s]Portanto, esta Persona não ganhará[n]qualquer poder adicional com a fusão.[n]Você ainda deseja criá-la?[n][w][e]

[msg combine_comu_rank_s10 [Igor]]
[s]Seu vínculo com o Confidant[n]é de nível 10.[n][w][e]
[s]Mmm, não há dúvida sobre isso.[n]Essa fusão liberará[n]poder imensurável.[n][w][e]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg combine_comu_doubt [Igor]]
[s]"[var 0]" doubt (not used)[n][w][e]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg combine_comu_broken [Igor]]
[s]"[var 0]" broken (not used)[n][w][e]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg combine_comu_world [Igor]]
[s]Tem certeza de que esta[n]pessoa é aceitável?[n][w][e]

[msg msg_combine_HELP000 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Nosso recurso definitivo para você é[n]Personal Fusion…[n][w][e]
[s][f 4 10 65535 0 0]É um ritual sagrado no qual suas Personas[n]são[n]fundidas para criar uma nova.[n][w][e]
[s][f 4 10 65535 0 0]É também a morte do seu velho[n]ego, que por sua vez gera[n]um novo estado de existência.[n][w][e]
[s][f 4 10 65535 0 0]Quando você usa blend, a Person[n]resultante quase sempre será[n]maior que as iniciais.[n][w][e]
[s][f 4 10 65535 0 0]No entanto, é importante notar[n]que as Personas empregadas[n]na fusão serão perdidas.[n][w][e]
[s][f 4 10 65535 0 0]É claro que usar múltiplas[n]Personas s para moldar uma[n]irá reduzir seu pool...[n][w][e]
[s][f 4 10 65535 0 0]Portanto, pese cuidadosamente os prós e os[n]contras desse processo...[n][w][e]

[msg msg_combine_HELP001 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Reflita por um momento sobre os[n]Confidentes que lhe oferecem ajuda[n]em sua vida diária…[n][w][e]
[s][f 4 10 65535 0 0]Esses laços têm uma conexão[n]íntima com as Personas [n]que habitam seu coração.[n][w][e]
[s][f 4 10 65535 0 0]Uma Persona fundida ganhará grande[n]poder se você estabelecer um vínculo[n]com o Confidente de seu Arcano.[n][w][e]
[s][f 4 10 65535 0 0]Esse vínculo não apenas lhe dará experiência, mas[n]pode até mesmo aumentá-la imediatamente.[n][w][e]
[s][f 4 10 65535 0 0]Obviamente, quanto maior a classificação[n]do Confidant, mais experiência a Persona[n]mesclada ganhará.[n][w][e]
[s][f 4 10 65535 0 0]Agora você entende o valor inestimável desses[n]títulos?[n][w][e]

[msg msg_combine_HELP002 [Igor]]
[s][bup 0 201 0 0 0]Deixe-me explicar o Impetus[n]do Arcanum para você mais especificamente.[n][w][e]
[s]O poder recebido do Momentum[n]do Arcanum é definido como[n]"Pontos de Momentum".[n][w][e]
[s]Ao usar esses pontos, você pode[n]aprimorar uma de suas[n]Personas fundidas da maneira que desejar.[n][w][e]
[s]Aumente seus pontos fortes ou[n]conserte suas fraquezas...[n]A escolha é somente sua.[n][w][e]
[s]Lembre-se disso quando participar de um ritual de[n]fusão.[n][w][e]

[msg msg_combine_HELP003 [Igor]]
[s][bup 0 201 0 0 0]Os "traços" são as capacidades individuais[n]do Personas . Existem vários[n]tipos e com múltiplos efeitos...[n][w][e]
[s]Você pode transmitir uma característica,[n]não mais, durante as fusões.[n]Escolha com cuidado.[n][w][e]
[s]Em casos raros, as características não podem[n]ser transmitidas, ou no processo[n]novas podem aparecer.[n][w][e]
[s]Da experiência vem o conhecimento.[n]Com o tempo, você entenderá totalmente[n]a transmissão de características.[n][w][e]

[msg msg_combine_HELP004 [Igor]]
[s][bup 0 201 0 0 0]Existe mais de um método para[n]combinar Personas.[n][w][e]
[s]Sim, existem outros rituais[n]além da fusão da guilhotina.[n][w][e]
[s]Se você progredir na sua[n]reabilitação, talvez consiga[n]participar dela.[n][w][e]
[s]Não se esqueça de se esforçar ao máximo daqui[n]para frente.[n][w][e]

[msg msg_combine_HELP005 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Personas nascidos de uma fusão[n]podem às vezes herdar algumas[n]habilidades dos originais.[n][w][e]
[s][f 4 10 65535 0 0]Assim, você pode aproveitar[n]fusões para criar Personas com habilidades[n]impossíveis de aprender de outra forma.[n][w][e]
[s][f 4 10 65535 0 0]Você mesmo precisará se aprofundar nessas[n]regras, mas ainda há[n]alguns conselhos gerais...[n][w][e]
[s][f 4 10 65535 0 0]Primeiro, quanto mais habilidades a[n]Personas inicial tiver, mais habilidades[n]podem ser herdadas.[n][w][e]
[s][f 4 10 65535 0 0]Além disso, você poderá[n]selecionar livremente[n]quais habilidades transmitir.[n][w][e]
[s][f 4 10 65535 0 0]No entanto, tenha em mente que[n]existem habilidades que[n]personas fundidas não podem herdar.[n][w][e]
[s][f 4 10 65535 0 0]Esta informação será vital[n]se você quiser criar Personas poderosas.[n]Tenha isso em mente.[n][w][e]

[msg msg_combine_HELP007 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Minhas desculpas, mas mesmo nosso[n]ritual não é uma arte perfeita.[n][w][e]
[s][f 4 10 65535 0 0]É raro, mas durante uma[n]fusão um acidente pode[n]acontecer.[n][w][e]
[s][f 4 10 65535 0 0]Nestes casos, nascerá uma[n]Pessoa diferente da[n]prevista inicialmente.[n][w][e]
[s][f 4 10 65535 0 0]Mesmo nós desconhecemos as[n]consequências desses incidentes.[n]Esteja ciente dessa eventualidade.[n][w][e]

[msg msg_combine_HELP008 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]A Guilhotina Calibrada mostra a você[n]as Personas que você pode fundir com[n]seu grupo atual.[n][w][e]
[s][f 4 10 65535 0 0]Você também pode usá-lo para examinar[n]todas as combinações possíveis[n]para obter a mesma Persona.[n][w][e]
[s][f 4 10 65535 0 0]Esse recurso será de grande[n]ajuda para você, então sugiro que faça[n]bom uso dele durante sua viagem.[n][w][e]

[msg msg_combine_HELP009 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Deixe-me explicar o método[n]fusão do Grupo Guilhotina.[n][w][e]
[s][f 4 10 65535 0 0]Em vez de escolher as Personas[n]que deseja combinar, você seleciona[n]uma fusão predeterminada.[n][w][e]
[s][f 4 10 65535 0 0]Cada uma dessas fusões requer[n]três ou mais Personas , mas elas resultam[n]em algo muito especial.[n][w][e]
[s][f 4 10 65535 0 0]As Personas que você receberá são[n]todas, sem exceção,[n]extraordinariamente fortes.[n][w][e]
[s][f 4 10 65535 0 0]Aconselho-te a aceitar este[n]desafio, para bem da tua[n]reabilitação...[n][w][e]

[msg msg_combine_HELP010 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Além do nosso mundo, existem[n]outros onde inúmeros ladrões[n]enfrentam suas mesmas provações.[n][w][e]
[s][f 4 10 65535 0 0]Ao cooperar com eles, você pode[n]realizar uma fusão[n]chamada Execução Pública.[n][w][e]
[s][f 4 10 65535 0 0]Você deve selecionar uma Persona de[n]seu pool e mesclá-la com uma[n]Persona oferecida por outro ladrão.[n][w][e]
[s][f 4 10 65535 0 0]Mesclar Personas que você não[n]possui tem vantagens[n]claras...[n][w][e]
[s][f 4 10 65535 0 0]Além disso, algumas habilidades muito[n]poderosas só podem ser obtidas[n]através da Execução Pública.[n][w][e]
[s][f 4 10 65535 0 0]No entanto, é um ritual muito[n]especial. Por causa disso, ele não pode[n]ser executado repetidamente.[n][w][e]
[s][f 4 10 65535 0 0]Você só pode realizar uma[n]Execução Pública por dia.[n]Não se esqueça.[n][w][e]

[msg msg_combine_HELP011 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Deixe-me explicar a fusão pela forca para você.[n][w][e]
[s][f 4 10 65535 0 0]É um ritual no qual uma[n]Pessoa é oferecida como uma espécie[n]de sacrifício a outra.[n][w][e]
[s][f 4 10 65535 0 0]O sacrifício derramará seu[n]poder naquela Pessoa na[n]forma de pontos de experiência.[n][w][e]
[s][f 4 10 65535 0 0]Quanto mais poderosa a Pessoa oferecida como[n]sacrifício, mais pontos de experiência ele[n]concederá.[n][w][e]
[s][f 4 10 65535 0 0]Além disso, se o sacrifício e o[n]receptor forem do mesma Arcana,[n]o segundo será ainda mais poderoso.[n][w][e]
[s][f 4 10 65535 0 0]Finalmente, sacrificar um[n]Demônio do Tesouro garantirá uma quantidade[n]imoderada de experiência adquirida.[n][w][e]
[s][f 4 10 65535 0 0]Considere cuidadosamente a escolha[n]entre uma fusão e um sacrifício.[n][w][e]

[msg msg_combine_HELP012 [Igor]]
[s][bup 0 201 0 0 0]Os pontos ganhos no Fork são chamados de "Pontos[n]Justos".[n][w][e]
[s]Lembre-se, eles são os mesmos que você obtém com[n]as fusões.[n][w][e]
[s]Com um sacrifício, você pode atribuir[n]Momentum Points a Personas[n]mesmo depois de criá-los.[n][w][e]
[s]E, claro, ao alocar[n]os pontos necessários, você também pode[n]obter "Surge Abilities".[n][w][e]
[s]Momentum Skills será de muita[n]ajuda para você. Aproveite ao máximo.[n][w][e]

[msg msg_combine_HELP013 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Você não pode oferecer outro sacrifício[n]a uma Persona que acabou[n]de ser lançada no Fork.[n][w][e]
[s][f 4 10 65535 0 0]Não suportaria o fluxo de poder.[n]Ergo, uma Persona pode receber[n]apenas um sacrifício por dia.[n][w][e]
[s][f 4 10 65535 0 0]Portanto, para otimizar seu tempo[n]passado aqui, recomendo que você[n]favoreça os sacrifícios mais poderosos.[n][w][e]
[s][f 4 10 65535 0 0]O limite diário tem uma[n]exceção: durante o alerta de[n]fusão, você pode fazer mais sacrifícios.[n][w][e]
[s][f 4 10 65535 0 0]Mas saiba que vários sacrifícios[n]garantem resultados inesperados.[n]Não se esqueça disso.[n][w][e]

[msg msg_combine_HELP014 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Usando a cadeira elétrica, você pode[n]oferecer um sacrifício a um item[n]para fortalecê-lo imensamente.[n][w][e]
[s][f 4 10 65535 0 0]É um ritual bastante pecaminoso,[n]desperdiçar uma criatura viva em[n]favor de um objeto inanimado...[n][w][e]
[s][f 4 10 65535 0 0]No entanto, os itens que você pode obter[n]por meio desse processo são[n]inestimáveis.[n][w][e]
[s][f 4 10 65535 0 0]Eu recomendo que você pegue vários[n]itens para usar na fusão.[n][w][e]

[msg msg_combine_HELP015 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Existe uma maneira de reduzir[n]apatia para reabilitação:[n]o alarme de fusão.[n][w][e]
[s][f 4 10 65535 0 0]Quanto mais batalhas você enfrentar, mais[n]provável que o alarme soe.[n][w][e]
[s][f 4 10 65535 0 0]Durante o alarme, a Guillotine[n]melhora as Personas novamente e pode[n]aprender habilidades.[n][w][e]
[s][f 4 10 65535 0 0]Os efeitos de outras[n]Execuções também foram aprimorados.[n][w][e]
[s][f 4 10 65535 0 0]Mas cuidado: não convoque[n]Personas apenas para sacrificá-los,[n]abusando do alarme.[n][w][e]
[s][f 4 10 65535 0 0]Dessa forma, você[n]muitas vezes obteria Personas longe[n]do que você precisa.[n][w][e]
[s][f 4 10 65535 0 0]No entanto... graças a acidentes[n]milagres podem acontecer.[n]Você será capaz de entender seus segredos?[n][w][e]
[s][f 4 10 65535 0 0]Fale com os guardiões para parar o alarme. Ajude[n]a reabilitação usando-o com sabedoria.[n][w][e]

[msg msg_combine_HELP016 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]O subconsciente humano há muito cultiva[n]a crença de que relíquias antigas[n]têm almas.[n][w][e]
[s][f 4 10 65535 0 0]Isso foi demonstrado graças[n]à existência de Shadows chamados[n]Treasure Demons.[n][w][e]
[s][f 4 10 65535 0 0]Eles não podem ser convocados para[n]batalha como uma Persona normal,[n]mas são inestimáveis em fusões.[n][w][e]
[s][f 4 10 65535 0 0]Ao fundi-los, as regras que[n]governam a obtenção de uma[n]Pessoa mudam radicalmente.[n][w][e]
[s][f 4 10 65535 0 0]Parece haver alguma ligação[n]com os Arcanos, mas as noções[n]sobre o assunto são escassas.[n][w][e]
[s][f 4 10 65535 0 0]Treasure Demons também oferece[n]benefícios fora das fusões de guilhotina.[n][w][e]
[s][f 4 10 65535 0 0]Testemunhe seu[n]esplendor com seus próprios olhos.[n][w][e]

[msg msg_combine_HELP017 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Se você jogar uma de suas[n]Personas em uma cela, nós a submeteremos a[n]treinamento especial de crescimento.[n][w][e]
[s][f 4 10 65535 0 0]Enquanto você está relaxando,[n]sua Persona ficará mais forte.[n]Você está de bom humor, Prisioneiro![n][w][e]
[s][f 4 10 65535 0 0]Oh, o Confinamento só pode hospedar uma pessoa[n]por vez. Afinal, é um confinamento solitário.[n][w][e]
[s][f 4 10 65535 0 0]E, claro, você não poderá usar[n]aquela Persona em batalha ou in[n]fusões. Lembre-se disso, prisioneiro![n][w][e]

[msg msg_combine_HELP018 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Quando uma pessoa passa um dia na solitária, seu[n]poder aumenta.[n][w][e]
[s][f 4 10 65535 0 0]Depois de um período de tempo adequado[n]no isolamento, Personas aprende[n]a "superar suas fraquezas".[n][w][e]
[s][f 4 10 65535 0 0]Quanto maior o Rank do Confidant[n]para o Person Arcanum,[n]mais rápido o crescimento.[n][w][e]
[s][f 4 10 65535 0 0]Não se esqueça das palavras do Mestre.[n]Os laços com os Confidentes[n]ajudarão na sua reabilitação.[n][w][e]

[msg msg_combine_HELP006 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]No isolamento, você pode olhar para dentro e[n]fortalecer o espírito. Queime incenso e aumente[n]a concentração![n][w][e]
[s][f 4 10 65535 0 0]O incenso só tem efeito no final[n]do dia. Você só pode gravar[n]um de cada vez, não se esqueça disso.[n][w][e]
[s][f 4 10 65535 0 0]Terminado um incenso, você pode queimar[n]outro. Então seu Personas [n]ficará muito mais forte.[n][w][e]
[s][f 4 10 65535 0 0]Você pode encontrar incenso no[n]Metaverso, mas também no[n]mundo real.[n][w][e]
[s][f 4 10 65535 0 0]Tente estocar, ok?!?[n]Fique atento![n][w][e]

[msg msg_combine_HELP019 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Levará vários dias para[n]a Persona concluir o treinamento,[n]mas não se esqueça deles lá, ok?[n][w][e]
[s][f 4 10 65535 0 0]Afinal, cada pessoa abriga seu coração. Se você[n]deixá-lo lá por muito tempo, ele desaparecerá[n]para sempre.[n][w][e]
[s][f 4 10 65535 0 0]No entanto, não somos tão perversos.[n]Avisaremos você[n]quando estiver próximo.[n][w][e]
[s][f 4 10 65535 0 0]Depois disso, caberá a você intervir.[n]Não venha chorar para nós[n]se você agir tolamente.[n][w][e]

[msg msg_combine_HELP020 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0]Personas têm[n]propriedades únicas chamadas traços.[n][w][e]
[s][f 4 10 65535 0 0]Os traços podem ser transmitidos com fusões.[n][w][e]
[s][f 4 10 65535 0 0]Explorando-os corretamente[n]você pode acabar com uma[n]Pessoa que não pode ser vencida.[n][w][e]
[s][f 4 10 65535 0 0]Algumas características especiais, no entanto,[n]não podem ser transmitidas.[n][w][e]
[s][f 4 10 65535 0 0]No entanto, durante as fusões[n]apenas uma característica[n]pode ser transmitida por vez. Escolha cuidadosamente...[n][w][e]

[msg msg_combine_MHELP001 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0]Neste Livro do Prisioneiro[n]você pode registrar o nome atual e as[n]habilidades de sua Persona.[n][w][e]
[s][f 4 10 65535 0 0]A partir de então, poderei convocar essa[n]Pessoa com base em seu[n]status registrado, por uma pequena taxa.[n][w][e]
[s][f 4 10 65535 0 0]Você tem que agradecer ao nosso mestre[n]por esta habilidade.[n][w][e]
[s][f 4 10 65535 0 0]A partir de agora, registrarei automaticamente[n]todas as Personas não registradas[n]que você trouxer para mim.[n][w][e]
[s][f 4 10 65535 0 0]Além disso, posso substituir as[n]pessoas registradas pelas últimas[n]habilidades, se você quiser.[n][w][e]
[s][f 4 10 65535 0 0]Você pode se registrar[n]gratuitamente e a qualquer momento.[n][w][e]
[s][f 4 10 65535 0 0]No entanto, para convocar uma Persona,[n]você terá que pagar uma comissão[n]proporcional ao seu poder.[n][w][e]
[s][f 4 10 65535 0 0]Use esse recurso com sabedoria durante sua[n]reabilitação.[n][w][e]

[msg msg_combine_MHELP002 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0]Embora seja[n]possível convocar uma Persona do[n]Grimorium durante o alarme, você deve fazê-lo com cautela.[n][w][e]
[s][f 4 10 65535 0 0]O motivo não é claro, mas quanto mais[n]Personas você convocar, mais[n]risco de acidentes de fusão aumenta.[n][w][e]
[s][f 4 10 65535 0 0]Use o Grimoire[n]cuidadosamente durante o Merge Alert.[n][w][e]

[msg combine_conquest_questio [Igor]]
[s]Esta Persona é muito[n]poderosa para o seu[n]nível de poder atual.[n][w][e]
[s]No entanto, dadas as circunstâncias,[n]posso concordar em facilitar[n]sua reabilitação.[n][w][e]
[s]Eu só vou te pedir [clr 3][var 0][clr 27] ienes e,[n]em troca, farei o ritual...[n]O que você acha?[n][w][e]

[sel combine_conquest_sel top]
[s]Vamos fazê-lo.[e]
[s]Esqueça.[e]

[msg combine_book_high_questi [Justine]]
[s]Aparentemente, você precisa invocar esta[n]Pessoa do Livro do Prisioneiro.[n][w][e]
[s]Eu a convocarei por um custo de [clr 3][var 0][clr 27][n]ienes. O que você deseja fazer?[n][w][e]

[sel combine_book_high_sel top]
[s]Vamos fazê-lo.[e]
[s]Esqueça.[e]

[msg FCL_MSG_COMBINE_WARNING_ [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Fusões funcionam melhor[n]durante o alarme![n][w][e]
[s][f 4 10 65535 0 0]NO ENTANTO, se você seguir os[n]padrões usuais com fusões, não obterá[n]os resultados desejados! Tome cuidado![n][w][e]

[msg FCL_MSG_COMBINE_WARNING__2 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0]O próximo passo pode ser uma fusão arriscada.[n]Esteja preparado se algo der errado![n][w][e]

[msg FCL_MSG_COMBINE_WARNING__3 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]O que você acha?[n]Ficou muito bem![n][w][e]
[s]Sua nova Persona temporariamente transborda[n]de poder.[n][w][e]
[s]Usá-lo em um ritual durante[n]o alarme pode obter[n]resultados inesperados.[n][w][e]
[s]Talvez não seja o resultado que você[n]espera, mas algo[n]grande acontecerá. Use-o a seu favor![n][w][e]

[msg FCL_MSG_COMBINE_WARNING__4 [Caroline]]
[s][bup 0 102 4 0 0][f 4 10 65535 0 0]A guilhotina tem sido usada demais... Continuar a[n]solicitá-la pode ser perigoso.[n][w][e]

[msg FCL_MSG_COMBINE_WARNING__5 [Caroline]]
[s][bup 0 102 4 0 0][f 4 10 65535 0 0]Usamos muito o Fork...[n]Por um tempo, pode não[n]funcionar como deveria.[n][w][e]

[msg FCL_MSG_COMBINE_WARNING__6 [Justine]]
[s][bup 0 101 4 0 0][f 4 10 65535 0 0]A cadeira elétrica é exigente.[n]Tenha cuidado se pretende usá-la.[n][w][e]

[msg FCL_MSG_COMBINE_WARNING__7 [Justine]]
[s][bup 0 101 2 0 0][f 4 10 65535 0 0][n]O equipamento de reabilitação está no limite.[n]É hora de desligar o alarme.[n][w][e]
[s][f 4 10 65535 0 0]Durante a revisão, devo[n]pedir que você saia.[n][w][e]

[msg FCL_MSG_COMBINE_WARNING__8 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0]Nós iremos? Não é o que você esperava, mas[n]pelo menos você conseguiu[n]algo que vale a pena?[n][w][e]
[s][f 4 10 65535 0 0]Bem, agora temos que consertar as[n]ferramentas. Saia daqui! Rua![n][w][e]

[msg FCL_MSG_COMBINE_WARNING__9 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0]Nós iremos? Não é o que você esperava, mas[n]você tem bastante[n]poder à sua disposição. Quase demais, Prisioneiro![n][w][e]
[s][f 4 10 65535 0 0]Bem, agora temos que consertar as[n]ferramentas. Saia daqui! Rua![n][w][e]

[msg msg_combine_koukai_a6]
[s]Você pode se conectar à rede e[n]mesclar Personas por meio de[n]correspondência aleatória.[n][w][e]

[msg msg_combine_kousyu_a6 [Caroline]]
[s]Ao sacrificar vários Personas para um único[n]Persona, você pode aumentar suas estatísticas.[n][w][e]

[msg msg_combine_denki_a6 [Caroline]]
[s]Você só pode executar um Persona[n]e depois transformá-lo em um objeto.[n][w][e]

[msg msg_combine_dokubou_a6 [Caroline]]
[s]Você pode deixar uma Pessoa[n]aqui por um determinado número de dias[n]e ganhar pontos de experiência.[n][w][e]

[msg combine_mes_tutorial_top [Residente do Velvet Room]]
[s]Bem-vindo... ao Velvet Room.[n][w][e]

[msg combine_mes_tutorial_com [Residente do Velvet Room]]
[s]Suba de nível com os residentes[n]do Velvet Room para estragar[n]o resultado das fusões, corrompendo-os.[n][w][e]
[s]Quanto maior o Rank,[n]maiores as chances.[n][w][e]
[s]Per ora, premi il tasto △[n]per esaminare questa funzione.[n][w][e]

