[msg MSG_000_0_0]
[s][vp 8 0 0 0 65535 0]...I should look for a job magazine[n]and go underground in Shibuya.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Found it! Here it is![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Oh yeah, do you still have time?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]It's not that I don't have time...[e]
[s]I have a lot of time.[e]
[s]I want to go home.[e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Hey! It's too early to be boring![n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We're here, anyway! Why don't we grab[n]some tea and we can continue the job[n]search?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You can't turn down an invitation from[n]Lady Ann. I'll stay with her for as long[n]as she wants![n][f 1 3 65535][w][e]

