[msg MSG_000_0_0 [Employee]]
[s][vp 8 0 0 0 65535 0]I'm sorry, we can not hire you at this[n]time because your stats are not high[n]enough.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, that's lame...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]I bet they would have hired you if your[n]stats were higher.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, look at the time![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]We should go home for today.[n][f 1 3 65535][w][e]

