[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Whoa! The hell!?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Are these... infrared lasers? There's[n]no way we can get past them...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]This level of security only proves[n]there's something worth protecting[n]up ahead.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Wait, there's something written[n]on the sign...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]"All personnel: This door can only[n]be opened via the security room[n]that lies beyond it..."[n][f 1 3 65535][w][e]
[s][f 4 16 3 3 300 65535 65535][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]"Please be cautious, as it is impossible[n]to open from the outside."[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]So, it's never gonna open!? How're we[n]supposed to get past!?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Wait... That door... I think I've seen[n]that pattern somewhere...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][f 4 16 3 3 300 1 65535][vp 8 0 0 9 65535 0]...Oh right! There's no mistaking it![n]That's the same door I saw earlier![n][f 1 3 65535][w][e]

[msg MSG_007_5_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Guys, let's head back![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Huh? Why!?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]I think I know what real-world door[n]that's based on. There may be[n]another way to open it![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]In any case, I'll explain later! Come on,[n]let's go![n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]I suppose we should listen to Morgana[n]for the time being...[n][f 1 3 65535][w][e]

