[msg MSG_000_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]You have expelled one who was stained[n]in vanity.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]You are now one step closer to your[n]rehabilitation. It's a delightful thing[n]indeed.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Our master is pleased. You should be[n]honored, Inmate.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]However, that man's remarks are[n]concerning. It seems another has[n]made their way into the Metaverse.[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Is that true?[e]
[s]Who could it be?[e]

[msg MSG_004_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]That is beyond my knowledge...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]But your rehabilitation is progressing[n]smoothly... That is for certain.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]May the devotion to your rehabilitation[n]grow even deeper.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]I have high hopes for you.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 1 0 0 0 0 0]I feel like my bond with Igor[n]is growing deeper...[n][f 1 3 65535][w][e]

