[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]What is the meaning of this, Principal[n]Kobayakawa? Why did you post that[n]notice?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Principal]]
[s][bup 0 204 1 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]It was all for your sake.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]I thought the more information you had,[n]the easier your investigation would[n]become.[n][f 1 3 65535][w][e]
[s][bup 0 204 0 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]And? Did any information arise about[n]the case I asked you to look into?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]*sigh* Nothing yet.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]I will pass the details along if anything[n]comes up. Right now, there is a more[n]pressing issue...[n][f 1 3 65535][w][e]

[msg MSG_002_5_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]It appears there are students at Shujin[n]who are being threatened by a criminal[n]organization.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Principal]]
[s][bup 0 204 4 0 0][vp 8 0 0 8 65535 0]......!?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]A student who saw your posting came to[n]us looking for help... I'd like to request[n]a countermeasure.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Principal]]
[s][bup 0 204 4 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Isn't this some sort of mistake? I can't[n]believe this would happen to the[n]students of our academy.[n][f 1 3 65535][w][e]
[s][f 4 16 6 7 301 65535 65535][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Now is no time for such problems.[n]There is still lingering concern regarding[n]the Phantom Thieves...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]But we received a request for help...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Principal]]
[s][bup 0 204 4 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]I-I'm rather busy at the moment. If you[n]wish to do something, you will need to[n]act on your own.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 4 16 6 7 301 1 65535][vp 8 0 0 14 65535 0]...Sir!?[n][f 1 3 65535][w][e]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Are you sure about this? I am still[n]investigating your case as well...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Principal]]
[s][bup 0 204 1 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Y-Yes, that's correct. It works out[n]perfectly![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]My intentions have borne fruit. This[n]criminal organization must be the[n]connecting factor.[n][f 1 3 65535][w][e]
[s][f 4 16 6 5 301 65535 65535][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]If you pursue this criminal issue, you'll[n]surely find clues about the Phantom[n]Thieves![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]But that's absurd...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Principal]]
[s][bup 0 204 2 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]So... let's say this rumor is true. Do you[n]intend to ignore those students in trouble?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]I...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Principal]]
[s][bup 0 204 1 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Your sister would have solved this easily[n]if she were in your position.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]My expectations of you are very high.[n]I hope you don't disappoint.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][f 4 16 6 5 301 1 65535][vp 8 0 0 24 65535 0]......[n][f 1 3 65535][w][e]

