[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 7 1 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Man, that assembly had me bored[n]to tears.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ann]]
[s][bup 0 4 0 1 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Huh? Did you have school too, Yusuke?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 3 1 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]I'm doing laundry, so these are the only[n]clothes I had to wear.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 4 1 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]You really should buy a couple more[n]outfits...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Come now, we didn't gather here to[n]make small talk, now did we?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Let's get to Alibaba's case.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Well then, I'll start.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]It looks like Futaba was listening[n]in on Leblanc.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 3 1 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]But why would she want to listen in on[n]the café?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]I have no idea.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 3 1 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]It's just like Boss said... She's a tough nut[n]to crack.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]In any case, her hacking skills will be[n]absolutely necessary if we wish to[n]stand up to Medjed.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Going by what she has told us, we may[n]even be able to identify who they are.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]We'll have to trust in her skills for now,[n]then.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 0 1 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Anyway, we found out that Futaba has[n]a Palace... but can someone who isn't[n]evil have one?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]That doesn't matter.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]A Palace is the materialization of[n]distorted cognitions brought about[n]by strong desires... That's all.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]It just so happens that a lot of warped[n]people turn out evil.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][bup 0 6 3 1 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]She's so young though... The pain she's[n]gone through must be the cause of her[n]distortion.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ann]]
[s][bup 0 4 3 1 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Maybe that has something to do with[n]why she calls herself Alibaba.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]According to the chief's story, Futaba[n]has auditory and visual hallucinations,[n]right?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]There's a chance those are related[n]to some important memories she's[n]holding.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 58 65535 0]It's hard to explain... but those memories[n]may have been warped by the distortions.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Basically we just gotta steal her Treasure,[n]right?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Well, yeah.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ann]]
[s][bup 0 4 2 1 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]So do we all agree about taking on[n]Futaba's Palace?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]She's asked us to do so. I don't think that[n]part is an issue.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]If we heal Futaba's heart, it will not only[n]help Boss, but she can then assist us with[n]Medjed.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Yusuke]]
[s][bup 0 5 1 1 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]I agree.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][bup 0 2 3 1 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]I've been wonderin' about how Boss said[n]"a lot happened" after Futaba's mom[n]died too.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Hold on a second.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Our investigation of her Palace may not[n]go like anything we've done up to this[n]point.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][bup 0 2 4 1 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Why's that?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Having an individual ask you to steal[n]their heart is an extremely irregular case.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]There's no telling what the Palace ruler's[n]disposition will be like, or the distortion[n]that'll be there.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]We may run into some unforeseen[n]situations. Do you still want to go in?[n][f 1 3 65535][w][e]

[sel SEL_025_0_0 top]
[s]Yeah, let's do it.[e]
[s]What should we do...?[e]

[msg MSG_026_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Are you afraid? Now is no time to be[n]indecisive.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 11 1 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]We gotta do this.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]All right. Let's just make sure we're[n]cautious.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Well, let's get crackin' on those[n]keywords, huh?[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]The ones we have at the moment are[n]"Futaba Sakura" and "Sojiro Sakura's[n]house."[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Ryuji]]
[s][bup 0 2 11 1 0][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]We got the "who" and the "where," so[n]all that's left is the "what," right?[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Yusuke]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Let us try going to their house first.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Ann]]
[s][bup 0 4 0 1 0][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]Boss is busy running the café, isn't he?[n]We should make sure he doesn't suspect[n]anything.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]Important memories, huh...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]I'll be able to remember everything if[n]I turn back into a human, right?[n][f 1 3 65535][w][e]

[sel SEL_037_0_0 top]
[s]I hope so.[e]
[s]I don't know.[e]
[s]You sure you're human?[e]

[msg MSG_038_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]That has to be the case.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]No, I'm sure I'll remember![n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 3 301 1][vp 8 0 0 51 65535 0]That's not important! I'm talking about[n]my memories here![n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]I... definitely want this mission[n]to succeed.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]If we can retrieve Futaba's memories,[n]then I'd bet we can get mine back too...[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]In any case, it's not every day you[n]stumble upon a hacker like her around.[n][f 1 3 65535][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 55 65535 0]You really do have a gift, don't you?[n][f 1 3 65535][w][e]

[sel SEL_043_0_0 top]
[s]Who knows?[e]
[s]I'm just lucky.[e]

[msg MSG_044_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 56 65535 0]You sure live up to my expectations.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 57 65535 0]Hey, they went on without us! Let's hurry[n]and catch up to them![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 1 0 0 0 0 0]I can sense a firm resolve[n]from Morgana...[n][f 1 3 65535][w][e]

