[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Are there still more?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]How should I know?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A timeworn pyramid, the revival of the[n]dead... All of this is supremely intriguing...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Don't take my word for this...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]But I've heard ancient Egyptians believed[n]the soul was eternal and that the dead[n]will rise again.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah yes, that belief in resurrection is why[n]they began mummifying the dead.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]They thought those things were gonna[n]come back to life? But they're[n]all dried out![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Even back then, people must have wished[n]for the day when they would[n]be reunited with their loved ones.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Urgh, enough of this shit! We ain't[n]at school, y'know![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]If we don't hurry and steal the Treasure,[n]we're gonna end up mummies ourselves![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You're right. Let's keep going.[n][f 1 3 65535][w][e]

