[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 104 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Shiiiiiit![n][f 1 2 60][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Ngh, is this...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Quicksand! Everyone, swim with all[n]your might![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 107 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]...Hey, you guys still alive?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 105 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Oww...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]First a boulder, then this... Did we[n]piss her off somehow?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]I don't think it has anything to do with[n]us angering her...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]I suspect the problem is that she can't[n]control her instinct to push people away[n]from her.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][bup 0 6 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]A simple defense mechanism...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Considering what she's been through,[n]I don't blame her for mistrusting others.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Joker, let's save her! We've gotta help[n]Futaba-chan open the door to her heart![n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]Of course.[e]
[s]Let's escape first.[e]

[msg MSG_014_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]I have no objections, but we should[n]worry about ourselves first and foremost.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Come on, let's look for a way back[n]above ground. Otherwise this place[n]is going to end up our tomb too.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Right, we should worry about ourselves[n]first and foremost.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Come on, let's look for a way back[n]above ground. Otherwise this place[n]is going to end up our tomb too.[n][f 1 3 65535][w][e]

