[msg MSG_000_0_0 [TV Reporter]]
[s][vp 8 0 0 39 65535 0]The date that Medjed has set for the[n]alleged cleanse is 8/21. That day is fast[n]approaching.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 2 65535 0]The Phantom Thieves, whom they[n]singled out, have not made any[n]notable actions at this time.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 3 65535 0]Will Medjed carry out their[n]cyberterrorism?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][bup 0 6 2 1 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]In order to stop them, we need to help[n]Futaba Sakura before the 21st.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]Our deadline is about two days prior,[n]so the 19th.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Meetin' up in Shibuya then comin' here's[n]a pain, right? Let's make this place our[n]hideout for a while.[n][f 1 3 65535][w][e]

[sel SEL_002_3_0 top]
[s]Sounds good.[e]
[s]Convenient.[e]

[msg MSG_002_7_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Is everyone fine with this place being our[n]next hideout then?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]We must take care not to be discovered[n]by Boss.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]There's no telling what may happen[n]inside that pyramid.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]We all need to be cautious so that place[n]doesn't become our graveyard.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 1 1 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Man, this is gonna be one crazy summer[n]vacation.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]We're dealin' with international hackers and[n]lookin' for a Treasure in a pyramid.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ann]]
[s][bup 0 4 2 1 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]How can you be enjoying this? This is[n]a crisis of whether or not our group[n]continues on, you know!?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 11 1 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]I know that![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 2 1 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]That reminds me. While we were in the[n]Mona Car, you were staring at me with[n]a dirty look, you perv.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 13 300 1][vp 8 0 0 20 65535 0]Shuddup! It was a great view![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][bup 0 2 1 1 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]You guys were lookin' too, am I right!?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Yusuke]]
[s][bup 0 5 1 1 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Indeed. The pyramid's golden ratio was[n]truly a sight to behold.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 7 1 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]That ain't what I'm talkin' about...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]I wasn't staring, Lady Ann.[n]I'm a gentleman, after all.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ann]]
[s][bup 0 4 2 1 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]It's not that you "weren't," but that you[n]"couldn't" since you were transformed,[n]am I right?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [(SE)新島 真]]
[s][vp 8 0 0 35 65535 0](溜息)[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Makoto]]
[s][bup 0 6 3 1 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Will we be all right like this?[n][f 1 3 65535][w][e]

[msg SYS_027_0_0]
[s][vp 8 0 0 0 65535 0]Your hideout has moved from the[n]Shibuya Teikyu Building Accessway[n]to the [clr 2]Yongen-Jaya Café Leblanc[clr 27].[n][f 1 3 65535][w][e]

