[msg dummy]
[s]......[n][w][e]

[msg D00_LAVENZA_BATTLE_01_MS [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 55407 65535 0]Permita-me experimentar para mim os[n]resultados de sua verdadeira reabilitação.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você está preparado agora?[n][w][e]

[sel D00_LAVENZA_BATTLE_01_SE top]
[s]Estou pronto para ir.[e]
[s]Um segundo.[e]

[msg D00_LAVENZA_BATTLE_01_MS_2 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 55435 65535 0]Obrigada.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E agora, vamos começar![n][w][e]

[msg D00_LAVENZA_BATTLE_01_MS_3 [Lavenza]]
[s][bup 0 100 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 55437 65535 0]Eu vejo...[n][w][e]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nesse caso, volte para mim quando você[n]realmente se preparar.[n][w][e]

