[msg MSG_BTLTALK_START_000 [Robô Chefe de Escritório]]
[s][vp 8 2 2 0 0 0]É POR CULPA DE PREGUIÇOSOS[n]COMO VOCÊ QUE O DIRETOR[n]É GROSSEIRO COMIGO![n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0]SEMPRE ME LIGA [clr 2]INÚTIL[clr 27][n]OU [clr 2]INCONFIÁVEL[clr 27].[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0]NÃO É INJUSTO PARA VOCÊ[n]SEMPRE E SÓ COMIGO?[n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_START_001 [Futaba]]
[s][bup 0 8 600 0 0][vp 8 2 2 9021 0 8][f 4 10 65535 0 0]Aparentemente, ele não[n]gosta do gerente dele.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Vamos tirar[n]informações dele, Joker![n][f 1 3 65535][w][e]

[sel SEL_BTLTALK_00_001 top]
[s]Você odeia o gerente?[e]
[s]Como é o gerente?[e]

[msg MSG_BTLTALK_FIRST_001 [Robô Chefe de Escritório]]
[s][vp 8 2 2 0 0 0]TODO MUNDO ODEIA ESSE CARA![n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0]FICA DIZENDO A TODOS QUE[n]SOMOS [clr 2]INÚTEIS[clr 27]. NÓS TEMOS[n]QUE FICAR EVITANDO ELE![n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0]UGH... COMO EU GOSTARIA QUE ALGUÉM[n]GOSTARIA ISSO PARA NÓS.[n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_FIRST_002 [Robô Chefe de Escritório]]
[s][vp 8 2 2 0 0 0]"INSUPORTÁVEL É PROVAVELMENTE[n]A PALAVRA QUE O DESCREVE[n]MELHOR![n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0]ELE TEM CORAGEM DE LIGAR PARA[n]TODO MUNDO E CHAMAR DE [clr 2]INÚTIL[clr 27] MESMO[n]QUE SEJA ELE O PREGUIÇOSO![n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0]XINGAMENTO! SE SOMENTE O[n]GERENTE DECIONAL DESAPARECESSE, EU SERIA[n]O FAVORITO PARA UMA PROMOÇÃO...[n][f 1 3 65535][w][e]

[sel SEL_BTLTALK_00_002 top]
[s]Eu poderia fazer isso acontecer, se...[e]
[s]Bem, vamos fazer um acordo...[e]

[msg MSG_BTLTALK_2ND_003 [Robô Chefe de Escritório]]
[s][vp 8 2 2 0 0 0]VOCÊ O QUE!?! VOCÊ ESTÁ ME DIZENDO[n]QUE VAI SE LIVRAR DELE PARA MIM?[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0]...NÃO PARE! VOCÊ ESTÁ MENTINDO![n]SÓ QUER INFORMAÇÕES[n]SOBRE O DIRETOR DE SEÇÃO![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_2ND_003_1 [Robô Chefe de Escritório]]
[s][vp 8 2 2 0 0 0]...ARGH, Droga! EU DEVERIA ME LIVRAR DA[n]CACA FACILMENTE[n]COM MEU PODER DO [clr 2]VENTO[clr 27]![n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0]MAS... EU... ESTOU COM MUITO[n]MEDO PARA... UGH![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_END_000 [Futaba]]
[s][bup 0 8 601 0 0][vp 8 2 2 9190 0 8][f 4 10 65535 0 0]Mueheheheh, então o gerente de[n]seção é fraco para [clr 2]Vento[clr 27], hein?[n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_END_001 [Futaba]]
[s][bup 0 8 600 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Não obtivemos nenhum detalhe[n]sobre o diretor-chefe, mas esta[n]informação ainda será útil![n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Parece que este acabou[n]falando. Podemos ir, Joker![n][f 1 3 65535][w][e]


