[msg MSG_BTL_START_000 [Shadow Aino]]
[s][vp 8 2 2 50846 1 73]Serei o único a proteger as bolas de neve![n]Não vou deixar ninguém ficar no meu caminho![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYS_MSG]
[s][vp 8 2 2 0 0 0]Ao escolher as respostas corretas, você[n]poderá mudar o coração do alvo.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0]Use as informações que você obteve para[n]alterar o coração do alvo![n][f 1 3 65535][w][e]

[msg MSG_BTL_DIA_BF__000_000 [Shadow Aino]]
[s][vp 8 2 2 50858 1 73]Eu não vou perder! Não tem jeito![n][f 1 3 65535][w][e]

[msg MSG_BTL_DIA_BF__000_001 [Shadow Aino]]
[s][vp 8 2 2 50845 1 73]Se eu for embora, quem vai proteger todas as[n]bolas de neve!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_FAILD [Morgana]]
[s][bup 0 3 4 0 0][vp 8 2 2 1029 0 3][f 4 10 65535 0 0]Merda, não conseguimos acalmá-la![n]Teremos que encontrar uma maneira diferente![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_START_000 [Shadow Aino]]
[s][vp 8 2 2 50830 1 73]Por favor! Pare![n][f 1 3 65535][w][e]
[s][vp 8 2 2 50852 1 73]Se eu for embora, não haverá ninguém[n]protegendo as bolas de neve![n][f 1 3 65535][w][e]

[msg MSG_BTL_START_001 [Morgana]]
[s][bup 0 3 4 0 0][vp 8 2 2 1038 0 3][f 4 10 65535 0 0]Joker, parece que há algo acontecendo com[n]este. Talvez devêssemos tentar falar com[n]eles.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Ok, aqui está o que sabemos sobre ela.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Ela está chamando os gatos que ela catnou de[n]"bolas de neve", os gatos estão[n]"estressados"...[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]E, finalmente, "os donos de animais estão[n]desistindo".[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_000 [Shadow Aino]]
[s][vp 8 2 2 50801 1 73]Tudo o que quero fazer é proteger as bolas[n]de neve.[n]Eu tenho que protegê-los, só tenho que[n]protegê-los![n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP01_000 top]
[s]Apenas desista.[e]
[s]Acalmar.[e]

[msg MSG_BTL_HOLDUP01_002_000 [Shadow Aino]]
[s][vp 8 2 2 50833 1 73]Não há como desistir![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_000 [Shadow Aino]]
[s][vp 8 2 2 50849 1 73]Estou calmo... claro que estou calmo...[n][f 1 3 65535][w][e]
[s][vp 8 2 2 50876 1 73]Eu preciso ficar calmo para as bolas de neve.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_001 [Morgana]]
[s][bup 0 3 2 0 0][vp 8 2 2 1025 0 3][f 4 10 65535 0 0]O que ela quer dizer com bolas de neve?[n]Isso é tão esquisito.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]São todos os gatos que as bolas de neve!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_002 [Shadow Aino]]
[s][vp 8 2 2 50849 1 73]Bolas de neve são bolas de neve...[n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP02_000 top]
[s]Existem muitas bolas de neve?[e]
[s]Eles são os gatos que você catnap?[e]

[msg MSG_BTL_HOLDUP02_001_000 [Shadow Aino]]
[s][vp 8 2 2 50801 1 73]Isso mesmo... eles são todos bolas de neve.[n]Eu tenho que protegê-los.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_002_000 [Shadow Aino]]
[s][vp 8 2 2 50801 1 73]Eu não os coloquei... estou protegendo-os.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_001 [Shadow Aino]]
[s][vp 8 2 2 50842 1 73]Enquanto eu os proteger, as bolas de neve[n]ficarão felizes...[n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP03_000 top]
[s]Eles estão infelizes assim.[e]
[s]Os gatos estão estressados.[e]
[s]Você não parece feliz.[e]

[msg MSG_BTL_HOLDUP03_002_000 [Shadow Aino]]
[s][vp 8 2 2 50833 1 73]Eu não dou a mínima para minha felicidade![n]Tudo o que importa é manter as bolas de neve[n]seguras![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_000 [Shadow Aino]]
[s][vp 8 2 2 50849 1 73]W-Well isso é...[n][f 1 3 65535][w][e]
[s][vp 8 2 2 50852 1 73]Mas se eu não ficar de olho nas bolas de[n]neve, elas também morrerão...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_001 [Morgana]]
[s][bup 0 3 2 0 0][vp 8 2 2 1038 0 3][f 4 10 65535 0 0]Eles vão morrer "também"?[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Então a verdadeira bola de neve já se foi?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_002 [Morgana]]
[s][bup 0 3 2 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Ok, acho que temos isso. Ela está calma o[n]suficiente para conversarmos com ela agora.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Vá em frente, Joker![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_003 [Shadow Aino]]
[s][vp 8 2 2 0 0 0]......[n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP04_000 top]
[s]Os gatos querem ir para casa.[e]
[s]A bola de neve se foi...[e]

[msg MSG_BTL_TALK_OFF [Shadow Aino]]
[s][vp 8 2 2 0 0 0]Você não pode falar com ela![n][f 1 3 65535][w][e]

[msg MSG_BTL_BTLEND_000_000 [Shadow Aino]]
[s][vp 8 2 2 50857 1 73]Você tem razão.[n][f 1 3 65535][w][e]

