[msg MSG_BTLSTART_000 [Sombra de Arihara]]
[s][vp 8 2 2 50245 1 702]As mulheres caem aos meus pés sem que eu levante[n]um dedo. Quem sabe quem será o próximo[n]escravo...?[n][f 1 3 65535][w][e]

[msg MSG_BTLREACTION_000 [Sombra de Arihara]]
[s][vp 8 2 2 50242 1 702]Heheheh...[n]Agora, olhem meu talento.[n][f 1 3 65535][w][e]

[msg MSG_BTLREACTION_MONA_01 [Morgana]]
[s][vp 8 2 2 1040 0 3][bup 0 3 4 0 0][f 4 10 65535 0 0]Não acredito...[n][f 1 3 65535][w][e]

[msg MSG_BTLREACTION_001 [Sombra de Arihara]]
[s][vp 8 2 2 50254 1 702]Meu charme não funciona[n]em homens![n][f 1 3 65535][w][e]
[s][vp 8 2 2 50249 1 702]Ngh! O que devo fazer...?[n][f 1 3 65535][w][e]

[msg MSG_BTLREACTION_MONA_03 [Morgana]]
[s][vp 8 2 2 1104 0 3][bup 0 3 2 0 0][f 4 10 65535 0 0]Ei! Ele agora está derrotado![n]Vamos acabar com isso, Joker![n][f 1 3 65535][w][e]

[msg MSG_BTLREACTION_002 [Sombra de Arihara]]
[s][vp 8 2 2 50288 1 702]II-Meu charme não funciona?!?[n]Eles podem ser cegos?!?[n][f 1 3 65535][w][e]

[msg MSG_BTLREACTION_MONA_02 [Morgana]]
[s][vp 8 2 2 1104 0 3][bup 0 3 2 0 0][f 4 10 65535 0 0]Eles podem dar a ele um prêmio por[n]sua ostentação.[n]Vamos acabar logo com isso, Joker![n][f 1 3 65535][w][e]

