[msg MSG_BTLSTART_000 [Ombra di Ono]]
[s][vp 8 2 2 50659 1 703]Hmm... que tipo de bagunça eu poderia[n]fazer agora?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_005 [Ombra di Ono]]
[s][vp 8 2 2 50659 1 703]Mas que tipo de...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Ombra di Ono]]
[s][vp 8 2 2 50676 1 703]Ai... estou com dor em todos os lugares![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_007 [Ombra di Ono]]
[s][vp 8 2 2 50622 1 703]É sempre assim quando chove...[n]mas para causar estragos, posso[n]até ignorar a dor![n][f 1 3 65535][w][e]

