[msg MSG_BTL_START_000 [Shadow Chiyo]]
[s][vp 8 0 2 50987 1 89]Pare de falar sobre plágio! Você não sabe[n]nada sobre isso![n][f 1 3 65535][w][e]

[msg MSG_BTL_START_001 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Joker! Vamos tentar convencê-la disso! Tenho[n]certeza de que seremos capazes de mudar o[n]coração dela![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYS_MSG]
[s][vp 8 0 2 0 0 0]Ao sustentar o inimigo, você poderá[n]conversar com o alvo.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 0 0 0]Ao escolher as respostas corretas, você[n]poderá mudar o coração do alvo.[n][f 1 3 65535][w][e]

[msg MSG_BTL_DIA_BF__000_000 [Shadow Chiyo]]
[s][vp 8 0 2 50969 1 89]Hmph! Um rápido retoque e eu ficarei bem![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0 [Yusuke]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Ela curou se retocando!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0_2 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Joker, vamos tentar falar com ela! Pode ser[n]mais fácil do que lutar com ela![n][f 1 3 65535][w][e]

[msg MSG_BTL_START_003]
[s][vp 8 0 2 0 0 0]Ao sustentar o inimigo, você poderá[n]conversar com o alvo.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 0 0 0]Ao escolher as respostas corretas, você[n]poderá mudar o coração do alvo.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_000 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Pare de jogar burro e diga-nos a verdade![n]Por que você acabou plagiar?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_001 [Shadow Chiyo]]
[s][vp 8 0 2 50965 1 89]Eu não estou jogando idiota! Feche![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_002 [Shadow Chiyo]]
[s][vp 8 0 2 50972 1 89]Todos estão tentando encontrar a fonte da[n]arte on-line e outros enfeites, mas o[n]rastreamento não é ilegal![n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP01_000 top]
[s]Você não obteve permissão.[e]
[s]Se for legal, está tudo bem?[e]
[s]Então parece o mesmo?[e]

[msg MSG_BTL_HOLDUP01_001_000 [Makoto]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Se você rastreou algo que é protegido por[n]direitos autorais sem permissão, é um[n]trabalho plagiado.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_001 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Correto, é ilegal.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_002 [Shadow Chiyo]]
[s][vp 8 0 2 50970 1 89]O que é isso...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_002_000 [Shadow Chiyo]]
[s][vp 8 0 2 50933 1 89]Todos vocês precisam calar a boca! Você não[n]tem o direito de me questionar![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_002_001 [Yusuke]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Ela não estava convencida por isso, Joker![n]Vamos adotar uma abordagem diferente![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_000_000 [Shadow Chiyo]]
[s][vp 8 0 2 50969 1 89]Eles estão apenas dizendo que é plágio[n]porque estão com ciúmes da minha[n]popularidade! Que mau deles![n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP02_000 top]
[s]Pare de plagiar.[e]
[s]O quanto você ganhou?[e]
[s]Sua fama adicionou pressão.[e]

[msg MSG_BTL_HOLDUP02_001_000 [Shadow Chiyo]]
[s][vp 8 0 2 50970 1 89]O que você está falando, é claro que eu não[n]estava sob nenhum pres- [n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_001 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Você pode ficar feliz por ter se tornado[n]popular, mas essa popularidade também trará[n]críticos mais severos.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_002 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Os fãs começam a esperar mais de você.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_002_000 [Shadow Chiyo]]
[s][vp 8 0 2 50987 1 89]Estou doente e cansado de ouvir esses[n]comentários de merda![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_002_001 [Yusuke]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Ela não estava convencida por isso, Joker![n]Vamos adotar uma abordagem diferente![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_000_000 [Shadow Chiyo]]
[s][vp 8 0 2 50901 1 89]Eu até fiz um novo título como resposta para[n]meus fãs![n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP03_000 top]
[s]Qual é a nova história?[e]
[s]Isso deve ter sido difícil.[e]
[s]Marketing viral.[e]

[msg MSG_BTL_HOLDUP03_001_000 [Shadow Chiyo]]
[s][vp 8 0 2 50970 1 89]O que...! Por que eu teria problemas para[n]fazer uma nova história!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_001 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Você foi capaz de desenhar como você gostou[n]no começo, mas agora está limitado a[n]desenhar o que os fãs querem ver.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_002_000 [Shadow Chiyo]]
[s][vp 8 0 2 50959 1 73]Cale a boca ou eu vou te matar![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_002_001 [Yusuke]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Ela não estava convencida por isso, Joker![n]Vamos adotar uma abordagem diferente![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_000_000 [Shadow Chiyo]]
[s][vp 8 0 2 50933 1 73]O que há de difícil em ser popular...!?[n]Não há nada difícil nisso![n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP04_000 top]
[s]Porque você é pobre?[e]
[s]Falta de habilidade?[e]
[s]Você pode ser muito popular.[e]

[msg MSG_BTL_HOLDUP04_001_000 [Shadow Chiyo]]
[s][vp 8 0 2 50901 1 73]N-no! Eu-eu sou um gênio! UM GÊNIO![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_001 [Yusuke]]
[s][bup 0 5 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Você começa a ter noites sem dormir. Você[n]fica acordado até tarde, pensando consigo[n]mesmo "talvez eu não tenha o que é[n]preciso"...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_002 [Yusuke]]
[s][bup 0 5 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Muitos autores lutaram com isso no passado,[n]e tenho certeza de que haverá mais à medida[n]que o tempo passa...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_003 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]No entanto, não é essa a razão pela qual as[n]pessoas continuam trabalhando duro?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_004 [Shadow Chiyo]]
[s][vp 8 0 2 50957 1 73]Ah...![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_005 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Eu entendo a sensação de querer fugir. É[n]preciso uma quantidade incrível de[n]habilidade para criar algo para os outros[n]verem.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_006 [Yusuke]]
[s][bup 0 5 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Mas você fez algo para arruinar todo o[n]trabalho duro que construiu. O que você[n]estava tentando proteger...?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_007 [Yusuke]]
[s][bup 0 5 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Quero que você tente e lembre-se do que era[n]mais importante para você como artista.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_008 [Shadow Chiyo]]
[s][vp 8 0 2 50957 1 73]O que foi mais importante para mim...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_002_000 [Shadow Chiyo]]
[s][vp 8 0 2 50959 1 73]A--você é estúpido!? Todos vocês odiadores[n]devem ir para o inferno![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_002_001 [Yusuke]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Ela não estava convencida por isso, Joker![n]Vamos adotar uma abordagem diferente![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_OFF [Shadow Chiyo]]
[s][vp 8 2 2 0 0 0]Você não pode falar com ela![n][f 1 3 65535][w][e]

[msg MSG_BTL_BTLEND_000 [Shadow Chiyo]]
[s][vp 8 0 2 50930 1 73]Pares em quadrinhos... isso é o mais[n]importante para mim.[n][f 1 3 65535][w][e]

