[msg MSG_BTL_FLYENTRY_000_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1001 1 213]Hehehe! Ser jovem[n]é um crime grave![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYENTRY_010_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1002 1 213]Os jovens são ingênuos e impulsivos,[n]e nem percebem[n]como são estúpidos.[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYENTRY_020_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1003 1 213]Eu simplesmente não pude evitar[n]explorar aqueles idiotas, posso?[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYUNDER50_000_0 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1004 1 213]Hahaha! Você vai continuar[n]tentando até o fim, hein?[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYUNDER50_010_0 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1005 1 213]Chega de jogos. Nunca[n]perdoarei bandidos como você.[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYUNDER50_020_0 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1006 0 6]Nós dizemos isso![n]É melhor você se preparar![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_001_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1007 1 213]Ngh... Aaargh...[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_002_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1008 0 3]Continue assim Joker! Encurrale-o![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_000_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1009 1 213]Droga...![n]Malditos bandidos...![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_000_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1010 0 3]Não tenha piedade! Vamos terminar![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_010_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1011 1 213]Agh... Mas o que...? Seus bandidos[n]são mais fortes do que parecem...[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_020_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1012 1 213]Parece que[n]deve usar artilharia...![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_030_000 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1013 0 3]Você é só fumaça e nada de fogo![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_040_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1014 1 213]Eheheh... Isso veremos...[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_060_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1015 1 213]É hora de apresentá-lo a você...![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_070_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1016 1 213]Aqui está... meu robô guardião![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_080_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1017 1 213]Giahahahahaha! Pronto para morrer!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_090_002 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1018 0 3]Um porco?!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_100_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1019 1 213]Isso não é um porco! Ele é o[n]guardião de defesa mecânica[n]do meu palácio, Piggytron![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1020 1 213]Me confrontar é um crime[n]muito grave, sabia? Agora vocês[n]todos vão para o inferno![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_110_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1021 0 3]Xingamento...! Eu não esperava que[n]ele tivesse um ás na manga![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_120_005 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 6]Joker! Por favor,[n]vamos reorganizar se você acha[n]que estamos com problemas![n][f 1 3 65535][w][e]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1023 0 6]Essa engenhoca é colossal...[n]Se ela nos atacar enquanto nossa[n]energia estiver baixa, será o nosso fim![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_130_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1024 0 6]Joker! Vamos reorganizar se[n]você acha que estamos com problemas![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1025 0 6]Temos que derrubar aquele robô gigante[n]mas se ele nos atacar enquanto[n]estivermos enfraquecidos, será um problema![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_000_0 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1026 1 214]Vocês bandidos realmente me dão nos nervos! Você[n]ligou para o meu Piggytron pig mais cedo, hein?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_010_0 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1027 1 214]Você também estava se referindo a mim quando[n]disse isso? Se sim... eu vou acabar com você![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_020_0 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1028 1 214]Vai, Piggytron! Formulário Super VIP![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_030_0 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1029 0 3]Se tornou?!? O que ele[n]vai fazer?!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_040_0 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1030 0 3]Não me diga que ele está[n]pensando em nos atropelar![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_050_0 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1031 0 3]Se tornou?!? Não me diga[n]que ele quer nos dominar![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGSPECIAL_000_0 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1032 1 214]O que você tem?!? Meu Piggytron[n]dá muito medo e você não consegue[n]falar mais, né? Muahahahah![n][f 1 3 65535][w][e]

[msg MSG_PARTY_ORDER02_000_00 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Huh?!? Aquele desgraçado quer[n]atropelar a gente de novo?!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_ORDER02_010_00 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1036 0 3]O que nós fazemos? Vamos tentar[n]distrair Kaneshiro?!?[n][f 1 3 65535][w][e]

[sel SEL_PARTY_ORDER02_020_00 top]
[s]Como fazemos isso?[e]
[s]Não, vamos socá-lo.[e]
[s]Alguém tem que ser a isca.[e]

[msg MSG_PARTY_ORDER02_030_00 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]Como você pode ver, Kaneshiro[n]é claramente um escravo do dinheiro![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1039 0 3]Podemos conseguir[n]sua atenção com[n]um item caro...![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1040 0 3]Vamos tentar, Joker! Você decide[n]qual item usar![n][f 1 3 65535][w][e]

[msg MSG_PARTY_ORDER_032_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]Não seja ridículo![n]Existe outro jeito![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1042 0 3]Como você bem sabe, Kaneshiro[n]é um escravo do dinheiro.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 3]Jogar para ele um objeto caro[n]poderia atrair sua atenção[n]para distraí-lo...![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1044 0 3]Vamos tentar, Joker! Você decide[n]qual item usar![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_010_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Huh?!? Aquele desgraçado quer[n]atropelar a gente de novo?!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_200_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1037 0 3]Qual é o plano? Devemos jogá-lo fora como antes,[n]ou você prefere encontrar outra solução?[n][f 1 3 65535][w][e]

[sel SEL_PARTY_TSUIKA02_020_0 top]
[s]Outra maneira?[e]
[s]Não, vamos socá-lo.[e]
[s]Alguém tem que ser a isca.[e]

[msg MSG_PARTY_TSUIKA_300_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]Não seja ridículo![n]Existe outro jeito![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_400_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]Como você bem sabe, Kaneshiro[n]é um escravo do dinheiro.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1039 0 3][f 4 10 65535 0 0]Jogar para ele um objeto caro[n]poderia atrair sua atenção[n]para distraí-lo![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1040 0 3]Vamos tentar, Joker! Você decide[n]qual item usar![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_000_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Huh?!? Aquele desgraçado quer[n]atropelar a gente de novo?!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_100_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1034 0 3]O que nós fazemos? Vamos tentar[n]distrair Kaneshiro?!?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1035 0 3][f 4 10 65535 0 0]Dessa forma, não pararíamos[n]a carga também? Talvez[n]possamos usar contra ele![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_500_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1200 0 3]Prestes a nos carregar de novo...[n]Ei Joker, eu tenho uma ideia.[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_700_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1201 0 3]Atacá-lo é bom...[n]mas por que não encontramos[n]outra maneira de distraí-lo?[n][f 1 3 65535][w][e]

[sel SEL_PARTY_TSUIKA_100_000 top]
[s]Outra maneira?[e]
[s]Não, vamos socá-lo.[e]
[s]Alguém tem que ser a isca.[e]

[msg MSG_PARTY_TSUIKA_800_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]Não seja ridículo![n]Existe outro jeito![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_900_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]Como você bem sabe, Kaneshiro[n]é um escravo do dinheiro.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1043 0 3]Jogar para ele um objeto caro[n]poderia atrair sua atenção[n]para distraí-lo![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1044 0 3]Vamos tentar, Joker! Você decide[n]qual item usar![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGSHOOT_000_000 [Ombra di Kaneshiro]]
[s]Gah![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGSHOOT_100_000 [Ombra di Kaneshiro]]
[s]Aaaaargh![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGSHOOT_200_000 [Ombra di Kaneshiro]]
[s]Ngh... Aaargh...[n][f 1 3 65535][w][e]
[s]Como você ousa?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGSHOOT_300_000 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1194 0 3]Ele está com problemas. Temos que continuar[n]mantendo ele sob pressão![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGOPEN_000_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1060 1 214]Huh...? E o que é isso?!? Ele brilha[n]como uma coisa preciosa![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGOPEN_010_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1061 1 214]Vá pegá-lo, Piggytron![n]Rápido![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGOPEN_020_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1062 1 214]...Wooow![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1063 0 214]Vai valer uma fortuna![n]Ótimo saque![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGOPEN_030_002 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1064 0 3]Funcionou...?!?[n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1065 0 3]Agora não precisamos mais[n]preocupar-nos em ser atropelados![n]Bom trabalho, Joker![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGWAIT_000_000 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1068 1 214]Oooh, isso não é ruim![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1069 1 214]Quando eu penhorar essa coisa,[n]posso pegar algumas garotas...[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGWAIT_010_002 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1070 0 3]Kaneshiro está totalmente distraído...[n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1071 0 3]Vamos atacá-lo enquanto ele está com a guarda[n]baixa! É certo que um avarento como ele seja[n]arruinado pelo dinheiro![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGCLOSED_000_00 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1072 1 214]Como você pensa em sujar[n]meu banco assim?!? O que diabos[n]te ensinam na escola hein?!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGCLOSED_010_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 2 1073 0 3]Não, eles não ligam...[n][f 1 3 65535][w][e]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 2 1074 0 3]Devemos usar algo[n]mais valioso...?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER25_000_0 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1075 1 214]Amaldiçoado... Como você ousa[n]ferir meu Piggytron![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER25_010_0 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1076 1 214]Meu Piggytron está vazando...?[n]Não, impossível![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER25_020_0 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1077 0 6]Seu destino está selado...[n]Você terminará mal.[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYENTRY_000_000_2 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1001 1 213]Hehehe! Ser jovem[n]é um crime grave![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYENTRY_010_000_2 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1002 1 213]Os jovens são ingênuos e impulsivos,[n]e nem percebem[n]como são estúpidos.[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYENTRY_020_000_2 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1003 1 213]Eu simplesmente não pude evitar[n]explorar aqueles idiotas, posso?[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYUNDER50_000_0_2 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1004 1 213]Hahaha! Você vai continuar[n]tentando até o fim, hein?[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYUNDER50_010_0_2 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1005 1 213]Chega de jogos. Nunca[n]perdoarei bandidos como você.[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYUNDER50_020_0_2 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1006 0 6]Nós dizemos isso![n]É melhor você se preparar![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_001_000EX [Ombra di Kaneshiro]]
[s][vp 8 0 2 1007 1 213]Ngh... Aaargh...[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_002_002EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1008 0 3]Continue assim, Joker![n]Coloque-o em um canto![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_000_000EX [Ombra di Kaneshiro]]
[s][vp 8 0 2 1009 1 213]Droga...! Malditos bandidos...![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_000_002EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1010 0 3]Não tenha piedade! Vamos terminar![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_010_000EX [Ombra di Kaneshiro]]
[s][vp 8 0 2 1011 1 213]Agh... Mas o que...? Seus bandidos[n]são mais fortes do que parecem...[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_020_000EX [Ombra di Kaneshiro]]
[s][vp 8 0 2 1012 1 213]Parece que[n]deve usar artilharia...![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_030_000EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1013 0 3]Você é só fumaça e nada de fogo![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_040_000EX [Ombra di Kaneshiro]]
[s][vp 8 0 2 1014 1 213]Eheheh... Isso veremos...[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_060_000EX [Ombra di Kaneshiro]]
[s][vp 8 0 2 1015 1 213]É hora de apresentá-lo a você...![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_070_000EX [Ombra di Kaneshiro]]
[s][vp 8 0 2 1016 1 213]Aqui está... meu robô guardião![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_080_000EX [Ombra di Kaneshiro]]
[s][vp 8 0 2 1017 1 213]Giahahahahaha! Pronto para morrer!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_090_002EX [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1018 0 3]Um porco?!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_100_000EX [Ombra di Kaneshiro]]
[s][vp 8 0 2 1019 1 213]Isso não é um porco! Ele é o[n]guardião de defesa mecânica[n]do meu palácio, Piggytron![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1020 1 213]Me confrontar é um crime[n]muito grave, sabia? Agora vocês[n]todos vão para o inferno![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_110_002EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1021 0 3]Xingamento...! Eu não esperava que[n]ele tivesse um ás na manga![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_120_005EX [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 6]Joker! Por favor,[n]vamos reorganizar se você acha[n]que estamos com problemas![n][f 1 3 65535][w][e]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1023 0 6]Essa engenhoca é colossal...[n]Se ela nos atacar enquanto nossa[n]energia estiver baixa, será o nosso fim![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_130_002EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1024 0 6]Joker! Vamos reorganizar se[n]você acha que estamos com problemas![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1025 0 6]Temos que derrubar aquele robô gigante[n]mas se ele nos atacar enquanto[n]estivermos enfraquecidos, será um problema![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_000_0_2 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1026 1 214]Vocês bandidos realmente me dão nos nervos! Você[n]ligou para o meu Piggytron pig mais cedo, hein?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_010_0_2 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1027 1 214]Você também estava se referindo a mim quando[n]disse isso? Se sim... eu vou acabar com você![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_020_0_2 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1028 1 214]Vai, Piggytron! Formulário Super VIP![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_030_0_2 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1029 0 3]Se tornou?!? O que ele[n]vai fazer?!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_040_0_2 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1030 0 3]Não me diga que ele está[n]pensando em nos atropelar![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_050_0_2 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1031 0 3]Se tornou?!? Não me diga[n]que ele quer nos dominar![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGSPECIAL_000_0_2 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1032 1 214]O que você tem?!? Meu Piggytron[n]dá muito medo e você não consegue[n]falar mais, né? Muahahahah![n][f 1 3 65535][w][e]

[msg MSG_PARTY_ORDER02_000_00_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Huh?!? Aquele desgraçado quer[n]atropelar a gente de novo?!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_ORDER02_010_00_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1036 0 3]O que nós fazemos? Vamos tentar[n]distrair Kaneshiro?!?[n][f 1 3 65535][w][e]

[sel SEL_PARTY_ORDER02_020_00_2 top]
[s]Como fazemos isso?[e]
[s]Não, vamos socá-lo.[e]
[s]Alguém tem que ser a isca.[e]

[msg MSG_PARTY_ORDER02_030_00_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]Como você pode ver, Kaneshiro[n]é claramente um escravo do dinheiro![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1039 0 3]Podemos conseguir[n]sua atenção com[n]um item caro...![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1040 0 3]Vamos tentar, Joker! Você decide[n]qual item usar![n][f 1 3 65535][w][e]

[msg MSG_PARTY_ORDER_032_002E [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]Não seja ridículo![n]Existe outro jeito![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1042 0 3]Como você pode ver, Kaneshiro[n]é claramente um escravo do dinheiro![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 3]Jogar para ele um objeto caro[n]poderia atrair sua atenção[n]para distraí-lo![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1044 0 3]Vamos tentar, Joker! Você decide[n]qual item usar![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_010_002_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Huh?!? Aquele desgraçado quer[n]atropelar a gente de novo?!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_200_002_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1037 0 3]Qual é o plano? Devemos jogá-lo fora como antes,[n]ou você prefere encontrar outra solução?[n][f 1 3 65535][w][e]

[sel SEL_PARTY_TSUIKA02_020_0_2 top]
[s]Outra maneira?[e]
[s]Não, vamos socá-lo.[e]
[s]Alguém tem que ser a isca.[e]

[msg MSG_PARTY_TSUIKA_300_002_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]Não seja ridículo![n]Existe outro jeito![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_400_002_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]Como você bem sabe, Kaneshiro[n]é um escravo do dinheiro.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1039 0 3][f 4 10 65535 0 0]Jogar para ele um objeto caro[n]poderia atrair sua atenção[n]para distraí-lo![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1040 0 3]Vamos tentar, Joker! Você decide[n]qual item usar![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_000_002_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Huh?!? Aquele desgraçado quer[n]atropelar a gente de novo?!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_100_002_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1034 0 3]O que nós fazemos? Vamos tentar[n]distrair Kaneshiro?!?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1035 0 3][f 4 10 65535 0 0]Dessa forma, não pararíamos[n]a carga também? Talvez[n]possamos usar contra ele![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_500_002_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1200 0 3]Prestes a nos carregar de novo...[n]Ei Joker, eu tenho uma ideia.[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_700_002_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1201 0 3]Atacá-lo é bom...[n]mas por que não encontramos[n]outra maneira de distraí-lo?[n][f 1 3 65535][w][e]

[sel SEL_PARTY_TSUIKA_100_000_2 top]
[s]Outra maneira?[e]
[s]Não, vamos socá-lo.[e]
[s]Alguém tem que ser a isca.[e]

[msg MSG_PARTY_TSUIKA_800_002_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]Não seja ridículo![n]Existe outro jeito![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_900_002_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]Como você bem sabe, Kaneshiro[n]é um escravo do dinheiro.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1043 0 3]Jogar para ele um objeto caro[n]poderia atrair sua atenção[n]para distraí-lo![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1044 0 3]Vamos tentar, Joker! Você decide[n]qual item usar![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGSHOOT_000_000_2 [Ombra di Kaneshiro]]
[s]Gah![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGSHOOT_100_000_2 [Ombra di Kaneshiro]]
[s]Aaaaargh![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGSHOOT_200_000_2 [Ombra di Kaneshiro]]
[s]Ngh... Aaargh...[n][f 1 3 65535][w][e]
[s]Como você ousa?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGSHOOT_300_000_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1194 0 3]Ele está com problemas. Temos que continuar[n]mantendo ele sob pressão![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGOPEN_000_000E [Ombra di Kaneshiro]]
[s][vp 8 0 2 1060 1 214]Huh...? E o que é isso?!? Ele brilha[n]como uma coisa preciosa![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGOPEN_010_000E [Ombra di Kaneshiro]]
[s][vp 8 0 2 1061 1 214]Vá buscá-lo, Piggytron![n]Rápido![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGOPEN_020_000E [Ombra di Kaneshiro]]
[s][vp 8 0 2 1062 1 214]...Wooow![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1063 0 214]Vai valer uma fortuna![n]Ótimo saque![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGOPEN_030_002E [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1064 0 3]Funcionou...?!?[n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1065 0 3]Agora não precisamos mais[n]preocupar-nos em ser atropelados![n]Bom trabalho, Joker![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGWAIT_000_000E [Ombra di Kaneshiro]]
[s][vp 8 0 2 1068 1 214]Oooh, isso não é ruim![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1069 1 214]Quando eu penhorar essa coisa,[n]posso pegar algumas garotas...[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGWAIT_010_002E [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1070 0 3]Kaneshiro está totalmente distraído...[n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1071 0 3]Vamos atacá-lo enquanto ele está com a guarda[n]baixa! É certo que um avarento como ele seja[n]arruinado pelo dinheiro![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGCLOSED_000_00_2 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1072 1 214]Como você pensa em sujar[n]meu banco assim?!? O que diabos[n]te ensinam na escola hein?!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGCLOSED_010_00_2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 2 1073 0 3]Não, eles não ligam...[n][f 1 3 65535][w][e]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 2 1074 0 3]Devemos usar algo[n]mais valioso...?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER25_000_0_2 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1075 1 214]Amaldiçoado... Como você ousa[n]ferir meu Piggytron![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER25_010_0_2 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1076 1 214]Meu Piggytron está vazando...?[n]Não, impossível![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER25_020_0_2 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1077 0 6]Seu destino está selado...[n]Você terminará mal.[n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_START [Ombra di Kaneshiro]]
[s][vp 8 0 2 1083 1 214]Que diabos... Meu Piggytron![n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_START2 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1084 1 214]Tudo bem! Vou lidar com vocês[n]covardes sozinho. Com o poder do dinheiro![n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_START3 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1006 0 6]É hora de um confronto![n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_BLOCK [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1090 0 3]O que!?! Eles o impediram?[n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_BLOCK2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]Mmm... A técnica do escudo é uma verdadeira dor[n]de cabeça... E se colocá-los dormecidos?[n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_TROUBLE [Ombra di Kaneshiro]]
[s][vp 8 0 2 1089 1 214]O negócio não poderia ser[n]melhor... todo esse dinheiro vai[n]direto para MIM![n][f 1 3 65535][w][e]
[s]Mas onde colocar essas coisas...[n]Ooh! Isso será perfeito.[n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_TROUBLE2 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1089 1 214]Huh? Que diabos...? Algo está errado![n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_TROUBLE3 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1089 1 214]O que está acontecendo?[n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_BREAK_DOWN01 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1089 1 214](未使用)オイ、俺を吸い込むんじゃねーYOォッ!![n][f 1 2 40][e]

[msg MSG_BTL_3RD_BREAK_DOWN02 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1089 1 214](未使用)そうだYO、この詰まったモン俺が食っちまえば...[n][f 1 3 65535][w][e]
[s](未使用)うぉふ、結構なボリュームじゃねーかYO...[n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_BREAK_DOWN03 [Piggytron]]
[s][vp 8 0 2 1089 1 214](未使用)ガーガー、想定外のゴミクズを吸い込みました。[n]エラー発生。エラー発生...[n][f 1 2 60][e]

[msg MSG_BTL_3RD_BREAK_DOWN04 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1089 1 214](未使用)ぐはあぁ...[n][f 1 2 60][e]

[msg MSG_BTL_3RD_BLOCK1B [Ombra di Kaneshiro]]
[s][vp 8 0 2 1091 1 214]Avaaanti, eu disse que sou uma parede[n]invencível, certo? Conheça[n]o poder do dinheiro! Sim![n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_BUFF [Ombra di Kaneshiro]]
[s][vp 8 0 2 1089 1 214](未使用)金さえありゃな...[n][f 1 3 65535][w][e]
[s]Mesmo essas coisas absurdas são[n]possíveis, quando você tem dinheiro![n]Ehehehe...[n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_PRE_SPECIAL [Ombra di Kaneshiro]]
[s][vp 8 0 2 1096 1 214]Por que vocês não se resignam[n]a morrer?[n][f 1 3 65535][w][e]

[msg MSG_BTL_AFTER_REINFORCE [Ombra di Kaneshiro]]
[s][vp 8 0 2 1089 1 214](未使用)カネさえあれば鉄壁なんだYO![n][f 1 3 65535][w][e]

[msg MSG_BTL_AFTER_SPECIAL [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1102 0 3]Seus subordinados se foram...[n]Relacionamentos baseados em dinheiro perdem[n]valor assim que ficam sem recursos![n][f 1 3 65535][w][e]

[msg MSG_BTL_AFTER_SPECIAL_B [Ombra di Kaneshiro]]
[s][vp 8 0 2 1089 1 214]Ei! Onde você está!?![n][f 1 3 65535][w][e]

[msg MSG_BTL_AFTER_SPECIAL_C [Ombra di Kaneshiro]]
[s][vp 8 0 2 1103 1 214]Merda, entendi tudo errado...[n][f 1 3 65535][w][e]

[msg MSG_BTL_AFTER_BROKEN [Ombra di Kaneshiro]]
[s][vp 8 0 2 1083 1 214]Que diabos... Meu Piggytron![n][f 1 3 65535][w][e]

[msg MSG_BTL_FRIENDSUMMON_01 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1085 1 214]Ei! Eu paguei esses caras[n]para consertar você![n]O que você acha?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1086 1 214]Eles são muito fortes![n]E voam muito bem![n][f 1 3 65535][w][e]

[msg MSG_BTL_FRIENDSUMMON_02 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1089 1 214]É hora de fazer suas últimas orações![n][f 1 3 65535][w][e]

[msg MSG_BTL_FRIENDSUMMON_03 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1087 1 214]Eheheh... Uma parede invencível![n][f 1 3 65535][w][e]

[msg MSG_BTL_FRIENDSUMMON_04 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1088 0 3]Ugh, é isso que você quer dizer com[n]"você mesmo cuidará de nós"?[n][f 1 3 65535][w][e]

[msg MSG_BTL_FRIENDSUMMON_05 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1089 0 3]Ei pessoal! Eles estão aumentando[n]em número, mas não podemos[n]desistir! Vamos indo![n][f 1 3 65535][w][e]

[msg MSG_BTL_FIRSTBLOCK_01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1092 0 3]Mmm... A técnica do escudo[n]é um verdadeiro saco...[n][f 1 3 65535][w][e]

[msg MSG_BTL_FIRSTBLOCK_02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1093 0 3]Podemos eliminar seus subordinados,[n]mas Kaneshiro não estava mentindo[n]quando disse que eles são durões.[n][f 1 3 65535][w][e]

[msg MSG_BTL_FIRSTBLOCK_03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1094 0 3]...Nesse caso, por que não os colocamos para[n]dormir? Se eles vão dormir, eles não podem nos[n]impedir![n][f 1 3 65535][w][e]

[msg MSG_BTL_FIRSTBLOCK_04 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1095 0 3]A escolha da tática é toda sua, Joker. Para mim[n]não parece um plano ruim![n][f 1 3 65535][w][e]

[msg MSG_BTL_HP25UNDER_01 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1097 1 214]W-W tudo bem... Hora do meu[n]último ás na manga![n][f 1 3 65535][w][e]

[msg MSG_BTL_HP25UNDER_02 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1098 1 214]Vamos nos divertir com uma chuva de[n]dinheiro! Claro?[n][f 1 3 65535][w][e]

[msg MSG_BTL_LASTMONEYSHOWER [Ombra di Kaneshiro]]
[s][vp 8 0 2 1099 1 214]Gah! Fiquei sem dinheiro![n][f 1 3 65535][w][e]

[msg MSG_BTL_FRIENDSGONE_01 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1100 1 214]Que...? Onde vocês estão indo!?![n][f 1 3 65535][w][e]

[msg MSG_BTL_FRIENDSGONE_02 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1101 1 214]Estou temporariamente sem[n]fundos! Vamos, volta aqui, ei![n][f 1 3 65535][w][e]

[msg MSG_BTL_ULTIMATUM [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1104 0 3]Você não tem mais alternativas. Por que[n]você não aceita seu destino?[n][f 1 3 65535][w][e]

[msg MSG_BTL_LAST_NOMONEY_01 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1105 1 214]N-não posso! S-Sem dinheiro...[n]io...[n][f 1 3 65535][w][e]

[msg MSG_BTL_LAST_NOMONEY_02 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1106 1 214]Ah, claro! No Piggytron[n]ainda tem algum dinheiro![n]Tenho que voltar logo![n][f 1 3 65535][w][e]

[msg MSG_BTL_LAST_NOMONEY_03 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1107 1 214]Ufa...dinheiro...dinheiro[n]sempre me acalma...[n][f 1 3 65535][w][e]

[msg MSG_BTL_LAST_NOMONEY_04 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1108 1 214]Um momento. Algo está errado,[n]Piggytron!?![n][f 1 2 80][e]

[msg MSG_BTL_LAST_NOMONEY_05 [Ombra di Kaneshiro]]
[s][vp 8 0 2 1109 1 214]Waaaaaaah![n][f 1 2 60][e]

