[msg MSG_BTLSTART_000_008 [Haru]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1001 0 7]É hora de você se render, pai![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_000_007 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 8]Você está preso! Desistir![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_010_000 [Shadow Okumura]]
[s][vp 8 0 2 1003 1 221]Desistir...?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_030_000 [Shadow Okumura]]
[s][vp 8 0 2 1004 1 221]Tente dizer isso depois de derrubar os[n]soldados de elite da minha empresa![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_040_008 [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 7]Não! Há mais!?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_040_007 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1006 0 8]O que, mais deles!?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_050_000 [Shadow Okumura]]
[s][vp 8 0 2 1007 1 221]Vá, meus funcionários! Seja a base sobre a[n]qual minha vitória é construída...![n][f 1 3 65535][w][e]

[msg MSG_SUMMON_000_008 [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1008 0 7]Ainda mais!?[n][f 1 3 65535][w][e]

[msg MSG_SUMMON_000_007 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1009 0 8]Eles têm mais!?[n][f 1 3 65535][w][e]

[msg MSG_SUMMON_010_000 [Shadow Okumura]]
[s][vp 8 0 2 1010 1 221]Todo problema pode ser resolvido com mais[n]mão de obra...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1011 1 221]Essa é a força da minha empresa![n][f 1 3 65535][w][e]

[msg MSG_SUMMON_020_008 [Haru]]
[s][bup 0 7 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1012 0 7]Felicidade baseada nos sacrifícios dos[n]outros não é a verdadeira felicidade...![n][f 1 3 65535][w][e]

[msg MSG_SUMMON_020_007 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1013 0 8]Isso não é algo para se orgulhar...![n][f 1 3 65535][w][e]

[msg MSG_BOMB_000_008 [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1014 0 7]Eu eu se autodestruto...!?[n][f 1 3 65535][w][e]

[msg MSG_BOMB_000_007 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1015 0 8]Isso acabou de explodir...!?[n][f 1 3 65535][w][e]

[msg MSG_BOMB_010_000 [Shadow Okumura]]
[s][vp 8 0 2 1016 1 221]Hahaha! Meus trabalhadores obedecerão a[n]qualquer pedido que eu lhes dê![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1017 1 221]Você não acha que a lealdade deles é[n]incrível!?[n][f 1 3 65535][w][e]

[msg MSG_BOMB_020_008 [Haru]]
[s][bup 0 7 105 65535 0][f 4 10 65535 0 0][vp 8 0 2 1018 0 7]Eu não posso acreditar nisso...![n][f 1 3 65535][w][e]

[msg MSG_BOMB_020_007 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 8]Eles simplesmente não têm permissão para[n]desobedecer a você...![n][f 1 3 65535][w][e]

[msg MSG_SENNMU_000_000 [Shadow Okumura]]
[s][vp 8 0 2 1020 1 221]HM...!? Parece que os trabalhadores comuns[n]não são adequados para o trabalho![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1021 1 221]Diretor-executivo! Venha até mim![n][f 1 3 65535][w][e]

[msg MSG_SENNMU_010_000 [Shadow Okumura]]
[s][vp 8 0 2 1022 1 221]Agora, então, cumpra seu dever como meu[n]braço direito![n][f 1 3 65535][w][e]

[msg MSG_SENNMU_020_000 [Shadow Okumura]]
[s][vp 8 0 2 1023 1 221]Para a eterna prosperidade dos alimentos de[n]Okumura![n][f 1 3 65535][w][e]

[msg MSG_SENMU75_000_000 [Shadow Okumura]]
[s][vp 8 0 2 1024 1 221]HM...!? O que você está fazendo!?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1025 1 221]Trabalhe mais! Contribua mais! O destino da[n]minha empresa repousa sobre o quanto você[n]trabalha![n][f 1 3 65535][w][e]

[msg MSG_SENMU25_000_000 [Shadow Okumura]]
[s][vp 8 0 2 1026 1 221]Ei! Perder não é uma opção aqui![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1027 1 221]Você carrega o nome da empresa Okumura[n]Foods! Mate esses ladrões, mesmo que isso[n]lhe custe sua vida![n][f 1 3 65535][w][e]

[msg MSG_ONRY_000_000 [Shadow Okumura]]
[s][vp 8 0 2 1028 1 221]O que...!? Até ele...!?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_030_000 [Shadow Okumura]]
[s][vp 8 0 2 1029 1 221]Grrr, alguém! Está aqui alguém!?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_040_000 [Shadow Okumura]]
[s][vp 8 0 2 1030 1 221]O que não está vindo!?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_050_008 [Haru]]
[s][bup 0 7 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1031 0 7]Pai... você foi abandonado mesmo por seus[n]próprios funcionários...[n][f 1 3 65535][w][e]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1032 0 7]Vamos terminar isso, Joker![n][f 1 3 65535][w][e]

[msg MSG_ONRY_050_007 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 8]Esse é o último dos lacaios?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_051_007 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1106 0 8]Vamos acabar com ele, Joker![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_000_008EX [Haru]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1001 0 7]É hora de você se render, pai![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_000_007EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 8]Você está preso! Desistir![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_010_000EX [Shadow Okumura]]
[s][vp 8 0 2 1003 1 221]Desistir...?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_030_000EX [Shadow Okumura]]
[s][vp 8 0 2 1004 1 221]Tente dizer isso depois de derrubar os[n]soldados de elite da minha empresa![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_040_008EX [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 7]Não! Há mais!?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_040_007EX [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1006 0 8]O que- mais inimigos!?[clr 2]Se não dermos para baixo rápido [clr 27], estamos condenados![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_050_000EX [Shadow Okumura]]
[s][vp 8 0 2 1007 1 221]Vá, meus funcionários! Seja a base sobre a[n]qual minha vitória é construída...![n][f 1 3 65535][w][e]

[msg MSG_SUMMON_000_008EX [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1028 0 7]Ainda mais!?[n][f 1 3 65535][w][e]

[msg MSG_SUMMON_000_007EX [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1029 0 8]Eles têm mais!?[n][f 1 3 65535][w][e]

[msg MSG_SUMMON_010_000EX [Shadow Okumura]]
[s][vp 8 0 2 1030 1 221]Todo problema pode ser resolvido com mais[n]mão de obra...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1031 1 221]Essa é a força da minha empresa![n][f 1 3 65535][w][e]

[msg MSG_SUMMON_020_008EX [Haru]]
[s][bup 0 7 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1032 0 7]Felicidade baseada nos sacrifícios dos[n]outros não é a verdadeira felicidade...![n][f 1 3 65535][w][e]

[msg MSG_SUMMON_020_007EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 8]Isso não é algo para se orgulhar...![n][f 1 3 65535][w][e]

[msg MSG_BOMB_000_008EX [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1042 0 7]Eu eu se autodestruto...!?[n][f 1 3 65535][w][e]

[msg MSG_BOMB_000_007EX [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 8]Isso acabou de explodir...!?[n][f 1 3 65535][w][e]

[msg MSG_BOMB_010_000EX [Shadow Okumura]]
[s][vp 8 0 2 1044 1 221]Hahaha! Meus trabalhadores obedecerão a[n]qualquer pedido que eu lhes dê![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1045 1 221]Você não acha que a lealdade deles é[n]incrível!?[n][f 1 3 65535][w][e]

[msg MSG_BOMB_020_008EX [Haru]]
[s][bup 0 7 105 65535 0][f 4 10 65535 0 0][vp 8 0 2 1046 0 7]Eu não posso acreditar nisso...![n][f 1 3 65535][w][e]

[msg MSG_BOMB_020_007EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1047 0 8]Eles simplesmente não têm permissão para[n]desobedecer a você...![n][f 1 3 65535][w][e]

[msg MSG_SENNMU_000_000EX [Shadow Okumura]]
[s][vp 8 0 2 1068 1 221]HM...!? Parece que os trabalhadores comuns[n]não são adequados para o trabalho![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1069 1 221]Diretor-executivo! Venha até mim![n][f 1 3 65535][w][e]

[msg MSG_SENNMU_010_000EX [Shadow Okumura]]
[s][vp 8 0 2 1070 1 221]Agora, então, cumpra seu dever como meu[n]braço direito![n][f 1 3 65535][w][e]

[msg MSG_SENNMU_020_000EX [Shadow Okumura]]
[s][vp 8 0 2 1071 1 221]Para a eterna prosperidade dos alimentos de[n]Okumura![n][f 1 3 65535][w][e]

[msg MSG_SENMU75_000_000EX [Shadow Okumura]]
[s][vp 8 0 2 1072 1 221]HM...!? O que você está fazendo!?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1073 1 221]Trabalhe mais! Contribua mais! O destino da[n]minha empresa repousa sobre o quanto você[n]trabalha![n][f 1 3 65535][w][e]

[msg MSG_SENMU25_000_000EX [Shadow Okumura]]
[s][vp 8 0 2 1074 1 221]Ei! Perder não é uma opção aqui![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1075 1 221]Você carrega o nome da empresa Okumura[n]Foods! Mate esses ladrões, mesmo que isso[n]lhe custe sua vida![n][f 1 3 65535][w][e]

[msg MSG_ONRY_000_000EX [Shadow Okumura]]
[s][vp 8 0 2 1076 1 221]O que...!? Até ele...!?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_030_000EX [Shadow Okumura]]
[s][vp 8 0 2 1077 1 221]Grrr, alguém! Está aqui alguém!?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_040_000EX [Shadow Okumura]]
[s][vp 8 0 2 1102 1 221]O que não está vindo!?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_050_008EX [Haru]]
[s][bup 0 7 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1103 0 7]Pai... você foi abandonado mesmo por seus[n]próprios funcionários...[n][f 1 3 65535][w][e]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1104 0 7]Vamos terminar isso, Joker![n][f 1 3 65535][w][e]

[msg MSG_ONRY_050_007EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1105 0 8]Esse é o último dos lacaios?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_051_007EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1106 0 8]Vamos acabar com ele, Joker![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_ADD_001 [Shadow Okumura]]
[s][vp 8 0 2 1008 1 221]Agora, meus trabalhadores dedicados![n]Visá-los aleatoriamente não fará o truque![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1009 1 221]Você tem que tirar cada um para fora[n]individualmente- aqui, alveje-o primeiro![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_001 [Shadow Okumura]]
[s][vp 8 0 2 1010 1 221]O homem pomposo de casaco preto![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_002 [Shadow Okumura]]
[s][vp 8 0 2 1011 1 221]O loiro desagradável![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_003 [Shadow Okumura]]
[s][vp 8 0 2 1012 1 221]Isso... coisa bizarra, em preto e branco![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_004 [Shadow Okumura]]
[s][vp 8 0 2 1013 1 221]A mulher de aparência sacanagem em vermelho![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_005 [Shadow Okumura]]
[s][vp 8 0 2 1014 1 221]O estranho com a Fox Mask![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_006 [Shadow Okumura]]
[s][vp 8 0 2 1015 1 221]A mulher bárbaro e de cabelos escuros![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_007 [Shadow Okumura]]
[s][vp 8 0 2 1016 1 221]O falso com o rosto da minha filha![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_NON1 [Corporobo]]
[s][vp 8 0 2 1017 0 0]Não consigo encontrar o alvo![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_NON2 [Corporobo]]
[s][vp 8 0 2 1019 0 0]Presidente Okumura! Não consigo encontrar o[n]alvo![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_CHAN [Shadow Okumura]]
[s][vp 8 0 2 1022 1 221]Lá, você os tirou. Em seguida, concentre-se[n]nisso![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_CHAN_2 [Shadow Okumura]]
[s][vp 8 0 2 1023 1 221]Ugh, que movimento secreto![n]Alvo esse em vez disso![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_CHAN_3 [Shadow Okumura]]
[s][vp 8 0 2 1024 1 221]Ei! Por que a demora? Você não pode[n]descartar pilhas de um trabalho simples?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1025 1 221]Basta disso! Alvo esse próximo![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_ESCAPED01 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1027 0 8]O que- ei! Onde você pensa que está indo!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_ESCAPED02 [Shadow Okumura]]
[s][vp 8 0 2 1036 1 221]Hmph, perder alguns funcionários[n]descartáveis não é nada para mim. Eu tenho[n]mais do que suficiente para substituí-los![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1037 1 221]Você cometeu um erro grave subestimando o[n]corpo da minha empresa![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_REINFORCED [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1034 0 8]Droga, quantos deles estão lá!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_REINFORCED_2 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1035 0 8]Tomar um para baixo um de cada vez não fará[n]o truque- [n][clr 2]Livre-se de tudo de uma vez [clr 27][n]Então você pode atacar Okumura![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_SWEPT01 [Shadow Okumura]]
[s][vp 8 0 2 1038 1 221]Hmph, então meus trabalhadores comuns não[n]podem atender às demandas aqui. Nesse[n]caso...[n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_SWEPT02 [Shadow Okumura]]
[s][vp 8 0 2 1039 1 221]Ugh, caramba, esses ladrões... Chefe do[n]balconista! Entre aqui e cuide disso![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_SWEPT03 [Shadow Okumura]]
[s][vp 8 0 2 1040 1 221]Droga! Ei, seção chefe! Tire esses pirralhos[n]de Loudmouth da minha vista![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_SWEPT04 [Shadow Okumura]]
[s][vp 8 0 2 1041 1 221]Argh... seu tempo chegou, diretor-chefe! Vá[n]em frente e mostre a eles o peso da elite[n]corporativa![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_SWEPT05 [Shadow Okumura]]
[s][vp 8 0 2 1007 1 221](未使用)[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_EXTRASP_RES [社畜秘書ロボ]]
[s]★(未使用)専務、特別さーびすノオ時間デス。[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_EXTRASP_COL [社畜秘書ロボ]]
[s]★(未使用)忘レ物ヲ回収イタシマス。[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_EXTRASP_RES_2 [社畜専務ロボ]]
[s]★(未使用)オット。[n]モウ、ソンナ時間カ。[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_00 [Shadow Okumura]]
[s][vp 8 0 2 1048 1 221]Sério, quão inútil você pode ser!?[n]O que quer que tenha sido a lealdade da[n]empresa?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_01 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1034 0 8](未使用)もうやめろ![n]自分の娘がこんなに苦しんでるんだぞ![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_02 [Shadow Okumura]]
[s][vp 8 0 2 1049 1 221]... Muito bem então, Haru! Ensine nossos[n]funcionários como demonstrar sua lealdade[n]adequadamente![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_TEST]
[s](ハルがÇ子の裏から登場するシーン)[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_03 [Cognitive Haru Okumura]]
[s][vp 8 0 2 1050 1 609]Sim, Pai![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_03B [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1051 0 7]Huh!? M-me!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_03C [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1052 0 8]O que- noir!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_04 [Shadow Okumura]]
[s][vp 8 0 2 1053 1 221]Meu Haru obedece fielmente minhas ordens![n]Afinal, ela não é nada como o seu Charlatan![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_05 [Haru]]
[s][bup 0 7 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1054 0 7]Basicamente... essa é a versão cognitiva do[n]meu pai...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_05B [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 8]Eu vejo... então essa é a cognição de Haru[n]de Okumura...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_07 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1056 0 8]Ei pessoal, não deixe isso chegar até você![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1057 0 8][f 4 10 65535 0 0]Lembre-se: quando derrubarmos Okumura, tudo[n]acabará. Vamos encerrar isso rápido![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_08 [Shadow Okumura]]
[s][vp 8 0 2 1058 1 221]Não está acontecendo. Você não deveria ter[n]subestimado a força da minha empresa.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1059 1 221]Funcionários, caem na fila![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_ENHANCE [Shadow Okumura]]
[s][vp 8 0 2 1060 1 221]Não vou deixar alguns ladrões mesquinhos[n]ficarem na empresa- não, no meu caminho![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_ENHANCE_2 [Shadow Okumura]]
[s][vp 8 0 2 1061 1 221]Quem discordar da minha visão será derrubado[n]como exemplo![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_ENHANCE_3 [Cognitive Haru Okumura]]
[s][vp 8 0 2 1062 1 609]As palavras do meu pai são absolutas.[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_ENHANCE_4 [Cognitive Haru Okumura]]
[s][vp 8 0 2 1063 1 609]Não há falhas na lógica de meu pai.[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_ENHANCE_5 [Shadow Okumura]]
[s][vp 8 0 2 1066 1 221]Há uma boa filha! Agora posso me orgulhar do[n]meu trabalho.[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_ENHANCE_6 [Shadow Okumura]]
[s][vp 8 0 2 1067 1 221]É isso mesmo, Haru. É preciso atingir o[n]inimigo enquanto o ferro está quente![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_01 [Shadow Okumura]]
[s][vp 8 0 2 1078 1 221]Droga! Se é assim que é...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1079 1 221]Haru, eu ordeno que você saia![n]Mostre a eles o poder da nossa empresa![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02 [Cognitive Haru Okumura]]
[s][vp 8 0 2 1080 1 609]Sim, Pai![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02B [Shadow Okumura]]
[s][vp 8 0 2 1081 1 221]Okumura Foods será destruído se eu cair![n]Você entende a situação aqui, Haru?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02B2 [Cognitive Haru Okumura]]
[s][vp 8 0 2 1082 1 609]Claro, pai![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02C [Shadow Okumura]]
[s][vp 8 0 2 1083 1 221]Bem, então me proteja- mesmo que isso lhe[n]custe sua vida![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02C2 [Cognitive Haru Okumura]]
[s][vp 8 0 2 1084 1 609]Como você deseja, pai![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_TEST]
[s](ハルがロボットに変身するシーン)[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02D [Haru]]
[s][bup 0 7 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1085 0 7]É assim que meu pai me vê...[n]Nada mais do que um fantoche que dança[n]quando ordenado...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02E [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1086 0 8]Eu não posso acreditar nesse cara! Uma[n]criança não é algum tipo de fantoche ou[n]ferramenta a ser usada![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02F [Cognitive Haru Okumura]]
[s][vp 8 0 2 1087 1 609]Isso é por causa do meu pai.[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02G [Shadow Okumura]]
[s][vp 8 0 2 1088 1 221]Qual é a espera, Haru!? Se você não os[n]parar, meus sonhos...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_03 [Shadow Okumura]]
[s][vp 8 0 2 1089 1 221]Gah, parece que não tenho outra escolha...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_04 [Shadow Okumura]]
[s][vp 8 0 2 1090 1 221]Haru-Destruça-se! Detonar e levar esses[n]malditos ladrões com você![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_05 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1091 0 8]De jeito nenhum!? Okumura está disposto a[n]sacrificar sua própria filha!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_05B [Haru]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1092 0 7]... Todo mundo, vamos destruí-lo antes que[n]possa se autodestruir![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_05B2 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1093 0 8]Mas, noir... isso é...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_05B3 [Haru]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1094 0 7]Não sou mais o fantoche subserviente do meu[n]pai! O verdadeiro eu está bem aqui,[n]opondo-se a ele![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_05C [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1095 0 8]Joker, não deixe detonar! Esse não é o[n]verdadeiro noir- destro-se![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_06 [Shadow Okumura]]
[s][vp 8 0 2 1096 1 221]Wha-!? Até Haru não conseguiu detê-los!?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1097 1 221]Eu já tive o suficiente! Alguém, entre aqui![n]...Alguém!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_06B [Shadow Okumura]]
[s][vp 8 0 2 1098 1 221]Então, mesmo Haru não conseguiu acabar com[n]eles...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1099 1 221]Eu já tive o suficiente! Alguém, entre aqui![n]...Alguém!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_07A [Haru]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1100 0 7]Pai, a hora chegou isso.[n]Espero que você tenha se preparado![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_07 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1101 0 8]Encontramos nossa chance! Joker, vamos[n]acabar com isso![n][f 1 3 65535][w][e]

