[msg MSG_BTLSTART_000_000 [Akechi]]
[s]Muito bem.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_010_007 [Futaba]]
[s]Aquele poder que torna[n]as pessoas psicóticas... ele[n]usou isso em pessoas reais...?[n][f 1 3 65535][w][e]
[s]Esse cara é louco![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_020_000 [Akechi]]
[s]Eu certamente não esperava derrotá-lo[n]com aqueles lacaios.[n][f 1 3 65535][w][e]
[s]Você me enganou e escapou da morte afinal.[n][f 1 3 65535][w][e]
[s]Eu nunca desistiria[n]da chance de matá-lo[n]com minhas próprias mãos![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_030_007 [Futaba]]
[s]Tá chegando... Se preparem![n][f 1 3 65535][w][e]

[msg MSG_BTLHPU50_000_000 [Akechi]]
[s]Ah... Caramba...[n][f 1 3 65535][w][e]

[msg MSG_BTLHPU50_010_000 [Akechi]]
[s]Então... nenhum de nós tinha[n]exibido sua verdadeira força, hein?[n][f 1 3 65535][w][e]
[s]...Não me subestime![n][f 1 3 65535][w][e]

