[msg MSG_BTL_START_000 [Morgana]]
[s][bup 0 3 2 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Ok, eu vou te mostrar um exemplo primeiro.[n]É melhor você assistir de perto![n][f 1 3 65535][w][e]

[msg MSG_ACT_START_000 [Morgana]]
[s][bup 0 3 2 0 0][vp 8 0 2 1002 0 3][f 4 10 65535 0 0]Use esta oportunidade para passear e trocar[n]sua vez com outra pessoa![n][f 1 3 65535][w][e]

[msg MSG_ACT_START_001]
[s]Agora você pode passar a mais de um membro[n]do partido para outro membro do partido.[n][w][e]
[s]O destinatário do Baton Pass verá um aumento[n]nas habilidades de ataque e cura. O[n]destinatário também pode passar o bastão[n]para outro membro do partido para aumentar[n]suas habilidades também.[n][w][e]
[s]Passe o bastão para outro membro do partido[n]pressionando o [n][clr 2]Botão R2 [clr 27].[n][w][e]

[msg MSG_ACT_START_003 [Morgana]]
[s][bup 0 3 2 0 0][vp 8 0 2 0 0 0][f 4 10 65535 0 0]Primeiro, troque com a Pantera![n][f 1 3 65535][w][e]

[msg MSG_ACT_START_002 [Morgana]]
[s][bup 0 3 2 0 0][vp 8 0 2 1003 0 3][f 4 10 65535 0 0]Agora, golpeie a fraqueza do inimigo e[n]experimente o bastão![n][f 1 3 65535][w][e]

