[msg MSG_BTLSTART_001]
[s]仮メッセージ[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Maruki]]
[s][vp 8 0 2 1001 1 503]Eu me recuso a deixar isso acabar assim...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002B [Maruki]]
[s][vp 8 0 2 1002 1 503]Adam Kadmon! Guie-nos todos para a nossa[n]realidade ideal![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002_2 [Sumire]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 0 2 1003 0 10]Você está errado![n][f 1 3 65535][w][e]

[sel SEL_BTLSTART002 top]
[s]Vamos decidir nossa realidade.[e]
[s]Não podemos perder isso.[e]

[msg MSG_BTLSTART_002_3 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1004 0 8]Sim! Nós nos recusamos a deixar isso[n]terminar de outra maneira também![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Maruki]]
[s](未使用)さぁアダムカドモン![n]僕の目指す現実へ導いてくれ![n][f 1 3 65535][w][e]

[msg MSG_BTLEND_001 [Maruki]]
[s][vp 8 0 2 1008 1 503]Eu ainda... não posso fazer isso!?[n][f 1 3 65535][w][e]

[msg MSG_BTLEND_002 [Maruki]]
[s][vp 8 0 2 1009 1 503]E minha realidade está bem diante dos meus[n]olhos...[n][f 1 3 65535][w][e]

[msg MSG_BTL_MARUKI_CAST [Maruki]]
[s][vp 8 0 2 1005 1 503]Adam Kadmon![n][f 1 3 65535][w][e]

[msg MSG_BTL_MARUKI_CAST2 [Maruki]]
[s][vp 8 0 2 1006 1 503]Persona![n][f 1 2 45][e]

[msg MSG_BTL_MARUKI_CAST3 [Maruki]]
[s][vp 8 0 2 1007 1 503]Me dê sua força...[n][f 1 3 65535][w][e]

