[msg MSG_BTLSTART_000 [Corporobo]]
[s][vp 8 0 2 0 0 0]HÃ? Quem diabos... você está tentando brigar[n]comigo!?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_001 [Futaba]]
[s][vp 8 2 2 9043 0 8][bup 0 8 602 65535 0][f 4 10 65535 0 0]Aqui está outro mandão...[n]Joker, vamos trabalhar com ele para algumas[n]informações![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Corporobo]]
[s][vp 8 0 2 0 0 0]Você tem algum tipo de negócio comigo?[n][f 1 3 65535][w][e]

[sel SEL_BTLTALK_00_001 top]
[s]Na verdade, é com seu chefe.[e]
[s]Onde está seu chefe?[e]

[msg MSG_BTLTALK1_000 [Corporobo]]
[s][vp 8 0 2 0 0 0]Oh, o chefe...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 0 0 0]Se você pode chamá-lo assim![n]Ele não pode fazer uma única coisa certa![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK1_001 [Futaba]]
[s][vp 8 2 2 9134 0 8][bup 0 8 604 65535 0][f 4 10 65535 0 0]Nós iremos! Parece-me que ele tem uma carne[n]com o chefe.[n][f 1 3 65535][w][e]

[msg MSG_BTLTALK1_001_2 [Futaba]]
[s][vp 8 0 2 0 0 0][bup 0 8 600 65535 0][f 4 10 65535 0 0]Joker, se você o jogar certo, ele pode dar[n]alguns detalhes úteis![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK1_002 [Corporobo]]
[s][vp 8 0 2 0 0 0]Tudo o que ele tem é sua classificação! Ele[n]anda por toda a volta e poderoso, mas ele[n]não é tudo isso![n][f 1 3 65535][w][e]
[s][vp 8 0 2 0 0 0]Ele nem tem idéia de que eu conheço sua[n]fraqueza![n][f 1 3 65535][w][e]

[sel SEL_BTLTALK_00_002 top]
[s]Uau, isso é impressionante.[e]
[s]Onde ele já está?[e]

[msg MSG_BTLTALK2_000 [Corporobo]]
[s][vp 8 0 2 0 0 0]EU SEI DIREITO? Que bom que você concorda![n][f 1 3 65535][w][e]
[s][vp 8 0 2 0 0 0]... você quer ouvir isso? Isso é enorme,[n]então sem dizer mais ninguém, entendeu?[n][f 1 3 65535][w][e]

[msg MSG_BTLTALK2_001 [Corporobo]]
[s][vp 8 0 2 0 0 0]O chefe é fraco para [clr 2]Psicokinesis [clr 27]![n]Nem mesmo seu revestimento de força[n]industrial pode salvá-lo delas![n][f 1 3 65535][w][e]
[s][vp 8 0 2 0 0 0]Oh... talvez eu deveria ter mantido isso[n]para mim mesmo...[n][f 1 3 65535][w][e]

[msg MSG_BTLTALK2_002 [Futaba]]
[s][vp 8 2 2 9196 0 8][bup 0 8 602 65535 0][f 4 10 65535 0 0]Legal! Um deslizamento clássico da língua![n][f 1 3 65535][w][e]
[s][vp 8 0 2 0 0 0][f 4 10 65535 0 0]Eu não acho que ele tenha mais sujeira,[n]então vamos apenas limpar o chão com ele[n]bem rápido![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK2_003 [Corporobo]]
[s][vp 8 0 2 0 0 0]Augh, não! ESPERE, ESPERE, ESPERE![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK2_004 [Futaba]]
[s][vp 8 2 2 9109 0 8][bup 0 8 602 65535 0][f 4 10 65535 0 0]Qualquer chefe que permita que seus[n]funcionários sofram merecem a mesma coisa![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK2_005 [Corporobo]]
[s][vp 8 0 2 0 0 0]Eu não tenho idéia. O chefe está ocupado[n]demais para eu me envolver.[n][f 1 3 65535][w][e]

[msg MSG_BTLTALK2_006 [Futaba]]
[s][vp 8 2 2 9196 0 8][bup 0 8 602 65535 0][f 4 10 65535 0 0]Esse cara é inútil! Vamos afastá-lo[n]rapidamente, Joker![n][f 1 3 65535][w][e]

