[msg MSG_NML03_FIND_01_01]
[s]Que e aquele!? Ha[n]alguem por perto![n][f 1 2 65535][e]

[msg MSG_NML03_FIND_01_02]
[s]La! eu acabei de ver[n]algo ai![n][f 1 2 65535][e]

[msg MSG_NML03_FIND_01_03]
[s]O que!? Quem esta ai!?[n][f 1 2 65535][e]

[msg MSG_NML03_FIND_01_04]
[s]Que e aquele!? Ha[n]alguem por perto![n][f 1 2 65535][e]

[msg MSG_NML03_FIND_01_05]
[s]Huh!? Houve...[n]alguem la apenas[n]Agora, nao havia?[n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_01_01]
[s]Pare! Como e que entraste!?[n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_01_02]
[s]Eu nao vou deixar voce escapar,[n]Voces ladroes![n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_01_03]
[s]Pare! Eu nao vou deixar voce ir![n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_01_04]
[s]Voce! Nao pense em voce[n]pode fugir![n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_01_05]
[s]Eu nao vou deixar voce ir![n]Todos, invasores![n]Cerca-los![n][f 1 2 65535][e]

[msg MSG_NML03_LOST_01_01]
[s]Eu os perdi... onde[n]voce esconde? Mostre-se![n][f 1 2 65535][e]

[msg MSG_NML03_LOST_01_02]
[s]Droga! Eu perdi eles...[n][f 1 2 65535][e]

[msg MSG_NML03_LOST_01_03]
[s]Eles sao rapidos...[n]Para onde eles foram?[n][f 1 2 65535][e]

[msg MSG_NML03_LOST_01_04]
[s]Eles ainda deveriam estar em[n]a area! Vou te encontrar...[n][f 1 2 65535][e]

[msg MSG_NML03_LOST_01_05]
[s]Eles desapareceram!?[n]Eles sao magicos!?[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_01]
[s]Enquanto eu estiver aqui,[n]Nenhum intruso jamais[n]passar por mim...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_02]
[s]"Se voce deseja passar,[n]Voce tera que me derrotar! "[n]Ok, boa pratica.[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_03]
[s]Eu nunca vou deixar ninguem[n]por aqui... nunca...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_04]
[s]Nenhum intruso poderia ter[n]chegou tao longe em...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_05]
[s]Eu nao posso deixar ninguem[n]por aqui...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_06]
[s]Eu quero dar um soco em alguem...[n]Eu nao me importo com quem.[n]Ladroes, criancas, qualquer um...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_07]
[s]Ahhh, eu amo o perfume[n]de dinheiro... eu podia cheirar[n]Aqueles gordos empilham para sempre.[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_08]
[s]Ahaha, o Sr. Kaneshiro's tais[n]Um preocupacao! Nao posso culpar[n]ele, com esse tipo de dinheiro...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_09]
[s]Vamos la, idiotas.[n]Venha assim... eu vou[n]Bata seus cranios![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_10]
[s]O fluxo de caixa e otimo hoje,[n]como sempre. Sr. Kaneshiro's[n]rolando! Ahaha![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_01]
[s]Eu nao vou deixar voce ir... eu vou encontrar[n]voce, nao importa o que...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_02]
[s]Onde voce se escondeu?[n]Eu nao vou deixar voce ir...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_03]
[s]Ao contrario daqueles outros[n]Blockheads, eu nao vou[n]Deixe alguem fugir...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_04]
[s]Vou encontra-los e[n]Vou captura-los![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_05]
[s]Eles estao por aqui?[n]Eles nao sao, nao sao?[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_06]
[s]Alguem esta ai?[n]Venha me pegar![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_07]
[s]Nada acontecendo aqui.[n]Mas talvez eu deva[n]dupla verificacao...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_08]
[s]Ninguem aqui![n]Ninguem la tambem![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_09]
[s]Se os intrusos aparecerem...[n]Vou mata-los com meus amigos![n]Ahaha![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_10]
[s]Heyyy! Venha para fora![n]Eu nao farei nada com voce...[n]Ahaha![n][f 1 2 65535][e]

[msg MSG_NML03_REPORT_01_01]
[s]Eu devo dizer o[n]Presidente do banco![n][f 1 2 65535][e]

[msg MSG_NML03_REPORT_01_02]
[s]Devo relatar isso ao banco[n]Presidente para apertar a seguranca.[n][f 1 2 65535][e]

[msg MSG_NML03_REPORT_01_03]
[s]Devemos relatar isso ao[n]Presidente do Banco de uma so vez![n][f 1 2 65535][e]

[msg MSG_NML03_REPORT_01_04]
[s]Devo perguntar ao banco[n]Presidente para aumentar a seguranca![n][f 1 2 65535][e]

[msg MSG_NML03_REPORT_01_05]
[s]So voce assiste... eu vou pegar[n]Seguranca se apertou para voce![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01_]
[s]Eu nao vou desistir disso,[n]nao importa o que.[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__2]
[s]Se eu nao proteger isso,[n]Sr. Kaneshiro vai me matar...[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__3]
[s]Isso me foi confiado.[n]Vou protege-lo, nao importa o que.[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__4]
[s]Por favor, ninguem vem[n]por agora![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__5]
[s]Seria ruim se isso fosse levado...[n]Devo trabalhar duro para defende-lo...[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01]
[s]Sr. Kaneshiro![n]Ha um intruso![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_2]
[s]Reportando![n]Intrudadores encontrados![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_3]
[s]Intrusos! Sr. Kaneshiro,[n]Por favor, esteja atento![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_4]
[s]I-Intruders! Sr. Kaneshiro![n]Eu encontrei intrusos![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_5]
[s]Intrudadores detectados![n]Intrudadores detectados![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0]
[s]Ninguem esta aqui. O que sou[n]Eu ate assistindo?[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_2]
[s]E ate possivel para qualquer um[n]Para invadir este lugar?[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_3]
[s]Barras de ouro... elas nao vao[n]Observe se eu embolsar alguns,[n]irao eles?[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_4]
[s]* suspiro* eu gostaria que tenhamos conseguido[n]mais funcionarios. Eu quero pegar[n]Mais pausas...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_5]
[s]Quanto tempo mais[n]Eu tenho que me proteger[n]nada?[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_6]
[s]Eu quero dar um soco em alguem...[n]Eu nao me importo com quem. Ladroes,[n]Criancas, qualquer um...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_7]
[s]Ahhh, eu amo o perfume de dinheiro...[n]Eu podia sentir o cheiro daquelas gordas[n]Stacks para sempre.[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_8]
[s]Ahaha, o Sr. Kaneshiro e tao[n]preocupacao! Nao posso culpa-lo,[n]Com esse tipo de dinheiro...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_9]
[s]Alguem esta ai?[n]Venha me pegar![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1]
[s]Se eu nao mantiver este lugar[n]Seguro, eu vou ser[n]fora de um trabalho...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_2]
[s]Cara, eu gostaria de poder pegar um[n]Cerveja com o Sr. Kaneshiro![n]Hahaha![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_3]
[s]Ninguem aqui![n]Ninguem la tambem![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_4]
[s]Se os intrusos aparecerem...[n]Vou mata-los com meus amigos![n]Ahaha![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_5]
[s]As criancas sao tao estupidas por[n]Desafiando adultos... Serio![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_6]
[s]Vamos la, idiotas.[n]Vem por aqui...[n]Vou bater em seus cranios![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_7]
[s]Nada acontecendo aqui.[n]Mas talvez eu deva[n]dupla verificacao...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_8]
[s]O fluxo de caixa e otimo hoje,[n]como sempre. Sr. Kaneshiro's[n]rolando! Ahaha![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_9]
[s]Deixe a seguranca para nos![n]Estamos sempre em guarda...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_10]
[s]Mannn, estou entediado...[n]Gostaria que alguem faria[n]Venha... entao... entediado...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_2]
[s]Heyyy! Venha para fora![n]Eu nao farei nada com voce...[n]Ahaha![n][f 1 2 65535][e]

[msg MSG_NML03_FIND_02_01]
[s]Woof![n]Woof woof![n][f 1 2 65535][e]

[msg MSG_NML03_FIND_02_02]
[s]AWOOOOOO![n][f 1 2 65535][e]

[msg MSG_NML03_FIND_02_03]
[s]Woof woof woof![n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_02_01]
[s]Woof![n]Woof woof![n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_02_02]
[s]Grrrrrr...[n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_02_03]
[s]Woof![n]Grrr... woof![n][f 1 2 65535][e]

[msg MSG_NML03_LOST_02_01]
[s]Woof! Woof![n][f 1 2 65535][e]

[msg MSG_NML03_LOST_02_02]
[s]ARF![n][f 1 2 65535][e]

[msg MSG_NML03_LOST_02_03]
[s]Grrrrr...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_02_01]
[s]*Onomatopeia de cheirar*[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_02_02]
[s]*Pant**Pant**Pant*[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_02_03]
[s]Rrr... rowr...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_02_01]
[s]*Onomatopeia de cheirar*[n]Woof... rowr...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_02_02]
[s]AWOOOOOO![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_02_03]
[s]Woof![n]*Onomatopeia de cheirar*[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_02_]
[s]Grrrrr...[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_02__2]
[s]*Onomatopeia de cheirar*[n]Woof woof![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_02__3]
[s]*Pant**Pant**Pant*[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_02]
[s]Grrrrr...[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_02_2]
[s]*Onomatopeia de cheirar*[n]Woof woof![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_02_3]
[s]*Pant**Pant**Pant*[n][f 1 2 65535][e]

