[msg MSG_GAMESTART [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]Vamos começar a jogar[n]Pro Golfer Sarutahiko.[n][f 1 3 65535][w][e]

[msg MSG_GAMESTART_NULL]
[s][vp 8 2 0 91 65535 0]Hora de começar[n]Pro Golfer Sarutahiko...[n][f 1 3 65535][w][e]

[msg MSG_READ_BOOK_URAWAZA_FI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1172 65535 0]A propósito, você não leu[n]aquele livro com técnicas secretas?[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Se não me engano existe um truque que[n]serve para desacelerar a barra,[n]facilitando o jogo...[n][f 1 3 65535][w][e]

[msg MSG_READ_BOOK_URAWAZA_NU]
[s][vp 8 2 0 0 65535 0]Agora que penso nisso, na verdade[n]li um livro sobre[n]técnicas secretas para finalizar videogames...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]De acordo com o livro, existe uma maneira[n]de desacelerar a barra e tornar[n]o jogo mais fácil.[n][f 1 3 65535][w][e]

[msg MSG_READ_BOOK_URAWAZA_FI_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Então, você quer usar o truque?[n]Ele vai desacelerar a barra.[n][f 1 3 65535][w][e]

[msg MND_201_6_0]
[s][vp 8 2 0 0 65535 0]Devo usar o truque[n]que vi naquele livro?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Use a técnica secreta[e]
[s]Jogue normalmente[e]

[msg MSG_READ_BOOK_URAWAZA_YE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Faz sentido, já que você[n]aprendeu. Está bem. Vamos lá.[n][f 1 3 65535][w][e]

[msg MND_203_6_0]
[s][vp 8 2 0 0 65535 0]OK, isso deve tornar o jogo mais fácil...[n][f 1 3 65535][w][e]

[msg MSG_READ_BOOK_URAWAZA_NO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Uau, você está animado! Bem, é isso![n][f 1 3 65535][w][e]

[msg MND_202_6_0]
[s][vp 8 2 0 0 65535 0]Eu deveria tentar usar[n]minhas habilidades sozinho para fazer isso...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1164 65535 0]Oh, há um curso de treinamento.[n]Vamos tentar isso primeiro.[n][f 1 3 65535][w][e]

[msg MND_016_1_0]
[s][vp 8 2 0 59 65535 0]Eu deveria tentar[n]o curso de treinamento...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]OK, vamos praticar golpear[n]na distância normal.[n][f 1 3 65535][w][e]

[msg MND_017_1_0]
[s][vp 8 2 0 0 65535 0]Começa com o treinamento[n]para atirar em alcance normal...[n][f 1 3 65535][w][e]

[msg SYS_018_0_0]
[s][vp 8 2 0 0 65535 0]Pressione [f 1 10 75] para mover a barra do[n]ponto inicial para a direita. Pressione[n][f 1 10 75] novamente para pará-lo dentro da área indicada.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oh, você conseguiu.[n]Não foi um tiro ruim.[n][f 1 3 65535][w][e]

[msg MND_019_1_0]
[s][vp 8 2 0 0 65535 0]Essa foi uma boa tacada...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]A bola está na grama alta.[n]Não foi um chute dos melhores...[n][f 1 3 65535][w][e]

[msg MND_020_1_0]
[s][vp 8 2 0 0 65535 0]Minha bola foi para a grama alta. Situação ruim...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oh, a tela mudou.[n]Agora você está preso na areia.[n][f 1 3 65535][w][e]

[msg MND_021_1_0]
[s][vp 8 2 0 0 65535 0]Agora a situação é diferente. Minha[n]bola está na areia. Acho que você precisa[n]prática com este obstáculo.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Nada mal! Você conseguiu tirar[n]a bola da areia.[n][f 1 3 65535][w][e]

[msg MND_022_1_0]
[s][vp 8 2 0 0 65535 0]consegui tirar[n]a bola da areia...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]A bola foi parar na lagoa![n]Pode ser um problema...[n][f 1 3 65535][w][e]

[msg MND_023_1_0]
[s][vp 8 2 0 0 65535 0]Caramba, a bola foi longe demais[n]ali...e caiu em um lago.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oooh, agora você está perto[n]da bandeira! Deve ser[n]o treinamento verde.[n][f 1 3 65535][w][e]

[msg MND_024_1_0]
[s][vp 8 2 0 0 65535 0]A situação mudou novamente.[n]Agora estou na frente do green, acho que[n]é usado para praticar chutes curtos.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ei, você conseguiu![n]A bola está no gramado.[n][f 1 3 65535][w][e]

[msg MND_025_1_0]
[s][vp 8 2 0 0 65535 0]Eu bati a bola no green![n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oh, você acertou a bola[n]no meio do mato... Feio, como um tiro.[n][f 1 3 65535][w][e]

[msg MND_026_1_0]
[s][vp 8 2 0 0 65535 0]Eu joguei a bola no[n]mato... Que triste...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Parece que você concluiu[n]seu curso de treinamento.[n]Vamos parar por aqui por hoje.[n][f 1 3 65535][w][e]

[msg MND_027_1_0]
[s][vp 8 2 0 0 65535 0]Aparentemente, concluí[n]o curso de treinamento...[n][f 1 3 65535][w][e]

[msg MSG_200_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1165 65535 0]Oh, próximo buraco[n]é um par 3.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...Tente completá-lo[n]em três acertos, OK?[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Lembre-se, o primeiro tiro é crucial.[n]Mire bem.[n][f 1 3 65535][w][e]

[msg MND_200_1_0]
[s][vp 8 2 0 45 65535 0]É um campo "par 3"...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Isso significa que tenho que completá-lo[n]sem acertar mais de três acertos.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Tenho que ter muito cuidado[n]ao mirar o primeiro tiro...[n][f 1 3 65535][w][e]

[msg MSG_201_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1190 65535 0]Você deve completar este caminho[n]com no máximo três acertos.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Lembre-se, o primeiro tiro é crucial.[n]Mire bem.[n][f 1 3 65535][w][e]

[msg MND_201_1_0]
[s][vp 8 2 0 45 65535 0]Devo concluir este percurso[n]sem golpear mais de três golpes...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Tenho que ter muito cuidado[n]ao mirar o primeiro tiro...[n][f 1 3 65535][w][e]

[msg MSG_250_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Excelente! Você mandou para o green.[n][f 1 3 65535][w][e]

[msg MND_250_1_0]
[s][vp 8 2 0 0 65535 0]Foi uma boa tacada.[n]Minha bola caiu no gramado.[n][f 1 3 65535][w][e]

[msg MSG_251_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Cara, caiu bem na[n]grama alta... Tente mais,[n]para a próxima tacada.[n][f 1 3 65535][w][e]

[msg MND_251_1_0]
[s][vp 8 2 0 0 65535 0]Foi direto para a grama alta...[n]Que desastre...[n][f 1 3 65535][w][e]

[msg MSG_203_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você tem dois tiros restantes.[n]Eu me pergunto se você será capaz[n]de embolsá-lo...[n][f 1 3 65535][w][e]

[msg MND_203_1_0]
[s][vp 8 2 0 0 65535 0]Faltam dois tiros...[n]Espero poder[n]mandá-la para o buraco...[n][f 1 3 65535][w][e]

[msg MSG_Stage02_Green_Rest1_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Uau, você envasou![n][f 1 3 65535][w][e]

[msg MND_Stage02_Green_Rest1_]
[s][vp 8 2 0 0 65535 0]Foi parar no buraco...![n][f 1 3 65535][w][e]

[msg MSG_253_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oh, está preso na areia...[n]Poderia ter sido melhor.[n][f 1 3 65535][w][e]

[msg MND_253_1_0]
[s][vp 8 2 0 0 65535 0]Ugh, direto na areia...[n]Golpe horrível.[n][f 1 3 65535][w][e]

[msg MSG_204_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você só tem um tiro restante.[n]Eu me pergunto se você será capaz[n]de colocá-lo no bolso...[n][f 1 3 65535][w][e]

[msg MND_204_1_0]
[s][vp 8 2 0 0 65535 0]Eu só tenho uma chance... Espero que[n]vá ao pote...[n][f 1 3 65535][w][e]

[msg MSG_205_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você terá que desferir o segundo golpe[n]da grama alta... Não vai ser fácil[n]tirá-la de lá.[n][f 1 3 65535][w][e]

[msg MND_205_1_0]
[s][vp 8 2 0 0 65535 0]Vou ter que acertar o segundo tiro[n]da grama alta...[n][f 1 3 65535][w][e]

[msg MSG_254_0_0 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você a puxou para fora da grama alta,[n]mas ela voltou...[n][f 1 3 65535][w][e]

[msg MND_254_1_0]
[s][vp 8 2 0 0 65535 0]...Movido para outra[n]área com grama alta.[n][f 1 3 65535][w][e]

[msg MSG_206_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Este é o terceiro e último tiro...Você realmente[n]acha que pode encerrar esta situação?[n][f 1 3 65535][w][e]

[msg MND_206_1_0]
[s][vp 8 2 0 0 65535 0]É minha terceira chance...[n]Minha última chance.[n][f 1 3 65535][w][e]

[msg MSG_252_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oh, você conseguiu...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]E você envasou também![n][f 1 3 65535][w][e]

[msg MND_252_1_0]
[s][vp 8 2 0 0 65535 0]Eu a tirei da grama...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]...E eu envasei![n][f 1 3 65535][w][e]

[msg MSG_255_0_0 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...Bola na areia.[n]Vai mal.[n][f 1 3 65535][w][e]

[msg MND_255_1_0]
[s][vp 8 2 0 0 65535 0]...Ela acabou na areia de novo.[n][f 1 3 65535][w][e]

[msg MSG_270_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Uau, você concluiu[n]sem pestanejar. E você também[n]deixou uma chance.[n][f 1 3 65535][w][e]

[msg MND_270_1_0]
[s][vp 8 2 0 0 65535 0]Nada mal,[n]mas só me resta uma chance.[n][f 1 3 65535][w][e]

[msg MSG_271_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você chegou perto do desastre,[n]mas finalmente conseguiu![n][f 1 3 65535][w][e]

[msg MND_271_1_0]
[s][vp 8 2 0 0 65535 0]De alguma forma eu consegui[n]completá-lo...[n][f 1 3 65535][w][e]

[msg MSG_300_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1163 65535 0]Este percurso tem 330 metros de comprimento.[n]É pelo menos um "par 4".[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tente completá-lo[n]em quatro hits, OK?[n][f 1 3 65535][w][e]

[msg MND_300_1_0]
[s][vp 8 2 0 23 65535 0]Este é um percurso...[n]de 330 metros. É um buraco par 4...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Isso significa que tenho quatro[n]tiros para terminar...[n][f 1 3 65535][w][e]

[msg MSG_302_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1189 65535 0]Ok, isso você vai[n]concluir em quatro acertos.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Lembre-se, o primeiro tiro é crucial.[n]Mire bem.[n][f 1 3 65535][w][e]

[msg MND_302_1_0]
[s][vp 8 2 0 0 65535 0]Devo completar este percurso[n]sem acertar mais de quatro golpes.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 26 65535 0]Tenho que ter muito cuidado[n]ao mirar o primeiro tiro...[n][f 1 3 65535][w][e]

[msg MSG_350_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Nossa, que golpe! Você reduziu bastante[n]a distância.[n][f 1 3 65535][w][e]

[msg MND_350_1_0]
[s][vp 8 2 0 0 65535 0]Que golpe...! Reduzi bastante[n]a distância.[n][f 1 3 65535][w][e]

[msg MSG_351_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...Ela acabou na grama alta.[n]Já...[n][f 1 3 65535][w][e]

[msg MND_351_1_0]
[s][vp 8 2 0 0 65535 0]...A bola foi direto para a grama alta.[n][f 1 3 65535][w][e]

[msg MSG_303_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você ainda tem três tiros restantes.[n]Não perca o ritmo.[n][f 1 3 65535][w][e]

[msg MND_303_1_0]
[s][vp 8 2 0 0 65535 0]Ainda tenho três tiros restantes.[n]Vamos seguir em frente...[n][f 1 3 65535][w][e]

[msg MSG_352_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bem, a bola está no green![n][f 1 3 65535][w][e]

[msg MND_352_1_0]
[s][vp 8 2 0 0 65535 0]Que golpe...! A bola[n]está no green.[n][f 1 3 65535][w][e]

[msg MSG_353_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...Você jogou exatamente[n]naquela área com grama alta.[n]No entanto, a pontaria não foi ruim...[n][f 1 3 65535][w][e]

[msg MND_353_1_0]
[s][vp 8 2 0 0 65535 0]Aterrissou no centro do percurso,[n]bem no meio da grama alta.[n]Não demorou...[n][f 1 3 65535][w][e]

[msg MSG_308_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você está na segunda tacada, mas tome cuidado.[n]A bola está cercada de grama.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Se você cometer um erro agora, será[n]inútil continuar tentando.[n]Não se apresse.[n][f 1 3 65535][w][e]

[msg MND_308_1_0]
[s][vp 8 2 0 0 65535 0]É hora do segundo golpe.[n]Há grama por toda parte...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Se eu cometesse um erro,[n]nunca conseguiria passar de nível[n]ficando abaixo do par...[n][f 1 3 65535][w][e]

[msg MSG_356_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...Ela acabou na grama alta novamente. Há pouco a[n]fazer agora.[n][f 1 3 65535][w][e]

[msg MND_356_1_0]
[s][vp 8 2 0 0 65535 0]Ela voou para o outro lado[n]e acabou na grama alta.[n]Eu realmente acho que perdi.[n][f 1 3 65535][w][e]

[msg MSG_306_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você está no terceiro tiro. Talvez[n]você consiga nocauteá-la...![n][f 1 3 65535][w][e]

[msg MND_306_1_0]
[s][vp 8 2 0 0 65535 0]Este é o terceiro tiro.[n]Com um pouco de sorte[n]vai acabar no buraco...[n][f 1 3 65535][w][e]

[msg MSG_354_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ei, você conseguiu! Ótimo trabalho![n][f 1 3 65535][w][e]

[msg MND_354_1_0]
[s][vp 8 2 0 0 65535 0]Direto para o buraco![n]Mira perfeita.[n][f 1 3 65535][w][e]

[msg MSG_355_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ela passou por cima do buraco[n]e acabou na areia...[n][f 1 3 65535][w][e]

[msg MND_355_1_0]
[s][vp 8 2 0 0 65535 0]A bola passou por cima do buraco...[n]e caiu na areia.[n][f 1 3 65535][w][e]

[msg MSG_304_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]OK, estamos de volta no meio[n]do caminho. Você ainda tem[n]dois tiros restantes...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você nunca será capaz de completar[n]este percurso se não alcançar[n]o green com esta tacada...[n][f 1 3 65535][w][e]

[msg MND_304_1_0]
[s][vp 8 2 0 0 65535 0]Estou de volta ao centro[n]do caminho. Faltam dois tiros...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Se eu não conseguir[n]chegar ao green com esta tacada, não posso[n]fechar abaixo do par...[n][f 1 3 65535][w][e]

[msg MSG_309_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Terceira tacada.[n]Acha que consegue[n]chegar ao green...?[n][f 1 3 65535][w][e]

[msg MND_309_1_0]
[s][vp 8 2 0 0 65535 0]É minha terceira chance. Espero[n]conseguir chegar ao green.[n][f 1 3 65535][w][e]

[msg MSG_357_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Não... Foi um tiro[n]muito fraco...[n][f 1 3 65535][w][e]

[msg MND_357_1_0]
[s][vp 8 2 0 0 65535 0]A distância não era suficiente...[n][f 1 3 65535][w][e]

[msg MSG_307_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]OK, quarta foto...[n]É a última disponível. Você irá[n]apontar diretamente para o buraco...![n][f 1 3 65535][w][e]

[msg MND_307_1_0]
[s][vp 8 2 0 0 65535 0]É meu quarto e último tiro...[n]Tenho que mirar com cuidado...[n][f 1 3 65535][w][e]

[msg MSG_310_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Este é o último tiro. Claro[n]você consegue daqui...?[n][f 1 3 65535][w][e]

[msg MND_310_1_0]
[s][vp 8 2 0 0 65535 0]É minha última chance...[n][f 1 3 65535][w][e]

[msg MSG_358_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você não conseguiu tirá-la da areia. Acabou, eu[n]acho.[n][f 1 3 65535][w][e]

[msg MND_358_1_0]
[s][vp 8 2 0 0 65535 0]Não consegui tirá-la[n]da areia...[n][f 1 3 65535][w][e]

[msg MSG_370_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Uau, você concluiu[n]sem pestanejar. E você também[n]deixou uma chance.[n][f 1 3 65535][w][e]

[msg MND_370_1_0]
[s][vp 8 2 0 0 65535 0]Nada mal,[n]mas só me resta uma chance.[n][f 1 3 65535][w][e]

[msg MSG_371_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você chegou perto do desastre,[n]mas finalmente conseguiu![n][f 1 3 65535][w][e]

[msg MND_371_1_0]
[s][vp 8 2 0 0 65535 0]De alguma forma eu consegui[n]completá-lo...[n][f 1 3 65535][w][e]

[msg MSG_400_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Droga... Este percurso[n]para especialistas é um par 5[n]com uns bons 530 metros de comprimento...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Pelo menos você tem cinco acertos[n]para completá-lo.[n][f 1 3 65535][w][e]

[msg MND_400_1_0]
[s][vp 8 2 0 0 65535 0]Este é um percurso para especialistas.[n]Tem 530 metros[n]e é um "par 5"...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Tenho apenas cinco acertos[n]para completá-lo.[n][f 1 3 65535][w][e]

[msg MSG_402_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Então, vamos tentar[n]a rota especialista novamente? Não precisa[n]acertar mais que cinco tiros, né?[n][f 1 3 65535][w][e]

[msg MND_402_1_0]
[s][vp 8 2 0 0 65535 0]É o curso especializado...[n]Tenho que completá-lo em cinco acessos.[n][f 1 3 65535][w][e]

[msg MSG_401_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]OK, vá devagar.[n]Afinal, é apenas o primeiro tiro.[n][f 1 3 65535][w][e]

[msg MND_401_1_0]
[s][vp 8 2 0 0 65535 0]É minha primeira chance...[n][f 1 3 65535][w][e]

[msg MSG_450_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Nossa, que golpe! Você reduziu bastante[n]a distância.[n][f 1 3 65535][w][e]

[msg MND_450_1_0]
[s][vp 8 2 0 0 65535 0]Um grande golpe...! Eu[n]consegui fechar a lacuna.[n][f 1 3 65535][w][e]

[msg MSG_451_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...Você já atirou na grama alta.[n]Você realmente desperdiçou,[n]este primeiro tiro.[n][f 1 3 65535][w][e]

[msg MND_451_1_0]
[s][vp 8 2 0 0 65535 0]...Ela foi direto para a grama alta.[n][f 1 3 65535][w][e]

[msg MSG_403_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você não está em uma posição ruim.[n]Você ainda tem quatro arremessos,[n]deve ser fácil.[n][f 1 3 65535][w][e]

[msg MND_403_1_0]
[s][vp 8 2 0 0 65535 0]Está indo bem. Ainda tenho[n]quatro tiros...[n][f 1 3 65535][w][e]

[msg MSG_452_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Uma excelente pontaria! A próxima[n]tacada deve atingir o verde.[n][f 1 3 65535][w][e]

[msg MND_452_1_0]
[s][vp 8 2 0 0 65535 0]Foi bem...! Eu quase[n]cheguei ao gramado.[n][f 1 3 65535][w][e]

[msg MSG_453_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ah... Tá no capim alto...[n][f 1 3 65535][w][e]

[msg MND_453_1_0]
[s][vp 8 2 0 0 65535 0]Ela afundou na grama alta...[n][f 1 3 65535][w][e]

[msg MSG_410_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você vai ter que dar o segundo golpe[n]da grama alta, hein...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]A julgar pelo comprimento da[n]rota, se você cometer um erro agora[n]não haverá mais nada a fazer.[n][f 1 3 65535][w][e]

[msg MND_410_1_0]
[s][vp 8 2 0 0 65535 0]Terei que desferir o segundo golpe[n]da grama alta.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Com uma jornada tão longa[n]não posso cometer mais erros.[n][f 1 3 65535][w][e]

[msg MSG_458_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você arrancou de um canteiro[n]de grama, mas colocou[n]em outro...[n][f 1 3 65535][w][e]

[msg MND_458_1_0]
[s][vp 8 2 0 0 65535 0]Ela saiu da pista e[n]caiu na grama alta...[n][f 1 3 65535][w][e]

[msg MSG_406_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tenha cuidado com este tiro,[n]OK? O green está logo ali na frente.[n][f 1 3 65535][w][e]

[msg MND_406_1_0]
[s][vp 8 2 0 0 65535 0]Quem sabe se consigo[n]enviar para o green...[n][f 1 3 65535][w][e]

[msg MSG_454_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oh... Você conseguiu![n]Você colocou a bola no gramado![n][f 1 3 65535][w][e]

[msg MND_454_1_0]
[s][vp 8 2 0 0 65535 0]A bola está no green...![n][f 1 3 65535][w][e]

[msg MSG_404_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você está em sua terceira tacada...[n]e ainda está longe do verde.[n][f 1 3 65535][w][e]

[msg MND_404_1_0]
[s][vp 8 2 0 0 65535 0]É minha terceira tacada, mas...[n]ainda falta muito[n]até chegar ao green...[n][f 1 3 65535][w][e]

[msg MSG_411_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você acertará o terceiro golpe da[n]grama alta... Você não pode cometer[n]mais erros agora.[n][f 1 3 65535][w][e]

[msg MND_411_1_0]
[s][vp 8 2 0 0 65535 0]Terei que vencer o terceiro golpe[n]da grama alta. Não posso causar[n]desastres agora.[n][f 1 3 65535][w][e]

[msg MSG_459_0_0 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Não estamos lá... Acabou[n]do outro lado,[n]bem na grama alta.[n][f 1 3 65535][w][e]

[msg MND_459_1_0]
[s][vp 8 2 0 0 65535 0]Ele voou sobre o percurso e[n]pousou na grama alta...[n][f 1 3 65535][w][e]

[msg MSG_408_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quarta tacada.[n]Acha que consegue[n]a partir daqui...?[n][f 1 3 65535][w][e]

[msg MND_408_1_0]
[s][vp 8 2 0 0 65535 0]É hora do quarto tiro.[n]Eu me pergunto se poderei[n]mandá-la para o buraco...[n][f 1 3 65535][w][e]

[msg MSG_457_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você usou muita força...[n]A bola está presa na areia.[n][f 1 3 65535][w][e]

[msg MND_457_1_0]
[s][vp 8 2 0 0 65535 0]Ela caiu na areia...[n][f 1 3 65535][w][e]

[msg MSG_407_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Então é a quarta tacada...[n]Você consegue acertar o verde?[n][f 1 3 65535][w][e]

[msg MND_407_1_0]
[s][vp 8 2 0 0 65535 0]Com esta tacada[n]devo mirar no verde...[n][f 1 3 65535][w][e]

[msg MSG_455_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Uuuh... Ela caiu na lagoa[n]em frente ao gramado...[n][f 1 3 65535][w][e]

[msg MND_455_1_0]
[s][vp 8 2 0 0 65535 0]Uh-oh. Acabou em um lago...[n][f 1 3 65535][w][e]

[msg MSG_412_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]A próxima tacada é a quarta.[n]Vamos tentar mirar no green.[n][f 1 3 65535][w][e]

[msg MND_412_1_0]
[s][vp 8 2 0 0 65535 0]É o quarto tiro. Eu tenho que tentar[n]apontar para o verde...[n][f 1 3 65535][w][e]

[msg MSG_460_0_0 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ela caiu na lagoa novamente...[n][f 1 3 65535][w][e]

[msg MND_460_1_0]
[s][vp 8 2 0 0 65535 0]Ela afundou na lagoa novamente...[n][f 1 3 65535][w][e]

[msg MSG_409_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Este é o quinto tiro.[n]Você não terá outra chance,[n]aponta bem...![n][f 1 3 65535][w][e]

[msg MND_409_1_0]
[s][vp 8 2 0 0 65535 0]É minha última chance...![n][f 1 3 65535][w][e]

[msg MSG_456_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Nossa, a bola foi direto para a caçapa![n][f 1 3 65535][w][e]

[msg MND_456_1_0]
[s][vp 8 2 0 0 65535 0]Eu envasei...![n][f 1 3 65535][w][e]

[msg MSG_413_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quinto tiro. Você deve mandá-la para o buraco a[n]todo custo.[n][f 1 3 65535][w][e]

[msg MND_413_1_0]
[s][vp 8 2 0 0 65535 0]É minha última chance...![n][f 1 3 65535][w][e]

[msg MSG_461_0_0 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você não conseguiu tirá-lo[n]da areia...[n][f 1 3 65535][w][e]

[msg MND_461_1_0]
[s][vp 8 2 0 0 65535 0]Cara, a bola ainda está[n]na areia...[n][f 1 3 65535][w][e]

[msg MSG_470_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Uau, você concluiu[n]sem pestanejar. E você também[n]deixou uma chance.[n][f 1 3 65535][w][e]

[msg MND_470_1_0]
[s][vp 8 2 0 0 65535 0]Nada mal,[n]mas só me resta uma chance.[n][f 1 3 65535][w][e]

[msg MSG_471_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você chegou perto do desastre,[n]mas finalmente conseguiu![n][f 1 3 65535][w][e]

[msg MND_471_1_0]
[s][vp 8 2 0 0 65535 0]De alguma forma eu consegui[n]completá-lo...[n][f 1 3 65535][w][e]

[msg MSG_CLEAR_URA_MORU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1166 65535 0]O livro de técnicas secretas é[n]ajudado, hein? Você é sempre tão[n]eficiente. Eu te admiro![n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Tentar controlar seus[n]cursos ensinou você a prestar[n]mais atenção aos detalhes.[n][f 1 3 65535][w][e]

[msg MND_CLEAR_URA_NULL]
[s][vp 8 2 0 78 65535 0]A técnica secreta tornou o jogo[n]menos emocionante do que o normal...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Mas sinto que focar em minha mira me ajudou a[n]aprimorar meu [f 4 11 2][clr 26][f 4 12 2][n][clr 27]...[n][f 1 3 65535][w][e]

[msg MSG_CLEAR_MORU [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 1019 65535 0][f 4 22 65535 1 41]Tentar controlar seus[n]cursos ensinou você a prestar[n]mais atenção aos detalhes.[n][f 1 3 65535][w][e]

[msg MND_CLEAR_NULL]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Sinto que adquiri[n]mais [f 4 11 2][clr 26][f 4 12 2][clr 27]...[n][f 1 3 65535][w][e]

[msg MSG_800_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1065 65535 0]Neste ponto, é impossível para você terminar[n]abaixo do par...[n][f 1 3 65535][w][e]

[msg MND_800_1_0]
[s][vp 8 2 0 72 65535 0]Neste ponto é impossível[n]fechar abaixo do par...[n][f 1 3 65535][w][e]

[msg MSG_GAMEOVER_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1025 65535 0]Fim de jogo...[n]Que tela deprimente.[n][f 1 3 65535][w][e]

[msg MND_GAMEOVER_NULL]
[s][vp 8 2 0 87 65535 0]Fim de jogo...[n][f 1 3 65535][w][e]

[msg MSG_FAILED_UP [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você perdeu... Mas checar[n]suas tacadas te ensinou[n]a prestar atenção aos detalhes.[n][f 1 3 65535][w][e]

[msg MND_FAILED_UP]
[s][vp 8 2 0 0 65535 0]Eu falhei, mas focar em[n]minha mira me ajudou a aprimorar[n]minha perícia...[n][f 1 3 65535][w][e]

[msg MSG_HINTO_BOOK_NO [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu gostaria que houvesse uma maneira de tornar[n]este jogo mais fácil...[n][f 1 3 65535][w][e]

[msg MND_HINTO_BOOK_NO]
[s][vp 8 2 0 0 65535 0]Se ao menos houvesse uma maneira[n]de diminuir a dificuldade...[n][f 1 3 65535][w][e]

[msg MSG_HINTO_BOOK00 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Não tem um livro sobre técnicas secretas? Talvez[n]você devesse tentar ler algum dia.[n][f 1 3 65535][w][e]

[msg MND_HINTO_BOOK04]
[s][vp 8 2 0 0 65535 0]Agora que penso nisso, tenho um livro[n]sobre técnicas secretas...Talvez[n]deva lê-lo algum dia.[n][f 1 3 65535][w][e]

[msg MSG_BOOK_DONE_M [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]É tão difícil? Devemos[n]tentar novamente, da próxima vez![n][f 1 3 65535][w][e]

[msg MND_BOOK_DONE_N]
[s][vp 8 2 0 0 65535 0]É bem difícil...[n]Vou tentar de novo mais tarde.[n][f 1 3 65535][w][e]

[msg MSG_GAME_END_MORU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1166 65535 0]Está ficando tarde. Vamos parar[n]aqui, esta noite, ok?[n][f 1 3 65535][w][e]

[msg MND_GAME_END_NULL]
[s][vp 8 2 0 57 65535 0]Acho que pratiquei o suficiente por hoje...[n][f 1 3 65535][w][e]

[msg MSG_GAME_END_MORU_DAY [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1166 65535 0]Demorou muito...[n]Deveríamos parar[n]de jogar por enquanto. O que você diz?[n][f 1 3 65535][w][e]

[msg MND_GAME_END_NULL_DAY]
[s][vp 8 2 0 57 65535 0]Hum, talvez eu deva fazer uma pausa.[n]Acho que joguei demais...[n][f 1 3 65535][w][e]

[msg MSG_DEBUG [for debug]]
[s][vp 8 2 0 0 65535 0]Modo de Depuração[n][f 1 3 65535][w][e]

[sel SEL_DEBUG top]
[s]com morgana[e]
[s]sem morgana[e]

[msg MSG_DEBUG_2 [for debug]]
[s][vp 8 2 0 0 65535 0]Modo de Depuração[n][f 1 3 65535][w][e]

[sel SEL_DEBUG_2 top]
[s]Rota 1[e]
[s]Rota 2[e]
[s]Rota 3[e]
[s]Caminho 4[e]

[msg MSG_DEBUG_3 [for debug]]
[s][vp 8 2 0 0 65535 0]Modo de Depuração[n][f 1 3 65535][w][e]

[sel SEL_DEBUG_3 top]
[s]Primeira vez[e]
[s]Segundo tempo[e]

