[msg MSG_007_0_0 [Manager]]
[s][vp 8 2 0 58451 5 0]Oh, você é o novo tempo parcial, certo?[n]Eu tenho esperado você.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Não há necessidade de se apresentar. Na[n]verdade, preciso que você comece a[n]trabalhar imediatamente.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 58452 5 0]Você tem alguma dúvida sobre o trabalho?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0_2nd [Manager]]
[s][vp 8 2 0 0 5 0]Algo mais?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]O que o trabalho implica?[e]
[s]Existem outros funcionários?[e]
[s]Não, na verdade não.[e]

[msg MSG_009_0_0 [Manager]]
[s][vp 8 2 0 58453 5 0]Pegue os pedidos dos clientes, prepare-os,[n]sirva-os, ligue-os e depois limpe a loja.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]As refeições estão prontas, por isso devem[n]ser simples. Apenas certifique-se de que[n]você é legal com os clientes, ok?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Manager]]
[s][vp 8 2 0 58454 5 0]Não exatamente. Nosso orçamento foi cortado,[n]apesar de ter uma equipe de poucos anos...[n]então você terá que fazer tudo sozinho.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Você é um cara jovem, certo?[n]Você vai ficar bem. Vou pagar mais para[n]compensar o trabalho extra![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1038 65535 0]Este trabalho é ridículo. Você tem que fazer[n]tudo sozinho desde o início?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ah bem. Apenas dê o seu melhor, eu acho. Eu[n]estarei torcendo por você.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1029 65535 0]Ei, ainda existem pratos sujos na mesa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]E há clientes na frente esperando para[n]pagar... você vai ficar bem?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1029 65535 0]Esse cliente à sua frente está esperando[n]para pagar. Ooh, esse é um rosto de[n]aparência zangado...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ei, alguém quer mudar sua ordem. Adicionar[n]um ovo? Eles deveriam ter nos dito mais[n]cedo.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1179 65535 0]Ei, a carne acabou. Você vai queimar se[n]deixar cozinhar mais.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Aquele cliente lá quer pedir comida. Quem[n]tem tempo para preparar isso?[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Manager]]
[s][vp 8 2 0 58456 5 0]Tudo bem, bom trabalho. Você pode sair[n]agora, já que é o fim do seu turno.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Este é o seu pagamento hoje. Obrigada.[n]Bem, espero que você possa continuar assim.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Th-isto foi tão difícil... este trabalho é[n]tão exigente...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Mas você ainda conseguiu todos esses pedidos[n]sozinho. Se você me perguntar, você era[n]bastante proficiente.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu não te culpo por parecer exausto...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Mas você ainda conseguiu todos esses pedidos[n]sozinho. Se você me perguntar, você era[n]bastante proficiente.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]A--você está bem? Você estava sozinho por aí[n]todo esse tempo...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Mas você ainda conseguiu todos esses pedidos[n]sozinho. Se você me perguntar, você era[n]bastante proficiente.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1050 65535 0]Vamos lá, vamos sair.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1181 65535 0]A-tudo certo. Fique calmo e lembre-se das[n]ordens![n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]O que a primeira pessoa pediu?[n][f 1 3 65535][w][e]

[msg MSG_028_1_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1180 65535 0]Sim está certo![n][f 1 3 65535][w][e]

[msg MSG_028_2_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]O que a segunda pessoa pediu?[n][f 1 3 65535][w][e]

[msg MSG_028_3_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1183 65535 0]Sim, eles disseram isso![n][f 1 3 65535][w][e]

[msg MSG_028_4_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]E o terceiro cliente?[n][f 1 3 65535][w][e]

[msg MSG_028_5_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1166 65535 0]Sim. Foi o que ouvi também![n][f 1 3 65535][w][e]

[msg MSG_028_6_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]O que o quarto lugar pediu?[n][f 1 3 65535][w][e]

[msg MSG_028_7_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1157 65535 0]Sim você está certo! Essa foi a ordem![n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1029 65535 0]H-hey, isso não está certo! Era uma tigela[n]de carne média.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1037 65535 0]Ei, espere um segundo. Eles não queriam uma[n]grande tigela de carne?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1139 65535 0]Não, espere! Era uma tigela de churrasco[n]médio...[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1018 65535 0]Sério!? Eu pensei que eles queriam uma[n]grande tigela de churrasco.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1027 65535 0]Hum? Eu pensei que era uma tigela de curry[n]médio.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1029 65535 0]Isso não está certo. Eles pediram uma grande[n]tigela de curry.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1038 65535 0]Não, não é isso. Era uma tigela de natto[n]médio.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1043 65535 0]Não, não está certo, é? Era uma grande[n]tigela de natto.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0]Não, era uma tigela média Hui Guo Rou![n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1065 65535 0]Não, isso não está certo. Eles queriam uma[n]grande tigela Hui Guo Rou![n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tudo bem, agora você só precisa fazer tudo e[n]servi-los![n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Uh-oh, esse cliente está esperando há algum[n]tempo! Pressa![n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Isto é mau. Estamos fazendo os clientes[n]esperarem. Pegue o ritmo![n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Manager]]
[s][vp 8 2 0 58458 5 0]Uau, bom trabalho![n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Parece que havia muitos clientes hoje, mas[n]você lidou com isso bem por conta própria![n][f 1 3 65535][w][e]
[s][vp 8 2 0 58455 5 0]Eu te paguei um pouco mais hoje. Bom[n]trabalho, continue assim![n][f 1 3 65535][w][e]

[msg MSG_049_0_1 [Manager]]
[s][vp 8 2 0 58458 5 0]Uau, bom trabalho![n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Parece que havia muitos clientes hoje, mas[n]você lidou com isso bem por conta própria![n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Estávamos tão lotados hoje quanto costumamos [clr 2]Dia de Yakiniku [clr 27]... Eu me pergunto se houve algum evento[n]acontecendo nas proximidades.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 58455 5 0]Eu te paguei um pouco mais hoje. Bom[n]trabalho, continue assim![n][f 1 3 65535][w][e]

[msg MSG_049_0_2 [Manager]]
[s][vp 8 2 0 58458 5 0]Uau, bom trabalho![n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Parece que havia muitos clientes hoje, mas[n]você lidou com isso bem por conta própria![n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]O problema é que consistentemente temos[n]muitos clientes em [n][clr 2]Dia de Yakiniku [clr 27], então... ninguém quer trabalhar naquele[n]dia.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 58455 5 0]Eu te paguei um pouco mais hoje. Bom[n]trabalho, continue assim![n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você foi incrível hoje, lidando com tantos[n]pedidos![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Tenho certeza de que foi difícil, mas acho[n]que você lidou com tudo de maneira bastante[n]proficiente![n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Manager]]
[s][vp 8 2 0 58456 5 0]Tudo bem, bom trabalho. Havia muitos[n]clientes hoje.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Tenho certeza de que foi muito trabalho, mas[n]você lidou com tudo por conta própria.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Não é muito, mas paguei um pouco mais do que[n]o normal hoje. Mantenha o bom trabalho![n][f 1 3 65535][w][e]

[msg MSG_051_0_1 [Manager]]
[s][vp 8 2 0 58456 5 0]Tudo bem, bom trabalho. Havia muitos[n]clientes hoje.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Tenho certeza de que foi muito trabalho, mas[n]você lidou com tudo por conta própria.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Não é como hoje era [clr 2]Dia de Yakiniku [clr 27]no entanto.[n]Gostaria de saber se houve um evento[n]acontecendo nas proximidades.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Não é muito, mas paguei um pouco mais do que[n]o normal hoje. Mantenha o bom trabalho![n][f 1 3 65535][w][e]

[msg MSG_051_0_2 [Manager]]
[s][vp 8 2 0 58456 5 0]Tudo bem, bom trabalho. Havia muitos[n]clientes hoje.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Tenho certeza de que foi muito trabalho, mas[n]você lidou com tudo por conta própria.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]O problema é que consistentemente temos[n]muitos clientes em [n][clr 2]Dia de Yakiniku [clr 27], então... ninguém quer trabalhar naquele[n]dia.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Não é muito, mas paguei um pouco mais do que[n]o normal hoje. Mantenha o bom trabalho![n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Cara... o gerente realmente sabe como[n]amotá-lo. Você se saiu bem sozinho.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Você cometeu alguns erros, mas foi bom [f 4 11 2][clr 26][f 4 12 2][clr 27]Treinamento, não foi?[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Manager]]
[s][vp 8 2 0 58456 5 0]Tudo bem, bom trabalho. Havia muitos[n]clientes hoje.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Nem sempre é assim, então espero que você[n]possa voltar em breve.[n][f 1 3 65535][w][e]

[msg MSG_053_0_1 [Manager]]
[s][vp 8 2 0 58456 5 0]Tudo bem, bom trabalho. Havia muitos[n]clientes hoje.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Não é como hoje era [clr 2]Dia de Yakiniku [clr 27]no entanto.[n]Gostaria de saber se houve um evento[n]acontecendo nas proximidades.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Nem sempre é assim, então espero que você[n]possa voltar em breve.[n][f 1 3 65535][w][e]

[msg MSG_053_0_2 [Manager]]
[s][vp 8 2 0 58456 5 0]Tudo bem, bom trabalho. Havia muitos[n]clientes hoje.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]O problema é que consistentemente temos[n]muitos clientes em [n][clr 2]Dia de Yakiniku [clr 27], então... ninguém quer trabalhar naquele[n]dia.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Nem sempre é assim, então espero que você[n]possa voltar em breve.[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Cara... o gerente realmente sabe como[n]amotá-lo. Você se saiu bem sozinho.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Você cometeu alguns erros, mas foi bom [f 4 11 2][clr 26][f 4 12 2][clr 27]Treinamento, não foi?[n][f 1 3 65535][w][e]

[msg MSG_055_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1169 65535 0]Ufa... bem, acho que devemos ir para casa em[n]breve.[n][f 1 3 65535][w][e]

[msg MSG_080_0_0 [Customer]]
[s][vp 8 2 0 0 65535 0]Ei. Tigela de carne média, por favor.[n][f 1 3 65535][w][e]

[msg MSG_081_0_0 [Customer]]
[s][vp 8 2 0 0 65535 0]Grande tigela de carne, por favor.[n][f 1 3 65535][w][e]

[msg MSG_082_0_0 [Customer]]
[s][vp 8 2 0 0 65535 0]Oh, posso ter uma tigela de churrasco médio?[n][f 1 3 65535][w][e]

[msg MSG_083_0_0 [Customer]]
[s][vp 8 2 0 0 65535 0]Dê-me uma grande tigela de churrasco.[n][f 1 3 65535][w][e]

[msg MSG_084_0_0 [Customer]]
[s][vp 8 2 0 0 65535 0]Uma tigela média de curry.[n][f 1 3 65535][w][e]

[msg MSG_085_0_0 [Customer]]
[s][vp 8 2 0 0 65535 0]Uma tigela de curry. Ah, torne-o grande.[n][f 1 3 65535][w][e]

[msg MSG_086_0_0 [Customer]]
[s][vp 8 2 0 0 65535 0]Uma tigela de natto médio.[n][f 1 3 65535][w][e]

[msg MSG_087_0_0 [Customer]]
[s][vp 8 2 0 0 65535 0]Uma grande tigela de natto, por favor.[n][f 1 3 65535][w][e]

[msg MSG_088_0_0 [Customer]]
[s][vp 8 2 0 0 65535 0]Uma tigela média Hui Guo Rou![n][f 1 3 65535][w][e]

[msg MSG_089_0_0 [Customer]]
[s][vp 8 2 0 0 65535 0]Uma tigela Hui Guo Rou, grande, por favor![n][f 1 3 65535][w][e]

[sel SEL_GYUDON_ANSWER0 top]
[s]Tigela de carne média [e]
[s]Grande tigela de churrasco [e]
[s]Tigela de curry médio [e]

[sel SEL_GYUDON_ANSWER1 top]
[s]Tigela de natto médio [e]
[s]Tigela de carne média [e]
[s]Tigela médio hui guo rou [e]

[sel SEL_GYUDON_ANSWER2 top]
[s]Grande tigela de curry [e]
[s]Grande tigela de churrasco [e]
[s]Tigela de carne média [e]

[sel SEL_GYUDON_ANSWER3 top]
[s]Grande tigela de carne [e]
[s]Grande tigela de churrasco [e]
[s]Grande tigela de natto [e]

[sel SEL_GYUDON_ANSWER4 top]
[s]Tigela de curry médio [e]
[s]Grande tigela de carne [e]
[s]Grande tigela Hui Guo Rou [e]

[sel SEL_GYUDON_ANSWER5 top]
[s]Tigela de natto médio [e]
[s]Tigela de curry médio [e]
[s]Grande tigela de carne [e]

[sel SEL_GYUDON_ANSWER6 top]
[s]Tigela de churrasco médio [e]
[s]Tigela de curry médio [e]
[s]Tigela de carne média [e]

[sel SEL_GYUDON_ANSWER7 top]
[s]Grande tigela de curry [e]
[s]Tigela de churrasco médio [e]
[s]Grande tigela Hui Guo Rou [e]

[sel SEL_GYUDON_ANSWER8 top]
[s]Grande tigela Hui Guo Rou [e]
[s]Grande tigela de churrasco [e]
[s]Tigela de churrasco médio [e]

[sel SEL_GYUDON_ANSWER9 top]
[s]Grande tigela de churrasco [e]
[s]Grande tigela de carne [e]
[s]Grande tigela de curry [e]

[sel SEL_GYUDON_ANSWER10 top]
[s]Tigela de natto médio [e]
[s]Grande tigela de churrasco [e]
[s]Tigela médio hui guo rou [e]

[sel SEL_GYUDON_ANSWER11 top]
[s]Tigela de carne média [e]
[s]Tigela médio hui guo rou [e]
[s]Grande tigela de churrasco [e]

[sel SEL_GYUDON_ANSWER12 top]
[s]Tigela de curry médio [e]
[s]Grande tigela de carne [e]
[s]Grande tigela Hui Guo Rou [e]

[sel SEL_GYUDON_ANSWER13 top]
[s]Tigela de churrasco médio [e]
[s]Tigela de curry médio [e]
[s]Tigela médio hui guo rou [e]

[sel SEL_GYUDON_ANSWER14 top]
[s]Tigela de natto médio [e]
[s]Grande tigela de curry [e]
[s]Tigela de curry médio [e]

[sel SEL_GYUDON_ANSWER15 top]
[s]Grande tigela de curry [e]
[s]Tigela de natto médio [e]
[s]Grande tigela de carne [e]

[sel SEL_GYUDON_ANSWER16 top]
[s]Tigela de natto médio [e]
[s]Grande tigela de curry [e]
[s]Grande tigela Hui Guo Rou [e]

[sel SEL_GYUDON_ANSWER17 top]
[s]Tigela de churrasco médio [e]
[s]Grande tigela de churrasco [e]
[s]Grande tigela de curry [e]

[sel SEL_GYUDON_ANSWER18 top]
[s]Tigela de natto médio [e]
[s]Grande tigela de curry [e]
[s]Tigela de carne média [e]

[sel SEL_GYUDON_ANSWER19 top]
[s]Tigela médio hui guo rou [e]
[s]Tigela de natto médio [e]
[s]Grande tigela de curry [e]

[sel SEL_GYUDON_ANSWER20 top]
[s]Grande tigela de carne [e]
[s]Grande tigela de churrasco [e]
[s]Tigela de natto médio [e]

[sel SEL_GYUDON_ANSWER21 top]
[s]Grande tigela de natto [e]
[s]Grande tigela de churrasco [e]
[s]Grande tigela Hui Guo Rou [e]

[sel SEL_GYUDON_ANSWER22 top]
[s]Tigela de curry médio [e]
[s]Grande tigela de natto [e]
[s]Tigela de carne média [e]

[sel SEL_GYUDON_ANSWER23 top]
[s]Grande tigela de carne [e]
[s]Tigela de churrasco médio [e]
[s]Grande tigela de natto [e]

[sel SEL_GYUDON_ANSWER24 top]
[s]Tigela médio hui guo rou [e]
[s]Tigela de curry médio [e]
[s]Tigela de natto médio [e]

[sel SEL_GYUDON_ANSWER25 top]
[s]Grande tigela de natto [e]
[s]Tigela médio hui guo rou [e]
[s]Tigela de churrasco médio [e]

[sel SEL_GYUDON_ANSWER26 top]
[s]Grande tigela de curry [e]
[s]Tigela de churrasco médio [e]
[s]Tigela médio hui guo rou [e]

[sel SEL_GYUDON_ANSWER27 top]
[s]Grande tigela Hui Guo Rou [e]
[s]Tigela de natto médio [e]
[s]Tigela de churrasco médio [e]

[sel SEL_GYUDON_ANSWER28 top]
[s]Tigela de curry médio [e]
[s]Grande tigela Hui Guo Rou [e]
[s]Grande tigela de carne [e]

[sel SEL_GYUDON_ANSWER29 top]
[s]Tigela de natto médio [e]
[s]Tigela de churrasco médio [e]
[s]Grande tigela Hui Guo Rou [e]

[msg MSG_RYUUJI_0_1 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7029 65535 0]Uau, eu sabia que você parecia familiar![n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 5 13 8 5 2]Fica hella lotado aqui às vezes...[n]Não se sobrecarregue, Aight?[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]De qualquer forma, vou pegar uma tigela de[n]carne com molho extra![n][f 1 3 65535][w][e]

[msg MSG_RYUUJI_1_1 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54250 65535 0]'Sup, trabalhando duro?[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 5 13 8 5 2]Eu recebo uma vibração diferente de você[n]quando você está trabalhando aqui. Você[n]parece mais maduro...[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Aight, me dê uma grande tigela de carne, por[n]favor![n][f 1 3 65535][w][e]

[msg MSG_YOSIDA_0_1 [Yoshida]]
[s][bup 0 112 500 0 0][f 4 10 65535 0 0][vp 8 2 0 20020 65535 0]Ah é você. Boa noite.[n][f 1 3 65535][w][e]
[s][bup 0 112 501 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 5 13 20 5 1012]Trabalhando duro como sempre, ao que parece.[n]Que rapaz confiável.[n][f 1 3 65535][w][e]
[s][bup 0 112 501 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bem, então, suponho que vou pedir uma tigela[n]de carne média.[n][f 1 3 65535][w][e]

[msg MSG_YOSIDA_1_1 [Yoshida]]
[s][bup 0 112 500 0 0][f 4 10 65535 0 0][vp 8 2 0 20006 65535 0]Boa noite. Parece que você está trabalhando[n]duro.[n][f 1 3 65535][w][e]
[s][bup 0 112 501 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 5 13 20 5 1012]Ver a maneira como você trabalha me motiva a[n]trabalhar mais também.[n][f 1 3 65535][w][e]
[s][bup 0 112 501 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oh, eu provavelmente deveria pedir agora.[n]Queria uma tigela de carne média com ovo.[n][f 1 3 65535][w][e]

[msg MSG_DEBUG_NPC [デバッグ]]
[s][vp 8 2 0 0 65535 0]Amigo aparece [n][f 1 3 65535][w][e]

[sel SEL_DEBUG_NPC top]
[s]竜司(初回)[e]
[s]竜司(汎用)[e]
[s]吉田(初回)[e]
[s]吉田(汎用)[e]
[s]誰も来ない[e]

