[msg MSG_preDartsStart_Moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tudo bem, vamos começar este jogo de equipe.[n][f 1 3 65535][w][e]

[sel SEL_NextPlayOrder_Ans top]
[s]Vamos fazê-lo.[e]
[s]Como são coisas com [var 0]...[e]
[s]Estou ligando para isso um dia.[e]

[sel SEL_PlayCourse_Ans top]
[s]Vamos jogar 301.[e]
[s]Estou pensando 501.[e]
[s]Estamos fazendo 701.[e]

[msg MND_DartsHeroBatonInfo]
[s][vp 8 2 0 0 65535 0]Eu sinto que aprendi algo jogando em um[n]time...[n][f 1 3 65535][w][e]

[msg MSG_DartsEnd_Moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1126 65535 0]Podemos treinar e nos divertir ao mesmo[n]tempo. Este é um lugar bastante útil.[n][f 1 3 65535][w][e]

[msg SYS_FinishInfo]
[s]Se houver apenas uma pequena quantidade da[n]sua pontuação na rodada 4, seu companheiro[n]de equipe poderá pedir conselhos sobre como[n]deve jogar.[n][w][e]
[s]Há uma chance maior de eles terminando o[n]jogo se você der uma resposta que os motiva.[n][w][e]
[s]Quando seu companheiro de equipe termina[n]dessa maneira, sua sinergia com esse[n]companheiro de equipe aumenta, aumentando o[n]nível da sua classificação.[n][w][e]

[msg MSG_GameEnd_ChallengeBon [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 53125 65535 0][f 4 22 65535 1 41]Uau... isso foi uma habilidade louca![n][f 1 3 65535][w][e]

[msg MSG_GameEnd_ChallengeBon_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1045 65535 0][f 4 22 65535 1 41]Você jogou muito bem naquele jogo![n][f 1 3 65535][w][e]

[msg SYS_AwardInfo]
[s]Ter um bom desempenho, como fazer um[n]hat-trick ou tonelada alta, aumentará o seu [n][f 4 11 2][clr 26][f 4 12 2][clr 27]No final do jogo Darts.[n][w][e]

[msg MSG_AwardInfo_moru [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Parece que há muitos prêmios diferentes[n]neste caso. Hehe, eu fiz minha lição de[n]casa![n][f 1 3 65535][w][e]

[msg MSG_Minigame_Kiyou [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1020 65535 0][f 4 22 65535 1 41]Cansado de todo aquele arremesso preciso?[n]Eu posso dizer que você cresceu um pouco.[n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7103 65535 0]Tudo bem, vamos primeiro![n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7080 65535 0]Yo, yo! Eu quero ir a seguir![n][f 1 3 65535][w][e]

[msg MSG_NextRetry_ryuji [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 7192 65535 0]Cara, terminar nesta nota seria péssimo,[n]você não acha? Vamos lá, vamos fazer mais[n]um![n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_ryuji [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7063 65535 0]Aww... isso não é divertido.[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bem, tudo bem. Vamos jogar na próxima vez![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Vamos com 301. Hehe, isso será fácil![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Vamos com 501. Um pouco difícil, mas[n]queremos um desafio, sim?[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hmm, que conjunto de regras para ir...[n]Você sabe o que? Vou deixar para você![n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu ouvi você! Então [var 0]isso é.[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7110 65535 0]Tudo bem, vamos fazer isso! Vamos conseguir[n]0 pontos, bem no ponto![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7045 65535 0]Acho que estou acordado... eu estou saindo![n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7048 65535 0]Na rodada 3. hehe, você conseguiu esse homem![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_ryuji [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Ok... esta é a minha última rodada. Melhor[n]não estragar tudo, hein?[n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7080 65535 0]Para o bem ou para o mal, esta é a última[n]rodada! É tudo você![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_ryuj [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7155 65535 0]Oof... ei, não deixe isso chegar até você[n]cara. Vou levar daqui![n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_ryuji [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7025 65535 0]Aw, porcaria... desculpe cara, tudo depende[n]de você...[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7027 65535 0]... Parece que eu poderia conseguir[n]acabar... cara, estou ficando tão nervoso![n][f 1 3 65535][w][e]

[sel SEL_Finish_ryuji top]
[s]Você tem que se psiciar![e]
[s]Basta jogar naturalmente.[e]
[s]Não pense em nada.[e]

[msg MSG_Finish_Act01_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7186 65535 0]Heh, eu entendo você! Eu estou indo para[n]este![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_ryuji [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7133 65535 0]Você está certo, não posso me deixar[n]endurecer... acho que vou relaxar e acender[n]isso com isso.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_ryuji [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7177 65535 0]O-oh sim? Não pense em nada?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54214 65535 0]Conseguimos! 0 pontos![n]Cara, não somos apenas o melhor time!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Heh... cara, eu me sinto tão motivado agora![n]Talvez porque eu soubesse que você estava[n]contando comigo?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_r [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7023 65535 0]Conseguimos! 0 pontos![n]Cara, não somos apenas o melhor time!?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_ry [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0][var 0]Esquerda, hein? Argh, quase chegamos a 0...[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7114 65535 0]Ainda tinha [var 0]Pontos restantes...[n]Cara, esse resultado meio que é péssimo.[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54242 65535 0]Cara, isso foi divertido! Trabalhou com um[n]bom suor lá![n][f 1 3 65535][w][e]

[msg MSG_DartsBye_ryuji [Ryuji]]
[s][vp 8 2 0 7062 65535 0]Welp, veja você![n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1051 65535 0][f 4 2], vamos nos unir para o primeiro jogo. Heh,[n]hora de mostrar minhas coisas.[n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1067 65535 0]Eu estou acordado a seguir! Lemme mostra o[n]que essas patas podem fazer![n][f 1 3 65535][w][e]

[msg MSG_NextRetry_moru [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0]Isso não pode estar certo... mais uma[n]tentativa![n]Você também não está satisfeito com isso,[n]não é?[n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_moru [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1043 65535 0]...Huh? Mas eu estava todos ansiosos para[n]ir...[n][f 1 3 65535][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bem, tenho certeza de que você tem muito em[n]que pensar. Vamos jogar na próxima vez.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Vamos com 301. Deve ser uma fila se[n]combinarmos nossa força![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Vamos com 501. Fique focado, ou você está em[n]um despertar rude.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Vamos ver, qual conjunto de regras devemos[n]usar...?[n]Vou deixar você decidir![n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tudo bem! Então vamos jogar [var 0].[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1156 65535 0]Você está pronto para ir? Vamos dar tudo o[n]que temos![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1117 65535 0]Parece que é a minha vez a seguir![n]Nyahaha, não caia por mim agora.[n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_moru [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 1034 65535 0]Então, agora estamos na 3 rodada... temos[n]que realmente prestar atenção à pontuação[n]agora![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1133 65535 0]Então esta é a minha última rodada...[n]Heh, isso está começando a ficar[n]interessante.[n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]Esta é a última rodada! Eu sei que você vai[n]passar![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_moru [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1027 65535 0]Er, não se preocupe com isso! Vou cuidar[n]disso![n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_moru [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1112 65535 0]... S-Sorry! Isso foi descuidado da minha[n]parte...[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_2 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1130 65535 0]Hmm... temos a chance de terminar aqui. Tudo[n]bem... aqui vai![n][f 1 3 65535][w][e]

[sel SEL_Finish_moru top]
[s]Eu preciso de alguns reflexos semelhantes a[n]gatos.[n][e]
[s]Seu cabelo está de pé no fim.[e]
[s]Estou contando com você.[e]

[msg MSG_Finish_Act01_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1031 65535 0]Cara, você com certeza tem um caminho com as[n]palavras! Acho que tenho isso agora![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1024 65535 0]Oh, tudo bem... mas eles definitivamente não[n]são parecidos com gatos, ok!?[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_moru [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0]O-oh, certo... ok, veja?[n]Eu... estou calmo miau...![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_2 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1184 65535 0]Um 0 perfeito! Ninguém pode nos vencer[n]quando estamos em parceria![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Era porque eu podia sentir sua motivação.[n]Isso me deixou capaz de me esforçar mais do[n]que o normal.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_m [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1045 65535 0]Um 0 perfeito! Ninguém pode nos vencer[n]quando estamos em parceria![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_mo [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0][var 0]Saiu... nós quase tivemos...[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_2 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0][var 0]Pontos restantes... isso não foi tão bom.[n]Desculpe, eu deveria estar indo melhor...[n][f 1 3 65535][w][e]

[msg MSG_DartsBye_moru [Morgana]]
[s][vp 8 2 0 1049 65535 0]Tudo bem, vamos voltar.[n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 6019 65535 0]Ooh![f 4 2], vamos você e eu conseguir o primeiro jogo![n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6075 65535 0]Eu quero ir a seguir! Estou ansioso para[n]jogar![n][f 1 3 65535][w][e]

[msg MSG_NextRetry_anne [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 6021 65535 0]Eu não quero que termine assim...![n]Ei, podemos jogar mais um?[n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_anne [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6063 65535 0]Oh... bem, isso é lamentável.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Acho que vamos jogar outra hora![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Vamos fazer 301. Acho que posso lidar com[n]isso![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Vamos fazer 501. ehehe... Vou tentar não[n]estragar tudo.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hmm... que regras devemos ir com...[n]Desculpe, você se importaria de decidir?[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Entendi! Então vamos jogar [var 0]![n][f 1 3 65535][w][e]

[msg MSG_StartRound01_anne [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54043 65535 0]Boa sorte! Estou torcendo por você![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_anne [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 54044 65535 0]Ok, eu estou bem. Caramba, estou ficando[n]nervoso![n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6117 65535 0]É a 3 rodada agora... vamos continuar![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_anne [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 6028 65535 0]Esta é a minha última rodada...[n]Tenho que garantir que eu não estrague tudo![n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6185 65535 0]Última rodada! Você consegue fazer isso![n]Eu acredito em você![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_anne [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 6027 65535 0]Uh-oh... você ultrapassou lá?[n]Tudo bem, não deixe isso chegar até você![n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_anne [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6170 65535 0]... eu, sinto muito. Eu fui um pouco[n]afastado...[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_3 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 6039 65535 0]Oh... podemos terminar aqui![n]... Eu acho que estou nervoso.[n][f 1 3 65535][w][e]

[sel SEL_Finish_anne top]
[s]Termine isso.[e]
[s]Está ficando quente aqui?[e]
[s]Basta jogar como normal.[e]

[msg MSG_Finish_Act01_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6060 65535 0]Oh, certo! Sim, isso é tudo o que você[n]realmente pode fazer![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6048 65535 0]Do que você está falando!?[n]... hehe, isso realmente me ajudou a relaxar.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_anne [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6190 65535 0]Sure. Eu tenho esse.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_3 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54042 65535 0]Conseguimos! 0 pontos exatamente![n]Fazemos uma equipe incrível ou o quê?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu podia sentir que você estava contando[n]comigo...[n]Então eu tive que me esforçar muito![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_a [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54042 65535 0]Conseguimos! 0 pontos exatamente![n]Fazemos uma equipe incrível ou o quê?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_an [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 6038 65535 0][var 0]Esquerda, hein... argh, quase tínhamos![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_3 [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 6038 65535 0][var 0]Pontos restantes...[n]Ahaha, isso não é muito bom.[n]Desculpe, isso foi muito difícil para mim...[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54049 65535 0]Ufa... isso foi estressante, mas divertido![n][f 1 3 65535][w][e]

[msg MSG_DartsBye_anne [Ann]]
[s][vp 8 2 0 6053 65535 0]Bem, vejo você por perto.[n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 4080 65535 0]Vamos nos unir para a primeira partida, [n][f 4 2]. * risada* Como é emocionante...![n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4034 65535 0]Tudo bem, eu irei a seguir.[n]Vamos dançar... com dardos![n][f 1 3 65535][w][e]

[msg MSG_NextRetry_yusuke [Yusuke]]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 4033 65535 0]Parece que este não é um jogo comum...![n]Por favor, deixe-me tentar de novo![n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_yusuke [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 4064 65535 0]...Eu vejo. Isso é lamentável.[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No entanto, pode ser melhor não ser[n]exagerado. O desafio pode esperar até outra hora![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Vamos com 301. Tudo começa com o básico.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Vamos com 501. Desejo me dar um desafio...[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hmm, que conjunto de regras devemos usar...?[n]Minhas desculpas, mas vou deixar a decisão[n]para você.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_yusuk [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Muito bem. Vamos jogar [var 0]então.[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_yusuke [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4060 65535 0]E assim começa... não há necessidade de ser[n]elaborado; Vá com a abordagem natural![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_yusuke [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4048 65535 0]Minha vez... * risada* Eu me deleito com[n]esse sentimento de tensão...![n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_yusuke [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4107 65535 0]É a 3 rodada... o tempo certamente voa[n]quando você está se divertindo...![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_yusuke [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 4083 65535 0]Este é um ponto crítico para mim.[n]Por favor, continue quando eu for embora...![n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4198 65535 0]A última rodada... eu vou te assistir até[n]seus momentos finais, então termine forte![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_yusu [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4076 65535 0]Entendo... mas é isso que torna a vida tão[n]interessante. Não tema, e deixe passar o[n]passado.[n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_yusuke [Yusuke]]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 4073 65535 0]Isso não deveria acontecer![n]Como eu poderia falhar...? Me perdoe.[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_4 [Yusuke]]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 4119 65535 0]Temos a oportunidade de terminar aqui![n]HRM... minha mão está tremendo...!?[n][f 1 3 65535][w][e]

[sel SEL_Finish_yusuke top]
[s]Finja que você está pintando.[e]
[s]É um terremoto?[e]
[s]Está tremendo de emoção.[e]

[msg MSG_Finish_Act01_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4131 65535 0]Você tem razão. Pintar é sobre estar no[n]momento! Sim... eu posso fazer isso agora![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_yusuke [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4134 65535 0]...Tu podes estar certo. Heh.[n]O tremor se acalmou um pouco.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_yusuke [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 4139 65535 0]O que? Mas, o prédio não está tremendo...[n]Não, são apenas meus dedos que tremem...![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_4 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4190 65535 0]Um 0 perfeito... e um sucesso perfeito.[n]A deusa da vitória sorriu sobre nós![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Que sessão estimulante de paixão por nós[n]dois! Estou de bom humor![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_y [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4190 65535 0]Um 0 perfeito... e um sucesso perfeito.[n]A deusa da vitória sorriu sobre nós![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_yu [Yusuke]]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 4047 65535 0][var 0]Restante... NGH, chegamos perto. Ficamos um[n]pouco aquém da nossa determinação?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_4 [Yusuke]]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 4047 65535 0][var 0]Pontos restantes...[n]Que resultado abismal. Parece que subestimei[n]os meandros dos dardos.[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53736 65535 0]A sensação de arremessar dardos...[n]Eu não gosto disso.[n][f 1 3 65535][w][e]

[msg MSG_DartsBye_yusuke [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Agora então, adeus.[n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_makoto [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2019 65535 0]Ei, [f 4 2], podemos ir primeiro?[n]Eu gostaria de testar essa técnica que[n]pensei.[n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_makoto [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2057 65535 0]Hum... eu poderia ir a seguir? Eu tenho[n]estudado a teoria sobre como jogar dardos.[n][f 1 3 65535][w][e]

[msg MSG_NextRetry_makoto [Makoto]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 2129 65535 0]Para ser sincero... não posso aceitar esse[n]resultado.[n]Você acha que poderíamos jogar mais um jogo?[n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_makoto [Makoto]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 2063 65535 0]...Tudo bem então.[n]Isso é um pouco decepcionante.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Vamos tocar em outra hora. Vou executar as[n]simulações na minha cabeça até então.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_makoto [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Vamos tentar 301. É melhor começar com o[n]básico, não?[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_makoto [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Vamos tentar 501. Quanto maior o desafio,[n]maior a chance de crescer.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_makoto [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hmm... qual conjunto de regras devemos[n]usar...?[n]Desculpe, eu poderia pedir que você decida?[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_makot [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tudo bem então.[var 0]isso é.[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_makoto [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2108 65535 0]Boa sorte. Enquanto você permanecer calmo,[n]você deve ficar bem![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_makoto [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2165 65535 0]É a minha vez...![n]Agora, se eu apenas fizer isso como as[n]simulações...[n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_makoto [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2114 65535 0]Já é a Rodada 3... certifique-se de[n]permanecer focado![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_makoto [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2064 65535 0]Então esta é a minha última rodada... eu[n]preciso jogar sem pensar demais...![n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_makoto [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2053 65535 0]Você é nossa única esperança agora. Boa[n]sorte na rodada final![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_mako [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 2199 65535 0]Parece que sua mão escorregou...[n]Está tudo bem. Não deixe isso chegar até[n]você.[n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_makoto [Makoto]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 2178 65535 0]O que...!? Como isso pôde acontecer...?[n]Eu sinto muito.[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_5 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2188 65535 0]Oh... poderíamos terminar aqui.[n]Eu-eu tenho que lembrar das simulações...[n][f 1 3 65535][w][e]

[sel SEL_Finish_makoto top]
[s]Que simulações?[e]
[s]Apenas vá com calma.[e]
[s]Respire fundo.[e]

[msg MSG_Finish_Act01_makoto [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2135 65535 0]Oh, certo... respiração controlada![n]Sim... eu me sinto muito mais calmo![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_makoto [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2165 65535 0]...Você tem razão. Eu preciso relaxar. Ok,[n]eu vou dar o meu melhor.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_makoto [Makoto]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 2170 65535 0]Oh, umm... eu... tenho que explicar isso[n]agora?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_5 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2162 65535 0]0 pontos! Conseguimos![n]Fazemos um excelente par, não é?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu vejo... os efeitos positivos da sinergia[n]entre duas pessoas produzem resultados[n]inesperadamente fortes...![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_m_2 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2162 65535 0]0 pontos! Conseguimos![n]Fazemos um excelente par, não é?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_ma [Makoto]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 2028 65535 0]Tivemos [var 0]Esquerda... isso é muito difícil.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_5 [Makoto]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 2021 65535 0]Tivemos [var 0]Esquerda... isso não é bom.[n]Sinto muito, eu deveria ter tentado mais.[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_makoto [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53335 65535 0]Foi divertido. Gosto de melhorar[n]gradualmente meu formulário a cada lance.[n][f 1 3 65535][w][e]

[msg MSG_DartsBye_makoto [Makoto]]
[s][vp 8 2 0 2053 65535 0]Até logo.[n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9155 65535 0]Tudo bem [f 4 2], vamos jogar![n]Hehehe... o jogador em mim está ansioso para[n]ir![n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9055 65535 0]Yo! Eu ligo para a próxima! Vamos lá, posso[n]ir?[n][f 1 3 65535][w][e]

[msg MSG_NextRetry_futaba [Futaba]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 9043 65535 0]Estou fortemente oposto a esse resultado![n]Solicitando uma tentativa![n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_futaba [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 9040 65535 0]Então chegou a isso... então, chegou a[n]isso...![n][f 1 3 65535][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]OK tudo bem. Mas estamos voltando aqui em[n]breve![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Tem que ser 301. Trezentos e um![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras: deve ser 501.[n]Parece mais gratificante esclarecer uma[n]dificuldade mais difícil![n][f 1 3 65535][w][e]

[msg MSG_CourseFree_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hrrm... que regras para ir...[n]Ok, você escolhe![n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_futab [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Afirmativo! Estamos indo [var 0]então![n][f 1 3 65535][w][e]

[msg MSG_StartRound01_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9177 65535 0]Não se preocupe. Onde há vontade, há um[n]caminho![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9089 65535 0]Heh, eu vou acertar isso, sem problemas![n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9076 65535 0]Tudo aquecido agora? Você só precisa ir[n]Fwoosh e depois Bam![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_futaba [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 9189 65535 0]Minha última rodada... Th-Things está[n]ficando interessante, como eles dizem...![n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54738 65535 0]Não entre em pânico agora! Apenas acredite[n]em si mesmo e jogue![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_futa [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54743 65535 0]Não desista ainda! Lembre-se de quão longe[n]você chegou![n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_futaba [Futaba]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 54741 65535 0]Eu calculei mal...! Por favor me perdoe...[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_6 [Futaba]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 9029 65535 0]Esta é minha chance de terminar...[n]A-am eu realmente ficando nervoso!?[n][f 1 3 65535][w][e]

[sel SEL_Finish_futaba top]
[s]O alvo é uma abóbora.[e]
[s]Isso é real.[e]
[s]Quer mudar?[e]

[msg MSG_Finish_Act01_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9135 65535 0]Esse sentimento de tensão... é totalmente[n]real! Sim! Eu vou milhar![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_futaba [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 9030 65535 0]Ei, não podemos fazer isso... heh, você pode[n]ter pena![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_futaba [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 9040 65535 0]Você faz parecer tão simples...[n]Além disso, parece mais uma pizza![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_6 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9105 65535 0]Woohoo! 0 pontos! Ninguém pode melhor nós![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Nós atacamos o campo de batalha juntos...[n]Vou brincar com um refrigerante mais tarde![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_f [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9105 65535 0]Woohoo! 0 pontos! Ninguém pode melhor nós![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_fu [Futaba]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 9043 65535 0][var 0]restante...? Estávamos tão perto de[n]terminar...![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_6 [Futaba]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 9043 65535 0][var 0]Pontos restantes...?[n]Isso é deprimente.[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54737 65535 0]Eu me sinto como um ninja! Isto é divertido![n][f 1 3 65535][w][e]

[msg MSG_DartsBye_futaba [Futaba]]
[s][vp 8 2 0 9012 65535 0]Hora de fazer como uma árvore![n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3057 65535 0]Hum...[f 4 2]-kun, você se importaria de brincar comigo?[n]Eu apreciaria se você pudesse me mostrar o[n]que fazer.[n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3057 65535 0]Ok... é a minha vez a seguir. Vamos fazer o[n]nosso melhor.[n][f 1 3 65535][w][e]

[msg MSG_NextRetry_haru [Haru]]
[s][bup 0 7 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 3110 65535 0]Hmm... poderíamos jogar mais um?[n]Eu não quero que termine assim![n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_haru [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3047 65535 0]Oh sério?[n]Hmm... isso é tão lamentável.[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Mas, bem. Vamos jogar outra vez![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Vamos com 301. Eu posso lidar com isso...[n]Eu penso.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Vamos com 501. Estou um pouco nervoso, mas[n]deve ser divertido, certo?[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Umm... que conjunto de regras devemos usar...[n]Sinto muito, mas você poderia decidir por[n]nós?[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ok! Nós vamos jogar [var 0]então.[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53522 65535 0]Boa sorte! O importante é se divertir![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53501 65535 0]Aqui vou eu! Vou fazer o meu melhor...![n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3048 65535 0]É a terceira rodada! Eu tenho um bom[n]pressentimento sobre isso![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_haru [Haru]]
[s][bup 0 7 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 3178 65535 0]Então este é o meu último turno... eu posso[n]fazer isso![n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3119 65535 0]É a rodada final! Estou tão nervoso...![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_haru [Haru]]
[s][bup 0 7 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 3118 65535 0]Não se preocupe com isso, ok?[n]Você quase teve![n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_haru [Haru]]
[s][bup 0 7 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 3027 65535 0]Wha...? Eu sinto Muito...[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_7 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 3180 65535 0]Olhe para a nossa pontuação... podemos[n]terminar! Como devo jogar!?[n][f 1 3 65535][w][e]

[sel SEL_Finish_haru top]
[s]Com elegância.[e]
[s]Como se você estivesse balançando um machado.[e]
[s]Divirta-se com isso.[e]

[msg MSG_Finish_Act01_haru [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 53531 65535 0]...Está certo! Eu me sinto meio animado[n]agora![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_haru [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3135 65535 0]Elegância...? Oh, você quer dizer apenas[n]jogar naturalmente! Ok, seja eu mesmo...[n]seja eu mesmo![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_haru [Haru]]
[s][bup 0 7 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 3196 65535 0]Huh!? Isso tem algo a ver com dardos?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_7 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3104 65535 0]Veja! 0 pontos! Uau...[n]Eu me sinto tão realizado![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Somos o melhor par de todos os tempos...[n]talvez?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_h [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3104 65535 0]Veja! 0 pontos! Uau...[n]Eu me sinto tão realizado![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_ha [Haru]]
[s][bup 0 7 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 3028 65535 0][var 0]Saiu... nós não conseguimos.[n]Eu me pergunto o que deu errado...[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_7 [Haru]]
[s][bup 0 7 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 3111 65535 0][var 0]Pontos restantes...[n]Nós não conseguimos. Foi minha culpa por[n]estar muito nervoso...?[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53539 65535 0]Ele Ele! Foi tão divertido brincar com[n]todos! Eu nem percebi como eu estava![n][f 1 3 65535][w][e]

[msg MSG_DartsBye_haru [Haru]]
[s][vp 8 2 0 3054 65535 0]Bem, adeus por enquanto![n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]Ok então, vamos? Estou todo preparado do meu[n]lado.[n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8018 65535 0]Você se importaria se eu tivesse o próximo[n]jogo?[n][f 1 3 65535][w][e]

[msg MSG_NextRetry_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8038 65535 0]... Vamos fazer mais um.[n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8028 65535 0]Realmente agora... bem, tudo bem.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras... vamos jogar 301.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras... vamos jogar 501.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Qual conjunto de regras devemos usar...?[n]Tudo bem, vou deixar para você.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_akech [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tudo bem, vamos jogar 701. Eu acredito que[n]você não tem problemas com isso?[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8128 65535 0]Você pode ir primeiro.[n][f 1 3 65535][w][e]

[msg MSG_StartRound02_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54447 65535 0]Então, eu estou bem.[n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Agora é sua vez. As coisas estão ficando[n]interessantes.[n][f 1 3 65535][w][e]

[msg MSG_StartRound04_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]Então esta será minha rodada final...[n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8153 65535 0]Bem, tudo depende de você agora. Boa sorte[n]para você.[n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_akec [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8047 65535 0]... isso é lamentável. Não deixe isso te[n]incomodar.[n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_akechi [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 8044 65535 0]... Parece que estou um pouco fora do meu[n]jogo.[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8128 65535 0]Tudo bem, hora de terminar isso. Oh, você[n]tem algumas palavras de encorajamento para[n]mim?[n][f 1 3 65535][w][e]

[sel SEL_Finish_akechi top]
[s]Estou torcendo por dentro.[e]
[s]Você não precisa de nenhum.[e]
[s]Vá, vá, Goro-Saaan![e]

[msg MSG_Finish_Act01_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8048 65535 0]*risada* Isso é um desafio? Muito bem,[n]responderei às suas expectativas elevadas.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8108 65535 0]Eu agradeço. Eu costumo me distrair se[n]estiver muito alto.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54411 65535 0]Oh, claro... obrigado.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8162 65535 0]Isso é um acabamento em 0 pontos.[n]Jogar dardos em um par não é tão ruim.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Me mata admitir... mas isso foi um pouco[n]emocionante. Bem, não é um sentimento ruim.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_a_2 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8162 65535 0]Isso é um acabamento em 0 pontos.[n]Jogar dardos em um par não é tão ruim.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_ak [Akechi]]
[s][bup 0 9 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 8038 65535 0][var 0]Saí... nós chegamos um pouco curtos.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_8 [Akechi]]
[s][bup 0 9 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 8038 65535 0][var 0]Pontos restantes... nós fomos curtos.[n]Eu me pergunto o que deu errado?[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54465 65535 0]Bem, isso foi bastante agradável.[n][f 1 3 65535][w][e]

[msg MSG_DartsBye_akechi [Akechi]]
[s][vp 8 2 0 8053 65535 0]Bem, então, vejo você mais tarde.[n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_akechiB [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54502 65535 0]Agora então, vamos começar. Estou pronto do[n]meu lado.[n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_akechi_2 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54502 65535 0]Eu vou a seguir. Parece bom?[n][f 1 3 65535][w][e]

[msg MSG_NextRetry_akechiBlac [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54473 65535 0]... estamos indo de novo. Você não pode[n]deixar isso acabar assim, pode?[n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_akechiBl [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54480 65535 0]O que... bem, tanto faz.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_akechi_2 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras... vamos com 301.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_akechi_2 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras... vamos com 501.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_akechiBla [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Qual conjunto de regras devemos usar...?[n]Tudo bem, vou deixar para você.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_akech_2 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Vamos jogar 701. Vai ser mais divertido[n]dessa maneira.[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_akechiB [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8128 65535 0]Você pode ir primeiro. Eu só vou assistir[n]por enquanto.[n][f 1 3 65535][w][e]

[msg MSG_StartRound02_akechiB [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Então é assim que você joga... hmph...[n]Assista e aprenda.[n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_akechiBl [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54489 65535 0]Você está acordado agora. É melhor você se[n]concentrar.[n][f 1 3 65535][w][e]

[msg MSG_StartRound04_akechiB [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54500 65535 0]Então, cheguei à minha rodada final.[n]Vou fazer isso sem problemas.[n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_akechiBl [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54473 65535 0]Esta é a última rodada. Sem pressa.[n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_akec_2 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54489 65535 0]Hmph... é melhor você não ter feito isso de[n]propósito.[n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_akechiBl [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54488 65535 0]... Não me olhe assim.[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_9 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]Hmm, parece que posso terminar aqui...[n]Agora, como jogar...[n][f 1 3 65535][w][e]

[sel SEL_Finish_akechiBlack top]
[s]Você decide.[e]
[s]Como um detetive?[e]
[s]Você tem que manter a calma.[e]

[msg MSG_Finish_Act01_akechiB [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54477 65535 0]Obviamente. Você nem precisou dizer isso.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_akechiB [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54499 65535 0]Eu não preciso que você me diga isso.[n]Estou sempre calmo.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_akechiB [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54474 65535 0]O que diabos isso significa até...[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_9 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54475 65535 0]Isso termina, 0 pontos.[n]Não é um resultado ruim.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto ao seu desempenho... bem, suponho que[n]você merece algum crédito.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_a_3 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54475 65535 0]Isso termina, 0 pontos.[n]Não é um resultado ruim.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_ak_2 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54489 65535 0][var 0]deixou? Hmph...[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_9 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54490 65535 0][var 0]Pontos restantes...[n]Hmph. Que resultado patético.[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_akechiBlac [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54501 65535 0]Bem, acho que isso serviu como uma boa[n]distração.[n][f 1 3 65535][w][e]

[msg MSG_DartsBye_akechiBlack [Akechi]]
[s][vp 8 2 0 54504 65535 0]Eu estarei indo então.[n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57033 65535 0][f 4 2]-senpai, podemos jogar juntos? Acho que vou[n]jogar mais reto se eu estiver em parceria[n]com você...![n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_sumire [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57142 65535 0]Eu poderia ir a seguir? Assistir as pessoas[n]tocarem realmente me motiva a participar.[n][f 1 3 65535][w][e]

[msg MSG_NextRetry_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57063 65535 0]...Eu sinto Muito! L-l-lt's Tente mais uma[n]vez![n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57061 65535 0]Eu-eu vejo...[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu entendo, no entanto. Vamos jogar na[n]próxima vez![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_sumire [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Devemos tentar 301? Eu acho que deveria ser[n]capaz de lidar com isso.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_sumire [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quanto às regras...[n]Devemos tentar 501? Se trabalharmos juntos,[n]eu sei que podemos limpar isso![n][f 1 3 65535][w][e]

[msg MSG_CourseFree_sumire [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ok, qual conjunto de regras devemos usar...?[n]Desculpe, eu poderia pedir que você escolha?[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_sumir [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ok! Então vamos tocar [var 0].[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57069 65535 0]Você consegue! Estou torcendo por você![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57002 65535 0]Rodada 2... então é a minha vez. Vou[n]precisar assistir meu formulário quando eu[n]jogar![n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57022 65535 0]Estamos apenas começando! Cuidado para não[n]perder o foco![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_sumire [Sumire]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 57064 65535 0]Esta é a minha última rodada! Eu tenho que[n]fazer isso contar...[n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57022 65535 0]Esta é a rodada final! Eu acredito em você,[n]senpai![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_sumi [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57163 65535 0]Está bem! Você acertou em espírito![n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57042 65535 0]Oh, o que aconteceu lá... me desculpe.[n]Meu objetivo parece estar errado...[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_10 [Sumire]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 57048 65535 0]Eu posso terminar...! Mas qual seria a[n]melhor maneira de jogar aqui?[n][f 1 3 65535][w][e]

[sel SEL_Finish_sumire top]
[s]Jogue como uma ginasta.[e]
[s]Não pense, apenas sinta.[e]
[s]Confie nos seus instintos.[e]

[msg MSG_Finish_Act01_sumire [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57116 65535 0]...Você tem razão! Eu só tenho que acreditar[n]em mim mesmo![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_sumire [Sumire]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 57119 65535 0]Okay...! Sinto... eu acho que posso fazer[n]isso![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_sumire [Sumire]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 57170 65535 0]Wha...!? Não, isso não faz sentido![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_10 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57052 65535 0]Senpai! Temos 0 pontos! Isso significa que[n]criamos uma excelente equipe!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]É porque estávamos perfeitamente[n]sincronizados...?[n]Eu me sinto tão motivado agora![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_s [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57052 65535 0]Senpai! Temos 0 pontos! Isso significa que[n]criamos uma excelente equipe!?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_su [Sumire]]
[s][bup 0 10 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 57055 65535 0][var 0]Esquerda... isso é lamentável.[n]Nós só precisávamos de um pouco mais...[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_10 [Sumire]]
[s][bup 0 10 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 57055 65535 0][var 0]Pontos restantes...[n]Isso é lamentável. E é tudo minha culpa...[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_sumire [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57162 65535 0]Muito obrigado. Eu me diverti muito![n][f 1 3 65535][w][e]

[msg MSG_DartsBye_sumire [Sumire]]
[s][vp 8 2 0 57071 65535 0]Espero que façamos isso de novo algum dia.[n][f 1 3 65535][w][e]

[msg MSG_Solo_playing_round01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1188 65535 0]Vamos, você entendeu! Foco![n][f 1 3 65535][w][e]

[msg MSG_Solo_playing_round02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1156 65535 0]Você está jogando sozinho, então não há[n]pressão. Basta jogar no seu próprio ritmo![n][f 1 3 65535][w][e]

[msg MSG_Solo_playing_round03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]Tudo bem, estamos no meio do caminho agora.[n]Três rodadas restantes. Continue![n][f 1 3 65535][w][e]

[msg MSG_Solo_playing_round04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1175 65535 0]Duas rodadas para ir! Você tem que fazer[n]este contar![n][f 1 3 65535][w][e]

[msg MSG_Solo_playing_round05 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 1106 65535 0]Na última rodada, hein... coloque tudo o que[n]você entrou nesses dardos![n][f 1 3 65535][w][e]

[msg MSG_Solo_playing_BustAft [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1182 65535 0]Isso foi um erro... mas você ainda tem uma[n]chance![n][f 1 3 65535][w][e]

[msg MSG_Solo_Clear [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 53140 65535 0]Terminado com 0 pontos! Eu sabia que voce[n]poderia fazer isso![n][f 1 3 65535][w][e]

[msg MSG_Solo_NotClear_ScoreF [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 53139 65535 0]Hmm, não conseguiu vencer, hein? E você[n]estava tão perto também...[n][f 1 3 65535][w][e]

[msg MSG_Solo_NotClear_ScoreB [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 53141 65535 0]Isso não acabou tão bem...[n]Mas não deixe isso te derrubar, tudo bem?[n][f 1 3 65535][w][e]

[msg MSG_Solo_ByeBye [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1049 65535 0]Ok, vamos voltar. Podemos repassar o que[n]aconteceu no trem![n][f 1 3 65535][w][e]

[msg MSG_Solo_StartScoreQ_1st [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1019 65535 0]Ah, sim, quantos pontos você quer começar?[n]Parece que existem algumas opções[n]diferentes.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]301, 501 ou 701... parece que a dificuldade[n]aumenta com o número, mas isso também pode[n]torná-los mais valiosos.[n][f 1 3 65535][w][e]

[msg MSG_Solo_StartScoreQ_com [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1019 65535 0]Oh, certo. Quantos pontos você vai começar[n]hoje?[n][f 1 3 65535][w][e]

[msg MSG_Solo_StartScore_301 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1023 65535 0]Ah, 301, hein?[n]Deveríamos ser capazes de pegar este, fácil![n][f 1 3 65535][w][e]

[msg MSG_Solo_StartScore_501 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1035 65535 0]Oh, 501, hein?[n]Isso deveria ser um desafio decente.[n][f 1 3 65535][w][e]

[msg MSG_Solo_StartScore_701 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 1164 65535 0]Uau, você está começando em 701?[n]Farei o meu melhor para animá-lo![n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7048 65535 0]Você vai sentir falta se tensidade assim.[n]Apenas relaxe![n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1181 65535 0]Vocês são muito bons. Estou impressionado.[n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6023 65535 0]Você é todo tão bom! É melhor eu não ficar[n]para trás![n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Yusuk [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0]É necessária precisão, até a ponta dos[n]dedos... que profundidade este jogo tem.[n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Makot [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2048 65535 0]Isso é bastante desafiador...[n]Isso me faz querer dominá-lo.[n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Futab [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9196 65535 0]This essa atmosfera... vamos, eu, eu entendi![n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3048 65535 0]Ele Ele! Vocês são todos tão habilidosos.[n]É melhor eu continuar também.[n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Akech [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0]Não utilizado.[n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Yoshi [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57058 65535 0]Que atmosfera madura... isso é divertido![n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7045 65535 0]Faça! Estamos torcendo por você![n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1045 65535 0]Fique calmo! Não há nada que não possamos[n]fazer![n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6023 65535 0]Boa sorte! Você consegue![n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4045 65535 0]Agora então, como isso vai acabar...?[n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Makoto [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2048 65535 0]Fique calmo! Concentre-se no seu[n]posicionamento.[n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9196 65535 0]Faça! Mostre-nos o que você tem![n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3119 65535 0]Você está bem! Eu sei que você pode fazer[n]isso![n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8035 65535 0]Boa sorte.[n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Yoshiz [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57026 65535 0]Vá em frente! É tudo sobre coração![n][f 1 3 65535][w][e]

[msg MND_chr_haiti]
[s][vp 8 2 0 0 65535 0]Quantos amigos devo trazer?[n][f 1 3 65535][w][e]

[sel SEL_chr_haiti_dbg top]
[s]Up to Ann (Default).[e]
[s]Até Yusuke.[e]
[s]Até Makoto.[e]
[s]Até Futaba.[e]
[s]Até Haru.[e]
[s]Até Akechi.[e]
[s]Até Sumire.[e]
[s]Comece como está.[e]

[msg MND_InviteAndPosSet]
[s][vp 8 2 0 0 65535 0]Quem foi chamado?[n][f 1 3 65535][w][e]

[sel SEL_InviteAndPosSet top]
[s]Configurações de força [e]
[s]Fazer nada [e]

[sel SELGEN_InviteAndPosSet top]
[s]Ryuji foi chamado.[e]
[s]Morgana foi chamado.[e]
[s]Ann foi chamada.[e]
[s]Yusuke foi chamado.[e]
[s]Makoto foi chamado.[e]
[s]Haru foi chamado.[e]
[s]Futaba foi chamado.[e]
[s]Akechi foi chamado.[e]
[s]Sumire foi chamado.[e]
[s]Jogar sozinho.[e]

[msg MSG_DUMMY]
[s][vp 8 2 0 0 65535 0]Teste [n][f 1 3 65535][w][e]

[msg MSG_DUMMY01]
[s][vp 8 2 0 0 65535 0]Para uma revanche, selecione se você jogar[n]com a segunda pessoa e em que modo jogar.[n][f 1 3 65535][w][e]

[msg MSG_DUMMY02]
[s][vp 8 2 0 0 65535 0]Se você tiver uma classificação máxima com a[n]outra pessoa, escolha o modo neste momento.[n][f 1 3 65535][w][e]

[msg MSG_DUMMY03]
[s][vp 8 2 0 0 65535 0]Atualize a pontuação na tela.[n][f 1 3 65535][w][e]

[msg MSG_DUMMY04]
[s][vp 8 2 0 0 65535 0]Switch Display para "Modo Selecione Status".[n][f 1 3 65535][w][e]

[msg MSG_DUMMY05]
[s][vp 8 2 0 0 65535 0]Defina a posição do parceiro no balcão.[n][f 1 3 65535][w][e]

[msg MSG_DUMMY06]
[s][vp 8 2 0 0 65535 0]Alterne o modo de exibição para "status do[n]jogo" [n][f 1 3 65535][w][e]

[msg MSG_DUMMY07]
[s][vp 8 2 0 0 65535 0]Teste de modo de acabamento [n][f 1 3 65535][w][e]
[s]Quando os pontos restantes estiverem abaixo[n]de 60, ative conversas para acabamento.[n][f 1 3 65535][w][e]

[msg MSG_DUMMY_ScoreSet]
[s][vp 8 2 0 0 65535 0]Defina a pontuação inicial para este jogo.[n][f 1 3 65535][w][e]

[msg MSG_DUMMY_ChallengeScore]
[s][vp 8 2 0 0 65535 0]A pontuação do desafio para o jogo 1 é [var 0].[n][f 1 3 65535][w][e]

[msg MSG_DUMMY_ChallengeScore_2]
[s][vp 8 2 0 0 65535 0]A pontuação do desafio para o jogo 2 é [var 0].[n][f 1 3 65535][w][e]

[msg MSG_DUMMY_ChallengeScore_3]
[s][vp 8 2 0 0 65535 0]A pontuação do desafio para o jogo 3 é [var 0].[n][f 1 3 65535][w][e]

[msg MSG_DBG_DebugMsgOpen]
[s][vp 8 2 0 0 65535 0]Exibir mensagens de depuração?[n][f 1 3 65535][w][e]

[sel SEL_DBG_MsgOpen top]
[s]Não [e]
[s]Sim [e]

[msg MSG_DBG_ChallengeScore]
[s][vp 8 2 0 0 65535 0]A pontuação do desafio calculada desta vez é [var 10][n][f 1 3 65535][w][e]

