[msg dummy_mes]
[s]......[n][w][e]

[msg D10_02_HINT_mes01 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não vejo outras entradas...[n][w][e]
[s]Devemos considerar[n][clr 2]outros caminhos além das portas[clr 27],[n]como o telhado ou as chaminés...[n][w][e]

[msg D10_02_e484_080_mes01 [Voce di Kasumi]]
[s][vp 1 0 0 1 0 0]Quem está aí?[n][w][e]

[msg D10_02_e484_080_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Foi Yoshizawa!?![n][w][e]

[sel D10_02_e484_080_SEL top]
[s]Vamos.[e]
[s]Parece que está ficando ruim.[e]

[msg D10_02_e484_080_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Sim, mas cuidado![n][w][e]

[msg D10_02_IN_mes01 [[f 4 31 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este é o mesmo lugar do ano passado, não é?[n][w][e]

[msg D10_02_promnadedoor_mes_ [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Foi aqui que aconteceu.[n][w][e]

[msg D10_02_promnadedoor_mes__2 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A prova está fechada,[n]mas o auditório está aberto...[n][w][e]

[msg D10_02_promnadedoor_mes__3 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8155 65535 0]De acordo com o mapa, o auditório[n]fica atrás daquela porta…[n][w][e]

[msg D10_02_promnadedoor_mes__4 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Depois entramos pela porta da esquerda[n]e seguimos sempre em frente.[n][w][e]

[msg D10_02_promnadedoor_mes__5 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eles estão se esforçando para nos dizer que está[n]aberto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8099 65535 0]Maruki deve estar esperando por nós lá.[n]Vamos ver.[n][w][e]

[msg D10_02_to_promnadedoor_l [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Essa deve ser a porta.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8135 65535 0]Aparentemente, o hall de entrada[n]está no centro de várias estradas[n]que levam ao exterior.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos.[n][w][e]

[msg D10_PaleceChangedReactio [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Tem muita multidão...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]É definitivamente tudo diferente da última[n]vez.[n][w][e]

[msg D10_PaleceChangedReactio_2 [Annuncio educato]]
[s]Obrigado por terem vindo,[n]pacientes.[n][w][e]
[s]Você será conduzido a uma de nossas instalações[n]de cuidados especializados de acordo com suas[n]necessidades pessoais.[n][w][e]

[msg D10_PaleceChangedReactio_3 [Annuncio educato]]
[s]Nós vamos ajudar cada um de vocês.[n][w][e]
[s]Não se preocupe. Todos podem ser[n]felizes.[n][w][e]

[msg D10_PaleceChangedReactio_4 [Annuncio educato]]
[s]Se você tiver alguma dúvida sobre as instalações,[n]pergunte a um funcionário próximo.[n][w][e]

[msg D10_PaleceChangedReactio_5 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57113 65535 0]Que anúncio estranho.[n]"Tornar-se feliz"?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Que tipo de lugar é este?[n][w][e]

[msg D10_02_AuditoriumGuide_m [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Acho que foi por aqui.[n][w][e]

[msg D10_02_AuditoriumGuide_m_2 [Annuncio educato]]
[s]Pacientes VIP identificados.[n]Vamos agora começar a visita.[n][w][e]

[msg D10_02_AuditoriumGuide_m_3 [Annuncio educato]]
[s]O Auditório já está aberto.[n][w][e]
[s]O mestre espera por você lá... com[n]o paciente que você procura.[n][w][e]

[msg D10_02_AuditoriumGuide_m_4 [Annuncio educato]]
[s]Por favor, entre pela porta[n]no lado esquerdo do hall de entrada.[n][w][e]

[msg D10_02_AuditoriumGuide_m_5 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Como eu pensava. Ele nos informa educadamente[n]sobre a localização deles.[n][w][e]

[msg D10_02_AuditoriumGuide_m_6 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Essa deve ser a porta.[n]Vamos.[n][w][e]

[msg D10_02_sumireReaction_me [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Comparado com a última vez[n]há algo diferente...[n][w][e]

[msg D10_02_sumireReaction_me_2 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]Isso foi há alguns meses, certo? Deveria[n]ter havido um despertar do coração desde então.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você se lembra quanto tempo se passou desde a[n]última vez que você esteve aqui?[n][w][e]

[msg D10_02_sumireReaction_me_3 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Acho que foi atrás daquela porta.[n]Foi onde ele me ajudou.[n][w][e]

[msg D10_02_sumireReaction_me_4 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu entendo, então você só conhece a área perto da[n]entrada.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8099 65535 0]Vamos continuar.[n][w][e]

[msg D10_02_posterSession_1st [[f 4 31 10 0]]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57135 65535 0]O que isso significa? Eu não entendo[n]uma única palavra disso...[n][w][e]

[msg D10_02_posterSession_1st_2 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece um relatório de pesquisa.[n][w][e]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aposto que você pode[n]decifrá-lo, Joker![n][w][e]

[msg D10_02_posterSession_1st_3 [[f 4 31 10 0]]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57037 65535 0]Estranho. Este pôster está fora de[n]lugar... E por que o Palácio[n]está cheio de gente?[n][w][e]

[msg D10_02_posterSession_1st_4 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Essas pessoas existem apenas no[n]conhecimento do senhor do Palácio.[n]Eles são como bonecos, digamos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas ainda não sabemos como[n]o senhor percebe as coisas que[n]o fariam aparecer.[n][w][e]

[msg D10_02_posterSession_1st_5 [[f 4 31 10 0]]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57119 65535 0]Bonecas, né? Eu nunca[n]teria dito isso. Eles parecem reais.[n][w][e]

[msg D10_02_posterSession_1st_6 [Akechi]]
[s][bup 0 9 802 0 0][vp 8 2 1 54502 65535 0]......[n][w][e]

[msg D10_02_posterSession_1st_7 [[f 4 31 10 0]]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Akechi-san?[n][w][e]

[msg D10_02_posterSession_1st_8 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8099 65535 0]...Nada. E como é inútil ficar aqui, devemos ir.[n][w][e]

[msg D10_02_posterSession_2nd [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Tem todos os ares de uma pesquisa sobre[n]ciência psi-cognitiva.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Maruki parece muito[n]interessado no assunto...[n][w][e]

[msg D10_02_posterSession_3rd [Ryuji]]
[s][bup 0 2 3 65535 0][vp 8 2 1 7085 65535 0]......[n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ei Pantera, isso soa um sino para você?[n][w][e]

[msg D10_02_posterSession_3rd_2 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nao nem um pouco.[n][w][e]

[msg D10_02_posterSession_3rd_3 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7028 65535 0]O mesmo vale para mim.[n][w][e]

[msg D10_02_posterSession_3rd_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4156 65535 0]O público que toma conhecimento da sua[n]pesquisa... Em que se baseia esse conhecimento?[n][w][e]

[msg D10_02_posterSession_3rd_5 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Suas descobertas ainda não estão totalmente[n]prontas para o mundo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ele parece quase convencido de que a massa[n]deve ter acesso à sua[n]pesquisa.[n][w][e]

[msg D10_02_posterSession_3rd_6 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9021 65535 0]Parecem informações genéricas,[n]para pessoas comuns. Isso seria pouco[n]mesmo para uma competição de ciências.[n][w][e]

[msg D10_02_posterSession_3rd_7 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bem, eu não entendo uma palavra.[n]Ele deveria ter escrito[n]em hiragana...[n][w][e]

[msg D10_02_posterSession_3rd_8 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3192 65535 0]Eu não acho que tornou[n]mais compreensível.[n][w][e]

