[msg dummy_mes]
[s]......[n][w][e]

[msg SCN_LOCK_06_mes01]
[s]Não parece que vai abrir...[n][w][e]

[msg SCN_LOCK_06_mes02 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não é bom de novo...[n][w][e]

[msg SCN_LOCK_06_mes03 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Isso significa que ainda existem pessoas que[n]não nos aceitam?[n][w][e]

[msg SCN_LOCK_06_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não se preocupe. Enquanto permanecermos[n]ativos, será aberto eventualmente.[n][w][e]

[msg SCN_LOCK_06_mes05 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nós apenas teremos que ser pacientes até que[n]isso realmente aconteça.[n][w][e]

[msg SCN_LOCK_CLEAR_06_mes01 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, isso se abriu...[n][w][e]

[msg SCN_LOCK_CLEAR_06_mes02 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Olhando para isso em uma escala maior, esta[n]é a área de cinquenta segundos, sim? Eu me[n]pergunto quantos restam...[n][w][e]

[msg SCN_LOCK_CLEAR_06_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nós apenas teremos que descobrir com nossos[n]próprios olhos! Vamos![n][w][e]

