[msg Dummy]
[s]......[n][w][e]

[msg D03_07_BUTA_01_KICKBACK_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Eu sei que já vimos isso antes no[n]Palácio, mas caramba, é horrível.[n][w][e]

[msg D03_07_BUTA_01_KICKBACK__2 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6025 65535 0]Quero dizer, é um cofrinho dourado. Parece óbvio[n]para mim que ele não pensa em nada além de[n]dinheiro.[n][w][e]

[msg D03_07_SHUTTER_STOPPER_0 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Mmm, parece que não quer abrir.[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se pesquisarmos bastante, devemos[n]encontrar os comandos.[n][w][e]

[msg D03_07_SHUTTER_OPEN01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]Talvez tenhamos encontrado os comandos que[n]estávamos procurando. Podemos fazer[n]alguma coisa aqui?[n][w][e]

[msg D03_07_SHUTTER_OPEN02 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6045 65535 0]Ver! A veneziana sumiu.[n]Podemos continuar![n][w][e]

[msg D03_07_SHUTTER_OPEN03 [Palestrante]]
[s]Chamando todos os guardas![n]Chamando todos os guardas![n][w][e]

[msg D03_07_SHUTTER_OPEN04 [Palestrante]]
[s]Os ratos conseguiram subir até o último andar![n]Fortaleça a segurança em todos os níveis![n][w][e]
[s]Eles não devem ir mais longe![n]Proteja o porquinho dourado[n]não importa o quê![n][w][e]

[msg D03_07_SHUTTER_OPEN05 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1025 65535 0]Inferno, deve ser realmente[n]difícil ...[n][w][e]

[msg D03_07_SHUTTER_OPEN06 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ele teme mais do que tudo que[n]coloquemos nossas mãos neste[n]"porquinho de ouro".[n][w][e]

[msg D03_07_SHUTTER_OPEN07 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7161 65535 0]Bem, acho que realmente se refere a[n]aquilo ali. É um tanto[n]suspeito, na minha opinião...[n][w][e]

[msg mini_EV_e259_502_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]Hum? Aqui está uma nota.[n]Diz "[clr 2]P=I[clr 27]".[n][w][e]

[msg mini_EV_e259_502_mes02 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E o que diabos isso significa?[n][w][e]

[msg mini_EV_e259_502_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espere um momento, a borda está rasgada.[n]É do diário de Kaneshiro?[n][w][e]

[msg mini_EV_e259_502_mes04 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1045 65535 0]Então é a próxima parte[n]do código anterior![n]Isso deve nos ajudar![n][w][e]

[msg mini_EV_e259_502_mes07 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]Hum? Aqui está uma nota.[n]Quem sabe se é uma pista[n]para descobrir o código PIN.[n][w][e]

[msg mini_EV_e259_502_mes08 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas tenho certeza que já descobrimos.[n][w][e]

[msg mini_EV_e259_502_mes09 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1048 65535 0]Então resolvemos sem[n]todas as pistas. Bom demais![n][w][e]

[msg mini_EV_e259_502_01_mes0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]Hum? Aqui está uma nota.[n]Diz "[clr 2]E=9 A=3[clr 27]".[n][w][e]

[msg mini_EV_e259_502_01_mes0_2 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece com o que encontramos antes. Isso também[n]tem uma borda desgastada.[n][w][e]

[msg mini_EV_e259_502_01_mes0_3 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1045 65535 0]Perfeito! Quanto mais pistas encontrarmos,[n]mais perto chegaremos de descobrir[n]o código.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos, vamos correr para o[n]carro para inseri-lo![n][w][e]

[msg mini_EV_e259_502_01_mes0_4 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6165 65535 0]Isso é meio que uma nota, não é?[n]Você acha que é uma pista?[n][w][e]

[msg mini_EV_e259_502_01_mes0_5 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4191 65535 0]Já descobrimos o PIN.[n]Encontramos isso[n]um pouco tarde.[n][w][e]

