[sel YESNO_SEL top]
[s]Sim[e]
[s]Não[e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]No momento você não tem nada para fazer aqui,[n]certo? Vamos lá, vamos outro lugar![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]O que você tem? Vamos,[n]temos que dizer olá para os outros![n][w][e]

[msg MSG_LAST_GREETING_Roof [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Oh, está fechado... Não deveríamos[n]ir para outro lugar?[n][w][e]

[msg MSG_ROOF_MAKOTO_NG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Parece bloqueado.[n][w][e]

[msg MSG_ROOF_HARU_NG [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Ah... está fechado. Acho que sem[n]Haru não podemos entrar.[n][w][e]

[msg MSG_STUDENT_COUNCIL_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Ei, você não tem motivo para entrar na sala do[n]conselho estudantil, não é?[n][w][e]

[msg MSG_STUDENT_COUNCIL]
[s][vp 1 0 0 0 0 0]Esta é a[n]sala do conselho estudantil.[n][w][e]
[s][vp 1 0 0 0 0 0]As cadeiras internas são[n]arranjadas em perfeita ordem...[n][w][e]

[msg CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]O banheiro cheira um pouco a mofo...[n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Você não sabe que é o banheiro das[n]mulheres?[n]Você não deveria entrar lá...[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]Não tenho motivos para[n]entrar no banheiro feminino...[n][w][e]

[msg MSG_Board_AfterKamo [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]"Não faça declarações[n]fora da escola"?[n]Mas todo mundo já está falando sobre isso...[n][w][e]

[msg MSG_BOARD_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]"Shujin[n]Código de Conduta da Academia". Ugh, isso é[n]muito específico...[n][w][e]

[msg MSG_BOARD]
[s][vp 1 0 0 0 0 0]Este quadro de avisos está cheio de[n]folhetos do clube e[n]mensagens do conselho estudantil...[n][w][e]

[msg MSG_RADIO_STUDIO_MORU [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Oooh, a sala de transmissão... Talvez[n]você devesse entrar sorrateiramente e[n]aparecer na escola![n][w][e]

[msg MSG_RADIO_STUDIO]
[s][vp 1 0 0 0 0 0]Os alunos na sala de transmissão[n]estão colocando os CDs em ordem...[n][w][e]

[msg MSG_GRADE1_CLASS_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]...Esta é uma sala de aula do primeiro ano.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Você não conhece ninguém aqui, não é? Não devemos[n]entrar sem qualquer motivo.[n][w][e]

[msg MSG_GRADE1_CLASS]
[s][vp 1 0 0 0 0 0]Esta é uma sala de aula do primeiro ano.[n][w][e]
[s][vp 1 0 0 0 0 0]Os alunos parecem se perguntar[n]por que você está aqui. Talvez eu devesse[n]ir para outro lugar...[n][w][e]

[msg MSG_Emergency_Door_m [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Ei, se você quiser sair, devemos[n]usar a entrada principal.[n][w][e]

[msg MSG_Emergency_Door]
[s][vp 1 0 0 0 0 0]Não tenho motivos para usar a saída de[n]emergência...[n][w][e]

[msg MND_BLDG_B_KEEPOUT_000_0]
[s][vp 1 0 0 0 0 0]Não preciso fazer nada[n]depois...[n][w][e]

[msg MSG_E13710100_NG_BldgA3F [Ryuji]]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]De lá você vai para as oficinas de construção.[n]Temos que chegar à sala da classe D.[n][w][e]

[msg MND_E13710100_NG_BldgA3F]
[s][vp 1 0 0 0 0 0]Eu deveria deixar o prédio do laboratório[n]para Ryuji...[n][w][e]

[msg MND_E12310100_GOTO_Rooft]
[s][vp 1 0 0 0 0 0]Há uma placa proibindo[n]a entrada, mas a porta[n]aparentemente está aberta...[n][w][e]

[msg MND_E12720100_NG_Rooftop]
[s][vp 1 0 0 0 0 0]No momento não tenho nada para fazer no telhado...[n][w][e]

[msg MSG_E13710100_NG_Rooftop [Ryuji]]
[s][bup 0 2 200 0 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]Acho que não vamos[n]encontrar ninguém do[n]time de vôlei lá em cima.[n][w][e]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Diz que a entrada é[n]proibida, então ninguém vai lá.[n][w][e]

[msg MND_E13710100_NG_Rooftop]
[s][vp 1 0 0 0 0 0]O telhado não é um lugar[n]muito movimentado. Vamos procurar[n]em outro lugar...[n][w][e]

[msg MND_E13710100_NG_Rooftop_2]
[s][vp 1 0 0 0 0 0]No momento não tenho nada para fazer no telhado...[n][w][e]

[msg MSG_E13910100_NG_Rooftop [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, eu disse a entrada principal! Se não nos[n]apressarmos, ele irá embora.[n][w][e]

[msg MND_E14130100_NG_Rooftop]
[s][vp 1 0 0 0 0 0]No momento não tenho nada para fazer no telhado...[n][w][e]

[msg MND_E14710100_NG_Rooftop]
[s][vp 1 0 0 0 0 0]Eu tenho que ir para o pátio imediatamente...[n][w][e]

[msg MSG_E23810100_NG_Rooftop [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Você não pode ir para o telhado.[n]Vamos para a[n]sala do conselho estudantil no terceiro andar.[n][w][e]

[msg MSG_E24320100_NG_Rooftop [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Você não pode ir para o telhado.[n]Vamos tentar em outro lugar.[n][w][e]

[msg MND_COMMON_NG_Rooftop_00]
[s][vp 1 0 0 0 0 0]Aqui eu não tenho que fazer nada[n]em particular, por enquanto...[n][w][e]

[msg MND_E12310100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]Na biblioteca tem[n]pessoas estudando[n]em silêncio geral...[n][w][e]

[msg MND_E12720100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]Na biblioteca tem[n]pessoas estudando[n]em silêncio geral...[n][w][e]

[msg MSG_E13710100_CHK_LIBRAR [Ryuji]]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 7161 65535 0]Ei, quer saber?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nesta biblioteca não tem[n]nem um mangá...[n][w][e]

[msg MND_E13710100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]Não vejo alunos na biblioteca...[n][w][e]

[msg MSG_E13910100_CHK_LIBRAR [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, eu disse a entrada principal! Se não nos[n]apressarmos, ele irá embora.[n][w][e]

[msg MND_E14130100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]Na biblioteca tem[n]pessoas estudando[n]em silêncio geral...[n][w][e]

[msg MND_E14710100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]Eu tenho que ir para o pátio imediatamente...[n][w][e]

[msg MSG_E23810100_CHK_LIBRAR [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Mais tarde. Você não tem que ir[n]para a sala do conselho estudantil[n]no terceiro andar?[n][w][e]

[msg MND_COMMON_CHK_LIBRARY_0]
[s][vp 1 0 0 0 0 0]Aqui eu não tenho que fazer nada[n]em particular, por enquanto...[n][w][e]

[msg MND_E12310100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]Esta é a[n]sala do conselho estudantil.[n][w][e]
[s][vp 1 0 0 0 0 0]As cadeiras internas são[n]arranjadas em perfeita ordem...[n][w][e]

[msg MND_E12720100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]Esta é a[n]sala do conselho estudantil.[n][w][e]
[s][vp 1 0 0 0 0 0]As cadeiras internas são[n]arranjadas em perfeita ordem...[n][w][e]

[msg MSG_E13710100_CHK_STUDEN [Ryuji]]
[s][bup 0 2 202 0 0][f 4 10 65535 0 0][vp 8 2 1 7156 65535 0]Não podemos contar com o[n]conselho estudantil.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eles só querem fazer[n]professores felizes.[n]Eles não se importam com mais nada.[n][w][e]

[msg MND_E13710100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]Esta é a[n]sala do conselho estudantil.[n][w][e]
[s][vp 1 0 0 0 0 0]As cadeiras internas são[n]arranjadas em perfeita ordem...[n][w][e]

[msg MSG_E13910100_CHK_STUDEN [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, eu disse a entrada principal! Se não nos[n]apressarmos, ele irá embora.[n][w][e]

[msg MND_E14130100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]Esta é a[n]sala do conselho estudantil.[n][w][e]
[s][vp 1 0 0 0 0 0]As cadeiras internas são[n]arranjadas em perfeita ordem...[n][w][e]

[msg MND_E14710100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]Eu tenho que ir para o pátio imediatamente...[n][w][e]

[msg MSG_E23810100_GOTO_STUDE [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1020 0 0]Esta é a[n]sala do conselho estudantil.[n][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Por que eles nos convocaram aqui?[n]Que estranho...[n][w][e]

[msg MND_COMMON_CHK_STUDENT_C]
[s][vp 1 0 0 0 0 0]Aqui eu não tenho que fazer nada[n]em particular...[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]O banheiro cheira um pouco a mofo...[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]O banheiro cheira um pouco a mofo...[n][w][e]

[msg MSG_E13710100_CHK_TOILET [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 7200 65535 0]Oh, eu estive segurando[n]ela por um longo tempo. Melhor[n]ir enquanto podemos![n][w][e]

[msg MSG_E13710100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 7028 65535 0]Fuuu...[n][w][e]

[msg MSG_E13710100_CHK_TOILET_3 [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 7045 65535 0]Bem, vamos continuar![n]Começaremos dando uma olhada[n]em sua turma.[n][w][e]

[msg MSG_E13710100_CHK_TOILET_4 [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Ele foge de novo?[n]Acabamos de ir lá.[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]O banheiro cheira um pouco a mofo...[n][w][e]

[msg MSG_E13910100_CHK_TOILET [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, eu disse a entrada principal! Se não nos[n]apressarmos, ele irá embora.[n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Por enquanto, vamos[n]para o pátio...[n][w][e]

[msg MND_E14710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Eu tenho que ir para o pátio imediatamente...[n][w][e]

[msg MSG_E23810100_GOTO_TOILE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1018 0 0]Você fará isso mais tarde. Você tem que ir[n]para a sala do conselho estudantil[n]no terceiro andar, certo?[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]O banheiro cheira um pouco a mofo...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Não tenho motivos para[n]entrar no banheiro feminino...[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Não tenho motivos para[n]entrar no banheiro feminino...[n][w][e]

[msg MSG_E13710100_CHK_TOILET_5 [Ryuji]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]Ei cara, você não pode entrar aí![n]Vamos nos apressar e ir[n]para sua aula![n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Não tenho motivos para[n]entrar no banheiro feminino...[n][w][e]

[msg MSG_E13910100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, o que você está fazendo?!?[n]Temos que nos apressar e[n]chegar a Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Não tenho motivos para[n]entrar no banheiro feminino...[n][w][e]

[msg MND_E14710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Eu tenho que ir para o pátio imediatamente...[n][w][e]

[msg MSG_E23810100_CHK_TOILET [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]Você não precisa de nada lá, não é? Não tem que[n]ir para a sala do conselho estudantil no[n]terceiro andar?[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]Não tenho motivos para[n]entrar no banheiro feminino...[n][w][e]

[msg MND_E12310100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Este quadro de avisos está cheio de[n]folhetos do clube e[n]mensagens do conselho estudantil...[n][w][e]

[msg MND_E12720100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Este quadro de avisos está cheio de[n]folhetos do clube e[n]mensagens do conselho estudantil...[n][w][e]

[msg MSG_E13710100_CHK_BOARD_ [Ryuji]]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]O que você está fazendo?[n]Venha, vamos[n]para sua aula![n][w][e]

[msg MND_E13710100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Este quadro de avisos está cheio de[n]folhetos do clube e[n]mensagens do conselho estudantil...[n][w][e]

[msg MSG_E13910100_CHK_BOARD_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, o que você está fazendo?!?[n]Temos que nos apressar e[n]chegar a Mishima![n][w][e]

[msg MND_E14130100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Este quadro de avisos está cheio de[n]folhetos do clube e[n]mensagens do conselho estudantil...[n][w][e]

[msg MND_E14710100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Eu tenho que ir para o pátio imediatamente...[n][w][e]

[msg MSG_E23810100_CHK_BOARD_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Há algum problema? Você está indo[n]para a sala do conselho estudantil[n]no terceiro andar, certo?[n][w][e]

[msg MND_COMMON_CHK_BOARD_000]
[s][vp 1 0 0 0 0 0]Este quadro de avisos está cheio de[n]folhetos do clube e[n]mensagens do conselho estudantil...[n][w][e]

[msg MND_E12310100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]Os alunos na sala de transmissão[n]estão colocando os CDs em ordem...[n][w][e]

[msg MND_E12720100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]Os alunos na sala de transmissão[n]estão colocando os CDs em ordem...[n][w][e]

[msg MSG_E13710100_CHK_HOUSOS [Ryuji]]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 1 7159 65535 0]Oh, por que não tentamos[n]reunir o time de vôlei[n]com um anúncio?[n][w][e]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]De fato, não. Kamoshida ouviria[n]isso e viria aqui.[n][w][e]

[msg MND_E13710100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]Os alunos na sala de transmissão[n]estão colocando os CDs em ordem...[n][w][e]

[msg MSG_E13910100_CHK_HOUSOS [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, eu disse a entrada principal! Se não nos[n]apressarmos, ele irá embora.[n][w][e]

[msg MND_E14130100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]Os alunos na sala de transmissão[n]estão colocando os CDs em ordem...[n][w][e]

[msg MND_E14710100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]Eu tenho que ir para o pátio imediatamente...[n][w][e]

[msg MSG_E23810100_CHK_HOUSOS [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Essa é a sala de transmissão. Não tem que ir para[n]a sala do conselho estudantil no terceiro andar?[n][w][e]

[msg MND_COMMON_CHK_HOUSOSITU]
[s][vp 1 0 0 0 0 0]Aqui eu não tenho que fazer nada[n]em particular...[n][w][e]

[msg MND_E12310100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Esta é uma sala de aula do primeiro ano.[n][w][e]
[s][vp 1 0 0 0 0 0]Os alunos parecem se perguntar[n]por que você está aqui. Talvez eu devesse[n]ir para outro lugar...[n][w][e]

[msg MND_E12720100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Esta é uma sala de aula do primeiro ano.[n][w][e]
[s][vp 1 0 0 0 0 0]Os alunos parecem se perguntar[n]por que você está aqui. Talvez eu devesse[n]ir para outro lugar...[n][w][e]

[msg MSG_E13710100_CHK_CLASS_ [Ryuji]]
[s][bup 0 2 202 0 0][f 4 10 65535 0 0][vp 8 2 1 7047 65535 0]Não vejo ninguém do[n]time de vôlei.[n][w][e]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vamos começar perguntando[n]aos seus colegas![n][w][e]

[msg MND_E13710100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Não vejo alunos com[n]lesões óbvias...[n][w][e]

[msg MSG_E13910100_CHK_CLASS_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, eu disse a entrada principal! Se não nos[n]apressarmos, ele irá embora.[n][w][e]

[msg MND_E14130100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Esta é uma sala de aula do primeiro ano.[n][w][e]
[s][vp 1 0 0 0 0 0]Os alunos parecem se perguntar[n]por que você está aqui. Talvez eu devesse[n]ir para outro lugar...[n][w][e]

[msg MND_E14710100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Eu tenho que ir para o pátio imediatamente...[n][w][e]

[msg MSG_E23810100_CHK_CLASS_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Essa é a turma do primeiro ano.[n]Vamos para a[n]sala do conselho estudantil no terceiro andar.[n][w][e]

[msg MND_COMMON_CHK_CLASS_1_0]
[s][vp 1 0 0 0 0 0]Esta é uma sala de aula do primeiro ano.[n][w][e]
[s][vp 1 0 0 0 0 0]Eu não tenho que fazer nada[n]em particular aqui...[n][w][e]

