[msg e511_630_mes_Start [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Estamos prestes a enfrentar[n]uma luta.[n]Você completou seus preparativos?[n][w][e]

[sel e511_630_mes_SEL top]
[s]Está tudo pronto.[e]
[s]Um segundo.[e]

[msg e511_630_mes_01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4087 65535 0]Mmm... Assim que estivermos prontos,[n]voltaremos.[n][w][e]

[msg e511_630_mes_02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4035 65535 0]Muito bem. Vamos![n][w][e]

[msg e511_630_mes_03 [Guarda sombra]]
[s]E assim, ouse desafiar Sua Excelência![n][w][e]

[sel e511_630_before_battle_S top]
[s]Nós passamos.[e]
[s]Fora do caminho.[e]

[msg e511_630_mes_04 [Guarda sombra]]
[s]Você não vai interferir no trabalho do mestre![n][w][e]

[msg e511_630_mes_05 [Guarda sombra]]
[s]Quem é VOCÊ para me dar ordens?[n][w][e]

[msg D10_12_researcher_enemy0 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Inimigos, Joker! ...Oh? As roupas deles...[n][w][e]

[msg D10_12_researcher_enemy0_2 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eles são... jalecos?[n]Por que os Shadows usam[n]jalecos em um estádio?[n][w][e]
[s]O que o Dr. Maruki vê neste[n]lugar?[n][w][e]

[msg D10_12_get_map_start [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4090 65535 0]Parece que este é[n]o mapa do Palácio.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]É detalhado… Parece que temos um longo caminho a percorrer.[n][w][e]

[msg D10_12_get_map02 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6184 65535 0]"Laboratório de ciências psi-cognitivas de[n]Maruki"...[n][w][e]

[msg D10_12_get_map03 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]O Palácio é um laboratório!?![n][w][e]

[msg D10_12_get_map04 [Akechi]]
[s][bup 0 9 801 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8130 65535 0]Você realmente não descobriu ainda?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Considerando o passado de[n]Maruki e a aparência do Palácio,[n]não foi difícil deduzir.[n][w][e]

[msg D10_12_get_map05 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7195 65535 0]Cale-se! É um lugar[n]tão absurdo que[n]não fazia sentido pensar nisso![n][w][e]

[msg D10_12_get_map05_insert0 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você me entende, não é, [f 4 2]!?![n][w][e]

[sel D10_12_get_map_SEL top]
[s]Fale por você mesmo.[e]
[s]Eu entendo você.[e]

[msg D10_12_get_map06 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54215 65535 0]...Sério?[n][w][e]

[msg D10_12_get_map07 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8155 65535 0]A aparência de um Palácio depende[n]do que seu senhor pensa[n]de alguém ou algo.[n][w][e]

[msg D10_12_get_map08 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7048 65535 0]Sim! Pegue isso![n][w][e]

[msg D10_12_get_map09 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8155 65535 0]...A aparência de um Palácio depende[n]do que seu senhor pensa[n]de alguém ou algo.[n][w][e]

[msg D10_12_get_map10 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No caso de Takuto Maruki, ele deve[n]considerar o estádio como[n]um laboratório.[n][w][e]

[msg D10_12_get_map11 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sim, essa parte está clara para mim.[n]Mas de todos os lugares possíveis,[n]por que o estádio?[n][w][e]

[msg D10_12_get_map12 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57037 65535 0]Oh... Me lembra de algo que ouvi há um tempo[n]atrás.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Antes do estádio, um laboratório de pesquisa foi[n]planejado para ser construído.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Terá algo a ver com essa história...?[n][w][e]

[msg D10_12_get_map_end [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8038 65535 0]É possível, mas por enquanto devemos[n]focar no progresso no[n]Palácio, não nas perguntas.[n][w][e]

[msg D10_12_1st_passcode_lock [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uh-oh. Essa porta tem uma trava de segurança[n]maluca e não tem nem o scanner...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos olhar mais de perto![n][w][e]

[msg D10_12_1st_passcode_lock_2 [Voz mecânica]]
[s]Bloqueio de segurança ativo.[n]Responda à seguinte[n]pergunta de autenticação:[n][w][e]
[s]O que Takuto Maruki sacrificou[n]em troca do poder de[n]reescrever cognições?[n][w][e]

[msg D10_12_1st_passcode_lock_3 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]Aaah, ele falou! Erm...[n]mas esse não é o problema.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O que diabos ele quer dizer? O Doc[n]perdeu alguma coisa? É um enigma?[n][w][e]

[msg D10_12_1st_passcode_lock_4 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9128 65535 0]É uma pergunta de segurança, como[n]quando você redefine uma senha. A[n]resposta só uma pessoa sabe.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]É assim que você acaba[n]usando suas informações[n]pessoais como chaves.[n][w][e]

[msg D10_12_1st_passcode_lock_5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entendi. Então precisamos de[n]informações sobre a vida de Maruki...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bem, é o palácio dele. Aposto[n]que olhando com cuidado encontraremos[n]as pistas para responder.[n][w][e]

[msg D10_12_1st_passcode_lock_6 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7052 65535 0]Ok, se esse é o plano,[n]vamos caçar pistas![n][w][e]

[msg D10_12_1st_passcode_lock_7 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]Joker, não deveríamos[n]encontrar as pistas primeiro?[n][w][e]

[msg D10_12_1st_passcode_lock_8 [Voz mecânica]]
[s]Bloqueio de segurança ativo.[n]Responda à seguinte[n]pergunta de autenticação:[n][w][e]
[s]O que Takuto Maruki sacrificou[n]em troca do poder de[n]reescrever cognições?[n][w][e]

[msg D10_12_1st_passcode_lock_9 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]Graças a esse vídeo,[n]sabe a resposta...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você também deve saber,[n]certo? A honra é sua.[n][w][e]

[sel D10_12_1st_passcode_lock_10 top]
[s]Um amigo dele.[e]
[s]A família dele.[e]
[s]O mestre dele.[e]
[s]A namorada dele.[e]

[msg D10_12_1st_passcode_lock_11 [Voz mecânica]]
[s]Resposta errada.[n]Dispositivo de bloqueio ativo.[n][w][e]

[msg D10_12_1st_passcode_lock_12 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8141 65535 0]Parece que você entendeu errado,[n]Joker. Tente novamente.[n][w][e]

[msg D10_12_1st_passcode_lock_13 [Voz mecânica]]
[s]Autenticação concluída.[n]Bloquear.[n][w][e]

[msg D10_12_1st_passcode_lock_14 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54241 65535 0]Yay! Conseguimos![n][w][e]

[msg D10_12_1st_passcode_lock_15 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Joker, vamos dar uma olhada mais de perto na[n]porta com a fechadura supersegura.[n][w][e]

[msg D10_12_get_map_start_bef [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O que... O que é isso?[n][w][e]

[msg D10_12_wall_vanish_start [Haru]]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ver! Os cabos sumiram![n][w][e]

[msg D10_12_wall_vanish_01 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]É uma sorte termos experimentado[n]o console encontrado nos Mementos...[n]agora podemos continuar.[n][w][e]

[sel D10_12_wall_vanish_sel top]
[s]Vamos.[e]
[s]Procedemos com cautela.[e]

[msg D10_12_wall_vanish_end [[f 4 31 10 0]]]
[s][bup 0 10 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57026 65535 0]Ok! Vamos, senpai![n][w][e]

[msg D10_12_find_boss_start [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]Um momento. Olhe para lá![n][w][e]

[msg D10_12_find_boss_01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aqui a segurança é ainda mais[n]rígida. Eles parecem muito fortes.[n][w][e]

[msg D10_12_find_boss_end [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Portanto, estamos em um lugar importante. Assim[n]que estiverem prontos, vamos retirá-los.[n][w][e]

[msg D10_12_1st_passcode_lock_16 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Hum? Espera, Joker...[n][w][e]

[msg note_find_reaction_start [[f 4 31 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57037 65535 0]O que será? Um diário?[n][w][e]

[msg note_find_reaction_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Assim parece. A julgar pelo que[n]está escrito, é provável[n]que pertença a Maruki...[n][w][e]

[msg note_find_reaction_watch [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Mesmo aquele vídeo anterior...[n]Ele adora falar sobre si mesmo.[n][w][e]

[msg note_find_reaction_notwa [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4191 65535 0]Ele parece ter anotado várias coisas[n]sobre o passado, mas estas[n]parecem ser apenas fragmentos...[n][w][e]

[msg note_find_reaction_end [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nem parece ter[n]qualquer significado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Não sei se pode ser útil para[n]a investigação, mas vamos mantê-lo e[n]ver se encontramos outros.[n][w][e]

