[sel YESNO_SEL top]
[s]Sim [e]
[s]Não [e]

[msg MSG_DUMMY]
[s]......[n][w][e]

[msg MSG_LAST_GREETING_DRUGST [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]O medicamento de Takemi é muito mais eficaz[n]do que as coisas que estão vendendo aqui.[n][w][e]

[msg MSG_LAST_GREETING_DRUGST_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]Você ainda precisa comprar necessidades[n]diárias neste momento? Vamos dizer adeus a[n]todos.[n][w][e]

[msg MSG_LAST_GREETING_KARAOK [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Todos nós fomos ao karaokê quando estávamos[n]procurando Kaneshiro, certo?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Sinto falta desses tempos... vamos voltar.[n][w][e]

[msg MSG_LAST_GREETING_BEEFDO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Você conheceu Yoshida quando estava[n]trabalhando aqui, certo?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Mas cara, esse trabalho foi difícil. Alguém[n]pode não ter sido capaz de lidar com isso.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Mas o proprietário... ele sempre o mantinha[n]fresco.[n][w][e]

[msg MSG_LAST_GREETING_BEEFDO_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Você veio comer aqui com Ryuji, certo?[n]Mesmo um ano depois, ele ainda é o mesmo[n]velho Ryuji.[n][w][e]

[msg MSG_LAST_GREETING_FAMILY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Viemos aqui quando Yusuke se juntou aos[n]ladrões Phantom...[n][w][e]
[s][f 4 10 65535 0 0]E viemos aqui com Sumire, bem como para[n]outras ocasiões também. De certa forma,[n]este foi o nosso segundo esconderijo.[n][w][e]

[msg MSG_LAST_GREETING_FAMILY_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Viemos aqui quando Yusuke se juntou aos[n]ladrões Phantom...[n][w][e]
[s][f 4 10 65535 0 0]E viemos aqui com Yoshizawa, bem como para[n]outras ocasiões também. De certa forma,[n]este foi o nosso segundo esconderijo.[n][w][e]

[msg MSG_LAST_GREETING_AUTO_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Digamos tchau para todos. Você pode obter[n]suco depois disso.[n][w][e]

[msg MSG_LAST_GREETING_BOOKST [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]Você não tem tempo para comprar livros[n]agora. Vamos dizer nossas despedidas a[n]todos.[n][w][e]

[msg MSG_LAST_GREETING_BOOKST_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Você pode olhar para o cronograma de[n]remessa, mas não poderá mais comprar livros[n]daqui...[n][w][e]

[msg MSG_LAST_GREETING_DONQ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Aposto que sua cidade natal tem lojas[n]maiores.[n][w][e]

[msg MSG_LAST_GREETING_CINEMA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]O novo cinema era realmente algo. Vamos[n]voltar.[n][w][e]

[msg MSG_LAST_GREETING_CINEMA_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Você não poderá dizer adeus se assistir a um[n]filme.[n][w][e]

[msg MSG_LAST_GREETING_GALAXY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1045 65535 0]Não achei que você se tornaria o[n]"capitão"... você realmente tem algo[n]"especial"![n][w][e]

[msg MSG_LAST_GREETING_GALAXY_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Eu acho que você chegou ao primeiro[n]companheiro.[n]Você se saiu muito bem.[n][w][e]

[msg MSG_LAST_GREETING_GALAXY_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Você chegou ao segundo companheiro, certo?[n]Comer demais não é bom para você...[n][w][e]

[msg MSG_LAST_GREETING_GALAXY_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]Você não tem tempo para comer hambúrgueres.[n]Vamos dizer nossas despedidas a todos.[n][w][e]

[msg MSG_LAST_GREETING_TSUTAY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Devolvi os DVDs que você emprestou.[n]Você não tem nada com o que se preocupar.[n][w][e]

[msg MSG_LAST_GREETING_TSUTAY_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Não poderíamos devolvê-lo se emprestássemos[n]algo agora. Vamos a algum outro lugar![n][w][e]

[msg MSG_LAST_GREETING_CREPE_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53138 65535 0]The double cream crêpe was Lady Ann's[n]favorito![n][w][e]
[s][f 4 10 65535 0 0]... Hmm, parece que não há desconto hoje.[n][w][e]

[msg MSG_LAST_GREETING_CREPE__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]You don't have time to buy a crêpe.[n]Vamos dizer nossas despedidas.[n][w][e]

[msg MSG_LAST_GREETING_CLOTHE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Você deve se tornar um adulto que fica bem[n]nisso.[n][w][e]

[msg MSG_LAST_GREETING_LOCKER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]... é aqui que vocês me resgataram.[n]Isso foi embaraçoso.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Mas agora é uma história engraçada, olhando[n]para trás... obrigado.[n][w][e]

[msg MSG_LAST_GREETING_DEADEN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]É aqui que Ryuji parou o táxi.[n]Ele era muito legal naquele momento.[n][w][e]

[msg MSG_LAST_GREETING_DEADEN_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Você não conhece ninguém que passaria aqui,[n]não é? Vamos a algum outro lugar.[n][w][e]

[msg MSG_LAST_GREETING_TRAINI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Você não tem tempo para ir à academia.[n]Vamos dizer tchau.[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Você não precisa estar aqui agora, não é?[n]Vamos lá, vamos para outro lugar![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]O que está errado? Vamos lá, devemos dizer[n]adeus aos outros![n][w][e]

[msg MSG_LastKeyfree [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Mal podemos esperar mais...[n]Temos que nos preparar e rápido![n][w][e]

[msg MND_0103]
[s]Não há nada que eu precise fazer aqui...[n][w][e]
[s]Eu deveria ir verificar todos...[n][w][e]

[msg MND_0103to0108_Error_Not]
[s]Isso não é hora de fazer compras...[n][w][e]
[s]Eu deveria ir verificar todos...[n][w][e]

[msg MND_0103to0108_Error_Not_2]
[s]Isso não é hora de desvios...[n][w][e]
[s]Eu deveria ir verificar todos...[n][w][e]

[msg MND_0103to0108_Error_Bur]
[s]É um sinal de hambúrguer do Big Bang.[n][w][e]
[s]Eu deveria ir verificar todos...[n][w][e]

[msg MND_LOOK_EVT_712_010_TOD]
[s]Os detetives ainda estão falando com ele. Eu[n]deveria voltar outra vez...[n][w][e]

[msg MSG_SHOP_LOCK]
[s](I haven't gotten any[n]info on the weapons shop.)[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_MILI]
[s]Agora você pode viajar rápido para o [n][clr 6]Airsoft Shop [clr 0]Em Shibuya.[n][w][e]

[msg MSG_KARAOKE_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Você não tem tempo para karaokê agora, não[n]é? Estou curioso sobre quais músicas você[n]escolheria.[n][w][e]

[msg MND_KARAOKE]
[s]Aparentemente está totalmente reservado...[n][w][e]

[msg Msg_NotOpen_moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Você está com fome ou algo assim? Podemos[n]muito bem ir para algo mais caro, e...[n][w][e]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0]OHO... esse funcionário de meio período é[n]difícil. Mas trabalhar aqui pode[n]desenvolver seu [n][f 4 11 2][clr 26][f 4 12 2][clr 27]...[n][w][e]

[msg MSG_BAITO_NOTOPEN]
[s]Parece ser um em uma grande cadeia de lojas[n]de tigela de carne...[n][w][e]

[msg MSG_BeefTutorial [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Venha para pensar sobre isso, você se[n]candidatou a um emprego de meio período[n]nesta loja de bowls, certo?[n][w][e]

[msg MSG_Beef_NoShift [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]HM? Seu turno na loja de bowls de carne está[n]em [n][clr 2]noite [clr 27], não é?[n][w][e]

[msg MSG_Beef_OKShift [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Você quer trabalhar aqui hoje?[n][w][e]

[sel SEL_Beef_Q top]
[s]Vamos ao trabalho.[e]
[s]Não vamos trabalhar hoje.[e]

[msg MSG_Gyudon_ParamInfo_int [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Você pode melhorar seu [n][f 4 11 2][clr 26][f 4 12 2][clr 27]Se você trabalha em um lugar de tigela de[n]carne.[n][w][e]

[msg MSG_Gyudon_ParamInfo_int_2 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1029 65535 0]O que está acontecendo? Está lotado...[n]Oh, há um desconto porque é [n][clr 2]Dia de Yakiniku [clr 27]![n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Se pudéssemos gerenciar tantos clientes, seu [f 4 11 2][clr 26][f 4 12 2][clr 27]seria consideravelmente melhorado...[n][w][e]

[msg MND_Beefdon_ParamUpInfo]
[s]Eu me sinto como meu [f 4 11 1][clr 26][f 4 12 2][clr 27][n]vai melhorar em breve...[n][w][e]

[msg MND_Beefdon_ParamEndInfo]
[s]Eu acho que tenho o suficiente [n][f 4 11 2][clr 26][f 4 12 2][clr 27]já...[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_GYUD]
[s]Agora você pode viajar rápido para o [n][clr 6]Loja de tigela de carne [clr 0]Em Shibuya.[n][w][e]

[msg MSG_FAMIRES_NOTOPEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]"Menino Bikkuri, renovado e reabrindo em[n]breve!"... Parece que eles estão abrindo um[n]restaurante familiar aqui.[n][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0]Diz [clr 2]Poderia [clr 27]. Vamos voltar novamente.[n][w][e]

[msg MSG_FAMIRES_NOTOPEN_MORU_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]"Menino Bikkuri, renovado e reabrindo em[n]breve!"... Esse é um nome estranho para um[n]restaurante.[n][w][e]
[s][f 4 10 65535 0 0]Ele abre no [clr 2]6 deste mês [clr 27].[n]Tudo bem, vamos voltar novamente.[n][w][e]

[msg MSG_Famires_Start_1st [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Ei, este restaurante familiar foi reformado[n]e está aberto novamente![n][w][e]

[msg MSG_Famires_Use_Common [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Aposto que você poderia estudar aqui[n]enquanto também aprecia o menu.[n][w][e]

[msg MSG_Famires_Use_RainDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Pode não haver muita gente por causa do[n]clima de hoje.[n][w][e]

[msg MND_Famires_ParamUpInfo]
[s]Eu me sinto como meu [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vai melhorar em breve...[n][w][e]

[msg MND_Famires_ParamEndInfo]
[s]Eu acho que tenho o suficiente [n][f 4 11 0][clr 26][f 4 12 0][clr 27]já...[n][w][e]

[msg MSG_Famires_Use_Ask [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Você quer estudar aqui?[n][w][e]

[sel SEL_FAMIRES_START_MORU top]
[s]Vamos entrar.[e]
[s]Vou passar.[e]

[msg MSG_Famires_MoneyNone [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Verifique sua carteira. Você não pode pedir[n]nada se não tiver dinheiro...[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_FAMI]
[s]Agora você pode viajar rápido para o [n][clr 6]O jantar [clr 0]Em Shibuya.[n][w][e]

[msg MND_Juice_NotOpen]
[s]Não estou com sede agora...[n][w][e]

[msg MSG_Juice_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Você está pensando em comprar algo para[n]beber?[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Tudo está esgotado... Vamos esperar que seja[n]reabastecido na próxima semana.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Opa, tudo está esgotado. Vamos esperar que[n]seja reabastecido na próxima semana.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]... tudo está esgotado. Eu acho que não é[n]surpresa com o quão quente está agora...[n][w][e]

[msg BOOKSTORE_NOTOPEN_TYPE01 [Staff]]
[s]Este lugar parece bastante cheio de[n]trabalhadores e estudantes de escritório.[n][w][e]
[s]Eu deveria vir outra hora em que está menos[n]lotado...[n][w][e]

[msg BOOKSTORE_NOTOPEN_TYPE02 [Server]]
[s]Este lugar está realmente lotado. É uma[n]feira de livros voltada para novas[n]contratações e alunos do primeiro ano.[n][w][e]
[s]Eu deveria vir outra hora em que está menos[n]lotado...[n][w][e]

[msg BOOKSTORE_SELECT [Bookstore Employee]]
[s]Bem-vindo. Os livros populares estão aqui.[n][w][e]

[msg BOOKSTORE_THANKS [Bookstore Employee]]
[s]Muito obrigado.[n][w][e]

[msg BOOKSTORE_NOT_BUY [Bookstore Employee]]
[s]Por favor, venha novamente.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_CONV]
[s]Agora você pode viajar rápido para o [n][clr 6]Loja de conveniência [clr 0]Em Shibuya.[n][w][e]

[msg MSG_Conveni_ByebyeEnd [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Você terminou aqui, certo? Vamos a algum[n]outro lugar.[n][w][e]

[msg DONQ_NOTOPEN]
[s]É uma linha diversa que inclui tudo, desde[n]comida até móveis domésticos...[n][w][e]
[s]Eu deveria comprar algo aqui assim que me[n]acostumar com minha rotina de vida diária.[n][w][e]

[msg DONQ_START [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Que labirinto louco. É quase como um[n]palácio...[n][w][e]

[msg DONQ_THANKS [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Você compra algo útil?[n][w][e]

[msg DONQ_NOT_BUY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]... Oh, você está apenas olhando em volta.[n][w][e]

[msg MSG_THEATER_NG [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1140 65535 0]Não sei se ir ao cinema à tarde é uma boa[n]ideia, mesmo que você precise de um[n]respiro...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Você quer ver os filmes que estão sendo[n]exibidos?[n]Então vamos cuidar de Kamoshida rapidamente![n][w][e]

[msg MSG_SYSTEM_SHORTCUT_Shib]
[s]Agora você pode viajar rápido para o [n][clr 6]Cinema [clr 0]Em Shibuya.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_BIGB]
[s]Agora você pode viajar rápido para [n][clr 6]Big Bang Burger [clr 0]Em Shibuya.[n][w][e]

[msg MSG_GAME_CENTER_DEFAULT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]Tem certeza de que tem tempo para jogar em[n]um fliperama?[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_SHIB]
[s]Agora você pode viajar rápido para o [n][clr 6]videogames [clr 0]Em Shibuya.[n][w][e]

[msg DrugStore_NOTOPEN]
[s]Este local não apenas vende medicamentos,[n]mas também detergentes e outras[n]necessidades diárias.[n][w][e]
[s]Eu deveria vir aqui da próxima vez que[n]preciso de algo.[n][w][e]

[msg DrugStore_SELECT [Drugstore Clerk]]
[s]Welcooome. Havia algo que você estava[n]procurando?[n][w][e]

[msg DrugStore_THANKS [Drugstore Clerk]]
[s]Muito obrigado. Por favor, venha de novo![n][w][e]

[msg DrugStore_NOT_BUY [Drugstore Clerk]]
[s]Por favor, apareça novamente![n][w][e]

[msg MSG_DRUGSTORE_KAMOSHIDA_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Eu prefiro receber remédios mais potentes do[n]que isso, mas isso terá que fazer por[n]enquanto.[n][w][e]

[msg MSG_DRUGSTORE_KAMOSHIDA__2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Devemos usar o medicamento mais potente que[n]isso. Onde podemos encontrar algum remédio[n]melhor?[n][w][e]

[msg MSG_CREPE_SHOP_DEFAULT]
[s]Há um aroma único e doce no ar...[n][w][e]

[msg MSG_CREPE_SHOP_DEFAULT_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]A crêpe store, huh? You're not really[n]a crêpe person though, are you?[n][w][e]

[msg MSG_CLOTHES_SHOP_DEFAULT]
[s]Há roupas de várias cores alinhadas dentro[n]da loja.[n][w][e]

[msg MSG_CLOTHES_SHOP_DEFAULT_2 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Esse é o tipo de moda que é popular hoje em[n]dia? Todos eles parecem o mesmo para mim...[n][w][e]

[msg MSG_LOCKER_DEFAULT]
[s]Eles foram desfigurados de adesivos e[n]rabiscos...[n][w][e]

[msg MSG_LOCKER_DEFAULT_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Por que alguém faria isso? Eles deixaram[n]isso em um estado tão terrível...[n][w][e]

[msg MSG_VELVET_GIRL_LOUD01 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 2 0 11018 65535 0]Você não tem tempo para brincar, preso![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Apresse-se de volta para sua prisão![n][w][e]

[msg MSG_VELVET_GIRL_Lavenza [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55422 65535 0]Esses ensaios... acredito que você pode[n]superá-los.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_VELV]
[s]Agora você pode viajar rápido para o [n][clr 6]Sala de veludo [clr 0].[n][w][e]

[msg MSG_DEADEND01_DEFAULT_MO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Não há nada que você precise fazer à frente,[n]certo? Vamos voltar![n][w][e]

[msg MSG_DEADEND01_DEFAULT]
[s]Há todos esses carros passando. Não há nada[n]que eu precise fazer à frente.[n][w][e]

[msg MSG_Training_NotOpen_Myr [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Uma academia de esportes, hein? É admirável[n]que você queira treinar, mas chegar ao[n]ponto de pagar dinheiro para fazer isso?[n][w][e]

[msg MSG_Training_NotOpen_Myr_2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Uma academia de esportes, hein? É admirável[n]que você queira treinar, mas chegar ao[n]ponto de pagar dinheiro para fazer isso?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Por que não apenas treinar no seu quarto?[n]Isso é mais econômico.[n][w][e]

[msg MSG_GIM_Start1st [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Esta academia... já estivemos aqui antes.[n][w][e]

[msg MSG_GIM_Think_AllDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Então você está planejando chegar à academia?[n]São 2.000 ienes por visita.[n][w][e]

[msg MSG_GIM_Think_Weekday_Go [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Então você está planejando chegar à academia?[n]São 1.000 ienes se você for uma tarde da[n]semana.[n][w][e]

[msg MSG_GIM_Think_Weekday_Yo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Então você está planejando chegar à academia?[n]São 1.800 ienes se você for uma noite de dia[n]da semana.[n][w][e]

[msg MSG_GIM_Think_Weekend_Go [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Então você está planejando chegar à academia?[n]São 1.200 ienes se você for em uma tarde de[n]fim de semana.[n][w][e]

[msg MSG_GIM_Think_Weekend_Yo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Então você está planejando chegar à academia?[n]São 2.000 ienes se você for em uma noite de[n]fim de semana.[n][w][e]

[sel SEL_GimShopEnter_Q top]
[s]Vamos entrar.[e]
[s]Não, não importa.[e]

[msg MSG_GIM_MoneyOver [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]... que decepcionante. Você não tem dinheiro[n]suficiente.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_GYM]
[s]Agora você pode viajar rápido para o [n][clr 6]Academia de Esportes [clr 0]Em Shibuya.[n][w][e]

[msg MSG_BURGER_BOARD_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Big Bang Burger, não é? Um nome bastante[n]grandioso.[n][w][e]

[msg MSG_BURGER_BOARD]
[s]É um sinal de hambúrguer do Big Bang.[n][w][e]
[s]Parece que eles têm um menu sazonal...[n][w][e]

[msg MSG_Deadend02_MORU [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Ninguém nesta cidade se preocupa com os[n]danos que eles causam aos outros... Sheesh,[n]sem maneiras.[n][w][e]

[msg MSG_Deadend02]
[s]Uma bicicleta está bloqueando o caminho...[n][w][e]

[msg MND_BookPanel_01]
[s]O sinal da livraria tem informações sobre[n]novas publicações escritas...[n][w][e]
[s]Eu deveria ir conferir de vez em quando...[n][w][e]

[msg MND_BookPanel_02]
[s]O sinal da livraria tem informações sobre[n]novas publicações escritas...[n][w][e]
[s]"Um must-have para sobreviver à era da[n]Internet!" está programado para um[n]lançamento no início de maio.[n][w][e]
[s]Eu deveria voltar aqui quando for lançado...[n][w][e]

[msg MND_BookPanel_03]
[s]O sinal da livraria tem informações sobre[n]novas publicações escritas...[n][w][e]
[s]"Recurso especial de pontos que aumentam a[n]feminilidade!" está programado para uma[n]versão em 16 de maio.[n][w][e]
[s]Eu deveria voltar aqui quando for lançado...[n][w][e]

[msg MND_BookPanel_04]
[s]O sinal da livraria tem informações sobre[n]novas publicações escritas...[n][w][e]
[s]"Livro especial para adultos que jogam[n]intelectualmente!" está programado para um[n]lançamento em 1 de junho.[n][w][e]
[s]Eu deveria voltar aqui quando for lançado...[n][w][e]

[msg MND_BookPanel_05]
[s]O sinal da livraria tem informações sobre[n]novas publicações escritas...[n][w][e]
[s]"Livro de histórias de fantasmas para[n]superar o verão quente!" está programado[n]para um lançamento em 1 de julho.[n][w][e]
[s]Eu deveria voltar aqui quando for lançado...[n][w][e]

[msg MND_BookPanel_06]
[s]O sinal da livraria tem informações sobre[n]novas publicações escritas...[n][w][e]
[s]"O recurso especial da cidade: a[n]característica especial de lagoas de[n]pesca!" será lançado em 16 de julho.[n][w][e]
[s]Eu deveria voltar aqui quando for lançado...[n][w][e]

[msg MND_BookPanel_07]
[s]O sinal da livraria tem informações sobre[n]novas publicações escritas...[n][w][e]
[s]"Quiet e conforto: característica especial[n]dos pontos de namoro!" sai em 1 de setembro.[n][w][e]
[s]Eu deveria voltar aqui quando for lançado...[n][w][e]

[msg MND_BookPanel_08]
[s]Não vejo nenhuma informação aqui que[n]realmente me interessa.[n][w][e]

[msg MSG_M79_GYU_DON_000_00_0 [Morgana]]
[s][vp 8 2 1 1164 65535 0][bup 0 3 5 0 0][f 4 10 65535 0 0]Este trabalho está sempre ocupado...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Esse timer de parte pode saber algo.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Vamos esperar que ele sai.[n][w][e]

[msg MSG_M79_GYU_DON_001_00_0 [Morgana]]
[s][vp 8 2 1 1167 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Oh? É ele?[n][w][e]

[msg MSG_M79_GYU_DON_002_00_0 [Timid Man]]
[s][f 4 25 1 500 0 0]Eek! Eu-eu sinto muito![n][w][e]

[sel SEL_M79_GYU_DON_003_00_0 top]
[s]Eu tenho uma pergunta.[e]
[s]Não me desculpe.[e]

[msg MSG_M79_GYU_DON_004_01_0 [Timid Man]]
[s][f 4 25 1 500 0 0]Oh... não, está... tudo bem.[n][w][e]
[s][f 4 25 1 65535 0 0]Hum, você pode sair do caminho?[n][w][e]

[msg MSG_M79_GYU_DON_005_00_0 [Timid Man]]
[s][f 4 25 1 500 0 0]W-quem você está...? Eu já contei à polícia[n]sobre ele...[n][w][e]
[s][f 4 25 1 500 0 0]Esta loja geralmente é uma operação de um[n]homem.[n]Nós realmente não vemos outros[n]funcionários...[n][w][e]
[s][f 4 25 1 500 0 0]E mesmo que eu o veja às vezes, apenas[n]conversamos algumas vezes...[n][w][e]

[sel SEL_M79_GYU_DON_006_00_0 top]
[s]Queremos provar sua inocência.[e]
[s]Por favor, diga-nos o que você sabe.[e]

[msg MSG_M79_GYU_DON_007_00_0 [Timid Man]]
[s][f 4 25 1 500 0 0]Ei, você poderia ser... amigo de Toji-kun?[n][w][e]
[s][f 4 25 1 500 0 0]... Eu acho que ele também é inocente. Ele é[n]um garoto muito brilhante e bom.[n][w][e]

[msg MSG_M79_GYU_DON_008_00_0 [Timid Man]]
[s][f 4 25 1 500 0 0]Ele tem dois empregos de meio período. Deve[n]ser difícil para ele, mas ele está sempre[n]sorrindo...[n][w][e]

[sel SEL_M79_GYU_DON_009_00_0 top]
[s]Algo mais?[e]
[s]Conte-nos mais.[e]

[msg MSG_M79_GYU_DON_010_00_0 [Timid Man]]
[s][f 4 25 1 500 0 0]Huh...? Quero dizer, eu não falei tanto com[n]ele...[n][w][e]
[s][f 4 25 1 500 0 0]Ah, mas conversamos sobre o nome de sua[n]família ser Karataki e como é um nome[n]incomum.[n][w][e]
[s][f 4 25 1 500 0 0]E ele disse que o nome da família de seu pai[n]também é único...[n][w][e]
[s][f 4 25 1 500 0 0]Foi... Ushiwata, eu acho?[n][w][e]

[msg MSG_M79_GYU_DON_011_00_0 [Timid Man]]
[s][f 4 25 1 500 0 0]E conversamos sobre como esse é um nome[n]perfeito para um lugar de tigela de carne...[n][w][e]
[s][f 4 25 1 500 0 0]Mas isso é tudo que eu sei...[n][w][e]

[msg MSG_M79_GYU_DON_012_00_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Hmm, Toji Karataki... Nós descobrimos o nome[n]dele então.[n][w][e]

[msg MSG_M79_GYU_DON_013_00_0 [Timid Man]]
[s][f 4 25 1 500 0 0]É tudo o que sei, desculpe. Posso ir[n]agora...?[n][w][e]

[msg MSG_E24330100_NG_GOTO_ST [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1176 0 0]Onde você está indo? Eu pensei que você[n]deveria estar explorando Shibuya...[n][w][e]
[s]Esta era sua área, certo?[n][w][e]

[msg MND_CHK_STATION]
[s][vp 1 0 0 0 0 0]Eu não deveria simplesmente ir para casa...[n][w][e]
[s][vp 1 0 0 0 0 0]Vou apenas seguir Ryuji por enquanto...[n][w][e]

[msg MND_CHK_STATION2]
[s][vp 1 0 0 0 0 0]Eu não deveria simplesmente ir para casa...[n][w][e]
[s][vp 1 0 0 0 0 0]Vou apenas seguir Ryuji por enquanto...[n][w][e]

[msg MND_COMMON_CHK_DRUGSTORE]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_DRUGSTORE_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1001 65535 0]Parece que você pode comprar coisas aqui[n]também.[n]Vamos ver, o remédio que ajuda quando é mais[n]necessário...?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Vamos verificar este lugar novamente em[n]algum momento. Parece que eles têm coisas[n]úteis aqui.[n][w][e]

[msg MSG_DRUGSTORE_KF_R [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7131 65535 0]Esta farmácia vende colírios e outras coisas.[n]É útil quando quero jogar a noite toda![n][w][e]

[msg MSG_DRUGSTORE_KF_2 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]...Minha nossa.[n][w][e]

[msg MND_COMMON_CHK_MILITARY]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MND_COMMON_CHK_KARAOKE]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_KARAOKE_KF [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Você não tem tempo para karaokê agora, não[n]é? Estou curioso sobre quais músicas você[n]escolheria.[n][w][e]

[msg MSG_KARAOKE_KF_R [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]Ei, vamos lá! Vamos conferir armas, certo?[n][w][e]

[msg MSG_KARAOKE_KF_0504 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Sem tempo para desvios! Vamos em algum lugar[n]onde possamos ganhar dinheiro![n][w][e]

[msg MND_COMMON_CHK_GYUDON]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_BEEFDON_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]...Oh? Não é aí que chegamos a comer com[n]Ryuji?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Até cheira bem de fora.[n]Me whehehe...[n][w][e]

[msg MSG_BEEFDON_KF_R [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7024 65535 0]O gengibre vermelho deles é o melhor!...[n]Mesmo apenas falar sobre isso me deixa com[n]fome.[n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tudo bem, da próxima vez. Vamos ir hoje.[n][w][e]

[msg MSG_BEEFDON_KF_0504 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Está com fome? Vamos trocar essa medalha.[n][w][e]

[msg MND_COMMON_CHK_FAMILY_RE]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_FAMILY_RESTAURANT_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1026 65535 0]Oh maldito... parece que esta loja ainda não[n]está aberta.[n][w][e]

[msg MSG_FAMILY_RESTAURANT_KF_2 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7080 65535 0]Aquele restaurante ainda está renovado.[n][w][e]

[msg MND_COMMON_CHK_AUTO_MACH]
[s][vp 8 2 65535 0 0 0]Voltarei aqui e comprarei algo quando tiver[n]tempo...[n][w][e]

[msg MSG_AUTO_MACHINE_KF_0504 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1046 65535 0]Você não tem tempo para beber suco![n]Vamos lá, vamos trocar essa medalha![n][w][e]

[msg MND_COMMON_CHK_BOOKSTORE]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_BOOKSTORE_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]A aquisição de conhecimento é importante[n]para ladrões. O conhecimento pode ser útil[n]em uma situação apertada.[n][w][e]

[msg MSG_BOOKSTORE_KF_R [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 54211 65535 0]Fico com sono quando leio livros.[n]'Especialmente quando é durante a aula...[n][w][e]

[msg MSG_BOOKSTORE_KF_2 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Minha nossa.[n][w][e]

[msg MSG_BOOKSTORE_KF_0504 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1043 65535 0]Não há como a livraria comprá-la! Vamos a[n]algum outro lugar.[n][w][e]

[msg MND_COMMON_CHK_CONVENIEN]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_CONVENIENCE_KF [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Hmm... parece que eles vendem todos os tipos[n]de lanches.[n]Ooh, aquele parece bom...[n][w][e]

[msg MSG_CONVENIENCE_KF_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7183 65535 0]HM? Eu paro aqui às vezes também.[n][w][e]

[msg MSG_CONVENIENCE_KF_0504 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]As lojas de conveniência não compram[n]coisas...[n]Você sabe que vamos trocar essa medalha por[n]dinheiro, certo?[n][w][e]

[msg MND_COMMON_CHK_DONQ]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_DONQ_KF [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0]Isso é incrível. Como um labirinto...[n][w][e]

[msg MSG_DONQ_KF_R [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7020 65535 0]É útil, pois eles vendem coisas baratas.[n]Gosta do pacote de valor jumbo? É enorme e[n]um valor totalmente bom para o preço![n][w][e]

[msg MSG_DONQ_KF_2 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1047 65535 0]Eu não acho que realmente precisava ser[n]explicado...[n][w][e]

[msg MSG_DONQ_KF_0504 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Vamos fazer compras outra vez. Precisamos[n]procurar um lugar em que possamos trocar[n]essa medalha por dinheiro.[n][w][e]

[msg MND_COMMON_CHK_CINEMA]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_CINEMA_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1001 65535 0]Oh, um cinema. Eles estão atualmente[n]jogando...[n][w][e]

[msg MSG_CINEMA_KF_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Ei, estamos indo para a loja de armas.[n]Vamos assistir a um filme outra vez.[n][w][e]

[msg MSG_CINEMA_KF_0504 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1140 65535 0]Não temos tempo para assistir a um filme![n]Vamos lá, vamos trocar essa medalha por[n]dinheiro hoje, não importa o quê![n][w][e]

[msg MND_COMMON_CHK_GALAXY]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_GALAXY_KF_R [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7161 65535 0]Quando penso na Central Street, penso em Big[n]Bang Burger. Eles vendem todos os tipos de[n]hambúrgueres lá. Eu recomendo- [n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Gah, não, foco. Deveríamos estar procurando[n]armas. Venha, vamos.[n][w][e]

[msg MSG_GALAXY_KF [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Todos os tipos de hambúrgueres, hein? Como[n]eles poderiam ser? Minha curiosidade está[n]despertada...[n][w][e]

[msg MSG_E24330100_NG_GOTO_UN [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1155 0 0]Você vai em frente e lida com a Central[n]Street.[n]Deixe o resto para os outros.[n][w][e]

[msg MSG_E24330100_NG_GOTO_UN_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1155 0 0]Você vai em frente e lida com a Central[n]Street.[n]Deixe o resto para os outros.[n][w][e]

[msg MND_COMMON_CHK_TSUTAYA]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_TSUTAYA_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Isso é... uma loja de aluguel.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Hmm... eles estão procurando novos membros.[n]Eu me pergunto o que você pode fazer se você[n]se tornar um.[n][w][e]

[msg MSG_TSUTAYA_KF_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7137 65535 0]Eu acho que você pode alugar e assistir a[n]programas populares. Mas não hoje. Estamos[n]indo para a loja de armas hoje.[n][w][e]

[msg MND_COMMON_CHK_GAME_CENT]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MND_COMMON_CHK_CREPE_SHO]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_CREPE_KF [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Isso se encaixaria perfeitamente em Lady[n]Ann...[n]É colorido e doce.[n][w][e]

[msg MSG_CREPE_KF_R [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7020 65535 0]Oh, estou surpreso que você saiba. Ann disse[n]que adora doces.[n][w][e]

[msg MND_COMMON_CHK_CLOTHES_S]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_CLOTHES_SHOP_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Eu acho que é isso que você chamaria de[n]roupas da moda. Por que você não[n]experimenta, [n][f 4 2]?[n][w][e]

[msg MSG_CLOTHES_SHOP_KF_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Hmm, não é realmente o meu estilo.[n][w][e]

[msg MND_COMMON_CHK_LOCKER]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_LOCKER_KF [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1177 65535 0]O grafite e os adesivos... acho que você não[n]pode mais abrir isso...[n][w][e]

[msg MSG_LOCKER_KF_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Hmm, não é realmente o meu estilo.[n][w][e]

[msg MND_COMMON_CHK_VELVET_DO]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_GAME_CENTER_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 0 0]Ei, você está procurando uma loja de armas...[n]O que é esse lugar, afinal?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]... Muitas pessoas estão usando óculos como[n]você. Devemos voltar mais tarde.[n][w][e]

[msg MSG_GAME_CENTER_KF_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Oh, eu vou a esse fliperama com bastante[n]frequência.[n]Vamos algum dia, [f 4 2].[n][w][e]

[msg MSG_GAME_CENTER_KF_01 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1192 0 0]Por que estamos no fliperama? Primeiro, você[n]precisa encontrar um lugar onde possa[n]vender essa medalha de ouro.[n][w][e]

[msg MSG_GAME_CENTER_KF_02 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1188 0 0]Ei, você não precisa estar no fliperama[n]agora. Por que não visitar outra hora?[n][w][e]

[msg MND_CHK_ITEM_SHOP]
[s][vp 8 2 65535 0 0 0]Esta deve ser a clínica com o charlatão que[n]prescreve medicamentos estranhos...[n][w][e]

[msg MND_CHK_WEAPON_SHOP]
[s][vp 8 2 65535 0 0 0]Parece a loja AirSoft que Ryuji mencionou...[n][w][e]

[msg MSG_KARAOKE_02_KF_01]
[s][vp 8 2 65535 0 0 0]Diz dentro da loja de karaokê que está[n]atualmente cheia...[n][w][e]

[msg MSG_KARAOKE_02_KF_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Que diabos? Quatrocentos ienes para cantar[n]por apenas meia hora? Sair na cidade pode[n]ficar caro.[n][w][e]

[msg MSG_GYUUDON_KF_01]
[s][vp 8 2 65535 0 0 0]É a loja de beliscões "Donburako". Há apenas[n]um funcionário, executando a loja sozinha.[n][w][e]
[s][vp 8 2 65535 0 0 0]Esse funcionário está se movendo com alguns[n]sérios [n][clr 1]Agilidade [clr 27]...[n][w][e]

[msg MSG_GYUUDON_KF_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Esta loja de beliscões é chamada[n]"Donburako". Apenas um funcionário aqui,[n]mas que incrível.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Você sabe, se você começou a trabalhar aqui,[n]poderá desenvolver seu [n][clr 1]Agilidade [clr 27].[n][w][e]

[msg MSG_IZAKAYA_KF_01]
[s][vp 8 2 65535 0 0 0]Há um izakaya nas costas.[n]Parece bastante lotado por dentro...[n][w][e]

[msg MSG_IZAKAYA_KF_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Oh, há um izakaya nas costas.[n]Eu acho que você pode ir quando tiver idade[n]suficiente.[n][w][e]

[msg MSG_FAMIRES_KF_01]
[s][vp 8 2 65535 0 0 0]Este lugar está cheio de estudantes e[n]casais. Este não é um bom lugar para matar[n]o tempo sozinho...[n][w][e]

[msg MSG_FAMIRES_KF_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Há tantos estudantes e casais aqui. Parece[n]muito solitário vir aqui sozinho, não é?[n][w][e]

[msg MSG_BERGER_KF_01]
[s][vp 8 2 65535 0 0 0]Big Bang Burger... sempre há comerciais para[n]este lugar, e estou ouvindo muito sobre[n]isso.[n][w][e]

[msg MSG_BERGER_KF_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Sempre há comerciais sobre este lugar, hein?[n][w][e]

[msg MSG_KFE_OPEN_SHOP_UNDER_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1175 0 0]A passarela subterrânea está à frente, mas a[n]loja que você deseja está na Central[n]Street, certo?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Vamos para aquele lugar no beco.[n][w][e]

[msg MSG_CINEMA_KF_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]O cinema, [clr 6]Cinema 7 [clr 27], hein?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Você provavelmente pode aprender algo[n]assistindo a um filme, mas não tem tempo[n]para isso agora.[n][w][e]

[msg MND_COMMON_MAIN_TRAINING]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[msg MSG_TRAINING_GIM_KF [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Oh, é uma... academia?[n][w][e]

[msg MSG_TRAINING_GIM_KF_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Ei, vamos lá. Estamos procurando uma loja de[n]armas, certo?[n][w][e]

[msg MND_COMMON_BookStore_Pan]
[s][vp 8 2 65535 0 0 0]Isso não é hora de desvios...[n][w][e]

[sel D_VELVET_IN_SEL top]
[s]Deixe-me entrar na célula.[e]
[s]Eu não quero entrar.[e]

[msg D_VELVET_IN_QUIET_01 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 12002 65535 0]Parece que você está muito preso.[n]Eu posso conceder esse desejo por você...[n][w][e]

[msg D_VELVET_IN_QUIET_OK [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Muito bem. Vou cumprir o seu desejo de bom[n]grado...[n][w][e]

[msg D_VELVET_IN_QUIET_NO [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]... Continue sua luta.[n][w][e]

[msg D_VELVET_IN_LOUD_01 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qual é o problema, preso? Você deseja voltar[n]para a prisão?[n][w][e]

[msg D_VELVET_IN_LOUD_OK [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Heheheh. Eu vou te colocar de volta onde[n]você pertence![n][w][e]

[msg D_VELVET_IN_LOUD_NO [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Continue lutando, preso.[n][w][e]

[msg D_VELVET_IN_LAST_01 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vou guiá-lo para o meu mestre...[n][w][e]

[sel D_VELVET_IN_LAST_SEL top]
[s]Eu quero me preparar.[e]
[s]Eu não quero entrar.[e]

[msg D_VELVET_IN_LAST_OK [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Então, por favor, digite.[n][w][e]

[msg D_VELVET_IN_LAST_NO [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Muito bem. Meu mestre e eu estaremos[n]cuidando de você.[n][w][e]

[msg MND_RankUp_OK_Chishiki]
[s]Eu me sinto como meu [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vai melhorar em breve...[n][w][e]

[msg MND_RankUp_NG_Chishiki]
[s]Eu não acho meu [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vai melhorar ainda...[n][w][e]

[msg MND_INC_PARAMCHK_L_TISIK]
[s]Parece que ainda tenho muito espaço para[n]melhorias...[n][w][e]

[msg MND_INC_PARAMCHK_M_TISIK]
[s]Eu posso sentir algo vindo para mim...[n][w][e]

[msg MND_INC_PARAMCHK_S_TISIK]
[s]Eu acho que estou perto de um avanço com o[n]meu [n][f 4 11 0][clr 26][f 4 12 0][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Miryoku]
[s]Eu me sinto como meu [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vai melhorar em breve...[n][w][e]

[msg MND_RankUp_NG_Miryoku]
[s]Eu não acho meu [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vai melhorar ainda...[n][w][e]

[msg MND_INC_PARAMCHK_L_MIRYO]
[s]Parece que ainda tenho muito espaço para[n]melhorias...[n][w][e]

[msg MND_INC_PARAMCHK_M_MIRYO]
[s]Eu posso sentir algo vindo para mim...[n][w][e]

[msg MND_INC_PARAMCHK_S_MIRYO]
[s]Eu acho que estou perto de um avanço com o[n]meu [n][f 4 11 1][clr 26][f 4 12 1][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Kiyou]
[s]Eu me sinto como meu [f 4 11 2][clr 26][f 4 12 2][clr 27][n]vai melhorar em breve...[n][w][e]

[msg MND_RankUp_NG_Kiyou]
[s]Eu não acho meu [f 4 11 2][clr 26][f 4 12 2][clr 27][n]vai melhorar ainda...[n][w][e]

[msg MND_RankUp_OK_Kiyou_Beef]
[s]Se as coisas correrem bem, acho que meu [n][f 4 11 1][clr 26][f 4 12 1][clr 27]Pode melhorar...[n][w][e]

[msg MND_INC_PARAMCHK_L_KIYOU]
[s]Parece que ainda tenho muito espaço para[n]melhorias...[n][w][e]

[msg MND_INC_PARAMCHK_M_KIYOU]
[s]Eu posso sentir algo vindo para mim...[n][w][e]

[msg MND_INC_PARAMCHK_S_KIYOU]
[s]Eu acho que estou perto de um avanço com o[n]meu [n][f 4 11 2][clr 26][f 4 12 2][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Dokyo]
[s]Eu me sinto como meu [f 4 11 3][clr 26][f 4 12 3][clr 27][n]vão melhorar em breve...[n][w][e]

[msg MND_RankUp_NG_Dokyo]
[s]Eu não acho meu [f 4 11 3][clr 26][f 4 12 3][clr 27][n]vai melhorar ainda...[n][w][e]

[msg MND_INC_PARAMCHK_L_DOKYO]
[s]Parece que ainda tenho muito espaço para[n]melhorias...[n][w][e]

[msg MND_INC_PARAMCHK_M_DOKYO]
[s]Eu posso sentir algo vindo para mim...[n][w][e]

[msg MND_INC_PARAMCHK_S_DOKYO]
[s]Eu acho que estou perto de um avanço com o[n]meu [n][f 4 11 3][clr 26][f 4 12 3][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Yasasisa]
[s]Eu me sinto como meu [f 4 11 4][clr 26][f 4 12 4][clr 27][n]vai melhorar em breve...[n][w][e]

[msg MND_RankUp_NG_Yasasisa]
[s]Eu não acho meu [f 4 11 4][clr 26][f 4 12 4][clr 27][n]vai melhorar ainda...[n][w][e]

[msg MND_RankUp_OK_Yasasisa_F]
[s]Se as coisas correrem bem, acho que meu [n][f 4 11 4][clr 26][f 4 12 4][clr 27]Pode melhorar...[n][w][e]

[msg MND_INC_PARAMCHK_L_YASAS]
[s]Parece que ainda tenho muito espaço para[n]melhorias...[n][w][e]

[msg MND_INC_PARAMCHK_M_YASAS]
[s]Eu posso sentir algo vindo para mim...[n][w][e]

[msg MND_INC_PARAMCHK_S_YASAS]
[s]Eu acho que estou perto de um avanço com o[n]meu [n][f 4 11 4][clr 26][f 4 12 4][clr 27]...[n][w][e]

[msg MSG_CinemaBuyTicketSIBUY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1179 65535 0]Oh sim! Você precisa comprar um ingresso[n]primeiro.[n][w][e]

[msg MSG_CinemaCancel [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1003 65535 0]O que, você mudou de idéia?[n][w][e]

[msg MSG_CinemaOK [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Está quase na hora do filme começar.[n]Vamos nos sentar.[n][w][e]

[msg MSG_CinemaWatched [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1177 65535 0][var 7]? Eu acho que você já teve o suficiente[n]disso...[n]Vamos voltar outra vez.[n][w][e]

[msg MSG_CinemaBuyTicket [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1157 65535 0]Você precisará comprar um ingresso se quiser[n]ver um filme.[n][w][e]

[msg MND_ParamEndInfo_Atama]
[s]Eu acho que tenho o suficiente [n][f 4 11 0][clr 26][f 4 12 0][clr 27]já...[n][w][e]

[msg MND_ParamEndInfo_Miryoku]
[s]Eu acho que tenho o suficiente [n][f 4 11 1][clr 26][f 4 12 1][clr 27]já...[n][w][e]

[msg MND_ParamEndInfo_Kiyou]
[s]Eu acho que tenho o suficiente [n][f 4 11 2][clr 26][f 4 12 2][clr 27]já...[n][w][e]

[msg MND_ParamEndInfo_Dokyo]
[s]Eu acho que tenho o suficiente [n][f 4 11 3][clr 26][f 4 12 3][clr 27]já...[n][w][e]

[msg MND_ParamEndInfo_Yasas]
[s]Eu acho que tenho o suficiente [n][f 4 11 4][clr 26][f 4 12 4][clr 27]já...[n][w][e]

[msg MSG_ParamMoru_Atama [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Hmm... parece que este filme pode te ensinar[n]como melhorar seu [n][f 4 11 0][clr 26][f 4 12 0][clr 27].[n][w][e]

[msg MSG_ParamMoru_Miryoku [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Hmm... parece que este filme pode te ensinar[n]como melhorar seu [n][f 4 11 1][clr 26][f 4 12 1][clr 27].[n][w][e]

[msg MSG_ParamMoru_Kiyou [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Hmm... parece que este filme pode te ensinar[n]como melhorar seu [n][f 4 11 2][clr 26][f 4 12 2][clr 27].[n][w][e]

[msg MSG_ParamMoru_Dokyo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Hmm... parece que este filme pode te ensinar[n]como melhorar seu [n][f 4 11 3][clr 26][f 4 12 3][clr 27].[n][w][e]

[msg MSG_ParamMoru_Yasas [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Hmm... parece que este filme pode te ensinar[n]como melhorar seu [n][f 4 11 4][clr 26][f 4 12 4][clr 27].[n][w][e]

[msg MSG_CINEMA_1ST_ACCESS_SI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Eu me pergunto o que eles estão mostrando[n]agora...[n][w][e]

[msg MSG_Cinema_MoneyNG [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Verifique sua carteira... você não tem[n]dinheiro suficiente para isso.[n][w][e]

[msg MSG_CINEMA_MEMBER_NG [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1112 65535 0]Quantas vezes você quer ver o mesmo filme?[n]Apenas dê um descanso...[n][w][e]

[msg MSG_CINEMA_1ST_ACCESS_SI_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Uau, esse teatro é enorme![n]Eu me pergunto o que eles estão mostrando.[n][w][e]

[msg MSG_CINEMA_NOT_OPEN [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Isso deveria ser um cinema, certo? Ninguém[n]está aqui... eu me pergunto se está fechado.[n][w][e]

[msg MND_CINEMA_NOT_OPEN]
[s]O cinema parece estar fechado agora...[n][w][e]

[msg MSG_CINEMA_NOT_OPEN02 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Não há ninguém por perto. Parece que eles[n]também não estão abertos à noite, então o[n]que está acontecendo?[n][w][e]

[msg MSG_CINEMA_BOOK [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Desde que você terminou de ler [n][clr 3]O ofício do cinema [clr 27]Aposto que você apreciará este filme ainda[n]mais.[n][w][e]

[msg MSG_COMMENT_LIST01_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É uma história sobre um adolescente que se[n]torna o "Milionário Tanktop" com dinheiro[n]que ganhou em um programa de perguntas...[n][w][e]

[msg MSG_COMMENT_2ndINFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Ah, é [var 7].[n]Quer ver de novo?[n][w][e]

[msg MSG_COMMENT_LIST02_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É uma história sobre um herói de capa[n]tentando derrubar uma floresta negra de[n]crime e corrupção.[n][w][e]

[msg MSG_COMMENT_LIST03_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É uma história sobre um homem que luta para[n]contar à mulher que ama como ele realmente[n]se sente.[n][w][e]

[msg MSG_COMMENT_LIST04_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É a história de um homem que tenta recuperar[n]sua vida depois de passar muito tempo na[n]prisão.[n][w][e]

[msg MSG_COMMENT_LIST05_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É a história de um homem que é forçado a[n]invadir seu apartamento seguro para obter[n]sua chave sobressalente.[n][w][e]

[msg MSG_COMMENT_LIST06_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É a história de um homem que foi designado[n]para limpar um enorme arranha-céu no dia de[n]Natal.[n][w][e]

[msg MSG_COMMENT_LIST14_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É a história de um pai vespa que viaja com[n]seu amigo de abelha para resgatar seu filho[n]que foi sequestrado por humanos.[n][w][e]

[msg MSG_COMMENT_LIST07_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É a história de um gato de robô que aluga[n]ferramentas úteis, mas cobra um prêmio alto[n]por seus serviços.[n][w][e]

[msg MSG_COMMENT_LIST08_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]O dinheiro desaparece, o chefe é morto e o[n]sangue percorre as ruas de Tóquio...[n][w][e]

[msg MSG_COMMENT_LIST09_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É a história das pessoas mais inúteis do[n]mundo formando uma equipe para combater[n]alienígenas.[n][w][e]

[msg MSG_COMMENT_LIST10_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É a história de dois homens presos em uma[n]sala com um elefante extremamente furioso.[n]Eles vão sobreviver...?[n][w][e]

[msg MSG_COMMENT_LIST15_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É a história de um homem com insônia que[n]desce para loucura após uma reunião em uma[n]certa loja de kebab.[n][w][e]

[msg MSG_COMMENT_LIST11_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É uma história trágica sobre um chefe da[n]Máfia que só quer afundar seus filhos.[n][w][e]

[msg MSG_COMMENT_LIST12_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É sobre um cara que volta no tempo para[n]aprender Ninjutsu e vingar seu amigo que[n]foi morto por um ninja.[n][w][e]

[msg MSG_COMMENT_LIST13_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É uma história sobre prisioneiros de guerra[n]que são forçados a fazer um trabalho[n]cansativo, mesmo que seja Natal.[n][w][e]

[msg MSG_COMMENT_LIST16_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É a história de uma pastora que se une a um[n]psiquiatra que amava o carneiro para pegar[n]um cisalheiro em série.[n][w][e]

[msg MSG_COMMENT_LIST17_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É a história de um estudante universitário[n]que se muda para um dormitório oprimido e[n]luta para libertar os outros pensionistas.[n][w][e]

[msg MSG_COMMENT_LIST18_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]No momento, estamos bem a tempo de ver [var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]É a história de um homem que acidentalmente[n]se junta ao circo, mas depois se levanta no[n]mundo através de seu próprio charme.[n][w][e]

[msg MND_Sentou_ParamInfo_Chi]
[s]Parece que assistir a este filme pode me dar[n]um pouco [n][f 4 11 0][clr 26][f 4 12 0][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo_]
[s]Mesmo se eu assistir a este filme, acho que[n]não vou conseguir mais [n][f 4 11 0][clr 26][f 4 12 0][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Dok]
[s]Parece que assistir a este filme pode me dar[n]um pouco [n][f 4 11 3][clr 26][f 4 12 3][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__2]
[s]Mesmo se eu assistir a este filme, acho que[n]não vou conseguir mais [n][f 4 11 3][clr 26][f 4 12 3][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Yas]
[s]Parece que assistir a este filme pode me dar[n]um pouco [n][f 4 11 4][clr 26][f 4 12 4][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__3]
[s]Mesmo se eu assistir a este filme, acho que[n]não vou conseguir mais [n][f 4 11 4][clr 26][f 4 12 4][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Iro]
[s]Parece que assistir a este filme pode me dar[n]um pouco [n][f 4 11 1][clr 26][f 4 12 1][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__4]
[s]Mesmo se eu assistir a este filme, acho que[n]não vou conseguir mais [n][f 4 11 1][clr 26][f 4 12 1][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Kiy]
[s]Parece que assistir a este filme pode me dar[n]um pouco [n][f 4 11 2][clr 26][f 4 12 2][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__5]
[s]Mesmo se eu assistir a este filme, acho que[n]não vou conseguir mais [n][f 4 11 2][clr 26][f 4 12 2][clr 27].[n][w][e]

