[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_COSTUME_01]
[s]Figurino 1 Explicação [n][w][e]

[msg MSG_COSTUME_02]
[s]Figurino 2 Explicação [n][w][e]

[msg MSG_COSTUME_03]
[s]Figurino 3 Explicação [n][w][e]

[msg MSG_COSTUME_DEFAULT]
[s]Explicação de roupas padrão [n][w][e]

[msg MND_NG_GOTO2F_1F_000_00]
[s]Eu deveria dormir para que estou pronto para[n]amanhã...[n][w][e]

[msg MSG_NG_GOTO2F_1F_0411_00]
[s]Meu corpo parece pesado... eu provavelmente[n]deveria dormir durante o dia.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0412_00]
[s]Meu corpo parece pesado... eu provavelmente[n]deveria dormir durante o dia.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0413_00]
[s]Já estou cansado hoje...[n]Eu provavelmente deveria dormir em breve.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0414_00]
[s]Estou me sentindo muito esgotado...[n]Eu provavelmente deveria dormir logo.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0415_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53115 65535 0]Você deve estar cansado do metaverso.[n]Vamos dormir.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0416_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53115 65535 0]Você não vai para Shibuya amanhã?[n]Vamos chamá-lo um dia e dormir.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0417_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Não adianta ignorá-lo. Já limpe a mesa.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0504_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Onde você está indo? Amanhã é a festa, sabe?[n][w][e]

[msg MSG_NG_GOTO2F_1F_0505_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 53115 65535 0]Você não tem escola de novo amanhã?[n]Estou cansado, então vamos encerrar o dia e[n]dormir.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0507_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Você não está cansado depois de ir a[n]lembranças?[n]Vamos dormir já.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0513_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53116 65535 0]Está tarde. Vamos dormir.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0514_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Você não pode sair outra vez?[n]Você deve descansar depois de acabar de[n]terminar seus exames.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0515_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53115 65535 0]Nossa investigação sobre Madarame começa[n]amanhã, sabe? Vamos encerrar um dia e[n]dormir.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0516_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Você não está cansado depois de ir ao[n]palácio hoje? Vamos dormir já.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0517_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Você deve garantir que seu corpo descanse o[n]suficiente. Estamos começando nossos planos[n]amanhã, sabe?[n][w][e]

[msg MSG_NG_GOTO2F_1F_0710_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Exames antes dos fogos de artifício, não é?[n]Você deve ligar para o dia e dormir para[n]poder trabalhar mais amanhã.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0716_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 53116 65535 0]Agora que os exames acabaram, podemos[n]descansar uma boa noite... vamos dormir.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0723_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53115 65535 0]Temos uma festa na loja de sushi amanhã,[n]sabe? Vamos encerrar um dia e dormir.[n][w][e]

[msg MND_NG_GOTO2F_1F_0724_00]
[s][vp 8 2 65535 0 0 0]Morgana ainda não está de volta.[n]Gostaria de saber se ele acabará voltando se[n]eu esperar por ele.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0821_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Vamos ficar parados, ligue para o dia e vá[n]dormir.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0831_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Você não tem escola de novo amanhã?[n]Vamos dormir cedo para que você não acorde[n]tarde.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1003_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 53116 65535 0]Com a coisa de Yoshizawa e tudo o mais que[n]aconteceu hoje, estou vencido...[n]Vamos dormir.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1011_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 53116 65535 0]Vamos dormir por enquanto e verificar o[n]status novamente amanhã.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1012_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Não sabemos quando podemos receber uma[n]ligação de Haru, então vamos ficar parados[n]hoje.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1020_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Você está com vontade de sair?[n]Vamos ficar parados hoje.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1026_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Que dia louco tem sido...[n]Vamos dormir um pouco.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1121_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]O chefe está certo, você realmente deve[n]garantir que seu corpo descanse um pouco[n]para o dia.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1123_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Estaremos procurando a palavra-chave[n]novamente amanhã. Você deve dormir um pouco.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1124_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Estaremos trabalhando a todo vapor a partir[n]de amanhã. Por hoje, você deve descansar um[n]pouco.[n][w][e]

[msg MSG_NG_GOTO2F_1F_000_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53115 65535 0]Vamos encerrar um dia e ir para a cama.[n][w][e]

[msg MSG_NG_GOTO2F_1F_DNG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53116 65535 0]Você não está cansado hoje?[n]Vamos dormir já.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0202_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Maruki está finalmente chegando. Você está[n]mentalmente preparado?[n][w][e]

[sel SEL_NG_GOTO2F_1F_0202_00 top]
[s]Eu preciso de mais tempo.[e]
[s]Vamos.[e]

[msg MSG_NG_GOTO2F_1F_0202_01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sim, você nunca sabe o que pode acontecer...[n]devemos ser cautelosos.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0202_02 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No entanto, você responde a Maruki, eu[n]confio em você. Eu sei que você tomará a[n]decisão certa.[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_04 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]Não estou deixando você ir para a cama até[n]limpar essa mesa![n][w][e]

[msg MSG_NG_GOTO2F_1F_COMMON_ [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ei, você não está cansado? Vamos dormir para[n]que estamos prontos amanhã.[n][w][e]

[msg MND_NG_GOTO2F_1F_COMMON_]
[s]Eu deveria dormir para que estou pronto para[n]amanhã...[n][w][e]

[msg MSG_LAST_GREETING_MY_Bed [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53116 65535 0]Vamos dormir...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1036 65535 0]Não, espere! Temos que ir dizer adeus a[n]todos![n][w][e]

[msg MSG_LAST_GREETING_MY_Sof [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Esta não é a hora de sentar e relaxar.[n]Vamos dizer adeus a todos![n][w][e]

[msg MSG_LAST_GREETING_MY_Clo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Temos que fazer as malas depois que dizemos[n]a todos, então não vá bagunçar agora.[n][w][e]

[msg MSG_LAST_GREETING_MY_Des [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Minhas receitas também o ajudaram, não é?[n][w][e]

[msg MSG_LAST_GREETING_MY_Tab [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Esta TV era uma verdadeira peça de lixo, mas[n]com certeza fez o trabalho.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Tenho boas lembranças de todas as vezes que[n]assistimos a DVDs juntos.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Eu realmente gostei de ver você jogar esses[n]jogos também.[n][w][e]

[msg MSG_LAST_GREETING_MY_Tab_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Esta TV era uma verdadeira peça de lixo, mas[n]com certeza fez o trabalho.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Tenho boas lembranças de todas as vezes que[n]assistimos a DVDs juntos.[n][w][e]

[msg MSG_LAST_GREETING_MY_Tab_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Esta TV era uma verdadeira peça de lixo, mas[n]com certeza fez o trabalho.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Eu realmente gostei de ver você jogar esses[n]jogos.[n][w][e]

[msg MSG_LAST_GREETING_MY_Tab_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Por que você está espaçado?[n]Vamos dizer adeus a todos.[n][w][e]

[msg MSG_LAST_GREETING_MY_She [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Você fez tantas lembranças nesta cidade...[n]lembre-se de fazer as malas e levá-las com[n]você quando partir.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Por enquanto, vamos ver todos.[n][w][e]

[msg MSG_LAST_GREETING_MY_She_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]Você terminou de limpar, certo?[n]Vamos ver todos.[n][w][e]

[msg MSG_LAST_GREETING_Chair_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]O fato de você estar saudável o ano inteiro[n]pode ser por causa de todo o treinamento.[n][w][e]

[msg MSG_LAST_GREETING_Chair [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Agora não é hora de começar a treinar![n]Vamos dizer tchau para todos![n][w][e]

[msg MSG_LAST_GREETING_FloorO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Essas plantas parecem saudáveis graças a[n]você. Tenho certeza de que eles estarão em[n]boas mãos com o chefe.[n][w][e]

[msg MSG_LAST_GREETING_FloorO_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Ei, o que há de errado? Não vamos dizer[n]adeus a todos?[n][w][e]

[msg MSG_LAST_GREETING_Stove [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]... Ei, você se lembra da primeira vez que[n]demitimos isso?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Muita coisa aconteceu desde então...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Mas foi graças a essa coisa que sobrevivemos[n]ao inverno. Não poderíamos ter pedido uma[n]mão de palco melhor.[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Você não precisa estar aqui agora, não é?[n]Vamos lá, vamos para outro lugar![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Qual é o problema? Vamos dizer tchau para[n]todos![n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9178 65535 0]Já está tão tarde...[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10_2 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9176 65535 0]Sojiro ainda está acordado?[n][w][e]
[s][f 4 10 65535 0 0]Isso é meio estranho...[n][w][e]

[sel SEL_BED_MORGANA_NIGHT_10 top]
[s]Vá para casa ou ele vai se preocupar.[e]
[s]Você pode dormir no sofá.[e]

[msg MSG_BED_MORGANA_NIGHT_10_3 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Espere, você não deveria dormir no sofá,[n]para que Futaba possa ir em frente e dormir[n]na cama?[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10_4 [Futaba]]
[s][bup 0 8 3 65535 0]......[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10_5 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9195 65535 0][f 4 23 1 65535 4 10 0 0]... eu vou para casa.[n][w][e]
[s][f 4 10 65535 0 0]Noite.[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_02 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Maruki finalmente está aqui...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Não se preocupe, [f 4 2].[n]Eu vou ficar com você.[n][w][e]

[msg Sofa_CHECK_NG_0409_mes00]
[s]Este sofá está coberto de poeira...[n][w][e]
[s]Parece que ainda posso usá-lo, mas terei que[n]limpá-lo primeiro...[n][w][e]

[msg Sofa_CHECK_NG_0409_mes01]
[s]Este sofá está coberto de poeira...[n][w][e]
[s]Parece que ainda posso usá-lo, mas terei que[n]limpá-lo primeiro...[n][w][e]

[msg Sofa_CHECK_NG_0409_mes02]
[s]O sofá foi limpo, então agora as pessoas[n]podem sentar nele novamente.[n][w][e]

[msg MSG_DESK_NOTCLEAN]
[s]Existem pilhas de livros nesta mesa...[n][w][e]

[msg MSG_DESK_NOTCLEAN_MONA_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Essa mesa parece que pode ser bastante[n]útil...[n][w][e]
[s][f 4 10 65535 0 0]Mas você pode limpá-lo mais tarde. Por[n]enquanto, vamos encerrar o dia e dormir um[n]pouco.[n][w][e]

[msg MSG_DESK_NOTCLEAN_MONA_0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Essa mesa parece que pode ser bastante[n]útil...[n][w][e]
[s][f 4 10 65535 0 0]Mas você pode limpá-lo mais tarde. Por[n]enquanto, vamos encerrar o dia e dormir um[n]pouco.[n][w][e]

[msg MSG_DESK_TUTORIAL_MONA_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Tudo bem, por que não lhe dou uma palestra[n]sobre ferramentas de infiltração?[n][w][e]

[msg MSG_ITEM_MAKE_STANDBY [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]Você vai fazer uma ferramenta de infiltração[n]para amanhã? Boa ideia.[n][w][e]

[msg MSG_Desk_ActNgNight [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Não vamos fazer isso hoje.[n][w][e]

[msg MND_Desk_ActNgNight]
[s]Eu deveria dormir hoje para estar pronto[n]para amanhã...[n][w][e]

[msg MSG_Desk_ActNgNight_0716 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1177 65535 0]Você pode se concentrar em fazer ferramentas[n]de infiltração? Eu acho que você está[n]cansado de exames. Vamos dormir.[n][w][e]

[msg MSG_Desk_ActNgNight_0831 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Você não tem escola de novo amanhã?[n]Vamos dormir cedo para que você não acorde[n]tarde.[n][w][e]

[msg MSG_NG_Desk_ActNgNight_1 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Há muito em minha mente, não posso me[n]concentrar... vamos fazer ferramentas de[n]infiltração em outra época.[n][w][e]

[msg MSG_NG_Desk_ActNgNight_1_2 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1037 65535 0]Droga, estou pensando em círculos...[n]Não posso me concentrar hoje, então vou[n]dormir.[n][w][e]

[msg FLOOR_CLEAN_mes00]
[s]Existem todos esses itens domésticos não[n]utilizados aqui.[n]Não está organizado...[n][w][e]

[msg MSG_FLOOR_NOT_CLEAN_MONA [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Esta é definitivamente uma área de[n]armazenamento...[n][w][e]

[msg MSG_MY_DELI_BOX_DEFAULT_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Que caixa de papelão enorme- oh, essas são[n]suas coisas lá...[n][w][e]

[msg MSG_MY_DELI_BOX_0417_MOR [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Espere, quem se importa com isso! Apresse-se[n]e limpe a mesa![n][w][e]

[msg MSG_MY_DELI_BOX_DEFAULT]
[s]É a caixa de papelão enviada de volta para[n]casa...[n][w][e]
[s]Tem algumas roupas extras e necessidades[n]diárias por dentro.[n][w][e]

[msg MSG_MY_DELI_BOX_TEST]
[s](TEST)[n]O que devo fazer?[n][w][e]

[sel SEL_MY_DELI_BOX_TEST top]
[s]Vou adquirir uma nova fantasia.[e]
[s]Vou trocar de roupa.[e]

[msg MSG_GET_COSTUME_TEST]
[s](TEST)[n]Qual fantasia devo adquirir?[n][w][e]

[sel SEL_GET_COSTUME_TEST top]
[s]Yasogami Uniforme [e]
[s]Uniforme Gekkoukan [e]
[s]Sete irmãs uniformes [e]
[s]Uniforme de St. Hermelin [e]
[s]Uniforme de Karukozaka [e]
[s]Roupa de Catherine [e]
[s]Roupas da vida estudantil [e]
[s]Maiôs [e]
[s]Roupas de empregada doméstica e mordomo [e]
[s]Roupas de férias [e]

[msg MSG_ALREADY_GET_COSTUME_]
[s]Eu já tenho esse.[n][w][e]

[sel SEL_MY_DELI_BOX top]
[s]Mudança de roupa 1 [e]

[msg MSG_MY_DELI_BOX_COSTUME_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Reação quando você muda 1 [n][w][e]

[msg MSG_MY_DELI_BOX_COSTUME__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Reação quando você muda 2 [n][w][e]

[msg MSG_MY_DELI_BOX_COSTUME__3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Reação quando você muda 3 [n][w][e]

[msg MSG_MY_DELI_BOX_COSTUME__4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Roupas padrão [n][w][e]

[msg SYSTEM_GET_COSTUME_P4]
[s]Eu adquiri o uniforme Yasogami.[n][w][e]

[msg SYSTEM_GET_COSTUME_P3]
[s]Eu adquiri o uniforme Gekkoukan.[n][w][e]

[msg SYSTEM_GET_COSTUME_P2]
[s]Eu adquiri o uniforme das sete irmãs.[n][w][e]

[msg SYSTEM_GET_COSTUME_IBUNR]
[s]Eu adquiri o uniforme de St. Hermelin.[n][w][e]

[msg SYSTEM_GET_COSTUME_IF]
[s]Eu adquiri o uniforme Karukozawa.[n][w][e]

[msg SYSTEM_GET_COSTUME_P4D]
[s]Eu adquiri a roupa P4D.[n][w][e]

[msg SYSTEM_GET_COSTUME_P4U]
[s]Eu adquiri a roupa P4U.[n][w][e]

[msg SYSTEM_GET_COSTUME_MEGAM]
[s]Eu adquiri a roupa Shin Megami Tensei.[n][w][e]

[msg SYSTEM_GET_COSTUME_RAIDO]
[s]Eu adquiri a roupa Raido Kuzunoha.[n][w][e]

[msg SYSTEM_GET_COSTUME_CATHE]
[s]Eu adquiri a roupa de um adulto perdido.[n][w][e]

[msg SYSTEM_GET_COSTUME_P5]
[s]Adquiri algumas roupas pessoais, uniformes[n]escolares, uniformes de ginástica e[n]loungewear para a vida como estudante.[n][w][e]

[msg SYSTEM_GET_COSTUME_SWIM]
[s]Eu adquiri alguns trajes de banho.[n][w][e]

[msg SYSTEM_GET_COSTUME_BUTLE]
[s]Eu adquiri algumas roupas de empregada e[n]mordomo.[n][w][e]

[msg SYSTEM_GET_COSTUME_XMAS]
[s]Eu adquiri algumas roupas de férias.[n][w][e]

[msg SYSTEM_GET_ITEM_NG]
[s]Este item atingiu seu limite máximo de[n]espera, para que você não possa mais[n]receber.[n][w][e]

[msg SYSTEM_GET_PERSONA_ORPHE]
[s]Eu adquiri Orfeu.[n][w][e]

[msg SYSTEM_GET_PERSONA_IZANA]
[s]Eu adquiri Izanagi.[n][w][e]

[msg SYSTEM_GET_PERSONA_THANA]
[s]Eu adquiri Thanatos.[n][w][e]

[msg SYSTEM_GET_PERSONA_MAGAT]
[s]Eu adquiri Magatsu Izanagi.[n][w][e]

[msg SYSTEM_GET_PERSONA_KAGUY]
[s]Eu adquiri Kaguya.[n][w][e]

[msg SYSTEM_GET_PERSONA_ARIAD]
[s]Eu adquiri Ariadne.[n][w][e]

[msg SYSTEM_GET_PERSONA_ASTER]
[s]Eu adquiri Asterius.[n][w][e]

[msg SYSTEM_GET_PERSONA_TUKIY]
[s]Eu adquiri Tsukiyomi.[n][w][e]

[msg SYSTEM_GET_PERSONA_MESSI]
[s]Eu adquiri o Messias.[n][w][e]

[msg SYSTEM_GET_ITEM_START01]
[s]Eu adquiri um conjunto de itens de cura.[n][w][e]

[msg SYSTEM_GET_ITEM_START02]
[s]Eu adquiri um conjunto de cartões de[n]habilidade.[n][w][e]

[msg MSG_WASHBOX_NOTOPEN]
[s]Há poeira coletando na cesta de lavanderia...[n][w][e]
[s]É isso mesmo, havia uma lavanderia na casa[n]de banho nas proximidades...[n][w][e]

[msg MSG_WASHBOX_NOTOPEN_MONA [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]... Ugh, essa cesta de lavanderia certamente[n]está em um estado lamentável.[n][w][e]
[s][f 4 10 65535 0 0]Venha para pensar sobre isso, não havia uma[n]lavanderia na casa de banho perto aqui?[n][w][e]

[msg MSG_SHELF_NOTCLEAN]
[s]Um monte de livros foi empurrado[n]descuidadamente nessas prateleiras...[n][w][e]

[msg MSG_SHELF_NOTCLEAN_MONA [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]É tão desarrumado. Os livros estão até[n]saindo das prateleiras...[n][w][e]

[msg MSG_Shelf_NotCleanThink_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Deveríamos realmente fazer uma limpeza...[n]mas precisamos fazê-lo outra hora.[n][w][e]

[msg MSG_TABLE_CleanEnd_Notin [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Essas prateleiras enormes são legais e[n]tudo...[n][w][e]
[s][f 4 10 65535 0 0]Seria melhor, porém, se tivéssemos algo para[n]colocar neles...[n][w][e]

[msg MND_TABLE_CleanEnd_Notin]
[s]As prateleiras estão vazias...[n][w][e]

[msg MSG_StopAct_CleanEnd_100 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Não precisamos arrumar as prateleiras agora,[n]não é? Devemos descansar um pouco.[n][w][e]

[msg MSG_TABLE_NOTCLEAN]
[s]Esta é uma pilha de revistas muito alta...[n][w][e]

[msg MSG_CatBed_1ST [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0]HM, desde que você se esforçou para comprar[n]isso, acho que vou começar a dormir aqui.[n][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Onde eu tenho dormido até agora?[n]... às vezes em cima de você.[n][w][e]

[msg MSG_CatBed_Common [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Agora, agora, não fique bravo.[n][w][e]

[msg MND_CatBed]
[s]É uma cama que comprei para Morgana...[n][w][e]

[msg MND_FloorObj_Plant_FIRST]
[s]Esta planta decorativa parece muito sem[n]vida...[n][w][e]

[msg MONA_FloorObj_Plant_FIRS [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Nós pensamos que ficaria bem aqui, mas[n]parece um pouco morto...[n][w][e]

[msg MONA_FloorObj_Plant_NoIt [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Eles não vendem nutrientes ou algo que trará[n]alguma cor de volta a ele?[n][w][e]

[msg MND_FloorObj_Plant_NoIte]
[s]Eu me pergunto se esta planta ficará mais[n]viva se eu der alguns nutrientes...[n][w][e]

[msg MONA_FloorObj_Plant_NoIt_2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 1026 65535 0]Você não tem nutrientes vegetais?[n]Comecei a ficar melhor também...[n][w][e]

[msg MND_FloorObj_Plant_NoIte_2]
[s]Eu não tenho nutrientes vegetais...[n][w][e]

[msg MONA_FloorObj_Plant_NG [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Parece bastante saudável por enquanto.[n][w][e]

[msg MND_FloorObj_Plant_NG]
[s]Esta planta parece bastante vibrante e[n]saudável por enquanto...[n][w][e]

[msg MONA_FloorObj_Plant_UseI [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Venha para pensar sobre isso, você comprou[n]alguns nutrientes vegetais, certo? Por que[n]você não tenta usá-los?[n][w][e]

[msg MND_FloorObj_Plant_UseIt]
[s]Está certo, eu tenho algo que posso usar...[n][w][e]

[msg MONA_FloorObj_Plant_UseI_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Você não deveria dar alguns nutrientes[n]vegetais agora?[n][w][e]

[msg MND_FloorObj_Plant_UseIt_2]
[s]Parece que eu deveria dar mais alguns[n]nutrientes...[n][w][e]

[msg MONA_FloorObj_Plant_UseI_3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Estes são baratos, mas é muito melhor do que[n]não dar nada...[n][w][e]

[msg MONA_FloorObj_Plant_UseI_4 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Estes são alguns nutrientes com preços[n]razoáveis. Isso deve trazer um pouco de[n]vida de volta a esta planta![n][w][e]

[msg MONA_FloorObj_Plant_UseI_5 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Você vai usar isso!? Você deve realmente se[n]preocupar com esta planta![n][w][e]

[msg MND_FloorObj_Plant_UseIt_3]
[s]Eu sinto que esta planta ficou um pouco mais[n]saudável...[n][w][e]

[msg MONA_FloorObj_Plant_UseI_6 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1181 65535 0]Isso deve fazer isso por um tempo![n][w][e]

[msg MND_FloorObj_Plant_UseIt_4]
[s]Isso deve ser suficiente por um tempo...[n][w][e]

[msg MSG_SUGGEST_CLEAN_MONA_0 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Ugh, nossa... não é fácil relaxar nesta[n]sala...[n][w][e]

[msg MSG_SUGGEST_CLEAN_MONA_0_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Estou surpreso que você possa morar aqui.[n][w][e]

[msg MSG_SUGGEST_CLEAN_MONA_0_3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Depois de encontrarmos perspectivas de[n]aquisição de armas, devemos limpar esta[n]sala...[n][w][e]

[msg MSG_SUGGEST_CLEAN_MONA_0_4 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Esqueça essa área por enquanto. Devemos[n]limpar a mesa primeiro.[n][w][e]

[msg MSG_SUGGEST_CLEAN_MONA_0_5 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Não, não lá, a mesa.[n][w][e]

[msg MSG_SUGGEST_CLEAN_MONA_0_6 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Não aquela mesa. Aquele nas costas.[n][w][e]

[msg MSG_SUGGEST_CLEAN_TABLE_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]Aquela mesa. Apresse-se agora e limpe-o.[n][w][e]

[sel SEL_SUGGEST_CLEAN_TABLE_ top]
[s]Vamos limpar isso.[e]
[s]Eu não estou no clima.[e]

[msg MSG_SUGGEST_CLEAN_TABLE__2 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Não diga isso. Vamos, eu vou te ensinar como[n]fazer ferramentas de infiltração...[n][w][e]

[msg MSG_SUGGEST_CLEAN_TABLE__3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]Ótimo, agora você pode fazer coisas sempre[n]que quiser![n][w][e]

[msg TUTORIAL_TOOL]
[s]Agora você pode criar ferramentas de[n]infiltração nesta mesa de trabalho.[n][w][e]

[msg MSG_Shelf_NotCleanThink [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Você sente vontade de limpar agora?[n][w][e]

[msg MSG_Shelf_Clean_Now [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1162 65535 0]Política, lei e filosofia... tudo isso soa[n]como alguns livros muito difíceis...[n][w][e]
[s][f 4 10 65535 0 0]Oh! Talvez você pudesse ler este![n][w][e]

[msg MSG_Shelf_Clean_End [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Eu me pergunto por que este está misturado[n]com todos esses livros difíceis...[n][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Bem, suponho que isso não importa.[n][w][e]

[msg MSG_Shelf_Clean_GetBook0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1162 65535 0]Política, lei e filosofia... tudo isso soa[n]como alguns livros muito difíceis...[n][w][e]
[s][f 4 10 65535 0 0]Pegue um, pelo menos. Um pouco de esforço[n]vai percorrer um longo caminho.[n][w][e]

[msg MSG_Shelf_Clean_GetBook0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 10 65535 0 0]Pegue isso também. Deve ser uma leitura[n]fácil, certo?[n][w][e]

[msg MSG_Shelf_Clean_Continue [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Esta é uma boa oportunidade.[n][w][e]
[s][f 4 10 65535 0 0]O chão ali também está muito bagunçado.[n]Vamos limpar tudo enquanto estamos nisso![n][w][e]

[msg MND_Shelf_NotCleanThink]
[s]Essas prateleiras estão tão repletas de[n]livros, alguns deles estão saindo...[n][w][e]

[msg MSG_Clean_DayEnd_1 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Esta sala parece um pouco mais confortável[n]agora...[n][w][e]
[s][f 4 10 65535 0 0]E assim como eu previ, encontramos um[n]tesouro, mas...[n][w][e]

[msg MSG_GetTv [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]É uma TV CRT. Não podemos assistir a nenhuma[n]transmissão sem sintonizador.[n][w][e]
[s][f 4 10 65535 0 0]Seria um desperdício apenas deixá-lo ficar[n]aqui. Existe um lugar onde podemos chegar a[n]eletrodomésticos baratos?[n][w][e]

[msg MSG_MyRoomClean_End [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]De qualquer forma, bom trabalho. Vamos fazer[n]uma pausa.[n][w][e]

[msg MSG_MyRoomClean_End_YORU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]De qualquer forma, bom trabalho. Pode muito[n]bem dormir um pouco enquanto podemos.[n][w][e]

[msg MSG_Clean_DayEnd_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Esta sala parece um pouco mais confortável[n]agora...[n][w][e]
[s][f 4 10 65535 0 0]Agora você pode mudar esta sala como quiser![n][w][e]
[s][f 4 10 65535 0 0]Você não está cansado? Tudo bem, vamos fazer[n]uma pausa.[n][w][e]

[sel SEL_Clean top]
[s]Vamos limpar isso.[e]
[s]Eu não estou no clima.[e]

[msg MSG_Clean_NG [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1002 65535 0]Não vamos limpar agora.[n][w][e]

[msg MIND_Clean_NG]
[s]Acho que não deveria fazer nenhuma limpeza[n]agora...[n][w][e]

[msg MSG_Floor_NotClean_Think [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Você sente vontade de limpar agora?[n][w][e]

[msg MSG_Floor_NotClean_Think_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Deveríamos realmente fazer uma limpeza...[n]mas precisamos fazê-lo outra hora.[n][w][e]

[msg MSG_Floor_Clean_Now [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Veja! Essa planta ainda está viva...[n]Podemos decorar com isso.[n][w][e]

[msg MSG_Floor_Clean_End [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Até uma sala sombria pode ser iluminada com[n]uma pequena folhagem verde...[n][w][e]
[s][f 4 10 65535 0 0]Vamos cuidar bem desta planta para que não[n]seque e afaste.[n][w][e]

[msg MSG_Floor_Clean_Continue [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Esta é uma boa oportunidade.[n][w][e]
[s][f 4 10 65535 0 0]As estantes de livros de lá estão parecendo[n]um pouco confusas. Vamos limpar tudo[n]enquanto estamos nisso![n][w][e]

[msg MND_Floor_NotClean_Think]
[s]Existem todas essas necessidades diárias não[n]utilizadas aqui. Não há organização para[n]eles...[n][w][e]

[msg MND_Stove01]
[s]É bom e quente.[n][w][e]
[s]Ainda parece haver combustível suficiente...[n][w][e]

[msg MND_Stove02]
[s]É bom e quente.[n][w][e]
[s]Parece haver menos combustível...[n][w][e]

[msg MND_Stove03]
[s]É bom e quente.[n][w][e]
[s]Parece que alguém já adicionou mais[n]combustível a ele...[n][w][e]

[msg MND_StopAct_Common_0724]
[s]Morgana ainda não voltou...[n][w][e]

[msg MND_StopAct_Common_0915]
[s]Quem era essa pessoa com Morgana?[n][w][e]

[msg MND_StopAct_Common_0916]
[s]Eu poderia conhecer os dois se fosse a[n]lembranças...?[n][w][e]

[msg MSG_StopAct_Common_0917 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Este lugar é tão monótono como sempre... mas[n]ainda é aconchegante o suficiente para mim.[n][w][e]

[msg MSG_StopAct_Common_1026_ [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Futaba parecia baixo... Como líder, você[n]sabe o que deve fazer, certo?[n][w][e]

[msg MSG_StopAct_Common_1026 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Futaba e o chefe vão ficar bem. Não se[n]preocupe com eles.[n][w][e]

[msg MSG_StopAct_Training_100 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Aquele palácio me desgastou...[n]Não vamos treinar hoje...[n][w][e]

[msg MSG_StopAct_Common_1121 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Hehe... mesmo que seja o mesmo sótão velho,[n]é um lugar importante para você, hein?[n][w][e]

[msg MSG_StopAct_Common_0202 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Não há como voltar agora.[n]Vamos dar 'inferno![n][w][e]

[msg MSG_StopAct_Common_0109 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]A escola começa amanhã para você, certo?[n]Você deve dormir mais cedo.[n][w][e]

[msg MSG_StopAct_Common_0110 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Ei, espere, você não vai dormir o[n]suficiente! Não vamos fazer isso hoje.[n][w][e]

[msg MSG_StopAct_Common_0111 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Eu sei que você está estressado, mas não[n]fique acordado até tarde. Sempre há amanhã.[n][w][e]

[msg MSG_StopAct_Common_0112 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]O palácio de hoje era incomum...[n]Estou exausto. Vamos descansar um pouco.[n][w][e]

[msg MSG_StopAct_Common_1003 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Não sinto vontade de ficar acordado esta[n]noite...[n]Vamos chamá-lo de um dia.[n][w][e]

[msg MSG_StopAct_Stair_0516 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]A verdade sobre Madarame, hein...[n]Vamos perguntar a Yusuke amanhã.[n][w][e]
[s]Você deve estar cansado depois de tudo o que[n]aconteceu hoje. É melhor encerrar um dia e[n]descansar.[n][w][e]

[msg MSG_StopAct_Stair_0611 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53115 65535 0]Está ficando muito tarde. Vamos encerrar um[n]dia e dormir.[n][w][e]

[msg MND_StopAct_Stair_0724]
[s]Morgana e eu podemos nos passar...[n][w][e]
[s]Eu deveria esperar até amanhã.[n][w][e]

[msg MSG_StopAct_Stair_0906 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]... Você está saindo amanhã para sua viagem[n]escolar, não é? Apresse-se e vá dormir já.[n][w][e]

[msg MSG_StopAct_Stair_0912 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ei... você acabou de voltar do Havaí, sabe?[n]Apenas... fique parado para esta noite.[n][w][e]

[msg MND_StopAct_Stair_0914]
[s]Eu deveria dormir para que estou pronto para[n]amanhã...[n][w][e]

[msg MND_StopAct_Stair_0915]
[s]Quem exatamente é o ladrão de beleza?[n]Eu deveria ir para a cama cedo para poder[n]investigar amanhã.[n][w][e]

[msg MND_StopAct_Stair_0916]
[s]Eu deveria ir para a cama cedo para me[n]preparar para a participação de lembranças[n]amanhã.[n][w][e]

[msg MSG_StopAct_Stair_0917 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1191 65535 0]Hoje foi tão cansativo... está ficando[n]tarde, então vamos dormir.[n][w][e]

[msg MSG_StopAct_Stair_1026_F [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Futaba parece deprimido. Você deveria falar[n]com ela.[n][w][e]

[msg MSG_StopAct_Stair_1026 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Eu posso ver o cansaço em seu rosto.[n]Já vá dormir.[n][w][e]

[msg MSG_StopAct_Stair_1121 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Entendo que você quer sair depois de estar[n]trancado...[n][w][e]
[s][f 4 10 65535 0 0]Mas a partir de amanhã, você estará muito[n]ocupado. Você deve ir com calma e descansar[n]hoje.[n][w][e]

[msg MSG_StopAct_Stair_0109 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Estou tão exausto- mental e fisicamente.[n]Vamos fazer com calma hoje.[n][w][e]

[msg MSG_StopAct_Stair_0110 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Existem alguns tópicos importantes sendo[n]discutidos amanhã. Eu sei que você está[n]nervoso, mas tente descansar um pouco.[n][w][e]

[msg MSG_StopAct_Stair_0111 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Eu sei que você quer se preparar, mas[n]economizar sua força também faz parte da[n]estratégia.[n][w][e]

[msg MSG_StopAct_Stair_0112 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Espere um minuto, você deve ficar cansado[n]depois de tudo o que caiu. Vamos apenas[n]descansar para hoje...[n][w][e]

[msg MSG_StopAct_Desk_0516 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Já está fazendo os preparativos para se[n]infiltrar no palácio? Eu admiro seu[n]entusiasmo...[n][w][e]
[s][f 4 10 65535 0 0]Mas você deve parar. Você não está cansado?[n]Eu não quero que você se machuque.[n][w][e]

[msg MSG_StopAct_Desk_0611 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Não vamos fazer isso hoje. Você não será[n]capaz de se concentrar quando se sentir[n]inchado.[n][w][e]

[msg MND_StopAct_Desk_0912 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Você parece sonolento...[n][w][e]
[s][f 4 10 65535 0 0]E se você se machucar? Você deve parar por[n]hoje.[n][w][e]

[msg MND_StopAct_Desk_0914]
[s]Um gato deixou as impressões de pata no pó...[n][w][e]
[s]Estou preocupado com Morgana...[n][w][e]

[msg MND_StopAct_Desk_0915]
[s]Morgana sempre cuidou de mim, mas ele não[n]está mais aqui...[n][w][e]

[msg MND_StopAct_Desk_0916]
[s]Morgana e seu amigo estão realmente[n]resolvendo os pedidos em lembranças...?[n][w][e]

[msg MSG_StopAct_Desk_0917 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1048 65535 0]Estarei quebrando o chicote novamente para[n]ensiná-lo a fazer ferramentas de[n]infiltração! Atenção![n][w][e]

[msg MND_StopAct_Desk_0202 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ei, Maruki está lá embaixo! Esta não é hora[n]de fazer ferramentas![n][w][e]

[msg MSG_StopAct_Table_0516 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53116 65535 0]Shibuya depois da escola amanhã...[n]Não durma só porque você estava no palácio.[n][w][e]

[msg MSG_StopAct_Table_0611 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Qual é o problema? Você está se lembrando da[n]festa de maconha quente?[n][w][e]

[msg MSG_StopAct_Table_0716 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Você estudou para os exames nos últimos[n]dias. Não fique acordado até tarde esta[n]noite e descanse um pouco, ok?[n][w][e]

[msg MSG_StopAct_Table_0906 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Você pode até fazer ferramentas de[n]infiltração sozinho agora...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 1037 65535 0]...Não é nada. Apenas vá dormir.[n][w][e]

[msg MSG_StopAct_Table_0912 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Se eu fosse...[n][w][e]
[s][f 4 10 65535 0 0]...Nao e nada.[n][w][e]

[msg MND_StopAct_Table_0914]
[s]Existem marcas de arranhões feitas de garras[n]nas pernas da mesa...[n][w][e]
[s]Estou preocupado com Morgana...[n][w][e]

[msg MSG_StopAct_Table_0917 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 53111 65535 0]Hehehe, acho que estou de volta.[n][w][e]

[msg MSG_StopAct_Table_1011 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1047 65535 0]Pobre Haru... ver seu próprio pai assim...[n]como algo tão horrível poderia acontecer?[n][w][e]

[msg MSG_StopAct_Table_0202 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]O que é isso? Algo em sua mente?[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Ouça, não tenha medo! Fique firme![n][w][e]

[msg MSG_StopAct_Gomi_0516 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Temos amanhã para pensar.[n]Podemos arrumar outra vez.[n][w][e]

[msg MSG_StopAct_GomiClean_05 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Eu sabia que Lady Ann estaria pensando em[n]tudo...[n][w][e]

[msg MSG_StopAct_Gomi_0611 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Você vai limpar agora?[n]Yusuke já está aqui, sabe?[n]Não precisa ser feito hoje.[n][w][e]

[msg MSG_StopAct_GomiClean_06 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1031 65535 0]Ainda bem que limpamos seu quarto.[n]Não queremos que Lady Ann entre em uma sala[n]suja agora, quer?[n][w][e]

[msg MSG_StopAct_GomiClean_07 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Você acabou de terminar com seus exames.[n]Você não precisa acumular seu cérebro com[n]layouts hoje.[n][w][e]

[msg MSG_StopAct_Gomi_0716 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Vamos limpar outra hora. Agora que a[n]temporada de exames acabou, podemos dormir[n]mais cedo, não é?[n][w][e]

[msg MSG_StopAct_GomiClean_09 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Vamos dormir. Não precisamos resolver suas[n]recordações agora...[n][w][e]

[msg MSG_StopAct_Gomi_0906 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Eu não acho que você precisa se preocupar em[n]limpar agora, já que você vai fazer sua[n]viagem à escola amanhã.[n][w][e]

[msg MSG_StopAct_Gomi_0912 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Por que você de repente está entrando nisso[n]agora? Salve para amanhã.[n][w][e]

[msg MSG_StopAct_GomiClean_09_2 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Parecia que o quarto estava super quieto[n]enquanto você se foi...[n][w][e]
[s][f 4 10 65535 0 0]Não que isso importe muito...[n][w][e]

[msg MND_StopAct_Gomi_0914]
[s]Morgana me disse para limpar...[n][w][e]
[s]Estou preocupado com Morgana...[n][w][e]

[msg MND_StopAct_GomiClean_09]
[s]O quarto está muito quieto...[n][w][e]
[s]Estou preocupado com Morgana...[n][w][e]

[msg MND_StopAct_GomiClean_09_2]
[s]Como o ladrão de beleza e Morgana se[n]encontraram...?[n][w][e]

[msg MND_StopAct_GomiClean_09_3]
[s]Como faço para consertar as coisas com[n]Morgana?[n][w][e]

[msg MSG_StopAct_GomiClean_10 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Você deve limpar, mas primeiro descanse um[n]pouco.[n][w][e]

[msg MSG_StopAct_GomiClean_10_2 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Você seriamente vai resolver a prateleira[n]agora? Eu nem consigo resolver meus[n]próprios sentimentos...[n][w][e]

[msg MSG_StopAct_Gomi_1011 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Nós fizemos... como sempre fizemos, certo?[n]Nós... devemos ficar bem...[n][w][e]

[msg MSG_StopAct_GomiClean_02 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Ei, [f 4 2], vamos descer as escadas depois de coletar[n]seus pensamentos.[n][w][e]

[msg MSG_StopAct_Training_051 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Ei, você parece exausto. Você não precisa[n]treinar hoje.[n][w][e]

[msg MSG_StopAct_Training_061 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0]Você realmente vai treinar com o estômago[n]cheio!? Isso só vai te deixar doente![n][w][e]

[msg MSG_StopAct_Training_071 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1191 65535 0]Entendo que você quer mover seu corpo depois[n]de terminar os exames, mas você não está se[n]sentindo cansado? Vamos dormir.[n][w][e]

[msg MSG_StopAct_Training_090 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1112 65535 0]Não faça nada que o cansasse. Afinal, a[n]partir de amanhã, temos muito trabalho pela[n]frente.[n][w][e]

[msg MSG_StopAct_Training_091 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1112 65535 0]Você ainda tem jet lag. Não precisamos fazer[n]isso hoje.[n][w][e]

[msg MND_StopAct_Training_091]
[s]A chuva é extraordinariamente alta...[n][w][e]
[s]Estou preocupado com Morgana...[n][w][e]

[msg MND_StopAct_Training_091_2]
[s]Estou tão preocupado com Morgana, acho que[n]não posso me concentrar no treinamento...[n][w][e]

[msg MSG_StopAct_Training_091_2]
[s]Estou tão preocupado com Morgana, acho que[n]não posso me concentrar no treinamento...[n][w][e]

[msg MSG_StopAct_Training_091_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Estou cansado hoje. Vamos treinar outra hora.[n][w][e]

[msg MSG_StopAct_Training_101 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Não sinto vontade de mover meu corpo...[n]O que exatamente... aconteceu...?[n][w][e]

[msg MSG_StopAct_Training_020 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Eu sempre estarei com você. Pense na sua[n]resposta com cuidado, ok?[n][w][e]

[msg MND_E10530101_NG_GOTO_1F]
[s][vp 1 0 0 0 0 0]Eu preciso acordar cedo amanhã...[n]Eu deveria descansar muito hoje.[n][w][e]

[msg fev0409_10_STEP_mes01]
[s][vp 1 0 0 0 0 0]... Parece que eu deveria fazer uma limpeza.[n][w][e]

[msg fev0409_NG_DOWN]
[s][vp 1 0 0 0 0 0]Eu deveria encerrar um dia e apenas dormir...[n][w][e]

[msg fev1030_NG_DOWN]
[s][vp 1 0 0 0 0 0]Eu deveria encerrar um dia e apenas dormir...[n][w][e]

[msg fev1121_NG_DOWN]
[s][vp 1 0 0 0 0 0]Eu deveria encerrar um dia e apenas dormir...[n][w][e]

[msg BED_CHECK_mes00]
[s][vp 1 0 0 0 0 0]Há um colchão aqui.[n][w][e]
[s][vp 1 0 0 0 0 0]Isso deveria ser minha cama...?[n][w][e]

[msg BED_CHECK_mes01]
[s][vp 1 0 0 0 0 0]Há uma cama colocada aqui no canto.[n][w][e]

[msg BED_CHECK_0409_END_mes01]
[s][vp 1 0 0 0 0 0]A partir de hoje, este é o meu quarto...[n][w][e]

[sel BED_CHECK_0409_EV_SEL top]
[s]Mudar e ir dormir [e]
[s]Não durma ainda [e]

[msg fev0410_04_mes01]
[s][vp 1 0 0 0 0 0]Esse som de toque não vem do meu celular...[n][w][e]

[msg fev0410_04_mes02]
[s][vp 1 0 0 0 0 0]Eu ouço isso vindo de baixo.[n][w][e]

[msg MND_E10530101_NG_BED]
[s][vp 1 0 0 0 0 0]O telefone no andar de baixo está tocando.[n]Eu deveria me apressar e responder...[n][w][e]

[msg BED_CHECK_0410_END_mes01]
[s][vp 1 0 0 0 0 0]Há mais alguma coisa que eu preciso fazer...?[n][w][e]

[sel BED_CHECK_0410_EV_SEL top]
[s]Dorme [e]
[s]Não durma ainda [e]

[msg MND_E10920100_NG_BED]
[s][vp 1 0 0 0 0 0]Parece que não tenho tempo para tirar uma[n]soneca agora...[n][w][e]

[msg MND_E12710100_NG_BED]
[s][vp 1 0 0 0 0 0]Parece que não tenho tempo para tirar uma[n]soneca agora...[n][w][e]

[msg MSG_E22810100_NG_BED [Morgana]]
[s][bup 0 3 10 65535 0][f 4 10 65535 0 0][vp 8 2 1 1111 65535 0]Vamos lá, é um pouco cedo para ficar de mau[n]humor na cama! Devemos perguntar primeiro[n]ao chefe.[n][w][e]

[msg MSG_E22810100_NG_BED_2 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Eu olhei lá embaixo também, mas não[n]encontrei uma panela. O que o chefe disse?[n][w][e]

[msg MND_E24410100_NG_BED]
[s][vp 1 0 0 0 0 0]É melhor eu ir e me encontrar com aquele[n]jornalista...[n][w][e]

[msg BED_CHECK_1030_END_mes01 [Futaba]]
[s][f 4 23 1 850 3 10 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9178 65535 0]Já está tão tarde...[n][w][e]

[sel BED_CHECK_1030_EV_SEL_1 top]
[s]Dorme [e]
[s]Não durma ainda [e]

[msg MSG_356_101_01_FUTABA_EN [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9176 65535 0]Sojiro ainda está acordado?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Isso é meio estranho...[n][w][e]

[sel BED_CHECK_1030_EV_SEL_2 top]
[s]Vá para casa ou ele vai se preocupar.[e]
[s]Você pode dormir no sofá.[e]

[msg MSG_356_101_01_FUTABA_EN_2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Espere, você não deveria dormir no sofá,[n]para que Futaba possa ir em frente e dormir[n]na cama?[n][w][e]

[msg MSG_356_101_01_FUTABA_EN_3 [Futaba]]
[s][bup 0 8 3 65535 0][vp 8 2 65535 0 0 0]......[n][w][e]

[msg MSG_356_101_01_FUTABA_EN_4 [Futaba]]
[s][f 4 23 1 850 4 10 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9195 65535 0]... eu vou para casa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Noite.[n][w][e]

[msg BED_CHECK_1121_END_mes01]
[s][vp 1 0 0 0 0 0]Eu deveria ir para a cama...[n][w][e]

[sel BED_CHECK_1121_EV_SEL top]
[s]Dorme [e]
[s]Não durma ainda [e]

[msg MSG_399_101_01_MORU_END [Morgana]]
[s][f 4 23 1 850 0 0 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Vamos apenas nos tratar muito de descanso[n]hoje...[n][w][e]

[msg MND_COMMON_NG_BED]
[s][vp 1 0 0 0 0 0]Não tenho tempo para dormir na cama agora...[n][w][e]

[msg MND_E10510100_CHK_Closet]
[s][vp 1 0 0 0 0 0]É a caixa de papelão enviada de volta para[n]casa...[n][w][e]
[s][vp 1 0 0 0 0 0]Tem algumas roupas extras e necessidades[n]diárias por dentro.[n][w][e]

[msg MND_E10530100_CHK_Closet]
[s][vp 1 0 0 0 0 0]É a caixa de papelão enviada de volta para[n]casa...[n][w][e]
[s][vp 1 0 0 0 0 0]Tem algumas roupas extras e necessidades[n]diárias por dentro.[n][w][e]

[msg MND_E10920100_CHK_Closet]
[s][vp 1 0 0 0 0 0]É a caixa de papelão enviada de volta para[n]casa...[n][w][e]
[s][vp 1 0 0 0 0 0]Tem algumas roupas extras e necessidades[n]diárias por dentro.[n][w][e]

[msg MND_E12710100_CHK_Closet]
[s][vp 1 0 0 0 0 0]É a caixa de papelão enviada de volta para[n]casa...[n][w][e]
[s][vp 1 0 0 0 0 0]Tem algumas roupas extras e necessidades[n]diárias por dentro.[n][w][e]

[msg MSG_E22810100_NG_Closet [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]HM? Você não deveria falar com o chefe e[n]pedir emprestado uma panela?[n][w][e]

[msg MSG_E22810100_NG_Closet2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Você foi e conversou com o chefe, certo?[n]Você não conseguiu emprestar uma panela?[n][w][e]

[msg MSG_E22810100_NG_ROOMOBJ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]HM? Você não deveria falar com o chefe e[n]pedir emprestado uma panela?[n][w][e]

[msg MSG_E22810100_NG_ROOMOBJ_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Você foi e conversou com o chefe, certo?[n]Você não conseguiu emprestar uma panela?[n][w][e]

[msg MND_E24410100_CHK_Closet]
[s][vp 1 0 0 0 0 0]É melhor eu ir e me encontrar com aquele[n]jornalista...[n][w][e]

[msg MND_COMMON_CHK_Closet]
[s][vp 1 0 0 0 0 0]Não tenho tempo para relaxar...[n][w][e]

[msg BENCH_CLEAN_LONELY_mes00]
[s][vp 1 0 0 0 0 0]É uma mesa com uma pilha de livros no topo.[n][w][e]
[s][vp 1 0 0 0 0 0]Ninguém pode usar isso como uma mesa[n]enquanto é assim...[n][w][e]

[msg BENCH_CLEAN_LONELY_mes01]
[s][vp 1 0 0 0 0 0]Ninguém pode usar isso como uma mesa[n]enquanto é assim...[n][w][e]

[msg BENCH_CLEAN_LONELY_mes02]
[s][vp 1 0 0 0 0 0]Posso usar isso como uma mesa se remover os[n]livros...[n][w][e]

[msg MND_E10530100_CHK_Desk]
[s][vp 1 0 0 0 0 0]Existem todos esses livros empilhados na[n]mesa. Não posso usar isso enquanto é assim.[n][w][e]

[msg MND_E10920100_CHK_Desk]
[s][vp 1 0 0 0 0 0]Existem todos esses livros empilhados na[n]mesa. Não posso usar isso enquanto é assim.[n][w][e]

[msg MND_E12710100_CHK_Desk]
[s][vp 1 0 0 0 0 0]Existem todos esses livros empilhados na[n]mesa. Não posso usar isso enquanto é assim.[n][w][e]

[msg MSG_E22810100_CHK_Desk [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 1029 65535 0]Ei, você não está prestes a forjar uma[n]panela, está!? Já vá perguntar ao chefe![n][w][e]

[msg MSG_E22810100_CHK_Desk2 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Estou tão feliz em comer panela quente com[n]todos! Eu me pergunto o que vai estar[n]dentro.[n][w][e]

[msg MND_E24410100_CHK_Desk]
[s][vp 1 0 0 0 0 0]É melhor eu ir e me encontrar com aquele[n]jornalista...[n][w][e]

[msg MND_COMMON_CHK_Desk]
[s][vp 1 0 0 0 0 0]Não tenho tempo para relaxar...[n][w][e]

[msg TABLE_CLEAN_mes00]
[s][vp 1 0 0 0 0 0]É uma mesa coberta de poeira.[n][w][e]
[s][vp 1 0 0 0 0 0]Se eu desenhar uma linha na poeira com o[n]dedo, provavelmente será muito fácil de[n]ver...[n][w][e]

[msg TABLE_CLEAN_mes01]
[s][vp 1 0 0 0 0 0]Eu não gostaria de comer nesta mesa...[n][w][e]

[msg TABLE_CLEAN_mes02]
[s][vp 1 0 0 0 0 0]Agora que esta tabela está limpa, eu me[n]pergunto se posso usá-la para qualquer[n]coisa...[n][w][e]

[msg MND_E10530100_CHK_Table]
[s][vp 1 0 0 0 0 0]Esta mesa está toda limpa agora...[n][w][e]

[msg MND_E10920100_CHK_Table]
[s][vp 1 0 0 0 0 0]Esta mesa está toda limpa agora...[n][w][e]

[msg MND_E12710100_CHK_Table]
[s][vp 1 0 0 0 0 0]Esta mesa está toda limpa agora...[n][w][e]

[msg MSG_E22810100_NG_CHK_Tab [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Podemos pensar no layout mais tarde.[n]Pegue o pote, primeiro.[n][w][e]

[msg MSG_E22810100_NG_CHK_Tab_2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 1177 65535 0]O que? Você não conseguiu encontrar uma[n]panela? Também não há um aqui...[n][w][e]

[msg MND_E24410100_CHK_Table]
[s][vp 1 0 0 0 0 0]É melhor eu ir e me encontrar com aquele[n]jornalista...[n][w][e]

[msg MND_COMMON_CHK_Table]
[s][vp 1 0 0 0 0 0]Não tenho tempo para relaxar...[n][w][e]

[msg SHELF_CLEAN_mes00]
[s][vp 1 0 0 0 0 0]Algumas partes dessas prateleiras têm[n]ferrugem nelas.[n][w][e]
[s][vp 1 0 0 0 0 0]Todos esses livros de aparência difícil[n]estavam descuidadamente amontoados nele...[n][w][e]

[msg SHELF_CLEAN_mes01]
[s][vp 1 0 0 0 0 0]Todos esses livros de aparência difícil[n]estavam descuidadamente amontoados nele...[n][w][e]

[msg SHELF_CLEAN_mes02]
[s][vp 1 0 0 0 0 0]Eu posso usar essas prateleiras se remover[n]os livros...[n][w][e]

[msg MND_E10530100_CHK_Shelf]
[s][vp 1 0 0 0 0 0]Um monte de livros foi empurrado[n]descuidadamente nessas prateleiras...[n][w][e]

[msg MND_E10920100_CHK_Shelf]
[s][vp 1 0 0 0 0 0]Um monte de livros foi empurrado[n]descuidadamente nessas prateleiras...[n][w][e]

[msg MND_E12710100_CHK_Shelf]
[s][vp 1 0 0 0 0 0]Um monte de livros foi empurrado[n]descuidadamente nessas prateleiras...[n][w][e]

[msg MSG_E22810100_NG_Shelf [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Uma sala arrumada é agradável, mas[n]precisamos nos preparar.[n]Vamos encontrar o pote.[n][w][e]

[msg MSG_E22810100_NG_Shelf2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Eu não acho que você encontrará o pote lá em[n]baixo. Não estaria lá embaixo?[n][w][e]

[msg MND_E24410100_CHK_Shelf]
[s][vp 1 0 0 0 0 0]É melhor eu ir e me encontrar com aquele[n]jornalista...[n][w][e]

[msg MND_COMMON_CHK_Shelf]
[s][vp 1 0 0 0 0 0]Não tenho tempo para relaxar...[n][w][e]

[msg MND_E10920100_CHK_Floor]
[s][vp 1 0 0 0 0 0]Alguns itens domésticos estão apenas[n]deitados no chão em desordem.[n]Eu mal consigo ver o chão...[n][w][e]

[msg MND_E10530100_CHK_Floor]
[s][vp 1 0 0 0 0 0]Alguns itens domésticos estão apenas[n]deitados no chão em desordem.[n]Eu mal consigo ver o chão...[n][w][e]

[msg MND_E12710100_CHK_Floor]
[s][vp 1 0 0 0 0 0]Alguns itens domésticos estão apenas[n]deitados no chão em desordem.[n]Eu mal consigo ver o chão...[n][w][e]

[msg MSG_E22810100_NG_Floor [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]Entendo querer limpar antes que todos[n]cheguem... mas você trouxe isso para si[n]mesmo, você sabe.[n][w][e]

[msg MSG_E22810100_NG_Floor2 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Eu tenho dito para você arrumar...[n][w][e]

[msg MND_E24410100_CHK_Floor]
[s][vp 1 0 0 0 0 0]É melhor eu ir e me encontrar com aquele[n]jornalista...[n][w][e]

[msg MND_COMMON_CHK_Floor]
[s][vp 1 0 0 0 0 0]Não tenho tempo para relaxar...[n][w][e]

[msg MND_E10510100_CHK_Washbo]
[s][vp 1 0 0 0 0 0]É uma cesta de lavanderia com um design[n]antigo.[n][w][e]
[s][vp 1 0 0 0 0 0]Há poeira e um pino de roupas dentro dela.[n][w][e]

[msg MND_E10510100_CHK_Washbo_2]
[s][vp 1 0 0 0 0 0]É uma cesta de lavanderia com um design[n]antigo.[n][w][e]

[msg MND_E10530100_CHK_Washbo]
[s][vp 1 0 0 0 0 0]Há mais alguma coisa que eu preciso fazer...?[n][w][e]

[msg MND_E10920100_CHK_Washbo]
[s][vp 1 0 0 0 0 0]Há uma cesta de lavanderia aqui...[n][w][e]

[msg MND_E12710100_CHK_Washbo]
[s][vp 1 0 0 0 0 0]Há uma cesta de lavanderia aqui...[n][w][e]

[msg MND_E24410100_CHK_Washbo]
[s][vp 1 0 0 0 0 0]É melhor eu ir e me encontrar com aquele[n]jornalista...[n][w][e]

[msg MND_COMMON_CHK_Washbox]
[s][vp 1 0 0 0 0 0]Há poeira coletando na cesta de lavanderia...[n][w][e]
[s][vp 1 0 0 0 0 0]É isso mesmo, havia uma lavanderia na casa[n]de banho nas proximidades...[n][w][e]

[msg MSG_COMMON_CHK_Washbox_M [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1170 0 0]... Ugh, essa cesta de lavanderia certamente[n]está em um estado lamentável.[n][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1189 0 0]Venha para pensar sobre isso, não havia uma[n]lavanderia na casa de banho perto aqui?[n][w][e]

[msg MND_NG_HIT_356_101]
[s][vp 1 0 0 0 0 0]Eu deveria encerrar um dia e apenas dormir...[n][w][e]

[msg MND_NG_HIT_399_101]
[s][vp 1 0 0 0 0 0]Eu deveria encerrar um dia e apenas dormir...[n][w][e]

[msg DELI_BOX_0409_mes00]
[s][vp 1 0 0 0 0 0]É a caixa de papelão enviada de volta para[n]casa...[n][w][e]
[s][vp 1 0 0 0 0 0]Está cheio de roupas e necessidades diárias.[n]Vou mudar para roupas mais confortáveis por[n]enquanto.[n][w][e]

[msg DELI_BOX_mes01]
[s][vp 1 0 0 0 0 0]Acho que devo limpar a sala enquanto estou[n]organizando coisas...[n][w][e]

[msg fev0409_10_CHECK_mes01]
[s][vp 1 0 0 0 0 0]Eu deveria começar a limpar primeiro...[n][w][e]

[sel fev0409_10_CHECK_SEL top]
[s]Comece a limpar [e]
[s]Verifique em outros lugares [e]

[msg MND_E10530100_CHK_Sofa]
[s][vp 1 0 0 0 0 0]O sofá foi limpo, então agora as pessoas[n]podem sentar nele novamente.[n][w][e]

[msg MND_E10920100_CHK_Sofa]
[s][vp 1 0 0 0 0 0]Não tenho tempo para descansar no sofá...[n][w][e]

[msg MSG_E22810100_NG_Sofa [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Você não pode estar cansado o suficiente[n]para querer sentar. Você só precisa[n]perguntar sobre o pote.[n][w][e]

[msg MSG_E22810100_NG_Sofa2 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Este será onde Lady Ann se senta...[n]Me whehehe...[n][w][e]

[msg MSG_E22810100_NG_TRChair [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1140 65535 0]Esta não é hora de começar a treinar![n]Temos que preparar o pote![n][w][e]

[msg MSG_E22810100_NG_TRChair_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1186 65535 0]O pote no andar de baixo não está no andar[n]de baixo? O que o chefe disse?[n][w][e]

[msg MND_E24410100_TRChair]
[s][vp 1 0 0 0 0 0]É melhor eu ir e me encontrar com aquele[n]jornalista...[n][w][e]

[msg MND_COMMON_TRChair]
[s][vp 1 0 0 0 0 0]Não tenho tempo para relaxar...[n][w][e]

[msg MSG_E22810100_NG_PlantOB [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 1048 65535 0]Eles dizem que as plantas crescem bem quando[n]ouvem vozes se divertindo. Vamos nos[n]divertir esta noite![n][w][e]

[msg MSG_E22810100_NG_PlantOB_2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]Não, esse não é o pote que você está[n]procurando...[n][w][e]

[msg MND_E24410100_PlantOBJ]
[s][vp 1 0 0 0 0 0]É melhor eu ir e me encontrar com aquele[n]jornalista...[n][w][e]

[msg MND_COMMON_PlantOBJ]
[s][vp 1 0 0 0 0 0]Não tenho tempo para relaxar...[n][w][e]

