[msg Dummy]
[s]......[n][w][e]

[msg D01_02_moru_navi_mes01 [Morgana]]
[s][bup 0 3 0 65535 0]Vamos usar a estrada da qual escapamos da última[n]vez![n][w][e]

[msg D01_02_moru_navi_mes02 [Morgana]]
[s][bup 0 3 0 65535 0]Você se lembra? Saímos da sala no topo da escada![n][w][e]

[msg D01_02_moru_navi_mes03 [Morgana]]
[s][bup 0 3 0 65535 0]Tudo bem, aqui vamos nós![n][w][e]
[s]...Uau![n][w][e]

[msg D01_02_moru_navi_mes04 [Morgana]]
[s][bup 0 3 0 65535 0]Já é hora da patrulha?!?[n]Depressa, antes que eles nos notem![n][w][e]

[msg D01_02_moru_navi_mes05 [Morgana]]
[s][bup 0 3 0 65535 0]A passagem subterrânea está[n]logo abaixo![n][w][e]

[msg D01_02_moru_navi_mes06 [Morgana]]
[s][bup 0 3 0 65535 0]Estamos quase lá![n][w][e]

[msg Dummy_09 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]É um vaso. Não parece haver nada aqui.[n][w][e]

[msg Dummy_10 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Merda, queime! Eu tenho[n]cera quente no meu rosto![n][w][e]

[msg Dummy_11 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não há nada aqui além de talheres.[n][w][e]

[msg Dummy_12 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hum... Nada aqui.[n][w][e]

[msg Dummy_13 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nossa... Esse castelo é o[n]reino do mau gosto...[n][w][e]

[msg D01_02__ng_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ei, não temos tempo para[n]foder. Vamos segui-lo.[n][w][e]

[msg D01_02__ng_mes02 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Então eles vão nos encontrar, idiota![n]Entre, rápido![n][w][e]

[msg D01_02_escape_ng_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Merda, tem um soldado[n]bem ali...[n][w][e]

[msg D01_02_escape_ng_mes02 [Morgana]]
[s][bup 0 3 0 65535 0]Mas não há outro jeito.[n]Temos que escapar por aquela[n]porta antes que eles nos encontrem.[n][w][e]

