[msg dammy]
[s]Fictício?[n][w][e]

[msg D10_03_look_at_researche [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ei! Olhe para aquela sombra.[n][w][e]

[msg D10_10_CardCheck_denied [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você não obterá nada de útil[n]analisando essa coisa.[n][w][e]

[msg D10_10_CardCheck_First_S [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]Parece algum tipo de[n]dispositivo de identificação.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Precisamos do ID correto para[n]continuar.[n][w][e]

[msg D10_10_CardCheck_First_E [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não precisamos ir por esse caminho.[n]Vamos deixar isso de lado, por enquanto.[n][w][e]

[msg D10_03_look_at_researche_2 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57047 65535 0]Existe aquela Sombra. Intervimos?[n][w][e]

[sel D10_03_look_at_researche_3 top]
[s]Vamos fazê-lo.[e]
[s]Ainda não.[e]

[msg D10_03_look_at_researche_4 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57186 65535 0]OK. Avise-me quando estiver livre.[n][w][e]

[msg D10_03_look_at_researche_5 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Um momento! Ele está conversando com outra sombra.[n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9089 65535 0]Eu deveria ser capaz de obter algumas[n]informações úteis.[n][w][e]

[msg D10_03_look_at_researche_6 [Agente]]
[s]Volte para seu lugar. Você deve estar na sala de[n]observação.[n][w][e]
[s]Siga o plano. Não[n]aja por conta própria.[n][w][e]

[msg D10_03_look_at_researche_7 [Guarda]]
[s]Estou apenas tentando eliminar[n]potenciais ameaças ao mestre.[n][w][e]
[s]Mas acho melhor evitar[n]levar o cartão comigo,[n]aqui. OK. Estou de volta à posição.[n][w][e]

[msg D10_03_look_at_researche_8 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9040 65535 0]O que..!? Desculpa Joker...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Essa sombra está prestes a ir embora![n]Leve-o! Rápido! Vai! Vai! Vai![n][w][e]

[msg D10_03_look_at_researche_9 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57144 65535 0]O que você está dizendo, Joker-senpai?[n][w][e]

[msg D10_03_researcher_battle [Guarda]]
[s]Coisa? Os Ladrões Fantasmas![n]Eles devem ter me seguido![n][w][e]

[msg D10_03_researcher_battle_2 [Agente]]
[s]Xingamento! Eu avisei![n]Agora temos que eliminá-los![n]Pelo mestreeeee![n][w][e]

[msg D10_03_researcher_battle_3 [Guarda]]
[s]Você quer meu cartão, hein? Bem,[n]você terá que merecê-lo![n][w][e]

[msg D10_03_researcher_battle_4]
[s]Não vou deixar você explorar a pesquisa do[n]Doutor Maruki novamente! Você terminou![n][w][e]

[msg D10_03_researcher_battle_5 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eles chegaram![n][w][e]

[msg D10_03_ID_Door_Open01 [[f 4 31 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57051 65535 0]Sim, agora está aberto![n][w][e]

[msg D10_03_ID_Door_Open02 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nós não vimos o que[n]está atrás desta porta...[n][w][e]
[s]Esse scanner deve estar aqui por[n]um motivo. Portanto, a vigilância[n]poderia ser mais rigorosa.[n][w][e]
[s]Tenha cuidado lá fora.[n]OK, Violet?[n][w][e]

[msg D10_03_ID_Door_Open03 [[f 4 31 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57026 65535 0]Oh! Ah sim, Mona-senpai![n][w][e]

[msg D10_10_CardCheck_Second_ [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O que está acontecendo, senpai?[n][w][e]

[msg D10_10_CardCheck_Second__2 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que não abre...[n]Vamos continuar procurando.[n][w][e]

[msg D10_10_CardCheck_Party01 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9127 65535 0]...Eu dei uma olhada, mas parece[n]feito para conceder[n]acesso apenas a partir daqui.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você precisa de um ID de porta.[n][w][e]

[msg D10_10_CardCheck_Party01_2 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7048 65535 0]Com uma fechadura dessas, deve[n]esconder algo importante![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos encontrar uma identidade![n][w][e]

[msg D10_10_CardCheck_Party01_3 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Mas primeiro precisamos de uma dica...[n][w][e]

[msg D10_10_CardCheck_Party01_4 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9114 65535 0]Oh! Olhar![n][w][e]

[msg D10_10_CardCheck_Party02 [Guarda]]
[s]Sim, a emboscada falhou. Agora[n]eles estão examinando o[n]dispositivo de autenticação.[n][w][e]
[s]Sem um cartão, eles não irão a lugar nenhum.[n][w][e]
[s]Este é o fim para eles.[n][w][e]

[msg D10_10_CardCheck_Party03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oi Oráculo![n][w][e]

[msg D10_10_CardCheck_Party03_2 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9089 65535 0]Eu interceptei a conversa[n]de algumas Sombras...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]A busca pelo distintivo[n]finalmente terminou.[n]Aquele Shade tem um.[n][w][e]

[msg D10_10_CardCheck_Party03_3 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7022 65535 0]Você está bisbilhotando ... er,[n]quero dizer, sua técnica[n]vem a calhar mais uma vez.[n][w][e]

[msg D10_10_CardCheck_Party03_4 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Eu nem vi aquela Sombra.[n][w][e]

[msg D10_10_CardCheck_Party03_5 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9081 65535 0]Duvido que ele saiba que eu ouvi.[n]Devemos emboscá-lo[n]para pegar seu distintivo?[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você não pode alcançá-lo a partir daqui, embora.[n]Você tem que dar a volta por trás e passar pelo[n]auditório.[n][w][e]

[msg D10_10_CardCheck_Party03_6 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57186 65535 0]Eu entendi. Temos que cuidar disso.[n]Vamos lá![n][w][e]

[msg D10_10_CardChecked_Party [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Passamos pelo auditório.[n][w][e]

[msg D10_10_CardChecked_Party_2 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que não abre...[n]Vamos continuar procurando.[n][w][e]

