[msg DUMMY_mes01]
[s]......[n][w][e]

[msg D156_10_hit_01_mes01]
[s]Este parece ser o centro da distorção do[n]palácio.[n][w][e]

[msg D156_10_hit_01_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]Vamos lá, vamos enviar o cartão Callin 'e[n]descobrir o que é essa merda nebulosa![n][w][e]

[msg D156_10_hit_01_mes03 [Haru]]
[s][bup 0 7 103 0 0]......[n][w][e]

[msg timer_block_mes04 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1029 65535 0]H-hey, você realmente tem tempo para sair[n]dessa maneira!?[n][w][e]

