[msg D05_02_e341_022_mes09 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9114 65535 0]E aí, Joker? Não há mais nada para fazermos[n]aqui.[n][w][e]

[msg D156_03_miniEV01_mes04 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Provavelmente precisaremos procurar um[n]servidor ou um terminal se quisermos romper[n]por aqui.[n][w][e]

[msg D156_03_miniEV01_mes05 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Um servidor, hein...[n][w][e]

[msg D156_03_miniEV01_02_mes0 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sugiro que usemos o elevador neste momento.[n][w][e]

[msg D156_03_miniEV02_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]Eu provavelmente poderia gerenciar se[n]pudermos encontrar um servidor de segurança[n]e o terminal associado...[n][w][e]

