[msg D08_01_e446_035_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4045 65535 0]Perfeito, a segurança está desativada![n][w][e]

[msg D08_01_e446_035_mes02 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Na hora... agora podemos seguir em frente![n][w][e]

[msg D08_01_e446_035_mes03 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3020 65535 0]Bem feito, Joker![n][w][e]

[msg D08_01_NPC_TALK_22_mes01 [Tired Middle-Aged Woman]]
[s]Shido...? Ele pode fazer o que quiser.[n]Eu realmente não me importo com que tipo de[n]cara ele é.[n][w][e]
[s]Não importará em breve de qualquer maneira...[n][w][e]

[msg D08_01_NPC_TALK_22_mes02 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1038 65535 0]Eu vejo...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ela não percebe o que ser governado por[n]alguém realmente significa...[n][w][e]

[msg D08_01_NPC_TALK_23_mes01 [Calm Young Man]]
[s]Por favor, deixe-me estar... e em troca, não[n]vou solicitar nada de você.[n][w][e]
[s]Deixe-me ver o fim deste mundo em paz...[n][w][e]

[msg D08_01_NPC_TALK_23_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2113 65535 0]Estou curioso para saber por que todo mundo[n]acredita que o mundo está chegando ao fim...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O que eles poderiam dizer...?[n][w][e]

[msg D08_01_NPC_TALK_24_mes01 [Tired Businessman]]
[s]Quem é o culpado pela multidão de problemas[n]no mundo...?[n][w][e]
[s]Eu me sinto doente só de pensar nisso. Tudo[n]o que realmente posso fazer agora é[n]ignorá-lo, suponho.[n][w][e]

[msg D08_01_NPC_TALK_24_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Que merda... ei! O mundo não vai melhorar[n]por conta própria, você sabe![n][w][e]

[msg D08_01_NPC_TALK_25_mes01 [Timid Young Man]]
[s]É melhor permanecer estagnado na vida...[n][w][e]
[s]Eu posso perder o único lugar que pertenço[n]se me colocar lá fora...[n][w][e]
[s]Tenho medo disso acontecendo, então acho que[n]vou ficar como sou...[n][w][e]

[msg D08_01_NPC_TALK_25_mes02 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6187 65535 0]Sua situação atual deve ser o que está[n]assustando você![n][w][e]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Como ele está bem com tudo isso...?[n][w][e]

