[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_MAMA_GREETING_01 [Lala Escargot]]
[s][vp 8 2 1 57724 65535 0]Vá direto para casa, está bem?[n][w][e]
[s]Não vagueie muito nesta área.[n]Algum esquisito pode[n]sequestrá-lo e acabar com você de forma terrível...[n][w][e]

[msg MND_E24440100_NG_GOOUT_0]
[s][vp 1 0 0 0 0 0]Eu deveria falar com[n]aquele repórter...[n][w][e]

[msg MSG_MAMA_LAST_GREETING [Lala Escargot]]
[s][vp 8 2 1 57723 65535 0]Tome cuidado. Cuidado com[n]odds no caminho de volta.[n][w][e]

[msg MND_RankUp_OK_Chishiki]
[s]Acho que minha [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vai aumentar em breve...[n][w][e]

[msg MND_RankUp_NG_Chishiki]
[s]Acho que [f 4 11 1][clr 26][f 4 12 0][clr 27][n]não vai aumentar tão cedo...[n][w][e]

[msg MND_INC_PARAMCHK_L_TISIK]
[s]Acho que ainda tenho muito[n]espaço para melhorar...[n][w][e]

[msg MND_INC_PARAMCHK_M_TISIK]
[s]Eu sinto que algo está vindo...[n][w][e]

[msg MND_INC_PARAMCHK_S_TISIK]
[s]Acho que estou a um passo de um avanço com meu [n][f 4 11 0][clr 26][f 4 12 0][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Miryoku]
[s]Acho que minha [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vai aumentar em breve...[n][w][e]

[msg MND_RankUp_NG_Miryoku]
[s]Acho que [f 4 11 1][clr 26][f 4 12 0][clr 27][n]não vai aumentar tão cedo...[n][w][e]

[msg MND_INC_PARAMCHK_L_MIRYO]
[s]Acho que ainda tenho muito[n]espaço para melhorar...[n][w][e]

[msg MND_INC_PARAMCHK_M_MIRYO]
[s]Eu sinto que algo está vindo...[n][w][e]

[msg MND_INC_PARAMCHK_S_MIRYO]
[s]Acho que estou a um passo de uma curva com [n][f 4 11 1][clr 26][f 4 12 1][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Kiyou]
[s]Acho que meu [f 4 11 2][clr 26][f 4 12 2][clr 27][n]vai aumentar em breve...[n][w][e]

[msg MND_RankUp_NG_Kiyou]
[s]Acho que [f 4 11 2][clr 26][f 4 12 2][clr 27][n]não vai aumentar tão cedo...[n][w][e]

[msg MND_RankUp_OK_Kiyou_Beef]
[s]Espero que meu[n][f 4 11 1][clr 26][f 4 12 1][clr 27] possa melhorar...[n][w][e]

[msg MND_INC_PARAMCHK_L_KIYOU]
[s]Acho que ainda tenho muito[n]espaço para melhorar...[n][w][e]

[msg MND_INC_PARAMCHK_M_KIYOU]
[s]Eu sinto que algo está vindo...[n][w][e]

[msg MND_INC_PARAMCHK_S_KIYOU]
[s]Acho que estou a um passo de um avanço com meu [n][f 4 11 2][clr 26][f 4 12 2][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Dokyo]
[s]Acho que meu [f 4 11 3][clr 26][f 4 12 3][clr 27][n]vai aumentar em breve...[n][w][e]

[msg MND_RankUp_NG_Dokyo]
[s]Acho que [f 4 11 3][clr 26][f 4 12 3][clr 27][n]não vai aumentar tão cedo...[n][w][e]

[msg MND_INC_PARAMCHK_L_DOKYO]
[s]Acho que ainda tenho muito[n]espaço para melhorar...[n][w][e]

[msg MND_INC_PARAMCHK_M_DOKYO]
[s]Eu sinto que algo está vindo...[n][w][e]

[msg MND_INC_PARAMCHK_S_DOKYO]
[s]Acho que estou a um passo de uma curva com [n][f 4 11 3][clr 26][f 4 12 3][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Yasasisa]
[s]Acho que meu [f 4 11 4][clr 26][f 4 12 4][clr 27][n]vai aumentar em breve...[n][w][e]

[msg MND_RankUp_NG_Yasasisa]
[s]Acho que [f 4 11 4][clr 26][f 4 12 4][clr 27][n]não vai aumentar tão cedo...[n][w][e]

[msg MND_RankUp_OK_Yasasisa_F]
[s]Espero que meu[n][f 4 11 4][clr 26][f 4 12 4][clr 27] possa melhorar...[n][w][e]

[msg MND_INC_PARAMCHK_L_YASAS]
[s]Acho que ainda tenho muito[n]espaço para melhorar...[n][w][e]

[msg MND_INC_PARAMCHK_M_YASAS]
[s]Eu sinto que algo está vindo...[n][w][e]

[msg MND_INC_PARAMCHK_S_YASAS]
[s]Acho que estou a um passo de um avanço com [n][f 4 11 4][clr 26][f 4 12 4][clr 27]...[n][w][e]

