[msg item_000]
[s]VAZIO[n][e]

[msg Item_001]
[s]Restaura 20 HP de um[n]aliado.[n][e]

[msg Item_002]
[s]Fórmula de ação rápida.[n]Restaura 50 HP de um[n]aliado.[n][e]

[msg Item_003]
[s]Fórmula de ação rápida.[n]Restaura 100 HP de um[n]aliado.[n][e]

[msg Item_004]
[s]Uma nova droga desenvolvida[n]pela TMC. Restaura 200 HP[n]de um aliado.[n][e]

[msg Item_005]
[s]Restaura 30% do HP[n]de um aliado.[n][e]

[msg Item_006]
[s]Restaure totalmente o HP[n]de um aliado.[n][e]

[msg Item_007]
[s]Uma nova droga desenvolvida[n]pela TMC. Restaura 50 HP[n]de todos os aliados.[n][e]

[msg Item_008]
[s]Uma nova droga desenvolvida[n]pela TMC. Restaura 100 HP[n]de todos os aliados.[n][e]

[msg Item_009]
[s]Uma nova droga desenvolvida[n]pela TMC. Restaura 200 HP[n]de todos os aliados.[n][e]

[msg Item_00A]
[s]Restaura totalmente o HP dos aliados.[n][e]

[msg Item_00B]
[s]Restaura os 10 SP de um[n]aliado.[n][e]

[msg Item_00C]
[s]Restaura os 50 SP de um[n]aliado.[n][e]

[msg Item_00D]
[s]Restaura os 100 SP de um[n]aliado.[n][e]

[msg Item_00E]
[s]Restaura totalmente o SP[n]de um aliado.[n][e]

[msg Item_00F]
[s]Revive um aliado caído[n]com 50% HP.[n][e]

[msg Item_010]
[s]Reviva um aliado caído[n]restaurando todo o HP.[n][e]

[msg Item_011]
[s]não usado[n][e]

[msg Item_012]
[s]Pomada médica. Cura[n]um aliado em chamas/[n]congelado/em choque.[n][e]

[msg Item_013]
[s]Bálsamo tropical. Cura[n]Raiva/Assunto/Confusão/Medo/[n]Desespero para um aliado.[n][e]

[msg Item_014]
[s]Cápsula de venda livre. Cure[n]Tontura/Amnésia/Sono/[n]Fome por um aliado.[n][e]

[msg Item_015]
[s]não usado[n][e]

[msg Item_016]
[s]não usado[n][e]

[msg Item_017]
[s]Concede a fuga de uma[n]batalha. Não pode ser usado[n]em algumas batalhas.[n][e]

[msg Item_018]
[s]Restaure totalmente o HP[n]e SP de todos os[n]aliados.[n][e]

[msg Item_019]
[s]Cura todas as doenças não especiais[n]negativas de[n]todos os aliados.[n][e]

[msg Item_01A]
[s]Cura todas as habilidades não especiais[n]negativas de[n]um aliado.[n][e]

[msg Item_01B]
[s]Restaura 30% do HP[n]de um aliado. Boost[n]Atk. e reduz a defesa.[n][e]

[msg Item_01C]
[s]Restaura 30% do HP de um all[n]Aumentar Atk,[n]Reduzir Prev. e iludiu[n][e]

[msg Item_01D]
[s]Restaura 30% do HP de um all[n]Melhora a precisão[n]e esquiva, reduz o ataque.[n][e]

[msg Item_01E]
[s]não usado[n][e]

[msg Item_01F]
[s]Forma una barriera intorno a[n]un alleato. Respinge tutte le[n]magie (non divine) 1 volta.[n][e]

[msg Item_020]
[s]Forma uma barreira para um[n]aliado que empurra para trás uma vez[n]atx. fis. e como arma.[n][e]

[msg Item_021]
[s]Aumenta o Ataque[n]de todos os aliados[n]por 3 turnos.[n][e]

[msg Item_022]
[s]Aumenta a precisão e[n]evasão para todos os[n]aliados por três turnos.[n][e]

[msg Item_023]
[s]Aumenta o Ataque[n]de todos os aliados[n]por 3 turnos.[n][e]

[msg Item_024]
[s]Novo produto antisséptico[n]da CMT. Remove a penalidade[n]para as estatísticas. de um aliado.[n][e]

[msg Item_025]
[s]Novo produto antisséptico[n]da CMT. Remove a penalidade[n]para as estatísticas. de um aliado.[n][e]

[msg Item_026]
[s]Causa 50 de dano de Fogo[n]a um inimigo. Alta chance de[n]infligir Queimaduras.[n][e]

[msg Item_027]
[s]Causa 50 de dano de Fogo[n]a todos os inimigos.[n][e]

[msg Item_028]
[s]Causa 50 de dano de gelo[n]a um inimigo. Alta chance de[n]infligir Congelamento.[n][e]

[msg Item_029]
[s]Causa 50[n]gelo de dano a todos os inimigos.[n][e]

[msg Item_02A]
[s]Causa 50 de dano de Vento[n]a um inimigo.[n][e]

[msg Item_02B]
[s]Causa 50 de dano de vento[n]a todos os inimigos.[n][e]

[msg Item_02C]
[s]Causa 50 de dano elétrico[n]a um inimigo. Alta chance de[n]infligir Choque.[n][e]

[msg Item_02D]
[s]Causa 50 de dano elétrico[n]a todos os inimigos.[n][e]

[msg Item_02E]
[s]Causa 100 de dano divino a todos os inimigos.[n][e]

[msg Item_02F]
[s]Chance média de[n]esta habilidade sagrada[n]matar um inimigo.[n][e]

[msg Item_030]
[s]Chance média de[n]esta habilidade amaldiçoada[n]matar um inimigo.[n][e]

[msg Item_031]
[s]Causa 150 de dano de Fogo[n]a um inimigo.[n][e]

[msg Item_032]
[s]Causa 150 de dano de Vento[n]a um inimigo.[n][e]

[msg Item_033]
[s]Causa 150[n]gelo de dano a um inimigo.[n][e]

[msg Item_034]
[s]Causa 150[n]de dano elétrico a um inimigo.[n][e]

[msg Item_035]
[s]Causa 50[n]dano psicocinético a um inimigo.[n][e]

[msg Item_036]
[s]Causa 50[n]dano psicocinético a todos[n]inimigos.[n][e]

[msg Item_037]
[s]Causa 50 de dano nuclear[n]a um inimigo.[n][e]

[msg Item_038]
[s]Causa 50 de dano nuclear[n]a todos os inimigos.[n][e]

[msg Item_039]
[s]Causa 50 de dano Sagrado[n]a um inimigo.[n][e]

[msg Item_03A]
[s]Causa 50 de dano Sagrado[n]a todos os inimigos.[n][e]

[msg Item_03B]
[s]Causa 50 de dano amaldiçoado a um inimigo.[n][e]

[msg Item_03C]
[s]Causa 50 de dano amaldiçoado a todos os inimigos.[n][e]

[msg Item_03D]
[s]Revive um aliado caído[n]com 50% HP.[n][e]

[msg Item_03E]
[s]Restaura 50 HP[n]de um aliado.[n][e]

[msg Item_03F]
[s]Nova droga CMT.[n]Revive um aliado[n]restaurando todo o HP.[n][e]

[msg Item_040]
[s]Proteção única[n]contra morte instantânea.[n][e]

[msg Item_041]
[s]não usado[n][e]

[msg Item_042]
[s]Nova droga CMT.[n]Revive todos[n]aliados caídos com 50% de HP.[n][e]

[msg Item_043]
[s]Nova droga CMT.[n]Reviva todos os aliados caídos[n]com HP total.[n][e]

[msg Item_044]
[s]Um óleo corporal. Cure[n]todos os acidentes. negativo[n]não especial de um aliado.[n][e]

[msg Item_045]
[s]não usado[n][e]

[msg Item_046]
[s]Um DVD player usado.[n]É antigo, mas funciona.[n]Falta o controle remoto.[n][e]

[msg Item_047]
[s]Um fertilizante econômico.[n]Para quem deseja cuidados básicos[n]com suas plantas.[n][e]

[msg Item_048]
[s]Um fertilizante caro. Para[n]aqueles que querem cuidar bem[n]das suas plantas.[n][e]

[msg Item_049]
[s]Fertilizante de primeira qualidade.[n]Para quem não poupa gastos[n]para cuidar das plantas.[n][e]

[msg Item_04A]
[s]Causa 150[n]dano psicocinético a um inimigo.[n][e]

[msg Item_04B]
[s]Causa 150 de dano nuclear[n]a um inimigo.[n][e]

[msg Item_04C]
[s]Causa 150 de dano Sagrado[n]a um inimigo.[n][e]

[msg Item_04D]
[s]Causa 150[n]dano amaldiçoado a um inimigo.[n][e]

[msg Item_04E]
[s]não utilizado[n][e]

[msg Item_04F]
[s]não utilizado[n][e]

[msg Item_050]
[s]Um conjunto de ferramentas[n]para reparar computadores.[n][e]

[msg Item_051]
[s]não utilizado[n][e]

[msg Item_052]
[s]Um frasco de[n]vidro colorido. Para os amantes[n]das flores.[n][e]

[msg Item_053]
[s]Espelho da sorte[n]em forma de estrela.[n]Para alguém espiritual.[n][e]

[msg Item_054]
[s]Um pack de snacks[n]disponíveis em vários sabores.[n]Para quem se sente jovem.[n][e]

[msg Item_055]
[s]Um guia que[n]vividamente representa a atmosfera[n]da antiga Cidade do Livro.[n][e]

[msg Item_056]
[s]Um livro cheio de truques[n]para comprar a preços baixos[n]pequenos eletrodomésticos.[n][e]

[msg Item_057]
[s]Um anel com uma gema  em forma de coração. Para[n]seduzir o coração de uma mulher.[n][e]

[msg Item_058]
[s]Um colar com uma gema em forma de coração. Para[n]seduzir o coração de uma mulher.[n][e]

[msg Item_059]
[s]Perfume de marca com um aroma[n]doce. Para uma pessoa[n]sensual em sua vida.[n][e]

[msg Item_05A]
[s]Luxuoso conjunto de aromaterapia[n]para relaxar a mente e o corpo[n]após um grande compromisso.[n][e]

[msg Item_05B]
[s]Cacto pequeno que[n]ficaria bem no escritório. Para aqueles que[n]trabalham em uma mesa.[n][e]

[msg Item_05C]
[s]Uma cesta cheia de flores de[n]todas as estações. Para[n]entusiastas de flores.[n][e]

[msg Item_05D]
[s]Aroma de rosas para um banheiro[n]luxuoso. Para a[n]mulher especial da sua vida.[n][e]

[msg Item_05E]
[s]Uma elegante caneca preta. Para[n]alguém que fica[n]em sua mesa.[n][e]

[msg Item_05F]
[s]Um pequeno leque com[n]um motivo floral. Para a mulher[n]tradicional.[n][e]

[msg Item_060]
[s]Linda caneta-tinteiro colocada[n]à venda mediante solicitação.[n]Para os olhos mais exigentes.[n][e]

[msg Item_061]
[s]Novo[n]robô aspirador de pó. Ele se limpa sozinho.[n]Para quem está ocupado com o trabalho.[n][e]

[msg Item_062]
[s]Um modelo em escala 1:12[n]altamente detalhado. Para[n]amantes de motos.[n][e]

[msg Item_063]
[s]Um conjunto de peluches com uma[n]personagem muito popular.[n]Para quem gosta de raridades.[n][e]

[msg Item_064]
[s]Aumenta a chance de[n]um aliado[n]ser alvo de inimigos.[n][e]

[msg Item_065]
[s]Ferramenta que permite[n]voltar à entrada[n]do Metaverso.[n][e]

[msg Item_066]
[s]não utilizado[n][e]

[msg Item_067]
[s]Permite que você evite[n]inimigos tornando-se in[n]detectável por um curto período de tempo.[n][e]

[msg Item_068]
[s]não utilizado[n][e]

[msg Item_069]
[s]Uma névoa que faz os inimigos dormirem.[n][e]

[msg Item_06A]
[s]Um tônico que relaxa o[n]inimigo. Reduz o nível de alerta[n]de um Palácio.[n][e]

[msg Item_06B]
[s]não usado[n][e]

[msg Item_06C]
[s]não usado[n][e]

[msg Item_06D]
[s]Uma bola de[n]fio de seda. Perfeito para[n]trabalho.[n][e]

[msg Item_06E]
[s]Pele animal usada para[n]transcrições e para a[n]fabricação de ferramentas.[n][e]

[msg Item_06F]
[s]Um prendedor de roupa de lata. Tem[n]o valor de um[n]objeto feito à mão.[n][e]

[msg Item_070]
[s]Óleo extraído de plantas.[n]Usado como combustível[n]para ferramentas mecânicas.[n][e]

[msg Item_071]
[s]Cortiça elástica. Pode ser[n]usado como um componente para[n]ferramentas.[n][e]

[msg Item_072]
[s]Limalhas de ferro com[n]propriedades magnéticas.[n]Usado para fazer aço.[n][e]

[msg Item_073]
[s]Lente que concentra[n]luz. Ótimo para instrumentos[n]que usam luz.[n][e]

[msg Item_074]
[s]Uma folha fina[n]de alumínio. Fácil de[n]usar.[n][e]

[msg Item_075]
[s]Pele animal muito[n]elástica. Muito útil para[n]criar ferramentas.[n][e]

[msg Item_076]
[s]Um[n]pó pirofórico tóxico usado para[n]induzir a combustão.[n][e]

[msg Item_077]
[s]Metal líquido usado[n]para fazer ferramentas.[n]Manuseie com cuidado.[n][e]

[msg Item_078]
[s]não utilizado[n][e]

[msg Item_079]
[s]Um livro de citações de[n]grandes filósofos. Leia e[n]adquira conhecimento.[n][e]

[msg Item_07A]
[s]Histórias aterrorizantes de[n]fantasmas. Se você os ler,[n]certamente ganhará coragem.[n][e]

[msg Item_07B]
[s]Best-seller de limpeza doméstica.[n]Vale a pena estudar a experiência do autor.[n][e]

[msg Item_07C]
[s]História comovente de um cachorro[n]e seu dono. Cheio de bondade.[n][e]

[msg Item_07D]
[s]não utilizado[n][e]

[msg Item_07E]
[s]não utilizado[n][e]

[msg Item_07F]
[s]Um jogo de boxe retrô.[n]Ao jogá-lo, você pode adquirir[n]o charme de um desafiante.[n][e]

[msg Item_080]
[s]O primeiro café com especiarias[n]do mundo. Restaura 10 HP[n]de um aliado.[n][e]

[msg Item_081]
[s]Shibuya River Water[n]filtrada 3 vezes. Restaure[n]10 HP para um aliado.[n][e]

[msg Item_082]
[s]Uma TV modelo antigo. O[n]controle remoto está faltando.[n][e]

[msg Item_083]
[s]não utilizado[n][e]

[msg Item_084]
[s]não utilizado[n][e]

[msg Item_085]
[s]A história de um grande[n]espadachim. Você se atreve a desafiar a morte?[n][e]

[msg Item_086]
[s]A referência[n]essencial[n]para quem trabalha[n]com flores.[n][e]

[msg Item_087]
[s]não utilizado[n][e]

[msg Item_088]
[s]não utilizado[n][e]

[msg Item_089]
[s]não utilizado[n][e]

[msg Item_08A]
[s]O épico de um incansável[n]buscador da sabedoria. Dê[n]conhecimento ao leitor.[n][e]

[msg Item_08B]
[s]A biografia de um amado[n]líder. Sua personalidade[n]expressa muita bondade.[n][e]

[msg Item_08C]
[s]A paixão meticulosa de um[n]técnico de automação. Pode[n]melhorar a experiência.[n][e]

[msg Item_08D]
[s]Livro sobre as[n]vicissitudes românticas de um galã.[n]Aprenda com seu charme.[n][e]

[msg Item_08E]
[s]não usado[n][e]

[msg Item_08F]
[s]Lixo simples. É[n]inútil mantê-lo.[n][e]

[msg Item_090]
[s]não usado[n][e]

[msg Item_091]
[s]não utilizado[n][e]

[msg Item_092]
[s]não utilizado[n][e]

[msg Item_093]
[s]Lanche japonês popular.[n]Restaura 20 HP de[n]um aliado.[n][e]

[msg Item_094]
[s]Uma Pedra Sagrada quebrada em[n]pedaços. Restaura 5 SP de[n]um aliado.[n][e]

[msg Item_095]
[s]Bilhete: necessário[n]para ver um filme[n]no cinema.[n][e]

[msg Item_096]
[s]bilhete de cinema 02[n][e]

[msg Item_097]
[s]bilhete de cinema 03[n][e]

[msg Item_098]
[s]bilhete de cinema 04[n][e]

[msg Item_099]
[s]não utilizado[n][e]

[msg Item_09A]
[s]não utilizado[n][e]

[msg Item_09B]
[s]Dez números consecutivos[n]para a loteria Summer[n]Mammoth.[n][e]

[msg Item_09C]
[s]Sanduíche redondo com cenouras[n]e castanhas. Restaura 200[n]HP de um aliado.[n][e]

[msg Item_09D]
[s]não utilizado[n][e]

[msg Item_09E]
[s]não utilizado[n][e]

[msg Item_09F]
[s]Reserve sobre o bairro antigo[n]renascido graças à[n]nova Tokyo Sky Tower.[n][e]

[msg Item_0A0]
[s]Um jogo de tiro retro[n]espacial. Jogá-lo pode[n]torná-lo mais corajoso.[n][e]

[msg Item_0A1]
[s]Livro que apresenta[n]parques estupendos para passar[n]um fim de semana tranquilo.[n][e]

[msg Item_0A2]
[s]Um jogo de tabuleiro retrô.[n]Jogá-lo pode torná-lo[n]mais gentil.[n][e]

[msg Item_0A3]
[s]Um jogo de luta[n]retro. Isso pode torná-lo[n]corajoso.[n][e]

[msg Item_0A4]
[s]2 episódios. Um cadáver esconde pistas decisivas. Inteligentes[n]deduções resolvem o caso.[n][e]

[msg Item_0A5]
[s]Três episódios. A mais recente[n]tecnologia forense revela a[n]chave para o mistério.[n][e]

[msg Item_0A6]
[s]Uma garota feia[n]conquista a todos graças ao[n]seu charme interior.[n][e]

[msg Item_0A7]
[s]Drama adolescente muito realista. Assistir a[n]histórias de amor aumenta o fascínio.[n][e]

[msg Item_0A8]
[s]Drama comovente que[n]se desenrola no pronto-socorro.[n]Ensina gentileza.[n][e]

[msg Item_0A9]
[s]não usado[n][e]

[msg Item_0AA]
[s]Apenas em dias chuvosos.[n]Natto cristalizado. Restaura[n]80 HP de todos os aliados.[n][e]

[msg Item_0AB]
[s]Pacote de ótimo lanche[n]lula. Restaura[n]20 HP de todos os aliados.[n][e]

[msg Item_0AC]
[s]Um conjunto de broches de um ídolo emergente[n]pop.[n]Para amigos preocupados com a moda.[n][e]

[msg Item_0AD]
[s]não usado[n][e]

[msg Item_0AE]
[s]não usado[n][e]

[msg Item_0AF]
[s]não usado[n][e]

[msg Item_0B0]
[s]Um guia ilustrado dos[n]santuários espalhados pela[n]grande cidade.[n][e]

[msg Item_0B1]
[s]Um manual para iniciantes[n]listando os lagos de pesca mais conhecidos.[n][e]

[msg Item_0B2]
[s]Uma revista que coleta[n]várias informações sobre[n]Yongen-Jaya.[n][e]

[msg Item_0B3]
[s]Manual para observação de estrelas[n]com um especial[n]on planetários.[n][e]

[msg Item_0B4]
[s][n]fantoche elfo do gelo, cujo doce sorriso[n]derreterá seu coração.[n][e]

[msg Item_0B5]
[s][n]fantoche de mascote do Big Bang Burger. Ir direto para o Big Bang.[n][e]

[msg Item_0B6]
[s]Mascote de uma agência de segurança. As pessoas[n]gostam de sua aparência duvidosa.[n][e]

[msg Item_0B7]
[s]Um fantoche muito peculiar[n]que se tornou popular graças[n]a sua aparência assustadora.[n][e]

[msg Item_0B8]
[s]Uma sobremesa feita com chá matcha verde Uji. Para os mais[n]gulosos.[n][e]

[msg Item_0B9]
[s]Trufas de chocolate[n]preparadas com muito carinho.[n]Para quem gosta de doces.[n][e]

[msg Item_0BA]
[s]não usado[n][e]

[msg Item_0BB]
[s]Aumenta muito a chance[n]de que um aliado possa[n]ser alvo de inimigos.[n][e]

[msg Item_0BC]
[s]não utilizado[n][e]

[msg Item_0BD]
[s]não utilizado[n][e]

[msg Item_0BE]
[s]Água usada em rituais.[n]Remove todos os bônus para[n]estatísticas. de todos os inimigos.[n][e]

[msg Item_0BF]
[s]Água benta purificada.[n]Remove todas as penalidades para[n]estatísticas. de todos os aliados.[n][e]

[msg Item_0C0]
[s]Vinho sem álcool para[n]cerimónias. Restaura todo[n]HP para todos os aliados.[n][e]

[msg Item_0C1]
[s]Cura todas as doenças não especiais[n]negativas de[n]todos os aliados.[n][e]

[msg Item_0C2]
[s]Apenas em dias de chuva.[n]É super macio! Restaura[n]200 HP de um aliado.[n][e]

[msg Item_0C3]
[s]Estilo japonês[n]capa de livro de papel crepom.[n]Para a mulher tradicional.[n][e]

[msg Item_0C4]
[s]Pão-de-ló[n]polvilhado com[n]açúcar em bruto. Para o dente doce.[n][e]

[msg Item_0C5]
[s]Um batom escarlate de[n]uma modelo famosa.[n]Para quem entende de moda.[n][e]

[msg Item_0C6]
[s]não utilizado[n][e]

[msg Item_0C7]
[s]não utilizado[n][e]

[msg Item_0C8]
[s]Anula as barreiras de um[n]inimigo que repelem[n]ataques físicos.[n][e]

[msg Item_0C9]
[s]Anula as barreiras de um[n]inimigo que repelem[n]ataques mágicos.[n][e]

[msg Item_0CA]
[s]não utilizado[n][e]

[msg Item_0CB]
[s]não utilizado[n][e]

[msg Item_0CC]
[s]não utilizado[n][e]

[msg Item_0CD]
[s]não utilizado[n][e]

[msg Item_0CE]
[s]não utilizado[n][e]

[msg Item_0CF]
[s]não usado[n][e]

[msg Item_0D0]
[s]não utilizado[n][e]

[msg Item_0D1]
[s]não utilizado[n][e]

[msg Item_0D2]
[s]Vara simples, mas robusta.[n]Torna um pouco mais fácil[n]a pescar.[n][e]

[msg Item_0D3]
[s]Uma vara muito forte.[n]Facilita ainda mais[n]a pesca.[n][e]

[msg Item_0D4]
[s]Vara de nova geração.[n]Torna super fácil[n]a pesca.[n][e]

[msg Item_0D5]
[s]Contém arginina.[n]Restaura 5 SP de[n]um aliado.[n][e]

[msg Item_0D6]
[s]Agora com mais pimenta.[n]Restaura 20 HP de[n]um aliado.[n][e]

[msg Item_0D7]
[s]Incrivelmente nutritivo.[n]Restaura 10 HP de[n]um aliado.[n][e]

[msg Item_0D8]
[s]Restaura 30% do HP de um aliado.[n]Aumenta a Evasão e[n]Precisão, reduz o Atk..[n][e]

[msg Item_0D9]
[s]Restaura 30% do HP de um aliado.[n]Reduz a Evasão e[n]Precisão, aumenta o Atk.[n][e]

[msg Item_0DA]
[s]Delicioso e nutritivo.[n]Restaura 50 HP e cura[n]a fome de um aliado.[n][e]

[msg Item_0DB]
[s]Restaura 30% do HP[n]de um aliado. Boost[n]Atk. e reduz a defesa.[n][e]

[msg Item_0DC]
[s]Os ácidos graxos ômega-3[n]ajudam a aumentar[n]seu conhecimento.[n][e]

[msg Item_0DD]
[s]Graças ao colágeno,[n]você poderá brilhar[n]com charme.[n][e]

[msg Item_0DE]
[s]As algas marinhas[n]minerais revitalizam[n]você e aumentam sua experiência.[n][e]

[msg Item_0DF]
[s]Contém melão amargo.[n]É preciso coragem para beber[n]esta tremenda mistura.[n][e]

[msg Item_0E0]
[s]Contém água termal.[n]Você quase pode sentir a[n]bondade dentro de você.[n][e]

[msg Item_0E1]
[s]não utilizado[n][e]

[msg Item_0E2]
[s]Uma mordida satisfaz[n]o estômago. Cura um aliado faminto.[n][e]

[msg Item_0E3]
[s]Dez números aleatórios para a[n]loteria mamute de verão.[n][e]

[msg Item_0E4]
[s]Pirulito Refrescante.[n]Cura[n]o Desespero de um aliado.[n][e]

[msg Item_0E5]
[s]Uma pedra misteriosa.[n]Cura o congelamento de um aliado.[n][e]

[msg Item_0E6]
[s]Uma esfera estranha. Cure um aliado em chamas.[n][e]

[msg Item_0E7]
[s]Um cristal misterioso.[n]Cura um aliado[n]em estado de choque.[n][e]

[msg Item_0E8]
[s]O sabor da tangerina é[n]refrescante. Restaura[n]10 HP de um aliado.[n][e]

[msg Item_0E9]
[s]não utilizado[n][e]

[msg Item_0EA]
[s]Sanduíche de Yon-Germain.[n]Restaura 10 HP de[n]um aliado.[n][e]

[msg Item_0EB]
[s]Uma massa com frutas.[n]Restaura 30 HP de[n]um aliado.[n][e]

[msg Item_0EC]
[s]não utilizado[n][e]

[msg Item_0ED]
[s]Pão é abocanhado.[n]Restaura 50 HP e cura[n]Fome de um aliado.[n][e]

[msg Item_0EE]
[s]Uma bebida que acaba com a[n]sonolência. Cura um aliado adormecido.[n][e]

[msg Item_0EF]
[s]Uma mistura de chás orientais[n]ocidentais. Restaura[n]10 HP de um aliado.[n][e]

[msg Item_0F0]
[s]Basicamente é cafeína[n]líquida. Restaura 10 HP[n]de um aliado.[n][e]

[msg Item_0F1]
[s]Chá popular, muito vendido[n]online. Restaura 10 HP de[n]um aliado.[n][e]

[msg Item_0F2]
[s]Dá vontade de dançar a noite toda. Restaura[n]10 HP de um aliado.[n][e]

[msg Item_0F3]
[s]Inesperadamente, tem um gosto[n]ótimo. Restaura[n]10 HP de um aliado.[n][e]

[msg Item_0F4]
[s]Preferido pelos jogadores da[n]velha guarda. Restaura[n]10 HP de um aliado.[n][e]

[msg Item_0F5]
[s]Um jogo de azar retrô.[n]Jogá-lo pode torná-lo[n]mais glamoroso.[n][e]

[msg Item_0F6]
[s]Um jogo de golfe retrô.[n]Jogá-lo pode[n]aumentar sua proficiência no golfe.[n][e]

[msg Item_0F7]
[s]Um cartão postal que se parece com[n]uma carta de aviso.[n]Envie para um ente querido.[n][e]

[msg Item_0F8]
[s]Cura todas as habilidades não especiais[n]negativas[n]de um aliado.[n][e]

[msg Item_0F9]
[s]Aumenta a eficácia de[n]treinos. Restaura[n]30% do HP de um aliado.[n][e]

[msg Item_0FA]
[s]Só quando chove. Facilita[n]o treinamento. Restaura[n]30% HP para um aliado.[n][e]

[msg Item_0FB]
[s]Um pão com[n]sabor nostálgico. Restaura 10[n]HP de um aliado.[n][e]

[msg Item_0FC]
[s]não utilizado[n][e]

[msg Item_0FD]
[s]não usado[n][e]

[msg Item_0FE]
[s]não usado[n][e]

[msg Item_0FF]
[s]não utilizado[n][e]

[msg Item_100]
[s]não utilizado[n][e]

[msg Item_101]
[s]não utilizado[n][e]

[msg Item_102]
[s]não utilizado[n][e]

[msg Item_103]
[s]não utilizado[n][e]

[msg Item_104]
[s]não utilizado[n][e]

[msg Item_105]
[s]não utilizado[n][e]

[msg Item_106]
[s]não utilizado[n][e]

[msg Item_107]
[s]não utilizado[n][e]

[msg Item_108]
[s]não utilizado[n][e]

[msg Item_109]
[s]não usado[n][e]

[msg Item_10A]
[s]Para aqueles que almejam[n]estrelas. Velocidade da[n]bola: 140 km/h.[n][e]

[msg Item_10B]
[s]O derradeiro desafio das[n]gaiolas de rebatidas. Velocidade[n]da bola: 165 km/h.[n][e]

[msg Item_10C]
[s]Para iniciantes. Velocidade da bola[n]: 69 km/h.[n][e]

[msg Item_10D]
[s]Para rebatedores intermediários.[n]Velocidade da bola:[n]88 km/h.[n][e]

[msg Item_10E]
[s]Para rebatedores de nível avançado. Velocidade da[n]bola: 109 km/h.[n][e]

[msg Item_10F]
[s]Prato especial com pasta de camarão.[n]Para quem[n]tem coragem de se mimar.[n][e]

[msg Item_110]
[s]Salisbury Steak, do jeito que a vovó fazia. Você pode[n]sentir sua bondade.[n][e]

[msg Item_111]
[s]Chá com muita fruta.[n]Suaviza a pele e[n]torna-te mais charmosa.[n][e]

[msg Item_112]
[s]Terminar a torre de sorvete[n]sem deixá-la cair aumenta[n]sua perícia.[n][e]

[msg Item_113]
[s]Café cheio de amor. Mesmo[n]uma empregada desajeitada pode[n]prepará-lo com muita facilidade.[n][e]

[msg Item_114]
[s]Um chá cheio de amor. Mesmo[n]uma empregada desajeitada pode[n]prepará-lo facilmente.[n][e]

[msg Item_115]
[s]Na mesa é servido chantilly. Difícil[n]para uma empregada desajeitada.[n][e]

[msg Item_116]
[s]Inclui uma decoração de col ketchup. Um pouco[n]demais para uma empregada desajeitada.[n][e]

[msg Item_117]
[s]não usado[n][e]

[msg Item_118]
[s]não utilizado[n][e]

[msg Item_119]
[s]não utilizado[n][e]

[msg Item_11A]
[s]não utilizado[n][e]

[msg Item_11B]
[s]não utilizado[n][e]

[msg Item_11C]
[s]não utilizado[n][e]

[msg Item_11D]
[s]não utilizado[n][e]

[msg Item_11E]
[s]não utilizado[n][e]

[msg Item_11F]
[s]não utilizado[n][e]

[msg Item_120]
[s]não utilizado[n][e]

[msg Item_121]
[s]não utilizado[n][e]

[msg Item_122]
[s]não utilizado[n][e]

[msg Item_123]
[s]não utilizado[n][e]

[msg Item_124]
[s]não usado[n][e]

[msg Item_125]
[s]não usado[n][e]

[msg Item_126]
[s]não usado[n][e]

[msg Item_127]
[s]não usado[n][e]

[msg Item_128]
[s]não usado[n][e]

[msg Item_129]
[s]não usado[n][e]

[msg Item_12A]
[s]não usado[n][e]

[msg Item_12B]
[s]não usado[n][e]

[msg Item_12C]
[s]não usado[n][e]

[msg Item_12D]
[s]não usado[n][e]

[msg Item_12E]
[s]não usado[n][e]

[msg Item_12F]
[s]não usado[n][e]

[msg Item_130]
[s]não usado[n][e]

[msg Item_131]
[s]não usado[n][e]

[msg Item_132]
[s]não usado[n][e]

[msg Item_133]
[s]Isca de peixe pequeno.[n]Pegue apenas peixes pequenos.[n][e]

[msg Item_134]
[s]Isca de peixe de tamanho médio.[n]Pode pegar peixes de tamanho médio.[n][e]

[msg Item_135]
[s]Big Fish Bait.[n]Pesque peixes grandes.[n][e]

[msg Item_136]
[s]Isca saborosa para pescar[n]peixes normais de qualquer[n]tamanho.[n][e]

[msg Item_137]
[s]Uma isca específica para o[n]Guardião. Não mais[n]peixe vai morder.[n][e]

[msg Item_138]
[s]Uma explosão de sabor![n]Restaura 20 HP de todos[n]aliados.[n][e]

[msg Item_139]
[s][n]Batata com anéis de cebola semelhante a Saturno.[n]Restaura 20 HP de um aliado.[n][e]

[msg Item_13A]
[s]Só na primavera. Cheio de[n]vegetais. Restaura 40 HP[n]de todos os aliados.[n][e]

[msg Item_13B]
[s]não utilizado[n][e]

[msg Item_13C]
[s]Só no outono. O ovo[n]lembra-se da lua. Restaura[n]120 HP de todos os aliados.[n][e]

[msg Item_13D]
[s]Novo hambúrguer da renascida[n]Okumura Foods. Restaura[n]200 HP de todos os aliados.[n][e]

[msg Item_13E]
[s]Tão bom que é digno de um rei. Restaura 10 HP[n]de um aliado.[n][e]

[msg Item_13F]
[s]Só na primavera. Cheio de[n]frutas. Restaura 80 HP[n]de todos os aliados.[n][e]

[msg Item_140]
[s]Apesar do nome, é um kebab. Restaura 20 HP[n]de um aliado.[n][e]

[msg Item_141]
[s]Phantom Thieves Snack.[n]Restaura 50 HP de um aliado.[n]e cura suas doenças.[n][e]

[msg Item_142]
[s]Macarrão chinês frio.[n]Disponível apenas no verão.[n]Restaura 200 HP de um aliado.[n][e]

[msg Item_143]
[s]Tasty Oden, disponível[n]somente no inverno. Restaura[n]50 HP de todos os aliados.[n][e]

[msg Item_144]
[s]Comida enlatada para comer em grupo. Restaura[n]40 HP de todos os aliados.[n][e]

[msg Item_145]
[s]Câmera de última geração.[n]Tire fotos em qualquer lugar![n]Para profissionais.[n][e]

[msg Item_146]
[s]Massajador capaz de[n]afinar o rosto. Para aqueles[n]que procuram os holofotes.[n][e]

[msg Item_147]
[s]Um laptop consertado.[n]Você pode usá-lo para se conectar[n]ao Shady Business.[n][e]

[msg Item_148]
[s]não utilizado[n][e]

[msg Item_149]
[s]Miniatura de dominação.[n][e]

[msg Item_14A]
[s]A miniatura de um Daisoujou moribundo.[n][e]

[msg Item_14B]
[s]Uma miniatura de Decarabia[n]embelezada com decalques.[n][e]

[msg Item_14C]
[s]Miniatura de Girimehkala[n]com equipamento aleatório[n][e]

[msg Item_14D]
[s]Um Kin-ki excêntrico em[n]miniatura.[n][e]

[msg Item_14E]
[s]Um Mothman em miniatura[n]tentando recriar[n]sua fofura.[n][e]

[msg Item_14F]
[s]bilhete de cinema 16[n][e]

[msg Item_150]
[s]Ferramenta que pode abrir[n]um baú trancado.[n][e]

[msg Item_151]
[s]Ferramenta que pode abrir[n]uma quantidade indefinida de[n]baús trancados.[n][e]

[msg Item_152]
[s](cut)[n][e]

[msg Item_153]
[s]não utilizado[n][e]

[msg Item_154]
[s]Aumenta as chances de[n]encontrar Demônios do Tesouro nos Palácios.[n][e]

[msg Item_155]
[s]não utilizado[n][e]

[msg Item_156]
[s]Um peixe dourado.[n][e]

[msg Item_157]
[s]Uma carpa escamosa.[n][e]

[msg Item_158]
[s]Um ciprinídeo elegante.[n][e]

[msg Item_159]
[s]Uma truta que brilha em sete cores diferentes.[n][e]

[msg Item_15A]
[s]Uma carpa que parece capaz de[n]flutuar ao[n]vento.[n][e]

[msg Item_15B]
[s]Uma truta que parece[n]pode ser vendida por um bom[n]preço.[n][e]

[msg Item_15C]
[s]Um ciprinídeo de sabor incomparável.[n][e]

[msg Item_15D]
[s]Uma carpa cheia de[n]poder.[n][e]

[msg Item_15E]
[s]O peixe lendário que[n]age como o deus protetor[n]do país.[n][e]

[msg Item_15F]
[s]Um adesivo normal.[n]Restaura 20 HP de[n]um aliado.[n][e]

[msg Item_160]
[s]não utilizado[n][e]

[msg Item_161]
[s]Use apenas em locais seguros.[n]Restaura 100% do[n]HP de todos os aliados.[n][e]

[msg Item_162]
[s]Um café[n]percolado especial. Restaura 30 SP[n]de um aliado.[n][e]

[msg Item_163]
[s]não utilizado[n][e]

[msg Item_164]
[s]não usado[n][e]

[msg Item_165]
[s]Um café[n]percolado especial. Restaura 100[n]SP de um aliado.[n][e]

[msg Item_166]
[s]Um curry quase no nível[n]do Leblanc. Restaura[n]20 SP para todos os aliados.[n][e]

[msg Item_167]
[s]O sabor é idêntico ao da roupa. Restaura[n]50 SP para todos os aliados.[n][e]

[msg Item_168]
[s]Um curry que supera o[n]gosto do patrão. Restaure[n]100 SPs de todos os al.[n][e]

[msg Item_169]
[s]não usado[n][e]

[msg Item_16A]
[s]Obtido de Star Forneus.[n]Um fã[n]apreciaria seu valor.[n][e]

[msg Item_16B]
[s]Use apenas em locais seguros.[n]Restaura 50% do[n]HP de todos os aliados.[n][e]

[msg Item_16C]
[s]Obtido no Train of Life.[n]Um fã[n]apreciaria seu valor.[n][e]

[msg Item_16D]
[s]Obtido do Poder[n]Intuição. Um entusiasta[n]sabe apreciar seu valor.[n][e]

[msg Item_16E]
[s]não usado[n][e]

[msg Item_16F]
[s]Obtido de Punch Ouch.[n]Um fã[n]apreciaria seu valor.[n][e]

[msg Item_170]
[s]Obtido de Gambla Goemon.[n]Um fã[n]apreciaria seu valor.[n][e]

[msg Item_171]
[s]Obtido do jogador de golfe[n]Sarutahiko. Um entusiasta[n]sabe apreciar seu valor.[n][e]

[msg Item_172]
[s]Extensa antologia sobre[n]pensamento social moderno.[n]Pode expandir o conhecimento.[n][e]

[msg Item_173]
[s]não usado[n][e]

[msg Item_174]
[s]não utilizado[n][e]

[msg Item_175]
[s]não utilizado[n][e]

[msg Item_176]
[s]Análise aprofundada da[n]piada. Pode melhorar[n]sua habilidade no beisebol.[n][e]

[msg Item_177]
[s]Um livro que explica[n]os truques da pesca. Agora[n]você pode ser um mestre![n][e]

[msg Item_178]
[s]Técnicas de leitura rápida e fácil. Isso aumentará sua[n]velocidade de leitura.[n][e]

[msg Item_179]
[s]Um guia completo sobre como[n]dar peso emocional[n]às suas fotos. Para cinéfilos.[n][e]

[msg Item_17A]
[s]não utilizado[n][e]

[msg Item_17B]
[s]Um guia de doces[n]que podem ser encontrados[n]em Chinatown.[n][e]

[msg Item_17C]
[s]Um livro que ajuda a não[n]perder ao visitar[n]um parque de diversões.[n][e]

[msg Item_17D]
[s]Romance sobre Arsene. Seus[n]truques inteligentes aumentam[n]seu conhecimento.[n][e]

[msg Item_17E]
[s]A história do destemido Capitão Kidd. A leitura[n]aumentará sua coragem.[n][e]

[msg Item_17F]
[s]A história de Zorro, o[n]cavalheiro bandido. Leia-o[n]para se tornar mais gentil.[n][e]

[msg Item_180]
[s]A história apaixonante de[n]Carmen. Para quem quer[n]ser fascinado.[n][e]

[msg Item_181]
[s]A história de Ishikawa Goemon. É preciso coragem[n]para desafiar o poder.[n][e]

[msg Item_182]
[s]A dinâmica biografia de[n]Giovanna. Desperte sua[n]bondade.[n][e]

[msg Item_183]
[s]Um Livro de Mitos. O[n]mundo macabro fortalecerá[n]sua coragem.[n][e]

[msg Item_184]
[s]A história de Milady. Suas[n]mil faces irão ajudá-lo a[n]desenvolver expertise.[n][e]

[msg Item_185]
[s]A lenda de Robin Hood.[n]Lê-lo pode[n]dar-lhe coragem.[n][e]

[msg Item_186]
[s]Livro sobre o grupo de hackers[n]Medjed. Para um conhecimento[n]dos crimes na Internet.[n][e]

[msg Item_187]
[s]Aprenda com um grande galã[n]e adquira o charme para[n]seduzir qualquer um.[n][e]

[msg Item_188]
[s]Uma coleção de truques[n]para todos os videogames.[n]Facilita o jogo.[n][e]

[msg Item_189]
[s]Dez números aleatórios para a loteria Mammoth[n]anual.[n][e]

[msg Item_18A]
[s]Dez números consecutivos[n]para a loteria anual[n]Mammoth.[n][e]

[msg Item_18B]
[s]Um bilhete de raspadinha[n]para a loteria Mammoth.[n]Resultados instantâneos.[n][e]

[msg Item_18C]
[s]não usado[n][e]

[msg Item_18D]
[s]não usado[n][e]

[msg Item_18E]
[s]não usado[n][e]

[msg Item_18F]
[s]A história de uma mulher[n]que fala com fantasmas.[n]Ensina bondade.[n][e]

[msg Item_190]
[s]Um drama sobre uma fuga da[n]prisão. Aprenda com a[n]experiência deles na clandestinidade.[n][e]

[msg Item_191]
[s]História de um homem dotado de[n]grande habilidade em criar[n]instrumentos do nada.[n][e]

[msg Item_192]
[s]Um filme de terror. Testemunhar[n]a invasão zumbi[n]irá fortalecer sua coragem.[n][e]

[msg Item_193]
[s]Investigadores lutando[n]com casos sobrenaturais.[n]Inspira você com coragem.[n][e]

[msg Item_194]
[s]não usado[n][e]

[msg Item_195]
[s]não usado[n][e]

[msg Item_196]
[s]não usado[n][e]

[msg Item_197]
[s]não usado[n][e]

[msg Item_198]
[s]não usado[n][e]

[msg Item_199]
[s]não usado[n][e]

[msg Item_19A]
[s]não utilizado[n][e]

[msg Item_19B]
[s]não utilizado[n][e]

[msg Item_19C]
[s]Uma revista de moda para[n]meninas com[n]gostos originais.[n][e]

[msg Item_19D]
[s]Uma revista que apresenta[n]ótimos locais de encontro[n]para adultos.[n][e]

[msg Item_19E]
[s]Sugue o calor[n]da sua cabeça. Cure um aliado em chamas.[n][e]

[msg Item_19F]
[s]Uma compressa quente para membros gelados. Cura um aliado congelado.[n][e]

[msg Item_1A0]
[s]Uma salada digna de uma[n]dea. Restaura 30 HP[n]de um aliado.[n][e]

[msg Item_1A1]
[s]Restaura 50 HP de um[n]aliado e reduz a precisão[n]e a evasão.[n][e]

[msg Item_1A2]
[s]Restaura 100 HP de um[n]aliado e reduz o ataque.[n][e]

[msg Item_1A3]
[s]Restaura 200 HP de um aliado e reduz a defesa.[n][e]

[msg Item_1A4]
[s]Um colírio que ajuda você a ver claramente. Cura a[n]tontura de um aliado.[n][e]

[msg Item_1A5]
[s]Donuts que dão[n]alívio. Cura um aliado assustado.[n][e]

[msg Item_1A6]
[s]Estimula a memória a partir das gengivas. Cure[n]um aliado esquecido.[n][e]

[msg Item_1A7]
[s]Um chá que acaba com a[n]sonolência. Cura um aliado adormecido.[n][e]

[msg Item_1A8]
[s]Um presente de Shinya.[n]Bunny Balloons[n]recebi em Destinyland.[n][e]

[msg Item_1A9]
[s]Um biscoito. Restaura[n]10% do SP de um aliado.[n]Reduz precisão/evasão.[n][e]

[msg Item_1AA]
[s]Enlatado por um tempo.[n]Retorna 10% de SP para[n]um aliado. Reduz a dif.[n][e]

[msg Item_1AB]
[s]Não é achocolatado. Devolva[n]10% de SP para um[n]aliado. Reduz Atk.[n][e]

[msg Item_1AC]
[s]Restaura 50 HP e cura[n]Fome de um aliado.[n][e]

[msg Item_1AD]
[s]não utilizado[n][e]

[msg Item_1AE]
[s]não utilizado[n][e]

[msg Item_1AF]
[s]Feito com o rei das[n]frutas. Restaura 10 HP[n]de um aliado.[n][e]

[msg Item_1B0]
[s]Tão bom que você[n]diz "Uau!" Restaura 20[n]HP de um aliado.[n][e]

[msg Item_1B1]
[s]Você nunca pode beber[n]todas as sementes. Restaura[n]20 HP de um aliado.[n][e]

[msg Item_1B2]
[s]Isso faz você pensar que está bêbado. Restaura 20 HP[n]de um aliado.[n][e]

[msg Item_1B3]
[s]Água de Shibuya filtrada 3[n]vezes e gaseificada. Restaura[n]30 HP de um aliado.[n][e]

[msg Item_1B4]
[s]Contém placenta.[n]Restaura 5 SP de[n]um aliado.[n][e]

[msg Item_1B5]
[s]não utilizado[n][e]

[msg Item_1B6]
[s]não utilizado[n][e]

[msg Item_1B7]
[s]não usado[n][e]

[msg Item_1B8]
[s]não usado[n][e]

[msg Item_1B9]
[s]Restaura 100 HP de um[n]aliado. Reduz defesa,[n]precisão e evasão.[n][e]

[msg Item_1BA]
[s]Restaura 100 HP de um[n]aliado. Reduz ataque,[n]precisão e evasão.[n][e]

[msg Item_1BB]
[s]Restaura 100 HP de um[n]aliado. Reduz ataque[n]e defesa.[n][e]

[msg Item_1BC]
[s]O que ele conterá? Restaura[n]30% SP para um aliado.[n]Reduz todas as estatísticas.[n][e]

[msg Item_1BD]
[s]Um café amargo.[n]Restaura 30 SP de[n]um aliado.[n][e]

[msg Item_1BE]
[s]Um café muito amargo.[n]Restaura 30 SP de[n]um aliado.[n][e]

[msg Item_1BF]
[s]Semelhante ao Leblanc,[n]mas muito picante. Restaure[n]20 SP para todos os aliados.[n][e]

[msg Item_1C0]
[s]É como o do patrão,[n]mas muito picante. Restaure[n]50 SP para todos os aliados.[n][e]

[msg Item_1C1]
[s]Supera o do patrão, mas[n]é bem picante. Restaure[n]50 SP para todos os aliados.[n][e]

[msg Item_1C2]
[s]Presente de Ryuji. Amostra[n]de comida falsa em um[n]restaurante em Ogikubo.[n][e]

[msg Item_1C3]
[s]Um presente de Kawakami.[n]A visão noturna do[n]Seaside Park.[n][e]

[msg Item_1C4]
[s]Um presente de Yusuke.[n]Uma cópia de uma escultura[n]em um museu.[n][e]

[msg Item_1C5]
[s]Presente de Iwai. Um[n]barco em miniatura[n]em forma de cisne.[n][e]

[msg Item_1C6]
[s]Um presente de Chihaya.[n]Uma lâmpada na forma de uma Sky[n]Tower em escala 1:4000.[n][e]

[msg Item_1C7]
[s]Presente de Haru. Espátula de[n]um lugar monjayaki[n]cujo uso requer habilidade.[n][e]

[msg Item_1C8]
[s]Presente da Ann. O pôster de[n]um ídolo de primeira[n]magnitude.[n][e]

[msg Item_1C9]
[s]Um presente de Yusuke.[n]Constelações que brilham[n]no escuro com um guia.[n][e]

[msg Item_1CA]
[s]Um presente de Hifumi.[n]Uma cópia gigante de madeira[n]de um rei shogi.[n][e]

[msg Item_1CB]
[s]Um presente da Futaba. A[n]miniatura de um herói[n]para se inspirar.[n][e]

[msg Item_1CC]
[s]Um presente de Yusuke. Uma[n]flecha do Santuário Meiji[n]que destrói o mal.[n][e]

[msg Item_1CD]
[s]Um presente da Futaba. Uma camiseta[n]souvenir, impressa[n]em inglês.[n][e]

[msg Item_1CE]
[s]Borracha que acalma o corpo e a alma. Cura um aliado chocado.[n][e]

[msg Item_1CF]
[s]não usado[n][e]

[msg Item_1D0]
[s]não usado[n][e]

[msg Item_1D1]
[s]não usado[n][e]

[msg Item_1D2]
[s]Chocolate feito à mão por Kawakami. Restaura[n]totalmente o SP de um aliado.[n][e]

[msg Item_1D3]
[s]Delicioso chocolate de[n]parte de Takemi. Restaura[n]todos os SPs de um aliado.[n][e]

[msg Item_1D4]
[s]Delicioso chocolate de[n]parte de Chihaya. Devolva[n]todos os SP para um aliado.[n][e]

[msg Item_1D5]
[s]Delicioso chocolate da parte de[n]oya. Restaura[n]todos os SPs de um aliado.[n][e]

[msg Item_1D6]
[s]Chocolate feito à mão por[n]Hifumi. Restaura totalmente o SP de um aliado.[n][e]

[msg Item_1D7]
[s]Delicioso chocolate de[n]parte de Makoto. Restaura[n]todos os SPs de um aliado.[n][e]

[msg Item_1D8]
[s]Chocolate feito à mão por[n]Haru. Restaura totalmente o SP de um aliado.[n][e]

[msg Item_1D9]
[s]Delicioso chocolate da parte de[n]Ann. Restaura[n]todos os SPs de um aliado.[n][e]

[msg Item_1DA]
[s]Chocolate artesanal da[n]Futaba. Restaura totalmente o SP de um aliado.[n][e]

[msg Item_1DB]
[s]Chocolate barato da parte de[n]Ryuji. Restaura[n]10 SP de um aliado.[n][e]

[msg Item_1DC]
[s]Chocolate barato de[n]de Sojiro. Restaura[n]10 SP de um aliado.[n][e]

[msg Item_1DD]
[s]Um presente de Haru.[n]Amuleto da sorte vendido no festival[n]Tori no Ichi.[n][e]

[msg Item_1DE]
[s]Um presente de Makoto. Um[n]travesseiro inspirado em um[n]clássico de Chinatown.[n][e]

[msg Item_1DF]
[s]Um presente de Makoto.[n]Um mascote do time[n]encontrado em Dome Town.[n][e]

[msg Item_1E0]
[s]Um presente de Ohya. Um copo[n]impresso com nomes de peixes,[n]usado em bares de sushi.[n][e]

[msg Item_1E1]
[s]Um presente de Ann.[n]O prêmio original para o[n]milhãoésimo cliente.[n][e]

[msg Item_1E2]
[s]não usado[n][e]

[msg Item_1E3]
[s]não utilizado[n][e]

[msg Item_1E4]
[s]não usado[n][e]

[msg Item_1E5]
[s]Este sistema é necessário[n]para reproduzir títulos[n]para FD.[n][e]

[msg Item_1E6]
[s]não usado[n][e]

[msg Item_1E7]
[s]Homem-Ovelha[n]fantoche com uma expressão preocupada.[n][e]

[msg Item_1E8]
[s]Pão de geléia de morango. Restaura[n]20 HP de um aliado.[n][e]

[msg Item_1E9]
[s]Produto raro que regenera.[n]Revive um aliado caído[n]restaurando todo o HP.[n][e]

[msg Item_1EA]
[s]Um Bolo de Natal.[n]Revive um aliado caído[n]recuperando todo o HP.[n][e]

[msg Item_1EB]
[s]Fórmula de ação rápida.[n]Restaura 200 HP de[n]um aliado.[n][e]

[msg Item_1EC]
[s]Jarra com frutas secas[n]de vários tipos. Restaura[n]40 HP de todos os aliados.[n][e]

[msg Item_1ED]
[s]Batata doce pegajosa[n]baixa em fibras. Restaura[n]10 SP de um aliado.[n][e]

[msg Item_1EE]
[s]Batata-doce típica[n]assada no inverno. Restaura[n]50 SP de um aliado.[n][e]

[msg Item_1EF]
[s]não usado[n][e]

[msg Item_1F0]
[s]não usado[n][e]

[msg Item_1F1]
[s]não usado[n][e]

[msg Item_1F2]
[s]não usado[n][e]

[msg Item_1F3]
[s]Uma cenoura difícil de cultivar. Restaura[n]totalmente o SP de um aliado.[n][e]

[msg Item_1F4]
[s]Um tomate difícil de[n]cultivar. Restaura 100[n]SP de todos os aliados.[n][e]

[msg Item_1F5]
[s]Um feijão difícil de[n]cultivar. Dobra os ataques físicos[n]uma vez.[n][e]

[msg Item_1F6]
[s]Uma cebola difícil de[n]cultivar. Dobra os ataques mágicos uma vez.[n][e]

[msg Item_1F7]
[s]não usado[n][e]

[msg Item_1F8]
[s]Beignets de Ann[n]estilo takoyaki. Restaura 100 SP[n]de um aliado.[n][e]

[msg Item_1F9]
[s]Donuts feitos por Makoto.[n]Restaura 100 SP de[n]um aliado.[n][e]

[msg Item_1FA]
[s]Bolo em forma de flor de cerejeira.[n]Restaura[n]100 SP de um aliado.[n][e]

[msg Item_1FB]
[s][n]Taiyaki especial de Kawakami. Restaura 100[n]SP de um aliado.[n][e]

[msg Item_1FC]
[s]Um cachorro-quente gyoza feito por Ryuji. Restaura 100 SP[n]de um aliado.[n][e]

[msg Item_1FD]
[s]não usado[n][e]

[msg Item_1FE]
[s]não usado[n][e]

[msg Item_1FF]
[s]Um laptop quebrado. Parece que[n]pode ser reparado.[n][e]

[msg Item_200]
[s]Aumenta a eficácia de[n]treinos. Restaura[n]30% do HP de um aliado.[n][e]

[msg Item_201]
[s]não usado[n][e]

[msg Item_202]
[s]não usado[n][e]

[msg Item_203]
[s]não usado[n][e]

[msg Item_204]
[s]Um guia de viagem que[n]lista as atrações de[n]todos os aquários de Tóquio.[n][e]

[msg Item_205]
[s]Guia de viagem listando[n]os lugares mais populares[n]e menos conhecidos.[n][e]

[msg Item_206]
[s]Incenso que aumenta[n]a força física. Aumente o Fr[n]de uma pessoa em 1.[n][e]

[msg Item_207]
[s]Incenso que instila[n]força mental. Aumente o Ma[n]de uma Persona em 1.[n][e]

[msg Item_208]
[s]Incenso que dispensa[n]paciência. Aumente o Rs[n]de uma pessoa em 1.[n][e]

[msg Item_209]
[s]Incenso que ilumina[n]o ritmo. Aumente Ag de uma[n]Pessoa em 1.[n][e]

[msg Item_20A]
[s]Incenso que aumenta a[n]sorte. Aumenta o Fo[n]de uma Persona em 1.[n][e]

[msg Item_20B]
[s]Incenso de qualidade que[n]melhora o físico. Aumente o[n]Fr de uma pessoa em 2.[n][e]

[msg Item_20C]
[s]Incenso de qualidade que estimula a mente. Aumente[n]Ma de uma Persona em 2.[n][e]

[msg Item_20D]
[s]Incenso de qualidade que dá[n]paciência. Aumente Rs[n]de uma Persona em 2.[n][e]

[msg Item_20E]
[s]Incenso que ilumina[n]o passo. Aumente Ag de uma[n]Pessoa em 2.[n][e]

[msg Item_20F]
[s]Incenso de qualidade que dispensa[n]boa sorte. Aumente a Força de[n]a Persona em 2.[n][e]

[msg Item_210]
[s]Incenso místico que[n]aumenta o físico. Aumente o[n]Fr de uma pessoa em 3.[n][e]

[msg Item_211]
[s]Incenso místico que instila[n]força mental. Aumente o Ma[n]de uma pessoa em 3.[n][e]

[msg Item_212]
[s]Incenso místico que dispensa[n]paciência. Aumenta os Rs de uma[n]pessoa em 3.[n][e]

[msg Item_213]
[s]Incenso místico que faz[n]sentir luz. Aumenta o[n]Ag de uma Persona em 3.[n][e]

[msg Item_214]
[s]Incenso místico que dispensa[n]boa sorte. Aumenta a Força de[n]a Persona em 3.[n][e]

[msg Item_215]
[s]Menchi-katsu pelo qual as pessoas enlouquecem. Restaura[n]30 SP para um aliado.[n][e]

[msg Item_216]
[s]Suplemento muscular.[n]Aumenta o ataque de um[n]aliado por três turnos.[n][e]

[msg Item_217]
[s]Suplemento muscular.[n]Aumenta a defesa de um[n]aliado por três turnos.[n][e]

[msg Item_218]
[s]Suplemento Muscular.[n]Aumenta a Precisão/Evasão[n]de um aliado por 3 turnos.[n][e]

[msg Item_219]
[s]não usado[n][e]

[msg Item_21A]
[s]Requintado sakura mochi de[n]um confeiteiro famoso.[n]Retorna 10 SP para um aliado.[n][e]

[msg Item_21B]
[s]não usado[n][e]

[msg Item_21C]
[s]Um cartão postal colorido e[n]elegante.[n]Para os amantes da arte.[n][e]

[msg Item_21D]
[s]Um porta-canetas sofisticado[n]em couro fino.[n]Para cavalheiros.[n][e]

[msg Item_21E]
[s]Vários tipos de ramen de[n]todo o Japão.[n]Para os amantes de macarrão.[n][e]

[msg Item_21F]
[s]Vitaminas ideais para todos os[n]aspectos da saúde.[n]Para os mais enérgicos.[n][e]

[msg Item_220]
[s]Pulseira com um estilo[n]simples e chique. Também adequado[n]para homens.[n][e]

[msg Item_221]
[s]Equipamento de musculação[n]para pernas e braços. Para[n]aqueles que adoram treinar.[n][e]

[msg Item_222]
[s]Óculos de sol esportivos[n]que reduzem os raios UV em[n]10%. Para quem ama correr.[n][e]

[msg Item_223]
[s]Um conjunto de 28 utensílios para[n]cozinhar qualquer coisa.[n]Para cozinheiros experientes.[n][e]

[msg Item_224]
[s]Quebra-cabeça 3D muito difícil.[n]Para desligar[n]aqueles que trabalham na mesa.[n][e]

[msg Item_225]
[s]não usado[n][e]

[msg Item_226]
[s]não utilizado[n][e]

[msg Item_227]
[s]não utilizado[n][e]

[msg Item_228]
[s]não utilizado[n][e]

[msg Item_229]
[s]não utilizado[n][e]

[msg Item_22A]
[s]não utilizado[n][e]

[msg Item_22B]
[s]não utilizado[n][e]

[msg Item_22C]
[s]não utilizado[n][e]

[msg Item_22D]
[s]não utilizado[n][e]

[msg Item_22E]
[s]Pequeno frasco de líquido.[n]Alta chance de infligir[n]tontura em um inimigo.[n][e]

[msg Item_22F]
[s]Frasco grande de líquido.[n]Chance média de infligir[n]tontura em todos os inimigos.[n][e]

[msg Item_230]
[s]Pequeno frasco de líquido.[n]Alta chance de infligir[n]Confusão em um inimigo.[n][e]

[msg Item_231]
[s]Frasco grande de líquido.[n]Chance média de infligir[n]Confusão. a todos os inimigos.[n][e]

[msg Item_232]
[s]Pequeno frasco de líquido.[n]Alta chance de infligir[n]Medo a um inimigo.[n][e]

[msg Item_233]
[s]Frasco grande de líquido.[n]Chance média de infligir[n]Medo a todos os inimigos.[n][e]

[msg Item_234]
[s]Pequeno frasco de líquido.[n]Alta chance de infligir[n]amnésia a um inimigo.[n][e]

[msg Item_235]
[s]Frasco grande de líquido.[n]Chance média de infligir[n]amnésia a todos os inimigos.[n][e]

[msg Item_236]
[s]Pequeno frasco de líquido.[n]Alta chance de infligir[n]Sleep em um inimigo.[n][e]

[msg Item_237]
[s]Frasco grande de líquido.[n]Chance média de infligir[n]Sleep em todos os inimigos.[n][e]

[msg Item_238]
[s]Pequeno frasco de líquido.[n]Alta chance de infligir[n]Fúria em um inimigo.[n][e]

[msg Item_239]
[s]Frasco grande de líquido.[n]Chance média de infligir[n]Fúria a todos os inimigos.[n][e]

[msg Item_23A]
[s]Pequeno frasco de líquido.[n]Alta chance de infligir[n]Desespero em um inimigo.[n][e]

[msg Item_23B]
[s]Grande frasco de líquido.[n]Média chance de infligir[n]Desespero. a todos os inimigos.[n][e]

[msg Item_23C]
[s]Pequeno frasco de líquido.[n]Alta chance de infligir[n]Subjugar. a um inimigo.[n][e]

[msg Item_23D]
[s]Grande frasco de líquido.[n]Chance média de infligir[n]Subjugar. a todos os inimigos.[n][e]

[msg Item_23E]
[s]Incenso de qualidade que[n]aumenta Fr e Ma em[n]uma pessoa em 1.[n][e]

[msg Item_23F]
[s]Incenso de qualidade que[n]aumenta Fr e Rs de[n]uma Pessoa em 1.[n][e]

[msg Item_240]
[s]Incenso de qualidade que[n]aumenta Fr e Ag de[n]uma Pessoa em 1.[n][e]

[msg Item_241]
[s]Incenso de qualidade que[n]aumenta Fr e Fo de[n]uma pessoa em 1.[n][e]

[msg Item_242]
[s]Incenso de qualidade que[n]aumenta Ma e Rs de[n]uma pessoa em 1.[n][e]

[msg Item_243]
[s]Incenso de qualidade que[n]aumenta Ma e Ag de[n]uma pessoa em 1.[n][e]

[msg Item_244]
[s]Incenso de qualidade que[n]aumenta Ma e Fo de[n]uma pessoa em 1.[n][e]

[msg Item_245]
[s]Incenso de qualidade que[n]aumenta Rs e Ag de[n]uma pessoa em 1.[n][e]

[msg Item_246]
[s]Incenso de qualidade que aumenta os[n]Rs e Fo de uma pessoa em 1.[n][e]

[msg Item_247]
[s]Incenso de alta qualidade que[n]aumenta Fr, Ma e Ag em a[n]Pessoa em 1.[n][e]

[msg Item_248]
[s]Jogo Featherman que[n]tem muitos fãs.[n]Pode dar conhecimento.[n][e]

[msg Item_249]
[s]Obtido de Featherman[n]Seeker. Um entusiasta[n]sabe apreciar seu valor.[n][e]

[msg Item_24A]
[s]Um dia[n]bilhete grátis para[n]as gaiolas de rebatidas.[n][e]

[msg Item_24B]
[s]Reforço muscular que[n]aumenta ATK/Def/Prev/[n]Elude de um aliado.[n][e]

[msg Item_24C]
[s]Senhor dos Guardiões.[n]Ele raramente é visto.[n][e]

[msg Item_24D]
[s]Miniatura Black Frost.[n]Você está com disposição para[n]causar problemas?[n][e]

[msg Item_24E]
[s]Estatueta de Buchimaru.[n]Amada por muitas[n]gerações.[n][e]

[msg Item_24F]
[s]O mascote da Jagariko,[n]uma famosa marca de salgadinhos.[n][e]

[msg Item_250]
[s]Isca de origem desconhecida. É[n]usado apenas para fazer[n]um tipo especial de mordida de peixe.[n][e]

[msg Item_251]
[s]Vara de pesca feita[n]com tecnologia espacial.[n]Qualidade de outro mundo.[n][e]

[msg Item_252]
[s]Boneca de um[n]caracol marinho com olhos brilhantes.[n]Um presente de [f 4 31 10 1].[n][e]

[msg Item_253]
[s]Estatueta de um Phoenix Ranger[n]apreciado pelos conhecedores mais exigentes.[n]Um presente de Ryuji.[n][e]

[msg Item_254]
[s]Chocolate feito à mão por[n]Sumire. Redefina todos os SPs de um aliado.[n][e]

[msg Item_255]
[s]Chocolate de cortesia de[n]Ann. Restaura[n]100 SP de um aliado.[n][e]

[msg Item_256]
[s]Chocolate de cortesia de[n]de Makoto. Restaura[n]100 SP de um aliado.[n][e]

[msg Item_257]
[s]Chocolate de cortesia de[n]Haru. Restaura[n]100 SP de um aliado.[n][e]

[msg Item_258]
[s]Chocolate de cortesia da[n]Futaba. Restaura[n]100 SP de um aliado.[n][e]

[msg Item_259]
[s]Chocolate de cortesia de[n]takemi. Restaura[n]100 SP de um aliado.[n][e]

[msg Item_25A]
[s]Chocolate de cortesia da parte de[n]chihaya. Devolva[n]100 SP a um aliado.[n][e]

[msg Item_25B]
[s]Chocolate de cortesia de[n]de Kawakami. Devolva[n]100 SP a um aliado.[n][e]

[msg Item_25C]
[s]Chocolate de cortesia de[n]Ohya. Restaura[n]100 SP de um aliado.[n][e]

[msg Item_25D]
[s]Chocolate de cortesia de[n]by Hifumi. Restaura[n]100 SP de um aliado.[n][e]

[msg Item_25E]
[s]Chocolate de cortesia de[n]por Sumire. Restaura[n]100 SP de um aliado.[n][e]

[msg Item_25F]
[s]Chocolate de cortesia de[n]by Sae. Restaura[n]100 SP de um aliado.[n][e]

[msg Item_260]
[s]Escolhido Sweet com Makoto.[n]Restaure totalmente o SP de um aliado.[n][e]

[msg Item_261]
[s]Escolhido Sweet com Haru.[n]Restaure totalmente o SP de um aliado.[n][e]

[msg Item_262]
[s]Sweet escolhido com Ann.[n]Restaura totalmente o SP de um aliado.[n][e]

[msg Item_263]
[s]Escolha Sweet com Futaba.[n]Restaure totalmente o SP de um aliado.[n][e]

[msg Item_264]
[s]Sweet escolhido com Chihaya.[n]Restaura totalmente o SP de um aliado.[n][e]

[msg Item_265]
[s]Sweet escolhido com Takemi.[n]Restaura totalmente o SP de um aliado.[n][e]

[msg Item_266]
[s]Sweet escolhido com Kawakami.[n]Restaura totalmente[n]o SP de um aliado.[n][e]

[msg Item_267]
[s]Escolhido Sweet com Ohya.[n]Restaure totalmente o SP de um aliado.[n][e]

[msg Item_268]
[s]Sweet escolhido com Hifumi.[n]Restaure totalmente o SP de um aliado.[n][e]

[msg Item_269]
[s]Escolhido Sweet com [f 4 31 10 1].[n]Restaura totalmente[n]o SP de um aliado.[n][e]

[msg Item_26A]
[s]Esta flor significa[n]"Eu te amo".[n]Quem gostaria de recebê-la?[n][e]

[msg Item_26B]
[s]Esta flor significa[n]"amor absoluto".[n]Quem gostaria de recebê-la?[n][e]

[msg Item_26C]
[s]Esta flor significa[n]"amor imutável".[n]Quem gostaria de recebê-la?[n][e]

[msg Item_26D]
[s]Use apenas em locais seguros.[n]Restaura 20% SP[n]de todos os aliados.[n][e]

[msg Item_26E]
[s]Use apenas em locais seguros.[n]Restaura 40% SP[n]de todos os aliados.[n][e]

[msg Item_26F]
[s]Dardos com equilíbrio invejável. Preferido[n]por profissionais.[n][e]

[msg Item_270]
[s]Sugestão especial para salto[n]arremessos. Para quem quer dominar o bilhar.[n][e]

[msg Item_271]
[s]Digno de um Hierofante.[n]Revive todos[n]aliados caídos com HP total.[n][e]

[msg Item_272]
[s]Daifuku de morango. Cure[n]todos os acidentes. e restaure[n]todos os HP dos aliados.[n][e]

[msg Item_273]
[s]Técnicas explicadas por um[n]profissional[n]jogador de dardos.[n][e]

[msg Item_274]
[s]Técnicas explicadas por um jogador[n]profissional[n]de sinuca.[n][e]

[msg Item_275]
[s]Contos femininos de amor[n]e paixão. Uma história de vida fascinante.[n][e]

[msg Item_276]
[s]O heroísmo médico de um[n]roedor independente.[n]Descubra a verdadeira bondade.[n][e]

[msg Item_277]
[s]Escritor e editor[n]lutando com[n]prazos iminentes. Alta voltagem.[n][e]

[msg Item_278]
[s]Um professor e um[n]time de golfe do ensino médio em crise.[n]O poder das convicções.[n][e]

[msg Item_279]
[s]Cartão de sócio de um maid[n]café. Ganhe um selo[n]por cada visita.[n][e]

[msg Item_27A]
[s]Uma foto autografada de Clara.[n]O autógrafo cobre a maior[n]parte de seu rosto.[n][e]

[msg Item_27B]
[s]Queijo saboroso.[n]Restaura 20 HP de[n]um aliado.[n][e]

[msg Item_27C]
[s]Queijo Saboroso.[n]Restaura 50 HP de[n]um aliado.[n][e]

[msg Item_27D]
[s]Queijo muito saboroso.[n]Restaura 100 HP de[n]um aliado.[n][e]

[msg Item_27E]
[s]Um saco de[n]grosso molho de abóbora. Restaura 100 HP[n]de um aliado.[n][e]

[msg Item_27F]
[s]RESERVA[n][e]

[msg Item_280]
[s]Um par de anéis que[n]deixa muita perplexidade. Para[n]aqueles que amam desafios.[n][e]

[msg Item_281]
[s]Uma almofada feita de material[n]pegajoso ao toque.[n]Para pessoas ocupadas.[n][e]

[msg Item_282]
[s]370.000 rotações/segundo[n]que destroem a placa.[n]Para quem está ocupado com o trabalho.[n][e]

[msg Item_283]
[s]Despertador ensurdecedor para maquiar qualquer preguiçoso.[n]Para quem está ocupado com o trabalho.[n][e]

[msg Item_284]
[s]Mini difusor que perfuma[n]e refresca o ar. Para aqueles que[n]trabalham em uma mesa.[n][e]

[msg Item_285]
[s]Chaveiro Katana com[n]design de dragão.[n]Para os jovens de coração.[n][e]

[msg Item_286]
[s]Um manual muito desgastado.[n]Melhora a eficácia do[n]estudo.[n][e]

[msg Item_287]
[s]Integrador que aperfeiçoa o objetivo. Aumenta a[n]chance crítica de um aliado.[n][e]

[msg Item_288]
[s]Geleia europeia para[n]comer na estrada. Restaure[n]100 HP para um aliado.[n][e]

[msg Item_289]
[s]Antibacteriano. Reduz[n]ataque de todos[n]inimigos por 3 turnos.[n][e]

[msg Item_28A]
[s]Poderoso desinfetante.[n]Reduz a defesa de todos[n]inimigos por 3 turnos.[n][e]

[msg Item_28B]
[s]Desinfetante. Reduzir fino e iludiu de todos os[n]inimigos por 3 turnos.[n][e]

[msg Item_28C]
[s]Antibacteriano. Reduz as[n]estatísticas de um inimigo por[n]3 turnos.[n][e]

[msg Item_28D]
[s]Desodorante sanitizante.[n]Cura todos os alt. negat.[n]não especial de um aliado.[n][e]

[msg Item_28E]
[s]Desodorante revigorante.[n]Cura todos os alt. negat.[n]aliados não especiais.[n][e]

[msg Item_28F]
[s]não utilizado[n][e]

[msg Item_290]
[s]não utilizado[n][e]

[msg Item_291]
[s]RESERVA[n][e]

[msg Item_292]
[s]A vida fascinante de[n]uma garota lidando com[n]situações desagradáveis.[n][e]

[msg Item_293]
[s]RESERVA[n][e]

[msg Item_294]
[s]Maçã brilhante e deliciosa.[n]Restaura todos os HP[n]dos aliados.[n][e]

[msg Item_295]
[s]Medicina de emergência.[n]Reviva um aliado caído[n]com 50% de HP.[n][e]

[msg Item_296]
[s]Manto sagrado. Chance média[n]de que uma habilidade sagrada[n]mata todos os inimigos.[n][e]

[msg Item_297]
[s]Tabuleiro do adivinho. Chance média[n]de que um amaldiçoado[n]mata todos os inimigos.[n][e]

[msg Item_298]
[s]Aumenta ATK/Def/Anterior/[n]Evasão de um[n]aliado por 3 turnos.[n][e]

[msg Item_299]
[s]Reduz o ATK/Def/[n]Precisão/Evasão[n]de um inimigo por 3 turnos.[n][e]

[msg Item_29A]
[s]Causa 50 de dano de Fogo[n]a um inimigo. Alta chance de[n]infligir Queimaduras.[n][e]

[msg Item_29B]
[s]Causa 50 de dano de Vento[n]a um inimigo.[n][e]

[msg Item_29C]
[s]Causa 50 de dano elétrico[n]a um inimigo. Alta chance de[n]infligir Choque.[n][e]

[msg Item_29D]
[s]Causa 50 de dano de gelo[n]a um inimigo. Alta chance de[n]infligir Congelamento.[n][e]

[msg Item_29E]
[s]Causa 50 de dano nuclear[n]a um inimigo.[n][e]

[msg Item_29F]
[s]Causa 50[n]dano psicocinético a um inimigo.[n][e]

[msg Item_2A0]
[s]Causa 50 de dano Sagrado[n]a um inimigo.[n][e]

[msg Item_2A1]
[s]Causa 50 de dano amaldiçoado a um inimigo.[n][e]

[msg Item_2A2]
[s]Um escudo protege todos[n]aliados de uma[n]morte instantânea do inimigo.[n][e]

[msg Item_2A3]
[s]Um pingente que aumenta[n]força. Dobra os ataques físicos[n]uma vez.[n][e]

[msg Item_2A4]
[s]Um pendente que melhora a[n]concentração. Duplo[n]uma vez atk. mágico.[n][e]

[msg Item_2A5]
[s]Para artesãos experientes. Le[n]abil. para criar ferramentas[n]infiltração melhorar.[n][e]

[msg Item_2A6]
[s]Para aspirantes a artesãos. Le[n]abil. para criar ferramentas[n]infiltração melhorar.[n][e]

[msg Item_2A7]
[s]Recheado com carne suculenta.[n]Restaura 30 HP de[n]um aliado.[n][e]

[msg Item_2A8]
[s]Nikuman avermelhado. É[n]melhor do que parece.[n]Restaura 50 HP de um aliado.[n][e]

[msg Item_2A9]
[s]Sanduíche com carne que esquenta por dentro. Restaura[n]100 HP de um aliado.[n][e]

[msg Item_2AA]
[s]Latas variadas de[n]carne enlatada. Restaura 40[n]HP de todos os aliados.[n][e]

[msg Item_2AB]
[s]Multipack de[n]cereais variados. Restaura[n]80 HP para todos os aliados.[n][e]

[msg Item_2AC]
[s]Recipiente grande de pipoca caramelada.[n]Restaura 100[n]HP para todos os aliados.[n][e]

[msg Item_2AD]
[s]Contém quatro[n]roupas usadas. Espero que você[n]goste de surpresas.[n][e]

[msg Item_2AE]
[s]Isso o satisfaz completamente. Retorna[n]30% de SP para um total.[n]Reduz todas as estatísticas.[n][e]

[msg Item_2AF]
[s]Um verdadeiro deleite.[n]Restaura 50 HP e cura[n]Fome de um aliado.[n][e]

[msg Item_2B0]
[s]Restaura 30% de HP para um[n]aliado. Potencializar Evasão e[n]preciso e reduz o ataque.[n][e]

[msg Item_2B1]
[s]Um bolinho de arroz chinês[n]que traz alegria. Restaura[n]100 SP de um aliado.[n][e]

[msg Item_2B2]
[s]Cacau osechi para comer[n]com os amigos. Restaura o HP de[n]todos os aliados.[n][e]

[msg Item_2B3]
[s]Um livro sobre a[n]fragilidade humana. Expande as condições[n]para um ataque técnico.[n][e]

[msg Item_2B4]
[s]Ele quebra todos os limites conhecidos.[n]Velocidade da[n]bola: ??? km/h.[n][e]

[msg Item_2B5]
[s]Ingredientes ultrassecretos![n]Restaura todos os HP e[n]SP de todos os aliados.[n][e]

[msg Item_2B6]
[s]Técnicas milagrosas de um[n]mestre do bilhar.[n]Aprenda tacada em massa.[n][e]

[msg Item_2B7]
[s]Incenso de qualidade que aumenta o[n]Ag e Fo de uma pessoa em 1.[n][e]

