[msg MSG_059_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 74 65535 0]Um edifício ligado aos artistas. Se[n]partimos dessa suposição,[n]o que poderia ser?[n][f 1 3 65535][w][e]

[sel SEL_060_0_0 top]
[s]Uma escola de arte.[e]
[s]Uma loja de arte.[e]
[s]Um museu.[e]

[msg MSG_061_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 75 65535 0]...Sem reação.[n]Mais alguma coisa?[n][f 1 3 65535][w][e]

[msg MSG_062_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 76 65535 0]...Isso também não é bom.[n]Mais alguma coisa?[n][f 1 3 65535][w][e]

