[msg DUMMY_MSG]
[s]…[n][w][e]

[sel RARE_TBOX_YES_NO top]
[s]Abra o peito [e]
[s]Ignore por agora [e]

[msg RARE_TBOX_MSG_M [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 1167 65535 0]Huh, está trancado...[n][w][e]

[msg RARE_TBOX_MSG_NO_KEY_M [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]É uma pena que não temos um [f 2 5 3 9999 0]agora mesmo.[n]Vamos fazer alguns mais tarde.[n][w][e]

[msg RARE_TBOX_MSG_KEY_CONF_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Precisa de um [f 2 5 3 9999 0]...[n]Nós temos [var 1]daqueles. Quer abri-lo?[n][w][e]

[msg RARE_TBOX_MSG_F [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][vp 8 2 0 9114 65535 0]Eh? Este baú do tesouro tem uma fechadura[n]agradável e pesada.[n][w][e]

[msg RARE_TBOX_MSG_NO_KEY_F [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0]Mas o seu [f 2 5 3 9999 0]A contagem cai para zero. Talvez da próxima[n]vez lembre-se de trazer alguns.[n][w][e]

[msg RARE_TBOX_MSG_CONF_F [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0]Parece que você realmente tem um [n][f 2 5 3 9999 0]![var 1], para ser exato.[n]Vamos abrir este bebê![n][w][e]

[msg RARE_TBOX_MSG_NO_KEY_1ST [Morgana]]
[s][bup 0 3 11 0 0][f 4 10 65535 0 0]Para abrir esses baús de tesouro, você[n]precisa de uma ferramenta especial chamada[n]de  [f 2 5 3 9999 0].[n][w][e]

[msg RARE_TBOX_MSG_NO_KEY_1ST_2 [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0]Um ladrão que não pode fazer um [f 2 5 3 9999 0][n]sozinhos? Isso é surpreendente.[n][w][e]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0]Faça com que Morgana ensine como quando você[n]chega em casa.[n][w][e]

[msg RARE_TBOX_MSG_NO_KEY_2ND [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Eu já mencionei isso antes, mas não me[n]importaria de ensinar a você como fazer um [n][f 2 5 3 9999 0]às vezes.[n][w][e]
[s]Bem, acho que isso pode esperar até[n]chegarmos em casa.[n][w][e]

[msg RARE_TBOX_MSG_NO_KEY_2ND_2 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0]Espere, você ainda não sabe como fazer um [f 2 5 3 9999 0]?[n][w][e]
[s]Faça com que Morgana ensine como quando você[n]chega em casa.[n][w][e]

[msg RARE_TBOX_MSG_NO_KEY_ADD [Morgana]]
[s][vp 8 2 0 1169 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]... Embora eu ache que sua mesa[n]provavelmente está muito confusa para isso[n]agora.[n][w][e]

[msg RARE_TBOX_MSG_NO_KEY_ADD_2 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][vp 8 2 0 9197 65535 0]... Embora essa mesa no seu quarto possa[n]estar muito confusa para você fazer[n]qualquer coisa agora...[n][w][e]

[msg TBOX_MSG_DIRTYMAIL1ST_M [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1029 65535 0]Ei... essas coisas são nojentas.[n]Você deve limpar em algum lugar...[n][w][e]
[s]Venha para pensar sobre isso, lembro-me de ver uma[n]sombra com uma... talvez se negociarmos corretamente,[n]podemos conseguir um.[n][w][e]

[msg TBOX_MSG_DIRTYMAIL1ST_M2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Espere, não havia uma roupa de moeda perto[n]de LeBlanc?[n][w][e]

[msg TBOX_MSG_DIRTYMAIL1ST_F [Futaba]]
[s][bup 0 8 105 0 0][f 4 10 65535 0 0][vp 8 2 0 9029 65535 0]Ughhh... esse equipamento é nojento. Você[n]deve lavá-lo em algum lugar![n][w][e]
[s]IIRC, há uma roupa de moeda perto de LeBlanc.[n][w][e]

[msg TBOX_MSG_SKILL_ACCESSORY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Este acessório parece ter algum poder[n]especial... aposto que será útil de alguma[n]forma![n][w][e]

[msg TBOX_MSG_SKILL_ACCESSORY_2 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0]Eu posso sentir algum tipo de poder especial[n]disso... Pode ser aconselhável segurá-lo.[n][w][e]

[msg RARE_TBOX_MSG_NO_KEY_SER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Bem, acho que esta é a sua primeira vez.[n]Aqui, você pode ter este. É minha posse[n]valiosa.[n][w][e]
[s]Mas da próxima vez você será responsável por[n]isso, tudo bem?[n][w][e]

[sel RARE_TBOX_NO_KEY_SERVICE top]
[s]O que você quer dizer?[e]
[s]Eu quero mais![e]

[msg RARE_TBOX_MSG_NO_KEY_SER_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Você vai fazer o seu próprio. Eu posso te[n]ensinar como voltar ao seu quarto.[n][w][e]

[msg RARE_TBOX_MSG_NO_KEY_SER_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Talvez, mas um ladrão como você deveria ser[n]capaz de fazer suas próprias ferramentas.[n]Eu posso te ensinar como no seu quarto.[n][w][e]

[msg RARE_TBOX_MSG_AQKEYPICK_ [Morgana]]
[s][bup 0 3 8 0 0][f 4 10 65535 0 0][vp 8 2 0 1171 65535 0]Você tem a [f 2 5 3 9999 0]Com você, certo? Vamos aceitar isso![n][w][e]

[msg RARE_TBOX_MSG_AQKEYPICK__2 [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][vp 8 2 0 9040 65535 0]Essa é a lendária ferramenta de infiltração,[n]o  [f 2 5 3 9999 0]![n][w][e]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0]Quero usá-lo para abrir isso!?[n][w][e]

[msg WEAPON_RYUJI_MSG [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 2 1 7020 65535 0]Ooh, isso parece mais forte do que eu[n]consegui agora! Deixe-me usar já![n][w][e]

[msg WEAPON_ANNE_MSG [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][vp 8 2 1 6159 65535 0]Isso parece mais promissor do que o que[n]estou usando agora... ei, posso tentar?[n][w][e]

[msg WEAPON_MORGANA_MSG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Oh, essa beleza parece que é apenas o meu[n]tamanho! Isso é meu agora, tudo bem?[n][w][e]

[msg WEAPON_YUSUKE_MSG [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][vp 8 2 1 4135 65535 0]Temos nossas mãos na arma...[n]Eu adoraria ter uma idéia disso...[n][w][e]

[msg WEAPON_MAKOTO_MSG [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][vp 8 2 1 2159 65535 0]Ah, parece que tem um desempenho melhor do[n]que o que eu tenho agora- seria tudo bem se[n]eu tentei usá-lo?[n][w][e]

[msg WEAPON_HARU_MSG [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][vp 8 2 1 3159 65535 0]Ooooh, um novo machado? Eu gostaria de[n]experimentar imediatamente![n][w][e]

[msg WEAPON_AKECHI_MSG [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][vp 8 2 1 8133 65535 0]Ah, essa arma parece vantajosa...[n]Você se importaria se eu usasse?[n][w][e]

[msg WEAPON_KUROAKECHI_MSG [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][vp 8 2 1 8133 65535 0]Isso parece ser uma arma superior para a[n]minha atual- eu vou usá-la sozinho, bem?[n][w][e]

[msg WEAPON_KASUMI_MSG [[f 4 31 10 0]]]
[s][bup 0 10 101 0 0][f 4 10 65535 0 0][vp 8 2 1 57142 65535 0]Isso parece mais poderoso do que o que estou[n]usando atualmente... você se importaria se[n]eu tentasse?[n][w][e]

[sel WEAPON_EQUIP_YES_NO top]
[s]Vá em frente.[e]
[s]Não agora.[e]

[msg WEAPON_RYUJI_MSG_YES [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 2 1 7103 65535 0]Alriiiight! Hora de gritar uma bunda![n][w][e]

[msg WEAPON_RYUJI_MSG_NO [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 2 1 7106 65535 0]TCH! Fiiiine...[n][w][e]

[msg WEAPON_ANNE_MSG_YES [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][vp 8 2 1 6108 65535 0]Obrigado! Ok, vamos ver...[n]Sim, parecendo bem![n][w][e]

[msg WEAPON_ANNE_MSG_NO [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][vp 8 2 1 6135 65535 0]Claro, sem problemas.[n][w][e]

[msg WEAPON_MORGANA_MSG_YES [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]*risada* Agora sou ainda mais uma ameaça![n][w][e]

[msg WEAPON_MORGANA_MSG_NO [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Oh, ok... bem, eu já sou uma força a ser[n]reconhecida![n][w][e]

[msg WEAPON_YUSUKE_MSG_YES [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][vp 8 2 1 4045 65535 0]... HM, isso me encaixa perfeitamente![n]Que excelente achado.[n][w][e]

[msg WEAPON_YUSUKE_MSG_NO [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][vp 8 2 1 4026 65535 0]Infelizmente... talvez mais tarde.[n][w][e]

[msg WEAPON_MAKOTO_MSG_YES [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][vp 8 2 1 2090 65535 0]Obrigado... Ah, isso é ótimo.[n][w][e]

[msg WEAPON_MAKOTO_MSG_NO [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][vp 8 2 1 2090 65535 0]Entendido.[n][w][e]

[msg WEAPON_HARU_MSG_YES [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][vp 8 2 1 3020 65535 0]Yay! Vou trabalhar mais do que nunca![n][w][e]

[msg WEAPON_HARU_MSG_NO [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][vp 8 2 1 3047 65535 0]Oh, tudo bem...[n][w][e]

[msg WEAPON_AKECHI_MSG_YES [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][vp 8 2 1 8059 65535 0]Obrigado. Eu prometo que vou contribuir[n]ainda mais agora.[n][w][e]

[msg WEAPON_KUROAKECHI_MSG_YE [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][vp 8 2 1 8059 65535 0]Ah, não muito surrado.[n][w][e]

[msg WEAPON_AKECHI_MSG_NO [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][vp 8 2 1 8021 65535 0]Tudo bem, você é o chefe aqui.[n][w][e]

[msg WEAPON_KUROAKECHI_MSG_NO [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][vp 8 2 1 8021 65535 0]Ugh, se você diz isso... Vamos torcer para[n]que você não esteja estragando tudo.[n][w][e]

[msg WEAPON_KASUMI_MSG_YES [[f 4 31 10 0]]]
[s][bup 0 10 101 0 0][f 4 10 65535 0 0][vp 8 2 1 57039 65535 0]Muito obrigado! Isso certamente será útil![n][w][e]

[msg WEAPON_KASUMI_MSG_NO [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 2 1 57055 65535 0]Tudo bem, entendido.[n][w][e]

[msg HERO_WEAPON_RYUJI_MSG [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 2 1 7020 65535 0]Oh! Essa coisa parece muito boa, Joker.[n]Por que não experimenta?[n][w][e]

[msg HERO_WEAPON_ANNE_MSG [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][vp 8 2 1 6159 65535 0]Ei, Joker! Por que você não troca o seu[n]atual com isso?[n][w][e]

[msg HERO_WEAPON_MORGANA_MSG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Que pontuação, Joker! Por que não tentar[n]agora?[n][w][e]

[msg HERO_WEAPON_YUSUKE_MSG [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][vp 8 2 1 4135 65535 0]Parece que vai se adequar bem a você, Joker-[n]por que não experimentar?[n][w][e]

[msg HERO_WEAPON_MAKOTO_MSG [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][vp 8 2 1 2159 65535 0]Parece algo que você pode lidar, Joker-[n]parece superior ao seu atual. Por que não[n]trocá-los?[n][w][e]

[msg HERO_WEAPON_FUTABA_MSG [Futaba]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][vp 8 2 1 9048 65535 0]Nova arma alerrrrrt! Joker, você quer[n]equipá-lo!?[n][w][e]

[msg HERO_WEAPON_HARU_MSG [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][vp 8 2 1 3159 65535 0]Uau, isso é uma arma muito louca![n]Eu acho que será perfeito para você.[n][w][e]

[msg HERO_WEAPON_AKECHI_MSG [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][vp 8 2 1 8133 65535 0]Ah, essa é uma arma de aparência poderosa.[n]Experimente, Joker.[n][w][e]

[msg HERO_WEAPON_KUROAKECHI_M [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][vp 8 2 1 8133 65535 0]Talvez isso seja mais útil que o seu[n]equipamento atual? Troque-os, Joker.[n][w][e]

[sel HERO_WEAPON_EQUIP_YES_NO top]
[s]Hora de mudar isso.[e]
[s]Não agora.[e]

