[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2198 65535 0]Eiko Takao-san. Ultimamente[n]você esteve no[n]distrito da Luz Vermelha, não foi?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nós vimos você, eu e[n][f 4 2]-kun.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se não estamos enganados, você trabalha[n]em um lugar chamado[n]After School Salon.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Como é trabalhar lá?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Eiko]]
[s][vp 8 0 0 0 65535 0]O que você quer dizer? É um[n]café normal. Eu tenho que usar uma fantasia,[n]mas fora isso é como os outros.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]E não preciso fazer nada estranho,[n]se é que você me entende.[n]É tudo perfeitamente legal.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2100 65535 0]Hmmm. Então você tem certeza que[n]nada de estranho acontece lá?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Eiko]]
[s][vp 8 0 0 0 65535 0]Mas sim. O pior que pode acontecer comigo[n]é algum velho me lançando[n]olhares.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2021 65535 0]Entendo. Mas, deixando esse[n]aspecto de lado, por que você trabalha lá?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Qual é a sua[n]situação financeira?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Eiko]]
[s][vp 8 0 0 0 65535 0]Huh? Eu não tenho nenhum problema.[n]Posso pedir dinheiro aos meus pais[n]quando eu quiser.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O-oh, entendo...[n][f 1 3 65535][w][e]

[msg MSG_006_5_0 [Eiko]]
[s][vp 8 0 0 0 65535 0]Nesse caso, no entanto, eles[n]me enganariam em todas as compras. É[n]por isso que trabalho lá.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eles me pagam bem e,[n]além disso, os clientes me mimam[n]muito bem.[n][f 1 3 65535][w][e]

[msg MSG_006_6_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 2128 65535 0]Eles mimam você... muito?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Eiko]]
[s][vp 8 0 0 0 65535 0]É bom quando alguém trata você[n]como alguém especial, não é?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Mas certamente uma superaluna[n]modelo como você sabe disso muito bem.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]De qualquer forma, você quer me delatar?[n]Você até trouxe[n]uma testemunha...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Espere um momento. Então vocês[n]dois estavam juntos em Shinjuku![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]E por que, senhorita presidente?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s][f 0 8 2 1 2217]Você está tendo uma ideia errada.[clr 27][e]
[s]E se estivéssemos juntos?[e]
[s]Não é da sua conta.[e]

[msg MSG_009_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2023 65535 0][f 5 13 3 5 6]Está certo. Eu tinha uma tarefa[n]para fazer e pedi a ele[n]para me acompanhar, só isso.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2046 65535 0]E-ei! Não diga coisas que possam[n]ser mal interpretadas![n][f 1 3 65535][w][e]

[msg MSG_010_5_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu simplesmente tinha uma tarefa a cumprir e pedi[n]a ele que me acompanhasse. Isso é tudo.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2022 65535 0]Ele não está totalmente errado...[n][f 1 3 65535][w][e]

[msg MSG_011_5_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Deixe-me esclarecer. Eu tinha uma tarefa a fazer[n]e pedi a ele que me acompanhasse. Isso é tudo.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De qualquer forma, não dê atenção a ele.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quanto a você, não pretendo[n]revelar nada a ninguém.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Eiko]]
[s][vp 8 0 0 0 65535 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 6 7 300 65535]Oh, entendi! Na prática, nós[n]temos que guardar[n]o segredo um do outro?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Cara, e eu percebi agora que[n]seu namorado é aquele suposto[n]criminoso... Você é durona, presidente![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 6 7 300 1][vp 8 2 0 2029 65535 0]Eu já disse que não é assim![n][f 1 3 65535][w][e]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu só estava com medo de que você estivesse[n]envolvido em algo obscuro. Ele veio apenas para[n]me ajudar.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Eiko]]
[s][vp 8 0 0 0 65535 0]Mmmh... Tanto faz.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Enfim, eu só estava pensando...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Não é o estojo do Buchimaru-kun?!?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 2192 65535 0]Huh? Você conhece Buchimaru-kun...?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Eiko]]
[s][vp 8 0 0 0 65535 0]Eu tinha tipo, um monte de coisas de [n]Buchimaru-kun, quando eu era menor.[n]Que explosão de nostalgia![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Mas por que está tão acabado?[n][f 1 3 65535][w][e]

[msg MSG_017_1_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, eles me deram quando[n]eu ainda estava no ensino fundamental...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu gostaria de comprar um novo, mas eles não[n]vendem mais os brinquedos de Buchimaru-kun.[n][f 1 3 65535][w][e]

[msg MSG_017_2_0 [Eiko]]
[s][vp 8 0 0 0 65535 0]Tão engraçado! A presidente do conselho estudantil[n]com um estojo![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]A ideia que tive sobre você[n]hoje deu uma volta[n]de 360°![n][f 1 3 65535][w][e]

[msg MSG_017_3_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mmh, isso não é o mesmo de antes?[n][f 1 3 65535][w][e]

[msg MSG_017_4_0 [Eiko]]
[s][vp 8 0 0 0 65535 0]Huh? Mas o que eu sei. Estou tão[n]tão maravilhada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Você não parece ser do tipo que[n]gosta de coisas assim.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eu via você mais como uma[n]robô gentil, mas evidentemente[n]eu só precisava conhecê-la melhor.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Por que não trocamos números de telefone?[n]Então vamos falar sobre[n]Buchimaru-kun... e seu namorado.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 2185 65535 0]O-oh, um... OK.[n][f 1 3 65535][w][e]

[msg MSG_018_5_0 [Makoto]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Espera, ele não é meu namorado...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Eiko]]
[s][vp 8 0 0 0 65535 0]Eeee salvou![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Merda, já é tarde?[n]Tenho que ir trabalhar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Mas então eu te envio uma montanha[n]de fotos da minha coleção[n]de Buchimaru-kun. Tchau tchau![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2028 65535 0]Foi um furacão...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 6 3 300 65535][vp 8 0 0 0 65535 0]Mas, na verdade, estou chocada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ela pensou que eu era um robô...[n][f 1 3 65535][w][e]

[sel SEL_022_0_0 top]
[s]Não fique brava.[e]
[s][f 0 8 2 1 2217]Você pode mudar.[clr 27][e]
[s]Bip-boops.[e]

[msg MSG_023_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 3 5 6]Eu não me importo.[n]Eu entendo que posso dar[n]essa impressão.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2035 65535 0][f 5 13 3 10 6]Sim. É por isso que[n]você está aqui para me ajudar.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Makoto]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 6 3 300 1][vp 8 2 0 2046 65535 0]Não tire sarro de mim![n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 2100 65535 0]Sabe, acho que Takao-san[n]apenas expressou o que muitos[n]outros pensam de mim.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu pensei que tinha mudado,[n]depois do que aconteceu com Kaneshiro.[n]Mas talvez isso não tenha sido suficiente...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Dito isso, foi muito inspirador[n]conhecer alguém[n]tão diferente de mim.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A partir de hoje tentarei olhar[n]o mundo com novos olhos.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2127 65535 0]Acho que vai me ajudar a sair da minha concha, é[n]isso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Espero que você esteja pronto. Vou mostrar a você[n]como uma aluna modelo pode ser útil![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Eu sinto que Makoto é movida[n]por uma calma determinação...[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Agora que tenho o contato dela, será[n]interessante falar com a Takao-san.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Talvez eu até consiga corrigir[n]equívocos que ela tem sobre você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E, como sempre, em caso de[n]notícias importantes você será avisado.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Makoto]]
[s][vp 8 2 0 2054 65535 0]Bem, até mais.[n][f 1 3 65535][w][e]

