[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 4086 65535 0]Eu sei que minha ligação foi bastante[n]repentina. Eu só posso me desculpar.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Já decidimos que vamos nos opor ao Dr.[n]Maruki, então eu sei que é tarde demais[n]para dizer qualquer coisa, mas...[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]O que está errado?[e]
[s]Você nem consegue olhar para mim?[e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][vp 8 2 65535 0 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu simplesmente não consigo continuar[n]desviando meus olhos da verdade...![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu traí você, e tudo o que defendemos![n]Como posso fingir que ainda sou digno de[n]nossos ideais elevados? Ou seu apoio!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 53713 65535 0]Eu sou... sou um idiota totalmente sem[n]esperança![n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]De onde vem isso?[e]
[s]Nah, você é meio estranho.[e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...Me perdoe. Deixe-me começar desde o[n]início.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Por favor, eu não mereço consolador...![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 4157 65535 0]Você me deu minha força. Você me ensinou a[n]enfrentar a verdade sem medo...[n][f 1 3 65535][w][e]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 37 3 100][vp 8 2 0 0 65535 0]Essa força- essa raiva é como eu me levantei[n]contra Madarame. Eu o vi pela fraude que[n]ele era, e eu me libertei de suas[n]mentiras...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]E apenas olhe o que eu me tornei.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]O Dr. Maruki me deu uma falsa segurança. Ele[n]me mostrou uma vida girada de meus desejos[n]mais profundos, e tolo que eu sou, eu a[n]recebi![n][f 1 3 65535][w][e]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 45 3 100][vp 8 2 0 0 65535 0]Que humilhação indescritível...! Como eu[n]poderia ser uma ovelha tão detestável e de[n]mente estreita de um homem!?[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Acalmar.[e]
[s]Respire fundo.[e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 4024 65535 0]Eu não posso! Isso não é hora de calma![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]E você! Você de todas as pessoas merece me[n]envergonhar, mas ainda não diz nada!?[n]Eu te travei...![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu cuspi os próprios princípios da arte![n]E mais do que isso- eu cuspi tudo o que você[n]fez para me ajudar a encontrar minhas[n]respostas![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 53713 65535 0]Não sou nada... nem mesmo vale as palavras[n]vazias que falei...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu não posso nem me trazer para olhar você[n]nos olhos... perdoe-me, [n][f 4 2]...[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]Esse é o coração humano.[e]
[s]Não há beleza nisso?[e]

[msg MSG_013_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nossos corações estão realmente tão[n]iludidos? Somos tolos o suficiente para nos[n]apegar a essas fantasias equivocadas!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... você me oferece misericórdia Eu não[n]mereço! Não há beleza nisso![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 4039 65535 0]Impossível![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Que beleza humana poderia ser enterrada[n]nesta paisagem infernal de humilhação!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Não... eu me recuso a aceitar! Não seria[n]nada além de uma desculpa para o meu[n]fracasso![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu era escravo da minha arrogância o tempo[n]todo. Como eu já acreditei no significado da[n]verdadeira beleza ao meu alcance...?[n][f 1 3 65535][w][e]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 37 3 100][vp 8 2 0 0 65535 0]Eu era apenas um tolo, perdido em sonhos![n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]Então você está desistindo?[e]
[s]É um começo, não um fim.[e]

[msg MSG_017_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4186 65535 0]Desistindo...?[f 4 2], EU...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4182 65535 0]Eu vejo. Talvez haja verdade nisso.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][vp 1 0 0 0 0 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu só posso me desculpar. Você me salvou de[n]repetir meus erros mais uma vez.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Comparado ao grande legado da arte de minha[n]mãe... eu ainda sou, mas uma garota[n]brincando em sua sombra enquanto ela voa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu sonhava em voar ao seu lado. No entanto,[n]para todos os meus saltos de fé, eu só[n]despejei do meu ninho, de novo e de novo...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 53712 65535 0]O que eu precisava... era um professor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Para entender a beleza no trabalho de minha[n]mãe... eu precisava de uma mão orientadora,[n]para oferecer críticas e validação à medida[n]que ganhei.[n][f 1 3 65535][w][e]

[msg MSG_021_5_0 [Yusuke]]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Mas por que eu estava tão convencido de que[n]meu professor deve ser alguém no mundo da[n]arte?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4048 65535 0]Afinal, eu tenho um amigo como você...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]E nossas conversas juntas já me levaram a[n]tantas belas revelações.[n][f 1 3 65535][w][e]

[sel SEL_023_0_0 top]
[s]Você está emocionando meio difícil...[e]
[s]Espaço pessoal, Yusuke.[e]

[msg MSG_024_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Minhas desculpas- eu fiquei à frente de mim[n]mesmo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Mas meu argumento permanece. Eu acredito que[n]ainda há muito que posso aprender com você.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4168 65535 0]E se isso é verdade... então eu encontrei[n]meu professor. E com ele, o caminho para[n]realmente entender a arte de minha mãe.[n][f 1 3 65535][w][e]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 41 5 100][vp 8 2 0 0 65535 0]Eu não vou perder o meu caminho de novo...[n]Vamos seguir esse caminho juntos![n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Yusuke]]
[s][vp 8 2 0 4107 65535 0]Entendo... então esse poder é meu núcleo e[n]minha essência.[n][f 1 3 65535][w][e]

[msg PFM_026_5_0]
[s][vp 1 0 0 0 0 0]Persona de Yusuke [clr 1]Kamu Susano-O [clr 27]se transformou em [clr 2]Gorokichi [clr 27]![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 2]... Essa realidade de ideais e perfeições-[n]não está totalmente errada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Na verdade, há partes dele que acho quase[n]dolorosamente bonito.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No entanto... você me ajudou a ver[n]claramente novamente. Acredito que desejo[n]voltar à nossa própria realidade.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Combina-me muito melhor pintar com feiúra e[n]beleza na minha paleta.[n][f 1 3 65535][w][e]

[sel SEL_029_0_0 top]
[s]Esse é o yusuke que eu sei.[e]
[s]Você é bom agora?[e]

[msg MSG_030_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]Ha! De fato.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 59 5 100][vp 8 2 0 0 65535 0]Vamos voltar para nossa verdadeira casa. À[n]realidade em que descobri a verdadeira[n]beleza.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 4192 65535 0]... Ah, mas primeiro... você sabe o que eles[n]dizem sobre lutar com o estômago vazio.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 59 5 100][vp 8 2 0 0 65535 0]Isso me lembra- eu ainda nem lhe ofereci[n]chá. E você trouxe algum tipo de tratamento[n]com você também, não é?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]É uma geléia de feijão doce? Ou talvez uma[n]sobremesa assada, como Dorayaki?[n]Ou talvez você tenha trazido...[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Yusuke]]
[s][vp 8 2 0 4031 65535 0]Obrigado por gastar todo esse tempo comigo.[n]Vejo você de novo em breve.[n][f 1 3 65535][w][e]

