[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 10 300 65535][vp 8 2 0 7045 65535 0]Liguei para Nakaoka e Takeishi para[n]encontrá-los aqui. Vou contar a eles[n]o que Yamauchi está fazendo.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]E se eles brigarem?[e]
[s]Duvido que eles acreditem em você.[e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 10 300 1][vp 8 2 0 7024 65535 0]Heheheh...[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aí talvez você não tenha entendido:[n]gravei tudo que[n]falou aquele safado na boate![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu sou um gênio, eu sei.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De qualquer forma... eu posso[n]precisar de algum... backup.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você pode ficar por aqui?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]O que você quer, Sakamoto?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Nakaoka]]
[s][vp 8 0 0 0 65535 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 12 300 65535]...Takeishi?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]Nakaoka?!? Que diabos...?[n]Você quer me vencer em dois?!?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 12 300 1][vp 8 2 0 7036 65535 0]Vá com calma. Eu só quero[n]dizer uma coisa.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ouça. Aqui está a verdade[n]sobre a nova equipe de atletismo.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Voz de Yamauchi]]
[s][vp 8 0 0 0 65535 0]Será o renascimento de um grupo[n]acabado no abismo do[n]desespero. Que história linda![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Voz de Yamauchi]]
[s][vp 8 0 0 0 65535 0]E a melhor parte é que[n]Takeishi não é apenas rico, mas sua mãe[n]preside a associação de pais.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Voz de Yamauchi]]
[s][vp 8 0 0 0 65535 0]Até então, no entanto, isso me ajudará[n]demonstrar aos outros[n]os benefícios da obediência.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]Isso deve ser uma piada... Yamauchi[n]prometeu me tornar[n]capitão...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Nakaoka]]
[s][vp 8 0 0 0 65535 0]É tudo verdade?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 7194 65535 0]É a voz de Yamauchi, não é?[n]E então as coisas aconteceram[n]exatamente como ele disse.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Takeishi]]
[s][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Yamauchi está certo. Eu tenho[n]talento verdadeiro... Não sou como você.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eu estava me esforçando muito, mas você[n]estava sempre à minha frente...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Como alguém como eu pode ter sucesso?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Como posso ter[n]orgulho de mim mesmo?!?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Orgulhoso?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]Meu pai sempre fala para todo mundo[n]como está orgulhoso de mim...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Como ele, vou ganhar uma[n]bolsa de esportes...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Que eu seguirei seus passos,[n]formando-me em Taisei...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Então eu ouvi Yamauchi. Como[n]capitão, ele me escreveria uma[n]boa carta de recomendação.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 7156 65535 0]Então, você acreditou nas coisas[n]ele disse sobre Nakaoka por causa[n]essa besteira?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 12 300 65535]C-Cale a boca! O que[n]um bandido como você sabe?!?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Você não sabe como me sinto...[n]Ninguém sabe![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 12 300 1][vp 8 2 0 7187 65535 0]Inferno, eu não sei![n][f 1 3 65535][w][e]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 37 5 100][vp 8 0 0 0 65535 0]Há quanto tempo corremos juntos, hein?!? Nós[n]passamos por muita coisa, você e eu![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]Sakamoto...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Para quem você vive sua vida?[n]Para seus pais? Para[n]professores? Para a empresa?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Talvez você devesse parar de viver[n]para eles e tentar viver apenas[n]para si mesmo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você acha que tem que[n]trair os outros para[n]ter orgulho de si mesmo?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]B-bem, eu...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se você realmente acredita nisso,[n]você está muito errado![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 7192 65535 0]Nakaoka. Você também sabia que havia[n]algo errado com[n]Yamauchi, não sabia?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aquele bastardo nunca[n]se interessou por atletismo, não é?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas você permaneceu em silêncio. Você sabia que[n]ele estava cometendo uma injustiça, mas você[n]deixou isso acontecer.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Nakaoka]]
[s][vp 8 0 0 0 65535 0]...Sim.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eu estava com medo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Sem Yamauchi, a equipe[n]não teria renascido...[n]Teríamos permanecido párias.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 7169 65535 0]...sentiu muita falta de correr?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sabe, não é tão assustador[n]não fazer parte de algo.[n]De certa forma, a pessoa é livre.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Na verdade, me assusta pensar[n]que sou uma pessoa má.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu costumava ser como você...[n]Eu estava com medo e mentia para mim mesmo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então eu o conheci.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não era minha intenção[n]ofender você, mas é provável que[n]agora você esteja com raiva de mim.[n][f 1 3 65535][w][e]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 7 300 65535][f 4 24 0 4 0 41 5 100][vp 8 0 0 0 65535 0]Então... se você quer me bater, vá em frente.[n]Estou pronto.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]Se sim...[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Nakaoka]]
[s][vp 8 0 0 0 65535 0]Se você insiste.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 7 300 1][vp 8 2 0 7041 65535 0]Huh? Você realmente quer fazer isso?!?[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Nakaoka]]
[s][vp 8 0 0 0 65535 0]Você disse que[n]combina com você, não é?[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]U-espere! Pare![n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nghh... Você teve que[n]bater tão forte?[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Nakaoka]]
[s][vp 8 0 0 0 65535 0]Hahaha, você sabe que estou começando a[n]sentir realmente um pouco melhor?[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]Eu também. Acho que posso[n]finalmente deixar tudo[n]isso para trás.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Nakaoka... me desculpe.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Nakaoka]]
[s][vp 8 0 0 0 65535 0]Peço desculpas também.[n]Você quer reviver a equipe?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]Sim, cara![n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 1 300 65535][vp 8 2 0 7028 65535 0]Você viu, certo? Agora que[n]foi um ato violento![n][f 1 3 65535][w][e]

[sel SEL_040_0_0 top]
[s][f 0 8 2 1 2217]Está tudo bem...[clr 27][e]
[s]Você mereceu isso.[e]

[msg MSG_041_0_0 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 15 2]Não... Sempre cuidei muito[n]desse rostinho bonito[n]e olha o que aconteceu com ele.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 10 2]Sim. Afinal, fui eu[n]quem errei primeiro.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 1 300 1][vp 8 2 0 7079 65535 0]De qualquer forma, eles provavelmente[n]se sentem muito melhor agora e[n]não vão brigar de novo.[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 5 100][vp 8 0 0 0 65535 0]...Obrigado.[n][f 1 3 65535][w][e]

[sel SEL_044_0_0 top]
[s][f 0 8 2 1 2217]Eu não fiz nada.[clr 27][e]
[s]Você pretende reembolsar?[e]

[msg MSG_045_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 10 2]Conte-me. Você ficou[n]ali imóvel enquanto eles me davam uma surra[n]...[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 5 2]...Você está falando sério? Posso oferecer-lhe[n]alguns ramen, se você realmente quiser. Mas[n]você paga pelos ingredientes extras![n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas falando sério...[n]Você tem sido uma grande ajuda.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você me empurrou para...[n]ser legal.[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 5 100][vp 8 2 0 7024 65535 0]Era como se eu estivesse dando uma tacada... e[n]você correndo ao meu lado.[n][f 1 3 65535][w][e]

[sel SEL_048_0_0 top]
[s]Mas fiquei parado...[e]
[s][f 0 8 2 1 2217]Parece legal? Eles bateram em você![clr 27][e]

[msg MSG_049_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 5 2]Não assim![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Era uma metáfora, ou como quer que essas coisas[n]sejam chamadas por lá! Claro você não estava[n]concorrendo![n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 10 2]Você é impiedoso![n]Esqueça as surras que[n]levei, ok!?[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Eu sinto meu vínculo[n]com Ryuji ficando mais forte...[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7050 65535 0]Bem, vamos para casa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Minha boca está sangrando. Acho que[n]vamos comer alguma coisa[n]outra hora.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Ryuji]]
[s][vp 8 2 0 7053 65535 0]A gente se pega![n][f 1 3 65535][w][e]

