[msg MSG_FIRLD_1 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O último item permanece na lista...[n]"Ficar bem longe de você".[n][f 1 3 65535][w][e]

[msg MSG_FIRLD_2 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu gostaria de te mostrar uma coisa,[n][f 4 2].[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Venha para o meu quarto.[n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 9058 65535 0]Esta é uma lista de promessas[n]que escrevi com a mãe...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Veja, tudo aqui está marcado[n]como concluído.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Na verdade... isso não é verdade.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 0 5 100][vp 8 0 0 0 65535 0]Há uma promessa sobre a qual[n]menti... Uma promessa[n]que nunca cumpri.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]"Dando-se bem com Kana-chan".[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 9176 65535 0]Tudo começou quando[n]eu estava no ensino fundamental.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sofri bullying[n]porque era estranho...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 0 10 100][vp 8 0 0 0 65535 0]As outras crianças me acusaram[n]de trapacear porque[n]eu tirei nota máxima.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então, uma vez eu entreguei o dever de casa em[n]branco... mas a escola descontou na minha mãe.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A vida na escola era horrível.[n]Às vezes durante o recreio[n]eu me trancava no banheiro chorando...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu não tinha amigos...[n]Estava sempre sozinho.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então uma garotinha chamada Kana foi morar[n]conosco...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ela teve muitas faltas, mas quando[n]ela começou a vir, as crianças a intimidaram[n]como fizeram comigo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas um dia ele me disse[n]"Bom dia". A partir desse momento,[n]ele me cumprimentou todos os dias.[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Você gostou?[e]
[s][f 0 8 2 1 2217]Isso deve ter sido um choque.[clr 27][e]
[s]Como você reagiu?[e]

[msg MSG_006_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9199 65535 0][f 5 13 10 5 8]Sim, mas isso me surpreendeu.[n]Na época, ninguém[n]queria falar comigo.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 10 10 8]Exatamente! Quer dizer, na época[n]ninguém queria falar comigo.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Com toda a honestidade ... nas primeiras vezes[n]eu ignorei completamente. Eu pensei que[n]era uma piada dos valentões.[n][f 1 3 65535][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No entanto, ela sempre voltava[n]olá para mim...[n][f 1 3 65535][w][e]
[s][f 4 24 0 4 0 42 3 100][f 4 24 0 4 0 0 0 0][f 4 24 0 4 0 9 3 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu finalmente decidi responder a ela.[n]Meu coração estava prestes[n]a se partir em mil pedaços...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 36 5 100][vp 8 2 0 9191 65535 0]Aparentemente, ele manteve[n]olá para mim porque pensou[n]que poderíamos fazer amigos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ele foi a primeira pessoa que[n]não se importou com minhas peculiaridades...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Fiquei tão feliz por aquela amizade[n]que contei para minha mãe. Foi lá[n]que ele adicionou algo à lista.[n][f 1 3 65535][w][e]
[s][f 4 24 0 4 0 36 3 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]"Dando-se bem com Kana-chan".[n][f 1 3 65535][w][e]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 35 5 100][f 4 24 0 4 0 5 5 100][vp 8 0 0 0 65535 0]M-Mas... eu não consegui.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 9176 65535 0]Em um dia de muito vento,[n]Kana-chan deixou cair o diário[n]e as páginas voaram para todos os lados.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu não queria espiar...[n]mas vi o que[n]ele escreveu.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E... quando vejo alguma coisa,[n]não esqueço...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Futaba]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Foi realmente horrível...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ela escreveu que seus pais[n]bateram nela, que tiraram[n]fotos dela com roupas estranhas...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O diário de Kana-chan estava cheio[n]de histórias como essa...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 1 10 100][vp 8 0 0 0 65535 0]Quando perguntei a ela sobre isso...[n]ela imediatamente ficou na defensiva.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 0 8 100][vp 8 0 0 0 65535 0]Eu me senti péssimo, mas ela continuou[n]gritando porque eu li...[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s][f 0 8 2 1 2217]Você não poderia fazer mais nada.[clr 27][e]
[s]Você se desculpou com ela?[e]
[s]Ela é que estava errada.[e]

[msg MSG_015_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 9195 65535 0][f 5 13 10 5 8]É... mas eu não[n]consegui falar pra ele...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 1 8 100][vp 8 0 0 0 65535 0]Eu...preso...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 9198 65535 0]Nuh-uh... eu congelei...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 9198 65535 0]Não. Kana-chan não podia contar[n]a ninguém sobre essas coisas...Ela só podia[n]escrever para desabafar...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 1 8 100][vp 8 0 0 0 65535 0]Por isso, quando ela ficou brava[n]comigo, eu... parei...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Finalmente... eu fugi.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu fugi... Eu só queria que ele parasse de[n]gritar. Eu queria que tudo voltasse a ser como[n]era...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 1 7 100][vp 8 0 0 0 65535 0]...Kana-chan se mudou[n]pouco depois disso.[n]Eu não falei com ela desde então.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 0 5 100][vp 8 0 0 0 65535 0]E então... eu menti para minha mãe.[n]Mesmo depois que Kana-chan saiu[n]eu disse a ela que éramos amigas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 1 8 30][vp 8 0 0 0 65535 0]Todo mês, ela escrevia[n]a promessa na lista... e eu[n]mentia para ela todo mês.[n][f 1 3 65535][w][e]

[msg MSG_018_5_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 9182 65535 0]Eu gostaria de...Eu gostaria de me desculpar[n]de alguma forma com Kana-chan.[n]Eu gostaria de dizer a ela que sinto muito...[n][f 1 3 65535][w][e]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por não ajudá-la, mesmo que ela estivesse[n]passando por coisas muito piores do que eu...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][vp 8 0 0 0 65535 0]Por ler seu diário...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 35 5 100][vp 8 0 0 0 65535 0]Desculpas... por fugir...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu odeio ser tão covarde...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 40 5 100][vp 8 0 0 0 65535 0]Mas talvez, agora que sou um Phantom[n]Thief cumprindo minhas promessas,[n]eu possa enfrentar meus medos![n][f 1 3 65535][w][e]

[msg MSG_019_3_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 8 2 300 65535][vp 8 0 0 0 65535 0]"Dar-se bem com Kana-chan"...[n]Dessa vez eu vou![n][f 1 3 65535][w][e]

[msg MSG_019_5_0 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 9178 65535 0]Aaah! Eu não queria dizer a você[n]todas essas coisas...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Futaba]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 8 2 300 1][vp 8 2 0 9027 65535 0]N-Nem o Sojiro sabe...[n]É tão embaraçoso![n][f 1 3 65535][w][e]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]D-Vai ter que me ajudar tá?!?[n][f 1 3 65535][w][e]

[sel SEL_020_5_0 top]
[s]Entendo.[e]
[s]Você está muito insistente hoje.[e]

[msg MSG_020_7_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 8 12 300 65535][vp 8 0 0 0 65535 0]Isso também faz parte do acordo![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Parece que Futaba[n]começa a contar comigo...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Futaba]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 8 12 300 1][vp 8 2 0 9196 65535 0]Ok, vou começar a trabalhar![n]Hora de descobrir[n]informações sobre Kana-chan![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, e... desculpe se eu não fui[n]muito hospitaleiro hoje. Talvez[n]na próxima vez![n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Futaba]]
[s][vp 8 2 0 9012 65535 0]Agora, faça como as chitas[n]e saia correndo do meu quarto![n][f 1 3 65535][w][e]

