[msg MSG_000_0_0 [Homeless Man]]
[s][vp 8 0 0 0 4 0]Então você quer saber sobre alguns acordos[n]de negócios subterrâneos, hein?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Você sabe que você pode encontrar algo que[n]você precisa na internet, certo?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Homeless Man]]
[s][vp 8 0 0 0 4 0]Ou você talvez esteja procurando algo um[n]pouco mais? Eu posso ver isso em seus olhos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]... Quem te enviou aqui?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Eu quero.[e]
[s]Eu não posso te dizer.[e]
[s]Não é da sua conta.[e]

[msg MSG_003_0_0 [Homeless Man]]
[s][vp 8 0 0 0 4 0]Então, Iwai tem um garoto que venha reunir[n]informações para ele? Nunca esperaria que[n]alguém como alguém como ele.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Homeless Man]]
[s][vp 8 0 0 0 4 0]Ficando com o Código de Honra, hein?[n]Nada mal para uma criança.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Homeless Man]]
[s][vp 8 0 0 0 4 0]Certo. De qualquer forma, eu vou te dizer...[n]mas apenas uma vez. Você está entrando em[n]algum negócio obscuro aqui.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Homeless Man]]
[s][vp 8 0 0 0 4 0]Tudo bem, apenas aja como se eu estivesse[n]murmurando para mim mesmo, você entendeu?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Não há promessas que vou dizer algo útil[n]também.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Homeless Man]]
[s][vp 8 0 0 0 4 0]Então, um executivo para a máfia de Hong[n]Kong veio ao Japão algum tempo na rodada de[n]Ano Novo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Aparentemente, algo grande caiu com um[n]enorme investidor asiático. O negócio valeu[n]cerca de... 100 milhões de ienes.[n][f 1 3 65535][w][e]

[msg MSG_007_5_0 [Homeless Man]]
[s][vp 8 0 0 0 4 0]Então, um executivo para a máfia de Hong[n]Kong veio ao Japão algum tempo na rodada de[n]Ano Novo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Aparentemente, algo grande caiu com um[n]enorme investidor asiático. O negócio valeu[n]cerca de... 100 milhões de ienes.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Homeless Man]]
[s][vp 8 0 0 0 4 0]Embora você imagine algo tão enorme que[n]teria mais pessoas conversando sobre isso...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Talvez eles alugassem algum tipo de clube de[n]ponta para mantê-lo o mais privado[n]possível...?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Eu não ouvi nada sobre isso.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Homeless Man]]
[s][vp 8 0 0 0 4 0]Tudo bem, terminamos aqui. Ir.[n][f 1 3 65535][w][e]

