[msg MSG_000_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13058 65535 0]Ok, isso é o suficiente por hoje.[n]Oh, há... algo[n]que eu gostaria de falar com você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]É sobre o segredo que Tsuda estava falando. Não é[n]apenas sobre meu passado yakuza.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quero ter certeza de que você não[n]diga nada estúpido[n]se conhecer Kaoru...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quando eu estava no clã Hashiba, mais do que dez[n]anos atrás, uma garota meio perturbada veio ao[n]escritório[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ele teve um bebê com ele e[n]ele repetia que[n]queria vendê-lo.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Iwai]]
[s][bup 0 104 2 0 0][f 4 10 65535 0 0][vp 8 2 0 13104 65535 0]Ela provavelmente era uma drogada[n]à procura de dinheiro para uma dose.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quando recusei, ela colocou a criança no chão e[n]fugiu.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Aquela criança era Kaoru.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 0 13082 65535 0]Olhando para trás, ainda não sei[n]por que o levei comigo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não apenas tive que deixar o[n]clã, mas agora estou preso em[n]uma loja que nem gosto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hehehe. Todo dia[n]é uma batalha.[n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu ainda não consegui dizer a[n]Kaoru que eu era um yakuza...[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Por que não?[e]
[s]Você não deve mentir para seu filho.[e]

[msg MSG_006_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Diga-me um pouco. Como você se sentiria[n]se descobrisse que seus pais[n]estão envolvidos em negócios obscuros?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Iwai]]
[s][bup 0 104 3 0 0][f 4 10 65535 0 0][vp 8 2 0 13028 65535 0]Minha mãe era assim. Ele passou[n]noites bebendo e correndo[n]atrás de todos os homens possíveis.[n][f 1 3 65535][w][e]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][f 4 24 0 4 0 0 5 100][vp 8 0 0 0 65535 0]Eu não suportaria vê-la[n]destruir assim.[n]Eu gostaria de ter uma mãe diferente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E então... eu não queria colocar[n]Kaoru na mesma situação.[n]Ele merecia uma boa infância.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Iwai]]
[s][bup 0 104 2 0 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 104 3 300 65535][vp 8 0 0 0 65535 0]É por isso que deixei o clã.[n]Eu segui o código, mas Tsuda[n]está me envolvendo novamente...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quando ele lembrou da minha[n]loja, ele veio me pedir[n]modelos personalizados.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Iwai]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 104 3 300 1][vp 8 2 0 13104 65535 0]Mas não foi um pedido...[n]O desgraçado fez exigências[n]ameaçando contar tudo a Kaoru.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O problema é que Tsuda[n]sabe demais.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ele não apenas conhece o passado de[n]Kaoru, mas também histórias sobre mim[n]e o resto da minha família.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não sei o que aconteceria se[n]Kaoru descobrisse a verdade...[n][f 1 3 65535][w][e]
[s][bup 0 104 2 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 37 5 100][vp 8 0 0 0 65535 0]Mas Tsuda não pararia por aí.[n]Depois de Kaoru, ele contaria meus[n]segredos para o resto do mundo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eventualmente, ele tentaria[n]roubar tudo o que tenho de mim.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13026 65535 0]Se algo sobre meu passado fosse descoberto, Kaoru[n]seria tratada como eu sou tratado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por outro lado, pais ruins[n]criam filhos ruins...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se ele recebesse tal marca,[n]ele nunca se livraria dela. Ele[n]sempre seria o bode expiatório ideal.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Assim como aconteceu comigo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 13047 65535 0]É por isso que me tornei[n]a yakuza. Ninguém mais[n]teria me recebido.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]É por isso que não posso[n]enfrentar Tsuda.[n][f 1 3 65535][w][e]
[s][bup 0 104 2 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 37 5 100][vp 8 0 0 0 65535 0]Ele tem muito poder...[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]Você é gentil, Iwai.[e]
[s][f 0 8 2 1 2217]Você é patético.[clr 27][e]
[s]Você deveria chamar a polícia.[e]

[msg MSG_016_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13082 65535 0]Pff! Pare com essa besteira.[n]Eu não sou nada legal...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 0 13082 65535 0][f 5 13 13 10 1004]Hehehe. Você está certo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aposto que Kaoru está cansada[n]de ter um pai covarde como eu.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Iwai]]
[s][bup 0 104 2 0 0][f 4 10 65535 0 0][vp 8 2 0 13028 65535 0]Não é assim que o mundo funciona.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas eu acho que um garotinho[n]rigoroso como você não consegue entender...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Iwai]]
[s][bup 0 104 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No entanto, tentei desacelerar[n]Tsuda com alguns protótipos baratos,[n]para descobrir como detê-lo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas o desgraçado sabe esconder bem suas cartas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Além disso, ele entendeu o que eu estava tentando[n]fazer e começou a me observar constantemente.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por sorte, foi quando[n]você veio, garoto.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13032 65535 0]*suspiro* Desculpe, eu mencionei essas coisas do[n]nada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Você provavelmente não quer[n]mais nada comigo, hein?[n][f 1 3 65535][w][e]

[sel SEL_022_0_0 top]
[s]Exatamente.[e]
[s]Não faça suposições.[e]
[s][f 0 8 2 1 2217]Vou ficar pelas armas.[clr 27][e]

[msg MSG_023_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 0 13082 65535 0][f 5 13 13 5 1004]Eu não posso culpá-lo. Só um[n]louco ficaria ao meu lado.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13043 65535 0]Umpf... Tudo bem ser durão,[n]mas tente não baixar[n]a guarda, garoto.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 0 13048 65535 0][f 5 13 13 10 1004]Inferno ... você é realmente[n]uma aberração dessas coisas.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, certo. Eu nunca[n]recompensei você por informações.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você está certo.[n][f 1 3 65535][w][e]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 5 100][vp 8 0 0 0 65535 0]Que tal um desconto[n]no menu especial? Deve[n]prendê-lo por um tempo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 13083 65535 0]Não é uma oferta ruim, hein?[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que meu vínculo[n]com Iwai está ficando mais forte...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Droga, já é tarde.[n]Tenho que ir para casa.[n][f 1 3 65535][w][e]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 5 100][vp 8 2 0 13089 65535 0]Depois das aulas particulares, Kaoru[n]come por três. Imagino que[n]ele volte a crescer em breve.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De qualquer forma, estamos fechando por hoje.[n]Você deveria ir para casa também.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Iwai]]
[s][vp 8 2 0 13053 65535 0]Cuide-se, rapaz.[n][f 1 3 65535][w][e]

