[msg MSG_000_0_0 [Doctor's Voice]]
[s][vp 8 0 0 0 65535 0]... Qual é o motivo da sua visita?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Você está resfriado? Dor de estômago?[n]Pé de atleta? Seja o que for, você precisará[n]levar um número...[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Man's Voice]]
[s][vp 8 0 0 0 65535 0]...Basta disso![n][f 1 3 65535][w][e]

[msg MSG_000_6_0 [Man's Voice]]
[s][vp 8 0 0 0 65535 0]Você é o único que poderia ter desenvolvido[n]esse tipo de medicamento.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Doctor's Voice]]
[s][vp 8 2 0 14028 65535 0]Receio não ter ideia do que você está[n]falando...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Man's Voice]]
[s][vp 8 0 0 0 65535 0]Não jogue idiota comigo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Há rumores de que é uma droga tão potente[n]que pode dar a uma pessoa poder ilimitado.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Doctor's Voice]]
[s][vp 8 0 0 0 65535 0]Sério? Isso é novidade para mim.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Man's Voice]]
[s][vp 8 0 0 0 65535 0]O desenvolvimento de medicamentos[n]experimentais, medicina e remédios à base[n]de plantas viola todos os regulamentos de[n]saúde.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Você está tentando criar um[n]super-estimulante? Um medicamento como esse[n]só se tornará uma questão social.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Doctor's Voice]]
[s][vp 8 0 0 0 65535 0]Você é realmente persistente, sabe disso?[n]Eu sou apenas um charlatão...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Man's Voice]]
[s][vp 8 0 0 0 65535 0]A polícia pode não estar agindo, mas imagino[n]que a mídia em breve a compreenda.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Você pretende arruinar minha reputação[n]novamente, hein? Você é uma desgraça para a[n]comunidade médica.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Doctor's Voice]]
[s][vp 8 2 0 14041 65535 0]... tsk![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Man's Voice]]
[s][vp 8 0 0 0 65535 0]O que há com o visual? Esse foi o seu erro,[n]não foi?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Não serei responsável por suas ações[n]criminais. Descarte esse "medicamento"[n]imediatamente e renuncie.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]O nome "tae takemi" nunca vai- [n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Man's Voice]]
[s][vp 8 0 0 0 65535 0]Ei, está alguém aí!?[n][f 1 3 65535][w][e]

