[msg MSG_000_0_0 [Signora anziana]]
[s][vp 8 0 0 0 5 0]...Obrigado querida. É[n]meu lenço favorito.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 0 14020 65535 0]...estava bem[n]na minha frente, então...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Signora anziana]]
[s][vp 8 0 0 0 5 0]Céu! Você é tímido, hein?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Takemi]]
[s][bup 0 108 7 0 0][f 4 10 65535 0 0][vp 8 2 0 14042 65535 0]E-Eu não sou tímido![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Signora anziana]]
[s][vp 8 0 0 0 5 0]Minha vizinha fala muito bem de você.[n]Ela diz que seus remédios são[n]melhores do que os hospitais.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]É reconfortante saber que tenho um médico tão bom[n]aqui na cidade. Até breve.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 2 0 14028 65535 0]*suspiro* ...Que diabos?[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]Bem, você é famoso.[e]
[s]Você parece irritado.[e]
[s]Aconteceu alguma coisa?[e]

[msg MSG_007_0_0 [Takemi]]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Obrigado.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Takemi]]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Sim, graças a você.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Takemi]]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...É tudo culpa sua.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 2 0 14026 65535 0]Por causa daquela garotinha[n]e do pai dela, as pessoas falam[n]muito sobre mim na cidade...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eles parecem sair por aí[n]dizendo a todos que eu preparo[n]drogas milagrosas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O número de pacientes[n]aumentou dramaticamente.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não sei o que diabos está passando na[n]cabeça de algumas pessoas.[n]Recebi pedidos bobos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ontem, por exemplo, uma paciente[n]pediu um[n]comprimido "cheiroso".[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Outro dia eles me perguntaram algo "contra um[n]resfriado". Ah! Uma droga do Prêmio Nobel.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Depois pediram loções para[n]pele e cabelo...e até[n]uma consulta para um gato...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Takemi]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 0 14110 65535 0]Droga. Não sou um gênio da medicina.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]Você está se divertindo?[e]
[s]Mas você é um gênio.[e]

[msg MSG_015_0_0 [Takemi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 108 3 301 1][vp 8 2 0 14024 65535 0]...Não.[n][f 1 3 65535][w][e]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tudo isso interfere no[n]desenvolvimento. Eu só quero[n]completar o novo medicamento.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu sou o Flagelo, esse é o meu papel.[n]Não fui feito para[n]todo o resto.[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]Você é masoquista.[e]
[s][f 0 8 2 1 2217]Combina com você.[clr 27][e]
[s]Você não é sincero.[e]

[msg MSG_017_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 2 0 14104 65535 0]Não combina com você?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Takemi]]
[s][bup 0 108 4 0 0][f 4 10 65535 0 0][vp 8 2 0 14040 65535 0]O que é?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sério?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Takemi]]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 14 10 1008]...Bem, você tem direito[n]à sua opinião.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Takemi]]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 2 0 14042 65535 0][f 5 13 14 5 1008]...Ah, pare com isso.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 2 0 14087 65535 0]Mas um "médico de bairro", né...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu costumava apreciar[n]esse tipo de profissão e estilo de vida[n]mas agora...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh sim. Para esses ensaios clínicos...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Com tantos pacientes leva mais[n]tempo para análise de dados,[n]então precisamos acelerar.[n][f 1 3 65535][w][e]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 0 5 0]Este é um pouco mais forte,[n]mas tenho certeza que você vai ficar bem.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que meu vínculo[n]com Takemi está ficando mais forte...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Takemi]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 0 14001 65535 0]Parece que a garotinha[n]terá uma recuperação completa.[n][f 1 3 65535][w][e]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 59 5 100][f 4 24 0 4 0 0 5 100]O tratamento funciona bem para ela. Por enquanto,[n]posso respirar aliviado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Talvez ele possa[n]voltar para a escola em breve.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Takemi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 108 15 301 1][vp 8 2 0 14104 65535 0]...Que sorriso é esse?[n]Você está ansioso pelo próximo[n]ensaio clínico?[n][f 1 3 65535][w][e]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tudo bem, vamos nos divertir.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Takemi]]
[s][vp 8 2 0 14097 65535 0]OK, obrigado pelo esforço.[n][f 1 3 65535][w][e]

