[msg MSG_000_0_0 [Old Lady]]
[s][vp 8 0 0 0 5 0]...Obrigado, querido. Este é o meu lenço[n]favorito.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 0 14020 65535 0]... estava bem na minha frente, então...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Old Lady]]
[s][vp 8 0 0 0 5 0]Oh meu Deus! Você é tímido, não é?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Takemi]]
[s][bup 0 108 7 0 0][f 4 10 65535 0 0][vp 8 2 0 14042 65535 0]Eu não sou tímido.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Old Lady]]
[s][vp 8 0 0 0 5 0]Meu vizinho fala muito bem de você.[n]Ela diz que seus medicamentos são melhores[n]do que os dos grandes hospitais.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]É muito reconfortante ter um médico tão[n]distinto aqui na cidade. Vejo você de novo[n]em breve.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 2 0 14028 65535 0]* suspiro*... o que diabos?[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]Bem, alguém é popular.[e]
[s]Você parece irritado.[e]
[s]Aconteceu alguma coisa?[e]

[msg MSG_007_0_0 [Takemi]]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Graças à você.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Takemi]]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... Sim, obrigado a você.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Takemi]]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...É tudo culpa sua.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 2 0 14026 65535 0]Há muita conversa pela cidade sobre mim,[n]iniciada por aquela garota e seu pai...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aparentemente, eles estão dizendo a todos[n]que eu posso fazer todos esses medicamentos[n]e remédios incríveis.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então agora o número de pacientes que estou[n]atendendo aumentou dramaticamente.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não sei o que algumas dessas pessoas estão[n]pensando. Eu tive muitos pedidos malucos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Como ontem, um paciente solicitou uma[n]compactação de "cheiro doce".[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E outro dia, eu tinha um pedido de um[n]"buster frio". Ha! Uma droga como essa[n]merece um Prêmio Nobel.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Outros pedidos incluíram tônicos de cabelo e[n]pele... eu até tive que fazer uma consulta[n]sobre um gato...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Takemi]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 0 14110 65535 0]Sheesh. Não é como se eu fosse algum tipo de[n]médico genial.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]Se divertindo?[e]
[s]Você é um gênio.[e]

[msg MSG_015_0_0 [Takemi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 108 3 301 1][vp 8 2 0 14024 65535 0]...Não.[n][f 1 3 65535][w][e]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tudo isso está interferindo no meu[n]desenvolvimento. Só estou interessado em[n]completar meu novo medicamento.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esse é o meu papel de praga. Não sou[n]adequado para todas essas outras coisas.[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]Você é um masoquista.[e]
[s][f 0 8 2 1 2217]Combina com você.[clr 27][e]
[s]Você não é honesto.[e]

[msg MSG_017_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 2 0 14104 65535 0]Algo errado com isso?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Takemi]]
[s][bup 0 108 4 0 0][f 4 10 65535 0 0][vp 8 2 0 14040 65535 0]O que?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sério?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Takemi]]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 14 10 1008]... bem, você tem direito à sua opinião.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Takemi]]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 2 0 14042 65535 0][f 5 13 14 5 1008]... quieto, você.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 2 0 14087 65535 0]Mas um "médico da cidade", hein?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esse tipo de profissão de estilo de vida[n]pode ter sido possível para mim ao mesmo[n]tempo, mas agora...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, sim, sobre esses ensaios clínicos...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Com tantos pacientes novos, está demorando[n]mais para analisar os dados, então[n]precisarei acompanhar.[n][f 1 3 65535][w][e]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 0 5 0]Isso é um pouco mais forte, mas tenho[n]certeza que você ficará bem.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Parece que meu vínculo com Takemi está se[n]tornando ainda mais profundo...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Takemi]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 0 14001 65535 0]Parece que essa garota vai fazer uma[n]recuperação completa.[n][f 1 3 65535][w][e]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 59 5 100][f 4 24 0 4 0 0 5 100]O tratamento parece ser uma boa combinação[n]para ela. Então, pelo menos eu posso[n]respirar um pouco mais fácil, por enquanto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... Espero que ela possa frequentar a escola[n]em breve.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Takemi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 108 15 301 1][vp 8 2 0 14104 65535 0]... Com o que você está tão feliz? Você está[n]animado para o seu próximo ensaio clínico?[n][f 1 3 65535][w][e]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, então, vamos nos divertir.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Takemi]]
[s][vp 8 2 0 14097 65535 0]Ok, obrigado pelo seu trabalho duro.[n][f 1 3 65535][w][e]

