[msg MSG_000_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Boa noite.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Você se lembra de alguma coisa desde o[n]momento em que tomou o remédio até agora?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]HM, pelo olhar em seus olhos, eu diria que[n]você não.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Você acordou brevemente de seu coma, mas[n]ficou completamente atordoado durante todo[n]o exame.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]... você finalmente perdeu a consciência e[n]adormeceu.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Takemi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 108 16 300 1][vp 8 0 0 6 65535 0]Você está louco? Apenas um idiota teria[n]bebido isso.[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Eu não estou fora da minha mente.[e]
[s]É para meus exames.[e]

[msg MSG_005_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Multar. A propósito, a razão pela qual você[n]perdeu a consciência foi por causa do sabor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Produz um cheiro ruim quando se mistura com[n]sucos gástricos, semelhantes ao Surstomming.[n][f 1 3 65535][w][e]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0][f 4 24 0 6 0 1 5 100][f 4 24 0 6 0 36 5 100]Ah bem. Tudo o que importa é que, graças a[n]você, consegui obter bons dados.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Ok, é a minha vez de cumprir a minha parte[n]do acordo. É por isso que esperei até você[n]acordar.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Não quero que o público em geral saiba sobre[n]meus medicamentos originais.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Então, você é estritamente proibido de[n]divulgar o que acontece aqui a alguém...[n]entendido?[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]É claro.[e]
[s]O mesmo vale para você.[e]

[msg MSG_008_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Então é um acordo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Enquanto você vier aqui, eu lhe darei o[n]remédio a um bom preço sempre que quiser.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Posso até adicionar seleções adicionais, a[n]tempo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][bup 0 108 1 0 0][vp 8 0 0 16 65535 0][f 4 24 0 6 0 1 5 100][f 4 24 0 6 0 36 5 100]... Estou ansioso pelo seu patrocínio[n]contínuo.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Eu fiz um acordo com Takemi...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Então... quando você pode voltar para o[n]próximo ensaio clínico?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Oh, você também não se lembra dessa parte?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Bem, eu estava dizendo que os sujeitos dos[n]testes para adolescentes são bastante[n]valiosos no setor de pesquisa médica.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Então, eu vou fornecer o remédio para seus[n]exames de admissão e, em troca, você será[n]meu porquinho-da-índia.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Takemi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 108 13 300 1][vp 8 0 0 21 65535 0]... Eu tenho que aperfeiçoar este remédio.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Se você puder se mover agora, pode ir para[n]casa.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Tudo bem, tome cuidado.[n][f 1 3 65535][w][e]

[msg MSG_013_4_0 [Sae]]
[s][vp 8 0 0 800 65535 0]Considerando todas as ações que você tomou,[n]você deve ter alguém com experiência médica.[n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Sae]]
[s][vp 8 0 0 801 65535 0]Quem? E como você tratou suas feridas?[n][f 1 3 65535][w][e]

[msg MSG_013_6_0 [Sae]]
[s][vp 8 0 0 802 65535 0]Será fácil descobrir quem se investigarmos[n]isso, você sabe![n][f 1 3 65535][w][e]

[msg MSG_013_7_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você concordou com um novo contrato.[n]Excelente.[n][f 1 3 65535][w][e]

[msg MSG_013_8_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você deve se beneficiar do medicamento[n]milagroso que fortalece seu corpo.[n][f 1 3 65535][w][e]

