[msg MSG_000_0_0 [Kawakami]]
[s][bup 0 109 601 0 0][f 4 10 65535 0 0][vp 8 2 0 15080 65535 0]Na verdade, eu realmente gosto da sensação[n]antiga desta sala.[n][clr 2][f 1 9 0][clr 27][n][f 1 3 65535][w][e]
[s][bup 0 109 600 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 109 1 300 65535][f 4 24 0 6 0 36 5 100][vp 1 0 0 0 0 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas tenho que dizer adeus hoje.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Kawakami]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 109 1 300 1][vp 8 2 0 15091 65535 0]O problema é que eu decidi sair![n][f 1 3 65535][w][e]
[s][bup 0 109 601 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... Meu chefe me encontrou um trabalho de[n]meio período que paga melhor que este.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kawakami]]
[s][bup 0 109 603 0 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 109 5 300 65535][vp 8 0 0 0 65535 0]Os guardiões de Takase-Kun continuam[n]aumentando suas demandas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... Então é isso que eu tenho que fazer.[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]Essa é a decisão errada.[e]
[s]Por favor, reconsidere.[e]
[s][f 0 8 2 1 2217]É mesmo isto que queres?[clr 27][e]

[msg MSG_008_0_0 [Kawakami]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 109 5 300 1][vp 8 2 0 15095 65535 0]Então, qual é a decisão certa!?[n]Por favor, diga![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Kawakami]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 109 5 300 1][vp 8 2 0 15095 65535 0]Eu fiz... e foi isso que eu inventei![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Kawakami]]
[s][bup 0 109 603 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]O que eu quero...?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Kawakami]]
[s][bup 0 109 603 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Os guardiões de Takase-Kun dizem que a única[n]maneira verdadeira de se desculpar com[n]Takase-kun é pagando a eles.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se isso não é verdade, então o que é a coisa[n]certa a fazer aqui...?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Kawakami]]
[s][bup 0 109 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Gostaria de saber se posso escapar de tudo[n]isso se deixar de ser professor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pessoas como eu não têm o direito de ser[n]professor. Se eu desistir sozinha, não[n]terei que pagar...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]É por isso que vou deixar meu emprego de[n]professor e meu emprego de empregada...[n]O que você acha?[n][f 1 3 65535][w][e]

[sel SEL_018_0_0 top]
[s]Você está fugindo.[e]
[s][f 0 8 2 1 2217]Se foi isso que você decidiu.[clr 27][e]
[s]Eu preciso do meu professor.[e]

[msg MSG_019_0_0 [Kawakami]]
[s][bup 0 109 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 15 5 1009]Haha... outra repreensão, hein?[n][f 1 3 65535][w][e]
[s][bup 0 109 603 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas você está certo...[n]Estou apenas fugindo...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Kawakami]]
[s][bup 0 109 603 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]Foi isso que eu decidi...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas eu realmente decidi por conta própria...?[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Kawakami]]
[s][bup 0 109 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... heh... você sempre parece fazer coisas[n]sobre você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se eu pudesse seguir meu próprio caminho,[n]como você...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Kawakami]]
[s][bup 0 109 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Agora que penso nisso, é tarde demais para[n]eu parar de ser professor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se eu realmente me sentisse mal pelo que[n]aconteceu, teria renunciado no dia em que[n]ele morreu.[n][f 1 3 65535][w][e]
[s][bup 0 109 603 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E, no entanto, ainda senti a necessidade de[n]ensinar...[n]Eu me pergunto por que me sinto assim mesmo[n]agora.[n][f 1 3 65535][w][e]

[sel SEL_022_5_0 top]
[s]Tente lembrar-se.[e]
[s]Essa é a sua resposta.[e]
[s]Dê uma olhada em si mesmo.[e]

[msg MSG_023_0_0 [Kawakami]]
[s][bup 0 109 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... [f 4 1]-kun.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_023_5_0 [Kawakami]]
[s][bup 0 109 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, está certo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Decidi que a maneira de me desculpar com ele[n]era garantir que nunca haja outro aluno[n]como ele.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Porque eu poderia ter sido capaz de salvá-lo[n]se não tivesse medo de rumores ou etiquetas[n]naquela época.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu queria me tornar uma professora que cuida[n]de seus alunos. Essa é a mentalidade que eu[n]tinha![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Kawakami]]
[s][bup 0 109 603 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas agora, passo todo o meu tempo livre em[n]empregos de meio período, só para continuar[n]trabalhando como professor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Coloquei o trabalho crítico de um professor[n]em segundo plano, para poder ganhar[n]dinheiro com "desculpas".[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Foi aí que tudo deu errado...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu não posso fazer as coisas certas com[n]takase-kun assim...[n][f 1 3 65535][w][e]

[sel SEL_024_4_0 top]
[s]Você vai desistir?[e]
[s]Erros podem ser corrigidos.[e]

[msg MSG_024_6_0 [Kawakami]]
[s][bup 0 109 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Serei o professor que aspiro ser... esse é o[n]caminho certo para fazer as pazes com[n]Takase-Kun.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A partir daqui, me recuso a pagar mais[n]dinheiro![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E essa é a minha resposta!...Bem, o que você[n]acha?[n][f 1 3 65535][w][e]

[sel SEL_024_8_0 top]
[s][f 0 8 2 1 2217]Esteja confiante em sua resposta.[clr 27][e]
[s][f 0 8 2 1 2217]Essa é a escolha certa.[clr 27][e]
[s][f 0 8 2 1 2217]Você está perguntando a um aluno?[clr 27][e]

[msg MSG_030_0_0 [Kawakami]]
[s][bup 0 109 601 0 0][f 4 10 65535 0 0][vp 8 2 0 15034 65535 0][f 5 13 15 15 1009]Você não pode obter a resposta certa de[n]outra pessoa. Só pode ser encontrado por[n]dentro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... eu aprendi isso com você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De certa forma, você é meu professor.[n]... haha, apenas brincando.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Eu sinto a confiança de Kawakami em me[n]fortalecer...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Kawakami]]
[s][bup 0 109 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estou tão preocupado em ganhar dinheiro que[n]não prestei atenção aos meus alunos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Especialmente para você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu evitei meus olhos de você porque você foi[n]rotulado, assim como Takase-kun era...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas a partir de agora, vou protegê-lo[n]também. Como seu professor, nunca vou te[n]trair.[n][f 1 3 65535][w][e]

[sel SEL_032_0_0 top]
[s]Eu quero te proteger.[e]
[s][f 0 8 2 1 2217]Isso é reconfortante.[clr 27][e]

[msg MSG_033_0_0 [Kawakami]]
[s][bup 0 109 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]... Esse tipo de linha funciona apenas de[n]alguém com idade suficiente para lidar com[n]suas próprias tarefas domésticas.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Kawakami]]
[s][bup 0 109 601 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... mas, obrigado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vou falar com os Takases.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu não vou mais correr. Tudo deve ficar bem,[n]desde que eu fale com eles cara a cara.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Kawakami]]
[s][bup 0 109 602 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 15 15 1009]Deixe para mim! Eu posso ser decisivo quando[n]conta![n][f 1 3 65535][w][e]
[s][bup 0 109 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vou falar com os Takases.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu não vou mais correr. Tudo deve ficar bem,[n]desde que eu fale com eles cara a cara.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Kawakami]]
[s][bup 0 109 601 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tudo bem, é hora de eu ir.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 15031 65535 0]Obrigada. Até logo.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Kawakami]]
[s][vp 8 2 0 15191 65535 0]Boa noite.[n][f 1 3 65535][w][e]

