[msg MSG_000_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Sim, substitua o item anterior.[n]Sem problemas, certo? Vamos mudar[n]tudo, para ir até o fim![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Vou descartar os outros[n]e reescrevê-los.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Sim, amanhã de manhã...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Desculpe, era o chefe...[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Você está em boas condições?[e]
[s]Em que você está trabalhando?[e]

[msg MSG_003_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Foi fantástico. Ele está ignorando[n]ordens de cima, para me ajudar.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Vou escrever um artigo especial[n]sobre os Phantom Thieves, e[n]o chefe está me ajudando.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 41 3 100][f 4 24 0 4 0 12 3 100][f 4 24 0 4 0 0 5 100][vp 8 0 0 7 65535 0]Fale sobre suas origens e as[n]raízes dos problemas que[n]quer resolver.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 42 3 100][f 4 24 0 4 0 9 3 100][f 4 24 0 4 0 0 0 0][vp 8 0 0 8 65535 0]...Acho que capta bem[n]o espírito do jornalismo.[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Você é sério.[e]
[s][f 0 8 2 1 2217]Tem certeza de que isso é entretenimento?[clr 27][e]
[s]Não precisa das minhas informações?[e]

[msg MSG_006_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0][f 5 13 16 5 1007]É onde eu me saio melhor.[n]Afinal, sou jornalista,[n]certo?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0][f 5 13 16 10 1007]Comunicar notícias sérias de uma forma[n]que parece entretenimento...[n]Essa é a melhor parte, certo?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 42 3 100][f 4 24 0 4 0 12 3 100][f 4 24 0 4 0 0 0 0][vp 8 0 0 46 65535 0]Primeiro temos que atrair[n]as pessoas para comprar, e então[n]acertá-las com a verdade![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Esqueça isso! Suas observações e[n]análises são o coração[n]da história.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Upstairs foram contra,[n]mas os leitores gostaram muito do artigo.[n][f 1 3 65535][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 3 100][vp 8 0 0 13 65535 0]Depois de termos vendido[n]tantas cópias, eles não podem[n]fazer nada...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Portanto, queremos aproveitar[n]a oportunidade para publicar[n]outras peças.[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s]Fico feliz em ouvir isso.[e]
[s][f 0 8 2 1 2217]Vou ler a próxima edição.[clr 27][e]

[msg MSG_011_0_0 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0][f 5 13 16 10 1007]No entanto, estamos apenas começando.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0][f 5 13 16 15 1007]Obrigada. Continuo contando com a sua[n]contribuição para que possamos[n]vender exemplares, sabe.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ohya]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 107 1 301 1][vp 8 0 0 17 65535 0]Tudo bem, vamos comemorar a[n]vitória! Lala-chan, espero que você[n]tenha um pouco de Dom Perignon para trazer![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Lala Escargot]]
[s][vp 8 0 0 18 65535 0]Eu te disse antes.[n]Não temos nada parecido.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Achei que sim, então pedi[n]uma garrafa na loja de vinhos.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Lala Escargot]]
[s][vp 8 0 0 20 65535 0]Ufa... OK, vou buscar.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Inacreditável... Parece que Lala-chan[n]entendeu a dica.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Eu queria falar com você...[n]em particular.[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s]Sobre o que?[e]
[s]Gosto de conversar.[e]

[msg MSG_020_0_0 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Oh, que tal[n]relaxar um pouco?[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]Eu também avancei[n]preparações para uma história sobre[n]o consultor de Shido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]Vou descobrir a verdade...[n]jurei a Kayo.[n][f 1 3 65535][w][e]

[msg MSG_021_5_0 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]Mais uma vez... obrigado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]Toda vez que eu estava prestes a desistir,[n]você me incentivou a continuar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]Se eu cheguei aqui[n]foi só graças a você...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]...Senhor Ladrão Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]O despertar do coração do chefe[n]aconteceu de forma idêntica[n]como nos outros casos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]E com um timing realmente[n]perfeito. Você é o único que poderia[n]orquestrar tudo.[n][f 1 3 65535][w][e]

[sel SEL_023_0_0 top]
[s]Você sempre soube?[e]
[s]É uma coincidência.[e]
[s]O verdadeiro Ladrão Fantasma é Lala.[e]

[msg MSG_024_0_0 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Era óbvio demais.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Você não acha que estamos[n]unidos o suficiente para parar[n]de esconder isso de mim?[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]Lala-chan é mais uma... Ameaça Fantasma.[n]Oh, merda, ela vai ficar furiosa![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Depois de todos os últimos artigos[n]sobre os Phantom Thieves, acho que eles[n]são muito corajosos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Ajudar os fracos... punir os[n]vilões... essas são todas as coisas[n]que eles realmente fazem.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]De certa forma, nós dois temos o mesmo objetivo.[n]Queremos denunciar os males da sociedade.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Portanto, não revelarei sua verdadeira identidade[n]a ninguém. Vamos criar uma frente comum para[n]combater o mal.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]...Se não fosse por você,[n]eu nunca teria me tornado[n]o jornalista que fui.[n][f 1 3 65535][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 3 100][f 4 24 0 4 0 9 3 100][vp 8 0 0 38 65535 0]O garoto do ensino médio que me deu[n]informações[n]também conquistou meu coração ...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 36 3 100][vp 8 0 0 39 65535 0]Qualquer dia desses[n]retribuo o favor, ok?[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Ohya]]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]Hahaha! Até lá,[n]nós competiremos para ver quem[n]explica o mal primeiro![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Eu sinto um forte vínculo[n]com Ohya...[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]De qualquer forma, onde diabos[n]foi Lala-chan...?[n][f 1 3 65535][w][e]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 42 3 100][f 4 24 0 4 0 9 3 100][f 4 24 0 4 0 0 0 0][vp 8 0 0 42 65535 0]Vamos começar?[n]Já que estamos no clima[n]de comemorar?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Ohya]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 107 10 300 1][vp 8 0 0 55 65535 0]Eu me pergunto se hoje você poderá voltar para[n]casa? Eu quero estar com você tanto quanto[n]possível![n][f 1 3 65535][w][e]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 43 3 100][vp 8 0 0 56 65535 0]É uma oferta que você[n]não poderia recusar![n][f 1 3 65535][w][e]

