[msg MSG_000_0_0 [Shinya]]
[s][bup 0 110 3 0 0][f 4 10 65535 0 0][vp 8 2 0 17019 65535 0]Não vamos treinar hoje.[n]Estou um pouco confuso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, [f 4 1]-san...[n]Você é fã de[n]Phantom Thieves, não é?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então você com certeza sabe o[n]nome do site de fãs deles,[n]estou certo?[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Esta pergunta afetará[n]a confiança de Shinya em mim.[n]Tenho que responder corretamente![n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Site Phantom Aficionado[e]
[s]Site do Entusiasta Fantasma[e]
[s]Eu amo ladrões fantasmas.[e]

[msg MSG_003_0_0 [Shinya]]
[s][bup 0 110 0 0 0][f 4 10 65535 0 0][vp 8 2 0 17035 65535 0]...Claro que você respondeu certo,[n]já que você os conhece pessoalmente.[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Não sei como, mas consegui[n]manter a confiança dele![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Shinya]]
[s][bup 0 110 2 0 0][f 4 10 65535 0 0][vp 8 2 0 17037 65535 0]...O que? Não, não é isso![n]É o site Phantom Aficionado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você realmente teve a[n]coragem de mentir para mim![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu não vou te ensinar merda nenhuma.[n]Saia.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Shinya está começando a[n]perder a fé em mim...[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Ele entendeu que eu minto![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Preciso reconquistar a confiança dele.[n][f 1 3 65535][w][e]

