[msg MSG_000_0_0 [Shinya]]
[s][bup 0 110 3 0 0][f 4 10 65535 0 0][vp 8 2 0 17019 65535 0]Não vamos treinar hoje.[n]Estou ficando um pouco confuso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, [f 4 1]-san... você é um fã dos ladrões Phantom,[n]certo?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O que significa que você obviamente sabe o[n]nome do site de fãs, certo?[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Esta pergunta afetará a confiança de Shinya[n]em mim. Eu tenho que responder corretamente![n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Site Phantom Aficionado [e]
[s]Site de entusiastas da fantasma [e]
[s]I ladrões fantasmas do coração [e]

[msg MSG_003_0_0 [Shinya]]
[s][bup 0 110 0 0 0][f 4 10 65535 0 0][vp 8 2 0 17035 65535 0]... Acho que não há como você ter respondido[n]errado, já que os conhece pessoalmente.[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]De alguma forma, eu era capaz de manter sua[n]confiança![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Shinya]]
[s][bup 0 110 2 0 0][f 4 10 65535 0 0][vp 8 2 0 17037 65535 0]...O que? Não, não é! É o site do Aficionado[n]Phantom.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então você estava mentindo para mim, afinal![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não estou ensinando nada a você. Saia daqui.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Shinya está começando a perder a confiança[n]em mim...[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Ele viu através de minhas mentiras![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eu tenho que recuperar a confiança dele...[n][f 1 3 65535][w][e]

