[msg MSG_000_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 18027 65535 0]Não tenho certeza se entendi[n]seu comportamento recente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Espero que você não esteja[n]tentando me enganar...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]......[n][f 1 3 65535][w][e]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A propósito, há um pedaço de[n]shogi onde eu trancaria você imediatamente,[n]se eu estivesse me enganando.[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Esta pergunta afetará[n]a confiança de Hifumi em mim.[n]Eu tenho que responder corretamente![n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Bispo.[e]
[s]Torre.[e]
[s]Lançar.[e]

[msg MSG_003_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 18048 65535 0]Sim, isso mesmo...[n]Então você aprendeu um pouco sobre[n]shogi.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Com licença. Esqueça o que[n]eu disse...[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Não sei como, mas consegui[n]manter a confiança dele![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Hifumi]]
[s][bup 0 106 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Já ouviu falar da[n]torre?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E aí você fala que gosta de shogi?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 18103 65535 0]...Você é incrível.[n]Vá embora, por favor.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Hifumi está começando a[n]perder a fé em mim...[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Ele entendeu que eu minto![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Preciso reconquistar a confiança dele.[n][f 1 3 65535][w][e]

