[msg MSG_000_0_0 [Sumire]]
[s][bup 0 10 900 2 0][f 4 10 65535 0 0][vp 8 2 0 57037 65535 0]Desculpe por essa coisa repentina.[n]Espero que não tenha sido um problema.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 0 8 2 1 2217]Sem problemas.[clr 27][e]
[s][f 0 8 2 1 2217]Estou de férias.[clr 27][e]

[msg MSG_002_0_0 [Sumire]]
[s][bup 0 10 900 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 33 5 10]Obrigado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu só queria falar com você sobre algo[n]pessoalmente.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sumire]]
[s][bup 0 10 901 2 0][f 4 10 65535 0 0][vp 8 2 0 57058 65535 0]Uau, que cheiro bom... Obrigado.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sumire]]
[s][bup 0 10 901 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hum... que bom. Tem algo[n]relaxante sobre isso.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sumire]]
[s][bup 0 10 900 2 0][f 4 10 65535 0 0][vp 8 2 0 57136 65535 0]Em breve estarei pronto para mostrar[n]minha performance para o técnico Hiraguchi.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E se você não se importar, eu[n]gostaria que você estivesse lá[n]quando eu fizer isso... Tudo bem?[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s][f 0 8 2 1 2217]Com certeza.[clr 27][e]
[s][f 0 8 2 1 2217]Claro.[clr 27][e]

[msg MSG_007_0_0 [Sumire]]
[s][bup 0 10 901 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 33 5 10]Excelente! Estou tão feliz...[n][f 1 3 65535][w][e]
[s][bup 0 10 900 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 6 35 5 100]Mas não estamos aqui[n]para falar sobre isso.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sumire]]
[s][bup 0 10 900 2 0][f 4 10 65535 0 0][vp 8 2 0 57142 65535 0]Você se lembra do que eu disse quando[n]fomos comprar roupas?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Como eu queria me mostrar para você[n]e como isso me ajudou[n]a parar de me preocupar?[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s][f 0 8 2 1 2217]Claro que sim.[clr 27][e]
[s]Vagamente...[e]
[s]O que?[e]

[msg MSG_010_0_0 [Sumire]]
[s][bup 0 10 900 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 33 5 10]Que bom que você se lembra.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Sumire]]
[s][bup 0 10 904 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O-Oh, você esqueceu?[n][f 1 3 65535][w][e]
[s][bup 0 10 903 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 6 38 10 100]Hum... bem, eu disse que me sinto[n]mais seguro quando penso em[n]você me observando.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ocorreu-me natural dizer isso na época, mas...[n]olhando para trás é embaraçoso.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sumire]]
[s][bup 0 10 903 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu estava pensando em Kasumi...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quem sabe como ela se sentiu.[n]Ela não queria perder para mim,[n]mas queria que eu a observasse...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Sumire]]
[s][bup 0 10 900 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Talvez tivéssemos isso em comum.[n]Queríamos alguém que nos visse por[n]quem somos, por causa de nossos esforços.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Enquanto houver alguém especial nos observando,[n]podemos permanecer fortes.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sumire]]
[s][bup 0 10 900 2 0][f 4 10 65535 0 0][vp 8 2 0 57188 65535 0]Finalmente percebi algo.[n]Acho que parte da força de Kasumi[n]veio daí.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...E era em mim que ela[n]pensava.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nunca ouvi falar, mas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Talvez ele tenha tentado me contar[n]por meio de sua performance.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Sumire]]
[s][bup 0 10 903 2 0][f 4 10 65535 0 0][vp 8 2 0 57045 65535 0]Haha... Não acredito que[n]demorei tanto tempo[n]para descobrir isso... Sou tão estúpido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas estou feliz por finalmente ter descoberto[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mesmo sendo uma pessoa inútil,[n]espero ter ajudado Kasumi...[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s][f 0 8 2 1 2217]Eu sei que sim.[clr 27][e]
[s][f 0 8 2 1 2217]Você não é inútil.[clr 27][e]
[s][f 0 8 2 1 2217]Este é um novo começo.[clr 27][e]

[msg MSG_017_0_0 [Sumire]]
[s][bup 0 10 900 2 0][f 4 10 65535 0 0][vp 8 2 0 57186 65535 0][f 5 13 33 10 10]Sim... eu gostaria de pensar que sim.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Sumire]]
[s][bup 0 10 900 2 0][f 4 10 65535 0 0][vp 8 2 0 57186 65535 0][f 5 13 33 10 10]Sim... eu tenho que acreditar em mim mesmo.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Sumire]]
[s][bup 0 10 900 2 0][f 4 10 65535 0 0][vp 8 2 0 57186 65535 0][f 5 13 33 10 10]Sim... eu também acho.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Sumire]]
[s][bup 0 10 903 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Kasumi nunca[n]receberá minhas desculpas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não posso dizer a ela como me sinto. Ele nunca[n]verá minhas corridas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]É a realidade, e é tudo culpa minha.[n]Eu tenho fugido[n]desta história por muito tempo.[n][f 1 3 65535][w][e]
[s][bup 0 10 900 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 6 59 5 100]Mas não vou mais fugir. É hora de[n]andar com minhas pernas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu quero viver para nós dois agora.[n]Pelo bem de tudo o que[n]nós desejamos.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Sumire]]
[s][bup 0 10 902 2 0][f 4 10 65535 0 0][vp 8 2 0 57182 65535 0]Quero amadurecer ainda mais.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mesmo que eu chore depois de perder[n]uma corrida, ou se a pressão[n]for demais...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Com a coragem de Kasumi e a[n]graça que ela viu em[n]mim...vou continuar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu quero mostrar a Kasumi quem[n]Sumire Yoshizawa realmente é.[n][f 1 3 65535][w][e]

[msg MND_022_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que Sumire é movida[n]por uma grande determinação...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Sumire]]
[s][bup 0 10 907 2 0][f 4 10 65535 0 0][vp 8 2 0 57143 65535 0]Hum... E assim...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Agora que decidi, bem, não[n]fugir dos meus sentimentos...[n]eu, uh...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]H-há algo que eu tenho que te dizer,[n]senpai![n][f 1 3 65535][w][e]

[sel SEL_024_0_0 top]
[s]O que acontece?[e]
[s]Mais alguma coisa?[e]
[s][f 0 8 2 1 2217]Continuar.[clr 27][e]

[msg MSG_025_0_0 [Sumire]]
[s][bup 0 10 907 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh! D-desculpe! Estou chegando lá![n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Sumire]]
[s][bup 0 10 907 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh! D-desculpe! Estou chegando lá![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Sumire]]
[s][bup 0 10 907 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 33 10 10]O-Obrigado. É[n]suor nervoso, eu acho ...[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Sumire]]
[s][bup 0 10 907 2 0][f 4 10 65535 0 0][vp 8 2 0 57063 65535 0]Eu entendi que não queria[n]exibir, mas simplesmente[n]ser visto por uma pessoa...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu quero ser olhado por uma pessoa especial. De[n]alguém que só tem olhos para mim.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então pensei que, para mim, essa[n]pessoa especial é realmente você,[n]senpai! Então...talvez signifique...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Que eu... sou... eu... um...[n][f 1 3 65535][w][e]

[sel SEL_029_0_0 top]
[s]Coisa?[e]
[s]Eu o que?[e]

[msg MSG_030_0_0 [Sumire]]
[s][bup 0 10 902 2 0][f 4 10 65535 0 0][vp 8 2 0 57092 65535 0]Eu... eu estou apaixonado por você![n][f 1 3 65535][w][e]

[msg MND_031_0_0]
[s][vp 8 0 0 0 65535 0]Eu tenho que escolher as palavras[n]com cuidado...[n][f 1 3 65535][w][e]

[msg MND_032_0_0]
[s][vp 8 0 0 0 65535 0]Eu tenho que escolher as palavras[n]com cuidado...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Já estou [clr 2]namorando[n]outra garota[clr 27]...[n][f 1 3 65535][w][e]

[msg MSG_032_5_0 [Sumire]]
[s][bup 0 10 903 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hum, mas... Deixar[n]você desconfortável é a última coisa que[n]quero fazer, então...[n][f 1 3 65535][w][e]

[sel SEL_033_0_0 top]
[s]Vamos continuar amigos, ok?[e]
[s]Eu também te amo.[f 2 7 0 1 745 1][e]

[msg MSG_034_0_0 [Sumire]]
[s][bup 0 10 904 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]......![n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Sumire]]
[s][bup 0 10 900 2 0][f 4 10 65535 0 0][vp 8 2 0 57040 65535 0]...Muito obrigado, senpai. Estou feliz[n]que você seja tão honesto comigo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E estou feliz por ter dito a você[n]como me sinto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu não estou arrependido. Mesmo se eu não[n]retribuir, vou valorizar esses[n]sentimentos e seguir em frente.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Sumire]]
[s][bup 0 10 901 2 0][f 4 10 65535 0 0][vp 8 2 0 57142 65535 0]Ah, mas por favor...[n]As coisas não precisam[n]ser diferentes entre nós, ok?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você também é um amigo que[n]eu admiro e amo.[n]E isso nunca vai mudar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mesmo que como amigo, eu ainda gostaria que[n]você olhasse para mim.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Assista, e eu prometo a você[n]que continuarei melhorando![n][f 1 3 65535][w][e]

[sel SEL_037_0_0 top]
[s]Mostre-me o que você pode fazer.[e]
[s]Mal posso esperar para ver.[e]
[s][f 0 8 2 1 2217]Você sempre pode contar comigo.[clr 27][e]

[msg MSG_038_0_0 [Sumire]]
[s][bup 0 10 901 2 0][f 4 10 65535 0 0][vp 8 2 0 57186 65535 0][f 5 13 33 5 10]Direita! Irei além de suas expectativas![n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Sumire]]
[s][bup 0 10 901 2 0][f 4 10 65535 0 0][vp 8 2 0 57186 65535 0][f 5 13 33 5 10]Farei o meu melhor, senpai! Encontrarei[n]novas maneiras de surpreender você![n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Sumire]]
[s][bup 0 10 901 2 0][f 4 10 65535 0 0][vp 8 2 0 57186 65535 0][f 5 13 33 10 10]É claro! Conto com você![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, e você também pode contar sempre comigo.[n]Quero ajudar enquanto posso.[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Sumire]]
[s][bup 0 10 900 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, já é tarde...? Eu tenho que[n]fazer exercício.[n][f 1 3 65535][w][e]

[msg MSG_041_5_0 [Sumire]]
[s][bup 0 10 901 2 0][f 4 10 65535 0 0][vp 8 2 0 57071 65535 0]Muito obrigado pelo café.[n]Agora com licença...[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Sumire]]
[s][bup 0 10 907 2 0][f 4 10 65535 0 0][vp 8 2 0 57065 65535 0]Mas o que...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E-Eu... você também me ama?!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh. Huh? E-Então... isso significa[n]que meus sentimentos são[n]retribuídos?[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Sumire]]
[s][bup 0 10 907 2 0][f 4 10 65535 0 0][vp 8 2 0 57097 65535 0]Então, hum... O-o que vai acontecer agora?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Espere, isso significa...[n]Você vai ser meu namorado?!?[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Sumire]]
[s][bup 0 10 907 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]B-bem, quero dizer, isso é o que[n]eu estava esperando, não é...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh... O que estou dizendo...?[n][f 1 3 65535][w][e]

[sel SEL_046_0_0 top]
[s][f 0 8 2 1 2217]Acalme-se.[clr 27][e]
[s][f 0 8 2 1 2217]Não tenha pressa.[clr 27][e]

[msg MSG_047_0_0 [Sumire]]
[s][bup 0 10 907 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 33 5 10]D-desculpe, eu[n]saí e agora estou[n]estragando tudo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Honestamente? Eu nunca[n]esperava chegar tão longe.[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Sumire]]
[s][bup 0 10 903 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Uff...[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Sumire]]
[s][bup 0 10 902 2 0][f 4 10 65535 0 0][vp 8 2 0 57021 65535 0][f 4 2]-senpai, você poderia...[n]Olhe para mim por um momento?[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Sumire]]
[s][bup 0 10 903 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Gostaria de saber se... Se vai ser[n]diferente, agora que estamos...[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Sumire]]
[s][bup 0 10 904 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Uau, eu não sei mais o que estou dizendo...[n]Quer saber? Faz o mesmo...[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Sumire]]
[s][bup 0 10 907 2 0][f 4 10 65535 0 0][vp 8 2 0 57043 65535 0]Aaah![n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Sumire]]
[s][bup 0 10 907 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E-Um...[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Sumire]]
[s][bup 0 10 913 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu-eu…um…você…[n][f 1 3 65535][w][e]

[sel SEL_055_0_0 top]
[s][f 0 8 2 1 2217]Então? Alguma coisa mudou?[clr 27][e]
[s][f 0 8 2 1 2217]Você está todo vermelho.[clr 27][e]
[s][f 0 8 2 1 2217]Você é muito bonita.[clr 27][e]

[msg MSG_056_0_0 [Sumire]]
[s][bup 0 10 913 2 0][f 4 10 65535 0 0][vp 8 2 0 57098 65535 0][f 5 13 33 15 10]Eu, hum... Tudo o que sei é que[n]meu coração está batendo tão[n]forte que quase dói...[n][f 1 3 65535][w][e]

[msg MSG_057_0_0 [Sumire]]
[s][bup 0 10 913 2 0][f 4 10 65535 0 0][vp 8 2 0 57098 65535 0][f 5 13 33 15 10]P-por que você está tão perto![n][f 1 3 65535][w][e]

[msg MSG_058_0_0 [Sumire]]
[s][bup 0 10 913 2 0][f 4 10 65535 0 0][vp 8 2 0 57098 65535 0]Cos...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 33 15 10]E-Eu não posso... É como se[n]estivesse derretendo...[n][f 1 3 65535][w][e]

[msg MSG_059_0_0 [Sumire]]
[s][bup 0 10 907 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O que eu faço...? Estou com vergonha,[n]mas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Eu quero estar ainda mais próximo[n]perto de você, senpai.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_059_5_0 [Sumire]]
[s][bup 0 10 906 2 0][f 4 10 65535 0 0][vp 8 2 0 57092 65535 0]Eu te amo muito, [f 4 2]-senpai.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu quero que você sempre olhe para mim...[n][f 1 3 65535][w][e]

[msg MND_060_0_0]
[s][vp 8 0 0 0 65535 0]Agora eu sou o namorado de Sumire...[n][f 1 3 65535][w][e]

[msg MND_061_0_0]
[s][vp 8 0 0 0 65535 0]Não há como voltar atrás...[n][f 1 3 65535][w][e]

[msg MSG_062_0_0 [Sumire]]
[s][bup 0 10 906 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hum... Se chegarmos[n]mais perto, vamos bater[n]nos óculos um do outro...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 57096 65535 0]...Mas sempre podemos tirá-los.[n][f 1 3 65535][w][e]

[msg MND_063_0_0]
[s][vp 8 0 0 0 65535 0]Sumire e eu passamos[n]tempo juntos...[n][f 1 3 65535][w][e]

[msg MSG_064_0_0 [Sumire]]
[s][vp 8 2 0 57004 65535 0]D-De qualquer forma... eu tenho que ir[n]para o treinamento.[n][f 1 3 65535][w][e]

[msg MND_065_0_0]
[s][vp 8 0 0 0 65535 0]Acompanhei Sumire[n]até a estação...[n][f 1 3 65535][w][e]

