[msg MSG_000_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57033 65535 0]Você não esperava me encontrar[n]em tal lugar, hein?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 0 8 2 1 2217]Sim, é uma surpresa.[clr 27][e]
[s]Por nada.[e]
[s]O que está em sua mente?[e]

[msg MSG_002_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 33 5 10]Eu supus. Mas estou feliz que você[n]decidiu me agradar.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, isso é um alívio. De qualquer forma,[n]estou feliz que você veio.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você não precisa se preocupar tanto![n]Estamos apenas a uma gaiola de rebatidas![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Os batimentos treinam[n]reflexos, visão dinâmica e[n]melhoram o poder da postura.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]São todos elementos importantes[n]mesmo na ginástica![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Parece plausível, não é? Na verdade[n]tudo, eu só queria vir aqui.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Honestamente, eu queria que você me visse[n]bater um home run.[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]É tudo um pouco repentino.[e]
[s]Eu fico e observo...[e]

[msg MSG_008_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57037 65535 0]Lembrei-me de algo de quando eu era pequeno. Meu[n]pai me levava frequentemente para as gaiolas de[n]rebatidas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As outras crianças tinham medo de[n]ser atingidas pelas bolas, mas[n]eu adorava balançar o bastão.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quando bati uma bola, pensei:[n]"Não importa o quão rápido eles são![n]Vou mandá-los voar!"[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Achei que talvez pudesse[n]descobrir como recuperar minha coragem,[n]se voltasse a essa mentalidade.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O que você acha disso? Pode[n]funcionar, certo?[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Boa ideia.[e]
[s][f 0 8 2 1 2217]Poder. Estou de olho em você.[clr 27][e]
[s]Melhor limitar-se à ginástica.[e]

[msg MSG_010_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57186 65535 0][f 5 13 33 5 10]Verdadeiro? Acho que vai ajudar![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57058 65535 0][f 5 13 33 15 10]Eu me sinto tão cheio de energia![n]Vou te mostrar o que eu[n]sou capaz, [f 4 1]-senpai![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 57063 65535 0]E-eu sei porque você se sente assim,[n]mas uma mudança de planos[n]é sempre bom![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Kasumi]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 57159 10 0]E no home plate está Kasumi[n]Yoshizawa! Agora eu vou![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Kasumi]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Vamos![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0]O-Eles sempre foram tão rápidos?!?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Kasumi]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Vou pegar o próximo...![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][vp 8 0 0 0 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Kasumi]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 57158 10 0]OK, o aquecimento acabou![n]A partir de agora, todos serão[n]home runs![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Aaah![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Kasumi]]
[s][bup 0 10 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0]O-O quê...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 57180 10 0]S-Sinto muito...eu sabia que[n]estava enferrujado, mas não[n]pensei que sentiria falta de TODOS...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Não vi a bola chegando e continuei estremecendo.[n]Não pensei que estava tão mal...[n][f 1 3 65535][w][e]

[sel SEL_022_0_0 top]
[s]Não desista.[e]
[s]Não perca a esperança.[e]
[s]Você pode fazer isso, certo?[e]

[msg MSG_023_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Senpai...[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0][f 4 24 0 10 6 35 5 100]É claro! Vou tentar de novo![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Calma...não tenha medo...[n]Olhos na bola...[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Kasumi]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 57159 10 0]Aqui estou![n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Kasumi]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Vamos...![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Kasumi]]
[s][bup 0 10 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Ngh...[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Cos...[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Eu consegui...[n][f 1 3 65535][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57161 10 0][f 4 24 0 10 6 42 4 100][f 4 24 0 10 2 9 4 100]Consegui, senpai! Eu bati na bola![n][f 1 3 65535][w][e]

[sel SEL_030_0_0 top]
[s]Parabéns.[e]
[s][f 0 8 2 1 2217]Eu vi![clr 27][e]
[s]Como foi?[e]

[msg MSG_031_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0][f 5 13 33 10 10]Sem o seu encorajamento[n]eu não teria conseguido, senpai![n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0][f 5 13 33 15 10]Eu sabia que você estava me observando! É por[n]isso que fiz o meu melhor![n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0][f 5 13 33 5 10]É como se eu tivesse tirado um peso[n]dos meus ombros. Eu me sinto ótimo![n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Até agora sempre trabalhei por conta própria. Eu[n]realmente queria causar uma boa impressão.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Mas sinto a necessidade de[n]atender às suas expectativas[n]já que nos conhecemos, [f 4 1]-senpai.[n][f 1 3 65535][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0][f 4 24 0 10 6 42 3 100]Esse sentimento[n]me fortaleceu![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Esqueci como é[n]trabalhar duro para outra pessoa...[n][f 1 3 65535][w][e]

[sel SEL_035_0_0 top]
[s][f 0 8 2 1 2217]É importante.[clr 27][e]
[s]Não se esqueça desse sentimento.[e]

[msg MSG_036_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57154 10 0][f 5 13 33 15 10]Já! Muito obrigado![n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57026 10 0][f 5 13 33 5 10]Claro, exatamente![n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Desde que te conheci, senpai,[n]aprendi muito sobre mim.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Mas agora, sinto-me a um passo de[n]ganhar minha autoconfiança.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57136 10 0]Oh, certo! Ultimamente eu também[n]sinto mais relaxado e enérgico![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Ainda não voltei ao[n]normal, mas[n]minhas notas também estão melhorando.[n][f 1 3 65535][w][e]

[sel SEL_040_0_0 top]
[s]Bom trabalho.[e]
[s]Ainda não acabou![e]

[msg MSG_041_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57039 10 0]Sim! Ainda tenho que mostrar a você[n]o que posso fazer![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Da próxima vez, você não vai me ver atrapalhado[n]com o bastão. Vou te mostrar uma nova rotina de[n]ginástica![n][f 1 3 65535][w][e]

[msg MND_042_0_0]
[s][vp 8 0 0 0 65535 0]Sinto a grande confiança que[n]Kasumi deposita em mim...[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 10 0]No entanto, ainda temos muitas[n]piadas. É a sua vez, senpai![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 10 0]Bata na bola com toda[n]sua força! Manda pro espaço![n][f 1 3 65535][w][e]

[msg MND_044_0_0]
[s][vp 8 0 0 0 65535 0]Eu suei pra caramba nas[n]gaiolas de rebatidas com Kasumi ...[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Kasumi]]
[s][vp 8 0 0 0 10 0]Oh, desculpe, eu tenho que ir.[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Kasumi]]
[s][vp 8 2 0 57002 65535 0]Muito obrigado por hoje.[n][f 1 3 65535][w][e]

