[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8061 65535 0]Desculpe ter arrastado você até aqui.[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu estava por aqui coletando[n]informações e notei alguns[n]clientes jogando isso...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu fiz algumas pesquisas. Aparentemente[n]é um atirador muito difícil.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você joga jogos assim?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Tempo todo.[e]
[s]Não, eu não sou muito bom.[e]
[s]E você?[e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, talvez você já jogou[n]isso também? Bem, só posso pedir-lhe[n]para ter calma.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, isso deve reduzir[n]qualquer desvantagem.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Também não jogo muito[n]videogame, então acho que[n]estamos no mesmo barco.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pessoalmente, não.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, tenho certeza que vou ficar bem.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][vp 8 0 0 0 65535 0]......[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Menino exuberante]]
[s][vp 8 0 0 0 9 0]Cara, que objetivo. Aquele cara[n]com o cabelo castanho não[n]está perdendo tempo.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Jovem rude]]
[s][vp 8 0 0 0 7 0]Até o de quatro olhos está se dando bem,[n]embora esteja visivelmente perdendo terreno...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Fiuuu! Amanhã vou acordar com dedos grossos. No[n]entanto, é um jogo bastante realista.[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s][f 0 8 2 1 2217]Você está acostumado com tiroteios?[clr 27][e]
[s]Você levou a sério, né?[e]

[msg MSG_010_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 5 13 9 5 9][vp 8 2 0 8161 65535 0]Ah, você notou isso? Bem, se eu quiser[n]vencê-lo, tenho que praticar[n]o máximo possível.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...brincadeirinha.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Receio que sou um novato.[n]Talvez seja devido à proverbial[n]sorte de iniciante.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8161 65535 0]Ah, você notou isso? Bem, se eu quiser[n]vencê-lo, tenho que praticar[n]o máximo possível.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Haha, brincadeira.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O que é, eu tinha um olhar tão assustador?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Seja como for, isso me deixou[n]um pouco nostálgico.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quando eu era pequeno, eu tinha uma arma de[n]brinquedo como esta.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E brincar me lembrou[n]de correr pela casa[n]segurando, fingindo ser um herói...[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s][f 0 8 2 1 2217]Você queria ser um herói?[clr 27][e]
[s]Muito interessante.[e]
[s]Difícil de acreditar.[e]

[msg MSG_017_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][f 5 13 9 10 9][vp 8 2 0 8036 65535 0]Não tenho certeza, mas[n]olhando para trás, acho que sim.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 5 13 9 5 9][vp 8 2 0 8038 65535 0]Você diz? Não parece tão[n]incomum para uma criança pequena.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Akechi]]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 8028 65535 0]Porque? Que tipo de pessoa[n]você pensa que eu sou?[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas existem diferentes tipos de[n]heróis, é claro. E[n]diferentes filosofias com as quais se identificam.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por exemplo, alguns se apegam[n]à sua visão de justiça,[n]mesmo que outros a rejeitem...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Enquanto para outros basta agradar[n]a opinião pública, perseguindo[n]aprovação e gratificação como heróis.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nós iremos? Qual dessas duas[n]alternativas melhor se adequa[n]à sua concepção de herói?[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s]Apegue-se à sua própria justiça.[e]
[s]Faça o que as pessoas querem.[e]
[s]Nenhum dos dois, na verdade.[e]

[msg MSG_022_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Bem, imaginei que você diria isso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas se ninguém mais defende a justiça[n]pela qual eles lutam, não é[n]apenas moralismo cego?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 54468 65535 0]Que surpresa. Não pensei que[n]você diria isso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas acho que está certo. Afinal,[n]se essa "justiça" é indesejada,[n]torna-se apenas moralismo vazio.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você acha que existe uma terceira opção?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Acho que lutar por uma[n]justiça que ninguém quer,[n]torna isso apenas um moralismo cego.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8032 65535 0]Oh, desculpe. Acho que saí pela tangente...[n]Perdoe-me.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]É que quando falo com você, não consigo[n]não mergulhar[n]nesses tópicos abstratos...[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]Sinto meu vínculo com[n]Akechi ficando mais forte...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Meu Deus, eu quebrei a[n]suar com esse jogo. Agora[n]vou cheirar como fliperama...[n][f 1 3 65535][w][e]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Um banho me faria bem.[n]Que tal me despedir?[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Akechi]]
[s][vp 8 2 0 8054 65535 0]Até a próxima.[n][f 1 3 65535][w][e]

