[msg MSG_000_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 11093 65535 0]So this is a slave camp... The décor[n]é bizarramente alegre por um lugar tão[n]horrível...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estou surpreso que alguém esteja operando no[n]coração da cidade como esta.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Originalmente, pensei que esses lugares[n]precisariam se esconder nas sombras, longe[n]do escrutínio público.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Clara]]
[s][vp 8 2 0 48600 65535 0]* Giggle* Bem-vindo para casa, mestre![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Justine]]
[s][bup 0 101 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você está se dirigindo a mim? Você está[n]muito enganado sobre quem é seu mestre...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Viemos aqui para observar completamente,[n]Justine.[n]Não se preocupe, vamos libertá-la quando[n]terminarmos.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei você.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Clara]]
[s][vp 8 0 0 0 65535 0]Sim mestre?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Diga-me, por que você está sorrindo assim?[n]Você é um escravo.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Clara]]
[s][vp 8 0 0 0 65535 0]Huh? Um escravo? O que você quer dizer,[n]mestre?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 15 301 65535][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Talvez você tenha pedido para sorrir, mas o[n]quê?[n]Você não tem vontade de rebelião? Ou você é[n]apenas naturalmente submisso?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Clara]]
[s][vp 8 0 0 0 65535 0]Bem, mestre, uhhh... eu não sei![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 15 301 1][vp 8 2 0 11097 65535 0]O que há com este insuportável... ei, preso![n]Você realmente acha que recebe reabilitação[n]adequada aqui!?[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]Você se acostuma com isso.[e]
[s]Você não gosta?[e]
[s]Eu não sei![e]

[msg MSG_013_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 2 0 11001 65535 0]Então você está dizendo que está aprendendo[n]como é ser um escravo...? Hmph, eu não[n]gosto do som disso![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 2 0 11100 65535 0]É seguro dizer que estou muito além de não[n]gostar![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 2 0 11022 65535 0]Você parece ser executado!?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 12089 65535 0]Acalme-se, Caroline.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Clara]]
[s][vp 8 0 0 0 65535 0]Ah, você não é apenas o mais fofo? *risada* [n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Assista! Você acha que rir de seus mestres é[n]uma disciplina adequada?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Clara]]
[s][vp 8 0 0 0 65535 0]* suspiro* Ohhhhh, agora eu entendo![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Você está aqui para o serviço de disciplina,[n]é isso?[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Clara]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 7 301 65535][vp 8 0 0 0 65535 0]Então ouça, seu pequeno camarão![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 7 301 1][vp 8 2 0 11096 65535 0]Wha-!?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Clara]]
[s][vp 8 0 0 0 65535 0]Pare de Gawkin 'para mim e já encomende![n]Você quer ser chocado com um de aqueles[n]pequenos garfos de camarão!? Fora com isso![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Caroline]]
[s][bup 0 102 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]SH-SH-SHE fora do jugo da opressão...![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Clara]]
[s][vp 8 0 0 0 65535 0]O QUE ACABEI DE DIZER!? Pedido! Ou você[n]precisa de um menu- se puder até ler! É[n]isso? Widdle Baby não consegue chame um[n]menu?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Caroline]]
[s][bup 0 102 4 0 0][f 4 10 65535 0 0][vp 8 2 0 11055 65535 0]A-ahh...[n][f 1 3 65535][w][e]

[sel SEL_026_0_0 top]
[s]Apenas o serviço usual, na verdade.[e]
[s]Vamos derrubar um pouco.[e]
[s]Por favor, não assedie as crianças.[e]

[msg MSG_027_0_0 [Clara]]
[s][vp 8 2 0 58353 65535 0]Como você deseja, Mestre- aqui está o menu![n]O que posso trazer você hoje?[n][f 1 3 65535][w][e]

[msg MSG_027_1_0 [Clara]]
[s][vp 8 2 0 58352 65535 0]Ohhh, então você queria o serviço normal,[n]afinal? Whoopsy-Daisy, fiquei à frente de[n]mim mesmo lá![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Aqui está o menu![n][f 1 3 65535][w][e]

[msg MSG_027_3_0 [Clara]]
[s][vp 8 2 0 58352 65535 0]Oh, eu estava exagerando? Whoopsy-Daisy,[n]fiquei um pouco pego lá![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Aqui está o menu![n][f 1 3 65535][w][e]

[msg MSG_027_5_0 [Caroline]]
[s][bup 0 102 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O que está errado com ela... seu humor muda[n]em um instante.[n][f 1 3 65535][w][e]

[msg MSG_027_7_0 [Justine]]
[s][bup 0 101 3 0 0][f 4 10 65535 0 0][vp 8 2 0 12021 65535 0]Essa versatilidade... ela poderia possuir o[n]potencial do poder do curinga?[n][f 1 3 65535][w][e]

[msg MSG_027_8_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, não importa isso. Devemos nos[n]concentrar no assunto em questão.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Justine]]
[s][bup 0 101 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O que poderia ser isso?[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Caroline]]
[s][bup 0 102 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Love★Pancake? What do they put in it?[n]Nada suspeito, espero...[n][f 1 3 65535][w][e]

[sel SEL_030_0_0 top]
[s]Amor.[e]
[s]Veneno.[e]
[s]É uma surpresa.[e]

[msg MSG_031_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eles colocam "amor" nele? Como isso é[n]possível?[n]O amor não é uma substância física! Eles[n]estão enganando você aqui?[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos pedir outra coisa.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, eu vejo! É assim que os rebeldes do[n]escravo se manifestam! Até a indústria de[n]alimentos é uma questão de vida e morte[n]neste mundo.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos pedir outra coisa.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Isso poderia ser uma forma do que alguns[n]chamam de "roleta russa"?[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não podemos arriscar as chances de ser[n]envenenado.[n]Vamos pedir outra coisa.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nesse caso, vamos com a sincera omelete.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Clara]]
[s][vp 8 0 0 0 65535 0]Como você deseja, Mestre.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Clara]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 15 301 65535][vp 8 2 0 58358 65535 0]Oh não! Eu estraguei tudo. Por favor, me[n]perdoe, masterrrrr![n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 15 301 1][vp 8 2 0 11043 65535 0]Como você ousa!? Corrija isso agora mesmo![n]Você pode implorar por perdão uma vez que eu[n]receba uma refeição perfeitamente sincera![n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Clara]]
[s][vp 8 0 0 0 65535 0]Mas... mas... eu enchei de amor...[n][f 1 3 65535][w][e]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 15 301 65535][vp 8 0 0 0 65535 0]Waaah...[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 15 301 1][vp 8 2 0 11105 65535 0]Nem tente aquele ato de falso em mim![n][f 1 3 65535][w][e]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Consertá-lo! Tempo duplo! Não estou deixando[n]você sair até que esteja certo![n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Clara]]
[s][vp 8 0 0 0 65535 0]N-no, eu... eu não posso... eu tentei tão,[n]tanto... mas sou tão desajeitado... eu até[n]pratiquei uma tonelada, e... e...[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Caroline]]
[s][bup 0 102 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Uh— ei...[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Justine]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 7 301 65535][bup 0 101 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Como você poderia fazer esse pobre escravo[n]chorar assim...[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 7 301 1][vp 8 2 0 11028 65535 0]Wha-!? Tudo bem, eu vou dizer que sinto[n]muito![n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Olha, eslavo- quero dizer, empregada! Eu[n]sinto Muito![n]Vou comer, vou comer! Apenas... pare de[n]chorar![n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Clara]]
[s][vp 8 2 0 58359 65535 0]Você irá!? Yaaaay! Muito obrigado![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Você se importaria com um chá de oo-quente[n]para acompanhá-lo? Eu também recomendo o[n]café relaxante![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eu prometo derramar meu coração para[n]fazê-los para você![n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Caroline]]
[s][bup 0 102 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tudo bem, traga o que quer que seja...[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Caroline]]
[s][bup 0 102 5 0 0][f 4 10 65535 0 0][vp 8 2 0 11028 65535 0]Isso tem sido tão cansativo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Até as pessoas que estão sendo servidas[n]precisam se comportar de uma certa[n]maneira... luto para compreender por que é[n]tão complicado.[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E, no entanto, as pessoas aqui estão[n]dispostas a pagar um bom dinheiro para[n]participar desta farsa de mestrado...[n][f 1 3 65535][w][e]
[s][bup 0 101 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 38 5 100]Os comprimentos que os humanos irão para[n]manter posições de poder... seus desejos[n]parecem realmente ilimitados.[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De qualquer forma, consideramos sua tarefa[n]completa.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aqui está a sua recompensa.[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sinto como se tivéssemos visto um lado da[n]humanidade hoje que era novo para nós.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De fato... este não é um novo evento para[n]nós neste momento.[n][f 1 3 65535][w][e]

[msg MSG_055_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Parecemos testemunhar novas facetas da[n]humanidade a cada tarefa especial que[n]realizamos.[n][f 1 3 65535][w][e]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 10 301 65535][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mais intrigante mesmo...[n][f 1 3 65535][w][e]

[msg MSG_056_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 10 301 1][vp 8 2 0 11092 65535 0]Mas a única coisa que importa para você é a[n]sua reabilitação- e você não esquece![n][f 1 3 65535][w][e]

[msg MND_057_0_0]
[s][vp 8 0 0 0 65535 0]Eu acompanhei os gêmeos de volta para a sala[n]de veludo...[n][f 1 3 65535][w][e]

