[msg MSG_000_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 12021 65535 0]Bem... a informação estava correta.[n]Parece haver muitos[n]objetos em exibição aqui.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Seria uma exposição de arte? Já[n]ouvi falar...parece envolver[n]o senso estético humano...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos, vamos revistar o prédio.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Justine]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 15 301 65535][bup 0 101 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você tem ideia de como alguém[n]aprecia a arte adequadamente?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 15 301 1][vp 8 2 0 55020 65535 0]O que você está insinuando!?![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Justine]]
[s][bup 0 101 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pare de falar alto.[n]As placas proíbem.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Caroline]]
[s][bup 0 102 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E-Eu sei... Seja como for,[n]apresse-se para apreciar[n]esta arte.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Justine]]
[s][bup 0 101 3 0 0][f 4 10 65535 0 0][vp 8 2 0 12066 65535 0]... Fiuuu. O número de trabalhos na[n]exposição superou em muito[n]as minhas expectativas.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, arte[n]não pode ser considerada carente de variedade.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Algumas obras eram decididamente[n]fotorrealistas. Mas não seria mais[n]fácil tirar uma foto diretamente?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E então queremos falar sobre esses[n]"retratos" ou como eles são chamados?[n]Qual é o sentido de pintar um rosto grande?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As "paisagens" são ainda mais misteriosas.[n]O que há de interessante em[n]pintar um terreno chato?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Qual é a graça de pintar[n]humanos ou cenários apenas para[n]outros humanos olharem?[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s]É apreender a sua "verdadeira beleza".[e]
[s]É para auto-satisfação.[e]
[s]Não é engraçado.[e]

[msg MSG_011_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah entendi. Existem algumas pinturas[n]de flores e mulheres nobres que[n]certamente se encaixam na descrição.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Caroline]]
[s][bup 0 102 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas também há imagens de coisas[n]como montanhas desoladas e[n]velhos enrugados.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Existe alguma "verdadeira beleza" neles também?[n]Eu simplesmente não entendo...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então você está dizendo que[n]artistas representam apenas o que[n]eles querem ver?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E então eles se sentam e[n]ouvem as pessoas discutirem e[n]apreciarem seu trabalho?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Que gesto inútil e ao mesmo tempo[n]tremendamente humano...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Justine]]
[s][bup 0 101 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quero dizer, não é uma forma de[n]entretenimento? Agora o fim[n]é ainda mais incompreensível para mim.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se houver algo que[n]não saibamos, duvido que você[n]saiba.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A propósito, havia um trabalho semelhante[n]e uma confusão de rabiscos.[n]Por que exibir tal reprovação?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu posso entender a existência de diferentes[n]níveis de artesanato, mas então[n]isso não foi muito infantil?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Justine]]
[s][bup 0 101 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não, se tem uma garotinha aqui, é você. Até eu[n]senti algo especial naquela pintura.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Caroline]]
[s][bup 0 102 4 0 0][f 4 10 65535 0 0][vp 8 2 0 11036 65535 0]Mas do que você está falando? Eles são rabiscos,[n]no entanto, você olha para isso! O rosto está[n]bagunçado, nariz e orelhas errados.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Foi uma representação precisa[n]da escuridão que habita no[n]coração humano.[n][f 1 3 65535][w][e]
[s][bup 0 101 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 44 5 100]Que pena, Carolina. Parece[n]que você não tem nem um[n]fragmento de senso estético.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você é bem vindo? Vou te dizer quem[n]falta, Justine... É VOCÊ[n]quem falta dioptrias![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Justine]]
[s][bup 0 101 2 0 0][f 4 10 65535 0 0][vp 8 2 0 12097 65535 0]Talvez falte sentido...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Parece que você precisa de uma[n]boa sacudida cerebral.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Justine]]
[s][bup 0 101 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O mesmo poderia ser dito sobre você.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, prisioneiro... você gostaria de me dizer[n]que bagunça[n]é realmente arte?[n][f 1 3 65535][w][e]

[sel SEL_026_0_0 top]
[s]É arte.[e]
[s]São rabiscos.[e]
[s]A arte é inspiradora.[e]

[msg MSG_027_0_0 [Justine]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 17 301 65535][bup 0 101 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hahaha. Hora de admitir[n]derrota, Caroline.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 17 301 1][vp 8 2 0 11105 65535 0]Grrr... Sua opinião é[n]válida, Prisioneiro![n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 2 0 11048 65535 0]Haha! Você perdeu desta vez,[n]Justine. Admita.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Justine]]
[s][bup 0 101 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A opinião do Prisioneiro[n]não é uma referência confiável.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Caroline]]
[s][bup 0 102 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Entendo o que você quer dizer...[n]Ou pelo menos eu acho...[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas acho que você está apenas[n]evitando a pergunta... Tudo bem,[n]vamos considerar um empate, por enquanto.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Donna sorpresa]]
[s][vp 8 0 0 0 65535 0]Ei, você viu a pintura que parece[n]um novelo de rabiscos?[n]Dizem que vale 500 milhões de ienes![n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Mamma intellettuale]]
[s][vp 8 0 0 0 65535 0]Coisa? Até meu bebê[n]poderia fazer algo assim.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Caroline]]
[s][bup 0 102 4 0 0][f 4 10 65535 0 0][vp 8 2 0 11096 65535 0]500 milhões... Realmente não faz[n]sentido.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nisso concordo plenamente[n]com você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mais investigações são necessárias.[n]Continuamos a inspecionar o local.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vimos uma grande[n]quantidade de trabalhos interessantes...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas aquela última escultura...[n]Não passava de uma reprodução de mau gosto[n]de um corpo nu.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você realmente quer que eu acredite[n]que ISSO conta[n]como arte também?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Justine]]
[s][bup 0 101 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu pensei que o conceito de "beleza"[n]apenas tivesse muitas formas,[n]mas é o reino do bizarro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por que os humanos perseguem[n]"beleza" em primeiro lugar?[n][f 1 3 65535][w][e]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 59 5 100]Você também perde seu tempo[n]perseguindo a beleza, Prisioneiro?[n][f 1 3 65535][w][e]

[sel SEL_039_0_0 top]
[s]Sim.[e]
[s]Eu prefiro ser feio.[e]
[s]Eu já sou bonita.[e]

[msg MSG_040_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Como quiser, mas é melhor pensar[n]na sua reabilitação... na sua[n]alma, antes de se dedicar à sua aparência.[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sua feiúra é indiferente para nós,[n]mas trabalhe em sua reabilitação,[n]em cultivar sua alma.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Justine]]
[s][bup 0 101 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...De onde vem toda essa[n]admirável segurança?[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Veremos como você se sente depois que[n]jogo você no lixo.[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De qualquer forma, vimos a arte que os humanos[n]tanto gostam. A tarefa está concluída.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aqui está sua recompensa.[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No entanto, ainda não entendo[n]por que alguns humanos chamam[n]o outono de "estação das artes"...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, não faz nada. Que tal[n]voltar e tentar[n]fazer nossas pinturas?[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Boa ideia. Mas o que pintamos?[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Uma guilhotina?[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...O mestre?[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55028 65535 0]...Bem, encontraremos uma solução[n]assim que você voltar. Ei,[n]Prisioneiro! Mexa-se.[n][f 1 3 65535][w][e]

[msg MND_051_0_0]
[s][vp 8 0 0 0 65535 0]Acompanhei os gêmeos[n]até o Velvet Room...[n][f 1 3 65535][w][e]

