[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1069 65535 0]Isso parece certo.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1070 65535 0]Isso não parece certo...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Mr. Hiruta]]
[s][bup 0 303 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37150 65535 0]Hoje é o segundo dia de exames.[n]Você pode começar.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [History]]
[s][vp 8 0 0 0 65535 0]Qual das seguintes expressões veio do nome[n]da posição que Minamoto no Yoshitsune[n]manteve?[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Atendente de panela quente.[e]
[s]Patrocínio do magistrado.[f 2 7 0 0 25 1][e]
[s]Marido dominador.[e]
[s]Fanfarrão.[e]

[msg MSG_005_0_0 [English]]
[s][vp 8 0 0 0 65535 0]Qual é a origem da palavra em inglês[n]"talento"?[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]O nome de uma soma da moeda.[f 2 7 0 0 25 1][e]
[s]O nome de um santo.[e]
[s]O nome de um artista.[e]

[msg MSG_007_0_0 [Ms. Chouno]]
[s][bup 0 304 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37200 65535 0]Todo mundo tem um teste?[n]Então você pode começar.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Social Studies]]
[s][vp 8 0 0 0 65535 0]Do que o filósofo grego Sócrates disse que o[n]mal nasceu?[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Desejo.[e]
[s]Ignorância.[f 2 7 0 0 25 1][e]
[s]Curiosidade.[e]

[msg MSG_010_0_0 [Math]]
[s][vp 8 0 0 0 65535 0]Qual é o menor número de cores necessárias[n]para pintar o Japão, então não há duas[n]áreas adjacentes da mesma cor?[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]2.[e]
[s]4.[f 2 7 0 0 25 1][e]
[s]8.[e]
[s]47.[e]

[msg MSG_012_0_0 [Ms. Usami]]
[s][bup 0 305 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37253 65535 0]Este é o segundo dia das finais.[n]Você pode começar.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Science]]
[s][vp 8 0 0 0 65535 0]Qual das seguintes afirmações é verdadeira[n]para esse organismo?[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]É um caranguejo de neve.[e]
[s]Não está relacionado a caranguejos.[f 2 7 0 0 25 1][e]
[s]Não é comestível.[e]
[s]É uma espécie protegida.[e]

[msg MSG_015_0_0 [Social Studies]]
[s][vp 8 0 0 0 65535 0]O que se diz ser a razão pela qual as[n]pessoas começaram a sonhar em cores?[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]Fotografias.[e]
[s]Filmes.[e]
[s]Televisão.[f 2 7 0 0 25 1][e]

[msg MSG_017_0_0 [Mr. Hiruta]]
[s][bup 0 303 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37150 65535 0]Hoje é o terceiro dia das finais. Você está[n]pronto? Então você pode começar.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Math]]
[s][vp 8 0 0 0 65535 0]Qual destes foi feito usando a proporção de[n]prata?[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s]O Partenon.[e]
[s]Papel de tamanho B4.[f 2 7 0 0 25 1][e]
[s]As pirâmides.[e]

[msg MSG_020_0_0 [English]]
[s][vp 8 0 0 0 65535 0]Defina "syn" e "aistese", as palavras-raiz[n]gregas de "sinestesia".[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s]"Sound" e "Color".[e]
[s]"Arte" e "Música".[e]
[s]"Juntos" e "sentidos".[f 2 7 0 0 25 1][e]
[s]"Sense" e "Sobreposição".[e]

[msg MSG_022_0_0 [Ms. Usami]]
[s][bup 0 305 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37270 65535 0]Este será o segundo dia de exames.[n]Por favor, comece.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Math]]
[s][vp 8 0 0 0 65535 0]Qual das seguintes afirmações sobre essa[n]bola é verdadeira?[n][f 1 3 65535][w][e]

[sel SEL_024_0_0 top]
[s]Ele foi projetado para TV em cores.[e]
[s]É um poliedro regular.[e]
[s]A proporção preta para branca é 1: 2.[e]
[s]Tem trinta e dois rostos.[f 2 7 0 0 25 1][e]

[msg MSG_025_0_0 [English]]
[s][vp 8 0 0 0 65535 0]Qual é o significado de "Robota", a palavra[n]tcheca que é a palavra raiz de "robô"?[n][f 1 3 65535][w][e]

[sel SEL_026_0_0 top]
[s]Humano sintético.[e]
[s]Máquina precisa.[e]
[s]Trabalho escravo.[f 2 7 0 0 25 1][e]

[msg MSG_027_0_0 [Ms. Chouno]]
[s][bup 0 304 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37200 65535 0]Hoje é o terceiro dia dos exames.[n]Vá em frente e comece.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [English]]
[s][vp 8 0 0 0 65535 0]Qual é o nome em inglês para o fenômeno,[n]onde parece que seu telefone celular está[n]vibrando?[n][f 1 3 65535][w][e]

[sel SEL_029_0_0 top]
[s]Sensações de variação fantasma.[e]
[s]Síndrome de volume perceptivo.[e]
[s]Síndrome de vibração fantasma.[f 2 7 0 0 25 1][e]

[msg MSG_030_0_0 [Social Studies]]
[s][vp 8 0 0 0 65535 0]Qual das seguintes afirmações é verdadeira[n]em relação aos pescadores corvos-marinhos[n]de Nagaragawa?[n][f 1 3 65535][w][e]

[sel SEL_031_0_0 top]
[s]Eles são funcionários do governo local.[e]
[s]Eles pertencem ao Mext.[e]
[s]Eles pertencem à agência doméstica imperial.[f 2 7 0 0 25 1][e]
[s]Qualquer um pode se tornar um.[e]

[msg MSG_032_0_0 [Ms. Usami]]
[s][bup 0 305 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37270 65535 0]Este é o segundo dia de seus exames.[n]Por favor, comece.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [English]]
[s][vp 8 0 0 0 65535 0]Qual traje de cartas representa o Santo[n]Graal?[n][f 1 3 65535][w][e]

[sel SEL_034_0_0 top]
[s]Clubes.[e]
[s]Espadas.[e]
[s]Corações.[f 2 7 0 0 25 1][e]
[s]Diamantes.[e]

[msg MSG_035_0_0 [Japanese]]
[s][vp 8 0 0 0 65535 0]Qual das alternativas a seguir não é[n]verdadeira sobre o Kanji para "Crow"?[n][f 1 3 65535][w][e]

[sel SEL_036_0_0 top]
[s]Vem do som que um corvo faz.[e]
[s]Foi tirado da aparência de um corvo.[e]
[s]Inclui um número.[f 2 7 0 0 25 1][e]

[msg MSG_037_0_0 [Mr. Hiruta]]
[s][bup 0 303 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37150 65535 0]Goste ou não, tudo termina hoje.[n]Agora, você pode começar.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Social Studies]]
[s][vp 8 0 0 0 65535 0]Que país se refere a uma pessoa que controla[n]a política nos bastidores como um[n]"primeiro-ministro de preto"?[n][f 1 3 65535][w][e]

[sel SEL_039_0_0 top]
[s]EUA.[e]
[s]França.[e]
[s]Grã Bretanha.[e]
[s]Japão.[f 2 7 0 0 25 1][e]

[msg MSG_040_0_0 [History]]
[s][vp 8 0 0 0 65535 0]A palavra japonesa "Dokyuu" se traduz em[n]"massivo". Que palavra em inglês inspirou o[n]"fazer" inicial em Dokyuu?[n][f 1 3 65535][w][e]

[sel SEL_041_0_0 top]
[s]Domínio.[e]
[s]Dreadnought.[f 2 7 0 0 25 1][e]
[s]Dreadlock.[e]

[msg MSG_042_0_0 [Mr. Hiruta]]
[s][bup 0 303 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37150 65535 0]Hoje é o segundo dia de exames.[n]Você pode começar.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Science]]
[s][vp 8 0 0 0 65535 0]Qual função cerebral é responsável pelo[n]fenômeno de ver uma ilusão nesta figura?[n][f 1 3 65535][w][e]

[sel SEL_044_0_0 top]
[s]Obstrução.[e]
[s]Exultação.[e]
[s]Alucinação.[e]
[s]Conhecimento.[f 2 7 0 0 25 1][e]

[msg MSG_045_0_0 [Math]]
[s][vp 8 0 0 0 65535 0]Qual dos mapas a seguir você pode pintar sem[n]áreas adjacentes sendo da mesma cor?[n][f 1 3 65535][w][e]

[sel SEL_046_0_0 top]
[s]Mapa do mundo.[e]
[s]Mapa do Japão.[e]
[s]Ambos.[f 2 7 0 0 25 1][e]

[msg MSG_047_0_0 [Ms. Chouno]]
[s][bup 0 304 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37200 65535 0]Todo mundo tem um teste?[n]Então você pode começar.[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Social Studies]]
[s][vp 8 0 0 0 65535 0]Nomeie o livro que definiu "Malefactor" como[n]o principal fator no progresso da raça[n]humana.[n][f 1 3 65535][w][e]

[sel SEL_049_0_0 top]
[s]Compêndio de leis.[e]
[s]Digital Devil Story.[e]
[s]Julieta.[e]
[s]O dicionário do diabo.[f 2 7 0 0 25 1][e]

[msg MSG_050_0_0 [Japanese]]
[s][vp 8 0 0 0 65535 0]Que arquétipo de personagem se refere a uma[n]mulher misteriosa e sedutora, geralmente[n]com motivos ocultos?[n][f 1 3 65535][w][e]

[sel SEL_051_0_0 top]
[s]Ingnee.[e]
[s]Femme fatale.[f 2 7 0 0 25 1][e]
[s]Crone.[e]
[s]Columbina.[e]

[msg MSG_052_0_0 [Ms. Usami]]
[s][bup 0 305 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37253 65535 0]Este é o segundo dia das finais.[n]Você pode começar.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Science]]
[s][vp 8 0 0 0 65535 0]Escreva o nome e o gênero deste organismo.[n][f 1 3 65535][w][e]

[sel SEL_054_0_0 top]
[s]Horsehair Crab (Erimacrus).[e]
[s]Snow Crab (Chionoecetes).[e]
[s]Red King Crab (Paralithodes).[f 2 7 0 0 25 1][e]

[msg MSG_055_0_0 [Social Studies]]
[s][vp 8 0 0 0 65535 0]O que aconteceu quando o governo emitiu[n]papel e moedas duras no Japão pela primeira[n]vez?[n][f 1 3 65535][w][e]

[sel SEL_056_0_0 top]
[s]Causou tumultos.[e]
[s]O governo entrou em colapso.[e]
[s]Causou confusão na economia.[f 2 7 0 0 25 1][e]

[msg MSG_057_0_0 [Mr. Hiruta]]
[s][bup 0 303 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37150 65535 0]Hoje é o terceiro dia das finais. Você está[n]pronto? Então você pode começar.[n][f 1 3 65535][w][e]

[msg MSG_058_0_0 [English]]
[s][vp 8 0 0 0 65535 0]Qual é o equivalente em inglês do idioma[n]norueguês "Bruxas de Chovera"?[n][f 1 3 65535][w][e]

[sel SEL_059_0_0 top]
[s]Chovendo filhotes.[e]
[s]Sapos chovendo.[e]
[s]Chuando gatos e cães.[f 2 7 0 0 25 1][e]

[msg MSG_060_0_0 [Japanese]]
[s][vp 8 0 0 0 65535 0]Qual das alternativas a seguir é outro nome[n]para o macarrão Soumen tradicionalmente[n]comido em Tanabata?[n][f 1 3 65535][w][e]

[sel SEL_061_0_0 top]
[s]Seda de Orihime.[e]
[s]Coragem dos demônios.[f 2 7 0 0 25 1][e]
[s]Coração demoníaco.[e]
[s]Canal estrelado.[e]

[msg MSG_062_0_0 [Ms. Usami]]
[s][bup 0 305 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37270 65535 0]Este é o segundo dia de seus exames.[n]Por favor, comece.[n][f 1 3 65535][w][e]

[msg MSG_063_0_0 [History]]
[s][vp 8 0 0 0 65535 0]Quem conduziu execuções usando este[n]dispositivo?[n][f 1 3 65535][w][e]

[sel SEL_064_0_0 top]
[s]Louis XV.[e]
[s]Joseph-Ignace Guillotin.[e]
[s]Charles-Henri Sanson.[f 2 7 0 0 25 1][e]

[msg MSG_065_0_0 [Social Studies]]
[s][vp 8 0 0 0 65535 0]Qual é a razão pela qual a maioria das[n]pessoas não pode se tornar um pescador de[n]Nagarasawa?[n][f 1 3 65535][w][e]

[sel SEL_066_0_0 top]
[s]Requer um aprendizado.[e]
[s]É uma profissão hereditária.[f 2 7 0 0 25 1][e]
[s]Eles não têm coragem.[e]

[msg MSG_067_0_0 [Ms. Chouno]]
[s][bup 0 304 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37200 65535 0]Hoje é o terceiro dia dos exames.[n]Vá em frente e comece.[n][f 1 3 65535][w][e]

[msg MSG_068_0_0 [English]]
[s][vp 8 0 0 0 65535 0]Qual é o significado de "Robota", a raiz[n]etimológica de "robô"?[n][f 1 3 65535][w][e]

[sel SEL_069_0_0 top]
[s]Uma boneca mecanizada.[e]
[s]Trabalho escravo.[f 2 7 0 0 25 1][e]
[s]A classe de trabalho.[e]

[msg MSG_070_0_0 [Science]]
[s][vp 8 0 0 0 65535 0]Qual das alternativas a seguir descreve a[n]densidade das estrelas no espaço externo?[n][f 1 3 65535][w][e]

[sel SEL_071_0_0 top]
[s]3 sementes de gergelim na sua mão.[e]
[s]3 melões no Atlântico.[e]
[s]3 abelhas em toda a Europa.[f 2 7 0 0 25 1][e]

[msg MSG_072_0_0 [Ms. Usami]]
[s][bup 0 305 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37270 65535 0]Este é o segundo dia de seus exames.[n]Por favor, comece.[n][f 1 3 65535][w][e]

[msg MSG_073_0_0 [English]]
[s][vp 8 0 0 0 65535 0]Qual traje de cartas representa o Santo[n]Graal?[n][f 1 3 65535][w][e]

[sel SEL_074_0_0 top]
[s]Corações.[f 2 7 0 0 25 1][e]
[s]Diamantes.[e]
[s]Clubes.[e]
[s]Espadas.[e]

[msg MSG_075_0_0 [Social Studies]]
[s][vp 8 0 0 0 65535 0]De acordo com a lei judicial japonesa, o que[n]é possível até uma criança em tribunal?[n][f 1 3 65535][w][e]

[sel SEL_076_0_0 top]
[s]Defender.[e]
[s]Processar.[e]
[s]Comparecer.[f 2 7 0 0 25 1][e]

[msg MSG_077_0_0 [Ms. Chouno]]
[s][bup 0 304 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37200 65535 0]Vocês estão todos prontos? Você pode começar.[n][f 1 3 65535][w][e]

[msg MSG_078_0_0 [History]]
[s][vp 8 0 0 0 65535 0]Como Johanna disse que se tornou uma papa[n]feminina na Europa medieval?[n][f 1 3 65535][w][e]

[sel SEL_079_0_0 top]
[s]Através de pura habilidade.[e]
[s]Homens e mulheres tinham direitos iguais.[e]
[s]Ela se vestia como homem.[f 2 7 0 0 25 1][e]

[msg MSG_080_0_0 [Japanese]]
[s][vp 8 0 0 0 65535 0]Qual é o nome da utopia fictícia de Kenji[n]Miyazawa?[n][f 1 3 65535][w][e]

[sel SEL_081_0_0 top]
[s]Costa do Plioceno.[e]
[s]Moria.[e]
[s]Tokio.[e]
[s]Ihatov.[f 2 7 0 0 25 1][e]

[msg MSG_082_0_0 [Ms. Usami]]
[s][bup 0 305 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37253 65535 0]Este é o terceiro dia de seus exames.[n]Por favor, comece.[n][f 1 3 65535][w][e]

[msg MSG_083_0_0 [English]]
[s][vp 8 0 0 0 65535 0]Qual é o termo inglês para um período anual[n]de aumento da precipitação?[n][f 1 3 65535][w][e]

[sel SEL_084_0_0 top]
[s]Temporada de tempestades.[e]
[s]A estação chuvosa.[f 2 7 0 0 25 1][e]
[s]Estação da colheita.[e]

[msg MSG_085_0_0 [Social Studies]]
[s][vp 8 0 0 0 65535 0]Qual personagem original de Sir Arthur Conan[n]Doyle apareceu em um romance de Maurice[n]LeBlanc?[n][f 1 3 65535][w][e]

[sel SEL_086_0_0 top]
[s]Watson.[e]
[s]Dupin.[e]
[s]Holmes.[f 2 7 0 0 25 1][e]
[s]Poirot.[e]

[msg MSG_999_1_0 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Ei, não aprendemos isso na aula...[n][f 1 3 65535][w][e]

[msg MSG_999_2_0 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 5 0 0][f 4 10 65535 0 0]Também não aprendemos este...[n][f 1 3 65535][w][e]

[msg MSG_999_3_0 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 1 0 0][f 4 10 65535 0 0]Ah, sim, este é um que você adivinhou, não[n]é? Você está realmente em um rolo![n][f 1 3 65535][w][e]

