[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2198 65535 0]Estou interessado em[n]ciência psi-cognitiva, o mesmo campo de[n]pesquisa da mãe de Futaba...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Duvido que encontremos informações públicas, mas[n]talvez sejam citadas em alguma revista acadêmica[n]antiga.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 0 8 2 1 2217]Vamos tentar encontrar um.[clr 27][e]
[s]As chances são mínimas...[e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 3 5 6]Obrigada. Eu realmente espero[n]encontrar algo...[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu quero aprender o máximo que puder[n]ciência psicocognitiva enquanto[n]Futaba recupera sua força.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Entendi. Talvez seja realmente[n]um esforço inútil...[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas eu quero aprender o máximo que puder[n]ciência psicocognitiva enquanto[n]Futaba recupera sua força.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se ao menos pudéssemos descobrir[n]mais. Talvez possamos resolver[n]o mistério do Metaverso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Seria ainda mais[n]fácil para nós atravessarmos.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Hifumi]]
[s][bup 0 106 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 18001 65535 0]...Oh.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hum, oi.[n][f 1 3 65535][w][e]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Erm... Adeus.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, espere![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por acaso você queria dizer algo a ele?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, não, nada de especial...[n]Só fiquei surpreso em vê-lo aqui.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não era minha intenção[n]perturbá-lo...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2156 65535 0]Não há necessidade de ser tão[n]legal. Ele estava apenas me ajudando[n]com os livros.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Ela é sua amiga?[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s]Ele é meu mestre shogi.[e]
[s]Ela é minha companheira guerreira.[e]

[msg MSG_011_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh...Mestre isso é um exagero...[n]Vamos apenas brincar juntos[n]a shogi...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Hifumi]]
[s][bup 0 106 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]G-Guerreiro...? Vamos[n]jogar shogi juntos...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ela é aquela shogi pro[n]que você mencionou?[n]A estrategista especialista?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2135 65535 0]Admito que só conheço as regras,[n]mas fico intrigado com a forma de pensar[n]de um jogador profissional.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Isso é... um livro[n]sobre táticas de shogi?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh sim. Às vezes eu venho aqui[n]para comprar alguns velhos[n]livros estratégicos sobre a disciplina.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Com licença se ouso...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você poderia me ensinar alguma[n]estratégia? Acho que pode[n]ser útil para o futuro.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Hifumi]]
[s][bup 0 106 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh? Claro, se você se importa.[n][f 1 3 65535][w][e]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, shogi...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Para atacar, você deve ser criativo[n]na sua abordagem e sacrificar[n]peças sem remorso...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então, o plano é fazer[n]o adversário focar nas peças sacrificadas,[n]e depois partir para o contra-ataque?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 18123 65535 0]Sim... Ei, você tem um[n]talento natural.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Outra estratégia é usar[n]peças esquisitas para atrair o oponente[n]para o seu lado do tabuleiro.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hmm, eu entendo. Dessa forma[n]você pode cercá-lo e...[n][f 1 3 65535][w][e]

[sel SEL_020_5_0 top]
[s][f 0 8 2 1 2217]Uma noção muito útil.[clr 27][e]
[s][f 0 8 2 1 2217]Você parece se dar bem.[clr 27][e]

[msg MSG_021_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 3 10 6][f 5 13 18 10 1006]Oh, desculpe. Ele estava dizendo[n]coisas tão interessantes que eu[n]perdi a noção do tempo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Falaremos com você mais tarde.[n]Você poderia dar uma olhada no livro[n]que discutimos anteriormente?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Makoto]]
[s][vp 8 0 0 0 65535 0]Nada promissor, né...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 2049 65535 0]Acho que devemos ir[n]para casa hoje.[n][f 1 3 65535][w][e]

