[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 3 4 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Não acredito que não conseguimos encontrar[n]uma única tabela...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Pelo menos podemos tentar pegar um bolo[n]aqui, mas... mesmo esse lugar está tão[n]lotado.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Vamos ter fé.[e]
[s]Não há mal em tentar.[e]
[s]Estou bem se estou com você.[e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Sim. Você tem razão.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Vamos indo.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Verdadeiro. Não faz sentido aumentar nossas[n]esperanças, mas vamos continuar tentando.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 6 4 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Th-obrigado você. Eu me sinto da mesma[n]forma...[n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [Makoto]]
[s][bup 0 6 7 4 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Espere, foco! Temos um bolo para comprar![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Vamos indo.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][bup 0 6 3 4 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Não parece que eles têm nada...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Ah bem. Talvez seja melhor encontrar outro[n]lugar.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Cheerful Female Staff]]
[s][f 4 10 65535 0 0][vp 8 0 0 11 8 0]Você não está no mercado de um bolo de[n]Natal, não é?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][bup 0 6 4 4 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]O-oh, hum... nós somos, na verdade.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Cheerful Female Staff]]
[s][f 4 10 65535 0 0][vp 8 0 0 13 8 0]Ah, fantástico...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 8 0]Um de nossos pedidos foi cancelado no último[n]minuto.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][bup 0 6 4 4 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Você está brincando![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Cheerful Female Staff]]
[s][f 4 10 65535 0 0][vp 8 0 0 16 8 0]Eu acho que é sua noite de sorte! Então,[n]você quer comprá-lo?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][bup 0 6 4 4 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Bem... se está realmente bem...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Então sim. Vamos aceitar.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Cheerful Female Staff]]
[s][f 4 10 65535 0 0][vp 8 0 0 19 8 0]É claro! Apenas espere um momento enquanto[n]preparo seu pedido![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Estou honestamente atordoado. Esse tipo de[n]coisa nunca acontece, certo?[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]Vamos chamá-lo de karma.[e]
[s]Suas boas ações valeram a pena.[e]

[msg MSG_017_0_0 [Makoto]]
[s][bup 0 6 1 4 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Certo. Vamos com isso.[n][f 1 3 65535][w][e]

