[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]É muito bom aaaaaa...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]O melhor bolo do mundo![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Ainda não consigo acreditar que[n]eles nos obrigaram a pegá-lo na hora.[n]Belo presente![n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Um presente de quem?[e]
[s]A quem temos que agradecer?[e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Uh, eu não sei.[n]Vamos... Natal em geral?[n][f 1 3 65535][w][e]
[s][bup 0 4 4 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 39 3 100][vp 8 0 0 5 65535 0][f 4 22 0 4 1]Oh, certo! Natal![n]Às vezes eu esqueci...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Tadaaaa! Seu presente![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Eu vi isso enquanto estava[n]fazendo compras outro dia.[n]É o seu estilo, não é?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]E vai ficar cada vez mais frio, então...[n]Vamos! O que você acha? Legal, né?[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Obrigado Ann.[e]
[s]Eu cuidarei disso.[e]

[msg MSG_005_0_0 [Ann]]
[s][bup 0 4 16 4 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Vamos, vamos, se você ficar todo sério[n]vai acabar me fazendo corar...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 0 4 0][vp 8 0 0 10 0 0]...Mh?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ann]]
[s][bup 0 4 0 4 0][vp 8 0 0 11 0 0]......[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]Ann está olhando para mim...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0][f 4 2]... Você tem, uh,[n]uma coisa...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Creme no nariz.[n]Vou tirar.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Hum. É isso![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Não me diga que você não gostou[n]pelo menos um pouco.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Hum...Olha, eu sei que isso[n]parece estranho, mas....[n][f 1 3 65535][w][e]

[msg MSG_012_5_0 [Ann]]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Obrigado.[n]Por se apaixonar por mim.[n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]Eu te amo.[e]
[s]Nós estaremos juntos para sempre.[e]

[msg MSG_014_0_0 [Ann]]
[s][bup 0 4 3 4 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Mas sério...[n]Você roubou minha piada.[n][f 1 3 65535][w][e]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 3 100][vp 8 0 0 19 65535 0]...eu te amo.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ann]]
[s][bup 0 4 4 4 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Oooh...Olha, olha![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Há muito mais neve do que antes, não é?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Que maravilha...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Não me lembro de ter sido tão[n]feliz na minha vida. Parece-me[n]o final de um conto de fadas.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Quero dizer, não é um final realmente,[n]pelo menos eu espero.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ann]]
[s][bup 0 4 3 4 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Mas você sabe o que quero dizer, não é? Quando[n]estou tão feliz, parte de mim[n]se pergunta se isso é verdade.[n][f 1 3 65535][w][e]

[sel SEL_024_0_0 top]
[s]É tudo verdade.[e]
[s]Você tem muita imaginação.[e]

[msg MSG_025_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Você tem razão. Evidentemente[n]não estou acostumado a[n]tal felicidade.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ann]]
[s][bup 0 4 3 4 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Ei, bem... posso[n]ficar fora o quanto quiser esta noite.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Então... eu pensei, bem...[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]Ann e eu passamos[n]tempo juntos...[n][f 1 3 65535][w][e]

