[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ah sim, hoje é Dia dos Namorados.[n]É por isso que[n]tãos casais vieram.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Você não tem nada legal planejado? Quero dizer,[n]você está aqui há quase um ano.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Sabe, na minha época...[n]Ah, sabe que coisas.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Haru]]
[s][bup 0 7 0 6 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]...Boa noite.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Ah, a cafeteria ainda é...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Oooh... Mas você poderia ter me contado.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]O lugar é todo seu.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Aproveite.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Meowhohoh...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Haru]]
[s][bup 0 7 7 6 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]Sinto muito. Você ficará cansado.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Haru]]
[s][bup 0 7 0 6 0][f 4 10 65535 0 0][vp 8 0 0 11 22 0]Eu queria ficar sozinho com você por um tempo...[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Para mim também.[e]
[s]Tudo está bem?[e]
[s]Desculpe, você está preocupado.[e]

[msg MSG_010_0_0 [Haru]]
[s][bup 0 7 1 6 0][f 4 10 65535 0 0][vp 8 0 0 12 22 0]É bom saber...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 22 0]Mas posso falar uma coisa?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Haru]]
[s][bup 0 7 1 6 0][f 4 10 65535 0 0][vp 8 0 0 14 22 0]Eu gostaria de poder dizer que sim, mas...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Haru]]
[s][bup 0 7 1 6 0][f 4 10 65535 0 0][vp 8 0 0 15 22 0]...Acho que não preciso exigir[n]um pedido de desculpas então.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Haru]]
[s][bup 0 7 3 6 0][f 4 10 65535 0 0][vp 8 0 0 16 22 0]Quando percebi o que tinha acontecido,[n]eu estava... morrendo de medo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 22 0]Tive medo de te perder para sempre.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]Desculpe.[e]
[s]Minha culpa.[e]

[msg MSG_015_0_0 [Haru]]
[s][bup 0 7 3 6 0][f 4 10 65535 0 0][vp 8 0 0 18 22 0]...Relaxe.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Haru]]
[s][bup 0 7 1 6 0][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]Enfim...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Haru]]
[s][bup 0 7 1 6 0][f 4 10 65535 0 0][vp 8 0 0 24 22 0]...Aqui. Chocolate. Feito por mim.[n][f 1 3 65535][w][e]

[sel SEL_018_0_0 top]
[s]Obrigada.[e]
[s]Vou comê-los sem exagerar.[e]
[s]Cacau cultivado por você?[e]

[msg MSG_019_0_0 [Haru]]
[s][bup 0 7 1 6 0][f 4 10 65535 0 0][vp 8 0 0 25 22 0]Eheheh, tudo bem.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Haru]]
[s][bup 0 7 6 6 0][f 4 10 65535 0 0][vp 8 0 0 26 22 0]Bom! Sem querer me gabar, mas eles são muito[n]bons. Pelo menos eu acho...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Haru]]
[s][bup 0 7 1 6 0][f 4 10 65535 0 0][vp 8 0 0 27 22 0]Bem, eu não cheguei tão longe...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 28 22 0]Mas isso não é uma má ideia. Talvez[n]ano que vem eu plante cacau![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Haru]]
[s][bup 0 7 0 6 0][f 4 10 65535 0 0][vp 8 0 0 29 22 0]Eu sei que é tarde demais para perguntar, mas...[n]Estamos de volta, certo? Estamos em nossa[n]realidade?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Haru]]
[s][bup 0 7 0 6 0][f 4 10 65535 0 0][vp 8 0 0 31 22 0]Ah, quase esqueci...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 32 22 0]Recebi uma oferta não oficial[n]da Okumura Foods.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 33 22 0]Ah, mas não desisti do sonho[n]do pequeno café.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 34 22 0]Mas acho que devo trabalhar primeiro como[n]empregado. Isso me ajudaria a aprender lições[n]importantes.[n][f 1 3 65535][w][e]

[sel SEL_024_0_0 top]
[s]Eu vou apoiar você.[e]
[s]Eu sei que você consegue.[e]

[msg MSG_025_0_0 [Haru]]
[s][bup 0 7 1 6 0][f 4 10 65535 0 0][vp 8 0 0 35 22 0]Obrigado![n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Haru]]
[s][bup 0 7 7 6 0][f 4 10 65535 0 0][vp 8 0 0 36 22 0]Posso sentar ao seu lado...?[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Haru]]
[s][bup 0 7 6 6 0][f 4 10 65535 0 0][vp 8 0 0 37 22 0]Desculpe se fui muito direto...[n]É tão relaxante.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Haru]]
[s][bup 0 7 3 6 0][f 4 10 65535 0 0][vp 8 0 0 38 22 0]Mês que vem você...[n]vai pra casa, né?[n][f 1 3 65535][w][e]

[sel SEL_029_0_0 top]
[s]Você vai sentir minha falta?[e]
[s]Você está com raiva?[e]

[msg MSG_030_0_0 [Haru]]
[s][bup 0 7 3 6 0][f 4 10 65535 0 0][vp 8 0 0 39 22 0]Claro que sim.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Haru]]
[s][bup 0 7 3 6 0][f 4 10 65535 0 0][vp 8 0 0 40 22 0]Estou mais triste do que com raiva.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Haru]]
[s][bup 0 7 0 6 0][f 4 10 65535 0 0][vp 8 0 0 41 22 0]...Mas não posso impedir você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 42 22 0]Decidimos superar isso[n]coisa. Temos que dar tudo de nós.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Haru]]
[s][bup 0 7 0 6 0][f 4 10 65535 0 0][vp 8 0 0 43 22 0]Eu estava pensando...[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Haru]]
[s][bup 0 7 0 6 0][f 4 10 65535 0 0][vp 8 0 0 44 22 0]Quando entrei para os[n]Phantom Thieves, queria ajudar[n]pessoas necessitadas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 45 22 0]Eu me imaginei como as heroínas[n]da minha infância.[n]Um campeão da justiça.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Haru]]
[s][bup 0 7 1 6 0][f 4 10 65535 0 0][vp 8 0 0 46 22 0]Mas encontrei muito mais...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 47 22 0]Agora há alguém com quem me importo.[n]Eu faria qualquer coisa pela[n]felicidade dessa pessoa.[n][f 1 3 65535][w][e]
[s][bup 0 7 6 6 0][f 4 10 65535 0 0][vp 8 0 0 48 22 0]E não por justiça, ou sabe-se lá que ideal. Isso[n]é o que eu quero.[n][f 1 3 65535][w][e]

[sel SEL_036_0_0 top]
[s]Quem?[e]
[s]Você está falando sobre...?[e]

[msg MSG_037_0_0 [Haru]]
[s][bup 0 7 6 6 0][f 4 10 65535 0 0][vp 8 0 0 49 22 0]Ele Ele. Quem será?[n][f 1 3 65535][w][e]

[msg MND_038_0_0]
[s][vp 8 0 0 0 65535 0]Passei uma noite[n]romântica com Haru...[n][f 1 3 65535][w][e]

