[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ah sim, hoje é Dia dos Namorados.[n]É por isso que[n]tãos casais vieram.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Você não tem nada legal planejado? Quero dizer,[n]você está aqui há quase um ano.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Sabe, na minha época...[n]Ah, sabe que coisas.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 0 6 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Olá![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 0 6 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Você tem um minuto?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Oooh... Mas você poderia ter me contado.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]O lugar é todo seu.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Aproveite.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]*suspiro*[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ann]]
[s][bup 0 4 1 6 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Boa noite...[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Sentar-se.[e]
[s]Vou fazer um café para você.[e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 6 6 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]...Obrigado.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 1 8 0][f 4 10 65535 0 0][vp 8 0 0 12 23 0]Tudo bem, é hora da[n]fase dois da[n]festa de retorno![n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]Não faria mal nenhum se divertir.[e]
[s]Vamos entrar nisso.[e]
[s]Fazemos coisas grandes.[e]

[msg MSG_013_0_0 [Ann]]
[s][bup 0 4 1 8 0][f 4 10 65535 0 0][vp 8 0 0 13 23 0]Sim! Faz uma vida desde que[n]temos tempo para nós dois.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 8 0][f 4 10 65535 0 0][f 4 24 0 23 6 59 5 100][vp 8 0 0 14 23 0]Ah, mas primeiro...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ann]]
[s][bup 0 4 3 8 0][f 4 10 65535 0 0][vp 8 0 0 15 23 0]Olha como ele é legal.[n]Deveríamos comemorar, certo?[n][f 1 3 65535][w][e]
[s][bup 0 4 0 8 0][f 4 10 65535 0 0][f 4 24 0 23 6 59 5 100][vp 8 0 0 16 23 0]Ah, mas primeiro...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ann]]
[s][bup 0 4 1 8 0][f 4 10 65535 0 0][vp 8 0 0 17 23 0]Não se preocupe, eu cuido disso![n][f 1 3 65535][w][e]
[s][bup 0 4 0 8 0][f 4 10 65535 0 0][f 4 24 0 23 6 59 5 100][vp 8 0 0 18 23 0]Mas espere, primeiro...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ann]]
[s][bup 0 4 3 8 0][f 4 10 65535 0 0][vp 8 0 0 19 23 0]É um absurdo você ter se entregado.[n]Foi como se eu tivesse desaparecido...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 23 0]Você me assustou pra caralho, sabia?[n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s]Desculpe.[e]
[s]Minha culpa.[e]

[msg MSG_018_0_0 [Ann]]
[s][bup 0 4 1 8 0][f 4 10 65535 0 0][vp 8 0 0 21 23 0]...Ok, tudo bem. Eu te perdôo.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 8 0][f 4 10 65535 0 0][f 4 24 0 23 6 59 5 100][vp 8 0 0 23 23 0]Mas a partir de agora vamos abordar[n]essas coisas juntos, ok? Não[n]importa o tamanho deles.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ann]]
[s][bup 0 4 1 8 0][f 4 10 65535 0 0][vp 8 0 0 24 23 0]Ok! Agora chega de conversa séria![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 25 23 0]Aqui está o que você estava[n]esperando...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ann]]
[s][bup 0 4 1 8 0][f 4 10 65535 0 0][vp 8 0 0 26 23 0]Hora do chocolate![n]Estava ansioso, né?[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s]Na verdade eu estava.[e]
[s]Uma verdadeira surpresa.[e]
[s]Feito à mão?[e]

[msg MSG_022_0_0 [Ann]]
[s][bup 0 4 1 8 0][f 4 10 65535 0 0][vp 8 0 0 27 23 0]Sério? Espero que tudo seja[n]como você imaginou.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ann]]
[s][bup 0 4 1 8 0][f 4 10 65535 0 0][vp 8 0 0 28 23 0]A sério? Como você pode ser[n]tão esquecido![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ann]]
[s][bup 0 4 0 8 0][f 4 10 65535 0 0][vp 8 0 0 29 23 0]O que é, você esperava que fosse?[n][f 1 3 65535][w][e]
[s][bup 0 4 1 8 0][f 4 10 65535 0 0][f 4 24 0 23 6 42 3 100][vp 8 0 0 30 23 0]Bem, quem sabe ano que vem.[n]Vou prepará-lo com muito amor.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ann]]
[s][bup 0 4 3 8 0][f 4 10 65535 0 0][vp 8 0 0 31 23 0]...Enfim, não que eu tenha pensado demais, mas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 32 23 0]Está tudo bem, certo? Tudo[n]está de volta ao normal?[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ann]]
[s][bup 0 4 0 8 0][f 4 10 65535 0 0][vp 8 0 0 34 23 0]Ei, uhm...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 35 23 0]Eu tenho trabalhado muito[n]como modelo ultimamente. Às vezes[n]eu também falo com Shiho.[n][f 1 3 65535][w][e]

[sel SEL_027_0_0 top]
[s]Eu vou apoiar você.[e]
[s]Eu sei que você consegue.[e]

[msg MSG_028_0_0 [Ann]]
[s][bup 0 4 1 8 0][f 4 10 65535 0 0][vp 8 0 0 37 23 0]Isso é realmente encorajador.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Ann]]
[s][bup 0 4 0 8 0][f 4 10 65535 0 0][vp 8 0 0 38 23 0]Então, posso sentar ao seu lado?[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Ann]]
[s][bup 0 4 3 8 0][f 4 10 65535 0 0][vp 8 0 0 39 23 0]Mês que vem[n]você vai pra casa, né?[n][f 1 3 65535][w][e]

[sel SEL_031_0_0 top]
[s]Você vai sentir minha falta?[e]
[s]Relacionamento a distância?[e]

[msg MSG_032_0_0 [Ann]]
[s][bup 0 4 3 8 0][f 4 10 65535 0 0][vp 8 0 0 40 23 0]Você não sabe quanto. Será[n]um funeral de verdade.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Ann]]
[s][bup 0 4 3 8 0][f 4 10 65535 0 0][vp 8 0 0 41 23 0]Ugh, tããão. Vai ser[n]difícil se acostumar.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Ann]]
[s][bup 0 4 3 8 0][f 4 10 65535 0 0][vp 8 0 0 43 23 0]Mesmo se estivermos distantes...[n]nossos corações permanecerão[n]mais próximos do que nunca.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Ann]]
[s][bup 0 4 0 8 0][f 4 10 65535 0 0][vp 8 0 0 44 23 0]Ei...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 45 23 0]No começo, eu estava apenas pensando em[n]impedir que os bandidos fizessem[n]mal. Como fizeram em Shiho.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Ann]]
[s][bup 0 4 1 8 0][f 4 10 65535 0 0][vp 8 0 0 46 23 0]Mas agora, bem... Talvez eu tenha[n]outras coisas em que pensar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 47 23 0]Eu tenho alguém para salvar. Ou para[n]fazer feliz, no mínimo.[n]Não como Panther, mas... como Ann.[n][f 1 3 65535][w][e]

[sel SEL_038_0_0 top]
[s]Quem?[e]
[s]Você está falando sobre...?[e]

[msg MSG_039_0_0 [Ann]]
[s][bup 0 4 6 8 0][f 4 10 65535 0 0][vp 8 0 0 48 23 0]Tente adivinhar.[n][f 1 3 65535][w][e]

[msg MND_040_0_0]
[s][vp 8 0 0 0 65535 0]Passei uma[n]noite romântica com Ann...[n][f 1 3 65535][w][e]

