[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ah sim, hoje é Dia dos Namorados.[n]É por isso que[n]tãos casais vieram.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Você não tem nada legal planejado? Quero dizer,[n]você está aqui há quase um ano.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Se você soubesse na minha época[n]quantos...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Hifumi]]
[s][bup 0 106 0 6 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Com licença...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Oooh... Mas você poderia ter me contado.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Aqui o lugar é todo seu.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Aproveite.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Hifumi]]
[s][bup 0 106 1 6 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Boa noite.[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]Sentar-se.[e]
[s]Vou fazer um café para você.[e]

[msg MSG_008_0_0 [Hifumi]]
[s][bup 0 106 1 6 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Muito obrigado.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Hifumi]]
[s][bup 0 106 2 6 0][f 4 10 65535 0 0][vp 8 0 0 10 22 0]Já faz um tempo...[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s]Eu acho que sim.[e]
[s]Senti a sua falta.[e]

[msg MSG_011_0_0 [Hifumi]]
[s][bup 0 106 3 6 0][f 4 10 65535 0 0][vp 8 0 0 11 22 0]Fiquei preocupada, sabe...?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Hifumi]]
[s][bup 0 106 7 6 0][f 4 10 65535 0 0][vp 8 0 0 14 22 0]P-Isso não tem nada a ver.[n][f 1 3 65535][w][e]
[s][bup 0 106 3 6 0][f 4 10 65535 0 0][f 4 24 0 22 6 38 5 100][vp 8 0 0 15 22 0]Eu fiquei com muito medo, sabe...?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Hifumi]]
[s][bup 0 106 5 6 0][f 4 10 65535 0 0][vp 8 0 0 16 22 0]Você é um absurdo.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Hifumi]]
[s][bup 0 106 4 6 0][f 4 10 65535 0 0][vp 8 0 0 17 22 0]Oh, não... eu não estou tentando[n]dar um sermão em você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 22 0]A razão de eu estar aqui é...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Hifumi]]
[s][bup 0 106 6 6 0][f 4 10 65535 0 0][vp 8 0 0 19 22 0]Eu queria te dar isso. Não[n]veio muito bem, mas...[n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s]É chocolate?[e]
[s]Eu estou tão feliz.[e]
[s]Eu vou aproveitar todos eles.[e]

[msg MSG_018_0_0 [Hifumi]]
[s][bup 0 106 1 6 0][f 4 10 65535 0 0][vp 8 0 0 20 22 0]Exatamente. É gostoso,[n]com certeza.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Hifumi]]
[s][bup 0 106 6 6 0][f 4 10 65535 0 0][vp 8 0 0 21 22 0]Sério? Talvez fizesse sentido[n]passar muito tempo na cozinha.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Hifumi]]
[s][bup 0 106 6 6 0][f 4 10 65535 0 0][vp 8 0 0 22 22 0]Estou feliz.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 22 0]Apenas... não espere muito do sabor.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Hifumi]]
[s][bup 0 106 1 6 0][f 4 10 65535 0 0][vp 8 0 0 24 22 0]...Enquanto eu vinha pra cá eu ainda tinha[n]ansiedade, mas agora tá melhor. Eu sinto[n]que posso respirar novamente.[n][f 1 3 65535][w][e]

[sel SEL_022_0_0 top]
[s]E você?[e]
[s]Como você foi?[e]

[msg MSG_023_0_0 [Hifumi]]
[s][bup 0 106 0 6 0][f 4 10 65535 0 0][vp 8 0 0 25 22 0]Não sei como dizer...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 22 0]Eles ainda me chamam de "Princesa Falsa".[n][f 1 3 65535][w][e]
[s][bup 0 106 1 6 0][f 4 10 65535 0 0][vp 8 0 0 27 22 0][f 4 24 0 22 6 36 5 100]Mas, honestamente, prefiro ser[n]tratado assim do que como um ídolo.[n]É uma libertação.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Hifumi]]
[s][bup 0 106 1 6 0][f 4 10 65535 0 0][vp 8 0 0 28 22 0]Posso me concentrar no shogi.[n]A partir de agora vou lutar para ser[n]o melhor, profissional ou não.[n][f 1 3 65535][w][e]
[s][bup 0 106 6 6 0][f 4 10 65535 0 0][vp 8 0 0 29 22 0]E... espero ainda ter você[n]ao meu lado.[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]Eu deveria dizer a Hifumi[n]que estou indo para casa...[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Hifumi]]
[s][bup 0 106 4 6 0][f 4 10 65535 0 0][vp 8 0 0 30 22 0]Hum... algo está errado?[n][f 1 3 65535][w][e]

[sel SEL_027_0_0 top]
[s]Vou voltar para minha cidade.[e]
[s]Eu vou para casa.[e]

[msg MSG_028_0_0 [Hifumi]]
[s][bup 0 106 3 6 0][f 4 10 65535 0 0][vp 8 0 0 31 22 0]Ah, é isso...[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Hifumi]]
[s][bup 0 106 0 6 0][f 4 10 65535 0 0][vp 8 0 0 32 22 0]Posso sentar aqui com você?[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Hifumi]]
[s][bup 0 106 3 6 0][f 4 10 65535 0 0][vp 8 0 0 33 22 0]Portanto, nossas horas estão contadas.[n]Em breve, não poderemos mais ficar assim.[n][f 1 3 65535][w][e]

[sel SEL_031_0_0 top]
[s]Desculpe pela notícia repentina.[e]
[s]Você vai se juntar a mim?[e]

[msg MSG_032_0_0 [Hifumi]]
[s][bup 0 106 3 6 0][f 4 10 65535 0 0][vp 8 0 0 34 22 0]Era assim que deveria acontecer. É um absurdo[n]que você tenha que sair agora que[n]estamos juntos de novo.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Hifumi]]
[s][bup 0 106 1 6 0][f 4 10 65535 0 0][vp 8 0 0 35 22 0]Sem pensar duas vezes.[n][f 1 3 65535][w][e]
[s][bup 0 106 0 6 0][f 4 10 65535 0 0][f 4 24 0 22 6 59 5 100][vp 8 0 0 36 22 0]Infelizmente, duvido que[n]seja tão simples.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Hifumi]]
[s][bup 0 106 0 6 0][f 4 10 65535 0 0][vp 8 0 0 37 22 0]As pessoas mudam, eu acho...[n]É isso aí.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 38 22 0]Nós dois mudamos.[n][f 1 3 65535][w][e]

[sel SEL_035_0_0 top]
[s]O que você quer dizer?[e]
[s]Uma mudança?[e]

[msg MSG_036_0_0 [Hifumi]]
[s][bup 0 106 0 6 0][f 4 10 65535 0 0][vp 8 0 0 39 22 0]Eu sinto algo diferente em você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 40 22 0]É difícil de explicar. Algo[n]sobre o seu... modo de tomar?[n][f 1 3 65535][w][e]
[s][bup 0 106 4 6 0][f 4 10 65535 0 0][vp 8 0 0 41 22 0][f 4 24 0 22 6 39 3 100]Bem... seja o que for,[n]parece uma mudança positiva.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Hifumi]]
[s][bup 0 106 0 6 0][f 4 10 65535 0 0][vp 8 0 0 42 22 0]Eu também mudei, eu acho.[n][f 1 3 65535][w][e]
[s][bup 0 106 3 6 0][f 4 10 65535 0 0][f 4 24 0 22 6 38 6 100][vp 8 0 0 43 22 0]Antes de te conhecer, nunca[n]me importei de ficar sozinho.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 44 22 0]Mas houve uma[n]mudança ainda mais drástica.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Hifumi]]
[s][bup 0 106 6 6 0][f 4 10 65535 0 0][vp 8 0 0 45 22 0]Agora eu sei como é[n]apaixonar-se...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 46 22 0]Ser dedicado a uma pessoa, com[n]mente e coração, a ponto[n]de fazer qualquer coisa por ela.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 47 22 0]Nunca experimentei nada parecido.[n][f 1 3 65535][w][e]

[sel SEL_039_0_0 top]
[s]É o mesmo para mim.[e]
[s]Você está dizendo que...?[e]

[msg MSG_040_0_0 [Hifumi]]
[s][bup 0 106 6 6 0][f 4 10 65535 0 0][vp 8 0 0 48 22 0]Quero dizer, tenho intenções sérias com você. E[n]eu não vou olhar para trás...[n][f 1 3 65535][w][e]

[msg MND_041_0_0]
[s][vp 8 0 0 0 65535 0]Passei uma noite[n]romântica com Hifumi...[n][f 1 3 65535][w][e]

