[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Oh, [f 4 2].[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Ótimo momento. Eu estava indo para a sua[n]sala de aula.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Aqui. Pegue isso.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]É chocolate. Pense nisso como um sinal de[n]agradecimento por tudo que você faz por nós.[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Obrigado.[e]
[s]Eu certamente reembolso você.[e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Não se preocupe com isso. Não precisa ser um[n]grande negócio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Vejo você de novo em breve, ok?[n][f 1 3 65535][w][e]

