[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Eu me encontrei com Haru no aquário...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 1 4 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Temos um grande tanque de peixes no trabalho[n]também...[n]Mas há um tipo diferente de beleza em tudo[n]isso.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Haru]]
[s][bup 0 7 1 4 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Eu já vi algumas datas de aquário em filmes[n]de romance. Sempre parecia um passeio tão[n]adorável.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 0 4 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Na época, um relacionamento normal parecia[n]além dos meus meios. Eu desisti de sempre[n]experimentar...[n][f 1 3 65535][w][e]
[s][bup 0 7 1 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 3 100][vp 8 0 0 4 65535 0]Mas suponho que isso significa que você fez[n]outro dos meus sonhos se tornar realidade.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haru]]
[s][bup 0 7 0 4 0][vp 8 0 0 5 0 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Tudo isso foi uma tentativa de devolver meus[n]afetos do Dia dos Namorados?[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]É claro.[e]
[s]Está correto.[e]

[msg MSG_006_0_0 [Haru]]
[s][bup 0 7 1 4 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Eu realmente não esperava nada em troca,[n]mas... estou feliz por você ter feito tudo[n]isso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]...Obrigado.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Haru]]
[s][bup 0 7 0 4 0][vp 8 0 0 9 0 0]......[n][f 1 3 65535][w][e]
[s][bup 0 7 1 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][vp 8 0 0 10 65535 0]Você me convidou para sair porque é o dia[n]branco?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]É claro.[e]
[s]Está correto.[e]

[msg MSG_009_0_0 [Haru]]
[s][bup 0 7 1 4 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Eu vejo! Obrigado Senhor...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Tivemos que passar o dia dos namorados,[n]então... eu estava preocupado conosco.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Mas uma vez que recebi seu convite, tudo[n]isso derreteu.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Haru]]
[s][bup 0 7 0 4 0][vp 8 0 0 14 0 0]......[n][f 1 3 65535][w][e]
[s][bup 0 7 1 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][vp 8 0 0 15 65535 0]Eu não acho que isso se destina a uma data[n]para o dia branco?[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]É claro.[e]
[s]Sim.[e]

[msg MSG_012_0_0 [Haru]]
[s][bup 0 7 1 4 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Isso não precisa ser algum tipo de[n]penitência para você, você sabe.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 6 36 3 100][vp 8 0 0 17 65535 0]E você me convidou para sair hoje, então...[n]O passado é passado.[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Haru parece satisfeito...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Haru]]
[s][bup 0 7 1 4 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Suponho que já vimos tudo agora.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Bem, temos algum tempo restante...[n]Vamos conseguir algo para comer antes de[n]irmos para casa?[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]Eu já tenho um conjunto de reservas.[e]
[s]Eu tenho um lugar em mente.[e]

[msg MSG_016_0_0 [Haru]]
[s][bup 0 7 4 4 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]O que? Oh, obrigado...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Haru]]
[s][bup 0 7 1 4 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Nesse caso, lidere o caminho.[n][f 1 3 65535][w][e]

