[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 4 4 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Este lugar é louco...[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Você gosta disso?[e]
[s]Esta é a minha primeira vez aqui.[e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 3 4 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Estou tão nervoso agora, não posso nem[n]dizer...[n][f 1 3 65535][w][e]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][vp 8 0 0 3 65535 0]Mas eu sei que estou feliz por estar aqui.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Oh sério? E aqui estava eu pensando que você[n]era regular.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]... de alguma forma eu duvido disso.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Mas isso é muito mais intenso do que eu[n]esperava.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Você realmente pensou nisso, hein?[n]Eu amo um cara que pode pensar à frente![n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Você está me fazendo corar.[e]
[s]Obrigado.[e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Sim.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 59 5 100][vp 8 0 0 9 65535 0]Oh, desculpe, me dê um segundo.[n][f 1 3 65535][w][e]

[msg MND_007_0_0]
[s][vp 8 0 0 0 65535 0]Quando devo dar o presente a ela?[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]○○○ is calling me...[n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]Eu não posso responder isso agora...![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Alguém ligando?[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]Não é grande coisa.[e]
[s]Não se preocupe com isso.[e]

[msg MSG_012_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]...Certo.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Ok, tudo se sente![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Announcer]]
[s][vp 8 0 0 13 65535 0]Senhoras e senhores, obrigado por se[n]juntarem a nós neste dia especial.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 14 65535 0]Desejamos a todos uma noite inesquecível,[n]com um último toque final de nós...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ann]]
[s][bup 0 4 14 4 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]O que? Aguentar...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ann]]
[s][bup 0 4 4 4 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]É tão bonito...[n][f 1 3 65535][w][e]

[sel SEL_018_0_0 top]
[s]Isto é para você.[e]
[s]Eu quero que você tenha isso.[e]

[msg MSG_019_0_0 [Ann]]
[s][bup 0 4 4 4 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Isto é para mim?[n][f 1 3 65535][w][e]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 5 100][vp 8 0 0 18 65535 0]Obrigado...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ann]]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]...Uau. O presente perfeito, com o tempo[n]perfeito.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Parece que estou em um filme...[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s]Como você está se sentindo?[e]
[s]Você prefere presentes comestíveis?[e]
[s]Surpresa.[e]

[msg MSG_022_0_0 [Ann]]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Insanamente feliz! Duh![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Oh, totalmente. Essa data teria sido[n]perfeita, mas você não me trouxe um bolo.[n][f 1 3 65535][w][e]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 5 100][vp 8 0 0 23 65535 0]Sério, porém, estou genuinamente,[n]insanamente feliz... obrigado.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ann]]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]... Oh, você está bem.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Não acredito que você foi a todo esse[n]problema. Mas quando penso sobre isso, é[n]uma coisa tão 'você' a se fazer.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Desde o dia em que te conheci...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Você sempre esteve tão focado no que pode[n]fazer por todos ao seu redor.[n]Sempre colocando outras pessoas em primeiro[n]lugar.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Eu realmente admiro isso por você. Talvez um[n]dia eu possa ser assim eu mesmo.[n][f 1 3 65535][w][e]

[sel SEL_027_0_0 top]
[s]Tenho certeza que você pode fazer isso.[e]
[s]Estou ansioso para isso.[e]

[msg MSG_028_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]...Obrigado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Vou colocar o trabalho. E um dia você vai[n]pensar: "Cara, estou tão feliz que Ann está[n]na minha vida!" [n][f 1 3 65535][w][e]

[sel SEL_029_0_0 top]
[s]Eu já penso assim.[e]
[s]Estou pensando nisso agora.[e]

[msg MSG_030_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Então você vai pensar mais.[n]Vou ter certeza.[n][f 1 3 65535][w][e]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Aconteça o que acontecer, eu quero ficar com[n]você a partir de agora, ok?[n][f 1 3 65535][w][e]

[msg MND_031_0_0]
[s][vp 8 0 0 0 65535 0]Ann e eu passamos algum tempo sozinhos[n]juntos...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]......[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Uma vez tarde, eu a segui de volta para a[n]estação...[n][f 1 3 65535][w][e]

