[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Eu me encontrei com Chihaya no aquário...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Uau...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Minha cidade natal definitivamente tinha[n]peixe, mas eles não estavam nem de longe[n]tão elegantes quanto estes...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Você sabe, Feng Shui diz que a água[n]representa a prosperidade financeira.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Então, talvez estar aqui nos traga uma[n]grande riqueza e fortuna![n][f 1 3 65535][w][e]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 5 100][vp 8 0 0 5 65535 0]... bem, talvez não.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Mas estou passando o tempo todo com você, em[n]um lugar tão bonito...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Devo ter mais sorte do que percebi![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]A propósito, você me convidou porque é dia[n]branco hoje?[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]É claro.[e]
[s]Está correto.[e]

[msg MSG_006_0_0 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Muito obrigado![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Eu-eu vi isso chegando, é claro! Nosso[n]destino me mostrou claramente que você[n]retornaria meus afetos.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]A propósito, você me convidou porque é dia[n]branco hoje?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]É claro.[e]
[s]Está correto.[e]

[msg MSG_009_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Eu-eu sabia disso![n][f 1 3 65535][w][e]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 5 100][vp 8 0 0 13 65535 0]Depois que não conseguimos nos ver no dia[n]dos namorados, fiquei preocupado...[n][f 1 3 65535][w][e]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 3 100][vp 8 0 0 14 65535 0]Suponho que era o destino, afinal![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]A propósito, você me convidou para sair hoje[n]porque é um dia branco?[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]É claro.[e]
[s]Sim.[e]

[msg MSG_012_0_0 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]...Bom. É um primeiro passo sensato para[n]recuperar seu bom karma.[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]... Chihaya parece satisfeito.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Obrigado por me levar para sair hoje.[n]Eu me diverti muito.[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]Eu fiz algumas reservas.[e]
[s]Ainda jantamos.[e]

[msg MSG_016_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Oh! Sério?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Chihaya]]
[s][bup 0 113 6 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Bem... então eu vou deixar isso para você.[n][f 1 3 65535][w][e]

