[msg MSG_000_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, [f 4 1]-san? Algo está errado?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Encontre-me em Shinagawa.[e]
[s]Vamos para Shinagawa.[e]

[msg MSG_002_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Shinagawa? Certo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vou fechar cedo para que eu possa ir.[n][f 1 3 65535][w][e]

[msg MND_003_0_0]
[s][vp 8 0 0 0 65535 0]Eu deveria me preparar para ir para[n]Shinagawa...[n][f 1 3 65535][w][e]

