[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Eu me encontrei com Kawakami no aquário...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Kawakami]]
[s][bup 0 109 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Normalmente não vou a lugares assim.[n]É realmente bom.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Pode ser um bom lugar para parar se o[n]trabalho me deixar muito estressado.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Kawakami]]
[s][bup 0 109 503 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]O-oh, desculpe... eu sei que você não me[n]convidou aqui para que eu pudesse reclamar[n]do trabalho.[n][f 1 3 65535][w][e]
[s][bup 0 109 501 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 3 100][vp 8 0 0 4 65535 0]Hoje deve ser o meu tempo de qualidade com o[n]mestre! Ou algo assim.[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]É tudo para nós.[e]
[s]Podemos vir aqui a qualquer momento.[e]

[msg MSG_004_0_0 [Kawakami]]
[s][bup 0 109 507 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Gah, você é tão injusto... eu não sei como[n]você diz essas linhas com uma cara séria.[n][f 1 3 65535][w][e]
[s][bup 0 109 506 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 3 100][vp 8 0 0 6 65535 0]Eu deveria ser o adulto aqui, mas não posso[n]assumir a liderança...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Kawakami]]
[s][bup 0 109 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Esta é uma data para o dia branco, certo?[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]É claro.[e]
[s]Está correto.[e]

[msg MSG_007_0_0 [Kawakami]]
[s][bup 0 109 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Eu não percebi como... SIILST VOCÊ era.[n]Você é cavalheiresco, é dedicado...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Você realmente dedica um tempo para pensar[n]em mim.[n][f 1 3 65535][w][e]
[s][bup 0 109 501 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 5 100][vp 8 0 0 10 65535 0]... Eu realmente gosto disso em você.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Kawakami]]
[s][bup 0 109 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Isso deve ser uma data para o dia branco?[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]É claro.[e]
[s]Está correto.[e]

[msg MSG_010_0_0 [Kawakami]]
[s][bup 0 109 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Ok, isso é um alívio. Eu não te vi no dia[n]dos namorados, então...[n][f 1 3 65535][w][e]
[s][bup 0 109 501 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 3 100][vp 8 0 0 13 65535 0]Vamos apenas compensar isso hoje![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Kawakami]]
[s][bup 0 109 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Ei. Só de saber, mas isso deve ser um pedido[n]de desculpas?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Para o Dia dos Namorados, quero dizer.[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]É claro.[e]
[s]Sim.[e]

[msg MSG_013_0_0 [Kawakami]]
[s][bup 0 109 501 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Pelo menos você sente pena de tudo.[n]Talvez você seja um bom garoto, afinal.[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0]... Kawakami parece satisfeito.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Kawakami]]
[s][bup 0 109 501 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Ok! Estou totalmente despertado agora.[n]Quer dar uma mordida no nosso caminho de[n]volta?[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]Eu tenho um conjunto de reservas.[e]
[s]Eu tenho um lugar em mente.[e]

[msg MSG_017_0_0 [Kawakami]]
[s][bup 0 109 504 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]O que? Uh, eu não tinha ideia...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Kawakami]]
[s][bup 0 109 501 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]... bem, eu acho que você é o mestre.[n][f 1 3 65535][w][e]

