[msg MSG_000_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sim, Yoshizawa falando.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Encontre-me em Shinagawa.[e]
[s]Vamos para Shinagawa.[e]

[msg MSG_002_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Agora mesmo? Claro, tudo bem![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não tenho prática hoje, então vou ir[n]imediatamente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vejo você lá![n][f 1 3 65535][w][e]

[msg MND_003_0_0]
[s][vp 8 0 0 0 65535 0]Eu deveria me preparar para ir para[n]Shinagawa...[n][f 1 3 65535][w][e]

