[msg MSG_000_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E aí? Há algo errado?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Venha para Shinagawa.[e]
[s]Vamos para Shinagawa.[e]

[msg MSG_002_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Shinagawa? E por quê? Bem, eu acho que[n]essa é uma pergunta estúpida ...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estou no trabalho, mas posso sair mais cedo. Nos[n]vemos lá.[n][f 1 3 65535][w][e]

[msg MND_003_0_0]
[s][vp 8 0 0 0 65535 0]Eu tenho que me preparar para ir para[n]Shinagawa...[n][f 1 3 65535][w][e]

