[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Conheci Futaba no aquário...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][bup 0 8 1 4 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Uau...eles são os peixes mais fotogênicos[n]do mundo![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Uma multidão de pessoas me[n]ansiedade, mas um cardume de peixes é[n]estranhamente fofo![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][bup 0 8 1 4 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Bem, um encontro no aquário?[n]Um grande clássico. Então nós vamos[n]fazer as outras coisas como um casal também.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][bup 0 8 1 4 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]O que é, tenho que dizer em voz alta?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Coisas de casal! Segurando[n]mãos no escuro, ou abraçando[n]a parede...[n][f 1 3 65535][w][e]
[s][bup 0 8 7 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 39 5 100][vp 8 0 0 6 65535 0]...Hum, esqueça.[n]Só de pensar nisso me envergonha.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][bup 0 8 0 4 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Então, você fez isso em troca?[n]Dia dos Namorados, quero dizer.[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Certamente.[e]
[s]Exatamente.[e]

[msg MSG_006_0_0 [Futaba]]
[s][bup 0 8 4 4 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Nossa... como você é maduro.[n][f 1 3 65535][w][e]
[s][bup 0 8 6 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][vp 8 0 0 9 65535 0]Estou... muito, muito feliz.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][bup 0 8 0 4 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Então, é isso que eu penso?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Afinal, é o Dia Branco.[e]
[s]Marcação de dia branco?[e]

[msg MSG_009_0_0 [Futaba]]
[s][bup 0 8 4 4 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]...![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]OK! No Dia dos Namorados[n]nós não nos vimos, então pensei[n]que tinha acabado e...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Futaba]]
[s][bup 0 8 6 4 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]B-Bem, então! Terminamos![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][bup 0 8 0 4 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Então, é isso que eu penso?[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]É para o Dia Branco.[e]
[s]Eu sinto muito.[e]

[msg MSG_013_0_0 [Futaba]]
[s][bup 0 8 2 4 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Bem, isso não vai compensar[n]o que você fez.[n][f 1 3 65535][w][e]
[s][bup 0 8 1 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][vp 8 0 0 16 65535 0]Não totalmente, pelo menos. Mas...[n]você está aqui comigo, então...[n]eu te perdôo.[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0]...Futaba parece feliz.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][bup 0 8 1 4 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]OK, eu diria que completamos[n]cem por cento da área de peixes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Está com fome? Talvez possamos conseguir algo a[n]caminho de casa[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]Eu já reservei.[e]
[s]Eu tenho um lugar em mente.[e]

[msg MSG_017_0_0 [Futaba]]
[s][bup 0 8 4 4 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Oh. Nossa.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Futaba]]
[s][bup 0 8 7 4 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]OK, mostre o caminho.[n][f 1 3 65535][w][e]

