[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]All the members I met up[n]with today do seem happy...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]I should check up on the[n]other members tomorrow...[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Ryuji seemed sincerely happy[n]about being able to run with[n]his fellow track team...[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Ann seemed happy to be[n]with Shiho, who is able to[n]continue playing volleyball...[n][f 1 3 65535][w][e]

[msg MND_003_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke seemed happy about his[n]mother's work, "Sayuri," being[n]recognized as a work of art.[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Makoto seemed happy being[n]able to spend time with both[n]her father and sister...[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Futaba seemed happy being able to[n]spend her daily life with both her mother[n]and Sojiro, who she loves very much...[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Haru seemed happy being able to[n]talk to her father without fear...[n][f 1 3 65535][w][e]

[msg MND_007_0_0]
[s][vp 8 0 0 0 65535 0]...But is this truly how[n]things should be?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]I should check up on the[n]other members tomorrow...[n][f 1 3 65535][w][e]

