[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]You don't need to be here right[n]now, do you? Come on, let's head[n]somewhere else![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]What's wrong? Come on, we should[n]go say goodbye to the others![n][w][e]

[msg CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]This is the guys' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]It's far dirtier than the ones[n]in the classroom building...[n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Don't you know that's the girls'[n]bathroom? You're not supposed[n]to be in there...[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the ladies' restroom...[n][w][e]

[msg MSG_HOKEN_ROOM_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Ugh... Why does the nurse's office have[n]to reek of medicine? It seriously hurts[n]my nose...[n][w][e]

[msg MSG_HOKEN_ROOM]
[s][vp 1 0 0 0 0 0]I can smell the medicine[n]in the nurse's office through[n]the cracked door...[n][w][e]

[msg MSG_KATEIKA_MORU [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Something smells good... I wonder if[n]someone was cooking in there earlier.[n][w][e]

[msg MSG_KATEIKA]
[s][vp 1 0 0 0 0 0]A pleasant aroma is wafting[n]this way. Maybe someone was[n]cooking something earlier.[n][w][e]

[msg MSG_HIHUKU_ROOM_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]That's a lot of sewing machines.[n]It would probably get really loud[n]if they were all on at once.[n][w][e]

[msg MSG_HIHUKU_ROOM]
[s][vp 1 0 0 0 0 0]There are a great many sewing[n]machines on the desks...[n][w][e]

[msg MSG_BUTURI_ROOM_MORU [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Somebody left some lab equipment[n]on the desk... That doesn't sound like[n]proper protocol to me.[n][w][e]

[msg MSG_BUTURI_ROOM]
[s][vp 1 0 0 0 0 0]There's some lab equipment[n]strewn across the desk...[n][w][e]

[msg MSG_Emergency_Door_m [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Hold on, we should use the main[n]entrance if you wanna go outside.[n][w][e]

[msg MSG_Emergency_Door]
[s][vp 1 0 0 0 0 0]There's no reason for me[n]to use the emergency exit...[n][w][e]

[msg MSG_Kateika_Tool [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]These might have sparkled at one point,[n]but they're just old and dull now...[n][w][e]

[msg MND_Kateika_Tool]
[s][vp 1 0 0 0 0 0]They've been used so many times,[n]the sheen has worn off completely...[n][w][e]

[msg MND_E14710100_NG_BldgB1F]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E15010100_NG_BldgB1F [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]I think Sakamoto went up to the[n][clr 2]PE faculty office on the second floor[clr 27]...[n][w][e]

[msg MND_E15010100_NG_BldgB1F]
[s][vp 1 0 0 0 0 0]For now, I better try[n]to get to Ryuji...[n][w][e]

[msg MSG_E65410200_NG_BldgB1F [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Hey, where are you going? Don't you[n]have to chase after that butterfly?[n][w][e]

[msg MSG_E13910100_NG_BldgB1F [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, I said the main entrance![n]He's gonna leave if we don't hurry.[n][w][e]

[msg MSG_E15010100_NG_BldgB1F_2 [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]I think Sakamoto went up to the[n][clr 2]PE faculty office on the second floor[clr 27]...[n][w][e]

[msg MND_E15010100_NG_BldgB1F_2]
[s][vp 1 0 0 0 0 0]For now, I better try[n]to get to Ryuji...[n][w][e]

[msg MSG_E13910100_NG_BldgB1F_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, I said the main entrance![n]He's gonna leave if we don't hurry.[n][w][e]

[msg MSG_E65110100_NG_BldgB1F [Lavenza]]
[s][bup 0 100 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 24008 65535 0]......[n][w][e]

[msg MND_E65110100_NG_BldgB1F]
[s][vp 1 0 0 0 0 0]Not this way...[n][w][e]

[msg MSG_E65410200_NG_BldgB1F_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Hey, where are you going? Don't you[n]have to chase after that butterfly?[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]This is the guys' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]It's far dirtier than the ones[n]in the classroom building...[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]This is the guys' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]It's far dirtier than the ones[n]in the classroom building...[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]This is the guys' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here for now...[n][w][e]

[msg MSG_E13910100_CHK_TOILET [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, what're you doin'!? We gotta hurry[n]and catch up to Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]This is the guys' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]It's far dirtier than the ones[n]in the classroom building...[n][w][e]

[msg MND_E14710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E15010100_CHK_TOILET [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]I think Sakamoto went up to the[n][clr 2]PE faculty office on the second floor[clr 27]...[n][w][e]

[msg MND_E15010100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]For now, I better try[n]to get to Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_TOILET [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1018 0 0]Not now. Isn't the student council room on[n]the [clr 2]third floor of the classroom building[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]I better hurry on my way...[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]This is the guys' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here for now...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]This is the ladies' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]This is the ladies' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]This is the ladies' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]

[msg MSG_E13910100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, what're you doin'!? We gotta hurry[n]and catch up to Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]This is the ladies' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]

[msg MND_E14710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E15010100_CHK_TOILET_2 [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]I think Sakamoto went up to the[n][clr 2]PE faculty office on the second floor[clr 27]...[n][w][e]

[msg MND_E15010100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]For now, I better try[n]to get to Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_TOILET_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]You don't need anything this way, do[n]you? Isn't the student council room on[n]the [clr 2]third floor of the classroom building[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]I better hurry on my way...[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]This is the ladies' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]

[msg MND_E12310100_CHK_HOKENS]
[s][vp 1 0 0 0 0 0]It's the infirmary.[n][w][e]
[s][vp 1 0 0 0 0 0]There's that faint[n]smell of antiseptic...[n][w][e]

[msg MND_E12720100_CHK_HOKENS]
[s][vp 1 0 0 0 0 0]This is the nurse's office.[n][w][e]
[s][vp 1 0 0 0 0 0]There's that faint[n]smell of antiseptic...[n][w][e]

[msg MND_E13710100_CHK_HOKENS]
[s][vp 1 0 0 0 0 0]A student who got injured during[n]the ball game is getting treated here.[n][w][e]
[s][vp 1 0 0 0 0 0]I don't see any students[n]with any major injuries...[n][w][e]

[msg MSG_E13910100_CHK_HOKENS [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, I said the main entrance![n]He's gonna leave if we don't hurry.[n][w][e]

[msg MND_E14130100_CHK_HOKENS]
[s][vp 1 0 0 0 0 0]This is the nurse's office.[n][w][e]
[s][vp 1 0 0 0 0 0]There's that faint[n]smell of antiseptic...[n][w][e]

[msg MND_E14710100_CHK_HOKENS]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E15010100_CHK_HOKENS [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]I think Sakamoto went up to the[n][clr 2]PE faculty office on the second floor[clr 27]...[n][w][e]

[msg MND_E15010100_CHK_HOKENS]
[s][vp 1 0 0 0 0 0]For now, I better try[n]to get to Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_HOKENS [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]This is the nurse's office. Isn't the student[n]council room on the [clr 2]third floor of the[n]classroom building[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_HOKENS]
[s][vp 1 0 0 0 0 0]No use going back...[n][w][e]
[s][vp 1 0 0 0 0 0]I better hurry on my way...[n][w][e]

[msg MND_COMMON_CHK_HOKENSITU]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here...[n][w][e]

[msg MND_E12310100_CHK_KATEIK]
[s][vp 1 0 0 0 0 0]This is the home economics room.[n][w][e]
[s][vp 1 0 0 0 0 0]I can see all sorts of cooking[n]utensils lined up on the shelf...[n][w][e]

[msg MND_E12720100_CHK_KATEIK]
[s][vp 1 0 0 0 0 0]This is the home economics room.[n][w][e]
[s][vp 1 0 0 0 0 0]It smells like they're cooking[n]something. From the aroma, it[n]must be something delicious...[n][w][e]

[msg MND_E13710100_CHK_KATEIK]
[s][vp 1 0 0 0 0 0]This is the home economics room.[n][w][e]
[s][vp 1 0 0 0 0 0]Someone left a burnt[n]pot out in the open...[n][w][e]

[msg MSG_E13910100_CHK_KATEIK [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, I said the main entrance![n]He's gonna leave if we don't hurry.[n][w][e]

[msg MND_E14130100_CHK_KATEIK]
[s][vp 1 0 0 0 0 0]This is the home economics room.[n][w][e]
[s][vp 1 0 0 0 0 0]It smells like they're cooking[n]something. From the aroma, it[n]must be something delicious...[n][w][e]

[msg MND_E14710100_CHK_KATEIK]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E15010100_CHK_KATEIK [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]I think Sakamoto went up to the[n][clr 2]PE faculty office on the second floor[clr 27]...[n][w][e]

[msg MND_E15010100_CHK_KATEIK]
[s][vp 1 0 0 0 0 0]For now, I better try[n]to get to Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_KATEIK [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]This is... the home economics room.[n]Isn't the student council room on the[n][clr 2]third floor of the classroom building[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_KATEIK]
[s][vp 1 0 0 0 0 0]I better hurry on my way...[n][w][e]

[msg MND_COMMON_CHK_KATEIKASI]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here...[n][w][e]

[msg MND_E12310100_CHK_HIFUKU]
[s][vp 1 0 0 0 0 0]This looks like the[n]dressmaking room.[n][w][e]
[s][vp 1 0 0 0 0 0]There are numerous sewing[n]machines all lined up...[n][w][e]

[msg MND_E12720100_CHK_HIFUKU]
[s][vp 1 0 0 0 0 0]This is the sewing room.[n]There are numerous sewing[n]machines all lined up here.[n][w][e]

[msg MND_E13710100_CHK_HIFUKU]
[s][vp 1 0 0 0 0 0]This is the sewing room.[n]There are numerous sewing[n]machines all lined up here.[n][w][e]

[msg MSG_E13910100_CHK_HIFUKU [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, I said the main entrance![n]He's gonna leave if we don't hurry.[n][w][e]

[msg MND_E14130100_CHK_HIFUKU]
[s][vp 1 0 0 0 0 0]This is the sewing room.[n]There are numerous sewing[n]machines all lined up here.[n][w][e]

[msg MND_E14710100_CHK_HIFUKU]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E15010100_CHK_HIFUKU [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]I think Sakamoto went up to the[n][clr 2]PE faculty office on the second floor[clr 27]...[n][w][e]

[msg MND_E15010100_CHK_HIFUKU]
[s][vp 1 0 0 0 0 0]For now, I better[n]try to get to Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_HIFUKU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]This is the sewing room. Isn't the student[n]council room on the [clr 2]third floor of the[n]classroom building[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_HIFUKU]
[s][vp 1 0 0 0 0 0]I better hurry on my way...[n][w][e]

[msg MND_COMMON_CHK_HIFUKUSIT]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here...[n][w][e]

[msg MND_E12310100_CHK_BUTURI]
[s][vp 1 0 0 0 0 0]It's the physics room.[n][w][e]
[s][vp 1 0 0 0 0 0]Someone left all this lab[n]equipment out in the open...[n][w][e]

[msg MND_E12720100_CHK_BUTURI]
[s][vp 1 0 0 0 0 0]This is the physics room.[n]There's a lot of unattended[n]lab equipment in here...[n][w][e]

[msg MND_E13710100_CHK_BUTURI]
[s][vp 1 0 0 0 0 0]This is the physics room.[n]There's a lot of unattended[n]lab equipment in here...[n][w][e]

[msg MSG_E13910100_CHK_BUTURI [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, I said the main entrance![n]He's gonna leave if we don't hurry.[n][w][e]

[msg MND_E14130100_CHK_BUTURI]
[s][vp 1 0 0 0 0 0]This is the physics room.[n]There's a lot of unattended[n]lab equipment in here...[n][w][e]

[msg MND_E14710100_CHK_BUTURI]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E15010100_CHK_BUTURI [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]I think Sakamoto went up to the[n][clr 2]PE faculty office on the second floor[clr 27]...[n][w][e]

[msg MND_E15010100_CHK_BUTURI]
[s][vp 1 0 0 0 0 0]For now, I better[n]try to get to Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_BUTURI [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]This seems like the physics room. Isn't the[n]student council room on the [clr 2]third[n]floor of the classroom building[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_BUTURI]
[s][vp 1 0 0 0 0 0]I better hurry on my way...[n][w][e]

[msg MND_COMMON_CHK_BUTURISIT]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here...[n][w][e]

[msg MND_E65110100_CHK_EMERGE]
[s][vp 1 0 0 0 0 0]Not this way...[n][w][e]

[msg MSG_KFEVT_EXIT_DOOR [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1178 0 0]That's the emergency exit! You don't[n]want to mess with that...[n][w][e]

[msg MND_KFEVT_EXIT_DOOR]
[s][vp 1 0 0 0 0 0]There's no reason for me[n]to use the emergency exit...[n][w][e]

[msg MND_E65110100_CHK_KATEIK_2]
[s][vp 1 0 0 0 0 0]I better hurry on my way...[n][w][e]

[msg MND_COMMON_CHK_KATEIKA_T]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here...[n][w][e]

