[msg MSG_LAST_GREETING_PAPER_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Iwai's gotta be the one making these flyers.[n]His handwriting's... cuter than I expected.[n][w][e]

[msg MSG_LAST_GREETING_CUPSUL [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Probably don't see a lot of military capsule[n]machines in your hometown, huh?[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]You don't need to be here right now, do[n]you? Come on, let's head somewhere else![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]What's wrong? Come on, we should go say[n]goodbye to the others![n][w][e]

[msg MSG_GOTO_OUT_NG]
[s][vp 8 2 1 0 65535 0]...I haven't gotten a weapon yet.[n]I should talk to the shop owner.[n][w][e]

[msg CHK_PAPER_RACK_PC_0404_0]
[s][vp 8 2 1 0 65535 0]This looks like an ad[n]for a model gun.[n][w][e]
[s][vp 8 2 1 0 65535 0]There are all these terms[n]that I don't recognize...[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]You interested in that revolver?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]It's equipped with a full barrel shroud and[n]the effect of the stabilizer is outstanding.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]The spring is stainless steel. If you're just[n]collecting, I can put in a dummy cartridge.[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404_2 [Surly Manager]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]You interested in that revolver?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]It's equipped with a full barrel shroud and[n]the effect of the stabilizer is outstanding.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]The spring is stainless steel. If you're just[n]collecting, I can put in a dummy cartridge.[n][w][e]

[sel CHK_PAPER_RACK_0404_SEL top]
[s]Okay, sure.[e]
[s]I'd rather not.[e]

[msg CHK_PAPER_RACK_IWAI_0404_3 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]...Oh yeah? Guess you must be the[n]careful type.[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404_4 [Surly Manager]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]...Oh yeah? Guess you must be the[n]careful type.[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404_5 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Heh... Well, I don't blame ya. If you wanted[n]to show off, that'd be the way to go.[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404_6 [Surly Manager]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Heh... Well, I don't blame ya. If you wanted[n]to show off, that'd be the way to go.[n][w][e]

[msg CHK_PAPER_RACK_PC_0418]
[s][vp 8 2 1 0 65535 0]It's an invitation flyer[n]for a survival game.[n][w][e]
[s][vp 8 2 1 0 65535 0]Looks like there's a survival game[n]club in Shujin Academy too...[n][w][e]

[msg CHK_PAPER_RACK_0425]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s]"Bringing you new model guns,[n]as well as various military[n]goods, every month!"[n][w][e]

[msg CHK_PAPER_RACK_0503]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"This month's featured product[n]packs a real kick! It's the [clr 4]Bianchi SBAS[clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0519]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"The star of the June lineup is...[n]the long-awaited [clr 4][var 1][clr 27]!"[n][w][e]
[s][vp 8 2 1 0 65535 0]"A rebirth of raging billows: the [clr 4]Sand Hawk[clr 27]![n]Extremely popular: [clr 4][var 3][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0607]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"This month's special is[n]finally here! It's the [clr 4]Comet 3[clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0620]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"July brings us a returning[n]legend: [clr 4][var 1][clr 27]!"[n][w][e]
[s][vp 8 2 1 0 65535 0]"Celebrating its 50th anniversary: [clr 4]Hellfire[clr 27]![n]And a dramatic arrival: [clr 4][var 3][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0710]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"This month's featured product is[n]the masterpiece of this century![n]It's the [clr 4][var 1][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0725]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"September's kicking off with a bang![n] Introducing the [clr 4][var 1][clr 27]!"[n][w][e]
[s][vp 8 2 1 0 65535 0]"Power overwhelming: the [clr 4]Annihilator[clr 27]![n]Detailed to perfection: [clr 4][var 3][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0815]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"Next month's featured product![n]Cherished by the world champion![n]It's the [clr 4][var 1][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0831]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"Here's the star of the October lineup![n]The supersonic knuckle: [clr 4][var 1][clr 27]!"[n][w][e]
[s][vp 8 2 1 0 65535 0]"For raw destruction: the [clr 4]Western SMG[clr 27]![n]Outstanding stability: [clr 4][var 3][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0914]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"October's spotlight item is so authentic,[n]it might as well be real: the [clr 4][var 1][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0921]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"The new star of November's[n]lineup is the [clr 4][var 1][clr 27]!"[n][w][e]
[s][vp 8 2 1 0 65535 0]"The [clr 4]Calamity Gun[clr 27] makes a comeback![n]For the newbies, it's the [clr 4][var 3][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_1012]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"This month's spotlight is on a[n]rare find! It's the [clr 4]Eraser[clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_1026]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"December's lineup brings us the[n]long-awaited [clr 4][var 1][clr 27]!"[n][w][e]
[s][vp 8 2 1 0 65535 0]"For the fans! The [clr 4]R. I. Pistol[clr 27]![n]Protection with peace of mind! [clr 4][var 3][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_1109]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"The year's-end featured product[n]is the legendary [clr 4][var 1][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_1123]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]

[msg CHK_PAPER_RACK_1207]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]

[msg CHK_PAPER_RACK_1219]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"January brings us a master craftsman's[n]newest work! [clr 4][var 1][clr 27]!"[n][w][e]
[s][vp 8 2 1 0 65535 0]"The last of its kind: [clr 4]SIG 227[clr 27]![n]One for every household: [clr 4][var 2][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0101]
[s][vp 8 2 1 0 65535 0]It looks like an ad for[n]this shop...[n][w][e]
[s][vp 8 2 1 0 65535 0]"Here's the star of the January lineup![n]Feel the new wind: [clr 4][var 1][clr 27]!"[n][w][e]

[msg MSG_CUPSULE_MACHINE_NOSA]
[s][vp 8 2 1 0 65535 0]It's a ration vending machine.[n][w][e]
[s][vp 8 2 1 0 65535 0]It says, "Scheduled to arrive[n]in a few days!"[n][w][e]

[msg MSG_CUPSULE_MACHINE_0401 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]It says, "Taste Test! The Rations of the[n]World VOL. 37."[n][w][e]

[msg MSG_CUPSULE_MACHINE_0607 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]It says, "Taste Test! The Rations of the[n]World VOL. 38."[n][w][e]

[msg MSG_CUPSULE_MACHINE_0815 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]It says, "Taste Test! The Rations of the[n]World VOL. 39."[n][w][e]

[msg MSG_CUPSULE_MACHINE_1012 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]It says, "Taste Test! The Rations of the[n]World VOL. 40."[n][w][e]

[msg MSG_CUPSULE_MACHINE_1207 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]It says, "Taste Test! The Rations of the[n]World VOL. 41."[n][w][e]

[msg MSG_CUPSULE_MACHINE_0101 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]It says, "Taste Test! The Rations of the[n]World VOL. 42."[n][w][e]

[msg MSG_CUPSULE_MACHINE_0109]
[s][vp 8 2 1 0 65535 0]It says, "Taste Test! The Rations of the[n]World VOL. 42."[n][w][e]

[msg MSG_CUPSULE_MACHINE_0404 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]It costs 800 yen per try, but... You want to[n]give this a go?[n][w][e]

[msg MSG_CUPSULE_MACHINE_0404_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]It's 800 yen each try, but do you wanna[n]give it a go?[n][w][e]

[msg MSG_CUPSULE_MACHINE_0109_2]
[s][vp 8 2 1 0 65535 0]It's 800 yen per try.[n]Should I give it a shot?[n][w][e]

[sel MIRIMESI_SEL top]
[s]Let's give it a try.[e]
[s]I'll pass.[e]

[msg SEL_MIRIMESI_A_02]
[s][vp 8 2 1 0 65535 0]The capsule is a bit sticky...[n][w][e]

[msg SEL_MIRIMESI_A_03]
[s][vp 8 2 1 0 65535 0]Maybe I'm imagining things,[n]but for a split second, I thought[n]I smelled something terrible...[n][w][e]

[msg SEL_MIRIMESI_A_04]
[s][vp 8 2 1 0 65535 0]It seems pretty normal[n]at first glance, but...[n][w][e]

[msg SEL_MIRIMESI_BIG_HAZURE [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13074 65535 0]...Well, that stinks.[n][w][e]

[msg SEL_MIRIMESI_HAZURE [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13043 65535 0]...Not too bad.[n][w][e]

[msg SEL_MIRIMESI_ATARI [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 1 13045 65535 0]Ho... You got lucky there.[n][w][e]

[msg SEL_MIRIMESI_BIG_HAZURE_ [Surly Manager]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13074 65535 0]...Well, that stinks.[n][w][e]

[msg SEL_MIRIMESI_HAZURE_name [Surly Manager]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13043 65535 0]...Not too bad.[n][w][e]

[msg SEL_MIRIMESI_ATARI_namel [Surly Manager]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 1 13045 65535 0]Ho... You got lucky there.[n][w][e]

[msg MSG_CUPSULE_NO_MONEY [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1025 65535 0]Whoa. You don't have enough money.[n][w][e]

[msg MSG_CUPSULE_NO_MONEY_HER]
[s][vp 8 2 1 0 65535 0]I don't have enough money...[n][w][e]

[msg MND_NOOPEN_SHOP]
[s]I still haven't purchased[n]anything yet...[n][w][e]

[msg MSG_180105_GOTO_NG_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]You haven't sold that gold medal yet, right?[n]Don't leave until you ask if you can sell that![n][w][e]

[msg MSG_OPEN_SHOP [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7183 65535 0]You goin' home already?[n][w][e]
[s][vp 8 2 1 0 65535 0]Anyways, I'll have you do the choosin'[n]from now on. Get me the strongest-[n]lookin' one![n][w][e]

[msg MSG_C12_BEGIN_TIME_08 [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13001 212 0]You got an awfully serious look. I don't[n]wanna get dragged into trouble, so I'm[n]not gonna ask.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 212 0]If there's anything you want, go ahead[n]and check 'em out.[n][w][e]

[msg MSG_C12_BEGIN_TIME_08_01 [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 212 0]...Just don't overdo it.[n][w][e]

[msg MSG_C12_BEGIN_TIME_0109_ [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13082 212 0]Sorry for the delay. Happy New Year.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 212 0]Got too many new-years troublemakers[n]coming by. The location probably doesn't[n]help.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 13090 212 0]Feels like the whole town's losin' its[n]damn mind.[n][w][e]

[msg MSG_C12_BEGIN_TIME_0109__2 [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 212 0]If there's anything you want, go ahead[n]and check 'em out.[n][w][e]

[msg MSG_C12_BEGIN_TIME_0109__3 [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 212 0]See ya.[n][w][e]

