[msg DUMMY_MSG]
[s]I sold [var 0].[n][w][e]

[msg MSG_LAST_GREETING_InfoCe [Information Desk Lady]]
[s][vp 8 2 1 58671 1 0]My, you're that young man from a while[n]ago, aren't you? The one who listened so[n]intently to the information I gave.[n][w][e]
[s][vp 8 2 1 0 1 0]Did you learn a lot about Kichijoji on[n]your own, too?[n][w][e]

[msg MSG_LAST_GREETING_InfoCe_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Hey, you're going to be leaving this city[n]soon, so you should say goodbye to that[n]nice info lady, too.[n][w][e]

[msg MSG_LAST_GREETING_InfoCe_3 [Information Desk Lady]]
[s][vp 8 2 1 58675 1 0]Huh!? You're moving away!?[n][w][e]
[s][vp 8 2 1 0 1 0]I see... I bet where you're from is a[n]wonderful place, too.[n][w][e]
[s][vp 8 2 1 0 1 0]But wouldn't you say that Kichijoji has[n]been a great hometown?[n][w][e]
[s][vp 8 2 1 0 1 0]That's why I hope you won't forget about[n]this city. Make sure you come again. I'll[n]always be here.[n][w][e]

[msg MSG_LAST_GREETING_InfoCe_4 [Information Desk Lady]]
[s][vp 8 2 1 58673 1 0]That's why I hope you won't forget about[n]this city. Make sure you come again. I'll[n]always be here.[n][w][e]

[msg MSG_LAST_GREETING_InfoCe_5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]There's no point learning more about this[n]city now, right? Let's go somewhere else.[n][w][e]

[msg MSG_LAST_GREETING_MeatFr [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]This place had a huge line, no matter[n]when we came. Hey, let's come here[n]again some day.[n][w][e]

[msg MSG_LAST_GREETING_DartsA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]We spent a lot of time here. Playing[n]together with everyone is a great[n]memory for the both of us.[n][w][e]

[msg MSG_LAST_GREETING_DartsA_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]There's no time play a game right now.[n]Let's go say goodbye to everyone.[n][w][e]

[msg MSG_LAST_GREETING_JazzCl [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Akechi was the one who told you about[n]this place...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]I bet he... C'mon, let's go somewhere else.[n][w][e]

[msg MSG_LAST_GREETING_JazzCl_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Looks like this place is closed during[n]the day. Let's go somewhere else.[n][w][e]

[msg MSG_LAST_GREETING_Shop_A [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]You've got tons of trustworthy friends.[n]You don't need to rely on healing crystals.[n][w][e]

[msg MSG_LAST_GREETING_Shop_V [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]It smells sooo goood... Ahem. You don't[n]have any business here, right? Let's go.[n][w][e]

[msg MSG_LAST_GREETING_Cafe_A [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]We came here a number of times with[n]Akechi. If he were still around, I bet—[n]Hm, never mind.[n][w][e]

[msg MSG_LAST_GREETING_Cafe [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]If you're gonna drink coffee, you should[n]do so at Leblanc. We gotta go see everyone[n]first.[n][w][e]

[msg MSG_LAST_GREETING_Shop_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1191 65535 0]Isn't this where you guys bought glasses[n]for Sumire's dad?[n][w][e]
[s]More importantly, why're you still[n]wearing yours?[n][w][e]

[msg MSG_LAST_GREETING_Shop_M_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Now's not the time to be picking out[n]glasses. Let's hurry up and go say goodbye[n]to everyone.[n][w][e]

[msg MSG_LAST_GREETING_FoodSh [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]This really is one fashionable store. Does[n]your hometown have a shop like this too?[n][w][e]

[msg MSG_LAST_GREETING_Statio [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]There's so much colorful and fashionable[n]stationery... It's fitting for Kichijoji.[n][w][e]

[msg MSG_LAST_GREETING_Temple [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]The open corridor of the temple was[n]quiet and really tranquil.[n][w][e]
[s][f 4 10 65535 0 0]Didn't you say your hometown is nice[n]and quiet too? I'm looking forward to it.[n][w][e]

[msg MSG_LAST_GREETING_Temple_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Hey, you don't know any monks, do you?[n]Let's go somewhere else.[n][w][e]

[msg MSG_LAST_GREETING_OldClo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Now's not the time to be looking for[n]fashionable secondhand clothes![n][w][e]

[msg MSG_LAST_GREETING_Dagash [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]That reminds me. I wonder why Sumire[n]was at this store?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Well, I guess it doesn't matter.[n]Let's go say our goodbyes.[n][w][e]

[msg MSG_LAST_GREETING_Dagash_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Now's not the time to be stopping for[n]a snack.[n][w][e]

[msg MSG_LAST_GREETING_Bank [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]I don't remember you ever having a bank[n]account. Let's go elsewhere.[n][w][e]

[msg MSG_LAST_GREETING_Ethnic [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Remember that sushi restaurant in Ginza?[n]Mmm. You know... I don't mind rotating[n]sushi restaurants either.[n][w][e]
[s][f 4 10 65535 0 0]Speaking of, does your hometown happen[n]to be near the sea? I can't wait to see what[n]kind of place it is![n][w][e]

[msg MSG_LAST_GREETING_HatSho [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1157 65535 0]So many stylish hats... All of these[n]would look great on Haru![n][w][e]

[msg MSG_LAST_GREETING_Taiyak [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]I want the best taiyaki around. Sea bream[n]shaped pancakes with red bean in them...[n]They have those in your hometown, right?[n][w][e]

[msg MSG_LAST_GREETING_TeaHou [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1157 65535 0]I agree, let's eat some sweets and relax[n]with a nice cup of tea...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]I mean, no! It'll be night before we know[n]it if we did that! Let's say our goodbyes[n]to everyone while the sun's still out.[n][w][e]

[msg MSG_LAST_GREETING_SocksS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1155 65535 0]I'm sure you already know this, but I'm[n]not wearing white socks, okay?[n][w][e]

[msg MSG_LAST_GREETING_Teleph [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53124 65535 0]Your cell phone helped us out a ton.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]From staying in contact with everyone to[n]the Metaverse Navigator... We wouldn't[n]be here had it not been for your phone.[n][w][e]

[msg MSG_LAST_GREETING_IceSho [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]You know, Ryuji often eats soda-flavored[n]ice cream bars. I remember him eating[n]one when we went to the beach, too.[n][w][e]

[msg MSG_LAST_GREETING_Fudous [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]You know, if we ever come back here,[n]I want to live in Yongen.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Don't you think so, too?[n][w][e]

[msg MSG_LAST_GREETING_MajorC [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]If you get full now, you won't be able to[n]say your farewells to everyone.[n][w][e]

[msg MSG_LAST_GREETING_Ethnic_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]I'm kinda excited to see your room in[n]your hometown. What's it like?[n][w][e]

[msg MSG_LAST_GREETING_Realto [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Don't you already have furniture in[n]your room in your hometown?[n][w][e]

[msg MSG_LAST_GREETING_Karaok [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Your hometown is pretty far from[n]here, right? I'll sing on the train to[n]keep you entertained.[n][w][e]

[msg MSG_LAST_GREETING_Record [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Do you have a machine that can play[n]giant CDs in your hometown?[n][w][e]

[msg MSG_LAST_GREETING_MusicT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Hey, did you know? Iwai plays the guitar![n][w][e]

[msg MSG_LAST_GREETING_MusicT_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]C'mon, you've got no interest in[n]instruments, right? Let's go somewhere[n]else.[n][w][e]

[msg MSG_LAST_GREETING_Pasta_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]What a fancy looking pasta shop.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]I bet someone like Kawakami would really[n]like this place. Let's bring her here one day.[n][w][e]

[msg MSG_LAST_GREETING_Pasta [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]What a fancy pasta place. Are you hungry[n]or something?[n][w][e]

[msg MSG_LAST_GREETING_Bicycl [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]We're not gonna bike home...[n]We're taking the train, aren't we?[n][w][e]

[msg MSG_LAST_GREETING_ToySho [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]What're you doing looking at toys?[n]Let's go see everyone.[n][w][e]

[msg MSG_LAST_GREETING_SteakF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]I bet Ryuji'd love eating meat like this.[n]Maybe we oughta come here with him[n]next time we visit.[n][w][e]

[msg MSG_LAST_GREETING_WineBa [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]A wine bar, huh? Let's come back here[n]and drink with Ohya when you're old[n]enough.[n][w][e]

[msg MSG_LAST_GREETING_WineBa_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]You're not old enough to drink yet.[n]C'mon, let's go somewhere else.[n][w][e]

[msg MSG_LAST_GREETING_Antiqu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Your room at Leblanc seems pretty[n]antique, but how's the room in your[n]hometown? I'm so excited.[n][w][e]

[msg MSG_LAST_GREETING_DonutS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Do you remember the donut thing?[n]Gotta admit I was pretty impressed[n]by your observation skills.[n][w][e]

[msg MSG_LAST_GREETING_DonutS_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]You want donuts? Don't they sell those[n]in your hometown?[n][w][e]

[msg MSG_LAST_GREETING_Sports [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]I bet going to the outdoors with everyone[n]would be fun.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]We could take a camping car and just[n]travel around the country.[n][w][e]

[msg MSG_LAST_GREETING_Realto_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]You remember when you just went and sat[n]down here? You must've really thought[n]this one was comfy.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]I'd be happy if the sofa in your hometown[n]was just as comfy.[n][w][e]

[msg MSG_LAST_GREETING_Realto_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]Why're you staring at the sofa?[n]Are you getting tired?[n][w][e]

[msg MSG_LAST_GREETING_Realto_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]You've got a chair in your room in your[n]hometown, right? Guess there's probably[n]not any beams to do training though, huh?[n][w][e]

[msg MSG_LAST_GREETING_AUTO_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Hey, we don't have time to be drinking[n]juice! We're going to go say our farewells,[n]right?[n][w][e]

[msg MSG_LAST_GREETING_CoinLo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]You won't be able to come back to get[n]your stuff for a while... It's probably[n]better not to use the coin lockers.[n][w][e]

[msg MSG_LAST_GREETING_Tobari [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1183 65535 0]The oden here looked so good, huh?[n]It's closed though.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]There were so many types of drinks[n]here. Well, it's closed right now.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1191 65535 0]This place was so small... Can't really go[n]in to check it out again since it's closed[n]though.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]This place's kitchen was so tiny, even the[n]chief would be astonished. It's closed right[n]now though, so we can't really check it out.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]I smell some fresh fish coming from here![n]...It's closed though.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_6 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1179 65535 0]That tomato oden looked really tasty, huh?[n]We can't eat any now though, it's closed.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_7 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]There's a small store on the second floor.[n]Think it's called "Pig Hot Spring." Does[n]that mean they have a hot spring here?[n][w][e]

[msg MSG_LAST_GREETING_Tobari_8 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]This place, "Tsuppari Banzuke," looks[n]like they have some local dishes to eat.[n]Isn't "tsuppari" a sumo term?[n][w][e]

[msg MSG_LAST_GREETING_Tobari_9 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1034 65535 0]This place is covered with graffiti.[n]Maybe you should come here with[n]Yusuke someday.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_10 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1023 65535 0]This store is lucky it's located on a fancy[n]street. Well, we can't check it out right[n]now, it's closed.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_11 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]The smell of fried chicken in there was so[n]enticing... It's closed right now though.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_12 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]You get to drink on tatami flooring here,[n]right? But we can't see it since it's closed.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_13 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]I remember they had barrels in the store.[n]It looked like they really cared about the[n]fanciness, despite how small the place was.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_14 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1001 65535 0]We got to eat all types of wings here.[n]Looks like it's closed though.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_15 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]The nikuman looks really good, but we[n]don't have time to be eating right now.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_16 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]The ramen at this place always looks so[n]good. One of these days I wanna go to[n]every ramen shop in Tokyo.[n][w][e]

[msg MSG_LAST_GREETING_Udon_1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Oh yeah, I saw Hifumi's interview.[n]Did you know she liked udon?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You should bring her here one day.[n][w][e]

[msg MSG_LAST_GREETING_Udon_1_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Might be a place where you can stand[n]and eat udon, but we don't have time[n]for that right now.[n][w][e]

[msg MSG_LAST_GREETING_Deaden [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Yeah, I'm sure we'll find them in the[n]trash... Hell no! Why would they be[n]here!? Let's get going![n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]C'mon, we've got nothing to do here.[n]Let's go elsewhere![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]We know no one's past this area. Let's[n]hurry up and head to where they are![n][w][e]

[msg MSG_LastKeyfree [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]We can't wait any longer...[n]We have to prepare, and fast![n][w][e]

[msg MND_0103]
[s]I should find out what[n]my friends are doing.[n][w][e]

[msg MND_TEMPLE_0103]
[s]......[n][w][e]
[s]It seems like they're[n]closed until the 8th.[n][w][e]

[msg MND_0103to0108_Error_Not]
[s]Now's not the time[n]to be shopping.[n][w][e]
[s]I should go check[n]up on everyone.[n][w][e]

[msg MND_0103to0108_Error_Not_2]
[s]This is no time for detours.[n][w][e]
[s]I should go check[n]up on everyone.[n][w][e]

[msg MND_CommonKeyFree]
[s]There's something I[n]need to do right now.[n][w][e]

[msg MSG_CommonKeyFree [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]You've got no business here.[n][w][e]

[msg MND_Juice_NotOpen]
[s]I'm not thirsty right now.[n][w][e]

[msg MSG_Juice_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Are you thinking of buying something[n]to drink?[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Everything's sold out... Let's wait for it[n]to get restocked next week.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Whoops, everything's sold out. Let's wait[n]for it to get restocked next week.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]...Everything's sold out. I guess it's no[n]surprise with how hot it is right now...[n][w][e]

[msg MSG_KF794101_AddInfo [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]C'mon, let's hurry over to the darts lounge.[n][w][e]

[msg MSG_GATE_DEAFULT_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Are you going to travel to another area?[n][w][e]

[sel SEL_GATE_YESNO_moru top]
[s]Yes, let's go.[e]
[s]No, not yet.[e]

[msg MND_GATE_0103]
[s]Let's go to a different area...[n][w][e]

[msg MSG_GOTO_Kichijoji2Shibu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Past this area is the Inogami Line.[n]Paying 200 yen will get you to Shibuya.[n]Do you wanna go?[n][w][e]

[sel SEL_GOTO_Kichijoji2Shibu top]
[s]That sounds good.[e]
[s]Let's not.[e]

[msg MSG_GOTO_Kichijoji2Shibu_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1001 0 0]Oh, you don't have enough money?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]I'll give you some from my secret stash for[n]now, but make sure you have some with[n]you next time.[n][w][e]

[msg MSG_GOTO_Kichijoji2Shibu_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]There's nothing you need to do here,[n]right? Let's go somewhere else![n][w][e]

[msg MSG_GOTO_Kichijoji2Shibu_4]
[s]There's nothing I need to do[n]over here. I should turn back...[n][w][e]

[msg MSG_KF794101_InfoCenter [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]A city information desk...? I guess you[n]don't really see stuff like that in other cities.[n][w][e]

[msg MSG_InfoCenter [Information Desk Lady]]
[s][vp 8 2 1 58671 1 0]Hello! We do our best to provide[n]information regarding this area![n][w][e]

[msg MSG_InfoCenter02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Why don't you ask them about Kichijoji?[n][w][e]

[msg MND_InfoCenter02]
[s]What do I want to know about Kichijoji...[n][w][e]

[msg MSG_InfoCenter_start [Information Desk Lady]]
[s][vp 8 2 1 58672 1 0]What would you like to hear about?[n][w][e]

[sel SEL_InfoCenter top]
[s]About this city.[e]
[s]What do you recommend?[e]
[s]About the stores.[e]
[s]Anything I should know?[e]
[s]Nothing.[e]

[msg MSG_InfoCenter01_01 [Information Desk Lady]]
[s][vp 8 2 1 58673 1 0]Certainly! Please allow me to explain![n][w][e]
[s][vp 8 2 1 0 1 0]There are four different areas...[n][w][e]
[s][vp 8 2 1 0 1 0]On the promenade, you can find a fried[n]food shop, a stationery store, a second-[n]hand clothing store, and a temple.[n][w][e]
[s][vp 8 2 1 0 1 0]The ground beef cutlet at the fried food[n]shop is delicious, but you will have to[n]wait in line.[n][w][e]
[s][vp 8 2 1 0 1 0]If you take a left at the fried food shop,[n]you'll see Retro Street. Here you can find a[n]selection of chic and sophisticated stores.[n][w][e]
[s][vp 8 2 1 0 1 0]There's also a jazz club at the end of the[n]alley. Sometimes popular singers will go[n]there, and the liveliness is inevitable.[n][w][e]
[s][vp 8 2 1 58674 1 0]Whew. I hope I explained it all right...[n]Do you have any other questions?[n][w][e]

[sel SEL_InfoCenter01_Inter top]
[s]Please continue.[e]
[s]I think I'll be okay.[e]

[msg MSG_InfoCenter01_02 [Information Desk Lady]]
[s][vp 8 2 1 58676 1 0]Of course![n][w][e]
[s][vp 8 2 1 0 1 0]After passing Retro street, you will see[n]Rue De Chouchou, which has a variety[n]of fancy stores to visit.[n][w][e]
[s][vp 8 2 1 0 1 0]There's also a well-known healing crystal[n]store selling power stones that provide[n]real results.[n][w][e]
[s][vp 8 2 1 0 1 0]Not only that, but on Rue De Chouchou[n]there is a lounge to enjoy darts and[n]billiards. Excitement is inevitable.[n][w][e]
[s][vp 8 2 1 0 1 0]The last one is Harmony Alley, which is[n]like a drinking district. It's located just[n]past this information desk.[n][w][e]
[s][vp 8 2 1 0 1 0]It has an old Japanese flavor, perfect[n]for just enjoying the atmosphere. The[n]inspiration is inevitable.[n][w][e]
[s][vp 8 2 1 0 1 0]...Was that too much information for[n]a minor?[n][w][e]
[s][vp 8 2 1 0 1 0]Well, that's about it for the city. Is there[n]something else I can help you with?[n][w][e]

[msg MSG_InfoCenter02_01 [Information Desk Lady]]
[s][vp 8 2 1 58673 1 0]I know just the thing! Please allow[n]me to explain! You're a minor correct?[n]If that's the case...[n][w][e]
[s][vp 8 2 1 0 1 0]If you go past the drinking district and[n]reach Rue De Chouchou, you will find a[n]darts and billiards lounge.[n][w][e]
[s][vp 8 2 1 0 1 0]It's actually a very casual place, and people[n]your age can walk in with no problem.[n][w][e]

[sel SEL_InfoCenter02_Inter top]
[s]How about for adults?[e]
[s]What about somewhere unique?[e]

[msg MSG_InfoCenter02_02 [Information Desk Lady]]
[s][vp 8 2 1 58675 1 0]Huh!? Well, you did come all the[n]way here...[n][w][e]
[s][vp 8 2 1 0 1 0]If you're looking for a place for adults...[n]There is a jazz club...[n][w][e]
[s][vp 8 2 1 0 1 0]And I THINK minors can go in...[n]Sorry for my lack of knowledge.[n][w][e]
[s][vp 8 2 1 0 1 0]Would you like to know anything else?[n][w][e]

[msg MSG_InfoCenter02_03 [Information Desk Lady]]
[s][vp 8 2 1 58677 1 0]Oh yes! One of the city's hidden gems[n]is the temple in the promenade.[n][w][e]
[s][vp 8 2 1 0 1 0]It's even popular among young people[n]who are looking for some guidance.[n][w][e]
[s][vp 8 2 1 0 1 0]Oh, maybe that doesn't really include[n]students like you...? Haha. If you're ever[n]interested you should check it out.[n][w][e]
[s][vp 8 2 1 0 1 0]Was there anything else you wanted to[n]hear about?[n][w][e]

[msg MSG_InfoCenter03_01 [Information Desk Lady]]
[s][vp 8 2 1 58673 1 0]Certainly! Allow me to explain![n][w][e]
[s][vp 8 2 1 0 1 0]There's a strange— Excuse me, a unique[n]secondhand clothing store here as well.[n][w][e]
[s][vp 8 2 1 0 1 0]It's located on the promenade street.[n]The manager always greets me in the[n]morning, but...[n][w][e]
[s][vp 8 2 1 0 1 0]He's always saying, "I specifically want[n]sooty clothing." And is quite picky about[n]what you bring in too.[n][w][e]
[s][vp 8 2 1 0 1 0]Oh, and have you been to the incense[n]store in Harmony Alley? It actually[n]opened quite recently.[n][w][e]
[s][vp 8 2 1 0 1 0]They have incenses that people have[n]never even heard of before. And it's[n]not a fishy store either.[n][w][e]
[s][vp 8 2 1 0 1 0]Was there anything else you wanted[n]to ask?[n][w][e]

[msg MSG_InfoCenter04_01 [Information Desk Lady]]
[s][vp 8 2 1 58678 1 0]Anything you should know... Actually,[n]yes. There's something I heard recently.[n][w][e]
[s][vp 8 2 1 0 1 0]About the fried food shop in the[n]promenade. People say it's tedious[n]to wait in line...[n][w][e]
[s][vp 8 2 1 0 1 0]And by nighttime it's already sold out.[n]So what're we to do if we want one?[n][w][e]
[s][vp 8 2 1 0 1 0]Well, they say on Sundays they make[n]more than usual.[n][w][e]
[s][vp 8 2 1 0 1 0]So, in other words, if you go there on a[n]Sunday night... And the story I heard[n]ends there.[n][w][e]
[s][vp 8 2 1 0 1 0]Anything else you would like to know?[n][w][e]

[msg MSG_InfoCenter05_01 [Information Desk Lady]]
[s][vp 8 2 1 58680 1 0]If you would like to know more about[n]Kichijoji, feel free to stop on by![n][w][e]

[msg MSG_InfoCenter_00 [Information Desk Lady]]
[s][vp 8 2 1 58679 1 0]Was there something else you wanted[n]to ask?[n][w][e]

[msg MSG_InfoCenter_ParamUp [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 1 0]Whew... That was quite a lot of[n]information. I think we were able to[n]broaden our insights about Kichijoji![n][w][e]

[msg MND_InfoCenter_ParamUp]
[s]I feel like I've broadened[n]my insights...![n][w][e]

[msg MSG_InfoCenter_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Looks like it's closed.[n][w][e]
[s][f 4 10 65535 0 0]If you have questions, you should come[n]back here during the daytime.[n][w][e]

[msg MND_InfoCenter_heiten]
[s]It looks like it's closed...[n][w][e]
[s]I should come back[n]here another time.[n][w][e]

[msg MSG_KF794101_FriedShop [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Holy crap, look at the line! I think I saw[n]this place on TV.[n][w][e]

[msg MSG_FriedShop_NG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Ooh, it smells sooo good! Looks like the[n]ground meat cutlet here's really popular.[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]But man, look at the line... It'll take[n]forever at this rate. Let's give it up.[n][w][e]

[msg MND_FriedShop_NG]
[s]It smells really good, but...[n][w][e]
[s]The line seems really long...[n]I should try again some other time.[n][w][e]

[msg MSG_FriedShop_NG_Night [Fried Food Shop Staff]]
[s][vp 8 2 1 0 2 0]Oh, you're here for our popular[n][clr 3]Chunky Katsu[clr 27]? Sorry, but we're[n]sold out for today...[n][w][e]
[s][vp 8 2 1 0 2 0]Try stopping by a different day.[n]We might have it then.[n][w][e]

[msg MSG_FriedShop_OK [Fried Food Shop Staff]]
[s][vp 8 2 1 0 2 0]Welcome. Here's your [clr 3]Chunky Katsu[clr 27].[n]It's the last one, too.[n][w][e]

[msg MSG_FriedShop_Thanks [Fried Food Shop Staff]]
[s][vp 8 2 1 0 2 0]Thanks! Be careful, it's hot.[n][w][e]

[msg MSG_FriedShop_NotBuy [Fried Food Shop Staff]]
[s][vp 8 2 1 0 2 0]Not in the mood for one today?[n][w][e]

[msg MSG_FriedShop_SoldOut [Fried Food Shop Staff]]
[s][vp 8 2 1 0 2 0]Sorry that was the last one.[n]Come again for seconds, okay?[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_DART]
[s]You can now quick travel to[n][clr 6]Darts & Billiards[clr 0] in Kichijoji.[n][w][e]

[msg MSG_JazzClub_PreStart [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]It's the jazz club that Akechi introduced[n]you to.[n][w][e]

[msg MSG_Jazzclub_Start_1st02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Places like this'll help you relax. And[n]talk about things that you'd usually[n]find difficult to.[n][w][e]
[s][f 4 10 65535 0 0]Hmm. As the leader of the Phantom[n]Thieves, maybe you can invite one of[n]the members here.[n][w][e]

[sel SEL_Jazzclub_1st top]
[s]Not a bad idea...[e]
[s]Wonder what everyone's up to...[e]

[msg MSG_JazzClub_Ck_info_1st [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]Oh, looks like for minors they will serve[n]"[clr 2]non-alcoholic cocktails[clr 27]."[n][w][e]

[msg MSG_JazzClub_Ck_info_Com [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]Hmm, looks like tonight's cocktail is[n]"[clr 2][var 0][clr 27]."[n][w][e]

[msg MSG_JazzClub_Ck_info_Get [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"It's so good that it'll give you more[n][clr 2]stamina[clr 27]! Bring your stamina to the[n][clr 2]next level[clr 27]!"[n][w][e]

[msg MSG_JazzClub_Ck_info_Kay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"The taste of this drink will give you[n][clr 2]power[clr 27] AND [clr 2]luck[clr 27]! You'll be able to[n][clr 2]defend[clr 27] yourself against anything!"[n][w][e]

[msg MSG_JazzClub_Ck_info_Sui [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"Let your [clr 2]soul[clr 27] open up with this cocktail[n]and take yourself to the [clr 2]next level[clr 27]!"[n][w][e]

[msg MSG_JazzClub_Ck_info_Mok [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"Let your [clr 2]speed[clr 27] and [clr 2]luck[clr 27] explode with[n]the special ingredients in this drink![n]Let yourself be covered in [clr 2]magic[clr 27]!"[n][w][e]

[msg MSG_JazzClub_Ck_info_Kin [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"[clr 2]All of your stats[clr 27] will improve! This[n]wonderful drink will help your[n][clr 2]stamina[clr 27] and [clr 2]soul[clr 27]!"[n][w][e]

[msg MSG_JazzClub_Ck_info_Nit [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"Today's original drink! Maybe you'll[n]be able to discover a new side of yourself,[n]maybe one you never knew about!?"[n][w][e]

[msg MSG_JazzClub_Ck_info_End [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Sounds pretty good![n][w][e]

[msg MSG_Jazz_TodaySinger_Tut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Huh, looks like there are[n]days [clr 2]a singer comes in[clr 27]...[n][w][e]

[msg MSG_Jazz_TodaySingerOK [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Oh, check it out! Today's a day that a[n]singer's coming in![n][w][e]

[msg MSG_JazzClub_AskUse [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]You wanna go listen in? Looks like it's[n]gonna cost you [clr 2]3,000 yen[clr 27].[n][w][e]

[sel SEL_Jazzclub_UseThink top]
[s]Invite someone[e]
[s]Check out the sign[e]
[s]Cancel[e]

[msg MSG_Jazz_NextSingerDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]The singer's coming in on [clr 2][var 1]/[var 2][clr 27]![n]Drinking cocktails while listening to[n]live music... Sounds pretty adult, huh?[n][w][e]

[msg MSG_Jazzclub_NoMoreSinge [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hmm. It's a bit disappointing, but it[n]doesn't look like there's any mentions[n]of when the singer's coming in...[n][w][e]

[msg MSG_Jazzclub_Who_Invite [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Who're you gonna invite?[n][w][e]

[sel SEL_SELECT_FRIEND top]
[s]Blank: This is not used[e]
[s]Protag: This will also not be used.[e]
[s]Ryuji[e]
[s]Morgana[e]
[s]Ann[e]
[s]Yusuke[e]
[s]Makoto[e]
[s]Haru[e]
[s]Futaba[e]
[s]Akechi[e]
[s][f 4 31 10 1][e]

[msg MSG_Jazz_FRIEND [Morgana]]
[s][bup 0 3 1 0 0][vp 8 2 1 1167 65535 0][f 4 10 65535 0 0]Oh, [var 3], huh?[n][w][e]

[sel SEL_NPC_SELECT top]
[s]Yeah.[e]
[s]Let me think it over.[e]

[msg MSG_FRIEND_NG [Morgana]]
[s][bup 0 3 0 0 0][vp 8 2 1 1185 65535 0][f 4 10 65535 0 0]So who're you gonna invite?[n][w][e]

[msg MSG_Jazzclub_Moru_Bye [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Then I'm gonna take a stroll. Just let[n]me know when we're heading home.[n][w][e]

[msg MSG_Jazzclub_Moru_NotBye [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Wonder if I'd enjoy the cocktails.[n]Guess I'll just have to give it a shot![n][w][e]

[msg MSG_Jazzclub_NoMoney [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]It's gonna cost 3,000 yen.[n]Looks like you don't have enough...[n][w][e]

[msg MSG_KF794101_JazzClub [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7024 65535 0]A jazz club, huh? Looks like some kind of secret[n]hideout for adults.[n][w][e]

[msg MSG_JazzClub_Lock [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]A jazz club... I wonder what kind of[n]place it is down there.[n][w][e]

[msg MND_JazzClub_Lock]
[s]Looks like it's a jazz club...[n][w][e]
[s]I can't even imagine[n]what it's like down there.[n][w][e]

[msg MND_JazzClub_PreStart]
[s]It's the jazz club Akechi showed[n]me... Maybe I should go in.[n][w][e]

[msg MSG_JazzClub_PreStartNot [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]It's the jazz club that Akechi introduced[n]you to, but it looks like it's only open at[n]night.[n][w][e]

[msg MND_JazzClub_PreStartNot]
[s]It's the jazz club[n]Akechi showed me...[n][w][e]
[s]But it's only open at night.[n]I should come back another time.[n][e]

[msg MSG_JazzClub_StartNotNig [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Oh, looks like the jazz club's only open[n]at night.[n][w][e]

[msg MND_JazzClub_StartNotNig]
[s]It seems to be open during the day.[n]Maybe I'll stop by next time.[n][w][e]

[sel SEL_Jazzclub top]
[s]Enter[e]
[s]Cancel[e]

[msg MSG_SYSTEM_SHORTCUT_JUZZ]
[s]You can now quick travel to the[n][clr 6]Jazz Club[clr 0] in Kichijoji.[n][w][e]

[msg MSG_JazzClub_Alpha [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]※本来は明智コープランク3で解禁しますが、[n] α1では強制的に解禁状態にします[n][w][e]

[msg MSG_Accessories_Start [Crystal Healing Employee]]
[s][vp 8 2 1 0 4 0]Welcome! Please take a look at what[n]we have![n][w][e]

[msg MSG_Accessories_THANKS [Crystal Healing Employee]]
[s][vp 8 2 1 0 4 0]Thank you! Please come again![n][w][e]

[msg MSG_Accessories_NOT_BUY [Crystal Healing Employee]]
[s][vp 8 2 1 0 4 0]Oh, is that right? Please do come again![n][w][e]

[msg MSG_KF794101_Variety [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]An Incense Shop? Seems totally fishy[n]to me.[n][w][e]

[msg MSG_Variety_Start [Incense Shop Staff]]
[s][vp 8 2 1 0 3 0]Ah, a customer! Please enjoy our special[n]perfumes![n][w][e]

[msg MSG_Variety_THANKS [Incense Shop Staff]]
[s][vp 8 2 1 0 3 0]Thanks again![n][w][e]

[msg MSG_Variety_NOT_BUY [Incense Shop Staff]]
[s][vp 8 2 1 0 3 0]Please come again some time![n][w][e]

[msg MSG_Variety_NotOpen [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Wh-Whoa, the smell...[n]I don't know if my nose can handle this.[n][w][e]
[s][f 4 10 65535 0 0]I didn't know you were into incenses...[n]If you're not, let's get outta here.[n][w][e]

[msg MSG_FoodShop_NotInfo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]They're selling a lot of stuff from foreign[n]countries. Man, I wanna go to one of[n]those some day...[n][w][e]

[msg MSG_FoodShop_NotInfo_Aft [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Looks like they sell a lot of stuff from[n]different countries. So what was main[n]thing they sold in Hawaii?[n][w][e]

[msg MND_FoodShop_NotInfo_Aft]
[s]It looks like they mainly[n]sell imported groceries.[n][w][e]
[s]There's nothing I need from here.[n][w][e]

[msg MSG_FoodShop_Start [Grocery Clerk]]
[s][vp 8 2 1 0 4 0]Welcome! Please feel free to enjoy[n]the tastes of countries the world over![n][w][e]

[msg MSG_FoodShop_THANKS [Grocery Clerk]]
[s][vp 8 2 1 0 4 0]Thank you very much! Please come again![n][w][e]

[msg MSG_FoodShop_NOT_BUY [Grocery Clerk]]
[s][vp 8 2 1 0 4 0]Thanks again![n][w][e]

[msg MSG_Stationer_Start [Stationery Store Employee]]
[s]Hello and welcome. We have plenty[n]of items here you can gift to others.[n][w][e]

[msg MSG_Stationer_THANKS [Stationery Store Employee]]
[s]Thank you for your purchase![n]We look forward to your next visit.[n][w][e]

[msg MSG_Stationer_NOT_BUY [Stationery Store Employee]]
[s]Please come again.[n][w][e]

[msg MSG_OldClothe_NotOpen_No [Secondhand Clothes Employee]]
[s]Oh, hello... You looking to sell clothing?[n][w][e]
[s]Huh... They all look pretty normal...[n]We already have clothing like that in[n]this store.[n][w][e]

[msg MSG_OldClothe_NotOpen_No_2 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1026 65535 0]Oh, what? He's not gonna buy it from[n]us? Do you have anything different?[n][w][e]

[msg MSG_OldClothe_NotOpen_No_3 [Secondhand Clothes Employee]]
[s]I'm looking more for [clr 2]sooty clothes[clr 27]...[n]You know, like they're almost trash.[n]If only I could find clothing like that...[n][w][e]

[msg MSG_OldClothe_NotOpen_No_4 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Well, it is said that aged meat does taste[n]better... Maybe it's the same for clothes?[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]He said something about [clr 2]sooty clothing[clr 27]...[n]Let's come back here again when we have[n]some.[n][w][e]

[msg MSG_OldClothe_NotOpen_Ye [Secondhand Clothes Employee]]
[s]Welcome, if you're looking to sell[n]clothing— W-Wait, what's that?[n][w][e]
[s]Can I take a look at that? Don't worry,[n]I won't steal it.[n][w][e]

[msg MSG_OldClothe_NotOpen_Ye_2 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]This guy's reacting to clothing that we[n]got from Shadows... Seems he knows[n]what he's talking about.[n][w][e]

[msg MSG_OldClothe_NotOpen_Ye_3 [Secondhand Clothes Employee]]
[s]I've been here for 40 years, but I've never[n]seen clothing that makes my heart chill...[n][w][e]
[s]All right, I'll buy it. But I'll only buy it for[n]the price it deserves.[n][w][e]
[s]So we have a point card system here.[n]Each [clr 2]piece of clothing[clr 27] you sell here will[n]give you [clr 2]10 points[clr 27].[n][w][e]
[s]Once you obtain enough points, you can[n]trade them for a prize. So feel free to let[n]us take that clothing off your hands.[n][w][e]

[msg MSG_OldClothe_NotOpen_Ye_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Not only is he gonna buy them from us,[n]he's gonna give us points for them too?[n]We should definitely come back here.[n][w][e]

[msg MSG_OldClothe_Start [Secondhand Clothes Employee]]
[s]So what can I do for ya?[n][w][e]

[msg MSG_OldClothe_Start_loop [Secondhand Clothes Employee]]
[s]Anything else?[n][w][e]

[sel SEL_OldClothe_bunki top]
[s]I want to sell.[e]
[s]Let me see the prizes.[e]
[s]Nothing.[e]

[msg MSG_OldClothe_SelCancel [Secondhand Clothes Employee]]
[s]No? Well, that's too bad...[n][w][e]

[msg MSG_OldClothe_Start_NotH [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Hey, you don't have any clothes to sell[n]right now.[n][w][e]

[msg MSG_OldClothe_AnySell [Secondhand Clothes Employee]]
[s]So you sold [var 2] pieces of clothing...[n]Hm, that'll get you [clr 2][var 0][clr 27] points.[n][w][e]
[s]And now you've got [clr 2][var 1][clr 27] points.[n][w][e]

[msg MSG_OldClothe_give_end [Secondhand Clothes Employee]]
[s]If you want more points, just sell the[n]clothes you got.[n][w][e]

[msg MSG_OldClothe_give_end_s [Secondhand Clothes Employee]]
[s]I hope you liked the stuff we had in[n]the store.[n][w][e]
[s]If you want more points, just sell the[n]clothes you got.[n][w][e]

[msg MSG_OldClothe_Bey [Secondhand Clothes Employee]]
[s]These clothes are amazing...[n]Come again, all right?[n][w][e]

[msg MSG_OldClothe_Bey_Nosell [Secondhand Clothes Employee]]
[s]Come sell us more stuff, okay?[n]I'll be waiting.[n][w][e]

[msg MSG_Hurugi_Start [Morgana]]
[s][bup 0 3 11 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]I always wanna know what's inside this[n]stuff. Let's take a look![n][w][e]

[msg MSG_Hurugi_end [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Not too bad. Let's get this again some time.[n][w][e]

[msg MSG_Temple_Night [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Doesn't look like the temple accepts[n]people at night. Let's try coming back[n]here during the [clr 2]daytime[clr 27].[n][w][e]

[msg MSG_Temple_Daily [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]I bet having a temple in a shopping[n]district really helps the businesses.[n][w][e]

[msg MND_Temple_Night]
[s]Looks like they don't accept[n]people at night. I should come[n]back during the [clr 2]daytime[clr 27]...[n][w][e]

[msg MSG_Temple_1st_info [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Whoa. To think there'd be a temple[n]inside a city.[n][w][e]
[s][f 4 10 65535 0 0]Hey, check out the sign. "In order to[n]gain a fulfilling life, you must first start[n]by understanding yourself."[n][w][e]
[s][f 4 10 65535 0 0]Meditating at the temple, huh? Looks[n]like you can do so during the daytime.[n][w][e]

[msg MSG_Temple_NotHaveCard [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Oh, you're not gonna stop by?[n][w][e]

[msg MSG_Temple_AskUse_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Maybe if you meditate and calm your[n]mind, you'll be able to learn something.[n][w][e]

[msg MSG_Temple_AskUse_002 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]What's the plan? Are you gonna meditate[n]at the temple?[n][w][e]

[sel SEL_TempleUse top]
[s]Let's check it out.[e]
[s]See my current status.[e]
[s]Not right now.[e]

[msg SYS_ShortCut_Temple]
[s]You can now quick travel to[n]the [clr 6]Temple[clr 0] in Kichijoji.[n][w][e]

[msg MSG_Cafe [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]What a fancy looking café. If I ever were[n]to invite Lady Ann somewhere— Why're[n]you looking at me like that?[n][w][e]

[msg MND_Cafe]
[s]It's a fancy looking café.[n][w][e]
[s]It looks like their specialty[n]is home roasted espressos.[n][w][e]

[msg MSG_Shop_Megane [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Your glasses are fake, right? It's hard to[n]tell unless you look at 'em real closely...[n][w][e]

[msg MND_Shop_Megane]
[s]......[n][w][e]
[s]My glasses are fake.[n]I don't need to change them.[n][w][e]

[msg MSG_KF794101_Deadend_mea [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Looks like there're just stores down on[n]this side.[n][w][e]

[msg MSG_Deadend_meat [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Looks like the interesting stores are back[n]there. Let's go back.[n][w][e]

[msg MND_Deadend_meat]
[s]There isn't anything that[n]interests me. I should go back.[n][w][e]

[msg MSG_KF794101_Deadend_Iza [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7028 65535 0]Damn it, I just hit my elbow. Why's this[n]place in such a small space?[n][w][e]

[msg MSG_Deadend_Izakaya [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Dang, looks like a dead end. It's like a[n]maze here.[n][w][e]

[msg MND_Deadend_Izakaya]
[s]It's a dead end...[n][w][e]

[msg MSG_KF794101_Deadend_Meg [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]That place we're lookin' for should be[n]around here. Let's turn back.[n][w][e]

[msg MSG_Deadend_Megane [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]I don't see anything interesting past here.[n]Let's turn back.[n][w][e]

[msg MND_Deadend_Megane]
[s]There's nothing that[n]I need to do up ahead.[n][w][e]

[msg MSG_KF794101_Deadend_Caf [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]There aren't a lotta stores anymore, huh.[n]Let's go back.[n][w][e]

[msg MSG_Deadend_Cafe [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Looks like this area has more houses[n]than stores...[n][w][e]

[msg MND_Deadend_Cafe]
[s]Looks like it's more of a[n]residential area past here.[n][w][e]

[msg MSG_KF794101_Deadend_Jaz [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7029 65535 0]This area's got more shops for adults.[n]Let's look somewhere else.[n][w][e]

[msg MSG_Deadend_Jazz [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Looks like there's more mature stores[n]around here... Let's head back.[n][w][e]

[msg MND_Deadend_Jazz]
[s]This area has more mature stores...[n][w][e]
[s]Let's go back.[n][w][e]

[msg MSG_VELVET_GIRL_LOUD01 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 2 1 11018 65535 0]You don't have time to be playing[n]around, Inmate![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hurry back to your prison![n][w][e]

[msg MSG_VELVET_GIRL_Lavenza [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55422 65535 0]These trials... I believe that you can[n]overcome them.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_VELV]
[s]You can now quick travel to the[n][clr 6]Velvet Room[clr 0].[n][w][e]

[msg MSG_Dagashi_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Check out what's in these showcases...[n][w][e]
[s]A Kichijoji special, "Dorayaki with[n]chestnuts and red bean paste"?[n]Sounds more like a hamburger...[n][w][e]

[msg MND_Dagashi_001]
[s]"Dorayaki with chestnuts[n]and red bean paste."[n][w][e]
[s]...It sounds like a hamburger.[n][w][e]

[msg MSG_Dagashi_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]It's already closed, but do you smell[n]that sweet scent?[n][w][e]

[msg MND_Dagashi_heiten]
[s]I can smell the sweet scent[n]of chestnuts from here...[n][w][e]

[msg MSG_Bank_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]It's a bank. You know, I've always[n]wondered why they call it that...[n][w][e]

[msg MND_Bank_001]
[s]There's nothing I need[n]to do at the bank...[n][w][e]

[msg MSG_Bank_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Looks like the bank's closed... I mean,[n]it is outside of business hours. Well,[n]not like we have to use it anyways.[n][w][e]

[msg MND_Bank_heiten]
[s]The bank is currently closed...[n][w][e]
[s]But it looks like there're still some[n]employees working...[n][w][e]

[msg MSG_HatShop_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]It's a hat store for the elderlies.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Why don't you wear a hat to smush in[n]your curly hair?[n][w][e]

[msg MND_HatShop_001]
[s]It's a hat store for the elderlies.[n][w][e]
[s]...Maybe I'll wear a hat one day.[n][w][e]

[msg MSG_HatShop_heiten [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]All you see are shutters at night...[n]It feels a bit lonely.[n][w][e]

[msg MSG_Taiyaki_Open [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]C'mon, they call it a fish, but it's only[n]taiyaki, right? Do you think I'd really[n]be satisfied with— Hm?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]"We will provide a fresh and organic[n]piece every time." Can taiyaki even[n]be fresh and organic?[n][w][e]

[msg MND_Taiyaki_Open]
[s]"We will provide a fresh and[n]organic piece every time."[n][w][e]
[s]They must have a specific[n]way they're making it...[n][w][e]

[msg MSG_Taiyaki_Close [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Why do you think they chose a red[n]snapper for the fish? It could've been[n]any fish, right?[n][w][e]

[msg MSG_TelephoneShop_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Oh, are you gonna buy me a cell phone?[n]Be sure to get me the newest one, all right?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]...Just kidding. I'm leaving the[n]communication with the other guys[n]to you.[n][w][e]

[msg MND_TelephoneShop_001]
[s]"Water resistant, huge screen, high[n]capacity, 4K compatible!" Looks like[n]they're advertising the new phone.[n][w][e]
[s]I'm fine with the one I have now.[n][w][e]

[msg MSG_TelephoneShop_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Have you seen those cell phones with[n]cracks on the screen?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]I wonder if it can cut your finger.[n]I feel like it would just fall right off...[n][w][e]

[msg MSG_IceShop_001 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Coffee, strawberry, green tea... Looks like[n]they have all kinds of flavors.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Oh! How about sushi-flavored ice cream?[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]...Never mind. I almost threw up just[n]thinking about it...[n][w][e]

[msg MND_IceShop_001]
[s]There's a lot of different[n]flavored ice cream.[n][w][e]
[s]Maybe I should come[n]here with someone.[n][w][e]

[msg MSG_IceShop_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Do you know the difference between soft[n]serve ice cream and regular ice cream?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]'Cause I've got no clue.[n][w][e]

[msg MSG_Realtor_Sofa_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Huh, check out that comfy looking sofa...[n]What're you doing sitting on it?[n][w][e]

[msg MND_Realtor_Sofa_001]
[s]It's a comfy looking sofa...[n][w][e]

[sel SEL_sofa top]
[s]Just a little bit longer...[e]
[s]Let's get going.[e]

[msg MSG_Realtor_Sofa_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]What, is it really that comfortable? I mean[n]if it's in front of the store like this I guess[n]it must be comfy...[n][w][e]
[s]Okay, let's get going.[n][w][e]

[msg MSG_Realtor_Sofa_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Really? Just how comfortable is this sofa...?[n][w][e]
[s]...Hey.[n][w][e]
[s]...Hellooo.[n][w][e]
[s]Man, everyone's looking at you...[n]I guess I'd call you bold for doing this.[n][w][e]

[msg MSG_Realtor_Sofa_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]All right, let's go.[n][w][e]

[msg MSG_Realtor_Sofa_End [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Okay, I get you really like this sofa. Let's[n]get it when you get your own place, all[n]right?[n][w][e]

[msg MSG_Realtor_Sofa_End_Fau [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]There're a lot of things to do. We've got[n]no time to be relaxing.[n][w][e]

[msg MSG_Realtor [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1186 65535 0]Do you wanna just get a new sofa for your[n]room? Maybe with the money I have...[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]Whoa, check out the price...[n]Never mind what I said before...[n][w][e]

[msg MND_Realtor]
[s]Maybe I could get some new furniture...[n][w][e]
[s]......[n][w][e]
[s]Doesn't look like I'll ever[n]have enough money for it...[n][w][e]

[msg MSG_Realtor_Yoru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]It's closed...[n][w][e]
[s][f 4 10 65535 0 0]With a shutter this big, it's almost[n]intimidating.[n][w][e]

[msg MSG_Realtor_Chair [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Huh, don't you think this chair's perfect[n]for me?[n][w][e]

[msg MND_Realtor_Chair]
[s]This chair's completely hand made...[n][w][e]
[s]There's a scent of varnish.[n][w][e]

[msg MSG_Fudousan [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Huh, check out the price for a one[n]bedroom... Guess it's expected in Kichijoji.[n][w][e]
[s]Wait, hold on... I think Yongen-Jaya is[n]pretty up there, too.[n][w][e]
[s]You might actually be living in a pretty[n]good area.[n][w][e]

[msg MND_Fudousan]
[s]It says,[n]"We'll help you find your home!"[n][w][e]
[s]Though I don't plan to rent[n]a house any time soon.[n][w][e]

[msg MSG_Karaoke [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]"Discounts for families and seniors!"[n]I think it's a little too early for you guys...[n][w][e]

[msg MND_Karaoke]
[s]"Includes various enka ballads!"[n][w][e]
[s]I wonder if there are songs I know...[n][w][e]

[msg MSG_RecordShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]These are pretty big CDs... Huh? Records?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]I bet with it being this big, the sound[n]quality's pretty good.[n][w][e]

[msg MND_RecordShop]
[s]It's a record shop...[n][w][e]
[s]I wouldn't have a way to play it,[n]even if I bought one.[n][w][e]

[msg MSG_MusicTool [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]That looks like an expensive violin. Huh?[n]It's a contrabass?[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]How about that one? A cello? And that[n]one's a viola? I'm so confused...[n][w][e]

[msg MND_MusicTool]
[s]All the instruments are so[n]expensive. I wonder how much[n]the maintenance fees are...[n][w][e]

[msg MSG_MusicTool_Yoru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]It's so cool that there're so many types[n]of instruments.[n][w][e]
[s][f 4 10 65535 0 0]Isn't it amazing that music can move[n]people to tears, with no words?[n][w][e]

[msg MSG_Pasta [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1155 65535 0]We recommend the pappardelle and[n]orecchiette. Try our cappelletti and[n]agnolotti as well...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]I did it... I said it without stopping![n][w][e]

[msg MND_Pasta]
[s]"We recommend the pappardelle[n]and orecchiette. Try our cappelletti[n]and agnolotti as well."[n][w][e]
[s]...I wonder what they all look like.[n][w][e]

[msg MSG_Pasta_Error [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1155 65535 0]We recommend the pappardelle and[n]orecchiette. Try our cappellitt—[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]...I just bit my tongue.[n][w][e]

[msg MSG_EthnicCafe [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]A revolving sushi restaurant is a mysterious[n]place, isn't it? I mean, why would the sushi[n]be revolving...?[n][w][e]

[msg MND_EthnicCafe]
[s]I can see the sushi moving[n]along the lanes.[n][w][e]

[msg MSG_Japanese_TeaHouse [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Oh, check out that menu up there.[n]"Shaved ice made from natural water."[n][w][e]
[s][f 4 10 65535 0 0]I wonder how different it is from faucet[n]water. What type of water does the chief[n]use...?[n][w][e]

[msg MND_Japanese_TeaHouse]
[s]"A photogenic natural shaved ice."[n][w][e]
[s]I can hear voices of girls[n]from past the stairs.[n][w][e]

[msg MSG_Japanese_TeaHouse_he [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]How do you read the name of this[n]shop...? Is it "Yamayuki" or "Sansetsu"?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]I wonder why they call it "snowy[n]mountain."[n][w][e]

[msg MSG_SocksShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Huh, they have socks for dogs?[n]But none for cats?[n][w][e]
[s][f 4 10 65535 0 0]Well, it's not like I need to wear socks...[n]I bet they'd look good on me though.[n][w][e]

[msg MND_SocksShop]
[s]The socks I brought are just fine.[n][w][e]

[msg MSG_SocksShop_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Looks like all the stores are closed at this[n]time. It's a bit quiet...[n][w][e]

[msg MSG_MajorCafe [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]※レストラン ヒット自体をカット予定 [n][w][e]

[msg MSG_MajorCafe_Yoru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]※レストラン ヒット自体をカット予定 [n][w][e]

[msg MND_MajorCafe]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]※レストラン ヒット自体をカット予定 [n][w][e]

[msg MSG_EthnicShop [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]They have masks from various countries.[n]It's a bit intimidating.[n][w][e]

[msg MND_EthnicShop]
[s]They have general stuff[n]from Asian countries.[n][w][e]
[s]They all seem unique.[n][w][e]

[msg MSG_CoinLocker [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]So you can unlock these lockers if you[n]have the right receipt, huh?[n][w][e]
[s][f 4 10 65535 0 0]Looks like they're all taken though.[n]I guess it's 'cause there're a lot of tourists.[n][w][e]

[msg MND_CoinLocker]
[s]All the lockers are taken...[n][w][e]

[msg MSG_Bicycle [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Oh, the bicycles here look really easy[n]to carry.[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]Hm. There's nowhere for me to sit[n]and ride...[n][w][e]

[msg MND_Bicycle]
[s]It's a light bicycle.[n][w][e]
[s]They probably removed the[n]basket in order to keep it light.[n][w][e]

[msg MSG_Bicycle_heiten [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Maybe one day we can go on a trip with[n]a bicycle. It'll probably be fun, even if we[n]get lost.[n][w][e]

[msg MSG_ToyShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Check out all the wooden toys... They[n]import them from foreign countries, huh?[n][w][e]
[s][f 4 10 65535 0 0]Oh, that black cat doll...[n]It's just like me—full of elegance.[n][w][e]

[msg MND_ToyShop]
[s]Looks like they have wooden toys.[n][w][e]
[s]I don't have any reasons to buy one.[n][w][e]

[msg MSG_ToyShop_heiten [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Wooden toys seem to have such class...[n]I sure wouldn't complain if I got one.[n][w][e]

[msg MSG_SportsShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]For mountain girls and beach girls...[n]Looks like they have a whole bunch[n]of outdoor stuff.[n][w][e]
[s][f 4 10 65535 0 0]How about some cat girls... Wait, how[n]would that even look?[n][w][e]

[msg MSG_SportsShop_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]You think the wall's green 'cause it's[n]supposed to look like the mountains?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Actually, never mind. There wouldn't be[n]anything to represent the sea or sky...[n][w][e]

[msg MND_SportsShop]
[s]They're selling a lot[n]of outdoor products.[n][w][e]

[msg MSG_WineBar [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Hey, check out that giant chunk of cheese![n][w][e]
[s][f 4 10 65535 0 0]Oh, it's fake... Well, I guess that was a[n]given. But it still does look pretty real.[n][w][e]

[msg MND_WineBar]
[s]"We have 100 types of wine."[n][w][e]
[s]Maybe I'll stop by once[n]I'm old enough.[n][w][e]

[msg MSG_WineBar_Yoru [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Aren't beer and wine both alcohol?[n]They're not really good for you...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]But I guess some people can't resist, right?[n][w][e]

[msg MSG_SteakFood [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]"Try our 40-day-aged, A5-rank meat![n]Savor meat that melts in your mouth."[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Oh crap, sorry. Some of my drool[n]just dripped on your shoulder...[n][w][e]

[msg MND_SteakFood]
[s]"Try our 40-day-aged, A5-rank meat![n]Savor meat that melts in your mouth."[n][w][e]
[s]I wonder what it's like...[n][w][e]

[msg MSG_AntiqueStore [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Dang, I thought there was a tree growing[n]in that store, but it was just a clock.[n][w][e]

[msg MND_AntiqueStore]
[s]There seems to be a lot of antiques[n]in this store. Wait, is that...[n][w][e]
[s]At first glance, I thought it was a[n]painting, but it was a table...[n][w][e]

[msg MSG_AntiqueStore_Yoru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]When you say the word antique, I feel[n]like it gives the item more value.[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]How about Leblanc? Is that retro?[n]Or is it antique...[n][w][e]
[s][f 4 10 65535 0 0]Wow. The term antique is pretty deep...[n][w][e]

[msg MSG_DonutShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]I think I just realized something.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Don't you think we're missing out[n]without the center part of the donut?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]But I guess the first shape that comes[n]to mind when you imagine a donut is[n]this one...[n][w][e]

[msg MND_DonutShop]
[s]I can smell the sweet[n]scent of donuts.[n][w][e]

[msg MSG_DonutShop_Quiz_001 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Here's a pop quiz.[n][w][e]
[s][f 4 10 65535 0 0]How many donuts do you think this[n]sign has...?[n][w][e]

[msg MSG_DonutShop_Quiz_Re [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]All right, now how many donuts are[n]on this sign?[n][w][e]

[sel SEL_Donut_01 top]
[s]...9[e]
[s]...10?[e]
[s]Hold on.[e]

[msg MSG_DonutShop_Quiz_Commo [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Mewhehe... Are you sure about that?[n][w][e]

[sel SEL_Donut_02 top]
[s]It should be 9.[e]
[s]Hold on.[e]

[sel SEL_Donut_03 top]
[s]It should be 10.[e]
[s]Hold on.[e]

[msg MSG_DonutShop_Quiz_Commo_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Do you think you got it right?[n][w][e]
[s][f 4 10 65535 0 0]The answer is...![n][w][e]

[msg MSG_DonutShop_Quiz_NG [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1036 65535 0]Nope! Too bad! The answer's 10![n][w][e]
[s][f 4 10 65535 0 0]Did you see the donut on the left?[n]That counts as one.[n][w][e]

[msg MSG_DonutShop_Quiz_OK [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1045 65535 0]Congratulations! You're correct![n]The answer's 10![n][w][e]
[s][f 4 10 65535 0 0]Looks like you noticed that donut on[n]the left. They put a donut there too, huh.[n][w][e]

[msg MSG_DonutShop_Quiz_Commo_3 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Sorry to poke fun at you. But wasn't it[n]pretty exciting?[n][w][e]

[msg MSG_DonutShop_Quiz_Cance [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Heheh. I bet you're gonna double check[n]now... Am I right?[n][w][e]

[msg MSG_DonutShop_Quiz_End_N [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Remember that donut quiz? Hehe, I still[n]remember that you got it wrong.[n][w][e]

[msg MSG_DonutShop_Quiz_End_O [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Remember that donut quiz?[n]I'm pretty surprised you got it right.[n][w][e]

[msg MSG_Tobari01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]The scent of the radish in the soup...[n]It gives me a warm feeling inside.[n][w][e]

[msg MND_Tobari01]
[s]The radish in the oden[n]is being boiled...[n][w][e]

[msg MSG_Tobari02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]There're so many different kinds of[n]alcohol. Just like coffee beans.[n][w][e]
[s][f 4 10 65535 0 0]But still, look at the names...[n]Some of them seem so violent.[n][w][e]

[msg MND_Tobari02]
[s]There are alcoholic beverages[n]displayed in a small area.[n][w][e]

[msg MSG_Tobari03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Look how much stuff they have, and in[n]such a small place... But don't you think[n]small spaces help you relax?[n][w][e]

[msg MND_Tobari03]
[s]...They used their small[n]space really well.[n][w][e]

[msg MSG_Tobari04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]How the heck are they going to cook in[n]such a small place?[n][w][e]
[s][f 4 10 65535 0 0]Hold on a sec. I think Leblanc's kitchen is[n]even smaller. Hats off to the chief...[n][w][e]

[msg MND_Tobari04]
[s]I smell something salty.[n][w][e]

[msg MSG_Tobari05 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Whoa! They have sushi too!? I can't look[n]at it. Wait no, it just looks so good...[n][w][e]

[msg MND_Tobari05]
[s]It's a bar that also serves sushi.[n][w][e]

[msg ChineseMan_Start [Chinese Bun Shop Employee]]
[s][vp 8 2 1 0 5 0]Hey welcome! We're selling our hot[n]and fresh Chinese buns here![n][w][e]

[msg ChineseMan_NOT_BUY [Chinese Bun Shop Employee]]
[s][vp 8 2 1 0 5 0]Please come again![n][w][e]

[msg ChineseMan_THANKS [Chinese Bun Shop Employee]]
[s][vp 8 2 1 0 5 0]Thanks! Come again![n][w][e]

[msg MSG_Tobari07 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]You can put tomato in oden? I wonder[n]if the soup becomes red from it.[n][w][e]

[msg MND_Tobari07]
[s]There're tomatoes in the oden.[n][w][e]
[s]I wonder what it tastes like.[n][w][e]

[msg MSG_Tobari08 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Now that I look at it, there's a second floor.[n]They really do cram everything in...[n][w][e]

[msg MND_Tobari08]
[s]They even have stores[n]on the second floor.[n][w][e]

[msg MSG_Tobari09 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Local dishes... I mean, you can get[n]everything in the city. What local[n]dishes are they talking about?[n][w][e]

[msg MND_Tobari09]
[s]Local dishes...[n][w][e]
[s]I wonder what they have here.[n][w][e]

[msg MSG_Tobari10 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Oh hey, I saw a drunk guy in Yongen-Jaya.[n][w][e]
[s][f 4 10 65535 0 0]He was so out of it, I could barely look[n]at him.[n][w][e]

[msg MND_Tobari10]
[s]It's a bar where you can[n]drink while standing.[n][w][e]
[s]I wonder how they[n]don't get tired...[n][w][e]

[msg MSG_Tobari11 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Don't you think ramen's the best thing[n]to eat at the end of the day? I guess[n]porridge wouldn't be so bad either.[n][w][e]

[msg MND_Tobari11]
[s]I can smell ramen...[n][w][e]
[s]The smell is automatically[n]making me feel hungry.[n][w][e]

[msg MSG_Tobari12 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]So after passing the alcohol area, you[n]get to a pretty stylish street. Each area's[n]so different...[n][w][e]

[msg MND_Tobari12]
[s]There're a lot of fancy items.[n][w][e]

[msg MSG_Tobari13 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Ahh, the smell of the fried chicken.[n]Hey, so what's the difference between[n]this and tempura?[n][w][e]

[msg MND_Tobari13]
[s]I can smell the delicious[n]fried chicken.[n][w][e]

[msg MSG_Tobari14 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Oh, huh. They have tatami in there?[n]I bet it's really comfy...[n][w][e]

[msg MND_Tobari14]
[s]There're tatami laid out inside.[n][w][e]
[s]...Seems really comfortable.[n][w][e]

[msg MSG_Tobari15 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Seeing barrels like that reminds me[n]of Kamoshida's Palace.[n][w][e]

[msg MND_Tobari15]
[s]It's a sake cask.[n][w][e]
[s]How did they get them here...?[n][e]

[msg MSG_Tobari16 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]So, there're two types of wings. There's[n]the regular wing and the wing sticks.[n]Didn't think there'd be so many choices.[n][w][e]

[msg MND_Tobari16]
[s]I can smell the savory[n]sauce and chicken.[n][w][e]

[msg MSG_Tobari_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]I guess these places don't open until[n]nighttime.[n][w][e]

[msg MND_Tobari_heiten]
[s]It looks like these places[n]don't open 'til night.[n][w][e]

[msg MSG_DeadEnd_Seacret [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]There're so much stuff here...[n][w][e]

[msg MND_DeadEnd_Seacret]
[s]I have nothing to[n]do past this area.[n][w][e]

[msg MSG_Udon_Open [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]A place where you can eat udon while[n]standing, huh?[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]You can choose from so many toppings.[n]Even when you're in a rush, you still have[n]to select your toppings carefully.[n][w][e]

[msg MND_Udon_Open]
[s]It's a place where you can[n]stand and eat udon.[n][w][e]
[s]There're so many toppings...[n][w][e]

[msg MND_COMMON_NG_MACHINE_00]
[s][vp 1 0 0 0 0 0]I don't have time to take[n]a break and buy drinks now.[n][w][e]

[msg MND_E10410100_NG_MACHINE]
[s][vp 1 0 0 0 0 0]I'm not thirsty right now.[n][w][e]

[msg MND_E10920100_NG_MACHINE]
[s][vp 1 0 0 0 0 0]Right now, I just don't have[n]the time to quench my thirst.[n][w][e]

[msg MSG_E27930100_NG_MACHINE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Can we do that later? We need to get info[n]on Futaba first.[n][w][e]

[msg MSG_E79310100_NG_MACHINE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Hey, you don't have time to take a break[n]and buy drinks.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Hurry up and take us to the clinic.[n][w][e]

[msg MSG_KF_Dagashi_mes01 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Whoa! Take a look at the showcase dude![n][w][e]

[msg MSG_KF_Dagashi_mes02 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]A Kichijoji special, "Dorayaki with[n]chestnuts and red bean paste"? It[n]almost looks like a hamburger...[n][w][e]

[msg MSG_KF_Dagashi_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7020 65535 0]"Dorayaki with chestnuts and red bean[n]paste." They really just throw all the tasty[n]stuff together, huh...[n][w][e]

[msg MSG_KF_HatShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1021 65535 0]A hats-only store, huh? They've got so[n]many of 'em.[n][w][e]

[msg MSG_KF_HatShop_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]How many heads could this store cover...[n][w][e]

[msg MSG_KF_HatShop_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Maybe I'll try on a hat sometime.[n][w][e]

[msg MSG_KF_Stationer_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1165 65535 0]My Morgana senses are telling me that[n]this store... sells a lot of stuff that suits[n]my taste![n][w][e]

[msg MSG_KF_Stationer_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]What the hell are Morgana senses...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7079 65535 0]Well, let's take a look.[n][w][e]

[msg MSG_KF_Stationer_mes03 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]That employee dude was sayin' somethin'[n]about how their stuff makes good gifts,[n]yeah?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]I guess it'd be pretty cool to get a gift[n]from here.[n][w][e]

[msg MSG_KF_Stationer_mes04 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I didn't think you'd actually buy somethin'.[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Did your senses tell you to get one?[n][w][e]

[msg MSG_KF_TelephoneShop_mes [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7085 65535 0]There're so many types of phones,[n]but I feel like they all look the same.[n][w][e]

[msg MSG_KF_TelephoneShop_mes_2 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Man, I want a phone of my own.[n]Preferably the newest one out there![n][w][e]

[msg MSG_KF_TelephoneShop_mes_3 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Water resistant, huge screen, high[n]capacity, 4K compatible! Man, can[n]you believe how far technology's goin'?[n][w][e]

[msg MSG_KF_OldClothesShop_me [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7155 65535 0]Oh, dude! Check out that sign in the store.[n]It says, "Bring your sooty clothing here!"[n][w][e]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]...Sooty clothes?[n][w][e]

[msg MSG_KF_OldClothesShop_me_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1020 65535 0]Heh, let's see what they've got![n][w][e]

[msg MSG_KF_OldClothesShop_me_3 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]W-Well, that was kind of a weird store...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]But I guess it was pretty fun.[n]Let's check it out again sometime.[n][w][e]

[msg MSG_KF_IceShop_mes01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Coffee, strawberry, green tea... Looks like[n]they have all kinds of flavors.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Oh! How about sushi-flavored ice cream?[n][w][e]

[msg MSG_KF_IceShop_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7025 65535 0]Shut up, Morgana! Ugh, I just imagined[n]what it'd taste like![n][w][e]

[msg MSG_KF_IceShop_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]They've got double scoops and triple[n]scoops, too. I wonder how many scoops[n]you can put on one cone...[n][w][e]

[msg MSG_KF_Fudousan_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1133 65535 0]Huh, check out the price for a one[n]bedroom... Guess it's expected in Kichijoji.[n][w][e]

[msg MSG_KF_Fudousan_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Dude, you're a cat. Rent shouldn't even[n]matter to you.[n][w][e]

[msg MSG_KF_Fudousan_mes03 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 23046 65535 0]I'm not a cat![n][w][e]

[msg MSG_KF_Fudousan_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7174 65535 0]You'd have to pay this amount every[n]month, right? Damn, it sure costs a lotta[n]money to live on your own...[n][w][e]

[msg MSG_KF_Bank_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7088 65535 0]Dude, why're there always banks near the[n]station? I mean, I don't go there often so it[n]doesn't really matter to me, but...[n][w][e]

[msg MSG_KF_Bank_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]It's a bank. You know, I've always[n]wondered why they call it that...[n][w][e]

[msg MSG_KF_Bank_mes03 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Maybe it's 'cause some guy named Bank[n]came up with the idea.[n][w][e]

[msg MSG_KF_Bank_mes04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1028 65535 0]Uh, that's definitely not it...[n][w][e]

[msg MSG_KF_Bank_mes05 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7046 65535 0]Damn it, freakin' Morgana.[n][w][e]

[msg MSG_KF_Bank_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]I wonder why there're so many different[n]types of banks...[n][w][e]

[msg MSG_KF_EthnicCafe_mes01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]A revolving sushi restaurant is a mysterious[n]place, isn't it? I mean, why would the sushi[n]be revolving...?[n][w][e]

[msg MSG_KF_EthnicCafe_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Heh, I wanna try expensive sushi[n]that's not revolvin' one of these days.[n][w][e]

[msg MSG_KF_EthnicCafe_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]Revolvin' sushi ain't bad, but I wanna[n]try expensive sushi that's not revolvin'[n]one of these days.[n][w][e]

[msg MSG_KF_Taiyaki_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]C'mon, they call it a fish, but it's only[n]taiyaki, right? Do you think I'd really[n]be satisfied with this?[n][w][e]

[msg MSG_KF_Taiyaki_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]But check out what it says: "We will[n]provide a fresh and organic piece every[n]time." Sounds pretty badass...[n][w][e]

[msg MSG_KF_Taiyaki_mes03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Fresh and organic? Guess we can't[n]judge a fish by its cover...[n][w][e]

[msg MSG_KF_Taiyaki_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]"We will provide a fresh and organic[n]piece every time." What do you think[n]it tastes like?[n][w][e]

[msg MSG_KF_TeaHouse_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]"Shaved ice made with natural water"?[n]So is it different from the water you get[n]from the faucets?[n][w][e]

[msg MSG_KF_TeaHouse_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I heard that when shaved ice was hella[n]popular, people were linin' up even[n]durin' the winter.[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Can't believe people'd eat that stuff[n]during the winter...[n][w][e]

[msg MSG_KF_TeaHouse_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7086 65535 0]"Photogenic natural shaved ice"?[n]I can't believe that shaved ice has[n]come this far.[n][w][e]

[msg MSG_KF_SocksShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1168 65535 0]It's a place that only sells socks. It's quite[n]a sight when all you see are socks...[n][w][e]

[msg MSG_KF_SocksShop_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh yeah, the socks I'm wearin' have holes[n]in 'em. I gotta get myself a new pair.[n][w][e]

[msg MSG_KF_SocksShop_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]They've got socks with characters on[n]them, too.[n][w][e]

[msg MSG_KF_MeatFryShop_mes01 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Holy crap, look at the line! I think I saw[n]this store on TV.[n][w][e]

[msg MSG_KF_MeatFryShop_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, the smell... Looks like their "special[n]meat cutlet" is their most popular item.[n][w][e]

[msg MSG_KF_MeatFryShop_mes03 [Fried Food Shop Staff]]
[s][vp 8 2 1 0 2 0]Sorry, we only have enough of the[n][clr 3]special meat cutlet[clr 27] for the people in[n]line right now.[n][w][e]
[s][vp 8 2 1 0 2 0]Try stopping by at nighttime.[n][w][e]

[msg MSG_KF_MeatFryShop_mes04 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0]Well, I guess we can't do shit if it's[n]this busy...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]But let's keep in mind that we might[n]be able to buy the "special meat cutlet"[n]at [clr 2]night[clr 27]![n][w][e]

[msg MSG_KF_Udon_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1171 65535 0]A place where you can eat udon while[n]standing, huh? They've got so many[n]toppings to choose from.[n][w][e]

[msg MSG_KF_Udon_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]These places are meant for eatin' ASAP,[n]but with this many toppings, you'd spend[n]all your time just decidin' what to get.[n][w][e]

[msg MSG_KF_Udon_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Udon that you can eat while standing.[n]This is what they call fast food, right?[n][w][e]

[msg MSG_KF_Temple_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7086 65535 0]When you look at it up close, it's quite[n]a sight, huh?[n][w][e]

[msg MSG_KF_Temple_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I bet having a temple in a shopping[n]district really helps the businesses.[n][w][e]

[msg MSG_KF_Temple_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]But why's there a temple in a shopping[n]district like this?[n][w][e]

[msg MSG_KF_CoinLocker_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]So you can unlock these lockers if you[n]have the right receipt, huh?[n][w][e]

[msg MSG_KF_CoinLocker_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Y'know, I feel like people tend to forget[n]where they put their shit a lotta the time.[n][w][e]

[msg MSG_KF_CoinLocker_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Looks like they're all taken though.[n]I guess it's 'cause there're a lot of tourists.[n][w][e]

[msg MSG_KF_FoodShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1133 65535 0]They've got food from foreign countries?[n]Some of these look pretty interestin'.[n][w][e]

[msg MSG_KF_FoodShop_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Seems like they've got some rare stuff.[n]Let's check it out![n][w][e]

[msg MSG_KF_FoodShop_mes03 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]It's pretty pricey, huh...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Maybe I'll buy one someday, jus' to see[n]what it tastes like.[n][w][e]

[msg MSG_KF_FoodShop_mes04 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Oh, did you get somethin'?[n]Lemme know what it tastes like, yeah?[n][w][e]

[msg MSG_KF_JuiceMachine01_me [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Oh, you gonna get a drink?[n][w][e]

[msg MSG_KF_JuiceMachine01_me_2 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7156 65535 0]Whoa, I've never seen it sold out.[n][w][e]

[msg MSG_KF_JuiceMachine01_me_3 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7044 65535 0]Looks like everything in this vending[n]machine's sold out.[n][w][e]

[msg MSG_KF_EthnicShop_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0]Don't these stores usually have a weird[n]smell? Man, I'm not a big fan of it...[n][w][e]

[msg MSG_KF_EthnicShop_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]You're such a kid, Ryuji. This is supposed[n]to be an exotic scent.[n][w][e]

[msg MSG_KF_EthnicShop_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]They have masks from various countries.[n]It's a bit intimidating.[n][w][e]

[msg MSG_KF_Karaoke_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1163 65535 0]"Discounts for families and seniors!"[n]I think I hear them singing.[n][w][e]

[msg MSG_KF_Karaoke_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Karaoke's always so cheap during the[n]week. I wonder if they're even makin'[n]money.[n][w][e]

[msg MSG_KF_Karaoke_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7086 65535 0]"Includes various enka ballads!"[n]I bet they're mainly songs that were[n]popular before we were born.[n][w][e]

[msg MSG_KF_Realtor_mes01 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Oh, check out all the stylish furniture.[n][w][e]

[msg MSG_KF_Realtor_mes02 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Do you wanna just get a new sofa for your[n]room? Maybe with the money I have...[n][w][e]

[msg MSG_KF_Realtor_mes03 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Dude, Morgana. Look at the price tag.[n][w][e]

[msg MSG_KF_Realtor_mes04 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 0 1032 65535 0]Oof... I take it back.[n][w][e]

[msg MSG_KF_Realtor_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7024 65535 0]Huh, if I had stuff like this in my room,[n]would I get popular?[n][w][e]

[msg MSG_KF_Realtor_Sofa_mes0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Wh-Whoa, that was so sudden you[n]almost startled me...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]But man, you've got some guts.[n]I'm pretty surprised![n][w][e]

[msg MSG_KF_Realtor_Sofa_mes0_2 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]...All right. I think we all know you got guts.[n]Let's get goin', dude.[n][w][e]

[msg MSG_KF_RecordShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]These are pretty big CDs... Huh? Records?[n][w][e]

[msg MSG_KF_RecordShop_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Y'think it's true that CDs and records[n]sound different?[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I don't think I'd ever be able to tell[n]the difference.[n][w][e]

[msg MSG_KF_RecordShop_mes00 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Records are so cool. If only I had the[n]thing that plays it...[n][w][e]

[msg MSG_KF_Main_MusicTool_me [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Check out all the instruments in there...[n]Maybe I'll give one a try.[n][w][e]

[msg MSG_KF_Main_MusicTool_me_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I bet you'd look good with a trumpet.[n][w][e]

[msg MSG_KF_Main_MusicTool_me_3 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]You're just basin' it off of my hair color,[n]aren't you?[n][w][e]

[msg MSG_KF_Main_MusicTool_me_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]That looks like an expensive violin. Huh?[n]It's a contrabass?[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]How about that one? A cello? And that[n]one's a viola? I'm so confused...[n][w][e]

[msg MSG_KF_JazzClub_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]A jazz club, huh? Seems like a place[n]for adults.[n][w][e]

[msg MSG_KF_JazzClub_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Dude, you get jazz? That's cool.[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Either way, it looks like it's only open[n]at night.[n][w][e]

[msg MSG_KF_JazzClub_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Looks like this jazz club is only open[n]at night.[n][w][e]

[msg MSG_KF_Izakaya06_mes01 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7159 65535 0]Dude, this nikuman looks so much tastier[n]than the ones at convenience stores.[n][w][e]

[msg MSG_KF_Izakaya06_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]It does... Hey, y'guys wanna get one?[n]How about it?[n][w][e]

[msg MSG_KF_Izakaya06_mes03 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7133 65535 0]Napolitan Nikuman and Peppery[n]Nikuman...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Man, I wonder what they taste like![n]I'm totally gonna eat it one of these days![n][w][e]

[msg MSG_KF_Izakaya_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]I guess these places don't open until[n]nighttime.[n][w][e]

[msg MSG_KF_Izakaya_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Wonder what it's like at night...[n]I kinda wanna check it out.[n][w][e]

[msg MSG_KF_Izakaya_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]I heard this area's pretty lively at night.[n]Wonder what it's like.[n][w][e]

[msg MSG_KF_ramen_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7086 65535 0]A ramen shop that's only open at night,[n]huh?[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Dude, those are usually the real good ones.[n][w][e]

[msg MSG_KF_ramen_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Everyone loves ramen so much. I mean,[n]there're even stores that have 2 hour[n]waitin' times, right?[n][w][e]

[msg MSG_KF_ramen_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]The place is closed, but you can still[n]smell the ramen.[n][w][e]

[msg MSG_KF_Variety_mes01 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]An incense store? Dude, I'm tellin' ya,[n]it seems freakin' fishy.[n][w][e]

[msg MSG_KF_Variety_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Wait, hold on...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 1187 65535 0]Hey, let's take a look![n][w][e]

[msg MSG_KF_Variety_mes03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1021 65535 0]I feel like these incenses have some[n]strange power... Maybe we can use it[n]for something.[n][w][e]

[msg MSG_KF_Variety_mes04 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh, I don't get it...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]But if Morgana's the one sayin' it, maybe[n]you should come buy it some time.[n][w][e]

[msg MSG_KF_VarietyNG_mes01 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]An incense store? Dude, I'm tellin' ya,[n]it seems freakin' fishy.[n][w][e]

[msg MSG_KF_VarietyNG_mes02 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]You've got no interest in incenses, right?[n]Where would you even use it...?[n][w][e]

[msg MSG_KF_Megane_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1020 65535 0]A store that only sells glasses...[n]Check out all the different kinds they have.[n][w][e]

[msg MSG_KF_Megane_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I keep forgettin', but your glasses are[n]fake, huh? Do you think I'd look smarter[n]if I had glasses on?[n][w][e]

[msg MSG_KF_Megane_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]I've never needed glasses, so I don't ever[n]go into stores like this.[n][w][e]

[msg MSG_KF_Accessories_mes01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1067 65535 0]Whoa! Check out all the treasures they[n]have in here![n][w][e]

[msg MSG_KF_Accessories_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Power stones are those amulet-like[n]things, right? They've got some weird[n]power or somethin'.[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Let's check it out.[n][w][e]

[msg MSG_KF_Accessories_mes03 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7114 65535 0]I almost got a bloody nose, just from[n]lookin' at those prices...[n][w][e]

[msg MSG_KF_Accessories_mes04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]But it looked like they actually had some[n]power in them. We oughta check it out[n]sometime.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Maybe it'll come in handy for the[n]Phantom Thieves![n][w][e]

[msg MSG_KF_DonutShop_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]I just realized somethin'...[n][w][e]

[msg MSG_KF_DonutShop_mes02 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]What's up, Morgana?[n][w][e]

[msg MSG_KF_DonutShop_mes03 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]We're really missing out with no center[n]part of the donut![n][w][e]

[msg MSG_KF_DonutShop_mes04 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]Yeah... That's really somethin' we need[n]to worry about right now...[n][w][e]

[msg MSG_KF_DonutShop_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7184 65535 0]Oh, weren't donuts a big thing at one[n]point? It was like super popular some[n]time ago.[n][w][e]

[msg MSG_KF_AntiqueStore_mes0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Wow, look at all the artistic antiques...[n][w][e]

[msg MSG_KF_AntiqueStore_mes0_2 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I'm done with this after lookin' at the[n]Museum the other day.[n][w][e]

[msg MSG_KF_AntiqueStore_mes0_3 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7190 65535 0]Dude, I thought that thing in there was a[n]picture, but it was a freakin' table.[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Man, I just don't get art.[n][w][e]

[msg MSG_KF_SteakFood_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]"Try our 40-day-aged, A5-rank meat![n]Savor meat that melts in your mouth."[n][w][e]

[msg MSG_KF_SteakFood_mes02 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Stop it! Stop it! You're gonna make me[n]wanna eat it![n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]This place is dangerous.[n]Let's stay away from here.[n][w][e]

[msg MSG_KF_SteakFood_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]Man, the smell of cooked meat is killin'[n]me... *slurp* Oh shit, I'm droolin'.[n][w][e]

[msg MSG_KF_WineBar_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7086 65535 0]"We have 100 types of wine."[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Wine's made of grapes, right?[n]Is the flavor really THAT different?[n][w][e]

[msg MSG_KF_WineBar_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]There's really a lot to wine. Like how[n]there's red wine and white wine...[n][w][e]

[msg MSG_KF_WineBar_mes03 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]All I got from that is that you're not good[n]at describin' stuff...[n][w][e]

[msg MSG_KF_WineBar_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Wine and cheese... I want to try it one day.[n][w][e]

[msg MSG_KF_SportsShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]For mountain girls and beach girls...[n]Looks like they have a whole bunch[n]of outdoor stuff.[n][w][e]

[msg MSG_KF_SportsShop_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Man, there's so many outdoorsy girls[n]around nowadays.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]But how come there aren't any mountain[n]boys or ocean boys?[n][w][e]

[msg MSG_KF_SportsShop_mes03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]...Good point.[n][w][e]

[msg MSG_KF_SportsShop_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7184 65535 0]You know, we might need some swim[n]suits one day.[n][w][e]

[msg MSG_KF_ToyShop_mes01 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]So they got imported toys here. They[n]sure seem different than the ones we[n]have here.[n][w][e]

[msg MSG_KF_ToyShop_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Looks like they're mainly made from wood.[n]Maybe we'd be able to make our own.[n][w][e]

[msg MSG_KF_ToyShop_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]So they're imported from different[n]countries, huh? The families in there[n]look pretty fancy, too...[n][w][e]

[msg MSG_KF_MajorCafe_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]What a fancy looking café. If I ever were[n]to invite Lady Ann somewhere— Why're[n]you looking at me like that?[n][w][e]

[msg MSG_KF_MajorCafe_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Well, it does say we can brings pets inside,[n]so maybe it'll be okay?[n][w][e]

[msg MSG_KF_MajorCafe_mes03 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Who're you calling a pet!?[n][w][e]

[msg MSG_KF_MajorCafe_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]What a fancy café. Looks like their[n]specialty is home-roasted espresso.[n][w][e]

[msg MSG_KF_Pasta_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]We recommend the pappardelle and[n]orecchiette. Try our cappelletti and[n]agnolotti as well...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]I did it! I said it without stopping![n][w][e]

[msg MSG_KF_Pasta_mes02 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Papprar...dille? Agno...what?[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I can't even say it, let alone imagine what[n]the hell it looks like...[n][w][e]

[msg MSG_KF_Pasta_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Looks like their recommendations are[n]pappardelle, orecchiette, cappelletti and[n]agnolotti![n][w][e]

[msg MSG_KF_Bicycle_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Oh, the bicycles here look really easy[n]to carry.[n][w][e]

[msg MSG_KF_Bicycle_mes02 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Dude, check out the prices on those[n]bicycles! Shit, aren't they more expensive[n]than motorbikes?[n][w][e]

[msg MSG_KF_Bicycle_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Wonder if expensive bikes are more[n]useful than those normal bikes...[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 7173 65535 0]I don't think I can ride this bike.[n]I feel like it'll get stolen or somethin'.[n][w][e]

[sel D_VELVET_IN_SEL top]
[s]Let me in the cell.[e]
[s]I don't want to go in.[e]

[msg D_VELVET_IN_QUIET_01 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 12002 65535 0]It seems you long to be imprisoned.[n]I can grant that wish for you...[n][w][e]

[msg D_VELVET_IN_QUIET_OK [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Very well. I shall gladly fulfill your desire...[n][w][e]

[msg D_VELVET_IN_QUIET_NO [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Continue your struggle.[n][w][e]

[msg D_VELVET_IN_LOUD_01 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What's the matter, Inmate? You longing[n]to go back to jail?[n][w][e]

[msg D_VELVET_IN_LOUD_OK [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Heheheh. I'm gonna put you back where[n]you belong![n][w][e]

[msg D_VELVET_IN_LOUD_NO [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Keep struggling, Inmate.[n][w][e]

[msg D_VELVET_IN_LAST_01 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I shall guide you to my master...[n][w][e]

[sel D_VELVET_IN_LAST_SEL top]
[s]I want to prepare.[e]
[s]I don't want to go in.[e]

[msg D_VELVET_IN_LAST_OK [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Then please, enter.[n][w][e]

[msg D_VELVET_IN_LAST_NO [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Very well. My master and I will be[n]watching over you.[n][w][e]

[msg MSG_KICHIJOJ_OPEN_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]You're gonna end up back at the station[n]if you go that way. Let's go to the darts[n]lounge for now.[n][w][e]

[msg MSG_MONEY_MORGANA_CHK_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1001 0 0]Oh, you don't have enough money?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]I'll give you some from my secret stash for[n]now, but make sure you have some with[n]you next time.[n][w][e]

[msg MSG_KFEVT_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Hey, where are you going?[n][w][e]

[msg MND_COMMON_CHK_000_00]
[s][vp 1 0 0 0 0 0]There's nothing that[n]I need to do up ahead...[n][w][e]

[msg EX_0103_0108_LOCK_mes01 [Female Guest with Hat]]
[s][vp 1 0 0 0 0 0]Is this the place? The one with the[n]charismatic perfumer we read about[n]in the magazine?[n][w][e]

[msg EX_0103_0108_LOCK_mes02 [Female Guest]]
[s][vp 1 0 0 0 0 0]Oh yeah. They got all those famous[n]models and actresses using their products.[n][w][e]

[msg EX_0103_0108_LOCK_mes03 [Female Guest with Hat]]
[s][vp 1 0 0 0 0 0]The store manager's supposedly a[n]mysterious guy, too! Everyone's talking![n][w][e]
[s][vp 1 0 0 0 0 0]I hope I can shake hands with them when[n]I make my purchase![n][w][e]

[msg EX_0103_0108_LOCK_mes04]
[s][vp 1 0 0 0 0 0]The line seems to be[n]for the incense shop.[n][w][e]
[s][vp 1 0 0 0 0 0]I don't think I can[n]go in any further...[n][w][e]

[msg EX_0103_0108_LOCK_mes00]
[s][vp 1 0 0 0 0 0]It's too crowded for me[n]to go in any further...[n][w][e]

