[msg D157_013_miniEV_01_mes01 [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8020 65535 0]Ah, we were able to circumvent the wall[n]of cards, it seems.[n][w][e]

[msg D157_013_miniEV_01_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Man, that long way 'round shit is bull![n]Where's that bastard from earlier, huh!?[n][w][e]

[msg e382_235_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6194 65535 0]Hey, isn't this the thing that Shadow was[n]messing with?[n][w][e]

[msg e382_235_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, we have an escape route now! We can[n]proceed onward without having to worry[n]about it anymore.[n][w][e]

[msg D06_mini_ev03_mes01 [Dealer]]
[s]Welcome.[n][w][e]
[s]I will now explain the rules of this battle[n]to you. Don't worry, they're quite simple.[n][w][e]

[msg D06_mini_ev03_mes02 [Dealer]]
[s][clr 2]If the card you show from your hand[n]is larger than your opponent's card,[n]you win[clr 27].[n][w][e]
[s][clr 2]Three wins[clr 27] will gain you [clr 2]one set[clr 27].[n][w][e]
[s]First to [clr 2]two sets[clr 27] is the winner.[n][w][e]
[s]If you emerge victorious, we will[n][clr 2]double[clr 27] the current number of coins[n]in your possession.[n][w][e]
[s]That is all for the explanation. Do you[n]understand the rules?[n][w][e]

[sel D06_mini_ev03_selA top]
[s]I do.[e]
[s]One more time, please.[e]

[msg D06_mini_ev03_selA_0_mes [Dealer]]
[s]Then let us begin the battle.[n][w][e]

[msg D06_mini_ev03_selA_1_mes [Dealer]]
[s]Very well. I will explain once more.[n][w][e]

[msg D06_mini_ev03_mes03 [Dealer]]
[s]You have won this set.[n][w][e]
[s]That is your first set. One more and we[n]will double your coin total.[n][w][e]

[msg D06_mini_ev03_mes4 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What the heck? This is a piece of cake.[n]We got this, no problem![n][w][e]

[msg D06_mini_ev03_mes5 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hopefully it continues being as simple[n]as it is now...[n][w][e]

[msg D06_mini_ev03_mes6 [Dealer]]
[s]My, you are quite the tough customer,[n]sir. I am in serious trouble here.[n][w][e]
[s]I'll need to step up my game.[n][w][e]

[msg D06_mini_ev03_mes7 [Dealer]]
[s]Hm, is that... a one?[n][w][e]
[s]Then I will go with this.[n][w][e]

[msg D06_mini_ev03_mes8 [Dealer]]
[s]Hmmm... What is your card?[n]I truly cannot tell...[n][w][e]
[s]I'll just go with this.[n][w][e]

[msg D06_mini_ev03_mes9 [Dealer]]
[s]Oh, is that a three? Then I'll use a four.[n][w][e]

[msg D06_mini_ev03_mes10 [Dealer]]
[s]I have a feeling you have a big number.[n]Perhaps I should go with this one.[n][w][e]

[msg D06_mini_ev03_mes11 [Dealer]]
[s]I'm not sure I can win this one.[n]I'll just have to endure.[n][w][e]

[msg D06_mini_ev03_mes12 [Dealer]]
[s]Oh, I was right. How lucky.[n][w][e]

[msg D06_mini_ev03_mes13 [Dealer]]
[s]I won, but only barely. It seems luck was[n]on my side.[n][w][e]

[msg D06_mini_ev03_mes14 [Dealer]]
[s]Oh, I chose correctly. It seems this is[n]my victory.[n][w][e]

[msg D06_mini_ev03_mes15 [Dealer]]
[s]My, I'm feeling quite clear-headed.[n]How lucky.[n][w][e]

[msg D06_mini_ev03_mes16 [Dealer]]
[s]Ah, it seems you couldn't win this one, sir.[n][w][e]

[msg D06_mini_ev03_mes17 [Dealer]]
[s]I am the winner of this set.[n][w][e]
[s]That's one for each of us. Whoever wins[n]the next set is the victor.[n][w][e]

[msg D06_mini_ev03_mes18 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You bastard! This shit's rigged![n][w][e]

[msg D06_mini_ev03_mes19 [Dealer]]
[s]Rigged? How do you mean?[n][w][e]

[msg D06_mini_ev03_mes20 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You knew exactly what numbers we[n]were using![n][w][e]

[msg D06_mini_ev03_mes21 [Dealer]]
[s]I'm not sure what you're talking about.[n]I just happened to guess correctly.[n][w][e]

[msg D06_mini_ev03_mes22 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You just happened to, hm?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Very well. But your tricks will not work[n]on us again.[n][w][e]

[msg D06_mini_ev03_mes23 [Dealer]]
[s]Wh-What in the world!?[n][w][e]

[msg D06_mini_ev03_mes24 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What's wrong? We won, yes?[n][w][e]

[msg D06_mini_ev03_mes25 [Dealer]]
[s]That can't be...[n][w][e]

[msg D06_mini_ev03_mes26 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Come, let us continue.[n][w][e]

[msg D06_mini_ev03_mes27 [Dealer]]
[s]S-Something's wrong... This can't be[n]happening![n][w][e]
[s]You guys must be cheating![n][w][e]

[msg D06_mini_ev03_mes28 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Look who's talking...[n][w][e]

[msg D06_mini_ev03_mes29 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We are most certainly not cheating. False[n]accusations are unbecoming, you know.[n][w][e]

[msg D06_mini_ev03_mes30 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's right! Anyways, let's keep this[n]shit rollin'![n][w][e]

[msg D06_mini_ev03_mes31 [Dealer]]
[s]Ngh...[n][w][e]

[msg D06_13_TRUMP_END_mes01 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So, this is our victory.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What was the prize again? You said you[n]would double the coins in our possession,[n]did you not?[n][w][e]

[msg D06_13_TRUMP_END_mes02 [Dealer]]
[s]...Yes.[n][w][e]
[s]The reception clerk will handle that[n]for you.[n][w][e]

[msg D06_13_TRUMP_END_mes03 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm? What are you scheming?[n][w][e]

[msg D06_13_TRUMP_END_mes04 [Dealer]]
[s]Did I not tell you?[n][w][e]
[s]You will have to survive a battle against[n]one of our talented staff if you want to[n]win this bet.[n][w][e]

[msg D06_13_TRUMP_END_mes05 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is freakin' ridiculous.[n][w][e]

[msg D06_13_TRUMP_END_mes06 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It should be a simple finish.[n][w][e]

[msg D06_13_TRUMP_END_mes7 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's get it over with then![n][w][e]

[msg Battle_Number01 [Dealer]]
[s]Welcome.[n][w][e]
[s]I will now explain the rules of this battle[n]to you. Don't worry, they're quite simple.[n][w][e]
[s][clr 2]If the card you show is larger[n]than your opponent's, you win[clr 27].[n][w][e]
[s]If you are the [clr 2]first to three sets[clr 27],[n]we will [clr 2]double[clr 27] the current number[n]of coins in your possession.[n][w][e]
[s]Well then, let us begin.[n][w][e]

[msg Battle_Number02 [Dealer]]
[s]Now then, let us proceed on to our[n]next battle.[n][w][e]

[msg Card_Battle_WIN [Dealer]]
[s]Very good, sir. I'm impressed.[n][w][e]

[msg Card_Battle_LOSE [Dealer]]
[s]Oh? This is my win.[n][w][e]

[msg Card_Battle_DRAW [Dealer]]
[s]It is a draw.[n][w][e]

[msg Card_Battle_WIN_SET [Dealer]]
[s]Wonderful, sir. You win this set.[n][w][e]

[msg Card_Battle_LOSE_SET [Dealer]]
[s]Oh, this is my set. How lucky.[n][w][e]

[msg Card_Battle_WIN_END [Dealer]]
[s]C-Congratulations, sir. It seems you are[n]the winner.[n][w][e]
[s]I'll be giving you the coins now.[n]Please take out your membership card.[n][w][e]

[msg Card_Battle_LOSE_END [Dealer]]
[s]Oh? Unfortunately, it seems as though[n]this is my victory.[n][w][e]
[s]Now then, it's time for your penalty, sir.[n][w][e]

[msg Card_Battle_Trick [Dealer]]
[s]Hm... If I had to guess, I'd say you placed[n]a [clr 2][var 0][clr 27]...[n][w][e]
[s]In that case, perhaps I should go[n]with this card.[n][w][e]

[msg Card_Battle_LAST_01 [Dealer]]
[s]Hmmm, I'm somewhat confused.[n][w][e]
[s]Perhaps I'll go with... this one?[n][w][e]

[msg Card_Battle_LAST_02 [Ryuji]]
[s]Dammit, quit messin' around...[n]This has gotta be rigged![n][w][e]

[msg Card_Battle_LAST02_01 [Dealer]]
[s]Ah, I'm feeling clear-minded once again![n]I think I'll go with this.[n][w][e]

[msg Card_Battle_LAST03_01 [Akechi]]
[s]Hold on a moment. Are you certain[n]you're not cheating here?[n][w][e]

[msg Card_Battle_LAST03_02 [Dealer]]
[s]Of course not! How exactly would[n]you expect I can cheat at this?[n][w][e]

[msg Card_Battle_LAST03_03 [Akechi]]
[s]Hmph, I expect that means you've[n]rigged this game in a manner[n]that is difficult to prove.[n][w][e]

[msg Card_Battle_LAST03_04 [Dealer]]
[s]You can interpret things however you[n]see fit, sir.[n][w][e]

[msg Card_Battle_LAST03_05 [Akechi]]
[s]Very well then. Let us continue playing.[n][w][e]

[msg Card_Battle_LAST03_06 [Dealer]]
[s]I'm glad you understand.[n]Now then, let's flip our cards.[n][w][e]

[msg WIN_COUNT_MES [Dealer]]
[s]The current win record is[n][clr 2][var 0][clr 27] for you, [clr 2][var 1][clr 27] for me.[n][w][e]

[msg __test_message_01]
[s]dummy fhit_157_013_00[n][w][e]

