[msg D157_009_miniEV_02_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7020 65535 0]...Dayum, this is a crazy number of slots,[n]yeah?[n][w][e]

[msg D157_009_miniEV_02_mes02 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I would expect they're all rigged to[n]prevent us from ever winning.[n][w][e]

[msg D157_009_miniEV_02_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Then should we deal with that first?[n][w][e]

[msg D157_009_miniEV_02_mes04 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8038 65535 0]No, I believe it would be prudent to[n]examine this slot area further.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Casinos hold their higher-limit slots[n]somewhere in the back.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If we were going to circumvent their trick,[n]would it not be more efficient to do so on[n]those?[n][w][e]

[msg D157_009_miniEV_02_mes05 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's assuming we'll even be able to[n]solve the problem.[n][w][e]

[msg D157_009_miniEV_02_mes06 [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I trust in your ability to handle such[n]a matter.[n][w][e]

[msg D157_009_miniEV_02_mes07 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A-Aight, let's go look for that sweet,[n]sweet slot machine![n][w][e]

