[msg DUMMY_MSG]
[s]......[n][w][e]

[sel YESNO_SEL top]
[s]Yes[e]
[s]No[e]

[msg MSG_NotUse_Table [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Someone's napping on the table...[n]Do any of these kids ever think[n]about being considerate?[n][w][e]

[msg MSG_STUDY_START_1ST [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Oh, looks like you can study here.[n][w][e]

[msg MSG_Sentou_ParamInfo_int [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Your [f 4 11 0][clr 26][f 4 12 0][clr 27] might improve[n]if you study at one of the open tables.[n][w][e]

[msg MSG_Study_Start_Kamo [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]There's other people around, but...[n]your [f 4 11 3][clr 26][f 4 12 3][clr 27] might improve[n]because of it.[n][w][e]

[msg MSG_Study_Start_Normal [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]What do you wanna do, study here?[n][w][e]

[msg MSG_Study_Start_BadWeath [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]There aren't many people today—maybe[n]because of the weather...! That means[n]you'll be able to focus on studying today![n][w][e]

[sel STUDY_THINK_SEL top]
[s]Let's do it.[e]
[s]I'll pass.[e]

[msg MND_Study_ParamEndInfo]
[s]I think I have enough[n][f 4 11 0][clr 26][f 4 12 0][clr 27] already...[n][w][e]

[msg MND_Study_ParamUpInfo]
[s]I feel like my [f 4 11 0][clr 26][f 4 12 0][clr 27][n]is going to improve soon...[n][w][e]

[msg MSG_BOOK_SHELF_01 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]All the books here look pretty tough...[n][w][e]

[msg MSG_BOOK_SHELF_02 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1177 65535 0]I don't think many people ever check[n]these books out. They're all covered[n]in a thick layer of dust.[n][w][e]

[msg MSG_BOOK_SHELF_03 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]This book's title is super boring... Is there[n]anything more interesting in here?[n][w][e]

[msg MSG_BOOK_SHELF_04 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Who picks the books they have in here?[n]They should really invest in something[n]more exciting...[n][w][e]

[msg MSG_BOOK_SHELF_05 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Man, all these books are gigantic...[n]Getting hit with one would suck.[n][w][e]

[msg MSG_BOOK_SHELF_06 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]This shelf is jam-packed with books.[n]Most of them seem a bit too serious[n]for my tastes.[n][w][e]

[msg MSG_BOOK_SHELF_07 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Does anyone actually read these?[n]Well, I guess they're here to study...[n][w][e]

[msg MSG_BOOK_SHELF_08 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Hmmm... None of these look very[n]compelling to me...[n][w][e]

[msg MSG_BOOK_SHELF_09 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]These books look ancient... I feel like[n]they'd crumble if you tried to turn the[n]pages.[n][w][e]

[msg MSG_BOOK_SHELF_10 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]These books smell... weird.[n][w][e]

[msg MSG_LastKeyfree [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]We can't wait any longer... We have[n]to prepare, and fast![n][w][e]

[msg MND_KFEVT_COMMON_NG]
[s][vp 1 0 0 0 0 0]There's nothing I particularly[n]need to do here right now.[n][w][e]

[msg MSG_NotUse_GUIDE_DESK [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1044 0 0]Do you really need to sit down and[n]read right now? Save that for later.[n][w][e]

[msg MSG_NotUse_TABLE_LEFT [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1170 0 0]You don't have time for leisurely[n]reading right now.[n][w][e]

[msg MSG_NotUse_STUDYDESK_CHA [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1178 0 0]Save the studying for later.[n][w][e]

[msg MSG_NotUse_BOOK_SHELF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1189 0 0]Do you really need to sit down and[n]read right now? Save that for later.[n][w][e]

[msg MND_RankUp_OK_Chishiki]
[s]I feel like my [f 4 11 1][clr 26][f 4 12 0][clr 27][n]is going to improve soon...[n][w][e]

[msg MND_RankUp_NG_Chishiki]
[s]I don't think my [f 4 11 1][clr 26][f 4 12 0][clr 27][n]is going to improve just yet...[n][w][e]

[msg MND_INC_PARAMCHK_L_TISIK]
[s]It looks like I still have a lot of[n]room for improvement...[n][w][e]

[msg MND_INC_PARAMCHK_M_TISIK]
[s]I can feel something[n]coming to me...[n][w][e]

[msg MND_INC_PARAMCHK_S_TISIK]
[s]I think I'm close to a breakthrough[n]with my [f 4 11 0][clr 26][f 4 12 0][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Miryoku]
[s]I feel like my [f 4 11 1][clr 26][f 4 12 0][clr 27][n]is going to improve soon...[n][w][e]

[msg MND_RankUp_NG_Miryoku]
[s]I don't think my [f 4 11 1][clr 26][f 4 12 0][clr 27][n]is going to improve just yet...[n][w][e]

[msg MND_INC_PARAMCHK_L_MIRYO]
[s]It looks like I still have a lot of[n]room for improvement...[n][w][e]

[msg MND_INC_PARAMCHK_M_MIRYO]
[s]I can feel something[n]coming to me...[n][w][e]

[msg MND_INC_PARAMCHK_S_MIRYO]
[s]I think I'm close to a breakthrough[n]with my [f 4 11 1][clr 26][f 4 12 1][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Kiyou]
[s]I feel like my [f 4 11 2][clr 26][f 4 12 2][clr 27][n]is going to improve soon...[n][w][e]

[msg MND_RankUp_NG_Kiyou]
[s]I don't think my [f 4 11 2][clr 26][f 4 12 2][clr 27][n]is going to improve just yet...[n][w][e]

[msg MND_RankUp_OK_Kiyou_Beef]
[s]If things go well, I think my[n][f 4 11 1][clr 26][f 4 12 1][clr 27] might improve...[n][w][e]

[msg MND_INC_PARAMCHK_L_KIYOU]
[s]It looks like I still have a lot of[n]room for improvement...[n][w][e]

[msg MND_INC_PARAMCHK_M_KIYOU]
[s]I can feel something[n]coming to me...[n][w][e]

[msg MND_INC_PARAMCHK_S_KIYOU]
[s]I think I'm close to a breakthrough[n]with my [f 4 11 2][clr 26][f 4 12 2][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Dokyo]
[s]I feel like my [f 4 11 3][clr 26][f 4 12 3][clr 27][n]are going to improve soon...[n][w][e]

[msg MND_RankUp_NG_Dokyo]
[s]I don't think my [f 4 11 3][clr 26][f 4 12 3][clr 27][n]are going to improve just yet...[n][w][e]

[msg MND_INC_PARAMCHK_L_DOKYO]
[s]It looks like I still have a lot of[n]room for improvement...[n][w][e]

[msg MND_INC_PARAMCHK_M_DOKYO]
[s]I can feel something[n]coming to me...[n][w][e]

[msg MND_INC_PARAMCHK_S_DOKYO]
[s]I think I'm close to a breakthrough[n]with my [f 4 11 3][clr 26][f 4 12 3][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Yasasisa]
[s]I feel like my [f 4 11 4][clr 26][f 4 12 4][clr 27][n]is going to improve soon...[n][w][e]

[msg MND_RankUp_NG_Yasasisa]
[s]I don't think my [f 4 11 4][clr 26][f 4 12 4][clr 27][n]is going to improve just yet...[n][w][e]

[msg MND_RankUp_OK_Yasasisa_F]
[s]If things go well, I think my[n][f 4 11 4][clr 26][f 4 12 4][clr 27] might improve...[n][w][e]

[msg MND_INC_PARAMCHK_L_YASAS]
[s]It looks like I still have a lot of[n]room for improvement...[n][w][e]

[msg MND_INC_PARAMCHK_M_YASAS]
[s]I can feel something[n]coming to me...[n][w][e]

[msg MND_INC_PARAMCHK_S_YASAS]
[s]I think I'm close to a breakthrough[n]with my [f 4 11 4][clr 26][f 4 12 4][clr 27]...[n][w][e]

