[sel YESNO_SEL top]
[s]Yes[e]
[s]No[e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]You don't need to be here right[n]now, do you? Come on, let's head[n]somewhere else![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]What's wrong? Come on, we should[n]go say goodbye to the others![n][w][e]

[msg MSG_LAST_GREETING_Roof [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Oh, it's locked... I guess we should[n]probably go somewhere else, huh?[n][w][e]

[msg MSG_ROOF_MAKOTO_NG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]It looks like it's locked.[n][w][e]

[msg MSG_ROOF_HARU_NG [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Oh... It's locked. I guess we can't go out[n]unless Haru's there.[n][w][e]

[msg MSG_STUDENT_COUNCIL_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Hey, you don't have any reason to go[n]to the student council room, do you?[n][w][e]

[msg MSG_STUDENT_COUNCIL]
[s][vp 1 0 0 0 0 0]This is the student council room.[n][w][e]
[s][vp 1 0 0 0 0 0]The seats inside are all[n]very neatly organized...[n][w][e]

[msg CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]The bathroom smells a bit musty...[n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Don't you know that's the girls'[n]bathroom? You're not supposed[n]to be in there...[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the ladies' restroom...[n][w][e]

[msg MSG_Board_AfterKamo [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]"Don't make any remarks outside of[n]school"? The public already knows...[n][w][e]

[msg MSG_BOARD_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]"The Shujin Academy General Code[n]of Conduct." Ugh, it's so detailed...[n][w][e]

[msg MSG_BOARD]
[s][vp 1 0 0 0 0 0]There are club handouts and[n]postings from the student council[n]all over this bulletin board...[n][w][e]

[msg MSG_RADIO_STUDIO_MORU [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Oooh, the broadcast room... Maybe you[n]should sneak in and introduce yourself[n]to the school![n][w][e]

[msg MSG_RADIO_STUDIO]
[s][vp 1 0 0 0 0 0]There are several students sorting[n]CDs in the broadcast room...[n][w][e]

[msg MSG_GRADE1_CLASS_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]...This is a first-year classroom.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]You don't know anyone in there, do you?[n]We probably shouldn't drop in on them[n]for no reason.[n][w][e]

[msg MSG_GRADE1_CLASS]
[s][vp 1 0 0 0 0 0]This is a first-year classroom.[n][w][e]
[s][vp 1 0 0 0 0 0]The students seem to be[n]wondering why I'm here. Maybe[n]I should go somewhere else...[n][w][e]

[msg MSG_Emergency_Door_m [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Hold on, we should use the main[n]entrance if you wanna go outside.[n][w][e]

[msg MSG_Emergency_Door]
[s][vp 1 0 0 0 0 0]There's no reason for me to[n]use the emergency exit...[n][w][e]

[msg MND_BLDG_B_KEEPOUT_000_0]
[s][vp 1 0 0 0 0 0]There's nothing that[n]I need to do up ahead...[n][w][e]

[msg MSG_E13710100_NG_BldgA3F [Ryuji]]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]That'll take you to the Practice Building.[n]We gotta get to the room for Class D.[n][w][e]

[msg MND_E13710100_NG_BldgA3F]
[s][vp 1 0 0 0 0 0]I should let Ryuji handle[n]the Practice Building...[n][w][e]

[msg MND_E12310100_GOTO_Rooft]
[s][vp 1 0 0 0 0 0]It has an off-limits sign[n]posted up, but it looks[n]like the door is unlocked...[n][w][e]

[msg MND_E12720100_NG_Rooftop]
[s][vp 1 0 0 0 0 0]There's nothing I need to[n]do on the rooftop right now...[n][w][e]

[msg MSG_E13710100_NG_Rooftop [Ryuji]]
[s][bup 0 2 200 0 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]I don't think we're gonna find anyone[n]from the volleyball team up there.[n][w][e]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]It does say it's off-limits, so no one's[n]been goin' up there.[n][w][e]

[msg MND_E13710100_NG_Rooftop]
[s][vp 1 0 0 0 0 0]The rooftop isn't a popular[n]place for people to hang out.[n]Let's search somewhere else...[n][w][e]

[msg MND_E13710100_NG_Rooftop_2]
[s][vp 1 0 0 0 0 0]There's nothing I need to do[n]on the rooftop right now...[n][w][e]

[msg MSG_E13910100_NG_Rooftop [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, I said the main entrance![n]He's gonna leave if we don't hurry.[n][w][e]

[msg MND_E14130100_NG_Rooftop]
[s][vp 1 0 0 0 0 0]There's nothing I need to do[n]on the rooftop right now...[n][w][e]

[msg MND_E14710100_NG_Rooftop]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E23810100_NG_Rooftop [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]The roof is closed. Let's go to the[n]student council room.[n][w][e]

[msg MSG_E24320100_NG_Rooftop [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]The rooftop is closed. Let's try[n]somewhere else.[n][w][e]

[msg MND_COMMON_NG_Rooftop_00]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here for now...[n][w][e]

[msg MND_E12310100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]There are students[n]quietly studying away[n]here in the library...[n][w][e]

[msg MND_E12720100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]There are students[n]quietly studying away[n]here in the library...[n][w][e]

[msg MSG_E13710100_CHK_LIBRAR [Ryuji]]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 7161 65535 0]Hey, man. Did you know?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]There isn't any manga at all in[n]this library...[n][w][e]

[msg MND_E13710100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]I don't see any students[n]in the library...[n][w][e]

[msg MSG_E13910100_CHK_LIBRAR [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, I said the main entrance![n]He's gonna leave if we don't hurry.[n][w][e]

[msg MND_E14130100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]There are students[n]quietly studying away[n]here in the library...[n][w][e]

[msg MND_E14710100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E23810100_CHK_LIBRAR [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Later. Aren't you going to the student[n]council room?[n][w][e]

[msg MND_COMMON_CHK_LIBRARY_0]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here for now...[n][w][e]

[msg MND_E12310100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]This is the student council room.[n][w][e]
[s][vp 1 0 0 0 0 0]The seats inside are all[n]very neatly organized...[n][w][e]

[msg MND_E12720100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]This is the student council room.[n][w][e]
[s][vp 1 0 0 0 0 0]The seats inside are all[n]very neatly organized...[n][w][e]

[msg MSG_E13710100_CHK_STUDEN [Ryuji]]
[s][bup 0 2 202 0 0][f 4 10 65535 0 0][vp 8 2 1 7156 65535 0]We can't count on anyone in the[n]student council.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]All of 'em do whatever they gotta do[n]to make the teachers happy. That's all[n]they care about.[n][w][e]

[msg MND_E13710100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]This is the student council room.[n][w][e]
[s][vp 1 0 0 0 0 0]The seats inside are all[n]very neatly organized...[n][w][e]

[msg MSG_E13910100_CHK_STUDEN [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, I said the main entrance![n]He's gonna leave if we don't hurry.[n][w][e]

[msg MND_E14130100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]This is the student council room.[n][w][e]
[s][vp 1 0 0 0 0 0]The seats inside are all[n]very neatly organized...[n][w][e]

[msg MND_E14710100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E23810100_GOTO_STUDE [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1020 0 0]This is the student council room.[n][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]What were we called here for? This is[n]rather strange...[n][w][e]

[msg MND_COMMON_CHK_STUDENT_C]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here...[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]The bathroom smells a bit musty...[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]The bathroom smells a bit musty...[n][w][e]

[msg MSG_E13710100_CHK_TOILET [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 7200 65535 0]Oh, I've been needin' to go this whole[n]time. We better go while we got the[n]chance![n][w][e]

[msg MSG_E13710100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 7028 65535 0]Phew...[n][w][e]

[msg MSG_E13710100_CHK_TOILET_3 [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 7045 65535 0]Aight, let's keep goin'! We'll start by[n]checkin' out your classroom.[n][w][e]

[msg MSG_E13710100_CHK_TOILET_4 [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]You need ta go again already? We just[n]went earlier.[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]The bathroom smells a bit musty...[n][w][e]

[msg MSG_E13910100_CHK_TOILET [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, I said the main entrance![n]He's gonna leave if we don't hurry.[n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Let's head to the[n]courtyard for now...[n][w][e]

[msg MND_E14710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E23810100_GOTO_TOILE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1018 0 0]Do it later. You're going to the student[n]council room on the third floor, right?[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]The bathroom smells a bit musty...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the ladies' restroom...[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the ladies' restroom...[n][w][e]

[msg MSG_E13710100_CHK_TOILET_5 [Ryuji]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]Whoa, man, we can't be goin' in there![n]Let's hurry and get to your classroom![n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the ladies' restroom...[n][w][e]

[msg MSG_E13910100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, what're you doin'!? We gotta hurry[n]and catch up to Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the ladies' restroom...[n][w][e]

[msg MND_E14710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E23810100_CHK_TOILET [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]You don't need anything over there,[n]do you? Aren't you going to the student[n]council room on the third floor?[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the ladies' restroom...[n][w][e]

[msg MND_E12310100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]There are club handouts and[n]postings from the student council[n]all over this bulletin board...[n][w][e]

[msg MND_E12720100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]There are club handouts and[n]postings from the student council[n]all over this bulletin board...[n][w][e]

[msg MSG_E13710100_CHK_BOARD_ [Ryuji]]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]Whaddya doin'? Let's hurry up and[n]get to your classroom![n][w][e]

[msg MND_E13710100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]There are club handouts and[n]postings from the student council[n]all over this bulletin board...[n][w][e]

[msg MSG_E13910100_CHK_BOARD_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, what're you doin'!? We gotta hurry[n]and catch up to Mishima![n][w][e]

[msg MND_E14130100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]There are club handouts and[n]postings from the student council[n]all over this bulletin board...[n][w][e]

[msg MND_E14710100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E23810100_CHK_BOARD_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Is something wrong? You're going to the[n]student council room on the third floor, right?[n][w][e]

[msg MND_COMMON_CHK_BOARD_000]
[s][vp 1 0 0 0 0 0]There are club handouts and[n]postings from the student council[n]all over this bulletin board...[n][w][e]

[msg MND_E12310100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]There are several students sorting[n]CDs in the broadcast room...[n][w][e]

[msg MND_E12720100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]There are several students sorting[n]CDs in the broadcast room...[n][w][e]

[msg MSG_E13710100_CHK_HOUSOS [Ryuji]]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 1 7159 65535 0]Oh, should we try makin' a broadcast[n]to get the guys on the volleyball team[n]together?[n][w][e]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]...Ah, wait. Kamoshida'll hear it[n]and rush over here too.[n][w][e]

[msg MND_E13710100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]There are several students sorting[n]CDs in the broadcast room...[n][w][e]

[msg MSG_E13910100_CHK_HOUSOS [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, I said the main entrance![n]He's gonna leave if we don't hurry.[n][w][e]

[msg MND_E14130100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]There are several students sorting[n]CDs in the broadcast room...[n][w][e]

[msg MND_E14710100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E23810100_CHK_HOUSOS [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]That's the broadcast room. Don't you[n]need to go to the student council room[n]on the third floor?[n][w][e]

[msg MND_COMMON_CHK_HOUSOSITU]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here...[n][w][e]

[msg MND_E12310100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]This is a first-year classroom.[n][w][e]
[s][vp 1 0 0 0 0 0]The students seem to be[n]wondering why I'm here. Maybe[n]I should go somewhere else...[n][w][e]

[msg MND_E12720100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]This is a first-year classroom.[n][w][e]
[s][vp 1 0 0 0 0 0]The students seem to be[n]wondering why I'm here. Maybe[n]I should go somewhere else...[n][w][e]

[msg MSG_E13710100_CHK_CLASS_ [Ryuji]]
[s][bup 0 2 202 0 0][f 4 10 65535 0 0][vp 8 2 1 7047 65535 0]I'm not seein' anyone from the[n]volleyball team.[n][w][e]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Let's start askin' the guys in your class![n][w][e]

[msg MND_E13710100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]I don't see any students[n]with any noticeable injuries...[n][w][e]

[msg MSG_E13910100_CHK_CLASS_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hey, I said the main entrance![n]He's gonna leave if we don't hurry.[n][w][e]

[msg MND_E14130100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]This is a first-year classroom.[n][w][e]
[s][vp 1 0 0 0 0 0]The students seem to be[n]wondering why I'm here. Maybe[n]I should go somewhere else...[n][w][e]

[msg MND_E14710100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]I better hurry to the courtyard...[n][w][e]

[msg MSG_E23810100_CHK_CLASS_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]That's the first-year classroom. Let's go[n]to the student council room on the third[n]floor.[n][w][e]

[msg MND_COMMON_CHK_CLASS_1_0]
[s][vp 1 0 0 0 0 0]This is a first-year classroom.[n][w][e]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here...[n][w][e]

