[msg D159_001_DUMMY_mes01]
[s]…[n][w][e]

[sel D_VELVET_IN_SEL top]
[s]Let me in the cell.[e]
[s]I don't want to go in.[e]

[msg D_VELVET_IN_QUIET_01 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 12002 65535 0]It seems you long to be imprisoned.[n]I can grant that wish for you...[n][w][e]

[msg D_VELVET_IN_QUIET_OK [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Very well. I shall gladly fulfill your desire...[n][w][e]

[msg D_VELVET_IN_QUIET_NO [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Continue your struggle.[n][w][e]

[msg D_VELVET_IN_LOUD_01 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What's the matter, Inmate? You longing[n]to go back to jail?[n][w][e]

[msg D_VELVET_IN_LOUD_OK [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Heheheh. I'm gonna put you back where[n]you belong![n][w][e]

[msg D_VELVET_IN_LOUD_NO [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Keep struggling, Inmate.[n][w][e]

[msg D_VELVET_IN_LAST_01 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I shall guide you to my master...[n][w][e]

[sel D_VELVET_IN_LAST_SEL top]
[s]I want to prepare.[e]
[s]I don't want to go in.[e]

[msg D_VELVET_IN_LAST_OK [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Then please, enter.[n][w][e]

[msg D_VELVET_IN_LAST_NO [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Very well. My master and I will be[n]watching over you.[n][w][e]

[msg D_BRIEFING_START_PC03_me [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, let's start our meeting.[n][w][e]

[msg D_BRIEFING_NEXT_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Is there anything else[n]you want to talk about?[n][w][e]

[msg D_BRIEFING_END_PC03_mes0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, meeting adjourned.[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC [Ryuji]]
[s][vp 1 0 0 2138 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right! Looks like[n]this place is safe.[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_2 [Morgana]]
[s][vp 1 0 0 3138 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ooh, a new safe room.[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_3 [Ann]]
[s][vp 1 0 0 4138 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is a nice spot[n]for a safe room![n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_4 [Yusuke]]
[s][vp 1 0 0 5138 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hmm... we can use this space.[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_5 [Makoto]]
[s][vp 1 0 0 6138 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This area seems sound. Let's[n]secure it as our safe room.[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_6 [Futaba]]
[s][vp 1 0 0 8138 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah! A safe room![n]We're good here.[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_7 [Haru]]
[s][vp 1 0 0 7138 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I didn't know there was[n]a safe room here...[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_8 [Akechi]]
[s][vp 1 0 0 9138 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, a safe room.[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_9 [[f 4 31 10 0]]]
[s][vp 1 0 0 10138 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I see there's a safe room here.[n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC [Ryuji]]
[s][vp 1 0 0 2139 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, we can use this place![n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_2 [Morgana]]
[s][vp 1 0 0 3139 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh. Looks like we can[n]use this place to rest.[n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_3 [Ann]]
[s][vp 1 0 0 4139 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is a safe room![n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_4 [Yusuke]]
[s][vp 1 0 0 5139 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We found a new safe room.[n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_5 [Makoto]]
[s][vp 1 0 0 6139 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yes! Looks like we can rest here.[n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_6 [Futaba]]
[s][vp 1 0 0 8139 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's safe here.[n]Wanna take a break?[n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_7 [Haru]]
[s][vp 1 0 0 7139 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This place looks safe.[n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_8 [Akechi]]
[s][vp 1 0 0 9139 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, this is a safe room.[n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_9 [[f 4 31 10 0]]]
[s][vp 1 0 0 10139 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's a safe room—care to drop in?[n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC [Ryuji]]
[s][vp 1 0 0 2140 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah nice! We can use[n]this as a safe room![n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_2 [Morgana]]
[s][vp 1 0 0 3140 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This looks usable.[n]Let's take a break, Joker.[n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_3 [Ann]]
[s][vp 1 0 0 4140 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A safe room! Thank goodness...[n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_4 [Yusuke]]
[s][vp 1 0 0 5140 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This space is quite[n]interesting... We can[n]use it as a safe room.[n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_5 [Makoto]]
[s][vp 1 0 0 6140 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We can use this place as a safe room.[n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_6 [Futaba]]
[s][vp 1 0 0 8140 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oooh, this place is relaxing.[n]Let's take a seat here.[n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_7 [Haru]]
[s][vp 1 0 0 7140 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We found a safe room![n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_8 [Akechi]]
[s][vp 1 0 0 9140 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's a safe room...[n]Shall we take a rest?[n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_9 [[f 4 31 10 0]]]
[s][vp 1 0 0 10140 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Found a safe room—should we[n]check it out?[n][w][e]

[msg SAFE_RETURN_TALK_01_PC02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sweet, I think we're gonna be able[n]to come right back here if we wanna.[n][w][e]

[msg SAFE_RETURN_TALK_01_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This should make a good base. We[n]can resume our infiltration from[n]here if we take a break too.[n][w][e]

[msg SAFE_RETURN_TALK_01_PC04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's make a note of this place so[n]we can come right back here later.[n][w][e]

[msg SAFE_RETURN_TALK_01_PC05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I expect this would be a great place[n]from which to resume our infiltration.[n][w][e]

[msg SAFE_RETURN_TALK_01_PC06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, we should be able to[n]resume our infiltration from[n]this place in the future.[n][w][e]

[msg SAFE_RETURN_TALK_01_PC07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sweet, we can use this place as a[n]base to resume our dungeon crawling![n][w][e]

[msg SAFE_RETURN_TALK_01_PC08 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I believe we can resume our operation[n]from here the next time we come in.[n][w][e]

[msg SAFE_RETURN_TALK_01_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, it seems we will be able to[n]resume things from here later on.[n][w][e]

[msg SAFE_RETURN_TALK_01_PC10 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It looks like we can use this area as a base.[n][w][e]

[msg SAFE_IN_MES_01_PC02_mes [Ryuji]]
[s][vp 1 0 0 2141 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Phew, we can rest here.[n][w][e]

[msg SAFE_IN_MES_01_PC03_mes [Morgana]]
[s][vp 1 0 0 3141 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, let's take five.[n][w][e]

[msg SAFE_IN_MES_01_PC04_mes [Ann]]
[s][vp 1 0 0 4141 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Phew, we can finally rest...[n][w][e]

[msg SAFE_IN_MES_01_PC05_mes [Yusuke]]
[s][vp 1 0 0 5141 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, let's take a rest here.[n][w][e]

[msg SAFE_IN_MES_01_PC06_mes [Makoto]]
[s][vp 1 0 0 6141 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's take a break, shall we?[n][w][e]

[msg SAFE_IN_MES_01_PC07_mes [Futaba]]
[s][vp 1 0 0 8141 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I can take a rest, right?[n]Don't worry, I won't fall asleep.[n][w][e]

[msg SAFE_IN_MES_01_PC08_mes [Haru]]
[s][vp 1 0 0 7141 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Phew, let's take a quick break.[n][w][e]

[msg SAFE_IN_MES_01_PC09_mes [Akechi]]
[s][vp 1 0 0 9141 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Phew, we can take a breather here.[n][w][e]

[msg SAFE_IN_MES_01_PC10_mes [[f 4 31 10 0]]]
[s][vp 1 0 0 10141 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We can take a breather here.[n][w][e]

[msg SAFE_IN_MES_02_PC02_mes [Ryuji]]
[s][vp 1 0 0 2142 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, let's take a break.[n][w][e]

[msg SAFE_IN_MES_02_PC03_mes [Morgana]]
[s][vp 1 0 0 3142 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay! Let's take a break![n][w][e]

[msg SAFE_IN_MES_02_PC04_mes [Ann]]
[s][vp 1 0 0 4142 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, let's take a break here.[n][w][e]

[msg SAFE_IN_MES_02_PC05_mes [Yusuke]]
[s][vp 1 0 0 5142 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Phew, let's rest a little.[n][w][e]

[msg SAFE_IN_MES_02_PC06_mes [Makoto]]
[s][vp 1 0 0 6142 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We can take a breather[n]here in this secure spot.[n][w][e]

[msg SAFE_IN_MES_02_PC07_mes [Futaba]]
[s][vp 1 0 0 8142 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A safe haven. Looks like we[n]can kick back and relax here.[n][w][e]

[msg SAFE_IN_MES_02_PC08_mes [Haru]]
[s][vp 1 0 0 7142 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Why don't we rest a little here?[n][w][e]

[msg SAFE_IN_MES_02_PC09_mes [Akechi]]
[s][vp 1 0 0 9142 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Shall we take a break?[n][w][e]

[msg SAFE_IN_MES_02_PC10_mes [[f 4 31 10 0]]]
[s][vp 1 0 0 10142 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's take a little break.[n][w][e]

[msg SAFE_IN_MES_03_PC02_mes [Ryuji]]
[s][vp 1 0 0 2143 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Good, we made it to the safe room![n][w][e]

[msg SAFE_IN_MES_03_PC03_mes [Morgana]]
[s][vp 1 0 0 3143 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, let's rest for a few.[n][w][e]

[msg SAFE_IN_MES_03_PC04_mes [Ann]]
[s][vp 1 0 0 4143 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We can finally rest our feet...[n][w][e]

[msg SAFE_IN_MES_03_PC05_mes [Yusuke]]
[s][vp 1 0 0 5143 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]How about we take a break here?[n][w][e]

[msg SAFE_IN_MES_03_PC06_mes [Makoto]]
[s][vp 1 0 0 6143 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Phew, we can rest here.[n][w][e]

[msg SAFE_IN_MES_03_PC07_mes [Futaba]]
[s][vp 1 0 0 8143 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We've reached a safe room![n]Perfect for chillin' and[n]killin' some time, huh?[n][w][e]

[msg SAFE_IN_MES_03_PC08_mes [Haru]]
[s][vp 1 0 0 7143 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's take a break.[n][w][e]

[msg SAFE_IN_MES_03_PC09_mes [Akechi]]
[s][vp 1 0 0 9143 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Say... why don't we rest a little?[n][w][e]

[msg SAFE_IN_MES_03_PC10_mes [[f 4 31 10 0]]]
[s][vp 1 0 0 10143 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We should be safe in here.[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0 [Ryuji]]
[s][vp 1 0 0 2042 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nice! We made it this far![n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0_2 [Morgana]]
[s][vp 1 0 0 3042 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Now then, what do we do from here?[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0_3 [Ann]]
[s][vp 1 0 0 4042 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're here. Now what do we do?[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0_4 [Yusuke]]
[s][vp 1 0 0 5042 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're here. What do we do next?[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0_5 [Makoto]]
[s][vp 1 0 0 6042 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We've arrived. Let's go.[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0_6 [Futaba]]
[s][vp 1 0 0 8042 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're here. So... what's next?[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0_7 [Haru]]
[s][vp 1 0 0 7042 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're here. What do we do now?[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0_8 [Akechi]]
[s][vp 1 0 0 9042 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We've arrived. What[n]do we do from here?[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC1 [[f 4 31 10 0]]]
[s][vp 1 0 0 10042 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, we made it—where to next?[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0 [Ryuji]]
[s][vp 1 0 0 2043 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aaand... we're here![n]Whaddya wanna do now?[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0_2 [Morgana]]
[s][vp 1 0 0 3043 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're here. Let's continue on![n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0_3 [Ann]]
[s][vp 1 0 0 4043 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right. Now, where do you[n]want to go from here?[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0_4 [Yusuke]]
[s][vp 1 0 0 5043 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We've arrived.[n]Now, what do we do?[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0_5 [Makoto]]
[s][vp 1 0 0 6043 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We've arrived safely.[n]Now let's proceed forward.[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0_6 [Futaba]]
[s][vp 1 0 0 8043 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're here? What do we do now?[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0_7 [Haru]]
[s][vp 1 0 0 7043 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We've arrived. Now, let's[n]continue our exploration.[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0_8 [Akechi]]
[s][vp 1 0 0 9043 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're here.[n]Now then, what comes next?[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC1 [[f 4 31 10 0]]]
[s][vp 1 0 0 10043 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Here we are. Let's get to exploring![n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0 [Ryuji]]
[s][vp 1 0 0 2044 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, where do we go from here?[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0_2 [Morgana]]
[s][vp 1 0 0 3044 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We've arrived. Now, let's[n]push forward, Joker.[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0_3 [Ann]]
[s][vp 1 0 0 4044 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We've arrived.[n]So, what do we do now?[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0_4 [Yusuke]]
[s][vp 1 0 0 5044 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Movement complete. Let's[n]continue our exploration.[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0_5 [Makoto]]
[s][vp 1 0 0 6044 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're here.[n]What do we do now, Joker?[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0_6 [Futaba]]
[s][vp 1 0 0 8044 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is where it begins, huh?[n]Where are we targeting?[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0_7 [Haru]]
[s][vp 1 0 0 7044 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, let's continue on.[n]What's the plan, Joker?[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0_8 [Akechi]]
[s][vp 1 0 0 9044 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We've arrived.[n]Now, shall we proceed?[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC1 [[f 4 31 10 0]]]
[s][vp 1 0 0 10044 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So, it's exploration time. What are[n]your orders?[n][w][e]

[msg SAFE_EXIT_LOW_01_PC02_me [Ryuji]]
[s][vp 1 0 0 2144 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, let's go.[n][w][e]

[msg SAFE_EXIT_LOW_01_PC03_me [Morgana]]
[s][vp 1 0 0 3144 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's go.[n][w][e]

[msg SAFE_EXIT_LOW_01_PC04_me [Ann]]
[s][vp 1 0 0 4144 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, let's go.[n]We still have work to do![n][w][e]

[msg SAFE_EXIT_LOW_01_PC05_me [Yusuke]]
[s][vp 1 0 0 5144 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, let's go.[n][w][e]

[msg SAFE_EXIT_LOW_01_PC06_me [Makoto]]
[s][vp 1 0 0 6144 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, back to exploring![n][w][e]

[msg SAFE_EXIT_LOW_01_PC07_me [Futaba]]
[s][vp 1 0 0 8144 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, time to go![n][w][e]

[msg SAFE_EXIT_LOW_01_PC08_me [Haru]]
[s][vp 1 0 0 7144 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Now, let's go.[n][w][e]

[msg SAFE_EXIT_LOW_01_PC09_me [Akechi]]
[s][vp 8 2 1 8099 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Now, let us depart.[n][w][e]

[msg SAFE_EXIT_LOW_01_PC10_me [[f 4 31 10 0]]]
[s][vp 1 0 0 10144 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's get going![n][w][e]

[msg SAFE_EXIT_LOW_02_PC02_me [Ryuji]]
[s][vp 1 0 0 2145 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, let's do this![n][w][e]

[msg SAFE_EXIT_LOW_02_PC03_me [Morgana]]
[s][vp 1 0 0 3145 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Come on! The Treasure awaits![n][w][e]

[msg SAFE_EXIT_LOW_02_PC04_me [Ann]]
[s][vp 1 0 0 4145 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, let's get back to exploring.[n][w][e]

[msg SAFE_EXIT_LOW_02_PC05_me [Yusuke]]
[s][vp 1 0 0 5145 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, back to work.[n][w][e]

[msg SAFE_EXIT_LOW_02_PC06_me [Makoto]]
[s][vp 1 0 0 6145 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Got it. Let's get back to work.[n][w][e]

[msg SAFE_EXIT_LOW_02_PC07_me [Futaba]]
[s][vp 1 0 0 8145 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]They're not on to us yet.[n]All right, let's roll![n][w][e]

[msg SAFE_EXIT_LOW_02_PC08_me [Haru]]
[s][vp 1 0 0 7145 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right then, shall we go?[n][w][e]

[msg SAFE_EXIT_LOW_02_PC09_me [Akechi]]
[s][vp 8 2 1 8096 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We don't know what may be waiting[n]for us. Let us explore carefully.[n][w][e]

[msg SAFE_EXIT_LOW_02_PC10_me [[f 4 31 10 0]]]
[s][vp 1 0 0 10145 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's get back to it![n][w][e]

[msg SAFE_EXIT_LOW_03_PC02_me [Ryuji]]
[s][vp 1 0 0 2146 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, time to go.[n][w][e]

[msg SAFE_EXIT_LOW_03_PC03_me [Morgana]]
[s][vp 1 0 0 3146 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ready? Let's go, Joker![n][w][e]

[msg SAFE_EXIT_LOW_03_PC04_me [Ann]]
[s][vp 1 0 0 4146 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, let's move on![n][w][e]

[msg SAFE_EXIT_LOW_03_PC05_me [Yusuke]]
[s][vp 1 0 0 5146 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's get back to exploring.[n][w][e]

[msg SAFE_EXIT_LOW_03_PC06_me [Makoto]]
[s][vp 1 0 0 6146 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Roger, let's go.[n]We're counting on you, Joker![n][w][e]

[msg SAFE_EXIT_LOW_03_PC07_me [Futaba]]
[s][vp 1 0 0 8146 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hang on! I'm getting ready![n][w][e]

[msg SAFE_EXIT_LOW_03_PC08_me [Haru]]
[s][vp 1 0 0 7146 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Now, let's get back to work.[n][w][e]

[msg SAFE_EXIT_LOW_03_PC09_me [Akechi]]
[s][vp 1 0 0 9146 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, back to work.[n][w][e]

[msg SAFE_EXIT_LOW_03_PC10_me [[f 4 31 10 0]]]
[s][vp 1 0 0 10146 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Just a little more![n][w][e]

[msg SAFE_EXIT_HIGH_01_PC02_m [Ryuji]]
[s][vp 1 0 0 2147 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right... Security's high,[n]so let's be careful.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC03_m [Morgana]]
[s][vp 1 0 0 3147 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Remember. We can always[n]withdraw if we need to.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC04_m [Ann]]
[s][vp 1 0 0 4147 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Come on, let's go[n]a little more.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC05_m [Yusuke]]
[s][vp 1 0 0 5147 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Watch the Shadows' movement.[n]It grows dangerous.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC06_m [Makoto]]
[s][vp 1 0 0 6147 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The situation is dangerous.[n]Let's stay focused.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC07_m [Futaba]]
[s][vp 1 0 0 8147 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm... This isn't good.[n]We're gonna hafta work hard.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC08_m [Haru]]
[s][vp 1 0 0 7147 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]They're on guard.[n]We need to be ready.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC09_m [Akechi]]
[s][vp 1 0 0 9147 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We must refocus. Do not let[n]yourself become careless.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC10_m [[f 4 31 10 0]]]
[s][vp 1 0 0 10147 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Be careful—the enemy's still on alert.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC02_m [Ryuji]]
[s][vp 1 0 0 2148 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hell yeah! Security's tough,[n]so put your game face on.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC03_m [Morgana]]
[s][vp 1 0 0 3148 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's continue exploring...[n]but be extra careful![n][w][e]

[msg SAFE_EXIT_HIGH_02_PC04_m [Ann]]
[s][vp 1 0 0 4148 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's be careful. We need to[n]watch the enemy's movement.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC05_m [Yusuke]]
[s][vp 1 0 0 5148 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's fun to work under[n]pressure, but be ready[n]to back off if need be.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC06_m [Makoto]]
[s][vp 1 0 0 6148 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, but it's risky.[n]Let's be careful.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC07_m [Futaba]]
[s][vp 1 0 0 8148 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's really dangerous right now.[n]Don't let your guard down.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC08_m [Haru]]
[s][vp 1 0 0 7148 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's a bit dangerous; we[n]need to watch the enemy.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC09_m [Akechi]]
[s][vp 1 0 0 9148 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]They're on alert outside. We[n]should proceed with caution.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC10_m [[f 4 31 10 0]]]
[s][vp 1 0 0 10148 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Be ready for anything.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC02_m [Ryuji]]
[s][vp 1 0 0 2149 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, let's be careful, Joker.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC03_m [Morgana]]
[s][vp 1 0 0 3149 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm... let's be even more[n]cautious than usual, Joker.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC04_m [Ann]]
[s][vp 1 0 0 4149 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The security level's high,[n]so let's be cautious.[n]Don't push it.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC05_m [Yusuke]]
[s][vp 1 0 0 5149 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]They're aware of us, Joker.[n]Do not rush in.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC06_m [Makoto]]
[s][vp 1 0 0 6149 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]They're on high alert.[n]Let's proceed with caution.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC07_m [Futaba]]
[s][vp 1 0 0 8149 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Their security's pretty tight.[n]Show me your stuff, Joker![n][w][e]

[msg SAFE_EXIT_HIGH_03_PC08_m [Haru]]
[s][vp 1 0 0 7149 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's take caution, okay?[n]Joker, don't press your luck.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC09_m [Akechi]]
[s][vp 1 0 0 9149 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]They're wary of us, Joker.[n]Do not be reckless.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC10_m [[f 4 31 10 0]]]
[s][vp 1 0 0 10149 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It'll be dangerous, but hopefully[n]we can still make some progress.[n][w][e]

[msg D_RECOVERY_EV_mes01]
[s]You have [clr 6]regained some HP[clr 27] by resting.[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Phew... Let's rest up, dude.[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3154 65535 0]All right! I'm alive again![n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0_3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We should stop for now.[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0_4 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I believe we have earned[n]ourselves a brief respite.[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0_5 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's rest for a minute.[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0_6 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahhh, time to relax for a bit.[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0_7 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's rest up.[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Shall we idle for a moment?[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC1 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Should we take a little break?[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mannn, I'm pooped.[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3160 65535 0]Ahhh, I feel rejuvenated![n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0_3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Phew... I could use a break.[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0_4 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let us pause here to[n]muster our strength.[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0_5 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Phew... I need to get my[n]heart rate down somehow.[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0_6 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahhh... So refreshed.[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0_7 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I think we should rest,[n]even if only a little bit.[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let us pause for now.[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC1 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's rest for a bit here.[n][w][e]

[msg SAFE_ACTIVE_IN_FIRST_PC0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The Treasure's just up ahead.[n]Come on, Joker. Let's go.[n][w][e]

[msg SAFE_ACTIVE_IN_SECOND_PC [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The Treasure is a little far from[n]here... Are you sure this is the[n]best starting spot, Joker?[n][w][e]

[msg SAFE_ACTIVE_IN_DISTANT_P [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh? This is nowhere near the[n]Treasure... You remember that's[n]why we're here today, right?[n][w][e]

[msg SAFE_ACTIVE_MES_PC03_mes [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]It looks like this room is still safe.[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We can't stay here long though.[n]Let's get over to the Treasure[n]once we're rested up![n][w][e]

[msg SAFE_ACTIVE_IN_DISCOVERY [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1022 65535 0]Huh, I wasn't expecting to[n]find a new safe room today...[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We can't stay here long though.[n]Let's get over to the Treasure[n]once we're rested up![n][w][e]

[msg SAFE_ACTIVE_EXIT_PC03_me [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1052 65535 0]Our only objective today is[n]stealing the Treasure! Let's go![n][w][e]

[msg SAFE_EXIT_D01_02_EX_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's go. Just remember[n]to be careful in here.[n][w][e]

[sel PROPOSAL_TALK_SEL top]
[s]Accept the proposal.[f 2 7 0 0 106 1][e]
[s]Do not accept the proposal.[f 2 7 0 0 106 1][e]

[sel PROPOSAL_REST_SEL top]
[s]Accept the proposal.[f 2 7 0 0 106 1][e]
[s]Do not accept the proposal.[f 2 7 0 0 106 1][e]

[msg VELVET_SPECIAL_TIME_REMI]
[s]I'm feeling a bit on edge...[n]I think there could be an active[n]alarm in the Velvet Room...[n][w][e]

[sel START_CHECK_SEL top]
[s]Head to most recent safe room[e]
[s]Infiltrate as is[e]
[s]Don't go in yet[e]

[msg START_CHECK_MES [Morgana]]
[s][bup 0 3 0 65535 0]So, where do you want to start exploring[n]from?[n][w][e]

[msg START_CHECK_MES_NEXT [Morgana]]
[s][bup 0 3 0 65535 0]Make sure you choose your starting[n]location carefully.[n][w][e]

[sel DUNGEON_EXIT_SEL top]
[s]*Special[e]
[s]Return to the real world[e]
[s]Don't leave yet[e]

[sel DUNGEON_EXIT_154_SEL top]
[s]Go to the city[e]
[s]Return to the real world[e]
[s]Don't leave yet[e]

[sel DUNGEON_EXIT_155_SEL top]
[s]Go to the city[e]
[s]Return to the real world[e]
[s]Don't leave yet[e]

[msg D01_EXIT_MES [Metaverse Navigator]]
[s]Now returning to the real world from[n]Kamoshida's Palace. Thank you for your[n]hard work.[n][w][e]

[msg D02_EXIT_MES [Metaverse Navigator]]
[s]Now returning to the real world from[n]Madarame's Palace. Thank you for your[n]hard work.[n][w][e]

[msg D03_EXIT_MES [Metaverse Navigator]]
[s]Now returning to the real world from[n]Kaneshiro's Palace. Thank you for your[n]hard work.[n][w][e]

[msg D04_EXIT_MES [Metaverse Navigator]]
[s]Now returning to the real world from[n]Futaba's Palace. Thank you for your[n]hard work.[n][w][e]

[msg D05_EXIT_MES [Metaverse Navigator]]
[s]Now returning to the real world from[n]Okumura's Palace. Thank you for your[n]hard work.[n][w][e]

[msg D06_EXIT_MES [Metaverse Navigator]]
[s]Now returning to the real world from[n]Niijima's Palace. Thank you for your[n]hard work.[n][w][e]

[msg D07_EXIT_MES [Metaverse Navigator]]
[s]Now returning to the real world from[n]Shido's Palace. Thank you for your hard[n]work.[n][w][e]

[msg D08_EXIT_MES [Metaverse Navigator]]
[s]Now returning to the real world from[n]Mementos. Thank you for your hard work.[n][w][e]

[msg D10_EXIT_MES [Metaverse Navigator]]
[s]Now returning to the real world from[n]Maruki's Palace. Thank you for your hard[n]work.[n][w][e]

[msg DUNGEON_ROUTE_COMP_PC03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]We've secured our route to the Treasure...[n]Do you want to get out of here?[n][w][e]

[msg DUNGEON_ROUTE_COMP_PC04_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]I guess all we can do now is prepare for[n]the Day of Fates... So, what now? Do you[n]want to head back?[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're already goin' back? We haven't[n]done nothing...[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What's wrong, Joker? We haven't done[n]anything yet.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh? You want to go home already?[n]But we haven't done anything.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What seems to be the matter? We have[n]yet to explore at all today.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What's wrong—you want to go back?[n]Despite not having done anything yet?[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh? We're going home, Joker? It feels[n]like we haven't even done anything today.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC08 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, what's the matter? We haven't[n]managed to do a single thing so far today.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC09 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm? You wish to return? But we have[n]yet to accomplish anything meaningful[n]in our time here.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC10 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh, we're going back? I feel like we[n]haven't actually done anything yet...[n][w][e]

[msg DUNGEON_EXIT_01_PC02_mes [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7072 65535 0]What's up? You wanna head back and[n]regroup?[n][w][e]

[msg DUNGEON_EXIT_01_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1059 65535 0]Hm? Do you want to retreat, Joker?[n][w][e]

[msg DUNGEON_EXIT_01_PC04_mes [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6072 65535 0]What's wrong? Do you want to pull out[n]of here?[n][w][e]

[msg DUNGEON_EXIT_01_PC05_mes [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4072 65535 0]Do you wish to reconvene, Joker?[n][w][e]

[msg DUNGEON_EXIT_01_PC06_mes [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2120 65535 0]Hm? You want to head back?[n][w][e]

[msg DUNGEON_EXIT_01_PC07_mes [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9136 65535 0]It might be a good idea to go home and[n]regroup.[n][w][e]

[msg DUNGEON_EXIT_01_PC08_mes [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3001 65535 0]Is it time for us to withdraw?[n][w][e]

[msg DUNGEON_EXIT_01_PC09_mes [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8130 65535 0]Oh? Are we retreating?[n][w][e]

[msg DUNGEON_EXIT_01_PC10_mes [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57089 65535 0]Oh, should we regroup?[n][w][e]

[msg DUNGEON_EXIT_01_PC11_mes [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8130 65535 0]Oh? Are we retreating?[n][w][e]

[msg ATD_EXIT_REMIND_FLOWER_V [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 53101 65535 0]Jose said flowers disappear once you[n]leave Mementos...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]......[n][w][e]

[msg ATD_EXIT_REMIND_FLOWER_V_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 53101 65535 0]Jose said flowers disappear once you[n]leave Mementos...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The amount of flowers you've collected[n]so far is [clr 2][var 0][clr 27]. Do you still want to leave?[n][w][e]

[msg ATD_EXIT_REMIND_FLOWER_V_3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Hm? Are we heading back?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The amount of flowers you have right[n]now is [clr 2][var 0][clr 27]. If you leave, they'll disappear.[n][w][e]

[msg ATD_EXIT_CABLE_VANISHED_ [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]We did everything we needed to.[n]Wanna call it a day?[n][w][e]

[msg ATD_EXIT_CANCEL_CABLE_VA [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1035 65535 0]All right. Let's explore a bit more.[n][w][e]

[msg D_EXIT_OK_01_PC02_mes [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7050 65535 0]Mkay, let's get goin'.[n][w][e]

[msg D_EXIT_OK_01_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1049 65535 0]Mm, let's head back for today.[n][w][e]

[msg D_EXIT_OK_01_PC04_mes [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6049 65535 0]Okay, let's go.[n][w][e]

[msg D_EXIT_OK_01_PC05_mes [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4049 65535 0]Hm, very well. Let us head back.[n][w][e]

[msg D_EXIT_OK_01_PC06_mes [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2049 65535 0]Okay, we can call it a day.[n][w][e]

[msg D_EXIT_OK_01_PC07_mes [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9050 65535 0]Aw yeah, let's go home![n][w][e]

[msg D_EXIT_OK_01_PC08_mes [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3049 65535 0]Very well. Let's head home.[n][w][e]

[msg D_EXIT_OK_01_PC09_mes [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8035 65535 0]That is a good idea. In that case, let us[n]get out of here.[n][w][e]

[msg D_EXIT_OK_01_PC10_mes [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57066 65535 0]Understood. Shall we head back then?[n][w][e]

[msg D_EXIT_OK_01_PC11_mes [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8138 65535 0]That is a good idea. In that case, let us[n]get out of here.[n][w][e]

[sel DUNGEON_EXIT_151_EX_SEL top]
[s]*Special[e]
[s]Activate the [clr 6]Metaverse Nav[clr 27][e]
[s]Don't activate the nav[e]

[msg DUNGEON_EXIT_D01_EX_mes [Ryuji]]
[s][bup 0 2 0 65535 0]If we use that nav thing around here,[n]I'm thinkin' it'll get us back to the real[n]world.[n][w][e]

[msg D_EXIT_OK_D01_EX_mes [Ryuji]]
[s][bup 0 2 0 65535 0]Sweet, it worked![n][w][e]

[msg D_EXIT_NG_D01_EX_mes [Ryuji]]
[s][bup 0 2 0 65535 0]What're you doin'? Let's get outta here![n][w][e]

[msg D_EXIT_CANCEL_PC02_mes [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7080 65535 0]Mkay. I can keep goin' if that's what you[n]want.[n][w][e]

[msg D_EXIT_CANCEL_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1096 65535 0]Right. Well then, let's continue our[n]exploration.[n][w][e]

[msg D_EXIT_CANCEL_PC04_mes [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6096 65535 0]Okay, let's look around in here a little[n]bit longer then.[n][w][e]

[msg D_EXIT_CANCEL_PC05_mes [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4052 65535 0]I agree. I expect there are still places[n]yet unseen.[n][w][e]

[msg D_EXIT_CANCEL_PC06_mes [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2081 65535 0]Right. Let's keep going.[n][w][e]

[msg D_EXIT_CANCEL_PC07_mes [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9130 65535 0]Gotcha. Let's hang in there a bit longer.[n][w][e]

[msg D_EXIT_CANCEL_PC08_mes [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3051 65535 0]Mm-hm. Well, let's get back to our[n]exploration.[n][w][e]

[msg D_EXIT_CANCEL_PC09_mes [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8070 65535 0]Very well, let us push onward a bit further.[n][w][e]

[msg D_EXIT_CANCEL_PC10_mes [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57163 65535 0]Yes. Let's go just a bit further.[n][w][e]

[msg D_EXIT_CANCEL_PC11_mes [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8137 65535 0]Very well. But don't let your guard down.[n][w][e]

[msg ALERT_MAX_EXIT_mes00 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1039 65535 0]Ngh, this is bad! The security level in[n]here is too high![n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Our lives will be in danger if we keep[n]exploring any longer.[n][w][e]
[s]We need to retreat, Joker![n][w][e]

[msg ALERT_MAX_EXIT_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]J-Just hold a sec. We could prolly go a little—[n][w][e]

[msg ALERT_MAX_EXIT_mes02 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1082 65535 0]The number of Shadows is rapidly[n]increasing! We need to leave! Hurry![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]Dude, what!? We already sent the[n]calling card![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All that hard work's gonna be for nothing[n]if we don't steal the Treasure today![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC03 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1040 65535 0]What? Have you not been listening to[n]anything I said!?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If we don't take the Treasure today,[n]everything we've done up to now will[n]go to waste![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC04 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6039 65535 0]Nope! Not happening! Absolutely,[n]definitely not![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All our preparation will go right out the[n]window if we don't take the Treasure[n]today![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4104 65535 0]You want to head back? Haha, it is rare[n]to hear you joke in such a manner during[n]a mission.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let us return to the task at hand, Joker.[n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2043 65535 0]Come now, no complaining. Are you not[n]our leader?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We must take the Treasure today, no matter[n]the cost![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Kk, let's go home...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9100 65535 0]Uh... That was a joke. No going home now.[n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC08 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I thought we can't pull out once we send[n]the calling card...[n][w][e]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3136 65535 0]Don't worry, Joker. You have all of our[n]support![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC09 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8112 65535 0]You wish to leave after coming this far?[n]How unlike you.[n][w][e]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We should try to do this today though.[n]I will lend you my aid.[n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC10 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57118 65535 0]I thought we couldn't turn back once[n]the calling card was sent?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's go, Joker. I'll give it my all too.[n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC11 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8018 65535 0]We've made it this far. We can't turn back[n]now.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's finish this.[n][w][e]

[msg SAFEROOM_EXIT_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You really want to head back, Joker?[n][w][e]

[msg SAFEROOM_EXIT_PC07_mes [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We really heading home, Joker?[n][w][e]

[msg D01_04_e166_015_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7103 65535 0]Mkay, all we gotta do now is steal the[n]Treasure that shows up, yeah? It's finally[n]time.[n][w][e]

[msg D01_04_e166_015_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But we need to send the calling card first.[n]When should we do it?[n][w][e]

[msg D01_04_e166_015_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Just hold on. Let's retreat for now, then[n]we can talk more about that stuff back[n]at the hideout.[n][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1030 65535 0]Oh, and well done today![n][w][e]

[msg D02_MISSION_POINT_PC03_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1172 65535 0]We should leave and try to disengage[n]the courtyard security.[n][w][e]

[msg D02_04_e210_240_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7153 65535 0]Well, I'm still kinda worried... but we[n]gotta do this.[n][w][e]

[msg D02_04_e210_240_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4076 65535 0]I cannot even begin to fathom what[n]Madarame's Treasure may be...[n][w][e]

[msg D02_04_e210_240_mes03 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Either way, we'll steal it for sure.[n]Oh, and you all did great today![n][w][e]

[msg D03_FIRST_END_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1172 65535 0]The cognitive door is closed. Should we[n]head back?[n][w][e]

[msg D06_FIRST_END_PC06_mes [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2118 65535 0]We'll need to regroup back in the real[n]world for now.[n][w][e]

[msg D07_FIRST_END_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]All right, Joker. Let's retreat![n][w][e]

[msg D01_EXIT_NG_EV01_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Where are you going, Joker?[n][w][e]
[s]Haven't we checked those cells enough?[n]Let's look further inside the castle next.[n][w][e]

[msg D01_EXIT_NG_EV01_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We'll have to pass through the entrance[n]hall to get there... but wasn't the door[n]locked?[n][w][e]
[s]It'll be impossible unless we can find[n]another route to the first floor of that[n]hall.[n][w][e]

[msg D07_DUNGEON_EXIT_SC_mes0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]C'mon, we came all this way. Let's at least[n]try checkin' around a little more first.[n][w][e]

