[msg MSG_CONVINI_Last_NormalE [Nanami]]
[s][f 4 23 1 1 3 5 65534 0][vp 8 2 1 58551 1 0]Welcome... Oh, [f 4 1]-kun.[n][w][e]
[s]I didn't know you had work today...[n]Oh! You're going back home.[n][w][e]
[s]I see now. That seems like a big deal.[n]Thanks for stopping by to let me know![n][w][e]

[msg MSG_CONVINI_Last_TrueEnd [Nanami]]
[s][f 4 23 1 1 3 5 65534 0][vp 8 2 1 58551 1 0]Welcome... Oh, [f 4 1]-kun![n][w][e]
[s]I didn't know you had work today...[n]What!? You're going back home!?[n][w][e]
[s]I see now... It's going to be lonely[n]here, with my comrade-in-arms gone,[n]you know?[n][w][e]
[s]Well... It was a pleasure working with[n]you! I hope everything works out on[n]your end![n][w][e]

[msg MSG_CONVINI_GREETING [Convenience Store Clerk]]
[s][f 4 23 1 1 3 5 65534 0][vp 8 2 1 0 1 0]Welcome! We're having a huge sale[n]on all of our hot food items![n][w][e]

[msg MSG_CONVINI_GREETING_nam [Nanami]]
[s][f 4 23 1 1 3 5 65534 0][vp 8 2 1 0 1 0]Welcome! We're having a huge sale[n]on all of our hot food items![n][w][e]

[msg MSG_Tutorial_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]That reminds me, don't you work[n]part-time here?[n][w][e]

[msg MSG_Tutorial_End [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]So, what are you going to do?[n][w][e]

[msg MSG_Friday [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Today's [clr 2]Friday[clr 27], so there'll be more[n]customers than usual. If the manager sees[n]you doing well, you might get a reward.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]So, what're you gonna do?[n][w][e]

[msg MSG_7tokubetubi [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Today's a [clr 2]double-points day[clr 27]. If the[n]manager sees you doing well, you[n]might get a reward.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]So, what're you gonna do?[n][w][e]

[sel MSG_CONVINI_ACT_THINK_SE top]
[s]I'll go to work.[e]
[s]Let's do some shopping.[f 2 7 0 0 106 1][e]
[s]Let's leave.[f 2 7 0 0 106 1][e]

[msg MSG_CONVINI_GREETING_RE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]You've finished already?[n][w][e]

[msg MSG_CONVINI_GREETING_6_8 [Convenience Store Clerk]]
[s][f 4 23 1 1 3 5 65534 0][vp 8 2 1 0 1 0]Welcome! Keeping you cool this[n]summer! [f 2 5 3 9999 0][n]is now on sale![n][w][e]

[msg MSG_CONVINI_GREETING_6_8_2 [Nanami]]
[s][f 4 23 1 1 3 5 65534 0][vp 8 2 1 0 1 0]Welcome! Keeping you cool this[n]summer! [f 2 5 3 9999 0][n]is now on sale![n][w][e]

[msg MSG_CONVINI_GREETING_9 [Convenience Store Clerk]]
[s][f 4 23 1 1 3 5 65534 0][vp 8 2 1 0 1 0]Welcome! A classic for fall and[n]winter! [f 2 5 3 9999 0],[n]is now on sale![n][w][e]

[msg MSG_CONVINI_GREETING_9_n [Nanami]]
[s][f 4 23 1 1 3 5 65534 0][vp 8 2 1 0 1 0]Welcome! A classic for fall and[n]winter! [f 2 5 3 9999 0],[n]is now on sale![n][w][e]

[msg MSG_Convini_NotShiftDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Hm...? It's not time for your shift yet.[n][w][e]

[msg MND_Conveni_ParamUpInfo]
[s]I feel like my [f 4 11 1][clr 26][f 4 12 1][clr 27][n]are going to improve soon...[n][w][e]

[msg MND_Conveni_ParamEndInfo]
[s]I think I have enough[n][f 4 11 1][clr 26][f 4 12 1][clr 27] already...[n][w][e]

[msg MSG_Conveni_Ask [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]You can raise your [f 4 11 1][clr 26][f 4 12 1][clr 27] by[n]learning how to handle customers. Do[n]you want to work this part-time job?[n][w][e]

[sel SEL_BaitoFix top]
[s]I'll work.[e]
[s]Let me think about it.[e]

[msg MSG_CONVINI_OK_BAITO_1ST [Convenience Store Clerk]]
[s][f 4 23 1 1 3 5 65534 0][vp 8 2 1 58554 1 0]Oh, are you the one who applied for[n]the part-time job? I'll call the manager,[n]please wait a moment.[n][w][e]

[msg MSG_CONVINI_OK_BAITO_NOR [Nanami]]
[s][f 4 23 1 1 3 5 65534 0][vp 8 2 1 58555 1 0]Oh, you're coming in today?[n]That'd be so helpful![n][w][e]

[msg MSG_CONVINI_END [Convenience Store Clerk]]
[s][f 4 23 1 1 3 5 65534 0][vp 8 2 1 0 1 0]Thank you very much![n][w][e]

[msg MSG_CONVINI_END_named [Nanami]]
[s][f 4 23 1 1 3 5 65534 0][vp 8 2 1 0 1 0]Thank you very much![n][w][e]

[msg MSG_LastKeyfree [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]We can't wait any longer...[n]We have to prepare, and fast![n][w][e]

