[msg dummy_mes]
[s]…[n][w][e]

[msg MSG_FIRST_01 [モルガナ]]
[s]第4路線、切替ポイント初進入メッセージ(仮)[n][w][e]

[msg MSG_FIRST_02 [モルガナ]]
[s]第4路線、第1区画初進入メッセージ(仮)[n][w][e]

[msg MSG_FIRST_03 [モルガナ]]
[s]第4路線、第2区画初進入メッセージ(仮)[n][w][e]

[msg MSG_FIRST_04 [モルガナ]]
[s]第4路線、第3区画初進入メッセージ(仮)[n][w][e]

[msg MSG_FIRST_05 [モルガナ]]
[s]第4路線、第4区画初進入メッセージ(仮)[n][w][e]

[msg MSG_FIRST_06 [モルガナ]]
[s]第4路線、第5区画初進入メッセージ(仮)[n][w][e]

[msg MSG_FIRST_07 [モルガナ]]
[s]第4路線、第6区画初進入メッセージ(仮)[n][w][e]

[msg MSG_FIRST_08 [モルガナ]]
[s]第4路線、第7区画初進入メッセージ(仮)[n][w][e]

[msg MSG_FIRST_09 [モルガナ]]
[s]第4路線、第8区画初進入メッセージ(仮)[n][w][e]

[msg MSG_FIRST_10 [モルガナ]]
[s]第4路線、第9区画初進入メッセージ(仮)[n][w][e]

[msg MSG_QUEST_BRANCH [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1130 65535 0]I can sense our target somewhere in this[n]area![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's scour this floor for them![n][w][e]

[msg MSG_QUEST_BRANCH_ex_27 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1131 65535 0]This is where that horrible cheater was...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We'll need some kind of plan if we want[n]to take him down.[n][w][e]

[msg MSG_QUEST_BRANCH_ex_72 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1037 65535 0]No, we should focus on what's in front of[n]us for now. I feel the presence of the target[n]ahead...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's search the whole area.[n][w][e]

[msg MSG_QUEST_FLOOR_NEIGHBOR [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]I can sense the target's presence nearby![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's coming from the next area! Let's go[n]check it out![n][w][e]

[msg MSG_QUEST_FLOOR_NEAR_LOW [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1130 65535 0]Hm, I think I can sense the target's[n]presence nearby.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It feels like it's in an area a little bit[n]further past here.[n][w][e]

[msg MSG_QUEST_FLOOR_MIDDLE_L [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]Hm, I feel the target's presence.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's still far though. They must be deeper[n]inside.[n][w][e]

[msg MSG_QUEST_FLOOR_FAR_LOWE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1192 65535 0]It's only slight, but I can sense the target's[n]presence.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It seems like it's coming from an area[n]much deeper down.[n][w][e]

[msg MSG_QUEST_FLOOR_NEIGHBOR_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1029 65535 0]I sense the target—super close![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's coming from an area above us![n]Let's go check it out![n][w][e]

[msg MSG_QUEST_FLOOR_NEAR_UPP [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1130 65535 0]Hm, I think I can sense the target's[n]presence nearby.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If we go a little back towards where we[n]came from, we might be able to reach[n]its location.[n][w][e]

[msg MSG_QUEST_FLOOR_MIDDLE_U [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]Hm, I feel the target's presence.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But it's still far away. We should probably[n]head up a ways.[n][w][e]

[msg MSG_QUEST_FLOOR_FAR_UPPE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1192 65535 0]I'm getting a slight reading from the target.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It feels like it's way back from where we[n]came from...[n][w][e]

[msg MSG_SHOP_1ST_MSG01 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56704 65535 0]Oh, mister![n][w][e]

[msg MSG_SHOP_1ST_MSG02 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]When you get flowers, bring them to me![n]I'll go ahead of you guys![n][w][e]

[msg MSG_ACCIDENT_TUTORIAL01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Whoa! What the hell happened?[n]It's so dark![n][w][e]

[msg MSG_ACCIDENT_TUTORIAL02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Mementos is an amalgamation of the[n]people's cognition. This can affect the[n]environment, as well as the structure.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]It hasn't been like this in a long time,[n]but it seems like the darkness won't be[n]the only thing we'll have to deal with.[n][w][e]

[msg MSG_ACCIDENT_TUTORIAL03 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]You mean we have even more stuff[n]to worry about?[n][w][e]

[msg MSG_ACCIDENT_TUTORIAL04 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]In a way... I can sense rare Shadows all[n]around us.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]We should explore this area for a bit—[n]despite the darkness.[n][w][e]

[msg MSG_ACCIDENT_TUTORIAL05 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 7 0 0]I don't really wanna stick around here,[n]but if you say so, then I guess we can go[n]for it...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 8 0 0]Joker, just... drive extra safe or something![n][w][e]

[msg MSG_QUEST_AFTER_FLOOR_NE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The target is coming from the next area![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's go check that area out.[n][w][e]

[msg MSG_QUEST_AFTER_FLOOR_NE_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The target is close.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It feels like it's in an area a little bit[n]further past here.[n][w][e]

[msg MSG_QUEST_AFTER_FLOOR_MI [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's still far though. They must be deeper[n]inside.[n][w][e]

[msg MSG_QUEST_AFTER_FLOOR_FA [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The target's presence is very weak.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Much deeper than where we are now.[n][w][e]

[msg MSG_QUEST_AFTER_FLOOR_NE_3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The target's close![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The area right before! Let's go![n][w][e]

[msg MSG_QUEST_AFTER_FLOOR_NE_4 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The target's close.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If we go a little back towards where we[n]came from, we might be able to reach its[n]location.[n][w][e]

[msg MSG_QUEST_AFTER_FLOOR_MI_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The target is still far away... Let's go back[n]towards where we came from.[n][w][e]

[msg MSG_QUEST_AFTER_FLOOR_FA_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The target's presence is very weak.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It feels like it's way back from where we[n]came from...[n][w][e]

[msg D191_01_miniEV01_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The paths seem to have changed since[n]last time.[n][w][e]

[msg D191_01_miniEV01_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is so creepy. What's going on?[n][w][e]

[msg D191_01_miniEV01_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This Palace is so twisted... It must be[n]worth checking out! Let's go![n][w][e]

[msg MSG_FIRST_01_02_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, there it is! The thing I want to[n]check on is inside![n][w][e]

[msg AT_D_FIRST_02_01_EV01_me [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7021 65535 0]We bumped into that guy again.[n]Uh, what was his name...[n][w][e]

[msg AT_D_FIRST_02_01_EV01_me_2 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You mean Jose, right? He's such an[n]adorable little kid, isn't he?[n][w][e]

[msg AT_D_FIRST_02_01_EV01_me_3 [Morgana]]
[s][bup 0 3 10 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Panther!? I'm adorable too, you know![n][w][e]

[msg AT_D_FIRST_02_01_EV01_me_4 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6071 65535 0]Yeah, yeah. Anyway, he said he was[n]looking for flowers and wanted our[n]help, right?[n][w][e]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sounds like he'll reward us too. Doesn't[n]it seem like helping him would be worth it?[n][w][e]

[msg AT_D_FIRST_02_01_EV01_me_5 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I guess. I am kinda curious about what[n]we'll get... Why don't we go look for[n]him? He's probably still around here.[n][w][e]

[msg AT_D_FIRST_02_01_EV01_me_6 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]Looking for him is fine and all, but[n]remember that it's risky to stay in[n]one area for too long.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There's this one really fearsome Shadow[n]in Mementos... If we hang around too[n]long, it'll hunt us down.[n][w][e]

[msg AT_D_FIRST_02_01_EV01_me_7 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]Huh!? The hell're you talkin' about!?[n]Why didn't you tell us this before!?[n][w][e]

[msg AT_D_FIRST_02_01_EV01_me_8 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1052 65535 0]We should be fine if we find him quickly.[n]All right, let's get going.[n][w][e]

[msg MSG_FIRST_02_02_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You know, this Palace's security level[n]doesn't seem to change, even if the[n]enemies spot you.[n][w][e]

[msg MSG_FIRST_02_02_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mementos is different. While other[n]Palaces exist because of just one[n]person, this one's from the public.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]From that perspective, it'd take more[n]than a few intruders to make a mark[n]on the security level.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You'd have to do something so bad that[n]the entire public sees you as an enemy.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So... be careful, okay, Skull?[n][w][e]

[msg MSG_FIRST_02_02_mes03 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, shut up![n][w][e]

[msg MSG_FIRST_02_05_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Oh, Joker. I almost forgot to mention...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]In Mementos, sometimes the road will[n]be unnaturally blocked.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The walls are pretty weak in those spots.[n]I should be able to break through them[n]no problem.[n][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If you see any while we're exploring,[n]try busting right through them![n][w][e]

[msg MSG_FIRST_02_05_mes02]
[s]In Mementos, you can press [clr 2][f 1 10 22][clr 27] to destroy[n]weak walls that look different from normal.[n][w][e]
[s]Try to break these walls whenever you[n]can. There may be something hidden[n]behind them.[n][w][e]

[msg MSG_FIRST_02_05_mes03 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6197 65535 0]Uh, just let us know before you do that...[n]Don't go crashing into any walls before[n]we can buckle up.[n][w][e]

[msg MSG_FIRST_02_06_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey... The next area has a different feel[n]to it somehow.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What is this...?[n][w][e]

[msg MSG_FIRST_02_07_mes01 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, that wall...[n][w][e]

[msg MSG_FIRST_02_07_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's the same type of wall we opened up[n]last time... Does this one open, too?[n][w][e]

[msg MSG_FIRST_02_07_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's check it out, Joker![n][w][e]

[msg MSG_FIRST_03_01_mes01 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]D-Doesn't this look different from[n]how it was before?[n][w][e]

[msg MSG_FIRST_03_01_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Looks like it'll be a new area from here[n]on. I'm starting to understand how this[n]place works...[n][w][e]

[msg MSG_FIRST_03_01_mes03 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yes... It is quite a marvel to find[n]the subway system down here.[n][w][e]

[msg MSG_FIRST_03_01_mes04 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uh, Earth to Yusuke! It's always been[n]like that![n][w][e]

[msg MSG_FIRST_03_02_mes01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey. How many areas are on this floor,[n]anyway?[n][w][e]

[msg MSG_FIRST_03_02_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The last floor had seven areas, but the[n]one before that only had two, right?[n][w][e]

[msg MSG_FIRST_03_02_mes03 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I suppose it varies, depending upon[n]the location...[n][w][e]

[msg MSG_FIRST_03_02_mes04 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Guess that means it ain't easy to tell how[n]much of a floor we got left to cover, huh?[n][w][e]

[msg MSG_FIRST_03_02_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's right. We won't know how many[n]areas are on a floor until we make it to[n]the end.[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But judging by the vibe I'm getting from[n]the Shadows... this floor isn't any smaller[n]than the last.[n][w][e]

[msg MSG_FIRST_03_05_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, this place is like a waiting room![n]Maybe we can chill here a bit.[n][w][e]

[msg MSG_FIRST_03_07_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh? The next area feels different from[n]the ones before...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Our goal may be close.[n][w][e]

[msg MSG_FIRST_03_08_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, look at that wall! Let's check and[n]see if it'll open up![n][w][e]

[msg MSG_FIRST_04_01_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh... The whole ambience changed[n]again...[n][w][e]

[msg MSG_FIRST_04_01_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I never realized how creepy the subway[n]system could be. Inside the train, you[n]don't even notice.[n][w][e]

[msg MSG_FIRST_04_01_mes03 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I agree. Perhaps it is like the darkness[n]in all men's hearts. Always there, never[n]perceived...[n][w][e]

[msg MSG_FIRST_04_01_mes04 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Haha, you talkin' about art stuff again?[n][w][e]

[msg MSG_FIRST_04_01_mes05 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's a new area from this point on.[n]Let's be careful heading in![n][w][e]

[msg MSG_FIRST_04_03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The last place had eight areas, so[n]I wonder if this one will be just as big...[n][w][e]

[msg MSG_FIRST_04_03_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're only in the third area. I suppose[n]this leisure ride will continue on for[n]a while longer.[n][w][e]

[msg MSG_FIRST_04_03_mes03 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]How is this supposed to be leisurely?[n][w][e]

[msg MSG_FIRST_04_03_mes04 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cut him some slack. Yusuke just wanted[n]to say somethin' cool.[n][w][e]

[msg MSG_FIRST_04_06_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, a waiting room. It seems we can rest[n]and find repose here.[n][w][e]

[msg MSG_FIRST_04_09_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What's this? Something about the next[n]area feels different from the ones before...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Maybe this means we're close to our goal?[n][w][e]

[msg MSG_FIRST_04_10_mes01 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Isn't that—[n][w][e]

[msg MSG_FIRST_04_10_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's that wall again. Let's check to see[n]if it opens.[n][w][e]

[msg MSG_FIRST_05_01_mes01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, man. This place just keeps gettin'[n]creepier and creepier...[n][w][e]

[msg MSG_FIRST_05_01_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's a sign of how much more twisted[n]this place is. I'm sure the Shadows here[n]are stronger, too.[n][w][e]

[msg MSG_FIRST_05_01_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yeah, and looks like there are more[n]enemies here than there were up[n]above. Be careful, okay?[n][w][e]

[msg MSG_FIRST_05_04_mes01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, there aren't any dangerous[n]enemies here. Seems like a good[n]place to rest.[n][w][e]

[msg MSG_FIRST_05_04_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh, another waiting room? Didn't this[n]one show up quicker than the last one[n]we saw?[n][w][e]

[msg MSG_FIRST_05_04_mes03 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, this is great! I've been wanting[n]to take a break![n][w][e]

[msg MSG_FIRST_05_06_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So, uh, where are we right now?[n][w][e]

[msg MSG_FIRST_05_06_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is the sixth area on this floor,[n]but counting the entire Palace...[n]it's the thirty-third one.[n][w][e]

[msg MSG_FIRST_05_06_mes03 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Thirty-three areas? I'm starting to feel[n]kind of overwhelmed... Just how big[n]IS this place?[n][w][e]

[msg MSG_FIRST_05_06_mes04 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Who knows? This whole place, its[n]overall structure... It's all a mystery.[n]Oh well.[n][w][e]
[s]Just, uh, hang in there![n][w][e]

[msg MSG_FIRST_05_08_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, is this a waiting room? There are[n]two of 'em here?[n][w][e]

[msg MSG_FIRST_05_08_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Either way, I'm glad we can take a[n]breather. Let's not miss the opportunity.[n][w][e]

[msg MSG_FIRST_05_09_mes01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]According to my research, we don't have[n]many more areas left... This is the home[n]stretch![n][w][e]

[msg MSG_FIRST_05_09_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, we can't be losin' our nerve[n]now! We're goin' in![n][w][e]

[msg MSG_FIRST_05_11_mes01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh? It feels different down there.[n]What is it?[n][w][e]

[msg MSG_FIRST_05_11_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'm sure what we're seeking is close.[n]We're almost there![n][w][e]

[msg MSG_FIRST_05_12_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There it is... that wall.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's check it out, Joker.[n][w][e]

[msg MSG_FIRST_06_01_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aww yeah, looks like we made it to[n]some kinda new area![n][w][e]

[msg MSG_FIRST_06_01_mes02 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Wow... This place is a lot bigger than[n]what I'd heard.[n][w][e]

[msg MSG_FIRST_06_01_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I expect the Shadows here will be strong,[n]too. Be careful![n][w][e]

[msg MSG_FIRST_06_03_mes01 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]How many floors down does this place go?[n][w][e]

[msg MSG_FIRST_06_03_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Even I don't know that. The only thing[n]I can say is...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The sheer scale of this place...[n]is astronomical.[n][w][e]

[msg MSG_FIRST_06_03_mes03 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, yeah, but c'mon. We all know[n]that already.[n][w][e]

[msg MSG_FIRST_06_03_mes04 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, Mona... You're always trying to act[n]cool in front of Noir.[n][w][e]

[msg MSG_FIRST_06_03_mes05 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Th-That's not true! I just wanted to[n]make sure she knew![n][w][e]

[msg MSG_FIRST_06_03_mes06 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hehehe.[n][w][e]

[msg MSG_FIRST_06_05_mes01 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, this looks like a place where we can[n]take a little break![n][w][e]

[msg MSG_FIRST_06_07_mes01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hmm, if I'm right, that area just now[n]was the midpoint.[n][w][e]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're halfway there, guys. Let's plow[n]the rest of the way through![n][w][e]

[msg MSG_FIRST_06_07_mes02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You're pretty good at navigatin'. Sure is[n]nice to have reliable info![n][w][e]

[msg MSG_FIRST_06_07_mes03 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Why are you looking at me!?[n][w][e]

[msg MSG_FIRST_06_09_mes01 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A waiting room? Ah, how fortuitous for[n]it to appear, just as I wished for respite.[n][w][e]

[msg MSG_FIRST_06_10_mes01 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Where are we right now?[n][w][e]

[msg MSG_FIRST_06_10_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You're getting close to the end...[n]No doubt about it.[n][w][e]

[msg MSG_FIRST_06_10_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We've got to keep going just a little longer.[n][w][e]

[msg MSG_FIRST_06_12_mes01 [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, I'm getting a different reading from[n]the next area... I think that's the finish[n]line![n][w][e]

[msg MSG_FIRST_06_12_mes02 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Finally... I'm tired of runnin'...[n][w][e]

[msg MSG_FIRST_06_12_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Just imagine what it's like for me![n][w][e]

[msg MSG_FIRST_06_13_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There it is... that wall.[n][w][e]

[msg MSG_FIRST_06_13_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's check it out![n][w][e]

[msg MSG_FIRST_07_01_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This... is the new, seventh area...[n][w][e]

[msg MSG_FIRST_07_01_mes02 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Is it just my imagination, or is this place[n]even creepier?[n][w][e]

[msg MSG_FIRST_07_01_mes03 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No, you're right. Without exaggeration,[n]this repugnant place is an assault on the[n]senses.[n][w][e]

[msg MSG_FIRST_07_01_mes04 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uh, sure, and the enemies here are[n]gonna be pretty feisty, too! Be careful,[n]all right?[n][w][e]

[msg MSG_FIRST_07_03_mes01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, how deep are we right now?[n][w][e]

[msg MSG_FIRST_07_03_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, you're in the third area on this[n]floor. That makes it the 55th area overall.[n][w][e]

[msg MSG_FIRST_07_03_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh. So we passed the big five-o...[n][w][e]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Man, Mona, you were right. This place is[n]astrologically big, or whatever you said.[n][w][e]

[msg MSG_FIRST_07_03_mes04 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well... I'm surprised too...[n][w][e]

[msg MSG_FIRST_07_06_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, a waiting room! We can kick back[n]and relax for a while![n][w][e]

[msg MSG_FIRST_07_08_mes01 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]*sigh* This place keeps goin' on and on...[n][w][e]

[msg MSG_FIRST_07_08_mes02 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, where are we right now?[n][w][e]

[msg MSG_FIRST_07_08_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Umm, this should be around the halfway[n]point. There's still another half to go.[n][w][e]

[msg MSG_FIRST_07_08_mes04 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Another half, she says...[n][w][e]

[msg MSG_FIRST_07_08_mes05 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Don't focus on that! It'll just make it[n]seem longer![n][w][e]

[msg MSG_FIRST_07_10_mes01 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yes, a waiting room! Hey, why don't we[n]take a break?[n][w][e]

[msg MSG_FIRST_07_11_mes01 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]According to my research, you're nearing[n]the end. Go go go! You can do it![n][w][e]

[msg MSG_FIRST_07_11_mes02 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, y'know, sometimes I think I wanna[n]try bein' the naviga—[n][w][e]

[msg MSG_FIRST_07_11_mes03 [Morgana]]
[s][bup 0 3 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I don't think you're cut out for it.[n][w][e]

[msg MSG_FIRST_07_11_mes04 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Man, shut up! You shot me down[n]way too fast...[n][w][e]

[msg MSG_FIRST_07_13_mes01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, the next area down there is giving[n]me a different reading. I'm sure that's[n]the goal![n][w][e]

[msg MSG_FIRST_07_13_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I really hope so... We've been at this[n]a while...[n][w][e]

[msg MSG_FIRST_07_13_mes03 [Morgana]]
[s][bup 0 3 2 65535 0]......[n][w][e]

[msg MSG_FIRST_07_14_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]...Look, it's that wall.[n][w][e]

[msg MSG_FIRST_07_14_mes02 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Do you think it'll open?[n][w][e]

[msg MSG_FIRST_09_05_mes01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We've found a waiting room. Shall we[n]take a break?[n][w][e]

[msg MSG_FIRST_09_11_mes01 [[f 4 31 10 0]]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It looks like we can take a break here.[n][w][e]

[msg MSG_FIRST_09_16_mes01]
[s]既存の終点モデルを使用していますが[n]開けた明るい空間になる予定です。[n][w][e]

[msg MEME_GREETING_mes01 [[f 4 31 10 0]]]
[s][vp 8 2 1 56704 65535 0]Oh, mister! Over here.[n][f 1 2 60][e]

[msg MSG_GOODBY_JOZE [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0]Hope we run into each other again soon![n][w][e]

[msg MSG_MENTION_OF_FLOWER_VA [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][vp 8 2 1 56791 65535 0]Oh, right! I should mention something[n]about those flowers you're collecting...[n][w][e]
[s][f 4 10 65535 0 0]For some reason, you can't leave[n]Mementos with them—they'll[n]disappear on you! It's weird.[n][w][e]
[s][f 4 10 65535 0 0]But it'd be so sad to collect flowers[n]just to have them disappear on you.[n]What a waste, am I right?[n][w][e]
[s][f 4 10 65535 0 0]So, don't forget to come bring them[n]to me before you leave Mementos,[n]okay?[n][w][e]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][vp 8 2 1 56706 65535 0]That should do it. Good job![n][w][e]

[msg MSG_MENTION_OF_FLOWER_VA_2 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0]If you've collected enough flowers,[n]make sure you come trade them with[n]me before you leave Mementos, okay?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 56706 65535 0]That should do it. Good job![n][w][e]

[msg e489_230_jose01 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56777 65535 0]Oh, that's right—here, before I forget.[n][w][e]

[msg e489_230_jose02 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Remember when I told you I'd come up[n]with a fun game for us to play in[n]Mementos?[n][w][e]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56766 65535 0]I thought of this after seeing the[n]subway in the other world.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This'll also prove that you're checking[n]for flowers in all sorts of places here.[n][w][e]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The stamps have different rewards than[n]the flowers, so try to get as much of[n]both as you can![n][w][e]

[msg e489_230_jose03 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56793 65535 0]So, got any flowers for me, mister?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If you do, let's trade! I've got some[n]really good stuff.[n][w][e]

[msg MEMENTOS_awakening_seed_]
[s]Jose is looking at[n]my [f 2 5 3 9999 0]...[n][w][e]

[msg MEMENTOS_awakening_seed__2 [Jose]]
[s][bup 0 221 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56784 65535 0]Oh, now this is neat—I've seen these[n]in my studies![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]They're the accumulated byproducts[n]of warped cognitions.[n][w][e]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This one still hasn't reached its full[n]potential, though...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56793 65535 0]May I see it? I won't do any damage.[n]I promise.[n][w][e]

[msg MEMENTOS_awakening_seed__3 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If I just do this...[n][f 1 2 53][e]

[msg MEMENTOS_awakening_seed__4 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]And then put that there...[n][f 1 2 80][e]

[msg MEMENTOS_awakening_seed__5 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56782 65535 0]...Nice![n][w][e]

[msg MEMENTOS_awakening_seed__6 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All done. Now it should do you[n]some good.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56766 65535 0]Here you go, mister.[n][w][e]

[msg MEMENTOS_awakening_seed__7 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let me know if you find any others like it,[n]okay?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Learning about warped cognitions[n]also teaches me more about humans.[n][w][e]

[msg MEMENTOS_awakening_seed__8]
[s]Jose is looking at[n]the [f 2 5 3 9999 0]...[n][w][e]

[msg MEMENTOS_awakening_seed__9 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56703 65535 0]Hey mister, is that a crystal you've[n]got there?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lemme see it![n][w][e]

[msg MEMENTOS_awakening_seed__10 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If I just do this...[n][f 1 2 53][e]

[msg MEMENTOS_awakening_seed__11 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]And then put that there...[n][f 1 2 80][e]

[msg MEMENTOS_awakening_seed__12 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56782 65535 0]...Nice![n][w][e]

[msg MEMENTOS_awakening_seed__13 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All done. Now it should do you[n]some good.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56766 65535 0]Here you go, mister.[n][w][e]

[msg MEMENTOS_awakening_seed__14 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let me know if you find any others like it,[n]okay?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Learning about warped cognitions[n]also teaches me more about humans.[n][w][e]

[msg MEMENTOS_refuse_awakenin [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56704 65535 0]Oh, mister—it looks like you've got[n]something interesting there.[n][w][e]

[msg MEMENTOS_refuse_awakenin_2]
[s]Jose is looking at[n]my [f 2 5 3 9999 0]...[n][w][e]

[msg MEMENTOS_refuse_awakenin_3 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56792 65535 0]Could I take a closer look at that crystal?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I feel like it'll do me a lot of good...[n]Please? Can I?[n][w][e]

[msg MEMENTOS_refuse_awakenin_4 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hmm... Okay... I see...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So you do this with these...[n]but do this over here, and...[n][w][e]

[msg MEMENTOS_refuse_awakenin_5 [Jose]]
[s][bup 0 221 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56756 65535 0]...Huh? Aw... Looks like it's not gonna[n]work just yet.[n][w][e]

[msg MEMENTOS_refuse_awakenin_6 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Here you go, mister. Thanks for[n]showing it to me.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56794 65535 0]The distortion inside that crystal is[n]still linked to distortion somewhere[n]else.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As long as it's still connected to that[n]place, the crystal can't reach its full[n]potential.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Could you show it to me again[n]once you get rid of that place?[n][w][e]

[msg MEMENTOS_refuse_awakenin_7 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56766 65535 0]I bet I'll be able to turn it into[n]something neat![n][w][e]

[msg JOZE_BEFORE_BTL_1st_01 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Hey, good job.[n][w][e]

[msg JOZE_BEFORE_BTL_1st_02 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Looks like this area was formed somewhat[n]recently.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]I haven't learned much of anything about[n]this place yet, so I need to drink some[n]more flowers.[n][w][e]

[msg JOZE_BEFORE_BTL_1st_03 [Jose]]
[s][bup 0 221 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]Ahh![n][w][e]

[msg JOZE_BEFORE_BTL_1st_04 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Hmm, the flavor has this...[n][w][e]

[msg JOZE_BEFORE_BTL_1st_05 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]No, I'm here for my studies.[n][w][e]

[msg JOZE_BEFORE_BTL_2nd_01 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Hey, good job.[n][w][e]

[msg JOZE_BEFORE_BTL_2nd_02 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]This isn't quite the same flavor I was[n]told about...[n][w][e]

[sel JOZE_BEFORE_BTL_2nd_SEL0 top]
[s]How is it?[e]
[s]Is it not good?[e]

[msg JOZE_BEFORE_BTL_2nd_03 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]It tastes...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]Hmm.[n][w][e]

[msg JOZE_BEFORE_BTL_2nd_04 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]I learned that a person's sense of taste[n]will change as they get older.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]Is that true? Has it happened to you?[n][w][e]

[sel JOZE_BEFORE_BTL_2nd_SEL0_2 top]
[s]Everyone's different.[e]
[s]Why do you care?[e]

[msg JOZE_BEFORE_BTL_2nd_05 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 7 0 0]I see... It's not like that for everyone,[n]huh?[n][w][e]

[msg JOZE_BEFORE_BTL_2nd_06 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 8 0 0]Well...[n][w][e]

[msg JOZE_BEFORE_BTL_2nd_07 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 9 0 0]I just can't bring myself to like the[n]flowers here.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 10 0 0]And I used to like drinking them so[n]much, too...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 11 0 0]If I don't succeed in my studies, then...[n][w][e]

[msg JOZE_BEFORE_BTL_2nd_08 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 12 0 0]Wait—I have to focus.[n][w][e]

[msg JOZE_BEFORE_BTL_3rd_01 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Hey, good job.[n][w][e]

[msg JOZE_BEFORE_BTL_3rd_02 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Remember how I told you I just couldn't[n]bring myself to like the flowers here?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Well, I think I know why now.[n][w][e]

[sel JOZE_BEFORE_BTL_3rd_SEL0 top]
[s]Enlighten me.[e]
[s]What is it?[e]

[msg JOZE_BEFORE_BTL_3rd_03 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]The flowers here taste sort of staticky.[n]I don't really like it.[n][w][e]

[msg JOZE_BEFORE_BTL_3rd_04 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Since these flowers are... Hmm, how[n]to phrase it like someone in the real[n]world...[n][w][e]

[msg JOZE_BEFORE_BTL_3rd_05 [Jose]]
[s][bup 0 221 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]Ah, right—it's the cognition of one's self,[n]which everyone has inside themselves.[n][w][e]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 7 0 0]When the flavor gets staticky like with[n]these, that means the self is uncertain[n]of its own cognition.[n][w][e]

[msg JOZE_BEFORE_BTL_3rd_06 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 8 0 0]Can people really not know what they[n]are? Is everyone like that?[n][w][e]

[msg JOZE_BEFORE_BTL_3rd_07 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 9 0 0]I don't get it. This is nothing like what[n]I'd been taught...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 10 0 0]But I can't quit my studies now.[n][w][e]

[msg MEME_STAMP_GREET_00 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56703 65535 0]Good job, mister! Is the exploration[n]going well?[n][w][e]

[msg MEME_STAMP_GREET_01 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56706 65535 0]Hey, good job—bring me any flowers?[n]It looks like you've got a nice little[n]stamp collection coming along![n][w][e]

[msg MEME_STAMP_GREET_02 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, good job—bring me any flowers?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56766 65535 0]It's nice to see you making progress[n]with the stamps, too![n][w][e]

[msg MEME_STAMP_GREET_03 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56706 65535 0]Good job—you've got a whole lot of[n]stamps now![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The more stamps you get, the more stuff[n]you can do in Mementos, so keep it up![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh! And don't forget to keep bringing[n]me Mementos flowers too, okay?[n][w][e]

[msg MEME_STAMP_GREET_04 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56706 65535 0]Good job! I've been looking forward[n]to seeing you.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'm always curious just how many stamps[n]you've got each time we cross paths—[n]same with the flowers.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56771 65535 0]Wow, you've got a whole bunch of them[n]now! I think you might've passed the[n]halfway mark! Keep up the good work.[n][w][e]

[msg MEME_STAMP_GREET_05 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Good job. I had a feeling you'd be[n]stopping by soon.[n][w][e]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56786 65535 0]Did you bring me some flowers?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You've got a whole bunch of stamps,[n]too! Would you like to try changing[n]the cognition of Mementos?[n][w][e]

[msg MEME_STAMP_GREET_06 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56701 65535 0]Good job, mister! I think you've got[n]almost all of the stamps...[n][w][e]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56766 65535 0]I'm glad you're enjoying the game[n]so much... setting up those stamp[n]kiosks was really worth it.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You're SO close to beating the game,[n]though—keep it up![n][w][e]

[msg MEME_STAMP_GREET_MAX [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56785 65535 0]Good job! You've collected all of[n]the stamps. Congratulations![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]And with that, the game is over. I'd[n]appreciate it if you kept bringing[n]me flowers, though.[n][w][e]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Um... You're not gonna stop coming[n]to see me now, are you, mister?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56799 65535 0]I always look forward to seeing you again.[n][w][e]

[msg MEME_GREETING_AFTER_3RD_ [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56731 65535 0]...Oh, sorry. So, did you want to trade[n]flowers, or change the cognition in[n]Mementos?[n][w][e]

[msg MEME_GREETING_NEW_LINEUP [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56706 65535 0]Good job, mister.[n][w][e]

[msg MEME_GREETING_2ND_ACCESS [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56701 65535 0]Nice to see you again. Did you bring me[n]more flowers?[n][w][e]

[msg MEME_SEED_ADDED_FIRST_01 [Jose]]
[s][bup 0 221 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, that's right...[n][w][e]

[msg MEME_SEED_ADDED_FIRST_02 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56793 65535 0]About those byproducts of warped[n]cognitions—the "Will Seeds"...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I wanted to learn more about humans,[n]so I went looking around to see if I could[n]find any of these, and look! I actually did.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I wonder why it was just lying around[n]here? Maybe it fell from some other[n]completely different place?[n][w][e]

[msg MEME_SEED_ADDED_FIRST_03 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well anyway, it looks like you're[n]collecting these, mister, so you can[n]have it if you trade me some flowers.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This looks a lot rarer than the others[n]though, so it's going to cost a little more[n]than usual.[n][w][e]

[msg MEME_NEW_LINEUP_FIRST_01 [Jose]]
[s][bup 0 221 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56777 65535 0]...Oh, that's right.[n][w][e]

[msg MEME_NEW_LINEUP_FIRST_02 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A new area of Mementos opened up,[n]so I went around and gathered more[n]stuff to trade.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hopefully I got something you like,[n]mister.[n][w][e]

[msg MEME_NEW_LINEUP_GENERAL_ [Jose]]
[s][bup 0 221 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56777 65535 0]...Oh, that's right.[n][w][e]

[msg MEME_NEW_LINEUP_GENERAL__2 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I was able to go to a new area, so I went[n]around and picked up some stuff.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If you traded any flowers you've found[n]for this stuff, I'd be so happy![n][w][e]

