[msg MSG_000_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]A proposito, quando voce apresenta[n]voce mesma...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Seja falando serio, mesmo se voce estiver mentindo[n]Para a aula, ok? Nao diga nada[n]desnecessario.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sharp-Eared Female Student]]
[s][vp 8 0 0 3 5 0]... voce acha que e ele?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Short-Haired Female Student]]
[s][vp 8 0 0 4 6 0]Huh? Aquele nos rumores?[n][f 1 3 65535][w][e]

