[msg MSG_000_0_0 [Kamoshida]]
[s][bup 0 202 1 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ola, Takamaki.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]As coisas tem sido bastante perigosas ultimamente[n]com todos esses acidentes.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Desculpe, tenho uma sessao de fotos hoje. E para[n]a edicao especial de verao, entao nao posso pagar[n]sentir falta...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Kamoshida]]
[s][bup 0 202 3 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Ei, agora... estar bem bem e[n]dandy, mas nao funcione seu lindo pequeno[n]eu para o osso.[n][f 1 3 65535][w][e]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Voce mencionou que nao estava se sentindo bem,[n]certo? Algo sobre apendicite?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Sim. Eu continuo planejando ir ao hospital,[n]Mas eu estive muito ocupado... desculpe-se por me preocupar[n]voces.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Voce deve estar sozinho tambem. Eu me sinto mal por[n]Mantendo seu melhor amigo na pratica[n]com tantas vezes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Ah, e... tenha cuidado com isso[n]Estudante de transferencia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Ele tem um registro criminal, afinal.[n]Se algo acontecesse com voce...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]...Obrigada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Por favor, de-me licenca.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kamoshida]]
[s][bup 0 202 2 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]TCH...[n][f 1 3 65535][w][e]

