[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Algo errado? Voce estava apenas de pe[n]Em torno de de repente.[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Para meus colegas de equipe, parecia[n]Eu nao estava me movendo...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 111 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Por que voce se espalha assim? Isso e[n]E meio dificil dizer o que voce esta pensando[n]as vezes.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Digamos que ele e um homem de alto calibre.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Estamos contando com voce, Joker![n][f 1 3 65535][w][e]

