[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Manha.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, os exames nao estao chegando?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]E melhor voce ficar no seu quarto e estudar[n]Se voce nao quiser falhar.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Esse e o plano.[e]
[s]Nao ha necessidade.[e]
[s]Que dor.[e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Apenas certifique-se de nao desperdicar o dia todo[n]Limpando sua mesa.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Alem disso, nao poderia doer aprender um pouco mais.[n]Voce se arrependeria de nao estudar quando[n]Voces estao todos crescidos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Entao, tente se dedicar ao seu trabalho,[n]miudo. Pelo menos por enquanto.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, bom pra voce. Conhecimento e[n]algo que voce nunca pode ter o suficiente.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Mas lembre-se, geralmente sao os[n]Isso esta muito confiante que acaba recebendo[n]perseguido.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Afinal, apenas um erro idiota pode[n]Volte para morder voce com muita forca.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, voce pode fazer o que quiser[n]sua vida, mas vai voltar para te assombrar[n]Se voce acabar falhando.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Alem disso, nao poderia doer aprender um pouco mais.[n]Voce pode se arrepender de nao estudar quando[n]Voces estao todos crescidos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Veja isso como o conselho de um anciao para voce.[n]O que voce faz com isso e a sua decisao.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ele esta certo... voce pode refinar sua visao[n]atraves do estudo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Quanto mais voce se aprimora, o[n]em geral suas interacoes interpessoais[n]se tornara.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Faca isso e voce podera ser um uniforme[n]Melhor ladrao fantasma. Tente e lembre-se[n]este.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A loja ja esta aberta para o dia.[n]Nao seja muito alto, entendeu?[n][f 1 3 65535][w][e]

