[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 111 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ei, isso nao e uma pintura desse cara?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Diz "Yusuke Kitagawa". Nao ha[n]confundindo.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 104 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Huh? Espere um segundo...[n][f 1 3 65535][w][e]
[s][f 4 16 2 7 301 65535 65535][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]O que voce acha que essas pinturas sao?[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Clientes do museu.[e]
[s]Os alunos de Madarame.[e]
[s]Bem pintado.[e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Mas se for esse o caso, por que[n]Kitagawa-kun tem uma pintura aqui?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Hmm... entao o que sao?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Eu acho que voce esta certo.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 4 16 2 7 301 1 65535][vp 8 0 0 8 65535 0]Serio? Todos eles? Mas foi apenas[n]Yusuke quando fomos para sua casa[n]antes da...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Isso deve incluir ex-alunos tambem.[n]Apenas um permanece agora...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Levando em consideracao o que nakanohara[n]Guy disse anteriormente, as coisas estao ficando mais claras.[n][f 1 3 65535][w][e]

[msg MSG_008_5_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Tudo bem, vamos continuar investigando. Nos[n]Precisa de algo para confirmar ainda mais[n]nossas deducoes.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 104 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Huh? Isso e o que chamou sua atencao?[n]Eu acho que voce tem um ponto la...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][bup 0 2 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Estamos saindo do topico fora do topico. Quem e esses caras[n]nas pinturas?[n][f 1 3 65535][w][e]

