[msg TUTORIAL_MSG01 [Special Orders]]
[s]In certain battles, you will be able to carry out[n]special orders. If these strategies succeed, the[n][clr 2]flow of battle will turn greatly in your favor[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Special Orders]]
[s]Be sure to choose the party member you believe[n]has the best chance of success.[n][w][e]

[msg TUTORIAL_MSG03 [Special Orders]]
[s]However, keep in mind that this party member will[n]act separately, meaning you will have to fight with[n][clr 2]one fewer party member[clr 27] for a period of time.[n][w][e]

