[msg TUTORIAL_MSG01 [The Beginning of It All]]
[s][f 4 2] is found guilty of a crime he didn't[n]commit and receives a criminal record. He is sent[n]to Tokyo to serve out his probation under the care[n]of [clr 2]Sojiro Sakura[clr 27], an acquaintance of his parents.[n][w][e]

[msg TUTORIAL_MSG02 [The Beginning of It All]]
[s][f 4 2] dreams of a man named Igor and[n]learns he must rebel against a fate of ruin. He also[n]meets mysterious twins, who instruct him to seek[n][clr 2]rehabilitation[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [The Beginning of It All]]
[s]His first morning at Shujin Academy, [f 4 2][n]meets Ryuji Sakamoto. The two wander into a[n]strange castle, where a self-declared king[n]almost kills them.[n][w][e]

[msg TUTORIAL_MSG04 [The Beginning of It All]]
[s]Luckily, [f 4 2]'s Persona awakens, and with[n]the help of Morgana, all three manage to[n]escape the castle.[n][w][e]

