[msg TUTORIAL_MSG01 [Going to the Jazz Club]]
[s]Team members you invite to the Jazz Club will have[n]their Personas strengthened, as well as receiving[n]other helpful effects. These effects differ depending[n]on what day of the week you visit.[n][w][e]

[msg TUTORIAL_MSG02 [Going to the Jazz Club]]
[s]If you visit the Jazz Club on a day when [clr 2]a live[n]singer performs[clr 27], a special cocktail will be[n]served. Also, the [clr 2]effects of the cocktail will[n]be doubled[clr 27] if it's a weekday.[n][w][e]

