[msg TUTORIAL_MSG01 [Rules of Tycoon]]
[s]A card's number determines its strength. Each card[n]must beat the previous one and the number of cards[n]in play must be met (such as pairs). The [clr 2]weakest[n]card is 3[clr 27], but the [clr 2]strongest is 2[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Rules of Tycoon]]
[s]The player holding the [clr 2]3 of Diamonds[clr 27] will go first[n]and the Beggar starts each subsequent round. For[n]additional information, check "Tutorials" or press [n][f 1 10 51] while playing Tycoon.[n][w][e]

