[msg TUTORIAL_MSG01 [Shadow Negotiation]]
[s]During a Hold Up, you can [clr 2]negotiate[clr 27] with any enemy[n]Shadow. A successful negotiation may even earn you[n]a new Persona.[n][w][e]

[msg TUTORIAL_MSG01_02 [Shadow Negotiation]]
[s]If your enemy is a Persona that you already have,[n]a mask will appear beside its name. If you ask it,[n]"[clr 2]Lend me your power[clr 27]," it will [clr 2]grant EXP to your[n]own Persona[clr 27], even if it's not currently equipped.[n][w][e]

[msg TUTORIAL_MSG02 [Shadow Negotiation]]
[s]Decide whether to defeat your foes quickly with[n]All-Out Attacks and earn experience, or negotiate[n]with them to obtain a Persona or other reward.[n][w][e]

