[msg D_TUTORIAL_30_mes01 [Cognition Changes in Mementos]]
[s]When you collect stamps, you will obtain points that[n]you can use to have Jose change the environmental[n]cognition.[n][w][e]

[msg D_TUTORIAL_30_mes02 [Cognition Changes in Mementos]]
[s]By changing the cognition, you will be able to[n]increase the amount of [clr 2]money[clr 27], [clr 2]experience[clr 27], or[n][clr 2]items[clr 27] you can obtain in Mementos.[n][w][e]

[msg D_TUTORIAL_30_mes03 [Cognition Changes in Mementos]]
[s]You will be able to choose which [clr 2]effect to increase[clr 27][n]by delegating points. Use your points wisely to help[n]make your investigation easier.[n][w][e]

[msg D_TUTORIAL_30_mes04 [Cognition Changes in Mementos]]
[s]You can [clr 2]reset[clr 27] the points you delegated by using[n][clr 2]flowers[clr 27]. However, the more points you delegated,[n]the more flowers you will need.[n][w][e]

[msg D_TUTORIAL_30_mes05 [Cognition Changes in Mementos]]
[s]To view the current cognition change, press [clr 2][f 1 10 53][clr 27][n]to pull up the main map. You can check the status[n]at any time during your investigation.[n][w][e]

