[msg TUTORIAL_MSG01 [Before Infiltrating a Palace]]
[s]Check your progress with the [clr 2]Hold Meeting[clr 27][n]option. Listen to your friends' opinions[n]and decide the best course of action.[n][w][e]

[msg TUTORIAL_MSG02 [Before Infiltrating a Palace]]
[s]Selecting [clr 2]Infiltrate Palace[clr 27] will take you to[n]the Palace. You cannot purchase items while[n]in a Palace, so be sure you're well prepared.[n][w][e]

[msg TUTORIAL_MSG03 [Before Infiltrating a Palace]]
[s]It will be nighttime when you return from a[n]Palace. If time runs out, it's [clr 2]game over[clr 27].[n]Keep an eye on the time remaining.[n][w][e]

