[msg TUTORIAL_MSG01 [How to Fight in Challenge Battles]]
[s]In a Challenge Battle, you will have to focus on[n]defeating your enemies, as well as how much[n]damage you deal to them.[n][w][e]

[msg TUTORIAL_MSG02 [How to Fight in Challenge Battles]]
[s]To deal massive damage, increase your party's attack[n]power and lower the enemies' defenses. You can also[n]knock the enemy down and try for a Technical Attack.[n][w][e]

[msg TUTORIAL_MSG03 [How to Fight in Challenge Battles]]
[s]You can achieve a high score by earning bonus points,[n]monitoring the order of battle, and knowing which[n]party member should receive a Baton Pass.[n][w][e]

