[msg TUTORIAL_MSG01 [Baton Pass Rank]]
[s]The higher your Baton Pass rank, the more powerful[n]the effects will be when performing a Baton Pass.[n][w][e]

[msg TUTORIAL_MSG02 [Baton Pass Rank]]
[s]Rank 1[n]Increase damage dealt.[n][w][e]

[msg TUTORIAL_MSG03 [Baton Pass Rank]]
[s]Rank 2[n]Increase damage dealt.[n]Heal HP after a Baton Pass.[n][w][e]

[msg TUTORIAL_MSG04 [Baton Pass Rank]]
[s]Rank 3[n]Increase damage dealt.[n]Heal even more HP after a Baton Pass.[n]Recover SP after a Baton Pass.[n][w][e]

[msg TUTORIAL_MSG05 [Baton Pass Rank]]
[s]You can verify a party member's Baton Pass Rank[n]on the Stats screen.[n][w][e]

