[msg D_TUTORIAL_27_mes01 [Thief Assist]]
[s]Press [clr 2][f 1 10 35][clr 27] while investigating the Metaverse to use[n]Thief Assist, giving you access to multiple helpful[n]functions that will aid your progress.[n][w][e]

[msg D_TUTORIAL_27_mes02 [Thief Assist]]
[s]Auto-Recover uses your party's healing skills[n]on [clr 2]all party members[clr 27]. Be aware that doing this[n][clr 2]consumes the required amount of SP[clr 27].[n][w][e]

[msg D_TUTORIAL_27_mes03 [Thief Assist]]
[s]You can use also use [clr 2]infiltration tools[clr 27] such as[n][clr 2]smokescreens[clr 27] to quickly flee a battle. These[n]tools will give you an advantage during fights![n][w][e]

