[msg TUTORIAL_MSG01 [Confirming Mementos Requests]]
[s]Check your information on a target by selecting[n][clr 2]View Requests[clr 27] at the hideout or by pressing[n][f 1 10 25] to view [clr 2]Requests[clr 27] in the main menu.[n][w][e]

[msg TUTORIAL_MSG02 [Confirming Mementos Requests]]
[s]Once the information has been confirmed, you[n]can begin by selecting [clr 2]Explore Mementos[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Confirming Mementos Requests]]
[s]Mementos can be explored even without a[n]target, but time will pass as it would in[n]a Palace infiltration. Exercise caution[n]when nearing a time limit.[n][w][e]

