C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E200_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E200_040.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E200_301.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E201_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E202_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E203_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E204_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E205_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E205_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E205_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E206_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E207_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E207_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E208_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E208_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E209_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E210_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E210_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E211_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E211_050.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E211_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E212_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E213_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E215_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E215_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E216_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E216_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E217_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E217_011.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E218_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E218_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E218_003.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E218_012.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E219_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E220_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E220_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E220_003.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E221_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E221_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E221_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E221_102.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E221_103.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E222_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E222_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E222_003.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E223_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E224_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E225_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E226_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E227_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E228_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E229_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E229_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E230_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E230_301.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E233_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E234_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E234_011.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E236_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E237_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E237_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E238_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E239_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E240_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E241_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E242_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E243_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E243_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E243_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E243_210.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E243_211.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E243_301.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E243_308.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E243_401.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E244_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E244_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E244_003.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E244_103.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E244_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E244_401.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E244_501.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E245_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E246_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E246_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E247_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E247_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E248_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E249_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E249_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E250_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E251_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E253_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E254_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E255_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E255_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E255_301.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E256_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E257_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E257_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E257_003.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E258_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E258_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E258_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E259_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E259_143.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E259_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E259_301.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E259_311.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E259_401.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E259_501.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E259_601.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E260_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E261_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E262_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E263_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E264_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E264_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E264_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E265_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E266_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E266_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E266_012.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E267_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E267_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E267_003.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E267_004.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E267_005.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E267_012.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E268_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E268_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E269_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E269_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E270_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E270_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E271_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E271_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E272_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E272_011.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E272_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E272_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E272_301.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E273_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E273_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E273_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E273_301.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E274_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E274_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E274_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E275_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E276_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E277_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E277_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E277_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E278_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E279_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E279_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E279_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E279_301.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E280_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E280_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E280_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E281_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E282_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E283_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E284_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E284_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E285_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E286_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E287_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E288_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E288_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E288_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E289_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E289_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E290_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E292_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E292_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E293_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E293_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E293_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E293_301.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E294_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E295_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E295_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E295_050.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E295_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E295_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E295_301.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E296_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E296_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E296_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E296_301.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E296_401.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E296_501.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E297_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E297_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E297_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E297_102.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E298_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E298_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E299_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E299_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
pause