[msg MSG_000_0_0 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 1 301 1][vp 8 0 0 1 65535 0]Meus queridos ladrões, bem-vindos ao[n]nosso novo ponto de encontro![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Desta vez nosso alvo[n]é Madarame![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Todos nós já vimos aquele Palácio.[n]Estaríamos em apuros se nos iludêssemos[n]que tudo será como da última vez.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]E além disso... A virtude de Lady[n]Ann está em perigo![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 7 300 1][vp 8 0 0 34 65535 0]O quê?!?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Faremos como com Kamoshida.[n]Primeiro, garantiremos[n]uma rota de infiltração.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Depois disso, enviaremos a carta de aviso. E[n]assim que materializarmos o Tesouro, vamos[n]roubá-lo.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Opa, tenho uma pergunta! Madarame[n]não sabe que temos que fazer algumas[n]coisas em seu palácio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Mas então, por que já somos tratados como[n]criminosos lá?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Você está aprendendo, Ryuji. Muito bem.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Deve ser porque ele não confia em ninguém. Todo[n]estranho poderia ser um inimigo para ele.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Ou talvez ele esteja apenas chateado[n]com todos os rumores[n]sobre ele.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Então, todo esse burburinho em[n]seu Palácio não tem nada[n]a ver conosco?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Seja como for, é melhor termos cuidado.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Será difícil roubar o Tesouro,[n]se tivermos que aumentar o nível de alerta[n]desnecessariamente.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Também teremos que ter[n]cuidado com Kitagawa-kun.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Tenho certeza que ele reportaria qualquer[n]atividade suspeita[n]para Madarame.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Você está certo![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Ei, qual será a forma[n]do Tesouro de Madarame?[n]Outra coroa?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Duvido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Mas meu sexto sentido vai[n]pegá-lo, quando o virmos.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Ah, certo, você vai enlouquecer como[n]da última vez, hein?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Temos até[n]o fim da exposição, né?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Isso significa... até 5 de junho.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Executaremos o plano[n]assim que enviarmos a[n]carta de aviso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Portanto, nosso[n]caminho de infiltração terá que ser definido[n]até 2 de junho.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Ouça com atenção. Não podemos[n]estragar tudo, POR QUALQUER RAZÃO, OK!?![n][f 1 3 65535][w][e]

