[msg MSG_000_0_0 [Male Council Member]]
[s][vp 8 0 0 1 65535 0]Presidente... Qual é o significado dessa[n]postagem?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]O diretor Kobayakawa colocou isso sem o meu- [n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Female Council Member]]
[s][vp 8 0 0 3 5 0]Já recebemos algumas informações anônimas.[n][f 1 3 65535][w][e]
[s][f 4 16 6 7 301 65535 65535][vp 8 0 0 4 5 0]"Ouvi dizer que alguns alunos estão sendo[n]ameaçados. Estou com tanto medo... por[n]favor, faça alguma coisa." [n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 4 16 6 7 301 1 65535][vp 8 0 0 5 65535 0]O que!?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Male Council Member]]
[s][vp 8 0 0 6 4 0]"Eles têm sujeira em mim e estão exigindo[n]dinheiro. Não posso ir à polícia... o que[n]devo fazer?" [n][f 1 3 65535][w][e]
[s][vp 8 0 0 7 4 0]Isso não está falando sobre os crimes que se[n]rumores de estar ocorrendo em Shibuya?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Female Council Member]]
[s][vp 8 0 0 8 5 0]Portanto, há até vítimas em nossa escola...[n]O que deveríamos fazer?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Male Council Member]]
[s][vp 8 0 0 9 4 0]Esta não é de responsabilidade do Conselho[n]Estudantil. Isso é assustador para nós[n]também...[n][f 1 3 65535][w][e]

[msg MSG_006_5_0 [Male Council Member]]
[s][vp 8 0 0 10 4 0]O diretor Kobayakawa ligou para você ontem,[n]certo? Ele te contou alguma coisa sobre[n]isso?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Bem não...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Ele saiu hoje, mas vou perguntar a ele[n]amanhã. Por favor, espere nisso por[n]enquanto...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Male Council Member]]
[s][vp 8 0 0 13 4 0]Se você diz...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]...Minhas desculpas pela confusão.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Não se preocupe. Vou fazer algo sobre tudo[n]isso...[n][f 1 3 65535][w][e]

