[msg MSG_000_0_0 [Veteran AD]]
[s][vp 8 0 0 1 9 0]O Sr. Akechi está chegando![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [(SE)女子高生の声A]]
[s][vp 8 0 0 2 65535 0]キャー、アケチくんだ![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [(SE)女子高生の声B]]
[s][vp 8 0 0 3 65535 0]かっこいいー![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Não é isso o cara de ontem?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Veteran AD]]
[s][vp 8 0 0 3 9 0]Cortando do comercial![n][f 1 3 65535][w][e]
[s][vp 8 0 0 4 9 0]Sete, seis, cinco segundos até o início,[n]quatro, três...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Cute Announcer]]
[s][vp 8 0 0 5 12 0]E agora, para o segmento "mais quente e[n]cumprimentado" do nosso show...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 6 12 0]Depois que sua última aparição foi tão bem[n]recebida, decidimos trazer de volta este[n]belo cavalheiro hoje.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 7 12 0]É o detetive do ensino médio, Goro Akechi![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 1 2 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Olá.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Cheerful Host]]
[s][vp 8 0 0 9 8 0]Obrigado por reservar um tempo para se[n]juntar a nós hoje, Akechi-kun. Sua[n]popularidade é impressionante.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Até eu achei uma surpresa.[n]É um pouco embaraçoso embora...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Cute Announcer]]
[s][vp 8 0 0 11 12 0]Seguindo em frente, nos disseram que há um[n]caso em sua mente agora. Gostaria de[n]compartilhar, detetive?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Ah sim. Esse seria o escândalo envolvendo o[n]mestre artista Madarame.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Cheerful Host]]
[s][vp 8 0 0 13 8 0]Aí está! Toda essa excitação do ladrão[n]fantasma também chamou sua atenção,[n]Akechi-kun![n][f 1 3 65535][w][e]
[s][vp 8 0 0 14 8 0]Permita-me ser franco por apenas um segundo.[n]O que você acha desses ladrões fantasmas[n]orientados para a justiça?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][bup 0 9 1 2 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Se eles realmente são heróis da justiça,[n]espero sinceramente que existam.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Cheerful Host]]
[s][vp 8 0 0 16 8 0]Ohhh, então você não nega a possibilidade de[n]que sejam reais?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Akechi]]
[s][bup 0 9 1 2 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Posso não parecer, mas às vezes desejo que o[n]Papai Noel realmente existisse.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Embora se o fizesse, eu teria que prendê-lo[n]por quebrar e entrar.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][vp 8 0 0 19 65535 0]......[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Mas hipoteticamente falando, se esses[n]ladrões fantasmas são reais...[n][f 1 3 65535][w][e]

[msg MSG_016_5_0 [Akechi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 9 3 300 1][vp 8 0 0 21 65535 0]Eu acredito que eles deveriam ser julgados[n]em um tribunal.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Cheerful Host]]
[s][vp 8 0 0 22 8 0]Essa é a afirmação. Eles estão cometendo[n]crimes?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 23 8 0]Algumas pessoas até dizem que os ladrões[n]estão realmente ajudando suas vítimas a[n]abandonar seus modos maus.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Akechi]]
[s][bup 0 9 2 2 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]O que o artista Madarame fez realmente foi[n]um crime imperdoável.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]No entanto, eles estão levando a lei em suas[n]próprias mãos, julgando-o. Está longe de[n]ser justiça.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Mais importante, você nunca deve mudar com[n]força o coração de uma pessoa.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Cheerful Host]]
[s][vp 8 0 0 27 8 0]Você tem um ponto. Afinal, essas pessoas[n]estão se chamando de ladrões fantasmas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 28 8 0]Incrível como sempre, Akechi-kun! Eu poderia[n]ouvir você por dias! Você tem o carisma[n]mais radiante![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Akechi]]
[s][bup 0 9 1 2 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Devo dizer que, porém, ficaria envergonhado[n]se esses ladrões fantasmas não existam.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Se fosse esse o caso, eu o resumiria em um[n]relatório como um projeto escolar.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Cute Announcer]]
[s][vp 8 0 0 31 12 0]Agora, então, vamos tentar perguntar a[n]alguns alunos a mesma idade que Akechi-kun[n]sobre os ladrões Phantom![n][f 1 3 65535][w][e]
[s][vp 8 0 0 32 12 0]Primeiro, pressione seu botão agora, se você[n]acha que os ladrões Phantom existem![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 3 301 1][vp 8 0 0 33 65535 0]Claro que sim![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Cheerful Host]]
[s][vp 8 0 0 34 8 0]Cerca de 30% ou mais? Quais são seus[n]pensamentos, Akechi-kun?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Akechi]]
[s][bup 0 9 4 2 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Estou um pouco surpreso. Isso é mais alto do[n]que eu esperava.[n][f 1 3 65535][w][e]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Eu adoraria ouvir algumas opiniões mais[n]detalhadas sobre as ações dos ladrões[n]Phantom.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Cute Announcer]]
[s][vp 8 0 0 37 12 0]Tudo bem, vamos tentar perguntar a esse[n]aluno aqui.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 38 12 0]Hipoteticamente falando, quais são seus[n]pensamentos sobre esses ladrões fantasmas,[n]se fossem reais?[n][f 1 3 65535][w][e]

[sel SEL_026_0_0 top]
[s]Eles são a própria justiça.[e]
[s]Eles são necessários.[e]
[s]Eles fazem mais do que os policiais.[e]

[msg MSG_027_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Você diz isso com tanta firmeza.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Akechi]]
[s][bup 0 9 1 2 0][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]Haha, eu não esperava isso.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Akechi]]
[s][bup 0 9 1 2 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]Hahaha.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Cheerful Host]]
[s][vp 8 0 0 42 8 0]Isso vai completamente contra a opinião que[n]você tinha sobre eles sendo julgados por[n]lei, Akechi-kun.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Akechi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 9 10 300 1][vp 8 0 0 43 65535 0]De fato. É bastante intrigante ouvir um[n]reconhecimento tão forte.[n][f 1 3 65535][w][e]

[msg MSG_031_5_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]Nesse caso, há mais uma pergunta que eu[n]gostaria de fazer...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Se alguém próximo a você, por exemplo, seu[n]amigo ao seu lado...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]Se o coração dele mudasse de repente... você[n]não pensaria que era o trabalho dos ladrões[n]fantasmas?[n][f 1 3 65535][w][e]

[sel SEL_032_0_0 top]
[s]De jeito nenhum.[e]
[s]Eles apenas têm como alvo criminosos.[e]
[s]O que você pensaria?[e]

[msg MSG_033_0_0 [Akechi]]
[s][bup 0 9 1 2 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]Haha, sem dúvidas. No entanto, há um grande[n]problema no seu raciocínio.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]Eu vejo. Mas como você pode ter tanta[n]certeza?[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Akechi]]
[s][bup 0 9 1 2 0][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]Ah, jogando a pergunta de volta para mim?[n]Bem, esta é minha opinião sobre o assunto.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]Se as ações dos ladrões são boas ou não,[n]sinto que há uma questão mais importante em[n]questão.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Cheerful Host]]
[s][vp 8 0 0 51 8 0]HM? O que você quer dizer?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Akechi]]
[s][bup 0 9 3 2 0][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]A questão de como eles mudam o coração das[n]pessoas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]Se eles honestamente possuem essa[n]habilidade...[n]Pode ser usado para mais do que extrair[n]confissões.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]Pode ser que o que parece ser crimes comuns[n]está realmente sendo perpetrado por esses[n]métodos...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Cheerful Host]]
[s][vp 8 0 0 55 8 0]Você sabe, você está absolutamente certo.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 56 65535 0]Oh, por favor, não entenda mal. Tudo isso é[n]puramente hipotético...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 57 65535 0]Somente se as pessoas que podem usar esse[n]poder realmente existem. De qualquer[n]maneira, isso não pode ser ignorado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 58 65535 0]A existência dos ladrões fantasmas não seria[n]nada além de uma ameaça à nossa vida[n]cotidiana.[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 59 65535 0]Para ser sincero, já estou trabalhando ao[n]lado da polícia para ajudar a resolver esse[n]assunto.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 60 65535 0]Parecia que o que ele estava dizendo poderia[n]estar certo...[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 61 65535 0]Ele fez parecer que somos os bandidos.[n]Eu não gosto disso.[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 62 65535 0]Mas essas coisas sobre a polícia...[n]Você acha que é real?[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 63 65535 0]Ele pode dizer o que quiser. A justiça de[n]tudo isso é algo que podemos decidir por[n]nós mesmos.[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 64 65535 0]Ah, desculpe, eu tenho que ir um vazamento.[n]Vocês podem esperar aqui? Eu volto já.[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 65 65535 0]Oh meu Deus... eu vou continuar, ok?[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Akechi]]
[s][bup 0 9 4 2 0][f 4 10 65535 0 0][vp 8 0 0 66 65535 0]Ah é você![n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 67 65535 0]Estou feliz por ter encontrado você. Eu[n]queria agradecer pessoalmente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 68 65535 0]Parafraseando Hegel, o avanço não pode[n]ocorrer sem tese e antítese...[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Akechi]]
[s][bup 0 9 1 2 0][f 4 10 65535 0 0][vp 8 0 0 69 65535 0]Haha, minhas desculpas. O que quero dizer é[n]que nossa discussão foi bastante[n]significativa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 70 65535 0]Poucas pessoas ao meu redor estão tão[n]dispostas a falar de idéia tão livre quanto[n]você fez antes.[n][f 1 3 65535][w][e]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 71 65535 0][f 4 24 0 7 6 59 5 100]Os adultos só estão interessados em usar os[n]jovens, enquanto simplesmente fazem o que[n]dizem os adultos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 72 65535 0]Existem muitas pessoas irresponsáveis nesses[n]tempos modernos. Eu posso entender por que[n]você apoiaria os ladrões Phantom.[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Akechi]]
[s][bup 0 9 3 2 0][f 4 10 65535 0 0][vp 8 0 0 73 65535 0]É possível que esse grupo seja exatamente[n]como você acredita e eles estão realmente[n]agindo com boas intenções.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 74 65535 0]Como eles têm talentos especiais, presumo[n]que seus corações devem estar queimando com[n]um senso de justiça e dever...[n][f 1 3 65535][w][e]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][f 4 24 0 7 6 59 3 100][vp 8 0 0 75 65535 0]But that justice is merely a façade[n]escondendo sua falta de força verdadeira.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 76 65535 0]É por isso que acredito que, se um oponente[n]verdadeiramente poderoso os fosse[n]encurralado, eles fugiriam sem um segundo[n]pensamento.[n][f 1 3 65535][w][e]

[sel SEL_052_0_0 top]
[s]Eles não correram.[e]
[s]Eles lutariam até o fim.[e]

[msg MSG_053_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 77 65535 0]Oh...?[n][f 1 3 65535][w][e]
[s][bup 0 9 1 2 0][f 4 10 65535 0 0][f 4 24 0 7 6 42 3 100][vp 8 0 0 78 65535 0]Você realmente é intrigante. Aposto que você[n]seria um parceiro de debate que vale a pena[n]sobre o assunto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 79 65535 0]Se estiver tudo bem com você, você[n]continuaria compartilhando seus pensamentos[n]comigo?[n][f 1 3 65535][w][e]

[sel SEL_054_0_0 top]
[s]Tudo bem para mim.[e]
[s]Eu adoraria.[e]

[msg MSG_055_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 80 65535 0]Obrigado, isso é uma ótima notícia. Sinto[n]algo em você que é bem diferente de outras[n]pessoas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 81 65535 0]Eu acho que você pode chamá-lo de intuição[n]do meu detetive? Haha, brincando, é claro.[n][f 1 3 65535][w][e]

[msg MND_055_1_0]
[s][vp 8 0 0 0 65535 0]Parece que o detetive Akechi gostou de mim...[n][f 1 3 65535][w][e]

[msg MSG_055_3_0 [Sae]]
[s][vp 8 0 0 800 65535 0]Não acredito que você escapou da rede da[n]polícia até hoje...[n][f 1 3 65535][w][e]

[msg MSG_055_5_0 [Sae]]
[s][vp 8 0 0 801 65535 0]A única explicação lógica é que alguém da[n]polícia tem laços com os ladrões[n]fantasmas...[n][f 1 3 65535][w][e]

[msg MSG_055_7_0 [Sae]]
[s][vp 8 0 0 802 65535 0]Explique-se![n][f 1 3 65535][w][e]

[msg MSG_056_0_0 [Akechi]]
[s][bup 0 9 1 2 0][f 4 10 65535 0 0][vp 8 0 0 82 65535 0]Ah, sim- devemos trocar informações de[n]contato.[n][f 1 3 65535][w][e]

[msg MSG_057_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 83 65535 0]... e, registrado.[n][f 1 3 65535][w][e]
[s][bup 0 9 1 2 0][f 4 10 65535 0 0][f 4 24 0 7 6 42 3 100][vp 8 0 0 84 65535 0]Bem, espero vê-lo novamente em breve.[n][f 1 3 65535][w][e]

[msg MSG_058_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 85 65535 0]A intuição de um detetive, hein? Não devemos[n]subestimar isso.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 86 65535 0]Por outro lado, há muita coisa que[n]poderíamos aprender com ele. Se ele entrar[n]em contato com você, tente sair com ele.[n][f 1 3 65535][w][e]

[msg MSG_059_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 87 65535 0]Desculpe por levar tanto tempo!... Espere,[n]isso foi Akechi?[n][f 1 3 65535][w][e]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 88 65535 0]Eu não suporto uma atitude poderosa tão[n]alta! Apenas respirando o mesmo ar que ele[n]me deixa doente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 89 65535 0]Vamos lá, [f 4 2]. Vamos.[n][f 1 3 65535][w][e]

