[msg MSG_000_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Nos encontramos na estação Shibuya, sim?[n]Para falar sobre nosso próximo alvo?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Vamos juntos.[e]
[s]Não se atrase.[e]
[s]Que dor.[e]

[msg MSG_002_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Não seria melhor ir separadamente, apenas[n]por precaução?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Nós nos encontraremos lá então.[n]Tudo bem com você, Yusuke?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]Mas não tenho o suficiente para a tarifa do[n]trem.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Cara, apenas caminhe.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Já estou em Shibuya, cara.[n]Eu abandonei minhas aulas da tarde.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Mas cara... ainda é diurno e já há uma[n]tonelada de pessoas obscuras aqui.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Olha quem Está Falando.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Ei, o que isso passou a dizer!?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Nós concordamos nisso na casa de banho![n]O calor frite seu cérebro!?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh bom, você ainda não foi para casa.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eu preciso que você vá para a sala do[n]conselho estudantil de uma só vez.[n]Niijima-san está pedindo por você.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ela disse que você esqueceu de arquivar seu[n]relatório de item perdido, então você terá[n]que fazer a papelada por toda parte.[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]Niijima?[e]
[s]Eu não perdi nada.[e]
[s]Que dor.[e]

[msg MSG_012_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Niijima Makoto, presidente do Conselho[n]Estudantil de Shujin? Você deveria[n]conhecê-la.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]A sala do conselho estudantil fica no[n]terceiro andar. Apenas certifique-se de[n]ir... *bocejo* [n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Talvez você tenha esquecido? Bem, fique[n]claro de qualquer maneira.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]A sala do conselho estudantil fica no[n]terceiro andar. Apenas certifique-se de[n]ir... *bocejo* [n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pensar assim não vai ajudar nada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]As coisas só pioram quando você é um[n]adulto... espere, não faz sentido reclamar[n]com você sobre isso...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]A sala do conselho estudantil fica no[n]terceiro andar. Apenas certifique-se de[n]ir... *bocejo* [n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A sala do conselho estudantil fica no[n]terceiro andar. Apresse-se agora.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]*Bocejo* Fico tão sonolento nessa hora do[n]dia...[n][f 1 3 65535][w][e]

