[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ok, hoje vamos para Shibuya,[n]como programado![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Podemos ter que lutar,[n]então cuidado![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ok, estamos todos aqui.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ontem eu também passei por aqui e...[n]Cara, é muita gente.[n]Vai ser uma bagunça.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Há também uma forte presença policial. Isso pode[n]levar os mafiosos a se esconderem.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Concordo. Recentemente, o aumento da[n]criminalidade é assunto da[n]mídia. Eles podem não aparecer.[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Sim, temos que.[e]
[s]Adiamos para hoje.[e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tá certo! Vamos chutá-los pelas bolas![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos, pessoal, somos quatro.[n]Não vai ser tão difícil[n]conseguir alguma coisa.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Que rude! Somos cinco![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Como dissemos ontem, você deve[n]dirigir-se à Central Street,[n][f 4 2].[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Perfeito, vamos lá! Deixe-me saber[n]se você encontrar algumas pessoas obscuras![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você tem que lidar com a Central[n]Street. Deixe para os outros[n]pensar sobre as áreas ao redor.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Aluno Kosei de cabelo preto]]
[s][vp 8 0 0 0 65535 0]Ei, eu estava em um fórum outro dia[n]e de repente vi esta postagem:[n]"10.000 peças na sede".[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Estudante Kosei de cabelos castanhos]]
[s][vp 8 0 0 0 65535 0]Huh? Mas o que é isso? Um código?[n]Parece um pouco suspeito...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Embora, para ser honesto, alguns[n]dias atrás eu ouvi uma coisa[n]semelhante enquanto estava naquele beco.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Aluno Kosei de cabelo preto]]
[s][vp 8 0 0 0 65535 0]Bem, tem havido muito aqui ultimamente, coisas[n]suspeitas. Deve ser por isso que existem tantas[n]forças policiais.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Anfitriões]]
[s][vp 8 0 0 0 65535 0]Terminei meu turno. Já era hora ... Ugh,[n]não é uma merda. Eu bebi demais...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Talvez eu devesse encontrar outro emprego. Você[n]sabe se existe algum emprego por aí que possa[n]render bem?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Jogador]]
[s][vp 8 0 0 0 65535 0]Pode ser. Você sabe, você poderia...[n]trabalhar para a máfia.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Você conhece aqueles caras obscuros nos[n]becos? Embora talvez você acabe[n]enganando algumas crianças...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Anfitriões]]
[s][vp 8 0 0 0 65535 0]Prefiro não me envolver.[n]Você sabe como é, não gosto da ideia[n]de viver atrás das grades.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Oficial de patrulha]]
[s][vp 8 0 0 0 65535 0]Novamente, nada a relatar. Nós[n]encontramos várias vítimas, mas nenhum[n]um dos verdadeiros perpetradores.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eles aparecem e desaparecem. E para[n]se isso não bastasse, eles conseguem[n]misturar-se com as crianças normais.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Agente cuidadoso]]
[s][vp 8 0 0 0 65535 0]Pare de reclamar! Se a gente não conseguir[n]alguma informação, as pessoas[n]vão dizer que a polícia é inútil![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]A mídia já está atrás de nós, e os superiores não[n]estão levantando um dedo. Não é nada[n]encorajador...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morador de rua]]
[s][vp 8 0 0 0 65535 0]O que é esse olhar assustador?[n]Se você tem que me dizer algo,[n]faça isso.[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]Eu quero um emprego de meio período.[e]
[s]Você faz parte da máfia?[e]

[msg MSG_021_0_0 [Morador de rua]]
[s][vp 8 0 0 0 65535 0]Um emprego a tempo parcial…? Você não[n]está falando de um trabalho normal, hein?[n]Um conselho: não faça isso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eles vão espremê-lo[n]até o último centavo[n]com extorsão e ameaças.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Morador de rua]]
[s][vp 8 0 0 0 65535 0]O? Não, não passo de um eremita solitário. De[n]qualquer forma, por que você está procurando por[n]eles?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Tente ficar longe dele,[n]você me entende? É horrível gente.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Morador de rua]]
[s][vp 8 0 0 0 65535 0]Alguns amigos meus se envolveram em seus[n]golpes... Eles controlam a cidade inteira,[n]confie em mim.[n][f 1 3 65535][w][e]

[sel SEL_024_0_0 top]
[s]Como encontro essa "máfia"?[e]
[s]Seus amigos vão fugir?[e]

[msg MSG_025_0_0 [Morador de rua]]
[s][vp 8 0 0 0 65535 0]Eles se misturam à multidão,[n]mas usam palavras estranhas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]É como uma espécie de[n]linguagem secreta. Uma linguagem codificada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]No entanto, se você sentir algo estranho, fique[n]longe. Essas pessoas visam os mais jovens.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Morador de rua]]
[s][vp 8 0 0 0 65535 0]Fácil de dizer, mas nenhum deles[n]tem para onde ir. Só uma[n]coisa: fique longe da máfia.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eles se misturam com a multidão, mas[n]não são impossíveis de encontrar.[n]Eles usam mensagens codificadas, sabe?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Sim, como uma linguagem secreta.[n]Cuidado se ouvir alguém[n]falando um pouco estranho.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Como você está?[n]Encontrou alguma coisa?[n][f 1 3 65535][w][e]

[sel SEL_028_0_0 top]
[s]Nada.[e]
[s]Eu quero ir para casa...[e]

[msg MSG_029_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]Parece o proverbial buraco[n]na água. Quem sabe os outros[n]como eles se saíram.[n][f 1 3 65535][w][e]

[sel SEL_030_0_0 top]
[s]Como foi, Ryuji?[e]
[s]Como foi Ann?[e]
[s]Como foi Yusuke?[e]

[msg MSG_031_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Aparentemente, no corredor[n]há um cara falando[n]sobre "drogas poderosas".[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Não estou esperando muito,[n]mas vou dar uma olhada.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Ouvi falar de alguém[n]propondo um tentador "[n]emprego bem remunerado" em frente à delegacia.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Eles parecem ter como alvo[n]principalmente meninas.[n]Vou ver do que se trata.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]De minha parte, parece que há[n]alguém dizendo coisas estranhas[n]no beco próximo ao fliperama.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Algo sobre gelo e[n]vegetais, e mais[n]sobre neve... amanhã.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Vou observar[n]a situação. O fliperama fica na[n]Central Street, certo?[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ok, vamos fazer[n]o que pudermos para ajudar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Não tenho ideia de qual é a faixa certa. Apenas[n]tente ir aos lugares mais suspeitos.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Morador de rua]]
[s][vp 8 0 0 0 65535 0]Já contei tudo sobre a máfia.[n]Precisa de mais?[n][f 1 3 65535][w][e]

[sel SEL_036_0_0 top]
[s]Eu quero agradecer-te.[e]
[s]Como posso identificá-los?[e]

[msg MSG_037_0_0 [Morador de rua]]
[s][vp 8 0 0 0 65535 0]Não há necessidade. Você me ajudou a afastar um[n]pouco o tédio. A máfia também me deu problemas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]No entanto, é melhor manter um[n]perfil baixo. A vida fica complicada,[n]assim que eles começam a notar você.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Morador de rua]]
[s][vp 8 0 0 0 65535 0]Eles se comunicam usando frases estranhas e[n]incomuns. Uma linguagem codificada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eles são muito cuidadosos, no entanto.[n]Até a polícia[n]tem dificuldade em encontrá-los.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Velhinha gentil]]
[s][vp 8 0 0 0 65535 0]Olá, jovem.[n]Talvez você possa me dizer[n]onde fica a linha Inogami?[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Desculpe vovó, estou ocupado.[n]Faça isso, desça as escadas[n]e depois vire à esquerda...[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Velhinha gentil]]
[s][vp 8 0 0 0 65535 0]Oh, Shibuya é tão complicada.[n]E então esses velhos ossos não[n]se movem como costumavam...[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*suspiro* Tudo bem, vamos embora.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Homem alto]]
[s][vp 8 0 0 0 65535 0]Eu disse a você, essa droga[n]é uma bomba real! Você tem que experimentar![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]É muito eficaz, confie em mim. Consegue[n]transformar as praças mais desertas[n]em exuberantes florestas de cabelos...[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ele é o cara de quem Ryuji estava falando.[n]Florestas exuberantes...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Melhor deixar para lá.[n]Mas eu entendo porque[n]ele achou isso suspeito.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos esquecer esse cara.[n]Vamos verificar em outro lugar.[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Urgh, há muitas pessoas! Eu encontro apenas[n]caçadores de talentos e outras pessoas que[n]querem atrair você e... Grrr![n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Caçador de talentos despreocupado]]
[s][vp 8 0 0 0 65535 0]Quinhentos mil ienes, por[n]um vídeo. E você pode[n]ganhar mais, com o tempo...[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Caçador de talentos despreocupado]]
[s][vp 8 0 0 0 65535 0]Huh? Você quer... aparecer[n]em um de nossos vídeos?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Acho que alguns podem[n]gostar, mas ... nós só contratamos[n]meninas. Sinto muito.[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Aparecer em um vídeo?[n]Que tipo de trabalho seria esse?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]De qualquer forma, não acho que tenha[n]nada a ver com drogas.[n]Não acho que tenha a ver com ele.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não é o que estamos procurando.[n]Vamos procurar em outro lugar.[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Eu só estava me perguntando onde fica o[n]fliperama. Eu vou.[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Agente sênior]]
[s][vp 8 0 0 0 65535 0]Espere, você é um estudante do ensino médio, não[n]é? Você deve ficar longe de lugares como este...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Na minha época, o fliperama era[n]um ponto de encontro de bandidos[n]e bandidos da pior espécie.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Homem ameaçador]]
[s][vp 8 0 0 0 65535 0]Você vai para o ensino médio, certo? Você quer um[n]trabalho de meio período fácil?[n][f 1 3 65535][w][e]

[sel SEL_054_0_0 top]
[s]Eu ouço você.[e]
[s]Não exatamente.[e]

[msg MSG_055_0_0 [Homem ameaçador]]
[s][vp 8 0 0 0 65535 0]Hahaha, eu sabia. No final[n]todos querem sua parte.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Porém, aqui tem muito barulho[n]para poder falar. Vamos mexer...[n][f 1 3 65535][w][e]

[msg MSG_056_0_0 [Homem ameaçador]]
[s][vp 8 0 0 0 65535 0]Hahaha, não diga isso. Ganhar dinheiro,[n]por aqui, é moleza.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Porém, aqui tem muito barulho[n]para poder falar. Vamos mexer...[n][f 1 3 65535][w][e]

[msg MSG_057_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não há dúvida de que é ele.[n]Não baixe a guarda.[n][f 1 3 65535][w][e]

[msg MSG_058_0_0 [Homem ameaçador]]
[s][vp 1 0 0 0 0 0]......[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Você sabe o que é um modelador de cachos?[n]Aquela engenhoca que as meninas usam[n]para deixar o cabelo cacheado, está me entendendo?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eu estava pensando... Se um cara[n]levar uma daquelas[n]coisas quentes na cara... o que poderia acontecer?[n][f 1 3 65535][w][e]

[sel SEL_059_0_0 top]
[s]Você teria uma queimadura.[e]
[s]Não entendi.[e]
[s]Mas aquele trabalho de meio período...[e]

[msg MSG_060_0_0 [Homem ameaçador]]
[s][vp 8 0 0 0 65535 0]Hahaha, exatamente![n]Acho que nem os médicos[n]poderiam consertar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eu tentei, sabe? Na cara de um cara. E como ele[n]gritou... eu tirei uma foto dele. Quer ver?[n][f 1 3 65535][w][e]

[msg MSG_061_0_0 [Homem ameaçador]]
[s][vp 8 0 0 0 65535 0]Oh? Você não sabe o que responder?[n]Ihihih, bem, a resposta é...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]"Aquele cara iria[n]chorar e pedir desculpas."[n]Eu tirei uma foto dele. Quer ver?[n][f 1 3 65535][w][e]

[msg MSG_062_0_0 [Homem ameaçador]]
[s][vp 8 0 0 0 65535 0]Desculpe, garoto. As inscrições[n]estão encerradas, então se prepare.[n]Sou um cara ocupado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Você sabe, se você brincar com fogo, mais cedo ou[n]mais tarde você se queima. E eu não acho que[n]você queira, estou certo?[n][f 1 3 65535][w][e]

[msg MSG_063_0_0 [Homem ameaçador]]
[s][vp 8 0 0 0 65535 0]Eu memorizei seu rosto,[n]então pare de bisbilhotar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]O meu é apenas um aviso.[n]É melhor você aproveitar[n]minha gentileza.[n][f 1 3 65535][w][e]

[msg MSG_064_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Droga... ele está nos ameaçando![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Nossa estratégia não[n]funcionou... Vamos para os outros.[n][f 1 3 65535][w][e]

[msg MSG_065_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Eu os subestimei.[n]É incrível, eles quase conseguiram[n]descobrir nossas intenções...[n][f 1 3 65535][w][e]

[msg MSG_066_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Tem certeza de que eles não estavam blefando[n]quando disseram que se lembravam de[n]nossos rostos?[n][f 1 3 65535][w][e]

[msg MSG_067_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]Em qualquer caso, isso tornará[n]ainda mais difícil investigar[n]trabalho de meio período.[n][f 1 3 65535][w][e]

[sel SEL_068_0_0 top]
[s]Ainda podemos fazer isso.[e]
[s]Vamos tentar de outra maneira.[e]

[msg MSG_069_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Contenha seu entusiasmo. Seria[n]muito confuso, se alguma coisa[n]acontecesse com você.[n][f 1 3 65535][w][e]

[msg MSG_070_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Isso pode nos levar de volta ao ponto de partida,[n]mas talvez não tenhamos outra escolha.[n][f 1 3 65535][w][e]

[msg MSG_071_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]Bem, vou voltar para Kosei e[n]continuar a busca.[n][f 1 3 65535][w][e]

[msg MSG_072_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Ah, e estarei conversando com minhas[n]namoradas que frequentam Shibuya.[n][f 1 3 65535][w][e]

[msg MSG_073_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Ok. Prefiro não encontrar a polícia de novo,[n]então vou dar uma olhada na internet por[n]enquanto.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Ok, vamos nos separar. Falaremos sobre isso[n]amanhã, se alguém[n]descobrir alguma coisa.[n][f 1 3 65535][w][e]

[msg MSG_074_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]E onde poderíamos nos reunir?[n]Eu sugeriria um lugar[n]longe de olhares indiscretos.[n][f 1 3 65535][w][e]

[msg MSG_075_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Hum, precisamos de um lugar onde ninguém possa[n]nos ouvir. Que tal karaokê? Também é barato.[n][f 1 3 65535][w][e]

[msg MSG_076_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]Ah, sim, isso seria perfeito. Se não[n]me engano eles também têm uma oferta pela[n]metade do preço, certo? A "hora hippie".[n][f 1 3 65535][w][e]

[msg MSG_077_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]...Cara, é happy hour.[n]O que há com os hippies...?[n][f 1 3 65535][w][e]

