[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Junya Kaneshiro!?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Acalme-se![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu vejo esse nome o tempo todo nos[n]tablóides...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eu acho que essas histórias realmente eram[n]verdadeiras...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... Sim, Kaneshiro tem um palácio.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tudo o que precisamos agora é de informações[n]sobre onde está esse palácio.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Devemos discutir isso amanhã quando todos[n]estiverem conosco.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Um palácio da máfia, hein? Agora estou[n]ficando animado.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Crossdressing Man B]]
[s][vp 8 0 0 0 65535 0]Ooh, o que você está animado?[n]Você não vai nos deixar senhoras de seus[n]pequenos segredos?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Huh? Oh, eu, uh...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Crossdressing Man A]]
[s][vp 8 0 0 0 65535 0]E você e seu amigo vêm comer conosco?[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Eu preciso ir para casa.[e]
[s]Uhhh, estou ocupado.[e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Resposta perfeita![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Crossdressing Man B]]
[s][vp 8 0 0 0 65535 0]Meu, que lamentável.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sim, então vamos precisar passar.[n]Desculpa aí...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Crossdressing Man A]]
[s][vp 8 0 0 0 65535 0]Oh, você não vai a lugar nenhum![n]Você é o espécime perfeito![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]U-u-um...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Deve ser difícil ser popular entre as[n]mulheres.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Huh? Ei...![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Heyyy! Você tem que estar brincando para mim![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Traitoooooor![n][f 1 3 65535][w][e]

