[msg MND_000_0_0]
[s][vp 1 0 0 0 0 0]Onde estou...?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ei...[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Café ok?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Homem de terno e gravata]]
[s][vp 8 0 0 3 6 0][f 4 3].[n]Esse é o seu nome, certo?[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Exatamente.[e]
[s]O que ele quer?[e]

[msg MSG_004_0_0 [Homem de terno e gravata]]
[s][vp 8 0 0 4 6 0]Há alguns dias, em uma estrutura onde[n]ocorriam atividades ilegais,[n]uma colegial foi presa...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 5 6 0]Ela estava semiconsciente com[n]drogas, mas ainda conseguiu[n]um nome... Seu.[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 1 0 0 0 0 0]Minha cabeça dói...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Homem de terno e gravata]]
[s][vp 8 0 0 6 6 0]Gostaríamos de falar mais[n]profundamente sobre as implicações[n]que tudo isso acarreta.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]O que diabos você fez?[n][f 1 3 65535][w][e]

