[msg MSG_000_0_0 [Menacing Man]]
[s][vp 8 0 0 1 65535 0]A-ahhhhhh![n][f 1 2 80][e]

[msg MSG_001_0_0 [Pierced Man]]
[s][vp 6 0 0 2 8 0]Puta merda! Que diabos!?[n][f 1 2 73][e]

[msg MSG_002_0_0 [Menacing Man]]
[s][vp 8 0 0 3 65535 0]Aaaaaaaaaaah![n][f 1 2 85][e]

[msg MSG_003_0_0 [Shadow Kaneshiro]]
[s][vp 1 0 0 4 0 0]Eu posso cuidar disso eu mesmo.[n][f 1 2 60][e]

[msg MSG_004_0_0 [Shadow Kaneshiro]]
[s][vp 1 0 0 5 0 0]Wassup yo!? Agora venha buscar alguns![n][f 1 2 83][e]

[msg MSG_005_0_0 [Makoto]]
[s][vp 1 0 0 6 0 0]Você está imundoso voando com dinheiro[n]sujo... Tire o inferno do meu rosto![n][f 1 2 125][e]

[msg MSG_006_0_0 [Shadow Kaneshiro]]
[s][vp 1 0 0 7 0 0]Gyahahaha! Aight, aqui vamos nós, peças de[n]merda![n][f 1 2 120][e]

