[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Então, a última palavra-chave...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Ela é reclusa, então devemos[n]apenas descobrir "o que"[n]sua casa significa para ela.[n][f 1 3 65535][w][e]
[s][bup 0 2 3 1 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Se ele não consegue sair,[n]talvez ele veja isso como uma prisão?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Ou talvez um labirinto[n]que ele não sabe como sair?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 3 1 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Mmm... Talvez um oásis?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Nada por enquanto. Então,[n]que tal...inferno?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ann]]
[s][bup 0 4 3 1 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]As pistas que temos[n]não são suficientes...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 3 1 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Se ao menos pudéssemos perguntar diretamente a[n]ela...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Pudermos. Vamos lá, vamos[n]encontrar Futaba.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]E o que diremos para[n]fazer-nos abrir a porta?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 11 1 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]O que você quer dizer? Nós nos esgueiramos.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][bup 0 6 4 1 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Você deve estar brincando, espero.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Você não acha que desta vez[n]a porta estará fechada?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Eu cuidarei disso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Ah, e quando invadi[n]noite passada, também descobri[n]onde fica o quarto de Futaba.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][bup 0 6 4 1 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]E se esbarrarmos no chefe?[n]Não poderemos evitar[n]suas perguntas.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ann]]
[s][bup 0 4 0 1 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Por enquanto está funcionando,[n]não devemos ter problemas.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 1 1 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Você está tendo dúvidas, Makoto?[n][f 1 3 65535][w][e]
[s][f 4 16 4 3 300 65535 65535][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Não se preocupe, não é nada.[n]Não é a primeira vez[n]que lidamos com coisas assim.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][bup 0 6 3 1 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]...Não temos outra escolha, não é?[n][f 1 3 65535][w][e]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Presumo que Futaba já tenha entrado em[n]contato com [f 4 2]-kun...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Talvez ela esteja disposta[n]a pelo menos falar com ele...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]...Muito bem. Vamos.[n][f 1 3 65535][w][e]

