[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sobrou algum?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E o que eu sei?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Uma pirâmide antiga, a ressurreição[n]dos mortos...Extremamente fascinante...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não tenho[n]certeza absoluta, mas...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Os antigos egípcios acreditavam que[n]a alma era imortal e que[n]os mortos poderiam voltar à vida.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah sim, a ideia de ressurreição[n]é o motivo que os levou[n]a mumificar os mortos.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eles acreditavam que essas coisas[n]voltariam à vida?[n]Mas se eles secassem![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]É provável que, mesmo assim,[n]as pessoas esperassem se reunir[n]com seus entes queridos após a morte.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Argh, chega dessa porcaria![n]Não estamos na escola, hein?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Se não nos apressarmos e roubar[n]o Tesouro, vamos acabar[n]nos transformando em múmias também![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você tem razão. Vamos.[n][f 1 3 65535][w][e]

