[sel YESNO_SEL top]
[s]Yes.[e]
[s]No.[e]

[msg MSG_000_0_0]
[s]Dummy[n][w][e]

[msg MSG_Fst_MeatFryShop_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0]Ugh... Are all these people in line?[n][w][e]

[msg MSG_Fst_Temple_MORU_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]"Zen meditation," huh...[n][w][e]

[msg MSG_Fst_DartsAndBilliard [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]The place has the air of mature sports.[n][w][e]

[msg MSG_Fst_Cafe_MORU_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]It smells so sweet and delicious...[n][w][e]

[msg MSG_650_104_04_NG [坂本 竜司]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Make sure you stick close, or we're gonna[n]get separated![n][w][e]

[msg MSG_650_104_05_NG [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7194 65535 0]Yo, not that way.[n][w][e]

[msg MSG_650_104_06_NG [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7185 65535 0]Hey, [f 4 2]! The darts lounge[n]is this way.[n][w][e]

[msg MSG_e650_104_HIT_04_mes0 [Makoto]]
[s][bup 0 6 2 65535 0][vp 8 2 0 2100 65535 0]......[n][w][e]

[msg MSG_e650_104_HIT_05_mes0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Ah, this is the road![n][w][e]

[msg MSG_e650_104_HIT_05_mes0_2 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]The name of that shop matches what's[n]on the free tickets.[n][w][e]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]It says... "Penguin Sniper"? Huh? Why'd[n]you give one of those doofy birds a gun?[n][w][e]

[msg MSG_e650_104_HIT_05_mes0_3 [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0]It's not meant to be taken literally...[n][w][e]

[msg MSG_e650_104_HIT_05_mes0_4 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Still, if you're comin' up with a good[n]name... Well, whatever. Let's check it out![n][w][e]

[msg MSG_e650_104_HIT_07_mes0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7020 65535 0]Ohh! Here, this is the place.[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh man, I'm getting kind of nervous...[n][w][e]

[msg MSG_e650_104_HIT_07_mes0_2 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Ha, you're such a child. Try not to[n]embarrass the rest of us, would you?[n][w][e]

[msg MSG_e650_104_HIT_07_mes0_3 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]You don't gotta tell me that![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]So, what's the plan? You wanna head[n]inside?[n][w][e]

[msg MSG_e650_104_HIT_07_NO [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7080 65535 0]Sure thing. We know where the place is[n]now, so we can wander around a bit.[n][w][e]

[msg MSG_e650_104_HIT_08_mes0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]This is the darts lounge that I got free[n]tickets for. You wanna head inside?[n][w][e]

[msg MSG_e650_104_HIT_08_NO [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Alright, let's walk around a bit more.[n][w][e]

[sel MSG_e650_104_END_SEL top]
[s]Let's go.[e]
[s]I still want to look around.[e]

[msg MSG_SYSTEM_SHORTCUT_DART]
[s]You can now quick travel to[n][clr 6]Darts & Billiards[clr 0] in Kichijoji.[n][w][e]

