[sel YESNO_SEL top]
[s]Yes[e]
[s]No[e]

[msg MSG_000_0_0]
[s]Dummy[n][w][e]

[msg MSG_026_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Wait, don't tell me you're going in[n]your uniform![n][w][e]

[msg MSG_026_5_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]If you go like that, you'll just stand[n]out to the police.[n][w][e]

[msg MSG_027_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]That should be fine.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Come on, let's go.[n][w][e]

