[sel YESNO_SEL top]
[s]Yes[e]
[s]No[e]

[msg MSG_ACT_FLD_RYUJI_01 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7018 65535 0]Hey, it's this way![n][w][e]

[msg MSG_ACT_FLD_RYUJI_02 [Ryuji]]
[s][f 4 23 1 857 3 5 0 5][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7045 65535 0]This is it. Pretty legit, huh?[n][w][e]

[sel SEL_ACT_FLD_RYUJI top]
[s]This place looks sketchy.[e]
[s]This is exciting.[e]

[msg MSG_ACT_FLD_RYUJI_03 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 1 0 0 0 65535 0]Right? To be honest, it'd be a bit[n]scary to go in alone...[n][w][e]

[msg MSG_ACT_FLD_RYUJI_04 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 1 0 0 0 65535 0]Oh, are you into this sorta military stuff?[n][w][e]

[msg MSG_ACT_FLD_RYUJI_05 [Ryuji]]
[s][f 4 23 1 857 3 5 0 5][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 0 65535 0]Anyways, let's check out what's inside.[n][w][e]

[msg MSG_ACT_FLD_RYUJI_10 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]Oh yeah, before we head in...[n]you know anything about guns[n]and shit?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]I guess we can just ask the guy[n]behind the counter if we can't figure[n]out what we want. C'mon, let's do this.[n][w][e]

[msg MND_CHK_STATION]
[s][vp 1 0 0 0 0 0]I shouldn't just go home...[n][w][e]
[s][vp 1 0 0 0 0 0]I'll just follow Ryuji for now...[n][w][e]

[msg MND_CHK_STATION2]
[s][vp 1 0 0 0 0 0]I shouldn't leave right now.[n][w][e]
[s][vp 1 0 0 0 0 0]There has to be somewhere I can[n]find potent medicine around here...[n][w][e]

[msg MND_BAITO_KARAOKE_NG]
[s][vp 1 0 0 0 0 0]It doesn't look like this[n]place sells any weapons...[n][w][e]

[msg MND_BAITO_KARAOKE_NG2]
[s][vp 1 0 0 0 0 0]It doesn't look like this place[n]sells the potent medicine I need...[n][w][e]

[msg MND_BAITO_GYUUDON_NG]
[s][vp 1 0 0 0 0 0]It doesn't look like this[n]place sells any weapons...[n][w][e]

[msg MND_BAITO_GYUUDON_NG2]
[s][vp 1 0 0 0 0 0]It doesn't look like this place[n]sells the potent medicine I need...[n][w][e]

[msg MND_BAITO_IZAKAYA_NG]
[s][vp 1 0 0 0 0 0]It doesn't look like this[n]place sells any weapons...[n][w][e]

[msg MND_BAITO_IZAKAYA_NG2]
[s][vp 1 0 0 0 0 0]It doesn't look like this place[n]sells the potent medicine I need...[n][w][e]

[msg MND_BAITO_FAMIRES_NG]
[s][vp 1 0 0 0 0 0]It doesn't look like this[n]place sells any weapons...[n][w][e]

[msg MND_BAITO_FAMIRES_NG2]
[s][vp 1 0 0 0 0 0]It doesn't look like this place[n]sells the potent medicine I need...[n][w][e]

[msg MND_CHK_WEAPON_SHOP]
[s][vp 1 0 0 0 0 0]It looks like this is the[n]airsoft shop I've heard about...[n][w][e]

[msg MND_CHK_ITEM_SHOP]
[s][vp 1 0 0 0 0 0]This must be the clinic[n]with the quack doctor who[n]prescribes weird medication...[n][w][e]

[msg MSG_TEST_KFE [Test]]
[s]Dummy[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_MILI]
[s]You can now quick travel to the[n][clr 6]Airsoft Shop[clr 0] in Shibuya.[n][w][e]

