[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7001 65535 0]Yo. Por acaso acordei cedo para variar.[n][f 1 3 65535][w][e]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esse idiota kamoshida... não podemos deixar[n]alguém assim correr livre.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Deixe-me saber se você está indo para o[n]palácio.[n]Sempre é bom para mim.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Como está hoje depois da escola?[e]
[s]Estou contando com você.[e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7107 65535 0]Claro que está tudo bem. Tudo bem, vamos nos[n]encontrar no telhado depois da escola.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As coisas vão começar a ficar ocupadas.[n]Temos que nos preparar...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7023 65535 0]Sim, eu peguei suas costas, cara! Então, não[n]deixe de falar comigo quando sair, sim?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]As coisas vão começar a ficar ocupadas.[n]Temos que nos preparar...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ei! Faltam apenas uma semana até a reunião[n]do Conselho de Administração![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Não posso vingar shiho assim- ou fazer[n]qualquer coisa sobre a expulsão de seus[n]rapazes![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Temos que nos apressar. Ei, podemos ir ao[n]palácio hoje?[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]Vamos fazer isso.[f 2 7 0 1 971 1][e]
[s]Não podemos ficar impacientes.[e]

[msg MSG_008_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Tudo bem. Vamos nos encontrar depois da[n]escola no esconderijo. Vou esperar pelo seu[n]texto.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 5 65535 0][bup 0 4 2 65535 0][f 4 10 65535 0 0]Ele não pode correr de graça depois de fazer[n]Shiho sofrer assim...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 6 65535 0][f 4 10 65535 0 0]É tão injusto. Vou fazê-lo pagar.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Você está me dizendo para esfriar e pensar[n]com mais calma? Ugh, eu tendem a me sentir[n]de cabeça para baixo rapidamente...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Mas não temos muito tempo.[n]Acho que devemos fazer o que pudermos o mais[n]rápido possível.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Vou deixar a decisão para você...[n]Mas entre em contato comigo o mais rápido[n]possível quando sentir vontade de ir.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Ah, bom dia... lotado como sempre hoje, hein?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Encontramos o tesouro, então tudo o que[n]resta é enviar o cartão de visita.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Temos menos de uma semana agora até a[n]reunião do conselho... o que você quer[n]fazer hoje?[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]Vamos enviar o cartão de visita.[f 2 7 0 1 971 1][e]
[s]Eu quero pensar nisso.[e]

[msg MSG_013_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]... Então chegou a hora. Vamos tirar os[n]desejos repugnantes de Kamoshida![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Ok, vejo você depois da escola no[n]esconderijo![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]...Entendi. Afinal, temos um pouco de tempo[n]até a reunião do conselho.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Bem, entre em contato comigo quando tomar[n]sua decisão. Eu vou acabar imediatamente.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Manhã! Lotado como sempre hoje, hein?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Como você gosta de ser embalado como[n]sardinha, estilo da cidade? Aposto que você[n]já teve o suficiente.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]... Eu não pretendo brincar por aí.[n]Eu simplesmente não sei o que fazer.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 20 65535 0][f 4 10 65535 0 0]Fico ansioso, a menos que esteja fazendo[n]alguma coisa, mas aqui estou de repente,[n]sem nada para fazer.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]É tão horrível apenas esperando os[n]resultados, não é? É tão preocupante...[n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s]Estou preocupado também.[e]
[s]Tenho certeza que as coisas estão indo bem.[e]

[msg MSG_018_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Você também, hein, [f 4 2]? Claro que você é. Desculpe por fazer uma[n]pergunta tão estranha.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Acho que tudo o que podemos fazer é[n]esperar... eu me pergunto como a condição[n]de Shiho também é.[n][f 1 3 65535][w][e]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Cara, toda essa conversa pesada logo de[n]manhã! Nós dois precisamos trocar de[n]engrenagem, [f 4 2].[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Você está certo... tudo o que podemos fazer[n]é acreditar e esperar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Obrigado. Eu me sinto melhor depois de falar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Não é bom ser um deprimente de manhã. Bem,[n]vamos ter um ótimo dia hoje![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0]Whaddup! Ufa, chegou na hora...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu tenho que manter minha força para coisas[n]como essa, então estava tomando café da[n]manhã e saí de casa tarde.[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De qualquer forma, estou cheio de energia.[n]Espero que você me deixe correr solto no[n]palácio hoje.[n][f 1 3 65535][w][e]

[sel SEL_022_0_0 top]
[s]É claro.[f 2 7 0 1 971 1][e]
[s]Vou pensar sobre isso.[e]

[msg MSG_023_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7023 65535 0]Oh sim! Eu tenho esse![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Vejo você no esconderijo depois da escola[n]então. Estarei esperando com tudo o que[n]tenho![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Nós vamos fazer um sinal de linha para o[n]tesouro![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7037 65535 0]O que, tem algo em sua mente?[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... bem, tudo bem. Mas pense um pouco sobre[n]o palácio.[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Basta ligar para o esconderijo depois da[n]escola, se você sentir vontade de ir.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0]Whaddup! Ufa, chegou na hora...[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Precisamos da nossa força se vamos derrubar[n]Kamoshida, certo? Correu tarde porque eu[n]comi três tigelas de arroz...[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De qualquer forma, estou cheio de energia.[n]Terei muito o que sobrar para correr solto[n]no palácio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Terminamos a investigatin 'It, para que[n]devemos enviar o cartão de visita hoje.[n][f 1 3 65535][w][e]

[sel SEL_027_0_0 top]
[s]Vamos fazê-lo.[f 2 7 0 1 971 1][e]
[s]Vou pensar sobre isso.[e]

[msg MSG_028_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7103 65535 0]Esse é o espírito![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vou contar a Ann também. Não se esqueça,[n]cara.[n]Estamos indo para o telhado depois da escola.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7038 65535 0]Botcha... bem, temos algum tempo antes da[n]reunião do conselho.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ainda assim, nossa expulsão está na linha.[n]Não podemos procrastinar para sempre.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0]Whaddup! * Pant* Eu fiz...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu dormi, então saí sem tomar café da[n]manhã...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu me sinto tão fraco por causa disso...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Depois que derrubamos Kamoshida, me sinto[n]tão gasto e fora de gás, sabe?[n]Você me pega, certo?[n][f 1 3 65535][w][e]

[sel SEL_032_0_0 top]
[s]Eu faço.[e]
[s]Você está relaxando.[e]

[msg MSG_033_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7035 65535 0]Direita? Agora tudo o que resta a fazer é[n]esperar por essa reunião do conselho...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De qualquer forma, estou com fome. Acho que[n]vou comprar um pouco de pão na loja da[n]escola...[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 7028 65535 0]Você está muito duro comigo, cara...[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quero dizer, não temos garantia de que ele[n]terá uma mudança de coração, mas a única[n]coisa que podemos fazer agora é esperar...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ugh, me preocupar com isso me deixa ainda[n]mais faminto. Acho que vou comprar um pouco[n]de pão na loja da escola...[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 7167 65535 0]Ei, está quase na hora da reunião do[n]conselho! Não me diga que você esqueceu![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Temos que mudar o coração de Kamoshida, ou[n]vamos ser expulsos![n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos para o palácio hoje![n][f 1 3 65535][w][e]

[sel SEL_037_0_0 top]
[s]Meus pensamentos exatamente.[f 2 7 0 1 971 1][e]
[s]Vou pensar sobre isso.[e]

[msg MSG_038_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7103 65535 0]Ah sim! É disso que estou falando![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vejo você no esconderijo depois da escola![n]Não se atrase![n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7025 65535 0]Gah... você realmente só vai no seu próprio[n]ritmo, não é!? Como você está tão frio[n]nesta situação!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*suspiro* Eu nem tenho energia para[n]reclamar quando você está sendo tão[n]indiferente com isso...[n][f 1 3 65535][w][e]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De qualquer forma, diga-me imediatamente se[n]você mudar de idéia. Tudo bem!?[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 7167 65535 0]Ei, está quase na hora da reunião do[n]conselho! Não me diga que você esqueceu![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Temos que mudar o coração de Kamoshida, ou[n]vamos ser expulsos![n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos enviar o cartão de visita o mais[n]rápido possível![n][f 1 3 65535][w][e]

[sel SEL_042_0_0 top]
[s]Vamos fazê-lo.[f 2 7 0 1 971 1][e]
[s]Vou pensar sobre isso.[e]

[msg MSG_043_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7103 65535 0]Ah sim! É disso que estou falando![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ok, vou contar a Ann também. Vamos ter uma[n]reunião de estratégia no telhado depois da[n]escola. Não se atrase![n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7025 65535 0]Gah, você realmente só vai no seu próprio[n]ritmo, não é!? * suspiro* Eu nem tenho[n]energia para reclamar...[n][f 1 3 65535][w][e]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De qualquer forma, diga-me imediatamente se[n]você mudar de idéia. Tudo bem!?[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7028 65535 0]Whaddup...[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ele mudou de coração de verdade, não foi?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]É meio difícil de acreditar agora...[n][f 1 3 65535][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vou chorar se ainda formos expulsos depois[n]de tudo isso.[n][f 1 3 65535][w][e]

[sel SEL_047_0_0 top]
[s]Vamos acreditar, e esperar.[e]
[s]Eu também...[e]

[msg MSG_048_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Você está tão calmo, cara... você não está[n]preocupado?[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh sim! Você está livre hoje?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se você não tem nada para fazer, venha me[n]ver depois da escola.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não é como se eu tivesse algo a dizer, mas[n]acho que falar ajuda a acalmar os nervos.[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7082 65535 0]Direita? Eu sabia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu ficaria super decepcionado se você me[n]dissesse para me acalmar e esperar ou algo[n]assim.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh sim! Você está livre hoje?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se você não tem nada para fazer, venha me[n]ver depois da escola.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não é como se eu tivesse algo a dizer, mas[n]acho que falar ajuda a acalmar os nervos.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6186 65535 0]Oh. Acho que temos a mesma transferência de[n]trem.[n][f 1 3 65535][w][e]
[s][bup 0 4 3 65535 0][vp 8 2 65535 6197 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu sei que estou sendo um pouco franco, mas[n]me pergunto se ficaremos bem indo neste[n]ritmo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Por que não vamos ao palácio hoje?[n]Só não quero ter arrependimentos.[n][f 1 3 65535][w][e]

[sel SEL_052_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Vou pensar sobre isso.[e]

[msg MSG_053_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6034 65535 0]Tudo bem, estarei esperando por você no[n]esconderijo depois da escola.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][bup 0 4 2 65535 0][f 4 10 65535 0 0]Não podemos deixar que esse bastardo[n]continue fazendo o que ele quiser.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][bup 0 4 0 65535 0][f 4 10 65535 0 0]Isso é uma promessa, ok? Não se espalhe para[n]mim.[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6186 65535 0]Desculpe. Eu sei que estou ficando[n]desesperado. Mesmo assim, eu quero que ele mude de[n]coração o mais rápido possível...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][bup 0 4 0 65535 0][f 4 10 65535 0 0]De qualquer forma, posso ir a qualquer[n]momento, então ligue para o esconderijo[n]depois da escola, se você estiver pronto[n]para isso.[n][f 1 3 65535][w][e]

[msg MSG_055_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6028 65535 0]Manhã. Ainda me sinto um pouco cansado de[n]todo esse trabalho duro. E quanto a você?[n][f 1 3 65535][w][e]

[msg MSG_056_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Encontramos o tesouro, então tudo o que[n]resta é enviar o cartão de visita.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Temos algum tempo até a reunião do conselho.[n]O que você quer fazer hoje?[n][f 1 3 65535][w][e]

[sel SEL_057_0_0 top]
[s]Vamos enviar o cartão de visita.[f 2 7 0 1 971 1][e]
[s]Eu quero pensar mais nisso.[e]

[msg MSG_058_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6034 65535 0]Não posso simplesmente sentar e não fazer[n]nada quando penso em Shiho.[n][f 1 3 65535][w][e]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E eu também não vou deixar vocês serem[n]expulsos. Kamoshida não vai se safar com[n]isso...![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Falaremos com mais detalhes depois da escola.[n][f 1 3 65535][w][e]

[msg MSG_059_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6063 65535 0]Entendo... encontramos o tesouro, mas acho[n]que ainda não sabemos o que mais está lá.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ainda temos tempo e não quero cometer erros[n]só porque estava sendo impaciente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estou feliz que você seja o calmo, [n][f 4 2], mas deixe-me saber se você mudar de idéia.[n][f 1 3 65535][w][e]

[msg MSG_060_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6186 65535 0]Bom dia...[n][f 1 3 65535][w][e]

[msg MSG_061_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Uhh...[n][f 1 3 65535][w][e]
[s][vp 8 2 65535 6197 0 0]......[n][f 1 3 65535][w][e]

[sel SEL_062_0_0 top]
[s]Você tem alergias?[e]
[s]E aí?[e]

[msg MSG_063_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 6192 65535 0]... alergias? Oh, uh, talvez! Eu me sinto[n]meio atordoado, e tudo parece estranho![n][f 1 3 65535][w][e]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas... hum... na verdade... tenho a sensação[n]de que alguém está me observando[n]ultimamente...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Espero que não...[n][f 1 3 65535][w][e]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 23 0 4 62 10 60 10]Oh! Talvez eu simplesmente não possa se[n]livrar da sensação de se infiltrar em um[n]palácio![n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No palácio, sempre estamos cautelosos por[n]não ser notados, você sabe![n][f 1 3 65535][w][e]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então tem que ser minha imaginação... sim...[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Isso me lembra, temos uma assembléia escolar[n]esta manhã- algo sobre um novo membro do[n]corpo docente.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eu apenas rezo para que seja alguém no meio[n]do caminho decente...[n][f 1 3 65535][w][e]

[msg MSG_064_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6027 65535 0]Na verdade... tenho a sensação de que alguém[n]está me observando ultimamente...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não, não pode ser...[n][f 1 3 65535][w][e]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 23 0 4 62 10 60 10]Oh! Talvez eu simplesmente não possa se[n]livrar da sensação de se infiltrar em um[n]palácio![n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No palácio, sempre estamos cautelosos por[n]não ser notados, você sabe![n][f 1 3 65535][w][e]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então tem que ser minha imaginação... sim...[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Isso me lembra, temos uma assembléia escolar[n]esta manhã- algo sobre um novo membro do[n]corpo docente.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eu apenas rezo para que seja alguém no meio[n]do caminho decente...[n][f 1 3 65535][w][e]

[msg MSG_065_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6005 65535 0]Manhã![n][f 1 3 65535][w][e]

[msg MSG_066_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6155 65535 0]A exposição Madarame dura até o dia 5 do[n]próximo mês... Temos que mudar seu coração[n]até então.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]As obras de arte em exibição também foram[n]feitas por seus alunos, não eram? Não[n]podemos deixar isso em paz.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Ei, que tal hoje?[n]Quer ir para o palácio?[n][f 1 3 65535][w][e]

[sel SEL_067_0_0 top]
[s]Vamos fazê-lo.[f 2 7 0 1 971 1][e]
[s]Deixe-me pensar sobre isso.[e]

[msg MSG_068_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6034 65535 0]Sim... nós temos que roubar o coração de[n]Madarame o mais rápido possível. Então[n]Kitagawa-kun também pode mudar...[n][f 1 3 65535][w][e]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ele está mentindo para si mesmo. Eu sei,[n]porque era assim que eu estava com[n]Kamoshida.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, eu te vejo no esconderijo depois da[n]escola. Estou contando com você, líder![n][f 1 3 65535][w][e]

[msg MSG_069_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6027 65535 0]... tudo bem, mas acho que devemos nos[n]apressar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Kitagawa-kun está mentindo para si mesmo. Eu[n]sei, porque era assim que eu estava com[n]Kamoshida.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu posso estar ultrapassando meus limites...[n]Mas eu quero ajudá-lo! Avise-me quando[n]sentir vontade de ir![n][f 1 3 65535][w][e]

[msg MSG_070_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7003 65535 0]Yo. Então começa hoje, hein?[n][f 1 3 65535][w][e]

[msg MSG_071_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, o que você vai fazer? Quer ir para o[n]palácio?[n][f 1 3 65535][w][e]

[sel SEL_072_0_0 top]
[s]Vamos fazê-lo.[f 2 7 0 1 971 1][e]
[s]Ainda estou pensando nisso.[e]

[msg MSG_073_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7023 65535 0]Awhright, vamos para o esconderijo depois da[n]escola, então![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][bup 0 2 0 65535 0][f 4 10 65535 0 0]Eu não sei muito sobre arte, mas ele tem[n]habilidade, não é?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então temos que ajudá-lo! Será uma merda se[n]algo acontecesse com ele como o que[n]aconteceu comigo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][bup 0 2 1 65535 0][f 4 10 65535 0 0]Então, eu vou dar tudo o meu![n]Eu estou pulando você também![n][f 1 3 65535][w][e]

[msg MSG_074_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7197 65535 0]Pode ser uma boa ideia ir mais cedo, mas[n]todos devem falar sobre isso primeiro.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Não sei muito sobre arte, mas não quero o[n]que aconteceu comigo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Eu quero abrir os olhos dele antes que seus[n]sonhos sejam esmagados.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][bup 0 2 1 65535 0][f 4 10 65535 0 0]Então, eu estarei esperando por você depois[n]da escola![n][f 1 3 65535][w][e]

[msg MSG_075_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 93 65535 0]Bom tempo. Eu queria te dizer uma coisa.[n][f 1 3 65535][w][e]

[msg MSG_076_0_0 [Yusuke]]
[s][vp 8 0 0 94 65535 0][bup 0 5 0 65535 0][f 4 10 65535 0 0]Madarame estava conversando com um advogado.[n]Suponho que ele está falando sério sobre[n]processar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 95 65535 0]Acho que devemos avançar nossos planos.[n]Por que não vamos ao palácio hoje?[n][f 1 3 65535][w][e]

[sel SEL_077_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Temos que nos preparar primeiro.[e]

[msg MSG_078_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 96 65535 0]Excelente. Eu quero parar esse homem o mais[n]rápido possível.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 97 65535 0]Nesse caso, vamos montar depois da escola.[n]Eu vou acabar em breve.[n][f 1 3 65535][w][e]

[msg MSG_079_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 98 65535 0]É verdade que você nunca sabe o que[n]acontecerá no palácio. Devemos nos preparar[n]bem.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 99 65535 0][bup 0 5 1 65535 0][f 4 10 65535 0 0]É bom ter uma pessoa calma e racional por[n]perto. Estou contando com você.[n][f 1 3 65535][w][e]

[msg MSG_080_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 100 65535 0]Você também monta este trem neste momento?[n]Que coincidência.[n][f 1 3 65535][w][e]

[msg MSG_081_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 101 65535 0]Terminamos de investigar o palácio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 102 65535 0]Tudo o que resta é o cartão de visita.[n]Quando você vai enviar?[n][f 1 3 65535][w][e]

[sel SEL_082_0_0 top]
[s]Vamos enviar hoje.[f 2 7 0 1 971 1][e]
[s]Depois de nos prepararmos.[e]

[msg MSG_083_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 103 65535 0]Esse é o espírito. Eu quero parar esse homem[n]o mais rápido possível.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 104 65535 0]Vamos nos reunir depois da escola então.[n]Eu vou estar esperando por você.[n][f 1 3 65535][w][e]

[msg MSG_084_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 105 65535 0]Então, quanto mais importante é, mais[n]cauteloso devemos ser... você tem razão.[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 106 65535 0]Você é confiável, como eu pensava.[n]Vou deixar o momento do cartão de visita sob[n]seus cuidados.[n][f 1 3 65535][w][e]

[msg MSG_085_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4002 65535 0]Você também monta este trem neste momento?[n]Que coincidência.[n][f 1 3 65535][w][e]

[msg MSG_086_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 4127 65535 0]Em relação à Madarame, sua saúde permanece a[n]mesma. Não há diferenças notáveis.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Uma mudança de coração realmente ocorrerá...?[n][f 1 3 65535][w][e]

[sel SEL_087_0_0 top]
[s]Isso vai acontecer.[e]
[s]Preocupado?[e]

[msg MSG_088_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0]...Que estranho. Eu acredito em você quando[n]você diz isso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você teve sucesso com Kamoshida.[n]Muito bem... vou esperar também e confiar[n]que ele mudará.[n][f 1 3 65535][w][e]

[msg MSG_089_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0]...Mais ou menos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ainda assim, fizemos tudo o que podíamos.[n]Muito bem... vou ter que esperar e confiar[n]que ele mudará.[n][f 1 3 65535][w][e]

[msg MSG_090_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6028 65535 0]Bom dia...[n][f 1 3 65535][w][e]

[msg MSG_091_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Havia um especial sobre a exposição Madarame[n]no News ontem...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eles estavam elogiando muito Madarame.[n]Ninguém sabe que as pessoas estão sofrendo[n]nos bastidores...[n][f 1 3 65535][w][e]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 6190 65535 0]Observar isso me deixou impaciente. Vamos[n]para o palácio![n][f 1 3 65535][w][e]

[sel SEL_092_0_0 top]
[s]Vamos hoje.[f 2 7 0 1 971 1][e]
[s]Vou pensar sobre isso.[e]

[msg MSG_093_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6034 65535 0]Sim! Eu quero ajudar Kitagawa-kun.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Todos nós trabalharemos juntos para mudar[n]seu coração. Vamos nos encontrar depois da[n]escola.[n][f 1 3 65535][w][e]

[msg MSG_094_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6166 65535 0]... estou ficando muito nervoso? Ainda[n]assim, há a coisa com Kitagawa-kun...[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu quero mudar o coração de Madarame, então[n]pense nisso, ok?[n][f 1 3 65535][w][e]

[msg MSG_095_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4006 65535 0]Ah, é você...[n][f 1 3 65535][w][e]

[msg MSG_096_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A propósito, vi um grande sinal para a[n]exposição Madarame no caminho aqui...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Não pude deixar de lembrar do museu de arte[n]repugnante. Devemos pressa em destruir esse[n]mundo...[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... Por que não vamos ao palácio hoje?[n][f 1 3 65535][w][e]

[sel SEL_097_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Não seja impaciente.[e]

[msg MSG_098_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4035 65535 0]De fato. Teremos que encontrar esse tesouro[n]ou o que quer que seja.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos montar depois da escola então.[n]Estou contando com você.[n][f 1 3 65535][w][e]

[msg MSG_099_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4107 65535 0]Não é apenas importante ir devagar, mas[n]também, hein?...Entendido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, entre em contato comigo quando for.[n][f 1 3 65535][w][e]

[msg MSG_100_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4006 65535 0]Ah, é você...[n][f 1 3 65535][w][e]

[msg MSG_101_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A propósito, vi um grande sinal para a[n]exposição Madarame no caminho aqui...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Não pude deixar de lembrar do museu de arte[n]repugnante. Devemos pressa em destruir esse[n]mundo...[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Podemos enviar o cartão de visita agora,[n]correto? Você não vai enviar?[n][f 1 3 65535][w][e]

[sel SEL_102_0_0 top]
[s]Vamos enviá-lo imediatamente.[f 2 7 0 1 971 1][e]
[s]Ainda não.[e]

[msg MSG_103_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4035 65535 0]De fato, sabemos onde o tesouro já está. Não[n]temos motivos para hesitar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos montar depois da escola então. É hora[n]de jogar um requiem para Madarame...![n][f 1 3 65535][w][e]

[msg MSG_104_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 4141 65535 0]Sabemos onde está o tesouro agora.[n]Existe uma preparação adicional que[n]precisamos?[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Que assim seja. Deixo o momento do cartão[n]de visita para você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Só não chegue tarde demais com isso.[n][f 1 3 65535][w][e]

[msg MSG_105_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4006 65535 0]Ah, é você...[n][f 1 3 65535][w][e]

[msg MSG_106_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Madarame está doente, mas a exposição ainda[n]está forte.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Não posso mais respeitá-lo como meu sensei...[n]Mas é triste pensar que não tenho mais um[n]mentor.[n][f 1 3 65535][w][e]

[sel SEL_107_0_0 top]
[s]Por que não fazer uma pausa?[e]
[s]Eu sou todo ouvidos se você precisar.[e]

[msg MSG_108_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0]Uma pausa, hein... Não consigo pensar em[n]nada para fazer.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu não sou do tipo que vai ao ar livre.[n]Suponho que pintar é o que faço para relaxar.[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, talvez eu possa precisar de uma tábua[n]em algum momento. Espero que você me humore[n]então.[n][f 1 3 65535][w][e]

[msg MSG_109_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 4090 65535 0]Conversa...? Para você?[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... Agora que penso nisso, não acredito que[n]já tive alguém com quem eu poderia[n]simplesmente conversar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, talvez eu possa precisar de uma tábua[n]em algum momento. Espero que você me humore[n]então.[n][f 1 3 65535][w][e]

[msg MSG_110_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54250 65535 0]Wassup.[n][f 1 3 65535][w][e]

[msg MSG_111_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 7192 65535 0]Nós realmente vamos ficar bem? A exposição é[n]apenas até este fim de semana.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos mudar o coração dele antes que ele[n]termine, certo? Temos que ir ao palácio em[n]breve ou estamos com problemas.[n][f 1 3 65535][w][e]

[sel SEL_112_0_0 top]
[s]Vamos hoje.[f 2 7 0 1 971 1][e]
[s]Ainda estamos bem.[e]

[msg MSG_113_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7045 65535 0]Sim! Temos que arrancar a máscara deste[n]artista falso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos nos encontrar depois da escola então![n]Eu estarei esperando![n][f 1 3 65535][w][e]

[msg MSG_114_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7106 65535 0]Tem certeza...? O final de maio, você sabe.[n][f 1 3 65535][w][e]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A exposição é apenas até este fim de semana.[n]Só não se esqueça disso, tudo bem?[n][f 1 3 65535][w][e]

[msg MSG_115_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7087 65535 0]Wassup.[n][f 1 3 65535][w][e]

[msg MSG_116_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, já procuramos totalmente no palácio,[n]certo?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A exposição é apenas até este fim de semana,[n]para que devemos enviar o cartão de visita[n]em breve.[n][f 1 3 65535][w][e]

[sel SEL_117_0_0 top]
[s]Vamos enviá-lo imediatamente.[f 2 7 0 1 971 1][e]
[s]Ainda não.[e]

[msg MSG_118_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Hehe, finalmente chegou a hora.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, vamos nos encontrar depois da escola![n]Eu estarei esperando no esconderijo![n][f 1 3 65535][w][e]

[msg MSG_119_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7038 65535 0]Sério...? Não temos muito tempo.[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas, vou deixar isso para você. Deixe-me[n]saber quando terminar os preparativos.[n][f 1 3 65535][w][e]

[msg MSG_120_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0]Wassup.[n][f 1 3 65535][w][e]

[msg MSG_121_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A propósito, a exposição até o final desta[n]semana, hein...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Fizemos o que podíamos e agora esperamos[n]pelos resultados.[n][f 1 3 65535][w][e]

[sel SEL_122_0_0 top]
[s]Quer sair?[e]
[s]Vamos estudar.[e]

[msg MSG_123_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7048 65535 0]É verdade que é importante respirar depois[n]de algum trabalho duro.[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas sinto que meu corpo ficará mais fraco se[n]eu brincar demais...[n][f 1 3 65535][w][e]

[msg MSG_124_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 7037 65535 0]Não. Essa é uma opção que é definitiva "não".[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A escola é o suficiente para estudar.[n]Vamos exercitar, cara![n][f 1 3 65535][w][e]

[msg MSG_125_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 6155 65535 0]Ei, [f 4 2]![n][f 1 3 65535][w][e]

[msg MSG_126_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A exposição de Madarame é até o dia 5, você[n]sabe. Estamos cortando perto...[n][f 1 3 65535][w][e]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ainda não sabemos onde o tesouro ainda está.[n]Deveríamos realmente ir ao palácio hoje![n][f 1 3 65535][w][e]

[sel SEL_127_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Ainda estamos bem.[e]

[msg MSG_128_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6034 65535 0]Direita. Isso é um alívio![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, eu estarei esperando depois da escola,[n]então não se esqueça![n][f 1 3 65535][w][e]

[msg MSG_129_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6047 65535 0]Sério...? Mas ainda não começamos nada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E temos que enviar um cartão de visita para[n]fazer o tesouro aparecer...[n][f 1 3 65535][w][e]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... Sim, devemos ir hoje, não importa o quê![n]Estarei esperando depois da escola, então[n]entre em contato comigo.[n][f 1 3 65535][w][e]

[msg MSG_130_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 107 65535 0]Ei, [f 4 2].[n][f 1 3 65535][w][e]

[msg MSG_131_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 108 65535 0]Você está ciente da situação?[n]A exposição termina neste fim de semana.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 109 65535 0]Não temos tempo. Não devemos ir ao palácio?[n][f 1 3 65535][w][e]

[sel SEL_132_0_0 top]
[s]Vamos hoje.[f 2 7 0 1 971 1][e]
[s]Ainda estamos bem.[e]

[msg MSG_133_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 110 65535 0]Eu vejo. Tudo bem.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 111 65535 0]Então vamos montar depois da escola.[n]Não se esqueça disso.[n][f 1 3 65535][w][e]

[msg MSG_134_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 112 65535 0]Deixe-me dizer que Sensei- Madarame é sério.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 113 65535 0]Ele trabalhará para destruir todos os três[n]quando a exposição terminar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 114 65535 0]Não podemos desperdiçar mais um minuto.[n]Pense em entrar hoje.[n][f 1 3 65535][w][e]

[msg MSG_135_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 115 65535 0]Ah, [f 4 2]... Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_136_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 116 65535 0]Fizemos tudo o que podíamos, mas é irritante[n]apenas esperando os resultados...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 117 65535 0]... Ei, por que não vamos para lembranças[n]hoje?[n][f 1 3 65535][w][e]

[sel SEL_137_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Outra hora.[e]

[msg MSG_138_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 118 65535 0]Seria ótimo. Eu gostaria de mover meu corpo[n]o máximo possível agora para tirar minha[n]mente das coisas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 119 65535 0]Bem, eu te vejo depois da escola então.[n][f 1 3 65535][w][e]

[msg MSG_139_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 120 65535 0]Eu vejo. Isso é decepcionante...[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 121 65535 0]Entre em contato comigo a qualquer momento[n]se mudar de idéia.[n][f 1 3 65535][w][e]

[msg MSG_140_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 133 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_141_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 134 65535 0]Ouvi falar de ontem de Ryuji e Ann.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 135 65535 0]Um detetive do ensino médio, hein...[n]Um sujeito problemático nos notou.[n][f 1 3 65535][w][e]

[sel SEL_142_0_0 top]
[s]Deixe-o falar.[e]
[s]É preocupante.[e]

[msg MSG_143_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 136 65535 0]Verdadeiro. Akechi é famoso, mas ele ainda é[n]um "civil"...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 137 65535 0]Eu não acho que ele descobrirá nossas[n]identidades, mas ele arruinar nossa[n]reputação deixa um gosto ruim.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 138 65535 0]Podemos precisar pensar em uma solução...[n][f 1 3 65535][w][e]

[msg MSG_144_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 139 65535 0]Concordou. Aquele companheiro de Akechi é[n]famoso, não é?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 140 65535 0]Eu não acho que ele descobrirá nossas[n]identidades, mas ele arruinar nossa[n]reputação deixa um gosto ruim.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 141 65535 0]Podemos precisar pensar em uma solução...[n][f 1 3 65535][w][e]

[msg MSG_145_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6005 65535 0]Bom Dia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nós iremos? Você conseguiu alguma informação?[n][f 1 3 65535][w][e]

[msg MSG_146_0_0 [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vou te dizer logo de cara que não encontrei[n]nada. Eu até perguntei em um monte de[n]lugares também...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A máfia realmente existe?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 6028 65535 0]Existem bandidos em todos os lugares, mas[n]máfia? Em Tóquio...?[n][f 1 3 65535][w][e]

[sel SEL_147_0_0 top]
[s]Tóquio é um grande lugar.[e]
[s]Tóquio é um lugar assustador.[e]

[msg MSG_148_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sim, isso é verdade... nossas vidas[n]acontecem em torno de Shibuya, afinal...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 6129 65535 0]Você acha que vamos descobrir mais se formos[n]mais profundamente, para uma cidade mais[n]adulta?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De qualquer forma, vamos continuar coletando[n]informações hoje.[n][f 1 3 65535][w][e]

[msg MSG_149_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6026 65535 0]Vamos lá, já se passaram dois meses desde[n]que você veio aqui.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... Embora Tóquio tenha áreas mais profundas[n]e "adultas" que Shibuya.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Acha que vamos aprender algo se formos a[n]esses lugares? De qualquer forma, vamos[n]continuar coletando informações hoje.[n][f 1 3 65535][w][e]

[msg MSG_150_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 170 65535 0]Bom Dia.[n][f 1 3 65535][w][e]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 171 65535 0]Eu tenho pensado muito em personas e[n]palácios desde ontem...[n][f 1 3 65535][w][e]

[msg MSG_151_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 172 65535 0]Esse banco flutuante realmente reflete a[n]personalidade de Kaneshiro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 173 65535 0]Ele está voando para que ninguém possa[n]rastrear seus passos... ele não confia em[n]ninguém.[n][f 1 3 65535][w][e]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 174 65535 0]Aposto que a segurança também está bem lá.[n][f 1 3 65535][w][e]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 175 65535 0]É por isso que devemos nos mover em breve.[n]Por que não vamos ao palácio hoje?[n][f 1 3 65535][w][e]

[sel SEL_152_0_0 top]
[s]Boa ideia.[f 2 7 0 1 971 1][e]
[s]Deixe-me pensar sobre isso.[e]

[msg MSG_153_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 176 65535 0]Excelente. Vou deixar minha agenda aberta[n]depois da escola, para que todos nós[n]devemos nos reunir.[n][f 1 3 65535][w][e]

[msg MSG_154_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 177 65535 0]Entendido. Tenho certeza de que você tem[n]seus motivos como líder.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 178 65535 0]Vou deixar minha agenda aberta depois da[n]escola, então fale comigo a qualquer[n]momento.[n][f 1 3 65535][w][e]

[msg MSG_155_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0]Whaddup![n][f 1 3 65535][w][e]

[msg MSG_156_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O que estamos fazendo hoje?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ainda temos tempo, mas não deveríamos[n]verificar a área ao redor do tesouro, pelo[n]menos?[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então, quer chegar ao palácio hoje?[n][f 1 3 65535][w][e]

[sel SEL_157_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Vou pensar sobre isso.[e]

[msg MSG_158_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7186 65535 0]Sim! Vamos aproveitar a chance de procurar[n]um monte de coisas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Este é um banco e tudo. Pode haver coisas[n]realmente ótimas lá que não estavam em[n]lugares anteriores.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, todos devemos nos reunir depois da[n]escola então. Não se esqueça.[n][f 1 3 65535][w][e]

[msg MSG_159_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0]Bem, vou deixar o tempo para você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas não decida tarde demais, cara.[n][f 1 3 65535][w][e]

[msg MSG_160_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0]Whaddup![n][f 1 3 65535][w][e]

[msg MSG_161_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, certo, já sabemos onde está o tesouro,[n]sim?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Qual é o plano? Quer enviar o cartão de[n]visita já?[n][f 1 3 65535][w][e]

[sel SEL_162_0_0 top]
[s]Vamos fazê-lo.[f 2 7 0 1 971 1][e]
[s]Eu não decidi.[e]

[msg MSG_163_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7103 65535 0]Ooh, estamos realizando o plano![n]Eu estou coçando por isso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tudo bem, vamos nos encontrar no local[n]habitual depois da escola. Eu estarei[n]esperando![n][f 1 3 65535][w][e]

[msg MSG_164_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7038 65535 0]Bem, ainda temos tempo. Deixe-me saber[n]quando terminar de se preparar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas não decida tarde demais, cara.[n][f 1 3 65535][w][e]

[msg MSG_165_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0]Whaddup![n][f 1 3 65535][w][e]

[msg MSG_166_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7192 65535 0]Ei, sobre o tesouro de Kaneshiro...[n]Não é meio decepcionante?[n][f 1 3 65535][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu pensei que o banco teria banheiras cheias[n]de bares de dinheiro ou ouro, sabe? Mas uma[n]pasta...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ugh... eu gostaria que houvesse algum lugar[n]em que eu pudesse encontrar um monte de[n]dinheiro...[n][f 1 3 65535][w][e]

[sel SEL_167_0_0 top]
[s]Por que você não consegue um emprego?[e]
[s]E quanto a lembranças?[e]

[msg MSG_168_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0]Um trabalho, hein... você tem um? Quero[n]dizer, é a maneira usual de ganhar dinheiro.[n][f 1 3 65535][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas isso não é do que os sonhos são feitos...[n]É muito comum![n][f 1 3 65535][w][e]

[msg MSG_169_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7137 65535 0]LEMENTOS, HUH... Acho que poderia obter[n]algum dinheiro com isso.[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Porém, não posso continuar sonhando com[n]isso, então é melhor você vir comigo e[n]fazer algum exercício.[n][f 1 3 65535][w][e]

[msg MSG_170_0_0 [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 6007 65535 0]É tão quente e úmido... Eu gostaria que a[n]estação chuvosa terminasse em breve.[n][f 1 3 65535][w][e]

[msg MSG_171_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A propósito, June está quase acabando.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não devemos começar a procurar o tesouro de[n]Kaneshiro?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, vamos ao palácio hoje.[n][f 1 3 65535][w][e]

[sel SEL_172_0_0 top]
[s]Vamos fazer isso.[f 2 7 0 1 971 1][e]
[s]Eu quero pensar mais nisso.[e]

[msg MSG_173_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6108 65535 0]Ok! Então, vamos ao palácio depois da escola![n][f 1 3 65535][w][e]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... Deus, é quente embora. O bom dos bancos[n]é que eles têm um bom AC.[n][f 1 3 65535][w][e]

[msg MSG_174_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6021 65535 0]Entendi. Entre em contato conosco se você[n]estiver indo.[n][f 1 3 65535][w][e]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... Deus, é quente embora. Seria ruim[n]sugerir esfriar em um banco?[n][f 1 3 65535][w][e]

[msg MSG_175_0_0 [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 6007 65535 0]É tão quente e úmido... Eu gostaria que a[n]estação chuvosa terminasse em breve.[n][f 1 3 65535][w][e]

[msg MSG_176_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A propósito, June está quase acabando.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sabemos onde está o tesouro agora.[n]O que você quer fazer?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Devemos enviar o cartão de visita hoje?[n][f 1 3 65535][w][e]

[sel SEL_177_0_0 top]
[s]Vamos enviar.[f 2 7 0 1 971 1][e]
[s]Vou pensar sobre isso.[e]

[msg MSG_178_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6108 65535 0]Ok! Este é o negócio real![n]Vamos fazer Kaneshiro implorar por[n]misericórdia![n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tudo bem, vejo você no lugar habitual depois[n]da escola. Não se esqueça.[n][f 1 3 65535][w][e]

[msg MSG_179_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6021 65535 0]Entendi. Vou deixar essa decisão para você, [n][f 4 2]. Ligue para nós quando você decidir.[n][f 1 3 65535][w][e]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... Deus, é quente embora. Seria ruim[n]sugerir esfriar em um banco?[n][f 1 3 65535][w][e]

[msg MSG_180_0_0 [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 6007 65535 0]É tão quente e úmido... Eu gostaria que a[n]estação chuvosa terminasse em breve.[n][f 1 3 65535][w][e]

[msg MSG_181_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A propósito, June está quase acabando.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Derrotamos Kaneshiro, para que possamos[n]descansar por um tempo... eu acho?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então, o que você quer fazer hoje?[n]Talvez algo como uma viagem a lembranças?[n][f 1 3 65535][w][e]

[sel SEL_182_0_0 top]
[s]Essa é uma boa ideia.[f 2 7 0 1 971 1][e]
[s]Eu quero descansar.[e]

[msg MSG_183_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6034 65535 0]Certo, também temos solicitações do quadro[n]de mensagens. Devemos responder a eles.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, vamos nos encontrar no esconderijo[n]depois da escola. Estarei esperando.[n][f 1 3 65535][w][e]

[msg MSG_184_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6021 65535 0]Quero dizer, os intervalos são importantes...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas temos esses pedidos no quadro de[n]mensagens, então não se esqueça de[n]respondê-los.[n][f 1 3 65535][w][e]

[msg MSG_185_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 53745 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_186_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4157 65535 0]Eu acredito que você não esqueceu, [f 4 2]?[n]O prazo de Kaneshiro é neste sábado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não podemos mais nos dar ao luxo de levar[n]nosso tempo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos ao palácio hoje. Devemos verificar o[n]paradeiro do tesouro imediatamente.[n][f 1 3 65535][w][e]

[sel SEL_187_0_0 top]
[s]Concordou.[f 2 7 0 1 971 1][e]
[s]Deixe-me pensar sobre isso.[e]

[msg MSG_188_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4088 65535 0]Estou feliz que você esteja rápido de pé.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não podemos permitir que Kaneshiro crie mais[n]vítimas.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, então, vamos nos reunir depois da[n]escola. Entre em contato comigo mais tarde.[n][f 1 3 65535][w][e]

[msg MSG_189_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0]Quero confiar no seu julgamento, mas podemos[n]não ter tempo suficiente no ritmo que[n]estamos indo.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Haverá repercussões terríveis para nós[n]também, se não o impedirmos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu posso ir a qualquer momento. Avise-me[n]quando estiver pronto.[n][f 1 3 65535][w][e]

[msg MSG_190_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4007 65535 0]Bom Dia. Está muito quente hoje...[n][f 1 3 65535][w][e]

[msg MSG_191_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4157 65535 0]Você se lembra? O prazo de Kaneshiro é neste[n]sábado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Já sabemos onde está o tesouro.[n]Podemos enviar o cartão de visita a qualquer[n]momento agora, e quanto a ele?[n][f 1 3 65535][w][e]

[sel SEL_192_0_0 top]
[s]Vamos enviar hoje.[f 2 7 0 1 971 1][e]
[s]Ainda estou nos preparativos.[e]

[msg MSG_193_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0]De fato, não há necessidade de ficar de[n]tempo.[n]Vamos mudar o coração de Kaneshiro hoje.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ligue-me novamente depois da escola então.[n]Todos nós enviaremos o cartão de visita[n]juntos.[n][f 1 3 65535][w][e]

[msg MSG_194_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 4026 65535 0]Não pretendo apressar você, mas lembre-se de[n]que não temos muito tempo.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ligue para nós quando estiver pronto.[n][f 1 3 65535][w][e]

[msg MSG_195_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4007 65535 0]Bom Dia. Está muito quente hoje...[n][f 1 3 65535][w][e]

[msg MSG_196_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A propósito, o prazo de Kaneshiro é neste[n]fim de semana, não é?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sua mudança de coração se aproxima...[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Os ladrões Phantom serão ainda mais[n]renomados do que antes, quando isso for[n]público.[n][f 1 3 65535][w][e]

[sel SEL_197_0_0 top]
[s]Mal posso esperar.[e]
[s]Vai ficar ocupado.[e]

[msg MSG_198_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0]Eu suponho. Não é uma sensação ruim ter seus[n]esforços reconhecidos.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aposto que também receberemos mais[n]solicitações nesse quadro de mensagens.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Acho que devemos cuidar de todos os casos[n]que temos agora, enquanto ainda temos a[n]chance.[n][f 1 3 65535][w][e]

[msg MSG_199_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4187 65535 0]Isso é verdade... com a atenção adicional,[n]podemos receber mais solicitações nesse[n]quadro de mensagens.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Acho que devemos cuidar de todos os casos[n]que temos agora, enquanto ainda temos a[n]chance.[n][f 1 3 65535][w][e]

[msg MSG_200_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2005 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_201_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2019 65535 0]Ei, você percebe que o prazo está a apenas[n]dois dias, não é?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As coisas vão acabar exatamente como[n]Kaneshiro quer se não fizermos algo. Temos[n]que roubar o tesouro, não importa o quê![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Temos que ir ao palácio hoje, tudo bem?[n][f 1 3 65535][w][e]

[sel SEL_202_0_0 top]
[s]É claro.[f 2 7 0 1 971 1][e]
[s]Ainda estamos bem.[e]

[msg MSG_203_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2059 65535 0]Que bom ouvir isso. Vamos nos certificar de[n]mudar o coração desse homem.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vejo você mais tarde então. Certifique-se de[n]não esquecer![n][f 1 3 65535][w][e]

[msg MSG_204_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2187 65535 0]Agora olhe aqui![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hoje é a nossa última chance, você entende[n]isso!? Esta não é a hora de estar sentado e[n]pensando![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Apenas... me avise quando estiver pronto.[n]Eu posso ir a qualquer momento.[n][f 1 3 65535][w][e]

[msg MSG_205_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 53343 65535 0]...Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_206_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2019 65535 0]Ei, temos apenas mais dois dias até o prazo.[n]Por quanto tempo vamos esperar?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você deve estar ciente de que estamos quase[n]sem tempo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Precisamos enviar o cartão de visita hoje,[n]entendeu isso?[n][f 1 3 65535][w][e]

[sel SEL_207_0_0 top]
[s]Vamos fazê-lo.[f 2 7 0 1 971 1][e]
[s]Deixe-me pensar sobre isso.[e]

[msg MSG_208_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2023 65535 0]Direita. Vamos dar um tapa nele com um aviso[n]final.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não podemos mais deixar que um criminoso[n]seja livre. Vamos nos reunir no esconderijo[n]depois da escola.[n][f 1 3 65535][w][e]

[msg MSG_209_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2046 65535 0]Agora olhe aqui![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O prazo de Kaneshiro é o 9! Não temos tempo[n]para ficar sentados pensando![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estamos enviando depois da escola hoje.[n]Estarei esperando.[n][f 1 3 65535][w][e]

[msg MSG_210_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 197 65535 0]Bom Dia. Está quente de novo hoje...[n][f 1 3 65535][w][e]

[msg MSG_211_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 198 65535 0]O prazo de Kaneshiro está se aproximando.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 199 65535 0]Fizemos tudo o que podíamos. Espero que[n]possamos evitar problemas agora...[n][f 1 3 65535][w][e]

[sel SEL_212_0_0 top]
[s]Estamos bem.[e]
[s]Você está preocupado?[e]

[msg MSG_213_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 200 65535 0]Como esperado de alguém que já passou por[n]isso três vezes.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 201 65535 0]Se você diz isso, então...[n]Sim, tenho certeza que vai bem.[n][f 1 3 65535][w][e]

[msg MSG_214_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 202 65535 0]Claro que sou. Palácios, mudando corações...[n]É difícil dizer o que é mais realidade...[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 203 65535 0]Ainda assim, a única coisa que posso fazer[n]agora é acreditar.[n][f 1 3 65535][w][e]

[msg MSG_215_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 258 65535 0]Whaddup! Cara, está tão quente hoje também...[n][f 1 3 65535][w][e]

[msg MSG_216_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 259 65535 0]Cara, e exatamente quando as aulas de verão[n]estúpidas e de Effin estavam acabando com...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 260 65535 0]Se não lidarmos com o caso de Futaba Sakura,[n]não teremos uma férias de verão de verdade.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 261 65535 0]É a pergunta que faz o chefe, não é?[n]Então, o que fazemos?[n][f 1 3 65535][w][e]

[sel SEL_217_0_0 top]
[s]Nós passamos.[e]
[s]Vamos perguntar por aí.[e]

[msg MSG_218_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 262 65535 0]Vamos lá... é muito cedo para desistir.[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 263 65535 0]Eu sei! Que tal perguntar aos vizinhos?[n]Talvez possamos descobrir algo sobre Boss e[n]Futaba.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 264 65535 0]E como eles são vizinhos, deixarei a[n]entrevista para você. Boa sorte, amigo.[n][f 1 3 65535][w][e]

[msg MSG_219_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 265 65535 0]Oh! Essa é uma ótima ideia![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 266 65535 0]Talvez os vizinhos saibam algo sobre Boss e[n]Futaba.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 267 65535 0]Ok, vou deixar a entrevista para você.[n]Boa sorte, amigo.[n][f 1 3 65535][w][e]

[msg MSG_220_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 315 65535 0]Ah, bom dia.[n][f 1 3 65535][w][e]

[msg MSG_221_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 316 65535 0]Er... hum... estou ansioso para trabalhar[n]com você a partir de hoje![n][f 1 3 65535][w][e]

[sel SEL_222_0_0 top]
[s]Mesmo aqui.[e]
[s]Você está muito ansioso.[e]

[msg MSG_223_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 317 65535 0]Vou confiar em você, como meu senpai e como[n]um ladrão fantasma.[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 318 65535 0]Estou pronto para ter o que meu pai fez[n]tornou público...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 319 65535 0]Então, vamos trabalhar duro juntos![n][f 1 3 65535][w][e]
[s][f 1 5]Morgana [n][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 22 0 5 23][vp 8 0 0 320 65535 0]Só podemos lutar ao lado de Haru até o[n]prazo, o 10.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 321 65535 0]Se Okumura está vendendo sua filha, eu não[n]colocaria nada além dele...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 322 65535 0]De qualquer forma, não podemos vencer esse[n]palácio sem Haru. Pode ser difícil para[n]ela, mas deve ser feito![n][f 1 3 65535][w][e]

[msg MSG_224_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 323 65535 0]Desculpe... acho que ainda tenho muito a[n]aprender como um ladrão fantasma.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 324 65535 0][bup 0 7 0 65535 0][f 4 10 65535 0 0]No entanto, decidi que o que meu pai está[n]fazendo deveria ser tornado público.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 325 65535 0]Então, vamos trabalhar duro juntos![n][f 1 3 65535][w][e]
[s][f 1 5]Morgana [n][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 22 0 5 23][vp 8 0 0 326 65535 0]Só podemos lutar ao lado de Haru até o[n]prazo, o 10.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 327 65535 0]Se Okumura está vendendo sua filha, eu não[n]colocaria nada além dele...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 328 65535 0]De qualquer forma, não podemos vencer esse[n]palácio sem Haru. Pode ser difícil para[n]ela, mas deve ser feito![n][f 1 3 65535][w][e]

[msg MSG_225_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2005 65535 0]Bom Dia. Como você está se sentindo?[n][f 1 3 65535][w][e]

[msg MSG_226_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Um banco, uma pirâmide e agora um[n]espaçoporto...[n]Tudo vai no mundo cognitivo, suponho.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De qualquer forma, isso é em uma escala[n]maior do que antes, então teremos que fazer[n]algumas pesquisas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Devemos nos mover em breve. Por que não[n]vamos ao palácio hoje?[n][f 1 3 65535][w][e]

[sel SEL_227_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Vou pensar sobre isso.[e]

[msg MSG_228_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2035 65535 0]Entendido. Não podemos perder isso, pelo bem[n]de Haru.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ok, vejo você depois da escola no[n]esconderijo. Não se esqueça.[n][f 1 3 65535][w][e]

[msg MSG_229_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2026 65535 0]Não vou empurrar você, mas não se esqueça de[n]Haru.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Fale comigo a qualquer momento, se você for.[n]Vou ter certeza de que estou pronto.[n][f 1 3 65535][w][e]

[msg MSG_230_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2005 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_231_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2195 65535 0]Ei, você decidiu o que está fazendo com o[n]cartão de visita? Quando vai enviar?[n][f 1 3 65535][w][e]

[sel SEL_232_0_0 top]
[s]Vamos enviar hoje.[f 2 7 0 1 971 1][e]
[s]Eu não decidi.[e]

[msg MSG_233_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2090 65535 0]Esse é um bom plano. Devemos agir[n]rapidamente, pelo bem de Haru também.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, vamos reunir todos.[n]Estarei esperando no esconderijo.[n][f 1 3 65535][w][e]

[msg MSG_234_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2197 65535 0]Haru has to go see her fiancé.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Verdadeiro. Ainda temos algum tempo antes de[n]começarmos a chamar a atenção, então talvez[n]devêssemos ser mais cautelosos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, deixe-me saber quando terminar os[n]preparativos. Vou ter certeza de estar[n]pronto a qualquer momento.[n][f 1 3 65535][w][e]

[msg MSG_235_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2005 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_236_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O palácio se foi, então acho que estamos[n]esperando por um tempo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O que vocês fazem em momentos como esses?[n][f 1 3 65535][w][e]

[sel SEL_237_0_0 top]
[s]Dar um tempo.[e]
[s]Estudar.[e]

[msg MSG_238_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2135 65535 0]Entendo... suponho que fará com que seja[n]bom, de vez em quando.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ainda assim, não exagere. Você não pode[n]esquecer seus deveres primários como[n]estudante do ensino médio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]É importante fazer o papel de um aluno[n]diligente, certo?[n][f 1 3 65535][w][e]

[msg MSG_239_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, você está dizendo que também é[n]importante desempenhar o papel de um aluno[n]diligente?[n][f 1 3 65535][w][e]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2048 65535 0]Estou impressionado. Eu gostaria que Ryuji[n]tivesse uma sugestão de você...[n][f 1 3 65535][w][e]

[msg MSG_240_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0]Morniiin '![n][f 1 3 65535][w][e]

[msg MSG_241_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, você está continuando com comentários[n]online?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Há muito ódio por Okumura e muitas[n]expectativas para nós.[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Seria melhor fazer isso o mais rápido[n]possível. Por que não vamos ao palácio hoje?[n][f 1 3 65535][w][e]

[sel SEL_242_0_0 top]
[s]Vamos fazer isso.[f 2 7 0 1 971 1][e]
[s]Não fique impaciente.[e]

[msg MSG_243_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7082 65535 0]Doce, está decidido![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Temos que mostrar a eles o poder dos ladrões[n]fantasmas. Vou esperar o esconderijo com[n]tudo o que tenho![n][f 1 3 65535][w][e]

[msg MSG_244_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7111 65535 0]Você realmente só vai no seu próprio ritmo,[n]não Cha...?[n][f 1 3 65535][w][e]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esta é a nossa chance de mostrar o poder dos[n]ladrões fantasmas. Não procrastine demais,[n]cara.[n][f 1 3 65535][w][e]

[msg MSG_245_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0]Morniiin '![n][f 1 3 65535][w][e]

[msg MSG_246_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, você está continuando com comentários[n]online?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Há muito ódio por Okumura e muitas[n]expectativas para nós.[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Seria melhor fazer isso o mais rápido[n]possível. Vamos enviar o cartão de visita[n]em breve.[n][f 1 3 65535][w][e]

[sel SEL_247_0_0 top]
[s]Vamos enviar agora.[f 2 7 0 1 971 1][e]
[s]Ainda não.[e]

[msg MSG_248_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7153 65535 0]Ah sim, doce! Vamos mostrar a eles o poder[n]dos ladrões fantasmas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos nos reunir depois das aulas.[n]Esta será uma declaração de guerra para[n]aquele CEO corrupto![n][f 1 3 65535][w][e]

[msg MSG_249_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7111 65535 0]Você realmente só vai no seu próprio ritmo,[n]não Cha...?[n][f 1 3 65535][w][e]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esta é a nossa chance de mostrar o poder dos[n]ladrões fantasmas. Não procrastine demais,[n]cara.[n][f 1 3 65535][w][e]

[msg MSG_250_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0]Morniiin '![n][f 1 3 65535][w][e]

[msg MSG_251_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, você está continuando com comentários[n]online?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Há muito ódio por Okumura e muitas[n]expectativas para nós.[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Espero que o pai de Haru mude de coração em[n]breve.[n][f 1 3 65535][w][e]

[sel SEL_252_0_0 top]
[s]Eles têm grandes esperanças para nós.[e]
[s]Tudo o que podemos fazer é esperar.[e]

[msg MSG_253_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7048 65535 0]Eu sei! Não é incrível!? Este será um grande[n]alvoroço novamente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Como sempre, vai demorar um pouco antes de[n]vermos alguns resultados, mas Maaan, estou[n]tão ansioso para isso.[n][f 1 3 65535][w][e]

[msg MSG_254_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7037 65535 0]Sim, você tem um ponto... mas tenho certeza[n]de que isso causará um impacto maior do que[n]antes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Como sempre, vai demorar um pouco antes de[n]vermos alguns resultados, mas Maaan, estou[n]tão ansioso para isso.[n][f 1 3 65535][w][e]

[msg MSG_255_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 329 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_256_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 330 65535 0]É apenas uma semana até o dia em que meu pai[n]prometeu...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 331 65535 0]Eu quero mudar seu coração até então, não[n]importa o quê. Não quero que ele continue[n]cometendo erros.[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 332 65535 0]É por isso que quero ir ao palácio hoje. Que[n]tal isso, [n][f 4 2]-kun?[n][f 1 3 65535][w][e]

[sel SEL_257_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Deixe-me pensar sobre isso.[e]

[msg MSG_258_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 333 65535 0]Obrigado![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 334 65535 0]Tenho certeza de que posso fazer isso com[n]todos ao meu lado. Vou esperar por você[n]depois da escola em LeBlanc.[n][f 1 3 65535][w][e]

[msg MSG_259_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 335 65535 0]Tudo bem. Avise-me depois de decidir.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 336 65535 0]Vou trabalhar duro também, então vamos[n]tentar fazer isso até o prazo.[n][f 1 3 65535][w][e]

[msg MSG_260_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 337 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_261_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 338 65535 0]É apenas uma semana até o dia em que meu pai[n]prometeu...[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 339 65535 0]Então agora nós apenas enviamos o cartão de[n]visita, certo? Quando será isso?[n][f 1 3 65535][w][e]

[sel SEL_262_0_0 top]
[s]Vamos enviar hoje.[f 2 7 0 1 971 1][e]
[s]Eu ainda não decidi.[e]

[msg MSG_263_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 340 65535 0]O que? Hoje!?[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 341 65535 0]OK. Todos nós devemos nos encontrar depois[n]da escola.[n]Ansioso por isso.[n][f 1 3 65535][w][e]

[msg MSG_264_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 342 65535 0]Eu vejo. Avise-me quando você decidir.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 343 65535 0]Vou trabalhar duro também, então vamos[n]tentar fazer algo sobre isso até o prazo.[n]Por favor, não se esqueça.[n][f 1 3 65535][w][e]

[msg MSG_265_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 344 65535 0]Ah, bom dia.[n][f 1 3 65535][w][e]

[msg MSG_266_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 345 65535 0]Em relação ao meu pai... ainda não há nada[n]diferente nele.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 346 65535 0]Não posso deixar de pensar em muitas coisas[n]quando estou apenas esperando. Coisas como,[n]foi bem...?[n][f 1 3 65535][w][e]

[sel SEL_267_0_0 top]
[s]Não precisa se preocupar.[e]
[s]Relaxar.[e]

[msg MSG_268_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 347 65535 0]Obrigado. Ouvir isso de você deixa minha[n]mente à vontade.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 348 65535 0]*risada* Acho que vou relaxar e cuidar do[n]canteiro de flores. Não consegui há um[n]tempo.[n][f 1 3 65535][w][e]

[msg MSG_269_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 349 65535 0]Obrigado. Eu sei que não adianta ficar[n]ansioso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 350 65535 0]*risada* Acho que vou relaxar e cuidar do[n]canteiro de flores. Não consegui há um[n]tempo.[n][f 1 3 65535][w][e]

[msg MSG_270_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 6022 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_271_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, não é quase a hora?[n]O prazo é o 10.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se não fizermos algo até então, Haru será[n]levado embora.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos para o palácio, ok?[n][f 1 3 65535][w][e]

[sel SEL_272_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Estou pensando sobre isso.[e]

[msg MSG_273_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6023 65535 0]Sim, temos que nos apressar.[n]Tenho certeza que Haru também está[n]preocupado.[n][f 1 3 65535][w][e]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Temos que parar isso, não importa o quê![n]Vamos nos encontrar depois da escola.[n][f 1 3 65535][w][e]

[msg MSG_274_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 6140 65535 0]Vamos nos mover! Nesse ritmo, Haru será dado[n]a esse homem...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não podemos deixar isso acontecer! Vamos[n]mudar o coração de seu pai o mais rápido[n]possível, ok?[n][f 1 3 65535][w][e]

[msg MSG_275_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6155 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_276_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O prazo está quase aqui.[n]Vamos ficar bem?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Temos que enviar o cartão de visita o mais[n]rápido possível. Vamos enviar em breve,[n]certo?[n][f 1 3 65535][w][e]

[sel SEL_277_0_0 top]
[s]Vamos enviar imediatamente.[f 2 7 0 1 971 1][e]
[s]Estou pensando sobre isso.[e]

[msg MSG_278_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6020 65535 0]Ok, entendi![n][f 1 3 65535][w][e]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não vou dar Haru a um homem assim.[n]Temos que parar isso, não importa o quê![n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, vejo você na LeBlanc depois da escola[n]então. Eu estarei lá logo depois.[n][f 1 3 65535][w][e]

[msg MSG_279_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6027 65535 0]Deixamos o momento para você, mas Haru será[n]levado por esse cara se não nos[n]apressarmos...[n][f 1 3 65535][w][e]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não podemos permitir isso! Vamos resolver[n]isso o mais rápido possível, ok?[n][f 1 3 65535][w][e]

[msg MSG_280_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6005 65535 0]Oh, bom dia.[n][f 1 3 65535][w][e]

[msg MSG_281_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O dia em que Haru vai ser enviado está quase[n]aqui...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pegamos o tesouro, então tudo o que[n]precisamos fazer é esperar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ainda assim, eu gostaria que pudéssemos[n]fazer algo enquanto isso. Por que não vamos[n]para lembranças hoje?[n][f 1 3 65535][w][e]

[sel SEL_282_0_0 top]
[s]Vamos fazer isso.[f 2 7 0 1 971 1][e]
[s]Eu não sinto vontade.[e]

[msg MSG_283_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6108 65535 0]Excelente! Eu quero fazer essas coisas[n]quando pudermos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se o presidente tiver uma mudança de[n]coração, talvez nossa reputação suba e[n]teremos mais pedidos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, vamos nos encontrar depois da escola[n]então. Vejo você lá![n][f 1 3 65535][w][e]

[msg MSG_284_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6194 65535 0]Você tem mais algo para fazer?[n]Bem, eu não vou forçar você.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se o presidente tiver uma mudança de[n]coração, talvez nossa reputação suba e[n]teremos mais pedidos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então, eu quero obter as solicitações que[n]atualmente temos do caminho, pelo menos.[n][f 1 3 65535][w][e]

[msg MSG_285_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 351 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_286_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 352 65535 0]Minha irmã é... séria. Sua determinação em[n]vencer essa luta se reflete nesse cassino.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 353 65535 0]Ela não será fácil de vencer. Eu sei disso[n]melhor do que ninguém.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 354 65535 0]Eu quero entender nossa situação o mais[n]rápido possível. Vamos ao palácio hoje.[n][f 1 3 65535][w][e]

[sel SEL_287_0_0 top]
[s]Essa é uma boa ideia.[f 2 7 0 1 971 1][e]
[s]Acalmar.[e]

[msg MSG_288_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 355 65535 0]Você realmente é confiável.[n][f 1 3 65535][w][e]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 356 65535 0]De acordo com Akechi-kun, a investigação[n]está no dia 20. Vamos detê-la, não importa[n]o quê.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 357 65535 0]Tudo bem então, vejo você no esconderijo[n]depois da escola. Vou informar a todos[n]também.[n][f 1 3 65535][w][e]

[msg MSG_289_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 358 65535 0]Desculpe. Talvez eu esteja ficando um pouco[n]alto demais.[n][f 1 3 65535][w][e]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 359 65535 0]Mas não suporto ver minha irmã assim.[n]Vamos detê-la, não importa o quê.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 360 65535 0]Se você está indo por acaso, me avise. Vou[n]garantir que estou pronto a qualquer[n]momento.[n][f 1 3 65535][w][e]

[msg MSG_290_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3001 65535 0]Bom Dia, [f 4 2]-kun, Mona-chan.[n][f 1 3 65535][w][e]

[msg MSG_291_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3018 65535 0]Os ladrões Phantom estão em todos os jornais[n]e televisão. Somos bandidos agora.[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Temos que limpar nosso nome, para meu pai[n]também.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então, eu gostaria de fazer algum progresso.[n]Por que não vamos ao palácio hoje?[n][f 1 3 65535][w][e]

[sel SEL_292_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Não há necessidade de ficar impaciente.[e]

[msg MSG_293_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3020 65535 0]Obrigada.[n][f 1 3 65535][w][e]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ouça, acho que Mako-chan está tendo um[n]momento difícil, já que alguém próximo a[n]ela é o alvo.[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Espero que possamos ajudá-la em breve. Bem,[n]vejo você depois da escola em LeBlanc.[n][f 1 3 65535][w][e]

[msg MSG_294_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3194 65535 0]Sinto muito por apressar você.[n]Estou apenas preocupado com Mako-chan.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Há muito o que pensar quando o alvo é alguém[n]próximo a você.[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De qualquer forma, espero que corra bem.[n]Vamos dar tudo isso.[n][f 1 3 65535][w][e]

[msg MSG_295_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3001 65535 0]Bom Dia, [f 4 2]-kun, Mona-chan.[n][f 1 3 65535][w][e]

[msg MSG_296_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3021 65535 0]Os ladrões Phantom estão em todos os jornais[n]e televisão. Somos bandidos agora.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estamos no momento em que podemos enviar um[n]cartão de visita, mas isso me deixa ansioso[n]para me sentar e esperar.[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E você, [f 4 2]-kun?[n][f 1 3 65535][w][e]

[sel SEL_297_0_0 top]
[s]Isso me deixa afetável também.[e]
[s]Isso não me incomoda.[e]

[msg MSG_298_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3020 65535 0]Ah, então somos iguais.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Paradas como essas me fazem pensar em muitas[n]coisas, ainda mais, já que não podemos nos[n]dar ao luxo de falhar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então, estamos enviando o cartão no dia 18...[n]Está a um caminho, mas eu gostaria de gastar[n]nesses dias com sabedoria.[n][f 1 3 65535][w][e]

[msg MSG_299_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3020 65535 0]*risada* Eu não deveria ter esperado nada[n]menos de você, líder.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Paradas como essas me fazem pensar em muitas[n]coisas, ainda mais, já que não podemos nos[n]dar ao luxo de falhar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então, estamos enviando o cartão no dia 18...[n]Está a um caminho, mas eu gostaria de gastar[n]nesses dias com sabedoria.[n][f 1 3 65535][w][e]

[msg MSG_300_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4006 65535 0]Ei.[n][f 1 3 65535][w][e]

[msg MSG_301_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4157 65535 0]Quais são seus planos depois da escola?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nosso prazo está se aproximando. Por que não[n]vamos ao palácio hoje?[n][f 1 3 65535][w][e]

[sel SEL_302_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Ainda não.[e]

[msg MSG_303_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0]De fato. Devemos mudar o coração do promotor[n]Niijima, para que ela possa virar os olhos[n]para o verdadeiro culpado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vou para o esconderijo depois da escola[n]então. Estou contando com você.[n][f 1 3 65535][w][e]

[msg MSG_304_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 4026 65535 0]Eu vejo. Eu não vou pressionar você...[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No entanto, nosso oponente também é sério.[n]Nós temos que fazer alguma coisa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não podemos falhar, não importa o quê.[n]Por favor, tenha isso em mente.[n][f 1 3 65535][w][e]

[msg MSG_305_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4006 65535 0]Ei.[n][f 1 3 65535][w][e]

[msg MSG_306_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Enviaremos o cartão de visita no dia 18,[n]daqui a dez dias. Você gostaria de fazer[n]alguma coisa antes disso?[n][f 1 3 65535][w][e]

[sel SEL_307_0_0 top]
[s]Eu quero treinar.[e]
[s]Eu quero jogar.[e]

[msg MSG_308_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4090 65535 0]Eu vejo. Você é bastante disciplinado.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se você precisar de nós, convoce-nos.[n]Eu estarei lá imediatamente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nossa existência depende dessa estratégia.[n]Vamos fazer tudo o que podemos.[n][f 1 3 65535][w][e]

[msg MSG_309_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]Entendo... você mantém sua compostura.[n]Suponho que você é feito de coisas mais[n]severas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Muito bem.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nossa existência depende dessa estratégia.[n]Vamos fazer tudo o que podemos.[n][f 1 3 65535][w][e]

[msg MSG_310_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6002 65535 0]Heeey.[n][f 1 3 65535][w][e]

[msg MSG_311_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Já é o 12. Temos cerca de uma semana até a[n]investigação.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Podemos fazê-lo para que possamos enviar o[n]cartão de visita? Vamos ao palácio hoje![n][f 1 3 65535][w][e]

[sel SEL_312_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Deixe-me pensar sobre isso.[e]

[msg MSG_313_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6034 65535 0]Sim, vamos nos apressar![n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não quero ser preso por uma acusação falsa.[n]Afinal, quero encontrar o verdadeiro[n]culpado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Todos devemos fazer o que pudermos.[n]Vamos nos encontrar depois da escola no[n]esconderijo.[n][f 1 3 65535][w][e]

[msg MSG_314_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6021 65535 0]Tenho certeza que você tem um plano. Você é[n]você, afinal.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não quero ser preso por uma acusação falsa.[n]Afinal, quero encontrar o verdadeiro[n]culpado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Avise-me quando você decidir ir.[n]Estarei esperando ouvir de você.[n][f 1 3 65535][w][e]

[msg MSG_315_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6002 65535 0]Heeey.[n][f 1 3 65535][w][e]

[msg MSG_316_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estamos enviando o cartão de visita no dia[n]18, então temos menos de uma semana[n]restante agora.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 6028 65535 0]*suspiro* Estou ficando nervoso.[n][f 1 3 65535][w][e]

[sel SEL_317_0_0 top]
[s]Eu sei como você se sente.[e]
[s]Vai ficar bem.[e]

[msg MSG_318_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 6040 65535 0]Você também, [f 4 2]?[n]Isso é surpreendente...[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ainda assim, desta vez é diferente do[n]habitual, tendo uma data definida para[n]enviar o cartão de visita e tudo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esta missão determinará nosso destino.[n]Temos que ter sucesso, não importa o quê.[n][f 1 3 65535][w][e]

[msg MSG_319_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6088 65535 0]Eu sabia que você diria isso.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... você é tão forte, [f 4 2].[n]Eu tenho que ser mais como você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esta missão determinará nosso destino.[n]Temos que ter sucesso, não importa o quê.[n][f 1 3 65535][w][e]

[msg MSG_320_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7001 65535 0]Ei, eu estive esperando por você, [n][f 4 2]. Você sabe o que estou indo, certo?[n][f 1 3 65535][w][e]

[msg MSG_321_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A investigação é no dia 20. Não temos muito[n]tempo, pois ainda precisamos enviar o[n]cartão de visita.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então, vamos ao palácio hoje! Você concorda[n]comigo, sim?[n][f 1 3 65535][w][e]

[sel SEL_322_0_0 top]
[s]Claro, por que não.[f 2 7 0 1 971 1][e]
[s]Vou decidir mais tarde.[e]

[msg MSG_323_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]Por que a atitude alto e poderoso?[n]Er, acho que tudo bem se estamos indo...[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Isso não é brincadeira, cara. Se não[n]pararmos a irmã de Makoto, será o fim de[n]nós.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos direto para o esconderijo depois da[n]escola. Vou fazer alguns aquecimentos[n]enquanto espero por você.[n][f 1 3 65535][w][e]

[msg MSG_324_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 7026 65535 0]Não há "mais tarde". O prazo está tão perto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se não pararmos Sae-san logo, será o fim de[n]nós.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos hoje. Tome uma decisão e depois entre[n]em contato comigo, ok?[n][f 1 3 65535][w][e]

[msg MSG_325_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7001 65535 0]Ei, eu estive esperando por você, [n][f 4 2]. Você sabe o que estou indo, certo?[n][f 1 3 65535][w][e]

[msg MSG_326_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Enviamos o cartão de visita no dia 18 e[n]depois realizamos o plano no dia seguinte.[n][f 1 3 65535][w][e]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... você está pronto, não é?[n][f 1 3 65535][w][e]

[sel SEL_327_0_0 top]
[s]Eu estive pronto.[e]
[s]Você está?[e]

[msg MSG_328_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Acho que nem precisei perguntar. Você é[n]confiável, mas não se esqueça de uma[n]coisa...[n][f 1 3 65535][w][e]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos não ter arrependimentos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esta é a nossa situação de fazer ou morrer.[n]Não temos a opção de falhar![n][f 1 3 65535][w][e]

[msg MSG_329_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0]Na verdade, estou tão preocupado que tenho[n]perdido o sono...[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Apenas Kiddin '.[n][f 1 3 65535][w][e]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas não se esqueça: não vamos nos arrepender.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esta é a nossa situação de fazer ou morrer.[n]Não temos a opção de falhar![n][f 1 3 65535][w][e]

[msg MSG_330_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 361 65535 0]*Bocejo* Mornin '...[n][f 1 3 65535][w][e]

[msg MSG_331_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 362 65535 0]São exames...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 363 65535 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 364 65535 0]Somos os heróis que salvaram este país,[n]certo? Não podemos estar isentos de exames?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 365 65535 0]E sou só eu, ou não temos um senso de[n]realização tão grande quanto eu pensava?[n][f 1 3 65535][w][e]

[sel SEL_332_0_0 top]
[s]A resposta pública foi péssima.[e]
[s]É por causa dos exames.[e]

[msg MSG_333_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 366 65535 0]É isso! As pessoas são tão duvidosas mesmo[n]após a conferência de imprensa.[n][f 1 3 65535][w][e]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 367 65535 0]Ele não foi preso, então acho que é[n]esperado... Temos que deixar isso para a[n]irmã de Makoto agora.[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 368 65535 0]Cara, eu gostaria que os exames[n]desaparecessem magicamente quando chegarmos[n]à escola![n][f 1 3 65535][w][e]

[msg MSG_334_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 369 65535 0]Eu diria que os exames são 80% disso, mas[n]não é isso que quero dizer...[n][f 1 3 65535][w][e]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 370 65535 0]Quero dizer as reações da sociedade. Eles[n]ainda são tão duvidosos mesmo após a[n]conferência de imprensa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 371 65535 0]Ele não foi preso, então acho que é[n]esperado... Temos que deixar isso para a[n]irmã de Makoto agora.[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 372 65535 0]Cara, eu gostaria que os exames[n]desaparecessem magicamente quando chegarmos[n]à escola![n][f 1 3 65535][w][e]

[msg MSG_335_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 373 65535 0]Ah, bom dia.[n][f 1 3 65535][w][e]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 374 65535 0]Exames hoje também, hein...[n][f 1 3 65535][w][e]

[msg MSG_336_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 375 65535 0]Finalmente derrotamos Shido, mas ainda temos[n]finais... essas batalhas não são uma após a[n]outra difícil?[n][f 1 3 65535][w][e]

[sel SEL_337_0_0 top]
[s]Eles são fáceis.[e]
[s]Eles são mais difíceis que Shido.[e]

[msg MSG_338_0_0 [Ann]]
[s][bup 0 4 12 65535 0][f 4 10 65535 0 0][vp 8 0 0 376 65535 0]Esse é o nosso líder, concluindo os exames e[n]mudando de coração com facilidade, hein?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 377 65535 0]Bem, os exames não são nada comparados a[n]Shido![n][f 1 3 65535][w][e]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 378 65535 0]*suspirar* [n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 379 65535 0]Talvez seja porque os exames ainda não[n]terminaram, mas sinto que não posso ficar[n]muito animado...[n][f 1 3 65535][w][e]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 380 65535 0]Ah, mas só temos mais dois dias, inclusive[n]hoje! Espere lá, eu![n][f 1 3 65535][w][e]

[msg MSG_339_0_0 [Ann]]
[s][bup 0 4 14 65535 0][f 4 10 65535 0 0][vp 8 0 0 381 65535 0]O que- Como você está!? Lidar com seus[n]exames como você faz suas mudanças de[n]coração...[n][f 1 3 65535][w][e]
[s][bup 0 4 12 65535 0][f 4 10 65535 0 0][vp 8 0 0 382 65535 0]De qualquer forma, os exames não são nada[n]comparados a Shido![n][f 1 3 65535][w][e]
[s][vp 8 0 0 383 65535 0][bup 0 4 3 65535 0][f 4 10 65535 0 0]*suspirar* [n][f 1 3 65535][w][e]
[s][vp 8 0 0 384 65535 0][f 4 10 65535 0 0]Talvez seja porque os exames ainda não[n]terminaram, mas sinto que não posso ficar[n]muito animado...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 385 65535 0][bup 0 4 1 65535 0][f 4 10 65535 0 0]Ah, mas só temos mais dois dias, inclusive[n]hoje! Espere lá, eu![n][f 1 3 65535][w][e]

[msg MSG_340_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 386 65535 0]Hoje é o último dia de exames. As coisas[n]estão indo bem para você?[n][f 1 3 65535][w][e]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 387 65535 0]Estou fazendo o mesmo que de costume.[n]Bem, sem problemas.[n][f 1 3 65535][w][e]

[msg MSG_341_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 388 65535 0]Estou bem com isso, mas minha irmã não[n]voltou para casa nos últimos dias.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 389 65535 0]Eu acho que ela tem muito no prato da[n]construção de um caso contra Shido...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 390 65535 0][bup 0 6 0 65535 0][f 4 10 65535 0 0]Ele tem conexões com pessoas poderosas.[n]Tenho certeza de que eles querem que ele[n]seja liberado para salvar suas próprias[n]peles.[n][f 1 3 65535][w][e]

[sel SEL_342_0_0 top]
[s]Isso é preocupante.[e]
[s]Sua irmã tem isso.[e]

[msg MSG_343_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 391 65535 0]Sim...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 392 65535 0]Ainda assim, Shido já confessou. Esse é um[n]fato indiscutível.[n][f 1 3 65535][w][e]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 393 65535 0]E é minha irmã. Ela verá isso, tenho certeza.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 394 65535 0]... Com isso dito, agora não é a hora de nos[n]afastarmos.[n][f 1 3 65535][w][e]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 395 65535 0]Você se lembra do que os exames vão cobrir?[n]Vou verificar o trem para você.[n][f 1 3 65535][w][e]

[msg MSG_344_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 396 65535 0]Sim, eu acredito também.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 397 65535 0]E é minha irmã. Ela verá isso, tenho certeza.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 398 65535 0]... Com isso dito, agora não é a hora de nos[n]afastarmos.[n][f 1 3 65535][w][e]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 399 65535 0]Você se lembra do que os exames vão cobrir?[n]Vou verificar o trem para você.[n][f 1 3 65535][w][e]

[msg MSG_345_0_0 [Ryuji]]
[s][bup 0 2 1 2 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0]Morniiin '![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A resposta à conferência de imprensa de[n]Madarame foi enorme! Todo mundo está[n]falando sobre o cartão de visita.[n][f 1 3 65535][w][e]

[msg MSG_346_0_0 [Ryuji]]
[s][bup 0 2 1 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As meninas estão me checando hoje...[n]Talvez eles não possam deixar de sentir meu[n]carisma de ladrão fantasma transbordante?[n][f 1 3 65535][w][e]
[s][bup 0 2 4 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh merda, estou finalmente começando a ser[n]popular com toda a mosca, querida... oh não![n][f 1 3 65535][w][e]

[sel SEL_347_0_0 top]
[s]O que está errado?[e]
[s]Algo é estranho...[e]

[msg MSG_348_0_0 [Ryuji]]
[s][bup 0 2 5 2 0][f 4 10 65535 0 0][vp 8 2 0 7039 65535 0]O que está errado!? Meu uniforme, cara! Isso[n]é o que! Estamos nos esforçando para mudar[n]para uniformes de verão hoje![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu sabia que as pessoas estavam olhando para[n]mim... Oh, maldito![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu tenho que ir para casa e mudar, então[n]você continua à frente![n][f 1 3 65535][w][e]

[msg MSG_349_0_0 [Ryuji]]
[s][bup 0 2 5 2 0][f 4 10 65535 0 0][vp 8 2 0 7039 65535 0]Claro que existe! Meu uniforme, cara![n]Meu uniforme! Estamos nos esforçando para[n]mudar para uniformes de verão hoje![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu sabia que as pessoas estavam olhando para[n]mim... Oh, maldito![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu tenho que ir para casa e mudar, então[n]você continua à frente![n][f 1 3 65535][w][e]

[msg MSG_350_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 400 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_351_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][vp 8 0 0 401 65535 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 402 65535 0]Finalmente chegou a hora. Você acha que vai[n]correr bem?[n][f 1 3 65535][w][e]

[sel SEL_352_0_0 top]
[s]Tem que ser.[e]
[s]Não sei.[e]

[msg MSG_353_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 403 65535 0]Direita. É algo que só podemos fazer.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 404 65535 0]Vejo você no lugar habitual depois da escola.[n]Vou dizer a todos para vir.[n][f 1 3 65535][w][e]

[msg MSG_354_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 405 65535 0]Eu vejo... ainda estou pronto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 406 65535 0]Vejo você no lugar habitual depois da escola.[n]Vou dizer a todos para vir.[n][f 1 3 65535][w][e]

[msg MSG_355_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 76 65535 0]Então é você. Você usou essa linha antes,[n]agora que penso nisso...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 77 65535 0][bup 0 5 2 65535 0][f 4 10 65535 0 0]...Espero que entenda.[n][f 1 3 65535][w][e]

[msg MSG_356_0_0 [Yusuke]]
[s][vp 8 0 0 78 65535 0][bup 0 5 2 65535 0][f 4 10 65535 0 0]Permita-me avisá-lo novamente. Não se[n]envolva mais.[n][f 1 3 65535][w][e]

[sel SEL_357_0_0 top]
[s]Porque?[e]
[s]Esperando por mim, você está?[e]

[msg MSG_358_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 79 65535 0]Não jogue idiota. Estou dizendo que você é[n]um inconveniente.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 80 65535 0][f 4 10 65535 0 0]Não vou te perdoar se você continuar[n]zombando do meu sensei.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 81 65535 0][f 4 10 65535 0 0]Estou limpo? Este é um aviso.[n][f 1 3 65535][w][e]

[msg MSG_359_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 82 65535 0]Eu só te vi coincidentemente. Não tenho[n]tempo para uma emboscada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 83 65535 0][f 4 10 65535 0 0]Se você continuar cheirando meu sensei...[n]Temos maneiras de lidar com isso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 84 65535 0][f 4 10 65535 0 0]Isso é tudo o que tenho a dizer.[n][f 1 3 65535][w][e]

[msg MSG_360_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 85 65535 0]Então é você. Você usou esta linha, agora[n]que penso nisso...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 86 65535 0][bup 0 5 2 65535 0][f 4 10 65535 0 0]De qualquer forma, o que há com essa mudança[n]repentina de atitude?[n][f 1 3 65535][w][e]

[msg MSG_361_0_0 [Yusuke]]
[s][vp 8 0 0 87 65535 0][bup 0 5 2 65535 0][f 4 10 65535 0 0]Fui contactado por Takamaki-san ontem à[n]noite. Ela aceitou a proposta de modelagem[n]nua.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 88 65535 0][f 4 10 65535 0 0]Isso é bom, é claro... mas espero que você[n]não esteja conspirando nada.[n][f 1 3 65535][w][e]

[sel SEL_362_0_0 top]
[s]Nós não sonharíamos com isso.[e]
[s]Eu poderia dizer o mesmo de você.[e]

[msg MSG_363_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 89 65535 0]Não entendo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 90 65535 0][f 4 10 65535 0 0]No entanto, chamarei a polícia se você[n]tentar alguma coisa. Lembre-se disso.[n][f 1 3 65535][w][e]

[msg MSG_364_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 91 65535 0]Não zombe da arte. Não nos julgue pelos seus[n]padrões mundanos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 92 65535 0][f 4 10 65535 0 0]Vou ligar para a polícia se você tentar[n]alguma coisa.[n]Lembre-se disso.[n][f 1 3 65535][w][e]

[msg MSG_365_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8002 65535 0]É um prazer ver você aqui.[n][f 1 3 65535][w][e]

[msg MSG_366_0_0 [Akechi]]
[s][vp 8 0 0 0 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]Oh, certo. Eu acho que Shujin também estava[n]nessa direção...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Ainda assim, eu não esperava encontrar você[n]neste momento. Talvez seja realmente o[n]destino...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Como você está?[n][f 1 3 65535][w][e]

[sel SEL_367_0_0 top]
[s]Nada mal.[e]
[s]Estou com sono.[e]

[msg MSG_368_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54417 65535 0]Haha. Relaxado como sempre, eu vejo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]... Eu tenho sido muito entrevistado[n]ultimamente, então tenho me perguntado como[n]responder a essas perguntas...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 8038 65535 0][f 4 10 65535 0 0]Vejo agora que não há necessidade de ser tão[n]rotatória com minhas respostas. Conversar[n]com você me ajuda a perceber muitas coisas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Se não for muito problemas, posso falar com[n]você novamente algum dia?[n][f 1 3 65535][w][e]

[msg MSG_369_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8040 65535 0]Você ficou acordado muito tarde? Você está[n]bem?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][bup 0 9 1 65535 0][f 4 10 65535 0 0]... Ah, eu gosto dessa resposta. É honesto e[n]impede a conversa de arrastar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]... Eu tenho sido muito entrevistado[n]ultimamente, então tenho me perguntado como[n]responder a essas perguntas...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 8038 65535 0][f 4 10 65535 0 0]Suponho que é melhor ser simplesmente você[n]mesmo e dizer o que você pensa. Você me deu[n]muito a considerar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Se não for muito problemas, posso falar com[n]você novamente algum dia?[n][f 1 3 65535][w][e]

[msg MSG_370_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 154 65535 0]Então nos encontramos novamente. Mas meu[n]tempo escuro que estamos tendo...[n][f 1 3 65535][w][e]

[msg MSG_371_0_0 [Akechi]]
[s][vp 8 0 0 155 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]Falando em obscuros... não houve novos[n]desenvolvimentos nos incidentes do Phantom[n]Thief.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 156 65535 0][f 4 10 65535 0 0]Se eles chegarem ao uso de cartões[n]telefônicos para chamar a atenção, duvido[n]que o caso de Madarame seja o último.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 157 65535 0]Que tipo de alvo eles escolherão a seguir? O[n]que você acha?[n][f 1 3 65535][w][e]

[sel SEL_372_0_0 top]
[s]Um criminoso, eu pensaria.[e]
[s]Eu não faço ideia.[e]

[msg MSG_373_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 158 65535 0]Os ladrões Phantom apenas têm como alvo[n]criminosos, hein... isso é realmente[n]verdade?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 159 65535 0][bup 0 9 3 65535 0][f 4 10 65535 0 0]Supondo que seja, há muitos vilões no mundo.[n]Como eles escolhem quem ir atrás?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 160 65535 0]......[n][f 1 3 65535][w][e]
[s][vp 8 0 0 161 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]...Oh, desculpe. Estou me perdendo na minha[n]própria cabeça...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 162 65535 0][f 4 10 65535 0 0]Eu tenho que ficar no topo de qualquer[n]atividade da Phantom Thieves devido ao que[n]eu disse no ar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 163 65535 0][f 4 10 65535 0 0]Se você ouvir rumores na escola, espero que[n]você possa me avisar.[n][f 1 3 65535][w][e]

[msg MSG_374_0_0 [Akechi]]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 164 65535 0]... Para ser franco, nem eu. Não há material[n]suficiente para formar pensamentos[n]concretos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 165 65535 0][f 4 10 65535 0 0]No entanto, tenho certeza de que em breve[n]terão como alvo alguém que receberá ainda[n]mais atenção...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 166 65535 0]......[n][f 1 3 65535][w][e]
[s][vp 8 0 0 167 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]...Oh, desculpe. Estou me perdendo na minha[n]própria cabeça...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 168 65535 0][f 4 10 65535 0 0]Eu tenho que ficar no topo de qualquer[n]atividade da Phantom Thieves devido ao que[n]eu disse no ar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 169 65535 0][f 4 10 65535 0 0]Se você ouvir rumores na escola, espero que[n]você possa me avisar.[n][f 1 3 65535][w][e]

[msg MSG_375_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 67 65535 0]Parece que você está frequentando a escola[n]seriamente.[n][f 1 3 65535][w][e]

[msg MSG_376_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 68 65535 0]Você também parece bem perto de Takamaki-san[n]se vocês dois estão indo para a escola[n]juntos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 69 65535 0]Você acabou de transferir aqui embora...[n]Eu acho que vocês dois realmente clicam.[n][f 1 3 65535][w][e]

[sel SEL_377_0_0 top]
[s]Estamos na mesma classe.[e]
[s]Na verdade, não.[e]

[msg MSG_378_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 70 65535 0]...Eu vejo. Você parecia muito mais perto do[n]que ontem de manhã.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 74 65535 0]Ouvi dizer que ela era vítima do Sr.[n]Kamoshida, mas era tudo o que havia para[n]isso...?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 75 65535 0][bup 0 6 0 65535 0][f 4 10 65535 0 0]De qualquer maneira, a inspeção mais[n]detalhada deve esclarecer tudo... adeus.[n][f 1 3 65535][w][e]

[msg MSG_379_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 73 65535 0]Sério? Não parecia assim ontem de manhã.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 74 65535 0][f 4 10 65535 0 0]Ouvi dizer que ela era vítima do Sr.[n]Kamoshida, mas era tudo o que havia para[n]isso...?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 75 65535 0][bup 0 6 0 65535 0][f 4 10 65535 0 0]De qualquer maneira, a inspeção mais[n]detalhada deve esclarecer tudo... adeus.[n][f 1 3 65535][w][e]

[msg MSG_380_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 179 65535 0]... Eu cheguei na hora! Suponho que ainda[n]estou seguro se você estiver aqui.[n][f 1 3 65535][w][e]

[msg MSG_381_0_0 [Akechi]]
[s][vp 8 0 0 180 65535 0][bup 0 9 3 65535 0][f 4 10 65535 0 0]Eu não posso me atrasar hoje também...[n][f 1 3 65535][w][e]

[sel SEL_382_0_0 top]
[s]Não é uma pessoa da manhã?[e]
[s]Pareces ocupado.[e]

[msg MSG_383_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 181 65535 0]Não, eu acordava muito cedo, filmando um[n]noticiário.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 182 65535 0][f 4 10 65535 0 0]Tenho muito mais trabalho na televisão por[n]causa dos ladrões fantasmas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 183 65535 0][bup 0 9 3 65535 0][f 4 10 65535 0 0]Tenho permissão da minha escola, mas ainda é[n]difícil fazer as duas coisas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 184 65535 0][bup 0 9 1 65535 0][f 4 10 65535 0 0]... Ah, eu não posso continuar reclamando.[n]Bem, vamos fazer o nosso melhor hoje.[n][f 1 3 65535][w][e]

[msg MSG_384_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 185 65535 0]Bem... eu não nego.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 186 65535 0][f 4 10 65535 0 0]Tenho muito mais trabalho na televisão por[n]causa dos ladrões fantasmas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 187 65535 0][bup 0 9 3 65535 0][f 4 10 65535 0 0]Tenho permissão da minha escola, mas ainda é[n]difícil fazer as duas coisas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 188 65535 0][bup 0 9 1 65535 0][f 4 10 65535 0 0]... Ah, eu não posso continuar reclamando.[n]Bem, vamos fazer o nosso melhor hoje.[n][f 1 3 65535][w][e]

[msg MSG_385_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 204 65535 0]Que clima agradável. Suponho que o final da[n]estação das chuvas?[n][f 1 3 65535][w][e]

[msg MSG_386_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 205 65535 0]Você se lembra da organização criminal de[n]Shibuya que eu falei com você da última vez?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 206 65535 0]A polícia tinha o principal agressor sob[n]custódia, mas ele começou a confessar seus[n]crimes de repente.[n][f 1 3 65535][w][e]

[sel SEL_387_0_0 top]
[s]Isso é bom.[e]
[s]Ele será preso?[e]

[msg MSG_388_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 207 65535 0]Ele definitivamente será preso. A[n]organização se dissipará e o caso será[n]fechado.[n][f 1 3 65535][w][e]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 208 65535 0]Mas há uma coisa em que estou desligado...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 209 65535 0]Por que alguém, que a polícia não conseguiu[n]pegar por todo esse tempo, se entregou do[n]nada?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 210 65535 0]Além disso, existem cartões telefônicos[n]espalhados por Shibuya...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 211 65535 0]O que os ladrões fantasmas fizeram com ele?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 212 65535 0]......[n][f 1 3 65535][w][e]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 213 65535 0]Oh! Desculpe, não quero me atrasar.[n][f 1 3 65535][w][e]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 214 65535 0]Vê você.[n][f 1 3 65535][w][e]

[msg MSG_389_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 215 65535 0]Ele definitivamente será preso. A[n]organização se dissipará e o caso será[n]fechado.[n][f 1 3 65535][w][e]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 216 65535 0]Mas há uma coisa em que estou desligado...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 217 65535 0]Por que alguém, que a polícia não conseguiu[n]pegar por todo esse tempo, se entregou do[n]nada?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 218 65535 0]Além disso, existem cartões telefônicos[n]espalhados por Shibuya...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 219 65535 0]O que os ladrões fantasmas fizeram com ele?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 220 65535 0]......[n][f 1 3 65535][w][e]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 221 65535 0]Oh! Desculpe, não quero me atrasar.[n][f 1 3 65535][w][e]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 222 65535 0]Vê você.[n][f 1 3 65535][w][e]

[msg MSG_390_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 122 65535 0]Eu quero te perguntar uma coisa.[n][f 1 3 65535][w][e]

[msg MSG_391_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 123 65535 0]Por que o Sr. Kamoshida mudou de repente?[n][f 1 3 65535][w][e]

[sel SEL_392_0_0 top]
[s]Ele cresceu consciência.[e]
[s]Eu não estou interessado.[e]

[msg MSG_393_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 124 65535 0]Essa é a sua hipótese?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 125 65535 0][f 4 10 65535 0 0]Ainda é muito repentino...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 126 65535 0][f 4 10 65535 0 0]Eu acredito que é natural pensar que algo[n]deve ter causado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 127 65535 0]... bem, tudo bem.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 128 65535 0][f 4 10 65535 0 0]Obrigado pela sua opinião valiosa.[n]Vou levar em consideração.[n][f 1 3 65535][w][e]

[msg MSG_394_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 129 65535 0]Você não está interessado neste tópico?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 130 65535 0][f 4 10 65535 0 0]Você se esquivou de ameaças imediatas.[n]Você não está interessado no que facilitou a[n]mudança?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 131 65535 0][f 4 10 65535 0 0]... bem, tudo bem.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 132 65535 0][f 4 10 65535 0 0]Obrigado pela sua opinião valiosa.[n]Vou levar em consideração.[n][f 1 3 65535][w][e]

[msg MSG_395_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 57 65535 0]Nós nos encontramos novamente.[n][f 1 3 65535][w][e]

[msg MSG_396_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 58 65535 0]Parece que você está deitado ultimamente.[n]O que há com a mudança?[n][f 1 3 65535][w][e]

[sel SEL_397_0_0 top]
[s]Estou agindo da mesma forma que de costume...[e]
[s]O que você quer dizer?[e]

[msg MSG_398_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 59 65535 0]Realmente... é apenas a minha imaginação[n]então?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 60 65535 0][f 4 10 65535 0 0]De qualquer forma...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 61 65535 0][f 4 10 65535 0 0]Eu gostaria que o culpado aparecesse em[n]breve...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 62 65535 0][f 4 10 65535 0 0]É absurdo fingir que posso fazer o trabalho[n]da polícia... Eu gostaria que ele[n]considerasse meus sentimentos antes de me[n]perguntar isso.[n][f 1 3 65535][w][e]

[msg MSG_399_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 63 65535 0]... Não se preocupe com isso. Deve ter sido[n]minha imaginação.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 64 65535 0][f 4 10 65535 0 0]Qualquer maneira...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 65 65535 0][f 4 10 65535 0 0]Eu gostaria que o culpado aparecesse em[n]breve...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 66 65535 0][f 4 10 65535 0 0]É absurdo fingir que posso fazer o trabalho[n]da polícia... Eu gostaria que ele[n]considerasse meus sentimentos antes de me[n]perguntar isso.[n][f 1 3 65535][w][e]

[msg MSG_400_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 223 65535 0]Que manhã refrescante. Como você está?[n][f 1 3 65535][w][e]

[msg MSG_401_0_0 [Akechi]]
[s][vp 8 0 0 224 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]... Eu não esperava que os ladrões fantasmas[n]suprimissem um homem com quem até a polícia[n]tinha problemas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 225 65535 0][bup 0 9 3 65535 0][f 4 10 65535 0 0]O fato de terem muito apoio online é[n]preocupante. Estou em um encadernador desde[n]que os denunciei anteriormente.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 226 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]Todas as entrevistas hoje em dia me[n]perguntam sobre isso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 227 65535 0][f 4 10 65535 0 0]... Ainda assim, podemos realmente dizer que[n]os ladrões fantasmas estão do lado da[n]justiça com apenas este exemplo?[n][f 1 3 65535][w][e]

[sel SEL_402_0_0 top]
[s]O que você quer dizer?[e]
[s]Deixe as pessoas falarem.[e]

[msg MSG_403_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 228 65535 0]Eu estava originalmente investigando os[n]incidentes de desligamento mental.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 229 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]As pessoas mudam de repente e causam[n]acidentes estranhos ou crimes horríveis...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 230 65535 0][f 4 10 65535 0 0]... Você não acha que é semelhante à mudança[n]de coração que os ladrões fantasmas estão[n]fazendo?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 231 65535 0][bup 0 9 3 65535 0]......[n][f 1 3 65535][w][e]
[s][vp 8 0 0 232 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]Agora que penso nisso, suas ações refletem[n]os casos de desligamento mental, com a taxa[n]de vítimas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 233 65535 0][f 4 10 65535 0 0]É impossível não ver uma conexão lá...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 234 65535 0][bup 0 9 4 65535 0][f 4 10 65535 0 0]... Ah, desculpe. Eu não quero te fazer[n]tarde. Vejo você de novo.[n][f 1 3 65535][w][e]

[msg MSG_404_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 235 65535 0]Haha, obrigado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 236 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]Mas... noto que você não está dizendo que os[n]ladrões fantasmas estão certos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 237 65535 0][f 4 10 65535 0 0]... Suponho que essa era uma maneira injusta[n]de expressá-lo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 238 65535 0][f 4 10 65535 0 0]Eu estava originalmente investigando os[n]incidentes de desligamento mental.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 239 65535 0][f 4 10 65535 0 0]... Você não acha que é semelhante à mudança[n]de coração que os ladrões fantasmas estão[n]fazendo?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 240 65535 0][bup 0 9 3 65535 0]......[n][f 1 3 65535][w][e]
[s][vp 8 0 0 241 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]Agora que penso nisso, suas ações refletem[n]os casos de desligamento mental, com a taxa[n]de vítimas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 242 65535 0][f 4 10 65535 0 0]É impossível não ver uma conexão lá...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 243 65535 0][bup 0 9 4 65535 0][f 4 10 65535 0 0]... Ah, desculpe. Eu não quero te fazer[n]tarde. Vejo você de novo.[n][f 1 3 65535][w][e]

[msg MSG_405_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 244 65535 0]É realmente verão agora. Fico suado apenas[n]andando um pouco.[n][f 1 3 65535][w][e]

[msg MSG_406_0_0 [Akechi]]
[s][vp 8 0 0 245 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]Eu não achei que Medjed atacasse os ladrões[n]Phantom. Coisas interessantes continuam[n]acontecendo este ano.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 246 65535 0][f 4 10 65535 0 0]A influência de [f 4 28]não conhece limites... eu subestimei,[n]honestamente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 247 65535 0]Eu me pergunto o que o público pensa disso.[n]Eles estão entretidos? Ou talvez incomodado?[n][f 1 3 65535][w][e]

[sel SEL_407_0_0 top]
[s]Entretido.[e]
[s]Incomodado.[e]

[msg MSG_408_0_0 [Akechi]]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 248 65535 0]Entretido, hein...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 249 65535 0][f 4 10 65535 0 0]Um luxo para os não envolvidos. Eu sei que[n]eles não significam nenhuma intenção.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 250 65535 0][f 4 10 65535 0 0]Então é isso que o público pensa...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 251 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]... Opa, não tenho tempo para uma conversa.[n]Minha participação tem sido ruim devido a[n]entrevistas ultimamente.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 252 65535 0][bup 0 9 1 65535 0][f 4 10 65535 0 0]Obrigado por sua opinião valiosa.[n]Eu te vejo por aí.[n][f 1 3 65535][w][e]

[msg MSG_409_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 253 65535 0]Pessoas com bom senso pensariam isso. Essa[n]também é sua opinião pessoal?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 254 65535 0][bup 0 9 3 65535 0][f 4 10 65535 0 0]Ainda assim, a grande maioria é simplesmente[n]entretida por isso. Eles pararam de pensar[n]criticamente...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 255 65535 0][f 4 10 65535 0 0]Então é isso que o público pensa...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 256 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]... Opa, não tenho tempo para uma conversa.[n]Minha participação tem sido ruim devido a[n]entrevistas ultimamente.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 257 65535 0][bup 0 9 1 65535 0][f 4 10 65535 0 0]Obrigado por sua opinião valiosa.[n]Eu te vejo por aí.[n][f 1 3 65535][w][e]

[msg MSG_410_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 268 65535 0]Huh? Você conseguiu um bronzeado? Você[n]parece diferente.[n][f 1 3 65535][w][e]

[msg MSG_411_0_0 [Akechi]]
[s][vp 8 0 0 269 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]Oh sim. Obrigado pelo café da última vez.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 270 65535 0][f 4 10 65535 0 0]It's a lovely café. I haven't relaxed[n]tanto há algum tempo.[n][f 1 3 65535][w][e]

[sel SEL_412_0_0 top]
[s]Você deveria voltar.[e]
[s]Está ocupado?[e]

[msg MSG_413_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 271 65535 0]É legal da sua parte dizer.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 272 65535 0][bup 0 9 3 65535 0][f 4 10 65535 0 0]Especialmente ultimamente, pois parece que[n]sou odiado por aqueles que apóiam os[n]ladrões Phantom...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 273 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]De qualquer forma, parece que sua escola[n]está com problemas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 274 65535 0][f 4 10 65535 0 0]A mídia está relatando que toda a escola[n]estava envolvida no encobrimento sobre o[n]professor de academia.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 275 65535 0][bup 0 9 3 65535 0][f 4 10 65535 0 0]Esses estudantes infelizes foram feitos de[n]vítimas, porque adultos valorizavam suas[n]próprias conveniências...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 276 65535 0][f 4 10 65535 0 0]Isso é imperdoável, não importa o motivo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 277 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]...Deixe-me saber se você precisar de alguma[n]coisa.[n]Farei o meu melhor para que o caso esteja[n]envolvido rapidamente.[n][f 1 3 65535][w][e]

[msg MSG_414_0_0 [Akechi]]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 278 65535 0]Não, não particularmente...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 279 65535 0][f 4 10 65535 0 0]Especialmente ultimamente, pois parece que[n]sou odiado por aqueles que apóiam os[n]ladrões Phantom...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 280 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]De qualquer forma, parece que sua escola[n]está com problemas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 281 65535 0][f 4 10 65535 0 0]A mídia está relatando que toda a escola[n]estava envolvida no encobrimento sobre o[n]professor de academia.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 282 65535 0][bup 0 9 3 65535 0][f 4 10 65535 0 0]Esses estudantes infelizes foram feitos de[n]vítimas, porque adultos valorizavam suas[n]próprias conveniências...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 283 65535 0][f 4 10 65535 0 0]Isso é imperdoável, não importa o motivo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 284 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]...Deixe-me saber se você precisar de alguma[n]coisa.[n]Farei o meu melhor para que o caso esteja[n]envolvido rapidamente.[n][f 1 3 65535][w][e]

[msg MSG_415_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 285 65535 0]Eu me pergunto quanto tempo esse calor[n]continuará... é cansativo.[n][f 1 3 65535][w][e]

[msg MSG_416_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 286 65535 0]Você conhece os rankings que são populares[n]hoje em dia? Você também está interessado[n]neles?[n][f 1 3 65535][w][e]

[sel SEL_417_0_0 top]
[s]É claro.[e]
[s]De jeito nenhum.[e]

[msg MSG_418_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 287 65535 0]Eu não culpo você. Todo mundo está prestando[n]atenção a isso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 288 65535 0][f 4 10 65535 0 0]Você sabia que meu nome também está listado?[n]Aparentemente, é devido à minha recente[n]desaprovação do grupo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 289 65535 0][bup 0 9 1 65535 0][f 4 10 65535 0 0]Antes que eu percebesse, eu me transformei[n]em um vilão de boa-fé.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 290 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]Ainda assim, pensei que, se eu me tornasse[n]um alvo, pudesse descobrir seus métodos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 291 65535 0][f 4 10 65535 0 0]A ideia era atraente quando pensei nisso.[n]Claro, não há garantia de que eu estaria[n]seguro.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 292 65535 0][bup 0 9 4 65535 0][f 4 10 65535 0 0]... bem, falar mais nos deixará atrasados.[n]Até logo![n][f 1 3 65535][w][e]

[msg MSG_419_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 293 65535 0]Você não está interessado...? Você é do tipo[n]que vai contra a tendência?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 294 65535 0][f 4 10 65535 0 0]Você sabia que meu nome também está listado?[n]Aparentemente, é devido à minha recente[n]desaprovação do grupo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 295 65535 0][bup 0 9 1 65535 0][f 4 10 65535 0 0]Antes que eu percebesse, eu me transformei[n]em um vilão de boa-fé.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 296 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0]Ainda assim, pensei que, se eu me tornasse[n]um alvo, pudesse descobrir seus métodos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 297 65535 0][f 4 10 65535 0 0]A ideia era atraente quando pensei nisso.[n]Claro, não há garantia de que eu estaria[n]seguro.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 298 65535 0][bup 0 9 1 65535 0][f 4 10 65535 0 0]Você deve conferir a lista em algum momento.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 299 65535 0][bup 0 9 4 65535 0][f 4 10 65535 0 0]... bem, falar mais nos deixará atrasados.[n]Até logo![n][f 1 3 65535][w][e]

[msg MSG_420_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 300 65535 0]É a primeira vez na escola em algum tempo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 301 65535 0][bup 0 2 7 65535 0][f 4 10 65535 0 0]*Bocejo* Estou com muito sono.[n][f 1 3 65535][w][e]

[msg MSG_421_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 302 65535 0]Você sobre o seu jet lag?[n][f 1 3 65535][w][e]

[sel SEL_422_0_0 top]
[s]Eu sou.[e]
[s]Ainda não.[e]

[msg MSG_423_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 303 65535 0]Sério? Aquilo foi rápido...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 304 65535 0][bup 0 2 1 65535 0][f 4 10 65535 0 0]Oh sim! Esqueça isso.[n]Você sabia sobre isso?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 305 65535 0][f 4 10 65535 0 0]Os ladrões Phantom são populares agora![n]Fiquei surpreso quando voltamos ao Japão.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 306 65535 0][f 4 10 65535 0 0]As pessoas estão realmente prestando atenção[n]a quem vamos atingir a seguir. Não é isso[n]surpreendente?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 307 65535 0][f 4 10 65535 0 0]Estou ficando muito empolgado. É aqui que[n]trabalhamos duro![n][f 1 3 65535][w][e]
[s][vp 8 0 0 308 65535 0][f 4 10 65535 0 0]Vamos fazer algo grande de novo e[n]surpreender o mundo![n][f 1 3 65535][w][e]

[msg MSG_424_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 309 65535 0]Ainda lento, hein? Bem, eu posso dizer o[n]mesmo para mim...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 310 65535 0][bup 0 2 1 65535 0][f 4 10 65535 0 0]Não importa isso, no entanto. Você sabia[n]sobre isso?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 311 65535 0][f 4 10 65535 0 0]Os ladrões Phantom são populares agora![n]Fiquei surpreso quando voltamos ao Japão.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 312 65535 0][f 4 10 65535 0 0]As pessoas estão realmente prestando atenção[n]a quem vamos atingir a seguir. Não é isso[n]surpreendente?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 313 65535 0][f 4 10 65535 0 0]Estou ficando muito empolgado. É aqui que[n]trabalhamos duro![n][f 1 3 65535][w][e]
[s][vp 8 0 0 314 65535 0][f 4 10 65535 0 0]Vamos fazer algo grande de novo e[n]surpreender o mundo![n][f 1 3 65535][w][e]

[msg MSG_425_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]Manhã. A reunião do conselho é o dia depois[n]de amanhã.[n][f 1 3 65535][w][e]

[msg MSG_426_0_0 [Ann]]
[s][vp 8 0 0 47 65535 0][bup 0 4 3 65535 0][f 4 10 65535 0 0]... Eu me pergunto se Kamoshida realmente[n]mudou de coração?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 48 65535 0][f 4 10 65535 0 0]E se falhássemos? Isso é tudo em que pude[n]pensar...[n][f 1 3 65535][w][e]

[sel SEL_427_0_0 top]
[s]Nós temos que acreditar.[e]
[s]Preocupado, hein?[e]

[msg MSG_428_0_0 [Ann]]
[s][vp 8 0 0 49 65535 0][bup 0 4 3 65535 0][f 4 10 65535 0 0]Fizemos o que podíamos. Acho que tudo o que[n]posso fazer agora é acreditar...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 50 65535 0][bup 0 4 0 65535 0][f 4 10 65535 0 0]Mas que estranho... me sinto um pouco melhor[n]agora.[n]Talvez seja por causa da sua compostura?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 51 65535 0][bup 0 4 1 65535 0][f 4 10 65535 0 0]Seremos capazes de vingar Shiho, e você não[n]será expulso! Após o intervalo, todos[n]seremos capazes de rir juntos![n][f 1 3 65535][w][e]
[s][vp 8 0 0 52 65535 0][bup 0 4 0 65535 0][f 4 10 65535 0 0]É nisso que vou acreditar.[n][f 1 3 65535][w][e]

[msg MSG_429_0_0 [Ann]]
[s][vp 8 0 0 53 65535 0][bup 0 4 3 65535 0][f 4 10 65535 0 0]Avenging Shiho, e fazendo suas expulsões[n]revogadas...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 54 65535 0][f 4 10 65535 0 0]Está tudo descansando sobre essa chance.[n]Claro que estou preocupado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 55 65535 0][bup 0 4 0 65535 0][f 4 10 65535 0 0]Mas a única coisa que posso fazer agora é[n]acreditar... e esperar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 56 65535 0][f 4 10 65535 0 0]...Desculpe. Obrigado por ouvir. Devemos[n]chegar à escola.[n][f 1 3 65535][w][e]

[msg MSG_430_0_0 [Woman with Camera]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 16002 65535 0]Ei, é você![n][f 1 3 65535][w][e]

[msg MSG_431_0_0 [Woman with Camera]]
[s][vp 8 0 0 0 65535 0][bup 0 107 0 65535 0][f 4 10 65535 0 0]Manhã! Indo para a escola agora?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Estou apenas voltando para casa! O sol da[n]manhã está muito brilhante...[n][f 1 3 65535][w][e]

[sel SEL_432_0_0 top]
[s]E quanto ao seu trabalho?[e]
[s]Quem é você de novo?[e]

[msg MSG_433_0_0 [Woman with Camera]]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 16036 65535 0]Eu puxei uma noite toda. O jornalista Ichiko[n]Ohya trabalha o tempo todo, você sabe![n][f 1 3 65535][w][e]
[s][bup 0 107 0 65535 0][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Bem, você trabalha duro em seus estudos.[n][f 1 3 65535][w][e]

[msg MSG_434_0_0 [Woman with Camera]]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 16044 65535 0]Ei! Como você poderia esquecer uma garota[n]adorável como eu?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Eu sou Ichiko Ohya, jornalista.[n]Eu entrevistei você na residência Madarame,[n]lembra?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]*Bocejo* Homem, All-Nighters são difíceis.[n]Bem, você trabalha duro em seus estudos.[n][f 1 3 65535][w][e]

[msg MSG_435_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3001 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_436_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*Giggle* Você ainda parece sonolento.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Deixe-me saber se você estiver indo para o[n]palácio, ok? Estou pronto para ir a[n]qualquer hora.[n][f 1 3 65535][w][e]
[s][bup 0 7 3 65535 0][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]......[n][f 1 3 65535][w][e]

[msg ``＜選択肢＞`` [Haru]]
[s]Você está bem?[n]Não se esforce.[n][e]

[msg MSG_438_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3194 65535 0]...Estou bem.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu tomei essa decisão por mim mesma, então[n]não me arrependo.[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Oh, desculpe. Esta discussão está ficando[n]meio sombria. Eu preciso sair disso.[n][f 1 3 65535][w][e]

[msg MSG_439_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Não estou, não se preocupe. Eu estaria[n]mentindo se dissesse que não estava[n]sozinho, mas...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 3189 65535 0][f 4 10 65535 0 0]Eu tomei essa decisão por mim mesma, então[n]não me arrependo.[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]...Oh, desculpe. Esta discussão está ficando[n]meio sombria. Eu preciso sair disso.[n][f 1 3 65535][w][e]

[msg MSG_440_0_0 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 19005 65535 0]Oh, bom dia, [f 4 1].[n][f 1 3 65535][w][e]

[msg MSG_441_0_0 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sobre as solicitações do local do phan. Se[n]eu encontrar algum este ano, certamente[n]passarei as informações sobre você![n][f 1 3 65535][w][e]

[sel SEL_442_0_0 top]
[s]Soa bem.[e]
[s]O que você está falando?[e]

[msg MSG_443_0_0 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 19024 65535 0]Não há tantas postagens agora, mas parece[n]que ainda há muitas pessoas em apuros.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Estamos todos contando com você, Phantom[n]Thieves! Dispense a justiça![n][f 1 3 65535][w][e]

[msg MSG_444_0_0 [Mishima]]
[s][bup 0 111 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 19067 65535 0]Opa, eu provavelmente não deveria dizer isso[n]aqui. Foi mal.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][bup 0 111 1 65535 0][f 4 10 65535 0 0]Não há tantas postagens agora, mas parece[n]que ainda há muitas pessoas em apuros.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 19024 65535 0]Estamos todos contando com você, Phantom[n]Thieves! Dispense a justiça![n][f 1 3 65535][w][e]

[msg MSG_445_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54053 65535 0]Manhã. É outro dia frio.[n][f 1 3 65535][w][e]

[msg MSG_446_0_0 [Ann]]
[s][bup 0 4 3 65535 0][vp 8 0 0 0 65535 0]......[n][f 1 3 65535][w][e]
[s][vp 8 2 0 6058 65535 0][f 4 10 65535 0 0]Você sabe, o público tem agido meio estranho[n]ultimamente, hein?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Até as pessoas ao meu redor estão falando de[n]maneira diferente agora, ou estão realmente[n]estranhamente otimistas...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]É a mesma coisa na cidade também.[n]Todo mundo parece meio inquieto...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Isso faz parte do poder do Dr. Maruki[n]também, não é?[n][f 1 3 65535][w][e]

[sel SEL_447_0_0 top]
[s]É possível.[e]
[s]Não sei.[e]

[msg MSG_448_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6188 65535 0]Sim. Eu acho que ainda não aconteceu com[n]todos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Mas se não mudarmos o coração do Dr. Maruki[n]até o prazo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Nem vamos perceber que algo está mais errado.[n][f 1 3 65535][w][e]
[s][bup 0 4 2 65535 0][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Temos que vencer, não importa o quê.[n][f 1 3 65535][w][e]

[msg MSG_449_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6166 65535 0]Bem, acho que ainda não aconteceu com todos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Mas se não mudarmos o coração do Dr. Maruki[n]até o prazo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Nem vamos perceber que algo está mais errado.[n][f 1 3 65535][w][e]
[s][bup 0 4 2 65535 0][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Temos que vencer, não importa o quê.[n][f 1 3 65535][w][e]

[msg MSG_450_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57005 65535 0]Bom dia, Senpai.[n][f 1 3 65535][w][e]

[msg MSG_451_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estamos indo para lembranças hoje?[n]Estou sempre pronto para ir ao meu lado.[n][f 1 3 65535][w][e]

[sel SEL_452_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Talvez não hoje...[e]

[msg MSG_453_0_0 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57026 65535 0]Ok! Temos uma questão para nos estabelecer[n]lá![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Vejo você mais tarde então. Por favor, dê-me[n]licença![n][f 1 3 65535][w][e]

[msg MSG_454_0_0 [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 57055 65535 0]Oh...[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bem, se você mudar de idéia, por favor me[n]avise![n][f 1 3 65535][w][e]

[msg MSG_455_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3001 65535 0]Ah, bom dia.[n][f 1 3 65535][w][e]

[msg MSG_456_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3021 65535 0]Todo mundo mudou. Isso pode realmente ser o[n]que é a felicidade...?[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]......[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3197 65535 0]Ei, por que não vamos para lembranças hoje?[n]Não podemos simplesmente deixar as coisas[n]do jeito que elas são.[n][f 1 3 65535][w][e]

[sel SEL_457_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Eu tenho outros planos.[e]

[msg MSG_458_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3020 65535 0]Ok! Vejo você mais tarde então.[n][f 1 3 65535][w][e]

[msg MSG_459_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 53561 65535 0]Oh... acho que não podemos fazer nada sobre[n]isso então.[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Se você pode ir, por favor, diga-me. Vou ter[n]certeza de que estou pronto.[n][f 1 3 65535][w][e]

[msg MSG_460_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8005 65535 0]Bom Dia, [f 4 2].[n][f 1 3 65535][w][e]

[msg MSG_461_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você está livre depois da escola hoje?[n]Estou pensando em ir a lembranças.[n][f 1 3 65535][w][e]

[sel SEL_462_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Deixe-me pensar sobre isso.[e]

[msg MSG_463_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54417 65535 0]Eu esperava que você diria isso. Vejo você[n]depois da escola então.[n][f 1 3 65535][w][e]

[msg MSG_464_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8028 65535 0]HM. Não estou preocupado, eu vejo. Eu não[n]acho que realmente temos tempo a perder.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Bem, tudo bem então. Deixe-me saber se você[n]mudar de idéia.[n][f 1 3 65535][w][e]

[msg MSG_465_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57005 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_466_0_0 [Sumire]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 57142 65535 0]Hum, tenho certeza que você já sabe disso,[n]mas não temos muito tempo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Temos que consertar o mundo, ou então...[n]Estamos indo para lembranças hoje, certo!?[n][f 1 3 65535][w][e]

[sel SEL_467_0_0 top]
[s]É claro.[f 2 7 0 1 971 1][e]
[s]Hum...[e]

[msg MSG_468_0_0 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57052 65535 0]Obrigado Senhor! Eu terminei de me preparar[n]do meu lado![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ok, te vejo depois da escola.[n]Por favor, dê-me licença![n][f 1 3 65535][w][e]

[msg MSG_469_0_0 [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 57060 65535 0]S-senpai... não é hora de ser indeciso...[n][f 1 3 65535][w][e]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Nós realmente deveríamos ir! Eu vou estar[n]esperando por você.[n][f 1 3 65535][w][e]

[msg MSG_470_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57022 65535 0]Bom dia, senpai![n][f 1 3 65535][w][e]

[msg MSG_471_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se estiver tudo bem com você, poderíamos ir[n]ao palácio hoje?[n][f 1 3 65535][w][e]

[sel SEL_472_0_0 top]
[s]Certo.[f 2 7 0 1 971 1][e]
[s]Deixe-me preparar.[e]

[msg MSG_473_0_0 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57039 65535 0]Obrigado! Vamos nos encontrar depois da[n]escola então.[n][f 1 3 65535][w][e]

[msg MSG_474_0_0 [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 57053 65535 0]Bom ponto. É muito perigoso lá.[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Avise-me quando terminar seus preparativos[n]então. Vou ter certeza de que estou pronto[n]para o meu fim também![n][f 1 3 65535][w][e]

[msg MSG_475_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4005 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_476_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 4028 65535 0]O estado do público ainda é o mesmo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Essas pessoas estão tendo seu passado e[n]experiências fabricadas, felizmente sem[n]saber que estão vivendo uma mentira...[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Eu posso entender como sua vida seria mais[n]fácil dessa maneira, mas não aguento.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4087 65535 0]Temos cerca de duas semanas até o prazo.[n]Ainda há tempo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Mas não podemos nos dar ao luxo de ficar[n]ocioso. Quais são seus planos para hoje, [n][f 4 2]?[n][f 1 3 65535][w][e]

[sel SEL_477_0_0 top]
[s]Vamos para o palácio.[f 2 7 0 1 971 1][e]
[s]Eu gostaria de me preparar.[e]

[msg MSG_478_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0]Entendido. Então vamos nos reunir depois da[n]escola.[n][f 1 3 65535][w][e]

[msg MSG_479_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4107 65535 0]Eu vejo. É importante estar pronto para[n]quaisquer ocorrências inesperadas.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Se você planeja ir ao palácio, no entanto,[n]me avise. Vou ir imediatamente.[n][f 1 3 65535][w][e]

[msg MSG_480_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57021 65535 0]Bom dia, Senpai.[n][f 1 3 65535][w][e]

[msg MSG_481_0_0 [Sumire]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não estou apressando você ou algo assim, mas[n]poderíamos ir ao palácio hoje?[n][f 1 3 65535][w][e]
[s][bup 0 10 3 65535 0][vp 8 2 0 57036 65535 0][f 4 10 65535 0 0]Sinto que não há muito tempo antes de[n]enfrentarmos o Dr. Maruki.[n][f 1 3 65535][w][e]

[sel SEL_482_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Não fique apressado.[e]

[msg MSG_483_0_0 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57026 65535 0]Ok! Vejo você mais tarde então.[n]Por favor, dê-me licença![n][f 1 3 65535][w][e]

[msg MSG_484_0_0 [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 57053 65535 0]Você tem razão. Sinto muito por ser tão[n]egoísta...[n][f 1 3 65535][w][e]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Mas, por favor, avise-me quando você for.[n]Eu posso estar pronto a qualquer momento![n][f 1 3 65535][w][e]

[msg MSG_485_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3001 65535 0]Bom Dia. Está muito frio hoje.[n][f 1 3 65535][w][e]

[msg MSG_486_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3197 65535 0]Você acha que já era hora de fomos ao[n]palácio? Não que eu esteja apressando você[n]ou algo assim...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Mas o prazo está chegando, certo?[n]Estou apenas um pouco preocupado.[n][f 1 3 65535][w][e]

[sel SEL_487_0_0 top]
[s]Vamos para o palácio.[f 2 7 0 1 971 1][e]
[s]Vou passar por hoje.[e]

[msg MSG_488_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3020 65535 0]OK, claro! Afinal, temos um trabalho a fazer.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Nos encontraremos depois da escola então.[n][f 1 3 65535][w][e]

[msg MSG_489_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 3186 65535 0]Huh...? Bem, acho que não seria bom entrar[n]em pânico.[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Mas ainda temos um trabalho a fazer. Por[n]favor, deixe-me saber se você decidir ir,[n]ok?[n][f 1 3 65535][w][e]

[msg MSG_490_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54473 65535 0][f 4 2]...[n][f 1 3 65535][w][e]

[msg MSG_491_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54499 65535 0]Tudo bem se você não estiver preocupado, mas[n]você vai se queimar se for empolgado.[n][f 1 3 65535][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não há muito tempo até o prazo.[n]Eu acredito que você pretende ir ao palácio[n]hoje?[n][f 1 3 65535][w][e]

[sel SEL_492_0_0 top]
[s]É claro.[f 2 7 0 1 971 1][e]
[s]Estou pensando sobre isso.[e]

[msg MSG_493_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54502 65535 0]Em seguida, nos encontraremos no lugar[n]habitual depois da escola.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Já disse isso muitas vezes, mas estamos[n]ficando sem tempo. Eu acredito que seria[n]apropriado entrar em pânico um pouco aqui.[n][f 1 3 65535][w][e]

[msg MSG_494_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54494 65535 0]Tch. Você simplifica...[n][f 1 3 65535][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Já disse isso muitas vezes, mas estamos[n]ficando sem tempo. Se você está ficando com[n]pés frios, fale agora.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas se você tiver vontade de lutar, ligue[n]para uma assembléia no esconderijo. Temos[n]que ir ao palácio.[n][f 1 3 65535][w][e]

[msg MSG_495_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57005 65535 0]Bom dia, Senpai.[n][f 1 3 65535][w][e]

[msg MSG_496_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então a única coisa que resta a fazer[n]agora... é esperar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hum, estou pensando em fazer algum[n]treinamento. Eu não quero arrastar todo[n]mundo para baixo.[n][f 1 3 65535][w][e]

[sel SEL_497_0_0 top]
[s]Não exagere.[e]
[s]Isso é impressionante.[e]

[msg MSG_498_0_0 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57030 65535 0]Eu vou ficar bem! A única coisa que tenho em[n]espadas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]... Mas não posso ter certeza do que vai[n]acontecer, então terei que fazê-lo com[n]moderação.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, olhe para a hora! Deveríamos continuar![n][f 1 3 65535][w][e]

[msg MSG_499_0_0 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57039 65535 0]Obrigado![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ainda não cheguei ao nível de todos os[n]outros, mas vou me certificar de que posso[n]fazer a minha parte![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oh, eu tenho que ir agora.[n]Por favor, dê-me licença.[n][f 1 3 65535][w][e]

[msg MSG_500_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0]Morniiin '.[n][f 1 3 65535][w][e]

[msg MSG_501_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7048 65535 0]Puta merda, essa neve é louca. Está[n]congelando, mas excitando ao mesmo tempo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Diga, você acha que houve alguma mudança em[n]lembranças também?[n][f 1 3 65535][w][e]

[sel SEL_502_0_0 top]
[s]Vamos ver.[f 2 7 0 1 971 1][e]
[s]Tenho que me preparar.[e]

[msg MSG_503_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7080 65535 0]Ah, inferno, sim![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu me pergunto como vai ser diferente?[n]Estou tão bombeado. Você tem que ficar[n]animado em momentos como este![n][f 1 3 65535][w][e]

[msg MSG_504_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7038 65535 0]Bem, vamos dar uma olhada depois que você[n]estiver pronto![n]Vamos, pareça bom!?[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Prometa-me que você pensa sobre isso, certo[n]cara?[n][f 1 3 65535][w][e]

[msg MSG_505_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8005 65535 0]Bom Dia, [f 4 2].[n][f 1 3 65535][w][e]

[msg MSG_506_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54502 65535 0]Dois dias até o prazo... nosso acordo também[n]estará acordado.[n][f 1 3 65535][w][e]

[sel SEL_507_0_0 top]
[s]O que você fará depois disso?[e]
[s]Tem sido um longo prazo.[e]

[msg MSG_508_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54489 65535 0]Não sou obrigado a te contar. Isso não faz[n]parte do nosso acordo.[n][f 1 3 65535][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Não importa o futuro. Apenas concentre-se em[n]derrotar Maruki por enquanto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Se perdermos, um destino mais humilhante do[n]que a morte estará esperando por nós.[n][f 1 3 65535][w][e]

[msg MSG_509_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54410 65535 0]Certamente tem...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]... Vamos acabar com tudo. Eu já tive o[n]suficiente dessa piada de um mundo.[n][f 1 3 65535][w][e]

[msg MSG_510_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57021 65535 0]Bom dia, Senpai.[n][f 1 3 65535][w][e]

[msg MSG_511_0_0 [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 57037 65535 0]... Amanhã é o dia, se o Dr. Maruki gosta ou[n]não...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]......[n][f 1 3 65535][w][e]

[sel SEL_512_0_0 top]
[s]Você está nervoso?[e]
[s]Apenas trate-o como qualquer outro dia.[e]

[msg MSG_513_0_0 [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 57180 65535 0]... um pouco, desculpe.[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Mas fizemos tudo o que podemos. Vamos dar[n]tudo o que temos e vencer agora.[n][f 1 3 65535][w][e]

[msg MSG_514_0_0 [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 57027 65535 0]Como qualquer outro dia... você está certo.[n]Eu não posso deixar os nervos chegarem até[n]mim agora...[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Fizemos tudo o que podemos. Vamos dar tudo o[n]que temos e vencer agora.[n][f 1 3 65535][w][e]

[msg MSG_515_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7001 65535 0]'E aí![n][f 1 3 65535][w][e]

[msg MSG_516_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Acabei de ouvir isso, mas aparentemente[n]estamos tendo um festival de verão em breve![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ouvi dizer que vai haver merdas como kebabs,[n]bifes... as coisas gostosas! Cara, estou[n]tão bombeado![n][f 1 3 65535][w][e]

[sel SEL_517_0_0 top]
[s]Que tal estudar?[e]
[s]Não há nada além de carne...?[e]

[msg MSG_518_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7156 65535 0]Bem, uh...[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]... eu vou descobrir! Havia algum inglês no[n]site também.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 7179 65535 0]Oh cara, agora estou com fome. Já vamos lá![n][f 1 3 65535][w][e]

[msg MSG_519_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7177 65535 0]Bem, duh! O que mais você gostaria?[n][f 1 3 65535][w][e]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh cara... eu não consigo parar de pensar em[n]carne... canalizando carne quente e[n]suculenta...[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7179 65535 0]Oh cara, agora estou com fome. Já vamos lá![n][f 1 3 65535][w][e]

[msg MSG_520_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 53512 65535 0]Oh, bom dia, [f 4 2]-kun.[n]Está frio hoje.[n][f 1 3 65535][w][e]

[msg MSG_521_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu, hum... desculpe, mas acho que não posso[n]me trazer para enfrentar você.[n][f 1 3 65535][w][e]

[sel SEL_522_0_0 top]
[s]Algo está errado?[e]
[s]Você está bem?[e]

[msg MSG_523_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3020 65535 0]Bem... é sobre meu pai.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]... Hum, há algo que eu preciso lhe dizer.[n]Você poderia me encontrar no telhado da[n]escola sempre que tiver tempo?[n][f 1 3 65535][w][e]

[msg MSG_524_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3036 65535 0]Estou bem? Eu não acho.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]... Hum, há algo que eu preciso lhe dizer.[n]Você poderia me encontrar no telhado da[n]escola sempre que tiver tempo?[n][f 1 3 65535][w][e]

[msg MSG_525_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0](仮)はよーっす。[n][f 1 3 65535][w][e]

[msg MSG_526_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...お前さ、話しに来てくれただろ?[n]1月の、初め頃さ。[n][f 1 3 65535][w][e]

[sel SEL_527_0_0 top]
[s]どうした?[e]
[s]大丈夫か?[e]

[msg MSG_528_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0]...あの時からずっと考えてることがあんだ。[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]やっとまとまってきたっつーか...[n]—ィけど[f 4 2] の時間ある時に、話聞いてくれ。[n][f 1 3 65535][w][e]

[msg MSG_529_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7032 65535 0]や、ダイジョーブ。[n]...けどよ、あの時からずっと考えてることがあんだ。[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]やっとまとまってきたっつーか...[n]—ィけど[f 4 2] の時間ある時に、話聞いてくれ。[n][f 1 3 65535][w][e]

[msg MSG_530_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0](仮)あ、[f 4 2] 君おはよう。[n]寒いね。[n][f 1 3 65535][w][e]

[msg MSG_531_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...あのね、その...[n]...ごめんね、なんか顔見れないや...[n][f 1 3 65535][w][e]

[sel SEL_532_0_0 top]
[s]どうした?[e]
[s]大丈夫か?[e]

[msg MSG_533_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]うん。[n]...お父様の事。[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...あのね、聞いて欲しい事があるの。[n]時間がある時でいいから、屋上に来て欲しいな。[n][f 1 3 65535][w][e]

[msg MSG_534_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]大丈夫...じゃ、[n]ない。かな。[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...あのね、聞いて欲しい事があるの。[n]時間がある時でいいから、屋上に来て欲しいな。[n][f 1 3 65535][w][e]

[msg MSG_535_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2005 65535 0](仮)あ、[f 4 2] おはよう。[n][f 1 3 65535][w][e]

[msg MSG_536_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...あのね、その...[n][f 1 3 65535][w][e]

[sel SEL_537_0_0 top]
[s]どうした?[e]
[s]大丈夫か?[e]

[msg MSG_538_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 2087 65535 0]...[f 4 2] 、話しに来てくれたよね。[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...あのね、ずっと考えてたことがあるの。[n]時間がある時でいいから、聞いてくれない?[n][f 1 3 65535][w][e]

[msg MSG_539_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 2100 65535 0]...どうかしら。[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...あのね、ずっと考えてたことがあるの。[n]時間がある時でいいから、聞いてくれない?[n][f 1 3 65535][w][e]

[msg MSG_540_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4008 65535 0](仮)[f 4 2] じゃないか。[n]今日も冷えるな。[n][f 1 3 65535][w][e]

[msg MSG_541_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...せっかく会った機会だ。[n]お前に話したいことがある。[n][f 1 3 65535][w][e]

[sel SEL_542_0_0 top]
[s]どうした?[e]
[s]大丈夫か?[e]

[msg MSG_543_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 4021 65535 0]ああ、そうだな...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]いや...ここでは♀られるな。[n]すまないが、都合が良い時に会いに来てくれ。[n][f 1 3 65535][w][e]

[msg MSG_544_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 4037 65535 0]...どうだろうな。[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]それがだな...いや、ここでは♀られるな。[n]すまないが、時間がある時に会いに来てくれ。[n][f 1 3 65535][w][e]

[msg MSG_545_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0](仮)あ、[f 4 2] 君おはよう。[n]寒いね。[n][f 1 3 65535][w][e]

[msg MSG_546_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...あのね、その...[n]...ごめんね、なんか顔見れないや...[n][f 1 3 65535][w][e]

[sel SEL_547_0_0 top]
[s]どうした?[e]
[s]大丈夫か?[e]

[msg MSG_548_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]うん。[n]...お父様の事。[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...あのね、聞いて欲しい事があるの。[n]時間がある時でいいから、屋上に来て欲しいな。[n][f 1 3 65535][w][e]

[msg MSG_549_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]大丈夫...じゃ、[n]ない。かな。[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...あのね、聞いて欲しい事があるの。[n]時間がある時でいいから、屋上に来て欲しいな。[n][f 1 3 65535][w][e]

[msg MSG_550_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57021 65535 0]Bom Dia, [f 4 2]-senpai.[n][f 1 3 65535][w][e]

[msg MSG_551_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Então... hoje é o dia em que o Dr. Maruki[n]deve entrar em contato conosco...[n][f 1 3 65535][w][e]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hum...[n][f 1 3 65535][w][e]

[sel SEL_552_0_0 top]
[s]O que está errado?[e]
[s]Você está bem?[e]

[msg MSG_553_0_0 [Sumire]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 57031 65535 0]Oh, não é nada... eu só tenho muito em minha[n]mente...[n][f 1 3 65535][w][e]
[s][bup 0 10 3 65535 0][vp 8 2 0 0 65535 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Está tudo bem, não é nada. Devemos chegar à[n]escola agora.[n][f 1 3 65535][w][e]

[msg MSG_554_0_0 [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 57031 65535 0]Oh eu estou bem. Acabei de ter algo em minha[n]mente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu preciso pensar um pouco mais sobre isso.[n]Por enquanto, devemos chegar à escola.[n][f 1 3 65535][w][e]

[msg MSG_555_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57005 65535 0]Bom dia, Senpai.[n][f 1 3 65535][w][e]

[msg MSG_556_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 57045 65535 0]Todo dia é tão quente. Eu esvazio minha[n]garrafa de água tão rápido...[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A propósito, as férias de verão estão[n]chegando. Posso perguntar quais são seus planos,[n]Senpai?[n][f 1 3 65535][w][e]

[sel SEL_557_0_0 top]
[s]Não tenho nada.[e]
[s]E você?[e]

[msg MSG_558_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57119 65535 0]Oh, então você não é do tipo que faz planos[n]com antecedência, eu vejo![n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Então talvez tenhamos a chance de praticar[n]mais um pouco! Vou te dar uma instrução[n]adequada![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Avise-me sempre que estiver disponível,[n]Senpai![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oh, o trem está aqui. Vamos lá então![n][f 1 3 65535][w][e]

[msg MSG_559_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57073 65535 0]Estarei treinando principalmente com a[n]equipe de ginástica. E se eu tiver tempo[n]livre, estarei fazendo auto-treinamento![n][f 1 3 65535][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oh, você gostaria de se juntar a mim, Senpai?[n]Sempre que você está disponível, ficaria bem![n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oh, o trem está aqui. Vamos lá então![n][f 1 3 65535][w][e]

[msg MSG_560_0_0 [Maruki]]
[s][bup 0 216 301 65535 0][f 4 10 65535 0 0][vp 8 2 0 57403 65535 0]Bom dia para você.[n][f 1 3 65535][w][e]

[msg MSG_561_0_0 [Maruki]]
[s][bup 0 216 303 65535 0][f 4 10 65535 0 0][vp 8 2 0 57450 65535 0]Há muitos estudantes aqui a essa hora.[n]É revigorante fazer com que o trabalho[n]comaça em um momento diferente de vez em[n]quando.[n][f 1 3 65535][w][e]

[sel SEL_562_0_0 top]
[s]Atrasado?[e]
[s]Você dormiu demais?[e]

[msg MSG_563_0_0 [Maruki]]
[s][bup 0 216 301 65535 0][f 4 10 65535 0 0][vp 8 2 0 57457 65535 0]Hahaha. Você me pegou.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No meu caminho para o trabalho hoje,[n]encontrei essas velhinhas carregando uma[n]bagagem pesada. Três deles de fato.[n][f 1 3 65535][w][e]
[s][bup 0 216 303 65535 0][f 4 10 65535 0 0][vp 8 2 0 57430 65535 0]Então, eu estava oferecendo para ajudar a[n]carregar suas coisas, mas depois minhas[n]costas fizeram o som que não deveria[n]fazer...[n][f 1 3 65535][w][e]
[s][bup 0 216 300 65535 0][f 4 10 65535 0 0][vp 8 2 0 57430 65535 0]...Bom, de qualquer forma! Você já ouviu as[n]notícias de Yoshizawa-san?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Estou tão feliz por ela. Isso me faz sentir[n]vontade de fazer o meu melhor também![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Claro, ao dizer isso, estou atrasado.[n][f 1 3 65535][w][e]
[s][bup 0 216 301 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bem, ei, todos nós precisamos mudar de vez[n]em quando! Então, vamos fazer o nosso[n]melhor para hoje, não é?[n][f 1 3 65535][w][e]

[msg MSG_564_0_0 [Maruki]]
[s][bup 0 216 304 65535 0][f 4 10 65535 0 0][vp 8 2 0 57457 65535 0]Claro que não, eu definitivamente acordei na[n]hora... embora eu esteja atrasado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No meu caminho para o trabalho hoje,[n]encontrei essas velhinhas carregando uma[n]bagagem pesada. Três deles de fato.[n][f 1 3 65535][w][e]
[s][bup 0 216 303 65535 0][f 4 10 65535 0 0][vp 8 2 0 57430 65535 0]Então, eu estava oferecendo para ajudar a[n]carregar suas coisas, mas depois minhas[n]costas fizeram o som que não deveria[n]fazer...[n][f 1 3 65535][w][e]
[s]s [n][bup 0 216 300 65535 0][f 4 10 65535 0 0][vp 8 2 0 57430 65535 0]...Bom, de qualquer forma! Você já ouviu as[n]notícias de Yoshizawa-san?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Estou tão feliz por ela. Isso me faz sentir[n]vontade de fazer o meu melhor também![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Claro, ao dizer isso, estou atrasado.[n][f 1 3 65535][w][e]
[s][bup 0 216 301 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bem, ei, todos nós precisamos mudar de vez[n]em quando! Então, vamos fazer o nosso[n]melhor para hoje, não é?[n][f 1 3 65535][w][e]

[msg MSG_565_0_0 [Sumire]]
[s][bup 0 10 901 65535 0][f 4 10 65535 0 0][vp 8 2 0 57021 65535 0]Bom Dia, [f 4 2]-senpai.[n][f 1 3 65535][w][e]

[msg MSG_566_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 2 0 57113 65535 0]Nós garantimos uma rota para o tesouro.[n]Agora só temos que esperar...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Recebo o plano, mas ainda não consigo me[n]acalmar.[n][f 1 3 65535][w][e]
[s][bup 0 10 900 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hum, se tivermos tempo, poderíamos ir a[n]lembranças?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu gostaria que você tivesse mais dicas[n]sobre como lutar no metaverso...[n][f 1 3 65535][w][e]

[sel SEL_567_0_0 top]
[s]Tudo bem.[f 2 7 0 1 971 1][e]
[s]Vou pensar sobre isso.[e]

[msg MSG_568_0_0 [Sumire]]
[s][bup 0 10 901 65535 0][f 4 10 65535 0 0][vp 8 2 0 57039 65535 0]Sério? Muito obrigado![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Estou na melhor forma agora, então, por[n]favor, seja o mais duro em mim possível![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Estarei esperando depois da escola então.[n][f 1 3 65535][w][e]

[msg MSG_569_0_0 [Sumire]]
[s][bup 0 10 900 65535 0][f 4 10 65535 0 0][vp 8 2 0 57186 65535 0]Certo! Sempre que você tiver tempo, ficaria[n]bem.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Estou na melhor forma agora, para que eu[n]possa ir a qualquer momento.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu estarei esperando então.[n][f 1 3 65535][w][e]

[msg MSG_570_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0]Mornin '.[n][f 1 3 65535][w][e]

[msg MSG_571_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7184 65535 0]O grande dia está quase aqui.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bem, fizemos tudo o que podemos, então agora[n]apenas temos esperar...[n][f 1 3 65535][w][e]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você tem algum plano hoje? Se você vai[n]treinar em lembranças, eu vou te entrar.[n][f 1 3 65535][w][e]

[sel SEL_572_0_0 top]
[s]Acho que podemos treinar.[f 2 7 0 1 971 1][e]
[s]Vou pensar sobre isso.[e]

[msg MSG_573_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7045 65535 0]Sim! Eu tive uma sensação de que você diria[n]isso![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Não temos idéia de como essa luta vai[n]acabar, então não pode doer ser o mais[n]forte possível![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tudo bem, te vejo depois da escola. Vou[n]dormir bem na aula e economizar minha[n]energia![n][f 1 3 65535][w][e]

[msg MSG_574_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7194 65535 0]Deveríamos realmente ir, cara. Você não quer[n]entrar em pânico mais tarde porque estamos[n]despreparados.[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você sabe o que eles dizem. Sem uso chorando[n]sobre refrigerante derramado... ou algo[n]assim.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]De qualquer forma, deixe-me saber se estamos[n]nos reunindo no esconderijo. Eu estarei[n]esperando![n][f 1 3 65535][w][e]

[msg MSG_575_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57005 65535 0]Bom Dia.[n][f 1 3 65535][w][e]

[msg MSG_576_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 57173 65535 0]... Senpai, você está dormindo bem?[n]Você parece meio cansado...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pode não ser o meu lugar para perguntar,[n]mas... Você está bem?[n][f 1 3 65535][w][e]

[sel SEL_577_0_0 top]
[s]Estou bem.[e]
[s]O que você quer dizer?[e]

[msg MSG_578_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57027 65535 0]Bem... tudo bem então.[n][f 1 3 65535][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, isso me lembra! O festival escolar é[n]amanhã, não é?[n][f 1 3 65535][w][e]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu não tinha ideia de que os preparativos[n]levariam muito trabalho... subestimei.[n][f 1 3 65535][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas trabalhar com todos para montar tudo é[n]ótimo...[n]Espero que todos nos divertimos amanhã.[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, eu vou fazer algum treinamento hoje,[n]então, por favor, com licença![n][f 1 3 65535][w][e]

[msg MSG_579_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57029 65535 0]Hum... não importa, não é nada.[n][f 1 3 65535][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Isto me lembra! Amanhã é o festival escolar,[n]não é?[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sua aula terminou com os preparativos?[n]É meio bom trabalhar com todos para juntar[n]todas as coisas...[n][f 1 3 65535][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Espero que todos nos divertimos amanhã.[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, eu vou fazer algum treinamento hoje,[n]então, por favor, com licença![n][f 1 3 65535][w][e]

[msg MSG_580_0_0 [Akechi]]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 8005 65535 0]... mm, bom dia, [f 4 2]. Eu estava trabalhando tarde ontem, então[n]estou cansado hoje.[n][f 1 3 65535][w][e]

[msg MSG_581_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]Eu confio que você não se esqueceu do prazo?[n]Vou dar tudo o que tenho, por sua causa[n]também.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Além disso, uma vez que os ladrões Phantom[n]terminarem este emprego final, acho que não[n]vou mais ver você como isso em particular.[n][f 1 3 65535][w][e]

[sel SEL_582_0_0 top]
[s]Sério?[e]
[s]O que você quer dizer?[e]

[msg MSG_583_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8038 65535 0]Não me interpretem mal, era tempo bem gasto.[n]Uma parte de mim é triste ver isso[n]terminando.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Mas depois que você se dissolveu, todo mundo[n]ficará ocupado procurando o culpado por[n]trás dos colapsos psicóticos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Até que isso aconteça, vamos continuar[n]trabalhando juntos. Agora então, eu vou.[n][f 1 3 65535][w][e]

[msg MSG_584_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Quero dizer, é exatamente como isso soa.[n][f 1 3 65535][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Depois de se dissipar, todo mundo estará[n]ocupado rastreando o culpado por trás dos[n]colapsos psicóticos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Até que isso aconteça, vamos continuar[n]trabalhando juntos. Agora então, eu vou.[n][f 1 3 65535][w][e]

[msg MSG_585_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8005 65535 0]... mm, bom dia, [f 4 2]. Eu estava trabalhando tarde ontem, então[n]estou cansado hoje.[n][f 1 3 65535][w][e]

[msg MSG_586_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]Oh, está certo. O prazo final está se[n]aproximando.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]... Uma vez que os ladrões fantasmas[n]terminam este trabalho final, acredito que[n]nosso acordo será concluído também.[n][f 1 3 65535][w][e]

[sel SEL_587_0_0 top]
[s]Eu penso que sim.[e]
[s]O que você quer dizer?[e]

[msg MSG_588_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Certamente era tempo bem gasto, e eu gostei.[n]Uma parte de mim é triste ver isso[n]terminando.[n][f 1 3 65535][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Mas nenhum de nós terá mais nada a ganhar,[n]então não há muito ponto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]De qualquer forma, vamos continuar[n]trabalhando juntos até então.[n][f 1 3 65535][w][e]

[msg MSG_589_0_0 [Akechi]]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Haha, eu quis dizer exatamente como isso[n]soou.[n][f 1 3 65535][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quero dizer, uma vez que os ladrões Phantom[n]se foram, nosso acordo não terá nenhum[n]significado. Não é certo?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]É triste, mas é assim que é. De qualquer[n]forma, vamos continuar trabalhando juntos[n]até então.[n][f 1 3 65535][w][e]

[msg MSG_590_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 53343 65535 0]Bom Dia.[n][f 1 3 65535][w][e]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu tenho pensado muito em personas e[n]palácios desde ontem...[n][f 1 3 65535][w][e]

[msg MSG_591_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2047 65535 0]Esse banco flutuante realmente reflete a[n]personalidade de Kaneshiro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ele está voando para que ninguém possa[n]rastrear seus passos. Ele não confia em[n]ninguém.[n][f 1 3 65535][w][e]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Certamente explica por que a segurança era[n]tão apertada.[n][f 1 3 65535][w][e]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 53306 65535 0]De qualquer forma, tudo o que resta é o[n]cartão de visita.[n]Quando você vai enviar?[n][f 1 3 65535][w][e]

[sel SEL_592_0_0 top]
[s]Vamos enviar hoje.[f 2 7 0 1 971 1][e]
[s]Ainda estou esperando.[e]

[msg MSG_593_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2023 65535 0]Tudo bem. Vou fazer meus próprios[n]preparativos.[n][f 1 3 65535][w][e]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não podemos deixar que essa vida baixa[n]continue fazendo o que quiser.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Vamos mudar seu coração, não importa o quê.[n]Ok, te vejo depois da escola.[n][f 1 3 65535][w][e]

[msg MSG_594_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2020 65535 0]Tudo bem. Ainda temos tempo... suponho que[n]não seria bom se apressar nas coisas.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu sou livre depois da escola. Estarei[n]pronto para ir a qualquer hora.[n][f 1 3 65535][w][e]

[msg MSG_595_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 53343 65535 0]Bom Dia.[n][f 1 3 65535][w][e]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu tenho pensado muito em personas e[n]palácios desde ontem...[n][f 1 3 65535][w][e]

[msg MSG_596_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2047 65535 0]Esse banco flutuante realmente reflete a[n]personalidade de Kaneshiro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ele está voando para que ninguém possa[n]rastrear seus passos... ele não confia em[n]ninguém.[n][f 1 3 65535][w][e]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Certamente explica por que a segurança era[n]tão apertada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nós fizemos tudo o que podemos, no entanto.[n]Agora só temos que esperar que Kaneshiro[n]realmente mude de coração.[n][f 1 3 65535][w][e]

[sel SEL_597_0_0 top]
[s]Isso vai acontecer.[e]
[s]Preocupado?[e]

[msg MSG_598_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2048 65535 0]Parece verdade, quando ouço você dizer isso.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Depois de todo o esforço que fazemos, sei[n]que as coisas vão ficar bem.[n][f 1 3 65535][w][e]

[msg MSG_599_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 2028 65535 0]Bem, um pouco. Toda essa conversa sobre[n]palácios ou corações mudando... está tão[n]fora de contato com a realidade.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas depois de todo o esforço que fazemos,[n]sei que as coisas vão ficar bem.[n][f 1 3 65535][w][e]

[msg MSG_600_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54473 65535 0][f 4 2]...[n][f 1 3 65535][w][e]

[msg MSG_601_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54499 65535 0]Tudo bem se você não estiver preocupado, mas[n]você vai se queimar se for empolgado.[n][f 1 3 65535][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não há muito tempo até o prazo.[n]Eu acredito que você pretende ir a[n]lembranças hoje?[n][f 1 3 65535][w][e]

[sel SEL_602_0_0 top]
[s]É claro.[f 2 7 0 1 971 1][e]
[s]Estou pensando sobre isso.[e]

[msg MSG_603_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54502 65535 0]Em seguida, nos encontraremos no lugar[n]habitual depois da escola.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0][f 4 10 65535 0 0]Já disse isso muitas vezes, mas estamos[n]ficando sem tempo. Eu acredito que seria[n]apropriado entrar em pânico um pouco aqui.[n][f 1 3 65535][w][e]

[msg MSG_604_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54494 65535 0]Tch. Você simplifica...[n][f 1 3 65535][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Já disse isso muitas vezes, mas estamos[n]ficando sem tempo. Se você está ficando com[n]pés frios, fale agora.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas se você tiver vontade de lutar, ligue[n]para uma assembléia no esconderijo. Temos[n]que ir para lembranças.[n][f 1 3 65535][w][e]

[msg MSG_605_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57021 65535 0]... Senpai, bom dia.[n][f 1 3 65535][w][e]

[msg MSG_606_0_0 [Sumire]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 57033 65535 0]Você se lembra do nosso prazo com o Dr.[n]Maruki, certo?[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Eu sei que você provavelmente já tem um[n]plano, mas estamos com pouco tempo...[n]poderíamos ir ao palácio hoje?[n][f 1 3 65535][w][e]

[sel SEL_607_0_0 top]
[s]Vamos.[f 2 7 0 1 971 1][e]
[s]Deixe-me pensar sobre isso.[e]

[msg MSG_608_0_0 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57026 65535 0]Ok! Estou todo pronto para o meu fim![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Nos encontraremos depois da escola então.[n]Por favor, dê-me licença![n][f 1 3 65535][w][e]

[msg MSG_609_0 [Sumire]]
[s][bup 0 10 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 57060 65535 0]Senpai... hoje é o nosso último dia, no[n]entanto.[n][f 1 3 65535][w][e]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Precisamos ir hoje! Estarei esperando ouvir[n]de você depois da escola![n][f 1 3 65535][w][e]

[msg MSG_610_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54053 65535 0]Manhã.[n][f 1 3 65535][w][e]

[msg MSG_611_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6058 65535 0]Diga, o que você acha que está acontecendo[n]com Kamoshida? Nós roubamos seu tesouro,[n]mas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu me pergunto se realmente mudamos de[n]coração.[n]Você acha que ele realmente expiará seus[n]crimes?[n][f 1 3 65535][w][e]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E se ele não mudar?[n][f 1 3 65535][w][e]

[sel SEL_612_0_0 top]
[s]Tendo problemas para acreditar?[e]
[s]Deve funcionar.[e]

[msg MSG_613_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6166 65535 0]Não é isso. Estou apenas ansioso...[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bem, acho que tudo o que podemos fazer é[n]esperar e esperar. Tudo bem, o suficiente[n]com a atitude negativa![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu tenho que ver seu coração mudar, com meus[n]próprios olhos, e ele responderá pelo que[n]fez![n][f 1 3 65535][w][e]

[msg MSG_614_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6186 65535 0]...Você tem razão.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu continuo pensando no pior cenário. Eu[n]tenho que acreditar que vai funcionar.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu tenho que ver seu coração mudar, com meus[n]próprios olhos, e ele responderá pelo que[n]fez![n][f 1 3 65535][w][e]

[msg MSG_615_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54250 65535 0]Wassup.[n][f 1 3 65535][w][e]

[msg MSG_616_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 7192 65535 0]Nós realmente vamos ficar bem? A exposição é[n]apenas até este fim de semana.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Temos que mudar seu coração antes que ele[n]termine, certo? Nós não teremos tempo[n]suficiente nesse ritmo![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Devemos ir ao palácio hoje![n]Vamos, vamos nos encontrar depois da escola![n][f 1 3 65535][w][e]

[sel SEL_617_0_0 top]
[s]Vamos fazer isso.[f 2 7 0 1 971 1][e]
[s]Ainda estamos bem.[e]

[msg MSG_618_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7045 65535 0]Sim! Temos que arrancar a máscara deste[n]artista falso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos nos encontrar depois da escola então![n]Eu estarei esperando![n][f 1 3 65535][w][e]

[msg MSG_619_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7189 65535 0]Cara, ainda não somos bons! Não fizemos[n]nenhum progresso![n][f 1 3 65535][w][e]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Meu intestino está me dizendo que o palácio[n]é um problema.[n]Temos que investigar enquanto ainda há tempo![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Deixe-me saber quando você estiver pronto[n]para ir, tudo bem? Eu estarei esperando.[n][f 1 3 65535][w][e]

[msg MSG_620_0_0 [Maruki]]
[s][bup 0 216 301 65535 0][f 4 10 65535 0 0][vp 8 2 0 57401 65535 0]Bom dia para você.[n][f 1 3 65535][w][e]

[msg MSG_621_0_0 [Maruki]]
[s][bup 0 216 300 65535 0][f 4 10 65535 0 0][vp 8 2 0 57521 65535 0]Há muitos estudantes aqui a essa hora.[n]É revigorante fazer com que o trabalho[n]comaça em um momento diferente de vez em[n]quando.[n][f 1 3 65535][w][e]

[sel SEL_622_0_0 top]
[s]Atrasado?[e]
[s]Você dormiu demais?[e]

[msg MSG_623_0_0 [Maruki]]
[s][bup 0 216 300 65535 0][f 4 10 65535 0 0][vp 8 2 0 57453 65535 0]Hahaha... você me pegou.[n][f 1 3 65535][w][e]
[s][bup 0 216 303 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No meu caminho para o trabalho hoje,[n]encontrei essas velhinhas carregando uma[n]bagagem pesada. Três deles de fato.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Então, eu estava oferecendo para ajudar a[n]carregar suas coisas, mas depois minhas[n]costas fizeram o som que não deveria[n]fazer...[n][f 1 3 65535][w][e]
[s][bup 0 216 300 65535 0][f 4 10 65535 0 0][vp 8 2 0 57422 65535 0]...Bom, de qualquer forma! Você já ouviu as[n]notícias de Yoshizawa-san?[n][f 1 3 65535][w][e]

[msg MSG_624_0_0 [Maruki]]
[s][bup 0 216 300 65535 0][f 4 10 65535 0 0][vp 8 2 0 57423 65535 0]Claro que não. Eu acordei na hora...[n]Embora eu esteja atrasado.[n][f 1 3 65535][w][e]
[s][bup 0 216 303 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No meu caminho para o trabalho hoje,[n]encontrei essas velhinhas carregando uma[n]bagagem pesada. Três deles de fato.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Então, eu estava oferecendo para ajudar a[n]carregar suas coisas, mas depois minhas[n]costas fizeram o som que não deveria[n]fazer...[n][f 1 3 65535][w][e]
[s][bup 0 216 300 65535 0][f 4 10 65535 0 0][vp 8 2 0 57422 65535 0]...Bom, de qualquer forma! Você já ouviu as[n]notícias de Yoshizawa-san?[n][f 1 3 65535][w][e]

[msg MSG_625_0_0 [Maruki]]
[s][bup 0 216 301 65535 0][f 4 10 65535 0 0][vp 8 2 0 57517 65535 0]Estou tão feliz por ela. Isso me faz sentir[n]vontade de fazer o meu melhor também![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Claro, ao dizer isso, estou atrasado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bem, ei, todos nós precisamos mudar de vez[n]em quando! Então, vamos fazer o nosso[n]melhor para hoje, não é?[n][f 1 3 65535][w][e]

