[msg SYS_000_0_0]
[s]Deseja retomar o jogo?[n][w][e]

[sel SEL_001_0_0 top]
[s]Reinicie a batalha[e]
[s]Comece de novo na Praça Shibuya[e]
[s]Recomece na entrada do templo[e]
[s]Reinicie a infiltração[e]
[s]Volte para a manhã anterior[e]
[s]De volta a uma semana atrás[e]
[s]Voltar para a tela inicial[e]

[sel SEL_001_0_0_3rd top]
[s]Reinicie a batalha[e]
[s]Recomeçar a partir da entrada do Palácio[e]
[s]Volte para a sala segura anterior[e]
[s]Reinicie a infiltração[e]
[s]Volte para a manhã anterior[e]
[s]De volta a uma semana atrás[e]
[s]Voltar para a tela inicial[e]

[sel SEL_001_0_0_AT top]
[s]Reinicie a batalha[e]
[s]Recomece a partir da entrada do Memento[e]
[s]Recomeçar a partir da última sala de espera[e]
[s]Recomeçar a partir da área anterior[e]
[s]Volte para a manhã anterior[e]
[s]De volta a uma semana atrás[e]
[s]Voltar para a tela inicial[e]

[msg SEL_001_1_0_A]
[s]Ritorna al momento dell'ingresso[n]nella Stazione di Shibuya (piazza).[n]Conserverai solo il denaro e i PE.[n][w][e]
[s]Você quer sair da praça[n]da estação de Shibuya?[n][w][e]

[msg SEL_001_1_0_3rd_A]
[s]Volte ao momento de entrada[n]no Palácio. Você só manterá[n]o dinheiro e o XP.[n][w][e]
[s]Você começa de novo a partir da entrada do[n]Palácio?[n][w][e]

[msg SEL_001_1_0_AT_A]
[s]Retorne ao momento de inserir Mementos. Você[n]manterá apenas o dinheiro e o XP.[n][w][e]
[s]Deseja reiniciar a partir da entrada do Memento?[n][w][e]

[msg SEL_001_1_0_B]
[s]Retorne ao momento de entrada no Santuário. Você[n]manterá apenas o dinheiro e o XP.[n][w][e]
[s]Você quer começar de novo da entrada[n]do santuário?[n][w][e]

[msg SEL_001_1_0_3rd_B]
[s]Retorne ao entrar na sala segura. Você manterá[n]apenas o dinheiro e o XP.[n][w][e]
[s]Deseja reiniciar a partir da Sala Segura?[n][w][e]

[msg SEL_001_1_0_AT_B]
[s]Retorne ao entrar na sala de espera. Você manterá[n]apenas o dinheiro e o XP.[n][w][e]
[s]Deseja reiniciar a partir da sala de espera?[n][w][e]

[msg SEL_001_1_0_C]
[s]Ao fazer isso, você retornará à[n]tela inicial e perderá todo[n]o progresso não salvo. Você confirma?[n][w][e]

[msg SEL_001_1_0_D]
[s]Retorne ao momento antes da infiltração. Você[n]manterá apenas o dinheiro e o XP.[n][w][e]
[s]Deseja reiniciar após a infiltração?[n][w][e]

[sel SEL_YES_NO top]
[s]Sim[e]
[s]Não[e]

