[msg MSG_NET_1ST_01 [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Heheheh... bem-vindo ao sedutor[n]World of Tanaka Shady Commodities![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Este site usa texto em fala para[n]Uma compra facil de entender[n]experiencia![n][w][e]

[msg MSG_YamiNet_TutorialEnd [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Esqueca qualquer duvida boba ou ceticismo[n]Voce pode ter e apenas se inscrever agora![n][w][e]

[msg MSG_NET_1ST_02 [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bem-vindo! Isso e sombrio de Tanaka[n]Mercadorias![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Basta registrar uma conta para desfrutar[n]o mundo atraente de Tanaka e sombrio[n]Mercadorias.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Esqueca qualquer duvida boba ou ceticismo[n]Voce pode ter e apenas se inscrever agora![n][w][e]

[msg MSG_YamiNet_MemberQ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Este site e incrivelmente sombrio...[n]Entao, voce vai se inscrever?[n][w][e]

[msg MND_YamiNet_MemberQ]
[s]Devo fazer uma conta?[n][w][e]

[sel SEL_NET_1ST_YES_NO top]
[s]Vamos nos inscrever.[e]
[s]Nao, e melhor nao.[e]

[msg MSG_NET_1ST_NO [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh que vergonha! Que pena![n]Mas, por favor, volte![n][w][e]

[msg MSG_NAME_CHANGE_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 22 65535 3 22]... e uma boa ideia usar seu nome verdadeiro[n]Em um site como este?[n][w][e]

[sel SEL_NAME_CHANGE_ON_OFF_M top]
[s]Esta bem.[e]
[s]Vou usar o Joker.[e]

[msg MSG_NAME_CHANGE_02 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nao sei. Dando seu nome verdadeiro em[n]Este site me parece bastante arriscado... mas e[n]voce decide.[n][w][e]

[msg MSG_NAME_CHANGE_03 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Seu nome de codigo, hein? Essa e uma boa ideia.[n][w][e]

[msg MSG_NAME_CHANGE_ON_01]
[s][vp 8 2 1 0 65535 0]Que nome deve[n]Eu me inscrevo?[n][w][e]

[sel SEL_NAME_CHANGE_ON_OFF top]
[s]Vou usar meu nome verdadeiro.[e]
[s]Eu vou com "Joker".[e]

[msg MSG_NET_1ST_SHOP [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Obrigado por inscrever-se! Bem-vindo ao[n]As mercadorias sombreadas de Tanaka![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Senhor.[f 4 1], voce abriu o[n]porta para possibilidades que as pessoas normais[n]so pode sonhar![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Agora, voce pode encontrar todos os itens raros[n]Voce poderia querer![n][w][e]

[msg MSG_NET_1ST_SHOP_NAME_CH [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Obrigado por inscrever-se! Bem-vindo ao[n]As mercadorias sombreadas de Tanaka![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sr. Joker, voce abriu a porta para[n]possibilidades que as pessoas normais podem[n]Apenas sonho de![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Agora, voce pode encontrar todos os itens raros[n]Voce poderia querer![n][w][e]

[msg MSG_NET_SHOP_IN [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bem-vindo! Isso e sombrio de Tanaka[n]Mercadorias![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Senhor.[f 4 1], voce abriu o[n]porta para possibilidades que as pessoas normais[n]so pode sonhar![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Agora, voce pode encontrar todos os itens raros[n]Voce poderia querer![n][w][e]

[msg MSG_NET_SHOP_IN_NAME_CHA [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bem-vindo! Isso e sombrio de Tanaka[n]Mercadorias![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sr. Joker, voce abriu a porta para[n]possibilidades que as pessoas normais podem[n]Apenas sonho de![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Agora, voce pode encontrar todos os itens raros[n]Voce poderia querer![n][w][e]

[msg MSG_NET_NO_BUY_END_YN [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ha algo que voce esqueceu de obter?[n]Certifique-se de nao perder[n]nada![n][w][e]

[sel SEL_NET_BUY_YES_NO top]
[s]Cancelar compra[e]
[s]Continue olhando[e]

[msg MSG_TRANSPORT [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bem-vindo! Isso e sombrio de Tanaka[n]Mercadorias![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Seu pedido esta a caminho. Deveria ser[n]chegando em breve.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nos esperamos te ver novamente em breve![n][w][e]

[msg MSG_SOLDOUT [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bem-vindo! Isso e sombrio de Tanaka[n]Mercadorias![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Atualmente, estamos todos esgotados![n]Pedimos desculpas sinceramente.[n]Lamentamos muito desaponta-lo![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nos esperamos te ver novamente em breve![n][w][e]

[msg MSG_RANK_UP_00 [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Boas noticias, Sr.[f 4 1]![n][w][e]

[msg MSG_RANK_UP_00_NAME_CHAN [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Boas noticias, Sr. Joker![n][w][e]

[msg MSG_RANK_BLACK [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O que voce ja gastou[n]10000 ienes![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sua classificacao de membros agora esta preta![n]Agora voce pode comprar todos os nossos[n]Produtos de camada preta![n][w][e]

[msg MSG_RANK_BLACK_NAME_CHAN [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O que voce ja gastou[n]10000 ienes![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sua classificacao de membros agora esta preta![n]Agora voce pode comprar todos os nossos[n]Produtos de camada preta![n][w][e]

[msg MSG_RANK_UP_01 [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas isso nao e tudo...![n][w][e]

[msg MSG_RANK_DARK [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce gastou mais de 50000 ienes![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sua classificacao de membros esta agora escura![n]Agora voce pode comprar todos os nossos[n]Produtos de camada escura![n][w][e]

[msg MSG_RANK_DARK_NAME_CHANG [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce gastou mais de 50000 ienes![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sua classificacao de membros esta agora escura![n]Agora voce pode comprar todos os nossos[n]Produtos de camada escura![n][w][e]

[msg MSG_RANK_UP_02 [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas espere, ha mais...![n][w][e]

[msg MSG_RANK_CHAOS [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce gastou mais de 100.000 ienes![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sua classificacao de membros agora e caos![n]Agora voce pode comprar todos os nossos[n]Produtos de caos![n][w][e]

[msg MSG_RANK_CHAOS_NAME_CHAN [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce gastou mais de 100.000 ienes![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sua classificacao de membros agora e caos![n]Agora voce pode comprar todos os nossos[n]Produtos de caos![n][w][e]

[msg MSG_RANK_Max [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce alcancou nosso membro mais alto[n]classificacao, entao esta e a nossa formacao completa. Nao podemos[n]Obrigado o suficiente![n][w][e]

[msg MSG_NO_RANK_UP [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ate agora voce gastou um total de[n][var 0]Yen![n][w][e]

[msg MSG_NO_RANK_UP_NAME_CHAN [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ate agora voce gastou um total de[n][var 0]Yen![n][w][e]

[msg MSG_SHOP_BUY [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Seu pedido chegara em breve. Nos[n]Entenda sua emocao, mas[n]Pedimos sua paciencia![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nos esperamos te ver novamente em breve![n][w][e]

[msg MSG_SHOP_END [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nos esperamos te ver novamente em breve![n][w][e]

[msg MSG_Kokuti_1GATU [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Estaremos passando por servidor[n]manutencao a partir de 31/01,[n]Entao, estaremos fora de servico![n][w][e]

[msg MSG_Kokuti_Saigo [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Estaremos passando por servidor[n]manutencao a partir de amanha,[n]1/31, entao estaremos fora de servico![n][w][e]

[msg MSG_Yami_Siyouhuka [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]"Passando manutencao do servidor", hein...[n]Parece que nao podemos usar o site.[n][w][e]

