[msg D07_BRIEFING_090_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Nos caminhamos ate as duas extremidades de[n]o navio, entao devemos ter uma boa ideia[n]do seu tamanho.[n][w][e]

[msg D07_BRIEFING_090_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sim. Pode haver outras passagens e[n]corredores se ramificando, mas sabemos o[n]layout geral agora.[n][w][e]

[msg D07_BRIEFING_090_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Estamos bastante acostumados a nos transformar em ratos[n]Neste ponto tambem. Tenho certeza que ficaremos bem[n]Se continuarmos assim![n][w][e]

