[msg dummy_mes]
[s]......[n][w][e]

[msg D01_03_PT_30000_01_PC02_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos la, vamos encontrar essa coisa do tesouro![n][w][e]

[msg D01_03_PT_30000_01_PC03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos continuar em busca do tesouro![n][w][e]

[msg D01_03_PT_30000_02_PC02_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cara, toda essa merda com as fantasias e o[n]Os nomes de codigo me deixaram muito empolgado.[n][w][e]

[msg D01_03_PT_30000_02_PC03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos garantir que tenhamos cuidado com o[n]Sombras enquanto avancamos.[n][w][e]

[msg D01_03_PT_30000_03_PC02_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Voce pode deixar a luta para mim![n][w][e]

[msg D01_03_PT_30000_03_PC03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Skull na verdade nao e tao ruim em lutar.[n]Ele pode ser apenas um diamante em bruto.[n][w][e]

[msg D01_04_PT_40000_01_PC02_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos la, vamos encontrar essa coisa do tesouro![n][w][e]

[msg D01_04_PT_40000_01_PC03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos continuar em busca do tesouro![n][w][e]

[msg D01_04_PT_40000_01_PC04_ [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Queremos procurar o tesouro,[n]certo? Vamos explorar.[n][w][e]

[msg D01_04_PT_40000_02_PC02_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cara, toda essa merda com as fantasias e o[n]Os nomes de codigo me deixaram muito empolgado.[n][w][e]

[msg D01_04_PT_40000_02_PC03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos garantir que tenhamos cuidado com o[n]Sombras enquanto avancamos.[n][w][e]

[msg D01_04_PT_40000_02_PC04_ [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entao este e o mundo de Kamoshida... mas e[n]Na verdade, a escola, certo?[n][w][e]

[msg D01_04_PT_40000_03_PC02_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Voce pode deixar a luta para mim![n][w][e]

[msg D01_04_PT_40000_03_PC03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Skull na verdade nao e tao ruim em lutar. Ele[n]Pode ser apenas um diamante em bruto.[n][w][e]

[msg D01_04_PT_40000_03_PC04_ [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pantera, hein... eu acho que talvez seja capaz de[n]Acostume-se a isso.[n][w][e]

[msg D01_ex_PT_60000_01_PC02_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Temos que roubar esse tesouro, nao importa[n]o que![n][w][e]

[msg D01_ex_PT_60000_01_PC03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O tesouro deve ser o nosso foco principal[n]hoje![n][w][e]

[msg D01_ex_PT_60000_01_PC04_ [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Precisamos fazer isso![n][w][e]

[msg D01_ex_PT_60000_02_PC02_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece o controle de seguranca da seguranca...[n]Mas nos conseguimos isso![n][w][e]

[msg D01_ex_PT_60000_02_PC03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tenho certeza que podemos ter sucesso se apenas usarmos[n]A rota de infiltracao![n][w][e]

[msg D01_ex_PT_60000_02_PC04_ [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos nos apressar e seguir para o tesouro![n][w][e]

[msg D01_ex_PT_60000_03_PC02_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nao temos que lutar hoje. Vamos so[n]Va para o tesouro![n][w][e]

[msg D01_ex_PT_60000_03_PC03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nao perca tempo lutando hoje,[n]Compreendo?[n][w][e]

[msg D01_ex_PT_60000_03_PC04_ [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nos so precisamos ir para o tesouro, certo?[n]Vamos nos apressar para onde esta![n][w][e]

[msg D01_02_target_mes10 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Primeiras coisas primeiro... temos que procurar por aqueles[n]Caras que vimos nas celulas.[n][w][e]

[msg D01_02_target_mes20 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nos realmente temos que encontrar aqueles caras que eram[n]trancado...[n][w][e]
[s]Ele estava falando sobre um "salao de treinamento de[n]Amor, "Certo? E melhor encontrarmos esse lugar.[n][w][e]

[msg D01_02_target_mes30 [Morgana]]
[s][bup 0 3 0 65535 0]Voce atingiu seu objetivo, certo? Ok, vamos pegar[n]fora daqui![n][w][e]

[msg D01_03_D151_01_target01_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Temos que encontrar a localizacao deste chamado[n]Tesouro.[n][w][e]

[msg D01_03_D151_01_target01__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Para fazer isso, procuraremos o predio![n][w][e]

[msg D01_03_D151_02_target01_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nao e... estranhamente barulhento?[n][w][e]

[msg D01_03_D151_02_target01__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu ouco vozes la...[n][w][e]
[s]E... eu posso sentir uma sombra. Voces dois,[n]tome cuidado.[n][w][e]

[msg D01_03_D151_02_target02_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nao esperava ver Kamoshida certa[n]Quando entramos.[n][w][e]

[msg D01_03_D151_02_target02__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Seria impossivel passar pelo[n]Hall Central. Vamos verificar em outro lugar.[n][w][e]

[msg D01_03_D151_02_target03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos pesquisar completamente o castelo.[n][w][e]
[s][clr 2]Concentrado[clr 27]e olhe em volta. Veja se voce[n]Encontre qualquer coisa suspeita.[n][w][e]

[msg D01_03_D151_14_target01_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Estou surpreso que voce tenha encontrado isso.[n][w][e]

[msg D01_03_D151_14_target01__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Voce era realmente[clr 2]concentrando-se[clr 27]como voce[n]visto. Voce tem um talento especial para isso, Joker.[n][w][e]
[s]Vamos continuar avancando, mantendo[n]Um olho em lugares especiais como esse.[n][w][e]

[msg D01_03_D151_14_target02_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se fizermos bom uso da capa, podemos[n]infiltrar-se com mais seguranca.[n][w][e]

[msg D01_03_D151_14_target02__2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Agora estamos falando. Isso e totalmente fantasma[n]ladrao-ish.[n][w][e]
[s]Vamos continuar assim![n][w][e]

[msg D01_03_D151_03_target01_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este lugar parece um castelo...[n]E diferente do underground.[n][w][e]

[msg D01_03_D151_03_target01__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sim. Esta e uma area que eu nao consegui[n]ao redor da pesquisa.[n][w][e]
[s]Nao entre cegamente. Siga em frente[n]com cuidado, ficando de olho para[n]qualquer coisa suspeita.[n][w][e]

[msg D01_03_D151_03_target02_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker. Vamos descansar na sala segura que[n]descoberto.[n][w][e]

[msg D01_03_D151_51_target01_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Estamos lutando muito mais do que eu[n]esperado... estou coco.[n][w][e]

[msg D01_03_D151_51_target01__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nos apenas comecamos.[n][w][e]
[s]Vamos descansar um pouco. Depois disso, podemos[n]Discuta para onde ir daqui, Joker.[n][w][e]

[msg D01_03_D151_51_target02_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entao, apenas temos que pegar esse "tesouro".[n]certo?[n][w][e]

[msg D01_03_D151_51_target02__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sim. E para fazer isso, teremos que manter[n]investigando o castelo.[n][w][e]

[msg D01_03_D151_51_target03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Isso era Lady Ann! Temos que ir ajuda-la![n][w][e]

[msg D01_03_D151_51_target03__2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Louco... mas, novamente, acho que faz[n]sentir que ela estaria por perto.[n][w][e]
[s]Enfim, vamos sair aqui![n][w][e]

[msg D01_03_D151_03_target10_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nao de a tona! Deste jeito! Pressa![n][w][e]

[msg D01_03_D151_03_target10__2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh puxa. Vamos la![n][w][e]

[msg D01_03_D151_03_target20_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lady Ann esta conosco agora! Vamos escapar,[n]Evitando a batalha o maximo possivel![n][w][e]

[msg D01_03_D151_03_target20__2 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Um gato? Eu sabia que estava falando...[n][w][e]

[msg D01_03_D151_03_target20__3 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos explicar mais tarde, Takamaki. Por enquanto,[n]Temos que correr![n][w][e]

[msg D01_03_D151_02_target10_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nao podemos nos dar ao luxo de voltar como chegamos.[n]Basta encontrar um caminho a seguir![n][w][e]

[msg D01_03_D151_02_target10__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Em momentos como esses... voce deve[n][clr 2]concentrado[clr 27]e procure um caminho.[n][w][e]

[msg D01_03_D151_02_target11_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que Takamaki esta se mantendo.[n][w][e]

[msg D01_03_D151_02_target11__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas ela esta exausta. Precisamos sair[n]De aqui, Stat.[n][w][e]
[s]Este lugar enfrenta o exterior...[n]Tem que haver uma maneira de escapar.[n][w][e]
[s]Nao ha como voltar agora. Pressione a frente.[n][w][e]

[msg D01_03_D151_02_target12_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ninguem esta nos perseguindo agora! Apresse-se, nos vamos[n]Escape a janela aberta![n][w][e]

[msg D01_03_D151_01_target10_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Devemos ir para casa hoje.[n][w][e]
[s]Se queremos voltar mais tarde, podemos apenas[n]Retorne ao ponto de entrada e abra o[n]Meta-Nav![n][w][e]

[msg D01_04_target_mes10_A [Ryuji]]
[s][bup 0 2 0 65535 0]Temos que encontrar a localizacao deste chamado[n]Tesouro.[n][w][e]

[msg D01_dummy_mes01]
[s]>D01:古城(進行カウンタ0)エラー[n]>現在の進行度に合わせた会話[n][w][e]

