[msg SPOT_TUTO_BEFORE_MORU01 [Morgana]]
[s]Ei, eu tenho algo eu[n]Preciso falar com voce sobre![n][w][e]
[s]Sente-se no sofa.[n]Ha boas noticias![n][w][e]

[msg SPOT_TUTO_BEFORE_MORU02 [Morgana]]
[s]Entao, a boa noticia e...[n][w][e]
[s]Eu achei isso na lata de lixo[n]em LeBlanc.[n][w][e]

[msg SPOT_TUTO_BEFORE_MORU03]
[s]"Pontos de data quente"...? E uma pagina[n]rasgado de uma revista.[n][w][e]

[msg SPOT_TUTO_BEFORE_MORU04 [Morgana]]
[s]Pode parecer apenas um[n]pedaco de papel, mas ha[n]Algumas informacoes interessantes la.[n][w][e]
[s]Vamos ver aqui...[n][w][e]
[s]"Venha para o lago de pesca de Ichigaya[n]Para um relaxamento silencioso "... HM,[n]Esta falando sobre um lago de pesca.[n][w][e]
[s]"Delicioso inabalavel: entregue[n]no famoso ramen de Ogikubo "... ooh,[n]Este e para uma loja de ramen.[n][w][e]

[msg SPOT_TUTO_BEFORE_MORU05]
[s]Uma lagoa de pesca e uma loja de ramen...[n][w][e]

[msg SPOT_TUTO_BEFORE_MORU06 [Morgana]]
[s]Agora, aqui esta a parte importante.[n][w][e]
[s]Se voce quer ser forte[n]Phantom Thief, voce nao pode ficar[n]preso dentro da sua concha.[n][w][e]
[s]Em outras palavras, voce precisa[n]Explore a cidade e expanda[n]sua esfera de conhecimento.[n][w][e]
[s]Voce tem o dia de folga hoje, entao[n]Agora e um bom momento para sair.[n][w][e]
[s]Vamos tentar ir para a pesca[n]lagoa ou a loja de ramen![n][w][e]

[msg SPOT_TUTO_RYUJI_INVITE00]
[s]Recebi uma mensagem de Ryuji.[n][w][e]

[msg SPOT_TUTO_RYUJI_INVITE00_2 [Morgana]]
[s]"Ei, eu quero pescar um pouco.[n]Vamos ir para Ichigaya! "[n][w][e]
[s]Ele parece que esta com pressa.[n][w][e]
[s]Nao e uma ma ideia, no entanto. Novo[n]as experiencias sao importantes[n]Para um ladrao fantasma.[n][w][e]
[s]E a melhor maneira de fazer isso[n]esta indo para algum lugar novo![n]Bem, vamos para Ichigaya![n][w][e]

[msg SPOT_TUTO_RYUJI_INVITE00_3]
[s]Eu acho que devo ir...[n][w][e]

[msg SPOT_TUTO_RYUJI_INVITE00_4 [Morgana]]
[s]A proposito... voce ate[n]Sabe como chegar a Ichigaya?[n][w][e]
[s]Aquele visual que voce esta me dando[n]diz nao. Aguentar. eu penso isso[n]deve estar por aqui...[n][w][e]

[msg SPOT_TUTO_RYUJI_INVITE00_5 [Morgana]]
[s]La! Isso e um mapa de trem[n]linhas, para que voce possa pensar sobre[n]Como chegar a Ichigaya.[n][w][e]
[s]A proposito, voce precisara[n]Pegue a linha Chuo Sobu.[n][w][e]

[msg MSG_NIGHT_0508_000 [Morgana]]
[s]Ufa. Bom trabalho.[n][w][e]
[s]Ver? Indo para lugares diferentes,[n]Voce pode ter novas experiencias.[n][w][e]
[s]Mas voce nao pode simplesmente ir a lugar nenhum.[n]Tem que estar em algum lugar que vai[n]Afie seu ladrao sentindo.[n][w][e]

[msg MSG_TUTORIAL_SPOT [Exploring the City]]
[s]Voce pode ir para a cidade[n][clr 2]durante o dia[clr 27]sobre[clr 2]dias de folga[clr 27].[n][w][e]
[s]Isso vai te ajudar a treinar[n]e expandir seu conhecimento.[n][w][e]
[s]Se voce for com um amigo, voce pode[n]ate aprofundar seu relacionamento. Voce[n]deve tentar fazer isso proativamente.[n][w][e]
[s]Quando voce quer sair, tambem[n]Verifica a[clr 2]mapa de trem[clr 27]na tua[n]quarto ou abra o[clr 2]grande mapa[clr 27].[n][w][e]

[msg MSG_NIGHT_0508_001 [Morgana]]
[s]Desta vez, voce aprendeu sobre[n]a[clr 4]lagoa de pesca[clr 27]por causa de[n]Convite de Ryuji.[n][w][e]
[s]Mas a partir de agora, voce tera que[n]Encontre novos pontos de hangout.[n]Por que nao comprar um guia?[n][w][e]
[s]Voce pode tentar ouvir o que[n]As pessoas estao dizendo na cidade tambem![n][w][e]

[msg MSG_NIGHT_0508_002]
[s]Um guia... eles podem vender um[n]daqueles na livraria.[n][w][e]

[msg MSG_NIGHT_0508_003 [Morgana]]
[s]Ja e tarde hoje.[n]Eu deveria descansar um pouco.[n][w][e]

