[msg D10_01_e484_071_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Primeiro, precisamos de um caminho para essa coisa enorme.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1052 65535 0]A area descendo por esses portoes[n]parece suspeito para mim. Vamos la, Joker![n][w][e]

[msg D10_01_e511_331_mes_star [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8128 65535 0]Vamos descobrir onde Maruki e o primeiro.[n]Eu nao quero perder tempo[n]vagando sem rumo.[n][w][e]

[msg D10_01_e511_331_mes_end [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Encontramos um guia de informacao[n]Depois de subir aquele elevador...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se ele pretende nos receber em So[n]graciosamente, talvez vamos nos deparar[n]Outro guia em breve.[n][w][e]

[msg D10_01_showtime_unlock_m [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54503 65535 0]Ah 悪 antes de eu esquecer...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu suspeito que as batalhas vao conseguir[n]Ainda mais dificil daqui em diante[n]Devido a nossa falta de mao de obra.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54478 65535 0]Focar em nossas proprias habilidades e bom e[n]tudo, mas dependendo da situacao, vai[n]Seja mais eficiente para se unir.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A combinacao move que tiramos[n]Antes... isso nao era meio ruim.[n][w][e]

[msg SYS_SP_ATACK_ON]
[s][clr 2][f 4 2]E o Showtime de Akechi[clr 27][n]foi desbloqueado.[n][w][e]

[msg D10_01_showtime_unlock_m_2 [Akechi]]
[s][bup 0 9 811 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54489 65535 0]Claro... que tudo depende se[n]ou nao voce pode me acompanhar.[n][w][e]

