[msg e380_300_mes01 [Mechanical Voice]]
[s]Autenticacao completa.[n][w][e]
[s]Agora voce pode acessar os seguintes andares:[n][w][e]
[s]O piso padrao.[n]O piso dos membros.[n]O piso limite alto.[n][w][e]

[msg e380_300_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6144 65535 0]Huh, o piso do gerente ainda nao esta[n]aparecer...[n][w][e]

[msg e380_300_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas ela esta tao perto que quase posso sentir o cheiro dela![n]O proximo andar e prolly sera o ultimo[n]1.[n][w][e]

[msg e380_300_mes04 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7186 65535 0]Welp, vamos subir ate o piso limite alto![n][w][e]

