[msg MSG_DUMMY]
[s]......[n][w][e]

[sel YESNO_SEL top]
[s]Sim[e]
[s]Nao[e]

[msg MND_JuiceShop_NotOpen]
[s]Eles vendem suco de frutas frescas aqui.[n][w][e]
[s]Eu deveria tentar quando tiver tempo...[n][w][e]

[msg MSG_1stInfo_Aojiru_01 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Um suporte de bebida, hein? E um pouco mais caro[n]do que outros lugares.[n][w][e]
[s][f 4 10 65535 0 0]Se eles tomam bebidas especiais, pode nao ser[n]Uma ma ideia para tentar um...[n][w][e]

[msg MSG_1stInfo_Aojiru_02 [Drink Vendor]]
[s][f 4 23 1 2 3 5 65534 0][vp 8 2 1 0 2 0]Bem-vindo! Temos suco de frutas frescas![n][w][e]
[s][vp 8 2 1 0 2 0]O que e isso? Bebidas especiais? Isso e o que[n]Temos hoje![n][w][e]

[msg MSG_1stInfo_Aojiru_03 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Ooh, eu me pergunto o que e.[n][w][e]

[msg MSG_1stInfo_Aojiru_NotSe [Drink Vendor]]
[s][f 4 23 1 2 3 5 65534 0][vp 8 2 1 0 2 0]Bem-vindo!...O que e isso? Bebidas especiais?[n][w][e]
[s][vp 8 2 1 0 2 0]Bem, em[clr 2]Domingos[clr 27]Temos um especial[n]Suco de vegetais...[n][w][e]

[msg MSG_1stInfo_Aojiru_NotSe_2 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0]Entao, nenhum hoje, hein? Isso e ruim.[n]Por que nao tentar voltar no domingo?[n][w][e]

[msg MSG_1stInfo_Aojiru_04 [Drink Vendor]]
[s][f 4 23 1 2 3 5 65534 0][vp 8 2 1 0 2 0]E incrivelmente amargo, mas se fortalece[n]seu corpo.[n][w][e]
[s][vp 8 2 1 0 2 0]E chamado Aojiru![n][w][e]
[s][vp 8 2 1 0 2 0]Toda semana, temos um tipo diferente de[n]Aojiru.[n][w][e]

[msg MSG_NotSale_Aojiru_01 [Drink Vendor]]
[s][f 4 23 1 2 3 5 65534 0][vp 8 2 1 0 2 0]Sinto muito, mas estamos vendidos de aojiru[n]hoje...[n][w][e]
[s][vp 8 2 1 0 2 0]Nos so temos isso[clr 2]Domingos[clr 27].[n][w][e]

[msg MSG_NotSale_Aojiru_02 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Aww, isso e muito ruim. Vamos voltar[n]outra hora![n][w][e]

[msg MSG_Sale_Aojiru_01 [Drink Vendor]]
[s][f 4 23 1 2 3 5 65534 0][vp 8 2 1 0 2 0]Bem-vindo! Voce gostaria de um pouco fresco[n]suco de frutas?[n][w][e]
[s][vp 8 2 1 0 2 0]Ja que hoje e[clr 2]Domingo[clr 27], nos tambem temos[n]Aojiru para venda![n][w][e]

[msg MSG_Sale_Aojiru_02 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Oh, eles tem! Eles tem aojiru![n][w][e]

[msg MSG_Aojiru_Notbuy [Morgana]]
[s][bup 0 3 11 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]O que, voce nao vai conseguir?[n]Demasiado assustado?[n][w][e]

[msg MSG_Aojiru_Today_Drink [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ei, tente limita-lo a uma vez por dia. Ate[n]Coisas saudaveis podem ser ruins se voce exagerar.[n][w][e]

[msg MND_Aojiru_ParamEndInfo_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Parece que ajiru de hoje vai melhorar[n]sua[f 4 11 0][clr 26][f 4 12 0][clr 27]... embora voce provavelmente[n]Nao precisa disso agora.[n][w][e]

[msg MND_Aojiru_ParamEndInfo__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Parece que ajiru de hoje vai melhorar[n]sua[f 4 11 1][clr 26][f 4 12 1][clr 27]... embora voce provavelmente[n]Nao precisa disso agora.[n][w][e]

[msg MND_Aojiru_ParamEndInfo__3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Parece que ajiru de hoje vai melhorar seu[n][f 4 11 2][clr 26][f 4 12 2][clr 27]... embora voce provavelmente[n]Nao precisa disso agora.[n][w][e]

[msg MND_Aojiru_ParamEndInfo__4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Parece que ajiru de hoje vai melhorar seu[n][f 4 11 3][clr 26][f 4 12 3][clr 27]... embora voce provavelmente nao[n]Precisa disso agora.[n][w][e]

[msg MND_Aojiru_ParamEndInfo__5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Parece que ajiru de hoje vai melhorar seu[n][f 4 11 4][clr 26][f 4 12 4][clr 27]... embora voce provavelmente[n]Nao precisa disso agora.[n][w][e]

[msg MSG_Aojiru_Start_RND01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Tudo bem! RATE-O![n][w][e]

[msg MSG_Aojiru_Start_RND02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Th-essa e uma cor... eu nao iria[n]quero beber isso.[n][w][e]

[msg MSG_Aojiru_Start_RND03 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Voce realmente precisa ser bombeado e[n]Diga a si mesmo que e para sua saude.[n][w][e]

[msg MSG_Aojiru_NowDrink [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Bom chuggging! E assim que se faz![n][w][e]

[msg MSG_Aojiru_End [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1045 65535 0]Bom trabalho! Eu estava vendo voce tentar tanto.[n][w][e]

[msg MSG_Aojiru_HumanParamGet [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Uau... voce parece um totalmente diferente[n]pessoa![n][w][e]

[msg TEST_MONA2 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 47 0 0]Voce subiu uma classificacao, nao e?[n][w][e]

[msg MSG_Aojiru_Finish [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Ok, agora que voce esta saudavel, vamos[n]Em outro lugar![n][w][e]

