[msg D01_BRIEFING_080_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7028 65535 0]Finalmente entramos na torre... esta comecando[n]sentir que estamos fechando no final...[n][w][e]

[msg D01_BRIEFING_080_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sim, a distorcao aqui e particularmente[n]Forte. Deveriamos estar chegando perto do[n]Tesouro.[n][w][e]

[msg D01_BRIEFING_080_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas isso significa que os inimigos serao[n]Mais forte tambem, certo? E melhor sermos[n]preparado para isso...[n][w][e]

