[msg D06_16_e384_100_mes01 [Makoto]]
[s][bup 0 6 103 0 0][vp 1 0 0 0 0 0]......[n][w][e]

[msg D06_16_e384_100_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]HM? E ai? Voce e curioso[n]sobre o tesouro?[n][w][e]

[msg D06_16_e384_100_mes03 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Falando nisso, realmente parece[n]Ha uma forma formada na nebulosidade...[n][w][e]

[msg D06_16_e384_100_mes04 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se eu tivesse que adivinhar... eu diria irmaos[n]Treasure e um caderno policial.[n][w][e]

[msg D06_16_e384_100_mes05 [Akechi]]
[s][bup 0 9 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Certo... seu pai era...[n][w][e]

[msg D06_16_e384_100_mes06 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2100 65535 0]Ela... provavelmente pensa que papai morreu[n]Porque a policia o estava usando.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E por isso que ela acredita que a justica e[n]sem sentido, e que nao ha[n]Point vivendo uma vida subserviente...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A morte de papai e ate a razao pela qual ela[n]aspirando a se tornar um promotor e[n]ficou tao obcecado em ganhar...[n][w][e]

[msg D06_16_e384_100_mes07 [Makoto]]
[s][bup 0 6 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ela realmente o amava...[n][w][e]

[msg D06_16_e384_100_mes08 [Akechi]]
[s][bup 0 9 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8038 65535 0]O coracao de Sae-san deve estar exausto[n]de viver tao ferozmente[n]mundo competitivo...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Somente crencas honestas nao sao suficientes[n]para voce passar por voce. Ate eu entendo[n]aquela dor...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas e exatamente por isso que precisamos[n]mudar seu coracao.[n][w][e]

[msg D06_16_e384_100_mes09 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]... Sim, e isso.[n][w][e]

[msg D06_16_e384_100_mes10 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E agora determinamos o local[n]do tesouro por esse objetivo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Voce gostaria de voltar para[n]A entrada agora, Coringa?[n][w][e]

[sel D06_16_e384_100_selA top]
[s]Vamos la.[e]
[s]Eu ainda quero explorar.[e]

[msg D06_16_e384_100_selA_0_m [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6023 65535 0]Ok! Poderemos enviar a chamada[n]Cartao do mundo real agora![n][w][e]

[msg D06_16_e384_100_selA_1_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1176 65535 0]Ha algo mais aqui[n]Isso chamou sua atencao?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ok, vamos olhar em volta um pouco mais[n]Antes de voltarmos![n][w][e]

[msg D06_16_e384_100_selA_2_m [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

