[msg MSG_DUMMY_01]
[s]※冷蔵庫処理(つまみ食い)[n][w][e]

[msg MSG_MGK_FREEZER_NG_MASTE [Sojiro]]
[s]......[n][w][e]
[s]O que diabos voce esta fazendo, abrindo[n]A geladeira enquanto o cafe ainda esta aberto?[n][w][e]
[s]Vamos. Apresse-se e feche-o.[n][w][e]

[msg MND_MGK_FREEZER_NG_0409]
[s]A geladeira esta embalada[n]cheio de ingredientes.[n][w][e]
[s]Estou exausto...[n]Eu devia ir dormir.[n][w][e]

[msg MSG_MGK_FREEZER_NG_CLEAN [Morgana]]
[s]Voce pode vasculhar a geladeira mais tarde.[n]Venha para o segundo andar, ha algo[n]devemos discutir.[n][w][e]

[msg MSG_MGK_FREEZER_NG_CLEAN_2 [Morgana]]
[s]Voce entendeu o que estou dizendo, certo?[n][w][e]
[s]Contanto que voce nao tenha limpado seu quarto,[n]Vou continuar dizendo isso.[n][w][e]

[msg MND_MGK_FREEZER_NG_MYROO]
[s]Estou cansado depois de tudo isso[n]aconteceu esta noite. Eu posso vasculhar[n]Atraves da geladeira mais tarde...[n][w][e]

[msg MSG_MGK_FREEZER_NG_DNG_0]
[s]Voce esta cansado, nao e? Voce pode remar[n]atraves da geladeira mais tarde.[n][w][e]

[msg MSG_MGK_FREEZER_NG_DNG [Morgana]]
[s]Ei, voce nao fez nada esta noite.[n]Voce espera comer tantas calorias[n]e nao engordar?[n][w][e]
[s]Voce deve invadir a geladeira quando estiver[n]exausto, talvez depois de voce entrar no[n]Metaverso ou algo assim.[n][w][e]

[msg MND_MGK_FREEZER_NG_DNG]
[s]Ainda nao estou com fome...[n]Talvez eu apenas vasculhe[n]atraves da geladeira mais tarde.[n][w][e]

[msg MSG_MGK_FREEZER_NG_MATER [Morgana]]
[s]Agora, na geladeira...[n][w][e]
[s]... nao parece haver ingredientes[n]podemos usar.[n][w][e]
[s]Ah bem. Estou com fome, mas talvez devessemos[n]Apenas va dormir.[n][w][e]

[msg MSG_MGK_FREEZER_CHK_END [Morgana]]
[s]HM? Voce mudou de ideia?[n][w][e]

[msg MSG_MGK_FREEZER_CHK [Morgana]]
[s]O chefe nao esta por perto, para que possamos vasculhar[n]Atraves da geladeira tudo o que queremos![n][w][e]

[msg MSG_MGK_FREEZER_COOK_STA [Morgana]]
[s]Agora, na geladeira...[n][w][e]
[s]... Ei, parece que o chefe nos deixou um saco de[n]coisas que podemos usar.[n][w][e]
[s]Devemos passar algum tempo fazendo[n]Algo para comer com esses ingredientes?[n][w][e]

[sel SEL_MGK_FREEZER_COOK_STA top]
[s]Faca comida[e]
[s]Pense um pouco mais[e]

