[msg D02_SP_ABILITY_START_00]
[s]★仮テキスト[n]特性解禁イベント・開始[n][w][e]

[msg D02_SP_ABILITY_START_01]
[s]★仮テキスト[n]特性解禁イベント・終了[n][w][e]

[msg EV_SP_ABILITY_OPEN_START [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1052 65535 0]Ok a todos, esta e a primeira infiltracao[n]Fox estara ligado desde o inicio 悪 vamos fazer[n]isso certo![n][w][e]

[msg EV_SP_ABILITY_OPEN_START_2 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 12018 65535 0]Voce parece estar bem, preso.[n][w][e]

[msg EV_SP_ABILITY_OPEN_START_3 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 55232 65535 0]Nosso mestre gostaria de uma palavra com voce.[n]Entre.[n][w][e]

[msg EV_SP_ABILITY_OPEN_END_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1018 65535 0]Ei! Joker![n][w][e]

[msg EV_SP_ABILITY_OPEN_END_0_2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1026 65535 0]Por que voce esta de pe?[n][w][e]

[msg EV_SP_ABILITY_OPEN_END_0_3 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Fique com o programa, tudo bem? Voce e[n]Um membro vital da equipe aqui![n][w][e]

[msg dummy_mes]
[s]......[n][w][e]

