[msg D157_006_miniEV_03_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6127 65535 0]Parece as regras para a area de slot[n]estao escritos aqui.[n][w][e]

[msg D157_006_miniEV_03_mes02 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Deixe-me ver... "Este jogo envolve[n]Simbolos correspondentes no rotativo[n]rolos de caca-niqueis. "[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"O pagamento sera de 20 moedas para todas as cerejas,[n]120 moedas para bar e 200 moedas para[n]triplo 7s. "[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"A aposta para um unico jogo[n]sao 20 moedas. "[n][w][e]

[msg D157_006_miniEV_03_mes03 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Portanto, a obtencao de 777 retornara dez vezes[n]tantas moedas quanto voce coloca? Aquilo e um[n]ganho liquido bastante significativo.[n][w][e]

[msg D157_006_miniEV_03_mes04 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este deve ser mais dificil[n]do que o jogo de dados, sim?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Suponho que os saldos de pagamento mais altos[n]isso saiu.[n][w][e]

