[msg D06_157_11_ex_chk_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]A vontade de Sis semeada esta apenas a frente...[n][w][e]

[msg D06_157_11_ex_chk_mes02 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Desculpe, mas voce estara nos deixando passar![n][w][e]

[msg D06_157_11_ex_chk_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espere, rainha 悪 estou recebendo o sentimento[n]que este vai ser uma dor de cabeca.[n][w][e]

[msg D06_157_11_ex_chk_mes04 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Provavelmente queremos estar tao prontos[n]o mais possivel para esta luta. Nos somos,[n]Joker?[n][w][e]

[sel D06_157_11_ex_chk_selA top]
[s]Nos com certeza somos.[e]
[s]Espere um segundo.[e]

[msg D06_157_11_ex_chk_selA_1 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1136 65535 0]Soa bem. Certifique-se de que somos legais[n]E pronto.[n][w][e]

[msg D06_157_11_ex_chk_re_mes [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1099 65535 0]Entao vamos. Prepare-se, Coringa![n][w][e]

[msg D06_157_11_ex_btl_mes01 [Shadow]]
[s]Oh querido... convidados? Aqui? Com licenca,[n]senhoras e senhores...[n][w][e]
[s]Peco desculpas, mas esta area esta fora dos limites[n]para os hospedes. Por favor, tire sua licenca.[n][w][e]

[msg D06_157_11_ex_btl_mes02 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2108 65535 0]Oh, nao e problema para o gerente[n]irma, embora seja voce quem e quem e[n]fora daqui![n][w][e]

[msg D06_157_11_ex_btl_af_mes [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2165 65535 0]E isso cuida disso! Vamos nos mover.[n][w][e]

[msg D06_157_11_ex_btl_af_mes_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tudo bem, Joker! Pegue e tire-nos para fora aqui![n][w][e]

