[msg D10_BRIEFING_040_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7162 65535 0]Eu nao tinha certeza do que ia acontecer[n]Quando voce ficou cercado, mas santo[n]Merda, Violet![n][w][e]

[msg D10_BRIEFING_040_mes02 [Sumire]]
[s][bup 0 10 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Heheh, obrigado...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Na verdade, parecia uma carga enorme do meu[n]ombros. Estou indo muito melhor[n]agora.[n][w][e]

[msg D10_BRIEFING_040_mes03 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Isso foi, tipo, algum tipo de incrivel[n]rotina de ginasta de batalha. Eu nao aguentava[n]Meus olhos de voce![n][w][e]

[msg D10_BRIEFING_040_mes04 [Sumire]]
[s][bup 0 10 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57030 65535 0]Oh! Oh nao, eu nao mereco esse tipo[n]de louvor, Pantera-Senpai![n][w][e]

[msg D10_BRIEFING_040_mes05 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, nao seja tao formal sobre isso! Apenas[n]Va com calma e acompanhe o grupo![n][w][e]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Estamos indo para o auditorio, certo?[n][w][e]

