[msg SYSTEM_GET_COSTUME_P4]
[s]Obteve o[clr 4]Uniformes de Yasogami[clr 27][n]e[clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_P3]
[s]Obteve o[clr 4]Uniformes Gekkoukan[clr 27][n]e[clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_P2]
[s]Obteve o[clr 4]Sete irmas[n]Uniformes[clr 27]e[clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_IBUNR]
[s]Obteve o[clr 4]St. Hermelin[n]Uniformes[clr 27]e[clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_IF]
[s]Obteve o[clr 4]Karukozaka[n]Uniformes[clr 27]e[clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_P4D]
[s]Obteve o[clr 4]Roupas de danca[clr 27][n]e[clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_P4U]
[s]Obteve o[clr 4]Ops de sombra[n]Uniformes[clr 27]e[clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_MEGAM]
[s]Obteve o[clr 4]Garb Samurai[clr 27][n]e[clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_RAIDO]
[s]Obteve o[clr 4]Uniformes estudantis[clr 27][n]e[clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_CATHE]
[s]Obteve o[clr 4]Adultos perdidos[n]Roupas[clr 27]e[clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_P5]
[s]Obteve o[clr 4]Roupas normais[clr 27], Assim,[n][clr 4]Uniformes escolares[clr 27], e[clr 4]Loungewear[clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_SWIM]
[s]Obteve o[clr 4]Maios[clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_BUTLE]
[s]Obteve o[clr 4]Roupas de empregada domestica e mordomo[clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_XMAS]
[s]Obteve o[clr 4]Roupas de Natal[clr 27].[n][w][e]

[msg SYSTEM_GET_ITEM_NG]
[s]Nao foi possivel receber alguns itens[n]Porque voce nao pode segurar nenhum[n]mais.[n][w][e]

[msg SYSTEM_GET_MONEY_NG]
[s]Nao pode receber mais porque[n]a quantia maxima de dinheiro[n]esta sendo realizada.[n][w][e]

[msg SYSTEM_GET_PERSONA_ORPHE]
[s]Obteve o Orfeu DLC,[n][clr 4][var 0][clr 27], e[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_ORPHE_2]
[s]Falhou em receber o Orpheus DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_IZANA]
[s]Obteve o izanagi dlc,[n][clr 4][var 0][clr 27], e[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_IZANA_2]
[s]Falhou em receber o Izanagi DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_THANA]
[s]Obteve o DLC Thanatos,[n][clr 4][var 0][clr 27], e[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_THANA_2]
[s]Falha ao receber o DLC Thanatos.[n][w][e]

[msg SYSTEM_GET_PERSONA_MAGAT]
[s]Obteve o Magatsu-Izanagi[n]DLC,[clr 4][var 0][clr 27], e[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_MAGAT_2]
[s]Falhou em receber o[n]Magatsu-Izanagi DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_KAGUY]
[s]Obteve o Kaguya DLC,[n][clr 4][var 0][clr 27], e[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_KAGUY_2]
[s]Falha ao receber o Kaguya DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_ARIAD]
[s]Obteve o Ariadne DLC,[n][clr 4][var 0][clr 27], e[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_ARIAD_2]
[s]Falhou em receber o Ariadne DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_ASTER]
[s]Obteve o Asterius DLC,[n][clr 4][var 0][clr 27], e[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_ASTER_2]
[s]Falhou em receber o Asterius DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_TUKIY]
[s]Obteve o Tsukiyomi DLC,[n][clr 4][var 0][clr 27], e[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_TUKIY_2]
[s]Falha ao receber o Tsukiyomi DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_MESSI]
[s]Obteve o Messias DLC,[n][clr 4][var 0][clr 27], e[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_MESSI_2]
[s]Falhou em receber o Messias DLC.[n][w][e]

[msg SYSTEM_GET_ITEM_START01]
[s]Obteve o[clr 3]Conjunto de itens de cura[clr 27].[n][w][e]

[msg SYSTEM_GET_ITEM_START01_]
[s]Falhou em receber o[n][clr 3]Conjunto de itens de cura[clr 27]DLC.[n][w][e]

[msg SYSTEM_GET_ITEM_START02]
[s]Obteve o[clr 3]Conjunto de cartoes de habilidade[clr 27].[n][w][e]

[msg SYSTEM_GET_ITEM_START02_]
[s]Falhou em receber o[n][clr 3]Conjunto de cartoes de habilidade[clr 27]DLC.[n][w][e]

[msg SYSTEM_GET_COSTUME_P5_DA]
[s]Obteve o[clr 4]Roupa da luz das estrelas[clr 27][n]e[clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_VELVE]
[s]Obteve o[clr 4]roupa ultramarina[n][clr 27]e[clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_FEATG]
[s]Obtido[clr 4]mascara de penas[clr 27][n]e[clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_DEEPS]
[s]Obtido[clr 4]Demonica com capacete[clr 27][n]e[clr 4]Demonica sem capacete[clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_JERSE]
[s]Obtido[clr 4]Recurso rebelde[clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_PQ2]
[s]Obteve o[clr 4]Novo desgaste do cinema[clr 27][n]e[clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_COSTUME_VIOLE]
[s][clr 4]>[var 0][clr 27], Assim,[n][clr 4]>[var 1][clr 27], Assim,[n][clr 4]>[var 2][clr 27], e[n][w][e]
[s][clr 4]>[var 3][clr 27], Assim,[n][clr 4]>[var 4][clr 27], Assim,[n][clr 4]>[var 5][clr 27], e[n][w][e]
[s][clr 4][var 6][clr 27]e[n][clr 4][var 7][clr 27]obtido.[n][w][e]

[msg SYSTEM_GET_COSTUME_VIOLE_2]
[s][clr 4]>[var 0][clr 27], Assim,[n][clr 4]>[var 1][clr 27], Assim,[n][clr 4]>[var 2][clr 27], e[n][w][e]
[s][clr 4]>[var 3][clr 27], Assim,[n][clr 4]>[var 4][clr 27], Assim,[n][clr 4]>[var 5][clr 27], e[n][w][e]
[s][clr 4]>[var 6][clr 27], Assim,[n][clr 4]>[var 7][clr 27], e[n][clr 4]>[var 8][clr 27], obtido.[n][w][e]

[msg SYSTEM_GET_COSTUME_VIOLE_3]
[s][clr 4]>[var 0][clr 27], Assim,[n][clr 4]>[var 1][clr 27], Assim,[n][clr 4]>[var 2][clr 27], e[n][w][e]
[s][clr 4]>[var 3][clr 27], Assim,[n][clr 4]>[var 4][clr 27], Assim,[n][clr 4]>[var 5][clr 27], e[n][w][e]
[s][clr 4][var 6][clr 27]e[n][clr 4][var 7][clr 27]obtido.[n][w][e]

[msg SYSTEM_GET_COSTUME_VIOLE_4]
[s][clr 4]>[var 0][clr 27], Assim,[n][clr 4]>[var 1][clr 27], Assim,[n][clr 4]>[var 2][clr 27], e[n][w][e]
[s][clr 4]>[var 3][clr 27], Assim,[n][clr 4]>[var 4][clr 27], Assim,[n][clr 4]>[var 5][clr 27], e[n][w][e]
[s][clr 4]>[var 6][clr 27], Assim,[n][clr 4]>[var 7][clr 27], Assim,[n][clr 4]>[var 8][clr 27], e[n][w][e]
[s][clr 4][var 9][clr 27], e[n][clr 4][var 10][clr 27]obtido.[n][w][e]

[msg SYSTEM_GET_PERSONA_IZANA_3]
[s]Obteve izanagi-no-okami[n]DLC,[clr 4][var 0][clr 27], Assim,[n]e[clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_IZANA_4]
[s]Falhou em receber o[n]Izanagi-no-Okami DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_ORPHE_3]
[s]Obteve o Orfeu DLC,[n][clr 4][var 0][clr 27], e[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_ORPHE_4]
[s]Falhou em receber o Orpheus DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_ATENA]
[s]Obteve o Athena DLC,[n][clr 4][var 0][clr 27], e[n][clr 3][var 1][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_ATENA_2]
[s]Falhou em receber o Athena DLC.[n][w][e]

[msg SYSTEM_GET_PERSONA_RAULU]
[s]Obtido Raoul DLC[n][clr 4][var 0][clr 27].[n][w][e]

[msg SYSTEM_GET_PERSONA_RAULU_2]
[s]Falha ao receber o Raoul DLC.[n][w][e]

[msg SYSTEM_GET_ITEM_DUNGEON_]
[s]Obtido[clr 3]Assistencia de exploracao[n]Pacote[clr 27].[n][w][e]

[msg SYSTEM_GET_ITEM_DUNGEON__2]
[s]Falhou em receber o[n][clr 3]Pacote de assistencia de exploracao[clr 27].[n][w][e]

[msg SYSTEM_GET_ITEM_DUNGEON__3]
[s]Nao pode receber mais porque[n]a quantia maxima de dinheiro[n]esta sendo realizada.[n][w][e]

[msg SYSTEM_GET_ITEM_BATTLE_P]
[s]Obteve o[clr 3]Battle Assist Pack[clr 27].[n][w][e]

[msg SYSTEM_GET_ITEM_BATTLE_P_2]
[s]Obteve o[clr 3]Battle Assist Pack[clr 27].[n][w][e]

[msg SYSTEM_GET_P5_SAVEDATA]
[s]Recebido[clr 3]Persona 5 Salvar dados[n]Presente especial[clr 27].[n][w][e]

[msg SYSTEM_CHECK_P5_SAVEDATA]
[s]Se voce tem Persona 5[n]Salvar dados, voce pode[n]receber varios beneficios.[n][w][e]
[s]Usar os beneficios?[n][w][e]

[msg SYSTEM_CHECK_P5_SAVEDATA_2]
[s]Nao e possivel adquirir dados de salvamento.[n]Voce gostaria de tentar de novo?[n][w][e]

[msg SYSTEM_CHECK_P5_SAVEDATA_3]
[s]Voce pode acessar os dados salvar[n]beneficios a qualquer momento acessando[n]A caixa de papelao no seu quarto.[n][w][e]

[msg SYSTEM_CHECK_P5_SAVEDATA_4]
[s]Obtained 〇〇.[n][w][e]

[sel SYSTEM_CHECK_P5_SAVEDATA_5 top]
[s]Sim[e]
[s]Nao[e]

[msg SYSTEM_DLC_GET_TOP]
[s]Recebido[clr 3]DLC[clr 27].[n][w][e]

[msg SYSTEM_DLC_GET_TOP_Fiber]
[s]Voce recebeu o seu[clr 3]conteudo de bonus[clr 27].[n][w][e]

[msg MIND_MYPALACE_COMPLETE]
[s]Algo esta na caixa de papelao...[n][w][e]

[msg SYSTEM_MYPALACE_COMPLETE]
[s]Recebido[clr 3]Conclusao do premio[n]Recompensa[clr 27].[n][w][e]

[msg SYSTEM_GET_GENERAL_UPPER]
[s]Voce nao pode segurar mais[n][clr 3][var 0][clr 27]. O item[n]nao pode ser recebido.[n][w][e]

[msg SYSTEM_GET_GENERAL_UPPER_2]
[s]Voce nao pode segurar mais[n][clr 4][var 0][clr 27]. O item[n]nao pode ser recebido.[n][w][e]

[msg SYSTEM_GET_ITEM_UPPER_LI]
[s]Voce nao pode segurar mais[n][clr 3][var 0][clr 27]. O item[n]nao pode ser recebido.[n][w][e]

