[msg TABLE_CLEAN_mes00]
[s]Esta mesa esta cheia de velhas[n]revistas e lixo variado.[n][w][e]

[msg TABLE_CLEAN_NG_0409_mes0]
[s]Pode parecer um pouco melhor se eu limpar...[n][w][e]

[msg TABLE_CLEAN_NG_TEACHER]
[s]Esta tabela esta uma bagunca...[n][w][e]
[s]Eu nao consigo lidar com tudo isso sozinho,[n]no entanto. Talvez se eu perguntasse algum tipo[n]de limpeza profissional...[n][w][e]

[msg TABLE_CLEAN_NG_mes01]
[s]Estou exausto. Eu nao posso reunir[n]ate a energia para limpar.[n][w][e]

[msg TABLE_CLEAN_MENU]
[s]Eu posso ser capaz de colocar algo[n]Nesta mesa, se eu limpar.[n][w][e]
[s]Devo passar algum tempo limpando?[n][w][e]

[sel TABLE_CLEAN_MENU_SEL top]
[s]Limpar[e]
[s]Cancelar[e]

[msg TABLE_CLEAN_mes01]
[s]O que e isso?[n][w][e]
[s]Havia um[clr 4]relogio de pulso[clr 27]apenas[n]deitado nesta montanha de lixo.[n]Parece que ainda e utilizavel.[n][w][e]

[msg TABLE_CLEAN_ITEM_GET]
[s]Eu tenho um[clr 4]Velinha de pulso velho[clr 27].[n][w][e]

[msg TABLE_CLEAN_mes02]
[s]Parece um pouco mais limpo agora.[n][w][e]

[msg TABLE_CLEAN_PARAM_UP]
[s]Limpando a sala tem[n]melhorou meu[clr 1]Dignidade[clr 27]![n][w][e]

[msg TABLE_CLEAN_END_mes01]
[s]Eu provavelmente poderia colocar algo aqui.[n][w][e]
[s]Uma vez que as coisas se acalmam, talvez[n]Eu posso comprar alguns[clr 2]mobiliario[clr 27]...[n][w][e]

[msg TABLE_CLEAN_END_mes02 [Morgana]]
[s]Problema de limpar a mesa,[n]Voce deveria colocar algo nisso![n][w][e]
[s]Vamos ver... o que seria[n]o perfeito 悪 oh! Eu sei![n][w][e]
[s]A loja de segunda mao onde voce[n]Comprei minha cama vendendo um[clr 2]televisao[clr 27]![n][w][e]
[s]E um aborrecimento descer as escadas[n]o primeiro andar quando voce quiser[n]assistir TV. Por que nao conseguir um aqui?[n][w][e]

[msg TABLE_CLEAN_END_TV [Morgana]]
[s]Eu acho que seria uma boa ideia colocar[n]a[clr 2]televisao[clr 27]Voce vai nessa mesa.[n][w][e]
[s]Voce quer colocar aqui?[n][w][e]

[sel SEL_TABLE_CLEAN_END_TV top]
[s]Vamos colocar a TV.[e]
[s]Nao, agora nao.[e]

[msg TABLE_CLEAN_END_TV_OK [Morgana]]
[s]Tudo bem! Vamos configurar a TV![n][w][e]

[msg TABLE_CLEAN_END_TV_NO [Morgana]]
[s]Voce nao vai fazer isso? So para voce saber,[n]Voce so pode colocar a TV nesta mesa![n][w][e]

[msg TABLE_CLEAN_END_mes03]
[s]Eu deveria ir para a cama...[n][w][e]

[msg TABLE_CLEAN_EV_DUMMY_01]
[s](仮)掃除をする主人公:モーション[n][w][e]

