[msg D08_01_e446_010_mes01 [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9114 65535 0]Huh? A luz no meio do chao[n]diferente daqueles que vimos entao[n]distante...[n][w][e]

[msg D08_01_e446_017_mes01 [Futaba]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9105 65535 0]Ooh, ele se abriu! Esse e o nosso Coringa![n][w][e]

[msg D08_01_e446_017_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas o que esses padroes poderiam no[n]piso significava...?[n][w][e]

[msg D08_01_e446_017_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tenho certeza de que descobri enquanto estava[n]assistindo... ha uma limitacao nisso[n]area.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Voce so pode mudar as cores ate dez[n]vezes. Mais do que isso, e teremos[n]Recomecar.[n][w][e]

[msg D08_01_e446_017_mes04 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6011 65535 0]Voce resolveu um quebra-cabeca como esse no seu primeiro[n]Tente, Joker? Isso e seriamente incrivel![n][w][e]

