[msg TUTORIAL_MSG01 [Customizing Weapons]]
[s][clr 2]Customizar [clr 27]foi adicionado ao menu na loja de Iwai, intocável.[clr 2]Armas à distância [clr 27], como armas, agora pode ser personalizado aqui.[n][w][e]

[msg TUTORIAL_MSG02 [Customizing Weapons]]
[s]Você pode instalar uma peça personalizada por arma. Quanto[n]maior a classificação do seu confidente, mais as peças[n]mais personalizáveis você poderá escolher.[n][w][e]

