[msg TUTORIAL_MSG01 [Challenge Battle Rewards and Bonuses]]
[s]Existem três tipos diferentes de recompensas que você pode[n]receber em uma batalha de desafio, dependendo da sua[n]pontuação final. Você só pode obter cada tipo uma vez.[n][w][e]

[msg TUTORIAL_MSG02 [Challenge Battle Rewards and Bonuses]]
[s]Você não pode fazer um ataque ou um ataque total durante[n]uma batalha de desafio. No entanto, se você cumprir certos[n]requisitos, receberá pontos de bônus.[n][w][e]

[msg TUTORIAL_MSG03 [Challenge Battle Rewards and Bonuses]]
[s]Na tela de recompensas, use [f 1 10 3]para ver os requisitos e oponentes de bônus. Apontar uma[n]pontuação alta, utilizando os membros do seu partido de[n]acordo.[n][w][e]

