[msg TUTORIAL_MSG01 [Part-Time Jobs]]
[s]Empregos de meio período causarão tempo para passar, mas[n]também permitirá que você ganhe dinheiro e aumente[n]estatísticas como [n][f 4 11 1][clr 26][f 4 12 1][clr 27]e [f 4 11 4][clr 26][f 4 12 4][clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Part-Time Jobs]]
[s]Alguns empregos exigem que você tenha [clr 2]Estatísticas altas [clr 27] o [n] suficiente antes de você se candidatar. Dependendo do trabalho, você só[n]pode trablhar algumas [n][clr 2] horas do dia[clr 27].[n][w][e]

