[msg D_TUTORIAL_09_mes01 [Quick Travel]]
[s]Agora você pode [clr 2]Viagem rápida [clr 27]. Traga o mapa com [n][clr 2][f 1 10 53][clr 27]e selecione uma sala segura visitada anteriormente para ir[n]para lá instantaneamente.[n][w][e]

[msg D_TUTORIAL_09_mes02 [Quick Travel]]
[s]Você também pode viajar rápido de um quarto seguro de volta[n]à entrada do palácio. Viagens rápidas só podem ser usadas[n]em [n][clr 2]esses dois locais [clr 27].[n][w][e]

