[msg dummy_mes]
[s]......[n][w][e]

[msg SCN_LOCK_06_mes01]
[s]Nao parece[n]vai abrir...[n][w][e]

[msg SCN_LOCK_06_mes02 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nao e bom de novo...[n][w][e]

[msg SCN_LOCK_06_mes03 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Isso significa que ainda existem pessoas[n]Quem nao nos aceita?[n][w][e]

[msg SCN_LOCK_06_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nao se preocupe. Enquanto permanecermos ativos,[n]vai abrir eventualmente.[n][w][e]

[msg SCN_LOCK_06_mes05 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Teremos apenas que ser paciente ate que isso[n]realmente acontece.[n][w][e]

[msg SCN_LOCK_CLEAR_06_mes01 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, isso se abriu...[n][w][e]

[msg SCN_LOCK_CLEAR_06_mes02 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Olhando para isso em uma escala maior, isso e[n]A area de cinquenta segundos, sim? me pergunto como[n]Muitos sao deixados...[n][w][e]

[msg SCN_LOCK_CLEAR_06_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos apenas ter que descobrir com o nosso[n]olhos! Vamos la![n][w][e]

