[msg ENTRANCE_DOOR_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]O inferno... nao vai se abrir do[n]dentro tambem?[n][w][e]

[msg ENTRANCE_DOOR_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que eles estao tentando selar todos os[n]entradas...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Como se isso nos parasse![n][w][e]

[msg FENCE_WEST_D_mes01]
[s]Parece as barras de ferro[n]estao bloqueando nosso caminho.[n][w][e]

[msg FENCE_WEST_U_mes01]
[s]Parece as barras de ferro[n]estao bloqueando nosso caminho.[n][w][e]

[msg FENCE_EAST_D_mes01]
[s]Parece as barras de ferro[n]estao bloqueando nosso caminho.[n][w][e]

[msg FENCE_EAST_U_mes01]
[s]Parece as barras de ferro[n]estao bloqueando nosso caminho.[n][w][e]

[msg FENCE_WEST_SWITCH_mes01]
[s]Abaixe as barras[n][w][e]

[msg FENCE_EAST_SWITCH_mes01]
[s]Abaixe as barras[n][w][e]

[msg D151_002_EV_LOCK_mes01 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh! Algo esta em movimento... sao aqueles[n]engrenagens?[n][w][e]

[msg D151_002_EV_LOCK_mes02 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1138 65535 0]Eu vejo. Aposto que podemos acessar uma area que nos[n]nao poderia antes. Bom olho, Coringa![n][w][e]

[msg D01_03_e161_025_pre_mes0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ei, olhe para aquela pintura no meio[n]la. Nao e isso Kamoshida!?[n][w][e]

[msg D01_03_e161_025_pre_mes0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ele pendurou seriamente uma pintura dele em seu[n]proprio castelo...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aquele cara deve realmente estar obcecado por[n]ele mesmo.[n][w][e]

[msg D01_03_e161_025_pre_mes0_3 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Olhando para a coisa que esta me deixando doente.[n]Vamos a algum outro lugar.[n][w][e]

[msg L1_Tutorial_mes01 [【サードアイ】]]
[s]dummy fhit_151_002_00[n]dummy fhit_151_002_00[n][w][e]

[msg D01_02_escape_ng_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Porcaria, ha um soldado ali...[n][w][e]

[msg D01_02_escape_ng_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas nao ha outra maneira. Nos teremos[n]para escapar por aquela porta antes de nos[n]ser apanhado.[n][w][e]

