[msg DUMMY_MSG]
[s]E velho[var 0].[n][w][e]

[msg MSG_LAST_GREETING_InfoCe [Information Desk Lady]]
[s][vp 8 2 1 58671 1 0]Meu, voce e tao jovem de um tempo[n]atras, nao e? Aquele que ouviu isso[n]atentamente as informacoes que dei.[n][w][e]
[s][vp 8 2 1 0 1 0]Voce aprendeu muito sobre Kichijoji em[n]seu proprio tambem?[n][w][e]

[msg MSG_LAST_GREETING_InfoCe_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ei, voce vai deixar esta cidade[n]em breve, entao voce deve dizer adeus a isso[n]Boa informacao, senhora tambem.[n][w][e]

[msg MSG_LAST_GREETING_InfoCe_3 [Information Desk Lady]]
[s][vp 8 2 1 58675 1 0]Huh!? Voce esta se mudando!?[n][w][e]
[s][vp 8 2 1 0 1 0]Eu vejo... aposto de onde voce e um[n]Lugar maravilhoso tambem.[n][w][e]
[s][vp 8 2 1 0 1 0]Mas voce nao diria que Kichijoji tem[n]foi uma grande cidade natal?[n][w][e]
[s][vp 8 2 1 0 1 0]E por isso que espero que voce nao esqueca[n]esta cidade. Certifique-se de voltar. Eu vou[n]Sempre esteja aqui.[n][w][e]

[msg MSG_LAST_GREETING_InfoCe_4 [Information Desk Lady]]
[s][vp 8 2 1 58673 1 0]E por isso que espero que voce nao esqueca[n]esta cidade. Certifique-se de voltar. Eu vou[n]Sempre esteja aqui.[n][w][e]

[msg MSG_LAST_GREETING_InfoCe_5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Nao faz sentido aprender mais sobre isso[n]cidade agora, certo? Vamos a algum outro lugar.[n][w][e]

[msg MSG_LAST_GREETING_MeatFr [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Este lugar tinha uma linha enorme, nao importa[n]Quando chegamos. Ei, vamos aqui[n]novamente algum dia.[n][w][e]

[msg MSG_LAST_GREETING_DartsA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Passamos muito tempo aqui. Jogando[n]junto com todo mundo e um otimo[n]Memoria para nos dois.[n][w][e]

[msg MSG_LAST_GREETING_DartsA_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Nao ha tempo jogar um jogo agora.[n]Vamos dizer adeus a todos.[n][w][e]

[msg MSG_LAST_GREETING_JazzCl [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Akechi foi quem lhe contou sobre[n]Esse lugar...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Aposto que ele... vamos la, vamos para outro lugar.[n][w][e]

[msg MSG_LAST_GREETING_JazzCl_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Parece que este lugar esta fechado durante[n]o dia. Vamos a algum outro lugar.[n][w][e]

[msg MSG_LAST_GREETING_Shop_A [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Voce tem muitos amigos confiaveis.[n]Voce nao precisa confiar em cristais de cura.[n][w][e]

[msg MSG_LAST_GREETING_Shop_V [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Cheira taaao Good... ahem. Voce nao[n]Tem algum negocio aqui, certo? Vamos la.[n][w][e]

[msg MSG_LAST_GREETING_Cafe_A [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Viemos aqui varias vezes com[n]Akechi. If he were still around, I bet—[n]HM, nao importa.[n][w][e]

[msg MSG_LAST_GREETING_Cafe [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Se voce vai beber cafe, voce deveria[n]Faca isso em LeBlanc. Temos que ir ver todos[n]primeiro.[n][w][e]

[msg MSG_LAST_GREETING_Shop_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1191 65535 0]Nao e aqui que voces compraram oculos[n]Para o pai de Sumire?[n][w][e]
[s]Mais importante, por que voce ainda[n]Vestindo o seu?[n][w][e]

[msg MSG_LAST_GREETING_Shop_M_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Agora nao e hora de escolher[n]oculos. Vamos nos apressar e dizer adeus[n]para todos.[n][w][e]

[msg MSG_LAST_GREETING_FoodSh [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Esta e realmente uma loja da moda. Faz[n]Sua cidade natal tambem tem uma loja como essa?[n][w][e]

[msg MSG_LAST_GREETING_Statio [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Ha tanta colorida e elegante[n]Artigos de papelaria... e adequado para Kichijoji.[n][w][e]

[msg MSG_LAST_GREETING_Temple [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]O corredor aberto do templo era[n]quieto e muito tranquilo.[n][w][e]
[s][f 4 10 65535 0 0]Voce nao disse que sua cidade natal e legal[n]E silencioso tambem? Estou ansioso para isso.[n][w][e]

[msg MSG_LAST_GREETING_Temple_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Ei, voce nao conhece nenhum monges, nao e?[n]Vamos a algum outro lugar.[n][w][e]

[msg MSG_LAST_GREETING_OldClo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Agora nao e hora de procurar[n]Roupas de segunda mao na moda![n][w][e]

[msg MSG_LAST_GREETING_Dagash [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Isto me lembra. Eu me pergunto por que Sumire[n]estava nesta loja?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Bem, acho que nao importa.[n]Vamos dizer nossos adeus.[n][w][e]

[msg MSG_LAST_GREETING_Dagash_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Agora nao e hora de parar por[n]um lanche.[n][w][e]

[msg MSG_LAST_GREETING_Bank [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Eu nao me lembro de voce ter um banco[n]conta. Vamos para outro lugar.[n][w][e]

[msg MSG_LAST_GREETING_Ethnic [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Lembra daquele restaurante de sushi em Ginza?[n]Mmm. Voce sabe... eu nao me importo de girar[n]restaurantes de sushi tambem.[n][w][e]
[s][f 4 10 65535 0 0]Falando, sua cidade natal acontece[n]Estar perto do mar? Mal posso esperar para ver o que[n]tipo de lugar e![n][w][e]

[msg MSG_LAST_GREETING_HatSho [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1157 65535 0]Tantos chapeus elegantes... todos estes[n]Ficaria otimo em Haru![n][w][e]

[msg MSG_LAST_GREETING_Taiyak [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]Eu quero o melhor taiyaki ao redor. Bream do mar[n]panquecas em forma de feijao vermelho nelas...[n]Eles tem aqueles em sua cidade natal, certo?[n][w][e]

[msg MSG_LAST_GREETING_TeaHou [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1157 65535 0]Eu concordo, vamos comer alguns doces e relaxar[n]Com uma boa xicara de cha...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Eu quero dizer nao! Vai ser noite antes de sabermos[n]Se fizessemos isso! Digamos nossos adeus[n]Para todos enquanto o sol ainda esta fora.[n][w][e]

[msg MSG_LAST_GREETING_SocksS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1155 65535 0]Tenho certeza que voce ja sabe disso, mas estou[n]Nao esta usando meias brancas, ok?[n][w][e]

[msg MSG_LAST_GREETING_Teleph [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53124 65535 0]Seu telefone celular nos ajudou uma tonelada.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]De permanecer em contato com todos para[n]o navegador Metaverse... nos nao fariamos[n]Esteja aqui se nao fosse para o seu telefone.[n][w][e]

[msg MSG_LAST_GREETING_IceSho [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Voce sabe, Ryuji costuma comer com sabor de refrigerante[n]Barras de sorvete. Eu me lembro dele comendo[n]Um quando fomos a praia tambem.[n][w][e]

[msg MSG_LAST_GREETING_Fudous [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Voce sabe, se voltarmos aqui,[n]Eu quero morar em Yongen.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Voce nao acha assim tambem?[n][w][e]

[msg MSG_LAST_GREETING_MajorC [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Se voce estiver cheio agora, nao podera[n]Diga suas despedidas a todos.[n][w][e]

[msg MSG_LAST_GREETING_Ethnic_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Estou meio animado para ver seu quarto em[n]sua cidade natal. Como e?[n][w][e]

[msg MSG_LAST_GREETING_Realto [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Voce ja nao tem moveis em[n]Seu quarto em sua cidade natal?[n][w][e]

[msg MSG_LAST_GREETING_Karaok [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Sua cidade natal esta muito longe de[n]Aqui, certo? Vou cantar no trem para[n]mantenha voce entretido.[n][w][e]

[msg MSG_LAST_GREETING_Record [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Voce tem uma maquina que pode jogar[n]CDs gigantes em sua cidade natal?[n][w][e]

[msg MSG_LAST_GREETING_MusicT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Ei, voce sabia? Iwai toca o violao![n][w][e]

[msg MSG_LAST_GREETING_MusicT_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Vamos la, voce nao tem interesse em[n]Instrumentos, certo? Vamos a algum sitio[n]senao.[n][w][e]

[msg MSG_LAST_GREETING_Pasta_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Que loja de massas de aparencia chique.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Aposto que alguem como Kawakami realmente[n]como este lugar. Vamos traze-la aqui um dia.[n][w][e]

[msg MSG_LAST_GREETING_Pasta [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Que lugar sofisticado. Esta com fome[n]ou alguma coisa?[n][w][e]

[msg MSG_LAST_GREETING_Bicycl [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Nao vamos andar de bicicleta para casa...[n]Estamos pegando o trem, nao estamos?[n][w][e]

[msg MSG_LAST_GREETING_ToySho [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]O que voce esta fazendo olhando para brinquedos?[n]Vamos ver todos.[n][w][e]

[msg MSG_LAST_GREETING_SteakF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Aposto que Ryuji adoraria comer carne assim.[n]Talvez devemos vir aqui com ele[n]Da proxima vez que visitarmos.[n][w][e]

[msg MSG_LAST_GREETING_WineBa [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Um bar de vinhos, hein? Vamos voltar aqui[n]e beba com ohya quando voce e velho[n]o suficiente.[n][w][e]

[msg MSG_LAST_GREETING_WineBa_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Voce nao tem idade suficiente para beber ainda.[n]Vamos la, vamos para outro lugar.[n][w][e]

[msg MSG_LAST_GREETING_Antiqu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Seu quarto em LeBlanc parece bonito[n]antigo, mas como esta a sala em seu[n]cidade natal? Estou tao animado.[n][w][e]

[msg MSG_LAST_GREETING_DonutS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Voce se lembra da coisa do donut?[n]Tenho que admitir que fiquei muito impressionado[n]por suas habilidades de observacao.[n][w][e]

[msg MSG_LAST_GREETING_DonutS_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Voce quer donuts? Eles nao vendem aqueles[n]em sua cidade natal?[n][w][e]

[msg MSG_LAST_GREETING_Sports [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Aposto ir ao ar livre com todos[n]seria divertido.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Poderiamos pegar um carro de acampamento e apenas[n]viajar pelo pais.[n][w][e]

[msg MSG_LAST_GREETING_Realto_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Voce se lembra quando voce foi e se sentou[n]aqui embaixo? Voce deve ter realmente pensado[n]Este era confortavel.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Eu ficaria feliz se o sofa em sua cidade natal[n]era tao confortavel.[n][w][e]

[msg MSG_LAST_GREETING_Realto_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]Por que voce esta olhando para o sofa?[n]Voce esta ficando cansado?[n][w][e]

[msg MSG_LAST_GREETING_Realto_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Voce tem uma cadeira no seu quarto em seu[n]Cidade natal, certo? Acho que provavelmente ha[n]Porem, nao ha feixes para fazer treinamento, hein?[n][w][e]

[msg MSG_LAST_GREETING_AUTO_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Ei, nao temos tempo para beber[n]suco! Vamos dizer nossas despedidas,[n]certo?[n][w][e]

[msg MSG_LAST_GREETING_CoinLo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Voce nao podera voltar para conseguir[n]suas coisas por um tempo... provavelmente e[n]Melhor nao usar os armarios da moeda.[n][w][e]

[msg MSG_LAST_GREETING_Tobari [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1183 65535 0]O Oden aqui parecia tao bom, hein?[n]Esta fechado embora.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Havia tantos tipos de bebidas[n]aqui. Bem, esta fechado agora.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1191 65535 0]Este lugar era tao pequeno... realmente nao posso ir[n]para conferir novamente, pois esta fechado[n]no entanto.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]A cozinha deste lugar era tao pequena, mesmo o[n]O chefe ficaria surpreso. Esta fechado direito[n]Agora, porem, nao podemos realmente conferir.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Sinto um peixe fresco vindo daqui![n]... esta fechado embora.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_6 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1179 65535 0]Aquele tomate Oden parecia realmente saboroso, hein?[n]Porem, nao podemos comer nenhum agora, esta fechado.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_7 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Ha uma pequena loja no segundo andar.[n]Acho que se chama "Pelta Hot Spring". Faz[n]Isso significa que eles tem uma fonte termal aqui?[n][w][e]

[msg MSG_LAST_GREETING_Tobari_8 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Este lugar, "Tsuppari Banzuke", parece[n]Como se eles tivessem alguns pratos locais para comer.[n]"Tsuppari" nao e um termo de sumo?[n][w][e]

[msg MSG_LAST_GREETING_Tobari_9 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1034 65535 0]Este lugar e coberto com grafite.[n]Talvez voce deva vir aqui com[n]Yusuke algum dia.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_10 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1023 65535 0]Esta loja tem sorte de estar localizado em uma fantasia[n]rua. Bem, nao podemos verificar certo[n]Agora, esta fechado.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_11 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]O cheiro de frango frito la estava tao[n]seduzir... esta fechado agora.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_12 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Voce pode beber no piso tatami aqui,[n]certo? Mas nao podemos ver, pois esta fechado.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_13 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Lembro que eles tinham barris na loja.[n]Parecia que eles realmente se importavam com o[n]fantasia, apesar de quao pequeno era o lugar.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_14 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1001 65535 0]Temos que comer todos os tipos de asas aqui.[n]Parece que esta fechado.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_15 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]O nikuman parece muito bom, mas nos[n]Nao tenho tempo para comer agora.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_16 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]O ramen neste lugar sempre parece tao[n]Boa. Um dia desses eu quero ir para[n]Cada ramen compra em Toquio.[n][w][e]

[msg MSG_LAST_GREETING_Udon_1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Ah, sim, eu vi a entrevista de Hifumi.[n]Voce sabia que ela gostava de Udon?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Voce deve traze-la aqui um dia.[n][w][e]

[msg MSG_LAST_GREETING_Udon_1_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Pode ser um lugar onde voce pode ficar[n]e coma Udon, mas nao temos tempo[n]para isso agora.[n][w][e]

[msg MSG_LAST_GREETING_Deaden [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Sim, tenho certeza que os encontraremos no[n]lixo... inferno nao! Por que eles seriam[n]aqui!? Vamos indo![n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Vamos la, nao temos nada para fazer aqui.[n]Vamos para outro lugar![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Nao sabemos que ninguem passou dessa area. Vamos[n]Apresse-se e va para onde eles estao![n][w][e]

[msg MSG_LastKeyfree [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Mal podemos esperar mais...[n]Temos que nos preparar e rapido![n][w][e]

[msg MND_0103]
[s]Eu deveria descobrir o que[n]Meus amigos estao fazendo.[n][w][e]

[msg MND_TEMPLE_0103]
[s]......[n][w][e]
[s]Parece que eles estao[n]fechado ate o dia 8.[n][w][e]

[msg MND_0103to0108_Error_Not]
[s]Agora nao e a hora[n]para fazer compras.[n][w][e]
[s]Eu deveria ir verificar[n]para todos.[n][w][e]

[msg MND_0103to0108_Error_Not_2]
[s]Nao e hora de desvios.[n][w][e]
[s]Eu deveria ir verificar[n]para todos.[n][w][e]

[msg MND_CommonKeyFree]
[s]Ha algo que eu[n]Precisa fazer agora.[n][w][e]

[msg MSG_CommonKeyFree [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Voce nao tem negocios aqui.[n][w][e]

[msg MND_Juice_NotOpen]
[s]Nao estou com sede agora.[n][w][e]

[msg MSG_Juice_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Voce esta pensando em comprar algo[n]para beber?[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Tudo esta esgotado... vamos esperar por isso[n]para ser reabastecido na proxima semana.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Opa, tudo esta esgotado. Vamos esperar[n]para que seja reabastecido na proxima semana.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]... tudo esta esgotado. Eu acho que nao e[n]Surpreenda com o quao quente esta agora...[n][w][e]

[msg MSG_KF794101_AddInfo [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]Vamos la, vamos nos apressar para o lounge dos dardos.[n][w][e]

[msg MSG_GATE_DEAFULT_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Voce vai viajar para outra area?[n][w][e]

[sel SEL_GATE_YESNO_moru top]
[s]Sim, vamos la.[e]
[s]Nao, ainda nao.[e]

[msg MND_GATE_0103]
[s]Vamos para uma area diferente...[n][w][e]

[msg MSG_GOTO_Kichijoji2Shibu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Alem desta area, e a linha Inogami.[n]Pagar 200 ienes o levara a Shibuya.[n]Voce quer ir?[n][w][e]

[sel SEL_GOTO_Kichijoji2Shibu top]
[s]Isso soa bem.[e]
[s]Nao vamos.[e]

[msg MSG_GOTO_Kichijoji2Shibu_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1001 0 0]Oh, voce nao tem dinheiro suficiente?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Vou te dar um pouco do meu esconderijo secreto para[n]agora, mas verifique se voce tem alguns com[n]voce na proxima vez.[n][w][e]

[msg MSG_GOTO_Kichijoji2Shibu_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Nao ha nada que voce precise fazer aqui,[n]certo? Vamos a algum outro lugar![n][w][e]

[msg MSG_GOTO_Kichijoji2Shibu_4]
[s]Nao ha nada que eu precise fazer[n]por aqui. Eu deveria voltar...[n][w][e]

[msg MSG_KF794101_InfoCenter [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]Uma mesa de informacoes da cidade...? Eu acho que voce[n]Na verdade, nao veja coisas assim em outras cidades.[n][w][e]

[msg MSG_InfoCenter [Information Desk Lady]]
[s][vp 8 2 1 58671 1 0]Ola! Fazemos o nosso melhor para fornecer[n]Informacoes sobre esta area![n][w][e]

[msg MSG_InfoCenter02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Por que voce nao pergunta a eles sobre Kichijoji?[n][w][e]

[msg MND_InfoCenter02]
[s]O que eu quero saber sobre Kichijoji...[n][w][e]

[msg MSG_InfoCenter_start [Information Desk Lady]]
[s][vp 8 2 1 58672 1 0]O que voce gostaria de ouvir?[n][w][e]

[sel SEL_InfoCenter top]
[s]Sobre esta cidade.[e]
[s]O que voce recomenda?[e]
[s]Sobre as lojas.[e]
[s]Alguma coisa que eu deveria saber?[e]
[s]Nada.[e]

[msg MSG_InfoCenter01_01 [Information Desk Lady]]
[s][vp 8 2 1 58673 1 0]Certamente! Por favor permita-me explicar![n][w][e]
[s][vp 8 2 1 0 1 0]Existem quatro areas diferentes...[n][w][e]
[s][vp 8 2 1 0 1 0]No passeio, voce pode encontrar um frito[n]loja de alimentos, uma artigos de papelaria, uma segunda-[n]loja de roupas de mao e um templo.[n][w][e]
[s][vp 8 2 1 0 1 0]A costela de carne moida na comida frita[n]loja e deliciosa, mas voce tera que[n]espere na fila.[n][w][e]
[s][vp 8 2 1 0 1 0]Se voce der uma esquerda na loja de alimentos fritos,[n]Voce vera a Retro Street. Aqui voce pode encontrar um[n]Selecao de lojas chiques e sofisticadas.[n][w][e]
[s][vp 8 2 1 0 1 0]Ha tambem um clube de jazz no final do[n]beco. As vezes, cantores populares vao[n]La, e a vivacidade e inevitavel.[n][w][e]
[s][vp 8 2 1 58674 1 0]Ufa. Espero ter explicado tudo certo...[n]Voce tem outras perguntas?[n][w][e]

[sel SEL_InfoCenter01_Inter top]
[s]Por favor continue.[e]
[s]Eu acho que vou ficar bem.[e]

[msg MSG_InfoCenter01_02 [Information Desk Lady]]
[s][vp 8 2 1 58676 1 0]E claro![n][w][e]
[s][vp 8 2 1 0 1 0]Depois de passar pela rua retro, voce vera[n]Rue de Chouchou, que tem uma variedade[n]de lojas sofisticadas para visitar.[n][w][e]
[s][vp 8 2 1 0 1 0]Ha tambem um cristal de cura bem conhecido[n]lojas vendendo pedras de energia que fornecem[n]resultados reais.[n][w][e]
[s][vp 8 2 1 0 1 0]Nao apenas isso, mas na rue de chouchou[n]ha um lounge para desfrutar de dardos e[n]bilhar. A emocao e inevitavel.[n][w][e]
[s][vp 8 2 1 0 1 0]O ultimo e o Harmony Alley, que e[n]Como um distrito de bebida. Esta localizado apenas[n]PASSO ESTE DESCURSO DE INFORMACOES.[n][w][e]
[s][vp 8 2 1 0 1 0]Tem um velho sabor japones, perfeito[n]para apenas apreciar a atmosfera. o[n]A inspiracao e inevitavel.[n][w][e]
[s][vp 8 2 1 0 1 0]... isso era muita informacao para[n]um menor?[n][w][e]
[s][vp 8 2 1 0 1 0]Bem, e isso para a cidade. Existe[n]algo mais eu posso ajuda-lo?[n][w][e]

[msg MSG_InfoCenter02_01 [Information Desk Lady]]
[s][vp 8 2 1 58673 1 0]Eu sei exatamente a coisa! Por favor permita[n]Eu explicar! Voce e um menor correto?[n]Se for esse o caso...[n][w][e]
[s][vp 8 2 1 0 1 0]Se voce passar pelo distrito de bebida e[n]Alcance a rue de chouchou, voce encontrara um[n]Darts e Billiards Lounge.[n][w][e]
[s][vp 8 2 1 0 1 0]Na verdade e um lugar muito casual, e pessoas[n]Sua idade pode entrar sem nenhum problema.[n][w][e]

[sel SEL_InfoCenter02_Inter top]
[s]Que tal para adultos?[e]
[s]Que tal algum lugar unico?[e]

[msg MSG_InfoCenter02_02 [Information Desk Lady]]
[s][vp 8 2 1 58675 1 0]Huh!? Bem, voce veio todo o[n]caminho aqui...[n][w][e]
[s][vp 8 2 1 0 1 0]Se voce esta procurando um lugar para adultos...[n]Ha um clube de jazz...[n][w][e]
[s][vp 8 2 1 0 1 0]E acho que os menores podem entrar...[n]Desculpe pela minha falta de conhecimento.[n][w][e]
[s][vp 8 2 1 0 1 0]Gostaria de saber mais alguma coisa?[n][w][e]

[msg MSG_InfoCenter02_03 [Information Desk Lady]]
[s][vp 8 2 1 58677 1 0]Oh sim! Uma das joias escondidas da cidade[n]e o templo no passeio.[n][w][e]
[s][vp 8 2 1 0 1 0]E ate popular entre os jovens[n]que estao procurando alguma orientacao.[n][w][e]
[s][vp 8 2 1 0 1 0]Oh, talvez isso realmente nao inclua[n]alunos como voce...? Haha. Se voce sempre[n]Interessado, voce deve conferir.[n][w][e]
[s][vp 8 2 1 0 1 0]Houve mais alguma coisa que voce queria[n]ouvir sobre?[n][w][e]

[msg MSG_InfoCenter03_01 [Information Desk Lady]]
[s][vp 8 2 1 58673 1 0]Certamente! Permita-me explicar![n][w][e]
[s][vp 8 2 1 0 1 0]There's a strange— Excuse me, a unique[n]Loja de roupas de segunda mao aqui tambem.[n][w][e]
[s][vp 8 2 1 0 1 0]Esta localizado na rua Promenade.[n]O gerente sempre me cumprimenta no[n]manha, mas...[n][w][e]
[s][vp 8 2 1 0 1 0]Ele esta sempre dizendo: "Eu quero especificamente[n]roupas fuligem. "E e bastante exigente sobre[n]O que voce traz tambem.[n][w][e]
[s][vp 8 2 1 0 1 0]Ah, e voce ja esteve no incenso[n]armazenar em Harmony Alley? Na verdade[n]abriu recentemente.[n][w][e]
[s][vp 8 2 1 0 1 0]Eles tem incensos que as pessoas tem[n]nunca ouvi falar de antes. E os seus[n]Tambem nao e uma loja de peixe.[n][w][e]
[s][vp 8 2 1 0 1 0]Havia mais alguma coisa que voce queria[n]perguntar?[n][w][e]

[msg MSG_InfoCenter04_01 [Information Desk Lady]]
[s][vp 8 2 1 58678 1 0]Qualquer coisa que voce deve saber... na verdade,[n]sim. Ha algo que ouvi recentemente.[n][w][e]
[s][vp 8 2 1 0 1 0]Sobre a loja de alimentos fritos no[n]passeio. As pessoas dizem que e tedioso[n]esperar na fila...[n][w][e]
[s][vp 8 2 1 0 1 0]E a noite, ja esta esgotado.[n]Entao, o que devemos fazer se queremos um?[n][w][e]
[s][vp 8 2 1 0 1 0]Bem, eles dizem aos domingos que fazem[n]Mais do que o normal.[n][w][e]
[s][vp 8 2 1 0 1 0]Entao, em outras palavras, se voce for la em um[n]Domingo a noite... e a historia que ouvi[n]termina ai.[n][w][e]
[s][vp 8 2 1 0 1 0]Mais alguma coisa que voce gostaria de saber?[n][w][e]

[msg MSG_InfoCenter05_01 [Information Desk Lady]]
[s][vp 8 2 1 58680 1 0]Se voce gostaria de saber mais sobre[n]Kichijoji, fique a vontade para parar![n][w][e]

[msg MSG_InfoCenter_00 [Information Desk Lady]]
[s][vp 8 2 1 58679 1 0]Havia algo mais que voce queria[n]perguntar?[n][w][e]

[msg MSG_InfoCenter_ParamUp [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 1 0]Ufa... isso foi muito[n]em formacao. Eu acho que fomos capazes de[n]Amplie nossas ideias sobre Kichijoji![n][w][e]

[msg MND_InfoCenter_ParamUp]
[s]Eu sinto que tenho ampliado[n]minhas ideias...![n][w][e]

[msg MSG_InfoCenter_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Parece que esta fechado.[n][w][e]
[s][f 4 10 65535 0 0]Se voce tiver duvidas, voce deve vir[n]de volta aqui durante o dia.[n][w][e]

[msg MND_InfoCenter_heiten]
[s]Parece que esta fechado...[n][w][e]
[s]Eu deveria voltar[n]Aqui outra hora.[n][w][e]

[msg MSG_KF794101_FriedShop [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Puta merda, olhe para a linha! Eu acho que vi[n]Este lugar na TV.[n][w][e]

[msg MSG_FriedShop_NG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Ooh, cheira tao bem! Parece o[n]Costete de carne moida aqui e realmente popular.[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]Mas cara, olhe para a linha... vai levar[n]para sempre a esse ritmo. Vamos desistir.[n][w][e]

[msg MND_FriedShop_NG]
[s]Cheira muito bom, mas...[n][w][e]
[s]A linha parece muito longa...[n]Eu deveria tentar novamente outra hora.[n][w][e]

[msg MSG_FriedShop_NG_Night [Fried Food Shop Staff]]
[s][vp 8 2 1 0 2 0]Oh, voce esta aqui para o nosso popular[n][clr 3]Chunky Katsu[clr 27]? Desculpe, mas estamos[n]esgotado para hoje...[n][w][e]
[s][vp 8 2 1 0 2 0]Tente parar em um dia diferente.[n]Podemos ter entao.[n][w][e]

[msg MSG_FriedShop_OK [Fried Food Shop Staff]]
[s][vp 8 2 1 0 2 0]Bem-vindo. Aqui esta o seu[clr 3]Chunky Katsu[clr 27].[n]E o ultimo tambem.[n][w][e]

[msg MSG_FriedShop_Thanks [Fried Food Shop Staff]]
[s][vp 8 2 1 0 2 0]Obrigado! Tenha cuidado, esta quente.[n][w][e]

[msg MSG_FriedShop_NotBuy [Fried Food Shop Staff]]
[s][vp 8 2 1 0 2 0]Nao esta com disposicao para um hoje?[n][w][e]

[msg MSG_FriedShop_SoldOut [Fried Food Shop Staff]]
[s][vp 8 2 1 0 2 0]Desculpe, esse foi o ultimo.[n]Venha de novo por segundos, ok?[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_DART]
[s]Agora voce pode viajar rapido para[n][clr 6]Dardos e bilhar[clr 0]Em Kichijoji.[n][w][e]

[msg MSG_JazzClub_PreStart [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]E o clube de jazz que Akechi apresentou[n]voce para.[n][w][e]

[msg MSG_Jazzclub_Start_1st02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Lugares como isso ajudarao voce a relaxar. E[n]falar sobre coisas que voce normalmente[n]achar dificil de.[n][w][e]
[s][f 4 10 65535 0 0]Hum. Como lider do Phantom[n]Ladroes, talvez voce possa convidar um dos[n]os membros aqui.[n][w][e]

[sel SEL_Jazzclub_1st top]
[s]Nao e uma ma ideia...[e]
[s]Me pergunto o que todo mundo esta fazendo...[e]

[msg MSG_JazzClub_Ck_info_1st [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]Oh, parece que para menores eles servirao[n]"[clr 2]coqueteis nao alcoolicos[clr 27]. "[n][w][e]

[msg MSG_JazzClub_Ck_info_Com [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]Hmm, parece que o coquetel desta noite e[n]"[clr 2][var 0][clr 27]. "[n][w][e]

[msg MSG_JazzClub_Ck_info_Get [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"E tao bom que vai te dar mais[n][clr 2]energia[clr 27]! Traga sua resistencia ao[n][clr 2]proximo nivel[clr 27]! "[n][w][e]

[msg MSG_JazzClub_Ck_info_Kay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"O sabor desta bebida vai te dar[n][clr 2]potencia[clr 27]E[clr 2]sorte[clr 27]! Voce sera capaz de[n][clr 2]defender[clr 27]voce mesmo contra qualquer coisa! "[n][w][e]

[msg MSG_JazzClub_Ck_info_Sui [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"Deixe sua[clr 2]alma[clr 27]Abra com este coquetel[n]e leve-se para o[clr 2]proximo nivel[clr 27]! "[n][w][e]

[msg MSG_JazzClub_Ck_info_Mok [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"Deixe sua[clr 2]Rapidez[clr 27]e[clr 2]sorte[clr 27]explodir com[n]Os ingredientes especiais nesta bebida![n]Deixe-se ser coberto em[clr 2]Magia[clr 27]! "[n][w][e]

[msg MSG_JazzClub_Ck_info_Kin [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"[clr 2]Todas as suas estatisticas[clr 27]melhorara! este[n]bebida maravilhosa ajudara o seu[n][clr 2]energia[clr 27]e[clr 2]alma[clr 27]! "[n][w][e]

[msg MSG_JazzClub_Ck_info_Nit [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"Bebida original de hoje! Talvez voce[n]ser capaz de descobrir um novo lado de si mesmo,[n]Talvez um que voce nunca soube!? "[n][w][e]

[msg MSG_JazzClub_Ck_info_End [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Parece muito bom![n][w][e]

[msg MSG_Jazz_TodaySinger_Tut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Huh, parece que existem[n]dias[clr 2]Um cantor entra[clr 27]...[n][w][e]

[msg MSG_Jazz_TodaySingerOK [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Oh, confira! Hoje e um dia que um[n]Singer esta chegando![n][w][e]

[msg MSG_JazzClub_AskUse [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]Voce quer ir ouvir? Parece que e[n]vou te custar[clr 2]3.000 ienes[clr 27].[n][w][e]

[sel SEL_Jazzclub_UseThink top]
[s]Convidar alguem[e]
[s]Confira o sinal[e]
[s]Cancelar[e]

[msg MSG_Jazz_NextSingerDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]O cantor esta chegando[clr 2][var 1]/[var 2][clr 27]![n]Bebendo coqueteis enquanto ouve[n]Musica ao vivo... soa bem adulto, hein?[n][w][e]

[msg MSG_Jazzclub_NoMoreSinge [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hum. E um pouco decepcionante, mas[n]Nao parece que ha alguma mencao[n]de quando o cantor esta chegando...[n][w][e]

[msg MSG_Jazzclub_Who_Invite [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Quem voce vai convidar?[n][w][e]

[sel SEL_SELECT_FRIEND top]
[s]Em branco: Isso nao e usado[e]
[s]Protag: Isso tambem nao sera usado.[e]
[s]Ryuji[e]
[s]Morgana[e]
[s]Ann[e]
[s]Yusuke[e]
[s]Makoto[e]
[s]Haru[e]
[s]Futaba[e]
[s]Akechi[e]
[s][f 4 31 10 1][e]

[msg MSG_Jazz_FRIEND [Morgana]]
[s][bup 0 3 1 0 0][vp 8 2 1 1167 65535 0][f 4 10 65535 0 0]Oh,[var 3], Ha?[n][w][e]

[sel SEL_NPC_SELECT top]
[s]Sim.[e]
[s]Deixe-me pensar sobre isso.[e]

[msg MSG_FRIEND_NG [Morgana]]
[s][bup 0 3 0 0 0][vp 8 2 1 1185 65535 0][f 4 10 65535 0 0]Entao, quem voce vai convidar?[n][w][e]

[msg MSG_Jazzclub_Moru_Bye [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Entao eu vou dar um passeio. Apenas deixe[n]Eu sei quando estamos indo para casa.[n][w][e]

[msg MSG_Jazzclub_Moru_NotBye [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Gostaria de saber se eu gostaria dos coqueteis.[n]Acho que vou ter que tentar![n][w][e]

[msg MSG_Jazzclub_NoMoney [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Vai custar 3.000 ienes.[n]Parece que voce nao tem o suficiente...[n][w][e]

[msg MSG_KF794101_JazzClub [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7024 65535 0]Um clube de jazz, hein? Parece algum tipo de segredo[n]Escondimento para adultos.[n][w][e]

[msg MSG_JazzClub_Lock [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Um clube de jazz... eu me pergunto que tipo de[n]Coloque esta la embaixo.[n][w][e]

[msg MND_JazzClub_Lock]
[s]Parece que e um clube de jazz...[n][w][e]
[s]Eu nem consigo imaginar[n]Como e la embaixo.[n][w][e]

[msg MND_JazzClub_PreStart]
[s]E o clube de jazz que Akechi mostrou[n]Eu... talvez eu deva entrar.[n][w][e]

[msg MSG_JazzClub_PreStartNot [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]E o clube de jazz que Akechi apresentou[n]voce, mas parece que so esta aberto em[n]noite.[n][w][e]

[msg MND_JazzClub_PreStartNot]
[s]E o clube de jazz[n]Akechi me mostrou...[n][w][e]
[s]Mas esta apenas aberto a noite.[n]Eu deveria voltar outra vez.[n][e]

[msg MSG_JazzClub_StartNotNig [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Oh, parece o unico clube de jazz apenas aberto[n]a noite.[n][w][e]

[msg MND_JazzClub_StartNotNig]
[s]Parece estar aberto durante o dia.[n]Talvez eu pare na proxima vez.[n][w][e]

[sel SEL_Jazzclub top]
[s]Digitar[e]
[s]Cancelar[e]

[msg MSG_SYSTEM_SHORTCUT_JUZZ]
[s]Agora voce pode viajar rapido para o[n][clr 6]Clube de jazz[clr 0]Em Kichijoji.[n][w][e]

[msg MSG_JazzClub_Alpha [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]※本来は明智コープランク3で解禁しますが、[n] α1では強制的に解禁状態にします[n][w][e]

[msg MSG_Accessories_Start [Crystal Healing Employee]]
[s][vp 8 2 1 0 4 0]Bem-vindo! Por favor, de uma olhada no que[n]temos![n][w][e]

[msg MSG_Accessories_THANKS [Crystal Healing Employee]]
[s][vp 8 2 1 0 4 0]Obrigada! Por favor, venha de novo![n][w][e]

[msg MSG_Accessories_NOT_BUY [Crystal Healing Employee]]
[s][vp 8 2 1 0 4 0]Oh, esta certo? Por favor, volte![n][w][e]

[msg MSG_KF794101_Variety [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]Uma loja de incenso? Parece totalmente suspeito[n]para mim.[n][w][e]

[msg MSG_Variety_Start [Incense Shop Staff]]
[s][vp 8 2 1 0 3 0]Ah, um cliente! Por favor, aproveite o nosso especial[n]Perfumes![n][w][e]

[msg MSG_Variety_THANKS [Incense Shop Staff]]
[s][vp 8 2 1 0 3 0]Obrigado novamente![n][w][e]

[msg MSG_Variety_NOT_BUY [Incense Shop Staff]]
[s][vp 8 2 1 0 3 0]Por favor, venha novamente algum tempo![n][w][e]

[msg MSG_Variety_NotOpen [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Wh-whoa, o cheiro...[n]Nao sei se meu nariz pode lidar com isso.[n][w][e]
[s][f 4 10 65535 0 0]Eu nao sabia que voce estava em incensos...[n]Se voce nao estiver, vamos sair aqui.[n][w][e]

[msg MSG_FoodShop_NotInfo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Eles estao vendendo muitas coisas de estrangeiras[n]paises. Cara, eu quero ir para um de[n]Esses dias...[n][w][e]

[msg MSG_FoodShop_NotInfo_Aft [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Parece que eles vendem muitas coisas de[n]paises diferentes. Entao, o que era principal[n]coisa que eles venderam no Havai?[n][w][e]

[msg MND_FoodShop_NotInfo_Aft]
[s]Parece que eles principalmente[n]vender mantimentos importados.[n][w][e]
[s]Nao ha nada que eu precise daqui.[n][w][e]

[msg MSG_FoodShop_Start [Grocery Clerk]]
[s][vp 8 2 1 0 4 0]Bem-vindo! Por favor, sinta-se a vontade para desfrutar[n]Os gostos dos paises em todo o mundo![n][w][e]

[msg MSG_FoodShop_THANKS [Grocery Clerk]]
[s][vp 8 2 1 0 4 0]Muito obrigado! Por favor, venha de novo![n][w][e]

[msg MSG_FoodShop_NOT_BUY [Grocery Clerk]]
[s][vp 8 2 1 0 4 0]Obrigado novamente![n][w][e]

[msg MSG_Stationer_Start [Stationery Store Employee]]
[s]Ola e bem-vindo. Nos temos bastante[n]de itens aqui voce pode presentear os outros.[n][w][e]

[msg MSG_Stationer_THANKS [Stationery Store Employee]]
[s]Obrigado pela sua compra![n]Estamos ansiosos para a sua proxima visita.[n][w][e]

[msg MSG_Stationer_NOT_BUY [Stationery Store Employee]]
[s]Por favor, venha novamente.[n][w][e]

[msg MSG_OldClothe_NotOpen_No [Secondhand Clothes Employee]]
[s]Oh, ola... voce quer vender roupas?[n][w][e]
[s]Huh... todos eles parecem bem normais...[n]Ja temos roupas assim em[n]esta loja.[n][w][e]

[msg MSG_OldClothe_NotOpen_No_2 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1026 65535 0]Oh o que? Ele nao vai comprar de[n]nos? Voce tem algo diferente?[n][w][e]

[msg MSG_OldClothe_NotOpen_No_3 [Secondhand Clothes Employee]]
[s]Estou procurando mais por[clr 2]roupas de fuligem[clr 27]...[n]Voce sabe, como se fossem quase lixo.[n]Se eu pudesse encontrar roupas assim...[n][w][e]

[msg MSG_OldClothe_NotOpen_No_4 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Bem, diz-se que a carne envelhecida tem gosto[n]Melhor... talvez seja o mesmo para as roupas?[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Ele disse algo sobre[clr 2]roupas fuligem[clr 27]...[n]Vamos voltar aqui novamente quando tivermos[n]algum.[n][w][e]

[msg MSG_OldClothe_NotOpen_Ye [Secondhand Clothes Employee]]
[s]Bem-vindo, se voce deseja vender[n]clothing— W-Wait, what's that?[n][w][e]
[s]Posso dar uma olhada nisso? Nao se preocupe,[n]Eu nao vou roubar.[n][w][e]

[msg MSG_OldClothe_NotOpen_Ye_2 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Esse cara esta reagindo as roupas que nos[n]Tenho sombras... parece que ele sabe[n]do que ele esta falando.[n][w][e]

[msg MSG_OldClothe_NotOpen_Ye_3 [Secondhand Clothes Employee]]
[s]Estou aqui ha 40 anos, mas nunca[n]Visto roupas que fazem meu coracao relaxar...[n][w][e]
[s]Tudo bem, eu vou comprar. Mas so vou comprar para[n]O preco que merece.[n][w][e]
[s]Entao, temos um sistema de cartao pontual aqui.[n]Cada[clr 2]peca de roupa[clr 27]voce vende aqui vai[n]te dar[clr 2]10 pontos[clr 27].[n][w][e]
[s]Depois de obter pontos suficientes, voce pode[n]troca-los por um premio. Entao fique a vontade para deixar[n]Nos tiramos essa roupa de suas maos.[n][w][e]

[msg MSG_OldClothe_NotOpen_Ye_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Nao so ele vai compra-los de nos,[n]Ele vai nos dar pontos para eles tambem?[n]Definitivamente, deveriamos voltar aqui.[n][w][e]

[msg MSG_OldClothe_Start [Secondhand Clothes Employee]]
[s]Entao, o que posso fazer por voce?[n][w][e]

[msg MSG_OldClothe_Start_loop [Secondhand Clothes Employee]]
[s]Algo mais?[n][w][e]

[sel SEL_OldClothe_bunki top]
[s]Eu quero vender.[e]
[s]Deixe-me ver os premios.[e]
[s]Nada.[e]

[msg MSG_OldClothe_SelCancel [Secondhand Clothes Employee]]
[s]Nao? Bem, isso e muito ruim...[n][w][e]

[msg MSG_OldClothe_Start_NotH [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ei, voce nao tem roupas para vender[n]agora mesmo.[n][w][e]

[msg MSG_OldClothe_AnySell [Secondhand Clothes Employee]]
[s]Entao voce vendeu[var 2]pedacos de roupa...[n]Hm, isso vai te levar[clr 2][var 0][clr 27]pontos.[n][w][e]
[s]E agora voce tem[clr 2][var 1][clr 27]pontos.[n][w][e]

[msg MSG_OldClothe_give_end [Secondhand Clothes Employee]]
[s]Se voce quiser mais pontos, basta vender o[n]roupas que voce tem.[n][w][e]

[msg MSG_OldClothe_give_end_s [Secondhand Clothes Employee]]
[s]Espero que voce tenha gostado das coisas que tivemos em[n]a loja.[n][w][e]
[s]Se voce quiser mais pontos, basta vender o[n]roupas que voce tem.[n][w][e]

[msg MSG_OldClothe_Bey [Secondhand Clothes Employee]]
[s]Essas roupas sao incriveis...[n]Venha de novo, tudo bem?[n][w][e]

[msg MSG_OldClothe_Bey_Nosell [Secondhand Clothes Employee]]
[s]Venha nos vender mais coisas, ok?[n]Eu estarei esperando.[n][w][e]

[msg MSG_Hurugi_Start [Morgana]]
[s][bup 0 3 11 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Eu sempre quero saber o que esta dentro disso[n]material. Vamos dar uma olhada![n][w][e]

[msg MSG_Hurugi_end [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Nao e tao ruim. Vamos pegar isso de novo algum tempo.[n][w][e]

[msg MSG_Temple_Night [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Nao parece que o templo aceita[n]pessoas a noite. Vamos tentar voltar[n]aqui durante o[clr 2]dia[clr 27].[n][w][e]

[msg MSG_Temple_Daily [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Aposto ter um templo em uma compra[n]O distrito realmente ajuda os negocios.[n][w][e]

[msg MND_Temple_Night]
[s]Parece que eles nao aceitam[n]pessoas a noite. Eu devo vir[n]de volta durante o[clr 2]dia[clr 27]...[n][w][e]

[msg MSG_Temple_1st_info [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Uau. Pensar que haveria um templo[n]dentro de uma cidade.[n][w][e]
[s][f 4 10 65535 0 0]Ei, confira a placa. "Em ordem de[n]Ganhe uma vida gratificante, voce deve primeiro comecar[n]entendendo-se. "[n][w][e]
[s][f 4 10 65535 0 0]Meditando no templo, hein? Parece[n]Como voce pode fazer isso durante o dia.[n][w][e]

[msg MSG_Temple_NotHaveCard [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Oh, voce nao vai parar?[n][w][e]

[msg MSG_Temple_AskUse_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Talvez se voce meditar e acalmar seu[n]Lembre-se, voce podera aprender algo.[n][w][e]

[msg MSG_Temple_AskUse_002 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Qual e o plano? Voce vai meditar[n]no templo?[n][w][e]

[sel SEL_TempleUse top]
[s]Vamos dar uma olhada.[e]
[s]Veja meu status atual.[e]
[s]Nao agora.[e]

[msg SYS_ShortCut_Temple]
[s]Agora voce pode viajar rapido para[n]a[clr 6]tempora[clr 0]Em Kichijoji.[n][w][e]

[msg MSG_Cafe [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]What a fancy looking café. If I ever were[n]to invite Lady Ann somewhere— Why're[n]Voce esta olhando para mim assim?[n][w][e]

[msg MND_Cafe]
[s]It's a fancy looking café.[n][w][e]
[s]Parece sua especialidade[n]e cafe assado em casa.[n][w][e]

[msg MSG_Shop_Megane [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Seus oculos sao falsos, certo? E dificil[n]Diga a menos que voce olhe para eles de perto...[n][w][e]

[msg MND_Shop_Megane]
[s]......[n][w][e]
[s]Meus oculos sao falsos.[n]Eu nao preciso altera-los.[n][w][e]

[msg MSG_KF794101_Deadend_mea [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Parece que ha apenas armazenar[n]este lado.[n][w][e]

[msg MSG_Deadend_meat [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Parece que as lojas interessantes estao de volta[n]la. Vamos voltar.[n][w][e]

[msg MND_Deadend_meat]
[s]Nao ha nada que[n]me interessa. Eu deveria voltar.[n][w][e]

[msg MSG_KF794101_Deadend_Iza [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7028 65535 0]Droga, eu apenas bati no meu cotovelo. Por que isso[n]colocar em um espaco tao pequeno?[n][w][e]

[msg MSG_Deadend_Izakaya [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Dang, parece um beco sem saida. E como um[n]labirinto aqui.[n][w][e]

[msg MND_Deadend_Izakaya]
[s]E um beco sem saida...[n][w][e]

[msg MSG_KF794101_Deadend_Meg [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Aquele lugar que estamos procurando deve ser[n]por aqui. Vamos voltar.[n][w][e]

[msg MSG_Deadend_Megane [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Nao vejo nada de passado interessante aqui.[n]Vamos voltar.[n][w][e]

[msg MND_Deadend_Megane]
[s]Nao ha nada que[n]Eu preciso fazer a frente.[n][w][e]

[msg MSG_KF794101_Deadend_Caf [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Nao ha mais lojas lotta, hein.[n]Vamos voltar.[n][w][e]

[msg MSG_Deadend_Cafe [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Parece que esta area tem mais casas[n]do que lojas...[n][w][e]

[msg MND_Deadend_Cafe]
[s]Parece que e mais um[n]Area residencial passada aqui.[n][w][e]

[msg MSG_KF794101_Deadend_Jaz [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7029 65535 0]Esta area tem mais lojas para adultos.[n]Vamos olhar para outro lugar.[n][w][e]

[msg MSG_Deadend_Jazz [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Parece que ha mais lojas maduras[n]por aqui... vamos voltar.[n][w][e]

[msg MND_Deadend_Jazz]
[s]Esta area tem lojas mais maduras...[n][w][e]
[s]Vamos voltar.[n][w][e]

[msg MSG_VELVET_GIRL_LOUD01 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 2 1 11018 65535 0]Voce nao tem tempo para jogar[n]ao redor, preso![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Apresse-se de volta para sua prisao![n][w][e]

[msg MSG_VELVET_GIRL_Lavenza [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55422 65535 0]Esses ensaios... eu acredito que voce pode[n]supere-os.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_VELV]
[s]Agora voce pode viajar rapido para o[n][clr 6]Sala de veludo[clr 0].[n][w][e]

[msg MSG_Dagashi_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Confira o que ha nessas exibicoes...[n][w][e]
[s]Um especial de Kichijoji, "Dorayaki com[n]castais e pasta de feijao vermelho "?[n]Parece mais um hamburguer...[n][w][e]

[msg MND_Dagashi_001]
[s]"Dorayaki com castanhas[n]e pasta de feijao vermelho. "[n][w][e]
[s]... Parece um hamburguer.[n][w][e]

[msg MSG_Dagashi_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Ja esta fechado, mas voce cheira[n]aquele perfume doce?[n][w][e]

[msg MND_Dagashi_heiten]
[s]Eu posso sentir o cheiro doce[n]de castanhas daqui...[n][w][e]

[msg MSG_Bank_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]E um banco. Voce sabe eu sempre[n]me perguntei por que eles chamam assim...[n][w][e]

[msg MND_Bank_001]
[s]Nao ha nada que eu precise[n]fazer no banco...[n][w][e]

[msg MSG_Bank_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Parece que o banco esta fechado... quero dizer,[n]Esta fora do horario comercial. Nos iremos,[n]Nao e como se tivessemos que usa-lo de qualquer maneira.[n][w][e]

[msg MND_Bank_heiten]
[s]O banco esta atualmente fechado...[n][w][e]
[s]Mas parece que ainda ha alguns[n]funcionarios trabalhando...[n][w][e]

[msg MSG_HatShop_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]E uma loja de chapeus para os idosos.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Por que voce nao usa um chapeu para mergulhar[n]Seu cabelo encaracolado?[n][w][e]

[msg MND_HatShop_001]
[s]E uma loja de chapeus para os idosos.[n][w][e]
[s]... Talvez eu use um chapeu um dia.[n][w][e]

[msg MSG_HatShop_heiten [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]Tudo que voce ve sao persianas a noite...[n]Parece um pouco sozinho.[n][w][e]

[msg MSG_Taiyaki_Open [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Vamos, eles chamam isso de peixe, mas e apenas[n]Taiyaki, certo? Voce acha que eu realmente[n]be satisfied with— Hm?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]"Vamos fornecer um novo e organico[n]peca toda vez. "Pode Taiyaki ate[n]ser fresco e organico?[n][w][e]

[msg MND_Taiyaki_Open]
[s]"Vamos fornecer um novo e[n]peca organica toda vez. "[n][w][e]
[s]Eles devem ter um especifico[n]como eles estao fazendo isso...[n][w][e]

[msg MSG_Taiyaki_Close [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Por que voce acha que eles escolheram um vermelho[n]Snapper para o peixe? Poderia ter sido[n]Algum peixe, certo?[n][w][e]

[msg MSG_TelephoneShop_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Oh, voce vai me comprar um telefone celular?[n]Certifique-se de me dar o mais novo, tudo bem?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]...Estou brincando. Estou saindo do[n]comunicacao com os outros caras[n]para voce.[n][w][e]

[msg MND_TelephoneShop_001]
[s]"Resistente a agua, tela enorme, alta[n]capacidade, compativel com 4K! "Parece[n]Eles estao anunciando o novo telefone.[n][w][e]
[s]Estou bem com o que tenho agora.[n][w][e]

[msg MSG_TelephoneShop_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Voce ja viu esses telefones celulares com[n]rachaduras na tela?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Eu me pergunto se ele pode cortar o dedo.[n]Eu sinto que isso iria cair imediatamente...[n][w][e]

[msg MSG_IceShop_001 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Cafe, morango, cha verde... parece[n]Eles tem todos os tipos de sabores.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Oh! Que tal sorvete com sabor de sushi?[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]...Deixa para la. Eu quase vomitei apenas[n]a pensar nisso...[n][w][e]

[msg MND_IceShop_001]
[s]Ha muitos diferentes[n]sorvete com sabor.[n][w][e]
[s]Talvez eu deva vir[n]aqui com alguem.[n][w][e]

[msg MSG_IceShop_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Voce sabe a diferenca entre suave[n]Sirva sorvete e sorvete comum?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Porque eu nao tenho ideia.[n][w][e]

[msg MSG_Realtor_Sofa_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Huh, confira aquele sofa de aparencia confortavel...[n]O que voce esta fazendo sobre isso?[n][w][e]

[msg MND_Realtor_Sofa_001]
[s]E um sofa de aparencia confortavel...[n][w][e]

[sel SEL_sofa top]
[s]So um pouco mais...[e]
[s]Vamos indo.[e]

[msg MSG_Realtor_Sofa_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]O que, e realmente tao confortavel? Quero dizer[n]Se estiver em frente a loja assim, eu acho[n]Deve ser confortavel...[n][w][e]
[s]Ok, vamos ir.[n][w][e]

[msg MSG_Realtor_Sofa_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Serio? Quao confortavel e este sofa...?[n][w][e]
[s]...Ei.[n][w][e]
[s]... hellooo.[n][w][e]
[s]Cara, todo mundo esta olhando para voce...[n]Acho que eu chamaria voce de ousado por fazer isso.[n][w][e]

[msg MSG_Realtor_Sofa_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Tudo bem vamos la.[n][w][e]

[msg MSG_Realtor_Sofa_End [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ok, eu te entendo muito do sofa. Vamos[n]Pegue quando voce conseguir seu proprio lugar, todos[n]certo?[n][w][e]

[msg MSG_Realtor_Sofa_End_Fau [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ha muitas coisas para fazer. Nos temos[n]Nao ha tempo para relaxar.[n][w][e]

[msg MSG_Realtor [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1186 65535 0]Voce quer apenas obter um novo sofa para o seu[n]quarto? Talvez com o dinheiro que tenho...[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]Uau, confira o preco...[n]Nao importa o que eu disse antes...[n][w][e]

[msg MND_Realtor]
[s]Talvez eu pudesse pegar alguns moveis novos...[n][w][e]
[s]......[n][w][e]
[s]Nao parece que eu jamais[n]tem dinheiro suficiente para isso...[n][w][e]

[msg MSG_Realtor_Yoru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]Ele esta fechado...[n][w][e]
[s][f 4 10 65535 0 0]Com um obturador tao grande, e quase[n]intimidadora.[n][w][e]

[msg MSG_Realtor_Chair [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Huh, voce nao acha que esta cadeira e perfeita[n]para mim?[n][w][e]

[msg MND_Realtor_Chair]
[s]Esta cadeira esta completamente feita a mao...[n][w][e]
[s]Ha um perfume de verniz.[n][w][e]

[msg MSG_Fudousan [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Huh, confira o preco de um[n]Quarto... acho que e esperado em Kichijoji.[n][w][e]
[s]Espere, espere... eu acho que Yongen-Jaya e[n]Muito la em cima tambem.[n][w][e]
[s]Voce pode realmente estar vivendo em uma bonita[n]Boa area.[n][w][e]

[msg MND_Fudousan]
[s]Diz,[n]"Vamos ajuda-lo a encontrar sua casa!"[n][w][e]
[s]Embora eu nao planeje alugar[n]uma casa em breve.[n][w][e]

[msg MSG_Karaoke [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]"Descontos para familias e idosos!"[n]Eu acho que e um pouco cedo para voces...[n][w][e]

[msg MND_Karaoke]
[s]"Inclui varias baladas de Enka!"[n][w][e]
[s]Eu me pergunto se ha musicas que eu conheco...[n][w][e]

[msg MSG_RecordShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Estes sao CDs muito grandes... hein? Registros?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Aposto que e tao grande, o som[n]Qualidade e muito boa.[n][w][e]

[msg MND_RecordShop]
[s]E uma loja de discos...[n][w][e]
[s]Eu nao teria uma maneira de tocar,[n]Mesmo se eu comprei um.[n][w][e]

[msg MSG_MusicTool [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Isso parece um violino caro. Huh?[n]E um contrabass?[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]Que tal esse? Um violoncelo? E essa[n]Um e uma viola? Estou tao confuso...[n][w][e]

[msg MND_MusicTool]
[s]Todos os instrumentos sao tao[n]caro. Eu me pergunto quanto[n]As taxas de manutencao sao...[n][w][e]

[msg MSG_MusicTool_Yoru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]E tao legal que existem tantos tipos[n]de instrumentos.[n][w][e]
[s][f 4 10 65535 0 0]Nao e incrivel que a musica possa se mover[n]Pessoas em lagrimas, sem palavras?[n][w][e]

[msg MSG_Pasta [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1155 65535 0]Recomendamos a Pappardelle e[n]Orecchiette. Experimente nosso Cappelletti e[n]Agnolotti tambem...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Eu fiz isso... eu disse isso sem parar![n][w][e]

[msg MND_Pasta]
[s]"Recomendamos o pappardelle[n]e Orecchiette. Experimente nosso Cappelletti[n]e Agnolotti tambem. "[n][w][e]
[s]... Eu me pergunto como eles sao todos.[n][w][e]

[msg MSG_Pasta_Error [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1155 65535 0]Recomendamos a Pappardelle e[n]orecchiette. Try our cappellitt—[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]... eu apenas mordi minha lingua.[n][w][e]

[msg MSG_EthnicCafe [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Um restaurante de sushi giratorio e um misterioso[n]lugar, nao e? Quero dizer, por que o sushi iria[n]estar girando...?[n][w][e]

[msg MND_EthnicCafe]
[s]Eu posso ver o sushi se movendo[n]ao longo das pistas.[n][w][e]

[msg MSG_Japanese_TeaHouse [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Ah, confira esse menu la em cima.[n]"Gelo raspado feito de agua natural".[n][w][e]
[s][f 4 10 65535 0 0]Eu me pergunto o quao diferente e da torneira[n]agua. Que tipo de agua o chefe[n]usar...?[n][w][e]

[msg MND_Japanese_TeaHouse]
[s]"Um gelo barbeado natural fotogenico."[n][w][e]
[s]Eu posso ouvir vozes de meninas[n]A partir das escadas.[n][w][e]

[msg MSG_Japanese_TeaHouse_he [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Como voce le o nome disso[n]fazer compras...? E "Yamayuki" ou "Sansetsu"?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Eu me pergunto por que eles chamam de "neve[n]montanha."[n][w][e]

[msg MSG_SocksShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Huh, eles tem meias para caes?[n]Mas nenhum para gatos?[n][w][e]
[s][f 4 10 65535 0 0]Bem, nao e como se eu precisasse usar meias...[n]Aposto que eles ficariam bem em mim.[n][w][e]

[msg MND_SocksShop]
[s]As meias que trouxe estao bem.[n][w][e]

[msg MSG_SocksShop_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Parece que todas as lojas estao fechadas neste[n]Tempo. Esta um pouco quieto...[n][w][e]

[msg MSG_MajorCafe [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]※レストラン ヒット自体をカット予定 [n][w][e]

[msg MSG_MajorCafe_Yoru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]※レストラン ヒット自体をカット予定 [n][w][e]

[msg MND_MajorCafe]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]※レストラン ヒット自体をカット予定 [n][w][e]

[msg MSG_EthnicShop [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Eles tem mascaras de varios paises.[n]E um pouco intimidador.[n][w][e]

[msg MND_EthnicShop]
[s]Eles tem coisas gerais[n]de paises asiaticos.[n][w][e]
[s]Todos eles parecem unicos.[n][w][e]

[msg MSG_CoinLocker [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Entao voce pode desbloquear esses armarios se voce[n]tem o recibo certo, hein?[n][w][e]
[s][f 4 10 65535 0 0]Parece que todos eles foram levados.[n]Eu acho que e porque ha muitos turistas.[n][w][e]

[msg MND_CoinLocker]
[s]Todos os armarios sao levados...[n][w][e]

[msg MSG_Bicycle [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Oh, as bicicletas aqui parecem muito faceis[n]carregar.[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]HM. Nao ha lugar para eu me sentar[n]e andar...[n][w][e]

[msg MND_Bicycle]
[s]E uma bicicleta leve.[n][w][e]
[s]Eles provavelmente removeram o[n]cesta para mante-lo leve.[n][w][e]

[msg MSG_Bicycle_heiten [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Talvez um dia possamos fazer uma viagem com[n]uma bicicleta. Provavelmente sera divertido, mesmo que[n]se perder.[n][w][e]

[msg MSG_ToyShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Confira todos os brinquedos de madeira... eles[n]importar-os de paises estrangeiros, hein?[n][w][e]
[s][f 4 10 65535 0 0]Oh aquela boneca de gato preto...[n]It's just like me—full of elegance.[n][w][e]

[msg MND_ToyShop]
[s]Parece que eles tem brinquedos de madeira.[n][w][e]
[s]Nao tenho motivos para comprar um.[n][w][e]

[msg MSG_ToyShop_heiten [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Brinquedos de madeira parecem ter essa classe...[n]Eu com certeza nao reclamaria se eu tivesse um.[n][w][e]

[msg MSG_SportsShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Para meninas da montanha e meninas de praia...[n]Parece que eles tem um monte inteiro[n]de coisas ao ar livre.[n][w][e]
[s][f 4 10 65535 0 0]Que tal algumas garotas de gatos... espere, como[n]Isso pareceria?[n][w][e]

[msg MSG_SportsShop_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Voce acha que o verde da parede porque e[n]deveria se parecer com as montanhas?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Na verdade, nao importa. Nao haveria[n]qualquer coisa para representar o mar ou o ceu...[n][w][e]

[msg MND_SportsShop]
[s]Eles estao vendendo muito[n]de produtos externos.[n][w][e]

[msg MSG_WineBar [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Ei, confira aquele pedaco gigante de queijo![n][w][e]
[s][f 4 10 65535 0 0]Oh, e falso... bem, eu acho que foi um[n]dado. Mas ainda parece muito real.[n][w][e]

[msg MND_WineBar]
[s]"Temos 100 tipos de vinho."[n][w][e]
[s]Talvez eu pare uma vez[n]Sou velha o suficiente.[n][w][e]

[msg MSG_WineBar_Yoru [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]A cerveja e o vinho nao sao alcool?[n]Eles nao sao realmente bons para voce...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Mas acho que algumas pessoas nao podem resistir, certo?[n][w][e]

[msg MSG_SteakFood [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]"Experimente nossa carne de 40 dias, a5-rank![n]Saboreie a carne que derrete na sua boca. "[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Oh porcaria, desculpe. Alguns da minha baba[n]Acabei de pingar no seu ombro...[n][w][e]

[msg MND_SteakFood]
[s]"Experimente nossa carne de 40 dias, a5-rank![n]Saboreie a carne que derrete na sua boca. "[n][w][e]
[s]Eu me pergunto como e...[n][w][e]

[msg MSG_AntiqueStore [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Droga, eu pensei que havia uma arvore crescendo[n]Naquela loja, mas era apenas um relogio.[n][w][e]

[msg MND_AntiqueStore]
[s]Parece haver muitas antiguidades[n]Nesta loja. Espere, e isso...[n][w][e]
[s]A primeira vista, eu pensei que era um[n]pintura, mas era uma mesa...[n][w][e]

[msg MSG_AntiqueStore_Yoru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Quando voce diz a palavra antiga, sinto[n]Como ele da ao item mais valor.[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]Que tal LeBlanc? Isso e retro?[n]Ou e antigo...[n][w][e]
[s][f 4 10 65535 0 0]Uau. O termo antiguidade e bem profundo...[n][w][e]

[msg MSG_DonutShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Eu acho que acabei de perceber algo.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Voce nao acha que estamos perdendo[n]Sem a parte central do donut?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Mas acho que a primeira forma que vem[n]a mente quando voce imagina um donut e[n]Este...[n][w][e]

[msg MND_DonutShop]
[s]Eu posso sentir o cheiro do doce[n]perfume de rosquinhas.[n][w][e]

[msg MSG_DonutShop_Quiz_001 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Aqui esta um questionario pop.[n][w][e]
[s][f 4 10 65535 0 0]Quantos donuts voce acha disso[n]sinal tem...?[n][w][e]

[msg MSG_DonutShop_Quiz_Re [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Tudo bem, agora quantos donuts sao[n]neste sinal?[n][w][e]

[sel SEL_Donut_01 top]
[s]... 9[e]
[s]... 10?[e]
[s]Aguentar.[e]

[msg MSG_DonutShop_Quiz_Commo [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Me whehehe... tem certeza sobre isso?[n][w][e]

[sel SEL_Donut_02 top]
[s]Deve ser 9.[e]
[s]Aguentar.[e]

[sel SEL_Donut_03 top]
[s]Deve ser 10.[e]
[s]Aguentar.[e]

[msg MSG_DonutShop_Quiz_Commo_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Voce acha que entendeu certo?[n][w][e]
[s][f 4 10 65535 0 0]A resposta e...![n][w][e]

[msg MSG_DonutShop_Quiz_NG [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1036 65535 0]Nao! Que pena! A resposta e 10![n][w][e]
[s][f 4 10 65535 0 0]Voce viu o donut a esquerda?[n]Isso conta como um.[n][w][e]

[msg MSG_DonutShop_Quiz_OK [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1045 65535 0]Parabens! Voce esta correto![n]A resposta e 10![n][w][e]
[s][f 4 10 65535 0 0]Parece que voce notou aquele donut em[n]a esquerda. Eles colocaram uma rosquinha la tambem, hein.[n][w][e]

[msg MSG_DonutShop_Quiz_Commo_3 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Desculpe zombar de voce. Mas nao foi[n]Muito emocionante?[n][w][e]

[msg MSG_DonutShop_Quiz_Cance [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Heheh. Aposto que voce vai verificar[n]Agora... estou certo?[n][w][e]

[msg MSG_DonutShop_Quiz_End_N [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Lembra daquele teste de donut? Hehe, eu ainda[n]Lembre-se de que voce entendeu errado.[n][w][e]

[msg MSG_DonutShop_Quiz_End_O [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Lembra daquele teste de donut?[n]Estou muito surpreso que voce acertou.[n][w][e]

[msg MSG_Tobari01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]O perfume do rabanete na sopa...[n]Isso me da uma sensacao calorosa por dentro.[n][w][e]

[msg MND_Tobari01]
[s]O rabanete no oden[n]esta sendo fervido...[n][w][e]

[msg MSG_Tobari02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Existem tantos tipos diferentes de[n]alcool. Assim como os graos de cafe.[n][w][e]
[s][f 4 10 65535 0 0]Mas ainda assim, olhe para os nomes...[n]Alguns deles parecem tao violentos.[n][w][e]

[msg MND_Tobari02]
[s]Existem bebidas alcoolicas[n]exibido em uma pequena area.[n][w][e]

[msg MSG_Tobari03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Veja quanta coisa eles tem e em[n]um lugar tao pequeno... mas voce nao acha[n]Pequenos espacos ajudam voce a relaxar?[n][w][e]

[msg MND_Tobari03]
[s]... eles usaram seus pequenos[n]espaco muito bem.[n][w][e]

[msg MSG_Tobari04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Como diabos eles vao cozinhar[n]Um lugar tao pequeno?[n][w][e]
[s][f 4 10 65535 0 0]Espere um segundo. Eu acho que a cozinha de LeBlanc e[n]Ainda menor. Tiramos o chapeu para o chefe...[n][w][e]

[msg MND_Tobari04]
[s]Sinto o cheiro de algo salgado.[n][w][e]

[msg MSG_Tobari05 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Uau! Eles tambem tem sushi!? Eu nao posso olhar[n]Nisso. Espere nao, parece tao bom...[n][w][e]

[msg MND_Tobari05]
[s]E um bar que tambem serve sushi.[n][w][e]

[msg ChineseMan_Start [Chinese Bun Shop Employee]]
[s][vp 8 2 1 0 5 0]Ei, bem-vindo! Estamos vendendo nosso quente[n]E paes chineses frescos aqui![n][w][e]

[msg ChineseMan_NOT_BUY [Chinese Bun Shop Employee]]
[s][vp 8 2 1 0 5 0]Por favor, venha de novo![n][w][e]

[msg ChineseMan_THANKS [Chinese Bun Shop Employee]]
[s][vp 8 2 1 0 5 0]Obrigado! Volte novamente![n][w][e]

[msg MSG_Tobari07 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Voce pode colocar o tomate em Oden? Eu me pergunto[n]Se a sopa ficar vermelha dela.[n][w][e]

[msg MND_Tobari07]
[s]Ha tomates no Oden.[n][w][e]
[s]Eu me pergunto como e o gosto.[n][w][e]

[msg MSG_Tobari08 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Agora que olho para ele, ha um segundo andar.[n]Eles realmente fazem tudo em...[n][w][e]

[msg MND_Tobari08]
[s]Eles ate tem lojas[n]no segundo andar.[n][w][e]

[msg MSG_Tobari09 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Pratos locais... quero dizer, voce pode obter[n]tudo na cidade. O que local[n]pratos eles estao falando?[n][w][e]

[msg MND_Tobari09]
[s]Pratos locais...[n][w][e]
[s]Eu me pergunto o que eles tem aqui.[n][w][e]

[msg MSG_Tobari10 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Oh, ei, eu vi um cara bebado em Yongen-Jaya.[n][w][e]
[s][f 4 10 65535 0 0]Ele estava tao fora disso, eu mal conseguia olhar[n]para ele.[n][w][e]

[msg MND_Tobari10]
[s]E um bar onde voce pode[n]beba em pe.[n][w][e]
[s]Eu me pergunto como eles[n]Nao fique cansado...[n][w][e]

[msg MSG_Tobari11 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Voce nao acha que o ramen e a melhor coisa[n]comer no final do dia? Eu acho[n]mingau tambem nao seria tao ruim.[n][w][e]

[msg MND_Tobari11]
[s]Eu posso sentir o cheiro de ramen...[n][w][e]
[s]O cheiro e automaticamente[n]me fazendo sentir fome.[n][w][e]

[msg MSG_Tobari12 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Entao, depois de passar pela area do alcool, voce[n]Chegue a uma rua bastante elegante. Cada area[n]muito diferente...[n][w][e]

[msg MND_Tobari12]
[s]Existem muitos itens sofisticados.[n][w][e]

[msg MSG_Tobari13 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Ahh, o cheiro do frango frito.[n]Ei, entao qual e a diferenca entre[n]isso e tempura?[n][w][e]

[msg MND_Tobari13]
[s]Eu posso sentir o cheiro do delicioso[n]frango frito.[n][w][e]

[msg MSG_Tobari14 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Oh, hein. Eles tem tatami la?[n]Aposto que e realmente confortavel...[n][w][e]

[msg MND_Tobari14]
[s]Ha tatami deitado por dentro.[n][w][e]
[s]... parece realmente confortavel.[n][w][e]

[msg MSG_Tobari15 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Ver barris assim me lembra[n]do palacio de Kamoshida.[n][w][e]

[msg MND_Tobari15]
[s]E um barril de saque.[n][w][e]
[s]Como eles os conseguiram aqui...?[n][e]

[msg MSG_Tobari16 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Entao, existem dois tipos de asas. Ha[n]A asa comum e as asas varrem.[n]Nao achava que haveria tantas opcoes.[n][w][e]

[msg MND_Tobari16]
[s]Eu posso sentir o cheiro do salgado[n]Molho e frango.[n][w][e]

[msg MSG_Tobari_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Eu acho que esses lugares nao abrem ate[n]periodo noturno.[n][w][e]

[msg MND_Tobari_heiten]
[s]Parece esses lugares[n]Nao abra ate a noite.[n][w][e]

[msg MSG_DeadEnd_Seacret [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Existem muita coisa aqui...[n][w][e]

[msg MND_DeadEnd_Seacret]
[s]Nao tenho nada para[n]Faca depois desta area.[n][w][e]

[msg MSG_Udon_Open [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Um lugar onde voce pode comer udon enquanto[n]de pe, hein?[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Voce pode escolher entre tantas coberturas.[n]Mesmo quando voce esta com pressa, voce ainda tem[n]Para selecionar suas coberturas com cuidado.[n][w][e]

[msg MND_Udon_Open]
[s]E um lugar onde voce pode[n]Fique e coma Udon.[n][w][e]
[s]Existem tantas coberturas...[n][w][e]

[msg MND_COMMON_NG_MACHINE_00]
[s][vp 1 0 0 0 0 0]Eu nao tenho tempo para levar[n]uma pausa e compre bebidas agora.[n][w][e]

[msg MND_E10410100_NG_MACHINE]
[s][vp 1 0 0 0 0 0]Nao estou com sede agora.[n][w][e]

[msg MND_E10920100_NG_MACHINE]
[s][vp 1 0 0 0 0 0]Agora, eu simplesmente nao tenho[n]a hora de saciar minha sede.[n][w][e]

[msg MSG_E27930100_NG_MACHINE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Podemos fazer isso mais tarde? Precisamos obter informacoes[n]em Futaba primeiro.[n][w][e]

[msg MSG_E79310100_NG_MACHINE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ei, voce nao tem tempo para fazer uma pausa[n]e compre bebidas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Apresse-se e nos leve para a clinica.[n][w][e]

[msg MSG_KF_Dagashi_mes01 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Uau! De uma olhada na vitrine cara![n][w][e]

[msg MSG_KF_Dagashi_mes02 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Um especial de Kichijoji, "Dorayaki com[n]casta e pasta de feijao vermelho "?[n]quase parece um hamburguer...[n][w][e]

[msg MSG_KF_Dagashi_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7020 65535 0]"Dorayaki com castanhas e feijao vermelho[n]colar. "Eles realmente jogam todo o saboroso[n]coisas juntas, hein...[n][w][e]

[msg MSG_KF_HatShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1021 65535 0]Uma loja somente para chapeus, hein? Eles tem assim[n]muitos deles.[n][w][e]

[msg MSG_KF_HatShop_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quantas cabecas esta capa da loja...[n][w][e]

[msg MSG_KF_HatShop_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Talvez eu experimente um chapeu algum dia.[n][w][e]

[msg MSG_KF_Stationer_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1165 65535 0]Meus sentidos de Morgana estao me dizendo que[n]Esta loja... vende muitas coisas que servem[n]meu gosto![n][w][e]

[msg MSG_KF_Stationer_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Que diabos sao os sentidos de Morgana...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7079 65535 0]Bem, vamos dar uma olhada.[n][w][e]

[msg MSG_KF_Stationer_mes03 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Aquele cara funcionario estava dizendo 'algo'[n]sobre como suas coisas fazem bons presentes,[n]sim?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Eu acho que seria muito legal conseguir um presente[n]daqui.[n][w][e]

[msg MSG_KF_Stationer_mes04 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu nao achei que voce realmente compraria algo.[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Seus sentidos disseram para voce conseguir um?[n][w][e]

[msg MSG_KF_TelephoneShop_mes [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7085 65535 0]Existem tantos tipos de telefones,[n]Mas sinto que todos parecem iguais.[n][w][e]

[msg MSG_KF_TelephoneShop_mes_2 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cara, eu quero um telefone meu.[n]De preferencia, o mais novo do mercado![n][w][e]

[msg MSG_KF_TelephoneShop_mes_3 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Resistente a agua, tela enorme, alta[n]capacidade, compativel com 4K! Cara, pode[n]Voce acredita no quao longe a tecnologia esta indo?[n][w][e]

[msg MSG_KF_OldClothesShop_me [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7155 65535 0]Oh, cara! Confira esse sinal na loja.[n]Diz: "Traga suas roupas fuligem aqui!"[n][w][e]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]... roupas de fuligem?[n][w][e]

[msg MSG_KF_OldClothesShop_me_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1020 65535 0]Heh, vamos ver o que eles tem![n][w][e]

[msg MSG_KF_OldClothesShop_me_3 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]W-Well, isso era uma especie de loja estranha...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Mas acho que foi muito divertido.[n]Vamos verificar novamente algum dia.[n][w][e]

[msg MSG_KF_IceShop_mes01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Cafe, morango, cha verde... parece[n]Eles tem todos os tipos de sabores.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Oh! Que tal sorvete com sabor de sushi?[n][w][e]

[msg MSG_KF_IceShop_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7025 65535 0]Cale a boca, Morgana! Ugh, eu apenas imaginei[n]Como seria o gosto![n][w][e]

[msg MSG_KF_IceShop_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Eles tem colheres duplas e triplas[n]tambem escapam. Eu me pergunto quantas colheres[n]Voce pode colocar um cone...[n][w][e]

[msg MSG_KF_Fudousan_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1133 65535 0]Huh, confira o preco de um[n]Quarto... acho que e esperado em Kichijoji.[n][w][e]

[msg MSG_KF_Fudousan_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cara, voce e um gato. Aluguel nem deveria[n]importa para voce.[n][w][e]

[msg MSG_KF_Fudousan_mes03 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 23046 65535 0]Eu nao sou um gato![n][w][e]

[msg MSG_KF_Fudousan_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7174 65535 0]Voce teria que pagar esse valor a cada[n]mes, certo? Caramba, com certeza custa uma lotra[n]dinheiro para viver por conta propria...[n][w][e]

[msg MSG_KF_Bank_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7088 65535 0]Cara, por que sempre existem bancos perto do[n]estacao? Quero dizer, eu nao vou la com frequencia, entao[n]realmente nao importa para mim, mas...[n][w][e]

[msg MSG_KF_Bank_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E um banco. Voce sabe eu sempre[n]me perguntei por que eles chamam assim...[n][w][e]

[msg MSG_KF_Bank_mes03 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Talvez seja porque um cara chamado Bank[n]surgiu com a ideia.[n][w][e]

[msg MSG_KF_Bank_mes04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1028 65535 0]Uh, definitivamente nao e isso...[n][w][e]

[msg MSG_KF_Bank_mes05 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7046 65535 0]Droga, Morgana.[n][w][e]

[msg MSG_KF_Bank_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]Eu me pergunto por que ha tantos diferentes[n]Tipos de bancos...[n][w][e]

[msg MSG_KF_EthnicCafe_mes01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Um restaurante de sushi giratorio e um misterioso[n]lugar, nao e? Quero dizer, por que o sushi iria[n]estar girando...?[n][w][e]

[msg MSG_KF_EthnicCafe_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Heh, eu quero experimentar sushi caro[n]Isso nao e um desses dias de Revolvin.[n][w][e]

[msg MSG_KF_EthnicCafe_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]Sushi de Revolvin nao e ruim, mas eu quero[n]tente sushi caro que nao e revolvin '[n]um destes dias.[n][w][e]

[msg MSG_KF_Taiyaki_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Vamos, eles chamam isso de peixe, mas e apenas[n]Taiyaki, certo? Voce acha que eu realmente[n]estar satisfeito com isso?[n][w][e]

[msg MSG_KF_Taiyaki_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas confira o que diz: "Vamos[n]fornecer uma peca fresca e organica a cada[n]tempo. "Parece muito durao...[n][w][e]

[msg MSG_KF_Taiyaki_mes03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Fresco e organico? Acho que nao podemos[n]Julgue um peixe pela capa...[n][w][e]

[msg MSG_KF_Taiyaki_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]"Vamos fornecer um novo e organico[n]peca sempre. "O que voce acha[n]Tem gosto de?[n][w][e]

[msg MSG_KF_TeaHouse_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]"Gelo raspado feito com agua natural"?[n]Entao e diferente da agua que voce recebe[n]das torneiras?[n][w][e]

[msg MSG_KF_TeaHouse_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ouvi dizer que quando o gelo barbeado era hella[n]Popular, as pessoas estavam ate mesmo[n]durante o inverno.[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nao posso acreditar que as pessoas comeriam essas coisas[n]durante o inverno...[n][w][e]

[msg MSG_KF_TeaHouse_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7086 65535 0]"Gelo de barbear natural fotogenico"?[n]Eu nao posso acreditar que o gelo barbeado tem[n]Venha ate aqui.[n][w][e]

[msg MSG_KF_SocksShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1168 65535 0]E um lugar que so vende meias. E bastante[n]uma visao quando tudo o que voce ve sao meias...[n][w][e]

[msg MSG_KF_SocksShop_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, sim, as meias que estou vestindo com buracos[n]em eles. Eu tenho que conseguir um novo par.[n][w][e]

[msg MSG_KF_SocksShop_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Eles tem meias com personagens em[n]eles tambem.[n][w][e]

[msg MSG_KF_MeatFryShop_mes01 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Puta merda, olhe para a linha! Eu acho que vi[n]Esta loja na TV.[n][w][e]

[msg MSG_KF_MeatFryShop_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, o cheiro... parece o "especial[n]Correta de carne "e o item mais popular.[n][w][e]

[msg MSG_KF_MeatFryShop_mes03 [Fried Food Shop Staff]]
[s][vp 8 2 1 0 2 0]Desculpe, so temos o suficiente do[n][clr 3]Cubra de carne especial[clr 27]para as pessoas em[n]linha agora.[n][w][e]
[s][vp 8 2 1 0 2 0]Tente parar a noite.[n][w][e]

[msg MSG_KF_MeatFryShop_mes04 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0]Bem, acho que nao podemos fazer merda se for[n]tao ocupado...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas lembre-se de que poderiamos[n]ser capaz de comprar o "Cretlet de carne especial"[n]no[clr 2]noite[clr 27]![n][w][e]

[msg MSG_KF_Udon_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1171 65535 0]Um lugar onde voce pode comer udon enquanto[n]de pe, hein? Eles tem tantos[n]Caminhos para escolher.[n][w][e]

[msg MSG_KF_Udon_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Esses lugares sao destinados a comer o mais rapido possivel,[n]Mas com tantas coberturas, voce gastaria[n]Todo o seu tempo apenas decidindo o que conseguir.[n][w][e]

[msg MSG_KF_Udon_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Udon que voce pode comer em pe.[n]Isso e o que eles chamam de fast food, certo?[n][w][e]

[msg MSG_KF_Temple_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7086 65535 0]Quando voce olha de perto, e bastante[n]uma visao, hein?[n][w][e]

[msg MSG_KF_Temple_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Aposto ter um templo em uma compra[n]O distrito realmente ajuda os negocios.[n][w][e]

[msg MSG_KF_Temple_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]Mas por que ha um templo em uma compra[n]distrito assim?[n][w][e]

[msg MSG_KF_CoinLocker_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Entao voce pode desbloquear esses armarios se voce[n]tem o recibo certo, hein?[n][w][e]

[msg MSG_KF_CoinLocker_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sabe, eu sinto que as pessoas tendem a esquecer[n]onde eles colocam sua merda uma boa parte do tempo.[n][w][e]

[msg MSG_KF_CoinLocker_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Parece que todos eles foram levados.[n]Eu acho que e porque ha muitos turistas.[n][w][e]

[msg MSG_KF_FoodShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1133 65535 0]Eles tem comida de paises estrangeiros?[n]Alguns deles parecem bastante interessados em[n][w][e]

[msg MSG_KF_FoodShop_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Parece que eles tem algumas coisas raras.[n]Vamos conferir![n][w][e]

[msg MSG_KF_FoodShop_mes03 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E muito caro, hein...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Talvez eu compre um algum dia, jus 'para ver[n]como e o gosto.[n][w][e]

[msg MSG_KF_FoodShop_mes04 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Oh, voce pegou algo?[n]Deixe-me saber como e o gosto, sim?[n][w][e]

[msg MSG_KF_JuiceMachine01_me [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Oh, voce vai tomar uma bebida?[n][w][e]

[msg MSG_KF_JuiceMachine01_me_2 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7156 65535 0]Uau, eu nunca vi isso esgotado.[n][w][e]

[msg MSG_KF_JuiceMachine01_me_3 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7044 65535 0]Parece tudo nesta venda[n]A maquina esta esgotada.[n][w][e]

[msg MSG_KF_EthnicShop_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0]Essas lojas geralmente tem um estranho[n]cheiro? Cara, eu nao sou um grande fa disso...[n][w][e]

[msg MSG_KF_EthnicShop_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce e um garoto, Ryuji. Isso e suposto[n]ser um perfume exotico.[n][w][e]

[msg MSG_KF_EthnicShop_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Eles tem mascaras de varios paises.[n]E um pouco intimidador.[n][w][e]

[msg MSG_KF_Karaoke_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1163 65535 0]"Descontos para familias e idosos!"[n]Acho que os ouco cantando.[n][w][e]

[msg MSG_KF_Karaoke_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O karaoke e sempre tao barato durante o[n]semana. Eu me pergunto se eles estao ate fazendo[n]dinheiro.[n][w][e]

[msg MSG_KF_Karaoke_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7086 65535 0]"Inclui varias baladas de Enka!"[n]Aposto que sao principalmente musicas que eram[n]popular antes de nascermos.[n][w][e]

[msg MSG_KF_Realtor_mes01 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Oh, confira todos os moveis elegantes.[n][w][e]

[msg MSG_KF_Realtor_mes02 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce quer apenas obter um novo sofa para o seu[n]quarto? Talvez com o dinheiro que tenho...[n][w][e]

[msg MSG_KF_Realtor_mes03 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cara, Morgana. Veja o preco.[n][w][e]

[msg MSG_KF_Realtor_mes04 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 0 1032 65535 0]Oof... eu tomo de volta.[n][w][e]

[msg MSG_KF_Realtor_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7024 65535 0]Huh, se eu tivesse coisas assim no meu quarto,[n]Eu seria popular?[n][w][e]

[msg MSG_KF_Realtor_Sofa_mes0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Who-whoa, isso foi tao repentino voce[n]Quase me assustou...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Mas cara, voce tem alguma coragem.[n]Estou muito surpreso![n][w][e]

[msg MSG_KF_Realtor_Sofa_mes0_2 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]...Tudo bem. Acho que todos sabemos que voce tem coragem.[n]Vamos dar certo, cara.[n][w][e]

[msg MSG_KF_RecordShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Estes sao CDs muito grandes... hein? Registros?[n][w][e]

[msg MSG_KF_RecordShop_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce acho que e verdade que CDs e registros[n]Parece diferente?[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Acho que nunca seria capaz de contar[n]A diferenca.[n][w][e]

[msg MSG_KF_RecordShop_mes00 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Os registros sao tao legais. Se ao menos eu tivesse o[n]coisa que joga...[n][w][e]

[msg MSG_KF_Main_MusicTool_me [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Confira todos os instrumentos la...[n]Talvez eu experimente um.[n][w][e]

[msg MSG_KF_Main_MusicTool_me_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Aposto que voce ficaria bem com uma trombeta.[n][w][e]

[msg MSG_KF_Main_MusicTool_me_3 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce esta apenas bacia para fora da cor do meu cabelo,[n]voce nao esta?[n][w][e]

[msg MSG_KF_Main_MusicTool_me_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Isso parece um violino caro. Huh?[n]E um contrabass?[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Que tal esse? Um violoncelo? E essa[n]Um e uma viola? Estou tao confuso...[n][w][e]

[msg MSG_KF_JazzClub_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Um clube de jazz, hein? Parece um lugar[n]para adultos.[n][w][e]

[msg MSG_KF_JazzClub_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cara, voce ganha jazz? Que legal.[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]De qualquer maneira, parece que esta apenas aberto[n]a noite.[n][w][e]

[msg MSG_KF_JazzClub_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Parece que este clube de jazz esta aberto apenas[n]a noite.[n][w][e]

[msg MSG_KF_Izakaya06_mes01 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7159 65535 0]Cara, esse nikuman parece muito mais saboroso[n]do que os em lojas de conveniencia.[n][w][e]

[msg MSG_KF_Izakaya06_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Faz... ei, voces querem pegar um?[n]Que tal isso?[n][w][e]

[msg MSG_KF_Izakaya06_mes03 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7133 65535 0]Napolitan nikuman e apimentado[n]Nikuman...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cara, eu me pergunto como eles tem gosto![n]Eu vou comer totalmente um dia desses![n][w][e]

[msg MSG_KF_Izakaya_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Eu acho que esses lugares nao abrem ate[n]periodo noturno.[n][w][e]

[msg MSG_KF_Izakaya_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me pergunto como e a noite...[n]Eu meio que quero dar uma olhada.[n][w][e]

[msg MSG_KF_Izakaya_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Eu ouvi essa area bastante animada a noite.[n]Gostaria de saber como e.[n][w][e]

[msg MSG_KF_ramen_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7086 65535 0]Uma loja de ramen que so esta aberta a noite,[n]Ha?[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cara, esses sao geralmente os verdadeiros bons.[n][w][e]

[msg MSG_KF_ramen_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Todo mundo ama tanto o ramen. Quero dizer,[n]Existem ate lojas que tem 2 horas[n]Esperando tempos, certo?[n][w][e]

[msg MSG_KF_ramen_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]O local esta fechado, mas voce ainda pode[n]cheire o ramen.[n][w][e]

[msg MSG_KF_Variety_mes01 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]Uma loja de incenso? Cara, estou dizendo[n]Parece muito suspeito.[n][w][e]

[msg MSG_KF_Variety_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Espere, aguarde...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 1187 65535 0]Ei, vamos dar uma olhada![n][w][e]

[msg MSG_KF_Variety_mes03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1021 65535 0]Eu sinto que esses incensos tem alguns[n]Poder estranho... talvez possamos usa-lo[n]para algo.[n][w][e]

[msg MSG_KF_Variety_mes04 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh, eu nao entendo...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas se Morgana esta dizendo isso, talvez[n]Voce deve comprar algum tempo.[n][w][e]

[msg MSG_KF_VarietyNG_mes01 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]Uma loja de incenso? Cara, estou dizendo[n]Parece muito suspeito.[n][w][e]

[msg MSG_KF_VarietyNG_mes02 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voce nao tem interesse em incensos, certo?[n]Onde voce o usaria...?[n][w][e]

[msg MSG_KF_Megane_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1020 65535 0]Uma loja que so vende oculos...[n]Confira todos os tipos diferentes que eles tem.[n][w][e]

[msg MSG_KF_Megane_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu continuo esquecendo, mas seus oculos sao[n]Fake, hein? Voce acha que eu ficaria mais inteligente[n]Se eu tivesse oculos?[n][w][e]

[msg MSG_KF_Megane_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Eu nunca precisei de oculos, entao nunca[n]Entre em lojas como esta.[n][w][e]

[msg MSG_KF_Accessories_mes01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1067 65535 0]Uau! Confira todos os tesouros que eles[n]tenho aqui![n][w][e]

[msg MSG_KF_Accessories_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Power Stones sao aquelas semelhantes a amuletas[n]Coisas, certo? Eles tem alguns estranhos[n]poder ou algo assim '.[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vamos dar uma olhada.[n][w][e]

[msg MSG_KF_Accessories_mes03 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7114 65535 0]Eu quase tenho um nariz ensanguentado, so de[n]olhando para esses precos...[n][w][e]

[msg MSG_KF_Accessories_mes04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas parecia que eles realmente tinham alguns[n]poder neles. Nos devemos dar uma olhada[n]as vezes.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Talvez seja util para o[n]Phantom Thieves![n][w][e]

[msg MSG_KF_DonutShop_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Acabei de perceber algo...[n][w][e]

[msg MSG_KF_DonutShop_mes02 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O que ha, Morgana?[n][w][e]

[msg MSG_KF_DonutShop_mes03 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Estamos realmente perdendo sem centro[n]parte do donut![n][w][e]

[msg MSG_KF_DonutShop_mes04 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]Sim... isso e realmente algo que precisamos[n]Preocupar-se agora...[n][w][e]

[msg MSG_KF_DonutShop_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7184 65535 0]Oh, nao era uma coisa grande em um em um[n]ponto? Era como um super popular alguns[n]tempo atras.[n][w][e]

[msg MSG_KF_AntiqueStore_mes0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Uau, olhe para todas as antiguidades artisticas...[n][w][e]

[msg MSG_KF_AntiqueStore_mes0_2 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu terminei com isso depois de olhar para o[n]Museu outro dia.[n][w][e]

[msg MSG_KF_AntiqueStore_mes0_3 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7190 65535 0]Cara, eu pensei que isso la havia um[n]Imagem, mas era uma mesa louca.[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cara, eu simplesmente nao entendo arte.[n][w][e]

[msg MSG_KF_SteakFood_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]"Experimente nossa carne de 40 dias, a5-rank![n]Saboreie a carne que derrete na sua boca. "[n][w][e]

[msg MSG_KF_SteakFood_mes02 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pare! Pare! Voce vai me fazer[n]quero comer![n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Este lugar e perigoso.[n]Vamos ficar longe daqui.[n][w][e]

[msg MSG_KF_SteakFood_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]Cara, o cheiro de carne cozida esta matando[n]Eu... * Slurp * Oh merda, estou babando.[n][w][e]

[msg MSG_KF_WineBar_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7086 65535 0]"Temos 100 tipos de vinho."[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O vinho e feito de uvas, certo?[n]O sabor e realmente tao diferente?[n][w][e]

[msg MSG_KF_WineBar_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ha muito para vinho. Tipo, como[n]Ha vinho tinto e vinho branco...[n][w][e]

[msg MSG_KF_WineBar_mes03 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]Tudo o que consegui disso e que voce nao e bom[n]na descricao de coisas...[n][w][e]

[msg MSG_KF_WineBar_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Vinho e queijo... eu quero experimentar um dia.[n][w][e]

[msg MSG_KF_SportsShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Para meninas da montanha e meninas de praia...[n]Parece que eles tem um monte inteiro[n]de coisas ao ar livre.[n][w][e]

[msg MSG_KF_SportsShop_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cara, ha tantas garotas ao ar livre[n]hoje em dia.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas como e que nao ha nenhuma montanha[n]meninos ou meninos oceanicos?[n][w][e]

[msg MSG_KF_SportsShop_mes03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]... bom ponto.[n][w][e]

[msg MSG_KF_SportsShop_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7184 65535 0]Voce sabe, podemos precisar de um pouco de natacao[n]ternos um dia.[n][w][e]

[msg MSG_KF_ToyShop_mes01 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Entao eles receberam brinquedos importados aqui. Elas[n]com certeza parecem diferentes dos que nos[n]tem aqui.[n][w][e]

[msg MSG_KF_ToyShop_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Parece que eles sao feitos principalmente de madeira.[n]Talvez pudessemos fazer o nosso.[n][w][e]

[msg MSG_KF_ToyShop_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Entao eles sao importados de diferentes[n]paises, hein? As familias la[n]parece muito chique tambem...[n][w][e]

[msg MSG_KF_MajorCafe_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]What a fancy looking café. If I ever were[n]to invite Lady Ann somewhere— Why're[n]Voce esta olhando para mim assim?[n][w][e]

[msg MSG_KF_MajorCafe_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bem, diz que podemos trazer animais de estimacao para dentro,[n]Entao talvez esteja bem?[n][w][e]

[msg MSG_KF_MajorCafe_mes03 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quem voce esta ligando para um animal de estimacao!?[n][w][e]

[msg MSG_KF_MajorCafe_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]What a fancy café. Looks like their[n]Especialidade e um cafe expresso em casa.[n][w][e]

[msg MSG_KF_Pasta_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Recomendamos a Pappardelle e[n]Orecchiette. Experimente nosso Cappelletti e[n]Agnolotti tambem...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Eu fiz isso! Eu disse isso sem parar![n][w][e]

[msg MSG_KF_Pasta_mes02 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pappar... Dille? Agno... O que?[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu nem posso dizer isso, muito menos imaginar o que[n]diabos parece...[n][w][e]

[msg MSG_KF_Pasta_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Parece que suas recomendacoes sao[n]Pappardelle, Orecchiette, Cappelletti e[n]Agnolotti![n][w][e]

[msg MSG_KF_Bicycle_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Oh, as bicicletas aqui parecem muito faceis[n]carregar.[n][w][e]

[msg MSG_KF_Bicycle_mes02 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cara, confira os precos neles[n]Biciclas! Merda, eles nao sao mais caros[n]do que motos?[n][w][e]

[msg MSG_KF_Bicycle_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me pergunto se as bicicletas caras sao mais[n]Util do que aquelas bicicletas normais...[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 7173 65535 0]Acho que nao posso andar de bicicleta.[n]Eu sinto que vai ser roubado ou algo assim.[n][w][e]

[sel D_VELVET_IN_SEL top]
[s]Deixe-me entrar na celula.[e]
[s]Eu nao quero entrar.[e]

[msg D_VELVET_IN_QUIET_01 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 12002 65535 0]Parece que voce esta muito preso.[n]Eu posso conceder esse desejo por voce...[n][w][e]

[msg D_VELVET_IN_QUIET_OK [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Muito bem. Vou cumprir o seu desejo de bom grado...[n][w][e]

[msg D_VELVET_IN_QUIET_NO [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]... Continue sua luta.[n][w][e]

[msg D_VELVET_IN_LOUD_01 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qual e o problema, preso? Voce esta saudando[n]voltar para a prisao?[n][w][e]

[msg D_VELVET_IN_LOUD_OK [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Heheheh. Eu vou te colocar de volta onde[n]voce pertence![n][w][e]

[msg D_VELVET_IN_LOUD_NO [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Continue lutando, preso.[n][w][e]

[msg D_VELVET_IN_LAST_01 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vou guia-lo para o meu mestre...[n][w][e]

[sel D_VELVET_IN_LAST_SEL top]
[s]Eu quero me preparar.[e]
[s]Eu nao quero entrar.[e]

[msg D_VELVET_IN_LAST_OK [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entao, por favor, digite.[n][w][e]

[msg D_VELVET_IN_LAST_NO [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Muito bem. Meu mestre e eu seremos[n]cuidando de voce.[n][w][e]

[msg MSG_KICHIJOJ_OPEN_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]Voce vai acabar de volta na estacao[n]Se voce for assim. Vamos para os dardos[n]lounge por enquanto.[n][w][e]

[msg MSG_MONEY_MORGANA_CHK_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1001 0 0]Oh, voce nao tem dinheiro suficiente?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Vou te dar um pouco do meu esconderijo secreto para[n]agora, mas verifique se voce tem alguns com[n]voce na proxima vez.[n][w][e]

[msg MSG_KFEVT_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Ei onde voce esta indo?[n][w][e]

[msg MND_COMMON_CHK_000_00]
[s][vp 1 0 0 0 0 0]Nao ha nada que[n]Eu preciso fazer a frente...[n][w][e]

[msg EX_0103_0108_LOCK_mes01 [Female Guest with Hat]]
[s][vp 1 0 0 0 0 0]E este o lugar? Aquele com o[n]Perfumista carismatico que lemos sobre[n]Na revista?[n][w][e]

[msg EX_0103_0108_LOCK_mes02 [Female Guest]]
[s][vp 1 0 0 0 0 0]Oh sim. Eles tem todos aqueles famosos[n]modelos e atrizes usando seus produtos.[n][w][e]

[msg EX_0103_0108_LOCK_mes03 [Female Guest with Hat]]
[s][vp 1 0 0 0 0 0]O gerente da loja e supostamente um[n]cara misterioso tambem! Todo mundo esta falando![n][w][e]
[s][vp 1 0 0 0 0 0]Espero poder apertar a mao deles quando[n]Eu faco minha compra![n][w][e]

[msg EX_0103_0108_LOCK_mes04]
[s][vp 1 0 0 0 0 0]A linha parece ser[n]para a loja de incenso.[n][w][e]
[s][vp 1 0 0 0 0 0]Eu nao acho que posso[n]va mais longe...[n][w][e]

[msg EX_0103_0108_LOCK_mes00]
[s][vp 1 0 0 0 0 0]Esta muito lotado para mim[n]ir mais longe...[n][w][e]

