[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_Planter_SetGlow [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Ha um[f 2 5 3 9999 0][n]plantado aqui.[n][w][e]

[msg MSG_Planter_NotGlow [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Nao ha nada plantado na flor[n]cama agora...[n][w][e]

[msg MND_KFEVT_COMMON_NG]
[s]Nao ha nada que eu particularmente[n]Precisa fazer aqui agora.[n][w][e]

[msg MND_E12310100_CHK_DOOR_0]
[s]Acho que vou apenas ir[n]casa para hoje...[n][w][e]

[msg AZITO_HIT_PC02_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]Ei, o que estamos fazendo hoje?[n][w][e]

[msg AZITO_HIT_PC02_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]Ei, ai esta voce.[n][w][e]

[msg AZITO_HIT_PC03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Parece que todo mundo esta aqui.[n][w][e]

[msg AZITO_HIT_PC03_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Desculpe pela espera.[n][w][e]

[msg AZITO_HIT_PC04_mes01 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0]Ei, o que voce quer fazer hoje?[n][w][e]

[msg AZITO_HIT_PC04_mes02 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0]Ai esta voce.[n][w][e]

