[msg Dummy]
[s]......[n][w][e]

[msg mini_EV_e205_111_mes01 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Droga, ja...?[n][w][e]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ei, o que quer fazer?[n][w][e]

[sel mini_EV_e205_111_selA top]
[s]Temos que vencer.[f 2 7 0 0 106 1][e]
[s]Vamos voltar mais tarde.[f 2 7 0 0 106 1][e]
[s]Vamos esperar que ele sai.[f 2 7 0 0 106 1][e]

[msg mini_EV_e205_111_selA_0_ [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7080 65535 0]Sim...[n][w][e]

[msg mini_EV_e205_111_selA_1_ [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7173 65535 0]Eu gostaria que pudessemos... mas nao[n]tem tempo, e eu nao vou deixar[n]Seu trabalho duro vai desperdicar.[n][w][e]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nos apenas temos que ir em frente...[n][w][e]

[msg mini_EV_e205_111_selA_2_ [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7085 65535 0]... como voce sabe se isso seria[n]sair? Nao temos tempo, sabe?[n][w][e]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Estou pensando que apenas temos que ir em frente...[n][w][e]

[msg mini_EV_e205_111_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O verdadeiro problema e o fato de que nos[n]Tenho que lidar com isso com apenas os dois[n]de nos...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]De qualquer forma, vou deixar o tempo para[n]Voce, cara.[n][w][e]

[msg mini_EV_e205_112_mes01 [Security's Voice]]
[s]Ei! Quem esta ai!?[n][w][e]

[msg mini_EV_e205_112_mes02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]Porcaria...! Vamos correr para isso![n][w][e]

[msg mini_EV_e205_110_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7159 65535 0]Ah sim! Esta e a sala![n][w][e]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entao... qual e a seguranca?[n][w][e]

[msg mini_EV_TEX_GET02_LOOK_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1057 65535 0]Ei, espere. Devemos levar isso[n]Panfleto conosco antes de irmos![n][w][e]

[msg mini_EV_e210_143_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Parece que esta e a sala de controle para[n]a seguranca...[n][w][e]

[msg mini_EV_e210_143_mes02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Doce! Vamos desligar essa merda ja![n][w][e]

[msg mini_EV_e210_144_mes01 [Trailing Guard Shadow]]
[s]Eu ouco os intrusos ja passaram[n]A seguranca do jardim central...[n][w][e]

[msg mini_EV_e210_144_mes02 [Leading Guard Shadow]]
[s]Sim. Acabei de receber uma ligacao antes para mudar[n]a senha aqui tambem...[n][w][e]

[msg mini_EV_e210_144_mes03 [Trailing Guard Shadow]]
[s]O que? E melhor nao ser simples.[n][w][e]

[msg mini_EV_e210_144_mes04 [Leading Guard Shadow]]
[s]Bem, eu estava tendo algum problema[n]chegando com um bom...[n][w][e]
[s]Por enquanto, eu o defina para os numeros para[n]Os pes de Lord Madarame.[n][w][e]

[msg mini_EV_e210_144_mes05 [Trailing Guard Shadow]]
[s]Os pes de Lord Madarame? O que sao[n]Voce falando sobre?[n][w][e]

[msg mini_EV_e210_144_mes06 [Leading Guard Shadow]]
[s]Vamos voltar de plantao. Ha uma chance[n]Os intrusos estao proximos.[n][w][e]

[msg mini_EV_e210_144_mes07 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7038 65535 0]Os pes de Madarame? O inferno e isso[n]Deveria significar!?[n][w][e]

[msg mini_EV_e210_144_mes08 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Talvez... o tamanho do sapato dele?[n][w][e]

[msg mini_EV_e210_144_mes09 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo, raposa. Voce sabe que o de Bastardo[n]tamanho de sapato?[n][w][e]

[msg mini_EV_e210_144_mes10 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4171 65535 0]Infelizmente, nunca ouvi[n]ele menciona isso. Temos certeza de que e[n]a senha adequada...?[n][w][e]

[msg mini_EV_e210_144_mes11 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pes de Madarame... o que voce acha[n]Isso poderia significar...?[n][w][e]

[msg D153_006_miniEV_01_mes01 [Madarame's Voice]]
[s][vp 8 1 65535 35 0 0]Como voce se atreve a pisar no meu tranquilo[n]Jardim de bambu com aqueles pes sombrios![n]Voce nao deve sair vivo![n][w][e]

[msg D153_006_miniEV_01_mes02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O que diabos foi isso...!?[n][w][e]

[msg D153_006_miniEV_01_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Provavelmente estamos apenas ouvindo[n]Pensamentos de Madarame. Ha[n]Nao ha necessidade de entrar em panico.[n][w][e]

[msg D153_006_miniEV_01_mes04 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4074 65535 0]Madarame...[n][w][e]

[msg mini_EV_e210_142_mes01 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6186 65535 0]Oh... estamos em outra pintura...[n][w][e]

[msg mini_EV_e210_142_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm... entao este espaco nao e apenas um,[n]Mas uma infinidade de pinturas.[n][w][e]

[msg mini_EV_e210_142_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7038 65535 0]... voce esta me dizendo que estao todos conectados?[n]Qual deles vai para onde?[n][w][e]

[msg mini_EV_e210_142_mes04 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Isso, teremos que continuar andando[n]descobrir...[n][w][e]

[msg mini_EV_e210_142_mes05 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Ei Joker, voce nao pode identificar o[n]Conexoes com suas habilidades?[n][w][e]

[msg D153_006_miniEV_02_mes01 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4044 65535 0]Entao ele ousa nos chamar de ladroes[n]quem sujo seu coracao...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aquele que manchou o proprio[n]A natureza da arte em si nao tem direito a[n]Acuse-nos de uma coisa dessas...![n][w][e]

[msg D153_006_miniEV_02_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Salve suas emocoes para mais tarde.[n]Temos que continuar nos movendo![n][w][e]

