[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]Então, temos que lidar com essa[n]solicitação do fórum?[n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]Temos que dar o nosso melhor.[n][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]E, a propósito, esperar é chato.[n][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][f 5 14]Na minha opinião, hoje devemos[n]ir para Mementos.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Sim, ainda não atendemos[n]o pedido de Mishima.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Se formos ao Mementos,[n]você quer que todos venham[n]ao esconderijo?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir para o ponto de encontro[e]
[s]Decidir depois[e]

[sel SEL_002 top]
[s][f 5 14]Vamos fazer isso.[e]

[msg MSG_REACTION [Futaba]]
[s][f 5 14]Excelente. Vamos nos reunir, então.[n][f 5 15][w][e]

