[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Oh, eu apenas me lembrei![n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14][f 4 2], você conseguiu perguntar a Boss sobre[n]Futaba Sakura?[n][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Ele não queria falar.[e]
[s]Eu tentei...[e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]Poderia haver uma razão para isso?[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Portanto, sem resultados. Poderia haver[n]uma razão para isso?[n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]HM. Alibaba pode ser nossa única[n]esperança de derrotar Medjed.[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Eu gostaria que pudéssemos obter algumas[n]informações sobre Futaba fora do chefe...[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Mas tentar forçá-lo provavelmente teria o[n]efeito oposto.[n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14]Para ser sincero, devo muito para o chefe[n]e  [f 4 2].[n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Não desejo que isso seja uma fonte de[n]discórdia entre eles.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Sim, eu sei exatamente o que você quer[n]dizer![n][w][e]

[msg MSG_011_0_0 [Makoto]]
[s][f 5 14][f 5 15]Provavelmente é melhor esperar o chefe[n]trazer o assunto.[n][w][e]

