[msg MSG_029_0_0 [Mishima]]
[s][f 5 14]Conseguimos![n]Salvamos a cidade![n][w][e]
[s][f 5 14]Lembra daquele pequeno gangster[n]em Shibuya? Ele parece ter[n]abandonado a vida do crime.[n][w][e]
[s][f 5 14]Droga. Eu só queria que eles[n]nos deixassem em paz.[n][w][e]
[s][f 5 14]Primeiro Kaneshiro, agora esses caras.[n]Vamos esperar que seja a última vez que[n]alguém tente.[n][w][e]

[sel SEL_030_0_0 top]
[s][f 5 14]Acho que sim.[e]
[s]Quem pode dizer?[e]
[s]O mal nunca dorme.[e]

[msg MSG_031_0_0 [Mishima]]
[s][f 5 14]Sim, isso seria bom.[n][w][e]

[msg MSG_032_0_0 [Mishima]]
[s][f 5 14]Talvez um dia possamos nos livrar de todos[n]esses criminosos, hein? Espero que sim.[n][w][e]

[msg MSG_033_0_0 [Mishima]]
[s][f 5 14]Mas enquanto o mal governar,[n]os Phantom Thieves nunca[n]descansarão, certo?[n][w][e]

[msg MSG_034_0_0 [Mishima]]
[s][f 5 14]Mas ei, os Phantom Thieves agora são[n]heróis em Shibuya.[n][w][e]
[s][f 5 14]Acho que eles vão se tornar mais[n]confiáveis do que a polícia.[n][w][e]
[s][f 5 14][f 5 15]Manterei você informado se[n]descobrir um novo caso![n][w][e]

[msg MSG_035_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Mais um trabalho bem feito! Eu realmente[n]acho que isso fortalecerá nossa[n]reputação![n][f 1 3 65535][w][e]

[msg MND_quest24_CLEAR_SELF]
[s][vp 8 2 65535 0 0 0]Parece que conseguimos[n]acordar o coração[n]do alvo...[n][f 1 3 65535][w][e]

