[msg MSG_000_0_0 [Haru]]
[s][f 5 14]Descobrimos onde está o tesouro.[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]Deseja enviar a carta de aviso[n]hoje? Devemos reunir[n]todos.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Então, o que você quer fazer? Vamos nos[n]reunir na reunião se você quiser enviar[n]a carta de aviso.[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir para o ponto de encontro[e]
[s]Decidir depois[e]

[sel SEL_002 top]
[s][f 5 14]Enviamos a carta de aviso.[e]

[msg MSG_REACTION [Haru]]
[s][f 5 14]Ok, entendi.[n][w][e]

[msg MSG_REACTION_02 [Haru]]
[s][f 5 14]Ok. Eu irei imediatamente para a reunião.[n][f 5 15][w][e]

