[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Ei, bom trabalho pessoal.[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Todos nós fizemos o nosso melhor.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Permita-me expressar meus agradecimentos[n]mais uma vez.[n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]Por sua causa, pude recuperar a pintura[n]que havia sido cheia do amor de minha[n]mãe.[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Ouvindo você dizer que faz a coisa toda[n]valer a pena, Yusuke![n][w][e]

[msg MSG_005_0_0 [Ann]]
[s][f 5 14]A sério.[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Eu não tinha certeza se você realmente[n]gostaria de mudar o coração de Madarame.[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Lamento ter preocupado você.[n]Não me arrependo agora.[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]E a mudança de coração vai acontecer[n]desta vez, certo?[n][w][e]

[sel SEL_009_0_0 top]
[s][f 5 14]Vai ficar bem.[e]
[s]Não sei.[e]
[s]Você está preocupado?[e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Sim. Fizemos isso exatamente como com[n]Kamoshida.[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]Portanto, não teremos certeza até que os[n]resultados estabelecidos...[n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14]É apenas a nossa segunda vez fazendo[n]isso, afinal.[n][w][e]

[msg MSG_013_0_0 [Ann]]
[s][f 5 14]A propósito, estou curioso sobre o que[n]ele disse no final.[n][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14]Você quer dizer sobre o outro intruso[n]além de nós?[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14]Era algo sobre uma máscara preta, sim?[n][w][e]

[msg MSG_016_0_0 [Yusuke]]
[s][f 5 14]Isso pode ter sido nada mais do que uma[n]mentira.[n][w][e]

[msg MSG_017_0_0 [Yusuke]]
[s][f 5 14]Madarame estava bastante perturbada[n]naquele momento, afinal.[n][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][f 5 14]Por enquanto, devemos esperar por sua[n]mudança de coração em paz.[n][w][e]

[msg MSG_019_0_0 [Ann]]
[s][f 5 14][f 5 15]OK.[n][w][e]

