[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]Como estão os Phantom Thieves?[n]Eu criei[n]muitas maneiras de ajudá-lo.[n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]A propósito, tenho um relatório[n]para você. Você está livre hoje?[n][w][e]

[msg CHAT_NOREACTION_MSG [Mishima]]
[s][f 5 14]É a hora errada?[n]Vou convidá-lo outra hora.[n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]Estarei em Akihabara, me avise se passar[n]por aqui![n][w][e]

[msg CHAT_REACTION_MSG [Mishima]]
[s][f 5 14]Ok! Eu vou esperar![n][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Você vai aceitar[n]o convite de Mishima?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Vá agora[e]
[s]Verifique a conexão com Mishima[e]
[s]Responder mais tarde[e]

[sel SEL_002 top]
[s][f 5 14]Eu irei imediatamente.[e]

