[msg MSG_000_0_0 [Hifumi]]
[s][f 5 14]Você seria meu oponente hoje?[n]Eu gostaria de brincar com você.[n][w][e]

[msg MSG_001_0_0 [Hifumi]]
[s][f 5 14]Se você tiver tempo, estarei esperando no[n]local habitual.[n][w][e]

[msg MSG_002_0_0 [Hifumi]]
[s][f 5 14]Hifumi parece estar esperando por você na[n]igreja. Quer vê-la?[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Vá imediatamente [n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Decidir depois [e]
[s]Eu estarei lá.[e]

[sel SEL_002 top]
[s][f 5 14]Eu não vou me segurar só porque somos um[n]casal, ok?[n][e]

[msg MSG_REACTION [Hifumi]]
[s][f 5 14]Hifumi parece estar esperando por você na[n]igreja. Quer vê-la?[n][w][e]

[msg MSG_REACTION_02 [Hifumi]]
[s][f 5 14]Ninguém pensa que você está vivo neste[n]momento, então deve ficar bem, desde que[n]você seja cuidadoso.[n][f 5 15][w][e]

[msg MSG_CORP_PLAY_CHECK1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Hifumi parece estar esperando por você na[n]igreja. Quer vê-la?[n][f 1 3 65535][w][e]

[msg MSG_CORP_PLAY_CHECK2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0] [n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]{{12}}[n][f 1 3 65535][w][e]

