[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Hoje vamos ao Palácio,[n]certo?[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]Eu acho que é uma boa ideia. Mas[n]não devemos ter pressa.[n][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]Concordo. Honestamente, temos que ir lá se[n]quisermos fazer alguma coisa.[n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]Concordo. Você está bem,[n]líder?[n][w][e]

[sel SEL_004_0_0 top]
[s][f 5 14]Vamos.[e]
[s]Melhor ter cuidado.[e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Merda, sim! Vamos encontrar uma maneira de[n]alcançar o Tesouro![n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Claro que sim! Vamos pensar nisso![n][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][f 5 14][f 5 15]Nesse caso, encontre-se no esconderijo depois[n]da escola.[n][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Aceita. Vejo você no[n]ponto de encontro depois da escola.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Devemos contar a Yoshizawa? Bem,[n]talvez seja melhor deixá-la em paz.[n][f 1 3 65535][w][e]

