[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]Você está de férias amanhã, certo? Vou esperar[n]na reunião.[n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]Então...?[n][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]Devemos jogar juntos![n][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][f 5 14]Vou trazer-lhe um grande amanhã.[n][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][f 5 14]Vou mostrar a você como jogar,[n]para que você possa jogar[n]para relaxar![n][w][e]

[msg MSG_004_1_0 [Futaba]]
[s][f 5 14]Ah, mas se você estiver ocupado[n]eu posso esperar![n][f 5 15][w][e]

[msg MSG_004_2_0 [Futaba]]
[s][f 5 14]Ah, mas se você estiver ocupado[n]eu posso esperar![n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]Eu não tenho um console.[e]
[s]Eu não tenho dinheiro suficiente.[e]
[s]Eu não tenho uma televisão.[e]

[sel SEL_005_0_0_nonTV top]
[s][f 5 14]Eu não tenho dinheiro suficiente.[e]
[s]Eu não tenho uma televisão.[e]

[sel SEL_005_0_0_nonGame top]
[s][f 5 14]Eu não tenho um console.[e]
[s]Eu não tenho dinheiro suficiente.[e]

[msg MSG_006_0_0 [Futaba]]
[s][f 5 14]Estou sem palavras.[n][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][f 5 14]E você seria um homem[n]moderno?[n][w][e]

[msg MSG_008_0_0 [Futaba]]
[s][f 5 14]Tudo bem, estou saindo![n][f 5 15][w][e]

[msg MSG_MORGANA_GAME [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1192 65535 0]Já que seus amigos[n]estão sempre aqui, seria bom ter um[n]console de jogo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Talvez o brechó[n]na rua tenha um.[n]Você pode querer parar e verificar.[n][f 1 3 65535][w][e]

[msg MSG_MORGANA_TV_NotSet [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Espero que a TV que você encomendou[n]chegue logo...[n][f 1 3 65535][w][e]

[msg MSG_MORGANA_NoHaveTV [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1170 65535 0]Uma televisão, né? É uma pena que você[n]não possa usar o andar térreo.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quantas porcarias... Quem sabe,[n]talvez limpando[n]você encontre uma TV.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Futaba]]
[s][f 5 14]É um jogo antigo chamado[n]"Power Intuition".[n]É super legal.[n][w][e]

[msg MSG_010_0_0 [Futaba]]
[s][f 5 14]Tudo bem, estou saindo![n][f 5 15][w][e]

[msg MSG_999_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1020 65535 0]Devemos descansar um pouco[n]se Futaba estará aqui o dia todo[n]amanhã.[n][f 1 3 65535][w][e]

