[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]O que o Medjed vai fazer?[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]É difícil para mim entender o que poderia[n]ser.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]As pessoas realmente estiveram em pé de[n]guerra com toda a coisa de limpeza...[n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Pensar que um grupo global de hackers[n]estaria nos direcionando...[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Devemos simplesmente ignorá-los?[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]Se ao menos pudéssemos.[e]
[s]Nós temos que agir.[e]
[s]Sim, uma ideia de Greaaat.[e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Sim, acho que seria fácil se essa fosse[n]uma das nossas opções...[n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]Claro, mas...[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]Uhhh, desculpe! Meu mal, cara![n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Não importa como você olhe para isso,[n]precisamos de uma contramedida.[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Nossa melhor aposta seria o Alibaba...[n][w][e]

[msg MSG_011_0_0 [Makoto]]
[s][f 5 14]Mas ela pode não ser capaz disso em seu[n]estado atual.[n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14]Acho que devemos pensar em algumas outras[n]maneiras também.[n][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][f 5 14]Sim, seria melhor ter o maior número[n]possível de soluções.[n][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Bem, ainda temos tempo, então vamos criar[n]algo bom, k?[n][w][e]

