[msg MSG_000_0_0 [Chihaya]]
[s][f 5 14]Minhas previsões me disseram[n]que você está bem, mas...[n][w][e]

[msg MSG_001_0_0 [Chihaya]]
[s][f 5 14]Ainda estou preocupado com você,[n]deixe-me ouvir de você.[n][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Estou bem.[e]
[s]Tudo está bem.[e]

[msg MSG_003_0_0 [Chihaya]]
[s][f 5 14]Fico feliz em ouvir isso.[n][w][e]

[msg MSG_004_0_0 [Chihaya]]
[s][f 5 14]Parece que você conseguiu[n]evitar sua morte...[n][w][e]

[msg MSG_005_0_0 [Chihaya]]
[s][f 5 14]No entanto, não consigo ver além[n]disso.[n][w][e]

[msg MSG_006_0_0 [Chihaya]]
[s][f 5 14]Por favor, tenha muito cuidado.[n][w][e]

[msg MSG_007_0_0 [Chihaya]]
[s][f 5 14]Se você não tem certeza sobre algo,[n]espero por você no lugar de sempre.[n][f 5 15][w][e]

