[msg MSG_001_0_0 [Haru]]
[s][f 5 14]É incrível o que aconteceu com o[n]Mementos...[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]Seu poder é algo terrível.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Não pensei que Mementos[n]poderia ir tão[n]fundo! Eles são enormes![n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Tá mais pra longe. Perdi a conta de[n]quanto tempo passamos naquelas[n]escadas...[n][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][f 5 14]Verdade, né?!? Não é um lugar adequado[n]para quem tem físico de gamer...[n][w][e]

[msg MSG_006_0_0 [Sumire]]
[s][f 5 14]Vou dizer o óbvio, mas quando você está[n]com braços e pernas cansados, o[n]alongamento sempre ajuda.[n][w][e]

[msg MSG_007_0_0 [Sumire]]
[s][f 5 14]Uma boa massagem[n]nos pontos de pressão[n]também pode fazer bem.[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]Uau, a atleta sabe das coisas![n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]A propósito... Você não disse[n]que iria[n]treinar depois, Sumire?[n][w][e]

[msg MSG_010_0_0 [Sumire]]
[s][f 5 14]Sim, estou prestes a começar![n][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][f 5 14]MAS COMO VOCÊ?!? Onde[n]você consegue toda essa energia...?[n][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][f 5 14]Bem, depende de você.[n]Apenas tente[n]não ficar muito cansado.[n][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][f 5 14]Se você desperdiçar toda a sua energia,[n]você não será apenas inútil na batalha.[n]Você também será um fardo para todos.[n][w][e]

[msg MSG_014_0_0 [Sumire]]
[s][f 5 14][f 5 15]Então vou ter certeza[n]de não exagerar![n][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Bem, teremos que nos infiltrar no Palácio[n]novamente. Espero que não encontremos a[n]estrada bloqueada...[n][f 1 3 65535][w][e]

