[msg MSG_001_00 [Ann]]
[s][f 5 14]Como tá indo? Você encontrou alguma coisa?[n][w][e]

[sel SEL_002_00 top]
[s][f 5 14]Talvez um pouco.[e]
[s]Você já?[e]

[msg MSG_003_00 [Yusuke]]
[s][f 5 14]Ah, então você já entendeu algo. Como se[n]espera de alguém como você, [n][f 4 2].[n][w][e]

[msg MSG_003_01 [Yusuke]]
[s][f 5 14]Perguntamos por aí, mas não há como saber[n]quantos desses são protagonistas reais[n]neste momento.[n][w][e]

[msg MSG_004_00 [Ann]]
[s][f 5 14]Por que simplesmente não analisamos a[n]Intel que reunimos até agora?[n][w][e]

[msg MSG_005_00 [Ryuji]]
[s][f 5 14]Vou começar.[n][w][e]
[s][f 5 14]Supostamente, um cara perto do Accessway[n]conversando sobre algumas "drogas[n]fortes".[n][w][e]
[s][f 5 14]Não estou contando com nada, mas vou dar[n]uma olhada.[n][w][e]

[msg MSG_006_00 [Ann]]
[s][f 5 14]Quanto a mim, ouvi falar de alguém[n]solicitando um "trabalho bem remunerado"[n]na praça da estação.[n][w][e]
[s][f 5 14]Aparentemente, eles estão principalmente[n]mirando meninas. Vou ver o que se trata.[n][w][e]

[msg MSG_007_00 [Yusuke]]
[s][f 5 14]Do meu lado, ouvi dizer que há pessoas[n]dizendo coisas estranhas no beco dos[n]fundos perto do fliperama.[n][w][e]
[s][f 5 14]Algo sobre gelo e vegetais, e algo sobre[n]neve amanhã...[n][w][e]
[s][f 5 14][f 5 15]Vou observar, apenas por precaução. O[n]fliperama está na Central Street,[n]correto?[n][w][e]

[msg MSG_008_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Tudo bem, devemos fazer o possível para[n]ajudá-los.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Não tenho idéia de quais desses leads são[n]reais. Tente ir para o lugar mais[n]suspeito.[n][f 1 3 65535][w][e]

