[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]Eu tenho que ir para a universidade para[n]deixar papéis.[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Podemos nos ver primeiro?[n][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][f 5 14][f 4 2]-kun...[n]Há uma coisa que eu quero te dar.[n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Estou em Shujin agora. Vamos nos encontrar[n]na estação Aoyama-Itchome.[n][f 5 15][w][e]

[msg MSG_LAST_GREETING_DOOR_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Você ainda não falou[n]com nenhum deles. Você ainda quer ir[n]ver a Makoto?[n][f 1 3 65535][w][e]

[msg MSG_LAST_GREETING_DOOR_0_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Você ainda não conversou com Futaba. Você[n]ainda quer ir ver a Makoto?[n][f 1 3 65535][w][e]

[msg MSG_LAST_GREETING_DOOR_0_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Você ainda não falou[n]com o chefe. Você ainda quer ir[n]ver a  Makoto?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Quer ir ver a Makoto?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Vá agora[e]
[s]Decidir depois[e]

