[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Aqui está nossa foto comemorativa do[n]festival de verão! Ou pelo menos... essa[n]era a ideia.[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14][f 5 18 483 80 1][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]É... definitivamente evocativo.[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]E vabbeh...[n]Essas são coisas que acontecem.[n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]É compreensível devido ao calor. Suas[n]palmas provavelmente estavam suadas e[n]você perdeu o controle.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Da próxima vez, vamos[n]a um lugar onde possamos[n]comer de verdade.[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Concordo. Pessoalmente, eu preferiria um[n]local interno.[n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14]Possivelmente com[n]assentos espaçosos[n]e água grátis.[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]Hum... Então acabamos[n]no restaurante novamente.[n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14]Por que não? É um lugar tranquilo[n]que também serve uma comida[n]deliciosa.[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14]Sim, isso é... Bem, falar[n]sobre comida me deu fome.[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]Ramen instantâneo agora[n]seria o ideal.[n][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Eu seguirei o exemplo. Felizmente,[n]recentemente coloquei minhas mãos em[n]algumas crostas de pão realmente[n]deliciosas.[n][w][e]

[msg MSG_014_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1032 65535 0]Lamento não ter conseguido pegá-lo. Eu sempre esqueço[n]como minhas patas felinas são curtas...[n][f 1 3 65535][w][e]

