[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Você ouviu falar sobre essa merda de[n]limpeza no Parque Inokashira?[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Será a ideia do diretor para[n]a reputação da escola, depois que[n]Kamoshida a escandalizou.[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Acho que o verbo "escandalizar"[n]não existe.[n][w][e]
[s][f 5 14]Mas eu entendo o que você quer dizer.[n]Além disso, todas as coisas de[n]consultoria parecem uma jogada[n]desesperada para mim.[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]Eles fazem o que podem.[e]
[s]É tudo tão irritante.[e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]Todas as garotas da turma estão loucas por[n]esse cara novo.[n][w][e]
[s][f 5 14]Eles dizem que Maruki é "legal",[n]"legal", "sensível" ... Todos eles[n]acham que ele é o tipo deles.[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Uau, isso deve ser muito popular.[n][w][e]

[msg MSG_011_0_0 [Ann]]
[s][f 5 14]Ah sim, você já foi[n]a uma das sessões dele?[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]Ah Merda. Eu esqueci.[n][w][e]
[s][f 5 14]Mas eu não sei... eu realmente não gosto disso.[n]Você sabe o que quero dizer, não é,[n][f 4 2]?[n][w][e]

[sel SEL_013_0_0 top]
[s][f 5 14]Eu já fui lá.[e]
[s]Ele é um bom conselheiro.[e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14]Uau! Sério?[n][w][e]

[msg MSG_015_0_0 [Ann]]
[s][f 5 14]Você deveria ir lá.[n][w][e]
[s][f 5 14]Se você arrastá-lo e atrair[n]atenção, nós[n]iremos pagar as consequências.[n][w][e]

[msg MSG_015_0_1 [Ann]]
[s][f 5 14]Você deveria ir lá. Bem,[n]hoje você não pode, mas...em breve.[n][w][e]
[s][f 5 14]Se você arrastá-lo e atrair[n]atenção, nós[n]iremos pagar as consequências.[n][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][f 5 14][f 5 15]E tudo bem...[n][w][e]

