[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]Eu acho que você já sabe disso...[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Mas fui ordenado pelo diretor Kobayakawa[n]para procurar os culpados.[n][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Culpados?[e]
[s]Ele está com nós?[e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Sim, os responsáveis pelo cartão de[n]visita.[n][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][f 5 14]Parece que estamos bem por enquanto, mas[n]não podemos decepcionar nossa guarda.[n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]Peço que você tente não se destacar por[n]um tempo.[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]A propósito, geralmente passo meu tempo[n]na sala do conselho estudantil.[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14][f 5 15]Se houver uma emergência, fique à vontade[n]para vir me encontrar lá.[n][w][e]

