[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Vamos entrar no Palácio![n][w][e]

[msg MSG_000_0_1 [Ryuji]]
[s][f 5 14]Não deveríamos encontrar[n]um caminho para o Tesouro?[n]O prazo está bem próximo...[n][w][e]

[msg MSG_000_0_2 [Ryuji]]
[s][f 5 14][f 5 15]Você tem que reunir todos.[n][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]O que você quer fazer? Devemos nos reunir[n]no local de encontro e entrar no Palácio?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir para o ponto de encontro[e]
[s]Decidir depois[e]

[sel SEL_002 top]
[s][f 5 14]Vejo você na reunião.[e]

[msg MSG_REACTION [Ryuji]]
[s][f 5 14]Vá, pronto![n][w][e]

[msg MSG_REACTION_02 [Ryuji]]
[s][f 5 14]Vou correr agora mesmo![n][f 5 15][w][e]

