[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Ei, [f 4 2].[n]Então, o que aconteceu depois?[n]Você sabe, sobre a coisa da empregada.[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Sem problemas.[e]
[s]Onde está a Sra. Chouno?[e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]O que isso deveria significar!?[n]Me dê os detalhes![n][w][e]

[sel SEL_003_0_0 top]
[s][f 5 14]Onde está a Sra. Chouno?[e]
[s]Vamos derrubar a Sra. Chouno.[e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Chouno está pegando Kawakami depois da[n]escola ultimamente...[n][w][e]

[msg MSG_004_1_0 [Ryuji]]
[s][f 5 14]Eu os encontrei hoje em frente ao[n]escritório da faculdade.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Espere, por que você passou da coisa da[n]empregada para Chouno!?[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Ei...[n]O que há sobre uma empregada?[n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]Porcaria, isso é um bate-papo em grupo!?[n]janela errada![n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]Você está tramando algo de novo?[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]Não é nada![n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Aposto que é algo estúpido.[n]Só não me arraste para isso.[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Sim, sim, desculpe.[n][w][e]

[msg MSG_100_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Kawakami disse que faria qualquer coisa[n]se tivéssemos Chouno nas costas dela.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Qualquer coisa, hein... isso meio que faz[n]você se sentir esperançoso, certo?[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Eles estão em frente ao escritório da[n]faculdade agora. Devemos ir ajudar?[n][f 1 3 65535][w][e]

[msg MND_100_0_0]
[s][vp 1 0 0 0 0 0]Parece que Kawakami caiu sob a suspeita[n]de Chouno. Se eu a ajudar, ela pode[n]fazer algo por mim...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Parece que eles estão em frente ao[n]escritório da faculdade. Talvez eu deva[n]voltar a ela.[n][f 1 3 65535][w][e]

