[msg MSG_CHAT_quest15_clear_0 [Mishima]]
[s][f 5 14]Você fez isso! Ele teve[n]um despertar do coração, yay![n][w][e]

[msg MSG_CHAT_quest15_clear_0_2 [Mishima]]
[s][f 5 14]Houve um post de agradecimento no fórum.[n]Ele finalmente entendeu o mal que causou.[n][w][e]

[msg MSG_CHAT_quest15_clear_0_3 [Mishima]]
[s][f 5 14][f 5 15]Acho que a gota d'água foi perceber que[n]seu sobrinho o odiava. Sinto um pouco de[n]pena dele.[n][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parece que seu coração[n]despertou verdadeiramente.[n]Bom trabalho![n][f 1 3 65535][w][e]

[msg MND_quest15_CLEAR_SELF]
[s][vp 1 0 0 0 0 0]Parece que conseguimos[n]acordar o coração[n]do alvo...[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Script fictícioChat_240[e]

