[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]Você... lembra que dia é hoje?[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Espere, eu não quero dizer isso para soar[n]como se eu estivesse incomodando você...[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Tenho coberto.[e]

[msg MSG_020_0_0 [Makoto]]
[s][f 5 14]Ok, eu acho...[n][w][e]

[msg MSG_021_0_0 [Makoto]]
[s][f 5 14]Então vamos nos encontrar na estação[n]Shibuya. Eu te vejo lá.[n][f 5 15][w][e]

