[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Não temos tempo restante![n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Você sabe o Conselho de Administração em[n]dois dias, certo?[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Vamos ser expulsos a esse ritmo![n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Apenas venha para o esconderijo, ok?[n]Estaremos esperando por você.[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14][f 5 15]E se você não vai mostrar, não tenho medo[n]de entrar sozinho.[n][w][e]

