[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Arihara escreveu um post[n]no Phan-Site.[n][w][e]
[s][f 5 14]Ele disse a verdade a todas as garotas. E[n]ele também está devolvendo o dinheiro[n]roubado.[n][w][e]
[s][f 5 14]Eu não sei como ele vai reparar aqueles[n]que ele machucou, ou aqueles que[n]deixaram a escola...[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Parece complicado.[e]
[s]Não há mais vítimas, no entanto.[e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Já...[n][w][e]
[s][f 5 14]Não é exatamente a conclusão mais decorosa,[n]eu acho.[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Já! É certamente algo[n]para se alegrar.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Acho que essa missão[n]me fez repensar toda a[n]Kamoshida.[n][w][e]
[s][f 5 14]Ele era tão popular.[n]Embora ele abusasse de seu poder[n]para conseguir o que queria.[n][w][e]
[s][f 5 14]Na época ... eu me senti como se não[n]tivesse escolha a não ser enorme-lo.[n][w][e]
[s][f 5 14]Então, quando parecia que[n]Arihara estava manipulando essas[n]garotas igualmente…[n][w][e]
[s][f 5 14]Não sei. Acho que um pouco[n]dessa raiva foi[n]retirada.[n][w][e]
[s][f 5 14]É um pouco embaraçoso,[n]retrospectiva ...[n][w][e]
[s][f 5 14]Sinto muito.[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]Não se preocupe.[e]
[s]Isso é típico de você.[e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]...Sim, eu acho que sim![n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14][f 5 15]Obrigado, [f 4 2].[n][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1180 65535 0]Fico feliz em ver Lady Ann[n]tão feliz. Seu sorriso[n]torna tudo mais suportável.[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Você pode ver o sorriso dela?[e]
[s]É apenas uma mensagem.[e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][vp 8 2 1 53113 65535 0]C-Cala a boca! Eu vejo[n]na minha cabeça, tá!?![n][f 1 3 65535][w][e]

