[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Ei, aquele repórter[n]ouviu, por acaso?[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]Nós só escrevemos para ela[n]anteontem. Qual é a pressa?[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Não sei. Procurei[n]informações, mas[n]não encontrei nada...[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Nós só temos duas semanas,[n]coisa. Estamos com pressa.[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]São dez dias,[n]para ser exato.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Mesmo começando imediatamente[n]após a resposta dele, nunca[n]chegaremos a tempo.[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Aparentemente, então, vai[n]ter que ser uma luta rápida.[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Também temos que decidir[n]o que fazer se ele não[n]responder.[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]Não traga má sorte![n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Estou apenas explorando[n]todas as possibilidades.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Você não está nervoso?[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]Nervosismo não vai nos ajudar a resolver[n]nada.[n][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][f 5 14]Se fosse a solução para[n]nossos problemas, eu provavelmente[n]iria entrar em pânico imediatamente.[n][w][e]

[msg MSG_013_0_0 [Ann]]
[s][f 5 14]Uau, ele quase se parece com um filósofo...[n][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Na minha opinião é estúpido e é isso.[n][w][e]

