[msg MSG_000_0_0 [Nanami]]
[s][f 5 14]Desculpe pela ligação repentina.[n]Sou Shibuya, da[n]loja de conveniência.[n][w][e]

[msg MSG_001_0_0 [Nanami]]
[s][f 5 14]Eu queria saber se você poderia[n]vir hoje?[n][w][e]

[msg MSG_002_0_0 [Nanami]]
[s][f 5 14]Damos pontos em dobro aos clientes com[n]o cartão, então estamos[n]um pouco sobrecarregados.[n][w][e]

[msg MSG_003_0_0 [Nanami]]
[s][f 5 14]Se você pudesse me ajudar,[n]eu agradeceria muito![n][w][e]

[msg MSG_004_0_0 [Nanami]]
[s][f 5 14]Oh, certo! O gerente disse[n]que você ganhará extra em[n]dias como esse![n][w][e]

[msg MSG_005_0_0 [Nanami]]
[s][f 5 14]Se não puder, tudo bem, mas se tiver[n]tempo, por favor, venha[n]ajudar![n][f 5 15][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1066 65535 0]Então, haverá muitas pessoas lá?[n]Pode ser útil praticar[n]seu [f 4 11 1][clr 26][f 4 12 1][clr 27].[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E você também ganha mais.[n]Pode valer a pena...[n][f 1 3 65535][w][e]

