[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]No fórum as coisas estão esquentando[n]muito! Eu coloquei um post especial de[n]propósito![n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]"O confronto final entre os[n]justos Phantom Thieves e[n]a organização Medjed está chegando!"[n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]As reações são excelentes.[n]Todos estão cativados.[n][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][f 5 14]Por enquanto, a maioria dos[n]comentários são nossos.[n][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][f 5 14]Provavelmente, graças ao que[n]aconteceu com Kaneshiro.[n][w][e]

[msg MSG_005_0_0 [Mishima]]
[s][f 5 14]No entanto, há quem diga que os Medjed[n]são "hackers da justiça".[n][w][e]

[msg MSG_006_0_0 [Mishima]]
[s][f 5 14]Mas não há nada certo no que eles[n]fazem.[n][w][e]

[msg MSG_007_0_0 [Mishima]]
[s][f 5 14]Desejo que um dia todo o site esteja[n]cheio de comentários a nosso favor.[n][w][e]

[msg MSG_008_0_0 [Mishima]]
[s][f 5 14][f 5 15]Mal posso esperar para que esse dia chegue.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 13 0 0]Ele pode esperar o que quiser,[n]mas não temos como[n]reagir a Medjed.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 14 0 0]Se não fizermos nada[n]nós teremos problemas...[n][f 1 3 65535][w][e]

