[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]Alerta vermelho! Diretiva de emergência![n][w][e]
[s][f 5 14]Um vilão Otaku tem contaminado a Terra Santa.[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Terra Santa?[e]
[s]Otaku vilão?[e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]Akihabara, duh. Tente acompanhar.[n][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][f 5 14]Sim. Os relatórios dizem que este Blackguard[n]assombra Akihabara.[n][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][f 5 14]Você sabe quem é o alvo?[n][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][f 5 14]Ele é um idiota, é o que ele é. Ele corta na[n]fila, ele toca mercadoria de edição[n]limitada...[n][w][e]
[s][f 5 14]Ele até bate os transeuntes e danifica as[n]coisas legais que eles acabaram de comprar.[n][w][e]
[s][f 5 14]As pessoas o apelidaram...[n]"Enfrentar." [n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Você não tem o nome verdadeiro dele?[n][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][f 5 14]Houve relatos das vítimas, mas não muito no[n]próprio cara.[n][w][e]
[s][f 5 14][f 5 15]Posso pedir a todos vocês para obter mais[n]informações?[n][w][e]

