[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Você tem minha gratidão.[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]O que você é tão educado por de repente?[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Eu realmente sou grato a você por me[n]fazer chegar aos meus sentidos.[n][w][e]

[sel SEL_003_0_0 top]
[s][f 5 14]Estas a exagerar.[e]
[s]Você nos deve um.[e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Eu certamente não sou. Devo expressar[n]minha gratidão sinceramente.[n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]De fato. Vou devolver o favor algum dia.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Você é um de nós agora, cara.[n]Estaremos contando com você, Mkay?[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]É claro.[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]E se alguma coisa surgir, não hesitaremos[n]em ajudar.[n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Obrigada.[n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Bem, então, vejo você.[n][w][e]

