[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]Eu tenho um favor para pedir...[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]O conselho estudantil está recebendo[n]queixas em relação a um personagem[n]suspeito em Ikebukuro.[n][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][f 5 14]Tecnicamente, essa não é a jurisdição da[n]escola, mas muitos estudantes vão para[n]lá, então...[n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Estou pensando em visitar amanhã para[n]investigar. Posso pedir para você se[n]juntar a mim?[n][f 5 15][w][e]

[msg MSG_101_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Qual é o plano? Você vai com Makoto?[n][f 1 3 65535][w][e]

[sel SEL_111_0_0 top]
[s]Comprometer-se [e]
[s]Declínio [e]
[s]Responda mais tarde [e]

[sel SEL_111_1_0 top]
[s]Acesse imediatamente [e]
[s]Declínio [e]
[s]Responda mais tarde [e]

[msg MSG_999_0_0 [Makoto]]
[s][f 5 14]Vou tentar essa investigação hoje. Você[n]pode me ajudar com isso?[n][f 5 15][w][e]

[sel SEL_200_0_0 top]
[s][f 5 14]Vamos.[e]
[s]Eu tenho planos.[e]

[msg MSG_201_0_0 [Makoto]]
[s][f 5 14]Muito apreciado.[n][w][e]

[msg MSG_202_0_0 [Makoto]]
[s][f 5 14]Vários relatórios de testemunhas oculares[n]mencionaram o [n][clr 2]planetário [clr 27].[n][w][e]

[msg MSG_203_0_0 [Makoto]]
[s][f 5 14]Então seria um bom lugar para se[n]encontrar, eu acho. Vejo você lá.[n][f 5 15][w][e]

[msg MSG_201_1_0 [Makoto]]
[s][f 5 14]Muito apreciado.[n][w][e]

[msg MSG_202_1_0 [Makoto]]
[s][f 5 14]Vários relatórios de testemunhas oculares[n]mencionaram o [n][clr 2]planetário [clr 27].[n][w][e]

[msg MSG_203_1_0 [Makoto]]
[s][f 5 14]Então seria um bom lugar para se[n]encontrar, eu acho. Vejo você lá.[n][f 5 15][w][e]

[msg MSG_210_0_0 [Makoto]]
[s][f 5 14]Entendo... bem, suponho que é assim que[n]tem que ser.[n][w][e]
[s][f 5 14]Deixe para mim. Vou me certificar de[n]pegar este causador de problemas.[n][f 5 15][w][e]

[msg MSG_400_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Alguém suspeito no planetário?[n]Me pergunto o que está acontecendo lá...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Bem, não adianta pensar demais. Vamos[n]para a cama.[n][f 1 3 65535][w][e]

[msg MSG_401_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Alguém suspeito no planetário?[n]Me pergunto o que está acontecendo lá...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Bem, não faz sentido pensar demais. Vamos[n]para o ponto de encontro.[n][f 1 3 65535][w][e]

[msg MSG_402_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Não vou desta vez, hein? Você teve planos[n]hoje?[n][f 1 3 65535][w][e]

[msg MSG_403_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Adiando por enquanto, hein? Não se[n]esqueça de responder mais tarde.[n][f 1 3 65535][w][e]

[msg ERROR_MSG_000_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, estou prestes a abrir a loja.[n]Você pode adiar a mexer com seu telefone[n]por enquanto?[n][w][e]

[msg ERROR_MSG_001_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]O chefe ficou bravo com você...[n]Talvez você deva responder mais tarde.[n][w][e]

[msg MND_CHAT_INVITE_STOP]
[s]Estou comendo agora. Talvez eu deva[n]responder mais tarde...[n][w][e]

[msg MND_COOP_RANK_UP_OK]
[s]Eu me sinto como meu vínculo com [var 7][n]Vai ficar mais forte em breve...[n][w][e]

[msg MND_COOP_RANK_UP_ROCK]
[s]Eu me sinto como meu vínculo com [var 7][n]Vai ficar mais forte em breve, mas...[n][w][e]

[msg MND_COOP_RANKUP_2]
[s]Esta pode ser uma boa oportunidade para[n]fortalecer meu vínculo com [n][var 7]...[n][w][e]

[msg MND_COOP_DOUZOKUSEI_HAVE]
[s]Eu sinto que posso me aproximar [n][var 7]Graças ao [var 2][n]Persona [clr 1][var 5][clr 27]...[n][w][e]

[msg MSG_SPOT_OPEN_KANDA]
[s]Agora você pode ir para [clr 2]Kanda [clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_SHINJUKU]
[s]Agora você pode ir para [clr 2]Shinjuku [clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_AKIHABARA]
[s]Agora você pode ir para [clr 2]Akihabara [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]gostam lá para sair com você.[n][w][e]

[msg MSG_SPOT_OPEN_INOKASHIRA]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Parque Inokashira [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]gostam lá para sair com você.[n][w][e]

[msg MSG_SPOT_OPEN_OGIKUBO]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Ogikubo Ramen [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]podem comer ramen para sair com você lá.[n][w][e]

[msg MSG_SPOT_OPEN_ODAIBA]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Parque Seasa de Odaiba [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]podem gostar desses parques para sair[n]com você lá.[n][w][e]

[msg MSG_SPOT_OPEN_UENO]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Museu Ueno [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]possam desfrutar de museus de arte para[n]sair com você lá.[n][w][e]

[msg MSG_SPOT_OPEN_TSUKISHIMA]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Tsukishima Monja [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]podem comer Monjayaki para sair com você[n]lá.[n][w][e]

[msg MSG_SPOT_OPEN_HARAJUKU]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Harajuku Takenoko Street [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]possam desfrutar da Takeko Street para[n]sair com você lá.[n][w][e]

[msg MSG_SPOT_OPEN_TYUKAGAI]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Motomachi Chinatown [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]gostam lá para sair com você.[n][w][e]

[msg MSG_SPOT_OPEN_MAIHAMA]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Maihama Destinyland [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]gostam lá para sair com você.[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Asakusa [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]possam apreciar a rua Skytree ou[n]Nakamise para sair com você lá.[n][w][e]

[msg MSG_SPOT_OPEN_IKEBUKURO]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Ikebukuro Planetarium [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]gostam lá para sair com você.[n][w][e]

[msg MSG_SPOT_OPEN_MEIJIJINGU]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Santuário Meiji [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]gostam lá para sair com você.[n][w][e]
[s]Além disso, você pode ir sozinho para[n]prestar homenagem ao santuário, se[n]desejar.[n][w][e]

[msg MSG_SPOT_OPEN_SUIDOUBASH]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Cidade de Suidobashi Dome [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]gostam lá para sair com você.[n][w][e]

[msg MSG_SPOT_OPEN_SHIBUYA]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Shibuya Wilton Hotel [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]gostam lá para sair com você.[n][w][e]

[msg MSG_SPOT_OPEN_GINZA]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Barra de sushi de ginza [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]podem comer sushi caro para sair com[n]você lá.[n][w][e]

[msg MSG_SPOT_OPEN_JINBOCHO]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Cidade do Livro JinboCho [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]gostam lá para sair com você.[n][w][e]
[s]Além disso, você pode ir sozinho para[n]fazer compras, se desejar.[n][w][e]

[msg MSG_SPOT_OPEN_ICHIGAYA]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Ichigaya Pisca de pesca [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]podem gostar de pescar para sair com[n]você lá.[n][w][e]
[s]Além disso, você pode ir sozinho e tentar[n]pescar, se assim escolher.[n][w][e]

[msg MSG_SPOT_OPEN_SHINAGAWA]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Aquário Shinagawa [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]possam desfrutar do aquário para sair[n]com você lá.[n][w][e]

[msg MSG_SPOT_OPEN_NAKANO]
[s]Agora você tem informações sobre um novo[n]ponto de encontro: [n][clr 2]Distrito de construção de comércio de[n]Nakano  [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que[n]possam desfrutar desse local para sair[n]com você lá.[n][w][e]

