[msg MSG_000_0_0 [Takemi]]
[s][f 5 14]Como seu médico, gostaria de confirmar[n]algo.[n][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][f 5 14]Entre em contato comigo assim que você[n]vir isso.[n][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]O que você precisa?[e]
[s]Eu ainda estou vivo.[e]

[msg MSG_003_0_0 [Takemi]]
[s][f 5 14]Pare de me deixar preocupado.[n][w][e]

[msg MSG_004_0_0 [Takemi]]
[s][f 5 14]Estou feliz que você esteja bem. Acabei[n]de ficar nervoso quando vi a notícia.[n][w][e]

[msg MSG_005_0_0 [Takemi]]
[s][f 5 14]Bem, estarei na clínica se você precisar[n]de algum medicamento.[n][f 5 15][w][e]

