[msg MSG_033_0_0 [Mishima]]
[s][f 5 14]Ei, parece que Kosei Queen teve uma[n]mudança de coração![n][w][e]
[s][f 5 14]Ela se acalmou e realmente pediu[n]desculpas ao estudante do sexo masculino.[n][w][e]
[s][f 5 14]Então, como foi?[n][w][e]

[sel SEL_034_0_0 top]
[s][f 5 14]Ela nos tratou como porcos.[e]
[s]Eu acho que gostei.[e]
[s]Ela era irritante.[e]

[msg MSG_035_0_0 [Mishima]]
[s][f 5 14]Os ladrões fantasmas, porcos!?[n]Você fez a escolha certa mudando o[n]coração dela![n][w][e]

[msg MSG_036_0_0 [Mishima]]
[s][f 5 14]Você está brincando certo? Ou você é[n]realmente um masoquista...?[n][w][e]

[msg MSG_037_0_0 [Mishima]]
[s][f 5 14]Pensei isso.[n][w][e]

[msg MSG_038_0_0 [Mishima]]
[s][f 5 14][f 5 15]De qualquer forma, os ladrões fantasmas[n]levaram outro alvo em forma![n]Vocês são tão confiáveis![n][w][e]

[msg MSG_039_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Ei, parece que ela mudou de coração! Eu[n]me pergunto se ela e o cara serão amigos[n]de agora em diante...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]... Você acha que existem reis ou rainhas[n]reais em lembranças...?[n][f 1 3 65535][w][e]

[msg MND_quest21_CLEAR_SELF]
[s][vp 8 2 65535 0 0 0]Parece que desencadeamos com sucesso uma[n]mudança de coração no alvo...[n][f 1 3 65535][w][e]

