[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Obrigado novamente por me deixar ficar a[n]noite.[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]Desculpas por sair tão silenciosamente,[n]mas seu descanso parecia pacífico.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Depois de muita luta interior, decidi[n]voltar aos dormitórios.[n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]Além disso, confiei o "Sayuri" ao seu[n]protetor, Sojiro.[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Essa pintura não deve mais existir na[n]realidade... mas é realmente o que minha[n]mãe pintou.[n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]Estou simplesmente satisfeito por termos[n]conseguido obtê-lo.[n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]E foi tudo por causa de vocês. Não posso[n]agradecer o suficiente.[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14][f 5 15]PS, eu ainda acredito que mingau é a[n]melhor maneira de terminar uma panela[n]quente.[n][w][e]

