[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Alguma palavra de Akechi?[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Nenhuma coisa.[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]Mas amanhã é o início do festival escolar.[n]Vai ficar bem?[n][w][e]

[msg MSG_003_0_0 [Haru]]
[s][f 5 14]Se Akechi-kun recusar nossa oferta, não[n]teremos um convidado...[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Huh? É com isso que você está preocupado?[n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]Agradeço a preocupação, mas vai ficar bem.[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Eu só preciso fazer Akechi-kun concordar[n]com isso de alguma forma.[n][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][f 5 14]Sim.[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]O que é esse bastardo de qualquer maneira?[n][w][e]

[msg MSG_009_0_0 [Futaba]]
[s][f 5 14]Ele não fez nada desde que disse que iria[n]se esconder.[n][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][f 5 14]Não tenho certeza. Vou tentar explicar as[n]circunstâncias em torno do festival[n]escolar para ele novamente.[n][w][e]

[msg MSG_011_0_0 [Makoto]]
[s][f 5 14]Espero que ele possa me dar uma resposta[n]até o final do dia.[n][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][f 5 14][f 5 15]Avisarei você se fizer algum progresso[n]nessa frente.[n][w][e]

