[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Eu fui ver Shiho hoje.[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]E eu disse a ela que resolvemos as coisas[n]com Kamoshida.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Ela ainda não recuperou a consciência...[n]mas eu tive que fazer as pazes.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Whaddya significa? Você não fez nada de[n]errado, Ann.[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Direita, [f 4 2]?[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]Não é sua culpa, Ann.[e]
[s]Isso está fazendo Kamoshida.[e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Mas eu não estava lá quando ela precisava[n]de ajuda. Sou um fracasso como amigo...[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Eu tenho que fazer tudo o que puder para[n]compensar isso, começando agora.[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]Caso contrário, acho que não poderei[n]seguir em frente.[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]Cara, eu não sabia que você era tão[n]apaixonado.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Eu não percebi totalmente isso no ensino[n]médio.[n][w][e]

[msg MSG_011_0_0 [Ann]]
[s][f 5 14]Eu acho que é por causa de vocês.[n]Estou um pouco envergonhado...[n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14][f 5 15]Enfim, Ryuji, [f 4 2]...[n]Espero que possamos continuar ajudando um[n]ao outro a partir de agora também.[n][w][e]

