[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Alguém conseguiu entrar em contato com[n]Haru?[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Eu não tenho.[e]
[s]Estou preocupado com ela.[e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Sem sorte aqui.[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Nem eu.[n][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][f 5 14]Ela não vai pegar.[n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]Também não parece que ela tenha visto[n]nenhum de nossos bate-papos.[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14][f 5 15]Estou preocupado com ela...[n][w][e]

