[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]Deus, estou furiosa![n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]Você ouviu o que Akechi disse,[n]certo, [f 4 1]?[n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]Como você ousa chamar os[n]Phantom Thieves de criminosos?[n][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][f 5 14]Como administrador do site[n]Phantom Aficionado,[n]não posso deixar de responder.[n][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][f 5 14]Vou mostrar a Akechi[n]como as pessoas na net realmente pensam![n][w][e]

[msg MSG_005_0_0 [Mishima]]
[s][f 5 14]Vou mudar a[n]pergunta da pesquisa pela manhã.[n][w][e]

[msg MSG_006_0_0 [Mishima]]
[s][f 5 14][f 5 15]A justiça está do lado dos Phantom[n]Thieves! Continue fazendo seu trabalho![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]...Por que, de todas as pessoas,[n]é ele quem está chateado?[n][f 1 3 65535][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 2 0 0]De qualquer forma, ele estava falando[n]sobre a pesquisa no Phan-Site, certo?[n]Vamos apenas esperar para ver.[n][f 1 3 65535][w][e]

