[msg MSG_000_0_0 [Ohya]]
[s][f 5 14]Você não veio ultimamente.[n][w][e]

[msg MSG_001_0_0 [Ohya]]
[s][f 5 14]Você não se deparou com nenhuma pista[n]interessante para mim? Ou...[n][w][e]

[msg MSG_002_0_0 [Ohya]]
[s][f 5 14]Não estou vendo você porque você não[n]precisa mais de informações minhas?[n][f 5 15][w][e]

[msg MSG_003_0_0 [Ohya]]
[s][f 5 14]Estarei esperando no bar esta noite...[n][f 5 15][w][e]

[msg CHAT_NOREACTION_MSG [Ohya]]
[s][f 5 14]Por que você não veio? Eu esperei por[n]você o tempo todo![n][w][e]

[msg CHAT_REACTION_MSG [Ohya]]
[s][f 5 14]OK.[n][f 5 15][w][e]

[msg MND_COOP_RANK_UP_OK]
[s]Eu sinto que meu vínculo com Ohya ficará[n]mais forte em breve...[n][w][e]

[msg MSG_MORUGANA_RANK1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Tome cuidado. Você parecerá suspeito se[n]recusar um convite depois de fazer um[n]acordo com alguém.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Se você não tem mais nada planejado,[n]certifique-se de ir, ok?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_RANK2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Tome cuidado. Você parecerá suspeito se[n]recusar um convite depois de fazer um[n]acordo com alguém.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Se você não tem mais nada planejado,[n]certifique-se de ir, ok?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_RANK3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Tome cuidado. Você parecerá suspeito se[n]recusar um convite depois de fazer um[n]acordo com alguém.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Se você não tem mais nada planejado,[n]certifique-se de ir, ok?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_RANK4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Tome cuidado. Você parecerá suspeito se[n]recusar um convite depois de fazer um[n]acordo com alguém.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Se você não tem mais nada planejado,[n]certifique-se de ir, ok?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_RANK5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Tome cuidado. Você parecerá suspeito se[n]recusar um convite depois de fazer um[n]acordo com alguém.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Se você não tem mais nada planejado,[n]certifique-se de ir, ok?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_CORPNG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Você deve estar cansado da sua viagem ao[n]metaverso. Talvez você deva descansar um[n]pouco hoje.[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]De cabeça para baixo [e]
[s]Verifique o vínculo com ohya [e]
[s]Responda mais tarde [e]

[sel SEL_002 top]
[s][f 5 14]Eu estarei lá.[e]

[msg MND_COOP_DOUZOKUSEI]
[s]Eu sinto que posso me aproximar de Ohya[n]graças ao [n][var 2][n]Persona [clr 1][var 5][clr 27]...[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]Agora você pode acessar um novo local: [clr 1]Asakusa [clr 27].[n][w][e]

