[msg MSG_000_0_0 [Chihaya]]
[s][f 5 14]Ei, há alguma razão para que[n]você não tenha vindo para obter[n]sua sorte?[n][w][e]

[msg MSG_001_0_0 [Chihaya]]
[s][f 5 14]Eu gosto quando você vem[n]me visitar...[n][w][e]

[msg MSG_002_0_0 [Chihaya]]
[s][f 5 14]Aguardo você no[n]lugar de sempre, em Shinjuku.[n][f 5 15][w][e]

[msg CHAT_NOREACTION_MSG [Chihaya]]
[s][f 5 14]Eu esperei por você, mas...[n]vou convidá-lo novamente, da próxima[n]vez que você vier, por favor.[n][w][e]

[msg CHAT_REACTION_MSG [Chihaya]]
[s][f 5 14]Espero por ti[n]no sítio do costume![n][f 5 15][w][e]

[msg MND_COOP_RANK_UP_OK]
[s]Sinto que em breve meu vínculo com[n]Chihaya se fortalecerá...[n][w][e]

[msg MSG_MORUGANA_RANK1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Preste atenção. Se você recusar um[n]convite imediatamente após fazer um[n]acordo com alguém, isso parecerá[n]suspeito.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Se você não tem outras coisas[n]para fazer, certifique-se de[n]aceitar. Entendeu?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Acho que vou passar algum[n]tempo no Red Light District.[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_RANK2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Preste atenção. Se você recusar um[n]convite imediatamente após fazer um[n]acordo com alguém, isso parecerá[n]suspeito.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Se você não tem outras coisas[n]para fazer, certifique-se de[n]aceitar. Entendeu?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_RANK3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Preste atenção. Se você recusar um[n]convite imediatamente após fazer um[n]acordo com alguém, isso parecerá[n]suspeito.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Se você não tem outras coisas[n]para fazer, certifique-se de[n]aceitar. Entendeu?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_RANK4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0][f 4 25 1 65535 0 0]Preste atenção. Se você recusar um[n]convite imediatamente após fazer um[n]acordo com alguém, isso parecerá[n]suspeito.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Se você não tem outras coisas[n]para fazer, certifique-se de[n]aceitar. Entendeu?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_RANK5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0][f 4 25 1 65535 0 0]Preste atenção. Se você recusar um[n]convite imediatamente após fazer um[n]acordo com alguém, isso parecerá[n]suspeito.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Se você não tem outras coisas[n]para fazer, certifique-se de[n]aceitar. Entendeu?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_CORPNG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Você deve estar cansado de sua última[n]visita ao Metaverso. Talvez[n]você devesse descansar um pouco hoje.[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Vá agora[e]
[s]Verifique o vínculo com Chihaya[e]
[s]Decidir depois[e]

[sel SEL_002 top]
[s][f 5 14]Nós estamos lá.[e]

[msg MND_COOP_DOUZOKUSEI]
[s]Sinto que posso me aproximar mais de[n]Chihaya graças a Persona[n][var 2] [clr 1][var 5][clr 27]...[n][w][e]

[msg MSG_SPOT_OPEN_ODAIBA]
[s]Você desbloqueou o acesso a um[n]novo local: [clr 1]Odaiba[clr 27].[n][w][e]

