[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]Ei, sobre aquele panfleto.[n]Estamos fazendo isso à noite, certo?[n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]Normalmente estou em Shibuya nessas horas.[n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]Avise-me quando você estiver indo para[n]isso.[n][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][f 5 14]É melhor você não me deixar para trás, ok?[n][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][f 5 14]Eu nunca vou te perdoar se você o fizer.[n][w][e]

[msg MSG_005_0_0 [Mishima]]
[s][f 5 14][f 5 15]Entrarei em contato com você novamente[n]mais tarde esta noite.[n][w][e]

