[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Ei, [f 4 2].[n]Você tem algum tempo hoje?[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Eu gostaria que você viesse comigo um[n]pouco...[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Estarei esperando no shopping underground.[n][w][e]

[msg CHAT_NOREACTION_MSG [Makoto]]
[s][f 5 14]Eu te peguei em um momento ruim?[n]Eu esperei o dia todo também... bem, vou[n]convidá-lo novamente mais tarde.[n][w][e]

[msg CHAT_REACTION_MSG [Ann]]
[s][f 5 14]Obrigado. Você se importaria de vir para[n]onde eu estou?[n][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Bem, você quer aceitar o convite de Lady[n]Ann?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Acesse imediatamente [e]
[s]Verifique o vínculo com Ann [e]
[s]Responda mais tarde [e]

[sel SEL_002 top]
[s][f 5 14]Eu estarei certo.[e]

[msg MND_COOP_DOUZOKUSEI]
[s]Eu deveria ser capaz de aprofundar nosso[n]vínculo, já que tenho [n][clr 1][var 5][clr 27][n]do [var 2]Arcana...[n][w][e]

