[msg MSG_000_0_0 [Akechi]]
[s][f 5 14]Parece que Sae-san está participando de[n]um julgamento amanhã.[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]Estou surpreso que ela esteja[n]participando do tribunal em um momento[n]como este...[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]Ela deve estar ocupada com a investigação[n]Phantom Thieves também...[n][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][f 5 14]Ela é uma promotora pública, afinal.[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Isso tem que ser difícil...[n][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][f 5 14]Ela pode ser nossa inimiga, mas eu[n]simpatizo com ela nesse sentido.[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Nosso inimigo...[n][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][f 5 14]Oh, minhas desculpas. Não é isso que eu[n]quis dizer.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]Tudo bem. Você estava apenas dizendo a[n]verdade.[n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]De qualquer forma, precisaremos agir[n]amanhã, certo? Obrigado por nos informar.[n][w][e]

[msg MSG_010_0_0 [Akechi]]
[s][f 5 14]Você é muito bem-vindo.[n][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][f 5 14][f 5 15]De qualquer forma, vamos nos encontrar no[n]local depois da escola amanhã.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Nós realmente não podemos falhar desta[n]vez. Vamos fazer isso com cuidado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Depois de irmos ao tribunal amanhã,[n]devemos ir direto para o palácio.[n][f 1 3 65535][w][e]

