[msg MSG_000_0_0 [Ann]]
[s][f 5 14]É domingo... onde nos encontramos para[n]entrar no Palácio?[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]No telhado deve ficar bom.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Não vai ser bloqueado?[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Não, isso não será um problema.[n]Está sempre aberto.[n][w][e]

[msg MSG_005_0_0 [Ann]]
[s][f 5 14]Hum, tudo bem.[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]De qualquer forma, o plano de hoje?[n][w][e]

[sel SEL_007_0_0 top]
[s][f 5 14]Eu vou.[e]
[s]Ainda estou pensando nisso.[e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14][f 5 15]Deixe-nos saber quando[n]você decidiu![n][w][e]

