[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Você encontrou alguma pista?[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Eu tenho um nome.[e]
[s]Vou te dizer amanhã.[e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Você fez isso![n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]Considerando como você está tentando nos[n]manter em suspense, espero que sejam[n]boas notícias.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Bem, então, vamos nos encontrar no[n]esconderijo amanhã![n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]Entendido.[n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]Ryuji parece estar ausente dessa[n]conversa. Devemos entrar em contato com[n]ele separadamente?[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14][f 5 15]Tenho certeza de que ele descobrirá[n]quando verificar seu telefone mais tarde.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 8 0 0]Já estamos praticamente no palácio de[n]Kaneshiro![n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 9 0 0]Isso foi surpreendentemente fácil![n][f 1 3 65535][w][e]

