[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Amanhã tem fogo de artifício de fogos de[n]artifício! Vamos nos encontrar em[n]Shibuya às 17h![n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Oi Makoto. Você vai usar[n]a yukata?[n][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][f 5 14]Essa é a minha intenção.[n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]Os Yukata desempenham um papel crucial na[n]tradição do verão... Eles realmente[n]realçam a beleza feminina.[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Acho que vou usar o meu também.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Você tem um...?[n]E você, [f 4 2]?[n][w][e]

[sel SEL_006_0_0 top]
[s][f 5 14]Eu não tenho um yukata.[e]
[s]Eu irei com minhas roupas de sempre.[e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Ei, existem! Por que você não vem sem[n]óculos?[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]E qual é o ponto?[n][w][e]

[msg MSG_009_0_0 [Ann]]
[s][f 5 14]Bem, não é todo dia que você consegue ver[n]os incêndios, seria triste estar com[n]suas roupas habituais![n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Eu pensei que uma mudança[n]lá seria bom.[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14]É uma excelente ideia! Você deveria[n]só vir sem óculos![n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Bem, não se atrase amanhã![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1067 65535 0]Fogos de artifício e yukatas dão[n]realmente uma sensação de verão...[n]Até Lady Ann usará um.[n][f 1 3 65535][w][e]

