[msg MSG_032_0_0 [Mishima]]
[s][f 5 14]Ei! Você fez isso! Você tem aquela dona[n]de casa reclamante![n][w][e]
[s][f 5 14]Ela não apenas parou de fazer[n]reclamações, mas também está por aí se[n]desculpando.[n][w][e]
[s][f 5 14]Ela está dizendo que estava errado para[n]ela pensar que era tão importante apenas[n]porque pagou por coisas.[n][w][e]
[s][f 5 14]A partir de agora, ela tentará se lembrar[n]de agradecer quando estiver fazendo[n]compras.[n][w][e]
[s][f 5 14]... Mas se a loja realmente faz algo[n]errado, você deve reclamar, certo?[n][w][e]
[s][f 5 14]Mesmo isso parece demais para mim. Você[n]sente que é difícil reclamar, mesmo que[n]seja justificado?[n][w][e]

[sel SEL_033_0_0 top]
[s][f 5 14]É fácil.[e]
[s]Não sou bom nisso.[e]
[s]É caso a caso.[e]

[msg MSG_034_0_0 [Mishima]]
[s][f 5 14]Uau, você tem coragem.[n][w][e]

[msg MSG_035_0_0 [Mishima]]
[s][f 5 14]Sei exatamente o que você quer dizer.[n][w][e]

[msg MSG_036_0_0 [Mishima]]
[s][f 5 14]Como se isso dependa de com quem você[n]está lidando? Entendi.[n][w][e]

[msg MSG_037_0_0 [Mishima]]
[s][f 5 14][f 5 15]De qualquer forma, esse é outro caso[n]fechado![n][w][e]

[msg MSG_038_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Aquele reclamante não foi nada para nós![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Talvez eu deva registrar uma reclamação[n]com o proprietário da Memento por[n]desperdiçar nosso tempo.[n][f 1 3 65535][w][e]

[msg MND_quest05_CLEAR_SELF]
[s][vp 8 2 65535 0 0 0]Parece que mudamos com sucesso o coração[n]do alvo.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Scriptchat_222 dummy [e]

