[msg MSG_000_0_0 [Kawakami]]
[s][f 5 14]Terminei meu trabalho na escola.[n][w][e]

[msg MSG_001_0_0 [Kawakami]]
[s][f 5 14]Podemos passar a véspera de Natal juntos,[n]se você quiser?[n]Sem pressão, embora...[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Vamos fazê-lo.[e]

[msg MSG_020_0_0 [Kawakami]]
[s][f 5 14]Sério!? Estou super a bordo.[n][w][e]

[msg MSG_021_0_0 [Kawakami]]
[s][f 5 14]Agora estou todo animado! Vou ir para a[n]cidade daqui a pouco.[n][f 5 15][w][e]

