[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Droga, motocicletas são legais...[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Eu gostaria que minha personalidade fosse[n]assim.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]O seu está em um navio.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Cara, você está brincando!? As[n]motocicletas são muito mais frias que os[n]barcos burros![n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Será como a música! "Eu sou um fantasma,[n]em um cavalo de aço que eu ando..." [n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]Não diga essas coisas. E para o registro,[n]certamente não sou "procurado".[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Honestamente, estou apenas surpreso que[n]você saiba como andar de motocicleta,[n]Niijima-senpai.[n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]Você tem uma licença?[n][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][f 5 14]Um regular, sim.[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14]Nicee... mal posso esperar para colocar[n]minhas mãos em um também.[n][w][e]

[msg MSG_016_0_0 [Makoto]]
[s][f 5 14]Além disso, lembre-se se eu mudar o[n]tópico por um momento?[n][w][e]

[msg MSG_017_0_0 [Yusuke]]
[s][f 5 14]Qual é o problema?[n][w][e]

[msg MSG_018_0_0 [Makoto]]
[s][f 5 14]Sinto muito, a todos.[n][w][e]

[msg MSG_019_0_0 [Makoto]]
[s][f 5 14]Eu sei que não estou em posição de dizer[n]isso. Eu realmente faço...[n][w][e]

[msg MSG_020_0_0 [Makoto]]
[s][f 5 14]No entanto, devo me desculpar.[n][w][e]

[msg MSG_021_0_0 [Makoto]]
[s][f 5 14]Foram minhas ações que arrastaram todos[n]vocês para essa bagunça.[n][w][e]

[msg MSG_022_0_0 [Makoto]]
[s][f 5 14]Além disso, entendi mal suas verdadeiras[n]intenções nisso.[n][w][e]

[msg MSG_023_0_0 [Makoto]]
[s][f 5 14]Se eu pudesse ter percebido o que estava[n]acontecendo com Suzui-san também...[n][w][e]

[msg MSG_024_0_0 [Ann]]
[s][f 5 14]Vamos lá, não precisamos falar sobre isso[n]agora.[n][w][e]

[msg MSG_025_0_0 [Yusuke]]
[s][f 5 14]Parece que ainda há problemas[n]remanescentes na mente de todos.[n][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][f 5 14]Agora não é hora de falar sobre essa[n]merda![n][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][f 5 14]Não temos que fazer algo sobre Kaneshiro?[n][w][e]

[msg MSG_028_0_0 [Ann]]
[s][f 5 14]Ele tem razão.[n][w][e]

[msg MSG_029_0_0 [Makoto]]
[s][f 5 14]Muito bem, eu entendo.[n][w][e]

[msg MSG_030_0_0 [Makoto]]
[s][f 5 14][f 5 15]De qualquer forma, farei o meu melhor[n]para ter certeza de não desacelerar[n]todos vocês.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 10 0 0]Bem, estávamos em desacordo até apenas um[n]tempo atrás...[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 11 0 0]Mas Ryuji está totalmente certo.[n]Precisamos trabalhar juntos para superar[n]isso![n][f 1 3 65535][w][e]

