[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Alibaba enviou uma mensagem para você?[n][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]*suspiro* é apenas ryuji.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Nenhuma coisa?[n][w][e]

[msg MSG_003_5_0 [Ryuji]]
[s][f 5 14][f 5 15]Deixe-nos saber o mais rápido possível se[n]ele tentar entrar em contato com você,[n]Mkay?[n][w][e]

