[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Se essa foto se espalhar,[n]acaba muito mal...[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Por que você está dizendo isso agora?[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Não sei. Quer dizer, não é que[n]fizemos nada[n]errado.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Estávamos no lugar errado[n]na hora errada.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Bem, sim. Esse é o problema.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Você acha que as pessoas não entenderiam[n]mesmo se tentássemos explicar[n]o que aconteceu?[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Hmmm...[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Seria muito difícil.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]Concordo.[n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]Acho que ninguém estaria disposto a ouvir[n]o que temos a dizer.[n][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][f 5 14]Se essa foto for divulgada,[n]as pessoas não levarão[n]a sério nada do que dissermos.[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]Mas se tivesse, seria[n]sério...[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14][f 5 15]A gente tem que despertar o coração dele[n]e pronto, bom...[n][w][e]

