[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Ei, o que você acha que devemos fazer[n]sobre a viagem para a praia?[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Você acha que ele[n]poderá participar tão cedo?[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Bem, ele realmente começou a falar muito[n]mais.[n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Ele fez muitos progressos,[n]se considerarmos em que estado[n]ele estava no começo.[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]O que você diz, Futaba? Você acha que[n]poderia fazer isso, talvez amanhã?[n][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][f 5 14]Amanhã!?![n][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][f 5 14]É muito cedo.[n][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][f 5 14]Eu quero preparar.[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]Faça o seu melhor.[e]
[s]Não se esforce demais.[e]
[s]Quando isso seria adequado para você?[e]

[msg MSG_009_0_0 [Futaba]]
[s][f 5 14]Mmm...[n][w][e]

[msg MSG_010_0_0 [Futaba]]
[s][f 5 14]Acho que consigo,[n]se você me der um pouco mais de tempo.[n][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][f 5 14]Eu devo estar bem depois de amanhã.[n][w][e]

[msg MSG_012_0_0 [Futaba]]
[s][f 5 14]pelo menos eu acho...[n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]Então iremos[n]depois de amanhã![n][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][f 5 14]Mas se você não quiser, avise-nos, Futaba.[n]OK?[n][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][f 5 14][f 5 15]Tudo está bem. Eu posso fazer isso.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 40 0 0]Agora finalmente sabemos[n]quando terminaremos. A praia[n]está ao virar da esquina![n][f 1 3 65535][w][e]

