[msg MSG_000_0_0 [Haru]]
[s][f 5 14]Posso incomodá-lo por um momento?[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]Agora que o funeral acabou, parece que um[n]pequeno fardo foi retirado dos meus[n]ombros.[n][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Isso deve ser difícil...[e]
[s]Você está bem?[e]

[msg MSG_003_0_0 [Haru]]
[s][f 5 14]É... mas estou bem.[n][w][e]

[msg MSG_004_0_0 [Haru]]
[s][f 5 14]Eu sou.[n][w][e]

[msg MSG_005_0_0 [Haru]]
[s][f 5 14]Eu prometo a você, estou bem.[n][w][e]

[msg MSG_006_0_0 [Haru]]
[s][f 5 14]Na verdade, eu me sinto mal, fazendo com[n]que todos se preocupem comigo...[n][w][e]

[msg MSG_007_0_0 [Haru]]
[s][f 5 14]E quanto a você? Você está bem?[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]Estou gerenciando.[e]
[s]Isso é horrível.[e]

[msg MSG_009_0_0 [Haru]]
[s][f 5 14]Você com certeza é forte.[n][w][e]

[msg MSG_010_0_0 [Haru]]
[s][f 5 14]Mantenha-se firme.[n][w][e]

[msg MSG_011_0_0 [Haru]]
[s][f 5 14]Voltarei, não se preocupe.[n][w][e]

[msg MSG_012_0_0 [Haru]]
[s][f 5 14]Acho que vou conseguir me juntar a todos[n]quando os exames terminarem.[n][w][e]

[msg MSG_013_0_0 [Haru]]
[s][f 5 14]Umm...[n][w][e]
[s][f 5 14][f 5 15]Bem, vejo você.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 56 0 0]Haru...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 57 0 0]Ela é quem deveria estar com dor agora,[n]mas ainda está tentando nos animar...[n][f 1 3 65535][w][e]

