[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Ei, você vê o artigo?[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Não.[e]
[s]Que tipo de artigo?[e]
[s]É sobre nós?[e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]É uma entrevista com um garoto da escola.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Na verdade, não. É principalmente uma[n]entrevista com um garoto shujin.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]"Boy M diz a todos: abuso desenfreado no[n]caso Kamoshida!" [n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Isso é o que dizia. É principalmente[n]sobre o castigo físico.[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]Você acha que esse garoto m é mishima?[n][w][e]

[sel SEL_013_0_0 top]
[s][f 5 14]Não sei.[e]
[s]Pode ser Makoto.[e]
[s]Provavelmente.[e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14]Hm, talvez eu esteja apenas imaginando[n]coisas...[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14]Mas quem mais tem um nome M e estava[n]sendo abusado por Kamoshida?[n][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][f 5 14]Oh, Makoto é um M também...[n]Então é a senhorita presidente, hein?[n][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][f 5 14]Espere, diz "garoto"![n]Tem que ser um cara![n][w][e]

[msg MSG_019_0_0 [Ryuji]]
[s][f 5 14]Além disso, o presidente da Srta. Nunca[n]concordaria com uma entrevista de[n]tablóides.[n][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 5 14]... Acho que pode ser ele, afinal.[n][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][f 5 14]Quero dizer que a coisa do site phan[n]também tem sido uma grande ajuda...[n][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][f 5 14]É prolicamente bom deixá-lo.[n]Ele não está nos fazendo nenhum mal.[n][w][e]

[msg MSG_025_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Te vejo mais tarde.[n][w][e]

[msg MSG_026_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Esse artigo... Você acha que o repórter[n]que conhecemos na Crossroads poderia ter[n]escrito?[n][f 1 3 65535][w][e]

[msg MSG_026_5_0]
[s][vp 1 0 0 0 0 0]Eu deveria verificar o artigo que Ryuji[n]mencionou...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Assim como eu pensei. O autor está[n]listado como Ichiko Ohya.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 3 0 0]...Eu vejo. Este artigo pode acabar sendo[n]útil para nós.[n][f 1 3 65535][w][e]

[sel SEL_028_0_0 top]
[s]Verdadeiro.[e]
[s]Como assim?[e]

[msg MSG_029_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 4 0 0]Se o governante do palácio vê e sua[n]cognição dos ladrões fantasmas muda...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 5 0 0]Ei, [f 4 2]. Estaríamos perdendo se não usássemos[n]isso para nossa vantagem.[n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 6 0 0]Se a tivermos nos pintando sob uma luz[n]positiva, a opinião pública de nós[n]mudará para melhor![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 7 0 0]Você deve tentar fazer com que ela[n]escreva mais alguns artigos sobre os[n]ladrões Phantom![n][f 1 3 65535][w][e]

