[msg MSG_000_0_0 [Takemi]]
[s][f 5 14]Quero ver você...[n][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][f 5 14]Na verdade, há uma coisa[n]que eu acho que tenho que te dizer…[n][w][e]

[msg MSG_002_0_0 [Takemi]]
[s][f 5 14]...mas não consigo decidir.[n][w][e]

[msg MSG_003_0_0 [Takemi]]
[s][f 5 14]...Desculpe, deixa pra lá.[n]Esqueça isso.[n][f 5 15][w][e]

[msg CHAT_REACTION_MSG_01 [Takemi]]
[s][f 5 14]Ah... OK.[n][f 5 15][w][e]

[sel SEL_001 top]
[s]Vá até ela imediatamente[e]
[s]Decidir depois[e]

[sel SEL_002 top]
[s][f 5 14]Eu estarei lá.[e]

[msg MSG_CORP_PLAY_CHECK1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]O que há de errado com Takemi?[n]Você quer passar na clínica?[n][f 1 3 65535][w][e]

[msg MSG_CORP_PLAY_CHECK2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ninguém pensa que você está vivo.[n]Se você tomar cuidado,[n]tudo deve ficar bem.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]O que há de errado com Takemi?[n]Você quer passar na clínica?[n][f 1 3 65535][w][e]

[msg ERROR_MSG_000_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, estou abrindo uma loja.[n]Você se importaria de parar[n]de jogar no seu telefone?[n][w][e]

[msg ERROR_MSG_001_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]O chefe ficou bravo com você... Talvez[n]você devesse responder mais tarde.[n][w][e]

[msg MND_CHAT_INVITE_STOP]
[s]estou comendo. Talvez eu deva[n]responder mais tarde...[n][w][e]

[msg MND_COOP_RANK_UP_OK]
[s]Sinto que em breve meu vínculo[n]com [var 7] se fortalecerá...[n][w][e]

[msg MND_COOP_RANK_UP_ROCK]
[s]Sinto que em breve meu vínculo[n]com [var 7] se fortalecerá, mas...[n][w][e]

[msg MND_COOP_RANKUP_2]
[s]Pode ser uma boa oportunidade para[n]reforçar meu vínculo com [var 7]...[n][w][e]

[msg MND_COOP_DOUZOKUSEI_HAVE]
[s]Sinto que posso me aproximar mais de[n][var 7] graças a Persona[n][var 2] [clr 1][var 5][clr 27]...[n][w][e]

[msg MSG_SPOT_OPEN_KANDA]
[s]Agora você pode ir para [clr 2]Kanda[n][clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_SHINJUKU]
[s]Agora você pode ir para [n][clr 2]Shinjuku[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_AKIHABARA]
[s]Agora você pode ir para [n][clr 2]Akihabara[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_INOKASHIRA]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Inokashira Park[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_OGIKUBO]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Ogikubo Ramen[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que gosta de ramen,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_ODAIBA]
[s]Você descobriu um novo[n]ponto de encontro:[n][clr 2]Odaiba's Seaside Park[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]gosta de parques aquáticos,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_UENO]
[s]Você descobriu um novo[n]ponto de encontro:[n][clr 2]Museu Ueno[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]pode gostar de arte,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_TSUKISHIMA]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Tsukishima Monja[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]gosta de comer monjayaki,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_HARAJUKU]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Harajuku Takenoko[clr 27].[n][w][e]
[s]Se você conhece alguém que gosta da Rua[n]Takenoko, tente[n]convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_TYUKAGAI]
[s]Você descobriu um novo[n]ponto de encontro:[n][clr 2]Chinatown de Motomachi[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_MAIHAMA]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Maihama's Destinyland[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Asakusa[clr 27].[n][w][e]
[s]Se você conhece alguém que gosta de[n]Skytree ou Nakamise Street, tente[n]convidá-los aqui.[n][w][e]

[msg MSG_SPOT_OPEN_IKEBUKURO]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Ikebukuro Planetarium[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_MEIJIJINGU]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Santuário Meiji[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]
[s]Se você quiser, também pode[n]ir lá sozinho para[n]orar no santuário.[n][w][e]

[msg MSG_SPOT_OPEN_SUIDOUBASH]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Dome Town of Suidobashi[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_SHIBUYA]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Wilton Hotel em Shibuya[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_GINZA]
[s]Você descobriu um novo[n]ponto de encontro:[n][clr 2]Sushi Bar em Ginza[clr 27].[n][w][e]
[s]Se você conhece alguém que gosta de[n]comer sushi caro,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_JINBOCHO]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Jinbocho's Book Town[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]
[s]Se você quiser, também pode[n]ir lá sozinho para fazer[n]algumas compras.[n][w][e]

[msg MSG_SPOT_OPEN_ICHIGAYA]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Lago Ichigaya[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]gosta de pescar, tente[n]convidá-lo aqui.[n][w][e]
[s]Além disso, se você quiser, pode ir lá[n]sozinho e experimentar alguns peixes.[n][w][e]

[msg MSG_SPOT_OPEN_SHINAGAWA]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Shinagawa Aquarium[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que pode gostar do aquário,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_NAKANO]
[s]Você descobriu um novo[n]ponto de encontro:[n][clr 2]Área do Complexo Comercial, Nakano[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

