[msg MSG_000_0_0 [Maruki]]
[s][f 5 14]Estou quase terminando meu artigo.[n][w][e]

[msg MSG_001_0_0 [Maruki]]
[s][f 5 14]Eu queria ouvir sua opinião antes de[n]terminar, finalmente.[n][w][e]
[s][f 5 14]Você acha que pode passar[n]para a enfermaria?[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que Maruki está esperando por você na[n]enfermaria. Você quer ir até ele?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Vá agora[e]
[s]Decidir depois[e]

[sel SEL_002 top]
[s][f 5 14]Nós estamos lá.[e]

[msg MSG_REACTION [Maruki]]
[s][f 5 14]Desculpe... Eu sei que é um pouco[n]súbito. Aguardo você.[n][f 5 15][w][e]

[msg MSG_CORP_PLAY_CHECK1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que Maruki está esperando por você na[n]enfermaria. Você quer ir até ele?[n][f 1 3 65535][w][e]

[msg MSG_CORP_PLAY_CHECK2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ninguém pensa que você está vivo.[n]Se você tomar cuidado,[n]tudo deve ficar bem.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Parece que Maruki está esperando por você na[n]enfermaria. Você quer ir até ele?[n][f 1 3 65535][w][e]

