[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]Eu vi a conferência![n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]Mas algo não está certo. É como se[n]ninguém estivesse reagindo a isso...[n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]Também não houve nenhum tipo de movimento[n]no fórum.[n][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][f 5 14]Até as pessoas na TV estão apenas falando[n]sobre a eleição...[n]Nada sobre os ladrões fantasmas.[n][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][f 5 14]Isso não é meio estranho?[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]Me incomoda.[e]
[s]Você pensa?[e]

[msg MSG_006_0_0 [Mishima]]
[s][f 5 14]Sim. Não faz sentido, certo?[n][w][e]

[msg MSG_007_0_0 [Mishima]]
[s][f 5 14]O apoio aos ladrões Phantom nem aumentou[n]depois que eles fizeram seu anúncio...[n][w][e]

[msg MSG_008_0_0 [Mishima]]
[s][f 5 14]Sim. Não faz sentido![n][w][e]

[msg MSG_009_0_0 [Mishima]]
[s][f 5 14]O apoio aos ladrões Phantom nem aumentou[n]depois que eles fizeram seu anúncio...[n][w][e]

[msg MSG_010_0_0 [Mishima]]
[s][f 5 14]De qualquer forma, talvez eu tente mudar[n]a pergunta da pesquisa.[n][w][e]

[msg MSG_011_0_0 [Mishima]]
[s][f 5 14]Seria estranho perguntar às pessoas se[n]elas apoiam os ladrões Phantom agora que[n]tanto mudou.[n][w][e]

[msg MSG_012_0_0 [Mishima]]
[s][f 5 14][f 5 15]Tudo bem, vou descobrir o que as pessoas[n]realmente pensam! Apenas espere![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 20 0 0]... Eu realmente não entendo. O que ele[n]vai perguntar?[n][f 1 3 65535][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 21 0 0]Bem, vamos deixar as coisas de[n]popularidade para Mishima por enquanto.[n][f 1 3 65535][w][e]

