[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Recebi uma atualização sobre a senhora do[n]gato. Parece que ela fez um post no local do[n]Phan.[n][w][e]
[s][f 5 14]Eu acho que ela se entregou à polícia.[n][w][e]
[s][f 5 14]Depois de pagar por seus crimes, ela fará[n]um trabalho voluntário para ajudar os[n]gatos perdidos.[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Bom para ela.[e]
[s]Espero que as coisas corram bem.[e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Concordo.[n][w][e]
[s][f 5 14]Eu acho que ela realmente queria[n]protegê-los.[n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Ela realmente os amava... com tanta força[n]que dominou seu melhor julgamento.[n][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Eu vejo... então Aino começou a pensar[n]positivamente.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ela provavelmente não se lembra de mim,[n]mas talvez eu a visite no futuro.[n][f 1 3 65535][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]... Eu fiz uma promessa, afinal.[n][f 1 3 65535][w][e]

