[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Quantos dias nos restam?[n]Não estamos chegando[n]muito perto?[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]É difícil se concentrar sabendo[n]o que está por vir...[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Já. Essas lições entram por um ouvido e[n]saem pelo outro.[n][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][f 5 14]Então, Ryuji, nada[n]muda para você.[n][w][e]

[msg MSG_004_0_0 [Haru]]
[s][f 5 14]Terei prazer em ajudá-lo a estudar, se[n]quiser. Afinal estou no terceiro ano.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Eu gostaria de poder dizer não, mas estou[n]na merda mais profunda ...[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Sim, eu diria que depois da missão[n]será viável...[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Direita. Dividir nossa[n]atenção entre dois problemas[n]não nos ajuda psicologicamente.[n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Restam apenas dez dias.[n]Pode ser nosso[n]momento mais crítico.[n][w][e]

