[msg MSG_000_0_0 [Akechi]]
[s][f 5 14]Lembra do pedido que fizemos nos[n]Mementos?[n][w][e]

[msg MSG_001_0_0 [Akechi]]
[s][f 5 14]Sabemos qual é o nosso[n]alvo, certo?[n][w][e]

[msg MSG_002_0_0 [Akechi]]
[s][f 5 14]E não sabemos quando encontraremos outro[n]grande objetivo.[n][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][f 5 14]Melhor lidar com isso[n]o mais rápido possível.[n][f 5 15][w][e]

[msg MSG_REACTION [Akechi]]
[s][f 5 14]OK. Eu irei imediatamente para a reunião.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Sim, ainda não atendemos[n]o pedido de Mishima.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Se formos ao Mementos,[n]você quer que todos venham[n]ao esconderijo?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir para o ponto de encontro[e]
[s]Decidir depois[e]

[sel SEL_002 top]
[s][f 5 14]Vamos todos nos encontrar.[e]

