[msg MSG_000_0_0 [Haru]]
[s][f 5 14]Isso não é muita atualização...[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]Mas acho que vou voltar para a escola, a[n]partir de amanhã.[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]Sinto muito por me preocupar com todos[n]vocês até agora.[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Você está realmente bem?[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Certifique-se de não se esforçar demais[n]neste momento de tristeza.[n][w][e]

[msg MSG_005_0_0 [Haru]]
[s][f 5 14]Não, eu realmente preciso me esforçar.[n]Minha mente sempre vagueia se eu não[n]tenho nada para fazer...[n][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][f 5 14]Sim, eu te entendo totalmente.[n][w][e]

[msg MSG_007_0_0 [Haru]]
[s][f 5 14]Além disso... não há nada que eu possa[n]fazer enquanto estou em casa.[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]Bem, uh... não sei como dizer, mas tente[n]não pensar muito nessas coisas.[n][w][e]

[sel SEL_009_0_0 top]
[s][f 5 14]Conte conosco a qualquer momento.[e]
[s]Estamos do seu lado, Haru.[e]

[msg MSG_0010_0_0 [Ann]]
[s][f 5 14]Sim, você não precisa se preocupar em nos[n]pedir nada![n]Estamos todos aqui para você![n][w][e]

[msg MSG_010_0_1 [Ann]]
[s][f 5 14]Sim, você pode vir até nós para qualquer[n]coisa![n][w][e]

[msg MSG_011_0_0 [Haru]]
[s][f 5 14]Hum... para ser completamente honesto...[n][w][e]

[msg MSG_012_0_0 [Haru]]
[s][f 5 14]Quando acabei sozinho... duvidei de todos[n]vocês um pouco.[n][w][e]

[msg MSG_014_0_0 [Haru]]
[s][f 5 14]Mas é tão horrível para mim duvidar de[n]você. Quero dizer, sou eu quem pediu a[n]todos para fazer isso.[n][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][f 5 14]Seu pai acabou de falecer, Haru. É[n]natural sentir uma enxurrada de emoção[n]nesses eventos.[n][w][e]

[msg MSG_016_0_0 [Futaba]]
[s][f 5 14]Sim, é muito difícil quando você perde[n]alguém assim...[n][w][e]

[msg MSG_017_0_0 [Haru]]
[s][f 5 14]Mas estou bem agora. Vocês todos me[n]ajudaram muito.[n][w][e]

[msg MSG_018_0_0 [Futaba]]
[s][f 5 14]De volta para você![n][w][e]

[msg MSG_019_0_0 [Haru]]
[s][f 5 14]Obrigada. Essas palavras são realmente[n]tranquilizadoras.[n][w][e]

[msg MSG_020_0_0 [Haru]]
[s][f 5 14][f 5 15]Bem, então, vou ver todos vocês na escola.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Haru... não estou surpreso que ela pareça[n]baixa. Você deve mantê-la em seus[n]pensamentos, [n][f 4 2].[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Ainda assim, apesar da aparência, Haru[n]tem a espinha dorsal. Tenho certeza que[n]ela vai ficar bem.[n][f 1 3 65535][w][e]

