[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Kaneshiro se livrou dessas fotos, certo?[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Isso foi o que ele disse.[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Você acha que podemos confiar nele?[n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Duvido que ele mentisse se ele realmente[n]tivesse uma mudança de coração.[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Parece que estamos todos claros então.[n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]Ainda não podemos ter certeza disso.[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Você quer dizer que ele pode não ter[n]mudado de coração?[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Não, tenho relativamente certeza de que[n]ele fez. Esse não é o problema.[n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14]Apesar da mudança de Kaneshiro, sua[n]organização permanece intacta.[n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Só espero que eles não funcionem com as[n]fotografias.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Você é como, fugir com isso?[n]Eu acho que isso é possível...[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]Afinal, a perda do líder não explica[n]necessariamente o desaparecimento do[n]grupo.[n][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][f 5 14]Isso é meramente conhecimento comum.[n][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][f 5 14]Mas o oposto às vezes também é verdadeiro.[n][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][f 5 14]Alguns grupos que não têm uma mão[n]orientadora forte simplesmente[n]desmoronam.[n][w][e]

[msg MSG_015_0_0 [Ann]]
[s][f 5 14]Então tudo isso depende de qual lado ele[n]vai...[n][w][e]

[sel SEL_016_0_0 top]
[s][f 5 14]Nós ficaremos bem.[e]
[s]Estou preocupado...[e]

[msg MSG_017_0_0 [Makoto]]
[s][f 5 14]Tudo o que podemos fazer agora é orar que[n]as peças caam a nosso favor.[n][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][f 5 14]Esperançosamente, a confissão de[n]Kaneshiro motiva a polícia a reprimir a[n]máfia...[n][w][e]

[msg MSG_019_0_0 [Yusuke]]
[s][f 5 14]Eu adoraria nada além de vê-los[n]derrotados de uma vez por todas.[n][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 5 14]Essa parte vai chegar à irmã de Makoto.[n][w][e]

[msg MSG_021_0_0 [Makoto]]
[s][f 5 14]Além disso, fizemos tudo o que podemos[n]por enquanto.[n][w][e]

[msg MSG_022_0_0 [Makoto]]
[s][f 5 14][f 5 15]Tudo o que resta agora é esperar até que[n]o resultado fique claro.[n][w][e]

