[msg MSG_000_0_0 [Haru]]
[s][f 5 14]Posso incomodá-lo por um momento?[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]Agora que o funeral passou,[n]parece que um pequeno peso foi[n]tirado dos meus ombros.[n][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Deve ser duro...[e]
[s]Você está bem?[e]

[msg MSG_003_0_0 [Haru]]
[s][f 5 14]Isso mesmo... mas estou bem.[n][w][e]

[msg MSG_004_0_0 [Haru]]
[s][f 5 14]Sim.[n][w][e]

[msg MSG_005_0_0 [Haru]]
[s][f 5 14]Estou bem, juro.[n][w][e]

[msg MSG_006_0_0 [Haru]]
[s][f 5 14]Na verdade, me deixa doente[n]saber que todo mundo[n]preocupado comigo...[n][w][e]

[msg MSG_007_0_0 [Haru]]
[s][f 5 14]Como vai? Tudo está bem?[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]Eu passo.[e]
[s]É horrível.[e]

[msg MSG_009_0_0 [Haru]]
[s][f 5 14]Claro que você é forte.[n][w][e]

[msg MSG_010_0_0 [Haru]]
[s][f 5 14]Aguentar.[n][w][e]

[msg MSG_011_0_0 [Haru]]
[s][f 5 14]Eu voltarei, não se preocupe.[n][w][e]

[msg MSG_012_0_0 [Haru]]
[s][f 5 14]Acho que poderei[n]ver todos novamente depois que[n]os exames terminarem.[n][w][e]

[msg MSG_013_0_0 [Haru]]
[s][f 5 14]Mmm...[n][w][e]
[s][f 5 14][f 5 15]Bem, vejo você.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 56 0 0]Haru...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 57 0 0]Ela é quem deveria[n]sentir o pior, mas[n]ela está se esforçando para nos animar...[n][f 1 3 65535][w][e]

