[msg MSG_000_0_0 [Kasumi]]
[s][f 5 14]Será emocionante descobrir[n]como isso vai acontecer.[n][w][e]

[msg MSG_000_1_0 [Kasumi]]
[s][f 5 14]Será emocionante descobrir[n]como isso vai acontecer.[n][w][e]

[msg MSG_000_2_0 [Kasumi]]
[s][f 5 14]Será emocionante descobrir[n]como isso vai acontecer.[n][w][e]

[msg MSG_000_3_0 [Kasumi]]
[s][f 5 14]Será emocionante descobrir[n]como isso vai acontecer.[n][w][e]

[msg MSG_000_4_0 [Kasumi]]
[s][f 5 14]Será emocionante descobrir[n]como isso vai acontecer.[n][w][e]

[msg MSG_000_5_0 [Kasumi]]
[s][f 5 14]Será emocionante descobrir[n]como isso vai acontecer.[n][w][e]

[msg MSG_000_6_0 [Kasumi]]
[s][f 5 14]Será emocionante descobrir[n]como isso vai acontecer.[n][w][e]

[msg MSG_000_7_0 [Kasumi]]
[s][f 5 14]Será emocionante descobrir[n]como isso vai acontecer.[n][w][e]

[msg MSG_001_0_0 [Kasumi]]
[s][f 5 14]O que você está fazendo?[n][w][e]

[msg MSG_002_0_0 [Kasumi]]
[s][f 5 14]Se você não tem compromissos, gostaria de[n]vir para Kichijoji?[n][f 5 15][w][e]

[msg MSG_REACTION [Kasumi]]
[s][f 5 14]Aguardo você.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]O que você quer fazer? Você quer ir[n]para Yoshizawa?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Vá agora[e]
[s]Recusar[e]

[sel SEL_002 top]
[s][f 5 14]Eu estarei lá.[e]

