[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Eu simplesmente não consigo me acalmar...[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Na verdade, você já almoçou?[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Desde que temos o dia de folga, por que[n]não nos reunimos e saímos para comer?[n][w][e]

[msg MSG_100_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]É um convite de Lady Ann![n]Você está indo, certo?[n][f 1 3 65535][w][e]

[sel SEL_111_0_0 top]
[s]Comprometer-se [e]
[s]Declínio [e]
[s]Responda mais tarde [e]

[sel SEL_111_1_0 top]
[s]Acesse imediatamente [e]
[s]Declínio [e]
[s]Responda mais tarde [e]

[sel SEL_200_0_0 top]
[s][f 5 14]OK, vamos lá.[e]
[s]Amanhã não é o melhor dia.[e]

[msg MSG_201_0_0 [Ann]]
[s][f 5 14]OK.[n]Você está bem em ir ao restaurante, certo?[n][w][e]

[msg MSG_202_0_0 [Ann]]
[s][f 5 14]Vamos nos encontrar em Shibuya.[n]Vou deixar Ryuji saber.[n][w][e]

[msg MSG_210_0_0 [Ann]]
[s][f 5 14]Sim...[n]Desculpe por convidá-lo de repente.[n][w][e]

[msg MSG_400_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Estou com muita fome também.[n]Naturalmente, eu estarei entrando.[n][f 1 3 65535][w][e]

[msg MSG_401_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]O que!? Você está recusando-a?[n][f 1 3 65535][w][e]

[msg MSG_402_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Você está indo, certo? Direita?[n][f 1 3 65535][w][e]

