[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Aqui está nossa foto comemorativa do[n]festival de verão![n]Pelo menos, essa foi a ideia.[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14][f 5 18 483 80 1][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]É... certamente evocativo.[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Bem, não deixe isso chegar até você.[n]Merda acontece.[n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]É compreensível, dado o calor. Talvez[n]suas mãos tenham ficado suadas e elas[n]caíram.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Da próxima vez, garantiremos que vamos a[n]algum lugar que podemos realmente comer.[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Concordou. Eu preferiria um[n]estabelecimento interno, eu mesmo.[n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14]De preferência um com amplo assento e[n]recargas gratuitas na água.[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]Uh... isso seria apenas o restaurante[n]novamente.[n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14]E porque não? É um lugar de calma, onde[n]também pode participar de comida[n]deliciosa.[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14]Quero dizer, eu acho...? Cara, toda essa[n]conversa sobre comida me deixou com fome.[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]Um ramen de xícara chegaria ao local.[n][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Eu acredito que farei o mesmo.[n]Felizmente, adquiri recentemente algumas[n]crostas de pão de alta qualidade.[n][w][e]

[msg MSG_014_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1032 65535 0]... desculpe, eu não consegui pegar por[n]você.[n]Eu sempre esqueço o quão curtos meus[n]braços são como um gato...[n][f 1 3 65535][w][e]

