[msg MSG_000_0_0 [Takemi]]
[s][f 5 14]Você não vem para o ensaio clínico?[n][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][f 5 14]Não poderei vender nenhum novo[n]medicamento a esse ritmo.[n][w][e]

[msg MSG_002_0_0 [Takemi]]
[s][f 5 14]Apresse-se e visite a clínica.[n][w][e]

[msg MSG_003_0_0 [Takemi]]
[s][f 5 14]Ou estou apenas te irritando agora?[n]Se for esse o caso, posso parar de[n]conversar com você.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ignorar os convites de Takemi está[n]diminuindo sua confiança em você...[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Você quer ir vê-la?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_CORPNG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Você deve estar cansado da sua viagem ao[n]metaverso. Talvez você deva descansar um[n]pouco hoje.[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Vá imediatamente [e]
[s]Decidir depois [e]

[sel SEL_002 top]
[s][f 5 14]Eu estarei lá em breve.[e]

[msg CHAT_REACTION [Takemi]]
[s][f 5 14]OK.[n][f 5 15][w][e]

[msg MSG_CORP_PLAY_CHECK1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ignorar os convites de Takemi está[n]diminuindo sua confiança em você...[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Você quer ir vê-la?[n][f 1 3 65535][w][e]

[msg MSG_CORP_PLAY_CHECK2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ignorar os convites de Takemi está[n]diminuindo sua confiança em você...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Ninguém pensa que você está vivo neste[n]momento, então deve ficar bem, desde que[n]você seja cuidadoso.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Você quer ir vê-la?[n][f 1 3 65535][w][e]

