[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Whoa, este índice de aprovação é insano.[n]São mais de 60% agora![n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]Ah, você está me fazendo corar![n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Eu não estou falando sobre você![n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Não, isso é definitivamente graças ao[n]Futaba silenciando medjed.[n][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][f 5 14]Ver??? Que tal isso!?[n][w][e]

[msg MSG_005_0_0 [Ann]]
[s][f 5 14]É meio assustador o quão forte é esse[n]momento...[n][w][e]

[sel SEL_006_0_0 top]
[s][f 5 14]É encorajador.[e]
[s]Estou preocupado.[e]
[s]Quem se importa?[e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]Direita? Essa merda é como a motivação[n]perfeita![n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]Vamos, você também?[n]O que você está dizendo!?[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]Por que o ombro frio? Essas pessoas estão[n]torcendo por nós.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Todo mundo tem grandes expectativas dos[n]ladrões Phantom. Vamos garantir que eles[n]sejam respondidos![n][w][e]

[msg MSG_011_0_0 [Makoto]]
[s][f 5 14]Além de tudo isso, este caso esclareceu[n]algo importante.[n][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][f 5 14]Você quer dizer isso criminoso.[n][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][f 5 14]Bem... suponho que, neste momento,[n]podemos nos referir a eles como aquele[n]por trás dos desligamentos mentais.[n][w][e]

[msg MSG_014_0_0 [Futaba]]
[s][f 5 14]Foi aquele que matou minha mãe...[n][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][f 5 14]Não podemos deixá-los estar.[n][w][e]

[msg MSG_016_0_0 [Makoto]]
[s][f 5 14][f 5 15]Vamos falar mais em detalhes sobre isso[n]amanhã na escola.[n][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][f 5 14]Porcaria.[n][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][f 5 14]Espero acordar a tempo.[n]Quando devo sair?[n][w][e]

[msg MSG_019_0_0 [Ann]]
[s][f 5 14]Uh, isso é uma piada?[n][w][e]

[msg MSG_020_0_0 [Yusuke]]
[s][f 5 14]Que tipo de estilo de vida você lidera?[n][w][e]

[msg MSG_021_0_0 [Makoto]]
[s][f 5 14]Inacreditável.[n][w][e]

[msg MSG_022_0_0 [Makoto]]
[s][f 5 14]Eu confio que você sabe o que vai[n]acontecer se você estiver atrasado?[n][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Sim, senhora...[n][w][e]

