[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]Oh, eu não notei que tinha recebido uma[n]resposta de Akechi-kun. Ele aceitou o[n]convite de palestra.[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Bom trabalho.[e]
[s]Ouvi.[e]

[msg MSG_002_0_0 [Makoto]]
[s][f 5 14]Obrigada. O primeiro passo é feito pelo[n]menos...[n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]HM? Sério?[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]De qualquer maneira, o problema real é o[n]que fazemos a seguir.[n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]A palestra é na tarde do segundo dia, sim?[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Espere, você está vindo para o nosso[n]festival escolar?[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]É durante a semana do exame, então[n]poderei ir à tarde.[n][w][e]

[msg MSG_007_0_1 [Makoto]]
[s][f 5 14]Você pode pagar essa distração?[n]Como está o seu estudo?[n][w][e]

[msg MSG_007_0_2 [Yusuke]]
[s][f 5 14]Decentemente.[n][w][e]

[msg MSG_007_0_3 [Yusuke]]
[s][f 5 14]Aliás, esse conselheiro também estará no[n]festival?[n][w][e]

[msg MSG_007_0_4 [Ryuji]]
[s][f 5 14]Oh, Dr. Maruki? Provavelmente.[n][w][e]

[msg MSG_007_0_5 [Yusuke]]
[s][f 5 14]Eu vejo! Finalmente, vou testemunhar suas[n]habilidades para mim...[n][w][e]

[msg MSG_007_0_6 [Yusuke]]
[s][f 5 14]Talvez eu deva preparar um presente.[n]Eles dizem que as primeiras impressões[n]são tudo.[n][w][e]

[msg MSG_007_0_7 [Ryuji]]
[s][f 5 14]Não sei se ele estará lá.[n]Se alguma coisa for confirmada, eu vou[n]deixar você uma linha.[n][w][e]

[msg MSG_007_0_8 [Yusuke]]
[s][f 5 14]Muito grato.[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]Você quer vir também, Futaba?[n]Vamos, vai ser divertido![n][w][e]

[msg MSG_009_0_0 [Futaba]]
[s][f 5 14]A sério?[n][w][e]

[msg MSG_010_0_0 [Haru]]
[s][f 5 14]Não vejo por que não. Todos nós devemos[n]andar juntos amanhã![n][w][e]

[sel SEL_011_0_0 top]
[s][f 5 14]Isso soa bem.[e]
[s]Não vamos.[e]

[msg MSG_012_0_0 [Makoto]]
[s][f 5 14]Em um momento como este?[n][w][e]

[msg MSG_014_0_0 [Haru]]
[s][f 5 14]Esta é a chance perfeita para relaxarmos.[n][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][f 5 14]Haru, hum, tem certeza que você está bem?[n]Isso parece um pouco em breve.[n][w][e]

[msg MSG_016_0_0 [Haru]]
[s][f 5 14]Eu sou, obrigado.[n][w][e]

[msg MSG_017_0_0 [Haru]]
[s][f 5 14]Eu sempre sonhei em andar pelo meu[n]festival escolar com amigos.[n][w][e]

[msg MSG_018_0_0 [Makoto]]
[s][f 5 14]Suponho que, se você disser assim, posso[n]me resignar a aproveitar nosso tempo lá[n]também.[n][w][e]

[msg MSG_019_0_0 [Makoto]]
[s][f 5 14]Obrigado, Haru.[n][w][e]

[msg MSG_020_0_0 [Haru]]
[s][f 5 14][f 5 15]O prazer é meu.[n][w][e]

