[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Eu observo a humanidade em Shibuya.[n]Isso estimula minha criatividade,[n]geralmente.[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]Mas devo admitir que acho[n]difícil me concentrar, dada[n]a nossa situação.[n][w][e]

[msg MSG_001_0_1 [Yusuke]]
[s][f 5 14]De qualquer forma, vejo você hoje?[n]Estou pronto quando você quiser.[n][w][e]

[msg MSG_001_1_0 [Yusuke]]
[s][f 5 14]Até que haja resultados claros, duvido que[n]consiga me acalmar completamente.[n][w][e]

[msg MSG_001_1_1 [Yusuke]]
[s][f 5 14]Por enquanto, continuarei a observar[n]a humanidade em Shibuya…[n][w][e]

[msg MSG_001_2_0 [Yusuke]]
[s][f 5 14]Continuarei a observar[n]a humanidade em Shibuya[n]por mais algum tempo.[n][w][e]

[msg MSG_001_2_1 [Yusuke]]
[s][f 5 14]Você gostaria de se juntar a mim?[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Avise-me se precisar de alguma coisa.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Yusuke ainda não foi para casa.[n]Você quer ir até ele?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Yusuke está em Shibuya.[n]Você quer ir até ele?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ninguém pensa que você está vivo.[n]Se você tomar cuidado,[n]tudo deve ficar bem.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Você quer ir na casa do Yusuke?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Vá agora[e]
[s]Decidir depois[e]

[sel SEL_002 top]
[s][f 5 14]Estou vindo.[e]

[msg MSG_REACTION [Yusuke]]
[s][f 5 14]OK. Estou na passagem subterrânea.[n][f 5 15][w][e]

