[msg MSG_000_0_0 [Haru]]
[s][f 5 14]【仮】[f 4 2]君、今大丈夫?[n]話したいことがあるの[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]【仮】大事な時期なのは[n]判ってる[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]【仮】けど、どうしても顔を見て[n]話したくって[n][w][e]

[msg MSG_003_0_0 [Haru]]
[s][f 5 14]【仮】どうかな?[n]時間貰えると嬉しいな[n][f 5 15][w][e]

[msg CHAT_REACTION_MSG_01 [Haru]]
[s][f 5 14]【仮】[n]ありがとう[n][w][e]

[msg CHAT_REACTION_MSG_02 [Haru]]
[s][f 5 14]【仮】それじゃあ、学校の屋上に[n]来て欲しいな[n][w][e]
[s]待ってるね[n][f 5 15][w][e]

[msg CHAT_REACTION_MSG_03 [Haru]]
[s][f 5 14]【仮】今、学校の屋上に来てるの[n]来て欲しいな[n][w][e]
[s]待ってるね[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Você vai aceitar[n]o convite de Haru?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Vá agora[e]
[s]Verifique o vínculo com Haru[e]
[s]Decidir depois[e]

[sel SEL_002 top]
[s][f 5 14]Eu estarei lá.[e]

[msg MND_COOP_DOUZOKUSEI]
[s]Eu deveria ser capaz de fortalecer[n]nosso vínculo, já que tenho [clr 1][var 5][clr 27][n]da Arcana [var 2]...[n][w][e]

