[msg MSG_CHAT_001_00 [Mishima]]
[s][f 5 14]Você falou com Nishiyama?[n][w][e]
[s][f 5 14]Bem, eu mesmo fiz uma pequena[n]investigação sobre Iida, a propósito.[n][w][e]
[s][f 5 14]Eles dizem que ele está envolvido em[n]algum tipo de trabalho obscuro de meio[n]período.[n][w][e]
[s][f 5 14]Aparentemente, esse trabalho[n]é coisa de louco ...[n][w][e]
[s][f 5 14]Tem algo a ver com tráfico de drogas, eu[n]acho.[n][w][e]
[s][f 5 14][f 5 15]Ouvi dizer que eles abordam[n]pessoas na Central Street.[n]E em plena luz do dia, mesmo...[n][w][e]

