[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Eu tentei mudar o ícone de bate-papo.[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Parece o mesmo para mim.[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Talvez seja apenas para o grupo e não[n]apareça aqui...[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Bem, você deve dar uma olhada mais tarde.[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]É aquele logotipo do Phantom Thieves que[n]eu tinha Yusuke desenhando para nós.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]O cartão de visita também ficou grande[n]como causa dele.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]De qualquer forma, este é o primeiro[n]emprego para os ladrões fantasmas. Nós[n]realmente não podemos estragar tudo, k?[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Não estou subestimando nada, garanto-lhe.[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]E certifique-se de que Yusuke descanse[n]muito hoje, ok?[n][w][e]

[msg MSG_009_0_0 [Ann]]
[s][f 5 14]Sim.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Bem, veja vocês amanhã![n][w][e]

[sel SEL_011_0_0 top]
[s][f 5 14]Entendi.[e]
[s]Noite.[e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14][f 5 15]Vejo você amanhã![n][w][e]

