[msg MSG_033_0_0 [Mishima]]
[s][f 5 14]Há um boato bastante perturbador[n]sobre um figurão da indústria[n]do entretenimento.[n][w][e]
[s][f 5 14]Diz-se que ele forçou jovens ídolos e[n]outras garotas a fazer sexo com ele para[n]avançar em sua carreira.[n][w][e]
[s][f 5 14]Aparentemente, ele está apenas explorando[n]seus sonhos.[n][w][e]

[sel SEL_034_0_0 top]
[s][f 5 14]Não podemos tolerar isso.[e]
[s]Eh, não parece tão sério.[e]
[s]Que indústria sórdida.[e]

[msg MSG_035_0_0 [Mishima]]
[s][f 5 14]Direita?!?[n][w][e]

[msg MSG_036_0_0 [Mishima]]
[s][f 5 14]Mas não é um problema,[n]se ele os está forçando?!?[n][w][e]

[msg MSG_037_0_0 [Mishima]]
[s][f 5 14]Eu não posso perdoá-lo.[n][w][e]

[msg MSG_038_0_0 [Mishima]]
[s][f 5 14]De qualquer forma, o nome Shiro Asakura[n]significa alguma coisa para você? Parece[n]que ele está por trás desses crimes.[n][w][e]
[s][f 5 14][f 5 15]Bem, para o resto[n]conto com você![n][w][e]

[msg MSG_quest33_MORGANA_SAY [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Esse cara não é muito famoso,[n]mas não podemos deixá-lo[n]sair impune.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Vamos falar com os outros no ponto de[n]encontro o mais rápido possível, ok?[n][f 1 3 65535][w][e]

[msg MND_quest33_OPEN_SELF]
[s][vp 8 2 65535 0 0 0]Parece que um novo alvo está disponível.[n]Talvez eu deva investigar esse nome.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Script fictícioChat_245[e]

