[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]Ei, aparentemente aquele assassino[n]desapareceu completamente[n]do metrô de Shibuya![n][w][e]
[s][f 5 14]Algum idiota que não liga para[n]sua pele foi lá de dia[n]para interrogar o morador de rua.[n][w][e]
[s][f 5 14]Mas é estranho que ele diga[n]que "desapareceu"[n]em vez de "se aposentou".[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Eu vejo...[e]
[s]É muito estranho.[e]
[s]Isso é bom em qualquer caso.[e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]Você resolveu a intriga? De você[n]eu não esperava menos.[n][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][f 5 14]É possível que ele tivesse[n]múltiplas personalidades.[n][w][e]
[s][f 5 14]Embora talvez eu esteja voando um pouco[n]demais com a imaginação...[n][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][f 5 14]Eu penso que sim. Palavras difíceis,[n]hein?[n][w][e]

[msg MSG_005_0_0 [Mishima]]
[s][f 5 14]No entanto, os Phantom Thieves podem[n]reivindicar sua vitória[n]sobre o assassino do mal![n][w][e]
[s][f 5 14][f 5 15]Tenho certeza que ainda mais pessoas[n]ficarão de olho em você a partir de[n]agora! Conto com você também![n][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Esse caso foi bem[n]complicado, não acham?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Um pouco como a exploração[n]dos Mementos, afinal...[n][f 1 3 65535][w][e]

[msg MND_quest29_CLEAR_SELF]
[s][vp 8 2 65535 0 0 0]Parece que conseguimos[n]despertar o coração do alvo.[n][f 1 3 65535][w][e]

