[msg MSG_000_0_0 [Chihaya]]
[s][f 5 14]As estrelas dizem que hoje é um dia muito[n]importante.[n][w][e]

[msg MSG_001_0_0 [Chihaya]]
[s][f 5 14]...Acho que não preciso[n]dizer o porquê, preciso...?[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Eu sei, não se preocupe.[e]

[msg MSG_020_0_0 [Chihaya]]
[s][f 5 14]Você parece já ter algo em mente.[n]Então eu confio em você, ok?[n][w][e]

[msg MSG_021_0_0 [Chihaya]]
[s][f 5 14]Eu vou esperar por você.[n][f 5 15][w][e]

