[msg MSG_000_0_0 [Haru]]
[s][f 5 14]Nessas circunstâncias, eu não tinha[n]certeza se deveria falar, mas...[n][w][e]

[msg MSG_000_5_0 [Haru]]
[s][f 5 14]Eu quero passar a véspera de Natal com[n]você...[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]Talvez pudéssemos caminhar um pouco a[n]cidade e depois voltar para o seu quarto?[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Isso parece ótimo.[e]

[msg MSG_020_0_0 [Haru]]
[s][f 5 14]Sério!?[n][w][e]

[msg MSG_021_0_0 [Haru]]
[s][f 5 14]Ainda estou em Shibuya! Venha me[n]encontrar em frente à estação![n][f 5 15][w][e]

