[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Estou assistindo pessoas em Shibuya[n]agora. Eu pensei que poderia fazer com[n]que os sucos criativos fluam.[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]Devo dizer que, porém, tive dificuldade[n]em me concentrar, dada a nossa situação[n]atual.[n][w][e]

[msg MSG_001_0_1 [Yusuke]]
[s][f 5 14]Enfim, estamos nos reunindo hoje?[n]Estou pronto a qualquer momento.[n][w][e]

[msg MSG_001_1_0 [Yusuke]]
[s][f 5 14]Devo dizer que, porém, duvido que possa[n]me acalmar até que os resultados sejam[n]esclarecidos para nós.[n][w][e]

[msg MSG_001_1_1 [Yusuke]]
[s][f 5 14]Por enquanto, pretendo continuar as[n]pessoas assistindo em Shibuya...[n][w][e]

[msg MSG_001_2_0 [Yusuke]]
[s][f 5 14]Ainda pretendo manter as pessoas[n]assistindo em Shibuya por um tempo hoje.[n][w][e]

[msg MSG_001_2_1 [Yusuke]]
[s][f 5 14]Você gostaria de se juntar a mim?[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Deixe-me saber se você precisar de alguma[n]coisa.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que Yusuke ainda não voltou para[n]casa. Quer vê-lo um pouco?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que Yusuke está em Shibuya.[n]Quer vê-lo um pouco?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ninguém pensa que você está vivo neste[n]momento, então deve ficar bem, desde que[n]você seja cuidadoso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Quer se encontrar com Yusuke um pouco?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Vá imediatamente [e]
[s]Decidir depois [e]

[sel SEL_002 top]
[s][f 5 14]Estou indo de cima.[e]

[msg MSG_REACTION [Yusuke]]
[s][f 5 14]OK. Estou na passagem subterrânea.[n][f 5 15][w][e]

