[msg MSG_ISHOP_HELLO [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][f 4 23 1 213 14 10 13 10]Isso é tudo o que tenho agora...[n][w][e]

[msg MSG_ISHOP_END [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][f 4 23 1 213 14 10 13 10]Então boa sorte com isso.[n][w][e]

[msg MSG_C13_COOP_OPEN_OK [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Oh sim! Lembra quando escutamos outro dia?[n][w][e]
[s][f 4 10 65535 0 0]Pode haver um remédio que possa lhe dar[n]super força. Definitivamente, poderíamos[n]usar isso.[n][w][e]
[s][f 4 10 65535 0 0]Vamos tentar perguntar àquele doutor Lady,[n]Tae Takemi.[n][w][e]

