[msg HELP_GIM_01]
[s]Custo: 10.000 ienes apenas utilizáveis[n]durante o dia nos fins de semana e feriados [n][e]

[msg HELP_GIM_02]
[s]Custo: 50.000 ienes apenas utilizáveis[n]durante o dia [n][e]

[msg HELP_GIM_03]
[s]Custo: 100.000 ienes utilizáveis a qualquer[n]dia, a qualquer hora [n][e]

[msg MSG_005_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Ei, bem-vindo.[n][w][e]
[s]São amantes de proteínas, uma academia para[n]quem quer um corpo saudável.[n][w][e]

[msg MSG_009_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Parece que você ainda não é um membro.[n]Você deve considerar isso![n][w][e]

[msg MSG_016_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Então, qual pacote de membros você gostaria?[n][w][e]

[sel SEL_017_0_0 top]
[s]Passe de bronze [ref 0 0][e]
[s]Pass Silver [ref 1 1][e]
[s]Pass Gold [ref 2 2][e]

[msg MSG_NO_MONEY [Morgana]]
[s][bup 0 3 2 0 0][vp 8 2 0 1029 65535 0]Você não tem dinheiro para isso...[n][w][e]

[msg MSG_018_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Oh, você não quer se tornar um membro? Você[n]deveria totalmente![n]Podemos suar juntos![n][w][e]

[sel SEL_019_0_0 top]
[s]Pensando melhor...[e]
[s]Talvez outra hora.[e]

[msg MSG_020_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Entendo... espero que você venha de novo![n][w][e]

[msg MSG_021_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Peguei vocês. Aquele, hein? Venha sempre que[n]quiser![n][w][e]
[s][vp 1 0 0 0 0 0]Agora, para comemorar sua associação, você[n]pode treinar hoje, não importa o que você[n]tenha escolhido.[n][w][e]
[s][vp 1 0 0 0 0 0]Você veio até aqui, então por que não ter?[n][w][e]

[sel SEL_022_0_0 top]
[s]Eu vou treinar.[e]
[s]Vou passar.[e]

[msg MSG_023_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Depois de sair, você só pode voltar durante[n]seus horários designados. Você está bem com[n]isso?[n][w][e]

[sel SEL_024_0_0 top]
[s]Eu não me importo.[e]
[s]Eu vou treinar.[e]

[msg MSG_025_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Entendo... bem, venha de novo quando você[n]sentir vontade![n][w][e]

[msg MSG_026_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Tudo bem, então! Vá em frente e treine para[n]o conteúdo do seu coração![n][w][e]

[msg MSG_027_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Ooh, não esperava que você escolhesse isso.[n]Você deve estar planejando algum[n]treinamento sério.[n][w][e]
[s][vp 1 0 0 0 0 0]Agora a academia é sua ostra![n]Venha para suar a suar sempre que quiser![n][w][e]
[s][vp 1 0 0 0 0 0]Bem, então, você quer começar a treinar[n]imediatamente?[n][w][e]

[sel SEL_028_0_0 top]
[s]Eu vou treinar.[e]
[s]Vou passar.[e]

[msg MSG_029_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Entendo... bem, venha de novo quando você[n]sentir vontade![n][w][e]

[msg MSG_030_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Tudo bem, então! Vá em frente e treine para[n]o conteúdo do seu coração![n][w][e]

[msg MSG_031_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Ei! Bem-vindo![n][w][e]

[msg MSG_032_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Então, para que você está aqui?[n][w][e]

[sel SEL_033_0_0 top]
[s]Eu quero conseguir uma associação.[e]
[s]Eu quero mudar meu passe.[e]
[s]Eu quero treinar.[e]
[s]Eu não preciso de nada.[e]

[msg MSG_034_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Você entendeu! Qual passe você gostaria?[n][w][e]

[sel SEL_035_0_0 top]
[s]Pass Silver [ref 0 1][e]
[s]Pass Gold [ref 1 2][e]

[msg MSG_036_0_0 [Personal Trainer]]
[s][vp 1 0 0 0 0 0]Entendo... bem, venha de novo quando você[n]sentir vontade![n][w][e]

[msg MND_EVENT_NEXT_000_00]
[s][vp 8 2 65535 0 0 0]Eu não vejo meus amigos aqui...[n]Eu deveria ir para outro lugar...[n][w][e]

[msg MSG_IKEDA_001_0_0 [Ikeda-senpai]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Oh, você é aquele cara que estava com[n]Sakamoto...[n][w][e]

[sel SEL_IKEDA_002_0_0 top]
[s]O que é Bonkin '?[e]
[s]Olá.[e]
[s]Eu sou seu amigo.[e]

[msg MSG_IKEDA_003_0_0 [Ikeda-senpai]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Oh não, você também não...[n][w][e]

[msg MSG_IKEDA_003_1_0 [Ikeda-senpai]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Hahah, não precisa ser tão educado.[n][w][e]

[msg MSG_IKEDA_003_2_0 [Ikeda-senpai]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Eu pensei assim.[n]Não é de admirar que você pareça familiar.[n][w][e]

[msg MSG_IKEDA_004_0_0 [Ikeda-senpai]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]É verdade que Sakamoto quer voltar para a[n]equipe de pista que ele está se movendo[n]apenas para que ele possa fazer a[n]reabilitação?[n][w][e]
[s][vp 8 2 1 0 65535 0]Eu me senti tão feliz ao ouvir isso![n]Seria coxo se ele não fizesse nada![n][w][e]
[s][vp 8 2 1 0 65535 0]Então, estou planejando ajudá-lo o máximo[n]possível.[n][w][e]
[s][vp 8 2 1 0 65535 0]Você não acha incrível se ele e eu pudesse[n]correr juntos novamente?[n][w][e]

[msg MSG_IKEDA_004_0_1 [Ikeda-senpai]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Então eu ouvi Sakamoto não voltar para a[n]equipe...[n][w][e]
[s][vp 8 2 1 0 65535 0]Eu sinto que é um desperdício de talento,[n]mas se esse é o caminho que ele escolhe, eu[n]aceitarei.[n][w][e]
[s][vp 8 2 1 0 65535 0]Talvez ele queira voltar um dia desses.[n][w][e]
[s][vp 8 2 1 0 65535 0]Se isso acontecer, eu com certeza adoraria[n]correr com ele novamente.[n][w][e]

[msg MSG_IKEDA_END_0 [Ikeda-senpai]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Eu posso correr com Sakamoto novamente.[n]Isso é tão incrível![n][w][e]

[msg MSG_IKEDA_END_1 [Ikeda-senpai]]
[s][f 4 23 1 65535 3 10 0 10][vp 8 2 1 0 65535 0]Bem, se Sakamoto voltar ao time de pista um[n]dia, eu certamente iria querer correr com[n]ele.[n][w][e]

[msg MND_IKEDA_010_0_0]
[s][vp 8 2 65535 0 0 0]Eu me despedi de Ikeda-senpai.[n]Eu deveria ir para outro lugar.[n][w][e]

