[msg MSG_054_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 76 65535 0]You good with that?[n][f 1 3 65535][w][e]

[sel SEL_055_0_0 top]
[s]Fine by me.[e]
[s]I want ramen.[e]
[s]We should save the money.[e]

[msg MSG_NOT_SELECT_PARA]
[s]......[n][w][e]
[s]ダメだ、この発言をするには[n][clr 26]そつがない[clr 27]くらいの[f 4 11 2][clr 26][f 4 12 2][clr 27]が必要だ...[n][w][e]

[msg MSG_054_5_0 [Ryuji]]
[s][bup 0 2 0 65535 0][vp 1 0 0 0 0 0][f 0 6 255 0]You good with that?[n][f 1 3 65535][e]

