[msg MSG_059_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 74 65535 0]A building that's related to artists...[n]If we think from there, what would it be...?[n][f 1 3 65535][w][e]

[sel SEL_060_0_0 top]
[s]An art school.[e]
[s]An art supply store.[e]
[s]A museum.[e]

[msg MSG_061_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 75 65535 0]...No reaction. Anything else?[n][f 1 3 65535][w][e]

[msg MSG_062_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 76 65535 0]...That's no good either. Anything else?[n][f 1 3 65535][w][e]

