[msg MSG_000_0_0 [Detetive policial]]
[s][vp 8 0 0 1 5 0]Desculpe, mas esta área não pode ser acessada...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Mulher de negócios]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Eu sou a Niijima[n]do Ministério Público.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Detetive policial]]
[s][vp 8 0 0 3 5 0]Do Ministério Público?[n]O que a traz aqui?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Mulher de negócios]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Deixe-me passar, é urgente.[n]Preciso verificar algumas coisas[n]com o suspeito.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Detetive policial]]
[s][vp 8 0 0 5 5 0]Niijima-san, receio que o caso não esteja mais[n]em sua jurisdição.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 6 5 0]Além disso...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Chef detetive]]
[s][vp 8 0 0 7 6 0]Você é a promotora Sae Niijima?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Chef detetive]]
[s][vp 8 0 0 8 6 0]Recebi uma ligação do seu superior.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 9 6 0]Apresse-se e vamos acabar com isso.[n]Francamente, você[n]está nos incomodando aqui.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Voz do diretor da SIU]]
[s][vp 8 0 0 10 65535 0]*suspiro* Achei que tinha[n]mandado você esperar.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Eu sou responsável por este caso[n]mas não tenho permissão nem para um[n]interrogatório!?![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Voz do diretor da SIU]]
[s][vp 8 0 0 12 65535 0]Chamei você porque sabia que[n]desistiria do assunto.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Não estarei convencida até[n]verificar por mim mesmo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Este é o MEU caso.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Voz do diretor da SIU]]
[s][vp 8 0 0 15 65535 0]*suspiro* Boa sorte então.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 16 65535 0]Não espero muito[n]mas...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Chef detetive]]
[s][vp 8 0 0 17 6 0]Ah, promotora, esqueci[n]de te falar uma coisa importante.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Chef detetive]]
[s][vp 8 0 0 18 6 0]Ele não terá muito tempo.[n]Não podemos deixar você[n]falar muito com ele.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sae]]
[s][bup 0 105 3 65535 0][vp 1 0 0 19 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Chef detetive]]
[s][vp 8 0 0 20 6 0]É para o bem dele.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 21 6 0]Seus métodos ainda são desconhecidos.[n]Nós nem sabemos se é seguro[n]entrar lá e falar com ele.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]...Entendo.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]...Eu não esperava que fosse você.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Desta vez você terá que responder[n]minhas perguntas.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Esses desgraçados...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Você pode me ouvir? Não sei[n]pelo o que você passou...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Eles fazem o que querem aqui,[n]e não posso impedi-los.[n][f 1 3 65535][w][e]

[msg MSG_020_5_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]É por isso que preciso que você me responda[n]honestamente. Não tenho muito tempo.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Qual era seu objetivo?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Por que você causou um incidente tão grave?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Não pensei que fosse uma brincadeira desde[n]o início, mas não consegui montar[n]um caso para o processo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Porque não consegui[n]entender a lógica.[n][f 1 3 65535][w][e]

[sel SEL_023_0_0 top]
[s]Claro que você não poderia...[e]
[s]Por que você quer saber?[e]

[msg MSG_025_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Exatamente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]É impossível para mim convencer[n]da existência de tal...[n]"mundo" apenas lendo os relatórios.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Se trata do que pode ou não[n]ser usado no tribunal.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Eu preciso saber.[n]Afinal, este é o meu caso.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Você parece ser capaz de falar.[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 59 65535 0]Quando e onde você descobriu[n]sobre a existência desse mundo?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 60 65535 0]Como é possível roubar o coração de outra pessoa?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 62 65535 0]Vamos, conte-me sua[n]versão completa da história.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 61 65535 0]...Comece do início.[n][f 1 3 65535][w][e]

