[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Hum, é aquele aplicativo estranho[n]que apareceu de repente[n]no meu telefone...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]O ícone parece[n]quase com um olho...[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Mas eu desinstalei...[e]
[s]É tão assustador...[e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Minhas pálpebras estão[n]pesadas...[n][f 1 3 65535][w][e]

