[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Tem tanta gente[n]espremida neste[n]vagão minúsculo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Realmente é verdade[n]o que dizem sobre[n]o metrô de Tóquio...[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Essa tela de LCD está transmitindo[n]as últimas notícias...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Parece que os efeitos[n]do acidente de ontem ainda não[n]terminaram...[n][f 1 3 65535][w][e]

