[msg MSG_002_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]*suspiro* Incrível...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Atrasar mais da metade[n]de um dia no primeiro dia...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Você se importa de me explicar?[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Estava perdido.[e]
[s]O trem estava atrasado.[e]
[s]Eu estava em um castelo.[e]

[msg MSG_005_0_0 [Kawakami]]
[s][bup 0 109 2 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Como você não encontrou o[n]caminho até agora?[n]Está quase na hora do almoço.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Resumindo, é verdade que você ainda não[n]está familiarizado com a área... mas[n]chegou tarde demais de qualquer maneira.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kawakami]]
[s][bup 0 109 2 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Tá na hora do almoço, sabe?[n]Você teria chegado mais cedo se[n]saísse de casa a pé.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]É verdade que os horários dos trens estão[n]um caos por causa do acidente,[n]mas você chegou atrasado de qualquer maneira.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Kawakami]]
[s][bup 0 109 2 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Você está brincando...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Kawakami]]
[s][bup 0 109 2 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Você quer se recompor?[n]Ontem você foi avisado[n]devidamente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Mas acima de tudo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Ouvi dizer que você foi visto[n]com aquele Sakamoto-kun.[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]Eu não tive escolha.[e]
[s]"Aquele" Sakamoto...?[e]

[msg MSG_012_0_0 [(SE)川上 貞代]]
[s][vp 8 0 0 12 65535 0](重いため息)[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Kawakami]]
[s][bup 0 109 2 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Não se meta com ele, ok?[n]Ele é só problema.[n][f 1 3 65535][w][e]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Embora...não fosse o caso[n]quando ele dedicava seu tempo[n]ao atletismo...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Enfim, o intervalo está quase acabando.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Hoje as aulas terminarão após[n]a quinta aula devido[n]ao acidente no metrô.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Vou apresentá-lo aos seus colegas assim que as[n]aulas forem retomadas.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Siga-me.[n][f 1 3 65535][w][e]

