[msg MSG_000_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]HM? O que está errado?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Isso é uma escola?[e]
[s]É isso... um castelo?[e]

[msg MSG_002_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]* suspiro* tem certeza de que está bem?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Além disso... parece que as pessoas já estão[n]falando sobre você, mas não sou eu quem[n]disse a elas.[n][f 1 3 65535][w][e]

[msg MSG_002_5_0 [Kawakami]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 109 16 300 1][vp 8 0 0 4 65535 0]Não consigo nem fazer uma pausa... por que[n]tenho que lidar com isso?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Você deve ir direto para casa sem parar em[n]qualquer lugar. Sakura-san parecia muito[n]zangado.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Ah, e sobre Sakamoto-kun. Não se envolva- [n][f 1 2 90][e]

[msg MSG_005_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Falando no diabo...[n][f 1 3 65535][w][e]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]O que você quer? Ouvi a polícia te pegar[n]cortando aulas hoje.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sakamoto]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Ugh... não era nada.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]E você também não pintou o cabelo de volta[n]para preto...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sakamoto]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Desculpa aí.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sakamoto]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]... Eu estarei esperando no telhado.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [(SE)川上 貞代]]
[s][vp 8 0 0 14 65535 0](わざとらしいため息)[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Ver? É por isso que não quero que você se[n]envolva. Entendido?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Por que você permitiu que um aluno como ele[n]se transferisse aqui? Ele já começou a se[n]associar a Sakamoto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Um aluno com registro criminal e o culpado[n]de um caso de agressão.[n][f 1 3 65535][w][e]

[msg MSG_012_5_0 [Kamoshida]]
[s][bup 0 202 3 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Nesse ritmo, seria inútil o quanto eu[n]contribui para a escola.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Principal]]
[s][bup 0 204 3 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Agora, não seja assim...[n][f 1 3 65535][w][e]
[s][bup 0 204 0 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Esta escola conta com você, Kamoshida-kun.[n]Você é nossa estrela.[n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Principal]]
[s][bup 0 204 3 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Ainda assim, também é necessário um acúmulo[n]constante por trás de esse brilho.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Kamoshida]]
[s][bup 0 202 3 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]... Seus problemas nunca parecem acabar,[n]eles, diretor Kobayakawa?[n][f 1 3 65535][w][e]
[s][bup 0 202 1 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Tudo bem, eu entendo. Continuarei fazendo o[n]meu melhor para responder às suas[n]expectativas de mim.[n][f 1 3 65535][w][e]

