[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]...Você está de volta.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Presumo que você[n]foi à escola hoje?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]É claro.[e]
[s]O que você acha disso?[e]
[s]Foi muito difícil.[e]

[msg MSG_002_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Acho que você aprendeu[n]sua lição, depois do que[n]aconteceu ontem.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Bem, contanto que você não se meta em encrenca,[n]estou bem com isso.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Huh? Eu faço as perguntas aqui. De qualquer[n]forma, contanto que você não tenha problemas,[n]estou bem com isso.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Ei... É melhor você não se meter em encrenca.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]As pessoas já segmentaram[n]você. Não faça[n]coisas estúpidas, ok?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Não sei o que você está fazendo,[n]mas confie em mim, você ficará desabrigado[n]se começar a causar problemas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Caso você tenha esquecido,[n]sua liberdade atualmente[n]tem limites.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]...Que diabos, você[n]pelo menos está me ouvindo?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Tente ficar longe[n]de más companhias, ok?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Ei, estou indo[n]para casa esta noite.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Vou desligar.[n]Não fique por aqui.[n][f 1 3 65535][w][e]

