[msg MSG_000_0_0 [Habitué arrogante]]
[s][vp 8 0 0 1 65535 0]Chefe, você ouviu?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 2 65535 0]Eles dizem que o motorista daquele[n]metro se comportou de[n]forma estranha durante o depoimento.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Você está se referindo àqueles raptus[n]o como eles são chamados,[n]que todo mundo fala o tempo todo?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Habitué arrogante]]
[s][vp 8 0 0 4 65535 0]Sim, ouvi dizer que eles alteram[n]a personalidade completamente.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 5 65535 0]Os noticiários dizem que[n]o motorista não conseguiu nem[n]responder às perguntas.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Só um idiota acreditaria[n]uma história tão absurda.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Ah, desculpe,[n]mas estamos fechando.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Habitué arrogante]]
[s][vp 8 0 0 8 65535 0]Umpf, que rude. Deve ser por isso que[n]ele não tem muitos clientes.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 9 65535 0]Na verdade, seu café não é[n]ruim, mas seus grãos reclamam[n]da tristeza deste lugar...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Obrigado pela visita.[n]Volte em breve.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Habitué arrogante]]
[s][vp 8 0 0 11 65535 0]Estou apenas tentando ajudá-la a melhorar[n]seu negócio. Bem, obrigado pelo[n]café, pelo menos.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Porra, que peste...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Oh... O que você quer?[n]Se você está entediado, vá lavar[n]alguns pratos.[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Como está o seu negócio?[e]
[s]Você trata os clientes assim?[e]
[s]Como você consegue clientes?[e]

[msg MSG_010_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Não é da sua conta.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Como sempre.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Cale a boca.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Contanto que a localidade não falhe,[n]tudo bem. Não sou do tipo que[n]sorri para agradar os outros.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]É esse o seu lema?[e]
[s]E se falhar?[e]

[msg MSG_015_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Não, não é sobre isso.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Quem sabe? Talvez eu acabe morando na rua.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Enquanto estou aqui,[n]o mundo me deixa em paz.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Sem aborrecimentos ou problemas para lidar. É o[n]meu esconderijo pessoal.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Eu provavelmente estaria falido[n]se o perdesse, mas acho que[n]o mesmo aconteceria com você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Portanto, você deve pelo menos[n]tentar ser útil.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]De qualquer forma, estou indo embora.[n]Não crie problemas.[n][f 1 3 65535][w][e]

