[msg MSG_000_0_0 [Haughty Regular]]
[s][vp 8 0 0 0 65535 0]Chefe, você ouviu?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Aparentemente, o motorista do metrô do[n]acidente estava agindo realmente estranho[n]durante sua audiência de testemunho.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você está falando sobre aquele psicótico, o[n]que as pessoas estão acontecendo?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Haughty Regular]]
[s][vp 8 0 0 0 65535 0]Sim, ouvi isso altera completamente sua[n]personalidade.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]A notícia está dizendo que o motorista não[n]podia nem falar quando eles tentaram fazer[n]perguntas.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não há como uma história absurda como essa[n]pode ser verdadeira.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ah, e desculpe, mas estamos fechando em[n]breve.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haughty Regular]]
[s][vp 8 0 0 0 65535 0]Hmph, que rude. Deve ser por isso que você[n]não recebe muitos clientes.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Seu café não está tão ruim.[n]O feijão deve estar lamentando o lamentável[n]estado desta loja...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Obrigado por parar. Por favor, volte.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Haughty Regular]]
[s][vp 8 0 0 0 65535 0]Hmph. Eu só digo isso por polidez, mas...[n]obrigado pelo café.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Gah, tanta dor. Ninguém pode dizer a[n]diferença entre real e instante, de[n]qualquer maneira.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh... o que você quer? Se você estiver[n]entediado, vá lavar alguns pratos ou algo[n]assim.[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Como é o negócio?[e]
[s]Ótimo serviço...[e]

[msg MSG_010_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Está bem. O mesmo que sempre.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não é diferente do habitual.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Enquanto o negócio estiver indo bem, não[n]sinto a necessidade de colocar um sorriso[n]falso no meu rosto.[n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]Isso é um lema?[e]
[s]Mas e se falhar?[e]

[msg MSG_014_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Não é importante.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quem sabe? Talvez eu acabe morando nas ruas.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Enquanto eu estiver aqui, todo mundo me[n]deixa.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Não há aborrecimentos ou pessoas[n]problemáticas para lidar. É como o meu[n]refúgio pessoal.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eu odiaria perdê-lo, mas seria pior para[n]você.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Então, por que você não se torna útil.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vou deixar a chave para você.[n]Fechar a loja amanhã.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Mal posso esperar todos os dias para você[n]chegar em casa.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Nada aqui eu sentiria falta se for roubado.[n]Só não queimar o lugar, você entendeu?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Certifique-se de desligar o gás e trancar as[n]portas. Os caminhões de bombeiros não podem[n]se encaixar nesses becos.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Enfim, estou saindo agora. Não causa nenhum[n]problema.[n][f 1 3 65535][w][e]

