[msg MSG_000_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]...Essa é toda a sua declaração?[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]*suspiro*[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Isso é tudo que você quer dizer?[n]Ou talvez as injeções[n]embaraçaram sua memória...?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]De qualquer forma, continuar falando com você[n]parece realmente uma perda de tempo.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]...É uma pena.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [(SE)主人公]]
[s][vp 8 0 0 6 65535 0]ハァ、ハァ、ハァ(ひどく荒い息遣い)[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Uomo misterioso]]
[s][vp 8 0 0 7 65535 0]...Deixe-me esclarecer uma coisa.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Uomo misterioso]]
[s][vp 8 0 0 8 65535 0]Aquele senso de justiça vazio que[n]você estava exibindo...?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 9 65535 0]Este é o fim de[n]tamanha idiotice.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Uomo misterioso]]
[s][vp 8 0 0 10 65535 0]...Adeus.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Essa memória nem[n]merecia ser relatada.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Eu até avisei você[n]que a ruína estava próxima.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]O jogo trouxe[n]ruína apenas para você, finalmente...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [(SE)警備係]]
[s][vp 8 0 0 14 65535 0]ん!? おい、誰か!![n][f 1 3 65535][w][e]
[s][vp 8 0 0 15 65535 0]死んでる! 自殺だ![n]くそ! ピストルなんて何処にñし持ってやがった![n][f 1 3 65535][w][e]

