[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ughh, estou recheado...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Em pânico totalmente quando vi a placa[n]"fechada para limpar" nos banheiros...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Você estava falando muito sobre comer até[n]vomitar, mas você realmente vomitou...[n]Você é algum tipo de idiota?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Ei, o mesmo vale para você![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Em que andar estava aquele restaurante?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Chegamos para chegar aqui, então tem que[n]estar em um andar inferior, certo?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]......![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]O que- [n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Distinguished Man]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 6 0]Ainda não há atualização no caso?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Man in a Suit]]
[s][vp 8 0 0 9 7 0]N-não ainda...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 10 7 0]Com licença, mas por que você está tão[n]envolvido? Não é algo com o qual você deve[n]se preocupar...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Distinguished Man]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 11 6 0]Eu não me importo com sua opinião, seu bufão[n]incompetente! Quando digo, acelere o ritmo,[n]você faz isso![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Ei, você está cortado na fila![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Man in a Suit]]
[s][vp 8 0 0 14 7 0]Estamos com pressa.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Oh, me desculpe. Então você pode se esforçar[n]na frente de outras pessoas se estiver com[n]pressa?[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Distinguished Man]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 17 6 0]Parece que a base de clientes mudou desde[n]que eu estive aqui por último. Eles[n]começaram uma creche?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]O que?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Man in a Suit]]
[s][vp 8 0 0 19 7 0]Senhor, não temos tempo para isso.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Distinguished Man]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 20 6 0]Eu sei.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Distinguished Man]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 21 6 0]Não se preocupe com eles![n][f 1 3 65535][w][e]

[msg MND_026_5_0]
[s][vp 8 0 0 0 65535 0]Essa voz agora...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]O inferno estava com aquele cara mandão?[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Não devemos voltar para baixo?[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Sim mas...[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 3 301 1][vp 8 0 0 25 65535 0]Aquele pau realmente me irritou. Ele nem[n]sequer escondeu o fato de ele olhar para[n]todos![n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Não perca a paciência por isso.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Eu simplesmente não posso perdoar adultos de[n]merda assim![n][f 1 3 65535][w][e]

[msg MND_032_5_0]
[s][vp 8 0 0 0 65535 0]A voz desse homem...[n][f 1 3 65535][w][e]

[msg MND_032_7_0]
[s][vp 8 0 0 0 65535 0]Parecia quase o daquele naquela época...[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]...O que está errado?[n][f 1 3 65535][w][e]

[sel SEL_034_0_0 top]
[s]Estou bem.[e]
[s]Só um pouco tonta.[e]
[s]Não se preocupe com isso.[e]

[msg MSG_035_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Tem certeza que? Você não está parecendo tão[n]quente.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Provavelmente é porque ele nunca come bem.[n]Estou sempre preso com comida de gato[n]enlatada também.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Você não se sente bem?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Ele quase nunca come bem, afinal...[n]Além disso, estou sempre preso comendo[n]comida de gato enlatada...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Isso só vai me fazer me preocupar mais, você[n]sabe.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Aposto que é porque ele raramente come bem.[n]Estou sempre preso com comida de gato[n]enlatada também...[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Ugh, essa besteira "senhor" me deixa doente![n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]... caramba![n][f 1 3 65535][w][e]

