[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Que diabos é esse lugar?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Espera, nossas roupas[n]mudaram!?![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]As Sombras sabem que estamos aqui!?![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Desde o momento em que[n]chegamos.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Você deveria ter nos contado![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Ainda estamos seguros aqui.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Eu vim várias vezes para investigar.[n]Sombras nunca ascendem a[n]este plano.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Mas quando você desce, a história muda. Este[n]lugar está simplesmente repleto de Sombras.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Mas acima de tudo, o que são[n]esses Mementos!?! Seria[n]hora de você nos explicar.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]As lembranças são...[n]o Palácio de todos.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Huh? O que você quer dizer com "todos"...?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Um palácio tão grande quanto o castelo[n]se forma apenas quando os desejos[n]são distorcidos ao extremo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Portanto, em vez de muitos[n]Palácios individuais, o público em geral tem[n]um gigantesco Palácio compartilhado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]E é aí que nos[n]encontramos... I Mementos.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Agora que você mencionou, este lugar[n]parece um pouco diferente do[n]Kamoshida Palace...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Quando você diz "compartilhado"... você quer[n]dizer que as pessoas estão todas aqui? Mesmo que[n]não se conheçam?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Pense nisso como[n]o inconsciente coletivo...[n][f 1 3 65535][w][e]

[msg MSG_012_5_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Não, esqueça.[n]Você não seria capaz de descobrir.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Então você está dizendo que...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Através deste lugar, podemos[n]acordar os corações mesmo[n]daqueles que não têm um Palácio?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Exatamente! Mas o processo[n]é um pouco diferente.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Mas este lugar parece realmente[n]enorme! Como vamos vasculhar[n]tudo a pé?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Finalmente chegou a hora...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Morganaaaa... transformaçãoee![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Venha, Panther. Senhoras primeiro.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Um ônibus...!?![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Louco![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Graças à forma como[n]a cognição toma forma no Metaverso,[n]além de um pouco de prática.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Não é tão diferente da maneira como[n]você se transforma.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Mudar de roupa é uma coisa, mas…[n]transformar-se em um veículo[n]é apenas outra galáxia![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Por alguma razão, o "ônibus gato"[n]é um conhecimento difundido[n]com o público em geral.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Mas por que um ônibus?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]...Não faço ideia.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Espere, por que você não chegou[n]ao castelo!?![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Eu faria se pudesse![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Mas o castelo era apertado, cheio[n]de escadas, e coisas assim não dá[n]andar em cima de um lustre![n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Oi Skull! Damas primeiro![n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Pare de empurrar! É perigoso![n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Panther, fique quieto![n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Todos a bordo! Vamos![n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]Por que vocês estão todos sentados lá atrás? Eu[n]sou um ônibus, sabe?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]Eu não vou a lugar nenhum a menos que alguém[n]assuma o volante.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Você não pode dirigir sozinho!?![n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]Você sabe dirigir?[n][f 1 3 65535][w][e]

[sel SEL_037_0_0 top]
[s]Só em videogames...[e]
[s]Eu não tenho uma licença.[e]
[s]Vou te mostrar alguns movimentos.[e]

[msg MSG_038_0_0 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]É um pouco preocupante, mas deixo o fardo para[n]você. Não tenho experiência mesmo em videogames.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]Você provavelmente é ainda mais habilidoso[n]do que eu.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]É ISSO que te preocupa?[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]Ei, quem se importa. Estamos[n]dirigindo um ônibus felino no Metaverso.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]Hum, segurança em primeiro lugar,[n]Ok?[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]É melhor você não bater[n]minha cara bonita na parede,[n]claro?!?[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]Tudo bem então, o volante é[n]todo seu![n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]Ligue o motor primeiro![n]Você não pode dirigir se estiver[n]desligado![n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][vp 8 0 0 55 65535 0]Ah cara, que chatice...[n]Onde estão as chaves dessa coisa?[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 56 65535 0]Para que você precisa de uma chave!?![n]Há um interruptor logo[n]abaixo do volante.[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 57 65535 0]Então você me faz cócegas![n]Mais abaixo! Mais abaixo![n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 58 65535 0]Ah, aqui...[n]Que prazer...[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][vp 8 0 0 59 65535 0]Uh, os que eu ouço estão ronronando...?[n]Que tipo de ônibus desviado![n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 60 65535 0]Não subestime meu[n]motor cat.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 61 65535 0]Estamos a todo vapor![n]Hora de voar![n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][vp 8 0 0 62 65535 0]Ei, posso ver...[n]o metrô?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 63 65535 0]É meio confuso, mas...[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 64 65535 0]Lembra quando eu[n]te disse anteriormente que o Metaverso e o[n]mundo real existem um sobre o outro?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 65 65535 0]No momento, estamos olhando para o mundo real. É[n]como para aquelas "aulas" dentro do castelo.[n][f 1 3 65535][w][e]

