[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Lembranças, hein? Ainda luto para entender aquele[n]lugar.[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Ah, e o que era esse tipo de[n]barreira no final?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Não tenho certeza, mas acho que[n]aquela parede estava lá[n]por um motivo muito específico.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]No entanto, como é o Palácio[n]do público em geral...a opinião[n]das massas pode influenciá-lo.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Como você sabe de tudo[n]isso, Morgana?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Minhas memórias ainda são[n]um pouco nebulosas sobre isso ...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]No entanto, devo descobrir o que[n]esconde nas profundezas dos[n]Mementos, custe o que custar.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Seja qual for o custo...?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]As lembranças não são apenas o[n]Palácio de Todos, mas também[n]a fonte de todos os Palácios.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Era uma vez, palácios com um único[n]senhor, como o de[n]Kamoshida, não existiam.[n][f 1 3 65535][w][e]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Portanto, se pudermos abordar[n]a causa raiz de[n]distorções, então minha aparência…[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Você precisava de alguém[n]para te salvar também...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]E-Eu só precisava de apoiadores...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Entendo... Então, é por isso que[n]você veio bisbilhotar[n]em nosso mundo.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Vou te ajudar. Espero que você possa[n]recuperar o que perdeu.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Conto com vocês.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Enfim, Morgana, você... você é um[n]boy? Ou você poderia ser[n]uma garota?[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]Ele é definitivamente um menino.[e]
[s]Deve ser uma menina.[e]
[s]Talvez seja um ônibus?[e]

[msg MSG_013_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Sim, concordo... só queria[n]ter certeza, nunca se sabe.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Pode até ser muito[n]velho. E se ele feder, como[n]velhos fazem?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Pare com isso...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Bem, Morgana pode ser terrivelmente sufocante às[n]vezes.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Se assim for, então é melhor[n]se apenas continuarmos amigos.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]É mútuo...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Isso também é possível![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Eu gostaria de dizer não, mas...[n]eu realmente não tenho certeza.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 3 301 1][vp 8 0 0 28 65535 0]Por que não!?![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]No entanto, sou claramente homem![n][f 1 3 65535][w][e]

[msg MSG_022_5_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Quer dizer, eu...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]...O que é?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Não... não é nada.[n]Vamos mudar de assunto![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]De qualquer forma, agora sabemos que[n]é possível fazermos pequenos[n]despertares do coração nos Mementos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Se encontrarmos alguma pista interessante, pode[n]valer a pena dar uma olhada nela para praticar.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Infelizmente, não havia mais nada[n]de interesse no site...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Aposto que ficaríamos impressionados,[n]se despertássemos alguns VIPs e[n]espalhassemos o nome dos Ladrões.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Afinal, os peixes grandes são nosso[n]objetivo principal.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]Primeiro você deve fazer[n]passar nos exames.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]eu tenho que estudar...[n][f 1 3 65535][w][e]

[msg SYS_032_0_0]
[s][vp 1 0 0 0 0 0]Agora você pode ir para os Mementos![n][w][e]
[s][vp 1 0 0 0 0 0]Aqui você pode despertar os corações de[n]pequenos criminosos que não têm[n]seu próprio palácio.[n][w][e]
[s][vp 1 0 0 0 0 0]Por enquanto, seja paciente e aguarde o próximo[n]objetivo.[n][w][e]

