[msg MSG_000_0_0 [Ryuji]]
[s][f 4 16 3 3 301 65535 65535][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Os Phantom Thieves que viajam de[n]trem... Assim como eu faço[n]todos os dias para ir à escola.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]O trem é a maneira mais rápida de chegar lá. E[n]então, animais de estimação são permitidos a[n]bordo.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][f 4 16 3 3 301 1 65535][vp 8 0 0 3 65535 0]Ei, quem você está chamando de animal!?![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Cala-te meu! Olha, nós não pagamos a taxa do[n]animal de estimação.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Eu sou aquele que te guia![n]Você deveria me chamar de "Mestre"![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Garotinha ingênua]]
[s][vp 8 0 0 6 6 0]Oooh, gatinho![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Nossa...![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Garotinha ingênua]]
[s][vp 8 0 0 8 6 0]É o seu animal de estimação, senhor?[n]Eu ouvi ele miando![n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]É um bicho de pelúcia.[e]
[s]Você imaginou.[e]
[s]Ele é apenas um monstro.[e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Sim, é apenas um brinquedo.[n]Se você esmagar a cabeça dele, ele miará.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Garotinha ingênua]]
[s][vp 8 0 0 10 6 0]Mas eu vi a cabeça saindo[n]do saco... Não é um gatinho?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]É... hum... só um brinquedo![n]Se você esmagar a cabeça dele, ele vai miar.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Garotinha ingênua]]
[s][vp 8 0 0 12 6 0]Que monstro...?[n]Não é um gatinho?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]É... hum... só um brinquedo![n]Se você esmagar a cabeça dele, ele vai miar.[n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Ouviu isso, [f 4 2]?[n]Pressione a cabeça dele.[n][f 1 3 65535][w][e]

[msg MSG_013_7_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Tudo isso é um absurdo...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]M-Miau...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Garotinha ingênua]]
[s][vp 8 0 0 17 6 0]Wowweeeee! Ainda! De novo![n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]Eu pressiono suavemente.[e]
[s]Eu pressiono com força.[e]
[s]Vá esmagando o botão.[e]

[msg MSG_017_0_0 [Morgana]]
[s][bup 0 3 8 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Purrr...[n][f 1 3 65535][w][e]

[msg MSG_017_5_0 [Morgana]]
[s][bup 0 3 8 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Mia... Miao...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Garotinha ingênua]]
[s][vp 8 0 0 20 6 0]Hahaha, que fofo![n]Quero ouvir de novo![n][f 1 3 65535][w][e]

[msg MSG_018_5_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Cara...o gato tá babando...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Miau?!?[n][f 1 3 65535][w][e]

[msg MSG_019_5_0 [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]...Bleahhh![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Garotinha ingênua]]
[s][vp 8 0 0 24 6 0]Hahaha, que gritinho engraçado![n]quero ouvir de novo![n][f 1 3 65535][w][e]

[msg MSG_020_5_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Acho...que vou vomitar...[n][f 1 3 65535][w][e]

[msg MSG_020_7_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Fale baixo seu idiota![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Mia... Miaoaoaoaoaoaoaoaoa![n][f 1 3 65535][w][e]
[s][vp 8 0 0 28 65535 0]......[n][f 1 3 65535][w][e]

[msg MSG_021_5_0 [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]...Bleahhh![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Garotinha ingênua]]
[s][vp 8 0 0 30 6 0]Hahaha, que hilário![n]Quero ouvir de novo![n][f 1 3 65535][w][e]

[msg MSG_022_5_0 [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Minha regurgitação aumentou...[n][f 1 3 65535][w][e]

[msg MSG_022_7_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Sério...?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Anúncio ferroviário]]
[s][vp 8 0 0 33 65535 0]Próxima parada: Shibuya.[n]As portas abrem à esquerda.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Oh, é a nossa parada![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Bem, até mais! Tchau tchau![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Garotinha ingênua]]
[s][vp 8 0 0 36 65535 0]Mm-mh! Tchau tchau![n][f 1 3 65535][w][e]

