[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]The deadline's tomorrow...[n]We gonna be OK?[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]The pictures are gone. He has no[n]avenue to threaten us anymore.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]That is, if we're able to trust[n]what Kaneshiro said.[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Don't say such scary stuff.[n][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][f 5 14]We can't relax just yet.[n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]He may still end up released[n]from police custody...[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]For real!?[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]That is, unless they have decisive[n]evidence like a confession.[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]It'll be fine.[e]
[s]I'm worried...[e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]True, there does seem to[n]be some movement.[n][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][f 5 14]But there does at least seem[n]to be some movement.[n][w][e]

[msg MSG_011_0_0 [Makoto]]
[s][f 5 14]Sis actually sent me a message[n]saying she won't be home tonight.[n][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][f 5 14]There's a chance that the police[n]have found their breakthrough.[n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]Oooh, does that mean it happened!?[n][w][e]

[msg MSG_014_0_0 [Ann]]
[s][f 5 14]The timing is perfect. I guess[n]let's just hope for the best?[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14][f 5 15]I'm gonna stay up all[n]night watching the[n]news to find out![n][w][e]

