[msg MSG_000_0_0 [Haru]]
[s][f 5 14]Can you meet up now?[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]There's a lot I want[n]to talk to you about...[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]I'll be by the Big Bang[n]Burger in Shibuya.[n][w][e]

[msg MSG_003_0_0 [Haru]]
[s][f 5 14]If you don't mind, I'd like[n]it if you could come see me.[n][f 5 15][w][e]

[msg MSG_LAST_GREETING_DOOR_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]You haven't talked to either of them[n]yet. Do you still want to go out and[n]meet with Haru?[n][f 1 3 65535][w][e]

[msg MSG_LAST_GREETING_DOOR_0_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]You haven't talked to Futaba yet.[n]Do you still want to go out and meet[n]with Haru?[n][f 1 3 65535][w][e]

[msg MSG_LAST_GREETING_DOOR_0_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]You haven't talked to the chief yet.[n]Do you still want to go out and meet[n]with Haru?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Do you want to go see Haru?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Go right away[e]
[s]Decide later[e]

