[msg MSG_000_0_0 [Haru]]
[s][f 5 14]Hey, why don't we try asking[n]Futaba-chan to look into the culprit[n]behind the psychotic breakdowns?[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]That's a great idea! Why[n]didn't I think of that?[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Hm, I suppose Futaba's[n]ability to process information[n]is truly world-class, after all.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Damn you're smart, Haru![n][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][f 5 14]I already tried.[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]And?[e]
[s]Did you find anything?[e]

[msg MSG_006_0_0 [Futaba]]
[s][f 5 14]I know so much now, it's hard[n]to make heads or tails of it.[n][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][f 5 14]Suspicious people appear, then[n]they disappear. It's been that,[n]over and over again.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]So they are manipulating[n]information to keep anyone[n]from reaching the truth...[n][w][e]

[msg MSG_009_0_0 [Futaba]]
[s][f 5 14]Well, there's one thing[n]I know for sure.[n][w][e]

[msg MSG_010_0_0 [Futaba]]
[s][f 5 14][f 5 15]Whoever we're going against[n]now is more dangerous than[n]we can possibly imagine.[n][w][e]

