[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]Things're getting really[n]crazy online.[n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]The Phantom Thieves have been[n]trending all over the country.[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]Not a day passes that I don't[n]hear people talking about the[n]Phantom Thieves in the city too...[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]That just means people are really[n]starting to count on us, right?[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]This fervor may be too extreme.[n]It is a dangerous omen.[n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]We could face great danger[n]if anyone manages to discover[n]our true identities.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Don't scare us like that![n]Ain't no way somebody's[n]gonna figure that out![n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]Either way, this excitement has[n]definitely piqued the public's[n]interest in the Phantom Thieves.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]We'll need to be even more[n]careful from now on.[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Why do we gotta be the[n]ones who sneak around?[n]It don't make sense...[n][w][e]

