[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Yo, I'm thinking of heading[n]over to our hideout tomorrow.[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]I'm really in the mood to[n]blow off some steam.[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]How about we meet up and[n]play some games together!?[n][w][e]

[msg MSG_002_1_0 [Ryuji]]
[s][f 5 14]Oh, don't worry about me if[n]you got stuff to do. I can[n]keep myself busy.[n][f 5 15][w][e]

[msg MSG_002_2_0 [Ryuji]]
[s][f 5 14]Oh, don't worry about me if[n]you got stuff to do. I can[n]keep myself busy.[n][w][e]

[sel SEL_003_0_0 top]
[s][f 5 14]I don't have a console.[e]
[s]I'm too poor for that.[e]
[s]I don't have a TV.[e]

[sel SEL_003_0_0_nonTV top]
[s][f 5 14]I'm too poor for that.[e]
[s]I don't have a TV.[e]

[sel SEL_003_0_0_nonGame top]
[s][f 5 14]I don't have a console.[e]
[s]I'm too poor for that.[e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]For real...?[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Well, I guess it ain't surprising[n]knowing where you live. Later![n][f 5 15][w][e]

[msg MSG_MORGANA_GAME [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1192 65535 0]People tend to gather over at your place,[n]so you might want to at least invest in a[n]game console...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Maybe the secondhand shop down the[n]street has one. You should check there[n]when you have time.[n][w][e]

[msg MSG_MORGANA_TV_NotSet [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I hope that TV you ordered gets here[n]soon...[n][f 1 3 65535][w][e]

[msg MSG_MORGANA_NoHaveTV [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1170 65535 0]A TV, huh... Too bad we can't use the[n]one on the first floor.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Look at all this junk, though... Maybe[n]you'd find a TV in here if you cleaned[n]up a little.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Mkay, seeya tomorrow![n][f 5 15][w][e]

[msg MSG_999_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1020 65535 0]Ryuji's coming over tomorrow, huh?[n]It's going to be noisy all day...[n][f 1 3 65535][w][e]

