[msg MSG_000_0_0 [Hifumi]]
[s][f 5 14]Would you help me in[n]developing a new move?[n][w][e]

[msg MSG_001_0_0 [Hifumi]]
[s][f 5 14]It should be a good[n]experience for you as well.[n][w][e]

[msg MSG_002_0_0 [Hifumi]]
[s][f 5 14]If you're free, please[n]come to the church.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Hifumi seems to be waiting for you at[n]the church. Wanna go see her?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Go right away[e]
[s]Decide later[e]

[sel SEL_002 top]
[s][f 5 14]I'll be right there.[e]

[msg MSG_REACTION [Hifumi]]
[s][f 5 14]OK, I'll be waiting.[n][f 5 15][w][e]

[msg MSG_CORP_PLAY_CHECK1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Hifumi seems to be waiting for you at[n]the church. Wanna go see her?[n][f 1 3 65535][w][e]

[msg MSG_CORP_PLAY_CHECK2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Nobody thinks you're alive at this point,[n]so it should be okay as long as you're[n]careful.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Hifumi seems to be waiting for you at[n]the church. Wanna go see her?[n][f 1 3 65535][w][e]

