[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]I called Sojiro and he seemed OK![n][w][e]

[msg MSG_000_5_0 [Futaba]]
[s][f 5 14]So, I have a proposal.[n]Let's spend Christmas Eve together.[n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]I wanna get some cake[n]and roasted chicken and[n]go to your room.[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Understood.[e]

[msg MSG_020_0_0 [Futaba]]
[s][f 5 14]!!![n][w][e]

[msg MSG_021_0_0 [Futaba]]
[s][f 5 14]I'm still in Shibuya. Let's[n]meet up soon. Already kinda[n]sick of these crowds...[n][f 5 15][w][e]

