[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Come train with me![n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]There's something I wanna[n]talk to you about too.[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]I'm at the arcade in Shibuya,[n]so lemme know when you're here.[n][w][e]

[msg CHAT_NOREACTION_MSG [Ryuji]]
[s][f 5 14]I was waiting for you![n]I'll invite you again.[n]Come next time, OK?[n][w][e]

[msg CHAT_REACTION_MSG [Ryuji]]
[s][f 5 14]OK. I'll wait here, then.[n][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]So, what do you plan on doing? Are you[n]going to take Ryuji up on his invitation?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Head over immediately[e]
[s]Check bond with Ryuji[e]
[s]Respond later[e]

[sel SEL_002 top]
[s][f 5 14]I'm on my way.[e]

[msg MND_COOP_DOUZOKUSEI]
[s]I should be able to deepen[n]our bond since I have [clr 1][var 5][clr 27][n]of the [var 2] arcana...[n][w][e]

