[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Wanna send the calling card?[n][w][e]

[msg MSG_000_0_1 [Ryuji]]
[s][f 5 14]We know the route to[n]the Treasure now.[n][w][e]

[msg MSG_000_0_2 [Ryuji]]
[s][f 5 14]Couldn't hurt to get it out[n]of the way sooner, right?[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]So, what will it be? Should we assemble[n]at the hideout and send the calling card?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Meet up[e]
[s]Decide later[e]

[sel SEL_002 top]
[s][f 5 14]Let's send the calling card.[e]

[msg MSG_REACTION [Ryuji]]
[s][f 5 14]Yeah! I'm getting pumped up.[n][w][e]

[msg MSG_REACTION_02 [Ryuji]]
[s][f 5 14]I'll be at the hideout soon.[n][f 5 15][w][e]

