[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]You free today?[n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]Can you come with me?[n]There's somewhere I want to go.[n][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]I'll be waiting in[n]front of Leblanc.[n][w][e]

[msg CHAT_NOREACTION_MSG [Futaba]]
[s][f 5 14]I waited for you...[n]I'll ask again another[n]time, so join me then.[n][w][e]

[msg CHAT_REACTION_MSG [Futaba]]
[s][f 5 14]K. Come back quickly.[n][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]So, what's the plan? Will you take[n]Futaba up on her invitation?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Head over immediately[e]
[s]Check bond with Futaba[e]
[s]Respond later[e]

[sel SEL_002 top]
[s][f 5 14]I'm on my way.[e]

