[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Hm, there has been no sign yet of[n]Kaneshiro acting on his threat.[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]He prolly thinks his money's[n]just gonna come rolling in.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]He does have the upper hand[n]on us, after all...[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]If that picture got out, who knows what[n]would end up happening to [f 4 2]...[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Guess worst-case scenario'd[n]be he gets expelled.[n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]No, there is a more serious[n]alternative... He's currently[n]under probation, meaning...[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]...I'm so sorry. This whole[n]situation is my fault.[n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]C'mon, stop that. I mean,[n]you're the one who's in the[n]most trouble right now.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]My sister is a prosecutor... This[n]will surely be a problem for her[n]as well. What should I do...?[n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Kaneshiro must surely be taking[n]that aspect into account too...[n][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]We need to stop him.[e]
[s]Let's change his heart.[e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14]For sure. Even the police are[n]having trouble with that bastard.[n]We'll be heroes if we catch him!![n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14]High risk, high reward...[n][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][f 5 14]You're all so positive...[n][w][e]

[msg MSG_014_0_0 [Yusuke]]
[s][f 5 14]Hm... In a way, your recklessness[n]is the only reason we are now able[n]to pursue this change of heart.[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14]Totally. We're in deep shit,[n]so we're gonna do whatever[n]we can to get out of it.[n][w][e]

[msg MSG_016_0_0 [Makoto]]
[s][f 5 14]I... never thought of things[n]in that way before.[n][w][e]

[msg MSG_017_0_0 [Yusuke]]
[s][f 5 14]It is quite strange hearing[n]something so positive from Ryuji.[n][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][f 5 14]Shuddup![n][w][e]

[msg MSG_019_0_0 [Ann]]
[s][f 5 14][f 5 15]All right, Leader! You can[n]decide when we meet up![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]When your position changes, your view[n]of the world changes too. It's a shift in[n]cognition.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 2 0 0]In any case, we're in big trouble if we[n]can't change Kaneshiro's heart. Let's[n]do this.[n][f 1 3 65535][w][e]

