[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]Aren't we going to the Palace?[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]I'd like to know what your[n]plans are for today.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Well, what do you want to do? Should we[n]meet up at the hideout and head into[n]the Palace?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Meet up[e]
[s]Not today[e]
[s]Decide later[e]

[sel SEL_002 top]
[s][f 5 14]Let's infiltrate the Palace.[e]
[s]Not today.[e]

[msg MSG_REACTION [Makoto]]
[s][f 5 14]All right. I'll head over[n]to the hideout immediately.[n][f 5 15][w][e]

[msg MSG_REACTION_02 [Makoto]]
[s][f 5 14]You're planning this out, correct?[n][w][e]

[msg MSG_REACTION_03 [Makoto]]
[s][f 5 14]You should gather everyone[n]once you have a plan.[n][w][e]

[msg MSG_REACTION_04 [Makoto]]
[s][f 5 14]In the meantime, I'll[n]do some work at the[n]student council room.[n][w][e]

[msg MSG_REACTION_05 [Makoto]]
[s][f 5 14]Come by if you need anything.[n][f 5 15][w][e]

