[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]How are the Phantom Thieves doing?[n]I've been thinking about a lot of[n]different ways to help you out.[n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]On that note, I have a report[n]to make. Are you free today?[n][w][e]

[msg CHAT_NOREACTION_MSG [Mishima]]
[s][f 5 14]Was this a bad time?[n]I'll invite you another time.[n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]I'll be wandering around Akihabara,[n]so feel free to call out to me![n][w][e]

[msg CHAT_REACTION_MSG [Mishima]]
[s][f 5 14]OK! I'll be waiting![n][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Well, are you going to accept Mishima's[n]invitation?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Head over immediately[e]
[s]Check bond with Mishima[e]
[s]Respond later[e]

[sel SEL_002 top]
[s][f 5 14]I'll head over now.[e]

