[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]So, what kinda person would be[n]a bigger target than Madarame?[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Hmmm...[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]I wonder...[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]I guess it'd have to be someone[n]who's the talk of the town?[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]That's quite a vague[n]prerequisite...[n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]Don't we have any[n]more specific ideas?[n][w][e]

[sel SEL_006_0_0 top]
[s][f 5 14]A crooked politician.[e]
[s]A famous celebrity.[e]
[s]An evil overlord.[e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Ah, yes. That is an[n]interesting line of thought.[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]Ooh, that might be a good one![n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]Dude, this ain't some[n]kinda video game![n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14]Either way, we'll need a lead[n]before we can begin anything.[n][w][e]

[msg MSG_011_0_0 [Ann]]
[s][f 5 14]We'll just have to look[n]for that as we go...[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14][f 5 15]If only there was a big target[n]just lying around for us...[n][w][e]

