[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Shall we send our calling card?[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]We know where the Treasure is,[n]and the sooner the better.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]We should gather at the hideout[n]as soon as possible.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]So, what will it be? Should we assemble[n]at the hideout and send the calling card?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Meet up[e]
[s]Decide later[e]

[sel SEL_002 top]
[s][f 5 14]Let's send the calling card.[e]

[msg MSG_REACTION [Yusuke]]
[s][f 5 14]Understood.[n][w][e]

[msg MSG_REACTION_02 [Yusuke]]
[s][f 5 14]I'll head to the hideout immediately.[n][f 5 15][w][e]

