[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Did you find any clues?[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]I have a name.[e]
[s]I'll tell you tomorrow.[e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]You did it![n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]Considering how you're trying to[n]keep us in suspense, I expect it[n]will be good news.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Well then, let's meet up[n]at the hideout tomorrow![n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]Understood.[n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]Ryuji seems to be absent from[n]this conversation. Should we[n]contact him separately?[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14][f 5 15]I'm sure he'll figure it out[n]when he checks his phone later.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 8 0 0]We're pretty much already in Kaneshiro's[n]Palace![n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 9 0 0]That was surprisingly easy![n][f 1 3 65535][w][e]

