[msg MSG_011_0_0 [Kasumi]]
[s][f 5 14]Hello, Senpai.[n][w][e]

[msg MSG_012_0_0 [Kasumi]]
[s][f 5 14]I couldn't really say much[n]out loud at school, but...[n][w][e]

[msg MSG_013_0_0 [Kasumi]]
[s][f 5 14]I just wanted to let you know[n]again that I'm glad you're safe.[n][w][e]

[msg MSG_014_0_0 [Kasumi]]
[s][f 5 14]...You remember the promise[n]we made on the roof?[n][w][e]

[sel SEL_015_0_0 top]
[s][f 5 14]Of course.[e]
[s][f 5 14]What was it again?[e]

[msg MSG_016_0_0 [Kasumi]]
[s][f 5 14]Really!?[n][w][e]

[msg MSG_016_1_0 [Kasumi]]
[s][f 5 14]You don't remember...!?[n][w][e]
[s][f 5 14]Well, I guess I can't blame you.[n]Considering everything else you[n]had to deal with, I mean.[n][w][e]
[s][f 5 14]We promised we'd go somewhere[n]together once things settled down.[n][w][e]

[msg MSG_017_0_0 [Kasumi]]
[s][f 5 14]I was so happy this morning—[n]I invited you without really[n]thinking...[n][w][e]
[s][f 5 14]But it looks like we can make good[n]on that promise by visiting the[n]shrine.[n][w][e]
[s][f 5 14]...Thank you for coming back okay.[n][w][e]

[sel SEL_018_0_0 top]
[s][f 5 14]Sorry to worry you.[e]
[s][f 5 14]I think we're okay.[e]

[msg MSG_019_0_0 [Kasumi]]
[s][f 5 14]You don't have to apologize![n]I just wish I could've done more[n]to help...[n][w][e]

[msg MSG_019_1_0 [Kasumi]]
[s][f 5 14]You only "think" so? That's[n]kind of worrying...[n][w][e]
[s][f 5 14]I'm just hoping nothing else[n]crazy happens.[n][w][e]

[msg MSG_020_0_0 [Kasumi]]
[s][f 5 14]As soon as exams are over, I'll be[n]going to a local training camp.[n][w][e]
[s][f 5 14]Honestly, I wasn't sure I should[n]go. After all, you were going[n]through so much...[n][w][e]
[s][f 5 14]But now I don't have to worry![n]I can finally focus on my training![n][w][e]
[s][f 5 14][f 5 15]Sorry to bother you when we're[n]busy with exams. Talk to you later![n][w][e]

[msg MSG_END_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Sounds like we really had Yoshizawa[n]worried.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Just wish we could get the general public[n]to change their minds about us, too...[n][f 1 3 65535][w][e]

