[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Everyone's comments used to be[n]so encouraging, but now they're[n]actually kinda frightening...[n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]This is utter chaos.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]The public dislike of Okumura[n]has grown exponentially as well.[n]How are you holding up, Haru?[n][w][e]

[msg MSG_003_0_0 [Haru]]
[s][f 5 14]We've been receiving anonymous[n]threats almost every day now...[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]That's scary...[n][w][e]

[msg MSG_005_0_0 [Haru]]
[s][f 5 14]But our security is tight, so[n]it's been OK so far.[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]I believe things will calm down[n]once we finish this, Haru.[n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]And what about us? Are we gonna[n]get all popular and shit again?[n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Let us not concern ourselves[n]with that for now. I only pray[n]that things calm down.[n][w][e]

