[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]You remember that[n]Mementos request?[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]We all agreed on that, right?[n]We still haven't finished it.[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]We don't know when the next[n]big target will show up.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Let's take care of it.[n]We can get some exercise too.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Oh yeah, we still haven't finished[n]Mishima's request.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]If we're going to Mementos, will you[n]have everyone gather at the hideout?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Meet up[e]
[s]Decide later[e]

[sel SEL_002 top]
[s][f 5 14]Round everyone up.[e]

[msg MSG_REACTION [Ryuji]]
[s][f 5 14]Cool! Let's meet up at the hideout![n][f 5 15][w][e]

