[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]I've been trying to think of[n]ways to support you all, but[n]I haven't had any good ideas.[n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]I'm in the classroom right now,[n]but it's boring by myself. Want[n]to hang out if you're free?[n][f 5 15][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]I'm on Central Street in Shibuya,[n]but it's boring by myself. Want[n]to hang out if you're free?[n][f 5 15][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][f 5 14]I'm in Shinjuku, but it's[n]boring by myself. Want to[n]hang out if you're free?[n][f 5 15][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][f 5 14]I'm in Akihabara, but it's[n]boring by myself. Want to[n]hang out if you're free?[n][f 5 15][w][e]

[msg MSG_REACTION [Mishima]]
[s][f 5 14]Thanks! I'll be waiting.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]So, what's it going to be? Do you want[n]to go see Mishima?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Go see him[e]
[s]Respond later[e]

[sel SEL_002 top]
[s][f 5 14]I'll be right there.[e]

