[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Yo, you wanna go to the[n]post-festival party and[n]try to calm down?[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]We can't really decide on what[n]Akechi was saying anyways. I'm[n]still pretty pissed though...[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Well, Mishima's here with[n]me. You should join us.[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]I'll be there.[e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 5 14]All right! Let's get our[n]mind off this shit![n][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][f 5 14]Seeya at the gym.[n][f 5 15][w][e]

