[msg MSG_000_0_0 [Chihaya]]
[s][f 5 14]The stars dictate that today is[n]a very important day.[n][w][e]

[msg MSG_001_0_0 [Chihaya]]
[s][f 5 14]...I trust I don't need to[n]tell you why...?[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Don't worry, I know.[e]

[msg MSG_020_0_0 [Chihaya]]
[s][f 5 14]It sounds like you have a[n]plan. I trust you, okay?[n][w][e]

[msg MSG_021_0_0 [Chihaya]]
[s][f 5 14]Then I'll be waiting for you.[n][f 5 15][w][e]

