[msg MSG_000_0_0 [Ann]]
[s][f 5 14]I found another request online[n]that's been resolved...[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]I was wondering about that.[n][w][e]

[msg MSG_001_5_0 [Makoto]]
[s][f 5 14]The problem seems to have[n]actually been fixed. It[n]can't be a fake.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]That means there is someone[n]else heading into Mementos.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]This makes me think of when[n]we were first getting started[n]as the Phantom Thieves.[n][w][e]

[msg MSG_003_5_0 [Ryuji]]
[s][f 5 14]All of a sudden Morgana just[n]decided to take us to Mementos.[n][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][f 5 14]Wait a second, could this be...[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]Morgana and Haru.[e]
[s]It's just a prank.[e]
[s]We can't lose to them.[e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Yeah, that's the only[n]logical conclusion.[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]It's hard to really think that[n]anymore. Requests are actually[n]being solved, remember?[n][w][e]

[msg MSG_007_5_0 [Makoto]]
[s][f 5 14]Maybe Morgana is taking[n]Okumura-san into Mementos.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]What good would it do to compete?[n][w][e]

[msg MSG_008_5_0 [Makoto]]
[s][f 5 14]What I mean is, I think[n]Morgana is taking Okumura-san[n]with him into Mementos.[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]For real? Ain't people[n]gonna figure out what's[n]going on though?[n][w][e]

[msg MSG_009_5_0 [Ryuji]]
[s][f 5 14]We never leave responses or[n]shit like that. They're[n]totally standing out.[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]I don't think anybody's noticed[n]yet, but it would be bad if they[n]tried to look into it.[n][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][f 5 14]Morgana and Haru could[n]be easily traced via the[n]network log.[n][w][e]

[msg MSG_011_5_0 [Futaba]]
[s][f 5 14]I don't think either of them[n]really understand how this works.[n][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][f 5 14]If we leave them be, our[n]identities would come to[n]light in addition to theirs.[n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]We gotta stop 'em then. Makoto,[n]can't you get in touch with[n]Okumura-san or something?[n][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][f 5 14]I don't have her contact info.[n][w][e]

[msg MSG_014_5_0 [Makoto]]
[s][f 5 14]And thanks to the Personal[n]Information Protection Law,[n]her home number is private.[n][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][f 5 14]Then we will need to wait until[n]Monday? It would be better for[n]us to deal with this soon...[n][w][e]

[sel SEL_016_0_0 top]
[s][f 5 14]Let's go to her house.[e]
[s]Let's wait in Mementos.[e]

[msg MSG_017_0_0 [Ann]]
[s][f 5 14]But that's also the home of the[n]president. There'll probably be[n]guards and cameras and stuff...[n][w][e]

[msg MSG_018_0_0 [Makoto]]
[s][f 5 14]In addition, we're not fully[n]certain that Morgana and Haru[n]are the ones behind this yet.[n][w][e]

[msg MSG_018_5_0 [Ryuji]]
[s][f 5 14]Then wanna just stake out in[n]Mementos till we catch 'em?[n][w][e]

[msg MSG_018_7_0 [Makoto]]
[s][f 5 14]That would be the safest way...[n][w][e]

[msg MSG_019_0_0 [Ann]]
[s][f 5 14]You're joking, right? You just[n]want to stay there until they[n]decide to show up?[n][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 5 14]I think that's all we can do[n]though... If we wanna catch 'em,[n]that's prolly the best way.[n][w][e]

[msg MSG_021_0_0 [Futaba]]
[s][f 5 14]Man, that sounds super fun.[n][w][e]

[msg MSG_021_5_0 [Futaba]]
[s][f 5 14]Bring me some games, snacks,[n]soda, and some instant yakisoba![n][w][e]

[msg MSG_022_0_0 [Yusuke]]
[s][f 5 14]I will leave the cooking to you.[n]I request one soup dish paired[n]with five vegetable dishes.[n][w][e]

[msg MSG_023_0_0 [Ann]]
[s][f 5 14]Some skin lotion would be[n]great too. I want to keep[n]myself moisturized.[n][w][e]

[msg MSG_024_0_0 [Ryuji]]
[s][f 5 14]Bring that shit yourselves![n][w][e]

[msg MSG_025_0_0 [Makoto]]
[s][f 5 14]Anyway, let's all gather[n]in Mementos tomorrow morning.[n][w][e]

[msg MSG_025_5_0 [Makoto]]
[s][f 5 14][f 5 15]This might not be easy,[n]but let's do what we can.[n][w][e]

