[msg MSG_000_0_0 [Ann]]
[s][f 5 14]I just got a message from Shiho.[n]It sounds like Kayo suddenly[n]came to her with an apology.[n][w][e]
[s][f 5 14]And—get this—she said "I'll take[n]care of the volleyball team.[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]That's great news.[e]
[s]What a relief.[e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Yeah![n][w][e]
[s][f 5 14][f 5 15]I couldn't have done it without all[n]of you. Thanks for helping me.[n][w][e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'm glad to see Lady Ann's feeling better![n][f 1 3 65535][w][e]

[msg SYS_000_0_0]
[s]このチャットは没データです[n][w][e]

