[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Well, I went in for counseling.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]You're going soon too, right,[n][f 4 2]?[n][w][e]

[sel SEL_003_0_0 top]
[s][f 5 14]How'd it go?[e]
[s]It's gonna suck.[e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Hmm... Well, it honestly wasn't as[n]rough as I was expecting.[n][w][e]

[msg MSG_005_0_0 [Ann]]
[s][f 5 14]It's gonna suck more if we start[n]attracting attention for skipping it.[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]I think you should just go and[n]give it a shot.[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Dr. Maruki's easier to talk to[n]than you'd think.[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14][f 5 15]Okay, see you tomorrow.[n][w][e]

