[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]I've really started turning the[n]heat up on the forum! I put a[n]special post up and everything![n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]"The showdown between the just[n]Phantom Thieves and the global[n]organization Medjed is here!"[n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]Reactions have been great too.[n]Everyone is really engaged.[n][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][f 5 14]So far, most of the comments[n]have been pro-Phantom Thieves.[n][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][f 5 14]Most likely because of what[n]happened in the Kaneshiro case.[n][w][e]

[msg MSG_005_0_0 [Mishima]]
[s][f 5 14]Those on the other side say[n]Medjed are "hackers of justice."[n][w][e]

[msg MSG_006_0_0 [Mishima]]
[s][f 5 14]But there's nothing resembling[n]justice in what they do.[n][w][e]

[msg MSG_007_0_0 [Mishima]]
[s][f 5 14]Someday, I want the whole site to be[n]filled with pro-Thieves comments.[n][w][e]

[msg MSG_008_0_0 [Mishima]]
[s][f 5 14][f 5 15]I'm looking forward to when[n]that day finally arrives.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 13 0 0]He can look forward to whatever he[n]wants, but we have no means of striking[n]back against Medjed.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 14 0 0]We're gonna be in deep trouble if we[n]don't do something...[n][f 1 3 65535][w][e]

