[msg MSG_000_0_0 [Ann]]
[s][f 5 14]It's already a week[n]into December.[n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]Things suck online.[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]People in the city are only[n]talking about Shido as well.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Yeah, all the buzz about[n]Akechi's completely gone.[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Shido may have pressured for[n]media silence on the matter.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Why don't people get mad about[n]that shit!? It don't make sense![n][w][e]

[sel SEL_006_0_0 top]
[s][f 5 14]Elections are more important.[e]
[s]They only care about Shido.[e]
[s]They're not interested.[e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]That may be true, but still...[n][w][e]

[msg MSG_008_0_0 [Futaba]]
[s][f 5 14]It's not even that! Everyone just[n]latches on to the latest story![n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]It's irritating to think about,[n]but you're probably right.[n][w][e]

[msg MSG_010_0_0 [Haru]]
[s][f 5 14]I thought something similar[n]when Father collapsed.[n][w][e]

[msg MSG_011_0_0 [Haru]]
[s][f 5 14]As long as it doesn't involve[n]you, the news is nothing but[n]another form of entertainment.[n][w][e]

[msg MSG_012_0_0 [Haru]]
[s][f 5 14]For the general public, each[n]passing story is simply a new[n]means of killing time.[n][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][f 5 14]They consume each topic, then[n]discard it before moving on[n]to the next big thing...[n][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14]But I bet that's all gonna[n]change once they see Shido[n]have a change of heart![n][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][f 5 14][f 5 15]I hope so. We will just have to[n]wait with belief in our hearts.[n][w][e]

