[msg MSG_000_0_0 [Takemi]]
[s][f 5 14]Are you home? If there's[n]nothing wrong with you, then[n]let me come over and examine you.[n][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][f 5 14]Just kidding. I just[n]wanted to see you.[n][w][e]

[msg MSG_002_0_0 [Takemi]]
[s][f 5 14]Can I come over[n]tomorrow after work?[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]I'll be waiting.[e]

[msg MSG_020_0_0 [Takemi]]
[s][f 5 14]Glad to hear it.[n]I'm looking forward[n]to tomorrow.[n][f 5 15][w][e]

