[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14][f 5 19]I forgot to post the photo[n]I took today![n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14][f 5 18 275 1 1][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Hey, not bad![n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Right!? I'm a natural with this[n]candy photography stuff![n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]I'll hope for your sake that[n]was intended to be "candid"[n]photography.[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]It's a shame about the rain, but[n]at least it means today was a little[n]more memorable.[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Yeah! But next time we really[n]can't miss the fireworks![n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14]Agreed.[n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Still, it was almost impressive how[n]swiftly the weather turned terrible.[n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Perhaps one of us is simply fated[n]to bring rain wherever he goes...[n][w][e]

