[msg MSG_000_0_0 [Haru]]
[s][f 5 14]It's hard to stay calm when[n]all we can do is wait...[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]Oh yeah...[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]We still haven't finished that[n]request from the forum, right?[n][w][e]

[msg MSG_003_0_0 [Haru]]
[s][f 5 14]Completing requests is still[n]a way of reforming society.[n]Shall we take care of it?[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Oh yeah, we still haven't finished[n]Mishima's request.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]If we're going to Mementos, will you[n]have everyone gather at the hideout?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Meet up[e]
[s]Decide later[e]

[sel SEL_002 top]
[s][f 5 14]Let's take care of it.[e]

[msg MSG_REACTION [Haru]]
[s][f 5 14]OK! I'll head right[n]over to the hideout.[n][f 5 15][w][e]

