[msg MSG_000_0_0 [Takemi]]
[s][f 5 14]Have you been taking care [n]of your body?[n][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][f 5 14]A lot of my patients have [n]suddenly become ill lately...[n][w][e]

[msg MSG_002_0_0 [Takemi]]
[s][f 5 14]So you're OK? I can examine you,[n]if you'd like.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Takemi is waiting for you at the clinic.[n]You wanna go see her?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Go right away[e]
[s]Decide later[e]

[sel SEL_002 top]
[s][f 5 14]I'll be right there.[e]

[msg MSG_REACTION_01 [Takemi]]
[s][f 5 14]I see. OK, I'll be waiting then.[n][f 5 15][w][e]

[msg MSG_CORP_PLAY_CHECK1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Takemi is waiting for you at the clinic.[n]You wanna go see her?[n][f 1 3 65535][w][e]

[msg MSG_CORP_PLAY_CHECK2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Nobody thinks you're alive at this point,[n]so it should be okay as long as you're[n]careful.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Takemi is waiting for you at the clinic.[n]You wanna go see her?[n][f 1 3 65535][w][e]

