[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Hey, wanna go to Mementos?[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]They were saying something's[n]weird down there, right?[n][w][e]
[s][f 5 14]I wanna see what's happening,[n]so let's go check it out![n][f 5 15][w][e]

[msg MSG_REACTION [Ryuji]]
[s][f 5 14]All right! Let's meet up[n]at the hideout![n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Good plan. I think we should investigate[n]Mementos, too.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]What's the plan? Wanna call everyone[n]to the Hideout?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Meet up[e]
[s]Decide later[e]

[sel SEL_002 top]
[s][f 5 14]Let's all meet up.[e]

