[msg MSG_OKUMURA_MAEOKI [Mishima]]
[s][f 5 14]Hey, sorry for bringing this up[n]when things are so chaotic...[n][w][e]
[s][f 5 14]I know it's been tough after[n]what happened to President[n]Okumura and all...[n][w][e]
[s][f 5 14]But this is the perfect time[n]for smaller changes of heart to[n]restore your reputation.[n][w][e]
[s][f 5 14]Anyway, here's the info I have...[n][w][e]

[msg MSG_SIMEITEHAI_MAEOKI [Mishima]]
[s][f 5 14]Hey, sorry to bring this up now.[n]I know you have your hands full...[n][w][e]
[s][f 5 14]But [f 4 28] can do it.[n]I have faith in all of you.[n][w][e]
[s][f 5 14]Anyway, here's the info I have...[n][w][e]

[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]This one's important![n][w][e]
[s][f 5 14]Apparently this post was made[n]by someone with ties to the[n]banks and the finance sector.[n][w][e]
[s][f 5 14]The target this time is a guy[n]who never pays back his loans.[n][w][e]
[s][f 5 14]It sounds like he might be[n]involved in organized crime too.[n]He could be dangerous.[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]How dangerous?[e]
[s]Sounds interesting.[e]
[s]Organized crime?[e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]Well, apparently even the police[n]are having trouble catching him.[n][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][f 5 14]Right? Apparently even the police[n]are having trouble catching him.[n][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][f 5 14]Well, apparently even the police[n]are having trouble catching him.[n][w][e]

[msg MSG_005_0_0 [Mishima]]
[s][f 5 14]He keeps changing his name and[n]appearance to elude them.[n][w][e]
[s][f 5 14]I guess he's basically the man[n]of a hundred faces. Not bad, huh?[n][w][e]
[s][f 5 14]According to one particular[n]post, he's currently going by[n]the name Fumio Akitsu.[n][w][e]
[s][f 5 14]I went ahead and made a warning[n]post about it... Is that OK?[n][w][e]
[s][f 5 14][f 5 15]Either way, I'm sure it'll be[n]easy for [f 4 28]![n][w][e]

[msg MSG_quest49_MORGANA_SAY [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Wow, this is some good info, even for[n]Mishima![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Let's discuss whether or not we go after[n]this guy over at the hideout![n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Dummy scriptChat_249[e]

