[msg MSG_000_0_0 [Takemi]]
[s][f 5 14]So. Today's White Day, right?[n][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][f 5 14]Just a friendly reminder for my[n]forgetful little guinea pig.[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]I remembered.[e]

[msg MSG_020_0_0 [Takemi]]
[s][f 5 14]Oh yeah? Good.[n][w][e]

[msg MSG_021_0_0 [Takemi]]
[s][f 5 14]I'm out for a medical conference[n]today, so we can meet up in[n]Shibuya. See you.[n][f 5 15][w][e]

