[msg MSG_000_0_0 [Takemi]]
[s][f 5 14]You're leaving tomorrow, right? [n]You should stop by the clinic.[n][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][f 5 14]I have good news.[n][w][e]

[msg MSG_002_0_0 [Takemi]]
[s][f 5 14]And I want to see you, too.[n]I'll be waiting.[n][f 5 15][w][e]

[msg MSG_LAST_GREETING_DOOR_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]You haven't talked to either of them[n]yet. Do you still want to go out and[n]meet with Takemi?[n][f 1 3 65535][w][e]

[msg MSG_LAST_GREETING_DOOR_0_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]You haven't talked to Futaba yet.[n]Do you still want to go out and[n]meet with Takemi?[n][f 1 3 65535][w][e]

[msg MSG_LAST_GREETING_DOOR_0_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]You haven't talked to the chief yet.[n]Do you still want to go out and meet[n]with Takemi?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Do you want to go see Takemi?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Go right away[e]
[s]Decide later[e]

