[msg MSG_001_0_0 [Haru]]
[s][f 5 14]Thank you for[n]everything yesterday.[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]Because of you, I've been able[n]to take a new step forward.[n][w][e]

[msg MSG_003_0_0 [Haru]]
[s][f 5 14]No, not just me... but[n]Okumura Foods as well![n][w][e]

[msg MSG_004_0_0 [Haru]]
[s][f 5 14]Speaking of which, I just[n]received word about Big Bang[n]Burger's new product.[n][w][e]

[msg MSG_005_0_0 [Haru]]
[s][f 5 14]Takakura-san said that it's[n]the jumping-off point for a[n]new-look Okumura Foods.[n][w][e]

[msg MSG_006_0_0 [Haru]]
[s][f 5 14]Not only is he thinking about the[n]business, but he wants to carry[n]out my father's will as well.[n][w][e]

[msg MSG_007_0_0 [Haru]]
[s][f 5 14]I was so happy to hear that.[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]You did great, Haru.[e]
[s]The future is bright.[e]
[s]Your feelings got through.[e]

[msg MSG_009_0_0 [Haru]]
[s][f 5 14]Thank you. And you've been there[n]the whole time, encouraging me...[n][w][e]

[msg MSG_010_0_0 [Haru]]
[s][f 5 14]Yes, I'm certain it will become[n]a truly wonderful company.[n][w][e]

[msg MSG_011_0_0 [Haru]]
[s][f 5 14]You think so? Thank goodness...[n][w][e]

[msg MSG_012_0_0 [Haru]]
[s][f 5 14]I need to keep working hard[n]too so I can open my café![n][w][e]

[msg MSG_013_0_0 [Haru]]
[s][f 5 14]By the way, Big Bang Burger's[n]new product is going to be[n]made available... today.[n][w][e]

[msg MSG_014_0_0 [Haru]]
[s][f 5 14]It's called the White Sea[n]Burger. It's a white patty[n]made entirely of seafood.[n][w][e]

[msg MSG_015_0_0 [Haru]]
[s][f 5 14]It would be excellent[n]if you could give it[n]a try, [f 4 2]-kun.[n][w][e]

[sel SEL_016_0_0 top]
[s][f 5 14]Of course.[e]
[s]Sounds delicious.[e]

[msg MSG_017_0_0 [Haru]]
[s][f 5 14]I hear they're very confident[n]about it... If you don't mind,[n]I'd love to get your thoughts.[n][w][e]

[msg MSG_018_0_0 [Haru]]
[s][f 5 14]I hear they're very confident[n]about it... I hope it lives up[n]to your expectations.[n][w][e]

[msg MSG_019_0_0 [Haru]]
[s][f 5 14]...Oh my, look at the time.[n]I would love to talk more, but[n]I really should be going to bed.[n][w][e]

[msg MSG_020_0_0 [Haru]]
[s][f 5 14][f 5 15]Good night.[n][w][e]

