[msg MSG_000_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]By the way, when you introduce[n]yourself...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Be serious about it even if you're lying[n]to the class, okay? Do NOT say anything[n]unnecessary.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sharp-Eared Female Student]]
[s][vp 8 0 0 3 5 0]...You think that's him?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Short-Haired Female Student]]
[s][vp 8 0 0 4 6 0]Huh? The one in the rumors?[n][f 1 3 65535][w][e]

