[msg MSG_000_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Hm? What's wrong?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Is this a school?[e]
[s]Is this... a castle?[e]

[msg MSG_002_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]*sigh* Are you sure you're okay?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Also... it seems like people are already[n]talking about you, but I'm not the one[n]who told them.[n][f 1 3 65535][w][e]

[msg MSG_002_5_0 [Kawakami]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 109 16 300 1][vp 8 0 0 4 65535 0]I can't even catch a break... Why do I[n]have to deal with this?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]You should head straight home without[n]stopping by anywhere. Sakura-san[n]sounded pretty angry.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Oh, and about Sakamoto-kun. Don't get[n]involved—[n][f 1 2 90][e]

[msg MSG_005_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Speak of the devil...[n][f 1 3 65535][w][e]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]What do you want? I heard the police[n]caught you cutting classes today.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sakamoto]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Ugh... It was nothin'.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]And you haven't dyed your hair back to[n]black either...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sakamoto]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Sorry 'bout that.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sakamoto]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]...I'll be waitin' on the rooftop.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [(SE)川上 貞代]]
[s][vp 8 0 0 14 65535 0](わざとらしいため息)[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]See? That's why I don't want you getting[n]involved. Understood?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Why did you allow a student like him[n]to transfer here? He's already started[n]associating with Sakamoto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]A student with a criminal record, and[n]the culprit of an assault case.[n][f 1 3 65535][w][e]

[msg MSG_012_5_0 [Kamoshida]]
[s][bup 0 202 3 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]At this rate, it'd be pointless how much[n]I contribute to the school.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Principal]]
[s][bup 0 204 3 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Now, don't be like that...[n][f 1 3 65535][w][e]
[s][bup 0 204 0 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]This school counts on you,[n]Kamoshida-kun. You are our star.[n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Principal]]
[s][bup 0 204 3 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Still, a steady build-up is necessary[n]behind such brilliance as well.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Kamoshida]]
[s][bup 0 202 3 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]...Your troubles never seem to end,[n]do they, Principal Kobayakawa?[n][f 1 3 65535][w][e]
[s][bup 0 202 1 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]All right, I understand. I'll continue to[n]do my best to answer your expectations[n]of me.[n][f 1 3 65535][w][e]

