[msg MSG_000_0_0 [Kamoshida]]
[s][bup 0 202 1 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Hey there, Takamaki.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Things have been pretty dangerous lately[n]with all those accidents.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Sorry, I have a photoshoot today. It's for[n]the special summer issue, so I can't afford[n]to miss it...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Kamoshida]]
[s][bup 0 202 3 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Hey, now... Being a model's fine and[n]dandy, but don't work your pretty little[n]self to the bone.[n][f 1 3 65535][w][e]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]You mentioned you weren't feeling well,[n]right? Something about appendicitis?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Yes. I keep planning to go to the hospital,[n]but I've been too busy... Sorry to worry[n]you.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]You must be lonely too. I feel bad for[n]keeping your best friend at practice[n]so often.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Oh, and... be careful around that[n]transfer student.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]He's got a criminal record, after all.[n]If something were to happen to you...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]...Thank you.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Please excuse me.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kamoshida]]
[s][bup 0 202 2 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Tch...[n][f 1 3 65535][w][e]

