[msg MSG_000_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]First off... I'd like to begin by[n]congratulating you.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]To think our master would give words of[n]praise...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]You better treasure this moment, Inmate![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]You have encountered allies who share[n]your ideals, and you have found your[n]place in reality.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]The time has come... Your rehabilitation[n]will soon begin.[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]What rehabilitation?[e]
[s]I don't understand.[e]

[msg MSG_005_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]I shall explain it to you now...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 15 300 1][vp 8 0 0 7 65535 0]Just shut up and listen, Inmate![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]You have a special potential. However,[n]that must be refined into a useful power.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]It is weak now, but refining it shall grant[n]you the strength to stand against the[n]coming ruin.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]...That is the rehabilitation cast upon you.[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Coming ruin?[e]
[s]Strength?[e]

[msg MSG_009_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]It's time you learned something for once![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]There are various means by which you[n]may gain the power to resist the ruin.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Fighting Shadows and gaining experience[n]is one way.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]The fusion process I taught you prior is[n]another.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]This is all possible because of our master's[n]guidance, Inmate![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Though it may be presumptuous of us,[n]we have words of wisdom as well.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]When you're out in reality, you better[n]hone your relationships with those[n]you have contracts with![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Spending time with those people...[n]will lead to the cultivation of your[n]relationships with them.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]If you've got time to waste, you'd better[n]visit your contractors, Inmate![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]That is another source of power to evade[n]the ruin that our master has mentioned.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Thanks to the contracts you've formed,[n]your heart is steadily gaining the power[n]of opposition.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]It seems the rehabilitation is going well.[n]This is a truly joyous occasion...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]I shall grant you an ability befitting of[n]your newfound growth. Consider it a gift.[n][f 1 3 65535][w][e]

[msg MSG_019_5_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]May the devotion to your rehabilitation[n]grow even deeper.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]I have high hopes for you.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]...The time has come. Return to your brief[n]moments of rest.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]And don't forget to go talk to your[n]contractors, Inmate![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 1 0 0 0 0 0]I feel like my bond with Igor[n]is growing deeper...[n][f 1 3 65535][w][e]

