[sel YESNO_SEL top]
[s]Sim[e]
[s]Nao[e]

[msg MSG_001_0_0 [Loud Female Student]]
[s][f 4 23 1 805 3 10 0 0][vp 8 2 1 0 805 0]Ei, voce ouviu?[n]Outro homem[n]perguntou Takamaki-san novamente.[n][w][e]

[msg MSG_002_0_0 [Harsh Female Student]]
[s][f 4 23 1 806 3 10 0 0][vp 8 2 1 0 806 0]Ela o recusou, nao foi?[n]Ela provavelmente ja esta namorando[n]alguem. Sim, ela esta escondendo isso.[n][w][e]

[msg MSG_003_0_0 [Loud Female Student]]
[s][f 4 23 1 805 3 10 0 0][vp 8 2 1 0 805 0]Ouvi dizer que ela e muito alta[n]manutencao. Quem quer que ela[n]O namorado deve ter isso dificil.[n][w][e]

