[msg MSG_000_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Obrigado por me convidar- embora eu admito[n]que me sinto um pouco como se estivesse[n]invadindo...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 0 7 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Não há necessidade de modéstia. Depois de[n]tudo o que passamos, não há estranhos aqui.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Sim! Você realmente ajudou [f 4 2] fora também.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Nesse caso, aceitarei sua oferta.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Ei, eu realmente não consigo parar de Starin[n]'com aquela coisa que você está vestindo.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 1 7 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Heh... então também chamou sua atenção.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Aconteceu para pegar o meu enquanto eu[n]passeava pela cidade.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Comprei para mim como recompensa para o[n]final do ano.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 0 7 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]O que você acha? Sobre o lenço.[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]Parece ótimo em você.[e]
[s]É único.[e]
[s]Eu prefiro um lenço longo de malha.[e]

[msg MSG_008_0_0 [Yusuke]]
[s][bup 0 5 1 7 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Obrigada. Seu elogio é música para meus[n]ouvidos.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Eu não acho que ninguém além de você possa[n]fazer isso, Kitagawa-senpai.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 4 7 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]OHO... você reconheceu sua beleza única[n]também![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Eu diria que é um pouco único.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 0 7 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Suponho que a diferença é se você dá[n]importância à funcionalidade ou estética.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Bem, o que você escolher, apenas[n]certifique-se de não pegar um resfriado...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Esse bate-papo de moda está bem e tudo mais,[n]mas se você não cavar nessa soba em breve,[n]isso ficará encharcado em você.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][bup 0 5 0 7 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Ah sim. Me desculpe.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Obrigado pela comida.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 1 300 65535]É hora de Chow![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 1 300 1][vp 8 0 0 20 65535 0]Mmm! Tão bom![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Sakura-san, você fez esses macarrão, certo?[n][f 1 3 65535][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 24 0 11 6 42 5 100][vp 8 0 0 22 65535 0]Eles são incríveis! Você poderia abrir um[n]restaurante Soba![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Aw, obrigado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Eu fiz um pouco demais, então se alguém[n]quiser um refil- [n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Segundos, por favor![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Quão rápido você come!?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Você come muito mais do que eu assumi que[n]sim, Yoshizawa-san.[n][f 1 3 65535][w][e]

[sel SEL_023_0_0 top]
[s]O estômago dela está sem fundo.[e]
[s]Bem, ela é uma atleta.[e]

[msg MSG_024_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]A sério?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Enquanto é tão magro!?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]... Não sei se isso explica completamente o[n]que está acontecendo aqui.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0][f 4 1]-senpai, não os brigue tanto.[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 24 0 11 6 35 5 100][vp 8 0 0 32 65535 0]O apetite é totalmente normal.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Newscaster]]
[s][vp 8 0 0 33 65535 0]Notícias de última hora em nossa principal[n]história...[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Newscaster]]
[s][vp 8 0 0 34 65535 0]Após quase duas semanas de silêncio, o[n]escritório do promotor planeja avançar com[n]o maior caso do ano.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 35 65535 0]Eles anunciaram que avançarão na acusação de[n]Shido representativo por seus crimes[n]confessados.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Finalmente está acontecendo...[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Eu estava planejando contar a todos sobre[n]isso um pouco mais tarde. Este caso é tudo[n]graças ao testemunho de um certo homem.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Mas, pelo menos, posso compartilhar este[n]pedaço de boas notícias com você.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Yusuke]]
[s][bup 0 5 0 7 0][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]E isso seria...?[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]A mulher envolvida em [f 4 1]O caso de carga falsa de Kun finalmente se[n]apresentou e deu seu testemunho.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Eu não posso dizer com certeza ainda...[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]Mas seu registro criminal pode muito bem ser[n]derrubado.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]Sério!?[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Isso é maravilhoso![n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]Parabéns, Senpai![n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]Claro, isso é altamente confidencial,[n]entendeu?[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]Que ótimas notícias, [f 4 2].[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]Parece que realmente estaremos tendo um[n]feliz ano novo.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]Isto é incrível! É um bom final de vida real![n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [TV Commercial]]
[s][vp 8 0 0 51 65535 0]E depois disso: o especial de duas horas de[n]Ano Novo de "Tokyo Vice"![n][f 1 3 65535][w][e]
[s][vp 8 0 0 52 65535 0]Uma história emocionante cheia de alguns dos[n]rostos mais famosos da rede![n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Handsome Actor]]
[s][vp 8 0 0 53 65535 0]Eu nunca vou desistir...![n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]Eu tenho visto esse cara na TV o tempo todo[n]ultimamente.[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 55 65535 0]Ah, sim, ele é um modelo que virou ator.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 56 65535 0]Com uma figura como essa, posso ver como ele[n]ficou tão popular.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 0 57 65535 0]Então, ele é popular, não é?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 58 65535 0]Se eu fosse mais parecido com aquele humano,[n]talvez Lady Ann...[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Newscaster]]
[s][vp 8 0 0 59 65535 0]O ano está terminando em seus momentos[n]finais- vamos dar uma olhada em como as[n]pessoas estão gastando, em todo o país.[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 60 65535 0]Agora que estou pensando sobre isso, muito[n]com certeza aconteceu este ano.[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 61 65535 0]Direita? É como, quantos anos de nossas[n]vidas realmente vivíamos este ano?[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Yusuke]]
[s][bup 0 5 0 7 0][f 4 10 65535 0 0][vp 8 0 0 62 65535 0]Duvido que experimentemos algo parecido por[n]isso por algum tempo.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 63 65535 0]Bem, isso é apenas do meu ponto de vista,[n]mas eu realmente espero que seja esse o[n]caso.[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 65 65535 0]Acho que começando no próximo ano, apenas[n]seremos bons meninos e meninas na escola.[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 66 65535 0]Se for esse o caso, suponho que você poderá[n]lidar com a lição de casa das férias de[n]verão por conta própria- bem?[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 67 65535 0]Por favor, não vá lá, senpai...[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [(SE)主人公]]
[s][vp 8 0 0 0 65535 0](笑い声)[n][f 1 3 65535][w][e]

[msg MSG_055_0_0 [(SE)坂本 竜司]]
[s][vp 8 0 0 0 65535 0](笑い声)[n][f 1 3 65535][w][e]

[msg MSG_056_0_0 [(SE)高巻 ¸]]
[s][vp 8 0 0 0 65535 0](笑い声)[n][f 1 3 65535][w][e]

[msg MSG_057_0_0 [(SE)モルガナ]]
[s][vp 8 0 0 0 65535 0](笑い声)[n][f 1 3 65535][w][e]

[msg MSG_058_0_0 [(SE)喜多川 祐介]]
[s][vp 8 0 0 0 65535 0](笑い声)[n][f 1 3 65535][w][e]

[msg MSG_059_0_0 [(SE)新島 真]]
[s][vp 8 0 0 0 65535 0](笑い声)[n][f 1 3 65535][w][e]

[msg MSG_060_0_0 [(SE)佐倉 双葉]]
[s][vp 8 0 0 0 65535 0](笑い声)[n][f 1 3 65535][w][e]

[msg MSG_061_0_0 [(SE)奥村 春]]
[s][vp 8 0 0 0 65535 0](笑い声)[n][f 1 3 65535][w][e]

[msg MSG_062_0_0 [(SE)芳♀ かすみ]]
[s][vp 8 0 0 0 65535 0](笑い声)[n][f 1 3 65535][w][e]

[msg MSG_063_0_0 [(SE)新島 冴]]
[s][vp 8 0 0 0 65535 0](笑い声)[n][f 1 3 65535][w][e]

[msg MSG_064_0_0 [(SE)佐倉 惣治郎]]
[s][vp 8 0 0 0 65535 0](笑い声)[n][f 1 3 65535][w][e]

[msg MSG_065_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 68 65535 0]Muita coisa aconteceu nos últimos doze[n]meses...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 69 65535 0]Mas no final, temos que gastá-lo assim. Eu[n]quero acreditar que este foi um ótimo ano[n]para nós.[n][f 1 3 65535][w][e]

[msg MSG_066_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 70 65535 0]Sim.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 71 65535 0]Não tenho nenhuma prova, mas sinto que o[n]próximo ano será ainda melhor para nós.[n][f 1 3 65535][w][e]

[msg MSG_067_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 72 65535 0]Eu sinto exatamente o mesmo! Que estranho...[n][f 1 3 65535][w][e]

[msg MSG_068_0_0 [Yusuke]]
[s][bup 0 5 0 7 0][f 4 10 65535 0 0][vp 8 0 0 73 65535 0]Bem, isso é natural, considerando o quão[n]satisfeitos estamos com a nossa celebração[n]no final do ano.[n][f 1 3 65535][w][e]

[msg MSG_069_0_0 [Newscaster]]
[s][vp 8 0 0 74 65535 0]Os jovens estão se reunindo em Shibuya o dia[n]todo para a grande contagem regressiva à[n]meia-noite, e essa multidão é...[n][f 1 3 65535][w][e]

[msg MSG_070_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 75 65535 0]Eu realmente não quero continuar, mas parece[n]que é hora.[n][f 1 3 65535][w][e]

[msg MSG_071_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 76 65535 0]Veja você no próximo ano, certo?[n][f 1 3 65535][w][e]

[msg MSG_072_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 77 65535 0]Próximo ano...[n][f 1 3 65535][w][e]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 24 0 10 6 37 5 100][vp 8 0 0 78 65535 0]Sojiro! Hora dos Osechi! Prepare os pratos[n]de Ano Novo, Chop Chop! E não se esqueça do[n]feijão preto![n][f 1 3 65535][w][e]

[msg MSG_073_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 79 65535 0]Sim, sim, eu ouvi você. Se eu começar a[n]preparar o feijão agora, eles estarão[n]prontos pela manhã.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 80 65535 0]Não se preocupe com a comida, basta ter uma[n]boa noite de sono.[n][f 1 3 65535][w][e]

