[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Temos que escolher nosso próprio caminho,[n]não é?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Akechi mencionou que precisávamos determinar[n]o que faremos daqui em diante- parece que[n]ele estava certo.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Não podemos aceitar essa realidade, mas...[n]isso significa que teremos que lutar contra[n]o Dr. Maruki, certo?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Está certo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Temos que enfrentar Maruki e roubar seu[n]desejo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]De certa forma, são negócios como sempre[n]para nós.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]O Dr. Maruki é um adulto com um desejo[n]distorcido, mas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Esse desejo é apenas um desejo de todos nós[n]sermos felizes, certo?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Admito, não é nada parecido com os desejos[n]que vimos em artistas como Shido e[n]Kamoshida.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Os ladrões fantasmas mudam apenas o coração[n]dos malfeitores. O Dr. Maruki é bem[n]diferente de nossos alvos anteriores...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Bem, acho que já sabemos o que precisamos[n]fazer.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Haru está certo- dr. Maruki não é um adulto[n]de merda.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Provavelmente há muitas pessoas por aí,[n]vivendo tudo feliz nessa realidade...[n][f 1 3 65535][w][e]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 5 100][vp 8 0 0 15 65535 0]Quem sabe? Talvez o Dr. Maruki esteja[n]realmente fazendo a coisa certa.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Mas todos ainda sentimos que essa realidade[n]está errada, certo?[n][f 1 3 65535][w][e]
[s][bup 0 2 13 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 37 5 100][vp 8 0 0 17 65535 0]Decidimos o que é certo para nós mesmos.[n]Foi nisso que todos concordamos quando fomos[n]atrás  [f 4 2] no palácio.[n][f 1 3 65535][w][e]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Se o coração de ChanGin 'Doc consertar nossa[n]realidade, então eu vou fazer isso.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Uh, então... alguém, diga algo...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Ah! Desculpe... eu estava pensando em como[n]você está certo, Ryuji.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Então, vamos mudar o coração de nosso alvo[n]para não reformar a sociedade, mas adquirir[n]a realidade em que acreditamos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Isso não parece ruim.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Então é unânime![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Bem, isso significa que nosso próximo passo[n]é bem claro.[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]Confira o palácio.[e]
[s]Volte ao palácio.[e]

[msg MSG_016_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Direita. Maruki disse que estaria disposto a[n]lutar se também formos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]É seguro assumir que ele está esperando que[n]nos infiltemos seu palácio.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Isso me lembra- você sabe que uh...[n]Coisas que dobram realidade?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Por que o DOC é capaz de fazer isso, afinal?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Eu tenho me perguntado a mesma coisa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Mesmo se ele fosse o principal especialista[n]em psiências cognitivas, isso não seria[n]suficiente para ele fazer tudo isso.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Se vamos lutar contra Maruki, é melhor[n]desenterrar mais um pouco dele primeiro.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Girl's Voice]]
[s][bup 0 100 0 0 1][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Bom dia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Esta é a fala de Lavenza.[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s]LAVENZA?[e]
[s]Volte novamente?[e]

[msg MSG_022_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Huh?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Girl's Voice]]
[s][bup 0 100 0 0 1][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Sim, permita-me repetir...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Bom dia. Esta é a fala de Lavenza.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Lady Lavenza!?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Lavenza]]
[s][bup 0 100 0 0 1][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Sua vontade de rebelião atingiu novos[n]patamares.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Gostaríamos de ajudar isso, se você achar[n]agradável.[n][f 1 3 65535][w][e]

[sel SEL_026_0_0 top]
[s]Isso seria útil.[e]
[s]Por favor.[e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]Espere, como ela está ligando para você?[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]E como ela sabia quão altos são nossas[n]vontades? Ela tocou em sua linha ou algo[n]assim?[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Seu tempo era perfeito demais...[n]Talvez ela realmente tenha feito![n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Lavenza]]
[s][bup 0 100 0 0 1][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]Não realizei nenhuma forma de vigilância[n]eletrônica.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]... aparentemente ela pode ouvi-lo.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Lavenza]]
[s][bup 0 100 0 0 1][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Há algo que desejo contar sobre sua situação[n]atual...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]No entanto, estou atingindo o limite da[n]minha capacidade de comunicação com esse[n]método.[n]Vamos nos encontrar pessoalmente amanhã.[n][f 1 3 65535][w][e]

[sel SEL_033_0_0 top]
[s]Encontra?[e]
[s]Onde?[e]

[msg MSG_034_0_0 [Lavenza]]
[s][bup 0 100 0 0 1][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]Sim. Claro, seus amigos também são[n]convidados.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]Quanto ao local...[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Lavenza]]
[s][bup 0 100 0 0 1][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]Seria melhor para mim selecionar um local[n]considerado fácil de alcançar por todas as[n]partes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]Portanto...[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Lavenza]]
[s][bup 0 100 0 0 1][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]Vamos nos reunir em sua escola.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]Em Shujin?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]Espere, ela estará na escola?[n]Lavenza vai?[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Lavenza]]
[s][bup 0 100 0 0 1][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]Nesse caso, te vejo amanhã.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 55 65535 0]Ela desligou...[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 56 65535 0]Ela realmente vai para a nossa escola?[n]Apenas, caminhe pelos portões da frente como[n]nada?[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 57 65535 0]Não tenho certeza do que fazer com isso...[n][f 1 3 65535][w][e]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 58 65535 0]Mas desde que determinamos nosso objetivo, e[n]Lavenza se ofereceu para nos ajudar...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 59 65535 0]Eu chamaria isso de algum tipo de progresso.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 60 65535 0]Tudo o que resta é o que discutirmos amanhã[n]na escola, além de se unirmos ou não à[n]Akechi.[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 61 65535 0]Considerando o quê [f 4 2] nos disse que realmente parece que[n]compartilhamos um objetivo final com[n]Akechi, mas...[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 62 65535 0]... bem, acho que devemos nos unir.[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 63 65535 0]Mmhm, eu também.[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 64 65535 0]Tem certeza?[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 65 65535 0]O Dr. Maruki é forte o suficiente para mudar[n]a própria realidade. Se vamos lutar com[n]ele, precisaremos da ajuda de Akechi.[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Haru]]
[s][bup 0 7 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 66 65535 0]Além disso, se ele nos trair novamente, nós[n]o levaremos também.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 67 65535 0]Eu acho que isso resolve isso.[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 68 65535 0]Vamos todos nos encontrar em Shujin amanhã.[n]Vou cuidar de descobrir como obter Yusuke e[n]Futaba na escola.[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 69 65535 0]Agradeço o esforço, obrigado.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 70 65535 0]Tudo bem, vamos para casa por enquanto.[n][f 1 3 65535][w][e]

