[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 812 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]TCH... não podemos nos dar ao luxo de perder[n]tempo com essa merda![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Cendrillon]]
[s][vp 8 0 0 2 65535 0]Nngh... aaaaaaaaagh![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 812 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Aqui vem![n][f 1 2 15][e]

[msg MSG_003_0_0 [Boy's Voice]]
[s][vp 8 0 0 4 4 0]Eu não acho![n][f 1 2 50][e]

[msg MSG_004_0_0 [Boyish Voice]]
[s][vp 8 0 0 5 5 0]Droga, crânio, eu disse para você não se[n]apressar assim![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Girl's Voice]]
[s][vp 8 0 0 6 8 0]Pelo menos parecia dar certo a nosso favor.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]Você veio...[e]
[s]Eu sabia que você estaria aqui.[e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Nossas desculpas por fazer você esperar[n]tanto tempo.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]É aquele...?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 104 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Akechi-kun e Dr. Maruki!?[n][f 1 3 65535][w][e]

[msg MSG_019_5_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Yoshizawa está preso por- por que sua[n]persona está fazendo isso!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]O que diabos está acontecendo aqui!?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Muito dessa merda não faz sentido, mas vamos[n]abordar mais tarde![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Temos que detê-la primeiro- certo, Joker?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Tudo bem! Vamos entrar em formação![n][f 1 3 65535][w][e]

