[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 800 0 0][f 4 10 65535 0 0][vp 8 2 0 0 4 0]Bem vindo de volta. Você estava atrasado.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Akechi]]
[s][bup 0 9 10 65535 1][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Sou eu. Eu descobri algo[n]que acho que devo contar a você.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Liguei para a casa de Yoshizawa para tentar[n]investigar. Eles acreditam que é um retiro[n]esportivo de ontem.[n][f 1 3 65535][w][e]
[s][bup 0 9 13 65535 1][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Maruki está de fato alterando[n]nossa realidade física[n]ao seu gosto...[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]É perturbador.[e]
[s]eu não acredito...[e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 10 65535 1][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]A sério. É a primeira vez[n]que testemunhei um poder[n]desta magnitude.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 10 65535 1][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Até mesmo os grandes Ladrões Fantasmas[n]dos quais você tanto se orgulha[n]caíram na armadilha dele.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 10 65535 1][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eu concordo, na verdade.[n]Infelizmente, esta[n]é a realidade.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 10 65535 1][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Até mesmo os grandes Ladrões Fantasmas[n]dos quais você tanto se orgulha[n]caíram na armadilha dele.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 10 65535 1][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Você quer tentar mudar[n]sua opinião, certo?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 10 65535 1][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tudo bem então. Acho que vamos precisar[n]da ajuda deles também...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Desde que você consiga trazê-los à razão, é claro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tudo depende de sua capacidade[n]de abandonar a realidade que deveriam[n]querer para si.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Terei o cuidado de investigar[n]maruki novamente. Você faz o que deve.[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Entendo.[e]
[s]Obrigada.[e]

[msg MSG_010_0_0 [Akechi]]
[s][bup 0 9 10 65535 1][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...Você se lembra do que dissemos?[n]Fizemos um acordo.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 10 65535 1][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bem, entrarei em contato com você, caso[n]descubra alguma coisa.[n]Boa noite.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 800 0 0][f 4 10 65535 0 0][vp 8 2 0 0 4 0]Foi Akechi? Você parece estar se dando bem[n]ultimamente.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Morgana]]
[s][bup 0 3 800 0 0][f 4 10 65535 0 0][vp 8 2 0 0 4 0]Ei, eu estava pensando, por que nós[n]Phantom Thieves[n]não vamos todos ao spa?[n][f 1 3 65535][w][e]
[s][bup 0 3 801 0 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][f 4 24 0 4 2 9 5 100][vp 8 2 0 0 4 0]Então, Lady Ann e eu podemos…[n]Ihihihih…[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 4 0]O que você acha disso? Isso seria perfeito, hein?[n]Devemos perguntar ao resto da equipe.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Maruki]]
[s][vp 8 2 0 0 65535 0]Em vez de explicar para você em palavras,[n]eu gostaria que você visse essa nova[n]realidade com seus próprios olhos.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Eu sei que seus amigos[n]já estão curtindo, [f 4 1]-kun.[n][f 1 3 65535][w][e]

[msg MND_015_0_0]
[s][vp 8 2 0 0 65535 0]Aparentemente esta é a[n]realidade desejada por Morgana...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Morgana]]
[s][bup 0 3 800 0 0][f 4 10 65535 0 0][vp 8 2 0 0 4 0]OK, melhor ir[n]dormir por hoje.[n][f 1 3 65535][w][e]
[s][bup 0 3 803 0 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 5 100][vp 8 2 0 0 4 0]Ah... Talvez a cama esteja começando a[n]ser algo íntimo demais[n]para dormirmos juntos.[n][f 1 3 65535][w][e]
[s][bup 0 3 801 0 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][f 4 24 0 4 2 9 5 100][vp 8 2 0 0 4 0]Ah bem! Acho que vou começar a[n]dormir no sofá.[n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s]Vocês estão felizes?[e]
[s]Você é um menino bonito.[e]

[msg MSG_018_0_0 [Morgana]]
[s][bup 0 3 804 0 0][f 4 10 65535 0 0][vp 8 2 0 0 4 0]Huh? E de onde vem isso?[n][f 1 3 65535][w][e]

[msg MSG_018_5_0 [Morgana]]
[s][bup 0 3 801 0 0][f 4 10 65535 0 0][vp 8 2 0 0 4 0]Bem, sim, eu diria que estou feliz.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 804 0 0][f 4 10 65535 0 0][vp 8 2 0 0 4 0]Huh? E o que isso tem a ver?[n][f 1 3 65535][w][e]
[s][bup 0 3 801 0 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][f 4 24 0 4 2 9 5 100][vp 8 2 0 0 4 0]Quero dizer, agradeço o[n]elogio![n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]Você gosta dessa realidade?[e]
[s]Nós costumávamos dormir juntos.[e]

[msg MSG_021_0_0 [Morgana]]
[s][bup 0 3 801 0 0][f 4 10 65535 0 0][vp 8 2 0 0 4 0]Gosta da realidade? Bem, é por isso que todos nós[n]lutamos, então...[n][f 1 3 65535][w][e]
[s][bup 0 3 803 0 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 5 100][vp 8 2 0 0 4 0]Espere... O que eu quis dizer com...?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Morgana]]
[s][bup 0 3 801 0 0][f 4 10 65535 0 0][vp 8 2 0 0 4 0]Haha, sim! Ainda me lembro que[n]você odiava quando eu me enroscava[n]em você![n][f 1 3 65535][w][e]
[s][bup 0 3 803 0 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 5 100][vp 8 2 0 0 4 0]Espera... eu costumava me enrolar em...?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Morgana]]
[s][bup 0 3 803 0 0][f 4 10 65535 0 0][vp 8 2 0 0 4 0]Não estou convencido...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 4 0]Eles me capturaram no Palácio Kamoshida.[n]Foi então[n]que nos conhecemos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 4 0]Quando nos juntamos ao Mementos,[n]eu me transformei em...[n][f 1 3 65535][w][e]

[sel SEL_024_0_0 top]
[s]Continue pensando nisso.[e]
[s]Eu sei que você consegue.[e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 804 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 4 0]Huh? OK...[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Morgana]]
[s][vp 8 2 0 0 65535 0]Tive a oportunidade[n]de ser útil para humanos[n]que muito admiro...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Nada poderia me deixar mais feliz.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Morgana]]
[s][bup 0 3 804 0 0][f 4 10 65535 0 0][vp 8 2 0 0 4 0]...O que foi...?[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Morgana]]
[s][bup 0 3 803 0 0][f 4 10 65535 0 0][vp 8 2 0 0 4 0]Desculpe, vou sair e pensar[n]sobre isso por um tempo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 4 0]Você deveria dormir um pouco.[n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][vp 8 2 0 0 65535 0]......[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Não posso fazer nada[n]só esperar.[n][f 1 3 65535][w][e]

