[msg MSG_000_0_0 [Ann]]
[s][vp 6 0 0 1 0 0]Mas isso...[n][f 1 2 30][e]

[msg MSG_001_0_0 [Futaba]]
[s][vp 6 0 0 2 0 0]Não... Você está brincando...[n][f 1 2 130][e]

[msg MSG_002_0_0 [Morgana]]
[s][vp 6 0 0 3 0 0]Maruki...Ele conseguiu...[n][f 1 2 90][e]

[msg MSG_002_5_0 [Morgana]]
[s][vp 6 0 0 4 0 0]Ele evoluiu sua Persona![n][f 1 2 60][e]

[msg MSG_003_0_0 [Yusuke]]
[s][vp 6 0 0 5 0 0]Quanta força de vontade...[n][f 1 2 80][e]

[msg MSG_004_0_0 [Maruki]]
[s][vp 6 0 0 6 0 0]Se for para a felicidade de todos,[n]não me importa o que aconteça comigo.[n][f 1 2 165][e]

[msg MSG_004_3_0 [Maruki]]
[s][vp 6 0 0 7 0 0]Não resista... Aceite.[n][f 1 2 80][e]

[msg MSG_004_5_0 [Maruki]]
[s][vp 6 0 0 8 0 0]Com meu poder... Não...[n][f 1 2 65][e]

[msg MSG_005_0_0 [Maruki]]
[s][vp 6 0 0 9 0 0]Com a minha e a de Adam Kadmon[n]juntos, nossa realidade é próxima![n][f 1 2 140][e]

