[msg MSG_000_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 7 301 1][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Mas o que...?!?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sumire]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Mas isso...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Parece um belo paraíso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Suponho que Maruki queira nos dizer que o[n]mundo se tornará assim, se ele for livre[n]para abusar de sua pesquisa.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Um paraíso...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Espere, mas isso é um[n]beco sem saída, não é? E ainda não[n]encontramos o Tesouro...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Dê uma olhada.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Aquela coisa brilhante?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Não há dúvida... esse é[n]o nosso Tesouro![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Isso também significa que o[n]caminho de infiltração é seguro.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Perfeito! Tudo o que temos a fazer é[n]enviar a carta de alta...[n][f 1 3 65535][w][e]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 4 100][vp 8 0 0 12 65535 0]Oh espere. Como podemos[n]fazer isso desta vez?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Você está certo, o Dr. Maruki[n]permaneceu aqui no Palácio por[n]todo o tempo, certo?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Certamente Maruki está bem ciente de que os[n]Phantom Thieves enviaram a carta de[n]desafio um dia antes do roubo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Considerando suas ações até agora,[n]suspeito que ele tentará intervir[n]de alguma forma naquele dia...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Eu tinha que apostar, diria que[n]ele vai atrás do Joker.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Direita. Nesse caso, deixarei a[n]carta de aviso em suas mãos,[n]Joker.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][bup 0 9 811 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Poderíamos simplesmente emboscá-lo e destruí-lo[n]assim que ele cair em nossa armadilha.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Não faremos nada assim![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Nosso objetivo é devolver a[n]realidade ao seu estado original,[n]não massacrar o Dr. Maruki.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Akechi]]
[s][bup 0 9 813 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Foi só uma brincadeira.[n][f 1 3 65535][w][e]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Afinal, todos vocês sabem muito bem[n]que a influência de Maruki na[n]realidade vai muito além deste Palácio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Um passo em falso aqui pode[n]significar nossa ruína do lado de fora,[n]onde não temos Personas.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Akechi]]
[s][bup 0 9 811 0 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]A estratégia mais segura continua sendo[n]despertar o coração de Maruki,[n]assim como você quer fazer.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Finalmente estamos prestes a[n]acordar seu coração...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Se roubarmos o tesouro do Doutor[n]Maruki, tudo será como antes,[n]certo?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Não tenho certeza, mas muito[n]provavelmente sim.[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]Tudo bem?[e]
[s]Você consegue?[e]

[msg MSG_021_0_0 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Sim! Naturalmente.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Chegamos até aqui...[n]Não podemos desistir agora.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Devemos proteger nossa[n]realidade.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Em relação ao prazo...[n]Dr. Maruki definiu[n][clr 2]3 de fevereiro[clr 27], certo?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Sim.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Ele é diferente dos inimigos enfrentados[n]até agora... Se quisermos vencê-lo,[n]temos que nos tornar muito mais fortes.[n][f 1 3 65535][w][e]

