[msg MSG_000_0_0 [Maruki]]
[s][bup 0 216 501 0 0][f 4 10 65535 0 0][vp 8 0 0 1 7 0]Obrigado por ter vindo.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]O que há de errado com Sumire?[e]
[s]Você fez alguma coisa com ela?[e]

[msg MSG_002_0_0 [Maruki]]
[s][bup 0 216 501 0 0][f 4 10 65535 0 0][vp 8 0 0 2 7 0]Ele está apenas dormindo. Eu nunca[n]quis machucá-la.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 7 0]Quando sua turbulência interior[n]acalmar, farei com que ela se lembre da[n]vida que ela mais deseja.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 812 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]A vida que ela almeja, né?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Chame do que quiser... você está fazendo[n]lavagem cerebral nas pessoas[n]para sua própria gratificação.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Maruki]]
[s][bup 0 216 503 0 0][f 4 10 65535 0 0][vp 8 0 0 6 7 0]Estou bem ciente de que minhas ações serão[n]interpretadas dessa forma por alguns...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 7 0]Mas se esta minha "indulgência"[n]garantia a felicidade de milhares,[n]não seria para um bem maior?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Maruki]]
[s][bup 0 216 500 0 0][f 4 10 65535 0 0][vp 8 0 0 8 7 0][f 4 1]-kun, se eu[n]entendi você corretamente, você visitou[n]seus amigos esta semana...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 7 0]Esta é a realidade que todos[n]eles sempre desejaram...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 7 0]Este fato[n]pareceu incomodá-los de alguma forma?[n][f 1 3 65535][w][e]

[msg MSG_005_5_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0]Vamos lá, você está correndo um pouco rápido[n]demais. Estou apenas tentando o meu melhor para[n]não ser enganado por vocês.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Maruki]]
[s][bup 0 216 501 0 0][f 4 10 65535 0 0][vp 8 0 0 11 7 0]Esta realidade é a "mais verdadeira" de[n]todas... você só precisa[n]reconhecê-la.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 7 0]Feito isso, você será[n]feliz como eles são.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Maruki]]
[s][bup 0 216 501 0 0][f 4 10 65535 0 0][vp 8 0 0 13 7 0]Ainda não percebeu?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 7 0]Eles não querem apenas viver[n]essas vidas: eles querem que[n]você escolha essa feliz realidade também.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]Esta realidade...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0]Fiquei tão triste quando a família dele[n]se mudou... Mas tudo[n]bem quando acaba bem![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0]Mas, graças ao patrocínio do Sensei,[n]todos os dias fico mais perto da criação[n]de um trabalho tão disruptivo.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Maruki]]
[s][bup 0 216 500 0 0][f 4 10 65535 0 0][vp 8 0 0 17 7 0]Por favor, tente entender... Para[n]o bem deles, e o seu...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][vp 8 0 0 0 65535 0]Estou muito animado por ele. É[n]como se ele finalmente estivesse recebendo[n]o reconhecimento que merece.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Futaba]]
[s][vp 8 0 0 0 65535 0]Sério?!? Todos no Leblanc,[n]meninos. É hora do curry![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Haru]]
[s][vp 8 0 0 0 65535 0]Oh pai... é ciúme[n]que eu percebo?[n][f 1 3 65535][w][e]

[msg MND_015_0_0]
[s][vp 8 0 0 0 65535 0]Meus amigos querem ficar nessa realidade...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Morgana]]
[s][vp 8 0 0 0 65535 0]Não estou convencido...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Morgana]]
[s][vp 8 0 0 0 65535 0]Eles me capturaram no Palácio Kamoshida.[n]Foi então[n]que nos conhecemos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Se nos juntássemos ao Mementos,[n]eu me transformaria em...[n][f 1 3 65535][w][e]

[msg MND_018_0_0]
[s][vp 8 0 0 0 65535 0]...Mas é mesmo?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Maruki]]
[s][bup 0 216 500 0 0][f 4 10 65535 0 0][vp 8 0 0 24 7 0]Bem, é hora...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Akechi]]
[s][bup 0 9 810 0 0][vp 1 0 0 25 0 0]......[n][f 1 3 65535][w][e]

[msg MND_020_5_0]
[s][vp 8 0 0 0 65535 0]......[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Se eu aceitar a oferta de Maruki...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Meus amigos e eu poderemos viver[n]felizmente nesta realidade que ele[n]criou... Ou assim ele diz...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Se ficarmos aqui, levaremos uma vida[n]verdadeiramente feliz, livre de dor e[n]sofrimento...[n][f 1 3 65535][w][e]

[msg MND_020_7_0]
[s][vp 8 0 0 0 65535 0]Mas, para tornar isso possível, nossas[n]memórias seriam distorcidas.[n]É provavelmente inevitável...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]......[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Maruki]]
[s][bup 0 216 500 0 0][f 4 10 65535 0 0][vp 8 0 0 26 7 0]Pelo bem de Yoshizawa-san e[n]de seus outros amigos...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 27 7 0]Eu quero que você me dê uma resposta.[n][f 1 3 65535][w][e]

[sel SEL_022_0_0 top]
[s]Não posso aceitar esta realidade.[e]
[s]Eu aceito esta realidade.[e]

[msg MSG_022_1_0 [Maruki]]
[s][bup 0 216 501 0 0][f 4 10 65535 0 0][vp 8 0 0 28 7 0]Oh, que alívio...[n]Você aceita este mundo!?![n][f 1 3 65535][w][e]

[msg MSG_022_3_0 [Akechi]]
[s][bup 0 9 814 0 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Não... [f 4 2], por favor,[n]diga-me que não está falando sério...[n][f 1 3 65535][w][e]

[sel SEL_022_5_0 top]
[s]Preciso pensar sobre isso.[e]
[s]Sério.[f 2 7 0 0 2120 1][e]

[msg MSG_022_7_0 [Maruki]]
[s][bup 0 216 500 0 0][f 4 10 65535 0 0][vp 8 0 0 30 7 0]Então vou ter que me repetir...[n][f 1 3 65535][w][e]

[msg MSG_022_9_0 [Maruki]]
[s][bup 0 216 501 0 0][f 4 10 65535 0 0][vp 8 0 0 31 7 0]Sério!?! Estou tão feliz que[n]você começou a ver[n]as coisas do meu ponto de vista![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 32 7 0]Você não precisa mais se preocupar com[n]nada. Eu cuidarei de tudo.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Maruki]]
[s][bup 0 216 504 0 0][f 4 10 65535 0 0][vp 8 0 0 33 7 0]Hã?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Akechi]]
[s][bup 0 9 811 0 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Aparentemente, as negociações[n]foram frustradas.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Maruki]]
[s][bup 0 216 503 0 0][f 4 10 65535 0 0][vp 8 0 0 35 7 0]...Entendo.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Maruki]]
[s][bup 0 216 503 0 0][f 4 10 65535 0 0][vp 8 0 0 36 7 0]Parece que ainda não[n]chegamos a um entendimento...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Sumire]]
[s][bup 0 10 10 6 0][f 4 10 65535 0 0][vp 8 0 0 37 5 0]Não...[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Sumire]]
[s][bup 0 10 10 6 0][f 4 10 65535 0 0][vp 8 0 0 38 5 0]Você não está falando sério, está? Por favor...[n]Eu imploro, [f 4 2]-senpai...[n]Deixe-me viver como Kasumi![n][f 1 3 65535][w][e]

[sel SEL_029_0_0 top]
[s]Não se esconda da verdade.[e]
[s]...[e]

[msg MSG_031_5_0 [Sumire]]
[s][bup 0 10 12 6 0][f 4 10 65535 0 0][vp 8 0 0 39 5 0]Mas por que? Essa dor é[n]insuportável... Por que não posso[n]deixá-la para trás!?![n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Sumire]]
[s][bup 0 10 11 6 0][f 4 10 65535 0 0][vp 8 0 0 40 5 0]Kasumi está perdida para sempre, e...[n]e é tudo minha culpa...[n]é tudo culpa de Sumire![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 41 5 0]Eu não posso viver uma vida assim![n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Sumire]]
[s][bup 0 10 112 0 0][f 4 10 65535 0 0][vp 8 0 0 42 5 0]Por favor... Não[n]tente me impedir...[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Sumire]]
[s][bup 0 10 111 0 0][f 4 10 65535 0 0][vp 8 0 0 44 5 0]Se você quiser, então eu...![n][f 1 3 65535][w][e]

[sel SEL_035_0_0 top]
[s]Você está falando sério?[e]
[s]Não faça isso...[e]

[msg MSG_036_0_0 [Akechi]]
[s][bup 0 9 813 0 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Que teimoso...[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]Você pode dizer a ela o que quiser, mas ela[n]não conseguirá te entender.[n]Não depende de nós, infelizmente.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]Eu poderia cuidar disso para você,[n]aqui e agora... Mas você me quer fora[n]vivo daqui, certo?[n][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 11 3 301 65535][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]Apresse-se e vamos acabar com isso.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Sumire]]
[s][bup 0 10 111 0 0][f 4 10 65535 0 0][vp 8 0 0 49 5 0]Se você não está desistindo,[n]então...[n][f 1 3 65535][w][e]

