[msg MSG_000_0_0 [??? Yoshizawa]]
[s][bup 0 10 923 6 0][f 4 10 65535 0 0][vp 8 0 0 1 5 0]EU...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Maruki]]
[s][bup 0 216 502 65535 0][vp 1 0 0 2 0 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]... parece que você se lembrou.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [??? Yoshizawa]]
[s][bup 0 10 925 6 0][f 4 10 65535 0 0][vp 8 0 0 4 5 0]Está certo... eu estou...[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Kasumi?[e]
[s]Kasumi...[e]

[msg MSG_004_0_0 [??? Yoshizawa]]
[s][bup 0 10 924 6 0][f 4 10 65535 0 0][vp 8 0 0 5 5 0]Kasu... mi?[n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [??? Yoshizawa]]
[s][bup 0 10 925 6 0][f 4 10 65535 0 0][vp 8 0 0 6 5 0]Não... isso não está certo! Eu sou... eu não[n]sou kasumi![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 812 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]... A garota chamada "Kasumi Yoshizawa" está[n]atualmente falecida.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [??? Yoshizawa]]
[s][bup 0 10 923 6 0][f 4 10 65535 0 0][vp 8 0 0 8 5 0]Era na primavera passada... antes de eu[n]começar em Shujin...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 5 0]Estávamos voltando para casa do treino.[n]Aconteceu ali, naquela rua do vídeo...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [??? Yoshizawa]]
[s][bup 0 10 925 6 0][f 4 10 65535 0 0][vp 8 0 0 10 5 0]Eu não estava olhando para onde estava[n]indo... E Kasumi, ela me protegeu do carro...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [??? Yoshizawa]]
[s][bup 0 10 925 6 0][f 4 10 65535 0 0][vp 8 0 0 11 5 0]Fui salvo por Kasumi... Eu a roubei de seus[n]sonhos... e até a vida dela![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 5 0]Eu sou... sua irmã mais nova, Sumire[n]Yoshizawa.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Vou assumir o controle daqui.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Afinal, eu faço um papel nessa história.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Seu nome verdadeiro... é Sumire Yoshizawa.[n]Ela é a irmã mais nova de Kasumi-san...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Mas há meses, ela só se viu como Kasumi[n]Yoshizawa...[n]sua irmã mais velha falecida.[n][f 1 3 65535][w][e]

[msg MSG_010_5_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Claro, foi apenas a cognição de si mesma que[n]mudou, de modo que para as pessoas ao seu[n]redor, ela ainda era Sumire-san.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Por alguma razão, no entanto... havia[n]algumas raras exceções a isso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Aconteceu algo para fazer você acreditar que[n]ela era Kasumi-san?[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 1 0 0 0 0 0]Parece ser um bolso da Shujin Academy. O[n]nome "Kasumi Yoshizawa" está escrito dentro.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][bup 0 9 810 65535 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Parece que você não tinha noção, mas ela era[n]Sumire Yoshizawa desde o início.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]No entanto, quando assistimos a outro vídeo,[n]ela deu seu nome como Kasumi Yoshizawa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Considerando uma afirmação tão estranha, eu[n]realmente suspeitava por um momento que ela[n]era a governante do palácio...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sumire]]
[s][bup 0 10 923 6 0][f 4 10 65535 0 0][vp 8 0 0 23 5 0]Depois que Kasumi morreu, mas antes de[n]começar em Shujin, recebi aconselhamento do[n]Dr. Maruki.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 24 5 0]Foi quando eu disse a ele...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Sumire]]
[s][bup 0 10 923 6 0][f 4 10 65535 0 0][vp 8 0 0 25 5 0]Se Kasumi se foi e não pode fazer seu sonho[n]se tornar realidade...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 5 0]Então eu quero me tornar Kasumi, para que eu[n]possa transformar seu sonho em realidade[n]para ela.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Akechi]]
[s][bup 0 9 810 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]É por isso que você se intrometiu com a[n]cognição dela? Por seus próprios desejos?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Está certo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Por mais limitado, eu já tinha o poder na[n]época de atualizar seu desejo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Coloque-se no lugar dela por um momento...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]A irmã mais velha de Sumire-San morreu por[n]protegê-la. Imagine sobreviver a uma[n]tragédia tão sombria...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Quem seria capaz de lidar com a culpa desse[n]sobrevivente, muito menos curar-se com as[n]cicatrizes emocionais que ela sofreu?[n][f 1 3 65535][w][e]

[msg MSG_017_3_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Se Sumire-San puder viver uma vida saudável[n]e positiva, tornando-se Kasumi-san...[n][f 1 3 65535][w][e]

[msg MSG_017_5_0 [Maruki]]
[s][bup 0 216 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Então acredito que a realidade é o que a[n]faria feliz.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Akechi]]
[s][bup 0 9 810 65535 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]... Eu já tive o suficiente da sua[n]racionalização alta e poderosa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Tudo o que você realmente fez foi usá-la[n]para tentar fazer com que todos reconheçam[n]a validade de sua pesquisa.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Maruki]]
[s][bup 0 216 503 65535 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Então é assim que você vê coisas, hein?[n]Isso é bastante infeliz.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]É claro que eu queria que a sociedade[n]reconhecesse a psiiência cognitiva através[n]da minha pesquisa...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]Mas isso é porque meu objetivo é salvar[n]todos no mundo como Yoshizawa-san, acabando[n]com todo o sofrimento![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Akechi]]
[s][bup 0 9 812 65535 0][vp 1 0 0 41 0 0]......![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Meu trabalho converterá os desejos do povo[n]em realidade.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 77 65535 0]Mesmo quando falamos, minha pesquisa está se[n]concretizando...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]Ninguém jamais terá que sofrer novamente sob[n]o jugo de um mundo injusto.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]Isso... Palácio, você chamou isso? É um[n]lugar onde os desejos de seu governante[n]assumem a forma física, sim?[n][f 1 3 65535][w][e]

[msg MSG_022_5_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Desejo utilizar minha pesquisa para salvar a[n]humanidade- suponho que esse seria o[n]"desejo" que tenho mais querido.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Akechi]]
[s][bup 0 9 812 65535 0][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]... Que absurdo total.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Maruki]]
[s][bup 0 216 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]Você poderia muito bem estar certo.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]Ainda assim, estou inteiramente sério sobre[n]mudar nossa realidade imperfeita.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]Assim como ela foi salva ao se tornar[n]Kasumi, salvarei todas as outras pessoas do[n]mundo que atualmente sofrem.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]Na verdade, é minha responsabilidade[n]fazê-lo...[n]Você pode ver como este mundo concedeu o[n]dever de mim.[n][f 1 3 65535][w][e]

[sel SEL_026_0_0 top]
[s]Isso é realmente salvação?[e]
[s]O que acontece com a antiga realidade?[e]

[msg MSG_027_0_0 [Maruki]]
[s][bup 0 216 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]As crueldades da história desaparecerão e[n]todos viverão suas vidas, assim como sempre[n]sonhavam.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 80 65535 0]Se você não chama isso de salvação, o que[n]seria?[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Maruki]]
[s][bup 0 216 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]Não sei ao certo- provavelmente será tratado[n]como se nunca existisse.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]A realidade cruel deixará de ser, e a[n]realidade que eu gerar será o único mundo[n]reconhecido pela sociedade.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Akechi]]
[s][bup 0 9 810 65535 0][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]E você assume que vamos comprar sua lavagem[n]cerebral e apenas viver na palma da sua mão?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 55 65535 0]Honestamente, isso parece absolutamente[n]revoltante.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 56 65535 0]... Tudo bem, então essa é a sua resposta,[n]Akechi-kun.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 57 65535 0]E os outros?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 58 65535 0]Yoshizawa-san...[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 59 65535 0]Permita-me perguntar mais uma vez...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 60 65535 0]Qual realidade você deseja habitar?[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Sumire]]
[s][bup 0 10 924 6 0][f 4 10 65535 0 0][vp 8 0 0 61 65535 0]Huh?[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Maruki]]
[s][bup 0 216 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 62 65535 0]Se desejar, você pode voltar à sua vida como[n]Sumire...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 63 65535 0]Mas se você preferir continuar sua vida como[n]kasumi, posso conceder esse desejo por você[n]também.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Sumire]]
[s][bup 0 10 925 6 0][f 4 10 65535 0 0][vp 8 0 0 64 65535 0]Dr. Maruki... eu...[n][f 1 3 65535][w][e]

[sel SEL_036_0_0 top]
[s]Não seja manipulado.[e]
[s]Acredite em si mesmo.[e]

[msg MSG_037_0_0 [Sumire]]
[s][bup 0 10 923 6 0][vp 1 0 0 65 0 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 66 65535 0]É impossível...[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Sumire]]
[s][bup 0 10 923 6 0][f 4 10 65535 0 0][vp 8 0 0 67 65535 0]Eu sinto Muito, [f 4 1]-senpai...[n][f 1 3 65535][w][e]

[msg MSG_038_3_0 [Sumire]]
[s][bup 0 10 923 6 0][f 4 10 65535 0 0][vp 8 0 0 78 65535 0]Eu... eu não posso voltar a ser ela...[n][f 1 3 65535][w][e]

[msg MSG_038_5_0 [Sumire]]
[s][bup 0 10 925 6 0][f 4 10 65535 0 0][vp 8 0 0 79 65535 0]Não posso ser quem levou sua irmã à morte[n]dela![n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Maruki]]
[s][bup 0 216 503 65535 0][f 4 10 65535 0 0][vp 8 0 0 70 65535 0]Por favor, não a julgue.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 71 65535 0]Isso é apenas evidência de quão dolorosa a[n]vida é para ela.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 72 65535 0]Vocês sentiam duas dúvidas que se formavam[n]na realidade que manifestei- foi o que o[n]trouxe aqui.[n][f 1 3 65535][w][e]

[msg MSG_040_3_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 73 65535 0]Mas, por favor, lembre-se disso também:[n]vocês dois não são excluídos das pessoas[n]que desejo salvar.[n][f 1 3 65535][w][e]

[msg MSG_040_5_0 [Maruki]]
[s][bup 0 216 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 74 65535 0]Venha agora, [f 4 1]-kun... você não aceita minha realidade por[n]sua própria felicidade?[n][f 1 3 65535][w][e]

[sel SEL_041_0_0 top]
[s]......[e]
[s]Vou encontrar minha própria felicidade.[e]

[msg MSG_042_0_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 75 65535 0]... nenhuma decisão ainda, hein?[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Maruki]]
[s][bup 0 216 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 76 65535 0]... Não há negócio até agora, hein?[n][f 1 3 65535][w][e]

