[msg MSG_000_0_0 [Maruki]]
[s][vp 6 0 0 1 0 0]Eu sinto Muito.[n][f 1 2 115][e]

[msg MSG_001_0_0 [Maruki]]
[s][vp 6 0 0 2 0 0]Eu disse que não me importava com o que[n]aconteceria comigo...[n][f 1 2 195][e]

[msg MSG_002_0_0 [Maruki]]
[s][vp 6 0 0 3 0 0]Mas eu acho...[n][f 1 2 160][e]

[msg MSG_003_0_0 [Maruki]]
[s][vp 6 0 0 4 0 0]Eu não estava comprometido com minhas[n]palavras...[n][f 1 2 90][e]

[msg MSG_004_0_0 [Maruki]]
[s][vp 6 0 0 5 0 0]Você também, hein?[n][f 1 2 85][e]

[msg MSG_005_0_0 [Sumire]]
[s][vp 6 0 0 6 0 0]Crow-senpai, o que você é-!?[n][f 1 2 60][e]

[msg MSG_006_0_0 [Akechi]]
[s][vp 6 0 0 7 0 0]Você não pode dizer?[n][f 1 2 30][e]

[msg MSG_007_0_0 [Akechi]]
[s][vp 6 0 0 8 0 0]TCH![n][f 1 2 25][e]

[msg MSG_008_0_0 [Maruki]]
[s][vp 6 0 0 9 0 0]Você pensa a mesma coisa, não é?[n][f 1 2 75][e]

[msg MSG_009_0_0 [Maruki]]
[s][vp 6 0 0 10 0 0]Claro que você faz...[n][f 1 2 60][e]

[msg MSG_010_0_0 [Maruki]]
[s][vp 6 0 0 11 0 0]Afinal...[n][f 1 2 60][e]

[msg MSG_011_0_0 [Sumire]]
[s][vp 6 0 0 12 0 0]Não, você não pode![n][f 1 2 45][e]

[msg MSG_012_0_0 [Akechi]]
[s][vp 6 0 0 13 0 0]Hesitamos agora- morremos![n][f 1 2 85][e]

[msg MSG_013_0_0 [Morgana]]
[s][vp 6 0 0 14 0 0]Lá em cima![n][f 1 2 25][e]

[msg MSG_014_0_0 [Maruki]]
[s][vp 6 0 0 15 0 0]Eu sou todo seu... use-me... como você[n]quiser...[n][f 1 2 120][e]

[msg MSG_015_0_0 [Maruki]]
[s][vp 6 0 0 16 0 0]Agora... mostre-nos... a realidade...[n][f 1 2 145][e]

[msg MSG_016_0_0 [Maruki]]
[s][vp 6 0 0 17 0 0]A realidade... desejamos...[n][f 1 2 110][e]

[msg MSG_017_0_0 [Maruki]]
[s][vp 6 0 0 18 0 0]Eu sou tu e...[n][f 1 2 90][e]

[msg MSG_018_0_0 [Adam Kadmon]]
[s][vp 6 0 0 19 0 0]... Tu és eu![n][f 1 2 95][e]

[msg MSG_019_0_0 [Futaba]]
[s][vp 6 0 0 20 0 0]Entrada![n][f 1 2 45][e]

