[msg MSG_000_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Quanto tempo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Nos conhecemos na[n]véspera de Natal, certo? Mmm, não.[n]Esqueça.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Tenho duas grandes notícias para você hoje.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Primeiro, nós finalmente[n]iniciamos o processo contra Shido.[n]Ele provavelmente será condenado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Obrigado por[n]cooperar. Seu testemunho[n]provou ser muito útil.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Estou feliz com isso.[e]
[s]Que alivio...[e]

[msg MSG_003_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]De fato, em um ponto[n]parecia não haver mais esperança[n]mais.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Mas, graças aos protestos civis,[n]alguns dos promotores mais indecisos[n]passaram para o nosso lado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Levará algum tempo até que as audiências comecem,[n]mas ainda é um primeiro passo para a mudança.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Atualmente, ele é acusado de corrupção,[n]violação das leis eleitorais[n]e das leis de financiamento.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Eu sabia que provar a existência do[n]Metaverso seria difícil,[n]mas...Ainda não estou satisfeito.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Shido, no entanto, confessou[n]todos os seus crimes, incluindo todos[n]que você conhece muito bem.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]E agora, a outra boa notícia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]A partir de hoje, você está livre novamente.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]Posso ir...?[e]
[s]Sério?[e]
[s]Por que tão de repente?[e]

[msg MSG_007_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Isso mesmo.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Isso mesmo.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Shido[n]confissão lançou luz sobre o seu caso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Conseguimos provar sua[n]inocência na agressão que[n]levou à sua prisão.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Sua sentença certamente será[n]revogada. Você é um homem livre agora.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Os outros fizeram tudo[n]o possível para ajudá-lo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]O depoimento da mulher[n]vítima da agressão[n]foi decisivo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]É incrível como eles conseguiram[n]rastrear as pessoas envolvidas[n]em um caso de mais de um ano atrás.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]E isso não é tudo... Você recebeu[n]o apoio de muitas outras[n]pessoas. Eu não esperava.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]No entanto, os Phantom Thieves,[n]agora, não existem mais.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Agora cabe a nós, adultos, orientar a sociedade[n]na direção certa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]...E, no entanto, continuo me perguntando[n]se você acredita em minhas palavras.[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]Fizemos uma promessa.[e]
[s]Eu confio nela... eu acho.[e]
[s]Não tenho certeza.[e]

[msg MSG_013_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Obrigado.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Farei o meu melhor,[n]e talvez um dia[n]conquiste sua total confiança.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]É uma pena... Eu deveria[n]esperar por isso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Farei questão de provar[n]minha boa fé para você com os resultados.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]De qualquer forma, estou feliz por[n]conseguir salvá-lo no tribunal.[n]Nunca me senti tão feliz.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Acredite em mim... Na época, salvar[n]seu futuro era mais importante[n]do que minha própria carreira.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]É como se você tivesse me ensinado a viver.[n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s]Ele está exagerando.[e]
[s]Não era minha intenção...[e]

[msg MSG_018_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Isso não é verdade.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]...A propósito, há uma coisa[n]em que venho pensando há um tempo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]O tesouro do meu mundo...[n]o que era?[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]Eu não lembro.[e]
[s]Por que ele quer saber?[e]

[msg MSG_021_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Eu estou bem com isso. Afinal,[n]isso não é um interrogatório.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Eu acho que isso não importa agora[n]mais.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Só tem... uma última coisa.[n]É algo que não contei[n]nem para Makoto...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Mas depois de conhecer todos vocês,[n]eu percebi uma coisa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]Meu "tesouro" mais precioso é[n]a justiça que uso para[n]proteger as pessoas que me são queridas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]Makoto também me ajudou[n]a descobrir.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Assim que o caso de Shido for encerrado,[n]acho que vou largar meu emprego para[n]tornar-me advogado de defesa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]Eu queria reformar o sistema,[n]mas acho que vou ter que deixar[n]alguém para fazer isso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]Eu quero exercer a justiça[n]não para meus próprios interesses,[n]mas para o bem do meu próximo.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Bom. Vou apresentar os papéis[n]para sua liberação.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 66 65535 0]Obrigado novamente por tudo[n]que você fez.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 67 65535 0]Até logo.[n][f 1 3 65535][w][e]

