[msg MSG_000_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]That was rather enjoyable, Inmate.[n]We won't underestimate the human[n]imagination again.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I'm a fan of that "popcorn" stuff as well.[n]I like how it's all puffed-up.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I'd like to come back when we get[n]the chance.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]You may claim to have enjoyed yourself,[n]but your screams told quite a different[n]story—to anyone who could hear.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]You were disruptive and embarrassing.[n]This is exactly why we get treated like[n]elementary schoolers.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Shut up! It was only because of that thing[n]jumping out at my face...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]And you were just as scared, Justine![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...It certainly was startling. The eyes and[n]nose seemed to stretch out right at me...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]And it all began the moment I donned[n]those black glasses...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]What was that thing that jumped out[n]of the screen? Could it have been...[n]a Persona?[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]It was the 3D glasses.[e]
[s]It was just movie magic.[e]
[s]Yep, that was a Persona.[e]

[msg MSG_006_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oh, so there was some sort of trick to[n]the glasses?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]But your own glasses are just normal[n]ones, right?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Your own attention wasn't wandering[n]while we were caught up in the movie,[n]was it?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]How very misleading. I nearly attempted[n]to destroy it with a Megidolaon.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oh, I see—they were some kind of device[n]that brings imaginations to life, huh?[n]What about the glasses you're wearing?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...Yours are just normal ones?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Your own attention wasn't wandering[n]while we were caught up in the movie,[n]was it?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]How very misleading. I nearly attempted[n]to destroy it with a Megidolaon.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]What, did you have one of your friends[n]hide behind the screen or something?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]How improper of you to try and scare us.[n]I nearly attempted to destroy it with a[n]Megidolaon.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...Why is it that humans even create such[n]large and elaborate fabrications in the[n]first place, though?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Isn't the imagining of these things[n]satisfying enough? Even dreaming[n]seems like a superior pastime.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Why do humans go so far as to spend their[n]money just to witness fictional events?[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]To escape reality.[e]
[s]As an intellectual exercise.[e]
[s]For the fun of it.[e]

[msg MSG_017_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]So they wish to avert their eyes from the[n]world they live in? What an unsettling[n]answer.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]You make it sound so scholarly.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]How about the preview we saw for[n]Muscled Man vs. Killer Shark? What part[n]of that exercise is intellectual to you?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Perhaps humans immerse themselves[n]in imaginary worlds as a means of[n]escaping reality?[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]What a naïve notion. Humans are such[n]simple-minded creatures.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Perhaps humans immerse themselves[n]in imaginary worlds as a means of[n]escaping reality?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hm? Hold on, did you just say "escape"?[n]You're not plotting a jailbreak... are you,[n]Inmate?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No matter how much you might rail[n]against it, you shall remain our Inmate.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hmph, I'd like to watch you TRY![n]What're you gonna do, blow the[n]door off your cell?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Don't be so crass, Caroline...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]If he were to attempt such a blatant[n]jailbreak, either our master or ourselves[n]would notice immediately.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Then how would YOU do it, Justine?[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I would use a spoon to dig a hole through[n]the wall, and conceal it with a poster of[n]some distractive image...[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Blowing open the cell door seems more[n]impactful.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]They used that plan in one of the movie[n]previews, correct? They wielded a bazooka[n]and went about blowing everything up.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Will you be caught or will you escape...?[n]If you're caught, then you'll be executed[n]for certain...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Suspense and excitement are necessary[n]elements of any escape.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Did you learn nothing from the movie,[n]Caroline? Or were you simply enjoying[n]yourself?[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Shut up! The Inmate'll settle this for us![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hey—tell us how you'd try to escape![n]Would you blast the door or use a spoon?[n][f 1 3 65535][w][e]

[sel SEL_031_0_0 top]
[s]I'm not going anywhere.[e]
[s]Blast that sucker open.[e]
[s]The spoon plot sounds good.[e]

[msg MSG_032_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]That is not the answer we are looking for[n]at the moment.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]It doesn't matter, either—you can't[n]escape us, no matter how sound[n]you think your plan is.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ha! Did you hear that, Justine! It's all about[n]making the greatest impact![n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Very well then. At any rate, he can't escape[n]us, regardless of what he does.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]*chuckle* Did you hear that, Caroline?[n]Even the Inmate knows that a crude plan[n]like yours has no hope of succeeding.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hmph! Whatever—it's not like he can[n]actually escape either way.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]There's no harm in allowing yourself to[n]fantasize a little bit, every now and then.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Indeed, today we learned more about the[n]power of human imagination. No wonder[n]such vile Palaces plague humanity.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]You're hereby free to fantasize, but keep[n]it in check, Inmate! Your job is to focus[n]on your rehabilitation![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Anyway, we hereby deem your assignment[n]complete.[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]報酬は合体機能(仮)です。[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I believe that will be all for today.[n]It is time to return.[n][f 1 3 65535][w][e]

[msg MND_043_0_0]
[s]I escorted the twins back[n]to the Velvet Room...[n][f 1 3 65535][w][e]

