[msg MSG_ISHOP_A4_PLAY_NG [郡司 朱実]]
[s]治験、今日は無理だよ。[n]…試したいのは、山々だけど。[n][w][e]
[s][clr 2]月曜、木曜、日曜[clr 27]に来て。[n]ちゃんと予定、空けといてね。[n][w][e]

[msg MSG_ISHOP_A4_TALK_01 [郡司 朱実]]
[s]んー…どうしたの。[n]薬なら、好きなの買ってけば?[n][w][e]
[s]……。[n][w][e]
[s]ハァ…つまんない。[n][w][e]
[s][clr 2]強い薬[clr 27]を試してみたいんだけどなー。[n]…ふふ。[n][w][e]

[msg MSG_ISHOP_A4_TALK_02 [郡司 朱実]]
[s]体調はどう?[n]こっちは準備、整ってるけど。[n][w][e]
[s]あとは貴方次第…さ、どうする?[n][w][e]

[msg MSG_ISHOP_A4_TALK_03 [郡司 朱実]]
[s]ん…ちょっと待ってて。[n]ちょうど今、データ整理してて。[n][w][e]
[s]…ん?[n]何か相談したいことでもあるの?[n][w][e]

[sel SEL_ISHOP_A4_TALK_03 top]
[s]相談してみる[e]
[s]今日はやめる[e]

[msg MSG_ISHOP_A4_TALK_03_A [郡司 朱実]]
[s]…は?[n]普通じゃない接着剤?[n][w][e]
[s]……。[n][w][e]
[s]あいかわらず、変な子…[n][w][e]
[s]でも、ちょっと面白い。[n]ようするにゲル状で、強度が高ければいいんでしょ。[n][w][e]
[s]ちょっと待ってて。[n]外科用の接着剤と、特殊な♀創膏を混ぜれば…[n][w][e]

[msg MSG_ISHOP_A4_TALK_03_A_0 [郡司 朱実]]
[s]…完♀。[n]はい、どうぞ。[n][w][e]
[s][f 1 5] [n]>[clr 2]朱実åの接着剤[clr 27]を入手した![n][w][e]
[s]>これで条件は整ったはずだ。[n] 後で畠山骨董店に行ってみようか…[n][w][e]
[s][f 1 5]郡司 朱実[n]こんな頼み、聞いた事ないけど。[n]まぁシンプルな配合だから、効果は確実。[n][w][e]
[s]それで…体調はどう?[n]今度は、こっちの協力する番でしょ。[n][w][e]

[msg MSG_ISHOP_A4_TALK_03_A_0_2 [郡司 朱実]]
[s]あとは貴方次第…さ、どうする?[n][f 1 5] [n]>朱実は治験を行いたいようだ…[n][w][e]

[msg MSG_ISHOP_A4_TALK_03_A_0_3 [郡司 朱実]]
[s]ま…今日は無理だけど…[n][clr 2]月曜、木曜、日曜[clr 27]の[clr 2]昼間[clr 27]に来て。[n][w][e]

[msg MSG_ISHOP_A4_TALK_03_B [郡司 朱実]]
[s]……。[n][w][e]
[s]うん…整理、終わり。[n]後は貴方次第だけど、どうする?[n][w][e]

[msg MSG_ISHOP_A4_TALK_04 [郡司 朱実]]
[s]薬、好きなの持ってっていいよ。[n]全部、効くから。[n][w][e]

[msg MSG_ISHOP_A4_TALK_05 [郡司 朱実]]
[s]…何?[n]今は都合が—いんだけど。[n][w][e]
[s]用あるなら[clr 2]昼間[clr 27]にして。[n][w][e]

[msg MSG_ISHOP_A4_TALK_01_CHE]
[s]>朱実に話を持ちかけてみようか…[n][w][e]

[msg MSG_ISHOP_A4_TALK_02_CHE]
[s]>朱実との関係を深めれば、[n] [clr 2]怪盗団に有利なこと[clr 27]が起こりそうだ…[n][w][e]

[sel SEL_ISHOP_A4_01 top]
[s]持ちかける[e]
[s]今日はやめる[e]

[sel SEL_ISHOP_A4_02 top]
[s]治験をする[e]
[s]コーポレイトの属性と機能を確認する[e]
[s]今日はやめる[e]

[msg MSG_ISHOP_A4_CORP_START_ [郡司 朱実]]
[s]…別の用事?[n][w][e]
[s]ふ~ん…まぁいいけど。[n]ちょうどヒマがピークだったの。[n][w][e]
[s]じゃ、どうぞ。[n]その話、聞かせてみて。[n][w][e]

[msg MSG_ISHOP_A4_CORP_START__2 [郡司 朱実]]
[s]いい子。[n]じゃあ、早速…[n][w][e]
[s]あ、ちょっと待ってて。[n]表の看板、休診中にして来るから。[n][w][e]

[msg HELP_ISHOP_A4_CORP_EFFEC [死神コーポレイト]]
[s]郡司朱実コーポレート ランク“[clr 2][var 0][clr 27]"[n]アルカナ属性は“[clr 1]死神[clr 27]"。[n][w][e]
[s]コーポランクが上昇すると、[n]“[clr 2]診療所[clr 27]"の機能が拡張します。[n][w][e]

[msg MSG_ISHOP_A4_CORP_CANCEL [郡司 朱実]]
[s]そう。[n]まぁ、好きにして。[n][w][e]
[s]……。[n][w][e]

[msg MSG_ISHOP_A4_CORP_CANCEL_2 [郡司 朱実]]
[s]そう…わかった。[n]でも、協力の約束は忘れないでね。[n][w][e]
[s]保険証のコピー押さえてるのも、忘れないように。[n][w][e]

[msg MSG_CORP_GUNJI_RANKUP_OK]
[s]朱美とは[n]そろそろ協力関係が強く結ばれそうです。[n][w][e]

[msg MSG_CORP_GUNJI_RANKUP_NO]
[s]>朱実とは、まだ仲が深まらない気がする…[n][w][e]

[msg ISHOP_HELLO [郡司 朱実]]
[s]…こんにちは。[n][w][e]

[sel YESNO_SEL top]
[s]はい[e]
[s]いいえ[e]

[msg ISHOP_HELLO_NIGHT [郡司 朱実]]
[s]…こんばんは。[n][w][e]

[msg ISHOP_HELLO_MOBILE [郡司 朱実]]
[s]あ、来た…[n][w][e]
[s]…この前頼まれてた[clr 2]治験薬[clr 27]、[n]もう出来あがってるけど、どうする…?[n][w][e]

[sel SEL_ISHOP_HELLO_MOBILE top]
[s]打ってくれ[e]
[s]心の準備が…[e]

[msg ISHOP_HELLO_MOBILE_CORP_ [郡司 朱実]]
[s]あ、そう…[n][w][e]
[s]じゃ、奥に来て…[n][w][e]

[msg ISHOP_HELLO_MOBILE_CORP__2 [郡司 朱実]]
[s]…分かった。[n]じゃあ準備が出来たら声掛けて…[n][w][e]

[msg ISHOP_TALK_CORPOK_01 [郡司 朱実]]
[s]…患者、さん。[n]今日は、診察、する?[n][w][e]

[msg ISHOP_TALK_CORPOK_02]
[s]>放課後は朱実と過ごしますか?[n][w][e]

[sel ISHOP_TALK_CORPOK_02_SEL top]
[s]朱実と過ごす[e]
[s]また今度[e]

[msg ISHOP_TALK_CORPOK_03 [郡司 朱実]]
[s]…どうぞ、こっち。[n][w][e]

[msg ISHOP_TALK_CORPOK_04]
[s]コーポイベントが流れます。[n]αでは省略します。[n][w][e]
[s]>朱実と別れて、自宅に帰った…[n][w][e]

[msg ISHOP_TALK_CORPOK_05 [郡司 朱実]]
[s]そう。[n]…お大事、に。[n][w][e]

[msg ISHOP_TALK_CORPNG_01 [郡司 朱実]]
[s]今日は往診で忙しいの。[n]また今度ね。[n][w][e]

[msg ISHOP_TALK_CORPNG_02]
[s]>朱実は忙しそうだ…[n] また今度、話しかけてみよう。[n][w][e]

[msg ISHOP_TALK_CORPNG_DAY_01 [郡司 朱実]]
[s]昼は診察で忙しい…[n]話があるなら夜に…[n][w][e]

[msg ISHOP_TALK_CORPNG_DAY_02]
[s]>朱実は昼間は忙しいようだ。[n] 夜に話しかけてみようか…[n][w][e]

[msg ISHOP_TALK_CORPOK_01_A3 [郡司 朱実]]
[s]今日も元気そうね。[n]まぁ、もっと元気になるÔ薬品もあるんだけど…[n][w][e]
[s]私の新しい薬の治験を協力してくれたら、[n]売ってあげなくもないわよ?[n][w][e]

[msg ISHOP_TALK_CORPOK_01_CLI [郡司 朱実]]
[s]まだ営業中よ、要件は手短に…[n]それとも、私の薬の話かしら…?[n][w][e]

[msg MSG_MISSION_AKEMI_CHECK]
[s]>アケミに何を話そうか…[n][w][e]

[msg ISHOP_TALK_CORPOK_02_A3]
[s]>朱実の薬の治験を手伝えば、[n] より[clr 2]強力な回復アイテム[clr 27]が購入できそうだ…[n] [clr 2]※αでは貰った薬を既に使い切った体で進みます[clr 27][n][w][e]

[msg ISHOP_TALK_CORPOK_02_MIS]
[s]>朱実と何をしようか…[n][w][e]

[msg ISHOP_TALK_CORPOK_02_OK_]
[s]>朱実から渡された[clr 2]治験薬[clr 27]を使い切っている![n][w][e]

[msg WSHOP_TALK_CORPOK_02_NG_]
[s]>しかし、朱実から渡された薬はまだ使い切っていない…[n][w][e]
[s][f 1 5]郡司 朱実[n]まだ私の薬は残ってるみたいね…[n]使い切ったら報告に来て。[n][w][e]

[msg ISHOP_TALK_CORPOK_02_NG_]
[s]>しかし、今日は決行日だ。[n] 朱実と話すのは、また今度にしよう…[n][w][e]

[msg ISHOP_TALK_CORPOK_02_MIS_2]
[s]>そういえば…[n] 朱実と実行するミッションがあったはずだ。[n][w][e]
[s]>このミッション遂行に成功すれば、[n] カツシカワールドのシャドウが弱まりそうだが…[n][w][e]

[sel ISHOP_TALK_CORPOK_02_SEL_2 top]
[s]ミッションを行う[e]
[s]治験に協力する[e]
[s]治験の報告をする[e]
[s]用は無い[e]

[sel ISHOP_TALK_CORPOK_02_SEL_3 top]
[s]奥にµ内してくれ[e]
[s]用は無い[e]

[msg ISHOP_TALK_ZATSUDAN [アケミ]]
[s]言っとくけど…[n]私の薬で何かあっても責任取らないから…[n][w][e]
[s]…それはだから。[n][w][e]

[msg MSG_MISSION_AKEMI_NONE [アケミ]]
[s]あ、そう…[n][w][e]

[msg ISHOP_TALK_CORPOK_03_A3]
[s]>朱実の薬の治験への協力を申し出た…[n][w][e]

[msg ISHOP_TALK_CORPOK_04_A3 [郡司 朱実]]
[s]それじゃあ、この薬を使い切ったら報告に来て…[n][w][e]

[msg ISHOP_TALK_CORPOK_05_A3]
[s]>朱実から[n] [clr 1]試験薬[clr 27]を3個手渡された。[n][w][e]
[s][clr 2]【αでは未実装】[clr 27][n]HPやバステを回復する薬を渡され、[n]使い切って報告すればランクアップする予定です。[n][w][e]

[msg ISHOP_TALK_CORP_CANCEL_0 [郡司 朱実]]
[s]…そう。[n][w][e]

[msg MSG_MISSION_AKEMI_MISSIO [郡司 朱実]]
[s]なに?[n]しかめっ面して…[n][w][e]
[s][f 1 5] [n]>朱実とミッションを行えば、[n] [clr 2]成長を促す特殊な薬[clr 27]が手に入れられるかもしれない…[n][w][e]

[msg MSG_MISSION_AKEMI_MISSIO_2]
[s]>朱実とミッションを行おうか…[n][w][e]

[sel SEL_MISSION_AKEMI_MISSIO top]
[s]ミッション開始![e]
[s]ミッションの内容を確認する[e]
[s]やっぱりやめる[e]

[msg MSG_MISSION_AKEMI_MISSIO_3]
[s]>朱実に協力をお願いしてみた…[n][w][e]

[msg MSG_MISSION_AKEMI_MISSIO_4 [郡司 朱実]]
[s]…また、厄介事。[n]面倒臭いけど…まあ、お互い様ね…[n][w][e]
[s]…ちょっと待ってて。[n]詳しくは閉ï後に聞くわ…[n][w][e]

[msg MSG_MISSION_AKEMI_MISSIO_5]
[s]>閉ï時間を待ち、人気のなくなった診療所で[n] 朱実に協力要請について説明した…[n][w][e]
[s]>…朱実は渋々ながらも、[n] [clr 2]成長促進薬[clr 27]を1つ調合してくれた![n][w][e]
[s]>この薬をëむとその潜入時のみ、[n] [clr 2]経験値が普段より多く[clr 27]もらえるようだ![n][w][e]
[s]>朱実に執♀に疑われる前に、[n] Ôïを後にしよう…[n][w][e]

[msg HELP_MISSION_AKEMI_MISSI [朱実とミッション]]
[s]朱実とミッションを行うと、[n][clr 2]その潜入時のみ経験値ボーナスが入る薬[clr 27]が入手できます。[n][w][e]

[msg MSG_MISSION_AKEMI_CORP [郡司 朱実]]
[s]あの薬、ëんだの…?[n][w][e]
[s][f 1 5] [n]>朱実に薬の治験結果を報告すれば、[n] [clr 2]より強力な回復アイテム[clr 27]が購入できそうだ…[n][w][e]

[sel SEL_MISSION_AKEMI_CORP_C top]
[s]朱実に治験結果を報告する[e]
[s]コーポレイトの機能と属性を確認する[e]
[s]やっぱりやめる[e]

[msg MSG_MISSION_AKEMI_CORP_S]
[s]>朱実に薬の治験が終わった事を伝えた…[n][w][e]

[msg MSG_MISSION_AKEMI_CORP_S_2 [郡司 朱実]]
[s]分かった…[n]じゃあ、こっち来て…[n][w][e]

[msg MSG_MISSION_AKEMI_CORP_F]
[s]>…ドラッグストアの奥へµ内された。[n][w][e]
[s][f 1 5]郡司 朱実[n]じゃあ、結構痛いけど、我慢して…[n][w][e]

[msg MSG_MISSION_AKEMI_CORP_C [郡司 朱実]]
[s]なんだ…[n][w][e]

[msg AKEMI_SYS_CHECK [劇薬ミッションについて]]
[s][clr 2]朱実と劇薬ミッション[clr 27]を行うと、治験慣れした体への[n]ドーピング注射により、日数限定で[clr 2]最大HPが増幅[clr 27]します。[n][w][e]

[msg ISHOP_SAYOUNARA [郡司 朱実]]
[s]…じゃ。[n][w][e]

[msg MSG_MISSION_TEST_DOUGUYA]
[s]>朱実の劇薬ミッションによる[n] [clr 2]最大HPが大きく増加[n][clr 27]する効果は、まだ持続している…[n][w][e]

[msg MSG_MISSION_TEST_DOUGUYA_2 [郡司 朱実]]
[s]平気…?[n]結構、痛いと思うけど…[n][w][e]
[s][f 1 5] [n]>女Ôは心配しつつもワクワクしているようだ…[n][w][e]
[s]>今なら、節制のペルソナ[n]“[clr 1]アプサラス[clr 27]"がいるので、[n] より信用で結ばれそうな気がする…[n][w][e]
[s]>今日は朱実に注射を打ってもらおうか?[n][w][e]

[sel SEL_MISSION_TEST_DOUGUYA top]
[s]無言で腕をまくる[e]
[s]今日はやめとこう[e]

[msg MSG_ISHOP_CORP_00]
[s]>“郡司内科"…[n][w][e]
[s]>まだ日も落ちていないのに、[n] 既に閉ïとしているようだ…[n][w][e]
[s][f 1 5]郡司 朱実[n]これで誰も来ない…[n]誰も邪魔しない…[n][w][e]

[sel SEL_ISHOP_CORP_00 top]
[s]待たせたな[e]
[s]救える命が減ったな[e]

[msg MSG_ISHOP_CORP_01_A [郡司 朱実]]
[s]待ってない。[n]今日も患者、ほぼゼロ。[n][w][e]
[s]ヤバい病気ならデカい病ï行くから。[n]ウチに来るのなんか、風邪だらけ。[n][w][e]

[msg MSG_ISHOP_CORP_01_B [郡司 朱実]]
[s]こんなÔïに救える命なんかない。[n]ヤバい病気ならデカい病ï行けばいい。[n][w][e]

[msg MSG_ISHOP_CORP_02]
[s]>朱実は退屈そうだ…[n][w][e]

[msg MSG_ISHOP_CORP_03 [郡司 朱実]]
[s]じゃ、聞かせて。[n]治験の結果。[n][w][e]

[msg MSG_ISHOP_CORP_04]
[s]>朱実に治験薬の副作用について報告した…[n][w][e]

[msg MSG_ISHOP_CORP_05 [郡司 朱実]]
[s]……。[n][w][e]
[s]…なるほど、原èが分かった。[n]ちょっと待ってて。[n][w][e]

[msg MSG_ISHOP_CORP_08]
[s]>朱実は手際よく、薬を調合し始めた。[n][w][e]
[s]>少し待ってみよう…[n][w][e]

[msg MSG_ISHOP_CORP_10 [郡司 朱実]]
[s]はい、お待たせ。[n]これで完成なはず。[n][w][e]
[s]…ただ、Ü晩寝かせなきゃだから、[n][clr 2]明日¹降[clr 27]に買いに来て。いい?[n][w][e]

[sel SEL_ISHOP_CORP_11 top]
[s]ありがとう[e]
[s]例の副作用はないだろうな?[e]

[msg MSG_ISHOP_CORP_11_A [郡司 朱実]]
[s]礼なんて、要らない。[n][w][e]

[msg MSG_ISHOP_CORP_11_B [郡司 朱実]]
[s]ない。[n]同じ失敗は二度としない。[n][w][e]

[msg MSG_ISHOP_CORP_12 [郡司 朱実]]
[s]……。[n][w][e]
[s]でも、体調—くなったら…すぐ言って。[n][w][e]
[s]貴方は大切な私の、治験体だから…[n][w][e]

[msg MSG_ISHOP_CORP_13]
[s]>……。[n][w][e]
[s]>郡司の薬への自信とともに、[n] 治験体である自分への心遣いを感じる…[n][w][e]

[msg HELP_RANK_UP_DAMMY [道具屋コーポランクアップ]]
[s](コーポレイトランクアップ演出)[n][w][e]

[msg MSG_ISHOP_CORP_14]
[s]>“[clr 2]—魔[clr 27]"コーポのランクが“[clr 2]2[clr 27]"に上がった![n][w][e]
[s]>“[clr 2]—魔[clr 27]"のペルソナを合体で創造する際、[n] [clr 2]合体ボーナスが多く入る[clr 27]ようになった![n][w][e]
[s]>また、[clr 2]Ô薬品のラインナップ[clr 27]が追加された![n][w][e]

[msg MSG_ISHOP_CORP_15 [郡司 朱実]]
[s]…あと、これ。[n]明日からの新しい治験薬。[n][w][e]
[s]今度はもう少し強力だと思う。[n]だから、元気な時にëんで。[n][w][e]
[s][f 1 5] [n]>…![n][w][e]
[s]>見るだけで体に—そうな赤い治験薬だ![n] これは危険な気配がする…[n][w][e]
[s]>…だが、この薬をëみきれば[clr 2]Ô薬品が更に増える[clr 27]。[n] 試せる時に試しておこうか…[n][w][e]
[s]>[clr 2]赤い治験薬[clr 27]を5コ受け取った。[n][w][e]
[s][f 1 5]郡司 朱実[n]……。[n][w][e]
[s]…そうだ。前に言い忘れてたけど、[n]他のÔ者に掛からないでほしい。[n][w][e]
[s]…特に、近くの[clr 2]大学病ï[clr 27]だけはダメ。[n]あそこは…[n][w][e]
[s]…知ってるでしょ?[n][clr 2]Ô療ミス[clr 27]とか[clr 2]黒い噂[clr 27]とか。[n][w][e]

[sel SEL_ISHOP_CORP_15 top]
[s]Ô療ミス?[e]
[s]黒い噂?[e]

[msg MSG_ISHOP_CORP_16 [郡司 朱実]]
[s]……。[n][w][e]
[s]…そっか。[n]君、こっち来たばっか、なんだっけ?[n][w][e]
[s]今の、忘れて。[n]とにかく、他のÔ者には掛からないでね。[n][w][e]
[s]…じゃないと、ヤバいの混ぜるから。[n]いいね?[n][w][e]

[msg MSG_ISHOP_CORP_17]
[s]>…郡司には何かワケがありそうだ。[n] だが今、深入りするのはやめておこう…[n][w][e]

[msg MSG_ISHOP_CORP_18]
[s]>郡司内科を後にした…[n][w][e]

[msg MSG_ISHOP_CORP_M_00]
[s]>ドラッグストア“イジョー"星見坂駅前。[n] 郡司が薬を調合しているようだ…[n][w][e]
[s]>事情をかいつまんで説明してみた…[n][w][e]
[s][f 1 5]郡司 朱実[n]性欲が抑えられる薬…?[n]作れないことはないけど…[n][w][e]
[s]…盛んなの?[n][w][e]

[sel SEL_ISHOP_CORP_M_00 top]
[s]自分がëむワケじゃない[e]
[s]…恥ずかしいんだ[e]

[msg MSG_ISHOP_CORP_M_01_A [郡司 朱実]]
[s]ふーん…[n][w][e]

[msg MSG_ISHOP_CORP_M_01_B [郡司 朱実]]
[s]恥ずかしがることじゃない。[n]生理現象だから。[n][w][e]

[msg MSG_ISHOP_CORP_M_01_TUIK [郡司 朱実]]
[s]でも、分かった…[n]そういうことなら、ちょっと待ってて…[n][w][e]
[s][f 1 5] [n]>朱実は薬棚を漁り始めた…[n][w][e]
[s]>しばらく待ってみよう…[n][w][e]

[msg MSG_ISHOP_CORP_M_02 [郡司 朱実]]
[s]あ…[n]あった…[n][w][e]
[s]…この薬の成分は、ノコギリヤシ。[n]テストステロンの分泌を抑える効果がある…[n][w][e]
[s]…ただ、それに色々混ぜたから、[n]もはやそれだけじゃ済まないと思うけど…[n][w][e]
[s]服用は1年に1回が限度。[n]絶対に食後にëんでね…[n][w][e]

[sel SEL_ISHOP_CORP_M_02 top]
[s]助かる[e]
[s]ずいぶん強力だな…[e]

[msg MSG_ISHOP_CORP_M_02_A [郡司 朱実]]
[s]別にお礼はいい。[n]これ、昔作ったものだし…[n][w][e]
[s]…誰にëませたかは内緒。[n][w][e]

[msg MSG_ISHOP_CORP_M_02_B [郡司 朱実]]
[s]これ、昔作ったものなの…[n][w][e]
[s]…誰にëませたかは内緒。[n][w][e]

[msg MSG_ISHOP_CORP_M_03]
[s]>郡司の目は真剣だ。[n] これがあれば[clr 2]カモシダのÊ常な性欲も抑えられる[clr 27]だろう…![n][w][e]
[s]>[clr 2]朱実åの性欲減退薬[clr 27]を手に入れた![n][w][e]

[msg MSG_ISHOP_CORP_M_04 [郡司 朱実]]
[s]…でも、やっぱり不健全。[n]成長期にはみんな経験することだから…[n][w][e]
[s]それとも、女子に興味ないのかな…?[n][w][e]

[msg MSG_ISHOP_CORP_M_05]
[s]>郡司の怪しむ目を交わしつつ、店を出た…[n][w][e]
[s]※翌朝、鴨志田のファンを装って、[n] “色欲減退薬"をしのばせる小イベントが発生する予定です。[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM [郡司 朱実]]
[s]何度も言うけど、[n]私の薬で何があっても知らないから…[n][w][e]
[s]けど、効き目は抜群だからそれだけは信用して…[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM_ [郡司 朱実]]
[s]ゴメン、今忙しい。[n][w][e]
[s]用なら[clr 2]夜[clr 27]にして。[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__2]
[s]>朱実は試験管を揺らして暇そうにしている…[n][w][e]

[sel SEL_MISSION_TEST_D_ITEM_ top]
[s]頼みたいことがある[e]
[s]今日は時間がある[e]
[s]特に用はない[e]

[msg MSG_MISSION_TEST_D_ITEM__3 [郡司 朱実]]
[s]……。[n][w][e]
[s]暇潰しになりそうなら、聞くけど…[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__4]
[s]>朱実の[clr 2]不思議なクスリ[clr 27]をうまく利用すれば、[n] カモシダを“[clr 2]不思議な気持ち[clr 27]"にさせられそうだ…[n][w][e]

[sel SEL_MISSION_TEST_D_ITEM__2 top]
[s]とある薬を用Äしてほしい[e]
[s]朱実との作戦の効果を確認する[e]
[s]朱実のコーポレイト属性を確認する[e]
[s]今度伝える[e]

[msg SEL_MISSION_TEST_D_ITEM__3 [郡司 朱実]]
[s]…面白そうだから、聞いてあげる。[n][w][e]
[s]今、閉ïにしてくる。[n]ちょっと待ってて…[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__5]
[s]>朱実に“自分がëむ"と偽って、[n] 不思議なクスリを作成してもらった![n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__6]
[s]>明日の朝、カモシダのëみ物に[n] こっそり混ぜておこう…[n][w][e]

[msg HELP_MISSION_TEST_D_ITEM [カモシダ薬漬け作戦成功!]]
[s]明日のみ、カモシダワールド内のシャドウが[n][clr 2]戦闘開始時、Ü定確率でネズミ状態となります[clr 27]。[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__7]
[s]>だが、朱実の薬にはまだためらいが残っている…[n][w][e]
[s]>もっと[clr 2]朱実との関係が深まれば[clr 27]、[n] 朱実は更に強い薬を作ってくれる気がする…[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__8]
[s]>朱実に“自分がëむ"と偽って、[n] 不思議なクスリを作成してもらった![n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__9]
[s]>明日の朝、カモシダのëみ物に[n] こっそり混ぜておこう…[n][w][e]

[msg HELP_MISSION_TEST_D_ITEM_2 [カモシダ薬漬け作戦成功!]]
[s]明日から2日間、カモシダワールド内のシャドウが[n][clr 2]戦闘開始時、Ü定確率でネズミ状態となります[clr 27]。[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__10]
[s]>だが、朱実の薬にはまだためらいが残っている…[n][w][e]
[s]>もっと[clr 2]朱実との関係が深まれば[clr 27]、[n] 朱実は更に強い薬を作ってくれる気がする…[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__11]
[s]>朱実に“自分がëむ"と偽って、[n] 不思議なクスリを作成してもらった![n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__12]
[s]>明日の朝、カモシダのëみ物に[n] こっそり混ぜておこう…[n][w][e]

[msg HELP_MISSION_TEST_D_ITEM_3 [カモシダ薬漬け作戦成功!]]
[s]明日から3日間、カモシダワールド内のシャドウが[n][clr 2]戦闘開始時、Ü定確率でネズミ状態となります[clr 27]。[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__13]
[s]>だが、朱実の薬にはまだためらいが残っている…[n][w][e]
[s]>もっと[clr 2]朱実との関係が深まれば[clr 27]、[n] 朱実は更に強い薬を作ってくれる気がする…[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__14]
[s]>そろそろ朱実との関係がもっと深まる気がする…[n][w][e]
[s]>Ôïを後にし、家に帰った…[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__15]
[s]>Ôïを後にし、家に帰った…[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__16 [郡司 朱実]]
[s]気になるんだけど…[n][w][e]
[s]…まあ、良い。[n]どうせいつもヒマだから…[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__17 [郡司 朱実]]
[s]…私もヒマ。[n][w][e]
[s]別にずっとここにいればいい。[n]薬の話くらいしかできないけど。[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__18]
[s]>朱実との関係が深まれば、[n] 怪盗団にとって[clr 2]有利なこと[clr 27]が起こりそうだ…[n][w][e]
[s]>今なら、死神のペルソナ“[clr 1]ウコバク[clr 27]"がいるので、[n] より関係が深まりそうな気がする…[n][w][e]

[sel SEL_MISSION_TEST_D_ITEM__4 top]
[s]是非聞かせてくれ[e]
[s]朱実のコーポレイト属性を確認する[e]
[s]朱実との作戦の効果を確認する[e]
[s]用を思い出した[e]

[msg MSG_MISSION_TEST_D_ITEM__19 [郡司 朱実]]
[s]分かった…[n]ちょっとここで待ってて…[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__20]
[s]>閉ïとなった郡司Ôïで薬の話をした。[n][w][e]
[s]>近くに大学病ïがあること、[n] Ô療ミスで黒い噂が流れていることを聞いた…[n][w][e]
[s]>朱実と時間を過ごし、[n] 少し朱実のことが分かった気がする…[n][w][e]

[msg HELP_MISSION_TEST_D_ITEM_4 [朱実コーポレイト]]
[s]朱実とのコーポランクが“[clr 2][var 1][clr 27]"になりました![n][w][e]

[msg HELP_MISSION_TEST_D_ITEM_5 [郡司 朱実]]
[s]…貴方がいないとヒマ。[n]だから、健康でいて。[n][w][e]
[s]貴方が望んだ薬なら、[n]いくらでも作るようにするから…[n][w][e]
[s][f 1 5] [n]>信用関係が深まったことで、朱実との作戦に[n] もっと[clr 2]大きい効果[clr 27]が期待できそうだ![n][w][e]
[s]>今度、朱実にお願いしてみようか…[n][w][e]

[msg HELP_MISSION_TEST_D_ITEM_6 [薬漬け作戦 効果UP!]]
[s]薬漬け作戦で得られるネズミ効果の[n]継続日数が1日から2日になりました![n][w][e]

[msg HELP_MISSION_TEST_D_ITEM_7 [薬漬け作戦 効果UP!]]
[s]薬漬け作戦で得られるネズミ効果の[n]継続日数が2日から3日になりました![n][w][e]

[msg HELP_MISSION_TEST_D_ITEM_8]
[s]>Ôïを後にし、家に帰った…[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__21 [郡司 朱実]]
[s]なんだ…[n][w][e]
[s]どうせ、ヒマだから…[n]また今度来て…[n][w][e]

[msg MSG_MISSION_TEST_D_ITEM__22 [郡司 朱実]]
[s]あ、そう…[n][w][e]

[msg HELP_ITEM_CORP [朱実コーポレイト]]
[s]朱実コーポレート ランク“[clr 2][var 0][clr 27]"[n]アルカナ属性は“[clr 1]死神[clr 27]"。[n][w][e]

[msg HELP_ITEM_MISSION [カモシダ薬漬け作戦]]
[s]朱実特性の不思議なクスリをカモシダにëませて、[n][clr 2]Ü定期間、シャドウがネズミとなる[clr 27]効果を得ます。[n][w][e]
[s]効果の継続日数はコーポランクに比例します。[n]現在、朱実とのコーポレイトランクは[clr 2][var 0][clr 27]です。[n][w][e]

[msg MSG_GUNJI_TALK_CORP_BEFO [郡司 朱実]]
[s]用が済んだら帰って…[n]今、忙しいの…[n][w][e]

[msg MSG_GUNJI_TALK_CORP_OK]
[s]>朱実を協力者に招き入れれば[n] もっと強力な薬が手に入るかもしれない…[n][w][e]
[s]>朱実に協力者を求めますか?[n] ※コーポ解禁仮処理[n][w][e]

[sel SEL_GUNJI_TALK_CORP_OK top]
[s]協力してもらう[e]
[s]今はやめておく[e]

[msg MSG_GUNJI_TALK_CORP_A4_S [郡司 朱実]]
[s]…今はヒマ。[n][w][e]
[s]別にずっとここにいればいい。[n]薬の話くらいしかできないけど。[n][w][e]

[msg MSG_GUNJI_TALK_CORP_A4_S_2 [郡司 朱実]]
[s]ゴメン、今忙しい。[n][w][e]
[s]用なら[clr 2]夜[clr 27]にして。[n][w][e]

[msg MSG_GUNJI_TALK_CORP_A4_C]
[s]>朱実は試験管を揺らして暇そうにしている…[n][w][e]

[msg MSG_GUNJI_TALK_CORP_A4_C_2]
[s]>朱実との関係が深まれば、[n] 怪盗団にとって[clr 2]有利なこと[clr 27]が起こりそうだ…[n][w][e]
[s]>今なら、死神のペルソナ“[clr 1]ウコバク[clr 27]"がいるので、[n] より関係が深まりそうな気がする…[n][w][e]

[sel SEL_GUNJI_TALK_CORP_A4_C top]
[s]話を聞かせてくれ[e]
[s]朱実のコーポレイト属性を確認する[e]
[s]特に用はない[e]

[msg MSG_GUNJI_TALK_CORP_A4_E [郡司 朱実]]
[s]分かった…[n]ちょっとここで待ってて…[n][w][e]

[msg HELP_GUNJI_CORP_ATTRIBUT [朱実コーポレイト]]
[s]朱実コーポレート ランク“[clr 2][var 0][clr 27]"[n]アルカナ属性は“[clr 1]死神[clr 27]"。[n][w][e]

[msg MSG_GUNJI_TALK_CORP_A4_C_3 [郡司 朱実]]
[s]なんだ…[n][w][e]
[s]どうせ、ヒマだから…[n]また今度来て…[n][w][e]

[msg MSG_GUNJI_TALK_INJECTION [郡司 朱実]]
[s]…何か用事?[n][w][e]

[sel SEL_GUNJI_TALK_INJECTION top]
[s]注射を打ってくれ[e]
[s]話を聞かせてくれ[e]
[s]特に用はない[e]

[msg MSG_INGECTION_START [郡司 朱実]]
[s]…どの注射をするの?[n][w][e]

[sel SEL_INGECTION_LIST top]
[s]HPアップ    8000円[e]
[s]SPアップ   15000円[e]
[s]バステ予防   20000円[e]
[s]耐性無効    18000円[e]
[s]やっぱりやめる[e]

[msg MSG_INGECTION_NO_MONEY [郡司 朱実]]
[s]お金が無いなら注射は打てない…[n]こっちもÜ応商売だから…[n][w][e]

[msg MSG_INGECTION_CHECK [郡司 朱実]]
[s]注射を打ったら[n]夜まで®静にしてもらうけど、いい?[n][w][e]

[sel SEL_INGECTION_CHECK top]
[s]1本頼む[e]
[s]やっぱりやめる[e]

[msg HELP_INGECTION_HPUP]
[s]HP上限アップ効果を得ました。[n]※仮メッセージです[n][w][e]

[msg HELP_INGECTION_SPUP]
[s]SP上限アップ効果を得ました。[n]※仮メッセージです[n][w][e]

[msg HELP_INGECTION_BUTST]
[s]バステ予防の効果を得ました。[n]※仮メッセージです[n][w][e]

[msg HELP_INGECTION_PRO]
[s]属性無効の効果を得ました。[n]※仮メッセージです[n][w][e]

