[sel NAME_ENTRY_CHECK top]
[s]I'm finished.[e]
[s]Let me rewrite that.[e]

[msg NAME_ENTRY_CONF]
[s][f 4 2] [f 4 1].[n]That is my name.[n][w][e]

[msg NAME_ENTRY_CONF_PHANTOM]
[s][f 4 28].[n]Let's go with this name.[n][w][e]

[msg NAME_ENTRY_NG_WORD]
[s]I can't use that name... I should[n]choose a different one.[n][w][e]

[msg NAME_ENTRY_MY_NAME]
[s]I can't use that name... I should[n]choose a different one.[n][w][e]

