[sel YESNO_SEL top]
[s]Yes[e]
[s]No[e]

[msg MSG_000_000_00]
[s]Dummy[n][w][e]

[msg fev0409_11_mes01]
[s][vp 1 0 0 0 0 0]It's late... It seems like I've[n]been cleaning for a while.[n][w][e]

[msg fev0409_11_mes02 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5001 65535 0]What the heck? I heard you making all[n]sorts of noise up here but I didn't think[n]you were cleaning.[n][w][e]

[msg fev0409_11_mes03 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5086 65535 0]Actually, the place doesn't look too bad.[n][w][e]

[msg fev0409_11_mes04 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Though it's only natural you'd want[n]to keep your room tidy.[n][w][e]

[msg fev0409_11_mes05 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5074 65535 0]Why don't you go to bed for tonight?[n]You don't have anything better to be[n]doing, right?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I'm going to close up shop and[n]get out of here myself.[n][w][e]

[msg fev0409_11_mes06 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, and here's some sheets.[n]Don't worry, they're clean.[n][w][e]

[msg fev0409_11_mes07]
[s][vp 1 0 0 0 0 0]These sheets are not only thin,[n]but clearly cheap as well...[n][w][e]

[msg fev0409_11_mes08 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I won't be the one looking after you[n]if you get sick from staying up too late,[n]you got that?[n][w][e]

[msg fev0409_11_mes09]
[s][vp 1 0 0 0 0 0]Sleeping in your bed will[n]move you forward one day.[n][w][e]

