[sel YESNO_SEL top]
[s]Yes[e]
[s]No[e]

[msg NIGIYAKADANSI_grt_A_01]
[s]He ran off so fast.[n]What's going on?[n][f 1 2 65535][e]

[msg NIGIYAKADANSI_grt_B_01]
[s]Hey, what the hell!?[n]You coulda ran into me![n][f 1 2 65535][e]

[msg NIGIYAKADANSI_grt_C_01]
[s]What's with that blond guy!?[n]He looked seriously angry.[n][f 1 2 65535][e]

[msg NIGIYAKADANSI_grt_D_01 [Hesitant Teacher]]
[s][vp 1 0 0 0 0 0]Oh no... Maybe we should bring him[n]in ahead of schedule? It's up to the[n]principal though...[n][f 1 3 65535][w][e]

