[sel YESNO_SEL top]
[s]Yes[e]
[s]No[e]

[msg MSG_DET_INFO_GOT_ENOUGH [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]I think we might be good to go[n]back to Taihei now.[n][w][e]

[msg MSG_DET_INFO_GOT_ALL [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]I think we've already learned all that we[n]possibly could. Let's go see Taihei.[n][w][e]

[msg MSG_DET_INFO_NEXT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Let's go look for anything else we[n]might be able to learn.[n][w][e]

[msg MSG_DET_BECKY_01 [Female Student Who Likes Sweets]]
[s][f 4 23 1 801 3 10 0 10]Is Ms. Kawakami's name actually "Becky"?[n]Hahaha, no, no, that's not it at all.[n][w][e]
[s]Ms. Kawakami used to work at a pastry[n]shop called "Becky" back when she was[n]a student though.[n][w][e]
[s]Huh. I wonder if that place is still around.[n]I think I'll try looking for it sometime...[n][w][e]

[msg MOR_DET_BECKY_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]I see. So Kawakami took the name she[n]uses in her work as a maid from there.[n][w][e]

[msg MSG_DET_BECKY_RE [Female Student Who Likes Sweets]]
[s][f 4 23 1 801 3 10 0 10]I should go eat at that pastry shop,[n]"Becky," sometime...[n][w][e]

[msg MSG_DET_BECKY_MISHIMA [Female Student Who Likes Sweets]]
[s][f 4 23 1 801 3 10 0 10]What the heck was up with that boy[n]from Class D, the one who used to be[n]on the volleyball team?[n][w][e]
[s]Hey... I don't feel like talking right now.[n]Would you mind leaving me alone?[n][w][e]

[msg MOR_DET_BECKY_MISHIMA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]She better not be talking about Mishima...[n][w][e]

