[sel YESNO_SEL top]
[s]Yes[e]
[s]No[e]

[msg MSG_017_0_0 [Motivated First-Year]]
[s][f 4 23 1 859 3 10 0 0][vp 8 2 1 0 859 0]Hey, wasn't that Sakamoto-senpai?[n]I saw him going up the stairs...[n][w][e]

[msg MSG_018_0_0 [Energetic First-Year]]
[s][f 4 23 1 860 3 10 0 0][vp 8 2 1 0 860 0]Maybe he called someone up there[n]so he can punch them.[n][w][e]

[msg MSG_019_0_0 [Motivated First-Year]]
[s][f 4 23 1 859 3 10 0 0][vp 8 2 1 0 859 0]Oh, do you mean like what happened[n]at track practice last year? I heard it[n]was a big fight...[n][w][e]

[msg MSG_020_0_0 [Energetic First-Year]]
[s][f 4 23 1 860 3 10 0 0][vp 8 2 1 0 860 0]Stay away from him! We only just[n]started high school... I'm too young[n]to die![n][w][e]

[msg MSG_033_0_0 [Proper First-Year]]
[s][f 4 23 1 857 3 10 0 0][vp 8 2 1 0 857 0]There have been far too many[n]accidents lately.[n][w][e]
[s][vp 8 2 1 0 857 0]What's the point of waking up early[n]if my train's just going to get to[n]the station late?[n][w][e]

[msg MSG_034_0_0 [Gossiping First-Year]]
[s][f 4 23 1 858 3 10 0 0][vp 8 2 1 0 858 0]You mean accidents like that train[n]engineer going crazy, right?[n][w][e]
[s][vp 8 2 1 0 858 0]I saw a photo of him online...[n]His face was totally messed up.[n][w][e]
[s][vp 8 2 1 0 858 0]Plus I heard some kid's parents were[n]on that train and are in critical[n]condition now...[n][w][e]

[msg MSG_035_0_0 [Proper First-Year]]
[s][f 4 23 1 857 3 10 0 0][vp 8 2 1 0 857 0]D-Don't be so gullible.[n][w][e]

[msg MSG_036_0_0 [Scared Male Student]]
[s][f 4 23 1 861 3 10 0 0][vp 8 2 1 0 861 0]Have you seen that transfer student[n]everyone's talking about? How does[n]he look? Tough?[n][w][e]

[msg MSG_037_0_0 [Talkative Male Student]]
[s][f 4 23 1 862 3 10 0 0][vp 8 2 1 0 862 0]Nah, I heard he actually dresses[n]kinda plain.[n][w][e]

[msg MSG_038_0_0 [Scared Male Student]]
[s][f 4 23 1 861 3 10 0 0][vp 8 2 1 0 861 0]He's probably just hiding his true[n]self under that. I'll make sure not[n]to cross him...[n][w][e]

[msg MSG_039_0_0 [Talkative Male Student]]
[s][f 4 23 1 862 3 10 0 0][vp 8 2 1 0 862 0]Yeah, I bet he's a totally different[n]person when he's mad. I heard he[n]almost killed someone.[n][w][e]

[msg MSG_SUZUI_000_00 [Injured Female Student]]
[s][bup 0 212 5 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]It still kind of hurts...[n][w][e]

[sel SEL_SUZUI_001_00 top]
[s]Did something happen?[e]
[s]Let me through.[e]

[msg MSG_SUZUI_002_00 [Injured Female Student]]
[s][bup 0 212 4 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Huh...?[n][w][e]

[msg MSG_SUZUI_003_00 [Injured Female Student]]
[s][f 4 23 1 855 3 10 0 0][bup 0 212 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Oh, no... I'm okay. I've just been spacing[n]out a little...[n][w][e]

[msg MSG_SUZUI_003_01 [Injured Female Student]]
[s][f 4 23 1 855 3 10 0 0][bup 0 212 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Oh, am I in the way...? Sorry, I've just[n]been spacing out a little bit lately...[n][w][e]

[msg MSG_SUZUI_004_00 [Injured Female Student]]
[s][bup 0 212 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Wait... Are you that new[n]transfer student from Class D?[n][w][e]

[sel SEL_SUZUI_005_00 top]
[s]Surprised you recognize me.[e]
[s]You've got the wrong guy.[e]

[msg MSG_SUZUI_006_00 [Injured Female Student]]
[s][f 4 23 1 855 3 10 0 0][bup 0 212 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Well, everyone has been talking[n]about you...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Don't worry about the rumors though.[n]I'm sure they're just surprised for now.[n][w][e]

[msg MSG_SUZUI_006_01 [Injured Female Student]]
[s][f 4 23 1 855 3 10 0 0][bup 0 212 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Huh? You don't need to lie.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 855 0]By the way, I don't mind what they[n]say in the rumors. I wouldn't[n]believe that stuff without proof.[n][w][e]

[msg MSG_SUZUI_007_00 [Injured Female Student]]
[s][bup 0 212 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]...A lot of people misunderstand[n]my best friend because of how[n]she looks too.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 855 0]It's not good to assume you know[n]a person just by looking at them,[n]don't you think?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Well, if you even need help,[n]I'd be glad to—[n][w][e]
[s][bup 0 212 5 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Ow... Not again...[n][w][e]

[sel SEL_SUZUI_008_00 top]
[s]Where is the rooftop?[e]
[s]Are you hurt?[e]

[msg MSG_SUZUI_009_00 [Injured Female Student]]
[s][f 4 23 1 855 3 10 0 0][bup 0 212 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Oh, um... It's right up these stairs.[n][w][e]

[msg MSG_SUZUI_009_01 [Injured Female Student]]
[s][f 4 23 1 855 3 10 0 0][bup 0 212 4 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Oh, yeah... I kind of hurt my shoulder[n]during volleyball.[n][w][e]
[s][bup 0 212 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]But, um... I'm all right. Don't worry[n]about me.[n][w][e]

[msg MSG_SUZUI_010_00 [Injured Female Student]]
[s][bup 0 212 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Well, sorry for stopping you[n]so suddenly here.[n][w][e]
[s][bup 0 212 3 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]I should be getting to practice,[n]so... see you around.[n][w][e]

[msg MSG_SUZUI_100_00 [Injured Female Student]]
[s][bup 0 212 5 0 0][f 4 10 65535 0 0][vp 8 2 1 0 856 0]I have to hurry to practice... I'll be[n]in trouble if I don't get there on time.[n][w][e]
[s][bup 0 212 2 0 0][vp 8 2 1 0 856 0]......[n][w][e]
[s][bup 0 212 3 0 0][f 4 10 65535 0 0][vp 8 2 1 0 856 0]I wonder if running away will solve[n]all my problems...[n][w][e]

[msg MSG_1ST_CONTACT_HARU_000 [Gentle Teacher]]
[s][f 4 23 1 856 3 10 0 0][vp 8 2 1 0 856 0]By the way, thank you for volunteering to[n]take care of the planters.[n][w][e]

[msg MSG_1ST_CONTACT_HARU_010 [Mature Third-Year]]
[s][f 4 23 1 855 3 10 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 3182 65535 0]Oh, it's no trouble. I'm not sure I'm up to[n]the task though...[n][w][e]

[msg MSG_1ST_CONTACT_HARU_011 [Gentle Teacher]]
[s][vp 8 2 1 0 856 0]Don't worry. You're being a huge help.[n][w][e]
[s][vp 8 2 1 0 856 0]Oh, and I'll make sure the roof is unlocked[n]for you... I imagine it's going to be a lot of[n]work, but I'm sure you can handle it.[n][w][e]

[msg MSG_1ST_CONTACT_HARU_012 [Mature Third-Year]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 3164 65535 0]Alright, I'll do my best! I'll go take a look at[n]them later.[n][w][e]

