[sel YESNO_SEL top]
[s]Yes[e]
[s]No[e]

[msg MSG_000_000_00]
[s]Dummy[n][w][e]

[msg MSG_E24320100_ANN_001_00 [Noncommittal Man]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]Hey, girl! If you're free, how 'bout a date?[n]You look so cute I just had to talk to you![n][w][e]

[msg MSG_E24320100_ANN_002_00 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ugh, not again...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I guess there's still a chance he might[n]know something... Fine, let's do this.[n][w][e]

[msg MSG_E24320100_ANN_003_00 [Ann]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, but isn't the mafia around here?[n]I'm sooooo scared...[n][w][e]

[msg MSG_E24320100_ANN_004_00 [Noncommittal Man]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]Yeah, I know. They're real frightening[n]guys, huh?[n][w][e]
[s][vp 8 2 1 0 850 0]Don't worry though, you'll be safe with me.[n]I have all sorts of connections around here.[n][w][e]

[msg MSG_E24320100_ANN_005_00 [Ann]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Wooow, you must know sooo much![n]Actually, I'm kinda interested in stories[n]about the mafia...[n][w][e]

[msg MSG_E24320100_ANN_006_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 850 0]She's turned the pickup attempt[n]back on him to try and get info![n]Lady Ann is incredible![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 850 0]Although her acting could use[n]some work... Godspeed.[n][w][e]

[msg MSG_E24320100_ANN_101_00 [Noncommittal Man]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]If you wanna talk, we should go[n]somewhere private. Maybe karaoke?[n][w][e]

[msg MSG_E24320100_ANN_102_00 [Ann]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ummmmmm... I... I... I'm really afraid[n]of tambourines! Can't we just talk here[n]instead?[n][w][e]

[msg MSG_E24320100_STUDENTFEM [Stylish Kosei Girl]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]Ooh, I think I might buy this. By the way,[n]wanna stop by Central Street later?[n][w][e]

[msg MSG_E24320100_STUDENTFEM_2 [Worrying Kosei Girl]]
[s][f 4 23 1 852 3 10 0 0][vp 8 2 1 0 852 0]Not today. Aren't there supposed[n]to be mafia in Shibuya?[n][w][e]
[s][vp 8 2 1 0 852 0]My parents are all worried now too after[n]they heard it was mostly young people[n]getting targeted...[n][w][e]

[msg MSG_E24320100_STUDENTFEM_3 [Stylish Kosei Girl]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]Oh yeah, I've heard that from the teachers.[n]There are even police patrolling there to[n]warn students.[n][w][e]

[msg MSG_E24320100_STUDENTFEM_4 [Worrying Kosei Student]]
[s][f 4 23 1 852 3 10 0 0][vp 8 2 1 0 852 0]I wonder if any of the victims have been[n]from Kosei... I do get lots of strange spam[n]messages...[n][w][e]

[msg MSG_E24320100_STUDENTFEM_5 [Worrying Kosei Girl]]
[s][f 4 23 1 852 3 10 0 0][vp 8 2 1 0 852 0]We'll be safe if we're inside, right?[n]I just want to shop in peace...[n][w][e]

[msg MSG_E24320100_STUDENTFEM_6 [Stylish Kosei Girl]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]I'm sure it'll be okay as long as we avoid[n]anywhere sketchy.[n][w][e]

[msg MSG_E24320100_ENDINFO_SH [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]There fewer students around[n]than I expected.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Lady Ann has this area covered, so we[n]should head over to Central Street.[n][w][e]

[msg MSG_E24320100_ENDINFO_SH_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]It seems like news about the mafia[n]is getting to be quite prevalent.[n]I wish we had more details...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Hm, where else do people hang out?[n]Maybe in the square in front of the[n]station? Let's check it out.[n][w][e]

[sel SEL_E24320100_ENDINFO_SH top]
[s]Bring it on.[e]
[s]I'm too tired.[e]

[msg MSG_E24320100_ENDINFO_SH_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Whoa, I like that fire![n][w][e]

[msg MSG_E24320100_ENDINFO_SH_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]I guess we did walk a lot. Just hang[n]in there for a little bit longer, okay?[n][w][e]

[msg MSG_E24320100_ENDINFO_SH_5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]There should be all sorts of people[n]there, so we might get some interesting[n]information.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]All right! Next stop, the square[n]in front of the station![n][w][e]

