[msg TalkMsg_DUMMY]
[s]......[n][w][e]

[msg TalkMsg_GUY_CONTACT_01]
[s]Heavens, I should never have gone[n]out today.[n][w][e]

[msg TalkMsg_GUY_CONTACT_02]
[s]...Ow, ouch! You're quite brutish for a[n]phantom thief, are you not?[n][w][e]

[msg TalkMsg_GUY_CONTACT_03]
[s]My word, this has been quite a day...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01]
[s]I can't quite fathom why any of this[n]is happening.[n][w][e]
[s]Care to explain yourself? I certainly hope[n]you have a good reason for this boorish[n]treatment.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_01 top]
[s]That would take a while.[e]
[s]There's no need to explain.[e]
[s]Just shut up...[e]

[msg TalkMsg_GUY_CHAT_FQ_01_R]
[s]Oh, that doesn't matter. What's more[n]important is that you explain your[n]behavior to my satisfaction.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_2]
[s]I doubt your circumstances are that[n]complicated, but...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_3]
[s]In that case, would you distill it to just the[n]main points, then?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_4]
[s]Do you honestly expect me to sit here like[n]this while you list all your feeble excuses?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_5]
[s]Oh? In that case, I demand you explain to[n]me why there is no need for you to explain.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_6]
[s]Are you aware that doesn't answer my[n]question?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_7]
[s]I'm inclined to disagree. I may be a hostage,[n]but you still require my cooperation, yes?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_8]
[s]Ahh, you're such a troublesome human.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_9]
[s]Well, if your explanation is to my satisfaction[n]and I find it reasonable... Perhaps I will.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_10]
[s]Apologies, but I simply can't concede[n]to your demands without any sort of[n]explanation.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_11]
[s]Oh, you are a brutish child. Must you really[n]be so overbearing?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_12]
[s]I don't see how that would benefit anyone[n]other than you. No. No, I shall not shut up[n]and die.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_13]
[s]Ah, so you never had any sort of reason at[n]all...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_14]
[s]Really, I don't see why you should be angry[n]at me. I'm the victim here, am I not?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_15]
[s]...Such a vulgar child.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_16]
[s]Ah, I wish to return home...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02]
[s]Excuse me, I believe this can be considered[n]sexual harassment.[n][w][e]
[s]I insist you surrender yourself to the[n]authorities.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_02 top]
[s]This is a misunderstanding.[e]
[s]I apologize.[e]
[s]You've got the wrong idea.[e]

[msg TalkMsg_GUY_CHAT_FQ_02_R]
[s]Ah, but most men say that after the fact.[n]Am I not right?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_2]
[s]A misunderstanding? Do remember that I[n]was the one who was harassed. You touched[n]me amidst the confusion, didn't you?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_3]
[s]Are you suggesting that you could not resist?[n]Perhaps crying myself to sleep is now my[n]only recourse.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_4]
[s]Nonetheless... I am feeling quite agitated.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_5]
[s]Very well. I suppose that I should[n]acknowledge your integrity.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_6]
[s]Oh? And can I assume that you will[n]apologize to the authorities as well?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_7]
[s]If you think you'll have to apologize later,[n]shouldn't that act as a deterrent for your[n]bad behavior in the first place?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_8]
[s]Do remember that some acts cannot be[n]forgiven even with an apology.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_9]
[s]...Even so, has it not occurred to you that[n]your behavior until now has been crass[n]and immoral?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_10]
[s]I've no intention of arguing with you.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_11]
[s]Truly? In that case, I suppose I should[n]apologize. This sort of thing tends to[n]happen more often than I'd like to admit.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_12]
[s]Are you defiantly playing the role of victim?[n]I've never met anyone as abominable as[n]you...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_13]
[s]Are you really attempting to harm me[n]without touching me? What outrageous[n]behavior...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_14]
[s]When a man like you is swept up by emotion[n]and behaves impulsively, he appears base[n]and petty.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_15]
[s]If you don't like something, you should[n]simply say so. You're quite the malicious[n]brat, aren't you?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_16]
[s]I am not your mother. I refuse to overlook[n]your impertinence.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03]
[s]Excuse me? Learn to read the mood...[n][w][e]
[s]I've been projecting a "don't speak to me"[n]aura towards you.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_03 top]
[s]I noticed.[e]
[s]I didn't feel an "aura."[e]
[s]But we may never meet again.[e]

[msg TalkMsg_GUY_CHAT_FQ_03_R]
[s]...You noticed, yet you still approached me?[n]Are you a human who values instinct over[n]intellect?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_2]
[s]I did see you're quite young for a human.[n]Perhaps you lack the skill to follow up on it.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_3]
[s]...I suppose you're the kind of person who[n]claims to do things differently than everyone[n]else...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_4]
[s]If you've noticed, then you should take the[n]next step and process what that information[n]means.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_5]
[s]Is that so? Strange. Well, I'll try to intensify[n]my vibes so that it's more clear to you, then.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_6]
[s]Yes, well, that problem lies with you,[n]the recipient. I'm afraid you must be[n]rather insensitive.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_7]
[s]Hearing it put like that offends me[n]somehow. So you were in my presence[n]and felt nothing?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_8]
[s]There is nothing worse than meeting[n]someone who cannot feel your aura.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_9]
[s]Perhaps, but you should be more[n]considerate. Leave people alone if[n]they wish to be left alone.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_10]
[s]But if you cannot feel my aura... Sigh.[n]I suppose it does not matter, in the end...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_11]
[s]You're glad to have met me, is that it?[n]Well, I'm flattered...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_12]
[s]It pains me to hear you use such a[n]hackneyed turn of phrase, especially[n]when it's not apropos.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_13]
[s]How peculiar. I'm fairly certain I've never[n]consented to you firing your gun like that.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_14]
[s]Um... You do understand that I neither[n]want to be in this situation nor involved[n]with you...?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_15]
[s]Perhaps I am expressing myself too poorly[n]to you, but that was simply unnecessary.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_16]
[s]Ah, if you're upset about me insinuating[n]that you are a dolt, then I applaud you[n]for noticing.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04]
[s]I must ask, was there something you desired[n]of me?[n][w][e]
[s]I am inclined to turn you down, but if you[n]still wish to speak, I will perhaps consider it.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_04 top]
[s]You have nothing I want.[e]
[s]Do you have time?[e]
[s]Don't turn me down.[e]

[msg TalkMsg_GUY_CHAT_FQ_04_R]
[s]You ask nothing of me, yet this is how[n]you treat me? I expected better from[n]you humans...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_2]
[s]In that case, I want nothing to do with you,[n]either.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_3]
[s]So I was simply a detour on the way to your[n]true objective? Hm... how unfortunate for[n]me.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_4]
[s]I did state that I may refuse you, but I[n]never expected you to have no demands[n]whatsoever...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_5]
[s]...If you had intended to ask me out—and[n]I'm sure you had—your approach requires[n]improvement.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_6]
[s]This is the way you show your interest in[n]me? ...You are utterly hopeless.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_7]
[s]Honestly... Do I look like I have time to deal[n]with this nonsense?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_8]
[s]Yes, in the sense that I don't know what will[n]happen from here on forth.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_9]
[s]Whether or not I do will depend entirely on[n]our conversation henceforth. But at least[n]now I understand how you feel.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_10]
[s]As I said, that was only a premise.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_11]
[s]Saying such a thing with a gun in your hand[n]makes it a threat, you know.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_12]
[s]What a pretentious young man... Your[n]behavior is rather disturbing.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_13]
[s]Ah, I apologize if you found my manner of[n]speaking unkind.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_14]
[s]Please just tell me what you want already.[n]You are prepared for my refusal, are you[n]not?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_15]
[s]You can ask me whatever you like. I am[n]simply stating that I also have a choice.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_16]
[s]A crude human like you should be grateful[n]that I even deign to speak to you.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05]
[s]Excuse me, why are you taking so much[n]anger out on me?[n][w][e]
[s]What is irritating you so much?[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_05 top]
[s]Rotten adults.[e]
[s]Egotistical women.[e]
[s]I'm not irritated.[e]

[msg TalkMsg_GUY_CHAT_FQ_05_R]
[s]That's a sentiment I only usually hear from[n]spoiled brats.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_2]
[s]May I remind you that you're the one[n]pointing a gun? Who is the rotten one[n]here?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_3]
[s]But again, why are you taking your anger[n]out on me?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_4]
[s]I will admit, there are adults that even I find[n]impossible to deal with.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_5]
[s]Oh, the type that nobody wants to deal[n]with. Don't you hate it when they come[n]to talk to you?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_6]
[s]I guess they can't stand not being the focus[n]of attention. Which is why they get left out[n]in the first place.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_7]
[s]Is your anger leading you to make poor[n]judgments? You are capable of reason,[n]aren't you?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_8]
[s]If I may say so, there is no great difference[n]between women like that and men like you.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_9]
[s]Well, I didn't expect you to say that. I don't[n]quite understand your actions then, but...[n]ah well.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_10]
[s]So... you're forcing me to endure this for no[n]reason at all!?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_11]
[s]You're a bit brutish, but I can sense a bold[n]defiance in your personality.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_12]
[s]You're insufferable. I won't tolerate this kind[n]of boorish behavior from you.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_13]
[s]Oh, so you aren't taking your anger out[n]upon me... Still, I wish for this to stop.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_14]
[s]Don't the humans around you warn you[n]against carrying such dreadful things?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_15]
[s]If you aren't irritated, then you're only[n]affirming to me that you're dangerous.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_16]
[s]I had not intended to say anything that[n]would elicit this kind of response.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06]
[s]It's frustrating when others bother me when[n]I have things to do.[n][w][e]
[s]Won't you just leave me be?[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_06 top]
[s]Fine, I will.[e]
[s]I can't just leave you.[e]
[s]Is that reverse psychology?[e]

[msg TalkMsg_GUY_CHAT_FQ_06_R]
[s]When you agree to it so quickly, I can't help[n]feeling a bit down...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_2]
[s]I can't say that feels genuine if you say it[n]while pointing a gun at me.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_3]
[s]Honestly, that's all you had to say from the[n]beginning.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_4]
[s]Good. I would be most grateful if you did.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_5]
[s]I suppose I should appreciate your[n]consideration.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_6]
[s]I think directing your attention to your[n]studies would be far more fruitful for you.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_7]
[s]I have neither the need, nor the desire,[n]for your concern.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_8]
[s]But that is my request![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_9]
[s]To make such an assumption is astounding.[n]You are certainly unique...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_10]
[s]Is that how you've interpreted my remarks?[n]Please understand that such was not my[n]intention.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_11]
[s]Oh, so you believe that I actually want you[n]to care? I suppose there are people who talk[n]that way.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_12]
[s]No. It absolutely isn't.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_13]
[s]I thought I asked you to leave me be. What[n]was that for? Are you attention-starved?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_14]
[s]Despite my request, you continue to shoot[n]at me. You're not very well-mannered for a[n]human, are you?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_15]
[s]If this is a tantrum to get me to care about[n]you, it's having just the opposite effect.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_16]
[s]...Would you please just leave me be now?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07]
[s]I know it's odd to say this about myself,[n]but... people who know me will say I never[n]let things go.[n][w][e]
[s]You will receive punishment for treating me[n]this way, mark my words.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_07 top]
[s]I'm sorry.[e]
[s]I'm prepared for the worst.[e]
[s]How much do you want?[e]

[msg TalkMsg_GUY_CHAT_FQ_07_R]
[s]...I'm shocked that you actually apologized[n]like that.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_2]
[s]Oh... I wasn't expecting that...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_3]
[s]Do you really mean that...?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_4]
[s]...Well, that is reassuring.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_5]
[s]So you're more than just talk... Still,[n]your behavior irritates me.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_6]
[s]Oh? It seems you're quite the daredevil.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_7]
[s]Preparing for the worst... That's exactly what[n]makes you humans so dangerous.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_8]
[s]I suppose being prepared would be prudent.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_9]
[s]...You are despicable.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_10]
[s]...It seems you've got quite the sense of[n]humor.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_11]
[s]That isn't what this is about...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_12]
[s]You hope to resolve this issue with money[n]alone? Typical human behavior...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_13]
[s]Do you intend to strike first before you can[n]be harmed? I guess that makes sense in this[n]case.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_14]
[s]Don't be so foolish. If you have any[n]self-awareness, you will cease this[n]behavior at once.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_15]
[s]That is what humans call "adding fuel to the[n]fire," is it not? You haven't gone mad, have[n]you?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_16]
[s]You're acting quite strangely. You do want[n]to hear what I have to say, do you not?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08]
[s]Allow me to ask you something...[n][w][e]
[s]Would you do to anyone else what you're[n]doing to me now?[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_08 top]
[s]I sure would.[e]
[s]No, I wouldn't.[e]
[s]This is a special exception.[e]

[msg TalkMsg_GUY_CHAT_FQ_08_R]
[s]Anyone at all that enters your field of vision?[n]Is that even a viable trait of human behavior?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_2]
[s]Then perhaps the unlucky one in this[n]scenario was me...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_3]
[s]You would do this to just anyone?[n]Are you out of your mind?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_4]
[s]You're a person of action, I see...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_5]
[s]...I suppose that means something about[n]me enticed you. I'll try to look at this more[n]positively.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_6]
[s]Then... why did it have to be me? I am[n]finding this dialogue infuriating.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_7]
[s]I suppose this means that there is something[n]about me that you especially despise...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_8]
[s]Ah, so this is a vagary of fate, is it not?[n]Is this what you humans call "bad luck"...?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_9]
[s]Oh, that sounds awfully dubious to me.[n]It sounds like some trite excuse humans[n]always say...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_10]
[s]Don't you say that to everyone? And calling[n]something "special" could be construed as[n]"capricious," no?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_11]
[s]When you put it that way, well... I suppose[n]I'm all right with it.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_12]
[s]The nuance of your words seems favorable,[n]but no, I am still not pleased about all this.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_13]
[s]That is your answer, yes? ...Hm, I feel that[n]could be interpreted either way.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_14]
[s]...I see. Of course brutes like you couldn't[n]simply adjust their behavior depending on[n]who they speak to.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_15]
[s]All I did was ask a simple question. Did that[n]upset you somehow?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_16]
[s]If you weren't in the mood for conversation,[n]then you should have told me so from the[n]start.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01]
[s]I've heard that human men have a proclivity[n]to tease the women that interest them.[n][w][e]
[s]Is it not possible for this series of events[n]involving you and me to be attributed[n]to that?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_01 top]
[s]Fair enough.[e]
[s]That is incorrect.[e]
[s]What are you talking about?[e]

[msg TalkMsg_GUY_CHAT_SQ_01_R]
[s]An affirmative answer, yet such a dry[n]response.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_2]
[s]So, then... Is that what is going on here with[n]us?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_3]
[s]Hm, that is a very business-like and[n]non-committal response.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_4]
[s]The way you said that was unnecessarily[n]cool and composed.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_5]
[s]It's clear to me that we fe— Wait, what?[n]You mean to say that I've been mistaken?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_6]
[s]I do not appreciate your attempts to[n]deliberately confuse me.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_7]
[s]But me thinking that couldn't have been a[n]mere product of my own conceit...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_8]
[s]Really? Does that mean you value[n]pragmatism over emotion?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_9]
[s]It is cruel of you to make me state this any[n]more clearly than I already have.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_10]
[s]Ah, you are the type who needs to define[n]everything clearly.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_11]
[s]You're far too obtuse. But, well, never mind[n]that...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_12]
[s]Are you really asking me that now?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_13]
[s]Are you the type who prefers a thrilling[n]relationship to an emotionally mature[n]one?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_14]
[s]I get the feeling that once you start, you'd[n]never quit...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_15]
[s]Ah, I assume you don't like clingy partners.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_16]
[s]...That awkwardness of yours is somehow[n]refreshing.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02]
[s]No matter the crime, humans treat it more[n]lightly if the perpetrator is a minor, do they[n]not?[n][w][e]
[s]Ah, so I suppose you commit such extreme[n]acts because you know you won't be[n]punished harshly...[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_02 top]
[s]I'm sorry.[e]
[s]Age doesn't matter.[e]
[s]This isn't extreme.[e]

[msg TalkMsg_GUY_CHAT_SQ_02_R]
[s]It's a relief that you're at least smart enough[n]to know when to apologize.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_2]
[s]If you believe that you need only apologize[n]to get away with this because you are a[n]minor, you are sorely mistaken.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_3]
[s]You can't just rely on adults to protect you[n]no matter what you do.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_4]
[s]Thinking that an apology is all you need[n]by this point is precisely what makes you[n]a minor.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_5]
[s]You're allowed to say that only if you are[n]self-subsistent.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_6]
[s]Arguing every point made against yours is[n]exactly what makes you a brat.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_7]
[s]I suppose that age is not a factor in human[n]greed.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_8]
[s]Don't you fear punishment? Are humans[n]really so driven by their selfish desires?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_9]
[s]I suppose our values are fundamentally[n]different.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_10]
[s]Have you ever learned "common sense"?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_11]
[s]That... That is not how I perceive it.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_12]
[s]Are you the type who pursues what you[n]want with reckless abandon?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_13]
[s]...You believe actions speak louder than[n]words, don't you?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_14]
[s]We agreed to "talk" about this, didn't we?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_15]
[s]I cannot consider being together with a[n]human who is too fast with his hands.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_16]
[s]Do you wish to talk? Or do you wish to kill?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03]
[s]I don't mean to doubt you or anything, but[n]would you mind if I ask you a question?[n][w][e]
[s]Is there really any benefit for me if I[n]joined with you?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_03 top]
[s]I think there is.[e]
[s]I can't promise that.[e]
[s]It's a matter of feeling.[e]

[msg TalkMsg_GUY_CHAT_SQ_03_R]
[s]Then I shall take this opportunity to observe[n]that for myself.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_2]
[s]That sort of vague response is very human,[n]in a bad way.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_3]
[s]Hearing you say it like that... Well, let's[n]just say that you'd benefit from more[n]confidence.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_4]
[s]What you're saying doesn't exactly exude[n]confidence.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_5]
[s]I couldn't possibly be with a human who[n]can't promise me something so simple.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_6]
[s]Perhaps you just don't understand how[n]to make yourself appealing to others.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_7]
[s]I suppose I can appreciate your honesty.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_8]
[s]I should have expected your response to be[n]non-committal.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_9]
[s]...You must think I'm a foolish woman if[n]you believed that line would distract me[n]from the issue.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_10]
[s]Are you saying that, in the end,[n]it's all up to me?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_11]
[s]Isn't that just something people say when[n]they're not quite sure of the answer?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_12]
[s]It was a simple "yes" or "no" question...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_13]
[s]...Let's work on improving our[n]communication skills, shall we?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_14]
[s]You are just showing off your strength, are[n]you not?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_15]
[s]Evidently, you're the kind of human who[n]can make it on his own.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_16]
[s]Ostensibly, there is no benefit for me at all...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04]
[s]If you consider it for a moment, you can't[n]really expect an honest opinion from[n]someone you're threatening at gunpoint.[n][w][e]
[s]Don't you think expecting your would-be[n]victim to be receptive to your words is[n]unreasonable?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_04 top]
[s]I do.[e]
[s]I don't.[e]
[s]Don't worry about it.[e]

[msg TalkMsg_GUY_CHAT_SQ_04_R]
[s]You seem to be lacking a conscience.[n]Are you certain you are even human?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_2]
[s]Oh. So this is the best outcome after you've[n]given all factors their due consideration?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_3]
[s]You would do well to abandon your egoistic[n]way of thinking.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_4]
[s]It's evident that you struggled while thinking[n]this over.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_5]
[s]Who am I kidding... I detest this[n]conversation.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_6]
[s]I don't outright reject that way of thinking,[n]but it carries a bias that favors you, yes?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_7]
[s]Naturally. If you felt differently, I suppose[n]you wouldn't be doing this.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_8]
[s]I do appreciate your candor. It leaves me no[n]freedom to misunderstand you, after all.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_9]
[s]Don't fret... about it? That is a unique turn of[n]phrase, evidently for my benefit.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_10]
[s]Such an abhorrent, egoistic attitude is true[n]to form for our stereotype of you humans.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_11]
[s]I'm talking to you because I can't help[n]fretting about it.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_12]
[s]You don't seem the type to hold the[n]emotions of others in high regard.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_13]
[s]See, now this is an example of what I mean[n]by unreasonable behavior.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_14]
[s]You do understand the principles of[n]conversation, do you not? Were my[n]expectations too high?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_15]
[s]Are you saying you will persist in[n]getting what you desire, no matter[n]the consequences?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_16]
[s]I suppose the disparity in culture and values[n]between us is just too great.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05]
[s]If I were to die here, my existence up to[n]this point would be rendered meaningless.[n][w][e]
[s]But this way of life in this world is all I've[n]ever known.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_05 top]
[s]It's not meaningless.[e]
[s]There are other ways to live.[e]
[s]You had a good run.[e]

[msg TalkMsg_GUY_CHAT_SQ_05_R]
[s]Do you mean that? So you can respect me[n]as an equal...?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_2]
[s]Hmm? But your words are in direct[n]contradiction to your actions.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_3]
[s]Are you saying I should be glad to gain the[n]experience?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_4]
[s]It's evident you've only said this to spare my[n]feelings. How mature of you.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_5]
[s]I appreciate you getting to the heart of the[n]matter. Perhaps I was overcomplicating[n]things.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_6]
[s]You make choosing a way of life sound as[n]frivolous as clothes shopping. Would you[n]not do that?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_7]
[s]It bothers me that I cannot imagine a life[n]outside of the one I have now...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_8]
[s]It's not your place to say that of someone[n]else's life so easily.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_9]
[s]Is that meant to cheer me up?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_10]
[s]Are you trying to be nice...?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_11]
[s]If that is the case, I will entrust my[n]life to you.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_12]
[s]You obviously couldn't care less.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_13]
[s]Do you mean to say that if I want to live in[n]the now, I must abandon all I've ever known[n]here?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_14]
[s]I can't believe I confessed my worries to you[n]and expected you to take me seriously...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_15]
[s]Do you mean to say that I should simply just[n]accept death? How loathsome...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_16]
[s]I'm gravely insulted that you've given no[n]consideration for my life and well-being[n]whatsoever.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06]
[s]...For now, I suspect that you've decided to[n]hear me out. Am I not right?[n][w][e]
[s]Why have you decided to be more[n]communicative with me?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_06 top]
[s]Your looks.[e]
[s]You seemed useful.[e]
[s]No particular reason.[e]

[msg TalkMsg_GUY_CHAT_SQ_06_R]
[s]I must admit, it doesn't feel bad to[n]hear that, but... Okay.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_2]
[s]...You mean to tell me that you've come all[n]this way, just to philander with women?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_3]
[s]...I don't believe that I'd have much of a[n]future with someone who would tell me[n]that.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_4]
[s]I suspected you had some ulterior motive.[n]I suppose I should have expected that from[n]a man like you.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_5]
[s]You don't see others as anything but tools,[n]do you?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_6]
[s]In that case, I shall assume that you have[n]high expectations for me.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_7]
[s]Do you believe so? I do have my strong[n]points and weaknesses...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_8]
[s]I am glad you recognize my practical[n]value, but...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_9]
[s]I suppose it is wise to trust your[n]instincts at times, but...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_10]
[s]You chose to take things this far for no real[n]reason...?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_11]
[s]I have never seen such simplicity in a[n]human's behavior...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_12]
[s]Do you mean to say that I am not attractive[n]to you at all?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_13]
[s]Do you mean to say that I should guess?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_14]
[s]Yet another human who can't handle basic[n]communication...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_15]
[s]Please, I must ask you to behave with a little[n]more common sense.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_16]
[s]Is it really that troublesome to at least[n]confirm or deny my assertions?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07]
[s]We were trying to kill each other just a short[n]while ago. It's surprising if you think about it.[n][w][e]
[s]I wonder if us speaking together like[n]this now means that we are somehow[n]connected...[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_07 top]
[s]It could be.[e]
[s]No way.[e]
[s]It's fate.[e]

[msg TalkMsg_GUY_CHAT_SQ_07_R]
[s]Hm, I thought so. I'm glad to see that[n]humans can feel the same way.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_2]
[s]I hope this connection can blossom[n]henceforth.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_3]
[s]"Could be"? Aren't you being a bit curt?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_4]
[s]"Could be"? The ambiguity of your words[n]troubles me.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_5]
[s]Well, that was extremely blunt. You may be[n]correct, but...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_6]
[s]It's rather annoying if I'm the only one who[n]is excited over the implications of all this...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_7]
[s]In that case, I should approach this with the[n]same sort of practicality.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_8]
[s]So rather than depend on fate, we must take[n]action in the relationship ourselves...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_9]
[s]Fate? That's the word you choose in this[n]situation?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_10]
[s]Oh, you humans and your clichés...[n]Not that I necessarily disapprove.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_11]
[s]Fate? Does that mean you also believe in[n]things such as reincarnation and karma?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_12]
[s]Are you trying to look smarter by using[n]difficult words?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_13]
[s]I see. Perhaps we are connected, but you're[n]willing to see this feud to the bitter end...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_14]
[s]Humans may be foolish at times, but this[n]sort of behavior is more befitting of a beast.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_15]
[s]I suppose it was rather silly to think this[n]was all brought about by some connection[n]between us...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_16]
[s]So... there is no connection between us?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08]
[s]All this would never have happened if you[n]had not come here.[n][w][e]
[s]I suppose this "real world" where you come[n]from must be fairly boring.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_08 top]
[s]You're right.[e]
[s]It keeps me busy.[e]
[s]It's better than here.[e]

[msg TalkMsg_GUY_CHAT_SQ_08_R]
[s]In that case, you'd better find some new way[n]to occupy yourself when you return to your[n]world.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_2]
[s]Oh? Then how do you deal with all the[n]boredom?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_3]
[s]You sound detached. I don't know if being[n]with you would be very entertaining...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_4]
[s]Going with you to such a mundane place[n]doesn't sound very appealing...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_5]
[s]If you're so busy, then why are you wasting[n]time here?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_6]
[s]Ah, I've heard there are humans out there[n]who pride themselves in being "busy." Is[n]that true?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_7]
[s]Being so busy has clearly turned you into a[n]nervous wreck... Thus, you took it out on me.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_8]
[s]In that case, I suppose we wouldn't be able[n]to spend very much time together there.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_9]
[s]If that is true, then would it not be better for[n]you to return home?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_10]
[s]Well, I've only known this place, so I suppose[n]I'll have to take you at your word.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_11]
[s]Even so, this place is my home.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_12]
[s]...Ah, you said it. I suspected as much.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_13]
[s]On second thought, with one of those in[n]your possession, how could you possibly[n]be bored?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_14]
[s]Have I upset you? Well, I feel the same way.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_15]
[s]...Do you not have any communication skills[n]at all, human?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_16]
[s]So that is the manner in which you wish to do[n]things? In that case, I shall follow suit.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09]
[s]Perhaps you may find our kind rather[n]annoying, but...[n][w][e]
[s]You do understand that we are here[n]because of people like you, right?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_09 top]
[s]I never thought of that.[e]
[s]I understand.[e]
[s]What do you mean?[e]

[msg TalkMsg_GUY_CHAT_SQ_09_R]
[s]I suspected as much. You're really hopeless,[n]human.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_2]
[s]I see, you came here BECAUSE you're[n]ignorant. That makes sense.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_3]
[s]Well then, I strongly suggest that you give it[n]more thought.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_4]
[s]So you're the sort to act on impulse alone,[n]then? How surprising...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_5]
[s]...Hm. You have little self-control over your[n]desires, don't you?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_6]
[s]Have you no concern about the trouble you[n]cause others?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_7]
[s]At the very least, you're possessed of a[n]willful drive and stubborn resolve.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_8]
[s]Are you trying to steal or kill...? What in the[n]world are you, anyway?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_9]
[s]You're not losing your temper, are you?[n]More importantly, you should answer[n]my question.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_10]
[s]You're quite the handful. What am I[n]supposed to do with you?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_11]
[s]I've been trying to speak to you normally,[n]but you are far too slow on the uptake.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_12]
[s]Shall I try to explain it once more? No, never[n]mind, it wouldn't be worth all the effort.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_13]
[s]Are you surprised? You had no idea until[n]now?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_14]
[s]You probably don't even realize that your[n]actions prove my point...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_15]
[s]Ah, it's fine. I understand that you don't[n]comprehend what I'm saying.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_16]
[s]You started this conversation with me, and[n]now you deem it not worth your time?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10]
[s]Speaking of which, I have heard that young[n]people today have poor communication[n]skills.[n][w][e]
[s]You, however, are talking to me right here.[n]Are you the exception to this rule?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_10 top]
[s]I'm not special.[e]
[s]That's right.[e]
[s]I have ulterior motives.[e]

[msg TalkMsg_GUY_CHAT_SQ_10_R]
[s]My, aren't you humble for a human?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_2]
[s]Oh, I'm aware that's something humans[n]say to appear humble, an exercise in false[n]modesty.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_3]
[s]Being overly modest will lead to people[n]taking advantage of you for the rest of[n]your life, you know.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_4]
[s]I intended to compliment you, but you're[n]saying I was mistaken about you being[n]exceptional?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_5]
[s]Bragging like that is nothing more than[n]obnoxious.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_6]
[s]Do you always insist on letting people talk[n]about you instead of talking about yourself?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_7]
[s]Upon consideration, I wouldn't be a very[n]good fit with such a special human as[n]yourself.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_8]
[s]I have no doubt that you are exceptional in[n]more ways than one.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_9]
[s]Does that mean you would prefer some nice[n]"thing" over me?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_10]
[s]I'm not accustomed to people being so[n]direct, but I am impressed by your honesty.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_11]
[s]Well, unfortunately, I have nothing on hand.[n]Oh dear, whatever shall we do?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_12]
[s]Ah, this must be the excessive greed[n]of the introvert...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_13]
[s]Perhaps I was the only one who thought we[n]could have a conversation...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_14]
[s]That response was special in a way that was[n]uniquely you.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_15]
[s]...It appears we have both found this[n]conversation tedious.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_16]
[s]Ah, evidently, I've been gravely mistaken.[n]My apologies.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11]
[s]You have teammates who would mourn you[n]if something were to happen, do you not?[n][w][e]
[s]I also have loved ones who would miss me.[n]You do catch my meaning, yes?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_11 top]
[s]I do now.[e]
[s]That doesn't matter.[e]
[s]I'm always alone.[e]

[msg TalkMsg_GUY_CHAT_SQ_11_R]
[s]Hm. It does appear that you are reflecting[n]on your actions...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_2]
[s]I see. Of course it wouldn't occur to a[n]common thief beforehand.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_3]
[s]It's about time you noticed.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_4]
[s]Yes, and things are this way now because[n]you are only capable of thinking solely of[n]yourself.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_5]
[s]You humans are capable of saying such[n]cold-hearted things.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_6]
[s]I suppose you're right. Even I'm unsure of[n]what I'm saying...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_7]
[s]...You're right. My apologies, it was rude of[n]me to bring it up.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_8]
[s]Oh? Perhaps we disagree, but I still admire[n]your conviction.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_9]
[s]Then how do you explain these other[n]humans surrounding us?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_10]
[s]I'm sorry, but that is just too tragic.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_11]
[s]I wonder if everyone who talks to you gets[n]as depressed as I do.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_12]
[s]Well, the underlying cause of that is most[n]likely your personality. Have you ever[n]considered that?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_13]
[s]You mean to say that you really understand[n]me?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_14]
[s]If you don't catch my meaning, you could[n]just ask me to explain.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_15]
[s]Are you attacking me because what I'm[n]saying frustrates and confuses you? You[n]are a lost cause, human.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_16]
[s]Oh, forget it. You are far too brutish to get[n]along with.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12]
[s]Truth be told, I cannot dismiss the idea of[n]being with you entirely...[n][w][e]
[s]But is it fair to my kind if only I find such[n]happiness, leaving them all behind?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_12 top]
[s]I think so.[e]
[s]They can all come.[e]
[s]Your kind?[e]

[msg TalkMsg_GUY_CHAT_SQ_12_R]
[s]It's quite a relief to hear that from you.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_2]
[s]Please don't give me such an ambiguous[n]answer after you've already made me[n]reconsider...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_3]
[s]I thought so. I mean, you're right, but...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_4]
[s]Still, this is quite sudden... I cannot make up[n]my mind at the moment. But then again...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_5]
[s]Is the happiness of everyone involved[n]your ideal?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_6]
[s]I see... You are thinking in terms of our[n]happiness, not just my own.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_7]
[s]But... you're not choosing me alone in that[n]scenario, are you?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_8]
[s]It's as though you're shepherding a herd of[n]animals, and I'm simply one of the flock... I[n]dislike that sort of thinking.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_9]
[s]I have allies, too, I'll have you know.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_10]
[s]Yes. It feels like I'm receiving some special[n]award that they can't have, and it doesn't[n]feel right.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_11]
[s]Truthfully, we may not be as close as the[n]word "kind" suggests...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_12]
[s]Please don't try to steer the conversation in[n]another direction by asking me irrelevant[n]questions.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_13]
[s]Is this a sensitive subject for you?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_14]
[s]...I changed my mind.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_15]
[s]...I didn't see that coming.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_16]
[s]Do you mean to say that you're willing to[n]sacrifice others for your own happiness?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13]
[s]...We are going to have to be on equal[n]footing if we are to be together.[n][w][e]
[s]Tell me, what does "equal footing" mean to[n]you?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_13 top]
[s]Not talking down to people.[e]
[s]Sharing household chores.[e]
[s]Splitting all the costs.[e]

[msg TalkMsg_GUY_CHAT_SQ_13_R]
[s]Naturally. Oh, and please let your actions—[n]not just your words—reflect that too, yes?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_2]
[s]True, but that needs to happen before we[n]can even be together.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_3]
[s]Supposedly, most human men talk down on[n]others, so it makes me happy to hear you say[n]that.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_4]
[s]Hmm, that feels somewhat hypocritical,[n]considering I'm essentially your hostage.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_5]
[s]The conversation suddenly took a turn[n]toward the domestic, hasn't it?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_6]
[s]Ah, I hadn't thought quite that far ahead.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_7]
[s]I believe you're getting quite ahead of[n]yourself with that line of thinking...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_8]
[s]Aren't you fantasizing? That's not the[n]direction I would have gone...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_9]
[s]That interpretation is rather convenient for[n]the man, is it not?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_10]
[s]I have no qualms with being frugal in our[n]finances, but...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_11]
[s]That is a rather petty way of thinking. It is[n]not a very promising start to a discussion[n]of equality.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_12]
[s]I suppose that could be considered[n]equal in a sense...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_13]
[s]I'm not quite sure how that is supposed to[n]illustrate equal footing.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_14]
[s]So equality, in your opinion, is devoting[n]myself to giving endlessly...?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_15]
[s]...I'm an understanding person, you know.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_16]
[s]Ah, you're not interested in equal footing at[n]all...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14]
[s]If we joined together, that would mean that[n]you become me, and I become you, yes?[n][w][e]
[s]I occasionally wish to pamper myself as a[n]reward for working hard. How would you[n]do that?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_14 top]
[s]Relax at home.[e]
[s]Go impulse shopping.[e]
[s]Don't be so selfish.[e]

[msg TalkMsg_GUY_CHAT_SQ_14_R]
[s]People are entitled to that only when[n]they work hard every day.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_2]
[s]Goodness. Spending time with you sounds[n]rather dull.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_3]
[s]After going through the trouble to free up[n]that time, you wouldn't do anything? What[n]about going out?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_4]
[s]I suppose that sounds appealing,[n]in its own way.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_5]
[s]You can do that anytime.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_6]
[s]That sounds good. There's something very[n]appealing about small creature comforts.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_7]
[s]That's what you think of when you[n]think of pampering yourself? Maybe[n]your upbringing is the problem.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_8]
[s]I have no real problem with that,[n]but it's rather mundane...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_9]
[s]This is hardly the time or place discipline[n]me...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_10]
[s]If that's how you feel, perhaps I would be[n]better off remaining alone.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_11]
[s]I suppose refraining from extravagance can[n]be a good idea.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_12]
[s]Are you telling me that I should conform to[n]what you want to do?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_13]
[s]You mean to say that my reward would be[n]"thrills"? No, thank you, I'll pass.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_14]
[s]Peace and comfort was what I actually had[n]in mind.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_15]
[s]I'm saying I may become you, and this is[n]what I get?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_16]
[s]You aren't annoyed because I asked you[n]that question, are you?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15]
[s]Perhaps it's odd to say this now, but I'm still[n]unwilling to admit defeat.[n][w][e]
[s]After all, is it not pitiable when one denies[n]one's own feelings?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_15 top]
[s]It's a difficult topic.[e]
[s]So don't deny them.[e]
[s]It's mature to admit defeat.[e]

[msg TalkMsg_GUY_CHAT_SQ_15_R]
[s]Oh? Have I got you thinking about it now?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_2]
[s]I simply abhor it when things must end on a[n]down note.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_3]
[s]...Thank you for understanding.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_4]
[s]Life is about survival first and foremost, no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_5]
[s]Are you saying a defeat need not mean[n]that my feelings are negated?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_6]
[s]You say this, and yet you've done nothing[n]but deny me.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_7]
[s]I sense you're trying to sound profound,[n]but it isn't working.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_8]
[s]Oddly, the more you console me, the more[n]miserable I feel...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_9]
[s]Aren't you trying too hard to sound[n]intelligent?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_10]
[s]You do have a point. Perhaps I stand to[n]benefit from adopting that perspective.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_11]
[s]It displeases me when humans behave[n]sanctimoniously.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_12]
[s]Your point is sound, but somehow,[n]I wish to resist it.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_13]
[s]I believe you misunderstood. I was not[n]talking back to you.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_14]
[s]I am having one conversation while you are[n]engaged in another one, evidently.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_15]
[s]I suppose you find yourself above this sort of[n]conversation, human?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_16]
[s]Clearly, I would be even more miserable if I[n]decided to join with a human like yourself.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16]
[s]Consider this. You may be able to use brute[n]force to take me, but you cannot force my[n]feelings on you to change.[n][w][e]
[s]Even with that in mind, do you still want me?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_16 top]
[s]That's right.[e]
[s]I didn't think that far...[e]
[s]The feelings will come.[e]

[msg TalkMsg_GUY_CHAT_SQ_16_R]
[s]If you declare that so readily... I'm inclined[n]to believe you.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_2]
[s]Somehow, I don't feel that there is any basis[n]for your confidence.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_3]
[s]Is that so? Then, why do I feel so irritated?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_4]
[s]You're too overbearing. Clearly you haven't[n]given it any actual thought.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_5]
[s]Impossible. You did all this on impulse[n]alone?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_6]
[s]...Do you understand the message I'm[n]getting from you right now?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_7]
[s]You're making a decision that will affect the[n]rest of my life, and you didn't care to think[n]that far?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_8]
[s]...I feared that was the case.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_9]
[s]I dislike not having proof positive for[n]something as important as this...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_10]
[s]...What? ...Oh. Never mind.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_11]
[s]Well, I won't deny the possibility that may[n]happen, but...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_12]
[s]You understand that we're speaking of MY[n]feelings, yes?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_13]
[s]You don't actually want me... What you[n]desire is a servant.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_14]
[s]Oh, did I hit a soft spot?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_15]
[s]Evidently, my feelings are of little[n]consequence to you.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_16]
[s]I can see that even if we were together, you[n]would still shove me around in this way.[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND]
[s](planned to be cut)[n]You are more aggressive than you appear...[n]So what is it that you desire?[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND_2]
[s](planned to be cut)[n]Deep breaths... Please just tell me, what do[n]you desire? Other than my life, that is.[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND_3]
[s](planned to be cut)[n]What is it that you want? What must I do to[n]go home?[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND_4]
[s](planned to cut)[n]You've hurt me enough, haven't you?[n]What more do you want of me?[n][w][e]

[sel TalkSel_GUY_NEGO_SURREND top]
[s]I want you.[e]
[s]...Give me money.[e]
[s]I want a rare item.[e]
[s]I want some intel.[e]
[s]Lower the security level.[e]

[msg TalkMsg_GUY_NEGO_FIFTYFI]
[s]What you ask may place me in grave peril.[n]I must refuse... unless you give me[n][var 0] yen.[n][w][e]

[msg TalkMsg_GUY_NEGO_FIFTYFI_2]
[s]No, my social circle would never tolerate[n]me doing that. Therefore, I ask you for a[n][f 2 5 3 9999 3].[n][w][e]

[msg TalkMsg_GUY_NEGO_FIFTYFI_3]
[s]What? That's far too precarious! At the very[n]least, give me some life force before[n]I attempt this.[n][w][e]

[msg TalkMsg_GUY_NEGO_FIFTYFI_4]
[s]What? That's far too precarious! At the very[n]least, give me some mind force before I[n]attempt this.[n][w][e]

[sel TalkSel_GUY_NEGO_FIFTYFI top]
[s]Fine, I'll give it to you.[e]
[s]I can't meet your demands.[e]

[msg TalkMsg_GUY_NEGO_REQUIRE]
[s]Goodness, it's sweltering. The heat is so[n]unbearable, I can hardly think![n][w][e]
[s]Rather than have you point a[n]gun at me, I would much prefer[n]a [f 2 5 3 9999 4].[n][w][e]

[msg TalkMsg_GUY_NEGO_REQUIRE_2]
[s]*cough* This isn't good... My condition...[n]*cough* Ahem...[n][w][e]
[s]This fever *cough* is insufferable.[n]If you would, may I have a[n][f 2 5 3 9999 4]?[n][w][e]

[msg TalkMsg_GUY_NEGO_REQUIRE_3]
[s]...Isn't this insufferable!? When the pollen[n]in the air makes your eyes so itchy!?[n][w][e]
[s]If you really intend to talk to me,[n]won't you at the very least give me[n]a [f 2 5 3 9999 4] first?[n][w][e]

[msg TalkMsg_GUY_NEGO_REQUIRE_4]
[s]You're seriously asking me to involve other[n]Shadows and lie to them?[n][w][e]
[s]I'd be killed if I were to be caught, but[n]I would take the risk if you gave me a[n][f 2 5 3 9999 3].[n][w][e]

[sel TalkSel_GUY_NEGO_REQUIRE top]
[s]Hand it over[e]
[s]Don't hand it over[e]

[msg TalkMsg_GUY_NEGO_PAYFOR_]
[s]...I shall give you [var 0] yen.[n]And with this, our encounter[n]shall be concluded.[n][w][e]

[msg TalkMsg_GUY_NEGO_PAYFOR__2]
[s]...I humbly offer you [var 0] yen.[n]Please accept it without reservation.[n][w][e]

[msg TalkMsg_GUY_NEGO_PAYFOR__3]
[s]...Take this [f 2 5 3 9999 1].[n]By all means, give it a try.[n][w][e]

[msg TalkMsg_GUY_NEGO_PAYFOR__4]
[s]...I humbly offer you a [f 2 5 3 9999 1].[n]It would please me if you find it useful.[n][w][e]

[sel TalkSel_GUY_NEGO_PAYFOR top]
[s]Sounds good.[e]
[s]I want more than this.[e]

[msg TalkMsg_GUY_NEGO_Re_ACCE]
[s]Is that so? Well, I suppose I have no other[n]choice.[n][w][e]

[msg TalkMsg_GUY_NEGO_Re_ACCE_2]
[s]...Oh, is that all?[n][w][e]

[msg TalkMsg_GUY_NEGO_Re_ACCE_3 [Ryuji]]

[msg TalkMsg_GUY_RESULT_GET_P]
[s]In truth, I am not a Shadow. I originated[n]from the humans' sea of souls...[n][w][e]
[s]My true name... is [clr 1][var 2][clr 27].[n]Henceforth, I am thou.[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_P_2]
[s]A moment... You already have a[n][clr 1][var 2][clr 27] within you.[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_P_3]
[s]Ah, but... you don't live up to my[n]standards yet. Won't you let it go[n]for now with this [f 2 5 3 9999 1]?[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_M]
[s]...Here, I shall give you [var 0] yen.[n]Please use it wisely.[n][w][e]
[s]Now, I must be going.[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_I]
[s]...Take this [f 2 5 3 9999 1]. I believe[n]this sort of thing would please you.[n][w][e]
[s]Now, let us bid each other adieu.[n]Farewell.[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_S]
[s]Here, take this. Be careful not to lose it.[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY]
[s]...I'm in no mood to speak with the likes of[n]you.[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_2]
[s]...This greedy, brutish creature![n]How dare you make light of me!?[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_3]
[s]...If you're not satisfied with this, allow me to[n]ask a friend to deliver you something extra![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_4]
[s]...And so, I take my leave! Don't bother[n]following me![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_5]
[s]Everyone, let us make haste to the far side of[n]this world![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_6]
[s]...Eh? A human? Seriously? Eh? Gunfire?[n]Am I surrounded? What? What?[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_7]
[s]N-No... Please, stop...! I-I'll leave...[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_8]
[s]......[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_9]
[s]Ugh! What do you want!? I have no[n]intention of talking to—[n][w][e]
[s]No... When I think about it, do I really need[n]to be so mad? Forgive me. I'm willing[n]to listen.[n][w][e]

[msg TalkMsg_RESULT_GET_SECRE]
[s]My word... This information... It isn't worth[n]telling you.[n][w][e]

[msg TalkMsg_SURRENDER_FROM_C]
[s]Oh, you are a fearsome opponent. No, it[n]would be best for me to surrender while I[n]have the chance.[n][w][e]

[msg TalkMsg_SUCCESS_SKIMMING]
[s]Hm? Is this what you desire? I must admit,[n]you have a keen eye ... Here then, take it.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_SHO]
[s]Uhhn, uuuh...[n][w][e]

[msg TalkMsg_RESULT_ENEMY_SLE]
[s]Zzz...[n][w][e]

[msg TalkMsg_RESULT_ENEMY_FLA]
[s]Ahhh, fire! Fire! I'm... burning!?[n][w][e]
[s]...Well, fires do go out eventually. All right,[n]then. I'm willing to listen to what you have[n]to say.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_VER]
[s]Oh my, this is disorienting... Why must we[n]communicate at a time like this...?[n][w][e]
[s]Then again, I'd rather not put this off... I'm[n]willing to listen to what you have to say.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_FOR]
[s]I feel like I am forgetting something, but[n]what could it be...?[n][w][e]
[s]No matter, I'll forget that I've forgotten. I'm[n]willing to prioritize listening to you now.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_DES]
[s]I have already abandoned all hope... I don't[n]deserve to live...[n][w][e]
[s]Ah, but you're showing interest in me... At[n]the very least, I should listen to what you[n]have to say...[n][w][e]

[msg TalkMsg_RESULT_ENEMY_BRA]
[s]Ah, I can hear a voice... That must be my[n]ordained path. I'm sure of it...[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH]
[s]Ah, so that is my ordained path...[n][w][e]
[s]Thank you for showing me the— Oh! I'm[n]sorry, I remember now...[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_2]
[s]Ah, so that is my ordained path...[n][w][e]
[s]No, I refuse to be deceived. This cannot be[n]my ordained path![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_3]
[s]Ah, so that is my ordained path...[n][w][e]
[s]Thank you for showing me the way. Please,[n]I'd like you to have this.[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_4]
[s]Ah, so that is my ordained path...[n][w][e]
[s]No, I refuse to be deceived. This cannot be[n]my ordained path![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_5]
[s]Ah, so that is my ordained path... I offer this[n]as a sign of my gratitude.[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_6]
[s]Ah, so that is my ordained path...[n][w][e]
[s]No, I refuse to be deceived. This cannot be[n]my ordained path![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_7]
[s]Ah, so that is my ordained path... Thank[n]you for showing me the way. I wish for[n]you to have this.[n][w][e]

[msg TalkMsg_CONTACT_11]
[s]Flee while you still can! Ahahaha! It is futile[n]to oppose King Kamoshida![n][w][e]

[msg TalkMsg_CONTACT_12]
[s]Flee while you still can! Ahahaha! It is futile[n]to oppose Lord Madarame![n][w][e]

[msg TalkMsg_CONTACT_13]
[s]Flee while you still can! Ahahaha! It is futile[n]to oppose Mr. Kaneshiro![n][w][e]

[msg TalkMsg_CONTACT_14]
[s]Flee while you still can! Ahahaha! It is futile[n]to oppose Queen Futaba![n][w][e]

[msg TalkMsg_CONTACT_15]
[s]Flee while you still can! Ahahaha! It is futile[n]to oppose Lord Okumura![n][w][e]

[msg TalkMsg_CONTACT_16]
[s]Flee while you still can! Ahahaha! It is futile[n]to oppose Lady Niijima![n][w][e]

[msg TalkMsg_CONTACT_17]
[s]Flee while you still can! Ahahaha! It is futile[n]to oppose Lord Akechi![n][w][e]

[msg TalkMsg_CONTACT_18]
[s]Flee while you still can! Ahahaha! It is futile[n]to oppose Lord Shido![n][w][e]

[msg TalkMsg_CONTACT_19]
[s]Flee while you still can! Ahahaha! It is futile[n]to oppose His Excellency![n][w][e]

[msg TalkMsg_CONTACT_10]
[s]Flee while you still can! Ahahaha! It is futile[n]to oppose the secret boss![n][w][e]

[msg TalkMsg_CONTACT_MEMENTOS]
[s]Ouch, ouch, ouch! I implore you,[n]please let me go![n][w][e]

[msg TalkMsg_CONTACT_MEMENTOS_2]
[s]What is the meaning of this? Do you truly[n]intend to threaten a woman!?[n][w][e]

[msg TalkMsg_CONTACT_MEMENTOS_3]
[s]Heavens, I should never have gone out[n]today.[n][w][e]

[msg TalkMsg_GREET_POSSESSING]
[s]Oh, you already have the mask of[n][clr 1][var 2][clr 27].[n]You could have just told me so...[n][w][e]

[msg TalkMsg_NEGO_POSSESSING_]
[s]I suppose I'll help you. You wanted money,[n]did you not?[n][w][e]

[msg TalkMsg_NEGO_POSSESSING__2]
[s]You wanted an item, did you not? Please,[n]take this.[n][w][e]

[msg TalkMsg_GREET_POSSESSED]
[s]Hm? We've met before, have we not? I truly[n]believed that we would be together forever.[n][w][e]

[msg TalkMsg_NEGO_POSSESSED]
[s]I'll let go of this grudge. After all, I wouldn't[n]want you to think I wasn't a proper lady...[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_M]
[s]I believe it was money that you desired, yes?[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_I]
[s]I believe you desired an item, yes?[n]Please take this.[n][w][e]

[msg TalkMsg_GREET_POSSESSED_]
[s]Can we not start over? Let us speak a[n]while in leisure, like we did back then...[n][w][e]

[msg TalkMsg_TALK_POSSESSED_B]
[s]This brings back old memories, doesn't it?[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_B]
[s]I suppose that's true, too.[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_B_2]
[s]I'm certain that all you care about is[n]money...[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_B_3]
[s]So you were seeking this...[n][w][e]

[msg TalkMsg_FIRST_CONTACT]
[s]Well... We must talk things over first.[n]I know nothing about you, after all...[n][w][e]

[msg TalkMsg_PRE_QUESTION]
[s]I feel as if we've spoken before. In any[n]case, would you mind if we talked?[n][w][e]

[msg TalkMsg_PRE_QUESTION_ACQ]
[s]It rather pleases me to hear you[n]say that.[n][w][e]

[msg TalkMsg_PRE_QUESTION_DEN]
[s]How coldhearted of you... Well, I'm one to[n]talk, but— Oh! I'm sorry, I remember now...[n][w][e]

[msg TalkMsg_TALK_TECH_ITEM]
[s]...That performance was absolutely[n]dreadful. Perhaps it'd be more believable[n]if you tried it again.[n][w][e]

[msg TalkMsg_TALK_TECH_PERSON]
[s]I love conversations such as this, so—[n]Oh! I'm sorry, I remember now...[n][w][e]

[msg TalkMsg_SETTLE_DOWN]
[s]Ah, apologies, my little prank went too far.[n]Why don't we just talk about something[n]else?[n][w][e]

[msg TalkMsg_RESULT_SHOT_1]
[s]Eeeek! What was that[n]all of a sudden!?[n][w][e]
[s]Do you mean to say arguing would be[n]fruitless? Well, if that's how you truly[n]feel...![n][w][e]

[msg TalkMsg_RESULT_SHOT_2]
[s]Eeeek! ...Oh. I'm not wounded, am I?[n][w][e]
[s]Are you threatening me? I believe you have[n]picked the wrong opponent.[n][w][e]

[msg TalkMsg_RESULT_SHOT_3]
[s]Ahhh, he's going to kill me![n][w][e]

[msg TalkMsg_RESULT_SHOT_4]
[s]Eek...! Listen, I'm willing to offer you this,[n]so would you please let me go?[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO]
[s]In truth, I am not a Shadow. I originated[n]from the humans' sea of souls...[n][w][e]
[s]My true name... is [clr 1][var 2][clr 27].[n]Henceforth, I am thou.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_2]
[s]In truth, I am not a Shadow. I originated[n]from the humans' sea of souls...[n][w][e]
[s]My true name... is [clr 1][var 2][clr 27].[n]Henceforth, I am thou.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_3]
[s]In truth, I am not a Shadow. I originated[n]from the humans' sea of souls...[n][w][e]
[s]My true name... is [clr 1][var 2][clr 27].[n]Henceforth, I am thou.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_4]
[s]In truth, I am not a Shadow. I originated[n]from the humans' sea of souls...[n][w][e]
[s]My true name... is [clr 1][var 2][clr 27].[n]Henceforth, I am thou.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_5]
[s]In truth, I am not a Shadow. I originated[n]from the humans' sea of souls...[n][w][e]
[s]My true name... is [clr 1][var 2][clr 27].[n]Henceforth, I am thou.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_6]
[s]In truth, I am not a Shadow. I originated[n]from the humans' sea of souls...[n][w][e]
[s]My true name... is [clr 1][var 2][clr 27].[n]Henceforth, I am thou.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_7]
[s]In truth, I am not a Shadow. I originated[n]from the humans' sea of souls...[n][w][e]
[s]My true name... is [clr 1][var 2][clr 27].[n]Henceforth, I am thou.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_8]
[s]In truth, I am not a Shadow. I originated[n]from the humans' sea of souls...[n][w][e]
[s]My true name... is [clr 1][var 2][clr 27].[n]Henceforth, I am thou.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_9]
[s]In truth, I am not a Shadow. I originated[n]from the humans' sea of souls...[n][w][e]
[s]My true name... is [clr 1][var 2][clr 27].[n]Henceforth, I am thou.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_10]
[s]In truth, I am not a Shadow. I originated[n]from the humans' sea of souls...[n][w][e]
[s]My true name... is [clr 1][var 2][clr 27].[n]Henceforth, I am thou.[n][w][e]

[msg TalkMsg_ED_bye_D01_01]
[s]You would do well to tread carefully.[n]King Kamoshida is a man possessed[n]of immense desire.[n][w][e]

[msg TalkMsg_ED_bye_D01_02]
[s]Hmph... I wonder if your power would even[n]pose a threat to King Kamoshida...[n][w][e]

[msg TalkMsg_ED_bye_D01_03]
[s]It's fair that I tell you that you're mistaken if[n]you think you can oppose King Kamoshida.[n][w][e]

[msg TalkMsg_ED_bye_D02_01]
[s]You would do well to tread carefully.[n]Lord Madarame is a man possessed[n]of immense desire.[n][w][e]

[msg TalkMsg_ED_bye_D02_02]
[s]Hmph... I wonder if your power would even[n]pose a threat to Lord Madarame...[n][w][e]

[msg TalkMsg_ED_bye_D02_03]
[s]It's fair that I tell you that you're mistaken if[n]you think you can oppose Lord Madarame.[n][w][e]

[msg TalkMsg_ED_bye_D03_01]
[s]You would do well to tread carefully.[n]Mr. Kaneshiro is a man possessed[n]of immense desire.[n][w][e]

[msg TalkMsg_ED_bye_D03_02]
[s]Hmph... I wonder if your power would even[n]pose a threat to Mr. Kaneshiro...[n][w][e]

[msg TalkMsg_ED_bye_D03_03]
[s]It's fair that I tell you that you're mistaken if[n]you think you can oppose Mr. Kaneshiro.[n][w][e]

[msg TalkMsg_ED_bye_D04_01]
[s]In any case, I doubt a brutish thug like you[n]can make your way to Queen Futaba.[n][w][e]

[msg TalkMsg_ED_bye_D04_02]
[s]Let me make this clear. You'd be better off if[n]you quit now. Stop heading toward Queen[n]Futaba.[n][w][e]

[msg TalkMsg_ED_bye_D04_03]
[s]Oh, I believe you'll find that reaching Queen[n]Futaba won't be a simple matter.[n][w][e]

[msg TalkMsg_ED_bye_D05_01]
[s]You would do well to tread carefully.[n]Lord Okumura is a man possessed[n]of immense desire.[n][w][e]

[msg TalkMsg_ED_bye_D05_02]
[s]Hmph... I wonder if your power would even[n]pose a threat to Lord Okumura...[n][w][e]

[msg TalkMsg_ED_bye_D05_03]
[s]It's fair that I tell you that you're mistaken if[n]you think you can oppose Lord Okumura.[n][w][e]

[msg TalkMsg_ED_bye_D06_01]
[s]You would do well to tread carefully.[n]Lady Niijima is a woman possessed[n]of immense desire.[n][w][e]

[msg TalkMsg_ED_bye_D06_02]
[s]Hmph... I wonder if your power would even[n]pose a threat to Lady Niijima...[n][w][e]

[msg TalkMsg_ED_bye_D06_03]
[s]It's fair that I tell you that you're mistaken if[n]you think you can oppose Lady Niijima.[n][w][e]

[msg TalkMsg_ED_bye_D07_01]
[s]You would do well to tread carefully.[n]Lord Akechi is a man possessed[n]of immense desire.[n][w][e]

[msg TalkMsg_ED_bye_D07_02]
[s]Hmph... I wonder if your power would even[n]pose a threat to Lord Akechi...[n][w][e]

[msg TalkMsg_ED_bye_D07_03]
[s]It's fair that I tell you that you're mistaken if[n]you think you can oppose Lord Akechi.[n][w][e]

[msg TalkMsg_ED_bye_D08_01]
[s]You would do well to tread carefully.[n]Lord Shido is a man possessed of[n]immense desire.[n][w][e]

[msg TalkMsg_ED_bye_D08_02]
[s]Hmph... I wonder if your power would even[n]pose a threat to Lord Shido...[n][w][e]

[msg TalkMsg_ED_bye_D08_03]
[s]It's fair that I tell you that you're[n]mistaken if you think you can oppose[n]Lord Shido.[n][w][e]

[msg TalkMsg_ED_bye_D09_01]
[s]You would do well to tread carefully.[n]His Excellency is a being possessed of[n]immense desire.[n][w][e]

[msg TalkMsg_ED_bye_D09_02]
[s]Hmph... I wonder if your power would even[n]pose a threat to His Excellency...[n][w][e]

[msg TalkMsg_ED_bye_D09_03]
[s]It's fair that I tell you that you're mistaken if[n]you think you can oppose His Excellency.[n][w][e]

[msg TalkMsg_ED_bye_D10_01]
[s]You would do well to tread carefully.[n]The secret boss is a being possessed[n]of immense desire.[n][w][e]

[msg TalkMsg_ED_bye_D10_02]
[s]Hmph... I wonder if your power would even[n]pose a threat to the secret boss...[n][w][e]

[msg TalkMsg_ED_bye_D10_03]
[s]It's fair that I tell you that you're mistaken if[n]you think you can oppose the secret boss.[n][w][e]

[msg TalkMsg_CONTACT_11_1]
[s]Y-You... What are you doing here,[n]sneaking around in the castle!?[n][w][e]

[msg TalkMsg_CONTACT_11_2]
[s]Please don't shoot! I promise I won't[n]say a thing to King Kamoshida![n][w][e]

[msg TalkMsg_CONTACT_11_3]
[s]W-Wait! What do you want from me?[n][w][e]

[msg TalkMsg_CONTACT_12_1]
[s]Y-You... What are you doing here,[n]sneaking around in the museum!?[n][w][e]

[msg TalkMsg_CONTACT_12_2]
[s]Please don't shoot! I promise I won't[n]say a thing to Lord Madarame![n][w][e]

[msg TalkMsg_CONTACT_12_3]
[s]What is the meaning of this? Do you truly[n]intend to threaten a woman!?[n][w][e]

[msg TalkMsg_CONTACT_13_1]
[s]Y-You... What are you doing here,[n]sneaking around in the bank!?[n][w][e]

[msg TalkMsg_CONTACT_13_2]
[s]Please don't shoot! I promise I won't[n]say a thing to Mr. Kaneshiro![n][w][e]

[msg TalkMsg_CONTACT_13_3]
[s]Ouch, ouch, ouch! I implore you,[n]please let me go![n][w][e]

[msg TalkMsg_CONTACT_14_1]
[s]Y-You... What are you doing here,[n]sneaking around the Queen's[n]resting place!?[n][w][e]

[msg TalkMsg_CONTACT_14_2]
[s]Please don't shoot! I promise I won't[n]say a thing to Queen Futaba![n][w][e]

[msg TalkMsg_CONTACT_14_3]
[s]W-Wait! What do you want from me?[n][w][e]

[msg TalkMsg_CONTACT_15_1]
[s]Y-You... What are you doing here,[n]sneaking around in the company!?[n][w][e]

[msg TalkMsg_CONTACT_15_2]
[s]Please don't shoot! I promise I won't[n]say a thing to Lord Okumura![n][w][e]

[msg TalkMsg_CONTACT_15_3]
[s]W-Wait! What do you want from me?[n][w][e]

[msg TalkMsg_CONTACT_16_1]
[s]Y-You... What are you doing here,[n]sneaking around in the casino!?[n][w][e]

[msg TalkMsg_CONTACT_16_2]
[s]Please don't shoot! I promise I won't[n]say a thing to Lady Niijima![n][w][e]

[msg TalkMsg_CONTACT_16_3]
[s]W-Wait! What do you want from me?[n][w][e]

[msg TalkMsg_CONTACT_17_1]
[s]Y-You... What are you doing here,[n]sneaking around in the castle!?[n][w][e]

[msg TalkMsg_CONTACT_17_2]
[s]Please don't shoot! I promise I won't[n]say a thing to Lord Akechi![n][w][e]

[msg TalkMsg_CONTACT_17_3]
[s]W-Wait! What do you want from me?[n][w][e]

[msg TalkMsg_CONTACT_18_1]
[s]Y-You... What are you doing here,[n]sneaking around on the ship!?[n][w][e]

[msg TalkMsg_CONTACT_18_2]
[s]Please don't shoot! I promise I won't[n]say a thing to Lord Shido![n][w][e]

[msg TalkMsg_CONTACT_18_3]
[s]W-Wait! What do you want from me?[n][w][e]

[msg TalkMsg_CONTACT_19_1]
[s]Y-You... What are you doing here,[n]sneaking around in this area!?[n][w][e]

[msg TalkMsg_CONTACT_19_2]
[s]Please don't shoot! I promise I won't[n]say a thing to His Excellency![n][w][e]

[msg TalkMsg_CONTACT_19_3]
[s]W-Wait! What do you want from me?[n][w][e]

[msg TalkMsg_CONTACT_10_1]
[s]Y-You... What are you doing here,[n]sneaking around in this area!?[n][w][e]

[msg TalkMsg_CONTACT_10_2]
[s]Please don't shoot! I promise I won't[n]say a thing to the secret boss![n][w][e]

[msg TalkMsg_CONTACT_10_3]
[s]W-Wait! What do you want from me?[n][w][e]

[msg TalkMsg_FQ_REACT_GOODMOO]
[s](planned to be cut)[n]I like this side of you. Hmhm... I'm already[n]starting to feel better.[n][w][e]

[msg TalkMsg_FQ_REACT_INTERES]
[s](planned to be cut)[n]You say the most interesting things, though[n]they often don't match your appearance.[n][w][e]

[msg TalkMsg_FQ_REACT_DISPLEA]
[s](planned to be cut)[n]Has anyone ever told you that you have no[n]artistic sensibilities?[n][w][e]

[msg TalkMsg_FQ_REACT_ANGER]
[s](planned to be cut)[n]Are you deliberately trying to upset me?[n]Or am I overthinking things...[n][w][e]

[msg TalkMsg_FQ_REACT_BROKEDO]
[s]Hmph... What a cheapskate.[n][w][e]

[msg TalkMsg_HAVE_NO_SECRET]
[s]This is difficult to admit, but... I don't have[n]any information that would be of any use to[n]you.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_REF]
[s]Where did you get the idea that talking[n]would resolve anything!? Just who do[n]you think you are!?[n][w][e]

[msg TalkMsg_RESULT_ENEMY_REF_2]
[s]No, I would rather die than speak to you![n][w][e]

[msg TalkMsg_RESULT_ENEMY_REF_3]
[s]Me? Speak to a human? Please, don't insult[n]me![n][w][e]

[msg TalkMsg_SHOOT_REACTION01]
[s]A-Are you the type that lets your emotions[n]get the better of you? I'm the same, so I can[n]underst— Oh![n][w][e]
[s]I'm sorry, I remember now...[n][w][e]

[msg TalkMsg_SHOOT_REACTION02]
[s]Do you crave stimulation? I can tell,[n]since I'm the same w— Oh![n][w][e]
[s]I'm sorry, I remember now...[n][w][e]

[msg TalkMsg_SHOOT_REACTION03]
[s]Y-You seem like the quiet type, but maybe[n]you like it flashy? I'm the same, so I can[n]underst— Oh![n][w][e]
[s]I'm sorry, I remember now...[n][w][e]

[msg TalkMsg_SHOOT_REACTION04]
[s]You're the type that constantly seeks power[n]over others... I can tell, since I'm the same[n]wa— Oh![n][w][e]
[s]I'm sorry, I remember now...[n][w][e]

[msg TalkMsg_PLEAD_SKIMMING]
[s]Sorry, but... do you have business with me?[n]You've been staring at me this whole time![n][w][e]

[msg TalkMsg_PLEAD_NO_SKIMMIN]
[s]I implore you! Please spare my life![n][w][e]

[msg TalkMsg_ACCEPT_ALERT_DOW]
[s]Very well. I shall let everyone know that I[n]haven't encountered anything that'd arouse[n]suspicion.[n][w][e]

[msg TalkMsg_NO_REQUIREMENT]
[s]You don't have it? That breaks my heart...[n][w][e]

[msg TalkMsg_RESULT_SQ_ITEM1]
[s]Fair enough. I shall give you this.[n]Forget you ever saw me.[n][w][e]

[msg TalkMsg_RESULT_SQ_ITEM2]
[s]Ah, I see. Please, take this as a small gift.[n]I'm glad I've come to understand you a[n]bit more.[n][w][e]

[msg TalkMsg_RESULT_SQ_PERSON]
[s]Speaking with you shows me how similar we[n]really a— Oh! I'm sorry, I remember now...[n][w][e]

[msg TalkMsg_RESULT_SQ_PERSON_2]
[s]That's how I think as we— Oh! I'm sorry,[n]I remember now...[n][w][e]

[msg TalkMsg_RESULT_SQ_PAYFOR]
[s]...I understand what you're saying, but I'm[n]afraid I'm just not in the mood today.[n][w][e]

[msg TalkMsg_RESULT_SQ_PAYFOR_2]
[s]You and I are similar, aren't we...? And yet,[n]I'm not in the mood for this.[n][w][e]

[msg TalkMsg_RESULT_SQ_AGAIN1]
[s]In the end, what was it that you wished to[n]say again?[n][w][e]
[s]Shall we talk about it once more?[n][w][e]

[msg TalkMsg_RESULT_SQ_AGAIN2]
[s]In the end, what was it that you wished to[n]say again?[n][w][e]
[s]Shall we talk about it once more?[n][w][e]

[msg TalkMsg_RESULT_SQ_CARD1]
[s]...I understand you, but this time, I wish for[n]you to let me go. Here, I leave you this gift.[n][w][e]

[msg TalkMsg_RESULT_SQ_CARD2]
[s]I won't deny we're similar, but for today,[n]please just let me go. Here, I shall leave[n]you this gift.[n][w][e]

[msg TalkMsg_RESULT_SQ_COUNTE]
[s]...Could you stop fooling around!?[n][w][e]

[msg TalkMsg_RESULT_SQ_COUNTE_2]
[s]I've never felt so annoyed in my life.[n]Would you please just die already!?[n][w][e]

[msg TalkMsg_RESULT_SQ_ALERT1]
[s]It occurs to me that you'd be a great match...[n]for all my rowdy friends![n][w][e]

[msg TalkMsg_RESULT_SQ_ALERT2]
[s]...I find your attitude quite offensive.[n]Perhaps it would be best if I consult[n]with a friend.[n][w][e]

[msg TalkMsg_RESULT_SQ_INFO1]
[s]Won't you please stop? I shall give some[n]valuable information in return.[n][w][e]

[msg TalkMsg_RESULT_SQ_INFO2]
[s]Look, I'm willing to compromise. In point of[n]fact, I have some information you may find[n]useful.[n][w][e]

[msg TalkMsg_RESULT_SQ_MONEY1]
[s]...At the very least, I'd like you to accept this.[n][w][e]

[msg TalkMsg_RESULT_SQ_MONEY2]
[s]...And with that, I shall give you this, so[n]please just let me go for today.[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_8]
[s]So that is my ordained path... However, it[n]appears there is nothing we can really[n]discuss...[n][w][e]
[s]Allow me to offer you this[n][f 2 5 3 9999 1] instead...[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_9]
[s]Ah, so that is my ordained path... Thank you[n]for showing me the way.[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_10]
[s]No, I refuse to be deceived. This cannot be[n]my ordained path![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_11]
[s]Ah, so that is my ordained path...[n][w][e]
[s]...[clr 1][var 2][clr 27] is[n]already your Persona. Please, have[n]this [f 2 5 3 9999 1] instead...[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_12]
[s]Ah, so that is my ordained path...[n][w][e]
[s]However, your level is far too low.[n]I apologize, but please take[n]this [f 2 5 3 9999 1] instead...[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_13]
[s]Please show me my ordained path...[n][w][e]

[msg TalkMsg_RESULT_HACKING]
[s]Your words have profoundly affected me.[n]I'm so deeply moved... I must give you this.[n][w][e]

[msg TalkMsg_SKIMMING_BRAINWA]
[s]Oh, you have your eye on this, do you not?[n]I didn't expect you to have such discerning[n]taste.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_11]
[s]I thank you, from the depths of my heart,[n]for sparing m— Oh! I'm sorry, I remember[n]now...[n][w][e]

[msg TalkMsg_CHARM_TECH_ITEM]
[s]...As a gentleman thief, I'd expect you to be a[n]bit more adroit in your deceptions.[n][w][e]

[msg TalkMsg_CHARM_TECH_PERSO]
[s]How should I put it? Ah, you're an[n]interesting lady. I wouldn't mind[n]conversing a little longer.[n][w][e]

[msg TalkMsg_BONUS_CARD]
[s]Oh my, would you forgive me if I gave[n]you this? I'm sure you can tell it's good,[n]high quality.[n][w][e]

[msg TalkMsg_DONATION]
[s]My, you require money? Well then, here.[n]Please accept this for your exploits.[n][w][e]

[msg TalkMsg_UNTALKABLE]
[s]Eee... Eeeeeeek![n][w][e]

[msg TalkMsg_GUY_OP_00_00]
[s]What are your intentions?[n][e]

[msg TalkMsg_GUY_OP_00_01]
[s]What will you do with me?[n][e]

[msg TalkMsg_GUY_OP_01_00]
[s]How horrid![n][e]

[msg TalkMsg_GUY_OP_01_01]
[s]You're pointing a gun at me...?[n][e]

[msg TalkMsg_GUY_OP_02_00]
[s]Shall we talk this over...?[n][e]

[msg TalkMsg_GUY_OP_02_01]
[s]Perhaps we can come to[n]an understanding...[n][e]

[msg TalkMsg_GUY_OP_03_00]
[s]This is atrocious.[n][e]

[msg TalkMsg_GUY_OP_03_01 [Ryuji]]

[msg TalkMsg_GUY_EN_No_00]
[s]...And with that, I bid you adieu. I do[n]appreciate you sparing my life.[n][w][e]

[msg TalkMsg_GUY_EN_No_01]
[s]...And with that, I must take my leave. I do[n]appreciate you helping me.[n][w][e]

[msg TalkMsg_GUY_EN_No_02]
[s]...And with that, I bid you farewell. I'm[n]pleased we could share an interesting[n]conversation.[n][w][e]

[msg TalkMsg_GUY_EN_bye_00]
[s]I will back down this time, but you had[n]better be careful from here on.[n][w][e]

[msg TalkMsg_GUY_EN_bye_01]
[s]Hmph... I wonder how much longer that[n]spirit of yours will work in your favor.[n][w][e]

[msg TalkMsg_GUY_EN_bye_02]
[s]I will be taking my leave now. Take care.[n][w][e]

[msg TalkMsg_GUY_NEGO_GIVE_00]
[s]...You're very thoughtful. It'd be rude of me[n]not to accept under these circumstances.[n][w][e]

[msg TalkMsg_GUY_NEGO_GIVE_01]
[s]I suppose it would be rude of me to decline.[n]I shall accept your gift.[n][w][e]

[msg TalkMsg_GUY_NEGO_DECLINE]
[s]You're insufferable. And here I am, fretting[n]and worrying for your benefit...[n][w][e]

[msg TalkMsg_GUY_NEGO_DECLINE_2]
[s]You're quite the penny pincher, are you not?[n]And here I was, taking an interest in you...[n][w][e]

[msg TalkMsg_GUY_NEGO_TAKE_00]
[s]It would please me greatly if this were to[n]benefit you.[n][w][e]

[msg TalkMsg_GUY_NEGO_TAKE_01]
[s]Is this to your satisfaction? You should be[n]grateful, you know.[n][w][e]

[msg TalkMsg_GUY_NEGO_DOUBLEU]
[s]...Oh? Is that still not enough?[n]You're insufferable...[n][w][e]

[msg TalkMsg_GUY_NEGO_DOUBLEU_2]
[s]You still desire more? Truly, there are[n]no limits to your greed, are there?[n][w][e]

[msg TalkMsg_GUY_NEGO_AGREE_0]
[s]This should be fine, yes? After all, this is for[n]your own benefit...[n][w][e]

[msg TalkMsg_GUY_NEGO_AGREE_0_2]
[s]It pleases me that you are willing to listen to[n]what I have to say.[n][w][e]

[msg TalkMsg_GUY_NEGO_REFUSE_]
[s]...Is that so? A pity. After all, this was for your[n]own benefit...[n][w][e]

[msg TalkMsg_GUY_NEGO_REFUSE__2]
[s]You're insufferable... How could you[n]possibly decline my generous offer?[n][w][e]

[msg TalkMsg_Coop_Reiji_00 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 10 301 1]Hey, what are you tryin' to pull?[n]Use your head, man![n][w][e]

[msg TalkMsg_Coop_Reiji_01 [Ryuji]]
[s]It seems like the Shadow[n]reconsidered...[n][w][e]

[msg TalkMsg_Coop_Morgana_00 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 10 301 1]Don't move! Your very life is on the line![n][w][e]

[msg TalkMsg_Coop_Morgana_01 [Morgana]]
[s]It seems like the Shadow[n]reconsidered...[n][w][e]

[msg TalkMsg_Coop_Ann_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 3 301 1]Don't move—unless you wanna get[n]filled with lead![n][w][e]

[msg TalkMsg_Coop_Ann_01 [Ann]]
[s]It seems like the Shadow[n]reconsidered...[n][w][e]

[msg TalkMsg_Coop_Yugo_00 [Yusuke]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 5 3 301 1]Resistance is futile! Consider well[n]the position you are in.[n][w][e]

[msg TalkMsg_Coop_Yugo_01 [Yusuke]]
[s]It seems like the Shadow[n]reconsidered...[n][w][e]

[msg TalkMsg_Coop_Makoto_00 [Makoto]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 6 3 301 1]Stop resisting and work with us here![n][w][e]

[msg TalkMsg_Coop_Makoto_01 [Makoto]]
[s]It seems like the Shadow[n]reconsidered...[n][w][e]

[msg TalkMsg_Coop_Haruko_00 [Haru]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 7 3 301 1]Please wait! Do you understand the[n]position you find yourself in?[n][w][e]

[msg TalkMsg_Coop_Haruko_01 [Haru]]
[s]It seems like the Shadow[n]reconsidered...[n][w][e]

[msg TalkMsg_Coop_Akechi_00 [Akechi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 9 3 301 1]Wait! You would be wise not to[n]attempt any sudden moves.[n][w][e]

[msg TalkMsg_Coop_Akechi_01 [Akechi]]
[s]It seems like the Shadow[n]reconsidered...[n][w][e]

[msg TalkMsg_Sense_Sixthsense [Akechi]]
[s]Initiating Sixth Sense![n][f 1 3 65535][w][e]
[s]Your heightened sense has made clear[n]an option that should not be chosen![n][w][e]

[msg TalkMsg_Sense_Negotiatio [Akechi]]
[s]Initiating Negotiation![n][f 1 3 65535][w][e]
[s]With heightened negotiation technique,[n]you now receive greater cooperation![n][w][e]

[msg TalkMsg_Sense_Gigolo_00 [Akechi]]
[s]Initiating Gigolo![n][f 1 3 65535][w][e]
[s]Showing off your refined seduction[n]stimulates the hearts and minds[n]of female Shadows![n][w][e]

[msg TalkMsg_Sense_Performanc [Akechi]]
[s]Initiate Performance![n][f 1 3 65535][w][e]
[s]Perform splendid antics and[n]captivate the "Enemy Shadow's[n]Interest."[n][w][e]

[msg TalkMsg_Sense_Intelligen [Akechi]]
[s]Initiate Intelligence![n][f 1 3 65535][w][e]
[s]Your broad-based display of knowledge[n]wins the respect of male Shadows![n][w][e]

[msg TalkMsg_Tisei]
[s]You don't have enough[n]intelligence to choose that.[n][f 1 4][e]

[msg TalkMsg_Iroke]
[s]You don't have enough[n]seductiveness to choose that.[n][f 1 4][e]

[msg TalkMsg_Ginou]
[s]You don't have enough technique[n]to choose that.[n][f 1 4][e]

[msg TalkMsg_Hinsei]
[s]You don't have enough character[n]to choose that.[n][f 1 4][e]

[msg TalkMsg_Yuuki]
[s]You don't have enough courage[n]to choose that.[n][f 1 4][e]

[sel Nego_Surrender_sel top]
[s]Lend me your power.[e]
[s]Show me the money.[e]
[s]I want an item.[e]
[s]Panther, you handle this.[e]

[sel Nego_Surrender_sel_01 top]
[s][clr 2]Join my cause.[clr 27][e]
[s]Give me some money.[e]
[s]I want an item.[e]
[s]Panther, you handle this.[e]

[sel Nego_Surrender_sel_02 top]
[s]Lend me your power.[e]
[s][clr 2]Show me the money.[clr 27][e]
[s]I want an item.[e]
[s]Panther, you handle this.[e]

[sel Nego_Surrender_sel_03 top]
[s]Lend me your power.[e]
[s]Show me the money.[e]
[s][clr 2]Give me the goods.[clr 27][e]
[s]Panther, you handle this.[e]

[sel Nego_Surrender_sel_04 top]
[s]Lend me your power.[e]
[s]Show me the money.[e]
[s][clr 2]Give me the goods.[clr 27][e]
[s]Panther, you handle this.[e]

[sel Nego_Payfor_sel top]
[s]I'll take it.[e]
[s][clr 2]You can do better than that.[clr 27][e]

[sel Nego_Brainwash_sel top]
[s]Submit to me.[e]
[s]Give me a donation.[e]
[s]Give me something useful.[e]
[s]Panther, you handle this.[e]

[sel TalkSel_Greet_Possesed_B top]
[s]All right, I suppose.[e]
[s]I didn't ask for this.[e]

[sel TalkSel_Pre_Question top]
[s]All right, I suppose.[e]
[s]There's no need for that.[e]

[msg Talk_tech]
[s]Yoshida Toranosuke[n]Impression Management! (Provisional)[n][w][e]

[sel TalkSel_Tech top]
[s]Please, help...![e]

[msg CharmTech [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 5 301 1]Come now, hot stuff. Can't you be[n]a little more gentle with me?[n][w][e]

[msg CharmActing [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 5 301 1]No... How could you take that from us!?[n][w][e]

[msg RareBooster]
[s]Yoshida Toranosuke[n]Impression Management! (Provisional)[n][w][e]

[msg CheapAct [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 5 300 1]Joker, this is too scary... we should[n]get out of here. Hey! Could you tell[n]your boss that we're leaving now?[n][w][e]

[msg TalkMsg_cnt_interruptE]
[s]A different enemy cut into the conversation.[n][w][e]

[msg TalkMsg_cnt_interruptP]
[s]After conversing with target[n]once, party members can cut in to[n]speed things up (percent chance).[n][w][e]

[msg TalkMsg_cnt_refuse]
[s]Target refused to converse. →[n]This happens if the result of[n]the conversation is a refusal.[n][w][e]

[msg TalkMsg_cnt_anger]
[s]Target is angry and counterattacks[n]Bad case when the result of[n]the conversation is refusal.[n][w][e]

[msg TalkMsg_cnt_unusual]
[s]Unable to converse due to[n]status effects.[n][w][e]

[msg TalkMsg_EOF]
[s]......[n][w][e]

[msg DebugMsg_ERROR]
[s](Error) →A variable is set to an invalid value.[n][w][e]

[msg DebugMsg_CHARACTER]
[s](Debug Mode)[n]Target Personality Type[n][w][e]

[sel DebugSel_CHARACTER top]
[s]Type A[e]
[s]Type B[e]
[s]Type C[e]
[s]Type D[e]
[s]Random[e]

[msg DebugMsg_CHECK_VAR]
[s][var 0].[n][w][e]

[msg DebugMsg_ENEMY_LV]
[s]Enemy ID [var 3][n]Enemy Level [var 0][n]Protag Level [var 1][n]AI_CHK_ENIDLV_O([var 0], 1) = [var 2][n][w][e]

[msg TalkMsg_GUY_RESULT_GET_P_4 [Ann]]
[s]Then I would like to give some experience[n]to the me within you.[n][w][e]

[msg TalkMsg_Coop_AkechiB_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 9 3 301 1]Huh, I wouldn't say that's a wise[n]choice... Perhaps you should give[n]this some more thought.[n][w][e]

[msg TalkMsg_Coop_Kasumi_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 11 3 301 1]Stop! I think you would be wise not[n]to make any careless moves.[n][w][e]

[msg TalkMsg_Coop_Sumire_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 11 3 301 1]Stop! I think you would be wise not[n]to make any careless moves.[n][w][e]

