[msg MSG_000_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3032 65535 0]Sorry to call you over out of the blue[n]like this—please, feel free to make[n]yourself at home.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Your room is beautiful.[e]
[s]You wanted to talk?[e]

[msg MSG_002_0_0 [Haru]]
[s][bup 0 7 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 3178 65535 0]Oh, there's nothing all that unusual[n]in here... No need to look around like[n]that.[n][f 1 3 65535][w][e]

[msg MSG_002_5_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...I needed to speak with you about[n]this situation... or rather, because[n]of it.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Yes, well...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]...I needed to speak with you about[n]this situation... or rather, because[n]of it.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I feel I owe you an apology,[n][f 4 2]-kun.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3177 65535 0]I'm sorry... I was just so useless.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]What's this all about?[e]
[s]What do you mean?[e]

[msg MSG_007_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I'm so ashamed...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Dr. Maruki crafted me a saccharine,[n]perfect new reality—and I accepted it[n]without a second's pause.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It was only because of you that I was[n]able to find my own path.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You were the one who gave me a[n]future... and what did I do with it...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...I'm so pathetic.[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Don't worry about it.[e]
[s]It's not your fault.[e]

[msg MSG_010_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3182 65535 0]...You're so kind, [f 4 2]-kun.[n]But I'm afraid that doesn't feel like[n]enough, this time.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I want to stand at your side through[n]this, and I want to do it with pride.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3184 65535 0]In truth... I did wish that my father[n]was still alive.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I wanted us to rebuild the company[n]together. No, more than that—I wanted[n]to save my father.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]But that's just not possible.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No matter how important he was to me,[n]he's gone now, and I cannot bring him[n]back.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Surely, if... if I could just rewrite the[n]past for my own benefit, it would be[n]terribly selfish.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]Why do you think that?[e]
[s]What about your happiness?[e]

[msg MSG_015_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3021 65535 0]I... don't know.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]But what of the newfound purpose I[n]gained after my father's death? What of[n]all the support you gave me?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Even if I could simply choose to be[n]happy, it wouldn't be worth denying[n]everything that brought me here.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3194 65535 0]...Just because it made me happy[n]doesn't mean it's right.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Because what about next time? When[n]I fail again, or something goes wrong,[n]do I simply get to erase that, too?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Knowing my father is gone... It's sad,[n]and it hurts. But that pain is precisely[n]what gave me strength, and resolve.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]All of us went through so much together.[n]I don't want to lose our struggles, or[n]the closeness we won through them.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Haru]]
[s][bup 0 7 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]So I need you to understand that I'm[n]determined to see this through. I won't[n]run away anymore.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I refuse Dr. Maruki's "gift" to us.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 53510 65535 0]I'll choose our reality. The one I defined[n]through my own hardship, mistakes,[n]and tears.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Haru]]
[s][vp 8 2 0 53511 65535 0]Is this... my power? I see...[n]So I can still fight harder.[n][f 1 3 65535][w][e]

[msg PFM_019_5_0]
[s][vp 1 0 0 0 0 0]Haru's Persona [clr 1]Astarte[clr 27] has[n]transformed into [clr 2]Lucy[clr 27]![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I'm sorry I kept you for so long.[n]That's all I wanted you to hear.[n][f 1 3 65535][w][e]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][vp 8 2 0 0 65535 0]From now on, I'll fight even harder—[n]to make up for all the trouble I've[n]caused you.[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s]You already fight hard.[e]
[s]I'll be counting on you.[e]

[msg MSG_022_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3023 65535 0]Thank you.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hearing you say that makes me feel[n]like I can do anything.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3023 65535 0]Yes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hearing you say that makes me feel[n]like I can do anything.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I will grow even stronger.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I have to keep pressing forward.[n]For Father's sake, too.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Haru]]
[s][vp 8 2 0 3060 65535 0]Thanks again for coming today.[n]Be careful on your way home.[n][f 1 3 65535][w][e]

