[msg MSG_000_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10028 65535 0]So, the chairman's pushing me as hard[n]as ever to sell those fake stones...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I've been trying to use this as an[n]opportunity to investigate into the[n]ADP's seminars so I can expose him...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]But the deeper I dig, the scarier[n]everything becomes.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]How so?[e]
[s]What have you found?[e]

[msg MSG_001_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10135 65535 0]The ADP apparently doesn't profit very[n]much from sales of the Holy Stones.[n]It's nothing more than a front.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Most of their revenue actually comes from[n]the seminars.[n][f 1 3 65535][w][e]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 50][vp 8 0 0 0 65535 0]There, they give their patrons some sort[n]of mind-altering drug...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]After which, they're encouraged to donate[n]their life savings to the "benefit of the ADP."[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]People have even gone missing after[n]seminars... Families have been torn[n]apart by this madness...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10028 65535 0]And I... I was a part of it all.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]By selling these fraudulent stones, I was[n]in direct support of their horrible actions.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I know this doesn't make up for what I've[n]done... but I want to help the others come[n]to their senses.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Barely anyone within the ADP will talk[n]to me though, and those who do won't[n]actually hear me out.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]What should I do, [f 4 1]-san...?[n]These people are all heading down[n]a path toward great ruin...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Chihaya]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 113 5 300 1][vp 8 2 0 10047 65535 0]There has to be some way I can deal with[n]the chairman...[n][f 1 3 65535][w][e]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Right. I'll just have to admit to everything[n]that's been going on, even if I get dragged[n]down too...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That's... the only way...[n][f 1 3 65535][w][e]

[msg MND_015_0_0]
[s][vp 8 0 0 0 65535 0]It looks like Chihaya's not sure how to[n]approach this issue...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]She might do something rash at this rate...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]I should take care of the chairman[n]before that happens...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10110 65535 0]I'm the only one who can stop him... right?[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Tell me his name.[e]
[s]What's Fukurai's first name?[e]

[msg MSG_005_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10043 65535 0]Oh, the chairman...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It's [clr 2]Yuichi Fukurai[clr 27].[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10018 65535 0]Why do you ask...?[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]I can't tell you.[e]
[s]Don't worry about it.[e]

[msg MSG_008_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10028 65535 0]O-Oh...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hm, how strange... It seems the cards have[n]changed somehow...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]My future is in line with that of the[n]Trickster... What does that mean...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Even so, my fate remains unchanged.[n]I am destined to stay a monster...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 10021 65535 0]Hm...[n][f 1 3 65535][w][e]

[msg MND_011_0_0]
[s][vp 8 0 0 0 65535 0]I need to take care of the chairman[n]for Chihaya...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'll have to think on this for a while.[n]Let's finish for today...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Chihaya]]
[s][vp 8 2 0 10139 65535 0]Well then, goodbye...[n][f 1 3 65535][w][e]

