[msg MSG_000_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13071 65535 0]Listen up, kid. I figured out Tsuda's[n]weakness.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]While you and Kaoru were over at that[n]diner, I was out gettin' info from a[n]reliable source of mine.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Turns out I guessed right.[n][f 1 3 65535][w][e]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 104 10 300 65535][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tsuda was the one on the other end of[n]that Hong Kong mafia deal.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Apparently he paid them off for a huge[n]arsenal of guns.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Iwai]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 104 10 300 1][vp 8 2 0 13094 65535 0]This is where things start gettin'[n]interestin' though.[n][f 1 3 65535][w][e]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]If he was smugglin' all that shit in,[n]why would he come to me askin' for[n]modified guns?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I mean, don't somethin' about that[n]seem off to you?[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Not at all.[e]
[s][f 0 8 2 1 2217]Absolutely.[clr 27][e]
[s]I guess he likes guns?[e]

[msg MSG_004_0_0 [Iwai]]
[s][bup 0 104 3 0 0][f 4 10 65535 0 0][vp 8 2 0 13028 65535 0]C'mon, you gotta see somethin' up[n]with that...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 0 13082 65535 0][f 5 13 13 10 1004]Right?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That piece of shit's tryin' to lord his[n]position over me... but he ain't got[n]shit now![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 0 13082 65535 0][f 5 13 13 5 1004]Heh, damn right. He loves 'em.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]What I'm really sayin' here is... I don't[n]think those Hong Kong guys ever[n]delivered on their end of the deal.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]They prolly just took his money and[n]flat-out stiffed him on the guns.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Masa told me somethin' real weird[n]back when you and Kaoru were over[n]at the diner though.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13021 65535 0]Apparently, the clan's been treatin' that[n]Hong Kong transaction like some kinda[n]massive business success.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That means Tsuda's been lyin' to 'em[n]this whole time...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]And now he's tryin' to use me to cover up[n]his mistake.[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]That's horrible.[e]
[s][f 0 8 2 1 2217]He's clever.[clr 27][e]
[s]What a crafty bastard.[e]

[msg MSG_010_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13043 65535 0]Hey, there's nothin' wrong with gettin'[n]some dumbass to take the fall when[n]you mess somethin' up.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'd just rather not be that dumbass.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13043 65535 0][f 5 13 13 10 1004]Yup. Everyone's always known he's one[n]sneaky son of a bitch.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13043 65535 0][f 5 13 13 5 1004]Yup. Everyone's always known he's one[n]sneaky son of a bitch.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13074 65535 0]...Don't matter now though. Everything's[n]gonna change once I tell the clan[n]what's up.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tsuda's not gonna be able to keep[n]intimidatin' me anymore.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]And I'll make sure Kaoru won't get[n]labeled, like I was...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]He'll be a regular, respectable adult.[n]Somethin' I coulda never even[n]dreamed of...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'm gonna have to talk to Tsuda himself[n]first though. Gotta follow the yakuza code.[n][f 1 3 65535][w][e]
[s][bup 0 104 0 0 0][f 4 24 0 4 0 59 5 100][vp 1 0 0 0 0 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 13019 65535 0]Hey, I got a favor to ask you.[n]If anythin' happens to me,[n]take care of Kaoru, okay?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Okay?[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s]Is Tsuda seriously dangerous?[e]
[s]Are you going alone?[e]

[msg MSG_020_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yeah. I'd like to think he's above[n]thug shit like that...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]But if he wanted, he could get rid of me[n]no problem. Unless I had some kinda[n]witness with me, that is...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Wait a sec. I've got you.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Prolly. I know he'd be able to get rid of[n]me no problem without a witness there,[n]but I've gotta put an end to this.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Besides, nobody would wanna...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Wait a sec. I've got you.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13035 65535 0]I want you to come talk to Tsuda[n]with me.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]He's not gonna dare lay a finger on[n]a civilian kid. It'd cause way too many[n]complications for him.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]If you come as my witness, things'll be[n]miles safer.[n][f 1 3 65535][w][e]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 5 100][vp 8 2 0 13086 65535 0]...All right then. It's settled.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, and lemme think of a reward. Gotta[n]thank you for the info, and for bein' my[n]witness.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 13083 65535 0]How 'bout I work even harder on that[n]special menu? That should be good[n]for you, yeah?[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]It feels like my bond with Iwai[n]is growing even deeper...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, I'll hit you up when it's time.[n]Let's do this, kid.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Iwai]]
[s][vp 8 2 0 13053 0 0]Thanks for today.[n][f 1 3 65535][w][e]

