[msg MSG_000_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 0 14027 65535 0]...Okay, that's all for today.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]If you're feeling okay, you can go[n]home now.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 0 14004 65535 0]Hello. Doctor Takemi's Clinic of Internal[n]Medicine.[n][f 1 3 65535][w][e]
[s][bup 0 108 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 39 5 40]...What? Again?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That's, well... that ship's already[n]sailed, so...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Takemi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 108 5 301 1][vp 8 2 0 14028 65535 0]*sigh* ...What a pain.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You remember that girl from the other[n]day? The Chief of Staff Oyamada's[n]patient?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Her dad's been bringing her here to be[n]treated, even though I referred them[n]to another hospital.[n][f 1 3 65535][w][e]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I even told them about the medical error[n]I made...[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]They trust you.[e]
[s]Was it really your fault?[e]

[msg MSG_005_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'm just a quack though...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Uh...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 0 14021 65535 0]The medical error was well-documented.[n]Everyone in my field knows about it.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I led the development of a new[n]drug for an incurable illness[n]called "Crawford-Ende's disease."[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Although I wasn't the one who[n]administered the medicine, it was[n]the cause of the error.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]With Crawford-Ende's, certain cells[n]indiscriminately attack other cells[n]throughout the body.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]When it reaches the muscles, the patient[n]slowly begins to die...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]There hasn't been much progress made[n]on it—partly because there haven't been[n]many cases of it.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I worked with a pharmaceutical company[n]that had reached the final stage of[n]production, but...[n][f 1 3 65535][w][e]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]One day, I was suddenly removed from[n]my position.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That Chief of Staff Oyamada, my[n]superior at the time, took over[n]the entire operation.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Takemi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 108 3 301 1][vp 8 2 0 14041 65535 0]I don't know if he wanted the glory of[n]developing a new drug or to become[n]rich and famous, but...[n][f 1 3 65535][w][e]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]He made careless mistakes and rushed[n]completion so he could use it on[n]a patient named Miwa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Miwa-chan had a reaction and lapsed [n]into critical condition. The chief panicked[n]and laid the blame on me.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Miwa-chan and her family resented me...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...No matter what I said, I couldn't change[n]how they felt about me.[n][f 1 3 65535][w][e]

[sel SEL_011_5_0 top]
[s]I had no idea.[e]
[s]It's not too late.[e]

[msg MSG_012_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 0 14064 65535 0]Well, that doesn't matter...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The development of the medicine was[n]suspended, so I had no reason to stay[n]at that hospital.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]At least now I can keep working as a[n]general practitioner, on my own terms...[n]with my guinea pig.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That's the new medicine I've been[n]trying out on you. This version is in[n]the final stage of testing.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It searches for those cells that take[n]the offensive and destroys them[n]upon detection.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That's why it's harmless for people who[n]don't have the disease... probably.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s][f 0 8 2 1 2217]That's good.[clr 27][e]
[s]When will it be done?[e]
[s]..."Probably"?[e]

[msg MSG_015_0_0 [Takemi]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 0 14048 65535 0][f 5 13 14 10 1008]You have a lot of faith in me. Thank you,[n]my little guinea pig.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Takemi]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 0 14132 65535 0][f 5 13 14 5 1008]That all depends on how cooperative[n]you are.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, nothing in life is guaranteed, right?[n][f 1 3 65535][w][e]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 0 14048 65535 0]...Hehe. Don't make that face.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Don't worry. This substance can't cause[n]any harm to cells that haven't been[n]infected.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 0 14080 65535 0]You'd better not flake on me this late in[n]the game.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'm inching closer to the finish line,[n]but I need your help to reach it.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]In exchange, I can offer you medicine[n]at a special price. I'm counting on you,[n]guinea pig.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]It feels like my bond with Takemi[n]is growing even deeper...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 2 0 14021 65535 0]Now, what should I do about that girl[n]and her dad? Being mean and scaring[n]them hasn't worked.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It's been a while since I've had to deal[n]with this kind of nuisance. It's stressing[n]me out.[n][f 1 3 65535][w][e]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 59 5 100]...Oh, sorry, that's all I wanted to talk to[n]you about. You can go home now.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Takemi]]
[s][vp 8 2 0 14097 65535 0]Okay, thanks for your hard work.[n][f 1 3 65535][w][e]

