[msg MSG_000_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, today's the day...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]...After I confessed, [n]I was scorned by the media. [n]I bet everyone wants me to lose.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]However, I'm not going to give[n]them the satisfaction. I'm going[n]to win... with these very hands.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 0 8 2 1 2217]Give it all you got.[clr 27][e]
[s]Do you feel confident?[e]
[s]You can do it.[e]

[msg MSG_003_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I will![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...No.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]But I don't intend to simply [n]let him win.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We shall see.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]But I'll do my very best.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, it's time.[n]I have to go to the venue.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]You won't be able to go inside the[n]match room, but you can watch over[n]the internet, if you'd like.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Now... I should be going.[n][f 1 3 65535][w][e]

