[msg MSG_000_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]...However, the government's overall[n]approval rating is dangerously low.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yoshida]]
[s][bup 0 112 500 0 0][f 4 10 65535 0 0][vp 8 2 0 20020 65535 0]I'll be sure to proceed with caution.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Considering that the grandson of[n]my former teacher is showing me[n]such kindness.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]Yes, well, I'd like to discuss a personal[n]matter. Allow me to be frank.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]I will be running for my grandfather's[n]seat in the coming election.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yoshida]]
[s][bup 0 112 501 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I see... Congratulations.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 7 300 65535]I held a low-level position in[n]the party's executive office,[n]but I'm new to candidacy... [n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 7 0]So I was hoping you could educate me[n]on how to run an election campaign.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yoshida]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 7 300 1][vp 8 2 0 20043 65535 0]Well, I was planning on running myself...[n]And I don't believe that I'm qualified to[n]teach you.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]I've heard that you've been working[n]harder than anyone these past twenty[n]years.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yoshida]]
[s][bup 0 112 500 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, I did have a lot of free[n]time after I lost the election.[n]Study is all an amateur can do.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]Amateur? You're a veteran,[n]if anything. Besides, you have[n]experience teaching him, right?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]Your reputation has greatly improved[n]around the executive office recently.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 7 0]And my grandfather has expressed his[n]intent on making peace with you now.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yoshida]]
[s][bup 0 112 503 0 0][f 4 10 65535 0 0][vp 8 2 0 20027 65535 0]I'd be happy to bury the hatchet[n]with Mr. Kuramoto...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]But I'm not worthy to join his group again.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]I thought you would find[n]these conditions favorable...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]...So I ask that you keep what[n]I'm about to tell you a secret.[n][f 1 3 65535][w][e]

[msg MSG_013_3_0 [Yoshida]]
[s][bup 0 112 500 0 0][f 4 10 65535 0 0][vp 8 2 0 20018 65535 0]Sorry, could you give us[n]a moment, [f 4 1]-kun? [n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Benzo]]
[s][vp 8 0 0 0 7 0]No, I'd like for your favorite[n]pupil to hear this too.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Yoshida]]
[s][bup 0 112 500 0 0][vp 8 2 0 20038 65535 0]......?[n][f 1 3 65535][w][e]
[s][bup 0 112 502 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 37 5 100][vp 8 0 0 0 65535 0]Wait a moment... is your plan to[n]involve him so that I can't decline?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]I simply trust his discretion.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]The Kuramoto group is planning to[n]move forward with a political realignment.[n][f 1 3 65535][w][e]

[msg MSG_017_5_0 [Yoshida]]
[s][bup 0 112 504 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Are you saying that you're[n]going to secede from the [n]Liberal Co-Prosperity Party...?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]With the government in a weakened[n]state, now's our chance. As such,[n]I want to emphasize our unity.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Yoshida]]
[s][bup 0 112 500 0 0][f 4 10 65535 0 0][vp 8 2 0 20044 65535 0]And so you've come to me,[n]a former member of the[n]Kuramoto Children...[n][f 1 3 65535][w][e]
[s][bup 0 112 503 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][vp 8 0 0 0 65535 0]But my views differ from those of[n]the Kuramoto group. And I[n]don't intend on changing them.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]I understand. However, you won't[n]be able to put those beliefs into[n]action if you don't get elected.[n][f 1 3 65535][w][e]

[msg MSG_020_5_0 [Benzo]]
[s][vp 8 0 0 0 7 0]...[f 4 1]-kun, could you talk some[n]sense into him? You'll benefit as well.[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s][f 0 8 2 1 2217]You should decline.[clr 27][e]
[s]That's a sweet deal.[e]
[s]I wasn't paying attention.[e]

[msg MSG_022_0_0 [Yoshida]]
[s][bup 0 112 500 0 0][f 4 10 65535 0 0][vp 8 2 0 20021 65535 0][f 5 13 20 5 1012]You think so too, hm...?[n][f 1 3 65535][w][e]
[s][bup 0 112 501 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 42 5 100][vp 8 0 0 0 65535 0]Haha, you're not intimidated, even by[n]the grandson of a big-time Diet member.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yoshida]]
[s][bup 0 112 503 0 0][f 4 10 65535 0 0][vp 8 2 0 20021 65535 0]Yes, if you only think about[n]the election, but...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Yoshida]]
[s][bup 0 112 500 0 0][f 4 10 65535 0 0][vp 8 2 0 20075 65535 0]Haha... Sorry to bore you.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Yoshida]]
[s][bup 0 112 500 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...I appreciate your offer, but[n]I must respectfully decline.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]So you're okay with being[n]No-Good Tora forever?[n][f 1 3 65535][w][e]

[sel SEL_027_0_0 top]
[s]He's not No-Good Tora.[e]
[s]Call him Mr. Yoshida.[e]
[s]He'll get elected this time.[e]

[msg MSG_028_0_0 [Yoshida]]
[s][bup 0 112 504 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 1]-kun...[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]Looks like you chose the[n]wrong politician to follow.[n][f 1 3 65535][w][e]

[sel SEL_030_0_0 top]
[s]That's not for you to decide.[e]
[s]Maybe...[e]
[s]I still believe in him.[e]

[msg MSG_031_0_0 [Yoshida]]
[s][bup 0 112 500 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Try to understand that he has[n]his own beliefs.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]Haha, it sounds as if that's[n]not your true opinion...[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]...My apologies. I made a slip of the tongue.[n]And in front of your secretary, no less.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Benzo]]
[s][vp 8 0 0 0 7 0]I don't need an answer right away.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 7 0]If you want to show deference to[n]my grandfather... please let me know.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 7 0]I already took care of the bill, so enjoy.[n]Now, if you'll excuse me...[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Yoshida]]
[s][bup 0 112 503 0 0][f 4 10 65535 0 0][vp 8 2 0 20028 65535 0]What's the point in getting[n]elected if it means sacrificing[n]your beliefs?[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Yoshida]]
[s][bup 0 112 500 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I bet when push came to shove,[n]Kuramoto-kun intended to[n]lure you in.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]He probably didn't expect me to[n]remain so calm after he showed[n]his trump card.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I feel surprisingly at ease whenever[n]you're with me, like that time with[n]Matsushita.[n][f 1 3 65535][w][e]

[msg MSG_037_5_0 [Yoshida]]
[s][bup 0 112 501 0 0][f 4 10 65535 0 0][vp 8 2 0 20032 65535 0]I'm truly indebted to you for all you've[n]done for me, but I must ask that you[n]continue to help me.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with[n]Yoshida is growing deeper...[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Yoshida]]
[s][bup 0 112 500 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You know, from the way he was[n]acting, I'd swear Kuramoto-kun[n]was hiding something...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 20049 65535 0]Ah, my apologies. We're done[n]eating, so let's go home.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Yoshida]]
[s][vp 8 2 0 20054 65535 0]Good work today.[n][f 1 3 65535][w][e]

