[msg MSG_000_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57526 65535 0]Well, today's just going to be another[n]back-and-forth as usual...[n][f 1 3 65535][w][e]
[s][bup 0 216 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Or will it!? Today's your lucky day![n]Please take a look at what's on this[n]table![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Maruki]]
[s][bup 0 216 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I've been making you listen to all this[n]tough stuff about traumas, pain, and[n]grief lately, so...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I found these cookies in an underground[n]mall! Now we can have a little break![n]They're kind of fancy cookies, too...[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Maruki]]
[s][bup 0 216 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I thought I'd get a surprise for you, since[n]you've been kind enough to indulge me[n]all this time. Go ahead, enjoy![n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 0 8 2 1 2217]This looks great![clr 27][e]
[s]How old do you think I am?[e]
[s]I could just take cash...[e]

[msg MSG_003_0_0 [Maruki]]
[s][bup 0 216 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 35 10 1014]Go on, don't be shy! I've got enough[n]for seconds, too![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Maruki]]
[s][bup 0 216 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I-I'm sorry, I didn't mean anything[n]patronizing by it... I just love little[n]treats like this myself, so...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Maruki]]
[s][bup 0 216 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 35 5 1014]Hahaha! You crack me up! Like I've got[n]the spare income to pay you.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57486 65535 0]Oh, I know. As long as we're talking[n]about cookies... They actually reminded[n]me about this psychological experiment.[n][f 1 3 65535][w][e]

[msg MSG_006_3_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The scientists prepared two containers,[n]and put the same kind of cookies in[n]both of them.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]In one container, they put only one[n]cookie. But the other one was filled[n]with cookies—ten of them.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So then they had their subjects try[n]cookies from each container, and asked[n]how their tastes compared.[n][f 1 3 65535][w][e]

[msg MSG_006_7_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Which container's cookies were marked[n]as tasting better? Any guesses?[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]The one-cookie container.[e]
[s]The ten-cookie container.[e]
[s]It was a tie.[e]

[msg MSG_008_0_0 [Maruki]]
[s][bup 0 216 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57492 65535 0]Correct. Easy to guess, huh?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57498 65535 0]Sorry, not quite. The subjects preferred[n]the taste of the single cookie.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57519 65535 0]I see! You're a rationalist, are you?[n]Unfortunately, the truth is that they[n]preferred the isolated single cookie.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]There's something called the "law of[n]scarcity."[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It's about what you'd imagine from the[n]name: people are drawn to things that[n]are more scarce.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You can see this law in action just[n]by observing how excited people get[n]over limited-edition merchandise.[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]I never considered that.[e]
[s]They're getting played.[e]
[s][f 0 8 2 1 2217]You know, you're right.[clr 27][e]

[msg MSG_013_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It's a strange prospect, right? but also[n]really intriguing![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 35 5 1014]In some cases, sure. But don't you think[n]it's intriguing, as well?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Maruki]]
[s][bup 0 216 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 35 10 1014]Ahaha, I know, right? Don't you think[n]it's really fascinating?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]In becoming aware of scarcity, we trigger[n]our own desires, and cause a change[n]in our cognition...[n][f 1 3 65535][w][e]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 114 1 300 65535][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Not only that—the effect spreads to our[n]senses, and creates a subjective,[n]observable difference in our reality.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Maruki]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 114 1 300 65535][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Basically, your perceptions can be changed[n]by your cognition or preconceptions.[n][f 1 3 65535][w][e]

[msg MSG_017_5_0 [Maruki]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 114 1 300 1][vp 8 2 0 57517 65535 0]It's all below the conscious level, but[n]it's really incredible![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Incidentally, now that you've heard[n]that story...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]How do you feel about that idea? That[n]your unconscious desires may have[n]changed the taste of the cookie?[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s][f 0 8 2 1 2217]My senses lied to me![clr 27][e]
[s][f 0 8 2 1 2217]Hey, as long as it tastes good.[clr 27][e]
[s]It's a little scary.[e]

[msg MSG_020_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 35 5 1014]Yeah, a lot of people would feel the same.[n]After all, the taste didn't actually change[n]objectively.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Maruki]]
[s][bup 0 216 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 35 5 1014]That's definitely not the usual response.[n]But it's one I can understand.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I guess I can understand that[n]perspective, sure.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It probably sounds like an exaggeration,[n]but something about that seems so[n]beautiful to me.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Maybe the human heart can falter, or[n]be unreliable sometimes...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]But if this experiment proves anything,[n]it's that even a simple preconception can[n]be enough to bring someone more joy.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57511 65535 0]For example, take that story I just[n]told you...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]What if you'd eaten that one cookie, and[n]it had been the best cookie of your life?[n]Say I never revealed the trick behind it.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That cookie would have remained more[n]delicious than usual. It would have been[n]a subjective truth of your reality.[n][f 1 3 65535][w][e]

[sel SEL_025_0_0 top]
[s]Not "truth" exactly...[e]
[s][f 0 8 2 1 2217]I guess so.[clr 27][e]
[s]I don't know...[e]

[msg MSG_026_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, point taken. I can see why you'd[n]say that.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 35 5 1014]Right. I'm glad to hear you say that.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Maruki]]
[s][bup 0 216 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ahaha, sorry. Maybe I'm taking the[n]example a little too far.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Basically, what I wanted to say was...[n][f 1 3 65535][w][e]

[msg MSG_029_5_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]If this idea of preconception could be[n]studied further, and actually applied to[n]treating people...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I feel like it could help a lot of people.[n]Maybe even more than I could help[n]through counseling.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Your reaction is proof enough. Plenty of[n]people would probably see it as a lie,[n]or simply ignoring their problems.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Still, even if that's true, I still believe[n]that method could save a lot of people.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Then again, it relies so heavily on[n]perspective. Some people might call it[n]a lie, or see it as running from problems.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Still, even if that's true, I still believe[n]that method could save a lot of people.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Maruki]]
[s][bup 0 216 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 57514 65535 0]Oh, yikes! I'm so sorry! We wound up[n]getting into an academic conversation[n]after all...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I really need to watch myself. Whenever[n]I'm talking to you, somehow I always[n]end up going back to my research.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Maruki]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 114 1 300 65535][bup 0 216 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I truly am grateful for everything you've[n]done. Not just because I can get your[n]opinion on these things, either...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It's more like... it's as if I'm talking to[n]an old friend.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Maruki]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 114 1 300 1][vp 8 2 0 57517 65535 0]Ah, but maybe that's too personal. After[n]all, this is all for the sake of our deal,[n]right? So we say, anyway.[n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][vp 8 0 0 0 65535 0]I can sense a strong bond[n]of friendship from Maruki...[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Maruki]]
[s][bup 0 216 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Now then, I'd better show you another[n]way to mentally train yourself![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]What I'm going to teach you today is...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Maruki]]
[s][f 4 10 65535 0 0][vp 8 2 0 57466 65535 0]Make sure you get home before it[n]gets too dark, okay?[n][f 1 3 65535][w][e]

