[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]This sure brings back some memories...[n]It's been quite some time since we last[n]got together like this.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Reminiscing, are we?[e]
[s]Chatting like this again is nice.[e]

[msg MSG_001_3_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Reminiscing?[n][f 1 3 65535][w][e]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]*chuckle* You very well could be right.[n]I'm remembering things that are a bit[n]too bitter for my taste, though...[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Are you being serious right now?[n]...Although, I must admit it's rather[n]gauche of me to ask such a question.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]At any rate, I want to thank you about[n]the deal we made on the "ship."[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Shido was arrested in our reality after his[n]heart was changed by the Phantom[n]Thieves... Could this really be?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][vp 8 0 0 7 65535 0]Let's make a deal... Okay?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][vp 8 0 0 8 65535 0]Change Shido's heart...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Please![n][f 1 3 65535][w][e]

[sel SEL_004_3_0 top]
[s]There's no mistaking it.[e]
[s]Just upholding the deal.[e]

[msg MSG_004_5_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]I see...[n][f 1 3 65535][w][e]

[msg MSG_004_8_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Boy... You're honest to a fault, aren't you?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]For so, so long, I've wanted to crush him...[n]but it seems you took care of that for me.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Sorry, but I don't see this as a favor to[n]me—if anything, it's the exact opposite.[n]After all, I lost my one shot at revenge.[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s]Still hung up on that?[e]
[s]How's that make sense?[e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Are you saying I'm being illogical with[n]this? I'm well aware—I know this isn't[n]the reaction I'd usually have ...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]But, it's how I feel, so there's nothing[n]I can do about it.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Maruki may claim to be distorting[n]reality so as to grant the wishes of[n]society at large...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]However, that's still nothing more than[n]the most convenient path to attaining his[n]wishes... That's no different from Shido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]What's a life worth in a reality that was[n]cooked up just to satisfy someone else?[n]I say none.[n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]You're so right.[e]
[s]I get how you feel.[e]

[msg MSG_014_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Your straightforwardness is quite[n]aggressive... Actually, it's to the point[n]of irritation.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]I genuinely cannot comprehend how[n]you live your life like that.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]You can drop the strange attempt[n]at sympathizing with me.[n][f 1 3 65535][w][e]

[msg MSG_015_5_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]You don't call out the flaws in others,[n]yet you lack any sort of resentment[n]in them.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]I genuinely cannot comprehend how[n]you live your life like that.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]After speaking with you here, though,[n]I've come to a realization...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]I will never accept this form of reality.[n]I'm done being manipulated.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Let's go back... to our true reality.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Akechi]]
[s][vp 8 0 0 27 65535 0]Haha... So THIS is it![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]This is great... I feel so alive! I'll sow[n]chaos as far as the eye can see![n][f 1 3 65535][w][e]

[msg MSG_023_5_0]
[s][vp 8 0 0 0 65535 0]Akechi's Persona [clr 1]Loki[clr 27] has[n]transformed into [clr 2]Hereward[clr 27]![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]You still have my glove, right? Don't[n]think I've forgotten about that.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]I simply can't lose to you again.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]See you.[n][f 1 3 65535][w][e]

