[msg MSG_000_3_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](ざわつく声)[n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Post-Festival MC]]
[s][vp 8 0 0 1 65535 0]All right, that was a great performance[n]by the dance club![n][f 1 3 65535][w][e]
[s][vp 8 0 0 2 65535 0]Everybody give them another[n]round of applause![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](パラパラとした拍手)[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 3 2 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Phew...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 0 2 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]...My apologies for being so distracted.[n]I can't stop thinking about Akechi-kun...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Are we really no match for him...?[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Let's relax for now.[e]
[s]He's a tough foe.[e]
[s][f 0 8 2 1 2217]Don't worry, Makoto.[clr 27][e]

[msg MSG_005_0_0 [Makoto]]
[s][bup 0 6 3 2 0][f 4 10 65535 0 0][vp 8 0 0 74 65535 0][f 5 13 3 5 6]Hm...[n][f 1 3 65535][w][e]
[s][bup 0 6 0 2 0][f 4 10 65535 0 0][f 4 24 0 4 0 35 5 100][vp 8 0 0 6 65535 0]You're right. What's done is done.[n]We should enjoy ourselves for the[n]time being.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][bup 0 6 0 2 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]But... I don't want to lose.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 6 2 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0][f 5 13 3 10 6]...Thank you.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Post-Festival MC]]
[s][vp 8 0 0 9 65535 0]And now, it's time for your[n]favorite Shujin tradition:[n]the Student Sharing Special![n][f 1 3 65535][w][e]
[s][vp 8 0 0 10 65535 0]Round of applause, everyone![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](パラパラとした拍手)[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][bup 0 6 3 2 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]This event is never very popular.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 2 0][f 4 10 65535 0 0][f 4 24 0 4 0 35 5 100][f 4 24 0 4 0 0 5 100][vp 8 0 0 12 65535 0]The older teachers seem to enjoy it[n]for some reason though...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Post-Festival MC]]
[s][vp 8 0 0 13 65535 0]All right, who has something to say?[n]Anyone, anyone!?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 15 65535 0]No? I'll just have to pick someone then![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][bup 0 6 0 2 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Oh, he's choosing from the crowd?[n]The MC this year is actually somewhat[n]capable.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Post-Festival MC]]
[s][vp 8 0 0 19 65535 0]Oooh, is that our lovely student[n]council president over there!?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Makoto]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 6 7 301 1][vp 8 0 0 20 65535 0]Huh!?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Post-Festival MC]]
[s][vp 8 0 0 21 65535 0]Come on up here, Miss Prez![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Makoto]]
[s][bup 0 6 5 2 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]...Do I have to go?[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]He picked you.[e]
[s]Are you going to ignore him?[e]
[s]I'll never forget you.[e]

[msg MSG_021_0_0 [Makoto]]
[s][bup 0 6 3 2 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]That's true...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Makoto]]
[s][bup 0 6 3 2 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]I'm not that cold...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Makoto]]
[s][bup 0 6 3 2 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]That's not really the proper use[n]for that phrase...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Post-Festival MC]]
[s][vp 8 0 0 26 65535 0]Everybody's waiting for you,[n]Miss President![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](拍手)[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Makoto]]
[s][bup 0 6 3 2 0][f 4 10 65535 0 0][vp 8 0 0 72 65535 0]*sigh*[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Post-Festival MC]]
[s][vp 8 0 0 28 65535 0]Here she is: everyone's favorite student[n]council president, Makoto Niijima-san![n][f 1 3 65535][w][e]

[msg MSG_027_5_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](拍手)[n][f 1 3 65535][w][e]

[msg MSG_027_7_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Hello...[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 29 65535 0](ヤジ)[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Post-Festival MC]]
[s][vp 8 0 0 30 65535 0]So, with the Kamoshida scandal,[n]Principal Kobayakawa's passing,[n]and even that Hawaii trip...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 31 65535 0]I'd be surprised if you've had any time[n]to study for your entrance exams![n][f 1 3 65535][w][e]
[s][vp 8 0 0 32 65535 0]Now then, on with the show![n]What would you like to share[n]with us today, Miss President?[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Post-Festival MC]]
[s][vp 8 0 0 33 65535 0]...Miss President?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Makoto]]
[s][bup 0 6 0 2 0][f 4 10 65535 0 0][vp 8 0 0 75 65535 0]Ummm...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]I... don't really have anything to say...[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Makoto]]
[s][bup 0 6 0 2 0][f 4 10 65535 0 0][vp 8 0 0 76 65535 0]...I'm sorry.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Post-Festival MC]]
[s][vp 8 0 0 37 65535 0]Here, I'll give you a question...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 38 65535 0]Do you think the Phantom Thieves[n]are really Shujin students?[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Makoto]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 6 7 301 1][vp 8 0 0 39 65535 0]What!?[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](観衆のざわめき)[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Post-Festival MC]]
[s][vp 8 0 0 42 65535 0]We're all dying to know what[n]Akechi-kun was going to say about[n]their true identities.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 43 65535 0]Some people theorize that they go[n]to our very school...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 44 65535 0]So, are they from Shujin? What do you[n]think, Miss President?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Makoto]]
[s][bup 0 6 4 2 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]What do I think...?[n][f 1 3 65535][w][e]

[msg MND_038_5_0]
[s][vp 8 0 0 0 65535 0]Makoto is in trouble...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]I need to change[n]the subject...[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Makoto]]
[s][bup 0 6 3 2 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]That's...[n][f 1 3 65535][w][e]

[sel SEL_040_5_0 top]
[s]Do you have a boyfriend!?[e]
[s]You're cute![e]
[s]I've always loved you![e]

[msg MSG_041_0_0 [Makoto]]
[s][bup 0 6 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]Huh...!?[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Post-Festival MC]]
[s][vp 8 0 0 48 65535 0]Oooh, what a question![n][f 1 3 65535][w][e]
[s][vp 8 0 0 49 65535 0]I'd love to hear the answer too![n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Makoto]]
[s][bup 0 6 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]Huh...!?[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Post-Festival MC]]
[s][vp 8 0 0 79 65535 0]Ohooo![n][f 1 3 65535][w][e]
[s][vp 8 0 0 78 65535 0]Where'd that come from!?[n][f 1 3 65535][w][e]

[msg MSG_044_5_0 [Makoto]]
[s][bup 0 6 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 77 65535 0]What!?[n][f 1 3 65535][w][e]

[msg MSG_044_7_0 [Post-Festival MC]]
[s][vp 8 0 0 80 65535 0]Now this is drama! A boy caught[n]in the throes of bittersweet youth![n]A stunning confession of love![n][f 1 3 65535][w][e]

[msg MSG_044_9_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](ヤジ)[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Post-Festival MC]]
[s][vp 8 0 0 50 65535 0]I think it was him![n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Makoto]]
[s][bup 0 6 2 2 0][f 4 10 65535 0 0][vp 8 0 0 73 65535 0]...Urgh![n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Post-Festival MC]]
[s][vp 8 0 0 52 65535 0]Sooo, Miss President! What's your[n]relation to this guy?[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Makoto]]
[s][bup 0 6 7 2 0][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]R-Relation...!?[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Post-Festival MC]]
[s][vp 8 0 0 54 65535 0]My, she's red as a beet![n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](歓声)[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Post-Festival MC]]
[s][vp 8 0 0 55 65535 0]A rare glimpse into the girly side[n]of our stunning Miss President![n][f 1 3 65535][w][e]
[s][vp 8 0 0 56 65535 0]But I'm a gentleman. It hurts my heart[n]to bully such a sweet girl![n][f 1 3 65535][w][e]
[s][vp 8 0 0 57 65535 0]Well, did you all enjoy our[n]blushing beauty? Thank you[n]very much, Miss President![n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](ブーイング)[n][f 1 3 65535][w][e]

