[msg MSG_000_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 2 0 22008 65535 0]So you've come.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]How does it feel slipping into the unusual[n]from your usual life?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Our master has arranged an access point[n]to assist you in coming here directly from[n]the real world.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 2 0 11001 65535 0]That door you just went through is it![n]Be thankful, Inmate![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]This too shall aid in your rehabilitation.[n]Make good use of it.[n][f 1 3 65535][w][e]

