[msg MSG_000_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55501 65535 0]Welcome to the Velvet Room.[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 2 0 0 65535 0]The prison door is open...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55404 65535 0]The state of the Velvet Room reflects[n]the state of your own heart.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]The room's changes reflect your showing[n]the spirit of rebellion to the entity that[n]binds your future.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55506 65535 0]Indeed. Your change in appearance[n]must also be due to the rebellious[n]spirit you've harbored for so long.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]And with that spirit, you appear to have[n]grasped a new possibility as well...[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Possibility?[e]
[s]What do you mean?[e]

[msg MSG_006_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55476 65535 0]The current you should be capable of[n]fusing new Personas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Please make good use of this to keep[n]the ruin at bay.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55505 65535 0]We will continue to provide aid[n]on your perilous journey.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Now, to your business...[n][f 1 3 65535][w][e]

