[msg CMB00_DUMMY]
[s]Ficticio[n][w][e]

[msg CMB00_MSG_001 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5001 0 0]* risada* nao se preocupe. Personas[n]nascem do eu interior...[n][w][e]

[msg CMB00_MSG_002 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5002 0 0]Descartando sua antiga identidade, voce[n]De lugar a um novo. Portanto, nos[n]Chame esse processo de "execucao".[n][w][e]

[msg CMB00_MSG_003 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5003 0 0]Pense nisso como a fusao de suas personas.[n][w][e]

[msg CMB00_MSG_004 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5004 0 0]Agora entao, vamos tentar uma persona real[n]fusao.[n][w][e]

[msg CMB00_MSG_005 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5005 0 0]Para comecar, selecione a primeira persona que voce deseja[n]fundir.[n][w][e]

[msg CMB00_MSG_006 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5006 0 0]Agora antes de selecionar o segundo[n]Persona, permita-me dizer uma coisa[n]muito importante.[n][w][e]

[msg CMB00_MSG_007 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5007 0 0]Voce se lembra de como mencionei[n]formando titulos com confidentes?[n][w][e]

[msg CMB00_MSG_008 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5008 0 0]Personas sao o poder do coracao...[n]Quanto mais fortes esses lacos, mais fortes[n]Suas personas serao.[n][w][e]

[msg CMB00_MSG_015 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5009 0 0]Em outras palavras, os efeitos de seus lacos[n]na execucao... ou fusao, se voce quiser, sao[n]bastante substancial.[n][w][e]

[msg CMB00_MSG_016 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5010 0 0]Quando voce fundem uma persona que compartilha[n]seu arcan com um de seus lacos, e[n]ganhara grande poder.[n][w][e]

[msg CMB00_MSG_017 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5011 0 0]Este sera um principio orientador para o seu[n]A incursoes em fusao... tente nao esquecer.[n][w][e]

[msg CMB00_MSG_018 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5012 0 0]Alem disso, ha uma coisa que devo[n]avisar voce sobre.[n][w][e]

[msg CMB00_MSG_019 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5013 0 0]Voce nao pode criar uma persona que[n]ultrapassa seu nivel atual.[n][w][e]

[msg CMB00_MSG_020 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5014 0 0]Isso ocorre porque a persona resultante[n]seria poderoso demais para voce lidar[n]efetivamente.[n][w][e]

[msg CMB00_MSG_021 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5015 0 0]Agora, entao, verifique os resultados da fusao e[n]Escolha uma persona que se adapte a sua estatura.[n][w][e]

[msg CMB00_MSG_009 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5016 0 0]Esta e a forma que sua nova persona e[n]Espera-se tomar apos a fusao.[n][w][e]

[msg CMB00_MSG_010 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5017 0 0]E possivel que eles herdem habilidades[n]Eles normalmente nao ganhariam.[n][w][e]

[msg CMB00_MSG_011 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Alem disso, cada persona tem inerente[n]Especialidades se separam de suas habilidades.[n][w][e]

[msg CMB00_MSG_012 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5019 0 0]Essas habilidades e especialidades sao distintas[n]um do outro. Habilidades sao caracteristicas que[n]pode ser passado atraves da fusao.[n][w][e]

[msg CMB00_MSG_012_01 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]No entanto, as especialidades inerentes de[n]Uma persona nao pode ser transmitida.[n][w][e]

[msg CMB00_MSG_012_02 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Mas e claro, nao ha necessidade de[n]Pense nisso agora. Para o tempo, selecione[n]o que quiser.[n][w][e]

[msg CMB00_MSG_013 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5048 0 0]O mestre ainda nao terminou! Ouca ele,[n]Preso![n][w][e]

[msg CMB00_MSG_TUTORIAL_ELECT [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Este ritual permite sacrificar personas[n]e transmuta-los em alto nivel[n]Itens.[n][w][e]
[s][f 4 10 65535 0 0]Voce perdera a persona, mas voce[n]Obtenha coisas como armas uteis e[n]acessorios![n][w][e]
[s][f 4 10 65535 0 0]Vamos gravar o resultado da transmutacao[n]de cada persona no registro de presos.[n]E melhor voce ficar agradecido![n][w][e]
[s][f 4 10 65535 0 0]Cada vez que voce faz um sacrificio, voce precisa[n]para usar um material especial com o potencial[n]para transmutacao.[n][w][e]
[s][f 4 10 65535 0 0]Voce provavelmente nao tem ideia do que e,[n]Portanto, pegue este e fique inserido.[n]E melhor voce mostrar sua gratidao por isso![n][w][e]
[s][f 4 10 65535 0 0]Voce deve ser capaz de encontra-los em[n]sua propria realidade tambem 悪 nao apenas o[n]outro. Faca o seu melhor para encontra-los![n][w][e]

[msg CMB00_MSG_TUTORIAL_ELECT_2 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]Este ritual permite que voce sacrifique[n]Personas e transmutando-os[n]em itens de alto nivel.[n][w][e]
[s][f 4 10 65535 0 0]Voce perdera a persona, mas em troca,[n]Voce ganhara itens uteis como armas[n]e acessorios.[n][w][e]
[s][f 4 10 65535 0 0]Vou gravar a transmutacao de cada persona[n]resultar no compendio persona.[n]Espero que isso seja util para voce.[n][w][e]
[s][f 4 10 65535 0 0]Ao oferecer um sacrificio, voce precisara[n]um material especial que tem potencial[n]para transmutacao dentro dela.[n][w][e]
[s][f 4 10 65535 0 0]... eu acredito que ver isso em acao sera mais[n]eficaz do que minha explicacao, entao devo[n]fornecer a voce um agora.[n][w][e]
[s][f 4 10 65535 0 0]Voce deve ser capaz de encontrar isso[n]materiais em ambas as realidades tambem.[n]Talvez voce deva ficar de olho?[n][w][e]

[msg CMB00_MSG_CELL_001 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Voce pode jogar uma de suas personas em[n]uma celula e nos daremos um pouco "especial[n]atencao "para ajuda-lo a crescer![n][w][e]
[s][f 4 10 65535 0 0]Voce so pode trancar uma persona[n]de cada vez, no entanto.[n][w][e]
[s][f 4 10 65535 0 0]E, enquanto estiver trancado, voce nao vai[n]ser capaz de usa-lo em batalha ou fusoes.[n]Se voce esquecer isso, esta tudo em voce![n][w][e]
[s][f 4 10 65535 0 0]A medida que os dias passam, sua persona vai crescer[n]mais forte e aprenda uma nova resistencia.[n][w][e]
[s][f 4 10 65535 0 0]Isso nao e tudo 悪 se voce se certificar de[n]queimar um pouco de incenso, a persona ira[n]cresca ainda mais![n][w][e]
[s][f 4 10 65535 0 0]Se voce quiser mais detalhes do que isso, voce[n]tem que perguntar mais tarde. Por enquanto, pegue uma persona[n]em bloqueio![n][w][e]

[msg CMB00_MSG_CELL_001_001 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Oh Ho! Eu nao sei onde voce conseguiu isso[n]incenso, mas voce deve usa-lo com[n]Esta persona![n][w][e]
[s][f 4 10 65535 0 0]Tudo bem, escolha uma persona para travar, entao[n]Queime o incenso! Voce vera os efeitos[n]Amanha o mais cedo possivel![n][w][e]

[msg CMB00_MSG_CELL_001_002 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]O que, voce nao tem nenhum incenso do seu[n]ter!?... tudo bem, eu vou te dar este, mas[n]e isso! Nao ha mais brindes depois disso![n][w][e]
[s][f 4 10 65535 0 0]Agora, escolha uma persona para travar, entao[n]Queime o incenso! Voce vera os efeitos[n]em apenas alguns dias![n][w][e]

[msg CMB00_MSG_CELL_001_L [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]Voce pode trancar uma de suas personas[n]em uma celula onde ela passara[n]treinamento especial para ajuda-lo a crescer.[n][w][e]
[s][f 4 10 65535 0 0]No entanto, voce so pode trancar[n]uma persona de cada vez.[n][w][e]
[s][f 4 10 65535 0 0]Observe que a persona sera[n]indisponivel para batalha ou fusoes enquanto[n]esta trancado.[n][w][e]
[s][f 4 10 65535 0 0]A medida que os dias passam, sua persona vai crescer[n]mais forte e aprenda uma nova resistencia.[n][w][e]
[s][f 4 10 65535 0 0]Nao apenas isso, mas voce pode aumentar o[n]taxa de crescimento por incenso.[n][w][e]
[s][f 4 10 65535 0 0]Se voce deseja saber mais, por favor pergunte[n]Mais tarde. Por enquanto, tente colocar[n]uma persona em bloqueio.[n][w][e]

[msg CMB00_MSG_CELL_001_001_L [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]... parece que voce ja esta em posse[n]de incenso.[n][w][e]
[s][f 4 10 65535 0 0]Por favor, bloqueie uma persona e depois queime[n]o incenso. Voce vera os efeitos[n]Depois de passar tempo suficiente.[n][w][e]

[msg CMB00_MSG_CELL_001_002_L [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]... parece que voce ainda nao tem nenhum[n]incenso. Nesse caso, vou fornecer[n]Voce com alguns 悪 apenas uma vez.[n][w][e]
[s][f 4 10 65535 0 0]Trancar a persona e depois queimar o[n]incenso. Voce deve poder ver[n]Os efeitos apos tempo suficientes passam.[n][w][e]

[msg CMB00_MSG_CELL_002 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Tudo bem, com isso feito, tudo o que voce precisa fazer[n]agora e esperar. Mas nao deixe isso em paz para[n]demasiado longo![n][w][e]
[s][f 4 10 65535 0 0]A persona faz parte do seu coracao.[n]Se ficar longe de voce por muito tempo,[n]pode desaparecer.[n][w][e]
[s][f 4 10 65535 0 0]Nos te daremos um unico aviso antes[n]Acontece, mas depois disso, e inteiramente[n]em voce.[n][w][e]

[msg CMB00_MSG_CELL_002_L [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]E agora, voce deve esperar ate o treinamento[n]esta concluido 悪 no entanto, e perigoso[n]Para deixar a persona por muito tempo.[n][w][e]
[s][f 4 10 65535 0 0]Uma persona ainda faz parte do seu coracao...[n]Se voce esta separado por muito tempo,[n]Pode muito bem desaparecer.[n][w][e]
[s][f 4 10 65535 0 0]Vou te dar um unico aviso antes dele[n]desaparece. Voce deve nao agir,[n]Voce deve se preparar para as consequencias...[n][w][e]

[sel CMB00_SEL_WARNING_ACC top]
[s]Continue.[e]
[s]Eu melhor nao.[e]

[msg CMB00_MSG_WARNING_ACC_00 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0]O equipamento ficou instavel![n]Cuidado com acidentes![n][w][e]
[s][f 4 10 65535 0 0]Nao podemos garantir que os resultados sao[n]vai ser o que voce esta esperando.[n]Voce ainda quer continuar?[n][w][e]

[msg CMB00_MSG_WARNING_ACC_01 [Caroline]]
[s][bup 0 102 4 0 0][f 4 10 65535 0 0]Quaisquer execucoes seriam bastante arriscadas[n]no momento...[n][w][e]
[s][f 4 10 65535 0 0]Nao podemos garantir que os resultados serao[n]O que voce esta esperando. Voce ainda quer[n]continue?[n][w][e]

[msg CMB00_MSG_WARNING_ACC_YE [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Certo! O alarme fica ligado![n][w][e]

[msg CMB00_MSG_WARNING_ACC_NO [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Hmph... tudo bem, vamos desligar o alarme.[n]Mas nao relaxe na sua reabilitacao,[n]Preso![n][w][e]

[msg CMB00_MSG_WARNING_ACC_00_2 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]O equipamento se tornou instavel.[n]Por favor, cuidado com os acidentes.[n][w][e]
[s][f 4 10 65535 0 0]Nao posso garantir que os resultados serao[n]O que voce esperava. Voce ainda vai continuar?[n][w][e]

[msg CMB00_MSG_WARNING_ACC_01_2 [Lavenza]]
[s][bup 0 100 4 0 0][f 4 10 65535 0 0]Ha um grande risco de realizar qualquer[n]execucoes no momento...[n][w][e]
[s][f 4 10 65535 0 0]Nao posso garantir que os resultados serao[n]O que voce esperava. Voce ainda vai continuar?[n][w][e]

[msg CMB00_MSG_WARNING_ACC_YE_2 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]Muito bem, vou deixar o alarme continuar.[n][w][e]

[msg CMB00_MSG_WARNING_ACC_NO_2 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]Muito bem, vou terminar o alarme. No entanto,[n]Peco que voce continue trabalhando duro[n]em direcao a sua reabilitacao.[n][w][e]

