[msg msg_cbs_mode_help_000]
[s]Em branco[n]Em branco[n]Em branco[n][e]

[msg msg_cbs_mode_help_001]
[s]Um modo de nivel basico que testa o combate[n]fundamentos, incluindo fraquezas impressionantes,[n]suporta, e passando bastao.[n][e]

[msg msg_cbs_mode_help_002]
[s]Um modo em que voce identifica o inimigo[n]Fraquezas e passes de bastao de corrente[n]para obter uma pontuacao alta.[n][e]

[msg msg_cbs_mode_help_003]
[s]Um modo avancado no qual voce busca[n]uma pontuacao alta aplicando doencas de status[n]e pontuacao de sucessos tecnicos.[n][e]

[msg msg_cbs_mode_help_004]
[s]Um modo de especialista no qual voce busca[n]uma pontuacao alta ao sobreviver e duradouro[n]os ataques ferozes do inimigo.[n][e]

[msg msg_cbs_mode_help_005]
[s]Um modo que testara os mestres de todos[n]elementos de combate, incluindo ataques,[n]guardando e apoiando.[n][e]

[msg msg_cbs_mode_help_006]
[s]Uma batalha especial contra o eco cognitivo[n]de um certo usuario de persona que lutou[n]para impedir a queda da humanidade.[n][e]

[msg msg_cbs_mode_help_007]
[s]Uma batalha especial contra o eco cognitivo[n]de um certo usuario de persona que dissipou[n]um nevoeiro estranho e sobrenatural.[n][e]

[msg msg_cbs_not_open_sys_mes]
[s]Voce pode tentar este desafio[n]comprando o conteudo em[n]the PlayStation渥Store.[n][w][e]

[msg msg_cbs_confirm_message [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Voce esta comecando esta batalha?[n][w][e]

[msg msg_cbs_confirm_message_ [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]Voce vai comecar esta batalha?[n][w][e]

[sel msg_cbs_confirm_select top]
[s]Sim.[e]
[s]Nao.[e]

[msg msg_cbs_devil_message_00 [Lavenza]]
[s]Hee-ho![n][w][e]

[msg msg_cbs_devil_message_00_2 [Lavenza]]
[s]Kill-ho![n][w][e]

[msg msg_cbs_devil_message_00_3 [Lavenza]]
[s]... ele![n][w][e]

[msg msg_cbs_devil_message_00_4 [Lavenza]]
[s]Ho![n][w][e]

[msg msg_cbs_devil_message_00_5 [Lavenza]]
[s]Brutalidade-ho![n][w][e]

[msg msg_cbs_devil_message_00_6 [Lavenza]]
[s]EU...[n][w][e]

[msg msg_cbs_devil_message_00_7 [Lavenza]]
[s]COMER...[n][w][e]

[msg msg_cbs_devil_message_00_8 [Lavenza]]
[s]... voce esta inteiro![n][w][e]

[msg msg_cbs_devil_message_00_9 [Lavenza]]
[s]EU...[n][w][e]

[msg msg_cbs_devil_message_00_10 [Lavenza]]
[s]O mesmo que voce![n][w][e]

[msg msg_cbs_devil_message_00_11 [Lavenza]]
[s]Matar...[n][w][e]

[msg msg_cbs_devil_message_00_12 [Lavenza]]
[s]MATAR![n][w][e]

[msg msg_cbs_devil_message_00_13 [Lavenza]]
[s]Sonolento...[n][w][e]

[msg msg_cbs_devil_message_00_14 [Lavenza]]
[s]Pressa...[n][w][e]

[msg msg_cbs_devil_message_00_15 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_16 [Lavenza]]
[s]Qualquer que seja...[n][w][e]

[msg msg_cbs_devil_message_00_17 [Lavenza]]
[s]Voce vai morrer por mim?[n][w][e]

[msg msg_cbs_devil_message_00_18 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_19 [Lavenza]]
[s]Sem espaco aqui...[n][w][e]

[msg msg_cbs_devil_message_00_20 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_21 [Lavenza]]
[s]Voce se importaria...[n][w][e]

[msg msg_cbs_devil_message_00_22 [Lavenza]]
[s]... morrendo para mim!?[n][w][e]

[msg msg_cbs_devil_message_00_23 [Lavenza]]
[s]Isto e tao...[n][w][e]

[msg msg_cbs_devil_message_00_24 [Lavenza]]
[s]... apertado...[n][w][e]

[msg msg_cbs_devil_message_00_25 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_26 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_27 [Lavenza]]
[s]Onde estou...?[n][w][e]

[msg msg_cbs_devil_message_00_28 [Lavenza]]
[s]Proxima lua cheia...[n][w][e]

[msg msg_cbs_devil_message_00_29 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_30 [Lavenza]]
[s]Eu nao me importo...[n][w][e]

[msg msg_cbs_devil_message_00_31 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_32 [Lavenza]]
[s]Onde estou...?[n][w][e]

[msg msg_cbs_devil_message_00_33 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_34 [Lavenza]]
[s]......[n][w][e]

[msg msg_cbs_devil_message_00_35 [Lavenza]]
[s]O nevoeiro esta chegando...[n][w][e]

[msg msg_cbs_lock_sys_message]
[s]Essa batalha ainda nao foi desbloqueada.[n][w][e]

[msg msg_cbs_unlock_trial_2_s]
[s]Uma nova dificuldade de batalha de julgamento[n]foi desbloqueado.[n][w][e]

[msg msg_cbs_unlock_trial_3_s]
[s]Uma nova dificuldade de batalha de julgamento[n]foi desbloqueado.[n][w][e]

[msg msg_cbs_unlock_trial_4_s]
[s]Uma nova dificuldade de batalha de julgamento[n]foi desbloqueado.[n][w][e]

[msg msg_cbs_unlock_trial_5_s]
[s]Uma nova dificuldade de batalha de julgamento[n]foi desbloqueado.[n][w][e]

[msg msg_cbs_unlock_chain_sys]
[s]Um novo modo foi desbloqueado[n]Para batalhas de desafio: cadeia.[n][w][e]

[msg msg_cbs_unlock_technical]
[s]Um novo modo foi desbloqueado[n]Para batalhas de desafio: tecnico.[n][w][e]

[msg msg_cbs_unlock_suvival_s]
[s]Um novo modo foi desbloqueado[n]Para batalhas de desafio: sobrevivencia.[n][w][e]

[msg msg_cbs_unlock_trickster]
[s]Um novo modo foi desbloqueado[n]Para batalhas de desafio: Trickster.[n][w][e]

[msg msg_cbs_unlock_p3_sys_me]
[s]Um novo modo foi desbloqueado[n]Para batalhas de desafio: lua cheia.[n][w][e]

[msg msg_cbs_unlock_p4_sys_me]
[s]Um novo modo foi desbloqueado[n]Para batalhas de desafio: Foggy Day.[n][w][e]

[msg msg_cbs_unlock_p3_hard_s]
[s]Uma nova dificuldade foi desbloqueada[n]para lua cheia.[n][w][e]

[msg msg_cbs_unlock_p4_hard_s]
[s]Uma nova dificuldade foi desbloqueada[n]para o dia de neblina.[n][w][e]

[msg msg_cbs_unlock_new_mode_]
[s]Um novo modo foi desbloqueado[n]Para batalhas de desafio.[n][w][e]

