[msg jyokyohelp_BLANK_PLAYER]
[s][f 0 4 128]Não usado[n][e]

[msg jyokyohelp_BLANK_ENEMY]
[s][f 0 4 128]Não usado[n][e]

[msg jyokyohelp_BATK_MATK_RES]
[s][f 0 4 128]Ataque restaurado![n][e]

[msg jyokyohelp_BATK_MATK_RES_2]
[s][f 0 4 128]Ataque restaurado![n][e]

[msg jyokyohelp_HIT_ESC_RESET]
[s][f 0 4 128]Precisão e evasão restauradas![n][e]

[msg jyokyohelp_HIT_ESC_RESET_2]
[s][f 0 4 128]Precisão e evasão restauradas![n][e]

[msg jyokyohelp_DEF_RESET_PLA]
[s][f 0 4 128]Defesa restaurada![n][e]

[msg jyokyohelp_DEF_RESET_ENE]
[s][f 0 4 128]Defesa restaurada![n][e]

[msg jyokyohelp_HIRISK_RESET_]
[s][f 0 4 128]Chance crítica restaurada![n][e]

[msg jyokyohelp_HIRISK_RESET__2]
[s][f 0 4 128]Chance crítica restaurada![n][e]

[msg jyokyohelp_RISKHG_RESET_]
[s][f 0 4 128]Chance crítica restaurada![n][e]

[msg jyokyohelp_RISKHG_RESET__2]
[s][f 0 4 128]Chance crítica restaurada![n][e]

[msg jyokyohelp_BADx2_RESET_P]
[s][f 0 4 128]Prontidão acidental restaurada![n][e]

[msg jyokyohelp_BADx2_RESET_E]
[s][f 0 4 128]Prontidão acidental restaurada![n][e]

[msg jyokyohelp_AGINDA_RESET_]
[s][f 0 4 128]Afinidade de fogo restaurada![n][e]

[msg jyokyohelp_AGINDA_RESET__2]
[s][f 0 4 128]Afinidade de fogo restaurada![n][e]

[msg jyokyohelp_BUFNDA_RESET_]
[s][f 0 4 128]Afinidade de Gelo Restaurada![n][e]

[msg jyokyohelp_BUFNDA_RESET__2]
[s][f 0 4 128]Afinidade de Gelo Restaurada![n][e]

[msg jyokyohelp_GALNDA_RESET_]
[s][f 0 4 128]Afinidade do vento restaurada![n][e]

[msg jyokyohelp_GALNDA_RESET__2]
[s][f 0 4 128]Afinidade do vento restaurada![n][e]

[msg jyokyohelp_JIONDA_RESET_]
[s][f 0 4 128]Afinidade de eletricidade restaurada![n][e]

[msg jyokyohelp_JIONDA_RESET__2]
[s][f 0 4 128]Afinidade de eletricidade restaurada![n][e]

[msg jyokyohelp_REDWALL_F_PLA]
[s][f 0 4 128]Resistência ao fogo restaurada...[n][e]

[msg jyokyohelp_REDWALL_F_ENE]
[s][f 0 4 128]Resistência ao fogo restaurada...[n][e]

[msg jyokyohelp_WHITEWALL_F_P]
[s][f 0 4 128]Resistência ao gelo restaurada...[n][e]

[msg jyokyohelp_WHITEWALL_F_E]
[s][f 0 4 128]Resistência ao gelo restaurada...[n][e]

[msg jyokyohelp_BLUEWALL_F_PL]
[s][f 0 4 128]Resistência à eletricidade restaurada...[n][e]

[msg jyokyohelp_BLUEWALL_F_EN]
[s][f 0 4 128]Resistência à eletricidade restaurada...[n][e]

[msg jyokyohelp_GREENWALL_F_P]
[s][f 0 4 128]Resistência ao vento restaurada...[n][e]

[msg jyokyohelp_GREENWALL_F_E]
[s][f 0 4 128]Resistência ao vento restaurada...[n][e]

[msg jyokyohelp_BAD_ATTACK_PL]
[s][f 0 4 128][var 0]surtar![n][e]

[msg jyokyohelp_BAD_ATTACK_EN]
[s][f 0 4 128][var 0]surtar![n][e]

[msg jyokyohelp_BAD_SKIP_PLAY]
[s][f 0 4 128]Ele não pode se mover por causa das alterações![n][e]

[msg jyokyohelp_BAD_SKIP_ENEM]
[s][f 0 4 128]Ele não pode se mover por causa das alterações![n][e]

[msg jyokyohelp_BAD_GEKIDO_PL]
[s][f 0 4 128][var 0]ele está furioso![n][e]

[msg jyokyohelp_BAD_GEKIDO_EN]
[s][f 0 4 128][var 0]ele está furioso![n][e]

[msg jyokyohelp_HP_PLAYER]
[s][f 0 4 128]HP insuficiente![n][e]

[msg jyokyohelp_HP_ENEMY]
[s][f 0 4 128]HP insuficiente![n][e]

[msg jyokyohelp_SP_PLAYER]
[s][f 0 4 128]SP insuficiente![n][e]

[msg jyokyohelp_SP_ENEMY]
[s][f 0 4 128]SP insuficiente![n][e]

[msg jyokyohelp_UNUSABLE_SKIL]
[s][f 0 4 128]Ele não se lembra de como usar habilidades![n][e]

[msg jyokyohelp_UNUSABLE_SKIL_2]
[s][f 0 4 128]Ele não se lembra de como usar habilidades![n][e]

[msg jyokyohelp_ESCAPE_PLAYER]
[s][f 0 4 128]bug 04[n][e]

[msg jyokyohelp_ESCAPE_ENEMY]
[s][f 0 4 128][var 0]foge...[n][e]

[msg jyokyohelp_BATK_MATK_SET]
[s][f 0 4 128]Ataque aumentado![n][e]

[msg jyokyohelp_BATK_MATK_SET_2]
[s][f 0 4 128]Ataque Aumentado![n][e]

[msg jyokyohelp_HIT_ESC_SET_P]
[s][f 0 4 128]Maior precisão e evasão![n][e]

[msg jyokyohelp_HIT_ESC_SET_E]
[s][f 0 4 128]Maior precisão e evasão![n][e]

[msg jyokyohelp_DEF_SET_PLAYE]
[s][f 0 4 128]Defesa aumentada![n][e]

[msg jyokyohelp_DEF_SET_ENEMY]
[s][f 0 4 128]Defesa aumentada![n][e]

[msg jyokyohelp_ENG_SET_PLAYE]
[s][f 0 4 128]ATK/DEF/Precisão/Evasão aumentada![n][e]

[msg jyokyohelp_ENG_SET_ENEMY]
[s][f 0 4 128]ATK/DEF/Precisão/Evasão aumentada![n][e]

[msg jyokyohelp_RND_SET_PLAYE]
[s][f 0 4 128]ATK/DEF/Precisão/Evasão reduzidos![n][e]

[msg jyokyohelp_RND_SET_ENEMY]
[s][f 0 4 128]ATK/DEF/Precisão/Evasão reduzidos![n][e]

[msg jyokyohelp_HIRISK_SET_PL]
[s][f 0 4 128]Maior chance crítica![n][e]

[msg jyokyohelp_HIRISK_SET_EN]
[s][f 0 4 128]Maior chance crítica![n][e]

[msg jyokyohelp_RISKHG_SET_PL]
[s][f 0 4 128]A chance crítica aumentou muito![n][e]

[msg jyokyohelp_RISKHG_SET_EN]
[s][f 0 4 128]A chance crítica aumentou muito![n][e]

[msg jyokyohelp_BADx2_SET_PLA]
[s][f 0 4 128]Prontidão acidental aumentada![n][e]

[msg jyokyohelp_BADx2_SET_ENE]
[s][f 0 4 128]Prontidão acidental aumentada![n][e]

[msg jyokyohelp_BATK_MATK_DOW]
[s][f 0 4 128]Ataque diminuído![n][e]

[msg jyokyohelp_BATK_MATK_DOW_2]
[s][f 0 4 128]Ataque diminuído![n][e]

[msg jyokyohelp_HIT_ESC_DOWN_]
[s][f 0 4 128]Precisão e evasão diminuídas![n][e]

[msg jyokyohelp_HIT_ESC_DOWN__2]
[s][f 0 4 128]Precisão e evasão diminuídas![n][e]

[msg jyokyohelp_DEF_DOWN_SET_]
[s][f 0 4 128]Defesa baixa![n][e]

[msg jyokyohelp_DEF_DOWN_SET__2]
[s][f 0 4 128]Defesa baixa![n][e]

[msg jyokyohelp_DEKAJA_PLAYER]
[s][f 0 4 128]Bônus de estatísticas. cancelado![n][e]

[msg jyokyohelp_DEKAJA_ENEMY]
[s][f 0 4 128]Bônus de estatísticas. cancelado![n][e]

[msg jyokyohelp_DEKUNDA_PLAYE]
[s][f 0 4 128]Penalidades de estatísticas canceladas![n][e]

[msg jyokyohelp_DEKUNDA_ENEMY]
[s][f 0 4 128]Penalidades de estatísticas canceladas![n][e]

[msg jyokyohelp_POWERCHARGE_P]
[s][f 0 4 128][var 0] carrega![n][e]

[msg jyokyohelp_POWERCHARGE_E]
[s][f 0 4 128][var 0] carrega![n][e]

[msg jyokyohelp_MINDCHARGE_PL]
[s][f 0 4 128][var 0]foca![n][e]

[msg jyokyohelp_MINDCHARGE_EN]
[s][f 0 4 128][var 0]foca![n][e]

[msg jyokyohelp_K_AGINDA2_PLA]
[s][f 0 4 128]Resistência ao fogo cancelada![n][e]

[msg jyokyohelp_K_AGINDA2_ENE]
[s][f 0 4 128]Resistência ao fogo cancelada![n][e]

[msg jyokyohelp_K_BUFUNDA2_PL]
[s][f 0 4 128]Resistência ao gelo cancelada![n][e]

[msg jyokyohelp_K_BUFUNDA2_EN]
[s][f 0 4 128]Resistência ao gelo cancelada![n][e]

[msg jyokyohelp_K_JIONDA2_PLA]
[s][f 0 4 128]Resistência à eletricidade anulada![n][e]

[msg jyokyohelp_K_JIONDA2_ENE]
[s][f 0 4 128]Resistência à eletricidade anulada![n][e]

[msg jyokyohelp_K_GARUNDA2_PL]
[s][f 0 4 128]Resistência ao vento cancelada![n][e]

[msg jyokyohelp_K_GARUNDA2_EN]
[s][f 0 4 128]Resistência ao vento cancelada![n][e]

[msg jyokyohelp_OKANE_PLAYER]
[s][f 0 4 128]Ele jogou fora [var 1] ienes![n][e]

[msg jyokyohelp_OKANE_ENEMY]
[s][f 0 4 128]Ele jogou fora [var 1] ienes![n][e]

[msg jyokyohelp_TETORABLAKE_P]
[s][f 0 4 128]Tetrakarn cancelado![n][e]

[msg jyokyohelp_TETORABLAKE_E]
[s][f 0 4 128]Tetrakarn cancelado![n][e]

[msg jyokyohelp_MAKARABLAKE_P]
[s][f 0 4 128]Makarakarn cancelado![n][e]

[msg jyokyohelp_MAKARABLAKE_E]
[s][f 0 4 128]Makarakarn cancelado![n][e]

[msg jyokyohelp_TETORAJA_PLAY]
[s][f 0 4 128]Tetraja ativado![n][e]

[msg jyokyohelp_TETORAJA_ENEM]
[s][f 0 4 128]Tetraja ativado![n][e]

[msg jyokyohelp_REDWALL_PLAYE]
[s][f 0 4 128]Maior resistência ao fogo![n][e]

[msg jyokyohelp_REDWALL_ENEMY]
[s][f 0 4 128]Maior resistência ao fogo![n][e]

[msg jyokyohelp_WHITEWALL_PLA]
[s][f 0 4 128]Resistência ao gelo aumentada![n][e]

[msg jyokyohelp_WHITEWALL_ENE]
[s][f 0 4 128]Resistência ao gelo aumentada![n][e]

[msg jyokyohelp_BLUEWALL_PLAY]
[s][f 0 4 128]Resistência à eletricidade aumentada![n][e]

[msg jyokyohelp_BLUEWALL_ENEM]
[s][f 0 4 128]Resistência à eletricidade aumentada![n][e]

[msg jyokyohelp_GREENWALL_PLA]
[s][f 0 4 128]Maior resistência ao vento![n][e]

[msg jyokyohelp_GREENWALL_ENE]
[s][f 0 4 128]Maior resistência ao vento![n][e]

[msg jyokyohelp_TETRKN_PLAYER]
[s][f 0 4 128]Barreira física levantada![n][e]

[msg jyokyohelp_TETRKN_ENEMY]
[s][f 0 4 128]Barreira física levantada![n][e]

[msg jyokyohelp_MAKRKN_PLAYER]
[s][f 0 4 128]Barreira mágica levantada![n][e]

[msg jyokyohelp_MAKRKN_ENEMY]
[s][f 0 4 128]Barreira mágica levantada![n][e]

[msg jyokyohelp_TTRJYA_PLAYER]
[s][f 0 4 128]Barreira erguida contra pássaros instantâneos![n][e]

[msg jyokyohelp_TTRJYA_ENEMY]
[s][f 0 4 128]Barreira erguida contra pássaros instantâneos![n][e]

[msg jyokyohelp_BATK_MATK_ADD]
[s][f 0 4 128]Bônus de ataque estendido![n][e]

[msg jyokyohelp_BATK_MATK_ADD_2]
[s][f 0 4 128]Bônus de ataque estendido![n][e]

[msg jyokyohelp_HIT_ESC_ADD_P]
[s][f 0 4 128]Bônus de Precisão/Evasão Estendidos![n][e]

[msg jyokyohelp_HIT_ESC_ADD_E]
[s][f 0 4 128]Bônus de Precisão/Evasão Estendidos![n][e]

[msg jyokyohelp_DEF_ADD_PLAYE]
[s][f 0 4 128]Bônus de defesa estendido![n][e]

[msg jyokyohelp_DEF_ADD_ENEMY]
[s][f 0 4 128]Bônus de defesa estendido![n][e]

[msg jyokyohelp_BATK_MATK_DOW_3]
[s][f 0 4 128]Penalidade de ataque estendida![n][e]

[msg jyokyohelp_BATK_MATK_DOW_4]
[s][f 0 4 128]Penalidade de ataque estendida![n][e]

[msg jyokyohelp_HIT_ESC_DOWN__3]
[s][f 0 4 128]Redução de Precisão/Evasão Expandida![n][e]

[msg jyokyohelp_HIT_ESC_DOWN__4]
[s][f 0 4 128]Redução de Precisão/Evasão Expandida![n][e]

[msg jyokyohelp_DEF_DOWN_ADD_]
[s][f 0 4 128]Penalidade de defesa estendida![n][e]

[msg jyokyohelp_DEF_DOWN_ADD__2]
[s][f 0 4 128]Penalidade de defesa estendida![n][e]

[msg jyokyohelp_RND_ADD_PLAYE]
[s][f 0 4 128]Penalidades estatísticas estendidas![n][e]

[msg jyokyohelp_RND_ADD_ENEMY]
[s][f 0 4 128]Penalidades estatísticas estendidas![n][e]

[msg jyokyohelp_REDWALL_ADD_P]
[s][f 0 4 128]Maior resistência ao fogo![n][e]

[msg jyokyohelp_REDWALL_ADD_E]
[s][f 0 4 128]Maior resistência ao fogo![n][e]

[msg jyokyohelp_WHITEWALL_ADD]
[s][f 0 4 128]Resistência ao Gelo Estendida![n][e]

[msg jyokyohelp_WHITEWALL_ADD_2]
[s][f 0 4 128]Resistência ao Gelo Estendida![n][e]

[msg jyokyohelp_BLUEWALL_ADD_]
[s][f 0 4 128]Resistência de eletricidade estendida![n][e]

[msg jyokyohelp_BLUEWALL_ADD__2]
[s][f 0 4 128]Resistência de eletricidade estendida![n][e]

[msg jyokyohelp_GREENWALL_ADD]
[s][f 0 4 128]Maior resistência ao vento![n][e]

[msg jyokyohelp_GREENWALL_ADD_2]
[s][f 0 4 128]Maior resistência ao vento![n][e]

[msg jyokyohelp_K_AGINDA2_ADD]
[s][f 0 4 128]Vulnerabilidade de fogo estendida![n][e]

[msg jyokyohelp_K_AGINDA2_ADD_2]
[s][f 0 4 128]Vulnerabilidade de fogo estendida![n][e]

[msg jyokyohelp_K_BUFUNDA2_AD]
[s][f 0 4 128]Vulnerabilidade estendida ao gelo![n][e]

[msg jyokyohelp_K_BUFUNDA2_AD_2]
[s][f 0 4 128]Vulnerabilidade estendida ao gelo![n][e]

[msg jyokyohelp_K_JIONDA2_ADD]
[s][f 0 4 128]Vulnerabilidade estendida à eletricidade![n][e]

[msg jyokyohelp_K_JIONDA2_ADD_2]
[s][f 0 4 128]Vulnerabilidade estendida à eletricidade![n][e]

[msg jyokyohelp_K_GARUNDA2_AD]
[s][f 0 4 128]Vulnerabilidade ao vento estendida![n][e]

[msg jyokyohelp_K_GARUNDA2_AD_2]
[s][f 0 4 128]Vulnerabilidade ao vento estendida![n][e]

[msg jyokyohelp_SET_BAD_ENZYO]
[s][f 0 4 128]está pegando fogo...[n][e]

[msg jyokyohelp_SET_BAD_ENZYO_2]
[s][f 0 4 128]Está pegando fogo![n][e]

[msg jyokyohelp_SET_BAD_TOUKE]
[s][f 0 4 128]Termina abaixo de zero...[n][e]

[msg jyokyohelp_SET_BAD_TOUKE_2]
[s][f 0 4 128]Termina abaixo de zero![n][e]

[msg jyokyohelp_SET_BAD_KANDE]
[s][f 0 4 128]Fique chocado...[n][e]

[msg jyokyohelp_SET_BAD_KANDE_2]
[s][f 0 4 128]Fique chocado![n][e]

[msg jyokyohelp_SET_BAD_MEMAI]
[s][f 0 4 128]Você está tonto...[n][e]

[msg jyokyohelp_SET_BAD_MEMAI_2]
[s][f 0 4 128]Você está tonto![n][e]

[msg jyokyohelp_SET_BAD_PANIC]
[s][f 0 4 128]Fica confuso...[n][e]

[msg jyokyohelp_SET_BAD_PANIC_2]
[s][f 0 4 128]Ficar confuso![n][e]

[msg jyokyohelp_SET_BAD_KYOUH]
[s][f 0 4 128]Tremendo de medo...[n][e]

[msg jyokyohelp_SET_BAD_KYOUH_2]
[s][f 0 4 128]Treme de medo![n][e]

[msg jyokyohelp_SET_BAD_BOUKY]
[s][f 0 4 128]Ele não se lembra mais de nada...[n][e]

[msg jyokyohelp_SET_BAD_BOUKY_2]
[s][f 0 4 128]Ele não se lembra mais de nada![n][e]

[msg jyokyohelp_SET_BAD_KUUHU]
[s][f 0 4 128]Ele está morrendo de fome...[n][e]

[msg jyokyohelp_SET_BAD_KUUHU_2]
[s][f 0 4 128]Ele está morrendo de fome![n][e]

[msg jyokyohelp_SET_BAD_SUIMI]
[s][f 0 4 128]É no mundo dos sonhos...[n][e]

[msg jyokyohelp_SET_BAD_SUIMI_2]
[s][f 0 4 128]É na terra dos sonhos![n][e]

[msg jyokyohelp_SET_BAD_GEKID]
[s][f 0 4 128]Ele sai em disparada…[n][e]

[msg jyokyohelp_SET_BAD_GEKID_2]
[s][f 0 4 128]Ir em um tumulto![n][e]

[msg jyokyohelp_SET_BAD_ZETUB]
[s][f 0 4 128]Perder a esperança...[n][e]

[msg jyokyohelp_SET_BAD_ZETUB_2]
[s][f 0 4 128]Perder a esperança![n][e]

[msg jyokyohelp_SET_BAD_SENNO]
[s][f 0 4 128]Ele não é mais ele mesmo...[n][e]

[msg jyokyohelp_SET_BAD_SENNO_2]
[s][f 0 4 128]Não é mais ele mesmo![n][e]

[msg jyokyohelp_SET_BAD_MOUSE]
[s][f 0 4 128]Torne-se um rato...[n][e]

[msg jyokyohelp_SET_BAD_MOUSE_2]
[s][f 0 4 128]Torne-se um rato![n][e]

[msg jyokyohelp_BAD_ESCAPE_PL]
[s][f 0 4 128][var 0]se aposenta![n][e]

[msg jyokyohelp_BAD_ESCAPE_EN]
[s][f 0 4 128][var 0]se aposenta![n][e]

[msg jyokyohelp_BOSS_01_LOOK_]
[s][f 0 4 128]Kamoshida está olhando para Ann...[n][e]

[msg jyokyohelp_BOSS_01_LOOK__2]
[s][f 0 4 128]Kamoshida está encarando Ryuji...[n][e]

[msg jyokyohelp_BOSS_01_HP_LA]
[s][f 0 4 128]O Tesouro impede que ele entre em colapso![n][e]

[msg jyokyohelp_BOSS_04_not_f]
[s][f 0 4 128]Wakaba Isshiki gemidos cognitivos...[n][e]

[msg jyokyohelp_FLANDA_RESET_]
[s][f 0 4 128]Afinidade nuclear restaurada![n][e]

[msg jyokyohelp_FLANDA_RESET__2]
[s][f 0 4 128]Afinidade nuclear restaurada![n][e]

[msg jyokyohelp_PSYNDA_RESET_]
[s][f 0 4 128]Afinidade com PK restaurada![n][e]

[msg jyokyohelp_PSYNDA_RESET__2]
[s][f 0 4 128]Afinidade com PK restaurada![n][e]

[msg jyokyohelp_FLAWALL_F_PLA]
[s][f 0 4 128]Resistência nuclear restabelecida...[n][e]

[msg jyokyohelp_FLAWALL_F_ENE]
[s][f 0 4 128]Resistência nuclear restabelecida...[n][e]

[msg jyokyohelp_PSYWALL_F_PLA]
[s][f 0 4 128]Resistência PK restaurada...[n][e]

[msg jyokyohelp_PSYWALL_F_ENE]
[s][f 0 4 128]Resistência PK restaurada...[n][e]

[msg jyokyohelp_KUISIB_PLAYER]
[s][f 0 4 128]Ele resistiu ao ataque![n][e]

[msg jyokyohelp_KUISIB_ENEMY]
[s][f 0 4 128]Ele resistiu ao ataque![n][e]

[msg jyokyohelp_FUKUTU_PLAYER]
[s][f 0 4 128]Sobreviva e recupere HP![n][e]

[msg jyokyohelp_FUKUTU_ENEMY]
[s][f 0 4 128]Sobreviva e recupere HP![n][e]

[msg jyokyohelp_WAIT_MAGIC_CH]
[s][f 0 4 128]Ele está acumulando poder mágico...[n][e]

[msg jyokyohelp_BOSS_02_not_m]
[s][f 0 4 128]A Sombra de Madarame geme...[n][e]

[msg jyokyohelp_BOSS_02_notmo]
[s][f 0 4 128]O olho direito está imóvel![n][e]

[msg jyokyohelp_BOSS_02_notmo_2]
[s][f 0 4 128]O olho esquerdo está imóvel![n][e]

[msg jyokyohelp_BOSS_02_notmo_3]
[s][f 0 4 128]O nariz está parado![n][e]

[msg jyokyohelp_BOSS_02_notmo_4]
[s][f 0 4 128]A boca está imóvel![n][e]

[msg jyokyohelp_SET_BAD_NURIT]
[s][f 0 4 128]Ele tomou um banho de tinta...[n][e]

[msg jyokyohelp_COMP_D1_LAY_1]
[s][f 0 4 128]Ele não pode atacar por causa do refém![n][e]

[msg jyokyohelp_BOSS_01_USE_S]
[s][f 0 4 128]Kamoshida sorri...[n][e]

[msg jyokyohelp_BOSS_01_SET_S]
[s][f 0 4 128]Kamoshida abre os olhos...[n][e]

[msg jyokyohelp_BOSS_01_AFTER]
[s][f 0 4 128]Kamoshida parece desanimado...[n][e]

[msg jyokyohelp_BOSS_05_WATCH]
[s][f 0 4 128]A Sombra de Okumura parece hesitar...[n][e]

[msg jyokyohelp_BOSS_05_SONG]
[s][f 0 4 128]O robo-viciado está tonto...[n][e]

[msg jyokyohelp_REINFORCE_00]
[s][f 0 4 128]Mas ninguém vem...[n][e]

[msg jyokyohelp_CHAGE_WOMANB]
[s][f 0 4 128]A Sombra de Sae está respirando pesadamente...[n][e]

[msg jyokyohelp_NO_TARGET]
[s][f 0 4 128]Não há alvos disponíveis.[n][e]

[msg jyokyohelp_HOMUNCULUS]
[s][f 0 4 128]O homúnculo se sacrificou![n][e]

[msg jyokyohelp_K_FLANDA_PLAY]
[s][f 0 4 128]Resistência nuclear cancelada![n][e]

[msg jyokyohelp_K_FLANDA_ENEM]
[s][f 0 4 128]Resistência nuclear cancelada![n][e]

[msg jyokyohelp_K_PSYNDA_PLAY]
[s][f 0 4 128]Resistência PK cancelada![n][e]

[msg jyokyohelp_K_PSYNDA_ENEM]
[s][f 0 4 128]Resistência PK cancelada![n][e]

[msg jyokyohelp_K_FLANDA_ADD_]
[s][f 0 4 128]Vulnerabilidade nuclear estendida![n][e]

[msg jyokyohelp_K_FLANDA_ADD__2]
[s][f 0 4 128]Vulnerabilidade nuclear estendida![n][e]

[msg jyokyohelp_K_PSYNDA_ADD_]
[s][f 0 4 128]Vulnerabilidade de PK estendida![n][e]

[msg jyokyohelp_K_PSYNDA_ADD__2]
[s][f 0 4 128]Vulnerabilidade de PK estendida![n][e]

[msg jyokyohelp_FLAYWALL_PLAY]
[s][f 0 4 128]Resistência nuclear aumentada![n][e]

[msg jyokyohelp_FLAYWALL_ENEM]
[s][f 0 4 128]Resistência nuclear aumentada![n][e]

[msg jyokyohelp_PSYWALL_PLAYE]
[s][f 0 4 128]Resistência PK aumentada![n][e]

[msg jyokyohelp_PSYWALL_ENEMY]
[s][f 0 4 128]Resistência PK aumentada![n][e]

[msg jyokyohelp_FLAYWALL_ADD_]
[s][f 0 4 128]Resistência nuclear estendida![n][e]

[msg jyokyohelp_FLAYWALL_ADD__2]
[s][f 0 4 128]Resistência nuclear estendida![n][e]

[msg jyokyohelp_PSYWALL_ADD_P]
[s][f 0 4 128]Resistência PK estendida![n][e]

[msg jyokyohelp_PSYWALL_ADD_E]
[s][f 0 4 128]Resistência PK estendida![n][e]

[msg jyokyohelp_BADSTATUS_REC]
[s][f 0 4 128]Doença de status curada![n][e]

[msg jyokyohelp_KARO_KARA_JUS]
[s][f 0 4 128]De Caroline para Justine![n][e]

[msg jyokyohelp_JUSU_KARA_KAR]
[s][f 0 4 128]De Justine para Caroline![n][e]

[msg jyokyohelp_EXCESS]
[s][f 0 4 128]Não há outros efeitos.[n][e]

[msg jyokyohelp_HIRISK_ADD]
[s][f 0 4 128]Bônus estendido de chance crítica![n][e]

[msg jyokyohelp_BADx2_ADD]
[s][f 0 4 128]Configuração Acidental Estendida![n][e]

[msg jyokyohelp_SENNOH_HEAL]
[s][f 0 4 128][var 0]cure o inimigo![n][e]

[msg jyokyohelp_SENNOH_TAL]
[s][f 0 4 128]O ataque do inimigo aumentou![n][e]

[msg jyokyohelp_SENNOH_RAK]
[s][f 0 4 128]Aumento da defesa inimiga![n][e]

[msg jyokyohelp_SENNOH_SUK]
[s][f 0 4 128]Precisão e evasão do aumento do inimigo![n][e]

[msg jyokyohelp_ITEM_DIS]
[s][f 0 4 128]Ele jogou fora [var 1]![n][e]

[msg jyokyohelp_SENNOH_TAL_AD]
[s][f 0 4 128]Bônus de ataque estendido![n][e]

[msg jyokyohelp_SENNOH_RAK_AD]
[s][f 0 4 128]Bônus de defesa estendido![n][e]

[msg jyokyohelp_SENNOH_SUK_AD]
[s][f 0 4 128]Bônus de Precisão/Evasão Estendidos![n][e]

[msg jyokyohelp_BAD_TOUKETU_N]
[s][f 0 4 128][var 0]é gelo![n][e]

[msg jyokyohelp_BAD_KANDEN_NO]
[s][f 0 4 128][var 0]fica chocado![n][e]

[msg jyokyohelp_BAD_PANIC_NOW]
[s][f 0 4 128][var 0]em confusão![n][e]

[msg jyokyohelp_BAD_SLEEP_NOW]
[s][f 0 4 128][var 0]ele está dormindo...[n][e]

[msg jyokyohelp_BAD_GEKIDO_NO]
[s][f 0 4 128][var 0]ele está furioso![n][e]

[msg jyokyohelp_BAD_SENNOU_NO]
[s][f 0 4 128][var 0]perder a cabeça![n][e]

[msg jyokyohelp_BAD_MOUSE_NOW]
[s][f 0 4 128][var 0]ele está hesitante![n][e]

[msg jyokyohelp_ALREADY]
[s][f 0 4 128]Já foi aplicado.[n][e]

[msg jyokyohelp_UNNECESSARY]
[s][f 0 4 128]Não há necessidade.[n][e]

[msg jyokyohelp_DONTUSE]
[s][f 0 4 128]Não pode ser usado no momento![n][e]

[msg jyokyohelp_SKILL_NONE]
[s][f 0 4 128]Nenhuma habilidade disponível![n][e]

[msg jyokyohelp_GOODS_NONE]
[s][f 0 4 128]Nenhum item disponível![n][e]

[msg jyokyohelp_OPERATION_IMP]
[s][f 0 4 128]Não há ninguém para dar ordens![n][e]

[msg jyokyohelp_ESCAPE_IMPOSS]
[s][f 0 4 128]Você não pode escapar![n][e]

[msg jyokyohelp_ESCAPE_FAILUR]
[s][f 0 4 128]Falha na tentativa de fuga![n][e]

[msg jyokyohelp_NOEFFECT]
[s][f 0 4 128]Não tem efeito![n][e]

[msg jyokyohelp_DEADRCV_SET_A]
[s][f 0 4 128]O aliado não é mais K.O.![n][e]

[msg jyokyohelp_ENG_ADD]
[s][f 0 4 128]Bônus estatísticos estendidos![n][e]

[msg jyokyohelp_KATSUSHIKA_RE]
[s][f 0 4 128]Ele cura diante de seus olhos...[n][e]

[msg jyokyohelp_BATK_MATK_SET_3]
[s][f 0 4 128]Ataque de grupo aumentado![n][e]

[msg jyokyohelp_DEF_SET_ASSIS]
[s][f 0 4 128]Defesa do grupo aumentada![n][e]

[msg jyokyohelp_HIT_ESC_SET_A]
[s][f 0 4 128]Prev. e iludir aumento de grupo![n][e]

[msg jyokyohelp_W_CHARGE_SET_]
[s][f 0 4 128]O grupo está carregado e concentrado![n][e]

[msg jyokyohelp_HP_HEAL_SET_A]
[s][f 0 4 128]Recuperação parcial de HP![n][e]

[msg jyokyohelp_SP_HEAL_SET_A]
[s][f 0 4 128]Recuperação parcial de SP![n][e]

[msg jyokyohelp_ROULETTE_HP_P]
[s][f 0 4 128]HP drenado![n][e]

[msg jyokyohelp_ROULETTE_HP_E]
[s][f 0 4 128]HP drenado![n][e]

[msg jyokyohelp_ROULETTE_SP_P]
[s][f 0 4 128]SP esgotado![n][e]

[msg jyokyohelp_ROULETTE_SP_E]
[s][f 0 4 128]SP esgotado![n][e]

[msg jyokyohelp_ROULETTE_TALK]
[s][f 0 4 128]O ataque foi alterado![n][e]

[msg jyokyohelp_ROULETTE_RAKK]
[s][f 0 4 128]A defesa foi alterada![n][e]

[msg jyokyohelp_ROULETTE_SUKK]
[s][f 0 4 128]Precisão e Evasão alteradas![n][e]

[msg jyokyohelp_GIIN_CHARGE_M]
[s][f 0 4 128][var 0]acumular potência![n][e]

[msg jyokyohelp_GIIN_PYRAMID_]
[s][f 0 4 128][var 0]observar...[n][e]

[msg jyokyohelp_KOUTAIKINSHI]
[s][f 0 4 128]Você não pode substituir aliados nocauteados![n][e]

[msg jyokyohelp_BOSS02_HANA]
[s][f 0 4 128]O nariz do artista estremece...[n][e]

[msg jyokyohelp_UNUSABLE_PERS]
[s][f 0 4 128]Ele não se lembra de como usar Personas![n][e]

[msg jyokyohelp_ALLCANCEL]
[s][f 0 4 128]Ergue uma barreira contra ataques. físico![n][e]

[msg jyokyohelp_P_CHANGE]
[s][f 0 4 128]Mudança de Persona.[n][e]

[msg jyokyohelp_OUT_AMMO]
[s][f 0 4 128]Sem munição![n][e]

[msg jyokyohelp_PIG_SPIN]
[s][f 0 4 128]Piggytron está girando mais rápido![n][e]

[msg jyokyohelp_INJECTION_HP]
[s][f 0 4 128]Ele resistiu graças à injeção![n][e]

[msg jyokyohelp_INJECTION_SP]
[s][f 0 4 128]Ele resistiu graças à injeção![n][e]

[msg jyokyohelp_PATIENCE]
[s][f 0 4 128]Ele resistiu graças à injeção![n][e]

[msg jyokyohelp_TOOFAR]
[s][f 0 4 128]O inimigo está muito longe![n][e]

[msg jyokyohelp_ZETUBOU]
[s][f 0 4 128][var 0]ele se desespera...[n][e]

[msg jyokyohelp_ZETUBOU_END]
[s][f 0 4 128][var 0]sucumbe...[n][e]

[msg jyokyohelp_DAME_BATON]
[s][f 0 4 128]Você não pode usar o Relay agora![n][e]

[msg jyokyohelp_NO_BATON]
[s][f 0 4 128]Ninguém pode receber o Relay![n][e]

[msg jyokyohelp_KYOHU_NOACT]
[s][f 0 4 128][var 0]vacilar![n][e]

[msg jyokyohelp_BAD_MOUSE_ESC]
[s][f 0 4 128][var 0]tente escapar![n][e]

[msg jyokyohelp_AKETI_TARGET]
[s][f 0 4 128]Akechi está encarando o Joker...![n][e]

[msg jyokyohelp_SUTEMI_HUTYAK]
[s][f 0 4 128]Agir. aumentado, diferente diminuído![n][e]

[msg jyokyohelp_SUTEMI_KAIHUK]
[s][f 0 4 128]O desespero desapareceu.[n][e]

[msg jyokyohelp_RAKUNDA_TARKA]
[s][f 0 4 128]Def. diminuído, ativo aumentou![n][e]

[msg jyokyohelp_TARNDA_SUKUKA]
[s][f 0 4 128]Ataque diminuído, evasão aumentada![n][e]

[msg jyokyohelp_SUKUNDA_TARKA]
[s][f 0 4 128]Elus. diminuído, ativo aumentou![n][e]

[msg jyokyohelp_RAKNDA_SUKUND]
[s][f 0 4 128]Defesa/Precisão/Evasão diminuída![n][e]

[msg jyokyohelp_SUKUNDA_TARND]
[s][f 0 4 128]Ataque/Precisão/Evasão diminuído![n][e]

[msg jyokyohelp_RAKNDA_TARNDA]
[s][f 0 4 128]Ataque e defesa diminuídos![n][e]

[msg jyokyohelp_CUP_CHANGE]
[s][f 0 4 128]A aparência do Santo Graal mudou...![n][e]

[msg jyokyohelp_BOSS_WAIT_1]
[s][f 0 4 128][var 0] carrega...[n][e]

[msg jyokyohelp_ENEMY_PRE_ESC]
[s][f 0 4 128][var 0]pânico![n][e]

[msg jyokyohelp_SUMMON_TEKI]
[s][f 0 4 128][var 0]parece![n][e]

[msg jyokyohelp_HOUKOKU_ESCAP]
[s][f 0 4 128][var 0]ele foge![n][e]

[msg jyokyohelp_SHIDO_PRE_FIR]
[s][f 0 4 128]A luz envolve a torre...![n][e]

[msg jyokyohelp_ITEM_SNATCH]
[s][f 0 4 128]Ele agarrou [clr 3][var 1][clr 27]![n][e]

[msg jyokyohelp_NO_SPSHOT]
[s][f 0 4 128]Não há munição suficiente![n][e]

[msg jyokyohelp_COVER_FAIL]
[s][f 0 4 128]A solicitação falhou...[n][e]

[msg jyokyohelp_SHIKIYOKU]
[s][f 0 4 128]Ceda às fantasias libertinas...[n][e]

[msg jyokyohelp_SHIKIYOKU_HIT]
[s][f 0 4 128]Ardendo de desejo...[n][e]

[msg jyokyohelp_COSTUP_HIT]
[s][f 0 4 128]Custo de habilidade dobrado...[n][e]

[msg jyokyohelp_COSTUP_BACK]
[s][f 0 4 128]Custo da habilidade restaurado...[n][e]

[msg jyokyohelp_SHIT_HIT]
[s][f 0 4 128]Morre de inveja...[n][e]

[msg jyokyohelp_SHIT_NOW]
[s][f 0 4 128]Ciúmes de [var 0]![n][e]

[msg jyokyohelp_GOMAN_START]
[s][f 0 4 128]O Livro está pronto para revidar...[n][e]

[msg jyokyohelp_GOMAN_HIT]
[s][f 0 4 128]O Livro emite seu julgamento![n][e]

[msg jyokyohelp_GOMAN_END]
[s][f 0 4 128]O Livro voltou ao normal...[n][e]

[msg jyokyohelp_LASTBOSS_CHAR]
[s][f 0 4 128]Uma luz sinistra se reúne…![n][e]

[msg jyokyohelp_HUNNU_HIT]
[s][f 0 4 128]Ele sai em disparada…[n][e]

[msg jyokyohelp_NET_HIT]
[s][f 0 4 128]Fuga impedida![n][e]

[msg jyokyohelp_NET_MISS]
[s][f 0 4 128]Mas ninguém atende a ligação...[n][e]

[msg jyokyohelp_TENKI_HIT]
[s][f 0 4 128]O conhecimento. compartilhado afeta a Sombra![n][e]

[msg jyokyohelp_BAD_KANDEN_MO]
[s][f 0 4 128]Choque transferido![n][e]

[msg jyokyohelp_JUSTINE_WAIT]
[s][f 0 4 128]Justine está perdida...[n][e]

[msg jyokyohelp_PC_WAIT]
[s][f 0 4 128]Ele não pode se mover...![n][e]

[msg jyokyohelp_KANTU]
[s][f 0 4 128]Ele penetrou na resistência do inimigo![n][e]

[msg jyokyohelp_BATON_1]
[s][f 0 4 128]Não utilizado.[n][e]

[msg jyokyohelp_BATON_2]
[s][f 0 4 128]Ataque e recuperação aumentados![n][e]

[msg jyokyohelp_BATON_3]
[s][f 0 4 128]Agir. e Recuperação aumentar muito![n][e]

[msg jyokyohelp_BATON_4]
[s][f 0 4 128]Ataque e recuperação máximos![n][e]

[msg jyokyohelp_TGET_MONEY]
[s][f 0 4 128]Você tem [var 1] ienes![n][e]

[msg jyokyohelp_TGET_ITEM]
[s][f 0 4 128]Você obteve [clr 3][var 1][clr 27]![n][e]

[msg jyokyohelp_TLOST_MONEY]
[s][f 0 4 128]Você entregou [var 1] ienes...[n][e]

[msg jyokyohelp_TLOST_ITEM]
[s][f 0 4 128]Você entregou [clr 3][var 1][clr 27]...[n][e]

[msg jyokyohelp_TGET_CARD]
[s][f 0 4 128]Obtenha [clr 3][var 1][clr 27] Cartão de[n]habilidade![n][e]

[msg jyokyohelp_TSUCKED_HP]
[s][f 0 4 128]O inimigo absorveu algum HP![n][e]

[msg jyokyohelp_TSUCKED_SP]
[s][f 0 4 128]O inimigo absorveu SP![n][e]

[msg jyokyohelp_TGET_INFO]
[s][f 0 4 128]Anote as informações de [var 1]![n][e]

[msg jyokyohelp_TKILLED_PARTY]
[s][f 0 4 128][var 0]...![n][e]

[msg jyokyohelp_TENEMY_EXIT]
[s][f 0 4 128]O inimigo recuou...[n][e]

[msg jyokyohelp_TCURE_BADSTAT]
[s][f 0 4 128]Alterações inimigas curadas![n][e]

[msg jyokyohelp_TDOWN_ALERT]
[s][f 0 4 128]Ele parece ter baixado a guarda...[n][e]

[msg jyokyohelp_TGET_BLANKCAR]
[s][f 0 4 128]Você obteve um [clr 3]Cartão Grátis[clr 27]![n][e]

[msg jyokyohelp_TNETWORK_COVE]
[s][f 0 4 128]Rodadas de suporte disparadas![n][e]

[msg jyokyohelp_TGET_PERSONA]
[s][f 0 4 128]Obter máscara [clr 1][var 0][clr 27]![n][e]

[msg jyokyohelp_TRELEASED_PAR]
[s][f 0 4 128][var 0] seja livre...[n][e]

[msg jyokyohelp_SHIDO_GANKOH_]
[s][f 0 4 128]A contagem de estoque de Shido aumentou![n][e]

[msg jyokyohelp_DOUBLE_SUMMON]
[s][f 0 4 128] invocou [var 0]![n][e]

[msg jyokyohelp_LOOK_AN]
[s][f 0 4 128][var 0] encara Ann...[n][e]

[msg jyokyohelp_UMEKI]
[s][f 0 4 128][var 0] gemidos...[n][e]

[msg jyokyohelp_HURUE]
[s][f 0 4 128][var 0] está tremendo...[n][e]

[msg jyokyohelp_NIYANIYA]
[s][f 0 4 128][var 0] sorri...[n][e]

[msg jyokyohelp_YOUSUMI]
[s][f 0 4 128][var 0] observa...[n][e]

[msg jyokyohelp_HATE_UP]
[s][f 0 4 128][var 0] é ber. fácil![n][e]

[msg jyokyohelp_BULLET_ZERO]
[s][f 0 4 128] Sem munição![n][e]

[msg jyokyohelp_ALL_WEAK]
[s][f 0 4 128] agora é fraco para todas as afinidades![n][e]

[msg jyokyohelp_HATE_OVER]
[s][f 0 4 128] não é mais um alvo fácil...[n][e]

[msg jyokyohelp_WARAI_TAIKI]
[s][f 0 4 128][var 0] risos...[n][e]

[msg jyokyohelp_INOTIGOI]
[s][f 0 4 128][var 0] fala...[n][e]

[msg jyokyohelp_OTAKARA_SKI]
[s][f 0 4 128][var 0] tem obj. cru![n][e]

[msg jyokyohelp_USONAKI_ENEMY]
[s][f 0 4 128][var 0] ele está hesitante![n][e]

[msg jyokyohelp_NOUSATSU_ENEM]
[s][f 0 4 128] A moral do inimigo melhorou![n][e]

[msg jyokyohelp_STRING]
[s][f 0 4 128] ATK [var 0] cai muito![n][e]

[msg jyokyohelp_AKECHI]
[s][f 0 4 128] As Sombras estão furiosas...![n][e]

[msg jyokyohelp_SKIMMING]
[s][f 0 4 128] Item raro encontrado no inimigo![n][e]

[msg jyokyohelp_HACK]
[s][f 0 4 128] A cognição mudou a seu favor![n][e]

[msg jyokyohelp_TENKI_HIT_INF]
[s][f 0 4 128] A gripe causa desespero![n][e]

[msg jyokyohelp_TENKI_HIT_TYP]
[s][f 0 4 128] Maior suscetibilidade a alterações![n][e]

[msg jyokyohelp_TENKI_HIT_HEA]
[s][f 0 4 128] A onda de calor queima o inimigo![n][e]

[msg jyokyohelp_DUMMY_01]
[s][f 0 4 128][var 0] Preparando-se...[n][e]

[msg jyokyohelp_DUMMY_02]
[s][f 0 4 128][var 0] olhar fixamente![n][e]

[msg jyokyohelp_DUMMY_03]
[s][f 0 4 128][var 0] mostra calma.[n][e]

[msg jyokyohelp_BIGBODY]
[s][f 0 4 128] HP não diminui![n][e]

[msg jyokyohelp_BOTTOMLESS]
[s][f 0 4 128] SP não diminui![n][e]

[msg jyokyohelp_ANALYZE_SINGL]
[s][f 0 4 128]Deb. [var 0] revelado![n][e]

[msg jyokyohelp_ANALYZE_GROUP]
[s][f 0 4 128]Fraquezas Reveladas![n][e]

[msg jyokyohelp_ALL_CHARGE]
[s][f 0 4 128]O grupo está carregado![n][e]

[msg jyokyohelp_RND_ALL_ENEMY]
[s][f 0 4 128]Todas as estatísticas do inimigo reduzidas![n][e]

[msg jyokyohelp_MAKRKN_TETRKN]
[s][f 0 4 128]Barreira física e mágica levantada![n][e]

[msg jyokyohelp_ATO_HAGANE]
[s][f 0 4 128]Custos reduzidos a 0![n][e]

[msg jyokyohelp_ATO_SOKONA]
[s][f 0 4 128]Custos reduzidos a 0![n][e]

[msg jyokyohelp_UNHATE_OVER]
[s][f 0 4 128]Ele não é mais um alvo difícil...[n][e]

[msg jyokyohelp_BARRIER_ENCOU]
[s][f 0 4 128]O inimigo tem uma barreira![n][e]

[msg jyokyohelp_BARRIER_USE]
[s][f 0 4 128][var 0]levantar barreira![n][e]

[msg jyokyohelp_BARRIER_RELEA]
[s][f 0 4 128]Barr. [var 0] desapareceu.[n][e]

[msg jyokyohelp_BARRIER_THROU]
[s][f 0 4 128]Um buraco apareceu na barreira![n][e]

[msg jyokyohelp_BUDDY_SPEC_RY]
[s][f 0 4 128]Reduz o dano recebido.[n][e]

[msg jyokyohelp_BUDDY_SPEC_MO]
[s][f 0 4 128]Aumenta a chance de acerto crítico.[n][e]

[msg jyokyohelp_BUDDY_SPEC_AN]
[s][f 0 4 128]Ataque mágico aumentado.[n][e]

[msg jyokyohelp_BUDDY_SPEC_YU]
[s][f 0 4 128]Dano de ataque aumentado.[n][e]

[msg jyokyohelp_BUDDY_SPEC_MA]
[s][f 0 4 128]O custo de HP das habilidades caiu pela metade.[n][e]

[msg jyokyohelp_BUDDY_SPEC_HA]
[s][f 0 4 128]O custo de SP das habilidades caiu pela metade.[n][e]

[msg jyokyohelp_BUDDY_SPEC_FU]
[s][f 0 4 128]Não usado.[n][e]

[msg jyokyohelp_BUDDY_SPEC_AK]
[s][f 0 4 128]Execute Roubar Informações ao atacar.[n][e]

[msg jyokyohelp_BUDDY_SPEC_NE]
[s][f 0 4 128]Ignore as resistências inimigas.[n][e]

[msg jyokyohelp_BARRIER_ERASE]
[s][f 0 4 128]A barreira foi eliminada![n][e]

[msg jyokyohelp_BLACK]
[s][f 0 4 128][var 0]escurece![n][e]

[msg jyokyohelp_WARIKOMI]
[s][f 0 4 128]Emboscada Inimiga![n][e]

[msg jyokyohelp_ZOKSEI_CHANGE]
[s][f 0 4 128]Reúna o poder do vento![n][e]

[msg jyokyohelp_ZOKSEI_CHANGE_2]
[s][f 0 4 128]Reúna o poder da eletricidade![n][e]

[msg jyokyohelp_BOSS_01_LOOK__3]
[s][f 0 4 128]Kamoshida está encarando Morgana...[n][e]

[msg jyokyohelp_EXBOSS_02_SUM]
[s][f 0 4 128]Madarame criou uma farsa![n][e]

[msg jyokyohelp_EXBOSS1_POWER]
[s][f 0 4 128]Agir. aumentado, diferente diminuído![n][e]

[msg jyokyohelp_UNSTABLE_WAIT]
[s][f 0 4 128][var 0]ele murmura...[n][e]

[msg jyokyohelp_UNSTABLE_ASLE]
[s][f 0 4 128][var 0]Adormece.[n][e]

[msg jyokyohelp_UNSTABLE_EXCI]
[s][f 0 4 128][var 0]ele está fora de si![n][e]

[msg jyokyohelp_UNSTABLE_BORE]
[s][f 0 4 128][var 0]ele se acalma.[n][e]

[msg jyokyohelp_UNSTABLE_DIZZ]
[s][f 0 4 128][var 0]ele está tonto.[n][e]

[msg jyokyohelp_TO_UNSTABLE]
[s][f 0 4 128]Aliado provocado![n][e]

[msg jyokyohelp_TECHNICAL_BRE]
[s][f 0 4 128]O golpe passa pela resistência![n][e]

[msg jyokyohelp_WARIKOMI_GEKI]
[s][f 0 4 128]De repente explode de raiva![n][e]

[msg jyokyohelp_KANESIRO_SPEC]
[s][f 0 4 128]Kaneshiro se distrai com o objeto...[n][e]

[msg jyokyohelp_KANESIRO_IDLE]
[s][f 0 4 128]Kaneshiro esfrega as mãos...[n][e]

[msg jyokyohelp_MSG_TEST]
[s][f 0 4 128]Sem inimigos para afligir![n][e]

[msg jyokyohelp_KANESIRO_ZAKO]
[s][f 0 4 128]Contrato cancelado por falta de fundos...[n][e]

[msg jyokyohelp_ULTIMATESUPPO]
[s][f 0 4 128]Suporte final ativado![n][e]

[msg jyokyohelp_OKUMURA_SYAIN]
[s][f 0 4 128][var 0]ver compromissos.[n][e]

[msg jyokyohelp_OKUMURA_SYAIN_2]
[s][f 0 4 128]Ele não aguenta a pressão e foge![n][e]

[msg jyokyohelp_BOSS_01_LOOK__4]
[s][f 0 4 128]Kamoshida está encarando o Joker...[n][e]

[msg jyokyohelp_BOSS_01_LOOK__5]
[s][f 0 4 128]Kamoshida está encarando alguém...[n][e]

[msg jyokyohelp_BOSS_01_MORGA]
[s][f 0 4 128]Morgana observa Kamoshida...[n][e]

[msg jyokyohelp_DETECTIVE_OOA]
[s][f 0 4 128]Fraquezas inimigas determinadas![n][e]

[msg jyokyohelp_DETECTIVE_ATA]
[s][f 0 4 128]Afinidades inimigas determinadas![n][e]

[msg jyokyohelp_TGET_EXP]
[s][f 0 4 128][clr 1][var 0][clr 27]recebe XP![n][e]

[msg jyokyohelp_FURIHARAI]
[s][f 0 4 128]Alteração de status removida![n][e]

[msg jyokyohelp_TENSIONSWITCH]
[s][f 0 4 128][var 0]ATK+ com fluxo![n][e]

[msg jyokyohelp_GIIN_REST]
[s][f 0 4 128]Shido respira pesadamente...[n][e]

[msg jyokyohelp_GIIN_STANDBY]
[s][f 0 4 128]Shido respira normalmente...[n][e]

[msg jyokyohelp_YAMATA_WAIT]
[s][f 0 4 128]A cabeça principal mudou![n][e]

[msg jyokyohelp_KAARI__WAIT1]
[s][f 0 4 128]Raiva em [var 0] aumenta.[n][e]

[msg jyokyohelp_KAARI__WAIT2]
[s][f 0 4 128]Raiva de [var 0] até máx.[n][e]

[msg jyokyohelp_KAARI__WAIT3]
[s][f 0 4 128][var 0]torna-se feroz.[n][e]

[msg jyokyohelp_ANUBIS_WAIT1]
[s][f 0 4 128]Ele se prepara para invocar os mortos...[n][e]

[msg jyokyohelp_AZATOTH_CHARG]
[s][f 0 4 128]Energias ameaçadoras se acumulam...[n][e]

[msg jyokyohelp_ADAM_STANDBY]
[s][f 0 4 128]Adam Kadmon é imóvel...[n][e]

[msg jyokyohelp_AZATOTH_IDLE]
[s][f 0 4 128]Azathoth prepara os tentáculos...[n][e]

[msg jyokyohelp_MARUKI_USE_CH]
[s][f 0 4 128]As afinidades dos tentáculos mudaram![n][e]

[msg jyokyohelp_ALL_CONCENTRA]
[s][f 0 4 128]O grupo está focado![n][e]

[msg jyokyohelp_JIIK_KAMAE]
[s][f 0 4 128][var 0]lâmina de atualização.[n][e]

[msg jyokyohelp_AISHO_KYOUKA]
[s][f 0 4 128]Afinidade alterada para iridescente![n][e]

[msg jyokyohelp_MARUKI_EFFECT]
[s][f 0 4 128]Tentáculos revividos em um estado especial![n][e]

[msg jyokyohelp_MARUKI_EFFECT_2]
[s][f 0 4 128]Dano de ataque aumentado![n][e]

[msg jyokyohelp_MARUKI_EFFECT_3]
[s][f 0 4 128]Ataque mágico aumentado![n][e]

[msg jyokyohelp_MARUKI_EFFECT_4]
[s][f 0 4 128]Ataque para baixo![n][e]

[msg jyokyohelp_MARUKI_EFFECT_5]
[s][f 0 4 128]Defesa baixa![n][e]

[msg jyokyohelp_MARUKI_EFFECT_6]
[s][f 0 4 128]Azathoth está carregado![n][e]

[msg jyokyohelp_MARUKI_EFFECT_7]
[s][f 0 4 128]O ataque de Azathoth aumentou![n][e]

[msg jyokyohelp_MARUKI_EFFECT_8]
[s][f 0 4 128]Azathoth está focado![n][e]

[msg jyokyohelp_MARUKI_EFFECT_9]
[s][f 0 4 128]O ataque de Azathoth diminuiu![n][e]

[msg jyokyohelp_MARUKI_EFFECT_10]
[s][f 0 4 128]Defesa baixa![n][e]

[msg jyokyohelp_NARUKISSOSU__]
[s][f 0 4 128][var 0]ele se enfeitiça.[n][e]

[msg jyokyohelp_SARASVATEXI__]
[s][f 0 4 128][var 0]toca alaúde.[n][e]

[msg jyokyohelp_MARUKICOOP_SP]
[s][f 0 4 128][var 0]gravando. poucos SP![n][e]

[msg jyokyohelp_D_EYE1_WEAK]
[s][f 0 4 128]Deb. revelado: [var 0]![n][e]

[msg jyokyohelp_D_EYE1_REFLEC]
[s][f 0 4 128]Refl. [var 0] detectar![n][e]

[msg jyokyohelp_D_EYE1_ABSORB]
[s][f 0 4 128]Absorver [var 0] rev.![n][e]

[msg jyokyohelp_D_EYE1_BLOCK]
[s][f 0 4 128]cancelar [var 0] detectar![n][e]

[msg jyokyohelp_D_EYE1_NORMAL]
[s][f 0 4 128]afim. [var 0] detectar![n][e]

[msg jyokyohelp_D_EYE2_ALL]
[s][f 0 4 128]Todas as afinidades reveladas![n][e]

[msg jyokyohelp_D_EYE2_RESIST]
[s][f 0 4 128]Res. revelado: [var 0]![n][e]

[msg jyokyohelp_KANESIRO_ZAKO_2]
[s][f 0 4 128]Kaneshiro protegido![n][e]

[msg jyokyohelp_ANN_COOPABILI]
[s][f 0 4 128][var 0]ele está em transe...[n][e]

[msg jyokyohelp_ANN_COOPABILI_2]
[s][f 0 4 128][var 0]acalmar...[n][e]

[msg jyokyohelp_MADARAME_ACCE]
[s][f 0 4 128]Criou uma pintura que absorve um ataque![n][e]

[msg jyokyohelp_KANESIRO_FAIL]
[s][f 0 4 128]Nada aconteceu...[n][e]

[msg jyokyohelp_TOKUSEI_PT_BU]
[s][f 0 4 128]Dano aumentado![n][e]

[msg jyokyohelp_TOKUSEI_PT_HE]
[s][f 0 4 128]Custos de SP reduzidos![n][e]

[msg jyokyohelp_TOKUSEI_PT_MA]
[s][f 0 4 128]Dano aumentado![n][e]

[msg jyokyohelp_TOKUSEI_PT_HP]
[s][f 0 4 128]Custos de HP reduzidos![n][e]

[msg jyokyohelp_TOKUSEI_PT_SP]
[s][f 0 4 128]Custos de SP reduzidos![n][e]

[msg jyokyohelp_TOKUSEI_PT_TE]
[s][f 0 4 128]Dano aumentado![n][e]

[msg jyokyohelp_TOKUSEI_PT_DA]
[s][f 0 4 128]Custos reduzidos![n][e]

[msg jyokyohelp_TOKUSEI_PT_CR]
[s][f 0 4 128]Dano aumentado![n][e]

[msg jyokyohelp_SK_ATK_JOSE]
[s][f 0 4 128]José solta os fogos de artifício![n][e]

[msg jyokyohelp_ANUBIS1]
[s][f 0 4 128]O equilíbrio muda para Curse.[n][e]

[msg jyokyohelp_ANUBIS2]
[s][f 0 4 128]O equilíbrio se desloca para o Sagrado.[n][e]

[msg jyokyohelp_UNSTABLE_DROP]
[s][f 0 4 128][clr 3][var 1][clr 27]cai![n][e]

[msg jyokyohelp_ITEM_POWERCHA]
[s][f 0 4 128][var 0]está carregado![n][e]

[msg jyokyohelp_ITEM_MINDCHAR]
[s][f 0 4 128][var 0]foca![n][e]

[msg jyokyohelp_TOKUSEI_PT_HE_2]
[s][f 0 4 128]não utilizado[n][e]

[msg jyokyohelp_TOKUSEI_PT_BU_2]
[s][f 0 4 128]não utilizado[n][e]

[msg jyokyohelp_TOKUSEI_PT_3B]
[s][f 0 4 128]não utilizado[n][e]

[msg jyokyohelp_TOKUSEI_PT_3B_2]
[s][f 0 4 128]não utilizado[n][e]

[msg jyokyohelp_TOKUSEI_PT_3B_3]
[s][f 0 4 128]não utilizado[n][e]

[msg jyokyohelp_TOKUSEI_PT_WE]
[s][f 0 4 128]não utilizado[n][e]

[msg jyokyohelp_TOKUSEI_PT_BA]
[s][f 0 4 128]não utilizado[n][e]

[msg jyokyohelp_COOP_ZONE]
[s][f 0 4 128][var 0]ATK+ com fluxo.[n][e]

[msg jyokyohelp_QUEST_KORO_WA]
[s][f 0 4 128]As articulações doem...[n][e]

[msg jyokyohelp_ABADON_ONLY]
[s][f 0 4 128][var 0]ele carrega...[n][e]

[msg jyokyohelp_ANUBIS_ONLY1]
[s][f 0 4 128][var 0] na maldição.[n][e]

[msg jyokyohelp_ANUBIS_ONLY2]
[s][f 0 4 128][var 0] no Santo.[n][e]

[msg jyokyohelp_ANUBIS_ONLY3]
[s][f 0 4 128][var 0] em equilíbrio.[n][e]

[msg jyokyohelp_BLACKU_1]
[s][f 0 4 128][var 0] iniciar. distância automática[n][e]

[msg jyokyohelp_BLACKU_2]
[s][f 0 4 128][var 0] não resiste.[n][e]

[msg jyokyohelp_BLACKU_3]
[s][f 0 4 128][var 0] está explodindo![n][e]

[msg jyokyohelp_ADAMU_DMG_CUT]
[s][f 0 4 128]Dano a Maruki bastante reduzido![n][e]

[msg jyokyohelp_MARUKI_WAITIN]
[s][f 0 4 128]Maruki olha assim...[n][e]

[msg jyokyohelp_TOKUSEI_TYPE_]
[s][f 0 4 128]Esticam[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__2]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__3]
[s][f 0 4 128]Custos de SP reduzidos com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__4]
[s][f 0 4 128]Alterar. status + com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__5]
[s][f 0 4 128]Custos de SP reduzidos com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__6]
[s][f 0 4 128]Custos de HP reduzidos com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__7]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__8]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__9]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__10]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__11]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__12]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__13]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__14]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__15]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__16]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__17]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__18]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__19]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__20]
[s][f 0 4 128]Custos de SP reduzidos com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__21]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__22]
[s][f 0 4 128]Custos de HP reduzidos com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__23]
[s][f 0 4 128]Custos de SP reduzidos com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__24]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__25]
[s][f 0 4 128]Custos reduzidos com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__26]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__27]
[s][f 0 4 128]Fictício[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__28]
[s][f 0 4 128]Fictício[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__29]
[s][f 0 4 128]Custos de SP reduzidos com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__30]
[s][f 0 4 128]Alterar. cancelado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__31]
[s][f 0 4 128]Ataque desviado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__32]
[s][f 0 4 128]SP recuperado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__33]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__34]
[s][f 0 4 128]Custos de SP reduzidos com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__35]
[s][f 0 4 128]absorver. dobre com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__36]
[s][f 0 4 128]Fraco para danificar - com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__37]
[s][f 0 4 128]Ef. sup. estendido com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__38]
[s][f 0 4 128]Possível. raio. + com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__39]
[s][f 0 4 128]poss. congelar + com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__40]
[s][f 0 4 128]Res. alteração + com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__41]
[s][f 0 4 128]Reflexo. dano + com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__42]
[s][f 0 4 128]Recuperação de HP + com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__43]
[s][f 0 4 128]Alterar. status + com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__44]
[s][f 0 4 128]poss. de Chamas + com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__45]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__46]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__47]
[s][f 0 4 128]Custos de SP reduzidos com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__48]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__49]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__50]
[s][f 0 4 128]Ef. sup. estendido com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__51]
[s][f 0 4 128][clr 1][var 2][clr 27]: poss. morto ist. +![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__52]
[s][f 0 4 128][clr 1][var 2][clr 27]ativado em emboscada![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__53]
[s][f 0 4 128]Ef. clima ativo com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__54]
[s][f 0 4 128]O poder aumenta muito com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__55]
[s][f 0 4 128][clr 1][var 2][clr 27]ativado em emboscada![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__56]
[s][f 0 4 128]Ataques poderosos x2 com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__57]
[s][f 0 4 128]Ataques fatais restantes: [var 1][n][e]

[msg jyokyohelp_TOKUSEI_TYPE__58]
[s][f 0 4 128]Eu uso obj. grátis com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__59]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__60]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__61]
[s][f 0 4 128]Enorme poder com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__62]
[s][f 0 4 128]SP custa pela metade com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__63]
[s][f 0 4 128]Ef. recuperação + com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__64]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__65]
[s][f 0 4 128][clr 1][var 2][clr 27]: poss. ativo Trat. +![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__66]
[s][f 0 4 128]Alterar. status + com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__67]
[s][f 0 4 128][clr 1][var 2][clr 27]: poss. morto ist. ++![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__68]
[s][f 0 4 128]Zero custos de SP com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__69]
[s][f 0 4 128][clr 1][var 2][clr 27]: poss. Att. concat. +![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__70]
[s][f 0 4 128]Oscilação dano com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__71]
[s][f 0 4 128]Custos reduzidos a 0 com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__72]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__73]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__74]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__75]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__76]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__77]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__78]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__79]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__80]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__81]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__82]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__83]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__84]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__85]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__86]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__87]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__88]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__89]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__90]
[s][f 0 4 128]VAZIO[n][e]

[msg jyokyohelp_TOKUSEI_TYPE__91]
[s][f 0 4 128]Poder aumentado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__92]
[s][f 0 4 128][clr 1][var 2][clr 27]impulsionar a recuperação![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__93]
[s][f 0 4 128]Custos de SP reduzidos com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__94]
[s][f 0 4 128]Ataque desviado com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__95]
[s][f 0 4 128][clr 1][var 2][clr 27]: Chamas/Cong./Choque. +![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__96]
[s][f 0 4 128]Alterar. status - com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__97]
[s][f 0 4 128]Custos de SP reduzidos com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__98]
[s][f 0 4 128]Recuperação com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__99]
[s][f 0 4 128]Custos de SP reduzidos com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_TOKUSEI_TYPE__100]
[s][f 0 4 128]Custos de SP reduzidos com [clr 1][var 2][clr 27]![n][e]

[msg jyokyohelp_UNHATE_START]
[s][f 0 4 128][var 0]é ber. dif.![n][e]

[msg jyokyohelp_HATE_ADD]
[s][f 0 4 128]Ef. estendida para um alvo mais fácil![n][e]

[msg jyokyohelp_UNHATE_ADD]
[s][f 0 4 128]Ef. estendida para um alvo mais difícil![n][e]

[msg jyokyohelp_CADENZA]
[s][f 0 4 128]Evasão aumentada![n][e]

[msg jyokyohelp_CADENZA_OVER]
[s][f 0 4 128]Evasão restaurada![n][e]

[msg jyokyohelp_CADENZA_ADD]
[s][f 0 4 128]Bônus de prevenção estendido![n][e]

[msg jyokyohelp_EXBOSS_02_FAK]
[s][f 0 4 128][var 0] contemplar![n][e]

[msg jyokyohelp_JIIKFLE_SENYO]
[s][f 0 4 128][var 0] mudar expr.![n][e]

[msg jyokyohelp_SPECIFIC_AZAT]
[s][f 0 4 128]Dano bastante reduzido em [clr 1]Shield[n]Tentáculo[clr 27]![n][e]

[msg jyokyohelp_SPECIFIC_AZAT_2]
[s][f 0 4 128]Dano reduzido em [clr 1]Shield Tentáculo[clr 27]![n][e]

[msg jyokyohelp_SPECIFIC_AZAT_3]
[s][f 0 4 128]Dano reduzido em uma pequena quantidade de [n][clr 1]Shield Tentáculo[clr 27]![n][e]

[msg jyokyohelp_KANESIRO_WAIT]
[s][f 0 4 128]Kaneshiro se arrepende...[n][e]

[msg jyokyohelp_MARUKI_DEFEAT]
[s][f 0 4 128]Maruki parece incapaz de se mover...[n][e]

