[msg TEST_000]
[s]スクリプトから発行した[n]メッセージです。[n][w][e]

[msg MSG_SPOT_OPEN_AKIHABARA]
[s]Agora você pode ir para [clr 2]Akihabara [clr 27].[n][w][e]
[s]Você também pode convidar pessoas que gostam[n]lá para sair com você.[n][w][e]

[msg TEST_MINE]
[s]Parece que eu promovei meu [n][f 4 11 4][clr 26][f 4 12 4][clr 27].[n][w][e]

[msg TEST_MINE2]
[s]Acho que posso enfrentar maiores desafios[n]agora![n][w][e]

