[msg TEST_000]
[s]スクリプトから発行した[n]メッセージです。[n][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Did you hear? Apparently it's[n]an astoundingly large burger.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]That sounds awesome.[e]
[s]I'm not interested.[e]
[s]It'd prolly make me sick...[e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That's the spirit![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Phantom thieves need the [f 4 11 3][clr 26][f 4 12 3][clr 27] to[n]try anything. We should go sometime.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Don't be so passive...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Phantom thieves need the [f 4 11 3][clr 26][f 4 12 3][clr 27] to[n]try anything. We should go sometime.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No whining! Young people can eat[n]anything![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Phantom thieves need the [f 4 11 3][clr 26][f 4 12 3][clr 27] to[n]try anything. We should go sometime.[n][f 1 3 65535][w][e]

