[msg MSG_BTLSTART_001 [Ryuji]]
[s][bup 0 2 0 65535 0]Estamos cercados! Isso nao parece[n]tao bom...![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Morgana]]
[s][bup 0 3 0 0 0]Temos que suportar, pessoal...![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Morgana]]
[s]Observe com cuidado, depois gire![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Morgana]]
[s]Parece que voce esta finalmente recebendo um[n]suspenso do basico.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_005]
[s]A batalha pode comecar com sua equipe cercada[n]Se o inimigo o pega desprevenido.[n][f 1 3 65535][w][e]
[s]Alem de uma virada extra inimiga no[n]inicio da batalha, certas acoes como[n]Como fugir, nao estara disponivel.[n][f 1 3 65535][w][e]

