[msg MSG_BTLSTART_000_008 [Haru]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1001 0 7]E hora de voce se render, pai![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_000_007 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 8]Voce esta preso! Desistir![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_010_000 [Shadow Okumura]]
[s][vp 8 0 2 1003 1 221]Desistir...?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_030_000 [Shadow Okumura]]
[s][vp 8 0 2 1004 1 221]Tente dizer isso depois de derrubar[n]Os soldados de elite da minha empresa![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_040_008 [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 7]Nao! Ha mais!?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_040_007 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1006 0 8]O que, mais deles!?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_050_000 [Shadow Okumura]]
[s][vp 8 0 2 1007 1 221]Va, meus funcionarios! Seja a fundacao[n]sobre o qual minha vitoria e construida...![n][f 1 3 65535][w][e]

[msg MSG_SUMMON_000_008 [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1008 0 7]Ainda mais!?[n][f 1 3 65535][w][e]

[msg MSG_SUMMON_000_007 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1009 0 8]Eles tem mais!?[n][f 1 3 65535][w][e]

[msg MSG_SUMMON_010_000 [Shadow Okumura]]
[s][vp 8 0 2 1010 1 221]Todo problema pode ser resolvido com[n]Mais mao de obra...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1011 1 221]Essa e a forca da minha empresa![n][f 1 3 65535][w][e]

[msg MSG_SUMMON_020_008 [Haru]]
[s][bup 0 7 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1012 0 7]Felicidade com base nos sacrificios de[n]Outros nao sao a verdadeira felicidade...![n][f 1 3 65535][w][e]

[msg MSG_SUMMON_020_007 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1013 0 8]Isso nao e algo para se orgulhar...![n][f 1 3 65535][w][e]

[msg MSG_BOMB_000_008 [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1014 0 7]Eu eu se autodestruto...!?[n][f 1 3 65535][w][e]

[msg MSG_BOMB_000_007 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1015 0 8]Isso acabou de explodir...!?[n][f 1 3 65535][w][e]

[msg MSG_BOMB_010_000 [Shadow Okumura]]
[s][vp 8 0 2 1016 1 221]Hahaha! Meus trabalhadores vao obedecer a qualquer[n]Ordem que dou a eles![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1017 1 221]Voce nao acha que a lealdade deles e[n]incrivel!?[n][f 1 3 65535][w][e]

[msg MSG_BOMB_020_008 [Haru]]
[s][bup 0 7 105 65535 0][f 4 10 65535 0 0][vp 8 0 2 1018 0 7]Eu nao posso acreditar nisso...![n][f 1 3 65535][w][e]

[msg MSG_BOMB_020_007 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 8]Eles simplesmente nao tem permissao para desobedecer[n]voces...![n][f 1 3 65535][w][e]

[msg MSG_SENNMU_000_000 [Shadow Okumura]]
[s][vp 8 0 2 1020 1 221]HM...!? Parece que os trabalhadores comuns sao[n]Nao e adequado para o trabalho![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1021 1 221]Diretor-executivo! Venha ate mim![n][f 1 3 65535][w][e]

[msg MSG_SENNMU_010_000 [Shadow Okumura]]
[s][vp 8 0 2 1022 1 221]Agora entao, cumpre seu dever como meu[n]Homem da mao direita![n][f 1 3 65535][w][e]

[msg MSG_SENNMU_020_000 [Shadow Okumura]]
[s][vp 8 0 2 1023 1 221]Para a eterna prosperidade de[n]Okumura Foods![n][f 1 3 65535][w][e]

[msg MSG_SENMU75_000_000 [Shadow Okumura]]
[s][vp 8 0 2 1024 1 221]HM...!? O que voce esta fazendo!?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1025 1 221]Trabalhe mais! Contribua mais! O destino[n]da minha empresa repousa sobre o quao dificil[n]voce trabalha![n][f 1 3 65535][w][e]

[msg MSG_SENMU25_000_000 [Shadow Okumura]]
[s][vp 8 0 2 1026 1 221]Ei! Perder nao e uma opcao aqui![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1027 1 221]Voce carrega a Okumura Foods Company[n]nome! Mate esses ladroes, mesmo que custe[n]voce e sua vida![n][f 1 3 65535][w][e]

[msg MSG_ONRY_000_000 [Shadow Okumura]]
[s][vp 8 0 2 1028 1 221]O que...!? Ate ele...!?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_030_000 [Shadow Okumura]]
[s][vp 8 0 2 1029 1 221]Grrr, alguem! Esta aqui alguem!?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_040_000 [Shadow Okumura]]
[s][vp 8 0 2 1030 1 221]O que nao esta vindo!?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_050_008 [Haru]]
[s][bup 0 7 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1031 0 7]Pai... voce foi abandonado mesmo por[n]seus proprios funcionarios...[n][f 1 3 65535][w][e]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1032 0 7]Vamos terminar isso, Joker![n][f 1 3 65535][w][e]

[msg MSG_ONRY_050_007 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 8]Esse e o ultimo dos lacaios?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_051_007 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1106 0 8]Vamos acabar com ele, Coringa![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_000_008EX [Haru]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1001 0 7]E hora de voce se render, pai![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_000_007EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 8]Voce esta preso! Desistir![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_010_000EX [Shadow Okumura]]
[s][vp 8 0 2 1003 1 221]Desistir...?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_030_000EX [Shadow Okumura]]
[s][vp 8 0 2 1004 1 221]Tente dizer isso depois de derrubar[n]Os soldados de elite da minha empresa![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_040_008EX [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 7]Nao! Ha mais!?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_040_007EX [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1006 0 8]O que mais inimigos!?[clr 2]Se nao tomarmos[n]'eles para baixo rapido[clr 27], estamos condenados![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_050_000EX [Shadow Okumura]]
[s][vp 8 0 2 1007 1 221]Va, meus funcionarios! Seja a fundacao[n]sobre o qual minha vitoria e construida...![n][f 1 3 65535][w][e]

[msg MSG_SUMMON_000_008EX [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1028 0 7]Ainda mais!?[n][f 1 3 65535][w][e]

[msg MSG_SUMMON_000_007EX [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1029 0 8]Eles tem mais!?[n][f 1 3 65535][w][e]

[msg MSG_SUMMON_010_000EX [Shadow Okumura]]
[s][vp 8 0 2 1030 1 221]Todo problema pode ser resolvido com[n]Mais mao de obra...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1031 1 221]Essa e a forca da minha empresa![n][f 1 3 65535][w][e]

[msg MSG_SUMMON_020_008EX [Haru]]
[s][bup 0 7 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1032 0 7]Felicidade com base nos sacrificios de[n]Outros nao sao a verdadeira felicidade...![n][f 1 3 65535][w][e]

[msg MSG_SUMMON_020_007EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 8]Isso nao e algo para se orgulhar...![n][f 1 3 65535][w][e]

[msg MSG_BOMB_000_008EX [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1042 0 7]Eu eu se autodestruto...!?[n][f 1 3 65535][w][e]

[msg MSG_BOMB_000_007EX [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 8]Isso acabou de explodir...!?[n][f 1 3 65535][w][e]

[msg MSG_BOMB_010_000EX [Shadow Okumura]]
[s][vp 8 0 2 1044 1 221]Hahaha! Meus trabalhadores vao obedecer a qualquer[n]Ordem que dou a eles![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1045 1 221]Voce nao acha que a lealdade deles e[n]incrivel!?[n][f 1 3 65535][w][e]

[msg MSG_BOMB_020_008EX [Haru]]
[s][bup 0 7 105 65535 0][f 4 10 65535 0 0][vp 8 0 2 1046 0 7]Eu nao posso acreditar nisso...![n][f 1 3 65535][w][e]

[msg MSG_BOMB_020_007EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1047 0 8]Eles simplesmente nao tem permissao para desobedecer[n]voces...![n][f 1 3 65535][w][e]

[msg MSG_SENNMU_000_000EX [Shadow Okumura]]
[s][vp 8 0 2 1068 1 221]HM...!? Parece que os trabalhadores comuns sao[n]Nao e adequado para o trabalho![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1069 1 221]Diretor-executivo! Venha ate mim![n][f 1 3 65535][w][e]

[msg MSG_SENNMU_010_000EX [Shadow Okumura]]
[s][vp 8 0 2 1070 1 221]Agora entao, cumpre seu dever como meu[n]Homem da mao direita![n][f 1 3 65535][w][e]

[msg MSG_SENNMU_020_000EX [Shadow Okumura]]
[s][vp 8 0 2 1071 1 221]Para a eterna prosperidade de[n]Okumura Foods![n][f 1 3 65535][w][e]

[msg MSG_SENMU75_000_000EX [Shadow Okumura]]
[s][vp 8 0 2 1072 1 221]HM...!? O que voce esta fazendo!?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1073 1 221]Trabalhe mais! Contribua mais! O destino[n]da minha empresa repousa sobre o quao dificil[n]voce trabalha![n][f 1 3 65535][w][e]

[msg MSG_SENMU25_000_000EX [Shadow Okumura]]
[s][vp 8 0 2 1074 1 221]Ei! Perder nao e uma opcao aqui![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1075 1 221]Voce carrega a Okumura Foods Company[n]nome! Mate esses ladroes, mesmo que custe[n]voce e sua vida![n][f 1 3 65535][w][e]

[msg MSG_ONRY_000_000EX [Shadow Okumura]]
[s][vp 8 0 2 1076 1 221]O que...!? Ate ele...!?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_030_000EX [Shadow Okumura]]
[s][vp 8 0 2 1077 1 221]Grrr, alguem! Esta aqui alguem!?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_040_000EX [Shadow Okumura]]
[s][vp 8 0 2 1102 1 221]O que nao esta vindo!?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_050_008EX [Haru]]
[s][bup 0 7 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1103 0 7]Pai... voce foi abandonado mesmo por[n]seus proprios funcionarios...[n][f 1 3 65535][w][e]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1104 0 7]Vamos terminar isso, Joker![n][f 1 3 65535][w][e]

[msg MSG_ONRY_050_007EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1105 0 8]Esse e o ultimo dos lacaios?[n][f 1 3 65535][w][e]

[msg MSG_ONRY_051_007EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1106 0 8]Vamos acabar com ele, Coringa![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_ADD_001 [Shadow Okumura]]
[s][vp 8 0 2 1008 1 221]Agora, meus trabalhadores dedicados! Alvejando[n]eles aleatoriamente nao farao o truque![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1009 1 221]Voce tem que tirar cada um individualmente 悪[n]Aqui, alveje-o primeiro![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_001 [Shadow Okumura]]
[s][vp 8 0 2 1010 1 221]O homem pomposo de casaco preto![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_002 [Shadow Okumura]]
[s][vp 8 0 2 1011 1 221]O loiro desagradavel![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_003 [Shadow Okumura]]
[s][vp 8 0 2 1012 1 221]Isso... coisa bizarra, em preto e branco![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_004 [Shadow Okumura]]
[s][vp 8 0 2 1013 1 221]A mulher de aparencia sacanagem em vermelho![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_005 [Shadow Okumura]]
[s][vp 8 0 2 1014 1 221]O estranho com a Fox Mask![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_006 [Shadow Okumura]]
[s][vp 8 0 2 1015 1 221]A mulher barbaro e de cabelos escuros![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_007 [Shadow Okumura]]
[s][vp 8 0 2 1016 1 221]O falso com o rosto da minha filha![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_NON1 [Corporobo]]
[s][vp 8 0 2 1017 0 0]Nao consigo encontrar o alvo![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_NON2 [Corporobo]]
[s][vp 8 0 2 1019 0 0]Presidente Okumura! NAO POSSO[n]ENCONTRE O ALVO![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_CHAN [Shadow Okumura]]
[s][vp 8 0 2 1022 1 221]La, voce os tirou. Proximo,[n]Concentre-se nisso![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_CHAN_2 [Shadow Okumura]]
[s][vp 8 0 2 1023 1 221]Ugh, que movimento secreto![n]Alvo esse em vez disso![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_TARGET_CHAN_3 [Shadow Okumura]]
[s][vp 8 0 2 1024 1 221]Ei! Por que a demora? Voce nao pode[n]Scrap Heaps faz um trabalho simples?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1025 1 221]Basta disso! Alvo esse proximo![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_ESCAPED01 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1027 0 8]O que 悪 Ei! Onde voce pensa que voce[n]indo!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_ESCAPED02 [Shadow Okumura]]
[s][vp 8 0 2 1036 1 221]Hmph, perdendo alguns descartaveis[n]funcionarios nao sao nada para mim. Eu tenho[n]Mais do que suficiente para substitui-los![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1037 1 221]Voce cometeu um erro grave[n]subestimando minha empresa[n]corpo![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_REINFORCED [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1034 0 8]Droga, quantos deles sao[n]la!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_REINFORCED_2 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1035 0 8]Tomando um para baixo um de cada vez nao vai[n]Faca o truque 悪[clr 2]Livre-se de tudo de uma vez[clr 27][n]Entao voce pode atacar Okumura![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_SWEPT01 [Shadow Okumura]]
[s][vp 8 0 2 1038 1 221]Hmph, entao meus trabalhadores comuns nao podem[n]atender as demandas aqui. Nesse caso...[n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_SWEPT02 [Shadow Okumura]]
[s][vp 8 0 2 1039 1 221]Ugh, caramba, esses ladroes... Chefe do balconista![n]Entre aqui e cuide disso![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_SWEPT03 [Shadow Okumura]]
[s][vp 8 0 2 1040 1 221]Droga! Ei, secao chefe! Pegue estes[n]Frats de Loudmouth fora da minha vista![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_SWEPT04 [Shadow Okumura]]
[s][vp 8 0 2 1041 1 221]Argh... seu tempo chegou, chefe[n]Diretor! Va em frente e mostre-lhes[n]O peso da elite corporativa![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYAIN_SWEPT05 [Shadow Okumura]]
[s][vp 8 0 2 1007 1 221](未使用)[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_EXTRASP_RES [社畜秘書ロボ]]
[s]★(未使用)専務、特別さーびすノオ時間デス。[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_EXTRASP_COL [社畜秘書ロボ]]
[s]★(未使用)忘レ物ヲ回収イタシマス。[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_EXTRASP_RES_2 [社畜専務ロボ]]
[s]★(未使用)オット。[n]モウ、ソンナ時間カ。[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_00 [Shadow Okumura]]
[s][vp 8 0 2 1048 1 221]Serio, quao inutil voce pode ser!?[n]O que quer que tenha sido a lealdade da empresa?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_01 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1034 0 8](未使用)もうやめろ![n]自分の娘がこんなに苦しんでるんだぞ![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_02 [Shadow Okumura]]
[s][vp 8 0 2 1049 1 221]... Muito bem entao, Haru! Ensinar nosso[n]funcionarios como demonstrar[n]sua lealdade corretamente![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_TEST]
[s](ハルが椅子の裏から登場するシーン)[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_03 [Cognitive Haru Okumura]]
[s][vp 8 0 2 1050 1 609]Sim, Pai![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_03B [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1051 0 7]Huh!? M-me!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_03C [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1052 0 8]O que 悪 noir!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_04 [Shadow Okumura]]
[s][vp 8 0 2 1053 1 221]Meu Haru obedece fielmente minhas ordens![n]Afinal, ela nao e nada como o seu[n]charlatao![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_05 [Haru]]
[s][bup 0 7 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1054 0 7]Basicamente... isso e cognitivo do meu pai[n]Versao de mim...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_05B [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 8]Eu vejo... entao essa e a cognicao de Okumura[n]de Haru...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_07 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1056 0 8]Ei pessoal, nao deixe isso chegar ate voce![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1057 0 8][f 4 10 65535 0 0]Lembre-se: uma vez que tomamos Okumura[n]para baixo, tudo acabou. Vamos encerrar isso[n]rapido![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_EP_08 [Shadow Okumura]]
[s][vp 8 0 2 1058 1 221]Nao esta acontecendo. Voce nao deveria ter[n]subestimou a forca do meu[n]companhia.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1059 1 221]Funcionarios, caem na fila![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_ENHANCE [Shadow Okumura]]
[s][vp 8 0 2 1060 1 221]Nao vou deixar alguns ladroes mesquinhos ficarem[n]Na empresa 悪 Nao, no meu caminho![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_ENHANCE_2 [Shadow Okumura]]
[s][vp 8 0 2 1061 1 221]Quem discorda da minha visao[n]sera derrubado como exemplo![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_ENHANCE_3 [Cognitive Haru Okumura]]
[s][vp 8 0 2 1062 1 609]As palavras do meu pai sao absolutas.[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_ENHANCE_4 [Cognitive Haru Okumura]]
[s][vp 8 0 2 1063 1 609]Nao ha falhas na logica de meu pai.[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_ENHANCE_5 [Shadow Okumura]]
[s][vp 8 0 2 1066 1 221]Ha uma boa filha! Agora eu posso[n]orgulhar-se do meu trabalho.[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_ENHANCE_6 [Shadow Okumura]]
[s][vp 8 0 2 1067 1 221]E isso mesmo, Haru. E preciso atacar[n]O inimigo enquanto o ferro esta quente![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_01 [Shadow Okumura]]
[s][vp 8 0 2 1078 1 221]Droga! Se e assim que e...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1079 1 221]Haru, eu ordeno que voce saia![n]Mostre a eles o poder da nossa empresa![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02 [Cognitive Haru Okumura]]
[s][vp 8 0 2 1080 1 609]Sim, Pai![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02B [Shadow Okumura]]
[s][vp 8 0 2 1081 1 221]Okumura Foods sera destruido se eu cair![n]Voce entende a situacao aqui, Haru?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02B2 [Cognitive Haru Okumura]]
[s][vp 8 0 2 1082 1 609]Claro, pai![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02C [Shadow Okumura]]
[s][vp 8 0 2 1083 1 221]Bem, entao me proteja 悪 mesmo que isso te custe[n]sua vida![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02C2 [Cognitive Haru Okumura]]
[s][vp 8 0 2 1084 1 609]Como voce deseja, pai![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_TEST]
[s](ハルがロボットに変身するシーン)[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02D [Haru]]
[s][bup 0 7 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1085 0 7]E assim que meu pai me ve...[n]Nada mais que um fantoche[n]que danca quando ordenado...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02E [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1086 0 8]Eu nao posso acreditar nesse cara! Uma crianca nao e uma[n]meio que fantoche ou ferramenta a ser usada![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02F [Cognitive Haru Okumura]]
[s][vp 8 0 2 1087 1 609]Isso e por causa do meu pai.[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_02G [Shadow Okumura]]
[s][vp 8 0 2 1088 1 221]Qual e a espera, Haru!? Se voce nao o fizer[n]Pare-os, meus sonhos...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_03 [Shadow Okumura]]
[s][vp 8 0 2 1089 1 221]Gah, parece que nao tenho outra escolha...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_04 [Shadow Okumura]]
[s][vp 8 0 2 1090 1 221]Haru 悪 Autodestruicao! Detonar e levar[n]Aqueles malditos ladroes com voce![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_05 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1091 0 8]De jeito nenhum!? Okumura esta ate disposto a[n]sacrifique sua propria filha!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_05B [Haru]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1092 0 7]... todos, vamos destrui-lo antes[n]Pode se autodestruir![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_05B2 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1093 0 8]Mas, noir... isso e...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_05B3 [Haru]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1094 0 7]Eu nao sou mais subserviente do meu pai[n]fantoche! O verdadeiro eu esta certo[n]Aqui, opondo-se a ele![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_05C [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1095 0 8]Coringa, nao deixe detonar! Isso nao e[n]O verdadeiro noir 悪 Destrui![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_06 [Shadow Okumura]]
[s][vp 8 0 2 1096 1 221]O que 悪!? Ate Haru nao conseguiu dete-los!?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1097 1 221]Eu ja tive o suficiente! Alguem, entre aqui![n]...Alguem!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_06B [Shadow Okumura]]
[s][vp 8 0 2 1098 1 221]Entao, mesmo Haru nao conseguiu acabar com eles...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1099 1 221]Eu ja tive o suficiente! Alguem, entre aqui![n]...Alguem!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_07A [Haru]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1100 0 7]Pai, a hora chegou isso.[n]Espero que voce tenha se preparado![n][f 1 3 65535][w][e]

[msg MSG_BTL_ADD_HARU_GO_07 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1101 0 8]Encontramos nossa chance! Coringa, vamos[n]Coloque um fim nisso![n][f 1 3 65535][w][e]

