[msg EX_000e_CHECK_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]TH-O INFERNO... não está se abrindo![n][w][e]

[msg EX_000e_CHECK_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espere... eu posso ouvir uma brisa fraca[n]soprando de algum lugar... Existe outra[n]maneira de passar?[n][w][e]

[msg LOCK_CLEAR01]
[s](調整中)扉の鍵を[n]解錠する流れが入る予定です。[n][w][e]

[msg LOCK_CLEAR02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7147 65535 0]Tudo bem! Vamos me mover![n][w][e]

[msg LOCK_DOOR]
[s]A porta está trancada.[n][w][e]

[msg D01_ex_e490_001_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Alguma coisa está com esta porta...[n][w][e]

[msg D01_ex_e490_001_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não parece diferente de tudo o que vimos até[n]agora?[n][w][e]

[msg D01_ex_e490_001_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu nunca vi nada parecido também...[n]Vamos dar uma olhada mais de perto, Joker.[n][w][e]

[msg DOOR_Dummy_MES [Morgana]]
[s]ERROR! イベントをセットして下さい。[n][w][e]

