[msg NOT_OPEN_DOOR]
[s]A porta está completamente selada.[n][w][e]

[msg LOCK_DOOR]
[s]A porta está trancada.[n][w][e]

[msg timer_block_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]Podemos relaxar mais tarde, cara![n][w][e]

[msg timer_block_mes03 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1029 65535 0]Onde você está indo?!?[n]O tempo está acabando![n][w][e]

[msg DOOR_Dummy_MES [Morgana]]
[s]ERROR! イベントをセットして下さい。[n][w][e]

