[msg D10_02_DOOR_mes01 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Não é bom... teremos que encontrar outra[n]maneira.[n][w][e]

[msg D10_02_DOOR_mes02 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos encontrar outra rota.[n][w][e]

[msg D10_02_ST_door_mes01 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Não discutimos a necessidade de ir ao[n]auditório? Não posso dizer que concordo com[n]algum desvio no momento.[n][w][e]

[msg NOT_OPEN_DOOR]
[s]A porta está bem selada.[n][w][e]

[msg LOCK_DOOR]
[s]A porta está trancada.[n][w][e]

[msg D10_02_ST_door_mes02 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Não sabemos o que o inimigo está planejando-[n]não vamos desviar-se por enquanto e apenas[n]focar em nosso objetivo.[n][w][e]

[msg DOOR_Dummy_MES [Futaba]]
[s]ERROR! イベントをセットして下さい。[n][w][e]

