[msg NOT_OPEN_DOOR]
[s]A porta está completamente selada.[n][w][e]

[msg NOT_OPEN_DOOR02]
[s](調整中)扉に柵がかかり[n]見た目的にも通れないとわかるようにします。[n][w][e]

[msg LOCK_DOOR]
[s]A porta está trancada.[n][w][e]

[msg LOCK_CLEAR01]
[s](調整中)扉にかかった柵を[n]解除する流れが入る予定です。[n][w][e]

[msg LOCK_CLEAR02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bom! Vamos![n][w][e]

[msg EX_0009_mes01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ei, não vai abrir![n][w][e]

[msg EX_0009_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Deve haver outras saídas![n]Vamos encontrar outra![n][w][e]

[msg LOCK_EX_DOOR]
[s]A porta está completamente fechada...[n][w][e]

[msg PREV_SEED_GET_EX_DOOR_me [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh? É o que eu acho que é? Joker,[n]você pode dar uma[n]olhar mais de perto?[n][w][e]

[msg DOOR_Dummy_MES [Morgana]]
[s]ERROR! イベントをセットして下さい。[n][w][e]

