[msg MSG_000_0_0 [オシャレに目覚めた男子]]
[s][vp 8 0 0 0 4 0]今日、帰りに本屋寄ってもいい?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [地味な男子]]
[s][vp 8 0 0 0 5 0]いいけど...[n]お前が本屋? 珍しいな...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]何買うんだ?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [オシャレに目覚めた男子]]
[s][vp 8 0 0 0 4 0]『色気が上がると噂のおしゃれ入門書』[n]って知らない?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]ネットのレビューも高くて、売り切れ続出。[n]ようやく再入荷したんだよ。[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]これで僕も...[n]フフフ...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Brutish Boy]]
[s][vp 8 0 0 0 4 0]Voce sempre tem otimas notas, cara...[n]Voce gosta, estudar na biblioteca ou[n]algo?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Refined Boy]]
[s][vp 8 0 0 0 5 0]De jeito nenhum. Na verdade, eu uso o restaurante para[n]tais atividades.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]E um lugar surpreendentemente otimo para[n]concentracao. Voce pode ate comer se[n]Voce fica com fome no meio da sessao.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Brutish Boy]]
[s][vp 8 0 0 0 4 0]Voce esta brincando comigo? Cara, todos voces ricos peeps[n]sao tao diferentes do resto de nos...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Eu quero estudar em uma lanchonete tambem! Ah bem,[n]Acho que tenho que encontrar um emprego de meio periodo para isso...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Rain-Hating Student]]
[s][vp 8 0 0 0 4 0]Eu realmente nao suporto dias chuvosos...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Meu cabelo fica todo fora de pancada, minhas roupas[n]Fique encharcado... faz voce querer apenas[n]Fique la dentro, sim?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Rain-Loving Student]]
[s][vp 8 0 0 0 5 0]Serio? Eu amo todas essas coisas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]E meio que, o som da chuva e[n]calmante... eu posso me concentrar na leitura e[n]estudando muito mais.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Rain-Loving Student]]
[s][vp 8 0 0 0 4 0]Huh? Eu nao estava esperando uma resposta como[n]que... voce com certeza e estranho...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Anxious Student]]
[s][vp 8 2 0 42913 4 0]... voce nao acha toda aquela chantagem[n]as coisas sao loucas?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Eu nao achei que tivesse nada a ver com[n]eu, mas ha ate vitimas no meu[n]classe...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Fast-Talking Student]]
[s][vp 8 0 0 0 5 0]Oooh, eu sei tudo sobre isso! Esses caras[n]supostamente veio perguntar se voce quer um[n]trabalho facil e bem remunerado...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Mas entao, se voce disser sim, voce e arrastado[n]em algumas coisas obscuras...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Os professores ou prez do conselho estudantil farao[n]algo sobre isso embora. As pessoas sao reais[n]preocupado.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Anxious Student]]
[s][vp 8 0 0 0 4 0]Oh, voce esta falando sobre essa postagem?[n]Eu me pergunto se ela estava falando serio sobre isso...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Ouvi dizer que ela sabia sobre Kamoshida e[n]o assedio sexual... ela prolly nao vai[n]seja muito ajuda...[n][f 1 3 65535][w][e]

