[msg SNUFF_PS_GET_NG]
[s]Voce ja tem essa mascara...[n][e]

[msg SNUFF_PS_MAX]
[s]Voce nao pode segurar mais mascaras...[n][e]

[msg COMBINE_WARNING_MSG]
[s]Estou sentindo inquieto...[n][w][e]

[msg SYS_HumanParam_ItemUse]
[s]Gracas ao "nome do item", seu[n]Estatisticas sociais aumentarao mais[n]do que o normal para esse periodo.[n][w][e]
[s]O efeito continuara tanto tempo[n]A medida que o tempo nao avanca. Faco[n]Bom uso disso enquanto voce pode.[n][w][e]

