[msg CMM_EVENT_OPEN]
[s][vp 1 0 0 0 0 0]Você desbloqueou o[n]Confidente da Arcana: O Mago![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Mesclando Arcanum Personas: O Mago[n]agora concederá a você XP[n]graças ao Arcanum Impetus![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Você aprendeu a criar[n][clr 1]ferramentas de infiltração[clr 27] com Morgana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_2]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: O Mago[n]alcançou [clr 2]Nível 2[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Personas Arcanas: O Mago![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_3]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: O Mago[n]alcançou [clr 2]Rank 3[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Personas Arcanas: O Mago![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Morgana agora pode usar [clr 1]Reverb[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_4]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: O Mago[n]alcançou [clr 2]Nível 4[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Personas Arcanas: O Mago![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora Morgana pode usar [clr 1]fala de gato[n][clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_5]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: O Mago[n]alcançou [clr 2]Nível 5[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Personas Arcanas: O Mago![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Aprendeu a[n][clr 1]Rob[clr 27] com Morgana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_6]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: O Mago[n]alcançou [clr 2]Nível 6[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Personas Arcanas: O Mago![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Você aprendeu a criar[n][clr 1]Ferramentas Mestras[clr 27] com Morgana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_7]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: O Mago[n]alcançou [clr 2]Nível 7[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Personas Arcanas: O Mago![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Morgana agora pode usar[n][clr 1]Harisen regenerativo[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_8]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: O Mago[n]alcançou [clr 2]Nível 8[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Personas Arcanas: O Mago![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Morgana agora pode usar [clr 1]Endurance[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_9]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: O Mago[n]alcançou [clr 2]Nível 9[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Personas Arcanas: O Mago![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Morgana agora pode usar [clr 1]baluarte[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKMAX]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: O Mago[n]alcançou [clr 2]MAX Rank[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Personas Arcanas: O Mago![n][f 1 3 65535][w][e]

[msg CMM_EVENT_UNLOCK]
[s][vp 1 0 0 0 0 0]Agora você pode fundir [clr 1]Futsunushi[clr 27],[n]a Persona[n]mais poderosa[n]da Arcana: o Mago.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_REVERSE]
[s][vp 1 0 0 0 0 0]Seu Mago Confidente está em um estado de Dúvida.[n]Você não receberá seus benefícios até limpar seu[n]nome.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_UPRIGHT]
[s][vp 1 0 0 0 0 0]Você levantou o estado de Dúvida[n]em seu Mago Confidente.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_BROKEN]
[s][vp 1 0 0 0 0 0]Seu Magician Confidant agora está quebrado. O[n]acordo está cancelado e você não receberá seus[n]benefícios neste estado.[n][f 1 3 65535][w][e]

