[msg CMM_EVENT_OPEN]
[s][vp 1 0 0 0 0 0]Você desbloqueou o confidente mágico![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Personas fusíveis do Magician Arcana agora[n]lhe concederão exp devido à explosão de[n]Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Você aprendeu a fazer [n][clr 1]Ferramentas de infiltração [clr 27]De Morgana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_2]
[s][vp 1 0 0 0 0 0]Seu confidente mágico aumentou para [clr 2]Rank 2 [clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais exp de Arcana Burst[n]ao fundir personas do Magician Arcana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_3]
[s][vp 1 0 0 0 0 0]Seu confidente mágico aumentou para [clr 2]Rank 3 [clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais exp de Arcana Burst[n]ao fundir personas do Magician Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Morgana agora pode usar [clr 1]Acompanhamento [clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_4]
[s][vp 1 0 0 0 0 0]Seu confidente mágico aumentou para [clr 2]Rank 4 [clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais exp de Arcana Burst[n]ao fundir personas do Magician Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Morgana agora pode usar [clr 1]Conversa de gatinhos [clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_5]
[s][vp 1 0 0 0 0 0]Seu confidente mágico aumentou para [clr 2]Rank 5 [clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais exp de Arcana Burst[n]ao fundir personas do Magician Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Você aprendeu como [n][clr 1]Pickpocket [clr 27]De Morgana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_6]
[s][vp 1 0 0 0 0 0]Seu confidente mágico aumentou para [clr 2]Rank 6 [clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais exp de Arcana Burst[n]ao fundir personas do Magician Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Você aprendeu a fazer [n][clr 1]Ferramentas de ás [clr 27]De Morgana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_7]
[s][vp 1 0 0 0 0 0]Seu confidente mágico aumentou para [clr 2]Rank 7 [clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais exp de Arcana Burst[n]ao fundir personas do Magician Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Morgana agora pode usar [n][clr 1]Harisen Recovery [clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_8]
[s][vp 1 0 0 0 0 0]Seu confidente mágico aumentou para [clr 2]Rank 8 [clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais exp de Arcana Burst[n]ao fundir personas do Magician Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Morgana agora pode usar [clr 1]Aguentar [clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_9]
[s][vp 1 0 0 0 0 0]Seu confidente mágico aumentou para [clr 2]Rank 9 [clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais exp de Arcana Burst[n]ao fundir personas do Magician Arcana![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Morgana agora pode usar [clr 1]Proteger [clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKMAX]
[s][vp 1 0 0 0 0 0]Seu confidente mágico aumentou para [clr 2]MAX RANK [clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais exp de Arcana Burst[n]ao fundir personas do Magician Arcana![n][f 1 3 65535][w][e]

[msg CMM_EVENT_UNLOCK]
[s][vp 1 0 0 0 0 0]Agora você pode se fundir [clr 1]Futsunushi [clr 27], a persona mais poderosa do Arcana Mágico.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_REVERSE]
[s][vp 1 0 0 0 0 0]Seu confidente mágico está em estado de[n]dúvida. Você não receberá seus benefícios[n]até limpar seu nome.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_UPRIGHT]
[s][vp 1 0 0 0 0 0]Você levantou o estado de dúvida sobre seu[n]confidente de mágico.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_BROKEN]
[s][vp 1 0 0 0 0 0]Seu confidente mágico está agora quebrado. O[n]acordo está desligado e você não receberá[n]seus benefícios nesse estado.[n][f 1 3 65535][w][e]

