[msg CMM_EVENT_OPEN]
[s][vp 1 0 0 0 0 0]Você desbloqueou o[n]Confidente da Arcana: O Diabo![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Mesclando Arcanum Personas:[n]O Diabo agora concederá XP a você[n]graças ao Arcanum Impetus![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você pode pedir a Ohya para escrever[n]você um [clr 1]Scoop infundado[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_2]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: o Diabo[n]alcançou [clr 2]Nível 2[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Arcane Personas: The Devil![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_3]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: o Diabo[n]alcançou [clr 2]Grau 3[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Arcane Personas: The Devil![n][f 1 3 65535][w][e]
[s]Agora você pode pedir a Ohya para escrever[n]para você um [clr 1]Shocking Scoop[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_4]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: O Diabo[n]alcançou [clr 2]Grau 4[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Arcane Personas: The Devil![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_5]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: O Diabo[n]alcançou [clr 2]Nível 5[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Arcane Personas: The Devil![n][f 1 3 65535][w][e]
[s]Agora você pode pedir a Ohya para escrever[n]para você um [clr 1]Scoop inédito[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_6]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: O Diabo[n]alcançou [clr 2]Nível 6[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Arcane Personas: The Devil![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_7]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: O Diabo[n]alcançou [clr 2]Nível 7[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Arcane Personas: The Devil![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você pode pedir a Ohya para escrever[n]para você um [clr 1]Outrageous Scoop[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_8]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: O Diabo[n]alcançou [clr 2]Nível 8[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Arcane Personas: The Devil![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_9]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: o Diabo[n]alcançou [clr 2]Grau 9[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Arcane Personas: The Devil![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKMAX]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: o Diabo[n]alcançou [clr 2]Classe MÁX[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você ganhará mais XP[n]do Arcanum Surge ao fundir[n]Arcane Personas: The Devil![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Agora você pode pedir a Ohya para escrever[n]para você um [clr 1]Legendary Scoop[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_UNLOCK]
[s][vp 1 0 0 0 0 0]Agora você pode fundir [clr 1]Belzebu[clr 27],[n]a Pessoa mais poderosa[n]da Arcana: o Diabo.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_REVERSE]
[s][vp 1 0 0 0 0 0]Seu confidente demoníaco está em estado de[n]dúvida. Você não receberá seus benefícios até[n]limpar seu nome.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_UPRIGHT]
[s][vp 1 0 0 0 0 0]Você levantou o estado de[n]Dúvida em seu Confidente Diabólico.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_BROKEN]
[s][vp 1 0 0 0 0 0]O Confidente da Arcana: o Diabo[n]quebrou. O pacto é nulo e,[n]neste estado, você não receberá mais[n]os benefícios.[n][f 1 3 65535][w][e]

