[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Que porra é essa...?!?[n]Não vamos dar um arranhão nela![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Huh? Futaba?!?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Você já entrou em seu próprio[n]mundo cognitivo?!?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][bup 0 8 700 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Mm-hm...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Uma pessoa entrando em[n]seu próprio Palácio?[n]Quando isso acontece...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Futaba]]
[s][bup 0 8 700 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Eu...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Voz masculina profunda]]
[s][vp 8 0 0 11 65535 0]Você a matou![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Futaba]]
[s][bup 0 8 703 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Não...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Voz masculina aguda]]
[s][vp 8 0 0 21 65535 0]Vamos, diga alguma coisa![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Voz feminina estridente]]
[s][vp 8 0 0 22 65535 0]A culpa é sua![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Futaba]]
[s][bup 0 8 703 0 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]A culpa é minha...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]É minha culpa que mamãe...[n][f 1 3 65535][w][e]

[msg DVL_024_0_0 [Monstro do palácio]]
[s][vp 8 0 0 26 65535 0]Certo![n][f 1 3 65535][w][e]
[s][vp 8 0 0 27 65535 0]Você me matou![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Yusuke]]
[s][bup 0 5 104 0 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Espera,[n]aquele monstro é a mãe dele?!?[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Os desejos e culpa de Futaba[n]devem ter distorcido[n]sua compreensão de sua mãe.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Em tudo isso há também o desejo[n]de que sua mãe ainda estivesse viva[n]e... aqueles gritos fantasmagóricos.[n][f 1 3 65535][w][e]

[msg DVL_028_0_0 [Wakaba Cognitivo]]
[s][vp 8 0 0 33 65535 0]Você é apenas um monstro que se meteu no meu[n]caminho! Eu gostaria que você nunca tivesse[n]nascido![n][f 1 3 65535][w][e]
[s][vp 8 0 0 34 65535 0]Eu poderia ter postado[n]meus resultados sem ter que[n]perder meu tempo com você![n][f 1 3 65535][w][e]
[s][vp 8 0 0 35 65535 0]Eu coloquei meu coração e alma nessa busca! Teria[n]sido a descoberta do século![n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]O que você quer dizer?[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Ele está falando sobre[n]ciência psi-cognitiva...?[n][f 1 3 65535][w][e]

[msg DVL_032_0_0 [Wakaba Cognitivo]]
[s][vp 8 0 0 39 65535 0]Você vai morrer![n][f 1 3 65535][w][e]
[s][vp 8 0 0 41 65535 0]Sua vida não tem sentido![n]Ninguém precisa de você![n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Futaba]]
[s][bup 0 8 703 0 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Ninguém se importa comigo...[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Homem adulto]]
[s][vp 8 0 0 43 65535 0]"Futaba nunca[n]deveria ter nascido",[n]"Não passou de um incômodo".[n][f 1 3 65535][w][e]
[s][vp 8 0 0 44 65535 0]Você parece ter dado[n]muitos problemas para sua mãe,[n]Futaba-chan ...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 45 65535 0]Ela deve ter desenvolvido algum tipo de neurose[n]de maternidade...[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Futaba]]
[s][bup 0 8 705 0 0][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]N-Ngh...[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 17 301 1][vp 8 0 0 48 65535 0]Ei, se isso continuar[n]nós estaremos na merda![n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Mulher jovem]]
[s][vp 8 0 0 55 65535 0]Aaagh... Agh...![n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Mulher jovem]]
[s][vp 8 0 0 56 65535 0]...F-Futabaaaa...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 57 65535 0]...V-Você... vocêeeeeee...[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Futaba]]
[s][bup 0 8 705 0 0][f 4 10 65535 0 0][vp 8 0 0 58 65535 0]Ngh...![n][f 1 3 65535][w][e]

[msg MSG_044_5_0 [Makoto]]
[s][bup 0 6 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Então, estar convencida de que ela[n]matou sua mãe... e pensando[n]que ela merecia morrer...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Futaba criou um palácio[n]onde sua mãe a quer morta?[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][vp 8 0 0 59 65535 0]Futaba-chan, dê uma boa olhada![n]Não tem como esse monstro[n]ser sua mãe![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 60 65535 0]É apenas uma ilusão criada por você![n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Futaba]]
[s][bup 0 8 703 0 0][f 4 10 65535 0 0][vp 8 0 0 61 65535 0]M-Mas...[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][vp 8 0 0 65 65535 0]Ele nunca te machucou, não é?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 66 65535 0]O chefe nos disse! Ela disse[n]que te criou sozinha e[n]sempre fez tudo o que podia![n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][vp 8 0 0 67 65535 0]Não é uma memória falsa que[n]foi impressa em sua memória?[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Futaba]]
[s][bup 0 8 703 0 0][f 4 10 65535 0 0][vp 8 0 0 68 65535 0]Uma memória falsa?[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Futaba]]
[s][bup 0 8 705 65535 0][f 4 10 65535 0 0][vp 8 0 0 69 65535 0]Aaah...[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Homem adulto]]
[s][vp 8 0 0 71 65535 0]Futaba, você forçou sua mãe[n]a destruir a pesquisa dela...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 72 65535 0]E pensar que ele[n]trabalhou tanto nisso ...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 73 65535 0]Ele perdeu a cabeça,[n]e a culpa é só sua...[n][f 1 3 65535][w][e]

[msg MSG_059_0_0 [Futaba]]
[s][bup 0 8 705 0 0][f 4 10 65535 0 0][vp 8 0 0 79 65535 0]M-Mãe... Eu-Eu...[n][f 1 3 65535][w][e]

[msg MSG_060_0_0 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 12 301 1][vp 8 0 0 80 65535 0]É a Sombra dele![n][f 1 3 65535][w][e]

[msg MSG_061_0_0 [Sombra de Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][vp 8 0 0 81 10 0]Futaba Sakura! Lembre-se![n][f 1 3 65535][w][e]

[msg MSG_063_0_0 [Sombra de Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][vp 8 0 0 83 10 0]Você é a razão que a levou ao suicídio. Você não[n]passava de um obstáculo para a pesquisa dele.[n][f 1 3 65535][w][e]

[msg MSG_075_0_0 [Sombra de Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][vp 8 0 0 101 10 0]Por que você acha que[n]foi suicídio?[n][f 1 3 65535][w][e]

[msg MSG_076_0_0 [Futaba]]
[s][bup 0 8 703 0 0][f 4 10 65535 0 0][vp 8 0 0 102 65535 0]...Para essa carta.[n][f 1 3 65535][w][e]

[msg MSG_077_0_0 [Sombra de Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][vp 8 0 0 103 10 0]Exatamente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 104 10 0]Foram os homens vestidos de preto que leram a[n]carta para você. O que ele dizia?[n][f 1 3 65535][w][e]

[msg MSG_078_0_0 [Futaba]]
[s][bup 0 8 703 0 0][f 4 10 65535 0 0][vp 8 0 0 105 65535 0]Naquela carta...[n]mãe reclamou de mim.[n][f 1 3 65535][w][e]

[msg MSG_079_0_0 [Sombra de Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][vp 8 0 0 106 10 0]Trauma e dor[n]fizeram você desviar o olhar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 107 10 0]Os homens de preto continuaram[n]lendo a carta[n]na frente de seus parentes.[n][f 1 3 65535][w][e]

[msg MSG_083_0_0 [Sombra de Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][vp 8 0 0 114 10 0]Pense com cuidado. Essa carta era[n]realmente autêntica?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 115 10 0]A mãe que te amou tanto[n]…poderia[n]escrever essas palavras?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 116 10 0]Ele já havia dito coisas tão horríveis para você[n]antes daquele momento?[n][f 1 3 65535][w][e]

[msg MSG_084_0_0 [Futaba]]
[s][bup 0 8 702 0 0][f 4 10 65535 0 0][vp 8 0 0 117 65535 0]Não![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 118 65535 0]Ele me repreendeu quando tive um ataque de raiva,[n]mas ele me amou![n][f 1 3 65535][w][e]

[msg MSG_085_0_0 [Sombra de Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][vp 8 0 0 119 10 0]Então, o que era aquela carta?[n][f 1 3 65535][w][e]

[msg MSG_086_0_0 [Futaba]]
[s][bup 0 8 702 0 0][f 4 10 65535 0 0][vp 8 0 0 120 65535 0]Foi só mentira![n][f 1 3 65535][w][e]

[msg MSG_087_0_0 [Sombra de Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][vp 8 0 0 124 10 0]Eles usaram você![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 125 10 0]Eles forjaram aquela carta[n]e culparam você[n]pela morte dela![n][f 1 3 65535][w][e]

[msg MSG_087_5_0 [Sombra de Futaba]]
[s][bup 0 8 900 0 0][f 4 10 65535 0 0][vp 8 0 0 126 10 0]Eles pisotearam seu jovem coração! Reagir! Você[n]não pode perdoar aqueles adultos corruptos![n][f 1 3 65535][w][e]

[msg MSG_088_0_0 [Futaba]]
[s][bup 0 8 703 0 0][f 4 10 65535 0 0][vp 8 0 0 122 65535 0]Aconteceu porque eu não conseguia[n]enfrentar a mim mesmo,[n]ou a morte da minha mãe...[n][f 1 3 65535][w][e]

[msg MSG_088_5_0 [Futaba]]
[s][bup 0 8 702 0 0][f 4 10 65535 0 0][vp 8 0 0 123 65535 0]E de qualquer maneira, por que eles tiveram que[n]gritar comigo assim?!?[n][f 1 3 65535][w][e]

[msg MSG_090_0_0 [Futaba]]
[s][bup 0 8 703 0 0][f 4 10 65535 0 0][vp 8 0 0 127 65535 0]Ah...[n][f 1 3 65535][w][e]

[msg MSG_091_0_0 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][vp 8 0 0 128 65535 0]Futaba-chan?!?[n][f 1 3 65535][w][e]

[msg MSG_092_0_0 [Futaba]]
[s][bup 0 8 705 0 0][f 4 10 65535 0 0][vp 8 0 0 129 65535 0]Ngh![n][f 1 3 65535][w][e]

[msg DVL_093_0_0 [Voz misteriosa]]
[s][vp 8 0 0 130 65535 0]O que te prende é uma ilusão.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 131 65535 0]Uma maldição que foi[n]imposta a você por indivíduos sem coração...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 132 65535 0]Você sabia disso desde o começo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 133 65535 0]E, no entanto, você se deixou vencer pelo medo...[n][f 1 3 65535][w][e]

[msg MSG_094_0_0 [Futaba]]
[s][bup 0 8 705 0 0][f 4 10 65535 0 0][vp 8 0 0 134 65535 0]...Está certo. Eu sabia, mas eu...[n][f 1 3 65535][w][e]

[msg DVL_095_0_0 [Wakaba Cognitivo]]
[s][vp 8 0 0 135 65535 0]É tudo culpa sua![n]Desta vez, você vai morrer![n][f 1 3 65535][w][e]

[msg DVL_096_0_0 [Voz misteriosa]]
[s][vp 8 0 0 136 65535 0]Você vai morrer como eles mandam?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 137 65535 0]A quem você vai obedecer?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 138 65535 0]Para as palavras traiçoeiras de uma ilusão[n]enfurecida? Ou a verdade que habita em sua alma?[n][f 1 3 65535][w][e]

[msg DVL_097_0_0 [Wakaba Cognitivo]]
[s][vp 8 0 0 139 65535 0]A culpa é sua![n]A culpa é toda sua![n][f 1 2 160][e]

[msg MSG_098_0_0 [Futaba]]
[s][bup 0 8 705 0 0][f 4 10 65535 0 0][vp 8 0 0 140 65535 0]Não vou deixar essas[n]mentiras distorcidas me enganarem novamente...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 141 65535 0]E não serei mais desviado[n]pelas vozes dos outros...[n][f 1 3 65535][w][e]

[msg MSG_098_3_0 [Futaba]]
[s][bup 0 8 703 0 0][f 4 10 65535 0 0][vp 8 0 0 142 65535 0]Confiarei apenas em meus olhos[n]e em meu coração, para distinguir[n]o falso do verdadeiro.[n][f 1 3 65535][w][e]

[msg MSG_098_5_0 [Futaba]]
[s][bup 0 8 702 0 0][f 4 10 65535 0 0][vp 8 0 0 143 65535 0]Você não é minha mãe![n]Você é apenas uma mentira[n]criada por aqueles adultos horríveis![n][f 1 3 65535][w][e]

[msg MSG_098_6_0 [Futaba]]
[s][bup 0 8 702 0 0][f 4 10 65535 0 0][vp 8 0 0 144 65535 0]Eu...eu não...[n][f 1 3 65535][w][e]

[msg MSG_098_7_0 [Futaba]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 8 13 301 1][vp 8 0 0 145 65535 0]Eu nunca vou perdoá-los![n][f 1 3 65535][w][e]

