[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Futaba estará sob seus cuidados hoje.[n][f 1 3 65535][w][e]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Certifique-se de não deixar caras tentarem[n]bater nela.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Eu não vou deixar o lado dela.[e]
[s]Não se preocupe.[e]
[s]Vou lutar contra eles.[e]

[msg MSG_002_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Bom, desde que você entenda. Eu vou contar[n]com você.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]As praias de verão estão cheias de todos os[n]tipos de idiotas soltando-se. Eu preciso[n]que você fique ao lado dela.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Não faça nada que faça você se destacar,[n]idiota. Basta agir com seus cérebros, ok?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Ei, já podemos ir?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Tem certeza de que você estará bem?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]É apenas uma viagem de um dia! Não me[n]subestime![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]R-right... desculpe.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]... Acho que eu só tenho que deixar ir.[n]Divirta-se, mas tenha cuidado com vocês[n]dois.[n][f 1 3 65535][w][e]

