[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu sei que posso não ser humano...[n]Eu sei disso há muito tempo...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas se eu não sou... o que eu sou?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Quando, onde e por que nasci?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]E onde é o meu lugar?[n][f 1 3 65535][w][e]

