[msg MSG_000_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Mona ainda não está em casa...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Tenho certeza que ele voltará quando ficar[n]com fome.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Newscaster]]
[s][vp 8 0 0 3 65535 0]Na nossa próxima história.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 4 65535 0]No final da noite passada, várias janelas de[n]vidro foram encontradas quebradas na sede[n]corporativa da Okumura Foods.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][f 5 14]Ei, isso é aquela Okumura.[n][w][e]

[msg MSG_004_0_0 [Newscaster]]
[s][vp 8 0 0 5 65535 0]Outros danos também foram relatados,[n]incluindo a destruição de uma estátua que[n]descreve o Sr. Okumura.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Huh... me pergunto se alguém tem um rancor[n]contra esse cara...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Newscaster]]
[s][vp 8 0 0 7 65535 0]No entanto, não havia sinais de invasão.[n]Identificar o culpado deve ser difícil...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][f 5 14]Você acha que Mona estava lá sozinho?[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]É possível.[e]
[s]Por que você diz isso?[e]
[s]Estou preocupado...[e]

[msg MSG_009_0_0 [Futaba]]
[s][f 5 14]Sim... ele pode não parecer às vezes, mas[n]ele é totalmente um gato capaz quando quer[n]ser.[n][w][e]

[msg MSG_010_0_0 [Futaba]]
[s][f 5 14]É apenas um pressentimento...[n][w][e]
[s][f 5 14]Quero dizer, ele pode ser bastante[n]imprudente e teimoso às vezes.[n][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][f 5 14]Uh-huh...[n][w][e]

[msg MSG_012_0_0 [Futaba]]
[s][f 5 14]De qualquer maneira, vamos ao Palácio de[n]Okumura amanhã. Vou entrar em contato com[n]todos.[n][w][e]

[msg MSG_013_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][vp 1 0 0 8 0 0]......?[n][f 1 3 65535][w][e]

