[msg MSG_000_5_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Olha... é isso... esse é o tesouro![n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]O que!?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Robotic Voice]]
[s][vp 8 0 0 2 65535 0]A sequência de lançamento de emergência será[n]ativada em breve.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 3 65535 0]Certas áreas podem ser desligadas ou[n]destruídas.[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Robotic Voice]]
[s][vp 8 0 0 4 65535 0]Repito, a sequência de lançamento de[n]emergência será ativada em breve.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 5 65535 0]Todo o pessoal é aconselhado a evacuar[n]imediatamente uma área segura da instalação.[n][f 1 3 65535][w][e]

[msg MSG_001_8_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]O que no mundo!?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Shadow Okumura's Voice]]
[s][vp 8 0 0 7 65535 0]Não há tempo para lidar com vocês ladrões.[n]Eu devo estar fazendo minha saída.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 8 65535 0]Todos vocês podem ficar de pé e assistir em[n]desespero enquanto desce junto com esta[n]base![n][f 1 3 65535][w][e]
[s][vp 8 0 0 9 65535 0]Sua destruição é iminente![n][f 1 3 65535][w][e]
[s][vp 8 0 0 10 65535 0]Hahahahahahahaha![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Não há tempo! Precisamos nos apressar![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][bup 0 8 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Por aqui![n][f 1 3 65535][w][e]

