[msg MSG_000_0_0 [(SE)自動音声(♀)]]
[s][vp 8 0 0 1 65535 0]4... 3... 2... 1...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 2 65535 0]...O fim...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Ufa... meu coração ainda está batendo...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]* suspiro* Fizemos um ótimo trabalho lá.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Você sabe, Morgana, você parecia quase[n]normal quando tomou o tesouro.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Oh?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]A verdade por trás dos desligamentos mentais[n]permanece sem solução. Okumura não era o[n]culpado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]Ainda assim, ele mencionou solicitar que as[n]pessoas fossem eliminadas. Ele tem que[n]saber quem é responsável.[n][f 1 3 65535][w][e]

[msg MSG_007_3_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]Milímetros...[n][f 1 3 65535][w][e]

[msg MSG_007_6_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]Mãe...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]É isto...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Seu tesouro... era um kit de modelo de[n]plástico?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Qual é o problema?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Lembro-me do pai me dizendo algo antes que[n]ele mudasse...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Ele disse que havia um kit de modelo que ele[n]realmente queria quando criança.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Mas não importa o quanto ele implorasse ao[n]meu avô, ele nunca conseguiu.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Sua família pode ficar parecida com milhares[n]desses kits.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]A Okumura Foods existe há gerações, mas era[n]uma pequena empresa até que meu pai assumiu[n]o controle.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Meu avô era um bom homem, mas não o melhor[n]empresário. Ele até emprestaria dinheiro[n]sem garantia...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Parece que os cobradores de dívidas eram uma[n]presença frequente quando meu pai era[n]jovem...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Deve ser por que...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Por que Okumura estava tão disposto a[n]perseguir sua própria felicidade às custas[n]dos outros.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Futaba]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 8 7 300 1][vp 8 0 0 24 65535 0]Uau!?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Essa coisa é insana...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]É um preço impressionante. Ouvi dizer que[n]isso pode acontecer com os itens do[n]colecionador, mas ainda assim...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]As pessoas vão pagar muito por um brinquedo[n]de plástico!?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]A propósito... quando exatamente a mudança[n]de coração deve acontecer?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Em breve. Isso é tudo que sabemos.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]Vamos ter que esperar e ver o que acontece[n]até então.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]Uma vez que ele mude de coração, certamente[n]seremos capazes de descobrir quem está por[n]trás dos desligamentos mentais.[n][f 1 3 65535][w][e]

