[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Na verdade, tenho pensado um pouco sobre[n]minhas ações desta vez...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Eu estava muito preocupado com quem eu sou e[n]como não comparo com os outros membros do[n]nosso grupo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Acontece que eu simplesmente não tenho[n]coragem, hein?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Está bem.[e]
[s]Isso acontece com todos.[e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Vamos lá, eu te conheço tempo suficiente.[n]Não há necessidade de ser modesto.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Obrigado.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Eu acho que a razão pela qual eu estava tão[n]desligado que querer ser humano é porque eu[n]precisava de um objetivo próprio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Bem, não um objetivo em si, mas algo[n]maior... acho que mais... um motivo para[n]viver.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Mas agora que tenho certeza de que pertenço[n]aos ladrões Phantom, sei o que quero fazer.[n]Você sabe o que é isso?[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]Nos tornar mais famosos?[e]
[s]Obter seu próprio quarto?[e]
[s]Não sei.[e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]O que mais, certo?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Isso também, eventualmente.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Vou fazer o que puder para garantir que os[n]ladrões Phantom tenham sucesso.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Em outras palavras, nossos objetivos estão[n]alinhados.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 10 301 1][vp 8 0 0 15 65535 0]De agora em diante, não vou segurar nada.[n][f 1 3 65535][w][e]

[msg MSG_011_5_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]É melhor você se esforçar também![n]Não me faça lamentar minha escolha![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Além disso... eu quero que Lady Ann seja[n]feliz.[n][f 1 3 65535][w][e]
[s][bup 0 3 8 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Se minhas ações podem ajudá-la a alcançar a[n]felicidade, isso é mais do que suficiente[n]para mim...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Espero que você não esteja pensando em como[n]tudo isso é saboroso![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 1 0 0 0 0 0]Eu sinto que meu vínculo com Morgana está[n]crescendo mais fundo...[n][f 1 3 65535][w][e]

