[msg MSG_000_0_0 [Newscaster]]
[s][vp 8 0 0 1 65535 0]Isso conclui o discurso dado pelo[n]representante Masayoshi Shido, que pode[n]estar formando um novo partido.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][vp 1 0 0 2 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Newscaster]]
[s][vp 8 0 0 3 65535 0]Agora retomamos nossa cobertura dos ladrões[n]Phantom, os suspeitos pela morte de Okumura[n]e outros.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 4 65535 0]A polícia designou os ladrões Phantom como[n]os fugitivos mais procurados do país...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 5 65535 0]E decidiram recompensar qualquer pessoa com[n]informações que levassem à captura dos[n]ladrões Phantom.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Olhar.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Newscaster]]
[s][vp 8 0 0 7 65535 0]Aqueles que fornecem informações receberão[n]uma recompensa de trinta milhões de ienes...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 8 65535 0]E, considerando a quantidade alta, mostra o[n]quão extraordinário a situação se tornou.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 9 65535 0]O dinheiro da recompensa será fornecido pela[n]polícia e pelas famílias das vítimas, mais- [n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Se eu denunciá-lo à polícia e eles o[n]prendem, supostamente recebo trinta milhões[n]de ienes por isso.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]Isso é insano...[e]
[s]Você vai nos denunciar?[e]
[s]Somente se formos pegos.[e]

[msg MSG_007_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Espero que você entenda a situação em que[n]está.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Mesmo pessoas que não tinham interesse antes[n]estarão à procura dos ladrões Phantom.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]E isso vai acontecer todos os dias, mesmo na[n]escola.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]...Por quê isso aconteceu?[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Eu sinto Muito.[e]
[s]Não houve escolha.[e]
[s]Eu não sabia que sim.[e]

[msg MSG_010_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Isso não é sobre mim.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Isso pode ter sido verdade, mas ainda[n]assim...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Eu vejo...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Bem, como eu coloco isso...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Lamento não ter percebido. Também é minha[n]responsabilidade que isso aconteceu.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Tudo o que posso fazer agora é lhe dar[n]abrigo.[n][f 1 3 65535][w][e]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Só não fique desesperado e faça algo[n]imprudente, tudo bem?[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]Eu sei.[e]
[s]Não se preocupe.[e]
[s]Acredite em mim.[e]

[msg MSG_015_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Eu não vou te vender. Enquanto você estiver[n]aqui, não há nada com que se preocupar.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Eu me sinto mal com o que fizemos com o[n]chefe. Eu também sou responsável.[n][f 1 3 65535][w][e]

