[msg MSG_000_0_0 [Frightened Student]]
[s][vp 8 0 0 1 28 0]A polícia está aqui de novo?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Irritated Student]]
[s][vp 8 0 0 2 15 0]Sim, parece que é real desta vez.[n]Aparentemente, um de nossos alunos é um[n]ladrão fantasma.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Frightened Student]]
[s][vp 8 0 0 3 28 0]A sério!?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Irritated Student]]
[s][vp 8 0 0 4 15 0]Eu li a mesma coisa online. Aparentemente, a[n]segurança pública já está em movimento...[n][f 1 3 65535][w][e]

