[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Peço desculpas pela interrupção.[n]Há um compromisso urgente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Então, peço desculpas profundamente...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Mas hoje tenho que encerrar aqui.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [(SE)講演会に来た人々]]
[s][vp 8 0 0 0 65535 0](『え~!?』というような『いいとも』的な声)[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Para compensar o tempo reservado[n]para esta reunião, o[n]rakugo research club...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [(SE)講演会に来た人々]]
[s][vp 8 0 0 0 65535 0](『マジ?』『いらねー』などのブーイング)[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Não posso elaborar os detalhes[n]da investigação dos Ladrões[n]Phantom...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Mas sinto que em breve[n]um novo passo será dado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Espero que você continue[n]interessado na história.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Dê uma salva de palmas ao nosso convidado[n]hoje, Goro Akechi.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [(SE)講演会に来た人々]]
[s][vp 8 0 0 0 65535 0](拍手)[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Nós realmente[n]fizemos a melhor coisa?[n][f 1 3 65535][w][e]

[msg MSG_009_3_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Ele virou[n]a ideia de Makoto contra nós.[n][f 1 3 65535][w][e]

[msg MSG_009_5_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Exatamente. Queríamos[n]obter informações, mas ele[n]virou o jogo.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]E daí? Aceitamos o seu[n]"acordo"?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Ele tem provas contra nós.[n]Não temos escolha...[n][f 1 3 65535][w][e]

[msg MSG_011_3_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Merda, que porra a gente faz?[n][f 1 3 65535][w][e]

[msg MSG_011_5_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Acalme-se, Ryuji.[n][f 1 3 65535][w][e]

[msg MSG_011_7_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Como diabos você quer que eu me acalme?[n]Que porra vamos fazer?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]O que está feito está feito. Devemos[n]acalmar e refletir mais[n]sobre esse assunto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Quando ele nos contatar novamente,[n]devemos ter decidido.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Sim, temos que pensar nisso[n]difícil...[n][f 1 3 65535][w][e]

