[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]Amanhã é o grande dia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Nós apenas temos que conduzir[n]a operação que Makoto[n]planejou.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 53105 65535 0]Nós apenas temos que entregá-lo.[n]Até chegarmos[n]a Niijima...[n][f 1 3 65535][w][e]

