[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Que jogo será desta vez?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Iremos vencer independentemente.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ombra di Sae]]
[s][bup 0 105 100 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Se você acha que[n]me encurralou, está cometendo um[n]grave erro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Eu só trouxe você aqui porque[n]podemos lutar como eu[n]quiser.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Irmã...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ombra di Sae]]
[s][bup 0 105 105 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Quando meu pai morreu em[n]serviço, eu odiei seu[n]assassino de todo o coração.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ombra di Sae]]
[s][bup 0 105 102 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Morrer servindo a justiça[n]parece nobre, mas são os que ficam[n]que têm que juntar os cacos![n][f 1 3 65535][w][e]

[msg MSG_008_5_0 [Ombra di Sae]]
[s][bup 0 105 102 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Você pode imaginar o que[n]eu tive que suportar?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 103 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Talvez eu a tenha superestimado.[n]Achei que o raciocínio dela[n]teria sido mais nobre.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Ele perdeu o controle...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Não é bom...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ombra di Sae]]
[s][bup 0 105 102 0 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]A justiça não pode se curvar[n]ao mal! Eu tenho que vencer a[n]qualquer custo![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Akechi]]
[s][bup 0 9 103 0 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Isso é apenas arrogância...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ombra di Sae]]
[s][bup 0 105 100 0 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]A única maneira de descobrir[n]quem está certo... é lutar.[n][f 1 3 65535][w][e]

