[msg MSG_GREET_RESERVE_1]
[s][vp 1 0 0 0 0 0]Dammit... I wanna go home...[n][f 1 3 65535][w][e]

[msg MSG_GREET_RESERVE_2]
[s][vp 1 0 0 0 0 0]I don't wanna go to school...[n]This sucks...[n][f 1 3 65535][w][e]

[msg MSG_GREET_RESERVE_3]
[s][vp 1 0 0 0 0 0]I'm so tired every day...[n][f 1 3 65535][w][e]

[msg MSG_GREET_RESERVE_4]
[s][vp 1 0 0 0 0 0]I don't want to go to work...[n][f 1 3 65535][w][e]

[msg MSG_GREET_RESERVE_5]
[s][vp 1 0 0 0 0 0]Are there any[n]breaks coming up?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0812_1]
[s][vp 1 0 0 0 0 0]Only 10 days left until[n]Medjed's deadline...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0812_2]
[s][vp 1 0 0 0 0 0]What are the Phantom[n]Thieves doing?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0812_3]
[s][vp 1 0 0 0 0 0]Are they just going to[n]let Medjed have their way?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0812_4]
[s][vp 1 0 0 0 0 0]What is Medjed trying to do?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0812_5]
[s][vp 1 0 0 0 0 0]Is this going to affect us?[n]We have nothing to do[n]with this...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0821_1]
[s][vp 1 0 0 0 0 0]Apparently some ATMs[n]aren't working...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0821_2]
[s][vp 1 0 0 0 0 0]I heard someone's[n]tampering with the[n]system.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0821_3]
[s][vp 1 0 0 0 0 0]Is it Medjed?[n]No, it couldn't be...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0821_4]
[s][vp 1 0 0 0 0 0]What are the police doing?[n]They're so incompetent...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0821_5]
[s][vp 1 0 0 0 0 0]Even the Phantom Thieves[n]couldn't stop them...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0824_1]
[s][vp 1 0 0 0 0 0]Did the Phantom Thieves[n]start all these scandals, too?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0824_2]
[s][vp 1 0 0 0 0 0]No, I don't think those[n]had calling cards...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0824_3]
[s][vp 1 0 0 0 0 0]You know, like,[n]changing people's hearts[n]from the shadows![n][f 1 3 65535][w][e]

[msg MSG_GREET_0824_4]
[s][vp 1 0 0 0 0 0]That's so manly! I'm[n]totally falling for them.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0824_5]
[s][vp 1 0 0 0 0 0]Maybe I should make a[n]request on that forum too...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1002_1]
[s][vp 1 0 0 0 0 0]I can't wait for his[n]public apology![n][f 1 3 65535][w][e]

[msg MSG_GREET_1002_2]
[s][vp 1 0 0 0 0 0]They should just execute[n]everyone who causes[n]trouble for society.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1002_3]
[s][vp 1 0 0 0 0 0]Ooh, maybe they could[n]take down my boss![n][f 1 3 65535][w][e]

[msg MSG_GREET_1002_4]
[s][vp 1 0 0 0 0 0]Politicians who knock the[n]Phantom Thieves are[n]just sore losers.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1002_5]
[s][vp 1 0 0 0 0 0]What about Akechi-kun?[n]Is he too afraid of[n]backlash to comment?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1016_1]
[s][vp 1 0 0 0 0 0]They still haven't caught[n]the Phantom Thieves?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1016_2]
[s][vp 1 0 0 0 0 0]I don't care how they[n]do it. Just throw them[n]in the slammer already.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1016_3]
[s][vp 1 0 0 0 0 0]It's too scary to have[n]murderers on the loose...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1016_4]
[s][vp 1 0 0 0 0 0]I wonder what kind of[n]people the culprits are.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1016_5]
[s][vp 1 0 0 0 0 0]They're murderers. Don't[n]give me any of this "justice"[n]crap.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1201_1]
[s][vp 1 0 0 0 0 0]I heard Shido's approval[n]rating went up again.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1201_2]
[s][vp 1 0 0 0 0 0]This election's[n]already decided![n][f 1 3 65535][w][e]

[msg MSG_GREET_1201_3]
[s][vp 1 0 0 0 0 0]I mean, I can't imagine[n]anyone but Shido in office.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1201_4]
[s][vp 1 0 0 0 0 0]It'd be nice to have[n]a strong country.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1201_5]
[s][vp 1 0 0 0 0 0]Shido has this in the bag![n]I can't wait for the election.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1215_1]
[s][vp 1 0 0 0 0 0]That damn circus is[n]happening soon.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1215_2]
[s][vp 1 0 0 0 0 0]It's almost election day.[n]I'm getting excited![n][f 1 3 65535][w][e]

[msg MSG_GREET_1215_3]
[s][vp 1 0 0 0 0 0]We'll definitely get all[n]300 seats in parliament...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1215_4]
[s][vp 1 0 0 0 0 0]If you care about this[n]country, you should[n]vote for Shido.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1215_5]
[s][vp 1 0 0 0 0 0]We're with you, Shido![n]Hurry up and become[n]prime minister![n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1201_]
[s][vp 1 0 0 0 0 0]That phantom thief is still[n]alive? Is this for real?[n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1201__2]
[s][vp 1 0 0 0 0 0]They have to be lying.[n]There's no proof.[n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1201__3]
[s][vp 1 0 0 0 0 0]His approval rating[n]is still the same.[n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1201__4]
[s][vp 1 0 0 0 0 0]I mean, I can't imagine[n]anyone but Shido in office.[n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1201__5]
[s][vp 1 0 0 0 0 0]Shido's gonna win![n]I hope he becomes[n]prime minister soon...[n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1215_]
[s][vp 1 0 0 0 0 0]That damn circus is[n]happening soon.[n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1215__2]
[s][vp 1 0 0 0 0 0]It's almost election day.[n]I'm getting excited![n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1215__3]
[s][vp 1 0 0 0 0 0]Is Shido-san okay? We haven't[n]heard from him since then...[n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1215__4]
[s][vp 1 0 0 0 0 0]He's strong. He'll[n]be back in no time![n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1215__5]
[s][vp 1 0 0 0 0 0]We're with you, Shido![n]Hurry up and become[n]prime minister![n][f 1 3 65535][w][e]

[msg MSG_GREET_0107_1]
[s][vp 1 0 0 0 0 0]My little sister's been telling[n]me to fix her PC... She's[n]always been the bossy type.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0107_2]
[s][vp 1 0 0 0 0 0]Study abroad? No thanks.[n]I'm having a great time here.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0107_3]
[s][vp 1 0 0 0 0 0]You work at a maid café!?[n]Wow, I never would have[n]guessed with you...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0107_4]
[s][vp 1 0 0 0 0 0]Huh? Really? It's the[n]best job I've ever had![n][f 1 3 65535][w][e]

[msg MSG_GREET_0107_5]
[s][vp 1 0 0 0 0 0]Have the store attendants[n]here always been so friendly?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0122_1]
[s][vp 1 0 0 0 0 0]Am I an idol...? No, not me.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0122_2]
[s][vp 1 0 0 0 0 0]My mom lets me play games.[n]We even play them together![n][f 1 3 65535][w][e]

[msg MSG_GREET_0122_3]
[s][vp 1 0 0 0 0 0]I'm not going to get a[n]facelift! I like my face.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0122_4]
[s][vp 1 0 0 0 0 0]Oh? I thought you said your[n]nose was... Sorry, never mind.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0122_5]
[s][vp 1 0 0 0 0 0]I don't mind the pay...[n]as long as I can buy[n]my trading cards.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0129_1]
[s][vp 1 0 0 0 0 0]You've changed somehow.[n]Like, you're more dependable[n]than you were before...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0129_2]
[s][vp 1 0 0 0 0 0]I like playing the maid.[n]I don't think I can hold[n]an office job...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0129_3]
[s][vp 1 0 0 0 0 0]Your own shop? Forget it. No[n]matter how hard you work,[n]it can still give you trouble.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0129_4]
[s][vp 1 0 0 0 0 0]Was I always like this...? ...Huh?[n]Oh, it's nothing![n][f 1 3 65535][w][e]

[msg MSG_GREET_0129_5]
[s][vp 1 0 0 0 0 0]I'm so glad to have a pet[n]like Leo! We'll be together[n]forever, won't we?[n][f 1 3 65535][w][e]

