[msg TEST_000]
[s]スクリプトから発行した[n]メッセージです。[n][w][e]

[msg MSG_MORU_0113_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1170 65535 0]Ainda ha pessoas em apuros[n]la fora, hein?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]... isso pode significar que ainda existem[n]Alguns alvos deixados em lembrancas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Se existem ou nao, e melhor[n]Esteja preparado para qualquer coisa 悪 Quem sabe[n]o que pode acontecer.[n][f 1 3 65535][w][e]

