[sel YESNO_SEL top]
[s]Sim [e]
[s]Não [e]

[msg MSG_000_000_00]
[s]Fictício [n][w][e]

[msg MSG_STAFF_JR_TALK_000_00 [Station Attendant]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]Pedimos desculpas pelo inconveniente durante[n]esse período movimentado! A linha JL está[n]muito fora do cronograma hoje.[n][w][e]
[s][vp 8 2 1 0 851 0]A linha Ginza? Que está localizado no [clr 2]Edifício Teikyu [clr 27]próxima porta.[n][w][e]

[msg MSG_STAFF_JR_GREET_000_0]
[s][vp 8 2 1 0 851 0][clr 2]Os trens não estão funcionando como[n]programado [n][clr 27].[n]Pedimos desculpas pela inconveniência![n][f 1 2 65535][e]

[msg MSG_STAFF_JR_GREET_000_0_2]
[s][vp 8 2 1 0 851 0][clr 28]Os trens não estão funcionando [clr 27][n][clr 28]conforme marcado [clr 27]. Pedimos desculpas pela inconveniência![n][f 1 2 65535][e]

[msg MSG_STAFF_PARK_TALK_000_ [Busy Station Worker]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]Os trens estão fora do cronograma hoje por[n]causa do acidente de metrô ontem...[n][w][e]
[s][vp 8 2 1 0 850 0]Para a linha JL, vá para o portão de[n]ingressos passando aqui no lado esquerdo.[n][w][e]
[s][vp 8 2 1 0 850 0]Para os metrôs, vá para o distrito[n]subterrâneo das escadas centrais.[n][w][e]
[s][vp 8 2 1 0 850 0]Para a linha Ginza, suba as escadas para o [clr 2]Taikyu Building Next Door [clr 27].[n][w][e]

[msg MSG_STAFF_PARK_GREET_000]
[s][vp 8 2 1 0 850 0]Esta área é extremamente [n][clr 2]superlotado [clr 27]agora mesmo![n][f 1 2 65535][e]

[msg MSG_STAFF_PARK_GREET_000_2]
[s][vp 8 2 1 0 850 0]Esta área é extremamente [n][clr 2]superlotado [clr 27]agora mesmo![n][f 1 2 65535][e]

[msg MSG_STAFF_STBLDG_TALK_00 [Sleepy Station Attendant]]
[s][f 4 23 1 852 3 10 0 0][vp 8 2 1 0 852 0]As escadas descendo estão atualmente muito[n]lotadas![n][w][e]
[s][vp 8 2 1 0 852 0]Se você planeja usar o metrô, use as escadas[n]centrais.[n][w][e]
[s][vp 8 2 1 0 852 0]... Eu tive que ficar acordado até tarde da[n]noite passada também.[n]Dê-me uma pausa de tudo isso já...[n]*yaaawn* [n][w][e]
[s][vp 8 2 1 0 852 0]Para a linha JL, vá para o quadrado e siga[n]para a direita. A linha Ginza é [n][clr 2]até essas escadas [clr 27]por aqui.[n][w][e]

[msg MSG_STAFF_STBLDG_GREET_0]
[s][vp 8 2 1 0 852 0]As escadas descendo são extremamente [clr 2]superlotado [clr 27]agora mesmo...[n][f 1 2 65535][e]

[msg MSG_STAFF_STBLDG_GREET_0_2]
[s][vp 8 2 1 0 852 0]As escadas descendo são extremamente [clr 2]superlotado [clr 27]agora mesmo...[n][f 1 2 65535][e]

