[sel YESNO_SEL top]
[s]Sim [e]
[s]Não [e]

[msg MSG_654_103_00]
[s]Fictício [n][w][e]

[msg MSG_SINGAKU_NPC_020_0 [Female Student in a Jersey]]
[s][f 4 23 1 810 3 10 0 10][vp 8 2 1 0 810 0]Todo mundo está de bom humor desde a virada[n]do ano novo. É estranho.[n]Aconteceu alguma coisa?[n][w][e]

[msg MSG_SINGAKU_NPC_021_0 [Lighthearted Female Student]]
[s][f 4 23 1 811 3 10 0 10][vp 8 2 1 0 811 0]Ouvi todos os seus desejos, todos estão[n]felizes que todos os seus desejos se[n]tornaram realidade. Então é provavelmente[n]isso, certo?[n][w][e]

[msg MSG_SINGAKU_NPC_022_0 [Female Student in a Jersey]]
[s][vp 8 2 1 0 810 0]Hmm... mas, estar muito feliz pode nem[n]sempre ser uma coisa boa. Você tem que[n]estar motivado para ganhar uma partida![n][w][e]

[msg MSG_SINGAKU_NPC_023_0 [Lighthearted Female Student]]
[s][f 4 23 1 811 3 10 0 10][vp 8 2 1 0 811 0]Parece que você está conversando com seu[n]namorado no time de futebol um pouco demais.[n][w][e]
[s]Vamos lá, ser feliz é uma coisa boa![n][w][e]

