[sel YESNO_SEL top]
[s]Sim [e]
[s]Não [e]

[msg MSG_000_000_00]
[s]Fictício [n][w][e]

[msg MSG_064_0_0 [Motivated First-Year]]
[s][vp 1 0 0 0 0 0]Cara, eu vi alguém muito bonito por aqui![n]Ela era como uma modelo![n][w][e]

[msg MSG_065_0_0 [Energetic First-Year]]
[s][vp 1 0 0 0 0 0]Você quer dizer Takamaki-senpai? Ela é[n]famosa. Ouvi dizer que ela costumava morar[n]no exterior e até modelos para anúncios...[n][w][e]

[msg MSG_066_0_0 [Motivated First-Year]]
[s][vp 1 0 0 0 0 0]Eu gostaria de poder conhecê-la, mas ela[n]parece quase impossível de se aproximar.[n][w][e]

[msg MSG_067_0_0 [Energetic First-Year]]
[s][vp 1 0 0 0 0 0]Concordou. Ela também se destaca totalmente.[n]Aparentemente, alguns terceiros anos[n]precisam ficar de olho nela.[n][w][e]

[msg MSG_068_0_0 [Motivated First-Year]]
[s][vp 1 0 0 0 0 0]O que!? Quão assustador... acho que é o que[n]acontece se você se destacar tanto quanto[n]ela...[n][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Finalmente encontrei você. Eu tenho um favor[n]a perguntar.[n][w][e]

[msg MSG_027_0_0 [Agitated Volleyball Player]]
[s][vp 1 0 0 0 0 0]S-sakamoto... eu sabia que você apareceria[n]para mim...[n][w][e]
[s][vp 1 0 0 0 0 0]Olha, eu tenho que torcer pelo Sr.[n]Kamoshida, então seria ótimo se isso[n]pudesse esperar até mais tarde.[n][w][e]

[msg MSG_028_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Ele é quem lhe deu essas lesões, certo?[n]Queremos acusá-lo, então precisamos de[n]vítimas.[n][w][e]
[s][vp 1 0 0 0 0 0]Você realmente quer deixar aquele bastardo[n]correr de graça? Estou implorando para nos[n]ajudar![n][w][e]

[sel SEL_029_0_0 top]
[s]Ajude-nos.[e]
[s]Não ignore isso.[e]

[msg MSG_030_0_0 [Agitated Volleyball Player]]
[s][vp 1 0 0 0 0 0]... Desculpe, mas você terá que procurar[n]outra pessoa.[n][w][e]
[s][vp 1 0 0 0 0 0]Eu quero me formar sem problemas...[n]Prefiro não acabar como você.[n][w][e]
[s][vp 1 0 0 0 0 0]Se eu for do lado ruim do Sr. Kamoshida, não[n]vou fugir. Você sabe o quão influente ele[n]é, certo...?[n][w][e]

[msg MSG_031_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Droga, a boca está ficando fechada.[n]Tudo- causa dos truques sujos desse[n]bastardo...[n][w][e]

[msg MSG_031_5_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Acho que precisamos passar para o próximo.[n]Eu não estou dando para cima...[n][w][e]

[msg MSG_078_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Não está trabalhando. Todo mundo cale a boca[n]no momento em que mencionamos o nome de[n]Kamoshida.[n][w][e]
[s][vp 1 0 0 0 0 0]Droga... o que devemos fazer!?[n][w][e]

[sel SEL_079_0_0 top]
[s]Vamos descansar um pouco.[e]
[s]Isto é tudo culpa sua.[e]

[msg MSG_080_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Sim, acho que não machucaria tomando um[n]respiro e repensando nossa estratégia por[n]enquanto.[n][w][e]
[s][vp 1 0 0 0 0 0]Vamos, vamos pegar algo para beber no pátio.[n][w][e]

[msg MSG_081_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Não diga isso. Você é aquele com o registro[n]criminal...[n][w][e]
[s][vp 1 0 0 0 0 0]Er, quero dizer registro de prisão. Não é[n]criminoso.[n][w][e]
[s][vp 1 0 0 0 0 0]...Desculpe.[n][w][e]
[s][vp 1 0 0 0 0 0]Vamos lá, vou comprar um pouco de suco para[n]compensar isso. Vamos descer para o pátio.[n][w][e]

[msg MSG_032_0_0 [Agitated Volleyball Player]]
[s][vp 1 0 0 0 0 0]Por que você está tentando provocar[n]problemas?[n]Todo mundo está bem com as coisas como elas[n]são...[n][w][e]
[s][vp 1 0 0 0 0 0]Você deve saber melhor do que ninguém...[n]O status quo é o caminho a percorrer.[n][w][e]

