[sel YESNO_SEL top]
[s]Sim[e]
[s]Não[e]

[msg MSG_DET_INFO_GOT_ENOUGH [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Acho que é hora de[n]voltar para Taihei agora.[n][w][e]

[msg MSG_DET_INFO_GOT_ALL [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Acho que já descobrimos[n]tudo o que é possível.[n]Vamos para Taihei.[n][w][e]

[msg MSG_DET_INFO_NEXT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Vamos tentar descobrir[n]algo mais.[n][w][e]

[msg MSG_DET_MISHIMA_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][f 4 23 1 802 3 10 0 10]Oh espere! Não me diga...[n][w][e]
[s]De acordo com minha pesquisa,[n]você está coletando informações[n]sobre o prof. Kawakamis...[n][w][e]
[s]E você quer que eu faça isso,[n]em seu lugar?[n][w][e]

[sel SEL_DET_MISHIMA_01 top]
[s]pode me ajudar?[e]
[s]O que você quer dizer?[e]

[msg MSG_DET_MISHIMA_02 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][f 4 23 1 802 3 10 0 10]Sim, deixe comigo.[n][w][e]
[s]Espere e veja! Terei o que você precisa em dez[n]minutos![n][w][e]

[msg MSG_DET_MISHIMA_03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Os dez minutos se passaram. Quem sabe[n]o que aconteceu com Mishima...[n][w][e]

[msg MSG_DET_MISHIMA_04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Hmm, aparentemente[n]é muito confiável.[n][w][e]

[msg MSG_DET_MISHIMA_10 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][f 4 23 1 802 3 10 0 10]Apenas me diga quando precisar de ajuda.[n][w][e]
[s]Eu vou te mostrar o quanto eu posso ser útil![n][w][e]

[msg MSG_DET_MISHIMA_50 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Acho que temos tudo[n]que precisamos, mesmo sem Mishima.[n][w][e]
[s]Vamos, vamos para Taihei.[n][w][e]

[msg MSG_DET_MISHIMA_51 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][f 4 23 1 802 3 10 0 10]O que...? Um erro?[n][w][e]
[s]Estranho... Talvez minhas informações[n]não fossem precisas...[n][w][e]

