[sel YESNO_SEL top]
[s]Sim[e]
[s]Não[e]

[msg MSG_000_000_00]
[s]Fictício[n][w][e]

[msg MSG_E24330100_STUDENT_F_ [Studentessa della Kosei]]
[s][f 4 23 1 854 3 10 0 0][vp 8 2 1 0 854 0]Ei, eu estava em um fórum outro dia[n]e de repente vi este post:[n]"10K Piece at HQ".[n][w][e]

[msg MSG_E24330100_STUDENT_F__2 [Studentessa in divisa da marinaio]]
[s][f 4 23 1 853 3 10 0 0][vp 8 2 1 0 853 0]Huh? Mas o que é isso? Um código?[n]Parece um pouco suspeito...[n][w][e]

[msg MSG_E24330100_STUDENT_F__3 [Studentessa della Kosei]]
[s][f 4 23 1 854 3 10 0 0][vp 8 2 1 0 854 0]Já. Muitas pessoas têm[n]conversas assim,[n]online...[n][w][e]

[msg MSG_E24330100_STUDENT_F__4 [Studentessa in divisa da marinaio]]
[s][f 4 23 1 853 3 10 0 0][vp 8 2 1 0 853 0]O que ele estava dizendo?[n][w][e]

[msg MSG_E24330100_STUDENT_F__5 [Studentessa della Kosei]]
[s][f 4 23 1 854 3 10 0 0][vp 8 2 1 0 854 0]Talvez esta seja terminologia específica? De[n]qualquer forma, não tem nada a ver conosco.[n][w][e]

[msg MSG_E24330100_ANN_001_00 [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 6032 65535 0]Desculpe, [f 4 2]. Aqui[n]não há nada.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Olha, alguém está fazendo perguntas[n]para um vídeo, perto dos trens...[n]Mas acho que é um trabalho de modelo.[n][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]De qualquer forma, não estou aqui.[n]Vá ver o que Ryuji e Yusuke[n]descobriram.[n][w][e]

[msg MSG_E24330100_ANN_101_00 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 6166 65535 0]Talvez eles estejam fazendo seleções[n]para uma agência? Não tem[n]nada a ver com drogas.[n][w][e]

[msg MSG_E24330100_ANN_102_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Este não é o lugar certo.[n]Vamos, vamos perguntar aos outros[n]o que eles descobriram.[n][w][e]

[msg MSG_E24330100_SCOUT_001_ [Talent scout spensierato]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]Quinhentos mil ienes por um vídeo.[n]E você pode até ganhar mais,[n]se ficar famoso...[n][w][e]

[sel SEL_E24330100_SCOUT_002_ top]
[s]Eu poderia fazer vídeos.[e]
[s]Me diga mais.[e]

[msg MSG_E24330100_SCOUT_003_ [Talent scout spensierato]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]Huh? Você quer... aparecer[n]em um de nossos vídeos?[n][w][e]
[s][vp 8 2 1 0 850 0]Acho que alguns podem[n]gostar, mas ... nós só contratamos[n]meninas. Sinto muito.[n][w][e]

[msg MSG_E24330100_SCOUT_004_ [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]...Aparecer em um vídeo?[n]Que tipo de trabalho seria esse?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]De qualquer forma, não acho que tenha[n]nada a ver com drogas.[n]Não acho que tenha a ver com ele.[n][w][e]

[msg MSG_E24330100_SCOUT_102_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Ele não é a pessoa que estamos procurando. Vamos[n]verificar em outro lugar.[n][w][e]

[msg MSG_E24330100_TELLADY_00 [Donna al telefono]]
[s][vp 8 2 1 0 852 0]Preparar? Cheguei em Shibuya[n]sem problemas...[n][w][e]
[s][vp 8 2 1 0 852 0]Mas havia um sem-teto[n]em nosso ponto de encontro.[n]Eu tive que fugir.[n][w][e]
[s][vp 8 2 1 0 852 0]Sim, uma vez ele desceu as escadas[n]após as catracas do JL... Estou[n]na praça agora. Eu estava com medo...[n][w][e]
[s][vp 8 2 1 0 852 0]Ele estava sentado perto da parede...[n]S-sim, hmm...[n][w][e]

[msg MSG_E24330100_TELLADY_10 [Donna al telefono]]
[s][vp 8 2 1 0 852 0]Sim, você o vê sentado lá[n]enquanto descia as escadas...[n]É assustador...[n][w][e]

[msg MSG_E24330100_MAKOTO_001 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 2120 65535 0]Você está trabalhando duro.[n]Encontrou alguma coisa?[n][w][e]

[sel SEL_E24330100_MAKOTO_002 top]
[s]Estou à procura de alguém.[e]
[s]Sem comentários.[e]

[msg MSG_E24330100_MAKOTO_003 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 2117 65535 0]Hum...? Você está procurando por um morador de[n]rua?[n][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]É uma boa ideia. Eles provavelmente[n]sabem muito sobre o que[n]acontece na cidade.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu não vi nenhum aqui, mas aposto[n]que na masmorra[n]haverá...[n][w][e]

[msg MSG_E24330100_MAKOTO_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1163 0 0]A masmorra... Não estou entusiasmado com a ideia,[n]mas devemos ir dar uma olhada.[n][w][e]

[msg MSG_E24330100_MAKOTO_003_2 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu sei quando não sou querido.[n]Não vou atrapalhar.[n][w][e]

[msg MSG_E24330100_MAKOTO_101 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2120 65535 0]Você precisa de mais alguma coisa?[n][w][e]

[msg MSG_E24330100_MAKOTO_102 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Deixe-a em paz. Temos que encontrar um sem-teto,[n]lembra?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Mas não vejo nenhum aqui.[n]Vamos para a masmorra.[n][w][e]

