[sel charaorder_se top]
[s]Sim[e]
[s]Não[e]

[msg charaorder_Hero_00]
[s]Devemos tentar jogar tinta em Madarame...?[n][w][e]

[msg charaorder_Hero_01]
[s]Fictício[n][w][e]

[msg charaorder_Reiji_00 [Ryuji]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1031 0 2]Temos que enchê-lo com tinta, hein?[n][w][e]

[msg charaorder_Reiji_01 [Ryuji]]
[s][vp 8 0 2 1072 0 2][f 4 10 65535 0 0]Eu vou quando você quer, cara![n][w][e]

[msg charaorder_Morgana_00 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Vamos pintá-lo com tinta![n][w][e]

[msg charaorder_Morgana_01 [Morgana]]
[s][vp 8 0 2 1073 0 3][f 4 10 65535 0 0]Deixe para mim![n][w][e]

[msg charaorder_Ann_00 [Ann]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1035 0 4]Temos que revestir com tinta![n][w][e]

[msg charaorder_Ann_01 [Ann]]
[s][vp 8 0 2 1074 0 4][f 4 10 65535 0 0]Estou pronto![n][w][e]

[msg charaorder_Yugo_00 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1037 0 5]Hora de deixá-los experimentar a humilhação[n]de serem cobertos de tinta…![n][w][e]

[msg charaorder_Yugo_01 [Yusuke]]
[s][vp 8 0 2 1075 0 5][f 4 10 65535 0 0]Eu farei. Deixe para mim.[n][w][e]

[msg charaorder_Makoto_00]
[s]Dummy datCharaOrder[n][w][e]

[msg charaorder_Makoto_01 [Yusuke]]
[s]Dummy datCharaOrder[n][w][e]

[msg charaorder_Ranko_00]
[s]Dummy datCharaOrder[n][w][e]

[msg charaorder_Ranko_01 [Yusuke]]
[s]Dummy datCharaOrder[n][w][e]

[msg charaorder_Hutaba_00]
[s]Dummy datCharaOrder[n][w][e]

[msg charaorder_Hutaba_01 [Yusuke]]
[s]Dummy datCharaOrder[n][w][e]

[msg charaorder_Akechi_00]
[s]Dummy datCharaOrder[n][w][e]

[msg charaorder_Akechi_01 [Yusuke]]
[s]Dummy datCharaOrder[n][w][e]

