[msg MSG_MISHIMA_PRE_COOP_00 [Mishima]]
[s][bup 0 111 505 65535 0][f 4 23 1 238 14 10 13 10][f 4 10 65535 0 0][vp 8 2 1 19027 65535 0][f 4 1]... Eu não pensei que[n]iria terminar assim ...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E agora o que eu faço...?[n]Se Kamoshida continuar[n]em cima de mim, é o fim para mim...[n][w][e]

[msg MSG_MISHIMA_PRE_COOP_03 [Mishima]]
[s][bup 0 111 503 65535 0][f 4 23 1 238 14 10 13 10][f 4 10 65535 0 0][vp 8 2 1 19028 65535 0][f 4 1]... Eu não pensei que[n]iria terminar assim ...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O Prof. Kamoshida não tem vindo[n]à escola ultimamente...[n]O que isso significa para nós...?[n][w][e]

[msg MSG_MISHIMA_PRE_COOP_01 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 238 14 10 13 10][f 4 10 65535 0 0][vp 8 2 1 19002 65535 0]Tenho muitas ideias para você! Espero que[n]você queira ouvir o que tenho a dizer![n][w][e]

[msg MSG_MISHIIMA_BEGIN_RANK6 [Mishima]]
[s][bup 0 111 5 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19001 65535 0]Ah, [f 4 1]...[n][w][e]

[msg MSG_C18_BEGIN_WEATHER_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19009 65535 0]Em dias de chuva há muitos acessos ao Phan-Site.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Acho que as pessoas preferem[n]estar na internet, quando[n]o tempo está ruim.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quem sabe esse pico de acessos[n]não vai dar em algo bom...[n][w][e]

[msg MSG_C18_BEGIN_WEATHER_01 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19011 65535 0]A neve! Quer dizer... Está nevando![n]Um, talvez eu faça um iglu![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Espere, você não sabe o que é um iglu?[n]É uma casa em forma de cúpula[n]feita inteiramente de neve.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oooh, farei um no quintal assim que[n]a neve se acumular![n]E talvez possamos nos reunir lá![n][w][e]

[msg MSG_C18_BEGIN_WEATHER_02 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19012 65535 0]Ouvi dizer que vai chover[n]mais por um tempo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh sim! Você sabia que a[n]taxa de criminalidade aumenta drasticamente[n]durante a estação chuvosa?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Terei que dar uma olhada no Phan-Site[n]para ver se há algo acontecendo.[n][w][e]

[msg MSG_C18_BEGIN_WEATHER_03 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19013 65535 0]Que vento louco! É um tufão![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No Phan-Site, toda a conversa[n]é sobre a tempestade...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No entanto, farei o possível[n]para coletar os detalhes mais[n]importantes! Me deixe fazê-lo![n][w][e]

[msg MSG_C18_BEGIN_WEATHER_04 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19014 65535 0]Dizem que este ano os polens[n]estão particularmente agressivos...[n]Você está bem, [f 4 1]?[n][w][e]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Com esses óculos, e com[n]uma máscara anti-alérgica,[n]você pareceria um criminoso![n][w][e]

[msg MSG_C18_BEGIN_WEATHER_05 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19015 65535 0]Esta chuva veio do nada... Um dos Phandom também[n]queria que você trouxesse um guarda-chuva para[n]ele.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Os Phantom Thieves não são um serviço de entrega[n]em domicílio...[n][w][e]

[msg MSG_C18_BEGIN_WEATHER_06 [Mishima]]
[s][bup 0 111 5 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19007 65535 0]Esta muito quente...[n][w][e]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O Phandom até gostaria que você consertasse o[n]clima...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Resumindo, vocês são os Phantom Thieves,[n]não os Phantom Weather Watchers...[n][w][e]

[msg MSG_C18_BEGIN_WEATHER_07 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19017 65535 0]Há uma gripe por aí, tente ser cuidadoso. Você[n]pode usar uma máscara, por exemplo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Espere, você é daqueles que[n]prefere não usar para evitar[n]embaçar os óculos?[n][w][e]

[msg MSG_C18_BEGIN_WEATHER_08 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19017 65535 0]Droga! Tá muito frio né!?![n]É uma loucura sair![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu tenho três aquecedores de mão no meu casaco,[n]ainda estou congelando do mesmo jeito![n][w][e]

[msg MSG_C18_BEGIN_TIME_01 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0]Ei, como vai você?[n][w][e]

[msg MSG_C18_BEGIN_TIME_02 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19002 65535 0]Lembra daquele grupo que uma vez[n]disse para hackear sites[n]em nome da justiça?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu coloquei muita esperança neles,[n]mas no final eles acabaram sendo[n]apenas impostores...[n][w][e]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Os verdadeiros heróis são os Phantom Thieves![n]Quero ajudar o máximo[n]possível![n][w][e]

[msg MSG_C18_BEGIN_TIME_03 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19002 65535 0]Os Phantom Thieves finalmente fizeram sua grande[n]estreia![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E o Phan-Site começou[n]a mexer bastante...[n]estarei muito ocupado![n][w][e]

[msg MSG_C18_BEGIN_OOYA_00 [Mishima]]
[s][bup 0 111 2 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19081 65535 0]Ei, você também poderia ter me dito que era[n]apenas uma entrevista! Eu parecia um idiota,[n]vestido assim![n][w][e]
[s][bup 0 111 5 65535 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][vp 8 2 1 0 65535 0]E aquela Ohya-san? É o próprio diabo![n]Foi horrível![n][w][e]

[sel SEL_C18_BEGIN_OOYA_01 top]
[s]O que aconteceu?[e]
[s]Eu imagino.[e]

[msg MSG_C18_BEGIN_OOYA_02 [Mishima]]
[s][bup 0 111 3 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 1 0 0 0 0 0][vp 8 2 1 19082 65535 0]Ela é fofa, mas também assustadora.[n]Ela me bombardeou com perguntas, e uma[n]drag queen flertou comigo...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E apesar de tudo eles tiraram[n]comigo. O que eu fiz errado...?[n][w][e]

[msg MSG_C18_BEGIN_OOYA_03 [Mishima]]
[s][bup 0 111 3 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 1 0 0 0 0 0][vp 8 2 1 19082 65535 0]Ela é fofa, mas também assustadora.[n]E sua amiga drag queen[n]é ainda mais assustadora...[n][w][e]

[msg MSG_C18_BEGIN_OOYA_04 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 1 0 0 0 0 0][vp 8 2 1 0 65535 0]No entanto, fiz o possível para divulgar os[n]Phantom Thieves![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Lembre-se disso quando ler um artigo que fale bem[n]de você![n][w][e]

[msg MSG_C18_BEGIN_TIME_04 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19002 65535 0]Os Phantom Thieves são praticamente imparáveis.[n]Todos eles te amam![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eheheh... Como eu, afinal.[n][w][e]

[msg MSG_C18_BEGIN_TIME_05 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19083 65535 0]É incrível! Phantom[n]Thieves mania não para mais![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O Phan-Site[n]está literalmente explodindo![n][w][e]

[msg MSG_C18_BEGIN_POLICE_00 [Mishima]]
[s][bup 0 111 5 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19027 65535 0]N-Não se preocupe...[n][w][e]
[s][bup 0 111 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu não disse uma palavra[n]para aqueles policiais estúpidos![n][w][e]

[msg MSG_C18_BEGIN_TIME_06 [Mishima]]
[s][bup 0 111 3 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19001 65535 0]Os Phantom Thieves foram feitos para ser a[n]encarnação da justiça... Como chegou a esse[n]ponto?[n][w][e]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]...Não. Não faz sentido ficar aqui reclamando.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ao despertar os corações dos criminosos,[n]tenho certeza de que mais cedo ou mais tarde[n]você pode virar a maré.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, e de minha parte farei[n]tudo o que puder para ajudá-lo.[n][w][e]

[msg MSG_C18_BEGIN_TIME_07 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19103 65535 0]Temos que nos mover com cuidado,[n]tentando não chamar a atenção...[n][w][e]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No entanto, não tema. Seu[n]segredo está seguro comigo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E não digo isso apenas como[n]administrador do Phan-Site,[n]mas como seu amigo...[n][w][e]

[msg MSG_C18_BEGIN_TIME_08 [Mishima]]
[s][bup 0 111 2 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19103 65535 0]...Eu acredito em você, [f 4 1]![n][w][e]

[msg MSG_C18_BEGIN_TIME_09 [Mishima]]
[s][bup 0 111 2 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19103 65535 0]Você não acha que as pessoas estão[n]agindo de forma estranha[n]desde que o ano novo começou?[n][w][e]
[s]O Phan-Site também é pouco[n]freqüentado. Quem sabe o que[n]está acontecendo.[n][w][e]

[msg MSG_C18_BEGIN_SECOMD_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19039 65535 0]Você precisa de algo?[n][w][e]

[msg MSG_C18_MAID_YORU_00 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19024 65535 0]Então esta noite vamos implementar a[n]Operação MAIDica Guard, certo?[n][w][e]

[sel SEL_C18_MAID_YORU_01 top]
[s]Sim absolutamente![e]
[s]Vamos falar sobre pedidos.[e]
[s]Ainda não.[e]

[msg MSG_C18_MAID_YORU_02 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19080 65535 0]Fantástico! Eu mal podia esperar![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sakamoto diz para encontrá-lo em seu apartamento.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vamos, venha comigo![n][w][e]

[msg MSG_C18_MAID_YORU_02_01 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19080 65535 0]Fantástico! Eu mal podia esperar![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]...Ei, você já trocou?!?[n]Na verdade seria melhor tirar[n]o uniforme da escola...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nos encontramos na casa de Sakamoto,[n]certo? Vamos passar na minha casa primeiro,[n]para que eu possa me trocar também.[n][w][e]

[msg MSG_C18_MAID_YORU_03 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19025 65535 0]Eu vejo...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mas deixe-me saber,[n]se você ainda estiver interessado.[n][w][e]

[msg MSG_C18_BEGIN_NOTCOOP_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Desculpe, mas hoje estou ocupado[n]coletando informações.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Você sabe, gerenciar o Phan-Site[n]não é tão simples.[n][w][e]
[s][vp 8 2 1 19127 65535 0][f 4 10 65535 0 0]De qualquer forma, vamos conversar depois.[n][w][e]

[msg MSG_C18_BEGIN_NOTCOOP_07 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Desculpe, mas estou muito ocupado hoje.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O Phan-Site virou fumaça,[n]tenho que fazer algo rápido.[n][w][e]
[s][vp 8 2 1 19127 65535 0][f 4 10 65535 0 0]Preciso pelo menos ter certeza de que[n]as pesquisas ainda funcionam...[n][w][e]

[msg MSG_C18_COOP_NOTRANKUP_0 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19018 65535 0]Ei, lembra daquela pessoa[n]horrível de quem eu estava falando?[n]Você vai despertar o coração dele, certo?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Estou contando com isso, hein? Se há alguém que[n]pode fazer isso, são os Phantom Thieves.[n][w][e]

[msg MSG_C18_COOP_NOTRANKUP_0_2 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19018 65535 0]Ei, lembra daquela pessoa[n]horrível de quem eu estava falando?[n]Você vai despertar o coração dele, certo?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, também estou atualizando[n]informações sobre esse ator.[n]Vou avisar o mais rápido possível.[n][w][e]

[msg MSG_C18_COOP_NOTRANKUP_S [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19127 65535 0]Avise-me quando[n]terminar esse pedido![n][w][e]

[msg MSG_C18_COOP_NOTQUEST_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19018 65535 0]Essa quantidade de informações me mantém muito[n]ocupado. Existem tantas pessoas más no mundo...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]De qualquer forma, escreverei para você mais[n]tarde. Espero que leia minhas mensagens![n][w][e]

[msg MSG_C18_COOP_NOTQUEST_01 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19018 65535 0]Ah, também estou atualizando[n]informações sobre esse ator.[n]Vou avisar o mais rápido possível.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Contando com você![n][w][e]

[msg MSG_C18_COOP_NOTQUEST_SE [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19024 65535 0]Avisarei se encontrar outra[n]solicitação válida. Por favor,[n]responda às minhas mensagens![n][w][e]

[msg MSG_C18_MAID_HIRU_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0]Escute... Você não esqueceu[n]sobre aquele panfleto, não é? Devemos[n]usar seus "serviços", vamos lá![n][w][e]

[msg MSG_C18_MAID_HIRU_01 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0]Oh sim! Você decidiu quando[n]aprofundar o assunto[n]desse panfleto?[n][w][e]
[s][f 4 10 65535 0 0]Se você quiser fazer isso, vá[n]para Shibuya, você me encontrará lá à noite.[n]Não vá sem mim, ok?[n][w][e]

[msg MSG_C18_COOP_RANKUPOK_00 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, você cuidou[n]desse pedido. Obrigado![n][w][e]

[msg MSG_MISHIMA_CORP_C00_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0]Ei, tenho ótimas informações.[n]Você quer saber do que se trata?[n][w][e]

[msg MSG_C18_COOP_01_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0]Eu tenho pensado muito sobre o que eu poderia[n]fazer para ajudá-lo...[n][w][e]
[s]A propósito, tenho um relatório[n]para você. Você está livre hoje?[n][w][e]

[msg MSG_C18_COOP_02_00 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh sim! Como sua imagem[n]representante, pensei que deveria[n]ajudá-lo de outras maneiras também.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Você tem algum tempo hoje?[n][w][e]

[msg MSG_C18_COOP_03_00 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, tenho outra ideia de como[n]ajudar você como[n]um representante de imagem.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]É uma ótima proposta, acredite em mim.[n]Você está livre hoje?[n][w][e]

[msg MSG_C18_COOP_04_00 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh sim! Você tem que se preparar para a próxima[n]missão, não é?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Na verdade, eu fiz o mesmo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Você deve estar se perguntando como, certo?[n]Eu te digo, se você tiver tempo para mim.[n][w][e]

[msg MSG_C18_COOP_05_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, um... Há algo que eu gostaria de falar com[n]você.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]É de extrema importância. Pense[n]você tem algum tempo comigo?[n][w][e]

[msg MSG_C18_COOP_06_00 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, eu fiz algumas pesquisas[n]sobre esse ator e encontrei algumas[n]informações importantes.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Você tem algum tempo para ouvir[n]do que se trata?[n][w][e]

[msg MSG_C18_COOP_06_01 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 11][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, certo. O que você diz? Podemos[n]falar sobre[n]última vez novamente?[n][w][e]

[msg MSG_C18_COOP_07_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ei, eu gostaria de falar com você por um momento[n]sobre como estou ajudando você. Você tem algum[n]tempo?[n][w][e]

[msg MSG_C18_COOP_07_01 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, [f 4 1].[n]Eu estava esperando por você.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tenho mais uma coisa para lhe contar sobre[n]a ajuda que estou lhe dando.[n][w][e]

[msg MSG_C18_COOP_08_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, [f 4 1]. Eu esperava que pudéssemos falar[n]sobre Akiyama-kun.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Você está livre agora?[n][w][e]

[msg MSG_C18_COOP_09_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Não sei por que,[n]mas não consigo esquecer[n]as palavras de Akiyama-kun...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]De qualquer forma, eu queria falar com você[n]sobre uma coisa... Você está livre?[n][w][e]

[msg MSG_C18_COOP_10_00 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Estou feliz por ter acreditado[n]em você, [f 4 1]. Obrigado![n][w][e]

[msg MND_COOP_DOUZOKUSEI]
[s]Sinto que posso me aproximar mais de[n]Mishima graças a Persona[n][var 2] [clr 1][var 5][clr 27]...[n][w][e]

[msg MND_COOP_RANKUP_OK_FIRST]
[s]Pode ser uma boa[n]oportunidade para fortalecer[n]minha ligação com Mishima...[n][w][e]

[msg MND_COOP_RANKUP_OK]
[s]Sinto que em breve meu vínculo com Mishima se[n]fortalecerá...[n][w][e]

[msg MND_COOP_RANKUP_QUEST]
[s]Sinto que em breve meu vínculo[n]com Mishima se fortalecerá, mas…[n][w][e]

[msg MND_COOP_RANKUP_NG]
[s]Eu não acho que meu vínculo com[n]Mishima vai se fortalecer, por enquanto...[n][w][e]

[msg MND_COOP_RANK_MAX_00]
[s]Eu tenho um vínculo forte[n]com Mishima...[n][w][e]

[msg MSG_COOP_CHECK_SHIDOU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ninguém pensa que você está vivo.[n]Se você for cuidadoso,[n]tudo ficará bem.[n][w][e]

[msg MSG_COOP_CHECK_DAY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Então, quais são suas intenções?[n]Você quer conhecer Mishima?[n][w][e]

[msg MSG_COOP_CHECK_DAY_6 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Então, o que você quer fazer?[n]Você quer ir falar com Mishima?[n][w][e]

[sel SEL_COOP_CHECK top]
[s]Passe um tempo com ele[e]
[s]Verifique a conexão com Mishima[e]
[s]Recusar[e]

[sel SEL_COOP_CHECK_6 top]
[s]Vá falar com ele[e]
[s]Verifique a conexão com Mishima[e]
[s]Recusar[e]

[msg MSG_C18_YES_01_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0]Excelente! Muito melhor do que trabalhar[n]somente no Phan-Site.[n][w][e]
[s]Vamos ao restaurante conversar.[n][w][e]

[msg MSG_C18_YES_02_00 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Que tal a lanchonete?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 19052 65535 0]Vamos.[n][w][e]

[msg MSG_C18_YES_03_00 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nós vamos comer em um restaurante bufê caro em[n]Shibuya.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 19059 65535 0]Eheheh... Não se preocupe com o preço! Vamos,[n]venha comigo![n][w][e]

[msg MSG_C18_YES_04_00 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quer muito saber, né?[n]Acho que você vai gostar![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 19052 65535 0]De qualquer forma, vamos para a lanchonete, vamos[n]lá! Nós não ficamos aqui estupefatos.[n][w][e]

[msg MSG_C18_YES_05_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Você é a única pessoa com quem posso falar sobre[n]isso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Seria melhor ir[n]para um lugar sossegado...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 19055 65535 0]Que tal o Parque Inokashira?[n][w][e]

[msg MSG_C18_YES_06_00 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19080 65535 0]Obrigada. Vamos para a lanchonete, então.[n][w][e]

[msg MSG_C18_YES_06_01 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19061 65535 0]Obrigado pelo seu interesse.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eu gostaria de ir a um lugar[n]onde eu pudesse conversar com você a sós...[n]Que tal o parque?[n][w][e]

[msg MSG_C18_YES_07_00 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19052 65535 0]Então vamos para algum lugar perto daqui![n][w][e]

[msg MSG_C18_YES_07_01 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19066 65535 0]Desculpe, me dê um segundo.[n][w][e]

[msg MSG_C18_YES_07_02 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Era Akiyama-kun.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ele quer que eu vá vê-lo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Está bem perto, aparentemente.[n]Parecia algo sério...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 19018 65535 0]Acho que não devemos ignorá-lo.[n]Quer vir comigo?[n][w][e]

[msg MSG_C18_YES_08_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Então vamos para a lanchonete conversar.[n][w][e]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 19083 65535 0]Isso pode surpreendê-lo, mas...[n]aqui podemos conversar melhor.[n][w][e]

[msg MSG_C18_YES_09_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Só quero relaxar um pouco...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 19051 65535 0]Vamos ao parque.[n][w][e]

[msg MSG_C18_YES_10_00 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19083 65535 0]Contando com você![n][w][e]

[msg MSG_MORGANA_COOP_ESCAPE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bem, vou dar uma volta.[n]Avise-me quando[n]você estiver pronto para ir.[n][w][e]

[msg MSG_C18_COOP_CANCEL_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, Ok... Talvez agora[n]você esteja muito ocupado para estar[n]com alguém como eu.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 19126 65535 0]Bem, me avise se mudar de ideia.[n]Vou manter meu telefone por perto, caso[n]você queira me enviar uma mensagem.[n][w][e]

[msg MSG_C18_COOP_CANCEL_06 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 19064 65535 0]Ah... Depois, talvez...?[n][w][e]

[msg MSG_SPOT_OPEN_KANDA]
[s]Agora você pode ir para [clr 1]Kanda[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_SHINJUKU]
[s]Agora você pode ir para [clr 2]Shinjuku[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_AKIHABARA]
[s]Agora você pode ir para [clr 2]Akihabara[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_INOKASHIRA]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Inokashira Park[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_OGIKUBO]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Ogikubo Ramen[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que gosta de ramen,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_ODAIBA]
[s]Você descobriu um novo[n]ponto de encontro:[n][clr 2]Parque Beira-Mar Odaiaba[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]gosta de parques aquáticos,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_UENO]
[s]Você descobriu um novo[n]ponto de encontro:[n][clr 2]Museu Ueno[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]pode gostar de arte,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_TSUKISHIMA]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Tsukishima Monja[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]gosta de comer monjayaki,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_HARAJUKU]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Harajuku Takenoko[clr 27].[n][w][e]
[s]Se você conhece alguém que gosta da Rua[n]Takenoko, tente[n]convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_TYUKAGAI]
[s]Você descobriu um novo[n]ponto de encontro:[n][clr 2]Chinatown de Motomachi[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_MAIHAMA]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Destinyland de Maihama[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Asakusa[clr 27].[n][w][e]
[s]Se você conhece alguém que gosta de Skytree ou[n]Nakamise Street, tente convidá-los aqui.[n][w][e]

[msg MSG_SPOT_OPEN_IKEBUKURO]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Ikebukuro Planetarium[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_MEIJIJINGU]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Santuário Meiji[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]
[s]Se você quiser, também pode[n]ir lá sozinho para[n]orar no santuário.[n][w][e]

[msg MSG_SPOT_OPEN_SUIDOUBASH]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Dome Town of Suidobashi[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_SHIBUYA]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Wilton Hotel em Shibuya[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_GINZA]
[s]Você descobriu um novo[n]ponto de encontro:[n][clr 2]Sushi Bar em Ginza[clr 27].[n][w][e]
[s]Se você conhece alguém que gosta de[n]comer sushi caro,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_JINBOCHO]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Cidade dos Livros Jinbocho[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]
[s]Se você quiser, também pode[n]ir lá sozinho para fazer[n]algumas compras.[n][w][e]

[msg MSG_SPOT_OPEN_ICHIGAYA]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Lago Ichigaya[clr 27].[n][w][e]
[s]Se você conhece alguém que[n]gosta de pescar, tente[n]convidá-lo aqui.[n][w][e]
[s]Além disso, se você quiser, pode[n]ir lá sozinho e experimentar alguns peixes.[n][w][e]

[msg MSG_SPOT_OPEN_SHINAGAWA]
[s]Você descobriu um novo[n]local de encontro:[n][clr 2]Shinagawa Aquarium[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que pode gostar do aquário,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_SPOT_OPEN_NAKANO]
[s]Você descobriu um novo[n]ponto de encontro:[n][clr 2]Área do Complexo Comercial, Nakano[clr 27].[n][w][e]
[s]Se você conhece alguém[n]que pode gostar do lugar,[n]tente convidá-lo aqui.[n][w][e]

[msg MSG_C18_BYEGREET_00_00 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 1 65535 0]Oh, [f 4 1]![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]Amanhã você finalmente vai voltar para casa,[n]eh? Isso significa que os[n]Phantom Thieves se separaram, eu acho.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]Meu documentário está progredindo bem,[n]de qualquer maneira. Ainda há muito a[n]fazer, mas estou otimista.[n][w][e]

[sel SEL_C18_BYEGREET_00_01 top]
[s]Promete bem.[e]
[s]Como se trata?[e]
[s]Bem, não espero menos.[e]

[msg MSG_C18_BYEGREET_00_02 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]Sim, deixe comigo![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]Vai ser digno da equipe[n][f 4 28], você vai ver![n][w][e]

[msg MSG_C18_BYEGREET_00_03 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Excelente![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 7 65535 0]Vai ser digno da equipe[n][f 4 28], você vai ver![n][w][e]

[msg MSG_C18_BYEGREET_00_04 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]Eheheh... Você finalmente entendeu[n]o que eu valho, hein?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 9 65535 0]Se sim, não vou decepcioná-lo![n]Farei algo digno[n]da equipe [f 4 28]![n][w][e]

[msg MSG_C18_BYEGREET_00_05 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 10 65535 0]Sabe... nunca pensei[n]que poderia criar algo tão[n]impacto como este documentário.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]Eu era tão covarde... Mas agora eu sei[n]que posso entregar uma mensagem[n]que só eu posso espalhar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]Neste ponto, não posso fazer nada além de dar[n]tudo de mim.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Hum, aqui.[n][w][e]

[msg MSG_C18_BYEGREET_00_06 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 14 65535 0]Ainda é um rascunho[n]provisório, mas gostaria que[n]o lesse.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 15 65535 0]Ah, e eu também gostaria da sua opinião![n]Você receberá uma porcentagem,[n]se vender bem...[n][w][e]
[s][f 4 10 65535 0 540][vp 8 0 1 16 65535 0]...Mas não brinque comigo,[n]se algo der errado, ok?[n][w][e]

[msg MSG_C18_BYEGREET_00_07 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 540][vp 8 0 1 17 65535 0]...Mas não brinque comigo,[n]se algo der errado, ok?[n][w][e]

[msg MSG_C18_BYEGREET_00_00_5 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 18 65535 0]Oh, [f 4 1]![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 19 65535 0]Amanhã você finalmente vai voltar para casa,[n]eh? Isso significa que os[n]Phantom Thieves se separaram, eu acho.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 20 65535 0]Meu documentário prossegue bem, no entanto. Ainda[n]há muito o que fazer, mas estou otimista.[n][w][e]

[sel SEL_C18_BYEGREET_00_01_5 top]
[s]O primeiro de uma trilogia, certo?[e]
[s]Como é o título?[e]
[s]Quando sai?[e]

[msg MSG_C18_BYEGREET_00_02_5 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 21 65535 0]Você quer fazer uma série? Eu não acho que[n]será tão bem sucedido ...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 22 65535 0]Mas se eu conseguir fazer um bom trabalho,[n]seria uma pena parar[n]em uma...[n][w][e]

[msg MSG_C18_BYEGREET_00_03_5 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 23 65535 0]Hã? Eu ainda não[n]pensei sobre isso... Estou muito ocupado[n]escrevendo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 24 65535 0]Mas quando chegar a hora de encontrá-lo,[n]eu buscarei conselhos diretamente[n]dos ex-Phantom Thieves.[n][w][e]

[msg MSG_C18_BYEGREET_00_04_5 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 25 65535 0]Ufa, há muito mais a fazer[n]que não quero pensar nisso,[n]por enquanto.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 26 65535 0]Mas não quero pegar leve[n]só porque não tenho prazos.[n]Quero que seja bom.[n][w][e]

[msg MSG_C18_BYEGREET_00_05_5 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 27 65535 0]Quem sabe quantas pessoas vão[n]entrar em contato com o meu trabalho...[n]Isso me emociona, mas também me assusta.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 28 65535 0]Pode se tornar um best-seller[n]ou cair no esquecimento.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 29 65535 0]Mas eu quero manter minhas esperanças altas.[n]É uma mensagem para o mundo inteiro[n]do meu antigo eu.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 30 65535 0]Mesmo que eu tenha medo de não conseguir,[n]darei tudo de mim! Assim como você[n]com a primeira carta de aviso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 31 65535 0]Oh, sim...[n]Ainda é um rascunho, mas...[n][w][e]

[msg MSG_C18_BYEGREET_00_06_5 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 32 65535 0]Eu gostaria que você pudesse[n]lê-lo. Eu gostaria de saber[n]o que você pensa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 33 65535 0]Claro que há muitas[n]lutas sobre as quais não[n]sei nada, certo?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 34 65535 0]Um dia você terá que me contar sobre isso.[n]Quanto mais eu puder contar sobre isso, melhor.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 35 65535 0]Eu vou fazer [f 4 28][n]fazer história![n][w][e]

[msg MSG_C18_BYEGREET_00_07_5 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 540][vp 8 0 1 36 65535 0]Eu vou fazer [f 4 28][n]fazer história![n][w][e]

