[sel YES_NO_SEL top]
[s]はい[e]
[s]いいえ[e]

[msg NPC_GREETING_MSG]
[s]Š拶[n][w][e]

[msg NPC_01]
[s]会話[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Você não precisa estar aqui agora, não é?[n]Vamos lá, vamos para outro lugar![n][w][e]

[msg MSG_LAST_GREETING_etc [Calm Priest]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Bem-vindo. Por favor, leve seu tempo.[n][w][e]

[msg MSG_LAST_GREETING_00_00 [Calm Priest]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Oh, você é quem costumava jogar shogi com[n]Togo-san...[n][w][e]

[msg MSG_LAST_GREETING_01_00 [Calm Priest]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Eu costumava jogar uma partida com ela de[n]vez em quando também. Ela se tornou muito[n]mais hábil desde então.[n][w][e]
[s][vp 8 2 1 0 0 0]Sem dúvida, você teve uma mão nisso...[n][w][e]
[s][vp 8 2 1 0 0 0]Você sempre pode procurar o Santuário aqui,[n]por isso, junte-se a ela para outro jogo.[n][w][e]

[msg MSG_LAST_GREETING_END [Calm Priest]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Você sempre pode procurar o Santuário aqui,[n]por isso, junte-se a ela para outro jogo.[n][w][e]

[msg MSG_SKILL_REMEMBER_NPC01 [Calm Priest]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Bem-vindo, Lost Lamb.[n][w][e]
[s][vp 8 2 1 0 0 0]Os cordeiros que se afastaram de seu caminho[n]e perderam de vista seus objetivos nesta[n]vida são bem-vindos aqui.[n][w][e]
[s][vp 8 2 1 0 0 0]Simplificando, ofereço consolo e conselhos[n]para aqueles com preocupações ou que[n]desejam refletir sobre seu passado.[n][w][e]

[msg MSG_ZangeOpenTalk [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Hmm, este parece um lugar conveniente para-[n]espere, ele disse "refletir sobre o passado[n]deles"?[n][w][e]

[msg MSG_ZangeOpenTalk02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Isso pode ser bastante útil para você se[n]você tivesse algo que queria lembrar.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]... Apenas certifique-se de não ofendê-lo ou[n]deixá-lo com raiva ao afastar seus[n]conselhos.[n][w][e]

[msg MSG_SKILL_REMEMBER_NPC01_2 [Calm Priest]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Dia após dia, muitas pessoas visitam esse[n]confessionário.[n][w][e]
[s][vp 8 2 1 0 0 0]Todos eles recuperam algo importante[n]refletindo sobre seu passado.[n][w][e]

[msg MSG_Shop_Start [Calm Priest]]
[s][vp 8 2 1 0 0 0]A propósito... você chegou em um bom tempo[n]hoje.[n][w][e]
[s][vp 8 2 1 0 0 0]Atualmente, estamos aceitando pequenas[n]doações de pessoas que desejam apoiar nossa[n]igreja e seu trabalho.[n][w][e]
[s][vp 8 2 1 0 0 0]Se você doar, receberá um item adequado para[n]o valor da sua doação.[n][w][e]

[msg MSG_Shop_AnyoneBuy [Calm Priest]]
[s][vp 8 2 1 0 0 0]Você fez uma boa ação. Deus esteja com você,[n]meu filho.[n][w][e]

[msg MSG_Shop_NotBuy [Calm Priest]]
[s][vp 8 2 1 0 0 0]...Eu vejo.[n][w][e]

[msg MSG_ShopInfo_AccessNotSu [Calm Priest]]
[s][vp 8 2 1 0 0 0]Oh, eu também devo mencionar que todo [n][clr 2]Domingo [clr 27], coletamos doações aqui na igreja.[n][w][e]
[s]Temos uma recompensa modesta preparada,[n]então venha visitar se você estiver[n]interessado.[n][w][e]

