[msg KARIOKI_NPC_grt00]
[s]Definindo garotas do NPC que seguram as[n]fraquezas uma da outra [n][w][e]

[msg KARIOKI_NPC_talk00]
[s]Localização temporária para meninas do NPC[n]que mantêm as fraquezas uma da outra [n][w][e]

[msg MSG_POLICEMAN_03_000_00 [Aloof Officer]]
[s][f 4 23 1 6 3 10 0 0][vp 8 2 1 0 6 0]Desculpe, mas estamos investigando por[n]dentro.[n]Você ficaria fora desta área por um tempo?[n][w][e]
[s][vp 8 2 1 0 6 0]Peço desculpas se eu te assustar.[n]Eu apreciaria sua cooperação.[n][w][e]

[msg MSG_BUKATSU_NPC01_000_00 [Blond Student Athlete]]
[s][f 4 23 1 80 3 10 0 10][vp 8 2 1 0 80 0]Bem, fale do diabo. O que vocês fizeram com[n]Kamoshida?[n][w][e]

[msg MSG_BUKATSU_NPC01_001_00 [Blond Student Athlete]]
[s][f 4 23 1 80 3 10 0 10][vp 8 2 1 0 80 0]Pare de causar problemas ou você vai[n]estragar tudo para todos. Mas acho que não[n]importa assim que você for expulso.[n][w][e]

[msg MSG_BUKATSU_NPC01_002_00 [Bossy Student Athlete]]
[s][f 4 23 1 81 3 10 0 10][vp 8 2 1 0 81 0]Você sai com Sakamoto, certo?[n]Há algo que eu quero que você diga a ele por[n]mim.[n][w][e]
[s][vp 8 2 1 0 81 0]"Você tem o que merece." Vocês sendo[n]expulsos da escola são boas notícias para[n]mim.[n][w][e]

[msg MSG_BUKATSU_NPC01_003_00 [Blond Student Athlete]]
[s][f 4 23 1 80 3 10 0 10][vp 8 2 1 0 80 0]Os caras do atletismo ficarão felizes em que[n]Sakamoto se foi. É toda culpa dele que eles[n]foram fechados.[n][w][e]

[msg MSG_YOWAMINIGIRI_001_0_0 [Ruthless Student]]
[s][vp 8 2 1 0 5 0]Ei... você roubou as perguntas para o[n]questionário do escritório dos professores,[n]não é?[n][w][e]

[msg MSG_YOWAMINIGIRI_001_1_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]O-OF CURSO NÃO... Por que você está dizendo[n]isso?[n][w][e]

[msg MSG_YOWAMINIGIRI_001_2_0 [Ruthless Student]]
[s][f 4 23 1 5 4 10 5 10][vp 8 2 1 0 5 0]Uau. Agora você vai mentir sobre isso? Eu[n]poderia enviar essa foto a todos como[n]prova, sabe?[n][w][e]

[msg MSG_YOWAMINIGIRI_001_3_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]Oh, não... por favor, não faça isso.[n]Você não pode informar os professores.[n][w][e]

[msg MSG_YOWAMINIGIRI_001_4_0 [Ruthless Student]]
[s][f 4 23 1 5 6 10 0 0][vp 8 2 1 0 5 0]Bom. Então faça a mesma coisa para mim. É[n]fácil para você roubar perguntas de teste,[n]certo?[n][w][e]

[msg MSG_YOWAMINIGIRI_002_0_0 [Ruthless Student]]
[s][vp 8 2 1 0 5 0]Você já recebe essas perguntas de teste?[n]Se você não se apressar, não conseguirá o[n]tempo de interrupção, sabe.[n][w][e]

[msg MSG_YOWAMINIGIRI_002_1_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]Eu não podia... os professores estão sendo[n]muito cuidadosos por causa dos "ladrões[n]fantasmas" ou o que seja.[n][w][e]

[msg MSG_YOWAMINIGIRI_002_2_0 [Ruthless Student]]
[s][f 4 23 1 5 4 10 5 10][vp 8 2 1 0 5 0]Huh? Você não conseguiu roubar as perguntas[n]do teste, assim como você fez nesta foto?[n][w][e]
[s][vp 8 2 1 0 5 0]Ou você já quis confessar seus crimes?[n]"Sinto muito, sou um ladrão e um[n]trapaceiro." Hum?[n][w][e]

[msg MSG_YOWAMINIGIRI_002_3_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]S-STOP! Eu sei! Por favor, apenas me dê um[n]pouco mais de tempo...[n][w][e]

[msg MSG_YOWAMINIGIRI_003_0_0 [Ruthless Student]]
[s][vp 8 2 1 0 5 0]Finalmente, você os pegou. Você realmente me[n]fez esperar até o último minuto.[n][w][e]

[msg MSG_YOWAMINIGIRI_003_1_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]Você está feliz? Agora exclua essa foto,[n]como você disse que faria.[n][w][e]

[msg MSG_YOWAMINIGIRI_003_2_0 [Ruthless Student]]
[s][vp 8 2 1 0 5 0]O que? Não. Você ainda pode ser útil para[n]mim. Não é certo, meu pequeno ladrão de[n]teste?[n][w][e]

[msg MSG_YOWAMINIGIRI_003_3_0 [Ruthless Student]]
[s][f 4 23 1 5 4 10 5 10][vp 8 2 1 0 5 0]Se alguém descobrir o que você fez, você[n]será expulso da escola, assim como o Sr.[n]Kamoshida.[n][w][e]

[msg MSG_YOWAMINIGIRI_003_4_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]Não... eu não posso continuar fazendo isso...[n][w][e]

[msg MSG_YOWAMINIGIRI_004_0_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]Você se saiu bem no teste, certo?[n]Quero dizer, você roubou as perguntas, por[n]isso deveria ter sido super fácil.[n][w][e]

[msg MSG_YOWAMINIGIRI_004_1_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]Oh vamos lá. Você os usou também.[n][w][e]

[msg MSG_YOWAMINIGIRI_004_2_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]Fingindo que você é inocente? Acha que você[n]é melhor do que eu? Pessoas como você me[n]deixam louco.[n][w][e]

[msg MSG_YOWAMINIGIRI_004_3_0 [Timid-Looking Female Student]]
[s][vp 8 2 65535 0 0 0]......[n][w][e]

[msg MSG_YOWAMINIGIRI_004_4_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]Qualquer que seja. Também estou contando com[n]você para as finais, Lil Miss Goody dois[n]sapatos, então não me decepcione.[n][w][e]

[msg MSG_YOWAMINIGIRI_005_0_0 [Ruthless Student]]
[s][vp 8 2 1 0 5 0]O que você está fazendo, abandonando a[n]escola? Você ainda precisa me fazer as[n]perguntas para o teste, certo?[n][w][e]
[s][vp 8 2 1 0 5 0]...O que? Você vai contar ao professor?[n][w][e]
[s][vp 8 2 1 0 5 0]Ei, sou eu quem deveria estar dizendo isso.[n][w][e]
[s][vp 8 2 1 0 5 0]É melhor você chegar à escola se não quiser[n]que todos na escola vejam essa foto. Você[n]entendeu!?[n][w][e]

[msg MSG_YOWAMINIGIRI_051_0_0 [Ruthless Student]]
[s][vp 8 2 1 0 5 0]Eu te disse, você não pode simplesmente[n]abandonar a escola sempre que quiser. Se[n]minhas notas caírem, isso é culpa sua.[n][w][e]

[msg MSG_YOWAMINIGIRI_051_1_0 [Timid-Looking Female Student]]
[s][vp 8 2 65535 0 0 0]......[n][w][e]

[msg MSG_YOWAMINIGIRI_051_2_0 [Ruthless Student]]
[s][vp 8 2 1 0 5 0]Ei, você acha que eu sou o ruim aqui?[n]Então, por que você não pede ajuda aos[n]"ladrões Phantom"?[n][w][e]

[msg MSG_YOWAMINIGIRI_051_3_0 [Ruthless Student]]
[s][f 4 23 1 5 4 10 5 10][vp 8 2 1 0 5 0]Mas se alguém vai implorar por misericórdia[n]em uma conferência de imprensa, é você. Eu[n]tenho provas aqui.[n][w][e]

[msg MSG_YOWAMINIGIRI_051_4_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]Me desculpe... vou fazer o que você quiser...[n][w][e]

[msg MSG_YOWAMINIGIRI_006_0_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]...Ei. Você vê essa garota com cabelos[n]pretos? O quieto que está olhando para[n]baixo o tempo todo.[n][w][e]

[sel SEL_YOWAMINIGIRI_007_0_0 top]
[s]Eu não a conheço.[e]
[s]Então e ela?[e]
[s]Talvez ela esteja doente.[e]

[msg MSG_YOWAMINIGIRI_006_1_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]Sim? Então eu acho que não importa.[n][w][e]

[msg MSG_YOWAMINIGIRI_006_2_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]Huh? Ah, esqueça. Não tem nada a ver com[n]você.[n][w][e]

[msg MSG_YOWAMINIGIRI_006_3_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]Sim? Bem, se ela estivesse doente, então[n]deveria ter me chamado.[n][w][e]

[msg MSG_YOWAMINIGIRI_006_4_0 [Ruthless Student]]
[s][vp 8 2 1 0 5 0]Como ela poderia não aparecer na escola?[n]Gah, isso é tão frustrante![n][w][e]

[msg MSG_YOWAMINIGIRI_007_0_0 [Ruthless Student]]
[s][vp 8 2 1 0 5 0]Ei, eu não disse para não abandonar a escola[n]sem você me dizer?[n][w][e]
[s][vp 8 2 1 0 5 0]Você quer que todos vejam essa foto? Quer[n]que eu poste on-line como os ladrões[n]Phantom?[n][w][e]
[s][vp 8 2 1 0 5 0]O que? Chantagem? Você está brincando.[n]Estou apenas fazendo o que é justo, sabe?[n]Como os ladrões fantasmas.[n][w][e]
[s][vp 8 2 1 0 5 0]Os ladrões Phantom punirem os bandidos, e[n]estou basicamente fazendo a mesma coisa![n][w][e]

[msg MSG_YOWAMINIGIRI_008_0_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]Que diabos...? Está tão perto das finais,[n]mas ela não está aparecendo na escola.[n][w][e]

[msg MSG_YOWAMINIGIRI_008_1_0 [Talkative Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]Oh, você não ouviu? Aquela garota está de[n]licença médica. Ela está descansando em[n]casa há um tempo.[n][w][e]
[s][vp 8 2 1 0 4 0]Ela está se candidatando à faculdade, então[n]acho que se estressou estudando demais.[n][w][e]

[msg MSG_YOWAMINIGIRI_008_2_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]Você precisa estar brincando! Sério?[n]Eu não acredito nisso...[n][w][e]

[msg MSG_YOWAMINIGIRI_009_0_0 [Ruthless Student]]
[s][vp 8 2 1 0 4 0]Estou tão profundo para os exames finais...[n]será culpa dela se eu perder minha[n]recomendação![n][w][e]
[s][vp 8 2 1 0 4 0]Não importa o quanto eu a empurro, ela ainda[n]não roubou as perguntas do teste.[n]Ela está até me ignorando.[n][w][e]
[s][vp 8 2 65535 0 0 0]......[n][w][e]
[s][vp 8 2 1 0 4 0]O que vou fazer? Ela não falou com a[n]polícia, não é? Talvez eu deva excluir essa[n]foto...[n][w][e]

[msg MSG_YOWAMINIGIRI_010_0_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]...Huh. Eu acho que você não estava tão[n]doente quanto eu pensava. Eu nunca deveria[n]ter preocupado.[n][w][e]

[msg MSG_YOWAMINIGIRI_010_1_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]Você estava preocupado, hein? Bem, sua[n]recomendação está na linha e você estaria[n]com problemas sem mim.[n][w][e]

[msg MSG_YOWAMINIGIRI_010_2_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]Qualquer que seja. Eu excluí a foto sua[n]roubando essas perguntas de teste.[n][w][e]
[s][vp 8 2 1 0 5 0]Agora você não pode dizer que eu chantageei[n]você.[n]Pena que não há provas.[n][w][e]

[msg MSG_YOWAMINIGIRI_010_3_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]O que? Oh, então você realmente excluiu essa[n]foto...[n][w][e]

[msg MSG_YOWAMINIGIRI_011_0_0 [Timid-Looking Female Student]]
[s][vp 8 2 1 0 4 0]Olá. Então, sobre o meu pedido... como foi?[n][w][e]
[s][vp 8 2 1 0 4 0]...Sério? Uau, você trabalha rápido.[n][w][e]
[s][vp 8 2 1 0 4 0]Direita. Vou depositar o dinheiro.[n]Depois de receber, envie-me as imagens...[n]sim.[n][w][e]

[msg MSG_YOWAMINIGIRI_012_0_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]O que você quer? Eu já te disse que apagarei[n]essa foto sua.[n][w][e]

[msg MSG_YOWAMINIGIRI_012_1_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 4 10 5 10][vp 8 2 1 0 4 0]... Eu pensei que deveria te mostrar isso.[n][w][e]

[msg MSG_YOWAMINIGIRI_012_2_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]O que você tem isso!? Como você tirou essa[n]foto!?[n][w][e]

[msg MSG_YOWAMINIGIRI_012_3_0 [Timid-Looking Female Student]]
[s][vp 8 2 1 0 4 0]Esqueça sua recomendação. Você deve estar[n]mais preocupado com a polícia se estiver[n]furto em lojas.[n][w][e]
[s][f 4 23 1 4 6 10 0 30][vp 8 2 1 0 4 0]Você sabe como isso funciona. Se você não[n]quer que as pessoas saibam, então você sabe[n]o que eu quero que você faça.[n][w][e]

[msg MSG_YOWAMINIGIRI_013_0_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]Olha, me desculpe! Por favor, apague essa[n]foto![n]Se eles sabem que eu tenho furtado em lojas,[n]eu...[n][w][e]

[msg MSG_YOWAMINIGIRI_013_1_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]Você começou isso. Agora você entende como[n]eu me sinto? Ficar chantageado não é tão[n]divertido, é?[n][w][e]

[msg MSG_YOWAMINIGIRI_013_2_0 [Ruthless Student]]
[s][f 4 23 1 5 3 10 0 0][vp 8 2 1 0 5 0]É por isso que estou dizendo que sinto[n]muito! Eu até roubei as perguntas do teste![n][w][e]

[msg MSG_YOWAMINIGIRI_013_3_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]Quando você foi quem me chantageia, você me[n]deixou sair do gancho? Eu não acho.[n][w][e]

[msg MSG_YOWAMINIGIRI_013_4_0 [Ruthless Student]]
[s][vp 8 2 65535 0 0 0]......[n][w][e]

[msg MSG_YOWAMINIGIRI_014_0_0 [Ruthless Student]]
[s][f 4 23 1 5 4 10 5 10][vp 8 2 1 0 5 0]Você é apenas um aluno do ensino médio, mas[n]fez datas com homens mais velhos por[n]dinheiro?[n][w][e]
[s][vp 8 2 1 0 5 0]Estou apenas chocado. Você parece tão[n]tímido, mas está executando seu próprio[n]golpe de romance, não é?[n][w][e]

[msg MSG_YOWAMINIGIRI_014_1_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]O que!? De jeito nenhum, você contratou um[n]investigador particular também!?[n][w][e]

[msg MSG_YOWAMINIGIRI_014_2_0 [Ruthless Student]]
[s][f 4 23 1 5 6 10 0 10][vp 8 2 1 0 5 0]Você acha que vou deixar alguém como você me[n]intimidar? Tudo o que fiz foi nivelar o[n]campo de jogo.[n][w][e]

[msg MSG_YOWAMINIGIRI_014_3_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 3 10 0 0][vp 8 2 1 0 4 0]Não pense que você pode se safar disso.[n]Não se esqueça que ainda tenho essas fotos[n]em lojas.[n][w][e]

[msg MSG_YOWAMINIGIRI_015_0_0 [Timid-Looking Female Student]]
[s][vp 8 2 1 0 4 0]Talvez devêssemos excluir qualquer evidência[n]que tenhamos e pare de nos encontrar assim.[n][w][e]

[msg MSG_YOWAMINIGIRI_015_1_0 [Ruthless Student]]
[s][vp 8 2 1 0 5 0]Hmm... sim. Não é bom para nós dois se[n]apenas chantagearmos um ao outro. Não há[n]sentido.[n][w][e]

[msg MSG_YOWAMINIGIRI_015_2_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 4 10 5 10][vp 8 2 1 0 4 0]Cale-se! Aqui estão as fotos incriminadoras[n]que tenho de você. Mostre-me aqueles que[n]você tem de mim.[n][w][e]

[msg MSG_YOWAMINIGIRI_015_3_0 [Ruthless Student]]
[s][f 4 23 1 5 4 10 5 10][vp 8 2 1 0 5 0]Bom. Isso é tudo que eu tenho.[n]Vamos excluí-los juntos.[n][w][e]

[msg MSG_YOWAMINIGIRI_015_4_0 [Timid-Looking Female Student]]
[s][f 4 23 1 4 6 10 0 30][f 4 23 1 5 6 10 0 30][vp 8 2 1 0 4 0]...Está feito. Tudo isso foi apagado.[n][w][e]
[s][vp 8 2 1 0 4 0]Mas quem sabe se isso era realmente tudo ou[n]não...? Hehehe.[n][w][e]

[msg MSG_YOWAMINIGIRI_015_5_0 [Ruthless Student]]
[s][vp 8 2 1 0 5 0]Haha, sim. Nós já fomos longe demais. Parece[n]que estamos presos um com o outro.[n][w][e]

[msg MSG_GRT_main_All_001_01_ [Ruthless Student]]
[s][vp 9 2 65535 42112 0 0]Então, ele é o estudante transferido sobre o[n]qual as pessoas estavam falando online...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_03_ [Ruthless Student]]
[s][vp 9 2 65535 42162 0 0]Ouvi dizer que ele foi preso por agressão.[n]Ele é um criminoso de verdade.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_04_ [Ruthless Student]]
[s][vp 9 2 65535 42512 0 0]Espere, esse é o cara que agrediu alguém?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_05_ [Ruthless Student]]
[s][vp 9 2 65535 42963 0 0]Ei, é ele, não é? As pessoas estavam falando[n]online...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_01_ [Ruthless Student]]
[s][vp 9 2 65535 42862 0 0]Até os professores desistiram dele.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_02_ [Ruthless Student]]
[s][vp 9 2 65535 43013 0 0]Os rumores estavam certos...[n]Ele parece realmente perigoso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_03_ [Ruthless Student]]
[s][vp 9 2 65535 42913 0 0]Eu não quero me envolver com ele... ele é[n]assustador.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_04_ [Ruthless Student]]
[s][vp 9 2 65535 42863 0 0]Se ele fosse expulso, eu me sentiria tão[n]aliviado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_05_ [Ruthless Student]]
[s][vp 9 2 65535 43212 0 0]Ele realmente é perigoso, não é?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_01_ [Ruthless Student]]
[s][vp 9 2 65535 43063 0 0]Ele já começou a causar problemas?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_02_ [Ruthless Student]]
[s][vp 9 2 65535 42712 0 0]Ele não vai apenas começar a atacar pessoas,[n]não é?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_03_ [Ruthless Student]]
[s][vp 9 2 65535 42363 0 0]Ele está sendo expulso?[n]Esse cara não deve ter nenhum remorso por[n]seus crimes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_04_ [Ruthless Student]]
[s][vp 9 2 65535 42562 0 0]Ele já está sendo expulso? Isso é meio[n]impressionante, de certa forma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_05_ [Ruthless Student]]
[s][vp 9 2 65535 43212 0 0]Esse aluno transferido já está sendo expulso[n]da escola![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_01_ [Ruthless Student]]
[s][vp 9 2 65535 42703 0 0]Estou tendo uma boa risada[n]desse absurdo deladrão fantasma.[n]Espero que não pare por aqui.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_03_ [Ruthless Student]]
[s][vp 9 2 65535 42951 0 0]Ele brigou com o Sr. Kamoshida? Ele é[n]estúpido?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_04_ [Ruthless Student]]
[s][vp 9 2 65535 40355 0 0]Provavelmente é apenas uma[n]brincadeira de alguém que assiste[n]muito anime...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_05_ [Ruthless Student]]
[s][vp 9 2 65535 38905 0 0]Um cartão de chamada Phantom Thief?[n]Isso é apenas uma brincadeira, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_01_ [Ruthless Student]]
[s][vp 9 2 65535 41705 0 0]Espere, essa coisa de ladrão fantasma era[n]real?[n]Não, isso é ridículo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_02_ [Ruthless Student]]
[s][vp 9 2 65535 44654 0 0]Por que ele estava de repente agindo dessa[n]maneira? Os ladrões Phantom o ameaçaram?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_03_ [Ruthless Student]]
[s][vp 9 2 65535 42602 0 0]Você pode acreditar nas coisas que o Sr.[n]Kamoshida disse que sim?[n]Ele é completamente horrível![n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_04_ [Ruthless Student]]
[s][vp 9 2 65535 40105 0 0]Você não pode roubar o coração de alguém...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_05_ [Ruthless Student]]
[s][vp 9 2 65535 43105 0 0]Essa brincadeira foi perfeitamente[n]cronometrada...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_01_ [Ruthless Student]]
[s][vp 9 2 65535 42313 0 0]Eu gostaria que ele tivesse desaparecido[n]junto com Kamoshida.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_02_ [Ruthless Student]]
[s][vp 9 2 65535 40302 0 0]Espere, ele realmente não tinha nada a ver[n]com isso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_03_ [Ruthless Student]]
[s][vp 9 2 65535 43362 0 0]Andando aqui como se ele possua o lugar...[n]Ele deveria ter sido expulso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_04_ [Ruthless Student]]
[s][vp 9 2 65535 42513 0 0]Talvez ele não tenha sido expulso, mas ele[n]ainda tem esse registro criminal...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_05_ [Ruthless Student]]
[s][vp 9 2 65535 42613 0 0]Ouvi dizer que o aluno transferido não está[n]mais sendo expulso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_01_ [Ruthless Student]]
[s][vp 9 2 65535 40103 0 0]O time de vôlei terminou sem Kamoshida.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_03_ [Ruthless Student]]
[s][vp 9 2 65535 38602 0 0]O time de vôlei vai ter isso de agora em[n]diante.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_04_ [Ruthless Student]]
[s][vp 9 2 65535 40505 0 0]Eu nunca gostaria de me tornar conhecido por[n]assédio sexual...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_05_ [Ruthless Student]]
[s][vp 9 2 65535 38354 0 0]Eu acho que o time de vôlei não receberá[n]mais o tratamento real da nossa escola...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_01_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_03_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_04_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_05_ [Ruthless Student]]
[s][vp 9 2 65535 38004 0 0]Se as pessoas estão falando muito sobre[n]isso, você quer dar uma olhada?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_01_ [Ruthless Student]]
[s][vp 9 2 65535 38755 0 0]Outro e-mail de spam?[n]Qual é o problema com tudo isso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_03_ [Ruthless Student]]
[s][vp 9 2 65535 42905 0 0]Alguns esquisitos tentaram começar a falar[n]comigo em Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_04_ [Ruthless Student]]
[s][vp 9 2 65535 38704 0 0]Ouvi dizer que eles estão realmente[n]segmentando alunos do ensino médio...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_05_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_01_ [Ruthless Student]]
[s][vp 9 2 65535 39804 0 0]Mencionou algo sobre os ladrões fantasmas.[n]Kamoshida está realmente envolvido de[n]alguma forma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_03_ [Ruthless Student]]
[s][vp 9 2 65535 38254 0 0]Tanto Kamoshida quanto Madarame... talvez[n]ladrões fantasmas realmente existam...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_04_ [Ruthless Student]]
[s][vp 9 2 65535 39103 0 0]É verdade que Madarame também recebeu um[n]cartão de visita?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_05_ [Ruthless Student]]
[s][vp 9 2 65535 42354 0 0]Ouvi dizer que os ladrões fantasmas enviaram[n]um cartão de visita para Madarame também...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_01_ [Ruthless Student]]
[s][vp 9 2 65535 38201 0 0]O que a polícia está fazendo?[n]Apresse-se e prenda-os...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_02_ [Ruthless Student]]
[s][vp 9 2 65535 43013 0 0]Estou ouvindo que algumas pessoas foram[n]arruinadas por golpes de phishing...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_03_ [Ruthless Student]]
[s][vp 9 2 65535 40652 0 0]Ouvi dizer que algumas pessoas da nossa[n]escola foram extorquidas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_04_ [Ruthless Student]]
[s][vp 9 2 65535 38752 0 0]Alguns de nossos colegas de classe realmente[n]foram enganados, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_05_ [Ruthless Student]]
[s][vp 9 2 65535 40802 0 0]É assustador que tantos mais pessoas estejam[n]se apaixonando por golpes de phishing hoje[n]em dia...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_01_ [Ruthless Student]]
[s][vp 9 2 65535 42204 0 0]As pessoas têm visto cartões de chamada[n]Phantom Thief em Shibuya![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_03_ [Ruthless Student]]
[s][vp 9 2 65535 42754 0 0]Quem eles vão punir a seguir?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_04_ [Ruthless Student]]
[s][vp 9 2 65535 40505 0 0]Quem é esse cara de Kaneshiro que eles estão[n]mirando desta vez?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_05_ [Ruthless Student]]
[s][vp 9 2 65535 39255 0 0]É verdade que eles encontraram outro cartão[n]de chamada Phantom Thief?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_01_ [Ruthless Student]]
[s][vp 9 2 65535 42256 0 0]Ouvi dizer que os ladrões fantasmas[n]derrubaram aquele anel de crime...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_03_ [Ruthless Student]]
[s][vp 9 2 65535 43350 0 0]Com esse sindicato do crime desaparecido,[n]não precisamos mais ter medo enquanto[n]passeava pela cidade.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_04_ [Ruthless Student]]
[s][vp 9 2 65535 41704 0 0]Os ladrões Phantom finalmente estão ficando[n]sérios![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_05_ [Ruthless Student]]
[s][vp 9 2 65535 43308 0 0]Então foi por causa de ladrões fantasmas que[n]Kaneshiro foi preso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_01_ [Ruthless Student]]
[s][vp 9 2 65535 39506 0 0]Parece que mais e mais pessoas estão[n]postando no fórum Phantom Thief.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_03_ [Ruthless Student]]
[s][vp 9 2 65535 42356 0 0]Todo mundo online está falando sobre ladrões[n]Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_04_ [Ruthless Student]]
[s][vp 9 2 65535 40503 0 0]O Fórum Phantom Thieves está sendo inundado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_05_ [Ruthless Student]]
[s][vp 9 2 65535 44804 0 0]Espere, você não ouviu falar do site[n]Aficionado Phantom!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_01_ [Ruthless Student]]
[s][vp 9 2 65535 38403 0 0]Esses ladrões fantasmas estão finalmente[n]começando a distribuir alguma justiça real![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_02_ [Ruthless Student]]
[s][vp 9 2 65535 38506 0 0]Estou realmente curioso sobre quem realmente[n]são os ladrões Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_03_ [Ruthless Student]]
[s][vp 9 2 65535 43300 0 0]Eu sabia! Eu sabia que os ladrões fantasmas[n]eram reais![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_04_ [Ruthless Student]]
[s][vp 9 2 65535 40304 0 0]Você acha que Kamoshida foi o primeiro[n]emprego dos ladrões Phantom, afinal?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_05_ [Ruthless Student]]
[s][vp 9 2 65535 38906 0 0]Os ladrões fantasmas são muito legais. Basta[n]olhar para a maneira como eles derrotam o[n]mal e outras coisas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_01_ [Ruthless Student]]
[s][vp 9 2 65535 37553 0 0]Mal posso esperar para ver o que vai[n]acontecer em um confronto entre os ladrões[n]e hackers fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_02_ [Ruthless Student]]
[s][vp 9 2 65535 38754 0 0]Quem você acha que vai ganhar? Os ladrões[n]fantasmas ou medjed?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_03_ [Ruthless Student]]
[s][vp 9 2 65535 43253 0 0]Estou ansioso pelo próximo confronto do[n]Phantom Thieves contra os hackers![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_04_ [Ruthless Student]]
[s][vp 9 2 65535 42554 0 0]Os ladrões Phantom versus hackers? Parece[n]que as coisas estão ficando interessantes![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_05_ [Ruthless Student]]
[s][vp 9 2 65535 45054 0 0]Medjed declarou guerra aos ladrões[n]fantasmas...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_01_ [Ruthless Student]]
[s][vp 9 2 65535 38404 0 0]A menos que os ladrões fantasmas atendam às[n]suas demandas, eles causam alguns danos[n]graves...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_03_ [Ruthless Student]]
[s][vp 9 2 65535 43601 0 0]O que os ladrões fantasmas estão fazendo!?[n]Apresse-se e retire-os antes que eles nos[n]atacem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_04_ [Ruthless Student]]
[s][vp 9 2 65535 39804 0 0]Como os ladrões fantasmas vão responder às[n]ameaças dos hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_05_ [Ruthless Student]]
[s][vp 9 2 65535 40256 0 0]Aqueles ladrões fantasmas vão parar esses[n]hackers antes que possam fazer qualquer[n]coisa, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_01_ [Ruthless Student]]
[s][vp 9 2 65535 37806 0 0]Os ladrões fantasmas são muito melhores que[n]a polícia![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_02_ [Ruthless Student]]
[s][vp 9 2 65535 40556 0 0]Os ladrões Phantom derrubaram Medjed![n]Ninguém pode ficar em seu caminho![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_03_ [Ruthless Student]]
[s][vp 9 2 65535 43303 0 0]Eu sabia que poderíamos contar com os[n]ladrões Phantom! Vou mostrar a eles mais[n]apoio![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_04_ [Ruthless Student]]
[s][vp 9 2 65535 40750 0 0]Por que devemos nos preocupar?[n]Esses ladrões fantasmas estão por aí,[n]lutando por nós.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_05_ [Ruthless Student]]
[s][vp 9 2 65535 42606 0 0]Você acredita que eles derrubaram uma[n]organização internacional de hackers? Que[n]incrível![n][f 1 2 180][e]

[msg MSG_GRT_main_All_150_01_ [Ruthless Student]]
[s][vp 9 2 65535 44654 0 0]Eu me pergunto se o diretor estava[n]pressionando eles...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_150_02_ [Ruthless Student]]
[s][vp 9 2 65535 42202 0 0]Estou começando a me preocupar! O drama[n]nesta escola prejudicará minhas chances de[n]faculdade?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_150_03_ [Ruthless Student]]
[s][vp 9 2 65535 42913 0 0]A reputação de Shujin acabou de descer o[n]ralo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_01_ [Ruthless Student]]
[s][vp 9 2 65535 38405 0 0]Ele conseguiu o que merecia, não foi? Quero[n]dizer, ele deixou Kamoshida fazer todas[n]essas coisas com seus alunos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_03_ [Ruthless Student]]
[s][vp 9 2 65535 40454 0 0]Os ladrões fantasmas mudaram seu coração, e[n]então ele se matou para compensar isso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_04_ [Ruthless Student]]
[s][vp 9 2 65535 41704 0 0]Então espere, ele se matou por culpa,[n]causado por ladrões fantasmas mudando seu[n]coração...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_05_ [Ruthless Student]]
[s][vp 9 2 65535 38255 0 0]Talvez seja o direito dele cometer suicídio,[n]mas eu gostaria que não causasse tantos[n]problemas para nós.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_01_ [Ruthless Student]]
[s][vp 9 2 65535 37556 0 0]A mídia realmente está de olho na nossa[n]escola.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_03_ [Ruthless Student]]
[s][vp 9 2 65535 38553 0 0]Como você pode não saber sobre os ladrões[n]Phantom!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_04_ [Ruthless Student]]
[s][vp 9 2 65535 37503 0 0]Tudo ficará bem se deixarmos para os ladrões[n]Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_05_ [Ruthless Student]]
[s][vp 9 2 65535 40206 0 0]Espero que aqueles ladrões fantasmas[n]continuem derrubando o mal e os[n]transgressores.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_01_ [Ruthless Student]]
[s][vp 9 2 65535 39404 0 0]A filha do presidente Okumura realmente vai[n]para a nossa escola?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_03_ [Ruthless Student]]
[s][vp 9 2 65535 41404 0 0]Ouvi dizer que a filha do presidente Okumura[n]é o terceiro ano da nossa escola![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_04_ [Ruthless Student]]
[s][vp 9 2 65535 46304 0 0]Aparentemente, esse CEO corrupto de todos[n]está falando tem uma filha que vai para a[n]nossa escola...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_05_ [Ruthless Student]]
[s][vp 9 2 65535 43804 0 0]O filho do presidente Okumura vai para a[n]nossa escola!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_01_ [Ruthless Student]]
[s][vp 9 2 65535 45804 0 0]Que tipo de vilão você acha que os ladrões[n]Phantom irão depois do próximo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_03_ [Ruthless Student]]
[s][vp 9 2 65535 38006 0 0]Não há nada a temer, desde que os ladrões[n]fantasmas estejam aqui![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_04_ [Ruthless Student]]
[s][vp 9 2 65535 42506 0 0]Ficaremos bem com os ladrões fantasmas nos[n]protegendo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_05_ [Ruthless Student]]
[s][vp 9 2 65535 46353 0 0]Alguém precisa excluir todas as pessoas más[n]e perversas em nosso mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_01_ [Ruthless Student]]
[s][vp 9 2 65535 43156 0 0]Esses adultos irresponsáveis precisam ser[n]derrubados pelos ladrões fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_02_ [Ruthless Student]]
[s][vp 9 2 65535 38206 0 0]Apenas se apresse e derrube-o, Phantom[n]Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_03_ [Ruthless Student]]
[s][vp 9 2 65535 42956 0 0]Eu sabia que eles iriam atrás do presidente[n]Okumura![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_04_ [Ruthless Student]]
[s][vp 9 2 65535 42650 0 0]Faça-o descer de joelhos e groveld![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_05_ [Ruthless Student]]
[s][vp 9 2 65535 42403 0 0]Eu esperava que eles enviassem um cartão de[n]visita! Mal posso esperar para ver o que[n]acontece a seguir![n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_01_ [Ruthless Student]]
[s][vp 9 2 65535 43057 0 0]Fiquei muito chocado quando vi a conferência[n]de imprensa do Presidente Okumura...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_02_ [Ruthless Student]]
[s][vp 9 2 65535 44602 0 0]Eu nunca imaginei que os ladrões Phantom[n]faria algo assim...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_03_ [Ruthless Student]]
[s][vp 9 2 65535 42762 0 0]O que aconteceu com o Presidente Okumura não[n]era CG... certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_04_ [Ruthless Student]]
[s][vp 9 2 65535 41902 0 0]Você viu a conferência de imprensa com o[n]Presidente Okumura?[n]Isso foi completamente louco...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_05_ [Ruthless Student]]
[s][vp 9 2 65535 40607 0 0]O que aconteceu durante a conferência foi[n]realmente real, não foi...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_01_ [Ruthless Student]]
[s][vp 9 2 65535 37857 0 0]Matá-lo estava cruzando a linha, Phantom[n]Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_03_ [Ruthless Student]]
[s][vp 9 2 65535 38357 0 0]Eu nunca pensei que os ladrões fantasmas[n]seriam assassinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_04_ [Ruthless Student]]
[s][vp 9 2 65535 37557 0 0]Então eles estão mudando o coração das[n]pessoas no começo, apenas para nos enganar!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_05_ [Ruthless Student]]
[s][vp 9 2 65535 42401 0 0]Eles o mataram!?[n]Isso é nojento![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_01_ [Ruthless Student]]
[s][vp 9 2 65535 42551 0 0]Eles estão até tentando pegar os ladrões[n]Phantom!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_03_ [Ruthless Student]]
[s][vp 9 2 65535 42601 0 0]Ouvi dizer que tudo o que eles fizeram até[n]agora eram apenas eles se aquecendo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_04_ [Ruthless Student]]
[s][vp 9 2 65535 39408 0 0]Alguém precisa prender os ladrões Phantom![n]Não importa quem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_05_ [Ruthless Student]]
[s][vp 9 2 65535 40857 0 0]Quando a polícia vai agir!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_01_ [Ruthless Student]]
[s][vp 9 2 65535 38109 0 0]Então, a polícia finalmente levou a sério a[n]prisão dos ladrões Phantom...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_02_ [Ruthless Student]]
[s][vp 9 2 65535 38407 0 0]Ouvi dizer que você pode obter dinheiro de[n]recompensa por fornecer informações sobre[n]os ladrões Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_03_ [Ruthless Student]]
[s][vp 9 2 65535 40605 0 0]Ouvi dizer que eles colocaram uma recompensa[n]nos ladrões fantasmas! Eles estão[n]finalmente fazendo a sua mudança...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_04_ [Ruthless Student]]
[s][vp 9 2 65535 39109 0 0]Agora eles estão fazendo alguma coisa!? Eles[n]não estão trabalhando um pouco lentos?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_05_ [Ruthless Student]]
[s][vp 9 2 65535 42407 0 0]Espero que isso convença os ladrões[n]fantasmas a parar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_01_ [Ruthless Student]]
[s][vp 9 2 65535 46251 0 0]Eles estão até tentando pegar os ladrões[n]Phantom!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_03_ [Ruthless Student]]
[s][vp 9 2 65535 42351 0 0]Ouvi dizer que tudo o que eles fizeram até[n]agora eram apenas eles se aquecendo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_04_ [Ruthless Student]]
[s][vp 9 2 65535 39757 0 0]Tudo está bagunçado por causa dos ladrões[n]fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_05_ [Ruthless Student]]
[s][vp 9 2 65535 42357 0 0]Alguém pega os ladrões Phantom! Não importa[n]quem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_01_ [Ruthless Student]]
[s][vp 9 2 65535 40552 0 0]De jeito nenhum... eu pensei que ele era um[n]shoo-in para o primeiro-ministro...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_03_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_04_ [Ruthless Student]]
[s][vp 9 2 65535 40352 0 0]Todas essas coisas representativas Shido[n]disseram, elas não podem ser verdadeiras...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_05_ [Ruthless Student]]
[s][vp 9 2 65535 42902 0 0]O que vamos fazer sem o representante[n]Shido...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_01_ [Ruthless Student]]
[s][vp 9 2 65535 42102 0 0]Não importa o que eu faço.[n]Não vai mudar nada...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_03_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_04_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_05_ [Ruthless Student]]
[s][vp 9 2 65535 44202 0 0]Alguém, por favor, faça algo sobre tudo[n]isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_01_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_03_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_04_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_05_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_06_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_07_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_08_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_09_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_01_ [Ruthless Student]]
[s][vp 9 2 65535 43062 0 0]Beber, fumar, roubo...[n]Eu ouvi que esse cara fez tudo.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_02_ [Ruthless Student]]
[s][vp 9 2 65535 42112 0 0]Então é ele? Esse é o cara com registro[n]criminal?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_03_ [Ruthless Student]]
[s][vp 9 2 65535 43313 0 0]Esse aluno transferido se envolveu em todos[n]os tipos de coisas obscuras, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_04_ [Ruthless Student]]
[s][vp 9 2 65535 42263 0 0]Ele parece inofensivo, mas fez algumas[n]coisas loucas, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_05_ [Ruthless Student]]
[s][vp 9 2 65535 42812 0 0]Esse aluno transferido realmente cometeu[n]alguns crimes, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_01_ [Ruthless Student]]
[s][vp 9 2 65535 43162 0 0]Ouvi dizer que ele puxa facas para pessoas[n]sem nenhum aviso.[n]Esse cara é um canhão solto.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_03_ [Ruthless Student]]
[s][vp 9 2 65535 43312 0 0]Ouvi dizer que quem faz contato visual com[n]ele tem que ser enviado para o hospital...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_04_ [Ruthless Student]]
[s][vp 9 2 65535 42712 0 0]Não o olhe nos olhos![n]Ele vai bater em você em quase morte...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_05_ [Ruthless Student]]
[s][vp 9 2 65535 43112 0 0]Todo mundo está dizendo que ele usa armas[n]para ameaçar as pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_01_ [Ruthless Student]]
[s][vp 9 2 65535 40155 0 0]Ugh, a polícia está aqui?[n]Vamos lá, me dê um tempo...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_03_ [Ruthless Student]]
[s][vp 9 2 65535 40454 0 0]Parece que a polícia vai investigar as[n]coisas sobre a nossa escola.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_04_ [Ruthless Student]]
[s][vp 9 2 65535 40355 0 0]A escola ficou tão barulhenta com toda essa[n]comoção...[n]Está me dando nos nervos.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_05_ [Ruthless Student]]
[s][vp 9 2 65535 42605 0 0]A polícia está andando, questionando as[n]pessoas, aparentemente.[n]Espero que eles saiam em breve.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_01_ [Ruthless Student]]
[s][vp 9 2 65535 42702 0 0]Vou ter que ficar acordado a noite toda para[n]Cram e depois adivinhar o que eu não sei...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_02_ [Ruthless Student]]
[s][vp 9 2 65535 42560 0 0]Quem se importa com os exames? Eu não sinto[n]vontade de estudar de qualquer maneira...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_03_ [Ruthless Student]]
[s][vp 9 2 65535 40951 0 0]Já está na hora do meio do meio!?[n]Tiro, eu preciso começar a revisar.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_04_ [Ruthless Student]]
[s][vp 9 2 65535 42658 0 0]Não temos atividades de clube, para que eu[n]possa apenas estudar.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_05_ [Ruthless Student]]
[s][vp 9 2 65535 41405 0 0]Os intermediários estão em breve, hein?[n]Que aborrecimento...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_01_ [Ruthless Student]]
[s][vp 9 2 65535 39052 0 0]Está quase na hora das finais.[n]É melhor me certificar de estudar o[n]suficiente...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_03_ [Ruthless Student]]
[s][vp 9 2 65535 42011 0 0]Preciso obter uma pontuação melhor nas[n]minhas finais do que no meu meio-médio![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_04_ [Ruthless Student]]
[s][vp 9 2 65535 39402 0 0]Cara, já é temporada de finais?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_05_ [Ruthless Student]]
[s][vp 9 2 65535 38010 0 0]Já está na hora das finais?[n]Eu só quero ir para meus clubes...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_01_ [Ruthless Student]]
[s][vp 9 2 65535 42204 0 0]Ah, sim, você já ouviu falar desse detetive,[n]Akechi?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_03_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_04_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_05_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_01_ [Ruthless Student]]
[s][vp 9 2 65535 39103 0 0]Você está do lado de Akechi, ou os ladrões[n]do Phantom?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_02_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_03_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_04_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_05_ [Ruthless Student]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_01_ [Ruthless Student]]
[s][vp 9 2 65535 38755 0 0]Essas pontuações só precisam ser um acaso.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_02_ [Ruthless Student]]
[s][vp 9 2 65535 39402 0 0]Um delinqüente que também é inteligente...[n]Isso é meio assustador, não é?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_03_ [Ruthless Student]]
[s][vp 9 2 65535 43201 0 0]Ele roubou as respostas do teste ou algo[n]assim?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_04_ [Ruthless Student]]
[s][vp 9 2 65535 38751 0 0]Aposto que ele apenas traiu durante o teste.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_05_ [Ruthless Student]]
[s][vp 9 2 65535 38905 0 0]Obter boas pontuações na escola não apagará[n]o que ele fez.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_01_ [Ruthless Student]]
[s][vp 9 2 65535 38752 0 0]Ele está no topo da classe? Qual é o negócio[n]dele?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_02_ [Ruthless Student]]
[s][vp 9 2 65535 39502 0 0]Eu me sinto totalmente derrotado.[n]Tenho tanta vergonha de mim mesma.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_03_ [Ruthless Student]]
[s][vp 9 2 65535 38305 0 0]Ele realmente conseguiu a pontuação superior?[n]Eles cometeram um erro quando estavam[n]classificando seus testes?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_04_ [Ruthless Student]]
[s][vp 9 2 65535 42663 0 0]Gostaria de saber se devo pedir que ele me[n]ensine. Ele é tão assustador embora...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_05_ [Ruthless Student]]
[s][vp 9 2 65535 42362 0 0]É melhor ele não deixar isso ir à sua[n]cabeça. Ele conseguir a pontuação superior[n]provavelmente foi um acaso, de qualquer[n]maneira.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_01_ [Ruthless Student]]
[s][vp 9 2 65535 37552 0 0]Antes de eu perceber, ele estava tirando[n]notas melhores do que eu...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_02_ [Ruthless Student]]
[s][vp 9 2 65535 41704 0 0]Eu pensei que ele era apenas um delinqüente,[n]mas ele é realmente muito bom...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_03_ [Ruthless Student]]
[s][vp 9 2 65535 37701 0 0]Você viu as notas dos testes?[n]As pontuações principais foram loucas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_04_ [Ruthless Student]]
[s][vp 9 2 65535 38704 0 0]Mesmo que ele tenha um registro criminal,[n]ele ainda tem essas pontuações?[n]Ele pode ser grande algum dia...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_05_ [Ruthless Student]]
[s][vp 9 2 65535 39652 0 0]Você não pode dizer ao olhar para ele, mas[n]acho que ele realmente estuda como um aluno[n]sério...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_01_ [Ruthless Student]]
[s][vp 9 2 65535 40104 0 0]Eu zombei dele, mas obter a pontuação[n]superior é incrível...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_02_ [Ruthless Student]]
[s][vp 9 2 65535 42210 0 0]A maneira como sua mente funciona[n]provavelmente é completamente diferente da[n]nossa...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_03_ [Ruthless Student]]
[s][vp 9 2 65535 43304 0 0]Eu li isso errado?[n]Ele não pode ter conseguido a pontuação[n]superior...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_04_ [Ruthless Student]]
[s][vp 9 2 65535 38404 0 0]Quando ele se tornou o topo da classe?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_05_ [Ruthless Student]]
[s][vp 9 2 65535 39605 0 0]Eu acho que ele realmente estava estudando[n]todo esse tempo...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_01_ [Ruthless Student]]
[s][vp 9 2 65535 38504 0 0]Eu tenho que admitir, ele realmente é tão[n]inteligente. Quero dizer, todas as[n]pontuações dele são tão boas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_02_ [Ruthless Student]]
[s][vp 9 2 65535 40152 0 0]Eu me sinto burro por estar com tanto medo[n]dele. Ele é realmente um aluno muito bom.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_03_ [Ruthless Student]]
[s][vp 9 2 65535 40955 0 0]É bom que ele tenha boas notas, mas ele[n]ainda é meio assustador...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_04_ [Ruthless Student]]
[s][vp 9 2 65535 40155 0 0]Mesmo que ele tenha uma boa pontuação, como[n]podemos ter certeza de que ele de repente[n]não causará problemas novamente?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_05_ [Ruthless Student]]
[s][vp 9 2 65535 40805 0 0]Entendo que ele é inteligente, mas ainda me[n]sinto mais confortável em manter minha[n]distância dele, sabe?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_01_ [Ruthless Student]]
[s][vp 9 2 65535 41705 0 0]Na verdade, é meio assustador quando alguém[n]assim obtém a pontuação superior...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_02_ [Ruthless Student]]
[s][vp 9 2 65535 44304 0 0]Ele pode até ser mais inteligente que[n]Akechi...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_03_ [Ruthless Student]]
[s][vp 9 2 65535 42363 0 0]Ele é realmente inteligente, mas ainda não[n]tenho tanta certeza sobre ele. Ele pode[n]acabar se tornando um gênio do mal...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_04_ [Ruthless Student]]
[s][vp 9 2 65535 44904 0 0]É inacreditável que ele tenha a pontuação[n]máxima.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_05_ [Ruthless Student]]
[s][vp 9 2 65535 42602 0 0]Bem, ele é o mais inteligente da nossa[n]escola...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_01_ [Ruthless Student]]
[s][vp 9 2 65535 42505 0 0]Esse cara joga futebol desde os dois?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_02_ [Ruthless Student]]
[s][vp 9 2 65535 43305 0 0]O que há com todas as ataduras...? Alguém[n]quebrou o ombro?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_03_ [Ruthless Student]]
[s][vp 9 2 65535 42502 0 0]Este foi o último ano do treinador? Eu não[n]quero que ele seja substituído...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_04_ [Ruthless Student]]
[s][vp 9 2 65535 46403 0 0]Preocupe-se com o tempo depois.[n]Apenas divirta-se com isso por enquanto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_05_ [Ruthless Student]]
[s][vp 9 2 65535 42251 0 0]Ele trocou de clubes!? Quero dizer, ele era[n]um de nós antes, não foi?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_06_ [Ruthless Student]]
[s][vp 9 2 65535 42802 0 0]HM? Não nos disseram para não vir para o[n]clube...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_01_ [Ruthless Student]]
[s][vp 9 2 65535 42200 0 0]Talvez eu tenha poupar com o velho.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_02_ [Ruthless Student]]
[s][vp 9 2 65535 43311 0 0]Meus pais são tão superprotetores...[n]Oh, eu tenho que chegar em casa![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_03_ [Ruthless Student]]
[s][vp 9 2 65535 42504 0 0]Estou tentando uma recomendação esportiva[n]desde que comecei aqui.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_04_ [Ruthless Student]]
[s][vp 9 2 65535 42953 0 0]Estou tirando hoje.[n]Vou fazer compras com minha irmã.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_05_ [Ruthless Student]]
[s][vp 9 2 65535 42205 0 0]Foi outra pessoa que recebeu tratamento?[n]Bem, temos pessoas suficientes agora.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_503_01_ [Ruthless Student]]
[s][vp 9 2 65535 42655 0 0]Aconselhamento...? Então, o que exatamente[n]você faz lá?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_503_02_ [Ruthless Student]]
[s][vp 9 2 65535 42953 0 0]Dr. Maruki?[n]Aquele cara é totalmente uma droga...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_503_03_ [Ruthless Student]]
[s][vp 9 2 65535 42503 0 0]Aposto que o conselheiro será popular.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_503_04_ [Ruthless Student]]
[s][vp 9 2 65535 43354 0 0]Ele está no escritório da enfermeira, certo?[n]Talvez eu vá se sentir vontade...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_504_01_ [Ruthless Student]]
[s][vp 9 2 65535 42101 0 0]Este evento de limpeza é um arrasto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_504_02_ [Ruthless Student]]
[s][vp 9 2 65535 42451 0 0]A escola está preocupada com sua imagem com[n]todas essas coisas sobre Kamoshida?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_504_03_ [Ruthless Student]]
[s][vp 9 2 65535 42101 0 0]Vamos acabar com isso e depois ir para[n]casa...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_504_04_ [Ruthless Student]]
[s][vp 9 2 65535 42351 0 0]Um evento de limpeza...[n]Você está brincando comigo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_601_01_ [Ruthless Student]]
[s][vp 9 2 65535 42101 0 0]Yoshizawa-san tem um rosto tão bonito...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_601_02_ [Ruthless Student]]
[s][vp 9 2 65535 42350 0 0]Estou com tanto ciúme de Yoshizawa-san...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_601_03_ [Ruthless Student]]
[s][vp 9 2 65535 42655 0 0]Eu acho que é difícil ter de atender a todas[n]essas expectativas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_601_04_ [Ruthless Student]]
[s][vp 9 2 65535 43352 0 0]Prodígios são realmente outra coisa...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_505_01_ [Ruthless Student]]
[s][vp 9 2 65535 42702 0 0]Existe algo acontecendo entre Yoshizawa-san[n]e o aluno transferido?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_505_02_ [Ruthless Student]]
[s][vp 9 2 65535 42602 0 0]Ela tem alguma conexão com esse cara?[n]Caramba...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_505_03_ [Ruthless Student]]
[s][vp 9 2 65535 43152 0 0]Yoshizawa-san está caindo com uma multidão[n]ruim...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_505_04_ [Ruthless Student]]
[s][vp 9 2 65535 42452 0 0]Vamos lá, os alunos de honra não devem se[n]associar a personagens obscuros...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_01_ [Ruthless Student]]
[s][vp 9 2 65535 43002 0 0]Vocês estão sendo muito duros.[n]Todos cometem erros...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_02_ [Ruthless Student]]
[s][vp 9 2 65535 43252 0 0]Ela não tem ninguém para culpar, mas a si[n]mesma se não conseguir obter esses[n]resultados...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_03_ [Ruthless Student]]
[s][vp 9 2 65535 43151 0 0]Eu acho patético que todos estejam se[n]aglomerando com Badmouth.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_04_ [Ruthless Student]]
[s][vp 9 2 65535 43255 0 0]Você está brincando?[n]Ela não é material medalhista.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_603_01_ [Ruthless Student]]
[s][vp 9 2 65535 43002 0 0]Eu vi a coisa toda...[n]Foi aquele segundo ano...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_603_02_ [Ruthless Student]]
[s][vp 9 2 65535 42452 0 0]Ela está viva? Ela caiu todo o caminho do[n]telhado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_603_03_ [Ruthless Student]]
[s][vp 9 2 65535 42302 0 0]O que poderia ter feito com isso fazer[n]isso...? Pobre menina...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_603_04_ [Ruthless Student]]
[s][vp 9 2 65535 42602 0 0]Eu nunca vou para o telhado de novo... Não[n]consigo lidar com coisas assim...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_603_05_ [Ruthless Student]]
[s][vp 9 2 65535 43155 0 0]Não me pergunte...[n]Ela provavelmente está viva...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_603_06_ [Ruthless Student]]
[s][vp 9 2 65535 43201 0 0]Eu vi pessoas tirando fotos![n]Inacreditável...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_502_01_ [Ruthless Student]]
[s][vp 9 2 65535 43002 0 0]Um estudante de honra e uma beleza. Fale[n]sobre a minha liga...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_502_02_ [Ruthless Student]]
[s][vp 9 2 65535 43350 0 0]Passei por um primeiro ano perto da academia[n]outro dia![n][f 1 2 180][e]

[msg MSG_GRT_main_All_502_03_ [Ruthless Student]]
[s][vp 9 2 65535 42850 0 0]Só de olhar para ela é felicidade o[n]suficiente para mim...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_502_04_ [Ruthless Student]]
[s][vp 9 2 65535 42800 0 0]Esse aluno de honra é uma beleza absoluta![n][f 1 2 180][e]

[msg MSG_GRT_main_All_502_05_ [Ruthless Student]]
[s][vp 9 2 65535 43105 0 0]Ela usava uma camisa da escola regular. Eu[n]gostaria que ela viesse em sua roupa de[n]ginasta.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_502_06_ [Ruthless Student]]
[s][vp 9 2 65535 42652 0 0]Ela realmente tem um rosto fofo.[n]É por isso que todo mundo está falando sobre[n]isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_502_07_ [Ruthless Student]]
[s][vp 9 2 65535 43252 0 0]Deve ser legal... eu gostaria de poder fazer[n]meus exames em um dia diferente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_502_08_ [Ruthless Student]]
[s][vp 9 2 65535 42651 0 0]Eu nunca vi alguém dormindo durante a aula.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_502_09_ [Ruthless Student]]
[s][vp 9 2 65535 43151 0 0]Talvez eu comece a fazer ginástica.[n][f 1 2 180][e]

[msg Quest34_target_00_00 [ターゲット34]]
[s]クエスト34のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][f 4 23 1 600 3 10 0 0][w][e]
[s]クエストの進捗は受注可能状態です。[n][w][e]

[msg Quest34_target_sinjyo_00]
[s]クエスト34のテスト心情メッセージです。[n][w][e]

[msg MSG_quest34_morgana_01 [Morgana]]
[s]クエスト34のモルガナメッセージです。[n]ターゲット用です。[n][w][e]

[msg Quest34_target_01_00 [ターゲット34]]
[s]クエスト34のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][f 4 23 1 600 3 10 0 0][w][e]
[s]クエストの進捗はメメントス突入可能状態です。[n][w][e]

[msg Quest34_target_sinjyo_01]
[s]クエスト34のテスト心情メッセージです。[n][w][e]

[msg Quest34_target_02_00 [ターゲット34]]
[s]クエスト34のテストメッセージです。[n]表示後、キャンプでの状態を確認して下さい。[n][f 4 23 1 600 3 10 0 0][w][e]
[s]クエストの進捗はミッションクリア状態です。[n][w][e]

[msg Quest34_target_sinjyo_02]
[s]クエスト34のテスト心情メッセージです。[n][w][e]

