[msg mini_EV_e200_146_mes01 [Segurança]]
[s]Hum? Acho que não reconheço você.[n]Você é um novo contratado?[n][w][e]
[s]...Então? Você precisa de algo?[n][w][e]

[sel mini_EV_e200_146_selA top]
[s]Desligamos os lasers.[e]
[s]Esqueci a senha.[e]
[s]Prazer em conhecê-lo.[e]

[msg mini_EV_e200_146_selA_0_ [Segurança]]
[s]Ah, isso é fácil.[n]Digite 07734 na máquina[n]da sala de segurança.[n][w][e]
[s]Entendeu o truque? Se você lê[n]de certa maneira, é "olá".[n]Então é fácil de lembrar, certo?[n][w][e]

[msg mini_EV_e200_146_selA_1_ [Segurança]]
[s]Oh, a[n]senha da sala segura? Disque 07734.[n][w][e]
[s]Entendeu o truque? Se você lê[n]de certa maneira, é "olá".[n]Então é fácil de lembrar, certo?[n][w][e]

[msg mini_EV_e200_146_selA_2_ [Segurança]]
[s]Bem, você é muito educado. Eu gosto de você. Se[n]precisar de alguma coisa, diga-me.[n][w][e]

[msg mini_EV_e200_146_mes02 [Segurança]]
[s]...Espera, por que você quer desligar[n]os lasers?[n][w][e]

[sel mini_EV_e200_146_selB top]
[s]Eu sou um intruso.[e]
[s]Vou roubar o Tesouro.[e]
[s]Eu queria tentar.[e]

[msg mini_EV_e200_146_selB_0_ [Segurança]]
[s]Eu sabia![n][w][e]

[msg mini_EV_e200_146_selB_1_ [Segurança]]
[s]O que?!? Então VOCÊ É o intruso![n][w][e]

[msg mini_EV_e200_146_selB_2_ [Segurança]]
[s]Uau, você também?[n]Na verdade, eu[n]fiz isso também.[n][w][e]
[s]Tente... não contar ao Lord[n]Madarame, ok?[n][w][e]

[msg mini_EV_e200_146_mes03]
[s]......[n][w][e]

[sel mini_EV_e200_146_selC top]
[s]Qual era a senha?[e]
[s]Vamos desligar os lasers?[e]

[msg mini_EV_e200_146_selC_0_ [Segurança]]
[s]Oh, a[n]senha da sala segura? Disque 07734.[n][w][e]
[s]Entendeu o truque? Se você lê[n]de certa maneira, é "olá".[n]Então é fácil de lembrar, certo?[n][w][e]

[msg mini_EV_e200_146_selC_1_ [Segurança]]
[s]Ah, isso é fácil.[n]Digite 07734 na máquina[n]da sala de segurança.[n][w][e]
[s]Entendeu o truque? Se você lê[n]de certa maneira, é "olá".[n]Então é fácil de lembrar, certo?[n][w][e]

[msg mini_EV_e200_146_mes04 [Segurança]]
[s]Parece que há intrusos.[n]Três caras mascarados e uma[n]criatura estranha.[n][w][e]
[s]Mas eles realmente acreditam que podem passar por[n]todas as medidas de segurança? Hahaha![n][w][e]

[msg D153_MOB_VOICE_TV_mes01 [Voz]]
[s][vp 8 1 65535 5000 0 0]Obrigado pela visita.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes02 [Voz]]
[s][vp 8 1 65535 5001 0 0]Neste momento há[n]uma exposição das obras[n]do grande Madarame.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes03 [Voz]]
[s][vp 8 1 65535 5002 0 0]Madarame lidera[n]a vanguarda do mundo[n]da arte japonesa.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes04 [Voz]]
[s][vp 8 1 65535 5003 0 0]Esta exposição pretende[n]exibir e partilhar[n]o fascínio destas obras.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes05 [Voz]]
[s][vp 8 1 65535 5004 0 0]As ideias de Madarame,[n]livres de quaisquer[n]noções preconcebidas...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes06 [Voz]]
[s][vp 8 1 65535 5005 0 0]...permitiu que a[n]forma de arte Nihonga[n]se desenvolvesse de novas maneiras.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes07 [Voz]]
[s][vp 8 1 65535 5006 0 0]E não só[n]ajudou a traçar[n]novos desenvolvimentos...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes08 [Voz]]
[s][vp 8 1 65535 5007 0 0]...na arte da pintura, mas[n]ele também se dedicou à[n]nova geração.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes09 [Voz]]
[s][vp 8 1 65535 5008 0 0]Ele é uma figura insubstituível[n]no panorama moderno[n]da arte japonesa.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes10 [Voz]]
[s][vp 8 1 65535 5009 0 0]Os olhos do mundo estão[n]em Madarame: como o mundo da arte irá inovar[n]agora?[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes [Eu notifico]]
[s][vp 8 1 65535 5100 0 0]Este trabalho, feito com[n]pinceladas delicadas e cuidadosas...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_2 [Eu notifico]]
[s][vp 8 1 65535 5101 0 0]...é conhecido por usar[n]cores completas e complexas.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_3 [Eu notifico]]
[s][vp 8 1 65535 5102 0 0]As características do sujeito[n]são lindamente capturadas.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_4 [Eu notifico]]
[s][vp 8 1 65535 5103 0 0]Quase parece tê-lo enfrentado em carne e osso.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_5 [Eu notifico]]
[s][vp 8 1 65535 5104 0 0]Não só manifesta[n]uma presença imponente...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_6 [Eu notifico]]
[s][vp 8 1 65535 5105 0 0]...mas também exala[n]um encanto misterioso,[n]peculiar...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_7 [Eu notifico]]
[s][vp 8 1 65535 5106 0 0]...que atrai e cativa[n]qualquer um que olhe.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_8 [Eu notifico]]
[s][vp 8 1 65535 5107 0 0]Seu charme é tal...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_9 [Eu notifico]]
[s][vp 8 1 65535 5108 0 0]...para tornar impossível[n]desviar seus olhos.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_10 [Eu notifico]]
[s][vp 8 1 65535 5109 0 0]Não seria um[n]exagero dizer que[n]esta imagem é perfeita.[n][f 1 6 65534][e]

