[msg TEST_MES]
[s]Ele tenta[n][w][e]

[sel YESNO_SEL top]
[s]Sim[e]
[s]Não[e]

[msg D06_06_MOB_MES_mes01 [Cliente]]
[s]Eu adoraria ir para o plano high stakes[n]...[n][w][e]

[msg D06_06_MOB_MES_mes02 [Cliente]]
[s]Craps e máquinas caça-níqueis... Aqui[n]é bem diferente dos[n]pisos inferiores![n][w][e]

[msg D06_06_MOB_MES_mes03 [Cliente]]
[s]Hoje a Sorte está do meu[n]lado... Já dobrei[n]minhas moedas![n][w][e]

[msg D06_06_MOB_MES_mes04 [Cliente]]
[s]Que diabos...[n]Não posso vencer![n][w][e]

[msg D06_06_MOB_MES_mes05 [Cliente]]
[s]Eu finalmente ganhei![n]Yuppieeee![n][w][e]

[msg D06_06_MOB_MES_mes06 [Cliente]]
[s]Talvez eu devesse desistir e[n]ir para casa...[n]Não, quero tentar de novo![n][w][e]

[msg D06_06_MOB_MES_mes07 [Cliente]]
[s]Minha habilidade é de pouca[n]utilidade neste andar[n]reservado para membros...[n][w][e]

[msg D06_06_MOB_MES_mes08 [Cliente]]
[s]Mais dinheiro...[n]Preciso de mais dinheiro...[n][w][e]

[msg D06_06_MOB_MES_mes09 [Cliente]]
[s]Para jogar nessa grande[n]caça-níqueis, você precisa de[n]5.000 moedas...[n][w][e]

