[sel YESNO_SEL top]
[s]はい[e]
[s]いいえ[e]

[msg NPC_GREETING_MSG]
[s]Š拶[n][w][e]

[msg NPC_01]
[s]会話[n][w][e]

[msg MSG_NARAIGOTO_001_0_0 [Mãe irritada]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Se você não se apressar, vai se[n]atrasar para a aula![n]Pare de brincar![n][w][e]

[msg MSG_NARAIGOTO_001_1_0 [Filha triste]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Eu não estou brincando.[n][w][e]
[s][vp 8 2 1 0 11 0]Por que eu tenho que fazer aulas de piano?[n]Eu não quero ser um pianista...[n][w][e]

[msg MSG_NARAIGOTO_001_2_0 [Mãe irritada]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Absurdo! Você precisa levar[n]as aulas mais a sério![n]É para o seu futuro![n][w][e]

[msg MSG_NARAIGOTO_001_3_0 [Filha triste]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Ok vejo você mais tarde...[n][w][e]

[msg MSG_NARAIGOTO_002_0_0 [Filha tímida]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Mãe, você sabia que os Phantom Thieves[n]mudam o coração das pessoas?[n][w][e]
[s][vp 8 2 1 0 11 0]Eu me pergunto se isso[n]os muda ...[n][w][e]

[msg MSG_NARAIGOTO_002_1_0 [Mãe irritada]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]O suficiente. Se você tem tempo para essas[n]tolices, também tem tempo para aprender uma nova[n]música.[n][w][e]
[s][vp 8 2 1 0 12 0]A competição está chegando![n]Se você não jogar bem,[n]sem jantar![n][w][e]

[msg MSG_NARAIGOTO_002_2_0 [Filha triste]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Não quero mais brincar...[n]Gostaria que minha mãe se tornasse[n]outra pessoa...[n][w][e]

[msg MSG_NARAIGOTO_003_0_0 [Filha tímida]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Meus amigos me convidaram para jogar vôlei em[n]nosso dia de folga.[n][w][e]

[msg MSG_NARAIGOTO_003_1_0 [Mãe irritada]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Você não pode! Como você vai tocar piano se se[n]machucar?!?[n][w][e]

[msg MSG_NARAIGOTO_003_2_0 [Filha tímida]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Então, por que não vamos juntos para algum lugar?[n]Meus amigos fazem viagens em família...[n][w][e]

[msg MSG_NARAIGOTO_003_3_0 [Mãe irritada]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Quando você é um pianista,[n]você vai viajar por todo o mundo.[n]Você só tem que continuar praticando.[n][w][e]
[s][vp 8 2 1 0 12 0]A competição está chegando.[n]Você absolutamente tem que vencer,[n]você entende?[n][w][e]

[msg MSG_NARAIGOTO_004_0_0 [Mãe histérica]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Que performance vergonhosa![n]Foi sua grande chance![n][w][e]
[s][vp 8 2 1 0 12 0]Por quê? Por que você não pode?[n]Você DEVE se tornar um pianista![n][w][e]
[s][vp 8 2 1 0 12 0]É tudo culpa sua, que você não[n]volte! Não me escute!![n][w][e]

[msg MSG_NARAIGOTO_004_1_0 [Filha de olhos brilhantes]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Desculpa... Desculpa...[n]Vou ter mais aulas...[n]*soluço*[n][w][e]

[msg MSG_NARAIGOTO_004_2_0 [Mãe histérica]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Quem deveria[n]chorar sou eu! É tudo culpa sua![n][w][e]

[msg MSG_quest30_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Parece que encontramos nosso objetivo! Vamos[n]falar sobre isso com os outros na reunião![n][w][e]

[msg MSG_NARAIGOTO_005_0_0 [Mãe mortificada]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Quando eu era jovem, queria ser pianista. Eu[n]estudei e pratiquei muito, mas...[n][w][e]
[s][vp 8 2 1 0 12 0]Sinto muito por ter forçado[n]você a perseguir meu sonho.[n]Você é livre para fazer o que quiser.[n][w][e]

[msg MSG_NARAIGOTO_005_1_0 [Filha bondosa]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Não gosto quando você fica com raiva,[n]mas gosto de piano.[n]Quero continuar tocando.[n][w][e]
[s][vp 8 2 1 0 11 0]Um dia serei pianista[n]e faremos uma turnê pelo mundo juntos.[n][w][e]

[msg MSG_NARAIGOTO_005_2_0 [Mãe mortificada]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Sinto muito... Obrigado.[n]Obrigado...[n][w][e]

[msg MSG_NARAIGOTO_006_0_0 [Mãe amorosa]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Você gostaria de fazer algo juntos[n]no seu dia de folga?[n]Eu, você e seu pai.[n][w][e]

[msg MSG_NARAIGOTO_006_1_0 [Filha feliz]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Eu quero ir às compras com você,[n]então brincar com o papai...[n][w][e]
[s][vp 8 2 1 0 11 0]Ah, e também quero ver algumas partituras! Eu[n]quero aprender uma nova música![n][w][e]

[msg MSG_NARAIGOTO_006_2_0 [Mãe amorosa]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]É claro. Ok, tenha cuidado.[n][w][e]

[msg MSG_NARAIGOTO_006_3_0 [Filha feliz]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Obrigado mãe! Farei o meu[n]melhor na aula![n][w][e]

[msg MSG_TUMAARASOI_001_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Esses incidentes me apavoram.[n]Meu marido acabou de ser[n]promovido... ele não pode morrer.[n][w][e]

[msg MSG_TUMAARASOI_001_1_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Vivemos tempos terríveis...[n]só peço que meu marido[n]esteja bem.[n][w][e]

[msg MSG_TUMAARASOI_001_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 20 20 0 10][vp 8 2 1 0 19 0]Ohoh, ela vai se sair bem sob a supervisão do[n]meu marido...[n]contanto que ela faça sua parte.[n][w][e]
[s][vp 8 2 1 0 19 0]Mica pode ter suas asas cortadas por[n]algum preguiçoso. Oh oh oh...[n][w][e]

[msg MSG_TUMAARASOI_002_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Por acaso seu filho frequenta Shujin? Ouvi dizer[n]que é uma escola bastante rígida.[n][w][e]
[s][vp 8 2 1 0 19 0]Deve ser difícil, com todos os alunos[n]rudes ... ohoho, quero dizer[n]único" lá.[n][w][e]

[msg MSG_TUMAARASOI_002_1_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]É verdade, ele não está indo muito bem na escola.[n]Ele terá tirado de seu pai. É difícil.[n][w][e]

[msg MSG_TUMAARASOI_002_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 20 10 0 10][vp 8 2 1 0 19 0]Bem, por trás de todo grande homem há uma grande[n]mulher, e por trás de todo filho há uma grande[n]mãe. Ooh.[n][w][e]

[msg MSG_TUMAARASOI_003_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Meu marido recebeu um[n]convite para a exposição de Madarame.[n]Gostaria de se juntar a nós?[n][w][e]

[msg MSG_TUMAARASOI_003_1_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Oh não. Nenhum de nós pode[n]distinguir uma obra de arte[n]de uma crosta.[n][w][e]

[msg MSG_TUMAARASOI_003_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 20 10 0 10][vp 8 2 1 0 19 0]Bem, você nunca será[n]culto se não se acostumar a[n]apreciar coisas bonitas.[n][w][e]

[msg MSG_TUMAARASOI_004_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]A exibição de Madarame foi[n]incrível.[n][w][e]
[s][vp 8 2 1 0 19 0]Quando me assumi, me senti tão[n]orgulhoso de ser japonês. Ooh...[n][w][e]

[msg MSG_TUMAARASOI_004_1_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Mas então foi você que eu vi na TV durante o[n]noticiário.[n][w][e]

[msg MSG_TUMAARASOI_004_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 20 10 0 10][vp 8 2 1 0 19 0]Oh Deus, sério?[n]Eu não tinha ideia. Ohhoho...[n][w][e]

[msg MSG_TUMAARASOI_005_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Madarame acabou por ser um vigarista nojento![n]Aquele se preocupa somente consigo mesmo.[n][w][e]

[msg MSG_TUMAARASOI_005_1_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Plágio, né? E de seu próprio[n]aluno também.[n][w][e]

[msg MSG_TUMAARASOI_005_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Ah, tem gente por aí,[n]ele assim... que se faz passar por seu[n]o trabalho árduo dos outros.[n][w][e]

[msg MSG_TUMAARASOI_005_3_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Ohoho... Sim, meu marido também estava[n]muito chateado.[n][w][e]

[msg MSG_TUMAARASOI_006_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Eu continuo ouvindo sobre essas histórias de[n]chantagem... é melhor seu marido tomar cuidado.[n][w][e]

[msg MSG_TUMAARASOI_006_1_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Felizmente, seu salário é[n]tão escasso que não[n]precisamos nos preocupar com tal ocorrência.[n][w][e]

[msg MSG_TUMAARASOI_006_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Como você é corajoso. Nós[n]temos muito mais medo de[n]correr o risco.[n][w][e]

[msg MSG_TUMAARASOI_006_3_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Acho que há coisas que[n]uma família rica como a sua[n]nunca consegue entender...[n][w][e]

[msg MSG_TUMAARASOI_007_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Não posso permitir que meu filho seja[n]chantageado! Por que a polícia não faz mais[n]sobre isso!?![n][w][e]

[msg MSG_TUMAARASOI_007_1_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Deve ter sido terrível.[n]O que aconteceu?[n][w][e]

[msg MSG_TUMAARASOI_007_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Mais do que terrível! Por sorte,[n]ele perdeu apenas uma[n]carteira barata. Coisas de 100.000 ienes.[n][w][e]

[msg MSG_TUMAARASOI_007_3_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Teria sido uma tragédia para nós.[n]Mas esperamos[n]menos de sua família. Ohhoho...[n][w][e]

[msg MSG_TUMAARASOI_008_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Os Phantom Thieves consertaram a[n]máfia, não é? Então eles aprendem a[n]machucar meu filho.[n][w][e]
[s][vp 8 2 1 0 19 0]Agora vou apoiar totalmente os Ladrões.[n]Vamos torcer para que eles entreguem[n]justiça mais maçãs podres![n][w][e]

[msg MSG_TUMAARASOI_008_1_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Eu só posso imaginar o que a polícia está[n]fazendo. Eles não parecem muito confiáveis para[n]mim.[n][w][e]

[msg MSG_TUMAARASOI_008_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Concordo. Embora eu tenha certeza de que eles[n]estão repensando como lidam com a prevenção do[n]crime.[n][w][e]

[msg MSG_TUMAARASOI_009_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Ouviu sobre aquela história sobre Medjed?[n]É hora dos Phantom Thieves fazerem[n]outra de suas mágicas![n][w][e]

[msg MSG_TUMAARASOI_009_1_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Nós certamente não podemos fazer nada sobre isso.[n]Seria terrível se Medjed tivesse como alvo nossa[n]empresa.[n][w][e]

[msg MSG_TUMAARASOI_009_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Exatamente. São os figurões como[n]meu marido que precisam[n]intervir se as coisas derem errado.[n][w][e]

[msg MSG_TUMAARASOI_009_3_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Às vezes, agradeço a Deus por meu marido não ter[n]subido na hierarquia da sociedade.[n][w][e]

[msg MSG_TUMAARASOI_010_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Os Phantom Thieves conseguiram![n]E eu estava torcendo por eles[n]o tempo todo.[n][w][e]

[msg MSG_TUMAARASOI_010_1_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]É tudo sobre os[n]Phantom Thieves agora.[n]Eles falam sobre isso em todos os talk shows.[n][w][e]

[msg MSG_TUMAARASOI_010_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Eu disse ao meu marido para colocar à venda um[n]sanduíche inspirado neles.[n][w][e]
[s][vp 8 2 1 0 19 0]Você não acha que seria um blockbuster? É sempre[n]bom estar pronto para pegar a onda.[n][w][e]

[msg MSG_TUMAARASOI_011_0_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Como está seu marido? A empresa[n]estará tentando conter os[n]prejuízos, após as últimas notícias.[n][w][e]

[msg MSG_TUMAARASOI_011_1_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]São todas mentiras! Eles têm[n]isso na Okumura Foods apenas[n]porque invejam seu sucesso![n][w][e]

[msg MSG_TUMAARASOI_011_2_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Tem certeza? Porque meu marido[n]nunca viu um centavo por[n]todas as horas extras, então...[n][w][e]
[s][vp 8 2 1 0 20 0]Quem sabe se eles vão culpar o CEO. Talvez fosse[n]melhor se ele confessasse a verdade. Ohhoho...[n][w][e]

[msg MSG_TUMAARASOI_012_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Parece que Okumura está[n]inalcançável... Meu marido[n]tem que trabalhar até tarde.[n][w][e]

[msg MSG_TUMAARASOI_012_1_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Bem, os Phantom Thieves[n]enviaram uma Carta de Aviso.[n]Os executivos vão entrar em pânico.[n][w][e]

[msg MSG_TUMAARASOI_012_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]A polícia tem que[n]agir e prender esses[n]criminosos![n][w][e]

[msg MSG_TUMAARASOI_012_3_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Você não era fã de Phantom[n]Thieves? Ohoho, eu sei que é um[n]mau momento, mas...[n][w][e]

[msg MSG_TUMAARASOI_013_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Não acredito que Okumura[n]desabou! O que será da empresa?[n][w][e]

[msg MSG_TUMAARASOI_013_1_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Você tem que se acalmar. Tenho certeza de que[n]a empresa ficará bem.[n][w][e]
[s][vp 8 2 1 0 20 0]Quero dizer, deve haver um bom[n]downsizing, para não mencionar o[n]downsizing...[n][w][e]

[msg MSG_TUMAARASOI_013_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Mas... Mas... Meu marido[n]ACABOU de ser promovido![n]Malditos, Phantom Thieves![n][w][e]

[msg MSG_TUMAARASOI_014_0_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Okumura Foods realmente teve um momento ruim. O[n]salário do seu marido cortou muito, certo?[n][w][e]

[msg MSG_TUMAARASOI_014_1_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]O importante é que a empresa[n]está de pé... e que minha[n]família tem muita economia.[n][w][e]
[s][vp 8 2 1 0 19 0]A propósito, como está o seu? Oh,[n]com licença... ponto dolorido?[n][w][e]

[msg MSG_TUMAARASOI_014_2_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Bem, na verdade, como ele[n]deu uma ajuda substancial,[n]ele foi promovido a CEO. Ohhoho...[n][w][e]

[msg MSG_TUMAARASOI_015_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Os Phantom Thieves ainda estão em liberdade, não[n]estão? Tenho medo de ficar sozinha quando meu[n]marido não está por perto.[n][w][e]

[msg MSG_TUMAARASOI_015_1_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Sozinho? E sua empregada? Você[n]mandou aquela pobre garota embora?[n][w][e]

[msg MSG_TUMAARASOI_015_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Nós tivemos que. Devemos[n]cortar todos os gastos desnecessários[n]neste momento de crise, certo?[n][w][e]

[msg MSG_TUMAARASOI_015_3_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Que mulher admirável você se tornou. Bem, como[n]dizem... orgulho precede a ruína.[n][w][e]

[msg MSG_TUMAARASOI_016_0_0 [Dona de casa não tão modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Aquele Shido...o cara do United[n]para o futuro...parece legal.[n]Ele deveria ser primeiro-ministro.[n][w][e]

[msg MSG_TUMAARASOI_016_1_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Ohoho... Sabe, eu realmente o conheci, por meio[n]de uma das tarefas do meu marido.[n][w][e]

[msg MSG_TUMAARASOI_016_2_0 [Dona de casa não tão modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Sério? Nós o conhecemos[n]outro dia, na associação[n]de seus torcedores.[n][w][e]
[s][vp 8 2 1 0 20 0]Parece muito legal.[n]Você estava no evento também?[n][w][e]

[msg MSG_TUMAARASOI_017_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 20 0]Você viu? O líder dos Thieves[n]Phantom ainda está vivo![n][w][e]

[msg MSG_TUMAARASOI_017_1_0 [Dona de casa não tão modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 19 0]Aposto que é um truque para de alguma forma[n]desacreditar Shido![n][w][e]
[s][vp 8 2 1 0 19 0]Isso é o que os programas de entrevistas dizem...[n]que é tudo calúnia na corrida para a eleição.[n][w][e]

[msg MSG_TUMAARASOI_018_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Estou preocupado com a saúde de Shido-san.[n][w][e]

[msg MSG_TUMAARASOI_018_1_0 [Dona de casa não tão modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Sim, ele absolutamente precisa reformar este[n]país. Meu filho vai fazer o vestibular.[n][w][e]
[s][vp 8 2 1 0 20 0]Eu quero que haja um Japão melhor esperando por[n]ele.[n][w][e]

[msg MSG_TUMAARASOI_019_0_0 [Dona de casa não tão modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Oh, feliz ano novo.[n]O ano passado foi cheio[n]de surpresas, não foi...?[n][w][e]

[msg MSG_TUMAARASOI_019_1_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Sim, realmente. Estou surpreso,[n]na verdade...[n][w][e]
[s][vp 8 2 1 0 19 0]...Os negócios correram tão bem[n]que[n]a estabilidade financeira de nossa família melhorou ainda mais.[n][w][e]
[s][vp 8 2 1 0 19 0]Além disso, meu marido[n]foi promovido e tem estado[n]muito ocupado...[n][w][e]

[msg MSG_TUMAARASOI_019_2_0 [Dona de casa não tão modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]O que...? O-Oh? É tão...[n][w][e]
[s][vp 8 2 1 0 20 0]Meu marido também foi promovido,[n]então imagino que eles continuarão[n]a trabalhar juntos com frequência.[n][w][e]

[msg MSG_TUMAARASOI_020_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Ouvi dizer que o inverno[n]será particularmente rigoroso...[n][w][e]
[s][vp 8 2 1 0 19 0]É por isso que decidimos[n]passá-lo em uma praia particular[n]no Havaí, a partir do próximo mês.[n][w][e]
[s][vp 8 2 1 0 19 0]O inverno lá deve ser bem mais ameno, então...[n][w][e]

[msg MSG_TUMAARASOI_020_1_0 [Dona de casa não tão modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]W-W-O quê?!? Você vai ficar fora por muito[n]tempo...[n][w][e]
[s][vp 8 2 1 0 20 0]M-Mas ei, também planejamos ir a uma praia[n]particular em Guam no próximo mês![n][w][e]
[s][vp 8 2 1 0 20 0]Meu marido ganhou um aumento, então podemos[n]pagar...[n][w][e]

[msg MSG_TUMAARASOI_020_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Uau, isso parece ótimo! Estou[n]bom em saber que sua[n]família está bem.[n][w][e]
[s][vp 8 2 1 0 19 0]Eu realmente acredito que este será[n]outro ano maravilhoso.[n][w][e]

[msg MSG_TUMAARASOI_020_3_0 [Dona de casa não tão modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]S-sim... concordo...[n][w][e]

[msg MSG_TUMAARASOI_021_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Oh. Meu marido disse que[n]foi escolhido como membro chave[n]para o próximo projeto![n][w][e]
[s][vp 8 2 1 0 19 0]Não houve nada além de ótimas notícias[n]ultimamente.[n][w][e]

[msg MSG_TUMAARASOI_021_1_0 [Dona de casa não tão modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]E-Estou feliz em ouvir isso.[n][w][e]
[s][vp 8 2 1 0 20 0]O negócio do meu marido também está crescendo.[n]Ele acabou de fechar um grande negócio...[n][w][e]
[s][vp 8 2 1 0 20 0]V-Estamos até pensando em construir uma nova casa![n][w][e]
[s][vp 8 2 1 0 20 0]Eu sinto que estou em uma grande[n]Felicidade Venda, você não acha?!?[n][w][e]

[msg MSG_TUMAARASOI_021_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Uau. Então você fez isso.[n][w][e]

[msg MSG_TUMAARASOI_021_3_0 [Dona de casa não tão modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]O que...?[n][w][e]

[msg MSG_TUMAARASOI_021_4_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Quer dizer, você está dizendo que as coisas[n]estão tão boas que não há nada mais[n]a desejar, certo?[n][w][e]
[s][vp 8 2 1 0 19 0]...Mas talvez você deva[n]oferecê-lo.[n][w][e]
[s][vp 8 2 1 0 19 0]Talvez você pergunte demais? Tudo depende de como[n]você o vê.[n][w][e]
[s][vp 8 2 1 0 19 0]Talvez você seja capaz de me entender, quando[n]experimentar a verdadeira felicidade.[n]Ohohoh...[n][w][e]

[msg MSG_TUMAARASOI_022_0_0 [Dona de casa não tão modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Ouvi dizer que seu marido foi[n]forçado a se aposentar.[n]Deve ser difícil para vocês dois.[n][w][e]

[msg MSG_TUMAARASOI_022_1_0 [Dona de casa não tão arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Sim... Podemos ter que nos mudar[n]com meus pais. Temporariamente,[n]claramente.[n][w][e]

[msg MSG_TUMAARASOI_022_2_0 [Dona de casa não tão modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Bem, se você quiser que eu traga algo da cidade,[n]por favor, não hesite em pedir.[n][w][e]
[s][vp 8 2 1 0 20 0]Tenho certeza que você sentirá muita falta da[n]cidade . Ohhoho...[n][w][e]

[msg MSG_TUMAARASOI_0504_0_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Seu filho vai para Shujin, certo?[n]Onde estava[n]aquela professora famosa presa...[n][w][e]
[s][vp 8 2 1 0 19 0]Se eu soubesse, teria[n]imediatamente transferido meu filho[n]para outra escola.[n][w][e]
[s][vp 8 2 1 0 19 0]Eu sempre me certifico de que[n]meu filho mantenha um diário.[n][w][e]
[s][vp 8 2 1 0 19 0]Então eu sei o que acontece na escola deles.[n][w][e]

[msg MSG_TUMAARASOI_0504_1_0 [Dona de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Bem, meu filho não está no time de vôlei[n]então não vejo a[n]necessidade de um diário...[n][w][e]

[msg MSG_TUMAARASOI_0504_2_0 [Dona de casa arrogante]]
[s][f 4 23 1 19 20 10 0 10][vp 8 2 1 0 19 0]Você sabe, nós, donas de casa, temos que criar[n]filhos bem-sucedidos. Não podemos ir com calma,[n]ohohoh...[n][w][e]

[msg MSG_TOKAISOMARU_001_0_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Hã? O que você tem?[n][w][e]

[msg MSG_TOKAISOMARU_001_1_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Eu sou seu namorado. Não posso deixar você[n]sozinho, com os trens descarrilando a torto e a[n]direito![n][w][e]
[s][vp 8 2 1 0 22 0]Não posso deixar de me preocupar! Não quero que a[n]cidade te engula de uma só vez![n][w][e]

[msg MSG_TOKAISOMARU_001_2_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Pare de fazer uma cena![n]Você está me envergonhando![n][w][e]

[msg MSG_TOKAISOMARU_002_0_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Esta cidade está cheia de pervertidos[n]e criminosos. Não é para nós.[n]Vamos para casa.[n][w][e]

[msg MSG_TOKAISOMARU_002_1_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Mas sempre foi meu sonho morar aqui! Acabar logo![n][w][e]

[msg MSG_TOKAISOMARU_002_2_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Então você vai jogar tudo fora?[n]Seu legado? sua casa?[n][w][e]

[msg MSG_TOKAISOMARU_002_3_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Não estou "jogando" nada fora. Eu já disse a você[n]que voltaremos para casa uma vez por ano. Não é[n]o suficiente para você?[n][w][e]

[msg MSG_TOKAISOMARU_003_0_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]As lojas de conveniência aqui são...[n]Bem, conveniente.[n][w][e]

[msg MSG_TOKAISOMARU_003_1_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Mesmo na aldeia podes encontrar[n]tudo o que precisas...[n]é só perguntares aos vizinhos![n][w][e]
[s][vp 8 2 1 0 22 0]E podemos enlouquecer![n]Uma volta de carro! Como em[n]limousine ou um carro de luxo![n][w][e]

[msg MSG_TOKAISOMARU_003_2_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Você quer dizer em um trator ou uma[n]pick-up. Uh, não, obrigado...[n]Não estou interessado.[n][w][e]

[msg MSG_TOKAISOMARU_004_0_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Fiz de tudo para ir à[n]exposição, dada a sua fama,[n]mas acabou por ser um plagiador![n][w][e]

[msg MSG_TOKAISOMARU_004_1_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Eu sabia! Nesta cidade[n]todos são mentirosos em série![n][w][e]
[s][vp 8 2 1 0 22 0]Eu até ouvi dizer que há um bando de ladrões à[n]solta! Vamos, deixe-me levá-lo para casa.[n][w][e]

[msg MSG_TOKAISOMARU_004_2_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Você está exagerando. Além disso, os[n]Phantom Thieves estão do nosso lado![n][w][e]

[msg MSG_TOKAISOMARU_005_0_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Disseram na TV que há[n]bandidos à solta. Feche bem a porta à noite.[n][w][e]

[msg MSG_TOKAISOMARU_005_1_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Sim, sim... a máfia. Relaxe,[n]a cidade é absolutamente segura.[n][w][e]

[msg MSG_TOKAISOMARU_005_2_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Mas a aldeia também, graças ao Taro vizinho![n][w][e]

[msg MSG_TOKAISOMARU_005_3_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Você quer dizer aquele cachorro idiota que[n]joga todo mundo que chega perto?[n]Cão de guarda bonito.[n][w][e]

[msg MSG_TOKAISOMARU_006_0_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eu quero ir a um clube e[n]dançar a noite toda ... e talvez[n]tomar alguns coquetéis também.[n][w][e]

[msg MSG_TOKAISOMARU_006_1_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Eu estava em um bar legal[n]não muito tempo atrás, em Shinjuku.[n][w][e]
[s][vp 8 2 1 0 22 0]O dono era muito simpático.[n]Foi como estar no céu...[n][w][e]

[msg MSG_TOKAISOMARU_006_2_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Você já foi... a um clube de recepcionistas?[n][w][e]

[msg MSG_TOKAISOMARU_007_0_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Com a máfia na prisão, posso[n]finalmente dormir em paz[n]e aproveitar a cidade sempre que quiser.[n][w][e]

[msg MSG_TOKAISOMARU_007_1_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Este lugar não é seguro! Existem[n]aqueles nojentos Phantom Thieves ou[n]o que quer que eles se chamem por aí.[n][w][e]
[s][vp 8 2 1 0 22 0]E se eles te atacassem no meio da noite? Vamos,[n]vamos, vamos para casa.[n][w][e]

[msg MSG_TOKAISOMARU_007_2_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eu já disse para você parar![n]Estou farto de ouvir você[n]falar sobre o país![n][w][e]

[msg MSG_TOKAISOMARU_008_0_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Se você ficar aqui, esses preguiçosos vão quebrar[n]seu computador![n][w][e]

[msg MSG_TOKAISOMARU_008_1_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eles são chamados de Medjed e são[n]hackers! E eles só visam[n]empresas de qualquer maneira.[n][w][e]

[msg MSG_TOKAISOMARU_008_2_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Você terá problemas se for tão imprudente. Se[n]você quiser, posso ficar de guarda esta noite.[n][w][e]

[msg MSG_TOKAISOMARU_008_3_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Sim Sim...[n][w][e]

[msg MSG_TOKAISOMARU_009_0_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Você deveria ir para casa em Obon. E então, a[n]cidade não é segura por causa de Medjeb.[n][w][e]

[msg MSG_TOKAISOMARU_009_1_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Geografia não conta com[n]internet. E os Thieves[n]Phantoms irão consertá-los de qualquer maneira.[n][w][e]

[msg MSG_TOKAISOMARU_009_2_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Os Phantom Thieves são apenas um mito! É por isso[n]que eles não responderam![n][w][e]
[s][vp 8 2 1 0 22 0]Acordar. Esta cidade é fundada[n]em mentiras![n][w][e]

[msg MSG_TOKAISOMARU_010_0_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Perdoe-me por dizer que os[n]Phantom Thieves eram uma[n]mentira...[n][w][e]
[s][vp 8 2 1 0 22 0]Eles são realmente especiais, esses.[n]Eu gostaria de me tornar como eles.[n][w][e]

[msg MSG_TOKAISOMARU_010_1_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Estou feliz que você[n]finalmente descobriu.[n][w][e]

[msg MSG_TOKAISOMARU_010_2_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Concordo. Para mostrar que sinto muito, vou comprar[n]algo para você na loja de beleza da cidade.[n][w][e]

[msg MSG_TOKAISOMARU_010_3_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eu pego tudo de volta. Você ainda não[n]entendeu porra nenhuma![n][w][e]

[msg MSG_TOKAISOMARU_011_0_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Aquele CEO é o próprio mal.[n]Ele não dá a mínima para nada[n]exceto para si mesmo![n][w][e]

[msg MSG_TOKAISOMARU_011_1_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Os Phantom Thieves irão consertar isso. Você não[n]precisa se preocupar. Eu só espero que eles[n]façam isso o mais rápido possível.[n][w][e]

[msg MSG_TOKAISOMARU_011_2_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]O corpo de bombeiros da vila[n]resolveria a situação[n]num piscar de olhos.[n][w][e]

[msg MSG_TOKAISOMARU_011_3_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eeeeeee a conversa acabou.[n][w][e]

[msg MSG_TOKAISOMARU_012_1_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eles entregaram uma nova Carta[n]de Aviso.[n][w][e]
[s][vp 8 2 1 0 21 0]Se o CEO despertar[n]o coração, você acha que os sanduíches[n]ficarão mais baratos?[n][w][e]

[msg MSG_TOKAISOMARU_012_2_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Eles abriram um no país recentemente. Não vou te[n]contar as falas... parecia uma feira.[n][w][e]
[s][vp 8 2 1 0 22 0]Eu não sabia que o Bangarang Burgers[n]era tão espetacular.[n][w][e]

[msg MSG_TOKAISOMARU_013_1_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eu poderia realmente usar um sanduíche,[n]mas depois de tudo isso...[n][w][e]

[msg MSG_TOKAISOMARU_013_2_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Você está falando de Bangarang? Aposto que toda a[n]empresa está prestes a falir.[n][w][e]
[s][vp 8 2 1 0 22 0]O rosto daquele CEO era...[n]aterrorizante. Aqueles Phantom Thieves[n]são implacáveis.[n][w][e]

[msg MSG_TOKAISOMARU_014_0_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Os Phantom Thieves estão fugindo,[n]verdade? É assustador pensar que[n]eles podem estar escondidos por perto.[n][w][e]

[msg MSG_TOKAISOMARU_014_1_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Isso significa que você finalmente[n]decidiu voltar para o país?[n][w][e]

[msg MSG_TOKAISOMARU_014_2_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Não. Trabalhei muito para vir[n]aqui, não posso sair assim.[n]Só espero que eles sejam pegos logo.[n][w][e]

[msg MSG_TOKAISOMARU_014_3_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Eu cuidarei de você. Estamos todos[n]muito preocupados, sabe.[n][w][e]

[msg MSG_TOKAISOMARU_015_0_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Você já ouviu? Um cara que veio[n]para a escola primária conosco[n]concorre à eleição.[n][w][e]

[msg MSG_TOKAISOMARU_015_1_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]O que, sério!?! Quem? Eu me pergunto[n]se nós fôssemos amigos...[n][w][e]

[msg MSG_TOKAISOMARU_015_2_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Bem, ele sempre disse que queria[n]melhorar a aldeia. Mas eu[n]ouvi dizer que é uma tarefa difícil.[n][w][e]

[msg MSG_TOKAISOMARU_016_0_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Não me importa o quão ruim as coisas fiquem, o[n]suicídio nunca é a solução.[n][w][e]
[s][vp 8 2 1 0 22 0]Dar tanto desprazer à mãe e ao pai... Não é uma[n]boa maneira de ir embora.[n][w][e]

[msg MSG_TOKAISOMARU_016_1_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Sim, eu realmente não entendo.[n]Ele não tinha motivos para se matar.[n][w][e]

[msg MSG_TOKAISOMARU_016_2_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]A culpa também é nossa! Depois de todas as coisas[n]ruins que dissemos sobre ele![n][w][e]

[msg MSG_TOKAISOMARU_016_3_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Você está certo, desculpe...[n]É a primeira vez que alguém fica[n]bravo assim, comigo.[n][w][e]

[msg MSG_TOKAISOMARU_017_0_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Shido é um homem mau? Devemos[n]acreditar nos Phantom Thieves?[n][w][e]

[msg MSG_TOKAISOMARU_017_1_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Ainda assim, temos que esperar para ver. Não[n]podemos fazer mais nada.[n][w][e]

[msg MSG_TOKAISOMARU_017_2_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]...Eu não sei o que é esperado de[n]mim... Eu realmente me sinto perdido[n]esta selva de concreto.[n][w][e]

[msg MSG_TOKAISOMARU_017_3_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Estou surpreso que você se sinta perdido.[n][w][e]

[msg MSG_TOKAISOMARU_018_0_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Escute, pensei em voltar para[n]país. Quer ficar na cidade?[n][w][e]

[msg MSG_TOKAISOMARU_018_1_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Hã? Sim... Por que essa decisão repentina?[n][w][e]

[msg MSG_TOKAISOMARU_018_2_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Eu entendi morando lá. Tóquio não é para mim.[n]Além disso, quero apoiar nosso colega de escola[n]nas eleições.[n][w][e]

[msg MSG_TOKAISOMARU_018_3_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]...Oh. Entendi.[n][w][e]

[msg MSG_TOKAISOMARU_019_0_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]D-Desculpe... Você pode repetir[n]o que acabou de dizer?[n][w][e]

[msg MSG_TOKAISOMARU_019_1_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Eu disse que deveríamos morar juntos em Tóquio.[n][w][e]
[s][vp 8 2 1 0 22 0]Você gosta do lugar, e eu também.[n][w][e]
[s]E então temos os mesmos valores.[n]Você não acha que é uma boa ideia?[n][w][e]

[msg MSG_TOKAISOMARU_019_2_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Ok, primeira coisa: o que há de errado com você?[n][w][e]
[s][vp 8 2 1 0 21 0]Você fala e age[n]diferente... Estou tão confuso.[n][w][e]

[msg MSG_TOKAISOMARU_020_0_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Desculpe, você pode repetir[n]o que você disse?[n][w][e]

[msg MSG_TOKAISOMARU_020_1_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Ok, eu digo que devemos morar em[n]uma dessas casas chiques.[n][w][e]
[s][vp 8 2 1 0 22 0]Podemos adicionar muitas[n]decorações femininas... Não é[n]o que você quer?[n][w][e]

[msg MSG_TOKAISOMARU_020_2_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]B-Bem, sim, isso é o que sempre quis, mas...[n][w][e]
[s][vp 8 2 1 0 21 0]Como você sabe tudo isso?[n][w][e]

[msg MSG_TOKAISOMARU_020_3_0 [Menino do campo]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Hoje é importante alargar[n]horizontes e nunca parar[n]de aprender.[n][w][e]
[s][vp 8 2 1 0 22 0]É assim que eu gosto dessa[n]feliz vida na cidade, junto com vocês.[n][w][e]

[msg MSG_TOKAISOMARU_021_0_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0]......[n][w][e]
[s][vp 8 2 1 0 21 0]Sempre sonhei em morar em[n]Tóquio. E agora posso fazer isso com ele...[n][w][e]
[s][vp 8 2 1 0 21 0]Tudo ótimo, mas…[n][w][e]
[s][vp 8 2 1 0 21 0]*suspiro* Por que me sinto tão triste, de[n]repente...?[n][w][e]

[msg MSG_TOKAISOMARU_021_1_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Todo mundo parece tão feliz desde que o ano novo[n]começou...[n][w][e]
[s][vp 8 2 1 0 21 0]Mas então, por que estou tão triste?[n][w][e]

[msg MSG_TOKAISOMARU_022_0_0 [Mulher encantadora]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Tóquio parece tão quieta[n]agora...[n][w][e]
[s][vp 8 2 1 0 21 0]Ou talvez... foi ele quem fez[n]muito barulho...[n][w][e]
[s][vp 8 2 1 0 21 0]Uh. Talvez haja coisas que eu não posso fazer só na cidade, mas… há outra coisa que eu sinto falta.[n][w][e]
[s][vp 8 2 1 0 21 0]...Talvez eu devesse ir para casa também.[n][w][e]

[msg Quest05_target_00_00 [Mitsumi Kure]]
[s][vp 8 2 1 0 600 0]Com licença, preciso falar com você.[n]Tive um problema com[n]seu curry picante.[n][w][e]
[s][vp 8 2 1 0 600 0]Estava muito picante![n]Comê-lo foi[n]uma experiência terrível![n][w][e]
[s][vp 8 2 1 0 600 0]Minha boca está toda queimada![n]O curry piorou minha[n]estomatite! Não posso comer...[n][w][e]
[s][vp 8 2 1 0 600 0]Ai! Ah! Dói muito![n]Você não deve vender[n]certas coisas para os clientes.[n][w][e]
[s][vp 8 2 1 0 600 0]Quero um pedido de desculpas e um reembolso.[n]Chame o gerente aqui,[n]por favor, e rápido.[n][w][e]
[s][vp 8 2 1 0 600 0]Aquele...? Meu nome é[n]Mitsumi! Mitsumi Kure![n][w][e]

[msg MSG_quest05_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Eu diria que temos nosso[n]objetivo. Hora de discutir[n]um plano no Esconderijo![n][w][e]

[msg HELP_MEMENTOS_MISSION_02 [Atualização da missão!]]
[s][clr 4]Conflito de lembrança[clr 27]"[n]O alvo foi identificado.[n]Discuta os detalhes com a[n]equipe no "[clr 2]esconderijo[clr 27]".[n][w][e]

[msg Quest05_target_01_00 [Mitsumi Kure]]
[s][vp 8 2 1 0 600 0]É por isso que não suporto[n]quem trabalha nos serviços.[n]Aqui, tenho provas.[n][w][e]
[s][vp 8 2 1 0 600 0]Encontrei esta[n]mensagem em minha bolsa que parece uma Carta[n]de Aviso de um crime.[n][w][e]
[s][vp 8 2 1 0 600 0]Deve ter sido você,[n]você vende essas sacolas![n]exijo um pedido de desculpas![n][w][e]

[msg Quest05_target_02_00 [Mitsumi Kure]]
[s][vp 8 2 1 0 600 0]Sinto muito pela última[n]vez e pelas reclamações sobre[n]minha estomatite.[n][w][e]
[s][vp 8 2 1 0 600 0]Deixe-me pedir desculpas[n]por todas essas reclamações[n]contra você.[n][w][e]
[s][vp 8 2 1 0 600 0]Para ser sincero, aquele curry apimentado estava[n]delicioso.[n][w][e]
[s][vp 8 2 1 0 600 0]Minha boca já estava inchada,[n]se piorou a culpa é só minha.[n]tenho muita vergonha...[n][w][e]
[s][vp 8 2 1 0 600 0]Hoje gostaria de expressar[n]minha gratidão.[n][w][e]
[s][vp 8 2 1 0 600 0]O curry aqui supera[n]por algumas mãos que[n]de qualquer outro restaurante.[n][w][e]
[s][vp 8 2 1 0 600 0]Espero que você adicione[n]outros pratos ao menu em breve.[n][w][e]

[msg Quest09_target_00_00 [Sachiko Kuwaiti]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]Eu disse a você, acabei de ver! Eu nunca trairia[n]você.[n][w][e]

[msg Quest09_target_00_01 [Homem prestes a processar]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]Não finja! Você me traiu[n]com tantas pessoas...[n]mesmo com meus amigos![n][w][e]
[s][vp 8 2 1 0 602 0]Tenho os vídeos[n]da agência de detetives[n]que contratei como prova![n][w][e]

[msg Quest09_target_00_02 [Sachiko Kuwaiti]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 65535 0 0 0]......[n][w][e]
[s][vp 8 2 1 0 601 0]O que há de errado com uma mulher[n]que anseia por amor? É você quem[n]não me abraça o suficiente![n][w][e]
[s][vp 8 2 1 0 601 0]E tudo bem, vá em frente. Denuncie-me.[n]Na família somos todos advogados.[n]Você nunca vai ganhar.[n][w][e]

[msg Quest09_target_00_03 [Homem prestes a processar]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]Huh? Você está brincando?!?[n]Não pense que você pode se safar![n][w][e]

[msg Quest09_target_sinjyo_00]
[s][vp 8 2 65535 0 0 0]Que comportamento desagradável...[n][w][e]

[msg MSG_quest09_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Parece que encontramos nosso[n]objetivo! Vamos voltar ao esconderijo e[n]discutir com os outros![n][w][e]

[msg Quest09_target_01_00 [Sachiko Kuwaiti]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]É este?!? Já que no tribunal[n]você não tem esperança, você usa truques[n]como esta Carta de Aviso?[n][w][e]

[msg Quest09_target_01_01 [Homem prestes a processar]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]O-o quê? N-não, não fui eu![n][w][e]
[s][vp 8 2 1 0 602 0]Devem ser aqueles Phantom Thieves! Eles estão[n]todos falando sobre como eles despertam o[n]coração das pessoas![n][w][e]

[msg Quest09_target_01_02 [Sachiko Kuwaiti]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]Como você ousa mentir para mim?!?[n]Eles não culpam apenas aqueles que[n]cometem crimes reais?[n][w][e]
[s][vp 8 2 1 0 601 0]Eu não fiz nada de errado.[n]Eu não sou uma pessoa má![n][w][e]

[msg Quest09_target_sinjyo_01]
[s][vp 8 2 65535 0 0 0]Parece que a Carta de Aviso[n]foi entregue com sucesso.[n][w][e]

[msg Quest09_target_02_00 [Sachiko Kuwaiti]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]U-Uhm...[n]Por favor, me escute...[n][w][e]

[msg Quest09_target_02_01 [Homem de olhos frios]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]Huh? O que você quer?!?[n]Se você acha que pode me enganar[n]fingindo chorar, eu não vou cair nessa![n][w][e]

[msg Quest09_target_02_02 [Sachiko Kuwaiti]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]Não é assim! Me desculpe[n]por trair você.[n][w][e]
[s][vp 8 2 1 0 601 0]Eu concederei a você qualquer indenização que[n]você quiser. Farei o que for preciso, custe o[n]que custar![n][w][e]
[s][vp 8 2 1 0 601 0]Por favor me perdoe.[n][w][e]

[msg Quest09_target_02_03 [Homem de olhos frios]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]Que diabos...?[n]É um pouco tarde para dizer[n]certas coisas...[n][w][e]
[s][vp 8 2 1 0 602 0]Entendo. Os Phantom Thieves[n]realmente mudaram seu coração.[n]Agora que eles salvaram você...[n][w][e]
[s][vp 8 2 1 0 602 0]Eu só quero que você encontre um bom companheiro.[n]Seja fiel e faça-o feliz.[n][w][e]

[msg Quest09_target_sinjyo_02]
[s][vp 8 2 65535 0 0 0]Parece que a missão foi um sucesso...[n][w][e]

[msg Quest14_target_00_00 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]A área usual fora[n]das catracas! Você deveria[n]conhecê-la agora, sua velha bruxa![n][w][e]
[s][vp 8 2 1 0 605 0]Ouça, apenas me empreste mais algum dinheiro,[n]você verá que eu vou conseguir. Cale a boca e se[n]apresse![n][w][e]
[s][vp 8 2 1 0 605 0]Oh vamos lá. Eu sei que você[n]se aposentou recentemente.[n][w][e]
[s][vp 8 2 1 0 605 0]Recolha-o rapidamente e traga o dinheiro aqui! E[n]pare de me chamar de Daichi-chan![n][w][e]
[s][vp 8 2 1 0 605 0]E que diabos. É pedir muito a uma mãe que ajude[n]seu filho sem fazer perguntas?[n][w][e]

[msg Quest14_target_sinjyo_00]
[s][vp 8 2 65535 0 0 0]Esse cara é terrível.[n][w][e]

[msg MSG_quest14_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Parece que encontramos nosso[n]objetivo! Vamos voltar ao esconderijo e[n]discutir com os outros![n][w][e]

[msg Quest14_target_01_00 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]Carta de Aviso...?[n]Que diabos é isso?[n][w][e]

[msg Quest14_target_01_01 [Homem prestes a processar]]
[s][vp 8 2 1 0 605 0]Foi endereçado a você, então...[n][w][e]

[msg Quest14_target_01_02 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]Você acha que eu quero algo[n]aquela bruxa velha e assustadora?[n][w][e]
[s][vp 8 2 1 0 605 0]Apenas me dê o maldito dinheiro![n][w][e]

[msg Quest14_target_sinjyo_01]
[s][vp 8 2 65535 0 0 0]Parece que a Carta de Aviso[n]foi entregue com sucesso.[n][w][e]

[msg Quest14_target_02_00 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]Mãe, decidi arranjar um emprego de au pair.[n][w][e]
[s][vp 8 2 1 0 605 0]Expliquei a situação[n]ao meu patrão, ele disse que[n]vai cuidar de mim.[n][w][e]

[msg Quest14_target_02_01 [Mãe de Daichi]]
[s][vp 8 2 1 0 605 0]Sério? Estou feliz em ouvir isso.[n][w][e]
[s][vp 8 2 1 0 605 0]Mesmo que isso me entristeça um pouco.[n]Não haverá mais ninguém[n]em casa...[n][w][e]

[msg Quest14_target_02_02 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]Eu irei ver você.[n][w][e]
[s][vp 8 2 1 0 605 0]E não se preocupe, vou devolver todo o dinheiro[n]que devo a você...[n][w][e]

[msg Quest14_target_02_03 [Mãe de Daichi]]
[s][vp 8 2 1 0 605 0]Deixar.[n][w][e]
[s][vp 8 2 1 0 605 0]Eu só queria que você fosse feliz.[n][w][e]

[msg Quest14_target_02_04 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]Mãe...[n][w][e]

[msg Quest14_target_sinjyo_02]
[s][vp 8 2 65535 0 0 0]Parece que a missão foi um sucesso...[n][w][e]

[msg Quest15_target_00_00 [Muneo Horiguchi]]
[s][f 4 23 1 603 3 10 0 0][vp 8 2 1 0 603 0]Eu disse a eles para se moverem e[n]aqueles respondem mal. A juventude de hoje[n]não tem esperança.[n][w][e]

[msg Quest15_target_00_01 [Sobrinho de Muneo]]
[s][f 4 23 1 604 3 10 0 0][vp 8 2 1 0 604 0]Vovô, você me ouviu? Eu disse[n]que posso ficar de pé.[n][w][e]

[msg Quest15_target_00_02 [Muneo Horiguchi]]
[s][vp 8 2 1 0 603 0]Esse não é o ponto.[n]Se eu pedir para eles desistirem,[n]eles deveriam.[n][w][e]

[msg Quest15_target_00_03 [Sobrinho de Muneo]]
[s][vp 8 2 1 0 604 0]Mas papai diz que não devemos gritar com as[n]pessoas...[n][w][e]

[msg Quest15_target_00_04 [Muneo Horiguchi]]
[s][vp 8 2 1 0 603 0]Não, é uma questão de educação[n]e disciplina! Alguém deve[n]ensiná-lo algumas maneiras.[n][w][e]

[msg Quest15_target_00_05 [Sobrinho de Muneo]]
[s][vp 8 2 1 0 604 0]Mas as pessoas por aqui[n]estão olhando para nós errado...[n][w][e]

[msg Quest15_target_00_06 [Muneo Horiguchi]]
[s][vp 8 2 1 0 603 0]Que idiotas![n][w][e]
[s][vp 8 2 1 0 603 0]Nós é que criamos o[n]Japão como é hoje, com[n]sangue e suor![n][w][e]
[s][vp 8 2 1 0 603 0]Por que eles acham que podem viver em paz?!? Os[n]jovens não têm o direito de reclamar.[n][w][e]
[s][vp 8 2 1 0 603 0]No entanto, eles até se recusam a desistir de seu[n]assento. Eles não sabem o que significa ter[n]respeito?!?[n][w][e]

[msg MSG_quest15_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Parece que encontramos nosso[n]objetivo! Vamos voltar ao esconderijo e[n]discutir com os outros![n][w][e]

[msg Quest15_target_01_00 [Muneo Horiguchi]]
[s][f 4 23 1 603 3 10 0 0][vp 8 2 1 0 603 0]Uma Carta de Aviso...?[n]Outrageous.[n][w][e]
[s][vp 8 2 1 0 603 0]Quem é o bandido safado[n]responsável por essa pegadinha[n]estúpida?[n][w][e]

[msg Quest15_target_sinjyo_01]
[s][vp 8 2 65535 0 0 0]Parece que a Carta de Aviso[n]foi entregue com sucesso.[n][w][e]

[msg Quest15_target_02_00 [Muneo Horiguchi]]
[s][f 4 23 1 603 3 10 0 0][vp 8 2 1 0 603 0]Meu sobrinho se afastou[n]completamente de mim.[n]Ele nem vem me ver.[n][w][e]
[s][vp 8 2 1 0 603 0]Ele se cansou das minhas constantes[n]reclamações sobre qualquer coisa...[n][w][e]
[s][vp 8 2 1 0 603 0]A família do meu filho também diz[n]que eu sou teimosa, que[n]as crianças precisam ser melhor educadas.[n][w][e]

[msg Quest15_target_02_01 [Sênior sorridente]]
[s][f 4 23 1 604 3 10 0 0][vp 8 2 1 0 604 0]Bem, a sabedoria vem com a idade,[n]mas conforme você envelhece, você não[n]se torna perfeito.[n][w][e]
[s][vp 8 2 1 0 604 0]E aí você sempre teve um jeito brusco de falar...[n][w][e]
[s][vp 8 2 1 0 604 0]Para ser sincero, eu também[n]pensei em me afastar[n]de você no passado.[n][w][e]

[msg Quest15_target_02_02 [Muneo Horiguchi]]
[s][f 4 23 1 603 3 10 0 0][vp 8 2 1 0 603 0]Eu entendi mal tantas coisas.[n]É um absurdo que você só comece a entender[n]nessa idade.[n][w][e]
[s][vp 8 2 1 0 603 0]Não me restam muitos anos[n]para recomeçar,[n]mas farei o que puder.[n][w][e]
[s][vp 8 2 1 0 603 0]Em primeiro lugar, vou me inscrever no[n]Silver Human Resources Center.[n][w][e]
[s][vp 8 2 1 0 603 0]Se eu puder me tornar útil[n]de alguma forma, darei um novo[n]sentido à minha vida.[n][w][e]

[msg Quest15_target_sinjyo_02]
[s][vp 8 2 65535 0 0 0]O despertar do coração[n]parece evidente[n]a partir de suas reflexões...[n][w][e]

[msg quest23_hint_talk_00 [ヒント23]]
[s]クエスト23のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest23_hint_sinjyo]
[s]クエスト23のテスト心情メッセージです。[n][w][e]

[msg MSG_quest23_morgana_00 [Morgana]]
[s]クエスト23のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

[msg quest26_hint_talk_00 [ヒント26]]
[s]クエスト26のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest26_hint_sinjyo]
[s]クエスト26のテスト心情メッセージです。[n][w][e]

[msg MSG_quest26_morgana_00 [Morgana]]
[s]クエスト26のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

[msg quest37_hint_talk_00 [ヒント37]]
[s]クエスト37のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest37_hint_sinjyo]
[s]クエスト37のテスト心情メッセージです。[n][w][e]

[msg MSG_quest37_morgana_00 [Morgana]]
[s]クエスト37のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

[msg quest42_hint_talk_00 [ヒント42]]
[s]クエスト42のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest42_hint_sinjyo]
[s]クエスト42のテスト心情メッセージです。[n][w][e]

[msg MSG_quest42_morgana_00 [Morgana]]
[s]クエスト42のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

[msg Quest44_target_00_00 [ターゲット44]]
[s][f 4 23 1 614 3 10 0 0]クエスト44のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗は受注可能状態です。[n][w][e]

[msg Quest44_target_sinjyo_00]
[s]クエスト44のテスト心情メッセージです。[n][w][e]

[msg MSG_quest44_morgana_01 [Morgana]]
[s]クエスト44のモルガナメッセージです。[n]ターゲット用です。[n][w][e]

[msg Quest44_target_01_00 [ターゲット44]]
[s][f 4 23 1 614 3 10 0 0]クエスト44のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗はメメントス突入可能状態です。[n][w][e]

[msg Quest44_target_sinjyo_01]
[s]クエスト44のテスト心情メッセージです。[n][w][e]

[msg Quest44_target_02_00 [ターゲット44]]
[s][f 4 23 1 614 3 10 0 0]クエスト44のテストメッセージです。[n]表示後、キャンプでの状態を確認して下さい。[n][w][e]
[s]クエストの進捗はミッションクリア状態です。[n][w][e]

[msg Quest44_target_sinjyo_02]
[s]クエスト44のテスト心情メッセージです。[n][w][e]

[msg Quest46_target_00_00 [ターゲット46]]
[s][f 4 23 1 616 3 10 0 0]クエスト46のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗は受注可能状態です。[n][w][e]

[msg Quest46_target_sinjyo_00]
[s]クエスト46のテスト心情メッセージです。[n][w][e]

[msg MSG_quest46_morgana_01 [Morgana]]
[s]クエスト46のモルガナメッセージです。[n]ターゲット用です。[n][w][e]

[msg Quest46_target_01_00 [ターゲット46]]
[s][f 4 23 1 616 3 10 0 0]クエスト46のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗はメメントス突入可能状態です。[n][w][e]

[msg Quest46_target_sinjyo_01]
[s]クエスト46のテスト心情メッセージです。[n][w][e]

[msg Quest46_target_02_00 [ターゲット46]]
[s][f 4 23 1 616 3 10 0 0]クエスト46のテストメッセージです。[n]表示後、キャンプでの状態を確認して下さい。[n][w][e]
[s]クエストの進捗はミッションクリア状態です。[n][w][e]

[msg Quest46_target_sinjyo_02]
[s]クエスト46のテスト心情メッセージです。[n][w][e]

[msg JUICE_SHOP_NOTOPEN [Funcionário]]
[s][vp 8 2 1 0 2 0]Desculpe, ainda estamos[n]renovando.[n][w][e]
[s][vp 8 2 1 0 2 0]○日になったらオープンしますので[n]また来てください![n][w][e]

[msg JUICE_SHOP_SELECT [Funcionário]]
[s][vp 8 2 1 0 2 0]Bem-vindo! Hoje o suco misto[n]está em oferta a[n]preço bem baixo![n][w][e]
[s][vp 8 2 1 0 2 0]Quer encomendar um?[n][w][e]

[msg JUICE_SHOP_THANKS [Funcionário]]
[s][vp 8 2 1 0 2 0]Muito obrigado![n]Esperamos vê-lo novamente muito,[n]muito em breve![n][w][e]

[msg JUICE_SHOP_NOT_BUY [Funcionário]]
[s][vp 8 2 1 0 2 0]Volte logo![n][w][e]

[msg JUICE_SHOP_SOLDOUT [Funcionário]]
[s][vp 8 2 1 0 2 0]Sinto muito.[n]Estamos sem estoque[n]de...tudo.[n][w][e]

[msg MSG_01030108_MAKOTO_01 [Sae]]
[s][bup 0 105 0 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 25 1 65535 0 0]Ah...[n][f 1 3 65535][w][e]

[msg MSG_01030108_MAKOTO_02 [Makoto]]
[s][bup 0 6 0 6 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 25 1 65535 0 0]Ah, [f 4 2]. Que coincidência.[n][f 1 3 65535][w][e]

[msg MSG_GRT_main_All_001_01_ [Makoto]]
[s][vp 9 2 65535 38752 0 0]Nada[n]bom acontece... Alguém[n]deveria fazer alguma coisa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_02_ [Makoto]]
[s][vp 9 2 65535 41352 0 0]Espero que nada tão estranho aconteça novamente[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_03_ [Makoto]]
[s][vp 9 2 65535 38355 0 0]Eles estão espalhando[n]pânico e ninguém[n]sabe por quê.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_04_ [Makoto]]
[s][vp 9 2 65535 41655 0 0]As pessoas enlouquecem[n]por causa do estresse?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_05_ [Makoto]]
[s][vp 9 2 65535 38805 0 0]Que chatice ter que ir[n]trabalhar... quase[n]falco dizendo que estou doente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_06_ [Makoto]]
[s][vp 9 2 65535 41852 0 0]É chato aqui...[n]eu quero ir[n]se divertir.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_07_ [Makoto]]
[s][vp 9 2 65535 46052 0 0]Por que nunca[n]nada de bom acontece? Alguém[n]deveria fazer alguma coisa...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_08_ [Makoto]]
[s][vp 9 2 65535 45152 0 0]Tudo é tão chato...[n]Quando algo[n]bom vai acontecer?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_09_ [Makoto]]
[s][vp 9 2 65535 37909 0 0]Eu quero ficar rico[n]rápido... Há[n]boas oportunidades?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_10_ [Makoto]]
[s][vp 9 2 65535 38710 0 0]Que chatice ter que ir[n]trabalhar... quase[n]falco dizendo que estou doente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_11_ [Makoto]]
[s][vp 9 2 65535 44755 0 0]Nada nunca vai mudar.[n]Não há necessidade de levar[n]coisas a sério.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_12_ [Makoto]]
[s][vp 9 2 65535 41555 0 0]Tudo é tão chato...[n]Quando algo[n]bom vai acontecer?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_13_ [Makoto]]
[s][vp 9 2 65535 37552 0 0]Que chatice ter que ir[n]trabalhar... quase[n]falco dizendo que estou doente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_14_ [Makoto]]
[s][vp 9 2 65535 43952 0 0]Nada[n]bom acontece... Alguém[n]deveria fazer alguma coisa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_15_ [Makoto]]
[s][vp 9 2 65535 39305 0 0]Tudo é tão chato...[n]Quando algo[n]bom vai acontecer?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_16_ [Makoto]]
[s][vp 9 2 65535 41110 0 0]Nada nunca vai mudar.[n]Não há necessidade de levar[n]coisas a sério.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_01_ [Makoto]]
[s][vp 9 2 65535 37902 0 0]Então ainda não sabemos a causa? Você[n]está brincando, espero...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_02_ [Makoto]]
[s][vp 9 2 65535 42709 0 0]As vendas estão caindo...[n]Eles são todos inúteis...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_03_ [Makoto]]
[s][vp 9 2 65535 40605 0 0]Ouvi dizer que eles enlouquecem[n]de raiva, como se[n]estivessem possuídos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_04_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]Não importa de quem é a culpa. Corra para[n]encontrar uma solução...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_05_ [Makoto]]
[s][vp 9 2 65535 38201 0 0]É chato aqui...[n]eu quero ir[n]se divertir.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_06_ [Makoto]]
[s][vp 9 2 65535 41855 0 0]Os políticos são terríveis. Não[n]importa quem está no poder.[n]São todos iguais...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_07_ [Makoto]]
[s][vp 9 2 65535 41005 0 0]Nada nunca vai mudar.[n]Não há necessidade de levar[n]coisas a sério.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_08_ [Makoto]]
[s][vp 9 2 65535 46052 0 0]O mundo é assustador...[n]De quem é a culpa?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_09_ [Makoto]]
[s][vp 9 2 65535 39052 0 0]Quando sei que algo vai acontecer, não consigo[n]deixar de ficar estressado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_10_ [Makoto]]
[s][vp 9 2 65535 43055 0 0]As pessoas não vão exagerar? Mais cedo ou mais[n]tarde isso vai se resolver...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_11_ [Makoto]]
[s][vp 9 2 65535 42955 0 0]Deve ser culpa dos[n]fantasmas. Isso não é assustador?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_12_ [Makoto]]
[s][vp 9 2 65535 43454 0 0]Então, alguém sabe[n]o que causou aquele[n]acidente estranho?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_13_ [Makoto]]
[s][vp 9 2 65535 42659 0 0]O mundo é assustador...[n]De quem é a culpa?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_14_ [Makoto]]
[s][vp 9 2 65535 40702 0 0]Todos os dias, fico entediado.[n]Deve haver algo[n]divertido para fazer...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_15_ [Makoto]]
[s][vp 9 2 65535 39360 0 0]É difícil ficar motivado[n]sem um grande aumento...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_16_ [Makoto]]
[s][vp 9 2 65535 43802 0 0]As vendas caíram...[n]É a[n]crise econômica, né...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_01_ [Makoto]]
[s][vp 9 2 65535 39109 0 0]Pena que[n]campeão olímpico é um[n]pervertido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_02_ [Makoto]]
[s][vp 9 2 65535 43405 0 0]Inferno, já que ele iria[n]confessar no final,[n]por que ele fez o que fez?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_03_ [Makoto]]
[s][vp 9 2 65535 38652 0 0]Ele se aproveitou das[n]garotas do time...[n]Que merda...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_04_ [Makoto]]
[s][vp 9 2 65535 40051 0 0]Ele assediou aquelas[n]garotas abusando de[n]sua posição... Tsk.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_05_ [Makoto]]
[s][vp 9 2 65535 37904 0 0]Um professor[n]foi preso por assédio?[n]Você está falando sério?!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_06_ [Makoto]]
[s][vp 9 2 65535 45301 0 0]Inferno, já que ele iria[n]confessar no final,[n]por que ele fez o que fez?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_07_ [Makoto]]
[s][vp 9 2 65535 40052 0 0]Ele se aproveitou das[n]garotas do time...[n]Que merda...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_08_ [Makoto]]
[s][vp 9 2 65535 44254 0 0]Ele confessou todos os seus[n]crimes, mas ainda não[n]entendo o que aconteceu.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_09_ [Makoto]]
[s][vp 9 2 65535 38152 0 0]Inferno, já que ele iria[n]confessar no final,[n]por que ele fez o que fez?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_10_ [Makoto]]
[s][vp 9 2 65535 42703 0 0]Pena que[n]campeão olímpico é um[n]pervertido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_11_ [Makoto]]
[s][vp 9 2 65535 46351 0 0]Ele assediou aquelas[n]garotas abusando[n]de sua posição...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_12_ [Makoto]]
[s][vp 9 2 65535 44751 0 0]Ele se aproveitou das[n]garotas do time...[n]Que merda...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_13_ [Makoto]]
[s][vp 9 2 65535 38152 0 0]Campeão olímpico ou[n]não, acabou.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_14_ [Makoto]]
[s][vp 9 2 65535 45304 0 0]Inferno, já que ele iria[n]confessar no final,[n]por que ele fez o que fez?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_15_ [Makoto]]
[s][vp 9 2 65535 46405 0 0]Por que ele confessou, tão[n]de repente? Eu realmente não entendo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_16_ [Makoto]]
[s][vp 9 2 65535 41001 0 0]Ele se aproveitou das[n]garotas do time...[n]Que merda...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_01_ [Makoto]]
[s][vp 9 2 65535 39105 0 0]Não me interesso muito por arte[n]mas parece ser uma arte famosa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_02_ [Makoto]]
[s][vp 9 2 65535 45650 0 0]Eu o vi na TV.[n]Ele faz lindas pinturas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_03_ [Makoto]]
[s][vp 9 2 65535 41404 0 0]Parece ser conhecido em[n]todo o mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_04_ [Makoto]]
[s][vp 9 2 65535 46053 0 0]Eu vi suas pinturas na TV.[n]Eles eram realmente lindos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_05_ [Makoto]]
[s][vp 9 2 65535 38200 0 0]Artistas ganham muito dinheiro. Agora[n]estou começando a pintar também...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_06_ [Makoto]]
[s][vp 9 2 65535 45504 0 0]Eu o vi na TV.[n]Ele faz lindas pinturas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_07_ [Makoto]]
[s][vp 9 2 65535 45753 0 0]Ele é tão famoso...[n]Talvez eu devesse começar[n]a pintar também.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_08_ [Makoto]]
[s][vp 9 2 65535 41300 0 0]Suas obras são[n]apreciadas em[n]todo o mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_09_ [Makoto]]
[s][vp 9 2 65535 46305 0 0]Arte e esse tipo de coisa[n]não me interessam, mas[n]ele parece ser famoso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_10_ [Makoto]]
[s][vp 9 2 65535 46303 0 0]Eu o vi na TV.[n]Ele faz lindas pinturas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_11_ [Makoto]]
[s][vp 9 2 65535 38259 0 0]Aposto que suas pinturas[n]são bem pagas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_12_ [Makoto]]
[s][vp 9 2 65535 41550 0 0]Suas obras são[n]apreciadas em[n]todo o mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_13_ [Makoto]]
[s][vp 9 2 65535 45654 0 0]Você sabe quem é Madarame?[n]Ele parece ser um pintor famoso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_14_ [Makoto]]
[s][vp 9 2 65535 45504 0 0]Eu o vi na TV.[n]Ele faz lindas pinturas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_15_ [Makoto]]
[s][vp 9 2 65535 40854 0 0]Parece ser conhecido em[n]todo o mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_16_ [Makoto]]
[s][vp 9 2 65535 40410 0 0]Aposto que[n]pintor ganha muito...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_01_ [Makoto]]
[s][vp 9 2 65535 42255 0 0]Você não acha que a culpa[n]é de quem[n]foi enganado?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_02_ [Makoto]]
[s][vp 9 2 65535 41352 0 0]Eu sei que é perigoso aqui fora,[n]mas eu tenho que ir trabalhar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_03_ [Makoto]]
[s][vp 9 2 65535 44502 0 0]Ouvi dizer que é perigoso.[n]Espero que alguém[n]resolva essa situação...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_04_ [Makoto]]
[s][vp 9 2 65535 46105 0 0]Eu me pergunto se essas[n]histórias sobre golpes e ameaças[n]são verdadeiras...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_05_ [Makoto]]
[s][vp 9 2 65535 45802 0 0]Ouvi dizer que basta clicar nele[n]para se ferrar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_06_ [Makoto]]
[s][vp 9 2 65535 41852 0 0]Ouvi dizer que a[n]gangue criminosa de Shibuya[n]é muito grande...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_07_ [Makoto]]
[s][vp 9 2 65535 41452 0 0]Os rumores sobre[n]extorsão e golpes são verdadeiros?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_08_ [Makoto]]
[s][vp 9 2 65535 43852 0 0]É apenas minha impressão,[n]ou você viu[n]mais rostos obscuros ultimamente?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_09_ [Makoto]]
[s][vp 9 2 65535 43704 0 0]Shibuya só se tornou[n]perigoso[n]recentemente, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_10_ [Makoto]]
[s][vp 9 2 65535 38502 0 0]Parece que a maioria[n]das vítimas são jovens...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_11_ [Makoto]]
[s][vp 9 2 65535 44759 0 0]Recebi outro e-mail...[n]Eles são persistentes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_12_ [Makoto]]
[s][vp 9 2 65535 40052 0 0]Você acredita que as ameaças[n]são reais...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_13_ [Makoto]]
[s][vp 9 2 65535 38204 0 0]Ouvi dizer que é[n]tudo dirigido por[n]uma grande organização...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_14_ [Makoto]]
[s][vp 9 2 65535 39152 0 0]Ouvi dizer que se eles[n]mirarem em você, você está ferrado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_15_ [Makoto]]
[s][vp 9 2 65535 40652 0 0]Às vezes por aqui[n]tem bandido...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_16_ [Makoto]]
[s][vp 9 2 65535 37952 0 0]Quando saio não consigo[n]relaxar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_01_ [Makoto]]
[s][vp 9 2 65535 44405 0 0]Ouvi dizer que quando você[n]tem uma convulsão, seu[n]cérebro desliga...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_02_ [Makoto]]
[s][vp 9 2 65535 44704 0 0]Esses casos aconteceram todos[n]um após o outro. Coincidências?[n]Acho que não...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_03_ [Makoto]]
[s][vp 9 2 65535 38602 0 0]Espero que não tenhamos que[n]testemunhar outro[n]esses incidentes absurdos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_04_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_05_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_06_ [Makoto]]
[s][vp 9 2 65535 39155 0 0]Então, todas aquelas pessoas que[n]desmaiaram...[n]Isso foi mentira?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_07_ [Makoto]]
[s][vp 9 2 65535 41154 0 0]Talvez não tenhamos mais[n]preocupação em ver[n]aqueles acidentes acontecerem novamente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_08_ [Makoto]]
[s][vp 9 2 65535 41155 0 0]Aposto que as pessoas[n]inventaram[n]coisas sobre ataques mentais.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_09_ [Makoto]]
[s][vp 9 2 65535 41610 0 0]Parece que aqueles incidentes estranhos[n]pararam assim,[n]de repente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_10_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_11_ [Makoto]]
[s][vp 9 2 65535 43200 0 0]Há muito menos[n]pessoas por perto que poderiam causar[n]esses acidentes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_12_ [Makoto]]
[s][vp 9 2 65535 39655 0 0]Até recentemente havia[n]muitos desses[n]acidentes absurdos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_13_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_14_ [Makoto]]
[s][vp 9 2 65535 40705 0 0]Eles poderiam acontecer de novo,[n]agora que estávamos[n]prestes a esquecer...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_15_ [Makoto]]
[s][vp 9 2 65535 45104 0 0]Aquele acidente no metrô não[n]aconteceu no início[n]de abril?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_16_ [Makoto]]
[s][vp 9 2 65535 39709 0 0]O culpado deve ser[n]quem está causando os acidentes![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_01_ [Makoto]]
[s][vp 9 2 65535 42554 0 0]Talvez, se eu me tornar seu[n]aluno, eu possa ser famoso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_02_ [Makoto]]
[s][vp 9 2 65535 41505 0 0]Arte? Na verdade eu não[n]interesso muito...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_03_ [Makoto]]
[s][vp 9 2 65535 45754 0 0]Ouvi dizer que há[n]uma exposição desse artista em Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_04_ [Makoto]]
[s][vp 9 2 65535 40050 0 0]Foi fantástico! Suas[n]obras são de outro mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_05_ [Makoto]]
[s][vp 9 2 65535 38200 0 0]É bom sair e curtir[n]um pouco de arte![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_06_ [Makoto]]
[s][vp 9 2 65535 45504 0 0]Será que vale a pena[n]ir à exposição[n]de Madarame...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_07_ [Makoto]]
[s][vp 9 2 65535 46054 0 0]Oh, aquele artista que[n]pintou "Sayuri"? Já[n]ouvi falar disso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_08_ [Makoto]]
[s][vp 9 2 65535 45154 0 0]Ele se comporta como uma pessoa humilde,[n]mas não parece um pouco[n]suspeito de alguma forma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_09_ [Makoto]]
[s][vp 9 2 65535 39054 0 0]Passei pela exposição,[n]mas estava muito lotado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_10_ [Makoto]]
[s][vp 9 2 65535 38700 0 0]Ele criou um enorme número de obras, para um[n]único artista. Isso faz parte de seu talento?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_11_ [Makoto]]
[s][vp 9 2 65535 43354 0 0]Parece ser tão famoso[n]que os ingressos são[n]essencialmente impossíveis de obter.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_12_ [Makoto]]
[s][vp 9 2 65535 40653 0 0]Se ela é uma[n]artista fenomenal, vale a pena[n]ir à exposição.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_13_ [Makoto]]
[s][vp 9 2 65535 37853 0 0]Já inauguraram a exposição?[n]Acho que vou. Então terei[n]algo para falar.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_14_ [Makoto]]
[s][vp 9 2 65535 42050 0 0]Ele é um artista famoso e[n]o orgulho de todo o Japão.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_15_ [Makoto]]
[s][vp 9 2 65535 41304 0 0]Se for uma pintura de um[n]artista famoso, tenho certeza que eles podem[n]vendê-la por quantias astronômicas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_16_ [Makoto]]
[s][vp 9 2 65535 45110 0 0]Sabe, eu realmente invejo[n]pessoas talentosas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_01_ [Makoto]]
[s][vp 9 2 65535 43753 0 0]Essa conferência de imprensa foi[n]uma explosão...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_02_ [Makoto]]
[s][vp 9 2 65535 46002 0 0]Abusar de alunos...[n]Que horrível...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_03_ [Makoto]]
[s][vp 9 2 65535 39651 0 0]E então aquele artista[n]enganou todo mundo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_04_ [Makoto]]
[s][vp 9 2 65535 46102 0 0]Quero o reembolso[n]do ingresso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_05_ [Makoto]]
[s][vp 9 2 65535 39804 0 0]Você não se pergunta[n]por que ele fez isso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_06_ [Makoto]]
[s][vp 9 2 65535 45505 0 0]O erro foi[n]permitir que ele fizesse isso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_07_ [Makoto]]
[s][vp 9 2 65535 39705 0 0]Quem sabe por que ele se desculpou tão do nada.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_08_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]Eu me sinto estúpido por ter[n]sido um admirador...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_09_ [Makoto]]
[s][vp 9 2 65535 46304 0 0]É imperdoável. Aproveite[n]assim dos alunos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_10_ [Makoto]]
[s][vp 9 2 65535 40551 0 0]Caí nela com todos os meus sapatos.[n]Ele nem era um artista de verdade...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_11_ [Makoto]]
[s][vp 9 2 65535 42604 0 0]Já ouvi falar de outras pessoas[n]que "confessaram seus[n]crimes" do nada...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_12_ [Makoto]]
[s][vp 9 2 65535 38055 0 0]É bobagem... As pessoas[n]não conseguem parar de falar[n]sobre[n]aqueles "Phantom Thieves"...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_13_ [Makoto]]
[s][vp 9 2 65535 40355 0 0]E assim, qualquer um poderia[n]tentar algo obscuro[n]nas nossas costas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_14_ [Makoto]]
[s][vp 9 2 65535 45500 0 0]A coletiva de imprensa...[n]O homem parecia[n]louco.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_15_ [Makoto]]
[s][vp 9 2 65535 39354 0 0]É verdade que alguém[n]previu[n]que isso aconteceria?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_16_ [Makoto]]
[s][vp 9 2 65535 40055 0 0]Então ele ficou rico desonestamente[n]todo esse tempo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_01_ [Makoto]]
[s][vp 9 2 65535 38702 0 0]Será que Shibuya será um[n]lugar seguro?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_02_ [Makoto]]
[s][vp 9 2 65535 43759 0 0]Os rumores sobre[n]extorsão e golpes são verdadeiros?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_03_ [Makoto]]
[s][vp 9 2 65535 40952 0 0]Os rumores sobre[n]extorsão e golpes são verdadeiros?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_04_ [Makoto]]
[s][vp 9 2 65535 43852 0 0]É apenas minha impressão,[n]ou você viu[n]mais rostos obscuros ultimamente?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_05_ [Makoto]]
[s][vp 9 2 65535 39752 0 0]Ninguém mais vem a Shibuya.[n]Todo mundo está com medo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_06_ [Makoto]]
[s][vp 9 2 65535 41852 0 0]Parece-me que ultimamente[n]há muito mais[n]pessoas obscuras por aí...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_07_ [Makoto]]
[s][vp 9 2 65535 41004 0 0]Os rumores sobre[n]extorsão e golpes são verdadeiros?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_08_ [Makoto]]
[s][vp 9 2 65535 46059 0 0]É apenas minha impressão,[n]ou você viu[n]mais rostos obscuros ultimamente?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_09_ [Makoto]]
[s][vp 9 2 65535 38204 0 0]Eles dizem que de repente[n]você é...[n]convocado para Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_10_ [Makoto]]
[s][vp 9 2 65535 42204 0 0]Parece que as pessoas[n]estão recebendo[n]e-mails de phishing.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_11_ [Makoto]]
[s][vp 9 2 65535 43352 0 0]A essa altura, todo mundo está com medo[n]de ir para Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_12_ [Makoto]]
[s][vp 9 2 65535 43854 0 0]Phishing? Mas é terrível![n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_13_ [Makoto]]
[s][vp 9 2 65535 40555 0 0]Eles dizem que de repente[n]você é...[n]convocado para Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_14_ [Makoto]]
[s][vp 9 2 65535 39151 0 0]Parece que as pessoas[n]estão recebendo[n]e-mails de phishing.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_15_ [Makoto]]
[s][vp 9 2 65535 42912 0 0]Às vezes por aqui[n]tem bandido...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_16_ [Makoto]]
[s][vp 9 2 65535 40802 0 0]Phishing? Mas é terrível![n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_01_ [Makoto]]
[s][vp 9 2 65535 38100 0 0]Alguns também foram[n]para Madarame, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_02_ [Makoto]]
[s][vp 9 2 65535 41505 0 0]É impossível que Phantom[n]Thievess realmente existam...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_03_ [Makoto]]
[s][vp 9 2 65535 40604 0 0]Se isso significa restaurar[n]paz a essas[n]partes, tudo bem, não é?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_04_ [Makoto]]
[s][vp 9 2 65535 44255 0 0]Phantom Thieves, hein? Você acredita que[n]eles realmente existem...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_05_ [Makoto]]
[s][vp 9 2 65535 40304 0 0]Seria interessante se essa[n]Carta de Aviso fosse verdadeira...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_06_ [Makoto]]
[s][vp 9 2 65535 38455 0 0]É impossível que Phantom[n]Thievess realmente existam...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_07_ [Makoto]]
[s][vp 9 2 65535 44254 0 0]Um amigo meu disse que[n]viu uma dessas[n]cartas de desafio![n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_08_ [Makoto]]
[s][vp 9 2 65535 45755 0 0]Phantom Thieves, hein? Você acredita que[n]eles realmente existem...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_09_ [Makoto]]
[s][vp 9 2 65535 44904 0 0]Toda essa conversa sobre[n]Phantom Thieves é ridícula...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_10_ [Makoto]]
[s][vp 9 2 65535 40355 0 0]Aquele Kaneshiro é um[n]vilão?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_11_ [Makoto]]
[s][vp 9 2 65535 42755 0 0]A Carta de Aviso dos[n]Phantom Thieves? É apenas uma[n]lenda urbana![n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_12_ [Makoto]]
[s][vp 9 2 65535 39005 0 0]Phantom Thieves, hein? Você acredita que[n]eles realmente existem...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_13_ [Makoto]]
[s][vp 9 2 65535 42554 0 0]Ouvi dizer que eles foram[n]fixados em carros e em todos os lugares.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_14_ [Makoto]]
[s][vp 9 2 65535 38450 0 0]É impossível que Phantom[n]Thievess realmente existam...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_15_ [Makoto]]
[s][vp 9 2 65535 39654 0 0]Ouvi dizer que eles foram[n]fixados em carros e em todos os lugares.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_16_ [Makoto]]
[s][vp 9 2 65535 43455 0 0]Phantom Thieves, hein? Você acredita que[n]eles realmente existem...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_01_ [Makoto]]
[s][vp 9 2 65535 37508 0 0]Vamos para Shibuya![n]Está tudo bem lá agora![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_02_ [Makoto]]
[s][vp 9 2 65535 41204 0 0]Parece que a partir de agora[n]as coisas vão ficar quietas,[n]por aqui.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_03_ [Makoto]]
[s][vp 9 2 65535 38600 0 0]Estou feliz que Shibuya[n]está calmo novamente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_04_ [Makoto]]
[s][vp 9 2 65535 41303 0 0]Que alívio![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_05_ [Makoto]]
[s][vp 9 2 65535 38204 0 0]Ainda bem que não existem mais[n]aqueles delinquentes![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_06_ [Makoto]]
[s][vp 9 2 65535 45300 0 0]O chefe da[n]organização criminosa foi[n]preso, finalmente![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_07_ [Makoto]]
[s][vp 9 2 65535 41454 0 0]Finalmente por aqui[n]tudo vai voltar ao normal![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_08_ [Makoto]]
[s][vp 9 2 65535 40050 0 0]Você pode voltar[n]em Shibuya sem medo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_09_ [Makoto]]
[s][vp 9 2 65535 39450 0 0]Finalmente podemos[n]ir para Shibuya[n]sem nos preocupar![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_10_ [Makoto]]
[s][vp 9 2 65535 42550 0 0]Eu não sabia o que[n]aconteceria, mas estou feliz que[n]eles o prenderam.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_11_ [Makoto]]
[s][vp 9 2 65535 42953 0 0]Podemos ir para[n]Shibuya novamente, agora que é[n]seguro novamente![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_12_ [Makoto]]
[s][vp 9 2 65535 41304 0 0]Estou feliz que Shibuya[n]está calmo novamente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_13_ [Makoto]]
[s][vp 9 2 65535 41700 0 0]É seguro morar[n]novamente em Shibuya![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_14_ [Makoto]]
[s][vp 9 2 65535 45503 0 0]Eu não sabia o que[n]aconteceria, mas estou feliz que[n]eles o prenderam.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_15_ [Makoto]]
[s][vp 9 2 65535 46203 0 0]Não há mais nada com que[n]preocupar-se, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_16_ [Makoto]]
[s][vp 9 2 65535 42000 0 0]Estou tão feliz que Shibuya[n]está quieto novamente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_01_ [Makoto]]
[s][vp 9 2 65535 37856 0 0]Viu as notícias?[n]Parece que[n]os Phantom Thieves fizeram isso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_02_ [Makoto]]
[s][vp 9 2 65535 41954 0 0]The Phantom Thieves[n]Carta de Aviso[n]previu tudo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_03_ [Makoto]]
[s][vp 9 2 65535 40954 0 0]Viu as notícias?[n]Parece que[n]os Phantom Thieves fizeram isso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_04_ [Makoto]]
[s][vp 9 2 65535 43854 0 0]É verdade que foram os[n]Phantom Thieves que solucionaram o[n]caso do acidente!?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_05_ [Makoto]]
[s][vp 9 2 65535 38504 0 0]Então foram os[n]Phantom Thieves que derrotaram[n]Kaneshiro, hein?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_06_ [Makoto]]
[s][vp 9 2 65535 38456 0 0]Esses caras são incríveis![n]Eles estão fazendo um[n]trabalho melhor do que a polícia![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_07_ [Makoto]]
[s][vp 9 2 65535 45156 0 0]E então aquela[n]Carta de Aviso não era brincadeira![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_08_ [Makoto]]
[s][vp 9 2 65535 39704 0 0]De acordo com relatos da mídia,[n]os Phantom Thieves podem[n]estar envolvidos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_09_ [Makoto]]
[s][vp 9 2 65535 39800 0 0]Seria incrível se[n]eles fossem realmente os[n]Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_10_ [Makoto]]
[s][vp 9 2 65535 44906 0 0]Esses caras são incríveis![n]Eles estão fazendo um[n]trabalho melhor do que a polícia![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_11_ [Makoto]]
[s][vp 9 2 65535 44456 0 0]As coisas correram[n]como ele esperava[n]a Carta de Aviso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_12_ [Makoto]]
[s][vp 9 2 65535 41804 0 0]De acordo com relatos da mídia,[n]os Phantom Thieves podem[n]estar envolvidos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_13_ [Makoto]]
[s][vp 9 2 65535 38756 0 0]Você ouviu sobre isso[n]no noticiário? Parece que[n]os Phantom Thieves fizeram isso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_14_ [Makoto]]
[s][vp 9 2 65535 39153 0 0]The Phantom Thieves[n]Carta de Aviso[n]previu tudo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_15_ [Makoto]]
[s][vp 9 2 65535 39356 0 0]Você ouviu sobre isso[n]no noticiário? Parece que[n]os Phantom Thieves fizeram isso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_16_ [Makoto]]
[s][vp 9 2 65535 39004 0 0]É verdade que foram os[n]Phantom Thieves que solucionaram o[n]caso do acidente!?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_01_ [Makoto]]
[s][vp 9 2 65535 38405 0 0]Medjed parece[n]muito interessado em[n]Phantom Thieves...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_02_ [Makoto]]
[s][vp 9 2 65535 41504 0 0]Mas que tipo de grupo é[n]Medjed, afinal?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_03_ [Makoto]]
[s][vp 9 2 65535 37700 0 0]Digamos que estou com os[n]Phantom Thieves. Eu sou como um[n]Robin Hood moderno.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_04_ [Makoto]]
[s][vp 9 2 65535 41153 0 0]Eles estão contando a ele sobre todas as[n]cores. Quem sabe o que[n]os Phantom Thieves farão...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_05_ [Makoto]]
[s][vp 9 2 65535 40304 0 0]Mas que tipo de grupo é[n]Medjed?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_06_ [Makoto]]
[s][vp 9 2 65535 45504 0 0]Eu me pergunto como[n]os Phantom Thieves vão lidar com esses[n]hackers.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_07_ [Makoto]]
[s][vp 9 2 65535 38354 0 0]Eu me pergunto por que Medjed[n]atacou[n]os Phantom Thieves...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_08_ [Makoto]]
[s][vp 9 2 65535 46056 0 0]Quem sabe como os[n]Phantom Thieves vão reagir depois de serem[n]provocados assim.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_09_ [Makoto]]
[s][vp 9 2 65535 39104 0 0]Veja as notícias sobre essa[n]declaração? Como você acha que[n]os Phantom Thieves vão reagir?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_10_ [Makoto]]
[s][vp 9 2 65535 42554 0 0]Os[n]Phantom Thieves cuidarão deles, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_11_ [Makoto]]
[s][vp 9 2 65535 45104 0 0]Quem sabe o que[n]os Phantom Thieves farão sobre[n]sobre Medjed...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_12_ [Makoto]]
[s][vp 9 2 65535 38254 0 0]Eles estão contando a ele sobre todas as[n]cores. Quem sabe o que[n]os Phantom Thieves farão...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_13_ [Makoto]]
[s][vp 9 2 65535 39804 0 0]Veja as notícias sobre essa[n]declaração? Como você acha que[n]os Phantom Thieves vão reagir?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_14_ [Makoto]]
[s][vp 9 2 65535 38452 0 0]Eu me pergunto como[n]os Phantom Thieves vão lidar com esses[n]hackers.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_15_ [Makoto]]
[s][vp 9 2 65535 38654 0 0]Os Phantom Thieves são os únicos que[n]podem derrotar[n]aqueles hackers![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_16_ [Makoto]]
[s][vp 9 2 65535 44254 0 0]Eles estão contando a ele sobre todas as[n]cores. Quem sabe o que[n]os Phantom Thieves farão...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_01_ [Makoto]]
[s][vp 9 2 65535 39057 0 0]Vamos, Phantom Thieves...[n]Fala...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_02_ [Makoto]]
[s][vp 9 2 65535 41756 0 0]Como eles vão[n]lutar contra esses hackers[n]the Phantom Thieves?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_03_ [Makoto]]
[s][vp 9 2 65535 42462 0 0]O Japão foi alvo.[n]Espero que façam[n]algo a respeito.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_04_ [Makoto]]
[s][vp 9 2 65535 41455 0 0]Eles precisam agir antes que[n]algo[n]mal aconteça conosco...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_05_ [Makoto]]
[s][vp 9 2 65535 41504 0 0]O que os Phantom Thieves[n]faz[n]contra os hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_06_ [Makoto]]
[s][vp 9 2 65535 41856 0 0]O que[n]os Phantom Thieves estão fazendo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_07_ [Makoto]]
[s][vp 9 2 65535 43852 0 0]O Japão foi alvo.[n]Espero que façam[n]algo a respeito.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_08_ [Makoto]]
[s][vp 9 2 65535 46055 0 0]Se os Phantom Thieves[n]revelarem suas identidades[n]tudo ficará bem, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_09_ [Makoto]]
[s][vp 9 2 65535 46303 0 0]O que os Phantom Thieves[n]faz[n]contra hackers...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_10_ [Makoto]]
[s][vp 9 2 65535 40557 0 0]Vamos, Phantom Thieves...[n]Fala...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_11_ [Makoto]]
[s][vp 9 2 65535 43201 0 0]Os Phantom Thieves estão[n]mantendo silêncio.[n]Como isso vai acabar?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_12_ [Makoto]]
[s][vp 9 2 65535 43455 0 0]Se os Phantom Thieves[n]revelarem suas identidades[n]tudo ficará bem, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_13_ [Makoto]]
[s][vp 9 2 65535 38754 0 0]O que os Phantom Thieves[n]faz[n]contra hackers...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_14_ [Makoto]]
[s][vp 9 2 65535 42054 0 0]Vamos, Phantom Thieves...[n]Fala...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_15_ [Makoto]]
[s][vp 9 2 65535 40804 0 0]O Japão foi alvo.[n]Espero que façam[n]algo a respeito.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_16_ [Makoto]]
[s][vp 9 2 65535 41805 0 0]Se os Phantom Thieves[n]revelarem suas identidades[n]tudo ficará bem, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_01_ [Makoto]]
[s][vp 9 2 65535 40754 0 0]Ouvi dizer que os Phantom Thieves[n]conseguiram![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_02_ [Makoto]]
[s][vp 9 2 65535 41950 0 0]Ainda bem que[n]tudo resolvido sem nenhum dano...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_03_ [Makoto]]
[s][vp 9 2 65535 44456 0 0]Aparentemente, o site Medjed[n]foi sabotado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_04_ [Makoto]]
[s][vp 9 2 65535 44254 0 0]Que alegria, tudo[n]resolvido e ninguém[n]se machucou.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_05_ [Makoto]]
[s][vp 9 2 65535 43700 0 0]É realmente louco[n]que eles derrotaram[n]Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_06_ [Makoto]]
[s][vp 9 2 65535 41850 0 0]Ainda bem que[n]tudo resolvido sem nenhum dano...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_07_ [Makoto]]
[s][vp 9 2 65535 41004 0 0]Aparentemente, o site Medjed[n]foi sabotado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_08_ [Makoto]]
[s][vp 9 2 65535 46100 0 0]Que legal,[n]agora está tudo bem! E obrigado[n]aos Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_09_ [Makoto]]
[s][vp 9 2 65535 37606 0 0]Isso significa que os[n]Phantom Thieves[n]nos salvaram, estou certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_10_ [Makoto]]
[s][vp 9 2 65535 38706 0 0]É realmente louco[n]que eles derrotaram[n]Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_11_ [Makoto]]
[s][vp 9 2 65535 42800 0 0]Parece que o site[n]Medjed foi fechado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_12_ [Makoto]]
[s][vp 9 2 65535 46106 0 0]Eu não acredito nisso! Eles[n]derrotaram um grupo de[n]hackers mundialmente famosos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_13_ [Makoto]]
[s][vp 9 2 65535 40106 0 0]Isso significa que os[n]Phantom Thieves[n]nos salvaram, estou certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_14_ [Makoto]]
[s][vp 9 2 65535 42053 0 0]É realmente louco[n]que eles derrotaram[n]Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_15_ [Makoto]]
[s][vp 9 2 65535 38004 0 0]Os Phantom Thieves[n]conseguiram, hein!?! Louco![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_16_ [Makoto]]
[s][vp 9 2 65535 38553 0 0]Eu não acredito nisso! Eles[n]derrotaram um grupo de[n]hackers mundialmente famosos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_01_ [Makoto]]
[s][vp 9 2 65535 39756 0 0]Os Phantom Thieves estavam[n]certos desde o início![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_02_ [Makoto]]
[s][vp 9 2 65535 43400 0 0]Esses Phantom Thieves são[n]tão loucos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_03_ [Makoto]]
[s][vp 9 2 65535 38900 0 0]Eles venceram os hackers,[n]não acredito.[n]Eles são incríveis![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_04_ [Makoto]]
[s][vp 9 2 65535 41656 0 0]Os Phantom Thieves SÃO[n]justiça![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_05_ [Makoto]]
[s][vp 9 2 65535 45803 0 0]Os Phantom Thieves[n]salvaram o Japão![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_06_ [Makoto]]
[s][vp 9 2 65535 39156 0 0]Achei que estávamos condenados.[n]Viva os Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_07_ [Makoto]]
[s][vp 9 2 65535 40806 0 0]Com certeza até no exterior[n]todos vão[n]ser surpreendidos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_08_ [Makoto]]
[s][vp 9 2 65535 41650 0 0]Estamos salvos, e tudo graças[n]aos Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_09_ [Makoto]]
[s][vp 9 2 65535 41904 0 0]Eu estava certo em[n]apoiá-los![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_10_ [Makoto]]
[s][vp 9 2 65535 44950 0 0]Ainda bem que os Thieves[n]Phantom estão lutando por nós![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_11_ [Makoto]]
[s][vp 9 2 65535 40206 0 0]Eles merecem tanto respeito[n]por derrubar Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_12_ [Makoto]]
[s][vp 9 2 65535 39006 0 0]Eu sou um super fã de[n]Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_13_ [Makoto]]
[s][vp 9 2 65535 39800 0 0]Abater Medjed é uma proeza[n]um grito![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_14_ [Makoto]]
[s][vp 9 2 65535 40706 0 0]Ainda bem que os Thieves[n]Phantom estão lutando por nós![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_15_ [Makoto]]
[s][vp 9 2 65535 39356 0 0]Aparentemente, o Japão[n]está seguro, graças ao Phantom[n]Thieves.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_16_ [Makoto]]
[s][vp 9 2 65535 41000 0 0]Os Phantom Thieves são[n]incríveis![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_01_ [Makoto]]
[s][vp 9 2 65535 40103 0 0]Onde quer que você vire, toda a conversa[n]é sobre os Ladrões[n]Phantom...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_02_ [Makoto]]
[s][vp 9 2 65535 44706 0 0]Phantom Thieves Fever[n]infectou toda a sociedade![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_03_ [Makoto]]
[s][vp 9 2 65535 40606 0 0]Eu também quero pedir a ele[n]que desperte o coração de[n]alguém que conheço![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_04_ [Makoto]]
[s][vp 9 2 65535 41306 0 0]Não temos nada a[n]temer, com Thieves[n]Phantom por aí![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_05_ [Makoto]]
[s][vp 9 2 65535 44353 0 0]Limpe toda a ralé deste mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_06_ [Makoto]]
[s][vp 9 2 65535 38458 0 0]Aqueles Phantom Thieves[n]apareceram do nada![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_07_ [Makoto]]
[s][vp 9 2 65535 44505 0 0]Muitas pessoas estão[n]entrando na onda dos[n]Phantom Thieves...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_08_ [Makoto]]
[s][vp 9 2 65535 41650 0 0]Tudo ficará bem enquanto os[n]Phantom Thieves estiverem[n]aqui para nos proteger![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_09_ [Makoto]]
[s][vp 9 2 65535 38206 0 0]Ficaremos bem.[n]Os Phantom Thieves[n]cuidem de nós![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_10_ [Makoto]]
[s][vp 9 2 65535 38405 0 0]É uma loucura o quão[n]populares são os Phantom Thieves...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_11_ [Makoto]]
[s][vp 9 2 65535 40606 0 0]Se você não conhece os[n]Phantom Thieves, você[n]está desatualizado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_12_ [Makoto]]
[s][vp 9 2 65535 41153 0 0]Talvez eu envie um pedido[n]aos Phantom Thieves...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_13_ [Makoto]]
[s][vp 9 2 65535 39056 0 0]Ficaremos bem.[n]Os Phantom Thieves[n]cuidem de nós![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_14_ [Makoto]]
[s][vp 9 2 65535 41861 0 0]Onde quer que você vire, toda a conversa[n]é sobre os Ladrões[n]Phantom...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_15_ [Makoto]]
[s][vp 9 2 65535 41656 0 0]Esses Phantom Thieves são[n]incríveis![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_16_ [Makoto]]
[s][vp 9 2 65535 39350 0 0]Enquanto houver[n]os Phantom Thieves,[n]o Japão estará seguro...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_01_ [Makoto]]
[s][vp 9 2 65535 40505 0 0]Eles os tratam como escravos,[n]verdade? Que empresa horrível.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_02_ [Makoto]]
[s][vp 9 2 65535 41500 0 0]Se eu acho que a Okumura[n]Foods explorou seus funcionários...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_03_ [Makoto]]
[s][vp 9 2 65535 40255 0 0]Sinto pena de todos[n]esses trabalhadores...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_04_ [Makoto]]
[s][vp 9 2 65535 40051 0 0]Eles são pessoas horríveis.[n]Eles tratam seus funcionários[n]pior do que animais...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_05_ [Makoto]]
[s][vp 9 2 65535 38204 0 0]Se eu acho que a Okumura[n]Foods explorou seus funcionários...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_06_ [Makoto]]
[s][vp 9 2 65535 39151 0 0]Eles tratam seus funcionários[n]como escravos, não é?[n]Isso é terrível.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_07_ [Makoto]]
[s][vp 9 2 65535 41001 0 0]Explorar seus[n]funcionários...É nojento...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_08_ [Makoto]]
[s][vp 9 2 65535 38601 0 0]Nos bastidores[n]eles se comportaram[n]de maneira muito antiética...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_09_ [Makoto]]
[s][vp 9 2 65535 40302 0 0]Parece que eles foram forçados a[n]fazer turnos impensáveis...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_10_ [Makoto]]
[s][vp 9 2 65535 43002 0 0]Estou surpreso que isso não tenha sido tornado[n]público até hoje...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_11_ [Makoto]]
[s][vp 9 2 65535 40004 0 0]Até meus pais ficaram[n]chocados com a notícia...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_12_ [Makoto]]
[s][vp 9 2 65535 42401 0 0]Eu não tinha ideia de que esse era o motivo do[n]rápido crescimento da Okumura Foods...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_13_ [Makoto]]
[s][vp 9 2 65535 44602 0 0]Ouvi dizer que eles os forçaram a trabalhar duro[n]por muitas horas seguidas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_14_ [Makoto]]
[s][vp 9 2 65535 43952 0 0]Estou surpreso que isso não tenha sido tornado[n]público até hoje...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_15_ [Makoto]]
[s][vp 9 2 65535 43454 0 0]Eles eram tão maus que[n]começaram um motim, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_16_ [Makoto]]
[s][vp 9 2 65535 39304 0 0]Eu não tinha ideia de que esse era o motivo do[n]rápido crescimento da Okumura Foods...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_01_ [Makoto]]
[s][vp 9 2 65535 40750 0 0]Eles não podem fazer[n]reforma social[n]ou algo assim?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_02_ [Makoto]]
[s][vp 9 2 65535 41203 0 0]Os Phantom Thieves[n]irão acabar com[n]todos os bandidos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_03_ [Makoto]]
[s][vp 9 2 65535 41403 0 0]Quem sabe quem eles escolherão[n]como próximo alvo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_04_ [Makoto]]
[s][vp 9 2 65535 41656 0 0]Se você quer mudar o[n]mundo, faça-o[n]de uma vez por todas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_05_ [Makoto]]
[s][vp 9 2 65535 38206 0 0]Você não acha que os[n]Phantom Thieves entrarão em ação em breve?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_06_ [Makoto]]
[s][vp 9 2 65535 43956 0 0]Contanto que deixemos[n]os Phantom Thieves fazerem isso,[n]tudo ficará bem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_07_ [Makoto]]
[s][vp 9 2 65535 40404 0 0]Quem sabe quem eles escolherão[n]como próximo alvo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_08_ [Makoto]]
[s][vp 9 2 65535 41000 0 0]Neste mundo podre,[n]Phantom Thieves[n]farão a diferença![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_09_ [Makoto]]
[s][vp 9 2 65535 44706 0 0]Aposto que os Thieves[n]Phantom vão intervir![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_10_ [Makoto]]
[s][vp 9 2 65535 37553 0 0]Vamos, Phantom Thieves![n]Façam algo interessante![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_11_ [Makoto]]
[s][vp 9 2 65535 43103 0 0]Tudo vai ficar bem...[n]Os Phantom Thieves vão consertar[n]coisas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_12_ [Makoto]]
[s][vp 9 2 65535 46100 0 0]Enquanto os Phantom Thieves[n]estiverem entre nós,[n]não temos nada a temer![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_13_ [Makoto]]
[s][vp 9 2 65535 41750 0 0]Aposto que os Thieves[n]Phantom vão intervir![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_14_ [Makoto]]
[s][vp 9 2 65535 45306 0 0]Vamos, Phantom Thieves![n]Façam algo interessante![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_15_ [Makoto]]
[s][vp 9 2 65535 46203 0 0]Quem sabe quem eles escolherão[n]como próximo alvo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_16_ [Makoto]]
[s][vp 9 2 65535 39306 0 0]Neste mundo podre,[n]Phantom Thieves[n]farão a diferença![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_01_ [Makoto]]
[s][vp 9 2 65535 42706 0 0]Outra Carta de Aviso![n]Eu sabia...[n]É para Okumura![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_02_ [Makoto]]
[s][vp 9 2 65535 41051 0 0]Okumura está condenado![n]É todo seu, Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_03_ [Makoto]]
[s][vp 9 2 65535 44203 0 0]Eu estava esperando ansiosamente que[n]sua Carta de Aviso fosse enviada![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_04_ [Makoto]]
[s][vp 9 2 65535 41003 0 0]Eu exijo um pedido de desculpas ainda[n]mais sincero do que[n]Madarame![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_05_ [Makoto]]
[s][vp 9 2 65535 39806 0 0]Então, Phantom Thieves![n]Pegue sua presa e não pare![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_06_ [Makoto]]
[s][vp 9 2 65535 41856 0 0]Não o deixe escapar,[n]Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_07_ [Makoto]]
[s][vp 9 2 65535 41000 0 0]Quero ver mais[n]castigos sensacionais![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_08_ [Makoto]]
[s][vp 9 2 65535 41161 0 0]Então, Phantom Thieves![n]Chute o traseiro deles![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_09_ [Makoto]]
[s][vp 9 2 65535 43156 0 0]Mostre-nos sua justiça![n]Derrote Okumura![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_10_ [Makoto]]
[s][vp 9 2 65535 37806 0 0]Isso é tudo que eu esperava,[n]Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_11_ [Makoto]]
[s][vp 9 2 65535 43253 0 0]Eu estava ansioso por[n]uma Carta de Aviso dos Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_12_ [Makoto]]
[s][vp 9 2 65535 39600 0 0]Eu exijo um pedido de desculpas ainda[n]mais sincero do que[n]Madarame![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_13_ [Makoto]]
[s][vp 9 2 65535 43406 0 0]Claro que ele é[n]punido por seu[n]apego ao dinheiro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_14_ [Makoto]]
[s][vp 9 2 65535 40706 0 0]Isso é tudo que eu esperava,[n]Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_15_ [Makoto]]
[s][vp 9 2 65535 37753 0 0]É mais do que justo que[n]aqueles que cometem[n]atrocidades semelhantes sejam punidos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_16_ [Makoto]]
[s][vp 9 2 65535 42400 0 0]O presidente Okumura merece[n]sofrer pelo que fez![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_01_ [Makoto]]
[s][vp 9 2 65535 43007 0 0]Do jeito que eles fazem...[n]É como se eles gostassem[n]de matar pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_02_ [Makoto]]
[s][vp 9 2 65535 41201 0 0]Não importa o quão ruim fosse. Apenas[n]mads o teriam matado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_03_ [Makoto]]
[s][vp 9 2 65535 40407 0 0]Que tipo de "[n]despertar do coração" foi esse!?![n]Eles são simplesmente assassinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_04_ [Makoto]]
[s][vp 9 2 65535 40055 0 0]Como eles acham que podem despertar[n]um coração matando alguém?[n]Eles mentiram![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_05_ [Makoto]]
[s][vp 9 2 65535 39402 0 0]Neste ponto eu acho que eles[n]gosta de matar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_06_ [Makoto]]
[s][vp 9 2 65535 42057 0 0]Não acredito que eles[n]mataram alguém! Eles são[n]loucos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_07_ [Makoto]]
[s][vp 9 2 65535 45157 0 0]Que tipo de "[n]despertar do coração" foi esse!?![n]Eles são simplesmente assassinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_08_ [Makoto]]
[s][vp 9 2 65535 41657 0 0]Então eles despertam[n]o coração das pessoas matando-as?[n]Você está brincando comigo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_09_ [Makoto]]
[s][vp 9 2 65535 43057 0 0]Do jeito que eles fazem...[n]É como se eles gostassem[n]de matar pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_10_ [Makoto]]
[s][vp 9 2 65535 43751 0 0]Não importa o quão[n]mau ele fosse, matá-lo era[n]insano![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_11_ [Makoto]]
[s][vp 9 2 65535 42607 0 0]Eles não deveriam tê-lo matado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_12_ [Makoto]]
[s][vp 9 2 65535 41007 0 0]Como eles acham que podem despertar[n]um coração matando alguém?[n]Eles mentiram![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_13_ [Makoto]]
[s][vp 9 2 65535 44171 0 0]Do jeito que eles fazem...[n]É como se eles gostassem[n]de matar pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_14_ [Makoto]]
[s][vp 9 2 65535 42057 0 0]Não importa o quão[n]mau ele fosse, matá-lo era[n]insano![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_15_ [Makoto]]
[s][vp 9 2 65535 45157 0 0]Que tipo de "[n]despertar do coração" foi esse!?![n]Eles são simplesmente assassinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_16_ [Makoto]]
[s][vp 9 2 65535 43251 0 0]Eles despertaram o coração de uma pessoa[n]matando-a? Eles são loucos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_01_ [Makoto]]
[s][vp 9 2 65535 43507 0 0]Alguém, não importa quem,[n]faça algo para parar[n]aqueles Phantom Thieves...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_02_ [Makoto]]
[s][vp 9 2 65535 43401 0 0]Tanto o governo quanto a polícia[n]são incompetentes...[n]O que será deste país?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_03_ [Makoto]]
[s][vp 9 2 65535 40957 0 0]Mas o que a polícia está fazendo!?![n]Vamos, prendam os Ladrões[n]Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_04_ [Makoto]]
[s][vp 9 2 65535 44251 0 0]Sabemos muito bem quem são os[n]culpados, porque ninguém[n]pegou ainda!?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_05_ [Makoto]]
[s][vp 9 2 65535 38202 0 0]Não é bom...[n]A frequência desses[n]raptus é assustadora...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_06_ [Makoto]]
[s][vp 9 2 65535 45302 0 0]Tanto o governo quanto a polícia[n]são incompetentes...[n]O que será deste país?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_07_ [Makoto]]
[s][vp 9 2 65535 39707 0 0]Mas o que a polícia está fazendo!?![n]Vamos, prendam os Ladrões[n]Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_08_ [Makoto]]
[s][vp 9 2 65535 43851 0 0]Sabemos muito bem quem são os[n]culpados, porque ninguém[n]pegou ainda!?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_09_ [Makoto]]
[s][vp 9 2 65535 41907 0 0]Alguém, não importa quem,[n]faça algo para parar[n]aqueles Phantom Thieves...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_10_ [Makoto]]
[s][vp 9 2 65535 40301 0 0]Tanto o governo quanto a polícia[n]são incompetentes...[n]O que será deste país?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_11_ [Makoto]]
[s][vp 9 2 65535 37657 0 0]Apresse-se e lide com[n]aqueles Phantom Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_12_ [Makoto]]
[s][vp 9 2 65535 40251 0 0]Quando a polícia[n]irá agir para prender[n]os Phantom Thieves!?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_13_ [Makoto]]
[s][vp 9 2 65535 42707 0 0]Alguém, não importa quem,[n]faça algo para parar[n]os Phantom Thieves...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_14_ [Makoto]]
[s][vp 9 2 65535 40702 0 0]Tanto o governo quanto a polícia[n]são incompetentes...[n]O que será deste país?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_15_ [Makoto]]
[s][vp 9 2 65535 40801 0 0]Mas o que a polícia está fazendo!?![n]Vamos, prendam os Ladrões[n]Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_16_ [Makoto]]
[s][vp 9 2 65535 41657 0 0]Sabemos muito bem quem são os[n]culpados, porque ninguém[n]pegou ainda!?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_01_ [Makoto]]
[s][vp 9 2 65535 43157 0 0]Alguém tem que pegar os[n]Phantom Thieves! Eu não me importo[n]como![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_02_ [Makoto]]
[s][vp 9 2 65535 46007 0 0]A polícia finalmente[n]agiu para prendê-los...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_03_ [Makoto]]
[s][vp 9 2 65535 41251 0 0]Eles realmente acreditam que[n]uma recompensa por suas cabeças é suficiente[n]para poder prendê-los?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_04_ [Makoto]]
[s][vp 9 2 65535 41307 0 0]Esses Phantom Thieves devem ser[n]pegos imediatamente![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_05_ [Makoto]]
[s][vp 9 2 65535 38404 0 0]Sério, eles colocaram uma recompensa de 30[n]milhões de ienes!?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_06_ [Makoto]]
[s][vp 9 2 65535 41859 0 0]Prenda os Phantom Thieves[n]e acabe com tudo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_07_ [Makoto]]
[s][vp 9 2 65535 41251 0 0]Colocar uma recompensa pelas cabeças dos Phantom[n]Thieves realmente servirá para prendê-los...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_08_ [Makoto]]
[s][vp 9 2 65535 41157 0 0]Quanto mais[n]temos que viver com[n]medo dos Phantom Thieves?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_09_ [Makoto]]
[s][vp 9 2 65535 45651 0 0]Por que o governo não reage?[n]Tem que fazer alguma coisa![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_10_ [Makoto]]
[s][vp 9 2 65535 43901 0 0]A polícia está demorando muito! É possível saber[n]o que eles estão fazendo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_11_ [Makoto]]
[s][vp 9 2 65535 41401 0 0]Não deveria ser função[n]da polícia lidar com[n]criminosos?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_12_ [Makoto]]
[s][vp 9 2 65535 42157 0 0]Eu não me importo como, mas[n]prenda aqueles assassinos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_13_ [Makoto]]
[s][vp 9 2 65535 38700 0 0]A recompensa por[n]Phantom Thieves é de 30 milhões[n]ienes! Isso não é um absurdo!?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_14_ [Makoto]]
[s][vp 9 2 65535 45501 0 0]Eles devem se mover para elaborar[n]um plano eficaz. Há[n]nossa vida em jogo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_15_ [Makoto]]
[s][vp 9 2 65535 39300 0 0]A polícia finalmente[n]agiu para prendê-los.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_16_ [Makoto]]
[s][vp 9 2 65535 41302 0 0]Eles sempre levam[n]uma vida inteira para agir...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_01_ [Makoto]]
[s][vp 9 2 65535 38405 0 0]Então, as pessoas que realizam[n]comícios nas ruas[n]concorrem às eleições...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_02_ [Makoto]]
[s][vp 9 2 65535 41610 0 0]Esperamos que nosso[n]governo seja transformado[n]por essas eleições...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_03_ [Makoto]]
[s][vp 9 2 65535 42155 0 0]Mas existe alguém neste[n]mundo capaz de consertar[n]coisas?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_04_ [Makoto]]
[s][vp 9 2 65535 39009 0 0]Meu filho começou a chorar[n]porque falava muito alto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_05_ [Makoto]]
[s][vp 9 2 65535 43709 0 0]Eu gostaria que[n]um político honesto e[n]competente surgisse...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_06_ [Makoto]]
[s][vp 9 2 65535 41854 0 0]Precisamos de um[n]político forte com[n]visão de futuro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_07_ [Makoto]]
[s][vp 9 2 65535 43252 0 0]Esperemos que nas eleições apareça[n]alguém capaz de[n]revolucionar a sociedade...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_08_ [Makoto]]
[s][vp 9 2 65535 41155 0 0]Quem sabe quais candidatos têm[n]mais chances de ganhar as[n]próximas eleições...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_09_ [Makoto]]
[s][vp 9 2 65535 43704 0 0]Quem é aquele cara que[n]fez muitos discursos[n]ultimamente...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_10_ [Makoto]]
[s][vp 9 2 65535 41705 0 0]Quando é a eleição?[n]Esqueceu totalmente[n]minha mente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_11_ [Makoto]]
[s][vp 9 2 65535 39655 0 0]Não me lembro quem, mas um dos[n]candidatos parece realmente[n]especial.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_12_ [Makoto]]
[s][vp 9 2 65535 46054 0 0]Muitos[n]membros Diet[n]promissores este ano, hein?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_13_ [Makoto]]
[s][vp 9 2 65535 38705 0 0]Talvez eu esteja errado, mas as[n]eleições serão[n]no final do ano, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_14_ [Makoto]]
[s][vp 9 2 65535 40703 0 0]Mas é verdade que houve um[n]cisma dentro do[n]partido governista?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_15_ [Makoto]]
[s][vp 9 2 65535 45755 0 0]A Câmara[n]dos Deputados realmente se dissolveu?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_16_ [Makoto]]
[s][vp 9 2 65535 39011 0 0]Sim, é ele... Ele não é[n]como os outros![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_01_ [Makoto]]
[s][vp 9 2 65535 44302 0 0]O que a polícia está fazendo!?![n]Apresse-se e prenda-os...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_02_ [Makoto]]
[s][vp 9 2 65535 41751 0 0]Tanto o governo quanto a polícia[n]são incompetentes...[n]O que será deste país?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_03_ [Makoto]]
[s][vp 9 2 65535 38357 0 0]Foi muito estranho quando[n]todos começaram a falar[n]sobre os Phantom Thieves...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_04_ [Makoto]]
[s][vp 9 2 65535 39007 0 0]Os Phantom Thieves são[n]assassinos de sangue frio![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_05_ [Makoto]]
[s][vp 9 2 65535 39755 0 0]Sério, quem são os Phantom[n]Thieves...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_06_ [Makoto]]
[s][vp 9 2 65535 40709 0 0]O que a polícia está fazendo? É[n]nestes momentos que[n]precisamos mais deles...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_07_ [Makoto]]
[s][vp 9 2 65535 40257 0 0]Não perca seu tempo criando um[n]perfil criminoso dos Ladrões.[n]Apenas prenda-os...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_08_ [Makoto]]
[s][vp 9 2 65535 46063 0 0]Mas quando eles vão prender[n]os Phantom Thieves?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_09_ [Makoto]]
[s][vp 9 2 65535 44907 0 0]Então todos esses ataques[n]foram na verdade obra dos[n]Phantom Thieves?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_10_ [Makoto]]
[s][vp 9 2 65535 42709 0 0]Eu não me importo quem[n]eles são. Basta prendê-los...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_11_ [Makoto]]
[s][vp 9 2 65535 42757 0 0]Eles são um bando de assassinos,[n]claro que são todos loucos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_12_ [Makoto]]
[s][vp 9 2 65535 41107 0 0]Tenho a sensação de que tudo isso[n]pode ser rastreado até a[n]primeira aparição dos Ladrões...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_13_ [Makoto]]
[s][vp 9 2 65535 39107 0 0]Não acredito que os[n]Phantom Thieves eram apenas[n]um grupo de assassinos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_14_ [Makoto]]
[s][vp 9 2 65535 38460 0 0]Phantom Thieves são insanos:[n]deleitam-se com o assassinato[n]e tudo mais...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_15_ [Makoto]]
[s][vp 9 2 65535 40857 0 0]Esses ataques são assustadores[n]e alguém tem que fazer[n]alguma coisa![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_16_ [Makoto]]
[s][vp 9 2 65535 39005 0 0]Phantom Thieves são[n]apenas criminosos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_01_ [Makoto]]
[s][vp 9 2 65535 42503 0 0]Shido-san realmente faz jus à sua reputação. É[n]como a justiça personificada.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_02_ [Makoto]]
[s][vp 9 2 65535 41504 0 0]Shido-san[n]está muito ocupado ultimamente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_03_ [Makoto]]
[s][vp 9 2 65535 41100 0 0]Shido-san tem algo[n]que o diferencia de[n]todos os outros![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_04_ [Makoto]]
[s][vp 9 2 65535 39000 0 0]Não confio tanto em[n]nenhum outro político![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_05_ [Makoto]]
[s][vp 9 2 65535 39804 0 0]Você não acha[n]Rep. Shido[n]muito atraente?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_06_ [Makoto]]
[s][vp 9 2 65535 38453 0 0]Shido-san é exatamente o[n]tipo de político que[n]precisamos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_07_ [Makoto]]
[s][vp 9 2 65535 41300 0 0]O representante Shido tem uma aura diferente. É[n]único e inimitável![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_08_ [Makoto]]
[s][vp 9 2 65535 41153 0 0]Estou impressionado. Shido-san[n]é muito jovem, mas tem uma[n]visão concreta do futuro.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_09_ [Makoto]]
[s][vp 9 2 65535 40354 0 0]Aquele político chamado Shido[n]parece realmente competente![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_10_ [Makoto]]
[s][vp 9 2 65535 43704 0 0]Shido é um Rep[n]incrível, hein?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_11_ [Makoto]]
[s][vp 9 2 65535 42754 0 0]Todo mundo diz que o político[n]chamado Shido é nossa[n]única esperança![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_12_ [Makoto]]
[s][vp 9 2 65535 46050 0 0]Assisti a um discurso de Shido. Ele realmente[n]parece capaz de fazer a diferença![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_13_ [Makoto]]
[s][vp 9 2 65535 38403 0 0]Parece que o Representante[n]Shido está em forma ultimamente![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_14_ [Makoto]]
[s][vp 9 2 65535 43953 0 0]Ultimamente ouço frequentemente o nome do[n]representante[n]Shido mencionado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_15_ [Makoto]]
[s][vp 9 2 65535 44753 0 0]Shido-san tem um carisma que[n]outros políticos sonham![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_16_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_01_ [Makoto]]
[s][vp 9 2 65535 43910 0 0]O mundo é um lugar melhor,[n]agora que aquele Phantom Thief[n]está morto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_02_ [Makoto]]
[s][vp 9 2 65535 37602 0 0]Quem esperaria que[n]aquele Phantom Thief fosse[n]apenas uma criança...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_03_ [Makoto]]
[s][vp 9 2 65535 42154 0 0]Mas é verdade? Aquele Phantom[n]Thief tirou a própria vida!?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_04_ [Makoto]]
[s][vp 9 2 65535 39001 0 0]Eu não me importo se ele é menor de idade...[n]Ele tem que assumir[n]suas responsabilidades![n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_05_ [Makoto]]
[s][vp 9 2 65535 38401 0 0]Que porra... Você não pode se matar imediatamente[n]depois de ser pego...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_06_ [Makoto]]
[s][vp 9 2 65535 39157 0 0]E assim ele cometeu suicídio para[n]evitar ter que confessar[n]seus métodos...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_07_ [Makoto]]
[s][vp 9 2 65535 39705 0 0]Tenho certeza que[n]outro[n]raptus nunca mais acontecerá...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_08_ [Makoto]]
[s][vp 9 2 65535 44202 0 0]Aquele Phantom Thief se matou!?! Eu pensei que[n]ele tinha acabado de ser preso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_09_ [Makoto]]
[s][vp 9 2 65535 39504 0 0]O líder dos Phantom Thieves foi[n]capturado e[n]tirou a própria vida!?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_10_ [Makoto]]
[s][vp 9 2 65535 40355 0 0]Ele não deveria ter se matado[n]só porque foi[n]pego...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_11_ [Makoto]]
[s][vp 9 2 65535 42154 0 0]Mas é verdade que o Phantom Thief[n]era um estudante!?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_12_ [Makoto]]
[s][vp 9 2 65535 42352 0 0]Nunca pensei que[n]Phantom Thief fosse apenas[n]um menor de idade...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_13_ [Makoto]]
[s][vp 9 2 65535 42302 0 0]Ele se matou na cela, hein?[n]Que final ruim...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_14_ [Makoto]]
[s][vp 9 2 65535 45311 0 0]Agora que aquele Phantom Thief[n]chutou o balde, estamos[n]seguros, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_15_ [Makoto]]
[s][vp 9 2 65535 39355 0 0]Mas é verdade? Aquele Phantom[n]Thief tirou a própria vida!?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_16_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_01_ [Makoto]]
[s][vp 9 2 65535 40750 0 0]Devemos confiar em Shido-san[n]para consertar este[n]mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_02_ [Makoto]]
[s][vp 9 2 65535 41353 0 0]Precisamos que Shido seja eleito.[n]Ele fará as mudanças[n]que a sociedade precisa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_03_ [Makoto]]
[s][vp 9 2 65535 40400 0 0]Shido-san será um grande[n]líder para este país![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_04_ [Makoto]]
[s][vp 9 2 65535 39361 0 0]Shido-san vai melhorar esta[n]nação! Ele consegue![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_05_ [Makoto]]
[s][vp 9 2 65535 38403 0 0]Ouvi dizer que Shido-san[n]vai revolucionar o mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_06_ [Makoto]]
[s][vp 9 2 65535 41850 0 0]Shido vai mudar este[n]país para melhor.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_07_ [Makoto]]
[s][vp 9 2 65535 45904 0 0]Há rumores de que o[n]próximo primeiro-ministro[n]representante Shido será nomeado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_08_ [Makoto]]
[s][vp 9 2 65535 46100 0 0]Shido-san vai ganhar a eleição![n]Não há dúvida![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_09_ [Makoto]]
[s][vp 9 2 65535 38804 0 0]Representante Shido[n]iniciará uma revolução![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_10_ [Makoto]]
[s][vp 9 2 65535 43003 0 0]Shido-san mudará o Japão![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_11_ [Makoto]]
[s][vp 9 2 65535 42454 0 0]Acho que Shido tem essas[n]eleições no bolso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_12_ [Makoto]]
[s][vp 9 2 65535 45253 0 0]Representante Shido[n]vai mudar este país![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_13_ [Makoto]]
[s][vp 9 2 65535 42850 0 0]Espero grandes coisas de você,[n]Representante Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_14_ [Makoto]]
[s][vp 9 2 65535 41853 0 0]Tudo ficará bem enquanto[n]Shido-san estiver conosco![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_15_ [Makoto]]
[s][vp 9 2 65535 40400 0 0]Representante Shido é o[n]melhor guia para nosso[n]futuro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_16_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_01_ [Makoto]]
[s][vp 9 2 65535 39503 0 0]Posso não ser um especialista, mas sei[n]que apostar no Shido[n]é a escolha certa![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_02_ [Makoto]]
[s][vp 9 2 65535 41953 0 0]Mal posso esperar para descobrir[n]o que Shido planejou para[n]reconstruir nossa nação.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_03_ [Makoto]]
[s][vp 9 2 65535 41153 0 0]Shido-san é tão confiável![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_04_ [Makoto]]
[s][vp 9 2 65535 39350 0 0]Certamente Shido-san levará[n]nossa nação[n]à grandeza![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_05_ [Makoto]]
[s][vp 9 2 65535 41750 0 0]O mundo precisa de[n]Shido-san![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_06_ [Makoto]]
[s][vp 9 2 65535 42053 0 0]Masayoshi Shido será o[n]líder do próximo[n]partido governante![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_07_ [Makoto]]
[s][vp 9 2 65535 41653 0 0]Não sei porque, mas Shido-san[n]me inspira muita confiança.[n]É espontâneo, sabe?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_08_ [Makoto]]
[s][vp 9 2 65535 41000 0 0]Mal posso esperar para ver quais[n]programas Shido tem[n]armazenado para o país![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_09_ [Makoto]]
[s][vp 9 2 65535 41753 0 0]Nós administraremos confiando[n]completamente em Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_10_ [Makoto]]
[s][vp 9 2 65535 43403 0 0]Então Shido-san será[n]nosso novo primeiro-ministro[n]após a eleição, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_11_ [Makoto]]
[s][vp 9 2 65535 42603 0 0]Shido-san vai revolucionar o[n]mundo inteiro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_12_ [Makoto]]
[s][vp 9 2 65535 41550 0 0]Nada de ruim já foi dito sobre Shido, então vou[n]votar nele sem hesitar.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_13_ [Makoto]]
[s][vp 9 2 65535 40161 0 0]De agora em diante, Shido-san liderará[n]o Japão no futuro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_14_ [Makoto]]
[s][vp 9 2 65535 45511 0 0]Shido-san transmite algo[n]que os outros não têm.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_15_ [Makoto]]
[s][vp 9 2 65535 38961 0 0]Ninguém pode vencer[n]Shido-san![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_16_ [Makoto]]
[s][vp 9 2 65535 39353 0 0]Nosso governo está agora[n]em boas mãos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_01_ [Makoto]]
[s][vp 9 2 65535 42251 0 0]Mas ele não deveria estar morto, aquele Phantom[n]Thief? Que porra está acontecendo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_02_ [Makoto]]
[s][vp 9 2 65535 41954 0 0]O que você acha do discurso[n]que eles fizeram após[n]sabotar as transmissões?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_03_ [Makoto]]
[s][vp 9 2 65535 41405 0 0]Realmente importa quem[n]está certo ou não?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_04_ [Makoto]]
[s][vp 9 2 65535 39355 0 0]O que está acontecendo...?[n]O que devemos fazer agora?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_05_ [Makoto]]
[s][vp 9 2 65535 38201 0 0]Não sei mais em que acreditar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_06_ [Makoto]]
[s][vp 9 2 65535 45509 0 0]Duvido que Shido-san faça[n]o que aqueles Phantom Thieves dizem[n]...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_07_ [Makoto]]
[s][vp 9 2 65535 41105 0 0]É verdade o que[n]os Phantom Thieves dizem...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_08_ [Makoto]]
[s][vp 9 2 65535 41457 0 0]Basicamente, o que é essa história de[n]Phantom Thieves?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_09_ [Makoto]]
[s][vp 9 2 65535 40155 0 0]Não sei mais em que acreditar.[n]Aposto que Shido[n]vai ficar bem.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_10_ [Makoto]]
[s][vp 9 2 65535 44901 0 0]Mas por que ainda falamos[n]sobre os Phantom Thieves?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_11_ [Makoto]]
[s][vp 9 2 65535 43355 0 0]Tenho certeza que tudo ficará[n]bem se deixarmos para Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_12_ [Makoto]]
[s][vp 9 2 65535 44757 0 0]The Phantom Thieves de novo?[n]O que está acontecendo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_13_ [Makoto]]
[s][vp 9 2 65535 41909 0 0]Por que os Phantom Thieves[n]apareceram de repente?[n]Eu não entendo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_14_ [Makoto]]
[s][vp 9 2 65535 39155 0 0]Os Phantom Thieves devem estar[n]mentindo, certo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_15_ [Makoto]]
[s][vp 9 2 65535 43205 0 0]O que os Ladrões dizem[n]será tudo inventado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_16_ [Makoto]]
[s][vp 9 2 65535 39352 0 0]Agora que os Phantom Thieves[n]sobreviveram novamente, eu não sei mais[n]no que acreditar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_01_ [Makoto]]
[s][vp 9 2 65535 42252 0 0]Shido-san deveria ter[n]mudado as coisas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_02_ [Makoto]]
[s][vp 9 2 65535 41202 0 0]Eu não posso acreditar nisso. Isso[n]não pode ser verdade, Shido-san...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_03_ [Makoto]]
[s][vp 9 2 65535 41252 0 0]Shido-san não vai nos abandonar,[n]ele vai...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_04_ [Makoto]]
[s][vp 9 2 65535 39702 0 0]Achei que poderia[n]confiar em Shido-san...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_05_ [Makoto]]
[s][vp 9 2 65535 38102 0 0]Se não podemos nem[n]confiar em Shido-san, que tipo[n]final nos espera...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_06_ [Makoto]]
[s][vp 9 2 65535 39855 0 0]Shido-san não está se sentindo bem?[n]Mas ele estará de volta ao campo,[n]certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_07_ [Makoto]]
[s][vp 9 2 65535 46102 0 0]Eu estava convencido de que Shido-san[n]realmente mudaria[n]esta nação...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_08_ [Makoto]]
[s][vp 9 2 65535 40052 0 0]O que faremos sem[n]Shido-san...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_09_ [Makoto]]
[s][vp 9 2 65535 38702 0 0]Shido-san deve ter exigido muito de si mesmo.[n]Ele vai se recuperar?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_10_ [Makoto]]
[s][vp 9 2 65535 45652 0 0]Estou um pouco preocupado com a saúde dela. Não é[n]como se ele fosse renunciar, não é?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_11_ [Makoto]]
[s][vp 9 2 65535 42452 0 0]Sem Shido-san, este[n]país está condenado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_12_ [Makoto]]
[s][vp 9 2 65535 39702 0 0]Não, Representante Shido...[n]Isso não pode ser verdade...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_13_ [Makoto]]
[s][vp 9 2 65535 40552 0 0]O que faremos sem[n]Shido-san...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_14_ [Makoto]]
[s][vp 9 2 65535 45302 0 0]Não... Precisamos de você,[n]Representante Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_15_ [Makoto]]
[s][vp 9 2 65535 42152 0 0]Shido-san já venceu...[n]Espero que ele não desista.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_16_ [Makoto]]
[s][vp 9 2 65535 39705 0 0]Ele falava com tanta energia...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_01_ [Makoto]]
[s][vp 9 2 65535 39105 0 0]Não importa em quem confiamos.[n]Nada nunca vai mudar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_02_ [Makoto]]
[s][vp 9 2 65535 44702 0 0]Não há esperança...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_03_ [Makoto]]
[s][vp 9 2 65535 38302 0 0]Acabou...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_04_ [Makoto]]
[s][vp 9 2 65535 40052 0 0]Não consigo mais acreditar em nada...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_05_ [Makoto]]
[s][vp 9 2 65535 41952 0 0]Nada vai mudar...[n]Estamos completamente desamparados...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_06_ [Makoto]]
[s][vp 9 2 65535 38455 0 0]É impossível...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_07_ [Makoto]]
[s][vp 9 2 65535 45452 0 0]Alguém conserte este[n]país, por favor...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_08_ [Makoto]]
[s][vp 9 2 65535 44805 0 0]Eu não me importo mais. Enfim[n]nada vai mudar mesmo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_09_ [Makoto]]
[s][vp 9 2 65535 37802 0 0]Estamos desesperados.[n]Alguém nos ajude...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_10_ [Makoto]]
[s][vp 9 2 65535 39052 0 0]Eu não me importo com quem...[n]Alguém nos salve...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_11_ [Makoto]]
[s][vp 9 2 65535 40652 0 0]Como isso pode acontecer?[n]Alguém tem que intervir...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_12_ [Makoto]]
[s][vp 9 2 65535 41552 0 0]Sem o representante Shido,[n]o país está praticamente[n]condenado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_13_ [Makoto]]
[s][vp 9 2 65535 44902 0 0]Alguém nos salve...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_14_ [Makoto]]
[s][vp 9 2 65535 39152 0 0]Estamos condenados...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_15_ [Makoto]]
[s][vp 9 2 65535 46202 0 0]Como isso vai acabar?[n]Alguém tem que nos ajudar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_16_ [Makoto]]
[s][vp 9 2 65535 41152 0 0]O que podemos fazer...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_01_ [Makoto]]
[s][vp 9 2 65535 39054 0 0]O que mais você precisa além do[n]essencial?[n]Eu amo o minimalismo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_02_ [Makoto]]
[s][vp 9 2 65535 41850 0 0]Minha família cresceu,[n]então tenho que ficar no serviço.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_03_ [Makoto]]
[s][vp 9 2 65535 39954 0 0]Esse? É um presente para minha mãe. Eu tomo um[n]todo ano.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_04_ [Makoto]]
[s][vp 9 2 65535 40053 0 0]O Japão é tão pacífico[n]sem incidentes perturbadores.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_05_ [Makoto]]
[s][vp 9 2 65535 40153 0 0]Vejo você no lugar de sempre, ok?[n]Aposto que as meninas[n]virão de qualquer maneira.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_06_ [Makoto]]
[s][vp 9 2 65535 39850 0 0]Você pode guardar essa[n]garrafa para mim? Na próxima[n]vez trarei minha esposa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_07_ [Makoto]]
[s][vp 9 2 65535 41550 0 0]Ele ainda usa a primeira gravata[n]que dei a ele.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_08_ [Makoto]]
[s][vp 9 2 65535 39702 0 0]Então aquela garota está[n]de volta à cidade e... e aí,[n]você não se lembra?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_09_ [Makoto]]
[s][vp 9 2 65535 59020 0 0]Desculpe, tenho que levar[n]minha filha para a aula.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_10_ [Makoto]]
[s][vp 9 2 65535 38103 0 0]Hoje eu tenho estágio de novo,[n]então... eu poderia ficar[n]livre à noite![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_11_ [Makoto]]
[s][vp 9 2 65535 37703 0 0]18 pontos é melhor do que[n]da outra vez. Você deveria estar[n]feliz![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_12_ [Makoto]]
[s][vp 9 2 65535 46050 0 0]Ver todo mundo assim me traz[n]de volta a como éramos[n]uma vez.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_13_ [Makoto]]
[s][vp 9 2 65535 43905 0 0]Meu snowboard? Você pode ficar com ele.[n]Eu não uso mais.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_14_ [Makoto]]
[s][vp 9 2 65535 39501 0 0]Espere, o que aconteceu com a[n]transferência!?! Achei que você tivesse[n]ordens para movê-lo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_15_ [Makoto]]
[s][vp 9 2 65535 38954 0 0]Não está procurando trabalho? Oh,[n]você está fazendo mestrado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_16_ [Makoto]]
[s][vp 9 2 65535 40652 0 0]Viagens de negócios para o exterior?[n]Eu não... Você conhece alguém[n]que já fez isso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_01_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_02_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_03_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_04_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_05_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_06_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_07_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_08_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_09_ [Makoto]]
[s][vp 9 2 65535 40152 0 0]Algo mudou...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_10_ [Makoto]]
[s][vp 9 2 65535 39752 0 0]Eh, eu só tenho que pensar em[n]meu pequeno jardim...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_11_ [Makoto]]
[s][vp 9 2 65535 37700 0 0]Sabe, talvez eu tente[n]fazer alguma coisa...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_12_ [Makoto]]
[s][vp 9 2 65535 40652 0 0]Quem sabe se o mundo[n]pode melhorar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_13_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_14_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_15_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_16_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_01_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_02_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_03_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_04_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_05_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_06_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_07_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_08_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_09_ [Makoto]]
[s][vp 9 2 65535 41610 0 0]Eu quero ficar rico[n]rápido... Há[n]boas oportunidades?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_10_ [Makoto]]
[s][vp 9 2 65535 41509 0 0]Não é minha culpa...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_11_ [Makoto]]
[s][vp 9 2 65535 42452 0 0]Nada nunca vai mudar.[n]Não há necessidade de levar[n]coisas a sério.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_12_ [Makoto]]
[s][vp 9 2 65535 45060 0 0]Todo dia é chato...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_13_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_14_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_15_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_16_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_01_ [Makoto]]
[s][vp 9 2 65535 39802 0 0]Isso é um negócio sério.[n]Não podemos[n]continuar assim.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_02_ [Makoto]]
[s][vp 9 2 65535 45654 0 0]Você viu o vídeo do acidente?[n]O descarrilamento[n]foi chocante...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_03_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]O trem ainda está atrasado?[n]Ugh, que chatice...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_04_ [Makoto]]
[s][vp 9 2 65535 41301 0 0]Deve ser obra de terroristas![n]Claro![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_05_ [Makoto]]
[s][vp 9 2 65535 38101 0 0]Os trens estão parados há algum tempo. O que[n]diabos está acontecendo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_06_ [Makoto]]
[s][vp 9 2 65535 38452 0 0]Quantos acidentes...![n]Agora podem acontecer[n]a qualquer momento...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_07_ [Makoto]]
[s][vp 9 2 65535 40802 0 0]Segurança é uma piada aqui. Tenho medo[n]de pegar o trem...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_08_ [Makoto]]
[s][vp 9 2 65535 40952 0 0]Quantos acidentes...![n]Agora podem acontecer[n]a qualquer momento...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_01_ [Makoto]]
[s][vp 9 2 65535 38504 0 0]Se foi no Good Morning Japan,[n]deve ser um[n]artista famoso, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_02_ [Makoto]]
[s][vp 9 2 65535 43554 0 0]Ouvi dizer que no mundo[n]da arte japonesa não há[n]ninguém do nível dele![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_03_ [Makoto]]
[s][vp 9 2 65535 40954 0 0]Se foi no Good Morning[n]Japan, deve ser um[n]artista famoso, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_04_ [Makoto]]
[s][vp 9 2 65535 46050 0 0]Madarame, o artista, era[n]um Good Morning Japan![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_05_ [Makoto]]
[s][vp 9 2 65535 38800 0 0]Então aquele Madarame que[n]estava no Good Morning Japan[n]é muito bom, hein...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_06_ [Makoto]]
[s][vp 9 2 65535 45300 0 0]Ouvi dizer que no mundo[n]da arte japonesa não há[n]ninguém do nível dele![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_07_ [Makoto]]
[s][vp 9 2 65535 41004 0 0]Se foi no Good Morning[n]Japan, deve ser um[n]artista famoso, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_08_ [Makoto]]
[s][vp 9 2 65535 46058 0 0]Madarame, o artista, era[n]um Good Morning Japan![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_09_ [Makoto]]
[s][vp 9 2 65535 43403 0 0]Eles anunciaram que haverá uma exposição dedicada[n]aos trabalhos de Madarame.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_10_ [Makoto]]
[s][vp 9 2 65535 40104 0 0]Parece que no mundo[n]da arte japonesa[n]ninguém está no nível dele![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_11_ [Makoto]]
[s][vp 9 2 65535 41254 0 0]Então aquele Madarame que[n]estava no Good Morning Japan[n]é muito bom, hein...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_12_ [Makoto]]
[s][vp 9 2 65535 43450 0 0]Ninguém pode igualá-lo no[n]campo da arte japonesa![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_13_ [Makoto]]
[s][vp 9 2 65535 45654 0 0]Eles anunciaram que haverá uma exposição dedicada[n]aos trabalhos de Madarame.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_14_ [Makoto]]
[s][vp 9 2 65535 39153 0 0]Parece que no mundo[n]da arte japonesa[n]ninguém está no nível dele![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_15_ [Makoto]]
[s][vp 9 2 65535 45050 0 0]Eu ouvi que o artista[n]Madarame estava no Good[n]Morning Japan![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_16_ [Makoto]]
[s][vp 9 2 65535 41300 0 0]Ninguém pode igualá-lo no[n]campo da arte japonesa![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_01_ [Makoto]]
[s][vp 9 2 65535 41602 0 0]É verdade que nem a[n]polícia pode fazer nada?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_02_ [Makoto]]
[s][vp 9 2 65535 37604 0 0]Eles parecem usar[n]truques muito sujos.[n]Eles são terríveis.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_03_ [Makoto]]
[s][vp 9 2 65535 40602 0 0]Ouvi dizer que houve[n]muitas vítimas[n]nesta história...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_04_ [Makoto]]
[s][vp 9 2 65535 44201 0 0]O que a polícia está fazendo? Por[n]esta etapa, eles acabarão[n]ferindo outras pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_05_ [Makoto]]
[s][vp 9 2 65535 40302 0 0]Sua família também foi[n]ameaçada? Mas é terrível...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_06_ [Makoto]]
[s][vp 9 2 65535 41852 0 0]Eles parecem usar[n]truques muito sujos.[n]Eles são terríveis.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_07_ [Makoto]]
[s][vp 9 2 65535 44502 0 0]Ouvi dizer que houve[n]muitas vítimas[n]nesta história...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_08_ [Makoto]]
[s][vp 9 2 65535 43201 0 0]O que a polícia está fazendo? Por[n]esta etapa, eles acabarão[n]ferindo outras pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_09_ [Makoto]]
[s][vp 9 2 65535 40555 0 0]É verdade que nem a[n]polícia pode fazer nada?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_10_ [Makoto]]
[s][vp 9 2 65535 39802 0 0]Eles parecem usar[n]truques muito sujos.[n]Eles são terríveis.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_11_ [Makoto]]
[s][vp 9 2 65535 40654 0 0]Uma vez dentro,[n]eles te forçam a fazer[n]coisas horríveis...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_12_ [Makoto]]
[s][vp 9 2 65535 41301 0 0]O que a polícia está fazendo? Por[n]esta etapa, eles acabarão[n]ferindo outras pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_13_ [Makoto]]
[s][vp 9 2 65535 43002 0 0]É verdade que nem a[n]polícia pode fazer nada?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_14_ [Makoto]]
[s][vp 9 2 65535 45505 0 0]Eles parecem usar[n]truques muito sujos.[n]Eles são terríveis.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_15_ [Makoto]]
[s][vp 9 2 65535 39955 0 0]Ouvi dizer que houve[n]muitas vítimas[n]nesta história...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_16_ [Makoto]]
[s][vp 9 2 65535 45252 0 0]O que a polícia está fazendo? Por[n]esta etapa, eles acabarão[n]ferindo outras pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_01_ [Makoto]]
[s][vp 9 2 65535 43150 0 0]Mal posso esperar para ver[n]as meninas em seus yukatas.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_02_ [Makoto]]
[s][vp 9 2 65535 38811 0 0]Mas quem tem tempo para ir[n]ver os fogos de artifício?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_03_ [Makoto]]
[s][vp 9 2 65535 40203 0 0]Talvez me faça bem ir[n]ao show de fogos de artifício...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_04_ [Makoto]]
[s][vp 9 2 65535 41405 0 0]Por causa do trabalho, não vi[n]fogos de artifício na[n]vida...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_05_ [Makoto]]
[s][vp 9 2 65535 40500 0 0]Vai ter[n]fogo de artifício, né?[n]Você vai?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_06_ [Makoto]]
[s][vp 9 2 65535 38451 0 0]Mas quem tem tempo para ir[n]ver os fogos de artifício?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_07_ [Makoto]]
[s][vp 9 2 65535 44853 0 0]Talvez me faça bem ir[n]ao show de fogos de artifício...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_08_ [Makoto]]
[s][vp 9 2 65535 41005 0 0]Por causa do trabalho, não vi[n]fogos de artifício na[n]vida...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_09_ [Makoto]]
[s][vp 9 2 65535 39805 0 0]O festival de fogos de artifício.[n]Só espero que não haja muita[n]sujeira na frente da minha loja.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_10_ [Makoto]]
[s][vp 9 2 65535 38802 0 0]Sim, sim... fogos de artifício o[n]não, ainda não terei férias.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_11_ [Makoto]]
[s][vp 9 2 65535 38954 0 0]Por que não ficamos juntos?[n]Seria ótimo![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_12_ [Makoto]]
[s][vp 9 2 65535 39003 0 0]Não consigo me lembrar da última vez[n]que vi fogos de artifício...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_13_ [Makoto]]
[s][vp 9 2 65535 39803 0 0]É cheio de yukata...[n]Eu os amo![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_14_ [Makoto]]
[s][vp 9 2 65535 39850 0 0]O yukata deve ser[n]usado com estilo![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_15_ [Makoto]]
[s][vp 9 2 65535 39658 0 0]Olha esse yukata![n]O molde é super fofo![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_16_ [Makoto]]
[s][vp 9 2 65535 39703 0 0]Quem sabe quanto tempo[n]estes fogos de artifício vão durar...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_01_ [Makoto]]
[s][vp 9 2 65535 41607 0 0]Você viu a coletiva de imprensa de Okumura?[n]Crazy...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_02_ [Makoto]]
[s][vp 9 2 65535 45001 0 0]Eles realmente exageraram...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_03_ [Makoto]]
[s][vp 9 2 65535 40607 0 0]O que aconteceu com[n]Sr. Okumura não era uma farsa, era...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_04_ [Makoto]]
[s][vp 9 2 65535 42157 0 0]Seus[n]olhos rolaram... Foi assustador...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_05_ [Makoto]]
[s][vp 9 2 65535 41602 0 0]Foi uma[n]execução pública… Uma[n]visão aterradora…[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_06_ [Makoto]]
[s][vp 9 2 65535 41857 0 0]Eles realmente exageraram...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_07_ [Makoto]]
[s][vp 9 2 65535 44202 0 0]O que aconteceu com[n]Sr. Okumura não era uma farsa, era...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_08_ [Makoto]]
[s][vp 9 2 65535 46107 0 0]Seus[n]olhos rolaram... Foi assustador...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_09_ [Makoto]]
[s][vp 9 2 65535 42302 0 0]O que aconteceu com Okumura foi[n]simplesmente horrível...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_10_ [Makoto]]
[s][vp 9 2 65535 37857 0 0]Aquela coletiva de imprensa[n]me traumatizou...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_11_ [Makoto]]
[s][vp 9 2 65535 38252 0 0]Você viu aquela[n]conferência de imprensa? Foi[n]arrepiante...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_12_ [Makoto]]
[s][vp 9 2 65535 43207 0 0]Foram os Phantom Thieves,[n]certo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_13_ [Makoto]]
[s][vp 9 2 65535 43057 0 0]O que aconteceu com Okumura foi[n]simplesmente horrível...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_14_ [Makoto]]
[s][vp 9 2 65535 38460 0 0]Aquela coletiva de imprensa[n]me traumatizou...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_15_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]Não era CG, era...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_16_ [Makoto]]
[s][vp 9 2 65535 45057 0 0]Foram os Phantom Thieves,[n]certo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_01_ [Makoto]]
[s][vp 9 2 65535 44904 0 0]Aquele detetive, Akechi, é[n]muito inteligente...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_02_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_03_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_04_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_05_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_06_ [Makoto]]
[s][vp 9 2 65535 42050 0 0]Mesmo estando apenas no ensino médio,[n]aquele Akechi já alcançou[n]vários marcos.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_07_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_08_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_09_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_10_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_11_ [Makoto]]
[s][vp 9 2 65535 38904 0 0]Akechi-kun é legal,[n]ele é bonito... Ele é perfeito[n]em todos os sentidos![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_12_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_13_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_14_ [Makoto]]
[s][vp 9 2 65535 39154 0 0]Você ouviu falar daquele detetive,[n]Akechi...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_15_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_16_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_01_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_02_ [Makoto]]
[s][vp 9 2 65535 41957 0 0]Como sabemos[n]se vão continuar a bater[n]só em quem merece...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_03_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_04_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_05_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_06_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_07_ [Makoto]]
[s][vp 9 2 65535 45157 0 0]Eles controlam o coração das pessoas[n]como querem, completamente[n]como querem...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_08_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_09_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_10_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_11_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_12_ [Makoto]]
[s][vp 9 2 65535 45257 0 0]Quem nos diz que eles não vão começar[n]atacar mesmo aqueles que não são[n]obviamente maus?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_13_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_14_ [Makoto]]
[s][vp 9 2 65535 39157 0 0]Manipular o coração de[n]pessoas... Como ele diz, é[n]um tanto suspeito.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_15_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_16_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_01_ [Makoto]]
[s][vp 9 2 65535 38700 0 0]Eu gostaria de poder namorar[n]uma garota bonita![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_02_ [Makoto]]
[s][vp 9 2 65535 38800 0 0]A garota que acabou de[n]passar era um espetáculo...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_03_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]Tudo bem, apenas certifique-se de que não haja[n]atrasos...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_04_ [Makoto]]
[s][vp 9 2 65535 39354 0 0]Ah, então fazer algum[n]exercício pode reduzir[n]o estresse?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_05_ [Makoto]]
[s][vp 9 2 65535 38750 0 0]Ei, olha isso![n]Ah, ela se foi...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_06_ [Makoto]]
[s][vp 9 2 65535 37800 0 0]As garotas de hoje são[n]tão refinadas![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_07_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]Se eu me atrasar por causa do[n]trem, ficarei muito chateado![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_08_ [Makoto]]
[s][vp 9 2 65535 38052 0 0]Eu sei que é melhor se eu[n]praticar, mas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_09_ [Makoto]]
[s][vp 9 2 65535 38101 0 0]Eu sinto a tensão[n]onde quer que eu vá...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_10_ [Makoto]]
[s][vp 9 2 65535 38802 0 0]Se apenas do céu[n]dinheiro chovesse...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_11_ [Makoto]]
[s][vp 9 2 65535 40802 0 0]O incidente foi um[n]ataque terrorista, certo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_12_ [Makoto]]
[s][vp 9 2 65535 38052 0 0]Meu filho nunca estuda.[n]Ele só foca nos clubes...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_13_ [Makoto]]
[s][vp 9 2 65535 37552 0 0]Ele é atlético e TAMBÉM bonito...?[n]A vida é injusta...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_14_ [Makoto]]
[s][vp 9 2 65535 38802 0 0]Todo dia é um pesadelo...[n]Eu mereço um tapinha nas costas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_15_ [Makoto]]
[s][vp 9 2 65535 39302 0 0]Eu diria que não há[n]mais lugares seguros...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_16_ [Makoto]]
[s][vp 9 2 65535 40952 0 0]Caramba, você poderia pelo menos[n]lavar seu uniforme...[n][f 1 2 180][e]

[msg MSG_HOMELESS_DAY_001_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Algo errado? Embora seja legal[n]que você preste atenção em[n]alguém como eu.[n][w][e]
[s][vp 8 2 1 0 30 0]Você é jovem, então obtenha aconselhamento. Tenha[n]cuidado para não acabar como eu.[n][w][e]
[s][vp 8 2 1 0 30 0]Não quero assustar você, mas[n]qualquer um pode acabar assim[n]se não tomar cuidado.[n][w][e]

[msg MSG_HOMELESS_DAY_002_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Hum? Você precisa de algo?[n][w][e]

[sel SEL_HOMELESS_DAY_002_0_0 top]
[s]Eu estava apenas dando uma olhada.[e]
[s]É difícil viver assim?[e]

[msg MSG_HOMELESS_DAY_002_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Mmm, acho que você não vê[n]pessoas como eu com frequência.[n]Talvez eu pareça estranho para você.[n][w][e]
[s][vp 8 2 1 0 30 0]Estou bem, escolhi[n]esta vida... mas você tenta[n]ser cuidadoso.[n][w][e]
[s][vp 8 2 1 0 30 0]Conheço pessoas que[n]acabaram assim por causa de[n]pessoas de má reputação.[n][w][e]

[msg MSG_HOMELESS_DAY_002_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Haha, é bom ver que[n]você se importa comigo. Não se preocupe,[n]eu estou acostumado com isso. Eu vou ficar bem.[n][w][e]
[s][vp 8 2 1 0 30 0]Eu tenho vivido esta vida desde que posso[n]memória. Minhas lembranças são[n]um pouco confusas, mas...[n][w][e]
[s][vp 8 2 1 0 30 0]Na verdade, tenho problemas para lembrar[n]o que acontece à noite...[n]Bem, isso não é grande coisa.[n][w][e]

[msg MSG_HOMELESS_NIGHT_002_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]O que você quer? Vá para casa,[n]se não quiser se machucar.[n][w][e]

[sel SEL_HOMELESS_NIGHT_002_0 top]
[s]Nada.[e]
[s]Sinto muito.[e]
[s]O que você está fazendo?[e]

[msg MSG_HOMELESS_NIGHT_002_1 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Tsk, então você só quer irritá-lo. Bah.[n][w][e]
[s][vp 8 2 1 0 30 0]Você ouviu sobre aquele enorme[n]acidente outro dia?[n]Coisa muito engraçada![n][w][e]
[s][vp 8 2 1 0 30 0]Isso deixou todo mundo nervoso.[n]Eu adoro ver suas[n]expressões apavoradas.[n][w][e]

[msg MSG_HOMELESS_NIGHT_002_2 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Muito bem, é melhor se crianças como você forem[n]boas.[n][w][e]
[s][vp 8 2 1 0 30 0]Na cidade você corre o risco de se machucar[n]se se intrometer nos assuntos dos[n]outros, sabe? Fique ligado.[n][w][e]

[msg MSG_HOMELESS_NIGHT_002_3 [Morador de rua]]
[s][vp 8 2 1 0 30 0]O que você se importa?[n]A maneira como eu vivo[n]não diz respeito a você, garoto.[n][w][e]
[s][vp 8 2 1 0 30 0]Na cidade você corre o risco de se machucar[n]se se intrometer nos assuntos dos[n]outros, sabe? Fique ligado.[n][w][e]

[msg MSG_HOMELESS_DAY_003_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ei, há algo que eu[n]quero perguntar a você.[n][w][e]
[s][vp 8 2 1 0 30 0]Eu ouvi falar de um "Madarame", um[n]com uma certa reputação.[n]Ele é um homem tão bom?[n][w][e]

[sel SEL_HOMELESS_DAY_003_0_0 top]
[s]É bem famoso.[e]
[s]Ele é uma pessoa má.[e]

[msg MSG_HOMELESS_DAY_003_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Entendi. Ele deve ser muito bom em fazer os[n]outros acreditarem no que ele quer.[n][w][e]

[msg MSG_HOMELESS_DAY_003_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Oh sim? Existe algum[n]rumor sobre ele?[n][w][e]

[msg MSG_HOMELESS_DAY_003_3_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Um amigo meu diz que é um ex-aluno dele. Ouvir[n]isso, foi uma experiência terrível.[n][w][e]
[s][vp 8 2 1 0 30 0]Eu não queria me aprofundar nisso.[n]Eu não queria me intrometer[n]em sua vida.[n][w][e]

[msg MSG_HOMELESS_NIGHT_003_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 3 10 0 10]Como eu pensei, eles estão todos[n]animados com[n]as cenas daquele velho bastardo.[n][w][e]
[s][vp 8 2 1 0 30 0]Quem sabe quantas pessoas[n]sofreram por causa dele.[n]Mas eu não dou a mínima de qualquer maneira.[n][w][e]

[msg MSG_HOMELESS_DAY_004_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Encontrei mais dinheiro[n]no meu bolso. A coisa é, eu não sei[n]como eles chegaram lá ...[n][w][e]

[sel SEL_HOMELESS_DAY_004_0_0 top]
[s]Você é sortudo.[e]
[s]Você está ficando burro?[e]
[s]O que aconteceu?[e]

[msg MSG_HOMELESS_DAY_004_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Eu penso que não. É assustador[n]encontrar dinheiro no bolso sem[n]saber de onde veio.[n][w][e]
[s][vp 8 2 1 0 30 0]Não sei o que fazer com eles, então sempre os[n]deixo em uma caixa de doações.[n][w][e]
[s][vp 8 2 1 0 30 0]Seria interessante ver[n]aquele detetive genial lutando[n]com esse mistério.[n][w][e]

[msg MSG_HOMELESS_DAY_004_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Para ser honesto, não posso refutar com certeza.[n][w][e]
[s][vp 8 2 1 0 30 0]Talvez eu seja uma coruja da noite?[n]No meio da noite eu sempre acabo[n]em outro lugar.[n][w][e]
[s][vp 8 2 1 0 30 0]Você não acha que Shibuya é[n]perigoso à noite? E se eu tiver[n]um desses ataques?[n][w][e]

[msg MSG_HOMELESS_DAY_004_3_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Comecei a ter esse[n]problema há algum tempo.[n]Não conseguia me lembrar das coisas.[n][w][e]
[s][vp 8 2 1 0 30 0]As lembranças do que acontece à[n]noite são particularmente nebulosas.[n]Isso me assusta muito, na verdade.[n][w][e]
[s][vp 8 2 1 0 30 0]Seria interessante ver[n]aquele detetive genial lutando[n]com esse mistério.[n][w][e]

[msg MSG_HOMELESS_NIGHT_004_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Tsk, ainda tenho[n]esta alteração? Depois de todo o[n]esforço que fiz.[n][w][e]

[sel SEL_HOMELESS_NIGHT_004_0 top]
[s]Que inveja.[e]
[s]Arrume um emprego.[e]
[s]O que você está fazendo aqui?[e]

[msg MSG_HOMELESS_NIGHT_004_1 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Cale-se. Quebra, garoto.[n][w][e]
[s][vp 8 2 1 0 30 0]Shibuya é uma bela cidade[n]à noite. Hehehe. Um garotinho[n]como você não consegue entender.[n][w][e]

[msg MSG_HOMELESS_NIGHT_004_2 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Não se preocupe, eu tenho[n]um emprego. E eu amo isso. À noite,[n]Shibuya é o meu reino...[n][w][e]

[msg MSG_HOMELESS_NIGHT_004_3 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Isso eu deveria perguntar.[n][w][e]
[s][vp 8 2 1 0 30 0]Cuidado, garoto. Nesta cidade[n]você não pode se intrometer[n]nos assuntos dos outros.[n][w][e]

[msg MSG_HOMELESS_NIGHT_004_4 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Bem, hora de ir[n]ear algum dinheiro. Se eu estiver com[n]minhas mãos, vou enferrujar.[n][w][e]

[msg MSG_HOMELESS_DAY_005_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]P-pare... Não tenho nada[n]de valor! Por favor,[n]não tenho nada. Eu não tenho nada...[n][w][e]
[s][vp 8 2 1 0 30 0]Huh? Você não quer me roubar? Por favor,[n]não me assuste mais assim.[n][w][e]

[sel SEL_HOMELESS_DAY_005_0_0 top]
[s]Você está exagerando.[e]
[s]Sinto muito.[e]
[s]O que aconteceu?[e]

[msg MSG_HOMELESS_DAY_005_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]É que tem havido vários[n]assaltos e assédios ultimamente...[n]Aconteceu com alguns amigos meus.[n][w][e]
[s][vp 8 2 1 0 30 0]Eles dizem que alguém dirige[n]tudo das sombras. Tente[n]ser cuidadoso, jovem.[n][w][e]

[msg MSG_HOMELESS_DAY_005_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Não, minha culpa. Eu pulei[n]rapidamente para conclusões.[n][w][e]
[s][vp 8 2 1 0 30 0]Como sempre, Shibuya é um lugar traiçoeiro à[n]noite.[n][w][e]

[msg MSG_HOMELESS_DAY_005_3_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Você ouviu sobre o caso Madarame?[n]Parece que[n]uma organização de Shibuya estava envolvida.[n][w][e]
[s][vp 8 2 1 0 30 0]Com esse movimento de[n]lavagem de dinheiro nas sombras,[n]Shibuya será perigoso por um tempo.[n][w][e]

[msg MSG_HOMELESS_NIGHT_005_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]O que você quer, garoto?[n]Se você ficar aqui à noite[n]muitas vezes, você vai se machucar.[n][w][e]

[sel SEL_HOMELESS_NIGHT_005_0 top]
[s]Eu não me importo.[e]
[s]Eu vou tomar cuidado.[e]
[s]Shibuya é perigoso?[e]

[msg MSG_HOMELESS_NIGHT_005_1 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Há cada vez mais pirralhos[n]que querem brigar[n]com pessoas como eu.[n][w][e]
[s][vp 8 2 1 0 30 0]O último que tentou[n]passou muito mal.[n]É melhor você tomar cuidado. Haha![n][w][e]

[msg MSG_HOMELESS_NIGHT_005_2 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Sim, você diz, mas não tem nenhuma intenção de[n]fazer isso, tem?[n][w][e]
[s][vp 8 2 1 0 30 0]Vocês todos falam bem, então[n]acabam fazendo[n]coisas tremendas. Como Madarame.[n][w][e]

[msg MSG_HOMELESS_NIGHT_005_3 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Digamos que galhos como você[n]tenham que ter cuidado. Este lugar[n]fez muita gente chorar...[n][w][e]
[s][vp 8 2 1 0 30 0]Falando em chorar, você viu aquele Madarame? Ele[n]choramingou como uma criança. Que divertido![n][w][e]

[msg MSG_HOMELESS_DAY_006_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Hum? O que é?[n]Procurando uma maneira de[n]matar o tempo?[n][w][e]

[sel SEL_HOMELESS_DAY_006_0_0 top]
[s]Exatamente.[e]
[s]Eu não tenho tempo.[e]
[s]Estou apenas olhando.[e]

[msg MSG_HOMELESS_DAY_006_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Vá para a passagem subterrânea da estação de[n]Shibuya, encontre anúncios de emprego perto das[n]escadas.[n][w][e]
[s][vp 8 2 1 0 30 0]Eu pensei em procurar[n]trabalho também, mas eles nunca vão dar[n]um assim... Haha.[n][w][e]

[msg MSG_HOMELESS_DAY_006_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Que bom para você. Não tenho dúvidas de que[n]as pessoas da sua idade preferem[n]se divertir do que se ocupar.[n][w][e]

[msg MSG_HOMELESS_DAY_006_3_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ouça, eu quero te perguntar uma coisa.[n]Muitas pessoas falam sobre os[n]Phantom Thieves.[n][w][e]
[s][vp 8 2 1 0 30 0]Que truque eles usam para roubar o coração das[n]pessoas? Haha, como se você soubesse...[n][w][e]

[msg MSG_HOMELESS_DAY_006_4_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ah, por falar nisso. Se acontecer de você me ver[n]à noite, você poderia manter uma distância[n]segura?[n][w][e]

[msg MSG_HOMELESS_NIGHT_006_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]O que você quer? Estou de bom humor,[n]então você pode me fazer companhia.[n][w][e]

[sel SEL_HOMELESS_NIGHT_006_0 top]
[s]Como está o seu negócio?[e]
[s]Eu não tenho nada a dizer.[e]

[msg MSG_HOMELESS_NIGHT_006_1 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Conheço um trabalho que te deixa rico.[n]Posso te dizer como entrar, mas[n]você vai ter que sumir de circulação.[n][w][e]
[s][vp 8 2 1 0 30 0]Naah, só brincando... Eheh.[n][w][e]

[msg MSG_HOMELESS_NIGHT_006_2 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Então vá para casa, garoto.[n]Se você bisbilhotar e[n]algo acontecer com você, não é da minha conta.[n][w][e]
[s][vp 8 2 1 0 30 0]À noite, este é[n]o nosso mundo... Eheh.[n][w][e]

[msg MSG_HOMELESS_NIGHT_006_4 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Eu amo a noite.[n]À noite estou livre.[n][w][e]

[msg MSG_HOMELESS_DAY_007_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Mmm?[n]Você precisa de alguma coisa?[n][w][e]

[sel SEL_HOMELESS_DAY_007_0_0 top]
[s]Eu só quero conversar um pouco.[e]
[s]Nada realmente.[e]
[s]Como está a cidade ultimamente?[e]

[msg MSG_HOMELESS_DAY_007_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Vejamos... Você sabe que os Phantom Thieves[n]enviaram uma Carta[n]de Aviso, certo?[n][w][e]
[s][vp 8 2 1 0 30 0]Tenho certeza que a atmosfera[n]vai esquentar bastante[n]por aqui.[n][w][e]

[msg MSG_HOMELESS_DAY_007_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ah, sim.[n]Você viu?[n][w][e]
[s][vp 8 2 1 0 30 0]Você já viu a Carta de Aviso dos Phantom[n]Thieves ? Eles têm uma maneira interessante de[n]se comportar.[n][w][e]

[msg MSG_HOMELESS_DAY_007_3_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Continuamos falando sobre a[n]Carta de Aviso enviada[n]pelos Phantom Thieves.[n][w][e]
[s][vp 8 2 1 0 30 0]O submundo se tornou um bando de bandidos.[n]Patético. O que aconteceu com o código de honra[n]deles?[n][w][e]

[msg MSG_HOMELESS_NIGHT_007_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Ainda a criança sem sono.[n]O que você quer?[n][w][e]

[sel SEL_HOMELESS_NIGHT_007_0 top]
[s]Eu só quero conversar um pouco.[e]
[s]Nada realmente.[e]
[s]Como está a cidade ultimamente?[e]

[msg MSG_HOMELESS_NIGHT_007_1 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Eles dizem que agora os Phantom Thieves[n]vão descontar na máfia. Eh,[n]para mim eles são apenas crianças.[n][w][e]
[s][vp 8 2 1 0 30 0]Bastaria eu brandir uma faca[n]para fazê-los fugir com o rabo[n]entre as pernas. Hahaha![n][w][e]

[msg MSG_HOMELESS_NIGHT_007_2 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Por causa daqueles Phantom Thieves[n]agora há mais[n]policiais por aqui.[n][w][e]
[s][vp 8 2 1 0 30 0]Tsk. Essa maldita[n]Carta de Aviso está[n]tornando minha vida difícil.[n][w][e]

[msg MSG_HOMELESS_NIGHT_007_3 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Desde que os Phantom Thieves[n]enviaram a Carta de Aviso, o[n]submundo de Shibuya está em crise.[n][w][e]
[s][vp 8 2 1 0 30 0]Inferno, não é tão ruim assim.[n]Eu vou me divertir fazendo[n]alguns deles... Eheheh.[n][w][e]

[msg MSG_HOMELESS_DAY_008_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Eu sinto que meus[n]amigos me evitam...[n]Talvez por causa... disso?[n][w][e]

[sel SEL_HOMELESS_DAY_008_0_0 top]
[s]O que você quer dizer com isso"?[e]
[s]Eles te odeiam?[e]

[msg MSG_HOMELESS_DAY_008_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Qualquer um que vê meu rosto[n]foge,[n]mas eu não entendo porque...[n][w][e]

[msg MSG_HOMELESS_DAY_008_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Haha... Acho que não[n]fiz nada que justifique[n]vazamentos como esse.[n][w][e]

[msg MSG_HOMELESS_DAY_008_4_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Posso te fazer uma pergunta?[n][w][e]
[s][vp 8 2 1 0 30 0]Você acha que é possível[n]alguém mudar[n]de repente sua personalidade?[n][w][e]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Não, desculpe. Deixar...[n][w][e]

[msg MSG_HOMELESS_NIGHT_008_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Umpf... O que você quer, garoto?[n][w][e]

[sel SEL_HOMELESS_NIGHT_008_0 top]
[s]Está tranquilo aqui agora?[e]
[s]Nada.[e]
[s]Você não vai dormir?[e]

[msg MSG_HOMELESS_NIGHT_008_1 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Sim, as coisas se acalmaram[n]após a prisão de Kaneshiro.[n]Os Phantom Thieves fizeram isso.[n][w][e]
[s][vp 8 2 1 0 30 0]Despertar corações parece absurdo, mas quer[n]saber? Isso torna o jogo da vida mais[n]interessante.[n][w][e]

[msg MSG_HOMELESS_NIGHT_008_2 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Desde que os Phantom Thieves[n]lidaram com Kaneshiro, a cidade[n]de repente se acalmou.[n][w][e]
[s][vp 8 2 1 0 30 0]Tsk, não há[n]aviso de perigo[n]no ar de Shibuya.[n][w][e]

[msg MSG_HOMELESS_NIGHT_008_3 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Hehehe. Eu trabalho à noite.[n]Se você tem um emprego para mim,[n]deixe uma carta nessa lixeira.[n][w][e]
[s][vp 8 2 1 0 30 0]Se você tiver algum problema[n]com lixo, eu[n]resolvo para você. Hahaha![n][w][e]

[msg MSG_HOMELESS_DAY_009_0_0 [Morador de rua]]
[s][f 4 23 1 30 5 10 4 10][vp 8 2 1 0 30 0]O? Bater nos meus amigos?[n]Impossível. Mas à noite...[n]lembro-me pouco da noite.[n][w][e]

[sel SEL_HOMELESS_DAY_009_0_0 top]
[s]Tudo está bem?[e]
[s]Não me lembro?[e]

[msg MSG_HOMELESS_DAY_009_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]S-sim, estou bem...[n][w][e]
[s][vp 8 2 1 0 30 0]Quando eu acordo de manhã eu fico com medo. Eu me[n]sinto como ... eu sou diferente.[n][w][e]

[msg MSG_HOMELESS_DAY_009_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]É como se minhas memórias fossem confusas. Como[n]se você estivesse em um sonho.[n][w][e]
[s][vp 8 2 1 0 30 0]Como se meu cérebro,[n]ou o próprio mundo,[n]foi reescrito...[n][w][e]

[msg MSG_HOMELESS_DAY_009_3_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Talvez os Phantom Thieves[n]fizeram algo para mim?[n]Não, impossível...[n][w][e]

[msg MSG_HOMELESS_NIGHT_009_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]O que você quer?[n]Estou muito chateado.[n][w][e]

[sel SEL_HOMELESS_NIGHT_009_0 top]
[s]Por quê?[e]
[s]Calmo.[e]

[msg MSG_HOMELESS_NIGHT_009_1 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Não é da sua conta.[n][w][e]
[s][vp 8 2 1 0 30 0]Se eu jogar bem minhas cartas,[n]posso transferir a culpa pelo meu[n]trabalho para os Phantom Thieves...[n][w][e]
[s][vp 8 2 1 0 30 0]Ei, que porra é essa?!?[n]Vá embora, faça fila em outro lugar,[n]saia daqui![n][w][e]

[msg MSG_HOMELESS_NIGHT_009_2 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Umpf, um velho bastardo[n]tentou invadir meu[n]território. Eu o silenciei.[n][w][e]
[s][vp 8 2 1 0 30 0]Se você não quer acabar assim também, fique longe[n]dessa lixeira.[n][w][e]
[s][vp 8 2 1 0 30 0]Mas se você tem um pedido para mim,[n]é outra história... Eheh.[n][w][e]

[msg MSG_HOMELESS_DAY_010_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Que coisas terríveis eu fiz...[n]Nesse ritmo, seria[n]melhor se eu morresse...[n][w][e]

[sel SEL_HOMELESS_DAY_010_0_0 top]
[s]O que aconteceu?[e]
[s]Volte a sí mesmo.[e]

[msg MSG_HOMELESS_DAY_010_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Não é nada. Eu pareço[n]ainda ... eu mesmo.[n][w][e]
[s][vp 8 2 1 0 30 0]Ei, você acha que é possível mudar o coração de[n]alguém?[n][w][e]

[msg MSG_HOMELESS_DAY_010_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Não, eu estou bem. Acho que ainda sou... eu mesmo.[n][w][e]
[s][vp 8 2 1 0 30 0]Os Phantom Thieves despertam[n]corações? Eu gostaria que eles fizessem isso[n]com o coração de ... você sabe quem.[n][w][e]

[msg MSG_HOMELESS_DAY_010_4_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Vou tentar convencê-lo a[n]escrever outra carta.[n]Melhor do que não fazer nada...[n][w][e]

[msg MSG_HOMELESS_NIGHT_010_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Aquele cara deixou outra[n]carta em nosso bolso? Eu nunca[n]mudarei de ideia. Ele pode esquecer.[n][w][e]

[sel SEL_HOMELESS_NIGHT_010_0 top]
[s]Uma letra?[e]
[s]"Aquele cara"? O que você quer dizer?[e]

[msg MSG_HOMELESS_NIGHT_010_1 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Você estava ouvindo, hein? Esteja ciente de que[n]se você enfiar o nariz onde não precisa,[n]você pode se machucar.[n][w][e]
[s][vp 8 2 1 0 30 0]Você sabe, cartas e notas escritas[n]são muito úteis. Queimaduras e[n]julgamentos desaparecem.[n][w][e]
[s][vp 8 2 1 0 30 0]A Internet deixa um rastro[n]Na minha indústria você tem que[n]usar papel.[n][w][e]
[s][vp 8 2 1 0 30 0]Eh, mesmo Medjed nunca descobrirá o que está[n]escrito aqui. Haha![n][w][e]

[msg MSG_HOMELESS_NIGHT_010_2 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Você estava ouvindo, hein? Smamma[n]se você não quer se machucar.[n][w][e]
[s][vp 8 2 1 0 30 0]Quanto mais você se agita e resiste,[n]mais você sofre, sabia?[n][w][e]
[s][vp 8 2 1 0 30 0]Mesmo que seja sempre mais engraçado[n]para mim quando é[n]o outro que fica animado... Eheheh.[n][w][e]

[msg MSG_HOMELESS_DAY_011_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]*suspiro* Você precisa de alguma coisa, jovem?[n][w][e]

[sel SEL_HOMELESS_DAY_011_0_0 top]
[s]Como você está?[e]
[s]Algo está te preocupando?[e]

[msg MSG_HOMELESS_DAY_011_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Onde quer que eu vá, ouço sobre os Phantom[n]Thieves. Eles os chamam de heróis contemporâneos.[n][w][e]
[s][vp 8 2 1 0 30 0]Se eu pedisse aos Phantom Thieves[n]para me ajudar, talvez eles ajudassem[n]a clarear minha cabeça. *suspira*[n][w][e]

[msg MSG_HOMELESS_DAY_011_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Algo parecido. Talvez eu devesse[n]perguntar aos Fan Thieves...[n][w][e]
[s][vp 8 2 1 0 30 0]Oh, esqueça.[n]Não é nada. Esqueça o que eu disse.[n][w][e]

[msg MSG_HOMELESS_DAY_011_3_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Encontrei em minhas roupas[n]dinheiro e uma faca manchada[n]de sangue. E mais de uma vez...[n][w][e]
[s][vp 8 2 1 0 30 0]Os períodos que não consigo lembrar[n]são sempre mais longos.[n]Ninguém entende meu problema...[n][w][e]

[msg MSG_HOMELESS_NIGHT_011_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]No momento estou de bom humor.[n]Se você quiser conversar,[n]eu vou acompanhá-lo.[n][w][e]

[sel SEL_HOMELESS_NIGHT_011_0 top]
[s]Eu não sei o que falar.[e]
[s]Aconteceu alguma coisa?[e]

[msg MSG_HOMELESS_NIGHT_011_1 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Sim, graças à confusão[n]feita pelos Phantom Thieves.[n]Vamos torcer para que continuem assim.[n][w][e]
[s][vp 8 2 1 0 30 0]Quando a polícia se concentra[n]neles, a vida fica mais fácil para mim.[n]Brincadeirinha. Hehehe.[n][w][e]

[msg MSG_HOMELESS_NIGHT_011_2 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Aquele? Então pare de me incomodar[n]e vá embora. Xô[n][w][e]
[s][vp 8 2 1 0 30 0]Por que você não pede para a mamãe[n]comprar fantoches para você[n]Phantom Thieves, garoto?[n][w][e]

[msg MSG_HOMELESS_NIGHT_011_3 [Morador de rua]]
[s][vp 8 2 1 0 30 0]O trabalho está indo bem.[n]Você também quer me contratar[n]para algum trabalho?[n][w][e]
[s][vp 8 2 1 0 30 0]Deixe as informações e o dinheiro[n]no lixo. Desaparecimentos, acidentes,[n]o que você quiser.[n][w][e]
[s][vp 8 2 1 0 30 0]Eu não deixo a menor evidência,[n]assim como[n]os Phantom Thieves fazem! Haha![n][w][e]

[msg MSG_HOMELESS_DAY_012_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]E-eu quero conhecer os Thieves[n]Phantom. Eu quero que eles mudem o[n]coração de alguém...[n][w][e]

[sel SEL_HOMELESS_DAY_012_0_0 top]
[s]Coração de quem?[e]
[s]Me deixe fazê-lo.[e]

[msg MSG_HOMELESS_DAY_012_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]É uma pergunta que...[n]eu gostaria de me fazer.[n][w][e]
[s][vp 8 2 1 0 30 0]Talvez eu encontrasse essa pessoa[n]se esperasse na[n]Okumura Foods?[n][w][e]

[msg MSG_HOMELESS_DAY_012_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Haha, agradeço a ideia.[n]Você parece um daqueles[n]heróis, os Phantom Thieves.[n][w][e]
[s][vp 8 2 1 0 30 0]Mas... eu nem sei quem[n]estou mirando...[n]Desculpe, eu estava pensando em voz alta.[n][w][e]

[msg MSG_HOMELESS_NIGHT_012_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]O que você quer? Tenho muito tempo,[n]então, se precisar de alguma coisa,[n]posso ouvi-lo.[n][w][e]

[sel SEL_HOMELESS_NIGHT_012_0 top]
[s]É chato para você?[e]
[s]Deixa para lá.[e]

[msg MSG_HOMELESS_NIGHT_012_1 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Sim, agora tenho muito mais tempo.[n]Devagar, consegui ficar[n]acordado mais tempo.[n][w][e]
[s][vp 8 2 1 0 30 0]Em breve estarei livre.[n]O coração daquele que me comanda[n]está enfraquecendo.[n][w][e]
[s][vp 8 2 1 0 30 0]De quem estou falando?[n]Alguém muito próximo! Haha![n][w][e]

[msg MSG_HOMELESS_NIGHT_012_2 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Vamos, não faça isso. Olha,[n]tantas[n]coisas interessantes estão acontecendo. Por exemplo...[n][w][e]
[s][vp 8 2 1 0 30 0]Você ouviu sobre a Carta de Aviso[n]para aquele bastardo pomposo? Finalmente[n]os Phantom Thieves notaram.[n][w][e]
[s][vp 8 2 1 0 30 0]Eles punem os ímpios a quem a lei não pode tocar.[n]Eles são como eu, hahaha![n][w][e]

[msg MSG_HOMELESS_DAY_013_0_0 [Morador de rua]]
[s][vp 8 2 65535 0 0 0]......[n][w][e]

[sel SEL_HOMELESS_DAY_013_0_0 top]
[s]Você está bem?[e]
[s]Tu estás doente?[e]

[msg MSG_HOMELESS_DAY_013_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Huh? Oh...[n]Você precisa de alguma coisa?[n][w][e]
[s][vp 8 2 1 0 30 0]Não tenho estado muito lúcido ultimamente.[n]Receio que isso possa levar[n]a vantagem se eu dormir...[n][w][e]

[msg MSG_HOMELESS_DAY_013_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Doente? Doente, né...[n][w][e]
[s][vp 8 2 1 0 30 0]Talvez seja disso que as pessoas falam. Eles[n]dizem que você perde a cabeça...[n][w][e]
[s][vp 8 2 1 0 30 0]Não parece tão ruim.[n]Apenas deixe[n]o outro cara desaparecer também...[n][w][e]

[msg MSG_HOMELESS_NIGHT_013_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Eheheh, que noite linda.[n]Eu tenho que aproveitar[n]essa liberdade ao máximo...[n][w][e]
[s][vp 8 2 1 0 30 0]E você?[n]Você também está curtindo a vida?[n][w][e]

[sel SEL_HOMELESS_NIGHT_013_0 top]
[s]Mais ou menos.[e]
[s]Sim definitivamente.[e]
[s]O mundo é uma merda.[e]

[msg MSG_HOMELESS_NIGHT_013_1 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Mais ou menos? Ah, que mediocridade.[n]O mundo inteiro é um jogo[n]e nós somos jogadores ou peões.[n][w][e]
[s][vp 8 2 1 0 30 0]Você é um jogador ou um[n]peão manipulado por alguém?[n]Pense nisso.[n][w][e]

[msg MSG_HOMELESS_NIGHT_013_2 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Esse sorriso diz tudo. Você entende. A vida é[n]apenas um jogo e você sabe jogar.[n][w][e]
[s][vp 8 2 1 0 30 0]Se você se cansar da[n]vida honesta, posso ensiná-lo[n]como se divertir mais.[n][w][e]

[msg MSG_HOMELESS_NIGHT_013_3 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Quer saber?[n]Você está certo.[n]É realmente uma merda.[n][w][e]
[s][vp 8 2 1 0 30 0]Enxames de adultos corruptos[n]Em volta como moscas.[n]E eu sou o mata-moscas.[n][w][e]

[msg MSG_HOMELESS_DAY_014_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Se eu soubesse o nome dele,[n]poderia ter pedido ajuda aos Phantom Thieves[n]antes![n][w][e]
[s][vp 8 2 1 0 30 0]Por mais que tente, não consigo me lembrar. Por[n]aqui ninguém conhece meu passado. O que eu faço?[n][w][e]
[s][vp 8 2 1 0 30 0]Talvez ele... saiba? Mas para mim[n]é impossível conhecê-lo...[n][w][e]
[s][vp 8 2 1 0 30 0]Alguém...[n]Alguém me ajude, por favor...[n][w][e]

[msg MSG_HOMELESS_NIGHT_014_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 3 10 0 10]Merda! Aquele bastardo...[n]Por que ele fez[n]nosso corpo assim?!?[n][w][e]
[s][vp 8 2 1 0 30 0]Ele queria me impedir com suicídio ou algo assim?[n]Eh, parece que ele não tem coragem.[n][w][e]
[s][vp 8 2 1 0 30 0]Isso não importa. Aquele cara vai desaparecer[n]logo, então nesse corpo[n]estarei apenas eu. Hehehe.[n][w][e]

[msg MSG_HOMELESS_DAY_015_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Nome... Meu nome...[n][w][e]
[s][vp 8 2 1 0 30 0]Perguntei à polícia e ao homem[n]de preto outro dia,[n]mas ninguém sabe...[n][w][e]
[s][vp 8 2 1 0 30 0]Alguém me diga,[n]por favor. O que...[n]Qual é o meu nome...?[n][w][e]

[msg MSG_HOMELESS_NIGHT_015_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 0 10]Eu não disse para você não falar[n]durante o dia? Se precisar de mim,[n]deixe uma carta no lixo.[n][w][e]

[msg MSG_HOMELESS_NIGHT_015_1 [Agente de terno]]
[s][vp 8 2 1 0 31 0][f 4 23 1 31 5 10 4 10]Sinto muito, mas tive que verificar[n]que o ex-mercenário "Yohei[n]Kiritani" perdeu a memória.[n][w][e]

[msg MSG_HOMELESS_NIGHT_015_2 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Nunca diga esse nome amaldiçoado! Você quer que[n]eu me livre de você também?!?[n][w][e]

[msg MSG_HOMELESS_NIGHT_015_3 [Agente de terno]]
[s][vp 8 2 1 0 31 0]C-claro que não.[n]Eu estaria condenado se ele[n]me visse...[n][w][e]

[msg MSG_quest29_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Eu diria que temos nosso[n]objetivo. Hora de discutir[n]um plano no Esconderijo![n][w][e]

[msg MSG_YOKOKUJYOU_GET_HIRU [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Yohei Kiritani?[n]Yohei... Há algo sobre[n]esse nome que...[n][w][e]
[s][vp 8 2 1 0 30 0]Esse é... meu nome?!?[n]Então significa que[n]os Phantom Thieves...?[n][w][e]

[msg MSG_YOKOKUJYOU_GET_YORU [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 0 10]Merda, como eles descobriram[n]meu nome?[n][w][e]
[s][vp 8 2 1 0 30 0]Eles vão tentar me cancelar?[n]Deixe-os tentar.[n]Vou cancelá-los...[n][w][e]

[msg MSG_HOMELESS_DAY_016_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Agora eu me lembro de tudo...Tudo[n]que eu fiz.[n]Aaah...que dor de cabeça...[n][w][e]

[sel SEL_HOMELESS_DAY_016_0_0 top]
[s]Você está bem?[e]
[s]Vá ao hospital.[e]

[msg MSG_HOMELESS_DAY_016_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Sim, obrigado. Eu me senti[n]mal quando as memórias[n]começaram a vir à tona.[n][w][e]

[msg MSG_HOMELESS_DAY_016_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Obrigado pelo pensamento, mas...[n]eu não mereço ser[n]tratado em um hospital.[n][w][e]

[msg MSG_HOMELESS_DAY_016_3_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Eu fiz coisas terríveis para[n]muitas pessoas por[n]pouco salário.[n][w][e]
[s][vp 8 2 1 0 30 0]Os Phantom Thieves me salvaram?[n]Não pode ser. Eles são...[n][w][e]

[msg MSG_HOMELESS_DAY_017_0_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ei, há[n]algumas coisas no seu passado que...[n]gostaria que você pudesse apagar?[n][w][e]

[sel SEL_HOMELESS_DAY_017_0_0 top]
[s]É claro.[e]
[s]Não.[e]
[s]E você?[e]

[msg MSG_HOMELESS_DAY_017_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ainda há tempo.[n]Conserte essas coisas[n]de uma vez por todas.[n][w][e]

[msg MSG_HOMELESS_DAY_017_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Entendi. Deixar. Mas no futuro[n]você pode entender que cometeu[n]erros ou se arrepender de algo.[n][w][e]

[msg MSG_HOMELESS_DAY_017_3_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Sim, eu gostaria de poder esquecer certas coisas.[n]Eu pensei que os excluiu, mas eu estava errado.[n][w][e]

[msg MSG_HOMELESS_DAY_017_4_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0]Eu decidi enfrentar[n]meus crimes. Os Phantom Thieves[n]me salvaram.[n][w][e]
[s][vp 8 2 1 0 30 0]É por isso que estou feliz[n]por eles estarem vivos.[n]A notícia me deixou feliz.[n][w][e]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Você ainda é jovem. Viva[n]sua vida ao máximo, ou[n]você terá arrependimentos como eu.[n][w][e]

[msg MSG_HOMELESS_DAY_018_0_0 [Morador de rua]]
[s][vp 8 2 1 0 65535 0]Ei, você não acha que há algo...[n]estranho nessa cidade?[n][w][e]
[s][vp 8 2 1 0 65535 0]De repente, eles parecem[n]todos tão felizes.[n][w][e]
[s][vp 8 2 1 0 65535 0]O que diabos está acontecendo?[n]É quase assustador...[n][w][e]

[msg MSG_HOMELESS_DAY_019_0_0 [Morador de rua]]
[s][vp 8 2 1 0 65535 0]Superficialmente, não parece haver[n]nada de bom na[n]vida sem-teto.[n][w][e]
[s][vp 8 2 1 0 65535 0]Mas a liberdade torna[n]muito divertido.[n][w][e]

[sel SEL_HOMELESS_DAY_019_0_0 top]
[s]Você não se lembra mais?[e]
[s]O que aconteceu?[e]
[s]Tem certeza?[e]

[msg MSG_HOMELESS_DAY_019_1_0 [Morador de rua]]
[s][vp 8 2 1 0 65535 0]Não, não me lembro de nada.[n]Absolutamente nada do passado.[n][w][e]
[s][vp 8 2 1 0 65535 0]Mas... o que aconteceu[n]no passado não importa,[n]certo? Hahaha...[n][w][e]

[msg MSG_HOMELESS_DAY_019_2_0 [Morador de rua]]
[s][vp 8 2 1 0 65535 0]Eu gostaria de perguntar a você a mesma coisa.[n]Nós nos conhecemos?[n][w][e]
[s][vp 8 2 1 0 65535 0]...Quero dizer, não me lembro de nada sobre[n]meu passado. Hahaha![n][w][e]

[msg MSG_HOMELESS_DAY_019_3_0 [Morador de rua]]
[s][vp 8 2 1 0 65535 0]Sim, é bom não ter que se preocupar com nada. Não[n]me lembro do passado, mas é por isso que me[n]sinto livre![n][w][e]
[s][vp 8 2 1 0 65535 0]É a demonstração de que para viver não é preciso[n]passado. Você concorda comigo? Hahaha![n][w][e]

[msg MSG_HOMELESS_DAY_020_0_0 [Morador de rua]]
[s][vp 8 2 1 0 65535 0]Você não me parece feliz.[n][w][e]
[s][vp 8 2 1 0 65535 0]Na cidade sempre encontro alguém[n]com essa expressão, vagando[n]num mar de gente feliz.[n][w][e]
[s][vp 8 2 1 0 65535 0]Mas com o que[n]todos vocês estão se preocupando?[n][w][e]
[s][vp 8 2 1 0 65535 0]Seria melhor se você esquecesse as[n]coisas negativas e vivesse como eu...[n][w][e]

[msg MSG_HOMELESS_DAY_021_0_0 [Morador de rua]]
[s][vp 8 2 1 0 65535 0]As coisas estão mudando.[n]Estou um pouco triste com a ideia de[n]ir embora.[n][w][e]

[sel SEL_HOMELESS_DAY_021_0_0 top]
[s]Onde você irá?[e]
[s]Espero ver-te de novo.[e]

[msg MSG_HOMELESS_DAY_021_1_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Não posso expiar meus pecados pendurados por[n]aqui. Vou encontrar um emprego em um lugar[n]tranquilo.[n][w][e]

[msg MSG_HOMELESS_DAY_021_2_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]É bom ter alguém[n]se despedindo.[n]Obrigado. Significa muito para mim.[n][w][e]

[msg MSG_HOMELESS_DAY_021_3_0 [Morador de rua]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Já que sou tão tolo, não sei se poderei expiar[n]meus pecados.[n][w][e]
[s][vp 8 2 1 0 30 0]No entanto, continuarei a pensar em uma[n]maneira de fazer isso. Adeus, jovem.[n][w][e]
[s][vp 8 2 1 0 30 0]Espero vê-lo novamente...[n]Se eu puder me tornar[n]uma pessoa respeitável.[n][w][e]

[msg MSG_Q83_HINT_HOMELESS_00 [Morador de rua]]
[s][vp 1 0 0 0 0 0]Hum? Você precisa de algo?[n][w][e]
[s][vp 1 0 0 0 0 0]Combinação de resultados para[n]apostas esportivas? Sim... Já ouvi falar.[n][w][e]
[s][vp 8 2 1 0 65535 0]Parece que eles são administrados por[n]uma organização que frequentemente faz[n]negócios com máfias estrangeiras.[n][w][e]
[s][vp 1 0 0 0 0 0]Ouvi dizer que eles não[n]se importam em ameaçar os jogadores,[n]especialmente as meninas.[n][w][e]

[sel SEL_Q83_HINT_HOMELESS_01 top]
[s]Por exemplo?[e]
[s]Ameaças?[e]

[msg MSG_Q83_HINT_HOMELESS_02 [Morador de rua]]
[s][vp 1 0 0 0 0 0]Eles os ameaçam de morte em caso de derrota,[n]embora eu duvide que eles realmente os matem.[n][w][e]
[s][vp 1 0 0 0 0 0]Como é uma partida fixa,[n]eles não podem ir à polícia.[n]Eles têm que seguir suas regras.[n][w][e]

[msg MSG_CHK_Q83_HINT_HOMELES]
[s][vp 1 0 0 0 0 0]クエスト83 ヒントNPC[n]全部ヒント手に入れた[n][w][e]

[msg MSG_CHK_Q83_HINT_HOMELES_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Parece que temos informações suficientes! Vamos[n]voltar ao esconderijo e falar sobre o plano![n][w][e]

[msg MSG_BACKGROUND_EKIIN_001 [Oficial da estação serial]]
[s][vp 8 2 1 0 17 0]Para a Linha Inogami, saia[n]no lado oposto[n]e continue.[n][w][e]
[s][vp 8 2 1 0 17 0]Para as linhas JL e Ginza,[n]saia deste lado[n]e siga para a saída número 8.[n][w][e]

