[msg TEST_MES]
[s]テスト[n][w][e]

[msg MEME_GREETING_mes01]
[s][vp 8 2 1 56704 65535 0]Oh senhor! Aqui.[n][f 1 2 60][e]

[msg MSG_GOODBY_JOZE [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0]Espero te ver em breve![n][w][e]

[msg MSG_MENTION_OF_FLOWER_VA [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][vp 8 2 1 56791 65535 0]Oh sim! Eu gostaria de te dizer algo[n]sobre essas flores que você está[n]colhendo...[n][w][e]
[s][f 4 10 65535 0 0]Por alguma razão, você não pode[n]tirá-los com você para fora do Mementos.[n]Eles simplesmente desaparecem. É bizarro.[n][w][e]
[s][f 4 10 65535 0 0]E seria triste recolhê-los para[n]então vê-los desaparecer... Um verdadeiro[n]desperdício, não é?[n][w][e]
[s][f 4 10 65535 0 0]Não se esqueça de trazê-los para mim antes de[n]sair do Mementos, ok?[n][w][e]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][vp 8 2 1 56706 65535 0]É assim que deve ser. Bom trabalho![n][w][e]

[msg MSG_MENTION_OF_FLOWER_VA_2 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0]Quando você coletar flores suficientes, venha até[n]mim e troque-as antes de deixar os Mementos, ok?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 56706 65535 0]É assim que deve ser. Bom trabalho![n][w][e]

[msg e489_230_jose01 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56777 65535 0]Ah sim. Antes que eu esqueça...[n][w][e]

[msg e489_230_jose02 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lembra quando eu disse que[n]crio um jogo divertido[n]para jogar nos Mementos?[n][w][e]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56766 65535 0]Veio até mim olhando para o[n]metrô no outro mundo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Isso também mostrará que você[n]procurou flores em todos os lugares.[n][w][e]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Os selos oferecem recompensas diferentes[n]do que flores: colecione[n]ambos como o inferno![n][w][e]

[msg e489_230_jose03 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56793 65535 0]Então, você tem flores para mim?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se sim, troque-os comigo! Eu tenho alguns[n]ótimos artigos.[n][w][e]

[msg MEMENTOS_awakening_seed_]
[s]José assiste[n]meu [f 2 5 3 9999 0]...[n][w][e]

[msg MEMENTOS_awakening_seed__2 [Jose]]
[s][bup 0 221 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56784 65535 0]Oh, que força...[n]eu os vi em meus estudos![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eles são o subproduto acumulado[n]de cognições distorcidas.[n][w][e]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No entanto, isso ainda não atingiu seu potencial[n]máximo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56793 65535 0]Eu posso ver isso? Eu não vou quebrá-lo.[n]Prometo.[n][w][e]

[msg MEMENTOS_awakening_seed__3 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se eu fizer isso...[n][f 1 2 53][e]

[msg MEMENTOS_awakening_seed__4 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E eu coloquei isso lá...[n][f 1 2 80][e]

[msg MEMENTOS_awakening_seed__5 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56782 65535 0]...Perfeito![n][w][e]

[msg MEMENTOS_awakening_seed__6 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Feito. Deve[n]vir a calhar agora.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56766 65535 0]Aqui, senhor.[n][w][e]

[msg MEMENTOS_awakening_seed__7 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se você encontrar mais algum,[n]avise-me, ok?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entender cognições distorcidas também me ajuda a[n]entender melhor os humanos.[n][w][e]

[msg MEMENTOS_awakening_seed__8]
[s]José assiste[n]o [f 2 5 3 9999 0]...[n][w][e]

[msg MEMENTOS_awakening_seed__9 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56703 65535 0]Ei senhor. Isso é um[n]cristal?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Deixe-me ver![n][w][e]

[msg MEMENTOS_awakening_seed__10 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se eu fizer isso...[n][f 1 2 53][e]

[msg MEMENTOS_awakening_seed__11 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E eu coloquei isso lá...[n][f 1 2 80][e]

[msg MEMENTOS_awakening_seed__12 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56782 65535 0]...Perfeito![n][w][e]

[msg MEMENTOS_awakening_seed__13 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Feito. Deve[n]vir a calhar agora.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56766 65535 0]Aqui, senhor.[n][w][e]

[msg MEMENTOS_awakening_seed__14 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se você encontrar mais algum,[n]avise-me, ok?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entender cognições distorcidas também me ajuda a[n]entender melhor os humanos.[n][w][e]

[msg MEMENTOS_refuse_awakenin [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56704 65535 0]Oh senhor. Você parece ter[n]algo interessante.[n][w][e]

[msg MEMENTOS_refuse_awakenin_2]
[s]José assiste[n]meu [f 2 5 3 9999 0]...[n][w][e]

[msg MEMENTOS_refuse_awakenin_3 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56792 65535 0]Posso dar uma olhada mais de perto[n]esse cristal?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Acho que me faria muito bem.[n]Posso, por favor?[n][w][e]

[msg MEMENTOS_refuse_awakenin_4 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm... Ok... Entendo...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Então, aqui vai assim...[n]enquanto aqui vai assim, e...[n][w][e]

[msg MEMENTOS_refuse_awakenin_5 [Jose]]
[s][bup 0 221 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56756 65535 0]Huh? Oh... Parece que ainda[n]não está funcionando.[n][w][e]

[msg MEMENTOS_refuse_awakenin_6 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aqui, senhor. Obrigado por[n]mostrá-lo para mim.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56794 65535 0]A distorção dentro desse[n]cristal ainda está conectada a uma[n]distorção em algum outro lugar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Enquanto ela permanecer conectada àquele[n]lugar, o cristal não pode[n]alcançar todo o seu potencial.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você poderia me mostrar novamente depois de se[n]livrar deste lugar?[n][w][e]

[msg MEMENTOS_refuse_awakenin_7 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56766 65535 0]Aposto que posso transformá-lo[n]em algo lindo![n][w][e]

[msg JOZE_BEFORE_BTL_1st_01 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Ei, ótimo trabalho.[n][w][e]

[msg JOZE_BEFORE_BTL_1st_02 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Parece que esta área foi[n]formada recentemente.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Ainda não sei muito sobre[n]este lugar, então acho que vou[n]beber mais algumas flores.[n][w][e]

[msg JOZE_BEFORE_BTL_1st_03 [Jose]]
[s][bup 0 221 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]Aaah![n][w][e]

[msg JOZE_BEFORE_BTL_1st_04 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Mmh, o gosto tem algo de...[n][w][e]

[msg JOZE_BEFORE_BTL_1st_05 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]Não, estou aqui para meus estudos.[n][w][e]

[msg JOZE_BEFORE_BTL_2nd_01 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Ei, ótimo trabalho.[n][w][e]

[msg JOZE_BEFORE_BTL_2nd_02 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Não é exatamente o gosto[n]que me disseram...[n][w][e]

[sel JOZE_BEFORE_BTL_2nd_SEL0 top]
[s]Quê?[e]
[s]Não é bom?[e]

[msg JOZE_BEFORE_BTL_2nd_03 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]sabe de...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]Hmmm.[n][w][e]

[msg JOZE_BEFORE_BTL_2nd_04 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Aprendi que o sentido do[n]gosto muda conforme a[n]idade cresce.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]Será verdade? Isto aconteceu-lhe?[n][w][e]

[sel JOZE_BEFORE_BTL_2nd_SEL0_2 top]
[s]Todos são diferentes.[e]
[s]Com o que você se importa?[e]

[msg JOZE_BEFORE_BTL_2nd_05 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 7 0 0]Entendo... Não é verdade para todo mundo,[n]eh?[n][w][e]

[msg JOZE_BEFORE_BTL_2nd_06 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 8 0 0]Nós iremos...[n][w][e]

[msg JOZE_BEFORE_BTL_2nd_07 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 9 0 0]Eu simplesmente não consigo gostar de flores aqui.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 10 0 0]Mas uma vez eu era louco por isso...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 11 0 0]Se meus estudos forem[n]bem-sucedidos, então...[n][w][e]

[msg JOZE_BEFORE_BTL_2nd_08 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 12 0 0]Espere um minuto... Preciso me concentrar.[n][w][e]

[msg JOZE_BEFORE_BTL_3rd_01 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Ei, ótimo trabalho.[n][w][e]

[msg JOZE_BEFORE_BTL_3rd_02 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Lembra quando eu disse que não gosto das flores[n]daqui?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Bem, acho que entendo o porquê.[n][w][e]

[sel JOZE_BEFORE_BTL_3rd_SEL0 top]
[s]Me esclareça.[e]
[s]E aí?[e]

[msg JOZE_BEFORE_BTL_3rd_03 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]As flores aqui têm gosto[n]elétrico. Eu não[n]gosto deles.[n][w][e]

[msg JOZE_BEFORE_BTL_3rd_04 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Já que essas flores são...[n]Mmh, como colocar isso na linguagem do mundo[n]real...[n][w][e]

[msg JOZE_BEFORE_BTL_3rd_05 [Jose]]
[s][bup 0 221 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]Ah, bem... eu sou o conhecimento de[n]one's self, que todo mundo tem[n]dentro.[n][w][e]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 7 0 0]Quando o sabor é tão elétrico,[n]isso significa que o eu não tem[n]certo conhecimento de si mesmo.[n][w][e]

[msg JOZE_BEFORE_BTL_3rd_06 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 8 0 0]As pessoas realmente não podem ter[n]consciência de si mesmas?[n]Todas elas são assim?[n][w][e]

[msg JOZE_BEFORE_BTL_3rd_07 [Jose]]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 9 0 0]Não entendi. Não é nada como[n]eles me ensinaram ...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 10 0 0]Mas ainda não posso abandonar meus estudos.[n][w][e]

[msg MEME_STAMP_GREET_00 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56703 65535 0]Muito bem, senhor! A exploração[n]correu bem?[n][w][e]

[msg MEME_STAMP_GREET_01 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56706 65535 0]Ei, muito bem... você tem flores para mim?[n]E vejo que sua coleção de selos[n]está indo bem![n][w][e]

[msg MEME_STAMP_GREET_02 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ei, muito bem... você tem flores para mim?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56766 65535 0]É bom ver que você também está progredindo[n]com os selos![n][w][e]

[msg MEME_STAMP_GREET_03 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56706 65535 0]Bom trabalho. Agora você tem[n]muitos selos![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quanto mais selos você coletar, mais coisas[n]você pode fazer em Mementos,[n]então continue assim![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh! E não se esqueça de me trazer[n]mais flores Mementos, ok?[n][w][e]

[msg MEME_STAMP_GREET_04 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56706 65535 0]Bom trabalho! Eu estava ansioso para vê-lo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sempre que nos cruzamos,[n]estou sempre curioso para saber[n]quantos selos e flores você coletou.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56771 65535 0]Uau, agora você tem tantos![n]Acho que já passou da metade do caminho![n]Continue assim.[n][w][e]

[msg MEME_STAMP_GREET_05 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bom trabalho. Eu senti que você[n]iria passar em breve.[n][w][e]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56786 65535 0]Você me trouxe alguma flor?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você também tem toneladas de selos![n]Você quer tentar mudar[n]sua compreensão dos Mementos?[n][w][e]

[msg MEME_STAMP_GREET_06 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56701 65535 0]Muito bem, senhor! Acho que[n]agora faltam poucos[n]selos...[n][w][e]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56766 65535 0]Fico feliz que você esteja gostando tanto do[n]jogo... Valeu a pena colocar esses quiosques.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mas agora falta MUITO POUCO para[n]terminar o jogo... continue assim![n][w][e]

[msg MEME_STAMP_GREET_MAX [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56785 65535 0]Bom trabalho! Coletou[n]todos os selos. Parabéns![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E com isso, o jogo acabou.[n]Eu agradeceria, porém, se[n]você continuasse a me trazer flores.[n][w][e]
[s][bup 0 221 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uhm... Você não vai parar de me visitar agora,[n]vai, senhor?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56799 65535 0]Espero te ver em breve.[n][w][e]

[msg MEME_GREETING_AFTER_3RD_ [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56731 65535 0]Oh, desculpe. Quer trocar flores[n]ou mudar a cognição[n]nos Mementos?[n][w][e]

[msg MEME_GREETING_NEW_LINEUP [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56706 65535 0]Ótimo trabalho, senhor.[n][w][e]

[msg MEME_GREETING_2ND_ACCESS [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56701 65535 0]Bom ver você de novo. Você[n]me trouxe mais flores?[n][w][e]

[msg MEME_SEED_ADDED_FIRST_01 [Jose]]
[s][bup 0 221 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, certo...[n][w][e]

[msg MEME_SEED_ADDED_FIRST_02 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56793 65535 0]Com relação aos subprodutos de[n]cognições distorcidas... as "Sementes[n]da luxúria"...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eu queria conhecer melhor vocês humanos,[n]então fui procurar por[n]um e, vejam só! Encontrei![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quem sabe o que ele estava fazendo abandonado[n]aqui...? Terá travamento[n]de um lugar completamente diferente?[n][w][e]

[msg MEME_SEED_ADDED_FIRST_03 [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Você parece estar coletando[n]estes, senhor. Você pode ficar com[n]se me der algumas flores.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Embora isso pareça mais[n]raro do que os outros, então[n]vai custar um pouco mais caro.[n][w][e]

[msg MEME_NEW_LINEUP_FIRST_01 [Jose]]
[s][bup 0 221 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56777 65535 0]Oh, certo.[n][w][e]

[msg MEME_NEW_LINEUP_FIRST_02 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uma nova área[n]Mementos foi aberta, então coletei[n]novas coisas para negociar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espero ter algo que você goste, senhor.[n][w][e]

[msg MEME_NEW_LINEUP_GENERAL_ [Jose]]
[s][bup 0 221 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 56777 65535 0]Oh, certo.[n][w][e]

[msg MEME_NEW_LINEUP_GENERAL__2 [Jose]]
[s][bup 0 221 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Consegui alcançar uma[n]nova área, então coletei[n]algumas coisinhas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se você quiser trocar as flores que[n]encontrou por esta mercadoria,[n]eu ficaria muito feliz![n][w][e]

