[sel YESNO_SEL top]
[s]Sim [e]
[s]Não [e]

[msg NPC_GREETING_MSG]
[s]Saudações [n][w][e]

[msg MSG_LastGreeting [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0][vp 8 2 1 57701 65535 0]Oh...?[n][w][e]
[s][f 4 25 1 0 0 0]Você está parecendo muito bonito lá, jovem.[n][w][e]
[s][f 4 25 1 0 0 0][vp 8 2 1 57743 65535 0]Volte a este bar quando você se tornar um[n]adulto. Vou quebrar algumas das minhas[n]melhores bebidas para você.[n][w][e]

[msg MSG_LastGreeting_0 [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0][vp 8 2 1 57701 65535 0]Oh...?[n][w][e]
[s][f 4 25 1 0 0 0]... Há um fogo em seus olhos agora, garoto.[n]Eu tenho que dizer que combina com você.[n][w][e]
[s][f 4 25 1 0 0 0][vp 8 2 1 57743 65535 0]Volte a este bar quando você se tornar um[n]adulto. Vou quebrar algumas das minhas[n]melhores bebidas para você.[n][w][e]

[msg MSG_LastGreeting_END [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0][vp 8 2 1 57701 65535 0]Volte a este bar quando você se tornar um[n]adulto. Vou quebrar algumas das minhas[n]melhores bebidas para você.[n][w][e]

[msg MSG_MAMA_00 [Lala Escargot]]
[s][f 4 25 1 0 0 0][vp 8 2 1 57739 65535 0]...O que?[n][w][e]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0]Você não sabe que não é educado olhar? Esse[n]tipo de coisa não é incomum por aqui.[n][w][e]

[msg MSG_MAMA_001 [Lala Escargot]]
[s][f 4 25 1 0 0 0][vp 8 2 1 57738 65535 0]Oh? Você está aqui para ver Ichiko-chan?[n][w][e]
[s]Não sei se é uma boa ideia. Ela é bêbada e[n]persistente nisso.[n][w][e]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0]Quando estiver em sua mira, você estará em[n]um passeio difícil.[n][w][e]

[msg MSG_MAMA_002 [Lala Escargot]]
[s][f 4 25 1 0 0 0][vp 8 2 1 57715 65535 0]* suspiro*... já é hora de contratar alguma[n]ajuda extra em torno do lugar...[n][w][e]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0]Ele teria que ser fofo, no entanto. Eu iria[n]querer alguém fácil aos olhos. Ah...[n]Ajuda encantadora é tão difícil de encontrar.[n][w][e]

[msg MSG_MAMA_003 [Lala Escargot]]
[s][f 4 25 1 0 0 0][vp 8 2 1 57729 65535 0]Oh, não se preocupe. Jovens como você não[n]são do meu tipo.[n][w][e]

[msg MSG_MAMA_004 [Lala Escargot]]
[s][f 4 25 1 0 0 0][vp 8 2 1 57730 65535 0]Você pode querer ficar longe de Ichiko-chan[n]por enquanto, garoto. Ela é, uh...[n]Bem, ela é muito martelada.[n][w][e]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0]Quando uma mulher da idade dela fica[n]bêbada... até eu fico preocupado.[n][w][e]

[msg MSG_MAMA_01 [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0][vp 8 2 1 57739 65535 0]Se você continuar chegando a um lugar como[n]este, não será um bom adulto.[n][w][e]
[s][f 4 25 1 0 0 0]Ou você poderia estar interessado em[n]trabalhar noites aqui?[n][w][e]

[sel SEL_MAMA top]
[s]Eu quero trabalhar aqui em meio período.[e]
[s]Eu não estou interessado.[e]

[msg MSG_MAMA_03 [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0][vp 8 2 1 57730 65535 0]E aqui eu pensei que estava fazendo um favor[n]a você...[n][w][e]
[s][f 4 25 1 0 0 0]Você deve estar mais atento à forma como[n]trata as senhoras. Caso contrário, você não[n]se tornará um homem bom.[n][w][e]

[msg MSG_Beit_Test [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0][vp 8 2 1 57725 65535 0]Você pode não perceber, mas você tem[n]potencial, jovem.[n][w][e]
[s]Eu posso te ensinar o básico de como as[n]coisas são executadas aqui. Não se[n]preocupe, você não fará nada ilegal.[n][w][e]

[msg MSG_Beit_1st_Start [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0][vp 8 2 1 57715 65535 0]O que você diz? Você queria fazer algum[n]trabalho para mim hoje?[n][w][e]

[msg MSG_BAR_PARA_NG [Lala Escargot]]
[s][f 4 25 1 0 0 0][vp 8 2 1 57715 65535 0]Hmm... eu gostaria de alguma ajuda, mas...[n][w][e]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0]Você tem potencial, mas ainda é um pouco sem[n]tempero.[n][w][e]
[s][f 4 25 1 0 0 0]Você não está pronto para fazer isso no meu[n]mundo. Volte quando você crescer um pouco.[n][w][e]

[msg MSG_Arbeit_Bar_NG]
[s]Para trabalhar na encruzilhada, você precisa [f 4 11 4][clr 26][f 4 12 4][clr 27]ser estar [clr 2][f 4 13 4 3][clr 27][n]e [f 4 11 2][clr 26][f 4 12 2][clr 27]ser estar [clr 2][f 4 13 2 3][clr 27].[n][w][e]

[msg MSG_MAMA_WorkDay_NG_01 [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0]Oh, você veio aqui para fazer algum trabalho?[n][w][e]
[s][f 4 25 1 0 0 0]Sinto muito. Estamos todos prontos para hoje.[n][w][e]

[msg MSG_MAMA_WorkDay_OK_01 [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0]Oh, você veio aqui para fazer algum trabalho?[n][w][e]

[msg MSG_MAMA_WorkDay_OK_02_0 [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0]Oh, você é um salva-vidas![n]Então, vamos direto a isso.[n][w][e]

[msg MSG_MAMA_WorkDay_OK_02_0_2 [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0]Oh isso é muito ruim.[n]Talvez outra hora.[n][w][e]

[msg MSG_OOYA_DayInfo [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0]Vou deixar Ichiko-chan saber que você estava[n]aqui.[n][w][e]

[msg MSG_ArbeitNG_Lala01 [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0]Oh... você está aqui para o trabalho?[n][w][e]

[msg MSG_ArbeitNG_OOYA [Ohya]]
[s][bup 0 107 0 65535 0][f 4 23 1 215 14 10 13 10][f 4 25 1 0 0 0][f 4 10 65535 0 0][vp 8 2 1 16066 65535 0]Bem, você não é um trabalhador esforçado?[n]Eu acho que já é hora de eu sair de qualquer[n]maneira.[n][w][e]

[msg MSG_ArbeitOK_Lala01 [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0]Oh... você está aqui para o trabalho?[n][w][e]

[msg MSG_ArbeitThink [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0]Então, você queria fazer algum trabalho para[n]mim hoje?[n][w][e]

[msg MSG_ArbeitThink_common [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0]O que você diz? Você queria fazer algum[n]trabalho para mim hoje?[n][w][e]

[msg MSG_ArbeitThink_common_R [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0][vp 8 2 1 57701 65535 0]Oh, você está aqui para o trabalho?[n][w][e]

[msg MSG_ArbeitThink_common_m [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Ajudar os diversos clientes aqui pode[n]melhorar seu [n][f 4 11 4][clr 26][f 4 12 4][clr 27]...![n][w][e]

[msg MND_Bar_ParamEndInfo]
[s]Eu acho que tenho o suficiente [n][f 4 11 4][clr 26][f 4 12 4][clr 27]já...[n][w][e]

[msg MND_Bar_ParamUpInfo]
[s]Eu me sinto como meu [f 4 11 4][clr 26][f 4 12 4][clr 27][n]vai melhorar em breve...[n][w][e]

[sel SEL_Work top]
[s]Eu vou fazer isso.[e]
[s]Vou passar.[e]

[msg MSG_ArbeitOK_Start [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0][vp 8 2 1 57731 65535 0]Tudo bem, continue e mude.[n][w][e]

[msg MSG_ArbeitOK_Cancel [Lala Escargot]]
[s][f 4 23 1 0 3 10 0 0][f 4 25 1 0 0 0][vp 8 2 1 57730 65535 0]Oh sério? Tudo bem, vá para casa então.[n][w][e]

[msg MSG_Sentou_ParamInfo_int [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Talvez você possa melhorar seu [f 4 11 3][clr 26][f 4 12 4][clr 27][n]Trabalhando no bar e ajudando os clientes?[n][w][e]

[msg MND_Sentou_ParamInfo]
[s]Eu sinto que poderia me melhorar de várias[n]maneiras trabalhando aqui...[n][w][e]

[msg MND_Sentou_ParamEndInfo]
[s]Eu acho que tenho o suficiente [n][f 4 11 4][clr 26][f 4 12 4][clr 27]já...[n][w][e]

[msg MND_RankUp_OK_Chishiki]
[s]Eu me sinto como meu [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vai melhorar em breve...[n][w][e]

[msg MND_RankUp_NG_Chishiki]
[s]Eu não acho meu [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vai melhorar ainda...[n][w][e]

[msg MND_INC_PARAMCHK_L_TISIK]
[s]Parece que ainda tenho muito espaço para[n]melhorias...[n][w][e]

[msg MND_INC_PARAMCHK_M_TISIK]
[s]Eu posso sentir algo vindo para mim...[n][w][e]

[msg MND_INC_PARAMCHK_S_TISIK]
[s]Eu acho que estou perto de um avanço com o[n]meu [n][f 4 11 0][clr 26][f 4 12 0][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Miryoku]
[s]Eu me sinto como meu [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vai melhorar em breve...[n][w][e]

[msg MND_RankUp_NG_Miryoku]
[s]Eu não acho meu [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vai melhorar ainda...[n][w][e]

[msg MND_INC_PARAMCHK_L_MIRYO]
[s]Parece que ainda tenho muito espaço para[n]melhorias...[n][w][e]

[msg MND_INC_PARAMCHK_M_MIRYO]
[s]Eu posso sentir algo vindo para mim...[n][w][e]

[msg MND_INC_PARAMCHK_S_MIRYO]
[s]Eu acho que estou perto de um avanço com o[n]meu [n][f 4 11 1][clr 26][f 4 12 1][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Kiyou]
[s]Eu me sinto como meu [f 4 11 2][clr 26][f 4 12 2][clr 27][n]vai melhorar em breve...[n][w][e]

[msg MND_RankUp_NG_Kiyou]
[s]Eu não acho meu [f 4 11 2][clr 26][f 4 12 2][clr 27][n]vai melhorar ainda...[n][w][e]

[msg MND_RankUp_OK_Kiyou_Beef]
[s]Se as coisas correrem bem, acho que meu [n][f 4 11 1][clr 26][f 4 12 1][clr 27]Pode melhorar...[n][w][e]

[msg MND_INC_PARAMCHK_L_KIYOU]
[s]Parece que ainda tenho muito espaço para[n]melhorias...[n][w][e]

[msg MND_INC_PARAMCHK_M_KIYOU]
[s]Eu posso sentir algo vindo para mim...[n][w][e]

[msg MND_INC_PARAMCHK_S_KIYOU]
[s]Eu acho que estou perto de um avanço com o[n]meu [n][f 4 11 2][clr 26][f 4 12 2][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Dokyo]
[s]Eu me sinto como meu [f 4 11 3][clr 26][f 4 12 3][clr 27][n]vão melhorar em breve...[n][w][e]

[msg MND_RankUp_NG_Dokyo]
[s]Eu não acho meu [f 4 11 3][clr 26][f 4 12 3][clr 27][n]vai melhorar ainda...[n][w][e]

[msg MND_INC_PARAMCHK_L_DOKYO]
[s]Parece que ainda tenho muito espaço para[n]melhorias...[n][w][e]

[msg MND_INC_PARAMCHK_M_DOKYO]
[s]Eu posso sentir algo vindo para mim...[n][w][e]

[msg MND_INC_PARAMCHK_S_DOKYO]
[s]Eu acho que estou perto de um avanço com o[n]meu [n][f 4 11 3][clr 26][f 4 12 3][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Yasasisa]
[s]Eu me sinto como meu [f 4 11 4][clr 26][f 4 12 4][clr 27][n]vai melhorar em breve...[n][w][e]

[msg MND_RankUp_NG_Yasasisa]
[s]Eu não acho meu [f 4 11 4][clr 26][f 4 12 4][clr 27][n]vai melhorar ainda...[n][w][e]

[msg MND_RankUp_OK_Yasasisa_F]
[s]Se as coisas correrem bem, acho que meu [n][f 4 11 4][clr 26][f 4 12 4][clr 27]Pode melhorar...[n][w][e]

[msg MND_INC_PARAMCHK_L_YASAS]
[s]Parece que ainda tenho muito espaço para[n]melhorias...[n][w][e]

[msg MND_INC_PARAMCHK_M_YASAS]
[s]Eu posso sentir algo vindo para mim...[n][w][e]

[msg MND_INC_PARAMCHK_S_YASAS]
[s]Eu acho que estou perto de um avanço com o[n]meu [n][f 4 11 4][clr 26][f 4 12 4][clr 27]...[n][w][e]

