[sel YESNO_SEL top]
[s]はい[e]
[s]いいえ[e]

[msg NPC_GREETING_MSG]
[s]Š拶[n][w][e]

[msg NPC_01]
[s]会話[n][w][e]

[msg MSG_NARAIGOTO_001_0_0 [Irritated Mother]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Você vai se atrasar para sua lição, se não[n]se apressar! Agora, pare de falar...![n][w][e]

[msg MSG_NARAIGOTO_001_1_0 [Sad Daughter]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]... Eu não estou morrendo.[n][w][e]
[s][vp 8 2 1 0 11 0]Por que tenho que fazer aulas de piano?[n]Eu não quero me tornar pianista...[n][w][e]

[msg MSG_NARAIGOTO_001_2_0 [Irritated Mother]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Absurdo! Você precisa ser mais sério sobre[n]suas lições! É para o seu futuro, você sabe![n][w][e]

[msg MSG_NARAIGOTO_001_3_0 [Sad Daughter]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]'Kay, te vejo mais tarde...[n][w][e]

[msg MSG_NARAIGOTO_002_0_0 [Timid Daughter]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Mãe, você sabia que os ladrões fantasmas[n]mudam o coração das pessoas?[n][w][e]
[s][vp 8 2 1 0 11 0]Eu me pergunto se isso os faz se tornar[n]pessoas diferentes...[n][w][e]

[msg MSG_NARAIGOTO_002_1_0 [Irritated Mother]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]O suficiente. Se você tem tempo para tais[n]bobagens, terá tempo para aprender uma nova[n]música.[n][w][e]
[s][vp 8 2 1 0 12 0]Não temos muito tempo até a competição! Sem[n]jantar se você não jogar bem![n][w][e]

[msg MSG_NARAIGOTO_002_2_0 [Sad Daughter]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Eu não quero mais fazer isso...[n]Eu gostaria que minha mãe se transformasse[n]em outra pessoa...[n][w][e]

[msg MSG_NARAIGOTO_003_0_0 [Timid Daughter]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Meus amigos me pediram para jogar vôlei no[n]nosso dia de folga.[n][w][e]

[msg MSG_NARAIGOTO_003_1_0 [Irritated Mother]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Você não pode! Como você vai tocar piano se[n]se machucar!?[n][w][e]

[msg MSG_NARAIGOTO_003_2_0 [Timid Daughter]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Então, que tal irmos a algum lugar?[n]Todos os meus amigos estão fazendo viagens[n]com suas famílias...[n][w][e]

[msg MSG_NARAIGOTO_003_3_0 [Irritated Mother]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Você pode ir a qualquer lugar do mundo[n]quando se tornar pianista. Você só precisa[n]continuar praticando.[n][w][e]
[s][vp 8 2 1 0 12 0]Está quase na hora da competição.[n]Você tem que vencer, entende?[n][w][e]

[msg MSG_NARAIGOTO_004_0_0 [Hysterical Mother]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Que desempenho vergonhoso![n]Essa foi a chance de uma vida![n][w][e]
[s][vp 8 2 1 0 12 0]Por que...? Por que você não pode fazer isso?[n]Eu preciso que você se torne um pianista![n][w][e]
[s][vp 8 2 1 0 12 0]É porque você não ensaiou![n]É porque você não me ouve![n][w][e]

[msg MSG_NARAIGOTO_004_1_0 [Daughter About to Cry]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Me desculpe... me desculpe... vou fazer mais[n]lições... *SOB * [n][w][e]

[msg MSG_NARAIGOTO_004_2_0 [Hysterical Mother]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Sou eu quem quer chorar![n]Isto é tudo culpa sua![n][w][e]

[msg MSG_quest30_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Parece que encontramos nosso alvo![n]Vamos discutir isso com o resto do grupo no[n]esconderijo![n][w][e]

[msg MSG_NARAIGOTO_005_0_0 [Crestfallen Mother]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Quando eu era jovem, queria me tornar[n]pianista. Eu trabalhei duro e pratiquei[n]muito, mas...[n][w][e]
[s][vp 8 2 1 0 12 0]Sinto muito por forçar meu sonho em você.[n]Você pode fazer o que quiser a partir de[n]agora.[n][w][e]

[msg MSG_NARAIGOTO_005_1_0 [Kind Daughter]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Não gosto quando você fica bravo, mas gosto[n]do piano, então quero continuar tocando.[n][w][e]
[s][vp 8 2 1 0 11 0]E um dia, vou me tornar um pianista e levar[n]você por todo o mundo.[n][w][e]

[msg MSG_NARAIGOTO_005_2_0 [Crestfallen Mother]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Sinto muito... obrigado.[n]Obrigado...[n][w][e]

[msg MSG_NARAIGOTO_006_0_0 [Kind Mother]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]E você, seu pai e eu fazemos algo juntos no[n]seu dia de folga?[n][w][e]

[msg MSG_NARAIGOTO_006_1_0 [Happy Daughter]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Eu quero fazer compras com você, depois[n]brincar com o pai...[n][w][e]
[s][vp 8 2 1 0 11 0]Ah, e eu quero ir olhar para as partituras[n]também! Eu quero aprender uma nova música![n][w][e]

[msg MSG_NARAIGOTO_006_2_0 [Kind Mother]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]É claro. Ok, tenha cuidado.[n][w][e]

[msg MSG_NARAIGOTO_006_3_0 [Happy Daughter]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Obrigado, mãe! Vou fazer o meu melhor na[n]lição![n][w][e]

[msg MSG_TUMAARASOI_001_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Todos esses acidentes estranhos estão[n]começando a me assustar. Meu marido acabou[n]de ser promovido- não posso morrer.[n][w][e]

[msg MSG_TUMAARASOI_001_1_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Que dia e idade horríveis em que vivemos...[n]Eu só peço que ele mantenha meu marido[n]seguro também.[n][w][e]

[msg MSG_TUMAARASOI_001_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 20 20 0 10][vp 8 2 1 0 19 0]Ohoho, ele ficará bem trabalhando sob meus[n]hubbers- desde que ele puxe seu peso.[n][w][e]
[s][vp 8 2 1 0 19 0]Não pode ter nenhum preguiçoso segurando-o.[n]OHOHO...[n][w][e]

[msg MSG_TUMAARASOI_002_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Seu filho não é um estudante Shujin? Ouvi[n]dizer que é uma escola bastante estrita.[n][w][e]
[s][vp 8 2 1 0 19 0]Deve ser desafiador, o que com tantos rude-[n]ohoho, quero dizer "único"- estudantes lá.[n][w][e]

[msg MSG_TUMAARASOI_002_1_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]É verdade, ele não se sai muito bem na[n]escola. Talvez ele tenha conseguido isso de[n]seu pai. Tem sido difícil.[n][w][e]

[msg MSG_TUMAARASOI_002_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 20 10 0 10][vp 8 2 1 0 19 0]Bem, por trás de todo grande homem há uma[n]ótima mulher, e atrás de cada criança uma[n]ótima mãe. OHOHO...[n][w][e]

[msg MSG_TUMAARASOI_003_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Meu Bub Bub recebeu um convite para a nova[n]exposição de Madarame. Você e sua família[n]cuidariam de participar?[n][w][e]

[msg MSG_TUMAARASOI_003_1_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Oh não. Nenhum de nós seria capaz de contar[n]a boa arte dos maus.[n][w][e]

[msg MSG_TUMAARASOI_003_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 20 10 0 10][vp 8 2 1 0 19 0]Bem, você nunca se tornará mais cultivado se[n]não apreciar as coisas mais refinadas.[n][w][e]

[msg MSG_TUMAARASOI_004_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]O show de Madarame foi simplesmente incrível.[n][w][e]
[s][vp 8 2 1 0 19 0]Isso me deixou totalmente orgulhoso de ser[n]japonês.[n]OHOHO...[n][w][e]

[msg MSG_TUMAARASOI_004_1_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Então foi você que eu vi na TV durante a[n]cobertura de notícias.[n][w][e]

[msg MSG_TUMAARASOI_004_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 20 10 0 10][vp 8 2 1 0 19 0]Oh meu, eu era realmente? Eu não fazia ideia.[n]OHOHO...[n][w][e]

[msg MSG_TUMAARASOI_005_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Que fraude horrível esse Madarame acabou[n]sendo! Ele não deve se importar com ninguém[n]além de si mesmo.[n][w][e]

[msg MSG_TUMAARASOI_005_1_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Plagializante, foi? E de seu próprio aluno,[n]por isso.[n][w][e]

[msg MSG_TUMAARASOI_005_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Você ouve sobre isso- pessoas que passam o[n]trabalho duro de outra pessoa como seu.[n][w][e]

[msg MSG_TUMAARASOI_005_3_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]OHOHO... sim, meu marido estava bastante[n]perturbado com isso também.[n][w][e]

[msg MSG_TUMAARASOI_006_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Eu continuo ouvindo sobre todo esse negócio[n]de chantagem- seus hubs devem ficar de olho.[n][w][e]

[msg MSG_TUMAARASOI_006_1_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Felizmente, seu salário é tão baixo que[n]nunca teremos que nos preocupar com algo[n]assim...[n][w][e]

[msg MSG_TUMAARASOI_006_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Isso é tão corajoso de você. Temos muito[n]medo de nos colocar em risco.[n][w][e]

[msg MSG_TUMAARASOI_006_3_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Suponho que há apenas coisas que uma família[n]rica como a sua nunca poderia entender...[n][w][e]

[msg MSG_TUMAARASOI_007_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Não posso permitir que meu filho seja[n]chantageado![n]Por que a polícia não está fazendo mais[n]sobre isso!?[n][w][e]

[msg MSG_TUMAARASOI_007_1_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Isso deve ter sido aterrorizante. O que[n]aconteceu?[n][w][e]

[msg MSG_TUMAARASOI_007_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Aterrorizante de fato! Felizmente, ele só[n]perdeu uma carteira barata. Não poderia ter[n]custado mais de 100.000 ienes.[n][w][e]

[msg MSG_TUMAARASOI_007_3_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Isso seria inimaginável para nós.[n]Eu não deveria ter esperado nada menos para[n]sua família. OHOHO...[n][w][e]

[msg MSG_TUMAARASOI_008_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Os ladrões fantasmas cuidavam da máfia,[n]certo? Os serve certos para causar minha[n]preciosa dor de menino.[n][w][e]
[s][vp 8 2 1 0 19 0]Eu apoio completamente os ladrões fantasmas[n]agora. Espero que eles tragam mais maçãs[n]ruins para a justiça![n][w][e]

[msg MSG_TUMAARASOI_008_1_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Só posso imaginar o que a polícia está[n]fazendo. Eles não pareciam muito confiáveis.[n][w][e]

[msg MSG_TUMAARASOI_008_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Concordo. Embora, tenho certeza de que eles[n]estão reavaliando como lidam com a[n]prevenção do crime.[n][w][e]

[msg MSG_TUMAARASOI_009_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Você viu aquela coisa medjed? É hora de os[n]ladrões fantasmas trabalharem sua mágica[n]novamente![n][w][e]

[msg MSG_TUMAARASOI_009_1_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Certamente não há nada que possamos fazer.[n]Seria horrível que Medjed estivesse de olho[n]em nossa empresa.[n][w][e]

[msg MSG_TUMAARASOI_009_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Exatamente. Superiores como meu marido são[n]quem precisa intervir se as coisas vão para[n]o sul.[n][w][e]

[msg MSG_TUMAARASOI_009_3_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Às vezes, fico aliviado que meu marido não[n]tenha subido tão alto nas fileiras.[n][w][e]

[msg MSG_TUMAARASOI_010_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Os ladrões fantasmas fizeram isso! Eu estive[n]do lado deles o tempo todo.[n][w][e]

[msg MSG_TUMAARASOI_010_1_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Todo mundo está tudo sobre os ladrões[n]Phantom agora. Eles são todos os que estão[n]na TV fala.[n][w][e]

[msg MSG_TUMAARASOI_010_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Eu disse aos meus hubs que ele deveria[n]vender um hambúrguer inspirado em ladrões[n]Phantom.[n][w][e]
[s][vp 8 2 1 0 19 0]Você não acha que seria um grande sucesso?[n]É preciso sempre ter o dedo no pulso.[n][w][e]

[msg MSG_TUMAARASOI_011_0_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Como está seu marido? A empresa deve estar[n]fazendo controle de danos completos após[n]essa reportagem.[n][w][e]

[msg MSG_TUMAARASOI_011_1_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]É tudo mentira! Todo mundo está querendo[n]obter o Okumura Foods porque tem ciúmes do[n]seu sucesso![n][w][e]

[msg MSG_TUMAARASOI_011_2_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Tem certeza? Meu marido, ele nunca recebe[n]nenhum pagamento de horas extras, então...[n][w][e]
[s][vp 8 2 1 0 20 0]Gostaria de saber se eles vão fixar isso no[n]CEO.[n]Ele provavelmente deveria apenas admitir a[n]verdade.[n]OHOHO...[n][w][e]

[msg MSG_TUMAARASOI_012_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Ouvi dizer que eles não podem chegar a[n]Okumura...[n]Meu Hubberton está trabalhando até tarde por[n]causa de tudo.[n][w][e]

[msg MSG_TUMAARASOI_012_1_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Bem, os ladrões fantasmas enviaram seu[n]cartão de visita. Não pode ser uma boa[n]notícia para os figurões corporativos.[n][w][e]

[msg MSG_TUMAARASOI_012_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]A polícia precisa sair de suas traseiras e[n]prender esses delinqüentes![n][w][e]

[msg MSG_TUMAARASOI_012_3_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Eu pensei que você era fã dos ladrões[n]Phantom? Ohoho, eu sei que os tempos são[n]difíceis agora, mas...[n][w][e]

[msg MSG_TUMAARASOI_013_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Não acredito que Okumura entrou em colapso![n]O que isso significa para a empresa?[n][w][e]

[msg MSG_TUMAARASOI_013_1_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Você precisa relaxar. Tenho certeza de que a[n]empresa ficará bem.[n][w][e]
[s][vp 8 2 1 0 20 0]Quero dizer, tenho certeza de que haverá[n]redução maciça, sem mencionar[n]rebaixamentos...[n][w][e]

[msg MSG_TUMAARASOI_013_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Mas... meus hubbers acabaram de ser[n]promovidos![n]Droga, ladrões Phantom![n][w][e]

[msg MSG_TUMAARASOI_014_0_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]A Okumura Foods passou por um verdadeiro[n]patch. Ouvi dizer que a nota de pagamento[n]do seu marido foi severamente reduzida.[n][w][e]

[msg MSG_TUMAARASOI_014_1_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Estou feliz que a empresa tenha sobrevivido[n]em uma peça- e que minha família tenha[n]muita em nossas economias.[n][w][e]
[s][vp 8 2 1 0 19 0]A propósito, como está o seu cara? Oh, me[n]desculpe- eu não pergunto?[n][w][e]

[msg MSG_TUMAARASOI_014_2_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Bem, na verdade, porque ele ajudou tanto no[n]caso, eles o promoveram ao CEO. OHOHO...[n][w][e]

[msg MSG_TUMAARASOI_015_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Os ladrões Phantom ainda estão soltos,[n]certo? Estou com tanto medo de estar[n]sozinho quando o husbo não estiver em casa.[n][w][e]

[msg MSG_TUMAARASOI_015_1_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Sozinho? E quanto à sua empregada? Você[n]deixou o pobre querido ir?[n][w][e]

[msg MSG_TUMAARASOI_015_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Nós tivemos que. Não pode poupar despesas[n]desnecessárias durante esse tempo[n]tumultuado, podemos?[n][w][e]

[msg MSG_TUMAARASOI_015_3_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Uma mulher tão admirável que você se tornou.[n]Bem, como se costuma dizer, o orgulho vem[n]antes de uma queda. OHOHO...[n][w][e]

[msg MSG_TUMAARASOI_016_0_0 [Not-So-Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Aquele sujeito shido- o cara do futuro[n]unido- parece muito bom. Ele deve se tornar[n]primeiro ministro.[n][w][e]

[msg MSG_TUMAARASOI_016_1_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Ohoho... você sabe, eu realmente conheci[n]Shido-san, durante uma das funções do meu[n]marido-budy.[n][w][e]

[msg MSG_TUMAARASOI_016_2_0 [Not-So-Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]É assim mesmo? Acabamos de conhecê-lo outro[n]dia, enquanto ingressamos na Associação de[n]Apoiadores.[n][w][e]
[s][vp 8 2 1 0 20 0]Ele parecia muito bom. Você estava no evento?[n][w][e]

[msg MSG_TUMAARASOI_017_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 20 0]Você viu? O líder dos ladrões fantasmas[n]ainda está vivo![n][w][e]

[msg MSG_TUMAARASOI_017_1_0 [Not-So-Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 19 0]Aposto que é apenas um truque destinado a[n]desacreditar Shido-san de alguma forma![n][w][e]
[s][vp 8 2 1 0 19 0]É isso que os talk shows estão dizendo- que[n]é apenas calúnia devido às eleições.[n][w][e]

[msg MSG_TUMAARASOI_018_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Estou preocupado com a saúde de Shido-san.[n][w][e]

[msg MSG_TUMAARASOI_018_1_0 [Not-So-Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Sim, precisamos que ele traga mudanças reais[n]para o Japão. Meu filho está se aproximando[n]dos exames de admissão.[n][w][e]
[s][vp 8 2 1 0 20 0]Eu quero um Japão melhor esperando por ele[n]do outro lado.[n][w][e]

[msg MSG_TUMAARASOI_019_0_0 [Not-So-Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Oh, feliz ano novo. No ano passado, foi[n]cheio de surpresas, você não concordaria...?[n][w][e]

[msg MSG_TUMAARASOI_019_1_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Sim, verdadeiramente. Estou muito chocado,[n]na verdade...[n][w][e]
[s][vp 8 2 1 0 19 0]... Considerando o quão extremamente bem os[n]negócios se realizaram, a estabilidade[n]financeira de nossa família é ainda mais[n]solidificada.[n][w][e]
[s][vp 8 2 1 0 19 0]Além disso, meu marido foi promovido, então[n]ele está muito ocupado...[n][w][e]

[msg MSG_TUMAARASOI_019_2_0 [Not-So-Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]O que...? O-oh, isso é tão...[n][w][e]
[s][vp 8 2 1 0 20 0]Bem, meu marido também foi promovido, então[n]acho que eles continuarão trabalhando um[n]com o outro com bastante frequência.[n][w][e]

[msg MSG_TUMAARASOI_020_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Ouvi dizer que está ficando cada vez mais[n]frio neste inverno...[n][w][e]
[s][vp 8 2 1 0 19 0]Por isso, decidimos passar o inverno em uma[n]praia particular no Havaí, a partir do[n]próximo mês.[n][w][e]
[s][vp 8 2 1 0 19 0]O inverno deve estar muito mais quente por[n]lá, então...[n][w][e]

[msg MSG_TUMAARASOI_020_1_0 [Not-So-Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]O que!? Isso é... muito tempo que você vai[n]passar por lá...[n][w][e]
[s][vp 8 2 1 0 20 0]B-mas quero dizer, estamos planejando ir[n]para uma praia particular em Guam também no[n]próximo mês![n][w][e]
[s][vp 8 2 1 0 20 0]Meu marido recebeu um aumento, então[n]felizmente poderíamos pagar...[n][w][e]

[msg MSG_TUMAARASOI_020_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Uau, isso parece incrível! Fico feliz em[n]saber que sua família está bem.[n][w][e]
[s][vp 8 2 1 0 19 0]Tenho a sensação de que este ano novo será[n]outro maravilhoso.[n][w][e]

[msg MSG_TUMAARASOI_020_3_0 [Not-So-Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Y-sim... eu acho também...[n][w][e]

[msg MSG_TUMAARASOI_021_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Hah. Meu marido me disse que foi selecionado[n]como membro principal de seu próximo[n]projeto![n][w][e]
[s][vp 8 2 1 0 19 0]Ultimamente não houve nada além de ótimas[n]notícias.[n][w][e]

[msg MSG_TUMAARASOI_021_1_0 [Not-So-Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Estou feliz em ouvir isso.[n][w][e]
[s][vp 8 2 1 0 20 0]O trabalho também está indo muito bem para o[n]meu marido. Ele acabou de conseguir um[n]grande negócio...[n][w][e]
[s][vp 8 2 1 0 20 0]W-We é até pensando em ter uma casa[n]novíssima construída para nós![n][w][e]
[s][vp 8 2 1 0 20 0]Eu sinto que estamos em uma venda de[n]felicidade, você sabe!?[n][w][e]

[msg MSG_TUMAARASOI_021_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Uau. Então eu acho que você fez isso.[n][w][e]

[msg MSG_TUMAARASOI_021_3_0 [Not-So-Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]O que...?[n][w][e]

[msg MSG_TUMAARASOI_021_4_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Quero dizer, você está dizendo que as coisas[n]estão indo tão bem para você que não há[n]mais nada para desejar, certo?[n][w][e]
[s][vp 8 2 1 0 19 0]... Mas parece que você precisa diminuir um[n]pouco a velocidade.[n][w][e]
[s][vp 8 2 1 0 19 0]Talvez você esteja sendo um pouco ganancioso?[n]Tudo depende de como você olha para ele.[n][w][e]
[s][vp 8 2 1 0 19 0]Você pode entender o que quero dizer, depois[n]de experimentar a verdadeira felicidade.[n]Hohoho...[n][w][e]

[msg MSG_TUMAARASOI_022_0_0 [Not-So-Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Ouvi dizer que seu marido foi forçado a se[n]aposentar.[n]Isso deve ter sido duro com vocês dois.[n][w][e]

[msg MSG_TUMAARASOI_022_1_0 [Not-So-Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Sim... podemos precisar morar com meus pais.[n]Temporariamente, é claro.[n][w][e]

[msg MSG_TUMAARASOI_022_2_0 [Not-So-Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Bem, se você precisar de eu trazer algo da[n]cidade, não hesite em perguntar.[n][w][e]
[s][vp 8 2 1 0 20 0]Tenho certeza que você sentirá falta da[n]cidade.[n]OHOHO...[n][w][e]

[msg MSG_TUMAARASOI_0504_0_0 [Arrogant Housewife]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Seu filho é um estudante Shujin, correto?[n]Onde aquele professor famoso foi preso...[n][w][e]
[s][vp 8 2 1 0 19 0]Se eu soubesse sobre um professor assim,[n]teria meu filho transferido para uma escola[n]diferente imediatamente.[n][w][e]
[s][vp 8 2 1 0 19 0]Eu sempre garanto que meu filho está[n]escrevendo em um diário.[n][w][e]
[s][vp 8 2 1 0 19 0]Dessa forma, eu sei o que está acontecendo[n]na escola deles.[n][w][e]

[msg MSG_TUMAARASOI_0504_1_0 [Modest Housewife]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Bem, meu filho não está no time de vôlei,[n]então não vejo a necessidade de um diário...[n][w][e]

[msg MSG_TUMAARASOI_0504_2_0 [Arrogant Housewife]]
[s][f 4 23 1 19 20 10 0 10][vp 8 2 1 0 19 0]Nós donas de casa somos responsáveis por[n]criar uma criança de sucesso, você sabe.[n]Não podemos estar relaxando, ohoho...[n][w][e]

[msg MSG_TOKAISOMARU_001_0_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Huh? O que deu em você?[n][w][e]

[msg MSG_TOKAISOMARU_001_1_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Eu sou seu namorado. Eu não poderia deixá-lo[n]para se defender enquanto os trens[n]descarrilam para a esquerda e para a[n]direita![n][w][e]
[s][vp 8 2 1 0 22 0]Eu simplesmente não consigo parar de me[n]preocupar com você! Eu não vou deixar esta[n]cidade engolir você inteiro![n][w][e]

[msg MSG_TOKAISOMARU_001_2_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Pare de fazer um barulho! Você está me[n]envergonhando![n][w][e]

[msg MSG_TOKAISOMARU_002_0_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Esta cidade é pervertida e criminosos[n]perigosos. Não há lugar para pessoas como[n]nós.[n]Vamos para casa.[n][w][e]

[msg MSG_TOKAISOMARU_002_1_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Mas foi meu sonho morar aqui![n]Já solte![n][w][e]

[msg MSG_TOKAISOMARU_002_2_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Então você só vai jogar tudo fora?[n]Sua herança? Você está em casa?[n][w][e]

[msg MSG_TOKAISOMARU_002_3_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eu não estou "jogando fora" nada. Eu disse[n]que voltaria para casa uma vez por ano para[n]visitar.[n]Não é suficiente?[n][w][e]

[msg MSG_TOKAISOMARU_003_0_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]As lojas de conveniência aqui são tão...[n]Bem, conveniente.[n][w][e]

[msg MSG_TOKAISOMARU_003_1_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Você pode obter o que você precisar no país[n]também- basta perguntar a um vizinho![n][w][e]
[s][vp 8 2 1 0 22 0]Eu posso levar você em encontros[n]sofisticados! Podemos ir uma unidade! Vou[n]pegá-lo em uma limusine ou um carro de luxo![n][w][e]

[msg MSG_TOKAISOMARU_003_2_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Você quer dizer um trator ou um caminhão.[n]Uh, não, obrigado. Não interessado.[n][w][e]

[msg MSG_TOKAISOMARU_004_0_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Fui do meu caminho para assistir à sua[n]exposição porque ele é muuuito famoso, mas[n]acabou que ele é um plágio![n][w][e]

[msg MSG_TOKAISOMARU_004_1_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Eu sabia! E'eryone nesta cidade é um[n]mentiroso degenerado![n][w][e]
[s][vp 8 2 1 0 22 0]Eu até ouvi dizer que há um monte de ladrões[n]à solta! Vamos lá, deixe-me levar você para[n]casa.[n][w][e]

[msg MSG_TOKAISOMARU_004_2_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Você está exagerando. Além disso, os ladrões[n]fantasmas estão do nosso lado![n][w][e]

[msg MSG_TOKAISOMARU_005_0_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]A TV diz que há criminosos à solta. Você tem[n]que garantir que você trava sua porta à[n]noite.[n][w][e]

[msg MSG_TOKAISOMARU_005_1_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Sim, sim- a máfia, eu sei.[n]Relaxe, a cidade está perfeitamente segura.[n][w][e]

[msg MSG_TOKAISOMARU_005_2_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]O mesmo acontece com o país, graças a Taro[n]da porta ao lado![n][w][e]

[msg MSG_TOKAISOMARU_005_3_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Você quer dizer aquele cachorro idiota que[n]brinca com alguém que se aproxima dele?[n]Cão de guarda muito bom.[n][w][e]

[msg MSG_TOKAISOMARU_006_0_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eu quero ir a um clube e dançar a noite toda.[n]Talvez até tenha alguns coquetéis.[n][w][e]

[msg MSG_TOKAISOMARU_006_1_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Eu fui a um bar muito bom há pouco tempo, em[n]Shinjuku.[n][w][e]
[s][vp 8 2 1 0 22 0]Gerente lá, ela era muito legal.[n]Era como estar no céu...[n][w][e]

[msg MSG_TOKAISOMARU_006_2_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Você... foi a um clube de hostess?[n][w][e]

[msg MSG_TOKAISOMARU_007_0_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eu posso ficar tranquilo sabendo que a máfia[n]foi fechada. Agora eu posso apenas viver[n]isso no estilo da cidade tudo o que quero.[n][w][e]

[msg MSG_TOKAISOMARU_007_1_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Este lugar não está seguro! Há aqueles[n]ladrões fantasmas assustadores ou qualquer[n]coisa que esteja sendo selvagem.[n][w][e]
[s][vp 8 2 1 0 22 0]E se eles te arrebatarem na calada da noite?[n]Vamos lá, vamos voltar para casa.[n][w][e]

[msg MSG_TOKAISOMARU_007_2_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eu disse que solte-o já! Estou tão cansado[n]de ouvir sobre o país![n][w][e]

[msg MSG_TOKAISOMARU_008_0_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Se você ficar aqui, esses preguiçosos vão[n]quebrar seu computador![n][w][e]

[msg MSG_TOKAISOMARU_008_1_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eles são chamados de Medjed e são hackers.[n]De qualquer forma, eles apenas têm como[n]alvo corporações.[n][w][e]

[msg MSG_TOKAISOMARU_008_2_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Você vai ficar em água quente de verdade,[n]fica tão descuidada. Se você quiser, eu[n]posso ficar de guarda esta noite.[n][w][e]

[msg MSG_TOKAISOMARU_008_3_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Yeah, yeah...[n][w][e]

[msg MSG_TOKAISOMARU_009_0_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Você deve voltar para casa para Obon.[n]Além disso, a cidade não está segura por[n]causa de Medjeb.[n][w][e]

[msg MSG_TOKAISOMARU_009_1_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]A geografia não importa na internet. Além[n]disso, os ladrões fantasmas cuidarão deles.[n][w][e]

[msg MSG_TOKAISOMARU_009_2_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Os ladrões Phantom são apenas um mito![n]É por isso que eles não responderam![n][w][e]
[s][vp 8 2 1 0 22 0]Acordar. Esta cidade é construída sobre[n]mentiras![n][w][e]

[msg MSG_TOKAISOMARU_010_0_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Desculpe, dizendo que os ladrões fantasmas[n]foram inventados...[n][w][e]
[s][vp 8 2 1 0 22 0]Eles são realmente algo mais.[n]Eu quero aprender com eles.[n][w][e]

[msg MSG_TOKAISOMARU_010_1_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Estou feliz que você esteja finalmente[n]conseguindo.[n][w][e]

[msg MSG_TOKAISOMARU_010_2_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Sim. Deixe-me que seja bom da loja de[n]presentes em casa, para mostrar que sinto[n]muito.[n][w][e]

[msg MSG_TOKAISOMARU_010_3_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eu tomo de volta. Você claramente não[n]entende ainda![n][w][e]

[msg MSG_TOKAISOMARU_011_0_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Esse CEO é simplesmente mau. Ele não se[n]importa com ninguém além de si mesmo![n][w][e]

[msg MSG_TOKAISOMARU_011_1_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Os ladrões Phantom cuidarão dele, não se[n]preocupe. Espero que eles façam isso logo.[n][w][e]

[msg MSG_TOKAISOMARU_011_2_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]O corpo de bombeiros de volta para casa[n]teria chegado ao resgate rapidamente.[n][w][e]

[msg MSG_TOKAISOMARU_011_3_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]E essa conversa acabou.[n][w][e]

[msg MSG_TOKAISOMARU_012_1_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eles deixaram um novo cartão de visita.[n][w][e]
[s][vp 8 2 1 0 21 0]Se o CEO mudar de coração, você acha que os[n]hambúrgueres ficarão mais baratos?[n][w][e]

[msg MSG_TOKAISOMARU_012_2_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Eles abriram um em casa há pouco tempo.[n]Linhas enormes- você pensaria que era um[n]festival ou algo assim.[n][w][e]
[s][vp 8 2 1 0 22 0]Eu não sabia que os hambúrgueres de[n]Bangarang eram tão incríveis.[n][w][e]

[msg MSG_TOKAISOMARU_013_1_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Eu realmente poderia ir para um hambúrguer,[n]mas depois de tudo isso...[n][w][e]

[msg MSG_TOKAISOMARU_013_2_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Você está falando sobre Bangarang?[n]Aposto que toda a empresa está indo para[n]baixo.[n][w][e]
[s][vp 8 2 1 0 22 0]O rosto desse CEO estava... aterrorizado.[n]Esses ladrões fantasmas são implacáveis.[n][w][e]

[msg MSG_TOKAISOMARU_014_0_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Os ladrões Phantom estão no LAM, certo? É[n]assustador pensar que eles poderiam estar[n]se escondendo por perto...[n][w][e]

[msg MSG_TOKAISOMARU_014_1_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Isso significa que você finalmente quer[n]voltar para o país?[n][w][e]

[msg MSG_TOKAISOMARU_014_2_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Não. Eu trabalhei muito para chegar aqui[n]apenas para sair agora. Só tenho que[n]esperar que eles sejam pegos em breve.[n][w][e]

[msg MSG_TOKAISOMARU_014_3_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Eu vou te manter seguro. Estamos todos muito[n]preocupados sobre você, você sabe.[n][w][e]

[msg MSG_TOKAISOMARU_015_0_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Não ouviu? Alguém da nossa escola primária[n]está administrando o escritório da Fer.[n][w][e]

[msg MSG_TOKAISOMARU_015_1_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]O que realmente!? Quem? Eu me pergunto se[n]éramos amigos...[n][w][e]

[msg MSG_TOKAISOMARU_015_2_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Bem, ele sempre dizia que queria melhorar[n]nossa cidade. É uma verdadeira batalha[n]difícil, eu ouvi, no entanto.[n][w][e]

[msg MSG_TOKAISOMARU_016_0_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Eu não me importo com o quão ruins são, o[n]suicídio nunca deve ser a resposta.[n][w][e]
[s][vp 8 2 1 0 22 0]Fazendo isso com sua mãe e papai...[n]Isso não é um bom caminho a percorrer.[n][w][e]

[msg MSG_TOKAISOMARU_016_1_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Sim, isso também não se encaixa bem comigo.[n]Não havia razão para ele morrer.[n][w][e]

[msg MSG_TOKAISOMARU_016_2_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]É a nossa culpa também![n]Depois da merda, dissemos sobre 'eu![n][w][e]

[msg MSG_TOKAISOMARU_016_3_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Você está certo, desculpe... ninguém jamais[n]tomou esse tom comigo antes.[n][w][e]

[msg MSG_TOKAISOMARU_017_0_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Shido é um homem mau? Deveríamos estar[n]acreditando nos ladrões Phantom?[n][w][e]

[msg MSG_TOKAISOMARU_017_1_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]De qualquer maneira, temos que assistir e[n]esperar.[n]Não há mais nada que possamos fazer.[n][w][e]

[msg MSG_TOKAISOMARU_017_2_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]... Eu não sei o que devo estar[n]realizando... me sentindo muito perdido[n]nesta selva concreta.[n][w][e]

[msg MSG_TOKAISOMARU_017_3_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Estou surpreso ao saber que você se sente[n]perdido.[n][w][e]

[msg MSG_TOKAISOMARU_018_0_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Então, acho que vou voltar para casa.[n]Você vai ficar na cidade?[n][w][e]

[msg MSG_TOKAISOMARU_018_1_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Huh? Sim... por que a mudança repentina?[n][w][e]

[msg MSG_TOKAISOMARU_018_2_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Aqui fica claro. Tóquio não é para mim. Além[n]disso, quero mostrar apoio ao nosso[n]companheiro de escola, correndo para[n]eleições.[n][w][e]

[msg MSG_TOKAISOMARU_018_3_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]...Oh. Eu vejo.[n][w][e]

[msg MSG_TOKAISOMARU_019_0_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]S-Sorry... você poderia repetir o que acabou[n]de dizer?[n][w][e]

[msg MSG_TOKAISOMARU_019_1_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Eu disse que deveríamos morar juntos em[n]Tóquio.[n][w][e]
[s][vp 8 2 1 0 22 0]Você gosta lá, e eu também.[n][w][e]
[s]Além disso, compartilhamos os mesmos valores.[n]Você não acha que é uma boa ideia?[n][w][e]

[msg MSG_TOKAISOMARU_019_2_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Ok, primeiro... o que aconteceu com você?[n][w][e]
[s][vp 8 2 1 0 21 0]Você está falando e agindo de maneira[n]diferente...[n]Estou tão confuso agora.[n][w][e]

[msg MSG_TOKAISOMARU_020_0_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Desculpe, você poderia repetir o que disse[n]de novo?[n][w][e]

[msg MSG_TOKAISOMARU_020_1_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Ok, estou dizendo que devemos viver em uma[n]dessas mansões de designer.[n][w][e]
[s][vp 8 2 1 0 22 0]Podemos fazer nosso lugar feminino e tudo[n]mais... Não é isso que você quer?[n][w][e]

[msg MSG_TOKAISOMARU_020_2_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]W-Well Sim, é isso que eu sempre quis, mas...[n][w][e]
[s][vp 8 2 1 0 21 0]Como você sabia tudo isso?[n][w][e]

[msg MSG_TOKAISOMARU_020_3_0 [Rural Young Man]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Atualmente, é importante ampliar seu[n]horizonte e continuar aprendendo coisas[n]novas.[n][w][e]
[s][vp 8 2 1 0 22 0]É assim que sou capaz de aproveitar esta[n]feliz vida na cidade com você.[n][w][e]

[msg MSG_TOKAISOMARU_021_0_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0]......[n][w][e]
[s][vp 8 2 1 0 21 0]Eu sempre sonhei em viver essa vida de[n]Tóquio.[n]E agora eu posso fazer isso com ele...[n][w][e]
[s][vp 8 2 1 0 21 0]Tudo está indo muito bem, mas...[n][w][e]
[s][vp 8 2 1 0 21 0]*suspiro* Por que eu me sinto tão triste de[n]repente...?[n][w][e]

[msg MSG_TOKAISOMARU_021_1_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Todo mundo parece tão feliz desde que[n]começamos o ano novo...[n][w][e]
[s][vp 8 2 1 0 21 0]Mas então, por que eu tenho que me sentir[n]tão triste...[n][w][e]

[msg MSG_TOKAISOMARU_022_0_0 [Adorable Woman]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Tóquio parece tão quieto agora...[n][w][e]
[s][vp 8 2 1 0 21 0]Ou talvez ele estivesse apenas... alto.[n][w][e]
[s][vp 8 2 1 0 21 0]Huh. Pode haver algumas coisas que eu só[n]posso fazer na cidade, mas... também há[n]algo faltando.[n][w][e]
[s][vp 8 2 1 0 21 0]... Talvez eu deva ir para casa também.[n][w][e]

[msg Quest05_target_00_00 [Mitsumi Kure]]
[s][vp 8 2 1 0 600 0]Com licença, mas preciso falar com você.[n]Eu tenho um problema com seu curry picante.[n][w][e]
[s][vp 8 2 1 0 600 0]É muito picante! Eu tive uma experiência[n]terrível ao comer![n][w][e]
[s][vp 8 2 1 0 600 0]O interior da minha boca é todo queimado![n]Seu curry agravou minha estomatite![n]Eu não posso nem comer...[n][w][e]
[s][vp 8 2 1 0 600 0]Ow! Aghhh! Sério dói muito! Você realmente[n]deveria estar vendendo isso para os[n]clientes?[n][w][e]
[s][vp 8 2 1 0 600 0]Eu quero um pedido de desculpas e um[n]reembolso.[n]Por favor, pegue seu gerente para mim e[n]apresse-o.[n][w][e]
[s][vp 8 2 1 0 600 0]Wha-? Meu primeiro nome é Mitsumi![n]Mitsumi Kure![n][w][e]

[msg MSG_quest05_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Eu acho que temos nosso alvo. Vamos sair de[n]um plano no esconderijo![n][w][e]

[msg HELP_MEMENTOS_MISSION_02 [Mission Update!]]
[s]" [clr 4]Ocorrência de lembranças [clr 27]"O alvo foi identificado.[n]Agora, vamos discutir isso com a equipe de[n]volta ao " [n][clr 2]esconderijo [clr 27]. " [n][w][e]

[msg Quest05_target_01_00 [Mitsumi Kure]]
[s][vp 8 2 1 0 600 0]É por isso que não posso lidar com pessoas[n]no negócio de serviços... espere, tenho uma[n]prova sólida.[n][w][e]
[s][vp 8 2 1 0 600 0]Encontrei esta mensagem de brincadeira que[n]parece um cartão de visita para um crime na[n]minha bolsa, sabe?[n][w][e]
[s][vp 8 2 1 0 600 0]Tem que ser vocês, já que vocês são os que[n]venderam essas malas! Eu exijo um pedido de[n]desculpas![n][w][e]

[msg Quest05_target_02_00 [Mitsumi Kure]]
[s][vp 8 2 1 0 600 0]Sinto muito pela última vez e por reclamar[n]de toda a coisa da estomatite.[n][w][e]
[s][vp 8 2 1 0 600 0]Por favor, deixe-me pedir desculpas por[n]fazer todas essas queixas sobre você.[n][w][e]
[s][vp 8 2 1 0 600 0]Se estou sendo honesto, esse curry picante[n]era realmente delicioso.[n][w][e]
[s][vp 8 2 1 0 600 0]O interior da minha boca já estava inchado,[n]então eu piorando foi a minha culpa. Estou[n]tão envergonhado...[n][w][e]
[s][vp 8 2 1 0 600 0]Hoje, eu só queria expressar minha gratidão.[n][w][e]
[s][vp 8 2 1 0 600 0]O curry que seu lugar faz é uma[n]classificação ou duas melhores que o curry[n]em outros restaurantes.[n][w][e]
[s][vp 8 2 1 0 600 0]Estou olhando para quando você estará[n]adicionando novos pratos ao seu menu.[n][w][e]

[msg Quest09_target_00_00 [Sachiko Kuwai]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]Eu te disse, acabei de me encontrar com ele[n]um pouco! Não há como te trair.[n][w][e]

[msg Quest09_target_00_01 [Man about to Cry and Sue]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]Não jogue idiota! Você foi infiel comigo com[n]tantas pessoas... incluindo meus amigos![n][w][e]
[s][vp 8 2 1 0 602 0]Até tenho evidências de vídeo da agência de[n]detetives que contratei![n][w][e]

[msg Quest09_target_00_02 [Sachiko Kuwai]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 65535 0 0 0]......[n][w][e]
[s][vp 8 2 1 0 601 0]O que há de errado sobre uma mulher que[n]procura amor? É sua culpa por não poder me[n]amarrar![n][w][e]
[s][vp 8 2 1 0 601 0]Tudo bem, vá em frente. Processe-me. Meu[n]lado da família são todos advogados. Você[n]nunca ganhará.[n][w][e]

[msg Quest09_target_00_03 [Man about to Cry and Sue]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]Huh? Você está brincando comigo!?[n]Você não pode simplesmente se safar disso![n][w][e]

[msg Quest09_target_sinjyo_00]
[s][vp 8 2 65535 0 0 0]Tão comportamento desagradável...[n][w][e]

[msg MSG_quest09_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Parece que encontramos nosso alvo![n]Vamos voltar para o esconderijo e discutir[n]isso com todos![n][w][e]

[msg Quest09_target_01_00 [Sachiko Kuwai]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]O que é isto!? Você sabe que não pode vencer[n]no tribunal, então está recorrendo a[n]truques como este cartão de visita?[n][w][e]

[msg Quest09_target_01_01 [Man about to Cry and Sue]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]O que? N-no, não fui eu![n][w][e]
[s][vp 8 2 1 0 602 0]Deve ser aqueles ladrões fantasmas![n]Todo mundo está falando sobre como eles[n]andam por aí, roubando corações![n][w][e]

[msg Quest09_target_01_02 [Sachiko Kuwai]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]Como você ousa mentir para mim!? Eles não[n]têm como alvo pessoas que cometeram crimes[n]reais?[n][w][e]
[s][vp 8 2 1 0 601 0]Não há nada de errado comigo.[n]Eu não sou uma pessoa má![n][w][e]

[msg Quest09_target_sinjyo_01]
[s][vp 8 2 65535 0 0 0]Parece que o cartão de visita foi entregue[n]com segurança.[n][w][e]

[msg Quest09_target_02_00 [Sachiko Kuwai]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]U-um... por favor me ouça...[n][w][e]

[msg Quest09_target_02_01 [Cold-Gazed Man]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]Huh? O que você quer!? Se você acha que pode[n]me enganar fingindo chorar, não funcionará![n][w][e]

[msg Quest09_target_02_02 [Sachiko Kuwai]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]Não é isso! Sinto muito por trair você até[n]agora.[n][w][e]
[s][vp 8 2 1 0 601 0]Vou te pagar qualquer dinheiro de consolação[n]que você quiser. Vou compensar você, o que[n]for preciso![n][w][e]
[s][vp 8 2 1 0 601 0]Então, por favor, me perdoe.[n][w][e]

[msg Quest09_target_02_03 [Cold-Gazed Man]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]Que diabos...? Já é meio tarde para você[n]dizer tudo isso...[n][w][e]
[s][vp 8 2 1 0 602 0]Entendo. Os ladrões Phantom realmente[n]mudaram seu coração. Agora que eles te[n]salvaram...[n][w][e]
[s][vp 8 2 1 0 602 0]Tudo que eu quero de você é que você se[n]encontra um cara legal. Seja leal a ele e[n]faça-o feliz.[n][w][e]

[msg Quest09_target_sinjyo_02]
[s][vp 8 2 65535 0 0 0]Parece que a missão foi um sucesso...[n][w][e]

[msg Quest14_target_00_00 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]A área usual do lado de fora dos portões de[n]ingresso! Você já deve saber agora, seu[n]velho Hag![n][w][e]
[s][vp 8 2 1 0 605 0]Olhe, me empreste algum dinheiro apenas mais[n]algumas vezes e eu vou atingir-o grande.[n]Então cale a boca e traga-o já![n][w][e]
[s][vp 8 2 1 0 605 0]Oh vamos lá. Eu sei que sua pensão chegou no[n]outro dia.[n][w][e]
[s][vp 8 2 1 0 605 0]Então, se você conseguir, apresse-se e traga[n]o dinheiro! E pare de chamar-me daichi-chan![n][w][e]
[s][vp 8 2 1 0 605 0]Nossa. É demais para uma mãe ajudar seu[n]filho quando ele está em um[n]congestionamento, sem perguntas?[n][w][e]

[msg Quest14_target_sinjyo_00]
[s][vp 8 2 65535 0 0 0]Esse cara é terrível...[n][w][e]

[msg MSG_quest14_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Parece que encontramos nosso alvo![n]Vamos voltar para o esconderijo e discutir[n]isso com todos![n][w][e]

[msg Quest14_target_01_00 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]Cartão de chamada...? O que diabos é isso...?[n][w][e]

[msg Quest14_target_01_01 [Man about to Cry and Sue]]
[s][vp 8 2 1 0 605 0]Foi endereçado a você, então...[n][w][e]

[msg Quest14_target_01_02 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]Você acha que eu quero algo assustador[n]assim, sua velha bruxa?[n][w][e]
[s][vp 8 2 1 0 605 0]Apenas me dê o maldito dinheiro![n][w][e]

[msg Quest14_target_sinjyo_01]
[s][vp 8 2 65535 0 0 0]Parece que o cartão de visita foi entregue[n]com segurança.[n][w][e]

[msg Quest14_target_02_00 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]Mãe, decidi que vou trabalhar como[n]funcionário.[n][w][e]
[s][vp 8 2 1 0 605 0]Expliquei minha situação ao meu chefe e ele[n]disse que cuidará de mim.[n][w][e]

[msg Quest14_target_02_01 [Daichi's Mother]]
[s][vp 8 2 1 0 605 0]Realmente agora? Fico feliz em ouvir isso.[n][w][e]
[s][vp 8 2 1 0 605 0]Isso me deixa um pouco triste.[n]Não haverá mais ninguém em casa...[n][w][e]

[msg Quest14_target_02_02 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]Vou visitar às vezes.[n][w][e]
[s][vp 8 2 1 0 605 0]E não se preocupe. Vou pagar todo o dinheiro[n]que devo a você...[n][w][e]

[msg Quest14_target_02_03 [Daichi's Mother]]
[s][vp 8 2 1 0 605 0]Não se preocupe com isso.[n][w][e]
[s][vp 8 2 1 0 605 0]Tudo que eu queria era que você fosse feliz.[n][w][e]

[msg Quest14_target_02_04 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]Mãe...[n][w][e]

[msg Quest14_target_sinjyo_02]
[s][vp 8 2 65535 0 0 0]Parece que a missão foi um sucesso...[n][w][e]

[msg Quest15_target_00_00 [Muneo Horiguchi]]
[s][f 4 23 1 603 3 10 0 0][vp 8 2 1 0 603 0]Eu digo a eles para se mudarem, mas eles[n]respondem. É por isso que a juventude de[n]hoje é inútil.[n][w][e]

[msg Quest15_target_00_01 [Muneo's Grandson]]
[s][f 4 23 1 604 3 10 0 0][vp 8 2 1 0 604 0]Vovô, eu disse que estou bem de pé.[n]Você não me ouviu?[n][w][e]

[msg Quest15_target_00_02 [Muneo Horiguchi]]
[s][vp 8 2 1 0 603 0]Essa não é a questão. Eles deveriam desistir[n]de seus assentos quando eu os digo.[n][w][e]

[msg Quest15_target_00_03 [Muneo's Grandson]]
[s][vp 8 2 1 0 604 0]Mas papai estava dizendo que não devemos[n]gritar com as pessoas...[n][w][e]

[msg Quest15_target_00_04 [Muneo Horiguchi]]
[s][vp 8 2 1 0 603 0]Não, essa é uma questão de educação moral,[n]disciplina! Alguém tem que dizer a eles o[n]que é apropriado.[n][w][e]

[msg Quest15_target_00_05 [Muneo's Grandson]]
[s][vp 8 2 1 0 604 0]Todo mundo ao nosso redor estava nos dando[n]um olhar sujo...[n][w][e]

[msg Quest15_target_00_06 [Muneo Horiguchi]]
[s][vp 8 2 1 0 603 0]Esses tolos![n][w][e]
[s][vp 8 2 1 0 603 0]Somos nós que sangraram e suam para[n]transformar o Japão no que é hoje![n][w][e]
[s][vp 8 2 1 0 603 0]Como pensam que eles são capazes de viver em[n]paz agora!? Os jovens não têm o direito de[n]reclamar.[n][w][e]
[s][vp 8 2 1 0 603 0]No entanto, eles têm a audácia de não[n]desistir de seus assentos. Eles não sabem[n]nada sobre respeito!?[n][w][e]

[msg MSG_quest15_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Parece que encontramos nosso alvo![n]Vamos voltar para o esconderijo e discutir[n]isso com todos![n][w][e]

[msg Quest15_target_01_00 [Muneo Horiguchi]]
[s][f 4 23 1 603 3 10 0 0][vp 8 2 1 0 603 0]HM, um cartão de visita...? Simplesmente[n]ultrajante.[n][w][e]
[s][vp 8 2 1 0 603 0]Que tipo de hooligan descarado é responsável[n]por essa brincadeira estúpida...?[n][w][e]

[msg Quest15_target_sinjyo_01]
[s][vp 8 2 65535 0 0 0]Parece que o cartão de visita foi entregue[n]com segurança.[n][w][e]

[msg Quest15_target_02_00 [Muneo Horiguchi]]
[s][f 4 23 1 603 3 10 0 0][vp 8 2 1 0 603 0]Meu neto se distanciou completamente de mim[n]agora.[n]Ele nem sequer visitará minha casa.[n][w][e]
[s][vp 8 2 1 0 603 0]Ele ficou cansado de estar comigo porque eu[n]discurso e elogio sobre tudo...[n][w][e]
[s][vp 8 2 1 0 603 0]A família do meu filho até me disse que sou[n]muito teimosa, que as crianças precisam[n]aprender empatia pelos outros.[n][w][e]

[msg Quest15_target_02_01 [Smiling Elderly Man]]
[s][f 4 23 1 604 3 10 0 0][vp 8 2 1 0 604 0]Bem, é claro, a sabedoria vem com a idade,[n]mas envelhecer não significa que você[n]também será perfeito.[n][w][e]
[s][vp 8 2 1 0 604 0]Além disso, você sempre teve uma maneira[n]aproximada de falar...[n][w][e]
[s][vp 8 2 1 0 604 0]Para ser sincero, também pensei em manter[n]minha distância de você no passado.[n][w][e]

[msg Quest15_target_02_02 [Muneo Horiguchi]]
[s][f 4 23 1 603 3 10 0 0][vp 8 2 1 0 603 0]Eu entendi mal todos os tipos de coisas.[n]Não acredito que estou apenas percebendo[n]agora nessa idade.[n][w][e]
[s][vp 8 2 1 0 603 0]Não tenho muitos anos para fazer um novo[n]começo, mas farei o que puder.[n][w][e]
[s][vp 8 2 1 0 603 0]Primeiro, pretendo me registrar no Centro de[n]Recursos Humanos de Prata.[n][w][e]
[s][vp 8 2 1 0 603 0]Tenho certeza de que, se eu puder ser útil,[n]de alguma forma, posso encontrar um novo[n]significado, novo valor, em minha vida.[n][w][e]

[msg Quest15_target_sinjyo_02]
[s][vp 8 2 65535 0 0 0]Parece que a mudança de coração é evidente[n]em sua auto-reflexão...[n][w][e]

[msg quest23_hint_talk_00 [ヒント23]]
[s]クエスト23のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest23_hint_sinjyo]
[s]クエスト23のテスト心情メッセージです。[n][w][e]

[msg MSG_quest23_morgana_00 [Morgana]]
[s]クエスト23のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

[msg quest26_hint_talk_00 [ヒント26]]
[s]クエスト26のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest26_hint_sinjyo]
[s]クエスト26のテスト心情メッセージです。[n][w][e]

[msg MSG_quest26_morgana_00 [Morgana]]
[s]クエスト26のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

[msg quest37_hint_talk_00 [ヒント37]]
[s]クエスト37のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest37_hint_sinjyo]
[s]クエスト37のテスト心情メッセージです。[n][w][e]

[msg MSG_quest37_morgana_00 [Morgana]]
[s]クエスト37のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

[msg quest42_hint_talk_00 [ヒント42]]
[s]クエスト42のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest42_hint_sinjyo]
[s]クエスト42のテスト心情メッセージです。[n][w][e]

[msg MSG_quest42_morgana_00 [Morgana]]
[s]クエスト42のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

[msg Quest44_target_00_00 [ターゲット44]]
[s][f 4 23 1 614 3 10 0 0]クエスト44のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗は受注可能状態です。[n][w][e]

[msg Quest44_target_sinjyo_00]
[s]クエスト44のテスト心情メッセージです。[n][w][e]

[msg MSG_quest44_morgana_01 [Morgana]]
[s]クエスト44のモルガナメッセージです。[n]ターゲット用です。[n][w][e]

[msg Quest44_target_01_00 [ターゲット44]]
[s][f 4 23 1 614 3 10 0 0]クエスト44のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗はメメントス突入可能状態です。[n][w][e]

[msg Quest44_target_sinjyo_01]
[s]クエスト44のテスト心情メッセージです。[n][w][e]

[msg Quest44_target_02_00 [ターゲット44]]
[s][f 4 23 1 614 3 10 0 0]クエスト44のテストメッセージです。[n]表示後、キャンプでの状態を確認して下さい。[n][w][e]
[s]クエストの進捗はミッションクリア状態です。[n][w][e]

[msg Quest44_target_sinjyo_02]
[s]クエスト44のテスト心情メッセージです。[n][w][e]

[msg Quest46_target_00_00 [ターゲット46]]
[s][f 4 23 1 616 3 10 0 0]クエスト46のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗は受注可能状態です。[n][w][e]

[msg Quest46_target_sinjyo_00]
[s]クエスト46のテスト心情メッセージです。[n][w][e]

[msg MSG_quest46_morgana_01 [Morgana]]
[s]クエスト46のモルガナメッセージです。[n]ターゲット用です。[n][w][e]

[msg Quest46_target_01_00 [ターゲット46]]
[s][f 4 23 1 616 3 10 0 0]クエスト46のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗はメメントス突入可能状態です。[n][w][e]

[msg Quest46_target_sinjyo_01]
[s]クエスト46のテスト心情メッセージです。[n][w][e]

[msg Quest46_target_02_00 [ターゲット46]]
[s][f 4 23 1 616 3 10 0 0]クエスト46のテストメッセージです。[n]表示後、キャンプでの状態を確認して下さい。[n][w][e]
[s]クエストの進捗はミッションクリア状態です。[n][w][e]

[msg Quest46_target_sinjyo_02]
[s]クエスト46のテスト心情メッセージです。[n][w][e]

[msg JUICE_SHOP_NOTOPEN [Employee]]
[s][vp 8 2 1 0 2 0]Desculpe, ainda estamos passando por[n]reformas.[n][w][e]
[s][vp 8 2 1 0 2 0]○日になったらオープンしますので[n]また来てください![n][w][e]

[msg JUICE_SHOP_SELECT [Employee]]
[s][vp 8 2 1 0 2 0]Bem-vindo! Nosso suco de baga misto está à[n]venda hoje a um preço baixo e baixo![n][w][e]
[s][vp 8 2 1 0 2 0]Você gostaria de pedir um?[n][w][e]

[msg JUICE_SHOP_THANKS [Employee]]
[s][vp 8 2 1 0 2 0]Muito obrigado! Esperamos vê-lo novamente[n]muito, muito em breve![n][w][e]

[msg JUICE_SHOP_NOT_BUY [Employee]]
[s][vp 8 2 1 0 2 0]Por favor, venha de novo![n][w][e]

[msg JUICE_SHOP_SOLDOUT [Employee]]
[s][vp 8 2 1 0 2 0]Estou muito desculpe... estamos vendidos[n]atualmente... tudo.[n][w][e]

[msg MSG_01030108_MAKOTO_01 [Sae]]
[s][bup 0 105 0 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 25 1 65535 0 0]Ah...[n][f 1 3 65535][w][e]

[msg MSG_01030108_MAKOTO_02 [Makoto]]
[s][bup 0 6 0 6 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 25 1 65535 0 0]Ah, [f 4 2]-que coincidência.[n][f 1 3 65535][w][e]

[msg MSG_GRT_main_All_001_01_ [Makoto]]
[s][vp 9 2 65535 38752 0 0]Nada de bom acontece...[n]Alguém deveria fazer algo sobre isso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_02_ [Makoto]]
[s][vp 9 2 65535 41352 0 0]Espero que nada estranho assim aconteça de[n]novo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_03_ [Makoto]]
[s][vp 9 2 65535 38355 0 0]Eles estão criando esse pânico, e ninguém[n]sabe o porquê.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_04_ [Makoto]]
[s][vp 9 2 65535 41655 0 0]Essas pessoas estão enlouquecendo por causa[n]do estresse?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_05_ [Makoto]]
[s][vp 9 2 65535 38805 0 0]Ugh, é uma dor que está tendo que ir[n]trabalhar.[n]Talvez eu chame de doente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_06_ [Makoto]]
[s][vp 9 2 65535 41852 0 0]É tão chato aqui... eu quero ir para algum[n]lugar divertido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_07_ [Makoto]]
[s][vp 9 2 65535 46052 0 0]Por que nada de bom acontece? Alguém faz[n]algo sobre tudo isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_08_ [Makoto]]
[s][vp 9 2 65535 45152 0 0]Tudo é tão chato...[n]Quando algo bom vai acontecer?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_09_ [Makoto]]
[s][vp 9 2 65535 37909 0 0]Eu quero ficar rico rápido... alguma boa[n]oportunidade por aí?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_10_ [Makoto]]
[s][vp 9 2 65535 38710 0 0]Ugh, é uma dor que está tendo que ir[n]trabalhar.[n]Talvez eu chame de doente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_11_ [Makoto]]
[s][vp 9 2 65535 44755 0 0]Nada vai mudar... então eu me recuso a levar[n]as coisas a sério.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_12_ [Makoto]]
[s][vp 9 2 65535 41555 0 0]Tudo é tão chato...[n]Quando algo bom vai acontecer?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_13_ [Makoto]]
[s][vp 9 2 65535 37552 0 0]Ugh, é uma dor que está tendo que ir[n]trabalhar.[n]Talvez eu chame de doente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_14_ [Makoto]]
[s][vp 9 2 65535 43952 0 0]Nada de bom acontece... alguém deveria fazer[n]algo sobre isso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_15_ [Makoto]]
[s][vp 9 2 65535 39305 0 0]Tudo é tão chato...[n]Quando algo bom vai acontecer?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_16_ [Makoto]]
[s][vp 9 2 65535 41110 0 0]Nada vai mudar... então eu me recuso a levar[n]as coisas a sério.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_01_ [Makoto]]
[s][vp 9 2 65535 37902 0 0]As pessoas ainda não sabem o que causou[n]isso? Você deve estar brincando comigo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_02_ [Makoto]]
[s][vp 9 2 65535 42709 0 0]As vendas continuam caindo...[n]Todo mundo é tão inútil...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_03_ [Makoto]]
[s][vp 9 2 65535 40605 0 0]Ouvi dizer que eles voam em uma raiva, como[n]se estivessem possuídos por algo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_04_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]Não importa quem é, alguém se apresse e faça[n]algo sobre tudo isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_05_ [Makoto]]
[s][vp 9 2 65535 38201 0 0]É tão chato aqui... eu quero ir para algum[n]lugar divertido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_06_ [Makoto]]
[s][vp 9 2 65535 41855 0 0]Os políticos são os piores.[n]Não importa quem está no poder, eles são[n]iguais.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_07_ [Makoto]]
[s][vp 9 2 65535 41005 0 0]Nada vai mudar... então eu me recuso a levar[n]as coisas a sério.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_08_ [Makoto]]
[s][vp 9 2 65535 46052 0 0]Este mundo é terrível...[n]Quem é o culpado por isso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_09_ [Makoto]]
[s][vp 9 2 65535 39052 0 0]Quando sei que algo vai acontecer, não posso[n]deixar de ficar estressado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_10_ [Makoto]]
[s][vp 9 2 65535 43055 0 0]As pessoas não estão exagerando para tudo[n]isso? Tudo vai ser resolvido[n]eventualmente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_11_ [Makoto]]
[s][vp 9 2 65535 42955 0 0]Tem que ser por causa de fantasmas. Isso não[n]é tão assustador?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_12_ [Makoto]]
[s][vp 9 2 65535 43454 0 0]Então, ninguém sabe o que causou esse[n]estranho acidente?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_13_ [Makoto]]
[s][vp 9 2 65535 42659 0 0]Este mundo é terrível...[n]Quem é o culpado por isso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_14_ [Makoto]]
[s][vp 9 2 65535 40702 0 0]Todos os dias, me sinto tão entediado. Eu me[n]pergunto se há algo divertido para fazer...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_15_ [Makoto]]
[s][vp 9 2 65535 39360 0 0]É difícil ficar motivado quando não consigo[n]um aumento...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_16_ [Makoto]]
[s][vp 9 2 65535 43802 0 0]As vendas estão caindo...[n]É porque a economia não está bem, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_01_ [Makoto]]
[s][vp 9 2 65535 39109 0 0]Pena que o medalhista de ouro acabou sendo[n]um pervertido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_02_ [Makoto]]
[s][vp 9 2 65535 43405 0 0]Nossa, se ele acabaria confessando de[n]qualquer maneira, por que fazer isso em[n]primeiro lugar?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_03_ [Makoto]]
[s][vp 9 2 65535 38652 0 0]Ele aproveitou as meninas do time... tão[n]nojento...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_04_ [Makoto]]
[s][vp 9 2 65535 40051 0 0]Não acredito que ele assediou sexualmente[n]aquelas garotas. Tch, abusando de poder[n]assim...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_05_ [Makoto]]
[s][vp 9 2 65535 37904 0 0]Um professor foi preso por ser um[n]pervertido? Você é de verdade!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_06_ [Makoto]]
[s][vp 9 2 65535 45301 0 0]Nossa, se ele acabaria confessando de[n]qualquer maneira, por que fazer isso em[n]primeiro lugar?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_07_ [Makoto]]
[s][vp 9 2 65535 40052 0 0]Ele aproveitou as meninas do time... tão[n]nojento...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_08_ [Makoto]]
[s][vp 9 2 65535 44254 0 0]Ele confessou seus crimes e tudo mais, mas[n]ainda não entendo exatamente o que[n]aconteceu.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_09_ [Makoto]]
[s][vp 9 2 65535 38152 0 0]Nossa, se ele acabaria confessando de[n]qualquer maneira, por que fazer isso em[n]primeiro lugar?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_10_ [Makoto]]
[s][vp 9 2 65535 42703 0 0]Pena que o medalhista de ouro acabou sendo[n]um pervertido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_11_ [Makoto]]
[s][vp 9 2 65535 46351 0 0]Não acredito que ele assediou sexualmente[n]aquelas garotas...[n]Tal abuso de poder...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_12_ [Makoto]]
[s][vp 9 2 65535 44751 0 0]Ele aproveitou as meninas do time... tão[n]nojento...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_13_ [Makoto]]
[s][vp 9 2 65535 38152 0 0]Medalhista de ouro ou não, ele terminou.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_14_ [Makoto]]
[s][vp 9 2 65535 45304 0 0]Nossa, se ele acabaria confessando de[n]qualquer maneira, por que fazer isso em[n]primeiro lugar?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_15_ [Makoto]]
[s][vp 9 2 65535 46405 0 0]Por que ele confessou de repente? Eu não[n]entendo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_16_ [Makoto]]
[s][vp 9 2 65535 41001 0 0]Ele aproveitou as meninas do time... tão[n]nojento...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_01_ [Makoto]]
[s][vp 9 2 65535 39105 0 0]Não estou realmente interessado em arte, mas[n]parece que ele é famoso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_02_ [Makoto]]
[s][vp 9 2 65535 45650 0 0]Eu o vi na TV. Sua arte é muito boa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_03_ [Makoto]]
[s][vp 9 2 65535 41404 0 0]Ouvi dizer que ele é conhecido em todo o[n]mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_04_ [Makoto]]
[s][vp 9 2 65535 46053 0 0]Eu vi suas pinturas na TV.[n]Eles foram bastante impressionantes.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_05_ [Makoto]]
[s][vp 9 2 65535 38200 0 0]Os artistas devem ganhar muito dinheiro.[n]Talvez eu também se torne um artista...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_06_ [Makoto]]
[s][vp 9 2 65535 45504 0 0]Eu o vi na TV. Sua arte é muito boa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_07_ [Makoto]]
[s][vp 9 2 65535 45753 0 0]Ele é tão popular. Talvez eu deva ser um[n]artista também.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_08_ [Makoto]]
[s][vp 9 2 65535 41300 0 0]Seu trabalho é muito aclamado em todo o[n]mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_09_ [Makoto]]
[s][vp 9 2 65535 46305 0 0]Não estou interessado em arte e esse tipo de[n]coisa, mas ouvi dizer que ele é muito[n]famoso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_10_ [Makoto]]
[s][vp 9 2 65535 46303 0 0]Eu o vi na TV. Sua arte é muito boa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_11_ [Makoto]]
[s][vp 9 2 65535 38259 0 0]Aposto que o trabalho dele é vendido por[n]muito...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_12_ [Makoto]]
[s][vp 9 2 65535 41550 0 0]Seu trabalho é muito aclamado em todo o[n]mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_13_ [Makoto]]
[s][vp 9 2 65535 45654 0 0]Você já ouviu falar de Madarame?[n]Aparentemente, ele é um artista famoso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_14_ [Makoto]]
[s][vp 9 2 65535 45504 0 0]Eu o vi na TV. Sua arte é muito boa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_15_ [Makoto]]
[s][vp 9 2 65535 40854 0 0]Ouvi dizer que ele é conhecido em todo o[n]mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_16_ [Makoto]]
[s][vp 9 2 65535 40410 0 0]Aposto que o artista está fazendo banco...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_01_ [Makoto]]
[s][vp 9 2 65535 42255 0 0]Você não acha que é culpa da vítima ser[n]enganada em primeiro lugar?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_02_ [Makoto]]
[s][vp 9 2 65535 41352 0 0]Eu sei que é perigoso aqui, mas tenho que[n]começar a trabalhar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_03_ [Makoto]]
[s][vp 9 2 65535 44502 0 0]Ouvi dizer que está ficando inseguro.[n]Espero que alguém tenha uma maneira de[n]resolver isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_04_ [Makoto]]
[s][vp 9 2 65535 46105 0 0]Eu me pergunto se toda essa conversa sobre[n]fraudes e ameaças é verdadeira...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_05_ [Makoto]]
[s][vp 9 2 65535 45802 0 0]Ouvi dizer que, depois de clicar nele, você[n]terminou para...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_06_ [Makoto]]
[s][vp 9 2 65535 41852 0 0]Então, ouvi dizer que o grupo criminal em[n]Shibuya é realmente muito enorme...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_07_ [Makoto]]
[s][vp 9 2 65535 41452 0 0]Esses rumores sobre extorsão e golpes são[n]verdadeiros?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_08_ [Makoto]]
[s][vp 9 2 65535 43852 0 0]Sou só eu, ou há mais pessoas de aparência[n]obscura por aqui ultimamente...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_09_ [Makoto]]
[s][vp 9 2 65535 43704 0 0]Só foi recentemente que ficou inseguro em[n]Shibuya, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_10_ [Makoto]]
[s][vp 9 2 65535 38502 0 0]Ouvi dizer que as vítimas são principalmente[n]jovens...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_11_ [Makoto]]
[s][vp 9 2 65535 44759 0 0]Eu tenho outro e-mail estranho...[n]Eles são tão persistentes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_12_ [Makoto]]
[s][vp 9 2 65535 40052 0 0]Você acha que essas ameaças são reais...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_13_ [Makoto]]
[s][vp 9 2 65535 38204 0 0]Ouvi dizer que uma grande organização está[n]por trás de tudo isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_14_ [Makoto]]
[s][vp 9 2 65535 39152 0 0]Ouvi dizer que você terminou se eles[n]segmentam você...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_15_ [Makoto]]
[s][vp 9 2 65535 40652 0 0]Às vezes eu vejo bandidos saindo por aqui...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_16_ [Makoto]]
[s][vp 9 2 65535 37952 0 0]Quando eu saio, eu simplesmente não consigo[n]relaxar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_01_ [Makoto]]
[s][vp 9 2 65535 44405 0 0]Depois de ter um colapso psicótico, ouço[n]você ficar com o cérebro morto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_02_ [Makoto]]
[s][vp 9 2 65535 44704 0 0]Esses casos aconteceram um após o outro.[n]Todas essas coincidências também foram?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_03_ [Makoto]]
[s][vp 9 2 65535 38602 0 0]Espero não ter que ver mais desses[n]incidentes estranhos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_04_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_05_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_06_ [Makoto]]
[s][vp 9 2 65535 39155 0 0]Então, tudo isso sobre as pessoas perdendo a[n]consciência...[n]Foi apenas uma mentira?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_07_ [Makoto]]
[s][vp 9 2 65535 41154 0 0]Talvez não tenhamos que nos preocupar mais[n]com esses acidentes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_08_ [Makoto]]
[s][vp 9 2 65535 41155 0 0]Aposto que as pessoas estavam apenas[n]inventando as coisas sobre esses[n]desligamentos mentais.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_09_ [Makoto]]
[s][vp 9 2 65535 41610 0 0]Parece que esses incidentes estranhos[n]simplesmente pararam de acontecer de[n]repente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_10_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_11_ [Makoto]]
[s][vp 9 2 65535 43200 0 0]Acho que menos pessoas estão por perto para[n]causar esses incidentes agora...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_12_ [Makoto]]
[s][vp 9 2 65535 39655 0 0]Muitos desses acidentes estranhos estavam[n]acontecendo até pouco tempo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_13_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_14_ [Makoto]]
[s][vp 9 2 65535 40705 0 0]Talvez isso aconteça novamente, exatamente[n]quando estamos prestes a esquecê-los...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_15_ [Makoto]]
[s][vp 9 2 65535 45104 0 0]Esse acidente de metrô não aconteceu no[n]início de abril?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_16_ [Makoto]]
[s][vp 9 2 65535 39709 0 0]Quem causa os acidentes deve ser o culpado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_01_ [Makoto]]
[s][vp 9 2 65535 42554 0 0]Talvez eu fique famoso se eu me tornar o[n]aluno dele![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_02_ [Makoto]]
[s][vp 9 2 65535 41505 0 0]Arte? Não estou realmente interessado[n]nisso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_03_ [Makoto]]
[s][vp 9 2 65535 45754 0 0]Ouvi dizer que a exposição de um artista[n]está sendo realizada em Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_04_ [Makoto]]
[s][vp 9 2 65535 40050 0 0]Foi tão impressionante![n]Seu trabalho é incrível![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_05_ [Makoto]]
[s][vp 9 2 65535 38200 0 0]É bom sair e experimentar arte![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_06_ [Makoto]]
[s][vp 9 2 65535 45504 0 0]Eu me pergunto se devo conferir a exposição[n]de Madarame...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_07_ [Makoto]]
[s][vp 9 2 65535 46054 0 0]Oh, o artista que pintou o "Sayuri"? Eu ouvi[n]falar dele![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_08_ [Makoto]]
[s][vp 9 2 65535 45154 0 0]Ele age tudo digno, mas ele não parece meio[n]suspeito para você de alguma forma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_09_ [Makoto]]
[s][vp 9 2 65535 39054 0 0]Eu tentei conferir o local, mas a multidão[n]era enorme.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_10_ [Makoto]]
[s][vp 9 2 65535 38700 0 0]Ele fez muitas peças para apenas um cara.[n]Isso faz parte de seu talento?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_11_ [Makoto]]
[s][vp 9 2 65535 43354 0 0]Ouvi dizer que as pessoas não conseguem[n]ingressos porque ele é tão popular.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_12_ [Makoto]]
[s][vp 9 2 65535 40653 0 0]Se a arte dele é tão boa, não poderia doer[n]ir vê-la.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_13_ [Makoto]]
[s][vp 9 2 65535 37853 0 0]A exposição já começou?[n]Acho que vou ir. Isso vai me dar algo para[n]falar.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_14_ [Makoto]]
[s][vp 9 2 65535 42050 0 0]Ele é um artista famoso- o orgulho do Japão![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_15_ [Makoto]]
[s][vp 9 2 65535 41304 0 0]Se for uma pintura de um artista famoso,[n]tenho certeza de que vai ter um preço alto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_16_ [Makoto]]
[s][vp 9 2 65535 45110 0 0]Você sabe, eu invejo pessoas com talento.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_01_ [Makoto]]
[s][vp 9 2 65535 43753 0 0]Essa conferência de imprensa foi bastante[n]hilária.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_02_ [Makoto]]
[s][vp 9 2 65535 46002 0 0]Abusando de seus alunos...[n]Que terrível...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_03_ [Makoto]]
[s][vp 9 2 65535 39651 0 0]Então, aquele artista enganou a todos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_04_ [Makoto]]
[s][vp 9 2 65535 46102 0 0]Eu quero um reembolso dessa taxa de entrada[n]ridícula![n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_05_ [Makoto]]
[s][vp 9 2 65535 39804 0 0]Não faz você se perguntar por que ele fez[n]isso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_06_ [Makoto]]
[s][vp 9 2 65535 45505 0 0]Era errado deixá-lo até agora.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_07_ [Makoto]]
[s][vp 9 2 65535 39705 0 0]Eu me pergunto por que ele de repente se[n]arrepende disso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_08_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]Eu me sinto estúpido por apoiá-lo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_09_ [Makoto]]
[s][vp 9 2 65535 46304 0 0]Ele é o pior. Explorando seus alunos assim...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_10_ [Makoto]]
[s][vp 9 2 65535 40551 0 0]Eu estava totalmente enganado. Ele nem era[n]um artista de verdade...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_11_ [Makoto]]
[s][vp 9 2 65535 42604 0 0]Ouvi falar de outras pessoas "confessando[n]seus crimes" de repente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_12_ [Makoto]]
[s][vp 9 2 65535 38055 0 0]É tão estúpido... as pessoas não para de[n]falar sobre esses "ladrões Phantom"...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_13_ [Makoto]]
[s][vp 9 2 65535 40355 0 0]Então, todos devem estar tramando algo[n]sombrio atrás de nossas costas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_14_ [Makoto]]
[s][vp 9 2 65535 45500 0 0]Essa conferência de imprensa... o homem deve[n]estar fora de sua mente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_15_ [Makoto]]
[s][vp 9 2 65535 39354 0 0]É verdade que alguém disse que isso[n]aconteceria assim?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_16_ [Makoto]]
[s][vp 9 2 65535 40055 0 0]Então ele estava ganhando dinheiro[n]desonestamente o tempo todo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_01_ [Makoto]]
[s][vp 9 2 65535 38702 0 0]Shibuya vai ficar bem...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_02_ [Makoto]]
[s][vp 9 2 65535 43759 0 0]Esses rumores sobre extorsão e golpes são[n]verdadeiros?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_03_ [Makoto]]
[s][vp 9 2 65535 40952 0 0]Esses rumores sobre extorsão e golpes são[n]verdadeiros?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_04_ [Makoto]]
[s][vp 9 2 65535 43852 0 0]Sou só eu, ou há mais pessoas de aparência[n]obscura por aqui ultimamente...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_05_ [Makoto]]
[s][vp 9 2 65535 39752 0 0]Ninguém vem mais para Shibuya porque todos[n]estão com medo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_06_ [Makoto]]
[s][vp 9 2 65535 41852 0 0]Eu sinto que há muito mais pessoas com[n]aparência obscura ultimamente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_07_ [Makoto]]
[s][vp 9 2 65535 41004 0 0]Esses rumores sobre extorsão e golpes são[n]verdadeiros?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_08_ [Makoto]]
[s][vp 9 2 65535 46059 0 0]Sou só eu, ou há mais pessoas de aparência[n]obscura por aqui ultimamente...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_09_ [Makoto]]
[s][vp 9 2 65535 38204 0 0]Ouvi um boato de que você pode ser convocado[n]para Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_10_ [Makoto]]
[s][vp 9 2 65535 42204 0 0]Ouvi dizer que as pessoas estão recebendo[n]e-mails que são realmente golpes de[n]phishing.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_11_ [Makoto]]
[s][vp 9 2 65535 43352 0 0]Todo mundo está com muito medo de visitar[n]Shibuya agora...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_12_ [Makoto]]
[s][vp 9 2 65535 43854 0 0]Golpes de phishing? Isso é terrível![n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_13_ [Makoto]]
[s][vp 9 2 65535 40555 0 0]Ouvi um boato de que você pode ser convocado[n]para Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_14_ [Makoto]]
[s][vp 9 2 65535 39151 0 0]Ouvi dizer que as pessoas estão recebendo[n]e-mails que são realmente golpes de[n]phishing.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_15_ [Makoto]]
[s][vp 9 2 65535 42912 0 0]Às vezes vejo bandidos por aqui...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_16_ [Makoto]]
[s][vp 9 2 65535 40802 0 0]Golpes de phishing? Isso é terrível![n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_01_ [Makoto]]
[s][vp 9 2 65535 38100 0 0]Alguns deles também foram para Madarame,[n]certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_02_ [Makoto]]
[s][vp 9 2 65535 41505 0 0]Não há como os ladrões fantasmas realmente[n]existem...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_03_ [Makoto]]
[s][vp 9 2 65535 40604 0 0]Tudo bem, desde que isso signifique que as[n]coisas ficam quietas por aqui, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_04_ [Makoto]]
[s][vp 9 2 65535 44255 0 0]Os ladrões fantasmas, hein?[n]Você acha que eles realmente existem...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_05_ [Makoto]]
[s][vp 9 2 65535 40304 0 0]Seria interessante se esse cartão de visita[n]fosse real...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_06_ [Makoto]]
[s][vp 9 2 65535 38455 0 0]Não há como os ladrões fantasmas realmente[n]existem...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_07_ [Makoto]]
[s][vp 9 2 65535 44254 0 0]Minha amiga disse que viu um daqueles[n]cartões de visita![n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_08_ [Makoto]]
[s][vp 9 2 65535 45755 0 0]Os ladrões fantasmas, hein?[n]Você acha que eles realmente existem...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_09_ [Makoto]]
[s][vp 9 2 65535 44904 0 0]Toda essa conversa sobre ladrões Phantom é[n]tão estúpida...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_10_ [Makoto]]
[s][vp 9 2 65535 40355 0 0]Esse Kaneshiro é uma pessoa má?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_11_ [Makoto]]
[s][vp 9 2 65535 42755 0 0]Um cartão de chamada Phantom Thief? Essa é[n]apenas uma daquelas lendas urbanas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_12_ [Makoto]]
[s][vp 9 2 65535 39005 0 0]Os ladrões fantasmas, hein?[n]Você acha que eles realmente existem...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_13_ [Makoto]]
[s][vp 9 2 65535 42554 0 0]Ouvi dizer que eles foram postados em todos[n]os carros e outras coisas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_14_ [Makoto]]
[s][vp 9 2 65535 38450 0 0]Não há como os ladrões fantasmas realmente[n]existem...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_15_ [Makoto]]
[s][vp 9 2 65535 39654 0 0]Ouvi dizer que eles foram postados em todos[n]os carros e outras coisas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_16_ [Makoto]]
[s][vp 9 2 65535 43455 0 0]Os ladrões fantasmas, hein?[n]Você acha que eles realmente existem...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_01_ [Makoto]]
[s][vp 9 2 65535 37508 0 0]Vamos para Shibuya![n]Está tudo bem lá agora![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_02_ [Makoto]]
[s][vp 9 2 65535 41204 0 0]Parece que as coisas serão mais seguras por[n]aqui a partir de agora.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_03_ [Makoto]]
[s][vp 9 2 65535 38600 0 0]Estou tão feliz que Shibuya está em paz[n]novamente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_04_ [Makoto]]
[s][vp 9 2 65535 41303 0 0]Que alivio![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_05_ [Makoto]]
[s][vp 9 2 65535 38204 0 0]Estou tão feliz que todos esses criminosos[n]se foram agora![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_06_ [Makoto]]
[s][vp 9 2 65535 45300 0 0]O chefe por trás dessa organização criminosa[n]finalmente foi presa![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_07_ [Makoto]]
[s][vp 9 2 65535 41454 0 0]Parece que as coisas finalmente se acalmam[n]por aqui![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_08_ [Makoto]]
[s][vp 9 2 65535 40050 0 0]Parece seguro andar por Shibuya novamente![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_09_ [Makoto]]
[s][vp 9 2 65535 39450 0 0]Agora não precisamos nos preocupar quando[n]vamos para Shibuya![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_10_ [Makoto]]
[s][vp 9 2 65535 42550 0 0]Eu não tinha certeza do que ia acontecer,[n]mas estou feliz que eles pudessem prendê-lo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_11_ [Makoto]]
[s][vp 9 2 65535 42953 0 0]Podemos sair em Shibuya agora que está[n]seguro novamente![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_12_ [Makoto]]
[s][vp 9 2 65535 41304 0 0]Estou tão feliz que Shibuya está pacífica[n]novamente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_13_ [Makoto]]
[s][vp 9 2 65535 41700 0 0]É seguro viver em Shibuya novamente![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_14_ [Makoto]]
[s][vp 9 2 65535 45503 0 0]Eu não tinha certeza do que ia acontecer,[n]mas estou feliz que eles pudessem prendê-lo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_15_ [Makoto]]
[s][vp 9 2 65535 46203 0 0]Não precisamos mais nos preocupar, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_16_ [Makoto]]
[s][vp 9 2 65535 42000 0 0]Estou muito feliz que Shibuya está pacífico[n]novamente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_01_ [Makoto]]
[s][vp 9 2 65535 37856 0 0]Você viu as notícias?[n]Aparentemente, foram os ladrões fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_02_ [Makoto]]
[s][vp 9 2 65535 41954 0 0]Então tudo correu de acordo com o cartão de[n]visita dos ladrões Phantom...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_03_ [Makoto]]
[s][vp 9 2 65535 40954 0 0]Você viu as notícias?[n]Aparentemente, os ladrões fantasmas fizeram[n]isso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_04_ [Makoto]]
[s][vp 9 2 65535 43854 0 0]É verdade que foram os ladrões fantasmas que[n]resolveram esse incidente!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_05_ [Makoto]]
[s][vp 9 2 65535 38504 0 0]Então os ladrões fantasmas derrubaram[n]Kaneshiro, não?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_06_ [Makoto]]
[s][vp 9 2 65535 38456 0 0]Esses caras são impressionantes![n]Eles estão fazendo um trabalho melhor do que[n]a polícia![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_07_ [Makoto]]
[s][vp 9 2 65535 45156 0 0]Então esse cartão de visita não era apenas[n]uma brincadeira, afinal![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_08_ [Makoto]]
[s][vp 9 2 65535 39704 0 0]A notícia estava dizendo que os ladrões[n]fantasmas poderiam realmente estar[n]envolvidos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_09_ [Makoto]]
[s][vp 9 2 65535 39800 0 0]Isso seria incrível se fosse realmente os[n]ladrões fantasmas que fizeram isso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_10_ [Makoto]]
[s][vp 9 2 65535 44906 0 0]Esses caras são impressionantes![n]Eles estão fazendo um trabalho melhor do que[n]a polícia![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_11_ [Makoto]]
[s][vp 9 2 65535 44456 0 0]Foi exatamente como o cartão de visita do[n]Phantom Thieves disse que sim![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_12_ [Makoto]]
[s][vp 9 2 65535 41804 0 0]A notícia estava dizendo que os ladrões[n]fantasmas poderiam realmente estar[n]envolvidos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_13_ [Makoto]]
[s][vp 9 2 65535 38756 0 0]Você vê essa coisa nas notícias? Parece que[n]foram os ladrões fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_14_ [Makoto]]
[s][vp 9 2 65535 39153 0 0]Então tudo correu de acordo com o cartão de[n]visita dos ladrões Phantom...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_15_ [Makoto]]
[s][vp 9 2 65535 39356 0 0]Você vê essa coisa nas notícias? Parece que[n]foram os ladrões fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_16_ [Makoto]]
[s][vp 9 2 65535 39004 0 0]É verdade que foram os ladrões fantasmas que[n]resolveram esse incidente!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_01_ [Makoto]]
[s][vp 9 2 65535 38405 0 0]Medjed parece terrivelmente consciente dos[n]ladrões fantasmas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_02_ [Makoto]]
[s][vp 9 2 65535 41504 0 0]Que tipo de grupo é medjed, afinal?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_03_ [Makoto]]
[s][vp 9 2 65535 37700 0 0]Estou meio que do lado do Phantom Thieves.[n]Eles são como Robin Hoods modernos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_04_ [Makoto]]
[s][vp 9 2 65535 41153 0 0]Eles estão falando muito lixo.[n]Eu me pergunto o que os ladrões fantasmas[n]farão sobre isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_05_ [Makoto]]
[s][vp 9 2 65535 40304 0 0]Que tipo de grupo até é medjed?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_06_ [Makoto]]
[s][vp 9 2 65535 45504 0 0]Eu me pergunto o que os ladrões fantasmas[n]farão sobre esses hackers.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_07_ [Makoto]]
[s][vp 9 2 65535 38354 0 0]Eu me pergunto por que Medjed está mirando[n]os ladrões fantasmas?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_08_ [Makoto]]
[s][vp 9 2 65535 46056 0 0]Eu me pergunto o que os ladrões fantasmas[n]farão depois de serem chamados assim.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_09_ [Makoto]]
[s][vp 9 2 65535 39104 0 0]Você vê as notícias sobre essa declaração? O[n]que os ladrões fantasmas farão?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_10_ [Makoto]]
[s][vp 9 2 65535 42554 0 0]Os ladrões Phantom cuidarão deles, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_11_ [Makoto]]
[s][vp 9 2 65535 45104 0 0]Eu me pergunto o que os ladrões Phantom vão[n]fazer sobre Medjed...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_12_ [Makoto]]
[s][vp 9 2 65535 38254 0 0]Eles estão falando muito lixo.[n]Eu me pergunto o que os ladrões fantasmas[n]farão sobre isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_13_ [Makoto]]
[s][vp 9 2 65535 39804 0 0]Você vê as notícias sobre essa declaração? O[n]que os ladrões fantasmas farão?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_14_ [Makoto]]
[s][vp 9 2 65535 38452 0 0]Eu me pergunto o que os ladrões fantasmas[n]farão sobre esses hackers.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_15_ [Makoto]]
[s][vp 9 2 65535 38654 0 0]Os ladrões Phantom são os únicos que podem[n]derrubar esses hackers![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_16_ [Makoto]]
[s][vp 9 2 65535 44254 0 0]Eles estão falando muito lixo.[n]Eu me pergunto o que os ladrões fantasmas[n]farão sobre isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_01_ [Makoto]]
[s][vp 9 2 65535 39057 0 0]Vamos lá, ladrões Phantom.[n]Diga algo já...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_02_ [Makoto]]
[s][vp 9 2 65535 41756 0 0]Como os ladrões fantasmas vão lutar contra[n]esses hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_03_ [Makoto]]
[s][vp 9 2 65535 42462 0 0]O Japão está sendo alvo.[n]Eu realmente espero que eles façam algo a[n]respeito.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_04_ [Makoto]]
[s][vp 9 2 65535 41455 0 0]Eles têm que fazer algo antes que algo ruim[n]aconteça conosco...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_05_ [Makoto]]
[s][vp 9 2 65535 41504 0 0]O que os ladrões Phantom podem fazer contra[n]hackers...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_06_ [Makoto]]
[s][vp 9 2 65535 41856 0 0]O que os ladrões fantasmas estão fazendo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_07_ [Makoto]]
[s][vp 9 2 65535 43852 0 0]O Japão está sendo alvo.[n]Eu realmente espero que eles façam algo a[n]respeito.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_08_ [Makoto]]
[s][vp 9 2 65535 46055 0 0]Eles não vão nos prejudicar se os ladrões[n]fantasmas revelarem suas verdadeiras[n]identidades, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_09_ [Makoto]]
[s][vp 9 2 65535 46303 0 0]O que os ladrões fantasmas podem fazer[n]contra hackers...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_10_ [Makoto]]
[s][vp 9 2 65535 40557 0 0]Vamos lá, ladrões Phantom.[n]Diga algo já...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_11_ [Makoto]]
[s][vp 9 2 65535 43201 0 0]Os ladrões Phantom com certeza estão ficando[n]quietos.[n]O que vai acontecer...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_12_ [Makoto]]
[s][vp 9 2 65535 43455 0 0]Eles não vão nos prejudicar se os ladrões[n]fantasmas revelarem suas verdadeiras[n]identidades, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_13_ [Makoto]]
[s][vp 9 2 65535 38754 0 0]O que os ladrões fantasmas podem fazer[n]contra hackers...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_14_ [Makoto]]
[s][vp 9 2 65535 42054 0 0]Vamos lá, ladrões Phantom.[n]Diga algo já...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_15_ [Makoto]]
[s][vp 9 2 65535 40804 0 0]O Japão está sendo alvo.[n]Eu realmente espero que eles façam algo a[n]respeito.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_16_ [Makoto]]
[s][vp 9 2 65535 41805 0 0]Eles não vão nos prejudicar se os ladrões[n]fantasmas revelarem suas verdadeiras[n]identidades, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_01_ [Makoto]]
[s][vp 9 2 65535 40754 0 0]Eu ouço os ladrões fantasmas realmente o[n]fizeram![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_02_ [Makoto]]
[s][vp 9 2 65535 41950 0 0]Estou feliz que tudo tenha sido resolvido[n]antes que qualquer dano fosse feito...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_03_ [Makoto]]
[s][vp 9 2 65535 44456 0 0]Parece que o site de Medjed foi assumido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_04_ [Makoto]]
[s][vp 9 2 65535 44254 0 0]Estou feliz que tudo tenha sido resolvido[n]sem que ninguém se machuque.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_05_ [Makoto]]
[s][vp 9 2 65535 43700 0 0]É absolutamente incrível que eles derrotaram[n]Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_06_ [Makoto]]
[s][vp 9 2 65535 41850 0 0]Estou feliz que tudo tenha sido resolvido[n]antes que qualquer dano fosse feito...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_07_ [Makoto]]
[s][vp 9 2 65535 41004 0 0]Parece que o site de Medjed foi assumido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_08_ [Makoto]]
[s][vp 9 2 65535 46100 0 0]Estou tão feliz que está tudo bem agora! É[n]tudo graças aos ladrões Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_09_ [Makoto]]
[s][vp 9 2 65535 37606 0 0]Isso significa que os ladrões fantasmas nos[n]salvaram, não é?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_10_ [Makoto]]
[s][vp 9 2 65535 38706 0 0]É absolutamente incrível que eles derrotaram[n]Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_11_ [Makoto]]
[s][vp 9 2 65535 42800 0 0]Ouvi dizer que o site de Medjed foi fechado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_12_ [Makoto]]
[s][vp 9 2 65535 46106 0 0]Não acredito que eles foram capazes de[n]derrotar um grupo de hackers internacionais![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_13_ [Makoto]]
[s][vp 9 2 65535 40106 0 0]Isso significa que os ladrões fantasmas nos[n]salvaram, não é?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_14_ [Makoto]]
[s][vp 9 2 65535 42053 0 0]É absolutamente incrível que eles derrotaram[n]Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_15_ [Makoto]]
[s][vp 9 2 65535 38004 0 0]Os ladrões fantasmas fizeram isso, hein!?[n]Isso é incrível![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_16_ [Makoto]]
[s][vp 9 2 65535 38553 0 0]Não acredito que eles foram capazes de[n]derrotar um grupo de hackers internacionais![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_01_ [Makoto]]
[s][vp 9 2 65535 39756 0 0]Os ladrões fantasmas estavam bem o tempo[n]todo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_02_ [Makoto]]
[s][vp 9 2 65535 43400 0 0]Esses ladrões fantasmas são bastante[n]impressionantes![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_03_ [Makoto]]
[s][vp 9 2 65535 38900 0 0]Não acredito que eles derrotaram esses[n]hackers.[n]Eles são tão incríveis![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_04_ [Makoto]]
[s][vp 9 2 65535 41656 0 0]Os ladrões fantasmas são justiça![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_05_ [Makoto]]
[s][vp 9 2 65535 45803 0 0]Os ladrões Phantom salvaram todo o Japão![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_06_ [Makoto]]
[s][vp 9 2 65535 39156 0 0]Eu pensei que estávamos condenados.[n]Viva os ladrões Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_07_ [Makoto]]
[s][vp 9 2 65535 40806 0 0]Tenho certeza de que as pessoas de outros[n]países devem ter ficado surpresas também...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_08_ [Makoto]]
[s][vp 9 2 65535 41650 0 0]Estamos salvos, tudo graças aos ladrões[n]Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_09_ [Makoto]]
[s][vp 9 2 65535 41904 0 0]Estou feliz por ter decidido apoiá-los![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_10_ [Makoto]]
[s][vp 9 2 65535 44950 0 0]Estou tão feliz que os ladrões fantasmas[n]estavam lá para nós![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_11_ [Makoto]]
[s][vp 9 2 65535 40206 0 0]Você precisa realmente respeitá-los por[n]poder derrubar Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_12_ [Makoto]]
[s][vp 9 2 65535 39006 0 0]Sou um grande fã dos ladrões Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_13_ [Makoto]]
[s][vp 9 2 65535 39800 0 0]Retirar o Medjed não é pouca coisa![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_14_ [Makoto]]
[s][vp 9 2 65535 40706 0 0]Estou tão feliz que os ladrões fantasmas[n]estavam lá para nós![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_15_ [Makoto]]
[s][vp 9 2 65535 39356 0 0]Parece que o Japão foi salvo, graças aos[n]ladrões Phantom.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_16_ [Makoto]]
[s][vp 9 2 65535 41000 0 0]Os ladrões Phantom são realmente incríveis![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_01_ [Makoto]]
[s][vp 9 2 65535 40103 0 0]Onde quer que você olhe, as pessoas estão[n]falando sobre os ladrões fantasmas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_02_ [Makoto]]
[s][vp 9 2 65535 44706 0 0]A sociedade está enlouquecendo com a febre[n]do ladrão fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_03_ [Makoto]]
[s][vp 9 2 65535 40606 0 0]Eu quero pedir que eles façam alguém mudar[n]de coração também![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_04_ [Makoto]]
[s][vp 9 2 65535 41306 0 0]Não há nada para se assustar com os ladrões[n]fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_05_ [Makoto]]
[s][vp 9 2 65535 44353 0 0]Livre-se de todas as pessoas más do mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_06_ [Makoto]]
[s][vp 9 2 65535 38458 0 0]Aqueles ladrões fantasmas realmente surgiram[n]do nada![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_07_ [Makoto]]
[s][vp 9 2 65535 44505 0 0]Muitas pessoas estão pulando no caminho de[n]banda do Phantom Thieves...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_08_ [Makoto]]
[s][vp 9 2 65535 41650 0 0]Tudo vai ficar bem enquanto os ladrões[n]fantasmas estiverem aqui![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_09_ [Makoto]]
[s][vp 9 2 65535 38206 0 0]Os ladrões Phantom estão cuidando de nós,[n]então ficaremos bem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_10_ [Makoto]]
[s][vp 9 2 65535 38405 0 0]É uma loucura o quão popular são os ladrões[n]Phantom...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_11_ [Makoto]]
[s][vp 9 2 65535 40606 0 0]Você está por trás dos tempos se não souber[n]sobre os ladrões Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_12_ [Makoto]]
[s][vp 9 2 65535 41153 0 0]Talvez eu envie um pedido para os ladrões[n]Phantom...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_13_ [Makoto]]
[s][vp 9 2 65535 39056 0 0]Os ladrões Phantom estão cuidando de nós,[n]então ficaremos bem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_14_ [Makoto]]
[s][vp 9 2 65535 41861 0 0]Onde quer que você olhe, as pessoas estão[n]falando sobre os ladrões fantasmas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_15_ [Makoto]]
[s][vp 9 2 65535 41656 0 0]Esses ladrões fantasmas são realmente[n]incríveis![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_16_ [Makoto]]
[s][vp 9 2 65535 39350 0 0]Enquanto esses ladrões fantasmas estiverem[n]por aí, o Japão ficará bem...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_01_ [Makoto]]
[s][vp 9 2 65535 40505 0 0]Eles os tratam como escravos, certo? Que[n]empresa terrível.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_02_ [Makoto]]
[s][vp 9 2 65535 41500 0 0]Pensar que a Okumura Foods estava explorando[n]seus funcionários...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_03_ [Makoto]]
[s][vp 9 2 65535 40255 0 0]Eu me sinto mal pelos trabalhadores lá...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_04_ [Makoto]]
[s][vp 9 2 65535 40051 0 0]Eles são os piores. É como se eles tratassem[n]seus funcionários como menos do que as[n]pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_05_ [Makoto]]
[s][vp 9 2 65535 38204 0 0]Pensar que a Okumura Foods estava explorando[n]seus funcionários...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_06_ [Makoto]]
[s][vp 9 2 65535 39151 0 0]Eles tratam seus funcionários como escravos,[n]certo? Isso é tão terrível.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_07_ [Makoto]]
[s][vp 9 2 65535 41001 0 0]Explorando seus próprios funcionários...[n]isso parece horrível...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_08_ [Makoto]]
[s][vp 9 2 65535 38601 0 0]Eles fizeram algumas coisas antiéticas nos[n]bastidores, certo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_09_ [Makoto]]
[s][vp 9 2 65535 40302 0 0]Parece que eles foram forçados a trabalhar[n]horários bastante insanos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_10_ [Makoto]]
[s][vp 9 2 65535 43002 0 0]Estou surpreso que esse assunto não tenha[n]sido tornado público até agora...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_11_ [Makoto]]
[s][vp 9 2 65535 40004 0 0]Meus pais ficaram chocados quando viram as[n]notícias também...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_12_ [Makoto]]
[s][vp 9 2 65535 42401 0 0]Eu não tinha ideia de que era por isso que a[n]Okumura Foods foi capaz de crescer tão[n]rapidamente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_13_ [Makoto]]
[s][vp 9 2 65535 44602 0 0]Ouvi dizer que eles foram forçados a[n]trabalhar muito por muitas horas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_14_ [Makoto]]
[s][vp 9 2 65535 43952 0 0]Estou surpreso que esse assunto não tenha[n]sido tornado público até agora...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_15_ [Makoto]]
[s][vp 9 2 65535 43454 0 0]Foi tão ruim que os tumultos começaram a[n]acontecer, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_16_ [Makoto]]
[s][vp 9 2 65535 39304 0 0]Eu não tinha ideia de que era por isso que a[n]Okumura Foods foi capaz de crescer tão[n]rapidamente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_01_ [Makoto]]
[s][vp 9 2 65535 40750 0 0]Eles não podem simplesmente fazer algum tipo[n]de reforma social ou algo assim?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_02_ [Makoto]]
[s][vp 9 2 65535 41203 0 0]Os ladrões Phantom continuarão tirando os[n]bandidos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_03_ [Makoto]]
[s][vp 9 2 65535 41403 0 0]Eu me pergunto quem eles escolherão como seu[n]próximo alvo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_04_ [Makoto]]
[s][vp 9 2 65535 41656 0 0]Se você vai consertar o mundo, basta chegar[n]a ele![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_05_ [Makoto]]
[s][vp 9 2 65535 38206 0 0]Você não acha que os ladrões fantasmas vão[n]tomar medidas em breve?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_06_ [Makoto]]
[s][vp 9 2 65535 43956 0 0]Tudo ficará bem, desde que deixe para os[n]ladrões fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_07_ [Makoto]]
[s][vp 9 2 65535 40404 0 0]Eu me pergunto quem eles escolherão como seu[n]próximo alvo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_08_ [Makoto]]
[s][vp 9 2 65535 41000 0 0]Os ladrões Phantom farão a diferença neste[n]mundo podre![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_09_ [Makoto]]
[s][vp 9 2 65535 44706 0 0]Tenho certeza de que os ladrões Phantom[n]farão algo a respeito![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_10_ [Makoto]]
[s][vp 9 2 65535 37553 0 0]Vamos lá, ladrões Phantom! Faça algo já[n]interessante![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_11_ [Makoto]]
[s][vp 9 2 65535 43103 0 0]Tudo ficará bem...[n]Os ladrões Phantom cuidarão disso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_12_ [Makoto]]
[s][vp 9 2 65535 46100 0 0]Não há nada a temer enquanto os ladrões[n]fantasmas estão aqui![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_13_ [Makoto]]
[s][vp 9 2 65535 41750 0 0]Tenho certeza de que os ladrões Phantom[n]farão algo a respeito![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_14_ [Makoto]]
[s][vp 9 2 65535 45306 0 0]Vamos lá, ladrões Phantom! Faça algo já[n]interessante![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_15_ [Makoto]]
[s][vp 9 2 65535 46203 0 0]Eu me pergunto quem eles escolherão como seu[n]próximo alvo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_16_ [Makoto]]
[s][vp 9 2 65535 39306 0 0]Os ladrões Phantom farão a diferença neste[n]mundo podre![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_01_ [Makoto]]
[s][vp 9 2 65535 42706 0 0]Outro cartão de visita chegou! Eu sabia- é[n]para Okumura![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_02_ [Makoto]]
[s][vp 9 2 65535 41051 0 0]Okumura terminou! Vá buscá-lo, Phantom[n]Thieves![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_03_ [Makoto]]
[s][vp 9 2 65535 44203 0 0]Eu estava esperando que eles enviem um[n]cartão de chamada![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_04_ [Makoto]]
[s][vp 9 2 65535 41003 0 0]Eu quero ver um pedido de desculpas ainda[n]mais dramático do que o que Madarame fez![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_05_ [Makoto]]
[s][vp 9 2 65535 39806 0 0]Tudo bem, ladrões Phantom![n]Vá em frente e não se segure![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_06_ [Makoto]]
[s][vp 9 2 65535 41856 0 0]Não o deixe escapar, ladrões Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_07_ [Makoto]]
[s][vp 9 2 65535 41000 0 0]Eu quero ver mais dessas punições[n]sensacionais![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_08_ [Makoto]]
[s][vp 9 2 65535 41161 0 0]Sim, ladrões Phantom![n]Chute suas bundas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_09_ [Makoto]]
[s][vp 9 2 65535 43156 0 0]Mostre-nos sua marca de justiça! Derrote[n]Okumura![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_10_ [Makoto]]
[s][vp 9 2 65535 37806 0 0]Eu estive esperando por isso, ladrões[n]Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_11_ [Makoto]]
[s][vp 9 2 65535 43253 0 0]Eu estava esperando o cartão de visita dos[n]ladrões Phantom aparecer![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_12_ [Makoto]]
[s][vp 9 2 65535 39600 0 0]Eu quero ver um pedido de desculpas ainda[n]mais dramático do que o que Madarame fez![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_13_ [Makoto]]
[s][vp 9 2 65535 43406 0 0]Só é lógico que ele seja punido por se[n]importar com nada além de dinheiro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_14_ [Makoto]]
[s][vp 9 2 65535 40706 0 0]Eu estive esperando por isso, ladrões[n]Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_15_ [Makoto]]
[s][vp 9 2 65535 37753 0 0]É justo que as pessoas que fazem coisas[n]terríveis enfrentam punição![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_16_ [Makoto]]
[s][vp 9 2 65535 42400 0 0]O presidente Okumura deve sofrer pelo que[n]fez![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_01_ [Makoto]]
[s][vp 9 2 65535 43007 0 0]Do jeito que eles fizeram... é como se eles[n]gostassem de matar pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_02_ [Makoto]]
[s][vp 9 2 65535 41201 0 0]Não importa o quão mal ele era. Eles são[n]loucos se eles escolheram matá-lo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_03_ [Makoto]]
[s][vp 9 2 65535 40407 0 0]Que tipo de "mudança de coração" foi essa!?[n]Eles são apenas assassinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_04_ [Makoto]]
[s][vp 9 2 65535 40055 0 0]Como matar alguém muda seu coração? Eles são[n]mentirosos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_05_ [Makoto]]
[s][vp 9 2 65535 39402 0 0]Eu só posso imaginar que eles gostam de[n]assassinar pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_06_ [Makoto]]
[s][vp 9 2 65535 42057 0 0]Não acredito que eles tiraram a vida de[n]alguém![n]Eles são loucos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_07_ [Makoto]]
[s][vp 9 2 65535 45157 0 0]Que tipo de "mudança de coração" foi essa!?[n]Eles são apenas assassinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_08_ [Makoto]]
[s][vp 9 2 65535 41657 0 0]Então eles mudam o coração de uma pessoa[n]matando-o? Você está brincando comigo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_09_ [Makoto]]
[s][vp 9 2 65535 43057 0 0]Do jeito que eles fizeram... é como se eles[n]gostassem de matar pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_10_ [Makoto]]
[s][vp 9 2 65535 43751 0 0]Não importa o quão mau seja o cara, eles são[n]loucos por matá-lo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_11_ [Makoto]]
[s][vp 9 2 65535 42607 0 0]Eles não tiveram que matá-lo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_12_ [Makoto]]
[s][vp 9 2 65535 41007 0 0]Como matar alguém muda seu coração? Eles são[n]mentirosos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_13_ [Makoto]]
[s][vp 9 2 65535 44171 0 0]Do jeito que eles fizeram... é como se eles[n]gostassem de matar pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_14_ [Makoto]]
[s][vp 9 2 65535 42057 0 0]Não importa o quão mau seja o cara, eles são[n]loucos por matá-lo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_15_ [Makoto]]
[s][vp 9 2 65535 45157 0 0]Que tipo de "mudança de coração" foi essa!?[n]Eles são apenas assassinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_16_ [Makoto]]
[s][vp 9 2 65535 43251 0 0]Eles mudam o coração de uma pessoa[n]matando-os? Eles são loucos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_01_ [Makoto]]
[s][vp 9 2 65535 43507 0 0]Alguém, qualquer um, precisa fazer algo para[n]parar aqueles ladrões fantasmas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_02_ [Makoto]]
[s][vp 9 2 65535 43401 0 0]Nem o governo nem a polícia são bons...[n]O que há com este país?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_03_ [Makoto]]
[s][vp 9 2 65535 40957 0 0]O que a polícia está fazendo!?[n]Apresse-se e prenda os ladrões fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_04_ [Makoto]]
[s][vp 9 2 65535 44251 0 0]Sabemos quem são os culpados, então por que[n]eles ainda não foram capturados!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_05_ [Makoto]]
[s][vp 9 2 65535 38202 0 0]Não é bom... aquelas avarias psicóticas têm[n]acontecido com mais frequência...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_06_ [Makoto]]
[s][vp 9 2 65535 45302 0 0]Nem o governo nem a polícia são bons...[n]O que há com este país?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_07_ [Makoto]]
[s][vp 9 2 65535 39707 0 0]O que a polícia está fazendo!?[n]Apresse-se e prenda os ladrões fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_08_ [Makoto]]
[s][vp 9 2 65535 43851 0 0]Sabemos quem são os culpados, então por que[n]eles ainda não foram capturados!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_09_ [Makoto]]
[s][vp 9 2 65535 41907 0 0]Alguém, qualquer um, precisa fazer algo para[n]parar aqueles ladrões fantasmas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_10_ [Makoto]]
[s][vp 9 2 65535 40301 0 0]Nem o governo nem a polícia são bons...[n]O que há com este país?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_11_ [Makoto]]
[s][vp 9 2 65535 37657 0 0]Apresse-se e faça algo sobre os ladrões[n]Phantom![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_12_ [Makoto]]
[s][vp 9 2 65535 40251 0 0]Quando a polícia vai começar a agir e[n]prender os ladrões Phantom!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_13_ [Makoto]]
[s][vp 9 2 65535 42707 0 0]Alguém, qualquer um, precisa fazer algo para[n]parar os ladrões Phantom...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_14_ [Makoto]]
[s][vp 9 2 65535 40702 0 0]Nem o governo nem a polícia são bons...[n]O que há com este país?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_15_ [Makoto]]
[s][vp 9 2 65535 40801 0 0]O que a polícia está fazendo!?[n]Apresse-se e prenda os ladrões fantasmas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_16_ [Makoto]]
[s][vp 9 2 65535 41657 0 0]Sabemos quem são os culpados, então por que[n]eles ainda não foram capturados!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_01_ [Makoto]]
[s][vp 9 2 65535 43157 0 0]Alguém só precisa capturar os ladrões[n]fantasmas! Eu não me importo como![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_02_ [Makoto]]
[s][vp 9 2 65535 46007 0 0]A polícia finalmente começou a fazer[n]movimentos para prendê-los...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_03_ [Makoto]]
[s][vp 9 2 65535 41251 0 0]Não me diga que eles acham que colocar um[n]preço em suas cabeças resultará em uma[n]prisão.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_04_ [Makoto]]
[s][vp 9 2 65535 41307 0 0]Os ladrões fantasmas já precisam ser pegos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_05_ [Makoto]]
[s][vp 9 2 65535 38404 0 0]Eles são sérios sobre a recompensa de 30[n]milhões de ienes!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_06_ [Makoto]]
[s][vp 9 2 65535 41859 0 0]Apresse-se e prenda os ladrões fantasmas[n]já...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_07_ [Makoto]]
[s][vp 9 2 65535 41251 0 0]Colocar um preço nas cabeças dos ladrões[n]Phantom realmente resultaria em sua[n]prisão...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_08_ [Makoto]]
[s][vp 9 2 65535 41157 0 0]Quanto tempo temos que viver com medo dos[n]ladrões fantasmas?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_09_ [Makoto]]
[s][vp 9 2 65535 45651 0 0]Por que o governo está em silêncio? Faça[n]alguma coisa![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_10_ [Makoto]]
[s][vp 9 2 65535 43901 0 0]A polícia está demorando muito para[n]responder![n]O que eles estão fazendo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_11_ [Makoto]]
[s][vp 9 2 65535 41401 0 0]Não é o trabalho da polícia lidar com[n]criminosos!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_12_ [Makoto]]
[s][vp 9 2 65535 42157 0 0]Eu não me importo como. Apenas prenda esses[n]assassinos já...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_13_ [Makoto]]
[s][vp 9 2 65535 38700 0 0]A recompensa pelos ladrões Phantom é de 30[n]milhões de ienes![n]Não é insano!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_14_ [Makoto]]
[s][vp 9 2 65535 45501 0 0]Eles precisam se apressar e encontrar um[n]plano que funcione. Nossas vidas estão em[n]jogo aqui...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_15_ [Makoto]]
[s][vp 9 2 65535 39300 0 0]A polícia finalmente começou a fazer[n]movimentos para uma prisão.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_16_ [Makoto]]
[s][vp 9 2 65535 41302 0 0]Eles estão sempre tão lentos para agir...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_01_ [Makoto]]
[s][vp 9 2 65535 38405 0 0]Então as pessoas que fazem discursos na rua[n]estão concorrendo para a eleição...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_02_ [Makoto]]
[s][vp 9 2 65535 41610 0 0]Esperançosamente, a maneira como nosso[n]governo faz as coisas muda após esta[n]eleição...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_03_ [Makoto]]
[s][vp 9 2 65535 42155 0 0]Existe alguém que é realmente capaz de[n]consertar as coisas neste mundo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_04_ [Makoto]]
[s][vp 9 2 65535 39009 0 0]Meu filho começou a chorar porque seu[n]discurso era tão alto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_05_ [Makoto]]
[s][vp 9 2 65535 43709 0 0]Eu gostaria que um político genuinamente bom[n]aparecesse...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_06_ [Makoto]]
[s][vp 9 2 65535 41854 0 0]O que precisamos agora é um político com[n]convicção e uma visão para o futuro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_07_ [Makoto]]
[s][vp 9 2 65535 43252 0 0]Se apenas alguém que pudesse iniciar uma[n]verdadeira revolução social funcionaria na[n]eleição...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_08_ [Makoto]]
[s][vp 9 2 65535 41155 0 0]Eu me pergunto quais candidatos têm maior[n]probabilidade de vencer nas próximas[n]eleições...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_09_ [Makoto]]
[s][vp 9 2 65535 43704 0 0]Quem é aquele cara que está fazendo muitos[n]discursos ultimamente...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_10_ [Makoto]]
[s][vp 9 2 65535 41705 0 0]Quando foi a eleição de novo? Eu esqueci[n]totalmente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_11_ [Makoto]]
[s][vp 9 2 65535 39655 0 0]Esqueci quem, mas aparentemente um dos[n]candidatos é realmente incrível.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_12_ [Makoto]]
[s][vp 9 2 65535 46054 0 0]Existem alguns membros promissores da dieta[n]este ano, você não acha?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_13_ [Makoto]]
[s][vp 9 2 65535 38705 0 0]Eu esqueço, é a próxima eleição no final do[n]ano?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_14_ [Makoto]]
[s][vp 9 2 65535 40703 0 0]A propósito, é verdade que há um cisma no[n]partido no poder?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_15_ [Makoto]]
[s][vp 9 2 65535 45755 0 0]A Câmara dos Deputados foi dissolvida?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_16_ [Makoto]]
[s][vp 9 2 65535 39011 0 0]Sim, é ele... ele não é como os outros[n]políticos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_01_ [Makoto]]
[s][vp 9 2 65535 44302 0 0]O que a polícia está fazendo!? Apresse-se e[n]prenda-os já...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_02_ [Makoto]]
[s][vp 9 2 65535 41751 0 0]Nem o governo nem a polícia são bons...[n]O que há com este país?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_03_ [Makoto]]
[s][vp 9 2 65535 38357 0 0]Naquela época, as pessoas começaram a falar[n]sobre os ladrões Phantom com certeza era[n]estranho...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_04_ [Makoto]]
[s][vp 9 2 65535 39007 0 0]Os ladrões Phantom são apenas um monte de[n]assassinos de sangue frio![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_05_ [Makoto]]
[s][vp 9 2 65535 39755 0 0]Sério, quem são os ladrões fantasmas...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_06_ [Makoto]]
[s][vp 9 2 65535 40709 0 0]O que a polícia está fazendo? Agora é quando[n]precisamos mais deles...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_07_ [Makoto]]
[s][vp 9 2 65535 40257 0 0]Não perca tempo tentando perfilar os ladrões[n]fantasmas. Apenas prendê-los...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_08_ [Makoto]]
[s][vp 9 2 65535 46063 0 0]Quando eles vão prender os ladrões Phantom!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_09_ [Makoto]]
[s][vp 9 2 65535 44907 0 0]Então, espere, todas aquelas quebras[n]psicóticas foram causadas pelos ladrões[n]Phantom?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_10_ [Makoto]]
[s][vp 9 2 65535 42709 0 0]Eu não me importo com quem eles realmente[n]são. Apenas prendê-los já...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_11_ [Makoto]]
[s][vp 9 2 65535 42757 0 0]Eles são um grupo de assassinos, é claro que[n]são todos loucos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_12_ [Makoto]]
[s][vp 9 2 65535 41107 0 0]Eu sinto que isso pode ser rastreado para[n]quando os ladrões fantasmas apareceram pela[n]primeira vez...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_13_ [Makoto]]
[s][vp 9 2 65535 39107 0 0]Não acredito que os ladrões fantasmas eram[n]na verdade um grupo de assassinos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_14_ [Makoto]]
[s][vp 9 2 65535 38460 0 0]Os ladrões fantasmas devem ser loucos, tendo[n]prazer em assassinato e tudo isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_15_ [Makoto]]
[s][vp 9 2 65535 40857 0 0]Os colapsos psicóticos são assustadores...[n]alguém tem que fazer alguma coisa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_16_ [Makoto]]
[s][vp 9 2 65535 39005 0 0]Os ladrões Phantom são apenas um monte de[n]criminosos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_01_ [Makoto]]
[s][vp 9 2 65535 42503 0 0]Shido-san realmente faz jus ao que seu nome[n]significa. Ele é como o juiz personificado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_02_ [Makoto]]
[s][vp 9 2 65535 41504 0 0]Shido-san tem trabalhado duro ultimamente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_03_ [Makoto]]
[s][vp 9 2 65535 41100 0 0]Há algo sobre Shido-san que o diferencia de[n]outras pessoas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_04_ [Makoto]]
[s][vp 9 2 65535 39000 0 0]Não sinto esse nível de confiança com nenhum[n]dos outros políticos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_05_ [Makoto]]
[s][vp 9 2 65535 39804 0 0]Você não acha que o representante Shido[n]parece muito bom?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_06_ [Makoto]]
[s][vp 9 2 65535 38453 0 0]Shido-san é o tipo de político que[n]precisamos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_07_ [Makoto]]
[s][vp 9 2 65535 41300 0 0]O representante Shido só tem essa aura sobre[n]ele.[n]Ele não é como mais ninguém![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_08_ [Makoto]]
[s][vp 9 2 65535 41153 0 0]Estou impressionado. Shido-san é tão jovem,[n]mas ele tem uma visão sólida para o futuro.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_09_ [Makoto]]
[s][vp 9 2 65535 40354 0 0]Esse político chamado Shido parece bastante[n]competente![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_10_ [Makoto]]
[s][vp 9 2 65535 43704 0 0]Shido é um representante incrível, hein?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_11_ [Makoto]]
[s][vp 9 2 65535 42754 0 0]Eles estavam dizendo que o político chamado[n]Shido é a nossa melhor esperança![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_12_ [Makoto]]
[s][vp 9 2 65535 46050 0 0]Eu vi uma pessoa chamada Shido dar um[n]discurso. Parece que ele poderia fazer a[n]diferença![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_13_ [Makoto]]
[s][vp 9 2 65535 38403 0 0]O representante Shido parece muito bom[n]ultimamente![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_14_ [Makoto]]
[s][vp 9 2 65535 43953 0 0]Ultimamente, tenho ouvido muito o nome de[n]Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_15_ [Makoto]]
[s][vp 9 2 65535 44753 0 0]Shido-san tem esse carisma que nenhum outro[n]político tem![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_16_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_01_ [Makoto]]
[s][vp 9 2 65535 43910 0 0]Espero que o mundo seja um lugar melhor[n]agora, com aquele ladrão fantasma morto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_02_ [Makoto]]
[s][vp 9 2 65535 37602 0 0]Eu não tinha ideia de que o ladrão fantasma[n]seria apenas uma criança...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_03_ [Makoto]]
[s][vp 9 2 65535 42154 0 0]É verdade? Aquele ladrão fantasma realmente[n]se matou!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_04_ [Makoto]]
[s][vp 9 2 65535 39001 0 0]Eu não me importo se ele é menor...[n]Ele precisa assumir a responsabilidade![n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_05_ [Makoto]]
[s][vp 9 2 65535 38401 0 0]Vamos lá, cara... você não pode simplesmente[n]se matar assim que for pego...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_06_ [Makoto]]
[s][vp 9 2 65535 39157 0 0]Então ele cometeu suicídio só para não ter[n]que confessar como ele fez isso...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_07_ [Makoto]]
[s][vp 9 2 65535 39705 0 0]Tenho certeza de que não veremos mais[n]aquelas avarias psicóticas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_08_ [Makoto]]
[s][vp 9 2 65535 44202 0 0]Aquele ladrão fantasma se matou? Eu pensei[n]que ele só foi preso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_09_ [Makoto]]
[s][vp 9 2 65535 39504 0 0]O líder dos ladrões Phantom foi preso e[n]depois cometeu suicídio!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_10_ [Makoto]]
[s][vp 9 2 65535 40355 0 0]Ele não teve que se matar só porque foi[n]preso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_11_ [Makoto]]
[s][vp 9 2 65535 42154 0 0]É verdade que o ladrão fantasma era um[n]estudante!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_12_ [Makoto]]
[s][vp 9 2 65535 42352 0 0]Eu nunca pensei que o ladrão fantasma seria[n]apenas um menor...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_13_ [Makoto]]
[s][vp 9 2 65535 42302 0 0]Matou-se na prisão, hein? Que fim abrupto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_14_ [Makoto]]
[s][vp 9 2 65535 45311 0 0]Se esse ladrão fantasma está morto, isso[n]significa que estamos seguros agora, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_15_ [Makoto]]
[s][vp 9 2 65535 39355 0 0]É verdade? Aquele ladrão fantasma realmente[n]se matou!?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_16_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_01_ [Makoto]]
[s][vp 9 2 65535 40750 0 0]Podemos depender de Shido-san para consertar[n]este mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_02_ [Makoto]]
[s][vp 9 2 65535 41353 0 0]Tudo o que precisamos fazer é colocar Shido[n]no comando. Ele fará as mudanças as[n]necessidades da sociedade.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_03_ [Makoto]]
[s][vp 9 2 65535 40400 0 0]Shido-san será um grande líder para este[n]país![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_04_ [Makoto]]
[s][vp 9 2 65535 39361 0 0]Shido-san vai melhorar esta nação! Eu sei[n]que ele pode fazer isso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_05_ [Makoto]]
[s][vp 9 2 65535 38403 0 0]Ouvi dizer que Shido-san revolucionará este[n]mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_06_ [Makoto]]
[s][vp 9 2 65535 41850 0 0]Shido vai mudar este país para melhor.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_07_ [Makoto]]
[s][vp 9 2 65535 45904 0 0]Falou-se sobre fazer o representante Shido[n]Próximo Primeiro Ministro...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_08_ [Makoto]]
[s][vp 9 2 65535 46100 0 0]Shido-san ganhará a eleição! Estou certo[n]disso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_09_ [Makoto]]
[s][vp 9 2 65535 38804 0 0]O representante Shido trará uma revolução![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_10_ [Makoto]]
[s][vp 9 2 65535 43003 0 0]Shido-san vai mudar o Japão![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_11_ [Makoto]]
[s][vp 9 2 65535 42454 0 0]Eu acho que Shido-San tem essa eleição na[n]bolsa![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_12_ [Makoto]]
[s][vp 9 2 65535 45253 0 0]O representante Shido mudará este país![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_13_ [Makoto]]
[s][vp 9 2 65535 42850 0 0]Estarei esperando você fazer grandes coisas,[n]representante Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_14_ [Makoto]]
[s][vp 9 2 65535 41853 0 0]Ficaremos bem, desde que tenhamos shido-san![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_15_ [Makoto]]
[s][vp 9 2 65535 40400 0 0]O representante Shido é o melhor líder para[n]o nosso futuro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_16_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_01_ [Makoto]]
[s][vp 9 2 65535 39503 0 0]Posso não saber muito, mas sei que você não[n]pode dar errado com Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_02_ [Makoto]]
[s][vp 9 2 65535 41953 0 0]Estou ansioso pelo que Shido-san planejou[n]para reconstruir nossa nação.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_03_ [Makoto]]
[s][vp 9 2 65535 41153 0 0]Shido-san é tão confiável![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_04_ [Makoto]]
[s][vp 9 2 65535 39350 0 0]Tenho certeza de que Shido-san levará nossa[n]nação à grandeza![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_05_ [Makoto]]
[s][vp 9 2 65535 41750 0 0]O que o mundo precisa é Shido-san![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_06_ [Makoto]]
[s][vp 9 2 65535 42053 0 0]Masayoshi Shido será o líder do próximo[n]partido no poder![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_07_ [Makoto]]
[s][vp 9 2 65535 41653 0 0]Estou realmente atraído por Shido-san.[n]Parece natural confiar nele, sabe?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_08_ [Makoto]]
[s][vp 9 2 65535 41000 0 0]Estou realmente ansioso pelo que Shido-san[n]está planejando para este país![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_09_ [Makoto]]
[s][vp 9 2 65535 41753 0 0]Ficaremos bem se deixarmos tudo para[n]Masayoshi Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_10_ [Makoto]]
[s][vp 9 2 65535 43403 0 0]Shido-san se tornará nosso novo[n]primeiro-ministro após a próxima eleição,[n]certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_11_ [Makoto]]
[s][vp 9 2 65535 42603 0 0]Shido-san mudará o mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_12_ [Makoto]]
[s][vp 9 2 65535 41550 0 0]Não há rumores ruins sobre Shido-san, então[n]me sinto seguro votando nele.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_13_ [Makoto]]
[s][vp 9 2 65535 40161 0 0]A partir daqui, Shido-san levará o Japão ao[n]futuro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_14_ [Makoto]]
[s][vp 9 2 65535 45511 0 0]Shido-san apenas tem esse ar diferente sobre[n]ele.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_15_ [Makoto]]
[s][vp 9 2 65535 38961 0 0]Não há alguém que possa derrotar Shido-san![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_16_ [Makoto]]
[s][vp 9 2 65535 39353 0 0]Nosso governo está em boas mãos agora![n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_01_ [Makoto]]
[s][vp 9 2 65535 42251 0 0]Esse ladrão fantasma não deveria estar morto?[n]O que diabos está acontecendo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_02_ [Makoto]]
[s][vp 9 2 65535 41954 0 0]O que você pensou sobre o que eles disseram[n]quando sequestraram as ondas de rádio?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_03_ [Makoto]]
[s][vp 9 2 65535 41405 0 0]Isso importa mais quem está certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_04_ [Makoto]]
[s][vp 9 2 65535 39355 0 0]O que está acontecendo...? O que devemos[n]fazer agora?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_05_ [Makoto]]
[s][vp 9 2 65535 38201 0 0]Eu não sei mais em que acreditar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_06_ [Makoto]]
[s][vp 9 2 65535 45509 0 0]Eu não acho que Shido-san fará qualquer[n]coisa que aqueles ladrões fantasmas dizem[n]para ele fazer...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_07_ [Makoto]]
[s][vp 9 2 65535 41105 0 0]O que os ladrões Phantom estão dizendo é[n]verdade...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_08_ [Makoto]]
[s][vp 9 2 65535 41457 0 0]Então, o que era aquela coisa Phantom[n]Thieves?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_09_ [Makoto]]
[s][vp 9 2 65535 40155 0 0]Eu não sei mais.[n]Tenho certeza que Shido ficará bem.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_10_ [Makoto]]
[s][vp 9 2 65535 44901 0 0]Por que estamos falando sobre os ladrões[n]fantasmas de novo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_11_ [Makoto]]
[s][vp 9 2 65535 43355 0 0]Tenho certeza de que vai ficar bem se[n]deixarmos para Shido-san.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_12_ [Makoto]]
[s][vp 9 2 65535 44757 0 0]Phantom Thieves, de novo?[n]O que está acontecendo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_13_ [Makoto]]
[s][vp 9 2 65535 41909 0 0]Por que esses ladrões fantasmas reapareceram[n]de repente? Eu não entendo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_14_ [Makoto]]
[s][vp 9 2 65535 39155 0 0]Aqueles ladrões fantasmas precisam estar[n]mentindo, certo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_15_ [Makoto]]
[s][vp 9 2 65535 43205 0 0]O que aqueles ladrões fantasmas estão[n]dizendo deve ser inventada...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_16_ [Makoto]]
[s][vp 9 2 65535 39352 0 0]Com os ladrões fantasmas aparecendo[n]novamente, não sei em que acreditar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_01_ [Makoto]]
[s][vp 9 2 65535 42252 0 0]Shido-san deveria mudar as coisas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_02_ [Makoto]]
[s][vp 9 2 65535 41202 0 0]Eu não posso acreditar. Isso não pode ser[n]verdade, Shido-san...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_03_ [Makoto]]
[s][vp 9 2 65535 41252 0 0]Shido-san não vai desistir, ele vai...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_04_ [Makoto]]
[s][vp 9 2 65535 39702 0 0]Eu pensei que poderia confiar em Shido-san...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_05_ [Makoto]]
[s][vp 9 2 65535 38102 0 0]Se não podemos nem depender de Shido-san, o[n]que vai acontecer conosco...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_06_ [Makoto]]
[s][vp 9 2 65535 39855 0 0]Ele não está se sentindo bem?[n]Shido-san voltará, porém, não é?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_07_ [Makoto]]
[s][vp 9 2 65535 46102 0 0]Eu realmente pensei que Shido-san iria mudar[n]esta nação...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_08_ [Makoto]]
[s][vp 9 2 65535 40052 0 0]O que vamos fazer sem Shido-san...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_09_ [Makoto]]
[s][vp 9 2 65535 38702 0 0]Ele deve estar se esforçando demais.[n]Shido-san está bem?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_10_ [Makoto]]
[s][vp 9 2 65535 45652 0 0]Estou um pouco preocupado com a saúde dele.[n]Ele não está pensando em apenas desistir,[n]está?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_11_ [Makoto]]
[s][vp 9 2 65535 42452 0 0]Sem Shido-san, este país é feito para...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_12_ [Makoto]]
[s][vp 9 2 65535 39702 0 0]Não, shido representativo...[n]Isso não pode ser verdade...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_13_ [Makoto]]
[s][vp 9 2 65535 40552 0 0]O que vamos fazer sem Shido-san...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_14_ [Makoto]]
[s][vp 9 2 65535 45302 0 0]Não... volte, representante Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_15_ [Makoto]]
[s][vp 9 2 65535 42152 0 0]Shido-san já ganhou.[n]Espero que ele não se demitisse.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_16_ [Makoto]]
[s][vp 9 2 65535 39705 0 0]Ele estava falando com tanta energia[n]embora...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_01_ [Makoto]]
[s][vp 9 2 65535 39105 0 0]Não importa de quem dependemos. Nada vai[n]mudar.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_02_ [Makoto]]
[s][vp 9 2 65535 44702 0 0]Isso é sem esperança...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_03_ [Makoto]]
[s][vp 9 2 65535 38302 0 0]Acabou...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_04_ [Makoto]]
[s][vp 9 2 65535 40052 0 0]Eu não posso acreditar mais em nada...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_05_ [Makoto]]
[s][vp 9 2 65535 41952 0 0]Nada vai mudar...[n]Não há nada que possamos fazer...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_06_ [Makoto]]
[s][vp 9 2 65535 38455 0 0]É impossível...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_07_ [Makoto]]
[s][vp 9 2 65535 45452 0 0]Alguém muda este país, por favor...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_08_ [Makoto]]
[s][vp 9 2 65535 44805 0 0]Eu não me importo mais...[n]Nada vai mudar, de qualquer maneira.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_09_ [Makoto]]
[s][vp 9 2 65535 37802 0 0]Não há mais esperança para nós. Alguém, por[n]favor, faça algo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_10_ [Makoto]]
[s][vp 9 2 65535 39052 0 0]Eu não me importo com quem...[n]Alguém nos salve...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_11_ [Makoto]]
[s][vp 9 2 65535 40652 0 0]Como isso aconteceu?[n]Alguém deveria fazer algo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_12_ [Makoto]]
[s][vp 9 2 65535 41552 0 0]Sem o representante Shido, nosso país está[n]praticamente acabado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_13_ [Makoto]]
[s][vp 9 2 65535 44902 0 0]Alguém nos salve...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_14_ [Makoto]]
[s][vp 9 2 65535 39152 0 0]Terminamos para...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_15_ [Makoto]]
[s][vp 9 2 65535 46202 0 0]O que vai acontecer?[n]Alguém tem que nos ajudar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_16_ [Makoto]]
[s][vp 9 2 65535 41152 0 0]O que devemos fazer...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_01_ [Makoto]]
[s][vp 9 2 65535 39054 0 0]O que mais você precisaria além do essencial?[n]O minimalismo é incrível.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_02_ [Makoto]]
[s][vp 9 2 65535 41850 0 0]Minha família cresceu, então preciso ficar[n]em serviço ativo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_03_ [Makoto]]
[s][vp 9 2 65535 39954 0 0]Esse? É um presente para minha mãe.[n]Eu dou um para ela todos os anos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_04_ [Makoto]]
[s][vp 9 2 65535 40053 0 0]O Japão é tão pacífico sem incidentes[n]perturbadores.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_05_ [Makoto]]
[s][vp 9 2 65535 40153 0 0]O local habitual está bem, certo?[n]Aposto que as meninas virão de qualquer[n]maneira.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_06_ [Makoto]]
[s][vp 9 2 65535 39850 0 0]Você guardaria essa garrafa aqui para mim?[n]Vou trazer minha esposa na próxima vez.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_07_ [Makoto]]
[s][vp 9 2 65535 41550 0 0]Ele ainda usa a gravata que eu lhe dei.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_08_ [Makoto]]
[s][vp 9 2 65535 39702 0 0]Então, essa garota está de volta à cidade[n]e... o que, você não se lembra?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_09_ [Makoto]]
[s][vp 9 2 65535 59020 0 0]Desculpe, tenho que levar meu filho à lição[n]dela.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_10_ [Makoto]]
[s][vp 9 2 65535 38103 0 0]Eu tenho meu estágio novamente hoje,[n]então... pode ser livre à noite![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_11_ [Makoto]]
[s][vp 9 2 65535 37703 0 0]18 pontos é melhor do que da última vez,[n]então você deve ser feliz![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_12_ [Makoto]]
[s][vp 9 2 65535 46050 0 0]Reunir com todos assim me leva de volta à[n]maneira como costumávamos ser.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_13_ [Makoto]]
[s][vp 9 2 65535 43905 0 0]Meu snowboard? Você pode ter isso. Eu[n]realmente não uso mais.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_14_ [Makoto]]
[s][vp 9 2 65535 39501 0 0]Espere, o que aconteceu com a realocação!?[n]Eu pensei que você conseguiu o pedido de[n]transferência?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_15_ [Makoto]]
[s][vp 9 2 65535 38954 0 0]Sem caça ao emprego por você? Oh, você está[n]fazendo a pós-graduação.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_16_ [Makoto]]
[s][vp 9 2 65535 40652 0 0]Viagens comerciais no exterior?[n]Não para mim... você conhece alguém que[n]esteve em um?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_01_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_02_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_03_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_04_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_05_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_06_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_07_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_08_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_09_ [Makoto]]
[s][vp 9 2 65535 40152 0 0]Algo mudou...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_10_ [Makoto]]
[s][vp 9 2 65535 39752 0 0]Eh, acho que vou apenas ir no meu próprio[n]ritmo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_11_ [Makoto]]
[s][vp 9 2 65535 37700 0 0]Você sabe, talvez eu faça algo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_12_ [Makoto]]
[s][vp 9 2 65535 40652 0 0]Eu me pergunto se o mundo vai melhorar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_13_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_14_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_15_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_16_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_01_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_02_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_03_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_04_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_05_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_06_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_07_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_08_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_09_ [Makoto]]
[s][vp 9 2 65535 41610 0 0]Eu quero ficar rico rápido... alguma boa[n]oportunidade por aí?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_10_ [Makoto]]
[s][vp 9 2 65535 41509 0 0]Não é minha culpa...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_11_ [Makoto]]
[s][vp 9 2 65535 42452 0 0]Nada vai mudar... então eu me recuso a levar[n]as coisas a sério.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_12_ [Makoto]]
[s][vp 9 2 65535 45060 0 0]Todo dia é tão chato...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_13_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_14_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_15_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_16_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_01_ [Makoto]]
[s][vp 9 2 65535 39802 0 0]Isso é realmente sério...[n]As coisas não podem continuar assim.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_02_ [Makoto]]
[s][vp 9 2 65535 45654 0 0]Você viu as notícias sobre o acidente? A[n]maneira como descarrilou foi catastrófica...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_03_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]O trem ainda está atrasado?[n]Ugh, isso é tão estúpido...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_04_ [Makoto]]
[s][vp 9 2 65535 41301 0 0]É o trabalho de terroristas![n]Tem que ser![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_05_ [Makoto]]
[s][vp 9 2 65535 38101 0 0]O trem está parado por tanto tempo. O que[n]diabos está acontecendo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_06_ [Makoto]]
[s][vp 9 2 65535 38452 0 0]Ultimamente houve tantos acidentes. Um[n]poderia acontecer a qualquer momento...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_07_ [Makoto]]
[s][vp 9 2 65535 40802 0 0]Segurança aqui é uma piada. Estou com muito[n]medo de pegar o trem agora...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_08_ [Makoto]]
[s][vp 9 2 65535 40952 0 0]Ultimamente houve tantos acidentes. Um[n]poderia acontecer a qualquer momento...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_01_ [Makoto]]
[s][vp 9 2 65535 38504 0 0]Ele deve ser um artista famoso se estivesse[n]no bom dia Japão.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_02_ [Makoto]]
[s][vp 9 2 65535 43554 0 0]Ouvi isso no mundo da arte japonesa, ninguém[n]mais chega perto![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_03_ [Makoto]]
[s][vp 9 2 65535 40954 0 0]Ele deve ser um artista famoso se estivesse[n]no bom dia Japão, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_04_ [Makoto]]
[s][vp 9 2 65535 46050 0 0]MARARAME O artista estava no Good Morning[n]Japan![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_05_ [Makoto]]
[s][vp 9 2 65535 38800 0 0]Então aquele cara Madarame no bom dia Japão[n]era bastante impressionante, hein...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_06_ [Makoto]]
[s][vp 9 2 65535 45300 0 0]Ouvi isso no mundo da arte japonesa, ninguém[n]mais chega perto![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_07_ [Makoto]]
[s][vp 9 2 65535 41004 0 0]Ele deve ser um artista famoso se estivesse[n]no bom dia Japão, certo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_08_ [Makoto]]
[s][vp 9 2 65535 46058 0 0]MARARAME O artista estava no Good Morning[n]Japan![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_09_ [Makoto]]
[s][vp 9 2 65535 43403 0 0]Eles estavam anunciando que haveria uma[n]exposição mostrando o trabalho de Madarame.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_10_ [Makoto]]
[s][vp 9 2 65535 40104 0 0]Ouvi isso no mundo da arte japonesa, ninguém[n]se aproxima.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_11_ [Makoto]]
[s][vp 9 2 65535 41254 0 0]Então aquele cara Madarame no bom dia Japão[n]era bastante impressionante, hein...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_12_ [Makoto]]
[s][vp 9 2 65535 43450 0 0]Mais ninguém pode se aproximar quando se[n]trata de arte japonesa![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_13_ [Makoto]]
[s][vp 9 2 65535 45654 0 0]Eles estavam anunciando que haveria uma[n]exposição mostrando o trabalho de Madarame.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_14_ [Makoto]]
[s][vp 9 2 65535 39153 0 0]Ouvi isso no mundo da arte japonesa, ninguém[n]se aproxima.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_15_ [Makoto]]
[s][vp 9 2 65535 45050 0 0]Ouvi dizer que Madarame, o artista, estava[n]no bom dia Japão![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_16_ [Makoto]]
[s][vp 9 2 65535 41300 0 0]Mais ninguém pode se aproximar quando se[n]trata de arte japonesa![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_01_ [Makoto]]
[s][vp 9 2 65535 41602 0 0]É verdade que mesmo a polícia não pode[n]tocá-los?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_02_ [Makoto]]
[s][vp 9 2 65535 37604 0 0]Ouvi dizer que eles usam alguns truques[n]realmente sujos. Eles são terríveis.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_03_ [Makoto]]
[s][vp 9 2 65535 40602 0 0]Ouvi dizer que muitas pessoas foram[n]vitimadas por isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_04_ [Makoto]]
[s][vp 9 2 65535 44201 0 0]O que a polícia está fazendo?[n]Nesse ritmo, eles vão machucar ainda mais[n]pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_05_ [Makoto]]
[s][vp 9 2 65535 40302 0 0]Até sua família é ameaçada? Isso é[n]assustador...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_06_ [Makoto]]
[s][vp 9 2 65535 41852 0 0]Ouvi dizer que eles usam alguns truques[n]realmente sujos. Eles são terríveis.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_07_ [Makoto]]
[s][vp 9 2 65535 44502 0 0]Ouvi dizer que muitas pessoas foram[n]vitimadas por isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_08_ [Makoto]]
[s][vp 9 2 65535 43201 0 0]O que a polícia está fazendo?[n]Nesse ritmo, eles vão machucar ainda mais[n]pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_09_ [Makoto]]
[s][vp 9 2 65535 40555 0 0]É verdade que mesmo a polícia não pode[n]tocá-los?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_10_ [Makoto]]
[s][vp 9 2 65535 39802 0 0]Ouvi dizer que eles usam alguns truques[n]realmente sujos. Eles são terríveis.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_11_ [Makoto]]
[s][vp 9 2 65535 40654 0 0]Ouvi dizer que eles fazem você fazer coisas[n]horríveis se eles te pegarem...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_12_ [Makoto]]
[s][vp 9 2 65535 41301 0 0]O que a polícia está fazendo?[n]Nesse ritmo, eles vão machucar ainda mais[n]pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_13_ [Makoto]]
[s][vp 9 2 65535 43002 0 0]É verdade que mesmo a polícia não pode[n]tocá-los?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_14_ [Makoto]]
[s][vp 9 2 65535 45505 0 0]Ouvi dizer que eles usam alguns truques[n]realmente sujos. Eles são terríveis.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_15_ [Makoto]]
[s][vp 9 2 65535 39955 0 0]Ouvi dizer que muitas pessoas foram[n]vitimadas por isso...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_16_ [Makoto]]
[s][vp 9 2 65535 45252 0 0]O que a polícia está fazendo?[n]Nesse ritmo, eles vão machucar ainda mais[n]pessoas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_01_ [Makoto]]
[s][vp 9 2 65535 43150 0 0]Estou ansioso para ver as meninas em seus[n]yukata.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_02_ [Makoto]]
[s][vp 9 2 65535 38811 0 0]Quem tem tempo para assistir aos fogos de[n]artifício?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_03_ [Makoto]]
[s][vp 9 2 65535 40203 0 0]Talvez eu deva ir assistir ao show de fogos[n]de artifício...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_04_ [Makoto]]
[s][vp 9 2 65535 41405 0 0]Não vejo fogos de artifício há tanto tempo.[n]Eu tenho estado tão ocupado com o trabalho[n]ultimamente...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_05_ [Makoto]]
[s][vp 9 2 65535 40500 0 0]Vai haver um show de fogos de artifício,[n]certo? Você vai?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_06_ [Makoto]]
[s][vp 9 2 65535 38451 0 0]Quem tem tempo para assistir aos fogos de[n]artifício?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_07_ [Makoto]]
[s][vp 9 2 65535 44853 0 0]Talvez eu deva ir assistir ao show de fogos[n]de artifício...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_08_ [Makoto]]
[s][vp 9 2 65535 41005 0 0]Não vejo fogos de artifício há tanto tempo.[n]Eu tenho estado tão ocupado com o trabalho[n]ultimamente...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_09_ [Makoto]]
[s][vp 9 2 65535 39805 0 0]Festival de fogos de artifício, hein...[n]Só espero que não fique muito sujo na frente[n]da minha loja.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_10_ [Makoto]]
[s][vp 9 2 65535 38802 0 0]Sim, sim... fogos de artifício ou não, ainda[n]não tenho um dia de folga.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_11_ [Makoto]]
[s][vp 9 2 65535 38954 0 0]Devemos ir bater em caras? Isso seria meio[n]divertido![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_12_ [Makoto]]
[s][vp 9 2 65535 39003 0 0]Não me lembro da última vez que vi um fogo[n]de artifício...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_13_ [Makoto]]
[s][vp 9 2 65535 39803 0 0]Yukatas em todos os lugares...[n]Estou amando isso![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_14_ [Makoto]]
[s][vp 9 2 65535 39850 0 0]Um Yukata tem que ser usado com estilo![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_15_ [Makoto]]
[s][vp 9 2 65535 39658 0 0]Olhe para este yukata![n]O design é tão fofo![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_16_ [Makoto]]
[s][vp 9 2 65535 39703 0 0]Eu me pergunto quanto tempo os fogos de[n]artifício vão estar?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_01_ [Makoto]]
[s][vp 9 2 65535 41607 0 0]Você viu a conferência de imprensa do Sr.[n]Okumura? Isso foi louco...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_02_ [Makoto]]
[s][vp 9 2 65535 45001 0 0]Eles realmente foram longe demais...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_03_ [Makoto]]
[s][vp 9 2 65535 40607 0 0]O que aconteceu com o Sr. Okumura não era[n]uma farsa, foi...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_04_ [Makoto]]
[s][vp 9 2 65535 42157 0 0]Seus olhos rolaram para trás em sua cabeça.[n]Foi tão assustador...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_05_ [Makoto]]
[s][vp 9 2 65535 41602 0 0]Essa foi uma execução pública...[n]Foi horrível assistir...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_06_ [Makoto]]
[s][vp 9 2 65535 41857 0 0]Eles realmente foram longe demais...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_07_ [Makoto]]
[s][vp 9 2 65535 44202 0 0]O que aconteceu com o Sr. Okumura não era[n]uma farsa, foi...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_08_ [Makoto]]
[s][vp 9 2 65535 46107 0 0]Seus olhos rolaram para trás em sua cabeça.[n]Foi tão assustador...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_09_ [Makoto]]
[s][vp 9 2 65535 42302 0 0]O que aconteceu com Okumura foi genuinamente[n]horrível...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_10_ [Makoto]]
[s][vp 9 2 65535 37857 0 0]Essa conferência de imprensa foi realmente[n]chocante...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_11_ [Makoto]]
[s][vp 9 2 65535 38252 0 0]Você viu essa conferência de imprensa?[n]Estava mortificando...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_12_ [Makoto]]
[s][vp 9 2 65535 43207 0 0]Foram os ladrões fantasmas que fizeram isso,[n]certo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_13_ [Makoto]]
[s][vp 9 2 65535 43057 0 0]O que aconteceu com Okumura foi genuinamente[n]horrível...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_14_ [Makoto]]
[s][vp 9 2 65535 38460 0 0]Essa conferência de imprensa foi realmente[n]chocante...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_15_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]Isso não era CG, certo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_16_ [Makoto]]
[s][vp 9 2 65535 45057 0 0]Foram os ladrões fantasmas que fizeram isso,[n]certo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_01_ [Makoto]]
[s][vp 9 2 65535 44904 0 0]Esse detetive Akechi é realmente[n]inteligente...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_02_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_03_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_04_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_05_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_06_ [Makoto]]
[s][vp 9 2 65535 42050 0 0]Mesmo que ele esteja no ensino médio, o[n]detetive Akechi está realizando bastante.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_07_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_08_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_09_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_10_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_11_ [Makoto]]
[s][vp 9 2 65535 38904 0 0]Akechi-kun é inteligente, bonito... ele é[n]perfeito![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_12_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_13_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_14_ [Makoto]]
[s][vp 9 2 65535 39154 0 0]Então, você já ouviu falar desse detetive,[n]Akechi?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_15_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_16_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_01_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_02_ [Makoto]]
[s][vp 9 2 65535 41957 0 0]Como sabemos se eles continuarão a atingir[n]apenas pessoas que merecem...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_03_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_04_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_05_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_06_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_07_ [Makoto]]
[s][vp 9 2 65535 45157 0 0]Eles controlam o coração das pessoas da[n]maneira que quiserem, fazendo o que[n]quiserem...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_08_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_09_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_10_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_11_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_12_ [Makoto]]
[s][vp 9 2 65535 45257 0 0]Como podemos ter certeza de que eles nunca[n]terão como alvo alguém que não é obviamente[n]mau...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_13_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_14_ [Makoto]]
[s][vp 9 2 65535 39157 0 0]Controlar o coração das pessoas... como ele[n]diz, parece um pouco suspeito.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_15_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_16_ [Makoto]]
[s]0 [n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_01_ [Makoto]]
[s][vp 9 2 65535 38700 0 0]Eu gostaria de poder namorar uma garota fofa![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_02_ [Makoto]]
[s][vp 9 2 65535 38800 0 0]A garota que passou agora era tão linda...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_03_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]Tudo bem, apenas certifique-se de que não se[n]atrase...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_04_ [Makoto]]
[s][vp 9 2 65535 39354 0 0]Oh, então eu me sentiria menos estressado se[n]eu fizesse meu corpo se mexer?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_05_ [Makoto]]
[s][vp 9 2 65535 38750 0 0]Ei, dê uma olhada![n]Ah, ela já saiu...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_06_ [Makoto]]
[s][vp 9 2 65535 37800 0 0]As meninas hoje em dia estão tão bem![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_07_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]Vou ficar tão bravo se eu estiver atrasado[n]por causa desse atraso no trem![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_08_ [Makoto]]
[s][vp 9 2 65535 38052 0 0]Eu sei que é melhor se eu exercitar, mas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_09_ [Makoto]]
[s][vp 9 2 65535 38101 0 0]Eu posso sentir a tensão onde quer que eu[n]vá...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_10_ [Makoto]]
[s][vp 9 2 65535 38802 0 0]Se apenas um monte de dinheiro cairia do[n]céu...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_11_ [Makoto]]
[s][vp 9 2 65535 40802 0 0]Esse acidente não foi um ataque terrorista,[n]certo...?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_12_ [Makoto]]
[s][vp 9 2 65535 38052 0 0]Meu filho nunca estuda. Tudo o que ele se[n]importa são seus clubes...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_13_ [Makoto]]
[s][vp 9 2 65535 37552 0 0]Ele é atlético e bonito...? A vida é tão[n]injusta...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_14_ [Makoto]]
[s][vp 9 2 65535 38802 0 0]Cada dia é tão desgastante...[n]Eu mereço um tapinha nas costas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_15_ [Makoto]]
[s][vp 9 2 65535 39302 0 0]Acho que nenhum lugar está mais seguro...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_16_ [Makoto]]
[s][vp 9 2 65535 40952 0 0]Nossa, você pelo menos lavaria seu próprio[n]uniforme...[n][f 1 2 180][e]

[msg MSG_HOMELESS_DAY_001_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Algo está errado? No entanto, é bom que você[n]esteja prestando atenção a alguém como eu.[n][w][e]
[s][vp 8 2 1 0 30 0]Você é jovem, então deixe-me dar alguns[n]conselhos. Certifique-se de não cair para[n]este lado da vida.[n][w][e]
[s][vp 8 2 1 0 30 0]Não pretendo assustá-lo, mas qualquer um[n]pode acabar assim se não estiver tomando[n]cuidado.[n][w][e]

[msg MSG_HOMELESS_DAY_002_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]HM? Você precisava de algo?[n][w][e]

[sel SEL_HOMELESS_DAY_002_0_0 top]
[s]Estou apenas olhando.[e]
[s]É difícil, vivendo como você?[e]

[msg MSG_HOMELESS_DAY_002_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]HM, eu acho que você não vê reclusos como eu[n]com muita frequência. Deve ser estranho[n]para você.[n][w][e]
[s][vp 8 2 1 0 30 0]Estou bem porque escolhi esse estilo de[n]vida, mas é melhor você ter cuidado.[n][w][e]
[s][vp 8 2 1 0 30 0]Tenho amigos que caíram nisso porque foram[n]vitimados por algumas pessoas más.[n][w][e]

[msg MSG_HOMELESS_DAY_002_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Haha, estou emocionado por você estar[n]preocupado comigo. Não se preocupe, estou[n]acostumado a isso.[n]Eu vou ficar bem.[n][w][e]
[s][vp 8 2 1 0 30 0]Eu estava vivendo esse tipo de vida antes[n]mesmo de me lembrar. Minha memória está um[n]pouco nebulosa.[n][w][e]
[s][vp 8 2 1 0 30 0]Na verdade, tenho problemas para lembrar[n]qualquer coisa que aconteça à noite... bem,[n]acho que não é um grande negócio.[n][w][e]

[msg MSG_HOMELESS_NIGHT_002_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]... o que quer? Vá para casa, se você não[n]quiser se machucar.[n][w][e]

[sel SEL_HOMELESS_NIGHT_002_0 top]
[s]Nenhuma coisa.[e]
[s]Eu sinto Muito.[e]
[s]O que você está fazendo?[e]

[msg MSG_HOMELESS_NIGHT_002_1 [Homeless Man]]
[s][vp 8 2 1 0 30 0]TCH... então você está apenas mexendo comigo.[n]Qualquer que seja.[n][w][e]
[s][vp 8 2 1 0 30 0]Você ouve sobre esse enorme acidente no[n]outro dia? Coisas muito engraçadas![n][w][e]
[s][vp 8 2 1 0 30 0]Todo mundo está ficando nervoso por causa[n]disso. Adoro ver o medo em seus rostos.[n][w][e]

[msg MSG_HOMELESS_NIGHT_002_2 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Sim, é uma boa ideia para crianças como você[n]ser honesto.[n][w][e]
[s][vp 8 2 1 0 30 0]Na cidade, você pode se machucar pelo[n]Meddlin 'nos negócios de outra pessoa, sabe?[n]Tome cuidado.[n][w][e]

[msg MSG_HOMELESS_NIGHT_002_3 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Com o que você se importa? A maneira como eu[n]vivo não tem nada a fazer com você, garoto.[n][w][e]
[s][vp 8 2 1 0 30 0]Na cidade, você pode se machucar pelo[n]Meddlin 'nos negócios de outra pessoa, sabe?[n]Tome cuidado.[n][w][e]

[msg MSG_HOMELESS_DAY_003_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ei, há algo que eu gostaria de lhe perguntar.[n][w][e]
[s][vp 8 2 1 0 30 0]Ouvi dizer que esse "Madarame" tem muita[n]reputação. Ele é tão bom de um homem?[n][w][e]

[sel SEL_HOMELESS_DAY_003_0_0 top]
[s]Ele é muito famoso.[e]
[s]Ele é apenas uma pessoa má.[e]

[msg MSG_HOMELESS_DAY_003_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Eu vejo. Ele ainda deve ser muito bom em[n]fazer as pessoas acreditarem no que ele[n]quer.[n][w][e]

[msg MSG_HOMELESS_DAY_003_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Oh? Há algum boato sobre ele circular?[n][w][e]

[msg MSG_HOMELESS_DAY_003_3_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Tenho um amigo que afirma ser um ex-aluno[n]dele. Aparentemente, ele teve uma[n]experiência terrível...[n][w][e]
[s][vp 8 2 1 0 30 0]Eu não pedi os detalhes, no entanto.[n]Eu me senti estranho investindo em sua vida.[n][w][e]

[msg MSG_HOMELESS_NIGHT_003_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 3 10 0 10]... Assim como eu pensei, as pessoas estão[n]entusiasmadas com aquela velha bastarda que[n]agete tudo.[n][w][e]
[s][vp 8 2 1 0 30 0]Eu me pergunto quantas pessoas sofreram nos[n]bastidores da causa dele. Bem, não como eu[n]me importo de qualquer maneira.[n][w][e]

[msg MSG_HOMELESS_DAY_004_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Encontrei dinheiro no bolso novamente. O[n]problema é que não tenho ideia de como[n]consegui...[n][w][e]

[sel SEL_HOMELESS_DAY_004_0_0 top]
[s]Você é sortudo.[e]
[s]Você ficou senil?[e]
[s]O que aconteceu?[e]

[msg MSG_HOMELESS_DAY_004_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Eu peço desculpa mas não concordo. Encontrar[n]dinheiro comigo e não saber de onde veio é[n]bastante assustador.[n][w][e]
[s][vp 8 2 1 0 30 0]Nunca tenho certeza de como se livrar disso,[n]então sempre deixo em uma caixa de doação.[n][w][e]
[s][vp 8 2 1 0 30 0]Pode ser interessante se eu solicitasse esse[n]detetive genial para resolver este[n]mistério...[n][w][e]

[msg MSG_HOMELESS_DAY_004_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]... Para ser sincero, não posso negar[n]inteiramente isso.[n][w][e]
[s][vp 8 2 1 0 30 0]Talvez eu tenha dormido? Parece que acabo em[n]outro lugar no meio da noite.[n][w][e]
[s][vp 8 2 1 0 30 0]Você não acha que Shibuya é perigoso à[n]noite? E se eu tiver uma dessas falhas[n]psicóticas?[n][w][e]

[msg MSG_HOMELESS_DAY_004_3_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Há um tempo, comecei a ter esse problema. Eu[n]simplesmente não seria capaz de lembrar as[n]coisas.[n][w][e]
[s][vp 8 2 1 0 30 0]Minhas memórias do que acontece à noite são[n]especialmente nebulosas. Estou com muito[n]medo disso, para ser sincero.[n][w][e]
[s][vp 8 2 1 0 30 0]Pode ser interessante se eu solicitasse esse[n]detetive genial para resolver este[n]mistério...[n][w][e]

[msg MSG_HOMELESS_NIGHT_004_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]TCH, isso é tudo o que resta desse dinheiro?[n]Eu também passei por todo esse problema de[n]ganhar isso.[n][w][e]

[sel SEL_HOMELESS_NIGHT_004_0 top]
[s]Estou com inveja.[e]
[s]Encontre algum trabalho a fazer.[e]
[s]O que você está fazendo aqui?[e]

[msg MSG_HOMELESS_NIGHT_004_1 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Cala boca. Apenas bata, garoto.[n][w][e]
[s][vp 8 2 1 0 30 0]Shibuya é uma cidade muito agradável à noite.[n]Heh. Talvez uma criança como você não[n]entendesse.[n][w][e]

[msg MSG_HOMELESS_NIGHT_004_2 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Não se preocupe, eu tenho um emprego fazendo[n]o que eu amo. É como Shibuya à noite existe[n]apenas para mim...[n][w][e]

[msg MSG_HOMELESS_NIGHT_004_3 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Ei, essa é a minha linha.[n][w][e]
[s][vp 8 2 1 0 30 0]Cuidado, garoto. Você não pode se intrometer[n]nos negócios de outras pessoas nesta cidade.[n][w][e]

[msg MSG_HOMELESS_NIGHT_004_4 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Tudo bem. Hora de sair e ganhar mais[n]dinheiro. Vou ficar enferrujado se tudo o[n]que faço é sentar.[n][w][e]

[msg MSG_HOMELESS_DAY_005_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]S-Stop... Não tenho nada que valha a pena[n]roubar![n]Por favor, estou sem dinheiro, estou sem[n]dinheiro...[n][w][e]
[s][vp 8 2 1 0 30 0]...Huh? Isso não é um assalto? Oh, por[n]favor, não me assuste assim.[n][w][e]

[sel SEL_HOMELESS_DAY_005_0_0 top]
[s]Você está exagerando.[e]
[s]Foi mal.[e]
[s]O que está acontecendo?[e]

[msg MSG_HOMELESS_DAY_005_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Mas tem havido toneladas de ameaças e[n]assaltos por aqui ultimamente...[n]Aconteceu com alguns dos meus amigos.[n][w][e]
[s][vp 8 2 1 0 30 0]Ouvi alguém puxar as cordas nos bastidores.[n]É melhor você cuidar também, jovem.[n][w][e]

[msg MSG_HOMELESS_DAY_005_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Não, sou eu quem tirou conclusões.[n][w][e]
[s][vp 8 2 1 0 30 0]À noite, como de costume, Shibuya é um lugar[n]traiçoeiro.[n][w][e]

[msg MSG_HOMELESS_DAY_005_3_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Você conhece aquele incidente de Madarame?[n]Aparentemente, uma organização de Shibuya[n]estava envolvida com ela.[n][w][e]
[s][vp 8 2 1 0 30 0]Com o dinheiro sendo transferido nos[n]bastidores, as tensões em Shibuya ficarão[n]altas por um tempo.[n][w][e]

[msg MSG_HOMELESS_NIGHT_005_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]O que quer, garoto? Você vai se machucar se[n]ficar por aqui à noite com muita frequência.[n][w][e]

[sel SEL_HOMELESS_NIGHT_005_0 top]
[s]Eu não me importo.[e]
[s]Eu vou tomar cuidado.[e]
[s]Shibuya é inseguro?[e]

[msg MSG_HOMELESS_NIGHT_005_1 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Cada vez mais, pirralhos arrogantes estão[n]tentando brigar com caras como eu.[n][w][e]
[s][vp 8 2 1 0 30 0]Não sei quem foi a última vez, mas virei a[n]mesa nele. Você pode querer cuidar. Haha![n][w][e]

[msg MSG_HOMELESS_NIGHT_005_2 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Sim, é o que você diz, mas você não vai[n]fazer isso, é?[n][w][e]
[s][vp 8 2 1 0 30 0]As pessoas podem falar tudo o que quiserem,[n]mas farão as coisas sombrias que querem[n]fazer.[n]Olhe para Madarame.[n][w][e]

[msg MSG_HOMELESS_NIGHT_005_3 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Digamos apenas um cara magro como você[n]deveria ter cuidado. Este lugar até faria[n]homens crescidos chorarem...[n][w][e]
[s][vp 8 2 1 0 30 0]Falando em homens adultos chorando, que tal[n]aquele Madarame, não é? Derramando seu[n]próprio feijão. Aquilo foi engraçado![n][w][e]

[msg MSG_HOMELESS_DAY_006_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]... hm? O que é isso? Você está apenas[n]tentando passar o tempo?[n][w][e]

[sel SEL_HOMELESS_DAY_006_0_0 top]
[s]Exatamente.[e]
[s]Estou muito ocupado para isso.[e]
[s]Apenas olhando.[e]

[msg MSG_HOMELESS_DAY_006_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Por que não conferir a passagem subterrânea[n]da estação Shibuya? Existem anúncios de[n]emprego ao lado das escadas.[n][w][e]
[s][vp 8 2 1 0 30 0]Eu também pensei em encontrar trabalho, mas[n]vou ser rejeitado, já que eu pareço assim...[n]Haha.[n][w][e]

[msg MSG_HOMELESS_DAY_006_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Oh isso é bom. Bem, tenho certeza de que, na[n]sua idade, você prefere se divertir do que[n]estar ocupado.[n][w][e]

[msg MSG_HOMELESS_DAY_006_3_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Diga, eu gostaria de te perguntar uma coisa.[n]Na cidade, continuo ouvindo sobre os[n]ladrões Phantom.[n][w][e]
[s][vp 8 2 1 0 30 0]Que tipo de truque eles usam para roubar o[n]coração das pessoas? Haha, bem, eu acho que[n]você não saberia...[n][w][e]

[msg MSG_HOMELESS_DAY_006_4_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Oh, certo. Se você me vir à noite... você se[n]certificaria de ficar a uma distância[n]segura?[n][w][e]

[msg MSG_HOMELESS_NIGHT_006_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]E aí? Estou de bom humor, então vou me[n]manter em companhia.[n][w][e]

[sel SEL_HOMELESS_NIGHT_006_0 top]
[s]Como está a economia?[e]
[s]Não tenho nada a dizer.[e]

[msg MSG_HOMELESS_NIGHT_006_1 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Eu sei um trabalho que vai te deixar rico.[n]Eu posso conectá-lo, mas você se apagará[n]legalmente.[n][w][e]
[s][vp 8 2 1 0 30 0]Nahhh, estou apenas mexendo com você... heh[n]heh.[n][w][e]

[msg MSG_HOMELESS_NIGHT_006_2 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Então vá para casa, garoto. Não é o meu[n]problema se você ficar por perto e algo[n]acontecer com você.[n][w][e]
[s][vp 8 2 1 0 30 0]Venha à noite, este é o nosso mundo...[n]Heh heh.[n][w][e]

[msg MSG_HOMELESS_NIGHT_006_4 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Eu amo isso à noite... eu consigo soltar e[n]ser livre.[n][w][e]

[msg MSG_HOMELESS_DAY_007_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]HM...? Você precisava de algo?[n][w][e]

[sel SEL_HOMELESS_DAY_007_0_0 top]
[s]Eu só quero conversar um pouco.[e]
[s]Nada realmente.[e]
[s]Como está a cidade hoje em dia?[e]

[msg MSG_HOMELESS_DAY_007_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Vamos ver... você sabe que os ladrões[n]fantasmas enviaram um cartão de visita,[n]certo?[n][w][e]
[s][vp 8 2 1 0 30 0]Tenho certeza de que isso vai causar as[n]coisas por aqui para ficar bem agitado.[n][w][e]

[msg MSG_HOMELESS_DAY_007_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Oh, está certo. Você viu isso?[n][w][e]
[s][vp 8 2 1 0 30 0]Você viu o cartão de visita do Phantom[n]Thieves? As coisas que eles fazem são[n]bastante interessantes.[n][w][e]

[msg MSG_HOMELESS_DAY_007_3_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Eu continuo ouvindo sobre o cartão de visita[n]que os ladrões fantasmas enviaram.[n][w][e]
[s][vp 8 2 1 0 30 0]O submundo não passa de bandidos agora. É[n]patético. O que aconteceu com o código de[n]honra deles?[n][w][e]

[msg MSG_HOMELESS_NIGHT_007_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Huh, é aquele garoto de coruja noturna[n]novamente.[n]O que quer?[n][w][e]

[sel SEL_HOMELESS_NIGHT_007_0 top]
[s]Eu só quero conversar um pouco.[e]
[s]Nada realmente.[e]
[s]Como está a cidade hoje em dia?[e]

[msg MSG_HOMELESS_NIGHT_007_1 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Eu ouço que os ladrões fantasmas vão atingir[n]a máfia agora? Eh, eles são todos um monte[n]de crianças para mim.[n][w][e]
[s][vp 8 2 1 0 30 0]Se eu pegasse uma faca e apenas os[n]acariciasse, tenho certeza de que eles[n]fugiriam, gritando. Hahaha![n][w][e]

[msg MSG_HOMELESS_NIGHT_007_2 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Por causa daqueles ladrões fantasmas, há[n]muito mais policiais correndo por essa área[n]agora.[n][w][e]
[s][vp 8 2 1 0 30 0]Tch. Esse cartão de visita deles é apenas[n]uma vida mais difícil para mim.[n][w][e]

[msg MSG_HOMELESS_NIGHT_007_3 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Os bandidos em Shibuya estão agindo desde[n]que os ladrões fantasmas enviaram o cartão[n]de visita deles.[n][w][e]
[s][vp 8 2 1 0 30 0]Ah, inferno, não é tudo ruim. Estou me[n]divertindo muito, estou divertindo alguns[n]deles...[n]Heh heh.[n][w][e]

[msg MSG_HOMELESS_DAY_008_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Eu sinto que meus amigos estão me[n]evitando... poderia ser por causa de...[n]isso?[n][w][e]

[sel SEL_HOMELESS_DAY_008_0_0 top]
[s]O que você quer dizer com "isso"?[e]
[s]Eles te odeiam?[e]

[msg MSG_HOMELESS_DAY_008_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Todo mundo foge assim que vê meu rosto, mas[n]não sei ao certo por que...[n][w][e]

[msg MSG_HOMELESS_DAY_008_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Haha... acho que não fiz nada que faria as[n]pessoas fugirem assim.[n][w][e]

[msg MSG_HOMELESS_DAY_008_4_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Hey, eu posso perguntar algo a você?[n][w][e]
[s][vp 8 2 1 0 30 0]Você acha que é possível que a personalidade[n]de alguém possa mudar da noite para o[n]dia...?[n][w][e]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Não, desculpe. Deixa para lá...[n][w][e]

[msg MSG_HOMELESS_NIGHT_008_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Hmph... o que quer, garoto?[n][w][e]

[sel SEL_HOMELESS_NIGHT_008_0 top]
[s]Está pacífico aqui agora?[e]
[s]Nenhuma coisa.[e]
[s]Você não vai dormir?[e]

[msg MSG_HOMELESS_NIGHT_008_1 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Sim, as coisas se acalmaram após a prisão de[n]Kaneshiro. Aqueles ladrões fantasmas[n]realmente fizeram isso.[n][w][e]
[s][vp 8 2 1 0 30 0]Roubar corações parece loucura, mas você[n]sabe o que? Isso torna este jogo de vida[n]mais interessante.[n][w][e]

[msg MSG_HOMELESS_NIGHT_008_2 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Desde que os ladrões fantasmas lidaram com[n]Kaneshiro, a cidade de repente ficou em[n]silêncio.[n][w][e]
[s][vp 8 2 1 0 30 0]TCH, não parece Shibuya se não houver perigo[n]no ar.[n][w][e]

[msg MSG_HOMELESS_NIGHT_008_3 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Heh heh. Ei, eu trabalho à noite. Se você[n]conseguiu um emprego para mim, deixe uma[n]carta naquela lixeira.[n][w][e]
[s][vp 8 2 1 0 30 0]Se houver algum lixo irritante que você[n]deseja retirar, vou descartá-lo por você.[n]Hahaha![n][w][e]

[msg MSG_HOMELESS_DAY_009_0_0 [Homeless Man]]
[s][f 4 23 1 30 5 10 4 10][vp 8 2 1 0 30 0]Eu? Espancando meus próprios amigos? Isso é[n]impossível. Mas à noite... minhas memórias[n]daquela época estão em branco.[n][w][e]

[sel SEL_HOMELESS_DAY_009_0_0 top]
[s]Você está bem?[e]
[s]Você não se lembra?[e]

[msg MSG_HOMELESS_DAY_009_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Y-sim... estou bem...[n][w][e]
[s][vp 8 2 1 0 30 0]Fico com medo quando acordo todas as manhãs.[n]Eu sinto que... sinto que não sou eu[n]mesmo...[n][w][e]

[msg MSG_HOMELESS_DAY_009_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]É mais como... minha memória é nebulosa.[n]Como se eu estivesse em algum sonho...[n][w][e]
[s][vp 8 2 1 0 30 0]É como se meu cérebro... ou o próprio mundo[n]fosse completamente reescrito...[n][w][e]

[msg MSG_HOMELESS_DAY_009_3_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Os ladrões fantasmas poderiam ter feito algo[n]comigo? Não... não há como...[n][w][e]

[msg MSG_HOMELESS_NIGHT_009_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]... o que quer? Estou muito chateado agora.[n][w][e]

[sel SEL_HOMELESS_NIGHT_009_0 top]
[s]Porque?[e]
[s]Acalmar.[e]

[msg MSG_HOMELESS_NIGHT_009_1 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Isso não envolve você.[n][w][e]
[s][vp 8 2 1 0 30 0]... se eu jogar minhas cartas da maneira[n]certa, posso fazer com que os ladrões[n]fantasmas assumam a culpa pelo meu[n]trabalho...[n][w][e]
[s][vp 8 2 1 0 30 0]Aw, que diabos!? Saia aqui, vá para outro[n]lugar![n][w][e]

[msg MSG_HOMELESS_NIGHT_009_2 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Hmph... Algum velho bastardo tentou mexer no[n]meu território, então eu gentilmente o[n]silenciei.[n][w][e]
[s][vp 8 2 1 0 30 0]Se você não quer que o mesmo aconteça com[n]você, você fica longe daquela lixeira.[n][w][e]
[s][vp 8 2 1 0 30 0]É uma história diferente se você tem um[n]pedido para mim... heh heh.[n][w][e]

[msg MSG_HOMELESS_DAY_010_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]O que... coisas terríveis que eu fiz. Nesse[n]ritmo, eu poderia muito bem morrer...[n][w][e]

[sel SEL_HOMELESS_DAY_010_0_0 top]
[s]O que aconteceu?[e]
[s]Controle-se.[e]

[msg MSG_HOMELESS_DAY_010_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Nao e nada. Eu ainda pareço ser... eu mesmo.[n][w][e]
[s][vp 8 2 1 0 30 0]Ei, você acha... um coração pode realmente[n]ser mudado...?[n][w][e]

[msg MSG_HOMELESS_DAY_010_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Não, estou bem. Eu ainda pareço ser... eu[n]mesmo.[n][w][e]
[s][vp 8 2 1 0 30 0]Os ladrões fantasmas roubam corações, hein?[n]Para ser sincero, eu gostaria que eles[n]tenham o coração de... você sabe.[n][w][e]

[msg MSG_HOMELESS_DAY_010_4_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Acho que vou tentar convencê-lo escrevendo[n]outra carta. É melhor do que não fazer[n]nada...[n][w][e]

[msg MSG_HOMELESS_NIGHT_010_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Aquele cara deixou outra carta no bolso?[n]Eu nunca vou mudar minha mente. Ele já deve[n]desistir.[n][w][e]

[sel SEL_HOMELESS_NIGHT_010_0 top]
[s]Uma letra?[e]
[s]Quem "esse cara" significa?[e]

[msg MSG_HOMELESS_NIGHT_010_1 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Você estava ouvindo, hein? Ei, você pode se[n]machucar se cutucar seu nariz onde não[n]deveria.[n][w][e]
[s][vp 8 2 1 0 30 0]Ei, cartas e notas escritas são realmente[n]úteis. Depois de queimar, não há mais[n]evidências.[n][w][e]
[s][vp 8 2 1 0 30 0]Usin 'a Internet deixa uma trilha. Para o[n]meu trabalho, você precisa usar papel para[n]sua papelada.[n][w][e]
[s][vp 8 2 1 0 30 0]Heh, mesmo medjed, nunca saberá o que está[n]escrito nesta nota. Haha![n][w][e]

[msg MSG_HOMELESS_NIGHT_010_2 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Você estava ouvindo, hein? Scram se você não[n]quiser se machucar.[n][w][e]
[s][vp 8 2 1 0 30 0]Quanto mais você luta e resiste, pior sua[n]dor e sofrimento, sabe?[n][w][e]
[s][vp 8 2 1 0 30 0]No entanto, é sempre mais divertido para mim[n]quando o outro cara luta... heh heh.[n][w][e]

[msg MSG_HOMELESS_DAY_011_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]*suspiro* Você precisou de alguma coisa,[n]jovem?[n][w][e]

[sel SEL_HOMELESS_DAY_011_0_0 top]
[s]Como você tem estado?[e]
[s]Preocupado com alguma coisa?[e]

[msg MSG_HOMELESS_DAY_011_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Onde quer que eu vá, ouço sobre esses[n]ladrões fantasmas. Eles estão sendo[n]chamados de heróis modernos.[n][w][e]
[s][vp 8 2 1 0 30 0]Se eu pedisse que Phantom Thieves me[n]ajudasse, me pergunto se eles poderiam[n]limpar a preguiça na minha cabeça...[n]*suspiro* [n][w][e]

[msg MSG_HOMELESS_DAY_011_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Algo parecido. Talvez eu deva perguntar[n]aqueles fantasmas [n][w][e]
[s][vp 8 2 1 0 30 0]... Oh, não importa. Não é nada. Apenas[n]esqueça o que eu disse.[n][w][e]

[msg MSG_HOMELESS_DAY_011_3_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Nas minhas roupas, encontrei algum dinheiro[n]e uma faca ensanguentada. E esta também não[n]é a primeira ou a segunda vez...[n][w][e]
[s][vp 8 2 1 0 30 0]Os trechos de tempo que não tenho lembrança[n]estão ficando mais longos. Ninguém entende[n]meu problema...[n][w][e]

[msg MSG_HOMELESS_NIGHT_011_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Estou de bom humor agora, então se você[n]quiser conversar, vou mantê-lo companhia.[n][w][e]

[sel SEL_HOMELESS_NIGHT_011_0 top]
[s]Não tenho nada para falar.[e]
[s]Aconteceu alguma coisa?[e]

[msg MSG_HOMELESS_NIGHT_011_1 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Praticamente, graças ao tumulto por aqueles[n]ladrões fantasmas. Espero que eles[n]continuem assim.[n][w][e]
[s][vp 8 2 1 0 30 0]Isso facilita as coisas para mim quando a[n]polícia está tão focada nelas. Apenas[n]mexendo com você. Heh heh.[n][w][e]

[msg MSG_HOMELESS_NIGHT_011_2 [Homeless Man]]
[s][vp 8 2 1 0 30 0]O que? Então pare de Borin 'e saia aqui.[n]Shoo.[n][w][e]
[s][vp 8 2 1 0 30 0]Por que você não tem sua mamãe compra alguns[n]brinquedos fantasmas, garoto?[n][w][e]

[msg MSG_HOMELESS_NIGHT_011_3 [Homeless Man]]
[s][vp 8 2 1 0 30 0]O trabalho está indo bem para mim. Você quer[n]tentar me contratar para algo também?[n][w][e]
[s][vp 8 2 1 0 30 0]Basta deixar suas informações e o dinheiro[n]na lixeira. Desaparecimentos, acidentes,[n]você escolhe. Eu faço.[n][w][e]
[s][vp 8 2 1 0 30 0]Não vou deixar um único pedaço de evidência[n]para trás, assim como os ladrões fantasmas[n]fazem isso! Haha![n][w][e]

[msg MSG_HOMELESS_DAY_012_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Eu-eu quero conhecer os ladrões Phantom.[n]Eu quero que eles mudem o coração de[n]alguém...[n][w][e]

[sel SEL_HOMELESS_DAY_012_0_0 top]
[s]De quem é o coração?[e]
[s]Deixe para mim.[e]

[msg MSG_HOMELESS_DAY_012_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Isso é uma pergunta... eu gostaria de me[n]perguntar...[n][w][e]
[s][vp 8 2 1 0 30 0]Talvez eu pudesse encontrar essa pessoa...[n]se eu esperar na Okumura Foods?[n][w][e]

[msg MSG_HOMELESS_DAY_012_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Haha, eu aprecio você tentando ajudar.[n]É como se você realmente fosse algum tipo de[n]herói fantasma do ladrão.[n][w][e]
[s][vp 8 2 1 0 30 0]No entanto... eu nem sei quem estou tentando[n]segmentar... desculpe, estou apenas falando[n]comigo mesmo.[n][w][e]

[msg MSG_HOMELESS_NIGHT_012_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]O que quer? Eu tenho muito tempo, então, se[n]você precisar de algo, eu o ouvirei.[n][w][e]

[sel SEL_HOMELESS_NIGHT_012_0 top]
[s]Você está entediado?[e]
[s]Vou passar.[e]

[msg MSG_HOMELESS_NIGHT_012_1 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Sim, eu tenho muito mais tempo em minhas[n]mãos agora. Consegui ficar de fora por mais[n]tempo, pouco a pouco.[n][w][e]
[s][vp 8 2 1 0 30 0]Parece que estarei livre em breve. O cara[n]que tem um controle sobre mim, o coração[n]está começando a enfraquecer.[n][w][e]
[s][vp 8 2 1 0 30 0]... de quem estou falando? Alguém bem perto[n]de mim! Haha![n][w][e]

[msg MSG_HOMELESS_NIGHT_012_2 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Ah, não seja assim. Olha, há muita diversão,[n]interessando coisas em andamento.[n]Por exemplo...[n][w][e]
[s][vp 8 2 1 0 30 0]Você ouve que o Bastardo Hoity-Tity tem um[n]cartão de visita? Ele finalmente recebeu a[n]atenção dos ladrões Phantom.[n][w][e]
[s][vp 8 2 1 0 30 0]Eles estão punindo pessoas más que a lei não[n]pode alcançar. Aqueles ladrões fantasmas[n]são como eu, hahaha![n][w][e]

[msg MSG_HOMELESS_DAY_013_0_0 [Homeless Man]]
[s][vp 8 2 65535 0 0 0]......[n][w][e]

[sel SEL_HOMELESS_DAY_013_0_0 top]
[s]Você está bem?[e]
[s]Você está doente?[e]

[msg MSG_HOMELESS_DAY_013_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]...Huh? Oh... você precisava de algo?[n][w][e]
[s][vp 8 2 1 0 30 0]Eu não tenho consciente tanto ultimamente.[n]Eu temo que ele possa dominar meu corpo se[n]eu dormir...[n][w][e]

[msg MSG_HOMELESS_DAY_013_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Doente? Doente, hein...[n][w][e]
[s][vp 8 2 1 0 30 0]Talvez seja isso... aquela coisa que as[n]pessoas estão falando. Onde você perde a[n]mente...[n][w][e]
[s][vp 8 2 1 0 30 0]Isso não parece tão ruim, no entanto.[n]Enquanto esse outro cara desaparecer[n]também...[n][w][e]

[msg MSG_HOMELESS_NIGHT_013_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Heh heh. Que noite de abelha.[n]Eu tenho que gostar totalmente do meu tempo[n]aqui, minha liberdade...[n][w][e]
[s][vp 8 2 1 0 30 0]O que você? Você também gosta de vida?[n][w][e]

[sel SEL_HOMELESS_NIGHT_013_0 top]
[s]Mais ou menos, sim.[e]
[s]Sim eu sou.[e]
[s]O mundo fede.[e]

[msg MSG_HOMELESS_NIGHT_013_1 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Tipo de? Hah, que medíocre. Você sabe, todo[n]o mundo é um jogo. Somos jogadores ou peças.[n][w][e]
[s][vp 8 2 1 0 30 0]Você é um jogador? Ou você é uma peça,[n]apenas se manipulou? Você realmente tem que[n]pensar nisso.[n][w][e]

[msg MSG_HOMELESS_NIGHT_013_2 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Você tem um verdadeiro sorriso lá. Sim, você[n]entendeu. A vida é apenas um jogo, e você[n]sabe como jogar.[n][w][e]
[s][vp 8 2 1 0 30 0]Você já se entedia do reto e estreito, eu[n]posso te ensinar como se divertir mais ao[n]longo da vida.[n][w][e]

[msg MSG_HOMELESS_NIGHT_013_3 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Você sabe o que? Você fez um bom ponto.[n]Este mundo é realmente o pior.[n][w][e]
[s][vp 8 2 1 0 30 0]Tudo o que tem são adultos imundos, repleta[n]de moscas. Apenas me considere uma[n]mata-mosca.[n][w][e]

[msg MSG_HOMELESS_DAY_014_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Eu poderia ter pedido ajuda ao Phantom[n]Thieves muito mais cedo, se eu soubesse o[n]nome dele![n][w][e]
[s][vp 8 2 1 0 30 0]Não importa o quanto eu tente, não me[n]lembro. Ninguém por aqui sabe sobre o meu[n]passado. O que devo fazer?[n][w][e]
[s][vp 8 2 1 0 30 0]Ele saberia? Mas é impossível para mim me[n]encontrar com ele...[n][w][e]
[s][vp 8 2 1 0 30 0]Alguém... alguém por favor me ajude...[n][w][e]

[msg MSG_HOMELESS_NIGHT_014_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 3 10 0 10]Merda, aquele bastardo...! Por que ele teve[n]que agitar nosso corpo assim!?[n][w][e]
[s][vp 8 2 1 0 30 0]Ele estava tentando me impedir de suicídio[n]ou algo assim? Heh, parece que ele não tem[n]coragem.[n][w][e]
[s][vp 8 2 1 0 30 0]Bem, tanto faz. Esse cara desaparecerá em[n]breve. Então, será apenas eu neste corpo.[n]Heh heh.[n][w][e]

[msg MSG_HOMELESS_DAY_015_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Nome... meu nome...[n][w][e]
[s][vp 8 2 1 0 30 0]Perguntei à polícia e aquele cara de terno[n]preto com quem conversei outro dia, mas[n]ninguém sabe...[n][w][e]
[s][vp 8 2 1 0 30 0]Alguém... alguém por favor me diga.[n]O que é... qual é o meu nome...?[n][w][e]

[msg MSG_HOMELESS_NIGHT_015_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 0 10]Eu não disse para você não falar com esse[n]dia comigo? Se você precisar de mim, deixe[n]uma carta na lixeira.[n][w][e]

[msg MSG_HOMELESS_NIGHT_015_1 [Agent Suit]]
[s][vp 8 2 1 0 31 0][f 4 23 1 31 5 10 4 10]Desculpe, mas eu precisava confirmar que o[n]ex-mercenário, "Yohei Kiritani", realmente[n]perdeu sua memória.[n][w][e]

[msg MSG_HOMELESS_NIGHT_015_2 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Nunca diga esse maldito nome! Você quer que[n]eu também desponha de você!?[n][w][e]

[msg MSG_HOMELESS_NIGHT_015_3 [Agent Suit]]
[s][vp 8 2 1 0 31 0]O-of-curso não. Eu ficaria impotente se você[n]me visasse...[n][w][e]

[msg MSG_quest29_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Eu acho que temos nosso alvo. Vamos sair de[n]um plano no esconderijo![n][w][e]

[msg MSG_YOKOKUJYOU_GET_HIRU [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Yohei Kiritani? Yohei... algo sobre isso[n]soa...[n][w][e]
[s][vp 8 2 1 0 30 0]É isso... meu nome!? Isso significa que os[n]ladrões fantasmas...?[n][w][e]

[msg MSG_YOKOKUJYOU_GET_YORU [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 0 10]Merda, como eles descobriram meu nome de[n]Frickin?[n][w][e]
[s][vp 8 2 1 0 30 0]Eles vão tentar e me apagar? Tudo bem, vamos[n]lá. Vou descartá-los em vez disso...[n][w][e]

[msg MSG_HOMELESS_DAY_016_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Lembro-me de tudo agora... todas aquelas[n]coisas que eu fiz... ugh, minha cabeça[n]dolorida...[n][w][e]

[sel SEL_HOMELESS_DAY_016_0_0 top]
[s]Você está bem?[e]
[s]Vá ao hospital.[e]

[msg MSG_HOMELESS_DAY_016_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Sim, obrigado... comecei a me sentir mal[n]quando minhas memórias do passado voltassem.[n][w][e]

[msg MSG_HOMELESS_DAY_016_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Agradeço a preocupação, mas... não mereço[n]ser tratado em um hospital...[n][w][e]

[msg MSG_HOMELESS_DAY_016_3_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Em troca de uma pequena quantia em[n]dinheiro...[n]Eu fiz coisas tão terríveis para tantas[n]pessoas...[n][w][e]
[s][vp 8 2 1 0 30 0]Fui salvo por ladrões Phantom?[n]Não pode ser. Eles estão...[n][w][e]

[msg MSG_HOMELESS_DAY_017_0_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ei, você tem uma coisa ou duas do passado...[n]que gostaria de apagar?[n][w][e]

[sel SEL_HOMELESS_DAY_017_0_0 top]
[s]É claro.[e]
[s]Não.[e]
[s]E quanto a você?[e]

[msg MSG_HOMELESS_DAY_017_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Não é tarde demais para você. Você deve[n]resolver as coisas de uma vez por todas.[n][w][e]

[msg MSG_HOMELESS_DAY_017_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Eu vejo... não importa. No entanto, você[n]pode perceber mais tarde que cometeu erros[n]ou se arrepende.[n][w][e]

[msg MSG_HOMELESS_DAY_017_3_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Sim, há coisas que eu gostaria de esquecer.[n]Eu pensei que os havia apagado, mas estava[n]errado.[n][w][e]

[msg MSG_HOMELESS_DAY_017_4_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0]Decidi começar a enfrentar meus próprios[n]crimes a partir de agora. Fui salvo, graças[n]aos ladrões Phantom.[n][w][e]
[s][vp 8 2 1 0 30 0]É por isso que fiquei tão empolgado quando[n]soube que eles estão vivos. Isso realmente[n]me fez feliz.[n][w][e]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ainda és jovem. Certifique-se de viver a[n]vida ao máximo, para que você não tenha[n]arrependimentos como eu.[n][w][e]

[msg MSG_HOMELESS_DAY_018_0_0 [Homeless Man]]
[s][vp 8 2 1 0 65535 0]Ei, você não acha que algo é...[n][w][e]
[s][vp 8 2 1 0 65535 0]Todo mundo parece tão feliz de repente.[n][w][e]
[s][vp 8 2 1 0 65535 0]O que no mundo está acontecendo? É quase[n]assustador...[n][w][e]

[msg MSG_HOMELESS_DAY_019_0_0 [Homeless Man]]
[s][vp 8 2 1 0 65535 0]Pode parecer que não há nada de bom em ficar[n]sem teto no começo.[n][w][e]
[s][vp 8 2 1 0 65535 0]Mas toda a liberdade o torna bastante[n]divertido.[n][w][e]

[sel SEL_HOMELESS_DAY_019_0_0 top]
[s]Você não se lembra mais?[e]
[s]O que está acontecendo?[e]
[s]Tem certeza?[e]

[msg MSG_HOMELESS_DAY_019_1_0 [Homeless Man]]
[s][vp 8 2 1 0 65535 0]Não, não me lembro de nada.[n]Absolutamente nenhuma memória do passado.[n][w][e]
[s][vp 8 2 1 0 65535 0]Mas quero dizer, o que aconteceu no passado[n]não importa, certo?[n]Hahaha...[n][w][e]

[msg MSG_HOMELESS_DAY_019_2_0 [Homeless Man]]
[s][vp 8 2 1 0 65535 0]Eu gostaria de lhe perguntar a mesma coisa.[n]Você me conhece ou algo assim?[n][w][e]
[s][vp 8 2 1 0 65535 0]... Quero dizer, não me lembro de nada sobre[n]o meu passado. Hahaha![n][w][e]

[msg MSG_HOMELESS_DAY_019_3_0 [Homeless Man]]
[s][vp 8 2 1 0 65535 0]Sim, é ótimo não ter que se preocupar com[n]nada. Não tenho lembrança do meu passado,[n]mas isso me faz sentir ainda mais livre![n][w][e]
[s][vp 8 2 1 0 65535 0]Isso prova que o passado não é necessário[n]para continuar vivendo. Você não concorda?[n]Hahaha![n][w][e]

[msg MSG_HOMELESS_DAY_020_0_0 [Homeless Man]]
[s][vp 8 2 1 0 65535 0]Você parece descontente.[n][w][e]
[s][vp 8 2 1 0 65535 0]Eu sempre encontro alguém na cidade com essa[n]expressão, flutuando em um mar de pessoas[n]felizes.[n][w][e]
[s][vp 8 2 1 0 65535 0]Mas com o que vocês estão tão preocupados?[n][w][e]
[s][vp 8 2 1 0 65535 0]Seria muito melhor se você esqueceu todas as[n]coisas ruins e vivesse como eu...[n][w][e]

[msg MSG_HOMELESS_DAY_021_0_0 [Homeless Man]]
[s][vp 8 2 1 0 65535 0]É a temporada para as partidas, hein... Eu[n]me sinto um pouco triste por deixar este[n]lugar.[n][w][e]

[sel SEL_HOMELESS_DAY_021_0_0 top]
[s]Onde você está indo?[e]
[s]Vamos nos encontrar novamente.[e]

[msg MSG_HOMELESS_DAY_021_1_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Não posso expiar meus pecados se me afunde,[n]sendo indeciso. Vou encontrar um emprego em[n]algum lugar quieto.[n][w][e]

[msg MSG_HOMELESS_DAY_021_2_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]É muito bom que eu realmente tenha alguém[n]para me despedir...[n]Obrigada. Significa muito.[n][w][e]

[msg MSG_HOMELESS_DAY_021_3_0 [Homeless Man]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Considerando o quão tolo de um homem eu sou,[n]não tenho certeza se posso expiar meus[n]pecados...[n][w][e]
[s][vp 8 2 1 0 30 0]Mas vou viver o resto da minha vida pensando[n]em como posso fazer isso... adeus, jovem.[n][w][e]
[s][vp 8 2 1 0 30 0]Espero que algum dia eu te veja de novo...[n]Se eu conseguir me tornar um homem decente.[n][w][e]

[msg MSG_Q83_HINT_HOMELESS_00 [Homeless Man]]
[s][vp 1 0 0 0 0 0]HM? Você precisava de algo?[n][w][e]
[s][vp 1 0 0 0 0 0]Uma partida fixa que está ligada ao jogo[n]esportivo? Sim... eu ouvi falar disso.[n][w][e]
[s][vp 8 2 1 0 65535 0]Aparentemente, eles são administrados por[n]uma organização perigosa que geralmente[n]lida com grupos de máfia estrangeiros.[n][w][e]
[s][vp 1 0 0 0 0 0]E ouço que eles fazem ameaças cruéis aos[n]jogadores, especialmente femininos.[n][w][e]

[sel SEL_Q83_HINT_HOMELESS_01 top]
[s]Por exemplo?[e]
[s]Ameaças?[e]

[msg MSG_Q83_HINT_HOMELESS_02 [Homeless Man]]
[s][vp 1 0 0 0 0 0]Como ameaças de morte, se eles perderem,[n]embora eu duvide que eles realmente os[n]matem.[n][w][e]
[s][vp 1 0 0 0 0 0]Bem, como é um acordo fixo, eles não podem[n]ir à polícia. Eles têm que seguir suas[n]próprias regras.[n][w][e]

[msg MSG_CHK_Q83_HINT_HOMELES]
[s][vp 1 0 0 0 0 0]クエスト83 ヒントNPC[n]全部ヒント手に入れた[n][w][e]

[msg MSG_CHK_Q83_HINT_HOMELES_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Parece que temos informações suficientes[n]agora. Vamos para o esconderijo e discutir[n]um plano![n][w][e]

[msg MSG_BACKGROUND_EKIIN_001 [Serious Station Attendant]]
[s][vp 8 2 1 0 17 0]Para a linha Inogami, saia dos portões do[n]outro lado e prossiga.[n][w][e]
[s][vp 8 2 1 0 17 0]Para a linha JL e Ginza, saia desses portões[n]e prossiga para a saída número oito.[n][w][e]

