[msg TEST_MES]
[s]Teste[n][w][e]

[sel YESNO_SEL top]
[s]Sim[e]
[s]Não[e]

[msg D06_04_MOB_MES_mes01 [Cliente]]
[s]M-mas que diabos...? O que[n]é esse vestido estranho?[n]Não me assuste assim.[n][w][e]

[msg D06_04_MOB_MES_mes02 [Cliente]]
[s]Você também é um convidado?[n]Não é um Joker de cassino?[n][w][e]

[msg D06_04_MOB_MES_mes03 [Cliente]]
[s]Isso é um cosplay?[n]Você parece gostar.[n][w][e]

[msg D06_04_MOB_MES_mes04 [Cliente]]
[s]Por que você está vestido assim?[n][w][e]

[msg TEST_VELVET_GIRL_QUIET01 [Justine]]
[s]Pecador preso pelos laços do destino...[n][w][e]
[s]Você não precisa ficar no[n]mundo real. Volte para sua cela[n]e encontre forças para resistir.[n][w][e]

[msg TEST_VELVET_GIRL_QUIET02 [Justine]]
[s]Para mudar seu destino[n]você deve continuar resistindo...[n][w][e]

[msg TEST_VELVET_GIRL_LOUD01 [Caroline]]
[s]Eheh, você realmente tem tempo a[n]perder?[n][w][e]
[s]Volte para o destino legal e desafie![n][w][e]

[msg TEST_VELVET_GIRL_LOUD02 [Caroline]]
[s]Experimente![n]Seu futuro depende disso![n][w][e]

