[msg TEST_MES]
[s]Ele tenta[n][w][e]

[sel YESNO_SEL top]
[s]Sim[e]
[s]Não[e]

[msg D06_06_MOB_MES_mes01 [Cliente]]
[s]Eu realmente gostaria de ir para o plano high[n]stakes ...[n][w][e]

[msg D06_06_MOB_MES_mes02 [Cliente]]
[s]Craps e máquinas caça-níqueis... Aqui[n]é bem diferente dos[n]pisos inferiores![n][w][e]

[msg D06_06_MOB_MES_mes03 [Cliente]]
[s]Hoje a Sorte está do meu[n]lado... Já dobrei[n]minhas moedas![n][w][e]

[msg D06_06_MOB_MES_mes04 [Cliente]]
[s]Que diabos...[n]Não posso vencer![n][w][e]

[msg D06_06_MOB_MES_mes05 [Cliente]]
[s]Eu finalmente ganhei![n]Yuppieeee![n][w][e]

[msg D06_06_MOB_MES_mes06 [Cliente]]
[s]Talvez eu devesse desistir e[n]ir para casa...[n]Não, quero tentar de novo![n][w][e]

[msg D06_06_MOB_MES_mes07 [Cliente]]
[s]Minha habilidade é de pouca[n]utilidade neste andar[n]reservado para membros...[n][w][e]

[msg D06_06_MOB_MES_mes08 [Cliente]]
[s]Mais dinheiro...[n]Preciso de mais dinheiro...[n][w][e]

[msg D06_06_MOB_MES_mes09 [Cliente]]
[s]Para jogar nessa grande[n]caça-níqueis, você precisa de[n]5.000 moedas...[n][w][e]

[msg D06_GREETING_MES_mes01]
[s]No final, apenas[n]pessoas de sucesso conseguem[n]ter sucesso…[n][w][e]

[msg D06_GREETING_MES_mes02]
[s]Ehehe... Ainda hoje[n]vou ganhar muito![n][w][e]

[msg D06_GREETING_MES_mes03]
[s]Só idiotas podem[n]pensar que trabalho é[n]sério.[n][w][e]

[msg D06_GREETING_MES_mes04]
[s]Como tudo depende da[n]sorte, o mundo conta[n]só sorte.[n][w][e]

[msg D06_GREETING_MES_mes05]
[s]Merda, perdi de novo...[n][w][e]

[msg D06_GREETING_MES_mes06]
[s]Só mais uma rodada...[n]Dessa vez eu tenho que vencer![n][w][e]

[msg D06_GREETING_MES_mes07]
[s]OK... se eu conseguir recuperar[n]tudo na próxima volta...[n][w][e]

[msg D06_GREETING_MES_mes08]
[s]Não importa como.[n]O importante é ganhar dinheiro.[n][w][e]

[msg D06_GREETING_MES_mes09]
[s]Muito dinheiro...[n]Sem azar...[n][w][e]

[msg D06_GREETING_MES_mes10]
[s]Se eu ganhar agora,[n]ficarei bilionário...![n][w][e]

[msg D06_GREETING_MES_mes11]
[s]Eu sinto que a sorte da próxima[n]ronda estará[n]do meu lado...[n][w][e]

[msg TEST_VELVET_GIRL_QUIET01 [Justine]]
[s]Pecador preso pelos laços do destino...[n][w][e]
[s]Você não precisa ficar no[n]mundo real. Volte para sua cela[n]e encontre forças para resistir.[n][w][e]

[msg TEST_VELVET_GIRL_QUIET02 [Justine]]
[s]Para mudar seu destino[n]você deve continuar resistindo...[n][w][e]

[msg TEST_VELVET_GIRL_LOUD01 [Caroline]]
[s]Eheh, você realmente tem tempo a[n]perder?[n][w][e]
[s]Volte para o cool e desafie a sua sorte![n][w][e]

[msg TEST_VELVET_GIRL_LOUD02 [Caroline]]
[s]Experimente![n]Seu futuro depende disso![n][w][e]

