[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e800_042[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Acho que ele capturou[n]a verdadeira beleza do ramen...[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que em breve meu vínculo[n]com Yusuke se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e800_042[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Acho que ele capturou[n]a verdadeira beleza do ramen...[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que em breve meu vínculo[n]com Yusuke se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e800_042[n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Acho que ele capturou[n]a verdadeira beleza do ramen...[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que em breve meu vínculo[n]com Yusuke se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e800_042[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Acho que ele capturou[n]a verdadeira beleza do ramen...[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que em breve meu vínculo[n]com Yusuke se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_016_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e800_042[n][f 1 3 65535][w][e]

[msg MND_017_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Acho que ele capturou[n]a verdadeira beleza do ramen...[n][f 1 3 65535][w][e]

[msg MND_018_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que em breve meu vínculo[n]com Yusuke se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_020_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e800_042[n][f 1 3 65535][w][e]

[msg MND_021_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke está à deriva no[n]mar de sabores...[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Acho que ele capturou[n]a verdadeira beleza do ramen...[n][f 1 3 65535][w][e]

[msg MND_022_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que em breve meu vínculo[n]com Yusuke se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_024_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e800_042[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke está à deriva no[n]mar de sabores...[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Acho que ele capturou[n]a verdadeira beleza do ramen...[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que em breve meu vínculo[n]com Yusuke se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e800_042[n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Acho que ele capturou[n]a verdadeira beleza do ramen...[n][f 1 3 65535][w][e]

[msg MND_030_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que em breve meu vínculo[n]com Yusuke se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_032_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e800_042[n][f 1 3 65535][w][e]

[msg MND_033_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Acho que ele capturou[n]a verdadeira beleza do ramen...[n][f 1 3 65535][w][e]

[msg MND_034_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que em breve meu vínculo[n]com Yusuke se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_036_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e800_042[n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Acho que ele capturou[n]a verdadeira beleza do ramen...[n][f 1 3 65535][w][e]

[msg MND_038_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que em breve meu vínculo[n]com Yusuke se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Estou muito cheio... Obrigado[n]por hoje. Até mais.[n][f 1 3 65535][w][e]

