[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 4105 65535 0]Este lugar está lotado.[n]Caldo de galinha temperado com[n]molho de soja...?[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nunca achei[n]ramen particularmente gostoso...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Enfim... vamos entrar na fila?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 4135 65535 0]Quantas nuances do mundo[n]eu desconhecia... Quem diria que[n]simples ramen era tão rico...[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O sabor delicado e perfumado é[n]uma explosão de aromas... O soberbo[n]noodle aquece-me a alma...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tal harmonia de sabores é[n]inesquecível. Que maneira sublime[n]de recuperar nutrientes![n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 0 8 2 1 2217]Nutrientes?[clr 27][e]
[s]Talvez você esteja exagerando.[e]
[s][f 0 8 2 1 2217]Como um crítico gastronômico.[clr 27][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4168 65535 0][f 5 13 5 10 5]Sim. Eu sempre sigo[n]uma dieta frugal,[n]alimentos baratos e nutritivos são ideais.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu consumo principalmente brotos de feijão. Eles[n]são baratos, saborosos e ricos em fibras.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 4173 65535 0][f 5 13 5 5 5]O que há de errado em expressar[n]minha alegria? Comida e arte desempenham[n]papéis semelhantes na vida![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]É importante elogiar as coisas[n]que você aprecia, sabe?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0][f 5 13 5 10 5]Ah, seria perfeito como um[n]trabalho de meio período! Eles me pagariam e[n]economizariam dinheiro em comida...![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No entanto, duvido que tenha[n]os requisitos necessários...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Isso não importa. Foi uma refeição incrivelmente[n]deliciosa! Obrigado por me trazer aqui.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sinto que a partir de agora[n]poderei continuar[n]fazendo o meu melhor.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4050 65535 0]Bem, acho que[n]devemos ir.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][vp 8 2 0 4045 65535 0]Tenho que ir para casa e começar a[n]pintar até ficar satisfeito![n][f 1 3 65535][w][e]

