[msg MSG_000_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 10081 65535 0]Entendi! Os preços são muito[n]baixos em sebos![n][f 1 3 65535][w][e]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mmm, há muitos aqui.[n]Quais eu poderia usar[n]como inspiração?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Autobiografias históricas.[e]
[s][f 0 8 2 1 2217]Livros de empreendedores.[clr 27][e]
[s]O que está na moda.[e]

[msg MSG_002_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10020 65535 0][f 5 13 11 10 1013]A vida daqueles que marcaram[n]seu nome na história...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]É verdade que vale a pena lê-los[n]pelo menos uma vez. Há muito a[n]aprender com essas vidas tumultuadas![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 10116 65535 0][f 5 13 11 15 1013]H-Ha, um manual de uma pessoa de sucesso? Às[n]vezes as pessoas pedem-me previsões sobre o[n]trabalho...[n][f 1 3 65535][w][e]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No entanto, como nunca tive um emprego "normal", muitas vezes não sei o que devo dizer.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Definitivamente valeria a pena[n]ler![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10020 65535 0][f 5 13 11 10 1013]Mmm, livros tão recentes que[n]eu poderia ler rapidamente para[n]compreender o pensamento comum.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Muitas vezes acontece que um[n]cliente baixa a guarda[n]para conversar um pouco...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sim, pode ser uma boa ideia[n]consultar livros recém-publicados.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você conhece livros de autoajuda?[n][f 1 3 65535][w][e]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você os lê e se pega pensando que isso é o[n]suficiente. No final você não se ajuda em nada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Gostaria de aprender as ideias contidas[n]esses livros e usá-las para[n]ajudar meus clientes.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hum?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A placa daquele[n]livro usado diz "Estudo do Destino"![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas... uma loja especializada em[n]vidência? [f 4 1]-san,[n]vamos dar uma olhada![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Chihaya]]
[s][vp 8 2 0 10048 65535 0]Este lugar é como[n]uma segunda casa...[n]Muito obrigado por hoje.[n][f 1 3 65535][w][e]

