[msg MSG_000_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3019 65535 0]Que ambiente animado![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu me pergunto se as pessoas são atraídas para cá[n]pelo fato de que este lugar está sempre na moda.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Moda, comida... o que mais?[n]Vamos fazer um tour! Podemos[n]encontrar algo interessante![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3048 65535 0]Crepes, panquecas e parfaits![n]Estavam todos deliciosos...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu quase não ousei comê-los[n]como eles eram fofos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]E todos aqueles clientes sorridentes...[n]Vê-los me deixou feliz.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Eu acho que entendi.[e]
[s]Por quê?[e]
[s][f 0 8 2 1 2217]Você também estava sorrindo.[clr 27][e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3001 65535 0][f 5 13 4 10 7]Sério?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas sim, claro... O sorriso dos[n]outros é a maior recompensa[n]para os aliados da justiça.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3127 65535 0][f 5 13 4 5 7]Você não acha ótimo[n]quando as pessoas sorriem[n]por causa do seu trabalho?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Achei que você entenderia,[n]vendo o que você faz[n]com os Phantom Thieves.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 3024 65535 0][f 5 13 4 15 7]Hã? Eu não percebi.[n][f 1 3 65535][w][e]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Seja como for, é ótimo poder[n]fazer os clientes sorrirem.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quem trabalha quer que as pessoas[n]valorizem o que fazem, enquanto[n]outros pagam para serem felizes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]São desejos inerentes à[n]natureza humana. Vir aqui[n]me ajudou a descobrir.[n][f 1 3 65535][w][e]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Muito obrigado por me convidar.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3018 65535 0]U-Uhm, tem outro lugar[n]que me intriga... tudo bem para você[n]se formos lá também?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Haru]]
[s][vp 8 2 0 3028 65535 0]É tão bom poder[n]comer comida deliciosa.[n][f 1 3 65535][w][e]

