[msg MSG_000_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3028 65535 0]Aaah, que cheirinho delicioso.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você não acha que os santuários têm um cheiro[n]misterioso? Talvez seja por causa das árvores?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 0 8 2 1 2217]Que tipo de cheiro?[clr 27][e]
[s][f 0 8 2 1 2217]Você está absolutamente certo.[clr 27][e]
[s]O ar é especial...[e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3111 65535 0][f 5 13 4 10 7]Hmm... É como caminhar por[n]uma poça de energia condensada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sabe, esse lugar me fez[n]pensar que um[n]casamento xintoísta seria legal...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3035 65535 0][f 5 13 4 10 7]Já! Isso não lhe dá a sensação[n]de que há algo[n]fora do comum?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu entendo porque algumas[n]pessoas querem celebrar[n]seu casamento em tais lugares...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3192 65535 0][f 5 13 4 5 7]O que pode ser? Isso me deixa tensa, mas no bom sentido...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Na verdade, já vi um[n]casamento aqui antes... Foi[n]uma experiência muito especial.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aliás, um dia a gente[n]cresce e casa também, né?[n][f 1 3 65535][w][e]

[msg MSG_006_5_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Acho que vou querer celebrar[n]meu casamento aqui. E convidarei todos os[n]outros Ladrões Fantasmas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Afinal, se eu tivesse[n]minha vida de volta...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...é graças a você.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3048 65535 0]Vamos, por que não visitamos melhor o santuário?[n]Eu amo explorar lugares de poder![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Haru]]
[s][vp 8 2 0 3049 65535 0]Tudo bem, vamos para casa.[n][f 1 3 65535][w][e]

