[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4135 65535 0]É difícil acreditar que Harajuku[n]está aqui. Este[n]silêncio é sobrenatural...[n][f 1 3 65535][w][e]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah entendi! É por isso que a[n]religião sempre foi um[n]tópico central na arte.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Talvez os artistas tenham capturado[n]algo particular...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Devemos fazer uma oferta.[n]Existe algum desejo que você[n]faria, [f 4 2]?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Boas notas.[e]
[s]Uma linda namorada.[e]
[s][f 0 8 2 1 2217]Muito dinheiro.[clr 27][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0][f 5 13 5 5 5]Você não acha que deveria[n]ganhá-lo com[n]seu esforço pessoal?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tudo o que você precisa fazer é estudar.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0][f 5 13 5 5 5]Você diz que pode ser obtido[n]por meio de orações?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O que você faria se quem você quisesse[n]estivesse rezando para nunca[n]acabar com você?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 4040 65535 0][f 5 13 5 10 5]Hmm![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E-eu estou um pouco... Na verdade,[n]eu perguntaria a mesma coisa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Porém...como eu me considero[n]um artista, devo me sustentar[n]inteiramente com a arte...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Confiando em um deus... Mmm.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Parece sublime, mas na realidade[n]não é nada especial: é[n]um sofisma disfarçado de oração.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aquele desequilíbrio... A inquietação[n]que agita no fundo[n]do coração humano...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mmm... pode não[n]ser uma coisa ruim.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Isso me lembra, [f 4 2]...[n]Eles dizem que mesmo a oferta de um[n]iene concede favor divino, certo?[n][f 1 3 65535][w][e]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu daria mais lances para[n]melhor sorte financeira, mas agora[n]até cinco ienes é muito para mim.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah bem. Os deuses[n]certamente entenderão minha terrível[n]situação econômica.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4079 65535 0]Aqui, [f 4 2].[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Afinal, você planta o que colhe. Para ganhar,[n]você deve gastar primeiro.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][vp 8 2 0 4182 65535 0]Ah, alguém deixou cair[n]uma moeda de dez ienes.[n]Lucky.[n][f 1 3 65535][w][e]

