[msg MSG_000_0_0 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57058 65535 0]Uau...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Que vista incrível! Você pode imaginar ser[n]tão alto?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Você não se importa com altura?[e]
[s][f 0 8 2 1 2217]É uma visão e tanto.[clr 27][e]
[s]B-mas se caímos...[e]

[msg MSG_003_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 5 13 33 10 10]Sim. Se alguma coisa, eles me fazem sentir[n]mais confortável.[n][f 1 3 65535][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 24 0 4 0 42 3 100]A partir daqui, parece tão diferente das[n]ruas que conhecemos, não é?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57026 65535 0][f 5 13 33 15 10]Sim, podemos ver tudo a partir daqui.[n]É meio bonito, à sua maneira.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 24 0 4 0 42 3 100]Você também gosta de altura, Senpai?[n]Estou feliz em ouvir isso.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sumire]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 5 13 33 10 10]Oh... você está ruim com altura?[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Devo dizer que é uma surpresa saber que você[n]tem uma fraqueza.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Por alguma razão, sou o oposto.[n]Olhar para baixo de um lugar alto me ajuda a[n]me sentir otimista e centralizado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]É como... um lembrete de que nosso mundo é[n]muito maior do que o que vemos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]E isso é o suficiente para eu pensar: "Ainda[n]posso continuar".[n][f 1 3 65535][w][e]

[msg MSG_006_5_0 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Então... estou muito, muito feliz que você[n]me trouxe aqui. Eu amo lugares assim![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sumire]]
[s][vp 8 2 0 57169 65535 0]Muito obrigado por sair hoje.[n][f 1 3 65535][w][e]

