[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2128 65535 0]Estamos indo do caminho certo? Eu sinto que[n]vamos nos perder.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hmmm... passamos por um portão azul, então[n]acho que estamos em Chinatown agora, certo?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Havia algo que eu queria experimentar[n]aqui... HM, o que foi?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2129 65535 0]Pães de porco? Bolinhos de gergelim?[n]Não, não é isso... desculpe, está[n]completamente escorregou minha mente...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Possui camarão e repolho por dentro, e é[n]embrulhado em papel de arroz...[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Pato de Pequim?[e]
[s]Rolos de ovo?[e]
[s][f 0 8 2 1 2217]Rolinho primavera?[clr 27][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 3 5 6]Não exatamente. O invólucro que você usa[n]para o pato de Pequim é feito de farinha,[n]não arroz.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh... eu me lembro agora! Rolinho primavera![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 3 5 6]Oh, isso foi perto! Eu estava pensando em[n]rolinhos primavera![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A parte do rolo me ajudou a lembrar![n]Obrigado pela dica.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 3 15 6]É isso! Não sei por que esqueci o nome.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu sei que posso obtê-los em Tóquio, mas[n]posso muito bem ter um chinês autêntico[n]aqui...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2119 65535 0]O que está errado? Você está franzindo a[n]testa.[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Não é chinês.[e]
[s][f 0 8 2 1 2217]Vamos encontrar alguns.[clr 27][e]
[s]Eu não gosto de coentro...[e]

[msg MSG_009_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 3 5 6]... Oh, eles são vietnamitas! Por que eu[n]achava que eles eram chineses...?[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Na verdade... espere um segundo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]China e Vietnã estão próximos um do outro.[n]Talvez ainda possamos encontrar alguns[n]aqui...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 3 10 6]Oh, espere... os rolinhos primavera não são[n]vietnamitas...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sis ficaria brava comigo se eu cometesse um[n]erro como este em um exame... então[n]novamente...[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]China e Vietnã estão próximos um do outro.[n]Talvez ainda possamos encontrar alguns[n]aqui...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 3 5 6]Coentro...? Espere um segundo...[n]Os rolinhos primavera são vietnamitas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*suspiro* Por que eu os confundi...? Não,[n]espere...[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]China e Vietnã estão próximos um do outro.[n]Talvez ainda possamos encontrar alguns[n]aqui...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por que não começamos a procurar?[n]Isto vai ser divertido.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se vamos nos perder, podemos nos perder[n]completamente.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2118 65535 0]Vamos lá, vamos começar com aquela rua ali![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2019 65535 0]Aqui, este é um presente para você.[n]Era tão fofo que eu não pude deixar de[n]comprá-lo.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][vp 8 2 0 2198 65535 0]Deveríamos ir para casa... mas qual é a[n]estação?[n][f 1 3 65535][w][e]

