[msg MSG_000_0_0 [Kawakami]]
[s][bup 0 109 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Que comece a batalha![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 15090 65535 0]Macarrão, bolo, omelete com[n]arroz frito... Meu oponente[n]é um habilidoso chef...[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Você vai comer tudo isso?[e]
[s][f 0 8 2 1 2217]Não exagere.[clr 27][e]
[s]Você vai se sentir mal de novo.[e]

[msg MSG_002_0_0 [Kawakami]]
[s][bup 0 109 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]Aproveitar uma oportunidade como[n]esta é a melhor forma[n]de combater o estresse, sabia?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Kawakami]]
[s][bup 0 109 501 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 15 15 1009]Hehehe. Não, não.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esta é uma batalha...[n]De fato, uma guerra total[n]entre o açúcar e o estresse![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Kawakami]]
[s][bup 0 109 501 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]Não se preocupe. Vou beber um[n]oolong tea[n]e não terei problemas.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Kawakami]]
[s][bup 0 109 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Você precisa comer direito também, ok?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu sei que você está muito ocupado,[n]mas não vou deixar você sucumbir[n]à desnutrição.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E agora, coma o quanto quiser.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kawakami]]
[s][bup 0 109 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 15098 65535 0]...Sinto-me culpado por todas[n]as preocupações que lhe dou.[n][f 1 3 65535][w][e]
[s][bup 0 109 501 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 1 5 0]Aqui a comida é muito boa, então[n]comemos o quanto quisermos e recuperamos[n]um pouco de energia![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Kawakami]]
[s][vp 8 2 0 15164 65535 0]Fiuuu... estou cheio![n]Vamos para casa, certo?[n][f 1 3 65535][w][e]

