[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Aceite-me um sorriso.[n][f 1 3 65535][w][e]
[s][f 5 13 14 10 1008][vp 8 0 0 0 65535 0]Ela parece gostar das minhas reações[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que meu vínculo[n]com Takemi se fortalecerá em breve...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Takemi]]
[s][vp 8 2 0 14054 65535 0]Bem, até mais.[n][f 1 3 65535][w][e]

[msg MND_003_5_0]
[s][vp 8 0 0 0 65535 0]Acompanhei Takemi[n]à sua clínica...[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Boneco[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Aceite-me um sorriso.[n][f 1 3 65535][w][e]
[s][f 5 13 14 10 1008][vp 8 0 0 0 65535 0]Ela parece gostar das minhas reações[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Sinto que meu vínculo[n]com Takemi se fortalecerá em breve...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Takemi]]
[s][vp 8 2 0 14054 65535 0]Você nunca é chato, sabia?[n]Bem, até mais.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]Acompanhei Takemi[n]à sua clínica...[n][f 1 3 65535][w][e]

