[msg MSG_000_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Uau, então é assim que se faz! Eu pensei que era[n]apenas merchandising de anime ...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas vejo que não é assim. Eles também vendem[n]muitas roupas.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oooh, que chapéu legal.[n]Talvez eu devesse comprá-lo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, eu conheço esse personagem![n]Ele vai para uma escola de magia,[n]certo? Quantas lembranças![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ei, olha essa camisa![n]"Todo ouriço é um capricho". É feito[n]apenas para você! Hahaha![n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 0 8 2 1 2217]Que bom que você está se divertindo.[clr 27][e]
[s]Você é um nerd?[e]
[s]Estou comprometido com esses cachos.[e]

[msg MSG_003_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]Hã? O-Oh, estou ficando muito animado?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]É só... me surpreende o quão[n]divertido é. Estou começando a entender as[n]pessoas que frequentam este lugar.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 15 5 1009]Não! Honestamente, eu não sei muito sobre[n]esse tipo de coisa...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mas você não acha excitante, de certa forma? É como entrar em uma caixa de brinquedos.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 15 5 1009]poxa! Eu pensei que eles eram naturais. Você está[n]procurando aquele visual desalinhado tão na moda[n]entre os jovens de hoje?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Enfim... É divertido[n]olhar vitrines por aqui.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu estava me perguntando como era desde que[n]ouvi sobre isso[n]de um dos meus alunos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eu não queria vir sozinho,[n]por isso te convidei.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Acabou sendo mais engraçado do que eu esperava. É[n]como eu descobri um novo mundo![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Kawakami]]
[s][vp 8 0 0 0 65535 0]Obrigado por ter vindo.[n][f 1 3 65535][w][e]

