[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Fictício [n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Futaba parece estar de bom humor...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 10 10 8]Parece que ela encontrou uma estátua em[n]tamanho real de seu personagem favorito...[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Eu sinto que meu vínculo com Futaba ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][vp 8 2 0 9050 65535 0]Feito! Vamos para casa![n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Fictício [n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Futaba parece estar de bom humor...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 10 10 8]Parece que ela encontrou uma estátua em[n]tamanho real de seu personagem favorito...[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Eu sinto que meu vínculo com Futaba ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][vp 8 2 0 9050 65535 0]Feito! Vamos para casa![n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]Fictício [n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]Futaba parece estar de bom humor...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 10 10 8]Parece que ela encontrou uma estátua em[n]tamanho real de seu personagem favorito...[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]Eu sinto que meu vínculo com Futaba ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][vp 8 2 0 9050 65535 0]Feito! Vamos para casa![n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]Fictício [n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Futaba parece estar de bom humor...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 10 10 8]Parece que ela encontrou uma estátua em[n]tamanho real de seu personagem favorito...[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0]Eu sinto que meu vínculo com Futaba ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][vp 8 2 0 9050 65535 0]Feito! Vamos para casa![n][f 1 3 65535][w][e]

[msg MND_016_0_0]
[s][vp 8 0 0 0 65535 0]Fictício [n][f 1 3 65535][w][e]

[msg MND_017_0_0]
[s][vp 8 0 0 0 65535 0]Futaba conseguiu se acalmar um pouco...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 10 10 8]Parece que a atmosfera desta área é[n]reconfortante para ela...[n][f 1 3 65535][w][e]

[msg MND_018_0_0]
[s][vp 8 0 0 0 65535 0]Eu sinto que meu vínculo com Futaba ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Futaba]]
[s][vp 8 2 0 9050 65535 0]Feito! Vamos para casa![n][f 1 3 65535][w][e]

[msg MND_020_0_0]
[s][vp 8 0 0 0 65535 0]Fictício [n][f 1 3 65535][w][e]

[msg MND_021_0_0]
[s][vp 8 0 0 0 65535 0]Futaba conseguiu se acalmar um pouco...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 10 10 8]Parece que a atmosfera desta área é[n]reconfortante para ela...[n][f 1 3 65535][w][e]

[msg MND_022_0_0]
[s][vp 8 0 0 0 65535 0]Eu sinto que meu vínculo com Futaba ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Futaba]]
[s][vp 8 2 0 9050 65535 0]Feito! Vamos para casa![n][f 1 3 65535][w][e]

[msg MND_024_0_0]
[s][vp 8 0 0 0 65535 0]Fictício [n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]Futaba conseguiu se acalmar um pouco...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 10 10 8]Parece que a atmosfera desta área é[n]reconfortante para ela...[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]Eu sinto que meu vínculo com Futaba ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Futaba]]
[s][vp 8 2 0 9050 65535 0]Feito! Vamos para casa![n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]Fictício [n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][vp 8 0 0 0 65535 0]Futaba parece estar de bom humor...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 10 10 8]Parece que ela encontrou uma estátua em[n]tamanho real de seu personagem favorito...[n][f 1 3 65535][w][e]

[msg MND_030_0_0]
[s][vp 8 0 0 0 65535 0]Eu sinto que meu vínculo com Futaba ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Futaba]]
[s][vp 8 2 0 9050 65535 0]Feito! Vamos para casa![n][f 1 3 65535][w][e]

[msg MND_032_0_0]
[s][vp 8 0 0 0 65535 0]Fictício [n][f 1 3 65535][w][e]

[msg MND_033_0_0]
[s][vp 8 0 0 0 65535 0]Futaba parece estar de bom humor...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 10 10 8]Parece que ela encontrou uma estátua em[n]tamanho real de seu personagem favorito...[n][f 1 3 65535][w][e]

[msg MND_034_0_0]
[s][vp 8 0 0 0 65535 0]Eu sinto que meu vínculo com Futaba ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Futaba]]
[s][vp 8 2 0 9050 65535 0]Feito! Vamos para casa![n][f 1 3 65535][w][e]

[msg MND_036_0_0]
[s][vp 8 0 0 0 65535 0]Fictício [n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][vp 8 0 0 0 65535 0]Futaba parece estar de bom humor...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 10 10 8]Parece que ela encontrou uma estátua em[n]tamanho real de seu personagem favorito...[n][f 1 3 65535][w][e]

[msg MND_038_0_0]
[s][vp 8 0 0 0 65535 0]Eu sinto que meu vínculo com Futaba ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Futaba]]
[s][vp 8 2 0 9050 65535 0]Feito! Vamos para casa![n][f 1 3 65535][w][e]

