[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Shinya está tocando silenciosamente...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 17 5 1010]Tocamos arma com foco intenso...[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Eu sinto que meu vínculo com Shinya ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Shinya]]
[s][vp 8 2 0 17053 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Shinya está tocando silenciosamente...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 17 5 1010]Tocamos arma com foco intenso...[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Eu sinto que meu vínculo com Shinya ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Shinya]]
[s][vp 8 2 0 17053 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]Shinya está tocando silenciosamente...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 17 5 1010]Tocamos arma com foco intenso...[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Eu sinto que meu vínculo com Shinya ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Shinya]]
[s][vp 8 2 0 17053 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Shinya está tocando silenciosamente...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 17 5 1010]Tocamos arma com foco intenso...[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Eu sinto que meu vínculo com Shinya ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Shinya]]
[s][vp 8 2 0 17053 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_016_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_017_0_0]
[s][vp 8 0 0 0 65535 0]Shinya tem um olhar sério em seu rosto...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 17 5 1010]Tocamos arma com foco intenso...[n][f 1 3 65535][w][e]

[msg MND_018_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Eu sinto que meu vínculo com Shinya ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Shinya]]
[s][vp 8 2 0 17053 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_020_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_021_0_0]
[s][vp 8 0 0 0 65535 0]Shinya está usando uma expressão sombria...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 17 5 1010]Tocamos arma com foco intenso...[n][f 1 3 65535][w][e]

[msg MND_022_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Eu sinto que meu vínculo com Shinya ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Shinya]]
[s][vp 8 2 0 17053 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_024_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]Shinya está usando uma expressão sombria...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 17 5 1010]Tocamos arma com foco intenso...[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Eu sinto que meu vínculo com Shinya ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Shinya]]
[s][vp 8 2 0 17053 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][vp 8 0 0 0 65535 0]Shinya está usando uma expressão sombria...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 17 5 1010]Tocamos arma com foco intenso...[n][f 1 3 65535][w][e]

[msg MND_030_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Eu sinto que meu vínculo com Shinya ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Shinya]]
[s][vp 8 2 0 17053 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_032_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_033_0_0]
[s][vp 8 0 0 0 65535 0]Shinya parece estar cheio de energia...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 17 5 1010]Tocamos arma com foco intenso...[n][f 1 3 65535][w][e]

[msg MND_034_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Eu sinto que meu vínculo com Shinya ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Shinya]]
[s][vp 8 2 0 17053 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_036_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][vp 8 0 0 0 65535 0]Shinya parece que ele está se divertindo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 17 5 1010]Tocamos arma com foco intenso...[n][f 1 3 65535][w][e]

[msg MND_038_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Eu sinto que meu vínculo com Shinya ficará[n]mais forte em breve...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Shinya]]
[s][vp 8 2 0 17053 65535 0]Sair com você nunca é chato, [n][f 4 1]-san. Bem, veja você.[n][f 1 3 65535][w][e]

