[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Kawakami limpou meu quarto.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]Ela parece feliz que eu[n]a solicitei...[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Sinto que em breve meu vínculo[n]com Kawakami se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Kawakami]]
[s][vp 8 2 0 15160 65535 0]Obrigado pela preferência![n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Kawakami limpou meu quarto.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]Ela parece feliz que eu[n]a solicitei...[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Sinto que em breve meu vínculo[n]com Kawakami se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Kawakami]]
[s][vp 8 2 0 15160 65535 0]Obrigado pela preferência![n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]Kawakami limpou meu quarto.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]Ela parece feliz que eu[n]a solicitei...[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Sinto que em breve meu vínculo[n]com Kawakami se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Kawakami]]
[s][vp 8 2 0 15160 65535 0]Obrigado pela preferência![n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Kawakami parece desconfortável.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]Mas ela também parece feliz que[n]eu a solicitei...[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Sinto que em breve meu vínculo[n]com Kawakami se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Kawakami]]
[s][vp 8 2 0 15064 65535 0]Bem, até mais...[n]*suspiro*[n][f 1 3 65535][w][e]

[msg MND_016_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_017_0_0]
[s][vp 8 0 0 0 65535 0]Kawakami parece feliz que[n]ele solicitou.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]É minha imaginação,[n]ou está cansado?[n][f 1 3 65535][w][e]

[msg MND_018_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Sinto que em breve meu vínculo[n]com Kawakami se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Kawakami]]
[s][vp 8 2 0 15064 65535 0]Bem, até mais...[n]*suspiro*[n][f 1 3 65535][w][e]

[msg MND_020_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_021_0_0]
[s][vp 8 0 0 0 65535 0]Kawakami parece feliz que[n]ele solicitou.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]É minha imaginação,[n]ou parece ruim?[n][f 1 3 65535][w][e]

[msg MND_022_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Sinto que em breve meu vínculo[n]com Kawakami se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Kawakami]]
[s][vp 8 2 0 15064 65535 0]Bem, até mais...[n]*suspiro*[n][f 1 3 65535][w][e]

[msg MND_024_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]Kawakami está feliz[n]por eu ter solicitado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]Como estou preocupado com ela,[n]resolvi deixá-la descansar...[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Sinto que em breve meu vínculo[n]com Kawakami se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Kawakami]]
[s][vp 8 2 0 15031 65535 0]...Obrigado.[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][vp 8 0 0 0 65535 0]Kawakami parece distraído.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]Passamos o tempo[n]conversando sobre coisas diferentes...[n][f 1 3 65535][w][e]

[msg MND_030_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Sinto que em breve meu vínculo[n]com Kawakami se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Kawakami]]
[s][vp 8 2 0 15054 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_032_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_033_0_0]
[s][vp 8 0 0 0 65535 0]Kawakami parece desconfortável.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]Passamos o tempo[n]conversando sobre coisas diferentes...[n][f 1 3 65535][w][e]

[msg MND_034_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Sinto que em breve meu vínculo[n]com Kawakami se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Kawakami]]
[s][vp 8 2 0 15054 65535 0]Até mais.[n][f 1 3 65535][w][e]

[msg MND_036_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][vp 8 0 0 0 65535 0]Kawakami parece aliviado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 15 10 1009]Passamos o tempo[n]conversando sobre coisas diferentes...[n][f 1 3 65535][w][e]

[msg MND_038_0_0]
[s][vp 8 0 0 0 65535 0][f 5 13 0 5 0]Sinto que em breve meu vínculo[n]com Kawakami se fortalecerá...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Kawakami]]
[s][vp 8 2 0 15054 65535 0]Obrigado pela preferência![n]Piada. Até mais...[n][f 1 3 65535][w][e]

