[msg D01_02_e129_060_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7192 65535 0]The trainin' hall's up ahead, right?[n][w][e]

[msg D01_02_e129_060_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yeah, it's a little further. Make sure you[n]watch out for any guards along the way.[n][w][e]

[msg D01_02_129_061_mes01 [Armored Soldier]]
[s][vp 1 0 0 1 0 0]Hey, have you seen anyone who looks like[n]an intruder?[n][w][e]

[msg D01_02_129_061_mes02 [Armored Soldier]]
[s][vp 1 0 0 2 0 0]No, nobody yet...[n][w][e]

[msg D01_02_129_061_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Shoot... I had a feeling there would be[n]a lot of enemies. It'd be impossible to[n]dodge all of them...[n][w][e]

[msg D01_02_129_061_mes04 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]Then, what do we do? Should we try and[n]take 'em down like before?[n][w][e]

[msg D01_02_129_061_mes05 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]It's not that simple. We still have a long[n]way to go, so we should be conserving[n]energy.[n][w][e]

[msg D01_02_129_061_mes06 [Ryuji]]
[s][bup 0 2 3 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]I-I see... Sorry...[n][w][e]
[s][bup 0 2 5 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 7 0 0]Dammit, I wish I could fight... I'd at least[n]be able to help out a little bit...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 8 0 0]But all I got is this toy from earlier...[n]I'm such a loser.[n][w][e]

[msg D01_02_129_061_mes07 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 9 0 0]Huh? Do you mean that gun?[n][w][e]

[msg D01_02_129_061_mes08 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 10 0 0]Yeah... It looks real n' all, but it doesn't[n]shoot anything...[n][w][e]

[msg D01_02_129_061_mes09 [Morgana]]
[s][bup 0 3 8 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 11 0 0]I see... Well, there is a way...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 12 0 0]Okay, we'll use that to take down[n]the enemies![n][w][e]

[msg D01_02_129_061_mes10 [Ryuji]]
[s][bup 0 2 4 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 13 0 0]What!? Were you listenin' to me?[n]It don't even shoot pellets...[n][w][e]

[msg D01_02_129_061_mes11 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 14 0 0]Don't worry, I'm sure this'll work.[n]Attack away, Frizzy Hair![n][w][e]

[sel D01_02_129_061_selA top]
[s]Leave it to me.[e]
[s]What're we going to do?[e]

[msg D01_02_129_061_selA_0_me [Ryuji]]
[s][bup 0 2 4 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 15 0 0]Dude! I-I keep sayin', it's not gonna[n]fire anything![n][w][e]

[msg D01_02_129_061_selA_1_me [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 16 0 0]Just trust me! Let's do this![n][w][e]

[msg D01_02_129_061_selA_1_me_2 [Ryuji]]
[s][bup 0 2 4 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 17 0 0]Wait, dude! I keep sayin', it's not gonna[n]fire anything![n][w][e]

[msg D01_02_e129_062_mes01 [Ryuji]]
[s][bup 0 2 4 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]Whoa! Did that toy gun just shoot real[n]freakin' BULLETS!?[n][w][e]

[msg D01_02_e129_062_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is a cognitive world.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As long as our opponent sees it as real,[n]it becomes such. It's a good thing it's[n]realistic-looking.[n][w][e]

[msg D01_02_e129_062_mes03 [Ryuji]]
[s][bup 0 2 5 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...I don't get it.[n][w][e]

[msg D01_02_e129_062_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1150 65535 0]Because they recognize it as a gun, your[n]ammo capacity is limited in battle.[n][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But your enemies are expecting you to[n]come at them with guns loaded, so your[n]ammo's replenished in every new fight.[n][w][e]

[msg D01_02_e129_062_mes07 [Armored Soldier]]
[s]What's this commotion over here...?[n][w][e]

[msg D01_02_e129_062_mes08 [Armored Soldier]]
[s]Wha—!? Why, you bastards![n][w][e]

[msg D01_02_e129_062_mes09 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Get ready, here comes another one![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1106 65535 0]Take 'em down![n][w][e]

[msg D01_02_e129_063_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1163 65535 0]Just like I thought, all our ammo had[n]returned for that fight.[n][w][e]

[msg D01_02_e129_063_mes02 [Ryuji]]
[s][bup 0 2 1 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I wasn't sure whether or not to bring it[n]at first, but I'm sure glad I did.[n][w][e]

[msg D01_02_e129_063_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1166 65535 0]We're definitely lucky to have the[n]additional firearm in our arsenal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I must say, well done—even if it was just[n]dumb luck that it worked here.[n][w][e]

[msg D01_02_e129_063_mes04 [Ryuji]]
[s][bup 0 2 11 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Did you really have to put it like that?[n][w][e]

[msg D01_02_e129_063_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quit griping, Blondie. You're still getting[n]praised.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh by the way, we should decide how[n]we divvy up our roles in battle from here[n]on out.[n][w][e]

[msg D01_02_e129_063_mes06 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As you can see, there are quite a lot of[n]enemies. It'll be important to coordinate[n]our moves well.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I can keep providing intel for us, but you[n]should decide how we fight, Frizzy Hair.[n][w][e]

[msg D01_02_e129_063_mes07 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Whaddya mean by "how we fight"?[n][w][e]

[msg D01_02_e129_063_mes08 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Basically, what we do in battle. He can[n]order us directly, or let us decide what[n]we do.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Though I guess I'm the only other one[n]fighting right now.[n][w][e]

[msg D01_02_e129_063_mes09 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]What's the plan? Want me following[n]orders, or acting on my own?[n][w][e]

[sel D01_02_e129_063_sel top]
[s]Direct commands[e]
[s]Act freely[e]

[msg D01_02_e129_063_mes10_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1035 65535 0]Understood! Let's see what you've got.[n][w][e]

[msg D01_02_e129_063_mes10_01 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1034 65535 0]Sounds good to me! I've got this.[n][w][e]

[msg D01_02_e129_064_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]All right, this is it![n][w][e]

[msg D01_02_e129_064_mes02 [Ryuji]]
[s][bup 0 2 2 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Kamoshida's... Training Hall... of Love?[n]What kinda bullshit is this!?[n][w][e]

[msg D01_02_e129_065_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]A guard... I'm pretty sure that's where we[n]need to be going, too...[n][w][e]

[msg D01_02_e129_065_mes02 [Ryuji]]
[s][bup 0 2 1 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]You guys gonna take it down again?[n][w][e]

[msg D01_02_e129_065_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]I guess that's our only choice... But wait,[n]this might be a good time...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]Okay, I've decided! I'm gonna teach you[n]two a special way to fight enemies![n][w][e]

[sel D01_02_e129_065_selA top]
[s]Is it a new technique?[f 2 7 0 0 106 1][e]
[s]I'll pass.[f 2 7 0 0 106 1][e]

[msg D01_02_e129_065_selA_0_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Something like that! Let's go![n][w][e]

[msg D01_02_e129_065_selA_1_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]Don't be so modest! This one's on[n]the house. Let's go![n][w][e]

[msg D01_02_e129_066_mes01 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Mm, that went really well! You're[n]definitely fit for this.[n][w][e]

[msg D01_02_e129_066_mes02 [Ryuji]]
[s][bup 0 2 4 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]What was that SUPER MOVE thing[n]you just did!?[n][w][e]

[msg D01_02_e129_066_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]I told you, it's called an All-Out Attack.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]If you manage to knock all the enemies[n]down, you might be able to use it to beat[n]them all at once.[n][w][e]

[msg D01_02_e129_066_mes04 [Ryuji]]
[s][bup 0 2 4 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Yeah, that was over quick![n][w][e]

[msg D01_02_e129_066_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]It's a concentrated attack on defenseless[n]enemies, after all.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 7 0 0]Now as I mentioned before, I want you[n]to be the head of our command. You can[n]decide when we use this.[n][w][e]

[sel D01_02_e129_066_selA top]
[s]All right.[e]
[s]That's too much trouble.[e]

[msg D01_02_e129_066_selA_1_m [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 8 0 0]Wouldn't it be more trouble defeating[n]them individually? Just accept your new[n]role with grace.[n][w][e]

[msg D01_02_e129_066_mes06 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 9 0 0]Strike the enemy's weakness, knock them[n]all down, then do an All-Out Attack! That's[n]the ideal pattern![n][w][e]

[msg Attack_Tutorial [Attacking]]
[s]Approach an enemy and press[n][f 1 10 22] to commence a battle.[n][w][e]

[msg AI_change_Tutorial [Giving Orders to Teammates]]
[s]Ally AI can be changed under [clr 2]PARTY[clr 27][n]in the main menu or [clr 2]TACTICS[clr 27] under[n][clr 2]ORDERS[clr 27] on the protagonist's turn.[n][w][e]

[msg TUTORIAL_MSG01]
[s]Tutorials you have seen before can be viewed[n]in the main menu. Press [f 1 10 12] to open the menu[n]and select [clr 2]System[clr 27], and then [clr 2]Tutorial[clr 27].[n][w][e]

