[msg D01_03_e161_011_mes01 [Metaverse Navigator]]
[s]This is the return point for[n]Kamoshida's Palace.[n][w][e]

[msg D01_03_e161_011_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Hm? What're you doin'?[n][w][e]

[sel D01_03_e161_011_selA top]
[s]This is the return point.[e]
[s]Let's go back.[e]
[s]Nothing.[e]

[msg D01_03_e161_011_selA_0_m [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7021 65535 0]Oh, so we can go back to reality if we use[n]the Metaverse Nav here.[n][w][e]

[msg D01_03_e161_011_selA_0_m_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But we just came in. C'mon, let's look[n]for that Treasure thing.[n][w][e]

[msg D01_03_e161_011_selA_1_m [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]C'mon, we just came in here.[n][w][e]

[msg D01_03_e161_011_selA_1_m_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's go look for that[n]Treasure thing instead.[n][w][e]

[msg D01_03_e161_011_selA_2_m [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7022 65535 0]Oh, okay.[n][w][e]

[msg D01_03_e161_011_selA_2_m_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, let's sneak in and look for that[n]Treasure thing![n][w][e]

[msg D01_03_e161_011_AF_mes01]
[s]It seems we can return to the[n]real world if we decide to use the[n]Metaverse Nav here.[n][w][e]
[s]However, it would be best[n]not to head back right now.[n][w][e]

[msg D01_03_e161_012_mes01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7047 65535 0]It's lookin' like this door still won't open.[n][w][e]

[msg D01_03_e161_012_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Didn't I tell you last time not to go in the[n]front too?[n][w][e]

[msg D01_03_e161_012_mes03 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ugh, I remember! Anyways, let's sneak[n]in the same way as last time![n][w][e]

[msg D01_03_e161_012_mes04]
[s]It seems as though this[n]door won't open...[n][w][e]
[s]We should probably use[n]another way to sneak in...[n][w][e]

