[msg D05_02_e341_024_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]Look, there're a ton of 'em... You wanna[n]start takin' their IDs?[n][w][e]

[msg D05_02_e341_024_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Not yet. If we go instead to their origin,[n]there should be even more "employees"[n]for us.[n][w][e]

[msg D05_02_e341_024_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2197 65535 0]Oh, great idea. That should make it even[n]easier to find a chief director! Let's head[n]over there, Joker.[n][w][e]

[msg LOCK_OFF_mes01]
[s]>本攻略では、オフィスでキーアイテム入手後[n] ロックを解除します。[n][w][e]

