[msg D07_35_MOUSEALERT_mes01 [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Look out. Run![n][w][e]

[msg D07_35_MOUSEALERT_mes02 [Ryuji]]
[s]Look out. Run![n][w][e]

[msg D07_35_MOUSEALERT_mes03 [Yusuke]]
[s]Look out. Run![n][w][e]

[msg D07_35_MOUSEALERT_mes04 [Haru]]
[s]Look out. Run![n][w][e]

[msg D07_35_MOUSEALERT_mes05 [Ann]]
[s]Look out. Run![n][w][e]

[msg D07_35_MOUSEALERT_mes06 [Morgana]]
[s]Look out. Run![n][w][e]

[msg D07_35_MOUSEALERT_mes07 [Makoto]]
[s]Look out. Run![n][w][e]

