[msg D159_02_npc_01_mes01 [Masked Guest]]
[s]What an odd costume. Is that what you[n]young people are into nowadays?[n][w][e]

[msg D159_02_npc_02_mes01 [Masked Guest]]
[s]Who are you? Don't think you can talk[n]to an honored guest of Mr. Shido so[n]casually.[n][w][e]

[msg D159_02_npc_03_mes01 [Masked Guest]]
[s]My, that was quite a show! Are you[n]entertainers?[n][w][e]

[msg D159_02_npc_03_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]Joker, we should go. It would be[n]a problem if we started drawing[n]attention to ourselves.[n][w][e]

