[msg D08_02_e454_010_mes01 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The other Phantom Thieves should be[n]imprisoned somewhere ahead.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Please find them... Save them...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is something only you can do...[n][w][e]

[msg D160_10_NPC_01_A_mes01 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We can speak in more detail once you've[n]rescued your teammates.[n][w][e]

[msg D160_10_NPC_02_A_mes01 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The other Phantom Thieves should be[n]imprisoned somewhere ahead.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Please find them... Save them...[n][w][e]

[msg D160_10_NPC_02_B_mes01 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Some of your teammates are still trapped[n]in the prison. Please save them all...[n][w][e]

[msg D160_10_c_01_mes01]
[s]The door is tightly sealed...[n][w][e]

