[msg D04_BRIEFING_010_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, don't this Palace feel kinda[n]different from all the other ones[n]we've been in up 'til now?[n][w][e]

[msg D04_BRIEFING_010_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Absolutely. The ruler of this one is a[n]complete mystery... Just what does[n]she want to do with us?[n][w][e]

[msg D04_BRIEFING_010_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Beats me.[n][w][e]

[msg D04_BRIEFING_010_mes04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anyway, we should try heading up those[n]stairs again.[n][w][e]

