[msg D05_02_e341_032_mes01 [???]]
[s]WHO ARE YOU? I DON'T RECALL[n]MAKING PLANS FOR VISITORS.[n][w][e]

[sel D05_02_e341_032_selA top]
[s]We're salesmen.[e]
[s]We're employees.[e]
[s]We're burglars.[e]

[msg D05_02_e341_032_selA_0_m [???]]
[s]IS THAT SO? YOU MUST BE HARD[n]WORKERS IF YOU'VE COME TO SELL[n]WITHOUT AN APPOINTMENT.[n][w][e]
[s]I'LL GLADLY LISTEN TO WHAT YOU[n]HAVE TO SAY. NOW THEN... DID[n]YOU BRING ANY GIFTS FOR ME?[n][w][e]

[msg D05_02_e341_032_selA_1_m [???]]
[s]I SEE, YOU ARE EMPLOYEES...[n]OR SO YOU CLAIM! NONE OF MY[n]UNDERLINGS DRESS SO ODDLY![n][w][e]
[s]YOU MUST BE INDUSTRY SPIES![n]I WON'T LET YOU LEAVE ALIVE![n][w][e]

[msg D05_02_e341_032_selA_1_m_2 [Haru]]
[s][bup 0 7 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3180 65535 0]Our only option now is to fight...! Let's[n]go, Joker![n][w][e]

[msg D05_02_e341_032_selA_2_m [???]]
[s]WHAT!? IN THAT CASE, I CANNOT LET[n]YOU LEAVE WITHOUT REPERCUSSIONS![n][w][e]

[msg D05_02_e341_032_selA_2_m_2 [Haru]]
[s][bup 0 7 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3180 65535 0]It looks like we just have to fight![n]Let's go, Joker![n][w][e]

[sel D05_02_e341_032_selB top]
[s]We have sweets.[e]
[s]We have spicy food.[e]
[s]We have gold.[e]

[msg D05_02_e341_032_selB_0_m [???]]
[s]AH, YOU ARE QUITE IN THE KNOW. I'M A[n]CONNOISSEUR OF ALL THINGS [clr 2]SWEET[clr 27].[n][w][e]
[s]I CAN'T HELP BUT CHOW DOWN[n]ON THEM WHEN I'M [clr 2]STRESSED[clr 27]![n][w][e]

[msg D05_02_e341_032_selB_1_m [???]]
[s]SPICY, HM? I SUPPOSE THAT IS[n]ACCEPTABLE. NOW THEN, WHAT[n]HAVE YOU BROUGHT TO SELL?[n][w][e]

[msg D05_02_e341_032_selB_2_m [???]]
[s]YOU YOUNG PEOPLE ARE SO[n]ILL-EDUCATED. I'M NOT IN THE[n]BUSINESS OF ACCEPTING BRIBES.[n][w][e]
[s]WHAT COMPANY ARE YOU FROM? I[n]DEMAND TO SEE A BUSINESS CARD.[n][w][e]

[msg D05_02_e341_032_selB_2_m_2 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Ugh, what a pain in the ass. We're[n]gonna have to fight, Joker![n][w][e]

[msg D05_02_e341_032_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]It is time we make our decision, Joker.[n]What do you want to do?[n][w][e]

[sel D05_02_e341_032_selC top]
[s]Let's fight him.[f 2 7 0 0 106 1][e]
[s]We should leave.[f 2 7 0 0 106 1][e]

[msg D05_02_e341_032_selC_0_m [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Right, there's no need for any more[n]discussion. Take him down![n][w][e]

[msg D05_02_e341_032_selC_1_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1163 65535 0]So you don't want to fight right now?[n]Then let's retreat![n][w][e]

[msg D05_02_e341_032_selC_1_m_2 [???]]
[s]HM? WHAT IS THE MATTER? DID[n]YOU FORGET SOMETHING?[n][w][e]

[msg D05_02_e342_end_mes01 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7028 65535 0]Man, what a pain... Huh?[n][w][e]

[msg D05_02_e342_end_mes02 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, this must be an employee ID card![n]Let me see... It says chief clerk on it.[n][w][e]

[msg D05_02_e342_end_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But we're looking for one that's chief[n]director or higher, yes?[n][w][e]

[msg D05_02_e342_end_mes04 [Futaba]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9021 65535 0]This one should be okay for now. At the[n]very least it'll help us get to some new[n]places.[n][w][e]

[msg D05_02_e342_end_mes05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yes, we can now enter areas restricted to[n]those of chief clerk rank or lower now.[n][w][e]

[msg D05_02_e342_end_mes06 [Speakers]]
[s]TIME FOR A SHIFT CHANGE! TIME[n]FOR A SHIFT CHANGE![n][w][e]
[s]EVERYONE, MOVE STATIONS! CONTINUE[n]WORKING UNTIL YOU DIE![n][w][e]

[msg D05_02_e342_end_mes07 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7182 65535 0]Wait, what? Shifts...?[n][w][e]

[msg D05_02_e342_end_mes08 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, it said to move stations... Perhaps[n]the rooms we have already entered will[n]have different robots.[n][w][e]

[msg D05_02_e342_end_mes09 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]We should go check it out.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, and don't forget to look for places[n]we can get into with that fancy new[n]employee ID card.[n][w][e]

[msg D156_13_miniEV05_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7020 65535 0]Huh. I'm thinkin' we can tell whether[n]they're the target if we can [clr 2]squeeze[clr 27][n][clr 2]some info outta 'em[clr 27].[n][w][e]

[msg D156_13_miniEV05_mes01_2 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7079 65535 0]Well, we ended up fightin' anyways,[n]but I think this is prolly a good way[n]of doin' this.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We can prolly tell whether they're the[n]target if we can [clr 2]squeeze some info outta[clr 27][n][clr 2]'em[clr 27] before we fight.[n][w][e]

[msg D156_13_miniEV05_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's right! We might be able to avoid[n]unnecessary battles if we [clr 2]cross-reference[clr 27][n][clr 2]that information[clr 27]![n][w][e]

[msg D05_02_e341_031_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]We can't get through here. Is this a rank[n]authentication device as well?[n][w][e]

[msg D05_02_e341_031_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yeah, you've gotta be a chief clerk or[n]higher. Basically, we'll need an employee[n]ID card for this.[n][w][e]

[msg D05_02_e341_031_mes03 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7194 65535 0]Ugh, you gotta be kiddin' me! Are all[n]companies like this!?[n][w][e]

[msg D05_02_e341_031_mes04 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...I believe our security in the real world[n]is even stricter.[n][w][e]

[msg D05_02_e341_031_mes05 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7174 65535 0]For real...?[n][w][e]

[msg D05_02_e341_031_mes06 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're gonna need an employee ID that's[n]chief clerk or higher to get through here,[n]Joker.[n][w][e]

[msg D05_02_e341_031_clear_me [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3045 65535 0]Yes, it opened![n][w][e]

[msg D05_02_e341_031_clear_me_2 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We might end up getting a chief[n]director ID eventually if we keep[n]getting higher and higher ranks![n][w][e]

[msg D05_02_e341_031_clear_me_3 [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2035 65535 0]Agreed. Let's go about this one step[n]at a time.[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, and if you're feeling tired, be sure[n]to stop in at a safe room, Joker.[n][w][e]

