[msg e382_300_mes01 [Shadow]]
[s]Welcome to the Battle Arena, the[n]infernal fighting ground where[n]the embers of life glow bright.[n][w][e]
[s]Oh, it's you guys... Our manager[n]told us about you.[n][w][e]

[msg e382_300_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7043 65535 0]Huh? The hell've you been[n]hearin' about us!?[n][w][e]

[msg e382_300_mes03 [Shadow]]
[s]My, you're so quick to anger.[n]Wonderful. This would be quite[n]boring if that wasn't the case.[n][w][e]

[msg e382_300_mes04 [Shadow]]
[s]Now, allow me to confirm something[n]before I begin explaining... Do you[n]currently have [clr 2]10,000[clr 27] coins?[n][w][e]

[msg e382_300_mes05 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uhhh, what? We don't.[n][w][e]

[msg e382_300_mes06 [Shadow]]
[s]Well that won't do at all. This is[n]out of the question if you don't[n]have enough for the entry fee.[n][w][e]
[s]Now listen up: Come back here[n]once you have that amount.[n][w][e]

[msg e382_300_mes07 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, it seems the games on this floor[n]all require participation fees...[n][w][e]

[msg e382_300_mes08 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, it seems this game requires[n]a participation fee...[n][w][e]

[msg e382_300_mes09 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2099 65535 0]Oh well. We need to play by the[n]rules, so let's go find somewhere[n]we can win the necessary coins.[n][w][e]

[msg e382_300_mes10 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3164 65535 0]Oh! Yes, we do![n][w][e]

[msg e382_300_mes11 [Shadow]]
[s]Oh, you have surely been busy.[n]Very well then, allow me to[n]explain this game to you.[n][w][e]
[s]Here, you will prove your supremacy[n]in a trio of fierce one-on-one battles.[n][w][e]
[s]Then again... this is the pinnacle[n]of our casino, the high limit floor.[n][w][e]
[s]Normally, our VIPs would prepare[n]substitutes who fight to the[n]death for their sake...[n][w][e]
[s]The attending guests then bet coins[n]on who they think will win.[n][w][e]

[msg e382_300_mes12 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Here too...? Ugh, this shit makes me sick.[n][w][e]

[msg e382_300_mes13 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The entirety of this floor must be like that.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Taking little risk for a high return is[n]truly the optimal business strategy.[n][w][e]

[msg e382_300_mes14 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But can we even participate if we[n]don't have a substitute...?[n][w][e]

[msg e382_300_mes15 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]Hey, we didn't need one[n]for the other game![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The same probably applies in here too.[n][w][e]

[msg e382_300_mes16 [Shadow]]
[s]As irritating as it may be, that is correct.[n]Please participate.[n][w][e]
[s]Registration will take place[n]at the counter over there.[n][w][e]

