[msg QUEST_19_ENTER_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]There it is. It's Jochi's Shadow.[n][w][e]

[msg QUEST_19_ENTER_mes01f [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Jochi's Shadow. Found you.[n][w][e]

[msg QUEST_19_ENTER_mes02 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4035 65535 0]Judging from the smirk on his face, it looks[n]like he's scheming something awful.[n][w][e]

[msg QUEST_19_ENTER_mes03 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]I heard he was threatenin' this old couple,[n]tryin' to kick them out of their own movie[n]theater.[n][w][e]

[msg QUEST_19_ENTER_mes04 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]If we leave him alone, he may resort[n]to violence.[n][w][e]

[msg QUEST_19_ENTER_mes05 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6183 65535 0]We can't let that happen! Let's go![n][w][e]

[sel SEL_070_0_0 top]
[s]Give it up.[e]
[s]Get out of Yongen.[e]
[s]I can't answer that.[e]

[msg MSG_016_0_0 [Shadow Jochi]]
[s][vp 8 2 1 46810 65535 0]Ah, so you're the Phantom Thieves. I'm[n]not sure what you'd want with me, though.[n][w][e]

[msg MSG_017_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][vp 1 0 0 0 0 0]It seems like you're trying to use force to[n]get people to leave their property?[n][w][e]

[msg MSG_018_0_0 [Shadow Jochi]]
[s][vp 1 0 0 0 0 0]Land development is important. Getting[n]rid of stubborn people in my way is part[n]of the job.[n][w][e]
[s][vp 1 0 0 0 0 0]I'm not just playing around, like you kids[n]are doing![n][w][e]

[msg MSG_019_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][vp 1 0 0 0 0 0]We're quite serious. We can't let those[n]who cause problems for others to go[n]unpunished.[n][w][e]
[s][vp 1 0 0 0 0 0]That includes people like you, who use[n]bullying tactics to get what they want.[n][w][e]

[msg MSG_020_0_0 [Shadow Jochi]]
[s][vp 1 0 0 0 0 0]You're just pissy-smelling kids acting big.[n]You should've stopped playing hero back[n]in preschool![n][w][e]

[msg MSG_022_0_0 [Shadow Jochi]]
[s][vp 1 0 0 0 0 0]*sob* But if they don't give up the land,[n]I'm going to get fired...[n][w][e]
[s][vp 1 0 0 0 0 0]Please, isn't there some way I can have[n]that movie theater?[n][w][e]

[sel SEL_023_0_0 top]
[s]Give it up.[e]
[s]Get out of Yongen.[e]
[s]I can't answer that.[e]

[msg MSG_024_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Yeah, know when to give up.[n][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1156 65535 0]Yeah, stop messing around with our[n]neighborhood.[n][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7157 65535 0]Yeah, you should've tried talkin' to[n]everyone in the shopping district, nicely.[n][w][e]

[msg MSG_027_0_0 [Shadow Jochi]]
[s][vp 1 0 0 0 0 0]Oh, er, I'm sorry. I'll give up. So please,[n]forgive me...[n][w][e]

[msg MSG_028_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][vp 1 0 0 0 0 0]I hope you'll consider the feelings of[n]those who get things taken from them[n]from now on.[n][w][e]

[msg MSG_029_0_0 [Shadow Jochi]]
[s][vp 8 2 1 46817 65535 0]I-I got it...[n][w][e]
[s][vp 1 0 0 0 0 0]I'll be honest with my superiors. I'll tell[n]them that no one has any interest in[n]leaving Yongen...[n][w][e]

[msg MSG_030_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][vp 1 0 0 0 0 0]Not just Yongen! You better make up for[n]the awful things you've done elsewhere,[n]too![n][w][e]

