[msg D06_12_e382_220_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo, Joker, there's some kinda vent over[n]here too.[n][w][e]

[msg D06_12_e382_220_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Might as well take the playin' card with us![n][w][e]

[msg D06_12_e382_220_mes03 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm? Joker, look over there.[n][w][e]

[msg D06_12_e382_220_mes04 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That decoration seems similar to where[n]we found the vent earlier...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's difficult to know if they are related,[n]but perhaps we should examine it and[n]find out.[n][w][e]

