[msg dummy_mes]
[s]......[n][w][e]

[msg D10_11_keeper_Clear_star [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, we took it down somehow. I think[n]we can get to the Will Seed now.[n][w][e]

[msg D10_11_keeper_Clear_end [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54503 65535 0]No sense leaving something we can use[n]behind.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's ours now.[n][w][e]

