[msg D159_07_npc_01_mes01 [Masked Guest]]
[s]*chuckle* Gazing upon this scenery[n]makes me truly feel that I'm one of[n]the chosen ones.[n][w][e]

[msg D159_07_npc_02_mes01 [Masked Guest]]
[s]Oh dear, I got far too excited in the[n]entertainment hall. I should cool down[n]here for a while.[n][w][e]

[msg D159_07_npc_03_mes01 [Masked Guest]]
[s]That man had so many tattoos...[n]And his mannerisms were quite[n]preposterous as well...[n][w][e]
[s]But I suppose if he's on this ship,[n]Mr. Shido must accept him...[n][w][e]

[msg D159_07_npc_04_mes01 [Bartender]]
[s]Welcome, sir. The back deck is just[n]this way.[n][w][e]
[s]We are currently on special alert, but[n]do not mind us. Please make yourself[n]at home.[n][w][e]

[msg D159_07_npc_05_mes01 [Bartender]]
[s]The entertainment hall is just near here.[n][w][e]
[s]We have various games there, including[n]slot machines. I suggest you head there[n]if you are bored.[n][w][e]

