[msg D01_04_e160_051_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hold on, Joker![n][w][e]

[msg D01_04_e160_051_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1148 65535 0]Can we look around a little more before[n]he head back? There might be a hidden[n]path we can take.[n][w][e]

[msg D01_04_e159_020_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7021 65535 0]Man, this place is crawlin' with Shadows[n]like always.[n][w][e]

[msg D01_04_e159_020_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Right, but they won't notice us from[n]where we are now. This is a great[n]infiltration point![n][w][e]

[sel D01_04_e159_020_selA top]
[s]It's thanks to Panther.[e]
[s]This is useful.[e]
[s]Let's keep going.[e]

[msg D01_04_e159_020_selA_0_m [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6027 65535 0]Huh? Oh right, that's me![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm... I'm still not really used to that[n]name...[n][w][e]

[msg D01_04_e159_020_selA_0_m_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7095 65535 0]Either way, it's prolly good we got a[n]hang of this place's layout when we[n]came in here before.[n][w][e]

[msg D01_04_e159_020_selA_1_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1022 65535 0]True. We might be able to get to some[n]places we haven't checked yet from here.[n][w][e]

[msg D01_04_e159_020_selA_1_m_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Either way, it's prolly good we got a[n]hang of this place's layout when we[n]came in here before.[n][w][e]

[msg D01_04_e159_020_selA_2_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1047 65535 0]Hm? You seem fired up, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Still, if we're not careful, we'll end up[n]getting chased out just like last time.[n][w][e]

[msg D01_04_e159_020_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6019 65535 0]Our objective now is to find the Treasure,[n]right?[n][w][e]

[msg D01_04_e159_020_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm-hm.[n][w][e]

[msg D01_04_e159_020_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As I said before, we need to find the[n]Treasure as well as secure a route to[n]its location.[n][w][e]

[msg D01_04_e159_020_mes06 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7192 65535 0]I don't get what you're talkin' about with[n]all that securin' a route stuff...[n][w][e]

[msg D01_04_e159_020_mes07 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'll teach you once we find the Treasure.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's not like you would understand if I[n]tried to teach you everything at once.[n][w][e]

[msg D01_04_e159_020_mes08 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yeah, I guess that's true... Hold on, it[n]feels like you're makin' fun of me for[n]some reason...[n][w][e]

[msg D01_04_e159_020_mes9 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anyway, let's just keep doing what[n]Mona tells us.[n][w][e]

[msg D01_04_e159_020_mes10 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Guess we gotta look for places we[n]haven't checked yet then.[n][w][e]

