[msg D156_13_miniEV01_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Look, Joker! That dude seems different[n]from the others.[n][w][e]

[msg D156_13_miniEV01_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Skull's actually right for once. Is that[n]the [clr 2]chief director[clr 27]?[n][w][e]

[msg D156_13_miniEV01_mes03 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, shall we defeat him and find out?[n]We should be able to check his [clr 2]employee[clr 27][n][clr 2]ID[clr 27] after.[n][w][e]

[msg D156_13_miniEV01_mes04 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There's no need to waste our energy[n]like that.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We may be able to tell who he is just by[n][clr 2]talking[clr 27] to him...[n][w][e]

[msg D156_013_miniEV02_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There's another one! It looks way[n]different from the others.[n][w][e]

[msg D156_013_miniEV02_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The one from earlier was a [clr 2]chief clerk[clr 27].[n]What rank is this one?[n][w][e]

[msg D156_013_miniEV02_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I don't know, but we need intel first.[n]Let's try talking without raising any[n]suspicions.[n][w][e]

[msg D156_13_miniEV03_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]Oh crap, that thing's huge![n]What's with him!?[n][w][e]

[msg D156_13_miniEV03_mes02 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Could that be a higher rank...?[n][w][e]

[msg D156_13_miniEV03_mes03 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3020 65535 0]If size shows the importance Father[n]places on them, I suppose he should[n]be quite high up...[n][w][e]

[msg D156_13_miniEV03_mes04 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're just gonna have to talk to him and[n]find out.[n][w][e]

