[msg D04_03_e295_081_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4158 65535 0]Hm, this may come in handy somewhere.[n]Shall we take it?[n][w][e]

[sel D04_03_e295_081_selA top]
[s]Take the gem[e]
[s]Don't take the gem[e]

[msg D04_03_e295_081_selA_0_m [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Very well. This may prove to be an object[n]of great import.[n][w][e]

[msg D04_03_e295_081_selA_1_m [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4020 65535 0]I see. We should at least remember[n]where this is. It may prove to be an[n]object of great import.[n][w][e]

[msg MSG_e295_081_AF01_000 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm? Have you decided to take the gem?[n][w][e]

[msg MSG_e295_081_AF02_000 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2089 65535 0]What's up, Joker? Think we should put[n]the gem we took back in here?[n][w][e]

[sel SEL_e295_081_AF02_001 top]
[s]Absolutely.[e]
[s]Nah, it's fine.[e]

[msg MSG_e295_081_AF02_002 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2090 65535 0]There we go, back to how it was before.[n]Well, let's go.[n][w][e]

[msg MSG_e295_081_AF02_003 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2023 65535 0]Let's go, then.[n][w][e]

[msg MSG_e295_082_000 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]So, do you think we should take[n]this gem?[n][w][e]

[sel SEL_e295_082_001 top]
[s]Take the gem[e]
[s]Don't take the gem[e]

[msg MSG_e295_082_002 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]All right. Let's grab it and continue[n]onward.[n][w][e]

[msg MSG_e295_082_003 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1023 65535 0]Oh, really? I guess we can just leave it be[n]for now, then.[n][w][e]

[msg MSG_e295_082_AF01_000 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What's up, Joker? Are you going to take[n]the gem after all?[n][w][e]

[msg MSG_e295_082_AF02_000 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What, are you thinking about putting[n]the gem back in here?[n][w][e]

[sel SEL_e295_082_AF02_001 top]
[s]Put it back[e]
[s]Don't put it back[e]

[msg MSG_e295_082_AF02_002 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aaand, it's like we never took it to[n]begin with. Let's go![n][w][e]

[msg MSG_e295_082_AF02_003 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, let's keep it then![n][w][e]

[msg D04_03_e295_081_AF03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We already used the gem that we got[n]from here. I don't think we have any[n]more business with this.[n][w][e]

[msg D04_03_e295_082_AF03_mes [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We've already put the gem from this[n]statue to good use. I doubt there's[n]anything else to be done.[n][w][e]

[msg D04_03_e295_081_FIRST_me [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]It's holdin' something... Wait, what is[n]this statue anyways? Some kinda dog...[n]thing?[n][w][e]

[msg D04_03_e295_081_FIRST_me_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is Anubis, the Egyptian god of the[n]underworld. It seems to have some[n]kind of shining orb...[n][w][e]

[msg D04_03_e295_081_FIRST_me_3 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6021 65535 0]That sounds kinda familiar. Something[n]about light from the god of the[n]underworld?[n][w][e]

[msg D04_03_e295_081_SECOND_m [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7020 65535 0]Huh, this statue's the same weird dog[n]thing as before. And look, it's got one[n]of them gems too![n][w][e]

[msg D04_03_e295_081_SECOND_m_2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The god's name is Anubis. It really isn't[n]that hard to remember, Skull...[n][w][e]

