[msg D08_01_e440_010_mes02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]Whoa, what the hell!? What's goin' on!?[n][w][e]

[msg D08_01_e440_010_mes03 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Calm down. It doesn't seem like it's a trap[n]or anything.[n][w][e]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Try touching it again, Joker.[n][w][e]

[msg D08_01_e440_010_mes04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6194 65535 0]It's back to normal? Just what was that...?[n][w][e]

[msg D08_01_e440_010_mes05 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hmmm. There seems to be more to this[n]prison, but right now this is a dead end[n]for some reason.[n][w][e]

[msg D08_01_e440_010_mes06 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Then this must be a security system. Will[n]we be able to proceed if we disable it?[n][w][e]

[msg D08_01_e440_010_mes07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Prolly. I'll need you to look into it a[n]little more though.[n][w][e]
[s][vp 8 2 1 9196 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Do it again, Joker. It looks like touching[n]it turns it back off, so it can't be that[n]dangerous, right?[n][w][e]

[msg D08_01_e440_112_mes01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9034 65535 0]Okay, now try walking around.[n][w][e]

[msg D08_01_e440_016_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]Whoa, it opened! You did it![n][w][e]

[msg D08_01_e440_016_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So that device is not only a switch, but[n]also the wall that's blocking our path.[n][w][e]

[msg D08_01_e440_016_mes03 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's a pretty elaborate device...[n][w][e]

[msg D08_01_e440_016_mes04 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4021 65535 0]It is only natural that security is tight in a[n]prison. Then again, no inmates actually[n]wish to leave...[n][w][e]

[msg D08_01_e440_016_mes05 [Warden's Voice]]
[s]They've broken through our safety net![n]Head to the scene at once! Don't let them[n]escape![n][w][e]

[msg D08_01_e440_016_mes06 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7175 65535 0]Ugh, can't you just try takin' it easy on us[n]this time!?[n][w][e]

