[msg D10_BRIEFING_150_mes01 [[f 4 31 10 0]]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57045 65535 0]After seeing what happened that day...[n]All these memories are flooding back...[n][w][e]
[s][bup 0 10 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But now, I'm more determined[n]than ever.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Everything I was feeling back then...[n]I don't want to lose that again.[n][w][e]

[msg D10_BRIEFING_150_mes02 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1045 65535 0]Heh, you've got guts, all right![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'd rather not let Violet's groove go to[n]waste—let's move out![n][w][e]

