[msg D07_BRIEFING_005_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So, we gotta find five targets before[n]we can get the Treasure.[n][w][e]

[msg D07_BRIEFING_005_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Considering how big this ship is, looking[n]for them won't be easy.[n][w][e]

[msg D07_BRIEFING_005_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But no matter what, we gotta beat the[n]crap outta this Palace ruler. We're takin'[n]that Treasure![n][w][e]

[msg D07_BRIEFING_005_mes04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Right! We can do it, together![n][w][e]

