[msg D08_01_e437_101_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]The hell is this place...?[n][w][e]

[msg D08_01_e437_101_mes02 [Ann]]
[s][bup 0 4 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's so creepy...[n][w][e]

[msg D08_01_e437_101_mes03 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So those strange pipes tunneling through[n]Mementos were originating from down[n]here after all.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You know, I have been considering[n]this for some time... They remind[n]me somewhat of veins.[n][w][e]

[msg D08_01_e437_101_mes04 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6198 65535 0]More importantly, what's up with this[n]scenery? What kind of distortion is this?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I mean, what does everyone think this[n]world is...!?[n][w][e]

[msg D08_01_e437_101_mes05 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Calm down, Lady Ann. The Treasure[n]is definitely here, and that's what's[n]important now.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]And I can sense something else.[n]A tremendous presence that's coming[n]from much deeper within...[n][w][e]

[msg D08_01_e437_101_mes06 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2193 65535 0]I don't know that I want to find out what[n]that may be, but we must harden our[n]resolves.[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's time to head for the depths![n][w][e]

