[msg D05_BRIEFING_070_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7024 65535 0]Dude, I could totally get used to all[n]this flyin' through space shit! But we're[n]almost at the end...[n][w][e]

[msg D05_BRIEFING_070_mes02 [Futaba]]
[s][bup 0 8 105 0 0]......[n][w][e]

[msg D05_BRIEFING_070_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You don't look so good, Oracle.[n]Is everything okay?[n][w][e]

[msg D05_BRIEFING_070_mes04 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]She must have gotten motion sickness...[n][w][e]

[msg D05_BRIEFING_070_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's not much further to the Treasure.[n]Hang in there, Oracle![n][w][e]

[msg D05_BRIEFING_070_mes06 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm... I'll try.[n][w][e]

