[msg D04_01_e293_020_mes01 [Ryuji]]
[s][bup 0 2 1 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7020 65535 0]Whoa, it's so nice inside! Is this place[n]air conditioned or something!?[n][w][e]

[msg D04_01_e293_020_mes02 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It may be because Futaba's room[n]in reality has AC pumping through it.[n]Either way, this is a relief...[n][w][e]

[msg D04_01_e293_020_mes03 [Ann]]
[s][bup 0 4 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh, our clothes still haven't changed[n]even now. This has never happened[n]to us before.[n][w][e]

[msg D04_01_e293_020_mes04 [Yusuke]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4128 65535 0]It is refreshing that she doesn't see us[n]as a threat... but we are completely[n]surrounded by walls.[n][w][e]

[msg D04_01_e293_020_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I guess this is a tomb... It's probably not[n]made to be easy to get into. Anyway,[n]let's explore.[n][w][e]

[msg D04_01_e293_201_mes01 [Ann]]
[s][bup 0 4 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6162 65535 0]These stairs go pretty far.[n][w][e]

[msg D04_01_e293_201_mes02 [Ryuji]]
[s][bup 0 2 5 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There's way too goddamn many...[n][w][e]

[msg D04_01_e293_201_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Don't ask for too much. You should be[n]happy we're not being attacked as we[n]ascend.[n][w][e]

[msg D04_01_e293_201_mes04 [Morgana]]
[s][bup 0 3 8 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1171 65535 0]More importantly, I can totally sense[n]the Treasure ahead. We're getting[n]pretty close now![n][w][e]

[msg D04_01_e293_201_mes05 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]These stairs seem to be headed into[n]the heart of the pyramid.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I wonder if that's where the Treasure[n]waits...[n][w][e]

[msg D04_01_e293_201_mes06 [Ryuji]]
[s][bup 0 2 1 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7172 65535 0]Welp, time to keep climbin' then.[n]Let's go.[n][w][e]

[msg D04_01_e293_025_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm? There's someone there![n][w][e]

