[msg D10_009_HuddleTalk_first [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1172 65535 0]All right, let's figure this out.[n][w][e]

[msg D10_009_HuddleTalk_first_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So, after some investigating, I think[n]they use this place to test patients'[n]mental states with a questionnaire.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If they find any abnormalities, they will[n]force treatment right away—not sure what[n]it is, but I suspect we should avoid it.[n][w][e]

[msg D10_009_HuddleTalk_first_3 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3127 65535 0]So if Dr. Maruki thinks we're fine as[n]we are, we get to skip the treatment?[n][w][e]

[msg D10_009_HuddleTalk_first_4 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Most likely.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It may not be easy, but we'll have to[n]try to think like Dr. Maruki whenever[n]coming up with our responses.[n][w][e]

[msg D10_009_HuddleTalk_first_5 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7021 65535 0]Sorry, Joker, but I ain't any good at[n]this kinda stuff. The questionnaire's[n]all yours, dude.[n][w][e]

[sel HUDDLE_AGENDA_SEL top]
[s]Let's review what we know.[e]
[s]Let's pick our answer.[e]
[s]Let's end the discussion here.[e]

[sel HUDDLE_NPC_SEL top]
[s]Strong-Willed Man[e]
[s]Reserved Man[e]
[s]Change the topic[e]

[sel HUDDLE_ANS_SEL top]
[s]A: Go after your friend.[e]
[s]B: Go get help.[e]

[sel HUDDLE_DICEDE_SEL top]
[s]Let's go with this answer.[e]
[s]Let's think it over again.[e]

[msg D10_009_HuddleTalk_agend [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1172 65535 0]Okay, let's think of how to handle[n]the first question. What should we[n]do, Joker?[n][w][e]

[msg D10_009_HuddleTalk_ReAge [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1003 65535 0]Do you want to talk about something[n]else?[n][w][e]

[msg D10_09_huddle_npc_choice [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right. Whose story do you want to[n]discuss?[n][w][e]

[msg D10_09_huddle_npc_rechoi [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1186 65535 0]Anyone else have something to say?[n][w][e]

[msg D10_09_huddle_ans_choice [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1035 65535 0]Okay, let's come up with an answer[n]based on what we've heard.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It really comes down to how Maruki[n]would think about it.[n][w][e]

[msg D10_09_huddle_ans_choice_2 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Risking yourself to help your friend[n]or take the time to find dependable[n]help...[n][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Determining which choice is incorrect[n]is quite difficult.[n][w][e]

[msg D10_09_huddle_ans_choice_3 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 53339 65535 0]And neither choice guarantees your[n]friend's safety, if you think about it.[n][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Neither option seems any more[n]successful than the other when[n]it comes to helping your friend...[n][w][e]

[msg D10_09_huddle_ans_choice_4 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm? Whaddya mean?[n][w][e]

[msg D10_09_huddle_ans_choice_5 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8155 65535 0]Your friend may end up hurt no matter[n]which answer you choose, so that isn't[n]the deciding factor here...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The issue is that [clr 2]you may end up[n]getting hurt[clr 27]. That's what we base[n]our decision on.[n][w][e]

[msg D10_09_huddle_ans_choice_6 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uhhh...[n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Great, Joker! You've totally got this![n][w][e]

[msg D10_09_huddle_ans_choice_7 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1028 65535 0]I guess he's done thinking it over...[n][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But we should have enough information[n]to make a wise decision. That part's up[n]to you, Joker.[n][w][e]

[msg D10_009_ans_diceded_star [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]All right, back to the elevator![n][w][e]

[msg D10_009_ans_not_dicede_s [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]I see, you wanna think it over for a bit.[n][w][e]

[msg D10_09_huddle_cancel_sta [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1023 65535 0]All right, I guess we're done here.[n][w][e]

[msg D10_09_huddle_cancel_ret [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1023 65535 0]All right, I guess we're done here.[n][w][e]

[msg D10_09_huddle_cancel_end [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1023 65535 0]All right, I guess we're done here.[n][w][e]

[msg D10_09_npc_a_info_start [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1156 65535 0]He's the one who chose A: Go after[n]your friend.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]He said he'd help any person he might[n]see who's in trouble.[n][w][e]

[msg D10_09_npc_a_info_01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]He had turned a blind eye in a similar[n]situation in the past...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]His regret is the main reason he would[n]intervene in the future.[n][w][e]

[msg D10_09_npc_a_info_02 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Hmm, standing up to evil to help your[n]friend certainly seems like the right[n]thing to do.[n][w][e]

[msg D10_09_npc_a_info_03 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That would be correct if this were based[n]on overly simplistic morals, but this is[n]rather based on Maruki's viewpoint.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You may find the man's stance admirable,[n]but would Maruki do the same?[n][w][e]

[msg D10_09_npc_a_info_04 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2127 65535 0]Right... [clr 2]The risk factor[clr 27] is what bothers me[n]about this choice.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You would likely be hurt if you ended[n]up failing. We have to consider[n]Dr. Maruki's thoughts about that.[n][w][e]

[msg D10_09_npc_a_info_05 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yeah... Dr. Maruki wants everyone to[n]find their happiness, so that means...[n][w][e]

[msg D10_09_npc_a_info_end [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]...I guess that's about it for this one.[n][w][e]

[msg D10_09_npc_b_info_start [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1156 65535 0]He's the one that chose B: Go get help.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]He said there's a chance he wouldn't be[n]able to help his friend alone, so he'd[n]rather find a way to increase the odds.[n][w][e]

[msg D10_09_npc_b_info_01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I get what he's sayin', but it still bugs[n]me... It's like he's just runnin' away...[n][w][e]

[msg D10_09_npc_b_info_02 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3189 65535 0]Yes, but it's not as if his sole priority[n]was avoiding getting hurt.[n][w][e]
[s][f 4 10 65535 3 0][f 4 25 1 65535 0 0]I wonder what Dr. Maruki would[n]think about it...[n][w][e]

[msg D10_09_npc_b_info_03 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Remember what Dr. Maruki said[n]on his last day at the school?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]He said it's okay to escape your problem[n]if it becomes too painful...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Do you think he'd consider this[n]the same thing?[n][w][e]

[msg D10_09_npc_b_info_end [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]...I guess that's about it for this one.[n][w][e]

[msg D10_09_npc_c_info_start]
[s]......[n][w][e]

[msg D10_09_npc_c_info_end]
[s]......[n][w][e]

[msg D10_09_npc_d_info_start]
[s]......[n][w][e]

[msg D10_09_npc_d_info_end]
[s]......[n][w][e]

[msg D10_09_npc_e_info_start]
[s]......[n][w][e]

[msg D10_09_npc_e_info_end]
[s]......[n][w][e]

