[msg JULY_AZITO_TALK_01_mes01 [Ann]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Exams are finally over...[n]I'm so exhausted...[n][w][e]

[msg JULY_AZITO_TALK_01_mes02 [Ryuji]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 1 0 0 2 0 0]I can get back to actually sleepin'[n]in peace...[n][w][e]

[msg JULY_AZITO_TALK_01_mes03 [Makoto]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 3 0 0]Huh. You must have been studying[n]pretty hard if it kept you up at night.[n][w][e]

[msg JULY_AZITO_TALK_01_mes04 [Ryuji]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 1 0 0 4 0 0]Nah, I was up playin' video games.[n]Slackin' off is just too much fun...[n][w][e]

[msg JULY_AZITO_TALK_01_mes05 [Ann]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 1 0 0 5 0 0]I know, right!? I kept cleaning my room[n]instead of studying! It might even be[n]TOO clean now...[n][w][e]

[msg JULY_AZITO_TALK_01_mes06 [Yusuke]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 6 0 0]You two are perfect exemplars of what[n]escapism can mean.[n][w][e]

[msg JULY_AZITO_TALK_01_mes07 [Makoto]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 7 0 0]*sigh* And I can only imagine what the[n]end result will be.[n][w][e]

[msg JULY_AZITO_TALK_01_mes08 [Ryuji]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 8 0 0]Whatever, it's over with now. Who cares[n]about that anymore!?[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 9 0 0]What's real important is the Phantom[n]Thieves' popularity! Ain't it amazin'!?[n][w][e]

[msg JULY_AZITO_TALK_01_mes09 [Ann]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 1 0 0 10 0 0]It kinda feels like our time's finally here![n][w][e]

[msg JULY_AZITO_TALK_01_mes10 [Yusuke]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 11 0 0]I have even heard people excitedly[n]speculating about our next target.[n]We will have to choose carefully.[n][w][e]

[msg JULY_AZITO_TALK_01_mes11 [Makoto]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 12 0 0]There's no need to hurry. We should[n]spend some time thinking it over.[n][w][e]

[msg JULY_AZITO_TALK_01_mes12 [Ryuji]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 13 0 0]Hold up, the most important thing now[n]is our celebration party![n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 14 0 0]I hope you guys didn't forget. It's the[n]fireworks festival on the 18th.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 15 0 0]I guess we're good meetin' up in Shibuya,[n]yeah? Let's say... 5 pm![n][w][e]

[msg JULY_AZITO_TALK_01_mes13 [Morgana]]
[s][f 4 23 1 65535 3 5 11 5][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 16 0 0]You sure are on top of THESE kinds[n]of things...[n][w][e]

