[msg GMC_PUZZLE_INIT_msg_02 [Stone Monument]]
[s]Those who serve the emerald queen are[n]the children of ebon, scarlet, and azure.[n][w][e]

[msg GMC_PUZZLE_EXIT_CHECK_ms [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What's wrong, Joker? Do you need to[n]think this over?[n][w][e]

[sel YESNO_SEL top]
[s]Yes please.[e]
[s]Not yet.[e]

[msg GMC_PUZZLE_EXIT_CLEAR_ms [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Aw yeah! There we go![n][w][e]

[msg GMC_PUZZLE_HINT_msg [Makoto]]
[s]The text on this slab must have some[n]sort of meaning.[n][w][e]
[s]If I were to say it with more common[n]colors, it would be something like...[n][w][e]
[s]"The black, red, and blue children[n]serve the green queen."[n][w][e]

