[msg MSG_000_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]So the Phantom Thieves only stole[n]the heart of Futaba Sakura?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]And Medjed was in turn defeated by her[n]real-world hacking abilities?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]This does correlate to the facts as we[n]know them...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]If he's telling the truth, then Wakaba[n]Isshiki didn't commit suicide...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Did a third party target her life with the[n]goal of destroying her research?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Wakaba's death was two years ago...[n]That also coincides with when the[n]incidents started occurring...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Does this other Metaverse user that[n]Madarame and Kaneshiro mentioned...[n]really exist?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Earlier, I briefly mentioned about those[n]psychotic breakdown incidents that have[n]alarmed the public.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]All of a sudden, people will lose[n]consciousness or become violent...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]A situation as incomprehensible as that[n]can't be explained away as "troubled[n]social conditions."[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]...I suspect that these cases are all[n]connected to a larger, man-made plot.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]The method involved always muddled[n]the explication, but your story has[n]virtually confirmed its viability.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Although, I wouldn't have expected[n]a new criminal to come to light from[n]your testimony...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]What did your group think of this other[n]Metaverse user?[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]The true criminal.[e]
[s]Not so different from us.[e]
[s]Unimportant.[e]

[msg MSG_007_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]How self-centered of you.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]The Phantom Thieves tamper with[n]people's hearts without asking consent.[n]How is that different?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]So you were aware that what you were[n]doing wasn't the pure justice you[n]envisioned?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Are you saying it didn't matter to you that[n]complete strangers were being victimized?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [(SE)新島 冴]]
[s][vp 8 0 0 19 65535 0](軽い自♀)[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Well... no matter how you thought of[n]them, there can be no doubting your[n]resolve.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Are those incidents because of you or[n]someone else? Either way, I will get to[n]the bottom of this.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Now, let's move on to your next crime.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Kunikazu Okumura...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]You should know who he is.[n][f 1 3 65535][w][e]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]...Considering what happened.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Your testimony regarding this incident[n]will be serious. I'm sure you understand[n]why.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Answer my next question carefully.[n]What did you do to this Okumura?[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 1 0 0 0 0 0]I feel like my bond with Sae[n]is growing deeper...[n][f 1 3 65535][w][e]

