[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Yo, welcome back.[n][f 1 3 65535][w][e]
[s][bup 0 103 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]You get tanned a bit?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]How was Hawaii?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]It was fun.[e]
[s]Normal, I guess.[e]
[s]Aloha![e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]I'm glad I paid for your travel expenses[n]then.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]You left the country and it was just[n]"normal"?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]He's been Hawaiianized...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][bup 0 103 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Eh, I can understand why.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]While you guys were off having fun,[n]things here have gotten a bit more[n]complicated.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Host]]
[s][vp 8 0 0 9 65535 0]So, I've heard the surprisingly hot items[n]at the moment are "masks" and "calling[n]cards"?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Female Assistant]]
[s][vp 8 0 0 10 65535 0]Here is a graph of the profits for stores[n]handling these items.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Host]]
[s][vp 8 0 0 11 65535 0]Double from last year!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Phantom thief goods seem to be in[n]especially high demand.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]I didn't know they sold that kind of stuff.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sojiro]]
[s][bup 0 103 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Should we try too? I mean, selling[n]phantom thief merchandise.[n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]Sounds good.[e]
[s]What about copyright?[e]
[s]Like Phantom Thief Curry?[e]

[msg MSG_014_0_0 [Sojiro]]
[s][bup 0 103 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]I'm just joking. Don't take it so seriously.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Sojiro]]
[s][bup 0 103 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]I don't think we need to worry about[n]that. They'll get caught the second they[n]try to sue.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Not like I'd actually wanna sell their stuff[n]though.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Sojiro]]
[s][bup 0 103 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Maybe I'll toss some dry ice on the side.[n]Y'know, give it that phantom-y effect...[n]*chuckle*[n][f 1 3 65535][w][e]
[s][bup 0 103 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Uh, I'm just joking, all right?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Female Assistant]]
[s][vp 8 0 0 20 65535 0]I wonder how our guests consider this[n]recent phenomenon.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Host]]
[s][vp 8 0 0 21 65535 0]What do you think, Akechi-kun?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Well...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]There he is, the anti-thief detective.[n][f 1 3 65535][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]I hope he slips up and self-destructs.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [(SE)佐倉 双葉]]
[s][vp 8 0 0 25 65535 0](『ククク』という笑い)[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]I can sense some chivalry behind their[n]actions.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]They are clever to take the silent[n]resentments of the public into account[n]and relieve them.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]I believe that may be the secret to their[n]popularity.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Host]]
[s][vp 8 0 0 29 65535 0]Well this is surprising. Your stance seems[n]to have softened.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Akechi]]
[s][bup 0 9 3 2 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]This doesn't change the fact that they are[n]dangerous. However... No, I shouldn't[n]say any more...[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Host]]
[s][vp 8 0 0 31 65535 0]Come on, you can say it.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Akechi]]
[s][bup 0 9 1 2 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Oh no, I won't be falling for that. I've[n]learned my lesson after the previous[n]backfire...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Sojiro]]
[s][bup 0 103 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]These thieves are more popular than the[n]police or politicians. What's the world[n]coming to?[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Rude![n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Sojiro]]
[s][bup 0 103 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]What're you so angry about?[n][f 1 3 65535][w][e]
[s][bup 0 103 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Hey, I'm gonna go to the bathroom.[n]Take care of any customers that show up.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]I finished the analysis.[n]You know, of the data...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Wanna meet now?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Seriously? Jet lag?[n][f 1 3 65535][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]Fine then. Tomorrow.[n][f 1 3 65535][w][e]

