[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Mm, that was delicious.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]The food was arranged on my plate[n]as though it were paint on a canvas.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 504 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]The staff brought out this table and food[n]just for us, huh?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]I thought if we were going to dine[n]together, it would be better to do it[n]somewhere with a view.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 1 300 1][vp 8 0 0 5 65535 0]The VIP life is incredible![n][f 1 3 65535][w][e]
[s][bup 0 4 501 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Not that I'd expect anything else from[n]a private rental![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]There really is no one else here.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 8 1 301 1][vp 8 0 0 8 65535 0]We are the rulers of the kingdom[n]of dreams![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Is this lighting just for our sake as well?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]That's right.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]It's beautiful...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Futaba]]
[s][bup 0 8 501 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]"It's not as beautiful as you..."[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]That's the kinda stuff couples say, right?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 501 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Almost anyone would fall for that line[n]in front of a sight like this![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Lady Ann, this view is not as beautiful as—[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][bup 0 2 501 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]C'mon, you guys're gettin' way too excited[n]about this stuff.[n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [(SE)モルガナ]]
[s][vp 8 0 0 0 65535 0](ため息)[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ann]]
[s][bup 0 4 501 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]You say that like you're not tapping into[n]your inner child too, Ryuji.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 12 300 1][vp 8 0 0 18 65535 0]This is just 'cause Futaba kept naggin' me[n]to put 'em on![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Futaba]]
[s][bup 0 8 502 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]I did not![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][bup 0 2 511 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]...You said somethin' like that![n][f 1 3 65535][w][e]

[sel SEL_018_0_0 top]
[s]Don't fight in those.[e]
[s]Fighting brings you closer.[e]
[s]Ryuji, you're the adult.[e]

[msg MSG_019_0_0 [Ryuji]]
[s][bup 0 2 502 0 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]What was that!?[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]That's a good way of putting it. I wonder[n]if that has to do with where we are.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][bup 0 2 503 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Well yeah, but...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ann]]
[s][bup 0 4 501 0 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Whoa, look at you being all obedient![n]Is the Destinyland charm rubbing off[n]on you?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [(SE)喜多川 祐介]]
[s][vp 8 0 0 25 65535 0](『ぶ! くく...』)[n][f 1 3 65535][w][e]

[msg MSG_023_5_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]My, this is so heartwarming![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Honestly, I would've liked to see[n]the parade as well.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]But given how sudden the request was,[n]they couldn't get enough staff together[n]to do it.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Perhaps that will have to wait until[n]next time.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 1 301 1][vp 8 0 0 30 65535 0]Either way, this party's totally the[n]best one so far! It's freakin' amazing![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]I'm glad to see you're enjoying it.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Be careful, Haru. You've shown these[n]guys what luxury means.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]This'll really raise the bar for our next[n]celebration party.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]You're already talking about our next[n]party? Don't you think that's somewhat[n]premature?[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [(SE)みんなの笑い声]]
[s][vp 8 0 0 35 65535 0](『それもそうか』『はしゃぎすぎ』など)[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Still... How do I put this?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]I met Mona-chan, I got to know you[n]all... Isn't everything going a little[n]too perfectly?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]It's actually a bit frightening...[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]You worry too much.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]...I must just be overly cautious[n]because of my circumstances up[n]till recently.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]I'm sorry for bringing it up.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Ann]]
[s][bup 0 4 504 0 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Hey, isn't it almost time? You know,[n]for the press conference.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Ryuji]]
[s][bup 0 2 501 0 0][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]Ooh, perfect timin'![n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]Father...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Okumura]]
[s][bup 0 205 0 0 0][f 4 10 65535 0 0][vp 8 0 0 57 65535 0]Thank you all for taking time out of[n]your busy schedules to gather here.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 58 65535 0]Today, I'd like to elaborate upon the[n]whole truth behind my company's[n]labor situation.[n][f 1 3 65535][w][e]

[msg MSG_039_3_0 [Okumura]]
[s][bup 0 205 0 0 0][f 4 10 65535 0 0][vp 8 0 0 60 65535 0]How my employees were forced to work[n]under severe conditions, how... lax we[n]were with sanitation...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 61 65535 0]And how my corporation acted as a[n]whole to... cover up every facet of this[n]scandal.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 62 65535 0]For all of this, I wholeheartedly[n]apologize.[n][f 1 3 65535][w][e]

[msg MSG_039_6_0 [Calm Journalist]]
[s][vp 8 0 0 65 65535 0]So are you saying all of this was done[n]under your orders?[n][f 1 3 65535][w][e]

[msg MSG_039_9_0 [Okumura]]
[s][bup 0 205 3 0 0][f 4 10 65535 0 0][vp 8 0 0 66 65535 0]...Yes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 64 65535 0]I... am solely responsible...[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Calm Journalist]]
[s][vp 8 0 0 69 65535 0]We heard that dozens of your[n]employees were forced to resign[n]due to mysterious illness.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 70 65535 0]Furthermore, these happened to be[n]officials who stood against your[n]proposal for overseas expansion.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 71 65535 0]The same thing also happened to[n]executives at competing companies[n]who were looking to expand abroad.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 72 65535 0]Is all of this true?[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Okumura]]
[s][bup 0 205 0 0 0][f 4 10 65535 0 0][vp 8 0 0 73 65535 0]Yes.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Calm Journalist]]
[s][vp 8 0 0 74 65535 0]Was it all coincidence?[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Calm Journalist]]
[s][vp 8 0 0 75 65535 0]We'd like some answers.[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Okumura]]
[s][bup 0 205 3 0 0][f 4 10 65535 0 0][vp 8 0 0 76 65535 0]About that... I have a critical piece of[n]information to announce here today.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 82 65535 0]Here it comes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 83 65535 0]Okumura's going to say who's really[n]behind the mental shutdowns.[n][f 1 3 65535][w][e]

