[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]What!? He knows everything!?[n]You gotta be fucking kidding![n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Wait, are you okay? Did he report you[n]or anything?[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]We likely wouldn't be receiving[n]these messages if [f 4 2][n]was not okay.[n][w][e]
[s][f 5 14]I had a feeling that Boss was no[n]ordinary man...[n][w][e]

[msg MSG_003_0_0 [Haru]]
[s][f 5 14]But he didn't recommend you turn[n]yourself in, did he?[n][w][e]
[s][f 5 14]I think in that case we can consider[n]him a new ally.[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]I'm more curious about what he[n]mentioned to you.[n][w][e]

[msg MSG_005_0_0 [Haru]]
[s][f 5 14]You mean how our enemy might[n]be the same people who targeted[n]Futaba's mother?[n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]Yes. She was killed by mental[n]shutdown, the same method used[n]by the culprit we pursue now.[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Wait a second though... Didn't you[n]say Boss had to "run from it all"...?[n][w][e]
[s][f 5 14]Does that mean someone was trying[n]to stop the news from getting out?[n]Who could do that...?[n][w][e]
[s][f 5 14]...Who do you think the culprit[n]could be?[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]A government official.[e]
[s]Someone very powerful.[e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]Ain't you letting your imagination[n]run wild a bit?[n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14]But it would make sense.[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14]Wait a sec! If you're right, then[n]wouldn't the police be working[n]for 'em too!?[n][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][f 5 14]...That's not impossible.[n][w][e]

[msg MSG_013_0_0 [Ann]]
[s][f 5 14]This is getting too big for me to[n]even think about...[n][w][e]

[msg MSG_014_0_0 [Haru]]
[s][f 5 14][f 5 15]Can we really win this?[n][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]We're gonna win, no matter what![n][f 1 3 65535][w][e]

