[msg MSG_000_0_0 [Frightened Student]]
[s][vp 8 0 0 1 28 0]The police are here again?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Irritated Student]]
[s][vp 8 0 0 2 15 0]Yeah, seems like it's for real this time.[n]Apparently one of our students is a[n]phantom thief.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Frightened Student]]
[s][vp 8 0 0 3 28 0]Seriously!?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Irritated Student]]
[s][vp 8 0 0 4 15 0]I read the same thing online. Apparently[n]Public Security is already on the move...[n][f 1 3 65535][w][e]

