[msg MSG_000_0_0 [Shadow Sae]]
[s][bup 0 105 100 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]...What losers.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Shadow Sae]]
[s][bup 0 105 102 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Criminal trials are but a gamble to be[n]won, and us prosecutors arrange the[n]gambling table.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Hence, losses are unacceptable![n]We must win, even if it has to be[n]on false charges![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Are you serious, Sis!?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Why won't you answer me!?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Mako-chan...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Shadow Sae]]
[s][bup 0 105 100 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Don't think such a petty trick could[n]defeat me.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]I may have to acknowledge your skills—[n]if you can make it up to the manager's[n]floor, that is.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 103 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]She thinks the trials which shape the[n]outcomes of people's lives are nothing[n]more than gambles?[n][f 1 3 65535][w][e]

[msg MSG_006_5_0 [Akechi]]
[s][bup 0 9 105 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]I wish I didn't have to hear that from[n]Sae-san herself...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Sis is completely distorted![n][f 1 3 65535][w][e]

[msg MSG_007_5_0 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]We have to stop her, quickly![n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Let's save her, together.[e]
[s]Calm down.[e]
[s]We'll manage somehow.[e]

[msg MSG_009_0_0 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]We all feel the same way.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]He's right. We still have a long way to go.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]He's right. I'm sure we can do it![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]There's no time to waste. She mentioned[n]something about a manager's floor, right?[n][f 1 3 65535][w][e]

[msg MSG_012_5_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Let's try heading up there. We'll change[n]Niijima-san's heart for sure.[n][f 1 3 65535][w][e]

