[msg MSG_000_0_0 [Akechi]]
[s][bup 0 217 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Shido-san, my job is complete.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Shido]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]I've told you not to call me by name.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Regardless, all that's left is to deal with[n]the remnants.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 217 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]The continued deaths of these teenagers[n]would be a bit much, don't you think?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]I considered making it appear they had[n]a falling out... but that would only[n]amplify public frenzy...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]It would be best to have each of them[n]meet with an unfortunate accident once[n]the storm blows over.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Shido]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Is there any possibility they'll want to[n]avenge their leader?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 217 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]No chance. They're nothing but cattle[n]anyway... They have no backbone[n]without his guidance.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]I will keep my eye on them just in case[n]though.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Shido]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]I'll be counting on you.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 217 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]They will live their lives cowering in[n]fear of death. An apt punishment for[n]obstructing our work.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Shido]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Make sure to kill that strange cat[n]once you find it as well.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 217 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Understood, though I doubt there is[n]anything to worry about. It's merely[n]a cat, after all.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 217 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]More importantly, they should be[n]dealing with the suicide right about now.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Things will become quite busy once the[n]word gets out... I'll need to prepare my[n]comments on the matter.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Shido]]
[s][bup 0 206 1 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]I must be prepared to deal with it on[n]my end as well.[n][f 1 3 65535][w][e]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Beyond that... what of the director[n]of the Special Investigations Unit?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 217 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Perhaps he'll be struck by a mysterious[n]illness sometime soon...[n][f 1 3 65535][w][e]

