[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0][f 4 2] getting captured by the[n]police went exactly how we planned it.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sae]]
[s][bup 0 105 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]And I had been interrogating him with[n]no knowledge of this.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]But, how did you lure Akechi into this...[n]cognitive world's interrogation room?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Heeheehee...[n][f 1 3 65535][w][e]

