[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 2117 65535 0]Wait, so you cook it yourself...[n]on this griddle... with a spatula!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Isn't this a restaurant? Why is[n]the customer making their meal!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hm... Do you know how[n]to make monjayaki?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]I don't.[e]
[s]Leave it to me.[e]
[s][f 0 8 2 1 2217]Anything's worth a try.[clr 27][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2026 65535 0][f 5 13 3 10 6]I-I see... Well, I suppose[n]we'll just have to try it out.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, they have instructions here.[n]Let's see... Mix, cook, serve...[n][f 1 3 65535][w][e]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 37 5 100]I need more details than that![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 3 10 6]Oh, that sounds good.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I would be sad if I tried to do it[n]and ended up ruining our food...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 2118 65535 0]Instead, I'd like to take this[n]opportunity to learn how to[n]make it. Will you teach me?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 3 15 6]True... There has to be a[n]first time for everything.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Whether or not you have the[n]willpower to actually go forth[n]and try it is the difference.[n][f 1 3 65535][w][e]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2108 65535 0][f 4 24 0 4 0 37 5 100]Okay... I'm going to cook[n]the perfect monjayaki![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Um, excuse me! I'd like to[n]order the most traditional[n]monja on your menu.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]And let's see... I'd also like[n]one of each of the most popular[n]items, from number one down...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh! And a mentai cheese[n]as well, please.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I think I'm starting to learn![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Monjayaki is so interesting![n]I never expected it to be[n]this much fun...![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Could it be that this is an[n]alternate form of entertainment?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2019 65535 0]Say, you can still eat more,[n]right? Boys are supposed to be[n]able to eat a lot, after all.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Please let me try once[n]more! I promise not to[n]mess it up this time![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][vp 8 2 0 2128 65535 0]I ate far too much... Hm, it[n]seems monja is no ordinary food.[n][f 1 3 65535][w][e]

