[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6011 65535 0]We're so high up! It's like I'm[n]monopolizing this incredible view![n][f 1 3 65535][w][e]
[s][bup 0 4 6 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Or would it be... duopolizing?[n]I'm here with you after all,[n][f 4 2]! *giggle*[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ann]]
[s][bup 0 4 7 65535 0][vp 1 0 0 0 0 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...I'm starting to get nervous.[n]It's so quiet up here... and[n]you're so close to me...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]C-Come on, let's talk about[n]something... A-And don't[n]stare so much...[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 0 8 2 1 2217]You're way too embarrassed.[clr 27][e]
[s][f 0 8 2 1 2217]But you're so cute.[clr 27][e]
[s][f 0 8 2 1 2217]I'm not saying anything.[clr 27][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 6029 65535 0][f 5 13 7 10 4]Wh-What? How can you look[n]so calm right now!?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 6029 65535 0][f 5 13 7 10 4]Wh-What? You always say that[n]stuff so nonchalantly![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ann]]
[s][bup 0 4 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 6029 65535 0][f 5 13 7 10 4]Y-You think this is funny, don't[n]you? You're such a meanie...![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I already told you... looking[n]at me like that isn't fair. I[n]totally lose my composure...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I can't even focus on the[n]scenery around us...[n][f 1 3 65535][w][e]
[s][bup 0 4 6 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 1 5 0]*sigh* You know... I love you.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ann]]
[s][vp 8 2 0 6088 65535 0][f 4 2], can we stay[n]together forever...?[n][f 1 3 65535][w][e]

