[msg MSG_BTLSTART_001 [Arsène]]
[s][vp 8 0 2 1001 0 0]I am Arsène, another you that exists[n]within... Ah, we meet once again.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Arsène]]
[s][vp 8 0 2 1002 0 0]You have progressed well through your[n]recollections. Last spring, you awakened[n]to this furious power.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Arsène]]
[s][vp 8 0 2 1003 0 0]Now, use that power... and defeat the[n]enemies before you![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Arsène]]
[s][vp 8 0 2 1007 0 0]Your fate will soon be determined...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_005 [Arsène]]
[s][vp 8 0 2 1008 0 0]Recall everything... Remember the[n]bonds you have forged with your[n]friends...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Arsène]]
[s][vp 8 0 2 1009 0 0]If you are fated to continue past this[n]point, then we shall surely meet again...[n][f 1 3 65535][w][e]

