[msg MSG_BTLSTART_001 [Shadow Nejima]]
[s][vp 8 0 2 1001 1 0]Hahaha! I'm strong! I'm the most[n]powerful![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Shadow Nejima]]
[s][vp 8 0 2 1002 1 0]Ain't no matter what you throw my way,[n]you won't put a scratch on me![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Shadow Nejima]]
[s][vp 8 0 2 1003 1 0]I told you it's useless! There's no way[n]you can win against me![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Morgana]]
[s][bup 0 3 5 0 0][vp 8 0 2 1004 0 3][f 4 10 65535 0 0]Ngh! The fact he's an infamous cheater[n]isn't just for show...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_005 [Morgana]]
[s][bup 0 3 5 0 0][vp 8 0 2 1005 0 3][f 4 10 65535 0 0]It's no good if we continue this! Let's[n]withdraw once and come up with a[n]countermeasure![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Futaba]]
[s][bup 0 8 602 0 0][vp 8 0 2 1006 0 8][f 4 10 65535 0 0]Look at him, acting all smug because[n]of his cheats...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_007 [Futaba]]
[s][bup 0 8 600 0 0][vp 8 0 2 1007 0 8][f 4 10 65535 0 0]We can't do anything to him at this rate[n]though. Let's retreat for now and[n]rethink our approach.[n][f 1 3 65535][w][e]

