[msg MSG_BTLSTART_000_006 [Shadow Sae]]
[s][vp 8 0 2 1001 1 228]Now, let us play a game of roulette.[n]The stakes will be... our lives.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1004 1 228]Of course, acts of violence are[n]forbidden here. One must follow the[n]rules.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_040_000 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 8]We already told you, there's no way[n]we're gonna follow your rules anymore![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_050_006 [Shadow Sae]]
[s][vp 8 0 2 1006 1 228]That's fine by me. Such troublesome[n]people will just face the penalty...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_999_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 2 2 9109 0 8]All right, let's do it![n][f 1 3 65535][w][e]

[msg MSG_BTLDFIRSTROU_000_000 [Shadow Sae]]
[s]......[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_060_000 [Shadow Sae]]
[s][vp 8 0 2 1002 1 228]You will predict which pocket the ball[n]will fall into.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1007 1 228]Now, the time has come for our first[n]round. Choose where you will place[n]your bet![n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_000_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1113 0 3]I'm almost positive she's going to try[n]and cheat, but even if we bring that up,[n]she'd just ignore us.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1114 0 3]We should go along with the game for[n]now and try to gain evidence on her[n]methods of cheating.[n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_010_008 [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1115 0 9]...I agree.[n][f 1 3 65535][w][e]

[msg MSG_FIRSTROULETTE_000_00]
[s][vp 1 0 0 0 0 0]Predict which pocket the ball will fall[n]into before your turn begins.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Various bonuses will be applied to the[n]enemies or your allies depending on[n]the outcome.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Greater bonuses will be given for more[n]difficult predictions.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Carefully consider the flow of battle[n]when determining where you place[n]your bet.[n][f 1 3 65535][w][e]

[msg MSG_FIRSTROULETTE_010_00 [Shadow Sae]]
[s][vp 8 0 2 1009 1 228]Have you made your decision?[n]Then let's see the results![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_900_000 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1116 0 3]We lost... Have you figured anything[n]out, Joker?[n][f 1 3 65535][w][e]

[sel SEL_TSUIKA_100_0_S top]
[s]I don't know...[e]
[s]I most certainly have.[e]

[msg MSG_BTLSTART_910_000 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1117 0 3]Let's keep watching her then. There[n]has to be something not right going on[n]here![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_920_000 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1118 0 3]Really!? How is she doing it!?[n][f 1 3 65535][w][e]

[sel SEL_TSUIKA01_000_0_S top]
[s]She's not actually cheating.[e]
[s]The pockets are drawings.[e]
[s]There's a glass lid.[e]

[msg MSG_BTLTSUIKA_990_000 [Akechi]]
[s][bup 0 9 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1119 0 9]That can't be![n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_991_000 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1120 0 3]There's no way she's playing this fair[n]and square. Let's keep watching and[n]figure it out.[n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_993_000 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 2 1121 0 3]I don't think that's the case. The ball[n]did fall into the pocket.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1122 0 3]Let's try observing a little more closely[n]so we can expose her trickery.[n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_994_000 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1123 0 3]I see... you're right! It did seem like the[n]ball floated for a split second there...[n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_995_000 [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1124 0 9]How humiliating...[n][f 1 3 65535][w][e]

[msg MSG_FIRSTROULETTE_020_00 [Futaba]]
[s][bup 0 8 603 65535 0][f 4 10 65535 0 0][vp 8 0 2 1010 0 8]We lost...[n][f 1 3 65535][w][e]

[msg MSG_FIRSTROULETTE_030_00 [Shadow Sae]]
[s][vp 8 0 2 1011 1 228]It seems luck was not on your side this[n]time. Try again next round.[n][f 1 3 65535][w][e]

[msg MSG_FIRSTPENALTY_000_000 [Shadow Sae]]
[s][vp 8 0 2 1012 1 228]Ah... So you've broken the rules.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1013 1 228]In that case, it's time you be penalized![n][f 1 3 65535][w][e]

[msg MSG_FIRSTPENALTY_010_000 [Shadow Sae]]
[s][vp 8 0 2 1013 1 228]In that case, it's time you be penalized![n][f 1 3 65535][w][e]

[msg MSG_FIRSTPENALTY_020_006 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1014 0 8]What!? THIS is the penalty!?[n][f 1 3 65535][w][e]

[msg MSG_FIRSTPENALTY_030_000 [Shadow Sae]]
[s][vp 8 0 2 1015 1 228]Those who cannot follow rules are not[n]to be tolerated. That is simply how[n]society operates.[n][f 1 3 65535][w][e]

[msg MSG_SECONDROULETTE_000_0 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1016 0 8]The stuff displayed on the monitor[n]changed...[n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1017 0 8]That must mean the betting changes[n]every time...[n][f 1 3 65535][w][e]

[msg MSG_SECONDROULETTE_000_0_2 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1016 0 8]The stuff displayed on the monitor[n]changed...[n][f 1 3 65535][w][e]

[msg MSG_SECONDROULETTE_000_0_3 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1017 0 8]That must mean the betting changes[n]every time...[n][f 1 3 65535][w][e]

[msg MSG_SECONDROULETTE_010_0 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1017 0 8]That must mean the betting changes[n]every time...[n][f 1 3 65535][w][e]

[msg MSG_NEXTRURE_000_000 [Shadow Sae]]
[s][vp 8 0 2 1018 1 228]Very well, time to make your bet![n][f 1 3 65535][w][e]

[msg MSG_FIRSTPENALTY_040_006 [Futaba]]
[s][bup 0 8 603 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 8]Ngh...![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_200_000 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1125 0 3]We lost... Have you figured anything[n]out, Joker?[n][f 1 3 65535][w][e]

[msg MSG_SECONDTRICK_000_006 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1020 0 3]W-We lost three times in a row...[n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1021 0 3]She has to be cheating![n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 3]I don't know how she's doing it, but[n]it's weird to lose this many times![n][f 1 3 65535][w][e]

[msg MSG_SECONDTRICK_010_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1021 0 3]She has to be cheating![n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 3]I don't know how she's doing it, but[n]it's weird to lose this many times![n][f 1 3 65535][w][e]

[msg MSG_TREE_001_0_S]
[s]The enemy might be cheating. However,[n]we don't know how they're doing it.[n][f 1 3 65535][w][e]

[sel SEL_TREE_001_0_S top]
[s]She's not cheating.[e]
[s]There's a glass lid.[e]
[s]The pockets are just pictures.[e]

[msg MSG_TREE_001_0_S_0 [Futaba]]
[s]The situation isn't that simple.[n]She's almost certainly cheating.[n][f 1 3 65535][w][e]

[msg MSG_TREE_001_0_S_1 [Futaba]]
[s]The pocket's been reflecting light oddly...[n][f 1 3 65535][w][e]
[s]Could this mean...[n][f 1 3 65535][w][e]

[msg MSG_TREE_001_0_S_2 [Futaba]]
[s]The ball has fallen into some of the[n]pockets. They can't just be fake.[n][f 1 3 65535][w][e]

[msg MSG_MEMBERRELEASED_000_0 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1023 0 8]Glass lids!?[n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1024 0 8]She must really think we're dumb to[n]try something so straightforward![n][f 1 3 65535][w][e]

[msg MSG_MEMBERRELEASED_010_0 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1026 0 8]Let's catch her in the act so she can't[n]talk her way out of it![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1028 0 8][f 4 10 65535 0 0]Have someone snipe the pocket when[n]that glass lid appears![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1029 0 8][f 4 10 65535 0 0]You're in charge of choosing who's[n]gonna be the sniper![n][f 1 3 65535][w][e]

[msg MSG_MEMBERRELEASED_020_0 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1028 0 8]Have someone snipe the pocket when[n]that glass lid appears![n][f 1 3 65535][w][e]

[msg MSG_MEMBERRELEASED_030_0 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1029 0 8]You're in charge of choosing who's[n]gonna be the sniper![n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_700_000 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1253 0 3]Hey, maybe I'm just seeing things, but[n]didn't that ball float for a split second[n]there...?[n][f 1 3 65535][w][e]

[sel SEL_TREE_900_0_S top]
[s]Are the pockets drawings?[e]
[s]Is there a glass lid?[e]

[msg MSG_BTLTSUIKA_500_000 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1254 0 3]I don't think that's the case. The ball[n]did fall into the pocket.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1255 0 3]But it looked like it was floating briefly[n]before it did, I swear.[n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_400_002 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1256 0 3]Oh, so that's what was happening![n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_410_008 [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0]How humiliating...[n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_420_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 8]Let's catch her in the act so she can't[n]talk her way out of it![n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 8]Have someone snipe the pocket when[n]that glass lid appears![n][f 1 3 65535][w][e]

[msg charaorder_Reiji_02 [Ryuji]]
[s]Leave it to me![n][w][e]

[msg charaorder_Morgana_02 [Morgana]]
[s]I'm off![n][w][e]

[msg charaorder_Ann_02 [Ann]]
[s]Okay, Joker![n][w][e]

[msg charaorder_Yugo_02 [Yusuke]]
[s]Very well. Hang in there.[n][w][e]

[msg charaorder_Makoto_02 [Makoto]]
[s]Okay... I'll give it a try![n][w][e]

[msg charaorder_Ranko_02 [Haru]]
[s]Okay, I'll go![n][w][e]

[msg charaorder_Hutaba_02 [Futaba]]
[s]ダミーなんですよ~。[n]私の出番はまだまーだ先~。[n][w][e]

[msg charaorder_Akechi_02 [Akechi]]
[s]Yes. I will pull it off without a hitch![n][w][e]

[msg MSG_ATTENTION01_000_000 [Shadow Sae]]
[s][vp 8 0 2 1066 1 228]If you intend on defeating me...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_010_000 [Shadow Sae]]
[s][vp 8 0 2 1067 1 228]...you will need to have luck on your[n]side.[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_020_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1068 0 3]We've got tons of bad luck on our side,[n]don't worry.[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_030_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0]Joker! Keep going![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_020_003 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 4]Luck, huh? Whatever.[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_030_003 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 4]Joker! Hang in there![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_020_004 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 5]Luck, hm...? How suspicious.[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_030_004 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 5]You will have to hold out just a bit[n]more, Joker.[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_020_005 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 6]Sis...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_030_005 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 6]Joker, just hold on a little longer...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_020_008 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 9]This is going well...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_030_008 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 9]Keep it up, Joker.[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_000_000 [Shadow Sae]]
[s]Lady Luck can be summoned with ease.[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_010_000 [Shadow Sae]]
[s]That is, if you hold the conviction that[n]you cannot lose.[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_020_002 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 3]Hmph, we'll be the ones laughing in[n]the end...![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_030_002 [Morgana]]
[s]Dummy[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_020_003 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 4]We don't have any[n]intention of losing![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_030_003 [Ann]]
[s]Dummy[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_020_004 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 5]Everything is going as planned. I will[n]use this moment to proceed.[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_030_004 [Yusuke]]
[s]Dummy[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_020_005 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 6]Looks like she hasn't noticed yet...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_030_005 [Makoto]]
[s]Dummy[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_020_008 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 9]This is going well...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_030_008 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 9]This is going well... I'm proceeding on![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION03_000_000 [Shadow Sae]]
[s][vp 8 0 2 1051 1 228]It is frightening to be forsaken by[n]Lady Luck... No matter what you do,[n]you are doomed to failure...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1052 1 228]If you tire of this, be sure to remember[n]that surrendering with grace is[n]important.[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION03_010_000 [Shadow Sae]]
[s][vp 8 0 2 1052 1 288]If you tire of this, be sure to remember[n]that surrendering with grace is[n]important.[n][f 1 3 65535][w][e]

[msg MSG_ATTENTIONSUCCESS_M_0 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1053 0 8]The sniper is in their designated spot.[n]All that's left is to wait for the next[n]roulette spin.[n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_000_002 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 3]All right, I'm shooting it![n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_000_003 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 4]Here it comes![n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_000_004 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 5]Now is my chance![n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_000_005 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 6]I must stop my sister...![n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_000_008 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 9]I hope you're prepared![n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_010_000 [Shadow Sae]]
[s][vp 8 0 2 1054 1 228]Hopefully your prediction will be[n]correct this time. *chuckle*[n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_010_001 [Shadow Sae]]
[s][vp 8 0 2 1055 1 228]WH— WHAT!?[n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_020_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1056 0 8]Heheh... Joker![n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_000_006 [Shadow Sae]]
[s][vp 8 0 2 1070 1 228]Goodness me, you just keep losing.[n]It seems luck isn't with you.[n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_010_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1071 0 8]Sh-Shut up![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1072 0 8]You're probably cheating! How else[n]would we keep losing like this!?[n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_020_000 [Shadow Sae]]
[s][vp 8 0 2 1073 1 228]Hmph! Why would I cheat...?[n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_030_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1074 0 8]There's no way you're not, you liar![n]It's totally obvious![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1075 0 8][f 4 10 65535 0 0]You're only up against me and Joker,[n]you know! You're supposed to be an[n]adult! You should be ashamed![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1077 0 8][f 4 10 65535 0 0]More importantly, are you so weak[n]that you have to cheat to win?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1078 0 8][f 4 10 65535 0 0]And you call yourself a Palace ruler?[n]You're just a wimp! You should totally[n]be ashamed![n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_031_000 [Shadow Sae]]
[s][vp 8 0 2 1076 0 228]......[n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_040_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1077 0 8]More importantly, are you so weak[n]that you have to cheat to win?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1078 0 8][f 4 10 65535 0 0]And you call yourself a Palace ruler?[n]You're just a wimp! You should totally[n]be ashamed![n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_050_000 [Shadow Sae]]
[s][vp 8 0 2 1079 1 228]You only dare talk like that because[n]you can't beat me...[n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_060_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1080 0 8]Shut it! To begin with—[n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_070_000 [Shadow Sae]]
[s][vp 8 0 2 1081 1 288]You're the one who needs to shut up![n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_000_002 [Morgana]]
[s]Dummy[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_000_003 [Ann]]
[s]Dummy[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_000_004 [Yusuke]]
[s]Dummy[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_000_005 [Makoto]]
[s]Dummy[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_000_008 [Akechi]]
[s]Dummy[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_010_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1057 0 8]What was that about fair and square!?[n]You were totally cheating![n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_020_006 [Futaba]]
[s]Dummy[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_030_000 [Shadow Sae]]
[s][vp 8 0 2 1058 1 288]Nnh...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1059 1 288]Ngh...[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_040_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1060 0 8]You coward! What're you so quiet for!?[n]Say something![n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_050_000 [Shadow Sae]]
[s]Dummy[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_060_000 [Shadow Sae]]
[s]Dummy[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_070_000 [Shadow Sae]]
[s][vp 8 0 2 1061 1 288]Shut up... SHUT UUUP![n][f 1 3 65535][w][e]

[msg MSG_SECONDMODE_000_005 [Makoto]]
[s][bup 0 6 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1082 0 6]S-Sis!?[n][f 1 3 65535][w][e]

[msg MSG_SECONDMODE_000_006 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1083 0 6]What the—!?[n][f 1 3 65535][w][e]

[msg MSG_SECONDMODE_010_000 [Shadow Sae]]
[s][vp 8 0 2 1084 1 228]Cheating!? Unfair!? Silence! This is[n]MY world![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1085 1 228]I AM the law! I am everything! No one[n]in this world deserves to win, except for[n]ME![n][f 1 3 65535][w][e]

[msg MSG_SECONDMODE_020_000 [Shadow Sae]]
[s][vp 8 0 2 1086 1 228]If you still dare to defy my justice, then[n]prepare to be totally crushed![n][f 1 3 65535][w][e]

[msg MSG_SECONDMODE_030_005 [Makoto]]
[s][bup 0 6 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1067 0 6]This... is my sister's true nature!? No...[n][f 1 3 65535][w][e]

[msg MSG_SECONDMODE_030_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1068 0 8]So this is her true nature...!?[n][f 1 3 65535][w][e]

[msg MSG_SECONDMODE_040_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1069 0 8]We're finally back to a normal fight...[n]Good luck, Joker![n][f 1 3 65535][w][e]

[msg MSG_GOBET_000_008 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1126 0 8]The roulette wheel is spinning again.[n]She doesn't have control over it...?[n][f 1 3 65535][w][e]

[msg MSG_GOBET_010_008 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1127 0 8]Hey, doesn't this seem like a good[n]opportunity for us?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1128 0 8]She won't cheat anymore, so if we win[n]at roulette, we'll have an advantage![n][f 1 3 65535][w][e]

[msg MSG_SECONDROULE_000_000 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1259 0 3]You're being a sore loser![n][f 1 3 65535][w][e]

[msg MSG_SECONDROULE_010_000 [Shadow Sae]]
[s][vp 8 0 2 1260 0 3]I never lose, even in games of pure[n]luck! Let me prove it![n][f 1 3 65535][w][e]

[msg MSG_SECONDROULE_020_000 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1261 0 3]So she's not going to cheat anymore...?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1262 0 3]This may be a good opportunity for us,[n]Joker. If we win at roulette, we'll get an[n]advantage in battle.[n][f 1 3 65535][w][e]

[msg MSG_HP75_000_000 [Shadow Sae]]
[s][vp 8 0 2 1129 1 288]As long as you win, it doesn't matter[n]what methods you use![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1130 1 288]Don't you all think the same!? You're[n]controlling the hearts of others to[n]achieve your own goals![n][f 1 3 65535][w][e]

[msg MSG_HP75_010_005 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1131 0 6]It's not for us! We only do it to help[n]others who are suffering![n][f 1 3 65535][w][e]

[msg MSG_HP75_010_008 [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1132 0 9]It's not for us! Those actions are for[n]justice![n][f 1 3 65535][w][e]

[msg MSG_HP75_010_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1133 0 8]We're not doing it for us! We just[n]wanna help people in trouble![n][f 1 3 65535][w][e]

[msg MSG_HP50_000_000 [Shadow Sae]]
[s][vp 8 0 2 1099 1 288]Only victory matters! To guarantee it,[n]you have to be willing to do anything![n]Doesn't might make right?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1100 1 288]No matter what happens here, I need to[n]keep winning![n][f 1 3 65535][w][e]

[msg MSG_HP50_000_005 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1101 0 6]Sis, why!?[n][f 1 3 65535][w][e]

[msg MSG_HP50_000_010 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1102 0 8]What kinda logic is that!? It's about time[n]you came to your senses![n][f 1 3 65535][w][e]

[msg MSG_HP25_000_000 [Shadow Sae]]
[s][vp 8 0 2 1109 1 288]I... I just need to win...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1110 1 288]As long as I can win... that's all that[n]matters...[n][f 1 3 65535][w][e]

[msg MSG_HP25_020_005 [Makoto]]
[s][bup 0 6 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1111 1 288]Sis...[n][f 1 3 65535][w][e]

[msg MSG_HP00_010_005 [Makoto]]
[s][bup 0 6 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1112 0 6]Sis![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_000_006EX [Shadow Sae]]
[s][vp 8 0 2 1001 1 228]EXさぁ、このルーレットで[n]お互いの命運を賭けた勝負をしましょう。[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1004 1 228]EXもちろん、暴力行Èは禁止よ?[n]ルールは守って貰うわ。[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_040_000EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 8]EXだから、今さらルールなんて[n]従うわけないだろ![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_050_006EX [Shadow Sae]]
[s][vp 8 0 2 1006 1 228]EX構わないわよ?[n]どうせ私のルールの前では無力。[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_999_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1263 0 8]EXよし、行くぞ![n][f 1 3 65535][w][e]

[msg MSG_BTLDFIRSTROU_000_000_2 [Shadow Sae]]
[s]EX......。[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_060_000EX [Shadow Sae]]
[s][vp 8 0 2 1002 1 228]EX貴方には、ボールがどのポケットに[n]落ちるか予想してもらう。[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1007 1 228]EXさぁ、1度目の勝負の時間よ。[n]どこに賭けるか、選んで頂戴![n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_000_002EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1243 0 3]EX十中八九イカサマだろうが、[n]ヤツにそれを言っても聞き入れないだろう。[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1244 0 3]EXここは素直に従って、[n]まずはイカサマの証拠を掴むことにしないか?[n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_010_008EX [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1264 0 9]EX...僕もそう思うよ。[n][f 1 3 65535][w][e]

[msg MSG_FIRSTROULETTE_000_00_2]
[s][vp 1 0 0 0 0 0]EX行動開始前に、ボールが[n]どのポケットに入るか予想してください。[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]EX予想を的中させると、敵味方に様々な[n]ボーナスが適用されます。[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]EX難しい予想を的中させるほど、[n]適用されるボーナスの効果も上昇します。[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]EX戦闘状況やボーナス内容から、[n]強気で賭けるか、手堅く賭けるか考えましょう。[n][f 1 3 65535][w][e]

[msg MSG_FIRSTROULETTE_010_00_2 [Shadow Sae]]
[s][vp 8 0 2 1009 1 228]EX選んだ? なら、結果を見てみましょう![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_900_000EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1245 0 3]EXやはり負けたか。[n]ジョーカー、何かわかったか?[n][f 1 3 65535][w][e]

[sel SEL_TSUIKA_100_0_SEX top]
[s]EXわからない[e]
[s]EXイカサマを見抜けた[e]

[msg MSG_BTLSTART_910_000EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1246 0 3]EXなら観察を続けて見抜いてやろうぜ。[n]必ずおかしな所があるはずだ![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_920_000EX [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1247 0 3]EX本当か!? どういうイカサマだ!?[n][f 1 3 65535][w][e]

[sel SEL_TSUIKA01_000_0_SEX top]
[s]EXイカサマじゃない[e]
[s]EXポケットは絵だ[e]
[s]EXガラスで蓋がしてある[e]

[msg MSG_BTLTSUIKA_990_000EX [Akechi]]
[s][bup 0 9 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1265 0 9]EXそんなはずはない![n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_991_000EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1248 0 3]EXアイツが正々堂々なんてありえないからな![n]観察を続けて見抜いてやろうぜ?[n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_993_000EX [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 2 1249 0 3]EXボールはポケットに入ってたし、[n]それはないと思うぞ?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1250 0 3]EXもう少し観察を続けて、[n]ヤツのイカサマを暴いてやろうぜ?[n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_994_000EX [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1251 0 3]EXなるほどな! 確かにボールがÜ瞬、[n]浮いたような動きをしていた...[n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_995_000EX [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1266 0 9]EX♀めた真似を...[n][f 1 3 65535][w][e]

[msg MSG_FIRSTROULETTE_020_00_2 [Futaba]]
[s][bup 0 8 603 65535 0][f 4 10 65535 0 0][vp 8 0 2 1010 0 8]EX外れた...[n][f 1 3 65535][w][e]

[msg MSG_FIRSTROULETTE_030_00_2 [Shadow Sae]]
[s][vp 8 0 2 1011 1 228]EX残念、運が—かったわね。[n]次もまた、がんばってちょうだい。[n][f 1 3 65535][w][e]

[msg MSG_FIRSTPENALTY_000_000_2 [Shadow Sae]]
[s][vp 8 0 2 1014 1 228]EXあら...ルールを破ったわね?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1015 1 228]EXなら、ペナルティを受けて貰う![n][f 1 3 65535][w][e]

[msg MSG_FIRSTPENALTY_010_000_2 [Shadow Sae]]
[s][vp 8 0 2 1015 1 228]EXなら、ペナルティを受けて貰う![n][f 1 3 65535][w][e]

[msg MSG_FIRSTPENALTY_020_006_2 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1016 0 8]EXちょっ...これがペナルティ!?[n][f 1 3 65535][w][e]

[msg MSG_FIRSTPENALTY_030_000_2 [Shadow Sae]]
[s][vp 8 0 2 1017 1 228]EXルールを守れない者には容赦しない。[n]それが社会というものよ。[n][f 1 3 65535][w][e]

[msg MSG_SECONDROULETTE_000_0_4 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 8]EXスクリーンの映像が変わってる...[n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1020 0 8]EX毎回、賭けの対象は変わるってことだな...[n][f 1 3 65535][w][e]

[msg MSG_SECONDROULETTE_000_0_5 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 8]EXスクリーンの映像が変わってる...[n][f 1 3 65535][w][e]

[msg MSG_SECONDROULETTE_000_0_6 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1020 0 8]EX毎回、賭けの対象は変わるってことだな...[n][f 1 3 65535][w][e]

[msg MSG_SECONDROULETTE_010_0_2 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1020 0 8]EX毎回、賭けの対象は変わるってことだな...[n][f 1 3 65535][w][e]

[msg MSG_NEXTRURE_000_000EX [Shadow Sae]]
[s][vp 8 0 2 1013 1 228]EXさあ、ベットの時間よ![n][f 1 3 65535][w][e]

[msg MSG_FIRSTPENALTY_040_006_2 [Futaba]]
[s][bup 0 8 603 65535 0][f 4 10 65535 0 0][vp 8 0 2 1018 0 8]EXくっ...!![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_200_000EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1252 0 3]EXやはり負けてしまったか...[n]何かわかったか、ジョーカー?[n][f 1 3 65535][w][e]

[msg MSG_SECONDTRICK_000_006E [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1029 0 3]EXさ、三回連続で外れた...[n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1030 0 3]EXねぇ、アイツやっぱりイカサマしてる![n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1031 0 3]EX手口はわかんないけど、[n]こんなにミスが続くなんて変だぞ![n][f 1 3 65535][w][e]

[msg MSG_SECONDTRICK_010_006E [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1030 0 3]EXねぇ、アイツやっぱりイカサマしてる![n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1031 0 3]EX手口はわかんないけど、[n]こんなにミスが続くなんて変だぞ![n][f 1 3 65535][w][e]

[msg MSG_TREE_001_0_SEX]
[s]EX敵はイカサマをしている可能性がある。[n]しかし、手口がわからない...[n][f 1 3 65535][w][e]

[sel SEL_TREE_001_0_SEX top]
[s]EXイカサマじゃない[e]
[s]EXガラスで蓋してる[e]
[s]EXポケットは絵だ[e]

[msg MSG_TREE_001_0_S_0EX [Futaba]]
[s]EXそこまで事態は甘くない...[n]ほぼ間Òいなくイカサマをされている。[n][f 1 3 65535][w][e]

[msg MSG_TREE_001_0_S_1EX [Futaba]]
[s]EX先ほどからポケットが[n]不自然に光を反射している...[n][f 1 3 65535][w][e]
[s]EXこれはもしかすると...[n][f 1 3 65535][w][e]

[msg MSG_TREE_001_0_S_2EX [Futaba]]
[s]EXポケットにボールが入っていた。[n]絵ではそうはいかない...[n][f 1 3 65535][w][e]

[msg MSG_MEMBERRELEASED_000_0_2 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 8]EXガラスでフタぁ...!?[n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1039 0 8]EXそんなストレートなイカサマして、[n]わたしたちを馬鹿にしてる...![n][f 1 3 65535][w][e]

[msg MSG_MEMBERRELEASED_010_0_2 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 8]EXなら、言い逃れできないよう、[n]イカサマの瞬間を抑えてやれ![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1043 0 8]EXガラスでフタをされたら、[n]ポケットを狙撃するんだ![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1044 0 8]EX誰に狙撃させるか、[n]指示出しを頼んだ![n][f 1 3 65535][w][e]

[msg MSG_MEMBERRELEASED_020_0_2 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 8]EXガラスでフタをされたら、[n]ポケットを狙撃するんだ![n][f 1 3 65535][w][e]

[msg MSG_MEMBERRELEASED_030_0_2 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1044 0 8]EX誰に狙撃させるか、[n]指示出しを頼んだ![n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_700_000EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1253 0 3]EXなあ、見間Òいかもしれんが...[n]あのボール、浮いてなかったか?[n][f 1 3 65535][w][e]

[sel SEL_TREE_900_0_SEX top]
[s]EXポケットが絵になってる?[e]
[s]EXガラスで蓋がしてある?[e]

[msg MSG_BTLTSUIKA_500_000EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1254 0 3]EXボールはポケットに入ってたし、[n]それはないと思うぜ?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1255 0 3]EXボールがポケットへ入る直前、[n]宙に浮いたように見えたんだ。[n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_400_002EX [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1256 0 3]EXそうか、そういうことか![n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_410_008EX [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0]EX♀めた真似を...[n][f 1 3 65535][w][e]

[msg MSG_BTLTSUIKA_420_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 8]EXなら、言い逃れできないよう、[n]イカサマの瞬間を抑えてやれ![n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 8]EXガラスでフタをされたら、[n]ポケットを狙撃するんだ![n][f 1 3 65535][w][e]

[msg charaorder_Reiji_02EX [Ryuji]]
[s]EX任せろ![n][w][e]

[msg charaorder_Morgana_02EX [Morgana]]
[s]EXワガハイ、ゴー![n][w][e]

[msg charaorder_Ann_02EX [Ann]]
[s]EXオーケー、ジョーカー![n][w][e]

[msg charaorder_Yugo_02EX [Yusuke]]
[s]EXよし、待っていろ。[n][w][e]

[msg charaorder_Makoto_02EX [Makoto]]
[s]EXうん...やってみる![n][w][e]

[msg charaorder_Ranko_02EX [Haru]]
[s]EXうん、私が行く![n][w][e]

[msg charaorder_Hutaba_02EX [Futaba]]
[s]EXダミーなんですよ~。[n]私の出番はまだまーだ先~。[n][w][e]

[msg charaorder_Akechi_02EX [Akechi]]
[s]EXああ、必ず成功させる![n][w][e]

[msg MSG_ATTENTION01_000_000E [Shadow Sae]]
[s][vp 8 0 2 1066 1 228]EX私に勝つのであれば...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_010_000E [Shadow Sae]]
[s][vp 8 0 2 1067 1 228]EX運を身につけないと、ね...?[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_020_002E [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1068 0 3]EX—運なら負けないつもりだ。[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_030_002E [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0]EXジョーカー![n]この調子で耐えろよ![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_020_003E [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 4]EX運、ねぇ...ま、いいけどさ。[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_030_003E [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 4]EXジョーカー![n]もうちょっと耐えててね![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_020_004E [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 5]EX運か...怪しいものだな。[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_030_004E [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 5]EXジョーカー、[n]もうしばらく耐えてもらうぞ。[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_020_005E [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 6]EX姉さん...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_030_005E [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 6]EXジョーカー、もう少し耐えて...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_020_008E [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 9]EXうまく進めているね...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION01_030_008E [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 9]EXジョーカー、この調子で耐えてくれ。[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_000_000E [Shadow Sae]]
[s]EX勝負運というのはね、呼び込めるものなのよ。[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_010_000E [Shadow Sae]]
[s]EX『負けられない』という信念さえあればね...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_020_002E [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 3]EXフン、最後に笑うのはワガハイらだ...![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_030_002E [Morgana]]
[s]EXダミー[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_020_003E [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 4]EXこっちだって負ける気ないっつの...![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_030_003E [Ann]]
[s]EXダミー[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_020_004E [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 5]EX良い調子だ、今のうちに進む。[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_030_004E [Yusuke]]
[s]EXダミー[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_020_005E [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 6]EXまだ、気付かれてないみたいね...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_030_005E [Makoto]]
[s]EXダミー[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_020_008E [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 9]EXうまく進めているね...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION02_030_008E [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 9]EX良い調子だね...進むよ![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION03_000_000E [Shadow Sae]]
[s][vp 8 0 2 1085 1 228]EXツキに見放されるのは怖いわね...[n]どうやっても失敗ばかり...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1086 1 228]EX嫌気がさしたなら、[n]潔く諦めるのも大切よ?[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION03_010_000E [Shadow Sae]]
[s][vp 8 0 2 1086 1 288]EX嫌気がさしたなら、[n]潔く諦めるのも大切よ?[n][f 1 3 65535][w][e]

[msg MSG_ATTENTIONSUCCESS_M_0_2 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1092 0 8]EX派遣者が狙撃地点に到着。[n]後は次のルーレットを待つだけだな。[n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_000_002E [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 3]EXよし、撃つぞ![n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_000_003E [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 4]EX来た![n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_000_004E [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 5]EXチャンスだ![n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_000_005E [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 6]EX姉さんを、止める...![n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_000_008E [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 2 1 0 9]EX覚悟して貰う...![n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_010_000E [Shadow Sae]]
[s][vp 8 0 2 1098 1 228]EX今度こそ、予想が当たるといいわね...[n]フフフ...[n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_010_001E [Shadow Sae]]
[s][vp 8 0 2 1099 1 228]EXなっ...何ぃぃっ!?[n][f 1 3 65535][w][e]

[msg MSG_TRICKBUSTER_020_006E [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1100 0 8]EXやっぱり...ジョーカー![n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_000_006E [Shadow Sae]]
[s][vp 8 0 2 1102 1 228]EXあらあら、負け続きじゃない。[n]運が無いのねぇ?[n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_010_006E [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1103 0 8]EXな...何が運だっ![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1104 0 8]EXどーせイカサマだろ!?[n]こんなに勝てないなんておかしい![n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_020_000E [Shadow Sae]]
[s][vp 8 0 2 1105 1 228]EX...! イカサマなんて...[n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_030_006E [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1106 0 8]EXしてないハズない![n]ウソ! バレバレだ![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1107 0 8]EXこっちはジョーカーとわたしだけなんだぞ![n]大人のクセに、恥を知れ![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1109 0 8]EXそもそも、イカサマしなきゃ[n]なんないほど弱いのか?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1110 0 8]EXそれで何がパレスの主だ?[n]ただのザコじゃん、やっぱり恥を知れーっ![n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_031_000E [Shadow Sae]]
[s][vp 8 0 2 1108 0 228]EX......。[n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_040_006E [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1109 0 8]EXそもそも、イカサマしなきゃ[n]なんないほど弱いのか?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1110 0 8]EXそれで何がパレスの主だ?[n]ただのザコじゃん、やっぱり恥を知れーっ![n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_050_000E [Shadow Sae]]
[s][vp 8 0 2 1111 1 228]EX勝てないからって、ずいぶん言うじゃない...[n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_060_006E [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1112 0 8]EXうっさい! そもそも...[n][f 1 3 65535][w][e]

[msg MSG_TSUMIBOUSHI_070_000E [Shadow Sae]]
[s][vp 8 0 2 1113 1 288]EXうるさいのはそっちよ!![n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_000_002EX [Morgana]]
[s]EXダミー[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_000_003EX [Ann]]
[s]EXダミー[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_000_004EX [Yusuke]]
[s]EXダミー[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_000_005EX [Makoto]]
[s]EXダミー[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_000_008EX [Akechi]]
[s]EXダミー[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_010_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1101 0 8]EXオイ、何が正々堂々だ![n]思いっきりイカサマだったぞ![n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_020_006EX [Futaba]]
[s]EXダミー[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_030_000EX [Shadow Sae]]
[s][vp 8 0 2 1114 1 288]EXう...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1115 1 288]EXううっ...[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_040_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1116 0 8]EXこの卑怯者、なに黙ってんだ![n]なんとか言えーっ![n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_050_000EX [Shadow Sae]]
[s]EXダミー[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_060_000EX [Shadow Sae]]
[s]EXダミー[n][f 1 3 65535][w][e]

[msg MSG_HOLDUP_070_000EX [Shadow Sae]]
[s][vp 8 0 2 1117 1 288]EXうるさい黙れぇっ!![n][f 1 3 65535][w][e]

[msg MSG_SECONDMODE_000_005EX [Makoto]]
[s][bup 0 6 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1118 0 6]S-Sis!?[n][f 1 3 65535][w][e]

[msg MSG_SECONDMODE_000_006EX [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1119 0 6]What the—!?[n][f 1 3 65535][w][e]

[msg MSG_SECONDMODE_010_000EX [Shadow Sae]]
[s][vp 8 0 2 1120 1 228]Cheating!? Unfair!? Silence! This is[n]MY world![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1121 1 228]I AM the law! I am everything! No one[n]in this world deserves to win, except for[n]ME![n][f 1 3 65535][w][e]

[msg MSG_SECONDMODE_020_000EX [Shadow Sae]]
[s][vp 8 0 2 1122 1 228]If you still dare to defy my justice, then[n]prepare to be totally crushed![n][f 1 3 65535][w][e]

[msg MSG_SECONDMODE_030_005EX [Makoto]]
[s][bup 0 6 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1123 0 6]EXこれがお姉ちゃんの...本性!? そんな...[n][f 1 3 65535][w][e]

[msg MSG_SECONDMODE_030_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1124 0 8]EXこれがヤツの本性ってことか...!?[n][f 1 3 65535][w][e]

[msg MSG_SECONDMODE_040_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1125 0 8]EXようやく戦闘らしくなるな。[n]気をêき締めろ、ジョーカー![n][f 1 3 65535][w][e]

[msg MSG_GOBET_000_008EX [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1126 0 8]EXまだルーレットが動いてるぞ。[n]主のÄ志とは無関係なのか...?[n][f 1 3 65535][w][e]

[msg MSG_GOBET_010_008EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1127 0 8]EXなあ、これってチャンスじゃないか。[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1128 0 8]EXもうイカサマされないし、[n]ルーレットで勝てば、戦いが有利になるぞ。[n][f 1 3 65535][w][e]

[msg MSG_SECONDROULE_000_000E [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1259 0 3]EXオマエ、性懲りもなく![n][f 1 3 65535][w][e]

[msg MSG_SECONDROULE_010_000E [Shadow Sae]]
[s][vp 8 0 2 1260 0 3]EX私は負けることはない![n]なぜなら私がルールだから!![n][f 1 3 65535][w][e]

[msg MSG_SECONDROULE_020_000E [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1261 0 3]EX...アイツがルール?[n]何を考えてやがるんだ。[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1262 0 3]EXジョーカ－、[n]ルーレットには十分注Äしろ![n][f 1 3 65535][w][e]

[msg MSG_HP75_000_000EX [Shadow Sae]]
[s][vp 8 0 2 1129 1 288]EXどんな手段を使っても、勝てばいいのよ!![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1130 1 288]EXあなたたちだってそうでしょう!?[n]目的のÈに、他人の心を操作してるじゃない![n][f 1 3 65535][w][e]

[msg MSG_HP75_010_005EX [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1131 0 6]EXそれは自分のÈじゃない![n]困っている誰かを助けるÈよ![n][f 1 3 65535][w][e]

[msg MSG_HP75_010_008EX [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1132 0 9]EXそれは自分のÈじゃない! 正義のÈだ![n][f 1 3 65535][w][e]

[msg MSG_HP75_010_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1133 0 8]EXそれは自分のÈじゃない![n]困っている誰かを助けるÈだ![n][f 1 3 65535][w][e]

[msg MSG_HP50_000_000EX [Shadow Sae]]
[s][vp 8 0 2 1134 1 288]EX私は勝つ![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1135 1 288]EX勝てばそれが正義なのよ![n][f 1 3 65535][w][e]

[msg MSG_HP25_000_000EX [Shadow Sae]]
[s][vp 8 0 2 1136 1 288]EX勝てば、勝てばいいのよ...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1137 1 288]EX勝ちさえすれば...[n]それで、きっと...[n][f 1 3 65535][w][e]

[msg MSG_HP25_020_005EX [Makoto]]
[s][bup 0 6 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1138 1 288]EXお姉ちゃん...[n][f 1 3 65535][w][e]

[msg MSG_HP00_010_005EX [Makoto]]
[s][bup 0 6 104 65535 0][f 4 10 65535 0 0]EXお姉ちゃん!![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXTRA_HINT0 [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1087 0 9]What? The roulette panels changed?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXTRA_HINT0B [Makoto]]
[s][bup 0 6 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1088 0 6]Wait! The roulette panels—!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXTRA_HINT0C [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1089 0 8]Wh-What the— The roulette panels[n]changed!?[n][f 1 3 65535][w][e]

[msg MSG_AFFINITY_CHANGE00 [Shadow Sae]]
[s]オフセット用[n][w][e]

[msg MSG_AFFINITY_CHANGE01 [Shadow Sae]]
[s][vp 8 0 2 1090 1 288]My justice has revealed to me... I must[n]judge evil with a burning rage![n][f 1 3 65535][w][e]

[msg MSG_AFFINITY_CHANGE02 [Shadow Sae]]
[s][vp 8 0 2 1091 1 288]My justice has revealed to me... I must[n]judge evil with an icy heart![n][f 1 3 65535][w][e]

[msg MSG_AFFINITY_CHANGE03 [Shadow Sae]]
[s][vp 8 0 2 1093 1 288]My justice has revealed to me... I must[n]strike at evil with my bolt of judgment![n][f 1 3 65535][w][e]

[msg MSG_AFFINITY_CHANGE04 [Shadow Sae]]
[s][vp 8 0 2 1092 1 288]My justice has revealed to me... I must[n]judge evil like a furious tempest![n][f 1 3 65535][w][e]

[msg MSG_AFFINITY_CHANGE05 [Shadow Sae]]
[s][vp 8 0 2 1095 1 288]My justice has revealed to me... I must[n]decimate these evil minds that defy me![n][f 1 3 65535][w][e]

[msg MSG_AFFINITY_CHANGE06 [Shadow Sae]]
[s][vp 8 0 2 1094 1 288]My justice has revealed to me... I must[n]purge all evil at an atomic level![n][f 1 3 65535][w][e]

[msg MSG_AFFINITY_CHANGE07 [Shadow Sae]]
[s][vp 8 0 2 1096 1 288]My justice has revealed to me... I have[n]been blessed with the ability to destroy[n]all evil![n][f 1 3 65535][w][e]

[msg MSG_AFFINITY_CHANGE08 [Shadow Sae]]
[s][vp 8 0 2 1097 1 288]My justice has revealed to me... that[n]cursing all evil is the correct course![n][f 1 3 65535][w][e]

[msg MSG_AFFINITY_CHANGE09 [Shadow Sae]]
[s][vp 8 0 2 1107 1 288]I'm right... I'm always right...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1108 1 288]That's why I have to be the victor! All who[n]stand in my way will be crushed![n][f 1 3 65535][w][e]

[msg MSG_AFFINITY_AFTER_CHANG [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1098 0 8]Be careful, Joker! Something's up with her![n][f 1 3 65535][w][e]

[msg MSG_AFFINITY_AFTER_FEVER [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1103 0 3]Wh-What the—!?[n][f 1 3 65535][w][e]

[msg MSG_AFFINITY_AFTER_FEVER_2 [Makoto]]
[s][bup 0 6 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1104 0 6]Wh-What in the world!?[n][f 1 3 65535][w][e]

[msg MSG_AFFINITY_AFTER_FEVER_3 [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1105 0 9]What's going on!?[n][f 1 3 65535][w][e]

[msg MSG_AFFINITY_AFTER_FEVER_4 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1106 0 8]What the—!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXTRA_HINT1 [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1264 0 9](未使用)気づいてるかい?[n]今のルーレットの結果...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1264 0 9](未使用)この勝負、僕らの勝ちかもね。[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXTRA_HINT2 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 8](未使用)!?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1005 0 8](未使用)何か分かったならはっきり言え![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXTRA_HINT3 [Akechi]]
[s][bup 0 9 101 65535 0][f 4 10 65535 0 0][vp 8 0 2 1264 0 9](未使用)ゴメンゴメン。[n]ここからは僕のちょっとした推理なんだけど...[n][f 1 3 65535][w][e]
[s][bup 0 9 100 65535 0][f 4 10 65535 0 0][vp 8 0 2 1264 0 9](未使用)ここは彼女の認知で出来たパレスだ。[n]ルーレット盤も彼女のÜ部と考えていいよね。[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 2 1264 0 9](未使用)さっきのイカサマもそういうことさ。[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXTRA_HINT3_2 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 8](未使用)そんなコトは分かってる![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXTRA_HINT3_3 [Akechi]]
[s][bup 0 9 100 65535 0][f 4 10 65535 0 0][f 4 10 65535 0 0](未使用)まあ聞いてよ。彼女の攻撃が[n]天秤から発生しているのは分かるよね。[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 2 1264 0 9](未使用)さっきから見ていたけど、ルーレットを[n]回す時、彼女は天秤も同時に制御している。[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 2 1264 0 9](未使用)そして、天秤の攻撃はルーレットの[n]結果と連動していることが見て取れた。[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXTRA_HINT3_4 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 8](未使用)...!![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXTRA_HINT3_5 [Akechi]]
[s][bup 0 9 100 65535 0][f 4 10 65535 0 0][vp 8 0 2 1264 0 9](未使用)彼女が攻撃する時、[n]天秤からルーレット盤までよく観察してごらん。[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1264 0 9](未使用)攻撃とルーレット結果が[n]連動していることに気づけると思うよ。[n][f 1 3 65535][w][e]
[s][bup 0 9 101 65535 0][f 4 10 65535 0 0][vp 8 0 2 1264 0 9](未使用)...あとは分かるだろ?[n]僕がライバルと認めた君ならね。[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXTRA_HINT5 [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1264 0 9](未使用)またハズレか...[n]このままじゃ危ないよ。[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 2 1264 0 9](未使用)敵の行動と、[n]結果を関連付けて考えてみてくれ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXTRA_SCALE1 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1247 0 3](未使用)...天秤!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXTRA_SCALE2 [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1264 0 9](未使用)天秤は司法と公正の象徴...![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXTRA_SCALE3 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 8](未使用)あれを使って何をするつもりだ?[n][f 1 3 65535][w][e]

