[msg MSG_BATTLESTART02_000_00 [Shadow Shido]]
[s]It seems you still don't understand[n]what happens when you defy me.[n][f 1 3 65535][w][e]
[s]...I will destroy you with my own[n]two hands.[n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART02_010_00 [Futaba]]
[s]What is this power!?[n][f 1 3 65535][w][e]
[s]Careful! Those muscles aren't just for[n]show![n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART02_020_00 [Shadow Shido]]
[s]You will regret your actions.[n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART02_030_00 [Shadow Shido]]
[s]...You've angered me for the last time.[n][f 1 3 65535][w][e]

[msg MSG_02HP50_000_000 [Shadow Shido]]
[s]Not bad...[n][f 1 3 65535][w][e]

[msg MSG_02HP50_010_000 [Shadow Shido]]
[s]But there is no reason for me to lose[n]to thieves![n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_000_00 [(SE)シャドウ獅童]]
[s](苦しむ声)[n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_010_00 [Shadow Shido]]
[s]How are these lowlife brats beating me?[n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_020_00 [Futaba]]
[s]Now's our chance! Let's take his Treasure![n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_030_00 [(SE)シャドウ獅童]]
[s](狂った高笑い)[n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_040_00 [(SE)シャドウ獅童]]
[s]Don't think you've won.[n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_050_00 [(SE)シャドウ獅童]]
[s](鼻で笑う)[n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_060_00 [Shadow Shido]]
[s]The power held by the most elite is[n]what rules over our society...[n][f 1 3 65535][w][e]
[s]It's vexing that I have to use this on[n]some foolish brats...[n][f 1 3 65535][w][e]
[s]But I will educate you through and[n]through![n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_070_00 [Morgana]]
[s]He's still gonna come at us!?[n][f 1 3 65535][w][e]

[sel SEL_BATTLESTART03_080_00 top]
[s]Time to do this![e]
[s]Let's take his heart.[e]
[s]What a hassle...[e]

[msg MSG_BATTLESTART03_090_00 [Morgana]]
[s]All right![n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_091_00 [Morgana]]
[s]You hear that, Shido!?[n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_092_00 [Morgana]]
[s]All right, our next move is gonna[n]end this once and for all![n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_100_00 [(SE)シャドウ獅童]]
[s](♀♀)[n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_110_00 [Futaba]]
[s]No way! He's even stronger now!?[n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_120_00 [Shadow Shido]]
[s]...Die.[n][f 1 3 65535][w][e]

[msg MSG_03HP50_000_000 [Shadow Shido]]
[s]Isn't this supposed to be... a "game"[n]arranged by God?[n][f 1 3 65535][w][e]

[msg MSG_03HP50_010_000 [Shadow Shido]]
[s]Why are the signs of defeat pointing[n]in my direction!?[n][f 1 3 65535][w][e]

[msg MSG_03HP50_020_000 [Morgana]]
[s]You're a disgrace![n][f 1 3 65535][w][e]

[msg MSG_03HP50_030_000 [Shadow Shido]]
[s]I accept that you are my destined[n]enemy.[n][f 1 3 65535][w][e]
[s]...Let us have a duel to end this.[n]Just you and me.[n][f 1 3 65535][w][e]

[sel SEL_03HP50_040_000 top]
[s]Bring it on.[e]
[s]I accept.[e]

[msg MSG_03HP50_050_000 [Shadow Shido]]
[s]Well put.[n][f 1 3 65535][w][e]

[msg MSG_03HP50_060_000 [Shadow Shido]]
[s]I... shall win this game![n][f 1 3 65535][w][e]

[msg MSG_03HP50_070_000 [Shadow Shido]]
[s]The ideals of the masses...[n][f 1 3 65535][w][e]

[msg MSG_03HP50_080_000 [Shadow Shido]]
[s]My... ambitions...[n][f 1 3 65535][w][e]

[msg MSG_03HP50_090_000 [Shadow Shido]]
[s]The sea is... swallowing them all...[n][f 1 3 65535][w][e]

