[msg MSG_NEXT_BTLSTART_001 [Ryuji]]
[s][bup 0 2 104 0 0][vp 8 0 2 7029 0 3][f 4 10 65535 0 0]Gah, that weird one's back![n][f 1 3 65535][w][e]

[msg MSG_NEXT_BTLSTART_002 [Morgana]]
[s][bup 0 3 2 0 0][vp 8 0 2 1112 0 3][f 4 10 65535 0 0]Stay calm—we have a general idea of[n]how to deal with it now, thanks to[n]our last showdown![n][f 1 3 65535][w][e]

[msg MSG_NEXT_BTLSTART_003 [Ann]]
[s][bup 0 4 102 0 0][vp 8 0 2 1112 0 3][f 4 10 65535 0 0]Right. Let's make this quick![n][f 1 3 65535][w][e]

