C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E910_091.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E940_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E950_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_010.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_086.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_111.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_112.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_113.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_114.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_120.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_130.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_707.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_722.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_750.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E980_767.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E993_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E994_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E995_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E996_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E996_002.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E997_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E998_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E999_100.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E999_103.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
pause