[msg MND_000_0_0]
[s]Não reconheço este número...[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Respostas[e]
[s]Ignorar[e]

[msg MND_002_0_0]
[s]Esse número de novo...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Prisioneiro, não me diga que você[n]estava ocioso.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Um assunto importante requer[n]sua atenção. Você pode nos contatar agora?[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Está bem.[e]
[s]Estou com sono.[e]

[msg MSG_006_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Venha aqui AGORA![n]Caso contrário, você será executado![n][f 1 3 65535][w][e]

[msg MND_007_0_0]
[s]Eu deveria ir para o Velvet Room.[n][f 1 3 65535][w][e]

