[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 0 65535 0]Vocês sabem o que é um truque?[n][f 1 3 65535][w][e]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]Eu vi recentemente na TV. Foi muito legal![n][f 1 3 65535][w][e]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]Eu acho que foi chamado de...[clr 1]arremesso [clr 27]![n]Vamos tentar![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ann]]
[s][bup 0 4 0 65535 0][vp 8 0 0 0 65535 0]Sim! Isso parece divertido![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 0 65535 0]Ei, você quer experimentar um truque?[n][f 1 3 65535][w][e]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]Eu acho que foi chamado de [clr 1]mão traseira [clr 27].[n]Você acha que podemos fazer isso?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][vp 8 0 0 0 65535 0]Você não pode nem segurar um bastão de[n]sugestão.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 0 65535 0]Vocês, vamos tentar um truque![n][f 1 3 65535][w][e]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]Vamos tentar o chamado [clr 1]massé[clr 27]![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]Se ao menos eu fosse duas pernas...[n]Tudo bem, vou deixar você levar os[n]holofotes, [f 4 2]![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]Tudo bem, vamos tentar um truque![n][f 1 3 65535][w][e]

[msg MSG_007_0_0]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]Você é muito bom! Você provavelmente é o[n]próximo cara mais legal- depois de mim, é[n]claro![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]Progressão é poder. Você parecia muito bem[n]quando estava dando o seu melhor.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][vp 8 0 0 0 65535 0]Tudo pronto![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][vp 8 0 0 0 65535 0]Está pronto![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 1 65535 0][vp 8 0 0 0 65535 0]Você está pronto para ir![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][vp 8 0 0 0 65535 0]Configure completo.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][vp 8 0 0 0 65535 0]Você deve estar pronto para ir.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Haru]]
[s][bup 0 7 1 65535 0][vp 8 0 0 0 65535 0]Está tudo configurado para você![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][vp 8 0 0 0 65535 0]Configurar missão, completa![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][vp 8 0 0 0 65535 0]Você está pronto para ir.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][vp 8 0 0 0 65535 0]O palco é seu.[n][f 1 3 65535][w][e]

