[msg MSG_000_0_0 [Shadow Shido]]
[s][bup 0 206 603 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Como eu poderia... perder?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [(SE)シャドウ獅童]]
[s][vp 8 0 0 2 65535 0](♀き)[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Por causar inumeros desligamentos mentais[n]Em outros, voce expiara... com sua vida.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 111 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Nao tem algo a dizer ao nosso[n]Lider antes de voce passar?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Shadow Shido]]
[s][bup 0 206 600 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Sim...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Shadow Shido]]
[s][bup 0 206 603 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Eu reconheco... que eu te incriminei[n]por acusacoes falsas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Eu fiz isso para me proteger...[n][f 1 3 65535][w][e]

[msg MSG_005_5_0 [Shadow Shido]]
[s][bup 0 206 603 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Sinto muito pelo que fiz...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Shadow Shido]]
[s][bup 0 206 601 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Parece que tem sido bastante[n]algum tempo desde que me senti sinceramente[n]apologetico...[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]Voce realmente quis dizer isso?[e]
[s]Confesse seus crimes.[e]
[s]Expiar o que voce fez.[e]

[msg MSG_009_0_0 [Shadow Shido]]
[s][bup 0 206 603 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Eu nao tenho forca de vontade para enganar voce[n]neste ponto...[n][f 1 3 65535][w][e]

[msg MSG_009_5_0 [Shadow Shido]]
[s][bup 0 206 603 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Entao, eu fui derrotado... haha...[n]Hahahaha...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Shadow Shido]]
[s][bup 0 206 601 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Hmph... isso pode ser bom...[n][f 1 3 65535][w][e]

[msg MSG_010_2_0 [Shadow Shido]]
[s][bup 0 206 603 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Entao, eu fui derrotado... haha...[n]Hahahaha...[n][f 1 3 65535][w][e]

[msg MSG_010_3_0 [Shadow Shido]]
[s][bup 0 206 601 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Hmph... isso pode ser bom...[n][f 1 3 65535][w][e]

[msg MSG_010_5_0 [Shadow Shido]]
[s][bup 0 206 603 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Entao, eu fui derrotado... haha...[n]Hahahaha...[n][f 1 3 65535][w][e]

