[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]E verdade que mesmo se apagarmos o[n]Metaverso, nao ha garantia de que[n]O mundo vai melhorar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]E se perdermos nossos poderes, nao seremos[n]capaz de enfrentar criminosos como[n]Shido de novo...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Entao, seria mais definitivo se nos[n]mudou o coracao dos criminosos quando eles vem[n]para cima, assim como fizemos?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Sinceramente, nao sei dizer qual e o melhor[n]metodo para fazer isso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]No entanto, Shido teve uma mudanca de[n]coracao. Duvido que ele tenha problemas deve[n]Ele se tornou primeiro-ministro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]No entanto, nao vai ficar bem conosco...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]... Entao, devemos ter como alvo criminosos[n]E nao o publico em geral, hein?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Rapazes...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]...Voce sabe o que?[f 4 2]esta certo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]E aqui que eu pertenco... eu quero continuar[n]Parte dos ladroes Phantom![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]... meus pensamentos exatamente.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Vou... adiar a decisao do nosso lider.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Entao, alguma objecao?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Entao, continuaremos como Phantom[n]Ladroes juntos?[n][f 1 3 65535][w][e]

