[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Droga! Isso nunca vai acabar![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Parece sem esperanca se houver tantos[n]presos apoiando isso...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Godlike Voice]]
[s][vp 8 0 0 3 65535 0]Seus tolos. Humano, mas desejando[n]erradicar os desejos da humanidade...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 104 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Quem e aquele!?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Godlike Voice]]
[s][vp 8 0 0 5 65535 0]Arrepender-se.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][bup 0 6 104 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]O tesouro esta falando!?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Godlike Voice]]
[s][vp 8 0 0 7 65535 0]Eu sou reverenciado como a graca dos sonhos[n]Para todos que me veem...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 8 65535 0]Um ser mais conhecido como[n]o Santo Graal...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Haru]]
[s][bup 0 7 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]O Santo Graal...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Holy Grail]]
[s][vp 8 0 0 10 65535 0]A prisao de regressao e representativa[n]dos desejos coletivos da humanidade.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 11 65535 0]Eles desejam ser acorrentados, rendo[n]sua cognicao e negligencie o mundo[n]Ao redor deles...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 13 65535 0]Esses Commonfolk com problemas com problemas vao[n]Faca sua "reforma social" tudo por nada.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Holy Grail]]
[s][vp 8 0 0 20 65535 0]O coracao compartilhado das massas tem[n]caiu em excesso de indolencia[n]e transformado em uma prisao.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [(SE)囚人たちの声]]
[s][vp 8 0 0 0 65535 0](聖杯を崇拝するおぞましい声『おぉ...』『聖杯ぃ...』など)[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Droga... eles estao adorando essa coisa![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Holy Grail]]
[s][vp 8 0 0 22 65535 0]Assim... o unico fim adequado para eles e[n]perecer dentro da prisao que eles desejavam[n]para eles mesmos.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Prepare-se! Aqui vem![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Isso ai![n][f 1 3 65535][w][e]

