[msg MSG_000_0_0 [Brown-Haired Young Man]]
[s][vp 8 0 0 1 40 0]Aqueles ladroes fantasmas...[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Brown-Haired Young Man]]
[s][vp 8 0 0 2 40 0]Pegue-o... derrube-o![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Jacket-Wearing Young Man]]
[s][vp 8 0 0 3 38 0]Por que... por que eu esqueci sobre eles?[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Jacket-Wearing Young Man]]
[s][vp 8 0 0 4 38 0]Eles me inspiraram tambem![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Brown-Haired Young Man]]
[s][vp 8 0 0 5 40 0]Provavelmente nao estivemos pensando[n]direto por um tempo agora...[n][f 1 3 65535][w][e]

[msg MSG_002_5_0 [Brown-Haired Young Man]]
[s][vp 8 0 0 6 40 0]Ja era hora de sairmos disso![n]Funcionar das coisas nao ajudara![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Jacket-Wearing Young Man]]
[s][vp 8 0 0 7 38 0]Phantom Thieves![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [(SE)茶髪の青年]]
[s][vp 8 0 0 8 40 0]聴こえるかー!? 怪盗団ーッ![n][f 1 2 90][e]

