[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1170 65535 0]Se ao menos Yoshizawa se juntasse ao[n]Phantom Thieves... que pena.[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Nao ha nada que possamos fazer.[e]
[s]Talvez pudessemos perguntar a ela novamente.[e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1020 65535 0]Sim, nao devemos pressionar o assunto.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 53107 65535 0]Eu duvido seriamente a resposta dela jamais[n]mudanca 悪 ela obviamente respondeu[n]Sem qualquer hesitacao.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Entao, como vamos quebrar[n]para os outros?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1169 65535 0]Acho que ainda temos alguns problemas[n]para sair...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Poderiamos causar mais mal do que ajudar se nos[n]trouxe a tona neste momento 悪 talvez nos vamos[n]Apenas fique quieto sobre Yoshizawa por enquanto.[n][f 1 3 65535][w][e]

