[msg MSG_000_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ah,[f 4 1]-senpai 悪 tao bom ver voce![n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Como voce esteve?[e]
[s]Como ta indo?[e]

[msg MSG_002_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Eu estive indo muito bem.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Esta indo maravilhosamente.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Voce tambem esta prestes a almocar,[n][f 4 1]-senpai?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Se estiver tudo bem com voce, voce se importaria[n]Comer juntos?[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]Boa ideia.[e]
[s]Claro.[e]

[msg MSG_007_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Ah, que bom ver voces dois juntos.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Oh, voce gostaria de se juntar a nos para almocar,[n]Dr. Maruki? Estavamos apenas discutindo[n]comendo juntos.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Tem certeza? Bem, talvez eu marque[n]junto, entao.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Maruki]]
[s][bup 0 216 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Umm, e isso... seu almoco,[n]Yoshizawa-san?[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]Ela e uma senhora em crescimento.[e]
[s]Bem, ela e uma atleta.[e]

[msg MSG_012_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Isso realmente nao...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Kasumi]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Eu tenho que comer muito para me manter ativo![n]Eu sempre queime tudo o que como![n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Do meu ponto de vista, sao seus dois[n]Almocos que sao o problema aqui.[n][f 1 3 65535][w][e]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 5 100][vp 8 0 0 13 65535 0]Se voce vai fortalecer seu corpo,[n]Voce tem que comer direito. Voce deveria realmente[n]Trabalhe em suas dietas.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Maruki]]
[s][bup 0 216 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Hahaha, touch姻.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]E voce esta certo, o seu parece[n]nutritivo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Voce sabe...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Voce parece estar emitindo um diferente[n]Vibe ultimamente.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Sim! Eu pude colocar meus problemas em[n]o passado e seguir em frente.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Ah, entao e isso que e. Voce nao parece[n]estar superexertando-se tambem.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Lamento que eu tenha preocupado voce.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Oh, de jeito nenhum. E maravilhoso ouvir[n]Como voce tem estado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Devo admitir que estou um pouco surpreso. Se voce[n]Nao me importe com a minha pergunta, houve alguns[n]tipo de razao para esse avanco?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Nos iremos...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]E tudo gracas a[f 4 1]-senpai e[n]seus conhecidos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Suponho que voce poderia dizer que eles me deram[n]uma razao para repensar as coisas 悪 ou, mais como[n]Um motivo para enfrentar meus problemas.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Nao e isso mesmo,[f 4 1]-senpai?[n][f 1 3 65535][w][e]

[sel SEL_026_0_0 top]
[s]Isso mesmo.[e]
[s]E melhor voce ficar agradecido.[e]

[msg MSG_027_0_0 [Maruki]]
[s][bup 0 216 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Suba seus problemas, nao e?[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Voce se tornou muito forte,[n]Yoshizawa-san.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Mmhm, estou totalmente superando agora![n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Desculpe por falar muito. Por que nao nos[n]Concentre-se em nossos almocos?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Obrigado pela comida![n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Oh, eu esqueci que tenho um par em seguida.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Eu deveria ir. Por favor, de-me licenca![n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Yoshizawa-san realmente parece ter[n]Encontrei seu pe.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Ela parecia absolutamente atormentada sobre[n]a situacao dela outro dia...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Eu tenho que dizer, essa mudanca drastica tem[n]Realmente me derrubou por um loop. Talvez[n]Os ladroes fantasmas mudaram seu coracao?[n][f 1 3 65535][w][e]

[sel SEL_041_0_0 top]
[s]Eu nao acho.[e]
[s]Qualquer coisa e possivel.[e]

[msg MSG_042_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Haha, eu estava apenas brincando.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Parece que o tempo acabou. Voce deveria ir[n]de volta a aula tambem.[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Maruki]]
[s][bup 0 216 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Ate a proxima.[n][f 1 3 65535][w][e]

[msg MSG_044_5_0 [Maruki]]
[s][bup 0 216 3 65535 0][vp 1 0 0 40 0 0]......[n][f 1 3 65535][w][e]

