[msg MSG_000_0_0 [School Announcement]]
[s][vp 8 0 0 0 65535 0]A aula comecara momentaneamente.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]A aula comecara momentaneamente.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eu repito...[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]... eu deveria encontrar um[n]fora daqui.[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Isso e...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [(SE)高巻 杏]]
[s][vp 8 0 0 0 65535 0]Se isso nunca tivesse acontecido, eu teria[n]Cheguei a aproveitar meu tempo no ensino medio[n]com shiho.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [(SE)坂本 竜司]]
[s][vp 8 0 0 0 65535 0]Eu praticaria o tempo todo, seria incrivel[n]Resultados em encontros de pista ao lado de[n]todo mundo na equipe...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]E eventualmente eu conseguiria alguns[n]bolsas de estudo para a faculdade para fazer coisas[n]mais facil para minha mae...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [(SE)新島 真]]
[s][vp 8 0 0 0 65535 0]Desde a morte de nosso pai, meu[n]irma esta apoiando a familia 悪 e[n]irrealista para exigir mais dela.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [(SE)佐倉 双葉]]
[s][vp 8 0 0 0 65535 0]...家族、お母さん。[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [(SE)モルガナ]]
[s][vp 8 0 0 0 65535 0]E como um homem humano, eu seria tao assim[n]esplendido.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [(SE)奥村 春]]
[s][vp 8 0 0 0 65535 0]Estou ajudando os alimentos okumura a crescer,[n]com meu pai me vigiando...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]E isso que eu imagino fazer para fazer[n]um ente querido orgulhoso.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [(SE)喜多川 祐介]]
[s][vp 8 0 0 0 65535 0]けど母は、生きている間に[n]自身の作品が評価されることはなかった...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [(SE)喜多川 祐介]]
[s][vp 8 0 0 0 65535 0]絵を続ける意欲が増す一方で、[n]亡き母の無念を想うと...[n][f 1 3 65535][w][e]

