[sel YESNO_SEL top]
[s]Sim[e]
[s]Nao[e]

[msg MSG_000_0_0]
[s]Ficticio[n][w][e]

[msg fev0409_10_NG_mes01 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5001 65535 0]...Voce precisa de algo?[n][w][e]

[sel fev0409_10_NG_SEL top]
[s]Meu quarto esta uma bagunca.[e]
[s]Voce precisa de alguma ajuda?[e]
[s]Nah, estou bem.[e]

[msg fev0409_10_NG_A_mes01 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 2 1 5122 65535 0]...E assim mesmo?[n][w][e]
[s][f 4 23 1 65535 3 10 0 0][vp 8 2 1 0 65535 0]Voce deve tentar limpa-lo se[n]voce nao gosta disso.[n][w][e]

[msg fev0409_10_NG_B_mes01 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 2 1 5099 65535 0]... Acho que nunca perguntei.[n][w][e]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Enfim, nao ha nada que eu precise de ajuda[n]agora mesmo. Por que voce nao vai limpar seu[n]quarto em vez disso?[n][w][e]

[msg fev0409_10_NG_C_mes01 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 2 1 5099 65535 0]Hmph. Se voce quiser conversar, seria melhor[n]fora de encontrar outra pessoa.[n][w][e]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Se voce esta realmente desesperado por algo para[n]Faca, talvez voce deva limpar seu quarto.[n][w][e]

[msg fev0409_10_NG_mes02 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Desculpe, nao tenho tempo de sobra[n]voce agora. Apenas suba as escadas e[n]Mantenha para si mesmo.[n][w][e]

