[sel YESNO_SEL top]
[s]Sim[e]
[s]Nao[e]

[msg MSG_TEST_800]
[s]Para 2F Wing East[n][w][e]

[msg MSG_TEST_801]
[s]Para o 1 andar[n](Stairs in Front of Cafeteria)[n][w][e]

[msg MSG_TEST_802]
[s]Para o 1 andar[n](Front of Courtyard)[n][w][e]

[msg MSG_TEST_803]
[s]Para o 3 andar[n](Front of Courtyard)[n][w][e]

[msg MSG_TEST_804]
[s]Para o 3 andar[n](Front of Cafeteria)[n][w][e]

[msg MSG_TEST_805]
[s]Entrada oeste do escritorio do corpo docente[n][w][e]

[msg MSG_TEST_806]
[s]Entrada do corpo docente Entrada leste[n][w][e]

[msg MSG_TEST_807]
[s]Gabinete do diretor[n][w][e]

[msg MSG_TEST_808]
[s]Entrada sul em sala de aula[n][w][e]

[msg MSG_TEST_809]
[s]Entrada norte da sala de aula[n][w][e]

