[sel YESNO_SEL top]
[s]Sim.[e]
[s]Nao.[e]

[msg MSG_000_0_0]
[s]Ficticio[n][w][e]

[msg MSG_Fst_Renraku_MORU_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Ei, voce precisa pegar a linha Inogami,[n]certo?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Nesse caso, e melhor voce tomar[n]a entrada de conexao ao lado do[n]loja de conveniencia.[n][w][e]

[msg MSG_Fst_Renraku_MORU_02 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Eu nao faco todas aquelas caminhadas por nada,[n]voce sabe.[n][w][e]

