[msg MSG_GREET_RESERVE_1]
[s][vp 1 0 0 0 0 0]Cara... eu quero ir pra casa...[n][f 1 3 65535][w][e]

[msg MSG_GREET_RESERVE_2]
[s][vp 1 0 0 0 0 0]A escola é uma merda...[n][f 1 3 65535][w][e]

[msg MSG_GREET_RESERVE_3]
[s][vp 1 0 0 0 0 0]Estou sempre muito cansado...[n][f 1 3 65535][w][e]

[msg MSG_GREET_RESERVE_4]
[s][vp 1 0 0 0 0 0]Não quero ir trabalhar...[n][f 1 3 65535][w][e]

[msg MSG_GREET_RESERVE_5]
[s][vp 1 0 0 0 0 0]Mas vamos fazer uma pausa?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0530_1]
[s][vp 1 0 0 0 0 0]Como é que todas as crianças estão[n]em agasalhos?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0530_2]
[s][vp 1 0 0 0 0 0]Alunos em uma escola[n]estão limpando.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0530_3]
[s][vp 1 0 0 0 0 0]Eu gostaria que eles viessem e me limpassem[n]também...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0530_4]
[s][vp 1 0 0 0 0 0]Nada mal para um grupo de alunos do ensino médio.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0530_5]
[s][vp 1 0 0 0 0 0]Essas pobres pessoas provavelmente[n]foram forçadas a se oferecer[n]como voluntárias...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0606_1]
[s][vp 1 0 0 0 0 0]Você viu as notícias?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0606_2]
[s][vp 1 0 0 0 0 0]Sobre a carta de aviso dos Phantom Thieves,[n]certo?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0606_3]
[s][vp 1 0 0 0 0 0]A forma como foi escrito[n]parecia completamente regular...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0606_4]
[s][vp 1 0 0 0 0 0]Eles realmente despertaram[n]o coração das pessoas?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0606_5]
[s][vp 1 0 0 0 0 0]Não acredito que[n]Phantom Thieves[n]existem mesmo...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0717_1]
[s][vp 1 0 0 0 0 0]Quem você acha que eles vão atacar[n]na próxima vez?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0717_2]
[s][vp 1 0 0 0 0 0]Eles só caçam bandidos,[n]certo? Não temos nada[n]com que nos preocupar...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0717_3]
[s][vp 1 0 0 0 0 0]Aparentemente, se você postar[n]um pedido no fórum deles,[n]eles farão o que você pedir![n][f 1 3 65535][w][e]

[msg MSG_GREET_0717_4]
[s][vp 1 0 0 0 0 0]Se eles lidam com os bandidos,[n]eu estou com eles! Vamos![n][f 1 3 65535][w][e]

[msg MSG_GREET_0717_5]
[s][vp 1 0 0 0 0 0]Para que precisamos da[n]polícia neste momento?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0918_1]
[s][vp 1 0 0 0 0 0]O que eles estão fazendo?[n]Tire-o![n][f 1 3 65535][w][e]

[msg MSG_GREET_0918_2]
[s][vp 1 0 0 0 0 0]Os Phantom Thieves não vão[n]nos decepcionar, vão?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0918_3]
[s][vp 1 0 0 0 0 0]Certamente não![n][f 1 3 65535][w][e]

[msg MSG_GREET_0918_4]
[s][vp 1 0 0 0 0 0]Eu quero ver a[n]culpa destruí-la...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0918_5]
[s][vp 1 0 0 0 0 0]Quem sabe o que eles vão nos dizer[n]desta vez.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1023_1]
[s][vp 1 0 0 0 0 0]Mas o que[n]aquele detetive pensa que está fazendo?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1023_2]
[s][vp 1 0 0 0 0 0]Ele só quer se tornar[n]mais famoso...[n]Ele quer se exibir.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1023_3]
[s][vp 1 0 0 0 0 0]Prenda os Phantom Thieves[n]e acabe com tudo...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1023_4]
[s][vp 1 0 0 0 0 0]Eu não sei... mas parece que[n]ele sabe algo sobre isso.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1023_5]
[s][vp 1 0 0 0 0 0]Aposto que ele descobriu[n]algo comprometedor![n][f 1 3 65535][w][e]

[msg MSG_GREET_0103_1]
[s][vp 1 0 0 0 0 0]Todo ano saio de férias...[n]Com minha família, claro![n][f 1 3 65535][w][e]

[msg MSG_GREET_0103_2]
[s][vp 1 0 0 0 0 0]Você está voltando para casa?!?[n]Então você vai realizar[n]todos os seus sonhos...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0103_3]
[s][vp 1 0 0 0 0 0]Escola? É divertido.[n]Eu também tenho amigos.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0103_4]
[s][vp 1 0 0 0 0 0]Mas aquela loja não estava fechada?[n]Erm... Acho que não.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0103_5]
[s][vp 1 0 0 0 0 0]As vendas não são as melhores,[n]mas estou bem com isso.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0127_1]
[s][vp 1 0 0 0 0 0]Estarei aqui até de manhã.[n]Só não posso[n]abandonar meus colegas.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0127_2]
[s][vp 1 0 0 0 0 0]Você trouxe um rascunho?[n]Do que você está falando?[n]Mas então... quem diabos é você?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0127_3]
[s][vp 1 0 0 0 0 0]Estou tão feliz que meu marido[n]sempre prepara o jantar para mim...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0127_4]
[s][vp 1 0 0 0 0 0]É tão tranquilo...[n]quero viver aqui para sempre...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0127_5]
[s][vp 1 0 0 0 0 0]Você tem ideia de como seria terrível[n]desistir de nossa vida cotidiana[n]como a conhecemos?[n][f 1 3 65535][w][e]

