[msg MSG_GREET_RESERVE_1]
[s][vp 1 0 0 0 0 0]Cara... eu quero ir pra casa...[n][f 1 3 65535][w][e]

[msg MSG_GREET_RESERVE_2]
[s][vp 1 0 0 0 0 0]Eu não quero ir para a escola...[n]É uma bola...[n][f 1 3 65535][w][e]

[msg MSG_GREET_RESERVE_3]
[s][vp 1 0 0 0 0 0]Estou sempre muito cansado...[n][f 1 3 65535][w][e]

[msg MSG_GREET_RESERVE_4]
[s][vp 1 0 0 0 0 0]Não quero ir trabalhar...[n][f 1 3 65535][w][e]

[msg MSG_GREET_RESERVE_5]
[s][vp 1 0 0 0 0 0]Mas nunca fazemos uma pausa?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0424_1]
[s][vp 1 0 0 0 0 0]Estou feliz por terem consertado o[n]metrô tão rapidamente.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0424_2]
[s][vp 1 0 0 0 0 0]Este ano houve[n]incidentes estranhos um após[n]o outro...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0424_3]
[s][vp 1 0 0 0 0 0]Nosso país está[n]desmoronando![n][f 1 3 65535][w][e]

[msg MSG_GREET_0424_4]
[s][vp 1 0 0 0 0 0]Mas não existem[n]políticos honestos?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0424_5]
[s][vp 1 0 0 0 0 0]Como posso confiar[n]em um país como este?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0429_1]
[s][vp 1 0 0 0 0 0]Trens parados? Poderia[n]foi outro[n]desses ataques?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0429_2]
[s][vp 1 0 0 0 0 0]Outro ministro pediu demissão?[n]O que está acontecendo?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0429_3]
[s][vp 1 0 0 0 0 0]Quão estúpido você tem que ser[n]para trair alguém?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0429_4]
[s][vp 1 0 0 0 0 0]Eles devem estar loucos...[n]acenar com uma adaga como[n]aquela do metrô...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0429_5]
[s][vp 1 0 0 0 0 0]Tá cheio de maluquice por aí![n]Cadê o povo[n]bom?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0515_1]
[s][vp 1 0 0 0 0 0]Para onde vai esta linha?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0515_2]
[s][vp 1 0 0 0 0 0]Oh, a exposição deve[n]abrir hoje.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0515_3]
[s][vp 1 0 0 0 0 0]Quantas pessoas... Quer voltar[n]outra vez?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0515_4]
[s][vp 1 0 0 0 0 0]Eu gosto muito, mas custa[n]muito caro... Talvez eu devesse[n]pedir um empréstimo.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0515_5]
[s][vp 1 0 0 0 0 0]Eu quero vê-la![n]Vamos juntos![n][f 1 3 65535][w][e]

[msg MSG_GREET_0521_1]
[s][vp 1 0 0 0 0 0]Houve tantos[n]incidentes estranhos recentemente![n][f 1 3 65535][w][e]

[msg MSG_GREET_0521_2]
[s][vp 1 0 0 0 0 0]Oh, eu ouvi sobre esta[n]exposição! Não havia[n]publicidade por aí?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0521_3]
[s][vp 1 0 0 0 0 0]Ei, onde você está indo, mocinha?[n]Vamos bater um papo?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0521_4]
[s][vp 1 0 0 0 0 0]Parece ser popular[n]até no exterior![n]É tão famoso![n][f 1 3 65535][w][e]

[msg MSG_GREET_0521_5]
[s][vp 1 0 0 0 0 0]Conheço um trabalho de meio período muito bom.[n]Você está interessado?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0610_1]
[s][vp 1 0 0 0 0 0]Você viu a transmissão?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0610_2]
[s][vp 1 0 0 0 0 0]Então os Phantom Thieves[n]eram os bandidos?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0610_3]
[s][vp 1 0 0 0 0 0]Agora que você[n]me faz pensar sobre isso...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0610_4]
[s][vp 1 0 0 0 0 0]Sempre tive[n]este sentimento.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0610_5]
[s][vp 1 0 0 0 0 0]É como[n]lavagem cerebral, não é? Algo[n]egoísta.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0710_1]
[s][vp 1 0 0 0 0 0]Os Phantom Thieves[n]despertaram[n]o coração dela, certo?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0710_2]
[s][vp 1 0 0 0 0 0]Sério!?! Os Phantom Thieves[n]são incríveis![n][f 1 3 65535][w][e]

[msg MSG_GREET_0710_3]
[s][vp 1 0 0 0 0 0]Não é legal como[n]eles acordam[n]o coração das pessoas?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0710_4]
[s][vp 1 0 0 0 0 0]Como eles os fazem[n]arrepender por suas ações?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0710_5]
[s][vp 1 0 0 0 0 0]É interessante...[n]Quem serão eles?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0728_1]
[s][vp 1 0 0 0 0 0]Ainda não[n]os Phantom Thieves fizeram nada?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0728_2]
[s][vp 1 0 0 0 0 0]Eu não entendo... Eles[n]quer apenas ignorá-los?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0728_3]
[s][vp 1 0 0 0 0 0]Com certeza eles[n]já estão pensando nisso![n][f 1 3 65535][w][e]

[msg MSG_GREET_0728_4]
[s][vp 1 0 0 0 0 0]Haverá problemas se[n]eles não fizerem algo...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0728_5]
[s][vp 1 0 0 0 0 0]Eu gostaria que eles cuidassem disso[n]uma vez...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0718_1]
[s][vp 1 0 0 0 0 0]Hackers desafiaram[n]os Phantom Thieves?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0718_2]
[s][vp 1 0 0 0 0 0]As coisas estão ficando interessantes![n][f 1 3 65535][w][e]

[msg MSG_GREET_0718_3]
[s][vp 1 0 0 0 0 0]Mas por que? Os[n]Phantom Thieves os atacaram?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0718_4]
[s][vp 1 0 0 0 0 0]Medjed é assustador...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0718_5]
[s][vp 1 0 0 0 0 0]Mal posso esperar para[n]the Phantom Thieves para[n]lidar com isso![n][f 1 3 65535][w][e]

[msg MSG_GREET_0807_1]
[s][vp 1 0 0 0 0 0]Os Phantom Thieves não disseram nada?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0807_2]
[s][vp 1 0 0 0 0 0]Ouvi dizer que eles estavam[n]comprando[n]material suspeito. Eles estão ferrados.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0807_3]
[s][vp 1 0 0 0 0 0]Outro vazamento?[n]O que eles estão fazendo?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0807_4]
[s][vp 1 0 0 0 0 0]Foram os[n]Phantom Thieves?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0807_5]
[s][vp 1 0 0 0 0 0]Foi muito chato[n]mas, dessa vez...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0812_1]
[s][vp 1 0 0 0 0 0]Faltam apenas dez dias[n]para Medjed expirar...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0812_2]
[s][vp 1 0 0 0 0 0]O que os[n]ladrões fantasmas estão fazendo?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0812_3]
[s][vp 1 0 0 0 0 0]Eles vão deixar[n]Medjed fazer o que quiser?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0812_4]
[s][vp 1 0 0 0 0 0]O que Medjed está tentando[n]fazer?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0812_5]
[s][vp 1 0 0 0 0 0]Isso nos afetará?[n]Não temos nada a ver com isso...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0821_1]
[s][vp 1 0 0 0 0 0]Hoje é o dia do ataque de[n]Medjed, certo?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0821_2]
[s][vp 1 0 0 0 0 0]Receio que os Phantom Thieves[n]não possam fazer nada...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0821_3]
[s][vp 1 0 0 0 0 0]Medjed deve ter sido demais até para eles.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0821_4]
[s][vp 1 0 0 0 0 0]As ações estão[n]caindo novamente...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0821_5]
[s][vp 1 0 0 0 0 0]Talvez o verdadeiro objetivo de Medjed[n]foi...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0822_1]
[s][vp 1 0 0 0 0 0]O que é isso?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0822_2]
[s][vp 1 0 0 0 0 0]Você está falando sério?!?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0822_3]
[s][vp 1 0 0 0 0 0]Impossível... não acredito...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0822_4]
[s][vp 1 0 0 0 0 0]Não é brincadeira, é?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0822_5]
[s][vp 1 0 0 0 0 0]Perderam? Como é[n]possível...?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0824_1]
[s][vp 1 0 0 0 0 0]Os Phantom Thieves[n]geraram esses escândalos?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0824_2]
[s][vp 1 0 0 0 0 0]Não, acho que cartas de desafio não foram[n]usadas...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0824_3]
[s][vp 1 0 0 0 0 0]Sabe, tipo... eles despertam[n]o coração das pessoas agindo nas sombras![n][f 1 3 65535][w][e]

[msg MSG_GREET_0824_4]
[s][vp 1 0 0 0 0 0]Estou errado ou houve[n]muito mais postagens de[n]estrangeiros recentemente?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0824_5]
[s][vp 1 0 0 0 0 0]Talvez eu também deva deixar[n]me um pedido no fórum...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0827_1]
[s][vp 1 0 0 0 0 0]Eles continuam aumentando os impostos![n][f 1 3 65535][w][e]

[msg MSG_GREET_0827_2]
[s][vp 1 0 0 0 0 0]Pare de oprimir os fracos![n][f 1 3 65535][w][e]

[msg MSG_GREET_0827_3]
[s][vp 1 0 0 0 0 0]O que é?[n]Um festival?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0827_4]
[s][vp 1 0 0 0 0 0]É um protesto,[n]parece óbvio...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0827_5]
[s][vp 1 0 0 0 0 0]Não seria mais rápido pedir[n]para despertar seu coração?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0830_1]
[s][vp 1 0 0 0 0 0]Todo mundo está falando sobre os[n]Phantom Thieves.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0830_2]
[s][vp 1 0 0 0 0 0]Você não pode se tornar um dos[n]Phantom Thieves, você sabe disso, certo?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0830_3]
[s][vp 1 0 0 0 0 0]Não! Eu quero me juntar[n]aos Phantom Thieves![n][f 1 3 65535][w][e]

[msg MSG_GREET_0830_4]
[s][vp 1 0 0 0 0 0]Quem sabe o que[n]eles farão agora.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0830_5]
[s][vp 1 0 0 0 0 0]É difícil não se emocionar![n]Mal posso esperar![n][f 1 3 65535][w][e]

[msg MSG_GREET_0901_1]
[s][vp 1 0 0 0 0 0]Você já viu o fórum? Eles[n]adicionaram um novo recurso![n][f 1 3 65535][w][e]

[msg MSG_GREET_0901_2]
[s][vp 1 0 0 0 0 0]Alguma classificação?[n]Interessante![n][f 1 3 65535][w][e]

[msg MSG_GREET_0901_3]
[s][vp 1 0 0 0 0 0]Você só vota?[n]Não é inútil?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0901_4]
[s][vp 1 0 0 0 0 0]Nunca se sabe. Eles também podem[n]ficar de olho neles.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0901_5]
[s][vp 1 0 0 0 0 0]Aposto que os Phantom Thieves[n]vão despertar seus corações![n][f 1 3 65535][w][e]

[msg MSG_GREET_0912_1]
[s][vp 1 0 0 0 0 0]O quê?[n]Legal![n][f 1 3 65535][w][e]

[msg MSG_GREET_0912_2]
[s][vp 1 0 0 0 0 0]Um selo Phantom[n]Thieves. Isso não é legal?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0912_3]
[s][vp 1 0 0 0 0 0]Quem você acha que serão[n]os próximos alvo dos[n]Phantom Thieves?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0912_4]
[s][vp 1 0 0 0 0 0]Quem sabe... Mal posso[n]esperar para descobrir![n][f 1 3 65535][w][e]

[msg MSG_GREET_0912_5]
[s][vp 1 0 0 0 0 0]Não importa...[n]Apenas se apresse.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0916_1]
[s][vp 1 0 0 0 0 0]É tudo culpa do CEO da[n]Okumura Foods, não é?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0916_2]
[s][vp 1 0 0 0 0 0]Por que os Phantom Thieves[n]deixariam ele agir?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0916_3]
[s][vp 1 0 0 0 0 0]Deixe-os ignorar os gráficos![n]Apresse-se e elimine-o![n][f 1 3 65535][w][e]

[msg MSG_GREET_0916_4]
[s][vp 1 0 0 0 0 0]Que decepção. Que tipo[n]de heróis eles são?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0916_5]
[s][vp 1 0 0 0 0 0]Que se apressem e[n]envie uma carta de aviso.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0921_1]
[s][vp 1 0 0 0 0 0]Presidente Okumura é o[n]alvo mais votado[n]do Phan-Site![n][f 1 3 65535][w][e]

[msg MSG_GREET_0921_2]
[s][vp 1 0 0 0 0 0]Quem sabe quando enviarão[n]a carta de aviso![n][f 1 3 65535][w][e]

[msg MSG_GREET_0921_3]
[s][vp 1 0 0 0 0 0]Do que ele é culpado?[n]Abuso de poder?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0921_4]
[s][vp 1 0 0 0 0 0]Eu gostaria de poder me aproximar[n]dos Phantom Thieves![n][f 1 3 65535][w][e]

[msg MSG_GREET_0921_5]
[s][vp 1 0 0 0 0 0]Talvez eu compre alguns[n]Phantom Thieves,[n]no meu caminho para casa...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1007_1]
[s][vp 1 0 0 0 0 0]Se os Phantom Thieves estão[n]cuidando disso,[n]não deve ser um problema.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1007_2]
[s][vp 1 0 0 0 0 0]Sério, quem sou eu?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1007_3]
[s][vp 1 0 0 0 0 0]Se você os conhecesse, seria[n]amor à primeira vista![n][f 1 3 65535][w][e]

[msg MSG_GREET_1007_4]
[s][vp 1 0 0 0 0 0]O que eles estão esperando?[n]Deixe-os fazer isso![n][f 1 3 65535][w][e]

[msg MSG_GREET_1007_5]
[s][vp 1 0 0 0 0 0]Os heróis têm o dever[n]de salvar os mais fracos.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1011_1]
[s][vp 1 0 0 0 0 0]Você ouviu as notícias?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1011_2]
[s][vp 1 0 0 0 0 0]Visto? Desmaiou durante[n]a entrevista...[n]Sem brincadeira![n][f 1 3 65535][w][e]

[msg MSG_GREET_1011_3]
[s][vp 1 0 0 0 0 0]Que horror...[n]Eles poderiam ter pelo menos colocado[n]um aviso antes do vídeo.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1011_4]
[s][vp 1 0 0 0 0 0]Eles disseram que o presidente[n]Okumura está morto![n][f 1 3 65535][w][e]

[msg MSG_GREET_1011_5]
[s][vp 1 0 0 0 0 0]Sério!?! Você está certo![n]Acabei de ver[n]isso sendo falado na TV![n][f 1 3 65535][w][e]

[msg MSG_GREET_1015_1]
[s][vp 1 0 0 0 0 0]Então eles[n]apenas zombaram de nós?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1015_2]
[s][vp 1 0 0 0 0 0]Acho que Akechi estava[n]certo, afinal...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1015_3]
[s][vp 1 0 0 0 0 0]Não, eu ainda acredito[n]em Phantom Thieves![n][f 1 3 65535][w][e]

[msg MSG_GREET_1015_4]
[s][vp 1 0 0 0 0 0]Eles são assassinos, então?[n]Que sejam presos, então![n][f 1 3 65535][w][e]

[msg MSG_GREET_1015_5]
[s][vp 1 0 0 0 0 0]Quanto tempo mais a polícia vai[n]deixá-los agir?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1111_1]
[s][vp 1 0 0 0 0 0]Por que eles ainda não estão presos? O que[n]o governo está fazendo?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1111_2]
[s][vp 1 0 0 0 0 0]Deixe-os prendê-los agora![n][f 1 3 65535][w][e]

[msg MSG_GREET_1111_3]
[s][vp 1 0 0 0 0 0]Faz sentido dissolver o governo[n]em um momento como[n]este?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1111_4]
[s][vp 1 0 0 0 0 0]Eles não deveriam se preocupar[n]com a segurança dos cidadãos,[n]primeira coisa?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1111_5]
[s][vp 1 0 0 0 0 0]Como nos[n]sentimos protegidos?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1116_1]
[s][vp 1 0 0 0 0 0]Mas eles estão procurando pelos ladrões fantasmas[n]ou o quê?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1116_2]
[s][vp 1 0 0 0 0 0]Você sabe o que há de novo...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1116_3]
[s][vp 1 0 0 0 0 0]Não estou interessado em política.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1116_4]
[s][vp 1 0 0 0 0 0]Prenda os Phantom Thieves[n]e acabe logo com isso![n][f 1 3 65535][w][e]

[msg MSG_GREET_1116_5]
[s][vp 1 0 0 0 0 0]Não podemos mais confiar[n]nos políticos incompetentes[n]que nos encontramos![n][f 1 3 65535][w][e]

[msg MSG_GREET_1121_1]
[s][vp 1 0 0 0 0 0]Ouvi dizer que prenderam[n]um dos Phantom Thieves![n]Impossível![n][f 1 3 65535][w][e]

[msg MSG_GREET_1121_2]
[s][vp 1 0 0 0 0 0]Eu não pensei que ele iria se matar...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1121_3]
[s][vp 1 0 0 0 0 0]Ele é um assassino. Ele[n]merece morrer.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1121_4]
[s][vp 1 0 0 0 0 0]Finalmente podemos respirar[n]um suspiro de alívio.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1121_5]
[s][vp 1 0 0 0 0 0]Ele se matou, hein?[n]Acho que[n]nunca saberemos realmente o porquê.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1122_1]
[s][vp 1 0 0 0 0 0]Aparentemente, Akechi[n]prendeu o líder[n]dos Phantom Thieves![n][f 1 3 65535][w][e]

[msg MSG_GREET_1122_2]
[s][vp 1 0 0 0 0 0]Ele é um herói.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1122_3]
[s][vp 1 0 0 0 0 0]Estou feliz que Akechi[n]está de volta![n][f 1 3 65535][w][e]

[msg MSG_GREET_1122_4]
[s][vp 1 0 0 0 0 0]Espero que eles levem[n]o resto da tripulação também![n][f 1 3 65535][w][e]

[msg MSG_GREET_1122_5]
[s][vp 1 0 0 0 0 0]É muito bom![n][f 1 3 65535][w][e]

[msg MSG_GREET_1125_1]
[s][vp 1 0 0 0 0 0]A[n]campanha eleitoral já começou.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1125_2]
[s][vp 1 0 0 0 0 0]Aposto que será uma[n]vitória esmagadora para[n]Rep. Shido![n][f 1 3 65535][w][e]

[msg MSG_GREET_1125_3]
[s][vp 1 0 0 0 0 0]Sim... com certeza vou votar[n]nele![n][f 1 3 65535][w][e]

[msg MSG_GREET_1125_4]
[s][vp 1 0 0 0 0 0]Talvez desta vez[n]vou votar também...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1125_5]
[s][vp 1 0 0 0 0 0]Não há muitos políticos[n]como Shido-san![n][f 1 3 65535][w][e]

[msg MSG_GREET_1206_1]
[s][vp 1 0 0 0 0 0]A campanha[n]está esquentando.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1206_2]
[s][vp 1 0 0 0 0 0]Você já decidiu em[n]em quem vai votar?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1206_3]
[s][vp 1 0 0 0 0 0]Vejo que Shido é popular[n]como sempre.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1206_4]
[s][vp 1 0 0 0 0 0]Faz sentido para os outros[n]correr?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1206_5]
[s][vp 1 0 0 0 0 0]Seu índice de aprovação[n]subiu novamente.[n]Até onde ele irá?[n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1206_]
[s][vp 1 0 0 0 0 0]A campanha[n]está esquentando.[n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1206__2]
[s][vp 1 0 0 0 0 0]Eles permitirão que a eleição[n]prossiga normalmente?[n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1206__3]
[s][vp 1 0 0 0 0 0]Eles tem que. Não podemos ficar[n]sem um primeiro-ministro.[n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1206__4]
[s][vp 1 0 0 0 0 0]Estou bem com Masayoshi[n]Shido. E aí não temos[n]muitas alternativas...[n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1206__5]
[s][vp 1 0 0 0 0 0]Sim... Acho que vou votar[n]para Shido-san também.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1216_1]
[s][vp 1 0 0 0 0 0]Este é o meu[n]último pedido! Peço que[n]votem em mim...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1216_2]
[s][vp 1 0 0 0 0 0][n]Carros de campanha eleitoral são chatos...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1216_3]
[s][vp 1 0 0 0 0 0]Peço seu apoio,[n]meus eleitores![n][f 1 3 65535][w][e]

[msg MSG_GREET_1216_4]
[s][vp 1 0 0 0 0 0]Já é[n]dia de eleição...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1216_5]
[s][vp 1 0 0 0 0 0]Eu, Masayoshi Shido, renovarei[n]este país![n][f 1 3 65535][w][e]

[msg MSG_GREET_1216_6]
[s][vp 1 0 0 0 0 0]eu vou votar! Boa[n]sorte, Shido-san![n][f 1 3 65535][w][e]

[msg MSG_GREET_1216_7]
[s][vp 1 0 0 0 0 0]Confio o[n]futuro do país a você![n][f 1 3 65535][w][e]

[msg MSG_GREET_1216_8]
[s][vp 1 0 0 0 0 0]Siga-me e juntos criaremos[n]um futuro melhor![n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1216_]
[s][vp 1 0 0 0 0 0]Atenda ao meu humilde[n]pedido! Vote em[n]Masayoshi Shido![n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1216__2]
[s][vp 1 0 0 0 0 0][n]Carros de campanha eleitoral são chatos...[n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1216__3]
[s][vp 1 0 0 0 0 0]Peço seu apoio,[n]meus eleitores![n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1216__4]
[s][vp 1 0 0 0 0 0]Já é[n]dia de eleição...[n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1216__5]
[s][vp 1 0 0 0 0 0]Vote em[n]Masayoshi Shido![n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1216__6]
[s][vp 1 0 0 0 0 0]Vou votar em você![n]Boa sorte, Shido-san![n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1216__7]
[s][vp 1 0 0 0 0 0]Confio o[n]futuro do país a você![n][f 1 3 65535][w][e]

[msg MSG_GREET_YOKOKUGO_1216__8]
[s][vp 1 0 0 0 0 0]Muito obrigado! Vote[n]para Masayoshi Shido![n][f 1 3 65535][w][e]

[msg MSG_GREET_1218_1]
[s][vp 1 0 0 0 0 0]Você viu os resultados[n]da votação!?![n][f 1 3 65535][w][e]

[msg MSG_GREET_1218_2]
[s][vp 1 0 0 0 0 0]Os votos são claramente[n]a favor de Shido! Eu sabia![n][f 1 3 65535][w][e]

[msg MSG_GREET_1218_3]
[s][vp 1 0 0 0 0 0]Certamente Masayoshi[n]Shido vai ganhar...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1218_4]
[s][vp 1 0 0 0 0 0]Até quando você pode votar?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1218_5]
[s][vp 1 0 0 0 0 0]Shido aponta diretamente[n]para a próxima eleição como[n]líder do partido...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1219_1]
[s][vp 1 0 0 0 0 0]O que aconteceu com Shido-san?[n][f 1 3 65535][w][e]

[msg MSG_GREET_1219_2]
[s][vp 1 0 0 0 0 0]Ele disse algumas coisas estranhas.[n][f 1 3 65535][w][e]

[msg MSG_GREET_1219_3]
[s][vp 1 0 0 0 0 0]O governo estaria em[n]perigo se Shido-san[n]entrar em colapso agora...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1219_4]
[s][vp 1 0 0 0 0 0]Achei que podíamos[n]contar com ele...[n][f 1 3 65535][w][e]

[msg MSG_GREET_1219_5]
[s][vp 1 0 0 0 0 0]O que vai acontecer?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0104_1]
[s][vp 1 0 0 0 0 0]Santuário para o Ano Novo?[n]Mas eu não tenho desejo...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0104_2]
[s][vp 1 0 0 0 0 0]Meu cachorro não é fofo?[n]Com kimono e hakama![n][f 1 3 65535][w][e]

[msg MSG_GREET_0104_3]
[s][vp 1 0 0 0 0 0]Ei, mas seu cachorro...[n]Ah, deixa pra lá...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0104_4]
[s][vp 1 0 0 0 0 0]Dinheiro de ano novo? Vou usá-los[n]para a mamãe, claro![n][f 1 3 65535][w][e]

[msg MSG_GREET_0104_5]
[s][vp 1 0 0 0 0 0]Eu preciso ter meu trabalho verificad[n]pelo meu professor o quanto antes...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0119_1]
[s][vp 1 0 0 0 0 0]Meu pai? Nós nos damos bem.[n]Muitas vezes saímos para beber.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0119_2]
[s][vp 1 0 0 0 0 0]Eles me fazem repetir um ano![n]Mais um ano de ensino médio para mim![n][f 1 3 65535][w][e]

[msg MSG_GREET_0119_3]
[s][vp 1 0 0 0 0 0]Priorize a saúde sobre[n]lucros. Não há necessidade de[n]horas extras.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0119_4]
[s][vp 1 0 0 0 0 0]Eu me peguei pensando no[n]chefe... Isso foi estranho.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0119_5]
[s][vp 1 0 0 0 0 0]Toda a família se reúne para[n]jantar. Não foi sempre assim?[n][f 1 3 65535][w][e]

[msg MSG_GREET_0210_1]
[s][vp 1 0 0 0 0 0]Que incômodo...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0210_2]
[s][vp 1 0 0 0 0 0]Todas essas más notícias[n]estão realmente se acumulando...[n][f 1 3 65535][w][e]

[msg MSG_GREET_0210_3]
[s][vp 1 0 0 0 0 0]Meu chefe é péssimo.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0210_4]
[s][vp 1 0 0 0 0 0][n]Nada de bom acontece.[n][f 1 3 65535][w][e]

[msg MSG_GREET_0210_5]
[s][vp 1 0 0 0 0 0]Estou ficando entediado com karaokê...[n][f 1 3 65535][w][e]

