[msg MSG_000_0_0]
[s][vp 8 0 0 0 65535 0]メッセージダミー[n][f 1 3 65535][w][e]

[msg MSG_SAMPLE_001_0_0 [Locutor]]
[s][vp 8 2 65535 34500 0 0]E agora uma atualização[n]sobre Medjed, que fez[n]uma declaração há algum tempo.[n][f 1 3 65535][w][e]

[msg MSG_SAMPLE_002_0_0 [Locutor]]
[s][vp 8 2 65535 0 0 0]Em seu site, Medjed[n]declarou vitória e[n]anunciou seu próximo crime.[n][f 1 3 65535][w][e]
[s][vp 8 2 65535 0 0 0]Acredita-se que seja mais uma[n]provocação aos Phantom Thieves,[n]cuja reação é aguardada.[n][f 1 3 65535][w][e]

[msg EV880103_TV_NEWS_0716_00 [Locutor]]
[s][vp 8 2 65535 34565 0 0]E agora, o clima.[n][f 1 3 65535][w][e]

[msg EV880103_TV_NEWS_0716_10 [Locutor]]
[s][vp 8 2 65535 0 0 0]Chuvas são esperadas[n]trovoadas para[n]toda a próxima semana.[n][f 1 3 65535][w][e]
[s][vp 8 2 65535 0 0 0]Recomendamos que você preste atenção[n]pois o clima pode sofrer[n]mudanças repentinas.[n][f 1 3 65535][w][e]

[msg EV880103_TV_NEWS_0729_00 [Locutor]]
[s][vp 1 0 0 1 0 0]Ainda sem resposta para Medjed[n]dos Phantom Thieves.[n]Então, o que você acha?[n][f 1 3 65535][w][e]

[msg EV880103_TV_NEWS_0729_10 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 1 0 0 2 0 0]É muito provável que os[n]Phantom Thieves não tenham[n]os meios para combatê-los.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 3 0 0]Afinal, Medjed é um adversário[n]muito diferente dos que[n]enfrentou até agora.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 4 0 0]A melhor escolha que eles podem fazer[n]é revelar suas identidades antes[n]que haja outras vítimas.[n][f 1 3 65535][w][e]

[msg EV880103_TV_NEWS_0729_20 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 1 0 0 5 0 0]Eles atingiram um ponto sensível...[n]Mas vamos vencê-los![n][f 1 3 65535][w][e]

[msg EV880103_TV_NEWS_0830_00 [Locutor]]
[s][vp 1 0 0 6 0 0]E agora, vamos lançar luz sobre[n]um assunto muito comentado:[n]os casos relacionados aos Phantom Thieves![n][f 1 3 65535][w][e]

[msg EV880103_TV_NEWS_0830_10 [Locutor]]
[s][vp 1 0 0 7 0 0]Os Phantom Thieves causaram um rebuliço ao[n]silenciar um conhecido grupo internacional de[n]hackers.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 8 0 0]Sua popularidade ultrapassou[n]as nossas fronteiras, atraindo[n]a atenção da mídia estrangeira.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 9 0 0]Muitos os descrevem como[n]"os heróis das trevas" ou "os ladrões[n]cavalheiros de uma nova era".[n][f 1 3 65535][w][e]

[msg EV880103_TV_NEWS_0830_20 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 10 0 0]Uau... Mas isso é loucura...[n]Então é verdade, o mundo inteiro[n]sabe sobre nós agora![n][f 1 3 65535][w][e]

