[msg MND_COOP_START_000_00]
[s]Quem poderia ser a essa hora...?[n][w][e]

[msg MND_COOP_NEXT_000_00]
[s]Outro telefonema... quem é desta vez?[n][w][e]

[msg MND_COOP_END_000_00]
[s]... eles desligaram.[n][w][e]
[s]Eles podem ser suspeitos.[n][w][e]
[s]Pode ter sido melhor aceitar o convite deles.[n][w][e]
[s]... eu deveria chamá-lo um dia.[n][w][e]

[msg MSG_COOP_MORGANA_000_00 [Morgana]]
[s]Por que você não está atendendo seu telefone?[n][w][e]

[msg MSG_COOP_MAKOTO_000_00 [Makoto]]
[s]Por que você não está atendendo seu telefone?[n][w][e]

[msg MSG_COOP_HARU_000_00 [Haru]]
[s]Por que você não está atendendo seu telefone?[n][w][e]

[msg MSG_COOP_YUSUKE_000_00 [Yusuke]]
[s]Por que você não está atendendo seu telefone?[n][w][e]

[msg MSG_COOP_SOJIRO_000_00 [Sojiro]]
[s]Por que você não está atendendo seu telefone?[n][w][e]

[msg MSG_COOP_ANNE_000_00 [Ann]]
[s]Por que você não está atendendo seu telefone?[n][w][e]

[msg MSG_COOP_RYUJI_000_00 [Ryuji]]
[s]Por que você não está atendendo seu telefone?[n][w][e]

[msg MSG_COOP_AKECHI_000_00 [Akechi]]
[s]Por que você não está atendendo seu telefone?[n][w][e]

[msg MSG_COOP_FUTABA_000_00 [Futaba]]
[s]Por que você não está atendendo seu telefone?[n][w][e]

[msg MSG_COOP_URANAI_000_00 [Chihaya]]
[s][bup 0 113 0 0 0][f 4 10 65535 0 0]Eu li minha fortuna, e disse que eu deveria[n]ligar para você...[n][w][e]
[s]Acabei de obedecer aos cartões... vejo você[n]mais tarde![n][w][e]

[msg MSG_COOP_URANAI_000_01 [Chihaya]]
[s][bup 0 113 0 0 0][f 4 10 65535 0 0]Hum, eu só queria perguntar... você está tão[n]ocupado que não tem tempo para falar comigo?[n][w][e]
[s]Você tem muito o que fazer? Existem segredos[n]que você não pode dizer a outras pessoas [n][w][e]
[s]Deixa para lá! Esqueça o que eu disse![n]Adeus![n][w][e]

[msg MSG_COOP_VELVET_A_000_00 [Justine]]
[s]Por que você não está atendendo seu telefone?[n][w][e]

[msg MSG_COOP_VELVET_B_000_00 [Caroline]]
[s]Por que você não está atendendo seu telefone?[n][w][e]

[msg MSG_COOP_IWAI_000_00 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0]Ei, sou eu. Por que você voltou?[n][w][e]
[s]Assustado? Você queria um pedido[n]personalizado, não é?[n][w][e]
[s]... então verifique sua atitude na porta,[n]Sr. Gun Maniac.[n][w][e]

[msg MSG_COOP_IWAI_000_01 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0]Ei, é você. Você não apareceu novamente.[n][w][e]
[s]Você gosta de armas, certo? Ou isso foi tudo[n]mentira?[n][w][e]
[s]... Não me decepcione.[n][w][e]

[msg MSG_COOP_TAKEMI_000_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0]Ei, apenas verificando, você precisa de[n]remédios para ajudar a estudar para seus[n]exames, certo?[n][w][e]
[s]Você não vem aos meus ensaios clínicos. Foi[n]tudo conversa?[n][w][e]
[s]Não perca meu tempo.[n][w][e]

[msg MSG_COOP_TAKEMI_000_01 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0]Você não queria mais participar dessas[n]clínicas?[n][w][e]
[s]Você estava mentindo quando disse que era[n]para exames da faculdade?[n][w][e]
[s]Se você ainda quiser fazer isso, apresse-se.[n][w][e]

[msg MSG_COOP_KAWAKAMI_000_00 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0]Hum... bem...[n][w][e]
[s]Você não precisa abandonar a aula de novo?[n][w][e]
[s]Estou apertado com dinheiro. Por favor?[n][w][e]

[msg MSG_COOP_KAWAKAMI_000_01 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0]Você não esqueceu sua promessa de me pedir[n]do Serviço de Maid, se eu deixar você pular[n]aula, não é?[n][w][e]
[s]O que você está fazendo quando você abandona[n]a aula, afinal?[n][w][e]
[s]Suspeito...[n][w][e]
[s]Oh! Peço desculpas por chamá-lo de tarde.[n]Boa noite.[n][w][e]

[msg MSG_COOP_OOYA_000_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0]...Sou eu.[n][w][e]
[s]O que está errado? Você não tem mais[n]informações para mim?[n][w][e]
[s]... ou talvez você nem seja fã dos ladrões[n]fantasmas?[n][w][e]
[s]... Se você está dizendo a verdade, se[n]apresse e venha me ver já.[n][w][e]

[msg MSG_COOP_OOYA_000_01 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0]...Ei, vamos lá. O que há com essa reação?[n][w][e]
[s]Estou tendo dúvidas de que você é realmente[n]um fã do Phantom Thieves...[n][w][e]
[s]...* suspiro* Eu não me importo mais. Até a[n]próxima.[n][w][e]

[msg MSG_COOP_ODA_000_00 [Shinya]]
[s][bup 0 110 0 0 0][f 4 10 65535 0 0]Ei, por que você não está vindo?[n]Eu queria falar sobre os ladrões Phantom com[n]você...[n][w][e]
[s]Ei, seria que você está mentindo sobre[n]conhecer os ladrões fantasmas?[n][w][e]
[s]...Qualquer que seja. Vê você.[n][w][e]

[msg MSG_COOP_ODA_000_01 [Shinya]]
[s][bup 0 110 0 0 0][f 4 10 65535 0 0]Ei o que está acontecendo? Você disse que me[n]contou sobre os ladrões Phantom...[n][w][e]
[s]Então você realmente estava mentindo sobre[n]conhecer os ladrões Phantom, afinal!?[n][w][e]
[s]Eu não me importo mais. Eu vou.[n][w][e]

[msg MSG_COOP_HIFUMI_000_00 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0]Se eu posso ser tão rude, mas devo dizer...[n]Você nunca melhorará com essas tentativas[n]sem coração.[n][w][e]
[s]Estar comprometido. Ou seja, se você[n]realmente gosta de shogi.[n][w][e]

[msg MSG_COOP_HIFUMI_000_01 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0]Talvez eu estivesse errado sobre sua paixão[n]por shogi...[n][w][e]
[s]Eu ficaria incrivelmente desapontado se seu[n]desejo de se tornar meu aprendiz fosse[n]apenas uma mentira.[n][w][e]

[msg MSG_COOP_MISHIMA_000_00 [Mishima]]
[s]Por que você não está atendendo seu telefone?[n][w][e]

[msg MSG_COOP_YOSHIDA_000_00 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0]Ei, isso é Yoshida. Em que você tem gasto[n]seu tempo ultimamente?[n][w][e]
[s]É importante fazer tempo para seus estudos-[n]mas você perdeu sua paixão pela legislatura?[n][w][e]
[s]... e eu tinha grandes esperanças para você.[n][w][e]

[msg MSG_COOP_YOSHIDA_000_01 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0]Olá, é Yoshida. Você perdeu o interesse pela[n]política?[n][w][e]
[s]Talvez você estivesse mentindo sobre suas[n]aspirações de se tornar um político.[n][w][e]
[s]Estou muito decepcionado com você...[n][w][e]

[msg MSG_COOP_SAE_000_00 [Sae]]
[s]Por que você não está atendendo seu telefone?[n][w][e]

[msg MSG_COOP_WORLD_000_00 [World]]
[s]Por que você não está atendendo seu telefone?[n][w][e]

