C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E000_200.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E000_201.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E000_202.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E000_203.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E000_204.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E000_205.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E000_206.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E000_207.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E000_208.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E060_010.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E060_020.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E060_030.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E060_040.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E080_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E080_003.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E080_040.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E080_050.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E090_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E092_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E092_051.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E093_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E093_151.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E094_001.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E094_051.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E096_101.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E096_151.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E099_000.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E099_010.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E099_020.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E099_030.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E099_040.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E099_050.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E099_060.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
C:/Users/gusta/OneDrive/Documentos/ps/ScriptGUI_v2.2_Dark/AtlusScriptCompiler.exe E099_070.BMD.msg -Compile -OutFormat V1BE -Library P5R -Encoding P5R_EFIGS 
pause