[msg MSG_000_0_0 [詩(ラヴェンツァ)]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Seu fracasso é manifesto, sua vontade espalhada[n]aos quatro ventos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Seu nobre estandarte agora está[n]solo distorcido, sua crença[n]desapareceu como um sonho acordado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]E assim o Herói encontra seu fim; sua rebelião é[n]reprimida, seu chamado é silencioso...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]É realmente assim? Eles finalmente[n]domaram seu espírito rebelde?[n][f 1 3 65535][w][e]

[msg SYS_002_0_0]
[s][vp 8 0 0 0 65535 0]O que você quer fazer?[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]De volta a uma semana atrás[e]
[s]Voltar para a tela inicial[e]

[sel SEL_004_0_0 top]
[s]Reinicie a batalha[e]
[s]Volte para a última sala segura[e]
[s]Reinicie a infiltração[e]
[s]Voltar para a tela inicial[e]

[sel SEL_005_0_0 top]
[s]Reinicie a batalha[e]
[s]Volte para a última sala segura[e]
[s]De volta a uma semana atrás[e]
[s]Voltar para a tela inicial[e]

[sel SEL_006_0_0 top]
[s]Reinicie a batalha[e]
[s]Volte para a última sala segura[e]
[s]Voltar para a tela inicial[e]

