[sel YESNO_SEL top]
[s]Sim[e]
[s]Não[e]

[msg MSG_TEST_800]
[s]Na Asa Oeste 1P[n][w][e]

[msg MSG_TEST_801]
[s]Na Asa Leste 1P[n][w][e]

[msg MSG_TEST_802]
[s]Entrada do ginásio 1P[n][w][e]

[msg MND_HERO]
[s]Ryuji ainda não chegou...[n][w][e]
[s]Vou esperar aqui um pouco,[n]relaxar um pouco...[n][w][e]

[msg MSG_029_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Porra, eu não entendi![n]Você?[n][w][e]

[sel SEL_030_0_0 top]
[s]Nada.[e]
[s]Quem pode dizer?[e]
[s]eu realmente não quero...[e]

[msg MSG_031_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Um dos meninos abusados[n]era um atleta do terceiro ano.[n][w][e]
[s][vp 1 0 0 0 0 0]Não está aqui,[n]vamos verificar o primeiro[n]andar das salas de aula![n][w][e]
[s][vp 1 0 0 0 0 0]Me irrita que ele esteja ferido,[n]mas isso torna[n]mais fácil encontrá-lo![n][w][e]

[msg MSG_032_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Você também não teve sorte,[n]então...[n][w][e]
[s][vp 1 0 0 0 0 0]Acredito que um terceiro ano foi derrotado junto[n]com o restante do time de vôlei.[n][w][e]
[s][vp 1 0 0 0 0 0]Não está aqui,[n]vamos verificar o primeiro[n]andar das salas de aula![n][w][e]
[s][vp 1 0 0 0 0 0]Me irrita que ele esteja ferido,[n]mas isso torna[n]mais fácil encontrá-lo![n][w][e]

[msg MSG_033_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Vamos, me dê uma mão![n]Eu vou retribuir oferecendo a você um[n]gyudon, ok?[n][w][e]
[s][vp 1 0 0 0 0 0]Acredito que um terceiro ano foi derrotado junto[n]com o restante do time de vôlei.[n][w][e]
[s][vp 1 0 0 0 0 0]Não está aqui,[n]vamos verificar o primeiro[n]andar das salas de aula![n][w][e]
[s][vp 1 0 0 0 0 0]Me irrita que ele esteja ferido,[n]mas isso torna[n]mais fácil encontrá-lo![n][w][e]

