[sel YESNO_SEL top]
[s]Sim[e]
[s]Não[e]

[msg MSG_BLDGA2F_BLDGB2F_00 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Ei, eu tenho que passar![n][w][e]

[msg MSG_BLDGA2F_BLDGB2F_01 [Studentessa]]
[s][vp 8 0 1 14 65535 0]Hã? Não empurre![n][w][e]

[msg MSG_BLDGA2F_BLDGB2F_02 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]Permissão, permissão![n][w][e]

[msg MND_BLDGA2F_TEACHER_NG]
[s][vp 1 0 0 0 0 0]Os professores parecem ansiosos,[n]mas nenhum deles vai[n]para o pátio...[n][w][e]
[s][vp 1 0 0 0 0 0]Melhor ir pessoalmente.[n][w][e]

[msg MND_BLDGA2F_KOUCHO_NG]
[s][vp 1 0 0 0 0 0]Não há ninguém na sala do diretor...[n][w][e]

[msg MND_BLDGA2F_MYCLASS_NG]
[s][vp 1 0 0 0 0 0]Agora não posso voltar para a aula. Eu tenho que[n]chegar ao pátio...[n][w][e]

