[msg TalkMsg_01 [Shadow Fukurai]]
[s]Voce pode me ouvir?[n][w][e]

[msg TalkMsg_02 [Shadow Fukurai]]
[s]Ei, eu pedi para voce me ouvir![n][w][e]

[msg TalkMsg_03 [Shadow Fukurai]]
[s]Por que eu falaria com voce sobre isso!?[n][w][e]

[msg TalkMsg_04 [Shadow Fukurai]]
[s]Huh? Voce nao quer falar sobre[n]algo um pouco mais benefico[n]para voce?[n][w][e]

[msg TalkMsg_05 [Shadow Fukurai]]
[s]O Tesouro...?[n][w][e]

[msg TalkMsg_06 [Shadow Fukurai]]
[s]E tudo a mesma coisa![n][w][e]

[msg TalkMsg_07 [Shadow Fukurai]]
[s]Por favor, espere! Por favor![n][w][e]

[msg TalkMsg_08 [Shadow Fukurai]]
[s]Ei, voce nao vai dizer algo?[n][w][e]

[sel TalkSel_01 top]
[s]Vamos falar sobre Chihaya.[e]
[s]Vamos falar sobre dinheiro.[e]
[s]Vamos falar sobre o tesouro.[e]

[sel TalkSel_02 top]
[s]Conte-me sobre Chihaya...[e]
[s]Conte-me sobre o dinheiro...[e]
[s]Conte-me sobre o tesouro...[e]

[sel TalkSel_03 top]
[s]Me de isto.[e]
[s]Entregue.[e]
[s]Eu quero isso agora.[e]

