[msg TalkMsg_DUMMY]
[s]......[n][w][e]

[msg TalkMsg_GUY_CONTACT_01]
[s]Hmph, tal humilhacao...[n][w][e]

[msg TalkMsg_GUY_CONTACT_02]
[s]Para que tal coisa aconteca de novo...[n][w][e]

[msg TalkMsg_GUY_CONTACT_03]
[s]Voce esta dizendo que voce sucumbira a tal[n]Barbarismo de novo...![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01]
[s]... eu gostaria de saber o verdadeiro significado de[n]esse comportamento.[n][w][e]
[s]Voce procura competicao amigavel com um[n]amado vizinho? Ou voce veio para[n]destruir um inimigo odiado?[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_01 top]
[s]Voce e um vizinho amado.[e]
[s]Voce e um inimigo repugnante.[e]
[s]Voce parece pregador.[e]

[msg TalkMsg_GUY_CHAT_FQ_01_R]
[s]... Essa e uma boa atitude. Sem duvida,[n]Isso vai agradar nosso pai tambem.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_2]
[s]Eu vejo. Voce nao mostra clemencia nem mesmo[n]aqueles amados. Nao se esqueca de ser[n]rigoroso em si mesmo tambem...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_3]
[s]Palavras mesquinhas... nao vao reprimir esta mare.[n]Nosso Pai nao pode ser enganado.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_4]
[s]Para chamar o exercicio de poder excessivo[n]"Competicao"... parece um conveniente[n]Frasando, nao e?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_5]
[s]Me desprezar e desprezar nosso pai.[n]Eu quero deixar isso claro.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_6]
[s]Pode-se honrar ate um inimigo como um[n]oponente digno... tal virtude e um presente[n]nosso pai deu a humanidade...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_7]
[s]Se sim, entao eu posso entender isso[n]eventos. Sou grato por sua resposta.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_8]
[s]Voce me ve como um oponente digno de[n]Essa resolucao? Vou aceitar isso como louvor.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_9]
[s]Nao fale tais denunciacoes[n]antes de pensar. Sua atitude apenas[n]Serve para separa-lo de Bliss.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_10]
[s]A visao do homem e estreita; O auto-estudo tem o seu[n]limites. Isso me agradaria se minhas palavras[n]prove edificar para voce.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_11]
[s]"O melhor medicamento tem um gosto amargo."[n]Essas sao as palavras do homem. Leva[n]minhas palavras agora como esse remedio.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_12]
[s]Minha palavra e a palavra de nosso pai.[n]Eu quero deixar isso claro.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_13]
[s]Hmph, entao voce esta continuando isso[n]comportamento mesmo agora? Que[n]humano de forca de vontade.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_14]
[s]Filhos do mesmo pai nao tem[n]Precisa de palavras... e? Um bonito[n]expressao, para um humano.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_15]
[s]Humano que nao pode entender minha consulta[n]mira, saiba que nosso pai estende seu[n]Benevolencia, mesmo para voce.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_16]
[s]Minha investigacao e a investigacao de nosso pai.[n]Eu quero deixar isso claro.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02]
[s]... voce ja cometeu[n]um pecado grave.[n][w][e]
[s]Voce sabe do que eu falo?[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_02 top]
[s]Pecado...?[e]
[s]Por favor, diga.[e]
[s]Nao fiz nada de errado.[e]

[msg TalkMsg_GUY_CHAT_FQ_02_R]
[s]Ahh, voce esta perto da compreensao. Para[n]Aja sem reconhecer o pecado... e o proprio pecado.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_2]
[s]Minha repreensao realmente o incomoda[n]assim...? Bom. Ser humano e sofrer.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_3]
[s]Adorar nosso Pai. Gaste seu[n]anos restantes humildemente. Aquilo vai[n]Sirva como expiacao para este pecado.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_4]
[s]... reconheca que voce pecou.[n]Se nao o fizer, voce continuara pecando[n]pela vida.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_5]
[s]Para buscar uma compreensao do bem[n]E o mal e encarado favoravelmente. Nosso[n]Pai ficara satisfeito tambem.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_6]
[s]Voce pergunta porque voce adivinhou meu[n]significado. Refletindo sobre suas acoes[n]mostra uma dedicacao admiravel.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_7]
[s]Seus proprios pecados produzem um[n]Iluminacao: Este e o homem. Orgulhoso[n]Humano... Transcenda sua ignorancia.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_8]
[s]Dependencia habitual e um problema em[n]e de si mesmo. Voce deveria dar amplo[n]pensei por conta propria.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_9]
[s]Os seres humanos nascem em pecado. Saber o[n]presenca da bencao divina de nosso Pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_10]
[s]A incapacidade jovem de reconhecer o pecado...[n]Parece que o homem ainda exige[n]benevolencia.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_11]
[s]Homem tolo que esqueceu o seu[n]consciencia do pecado. Voce ousa desgraca[n]o nome de nosso pai?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_12]
[s]... ousadamente declarado, humano. Isso sem arte[n]O comportamento causa uma impressao favoravel.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_13]
[s]Eu pego que esse comportamento erratico nasce[n]de um conhecimento nascente do pecado. Tal[n]A auto-abordagem e boa.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_14]
[s]Eu nem imaginava tal[n]resposta. Suponho que voce e o[n]Tipo de humano conhecido como "unico".[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_15]
[s]Voce nao pode extinguir seus pecados com[n]tiros. O homem fala bem quando diz[n]"O pecado gera pecado."[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_16]
[s]Me agredir e suportar a inimizade a[n]nosso pai. Parece que voce adicionou[n]outro pecado.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03]
[s]Ha algo que voce deve fazer, e isso[n]nao e meu assassinato...[n][w][e]
[s]E tomar consciencia do olhar de[n]nosso pai, que cuida de voce[n]com graca amorosa.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_03 top]
[s]Nao entendo.[e]
[s]Eu sinto o olhar dele.[e]
[s]Eu prefiro um olhar mais duro.[e]

[msg TalkMsg_GUY_CHAT_FQ_03_R]
[s]Por que nosso pai lhe deu "livre arbitrio"?[n]Parece um beneficio excessivo, nao e?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_2]
[s]Primeiro, voce deve ter vontade de[n]Compreendo. Certamente voce pode fazer isso,[n]Tao sagaz quanto voce.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_3]
[s]Nao ha necessidade de ser apressado. Nosso[n]O pai e parado em sua misericordia.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_4]
[s]Se voce iria a tanta medida para provar[n]um ponto, voce deve aplicar o mesmo[n]obstinacao para entender.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_5]
[s]Um bom sinal, para a distancia entre[n]voce e nosso pai e a distancia que voce[n]deve atravessar para alcancar a paz.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_6]
[s]Essas palavras... mesmo que sejam, mas o seu[n]imaginacao, eu olho favoravelmente[n]sua vontade de entender.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_7]
[s]Cessam suas falsidades. Aquelas palavras[n]Sirva apenas para degrada-lo ainda mais.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_8]
[s]Voce, que comete essa loucura, ousa falar[n]de nosso pai? Que senso inflado de[n]auto-importancia.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_9]
[s]Entao imagine como voce pode ser visto[n]Se voce me matasse.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_10]
[s]Tenha certeza, ha calor e[n]Gravidade no olhar de nosso pai...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_11]
[s]Gentil ou duro, cabe a nosso pai.[n]A escolha certamente nao e de ser[n]feito por gente como voce.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_12]
[s]Austeridade e uma caracteristica favoravel, especialmente[n]quando direcionado para o eu.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_13]
[s]... ha. Voce perdeu. Vou propor um[n]Interpretacao favoravel: mostra[n]Seu senso de auto-abordagem.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_14]
[s]Haha, voce esta vacilando? Nosso pai e[n]Observando voce o tempo todo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_15]
[s]Se voce tiver tempo para aprovar tao terrivel[n]assalto, use-o para refletir sobre[n]suas acoes.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_16]
[s]Tudo o que voce esta fazendo aqui esta evitando o seu[n]olhos da verdade.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04]
[s]Mesmo a essa hora, nosso pai misericordioso[n]Pode lhe dar perdao.[n][w][e]
[s]VOW que voce usara esse poder no[n]nome de nosso pai.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_04 top]
[s]Vou pensar sobre isso.[e]
[s]Nao ha necessidade de ser tao dramatico.[e]
[s]Eu recuso.[e]

[msg TalkMsg_GUY_CHAT_FQ_04_R]
[s]Incapaz de agir, apesar de saber o[n]caminho justo... nosso pai existe para[n]Oriente essa fragilidade.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_2]
[s]Vamos considerar favoravelmente o mero[n]indicacao de compreensao. Licitacao[n]Adeus ao seu passado abominavel.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_3]
[s]Esse poder e um beneficio de nosso pai.[n]No entanto, sinto orgulho em suas palavras.[n]Estou enganado?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_4]
[s]Nao equivale... mesmo[n]A clemencia tem limites.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_5]
[s]Uso indevido de grande poder degenera[n]a mera violencia. Tenho certeza que voce[n]Entenda, como voce e.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_6]
[s]Estou dizendo isso por sua causa. Eterno[n]Benevolencia comeca com amor e[n]respeito por nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_7]
[s]Homem, que nao pode exercer o poder que ele[n]se obteve. Eu oro tanto orgulho[n]nao traz ruina.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_8]
[s]Nao procuro sua opiniao. Saiba que meu[n]Aviso e o de nosso Pai, ele mesmo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_9]
[s]Para recusar a misericordia de nosso pai... voce e[n]como uma serpente no jardim 悪[n]Falou um.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_10]
[s]Parece que sua vontade nao cresceu[n]com seu corpo. Que nosso pai mostre[n]misericordia do homem lamentavel.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_11]
[s]O poder de empunhar o presente de nosso pai de[n]linguagem... e dominio muito pesado[n]cruzar para suportar?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_12]
[s]Duvide, deliberacao... estes tambem sao ensaios[n]de nosso pai. Nesse caso, eles nao trarao[n]seu crescimento?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_13]
[s]Isso esta certo. Use esse poder para atacar[n]nos adversarios de nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_14]
[s]Eu sei que voce tem poder excepcional.[n]Tudo o que resta e apontar para o apropriado[n]inimigo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_15]
[s]Vou deixar isso claro. Mesmo com o[n]Poder que voce segura, voce nao e pareo[n]para nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_16]
[s]Voce nao obteve esse poder em[n]seu proprio. Sabe que existe apenas porque[n]Nosso Pai permite isso.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05]
[s]... para se comportar dessa maneira, deve haver[n]algo neste mundo que e preocupante[n]voces.[n][w][e]
[s]...Muito bem. No lugar de nosso pai,[n]Vou ouvir suas reclamacoes.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_05 top]
[s]Por que nao podemos acabar com a guerra?[e]
[s]Sem queixas aqui.[e]
[s]Nao consigo uma namorada.[e]

[msg TalkMsg_GUY_CHAT_FQ_05_R]
[s]Levante-se e exalte o teu inimigo. Esses[n]Atos sao significativos e seu crescimento[n]agrada nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_2]
[s]Em meio a toda a criacao, apenas os salarios do homem[n]Guerras arbitrarias. Sua propria consulta forma um[n]Repudio total do homem.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_3]
[s]Homem insolente, que esqueceu o nosso[n]Misericordia do pai. Seu poder excessivo e[n]a causa de tanta miseria.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_4]
[s]Se toda a humanidade unida sob o nome[n]de nosso pai, entao esse conflito seria[n]Mas um sonho.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_5]
[s]Hmhm... voce leva suas queixas assim[n]estoicamente. Suponho que isso e preferivel[n]aquele que so reclama.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_6]
[s]Entao o que e que inspira o seu[n]comportamento? Eu luto para entender.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_7]
[s]Voce nao precisa lutar para conter todos os seus[n]frustracoes dentro. Por favor, fale francamente[n]E claramente comigo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_8]
[s]Nenhum humano e sem queixas. Voce[n]deve aprender a ser mais honesto.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_9]
[s]Humanos que se lembram de gratidao por[n]nosso pai e lindo. Ninguem pode[n]ignore esse apelo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_10]
[s]Quanto mais voce deseja, mais isso[n]retiros... abnegado traz seu[n]Deseja mais perto da fruicao.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_11]
[s]Voce nao tem o apelo digno de tal[n]empreendimento. Sim, comece advertindo[n]voce mesma.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_12]
[s]Tal servilidade para um filho do nosso[n]Pai magnifico... tenha o[n]Demonios ja corromperam voce?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_13]
[s]Deseja resolver seus problemas em[n]seu proprio? Sua iniciativa faz um[n]impressao favoravel.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_14]
[s]Seus problemas aparecem profundamente[n]enraizado. Mais uma razao para expressar[n]gratidao a nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_15]
[s]O desespero leva, mas a um destrutivo[n]fim. Lembre-se de sua gratidao a nosso pai[n]de uma vez so.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_16]
[s]... Violencia em relacao a mim e a violencia em relacao[n]o proprio pai. Refletir sobre isso[n]palavras de uma so vez.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06]
[s]... Estou sob a protecao do nosso[n]Pai magnifico.[n][w][e]
[s]Portanto, nao posso ser destruido. Desistir[n]A partir disso, inutilidade.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_06 top]
[s]O que voce esta falando?[e]
[s]Isso e absurdo.[e]
[s]Entao eu vou desistir.[e]

[msg TalkMsg_GUY_CHAT_FQ_06_R]
[s]Haha, tudo bem... voce me emprestou seu ouvido.[n]Essa atitude significa que voce ja tem[n]conflito abandonado.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_2]
[s]Compaixao existe porque mantemos o amor[n]e respeito em nossos coracoes. Nosso pai e[n]Observando voce tambem.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_3]
[s]Inimizade em relacao a mim e inimizade em relacao ao nosso[n]O proprio pai. Voce deveria ser sagaz[n]o suficiente para temer isso.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_4]
[s]O que e importante nao e a linguagem[n]compreensao, mas sim o[n]contemplacao de nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_5]
[s]Haha, isso e bom... me temendo...[n]Serve como impeto para voce[n]Conheca a majestade de nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_6]
[s]Voce e eu existimos embaixo do nosso[n]Pai magnifico. Saiba disso[n]A propria luta nao serve para nao serve.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_7]
[s]Esse mesmo comentario sublinha seu[n]duvida. Voce consegue nada, mas expondo[n]Sua propria fraqueza...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_8]
[s]A profundidade da minha adoracao para o nosso[n]Pai... supera em muito os limites[n]da sua imaginacao.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_9]
[s]Um curso de acao sabio. Nosso pai deve[n]perdoe voce tambem.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_10]
[s]Bom. Deixe o pensamento de me atacar[n]Passe por sua mente.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_11]
[s]Interessante. Entao essa foi a extensao de[n]Sua resolucao.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_12]
[s]Voce nao decide se eu sou ou nao[n]"salvo"... a decisao e de nosso pai[n]sozinho.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_13]
[s]Haha, isso e suficiente... eu nao sou seu[n]inimigo, e mais importante, nem[n]e nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_14]
[s]Por favor, espero que possamos alcancar um verbal[n]Entendendo... a violencia entristece nosso[n]Pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_15]
[s]... Eu ouso dizer que voce pretendia perder,[n]Mas isso tambem e o trabalho do nosso pai[n]assistencia divina.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_16]
[s]Aventurar-se a ter sucesso em seu inutil[n]Cruzada... essa loucura lanca uma palma[n]nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07]
[s]... Eu temo que voce tenha se desviado. Nosso[n]O pai ora, voce volta para os justos[n]caminho.[n][w][e]
[s]Deixe-me ouvir voce palavras absolutas de[n]arrependimento.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_07 top]
[s]Desculpe.[e]
[s]"Palavras de arrependimento."[e]
[s]Nao sinto muito.[e]

[msg TalkMsg_GUY_CHAT_FQ_07_R]
[s]Tao esplendida obediencia. Certamente, isso[n]vai agradar nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_2]
[s]Se essa fosse sua verdadeira mente, voce faria[n]Diga isso sem avisar. Agradeca[n]para nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_3]
[s]Agora, reconheca sua miseria, por[n]Na verdade, voce entristeceu nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_4]
[s]Palavras de desculpas, elas professam um[n]aquiescencia a punicao. Eu vi[n]essa aceitacao dentro de voce.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_5]
[s]Para cometer tanta travessia com o[n]idioma que nosso pai forneceu! o[n]a propria expressao e unica.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_6]
[s]Nao e isso que eu quis dizer...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_7]
[s]Nosso pai ve atraves de superficial[n]palavras e equivocos.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_8]
[s]Voce parece expressar penitencia, ainda[n]Voce nao mostra remorso. Suas palavras sao[n]o epitome da tolice humana.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_9]
[s]Eu falo pelo proprio pai, ainda[n]voce tem a temeridade de responder[n]com essas palavras infantis?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_10]
[s]Haha, voce e como uma crianca que apenas[n]discurso aprendeu. Mas a propria vida humana[n]e um mero piscar de olhos para mim.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_11]
[s]Voce recebeu permissao[n]pedir desculpas 悪 para nao escolher.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_12]
[s]Nosso Pai e gentil e tolerante;[n]ha valor em um humano como voce[n]reabilitacao.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_13]
[s]Aquele tirado... e o seu grito de ajuda.[n]Arrependimento e eventos como esses nao vao[n]ocorrem uma segunda vez.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_14]
[s]A duvida e passageira, mas a realidade do pecado e[n]eterno. Eu nao quero voce acumular tal[n]transgressoes.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_15]
[s]Suponho que voce nao tem intencao de[n]desculpando-se. Nao te dor de dor[n]triste nosso pai, entao?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_16]
[s]Voce prefere deixar sua arma falar,[n]voce? Quao essencialmente humano,[n]Aquela maneira vulgar de fala.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08]
[s]Saiba que suas acoes sao ao mesmo tempo[n]proprio e os do homem.[n][w][e]
[s]Para me ver como um inimigo e incorrer[n]A ira de nosso pai. O futuro do homem repousa[n]em suas maos.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_08 top]
[s]Deixe o futuro para mim.[e]
[s]Eu preciso da sua orientacao.[e]
[s]Eu nao entendo.[e]

[msg TalkMsg_GUY_CHAT_FQ_08_R]
[s]O que o futuro pode ser confiavel para quem[n]Aunha-se outros, entao?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_2]
[s]Falado com tanta clareza... sua resolucao[n]e realmente mais convincente.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_3]
[s]Um homem tolo e capaz de[n]erradicando a humanidade. Voce pode[n]Entende se eu forro isso assim?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_4]
[s]Nenhum homem o seguira como voce e agora.[n]Voce realmente tem alguma autoconsciencia?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_5]
[s]De fato, a humildade e a chave para abrir[n]O caminho para o futuro...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_6]
[s]O criador tambem e o destruidor. Isto e para[n]Seu proprio beneficio que voce entende[n]Gloria de nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_7]
[s]Nesse caso, voce deve primeiro se arrepender de[n]Seu comportamento passado...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_8]
[s]Nao confunda dependencia de nenhum[n]absolvicao. Voce deve assumir a responsabilidade[n]para suas proprias acoes.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_9]
[s]Primeiro, prepare em si mesmo um lugar[n]propicio ao entendimento. Voce[n]ainda nao chegaram a este lugar.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_10]
[s]Voce tem minha palavra; Isso nao e tentativa de[n]decepcao. Trate-o como uma licao do caminho[n]da humanidade.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_11]
[s]Unir as maos comigo no culto ao nosso[n]Pai... isso e tudo o que esta sendo perguntado[n]de voce.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_12]
[s]Voce nao tem entendimento porque voce[n]falta capacidade. Primeiro, perceba o seu proprio[n]impotencia.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_13]
[s]Suas acoes agora levarao o fardo de[n]Futuro do homem. Viva cada dia a serio[n]contemplacao.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_14]
[s]... continue a manter o nome do nosso[n]Pai em seu coracao, e voce pode fazer lances[n]Adeus a agonia inutil.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_15]
[s]Se nosso pai derruba seu martelo[n]de julgamento, voce sofrera a ira[n]de toda a humanidade.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_16]
[s]Voce nao e digno do de nosso pai[n]amor; Voce e completamente irremedavel,[n]filho do homem.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01]
[s]... agora, permita-me perguntar isso claramente.[n][w][e]
[s]Voce pode se sacrificar para[n]demonstrar sua veneracao do nosso[n]Pai?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_01 top]
[s]Eu certamente posso tentar.[e]
[s]Nao pode fazer.[e]
[s]O que e veneracao?[e]

[msg TalkMsg_GUY_CHAT_SQ_01_R]
[s]Ore para que a atitude continue eternamente.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_2]
[s]Se e possivel ou nao, seu[n]A atitude causa uma impressao favoravel.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_3]
[s]Essa flippancia.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_4]
[s]Tais palavras glib sao claramente falsas![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_5]
[s]... Nosso Pai preve que voce tera[n]uma mudanca de coracao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_6]
[s]Se isso for verdade, nao sei as palavras para[n]conversando com voce.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_7]
[s]Mesmo nosso pai magnanimo nao deve[n]perdoe essas palavras.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_8]
[s]Se voce sente a grandeza de nosso pai,[n]Certamente voce tambem deve ser salvo...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_9]
[s]Voce deve estar cansado.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_10]
[s]Parece que voce precisa... orientacao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_11]
[s]... Vou sobreviver para espalhar os ensinamentos[n]de nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_12]
[s]E dificil acreditar que voce e[n]humano...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_13]
[s]Os lideres perdidos tambem sao o meu papel.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_14]
[s]... um aviso de nosso pai foi[n]passou adiante.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_15]
[s]Esta idiotice e o seu fazendo...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_16]
[s]... um aviso de nosso pai foi[n]passou adiante.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02]
[s]... Tanto o seu mundo quanto este mundo,[n]Tudo e a criacao do nosso[n]Pai onipotente.[n][w][e]
[s]Voce, que reside naquele mundo do[n]Todo-Poderoso, o que e que sitiou[n]voce assim?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_02 top]
[s]Onipotente?[e]
[s]Eu nao sou sitiado.[e]
[s]Ha alguem que eu quero salvar.[e]

[msg TalkMsg_GUY_CHAT_SQ_02_R]
[s]De fato. Meditar sobre isso e o primeiro[n]passo em direcao a felicidade.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_2]
[s]...Isso e um bom comeco. Tal especulacao[n]tem um grande significado.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_3]
[s]Muito. Sua serenidade tambem esta la.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_4]
[s]Se voce nao tem entendimento, entao eu posso[n]De a voce uma licao completa.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_5]
[s]... voce nao tem a capacidade de se relacionar com os outros,[n]Nao e?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_6]
[s]Minhas palavras sao as de nosso pai. Conhecer[n]que voce nao tem escolha a nao ser aceitar[n]eles.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_7]
[s]... Eu sei que voce esta blefando.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_8]
[s]... Nao finge tanta estoicleidade. EU[n]Saiba o que voce realmente sente.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_9]
[s]Oh? Voce deseja ajudar os necessitados? Um[n]objetivo admiravel.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_10]
[s]Nosso Pai deve olhar favoravelmente[n]suas intencoes virtuosas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_11]
[s]Falado com armas desenhadas e apontadas,[n]Tais sentimentos sao ocos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_12]
[s]Entao voce viu que ha sofrimento[n]Mesmo em um mundo do Todo-Poderoso?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_13]
[s]Eu vejo. Voce decidiu desafiar[n]este julgamento sozinho...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_14]
[s]Voce nao precisa acelerar sua resposta.[n]Definhando sua decisao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_15]
[s]Saiba que essa obstinacao deve manter[n]voce alem daqueles que ofereceriam[n]compreensao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_16]
[s]Voce e tao sitiado que voce[n]Nao pode nem abrir sua boca?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03]
[s]... voce, que esqueceu a autoridade de nosso pai[n]e tornou-se uma vitima da sociedade construida[n]por homem impudente...[n][w][e]
[s]Pense com cuidado. Eu nao sou aquele que voce[n]deve detestar.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_03 top]
[s]Voce tem razao...[e]
[s]Isso e absurdo.[e]
[s]Eu serei o juiz disso.[e]

[msg TalkMsg_GUY_CHAT_SQ_03_R]
[s]Muito bom. Eu sou grato por seu[n]sabedoria.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_2]
[s]Errar e humano...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_3]
[s]A razao pela qual eu apareco antes de voce e[n]guie o caminho.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_4]
[s]Ha. Isso poderia significar que voce simplesmente precisa de um[n]Pequeno empurrao?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_5]
[s]Voce nunca descartara sua inimizade[n]para mim?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_6]
[s]Voce ainda nao entende o estado de[n]este mundo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_7]
[s]Parece que minhas palavras nao tem[n]Cheguei a voce...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_8]
[s]Voce aumenta intencionalmente o numero[n]de seus inimigos como um auto-imposto[n]tentativas?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_9]
[s]Entao, vou confiar este assunto ao seu[n]boa discricao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_10]
[s]Sinto o poder concedido por nosso pai.[n]O poder do livre arbitrio.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_11]
[s]Nem tudo vai do jeito que voce espera...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_12]
[s]Meu destino repousa em suas maos...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_13]
[s]Voce deve estar... gostando disso.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_14]
[s]Para voce, tudo o que voce ve e seu inimigo...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_15]
[s]Vou dizer isso mais uma vez: ponderar isso[n]Nos vamos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_16]
[s]Embora seu comportamento seja diferente, parece[n]voce e pequeno, mas um humano insolente[n]voce mesma...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04]
[s]... sim, eu serei martirizado aqui, e o[n]grandeza de nosso pai sera mencionado[n]para todos os tempos...[n][w][e]
[s]Eu nao temo a morte, nem voce.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_04 top]
[s]Na sua situacao?[e]
[s]Voce e dificil.[e]
[s]Nao se esforce.[e]

[msg TalkMsg_GUY_CHAT_SQ_04_R]
[s]E porque minhas crencas estao firmemente mantidas...[n]Isso e dificil para voce em sua juventude?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_2]
[s]Lance seus olhos em outro lugar, olhe alem[n]voce mesmo... isso por si so deve ser suficiente.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_3]
[s]Nosso pai esta comigo... isso e suficiente.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_4]
[s]Essa... e a grandeza de nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_5]
[s]Sim. Esse e o poder da fe.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_6]
[s]Suas ameacas ficam muito aquem de alcancar[n]nosso pai...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_7]
[s]Eu tenho mais a temer em perder o pai de nosso pai[n]graca.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_8]
[s]Isso e apenas um pouco em comparacao com o[n]grandeza de nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_9]
[s]... suportar o insuportavel e certamente o[n]maneira de toda a vida.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_10]
[s]Certamente nas circunstancias, tal[n]A preocupacao esta realmente vazia.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_11]
[s]Voce nem pode discernir se meu[n]As palavras sao verdadeiras?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_12]
[s]... voce tem um olhar inutil para[n]Observacao, nao e?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_13]
[s]Voce esta testando se meu[n]Palavras sao sinceras?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_14]
[s]... Eu respeito voce por lutar bravamente.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_15]
[s]Eu nao desejo sobrecarregar voce com sentimentos[n]de culpa pelo meu assassinato.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_16]
[s]Voce e bastante infantil. Um perdedor dolorido, eu[n]deve dizer.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05]
[s]... Permita-me falar com voce como se voce[n]eram um adulto maduro.[n][w][e]
[s]Por respeito ao nosso pai, vamos tomar[n]um momento de descanso...[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_05 top]
[s]Se e o que voce quer.[e]
[s]O que voce esta me contando?[e]
[s]Eu sou menor.[e]

[msg TalkMsg_GUY_CHAT_SQ_05_R]
[s]Meu... quao atencioso de voce.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_2]
[s]Uma negociacao madura... voce e apenas[n]Fingindo entender, voce nao esta?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_3]
[s]... voce esta procurando algo em[n]voltar, suponho?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_4]
[s]Muito atencioso de voce.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_5]
[s]Eu nao esperava tal obtusidade.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_6]
[s]Esse aspecto da sua personalidade e por que eu[n]Pense em voce quando crianca.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_7]
[s]... Eu nao desejo triste[n]Esta briga desnecessaria.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_8]
[s]Voce nao pode fazer o seu caminho[n]sociedade com tanta obtusidade.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_9]
[s]Voce pensa muito pouco de si mesmo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_10]
[s]Para perceber a propria imaturidade...[n]faz uma impressao favoravel.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_11]
[s]Voce meramente... finge na maturidade?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_12]
[s]Haha... se sim, entao eu posso aproveitar isso[n]oportunidade...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_13]
[s]Voce pretende concluir uma tarefa urgente?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_14]
[s]Esta violencia e uma birra patetica,[n]nada mais.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_15]
[s]... Nosso pai sofre.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_16]
[s]Como voce pode permanecer imperturbavel, mesmo[n]Quando confrontado com o nome de nosso pai...?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06]
[s]... voce me feriu, um enviado de[n]nosso pai. E inevitavel que a calamidade[n]Devo acontecer com voce.[n][w][e]
[s]... o minimo que posso fazer e estender este pequeno[n]misericordia. Nomeie uma calamidade que voce pode suportar.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_06 top]
[s]Faca-o lotado onde eu compro.[e]
[s]De-me violencia.[e]
[s]Sem calamidades, por favor.[e]

[msg TalkMsg_GUY_CHAT_SQ_06_R]
[s]... uma calamidade tao secular.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_2]
[s]Hmm... entao voce deseja se abster de[n]bens materiais, nao e? Este[n]faz uma impressao favoravel.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_3]
[s]Nao consigo imaginar uma resposta tao glib e[n]sincero.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_4]
[s]Suponho que isso e tecnicamente calamitado,[n]Mas... oh, nao importa.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_5]
[s]Talvez voce a favor, mas eu nao posso suportar[n]Essa violencia de voce...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_6]
[s]Voce fala como se tivesse crescido[n]em vez de sofrer violencia...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_7]
[s]Se isso e tudo que voce deseja, eu posso obrigar voce[n]pessoalmente.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_8]
[s]Acredite em nosso pai, e voce deve[n]Encontre a forca para suportar tanta calamidade.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_9]
[s]Ate o pecado inocente deve ser eternamente[n]punido.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_10]
[s]Declarando que a intencao de alguem difere de[n]egoismo simples.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_11]
[s]No que me diz respeito, encontrando voce[n]era minha propria calamidade...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_12]
[s]Nao seja irracional.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_13]
[s]Minhas palavras nao podem ser silenciadas pelo[n]Gosta de tiros.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_14]
[s]... Eu vejo sua impaciencia claramente.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_15]
[s]Voce entra em panico quando a realidade e dificil de[n]urso...? Patetico, nao e?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_16]
[s]Voce prefere uma escolha mais pratica[n]do que o das calamidades?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07]
[s]... a proposito, parece que ha alguns[n]mal-entendido aqui.[n][w][e]
[s]Esse poder, ele se origina de nosso pai.[n]Portanto, nao e razoavel retribuir por[n]o favor?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_07 top]
[s]Eu nunca considerei isso.[e]
[s]Esse poder e todo meu.[e]
[s]Nao sei.[e]

[msg TalkMsg_GUY_CHAT_SQ_07_R]
[s]... Adenha-se de tudo o que voce era.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_2]
[s]A partir deste dia, seu[n]A consciencia deve ser alterada.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_3]
[s]Que humano insolente... isso e[n]o suficiente.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_4]
[s]Como voce ousa afirmar sua reivindicacao a isso[n]poder sem nem mesmo conhecer a fonte[n]voce mesma?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_5]
[s]... homem insolente, quao facilmente voce cai[n]de graca.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_6]
[s]Mesmo que o proprio poder que voce usa[n]"Ganhe" qualquer coisa e um presente do nosso[n]Pai?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_7]
[s]Parece que voce cresceu[n]Irebiado no vinho do narcisismo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_8]
[s]Tal arrogancia... isso e o verdadeiro[n]Medida da natureza humana?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_9]
[s]Sem duvida, isso e porque nosso pai[n]esta tao perto que ele nao pode ser visto.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_10]
[s]Poderia ser porque o poder de nos[n]Enviados nao sao iguais a tarefa...?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_11]
[s]Embora voce possa nao entender agora,[n]O dia chegara quando voce o fizer.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_12]
[s]Minha caridade e a benevolencia da nossa[n]Pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_13]
[s]Eu vejo. Entao, esse artificio astuto e o[n]Produto da sua "civilizacao"...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_14]
[s]Voce, que se recusa a viajar no caminho de[n]a humanidade, pode ser considerada nada alem de[n]um tolo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_15]
[s]Este comportamento erratico e o resultado de seu[n]ignorancia nas maneiras de expressar[n]gratidao?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_16]
[s]Nao estou fazendo um irracional[n]exigem.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08]
[s]... a proposito, voce conhece a origem de[n]vida? Tanto voce quanto eu fomos criados por nosso[n]Pai.[n][w][e]
[s]Ou seja, somos irmaos. Ha[n]Nao ha razao para lutarmos.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_08 top]
[s]Deixe meus pais fora disso.[e]
[s]Tu podes estar certo.[e]
[s]Mas voce e uma sombra.[e]

[msg TalkMsg_GUY_CHAT_SQ_08_R]
[s]Voce nao tem pais, salve nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_2]
[s]Voce pode dar um testemunho com confianca?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_3]
[s]Sangue como familia e uma ideia inculcada[n]Sobre a formacao da "sociedade".[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_4]
[s]Com o tempo, ate voce pode vir para[n]Compreendo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_5]
[s]Nao ha duvida de que somos irmaos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_6]
[s]Finalmente, parece que essa animosidade vai[n]dissipar.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_7]
[s]Vou declarar isso claramente... embora[n]Irmaos, nao somos iguais.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_8]
[s]Essencialmente, nosso pai e seus filhos[n]sao os mesmos...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_9]
[s]Basear conflitos em aparencias ou[n]linhagens de sangue... isso e perigoso[n]Ideologia, voce nao concorda?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_10]
[s]Voce diz isso, mas vemos comum[n]valores que nos conectam ambos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_11]
[s]Isso tambem e um julgamento imposto por nosso[n]Pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_12]
[s]Isso nada mais e do que sua tentativa[n]para justificar seus atos crueis de violencia.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_13]
[s]Pensar que, apesar da nossa fraternidade, nos[n]nao tenho as palavras com as quais[n]conversar...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_14]
[s]Enquanto houver um coracao que bate dentro[n]Seu peito... entao somos irmaos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_15]
[s]Vou perguntar ao nosso Pai... e verdadeiramente[n]perdao que eu deveria conceder[n]Meu irmao aqui antes de mim?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_16]
[s]Suponho que voce esta perplexo, voce esta[n]nao? Se voce cessar esta batalha agora, nosso[n]Pai perdoara voce.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09]
[s]Eu vejo agora... e entao eu entendo tudo isso[n]foi feito. Isso e apenas um teste?[n][w][e]
[s]Voce pareceu testar minha adoracao[n]de nosso pai. Sim, voce e... o tentador![n][w][e]

[sel TalkSel_GUY_CHAT_SQ_09 top]
[s]Voce me pegou.[e]
[s]Voce esta enganado.[e]
[s]Voce esta bem?[e]

[msg TalkMsg_GUY_CHAT_SQ_09_R]
[s]Se voce e realmente aquele tentador diabolico,[n]Entao nao tenho chance de vitoria.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_2]
[s]O tentador... o grande adversario.[n]Nao tenho chance de vitoria.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_3]
[s]Voce me despreza porque eu sou um[n]Enviado de nosso Pai?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_4]
[s]... Eu ceder a sua tentacao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_5]
[s]Beguilers raramente falam a verdade.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_6]
[s]Se for esse o caso, entao como voce[n]conta do meu tremor?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_7]
[s]Voce nao e o tentador...? Entao eu posso[n]provar vitorioso, afinal.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_8]
[s]Uma intencao insidiosa sem senso de[n]autoconsciencia... eu esperaria nao[n]Menos do tentador.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_9]
[s]Nao ha necessidade de se preocupar. Pois estou sob[n]A protecao divina de nosso Pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_10]
[s]Que irritante... pensar que o tentador[n]me mostrou pena...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_11]
[s]Isso depende da sua abordagem...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_12]
[s]Nosso Pai nunca iria me abandonar...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_13]
[s]... Nao vou abandonar minha adoracao por[n]nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_14]
[s]Espere! Se voce e o tentador...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_15]
[s]Voce se esquece de si mesmo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_16]
[s]Embora a carne possa perecer, a alma vive[n]em... voce nao sabe disso?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10]
[s]A proposito, voce ja esta em posse[n]da bencao divina de nosso Pai.[n][w][e]
[s]O que voce espera realizar por[n]Me machucando mais...?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_10 top]
[s]Mais sono.[e]
[s]Tesouro.[e]
[s]Depois de comecar, nao consigo parar.[e]

[msg TalkMsg_GUY_CHAT_SQ_10_R]
[s]Voce me sacrificaria para satisfazer seu[n]indolencia...? Quao desprezivel.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_2]
[s]Eu vejo. Entao, voce pretende me enviar[n]Para meu sono eterno?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_3]
[s]Uma escolha de palavras que nao devem ser usadas[n]No meio da batalha...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_4]
[s]Entao, e provavel que essa atitude prove um[n]obstaculo a qualquer descanso pacifico.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_5]
[s]O que voce sofre parece ser[n]Mais do que desejo material...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_6]
[s]Isso e ainda mais imperdoavel![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_7]
[s]Nao posso perdoar um ladrao cego por seu[n]propria avareza![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_8]
[s]Voce acredita que tais bugigangas mesquinhas valem[n]arriscando sua vida?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_9]
[s]Isso significa que voce vai me ferir[n]Infinitamente?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_10]
[s]Entao nao comece.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_11]
[s]E essa tolice que faz o homem[n]tao cativante.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_12]
[s]Entao, voce vai expor o seu proprio[n]tolice para mim?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_13]
[s]Voce nao pode nem descobrir o que voce[n]espero realizar... isso e patetico,[n]nao e?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_14]
[s]Humano, possuido por avareza, eis[n]minha determinacao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_15]
[s]... continue ao longo deste caminho e voce vai[n]perdido ate a bencao divina de nosso[n]Pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_16]
[s]Voce nao pode progredir enquanto ciente de seu[n]propria tolice, filho patetico do homem...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11]
[s]...Pense com cuidado. Estou aqui por causa de[n]Seu desejo de salvacao.[n][w][e]
[s]Para voce me forcar a me prostrar,[n]Como aquele que so procura seu bem-estar...[n]Existe algo mais irracional?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_11 top]
[s]Me desculpe.[e]
[s]Eu nao quero salvacao.[e]
[s]Cale-se.[e]

[msg TalkMsg_GUY_CHAT_SQ_11_R]
[s]Se voce busca a salvacao, eu posso te dar[n]o socorro que voce deseja.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_2]
[s]Eu desejo transmitir a sinceridade do meu[n]palavras.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_3]
[s]Parece que voce tem um coracao suficiente para[n]Confesse seus pecados, pelo menos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_4]
[s]Nao vou ouvir palavras superficiais de arrependimento.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_5]
[s]Se voce tiver tempo para abrir seu[n]boca, entao use esse tempo para melhorar[n]essa situacao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_6]
[s]Entao como voce explica minha presenca[n]aqui?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_7]
[s]Essa e uma desculpa para justificar o seu[n]acoes irracionais.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_8]
[s]Eu quero remover todos os obstaculos ao seu[n]obediencia.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_9]
[s]Voce pretende esconder seu devasso[n]atos?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_10]
[s]Esmagando um inconveniente... isso tambem,[n]e irracional.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_11]
[s]Muito bem. Vou orar por voce em silencio.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_12]
[s]Nao posso dizer que e um bom plano. Voce[n]nao tem nada a ganhar com meu silencio.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_13]
[s]Mesmo se voce estiver ciente do seu erro, voce[n]ainda sao muito cravos para reconhece-lo...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_14]
[s]Alguem se pergunta quantas outras verdades[n]poderia ter sido enterrado no mesmo[n]moda, no seu mundo...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_15]
[s]Para ceder antes de devasso, isso e[n]Outro julgamento de nosso pai...?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_16]
[s]Saiba que acumular atos irracionais[n]para isolamento ou destruicao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12]
[s]... eu quero deixar algo claro, entao[n]Vou me aventurar a fazer essa pergunta.[n][w][e]
[s]Voce... me acha um charlatan?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_12 top]
[s]Eu nao acho isso.[e]
[s]Eu penso em voce como um inimigo.[e]
[s]Voce nao e um?[e]

[msg TalkMsg_GUY_CHAT_SQ_12_R]
[s]Esta correto. Estou orientando voce para o seu[n]caminho da felicidade.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_2]
[s]Pela maneira como voce me tratou,[n]Nao tenho certeza se deveria acreditar em voce...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_3]
[s]Se isso for verdade, por que razao[n]Recebi essa lesao grave?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_4]
[s]Eu sinto uma agenda oculta por tras do seu[n]palavras... mas eu vou deixar isso para la.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_5]
[s]Reconsiderar isso. Eu nao sou um charlatan[n]Nem sou seu inimigo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_6]
[s]Isso e um grave mal-entendido.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_7]
[s]Eu sei. Voce nao teve que colocar isso[n]em palavras.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_8]
[s]E dizer isso dependendo de[n]negociacoes, pode haver espaco[n]Para uma reconciliacao?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_9]
[s]Tal insensibilidade. Voce esta tentando[n]me provoque?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_10]
[s]Claramente um terrivel mal-entendido tem[n]foram feitos e devem ser corrigidos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_11]
[s]Voce percebe que eu sou um enviado de[n]nosso pai?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_12]
[s]Parece que voce nao tem perspicacia para[n]entender adequadamente a situacao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_13]
[s]Vou aceitar isso como voce encorajando[n]Eu nao para "me vender pouco".[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_14]
[s]Se eu realmente penso nisso, nao me importo[n]Sua impressao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_15]
[s]... voce nao precisa ter medo; Eu nao sou o que[n]voce pensa.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_16]
[s]A deterioracao da capacidade do homem de[n]Converse... parece que isso se tornou[n]um problema serio.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13]
[s]... ah, voce mergulha em direcao ao seu[n]proprios desejos, sem consideracao pelos outros,[n]Ou mesmo nosso pai?[n][w][e]
[s]Parece que os filhos do homem tem[n]denunciou a palavra de nosso pai.[n]Diga-me, em que valor voce encontrou?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_13 top]
[s]Nos temos amor.[e]
[s]Eu posso sobreviver sozinho.[e]
[s]Encontre para mim.[e]

[msg TalkMsg_GUY_CHAT_SQ_13_R]
[s]... Eu ouvi que o homem hoje pode amar[n]Os seres humanos encontrados em pinturas...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_2]
[s]O amor e tantas vezes a desculpa em que se baseou em[n]veu em atividades mais amplas...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_3]
[s]E comum mencionar "amor" quando[n]Deseja esconder algo...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_4]
[s]Isso tambem e a providencia mencionada de[n]por nosso pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_5]
[s]Ouvi dizer que existem muitas pessoas que[n]va ao longo da vida solteira.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_6]
[s]Sua consciencia da santidade de[n]o individuo torna um favoravel[n]impressao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_7]
[s]Suponho que seja um beneficio de uma cultura[n]de comunicacao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_8]
[s]Seu estabelecimento como individuo...[n]Isso faz de voce o seu igual?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_9]
[s]...De fato. Eu nao tinha considerado isso.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_10]
[s]Eu me esforcei para faze-lo, mas... me desculpe.[n]Nao encontrei nada.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_11]
[s]Seria como encontrar uma agulha em[n]um palheiro.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_12]
[s]Eu nao tenho tempo para desperdicar meus esforcos[n]em nome do homem.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_13]
[s]Entao, voce usara esse poder para mostrar[n]Seu valor?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_14]
[s]Eu nao pretendia sugerir que o homem e inutil.[n]Aceite minhas desculpas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_15]
[s]Pelo contrario, voce deve agradecer que[n]Eu apontei sua imaturidade.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_16]
[s]Essa e precisamente a gordura de que[n]Eu estava falando![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14]
[s]... agora que penso nisso, foi[n]pacifico aqui, ate sua chegada.[n][w][e]
[s]Voce jogou este lugar em revolta.[n]O que voce pensaria se eu fiz o mesmo[n]seu mundo?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_14 top]
[s]Eu nao permitiria.[e]
[s]Eu nao tinha pensado nisso.[e]
[s]Olho por olho.[e]

[msg TalkMsg_GUY_CHAT_SQ_14_R]
[s]Exatamente. E dificil permitir tal[n]Violencia... entao, eu tenho seu consentimento.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_2]
[s]Exceto que, ao contrario de voce, sou misericordioso.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_3]
[s]Era injusto da minha parte ter tido[n]Esperava muito de um tolo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_4]
[s]Se este incidente puder ser usado como um bom[n]Licao moral, entao eu tambem estou satisfeito.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_5]
[s]Se esse incidente fez voce se ampliar[n]Seu pensamento, estou satisfeito.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_6]
[s]A vida... e um presente que voce recebeu.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_7]
[s]Bem, entao, seguindo em frente, voce deve[n]Considere essas coisas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_8]
[s]Voce e uma criatura imprudente por natureza.[n]Era injusto da minha parte ter esperado[n]mais de voce.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_9]
[s]Um ato portador de odio serve apenas para nascer[n]odeio novamente.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_10]
[s]Voce deve cortar essas correntes tristes[n]isso liga voce.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_11]
[s]Incorreto... refletir sobre o significado de[n]"Vire a outra bochecha."[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_12]
[s]Essa ideologia e a antitese do heroismo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_13]
[s]Ah, entao suas acoes sao baseadas em um[n]Verdadeiro entendimento da revolta...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_14]
[s]Eu vejo. Ha uma grande causa que voce tambem[n]deve alcancar.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_15]
[s]Voce esta fingindo que nao ve o[n]Impropriedade diante de seus olhos?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_16]
[s]Voce continua a semear discordia mesmo depois de[n]recebendo esse aviso...?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15]
[s]... uma vez, o mundo que voce habitou foi chamado[n]"Paraiso." O que e agora?[n][w][e]
[s]Nao e um terreno fertil para o impacto[n]humanos? Como voce ve este mundo de[n]Sua?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_15 top]
[s]Cheio de adultos corruptos.[e]
[s]Muitos lugares para fazer compras.[e]
[s]Parece normal para mim.[e]

[msg TalkMsg_GUY_CHAT_SQ_15_R]
[s]E todos eles os habitantes do[n]Paraiso caido...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_2]
[s]Eu so posso orar para que voce nao acabe[n]o mesmo caminho.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_3]
[s]Talvez voce deva corrigir o seu proprio[n]comportamento antes de criticar os adultos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_4]
[s]Entao vamos nos esforcar para um paraiso[n]desprovido de distorcao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_5]
[s]Esse e um ponto de vista intrigante... mas[n]Nao ha nada aqui para discutir.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_6]
[s]Isso tambem e outro beneficio do nosso[n]Pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_7]
[s]Isso e certamente um sintoma do homem[n]Avarice inchado.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_8]
[s]Sua perspectiva... acho que e muito[n]pragmatico.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_9]
[s]Entao... voce se ajustou a isso[n]situacao atual do mundo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_10]
[s]Voce diz que o mundo de nosso pai e "normal"...?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_11]
[s]Que ser humano magnanimo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_12]
[s]Voce se atreve a tomar uma atitude tao desafiadora[n]sobre a mediocridade deste mundo...?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_13]
[s]Quanto tempo voce continuara a evitar[n]seus olhos?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_14]
[s]Eu sou a unica coisa que voce esta focado[n]ON, eu nao estou?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_15]
[s]E claro. Como eu poderia esperar ser[n]Entendido por um expulso do paraiso?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_16]
[s]Voce quer dizer que voce nao e um[n]"Humano insolente"?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16]
[s]...Me ouca. Eu sou o portador do homem[n]felicidade, despachada para voce pelo nosso[n]Pai.[n][w][e]
[s]Destruir-me e manter isso[n]felicidade do homem. Voce e sabio.[n]Voce entende isso, nao e?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_16 top]
[s]Isso seria ruim.[e]
[s]O que voce esta tentando dizer?[e]
[s]Estou feliz o suficiente.[e]

[msg TalkMsg_GUY_CHAT_SQ_16_R]
[s]"Felicidade" e um principio do humano[n]conduta.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_2]
[s]... parece que voce chegou tarde demais para[n]essa realizacao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_3]
[s]Entao chore por sua insolencia e implore[n]por perdao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_4]
[s]Devo contar a nosso pai deste incidente.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_5]
[s]E um solecismo responder minha pergunta[n]com uma pergunta...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_6]
[s]Eu imagino considerar a felicidade mutua[n]renderizaria ate esse tipo de[n]trocar desnecessario.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_7]
[s]Certamente existem meios mais altos de[n]entendimento do que o de mero[n]Lingua. Voce deveria saber.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_8]
[s]A resposta para essa pergunta deve ser[n]encontrado por conta propria.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_9]
[s]Nao se esqueca: sua alegria pode se tornar[n]a tristeza de outro.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_10]
[s]Voce elogia o atual que voce... um favoravel[n]impressao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_11]
[s]E, no entanto, isso tambem e um beneficio do nosso[n]Pai.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_12]
[s]Tal e sua propria ilusao.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_13]
[s]... com isso, a felicidade recuou[n]ainda mais longe.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_14]
[s]Por que voce nao pode compreender isso[n]Terminar esse conflito e a felicidade?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_15]
[s]... minha existencia e para o proposito de[n]Sua felicidade tambem.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_16]
[s]Tolo, que nao entende o gracioso[n]Benevolencia de nosso Pai...[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND]
[s](planned to be cut) Greedy child, unafraid of the divine...[n]O que voce deseja tanto?[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND_2]
[s](planned to be cut) Are you really going to pull the trigger?[n]Reconsiderar suas acoes. O que poderia[n]Tal ato realizado?[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND_3]
[s](planned to be cut) If you have any mercy, allow me[n]perguntar. O que posso lhe oferecer no lugar[n]da minha vida?[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND_4]
[s](planned to be cut) What humiliation... What would you[n]Peca enquanto apontava isso para mim?[n][w][e]

[sel TalkSel_GUY_NEGO_SURREND top]
[s]Quero voce.[e]
[s]...De-me dinheiro.[e]
[s]Eu quero um item raro.[e]
[s]Eu quero um pouco de Intel.[e]
[s]Abaixe o nivel de seguranca.[e]

[msg TalkMsg_GUY_NEGO_FIFTYFI]
[s]Voce esta me dizendo... para contar uma mentira com[n]O objetivo de enganar outras sombras?[n][w][e]
[s]O mero pensamento e imundo, mas eu posso[n]Divirta a ideia se eu receber[n][var 0]Yen...[n][w][e]

[msg TalkMsg_GUY_NEGO_FIFTYFI_2]
[s]Voce esta me dizendo... para contar uma mentira com[n]O objetivo de enganar outras sombras?[n][w][e]
[s]Se isso viesse a luz, entao eu seria...[n]Conceda-me[f 2 5 3 9999 3]Yen, e eu vou[n]arriscar...[n][w][e]

[msg TalkMsg_GUY_NEGO_FIFTYFI_3]
[s]Voce me faria enganar meus irmaos?[n][w][e]
[s]Voce pode me conceder parte de sua vida[n]forca? Vamos considerar esse assunto mais[n]depois disso...[n][w][e]

[msg TalkMsg_GUY_NEGO_FIFTYFI_4]
[s]Voce me faria enganar meus irmaos?[n][w][e]
[s]Voce pode me conceder alguns dos seus[n]energia? Vamos considerar este assunto[n]mais depois disso...[n][w][e]

[sel TalkSel_GUY_NEGO_FIFTYFI top]
[s]Tudo bem, eu vou dar para voce.[e]
[s]Nao posso atender as suas demandas.[e]

[msg TalkMsg_GUY_NEGO_REQUIRE]
[s]Que calor... a terra esta irritada pelo[n]Tirania do homem. O que eu consegui[n]eu mesmo confundido...?[n][w][e]
[s]Muito bem. Devo atender ao seu pedido. Voce[n]pode fornecer um dizimo de[f 2 5 3 9999 4], Assim,[n]correto?[n][w][e]

[msg TalkMsg_GUY_NEGO_REQUIRE_2]
[s]...* tosse** tosse* eu fui visitado[n]pelas dores da doenca.[n][w][e]
[s]Eu sei que voce e um ladrao noturno, mas[n]prestar atencao ao meu pedido. Eu pergunto isso[n]me forneca um[f 2 5 3 9999 4]...[n][w][e]

[msg TalkMsg_GUY_NEGO_REQUIRE_3]
[s]... Pai, esses olhos com coceira! Nao posso[n]Pare de arranhar.[n][w][e]
[s]Eu nao sei quem voce e, mas voce[n]por acaso ter algum[f 2 5 3 9999 4]?[n][w][e]

[msg TalkMsg_GUY_NEGO_REQUIRE_4]
[s]No entanto, pedindo que eu envolva outro[n]Sombras e mentir...[n][w][e]
[s]Isso e perigoso. Se exposto, eu faria[n]ser assassinado. Mas eu era para receber[n][f 2 5 3 9999 3], Eu consideraria isso.[n][w][e]

[sel TalkSel_GUY_NEGO_REQUIRE top]
[s]Entregue[e]
[s]Nao entregue[e]

[msg TalkMsg_GUY_NEGO_PAYFOR_]
[s]... a misericordia de nosso pai. Em seu mundo,[n]isso vale[var 0]Yen.[n][w][e]

[msg TalkMsg_GUY_NEGO_PAYFOR__2]
[s]Receber a caridade de nosso pai. Na tua[n]mundo, isso vale a pena[var 0]Yen.[n][w][e]

[msg TalkMsg_GUY_NEGO_PAYFOR__3]
[s]Tudo e o beneficio de nosso pai...[n]Isto e[f 2 5 3 9999 1].[n][w][e]

[msg TalkMsg_GUY_NEGO_PAYFOR__4]
[s]Que este seja o impeto da sua salvacao...[n]Pegue isso[f 2 5 3 9999 1].[n][w][e]

[sel TalkSel_GUY_NEGO_PAYFOR top]
[s]Isso e o suficiente para mim.[e]
[s]Voce tem mais, certo?[e]

[msg TalkMsg_GUY_NEGO_Re_ACCE]
[s]E assim mesmo? Eu nao vou pressionar voce, mas...[n][w][e]

[msg TalkMsg_GUY_NEGO_Re_ACCE_2]
[s]Hmph. Parece que voce esta profundo em pecado...[n][w][e]

[msg TalkMsg_GUY_NEGO_Re_ACCE_3 [Ryuji]]

[msg TalkMsg_GUY_RESULT_GET_P]
[s]Eu nao sou uma sombra deste lugar...[n]Eu residi no mar do[n]Alma humana desde os tempos antigos...[n][w][e]
[s]Meu nome e[clr 1][var 2][clr 27].[n]Esse e o seu nome tambem...[n]Nao esqueca disto.[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_P_2]
[s]Oh, mas[clr 1][var 2][clr 27][n]ja esta dentro de voce![n][w][e]

[msg TalkMsg_GUY_RESULT_GET_P_3]
[s]Ahh, mas sua classificacao e tao baixa... para o seu[n]crescimento, eu te concordo isso[f 2 5 3 9999 1].[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_M]
[s]O chamado "dinheiro" nao tem valor real, mas[n]No seu mundo, isso e igual[var 0]Yen.[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_I]
[s]Entao, eu vou lhe conceder um[n][f 2 5 3 9999 1]. Nao esqueca[n]gratidao por nosso pai.[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_S]
[s]Isso tambem e novidade de nosso pai. Nao faca[n]Dissemine-o desnecessariamente.[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY]
[s]Nosso Pai aconselha voce a nao falar de[n]para qualquer pessoa, sob qualquer circunstancia.[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_2]
[s]Humano cobicado, parece que voce precisa[n]julgamento...![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_3]
[s]Bem, entao, a proxima coisa que vou conceder a voce[n]e o primeiro ataque do julgamento do meu irmao![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_4]
[s]... humano problematico... vou recuar[n]por enquanto![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_5]
[s]E com isso, adeus! Que o Pai[n]cuidar de voce![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_6]
[s]... O-OR... Pai? Eu sou o pai!?[n]Ou... a mae?[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_7]
[s]Nao chegue mais perto e sujo criatura![n]Pai! Me ajude!![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_8]
[s]......[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_9]
[s]Humano irritante! Como voce ousa[n]Tente conversar comigo![n][w][e]
[s]... Mas talvez minha raiva tenha sido extraviada.[n]Fale, e eu vou ouvir voce...[n][w][e]

[msg TalkMsg_RESULT_GET_SECRE]
[s]Oh, eu nao percebi que voce ja sabia[n]este. Nesse caso, vou conceder isso a voce[n]em vez de.[n][w][e]

[msg TalkMsg_SURRENDER_FROM_C]
[s]... constantemente lutando contra nao e como mostrar[n]sua adoracao de nosso pai. eu devo[n]Retiro daqui.[n][w][e]

[msg TalkMsg_SUCCESS_SKIMMING]
[s]Oh, voce esta interessado nisso? Tu es[n]Um humano observador, voce nao e?[n][w][e]

[msg TalkMsg_RESULT_ENEMY_SHO]
[s]Guh, Gah...[n][w][e]

[msg TalkMsg_RESULT_ENEMY_SLE]
[s]ZZZ...[n][w][e]

[msg TalkMsg_RESULT_ENEMY_FLA]
[s]Por que e como se eu estivesse assando no[n]Chamas do purgatorio...? Ughhh... queima...[n][w][e]
[s]Vou suportar esse calor em nome de[n]nosso pai... agora, permita-me ouvir[n]O que voce tem a dizer.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_VER]
[s]Hrgh, minha visao, nao posso ficar focado...[n]O mundo de nosso pai esta girando...![n][w][e]
[s]Vou suportar essa tontura em nome de[n]nosso pai... agora, permita-me ouvir o que[n]voce tem que dizer.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_FOR]
[s]Sinto como se estivesse esquecendo[n]algo...[n][w][e]
[s]... Mas espere, sinto que me lembrei. Permitir[n]eu ouvir o que voce tem a dizer.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_DES]
[s]Pai, voce me abandonou...?[n][w][e]
[s]Muito bem. Vou ouvir voce. No[n]muito menos, voce parece precisar de mim...[n][w][e]

[msg TalkMsg_RESULT_ENEMY_BRA]
[s]Oh... um novo Salvador desembarcou de[n]Paraiso?[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH]
[s]Voce e o Salvador...[n][w][e]
[s]... ah! Suas palavras me despertaram[n]para a verdade...[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_2]
[s]Ahh... voce e o salvador...[n][w][e]
[s]... Nao, nao vou ser enganado, falso salvador![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_3]
[s]Ahh... voce e o salvador...[n][w][e]
[s]Obrigada. Por favor, aceite esta oferta.[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_4]
[s]Ahh... voce e o salvador...[n][w][e]
[s]... Nao, nao vou ser enganado, falso salvador![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_5]
[s]Ahh... voce e o Salvador... obrigado.[n]Por favor, aceite este tesouro.[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_6]
[s]Ahh... voce e o salvador...[n][w][e]
[s]... Nao, nao vou ser enganado, falso salvador![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_7]
[s]Oh, entao esse e o meu caminho ordenado... obrigado[n]voces. Meus olhos estao abertos. Eu te concordo isso.[n][w][e]

[msg TalkMsg_CONTACT_11]
[s]Idiota! Voce nao se atreva a desafiar o rei kamoshida[n]da sua estacao humilde.[n][w][e]

[msg TalkMsg_CONTACT_12]
[s]Idiota! Voce nao se atreva a desafiar Lord Madarame[n]da sua estacao humilde.[n][w][e]

[msg TalkMsg_CONTACT_13]
[s]Idiota! Nao se atreva a desafiar o Sr. Kaneshiro[n]da sua estacao humilde.[n][w][e]

[msg TalkMsg_CONTACT_14]
[s]Idiota! Nao se atreva a desafiar a rainha[n]da sua estacao humilde.[n][w][e]

[msg TalkMsg_CONTACT_15]
[s]Idiota! Nao se atreva a desafiar Lord Okumura[n]da sua estacao humilde.[n][w][e]

[msg TalkMsg_CONTACT_16]
[s]Idiota! Nao se atreva a desafiar Lady Niijima[n]da sua estacao humilde.[n][w][e]

[msg TalkMsg_CONTACT_17]
[s]Idiota! Voce nao se atreva a desafiar o mestre akechi[n]da sua estacao humilde.[n][w][e]

[msg TalkMsg_CONTACT_18]
[s]Idiota! Nao se atreva a desafiar o Senhor Shido[n]da sua estacao humilde.[n][w][e]

[msg TalkMsg_CONTACT_19]
[s]Idiota! Nao se atreva a desafiar sua excelencia[n]da sua estacao humilde.[n][w][e]

[msg TalkMsg_CONTACT_10]
[s]Idiota! Nao se atreva a desafiar o segredo[n]Chefe da sua estacao humilde.[n][w][e]

[msg TalkMsg_CONTACT_MEMENTOS]
[s]...O que voce esta fazendo!?[n][w][e]

[msg TalkMsg_CONTACT_MEMENTOS_2]
[s]E mortificante ter ficado cara a cara[n]com um rufiano...[n][w][e]

[msg TalkMsg_CONTACT_MEMENTOS_3]
[s]Hmph, tal humilhacao...[n][w][e]

[msg TalkMsg_GREET_POSSESSING]
[s]Oh, voce tem a mascara de[clr 1][var 2][clr 27].[n]Entao voce e um amigo.[n][w][e]

[msg TalkMsg_NEGO_POSSESSING_]
[s]Sera um prazer cooperar.[n]Voce deseja a coisa conhecida como[n]"Dinheiro", correto?[n][w][e]

[msg TalkMsg_NEGO_POSSESSING__2]
[s]Eu nao vou ser inaugurado em meu apoio. Voce[n]Desejo bens, correto? Pegue isso.[n][w][e]

[msg TalkMsg_GREET_POSSESSED]
[s]Estamos juntos uma vez, mas agora, aqui[n]Nos estamos em margens opostas...[n][w][e]

[msg TalkMsg_NEGO_POSSESSED]
[s]Eu nao tenho ma vontade. Eu so desejo evitar[n]conflito desnecessario.[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_M]
[s]... o dinheiro seria aceitavel?[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_I]
[s]... os bens sao aceitaveis? Por favor, pegue isso.[n][w][e]

[msg TalkMsg_GREET_POSSESSED_]
[s]Alguns dizem que velhas amizades podem ser[n]renovado. Como voce se sente sobre[n]falando sobre as coisas?[n][w][e]

[msg TalkMsg_TALK_POSSESSED_B]
[s]Bom. Parece que ainda podemos chegar a um[n]entendimento mutuo...[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_B]
[s]Eu vejo. Muito bem entao.[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_B_2]
[s]Voce esta interessado em dinheiro, suponho...[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_B_3]
[s]Eu acredito que isso pode ser o que voce queria...[n]Por favor, pegue.[n][w][e]

[msg TalkMsg_FIRST_CONTACT]
[s]...Muito bem. Discussao e parte integrante de[n]alcancando um entendimento mutuo.[n][w][e]

[msg TalkMsg_PRE_QUESTION]
[s]... eu sei que tipo de humano voce[n]sao, mas me responda uma coisa.[n][w][e]

[msg TalkMsg_PRE_QUESTION_ACQ]
[s]Voce escolheu... sabiamente.[n][w][e]

[msg TalkMsg_PRE_QUESTION_DEN]
[s]Voce esta com frio, como estou... minha palavra, eu apenas[n]lembrou-se de algo![n][w][e]

[msg TalkMsg_TALK_TECH_ITEM]
[s]...Ridiculo. Voce pensou que poderia[n]Tao facilmente me enganar?[n][w][e]

[msg TalkMsg_TALK_TECH_PERSON]
[s]Voce e tao eloquente quanto eu... minha palavra,[n]Acabei de me lembrar de algo![n][w][e]

[msg TalkMsg_SETTLE_DOWN]
[s]Y-voce nao deveria estar causando tal[n]comocao... o que me lembra, eu[n]tem algo para discutir com voce.[n][w][e]

[msg TalkMsg_RESULT_SHOT_1]
[s]Covarde! Voce se recusa a ate divertir[n]minhas perguntas!?[n][w][e]
[s]Muito bem. Permita-me responder no vencimento[n]Gentil![n][w][e]

[msg TalkMsg_RESULT_SHOT_2]
[s]Oh! Pai... estou salvo. Eu ofereco meu[n]gratidao sincera.[n][w][e]
[s]... voce deve se arrepender de nos menosprezar...![n][w][e]

[msg TalkMsg_RESULT_SHOT_3]
[s]...Voce ficou maluco!? Nao ha[n]Escolha, mas para fugir![n][w][e]

[msg TalkMsg_RESULT_SHOT_4]
[s]Aaaah...![n][w][e]
[s]Ele here! Pegue isso![n][w][e]

[msg TalkMsg_RESULT_GET_PERSO]
[s]Eu nao sou uma sombra deste lugar...[n]Eu residi no mar do[n]Alma humana desde os tempos antigos...[n][w][e]
[s]Meu nome e[clr 1][var 2][clr 27].[n]Esse e o seu nome tambem...[n]Nao esqueca disto.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_2]
[s]Eu nao sou uma sombra deste lugar...[n]Eu residi no mar do[n]Alma humana desde os tempos antigos...[n][w][e]
[s]Meu nome e[clr 1][var 2][clr 27].[n]Esse e o seu nome tambem...[n]Nao esqueca disto.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_3]
[s]Eu nao sou uma sombra deste lugar...[n]Eu residi no mar do[n]Alma humana desde os tempos antigos...[n][w][e]
[s]Meu nome e[clr 1][var 2][clr 27].[n]Esse e o seu nome tambem...[n]Nao esqueca disto.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_4]
[s]Eu nao sou uma sombra deste lugar...[n]Eu residi no mar do[n]Alma humana desde os tempos antigos...[n][w][e]
[s]Meu nome e[clr 1][var 2][clr 27].[n]Esse e o seu nome tambem...[n]Nao esqueca disto.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_5]
[s]Eu nao sou uma sombra deste lugar...[n]Eu residi no mar do[n]Alma humana desde os tempos antigos...[n][w][e]
[s]Meu nome e[clr 1][var 2][clr 27].[n]Esse e o seu nome tambem...[n]Nao esqueca disto.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_6]
[s]Eu nao sou uma sombra deste lugar...[n]Eu residi no mar do[n]Alma humana desde os tempos antigos...[n][w][e]
[s]Meu nome e[clr 1][var 2][clr 27].[n]Esse e o seu nome tambem...[n]Nao esqueca disto.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_7]
[s]Eu nao sou uma sombra deste lugar...[n]Eu residi no mar do[n]Alma humana desde os tempos antigos...[n][w][e]
[s]Meu nome e[clr 1][var 2][clr 27].[n]Esse e o seu nome tambem...[n]Nao esqueca disto.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_8]
[s]Eu nao sou uma sombra deste lugar...[n]Eu residi no mar do[n]Alma humana desde os tempos antigos...[n][w][e]
[s]Meu nome e[clr 1][var 2][clr 27].[n]Esse e o seu nome tambem...[n]Nao esqueca disto.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_9]
[s]Eu nao sou uma sombra deste lugar...[n]Eu residi no mar do[n]Alma humana desde os tempos antigos...[n][w][e]
[s]Meu nome e[clr 1][var 2][clr 27].[n]Esse e o seu nome tambem...[n]Nao esqueca disto.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_10]
[s]Eu nao sou uma sombra deste lugar...[n]Eu residi no mar do[n]Alma humana desde os tempos antigos...[n][w][e]
[s]Meu nome e[clr 1][var 2][clr 27].[n]Esse e o seu nome tambem...[n]Nao esqueca disto.[n][w][e]

[msg TalkMsg_ED_bye_D01_01]
[s]Prepare-se para o rei Kamoshida's[n]julgamento de sua loucura.[n][w][e]

[msg TalkMsg_ED_bye_D01_02]
[s]Hah... voce acha que seu poder sera verdadeiramente[n]ser uma partida contra o rei Kamoshida?[n][w][e]

[msg TalkMsg_ED_bye_D01_03]
[s]Permita-me avisa-lo: King Kamoshida[n]nao e tao branda quanto eu.[n][w][e]

[msg TalkMsg_ED_bye_D02_01]
[s]Prepare-se para a de Lord Madarame[n]julgamento de sua loucura.[n][w][e]

[msg TalkMsg_ED_bye_D02_02]
[s]Hah... voce acha que seu poder sera verdadeiramente[n]Seja uma partida contra Lord Madarame?[n][w][e]

[msg TalkMsg_ED_bye_D02_03]
[s]Permita-me avisa-lo: lorde Madarame[n]nao e tao branda quanto eu.[n][w][e]

[msg TalkMsg_ED_bye_D03_01]
[s]Prepare-se para o Sr. Kaneshiro's[n]julgamento de sua loucura.[n][w][e]

[msg TalkMsg_ED_bye_D03_02]
[s]Hah... voce acha que seu poder sera verdadeiramente[n]ser uma partida contra o Sr. Kaneshiro?[n][w][e]

[msg TalkMsg_ED_bye_D03_03]
[s]Permita-me avisa-lo: Sr. Kaneshiro[n]nao e tao branda quanto eu.[n][w][e]

[msg TalkMsg_ED_bye_D04_01]
[s]A estrada robusta que leva a rainha[n]Desta tumba real... voce pode superar isso?[n][w][e]

[msg TalkMsg_ED_bye_D04_02]
[s]Hmph... um vilao como se voce nunca pudesse[n]alcancar a rainha.[n][w][e]

[msg TalkMsg_ED_bye_D04_03]
[s]... Deixe a rainha estar. A rainha nao e[n]O tipo a ser insignificante por bandidos mesquinhos.[n][w][e]

[msg TalkMsg_ED_bye_D05_01]
[s]Prepare-se para o senhor Okumura[n]julgamento de sua loucura.[n][w][e]

[msg TalkMsg_ED_bye_D05_02]
[s]Hah... voce acha que seu poder sera verdadeiramente[n]ser uma partida contra Lord Okumura?[n][w][e]

[msg TalkMsg_ED_bye_D05_03]
[s]Permita-me avisa-lo: lorde Okumura[n]nao e tao branda quanto eu.[n][w][e]

[msg TalkMsg_ED_bye_D06_01]
[s]Prepare-se para a Lady Niijima's[n]julgamento de sua loucura.[n][w][e]

[msg TalkMsg_ED_bye_D06_02]
[s]Hah... voce acha que seu poder sera verdadeiramente[n]ser uma partida contra Lady Niijima?[n][w][e]

[msg TalkMsg_ED_bye_D06_03]
[s]Permita-me avisa-lo: Lady Niijima[n]nao e tao branda quanto eu.[n][w][e]

[msg TalkMsg_ED_bye_D07_01]
[s]Prepare-se para o mestre Akechi's[n]julgamento de sua loucura.[n][w][e]

[msg TalkMsg_ED_bye_D07_02]
[s]Hah... voce acha que seu poder sera verdadeiramente[n]ser uma partida contra o mestre Akechi?[n][w][e]

[msg TalkMsg_ED_bye_D07_03]
[s]Permita-me avisa-lo: Mestre Akechi[n]nao e tao branda quanto eu.[n][w][e]

[msg TalkMsg_ED_bye_D08_01]
[s]Prepare-se para o lorde Shido's[n]julgamento de sua loucura.[n][w][e]

[msg TalkMsg_ED_bye_D08_02]
[s]Hah... voce acha que seu poder sera verdadeiramente[n]ser uma partida contra Lord Shido?[n][w][e]

[msg TalkMsg_ED_bye_D08_03]
[s]Permita-me avisa-lo: lorde shido e[n]nao tao branda quanto eu.[n][w][e]

[msg TalkMsg_ED_bye_D09_01]
[s]Prepare-se para a Excelencia dele[n]julgamento de sua loucura.[n][w][e]

[msg TalkMsg_ED_bye_D09_02]
[s]Hah... voce acha que seu poder sera verdadeiramente[n]ser uma partida contra sua excelencia?[n][w][e]

[msg TalkMsg_ED_bye_D09_03]
[s]Permita-me avisa-lo: a excelencia dele[n]nao e tao branda quanto eu.[n][w][e]

[msg TalkMsg_ED_bye_D10_01]
[s]Prepare-se para o chefe secreto[n]julgamento de sua loucura.[n][w][e]

[msg TalkMsg_ED_bye_D10_02]
[s]Hah... voce acha que seu poder sera verdadeiramente[n]ser uma partida contra o chefe secreto?[n][w][e]

[msg TalkMsg_ED_bye_D10_03]
[s]Permita-me avisa-lo: o chefe secreto[n]nao e tao branda quanto eu.[n][w][e]

[msg TalkMsg_CONTACT_11_1]
[s]Espere! Vou informar o rei Kamoshida![n][w][e]

[msg TalkMsg_CONTACT_11_2]
[s]... Fique sua mao! Se voce atacar, voce[n]vai se revelar ao rei Kamoshida![n][w][e]

[msg TalkMsg_CONTACT_11_3]
[s]Tenha misericordia de mim! Eu farei qualquer coisa...[n][w][e]

[msg TalkMsg_CONTACT_12_1]
[s]Espere! Vou informar Lord Madarame![n][w][e]

[msg TalkMsg_CONTACT_12_2]
[s]... Fique sua mao! Se voce atacar, voce[n]Vai se revelar a Lord Madarame![n][w][e]

[msg TalkMsg_CONTACT_12_3]
[s]Tenha misericordia de mim! Eu farei qualquer coisa...[n][w][e]

[msg TalkMsg_CONTACT_13_1]
[s]Espere! Vou informar o Sr. Kaneshiro![n][w][e]

[msg TalkMsg_CONTACT_13_2]
[s]... Fique sua mao! Se voce atacar, voce[n]vai se revelar ao Sr. Kaneshiro![n][w][e]

[msg TalkMsg_CONTACT_13_3]
[s]Tenha misericordia de mim! Eu farei qualquer coisa...[n][w][e]

[msg TalkMsg_CONTACT_14_1]
[s]Espere! Vou informar a rainha![n][w][e]

[msg TalkMsg_CONTACT_14_2]
[s]... Fique sua mao! Se voce atacar, voce[n]vai se revelar a rainha Futaba![n][w][e]

[msg TalkMsg_CONTACT_14_3]
[s]Tenha misericordia de mim! Eu farei qualquer coisa...[n][w][e]

[msg TalkMsg_CONTACT_15_1]
[s]Espere! Vou informar Lord Okumura![n][w][e]

[msg TalkMsg_CONTACT_15_2]
[s]... Fique sua mao! Se voce atacar, voce[n]Vai se revelar a Lord Okumura![n][w][e]

[msg TalkMsg_CONTACT_15_3]
[s]Tenha misericordia de mim! Eu farei qualquer coisa...[n][w][e]

[msg TalkMsg_CONTACT_16_1]
[s]Espere! Vou informar Lady Niijima![n][w][e]

[msg TalkMsg_CONTACT_16_2]
[s]... Fique sua mao! Se voce atacar, voce[n]vai se revelar a Lady Niijima![n][w][e]

[msg TalkMsg_CONTACT_16_3]
[s]Tenha misericordia de mim! Eu farei qualquer coisa...[n][w][e]

[msg TalkMsg_CONTACT_17_1]
[s]Espere! Vou informar o mestre Akechi![n][w][e]

[msg TalkMsg_CONTACT_17_2]
[s]... Fique sua mao! Se voce atacar, voce[n]Vai se revelar ao Mestre Akechi![n][w][e]

[msg TalkMsg_CONTACT_17_3]
[s]Tenha misericordia de mim! Eu farei qualquer coisa...[n][w][e]

[msg TalkMsg_CONTACT_18_1]
[s]Espere! Vou informar Lord Shido![n][w][e]

[msg TalkMsg_CONTACT_18_2]
[s]... Fique sua mao! Se voce atacar, voce[n]Vai se revelar a Lord Shido![n][w][e]

[msg TalkMsg_CONTACT_18_3]
[s]Tenha misericordia de mim! Eu farei qualquer coisa...[n][w][e]

[msg TalkMsg_CONTACT_19_1]
[s]Espere! Vou informar sua excelencia![n][w][e]

[msg TalkMsg_CONTACT_19_2]
[s]... Fique sua mao! Se voce atacar, voce[n]vai se revelar a sua excelencia![n][w][e]

[msg TalkMsg_CONTACT_19_3]
[s]Tenha misericordia de mim! Eu farei qualquer coisa...[n][w][e]

[msg TalkMsg_CONTACT_10_1]
[s]Espere! Vou informar o chefe secreto![n][w][e]

[msg TalkMsg_CONTACT_10_2]
[s]... Fique sua mao! Se voce atacar, voce[n]vai se revelar ao chefe secreto![n][w][e]

[msg TalkMsg_CONTACT_10_3]
[s]Tenha misericordia de mim! Eu farei qualquer coisa...[n][w][e]

[msg TalkMsg_FQ_REACT_GOODMOO]
[s](planned to be cut) Hmhm... I feel better already.[n][w][e]

[msg TalkMsg_FQ_REACT_INTERES]
[s](planned to be cut) You seem to have right attitude.[n][w][e]

[msg TalkMsg_FQ_REACT_DISPLEA]
[s](planned to be cut) ... I don't feel so good anymore.[n][w][e]

[msg TalkMsg_FQ_REACT_ANGER]
[s](planned to be cut) How infuriating. You should think[n]antes de falar.[n][w][e]

[msg TalkMsg_FQ_REACT_BROKEDO]
[s]Muito bem. Seria tolice[n]Espere mais de voce.[n][w][e]

[msg TalkMsg_HAVE_NO_SECRET]
[s]Infelizmente... eu nao acontece[n]tem alguma informacao que seria[n]de uso para voce.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_REF]
[s]Eu nao serei inclinado por ameacas! Eu preciso de[n]Apenas para perseverar em minha fe![n][w][e]

[msg TalkMsg_RESULT_ENEMY_REF_2]
[s]Nao tenho nada a dizer sobre bandidos.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_REF_3]
[s]Esta negociacao e apenas um desperdicio de palavras![n][w][e]

[msg TalkMsg_SHOOT_REACTION01]
[s]U-u-uping o prestigio dos fortes... eu vejo[n]eu mesmo dentro de voce...[n][w][e]
[s]Ah! Este tempo gasto com voce tem[n]me despertou para a verdade...[n][w][e]

[msg TalkMsg_SHOOT_REACTION02]
[s]Sendo agressivo porque voce tem um[n]Safeguard... eu me vejo dentro de voce...[n][w][e]
[s]Ah! Este tempo gasto com voce tem[n]me despertou para a verdade...[n][w][e]

[msg TalkMsg_SHOOT_REACTION03]
[s]N-no misericordia pelos fracos... e como se eu fosse[n]olhando para um espelho...[n][w][e]
[s]Ah! Este tempo gasto com voce tem[n]me despertou para a verdade...[n][w][e]

[msg TalkMsg_SHOOT_REACTION04]
[s]P-Power e a medida do valor de alguem...[n]Essa e minha crenca tambem...[n][w][e]
[s]Ah! Este tempo gasto com voce tem[n]me despertou para a verdade...[n][w][e]

[msg TalkMsg_PLEAD_SKIMMING]
[s]Pare! Voce tem me observado tudo isso[n]Tempo. Ha algo que voce quer dizer?[n][w][e]

[msg TalkMsg_PLEAD_NO_SKIMMIN]
[s]Eu me rendo! Por favor, apenas poupe minha vida![n][w][e]

[msg TalkMsg_ACCEPT_ALERT_DOW]
[s]Eu entendo. Vou relatar a todos[n]que nao ha nada errado.[n][w][e]

[msg TalkMsg_NO_REQUIREMENT]
[s]Voce nao tem o que eu preciso![n][w][e]

[msg TalkMsg_RESULT_SQ_ITEM1]
[s]Eu te ofereco isso. Esqueca tudo sobre mim.[n][w][e]

[msg TalkMsg_RESULT_SQ_ITEM2]
[s]Agora, vamos selar o acordo com isso.[n][w][e]

[msg TalkMsg_RESULT_SQ_PERSON]
[s]Essa paixao parece familiar... ah! este[n]O tempo gasto me despertou para a verdade...[n][w][e]

[msg TalkMsg_RESULT_SQ_PERSON_2]
[s]Eu posso ressoar com isso... ah! Desta vez[n]gasto me despertou para a verdade...[n][w][e]

[msg TalkMsg_RESULT_SQ_PAYFOR]
[s]Eu entendo o que voce esta dizendo, mas...[n]Ha algo que nao[n]faz sentido.[n][w][e]

[msg TalkMsg_RESULT_SQ_PAYFOR_2]
[s]...Eu vejo. Eu entendo voce, humano.[n]No entanto, vamos resolver as coisas com isso.[n][w][e]

[msg TalkMsg_RESULT_SQ_AGAIN1]
[s]No final, o que voce queria[n]comunicar?[n][w][e]

[msg TalkMsg_RESULT_SQ_AGAIN2]
[s]No final, o que voce queria[n]comunicar?[n][w][e]

[msg TalkMsg_RESULT_SQ_CARD1]
[s]Eu sinto que nao ha mais necessidade de[n]conversacao. Pegue isso e deixe-nos[n]Diga nossas despedidas.[n][w][e]

[msg TalkMsg_RESULT_SQ_CARD2]
[s]Entao, por favor, aceite isso.[n][w][e]

[msg TalkMsg_RESULT_SQ_COUNTE]
[s]Sinta a ira dos ceus![n][w][e]

[msg TalkMsg_RESULT_SQ_COUNTE_2]
[s]Agora, aceite seu julgamento![n][w][e]

[msg TalkMsg_RESULT_SQ_ALERT1]
[s]Eu terei que voce conhece o poder do meu[n]Forcas![n][w][e]

[msg TalkMsg_RESULT_SQ_ALERT2]
[s]...Eu nao posso te perdoar! Nao importa o que[n]acontece![n][w][e]

[msg TalkMsg_RESULT_SQ_INFO1]
[s]Vou lhe conceder muito conhecimento, entao[n]Voce nao vai me poupar esse absurdo?[n][w][e]

[msg TalkMsg_RESULT_SQ_INFO2]
[s]Olha, vou conceder informacoes, entao[n]Encontre-me no meio do caminho aqui, ok?[n][w][e]

[msg TalkMsg_RESULT_SQ_MONEY1]
[s]... pegue isso pelo menos.[n][w][e]

[msg TalkMsg_RESULT_SQ_MONEY2]
[s]... E com isso, eu vou te dar isso. Entao[n]Olhe para o outro lado.[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_8]
[s]Oh, entao esse e o meu caminho ordenado...[n]No entanto, parece que voce ja[n]tem as informacoes que voce procura.[n][w][e]
[s]Entao me permita oferecer isso isso[n][f 2 5 3 9999 1]em vez de...[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_9]
[s]Ahh, voce e o Salvador... obrigado.[n]Parece que a paz chegou...![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_10]
[s]... Nao, nao vou ser enganado, falso salvador![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_11]
[s]Ahh, voce e o Salvador...[n][w][e]
[s]Voce ja tem a persona[n][clr 1][var 2][clr 27]... Por favor, pegue[n]isto[f 2 5 3 9999 1]em vez de.[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_12]
[s]Ahh, voce e o Salvador...[n][w][e]
[s]No entanto, sua classificacao esta abaixo do meu[n]ter. Permita-me conceder isso a voce[n][f 2 5 3 9999 1]em vez de.[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_13]
[s]Ensine-me sobre o grande salvador...[n][w][e]

[msg TalkMsg_RESULT_HACKING]
[s]O eu que voce ve aqui tem sido profundamente[n]manchado, mas eu te ofereco o meu mais valorizado[n]posse.[n][w][e]

[msg TalkMsg_SKIMMING_BRAINWA]
[s]Oh, quao adequado do escolhido que[n]voce reconheceria a sacralidade de[n]isto.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_11]
[s]Agradeco do fundo do meu...[n]meu... ah! Sua bondade despertou[n]eu para a verdade...[n][w][e]

[msg TalkMsg_CHARM_TECH_ITEM]
[s]... Estou chocado, sem palavras. voce ja pensou[n]Isso me enganaria?[n][w][e]

[msg TalkMsg_CHARM_TECH_PERSO]
[s]Agora que voce me confessou, isso[n]nao seria um bom pressagio para eu desconsiderar[n]a tua historia.[n][w][e]

[msg TalkMsg_BONUS_CARD]
[s]... Eu admiro essas palavras! Eu gostaria de[n]termine com isso.[n][w][e]

[msg TalkMsg_DONATION]
[s]E uma mera insignificancia, mas por favor aceite[n]este auxilio.[n][w][e]

[msg TalkMsg_UNTALKABLE]
[s]Nnn... ggghh![n][w][e]

[msg TalkMsg_GUY_OP_00_00]
[s]Meu coracao...[n][e]

[msg TalkMsg_GUY_OP_00_01]
[s]... e puro como a neve acionada.[n][e]

[msg TalkMsg_GUY_OP_01_00]
[s]Mesmo se for destruido...[n][e]

[msg TalkMsg_GUY_OP_01_01]
[s]Vou te perdoar...[n][e]

[msg TalkMsg_GUY_OP_02_00]
[s]Minhas intencoes...[n][e]

[msg TalkMsg_GUY_OP_02_01]
[s]... Eu quero que voce os entenda.[n][e]

[msg TalkMsg_GUY_OP_03_00]
[s]Este tratamento gentil...[n][e]

[msg TalkMsg_GUY_OP_03_01 [Ryuji]]

[msg TalkMsg_GUY_EN_No_00]
[s]... Adeus e lembre-se: o bom[n]voce faz pelos outros e o bem que voce faz[n]para voce mesmo.[n][w][e]

[msg TalkMsg_GUY_EN_No_01]
[s]... Eu sobrevivi por pouco? eu vou[n]Obrigado agora por me conceder seu[n]misericordia.[n][w][e]

[msg TalkMsg_GUY_EN_No_02]
[s]... e com isso eu devo partir. De o seu[n]tudo e faca o seu melhor.[n][w][e]

[msg TalkMsg_GUY_EN_bye_00]
[s]Prepare-se para o julgamento de[n]Sua loucura.[n][w][e]

[msg TalkMsg_GUY_EN_bye_01]
[s]Hmph... os ceus nao permitirao[n]Tanta selvageria para correr desenfreado.[n][w][e]

[msg TalkMsg_GUY_EN_bye_02]
[s]Vou orar por voce alcancar a penitencia por[n]Nossa proxima reuniao...[n][w][e]

[msg TalkMsg_GUY_NEGO_GIVE_00]
[s]... eu aceitarei seu sentimento.[n][w][e]

[msg TalkMsg_GUY_NEGO_GIVE_01]
[s]... entao, eu vou levar isso.[n][w][e]

[msg TalkMsg_GUY_NEGO_DECLINE]
[s]Perder a chance de expiar[n]desejos egoistas... que tolice...[n][w][e]

[msg TalkMsg_GUY_NEGO_DECLINE_2]
[s]Esse comportamento frivolo... mas eu devo[n]nao diga uma palavra...[n][w][e]

[msg TalkMsg_GUY_NEGO_TAKE_00]
[s]Este e um beneficio de nosso pai. Refletir[n]sobre isso.[n][w][e]

[msg TalkMsg_GUY_NEGO_TAKE_01]
[s]Isso vai salvar voce, suponho.[n][w][e]

[msg TalkMsg_GUY_NEGO_DOUBLEU]
[s]Humano tolo, possuido pela ganancia...[n][w][e]

[msg TalkMsg_GUY_NEGO_DOUBLEU_2]
[s]Essa ganancia sem fundo. Assim como[n]Abaddon, lider de gafanhotos.[n][w][e]

[msg TalkMsg_GUY_NEGO_AGREE_0]
[s]Obrigado por ser tao atencioso.[n][w][e]

[msg TalkMsg_GUY_NEGO_AGREE_0_2]
[s]Isso nao e para o meu beneficio. Por favor, pense[n]Dele beneficiando o mundo.[n][w][e]

[msg TalkMsg_GUY_NEGO_REFUSE_]
[s]Hmph, que pena... isso foi para[n]Seu beneficio.[n][w][e]

[msg TalkMsg_GUY_NEGO_REFUSE__2]
[s]Suponho que ha uma boa razao para que[n]Voce recusaria meu pedido, correto?[n][w][e]

[msg TalkMsg_Coop_Reiji_00 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 10 301 1]Ei, o que voce esta tentando puxar? Usar[n]Sua cabeca, cara![n][w][e]

[msg TalkMsg_Coop_Reiji_01 [Ryuji]]
[s]Parece a sombra[n]reconsiderado...[n][w][e]

[msg TalkMsg_Coop_Morgana_00 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 10 301 1]Nao me mova! Sua propria vida esta em jogo![n][w][e]

[msg TalkMsg_Coop_Morgana_01 [Morgana]]
[s]Parece a sombra[n]reconsiderado...[n][w][e]

[msg TalkMsg_Coop_Ann_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 3 301 1]Nao se mova 悪 a menos que voce queira obter[n]Cheio de chumbo![n][w][e]

[msg TalkMsg_Coop_Ann_01 [Ann]]
[s]Parece a sombra[n]reconsiderado...[n][w][e]

[msg TalkMsg_Coop_Yugo_00 [Yusuke]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 5 3 301 1]Resistir e inutil! Considere bem[n]a posicao em que voce esta.[n][w][e]

[msg TalkMsg_Coop_Yugo_01 [Yusuke]]
[s]Parece a sombra[n]reconsiderado...[n][w][e]

[msg TalkMsg_Coop_Makoto_00 [Makoto]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 6 3 301 1]Pare de resistir e trabalhe conosco aqui![n][w][e]

[msg TalkMsg_Coop_Makoto_01 [Makoto]]
[s]Parece a sombra[n]reconsiderado...[n][w][e]

[msg TalkMsg_Coop_Haruko_00 [Haru]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 7 3 301 1]Por favor, espere! Voce entende o[n]posicao em que voce se encontra?[n][w][e]

[msg TalkMsg_Coop_Haruko_01 [Haru]]
[s]Parece a sombra[n]reconsiderado...[n][w][e]

[msg TalkMsg_Coop_Akechi_00 [Akechi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 9 3 301 1]Espere! Voce seria sabio para nao[n]tente qualquer movimento repentino.[n][w][e]

[msg TalkMsg_Coop_Akechi_01 [Akechi]]
[s]Parece a sombra[n]reconsiderado...[n][w][e]

[msg TalkMsg_Sense_Sixthsense [Akechi]]
[s]Iniciando o sexto sentido![n][f 1 3 65535][w][e]
[s]Seu sentido elevado deixou claro[n]Uma opcao que nao deve ser escolhida![n][w][e]

[msg TalkMsg_Sense_Negotiatio [Akechi]]
[s]Iniciando negociacao![n][f 1 3 65535][w][e]
[s]Com tecnica de negociacao aumentada,[n]Agora voce recebe maior cooperacao![n][w][e]

[msg TalkMsg_Sense_Gigolo_00 [Akechi]]
[s]Iniciando Gigolo![n][f 1 3 65535][w][e]
[s]Mostrando sua seducao refinada[n]estimula os coracoes e mentes[n]de sombras femininas![n][w][e]

[msg TalkMsg_Sense_Performanc [Akechi]]
[s]Inicie o desempenho![n][f 1 3 65535][w][e]
[s]Suas esplendidas travessuras cativam[n]O interesse da sombra inimiga![n][w][e]

[msg TalkMsg_Sense_Intelligen [Akechi]]
[s]Inicie a inteligencia![n][f 1 3 65535][w][e]
[s]Sua ampla exibicao de conhecimento[n]vence o respeito de[n]Sombras masculinas![n][w][e]

[msg TalkMsg_Tisei]
[s]Voce nao tem o suficiente[n]conhecimento para escolher isso.[n][f 1 4][e]

[msg TalkMsg_Iroke]
[s]Voce nao tem o suficiente[n]charme para escolher isso.[n][f 1 4][e]

[msg TalkMsg_Ginou]
[s]Voce nao tem o suficiente[n]Proficiencia para escolher isso.[n][f 1 4][e]

[msg TalkMsg_Hinsei]
[s]Voce nao tem o suficiente[n]bondade em escolher isso.[n][f 1 4][e]

[msg TalkMsg_Yuuki]
[s]Voce nao tem o suficiente[n]coragem para escolher isso.[n][f 1 4][e]

[sel Nego_Surrender_sel top]
[s]Me de seu poder.[e]
[s]Mostre-me o dinheiro.[e]
[s]Eu quero um item.[e]
[s]Pantera, voce lida com isso.[e]

[sel Nego_Surrender_sel_01 top]
[s][clr 2]Junte-se a minha causa.[clr 27][e]
[s]Mostre-me o dinheiro.[e]
[s]Eu quero um item.[e]
[s]Pantera, voce lida com isso.[e]

[sel Nego_Surrender_sel_02 top]
[s]Me de seu poder.[e]
[s][clr 2]Mostre-me o dinheiro.[clr 27][e]
[s]Eu quero um item.[e]
[s]Pantera, voce lida com isso.[e]

[sel Nego_Surrender_sel_03 top]
[s]Me de seu poder.[e]
[s]Mostre-me o dinheiro.[e]
[s][clr 2]De-me as mercadorias.[clr 27][e]
[s]Pantera, voce lida com isso.[e]

[sel Nego_Surrender_sel_04 top]
[s]Me de seu poder.[e]
[s]Mostre-me o dinheiro.[e]
[s][clr 2]De-me as mercadorias.[clr 27][e]
[s]Pantera, voce lida com isso.[e]

[sel Nego_Payfor_sel top]
[s]Eu vou levar.[e]
[s][clr 2]Voce pode fazer melhor do que isso.[clr 27][e]

[sel Nego_Brainwash_sel top]
[s]Envie para mim.[e]
[s]De-me uma doacao.[e]
[s]De-me algo util.[e]
[s]Pantera, voce lida com isso.[e]

[sel TalkSel_Greet_Possesed_B top]
[s]Tudo bem, suponho.[e]
[s]Eu nao pedi isso.[e]

[sel TalkSel_Pre_Question top]
[s]Tudo bem, suponho.[e]
[s]Nao ha necessidade disso.[e]

[msg Talk_tech]
[s]Yoshida Toranosuke[n]Impression Management! (Provisional)[n][w][e]

[sel TalkSel_Tech top]
[s]Por favor ajude...![e]

[msg CharmTech [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 5 301 1]Vamos la, coisas quentes. Voce nao pode ser um[n]um pouco mais gentil comigo?[n][w][e]

[msg CharmActing [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 5 301 1]Nao... como voce poderia tirar isso de nos?[n][w][e]

[msg RareBooster]
[s]Yoshida Toranosuke[n]Impression Management! (Provisional)[n][w][e]

[msg CheapAct [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 5 300 1]Coringa, isso e muito assustador... devemos[n]saia daqui. Ei! Voce poderia dizer[n]Seu chefe que estamos saindo agora?[n][w][e]

[msg TalkMsg_cnt_interruptE]
[s]Um inimigo diferente cortado em[n]a conversa.[n][w][e]

[msg TalkMsg_cnt_interruptP]
[s]Depois de conversar com o Target uma vez,[n]Os membros do partido podem se acelerar[n]things up (percent chance).[n][w][e]

[msg TalkMsg_cnt_refuse]
[s]O alvo se recusou a conversar.[n]→This happens if the result of[n]A conversa e uma recusa.[n][w][e]

[msg TalkMsg_cnt_anger]
[s]Target esta com raiva e contra-ataques.[n]Resultado ruim quando o resultado de[n]A conversa e uma recusa.[n][w][e]

[msg TalkMsg_cnt_unusual]
[s]Incapaz de conversar devido a[n]Efeitos de status.[n][w][e]

[msg TalkMsg_EOF]
[s]......[n][w][e]

[msg DebugMsg_ERROR]
[s](Error) →A variable is set to an invalid value.[n][w][e]

[msg DebugMsg_CHARACTER]
[s](Debug Mode)[n]Tipo de personalidade alvo[n][w][e]

[sel DebugSel_CHARACTER top]
[s]Tipo A.[e]
[s]Tipo B.[e]
[s]Tipo c[e]
[s]Tipo d[e]
[s]Aleatorio[e]

[msg DebugMsg_CHECK_VAR]
[s][var 0].[n][w][e]

[msg DebugMsg_ENEMY_LV]
[s]ID inimigo[var 3][n]Nivel inimigo[var 0][n]Nivel de protag[var 1][n]AI_CHK_ENIDLV_O([var 0], 1) = [var 2][n][w][e]

[msg TalkMsg_GUY_RESULT_GET_P_4 [Ann]]
[s]Nesse caso, vou ajudar[n]o eu dentro de voce. Isso deve ser[n]uma boa experiencia.[n][w][e]

[msg TalkMsg_Coop_AkechiB_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 9 3 301 1]Huh, eu nao diria que e um sabio[n]escolha... talvez voce deva dar[n]isso e um pouco mais de reflexao.[n][w][e]

[msg TalkMsg_Coop_Kasumi_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 11 3 301 1]Pare! Eu acho que voce seria sabio nao[n]fazer movimentos descuidados.[n][w][e]

[msg TalkMsg_Coop_Sumire_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 11 3 301 1]Pare! Eu acho que voce seria sabio nao[n]fazer movimentos descuidados.[n][w][e]

