[msg MSG_BTLTALKSTART01_000_0 [Lavenza]]
[s]Nada mal 悪 Voce conseguiu me tropecar...[n][f 1 3 65535][w][e]

[msg MSG_BTLTALKSTART01_000_0_2 [Lavenza]]
[s]Nada mal 悪 Voce conseguiu me tropecar...[n][f 1 3 65535][w][e]

[msg MSG_BTLTALKSTART01_000_0_3 [Lavenza]]
[s]Nada mal 悪 Voce conseguiu me tropecar...[n][f 1 3 65535][w][e]

[msg MSG_BTLTALKSELECT_000_00 [Lavenza]]
[s]Ficticio[n][f 1 3 65535][w][e]

