[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Essa deve ser a tabela.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][bup 0 8 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Direita. Esse político influente vem aqui.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]... Por que não nos sentamos à mesa ao lado[n]e esperamos por ele?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Eu irei. Ele pode ser guardado se formos em[n]um grande grupo.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Mas não seria estranho com apenas uma garota[n]sentada lá?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Alguém quer vir comigo?[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Vá, crânio.[e]
[s]Vá, Fox.[e]
[s]Eu irei.[e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Essa foi minha intenção desde o início![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Resistir! Eu vou com ela.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][bup 0 5 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Por mim tudo bem.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Segure, Joker! Deixe-me ir com ela![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][bup 0 2 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Quero dizer, cara! É um restaurante![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]O que você é, um pré-escolar!?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][bup 0 6 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 65 65535 0]Eu estava me perguntando por que você estava[n]tão empolgado com isso...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 66 65535 0]*suspirar* [n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Por que alguém não está me pedindo para[n]fazer isso?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][bup 0 6 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Tudo bem, estamos entrando.[n][f 1 3 65535][w][e]

[msg MSG_014_5_0 [Makoto]]
[s][bup 0 6 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Todo mundo fica por perto. Vou dar o sinal[n]quando estiver certo.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Cara, o que devo comer?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Futaba]]
[s][bup 0 8 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Você não pode ficar cheio de comida em um[n]palácio.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Ele é mais burro como sempre...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][bup 0 2 107 65535 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Uhh... eu não consigo ler isso...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Makoto]]
[s][bup 0 6 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]I'll have the sautéed foie gras.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Uma salada enfeitada com trufas... e[n]cordeiro assado, por favor.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][bup 0 2 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Não acredito que você pode pedir tão[n]facilmente assim...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Diga, não é jovem em comparação com os[n]outros aqui? Eles estão todos envolvidos[n]com Shido, sim?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Makoto]]
[s][bup 0 6 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Eles parecem ser figuras importantes nos[n]mundos políticos e financeiros.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Shadow Politician]]
[s][vp 8 0 0 26 65535 0]Sobre a permissão de quem você está sentado[n]lá, pirralhos?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Cujo? Uhh... não vejo sinais reservados ou[n]nada aqui.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Shadow Politician]]
[s][vp 8 0 0 28 65535 0]Seria um incômodo se você fizesse uma[n]raquete ao lado da minha mesa.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 29 65535 0]Eu desejo jantar de lazer. Crianças como[n]você que estão simplesmente com fome devem[n]sair.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 3 301 1][vp 8 0 0 30 65535 0]O que é que foi isso?[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Crânio! Fique quieto.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Ryuji]]
[s][bup 0 2 107 65535 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]S-Sorry...[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Makoto]]
[s][bup 0 6 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Peço desculpas por nossa discourtesia.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Shadow Politician]]
[s][vp 8 0 0 34 65535 0]Se você entende, então vá para casa.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Makoto]]
[s][bup 0 6 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Com licença, mas você pode ser o Sr. Ooe?[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Shadow Politician]]
[s][vp 8 0 0 36 65535 0]De fato, eu sou.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Makoto]]
[s][bup 0 6 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Este será um pedido insolente, mas você nos[n]forneceria uma carta de introdução a... Sr.[n]Shido?[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Shadow Politician]]
[s][vp 8 0 0 38 65535 0]Pela aparência, você parece ser menor. Por[n]que você precisa de uma introdução?[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Makoto]]
[s][bup 0 6 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Desejamos receber uma audiência com ele...[n]Sua ideologia política ressoa muito[n]conosco...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]Claro, o mesmo pode ser dito sobre você, Sr.[n]Ooe.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Shadow Politician]]
[s][vp 8 0 0 41 65535 0]Você tem uma língua prateada para uma tão[n]jovem... não que eu me importe. Você é um[n]estudante do ensino médio?[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Makoto]]
[s][bup 0 6 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Sim senhor.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Shadow Politician]]
[s][vp 8 0 0 43 65535 0]Falando em escolas secundárias... Ouvi dizer[n]que algum diretor em algum lugar chutou o[n]balde.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 44 65535 0]Ele supostamente tentou vazar o nome do Sr.[n]Shido...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Shadow Politician]]
[s][vp 8 0 0 45 65535 0]Se ele simplesmente tivesse obedecido, ele[n]poderia ter permanecido nos escalões[n]superiores. Pensar que ele descartaria tudo[n]isso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 46 65535 0]Uma elite como eu não consegue nem entender[n]por que alguém faria isso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 47 65535 0]Se você promete sua lealdade, recebe a honra[n]de selecionar aqueles que teriam[n]desligamentos mentais.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Makoto]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 6 14 300 1][vp 8 0 0 48 65535 0]Você pediu ao Sr. Shido para desencadear um[n]desligamento mental em alguém também?[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Shadow Politician]]
[s][vp 8 0 0 49 65535 0]HM? Ah, mais ou menos.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Makoto]]
[s][bup 0 6 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]Considerando o seu calibre, eu assumiria que[n]o alvo deve ter sido alguém muito[n]importante.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Shadow Politician]]
[s][vp 8 0 0 51 65535 0]Importante? Não, o próprio alvo não foi nada[n]tão impressionante.[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Makoto]]
[s][bup 0 6 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]Oh, você deve estar sendo modesto...[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Shadow Politician]]
[s][vp 8 0 0 53 65535 0]Você se lembra do acidente do metrô no[n]início da primavera? O que eu tinha como[n]alvo era aquele engenheiro.[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Ryuji]]
[s][bup 0 2 104 65535 0][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]Foi você!?[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Shadow Politician]]
[s][vp 8 0 0 55 65535 0]Era para retirar o presidente de alguma[n]empresa e um diplomata que ficou do lado do[n]governo atual.[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Makoto]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 6 10 300 1][vp 8 0 0 56 65535 0]Entendo... isso foi muito útil, Sr. Ooe.[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Shadow Politician]]
[s][vp 8 0 0 57 65535 0]HM?[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Makoto]]
[s][bup 0 6 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 58 65535 0]Na verdade, minha irmã é promotora no[n]escritório do promotor público.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 59 65535 0]Eu poderia passar o que você acabou de dizer[n]a ela...[n]Que tal isso? Você não vai nos dar uma carta[n]de introdução?[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Shadow Politician]]
[s][vp 8 0 0 60 65535 0]Isso é uma ameaça? Quem são seus dois?[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Makoto]]
[s][bup 0 6 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 61 65535 0]A carta de introdução, por favor.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Shadow Politician]]
[s][vp 8 0 0 62 65535 0]Não fique arrogante, pirralhos! Eu nunca vou[n]te dar um![n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 63 65535 0]Parece que você tem um! Welp, acho que é[n]hora de usar força bruta![n][f 1 3 65535][w][e]

[msg MSG_055_0_0 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 64 65535 0]Rapazes![n][f 1 3 65535][w][e]

