[msg MSG_000_0_0 [Shido]]
[s][bup 0 206 1 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]...Certo. Continuarei a[n]aceitá-los mesmo depois de[n]assumir o cargo de primeiro-ministro.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Deputato Ooe]]
[s][vp 8 0 0 5 65535 0]Assim como eu esperava,[n]Sr. Shido. Você é um homem[n]muito confiável.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Shido]]
[s][bup 0 206 1 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]E, em troca, só peço que continuem a me apoiar.[n]Manter o controle do mundo é caro.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Deputato Ooe]]
[s][vp 8 0 0 6 65535 0]É claro. Vou garantir que ela receba[n]a quantia certa para agradecê-la[n]por sua ajuda com a "limpeza".[n][f 1 3 65535][w][e]
[s][vp 8 0 0 7 65535 0]Aquele incidente na primavera foi[n]muito útil. E o crédito é todo dela, senhor.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Shido]]
[s][bup 0 206 1 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Se os estudos da[n]psi-ciência cognitiva progredirem, acho que[n]poderíamos aumentar seus efeitos.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Deputato Ooe]]
[s][vp 8 0 0 8 65535 0]Hehehe. Desejo-lhe boa sorte[n]em seu empreendimento. Espero que você[n]continue a nos ajudar.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [(SE)獅童 正義]]
[s][vp 8 0 0 4 65535 0](含み笑い)[n][f 1 3 65535][w][e]

