[msg MSG_000_0_0 [Shadow Cleaner]]
[s][vp 8 0 0 1 65535 0]Haha, você punks é difícil! Eu gosto disso![n][f 1 3 65535][w][e]
[s][vp 8 0 0 2 65535 0]Você tem algum backbone. Tudo bem, eu vou te[n]dar minha carta.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Shadow Cleaner]]
[s][vp 8 0 0 3 65535 0]Normalmente eu teria que "limpar" vocês para[n]mexer no navio, mas...[n]Não faz sentido agora.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Você está nos deixando ir?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Shadow Cleaner]]
[s][vp 8 0 0 5 65535 0]Este lugar não vai durar muito mais se[n]soldados poderosos como vocês chegaram aqui.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 6 65535 0]Hora de eu jato. O capitão foi ótimo, mas[n]ele terá que cair apenas com este navio.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 7 65535 0]Veja você mais tarde, Kiddos.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Essa foi uma resposta inesperada para uma[n]criação cognitiva...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Haru]]
[s][bup 0 7 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Os políticos nunca chegam muito perto de[n]suas conexões obscuras. Eles devem ter sido[n]apenas ligados monetariamente.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Deve ser isso.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Bem, finalmente temos todos os cinco.[n]Precisamos usá-los para entrar no salão de[n]montagem principal, certo?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Haru]]
[s][bup 0 7 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Sim, e acredito que será onde encontrarmos o[n]tesouro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Estivemos na maioria dos outros lugares para[n]reunir as cartas- quase não há dúvida sobre[n]isso.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Vamos levar o tesouro dele, não importa o[n]quê![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][bup 0 6 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Como tenho certeza de que todos sabem, a[n]importância desse cartão em particular é[n]diferente de qualquer um que tenha vindo[n]antes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Uma vez que o enviarmos, nossos oponentes[n]saberão que Joker, que presumiam mortos,[n]ainda está vivo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Estaremos colocando nossas costas na parede.[n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Yusuke]]
[s][bup 0 5 105 65535 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Se perdermos, nossas vidas realmente[n]acabarão...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Haru]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Não podemos deixar isso acontecer, podemos!?[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]Definitivamente vamos ganhar.[e]
[s]Será uma batalha difícil.[e]
[s]Hora de retorno.[e]

[msg MSG_016_0_0 [Ryuji]]
[s][bup 0 2 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Isso aí![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Haru]]
[s][bup 0 7 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Faremos isso! A justiça está com os ladrões[n]Phantom![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][bup 0 5 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Sim. Este não é apenas um Phantom Thieves[n]Matter para você. É também um assunto[n]pessoal.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Então está decidido.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Makoto]]
[s][bup 0 6 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]A verdadeira questão é: como e para onde[n]enviamos o cartão de visita?[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Que tal torná-lo super chamativo?[n]Todo o nosso grande plano foi tudo para esse[n]momento, você sabe![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Yusuke]]
[s][bup 0 5 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Na verdade, deve ser feito teatralmente.[n]Um pequeno vazamento só será esmagado pela[n]influência de Shido.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Haru]]
[s][bup 0 7 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Talvez não precise estar em forma de carta[n]desta vez.[n][f 1 3 65535][w][e]

[msg MSG_024_5_0 [Futaba]]
[s][bup 0 8 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Hehe... finalmente é a minha vez de roubar[n]os holofotes.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Makoto]]
[s][bup 0 6 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]...Qual é o problema?[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Futaba]]
[s][bup 0 8 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Heeheehee... não é nada.[n][f 1 3 65535][w][e]

[msg MSG_027_5_0 [Yusuke]]
[s][bup 0 5 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Bem, não há utilidade em pensar sobre isso[n]aqui. Vamos voltar por enquanto.[n][f 1 3 65535][w][e]

