[msg MND_000_0_0]
[s][vp 1 0 0 0 0 0]......[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Onde estou...?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ei...[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Café ok?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Homem de terno e gravata]]
[s][vp 8 0 0 3 65535 0][f 4 3].[n]Esse é o seu nome, certo?[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Exatamente.[e]
[s]E aí?[e]

[msg MSG_004_0_0 [Homem de terno e gravata]]
[s][vp 8 0 0 4 65535 0]...Parabéns.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 5 65535 0]Você foi escolhido pelo deus.[n]Portanto, iremos protegê-lo[n]não importa o que aconteça.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Homem de terno e gravata]]
[s][vp 8 0 0 6 65535 0]De agora em diante, você será um presidiário.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 7 65535 0]Você fez a escolha certa.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]Concordo.[e]
[s]O que ele está dizendo?[e]

[msg MSG_007_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Eu gostaria de poder me tornar[n]um prisioneiro também...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Homem de terno e gravata]]
[s][vp 8 0 0 9 65535 0]Bem... agora você virá conosco.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 10 65535 0]Afinal, a humanidade cairá em[n]ruínas em pouco tempo.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]*suspiro* Já estamos arruinados...[n][f 1 3 65535][w][e]

