[msg MSG_000_2_0 [Panicking Man]]
[s][vp 8 0 0 2 13 0]D-doa alguém sabe onde está meu amigo!?[n]Ele estava ao meu lado...[n][f 1 3 65535][w][e]

[msg MSG_000_7_0 [Flustered Woman]]
[s][vp 8 0 0 4 15 0]Não! Uma pessoa desapareceu bem na frente[n]dos meus olhos![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Middle-Aged Businessman]]
[s][vp 8 0 0 1 11 0]P-Por favor, salve-nos! Alguém! Alguém![n][f 1 3 65535][w][e]

