[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 4 3 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]...Sério?!?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][bup 0 6 0 3 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Agora que sabemos o nome, tudo o que precisamos é[n]de um endereço.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 0 3 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Você tem razão. Trabalhando todos[n]juntos, teremos sucesso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Minha irmã ainda não me avisou, mas acho que ela[n]está estudando todas as soluções possíveis.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]E eu também.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 1 3 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]...Obrigado. Dê meus cumprimentos a Shiho-san.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 0 3 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Oh, seria possível ter a ajuda deles também?[n]Tenho certeza de que eles ficarão felizes em[n]ajudar.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][bup 0 6 1 3 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]...Isso seria ótimo.[n]Ok, vou deixar isso para você.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][bup 0 6 0 3 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]...Mm-hm. Até amanhã.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Temos que salvá-lo. A qualquer custo.[n][f 1 3 65535][w][e]

