[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Oi.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Você conseguiu tudo?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Quando acolhi você, pensei[n]que estava fazendo um favor a você...[n]mas, em vez disso, foi o contrário.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]...Cuide-se.[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Você também.[e]
[s]Vou me sentir sozinho sem você.[e]
[s]Finalmente livre.[e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Não seja tão atrevido.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Pare com isso. Prefiro ouvir[n]essas coisas de uma mulher.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Muito duro da sua parte.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Ah, desculpe... Eu queria[n]Futaba para dizer olá também...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Mas não consegui encontrá-lo desde esta manhã.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]O mesmo vale para o gato...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Se você estiver na cidade novamente,[n]apareça. Vou comprar para você[n]uma boa xícara de café.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]...Espere, isso significa que[n]não poderei fechar o clube...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Bem, o que você está fazendo?[n]Vá, se apresse.[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]Eu sou muito grato a você.[e]
[s]Obrigado por tudo.[e]

[msg MSG_013_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]...Sim.[n][f 1 3 65535][w][e]

