[msg MSG_000_0_0 [Newscaster]]
[s][vp 8 0 0 1 65535 0]... em outras notícias.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 2 65535 0]A polícia retirou oficialmente o mandado de[n]prisão nos ladrões Phantom...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 3 65535 0]Além de pedir desculpas por aqueles que[n]lideraram a investigação, citando que eram[n]inadequados para a tarefa.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 4 65535 0]Devido a uma mudança drástica na política,[n]especula-se que eles também tenham mudado[n]de coração...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Businessman]]
[s][vp 8 0 0 5 65535 0]Então a polícia estava errada, afinal.[n]Eles são os que devem estar fazendo coisas[n]obscuras.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Young Businesswoman]]
[s][vp 8 0 0 6 65535 0]Não há como os ladrões fantasmas podem ser[n]maus...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Newscaster]]
[s][vp 8 0 0 7 65535 0]As ações dos ladrões fantasmas não mostram[n]sinais de parar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 8 65535 0]A mudança de relatórios policiais do coração[n]já superou cem casos.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Surprised Male Student]]
[s][vp 8 0 0 9 65535 0]Apenas cem? Eu pensei que já teria sido o[n]dobro disso.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Happy Male Student]]
[s][vp 8 0 0 10 65535 0]Sim, eu sei o que quer dizer. Vemos notícias[n]sobre eles todos os dias.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Newscaster]]
[s][vp 8 0 0 11 65535 0]Enquanto isso, há relatos de que a taxa de[n]crimes e suicídios está diminuindo- [n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Female Pedestrian]]
[s][vp 8 0 0 12 65535 0]As coisas vão ficar bem? Nosso filho vai[n]nascer em breve...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Male Pedestrian]]
[s][vp 8 0 0 13 65535 0]Significa apenas que mais casos estão sendo[n]expostos graças aos ladrões Phantom.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 14 65535 0]Não se preocupe. Tenho certeza de que eles[n]farão algo sobre tudo isso.[n][f 1 3 65535][w][e]

