[msg MSG_000_0_0 [Girl's Voice]]
[s][vp 8 0 0 0 65535 0]Você deve ser capaz de sair dessa maneira![n]Pressa![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Young Man's Voice]]
[s][vp 8 0 0 0 65535 0]Cara, ele pode até nos ouvir!?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Girl's Voice]]
[s][vp 8 0 0 0 65535 0]Não se preocupe, estou pegando as vozes de[n]todos. Apenas vá, Joker![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Young Woman's Voice]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]HM? Espere um segundo![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Young Woman's Voice]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O que- estou recebendo uma leitura estranha[n]em seu caminho![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vamos, corra![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Young Woman's Voice]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O que você está fazendo!? Não há tempo para[n]dobrar de volta![n][f 1 3 65535][w][e]

