[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]A viagem escolar está finalmente chegando ao[n]fim...[n][f 1 3 65535][w][e]
[s][bup 0 6 1 1 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Eu nunca pensei que teria a chance de ir em[n]um este ano também...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 3 1 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Mas nem parecia que eu estava fora do país.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 0 1 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Até Yusuke apareceu.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Estou simplesmente feliz que a tempestade[n]não tenha chegado aqui...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Pode não ter sido a viagem mais emocionante,[n]mas ainda nos divertimos.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 3 1 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Honestamente, sou grato por não termos que[n]lidar com a tempestade. Eles realmente são[n]terríveis...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Então, o que você acabou fazendo ontem?[n]Você está com segredos de mim? Isso é contra[n]o código BRO![n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]Não estou dizendo.[e]
[s]Foi para a praia.[e]
[s]Eu estava com alguém.[e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 5 1 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]O que!? Isso parece muito desconfiado para[n]mim...[n][f 1 3 65535][w][e]
[s][bup 0 2 7 1 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Eu não vou continuar fazendo Pryin '.[n]A última coisa que eu preciso é o seu amante[n]secreto vindo depois de mim com um machado.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 2 1 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]O que, sozinho? De jeito nenhum eu vou[n]acreditar nisso![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 3 1 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]O desespero em sua cara é bastante[n]impróprio, Ryuji.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 4 1 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Cara, de verdade!?[n][f 1 3 65535][w][e]
[s][bup 0 2 7 1 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]... na verdade, não diga nada. A última[n]coisa que eu preciso é o seu amante secreto[n]vindo depois de mim com um machado.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Isso é o suficiente, pessoal.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ann]]
[s][bup 0 4 0 1 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Parecia que essa viagem passou em um flash.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Não tenho certeza se quero ir para casa ou[n]ficar aqui mais tempo neste momento...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Ei, por que não compramos lembranças juntas[n]antes de chegar?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ann]]
[s][bup 0 4 1 1 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Ooh, conte comigo![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Yusuke]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Permita-me me juntar a você também...[n]Embora eu não tenha fundos para lembranças.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Makoto]]
[s][bup 0 6 3 1 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Você poderá voltar ao Japão... certo?[n][f 1 3 65535][w][e]

