[msg MSG_000_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Está ficando bem frio, né?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Desculpe por ter feito você subir aqui. Não é[n]algo que você possa discutir entre as pessoas.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0][f 4 1]-senpai, você ainda pretende[n]continuar sua[n]missão com os Phantom Thieves?[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]O que você quer dizer?[e]
[s]Por que você pergunta?[e]

[msg MSG_004_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]...Ultimamente, o tempo todo[n]falar mal é sobre os Phantom[n]Thieves.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Embora existam muitos que acreditam[n]em sua causa...enquanto[n]sabem nada sobre você...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Mais e mais pessoas estão[n]falando sobre os Phantom Thieves![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Eu sei que não cabe a mim dizer,[n]já que também recusei[n]a oferta de acompanhá-lo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Mas essa mudança de atitude[n]é simplesmente terrível.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Eles estão fazendo com você exatamente[n]o que fizeram comigo...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]No entanto, você continua implacável em[n]seu caminho... Por que, senpai?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Eu tenho que cuidar de algo.[e]
[s]Há algo para terminar.[e]

[msg MSG_009_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Cuide de uma coisa...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Hum. Eu entendo...[n][f 1 3 65535][w][e]

[msg MSG_009_5_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Questões pendentes?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Então você ainda tem algo[n]para terminar.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Sim...[n][f 1 3 65535][w][e]

[msg MSG_010_3_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Mas não se preocupe conosco![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Não há nem mesmo uma chance em um milhão de que[n]meu Phantom Thieves falhe![n][f 1 3 65535][w][e]

[msg MSG_010_5_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]Eu entendo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]Bem, eu não estou segurando você.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Mas... posso te pedir um favor?[n]Ou melhor, você pode me prometer[n]uma coisa?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Quando as coisas se acalmarem,[n]eu gostaria que fôssemos a algum lugar[n]nos divertirmos juntos.[n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]Eu prometo.[e]
[s]Eu olho para a frente.[e]
[s]Acho que não consigo...[e]

[msg MSG_014_0_0 [Kasumi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 11 1 300 1][vp 8 0 0 15 65535 0]Negócio, então![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Eu também.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Não diga certas coisas,[n]nem mesmo em tom de brincadeira.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Já estou começando a contar os[n]dias até esse momento.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Então... Tenha cuidado.[n][f 1 3 65535][w][e]

[msg MSG_021_5_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Ah, e também pretendo cumprir[n]a outra promessa que fiz a você,[n]sobre treinamento físico.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Talvez amanhã... ou é muito cedo?[n]Talvez seja melhor treinarmos[n]depois de amanhã, hein?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Ah, mas esse é o dia em que...[n][f 1 3 65535][w][e]

[sel SEL_023_0_0 top]
[s]Talvez outra hora.[e]
[s]Outro dia seria melhor.[e]

[msg MSG_024_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Hum. Eu entendo.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 30 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Ah! Ainda não almocei![n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Vamos, [f 4 1]-senpai![n]Você tem que comer também![n][f 1 3 65535][w][e]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 41 5 100][vp 8 0 0 33 65535 0]Você não pode vencer uma[n]luta com o estômago vazio![n][f 1 3 65535][w][e]

