[msg MSG_000_0_0 [Diretor]]
[s][bup 0 204 2 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Vou dizer de novo, só para ficar[n]claro: você será expulso instantaneamente[n]se bagunçar as coisas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Você é apenas um fardo, na minha opinião,[n]mas era necessário levar[n]certos fatores em conta...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Você pode ter se safado do que[n]fez no passado,[n]mas esses dias acabaram.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Se você for expulso da[n]escola, ninguém mais vai[n]aceitá-lo. Tenha isso em mente.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Diretor]]
[s][bup 0 204 0 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Este é o professor responsável[n]pela sua turma.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Eu sou Sadayo Kawakami.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Aqui está sua carteira de estudante.[n][f 1 3 65535][w][e]

[msg MND_002_5_0]
[s][vp 8 0 0 0 65535 0]......?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Leia as regras.[n]Qualquer violação o enviará[n]diretamente para o escritório do consultor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]E se por acaso você causar[n]problemas, não poderei[n]protegê-lo de forma alguma.[n][f 1 3 65535][w][e]

[msg MSG_003_5_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]...Eu tenho sua palavra sobre isso,[n]certo, Diretor Kobayakawa?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Diretor]]
[s][bup 0 204 0 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Ele é o único responsável[n]por suas ações.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Sim, mas por que eu...?[n]Deve ter tido alguns[n]candidatos melhores.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Diretor]]
[s][bup 0 204 3 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Foi uma[n]transferência repentina, e sua turma era[n]a única com vaga disponível.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sojiro]]
[s][bup 0 103 503 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Se você explicou tudo para nós,[n]você se importa se formos?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Tenho um clube para administrar.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Diretor]]
[s][bup 0 204 2 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Sakura-san, por favor[n]fique de olho nele.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Não o faça criar[n]nenhum problema quando ele estiver fora...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Bem, eu definitivamente vou dar a ele um bom[n]discurso sobre a situação[n]em que ele está.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [(SE)川上 貞代]]
[s][vp 8 0 0 19 65535 0](ため息)[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Venha para a sala dos professores amanhã,[n]assim que chegar à escola.[n]Eu acompanho você até a aula.[n][f 1 3 65535][w][e]

