[msg TEST_000]
[s][vp 8 0 0 0 65535 0]スクリプトから発行した[n]メッセージです。[n][f 1 3 65535][w][e]

[msg THINK_START_0_00 [Biology]]
[s][vp 8 0 0 0 65535 0]What is the reason people will see[n]the same thing differently?[n][f 1 3 65535][w][e]

[msg THINK_START_1_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]If how they're seeing things is different,[n]it probably has to do with this kind of[n]information...[n][f 1 3 65535][w][e]

[sel THINK_1_SEL_00 top]
[s]Auditory information.[e]
[s]Personal information.[e]
[s]Visual information.[e]

[msg THINK_1A_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Wait. We're talking about them seeing[n]things differently. Is that really right?[n][f 1 3 65535][w][e]

[msg THINK_1B_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Wait. We're talking about them seeing[n]things differently. Is that really right?[n][f 1 3 65535][w][e]

[msg THINK_1C_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Right. How you see something is visual[n]information.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]What takes the visual information from[n]your eyes and processes it is the, uh...[n][f 1 3 65535][w][e]

[sel THINK_2_SEL_00 top]
[s]Brain.[e]
[s]Stomach.[e]
[s]Marrow.[e]

[msg THINK_2A_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Right.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]The brain processes visual information.[n]So, the reason why people see things[n]differently is...[n][f 1 3 65535][w][e]

[msg THINK_2B_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]That's not right... is it?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I think you'd better rethink this one.[n][f 1 3 65535][w][e]

[msg THINK_2C_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]That's not right... is it?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I think you'd better rethink this one.[n][f 1 3 65535][w][e]

[sel THINK_3_SEL_00 top]
[s]They have different cognitions.[e]
[s]Their visual acuity.[e]
[s]How accurate the printout is.[e]

[msg THINK_3A_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]"How the brain interprets the same[n]visual data—how one perceives the[n]world—differs from person to person."[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Ooh, this sounds pretty good![n][f 1 3 65535][w][e]

[msg THINK_3B_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]...Is that really right?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Try thinking it through again.[n][f 1 3 65535][w][e]

[msg THINK_3C_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]...Is that really right?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Try thinking it through again.[n][f 1 3 65535][w][e]

[msg MISS_LAST_ALL_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1170 65535 0]Mm, I don't think that's it...[n][f 1 3 65535][w][e]

[msg THINK_START_0_01 [History]]
[s][vp 8 0 0 0 65535 0]Why did Ishikawa Goemon become[n]a popular subject after his death?[n][f 1 3 65535][w][e]

[msg THINK_START_1_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Goemon was popular because he wasn't[n]just a thief. He was a...[n][f 1 3 65535][w][e]

[sel THINK_1_SEL_01 top]
[s]Hottie.[e]
[s]Gentleman thief.[e]
[s]Vice-shogun.[e]

[msg THINK_1A_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Come on! Think it through again.[n][f 1 3 65535][w][e]

[msg THINK_1B_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Stealing from the rich and giving to the[n]poor—yup, that's Goemon all right.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]And, the person in power who had it in[n]for Goemon was...[n][f 1 3 65535][w][e]

[msg THINK_1C_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]That's not right, is it? Think it through[n]again.[n][f 1 3 65535][w][e]

[sel THINK_2_SEL_01 top]
[s]Oda Nobunaga.[e]
[s]Toyotomi Hideyoshi.[e]
[s]Tokugawa Ieyasu.[e]

[msg THINK_2A_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]That's not right, is it? Think it through[n]again.[n][f 1 3 65535][w][e]

[msg THINK_2B_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Yeah, Hideyoshi was the most powerful[n]figure during the Sengoku period.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]And, Goemon's death after he got[n]captured by Hideyoshi is famous too...[n][f 1 3 65535][w][e]

[msg THINK_2C_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]That's not right, is it? Think it through[n]again.[n][f 1 3 65535][w][e]

[sel THINK_3_SEL_01 top]
[s]He was boiled alive.[e]
[s]He was forced to swallow needles.[e]
[s]He was skinned.[e]

[msg THINK_3A_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Yeah! We even have the term[n]"Goemon bath" because of it![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]"Goemon fought against those in power[n]and was executed for it. After his death,[n]he was seen as a hero."[n][f 1 3 65535][w][e]

[msg THINK_3B_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]No. I think there was some well-known[n]phrase associated with it. Try thinking it[n]over again.[n][f 1 3 65535][w][e]

[msg THINK_3C_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]No. I think there was some well-known[n]phrase associated with it. Try thinking it[n]over again.[n][f 1 3 65535][w][e]

[msg THINK_START_0_02 [History]]
[s][vp 8 0 0 0 65535 0]Explain why the guillotine was used[n]during the French Revolution.[n][f 1 3 65535][w][e]

[msg THINK_START_1_02 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]First of all, who proposed the idea of[n]the guillotine?[n][f 1 3 65535][w][e]

[sel THINK_1_SEL_02 top]
[s]An executioner.[e]
[s]A doctor.[e]
[s]The king.[e]

[msg THINK_1A_02 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Hmmm... I don't think that's right...[n]Let's try this again.[n][f 1 3 65535][w][e]

[msg THINK_1B_02 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Yeah! I think he was named Joseph-[n]Ignace Guillotin.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]So, from his perspective, what was[n]the advantage of the guillotine?[n][f 1 3 65535][w][e]

[msg THINK_1C_02 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Hmmm... I don't think that's right...[n]Let's try this again.[n][f 1 3 65535][w][e]

[sel THINK_2_SEL_02 top]
[s]It'd entertain the masses.[e]
[s]It could execute people quickly.[e]
[s]He'd get bodies to dissect.[e]

[msg THINK_2A_02 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Really? Try thinking it through again.[n][f 1 3 65535][w][e]

[msg THINK_2B_02 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]There were thousands of people[n]executed during the Revolution...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Looks like... "they needed a method of[n]execution that was quick and impartial."[n][f 1 3 65535][w][e]

[msg THINK_2C_02 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]You don't need to chop their head off[n]to be able to dissect them. Try thinking[n]it through again.[n][f 1 3 65535][w][e]

[msg THINK_START_0_03 [Biology]]
[s][vp 8 0 0 0 65535 0]Describe how sounds are played[n]through a cell phone.[n][f 1 3 65535][w][e]

[msg THINK_START_1_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]I think they said the voice you hear[n]through the phone is...[n][f 1 3 65535][w][e]

[sel THINK_1_SEL_03 top]
[s]Their real voice.[e]
[s]Their voice pitched up.[e]
[s]Not their real voice.[e]

[msg THINK_1A_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Really? I don't think that was it...[n][f 1 3 65535][w][e]

[msg THINK_1B_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Really? I don't think that was it...[n][f 1 3 65535][w][e]

[msg THINK_1C_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]There would be too much data to[n]transmit, so it just plays a sound[n]similar to your voice, I think.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]But why does the listener think the[n]synthetic voice is the real person?[n][f 1 3 65535][w][e]

[sel THINK_2_SEL_03 top]
[s]They speak the same.[e]
[s]Humans have bad hearing.[e]
[s]They can sense their aura.[e]

[msg THINK_2A_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Yeah. Everyone talks their own way:[n]their tone, how they stress words,[n]and so on.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Even if the voice is different, as long[n]as they talk the same, the listener will[n]subconsciously...[n][f 1 3 65535][w][e]

[msg THINK_2B_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Really? C'mon, be serious.[n][f 1 3 65535][w][e]

[msg THINK_2C_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Really? C'mon, be serious.[n][f 1 3 65535][w][e]

[sel THINK_3_SEL_03 top]
[s]Nod along.[e]
[s]Supplement the voice.[e]
[s]Tap their foot.[e]

[msg THINK_3A_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Absolutely— I mean, no! Calm down,[n]and let's think this through.[n][f 1 3 65535][w][e]

[msg THINK_3B_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]That's it![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]"Even if the sound differs from the[n]actual voice, the listener's brain[n]will make it sound like their voice."[n][f 1 3 65535][w][e]

[msg THINK_3C_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Absolutely— I mean, no! Calm down,[n]and let's think this through.[n][f 1 3 65535][w][e]

[msg THINK_START_0512_00 [History]]
[s][vp 8 0 0 0 65535 0]Provide the reason why Minamoto no[n]Yoshitsune is viewed as a hero.[n][f 1 3 65535][w][e]

[msg THINK_START_0512_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Yoshitsune had a brother, right? Uh,[n]I think his name was...[n][f 1 3 65535][w][e]

[sel THINK_1_SEL_0512_02 top]
[s]Fujiwara no Hidehira.[e]
[s]Kiso Yoshinaka.[e]
[s]Minamoto no Yoritomo.[e]

[msg THINK_1A_0512_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]Was that his name...?[n][f 1 3 65535][w][e]

[msg MISS_1A_0512_03_ADD [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Yoshitsune's brother's really famous too,[n]isn't he? I think his name was...[n][f 1 3 65535][w][e]

[msg THINK_1B_0512_04 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]Was that his name...?[n][f 1 3 65535][w][e]

[msg THINK_1C_0512_05 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Yeah, that's the one.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Yoshitsune worked under Yoritomo.[n]He did a lot for his brother.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]But they ended up coming into conflict.[n]And in the end, when they had to[n]oppose each other...[n][f 1 3 65535][w][e]

[sel THINK_2_SEL_0512_06 top]
[s]Yoritomo won.[e]
[s]They both lost.[e]
[s]Yoshitsune won.[e]

[msg THINK_2A_0512_07 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Yeah. Yoshitsune committed suicide after[n]being exiled by his brother.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]But even though he lost, Yoshitsune's[n]the one who went down in history[n]as a hero.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]That's probably because people tend to[n]sympathize less with figures in power,[n]and sympathize more with...[n][f 1 3 65535][w][e]

[msg THINK_2B_0512_08 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]No, I don't think so.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I think you'd better reconsider this...[n][f 1 3 65535][w][e]

[msg THINK_2C_0512_09 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]No, I don't think so.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I think you'd better reconsider this...[n][f 1 3 65535][w][e]

[msg MISS_2A_0512_09_ADD [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Uh, the idea is to explain why he's[n]viewed as a hero...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Yoshitsune had a brother, right? I think[n]his name was...[n][f 1 3 65535][w][e]

[sel THINK_3_SEL_0512_10 top]
[s]The weak.[e]
[s]The vengeful.[e]
[s]The crafty.[e]

[msg THINK_3A_0512_11 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Yeah. Not just any weak person, though.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]People love rooting for an underdog[n]who stands up to powerful oppressors.[n]And Yoshitsune did that to his brother.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]So the reason Yoshitsune is treated as a[n]hero is because he stood up against[n]the powerful Yoritomo![n][f 1 3 65535][w][e]

[msg THINK_3B_0512_12 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]Really!?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Try thinking it through again.[n][f 1 3 65535][w][e]

[msg THINK_3B_0512_12_ADD [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Uh, the idea is to explain why he's[n]viewed as a hero...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Yoshitsune had a brother, right? I think[n]his name was...[n][f 1 3 65535][w][e]

[msg THINK_3C_0512_13 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]Really!?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Try thinking it through again.[n][f 1 3 65535][w][e]

[msg THINK_START_0713_00 [History]]
[s][vp 8 0 0 0 65535 0]Explain the origin of baozi.[n][f 1 3 65535][w][e]

[msg THINK_START_0713_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Ugh. Baozi, in this hot weather...? Well,[n]never mind.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I think this came up in class. They were[n]invented by that famous guy from[n]Romance of the Three Kingdoms, right?[n][f 1 3 65535][w][e]

[sel THINK_1_SEL_0713_02 top]
[s]Lu Su.[e]
[s]Zhuge Liang.[e]
[s]Cao Cao.[e]

[msg THINK_1A_0713_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]Was that really it...? I don't think so.[n][f 1 3 65535][w][e]

[msg MISS_1A_0713_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Let's start with the guy who invented[n]baozi. It's... you know, that guy from[n]Romance of the Three Kingdoms...[n][f 1 3 65535][w][e]

[msg THINK_1B_0713_04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yeah. The strategist of Shu.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I think the story was about a river[n]overflowing somewhere Zhuge Liang[n]visited.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]And they were offering something to[n]quell the river...[n][f 1 3 65535][w][e]

[msg THINK_1C_0713_05 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]Was that really it...? I don't think so.[n][f 1 3 65535][w][e]

[sel THINK_2_SEL_0713_06 top]
[s]Travelers' hearts.[e]
[s]Barbarians' heads.[e]
[s]Barbarians' skulls.[e]

[msg THINK_2A_0713_07 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]Is that right? Think about it again.[n][f 1 3 65535][w][e]

[msg THINK_2B_0713_08 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]That's it. A crazy story...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]And that's how he came up with the[n]baozi, right?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]This master strategist came up with[n]the baozi to...[n][f 1 3 65535][w][e]

[msg THINK_2C_0713_09 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]Is that right? Think about it again.[n][f 1 3 65535][w][e]

[sel THINK_3_SEL_0713_10 top]
[s]To offer them instead of heads.[e]
[s]To offer with the heads.[e]
[s]To feed the survivors.[e]

[msg THINK_3A_0713_11 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Yeah. I think you're right.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]The baozi were invented as an offering[n]to a river spirit, to replace the tradition[n]of offering severed heads![n][f 1 3 65535][w][e]

[msg THINK_3B_0713_12 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]I don't think that's it... Maybe we should[n]think a little harder.[n][f 1 3 65535][w][e]

[msg THINK_3C_0713_13 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]I don't think that's it... Maybe we should[n]think a little harder.[n][f 1 3 65535][w][e]

[msg MISS_2A_0713_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Uhh... So the question's about the[n]origin of baozi.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I think we learned this in class, right?[n]Someone from the Romance of the[n]Three Kingdoms invented it...[n][f 1 3 65535][w][e]

[msg THINK_START_1017_00 [Math]]
[s][vp 8 0 0 0 65535 0]Provide an explanation for why the[n]soccer ball is only comprised of the[n]colors black and white.[n][f 1 3 65535][w][e]

[msg THINK_START_1017_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Soccer balls...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Didn't the teacher say that the number[n]of colors used to be different? Do you[n]remember?[n][f 1 3 65535][w][e]

[sel THINK_1_SEL_1017_02 top]
[s]It used to be flashier.[e]
[s]It used to be one color.[e]
[s]It used to be three colors.[e]

[msg THINK_1A_1017_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]No, I don't think so.[n][f 1 3 65535][w][e]

[msg MISS_1A_1017_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Something was different about the old[n]soccer balls, right?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]...Um, what was it? I think the teacher[n]said this in class... Do you remember?[n][f 1 3 65535][w][e]

[msg THINK_1B_01017_04 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Right, it was only one color. But that[n]wouldn't really grab your eye.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Oh yeah, I remember. I think she said[n]that unlike now, soccer games were[n]broadcasted with...[n][f 1 3 65535][w][e]

[msg THINK_1C_1017_05 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]No, it was less than that.[n][f 1 3 65535][w][e]

[sel THINK_2_SEL_1017_06 top]
[s]No commentary.[e]
[s]Black and white picture.[e]
[s]No visuals.[e]

[msg THINK_2A_1017_07 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]Really? Let's think it over again.[n][f 1 3 65535][w][e]

[msg MISS_2A_1017_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]The question here is: Why are soccer[n]balls colored with black and white[n]only? That's it, right?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Didn't the teacher say that the number[n]of colors used to be different? Do you[n]remember?[n][f 1 3 65535][w][e]

[msg THINK_2B_1017_08 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Right. A single-colored ball would be[n]hard to spot in black and white.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]So they changed the color of the ball[n]to make it easily identifiable on TV.[n][f 1 3 65535][w][e]

[msg THINK_2C_1017_09 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]Was that what we learned in class?[n]Let's think it over.[n][f 1 3 65535][w][e]

[msg THINK_START_1220_00 [History]]
[s][vp 8 0 0 0 65535 0]Explain why the infamous thief[n]Nezumi Kozo had makeup applied[n]to him before his execution.[n][f 1 3 65535][w][e]

[msg THINK_START_1220_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]He was a really famous thief in the[n]Edo period, right? How much money[n]did he steal, in the end?[n][f 1 3 65535][w][e]

[sel THINK_1_SEL_1220_02 top]
[s]About 300,000 yen.[e]
[s]Around 100 million yen.[e]
[s]Over one billion yen.[e]

[msg THINK_1A_1220_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]Hmm... I don't think that's right.[n][f 1 3 65535][w][e]

[msg MISS_1A_1220_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Nezumi Kozo was one of the greatest[n]thieves of the Edo period. I think the[n]damage amounted to...[n][f 1 3 65535][w][e]

[msg MISS_2A_1220_00 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]The question is "why did Nezumi Kozo[n]have makeup applied to him"?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Nezumi Kozo was one of the greatest[n]thieves of the Edo period. I think the[n]damage amounted to...[n][f 1 3 65535][w][e]

[msg THINK_1B_1220_04 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]Hmm... I don't think that's right.[n][f 1 3 65535][w][e]

[msg THINK_1C_1220_05 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]That's right. But he was caught in the[n]end.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]As a result, he was sentenced to...[n][f 1 3 65535][w][e]

[sel THINK_2_SEL_1220_06 top]
[s]Having his head displayed.[e]
[s]Death by sawing.[e]
[s]Seppuku.[e]

[msg THINK_2A_1220_07 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Yeah, he was paraded around town and[n]then had his head displayed.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]It sounds harsh, but it had a certain[n]significance back then, right?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Criminals, especially famous criminals,[n]were mostly paraded around for...[n][f 1 3 65535][w][e]

[msg THINK_2B_1220_08 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]Was that really it? Let's think it over.[n][f 1 3 65535][w][e]

[msg THINK_2C_1220_09 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]That's more of a warrior thing... Let's[n]rethink this.[n][f 1 3 65535][w][e]

[sel THINK_3_SEL_1220_10 top]
[s]Ritual purposes.[e]
[s]Public performance.[e]
[s]Racing them.[e]

[msg THINK_3A_1220_11 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]Is that really it...? Let's think about it[n]more.[n][f 1 3 65535][w][e]

[msg THINK_3B_1220_12 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]...Oh, that sounds familiar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]The people wouldn't have been happy[n]if he looked shabby for his death.[n]Things were brutal back then...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Even condemned criminals had to be[n]prettied up for a crowd.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]So the reason Nezumi Kozo had makeup[n]was to appease the people![n][f 1 3 65535][w][e]

[msg THINK_3C_1220_13 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 3 0 0][f 4 10 65535 0 0]No, that's not it... Let's calm down and[n]think it over.[n][f 1 3 65535][w][e]

[msg THINK_START_0228_00 [Biology]]
[s][vp 8 0 0 0 65535 0]Explain how to dye hair gold[n]by using metal.[n][f 1 3 65535][w][e]

[msg THINK_START_0228_01 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Well, this question's... imaginative...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Do you remember what melts metal?[n][f 1 3 65535][w][e]

[sel THINK_1_SEL_0228_02 top]
[s]Tea.[e]
[s]Acid.[e]
[s]Alkali.[e]

[msg THINK_1A_0228_03 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Uh, I don't think so.[n][f 1 3 65535][w][e]

[msg THINK_1B_0228_04 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Yeah, acid melts most things.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]So if you melt gold with acid, and use[n]that to dye your hair, would your hair[n]turn golden...?[n][f 1 3 65535][w][e]

[msg THINK_1C_0228_05 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]No, that's not it.[n][f 1 3 65535][w][e]

[sel THINK_2_SEL_0228_06 top]
[s]It would turn blue.[e]
[s]It will turn gold.[e]
[s]It won't turn gold.[e]

[msg THINK_2A_0228_07 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]I don't think that's it... Let's think about[n]this again.[n][f 1 3 65535][w][e]

[msg THINK_2B_00228_08 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Oh, wait...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Acid doesn't melt gold. So melting gold[n]isn't gonna work here.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]But we could theoretically use acid to[n]melt a metal with a color similar to[n]gold. Which would be...[n][f 1 3 65535][w][e]

[msg THINK_2C_0228_09 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]I don't think that's it... Let's think about[n]this again.[n][f 1 3 65535][w][e]

[sel THINK_3_SEL_0228_10 top]
[s]Brass.[e]
[s]Iron.[e]
[s]Silver.[e]

[msg THINK_3A_0228_11 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]No, that's not it. Calm down and think[n]about it again.[n][f 1 3 65535][w][e]

[msg THINK_3B_0228_12 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Yeah, that's it! All right, now we have[n]our answer.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]To dye your hair gold, you would melt[n]brass with acid, and douse your hair[n]in it![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]...Though that seems like an easy way[n]to make yourself sick.[n][f 1 3 65535][w][e]

[msg THINK_3C_0228_13 [Morgana]]
[s][vp 8 0 0 0 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]No, I don't think that's it. Calm down[n]and think through it again.[n][f 1 3 65535][w][e]

