[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0]Huh...? Who could that be at this hour?[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]It seems I have other[n]messages as well...[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_SETUP_HARAJ [Morgana]]
[s][bup 0 3 0 0 0]Aren't we supposed to be going[n]to Harajuku with Mishima? Let's[n]go meet up with him.[n][w][e]

[msg MSG_MORUGANA_SETUP_MEIJI [Morgana]]
[s][bup 0 3 0 0 0]We're supposed to be going to[n]Meiji Shrine with Lady Ann, right?[n][w][e]
[s]We can't let her wait.[n]Let's get out of here already.[n][w][e]

[msg MSG_MORUGANA_SETUP_IKEBU [Morgana]]
[s][bup 0 3 0 0 0]Didn't we promise Mishima we'd[n]go to the planetarium with him?[n][w][e]
[s]Let's start heading to Ikebukuro.[n][w][e]

[msg MSG_MORUGANA_SETUP_ICHIG [Morgana]]
[s][bup 0 3 0 0 0]Didn't we promise Ryuji we'd go[n]fishing with him in Ichigaya?[n][w][e]
[s]I'm excited for this fishing pond...[n]Come on, let's head out.[n][w][e]

[msg MSG_MORUGANA_SETUP_JINBO [Morgana]]
[s][bup 0 3 0 0 0]We're going to go look for old books[n]with Makoto in Jinbocho today, right?[n][w][e]
[s]Let's go. I'm sure she's waiting.[n][w][e]

[msg MSG_MORUGANA_SETUP_AKIHA [Morgana]]
[s][bup 0 3 0 0 0]We promised Hifumi we'd check[n]out the electronics store in[n]Akihabara with her today, huh?[n][w][e]
[s]Come on, let's go see what[n]the latest technology is.[n][w][e]

[msg MSG_MORUGANA_SETUP_SUIDO [Morgana]]
[s][bup 0 3 0 0 0]We're taking Mishima over[n]to Dome Town, right?[n][w][e]
[s]It's weird that we're going to[n]an amusement park with him... but[n]let's just go have some fun.[n][w][e]

[msg MSG_MORUGANA_SETUP_ASAKU [Morgana]]
[s][bup 0 3 0 0 0]We're going to Nakamise Street[n]with Haru, right? I hear it's[n]super crowded from the festival...[n][w][e]
[s]But I'm definitely excited for it![n]Stop standing around and let's go![n][w][e]

[msg MSG_MORUGANA_SETUP_SHINA [Morgana]]
[s][bup 0 3 0 0 0]Aren't we supposed to be going[n]to the aquarium with Akechi?[n]Let's go meet up with him.[n][w][e]

[msg MSG_MORUGANA_SETUP_NAKAN [Morgana]]
[s][bup 0 3 0 0 0]So you're going to Nakano Broadway[n]with Futaba...[n][w][e]
[s]I wonder what kind of place that is?[n][w][e]

[msg MSG_MORUGANA_SETUP_REQUE [Morgana]]
[s][bup 0 3 0 0 0]We're supposed to be heading to[n]Chinatown with Ryuji today.[n][w][e]
[s]Let's head over to the rendezvous[n]point so we don't get lost.[n][w][e]

[msg MSG_MORUGANA_SETUP_REQUE_2 [Morgana]]
[s][bup 0 3 0 0 0]Ooh, today we're going to the[n]buffet with Lady Ann, right?[n][w][e]
[s]I just hope we can eat something[n]other than beans this time...[n][w][e]

[msg MSG_MORUGANA_SETUP_REQUE_3 [Morgana]]
[s][bup 0 3 0 0 0]We're going to Destinyland[n]with Lady Ann today, right?[n][w][e]
[s]I'm so excited... Let's make[n]sure we're not late.[n][w][e]

[msg MSG_MORUGANA_SETUP_REQUE_4 [Morgana]]
[s][bup 0 3 0 0 0]Didn't we promise we'd go to[n]Meiji Shrine with Yusuke? Come on,[n]let's make sure we're not late.[n][w][e]

[msg MSG_MORUGANA_SETUP_REQUE_5 [Morgana]]
[s][bup 0 3 0 0 0]We promised Makoto we'd go to[n]Chinatown with her today, right?[n]Let's eat a ton of food![n][w][e]

[msg MSG_MORUGANA_SETUP_REQUE_6 [Morgana]]
[s][bup 0 3 0 0 0]We promised Makoto last night we'd[n]go to Dome Town with her today.[n][w][e]
[s]Aren't amusement parks just so[n]excited? Let's not be late![n][w][e]

[msg MSG_MORUGANA_SETUP_REQUE_7 [Morgana]]
[s][bup 0 3 0 0 0]We're supposed to be going to[n]Akihabara with Futaba, remember?[n][w][e]
[s]I feel like it'll be crowded[n]because of the holiday... She'll[n]be okay this time... right?[n][w][e]

[msg MSG_MORUGANA_SETUP_REQUE_8 [Morgana]]
[s][bup 0 3 0 0 0]Hey, we promised Haru we'd[n]go get sushi with her today.[n][w][e]
[s]...And you better let me have[n]some this time![n][w][e]

[msg MSG_MORUGANA_SETUP_REQUE_9 [Morgana]]
[s][bup 0 3 0 0 0]We're supposed to be grabbing[n]monjayaki with Haru in Tsukishima.[n][w][e]
[s]Come on, let's head out. We[n]don't want to keep her waiting.[n][w][e]

[msg MSG_MORUGANA_SETUP_MOVIE [Morgana]]
[s][bup 0 3 0 0 0]We're supposed to be meeting[n]Ryuji for a movie. Let's head[n]over to our rendezvous point.[n][w][e]

[msg MSG_MORUGANA_SETUP_MOVIE_2 [Morgana]]
[s][bup 0 3 0 0 0]We're watching a movie with[n]Lady Ann today![n][w][e]
[s]We can't afford to let her wait.[n]Let's head over to the meeting point.[n][w][e]

[msg MSG_MORUGANA_SETUP_MOVIE_3 [Morgana]]
[s][bup 0 3 0 0 0]We promised to meet Yusuke for[n]a movie. Let's head over to[n]the rendezvous point.[n][w][e]

[msg MSG_MORUGANA_SETUP_MOVIE_4 [Morgana]]
[s][bup 0 3 0 0 0]We're supposed to be seeing a[n]movie with Makoto today. Let's[n]get out of the house, okay?[n][w][e]

[msg MSG_MORUGANA_SETUP_MOVIE_5 [Morgana]]
[s][bup 0 3 0 0 0]Don't you remember promising[n]Futaba that you'd watch a movie[n]with her? Stop standing around![n][w][e]

[msg MSG_MORUGANA_SETUP_MOVIE_6 [Morgana]]
[s][bup 0 3 0 0 0]Aren't we going to watch a[n]movie with Haru? Let's head[n]over to the meeting point.[n][w][e]

[msg MSG_SPOT_OPEN_KANDA]
[s]You can now go to [clr 1]Kanda[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_SHINJUKU]
[s]You can now go to [clr 2]Shinjuku[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_AKIHABARA]
[s]You can now go to [clr 2]Akihabara[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]

[msg MSG_SPOT_OPEN_INOKASHIRA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Inokashira Park[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]

[msg MSG_SPOT_OPEN_OGIKUBO]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Ogikubo Ramen[clr 27].[n][w][e]
[s]You can also invite people[n]who may enjoy eating ramen[n]to hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_ODAIBA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Odaiba Seaside Park[clr 27].[n][w][e]
[s]You can also invite people[n]who may like such parks to[n]hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_UENO]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Ueno Museum[clr 27].[n][w][e]
[s]You can also invite people[n]who may enjoy art museums[n]to hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_TSUKISHIMA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Tsukishima Monja[clr 27].[n][w][e]
[s]You can also invite people[n]who may enjoy eating monjayaki[n]to hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_HARAJUKU]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Harajuku Takenoko Street[clr 27].[n][w][e]
[s]You can also invite people[n]who may enjoy Takenoko Street[n]to hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_TYUKAGAI]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Motomachi Chinatown[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]

[msg MSG_SPOT_OPEN_MAIHAMA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Maihama Destinyland[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Asakusa[clr 27].[n][w][e]
[s]You can also invite people who may[n]enjoy the Skytree or Nakamise Street[n]to hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_IKEBUKURO]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Ikebukuro Planetarium[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]

[msg MSG_SPOT_OPEN_MEIJIJINGU]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Meiji Shrine[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]
[s]Furthermore, you can go by[n]yourself to pay homage to[n]the shrine if you wish.[n][w][e]

[msg MSG_SPOT_OPEN_SUIDOUBASH]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Suidobashi Dome Town[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]

[msg MSG_SPOT_OPEN_SHIBUYA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Shibuya Wilton Hotel[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]

[msg MSG_SPOT_OPEN_GINZA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Ginza Sushi Bar[clr 27].[n][w][e]
[s]You can also invite people who[n]may enjoy eating expensive sushi[n]to hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_JINBOCHO]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Jinbocho Book Town[clr 27].[n][w][e]
[s]You can also invite people[n]who may like it there to[n]hang out with you.[n][w][e]
[s]Furthermore, you can go by[n]yourself for some shopping[n]if you so desire.[n][w][e]

[msg MSG_SPOT_OPEN_ICHIGAYA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Ichigaya Fishing Pond[clr 27].[n][w][e]
[s]You can also invite people[n]who may enjoy fishing to[n]hang out with you there.[n][w][e]
[s]Furthermore, you can go by[n]yourself and try your hand at[n]fishing if you so choose.[n][w][e]

[msg MSG_SPOT_OPEN_SHINAGAWA]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Shinagawa Aquarium[clr 27].[n][w][e]
[s]You can also invite people[n]who may enjoy the aquarium[n]to hang out with you there.[n][w][e]

[msg MSG_SPOT_OPEN_NAKANO]
[s]You now have information[n]on a new hangout spot:[n][clr 2]Nakano Commerce Building District[clr 27].[n][w][e]
[s]You can also invite people[n]who may enjoy that location[n]to hang out with you there.[n][w][e]

