[msg MSG_000_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Eu estive esperando por voce.[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Estamos introduzindo um novo regime para[n]Sua reabilitacao na forma de[n]Desafio batalhas.[n][f 1 3 65535][w][e]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][f 4 24 0 3 6 36 3 100][vp 8 0 0 2 65535 0]Para esses ensaios, permitiremos cognicoes[n]de seus camaradas para lutar ao seu lado.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Dependendo dos seus resultados em combate,[n]voce recebera alguma forma de[n]compensacao por seus esforcos.[n][f 1 3 65535][w][e]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][f 4 24 0 3 6 36 3 100][vp 8 0 0 4 65535 0]Voce deveria provar bem-sucedido, existe[n]sem duvida que voce sera recompensado[n]e fortalecido no corpo e na mente.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Nos preparamos um estagio especial[n]para voce passar por esta parte do seu[n]reabilitacao.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Por favor, aproveite esta oportunidade para[n]demonstrar os alcances mais distantes[n]da forca que voce ganhou agora.[n][f 1 3 65535][w][e]

