[msg MSG_000_0_0 [詩]]
[s][vp 8 0 0 0 65535 0]Voce caiu para a terra e sua vida[n]foi roubado. Voce nem aprendeu[n]o nome de seus companheiros ladroes.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Voce que perdeu na aposta de seu[n]Vida e desperdicio como uma engrenagem dos fortes.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]A reabilitacao nao foi cumprida e[n]a falsa desonra se tornou um verdadeiro[n]notoriedade...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Entao, o jogo acabou...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Que fim verdadeiramente tolo...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [詩]]
[s][vp 8 0 0 0 65535 0]Voce caiu para a terra e sua vida[n]foi roubado. O caminho para[n]A reabilitacao tambem nao foi cumprida.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]A falsa desonra se tornou um verdadeiro[n]notoriedade. A alma da justica sera[n]Contado como insanidade de um pecador.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]O heroi finalmente nao conseguiu dar o seu[n]choro vitorioso e desaparece como uma equipamento[n]dos fortes...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Entao, o jogo acabou...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Assim como o sucesso estava ao seu alcance...[n][f 1 3 65535][w][e]

[msg SYS_004_0_0]
[s][vp 8 0 0 0 65535 0]O que voce deseja fazer?[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Voltar para uma semana antes[e]
[s]Retornar a tela do titulo[e]

[sel SEL_006_0_0 top]
[s]Reinicie a batalha[e]
[s]Voltar para um quarto seguro anterior[e]
[s]Reinicie a infiltracao[e]
[s]Retornar a tela do titulo[e]

[sel SEL_007_0_0 top]
[s]Reinicie a batalha[e]
[s]Voltar para um quarto seguro anterior[e]
[s]Voltar para uma semana antes[e]
[s]Retornar a tela do titulo[e]

[sel SEL_008_0_0 top]
[s]Reinicie a batalha[e]
[s]Voltar para um quarto seguro anterior[e]
[s]Retornar a tela do titulo[e]

[sel SEL_009_0_0 top]
[s]Voltar para um quarto seguro anterior[e]
[s]Reinicie a infiltracao[e]
[s]Retornar a tela do titulo[e]

[sel SEL_010_0_0 top]
[s]Voltar para um quarto seguro anterior[e]
[s]Voltar para uma semana antes[e]
[s]Retornar a tela do titulo[e]

